### ISSUE TITLE
Creating a new character sometimes irradiates them.

### ISSUE THREAD

**Issue by tivec** [CleverRaven/Cataclysm-DDA#35463]
# Describe the bug
Since build 9883, creating characters can sometimes result in a character spawning with 200-2000 points of radiation. This also seems to save with templates.

# Steps To Reproduce

1. Create a new world.
2. Create a new character, choose any options.
3. Enter the world and check @ screen for radiation level. Stats are also reduced to 0.

# Expected behavior

Normally, I don't expect my characters to start with 0 stats and radiation poisoning (though it could be a good scenario!)

# Screenshots

# Versions and configuration

<- OS: MacOs
    - OS Version: Name: Mac OS X; Version: 10.15; Build: 19A602; 
- Game Version: 0.D-9308-g1d6366e688 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    DinoMod [DinoMod],
    Hydroponics [hydroponics],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks],
    Necromancy [necromancy],
    sees-player icon, retrodays [sees_player_retro],
    No Fungal Monsters [No_Fungi],
    Classes and Scenarios Mod [more_classes_scenarios],
    Fuji's Military Profession Pack [fuji_mpp],
    Sleep Deprivation [sleepdeprivation],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

**Comment by scalpelenema** [comment]
can confirm. it aslo happens with default mods only. debian linux

**Comment by LeeMartin77** [comment]
> can confirm. it also happens with default mods only. debian linux

I've noticed the same thing on the same platform. I think I've also seen that the radiation seems to drop from 2,000 to 200 after the first movement.

**Comment by mlangsdorf** [comment]
okay, I'll look into it.

**Comment by BX442** [comment]
Windows 10
I compiled it myself.
After creating the character, I noticed a debate on the characteristics, the description indicated that I have 20 units of radiation

_Translator, I'm sorry :)_

**Comment by mlangsdorf** [comment]
Whoops!  I moved some code around and missed one line.  Should be fixed shortly.
