### ISSUE TITLE
Export version number to clipboard for experimental

### ISSUE THREAD

**Issue by Funguss** [CleverRaven/Cataclysm-DDA#35473]
Writing out the version number is hell compared to writing what build you're using. I'm dubious about how useful it is anyway, but if it is, having it easy to obtain is important.  I imagine it's on bug report text files, and I know it's on the main screen, but beyond that it's invisible, annoying to copy and easy to typo. This could all be addressed by having an option on the main or debug menu that sends the version number to the clipboard. I imagine these are the best places for them, plus something on the main menu maybe, but so long as it's documented in the bug report template here then it's probably fine to stick it somewhere ungodly.

As I have no idea how useful it is compared to the build number I'd also suggest exporting that to clipboard too, all nicely formatted with bullet points, colons, carriage returns, whatever. If this stuff is useful then making it convenient to read and provide should be worth it.
e.g:

- Version:	`0.D-9308-g1d6366e`
- Build: 	`Build #9886`

Nice, huh?

**Comment by ZhilkinSerg** [comment]
Game itself knows nothing about its build number (it is possible to add a file with that info during the build process, but it requires changes on build scripts on a build machine, not in this repo).

You can already dump game version (and other useful info) using "Debug - Info - Generate game report" menu - it will be properly formatted to be used in issues. Issue template tells you about that.

**Comment by Funguss** [comment]
Aha. I see that now, I got that mixed up with "check game state" which led me to getting frustrated and giving up on it. I dunno if that was just me or if there's anybody else who'll get those two mixed up. Had I known the correct option copies to the clipboard I'd have likely worked out I had the wrong option and looked a bit harder, so it might be worth mentioning that in to the issue template?

**Comment by ZhilkinSerg** [comment]
Yeah, maybe we need to update issue template.
