### ISSUE TITLE
Crafting Bodkin Bolt interupted due to not having a "none" 

### ISSUE THREAD

**Issue by Orange01gaming** [CleverRaven/Cataclysm-DDA#35493]
# Describe the bug

My crafting gets interrupted almost right away due to a lack of a material called a "none"

# Steps To Reproduce

-Try to craft a bodkin bolt. I used sinew, scrap metal, plank, and plastic bag
-Get interrupted

# Expected behavior

The item crafts as usual.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-9271-g17dd261 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    PKs Rebalancing [PK_REBALANCE],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Mutant NPCs [mutant_npcs]
]

**Comment by sdp0et** [comment]
I don't know if it's related, but I noticed a few days ago that there is a "none" at the bottom of my inventory.  You can borrow it if you like.
![image](https://user-images.githubusercontent.com/5922308/68977233-669d0000-07bd-11ea-9f84-4ca950767604.png)

**Comment by Orange01gaming** [comment]
Thanks for nothing ;)

**Comment by Night-Pryanik** [comment]
Anyone encountered this bug throughout year and a half?
