### ISSUE TITLE
Android Back Button for Keyboard Gone and Text Wrapping in Home Screen

### ISSUE THREAD

**Issue by ChrispyChris** [CleverRaven/Cataclysm-DDA#35496]
# Describe the bug
I loaded up a couple of the experimental builds to make sure it wasn't just the latest one: 9895, and it's not exclusive. On the experimental version when I load the game, the phone would normally leave the virtual home button, back button, and recent apps button on the far right side of the screen, that's how I would pull up the keyboard. After the splash screen, they disappear and I'm brought to the main menu where I can only use the virtual joystick. You can also see some text being cut off and wrapped.

Virtual buttons on phone not being displayed. Screen doesn't seem to fit the game like version from Play Store. 

# Steps To Reproduce
Load up an experimental build on Android. 
I'm on Google OG Pixel.

# Expected behavior
Virtual buttons remain on the phone's screen and text fits completely. 

# Screenshots
![Bp3WHxF_d](https://user-images.githubusercontent.com/13801530/68753664-48b37d80-05ba-11ea-8098-a5bde390baad.jpg)
![S4i07eH_d](https://user-images.githubusercontent.com/13801530/68753694-50732200-05ba-11ea-9dcb-3cf4552a0fcf.jpg)
![9NSPyRs_d](https://user-images.githubusercontent.com/13801530/68753704-5537d600-05ba-11ea-9ae3-ea4662cf9cb0.jpg)
![tR47UNF_d](https://user-images.githubusercontent.com/13801530/68753718-5963f380-05ba-11ea-87b4-1c30ae810b6f.jpg)

https://i.imgur.com/tR47UNF.png
https://i.imgur.com/9NSPyRs.png
https://i.imgur.com/S4i07eH.png
https://i.imgur.com/Bp3WHxF.png

Link to imgur album: https://imgur.com/a/U6yLZ0H

# Versions and configuration
9895 and Google Play Store version.

**Comment by ZhilkinSerg** [comment]
Could be caused by https://github.com/CleverRaven/Cataclysm-DDA/pull/34841.

Please try https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-jenkins-b9780 (first version prior to #34841).

**Comment by ChrispyChris** [comment]
> Could be caused by #34841.
> 
> Please try https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-jenkins-b9780 (first version prior to #34841).

This was the issue, although the splash screen on linked version was very weird haha. 

So it seems this is intentional, but I'm not sure how it's good as it messes up some text and doesn't allow player to bring up keyboard. 

Will I just need to change the code myself in each experimental release, or will this get fixed in master?

**Comment by ZhilkinSerg** [comment]
Virtual buttons do not exist on all device models, so we need to add configuration option to toggle that screen setting.

**Comment by ChrispyChris** [comment]
Gotcha, well I would help if I knew how to program for Android, but hopefully this isn't hard for you all to do! Thanks for figuring it out.

**Comment by ZhilkinSerg** [comment]
Try installing and running this APK - https://www.dropbox.com/sh/oi4mrpfbwyzayqh/AABWAcefJ4qCH2NWtYyXPo12a?dl=0. It has same app identifier, but signed by a different key than versions on Playstore and Github, so you would need to uninstall an existing version first, so make sure to backup your saves.

**Comment by ChrispyChris** [comment]
> ![Screenshot_2019-11-19-16-48-13-554_com cleverraven cataclysmdda](https://user-images.githubusercontent.com/16213433/69151958-b72d9980-0aec-11ea-9c3a-dca09f51e354.png)
> Try installing and running this APK - https://www.dropbox.com/sh/oi4mrpfbwyzayqh/AABWAcefJ4qCH2NWtYyXPo12a?dl=0. It has same app identifier, but signed by a different key than versions on Playstore and Github, so you would need to uninstall an existing version first, so make sure to backup your saves.

Which APK in that Dropbox do you want me to use? There are two in there.

**Comment by ZhilkinSerg** [comment]
Does not matter - they are basically the same regarding this "Force fullsceen" option.

**Comment by ChrispyChris** [comment]
> Does not matter - they are basically the same regarding this "Force fullsceen" option.

That worked for me! When will that update be consistent in the experimental builds so I don't have to worry about staying up to date?
