### ISSUE TITLE
No NPC Needs: Plant mutation leads to obesity

### ISSUE THREAD

**Issue by Funguss** [CleverRaven/Cataclysm-DDA#35494]
NPCs with roots go and sleep outside, which is nice. However, the more time they spend rooted the fatter they get. I'm guessing this might be an issue with players, too, though I assume it's manageable with detachable vines or a simple exercise bike. 

# Steps To Reproduce

1. Spawn NPC with the plant mutation class.
2. Spend a few months doing as you do.
3. Watch them grow into a mighty oak!

# Expected behavior

This seems like an unintended effect, and one that's unmanageable as far as I can see. If heart failure at high obesity is a thing then there may be a big issue here. It seems reasonable that an NPC would only absorb what they need, to a maximum of overweight at least. Obese seems like overkill. It could be modified by personality I guess, though that should be exposed somehow if it is the case.

# Screenshots

![image](https://user-images.githubusercontent.com/57632331/68742421-0ef96b80-05e8-11ea-82a0-c185330fdccd.png)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-9343-geb3c2fd [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Garden Pots [growable-pots],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    No Rail Stations [No_Rail_Stations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Roadheader and other mining vehicles [Heavy miners],
    Disable NPC Needs [no_npc_food],
    No Fungal Monsters [No_Fungi]
]

# Additional context

If it's not already a feature it might be good to reduce the food consumption for base camp tasks based on certain mutations and CBMs that an NPC has.

**Comment by Saint-of-Grey** [comment]
Oh dear... I totally forgot to include a check for if the character had when I redid plant nutrition...
