### ISSUE TITLE
CROWS turrets are not affected by Directional EMP CBM

### ISSUE THREAD

**Issue by MrOlaf** [CleverRaven/Cataclysm-DDA#35502]
# Describe the bug

The new CROWS turrets are not affected by Directional EMP CBM and they should be shut down instantly it is used.

# Steps To Reproduce

1. Set a player, preferably with a Cloak CBM, next to a CROWS turret
2. Use Directional EMP CBM on the turret
3. Turret is still alive and not disabled
4. For comparison repeat the same steps with a laser turret

# Expected behavior

Turret should be shut down after Directional EMP CBM is used on it.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-9282-g4c43c0d (tiles)
 - Graphics version: [Tiles]
 - Mods loaded: dda, disable NPC needs

**Comment by LaVeyanFiend** [comment]
Cannot be confirmed.
![image](https://user-images.githubusercontent.com/51099123/68996429-e2ec1d80-0867-11ea-92db-a417bc3f8fda.png)

**Comment by MrOlaf** [comment]
How is it about diagonal tiles? I seem to remember I had the issue on a diagonal.

**Comment by Fris0uman** [comment]
Just tested it and it works from every direction as long as you stand next to the turret

**Comment by MrOlaf** [comment]
Thanks for the effort. I really thought i was on to something here ☹️ oh
well at least it was a learning opportunity

**Comment by Night-Pryanik** [comment]
Should be closed then?

**Comment by MrOlaf** [comment]
Yes, please.
