### ISSUE TITLE
Tamed cow spontaneously despawning

### ISSUE THREAD

**Issue by Solusphere** [CleverRaven/Cataclysm-DDA#35513]
# Describe the bug

I have a pet cow. It consistently despawns for no apparent reason.

# Steps To Reproduce

1. Load the provided save.
2. Continue the crafting job in progress.
3. Most of the time, by the time the job is finished, the cow has despawned. If not, it will despawn in front of you within a couple minutes. Spawning a clairvoyance artefact confirms that the cow hasn't simply moved out of view, but has in fact ceased to be.

# Expected behavior

I expect my cow to not suffer spontaneous complete existence failure.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-9308-g1d6366e [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Folding Parts pack [deoxymod]
]

**Comment by Solusphere** [comment]
[Moravia.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3844889/Moravia.zip)

**Comment by Solusphere** [comment]
Upon further experimentation, IMMEDIATELY interrupting the crafting job (which takes a couple tries) stepping out of the window to the left, and waiting for an hour seems to placate whatever mad god is responsible for all this, allowing the cow to survive. Possibly a pathfinding bug from the cow trying and failing to enter the window?

**Comment by davidpwbrown** [comment]
Cows eat crops.

**Comment by Solusphere** [comment]
> Cows eat crops.

Ah, of course. That rules that out as a cause. I will note that I haven't had the issue recur after I managed to get the cow inside my house. However, the original issue is still very easily replicable using the save I provided.

**Comment by BevapDin** [comment]
In my tests, the does not despawn, but simply wanders of. In one test it was far to the south of the map after the crafting finished.

In another test, I spawned a clairvoyance artefact and moved into the shadow (so the cow could not see me). After waiting a few hours (!), the cow started to wander around (eating the crops). It also moved more and more away from it's starting point (away from the house).
