### ISSUE TITLE
can we have advanced inventory window wider?

### ISSUE THREAD

**Issue by jarmush** [CleverRaven/Cataclysm-DDA#35516]
can we have wider inventory window? or at least have an option to set its width?
long item names don't fit, but we have a lot of useless space on each side.

![изображение](https://user-images.githubusercontent.com/6452938/68838418-966dda00-06cf-11ea-9dae-07437ec0b395.png)

**Comment by Night-Pryanik** [comment]
Should it overlap sidebar, or should it fit window width minus sidebar width?

**Comment by jarmush** [comment]
IMO sidebar should be visible, so 2nd would be ok

**Comment by Nekatydaerla** [comment]
On low resolution (1280x1024) it takes up whole screen overlapping sidebar, please don't change that.

**Comment by Night-Pryanik** [comment]
I can easily make AIM fit the whole screen:

This is an example of 1840x976 screen
![изображение](https://user-images.githubusercontent.com/11132525/68843802-274db100-06e2-11ea-92fe-5db8d876554b.png)

**Comment by snipercup** [comment]
I prefer to have the sidebar visible. I support this idea.

**Comment by Funguss** [comment]
Is it possible to have multiple settings controlled via an interface setting? That way peeps can have whatever style they want.

**Comment by Night-Pryanik** [comment]
> Is it possible to have multiple settings controlled via an interface setting?

Of course it is possible. It just involves significantly more coding rather than setting some fixed value.

**Comment by Funguss** [comment]
Uhh... Damn. Well, I don't know if it's worth it as an option in that case. I say go with whatever you think is best

**Comment by Night-Pryanik** [comment]
Actually it was easier than I thought, so I implemented "fullscreen" - "sidebar visible" toggle in options.

**Comment by Nekatydaerla** [comment]
Thank you! I can see why people might want sidebar if they have the space, but on old 4:3 monitor that would be bad.
