### ISSUE TITLE
Compact suppressor is much worse version of standard suppressor now. 

### ISSUE THREAD

**Issue by SirPendrak** [CleverRaven/Cataclysm-DDA#35527]
# Describe the bug

Standard supressor is 0,16l, compact is BIGGER and occupies 0,25l of space. 
Other than that, standard one is more effective at silencing shots, and makes shooting more comfortable and can be installed on rifles, but theese virtues are fine. 

# Steps To Reproduce

Compare theese two items.

# Expected behavior

Compact suppressor being smaller than standard one. Standard one used to be 0,5l big. 
The new 0,16l volume is probably based on some real-life example of common suppressor, but I dont think its good to give every weapon and weapon-oriented item in game their exact real volume, because, like in this example, adding long suppressor at the end of the firearm makes it much more unwieldy IRL and hard to carry in backpack etc. than it would seem from just flat 0,16 increase in volume.

**Comment by ymber** [comment]
We need a load of different items for suppressors. I modeled it on a Saker ASR 556K so it shouldn't work on most things it works on. Right now the things to sort out for suppressors are handling subsonic projectiles properly and fixing the items. The second is all in JSON and it would be pretty easy for someone with a modicum of weapons knowledge and some research time.
