### ISSUE TITLE
Feature request GUI HP colour bars change colour depending on burns and/or frostbite?

### ISSUE THREAD

**Issue by TechyBen** [CleverRaven/Cataclysm-DDA#35520]
**Is your feature request related to a problem? Please describe.**  
I'm pretty useless at noticing info spams (though I do use the info on the right on the GUI for many notifications that are very important). One I often miss, as it comes/goes depending on many factors, is "frostbite". In that, I forget to check if it's gone/come back, when transitioning between areas etc, or if fast/quickly acting weather.

This can result in annoying "broken limbs" due to not getting back to safety quickly enough, and the damage just multiplying.

**Describe the solution you'd like**  
The health bars to change colour depending on frostbite and/or severity of coldness/heat (oh, just realised, could do the opposite for high temp!). Could just be part of the HP bar, or just the names, thus the health bars current behaviour would not change. But the HP "arms" or "torso" would go orange for burns, and light blue for frostbite. (though this would be truncated from arms/hands and legs/feet, it's close enough to stop constant checking the player status / @ screen.)

**Describe alternatives you've considered**  
Not sure where else to place this in the GUI. I know I can press @ to see it, but doing so every 5 mins [in game time, which is seconds in real life play] or so to see if I'm successful in the fire/room/clothes I keep changing to mitigate it, is a bit annoying. Hiving it clear, but not cluttering the GUI is nice.

**Additional context**  
Spring start is often very cold, and being able to understand when I can warm up, run out and get some materials, run back and warm up again, might smooth out some gameplay loops (without needing any rebalancing/gaming/save scumming :P ). I understand the "your arms will be frostbitten in 1 hour" etc, but just seeing it transition on screen might help me a bit.

Feel fine to nuke this idea from orbit if it's really that bad. ;)

**Comment by KorGgenT** [comment]
ok, so maybe checking for certain effects on your limbs and change the color to suit
