### ISSUE TITLE
Weather/Wind doesn't change.

### ISSUE THREAD

**Issue by jasonmbrown** [CleverRaven/Cataclysm-DDA#35535]
# Describe the bug
Weather has not changed for me, in 180 days (I have to manually fill my vehicle with dirty swamp water every so often). Its always Clear, 

# Steps To Reproduce

There's not much I can say about how to reproduce, other then just play?

# Expected behavior
I would expect weather to be changing.

# Versions and configuration
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-9369-ge612365 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs],
    More City Locations [cityside],
    More Locations [more_locations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks],
    Prevent Zombie Revivication [no_reviving_zombies],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Simplified Nutrition [novitamins],
    No Fungal Monsters [No_Fungi]
]

**Comment by RosieMcCattail** [comment]
Can confirm. Weather is always clear, wind direction is stuck to SE and the wind is always calm.

**Comment by TechyBen** [comment]
Yeah... I'm on day 13, and had no rain/snow etc... thought it was a new weather setting/system (been out of the game/loop for a while). So if it's not just a dry spell in spring, then it's really really dry!

**Comment by davidpwbrown** [comment]
The new rain system will mean less rain, a lot less.

#34515 gave the reasoning for this, and it is sound.

Although - unfortunately it kinda broke wind, I will need to fix that. ( hah, broke wind... )
This may account for the perceived lack of change in the weather, I understand the reasoning behind the change - that most precipitation will be too light to matter, but it does kinda make the weather system have the *perception* of being unchanging now...

**Comment by jasonmbrown** [comment]
... I mean im in autumn and it has not rained once, that I am aware of? Are you sure about it working?

**Comment by davidpwbrown** [comment]
Yeah.... it does feel wrong, but the data seems to support the fact that most precipitation irl would be too light to matter in-game by our current standards of what happens in-game when the weather is "raining"
The best solution would be more intermediate categories of rain, " very light drizzle " "Light drizzle" etc.

**Comment by DatMeg** [comment]
In a 30-day cycle, it took until Autumn 6 to have any rain, and it was very brief. Perhaps an hour or two.

**Comment by TechyBen** [comment]
" The wettest month of the year is June with an average rainfall of 3.38 Inches."
In game, do we need the granularity of real life? Or can we give the player/char 6 days of 1/2 an inch in June (as an example). Yes, if we averaged/realitied it out, they'd get an unnoticeable drizzle of 1/3 inch every day in June... :P

Here in the UK... we very much get a lot of rain. So playing a game where it's suppose to be real life, and it never rains, is strange. XD

**Comment by kevingranade** [comment]
Instead of throwing the reality basis out the window, we can look into having both rainfall and rain duration targets we meet so that rain is both an appropriately scaled resource and hazard, and it "feels like" it has the right frequency of occurence.
