### ISSUE TITLE
Both variants of Northrop robots drop fully functional, innactive manhacks that havent been used yet, contrary to their descrieption of frying manhacks in case of "death" 

### ISSUE THREAD

**Issue by SirPendrak** [CleverRaven/Cataclysm-DDA#35530]
# Describe the bug

Both Northrops drop innactive versions of unusued manhacks. Their description mentions EMP emitter on board designed to fry manhacks.
They probably should drop broken variants. 
So terrorist cannot get easy acces to explosive materials or nuke when they destroy one.

# Versions and configuration

Build 9898
Vanilla game, no mods that affect robots

**Comment by Maleclypse** [comment]
I tried seeing if  an emp blast would turn inactive manhacks into broken manhacks, it does not.

**Comment by MrOlaf** [comment]
I always figured it would disable the active manhacks in the EMP blast  ike the active grenade hack next to it.

**Comment by SirPendrak** [comment]
It depends on the dyrenght of the EMP, and stronger EMP can probably permamently destroy electronics.

**Comment by kevingranade** [comment]
This would be fine with a description update, I'm not at all sure that belongs in the description even if it does do it.
