### ISSUE TITLE
NPC dies when completing CBM installation

### ISSUE THREAD

**Issue by VVIITTAALLIIKK** [CleverRaven/Cataclysm-DDA#35559]
# Describe the bug
I tried to install the CBM in the NPC, the first three were installed normally, when the installation of the fourth CBM was finished, the NPC died and an error occurred:
 DEBUG    : NPC Bridget Lacroix, Bone Seer entered infinite loop.  Turning on debug mode
 FUNCTION : void game::monmove()
 FILE     : src/game.cpp
 LINE     : 4259

Upd: NPC dies one turn after
how to wake up from the auto-dock
Upd x2: NPC dies when install Metabolic Interchange or Joint Torsion Ratchet CBM
Upd (again): NPC dies when recharge bionic energy.
I gave her ethanol for recharge bionic energy (Ethanol Burner CBM) and she again dies with the same error (entered infinite loop)

# Versions and configuration

 - OS: Windows 7
 - Game Version: 0.D-9380-ge0332e1 [64-bit]; build: 9903
 - Graphics version: Tiles
 - Mods loaded: 
C.R.I.T Expansion Mod
Disable NPC Needs
Fuji's More Buildings
Icecoon's Arsenal
More Locations
Modular Turrets
SpeedyDex
Vehicle Additions Pack
Tanks and Other Vehicles
DeadLeaves' Fictional Guns

**Comment by Fris0uman** [comment]
What CBM did you install?

**Comment by VVIITTAALLIIKK** [comment]
Finger laser

**Comment by VVIITTAALLIIKK** [comment]
Metabolic Interchange or Joint Torsion Ratchet CBM

**Comment by Fris0uman** [comment]
Can you provide a save where the bug occurs? Because I just tried to install MI on an NPC and it didn't die.

**Comment by VVIITTAALLIIKK** [comment]
СMB and auto-dock attached
Take one 7z or rar:
https://yadi.sk/d/SmgEGcEQQRa3fA

**Comment by VVIITTAALLIIKK** [comment]
Upd (again)
NPC dies when recharge bionic energy.
I gave her ethanol for recharge bionic energy (Ethanol Burner CBM) and she again dies.

**Comment by Fris0uman** [comment]
It seems that having multiple power generation CBM on NPCs causes the infinite loop
