### ISSUE TITLE
More ways to recharge batteries/electronic devices

### ISSUE THREAD

**Issue by Termineitor244** [CleverRaven/Cataclysm-DDA#35564]
**Is your feature request related to a problem? Please describe.**  
Ever since the Battery overhaul in #29651 the electronical devices became more difficult to recharge, which is ok, this is the apocalypse, and its illogical to be able to trade batteries between different devices, but the baterry overhaul didn´t implement more natural ways in which the average survivor would logically be able to recharge its common devices (Cellphone and camera) as seen in #30378 and #30256

**Describe the solution you'd like**  
I have several ideas that could be implemented together or individually:

1._ **Power banks**, these things are pretty common in real life, and allow you to recharge your standard electronics (Cellphone, camera, tablets, etc) but they are nowhere seen in the game, they should be a semmi-common loot in houses and even zombies (I know I always carry one or two with me when I go out)

2._ The **Solar Backpacks** need to be able to work with your electronics, it just makes more sense that what they are right now, chargers for your CBM system, that are not really that useful if you really are in CBMs

3._ Being able to **transfer energy** between devices (Crafting something to do it) with some low skill in electronics and risk of blowing up, because, well, energy transmision is like the first topic you see in electronics

4._ Increase the amount of cars that have a recharge station or a **new car charger item** (More like cellphone charger), it doesn´t has to work with everything, but hey, almost everyone that I know has a simple recharger for their cellphone in their cars, something like this: [Link](https://www.amazon.com/AUKEY-Charger-Output-iPhone-Samsung/dp/B00M6QODH2)

**Describe alternatives you've considered**  
Suffer watching how I need to change of cellphone every day while my Solar Backpack just sits there, in a corner, doing nothing

**Additional context**  
I would do it if I had used github before, at least the power bank thing seems pretty easy, but I have no previous experience in this platform, and maybe I would need to do more work determining which specific devices could recharge with it

Also, sorry for any typos or misspellings, English is not my first language

**Comment by Funguss** [comment]
I've met a few people while traveling who have these roll up solar panels for charging phones and such. They look like a tablemat when rolled out and charge a phone in a couple of hours. Seems like these should exist, too.

**Comment by Termineitor244** [comment]
> 
> 
> I've met a few people while traveling who have these roll up solar panels for charging phones and such. They look like a tablemat when rolled out and charge a phone in a couple of hours. Seems like these should exist, too.

I agree, I have seen some too, and with the technology already in the game, it would not be weird to have them, we already have the Solar Backpack, so I just went with the option to enhance it, but both things seem fine to me, we need more common rechargers

**Comment by Inglonias** [comment]
It might be worth it to have more vehicles contain charging stations as a short term fix. After all, most cars these days have a USB port for charging phones.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/rework-solar-backpack-to-make-it-charge-smartphones-not-only-cbms/28227/1
