### ISSUE TITLE
Fire goes out when cooking

### ISSUE THREAD

**Issue by Sumguy62** [CleverRaven/Cataclysm-DDA#35572]
# Describe the bug

Fires started in stoves or fireplaces go out when trying to cook.

# Steps To Reproduce

1. Make a fire in a wood stove or fireplace with plenty of fuel. (Wizard Retreat scenario. have not tried to reproduce in others) 
2. Craft food.
3. It goes out before you finish every time.

# Expected behavior

Expected the fire to last long enough to cook.

# Screenshots
<img width="1331" alt="Screen Shot 2019-11-17 at 3 57 17 PM" src="https://user-images.githubusercontent.com/11052922/69014578-97b23780-0959-11ea-9e3a-7a837de404b6.png">
# Versions and configuration
 - OS: OSX 10.14.6
 - Game Version: 0.D-9380-ge0332e1 and 0.D-9422-g8d5b04e
 - Graphics version: Tiles
 - Mods loaded: <img width="389" alt="Screen Shot 2019-11-17 at 4 41 47 PM" src="https://user-images.githubusercontent.com/11052922/69014521-312d1980-0959-11ea-8ae2-42016043c9ec.png">

**Comment by Funguss** [comment]
Hmm... Has it been raining? The location might not have a roof though I'm not sure if that makes a difference currently. The way rooves are handled changed recently and I've not tried lighting fires in roofless buildings yet.

**Comment by Sumguy62** [comment]
nope. it was clear weather. it may be roofless, though.

**Comment by Funguss** [comment]
Nah, sounds like a bug then. It doesn't look like a problem for me, I just spawned in a couple of fireplaces and all logs burned away and left fires that lasted hours. Though I do have some smoking racks set up that have been going for around 24 hours, ticking very slowly down, that have stuck at 1hr for about 12 now. Maybe it's related. I'll post a bug report for it later if not.

**Comment by Sumguy62** [comment]
Did you try crafting using the fires?

**Comment by TychaiosIlithios** [comment]
Err, not a pro but last time I checked cooking fire worked differently. You don't put all wood in fire, cuz it just creates a huge fireball not longer burning (not by much). Instead near a fire you build a free to build designation thing named somewhat like firewood storage and during crafting your character automatically puts usable fuel from designated storage to burning fire.

**Comment by Sumguy62** [comment]
welp. this works. that's not intuitive at all. Still, it goes out before turning everything to ash, so I still think it's a bug.

**Comment by tivec** [comment]
Can you provide a save for when this happens so we can take a look?

**Comment by Funguss** [comment]
Alright, having tried to walk over a skylight I'm asked if  want to step on to the ledge. I'm guessing it lets everything through, not just light, and your fire was put out by rain.

**Comment by wapcaplet** [comment]
I cannot reproduce this in 0.E-5926-g a883429bdd using a fireplace with logs in it. After lighting the fireplace, I can craft several batches of scrambled eggs (taking more than 30 minutes), and the fire does not go out.
