### ISSUE TITLE
Dive knife is twice as dense as lead

### ISSUE THREAD

**Issue by BenlyAZ** [CleverRaven/Cataclysm-DDA#35571]
A dive knife has a volume of 0.01 L (10 cubic centimeters) and a weight of .23 kg (230 grams) for a density of 23g/cc. The density of pure lead in real life is 11.3g/cc.

1. Make a dive knife.
2. Observe its stats and see that it indeed has these values.

# Expected behavior

I would expect the knife to be either lighter or bulkier. 10 cubic centimeters of steel weighs 80 grams.

**Comment by Rivet-the-Zombie** [comment]
It would seem that the dive knife's size has never been updated since we got <250ml volume increments.
