### ISSUE TITLE
NPCs deconstructing vehicles explode from infinite loop

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#35586]
# Describe the bug

I told 2 NPCs to deconstruct vehicles in VDZ (armored car and flatbed truck). When I return from supply run, they get their brains exploded because they went into infinite loop.

# Steps To Reproduce

-load attached save;
-press "5" 7 or 8 times so you'll drive into  tile adjacent to shelter where VDZ is
-get error messages and exploding brains.

**Edit** - if you stop the vehicle and go there on feet they are fine and they just follow you around, not deconstructing. Maybe something with vehicle headlights lighting their work area?

# Expected behavior

NPCs not getting into loop and getting their brains out for the zombies to feast on.

# Versions and configuration

- OS: Windows 7 x64
- Game Version: 0.D-9483-ga3b0f0f [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

Happened on 9901, updated to 9911, same thing.

[crash-debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3858819/crash-debug.zip)
Save file was too big for attaching so here's [the link](https://drive.google.com/file/d/1OWGrzboIAwmRGdABeeMPS8pru-J81PDM/view?usp=sharing)

**Comment by davidpwbrown** [comment]
Yeah, out of bubble, back into bubble, this is a known limitation of letting them roam around doing activities, for a turn when they are loaded into bubble, the thing they are working on might not be in the bubble yet, causing the infinite loop, 

Got a few ideas on how to fix.

**Comment by Zireael07** [comment]
Just return early if the thing is not in the bubble yet?

**Comment by davidpwbrown** [comment]
Yeah, thats the simplest way, ideally id want to stash the activity smartly, then when the NPC is reloaded into bubble, pause for a few turns before resuming it, to give a chance for its targets to get loaded too.

**Comment by davidpwbrown** [comment]
Oh but this particular bug might be different - the OP says that when they *walk* towards the NPCs the NPCs are fine, but when driving towards them, they infinite loop, interesting...
