### ISSUE TITLE
Javelins are extremely tiny

### ISSUE THREAD

**Issue by BenlyAZ** [CleverRaven/Cataclysm-DDA#35582]
# Describe the bug

Javelins in-game are 70 cubic centimeters. Assuming they're more or less cylindrical, this would make them slightly smaller than a king-size Sharpie marker, which is not exactly my image of a javelin.

# Steps To Reproduce

1. Make a javelin.
2. It is very small.

# Expected behavior

Either a javelin should be considerably larger or it should be more properly called a pub dart.

**Comment by Zireael07** [comment]
I managed to find dimensions for a sport javelin:

> The size, shape, minimum weight, and center of gravity of the javelin are all defined by IAAF rules. In international competition, men throw a javelin between 2.6 and 2.7 m (8 ft 6 in and 8 ft 10 in) in length and 800 g (28 oz) in weight, and women throw a javelin between 2.2 and 2.3 m (7 ft 3 in and 7 ft 7 in) in length and 600 g (21 oz) in weight. The javelin has a grip, about 150 mm (5.9 in) wide, made of cord and located at the javelin's center of gravity (0.9 to 1.06 m (2 ft 11 in to 3 ft 6 in) from the javelin tip for the men's javelin and 0.8 to 0.92 m (2 ft 7 in to 3 ft 0 in) from the javelin tip for the women's javelin).

Also > [the grip] and can't be more than .31 inches larger than the diameter of the shaft

Therefore we can assume the javelin's height is 2.6m and the radius is 150 mm, trying to calculate the volume, be back soon...

**Comment by BenlyAZ** [comment]
I would suspect they should be shorter than that. These aren't competition javelins, they're combat/hunting javelins and as such portability is a concern. I would model them more towards a historical peltast's javelin, which was apparently "from 1.25 to 2.25 meters in length" (https://www.ancient.eu/Peltast/).

**Comment by FuelType-Memes** [comment]
> Therefore we can assume the javelin's height is 2.6m (260 cm) and the radius is 150 mm (15 cm), trying to calculate the volume, be back soon...
> 
> EDIT: 1.84×10^5 cm3 according to an online calculator, so 1.84×10^3 m3 = 1.84×1000m3 = 1840 m3... do I have too many zeroes? 😕

0.184m^3, thus 184L which is a lot. You are not actually calculating for a cylinder, more like 2 equal cones

**Comment by BenlyAZ** [comment]
Since it's made from a pointy stick (1.25 liters) and is 600g to the pointy stick's 900g, maybe shave it down to about 800cc to maintain that proportion?

**Comment by reed501** [comment]
If you assume we're not using olympic javelins to hunt deer then you can probably shrink the length down to ~1.25-1.5m in length. Your radius calculation must be wrong: 15 centimeters is 6 inches! That's a 1 foot wide spear being thrown?! More accurately the radius for a hunting javelin would be around 8-10mm. This makes our javelin somewhere in the range of .25 to .5 Liters, which is much more realistic in my opinion.

**Comment by DaviBones** [comment]
I suspect that "150 mm wide" was referring to the length of shaft covered by the grip, not the grip's thickness (a very reasonable misunderstanding). This is why reality checks are useful :grin:

**Comment by DaviBones** [comment]
Can't reproduce, actually. Both wooden and iron javelins are 1L in master, which roughly matches a 200 cm length by 1.1 cm radius cylinder, which is well within reason.

What version are you using? (This is why we have the template incidentally, please don't delete sections because you deem them unimportant, in the future)

**Comment by BenlyAZ** [comment]
My mistake! This is on latest experimental.

**Comment by DaviBones** [comment]
I just tested on latest experimental, and found that both types of javelins are 1L (and the file the item is defined in hasn't changed in a month).

Screenshot?

**Comment by BenlyAZ** [comment]
Okay, it's got to be a mod thing then. Mea culpa for not verifying that this was an issue in core. It's a More Survival Tools issue, seems like.
