### ISSUE TITLE
Vehicle Funnels can't fill tanks with water in rain

### ISSUE THREAD

**Issue by totoro0924** [CleverRaven/Cataclysm-DDA#35599]
# Describe the bug

Vehicle Funnels can't fill tanks with water in rain

# Steps To Reproduce

1. spawn a car 
2. install a funnel and vehicle tank (60L)
3. change weather to rain
4. wait
5. vehicle tank didn't filled with water

# Expected behavior

vehicle tank should filled with water

# Screenshots

![K-1](https://user-images.githubusercontent.com/57940121/69233778-e1f11e00-0bd0-11ea-977b-8d33d7dcd71e.jpg)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-9499-gd0db81d [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Bens GF recipes [Tolerate_This],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Makeshift Items Mod [makeshift],
    Mythological Replicas [nw_pack],
    Craftable Gun Pack [craftgp],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    EZ-Mode Medical [fast_healing],
    Hydroponics [hydroponics],
    NPC traits [npc_traits],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Mythical Martial Arts [MMA],
    Mutant NPCs [mutant_npcs],
    Alternative Map Key [alt_map_key],
    Crazy Cataclysm [crazy_cataclysm],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Mapgen Demo [mapgen_demo],
    Beta National Guard Camp [national_guard_camp],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks],
    Folding Parts pack [deoxymod],
    Necromancy [necromancy],
    [DP_MOD] Indicators: REMIX [DP_REMIX_INDICATORS],
    Battery Migration for Existing Games [Battery_Overhaul_Legacy_Mode],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Classic Roguelike Classes [RL_Classes],
    Classes and Scenarios Mod [more_classes_scenarios],
    Manual Bionic Installation [manualbionicinstall],
    Safe Autodoc [safeautodoc]
]

**Comment by RDru** [comment]
Is your tank in the same tile as funnel? It won't work otherwise.

**Comment by Funguss** [comment]
Has the tank got a different fluid in it already? Also won't work.

**Comment by totoro0924** [comment]
> 탱크가 깔때기와 같은 타일에 있습니까? 그렇지 않으면 작동하지 않습니다.

same
![K-1](https://user-images.githubusercontent.com/57940121/69233598-845cd180-0bd0-11ea-86f6-fe8b840de51d.jpg)

**Comment by totoro0924** [comment]
> Has the tank got a different fluid in it already? Also won't work.



> Has the tank got a different fluid in it already? Also won't work.
It's empty

**Comment by sdp0et** [comment]
How long do you wait? I thought I had this issue but found out in [#34515](https://github.com/CleverRaven/Cataclysm-DDA/pull/34515) that it was really just much slower.  And (this may not be accurate) I got the impression from that PR (or one of the linked ones) that not all "rain" is equall (they all use the same animation, but some sprinkle showers may not be enough to noticeably fill containers).

**Comment by totoro0924** [comment]
> How long do you wait? I thought I had this issue but found out in [#34515](https://github.com/CleverRaven/Cataclysm-DDA/pull/34515) that it was really just much slower. And (this may not be accurate) I got the impression from that PR or one of the linked ones that not all "rain" is equall (they all use the same animation, but some sprinkle showers may not be enough to noticeably fill containers).

Thanks to help.... I didn't think it would take this long.
