### ISSUE TITLE
Suggestion Favorite Inventory Items

### ISSUE THREAD

**Issue by jasonmbrown** [CleverRaven/Cataclysm-DDA#35591]
**Is your feature request related to a problem? Please describe.**  
Basically I would like some method of "Favoring" certain items in my inventory. 
Prioritizing them to be Last to get dropped when A bag rips, and excluding them from the Select all inventory items while dropping. Possibly always having them listed at the top of menus.
The main reason I ask for this, is simply to make things a little bit easier when your in the middle of a swarm, and your bag gets ripped. Or if your dropping items and your sick of Unselecting the same 12 items.

**Describe alternatives you've considered**  
The bag portion would only be useful until the bag mechanics get reworked (And you can just always have certain items in your pockets or pouches). 

However having the ability to flag inventory items Not to be selected with "select all" would still be useful for quickly dropping loot, without accidentally dropping your secondary weapon or your bandages and then not having them when your bleeding out from a horde 15 minutes later.

**Comment by ZhilkinSerg** [comment]
We already have this - see https://github.com/CleverRaven/Cataclysm-DDA/pull/29287
