### ISSUE TITLE
Not an issue, personal question for a stable build

### ISSUE THREAD

**Issue by TychaiosIlithios** [CleverRaven/Cataclysm-DDA#35594]
Hello sorry to disturb, I sorta kinda lost my old pc so wanted to ask for a good memory if anyone can hint a way to get latest version of this game --with turn still being six seconds--. I know that whole community is working tirelessly for the brighter tomorrow and old stuff shouldn't be holding back the creative spirit, but really really really nostalgia drives me to ask for it aaand explaining this game to newer geeks still works a bit better with it. So anyone with working memory - version hints?

**Comment by mkikt4743** [comment]
Launcher has an option for 'Stable', try that

**Comment by Funguss** [comment]
Or just download 0.A or whatever you're looking for from the releases page. https://cataclysmdda.org/releases/

**Comment by ZhilkinSerg** [comment]
Downloads are [here](https://cataclysmdda.org/releases/) and [here](https://github.com/CleverRaven/Cataclysm-DDA/releases/).

You [search](https://github.com/CleverRaven/Cataclysm-DDA/pulls?utf8=%E2%9C%93&q=is%3Apr+label%3A%22Game%3A+Mechanics+Change%22+%22turn+length%22+is%3Aclosed+) for a [pull request](https://github.com/CleverRaven/Cataclysm-DDA/pull/30253) that changed turn length. Search page for a merge commit using "merged commit" as search term and follow its [link](https://github.com/CleverRaven/Cataclysm-DDA/commit/55213a08266985ceb636d9c7434d552597e063c4).

![image](https://user-images.githubusercontent.com/16213433/69126694-d19a4f80-0ab9-11ea-82f3-2e20ef4a05d9.png)


There you will see which release it was merged in first:

![image](https://user-images.githubusercontent.com/16213433/69126810-17571800-0aba-11ea-8487-3488a740d176.png)

You can then follow release [link](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-jenkins-b9113) to go to release download page. Generally any builds prior to that would not contain changes from aforementioned PR.

Then you should decrease build number in URL by one (e.g. change it from 9113 down to 9112) until you hit an existing [page](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-jenkins-b9112) with desirable release.
