### ISSUE TITLE
Successfully picking residential door lock triggers alarm

### ISSUE THREAD

**Issue by Solusphere** [CleverRaven/Cataclysm-DDA#35596]
# Describe the bug

Despite successfully picking the lock on a door on the first attempt, an alarm sounded before I even opened the door.

# Steps To Reproduce

1. Walk up to the house shown in screenshot (and probably others.)
2. Pick lock.
3. Cover ears as alarm sounds.

# Expected behavior:

The grade of door that can be picked by an improvised lockpick to begin with shouldn't have the kind of security systems that can detect a successful lockpicking attempt. While it's theoretically possible to make such a system, having it on a civilian residence seems like overkill. Perhaps it could detect a FAILED lockpick attempt, but succeeding on the first try should bypass the alarm. Otherwise, what's the point? You may as well just smash the window.

# Screenshots

Apologies for the external links, my workplace filter doesn't play well with github uploads.
The house in question: https://i.imgur.com/7USZNTl.png
The alarm: https://i.imgur.com/3Qhxo54.png

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-9497-g86d409b [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Folding Parts pack [deoxymod]
]

# Additional context

**Comment by Night-Pryanik** [comment]
> While it's theoretically possible to make such a system, having it on a civilian residence seems like overkill.

You've encountered the _very rare_ case when owners of the house indeed installed such a system on their locks. Some `t_door_locked_alarm` terrains (locked wooden doors with an alarm) will trigger the alarm effect even on successful picking. So that's intended, and I'd say it's of no issue.

**Comment by kevingranade** [comment]
I agree, this is a reasonable thing to have happen. If someone wants to add more nuance and detail to doors they can, but I'm not going to leave an issue open about it, and it's certainly not a bug.
