### ISSUE TITLE
Chitinous plate mutations prevents using hoods

### ISSUE THREAD

**Issue by AntonDumov** [CleverRaven/Cataclysm-DDA#35603]
# Describe the bug

Items with flag HOOD does not provide warmth bonus to head if your character has chitinous plate mutation or furred plate mutations. It happens because mutation adds 10 encumbrance points to all body parts and in the [code](https://github.com/CleverRaven/Cataclysm-DDA/blob/f388e84dadf48478c077584074d328404d13f375/src/character.cpp#L6850) it checks that encumbrance points must be less than 10. I think it should check only points that gained from clothing, and ignore points from mutations.

# Steps To Reproduce

1. Make a player with Arachnid and Chitinous Plate mutations.
2. Wear any item with the HOOD flag, like a leather cloak.
3. If you check the warmth tab in the info panel, you can see that there is no bonus to head temperature.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-9499-gd0db81d [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    More Locations [more_locations],
    Urban Development [Urban_Development],
    Mutant NPCs [mutant_npcs],
    NPC traits [npc_traits],
    Zetsukaze's Hair Extensions! [zets_hair_extensions],
    Zet's Hair - More Locations [zets_hair_ext_more_locations],
    Hydroponics [hydroponics],
    Alternative Map Key [alt_map_key],
    Cars to Wrecks [cars_to_wrecks],
    Vehicle Additions Pack [blazemod],
    Folding Parts pack [deoxymod],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills],
    Roadheader and other mining vehicles [Heavy miners],
    No Rail Stations [No_Rail_Stations]
]

**Comment by SirPendrak** [comment]
"it should check only points that gained from clothing, and ignore points from mutations, **and CBMs**" I am not sure if w have lready hed-encumbring bionics, but htere might be ones in the future. And for consistency sake with other bodyparts.

**Comment by kevingranade** [comment]
So you have a spider shaped head now and the hood doesn't fit.  I'm not
convinced this is a problem.

**Comment by Amoebka** [comment]
The hood doesn't fit even when the clothes explicitly state that they accomodate mutated anatomy. Spider head or not, a cloak should be able to cover it.

**Comment by AntonDumov** [comment]
> So you have a spider shaped head now and the hood doesn't fit. I'm not convinced this is a problem.

Is there another way to warmth the spider head? Cause there is no headgear with the OVERSIZED flag, except earplugs.

**Comment by TKTKO** [comment]
There are some items that work for this. Turban and Headscarf both work and can have fur/wool lining added. I currently have a character with this exact setup and currently have both items lined and equipped. So it is possible, just difficult.
