### ISSUE TITLE
"Fall back!" or other such combat commands

### ISSUE THREAD

**Issue by Funguss** [CleverRaven/Cataclysm-DDA#35614]
**Is your feature request related to a problem? Please describe.**  

Currently, NPCs throng around the PC, pushing and shoving each other out the way and racing into the line of fire when they're out of ammo or holding a nice big stick. We can set a retreat zone, but this appears to be more of a rout zone as we have no actual way to order a retreat or set up defensive lines. There's no way to get your team to crouch down to use cover, scale walls (or even stepladders) or get the melee fighters to crouch down in front of the ranged, ready to face the horde while you and the crack shots pick off the shockers or spitters. It's a complete bloody shambles!

**Describe the solution you'd like**  
1. Defence zones. In their infancy it's enough that your NPCs just stand their until their morale breaks, but this should be expanded eventually. Currently it's near impossible to get them to stay in one place, especially if you have a few together. There's always one who can't sit still.
2. Order a retreat. NPCs should immediately disengage and flee to the nearest retreat point, pulling comrades out of the grips of zombies if they have the opportunity. If they're not freaked out or their personality is appropriate they should have a chance of ignoring you and fighting on, or doing their utmost to save a comrade. Until they realise you made the right call that is!
3. NPCs should be able to climb as you do, at the very least using stepladders.

Less immediate ideas:

4. Night watch, and sensitivity levels. Raise the alarm for every little sound? When you hear an enemy? When you see a zombie? Or hulk? Or NPC? Or... something else?
5. Silent commands. Not always available, only when in sight.
6. Radio pip commands, agreed ahead of time and would require the use of radios and earpieces.

The list goes on, I'm sure.

**Describe alternatives you've considered**  
Adding the ability to tie them up with rope like the dogs they are.

**Additional context**  
Currently NPCs really do behave like a group of thugs. With more options there should be more training and discipline. I'd love to see Marcus from the shelter go from fleeing at the first sight of a zombie to gritting his teeth and holding steady as the three hulks approach, with a single shotgun and enough shells to bring two down, three if he's lucky. And he's got the will to make that luck happen.

Currently he might shout "watch out for that hulk!" then dash at them with the makeshift hammer you just made for him. I mean, it's impressive, but...

**Comment by Night-Pryanik** [comment]
Related: #25780 and #30747.

**Comment by esotericist** [comment]
Notably, #30747 eventually got merged in the form of #30780, after kevin had to work on it a bit.

see: https://github.com/CleverRaven/Cataclysm-DDA/pull/30780#issuecomment-500717854

As for #25780, *some* of that is in with the new `C` menu, but there's definitely room for more functionality especially where faction camps are concerned.
