### ISSUE TITLE
NPCs half repair vehicles

### ISSUE THREAD

**Issue by Funguss** [CleverRaven/Cataclysm-DDA#35612]
Currently NPCs are held to higher standards than the PC when using welding rigs. If they have  to move out of the line of sight or too far from the rig they're unable to use it, reducing the combined utility of welding rigs and NPCs.

# Steps To Reproduce

1. Set up a powered welding rig near a damaged vehicle.
2. Set a vehicle repair zone around vehicle.
3. Order NPC to repair vehicle.
4. Once NPC is finished check damage of vehicle. Many parts will remain damaged.

Edit: Could not reproduce this behaviour at first, then realised it was due to having the debug hammerspace mutation. So, turn that off. Yeah. Reproducible in unmodded game.

# Expected behavior

Vehicle repair is a dull process, but micromanaging NPCs in order to get them to repair can become frustrating. The vehicle welding rig, in the hands of an NPC, is almost a waste depending on the availability of materials. Supplying them with a welder and rechargeable batteries becomes desirable, despite the fact that the welding rig exists purely to streamline this process (at least, I assume that's the reason, plus it means you don't have to muck around with charging batteries). As the rig exists purely for convenience and QOL I see no reason that it shouldn't do the same for NPCs. Indeed, this seems more of an oversight than intentional design.

I would expect that a vehicle welding rig attached to, or within four tiles of, a vehicle should be enough for an NPC to be able to use it, regardless of the position of the NPC in relation to the rig. As the exact nature of the rig is undefined in the description I feel this is an acceptable implementation. If not, explicitly adding a couple of batteries to the recipe requirements should suffice. Or maybe a heavy duty cable.

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

 - OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
 - Game Version: [from the main menu, e.g. 0.C-29938-g90f5268437]
 - Graphics version: [Tiles or Terminal]
 - Mods loaded: [e.g.dda, boats, hacktheplanet, StatsThroughSkills]

# Additional context

For your convenience, a bombed military vehicle including boards to block sight with a welding cart stationed below it is located to the NW in this world. All NPCs have welding goggles and mechanics skills to carry out repairs.
[Bug Test.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3867258/Bug.Test.zip)

**Comment by davidpwbrown** [comment]
The problem is that the player has the intelligence to move the vehicle close to the welding rig, or drag the welding rig ( if its draggable ) closer to the bit they are working on.

NPCs dragging stuff or NPCs moving a vehicle is not something thats gonna be done anytime soon, so the only real solution for them is to a)recognise a welding rig is nearby, and position themselves accordingly to make use of it, or b) just use welder items 

I'll see what I can do about a).

also there is another case where we can perhaps abstract the welding requirement if they are at a faction camp that provides welding as part of its upgrades.

**Comment by Funguss** [comment]
Ah, I think I didn't explain what I meant clearly there. The PC can repair any part without moving next to it, whereas NPCs move next to the tile. The PC can stand next to the welding rig and use it to repair anything, but the NPC is unable to do so once it moves out of sight or further than the usable radius.

What about removing the usage limits for a welding rig located in the vehicle repair zone?

**Comment by davidpwbrown** [comment]
Ah, yeah, the NPC targets specific vehicle parts per tile, wheras the player has the benefit of using the vehicle interaction menu.

Yes, I can modify it so that if the welding rig is within the zone, it gets used.
