### ISSUE TITLE
Impossible to survive in the desert!

### ISSUE THREAD

**Issue by Vasari-Lloyd** [CleverRaven/Cataclysm-DDA#35629]
### **Is your feature request related to a problem? Please describe.**  
**Good day gentlemen survivors!** 

Faced with some problems regarding the temperature in the game. A moment of background: it was decided to record the passage in the desert (this is not clickbait, you can not go https://www.youtube.com/watch?v=g9f55hUSmQE&feature=youtu.be) I began to play with the mod on the **desert region**, and **without cities**. In this mode, the rather limited resources of high-tech technology. The passage was decided to start in mid-spring, so that by the summer to acquire some kind of equipment for cooling the character’s asshole. 

But this is bad luck. There are over a hundred ways to keep warm in the game. But I can’t think of how to lower the temperature. Now it’s 60 a spring day and 42-45 degrees Celsius outside. That is, it is simply impossible there, the character’s health just melts in the literal and figurative sense. 

In fact, from the solutions it’s only 1 KBM for climate control (but in the desert it’s impossible to find it, but you also need to find where to put it, etc.). Several types of power armor, but again, where to get them in the desert? The moisture protection suit does not wag the temperature. There are still some mutations in the cold-blooded branch, but this is also quite late content, and the effect of them is not strong. Another option is a car + air conditioning. But even if by some miracle it’s possible to assemble a car in the desert (although it’s still hot in it), when you exit the character almost immediately overheats. There remains only the basement, of which there are not many in the desert, and night outings. Now it’s not summer yet, and at night it’s even hot in cowards! Alternatively, you can find an oasis and go into deep water and get the status of "wet" but as soon as you exit the status of "wet" remains and the temperature again becomes unbearable. It turns out survival in the heat is much more difficult than in winter.

### ****Describe the solution you'd like****  
The most obvious solutions seem to me the following:
1. The ability to pour water on yourself from the container and get the status of "wet" but just to really lower the temperature. (to Riddick's type when he saved Kira :). Let not be necessary but significantly.
2. A hat with wide brim can partially protect against heat.
3. A fan of “shit and sticks,” like on ladies in castles.
4. Battery-powered fan. Just a motor and a propeller can even assemble a moron in the desert, which should help a little with the heat.
5. Any umbrella can also help a little.
6. Finally, a home-made air conditioner from containers, water, and a fan. As a part of the machine.

### **Additional context**  

Maybe something else, but so far that's all that comes to mind.

Thanks for attention!
![Desert CDDA](https://user-images.githubusercontent.com/58004591/69270994-aa04cd80-0c06-11ea-8ef4-6a3784198559.jpg)
ps: Sorry for the mistakes, English is not my native language

**Comment by DaviBones** [comment]
Fun fact: Before electricity, passive evaporative cooling techniques were widely used.
https://en.wikipedia.org/wiki/Evaporative_cooler#Applications

Thanks to the water's high heat capacity, and high heat of transformation, all you really need to cool down a hot, dry room is some water, and a container for said water. The more surface area the water has, the faster cooling occurs.

**Comment by anothersimulacrum** [comment]
I think this complaint should be clarified to two reports:
A bug report, that the temperature in the desert during mi spring is too higher.
And a feature request for more low tech ways of cooling off.

I do not think the issue as it appears in the first paragraph (it is impossible to survive in the desert with no civilization) is valid, but those two are.

**Comment by Vasari-Lloyd** [comment]
Yes, I agree with you that I embellished a little with the words "it is impossible to survive ....". But this can attract more people than a post titled "I'm Hot, Let's Make a Straw Hat." Yes, indeed, you are right, most likely you just do not have enough low-tech (and preferably mobile) cooling methods.

**Comment by Solusphere** [comment]
It hit 42 degrees Celcius on the weekend in my hometown IRL. It's currently spring. Definitely would not recommend without air conditioning.

**Comment by davidpwbrown** [comment]
The temperature is broadly correct. ( at least in the right ballpark )

The desert mod is not intended to be balanced for a complete playthrough, it is a WIP mod to showcase to other modders how to make "biomes" using the regional map settings overlay settings.

So I'm not too concerned about balance impacts from using that mod in addition to having zero cities, that sounds like suicide to me, but your suggestions for heat-ameliorating features would be perhaps useful anyway.

**Comment by kevingranade** [comment]
The scenario as outlined in the issue is roughly speaking, unsurviveable, so it's not at all a bug that you can't do so.
IF we ever make a desert environment an official part of the setting, we will want to look into survivability, but until then there is no value leaving this issue open.
