### ISSUE TITLE
Human lard not usable in other recipes

### ISSUE THREAD

**Issue by rinshankouhai** [CleverRaven/Cataclysm-DDA#35621]
# Describe the bug

Human lard can't be used in other recipes. Even cannibal recipes require animal fat.

# Steps To Reproduce

1. Play as a Cannibal. Procure human lard using your book's recipe.
2. Search "c:human,c:lard"
3. Human lard can't be used in any other recipes.

# Expected behavior

Human lard should be usable like any other fat

# Versions and configuration

- OS: Windows 7
    - OS Version: MINGW/CYGWIN/MSYS2
- Game Version: 0.D-9240-g1bb08dd [32-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    C.R.I.T Expansion Mod [crt_expansion],
    Bens GF recipes [Tolerate_This],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Alternative Map Key [alt_map_key],
    Crazy Cataclysm [crazy_cataclysm],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Mythical Martial Arts [MMA],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks],
    Necromancy [necromancy]
]

# Additional context

Playing a creepy cannibal-type, and I've noticed that human lard can't be used in other recipes. Even cannibal recipes don't list human lard as an option, and require you to use animal fat instead. This seems like a simple oversight, a small but important tweak for players who want to go a little bit Hannibal. There's no logical reason it can't be used like any other fat.

EDIT: Human tallow shares this issue.

**Comment by DaviBones** [comment]
I am currently almost done with a PR that fixes this issue.
