### ISSUE TITLE
Terminal Settings Not Saving

### ISSUE THREAD

**Issue by Shinino** [CleverRaven/Cataclysm-DDA#35631]
# Describe the bug

The terminal settings (in Settings > Graphics) do not save.  They also do not offer the option to save unless you also change something else -- but still does not save the terminal settings.  

That said, resizing the window itself works, as does setting it to fullscreen and windowed borderless.

# Steps To Reproduce

1: Start game
2: Choose Settings
3: Choose Options
4: Choose Graphics
5: Change anything on lines 9 and 10 (Terminal width and Terminal height)
6: Press escape to leave menu

# Expected behavior

See a dialogue asking if I want to change settings.  Once done, see settings applied in the options > graphics section.  Once restarted, see changes take effect.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-9501-g41ef0cb
 - Graphics version: Tiles
 - Mods loaded: non-relevant, as before game actually begins.

**Comment by RustyBrute** [comment]
Same issue on android build 9221. And the game screen shrink to a tiny box on the corner of my phone.

**Comment by TheRealSnowman** [comment]
Can confirm all of this so far as on build 9621 for android. I was hoping I didn't have to edit the file but I guess that's the workaround for now.

Tiny screen problem is dependent on exiting a seperately displayed menu, either options or new game, and going back to the title screen. Makes sense to say it's definitely using those default resolutions, but not stretching to fit the screen.

**Comment by ThomasLinkin** [comment]
yeah, i found the same problem guys. we only have one dev for the whole mobile platform,so it's must be hard to dealt with
