### ISSUE TITLE
Filter mask does not protect against smoke

### ISSUE THREAD

**Issue by Solusphere** [CleverRaven/Cataclysm-DDA#35635]
# Describe the bug

Wearing an active filter mask provides no protection against clouds of smoke, including "thin smoke", "smoke" and "thick smoke". Charges in the filter are used up, but you still get the "You inhale a lungful of thick smoke" message (even if you just stepped in thin smoke).

# Steps To Reproduce

1. Wear a filter mask.
2. Activate the filter mask.
3. Step into smoke clouds of any kind.

# Expected behavior

According to the description, the filter mask "protects from smoke quite well." I would expect it to provide complete protection from thin smoke and regular smoke, and at least partial protection from thick smoke, but it does none of these.

# Screenshots

https://cdn.discordapp.com/attachments/252368751016542218/646958559191629834/unknown.png

https://cdn.discordapp.com/attachments/252368751016542218/646952884902035473/unknown.png
# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-9497-g86d409b [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks]
]

# Additional context

**Comment by Gilferedir** [comment]
From what I have been able to find it looks like this was changed when smoke effects were JSONized here #34388. Unless I'm misunderstanding how it works, it looks like all smoke types were given an immunity_data value of 12, which would be above the filter masks activated environmental protection value of 7.
