### ISSUE TITLE
Apartment Was Generated With One Door Completely Blocked

### ISSUE THREAD

**Issue by HarleyLorenzo** [CleverRaven/Cataclysm-DDA#35663]
# Describe the bug

In this mapgen, the apartment building was generated with its north entrance blocked by the walls of a house.

# Steps To Reproduce

1. N/A (Unsure how to reproduce this behavior as I've only ever seen it in this world)

# Expected behavior

The apartment building should have its north entrance generated unblocked by another building's walls.

# Screenshots

[The map generation bug in question](https://user-images.githubusercontent.com/16141371/69465948-b1d08900-0d50-11ea-89a6-780157c0a070.png)

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 19.10; Release: 19.10; Codename: eoan; 
- Game Version: 0.D-9539-g4b261b5 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Generic Guns [generic_guns],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Crazy Cataclysm [crazy_cataclysm],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Prevent Zombie Revivication [no_reviving_zombies],
    Stats Through Skills [StatsThroughSkills],
    Medieval and Historic Classes and Shields [Medieval_Stuff]
]

# Additional context

This map was generated on an earlier version (I believe 0-D.9422-g8d5b04e). 

I will also backup a save of this instance in case someone wants to review in-game.

**Comment by Funguss** [comment]
Is that the single overmap tile apartment? Just came across one with a double line of windows and a door that led inside one of those wire lockup areas. Not sure if these are a mod addition, guessing so - probably Fuji's.

**Comment by HarleyLorenzo** [comment]
> Is that the single overmap tile apartment? Just came across one with a double line of windows and a door that led inside one of those wire lockup areas. Not sure if these are a mod addition, guessing so - probably Fuji's.

It is a one overworld tile apartment, and I didn't know that these might be a mod addition. I'll do some further investigation on this to confirm if it is a mod addition or not.

**Comment by Funguss** [comment]
Simple way to do that is what I just did - look in the mods folder. Yep, it's one of Fuji's additions, check out data\mods\Fuji_Structures\worldgen\s_apt.json. I'm really liking what I've seen so far, it's just a shame you need More Locations for it. Each place I visit I end up really disliking but I'm gonna have to start a new world to get rid of it all. Towers in general, but especially the refugee ones, I really dislike.

**Comment by Night-Pryanik** [comment]
Judging by the screenshot, the building north of the apartment is one of the procedurally-generated houses. They are very long gone from the game, so I guess this situation shouldn't happen anymore.
