### ISSUE TITLE
Push friendlies up/down/away from stairs

### ISSUE THREAD

**Issue by new02DAY** [CleverRaven/Cataclysm-DDA#35666]
**Is your feature request related to a problem? Please describe.**  
Related to #35665, since I didn't think a bug report would be a good place for a feature suggestion.
I've also run into some situations where a friendly NPC would fall asleep on stairs and block access.

**Describe the solution you'd like**  
Allow players the ability to push (also maybe pull?) friendlies up/down/away from stairs.

**Describe alternatives you've considered**  
Ignore it, since it's not a common issue or can be avoided by some pre-planning (ie. making sure NPCs are away from stairs before the player goes down).

**Additional context**

**Comment by Funguss** [comment]
Next time try 'C' to talk to them and wake them, or tell everyone on your team to wake up. That should work if you have Z levels enabled. But I agree on the inclusion of the feature.

**Comment by new02DAY** [comment]
> Next time try 'C' to talk to them and wake them, or tell everyone on your team to wake up. That should work if you have Z levels enabled. But I agree on the inclusion of the feature.

Huh. Didn't think to try talking to them. Thanks, I'll try and remember that for next time.

**Comment by Funguss** [comment]
You're welcome! :+1: It _should_ work, though I've never had this precise issue. You can definitely talk across Z levels though, so long as you're in range. A lot of other things bork across Z levels so I don't blame you for overlooking this!
