### ISSUE TITLE
spell `ethereal grasp` cause segfault  

### ISSUE THREAD

**Issue by MEXAHOTABOP** [CleverRaven/Cataclysm-DDA#35672]
# Describe the bug

segfault on successful cast `ethereal grasp` spell from magiclysm 

# Steps To Reproduce

1. successful cast ethereal grasp on enemy
2. in about 90% of casts game crashes
3. if not goto 1

tested on own build and on jenkins build 

# Versions and configuration

 - OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Gentoo; Description: Gentoo Base System release 2.6; Release: 2.6; Codename: n/a; (gentoo unstable)
- Game Version: 0.D-9619-g16817428c1 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Mutant NPCs [mutant_npcs],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    EZ-Mode Medical [fast_healing],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Folding Parts pack [deoxymod],
    Tanks and Other Vehicles [Tanks],
    Safe Autodoc [safeautodoc],
    Simplified Nutrition [novitamins],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills]
]

# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3882295/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3882296/debug.log)
[Иксония2.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3882297/2.zip) (save) just cast spell on turret nearby

**Comment by MEXAHOTABOP** [comment]
for some reason all works correctly when i try to debug loop step by step https://github.com/CleverRaven/Cataclysm-DDA/blob/16817428c1a4f7ce5b6c6672ff5ccb1333dc1713/src/magic_spell_effect.cpp#L351

can someone on older linux with gcc(libc) <9.2 try to reproduce this crash?

**Comment by davidpwbrown** [comment]
erasing while iterating needs different handling to that dosnt it?
