### ISSUE TITLE
Crash when activating item not from inventory

### ISSUE THREAD

**Issue by M-Real** [CleverRaven/Cataclysm-DDA#35673]
# Describe the bug

When using the (a)ctivate command on some items outside of the player's inventory, the game crashes.

# Steps To Reproduce

1. Have any activate-able item nearby but not in player inventory
2. Use (a)ctivate on the item
3. The game crashes

# Expected behavior

The item should activate as normal.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-9615-gefbacc3 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context

I initially discovered this bug when trying to unfold a vehicle, but others have since reported many other items for which it occurs. I have updated this post to reflect the broader scope of the bug. It is generally advised to not attempt the activation of items outside of player inventory until this is fixed. However, there are some items which appear to still work just fine (I have tested the filled charcoal kiln and lit charcoal kiln and they worked successfully, but you do so at your own risk).

[Logs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3882358/Logs.zip)
[Crash Test.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3882359/Crash.Test.zip)

**Comment by ZhilkinSerg** [comment]
Cause by

**Comment by M-Real** [comment]
Oh shoot, I didn't think to test activating other kinds of items outside the inventory. Hopefully my report helped figure out this crash at least.
