### ISSUE TITLE
Modular Turrets needs to update to new robotic parts system

### ISSUE THREAD

**Issue by CSHague** [CleverRaven/Cataclysm-DDA#35689]
# Describe the bug

With Modular Turrets mod enabled, the Turret Control unit cannot be crafted as all Modular Turrets turrets (which replace CROWS and other other variants) are using outdated uncraft recipes that give RAM and processors still. Modular Turrets and Salvaged Robots needs to be updated to include the newly added module components otherwise the Turret Control Unit is nearly-impossible to craft.

# Steps To Reproduce

Attempt to craft Turret Control Unit with Modular Turrets mod. Realize that Firing Operating system and Targeting module cannot be retrieved from inactive or broken Modular Turrets. Check the repo to notice that Modular Turrets overrides most turret uncraft recipes which would contain the needed parts otherwise.

# Expected behavior

Able to get robotic module parts from salvaged modular turrets to build vehicle turret controls as you would from CROWS or other robotic drones.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-9619-g1681742 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Aftershock [aftershock],
    Bens GF recipes [Tolerate_This],
    Garden Pots [growable-pots],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Makeshift Items Mod [makeshift],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks]
]
]

# Additional context

You can still get the parts from killing a chicken walker and maybe a few others, but I'm not even sure if salvage robots changes that as well.

**Comment by Maleclypse** [comment]
My first thought after looking at the Modular turrets files is to remove the monster overrides?

**Comment by CSHague** [comment]
I'm not sure that's feasible without breaking modular turrets' or salvage robots' functionality. You would normally disassemble a broken or inactive turret into its associated disarmed variant. If the override were removed you'd lose out on the modular weapons when you disassemble them.  Seems like the robotic driving units that the disarmed turrets disassemble into should be replaced with the robotic modules and the RAM and processors removed as the modules all break down into similar items

**Comment by Maleclypse** [comment]
@I-am-Erk I think that if "Update Generic Guns mod to be synchronized with current core content" #35359 is an 0.E blocker that this should be as well.   It's lack of updates makes it detrimental to play with currently compared to the additions in mainline.  There is a current PR that looks like it is ready to bring this to the same level of update that the other mod is being updated to.  I'm curious on your opinion.

**Comment by I-am-Erk** [comment]
Honestly I think a better argument might be that the modular turrets mod should be picked over and obsoleted, since we basically have modular turrets already.

**Comment by esotericist** [comment]
in keeping with erk's last post, I think the key question is: what does modular turrets *actually provide* that the vanilla game does not, which is sufficiently distinct such as to either warrant the mod still existing, or warrant being integrated into the core game?

As far as I know, it's mostly vestigial at this point. I'd welcome strong counter arguments to the contrary, though.
