### ISSUE TITLE
Player isn't warned of the appareance of a swarm of bees

### ISSUE THREAD

**Issue by xrogaan** [CleverRaven/Cataclysm-DDA#35680]
**Is your feature request related to a problem? Please describe.**  
When walking around in a field, the player may occasionally meet a swarm of bee (**not** the giant mutated ones). The player isn't warned by said swarm, because it isn't a monster. Yet the swarm sting hurts so much that it'll renders the character inoperable. Painkillers seems to have no practical effect.

They are defined in data/json/field_type.json with the id `fd_bees`.

**Describe the solution you'd like**  
Being warned of the existence of those hellish creatures would probably be an even solution.

**Describe alternatives you've considered**  
Reducing the pain or providing a way to alleviate the "stung" effect.

**Comment by Night-Pryanik** [comment]
Closing as the bees field is no more.

**Comment by anothersimulacrum** [comment]
I think this still has value as a feature request for safe mode interaction with dangerous fields.
