### ISSUE TITLE
NPCs should be enabled by default.

### ISSUE THREAD

**Issue by Swend5** [CleverRaven/Cataclysm-DDA#35698]
**Is your feature request related to a problem? Please describe.**  
As a new player, as I started learning the game (without looking the options related to world generation), I was convinced that there would be NPCs in the game. The game comes with a mod "Disable NPC Needs", there are skills called bartering and speaking, and there are traits that refer to social interaction. I had no reason to believe that they would be disabled by default, and it felt very frustrating to find out after many hours of gameplay that they were, leaving me to scrap my first successful playthrough if I wanted them.

**Describe the solution you'd like**  
Enable NPCs by default.

**Describe alternatives you've considered**  
If there is a reason it is actually a good idea to have them disabled for new players (and let me be clear: I am not saying there isn't), direct their attention to the fact that they are disabled in spite of the mechanics that interact with them, and inform them what the consequences would be if they enable them when starting out.

**Comment by ZhilkinSerg** [comment]
Static npcs are enabled by default.

**Comment by Swend5** [comment]
Oh, I'm an idiot, of course I am on the 0.D stable release and not the newest experimental one. Just delete this...
