### ISSUE TITLE
Placing thread as fuse/trail markers?

### ISSUE THREAD

**Issue by TechyBen** [CleverRaven/Cataclysm-DDA#35705]
**Is your feature request related to a problem? Please describe.**  
I was just attempting to place a trail of "thread" as a trail to follow/return to a hidden [thing], so I don't forget where it is in the forest. Then noticed how annoying it is to do it by hand... lots of button pressing. But I do have over 200 thread, so it could cover a nice area for me to then find using the map marker etc.

**Describe the solution you'd like**  
A craftable item, with for example a scrap of metal or splinter of wood, that would be a "spool of thread". Similar to the "bundle of rags" it would partially be a storage/stack of the thread, but on activation would have 2 options.
1) "unravel thread from the spool... it is all tangled in your backpack now."
2) "lay as a combustible fuse/trail marker"

**Describe alternatives you've considered**  
A button to autodrop. But that could also get messy. As this is a situational mechanic I have in mind, I don't see much of a problem "crafting" this into an item. Yes, the character/player could do it with any bundle of thread, but an actual spool would be quicker/easier IRL to unravel.

**Additional context**  
I just though a fuse wire/ignition system would also be an interesting (though arguable abusable) mechanic. So posting here for ideas. :)

**Comment by CoroNaut** [comment]
I like it, maybe I can criss-cross the threads to time multiple detonations to happen in the same turn?
