### ISSUE TITLE
Killing zombies standing on display cases drops items under the glass

### ISSUE THREAD

**Issue by SpellingSword** [CleverRaven/Cataclysm-DDA#35708]
# Describe the bug

Killing zombies standing on display cases drops items under the glass, forcing you to break it open to get them. This is silly.

# Steps To Reproduce

1. Have enemy stand on sealed display case
2. Kill them
3. Observe items teleport beneath the glass

# Expected behavior

Items drop outside the case

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-9539-g4b261b5 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    No Fungal Monsters [No_Fungi]
]

**Comment by Funguss** [comment]
Huh... How did they even get on there? Or... maybe they're inside the case too?!
Seriously though, I've never seen a zombie climb on one, I didn't think it was possible.

**Comment by gcaliber** [comment]
A similar thing happens with missed shots. Ammo that lands on a display case is not accessible without breaking it.

**Comment by Night-Pryanik** [comment]
I guess this is a duplicate of #8979.
