### ISSUE TITLE
Bike rack crashes game

### ISSUE THREAD

**Issue by gregoranders** [CleverRaven/Cataclysm-DDA#35714]
# Describe the bug

VERSION: 0.D-9634-g962e122266
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation faultError creating SDL message box: No message system available

STACK TRACE:

    ./cataclysm-tiles(_Z21debug_write_backtraceRSo+0x23) [0x94e533]
    ./cataclysm-tiles() [0x94af63]
    ./cataclysm-tiles() [0x94abd3]
    /lib64/libc.so.6(+0x390d0) [0x7f6108a7f0d0]
    ./cataclysm-tiles(_ZN7vehicle22remove_carried_vehicleERKSt6vectorIiSaIiEE+0xa7) [0x147fc37]
    ./cataclysm-tiles(_ZN7vehicle13use_bike_rackEi+0xed6) [0x14e7c46]
    ./cataclysm-tiles(_ZN7vehicle13interact_withERK8tripointi+0x21e2) [0x14ea292]
    ./cataclysm-tiles(_ZN4game7examineERK8tripoint+0x285) [0x9aee65]
    ./cataclysm-tiles(_ZN4game7examineEv+0x1b6) [0x9aeb46]
    ./cataclysm-tiles(_ZN4game13handle_actionEv+0x68fa) [0xa5b99a]
    ./cataclysm-tiles(_ZN4game7do_turnEv+0xa18) [0x988428]
    ./cataclysm-tiles(main+0x14bc) [0x92812c]
    /lib64/libc.so.6(__libc_start_main+0xeb) [0x7f6108a69e5b]
    ./cataclysm-tiles(_start+0x2a) [0x926bba]

    Attempting to repeat stack trace using debug symbols…
    debug_write_backtrace(std::ostream&)
    ??:?
    log_crash(char const*, char const*)
    crash.cpp:?
    signal_handler(int)
    crash.cpp:?
    ??
    ??:0
    vehicle::remove_carried_vehicle(std::vector<int, std::allocator<int> > const&)
    ??:?
    vehicle::use_bike_rack(int)
    ??:?
    vehicle::interact_with(tripoint const&, int)
    ??:?
    game::examine(tripoint const&)
    ??:?
    game::examine()
    ??:?
    game::handle_action()
    ??:?
    game::do_turn()
    ??:?
    main
    ??:?
    __libc_start_main
    ??:?
    _start
    ??:?

# Steps To Reproduce

Dismount mounted bike rack with inboard mirrors...see stacktrace.

# Expected behavior

No crash.

# Screenshots

None
# Versions and configuration

Linux. see stacktrace.

# Additional context

**Comment by Funguss** [comment]
Weirdly, you can't put things in storage attached via bike rack, though anything already in there stays. Dunno if that's related.

**Comment by jeremyshannon** [comment]
This sounds like it's the same problem seen in #37304  
Hey gregoranders,. can you check your save and see if there are any items attached to your bike that lack the "carry:" tag? Or if you suspect it's the inboard mirror, you could try removing it and see if that lets you unrack the bike.
