### ISSUE TITLE
New faction camp error

### ISSUE THREAD

**Issue by Funguss** [CleverRaven/Cataclysm-DDA#35710]
# Describe the bug

After telling a follower you want to set up a camp and naming it, this error is produced:

 DEBUG    : invalid overmap terrain id "faction_base_camp_new_0"

 FUNCTION : int_id<T> generic_factory<T>::convert(const string_id<T>&, const int_id<T>&) const [with T = oter_t]
 FILE     : src/generic_factory.h
 LINE     : 384

Doesn't seem to be a mod issue, tested in a mod free world. Camp still generates but overmap tile is changed to '% nothing' in all white. Maybe a rename or typo somewhere? See below screenshots for two separate examples.

# Steps To Reproduce

1. Bring your NPC to a field.
2. Ask them to set up a camp.
3. Name the camp.
4. View map.

# Screenshots

![Overmap Camp](https://user-images.githubusercontent.com/57632331/69505703-193e3280-0f23-11ea-8f65-f4e56b55ac20.png)
![Overmap Camp 2](https://user-images.githubusercontent.com/57632331/69505706-1ba08c80-0f23-11ea-9304-01ded86c1dc7.png)

# Versions and configuration
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-9634-g962e122 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional Info

Ok, so I'm pretty wary of going ahead with this camp even though it seems fine, so I decided to look into it myself a bit. Turns out there's a 'faction_base_camp_new_0_north' (or south, east or west) in the overmap editor but no 'faction_base_camp_new_0'. I'm guessing that's a template that's getting called erroneously when it should simply be 'faction_base_camp' for a survey. But maybe I'm wrong. Currently testing out the camp with a tile swap and seeing how it plays.

**Comment by Bliczz** [comment]
Same problem, and plus to that, my NPC companions start to run away from the camp after the mission done. They ran in the random directories, even in to the water. I had two companions. First one ran away in to the water and drawn. Second one ran to the closest farm. Than I ask him to comeback to the camp, he did it, but after save and load the game he is disappear. I see him on the global map, in the camp, but I dont see him directly. In faction menu it said, what he is on the mission, on guard, and go to the camp, and his coordinates is correct with the camp coordinates.

I saw on some forum same problem, but I thought, what it was fixed.
Im using latest build - 9929

Can I some how delete faction camp and my brocken companions?
[https://cdn.discordapp.com/attachments/545448324660985862/648436944623239168/unknown.png](url)
[https://cdn.discordapp.com/attachments/545448324660985862/648437138601410560/unknown.png](url)

**Comment by davidpwbrown** [comment]
> Same problem, and plus to that, my NPC companions start to run away from the camp after the mission done. They ran in the random directories, even in to the water. I had two companions. First one ran away in to the water and drawn. Second one ran to the closest farm. Than I ask him to comeback to the camp, he did it, but after save and load the game he is disappear. I see him on the global map, in the camp, but I dont see him directly. In faction menu it said, what he is on the mission, on guard, and go to the camp, and his coordinates is correct with the camp coordinates.
> 
> I saw on some forum same problem, but I thought, what it was fixed.
> Im using latest build - 9929
> 
> Can I some how delete faction camp and my broken companions?
> [https://cdn.discordapp.com/attachments/545448324660985862/648436944623239168/unknown.png](url)
> [https://cdn.discordapp.com/attachments/545448324660985862/648437138601410560/unknown.png](url)

Bliczz were your NPCs assigned to the camp and had jobs assigned to them, or you just did a mission with them from the bulletin board?

**Comment by Bliczz** [comment]
> > Same problem, and plus to that, my NPC companions start to run away from the camp after the mission done. They ran in the random directories, even in to the water. I had two companions. First one ran away in to the water and drawn. Second one ran to the closest farm. Than I ask him to comeback to the camp, he did it, but after save and load the game he is disappear. I see him on the global map, in the camp, but I dont see him directly. In faction menu it said, what he is on the mission, on guard, and go to the camp, and his coordinates is correct with the camp coordinates.
> > I saw on some forum same problem, but I thought, what it was fixed.
> > Im using latest build - 9929
> > Can I some how delete faction camp and my broken companions?
> > [https://cdn.discordapp.com/attachments/545448324660985862/648436944623239168/unknown.png](url)
> > [https://cdn.discordapp.com/attachments/545448324660985862/648437138601410560/unknown.png](url)
> 
> Bliczz were your NPCs assigned to the camp and had jobs assigned to them, or you just did a mission with them from the bulletin board?

Just did the mission. Before I gave them a mission, they are followed me.

**Comment by davidpwbrown** [comment]
Are you using the isometric tileset?

**Comment by snipercup** [comment]
I'm getting the same issue and i'm using the isometric tileset chesthole_iso.

**Comment by Bliczz** [comment]
Im using MSX++UnDeadPeopleEdition tileset.

**Comment by Funguss** [comment]
Um... Has this bug report gotten completely derailed by a different bug? In the hopes that it hasn't, I'll say no. No to tilesets. No tiles ever, thanks.

Regarding the other bug, if it's not a tileset issue then I'm guessing they've got a weird goal or task. Tell them to stop what they're doing, then tell them to follow the same rules as another survivor who isn't doing something you don't want them to do. And, just in case you decide to do it the other way around, don't. Tell them to stop, then tell them to copy the good one. They won't listen to some instructions if they're busy with some things.

If they still run off then I'm stumped and you should probably open a separate bug report because it's probably only related in so far as you're at a camp and it irks me when I think there's a response to a bug I've reported and instead it's... this.

**Comment by davidpwbrown** [comment]
I was asking if *you* used the isometric tileset because I was wondering if the iso rotation was messing with the faction camp rotation, apparently its not that.

I was asking Bliczz about what the NPCs were assigned to, because that could give clues about whether the basecamp was actually stored correctly on the overmap.

Im not derailing your issue, its all relevant - bliczz said they had the same issue as you, and the NPCs running off were maybe a symptom of this issue, its all connected.
