### ISSUE TITLE
Cracklins made when crafting Mutant Lard do not have toxins

### ISSUE THREAD

**Issue by M-Real** [CleverRaven/Cataclysm-DDA#35712]
# Describe the bug

When crafting Mutant Lard, the Cracklins that are also produced do not have the toxins that mutant food products usually have.

# Steps To Reproduce

1. Acquire some Mutant Fat
2. Use the Mutant Fat to craft Mutant Lard (Mutant Tallow not yet tested)
3. The Cracklins that result from the recipe will be normal with no toxins

# Expected behavior

The Cracklins should have toxins like all other mutant food products.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-9634-g962e122 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context

[Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3884929/Save.zip)

**Comment by KorGgenT** [comment]
all byproducts are like this - the byproduct has the "default" values, and the regular product has all the rest. (this is where the negative calorie thing can come in, interestingly enough)

**Comment by DaviBones** [comment]
The whole lard/tallow thing irks me a little. In real life, as far as I've ever heard, lard is rendered pig fat, and tallow is rendered fat from other ungulates (usually cow fat). In-game they are basically a gamey way to fabricate a differentiation which IMHO is unnecessary in the first place. Cracklins as a byproduct feel like a similarly gamey way of balancing the mass/calories of the two recipes.

I'm tempted to just combine them into a single item, "rendered fat", and get rid of the byproduct entirely, which would solve this issue.

**Comment by casswedson** [comment]
Fixed by #45812
