### ISSUE TITLE
Characters are able to spawn with 2 pairs of eyewear on

### ISSUE THREAD

**Issue by VTCobaltblood** [CleverRaven/Cataclysm-DDA#35720]
# Describe the bug

Near-sighted or far-sighted characters that pick professions that spawn with sunglasses, stylish sunglasses or any other kind of eyewear spawn with both equipped at once.

# Steps To Reproduce

1. Pick Bionic Student as your character profession.
2. Pick the near-sighted trait.
3. Your character spawns with both sunglasses and eyeglasses on at once.

# Expected behavior

Either one pair of eyewear gets stashed in the inventory, or sunglasses are replaced with their fit-over version.

# Versions and configuration

- OS: Windows
    - OS Version: Windows 7 
- Game Version: 0.D-9425-ga6c8ece [32-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Bees [No_Bees],
    No Ants [No_Anthills],
    No Fungal Monsters [No_Fungi],
    Generic Guns [generic_guns]
]

**Comment by kevingranade** [comment]
That character is making a
( •_•)
( •_•)>⌐■-■
﻿(⌐■_■)
Spectacle of themselves.

**Comment by sah4001** [comment]
Is it uncommon to wear a pair of sunglasses on top of another pair of glasses?

**Comment by Moth-Tolias** [comment]
yes, very.
