### ISSUE TITLE
Name, skill, and material inconsistencies for the .308 pipe rifle and handmade carbine

### ISSUE THREAD

**Issue by LaVeyanFiend** [CleverRaven/Cataclysm-DDA#35728]
**Is your feature request related to a problem? Please describe.**  
1. The (now) detachable mag-fed pipe rifle .308's name is too similar to the single-shot pipe rifle [Insertcaliberhere]s, and is more similar to the handmade carbine(also detachable magfed).
2. The handmade carbine takes more skill to craft(7/5 mechanics & marksmanship vs. 5/3 for the pipe rifle .308).
3. Handmade carbine also requires more materials(fine bolt turning & welding equipment in addition to the fine screwdriving/metalsawing & pliers/multitool)

**Describe the solution you'd like**  
1. Rename the pipe rifle .308 to pipe battle rifle or handmade heavy carbine.
2. Lower skill requirements for the handmade carbine so you don't need sniper-level marksmanship to make a non-sniper rifle.
3. Increase material requirements for the pipe rifle .308 to be equal or greater than the handmade carbine.
4. Remove the pliers/multitool requirement from both recipes and change to bolt turning 1(which is why they are there anyways).

**Describe alternatives you've considered**  
1. Swap their skill requirements since .308 is a more powerful round.
2. Make both 7 mechanics/5 marksmanship instead of Alt 1.
3. Make both 7 mechanics/3 marksmanship so you don't need sniper-level marksmanship.
4. Decrease handmade carbine's material requirements down to the pipe rifle .308's.

**Additional context**  
Review requested from @Rail-Runner, as he changed the pipe rifle .308 recently .

**Comment by Rail-Runner** [comment]
Well, not entirely sure about the correct approach here, and so I'll wait until someone else comments before doing anything, but my opinion is the following:

1. Rename .308 pipe rifle to heavy handmade carbine.
2, Make both guns need 7 mechanics and 3 marksmanship to craft and change materials and tools used for .308 rifle to be the same as for handmade carbine.
