### ISSUE TITLE
Liquid-loaded Modular Turrets can be deactivated giving filled default containers

### ISSUE THREAD

**Issue by CSHague** [CleverRaven/Cataclysm-DDA#35737]
# Describe the bug

Modular Turrets that are loaded with liquid ammunition such as flamethrowers will drop filled plastic jerrycans of their ammunition regardless of how many shots were taken by the turret. EDIT: When the turrets are loaded, they take from any container but always spawn a new container when deactivated.

# Steps To Reproduce

Spawn an inactive military flamethrower turret. Spawn container of napalm. Have enough skill to program turret when activated and activate it. It will load the fuel. Now walk into the turret and it will prompt you for deactivation. Deactivating gives filled jerrycan of napalm. Deactivating water turret in this manner gives a plastic bottle filled with water.

# Expected behavior

Should prompt for a container to fill or to dump the liquid on the ground.

# Screenshots

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-9667-g329f99b [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Aftershock [aftershock],
    Bens GF recipes [Tolerate_This],
    Garden Pots [growable-pots],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Makeshift Items Mod [makeshift],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks]
]

 - OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
 - Game Version: [from the main menu, e.g. 0.C-29938-g90f5268437]
 - Graphics version: [Tiles or Terminal]
 - Mods loaded: [e.g.dda, boats, hacktheplanet, StatsThroughSkills]

# Additional context

 I've been working on updating Modular Turrets to use newer parts when I came across this bug.  I was trying to get modular turrets to drop their ammo on death (successfully in the case of bullet using turrets) when I found that flamer turrets specifically dropped hundreds of filled containers when given the DROPS_AMMO flag. The starting_ammo was 200. It was quite a sight. Sorry no screenshots.

**Comment by ymber** [comment]
This mod is on the way out so the issue is no longer relevant.
