### ISSUE TITLE
disassembling someone stuff does not counts as crime

### ISSUE THREAD

**Issue by Leviathan21** [CleverRaven/Cataclysm-DDA#35739]
# Describe the bug
disassembling faction owned stuff does not counts as crime

# Steps To Reproduce

1. get into refugee center
2. disassemble blanket
3. zero fucks given despite of being faction stuff

# Expected behavior
guards go haywire

**Comment by Funguss** [comment]
You're not stealing it, and why would they want it after it's broken? Sheesh.

To be fair they should just tell you to stop, not go haywire. Unless you don't stop when they tell you to. I've never actually tried stealing from an NPC or faction, but I would expect them to do the same, too, not immediately resort to violence.

**Comment by Leviathan21** [comment]
@Funguss порвало у дауна

**Comment by davidpwbrown** [comment]
Currently, when moving their objects or messing with their vehicles, you get 3 warnings
If you continue, then they turn hostile.

The same should apply here.
