### ISSUE TITLE
Zone Interaction error with sawing planks.

### ISSUE THREAD

**Issue by HudsonCW** [CleverRaven/Cataclysm-DDA#35736]
# Describe the bug

Flashing Error message when using zones to chop logs into planks

# Steps To Reproduce

Place logs in wood zone, use zone interaction (shift + o) to chop logs.

# Expected behavior

I can only speculate that the reason it is throwing this error message is because I am using a misc repair kit to chop the logs, and the error message mentions using charges.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-9667-g329f99b [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Mapgen Demo [mapgen_demo],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Craftable Gun Pack [craftgp]
]

# Additional context

Note: I originally encountered this bug on Experimental Build 9898, I then updated to Experimental build 9936 and encountered the same issue under the same circumstances.  

[Bug Report.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3895079/Bug.Report.zip)

**Comment by davidpwbrown** [comment]
Cannot reproduce on latest master. Using misc repair kit and logs in a wood zone, no debugmsg error.

Do you have a reproducible save?

**Comment by HudsonCW** [comment]
I just tested it to make sure the issue hadn't self resolved on my save, both with and without the misc repair kit; and I am still getting the error message. 
[Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3898074/Save.zip)
