### ISSUE TITLE
Firearm repair kit and soldering iron battery type mismatch

### ISSUE THREAD

**Issue by TheDarkMaster13** [CleverRaven/Cataclysm-DDA#35745]
# Describe the bug

The Firearm repair kit is built using a soldering iron, which takes light batteries.  However the kit uses medium batteries by default.  Likely an oversight, as the kit is just combining all the tools together in one place.  The two should use the same batteries.

# Steps To Reproduce

1. Check the soldering iron item/recipe compatible magazines.
2. Check the firearm repair kit item/recipe compatible magazines.

# Expected behavior

Both items should accept the same batteries as magazines.

# Versions and configuration

<!-- Please complete the following information; you can now go to:
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-9499-gd0db81d [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Modular Turrets [modular_turrets],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Disable Religious Texts [no_religious_Texts],
    No Survivor Armor [no_survivor_armor],
    No Fungal Monsters [No_Fungi]
]

**Comment by Funguss** [comment]
Well... IIRC the firearm repair kit has a substantially higher battery usage than the soldering iron, so this might be a convenience consideration. Though, again, IIRC there's a medium battery mod, or whatever size it is that you're implying. Might the materials already be part of the recipe? Should they be? I dunno. Just food for thought.

That being said, I'm pretty sure there are recipes that require more than a disposable light or ultralight or whatever battery can provide. Not that that's much of an issue with the current crafting mechanics, but still.

Another consideration is that the firearm repair kit is a specific thing, not just the sum of all parts. The soldering iron used in construction stops being usable as a soldering iron (yet again IIRC) and recipes specifically ask for the firearm repair kit, not just the tools that go into it. It's reasonable to assume that at least some of them have undergone some kind of fundamental change in nature.

Um... Too much memory there. Sorry, no time to check it out.
