### ISSUE TITLE
Issue with scrolling in item description

### ISSUE THREAD

**Issue by ZoolookCDDA** [CleverRaven/Cataclysm-DDA#35766]
# Describe the bug

When scrolling the description of an item with PgUp and PgDown, the scrolling might get stuck.

# Steps To Reproduce

1. In the attached save game, press 'V' and go to the description for the cellphone.
2. Press PgUp any positive x number of times.
3. Now, scrolling the item description 1 step down requires x+1 PgDn key presses

# Expected behavior

Since pressing PgUp x number of times does not scroll the description, a single PgDn key press in step 3 above should suffice to scroll the description down by one step, not x+1 key presses.

# Versions and configuration

-----------------------------------------
22:23:00.906 : Starting log.
22:23:00.906 INFO : Cataclysm DDA version 0.D-9735-gc3982c9
22:23:00.908 INFO : Number of render drivers on your system: 3
22:23:00.908 INFO : Render driver: 0/opengl
22:23:00.908 INFO : Render driver: 1/opengles2
22:23:00.908 INFO : Render driver: 2/software
22:23:01.073 INFO : SDL version used during compile is 2.0.4
22:23:01.073 INFO : SDL version used during linking and in runtime is 2.0.8
22:23:01.165 INFO : Active renderer: 2/software
22:23:01.177 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
22:23:01.200 WARNING : opendir [./mods/] failed with "Ingen sådan fil eller filkatalog".
22:23:04.141 WARNING : opendir [./save/Birdseye/mods] failed with "Ingen sådan fil eller filkatalog".
22:23:11.243 INFO : Loaded tileset: retrodays
22:23:28.177 :  GAME REPORT:
- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 18.04.3 LTS; Release: 18.04; Codename: bionic; 
- Game Version: 0.D-9735-gc3982c9 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

22:23:32.263 : Log shutdown.
-----------------------------------------

# Additional context

The bug seems to occur for any item whose entire description requires scrolling with PgUp and PgDn. It probably isn't necessary to use the attached save to obtain the bug.

A similar bug occurs when scrolling to the bottom of the item description and then pressing PgDn x number of times. Scrolling the description up by one step now requires PgUp to be pressed x+1 times.

I assume that somewhere in the code, the scroll offset is incremented/decremented even when it is outside the bounds defined by the item description and this causes the bug.

[ScrollProblems.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3903034/ScrollProblems.zip)

**Comment by 8street** [comment]
Sorry for the previous commits, now I'll redo everything. I found a better solution.
