### ISSUE TITLE
Implement Stockpile Zones

### ISSUE THREAD

**Issue by jagoly** [CleverRaven/Cataclysm-DDA#35773]
**Is your feature request related to a problem? Please describe.**  
Currently, storing supplies in a vehicle can be a pain. Say you want to ensure that you always have a few rags, plastic chunks, scrap metals, and some kind of thread. Currently, if you put all of these in a vehicles zone, it will probably just get completely filled with one type of item. If you want to ensure you have all of the items available, you need one zone for each. This is silly.

My proposal is to implement a stockpile zone, or to enhance the existing custom loot zone to support specifying amounts. It seems unnecessary to have them as separate zone types, when combined with my proposed zone priority feature (I will make a separate issue for that, or maybe just a pull request since it shouldn't be in any way contentious).

**Describe the solution you'd like**  
I propose extending the custom zone syntax to support a range of new features, to start with:

- allow ANDing filters together, for example to find jars with food in them
  -  `(c:food,jar)`
- allow searching through an items flags
  - `f:filthy`

These are useful even without stockpiles, as they let you do things like search for filthy items of a specific type, like `(c:spare parts,f:filthy)`. In addition, stockpiles require the ability to:

- allow explicitly ORing filters, into a group
  - `[thread,sinew,yarn]`
- specify an amount for an item or group
  - `plastic chunk*20`
  - `[thread,sinew,yarn]*300`
- optionally, allow specifying a volume or weight (not sure if this has a proper use case)
  - `c:food*20L`

Some possibly useful features that could be convenient even without stockpiles:
- allow quoting items to make finding exact items easier
  - `"rag"`

One thing that should be noted is that with these changes, all existing filters would still work, with the possible exception of negated filters, as they would be ORed rather than ANDed when there are no brackets. 

**Describe alternatives you've considered**  
Adding an entirely new GUI for stockpiles so users don't have to type out the filter. However, there is no reason this could not be added as well - the gui could just be used to create the filter strings.

**Additional context**  
One thing I noted while doing this is that with the added grouping and ability to check flags, custom filters would be able to match every item that is currently matched by the existing, hardcoded filters. As such, to me it seems logical to replace all of that hardcoding, and just store a filter for each zone type in `loot_zones.json`. Then we would just have three loot related zone types - LOOT_UNSORTED (maybe renamed to LOOT_SOURCE), LOOT_CUSTOM (maybe renamed to LOOT_DESTINATION) and LOOT_IGNORE.

 A performance concern has been raised with this, however in my testing I've found that just using custom zones everywhere makes no noticeable difference at all. See my experimental code for that here https://github.com/jagoly/Cataclysm-DDA/commit/ed3841d6c5ee97d8e88a247e3187f1fcd4220017. I've also been sharing my results for this on discord.

**Comment by Funguss** [comment]
You probably want Slaves to Mi-Go 2: NPC Fortress. Sorry, it's not here yet. ;)

I'm pretty sure you can do that kind of thing with the current iteration of custom zones by using "glass jars, -c:drugs, -c:containers" (or whatever category glass jars and the things that they contain are in). If you use -c:a, -c:e, -c:i and -c:u that should deal with everything save food. Give it a go and see.

Currently the food stockpile is required by faction camps, so that would need some going over. Apart from that I agree for the most part you can ignore the hardcoded zones and use customs, however I do believe there's some logic being implemented with the different types of food zones that means they're optimised for intelligent storage. At least, it seems that way from reading the descriptions... Though I will never, ever trust unintelligent things to store my perishables unless I can read what they're thinking.

**Comment by jagoly** [comment]
for basecamp food zones, they are not a loot zone, they are a different type of zone. the sort out loot action will never place anything there.

as for intelligent storage, I assume you mean for example perishable food zones having priority over regular food zones. I've got a separate priority system implemented that deals with that:
![Screenshot from 2019-11-27 09-18-09](https://user-images.githubusercontent.com/4125929/69847105-45aed180-12ca-11ea-951d-fa753c8340e7.png)

**Comment by Funguss** [comment]
Yeah, you need a food stockpile zone as well as a basecamp food zone, that's the thing. Also, with the food zones, if they're a single tile wide you can bind them to a vehicle. I'm not too sure why that only applies to food zones and not custom loot zones, but it does give them more of a purpose. It may apply to the other kind of loot zones that aren't custom too, I've not checked. Anyway, it's a minor point; you're totally right in that they can do with more options and a better GUI.

I'm curious about those numbers at the beginning of the zone names... Do they have any kind of functionality? Is that something you've coded? Or does the position in the list have some kind of effect on how items are sorted?

Just in case anybody failed to get my reference (it was a bit obscure), I was trying to say that DF has a really nice stockpile system, especially with the additions from DF Hack. It's a good reference point.

**Comment by jagoly** [comment]
Yep, those numbers are zone priority, you can change them with +-. The way they work is that if an item matches multiple zones, it will always go into the zone with highest priority. So, there's no need to put a bunch of -foo filters in your more general zones if you want to have zones for specific items, just give the specific zones a higher priority. It also allows you to re-order vehicle loot zones, which is currently impossible. I'm doing up a PR for this stuff now.

Also I've played a tonne of dwarf fortress lately, so that's probably where a lot of my thinking is coming from XD

**Comment by jagoly** [comment]
also as a note one thing I'd also like to do (out of the scope of this issue) is change zones to not be restricted to being a rectangle. Make it so that you can just "paint" a zone of whatever shape you want. This probably isn't too useful for static zones, but would be nice for vehicle zones, to let you bind a zone to multiple cargo spaces (which is also something I want to do)
