### ISSUE TITLE
Music saps morale from wearing stylish clothing

### ISSUE THREAD

**Issue by Relyksboa** [CleverRaven/Cataclysm-DDA#35781]
# Describe the bug

Using a musical instrument or listening to an mp3 player while wearing stylish clothing seems to cause the music morale buff to sap morale from the stylish clothing buff

# Steps To Reproduce

1. Wear any clothing with the FANCY or VERY_FANCY tags and observe correct morale levels from the clothing
2, use an instrument or an mp3 player and wait 5 or so minutes
3. check the moral menu and do the math to determine that the stylish buff has decreased morale despite not taking off any of the clothes

# Expected behavior

The music buff should not sap points from the stylish buff.

# Screenshots
EX: wearing a wedding dress (+10 morale) and a wedding veil (+6 Morale) for a total for 16 morale
![Before Music](https://user-images.githubusercontent.com/52992503/69894728-772e9980-12d8-11ea-9456-d5cba9931812.PNG)
As seen here (after some quick maffs), the current music buff is 9, while the stylish buff is 12.
![after music](https://user-images.githubusercontent.com/52992503/69894734-a34a1a80-12d8-11ea-8f6d-9554fb09c7d9.PNG)

# Versions and configuration

 - OS: windows
 - Game Version: 0.D-9759-g0d2c11b
 - Graphics version: terminal
 - Mods loaded: dda, no npc needs

# Additional context
n/a

**Comment by kevingranade** [comment]
Morale from different sources is added together using a formula that reduces the impact of multiple sources, see #29396
