### ISSUE TITLE
Dino Dave Mission NullPtr if asked for new job immediately after completing previous

### ISSUE THREAD

**Issue by SpellingSword** [CleverRaven/Cataclysm-DDA#35799]
# Describe the bug

Dino Dave will ALWAYS give a NullPtr bug instead of a proper mission when asking for a new one in the same dialogue window as the one you turned in the last one. 

Closing the dialogue after completing a mission and talking to him again allows to get the next one without bugs.

# Steps To Reproduce

1. Complete DD's mission
2. Without saying "bye" ask if he has any jobs for you
3. Get NullPtr bug

# Expected behavior

Should work the same as if you close the dialogue first

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-9759-g0d2c11b [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    No Fungal Monsters [No_Fungi]
]

# Additional context

I first noticed it after completing the small cardboard mission, but couldn't reproduce because it didn't happen after reload (Since I quit the conversation to save, after turning it in).

Here's a save file where it is reproducible:
[Enigma.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3907908/Enigma.zip)

To avoid the bug, turn in the medium boxes, say goodbye, THEN talk again and ask for a new mission.

**Comment by I-am-Erk** [comment]
Well, I can't find anything unusual about dino dave's missions as opposed to pretty much anyone else's, so I'm not sure what's up here.
