### ISSUE TITLE
Brioche (food item) can't be used for crafting

### ISSUE THREAD

**Issue by Silvenius** [CleverRaven/Cataclysm-DDA#35814]
Game version:

Operating system:

Tiles or curses:

Mods active:

### Expected behavior
Brioche (a kind of roll) should be usable to craft sandwiches. 

### Actual behavior
Brioche rolls are unable to be used for anything other than eating them plain

### Steps to reproduce the behavior
Acquire brioche, crafting menu

**Comment by Fris0uman** [comment]
Just need someone to add more recipe using the item.
