### ISSUE TITLE
Fire does not spread while on the ground

### ISSUE THREAD

**Issue by eternalnight264** [CleverRaven/Cataclysm-DDA#35824]
# Describe the bug

When placing a body or pile of bodies on the floor outside on multiple adjacent tiles, and then applying wood underneath them, lighting one pile of wood does not spread the fire to the adjacent tiles.

When approaching a fungal tower and lighting the fungal bed on fire, or a fungal stalk, the fire does not spread to adjacent tiles.

# Steps To Reproduce

1. Start a world.
2. Kill zombies/find tower
3. Get lighter
4. Light a fire on desired object
5. Fire does not spread beyond the tile you set on fire, said fire goes out when the fuel is exhausted.

# Expected behavior

Fires used to spread to adjacent, burnable tiles and objects. When lighting multiple corners of a fungal bed in clear weather, I expect it to spread to adjacent tiles.

Fires used to be a good way to dispose of rotting bodies, the fires easily spread to other piles of wood nearby and burned the corpses and things I wanted to trash.

This makes sense because fire should spread to nearby burnable objects, especially when the fire becomes 'raging'.

# Screenshots

[Here is the fire at 'raging'.](https://i.gyazo.com/402e9138ecdafe80609ea61cb31b6ad6.png)
[Here are the wind conditions.](https://i.gyazo.com/5e057f590b7b17b252fd77b1dd345e3e.png)

# Versions and configuration

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3913947/debug.log)

 - OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-9800-g248b687 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Safe Autodoc [safeautodoc],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Extended Realistic Guns [realguns],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Crazy Cataclysm [crazy_cataclysm],
    Mutant NPCs [mutant_npcs],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Mapgen Demo [mapgen_demo],
    Urban Development [Urban_Development],
    Boats [boats],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Classes and Scenarios Mod [more_classes_scenarios],
    Classic Roguelike Classes [RL_Classes],
    Manual Bionic Installation [manualbionicinstall],
    Stats Through Skills [StatsThroughSkills],
    No Filthy Clothing [no_filthy_clothing],
    Sleep Deprivation [sleepdeprivation],
    Garden Pots [growable-pots],
    Mythical Martial Arts [MMA],
    Alternative Map Key [alt_map_key],
    C.R.I.T Expansion Mod [crt_expansion],
    Hydroponics [hydroponics],
    Necromancy [necromancy],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Magiclysm [magiclysm],
    No Rail Stations [No_Rail_Stations],
    Roadheader and other mining vehicles [Heavy miners],
    Stats Through Kills [stats_through_kills],
    Fuji's Military Profession Pack [fuji_mpp]

# Additional context

It used to work, now it doesn't. I am just confused as to why. It probably has an easy fix, but I have tried to reload my game, I have tried to change the wind direction through the debug menu, none of it works.

This persists across saves.

**Comment by eternalnight264** [comment]
I have also added two extra screenshots where I show another save I just started where the fire also does not spread.

[Another 'Raging' fire](https://i.gyazo.com/fc85b9f6e25cdbeade8af7a39ec96883.jpg)

[Several hours later.. still not spread](https://i.gyazo.com/9f685a12b059a6d97d0bd550938d196f.png)

**Comment by anothersimulacrum** [comment]
Could you upload your save?

**Comment by eternalnight264** [comment]
[You can see where I even attempted to teleport around, thinking maybe a different area with less zombies might have better fire? I am unsure.](https://github.com/CleverRaven/Cataclysm-DDA/files/3917073/New.England.-.Copy.zip)

**Comment by adamdeno** [comment]
is there a setting for the fire to spread? if so maybe check it up if the flag exists , maybe the game thinks the fire cannot spread or something has made the fire not able to spread

just assumtions

**Comment by eternalnight264** [comment]
I've tried it on asphalt (Roads) fields (On building tiles) and fields (On actual field tiles and forests.) The only place the fire actually spreads is if the tile itself is flammable. (Wooden floor, etc.)

As far as I know, the fire should be spreading to other flammable objects adjacent to it.

**Comment by adamdeno** [comment]
it took at least 1 hour for me to spread both indoors and outdoors
**Try placing 3/4 tiles of fire next each other , that way it might spread**

**Comment by wapcaplet** [comment]
I can partially confirm this in 0.E-5877-g963edfda5d

Given several adjacent piles of flammable items (blankets, clothes, planks), if I light one of them on fire, it will not spread to the adjacent piles. The same is true of corpses.

![image](https://user-images.githubusercontent.com/238395/93010168-a8661680-f546-11ea-9243-bb5b93f51fdf.png)

However I cannot reproduce the issue with fungal beds. The fire spreads just fine through those, after lighting only one spot.

![image](https://user-images.githubusercontent.com/238395/93010196-fa0ea100-f546-11ea-817a-d8fb877dec17.png)

**Comment by KorGgenT** [comment]
can we confirm this is still an issue again now that fire spread code has been adjusted recently?
