### ISSUE TITLE
Glasses should be "flimsy"

### ISSUE THREAD

**Issue by Aphegis** [CleverRaven/Cataclysm-DDA#35820]
**The problem:**
Currently, the game simulates damage to the player's character's eyes, and this is usually a place where the player rarely has items that provide protection. However, a problem arises when the player is wearing glasses, sometimes you get eye damage, but your glasses remain intact, this is highly unrealistic and makes the "near sighted, far sighted" traits more OP than they should be. Currently, they don't provide any big debuff, because finding glasses in the game is extremely easy and your glasses rarely break.

** Describe the solution you want **
The flimsy tag should be added to reading glasses / bifocal glasses / glasses made of fragile materials.

** Describe the alternatives you considered **
Keep the "short-sighted / far-sighted" traits as 4 free points in character creation.

** Additional Context **
I don't know if wearable items can have a "flimsy" label, but even if they don't, in my opinion, it would be worth creating this feature.
This change would slightly weaken the "near-sighted/far-sighted" traits, in my opinion, a necessary rebalancing, rather than simply lowering the points from those traits in the character creation.

**Comment by Xion350** [comment]
The `FRAGILE` flag does indeed work on Eyeglasses.  I don't know how it would affect them in combat, or how long/many hits they would last since I can't think of an easy way to test them.
