### ISSUE TITLE
Any page larger than main menu screen will appear behind main menu instead of closing

### ISSUE THREAD

**Issue by adamdeno** [CleverRaven/Cataclysm-DDA#35835]
Game version: 
> 0.D-9811-g6b32e99 (tiles)

Operating system: 
> Windows 10

Tiles or curses: 
> Tiles

Mods active:
![mods](https://user-images.githubusercontent.com/41305926/70090355-a881cf00-1622-11ea-80a7-d695cb688129.PNG)

### Expected behavior
 
![expect](https://user-images.githubusercontent.com/41305926/70090480-f1398800-1622-11ea-94bd-80fb3696e810.PNG)

### Actual behavior

![actual](https://user-images.githubusercontent.com/41305926/70090596-26de7100-1623-11ea-8190-bbb92e0590c7.PNG)

### Steps to reproduce the behavior
open any window larger than main menu
all while selecting "Windowed Borderless" setting in graphics tab

**Comment by Night-Pryanik** [comment]
I guess changes made in #35694 is the culprit.
