### ISSUE TITLE
Construction: Blueprint zone not functioning

### ISSUE THREAD

**Issue by alken2** [CleverRaven/Cataclysm-DDA#35837]
# Describe the bug

No constructions are performed when either the character or a follower attempts to perform the zone activity for a 'Construction: Blueprint' zone

# Steps To Reproduce

1. Enter the Zone Manager and add a 'Construction: Blueprint' zone
2. Choose any construction (preferably ones with tools and components available)
3. Exit the Zone Manager and perform the 'Construct plots' zone activity
4. No construction is performed

OR

1. Enter the Zone Manager and add a 'Construction: Blueprint' zone
2. Choose any construction (preferably ones with tools and components available)
3. Ask a follower to do construction work
4. No construction is performed, yet the NPC immediately "completes" the assigned task 

# Expected behavior

The 'Construction: Blueprint' zone should allow the character or NPCs to perform as many available stages of the chosen construction as possible given components and tools.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-9800-g248b687 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Garden Pots [growable-pots],
    Hydroponics [hydroponics],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    No Rail Stations [No_Rail_Stations],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Roadheader and other mining vehicles [Heavy miners],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by wapcaplet** [comment]
Cannot reproduce. I used a construction blueprint zone to build a crafting spot, deconstruct several benches, and build a table. All worked as expected.


- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-5147-ge23fd18712 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
