### ISSUE TITLE
Reinforced vending machines in gun stores spawn only 1 round of each ammo type

### ISSUE THREAD

**Issue by SpellingSword** [CleverRaven/Cataclysm-DDA#35832]
# Describe the bug

The vending machines have exactly 1 of each ammo type in them. I assume this is not intended?

# Expected behavior

A reasonable amount of ammo in vending machines

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-9802-gfadcffd [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    No Fungal Monsters [No_Fungi]
]

**Comment by Night-Pryanik** [comment]
It's not an item spawning bug. Ammo spawns as intended:

![изображение](https://user-images.githubusercontent.com/11132525/70335827-7ca05c80-1861-11ea-9904-3ebb8a558bcd.png)

In this example game spawned 2 stacks of .38 FMJ (2x40 = 80). 
The bug in enumeration numbers on the left side. It should show "1, 2, 3" etc, but for some reason it show only 1.
