### ISSUE TITLE
After starting a new world (or maybe running into an unexplored building) , doors behave weirdly giving wrong messages.

### ISSUE THREAD

**Issue by adamdeno** [CleverRaven/Cataclysm-DDA#35841]
# Describe the bug

When starting a new world or just going to a new unexplored building , Pressing `e` on the door will give you a message that the door is locked , yet when you move at it or press `o` the door opens despite the message shown.

**P.S: I am not sure if this happens to all  doors...**

# Steps To Reproduce

1. Find any unexplored building.
2. Try to pressing `e` on the door.
3. Gives Locked door message , despite it being opened and closed normally

# Expected behavior

nothing.

# Screenshots

![door1](https://user-images.githubusercontent.com/41305926/70094461-3cf02f80-162b-11ea-911f-d78676c3517c.PNG)

![door2](https://user-images.githubusercontent.com/41305926/70094473-4083b680-162b-11ea-9af6-856ddd6f4d12.PNG)

# Versions and configuration

 - OS: 
> Windows 10
 - Game Version: 
> 0.D-9811-g6b32e99 (tiles)
 - Graphics version:
> Tiles
 - Mods loaded: 

![mods](https://user-images.githubusercontent.com/41305926/70094582-7aed5380-162b-11ea-8038-07f4ff7b8a3e.PNG)

# Additional context

i just noticed it and made this bug report.

**Comment by Night-Pryanik** [comment]
Can't confirm this on 0.D-9825. Could you please provide a savegame where this reliably happens?

Do you have a crowbar or lockpicks in your inventory?

**Comment by adamdeno** [comment]
i was starting as "survivor" profession  and i was in my starting house.

**Comment by adamdeno** [comment]
i also have it on the most recent build
