### ISSUE TITLE
Faction camp food: bird food is overpowered

### ISSUE THREAD

**Issue by skybluecat** [CleverRaven/Cataclysm-DDA#35848]
# Describe the bug

The player character can't eat bird food. But using "Distribute food" in faction camps, bird food counts as 400 kcal each (which is a lot) even though the seeds used to craft them may provide no calories. Also Cattle Fodder can be distributed as well, but at least its caloric content is normal.

# Steps To Reproduce

Have Survival 1 and Cooking 1 and a faction camp. Craft some bird food (with some seeds, like decorative plant seeds that can be harvested easily, which have no calories BTW). Use Distribute Food on bird food and they are worth 400 kcal each.

# Expected behavior

Non-human food should not be accepted by Distribute Food. 

Alternatively, make Cattle fodder and Bird food edible (why only let NPCs eat them?) but make bird food have more reasonable caloric contents depending on the materials used. If so, seeds should probably provide some calories as well.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-9802-gfadcffd [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by aoae23** [comment]
These is something fowl about this bug

**Comment by Xion350** [comment]
You can already eat Cattle fodder and Bird food edible by having the right mutations.  (Cat food and Dog food also get a enjoyment boost by having those mutation lines.)  It'd be more thematic to just fix it and disallow it as food to distribute for camps.  I'm sure there's other situations where inedible foods are viable to distribute.
