### ISSUE TITLE
Make FEMA evacuation pamphlet "looks_like": "newest_newspaper" instead "newspaper"

### ISSUE THREAD

**Issue by Lamandus** [CleverRaven/Cataclysm-DDA#35858]
Since the FEMA pamphlet is a new object, wouldn't it be a good idea to make it look like a paper note? At least until the tilesetprocers catch up?

Edit: as @sah4001 correctly stated, it "looks like newspaper" but since "newspaper" is not an valid id, it returns "false", so to speak, and should be "newest_newspaper" instead.

**Comment by sah4001** [comment]
It currently looks like newspaper at the time of writing.

**Comment by Lamandus** [comment]
> 
> 
> It currently looks like newspaper at the time of writing.

Yes it does, but there is no id named "newspaper".
So it should be either newest_newspaper or weeks_old_newspaper, or am I wrong?

**Comment by sah4001** [comment]
you are right, newest newspaper seems best

**Comment by sah4001** [comment]
Pull request made

**Comment by Lamandus** [comment]
> 
> 
> Pull request made

thanks mate. Closing down!
