### ISSUE TITLE
Stereo system in cars doesn't give info of the music playing

### ISSUE THREAD

**Issue by cornupis** [CleverRaven/Cataclysm-DDA#35854]
Game version:0.D-9787

Operating system:Linux

Tiles or curses:tiles

Mods active:none

### Expected behavior
In stable there was info about the music playing while driving
### Actual behavior
no info of music sound is 15
### Steps to reproduce the behavior
turn on stereo system in car

**Comment by adamdeno** [comment]
have you waited for a while? it some times gives you what is playing on the logs from time to time , i will check it here too

**Comment by cornupis** [comment]
I have been driving for a little while and no info. The music morale is working and the sound but no message of the type of music I am listening to.

**Comment by Qrox** [comment]
I remember there is code to suppress sound messages when the sound originates from the player's tile. Maybe that's the culprit here?
