### ISSUE TITLE
Missing fouling icon/character

### ISSUE THREAD

**Issue by RDru** [CleverRaven/Cataclysm-DDA#35856]
# Describe the bug

I have few weapons that I found after it was implemented and they have the icon.
All guns I'm finding now don't have it.
Using the gun adds fouling but doesn't add icon.
Found guns can have fouling in description but don't have icon.

# Steps To Reproduce

# Expected behavior

Icon should be visible

# Screenshots

here you can see the weapon without icon but with fouling in description:
![1](https://user-images.githubusercontent.com/26722636/70152130-f2af9280-16ac-11ea-938e-57667cfdcf07.png)

# Versions and configuration
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-9827-g4b589b7 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Classes and Scenarios Mod [more_classes_scenarios],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    No Fungal Monsters [No_Fungi],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Alternative Map Key [alt_map_key],
    Vehicle Additions Pack [blazemod]
]

# Additional context

**Comment by RDru** [comment]
nvm, it works

**Comment by AlexMooney** [comment]
I'm [not able to see the fouling characters](https://github.com/CleverRaven/Cataclysm-DDA/issues/36157) even though my ttf font has the unicode glyphs.

### Inconsolata

![Screenshot from 2019-12-16 10-41-46](https://user-images.githubusercontent.com/8269566/70933389-c3741c00-1ff0-11ea-9f5a-7b8d59f44f65.png)

![image](https://user-images.githubusercontent.com/8269566/70933465-e1418100-1ff0-11ea-8f29-3872ff3e0f10.png)

---

### Unifont

![image](https://user-images.githubusercontent.com/8269566/70933694-472e0880-1ff1-11ea-8b75-0a8119f834e6.png)

![image](https://user-images.githubusercontent.com/8269566/70933559-0df59880-1ff1-11ea-9fd4-0511ac79389f.png)
