### ISSUE TITLE
Activating "Self-Aware" mutation gives wake-up text

### ISSUE THREAD

**Issue by SpellingSword** [CleverRaven/Cataclysm-DDA#35867]
# Describe the bug

Using Self-Aware from the mutation page writes text into the log, alongside the actual health value. Right now the text is the same as for when you wake up, which is not what you'd expect. 

# Steps To Reproduce

1. Use the Self-Aware mutation
2. Wake up?

# Expected behavior

Either different text or no text at all, just the value.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-9827-g4b589b7 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    No Fungal Monsters [No_Fungi]
]

**Comment by TechyBen** [comment]
Seems like a feature not a bug... though I cannot really comment on my success on waking myself up with my IRL self aware stat. XD
