### ISSUE TITLE
Defining directional bias for car textures

### ISSUE THREAD

**Issue by Zupercharged** [CleverRaven/Cataclysm-DDA#35861]
**Is your feature request related to a problem? Please describe.**  
The problem originated from my attempts to make my 'humvee' actually somewhat resemble the genuine article. I took some printscreens in game and proceeded to mess around with the tiles in MS paint resulting in this:
![Humvee retextured](https://user-images.githubusercontent.com/58523066/70163795-f399f180-16b7-11ea-98ce-d3b7c4398f64.png)
The immediate issue here is the fact that to have a windscreen texture like that, the game would have to have windows be installed similar to hull boards or frames where you can pick from a selection of symbols each representing a particular side, some with a unique texture to match that part. 

The second but more significant issue is with side textures such as the doors and side boards. Currently the textures must be designed such that it is symmetrical so that it works either side of the car. The problem with this is that symmetrical side tiles cannot be very detailed, nor clearly reflect which side is inside or outside, limiting the visuals of the car to what we have currently.

**Describe the solution you'd like**  
The solution to the first problem is simply to have more structural components be supported by the current directionality designators, like so:

![Window textures](https://user-images.githubusercontent.com/58523066/70164055-6905c200-16b8-11ea-97b4-ec2147b1ec14.png)
What I suggest for the main issue is that when building the car, when one selects the side part ( | ), they then get asked to define the outside via the additional query (arrow key left) or (arrow key right). The part on the schematic still just shows as ( | ) but it now has a directional bias, which when tiles are enabled will flip them to face the correct direction. 

Similar choices for doors, seats and other less structural assets would also be beneficial simply by adding (arrow key up) and (arrow key down) to the possible choices.

Such a change should not have any compatibility issues with existing saves or tilesets. Car sides are still ( | ) and the existing tile sets are symmetrical and so wouldn't care either way. Meanwhile the the benefits of this is that the framework would exist for more detailed vehicle tiles down the line, this is just a mock up but it serves to demonstrate:

![Texture overhaul](https://user-images.githubusercontent.com/58523066/70165281-89cf1700-16ba-11ea-98b2-14681ac845b0.png)

**Describe alternatives you've considered**  
To be absolutely clear the issues and solutions here are solely in relation to visually improving vehicle tiles by making a concrete proposal on how it could be achieved. The alternative would be to simply not make a change. Cars will still be cars either way.

**Additional context**  
![Humvee evolution](https://user-images.githubusercontent.com/58523066/70166433-a704e500-16bc-11ea-9097-683dc84db2d4.png)
_A side-by-side comparison of the original and retextured Humvee tiles. Note the sideways facing doors and alternate windscreen design._

**Comment by ZhilkinSerg** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/projects/34

**Comment by Zupercharged** [comment]
Happy to see that such things are being taken seriously. However I am fairly certain that what I have proposed is a different solution to a similar goal, that being a tile framework that makes cars look nice. The other relevant proposal is https://github.com/CleverRaven/Cataclysm-DDA/issues/34899 which aims to create a framework for multi-tiles (similar to how couches link if I understand correctly) to allow car tiles to automatically arrange themselves to make nice looking car.

My proposal differs in that it remains within the bounds of the current individual tile system, merely adding an extra layer of options to allow for more customisable tile layouts in order to achieve the same effect of a nice looking car. My proposal is by personal assessment smaller in scope since it doesn't revolve around the implementation of an entirely new framework, while still arguably achieving similar results. 

Indeed the option for players to choose which way certain assets face (ie making chairs in the back of the APC face inwards) is a function entirely compatible with a multi-tile hull solution, and an option that I think would greatly benefit vehicle aesthetics as much as nice looking hulls.

**Comment by mouseturd** [comment]
I just want to be able to paint my car different colors

**Comment by I-am-Erk** [comment]
These are nice tiles, why aren't you contributing to ultica ;)

**Comment by mlangsdorf** [comment]
If you want to add directional doors and windshields, it's a pretty straightforward JSON change.

**Comment by I-am-Erk** [comment]
0.E is out. I would really like to see this implemented now kthx. It's a lot of JSON work but it would make vehicles possible so I can finish Ultica.

**Comment by mlangsdorf** [comment]
Closing this because we have directional variants for everything and when #42803 merges, we'll have an easy system for adding additional directional variants.
