### ISSUE TITLE
bashing weapons operate normally while swimming in deep water

### ISSUE THREAD

**Issue by Silvenius** [CleverRaven/Cataclysm-DDA#35879]
# Describe the bug

Even a trained swimmer would have extreme difficulty wielding a swung (bashing) weapon against a target on the surface, and find it impossible vs a submerged foe.

# Steps To Reproduce

Have bashing weapon, engage foe while swimming in deep water

# Expected behavior

I'd expect an error message for any bashing weapon while swimming, or have a VERY substantial penalty to strike with a one-handed weapon only

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

 - OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
 - Game Version: [from the main menu, e.g. 0.C-29938-g90f5268437]
 - Graphics version: [Tiles or Terminal]
 - Mods loaded: [e.g.dda, boats, hacktheplanet, StatsThroughSkills]

# Additional context

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
