### ISSUE TITLE
Swimming in deep water does not ruin matchbooks

### ISSUE THREAD

**Issue by Silvenius** [CleverRaven/Cataclysm-DDA#35878]
# Describe the bug

Swimming in deep water without specialized watertight containers would realistically ruin matches very quickly, and certainly at least render them inoperable until dried.

# Steps To Reproduce
Have matchbook containing matches in inventory, swim in deep water

# Expected behavior

Matchbook (x) should have condition degraded or destroyed on contact with deep water

Ideally also describe *why* you expect it to happen.

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

 - OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
 - Game Version: [from the main menu, e.g. 0.C-29938-g90f5268437]
 - Graphics version: [Tiles or Terminal]
 - Mods loaded: [e.g.dda, boats, hacktheplanet, StatsThroughSkills]

# Additional context

**Comment by Sumguy62** [comment]
We don't have containers yet, so having waterproof containers to mitigate the "issue" of items being damaged by getting wet is impossible at this time. I'd hold off on "fixing" this until there's a way to protect items from water damage.

**Comment by wapcaplet** [comment]
Should be easy to do now since #47018
