### ISSUE TITLE
Aftershock error on loading world after updating

### ISSUE THREAD

**Issue by SpellingSword** [CleverRaven/Cataclysm-DDA#35894]
# Describe the bug

 DEBUG    : Error: data/mods//Aftershock/items/afs_bioparts.json: line 44:14: unrecognized volumetric unit

Like all mi-go bioparts the openings on this piece closed up after it was cut free and it seems to have gone into a form of hibernation with the pulses occurring slower and slower as it conserves energy.",
    "weight": "40 g",
    "volume":
             ^
              "250 mL",
    "price": 100,
    "to_hit": -1,

 FUNCTION : bool main_menu::load_character_tab(bool)
 FILE     : src/main_menu.cpp
 LINE     : 1053

# Steps To Reproduce

1. Update game from 2 builds ago
2. Get error on load

# Expected behavior
No error

**Comment by KorGgenT** [comment]
just needs to be changed to `ml` instead of `mL`

**Comment by anothersimulacrum** [comment]
The fix for this was merged
