### ISSUE TITLE
SD Card Decryption giving inaccesible recipes

### ISSUE THREAD

**Issue by MACIEKBAKI** [CleverRaven/Cataclysm-DDA#35908]
# Describe the bug
Decrypting science SD cards has a chance to give recipes that should be inaccesible normally.
# Steps To Reproduce

1. Grab a bunch of science SD cards
2. Grab a tablet PC
3. Keep decrypting SD cards
4. Get inaccesible recipe. Soon enough.

# Expected behavior

I expected the tablet PC to give me a normally accesible recipe - for example, for a switchblade or similar.

# Screenshots

![https://cdn.discordapp.com/attachments/252368751016542218/652621737917284400/unknown.png](https://cdn.discordapp.com/attachments/252368751016542218/652621737917284400/unknown.png)
![https://i.imgur.com/ky8ETSv.png](https://i.imgur.com/ky8ETSv.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-9787-g847e182 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Aftershock [aftershock],
    Cataclysm++ [Cata++],
    Arcana and Magic Items [Arcana],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Alternative Map Key [alt_map_key],
    EZ-Mode Medical [fast_healing],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks],
    No Fungal Monsters [No_Fungi],
    No Flaming Eyes [fuck_flaming_eyes], -- flaming eye blacklist I made for myself
    Prevent Zombie Revivication [no_reviving_zombies],
    Safe Autodoc [safeautodoc],
    Manual Bionic Installation [manualbionicinstall],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context
n/a

**Comment by KorGgenT** [comment]
Can you give me an example of a recipe that exists in the repo that you can get doing this? i want the minimum mod list in order for the reproduciton to be useful.

**Comment by KorGgenT** [comment]
fixed by #36566
