### ISSUE TITLE
Food found on zombies, especially decayed zombies, should be unappetizing

### ISSUE THREAD

**Issue by Silvenius** [CleverRaven/Cataclysm-DDA#35909]
**Is your feature request related to a problem? Please describe.**  

Mmmm! Malted milk balls in a rotting zombie corpse's pockets! 
Let's think about what a decaying body does when it's decomposing. Fluids leak from the body, in some zombie canons insects lay eggs on it, and at the very least it probably REEKS of rotting flesh. Again, bacterial action on zombies vary according to the writers, but I offer this real-world anecdote.

At some point during the MENA conflicts, a US soldier was recorded stripping snack food from the dead body of a foe. He opened and consumed the sealed, packaged snack food, and immediately vomited. "I can TASTE him," he choked. He lost his lunch.

Real dead bodies STINK. While I can see food being found on them being conceivably technically safe in some cases, SMELLS attach themselves to food items and packaging, and dead bodies SMELL. 

**Describe the solution you'd like**  

For SURE this would interact with the Squeamish and Strong Stomach trait. I could see this being implemented with an additional tag along the lines of [filthy] for food items, with no way to clean the items found. 

Another option would have the food found directly on Zombie corpses have a tag that makes it ONLY consumable by those with the Strong Stomach trait.

**Describe alternatives you've considered**  

**Additional context**

**Comment by anothersimulacrum** [comment]
This can be entirely implemented through JSON after #35813.

**Comment by Silvenius** [comment]
> This can be entirely implemented through JSON after #35813.

Another key distinction should be that the taste/condition of consumables should degrade according to type (sealed plastic bottles = least, unwrapped items and cardboard/porus packaging= most) over time if it occupies the same tile as a corpse which is rotting (and, to extrapolate this, to sufficient amounts of other rotting material). Therefore food on a fresh human body (as may be found in the first days of a world's spawn) may be in consumable condition, but that will change as the body shifts through the decomposition process.

**Comment by FuelType-Memes** [comment]
The zombies are not classic "zombies" I suggest reading the design doc: https://cataclysmdda.org/design-doc/#effects-of-blob-infection

**Comment by jeremyshannon** [comment]
I always assumed we were just abstracting out packages and individually wrapped candies and stuff, but come to think of it, that notion has been floating around my head since the Whales days, and why aren't they in little packages/boxes now?

**Comment by anothersimulacrum** [comment]
Because nobody has updated them to be. Sounds like an easy first PR.
