### ISSUE TITLE
Crash when telling Nurse at the Ranch that you are her friend

### ISSUE THREAD

**Issue by SpellingSword** [CleverRaven/Cataclysm-DDA#35907]
# Describe the bug

100 % reproducible. Telling a nurse "Because I'm your friend!" when asking for items results in a crash. Other options do not result in a crash.

# Steps To Reproduce

1. In the provided save file, ask for a new job from the Nurse
2. Request items
3. Choose "Because I'm your friend!" option
4. Crash

# Expected behavior

No crash

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-9846-g34ac4b8 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    No Fungal Monsters [No_Fungi]
]

# Additional context

Logs:
[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3934162/config.zip)

Save:
[Enigma.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3934179/Enigma.zip)

**Comment by ZhilkinSerg** [comment]
Cannot reproduce on latest master.

Please update and report if you still having this issue.

**Comment by ZhilkinSerg** [comment]
Still won't reproduce on latest master.
