### ISSUE TITLE
Consuming items/performing actions while operating a moving vehicle should roll against drive skill for involuntary direction change

### ISSUE THREAD

**Issue by Silvenius** [CleverRaven/Cataclysm-DDA#35902]
# Describe the bug

As of this writing, items can be consumed while operating a moving vehicle with the only effect to the vehicle being a straight continuing trajectory during the period of the action state.

# Steps To Reproduce

Be in functioning, mobile motor vehicle
operate vehicle forward or backward normally
consume item in inventory

# Expected behavior

I think multi-tasking should have more failure modes, namely a roll against Driving skill with a chance of left/right input without the character's direct intervention.

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

 - OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
 - Game Version: [from the main menu, e.g. 0.C-29938-g90f5268437]
 - Graphics version: [Tiles or Terminal]
 - Mods loaded: [e.g.dda, boats, hacktheplanet, StatsThroughSkills]

# Additional context

**Comment by Silvenius** [comment]
Note: in addition to L/R input, a chance of speed increase/decrease should also be layered in.

**Comment by kevingranade** [comment]
I'm far more inclined to add a prohibition to performing problematic actions while driving than add a chance to lose control of the vehicle.
