### ISSUE TITLE
Doing bumps of cocaine should take more time, with a risk of spillage/ coke should not be able to be consumed while swimming or being grappled

### ISSUE THREAD

**Issue by Silvenius** [CleverRaven/Cataclysm-DDA#35901]
# Describe the bug

From my understanding, in-game at this time it is possible to do bumps of coke while literally running, swimming, operating a vehicle, or being grappled by zombies (though the latter example would expose you to opportunity attacks). This is not at all accurate- insufflation of anything requires a still environment and a steady hand, or the user will spill everything.

a) If in hand-to-hand combat, realistically a character would NOT be able to use their fine motor skills to take a bump of coke. Readying even what users refer to as a 'key bump' (a small amount of powdered cocaine placed on the end of a key for insufflation) would require a controlled environment and the slightest jitter or shake would cause probable wastage and/or failure.
b)Swimmers would not be able to use this item in this way due to contamination of the product with water as well as the fine motor skills required to load and insufflate the drug.
c) Characters walking, running, or using roller skates (for example) should have varying rates of roll difficulty vs PER and DEX in order to perform the Consume Item command with this type of drug effectively, with a warning message. Error states should include spillage and/or doing too much.

# Steps To Reproduce
Character has cocaine (x) in inventory
Character is swimming, driving, or being grappled

# Expected behavior

1) Characters in motion or operating a vehicle should get a warning message if they try to take coke:

Warning! Attempting to use this item in motion may result in spillage and/or incorrect dosages. Proceed? (y/n)

And there should be a roll against PER and DEX (0.5*PER+0.5*DEX, for instance) to avoid spillage, with the margin of failure causing the message:

You spilled (3, for example) cocaine on your surroundings while attempting to use it.

The (3 or whatever #) referenced above should be removed from both inventory and the game, being regarded as 'lost' or destroyed with no item markers on the ground.

An alternative failure state would have the character accidentally consuming more uses of the item than the default 1 use, with predictable results (Stimulant Overdose, death, etc) if sufficient.

Using roller skates and running should have much higher difficulty levels for the roll than walking or crouch-walking, though all should be penalized. 

2) Darkness should be a factor as well, even for a character who is remaining still in a calm environment.
Characters using this item in darkness or while blind should get a warning message:

Warning! Attempting to use this item in the dark may result in incorrect dosages and/or spillage. Proceed? (y/n)

The penalties for low-light should be present but negligible, and the penalties for perfect darkness or blindness should stack with motion penalties.

3) Characters swimming or in hand-to-hand combat (being grappled is a good example) should get a failure message:

You cannot consume this item while swimming, grabbing objects, or while being grappled!

And this would result in no consumption taking place, with the action attempt being cancelled.

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

 - OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
 - Game Version: [from the main menu, e.g. 0.C-29938-g90f5268437]
 - Graphics version: [Tiles or Terminal]
 - Mods loaded: [e.g.dda, boats, hacktheplanet, StatsThroughSkills]

# Additional context

**Comment by thethunderhawk** [comment]
Afaik we don’t really make a distinction between snorting it or eating it, parachuting it with TP etc.

**Comment by Silvenius** [comment]
> Afaik we don’t really make a distinction between snorting it or eating it, parachuting it with TP, shooting it up, etc. I’m sure it’s currently treated like eating pills.

It seems to be treated like eating pills, and it shouldn't. Coke isn't very bioavailable orally although it may have an alternative use in-game as a short-to-medium term analsegic. I'll open another thread on those lines, maybe.

**Comment by Silvenius** [comment]
EDIT:
The film "Fear and Loathing in Las Vegas" has exactly the principle in this issue report-- a character attempts to use cocaine in a moving vehicle and fails, losing much of it.

**Comment by kevingranade** [comment]
I'm not particularly interested in adding this specifically for cocaine,
but most of this would be addressed by a generic system for comestibles
requiring time to consume and being at risk of being dropped if the player
is assaulted or in motion while manipulating said items.
