### ISSUE TITLE
Walking over broken glass and other terrain barefoot or in socks does not cause bad things to happen

### ISSUE THREAD

**Issue by Silvenius** [CleverRaven/Cataclysm-DDA#35915]
# Describe the bug

Ever seen DIE HARD?
A character can run naked after shattering a window over the broken glass and never have anything happen. Things should happen, especially if running or if knocked down.

# Steps To Reproduce

have nothing on feet, or just socks
enter broken glass in tile (for example)

# Expected behavior

Characters should have the possibility of injury if entering broken glass (for example) with inadequate footwear.
This includes bare feet, socks (effects may be mitigated by multiple layers of socks, such as 4x wool socks), and to a lesser extent open-top sandals or flip-flops.

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

 - OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
 - Game Version: [from the main menu, e.g. 0.C-29938-g90f5268437]
 - Graphics version: [Tiles or Terminal]
 - Mods loaded: [e.g.dda, boats, hacktheplanet, StatsThroughSkills]

# Additional context

**Comment by Silvenius** [comment]
NOTE: obviously effects should be mitigated somewhat with the Tough Feet trait, and made worse with Thin Skin

**Comment by tivec** [comment]
You already have a chance to take damage when walking over glass, maybe we can add a change to the trap to check for the player being barefeet?

**Comment by adamdeno** [comment]
or maybe add a flag to the tile if it contains something "sharp" and it would check if the player has foot wear , because not only glass there is scrap metal , nails , legos , etc

**Comment by TechyBen** [comment]
> You already have a chance to take damage when walking over glass, maybe we can add a change to the trap to check for the player being barefeet?

This might actually offer a system to improve traps. I was trying to throw some of the trip/spike traps for zeds to get caught in, then realised they only work if you "place/set" them. :(
