### ISSUE TITLE
Wearing footwear without socks does not cause problems

### ISSUE THREAD

**Issue by Silvenius** [CleverRaven/Cataclysm-DDA#35916]
# Describe the bug

Have you ever worn footwear without socks, particularly in a damp environment? Damage to one's feet becomes the norm.  As it is, a character can wear badly-fitting shoes without socks and never encounter any issue. 

# Steps To Reproduce

Wear footwear without socks

# Expected behavior

I'd expect persistent injury messages to develop that would eventually destroy character mobility and require disinfection and so on. These kinds of injuries may not seem obvious but become particularly debilitating in a survival scenario. 

Badly fitting footwear should be a nightmare without socks.

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

 - OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
 - Game Version: [from the main menu, e.g. 0.C-29938-g90f5268437]
 - Graphics version: [Tiles or Terminal]
 - Mods loaded: [e.g.dda, boats, hacktheplanet, StatsThroughSkills]

# Additional context

**Comment by tivec** [comment]
This all depends on the type of shoes though. I used to hike in sandals without socks, and that was by far the best when getting wet. Walking around in shoes without socks would be a pain though.

I don't know how much we want to modify the clothing system, but it might be an interesting thing to have some form of flag on footwear like CHAFING, and adding foot (leg?) damage over time when worn?

Question is if this might be something for the other clothing items, or if we want to go this deep.

**Comment by TechyBen** [comment]
Generally can be okish... worse if wet though!

**Comment by Amoebka** [comment]
Seems like a very poor work/result ratio. Socks and footwraps are trivially obtainable (as they should be), so in practice the player will virtually never care about this effect being in the game.

**Comment by Silvenius** [comment]
> Seems like a very poor work/result ratio. Socks and footwraps are trivially obtainable (as they should be), so in practice the player will virtually never care about this effect being in the game.

The fact that socks are readily available does not change the importance of putting this to rest. Food is readily available, to run by a similar argument, yet here we have a detailed nutrition and hydration system, with excreta only not modeled because we don't want to. Socks are ABSOLUTELY critical in a mid-to-long-term real world outdoor survival context, and I won't be proven wrong here.
