### ISSUE TITLE
Can no longer see through vehicle windshields

### ISSUE THREAD

**Issue by Saywarder** [CleverRaven/Cataclysm-DDA#35918]
Game version: 9962

Operating system: W10 x64

Tiles or curses: MshockXotto+patch12

Mods active: Disable NPC Needs, Magiclysm, Makeshift Items Mod, Cataclysm++, Hydroponics, Mining Mod, More Locations, Arcana and Magic Items, Stats Through Kills, Stats Through Skills, SpeedyDex

### Expected behavior
When you enter a vehicle, you can see forward through the windshield, sideways through the windows, etc.

### Actual behavior
When you enter a vehicle, the entire surrounding area becomes dark and unknown except for the tile you are standing on.

### Steps to reproduce the behavior
Enter any vehicle tile.

**Comment by KorGgenT** [comment]
are you crouching?

**Comment by Xion350** [comment]
You might be crouching, or you have curtains on the windows?

**Comment by ZhilkinSerg** [comment]
I bet on crouching.

**Comment by kevingranade** [comment]
Crouching.
