### ISSUE TITLE
Being grappled or struck in melee while operating a moving vehicle should affect vehicle steering

### ISSUE THREAD

**Issue by Silvenius** [CleverRaven/Cataclysm-DDA#35914]
# Describe the bug

Driving in your car, with a zombie in the backseat or on the console next to you, reaching over and grabbing you-- c'mon, we've all been there. But shouldn't it mess with our driving?

# Steps To Reproduce
Drive through crowd of zombies in a mobile, functioning car, get one of them in the car next to you, allow zombie to occupy adjacent tile in your vehicle, drive. The zombie will attack you normally, and your grapple/injury state does not affect the vehicle's mode of travel in any way.

# Expected behavior
I would expect rolls vs driving skill graded against injury and pain states if injured during vehicle operation and motion, with unintended L/R inputs and to a lesser extent forward/backward inputs occurring on roll failure. 

These effects should be tremendously exacerbated if grappled by a foe while attempting to drive.

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

 - OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
 - Game Version: [from the main menu, e.g. 0.C-29938-g90f5268437]
 - Graphics version: [Tiles or Terminal]
 - Mods loaded: [e.g.dda, boats, hacktheplanet, StatsThroughSkills]

# Additional context

**Comment by adamdeno** [comment]
maybe if you are grabbed too , they force you out of the vehicle along with being hit that cause messing the steering

**Comment by Night-Pryanik** [comment]
> maybe if you are grabbed too , they force you out of the vehicle along with being hit that cause messing the steering

That's what happening now. Sometimes it works too good - #22764.
