### ISSUE TITLE
Unaging meat on Steel butchers rack

### ISSUE THREAD

**Issue by Zupercharged** [CleverRaven/Cataclysm-DDA#35949]
# Describe the bug

Meat butchered on the metal meat butchering rack remained (Fresh) days after expiration, when taken off rack it instantly aged to rotten. Crafting preserved food with it while still on the rack registered it as fresh (vacuum sealing and canning in jars) and produced fresh preserved food. 

# Steps To Reproduce

1. Make a player with a metal butchering rack, dead animal and butchering tool (Optional vacuum sealer and plastic bags).
2. Butcher animal corpse on deployed rack.
3. Leave it a few days and check quality.
4. (Optional) Craft salted meat slices with old meat and check resulting quality.

# Expected behavior

Meat ages normally while on rack because that's how its supposed to work.

# Versions and configuration

23:35:33.905 :  GAME REPORT:
- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-9883-g8b7ffba [64-bit]
- Graphics Version: Tiles
- Mods loaded: 
    Dark Days Ahead [dda],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Cataclysm++ [Cata++],
    NPC traits [npc_traits],
    Zetsukaze's Hair - 0.D EDIT [zets_hair_extensions],
    More Locations [more_locations],
    Zet's Hair - More Locations [zets_hair_ext_more_locations],
    Fuji's More Buildings [FujiStruct],
    Mapgen Demo [mapgen_demo],
    No Rail Stations [No_Rail_Stations],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Roadheader and other mining vehicles [Heavy miners],
    Bionic Slots [cbm_slots],
    Classes and Scenarios Mod [more_classes_scenarios],
    Disable NPC Needs [no_npc_food],
    Fuji's Military Profession Pack [fuji_mpp],
    Sleep Deprivation [sleepdeprivation],
    SpeedyDex [speedydex],
    Graphical Overmap [Graphical_Overmap]

# Additional context

Butchers rack was salvaged from a butchers shop.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-12863.
