### ISSUE TITLE
Battery system bionic was not updated

### ISSUE THREAD

**Issue by CorruptInsurance** [CleverRaven/Cataclysm-DDA#35943]
# Describe the bug

Battery system does not give the expected amount of energy from comsuming a battery. For example, consuming a light battery gives 50j of energy, whereas it should really give 50kj of energy. As is, this bionic is worthless, as it is impossible to gather enough batteries to recharge you capacitance banks.

# Steps To Reproduce

1. Make a player with the battery system bionic, e.g bionic agent.
2. Use some energy.
3. Try to recharge with batteries.
4. Realise that the energy gain is far too small.

# Expected behavior

It is expected that there is a significant gain in energy when a light battery is consumed (+50kj).

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

 - OS: debian 9
 - Game Version: 0.D-9846-g34ac4b8
 - Graphics version: Tiles
 - Mods loaded: bionic slots, magiclysm.

# Additional context

**Comment by anothersimulacrum** [comment]
![cbm](https://user-images.githubusercontent.com/42699974/70380460-ea1cbd80-1933-11ea-9704-9e0965470313.gif)
Cannot reproduce.
