### ISSUE TITLE
Suggestion: Riot Armor Coverage Rebalance

### ISSUE THREAD

**Issue by Xenotrenium** [CleverRaven/Cataclysm-DDA#35947]
Game version:
0.D-9897-g8982fdb (tiles)
Operating system:
Windows 10
Tiles or curses:
Tiles
Mods active:
No relevant mods

### Expected behavior
Riot Armor having superiour protective capabilities compared to regular clothing
### Actual behavior
Riot armor having only 70% coverage

########

ACTUAL INGAME STATS
![_riot_armor](https://user-images.githubusercontent.com/15146006/70381322-53a6c700-1948-11ea-844b-fbf45eab62a4.png)
http://cdda-trunk.chezzo.com/armor_riot

TL;DR Suggestions:

Increase coverage to 95%
Fire Resistance 3
Acidic Resistance 1

########

_I am aware of a new coverage system in the works. The following is meant for the current state of armor and it's coverage mechanic._

I was disappointed in finding riot armor (again) to still be at a measly 70% coverage in which many other clothing types are vastly more protective. Given how players gravitate thowards approximations of 100% coverage clothing\armor, I would prefer if we could alter Riot Armor to have a much higher coverage rating than before for the following reasons:

**Thematic & Balance Comparison**
-Comparing Riot Armor to many other armors in the game makes one question why any Police-force would use it for it's intended purpose. Why don't we see Riot Control Police walk around with Leather Jackets which are arguably much better? 
![image](https://user-images.githubusercontent.com/15146006/70381070-8222a300-1944-11ea-846b-05d4a4dcd2fe.png)

**Inadequate Real World Representation**
![_riot](https://user-images.githubusercontent.com/15146006/70381302-16dad000-1948-11ea-98bb-84b4edb221fd.jpg)
-In the real world, Riot Control Armor may only cover the most important parts of the body with hard plating and soft foam padding elsewhere to keep mobility relatively high, however that is not adequately represented. A 70% coverage unfortunately means that 30% of attacks will go through (AFAIK), which renders the suit quite inadequate for long term CQC, which the suit should excel in\at. I would interpret the actual coverage in the sheer surface area of the suit to possibly be approximately 70%, but effectively higher due to the layout of the armor. 

Furthermore, some additional suggestions to the armor:
From 
https://www.securityprousa.com/products/secpro-complete-hybrid-riot-suit
"They are designed to withstand hard blow, and prevent penetration or stabbing by sharp tools, anti-fire and anti-acidity.

The SecPro Riot Suit is currently deployed and passes the rigorous standards of our most elite law enforcement agencies, for quality, operational flexibility, protection area, energy absorbency, and flame resistance performance."

I interpret this as a freedom for us to take on new protective abilities as we deem fit, specifically **acidic and fire resistance**. 

Given that most riot control armor is extremely modular, having a "Riot Armor" in the game effectively puts itself in an odd position from the get go. Realistically we would have different types of Riot Gear encompassing many different parts of the body. 

I would probably prefer having said modularity to Riot Gear at some point, although at the moment I might be fine with just stating a few of my ideas on how to improve the Riot Armor currently in the game in which the first three are my highest confidence suggestions:

**Increase coverage to 95%
Fire Resistance 3
Acidic Resistance 1**
Extend coverage to Arms and Legs
Increase bash protection to 12
Increase cut protection to 10

Should we have the time and\or the new coverage system has arrived:
Make Riot Gear completely modular (shin guards\leg guards\shoulder pads)
Have different types of Riot Gear for different situations

I don't often post issues, please let me know if I made a mistake somewhere
Thanks for your time!

**Comment by anothersimulacrum** [comment]
> A 70% coverage unfortunately means that 30% of attacks will go through (AFAIK)

That is not how it works, see https://github.com/CleverRaven/Cataclysm-DDA/wiki/Armor-balance for how it does.

**Comment by Xenotrenium** [comment]
> > A 70% coverage unfortunately means that 30% of attacks will go through (AFAIK)
> 
> That is not how it works, see https://github.com/CleverRaven/Cataclysm-DDA/wiki/Armor-balance for how it does.

This was talked about in discord and is not accurate. If someone knows that coverage does not linearly correspond to the chance of applying armor to an attack, please share! Otherwise I do believe 70% coverage chance = 30% chance that armor does not apply.
