### ISSUE TITLE
Error: item group "mischw" already defined with type "collection"

### ISSUE THREAD

**Issue by snipercup** [CleverRaven/Cataclysm-DDA#35956]
# Describe the bug

When loading a game or starting a new one, this error shows:
 DEBUG    : Error: item group "mischw" already defined with type "collection"

 FUNCTION : bool main_menu::load_character_tab(bool)
 FILE     : src/main_menu.cpp
 LINE     : 1066

# Steps To Reproduce

1. Start new game
2. See error

# Expected behavior
To start/load a game normally

# Versions and configuration
Build 9971 and 9972 but not on 9970:

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-9898-g49b5702 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Craftable Gun Pack [craftgp],
    Makeshift Items Mod [makeshift],
    Mining Mod [Mining_Mod],
    Folding Parts pack [deoxymod],
    Simplified Nutrition [novitamins],
    Magiclysm [magiclysm],
    More Survival Tools [More_Survival_Tools],
    More Locations [more_locations],
    Garden Pots [growable-pots],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    Hydroponics [hydroponics],
    Fuji's More Buildings [FujiStruct],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Bens GF recipes [Tolerate_This],
    Icecoon's Arsenal [ew_pack],
    Cataclysm++ [Cata++],
    Urban Development [Urban_Development],
    Mythological Replicas [nw_pack],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs]
]

# Additional context
Was also reported on the discourse:
https://discourse.cataclysmdda.org/t/build-9972-error-on-starting-new-game/22177

**Comment by snipercup** [comment]
The discourse post refers to Aftershock and PK rebalancing but i'm not running those.

**Comment by snipercup** [comment]
Probably already fixed by #35958. I still need to confirm this.

**Comment by Fris0uman** [comment]
Pk is part of the repo?
Modular Turret also had the problem but it should be fixed by #35962

**Comment by Fris0uman** [comment]
Should be fixed now

**Comment by snipercup** [comment]
I updated to 9975 and I no longer have the issue.
