### ISSUE TITLE
Add faction ownership sensitivity to auto-pickup and other filters

### ISSUE THREAD

**Issue by CSHague** [CleverRaven/Cataclysm-DDA#35954]
**Is your feature request related to a problem? Please describe.**  
I noticed when moving around my base I tend to pick up things I have set on auto-pickup after I set them down. If I could set an auto-pickup filter for not-my-faction, I could avoid picking up things I already own. This would save on some minor headaches. Alternately, it will allow the player to prevent accidentally auto-looting other faction's items as well. 
**Describe the solution you'd like**  
A filter prefix, such as f: that could filter for faction ownership in various menus. 

For instance: -f:Your,nail would filter for nails that are not owned by the player faction "Your Followers". Excluding f:Old from auto-pickup would prevent accidental theft from the "Old Guard" faction.

**Describe alternatives you've considered**  
Well, a setting in auto-pickup for non-owned items could work as well, but a filter that works for other menus would be better.

**Comment by NeevAsteria** [comment]
There's a zone option (shift-y/capital Y). You can set 'no auto pickup zones' by using that.

**Comment by davidpwbrown** [comment]
This is a good idea, I'll see what I can do with it.
