### ISSUE TITLE
Map notes don't function with certain characters set as custom glyphs.

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#35965]
# Describe the bug
When trying to set a note over an evac center to note it was fully stocked, I tried to use a '+' as my custom glyph. This had strange effects.

# Steps To Reproduce

1. Open the map
2. Create a new note. Give it a + for a custom glyph and try giving it custom colors and text too. This causes strange things to happen in the notes system.

# Expected behavior
I should be able to set any glyph I like, right? If there are limits, maybe add a message for that!

# Screenshots
![image](https://user-images.githubusercontent.com/2125926/70393073-7ff82d00-19b4-11ea-9b72-4dd231e01594.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-9919-gf06fbcc [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    No Rail Stations [No_Rail_Stations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    [DP_MOD] Indicators: Chesthole [DP_AMAZING_CHEST_INDICATORS],
    sees-player icon, -attitude [sees_player_less_attitude],
    No Ants [No_Anthills],
    No Fungal Monsters [No_Fungi],
    Classes and Scenarios Mod [more_classes_scenarios],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins]
]

**Comment by Inglonias** [comment]
Ok. Not sure if I should close this, but I was able to get things to work properly if I set things up like this:

![image](https://user-images.githubusercontent.com/2125926/70393140-25130580-19b5-11ea-9438-8fe1335226bc.png)

**Comment by BevapDin** [comment]
You're using the wrong syntax. The text must `S:text` or `S:C;text` or `C;text` (with `S` being a symbol, `C` being a color code). Your text `S:textC;` does not fit. The game considers `textC` to be a color code.

**Comment by Inglonias** [comment]
Alright. I suspect this issue is at best a typo and at worst, unclear instructions.

Closing.
