### ISSUE TITLE
Automated turrets only attempt to target personnel, not moving vehicles

### ISSUE THREAD

**Issue by Silvenius** [CleverRaven/Cataclysm-DDA#35968]
# Describe the bug

Driving just outside of max range of an automated turret so that parts of the vehicle a character is driving are within the weapon's range does not trigger it to fire on a character's vehicle. 

# Steps To Reproduce
drive a multi-tile, mobile vehicle closer and closer to an automated turret (i.e. at a missile silo or roadblock)
it will only fire at the character once the character is close enough, and does not regard the vehicle the character is driving as a target, and it should

# Expected behavior

It might be expected that an automated weapon system would target an unidentified, mobile vehicle within its range, but this could be seen as a function of the weapon system's programming. Instead, it attempts to neutralize the driver by shooting through the vehicle, but ignores parts of the vehicle within weapon range if the driver is out of the range envelope.

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

 - OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
 - Game Version: [from the main menu, e.g. 0.C-29938-g90f5268437]
 - Graphics version: [Tiles or Terminal]
 - Mods loaded: [e.g.dda, boats, hacktheplanet, StatsThroughSkills]

# Additional context

**Comment by tenmillimaster** [comment]
This is a known issue, and desired behavior with *some* turrets.
