### ISSUE TITLE
Wrap up loose ends for new alcohols from #35164

### ISSUE THREAD

**Issue by DaviBones** [CleverRaven/Cataclysm-DDA#35973]
### Summary
To properly "finish" #35164, the following things should be done (see the PR for more details):
- Add inheritance to the new alcohols as I pointed out in a review.
- Capitalize proper nouns in the item names, and remove references to specific containers as pointed out by @Kodiologist.
- Add the new alcohols to recipes, and `cooking_components.json` lists, as pointed out by @Jovus.

**Comment by Jovus** [comment]
This looks like a good project for a new contributor who wants to get his feet wet with only very slightly more complicated JSONs. (That's me volunteering but noncommitally, and not before January due to travel.)

**Comment by LaVeyanFiend** [comment]
> This looks like a good project for a new contributor who wants to get his feet wet with only very slightly more complicated JSONs, and who wants to figure out how to link PRs and Issues through Github.

Nah, this is mine. 😈
