### ISSUE TITLE
Error on saving when unrelated damaged save is present but not loaded

### ISSUE THREAD

**Issue by esotericist** [CleverRaven/Cataclysm-DDA#35979]
# Describe the bug

When a save file that has been damaged/corrupted in a specific fashion is present -- even if it hasn't been loaded -- errors related to invalid contents of `worldoptions.json` are produced.

# Steps To Reproduce

Steps to reproduce the behavior with the attached save:
1. unpack `Keeler.zip` into saves folder
2. load any other save file (do not load Keeler)
3. attempt to save other save file
4. observe errors

Believed steps to reproduce the data corruption that resulted in the attached save:
1. create a new save in a recent experimental
2. load same save file in 0.D stable
3. save that file in 0.D stable
4. obtain newly broken save due to data migration being one-directional

# Expected behavior

Honestly a *completely different save* having *anything* invalid in it should never result in errors when saving a file that is itself not damaged.

That said, `worldoptions.json` is definitely screwed up here, and probably other things in the save file besides.

# Screenshots

screenshot, 'cuz you can't stop me (but debug.log is also attached):

![image](https://user-images.githubusercontent.com/1569754/70415753-3b9b7a00-1a12-11ea-9fc7-5ad40d9d917e.png)

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 19.10; Release: 19.10; Codename: eoan; 
- Game Version: 0.D-9847-g25470d8989-dirty [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

debug log file 

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3938289/debug.log)

corrupted save file

[Keeler.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3938291/Keeler.zip)

**Comment by Night-Pryanik** [comment]
I followed the confirmation steps: unpacked Keeler into saves folder and loaded my game from other world. I was able to successfully save game in my other world without any errors. 
I'm closing this until reconfirmed.
