### ISSUE TITLE
Cars loading around Refugee Center can spawn running

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#35987]
# Describe the bug

Not a high priority bug, but it seemed strange when a small horde of zombies came clambering at a window at the refugee center and I went outside to put them down and I saw that they were summoned by a running vehicle.  

# Steps To Reproduce

1. Goto Refugee Center
2. Are there cars spawned? 
3. Are some of them currently running?
4. Note that you can't interact to stop the sound without angering the Free Traders.
5. Guards also sometimes noticed the sound and wandered looking for it.

# Expected behavior

Cars outside the refugee center to not be running aimlessly as if abandoned by previous owners.

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

 - OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
 - Game Version: [from the main menu, e.g. 0.C-29938-g90f5268437]
 - Graphics version: [Tiles or Terminal]
 - Mods loaded: [e.g.dda, boats, hacktheplanet, StatsThroughSkills]

# Additional context

**Comment by cozardi** [comment]
I've seen the same happen on cities or some roads, I don't think it's a refugee center bug. It makes sense in the first few days after the cataclysm, but as of now you can run into a running car in day 130 after the cataclysm

**Comment by Rail-Runner** [comment]
Maybe just set all vehicles to never spawn with engine running? Reading the lore, it seems like most cars that would have been abandoned idling would have run out of fuel by the date of game start; even if not, zombies certainly would have smashed the still-running cars into scrap already.

**Comment by Orange01gaming** [comment]
> I've seen the same happen on cities or some roads, I don't think it's a refugee center bug. It makes sense in the first few days after the cataclysm, but as of now you can run into a running car in day 130 after the cataclysm

Perhaps this is another survivors car? Easier to explain than the food spoilage not happening.

**Comment by jkraybill** [comment]
I've also seen this occur with motorbikes at campsites, so it seems like a broader issue. It doesn't feel right. I agree with @Rail-Runner's (easy?) proposal that vehicles don't spawn running.
