### ISSUE TITLE
Sausage cannot be crafted with frozen meat.

### ISSUE THREAD

**Issue by Xion350** [CleverRaven/Cataclysm-DDA#35980]
# Describe the bug

Trying to craft Sausage with meat and Tallow that are currently frozen excludes them from the ingredient list.

![image](https://user-images.githubusercontent.com/13670135/70425720-4f0d0c00-1a37-11ea-9e3f-1b4b22250aff.png)

In this image I have just picked up all of the ingredients for the recipe but it isn't counting them as valid.

# Steps To Reproduce

1. Pick up Frozen meat or have it nearby along with the other ingredients
2. Try to craft Sausage with a loaded charcoal smoker and other tools on hand
3. Despite having all ingredients it isn't possible

# Expected behavior

Like other crafting recipes requiring meat it should be fine with crafting whether the meat is frozen or not.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-9993-g275c722 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by AMurkin** [comment]
Related PRs: #29699, #29727

**Comment by Xion350** [comment]
If it IS intentional, there should be some kind of indicator.  Even a small note on the recipe page that says "This cannot be crafted with frozen ingredients" or something.
