### ISSUE TITLE
Cannot get the location of the Refugee Center

### ISSUE THREAD

**Issue by scalpelenema** [CleverRaven/Cataclysm-DDA#35994]
# Describe the bug

Cannot get the location of the Refugee Center when accessing terminal in Evac Shelter

# Steps To Reproduce

1. Start a new game in Evac Shelter with working terminal.
2. Access the Terminal.
3. Press '3' & 'Q' - get the error message (see the screenshot). Press 'm' and 'M' - location of the quest is not shown

# Expected behavior

Well, seeing location coordinates, I guess )

(System - Debian, Version - latest Git, mods - Vanilla)

# Screenshots

![Снимок экрана_2019-12-10_10-50-24](https://user-images.githubusercontent.com/47364202/70514752-d85a3680-1b3c-11ea-90d8-6d31b7208aeb.png)

**Comment by ralreegorganon** [comment]
Please attach the save.

**Comment by scalpelenema** [comment]
[uncas.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3943975/uncas.zip)

**Comment by scalpelenema** [comment]
I guess that it not happens always, but around 50% of cases when you start a 'fixed scenario' with working terminal

**Comment by adamdeno** [comment]
happens most of the time , probably because the world has no refugee spawned... yet
