### ISSUE TITLE
Arcana monster has invalid flag

### ISSUE THREAD

**Issue by Alterforce** [CleverRaven/Cataclysm-DDA#36028]
# Describe the bug
Attempting to start a new game or load a new game with the Arcana mod in build 9990 results in not being able to play the world.

# Steps To Reproduce
1. Make a world with the Arcana mod in build 9990
2. Try to play in this world

# Expected behavior
Being able to play the world

# Screenshots
![arcana monster error](https://user-images.githubusercontent.com/43394039/70634606-7c42ff80-1c6d-11ea-8067-00a9323b25c3.png)

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-10074-g3de41d
 - Graphics version: Terminal
 - Mods loaded: 
Dark Days Ahead
Disable NPC Needs
Arcana and Magic Items<
Necromancy
Magiclysm
Mythological Replicas
Medieval and Historic Classes and Shields

# Additional context
I was able to play with the Arcana mod without issue on a previous version

**Comment by anothersimulacrum** [comment]
We don't have anything to do with Arcana, we can't do anything about this.
Please report this on Arcana's github repo.

**Comment by ymber** [comment]
We don't develop arcana, report it to the relevant maintainer. Regeneration flags are obsolete and some people haven't updated their mods to use the new regeneration attributes.
