### ISSUE TITLE
Eyeglasses/bifocals, while able to start a fire in sunlight, cannot be used to light rolled smokeables in same

### ISSUE THREAD

**Issue by Silvenius** [CleverRaven/Cataclysm-DDA#36031]
# Describe the bug

Lenses used to start fires (emergency whistle, bifocals, etc) in sunlight can't light cigarettes and joints 

# Steps To Reproduce

have rolled smokables (joint, cigarette, etc) in inventory
be in direct sunlight
have firestarting lens in inventory
attempt to 'consume' (light) rolled smokeable

# Expected behavior

A message:
You light your (item) by focusing the sun's rays.
conversion of (item) to (item) (lit)

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

 - OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
 - Game Version: [from the main menu, e.g. 0.C-29938-g90f5268437]
 - Graphics version: [Tiles or Terminal]
 - Mods loaded: [e.g.dda, boats, hacktheplanet, StatsThroughSkills]

# Additional context

**Comment by wapcaplet** [comment]
It looks like this has been fixed at some point. I could not reproduce the problem in 0.E-9737-g511ddcb179. Using bifocals or a whistle multitool, I can light a cigarette, cigar, or joint.
