### ISSUE TITLE
Generic Guns error: item on blacklist abzats does not exist

### ISSUE THREAD

**Issue by Jerimee** [CleverRaven/Cataclysm-DDA#36032]
# Describe the bug

On world generation, an error is thrown if the Generic Guns mod is enabled along with the base game. I've encountered this twice; both times with just the base game and this mod only enabled.

# Steps To Reproduce

1. New World
2. Enable base game and Generic Guns under the Content tab
3. Finalize and generate world

The error will then display: _"DEBUG    : item on blacklist abzats does not exist"_ (see more under Additional Context).

# Expected behavior

No errors reported.

# Versions and configuration

 - OS: Windows 7
 - Game Version: 0.D-10074-g3d4e41d (tiles) 9990
 - Graphics version: Tiles
 - Mods loaded: Generic Guns

# Additional context
```
DEBUG    : item on blacklist abzats does not exist

 FUNCTION : void Item_factory::finalize_item_blacklist()
 FILE     : src/item_factory.cpp
 LINE     : 467

```

A quick google returns, the Heavy Automatic Shotgun, or Abzats, is a makeshift firearm... Additionally I noticed a reference to it on line 8 of https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/mods/Generic_Guns/gg_guns_blacklist.json 

cc @nikheizen

**Comment by HarleyLorenzo** [comment]
I also had this error on a world of mine with generic guns, though I disabled the mod afterward.

**Comment by Jerimee** [comment]
There are a handful of other errors as well. I'm a bit confused as to why I don't always notice them... User error probably.
```

 DEBUG    : item on blacklist l_def_12 does not exist

 FUNCTION : void Item_factory::finalize_item_blacklist()
 FILE     : src/item_factory.cpp
 LINE     : 467

```

debug.log:
```

Backtrace emission took 0 seconds.
src/item_factory.cpp:467 [void Item_factory::finalize_item_blacklist()] item on blacklist abzats does not exist
19:36:12.676 ERROR : src/item_factory.cpp:467 [void Item_factory::finalize_item_blacklist()] item on blacklist l_def_12 does not exist
19:36:33.426 ERROR : (error message will follow backtrace)
    (@0x5f49fe[cataclysm-tiles.exe+0x1f49fe]), 
    (@0x5f503a[cataclysm-tiles.exe+0x1f503a]), 
    (@0x5f82c6[cataclysm-tiles.exe+0x1f82c6]), 
    (@0x835e4d[cataclysm-tiles.exe+0x435e4d]), 
    (@0x83954f[cataclysm-tiles.exe+0x43954f]), 
    (@0x78caf6[cataclysm-tiles.exe+0x38caf6]), 
    (@0x6e925b[cataclysm-tiles.exe+0x2e925b]), 
    (@0x713b95[cataclysm-tiles.exe+0x313b95]), 
    (@0x94511a[cataclysm-tiles.exe+0x54511a]), 
    (@0x948da9[cataclysm-tiles.exe+0x548da9]), 
    (IMG_LoadWEBP_RW+0x63f8f4@0x1717734[cataclysm-tiles.exe+0x1317734]), 
    (@0x4013ed[cataclysm-tiles.exe+0x13ed]), 
    (@0x4014fb[cataclysm-tiles.exe+0x14fb]), 
    (BaseThreadInitThunk+0xd@0x7765556d[kernel32.dll+0x1556d]), 
    (RtlUserThreadStart+0x1d@0x777b372d[ntdll.dll+0x5372d]), 
Backtrace emission took 0 seconds.
src/item_factory.cpp:467 [void Item_factory::finalize_item_blacklist()] item on blacklist surv_levershotgun does not exist
19:36:33.426 ERROR : src/item_factory.cpp:467 [void Item_factory::finalize_item_blacklist()] item on blacklist taurus38mag does not exist
19:36:33.427 ERROR : src/item_factory.cpp:467 [void Item_factory::finalize_item_blacklist()] item on blacklist taurus_38 does not exist
19:36:43.223 INFO : Loaded tileset: ChestHole16
19:42:06.919 : Log shutdown.
```

**Comment by Jerimee** [comment]
I think that the complete list is:

- surv_levershotgun
- taurus38mag
- taurus_38
- l_def_12
- abzats

Please note that so far as I can tell these errors can be ignored without impacting the resulting game.

**Comment by LaVeyanFiend** [comment]
Ewps, seems both I and @tenmillimaster forgot to update generic guns when we phased out the Taurus Pro .38 and those shotguns respectively.
Guess I'll take it then. ^_^

**Comment by anothersimulacrum** [comment]
Tenmillimaster is in the midst of reworking generic guns, may want to leave it to him.

**Comment by LaVeyanFiend** [comment]
It's only +2/-5, and causes visible load errors. I'm sure he can adjust the rework

**Comment by tenmillimaster** [comment]
This is acceptable to me.
