### ISSUE TITLE
meat vanished

### ISSUE THREAD

**Issue by Daebis** [CleverRaven/Cataclysm-DDA#36052]
> - OS: Linux
>     - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 18.04.3 LTS; Release: 18.04; Codename: bionic; 
> - Game Version: 0.D-10083-g84de815c4b [64-bit]
> - Graphics Version: Tiles
> - Mods loaded: [
>     Dark Days Ahead [dda],
>     Désactiver les besoins des PNJ [no_npc_food]
> ]

with auto compile launcher on french and 2ch soundpack & chestHole16 tilset 

i have 1 clean water bottle + 1 proteine powder + 1 limonade powder on my inventory.
and on me/near tin and bowl
i use "&" to "craft a protein stack" and ... vanished.
my savegame (if that help you )https://we.tl/t-RGdR9eeDK4
from /home/dae/.cataclysm-dda/save/Neely/

# Describe the bug

# Steps To Reproduce

1. Make a player with a gun, magazine, and some ammo.
2. Try to aim at a wall.
3. There's no way to increase aim level.

# Expected behavior

Ideally also describe *why* you expect it to happen.

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

 - OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
 - Game Version: [from the main menu, e.g. 0.C-29938-g90f5268437]
 - Graphics version: [Tiles or Terminal]
 - Mods loaded: [e.g.dda, boats, hacktheplanet, StatsThroughSkills]

# Additional context

**Comment by aoae23** [comment]
Did you correctly fill out the steps to reproduce? There's no way anyone can fix the bug if it can't be reproduced.

**Comment by KorGgenT** [comment]
please properly fill out the form, and erase the parts that were there as an example.

**Comment by Daebis** [comment]
not really a bug. my proteine soupe are just "teleported" somewhere on a storage.

**Comment by Night-Pryanik** [comment]
Should be closed then?
