### ISSUE TITLE
Segmentation error when trying to auto farm.

### ISSUE THREAD

**Issue by Lamandus** [CleverRaven/Cataclysm-DDA#36063]
# Describe the bug

Trying to autofarm "O" -> Farm plots will lead to that error:

# Steps To Reproduce

1. Load up my save. Press "O" and choose "Farm plots"

![error](https://user-images.githubusercontent.com/33199510/70773611-3f176400-1d78-11ea-9b77-081f967ce116.jpg)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-10146-g068c4f0 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    [DeadPeople] Zombie Revival Indicator [DP_ZOMBIE_REVIVAL_INDICATOR],
    0Graphical Overmap [0Graphical_Overmap],
    No Survivor Armor [no_survivor_armor],
    No Sci-Fi Equipment [no_scifi],
    No Flaming Weapons [no_flaming_weapons],
    No Fictional Guns [no_rivtech_guns],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex]
]

# Additional context
[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3959253/config.zip)
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3959257/save.zip)

**Comment by davidpwbrown** [comment]
I cannot reproduce on that save, on Linux, on latest master, I load it up and it performs the farming fine.

Your build isnt that old, but can you confirm this is still happening for you on latest experimental?

**Comment by Lamandus** [comment]
I couldn't reproduce it again. That is true.
