### ISSUE TITLE
Replace explosive projectile effect flags with explosion objects

### ISSUE THREAD

**Issue by ymber** [CleverRaven/Cataclysm-DDA#36072]
**Is your feature request related to a problem? Please describe.**  
Currently explosive projectiles are limited by having to use one of the effect flags that the code checks for.

**Describe the solution you'd like**  
Projectiles should define `explosion` attributes as other items do and the projectile flags for explosions should be removed.

**Comment by ZhilkinSerg** [comment]
I've started on jsonizing ammo effects here - https://github.com/ZhilkinSerg/Cataclysm-DDA/tree/refactor-ammo-effects (also there is a little more recent local version).

**Comment by ymber** [comment]
Closed by #36919.
