### ISSUE TITLE
Can't store screwdriver or stone hammer in hiking backpack or tool belt.

### ISSUE THREAD

**Issue by rah-jain** [CleverRaven/Cataclysm-DDA#36073]
# Describe the bug

I tried to Activate my **hiking backpack** (or **tool belt**) to store my **screwdriver** and **stone hammer** in it. The backpack says it has slots to store 2 items of between 0.25 and 2.50 L. The screwdriver is 0.25 L and the stone hammer is 0.50 L, so they should fit in the slots. (I did notice that a paring knife, which is 0.25 L _did_ fit in the backpack's item slot.) Maybe this is a rounding issue?

# Steps To Reproduce

1. Craft screwdriver, stone hammer, and hiking backpack (or tool belt).
2. Activate hiking backpack (or tool belt).
3. Get error that no "weapons" that can be put into the backpack (or belt) while screwdriver and stone hammer are both still in inventory.

# Expected behavior

Items that are within the size range should be able to be stored in the container. If some other restriction prevents the items from being stored, that restriction should be mentioned in the descriptions of the items.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-9598-g6af71bb [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Bens GF recipes [Tolerate_This],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Simplified Nutrition [novitamins],
    Sleep Deprivation [sleepdeprivation],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context
The **screwdriver** _was_ able to be stored in a **leather belt**.

**Comment by LaVeyanFiend** [comment]
1) The hiking backpack allows ``SHEATH_KNIFE`` and ``SHEATH_SWORD`` items.
2) The toolbelt allows ``BELT_CLIP`` items b/w .33-1L, and the stone hammer doesn't have ``BELT_CLIP``.

**Comment by rah-jain** [comment]
Thanks for digging into this. Is there really a need to assume that the backpack cannot have some sort of tool clip on it? Is it just a concern that it's too much flexibility for free? If so, that seems like some sort of moddability for armor is what is called for, where one can construct a sheath mod kit, a tool clip mod kit, etc, and attach those to mounting points on the armor.
