### ISSUE TITLE
Game warns of zombies being aimed at

### ISSUE THREAD

**Issue by glenmack** [CleverRaven/Cataclysm-DDA#36088]
### Expected behavior
Not interrupt aiming at a particular zombie to tell you it is there.

### Actual behavior
Only one zombie in sight, already aiming at it, steadying aim is interrupted to tell you X type zombie approaching.

### Steps to reproduce the behavior

Aim at approaching zombie with safe mode on.

**Comment by Ramza13** [comment]
Pretty sure #35983 will fix this.

**Comment by glenmack** [comment]
> Pretty sure #35983 will fix this.

From what I've read, no it doesn't. Your fix ignores things based on distance and z-level. Not on whether it is being aimed at or not. I will still want to be informed of other approaching monsters just not the particular one I'm aiming at because I already know it is there.

**Comment by Ramza13** [comment]
> > Pretty sure #35983 will fix this.
> 
> From what I've read, no it doesn't. Your fix ignores things based on distance and z-level. Not on whether it is being aimed at or not. I will still want to be informed of other approaching monsters just not the particular one I'm aiming at because I already know it is there.

Good point.

**Comment by JeanLucVanDamme** [comment]
> I will still want to be informed of other approaching monsters just not the particular one I'm aiming at because I already know it is there.

Agreed. This is incredibly irritating when playing as ranged characters. You're aiming at the only creature in sight, and this prompt comes up several times at different distances. Even more annoying when the creature is super low-powered and poses no threat at any distance.

**Comment by Ramza13** [comment]
So I have been looking into fixing this and have some questions.  

First while I remember this happening to me I'm having trouble reproducing it for testing, does anyone have steps/settings to force it to occur?

Second I noticed in the code that at present the warning about a monster being dangerously close will not happen while you are aiming regardless of target.  It would be quite easy to move this check from where it is to happen anytime you spot a monster.  

This isn't quite the ask but would be very easy and is already the behavior of the dangerously close warning which is supposed to be the last line of defense so it would standardize the behavior.

Would this be considered an acceptable fix?
