### ISSUE TITLE
Health Regen Significantly Less Than Expected

### ISSUE THREAD

**Issue by FracturedSolace** [CleverRaven/Cataclysm-DDA#36095]
Game version: 10189 Experimental

Operating system: Windows 10 x64

Tiles or curses: Tiles

Mods active: Disable NPC Needs and Mythological Replicas

### Expected behavior
Significant healing during sleep

### Actual behavior
Healing 5hp per body part with approx. 8 hours of sleep, despite not having imperceptive healer and hidden health stat at 10

### Steps to reproduce the behavior
Unsure, affected save file provided
[Glithced Character Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3963817/Glithced.Character.Save.zip)

**Comment by GGgatherer** [comment]
What is your first aid level? Did you disinfect/bandage your wounds?

**Comment by ZhilkinSerg** [comment]
Seems to be working as expected.

Base healing rate for player is 0.0001 hp per turn.

https://github.com/CleverRaven/Cataclysm-DDA/blob/72dbda868da802919366b475105d40aa5191224e/data/json/game_balance.json#L58-L64

This is 0.36 hp per hour or 2.88 hp per 8 hours. You've got 5 hp per same time which looks good for your high health.

See https://github.com/CleverRaven/Cataclysm-DDA/pull/31611 for reference.

**Comment by FracturedSolace** [comment]
I was unaware base healing was changed. This absolutely appears accurate given that change.
