### ISSUE TITLE
Training Spells from NPCs

### ISSUE THREAD

**Issue by araneyl** [CleverRaven/Cataclysm-DDA#36090]
# Describe the bug
Once completing a mission for a spellcasting npc, attempting to gain training in a spell that is unknown to the player produces an infinite loop of training.

# Steps To Reproduce

1. Find and complete mission for spellcasting NPC from magiclysm.
2. Ask for training in a spell unknown to the player.
3. Enter infinite training loop.

# Expected behavior
Theoretically, asking for training in a spell unknown to the player should teach the player the spell to level 0, just like the initial reading of a spell from a book or scroll.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-10157-gcf1dc76 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm]
]

# Additional context
Asking for training in a spell known to the player appears to work correctly. Learning a spell from the same spell group, such as asking to be trained in Cure Light Wounds while knowing any other Biomancer spell does not seem to impact the loop. Essentially it does not appear to be an issue with spell casting classes, but with learning a spell that is not already known.

[test npc spell learn.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3963365/test.npc.spell.learn.zip)

This is a world with a test character prepared to show the issue. The setup isn't difficult though, if there are issues with launching this save. To launch this save you will have to pull the files from the PR #35597 You will spawn in the wizard tower with all 3 spellcasting npcs next to you.

**Comment by davidpwbrown** [comment]
Its down to the time taken, some of the spells come out at over 100 hours.
Others appear to be 25 or so hours, and seeing as the train activity is based on player speed, having low speed can make it spiral out of control.

Until we have a framework for resuming training properly from incremental gains of a spell you dont know yet, ill just slash the amount of time to train by a huge amount to fix this short term.
