### ISSUE TITLE
crash after new character (cataclysm-tiles.exe)

### ISSUE THREAD

**Issue by Jerimee** [CleverRaven/Cataclysm-DDA#36091]
# Describe the bug

The game crashed right after new character creation. 

While I didn't attempt to reload, I don't anticipate that it will crash next time, as the game has been creating characters and regenerating the world several times this evening with no issue.

# Versions and configuration

windows 7
0.D-10157-gcf1dc76 (tiles)
9999

no mods enabled at all

# Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3963485/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3963486/crash.log)

**Comment by glenmack** [comment]
Were you doing a lab start? If so, this is probably related to the research centre mapgen crashing the game.

**Comment by Jerimee** [comment]
Not a lab start - I was doing standard evacuee / survivor

**Comment by ZhilkinSerg** [comment]
Unfortunately, we cannot go any further with the details provided (Windows stack trace is not that helpful yet). I will close it to clean up queue, but you can ping to reopen if you have more info to reproduce the crash.
