### ISSUE TITLE
CBM list in "manifesto" computer screen shows color tags as plaintext

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#36098]
# Describe the bug

Exactly what it says on the tin. Also, see attached screenshot.

# Steps To Reproduce

1. Load attached save
2. 'e'xamine adjacent terminal
3. Select 1-manifesto
4. See the same thing as in screenshot.

# Expected behavior

Either color tags should be processed as, well, color tags(i.e. make them change text color), or they should be truncated from the text on terminal.

# Screenshots

![cdda-colortags](https://user-images.githubusercontent.com/56833396/70849047-0aa4c480-1eac-11ea-86d8-18462fb3057b.png)

# Versions and configuration

- OS: Windows 7 x64
- Game Version: 0.D-10189-gd2cb78a [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills]
]

[savefile](https://drive.google.com/open?id=1fSBpPgIxCRxOLZZz6BycXQpkWCm_FVOV)

**Comment by ZhilkinSerg** [comment]
Why is CBM damaged in the first place? Were there some kind of explosion nearby CBM storage?

Computer should not be showing current state of stored items.

**Comment by GGgatherer** [comment]
> Why is CBM damaged in the first place?
Frankly, I have no idea. There were some wandering monsters but as far as I know only mole rats could get into bionic storages, and there were no mole rats. I didn't hear any explosions too, only turrets shooting several times when I was aboveground.
