### ISSUE TITLE
Seg Fault when initiating melee combat.

### ISSUE THREAD

**Issue by Berkyjay** [CleverRaven/Cataclysm-DDA#36111]
# Describe the bug
When initiating melee combat the game will seg fault.  The problem with this bug is that it's difficult to repeat.  It usually happens when I enter an area that I haven't been too and will only happen when 1) I initiate combat or b) open up the over map.  This bug is for 'a'.  If I reload the game, the bug won't happen again.  It feels like an issue with the way elements are loaded when a new area is entered.

# Steps To Reproduce
1. Exit vehicle after entering a new area
2. Walk up to a target and attack with melee weapon.

# Expected behavior
The game doesn't crash when I hit a target.

# Screenshots

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-10195-g72dbda8 [32-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Mutant NPCs [mutant_npcs],
    Bionic Slots [cbm_slots],
    Classes and Scenarios Mod [more_classes_scenarios],
    Stats Through Skills [StatsThroughSkills],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks]
]

# Additional context
[crash_12-14-2019-1106.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3964237/crash_12-14-2019-1106.log)
[debug_12-14-2019-1106.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3964238/debug_12-14-2019-1106.log)

# Save Game
https://drive.google.com/open?id=1W-fqK9cDAS-jPBW1lOlm32mI3kJd3uQf

**Comment by davidpwbrown** [comment]
could be dup of https://github.com/CleverRaven/Cataclysm-DDA/issues/36138 ?

**Comment by Berkyjay** [comment]
> could be dup of #36138 ?

That issue looks like the other seg faults I've been running into.

**Comment by ZhilkinSerg** [comment]
Cannot reproduce.

We have more useful backtrace now. Please ping me to reopen if you can reproduce it with newer version.
