### ISSUE TITLE
Missing mutation interaction

### ISSUE THREAD

**Issue by Bulletfang** [CleverRaven/Cataclysm-DDA#36126]
# Describe the bug

Venomous mutation does not interact with Large Talons mutations when attacking unarmed. It does not apply its poison effect.

# Steps To Reproduce

1. Make a player with the Venomous and Large Talons mutations.
2. Attack an enemy without weapons and deal cut damage.
3. The attacks don't apply poison.

# Expected behavior

Unarmed melee attacks have the advertised chance to apply poison when dealing cutting damage. Unarmed attacks with the Large Talons mutation deal cut damage, which, technically, qualifies them for the Venomous mutation to take effect:

![Untitled3](https://user-images.githubusercontent.com/45204409/70860989-90665580-1f28-11ea-9b17-1741eebd25c5.png)

The Large Talons mutation turns the player's unarmed melee attacks into the cutting type, this is an example of me doing that:

![Untitled4](https://user-images.githubusercontent.com/45204409/70861013-d1f70080-1f28-11ea-826d-15a4cd35a8bd.png)

Venomous probably doesn't recognize the attacks as viable for its effect because they're not extra attacks like a Beak mutation gives you, which by the way does apply the poison effect.

Version: Latest as of 15th December 2019, tested with no mods.

**Comment by Fris0uman** [comment]
Yeah so looking at the code only special attack can apply the poison effect. Since special attacks happen in the same turn as normal attack we can either make it so one of those poison the enemy if it deals cut/stab damage or make it OP and have both of them deal poison.
