### ISSUE TITLE
Beak and mouth flaps not mutually exclusive

### ISSUE THREAD

**Issue by glenmack** [CleverRaven/Cataclysm-DDA#36127]
# Describe the bug
During a lab run I managed to mutate both beak and mouth flaps.

# Steps To Reproduce
Use the debug menu.

# Expected behavior
Should be mutually exclusive. I think. The description says the flaps are around your mouth, barring complicated code to have mouth flaps refer to any other mouth mutations I think mouth flaps should be mutually exclusive wit any other mouth mutation.

**Comment by DaviBones** [comment]
No, mouth flaps are *around* your mouth, a beak *is* your mouth. You can have both. Think cephalopods (both IRL and in-game mutation tree), they have both a beak and mouth tentacles (which mouth flaps are a precursor of in-game)

**Comment by glenmack** [comment]
> No, mouth flaps are _around_ your mouth, a beak _is_ your mouth. You can have both. Think cephalopods (both IRL and in-game mutation tree), they have both a beak and mouth tentacles (which mouth flaps are a precursor of in-game)

The beak is your mouth equivalent but is not a mouth. I accept that they could co-exist, but both calling them mouth flaps and the description either need changing based on your facial orifice or need to only happen when you have a mouth.

**Comment by KorGgenT** [comment]
sounds like you only have a semantic issue here.

**Comment by glenmack** [comment]
> sounds like you only have a semantic issue here.

It's semantic if you can change the name and description on the fly, if it can't be done it should be mutually exclusive.

**Comment by kevingranade** [comment]
A beak is still a mouth, the description is fine.
