### ISSUE TITLE
Segmentation fault -- Missing Item Description

### ISSUE THREAD

**Issue by KoRv117** [CleverRaven/Cataclysm-DDA#36144]
# Describe the bug

Trying to load my save after the latest update, I receive an error message, pressing space to continue gives me a segmentation fault.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-10248-g4be222a
 - Graphics version: Tiles
 - Mods loaded:

  "dda",
  "filthy_morale",
  "novitamins",
  "No_Fungi",
  "Tolerate_This",
  "craftgp",
  "FIC_Weapons",
  "realguns",
  "ew_pack",
  "makeshift",
  "More_Survival_Tools",
  "modular_turrets",
  "Salvaged_Robots",
  "mutant_npcs",
  "more_locations",
  "FujiStruct",
  "boats",
  "deoxymod",
  "blazemod",
  "Tanks",
  "more_classes_scenarios",
  "safeautodoc",
  "sleepdeprivation",
  "StatsThroughSkills",
  "magiclysm",
  "hydroponics",
  "MMA",
  "speedydex",
  "aftershock",
  "crt_expansion",
  "Mining_Mod",
  "More_Armors"

# Additional context

Crash.log was empty

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3965651/debug.log)

Save file zip is unfortunately too large for GitHub

![KoRv Segmentation Fault](https://user-images.githubusercontent.com/56089860/70871771-8700db80-1f70-11ea-974e-fd22b04b597d.png)

**Comment by Helldrone** [comment]
Hello! i updated to the latest and tried to load my save, it crashed and i got this error message.
![image](https://user-images.githubusercontent.com/49344129/70872712-59d11f00-1faa-11ea-97b6-689e17715115.png)

Here's the modlist.
![image](https://user-images.githubusercontent.com/49344129/70872877-1a570280-1fab-11ea-8979-02c90dc91917.png)


Here's the Error that popped up.

![image](https://user-images.githubusercontent.com/49344129/70872885-335fb380-1fab-11ea-8610-ef34b9547325.png)
