### ISSUE TITLE
Make interrupt messages being an option to turn on/off

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [CleverRaven/Cataclysm-DDA#36151]
**Is your feature request related to a problem? Please describe.**  
A problem, well, when you have auto-foraging turned on, and you're getting 

https://media.discordapp.net/attachments/252368987210514433/656078283619958784/aaa.png
https://media.discordapp.net/attachments/252368987210514433/656078291903447051/bbb.png

every step you make, you tell me. If I may be so blunt: It's fucking annoying! I need it to go away! I like living on the edge! If I die, it's my fault. Not the games. No handholding for me.

Also same stuff when you have 1-shot weapons. You reload, message "blabla close", you aim, message "blabla close", you shot, you reload, message, you aim, message, you get the picture. That's not my definition of fun. BEing interrupted at every other turn.

Please make these interrupt messages an option to be turned off / on by the user! "Discussion"/Feedback going here: https://discordapp.com/channels/252365627543519232/252368987210514433/656078284164956170

**Comment by Fris0uman** [comment]
As far as I understand this #35983 should solve the issue
