### ISSUE TITLE
Unload all in tile

### ISSUE THREAD

**Issue by glenmack** [CleverRaven/Cataclysm-DDA#36153]
**Is your feature request related to a problem? Please describe.**  
Unloading food and ammo from containers is a real pain for those of us that horde, what with food containers being especially space inefficient for fridges/freezers. Unloading each container individually being especially tedious, I figured unloading all in a tile would be a good feature, and may apply to ammo magazines, liquid containers, etc.

**Describe the solution you'd like**  
The ability to unload everything that is un-loadable on a tile.

**Comment by OzoneH3** [comment]
Related stale issue for reference #24002.
