### ISSUE TITLE
NPC(s) do not pulp corpses while following player, nor follow player after.

### ISSUE THREAD

**Issue by eternalnight264** [CleverRaven/Cataclysm-DDA#36166]
# Describe the bug

NPC(s) do pulp bodies properly. They state they are going to do it, run over, and stand atop the corpse not moving. They also cease to follow me at this point, despite still being a 'follower'. This goes on until I re-'hire' them.

# Steps To Reproduce

1. Spawn in with a starting NPC.
2. Have them kill a zombie.
3. Witness them state they want to pulp the corpse, run over, and stand atop the corpse.
4. They stand atop the corpse, unmoving, not saying anything or pulping.
5. Step away. They do not follow me.
6. Speak to them, dismiss them, and rehire them in order to get them to even follow me again.

# Expected behavior

NPC(s) will move towards the zombie's corpse, state their intention to pulp it. 
They will then pulp it and promptly return to the player's side, continuing to follow.

# Screenshots

https://i.gyazo.com/d151ec59792b02548626532eeb1f5fed.jpg

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-10279-gc698d3d [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    Mythological Replicas [nw_pack],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Crazy Cataclysm [crazy_cataclysm],
    EZ-Mode Medical [fast_healing],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Mapgen Demo [mapgen_demo],
    No Rail Stations [No_Rail_Stations],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks],
    Necromancy [necromancy],
    Bionic Slots [cbm_slots],
    Classes and Scenarios Mod [more_classes_scenarios],
    Classic Roguelike Classes [RL_Classes],
    Fuji's Military Profession Pack [fuji_mpp],
    No Filthy Clothing [no_filthy_clothing],
    Sleep Deprivation [sleepdeprivation],
    Simplified Nutrition [novitamins],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    Cataclysm++ [Cata++]
]

# Additional context

Save file?  I guess?

[Mountain Pine.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3970025/Mountain.Pine.zip)

**Comment by EirenexTheDragon** [comment]
happened to me aswell. i managed to fix the following issue by telling them to guard and then to follow me rightafterwards. though its best to pulp all corpses first before ordering

**Comment by eternalnight264** [comment]
Precisely, nothing I do appears to be able to solve the issue permanently. Only temporarily.

**Comment by davidpwbrown** [comment]
Will look into this, seems a reoccurence of bugs ive seen before.

**Comment by eternalnight264** [comment]
I noticed there was [this](https://github.com/CleverRaven/Cataclysm-DDA/issues/32341) before, perhaps related?

**Comment by davidpwbrown** [comment]
Perhaps, though what I had seen before was them reverting to non-follower behaviour, which indicates a deeper problem.

**Comment by Ezsk** [comment]
Perhaps they are [out of stamina.](https://github.com/CleverRaven/Cataclysm-DDA/issues/35969)

**Comment by EirenexTheDragon** [comment]
i had one npc become winded from pulping, but the other was not getting winded from pulping. even waiting for a bit wouldnt help it

**Comment by davidpwbrown** [comment]
oops linked wrong issue, this is the one ill look at next.

**Comment by davidpwbrown** [comment]
btw, the save archive cant be unzipped, it seems to be corrupted or part of a multi-part archive that isnt present
