### ISSUE TITLE
Soap Flakes Uncraftable Except by CBM

### ISSUE THREAD

**Issue by Zourin2** [CleverRaven/Cataclysm-DDA#36162]
# Describe the bug

Soap Flakes require a tool with Cutting 2 or higher. The only tool in the base game with that level is the Extended Toolset CBM, per the Chezzo item browser.

# Expected behavior

Craftable without cybernetic implants.

Reducing it to Cutting 1 or more, upgrading existing higher-quality cutting tools to level 2, or introduction of a cheese grater for the purposes of flaking soap (and possibly hard cheese) are all acceptable.

**Comment by glenmack** [comment]
I was wondering what the hell had cutting 2 when I saw that recipe.
