### ISSUE TITLE
Many mods have json errors that need to be cleared up

### ISSUE THREAD

**Issue by jbytheway** [CleverRaven/Cataclysm-DDA#36171]
# Describe the bug

Recent work on various fronts has substantially improved the validation of json game data in the CI testing.  However, the errors were only checked for the core game data (and a couple of mods).

Now #35995 has added a test which is intended to load the data for all mods, so that they can all be checked in CI and errors don't creep into the mods.

However, many mods still have errors, so currently there is a [blacklist](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/build-scripts/mod_test_blacklist) of mods which are not checked.

The hope is that each mod can now be fixed to load cleanly, and this work can be done piecemeal.  As each mod is fixed it can be removed from the blacklist.  Ultimately, we want the blacklist to be unnecessary.

If a mod you care about is blacklisted, then I encourage you to try fixing it and make a suitable PR.

To see the errors locally, run the tests (`tests/cata_test`) with the `--mods=` option, listing the id of the mod in question.  For example:

```
./tests/cata_test --mods=magiclysm '~*'
```

The `'~*` parameter causes it to not actually run any of the tests; for the purposes of this work running the tests is probably not necessary, because the errors arise during the loading of game data, before any tests run.

Most of the problems are simple misunderstandings of the json format.  To get some inspiration on how to resolve errors, see the previous PRs that fixed the core game data #34455 and Magiclysm #34525.

# Additional context

Here is a list of the currently blacklisted mods that need to be fixed:

- [x] aftershock
- [x] alt_map_key
- [x] Animatronics
- [x] Battery_Overhaul_Legacy_Mode
- [x] blazemod
- [x] cbm_slots
- [x] classic_zombies
- [x] crazy_cataclysm
- [x] crt_expansion
- [x] desertpack
- [x] DinoMod
- [x] ew_pack
- [x] FIC_Weapons
- [x] FujiStruct
- [x] generic_guns
- [x] Graphical_Overmap
- [x] growable-pots
- [x] Heavy miners
- [x] hydroponics
- [x] magiclysm
- [x] manualbionicinstall
- [x] mapgen_demo
- [x] Medieval_Stuff
- [x] MMA
- [x] modular_turrets
- [x] more_locations
- [x] More_Survival_Tools
- [x] mutant_npcs
- [x] my_sweet_cataclysm
- [x] national_guard_camp
- [x] No_Anthills
- [x] No_Bees
- [x] no_faults
- [x] no_filthy_clothing
- [x] No_Fungi
- [x] no_medieval_items
- [x] no_npc_food
- [x] No_Rail_Stations
- [x] No_Triffids
- [x] novitamins
- [x] realguns
- [x] safeautodoc
- [x] Salvaged_Robots
- [x] sees_player_hitbutton
- [x] sees_player_retro
- [x] sleepdeprivation
- [x] speedydex
- [x] stats_through_kills
- [x] Tanks
- [x] Tolerate_This
- [x] Urban_Development

**Comment by Maleclypse** [comment]
I use Github Desktop and Atom for JSON editing.  Is there another tool I need to get to run the tests as you describe above?

**Comment by jbytheway** [comment]
To make it easy for yourself, you need to compile the code yourself.  In theory we could distribute the test executable alongside the game to allow you to test without compiling, but currently that's not done.  This is a rare niche circumstance in which it is useful, because generally you wouldn't need to run the tests unless you were editing the code.

If you are willing to be more patient, however, you can rely on Travis to run the tests for you.  Open a PR where you remove a mod from the blacklist (mark it WIP) and see what errors Travis reports for you to fix.

**Comment by ZhilkinSerg** [comment]
Blacklist as of today:

```
aftershock
blazemod
crt_expansion
generic_guns
Graphical_Overmap
mapgen_demo
more_locations
no_medieval_items
sees_player_hitbutton
sees_player_retro
```

**Comment by jbytheway** [comment]
We're now down to just two mods blacklisted:
```
more_locations
Graphical_Overmap_More_Locations
```
(and the latter only because it depends on the former).

more_locations is in the process of being slowly transitioned to core content.  It probably won't be unblacklisted until that's done.

**Comment by hexagonrecursion** [comment]
mod_test_blacklist was removed by #46337

**Comment by jbytheway** [comment]
Yes, this can be closed now.
