### ISSUE TITLE
Opening Software Keyboard/pressing back button on Android 2nd time causes crash - it's back

### ISSUE THREAD

**Issue by chriseich21** [CleverRaven/Cataclysm-DDA#36175]
# Describe the bug
Inputting commands with the Software Keyboard (SwiftKey) is frequently crashing on the 2nd attempt to open keyboard when using software back button/gesture on Note 9 and Android 9.

# Steps To Reproduce
1. Start as anything (Used Random Start) after creating a world
2. Open Software Keyboard by using back button. 
3. Close keyboard
4. Repeat Step 2, Crash

# Expected behavior
Keyboard should be able to be open and closed as many times as you would like using software back button

# Versions and configuration

 - OS: Android 9.0
 - Game Version: Build 10015 (both arm64 and armeabi) 
 - Graphics version: Tiles
 - Mods loaded: [DDA, No NPC Needs]

**Comment by paulorenzo-santos** [comment]
Last working build was 9996, builds after this all crash like in issue #33781

**Comment by chriseich21** [comment]
There was no reported issue right? I looked through last 2 months of issues and didn't see anything

**Comment by paulo-renzo** [comment]
Yeah, this just started happening again after 9996

**Comment by chriseich21** [comment]
Just checking, sometimes I'm bad about opening duplicates

**Comment by ZhilkinSerg** [comment]
Don't worry it is a temporary thing.

**Comment by chriseich21** [comment]
Sweet, thanks for working on it and the original fix! I play on Android 90% of the time

**Comment by ZhilkinSerg** [comment]
Please try https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-jenkins-b10029

**Comment by paulo-renzo** [comment]
Yeah, keyboard works on 10029. Thanks!

**Comment by ZhilkinSerg** [comment]
Would you also please try Google Play version (https://play.google.com/store/apps/details?id=com.cleverraven.cataclysmdda.experimental) on Android 9 and see if there are still issues with Back button?

**Comment by paulo-renzo** [comment]
> Would you also please try Google Play version (https://play.google.com/store/apps/details?id=com.cleverraven.cataclysmdda.experimental) on Android 9 and see if there are still issues with Back button?

The experimental on Google Play still has the Back button issue. I'm currently on 10047 which does not have the problem.

**Comment by ZhilkinSerg** [comment]
> 
> 
> > Would you also please try Google Play version (https://play.google.com/store/apps/details?id=com.cleverraven.cataclysmdda.experimental) on Android 9 and see if there are still issues with Back button?
> 
> The experimental on Google Play still has the Back button issue. I'm currently on 10047 which does not have the problem.

Can you please update/reinstall it and check again now?

**Comment by paulo-renzo** [comment]
The Google Play experimental (10055) still has the problem.

**Comment by ZhilkinSerg** [comment]
@paulo-renzo Would you mind to test this version? There is a third option in prelaunch menu. See if back button behaves differently with either state of that checkbox.

https://www.dropbox.com/s/qyc4x8391psytd2/cataclysmdda-0.D-10803-gdca3ca5c05-dirty-experimental-arm64-v8a-release.apk?dl=0

**Comment by paulo-renzo** [comment]
with that version back button doesn't crash anymore but can't open keyboard either(first press opens kb, 2nd closes kb, press after doesn't crash or open kb)

**Comment by ZhilkinSerg** [comment]
> 
> 
> with that version back button doesn't crash anymore but can't open keyboard either(first press opens kb, 2nd closes kb, press after doesn't crash or open kb)

Thanks a lot for testing for me! Is that with the third checkbox (""Trap Back button") in prelaunch menu ticked? What if you change its state to unticked? Is it crashing then?

**Comment by paulo-renzo** [comment]
Yeah, 3rd option ticked. If unticked crashes after opening kb the first time. Changing in options to True needs restart, no crash but can't  reopen kb.

**Comment by Draakus** [comment]
Hey, just want to add that the same problem is present on Android 10 with the newest experimental build (10793) on the play store.

I switched over from iPhone to android and cdda was the main reason, I don't mind playing an older working build but if it could somehow be fixed that would be amazing. Sadly I have no idea about coding but I'm happy to test.

**Comment by ZhilkinSerg** [comment]
You can use APK from github releases page (it should work okay) until issue is resolved.

**Comment by Draakus** [comment]
> You can use APK from github releases page (it should work okay) until issue is resolved.

Thank you very much, the 10137 APK works without the keyboard crash!
