### ISSUE TITLE
Spells cast by monsters count as cast by player

### ISSUE THREAD

**Issue by LaVeyanFiend** [CleverRaven/Cataclysm-DDA#36174]
# Describe the bug

If a monster is damaged or killed by a spell cast by another monster, it counts as the player casting it.

# Steps To Reproduce

1. Spawn krabjek and giant web spider.
2. Wait for the krabjek to cast Necrotic Gaze on the spider.
3. The player will be credited for damaging the spider.
4. If spider dies from this, player gets kill credit.

# Expected behavior

The player is not credited for casting of monsters.

# Screenshots
Damage from krabjek gazes count as player's
![image](https://user-images.githubusercontent.com/51099123/70959877-5a6dc200-204b-11ea-9f5d-6d51beea5484.png)
Kills from krabjek gazes count as player's
![image](https://user-images.githubusercontent.com/51099123/70959893-68234780-204b-11ea-8155-aef0bf45832d.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-10363-ge6a160d [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm]
]

**Comment by anothersimulacrum** [comment]
Fixed by #36174?

**Comment by Night-Pryanik** [comment]
@anothersimulacrum you mentioned the issue we're in, not the PR.

**Comment by anothersimulacrum** [comment]
Well that's no use, isn't it! I meant #38836
