### ISSUE TITLE
Survivor Utility Belt reporting (poor fit)

### ISSUE THREAD

**Issue by CypherHyena** [CleverRaven/Cataclysm-DDA#36180]
# Describe the bug
If you craft an Aftershock Survival Utility Belt (sheath) (and probably the holster version too) and then attempt to use it's prying ability to pry open a window, it fails. The belt shows a "1 prying" quality. When you attempt to do a window it says:

You attempt to pry open the window with curtains using your ++ survivor utility belt (sheath)...

You can't get sufficient leverage to open that with your | | survivor utility belt (sheath) (poor fit).

Notice the second line shows a different quality indicator than the first? I believe the top start of the check is using your actual item, and the final second part of the check is using the generic item from the database with by default doesn't fit. 

The belt I'm wearing is tailored and says (fits) in it's description.

# Steps To Reproduce

1. Make a survivor utility belt (sheath)
2. Wear it
3. press E and move towards a window to examine a window from the outside. This will trigger the game to attempt to pry it open, and you will get the above message.

# Expected behavior

The belt would allow me to pry the window open.

# Screenshots

![image](https://user-images.githubusercontent.com/53030348/70972252-92cfc900-2068-11ea-9525-cb5741b84647.png)

![image](https://user-images.githubusercontent.com/53030348/70972294-a67b2f80-2068-11ea-8350-e24117a95ff6.png)

# Versions and configuration

<!-- Please complete the following information; you can now go to:
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-10346-gcbe8a09 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    No Fungal Monsters [No_Fungi],
    Mythical Martial Arts [MMA],
    Mutant NPCs [mutant_npcs],
    Disable NPC Needs [no_npc_food],
    Disable Religious Texts [no_religious_Texts],
    No Antique Firearms [no_olg_guns],
    Makeshift Items Mod [makeshift],
    Classes and Scenarios Mod [more_classes_scenarios],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Filthy Clothing [filthy_morale],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key]
]

**Comment by araneyl** [comment]
This is a test file that will show the poor fit issue and is in the current version of the game.
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-10363-ge6a160d [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock]
]


[testshock.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3971937/testshock.zip)

**Comment by Termineitor244** [comment]
The survivor belt with tools included has been obsoleted from the game, and the belt is now only a normal container, so this issue should be closed.

**Comment by wapcaplet** [comment]
Thanks @Termineitor244 for checking this. Closing issue.
