### ISSUE TITLE
Add alternative end evolutions to skeletons

### ISSUE THREAD

**Issue by arijust** [CleverRaven/Cataclysm-DDA#36194]
**Is your feature request related to a problem? Please describe.**  
During end-game majority of skeletons turn into skeletal juggernauts.

**Describe the solution you'd like**  
Add new skeletal monsters, so mid-game skeletons can evolve into something else.  

**Describe alternatives you've considered**  
Reduce max evolution of skeleton by one. So skeleton spawns can vary more during end game.

**Comment by Haranador** [comment]
Some sort of ranged variant maybe? Skeletal Javelineer or something.

**Comment by I-am-Erk** [comment]
A fast-moving, long-limbed skeletal creature whose limbs had turned into stilt-like spears would be interesting. Something like this, but a zombie 
![image](https://user-images.githubusercontent.com/45136638/71193143-79807580-223e-11ea-9aca-3ccb0738df2a.png)
