### ISSUE TITLE
The amazing teleporting hulk

### ISSUE THREAD

**Issue by anothersimulacrum** [CleverRaven/Cataclysm-DDA#36190]
# Describe the bug
When the hulk shoves my car, it teleports

# Steps To Reproduce

1. Load `Calcium`.
2. Wait a few turns.
3. Hulk shoves car and teleports.

# Expected behavior

Hulks don't teleport

# Screenshots

(It stands there doing nothing for a few seconds before it starts moving)
![tealhulk](https://user-images.githubusercontent.com/42699974/71005473-93805380-2098-11ea-8dbf-1cfeecb2ac3a.gif)

# Versions and configuration

- OS: Linux
    - OS Version: Arch Linux, Kernel version 5.4.2
- Game Version: 0.D-10380-g936a155262 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

I suspect coordinate weirdness is going on here.
[Calcium.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/3973820/Calcium.tar.gz)

**Comment by glenmack** [comment]
Looks like he's shoving the car into himself as he steps into the space and is getting knocked down by the car.

**Comment by jbytheway** [comment]
Looks like he's teleporting exactly one submap over and up, so probably the hulk's location is being saved before the player moves, and restored afterwards, at which point the map has shifted so it gets placed back in the wrong spot.
