### ISSUE TITLE
Defrost not functional

### ISSUE THREAD

**Issue by coreyblanke** [CleverRaven/Cataclysm-DDA#36202]
Game version:
10020
Operating system:
Windows 7 (x64)
Tiles or curses:
-
Mods active:
![image](https://user-images.githubusercontent.com/24921373/71043427-32866900-20f4-11ea-864c-0bae40e4c393.png)

### Expected behavior
(a)ctivate a pot/pan with fire nearby, defrost food menu pops up with all food on you, food can be defrosted.
### Actual behavior
defrosting menu does not show, instead a text box saying "You don't have appropriate food to heat up." shows and returns to the game despite frozen food being in the inventory.
### Steps to reproduce the behavior
start a fire, spawn in a cast-iron pan, spawn in a frozen peanut butter sandwich, attempt to unfreeze the sandwich

**Comment by ssh851000914** [comment]
This problem began from version 10016.
