### ISSUE TITLE
Discussion about the construction of Stone Walls

### ISSUE THREAD

**Issue by Ker-Nes** [CleverRaven/Cataclysm-DDA#36207]
Recently there has been a [change in the construction recipe for stone walls,](https://github.com/CleverRaven/Cataclysm-DDA/commit/3296581a5eac4d1f1f90f12bffcd7d7eea1763ea) which admittedly were rather too cheap (if demanding high skills), to require pebble and mortar. Which while the pebble does make perfect sense, the mortar not so much. I thought said wall, as represented by the high requirements of fabrication skill, were meant to represent something like the Burdock Piling japanese method (https://en.wikipedia.org/wiki/Burdock_piling), which was used to create castle walls and did not use any kind of mortar.

As such, I would like to know what people would think of removing the mortar requirement for said wall. At the same time, a vast increase in the stone requirement should probably be in order, something in the order of, let's say, 48-96 for each step of the construction (sure, that takes a while to gather, but it also doesn't requires anything but time to gather), both for realism and for some semblance of balance.

Another thing to consider might be making two construction recipes, or even two types of stone walls, one for the mortared kind, with a reduced fabrication skill requirement, and the other the burdock piling method, with a high skill requirement but no mortar usage and more stone (to represent extra width for stability)? 

Thoughts?

**Comment by anothersimulacrum** [comment]
#36195 implements what you are talking about.

**Comment by ralreegorganon** [comment]
#36195 is already in progress to add stone walls without mortar.

**Comment by I-am-Erk** [comment]
Resolved now that field stone walls are merged
