### ISSUE TITLE
Constant crashes and game freezing

### ISSUE THREAD

**Issue by UndeadMoose** [CleverRaven/Cataclysm-DDA#36201]
# Describe the bug

After build 10017 I've been getting many random crashes. Some crashes I got were due to auto attacking, and the rest are totally random. Then when going near any vehicle the game will freeze for a second and continue on. A freeze will also occur when examining a vehicle you haven't examined before.

# Steps To Reproduce

1. Play the game for a short amount of time.
2. Go near any vehicle
3. Examine a vehicle

# Expected behavior

Game shouldn't crash so much, and shouldn't freeze going near and or examining a vehicle.

# Screenshots

**If applicable**, add screenshots to help explain your problem.

![Screenshot (403)](https://user-images.githubusercontent.com/56947231/71041957-cb0cff80-216d-11ea-9fae-8d21c29a29f1.png)
![Screenshot (404)](https://user-images.githubusercontent.com/56947231/71042280-a1080d00-216e-11ea-8f25-6a4782711e60.png)

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-10426-ge93e21d
 - Graphics version: Tiles
 - Mods loaded: None

# Additional context

I tested this with and without mods and I still had random crashes and freezes. I am running the 64bit version.

[Crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3975872/Crash.zip)

**Comment by anothersimulacrum** [comment]
Are you running the 64 bit or 32 version of the game?

**Comment by UndeadMoose** [comment]
> Are you running the 64 bit or 32 version of the game?
Oh yeah sorry forgot to add that. I'm running the 64 bit version.

**Comment by UndeadMoose** [comment]
Got another crash while walking around a city. I got one while walking into a barn too but wasn't able to get a save for that. Also noticed something odd while testing (on the save provided). A barn spawned but the structure of it was gone oddly

![Screenshot (410)](https://user-images.githubusercontent.com/56947231/71051284-26011f80-218b-11ea-94e8-5b6e46bedc8d.png)
 the shadows were still casting underneath where it was supposed to be.
![Screenshot (408)](https://user-images.githubusercontent.com/56947231/71051188-c9056980-218a-11ea-97b4-bce3c175b455.png)
![Screenshot (406)](https://user-images.githubusercontent.com/56947231/71050868-c35b5400-2189-11ea-8c5d-5f1a73066065.png)
![Screenshot (407)](https://user-images.githubusercontent.com/56947231/71050878-cb1af880-2189-11ea-9478-abcdec61097e.png)
[Crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3976358/Crash.zip)
[Ravinia.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3976360/Ravinia.zip)

**Comment by davidpwbrown** [comment]
could be dup of https://github.com/CleverRaven/Cataclysm-DDA/issues/36138 ?

**Comment by UndeadMoose** [comment]
Still having these random crashes out of nowhere while wandering around.
[CDDACrash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3991861/CDDACrash.zip)
