### ISSUE TITLE
Expand autodrive to work on rivers

### ISSUE THREAD

**Issue by ymber** [CleverRaven/Cataclysm-DDA#36216]
**Is your feature request related to a problem? Please describe.**  
Autodrive currently only works on roads and I want to use it in a canoe.

**Describe the solution you'd like**  
Improve autodrive to work on different terrains.

**Additional context**  
Autodrive across different terrains and z levels might be disrupted by multi z level bridges and rivers.

**Comment by davidpwbrown** [comment]
ok. should be doable.
