### ISSUE TITLE
error on a loading screen

### ISSUE THREAD

**Issue by totoro0924** [CleverRaven/Cataclysm-DDA#36210]
# Describe the bug

when i start a new game or loading a save i'm getting error
 DEBUG    : JSON contains circular dependency.  Discarded 1 objects:
{
    "type": "overmap_terrain",
    "id": "house_base",
    "copy-from": "house_base",
    "name": "house",
    "sym": "^",
    "color": "light_green"
  },

 FUNCTION : void DynamicDataLoader::load_deferred(DynamicDataLoader::deferred_json&)
 FILE     : src/init.cpp
 LINE     : 134
 
and

 DEBUG    : plant coverage total exceeds 100%

 FUNCTION : void groundcover_extra::finalize()
 FILE     : src/regional_settings.cpp
 LINE     : 763

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-10441-gb918ea5 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Bens GF recipes [Tolerate_This],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Makeshift Items Mod [makeshift],
    Mythological Replicas [nw_pack],
    Craftable Gun Pack [craftgp],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    EZ-Mode Medical [fast_healing],
    Hydroponics [hydroponics],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Mythical Martial Arts [MMA],
    Mutant NPCs [mutant_npcs],
    Alternative Map Key [alt_map_key],
    Crazy Cataclysm [crazy_cataclysm],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Mapgen Demo [mapgen_demo],
    No Rail Stations [No_Rail_Stations],
    Urban Development [Urban_Development],
    Beta National Guard Camp [national_guard_camp],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks],
    Folding Parts pack [deoxymod],
    Necromancy [necromancy]
]

**Comment by anothersimulacrum** [comment]
Alt map key was not updated after #36075

**Comment by totoro0924** [comment]
thanks
