### ISSUE TITLE
New map extras from the long grass PR Erk made have unreasonably high spawn rates.

### ISSUE THREAD

**Issue by Amoebka** [CleverRaven/Cataclysm-DDA#36229]
# Describe the bug

https://github.com/CleverRaven/Cataclysm-DDA/pull/35990 introduced new map extras for fields. Spawn rates feel extremely off, desolate sheds and ponds are absolutely everywhere.
Did you forget to turn down the spawn rates after testing?

# Steps To Reproduce

1. Make a world.
2. Run around a field.
3. Barns and ponds are like 10% of all field tiles.

# Expected behavior

Barns and ponds should be rare. Tree patches should be less common.

# Versions and configuration

 - OS: win10
 - Game Version: 0.D-10453-g572b78f
 - Graphics version: tiles
 - Mods loaded: none

# Additional context

Fields mapgen has gone berserk, with this chant I summon @I-am-Erk.

**Comment by I-am-Erk** [comment]
I'm already working on it, no need to call me out in the issue title

**Comment by kevingranade** [comment]
Erk may or may not be joking, but calling people out in issues is bad form so please don't do it.

**Comment by I-am-Erk** [comment]
I'm only a little joking, I'm not really offended but I could easily see someone else being.
