### ISSUE TITLE
Mass Zombie Suicide due to Damaging Tiles

### ISSUE THREAD

**Issue by Curt5** [CleverRaven/Cataclysm-DDA#36225]
# Describe the bug

Zombies appear to be committing suicide in droves. So far as I can tell, this is due to some sort of issue with zombie pathfinding and the behavior of zombies investigating nearby deaths.
If there is a damaging effect on a tile- broken glass, scratches from rose thorns, etc- zombies appear to gravitate around that tile, continually crossing over it until they die from repeated scratch damage.
This death prompts other nearby zombies to investigate, which causes them to pass over the damaging tile repeatedly, until they too die. This causes nearby zombies to investigate...
Which results in all the zombies in an area around the damaging tile killing themselves on a rosebush or shard of broken glass, and producing a neat and tidy pile of 6 to 10 dead zombies on a single tile due to scratch damage.

# Steps To Reproduce

1. Spawn into a standard world.
2. Break a window somewhere. This behavior also appears on rosebushes, but windows are consistent and observable.
3. Go somewhere else while still keeping the window within the reality bubble. This works best if you hang out in a basement or something, to ensure the zombies have no other lures.
4. Wait a day or so.
5. There is now a pile of dead zombies next to the window.

# Expected behavior

I would expect zombies to not commit mass suicide.

# Screenshots

https://puu.sh/EQO3p/89eca26f60.png

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-10453-g572b78f [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    C.R.I.T Expansion Mod [crt_expansion],
    Cataclysm++ [Cata++],
    Bens GF recipes [Tolerate_This],
    Bootleg Walkers [Bootleg_Walkers],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Gun Cotton [guncotton],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Secronom [secronom],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    More City Locations [cityside],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Roadheader and other mining vehicles [Heavy miners],
    Artyoms' Gun Emporium - Reloaded [Arts' Guns],
    Classes and Scenarios Mod [more_classes_scenarios],
    Classic Roguelike Classes [RL_Classes],
    Fuji's Military Profession Pack [fuji_mpp],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

- note #1: you can drag and drop files in this issue post!
- note #2: it is very important for us that you provide a save file in case of a crash. It really helps the developers
    to reproduce the bug and fix it. If possible, try to provide a save file that occurs in the right conditions, just
    before the crash happens. -->

**Comment by Haranador** [comment]
I feel like this is as it should be. Zombies are not really supposed to be smart in any way and i don't think they are supposed to feel pain? And they will revive anyway.

**Comment by Curt5** [comment]
I disagree. This error takes some challenge out of the game, it's ridiculous, and it's a bit annoying.
It takes challenge out of the game because cities will kinda clear themselves out. So long as you poke your head out of your house every day, you can just wander around and harvest the 'free kills' by smashing the huge corpse piles next to the windows.
Zombies dying also makes a noise, so if you're living above or below a house with windows, you can enjoy the sound of zombies dying over and over whenever you pass time by reading or sleeping.
It's also, just, y'know. Pretty dumb. 10+ zombies have been killed by repeatedly walking into... a rosebush? A _bush?_

**Comment by ThomasLinkin** [comment]
well, obviously , that's how the game was. try a higher zombie spawn rate if you felt like it's too easy for you. the zombie,like Haranador said, shouldn't be smart. and since the zombie also hunting by sounds, it's actually a normal thing. they follow the sounds or the enemy in their vision, accidently walk into a tile which damage anything walked into it, and they die.

**Comment by Curt5** [comment]
Turning up zombie spawns would do nothing but produce larger piles of dead zombie bodies, because this isn't an issue of occasionally finding a dead zombie killed by their own stupidity, this is an issue of pathfinding leading to mass death-by-thousand-cuts which chains into more deaths thanks to zombies investigating dead zombies.

**Comment by ThomasLinkin** [comment]
if a zombie heard a noise, it will follow the noise. and since they usually walk along as a horde in the city, nothing could ensure that the whole horde won't hear it too.and trust me bro, it's really helpful in the early game if you turn the zombie spawn rate to 5.00
try it, and feel the pain bro

**Comment by Curt5** [comment]
I'm sure it's helpful. That doesn't change the fact that ten zombies committing ritual suicide on a rosebush is A: ridiculous and B: very much not intended behavior.

**Comment by kevingranade** [comment]
We could look at making scratch damage non-lethal, it's intended to be a hassle not a fatal risk.
Alternately, the sources of scratch damage should be degrading.

There is no effect that makes zombies investigate the site of other zombies deaths. It's also irrelevant as you can easily contrive to lead zombies over hazards.

**Comment by Curt5** [comment]
I must've been misinformed on the zombie investigating thing, sorry.

I suppose making sources of damage eventually degrade would work, but I'm more curious where this issue came from, and why zombies are gravitating around sources of damage in the first place. I took a big break from the game- right before .D came out- and just recently got back to it. So far as I can tell, this is a pretty new issue- you would occasionally find zombies damaged by the environment, but only rarely killed by their own stupidity, where here it seems to be the norm.

**Comment by scorpion451** [comment]
Heavy "Feature not bug" vote here.

If anything, I'd suggest taking the idea of zombies being attracted to dead zombies as a suggestion.

On one level makes basic traps a bit more useful, on another level encourages keeping up with cleanup in your area.
