### ISSUE TITLE
safemode doesn't work if compass is hidden

### ISSUE THREAD

**Issue by captnblood** [CleverRaven/Cataclysm-DDA#36236]
# safemode doesn't work if compass is hidden
with the new panel it is possible to hide compass, however if we do so the safemode is completely bypassed.

# Steps To Reproduce
- disable compass in the panel
- try approaching monsters
- confirm safemode does not warn and stop you.

# Expected behavior
safemode should work wether compass is hidden or not in the panel

# Versions and configuration
 - OS: arch linux
 - Game Version: 0.D-10453-g572b78f982
 - Graphics version: Tiles
 - Mods loaded: dda, graphical_overmap

# Additional context
the function mon_info() in game.cpp could be divided in two separate functions.
- one for allowing safemode to work   (that should always be used)
- one for drawing compass   (only used if compass is enabled in panel)
   
there's a large block of continuous code in mon_info() that is responsible for the safemode check,
that large block can be easily extracted out of there and be inserted in a dedicated function.

**Comment by Kilvoctu** [comment]
This explains why my safemode hasn't worked in months. Have had my compass disabled for all that time. Turned it back on to test and indeed safemode worked,
