### ISSUE TITLE
Bamboo as a versatile renewable resource

### ISSUE THREAD

**Issue by new02DAY** [CleverRaven/Cataclysm-DDA#36231]
**Is your feature request related to a problem? Please describe.**  
Although not a large problem, I know some players, like myself, are concerned about renewable sources of wood for burning, crafting, etc. Bamboo would also be a food source and a source for ethanol (see below).

**Describe the solution you'd like**  
I'd like to suggest adding bamboo as a fast growing and harvest-able plant. Although there are many varieties of bamboo, I'd suggest keeping it to a generic "bamboo", to avoid confusion. Or maybe choosing one species, but that would be strangely highly specific. Some bamboos species are found in the New England region and a quick search shows that bamboo are popular as privacy hedges and ornamental plants on properties, so that would fit with mansions and houses as source.

Some bamboos are edible as bamboo shoots after processing (without which they produce cyanide in the GI). There are some examples of edible and larger species in **Additional Context**. 

**Describe alternatives you've considered**  
Increasing the amount of heavy sticks found by foraging from bushes. Or making grow-able trees, but that requires more time (as in planting to maturity) than bamboo. Some species can grow 6+ ft. in a season, even in cold regions.

**Additional context**  
**Timber bamboos**
https://en.wikipedia.org/wiki/Phyllostachys_aurea
https://en.wikipedia.org/wiki/Phyllostachys_aureosulcata
https://www.cabi.org/isc/datasheet/42069
https://lewisbamboo.com/product/yellow-groove/

**Japanese bamboo**
https://en.wikipedia.org/wiki/Reynoutria_japonica
https://plants.usda.gov/core/profile?symbol=POCU6

**As food**
https://en.wikipedia.org/wiki/Bamboo_shoot

**As biofuel**
https://www.dnaindia.com/india/report-india-s-first-biofuel-refinery-to-harness-fuel-out-of-bamboo-2232917
https://biotechnologyforbiofuels.biomedcentral.com/articles/10.1186/1754-6834-6-173

**Comment by snipercup** [comment]
I can't relate to the premise of this suggestion but I support the idea of adding bamboo. I get an instant oriental vibe when you mention bamboo and until you mentioned it I didn't expect bamboo to grow in England. The reason I support bamboo is because it allows for more thematic walls and props. Instead of widespread bamboo growing I'd expect it to be exclusive to certain farms/gardens and the items to be exclusive to Chinese themed restaurants/houses.

**Comment by kevingranade** [comment]
Please make a more detailed proposal, you need a set of claims about growth rate and yield of bamboo.  The sources are also necessary, but you need to provide a summary as well.

**Comment by new02DAY** [comment]
> I can't relate to the premise of this suggestion but I support the idea of adding bamboo. I get an instant oriental vibe when you mention bamboo and until you mentioned it I didn't expect bamboo to grow in England. The reason I support bamboo is because it allows for more thematic walls and props. Instead of widespread bamboo growing I'd expect it to be exclusive to certain farms/gardens and the items to be exclusive to Chinese themed restaurants/houses.

I didn't even think of that. More theme and variety is always cool.

> Please make a more detailed proposal, you need a set of claims about growth rate and yield of bamboo. The sources are also necessary, but you need to provide a summary as well.

Will do. I'll try and put together proper numbers and update the post, probably after the holidays. I just figured I'd see if anyone had comments for or against.

**Comment by Zireael07** [comment]
Do we even have bamboo in New England? Can it grow in the local climate, if brought over by Asian settlers?

**Comment by new02DAY** [comment]
> Do we even have bamboo in New England? Can it grow in the local climate, if brought over by Asian settlers?

Bamboo are available as ornamental plants in the area from what I can tell (not sure about general popularity). Part of the reason I got to thinking about it is because I drive past a couple of houses with bamboo hedges in the NY metro area, and we're in the warmer edge for hardiness according to http://bamboogarden.com/cold%20hardy%20bamboo.html. And from what I've read so far, as long as the roots survive (which they supposedly can even colder than -20F) the shoots will grow back.

I figured they'd make good plants for mansions, botanical gardens, even community gardens, and maybe a Chinese and/or Japanese-themed restaurant or house. They wouldn't exactly be ubiquitous, but maybe the same as oats in the current builds, pretty rare but worth looking for.

**Comment by Zourin2** [comment]
Short excerpt from the google gods regarding climate and certain species of bamboo

> To grow bamboo plants in northern climates, you need to find one of the cold-hardy bamboo plants. Some kinds will survive winter as far north as USDA cold-hardiness zone 5. ... In other words, these tropical plants that are evergreens in their native lands will act as herbaceous perennials in a cold climate.

We're familiar with tropical bamboo and their surprising growth rates, although we may want to focus on these hardier species that can weather winter conditions.

**Comment by LyleSY** [comment]
I'm interested in taking this on. Some quick research https://production.wordpress.uconn.edu/cipwg/wp-content/uploads/sites/244/2013/12/BambooFAQ.pdf shows it's legal everywhere in New England, but its planting is regulated in CT because it spreads so quickly
