### ISSUE TITLE
Flashlights disappearing when trying to throw past turrets

### ISSUE THREAD

**Issue by glenmack** [CleverRaven/Cataclysm-DDA#36239]
# Describe the bug
When exiting labs from the inside, sometimes I use an opaque object to block LOS with the turret peek (X) around the object, while wielding a flashlight, and throw the flashlight towards the door. The flashlight vanishes, and I can not find it from that point forward. Happened just now in build 10021 and twice in an earlier build.

# Steps To Reproduce
As above.

# Expected behavior
Flashlights should not disappear.

# Additional context

I think the flashlights may be hitting the turret. As a thrown object maybe they are being considered a projectile? Even if they do hit, they shouldn't go out. I'm just trying to throw past them, for lighting purposes. I'm getting no message about doing 0 damage to the turret. This time was a heavy duty flashlight so it shouldn't be breaking either.

**Comment by anothersimulacrum** [comment]
I'm getting a similar bug, when trying to throw an active item (dynamite), it just disappears.

**Comment by davidpwbrown** [comment]
oops may or may not be fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/36296 actually, if this is specific to active items....

Though the other issues do also note that thrown items disappear....
