### ISSUE TITLE
Zombie corpses cannot be manually pulped

### ISSUE THREAD

**Issue by Little-119** [CleverRaven/Cataclysm-DDA#36242]
# Describe the bug

Attempting to pulp a zombie corpse always results in 'The corpse moved before you could finish smashing it!'
(However, auto-pulp works just fine.)

# Steps To Reproduce

1. Kill zombie
2. `s`mash the zombie
3. Observe failure to pulp the corpse

# Expected behavior

To have `s`mashing a corpse result in removing the corpse's ability to revive, so I don't have to use auto-pulp or burn or `B`utcher the corpse instead.

# Screenshots
N/A

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-10458-g5c5a4bb [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context

**Comment by HarleyLorenzo** [comment]
Can confirm it works on this version and configuration as well (commit e8be1ac)
- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 19.10; Release: 19.10; Codename: eoan; 
- Game Version: 0.D [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Crazy Cataclysm [crazy_cataclysm],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Stats Through Skills [StatsThroughSkills],
    Medieval and Historic Classes and Shields [Medieval_Stuff]
]

**Comment by HarleyLorenzo** [comment]
Using git bisect, commit 1e4d076deb800ef75eea04d3ee15106ffa104bf4 is where the problem started

**Comment by anothersimulacrum** [comment]
Thanks for finding that! I know the issue, fix coming soon.
