### ISSUE TITLE
Smashing corpses yields the message, 'The Corpse moved before you could finish smashing it'.

### ISSUE THREAD

**Issue by eternalnight264** [CleverRaven/Cataclysm-DDA#36265]
# Describe the bug

Attempting to pulp a zombie corpse through normal means does absolutely nothing. The message, 'The corpse moved before you could finish smashing it' appears. NPCs are still able to do so. Butchering works as well.
 

# Steps To Reproduce

1. Start a new game with any start, character, etc.
2. Find a zombie.
3. Kill said zombie.
4. Attempt to pulp a corpse, find that said corpse is unpulpable with the above message.
:OPTIONAL:
5. Spawn NPC.
6. Let NPC attempt to pulp corpse.
7. Witness success.

# Expected behavior

When I attempt to pulp a zombie corpse, I expect it to succeed immediately, preventing revivification.

# Screenshots

[Me not being able to smash.](https://i.gyazo.com/3f28e88aced3b2f74f0307622b4fa7d4.jpg)
[NPC being able to smash.](https://i.gyazo.com/fde8c9cf849d2691ddfd2feeb0777704.jpg)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-10467-ge8be1ac [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    Mythological Replicas [nw_pack],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Crazy Cataclysm [crazy_cataclysm],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Mapgen Demo [mapgen_demo],
    No Rail Stations [No_Rail_Stations],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks],
    Necromancy [necromancy],
    Bionic Slots [cbm_slots],
    Classes and Scenarios Mod [more_classes_scenarios],
    Classic Roguelike Classes [RL_Classes],
    Fuji's Military Profession Pack [fuji_mpp],
    No Filthy Clothing [no_filthy_clothing],
    Sleep Deprivation [sleepdeprivation],
    Simplified Nutrition [novitamins],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    Cataclysm++ [Cata++]
]

# Additional context

**Comment by Kilvoctu** [comment]
This should have been fixed in build10032 due to PR #36246. At least it was for me.

**Comment by eternalnight264** [comment]
Odd, I thought I was at 10033 but I guess I missed an update. Thanks!
