### ISSUE TITLE
The rotating charges of a few consumable items in profession choosing

### ISSUE THREAD

**Issue by ThomasLinkin** [CleverRaven/Cataclysm-DDA#36279]
# Describe the bug

whenever i started a new game, i notice something. in the profession tab, there are quite a few profession with consumable items like lighter ,...etc . but if i scroll down the right panel to see further description, the charges changed in a unpredictable way and it kept the latest charges into the game and i also notice the little white square near a weapon (which indicate a weapon's durability i think) also change this way

# Steps To Reproduce

1. Create a new world
2. Create custom character
3. Choose a profession with a lighter . Ex: CRIT Enforcer
4. Scroll through the beginning inventory of the progression
5. Look at the charges of the lighter as you scroll up and down

# Expected behavior

The charges should stay at a reasonable number, not jumping up and down randomly. 

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

 - OS: Android
 - Game Version: 0.D-10537-g3b6a7bd
 - Graphics version: RetroDays
 - Mods loaded: C.R.I.T Expansion pack

# Additional context

**Comment by Qrox** [comment]
These little white squares near weapon names indicate a gun's fouling level. As for the charges change, it's likely because the values are re-rolled each time the panel is scrolled.

**Comment by ThomasLinkin** [comment]
> These little white squares near weapon names indicate a gun's fouling level. As for the charges change, it's likely because the values are re-rolled each time the panel is scrolled.

ah, i get the "fouling" part. but the reroll is pretty much hard to uunderstand. that looks like a bug to me btw

**Comment by Night-Pryanik** [comment]
> The charges should stay at a reasonable number, not jumping up and down randomly.

Why? Random charges number is ok.

**Comment by BevapDin** [comment]
There should be a statement hinting that the items you get upon game start may differ. This does not only mean item charges. Items are now generated via an item group, which can have any kind of randomness within it.

**Comment by kevingranade** [comment]
At face value it's reasonable for them to randomize, but it encourages startscumming, so I'd prefer to eliminate random rolls at game start.
