### ISSUE TITLE
Monomolecular blade does not use cutting skill

### ISSUE THREAD

**Issue by vlad1492** [CleverRaven/Cataclysm-DDA#36277]
Fight all day, cutting skill does not increase. 

1. Start with a bionic assassin
2. Check 'Cutting Weapons' skill level
3. Go fight with your monomolecular blade
4. Note zero increase in skill

# Expected behavior
Should incease like knives and swords. 
# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-10157-gcf1dc76 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    More Survival Tools [More_Survival_Tools],
    Makeshift Items Mod [makeshift],
    Icecoon's Arsenal [ew_pack],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    PKs Rebalancing [PK_REBALANCE],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Arcana and Magic Items [Arcana],
    Bionic Slots [cbm_slots],
    Fuji's Military Profession Pack [fuji_mpp],
    Manual Bionic Installation [manualbionicinstall],
    Safe Autodoc [safeautodoc],
    Sleep Deprivation [sleepdeprivation],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

**Comment by Rivet-the-Zombie** [comment]
Doesn't it use unarmed skill instead?

**Comment by Amoebka** [comment]
All bionic weapons use and level unarmed skill for whatever reason.

**Comment by Rivet-the-Zombie** [comment]
That would be because they're attached directly to your arm or hand.

**Comment by vlad1492** [comment]
Hmm. A foot-long indestructible blade with a profoundly sharp edge. Somehow I don't think conventional unarmed techniques apply.   
Do punch-daggers use unarmed only?

**Comment by Rivet-the-Zombie** [comment]
>Do punch-daggers use unarmed only?

I believe so.

**Comment by Little-119** [comment]
I imagine, based on the description, that the mono-molecular blade works like the nanoblade in Deus Ex. As it's fixed to your forearm, as opposed to being held in your hand, the motions you make would probably be more similar to unarmed combat or combat with a punch-dagger (because you'd be able to make slashing motions) than combat with a sword or similar weapon.
