### ISSUE TITLE
Bread and flatbread recipes acting weird

### ISSUE THREAD

**Issue by BenlyAZ** [CleverRaven/Cataclysm-DDA#36280]
# Describe the bug

Some recipes, including bread and flatbread but possibly others (those are the two I've noticed), do not appear in the usual place on the crafting menu. Searching for bread locates them, with a skill requirement of N/A and no ingredient or tool requirements. I assume the problem involves my mods somehow because otherwise I imagine a lot more people would be discussing it.

# Steps To Reproduce

1. I open up the crafting menu and go to "food -> bread"; bread is not there.
2. I search the crafting menu for bread and it appears.
3. If I select it, I get free bread.

# Expected behavior

I would expect the recipes to appear where they belong and not be free.

# Screenshots

The recipe as displayed when searching for bread.

![Screenshot (63)](https://user-images.githubusercontent.com/51046470/71223965-2ab8f700-22a3-11ea-9408-6aee6da5cd61.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.D-10537-g3b6a7bd [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    DinoMod [DinoMod],
    EZ-Mode Medical [fast_healing],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks],
    Classes and Scenarios Mod [more_classes_scenarios],
    Safe Autodoc [safeautodoc],
    Prevent Zombie Revivication [no_reviving_zombies],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Mining Mod [Mining_Mod],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Simplified Nutrition [novitamins],
    No Fungal Monsters [No_Fungi],
    No Rail Stations [No_Rail_Stations],
    No Fictional Guns [no_rivtech_guns],
    No Sci-Fi Equipment [no_scifi],
    Gun Cotton [guncotton],
    No Explosive Zombies [No_Explosive_Zombies]
]

**Comment by LaVeyanFiend** [comment]
Already fixed per #36275/Build 10041.
