### ISSUE TITLE
NPC attacks player through Z-level

### ISSUE THREAD

**Issue by Xenotrenium** [CleverRaven/Cataclysm-DDA#36291]
# Describe the bug

NPC's can attack the player through the floor. 

# Steps To Reproduce

Find Outpost, or possible other good testing location
Locate Hostile NPCs above you
Move under the NPC's so that you are horizontally adjacent

# Expected behavior

Attacks through the floor should not be possible

# Screenshots

**If applicable**, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/15146006/71250242-7c06cc00-231f-11ea-84ae-c9fb23131692.png)

![image](https://user-images.githubusercontent.com/15146006/71250316-a3f62f80-231f-11ea-9fe9-2491700f58cb.png)

![image](https://user-images.githubusercontent.com/15146006/71250385-d30ca100-231f-11ea-82eb-064e9da728ec.png)
-> teleporting one z-level straight up
![image](https://user-images.githubusercontent.com/15146006/71250354-be300d80-231f-11ea-839f-bcff3a20e433.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-10554-g418fa9c [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    Makeshift Items Mod [makeshift],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks],
    Bionic Slots [cbm_slots],
    Fuji's Military Profession Pack [fuji_mpp],
    Stats Through Skills [StatsThroughSkills]
]

#Additional Notes
If standing on top of a staircase with zombies under you, you can hold TAB to attack them - might be related.

EDITS:
Additional Information: Z-Level on, 3D vision on (1lvl limit)
NOT tested if possible when OVER NPCs
NOT tested if REVERSE is possible when OVER NPCs

**Comment by esotericist** [comment]
Just for the sake of confusion: there are some known issues with 3d vision that cause things like this. There's work in progress to resolve that, but they're not going to happen before 0.E
