### ISSUE TITLE
Throwing wielded objects

### ISSUE THREAD

**Issue by DeimosDread** [CleverRaven/Cataclysm-DDA#36293]
When using a thrown object such as "throwing axe" or "throwing knife" it deals a minuscule amount of damage when thrown while wielded, but when thrown straight from the inventory it deals full/appropriate damage. Thrown object also disappears after being thrown while wielded.

# Steps To Reproduce

1. Spawn new character, thrown axe/knife, and (basic) zed.
2. Wield axe/knife and throw at zed. It will fail to penetrate armor. (Repeat ad nauseam)
3. Drop axe/knife and throw one from inventory, normal damage and armor pen. Weapon appears on ground when thrown.

# Expected behavior

Normal damage regardless of if the weapon is wielded or not. 
Normal weapon recovery when being thrown while wielded.

# Versions and configuration

- OS: Windows 10
    - OS Version: 10.0 1903
- Game Version: 0.D-10554-g418fa9c [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

I've tested this with homebrew items, and weapons with the same results.

**Comment by davidpwbrown** [comment]
related to https://github.com/CleverRaven/Cataclysm-DDA/issues/36271  and https://github.com/CleverRaven/Cataclysm-DDA/issues/36239 I imagine
