### ISSUE TITLE
Risky Terrain Legacy Mode

### ISSUE THREAD

**Issue by Muntari** [CleverRaven/Cataclysm-DDA#36314]
**Is your feature request related to a problem? Please describe.**  
I'm always frustrated when I have to toggle running just to walk a risky terrain, default settings were much less bothersome.

**Describe the solution you'd like**  
Provide legacy behaviour. Also running into risky terrain should discount stamina cost when running mode is turned on.

**Comment by Muntari** [comment]
disregard what was said about the stamina cost, unless the run move is going to take as much move time as a walk move

**Comment by Ramza13** [comment]
#36037 will add this .
