### ISSUE TITLE
Crafting uses best item available

### ISSUE THREAD

**Issue by Berkyjay** [CleverRaven/Cataclysm-DDA#36310]
**Is your feature request related to a problem? Please describe.**  
When crafting, the worst components seem to be used first.  For example if crafting clothing dirty or poor fit items are used first.  If cooking, rotten components are always used first.

**Describe the solution you'd like**  
The crafting process should always use the best components available.  This is assuming that the PC has some agency of their own and will not choose components that would produce unusable items.  

**Describe alternatives you've considered**  
At the very least, the player should be prompted before crafting starts in order to save in game time.

**Comment by sztosz** [comment]
I would love to be able to choose components by hand from all available. Especially for cooking, when I cook something I want to eat just right after, I want to use the items that spoils soon first, but game often uses automatically not those components I would like it too. Sometimes games open new jar of pickled or can of canned meat, when there is already one open. I guess solution for that is to move components you don't want to be used out of your reach when crafting. Still being able to choose exactly what to use would solve all of those issues, both yours and mine.
