### ISSUE TITLE
Military and police roadblocks should be visible on the overmap

### ISSUE THREAD

**Issue by SirPendrak** [CleverRaven/Cataclysm-DDA#36321]
**Is your feature request related to a problem? Please describe.**  

Increase in range of turets made them much more dangerous, especially military ones that have death zone of about 80% of player vision range. 
In some situations, like driving a vehicle at reasonable speed 60 km/h or when going through dense forest you can encounter unfair situations when you get oneshot by .50 bullet and that 200 movecost aimtime is not enough to fall back to safety. 

**Describe the solution you'd like**  

Both versions of roadblocks should appear on overmap like military bases, bunkers etc. do. 
After all, if you can see the road, and sometimes even objects behind that road, especially with binoculars, then you should know there is something ahead. And it would reward scouting terain from high places a bit too. 

**Describe alternatives you've considered**  

Remove roadblocks from game and lore. Theyre not hard if youre creative and prepared, but can be unfun, and provide shit tons of ammunition that can make you unstoppable monster clearing whole towns if you just have the right riffle. But thats another problem. 

**Additional context**  
I know CDDA is mixed apocalypse and not only zombies, but zombies should remain main threat.

**Comment by Little-119** [comment]
They do appear (as notes) if you turn on the `Autonotes (map extras)` option.

Though, on that note, perhaps `Autonotes (map extras)` should be set to be enabled by default, and additionally the notes for roadblocks should be marked with a red `!` instead of a yellow `x`.

**Comment by Amoebka** [comment]
You can manually edit map_extras.json to set which extras you want autonoted and which symbols/colors are used for each one.

**Comment by Fris0uman** [comment]
This https://github.com/CleverRaven/Cataclysm-DDA/pull/35821 should reduce the threat from thos roadblock a lot

**Comment by Zupercharged** [comment]
I personally quite like making notes on the locations of various things myself, roadblocks included.
