### ISSUE TITLE
Option to change position of "look around" and "aim" windows

### ISSUE THREAD

**Issue by Kilvoctu** [CleverRaven/Cataclysm-DDA#36327]
**Is your feature request related to a problem? Please describe.**  
I like my sidebar position on the left. The UI windows for looking around and aiming a weapon are always on the right. This causes an undesired amount of stuff on screen when being used.
In the interface options, Pickup window position can be changed between left, right, and overlapping; however, there are no similar options for Look Around nor Aim.

**Describe the solution you'd like**  
An option for the position of the Look Around window and the Aim window to be displayed on the left side.

**Additional context**  
Looking around while sidebar is on the left.
![before](https://user-images.githubusercontent.com/2993060/71312297-ad020200-23ee-11ea-8258-6f78f959eb9b.jpg)

Mockup of desired window location.
![after](https://user-images.githubusercontent.com/2993060/71312299-ad020200-23ee-11ea-973c-f20d86687125.jpg)

Aiming a weapon at a certain enemy can be inconvenient at times.
![before2](https://user-images.githubusercontent.com/2993060/71312298-ad020200-23ee-11ea-81a7-bc062479b673.jpg)

Mockup of desired window location.
![after2](https://user-images.githubusercontent.com/2993060/71312296-ad020200-23ee-11ea-9810-08050f539cec.jpg)

**Comment by kevingranade** [comment]
Reopening because it just got caught in the feature freeze.
