### ISSUE TITLE
Disjointed Anthill Generation

### ISSUE THREAD

**Issue by Zourin2** [CleverRaven/Cataclysm-DDA#36320]
Anthills can be generated with many chambers disconnected from the entrance/tunnel system. 

This is possibly duplicate of #27726 but that issue has been untouched in almost a year.

[Screenshot](https://i.imgur.com/butjExa.png)

[Cresthaven.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3991332/Cresthaven.zip)
Attached save file w/ debug character at the glitched anthill. I advise using debug teleports.

Mods at generation: Stock with No fungals

**Comment by Outta-my-way-burrocrat** [comment]
This happened before: https://github.com/CleverRaven/Cataclysm-DDA/issues/20417 https://github.com/CleverRaven/Cataclysm-DDA/pull/21438

**Comment by Night-Pryanik** [comment]
Closing as duplicate.
