### ISSUE TITLE
Weird binary in recent commits on i686 arch

### ISSUE THREAD

**Issue by tim77** [CleverRaven/Cataclysm-DDA#36336]
# Describe the bug

New weird binary appeared in recent commits. It only happened on i686, others 32-bit arches doesn't have this issue:

`/usr/bin/cataclysm.gdb-index-lYI7vO`

Full build log
https://kojipkgs.fedoraproject.org//work/tasks/8773/39858773/build.log

# Versions and configuration

 - OS: Fedora Rawhide
 - Game Version: build #10048 https://github.com/CleverRaven/Cataclysm-DDA/commit/e04ddf1f5ea5ca5c1eb8c49e4b54d1d9e110fe56
 - Graphics version: Tiles + Terminal

**Comment by ZhilkinSerg** [comment]
From what I can tell it is gdb and/or environmental issue:

```
extracting debug info from /builddir/build/BUILDROOT/cataclysm-dda-0.D.10049-1.20191221git1e8f27e.fc32.i386/usr/bin/cataclysm-tiles
../../gdb/utils.c:691: internal-error: virtual memory exhausted: can't allocate 30800306 bytes.
A problem internal to GDB has been detected,
further debugging may prove unreliable.
```

**Comment by tim77** [comment]
Tried to reduce GDB verbosity but no lock. There is much more then enough memory both RAM and disk space. Disabled i686 build since Fedora deprecated this arch anyway on >= F31. Sorry for noise.
