### ISSUE TITLE
Craters spawning and z level

### ISSUE THREAD

**Issue by 1n17** [CleverRaven/Cataclysm-DDA#36346]
# Describe the bug
Overmap special crater seem to be spawning creatures regardless of z level

# Steps To Reproduce
Start a game in lab complex, hang around for a while in/near rooms that have crater special on surface level, notice influx of nether creatures - alternatively in last step: unexpectedly die wondering form where did that flying polip came

# Expected behavior
Are craters even supposed to spawn creatures, that seems to be a job for a portal. Whatever the case may be, spawning should probably not go trough layers of solid rock.

# Screenshots
# Versions and configuration
0.C-47743-g38a3cdcc88

# Additional context

**Comment by ZhilkinSerg** [comment]
Craters do not spawn any creatures by themselves.

**Comment by ZhilkinSerg** [comment]
Also, did you report version number correctly? We do not take bug report for legacy versions (0.C) unless issue is still present in latest experimental version.

**Comment by 1n17** [comment]
That is what 'make version' says on what I pulled from master and compiled about a week ago (upon checking - 10 days), last commit 38a3cdcc887c000c7d2370edd66b38f433ee7096, if that is 'legacy' idk what to say..
Anyhow, would that not be case of craters behaving oddly (and I very much doubt it since i can reproduce it in any lab room under crater special - and there are multiple of those generated on surface level of lab complex, on any z level and it does not happen in any other room) what might be the case of those spawns

**Comment by ZhilkinSerg** [comment]
Yeah, I can see commit hash, but `make version` should report `0.D` instead of `0.C`.

Anyway, do you have an affected savegame to check overmap there? There could be map extra looking like crater (or even spawned over `crater` terrain) which can possible spawn nether creatures.

**Comment by Zupercharged** [comment]
One thing that I have noticed is that labs with the portal finale tend to spawn migos and nether creatures on z levels directly above the finale all the way up to the top of the lab, but not on the surface. It may be that the crater being on top was just a coincidence and it was actually just the finale.

**Comment by Zupercharged** [comment]
One thing that I have noticed is that labs with the portal finale tend to spawn migos and nether creatures on z levels directly above the finale all the way up to the top of the lab, but not on the surface. It may be that the crater being on top was just a coincidence and it was actually just the finale.

**Comment by Qrox** [comment]
> Yeah, I can see commit hash, but make version should report 0.D instead of 0.C.

It actually checks the most recent tag and use that as the version prefix. I also had this problem until I fetched the 0.D tag from the repo.

**Comment by 1n17** [comment]
Yes, well.. I had a moment to investigate this further, so:
The lab type in question (if that is of any relevance) is one with parking lots and research facility overmap tiles on surface level, lab basement below it and otherwise standard lab further down.
Crater specials that were my suspect appear to not be related to the spawning after all as only single overmap coordinate is the spawn source and monsters were simply bleeding out to adjacent rooms - craters in L shaped pattern overlapping that coordinate led me to false conclusion there.
Now, portal finale - interesting, I double checked just now - nope.
Another thing I've noticed that monsters spawned seem to be on some sort of life timer, or otherwise something is killing them - the floor of the 'spawn room' on z-level I've spent several days on is strewn with corpses - making only a few of which can be ascribed to me. I suspect a broken generator one z-level above.. Sparks definitely don't appear on other z-levels but perhaps damage does get applied?
And in case there was any doubt about it, I am playing with 'experimental z-levels' option enabled (and with wander spawns enabled as well).

**Comment by 1n17** [comment]
One more observation, 'Portal In' special in at the very top level of research facility overmap tile at the coordinate that spawns happen - could that possibly be the culprit?

**Comment by 1n17** [comment]
Not sure why this got closed - I for one still have no idea what is causing continuous spawns of nether creatures on multiple z-levels, nor what would even be capable of such a feat, as after looking over mx_portal_in and related code it seems they could do one time (at creation) spawn only.

**Comment by anothersimulacrum** [comment]
It's not closed?

**Comment by sxzd** [comment]
I'm pretty sure its the tears in reality in lab finales that are causing constant spawns of nether creatures. I waited on top of a tear in reality that was 6 Z-levels below and nether creatures started spawning in sporadically. The lab was hidden in the basement of a random house in a city and there doesn't seem to be any other reason for why the nether creatures were spawning in.  The nether monsters only spawn on the same Z-level as the player. They also only spawn on the same map tile as the tear in reality. There's a save file attached where if you wait 30 in-game minutes with the debug character, you can see the bug in action. 
The save was made on version 0.D-10872-ga8dfebc. Tested on version 0.D-10899-g528f49b.
[Test.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4012116/Test.zip)

The shimmering portals are not to be confused with the tears in reality, they're two different (though very similar) things.

**Comment by kevingranade** [comment]
Thanks for mentioning the tears in reality, that helped.

It turns out this is caused by map::add_spawn(), which accepts a point instead of a tripoint, so when the tear in reality tells it to spawn a monster "nearby", that is translated into "nearby on the active map", which is the level the player is on.  Looking into a fix now.
