### ISSUE TITLE
Dissoluted Devourer Insta-kill on salvaged robots

### ISSUE THREAD

**Issue by RiPCorD5A1** [CleverRaven/Cataclysm-DDA#36348]
# Describe the bug

Dissoluted devourer is able to use Zombie_fuse ability to insta kill salvaged robots

# Steps To Reproduce

1. Spawn into a world.
2. Spawn both a salvaged robot and a devourer.
4. Activate the inactive robot.
3. Wait for devourer to fuse with robot

# Expected behavior

For this interaction to not happen. I'm not a coder in the slightest and the mob doesn't have a lot of lore so i'm only going by the flag name and the balance associated.

# Screenshots

![Devour](https://user-images.githubusercontent.com/59139849/71322708-2f8ece00-2490-11ea-8a92-b311d9eda14b.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-10562-gf1e683c [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    Disable Mutagens [no_mutagen],
    Disable Religious Texts [no_religious_Texts],
    No Explosive Zombies [No_Explosive_Zombies],
    No Acid Zombies [No_Acid_Zombies],
    Fuji's Military Profession Pack [fuji_mpp],
    Prevent Zombie Revivication [no_reviving_zombies],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills]

On tests this interaction may take a long time to happen. Moving into the robot and displacing them seems to speed this up.

**Comment by Ezsk** [comment]
Devourer zombies seems to killing any mobs even it is a robots and player's pets.
and monattack.cpp is like this now.

```
    monster *critter = nullptr;
    for( const tripoint &p : g->m.points_in_radius( z->pos(), 1 ) ) {
        critter = g->critter_at<monster>( p );
        if( critter != nullptr && critter->faction == z->faction
            && critter != z && critter->get_size() <= z->get_size() ) {
            break;
        }
    }
```

store the nearby  mob in *critter.
it decision the it is able to fuse. if so break the loop.
but also last mob in the loop will stored in *critter and goes to fusion process no matter it is able to fuse or not.   

Looks this is a simple bug.
I don't have environment to test the code and compile. so I hope someone else fixes this.

**Comment by anothersimulacrum** [comment]
Suggested fix: set critter to nullptr when you break.
