### ISSUE TITLE
Exessive pharmacy loot

### ISSUE THREAD

**Issue by Zupercharged** [CleverRaven/Cataclysm-DDA#36353]
# Describe the bug
So ive been having issues with the loot levels of a particular kind of pharmacy for a while now, where it provides so much loot in such great variety that it removes all enjoyment and purpose for further looting.

To be specific, the sheer quantity of supplies in these locations both medical and otherwise are very much in excess of what one would expect from both a narrative and gameplay perspective and can quite happily meet all immediate needs of most survivors to support them for more than enough time for them to fully prepare, making even the idea of looting anywhere else unattractive and unrewarding.

For such a prime and obvious target for looting it is odd to find it nearly fully stocked compared to anywhere else. Not to mention that the building itself is barely defended while also being very secure, making the loot inside laughably easy to get and with no pressure to attempt to extract it in any great hurry or have to leave any behind.

Worst of all, it is completely disproportionate from the quantity of loot anywhere else for something that occupies the space of a single plot of land the size of a typical house with about as much protection. Reducing the loot spawn rate is not a solution as the loot elsewhere does not feel so egregiously generous, so by lowering it to a sensible level it leaves everywhere else barren in comparison.

# Steps To Reproduce

1. Create a new world with loot density 1.00.
2. Find a pharmacy in the city.
3. Inspect the loot in stock.

# Expected behavior

I would expect the loot in this location to be more comparable to the quantities found in other locations at the same loot density, maybe 1 in 3 shelves stocked and with no more than 2-3 different items per shelf.

As the inventory below demonstrates, I would also expect the loot tables to be more specific to the specialties of a pharmacy. Books being more specific to First aid and Chemistry (Cooking) as well as perhaps more social skills, Tools being more health and relaxation focused (yes even vibrators), Less food overall, with less sweets and soft drinks and more healthy snacks like protein bars and fruits and stuff, as well as more water and tea and whatever.

# Screenshots
![overall picture](https://user-images.githubusercontent.com/58523066/71324204-ea8c8b00-24d3-11ea-8672-7adfd885d2b5.png)
_Composite map of the entire pharmacy before taking an inventory of all the loot._

![drugs](https://user-images.githubusercontent.com/58523066/71324211-f8421080-24d3-11ea-9bf0-dab8ecf0ca33.png)
_Full inventory of all medical loot from the pharmacy._

![food](https://user-images.githubusercontent.com/58523066/71324220-14de4880-24d4-11ea-9c36-2b18f7cee1cf.png)
_Full inventory of all foodstuffs from the pharmacy. Do note that a lot of the red and greyed out items would be perfectly edible to a non-carnivore character._

![books](https://user-images.githubusercontent.com/58523066/71324237-4ce58b80-24d4-11ea-94ef-8ba0223414a3.png)
_A full inventory of all Books from the pharmacy. Note that the skill books cover a range of skills unrelated to medical care as well as the map._

![other](https://user-images.githubusercontent.com/58523066/71324270-cda48780-24d4-11ea-8bce-d6b8d2697d19.png)
_Full inventory of all other miscellaneous items from the pharmacy. Note the Toolbox, metal files, sewing kit and gun. Also note that the ID cards were not from the pharmacy, I forgot to drop them for the screenshot._

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-10610-g8761541 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Cataclysm++ [Cata++],
    NPC traits [npc_traits],
    Zetsukaze's Hair - 0.D EDIT [zets_hair_extensions],
    More Locations [more_locations],
    Zet's Hair - More Locations [zets_hair_ext_more_locations],
    Fuji's More Buildings [FujiStruct],
    Mapgen Demo [mapgen_demo],
    No Rail Stations [No_Rail_Stations],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Roadheader and other mining vehicles [Heavy miners],
    Bionic Slots [cbm_slots],
    Classes and Scenarios Mod [more_classes_scenarios],
    Disable NPC Needs [no_npc_food],
    Fuji's Military Profession Pack [fuji_mpp],
    Sleep Deprivation [sleepdeprivation],
    SpeedyDex [speedydex],
    Graphical Overmap [Graphical_Overmap]

# Additional context

First of all I would like to confirm I am playing with an unchanged item spawn scaling factor of 1.00.

This is actually the third time I have thought of making this issue, but at first I wasn't certain if it was a mainline issue or not, nor if it was just an isolated case. I have since rechecked this particular pharmacy multiple times (my latest save does not have loot generated so the loot is different each time, though still in the same quantities) and I have also made an effort to confirm with any other pharmacies I could find. However I have only been able to find pharmacies of this particular floor plan so I do not know if the other variant is similarly overstocked, I can however confirm that this kind of pharmacy was consistently overpopulated.

As a result the screenshot examples I took were my third attempt to document this issue before I left for a week (version 10007) . From what I have read no additional changes have been made on the loot spawns, however before submitting this issue I did update to the most recent version (10053) and confirmed the issue still persisted for me. The Versions and configuration data is from this most recent check and not from the time of the screenshots.

I have also enquired on the Discord a few times to confirm details where I could, and was kindly provided a link to this particular pull request (https://github.com/CleverRaven/Cataclysm-DDA/pull/35175) which may be related, and if not it may be possible to tweak in order to provide a solution.

Finally I would like to recognise that this is technically a personal issue, based on a subjective opinion on what is an appropriate volume and spread of loot. Despite that I do sincerely believe this is an issue which significantly impacts both the enjoyment and balance of the game, hence the submission of this report.

**Comment by Zourin2** [comment]
I must point out it is feasible, however improbable, for a store to not have been picked clean. Shops have a LOT of stock and if there wasn't anyone alive nearby to do anything about it, it would still be there. The fabled unspoiled treasure.

That said, this should be a rarity, Also, with so many people possibly getting sick and panicking, you would expect to see a significant zombie presence inside of pharmacies and food stores as the remains of those who thought the proper move was to stock up on toilet paper and bottled water.

**Comment by Zupercharged** [comment]
> I must point out it is feasible, however improbable, for a store to not have been picked clean. Shops have a LOT of stock and if there wasn't anyone alive nearby to do anything about it, it would still be there. The fabled unspoiled treasure. If it were realistic, almost every 'still sealed' pharmacy would have enough meds for hundreds of people or more, which would be a lot more than the cornucopia you're complaining about. Think about how many antibiotics your local pharmacy probably has stocked. Thousands of pills? Millions?<

Honestly I don't entirely disagree with this argument, however I have a few issues with this, the first of which you have addressed;

**Why are all of the pharmacies fully stocked?** 
This is of course an issue of luck and probability, but as you said, there needs to be less certainty with how much you will find. In my opinion it would be best to have well stocked pharmacies like these be a rarity, and as I will detail below, much more seriously protected. But I think you agree that some kind of system to generate variations in the volume of loot from stocked to looted would be more 'realistic' 

My argument on the diversity of the loot pool still stands.

**What about the gun shops?** 
Currently gunshops even at their best are nowhere as well stocked as this, in fact no other shop is and yet none of these locations feel understocked. This is one of the big reasons I find it to be an issue, as the density of loot here is out of balance with every other location in the game! Why aren't the backrooms of computer stores full of mountains of video game sets? Why aren't there grocery trucks full of canned foods? The argument for this can be made for virtually any location but yet they aren't stocked like this and the main reason is balance, because too much loot in one area devalues all others. Why bother raiding a mini lab when you will get more medical supplies just prying a door to a pharmacy?

**What's the point of the Item spawn scaling factor (ISSF) setting?** 
When discussing this beforehand a few people said 'if you don't like it turn down the loot density', which should be a valid point except it isn't because the loot density literally everywhere else is fine and so by bringing this inline I starve every location and the issue persists. If you want to play a world where shops are pristine, or one everywhere has been picked clean, the ISSF should be the measure to facilitate that.

Perhaps a second value for loot density called 'Item spawn scaling variation factor' or something, which defines a maximum and minimum to each side of the ISSF such that the loot generated in each location would generate with an ISSF somewhere within the defined range? However this would be a feature well outside the scope of this issue.

**Where's the challenge?** 
I don't know about everyone else but I play this for the !!FUN!!. I don't actually dislike the idea of a well stocked shop, however I _do_ dislike a well stocked shop that has no realistic defence, because if I with a pole bent into the shape of a crowbar can get in... its not very secure, to the point where I would argue its actually more realistic that no one got in before. Even gunshops feel more protected and rewarding, with a well stocked one having a gun or ammo on every other shelf and gun safes which are actually a challenge to get into without damaging the contents inside as opposed to almost every shelf spilling with 1-5 different items on each.

Zombies more commonly populating the interior would be a good start, but that's not nearly equivalent to the sheer quantity available. What if the reason the best stocked pharmacies were protected was because FEMA designated them early on as frontline clinics when things were still considered as riots, thus fortifying it with one or two turrets on the open area out front (or maybe even inside) and more evolved zombies like soldiers, scientists and hazmats? This would of course be rare and a feature well outside the scope of the issue I have highlighted, but it would go a long way to making a hoard like this feel rewarding to get.

**Comment by Amoebka** [comment]
Hilariously enough, that's how a **looted** pharmacy looks. 15 antibiotic pills is literally one blister pack the previous looter forgot behind the counter. An unlooted pharmacy would, as mentioned above, have tens of thousands of pills.
If anything, looting a pharmacy and **not** finding an antibiotic pill is unreasonable. You shouldn't have to raid a secret underground superscience lab to get one.
What concerns me more is the variety. Why are there non-medical books, toolboxes and snack foods in a pharmacy? Guns can at least be used to solve most medical problems, what's the excuse for the rest?

**Comment by Zupercharged** [comment]
To be clear, my issue isn't how many pills spawn in one (i am perfectly fine with aspirin always spawning in 20s and i consider it 1 singular drug item when discussing spawns), that is not the issue i am raising here. If the loot variety was reduced and then the amount of items that could spawn per shelf limited to 1 or 2, you would likely still walk out of a pharmacy with a drug list similar to the one listed above because a big part of the problem is that the shelves are overpopulated with _other stuff_.

I suggested 1 in 3 shelves spawning with 1-2 separate item spawns because that is generally what you expect to find in a gun store. With what you have said I actually agree that pills being smaller and more common should probably have greater spawn density, but that's fine, the issue i am raising is in essence that pharmacies are currently unbalanced so this is entirely open to discussion on what a balanced pharmacy should look like. So yeah i agree with what you're saying, but what would it look like? 

Personally I am leaning towards spreading the medically relevant loot over the shelves so that the pharmacy still looks full but each shelve doesn't have 4 or 5 separately spawned items, with 1-2 items in some of the shelves out front but the back rooms having every shelf stocked with 1-3 different drugs each.

**Comment by Ker-Nes** [comment]
>  What concerns me more is the variety. Why are there non-medical books, toolboxes and snack foods in a pharmacy? Guns can at least be used to solve most medical problems, what's the excuse for the rest?

It's realistic. Most pharmacies nowadays do have a pretty varied stock, specially of those small stuff someone might buy anyway while being there buying other stuff or even just passing by. Soft drinks, minor snacks, the like.

**Comment by CataphractPrime** [comment]
Note: Pharmacies always have high glucose confections near the front counter. From what I hear, this is for the benefit of diabetics.

**Comment by Zupercharged** [comment]
>It's realistic. Most pharmacies nowadays do have a pretty varied stock, specially of those small stuff someone might buy anyway while being there buying other stuff or even just passing by. Soft drinks, minor snacks, the like.

I would argue 'pretty varied stock' doesn't cover them stocking heavy reading on mechanics or fabrication, nor specialist metal working tools and tailor kits or firearms. As for snacks; gum, protein bars, juice and other healthier things (glucose things included) are what I would expect a pharmacy to endorse. What you said was not wrong but it doesn't translate to what is actually stocked in game.

Realism is only one side of the scale, the other being balance. While plausible, the pharmacy doesn't need to stock car jacks or whatever, it just needs to stock drugs. Im not against a bit of variety but this isn't a general store, the extra items shouldn't be taking up half the shelf space. I still think restricting the misc loot pool to more general items and reducing its shelf space to an isle or two near the checkout, and then spreading the rest of the drug spawns across the freed up shelves is the best course of action. This is still plausible, _still realistic_, but also _more balanced_.

**Comment by Ezsk** [comment]
Well... this discussion will take several months.
Can we restrict pharmacy shops by blacklist mods ?

**Comment by mkikt4743** [comment]
yeah should probs just contain lots of medical loot and books, not any guns or tools, my local CVS has a lot of food as well, not just near the counter. Tools should really only be found in house garages and hardware stores

**Comment by Orinyau** [comment]
I'm okay with the random gun. Weren't gun laws reduced before the cataclysm? What with the riots and stuff it could have been an employees personal firearm. 

Unless it spawned on the shelf. If so, that's just silly.

**Comment by LaVeyanFiend** [comment]
> Weren't gun laws reduced before the cataclysm?

That lore note was removed, so no.

**Comment by Orinyau** [comment]
Where can one find the updated lore,. I notice there have been a lot of changes recently.
________________________________

**Comment by kevingranade** [comment]
I see one valid issue here, which is that I don't expect guns to spawn in an average pharmacy.
It looks like this is caused by the "behind counter" spawnngroup, which is evidently targeting a stereotypical inner city gas station or bodega with a gun under the front counter. We need to be more careful about where that item group gets used.

Everything else seems like something I expect to find in an American pharmacy,  from the medicine to the magazine racks to the junk food to the tools.

One thing it's missing is rows upon rows of cosmetics and cleaning products.

As for quantities, things are in flux as we're overhauling spawn lists all over the game, but there's no way I'm aware of to holistically overhaul how we handle spawningvwithout a few discontinuities like this.

**Comment by Zupercharged** [comment]
Since first posting this issue, anothersimulacrum has informed me of the overarching changes to loot quantities so I consider the issue of the loot density imbalance to be a symptom of active development, which is fine. I can certainly understand iterative changes to do bug fixes bit by bit instead of all at once.

As for the pharmacy loot pool thanks for taking it into consideration, it was originally the lesser of the two issues but im glad it was of some use. Im certainly alot more comfortable with most of it knowing every other location is also being overhauled to a similar standard, though I do still find the toolboxes and tailoring kits to still be a bit too specialized.
