### ISSUE TITLE
Deconstructing gravel yields pebbles and "nothing" tile

### ISSUE THREAD

**Issue by Gremilcar** [CleverRaven/Cataclysm-DDA#36366]
# Describe the bug
After using "*" to deconstruct gravel tile I get pebbles and black "nothing" tile

# Steps To Reproduce

1. Find gravel tile (I found mine near silo at the farm)
2. Press * and use "Deconstruct furniture"

# Expected behavior

Either tile should not be deconstructable or result in default "dirt" tile 

# Screenshots

https://i.gyazo.com/52b5f0ea231ca48cbc69771a3a96483f.png

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-10610-g8761541 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Garden Pots [growable-pots],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    Mining Mod [Mining_Mod],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

**Comment by snipercup** [comment]
Duplicate of #35977

**Comment by Gremilcar** [comment]
My fault didn't check this one
