### ISSUE TITLE
Horse reins

### ISSUE THREAD

**Issue by ymber** [CleverRaven/Cataclysm-DDA#36373]
**Is your feature request related to a problem? Please describe.**  
Horses can only be led through dangerous areas by riding them.

**Describe the solution you'd like**  
Add reins you can attach which will force the horse to stay within 1 tile of you.

**Describe alternatives you've considered**  
Give horse 2-3 tiles of movement when holding reins.

**Comment by ymber** [comment]
#37148 didn't address this. The issue is about keeping them following you while you're on foot.

**Comment by ZhilkinSerg** [comment]
Thanks. It was addressing #37147 and closed this issue by accident.

**Comment by Night-Pryanik** [comment]
Resolved by #50890. Not with reins though, but with a rope, but I think it doesn't matter.
