### ISSUE TITLE
Autocombat (TAB) tries to move into friendly robots

### ISSUE THREAD

**Issue by Amoebka** [CleverRaven/Cataclysm-DDA#36375]
# Describe the bug

When using autocombat (pressing TAB by default) adjacent to a friendly robot, player character will attempt to move into the robot triggering the disable/swap prompt. This makes melee combat with robotic allies helping you extremely annoying and tedious (can't use tab because of the prompt spam).

# Steps To Reproduce

1. Stand adjacent to a zombie and a friendly robot.
2. Press tab or whatever button you have for autocombat.
3. Sometimes you will hit the zombie, sometimes you will be prompted to swap positions with your robot.

# Expected behavior

Friendly robots aren't treated as acceptable targets for autocombat. Pressing tab when adjacent to both ally and enemy always attacks the enemy. Pressing tab when adjacent to an ally and no enemies doesn't trigger the disable/swap promt and waits a turn instead.

# Versions and configuration

 - OS: win10
 - Game Version: 0.D-10626-gb9b3dc2
 - Graphics version: tiles
 - Mods loaded: none

**Comment by Ezsk** [comment]
This problem occurred with NPCs. not only robots.
