### ISSUE TITLE
NPC followers stopped being friendly.

### ISSUE THREAD

**Issue by Berkyjay** [CleverRaven/Cataclysm-DDA#36386]
# Describe the bug
All of my NPC followers stopped being friendly with me.  I can still access their dialog tree normally.  But they no longer follow orders, nor will they follow me, nor can I adjust their armor.  Telling them that "I'm going my own way" does nothing as well.  This issue happened after my last update of the game.

# Steps To Reproduce
Load up game and attempt to interact with NPCs in the area.  You can tell them to follow but they won't follow.  You can attempt to reorder their armor, but it says that they aren't friendly.

# Expected behavior
NPC followers respond to requests.

# Screenshots
![NPC_01](https://user-images.githubusercontent.com/5049386/71374867-2a558000-2571-11ea-9ce7-27406226ac86.PNG)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-10628-gf7cb595 [32-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Mutant NPCs [mutant_npcs],
    Bionic Slots [cbm_slots],
    Classes and Scenarios Mod [more_classes_scenarios],
    Stats Through Skills [StatsThroughSkills],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks]
]

# Additional context
https://drive.google.com/open?id=1W-fqK9cDAS-jPBW1lOlm32mI3kJd3uQf

**Comment by RiPCorD5A1** [comment]
Can confirm similar issues. Mine was when i tested to see if follower would go to assigned camp when i said i would go on my own. The npc left the faction and stole some things. when i talked to her again however the full follower menu would appear, however i could not not have her follow me again. I could make her guard a area, trade with her although the items she stole wouldn't appear, and ask her to due certain task which she wouldn't complete. I then sent her to the camp which she complied with and then stayed there, however as reload of the game she had disappeared, but she was still in the faction menu and a lone faction.

src/faction.cpp:426 [faction* faction_manager::get(const faction_id&, bool)] Requested non-existing faction 'solo_Lara 'Regiomontano' Schuler'
20:13:39.916 ERROR : (error message will follow backtrace)
    (@0x5f698e[cataclysm-tiles.exe+0x1f698e]), 
    (@0x5f6fca[cataclysm-tiles.exe+0x1f6fca]), 
    (@0x5fa256[cataclysm-tiles.exe+0x1fa256]), 
    (IMG_LoadWEBP_RW+0x1112d5@0x11e5005[cataclysm-tiles.exe+0xde5005]), 
    (@0x609e5e[cataclysm-tiles.exe+0x209e5e]), 
    (@0x7425c6[cataclysm-tiles.exe+0x3425c6]), 
    (@0x70d1dd[cataclysm-tiles.exe+0x30d1dd]), 
    (IMG_LoadWEBP_RW+0x643ffc@0x1717d2c[cataclysm-tiles.exe+0x1317d2c]), 
    (@0x4013ed[cataclysm-tiles.exe+0x13ed]), 
    (@0x4014fb[cataclysm-tiles.exe+0x14fb]), 
    (BaseThreadInitThunk+0x14@0x7ff958877bd4[KERNEL32.DLL+0x17bd4]), 
    (RtlUserThreadStart+0x21@0x7ff95a74ced1[ntdll.dll+0x6ced1]), 
Backtrace emission took 0 seconds.
src/debug_menu.cpp:1527 [void debug_menu::debug()] Test debugmsg
20:14:18.358 :  GAME REPORT:
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-10562-gf1e683c [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    Disable Mutagens [no_mutagen],
    Disable Religious Texts [no_religious_Texts],
    No Explosive Zombies [No_Explosive_Zombies],
    No Acid Zombies [No_Acid_Zombies],
    Fuji's Military Profession Pack [fuji_mpp],
    Prevent Zombie Revivication [no_reviving_zombies],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills]

**Comment by davidpwbrown** [comment]
@RiPCorD5A1 when you tell an NPC "I am going to go my own way" thats telling them to leave your faction. They will naturally revert to dynamic NPC behaviour at that point.

**Comment by RiPCorD5A1** [comment]
@davidpwbrown  I know that now but that was just the start of the chain reaction of errors.

**Comment by Berkyjay** [comment]
@davidpwbrown after looking at the NPCs in the debug menu it looks like they were all removed from the players faction.  It seems like they're stuck in this limbo of acting friendly but not technically friendly.

**Comment by davidpwbrown** [comment]
I think I know whats happening here.

1. the stop_guard() function had a wrong check, it erroneously set npcattitude etc to null when it thought that a non-follower was using the stop_guard() function, this then caused them to be considered a non-follower for some things, but a follower for other things ( chat topics ).
2. then when talking to them subsequently you wont be able to get them to stop guarding, as it will keep returning early as they arent considered a follower
3. You then tell the NPC you are going to go your own way, I see this in your message log berkyjay, one of your npc "leaves" your faction, this `leave()` function is only called from dialogue.

4. this can result in the debugmsg ripcord saw sometimes, as leave() tries to create a new solo faction for that NPC.

5. this all results, I think from stop_guard() doing some weird stuff.

6. if someone can try and make this happen again with exact repro steps id be very grateful for the chnace to confirm my suspicions.

**Comment by RiPCorD5A1** [comment]
Also on the fact that the npc disappeared after a reload of the program but is still in the faction menu is that the map shows the npc still at the camp, however she is nowhere to be found or is invisible

![map](https://user-images.githubusercontent.com/59139849/71385881-a66eb880-25af-11ea-9b8b-782e230c27b2.png)
 
![gone](https://user-images.githubusercontent.com/59139849/71385884-ac649980-25af-11ea-9bbf-db68dc951b31.png)

**Comment by davidpwbrown** [comment]
I think this is all related to the same original issue which causes a cascade of related problems.

However if you can get this to happen reliably in a reproduction case, then please let me know.

**Comment by Berkyjay** [comment]
@davidpwbrown Are you looking for a situation where we have NPCs in our faction that then lose the faction status?  I'm actually not sure how this even happened to be honest.  The only two things that happened were that 1) I updated the game & 2) I interacted with another faction a few overmap tiles away from my Faction Camp.  I can try recreating that, but it might take some time due to the holidays.

**Comment by Solusphere** [comment]
@davidpwbrown I had this happen on my save, and I can confirm that I definitely never told them to go their own way. This was on build 10047, and it appeared to happen immediately on game load in one session, even though I had played for several sessions previously on the same build. I updated to the latest version and it did not fix the issue, but I don't know if your fix has been deployed yet. I can provide saves immediately before and after the issue occurred, but I don't know how to reproduce it. The only thing I can think of that might have triggered it was that I created a separate character on the same world for testing purposes, who promptly died. I'm attaching two save folders before and after the issue. 18 is before the issue occured, 20 is after. The world is Clatonia, the character is Anneka Lee, and the affected follower is Latasha Dubois. Hopefully your fix corrects the issue when it's deployed, but I'm leaving this here while it's still fresh on my mind just in case.
[auto_after_end18.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3998553/auto_after_end18.zip)
[auto_after_end20.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3998554/auto_after_end20.zip)

**Comment by davidpwbrown** [comment]
The "fix" wont fix already-haywire NPCs, it will stop it happening in future.

And yes, thanks, that is definitely a potential cause - creating a new character in same world who dies.

Because there was another issue, where NPCs from a previous character were followers of the new character, so what I did was clear NPC follower status when character dies, this would then mean when you go back to your original character, they no longer have any followers, because there is only one player faction in the game, and this can cause all kinds of NPC weirdness with multiple characters in same world.

Theres no easy fix to that for the moment, other than not having multiple characters in the same world, ultimately we would want the player faction to be unique to each character, but that would involve rewriting a LOT of faction code.

**Comment by Solusphere** [comment]
Ok, thanks. Note to self: Always make a separate world for test characters.

**Comment by logros13** [comment]
@ZhilkinSerg Just had what appears to be this issue happen on a new game in the current experimental. Npc suddenly ran away from my faction camp and would not follow orders despite still acting like they where in my faction when spoken to. 

trying to loot her body after she got her head caved in by a hulk resulted in a warning that doing so would be stealing from "no faction" indicating she was no longer part of my faction despite the dialogue indicating she was. On a semi-related note is stealing from the "no faction" faction supposed to be a thing or is this another bug?

os: win 10
version: aa126fe (tiles)
Mods:
[
  "dda",
  "no_npc_food",
  "package_bionic_professions",
  "blazeindustries",
  "No_Rail_Stations",
  "StatsThroughSkills",
  "speedydex"
]

**Comment by JantDarvus** [comment]
I can confirm this bug is still present. I've just, uh, liquidated a camp in frustration on realising that I can't get any of the camp followers to follow me, they all have the 'is not friendly!' message if I try to sort their armour, and debug showed them as 'no faction'. I have at no point told anyone to go their own way.

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 7ddf235 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by JantDarvus** [comment]
As an extra note, a simple way to solve this on-demand would presumably be if changing NPC faction was possible via the debug menu. Unless I've missed it, which I may have, you cannot do this but being able to just set them back to the 'your_followers' faction would presumably undo the problem.

**Comment by LeahLuong** [comment]
@JantDarvus You should prob make the faction debug option a formal feature request.

Jant didn't say it but I will: this issue should prob be reopened if the issue is still present & reproducible.

**Comment by JantDarvus** [comment]
@LeahLuong ah, I hadn't even realised it was closed. I just came across this when I went looking for any clue about what was going on. And good idea, I'll put in a request.

**Comment by Maleclypse** [comment]
It won't be reopened if the problem is caused by save-scumming.  It would need to be happening from some other chain of events.

**Comment by LeahLuong** [comment]
@Maleclypse I understand the sentiment when it comes to savescummers. That said, this is kind of a gamebreaking issue if it does come up in the future w/out a debug fix. There have been recent issues where the game is holding onto info it prob shouldn't; portal storms duration carrying across game worlds & problems w/ remaking chars in an ongoing world are some examples that come to mind. Perhaps this issue warrants more investigation. I won't be looking into but I'll keep my fingers crossed it doesn't crop up again. Hopes & prayers & all that rot.
