### ISSUE TITLE
Dont drop the UPS!

### ISSUE THREAD

**Issue by Zupercharged** [CleverRaven/Cataclysm-DDA#36395]
**Is your feature request related to a problem? Please describe.**  
There is no way to prevent your character from dropping their UPS when you drop your bag, in fact it seems to be one of the first items the game chooses to dump. 

This is a problem because whenever I drop my bag it is because I am facing imminent combat, so dropping the ammunition for my ranged weapon system is understandably the last thing I want to do, and has actually gotten me killed on multiple occasions as I could not retrieve it in time to engage enemies that are best engaged from afar (shockers, zappers, hulks, brutes, bio-weapons (Cat++), bio operators (Cat++), etc.) mid way through a melee.

**Describe the solution you'd like**  
The easiest solution I can think of is to make large magazine pouches accept carrying the UPS, this solution already works for conventional magazines so it shouldn't be too much of a stretch.

**Describe alternatives you've considered**  

- Make UPS cases compatible with the Shoulder strap gun mod. In this way the UPS can be easily modified to be worn so it cannot be dropped with the bag.
- Make a new clothing piece similar to the jerrypack which results in an article of clothing that acts like a UPS.
- Make it so favourited items are last to be dropped.

**Additional context**  
I somehow find it hard to believe no one has had this problem before, but I cannot find any existing issues on it nor any existing solutions in game.

**Comment by Ezsk** [comment]
I do not like OP things but I love idea of wearable UPS that contained in Aftershock.

**Comment by Soup-de-Loop** [comment]
As mentioned, the UPS is wearable in Aftershock- on the legs. A belt-mounted UPS might be cool, perhaps a chest strapped one, or as you say, a backpack one? Of course, the default answer is that there's a CBM/bionic that technically fills the niche of an "undroppable UPS".

**Comment by 1n17** [comment]
> Make it so favourited items are last to be dropped.

Would be my go to for this one, not that I'm opposed to (concurrent) wearable solution. Which reminds me that favorite flag is severely underutilized, iirc it only prevents dropping items with move all advanced inventory command, would be nice if it also stopped items from being consumed by crafting and accidentally disassembled.

**Comment by Marrim** [comment]
I vaguely remember suggesting the wearable UPS variants (backpack, belt etc). Have they been implemented in Aftershock? Why not in mainline?

**Comment by kevingranade** [comment]
When you drop a bag, also select a number of other items sufficient to prevent your inventory from overflowing.
