### ISSUE TITLE
Mechs left in vehicles sometimes disappear 

### ISSUE THREAD

**Issue by 1n17** [CleverRaven/Cataclysm-DDA#36398]
# Describe the bug
Pretty much as in title, I haven't done extensive testing on this but it did happen at least three times now, all in very similar circumstances.

# Steps To Reproduce
Now, I haven't figured out exact conditions but it goes something like this:

Find a Mech, swipe milid card and happily ride it out to your vehicle.
Swap places to force it on passenger seat for ease of transportation to the main base.
Walk away and do something else for a while - couple overmap tiles should be enough.
Come back to your vehicle and likely be very puzzled about the Mech's mysterious disappearance despite no signs of malfeasance of any kind.

# Expected behavior
Mechs not evaporating when left in vehicles.

# Screenshots

# Versions and configuration
0.C-47743-g38a3cdcc88
# Additional context

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
