### ISSUE TITLE
Insecticide / Lye ingredient typo

### ISSUE THREAD

**Issue by Zourin2** [CleverRaven/Cataclysm-DDA#36396]
**Problem:**

1 base 'dose' of Insecticide (.25L) requires 50 Lye (12.5L) in order to be crafted, with no substitutions for this ingredient. This equates to a mandatory 25000 (43L)  wood ash. Aside from pathological arsonry, this amount of ash would require about 62 hours and 250 planks/sticks to craft manually, or less efficiently, throwing about 1000 planks into a pile and hope you get that amount of ash when it finishes burning sometime between next year and your next run.

All other crafts use Lye Powder (except Lye Powder itself), rather than Lye which is an intermediate ingredient. The recipe for Insecticide likely incorrectly uses Lye instead of Lye Powder.

Also, I would like to point out that the 3000:200 conversion of ash to Lye > Lye to Powder is a total PITA and a waste of ingame time and playtime. Just an obligate protest.
["Soap making is automatic"](https://www.motherearthnews.com/homesteading-and-livestock/how-to-make-soap-from-ashes-zmaz72jfzfre)

**Expectation**

Option 1: Replace the Lye (50) requirement with a much more sane Lye Powder (50) requirement and treat this as a typo..

Option 2: Allow reconstituting Lye Powder back into Lye, as Lye Powder via charcoal is a much more sane process. 

Option 3: [Lye Leaching Barrel](https://www.motherearthnews.com/homesteading-and-livestock/how-to-make-soap-from-ashes-zmaz72jfzfre) plus better efficiency on ash-to-lye) Allow us to automate the process and get on with with getting on.

**Comment by kevingranade** [comment]
Seems legit, if I'm reading the entries correctly one unit of lye is equivalent to ~33 units of lye powder, so probably something like ``[ [ "lye", 2 ], [ "lye_powder", 50 ] ]`` would be appropriate.

For reference, this is probably similar to the process outlined here
