### ISSUE TITLE
Game crashes when trying to clean water

### ISSUE THREAD

**Issue by fuchssohn** [CleverRaven/Cataclysm-DDA#36390]
# Describe the bug
When I try to clean water in a brazier inside the evac shelter the game closes itself with an error

# Steps To Reproduce

1. Activate a brazier inside the evac shelter, load it with wood and light it.
2. With the water on the inventory, search for clean water in the crafting menu
3. When the player hit the confirmation on the menu the game crashes.

# Expected behavior

It is expected that the water should be clean without the crash.

# Screenshots

![Glen 'Ninja' Mansfield _2019-12-23_23-30-47_+0000](https://user-images.githubusercontent.com/7224151/71384975-4550e000-25c3-11ea-8ee9-67857491ba8c.png)

# Versions and configuration

 - OS: Linux Fedora 31 KDE
 - Game Version: 0.D
 - Graphics version: MX (any) and/or Chesthole16
 - Mods loaded: dda, disable npc needs, medieval and historic classes, classic zombies, stats through skills

# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3996602/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3996603/debug.log)
[save_file_crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3996606/save_file_crash.zip)

<!-- Crash: if your problem refers to a crash, please add the following files to the "Additional Context" paragraph:
    - From the /config folder (you can zip them both together):
        - crash.log file.
        - debug.log file.
    - Your save file (zipped)

**Comment by davidpwbrown** [comment]
crash log seems to suggest problem with the fire / burning rather than the crafting, and when Iload the save and craft clean water, i dont get a crash.

**Comment by fuchssohn** [comment]
I used splintered wood on the fire, and am playing the game in a window. I tried all sorts of tiles and no luck. Even in an earlier save that I don't have anymore I got the same crash.

**Comment by ZhilkinSerg** [comment]
Do you also get the error in latest experimental or only in stable 0.D?

**Comment by AMurkin** [comment]
Looking at the sidebar on the screenshot, that's not stable 0.D.

**Comment by fuchssohn** [comment]
> Do you also get the error in latest experimental or only in stable 0.D?

No, when I tested in #10070 it didn't crash. I assume that's on the 0.D that I have avaliable from the repository to install. The #10070 I grabbed from the website.

**Comment by hexagonrecursion** [comment]
This bug was likely fixed in https://github.com/CleverRaven/Cataclysm-DDA/pull/36471.

**Comment by Night-Pryanik** [comment]
Closing until reconfirmed.
