### ISSUE TITLE
Some furniture can't store items (volume 0,0L)

### ISSUE THREAD

**Issue by cozardi** [CleverRaven/Cataclysm-DDA#36407]
# Describe the bug

Tables, desks, crates, beds,  can't store things on them (anything placed there "overflows" to a nearby tile, as if full), their storage volume appears as 0,0L in the advanced inventory. Bookcases and dressers do have storage volume and are able to hold things. Not sure about any other furniture. Furniture can still hold previously placed items (i've just run into this bug after I updated to the latest version)

# Steps To Reproduce

1. Load attached save
2. Try to store things or use the advanced inventory in the nearby crate, table, chair, etc. Note how some of them still hold items.

# Expected behavior

You can place items (if not a lot of them) on furniture, to go for that comfy home base look.

# Versions and configuration

- OS: Windows 
    - OS Version: 10.0 1903
- Game Version: 0.D-10660-g5f963d1 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Hydroponics [hydroponics],
    Folding Parts pack [deoxymod],
    [DP_MOD] Indicators: Xotto [DP_XOTTO_INDICATORS],
    sees-player icon, retrodays [sees_player_retro]
]

# Additional context

I just want to tidy up my base :(

[Clementson.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3998640/Clementson.zip)

**Comment by KorGgenT** [comment]
my first suspsicion is that this was introduced in #36354
AFAIK, the fix would be adding json storage values to the offending furniture
