### ISSUE TITLE
Can't mine upward with items lying on downstair

### ISSUE THREAD

**Issue by FeepingCreature** [CleverRaven/Cataclysm-DDA#36405]
# Describe the bug

Can't construct with items lying on a down staircase.

# Steps To Reproduce

1. Have tools and items necessary to build up staircase in rock

2. Be standing on a down staircase dug up from a lower level

3. Have required resources dropped at your feet

4. Try to mine Upstair.

# Expected behavior

Items should fulfill construction attempt.

# Screenshots

![cdda bug](https://user-images.githubusercontent.com/540727/71414231-37986a80-2656-11ea-8996-627340dc0858.png)

# Versions and configuration

Version: 572b78f982669c758df1d7137b56c4d00a5f7010 stock

# Additional Context

Just noticed: merely mining out and standing in a free space is enough to fix it, the items can be on the staircase, you just can't be also standing on them.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-6416.
