### ISSUE TITLE
Monsters teleport through floors

### ISSUE THREAD

**Issue by ymber** [CleverRaven/Cataclysm-DDA#36403]
# Describe the bug
Monsters teleport through the ground onto the surface from a lab beneath. Presumably this is a general behavior between any two z levels.

# Steps To Reproduce
Steps to reproduce the behavior in the attached save:
1. Wait 5 minutes

# Expected behavior
Fungaloids don't teleport through the ground.

# Versions and configuration
- OS: Linux
    - OS Version: Kernel 5.4.5
- Game Version: 0.D-10649-g82cb0bf [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fictional Guns [no_rivtech_guns],
    No Flaming Weapons [no_flaming_weapons],
    No Rail Stations [No_Rail_Stations]
]

# Additional context
[Onyx.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3998257/Onyx.zip)

**Comment by esotericist** [comment]
I was able to confirm this on master using `5` to wait the long way, having a zombie scientist appear next to the character (so it isn't the extant safe mode notification issue).

**Comment by 1n17** [comment]
Indeed, spawning clairvoyance artifact and teleporting around gave me some idea on what is going on (related #36346) -  It seems that when monsters enter (possibly also teleport trap) a portal they appear on player current z level, it stands to reason it is the same case for portals that are spawning monsters

**Comment by KorGgenT** [comment]
a portal you say... if it's only portals, how much of a bug is this/ what do we want the limit of a portal to be?

**Comment by kevingranade** [comment]
A quick glance at the teleport code indicates that random teleports are using map calls with 2D functions, which implicitly target the level the player is on.

**Comment by kevingranade** [comment]
No I'm mistaken, it uses the 3D map functions, but never initializes the z component of the tripoint.
