### ISSUE TITLE
Hauling items through different floors dont work if the world is created with z-levels off.

### ISSUE THREAD

**Issue by Aphegis** [CleverRaven/Cataclysm-DDA#36419]
# Describe the bug

"Hauling" feature doesn't move items through different floors if the world is created with z-levels off.
When you try to use a stairs (both up and down) the log says "you stop hauling the items" and the items stay at the original floor.

# Steps To Reproduce

1. Create a world with no mods and disable z-levels
2. Try to haul items through stairs and fail.

# Versions and configuration

 - Game Version: 0.D-10610-g8761541 (tiles)
 - Mods loaded: None

# Additional context

If you try to turn z-levels on after the worls is created, the problem remains, and if you teleport to a different overmap using the debug menu, you still can't haul items through different floors.

**Comment by kevingranade** [comment]
Does the issue persist forever on a world created with the z-level option off, or does it just require a game restart for the z-level option to take effect, as it usually does?

**Comment by Aphegis** [comment]
Yes, the player is able to haul items through floors after a game restart with the z-levels turned on. I did not knew this.
I created this issue because i thought that the hauling system [through different floors] were coded to work even with z-levels off, it's in my opinion one of the biggest quality of life improvements from this last year and in an ideal world it should work for everyone. 
But if it's not viable/possible to make it work with z-levels off [without having to go the main menu and reload the world], let me know so i can close this issue!

**Comment by davidpwbrown** [comment]
It was always a limitation of the system that hauling across z-levels wasnt going to work with z-levels disabled, I dont know what it would entail to make it work, I dont think itd be too difficult, but in terms of this issue, its not a bug, more of a feature request.

**Comment by kevingranade** [comment]
Yes this is working as expected, our focus is on making the z-level option stable enough to make it mandatory.
