### ISSUE TITLE
Mono blade tumbles from you hand. {Softlock}

### ISSUE THREAD

**Issue by RiPCorD5A1** [CleverRaven/Cataclysm-DDA#36421]
# Describe the bug

The Mono blade cbm was knocked from my hand. But i can reactivate the cmb to get another blade.

# Steps To Reproduce

Here's what happened, haven't tried to replicate.

1. Activate mono blade
2. Be in extreme pain, have a broken limb, have super low health.
3. Have a skeletal Juggernaut punt you.
  
# Expected behavior

Well if the blade being removed is expected then i expect to lose the cbm.

# Screenshots

![More Power](https://user-images.githubusercontent.com/59139849/71428134-76ddb000-2684-11ea-8b9e-e5948c517983.png)

# Versions and configuration

19:36:56.928 :  GAME REPORT:
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-10668-gf005f00 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    Disable Mutagens [no_mutagen],
    Disable Religious Texts [no_religious_Texts],
    No Explosive Zombies [No_Explosive_Zombies],
    No Acid Zombies [No_Acid_Zombies],
    Fuji's Military Profession Pack [fuji_mpp],
    Prevent Zombie Revivication [no_reviving_zombies],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills]
]

Also i just picked up the blade and now i cant drop it.

And because im an idiot i equipped the blade and now i cant unequip it.

![weeeeee](https://user-images.githubusercontent.com/59139849/71428474-9249ba80-2686-11ea-84a2-f50986135293.png)

**Comment by kevingranade** [comment]
Looks like the code in apply_damage that makes you drop your weapon when your arm is brought to 0 HP doesn't check for special unwieldable items.
