### ISSUE TITLE
Chickens lay too few eggs

### ISSUE THREAD

**Issue by Ker-Nes** [CleverRaven/Cataclysm-DDA#36426]
**Is your feature request related to a problem? Please describe.**  
Currently, while I'm unsure of the exact value, tame chickens seem to be laying perhaps one or two eggs a week. Not only this makes them essentially useless in terms of getting an egg production going, it's also unrealistic.

Admittedly it might have more to do with how chicken eggs (and manure) are spawned, since they only seem to spawn when the animals are not in my reality bubble, but I have no idea of how that particular bit of code is handled. 

**Describe the solution you'd like**  
It would be nice to see them at least producing eggs in the same rate as real life, about one per day (or more precisely, one per around 26 hours), with an yearly break of about half a season for molting.

**Describe alternatives you've considered**  
There is the issue that older chickens do lay less eggs, which is to say that it might be a good idea to average less than the optimum number of eggs. I would perhaps say that one every 36 hours or so might be a good option in this case, while still being a significant increase in what I feel might be the game's current laying rate.

**Additional context**  
https://poultry.extension.org/articles/poultry-management/raising-chickens-for-egg-production/
https://www.thehappychickencoop.com/when-will-my-chicken-start-laying-eggs/
https://www.purinamills.com/chicken-feed/education/detail/how-long-do-chickens-lay-eggs-goals-for-laying-hens

**Comment by Zourin2** [comment]
In a slight tangent to this.. there's always been a the issue of feeding animals.

I think the best short term solution would be to make animals function a bit like the smoking rack or charcoal kiln. Put food in, wait a while, get egg/milk (for cow), repeat. Its not hard to get an ungodly amount of seeds for bird feed, but really nothing to do with it if you're not expanding the farm.  Having them 'take winter off' puts an extra twist on the 'food is tough' season. 

A tougher approach would be allowing persistent production as long as a 'feeding trough' is nearby and stocked with food, similar to basecamp food supplies but for animals. TBH, chickens are pretty good foragers on their own, and can pretty much be content with a big ol' compost pile for bug-food and warmth.

**Comment by Ker-Nes** [comment]
> 
> 
> In a slight tangent to this.. there's always been a the issue of feeding animals.
> 
> I think the best short term solution would be to make animals function a bit like the smoking rack or charcoal kiln. Put food in, wait a while, get egg/milk (for cow), repeat. Its not hard to get an ungodly amount of seeds for bird feed, but really nothing to do with it if you're not expanding the farm. Having them 'take winter off' puts an extra twist on the 'food is tough' season.
> 
> A tougher approach would be allowing persistent production as long as a 'feeding trough' is nearby and stocked with food, similar to basecamp food supplies but for animals. TBH, chickens are pretty good foragers on their own, and can pretty much be content with a big ol' compost pile for bug-food and warmth.

While not a bad idea in itself, we need to also consider that realistically the animals would be allowed to forage for a lot of their food given the general circumstances in the post apocalypse, even if the player might not quite do the same for gameplay reasons (that is, framerate, there not being many mechanisms to actually herd the animals when it comes time to deal with them, or them coming back to a specific place every so often, such as a coop, etc. ), so their food requirements need to be in line with them not needing to be wholly fed from the appropriate feed.

**Comment by Ker-Nes** [comment]
> 
> 
> In a slight tangent to this.. there's always been a the issue of feeding animals.
> 
> I think the best short term solution would be to make animals function a bit like the smoking rack or charcoal kiln. Put food in, wait a while, get egg/milk (for cow), repeat. Its not hard to get an ungodly amount of seeds for bird feed, but really nothing to do with it if you're not expanding the farm. Having them 'take winter off' puts an extra twist on the 'food is tough' season.
> 
> A tougher approach would be allowing persistent production as long as a 'feeding trough' is nearby and stocked with food, similar to basecamp food supplies but for animals. TBH, chickens are pretty good foragers on their own, and can pretty much be content with a big ol' compost pile for bug-food and warmth.

While not a bad idea in itself, we need to also consider that realistically the animals would be allowed to forage for a lot of their food given the general circumstances in the post apocalypse, even if the player might not quite do the same for gameplay reasons (that is, framerate, there not being many mechanisms to actually herd the animals when it comes time to deal with them, or them coming back to a specific place every so often, such as a coop, etc. ), so their food requirements need to be in line with them not needing to be wholly fed from the appropriate feed.

**Comment by yowshi** [comment]
> While not a bad idea in itself, we need to also consider that realistically the animals would be allowed to forage for a lot of their food given the general circumstances in the post apocalypse, even if the player might not quite do the same for gameplay reasons (that is, framerate, there not being many mechanisms to actually herd the animals when it comes time to deal with them, or them coming back to a specific place every so often, such as a coop, etc. ), so their food requirements need to be in line with them not needing to be wholly fed from the appropriate feed.

That assumes you keep then in an area with grass and such. i keep my animals inside a fema shelter there's nothing to forage inside.

**Comment by Aphegis** [comment]
This is probably part of the farming long term project. (Or should be)
https://github.com/CleverRaven/Cataclysm-DDA/projects/11
