### ISSUE TITLE
Spawn rates lower than the default can make Clear Back Bay impossible

### ISSUE THREAD

**Issue by Kodiologist** [CleverRaven/Cataclysm-DDA#36422]
# Describe the bug

It seems that you need to kill a particular monster, a named zombie, in order to complete the Clear Back Bay mission, but if the spawn rate is below 1, the monster may not spawn, so the quest becomes impossible to complete.

# Steps To Reproduce

1. Create a world with spawn rate 0.10.
2. Teleport to the refugee center.
3. Get the quest.
4. Kill all the zombies in the back bay. In general, the named zombie won't be there.
5. Observe that the quest-giver doesn't think the quest is done.

# Expected behavior

One of:

1. The game should force the named zombie to spawn.
2. The quest-giver should be satisfied with killing the zombies that do spawn.
3. If the named zombie is never spawned, the quest shouldn't be offered in the first place.

**Comment by Hirmuolio** [comment]
The mapgen code for spawning one monster seems to have two separate ways to not spawn any monsters and the earlier one is getting triggered here.

mapgen.cpp line 1207

```
if( !x_in_y( odds_after_density, 100 ) ) {
    return;
}`
```

The number of monsters to spawn is decided later and can again making this x_in_y check redundant.

The x_in_y check should probably be just removed.
