### ISSUE TITLE
Warmth indicators in armor menu are always in F?

### ISSUE THREAD

**Issue by glenmack** [CleverRaven/Cataclysm-DDA#36448]
### Expected behavior

Warmth indicators should be relevant to interface temps.

### Actual behavior

Warmth indicators do not change numeric value, regardless of interface selection.

### Steps to reproduce the behavior

Open armor menu, read warmth values, change interface, read warmth values.

**Comment by Night-Pryanik** [comment]
You mean these values?
![изображение](https://user-images.githubusercontent.com/11132525/74006681-e211e600-4995-11ea-998b-4ded3a2a38cd.png)

That's not a bug. The values here are not in Fahrenheit or Celsius or Kelvin. These are abstracted relative values.
