### ISSUE TITLE
Crafting with table drops item on floor

### ISSUE THREAD

**Issue by BenlyAZ** [CleverRaven/Cataclysm-DDA#36457]
While crafting (at least at a vehicle workbench or a desk), the in-progress item will be placed on the workbench, but when completed it's dropped at the player's feet. This is mostly just an oddity, but in vehicles it has the mildly annoying effect that the item doesn't necessarily end up in an item-containing spot and will be left on the ground unless the player moves it into a storage space manually.

# Steps To Reproduce

1. Get a rock, a hammer, and a desk.
2. Craft pebbles.
3. The pebbles are on the floor. 

# Expected behavior

Since the item is on the table during crafting, I would expect it to stay there when completed rather than falling on the ground.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.D-10692-gb7329f6 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    DinoMod [DinoMod],
    EZ-Mode Medical [fast_healing],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks],
    Classes and Scenarios Mod [more_classes_scenarios],
    Safe Autodoc [safeautodoc],
    Prevent Zombie Revivication [no_reviving_zombies],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Mining Mod [Mining_Mod],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Simplified Nutrition [novitamins],
    No Fungal Monsters [No_Fungi],
    No Rail Stations [No_Rail_Stations],
    No Fictional Guns [no_rivtech_guns],
    No Sci-Fi Equipment [no_scifi],
    Gun Cotton [guncotton],
    No Explosive Zombies [No_Explosive_Zombies]
]

**Comment by davidpwbrown** [comment]
Yeah ive noticed this, may be due to changes in https://github.com/CleverRaven/Cataclysm-DDA/pull/36230
