### ISSUE TITLE
Pigs should be able to eat (and make it dissapear from the game world) almost anything

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [CleverRaven/Cataclysm-DDA#36466]
How do you get rid of a corpse?

It's simple: Ditch it in a pig pen. They will eat almost anything. No corpse, no murder, no charge. So, in terms of the game world:

Have a few pigs and a pig pen, and drop rotten food, whole corpses, butchery remains on the tiles, and the pigs will slowly devour them.

As a bonus: Mutant stuff will make pigs mutate to mutant pigs that'll have a chance to go bananas and possibly kill the player. Mutant pigs....!

**Comment by Fris0uman** [comment]
This is a pretty useless use case, but making monster able to consume specific stuff would be nice.
Currently I think only giant amoeba has that ability.

**Comment by Unrepentant-Atheist** [comment]
Then how do you get rid of all the rotten stuff laying around in the world? It just piles up and up and up and doesn't get removed. Especially all these bones. I'm one of these who like to have it tidy near me base.

**Comment by Fris0uman** [comment]
Burn it, or leave it be because rotten stuff disapear eventually.

**Comment by Zireael07** [comment]
I wouldn't say it's a useless use case per se, while a bit rare, we already have animals and rotting stuff, so having pigs eat it (and bones, those don't rot and pile up) makes perfect sense from an immersive game viewpoint.
