### ISSUE TITLE
NPC Beggar Doesn't Take MREs

### ISSUE THREAD

**Issue by Oakeave** [CleverRaven/Cataclysm-DDA#36460]
Game version:
0.D-10692-gb7329f6

Operating system:
Windows 10

Tiles or curses:
UNDEAD_PEOPLE

Mods active:
Disable NPC Needs
More Survival Tools
Garden Pots
Makeshift Items Mod
Modular Turrets
Salvaged Robots
Mutant NPCs
Hydroponics
More Locations
Folding Parts pack
Vehicle Additions pack
No Survivor Armor
Bionic Slots
Classes and Scenarios Mod
Medieval and Historic Classes and Shields
Mythological Replicas
Tanks and Other Vehicles
Roadheader and other mining vehicles

### Expected behavior
When you give the beggar the MRE, he should accept it and the MRE should disappear from your inventory.
### Actual behavior
The beggars acts like he took the MRE, but the MRE is still inside your inventory.
### Steps to reproduce the behavior
1. Talk to NPC
2. Offer food
3. Offer your MRE

**Comment by Ezsk** [comment]
meals rejected by everyone.
that's right.

**Comment by wapcaplet** [comment]
Cannot reproduce. I brought several MREs to the lobby of the refugee center, and offered them to the beggars - they were accepted, and the MREs disappeared from my inventory. Using debug mind control to trade with the NPCs, I confirmed that the MREs were in their inventory.

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-5147-ge23fd18712 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
