### ISSUE TITLE
NPCs try to heal you with rags

### ISSUE THREAD

**Issue by Feuerhai** [CleverRaven/Cataclysm-DDA#36463]
# Describe the bug

If you're hurt NPCs will try to heal you with rags, which won't help, turns the rag into a blood soaked rag and throws an error.

# Steps To Reproduce

1. Get hurt.
2. Get a NPC follower.
3. Give him a rag.
4. Wait for him to try and heal you with it.

# Expected behavior

NPCs will only try to heal you with rags when you're bleeding, so it can actually help and they won't unnecessarily use up ressources.

# Versions and configuration

- OS: Windows 10
    - OS Version: 10.0 1903
- Game Version: 0.D-10709-gd18fc5d [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

 DEBUG    : Tried to consume charges for non-tool, non-food, non-med item

 FUNCTION : bool Character::consume_charges(item&, int)
 FILE     : src/character.cpp
 LINE     : 5480

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4002379/debug.log)

**Comment by Ramza13** [comment]
Just tried but could not reproduce this.

**Comment by Feuerhai** [comment]
Just tried it myself on latest again, seems to be fixed
