### ISSUE TITLE
Diminishing morale bonuses from food applies to alcohol

### ISSUE THREAD

**Issue by shadowsapex** [CleverRaven/Cataclysm-DDA#36482]
# Describe the bug

An alcohol drink's morale buff decreases as you drink the same one too often, like food.

# Expected behavior

For alcohol to have an exception like junk food. You don't exactly drink alcohol for its taste

# Versions and configuration

 - OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
 - Game Version: [from the main menu, e.g. 0.C-29938-g90f5268437]
 - Graphics version: [Tiles or Terminal]
 - Mods loaded: [e.g.dda, boats, hacktheplanet, StatsThroughSkills]

# Additional context

**Comment by kevingranade** [comment]
I seriously don't see a problem here, frequent consumption of alcohol (and particularly the *same* alcohol) doesn't strike me as a great strategy for maintaining high levels of morale.
