### ISSUE TITLE
Stockpile Zone Improvements

### ISSUE THREAD

**Issue by Zourin2** [CleverRaven/Cataclysm-DDA#36485]
Zones are great, but there are a few redundancies that I think could be ironed out.

1. Storage zones should be 'no auto-pickup' by default. Why would I put something down for the express purpose of picking it right back up? "no auto-pickup" can be changed to a much less needed "enable auto-pickup" for whatever fringe situation you can think of.

2. Storage sorting zones should be "unsorted" by default. This hits on an issue with stockpile zones that sort items in containers. Once the container is empty, it requires an 'unsorted' zone to move the empty container elsewhere (such as to a Container zone).  The "unsorted" zone is still useful for drop-offs and cleanups, and any tiles that you don't want your housekeeper touching can use the "Ignore" zone. 

3. F.Clothing should include filthy textiles and items such as filthy threads, rags, kevlar, etc. Alternatively, replace F.Clothing and F.Armor with just a "Filthy Items" zone option. This is a common sense alternative to simply creating a custom zone set to "Filthy", which renders both F.Clothing and F.Armor obsolete. This doesn't quite fix the problems with trying to load washing machines during automated housekeeping, but at least there won't be tons of unusable leather parked in the very busy "Spare parts" section.

4. Storage zones should be "No NPC Pickup" by default until the kleptos can be kept from pocketing all your milkballs and scrap electronics. Ideally, they should only freely grab items from stockpiles to fulfil *needs*, such as food, drink, meds, task tools, or ammo to refill magazines/pouches/weapons. Until then, there's no reason why followers should be permitted to touch your tender stockpile of cellphones and vibrators. Bonus points if Followers actually used these zones to unload their pockets after a town run.

**Comment by Little-119** [comment]
To add to this, I'd like an option for perishable food zones that filters items based on their shelf life/how long they have until they rot. That way I can use the limited space inside minifridges/minifreezers for things that actually need to be cold/frozen instead of a bunch of junk food that'll expire long after I've died to my own mid-late game hubris.

**Comment by Zourin2** [comment]
I agree. It's annoying to group things like milk next to the flour and dehydrated/smoked meat.
