### ISSUE TITLE
SIGSEGV when pressing s while aiming a reach weapon

### ISSUE THREAD

**Issue by dsmky117** [CleverRaven/Cataclysm-DDA#36499]
# Describe the bug

A segmentation fault occurs when you press the 's' key while aiming a reach weapon.

# Steps To Reproduce
1. Give yourself a reach weapon (I tested a steel spear, lucerne hammer, pike).
2. Press 'f'.
3. Press 's'. The game will crash.

# Expected behavior
No crash.

# Versions and configuration
- OS: Windows 10.0 1903
- Game Version: 0.D-10735-gd136e46 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4006733/config.zip)

**Comment by ZhilkinSerg** [comment]
Looks like something that was not fixed in #35132.
