### ISSUE TITLE
Bridge over open "air" tiles

### ISSUE THREAD

**Issue by RafeHaab** [CleverRaven/Cataclysm-DDA#36496]
**Is your feature request related to a problem? Please describe.**  
Build bridges over open-air tiles

**Describe the solution you'd like**  
Add a construction recipe for this kind of bridge

**Describe alternatives you've considered**  
Nothing, it's too hot to think.

**Additional context**  
Code here for anyone who wants to think outside the box in my place:

  {
    "type": "construction",
    "description": "Build Log Bridge",
    "//": "Step 1: half of a log bridge",
    "category": "CONSTRUCT",
    "required_skills": [ [ "fabrication", 4 ] ],
    "time": "60 m",
    "qualities": [ [ { "id": "SAW_W", "level": 2 } ] ],
    "components": [ [ [ "log", 2 ], [ "wood_beam", 2 ] ], [ [ "stick_long", 4 ], [ "2x4", 6 ] ] ], 
    "pre_terrain": "t_open_air",
    "post_terrain": "t_bridge_air_half"
  },
  {
    "type": "construction",
    "description": "Build Log Bridge",
    "//": "Step 2: Finish the log bridge",
    "category": "CONSTRUCT",
    "required_skills": [ [ "fabrication", 4 ] ],
    "time": "60 m",
    "qualities": [ [ { "id": "HAMMER", "level": 2 }, { "id": "SAW_W", "level": 2 } ] ],
    "components": [ [ [ "wood_panel", 2 ] ], [ [ "stick", 12 ], [ "2x4", 6 ] ] ], [ [ "rope_6", 4 ], [ "rope_makeshift_6", 6 ], [ "nail", 24 ] ],
    "pre_terrain": "t_bridge_air_half",
    "post_terrain": "t_bridge_air"
  },

**Comment by scorpion451** [comment]
A metal grate option like some of the existing generated structures have for catwalks and fire escapes would be nice too.

**Comment by RafeHaab** [comment]
Metal grates sound good, let me look into it.

**Comment by RafeHaab** [comment]
Opened pull issue.
