### ISSUE TITLE
Flamethrower fuel cannot be fired from an aux flamethrower as its range is zero

### ISSUE THREAD

**Issue by Jordanb716** [CleverRaven/Cataclysm-DDA#36498]
# Describe the bug
As "flamethrower fuel" has a range of zero, if it's loaded into an aux flamethrower it cannot be fired at all. Napalm can be fired.

# Steps To Reproduce
1. Attach aux flamethrower to gun (in my case a KSG).
2. Load with flamethrower fuel in a small pressurized fuel tank.
3. Attempt to fire it.

# Expected behavior
I would expect to be able to fire flamethrower fuel out of a flamethrower at at least a tiny range.
This Forgotten Weapons video gives approximate ranges for liquid and gelled fuels (20 and 40 yards respectively) from a WW2 M2 Flamethrower, Maybe give the fuels those ranges and give the aux flamethrower some penalty to reflect its smaller size?
https://youtu.be/aPQYK5ZMbWY?t=157

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-10735-gd136e46 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bens GF recipes [Tolerate_This],
    Garden Pots [growable-pots],
    Alternative Map Key [alt_map_key],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Beta National Guard Camp [national_guard_camp],
    No Fungal Monsters [No_Fungi],
    Manual Bionic Installation [manualbionicinstall],
    Safe Autodoc [safeautodoc],
    Sleep Deprivation [sleepdeprivation],
    Stats Through Kills [stats_through_kills]
]

**Comment by Brian-Otten** [comment]
There is another issue open on this for grenade launchers, i suspect this might be the same, in  that you need launcher skill @ 2 for the range to be above zero.

**Comment by Jordanb716** [comment]
Seems weird to have skill determine maximum range and not just accuracy at long range.
