### ISSUE TITLE
Item compare able to cause game crash when searching

### ISSUE THREAD

**Issue by molotoveVGC** [CleverRaven/Cataclysm-DDA#36494]
# Describe the bug

Comparing items while using the item search function may cause a game crash with a segfault. In some instances, it does not crash, but compares an item to itself. Recreated in latest experimental on a new world with a new character.

# Steps To Reproduce

1. Have two comparable items. It does not matter in or out of inventory
2. (I)tem compare one item, and use (/) to search for the second item.
3. On selection of the second item, crash.  Occasionally, the second item will be compared to itself, instead of the first item.

# Expected behavior

Item 1 and Item 2 to be compared side by side.

# Versions and configuration

 GAME REPORT:
- OS: Linux (ChromeOS Linux Beta)
    - OS Version: Linux penguin 4.19.86-07780-g3c6544b539b7 aarch64 GNU/Linux
- Game Version: 0.D-10735-gd136e46425-dirty [64-bit]
- Graphics Version: Curses
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
First seen on Version: 0.D-9671-gdf0e590144

# Additional context

[world.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4006257/world.zip)
[logs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4006258/logs.zip)

I'm wiilling to recompile to test fixes on Linux, but am probably unable to access another OS at this time.

Initially reported this as just weapons (included save uses a cudgel and spear), but appears it I can reproduce it with pliers and bolt cutters as well.

**Comment by molotoveVGC** [comment]
This behavior seems similar to #34046 and may be fixed by #36606.

**Comment by ymber** [comment]
Can you still reproduce the behavior #36606 merged?

**Comment by molotoveVGC** [comment]
I've recompiled to a version containing 36606 and it appears resolved. I'm not able to reproduce the crash or the misleading UI behavior at all.
