### ISSUE TITLE
Strange issue with counterattacks causing massive damage to player's arm

### ISSUE THREAD

**Issue by Kelenius** [CleverRaven/Cataclysm-DDA#36517]
# Describe the bug

Being attacked by a monster while wielding a large item and counterattacking breaks your arm.

# Steps To Reproduce

1. Be a survivor with high skills, capable of counterattacking.
2. Hold a large item (I encountered this issue with rotary evapourator).
3. Stand next to a monster (giant cockroach in my case) and get attacked until you counter.

# Expected behavior

?????

# Screenshots

![изображение](https://user-images.githubusercontent.com/6681708/71549121-35713b80-29c9-11ea-8d5f-d3a7cdbfa5e7.png)
![изображение](https://user-images.githubusercontent.com/6681708/71549124-4e79ec80-29c9-11ea-91d0-2540ae94296e.png)
![изображение](https://user-images.githubusercontent.com/6681708/71549132-6c475180-29c9-11ea-9fae-81b59602dca6.png)
![изображение](https://user-images.githubusercontent.com/6681708/71549136-79fcd700-29c9-11ea-85d0-ac08e3370d3b.png)
(It doesn't happen every time, to these are different games)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-10735-gd136e46 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Vehicle Additions Pack [blazemod],
    Folding Parts pack [deoxymod],
    No Acid Zombies [No_Acid_Zombies],
    No Fungal Monsters [No_Fungi],
    Prevent Zombie Revivication [no_reviving_zombies]
]

# Additional context

[Franklinville.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4007424/Franklinville.zip)

I suspect that counterattacks somehow multiply damage by the time it takes to perform it, and because huge item = lots of time spent attacking, that translates into massive damage somehow, because I'm also dealing 300+ damage to the roach with one attack, way over what I should be capable of. Also, the messages say that the rotary evapourator shatters, which doesn't happen.

**Comment by kevingranade** [comment]
This is getting triggered by the item "shattering" since it's made of glass, and the damage scales with item volume.
https://github.com/CleverRaven/Cataclysm-DDA/blob/477661cd4534ec6f61cb82caba74a7f73c1cbf8a/src/melee.cpp#L1776
There is a secondary issue in that counterattacks shouldn't be triggering with such a large (and more importantly, slow) item.

**Comment by Soup-de-Loop** [comment]
This was an interesting one, I actually had it happen recently when trying to carry a rotary evapourator out of a Research Lab. Z got too close, had far more pain than I thought from such a small encounter and badaboom, right arm completely mangled and requiring a splint. Good to know why, now.
