### ISSUE TITLE
Migo structure is unmarked on overmap

### ISSUE THREAD

**Issue by ymber** [CleverRaven/Cataclysm-DDA#36511]
# Describe the bug
I ran into 15 migos in an open field that turned out to be from some kind of migo structure that wasn't marked on the overmap.

# Steps To Reproduce
Unknown. All other migo structures in this game are visible on the overmap.

# Expected behavior
Migo structures are marked on the overmap.

# Versions and configuration
- OS: Linux
    - OS Version: Kernel 5.4.6
- Game Version: 0.D-10768-g83bb1af18d [64-bit] - this is a custom build from master at f8ba267d1ce720998b863e7ac2f90a15003d5171 with #36235, #36377, #36438, and #36464 applied.
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations],
    No Fictional Guns [no_rivtech_guns],
    No Flaming Weapons [no_flaming_weapons]
]

**Comment by anothersimulacrum** [comment]
This is very likely one of the possible variants of the `mx_portal_in` map extra.

**Comment by 1n17** [comment]
That would generate special note on map tho (unless disabled), something might be afoot as on my end I've ran into several unmarked barns and single tile sized patches of forest appearing on map as field after recent pull..

**Comment by sztosz** [comment]
Those barns and small forests were added as some flavor to  just before X-Mass, it was this PR https://github.com/CleverRaven/Cataclysm-DDA/pull/35990 I believe. But they are really just to break the monotony of the grass, there is nothing really special with them, and so they are not being mark on the overmap.

**Comment by 1n17** [comment]
Ahh, I see. I suppose they are at least easier to spot than solitary trees when off-road driving but in turn require larger course corrections, and I'd still prefer to have them marked automatically.

**Comment by Night-Pryanik** [comment]
This mi-go structure isn't a separate overmap terrain, it's just a bunch of terrains and monsters spawned in the field, so it can't be marked like other locations.

I guess as a possible solution we could create a json-version of the structure and make it spawn on universal basis when the corresponding map extra triggers, but in any case that's definitely not a bug.

**Comment by ymber** [comment]
I think it should be removed as a map extra. The resin structure would be visible from a long distance and it's substantial enough to justify being its own OMT.
