### ISSUE TITLE
barefoot and already wearing footwear

### ISSUE THREAD

**Issue by Jerimee** [CleverRaven/Cataclysm-DDA#36512]
# Describe the bug

I can't wear anything on my feet. I was wearing winter boots, and took them off to equip another pair of shoes. Wouldn't let me; said I already had footwear equipped. Took off socks to no avail. Wouldn't let me put on any shoes, including the winter boots I just had on.

~~I have the Tough Feet perk/trait. Perhaps that has something to do with it.~~

I think the issue was that I was wearing a blanket. So you can wear a blanket with shoes on, but then if you take the shoes off, you can't wear them again, because now blanket is footwear (?). Not sure if this is desirable or not, but it is a bit confusing.

# Steps To Reproduce

1. Be wearing some shoes
2. Wear a blanket
3. Take off shoes
4. Now you can't put shoes back on again

# Expected behavior

I expected to be able to wear shoes with blanket, because I could wear blanket with shoes (if that makes sense). 

Assuming my understanding of what is happening is correct, an improvement might be for the error message to say "already wearing footwear: [item name worn]". Alternatively, when wearing blanket or similar, and attempt to put on footwear, blanket could automatically unequip from just feet, or a dialog warning "do you want to unequip blanket?"

# Additional

Attached is savegame file.
[Glenmora.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4007136/Glenmora.zip)

Feel free to close this as user error, or re-categorize it as a feature request.

**Comment by Jerimee** [comment]
user error! turns out I was wearing blanket

**Comment by davidpwbrown** [comment]
blanket needed to  be activated to expose feet.
