### ISSUE TITLE
Cardboard Box Storage

### ISSUE THREAD

**Issue by Zourin2** [CleverRaven/Cataclysm-DDA#36515]
**Is your feature request related to a problem? Please describe.**  
Cardboard boxes are neigh-useless. 

**Describe the solution you'd like**  
Allow cardboard boxes to store Powder-type items such as Lye Powder, Flour, Salt, Sugar, and various medical pills and non-liquid drugs.

**Describe alternatives you've considered**  
Hiding in them to confuse and evade enemies.

**Comment by ZhilkinSerg** [comment]
See #3671

**Comment by Zourin2** [comment]
Considering that's been around since 2013, I was thinking more of a temporary flextape job until #3671 looks like it's going to bear fruit.

**Comment by anothersimulacrum** [comment]
Someone is actively working on #3671, and having a half-way implemented version of it would be bad, might as well go the whole way.
