### ISSUE TITLE
Error from astyle-check in src/weather.cpp

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#36516]
# Describe the bug

When doing a clean compilation on Ubuntu Linux with this recent change to src/weather.cpp: https://github.com/CleverRaven/Cataclysm-DDA/commit/d4c7fbf29049e68f76163bc3c2611d226cff0fa0

I am getting this error from astyle-check:
$ make -j2 TILES=1 SOUND=0 RELEASE=1 USE_HOME_DIR=1                                                       astyle -V: Artistic Style Version 3.1                                                                                                  #define VERSION "0.D-10748-g941f00f157"                                                                                                
astyle regressions found.                                                                                                              Formatted  src/weather.cpp                                                                                                             Makefile:1029: recipe for target 'astyle-check' failed                                                                                 
make: *** [astyle-check] Error 1

# Steps To Reproduce

1. Run 'make clean && make -j2 TILES=1 SOUND=1 RELEASE=1 USE_HOME_DIR=1

# Expected behavior

Successful compilation

# Versions and configuration

Using experimental branch as of commit https://github.com/CleverRaven/Cataclysm-DDA/commit/d4c7fbf29049e68f76163bc3c2611d226cff0fa0

# Additional context

Rolling back the commit in question allowed me to compile successfully.

**Comment by BevapDin** [comment]
Fixed by #36505.
