### ISSUE TITLE
Secronom breaking my save

### ISSUE THREAD

**Issue by HunorP** [CleverRaven/Cataclysm-DDA#36526]
# Bug description

Secronom update breaking the save

# Steps To Reproduce

1. Update game to Build 10086
2. Update mod (Secronom) after the game tolds you 
3. Trying to load up save with mod in question enabled and fail.

# Expected behavior

Save loading up successfully 

# Additional context 

DEBUG    : Tried to convert argument of type NSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE to x, which is not possible at: "Deprecated foreground color suffix was used: (%d|) in (%s).  Please update mod that uses that."

 FUNCTION : nc_color color_from_string(const string&)
 FILE     : src/color.cpp
 LINE     : 563

 (Post-update)
 DEBUG    : Error: data/mods//secronom/Modification Files/Items/secro_guns.json: line 362:17: separator not strictly allowed at end of array

        [ "rail", 1 ],
        [ "sights", 1 ],
        [ "stock", 1 ],
                ^

        ],
        "ammo_effects": [ "PLASMA", "INCENDIARY" ],

 FUNCTION : bool main_menu::load_character_tab(bool)
 FILE     : src/main_menu.cpp
 LINE     : 1060

**Comment by Night-Pryanik** [comment]
This mod isn't officially supported. Ask its author to fix the bug.

**Comment by Axema** [comment]
It is fixed now, and your save file is safe. Just update the mod from the mod's repo.
