### ISSUE TITLE
Snow Trail

### ISSUE THREAD

**Issue by ThomasLinkin** [CleverRaven/Cataclysm-DDA#36523]
**Is your feature request related to a problem? Please describe.**  
Snow Trail

**Describe the solution you'd like**  
What if it's winter and the game allows the animals to leave a faint trail behind them for you to track them down and hunt them?

**Describe alternatives you've considered**  
It would be nice to have a little trail behind. For realistic purposes

**Additional context**  
Just an recommendation, again, it would be nice af

**Comment by ZhilkinSerg** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/28227
