### ISSUE TITLE
Acidic Ant are not removed with the mod "No Acid Zombies"

### ISSUE THREAD

**Issue by Moumix3** [CleverRaven/Cataclysm-DDA#36525]
Game version: build 10076

Expected behavior:
Even though the mod name specifies "zombies", the expectation (that I had at least) is that I would have no acid monster at all in the game. If I'm not mistaken, Acidic Ants are (relatively) new additions to the game, so this issue wasn't happening before.

If this mod is solely designed for acid zombies and not other acid monsters, maybe we could create a second one for all the other acid monsters. Otherwise, this could be renamed to "No acid enemies", and remove all acid enemies, not just the zombies.

**Comment by kevingranade** [comment]
Yes, hence the name.
If you want a no acid ants mod, edit the No Anthills mod, but I'm not interested in having that mod mainlined.
