### ISSUE TITLE
Crash to desktop when NPC tries chopping trees

### ISSUE THREAD

**Issue by snipercup** [CleverRaven/Cataclysm-DDA#36544]
# Describe the bug
When the NPC returns to camp to grab a tool in order to chop trees, the game crashes. It worked before on this save, about 36 hours ago. After that, I started getting errors during save load that I have not seen before.

# Steps To Reproduce
1. Load the save
2. Wait for the NPC to return to camp (he is already given the order to chop trees
3. Observe crash

# Expected behavior
Not crash

# Screenshots

In the save, there is an area with tree stumps and a chop trees zone:
![image](https://user-images.githubusercontent.com/50166150/71564271-3b851c00-2a9e-11ea-9c80-26befc20c221.png)

The NPC is given the order by talking to him, talk about current activities, order to chop down trees in the zone.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-10802-g072ff2f [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Craftable Gun Pack [craftgp],
    Makeshift Items Mod [makeshift],
    Mining Mod [Mining_Mod],
    Folding Parts pack [deoxymod],
    Simplified Nutrition [novitamins],
    Magiclysm [magiclysm],
    More Survival Tools [More_Survival_Tools],
    More Locations [more_locations],
    Garden Pots [growable-pots],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    Hydroponics [hydroponics],
    Fuji's More Buildings [FujiStruct],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Bens GF recipes [Tolerate_This],
    Icecoon's Arsenal [ew_pack],
    Cataclysm++ [Cata++],
    Urban Development [Urban_Development],
    Mythological Replicas [nw_pack],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs]
]

# Additional context

Crash and debug logs
[debugandcrashlog.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4008721/debugandcrashlog.zip)

Save file: https://ufile.io/mruj77vc
(Github only allows 10MB, save is 50MB)

**Comment by ZhilkinSerg** [comment]
Empty `str_values` for `ACT_MULTIPLE_CHOP_TREES` activity in backlog.

![image](https://user-images.githubusercontent.com/16213433/71571950-03a5c500-2aee-11ea-8d6a-af629c6c5cae.png)

**Comment by davidpwbrown** [comment]
Weird. the requirements object was stored as empty.

I can fix the crash by checking emptiness in the relevant unpacking function, but wonder why it did?

When I cancel that NPCs activity in the save, then tell them to start again, they dont do anything, because the nearest loot zone is too far away for them to fetch, so they dont.

However it does crash if I let them continue what theyve started, and they are walking all the way to the north-east, which is weird because the search radius for loot zones should only be 10 tiles....

**Comment by davidpwbrown** [comment]
Then it crashes due to `    ??
    ??:0
    itype::count_by_charges() const
` soon after, wtf.
