### ISSUE TITLE
Removing carpet bypasses safe lock

### ISSUE THREAD

**Issue by DatMeg** [CleverRaven/Cataclysm-DDA#36541]
# Describe the bug

The process of removing carpeting (via the construction menu) moves items off of the tile being deconstructed. Turns out, it does this for the content of safes as well, bypassing the lock. However, there aren't many places in the game where safes spawn on top of carpeting, or floors that can be carpeted (like you can't do this in bank vaults)

# Steps To Reproduce

1. Find a Bank Vault.
2. Debug map-edit the floor under the safes to carpeting (it works on all 6 variants).
3. Deconstruct the carpeted floor (just need a Hammer).
4. Find your loot on the ground nearby.
5. Pick the safe, and find it empty.

Alternatively:
1. Find a Light Industrial complex (which does require a mod).
2. Go to the carpeted office with a safe.
3. Deconstruct the carpeted floor under the safe
4. Get your loot.

# Expected behavior

The contents of the safe should probably remain locked inside, even when working the floors near them.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-10794-g7881181 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by Zupercharged** [comment]
I remember someone saying that dragging a safe has a similar effect where the loot doesn't travel with it. Also might be worth checking if the issue could be reproduced by trying building flooring underneath the safe.

**Comment by DatMeg** [comment]
> 
> 
> I remember someone saying that dragging a safe has a similar effect where the loot doesn't travel with it. Also might be worth checking if the issue could be reproduced by trying building flooring underneath the safe.

Moving safes got fixed awhile back. _I did go back and test building under safes, and that also does bypass the locks._
