### ISSUE TITLE
Only 2 are dropped when dropping item stacks

### ISSUE THREAD

**Issue by NeevAsteria** [CleverRaven/Cataclysm-DDA#36554]
# Describe the bug

Dropping a stack of an item just makes it drop only 2 of it. Only affected items are the ones with quantity first (e.g. planks, pipes, etc.), items with the quantity on a parentheses are not affected (e.g. nails, scrap metal, rocks, etc.)

# Steps To Reproduce

1. Have an item that can be stacked
2. Drop items
3. Check ground and inventory and see you only dropped 2 of it

# Expected behavior

If you intend to drop a fulls stack, it should drop all of it not just 2

# Screenshots

![image](https://user-images.githubusercontent.com/58652206/71577823-a2531580-2b30-11ea-9156-e67052fd5c7a.png) ![image](https://user-images.githubusercontent.com/58652206/71577864-c6aef200-2b30-11ea-9eaf-0978aa14cbb8.png)
![image](https://user-images.githubusercontent.com/58652206/71577885-dcbcb280-2b30-11ea-9f95-4c28dc94a03d.png) ![image](https://user-images.githubusercontent.com/58652206/71577891-e6deb100-2b30-11ea-825d-cbabd5758bac.png)

# Versions and configuration

 - OS: Windows 8.1
 - Game Version: 0.D-10828-gc532fc4
 - Graphics version: Tiles
 - Mods loaded: 
![image](https://user-images.githubusercontent.com/58652206/71578019-594f9100-2b31-11ea-89f2-2c767b0bc485.png)

# Additional context

None. I believe I have explained the bug fully.

**Comment by Alapaga** [comment]
I second this, my operating system is windows 10

**Comment by Lamandus** [comment]
I third this.

**Comment by Lamandus** [comment]
I checked and the version which caused it to happen was 10091, while 10090 still has a functioning multi drop.

**Comment by Alkheemist** [comment]
Gonna take a wild guess and say it was introduced in https://github.com/CleverRaven/Cataclysm-DDA/commit/1c9dafc398a004a4f0eb03aa8ab47e76cd423e7a
since that's the only commit related to dropping between those two build numbers

**Comment by KorGgenT** [comment]
yup. looking into it now.

**Comment by KorGgenT** [comment]
in activity_item_handling.cpp, there's this block of code:
```
    while( !items.empty() && ( p.is_npc() || p.moves > 0 || items.front().consumed_moves == 0 ) ) {
        act_item &ait = items.front();

        p.mod_moves( -ait.consumed_moves );

        if( p.is_worn( *ait.loc ) ) {
            p.takeoff( *ait.loc, &res );
        } else if( ait.loc->count_by_charges() ) {
            res.push_back( p.reduce_charges( const_cast<item *>( &*ait.loc ), ait.count ) );
        } else {
            res.push_back( p.i_rem( &*ait.loc ) );
        }

        items.pop_front();
    }
```
for some reason, the if statement, specifically res.push_back invalidates every single item_location in the list `items`. one possibility is that `items` is just a bunch of copies of the same pointer.

**Comment by BevapDin** [comment]
A guess: when an `item_location` is created for the item to be dropped, it is created via the item index. The `item_location::impl::item_on_person` stores the index, but does not retrieve the item reference at that point.

That is done later when the outside code requests the item pointer via the `item_location` interface. At that point, the index could have changed its meaning.

----

Alternatively: the `item_location` is created using the item pointer, which is stored (but the index is never calculated as it is not necessary). Dropping the item invalidates the item pointer, and the item location is no invalid and skipped.

**Comment by Rainoutt** [comment]
I can confirm the bug, latest version and Windows 10.

**Comment by KorGgenT** [comment]
@BevapDin the item location is created from the item retrieved via index in advanced inventory, but the item location isn't even storing the index. What i'm seeing happen while stepping through the code is that by the second turn of the activity, it has forgotten all of the item_locations that were in the targets list of the activity. They don't get invalidated in the activity itself, but when the activity returns and it tries to manipulate them, it can't. resulting in dropping only as many as you could dorp in a single turn, and also occasionally seg faulting due to null item pointers. I haven't yet been able to pinpoint where the item locations are actually being invalidated though.

**Comment by KorGgenT** [comment]
in obtain_activity_item, there is this block of code: 
```
    while( !items.empty() && ( p.is_npc() || p.moves > 0 || items.front().consumed_moves == 0 ) ) {
        act_item &ait = items.front();

        p.mod_moves( -ait.consumed_moves );

        if( p.is_worn( *ait.loc ) ) {
            p.takeoff( *ait.loc, &res );
        } else if( ait.loc->count_by_charges() ) {
            res.push_back( p.reduce_charges( const_cast<item *>( &*ait.loc ), ait.count ) );
        } else {
            res.push_back( p.i_rem( &*ait.loc ) );
        }

        items.pop_front();
    }
```
res.push_back is what is invalidating the entire list of item_locations in `items, causing you to only be able to drop two, since `targets` is not invalidated yet

**Comment by KorGgenT** [comment]
and i just realized i said this twice. well at least i've confirmed it

**Comment by Unrepentant-Atheist** [comment]
That fix is not really good. Can't drop large quantities or many items, game freezes.

**Comment by Lamandus** [comment]
can confirm, game freezes when dropping too many different items.

**Comment by innun** [comment]
> That fix is not really good. Can't drop large quantities or many items, game freezes.

same here.  
crash.log:   
```
The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 0.D-10976-ga39fc83
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

    ./cataclysm-tiles(_Z21debug_write_backtraceRSo+0x38) [0xa2ad71]
    ./cataclysm-tiles() [0xa1b398]
    ./cataclysm-tiles() [0xa1b51a]
    /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7f5f85b71f20]
    ./cataclysm-tiles(_ZNK4item16count_by_chargesEv+0) [0xb86404]
    ./cataclysm-tiles() [0x8be565]
    ./cataclysm-tiles(_ZN17activity_handlers12drop_do_turnEP15player_activityP6player+0x84) [0x8c4fcd]
    ./cataclysm-tiles(_ZNKSt8functionIFvP15player_activityP6playerEEclES1_S3_+0x24) [0x8d69b6]
    ./cataclysm-tiles(_ZN15player_activity7do_turnER6player+0x11a) [0xf6a7cc]
    ./cataclysm-tiles(_ZN4game16process_activityEv+0x82) [0xaca5ec]
    ./cataclysm-tiles(_ZN4game7do_turnEv+0x223) [0xae73f9]
    ./cataclysm-tiles(main+0x12b3) [0x7fccf4]
    /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f5f85b54b97]
    ./cataclysm-tiles(_start+0x29) [0x887f59]

    Attempting to repeat stack trace using debug symbols…
    debug_write_backtrace(std::ostream&)
    ??:?
    log_crash
    crash.cpp:?
    signal_handler
    crash.cpp:?
    ??
    ??:0
    item::count_by_charges() const
    ??:?
    obtain_activity_items(player_activity&, player&) [clone .constprop.1818]
    activity_item_handling.cpp:?
    activity_handlers::drop_do_turn(player_activity*, player*)
    ??:?
    std::function<void (player_activity*, player*)>::operator()(player_activity*, player*) const
    ??:?
    player_activity::do_turn(player&)
    ??:?
    game::process_activity()
    ??:?
    game::do_turn()
    ??:?
    main
    ??:?
    __libc_start_main
    /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:344
    _start
    ??:?
```
