### ISSUE TITLE
Multiple errors when approaching hazardous waste sarcophagus.

### ISSUE THREAD

**Issue by Solusphere** [CleverRaven/Cataclysm-DDA#36561]
# Describe the bug

I receive a series of error messages when approaching a hazardous waste sarcophagus. After skipping through around 5 errors, reaching the sarcophagus shows it has completely failed to load.

# Steps To Reproduce

1. Load the provided save. (Character is Anneka Lee)
2. Proceed down the road.
3. Encounter series of error messages.

# Expected behavior

The hazardous waste sarcophagus should load successfully with no error messages.

# Screenshots

https://cdn.discordapp.com/attachments/252368751016542218/661185297509384192/unknown.png

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.D-10853-g5b3dcd7 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    More Survival Tools [More_Survival_Tools],
    Mutant NPCs [mutant_npcs],
    Folding Parts pack [deoxymod],
    Whaleys Hair Mod [WHALEYHAIR1],
    No Fungal Monsters [No_Fungi]
]

# Additional context

I'm using a single, cosmetic, third party mod. Ignoring it should be safe, but I'm including it just to be on the safe side.

[Clatonia.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4009843/Clatonia.zip)

**Comment by Night-Pryanik** [comment]
This happens because you're playing in a old, pre-#35998 world. New worlds shouldn't have this error.

**Comment by ZhilkinSerg** [comment]
> This happens because you're playing in a old, pre-#35998 world. New worlds shouldn't have this error.

Didn't you add savegame migration in that PR?

**Comment by Night-Pryanik** [comment]
> Didn't you add savegame migration in that PR?

Nope.

**Comment by Solusphere** [comment]
Ah, damn. I don't suppose there are any quick edits I could make to fix my current world?

**Comment by ZhilkinSerg** [comment]
> 
> 
> > Didn't you add savegame migration in that PR?
> 
> Nope.

Oh. I will look into it tonight then.
