### ISSUE TITLE
After heavily infected/antibiotic recovery, player is exhausted after 5 continuous days of full sleep

### ISSUE THREAD

**Issue by TimothyQuark** [CleverRaven/Cataclysm-DDA#36572]
# Describe the bug

Character is still exhausted despite 5 days of sleeping after recovering from an infection.

Character was bitten in the right leg by a zombie, and I went to sleep without noticing it. Wound became heavily infected, but after waking up I immediately used antibiotics. Once those kicked in, character went into the usual nausea spiral of throwing up, difficulty sleeping etc for 3-4 days. When this passed, character was dehydrated and dead tired, but no pain or other effects. Immediately went to sleep again, only for character to turn exhausted. I have been doing nothing except waking up, eating 2000 calories every meal to get back to overweight, eating vitamins and calcium tablets, drinking until engorged and then going back to sleep. This has gone for 5 days now and character is still exhausted, despite waking up with positive health messages ("Awareness comes fast, your body coming quickly to attention after your rest").

# Steps To Reproduce

1. Get heavily infected, use antibiotics.
2. Survive nausea spiral.
3. Player will go from dead tired to exhausted after sleeping without any (visible) negative modifiers.
4. Player stays exhausted despite doing nothing but eating, drinking and sleeping.

Probably useful to know are character CBMs:

- Leukocyte Breeder System (always on, however nausea spiral caused character to lose so much weight that metabolic interchange stopped running, so was off for two days or so)
- Blood Analysis
- Blood Filter
- Repair Nanobots
- Metabolic Interchange (set to activate when under 25% power)

# Expected behavior
After infection is over and character has recovered, a few nights of good sleep should return them to normal. Should not be exhausted after multiple days of sleep.

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-10801-g8c616da [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Disable Religious Texts [no_religious_Texts],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

Character is sleeping in car, so whenever they wake up at night it is freezing cold (-60 to -120), I think this is partly due to exhaustion? Those are really low numbers for spring time, but it looks like sleeping with a blanket on seat mitigates this.

Save file: https://drive.google.com/file/d/1s0d3zDTiJ6YZQuKBPLYk1j9DfjvWsLnF/view?usp=sharing

**Comment by RobertoVGoulart** [comment]
I mean, you did nearly become zombified, which is probably the worst "disease" possible to get during the cataclysm, so you should take longer than a cold to get fully recovered.

**Comment by anothersimulacrum** [comment]
This isn't a zombie infection,, this is a normal infection.

**Comment by kevingranade** [comment]
As outlined here https://discourse.cataclysmdda.org/t/infection-and-infection-recovery-two-possible-bugs/22275 there may be a logic error where antibiotic use extends the duration of infection and inappropriately increases severity of the resulting infection recovery.

It's also possible the rate of fatigue gain hasn't been updated for one second turns, exacerbating the severity of recovery.

**Comment by KingApep** [comment]
Reproduced on a character at day 1:

Started day 1 bionic surgeon: First aid 10
Used antibiotics immediately
After two days of infected limb, it was cured 
As soon as limb was cured, fatigue turned to exhausted state and all limbs dropped to -140 to -200
5 days later, character is still exhausted.

**Comment by Soup-de-Loop** [comment]
I've run into this a couple of times because the Infected start is my default lately, and I've debugged to check why the exhausted state stayed, I was getting fatigue numbers of **more than** 2000 _after_ I entered recovery stage.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/royal-jelly-antiobitics-not-working/24316/2
