### ISSUE TITLE
"(loose) knit scarves" are MUCH more difficult to repair than "knit scarves" 

### ISSUE THREAD

**Issue by MLamor** [CleverRaven/Cataclysm-DDA#36580]
Game version: 0.D-10214-ge667aa0

Operating system: Windows 10 

Tiles or curses: Tiles

Mods active: DDA, Disable NPC Needs, Icecoons Arsenal, Deadleavs Fictional Guns, Makeshift Items, More Survival Tools, Modular Turrets, Salvaged Robots, Mutant NPC, Beta National Guard Camp,
More Locations, Fuji's More Buildings, Mapgen Demo, No Rail Stations, Urban Development, Folding Parts, Vehicle Additions, Tanks & Other Vehicles, Roadheader & Mining Vehicles

### Expected behavior
A scarf should be just as simple/difficult to repair whether it is being worn tight, or being worn loosely, because it is the same item either way.

### Actual behavior
(loose) knit scarves are harder (or impossible) to repair, while a regular knit scarf is easy to repair.

### Steps to reproduce the behavior
With 5 Tailoring skill, using a Sewing Kit, attempting to reinforce a (loose) knit scarf will have 0% chance for success, and 4% chance for failure, (a)ctivating the (loose) knit scarf to tighten it first changes it to 10% chance for success, and 0% chance for failure.

**Comment by k4gi** [comment]
I was investigating this yesterday (with the help of the Discord). The cause could be that repairing an item gets harder if the player doesn't know its recipe, or if a recipe doesn't exist. I couldn't decipher the code enough to find out if this is the case :stuck_out_tongue_closed_eyes:

**Comment by Night-Pryanik** [comment]
Here's comments from the `repair_item_actor::repair_recipe_difficulty`:

```
If the recipe is not known by the player, +1 to difficulty
If player doesn't meet the requirements of the recipe, +1 to difficulty
If the recipe doesn't exist, difficulty is 10
```

So, repair difficulty of crafting the knit scarf is 1, but because there is no recipe for crafting the loose knit scarf, its repair difficulty is 5 (and not 10, if I'm reading the code right). That's why repairing loose knit scarf is harder.
