### ISSUE TITLE
Mr. <last_name> is a vampire!

### ISSUE THREAD

**Issue by k4gi** [CleverRaven/Cataclysm-DDA#36587]
# Describe the bug

The graffiti snippet "Mr. <last_name> is a vampire!" doesn't substitute the <last_name> tag for a name.

# Steps To Reproduce

I don't know how to make graffiti spawn on a wall, but if I did that's what I'd do to try and reproduce this.

# Expected behavior

I expected the <last_name> tag to be substituted from one of the last names in the list. That's what the other tags are doing.

![Screenshot of the text](https://user-images.githubusercontent.com/26471575/71610041-ac811c80-2be1-11ea-95e0-3d3d2893a5f4.png)

# Versions and configuration

 - OS: Ubuntu 19.04
 - Game Version: 0.D-10802-g072ff2f
 - Graphics version: Tiles
 - Mods loaded: Dark Days Ahead, Disable NPC Needs

**Comment by Qrox** [comment]
The correct tag would be `<family_name>`.
