### ISSUE TITLE
Plastic bags and glass pieces can only be put in two other containers at a time

### ISSUE THREAD

**Issue by chuizhi** [CleverRaven/Cataclysm-DDA#36595]
**Please be patient, because I use translation software to translate Chinese into English**

# Describe the bug

In the game, when you "put down" a piece of glass / plastic bag / non-metallic products (vacuum packaging meat chips, etc.), you can only put down 2 pieces. No matter what method you use, you can only put down 2 pieces at a time

From version 10091 to today's 10099, it has not been good

Version 10085 is normal

# Versions and configuration
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-10910-g44775fc [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    浩劫余生 [dda],
    禁用NPC需求 [no_npc_food],
    余波未尽 [aftershock],
    Ben的定制菜单 [Tolerate_This],
    DeadLeaves的虚构枪械 [FIC_Weapons],
    C.R.I.T 扩展 [crt_expansion],
    大魔法 [magiclysm],
    Icecoon的军工厂 [ew_pack],
    中世纪及历史上的职业和盾牌 [Medieval_Stuff],
    园艺花盆 [growable-pots],
    更多幸存者工具 [More_Survival_Tools],
    神话武器复制品 [nw_pack],
    自制简易物品 [makeshift],
    模块化炮塔 [modular_turrets],
    改装机器人 [Salvaged_Robots],
    变异NPC [mutant_npcs],
    水培种植 [hydroponics],
    甜蜜大灾变 [my_sweet_cataclysm],
    神话武术 [MMA],
    更多的地点 [more_locations],
    Fuji的更多建筑包 [FujiStruct],
    更多城镇建筑 [Urban_Development],
    测试民兵营地 [national_guard_camp],
    载具增强包 [blazemod],
    坦克和其他车辆 [Tanks],
    折叠式车辆部件 [deoxymod],
    掘进机及其他矿车 [Heavy miners],
    死灵法术 [necromancy],
    移除真菌类怪物 [No_Fungi],
    完全可靠的医疗仪 [safeautodoc],
    手动安装生化插件 [manualbionicinstall]

**Comment by Feuerhai** [comment]
Already reported here: #36554

**Comment by BevapDin** [comment]
Closing as duplicate.
