### ISSUE TITLE
Extinguishers are smaller than the containers they produce when dissassembled.

### ISSUE THREAD

**Issue by sztosz** [CleverRaven/Cataclysm-DDA#36603]
# Describe the bug

Large fire extinguisher has volume of 11500 ml, and when disassembled, produces 20000 ml container. 

Small fire extinguisher has volume of 1500 ml, and when disassembled, produces 2000 ml container. 

# Expected behaviour

Extinguishers when disassembled should produce tanks smaller than extinguishers itself.

# Versions and configuration

- OS: Linux
- OS Version: LSB Version: 1.4; Distributor ID: Antergos; Description: Antergos Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.D-10921-g51b0689218-dirty [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Graphical Overmap [Graphical_Overmap],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Disable Religious Texts [no_religious_Texts],
    No Flaming Weapons [no_flaming_weapons],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Magiclysm [magiclysm]
]

# Additional context

We can either adjust the volume (and preferably weight) of extinguishers, or introduces smaller tanks, a 10 L tank for the bigger one, and a 1 L one for the smaller one. 

Adjusting volume and weight of existing extinguishers seems to be straightforward, and would not introduce another containers that could theoretically be installed in cars etc. 

On the other hand, the large one is supposed to be "three gallons" from description. Though when I dig somewhat deeper into US extinguishers they are usually described in weight of the extinguishing agent, not volume. And I really wasn't able to find a 3 gallon (11.3562 l) extinguisher when searching web. And that makes me think that since SI units are used in game internally (thank god!) then we should just stay with that, change volume and weight of extinguishers (and description of the large one).

I can do a PR, but I'd rather hear from someone else if it makes any sense to do so.

**Comment by Brian-Otten** [comment]
I made a pull for this one partially to practice my PR skills a bit, hopefully a good way to resolve the issue so have a look.
