### ISSUE TITLE
Memory not connecting walls properly

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#36609]
# Describe the bug

Map memory would usually keep the same tile as what you saw, but in this case it seems that some tiles are changing between map memory and normal vision

# Steps To Reproduce

1. Find natural occurrence of such a tile (probably best in lab in the same section as pictures) 

# Expected behavior

Map memory is a record of what normal vision sees

# Screenshots

The only weird tiles are the ones below the character and right at the top with just a couple problem connections.

Picture showing walls below character are blocks instead of connected walls
![Capture2](https://user-images.githubusercontent.com/24307650/71637534-37c6d600-2c13-11ea-8a62-29320e59f15d.PNG)

Normal vision of the connected walls
![Capture3](https://user-images.githubusercontent.com/24307650/71637539-5fb63980-2c13-11ea-9019-7be0b51491ee.PNG)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-10922-gb1541cd [32-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    No Fungal Monsters [No_Fungi],
    Disable Religious Texts [no_religious_Texts]
]

**Comment by Qrox** [comment]
The only reason I can think of is that map memory connection was not correctly calculated when memorizing the tiles, but I'm not able to reproduce it. Have you previously entered the bottom aisle? Were you there with low light level?

**Comment by kevingranade** [comment]
I think you're right, it memorizes the wall as drawn the first time you see it, but it doesn't get updated once you see the wall next to it that adjusts what tile is drawn there.

**Comment by Qrox** [comment]
Well, it always calculate the connection according to nearby tiles even if you can't see them, so I don't known why would the connection be wrong in the first place.

**Comment by kevingranade** [comment]
I'm pretty sure it doesn't, that would leak information.

**Comment by Qrox** [comment]
You're right, I didn't reproduce it because the tileset I was using doesn't have edges on the wall tiles, so it looked as if it calcuated connection according to nearby tiles.
