### ISSUE TITLE
Sandbags each need: 60 sand  Earth bags each need: 3 pieces of earth

### ISSUE THREAD

**Issue by chuizhi** [CleverRaven/Cataclysm-DDA#36600]
**Please be patient, because I use translation software to translate Chinese into English**

# Describe the bug
Sandbags each need: 60 sand  
Earth bags each need: 3 pieces of earth
I built a concrete wall around my house and dug up a lot of mud that I couldn't handle. Make earth bags, but the soil consumption is too small.
![image](https://user-images.githubusercontent.com/59391871/71628778-ca2ba180-2c34-11ea-8afb-26fb14f1ea82.png)

# Versions and configuration

OS: Windows
OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
Game Version: 0.D-10910-g44775fc [64-bit]
Graphics Version: Tiles
Mods loaded: [
浩劫余生 [dda],
禁用NPC需求 [no_npc_food],
余波未尽 [aftershock],
Ben的定制菜单 [Tolerate_This],
DeadLeaves的虚构枪械 [FIC_Weapons],
C.R.I.T 扩展 [crt_expansion],
大魔法 [magiclysm],
Icecoon的军工厂 [ew_pack],
中世纪及历史上的职业和盾牌 [Medieval_Stuff],
园艺花盆 [growable-pots],
更多幸存者工具 [More_Survival_Tools],
神话武器复制品 [nw_pack],
自制简易物品 [makeshift],
模块化炮塔 [modular_turrets],
改装机器人 [Salvaged_Robots],
变异NPC [mutant_npcs],
水培种植 [hydroponics],
甜蜜大灾变 [my_sweet_cataclysm],
神话武术 [MMA],
更多的地点 [more_locations],
Fuji的更多建筑包 [FujiStruct],
更多城镇建筑 [Urban_Development],
测试民兵营地 [national_guard_camp],
载具增强包 [blazemod],
坦克和其他车辆 [Tanks],
折叠式车辆部件 [deoxymod],
掘进机及其他矿车 [Heavy miners],
死灵法术 [necromancy],
移除真菌类怪物 [No_Fungi],
完全可靠的医疗仪 [safeautodoc],
手动安装生化插件 [manualbionicinstall]

**Comment by chuizhi** [comment]
Can you increase the amount of soil needed to make the earth bag?

**Comment by anothersimulacrum** [comment]
There is a problem here, but it's not the earth bag soil consumption, it's the sand bag - it somehow turns `300 ml` of sand into a `16 L` bag, while the earth bag turns `15 L` of earth into a `16 L` bag.

**Comment by chuizhi** [comment]
> There is a problem here, but it's not the earth bag soil consumption, it's the sand bag - it somehow turns `300 ml` of sand into a `16 L` bag, while the earth bag turns `15 L` of earth into a `16 L` bag.

呃……那么能不能增加泥土的消耗？你看图，泥土实在太多了。修建强化混凝土墙之后，一地建筑垃圾。
Er... Can we increase the consumption of soil? Look at the picture. There is too much mud. After the construction of reinforced concrete wall, the construction waste is everywhere.

**Comment by anothersimulacrum** [comment]
Soil shouldn't magically vanish, dump it somewhere or use it in something else.

**Comment by chuizhi** [comment]
> Soil shouldn't magically vanish, dump it somewhere or use it in something else.

I want to make earth bags out of earth. But it's too little to consume three at a time.

**Comment by Ker-Nes** [comment]
> I want to make earth bags out of earth. But it's too little to consume three at a time.

Yet the volumes are appropriate. One unit of sand represents perhaps around a handful of sand. One unit of earth is probably around a bucketful of earth. Maybe one unit more if you assume the earth is packed and compacted inside the bag, which is not generally true in most cases. You will also likely face issues with getting enough textiles, as canvas bags seem to take a massive amount of it.

You will likely have a better time either carrying them out of sight to dump them, or if you absolutely want to make use of them, creating adobe bricks. Getting a few large farm animals should get you enough manure to craft quite a lot of it every few days or so.
