### ISSUE TITLE
Tilesets listed twice in the options menu

### ISSUE THREAD

**Issue by RobertoVGoulart** [CleverRaven/Cataclysm-DDA#36617]
# Describe the bug

Every entry on the list of Tilesets avaliable in the Options menu seems to be duplicated.

# Steps To Reproduce

Go to Settings > Options > Graphics tab > "Choose Tileset" and check the list of possible options on top. 

# Expected behavior

Only one option for each Tileset avaliable.

# Screenshots

Default options from a fresh install: 

![Image 2008](https://user-images.githubusercontent.com/20757625/71643860-b9fbdc80-2c9d-11ea-8dde-faea7417f66a.jpg)

After downloading "UltimateCataclysm" Tileset, confirming there's only one entry of it on the "gfx" folder and rechecking the listing: 
![Image 2010](https://user-images.githubusercontent.com/20757625/71643862-c2ecae00-2c9d-11ea-82b8-1f5c0c2d9d6e.jpg)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-10932-g9eb7975 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Urban Development [Urban_Development],
    Mapgen Demo [mapgen_demo],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Beta National Guard Camp [national_guard_camp],
    Safe Autodoc [safeautodoc],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

"gfx" folder seems to only have one of each tileset, "options.json" shows duplicated entries.

**Comment by ZhilkinSerg** [comment]
This happens because both gfx dir and user gfx dir are pointing to same folder.

**Comment by ZhilkinSerg** [comment]
Caused by #35091
