### ISSUE TITLE
Items in toilet dissappear on save/load

### ISSUE THREAD

**Issue by snipercup** [CleverRaven/Cataclysm-DDA#36616]
# Describe the bug

Items dropped on a toilet disappear when saving the game, exiting and loading the game again. I've had it happen to bathtub too but haven't been able to reproduce it consistently.

# Steps To Reproduce

1. Drop an item on a toilet
2. Save and exit
3. Load the game, observe items are gone

# Expected behavior

Items should stay in the toilet

# Screenshots

Before save/exit:
![image](https://user-images.githubusercontent.com/50166150/71643380-5384b780-2cb9-11ea-8c42-556f434a9a43.png)
![image](https://user-images.githubusercontent.com/50166150/71643383-5f707980-2cb9-11ea-86f6-8cff2d5cd7f8.png)

After:
![image](https://user-images.githubusercontent.com/50166150/71643386-6a2b0e80-2cb9-11ea-91df-d50b0887b613.png)
![image](https://user-images.githubusercontent.com/50166150/71643393-757e3a00-2cb9-11ea-8083-2142f0e3c435.png)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-10932-g9eb7975 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Bens GF recipes [Tolerate_This],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Generic Guns [generic_guns],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Cataclysm++ [Cata++],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Roadheader and other mining vehicles [Heavy miners],
    Necromancy [necromancy]
]

# Additional context
Save with a pile of gore in the player spot. See if you can reproduce it by distributing the gore to the toilet/tub and saving/loading.
[20191238-0124-100-100_copy.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4014247/20191238-0124-100-100_copy.zip)

**Comment by BevapDin** [comment]
Are you talking about the rotten stuff? That disappears when the map is loaded as it "rots away to nothing". This happens upon loading a game, but also when you move away and come back to the place.

This is intentional.

**Comment by snipercup** [comment]
Ah, so that was it. It does not happen with the tainted bone, so you're right.
