### ISSUE TITLE
Flexible Farming

### ISSUE THREAD

**Issue by Grubleafeater** [CleverRaven/Cataclysm-DDA#36620]
How about either adding a category of farm that will plant any available seeds(including decorative ones, if only for withered plants) or making farm categories toggles, so you can select what seed types you want planted rather than only have one? After all, your underlings are supposedly sentient and should be able to understand that if one seed isn't available, you plant another. With a little more complexity, it could also be given a priority system(IE first check for buckwheat, then check for oats).

**Comment by Funguss** [comment]
Either this will need to be done carefully or harvested items will need to be deposited on the source tile. Currently harvested items that are dropped in an adjacent tile, but if these are occupied (by other crops, for example) then the harvest is destroyed. Different crops grow at different speeds so you need to take this into account when planting. It's a bit of a hassle. If zones are able to plant any seed then you could end up with farms that generate very low yields when harvested, and if you leave it all up to NPCs you may never know why.
