### ISSUE TITLE
Use system time for holidays

### ISSUE THREAD

**Issue by Pgj1997** [CleverRaven/Cataclysm-DDA#36628]
I've noticed that we've been manually changing the title screens for the holiday variants. I don't think it's really necessary to make an entirely new patch update just for a small Easter egg. I have a better solution: system time. The game will pull from the system's internal clock, and will display whatever title screen based on that. I did a bit of digging to see if C++ supports pulling from system time, and, with my very little knowledge on programming code from scratch, here's what I got.

```
#include <ctime>

int main() {

time_t currentTime;
struct tm *local time;

time( &currentTime );
 localTime = localtime( &currentTime );

int month = localTime->tm_mon; 
init day = localTime->tm_mday;
init wday = localTime->tm_wday;


if((month = 0) && (day = 1))
	static const holiday current_holiday holiday::new_year;

if((month = 2) && (day ≥ 21) && (wday = 0))
	static const holiday current_holiday holiday::easter;

if((month = 3) && (day ≤ 7) && (wday = 0))
	static const holiday current_holiday holiday::easter;

if((month = 6) && (day = 4))
	static const holiday current_holiday holiday::independence_day;

if(month = 9)
	static const holiday current_holiday holiday::halloween;

if((month = 10) && (day = 25) && (wday = 4))
	static const holiday current_holiday holiday::thanksgiving;

if((month = 10) && (day = 26) && (wday = 4))
	static const holiday current_holiday holiday::thanksgiving;

if((month = 11) && (day ≤ 25))
	static const holiday current_holiday holiday::christmas;

ifElse
	static const holiday current_holiday holiday::none;
}
```

**Comment by kevingranade** [comment]
Thanks a ton, I somehow missed this part of the language standard the last time I was looking for a solution.

**Comment by kevingranade** [comment]
References
https://en.cppreference.com/w/cpp/chrono/c/localtime
https://en.cppreference.com/w/cpp/chrono/c/tm

Ideally we'd have a json calendar of future holidays we update yearly or something, though there's no real reason it can't be updated for the next decade or so.

**Comment by Pgj1997** [comment]
> Ideally we'd have a json calendar of future holidays we update yearly or something, though there's no real reason it can't be updated for the next decade or so.

For holidays like Easter and Thanksgiving? Yeah, that'd probably be handy.

I trust that my code for Thanksgiving will work (found out that Thanksgiving is always on either the 25th or 26th), but not really my Easter code. Tried doing the math, and I just assumed it isn't mathematically possible for Easter to occur on anything past April 7th.

**Comment by Pgj1997** [comment]
So what exactly is stopping us from adding this?

**Comment by anothersimulacrum** [comment]
Someone doing it.

**Comment by Pgj1997** [comment]
It seriously can't be that hard to implement, right?

Would the code I gave not work?

**Comment by anothersimulacrum** [comment]
The code you gave would not work, but could be very easily turned into actual C++ instead of psuedocode and work (though there are some things that are wrong there regardless of pseudocode/actual C++.

**Comment by anothersimulacrum** [comment]
e.g.
```cpp
holiday get_holiday_from_time() {
    struct tm *local_time;

    std::time_t current_time = time( nullptr );
    local_time = std::localtime( &currentTime );

    int month = localTime->tm_mon; 
    int day = localTime->tm_mday;
    int wday = localTime->tm_wday;

    if( month == 0 && day == 1 ) {
        return holiday::new_year;
    } else if( month == 2 && day >= 21 && wday == 0 ) {
        return holiday::easter;
    } else if( month == 3  && day <= 7 && wday == 0 ) {
        return holiday::easter;
    } else if( month == 6 && day == 4 ) {
        return holiday::independence_day;
    } else if( month == 9 ) {
        return holiday::halloween;
    } else if( month == 10 && day == 25 && wday == 4 ) {
        return holiday::thanksgiving;
    } else if( month == 10 && day == 26 && wday == 4 ) {
        return holiday::thanksgiving;
    } else if( month == 11 && day <= 25 ) {
        return holiday::christmas;
    } else {
        return holiday::none;
    }
}
```
