### ISSUE TITLE
Error when dragging motorcycle or shopping cart around

### ISSUE THREAD

**Issue by UndeadMoose** [CleverRaven/Cataclysm-DDA#36626]
# Describe the bug

While dragging around a motorcycle or a shopping cart I occasionally got messages in the log that said "this x collides with errors in the movement code"

# Steps To Reproduce

1. Grab a motorcycle or a shopping cart
2. Drag it around

# Expected behavior

They shouldn't collide with movement code.

# Screenshots

![Screenshot (506)](https://user-images.githubusercontent.com/56947231/71647282-b7e65c00-2d37-11ea-9695-41c9f04f3351.png)

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-10923-g2169375
 - Graphics version: Tiles
 - Mods loaded: None

# Additional context

I first got this when I was dragging around a motorcycle around in a field campsite. Then occasionally got it when dragging around a shopping cart at a grocery store.

**Comment by Night-Pryanik** [comment]
Duplicate of #23000.
