### ISSUE TITLE
Multidrop shows drop all but instead drops only some

### ISSUE THREAD

**Issue by AntMatriarch** [CleverRaven/Cataclysm-DDA#36621]
Game version:
experimental build #10102,
0.D-10923-g2169375

Operating system:
Windows 7 Ultimate

Tiles or curses:
Tiles

Mods active:
Dark days ahead,
Disable NPC needs,
C.R.I.T Expansion Mod
Bens GF recipes
Garden Pots
Makeshift Items Mod
More Survival Tools
Modular Turrets
Mutant NPCs
sees-player icon, HitButton_iso
sees-player icon, retrodays

### Expected behavior
Drops all, as shown

### Actual behavior
Doesn't drop all

### Steps to reproduce the behavior
Have fire bricks in your inventory,
press 'd' to multidrop
select firebricks
'enter' to drop it.

### Images
![Untitled](https://user-images.githubusercontent.com/45233782/71644743-78544b80-2d08-11ea-89f4-e87971908c3f.png)
![Untitled2](https://user-images.githubusercontent.com/45233782/71644747-8bffb200-2d08-11ea-91d4-a40e20d4371d.png)

**Comment by BevapDin** [comment]
Sounds very similar to #36554. Could this be the same?

**Comment by ymber** [comment]
This is the same behavior as reported in #36554. Closing as a duplicate.
