### ISSUE TITLE
Can't see faction camp bulletin board in map memory

### ISSUE THREAD

**Issue by k4gi** [CleverRaven/Cataclysm-DDA#36624]
# Describe the bug

I've made a faction camp in an evac shelter. The bulletin board, when out of sight, is not visible on map memory. Instead the floor under it is shown.

# Steps To Reproduce

1. Make a faction camp and approach the bulletin board.
2. Move out of line of sight.
3. You will not be able to see the bulletin board in map memory.

# Expected behavior

I expect the bulletin board to be visible in map memory.

# Screenshots

![screenshot_1](https://user-images.githubusercontent.com/26471575/71646729-91c4ba00-2d3f-11ea-845d-b1a44c46e209.png)
![screenshot_2](https://user-images.githubusercontent.com/26471575/71646736-a2753000-2d3f-11ea-8093-173cd4a22abe.png)

# Versions and configuration

 - OS: Ubuntu 19.04
 - Game Version: 0.D-10802-g072ff2f
 - Graphics version: Tiles
 - Mods loaded: Dark Days Ahead, Disable NPC Needs

# Additional context

**Comment by Night-Pryanik** [comment]
AFAIK furniture (bulletin board included) isn't visible at all in map memory when out of sight. I'm not sure if it's a bug.
