### ISSUE TITLE
Clothing items collide that shouldn't

### ISSUE THREAD

**Issue by ymber** [CleverRaven/Cataclysm-DDA#36634]
# Describe the bug
Wearable items that shouldn't collide in clothing layers often do. This is most visible in SKINTIGHT and BELTED.

# Steps To Reproduce
1. Wear knee pads and a leg ammo pouch at the same time.

# Expected behavior
Clothes that are normally worn over each other do not cause extra encumbrance penalties. Clothes that occupy the same layer but different areas do not cause extra encumbrance penalties.

# Screenshots
![2020-01-05_1534_02](https://user-images.githubusercontent.com/34044886/71782468-0a42a980-2fd2-11ea-901a-09baac30f92e.png)
![2020-01-05_1534_29](https://user-images.githubusercontent.com/34044886/71782469-0a42a980-2fd2-11ea-93df-1026f0799618.png)
![2020-01-05_1534_59](https://user-images.githubusercontent.com/34044886/71782470-0a42a980-2fd2-11ea-82e6-ff9351ac3cf3.png)
![2020-01-05_1535_17](https://user-images.githubusercontent.com/34044886/71782471-0a42a980-2fd2-11ea-9d27-a44dd6ce0d91.png)

# Versions and configuration
 - OS: N/A
 - Game Version: Current master at fe0e3ded3c0801632951bd63fafa6c2cb7111e6f
 - Graphics version: N/A
 - Mods loaded: N/A

**Comment by wapcaplet** [comment]
The examples you provided look like legitimate clothing layer conflicts to me:

- knee pads and leg ammo pouch are both strapped to the legs
- boy shorts, compression shorts, and leggings are all worn next to the skin on the legs
- sports bra and compression top are both worn next to the skin on the torso

In your screenshots, the messages indicate why the items are in conflict - wearing multiple items on the same layer, on the same body part, is adding the extra encumbrance. My understanding of the clothing layer system is that's how it's supposed to work. Have I misunderstood, or am I missing something?

**Comment by ymber** [comment]
Yeah this is expected behavior for the current system. I want to improve the system so we've got better granularity in body part coverage and layers. Compression shorts are a bad example but we have some things that collide in the same layer that are normally worn together. The knee pads and ammo pouch shouldn't collide because theyre on different parts of the leg. I meant to handle this one before 0f but I got caught up with other things.

**Comment by Rivet-the-Zombie** [comment]
Maybe we could add separate segments for thigh, knee, and calf? Same for the arms, and maybe the torso (abdomen, chest, neck, back) so that your scarf wouldn't be trying to occupy the same space as your mouthguard &etc.

**Comment by hexagonrecursion** [comment]
knee pads and a leg ammo pouch no longer collide

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 0d43a6e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Graphical Overmap [Graphical_Overmap]
]

**Comment by NetSysFire** [comment]
Can confirm. Looks like it is fixed.
