### ISSUE TITLE
map::place_items() called with an invalid chance (500)

### ISSUE THREAD

**Issue by AMurkin** [CleverRaven/Cataclysm-DDA#36637]
# Describe the bug

<details>
<summary>Debug message(s) when traveling around the world.</summary>
<pre>
    debug_write_backtrace(std::ostream&)
    ??:?
    DebugLog(DebugLevel, DebugClass)
    ??:?
    realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    ??:?
    void realDebugmsg<int&>(char const*, char const*, char const*, char const*, int&)
    ??:?
    map::place_items(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, tripoint const&, tripoint const&, bool, time_point const&, int, int)
    ??:?
    map::place_items(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, point const&, point const&, bool, time_point const&, int, int)
    ??:?
    jmapgen_item_group::apply(mapgendata&, jmapgen_int const&, jmapgen_int const&) const
    ??:?
    jmapgen_objects::apply(mapgendata&) const
    ??:?
    jmapgen_objects::apply(mapgendata&, point const&) const
    ??:?
    mapgen_function_json::generate(mapgendata&)
    ??:?
    run_mapgen_func(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, mapgendata&)
    ??:?
    map::draw_map(mapgendata&)
    ??:?
    map::generate(tripoint const&, time_point const&)
    ??:?
    map::loadn(tripoint const&, bool)
    ??:?
    map::shift(point const&)
    ??:?
    game::update_map(int&, int&)
    ??:?
    game::update_map(player&)
    ??:?
    map::displace_vehicle(vehicle&, tripoint const&)
    ??:?
    map::move_vehicle(vehicle&, tripoint const&, tileray const&)
    ??:?
    vehicle::act_on_map()
    ??:?
Backtrace emission took 1 seconds.
src/mapgen.cpp:6401 [std::vector<item*> map::place_items(const items_location&, int, const tripoint&, const tripoint&, bool, const time_point&, int, int)] map::place_items() called with an invalid chance (500)
15:40:24.954 ERROR : src/mapgen.cpp:6401 [std::vector<item*> map::place_items(const items_location&, int, const tripoint&, const tripoint&, bool, const time_point&, int, int)] map::place_items() called with an invalid chance (500)
15:40:26.409 ERROR : src/mapgen.cpp:6401 [std::vector<item*> map::place_items(const items_location&, int, const tripoint&, const tripoint&, bool, const time_point&, int, int)] map::place_items() called with an invalid chance (500)
</pre>
</details>

# Steps To Reproduce

1. Travel around the world.

# Expected behavior

No debug messages.

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: LinuxMint; Description: Linux Mint 19.3 Tricia; Release: 19.3; Codename: tricia; 
- Game Version: 0.D-10189-gd2cb78a [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    "dda",
    "no_npc_food"
]

# Additional context

Debug message source line:
https://github.com/CleverRaven/Cataclysm-DDA/blob/9eb79751ab19faabd5a986c794a42d3bfd862518/src/mapgen.cpp#L5869

`"chance": 500` can be found [here](https://github.com/CleverRaven/Cataclysm-DDA/blob/731155a052eab6b9f83e5d34d13379a20f9246ca/data/json/mapgen/park.json#L349-L365).

[Docs](https://github.com/CleverRaven/Cataclysm-DDA/blob/13b78c9f170ce2011ec5da0ec07c2da07d6fa46f/doc/MAPGEN.md#2502-chance) describing a "chance" as **optional** one-in-??? chance to apply.

**Comment by Zireael07** [comment]
Why would one in 500 not be a valid setting? 😕

**Comment by AMurkin** [comment]
`map::place_items(...)` checks `if( chance > 100 || chance <= 0 )` to show this debug message.
So it's not one-in-??? it seems.

**Comment by Fris0uman** [comment]
So was it meant to be 1/500, meaning it should be changed to 1 to be rare, or was it meant to be very common stuff and should be changed to 100?
