### ISSUE TITLE
Custom loot zones attached to a vehicle do not work

### ISSUE THREAD

**Issue by Kelenius** [CleverRaven/Cataclysm-DDA#36652]
# Describe the bug

If you create a custom loot zone with a filter and attach it to a vehicle, items that are supposed to be placed into it are left untouched. They don't go into the zone they would go if the custom zone didn't exist, either.

# Steps To Reproduce

1. Get a vehicle with several cargo parts.
2. Set up an unsorted loot zone, a custom loot zone with filter "battery", and a spare parts loot zone.
3. Place some rags and batteries into the loot zone.
4. Sort out loot.

# Expected behavior

Rags would go into spare parts and batteries into custom. If the filter wasn't set properly, both would go into spare parts.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-10968-gfe0e3de [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Folding Parts pack [deoxymod],
    No Acid Zombies [No_Acid_Zombies],
    No Fungal Monsters [No_Fungi],
    Prevent Zombie Revivication [no_reviving_zombies]
]

# Additional context

In the attached save, there's a battery on the workbench, which is a zone for sorting out loot. It doesn't get sorted, despite there being a zone for the batteries and the spare parts.

[Franklinville.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4017420/Franklinville.zip)

**Comment by Fris0uman** [comment]
feel free to reopen if the bug re-appears
