### ISSUE TITLE
Segmentation fault when moving items to vehicle cargo carrier

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#36653]
# Describe the bug

Using the save file provided at the bottom, trying to put some items in the cargo just left of the character causes a segmentation fault, I think its different every time, so I don't think its a problem with any specific item, just the process of moving said items. I've tried moving items one item at a time, and still eventually got the seg fault.

Crash.log:
CRASH LOG FILE: config/crash.log
VERSION: 0.D-10922-gb1541cd
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x559EC6[cataclysm-tiles.exe+0x159EC6]
    @0x55A13E[cataclysm-tiles.exe+0x15A13E]
    SMPEG_error+0x3DAF3@0xCB16F5[cataclysm-tiles.exe+0x8B16F5]
    @0x72DC9D3
    GetProfileStringW+0x12DDF@0x771C03BB[kernel32.dll+0x503BB]
    RtlKnownExceptionFilter+0xB7@0x77825B57[ntdll.dll+0x75B57]
    RtlInitializeExceptionChain+0x36@0x777E98C5[ntdll.dll+0x398C5]

# Steps To Reproduce

1. Grab save file and launch its world
2. Use drop key to drop items directly to the left of character into vehicle cargo carrier
3. Use the keybind to "drop all" items that aren't favorites.
4. Notice there is a segmentation fault during the process of dropping your items into the vehicle.

# Expected behavior
Shouldn't get a seg fault when moving items
# Versions and configuration
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-10922-gb1541cd [32-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    No Fungal Monsters [No_Fungi],
    Disable Religious Texts [no_religious_Texts]
]
# Additional context
The save file will appear very small, it is just a cut-out from my main world which is a handsome 470 MB (I want that save file compression eventually lol)
[Mexia2.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4017497/Mexia2.zip)

**Comment by CoroNaut** [comment]
Maybe caused by #36554, just read that issue now.

**Comment by Unrepentant-Atheist** [comment]
Needs to be reopen. Because although I'm not getting a segfault, my game freezes completely, when dropping stuff into cargo carriers.
