### ISSUE TITLE
Talon UGV shoots for full damage through reinforced doors

### ISSUE THREAD

**Issue by glenmack** [CleverRaven/Cataclysm-DDA#36669]
# Describe the bug
Talon UGV shoots for full damage through reinforced doors

# Expected behavior
Reinforced glass doors should be stopping most of the damage, as per reinforced glass.

**Comment by TechyBen** [comment]
Is reinforced glass that strong? Though having it able to deflect 1 bullet, but then be rather flimsy after seems more akin to real life (IIRC reinforced glass can be made rather thick and well protected, but been a while since I've been on that specific Mythbusters binge XD ).

**Comment by Warriorcat49** [comment]
> Is reinforced glass that strong? Though having it able to deflect 1 bullet, but then be rather flimsy after seems more akin to real life (IIRC reinforced glass can be made rather thick and well protected, but been a while since I've been on that specific Mythbusters binge XD ).

Depending on what we mean by reinforced glass, there are many different types which can and will stop multiple rifle bullets. In-game though, it's supposed to halve damage I think, And two tiles of reinforced glass will completely stop up to 5.56, possibly more; I haven't actually tested with higher.

**Comment by scorpion451** [comment]
Wikipedia actually has pretty good numbers for true glass: https://en.wikipedia.org/wiki/Bulletproof_glass

Based on how many hits from a sledgehammer it can take, the stuff in the labs is probably toward the bottom of the list, where you go from how many shots it can stop and start looking at how big of an anti-materiel round it can stop.

**Comment by glenmack** [comment]
> Is reinforced glass that strong? Though having it able to deflect 1 bullet, but then be rather flimsy after seems more akin to real life (IIRC reinforced glass can be made rather thick and well protected, but been a while since I've been on that specific Mythbusters binge XD ).

I have since observed that it works both ways. I can shoot a talon, or any other monster through the reinforced door, as well. Tactically it's less interesting than having to open a door, and yes, "bullet resistant glass" should be cutting at least half the damage if not all.

Realism aside. The glass needs to stop some or all bullet damage. No one puts live-fire robots and turrets inside a scientific or military research facility. They never will. So if you're going to cut bullet resistant glass in labs for "realism" take out the live fire defences in labs too.

**Comment by molkero** [comment]
Shouldn't the glass at least break when shot through?
