### ISSUE TITLE
Belt Feed Adapter recipe is orphaned and unobtainable.

### ISSUE THREAD

**Issue by Solusphere** [CleverRaven/Cataclysm-DDA#36668]
The recipe of the small arms Belt Feed Adapter gunmod exists in the game's files, but is not autolearned and is not contained in any books, as seen here: 
http://cdda-trunk.chezzo.com/beltfeed/craft

This should either be autolearned, added to one or more of the gun recipe books, or the recipe removed from the game.

**Comment by VReaperV** [comment]
It's obsoleted, and is still there for backwards-compatibility.

**Comment by Night-Pryanik** [comment]
It will be removed after 0.E.
