### ISSUE TITLE
Add warning on unwielded grenade activation

### ISSUE THREAD

**Issue by Grubleafeater** [CleverRaven/Cataclysm-DDA#36665]
It's not entirely clear when activating a grenade that you should have it ready to throw before you activate it, which can lead to accidentally blowing yourself up because you think you have five turns to work with. It should be reasonably common sense in universe to have it ready to throw when you pull the pin;ergo, adding a warning when activating a grenade in pocket would make sense.

**Comment by TechyBen** [comment]
Perhaps make it as part of the action? "Activate and throw/activate and drop/activate..."
IRL pulling the pin alone does nothing, right, it has to be pull pin AND release the lever/throw (though some old German nades might work differently).

**Comment by l29ah** [comment]
In 0.E-8034-g73b5cf62a8 i couldn't throw a grenade without wielding it first.
