### ISSUE TITLE
Indication of base camp's "reserved footprint"

### ISSUE THREAD

**Issue by scorpion451** [CleverRaven/Cataclysm-DDA#36670]
**Is your feature request related to a problem? Please describe.**  
It is difficult to anticipate what tiles should be reserved for camp constructions in general, and what tiles a given improvement will alter.

This leads to issues like needing to relocate appliance rig-type vehicles because a structure wasn't where I expected it to be, or having piles of items end up inside of walls. (for instance, using (g)et thankfully allowed retrieval of all of my camp's tools from the corner of the new east room)

This also makes it difficult to know if it is safe to customize certain parts of a camp- say, can I safely build a few windmills near the room I've been using as a larder, or is there a chance that I'm accidentally obstructing a spot where something might be built in the future?

**Describe the solution you'd like**  
There's a couple ways to do this; the one I like best would be to have the survey activity do some sort of free or low-cost tile improvement that marks out future structure footprints, in an unobtrusive but obvious way. Something like regularly placed chalk or paint marks, or stakes stuck in the ground

**Describe alternatives you've considered**  
Even just a preview highlighting the area to be altered by a chosen improvement would be nice- say, centering the view over the spot, with highlight boxes ala zone placement.

**Additional context**  
This should also make the realists happy as well: this sort of thing is how real construction sites make sure that the port-a-potties don't get placed in the middle of where they're about to pour concrete, and designate the places where it's safe to pile up pallets of bricks that they don't want to have to move during the project.

**Comment by TechyBen** [comment]
I've known of fork lifts being left in the wrong place, and now behind some big machinery/walls and part of the "furniture" less someone disassemble them bit by bit... or an external wall. So yeah, in game also a nice feature.

**Comment by davidpwbrown** [comment]
Yeah this is something ill be working towards, with the camp upgrades placing appropiate construction zones, so the NPCs can work on them in real time, and you can mix and match with what you already have there, and the zones will show the footprint.

It stalled due to 0.E bugfixing, but I will be reapproaching this soon.
