### ISSUE TITLE
trying to heat up water in container consumes it directly instead

### ISSUE THREAD

**Issue by nullptr98** [CleverRaven/Cataclysm-DDA#36680]
# Describe the bug

getting close to a fire source and trying to heat up water will consume it directly without heating it up

# Steps To Reproduce

1. have a stock pot with clean water in it
2. hold the pot
2. stand near fire
3. open use item menu
4. choose heat up water
5. it will consume it directly instead of heating it.

![heat1](https://user-images.githubusercontent.com/50782363/71934766-6c073d00-31a5-11ea-913f-6a0742e62810.png)

![heat2](https://user-images.githubusercontent.com/50782363/71934773-745f7800-31a5-11ea-9fc2-0babc8e5d2a0.png)

![heat3](https://user-images.githubusercontent.com/50782363/71934786-7a555900-31a5-11ea-93aa-484abf1ccadd.png)

# Expected behavior

water inside the container should be heated up and not consumed.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-10977-g4a734f0 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

Updated to last build, problem still occurs.

# Additional information:

Items in inventory: default evacuate start, just spawned brazier, long sticks, and the stock pot.
I unloaded the water from the bottles into the pot, but it dosnt matter, tried filling the pot from a water dispenser, same thing

**Comment by ZhilkinSerg** [comment]
I cannot reproduce the issue in latest version. Please go into more details (which container did you use, what other items were in inventory, etc).

**Comment by nullptr98** [comment]
I updated the issue and reverified with lastest build, still occurs.
