### ISSUE TITLE
[CR] Discolored item names in the dark.

### ISSUE THREAD

**Issue by 8street** [CleverRaven/Cataclysm-DDA#36689]
**Is your feature request related to a problem? Please describe.**  
In darkness, in reality, objects are not visible well enough. I can make them discolor in game. How do you like it? I myself am not sure if this is worth doing, but it will give the game more realism.

**Describe the solution you'd like**  
Discolored item names in the very dark. All items color in the very dark becomes c_dark_gray color. In inventory, advanced inventory, pickup window, shif-v window and everywhere at all.

Code example, item.cpp:
```
nc_color item::color_in_inventory() const
{
    // TODO: make a const reference
    avatar &u = g->u;

    //if player in very dark then return dark color
    float light = u.fine_detail_vision_mod();
    if ( light >= 4.0f ) {
        return c_dark_gray;
    }
...

```

**Describe alternatives you've considered**  
Do nothing.

**Additional context**  
Before
![dis3](https://user-images.githubusercontent.com/30113229/71762913-c9219b00-2ee6-11ea-9662-43d7aee30298.png)

After in very dark
![dis4](https://user-images.githubusercontent.com/30113229/71762916-d3439980-2ee6-11ea-9c69-5a3eada9fcc3.png)

Please comment how do you like this?

**Comment by Zireael07** [comment]
Many characters have night vision from mutations so I assume "bad night vision" isn't a case for them.
Also I believe the colors in UI are a matter of quality-of-life, not actually seeing items?

**Comment by ZhilkinSerg** [comment]
Yeah, I don't think that inventory is something that you look at, but something that you know you have in your posession.

**Comment by 8street** [comment]
Well, in the dark, the player can neither read nor craft. Why can he easily pick up items?
I agree, we don’t touch the color in the inventory, advanced inventory. But I can change the colors in the pickup and shift-v window. More opinions?

**Comment by Ulysses2** [comment]
Yeah, the colored labels aren't actually representative of the item's color, but of its qualities. Like for instance, CBMs that you don't have yet are green. And it doesn't give you any information you didn't already have from the item's name, it's just a matter of convenience, so I don't see the point really.

**Comment by 8street** [comment]
![dis5](https://user-images.githubusercontent.com/30113229/71766017-4d3a4980-2f0c-11ea-8390-1eb921cfa2cd.png)
Well, can still pick up items by touch. Only selected is visible. Although this is probably really overkill.

**Comment by Zireael07** [comment]
Definitely overkill IMHO.

**Comment by 8street** [comment]
OK. The community does not need this. Closed.
