### ISSUE TITLE
Monsters don't spawn in 10113 and later

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#36690]
# Describe the bug

After updating to 10113 there are no zombies spawning, literally 0. Ones which are already on the map are fine, they don't disappear, but when I'm entering new overmap tiles there are no zombies whatsoever. Rolling back to 10112 fixes the issue.

# Steps To Reproduce

1. Load [the save](https://drive.google.com/open?id=1cxNB6nadSs4qnqiVKXIVYz0XEjcTlzJ7).
2. Drive east about 5 overmap tiles - till you approach the city.
3. See no zombies.
4. Even special encounter (mission currently selected which is in the same city) doesn't spawn military zeds that should *always* be there.

# Expected behavior

Zombies being spawned as usual.

# Versions and configuration

    OS: Windows 7 x64
    Game Version: 0.D-10984-ged9e547 (tiles)
    Graphics Version: Tiles
    Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills]
    ]

Also tried updating to 10115, same thing, no zeds.

**Comment by ZhilkinSerg** [comment]
Should be caused by #36690.
