### ISSUE TITLE
Extra hotplate should be removed from (vehicle part) chemistry lab

### ISSUE THREAD

**Issue by Ulysses2** [CleverRaven/Cataclysm-DDA#36695]
**Is your feature request related to a problem? Please describe.**  
The chemistry lab counts as both a chemistry set and a hotplate for purposes of crafting. As a result, every time you craft with it, you're asked whether you want to use the chemistry set or the hotplate.

**Describe the solution you'd like**  
The lab should only count as a chemistry set. The chemistry set can do everything a hotplate can, so there won't be any loss of functionality.

**Describe alternatives you've considered**  
There could be code to check when multiple nearby crafting stations are attached to the same vehicle, and if so, use one automatically. That would help if, say, you have both a chemistry lab and a kitchen unit. But I guess there could be edge cases where one of them gets removed and you aren't able to complete your in progress craft.

**Additional context**  
The recipe for the lab doesn't include an extra hotplate, it just has a chemistry set with a hotplate in it. Hence why you're able to use it to cook food and stuff.

**Comment by Ulysses2** [comment]
Also, looking at the json, it looks like the smashing result includes entries for both a chemistry set and a hotplate. I'm not sure if this means it's a 50/50 chance as to which one you get, or if you've got a 25% chance of getting both.

**Comment by Brian-Otten** [comment]
I had a look and as far i can see the item doesn't have the hotplate flag in json, only the "CHEMLAB" flag. I found no way to remove the hotplate ability from that flag in json so this might need to be done in c++.
