### ISSUE TITLE
Cable Charger CBM lacks effective power saving mode.

### ISSUE THREAD

**Issue by Solusphere** [CleverRaven/Cataclysm-DDA#36696]
**Is your feature request related to a problem? Please describe.**  
The cable charger is capable of drawing an extraordinary amount of power from a connected vehicle in very short order, even when a character's power storage is effectively at full. While the cable charger does feature an automatic cutoff, it only triggers when your internal power stores are at exactly 100%. This means that ANY ongoing bionic power draw, even the miniscule draw from an active leukocyte breeder, will cause the cable charger to drain power from the vehicle at an alarming rate, roughly a full storage battery's worth every hour.

**Describe the solution you'd like**  
The cable charger should shut off automatically when above a certain threshold, similar to other power-generating bionics, and not only when the batteries are entirely full.

**Describe alternatives you've considered**  
None that come to mind.

**Additional context**  

The power source:
![image](https://user-images.githubusercontent.com/19789267/71769123-e2aefb00-2f57-11ea-95b7-b5285aea1845.png)

My bionic power at test start:
![image](https://user-images.githubusercontent.com/19789267/71769133-05d9aa80-2f58-11ea-9976-777a77ce29d7.png)

The power source after waiting for half an hour with a leukocyte breeder turned on.
![image](https://user-images.githubusercontent.com/19789267/71769159-56e99e80-2f58-11ea-9847-5d566e43372a.png)

Attempting to turn on fuel-saving mode with the cable charger:
![image](https://user-images.githubusercontent.com/19789267/71769245-7c2adc80-2f59-11ea-956b-cd366284a550.png)

**Comment by kevingranade** [comment]
Ok so it's apparently drawing some large amount and discarding most of it if it doesn't have anywhere to store it.
