### ISSUE TITLE
Percieved character temperatures are lower inside buildings compared to outside

### ISSUE THREAD

**Issue by Dziugaske** [CleverRaven/Cataclysm-DDA#36692]
# Description

Under the same temperature and wind conditions, my character experiences 8 or so degrees lower temperatures inside buildings.

# Steps to reproduce the behavior:
1. Check temperature in player info while outside.
2. Check temperature in player info while inside a building.

# Expected behavior

Under the same temperature and wind conditions, I expected the same percieved temperature inside the building.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-10999-g9e6c9bf [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

![Temperature1](https://user-images.githubusercontent.com/42064096/71765244-c0d35b00-2efa-11ea-8896-9ac2dfc0128f.PNG)
![Tempetature2](https://user-images.githubusercontent.com/42064096/71765245-c335b500-2efa-11ea-814a-16b8793a80e8.PNG)

[New Harmony.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4021873/New.Harmony.zip)

**Comment by MLamor** [comment]
I might be mistaken (I haven't looked into the code)
But I assumed that the increase in heat when you go outside mid-day is from the sun.

On bright summer days my character will be hot outside, but warm indoors, at dusk and dawn it seems to be less of an issue.

**Comment by scorpion451** [comment]
Yep. Don't see anything weird here, just being in the shade vs being in the sun.
