### ISSUE TITLE
Aftershock Breaks Butchering For Zombies and Human Corpses

### ISSUE THREAD

**Issue by LordZanos** [CleverRaven/Cataclysm-DDA#36708]
# Describe the bug

All butchering options besides dissection do not provide intended components with Aftershock loaded. Instead, only butchering refuse is obtained regardless of option chosen, with dissection having a chance at retrieving titanium implants.

# Steps To Reproduce

1. Find or make human or zombie corpse.
2. Butcher it with quick or full butchering.
3. Examine yield.

# Expected behavior

Butchering options provide varying yields of meat/fat/bones/organs/etc depending on choice.

# Screenshots

# Versions and configuration

# Additional context

Likely caused by https://github.com/CleverRaven/Cataclysm-DDA/pull/36581

**Comment by Soup-de-Loop** [comment]
That's my bad, thank you for catching this one and the subsequent fix on it.
