### ISSUE TITLE
Guns of the same make isn't stacking

### ISSUE THREAD

**Issue by DillonSimeone** [CleverRaven/Cataclysm-DDA#36715]
# Describe the bug

![image](https://user-images.githubusercontent.com/21962421/71775784-82aa5b80-2f3b-11ea-80d3-88c03de9c0ec.png)

In the image above, you can see that some of my guns are stacking while others isn't. Toggling debug mode then comparing two of the guns that wasn't stacking reveals that both have very tiny foulings on them.

![image](https://user-images.githubusercontent.com/21962421/71775795-ac638280-2f3b-11ea-88fe-7124ed5b15e1.png)

# Steps To Reproduce

1. Debug in a few copies of the same gun, some magazines and a whole lot of ammo. You'll see that the guns will stack. 

2. Fire some bullets from one, then note that despite having no fouling displayed, the gun you used will not stack with other guns anymore.

# Expected behavior

Guns of the same make stacking despite having little enough foulings that it doesn't display in the inventory screen, because otherwise there's nothing else telling the player that those guns are different from each other. 

# Screenshots

![image](https://user-images.githubusercontent.com/21962421/71775869-986c5080-2f3c-11ea-9cc4-56ba80bd503e.png)

Having so many same guns not stacking makes it difficult to look though your piles of guns. 

# Versions and configuration

 - OS: Windows 10 
 - Game Version: O.D-11016-g91d7b51
 - Graphics version: Tiles
 - Mods loaded: 
  "dda",
  "no_npc_food",
  "magiclysm",
  "aftershock",
  "crt_expansion",
  "FIC_Weapons",
  "growable-pots",
  "ew_pack",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "nw_pack",
  "alt_map_key",
  "Cata++",
  "Mining_Mod",
  "my_sweet_cataclysm",
  "MMA",
  "vamp_stuff",
  "Arcana",
  "vamp_stuff+arcana",
  "more_locations",
  "No_Rail_Stations",
  "deoxymod",
  "blazemod",
  "Heavy miners",
  "Tanks",
  "necromancy",
  "Arts' Guns",
  "no_religious_Texts",
  "novitamins",
  "speedydex",
  "secronom",
  "stats_through_kills"

# Other

I've attached my savefile to this issue so you can quickly examine the guns. In the save, I have a bunch of guns sitting in my inventory, and there's even more guns south of the worktable in my car. 

[Forest Hills.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4022932/Forest.Hills.zip)

**Comment by wapcaplet** [comment]
Confirmed, and still an issue in 0.E-10095-g9a1187f549. Every foulable gun keeps an exact count of the number of bullets it has fired, and no guns will stack unless they have fired exactly the same number of bullets.

Here are 5 Glock 17 handguns that have each fired a different number of bullets between 0 and 5, on the ground:

![image](https://user-images.githubusercontent.com/238395/111848303-612f5880-88d0-11eb-8f66-f7b7c422ec88.png)

And in the inventory:

![image](https://user-images.githubusercontent.com/238395/111848344-73a99200-88d0-11eb-826a-648cd205da4e.png)

With debug mode turned on, one can see the "dirt" value that causes them not to stack:

![image](https://user-images.githubusercontent.com/238395/111848385-8e7c0680-88d0-11eb-8c23-4b398c0ebe6a.png)
