### ISSUE TITLE
Leaky turrets. Bullets falling out.

### ISSUE THREAD

**Issue by TechyBen** [CleverRaven/Cataclysm-DDA#36721]
# Describe the bug

Bullets leak out of turrets.

# Steps To Reproduce

Use a salvaged turret/gun with damage to it in a car/vehicle, reload it, see bullets fall on the floor as time goes by...

# Expected behavior

Bullets don't leak from turrets.

# Versions and configuration

 - OS: [Win7
 - Game Version: 10121
 - Graphics version: Tiles
 - Mods loaded: Some... Ah, is it modular turrets the cause? [edit] Removing the mod manually gets the same result in my save.

Might be as design, like a stang magazine with holes in it and all the bullets falling out. But kinda unintuitive if it is.

**Comment by ymber** [comment]
Haven't looked into this but I suspect the code for fuel to leak from tanks is being inappropriately applied to other vehicle containers.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-6416.
