### ISSUE TITLE
Emp Projector CBM uses energy during aiming phase

### ISSUE THREAD

**Issue by Ker-Nes** [CleverRaven/Cataclysm-DDA#36725]
# Describe the bug

Using the Emp Projector CBM uses the 50 kJ of energy every step used for aiming, not only when fired.

# Steps To Reproduce

1. Have the Emp Projector CBM installed.
2. Have enough bionic energy.
3. Activate it, pick a target and start aiming.
4. Observe that in you spent far more than 50 kJ of energy, directly proportional to the time you spent aiming.

# Expected behavior

Only spending 50 kJ of bionic energy, or at least some number that doesn't depend on time spent aiming.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-11025-g9fe2e72 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Bens GF recipes [Tolerate_This],
    Craftable Gun Pack [craftgp],
    Garden Pots [growable-pots],
    Gun Cotton [guncotton],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    DinoMod [DinoMod],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks],
    No Explosive Zombies [No_Explosive_Zombies],
    Manual Bionic Installation [manualbionicinstall],
    Safe Autodoc [safeautodoc],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Fris0uman** [comment]
Can't reproduce the bug.
Tried aiming for a long time and then cancelling > no power consumed
aiming a long time and then shooting > 250 kJ consumed each time no matter the time aimed

Maybe the emp projector should have a non auto firing mode
