### ISSUE TITLE
After death NPC reset to state as if they never met the characater before

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [CleverRaven/Cataclysm-DDA#36729]
# Describe the bug & # Steps To Reproduce

1. Die in a fight
2. Segfault after death
3. Restart game
4. Load game
4. NPC behave as if they met the character for the first time according to behavior and dialog options

# Expected behavior
Die, crash game, load saveame, continue normally with NPC's behavior as it was.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.D-11026-g7a023e4 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Nechronica Redux [Nechronica_Redux],
    Mutant NPCs [mutant_npcs],
    Psychiclysm [psychiclysm],
]

 - Game Version: [from the main menu, e.g. 0.C-29938-g90f5268437]
 - Graphics version: [Tiles or Terminal]
 - Mods loaded: [e.g.dda, boats, hacktheplanet, StatsThroughSkills]

# Additional context

Instead of segfault, can be forced by save scumming (for debug purposes? maybe), i.e. after death, 1st window alt+f4 out of the game, restart, and load game, same thing, NPCs behave as if they never met the player character ever

**Comment by anothersimulacrum** [comment]
I don't think this is the issue you say it is.
The NPC resetting to having never met you is what should be happening, crashing/your save being preserved after death is not.

**Comment by Night-Pryanik** [comment]
Continuing game after character death leads to all kinds of weird issues. We are not planning to fix them AFAIK.
