### ISSUE TITLE
Laser Weapons can Spawn with gunpowder fouling

### ISSUE THREAD

**Issue by Ker-Nes** [CleverRaven/Cataclysm-DDA#36731]
# Describe the bug

Laser weaponry can be found with gunpowder fouling 

# Steps To Reproduce

This one is a bit annoying to replicate, as it seems to only come up with "naturally spawning" rifles, you can't just spawn a bunch of laser rifles through the debug menu.

1. Have somewhere where laser rifles have a decent chance of spawning somewhere you know but outside your reality bubble and not yet "activated", so what will spawn there is not yet defined. Appropriate type of labs or military bunkers are a good option. 
2. Savescum until a laser weapon with fouling drops.

# Expected behavior

Laser weapons, not using gunpowder should not have gunpowder fouling. It could have a similar "wear and tear caused defect", perhaps something like the lens getting out of perfect alignment, or even just getting the lens dirty, but no matter which, they should a different way of mending those defects, and not need new lubrication.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-11025-g9fe2e72 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Bens GF recipes [Tolerate_This],
    Craftable Gun Pack [craftgp],
    Garden Pots [growable-pots],
    Gun Cotton [guncotton],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    DinoMod [DinoMod],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks],
    No Explosive Zombies [No_Explosive_Zombies],
    Manual Bionic Installation [manualbionicinstall],
    Safe Autodoc [safeautodoc],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

I already cleaned the laser rifle I found fouled before I remembered to open this bug report and so I lack a screen shot.

**Comment by anothersimulacrum** [comment]
What laser weapons?
This means that the laser weapons are missing the `NON-FOULING` tag, which means they can both foul and spawn with fouling. Adding this tag will prevent them from spawning with fouling, and from fouling.

**Comment by Ker-Nes** [comment]
The one I found fouled was the A7 Laser Rifle. From what I managed to search, I think it's still in the base game, and not been transferred to the mods?

**Comment by anothersimulacrum** [comment]
That shouldn't spawn with fouling, can you reproduce this again? I suspect that weapon was spawned before the patch to prevent it spawning with fouling was introduced.

**Comment by Ker-Nes** [comment]
> That shouldn't spawn with fouling, can you reproduce this again? I suspect that weapon was spawned before the patch to prevent it spawning with fouling was introduced.

Will try to do so in a day or so. But it was unlikely that it had spawned before that time, since I've started this game after the whole fouling system (including the laser not fouling) was merged. Found one A7 laser gun in a military bunker after finally finding (and getting) a military ID card, and encountered it fouled.

Will see if I can make it happen again with debuging a overmap edit and creating massive amounts of military bunkers to see if I can get a new one.

**Comment by Ker-Nes** [comment]
Aha, I still had a save backup from before actually breaking in the bunker, but after I went above ground very near to it, so it had already spawned. 
![laser](https://user-images.githubusercontent.com/37450179/71842629-d84c4880-30a0-11ea-8501-458fc3702984.png)

Will see if I can get it to happen in a new world too, but that might take a few days, as I'm probably going to have to make a few hundred new military bunkers appear, so that not only they have a laser weapon, but a fouled one.

**Comment by TechyBen** [comment]
Make it a feature not a bug? Change it to heat/ash/dust damage. A laser would have optics, and these would work better when clean. :)

**Comment by anothersimulacrum** [comment]
You don't clean optics  with a pipe cleaner though. Maintenance for laser and other weapons could be implemented, but it should be separate with fouling.

**Comment by TechyBen** [comment]
> You don't clean optics with a pipe cleaner though. Maintenance for laser and other weapons could be implemented, but it should be separate with fouling.

Oh, I agree on that point!
