### ISSUE TITLE
Localisation is glitching

### ISSUE THREAD

**Issue by eilaattwood** [CleverRaven/Cataclysm-DDA#36737]
# Describe the bug

After one of the recent updates (I jumped from build 10108 to build 10127) russian translation begun to glitch. Some of the strings are translated as before, but some are not translated anymore (but used to be translated in the previous version)

# Steps To Reproduce

1. Set game language to Russian
2. Create new world and new player
3. Check surrounding item names

# Expected behavior

All strings that are present in translation files should be translated in game.

# Screenshots

![test.png](https://user-images.githubusercontent.com/28134842/71786699-16048f00-3017-11ea-8f79-99c05c739613.PNG)

# Versions and configuration

 - OS: [Windows 10 x64]
 - Game Version: [0.D-11032-g7810b06]
 - Graphics version: [Tiles]
 - Mods loaded: [ "dda", "no_npc_food" ]

# Additional context

[savefile.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4024099/test.zip)

**Comment by anothersimulacrum** [comment]
I think it's more likely the names of those items were changed somehow and the translations for them were invalidated.

**Comment by Night-Pryanik** [comment]
Yes, exactly.

**Comment by eilaattwood** [comment]
> 
> 
> I think it's more likely the names of those items were changed somehow and the translations for them were invalidated.

Strange, this affected too random items... From different mods, from different categories...

> 
> 
> I think it's more likely the names of those items were changed somehow and the translations for them were invalidated.

Strange, because items from different categories and mods are affected. Wheels, regular books, scrolls from magiclysm... What recent PR changed ALL of them?

**Comment by Night-Pryanik** [comment]
I think this one - #36501?
