### ISSUE TITLE
CBM idea: Implanted Radio

### ISSUE THREAD

**Issue by cozardi** [CleverRaven/Cataclysm-DDA#36744]
**Is your feature request related to a problem? Please describe.**  
Not really a problem itself, just that a two-way radio is useful for dealing with NPCs, and an implanted two-way radio wouldn't be that hard to justify in-universe, being useful for soldiers not having to risk equipment getting damaged and civilians for being convenient and (mostly) non-invasive (maybe used as a walkie-talkie by industrial cyborgs, or as a way to call people without needing to take out their phone).
Also, useful for diluting the pool of must-have CBMs with some situationally-useful ones.

**Describe the solution you'd like**  
A CBM that acts as a two-way radio when activated, description could say something about a small speaker being implanted inside the ear, picking up the user's speech through skull vibrations / a microphone inside the user's throat (though, this last one sounds a bit more dangerous to implant) and a flexible antenna under the user's scalp.

**Describe alternatives you've considered**  
Not adding the CBM.
Having this be a part of the bionic hearing CBM.

**Comment by Amoebka** [comment]
Having low-value bionics that duplicate dirt common items will become pointless when bionic slots get mainlined. Nobody would want to waste precious head slots for the ability to not carry an actual radio with them.

The functionality should probably be given to another low-impact head bionic. I think Remote Controller would be a much better fit than Enhanced Hearing, though.

**Comment by TechyBen** [comment]
> Having low-value bionics that duplicate dirt common items will become pointless when bionic slots get mainlined. Nobody would want to waste precious head slots for the ability to not carry an actual radio with them.
> 
> The functionality should probably be given to another low-impact head bionic. I think Remote Controller would be a much better fit than Enhanced Hearing, though.

To be fair though, I could see swappable chips/slots/multifunction being there in the future though. IRL we have mobile phones that cover like 99% of compute and communication abilities, yet these CMBs have trouble doing 1 thing let alone 2 or 3. ;)

**Comment by davidpwbrown** [comment]
When bionic slots are enforced,  Id like to think that very small CBMS like an implanted subdermal radio That uses something like https://en.wikipedia.org/wiki/Subvocal_recognition would be entirely feasible and take up veyr little in the way of slots. Whether the *player* would find that a worthwhile tradeoff for the slots it takes up, is a moot point when it comes to whether something was produced in the in-game lore.

For example, if there was a CBM that enabled someone to detect bombs with their sense of smell, that would be probably of limited value to the player but was perhaps a specialised CBM in a niche use case in the pre-cataclysm world, dosnt mean it shouldnt exist.

This kinda thing would also perhaps be part of a wider multi-use special-forces type implant that combined it with a tactical computer or some other such fluff, that together made sense as an implant.

**Comment by Amoebka** [comment]
The problem is a lot of these smaller CBMs, like radio, RC, clock, etc, aren't believable as stand alone implants. Would anyone really design a microchip that requires special equipment to install under full anesthesia, and only put alarm clock on it even though they could have just as easily put the entire smartphone package there? Would anyone buy such a CBM in-universe?

**Comment by davidpwbrown** [comment]
CBM alarm clock sure , thats silly. but CBM radio and RC would have specific yet niche uses, where people in the military or media or sports or w/e would feasibly pay to have one implanted.

**Comment by tenmillimaster** [comment]
>Having low-value bionics that duplicate dirt common items will become pointless when bionic slots get mainlined. Nobody would want to waste precious head slots for the ability to not carry an actual radio with them.

If there's a market for the implant, it should exist, **regardless of whether or not post apocalyptic cata players will find it useful**.

If you thought it was nifty to have an alarmclock, implanted headphones, and UHF/VHF radio installed pre-cataclysm, and then found some nifty CBM and can't easily stick it in now... them's the breaks.

**Comment by 1n17** [comment]
>If you thought it was nifty to have an alarmclock, implanted headphones, and UHF/VHF radio installed pre-cataclysm

Thing is, those are incoherent and unrealistic as well. Considering tech level required for mere existence of things like eg. enhanced memory banks or repair nanobots, idea of simultaneously having this atomized implant systems that would be more at home in any C-tier scifi flick from the 60's seems quite ill conceived.

And even tech level aside, in any scenario extrapolating contemporary trends one can safely assume primary commercial application for civilian market would be smartphone type implant including all relevant features (ie. in game terms alarm/watch, radio, camera, music player, games), and likely a deluxe version also featuring augmented reality (ie. tactical overlay, audio and visual enhancing) and short range coms. Similarly things like leukocyte breeder, adrenal pump and sleep aid thingie would also be a package deal, and likely require 'smartphone' implant to interface with and function at all.

**Comment by tenmillimaster** [comment]
>Considering tech level required for mere existence of things like eg. enhanced memory banks or repair nanobots, 
Things in game do not justify things not in game. Those items do not appear to be supported by the design docs, and are thus candidates for deletions.

An implanted alarm clock is essentially a bluetooth configurable casio watch, probably with a tiny vibration motor or buzzer near the user's ear, and some rudimentary haptic controls. Likely of use to procrastinators, heavy sleepers, etc... Or any profession that uses timers *a lot*. 

Implanted headphones would basically be cochlear implants or other such hearing aid devices, but with bluetooth input. 

Considering that UHF/VHF transceivers are available on system-on-a-chip format, an implanted two-way radio would just have that, some power circuitry typical of other cbms, and the electronics to support bone conduction headphones ( a driver mounted on a bone, basically, or in close contact behind the ears), and subdermal throat microphone, some control logic for station IDs/memory+protocols and perhaps SSB/CW/FM modes if you wanna get fancy, wouldn't be too difficult. You could again use some sort of haptic interface for latch/PTT/mode settings. A typical antenna for this kind of handheld radio doesn't need to be very large, so a ~6" one at the hip or leg would work fine for talking to a nearby repeater.

Mundane items have less chance of becoming obsolete and needing to be replaced quickly, better reliability, and better chance of getting FDA approval. They're also less intensive in the number of hoops they need to get through to make it past the 'reasonableness' metric of CDDA implementation.

People implant magnets in their fingers for an 'extra' sense, IRL. That's incredibly mundane. You really don't think someone would want always-present headphones, or a timer/stopwatch that cannot be lost and cannot beignored?

Mundane CBM

**Comment by ashGlaw** [comment]
I would assume the low end cbms are geared toward a low end market. The expensive ones do a lot, but you could have cheap stuff too. I can’t imagine the radio implant would cost more than $20k with installation, probably a fraction of that
