### ISSUE TITLE
Weapon Duplication 

### ISSUE THREAD

**Issue by TaxVEVO** [CleverRaven/Cataclysm-DDA#36742]
Weapon Duping (Build 10121)

1. Drop Sheath/Scabbard (anything that can hold a melee weapon) with melee weapon inside of it
2. Wield the sheath/scabbard and pull the weapon out of it. 
A duplicate weapon will be in your hand and the original will still be inside of the thing you left it in.

**Comment by TaxVEVO** [comment]
the sheath has to put you over your normal volume so you cant carry it in your inventory 
and you have to examine it and get the prompt to take the weapon out
taking the weapon out should duplicate whatever was in your sheath 
unsure why this happens
screenshot (hopefully) shows the dupe in action
![screenshotofdup](https://user-images.githubusercontent.com/59544614/71788729-847f2800-2fea-11ea-9703-6f15be9fe83c.PNG)

**Comment by Grubleafeater** [comment]
Tested against 10090--Doesn't work, you're prompted to drop the sheathe instead of drawing from it.
