### ISSUE TITLE
Cannot scroll through item description without dedicated PgUp/PgDn keys on my keyboard

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#36751]
# Describe the bug
I cannot use my laptop's keyboard to scroll up and down on the description of an item. The Page Up and Page Down keys on my laptop are on the numpad, and I'm expected to turn numlock off if I want to page up or page down in other applications.

# Steps To Reproduce

1. Purchase an [Acer Aspire 5 laptop](https://www.amazon.com/Acer-i5-8265U-Keyboard-Fingerprint-A515-54-51DJ/dp/B07TJ21K7T) or any other laptop with [this sort of keyboard layout](https://images-na.ssl-images-amazon.com/images/I/71qkRXb-6VL._AC_SL1500_.jpg). Page up and Page down are on the Numpad 9 and Numpad 3 keys respectively.
2. Note that you cannot scroll through the item descriptions in-game.
3. **Workaround:** Use the on-screen keyboard to press page up and page down.

# Expected behavior
I wanted to be able to turn numlock off and scroll through the item descriptions without resorting to the on-screen keyboard.

# Screenshots
N/A

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.D-11046-gb0160b4 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    No Rail Stations [No_Rail_Stations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Classes and Scenarios Mod [more_classes_scenarios],
    Simplified Nutrition [novitamins],
    No Ants [No_Anthills],
    No Fungal Monsters [No_Fungi]
]

# Additional context
Alternatively, this could probably be fixed by giving me the ability to remap those keys. I searched for the ability to do that and couldn't find it. If you know what these entries are called in the keymap menu, this is likely not going to be an issue - I can just remap the appropriate keys in that case.

**Comment by Ramza13** [comment]
This is a known issue #28012

**Comment by Inglonias** [comment]
Ah. Whoops.

I was just able to find the keybindings menu for this. I needed to invoke the keybind menu from the item examine menu.
