### ISSUE TITLE
Foldable turret mount becomes unfoldable with gun attached

### ISSUE THREAD

**Issue by Shodan14** [CleverRaven/Cataclysm-DDA#36757]
# Describe the bug

You can now make a foldable vehicle with a turret mount. When you add a gun to that turret, it becomes unfoldable, making this change much less useful.

# Steps To Reproduce

1. Spawn foldable light frame, turret mount and M4A.
2. Assemble the items.
3. The game tells you that the new vehicle will become unfoldable.

# Expected behavior

At least some smaller guns should be foldable with the makeshift turret.

# Screenshots
![Untitled](https://user-images.githubusercontent.com/38443078/71838408-6801ef00-30c1-11ea-9e6d-2ac70de11f3c.png)

# Versions and configuration

- OS: Windows
    - OS Version: Windows 10.0 1909
- Game Version: 0.D-11030-gbce06b8 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    No Rail Stations [No_Rail_Stations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Disable Religious Texts [no_religious_Texts],
    No Antique Firearms [no_olg_guns],
    No Flaming Weapons [no_flaming_weapons],
    No Ants [No_Anthills],
    Classes and Scenarios Mod [more_classes_scenarios],
    No Filthy Clothing [no_filthy_clothing],
    Safe Autodoc [safeautodoc],
    Simplified Nutrition [novitamins]
]

**Comment by ymber** [comment]
This was intended behavior when I made turret mounts foldable. Whether it's the correct behavior for all turrets is debatable. I was thinking of M2s and Mk19s when did it and they didn't seem feasible to integrate into a small foldable design.

**Comment by Shodan14** [comment]
> 
> 
> This was intended behavior when I made turret mounts foldable. Whether it's the correct behavior for all turrets is debatable. I was thinking of M2s and Mk19s when did it and they didn't seem feasible to integrate into a small foldable design.

Ok, good to know. I was going to use it to make custom portable turrets with turret control unit, vehicle controls, a battery, a solar panel and a laser. Any chance you're willing to make some smaller mounted weapons foldable?

**Comment by Ker-Nes** [comment]
> 
> 
> > This was intended behavior when I made turret mounts foldable. Whether it's the correct behavior for all turrets is debatable. I was thinking of M2s and Mk19s when did it and they didn't seem feasible to integrate into a small foldable design.
> 
> Ok, good to know. I was going to use it to make custom portable turrets with turret control unit, vehicle controls, a battery, a solar panel and a laser. Any chance you're willing to make some smaller mounted weapons foldable?

You could just dismount the gun before folding and carry in two "packs" too. Dismounting a weapon from a turret mount should take nearly negligible time.

**Comment by Shodan14** [comment]
> 
> 
> > > This was intended behavior when I made turret mounts foldable. Whether it's the correct behavior for all turrets is debatable. I was thinking of M2s and Mk19s when did it and they didn't seem feasible to integrate into a small foldable design.
> > 
> > 
> > Ok, good to know. I was going to use it to make custom portable turrets with turret control unit, vehicle controls, a battery, a solar panel and a laser. Any chance you're willing to make some smaller mounted weapons foldable?
> 
> You could just dismount the gun before folding and carry in two "packs" too. Dismounting a weapon from a turret mount should take nearly negligible time.
Thanks, yeah, that's the plan for now. I guess I'll also mess around with the modular turrets mod.

**Comment by ymber** [comment]
Smaller turrets are mod content so the maintainer of whichever mod they're from would have to update them but folding something with a mounted carbine does seem reasonable.

**Comment by Shodan14** [comment]
> 
> 
> Smaller turrets are mod content so the maintainer of whichever mod they're from would have to update them but folding something with a mounted carbine does seem reasonable.
Yeah, like fold it around the gun. It can take up a bunch of volume, just let me pick that sucker up.
