### ISSUE TITLE
Cold Pressing Oil from Seeds through the power of Wind

### ISSUE THREAD

**Issue by Ker-Nes** [CleverRaven/Cataclysm-DDA#36754]
**Is your feature request related to a problem? Please describe.**  
The recipe for making vegetable cooking oil not only is highly inferior to the animal cooking oil, with the batches of 1 vs batches of 16 and no batch time saving like animal cooking oil has. This is realistic for a manual process of pressing oil from seeds with generic tools, but it's still annoying.

**Describe the solution you'd like**  
We already have implemented wind mills for milling flour from grain. Cold pressing, as pretty much just a repetitive mechanical process (at least the actually laborious and time consuming part of the process), there's no reason why the same process couldn't be implemented for vegetable oil. 

Taking the appropriate seeds (possibly after a shorter "treatment" through a recipe involving water and heat, to even be done in large batches, as this is just washing, drying and putting it through a minor heat treatment), putting them in a mill (possibly a different type of mill than the currently existing one, as the mechanisms are rather different than what you need for grinding grain into flour) alongside a container (or assume it already has a inbuilt container, like the fermenting vat, and just need afterwards a container for collecting the pressed oil), and waiting. 

**Describe alternatives you've considered**  
Two main alternatives: 
One would be implementing a dedicated hand tool, like a screw press, that would allow one to make vegetable oil in larger batches, or at least with batch time savings. Something like this: https://www.aliexpress.com/popular/manual-oil-press.html

The other would be having a electrically driven (hydraulic) press to be mounted in vehicles, to represent modern industrial cold pressing equipment like the smaller options between these: https://www.alibaba.com/countrysearch/CN/cold-press-mill.html

The latter is not particularly attractive, at least without creating the equivalent for milling flour too, as keeping consistency in how we implement these options is probably a good idea. The first might actually be a good idea even if we implement the cold press wind mill, as it's mostly adding a new item and creating a new recipe, which I feel that might be easier than messing with the windmill code. 

**Additional context**  
https://davehakkens.nl/projects/wind_oil/
https://www.researchgate.net/publication/329993761_Cold_press_in_oil_extraction_A_review
https://www.britannica.com/science/oil-extraction#ref118270

**Comment by davidpwbrown** [comment]
This is a good idea.

**Comment by TechyBen** [comment]
A cold press also has other uses, right? So as well as making oil, other food (etc) products could use it in recipies.
