### ISSUE TITLE
Repairing uncraftable armor/clothes is currently too hard

### ISSUE THREAD

**Issue by Brian-Otten** [CleverRaven/Cataclysm-DDA#36761]
# Describe the bug
Repairing of uncraftable armor/clothes is not reasonably possible for most/all players, even with endgame skills.

# Steps To Reproduce
Spawn army pants/sheriff shirt/ rollerblades/ other uncraftable armors.
Set tailoring to 8.
Try to refit/repair clothes with tailor kit
See that the success chance is for repair/refit is 0% or far lower than than the damage chance.

# Expected behavior
Uncraftable clothing repair chance is based on the material it is made from. This would keep repairs in line with what your character could craft. Alternatively reduce the difficulty slightly so endgame characters can repair their sentimental value sheriff shirt.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-11048-g8ad1db2 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Craftable Gun Pack [craftgp],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    EZ-Mode Medical [fast_healing],
    No Rail Stations [No_Rail_Stations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Roadheader and other mining vehicles [Heavy miners],
    No Acid Zombies [No_Acid_Zombies],
    No Explosive Zombies [No_Explosive_Zombies],
    No Fungal Monsters [No_Fungi],
    Safe Autodoc [safeautodoc],
    Manual Bionic Installation [manualbionicinstall],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]

**Comment by anothersimulacrum** [comment]
So, what's happening here is that items without a recipe have their recipe difficulty difficulty set to 10 - this is new after #36700, even though the comment says that it was set to 10, it was actually set to 5.

**Comment by 1n17** [comment]
Quick glance with blame shows that value was changed between dbf9aeb85dd1bc00edbd666b7f723850a044b341 and b70a6a456456070ae47a692933d80f5ee5d786dd without updating comment about difficulty.

**Comment by anothersimulacrum** [comment]
With `repairs_like`, I think we should keep it at 10 and add a `repairs_like` to the things that are too difficult.

**Comment by 1n17** [comment]
So - vast majority of uncraftable items. That would be fine in theory and perhaps a good long term goal, but in the meantime it leaves almost every uncraftable item unrepairable. Then there is the issue of NO_REPAIR flag existence.

**Comment by Brian-Otten** [comment]
So that pr should hopefully fix it and it only took a bit of blood sweat and tears.
