### ISSUE TITLE
Libraries in science labs are woefully understocked

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#36784]
**Is your feature request related to a problem? Please describe.**  
Since #36096 was merged, the libraries in science labs are astonishingly barren by comparison to civilian libraries. A single library in a town can provide a survivor with more or less a complete set of skillbooks.

**Describe the solution you'd like**  
Update the libraries in science labs with SUS spawns, if possible.

**Describe alternatives you've considered**  
In all seriousness, labs are already pretty stuffed with goodies. Not sure if balance is a concern here, but it could be worth considering.

**Additional context**  N/A

**Comment by ymber** [comment]
The libraries in cities are overstocked really. We could do with some larger central library maps and academic libraries in educational institutions along with substantially increasing book variety so we can have realistic book distributions.

**Comment by Jerimee** [comment]
I'm working on books in general. Let me know if you have ideas for books and I might be able to add them.

**Comment by glenmack** [comment]
> I'm working on books in general. Let me know if you have ideas for books and I might be able to add them.

More variety and coverage of skill levels would be interesting and not need recipes, Stuff like biology books teaching first aid, physics books teaching electronics (low levels), knitting books for tailoring.

By coverage I mean levels 2-4 or 3-5, 1-2, rather than the low-mid-high pattern of 1-3, 3-6, 6+
