### ISSUE TITLE
Vanishing wreckage

### ISSUE THREAD

**Issue by Alterforce** [CleverRaven/Cataclysm-DDA#36783]
# Describe the bug

Wreckage suddenly appears if approached from the west and disappears if sufficiently far away.

# Steps To Reproduce

1. Find wreckage
2. Approach it from the west
3. Observe how it pops in and out of reality when the player goes near and away from it

# Expected behavior

Wreckage does not disappear or suddenly appear from view when approached from the west.

# Screenshots

![vanishing wreck 1](https://user-images.githubusercontent.com/43394039/71901080-1d07da80-319a-11ea-83a7-bb6af3163625.png)
Wreck is missing

![vanishing wreck 2](https://user-images.githubusercontent.com/43394039/71901125-33159b00-319a-11ea-94e0-4dcd1c4d7fc0.png)
Wreck suddenly materializes

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-11048-g8ad1db2
 - Graphics version: Tiles
 - Mods loaded:
![vanishing wreck mods](https://user-images.githubusercontent.com/43394039/71901183-61937600-319a-11ea-904e-cd3c5045dda5.png)

# Additional context

Wreckage does not suddenly appear or disappear when approached from north or east.  South is unknown.

Save file: 
[CDDA Vanishing Wreck.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4030975/CDDA.Vanishing.Wreck.zip)

**Comment by kevingranade** [comment]
From the symptoms the owning submap might not be aw t the center point of the vehicle any more.

**Comment by int-ua** [comment]
Removing the `Bug` label until a fresh confirmation.

**Comment by OliveChukar** [comment]
Tested in ver 0.E-9111-gd1e702b-dirty. With the save from original issue the odd vehicle thing happened exactly as shown in the screenshots.  I have no idea how to reproduce this thing in a fresh world so i did not try.

**Comment by int-ua** [comment]
Thank you, @OliveChukar! Not assigning `Bug` label because it may be very hard to reproduce creating such wreckage and it _may_ be required to understand what caused this for fixing. IMHO it requires either a reliable way to reproduce from scratch or at least a second occurrence.

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
