### ISSUE TITLE
Makeshift Earplugs

### ISSUE THREAD

**Issue by chaoticidealism** [CleverRaven/Cataclysm-DDA#36788]
**Is your feature request related to a problem? Please describe.**  
Earplugs are handy for ignoring distractions while reading, crafting, etc. when you know you are in a safe place. But finding them is a matter of luck.

**Describe the solution you'd like**  
We need a makeshift earplug recipe. Have the ingredients be cotton balls or rags or plastic bags--you're basically just stuffing things into your ears so you can read in peace. Maybe they don't protect your hearing as well as regular earplugs, but they'll at least deafen you so you can concentrate on learning how to cook haggis.

**Describe alternatives you've considered**  
Constantly ignoring sounds when you're in a safe place and trying to perform an extended action is so annoying I usually resort to cheating in some earplugs.

**Comment by Ramza13** [comment]
It's not make shift earplugs but #36786 might give you what you want.

**Comment by Ker-Nes** [comment]
Not even makeshift, but there's no reason why the player might not be able to craft earplugs from wax, even if of a type that probably should get damaged when removed, to represent them being somewhat disposable. It's not even a difficult recipe, being just a small lump of wax that you mold with your fingers to properly fit the contours of your ear after putting it there.

**Comment by Amoebka** [comment]
Noise cancelling headgear is easily craftable and has the same functionality.

**Comment by ZhilkinSerg** [comment]
As already mentioned, we have craftable noise cancelling headgear.
