### ISSUE TITLE
Friendly nurses don't do anything useful

### ISSUE THREAD

**Issue by Kelenius** [CleverRaven/Cataclysm-DDA#36791]
# Describe the bug

I have a friendly nurse that tells me she'll assist me in surgery and wants to give me a check-up, but doesn't actually do anything.

# Steps To Reproduce

1. Load the attached save.
2. Try to get a check-up from the nurse to no avail.
3. Check the CBM installation success chances, disable the nurse and check them again.

# Expected behavior

The nurse should improve the success chance and give check-ups.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-11071-g91c47b0 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Folding Parts pack [deoxymod],
    No Acid Zombies [No_Acid_Zombies],
    No Fungal Monsters [No_Fungi],
    Prevent Zombie Revivication [no_reviving_zombies]
]

# Additional context

I'm pretty sure it's not a defective nurse. She's not trying to remove my CBMs, she says she'll assist me, and the effect even appears on my character panel, but nothing is happening.

The nurse was deployed from an item, if that matters.

[Franklinville.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4031784/Franklinville.zip)

**Comment by glenmack** [comment]
I heard Vormithrax say that they will show you your exact hit points, and they're supposed to help with CBM installs, but I've never seen anything like that with either deploying them from an inactive state, or reprogramming them via Control Laptop.

**Comment by Fris0uman** [comment]
`installer.get_effect_int( effect_assisted )` returns 1 instead of the expect 3 which makes the bonus insignificant.
Also either the formula has changed or my initial calcutions were wrong but it seems that +3 would not do much either.

**Comment by Fris0uman** [comment]
There is indeed a problem with the check up special attack, the cooldown is too long basically. Will push a fix soon
