### ISSUE TITLE
book_learn optional third entry does nothing?

### ISSUE THREAD

**Issue by Jerimee** [CleverRaven/Cataclysm-DDA#36790]
# Describe the bug

Locally, I added a cookbook cookbook_liverforkids. I then added the following line to the foie_gras result of offal_dishes.json:

`"book_learn": [ [ "mag_cooking", 4 ], [ "mag_glam", 5 ], [ "cookbook_liverforkids", 5, "Buttery Duck Bites" ] ]`

The recipe can be learned from the book in game, but the display shows no mention of "Buttery Duck Bites"

# Steps To Reproduce

1. Add a third entry to book_learn identifier.
2. Wish yourself the book using the debug.
3. Read/view the book. There is no mention of the string added in step one.

# Expected behavior

From the doc in JSON_INFO it reads: "The optional third entry defines a name for the recipe as it should appear in the books description"

I took this to mean that the book description would display the recipe as specified in the third entry string. It displays it as the result instead.
![cdda-liver](https://user-images.githubusercontent.com/2730677/71916266-975d3e00-314b-11ea-9034-52138a238317.png)

# Screenshots

# Versions and configuration

n/a

# Additional context

at JSON_INFO.md#recipes it reads:

```
"book_learn": [              // (optional) Array of books that this recipe can be learned from. Each entry contains the id of the book and the skill level at which it can be learned.
    [ "textbook_anarch", 7, "something" ], // The optional third entry defines a name for the recipe as it should appear in the books description (default is the name of resulting item of the recipe)
    [ "textbook_gaswarfare", 8, "" ] // If the name is empty, the recipe is hidden, it will not be shown in the description of the book.
],
"difficulty": 3,             // Difficulty of success check
```

```
[ "textbook_anarch", 7, "something" ], // The optional third entry defines a name for the recipe as it should appear in the books description (default is the name of resulting item of the recipe)
```

But the optional third entry doesn't appear to do anything...

In recipe.cpp the only of mention of book_learn is:

```c++
    if( jo.has_member( "book_learn" ) ) {
        booksets.clear();
        for( JsonArray arr : jo.get_array( "book_learn" ) ) {
            booksets.emplace( arr.get_string( 0 ), arr.size() > 1 ? arr.get_int( 1 ) : -1 );
        }
    }
```

And in fact it appears that that is the only mention in all of src. 

So is the third optional entry deprecated? WIP?

**Comment by Night-Pryanik** [comment]
Yeah, seems like either it was never implemented or was removed for some reason.

**Comment by Jerimee** [comment]
I thought it was a nice feature, but clearly not a necessity. Should I close this issue and add it to a feature request? Or is there some way to just convert this into a feature req?

**Comment by Night-Pryanik** [comment]
It's fine as it is.

**Comment by BevapDin** [comment]
This feature was removed by b70a6a45, no idea why.

**Comment by Jerimee** [comment]
This issue is still open right? 

If there is a decent hope of this feature being restored I'll continue to populate the field.

**Comment by kevingranade** [comment]
There is, it's a nice feature and it shouldn't be hard to re-add.

**Comment by esotericist** [comment]
Reopening, as a discrepancy between documentation and game code to the extent of "feature described does not actually exist" is absolutely a bug.
