### ISSUE TITLE
Let me mark obstacles for the overmap auto walk feature

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#36792]
**Is your feature request related to a problem? Please describe.**  
The auto walk feature over the overmap is nice, but some of the map extras that can be spawned are radioactive, or actively shooting at me, or filled with bionic zombies and I don't feel like walking through those.

**Describe the solution you'd like**  
Add the ability to mark a tile that I've put a map note on as "hazardous". If the pathfinder hits a hazardous square, route around it. Bonus points if we can set a radius around it to avoid as well.

**Describe alternatives you've considered**  
N/A. This is an enhancement reqiest

**Additional context**  
N/A

**Comment by davidpwbrown** [comment]
Can do this.
