### ISSUE TITLE
Webbing belt does nothing

### ISSUE THREAD

**Issue by Kelenius** [CleverRaven/Cataclysm-DDA#36814]
# Describe the bug

Wedding belt is a clothing item that has 0% coverage, 0 warmth, no storage, and can't be used for anything.

# Expected behavior

It should do _something_, be it 5% coverage, 5 warmth, storage, holster, or something else.

# Screenshots

![изображение](https://user-images.githubusercontent.com/6681708/71973503-2a67a800-3220-11ea-9724-ce1d6e72cb7c.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-11091-g44b584e [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by TechyBen** [comment]
I am now probably on some list after googling that... but yeah. It's a belt. So either as the current leather belt, or as a tool holding/etc belt would be nice.

**Comment by ymber** [comment]
0% coverage is an oversight. Really it should be usable as something to attach things to but currently holsters and sheaths and such can be worn without being attached to anything so we don't reflect this well.

**Comment by Brian-Otten** [comment]
Perhaps have it come equipped with 2 pouches for magazines? it can function like a findable of the chest ammo pouch. Add "There are 2 pouches for a magazine clipped to the belt". and give it slightly higher encumbrance than the chest ammo pouch.

**Comment by l29ah** [comment]
Still does nothing.

**Comment by ynemo** [comment]
+1
