### ISSUE TITLE
Segfault upon loading a save

### ISSUE THREAD

**Issue by killwort** [CleverRaven/Cataclysm-DDA#36824]
# Describe the bug
Game crashes with segfault right after loading provided savegame.

# Steps To Reproduce

1. Load the savegame, reproduced in 0.D-10749-gc886711 and 0.D-11091-g44b584e with chesthole16 and undeadpeople tilesets.
2. No further action required, game crashes right after rendering initial frame.

# Expected behavior

Game should not crash :)

# Versions and configuration
 - OS: Windows 10
 - Game Version: 0.D-10749-gc886711 and 0.D-11091-g44b584e 
 - Graphics version: Tiles
 - Mods loaded: Refer to save

# Additional context

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4036633/default.zip)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4036634/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4036635/crash.log)

**Comment by ZhilkinSerg** [comment]
![image](https://user-images.githubusercontent.com/16213433/72004302-2bb6c600-325c-11ea-985c-fa19f6cd196a.png)

**Comment by killwort** [comment]
Replacing ACT_HEATING with ACT_NULL in .sav file actually allowed to load save.
