### ISSUE TITLE
AT4 is reloadable

### ISSUE THREAD

**Issue by Phenomphear** [CleverRaven/Cataclysm-DDA#36830]
The AT4 can be reloaded if the player has 84mm rounds. The AT4 is a disposable launcher and can not be reloaded IRL

I'm actually not sure how to make it disposable. The AT4 is a "copy-from" the LAW, so I assumed it would just work the same but yet the AT4 can be reloaded.

**Comment by Brian-Otten** [comment]
Let me quote the flavor text for the ammo used in the at4:
"A 84x246mm High Explosive anti-personnel round for the Carl Gustav M3 recoilless rifle. Designed to be highly effective against personnel."
I think we can safely rename the AT4 into the Carl Gustav M3 and call it a day. If you want you could adjust it's weight to the real life 22 pounds as well, but gun weights are already slightly iffy across the board so not perse needed.
