### ISSUE TITLE
40mm Pipe Launcher has zero range (Cannot fire)

### ISSUE THREAD

**Issue by Benny-Bear** [CleverRaven/Cataclysm-DDA#36831]
# Describe the bug

The 40mm Pipe Launcher underbarrel gun mod has zero range with launcher skill below 2.
When above Launcher skill level 2 you can fire it but you seem to always be hit by bomb fragments even when firing 40 tiles away.

# Steps To Reproduce

1. Make a player with a gun with 40mm Pipe Launcher mod with 0-1 Launcher skill
2. Try to shoot grenade at zombie
3. You cannot aim anywhere, nor fire the gun

# Expected behavior
Big explosions

# Screenshots
![unknown](https://user-images.githubusercontent.com/29996039/72027491-dcb16680-3244-11ea-8dc2-e1108b6acc2b.png)

**Comment by Night-Pryanik** [comment]
Related to #36498?

**Comment by githubuser343** [comment]
Same issue is happening with M203 underbarrel grenade launcher still in latest stable 0.E.

**Comment by irwiss** [comment]
On latest master there's explicit messages about skill requirement
![image](https://user-images.githubusercontent.com/6560075/189505751-efa8f18a-fa55-4243-ae31-030bb0643429.png)

Once launchers theoretical skill is 2 the range is 60
