### ISSUE TITLE
Add a way to automatically heal the character with available consumables.

### ISSUE THREAD

**Issue by Brian-Otten** [CleverRaven/Cataclysm-DDA#36835]
Healing your character after you have taken some form of full body damage, or just from general combat after taking some spread out damage, can take a lot of keypresses. I find myself semi regularly having to bandage/disinfect every separate limb. This costse a lot of playtime for something you make very little choices in.

I'd love if there was a way to have your character automatically apply the best available antiseptic and bandage on every body part automatically, with a single keypress and a confirmation menu. I'd imagine this would be good as an unbound key you could bind yourself, but perhaps some more elegant UI inclusion is possible.

**Comment by TechyBen** [comment]
If keypresses is the goal, "automatic" seems overkill. However, I'm never against reducing keypresses. So an "apply best/worse (toggle etc) medication (bandage etc) to most damaged body part (with cycling once detecting bandage already applied)" would work to lessen keypresses.

I was wondering about the future container update too... things like a first aid kit would then be "applied" and could just automate things like medication (only the cycling through body parts bit) and be "reloaded" with bandages/disinfectant, quite easily.

As said, I don't mean total automation, just a medical version of the build/craft system that automatically gets the materials if in reach, as suppose to you having to "apply" each material manually in turn.

**Comment by Brian-Otten** [comment]
Yes, the main goal here is to reduce keypresses to heal up, so any decently elegant solution to it would be great.

**Comment by Ulysses2** [comment]
The first damaged limb is selected by default when you open the window, even if it's bandaged at "you don't expect any improvement" and has no status effects.

Also, bandaging NPCs is an enormous pain and it would be nice if the window would stay open while you're doing it. You could give them bandages, but then they won't get the benefit of your first aid skill.

You can apply bandages to yourself by `E`ating them, so that does cut down on the inventory searching if you don't have a lot of food around.

**Comment by TechyBen** [comment]
Slept on the idea. Wondered about it being a task for NPCs. A "use any/lowest available quality" for training up (go get bitten by an angry beaver, and train up the NPC) a "use best quality" option and a toggle for "only if bleeding/infected/damage over 10%" option. Then ask the NPC to "heal up people/me" and they'd go around applying bandages etc from their inventory/nearby stores?

I know it's a lot of work, but my best ability is thinking through steps logically, or applying existing working/design schemes to new ideas. :)

**Comment by Ramza13** [comment]
So right now NPC's with first aid skill 1 or greater and supplies should heal the player correctly.  The same logic could be pulled out and used to add this feature.  #36710 has references to the NPC logic that would need moving.
