### ISSUE TITLE
Some foodstuffs don't have vitamins at all

### ISSUE THREAD

**Issue by AntMatriarch** [CleverRaven/Cataclysm-DDA#36844]
# Describe the bug
Title

# Steps To Reproduce
>Press '&' (default)
>Turn to the food tab

# Expected behavior
Has some vitamins

# Screenshots
![Untitled](https://user-images.githubusercontent.com/45233782/72082359-ff25ab80-333a-11ea-8fcd-2ed472f5d149.png)
![Untitled2](https://user-images.githubusercontent.com/45233782/72082374-0351c900-333b-11ea-8c88-313c41da9af4.png)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-10735-gd136e46 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Bens GF recipes [Tolerate_This],
    Garden Pots [growable-pots],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Mutant NPCs [mutant_npcs],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player icon, retrodays [sees_player_retro]
]

**Comment by JeanLucVanDamme** [comment]
I wonder, is this because...
- no one has gotten around to adding vitamin values to those foods, or 
- those foods have negligible amounts of the vitamins the game cares about?

**Comment by AntMatriarch** [comment]
I don't know, some food has like 1% added in so even if miniscule it should have it. I'm pretty sure some alcohols also dont have it in the game. But alcohol actually absorbs vitamins so maybe it should be -1+% instead of +1+%? If that's the case, goodluck to the devs lol.

**Comment by kevingranade** [comment]
If you have specific foods in mind that have meaningful amounts of vitamins that are missing in the game, feel free to report them, but it's not the case that all foods will have them.
