### ISSUE TITLE
Taking stuff apart

### ISSUE THREAD

**Issue by 1n17** [CleverRaven/Cataclysm-DDA#36841]
**Is your feature request related to a problem? Please describe.**  
Taking stuff apart takes significantly less time than putting it together (even back together, ask any kid if you don't remember). But maintaining thousands of dedicated uncraft recipes reflecting that would be inefficient to say the least.

I'm getting a feeling I haven't elucidated myself properly here, so to reiterate - sans perhaps welded contraptions (unless using 'angular' grinder), _taking things apart, in the real word, is almost always significantly faster than putting them together, hence so it should in game_.

**Describe the solution you'd like**  
Allow `reversible` property to also take time value that would translate directly into auto-generated uncraft recipes.

**Describe alternatives you've considered**  
Have default uncraft time initialized to half of craft time, unless electronics is main skill then it becomes third of craft time - that is what I've been running locally for a while (on top of the above, to quickly deal with exceptions), to save myself effort of updating existing recipes.

**Additional context** 
This could substantially reduce amount of existing uncraft recipes.

NB. This isn't as much a request as proposal, I could have either solution up as PR's in minutes, just looking for input.

**Comment by TechyBen** [comment]
Dynamic generation is nice. As a game logic it would be easy for players to understand. As "real life" logic, well, we'd have to manually test/figure out/check deconstruction/disassembly times. That could be exhaustive to do with so many recipes/items.

It's a bit of a tangent, but IRL taking a phone apart carefully might take 10 or so minutes if not wishing to damage parts (see youtube https://youtu.be/o4p1gR27rNQ ). But in game is *30 seconds*. :p 

Assembling just the screen might take 20 mins: https://youtu.be/giHMOKIKvLs Though that's different to most makeshift/DIY projects (though again, has a lot of screw in parts, so not as slow as possibly soldering in parts). So those numbers for electronics don't seem too far off. This radio project also took around 20 mins: https://youtu.be/AW_ib2_fKPg So DIY electronics stuff might be comparable if the parts/recipe is already known and setup.

That said, when it comes to taking a chair or table apart, it can be done quickly if screwed/bolted (say garden furniture) together, or if nailed, hammering it with a crowbar.

Not sure how to treat non-electronic devices. IMO they'd be the quicker to dismantle objects.

**Comment by 1n17** [comment]
Well, soldering is quite quick with a bit of practice and when having right tool/tip for the job, de-soldering is even quicker and less tool dependent.
As to electronics more broadly, when you construct stuff you need to pick right value for elements, test them, then test connections you made, you get the drift - a whole lot of triple checking at every step. But when disassembling you don't care about all that - de-solder either to core elements or to functional blocks (power_suppy, amplifier come to mind) and throw them to boxes.

Very miniaturized consumer electronics are bit different, most everything is is either on main board or function blocks connected by connectors of some kind, and all basic components and higher logic are very small SMD's you wouldn't find much use for anyway were you to de-solder them, at least not without capabilities to print a circuit board of sufficient track precision, and single layer one would do you little good either. So at most you could reuse some modules, eg. GPS-receiver. So, as far as smartphones etc are concerned, I'd say disassembly times are OK-ish, perhaps could be risen to 2 minutes, to account for frustrated groaning at tamper-proof screws before prying the thing open with a blade. Though you should get a battery out of smartphones.

**Comment by 1n17** [comment]
And as to dynamic generation - game already does that, it even has rudimentary support for nonrecoverable elements (mostly used for glues IIRC).
What I am addressing is that specifying `reversible: true` - which auto-generates `uncraft` recipe that takes craft time as `uncraft` time was the default option, or rather, other than manually go trough the recipe ordeal again just to make `uncraft` time different - only option.
Also to reiterate - sans perhaps welded contraptions (unless using 'angular' grinder), taking things apart is almost always significantly faster than putting them together.
Well, technically in the PR submitted I only open the option of easily specifying `uncraft` time with no additional fiddling.
