### ISSUE TITLE
AT4 starts empty and cannot be reloaded.

### ISSUE THREAD

**Issue by Brian-Otten** [CleverRaven/Cataclysm-DDA#36866]
# Describe the bug
AT4 rocket launcher can't be reloaded but spawns empty. 

# Steps To Reproduce
Spawn at4 and ammo. Cannot reload the gun to fire it once. check the item group it spawns in (guns_launcher_rocket).
Issue probably caused by #36845

# Expected behavior

You can load the AT4 with one round of your choice before discarding it after firing. Since there are multiple variants of the rocket it uses available having them only spawn loaded might feel weird, since you would get no choice in which rocket to use.

# Screenshots
![image](https://user-images.githubusercontent.com/47374323/72133196-23a47680-3381-11ea-9ef6-c2e3f39ecd0e.png)
![image](https://user-images.githubusercontent.com/47374323/72133207-299a5780-3381-11ea-8008-56ebbb0b407f.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-11109-g6674292 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Craftable Gun Pack [craftgp],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    EZ-Mode Medical [fast_healing],
    No Rail Stations [No_Rail_Stations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Roadheader and other mining vehicles [Heavy miners],
    No Acid Zombies [No_Acid_Zombies],
    No Explosive Zombies [No_Explosive_Zombies],
    No Fungal Monsters [No_Fungi],
    Safe Autodoc [safeautodoc],
    Manual Bionic Installation [manualbionicinstall],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

# Additional context
Possible solutions:
Make the gun able to load ammo and fire once before being discarded.
Make them come preloaded with one of the standard rounds and add the Carl gustav m3 so a ingame weapon can use the remaining rounds.
Make them come preloaded and remove the ammo it uses from the spawn tables
Replace the weapon with the m3 carl gustav which can reload.
Make the at4 reloadable again.

**Comment by tenmillimaster** [comment]
The m3 is already in game.
