### ISSUE TITLE
SMP support

### ISSUE THREAD

**Issue by muravey-omsk** [CleverRaven/Cataclysm-DDA#36885]
Why game don't support SMP/threads?

**Comment by KorGgenT** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/issues/20775#issuecomment-291001781

**Comment by muravey-omsk** [comment]
I mean multicore CPU, not GPU.

**Comment by anothersimulacrum** [comment]
That comment is saying that both GPU and CPU milt reading have the same problems.
