### ISSUE TITLE
"Consume item" window is reset if a filter was set

### ISSUE THREAD

**Issue by Ulysses2** [CleverRaven/Cataclysm-DDA#36884]
# Describe the bug

Normally, after you eat something, the "consume item" window will reopen and auto-select whatever you just ate if you had more of it. However, if you set a filter using `/`, the filter is reset and the first item in the list is auto-selected.

# Steps To Reproduce

1. Get a bunch of comestibles
2. Press `E` and then `/`, then enter something to narrow down the list
3. Eat something and the window will reset

# Expected behavior

The item you just ate should be auto-selected regardless of whether you set a filter. As for the filter, this is less clear since there are a lot of different UI windows with filters, and they are not consistent at all with how they handle this issue. I am tentatively thinking it should stay until the window is manually closed.

# Versions and configuration

- OS: MacOs
    - OS Version: Name: Mac OS X; Version: 10.14.6; Build: 18G2022; 
- Game Version: 0.D-11103-gbd3a2e3 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
There's another mildly annoying UI bug with this window, but I'll write up a separate report for that.

**Comment by CoroNaut** [comment]
I've found that the consume item menu was helpful when driving because it would flash the screen when the vehicle would move. It helps me not crash into something while eating and driving, but it is indeed annoying when it flashes just holding down the enter key to eat a lot of food. 

I also never saw the reason for why it took up so much of the screen, I feel like it could be nice to have it as a side menu like the examine menu instead.

**Comment by jkraybill** [comment]
I've found slightly different behaviour (latest build and recent experimentals) -- the menu seems to reset a lot more than expected, when the base menu (total amount of consumable items) is about more than a page, whether filtered or not.

I haven't been able to exactly pin it down, but when dealing with a large menu of consumables, the menu tends to reset to the top item (but not always).

Example: spawned a page and a quarter of items in latest build. Some in inventory, some on floor below me. Eat any item in the list, the list resets to top item after consumption.

![image](https://user-images.githubusercontent.com/1361701/74225209-5a6a0580-4d0e-11ea-8642-0295a65ff971.png)

Filter down to a list that is less than a page, but items are in more than one location, list still resets to top item after consumption:

![image](https://user-images.githubusercontent.com/1361701/74225267-7b325b00-4d0e-11ea-9037-e253c8b6256c.png)

Filter down to a list that is only 3 items long, but items are in 2 locations (inventory and cupboard), list still resets after consumption:

![image](https://user-images.githubusercontent.com/1361701/74225339-9f8e3780-4d0e-11ea-9cbf-7205df143b39.png)

Filter down to a list that only has items in one location, list does NOT reset after consumption (which is correct behaviour IMO):

![image](https://user-images.githubusercontent.com/1361701/74225408-bc2a6f80-4d0e-11ea-9605-1a2bd8449233.png)

**Comment by jkraybill** [comment]
It's not as simple as "selected list has items in multiple locations". In this example, which is filtered, but has multiple locations, the list DOES stay on the selected item after consumption:

![image](https://user-images.githubusercontent.com/1361701/74226844-6b684600-4d11-11ea-9796-100c43d33676.png)

**Comment by WeaverThree** [comment]
I just messed with this a little myself. I had to get it down to exactly one purple heading in the menu myself for it to stop resetting, and the last offender was a worn canteen with 2/6 water in it.

**Comment by scorpion451** [comment]
Can confirm this as happening for me without filtering as in #38014.
Been trying to figure it out myself, but it seems like [one of those problems](https://www.xkcd.com/1316/).

**Comment by jkraybill** [comment]
@scorpion451 can you please elaborate and maybe post a screenshot? Specifically is it occurring when your E menu contains items in multiple locations and/or multiple states of edibility?

**Comment by Funguss** [comment]
Occasionally I've been getting a "tried to duplicate item" message on eating, too. I'll grab the log next time in case it's relevant, and do some testing on eating.

**Comment by jkraybill** [comment]
@Funguss you may want to check if the fix for #37583 resolved the duplicate item issue, that one was fixed recently and sounds like what you're reporting.

**Comment by Karthas077** [comment]
The two bugs are most likely related to an underlying problem, as the source of the duplicate item debug message was triggered by the attempts to refresh the consume item menu.

**Comment by Qrox** [comment]
> and the last offender was a worn canteen with 2/6 water in it.

This. I experimented with it a bit and the problem seems to only happen if there's a container in the filtered list.

**Comment by Funguss** [comment]
#38342 probably stems from the same cause then as it's happening solely with liquids (i.e. containers). I just had a canteen of water disappear, was about to update that it wasn't to do with freshness after all but is simply to do with containers.
