### ISSUE TITLE
Examine menu doesn't correctly redraw when changing size

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#36891]
# Describe the bug

If the examine menu opens and immediately displays an item with a long name and you happen to have another page where all items are short names, the examine menu will re-size to be horizontally smaller and leave fragments of text from the long names of items from the previous pages.

# Steps To Reproduce

1. Make a pile of loot with 2+ pages where items with long names show up first to make the examine menu resize to be larger horizontally
2. Change to second page where all items' names are smaller
3. Notice the page has fragments of text from previous page

# Expected behavior

1. The examine menu determines width based on longest-name in the list of loot and sticks to it while redrawing at that same width for every page
2. The examine menu will be default width and long names will be truncated to accommodate

# Screenshots
First page:
![Capture](https://user-images.githubusercontent.com/24307650/72175928-55cace00-33ab-11ea-9eb4-21e7bbb77794.PNG)
Second page:
![Capture2](https://user-images.githubusercontent.com/24307650/72175936-58c5be80-33ab-11ea-944c-36dbf962bda5.PNG)

# Versions and configuration
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-10922-gb1541cd [32-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    No Fungal Monsters [No_Fungi],
    Disable Religious Texts [no_religious_Texts]
]

**Comment by 8street** [comment]
Please try update the game and testing now. I'd fixed this bug in #36593

**Comment by CoroNaut** [comment]
Fixed
