### ISSUE TITLE
Expand variety of NBC suits.

### ISSUE THREAD

**Issue by Brian-Otten** [CleverRaven/Cataclysm-DDA#36890]
**Is your feature request related to a problem? Please describe.**  
Currently the game has a small selection of environmental protection suits, but they don't quite match what you might expect you would find in real life.

**Describe the solution you'd like**  
You would expect the soldiers to have some kind of strapped NBC suit
https://en.wikipedia.org/wiki/NBC_suit
Some factory locations and some of the lab locations would have a very light outer layer cleansuit without much protection
https://en.wikipedia.org/wiki/Cleanroom_suit
While the xedra labs and some special locations would have Level A and level B hazmat suits:
https://www.dgdeclaration.com/different-hazmat-suit-levels/

The current spawn lists and stats of the suits we do have don't quite fit what you would expect in real life, so it would involve changing some of the suits to better fit real life, adding 1 or 2, and adjusting the spawntables to find them where you expect.

**Describe alternatives you've considered**  
Leaving all the armors ingame as it is but only adjusting spawn tables.
Keeping the armors and spawns as is.

**Comment by 8street** [comment]
I found in game something like suggested cleanroom and hazmat suits. They were named something like this: a lab coat and a protective suit of the center 01.
