### ISSUE TITLE
(2) crashes during game saves in recent play.

### ISSUE THREAD

**Issue by 1FSTCAT** [CleverRaven/Cataclysm-DDA#36894]
Game version: Recent versions from the past 14 days.

Operating system: Window 10

Tiles or curses:

Mods active:

### Expected behavior
I know we want CDDA to be "hardcore" and "permadeath", but why not keep the last ~10 saves and let the player decide when and how to reload? I hate playing for and losing 3 hours of progress 
 because items and maps became out of synch unrecoverably due to a save game error. It sure would be nice to reload back to before the error began and then avoid whatever buggy item/location/etc is causing the issue.

### Actual behavior
First round of play, about 7 days ago - had autosave turned on and experienced an error during the save about 2 hours in. Text said something about .JSON corruption but could not get the error to go away. Had to close and restart the game. When I did, the map, character and items were out of synch / duplicated.

Second round of play, yesterday, autosave turned off. Had an hour or two in a game, resumed it. Played for about an hour and attempted to "save and quit". Game hard-locked during the save (no errors shown, just locked up). Had to "end task" on it. Was able to reload but found the map and things I had brought back to base were out of synch again. Places I'd visited before the crash were now showing as unexplored, but everything I had brought back to base was "current".

**Comment by BevapDin** [comment]
> Text said something about .JSON corruption but could not get the error to go away.

Well, without posting the exact error message (preferably with additional details), we can not fix this.

**Comment by KorGgenT** [comment]
There's no actionable information in this PR. please update it with information we can use to find a bug.

**Comment by 1FSTCAT** [comment]
If the game just stops responding during save, is there an error log that we can use to troubleshoot?

**Comment by kevingranade** [comment]
Non-permadeath or in-game save backups are not open for discussion.
