### ISSUE TITLE
Can gain infinite trust and negative infinite anger for any npc

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#36904]
If you can manage to get an npc to like you enough to select "Another survivor, we should travel together" consistently, you can gain infinite trust and negative infinite anger

# Steps To Reproduce

1. Pick option "Another survivor, we should travel together"
2. Then pick option "We're friends aren't we?"
3. (Gains 2 trust and -1 anger)
4. "Awesome"
5. "I'm going to go my own way for a while"
6. "Yeah, I'm sure, Bye"
7. repeat steps 1-5
8. Infinite trust, negative infinite anger

# Expected behavior

The love potion that is constantly pushing someone away and accepting them back in a matter of a few words doesn't work

# Versions and configuration
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-11103-gbd3a2e3 [32-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    No Fungal Monsters [No_Fungi],
    Disable Religious Texts [no_religious_Texts]
]

**Comment by CoroNaut** [comment]
Also, if you select the first option instead, you gain 1 trust every time, and I think another stat increases too.

**Comment by kevingranade** [comment]
Should be a simple matter of delaying the bonuses until you commit to travelling together, or simply capping trust level at a little above what is required to trigger the option.

**Comment by davidpwbrown** [comment]
Could we not mirror the bonuses with equal negatives when you say your going to go your own way?

( maybe even a bit more negative, so that constant splitting up and rejoining will eventually piss them off )

**Comment by kevingranade** [comment]
yea making it symmetric works too.
