### ISSUE TITLE
Show current weight (and limit) and Volume (and its limit) in the UI (as togglable option)

### ISSUE THREAD

**Issue by Lamandus** [CleverRaven/Cataclysm-DDA#36924]
**Is your feature request related to a problem? Please describe.**  
I use a lot of auto pickup, and I sometimes want to see in a glance if I still have enough volume or not. To do so know, you need to look into the inventory. Sure that Feature is not important in any shape or form. But (at least for me) it would be a QoL feature, just to see how much I can still carry.
**Describe the solution you'd like**  
Show the volume and weight in the UI. And the possibility to switch it on or off in the UI editor.

**Describe alternatives you've considered**  
keeping it as it is

**Additional context**  
Mockup 1
![Vol](https://user-images.githubusercontent.com/33199510/72204379-7f512b80-3477-11ea-90f5-45ae55c2f5e6.jpg)
Mockup 2
![Vol](https://user-images.githubusercontent.com/33199510/72204456-71e87100-3478-11ea-8ee7-89306422b6e2.jpg)

**Comment by KorGgenT** [comment]
shouldn't probably be too hard to add a panel to all the layouts.
