### ISSUE TITLE
Auto-Chop in designated Area with a hachet results in error

### ISSUE THREAD

**Issue by kuhnchris** [CleverRaven/Cataclysm-DDA#36934]
# Describe the bug
Grab hachet, mark tree area as designated area for chop wood, try to "Chop Wood".
Wood is being chopped but I keep having to nick off this error that I'm not using an consumable tool to chop wood.

# Steps To Reproduce
see above

# Expected behavior
Uninterrupted chopping of wood due to task execution

# Screenshots
![chopchopgoeswood](https://user-images.githubusercontent.com/761911/72210320-bfd19900-34b9-11ea-913b-6935bb9962ad.gif)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-11147-gb2f3d1c [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

 DEBUG    : Tried to consume charges for non-tool, non-food, non-med item
 FUNCTION : bool Character::consume_charges(item&, int)
 FILE     : src/character.cpp
 LINE     : 5672

**Comment by kuhnchris** [comment]
Since this says "tried to cosume charges for non-tool non-food non-med item" - maybe it's because the hachet is declared as "weapon"?

**Comment by davidpwbrown** [comment]
Can you upload the savegame if possible, please?
