### ISSUE TITLE
Ammo type 40mm is not known

### ISSUE THREAD

**Issue by MangoKangaroo** [CleverRaven/Cataclysm-DDA#36930]
# Describe the bug

An error regarding 40mm ammunition occurs when loading a world. It is worth noting that I have had this issue since 10090. Furthermore, this error occurs multiple times at once pertaining to all 40mm ammo types.

# Steps To Reproduce

1. Create new world
2. Attempt to create new player for world
3. Error occurs during initial world loading and whenever loading the world from now on

# Expected behavior

No error to occur during world loading.

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Pop!_OS 19.10; Release: 19.10; Codename: eoan; 
- Game Version: 0.D-11109-g6674292 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Icecoon's Arsenal [ew_pack],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs],
    Disable NPC Needs [no_npc_food],
    Manual Bionic Installation [manualbionicinstall],
    Prevent Zombie Revivication [no_reviving_zombies],
    Safe Autodoc [safeautodoc],
    Stats Through Kills [stats_through_kills]
]

# Additional context

Same issue occurs with world that has no mods beyond the core DDA.

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4049635/debug.log)
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4049636/save.zip)

**Comment by Kilvoctu** [comment]
Is it perchance coming from Icecoon's Arsenal?

This PR #35865 updated the ammo types a while back, and any mods using the old types need to be updated

**Comment by MangoKangaroo** [comment]
As noted in additional context, this occurs in worlds without Icecoon's Arsenal.

**Comment by MangoKangaroo** [comment]
So, I've done my due diligence in further testing with a fresh copy of the game on the same version. I'm unable to get this issue to repeat. My theory is that overwriting files to update my game may have caused this issue to occur. Why this may be is outside my limited knowledge.

What I do know is that given I am unable to reproduce this issue in my fresh copy, this issue should be fine to close unless anyone else thinks there's something at play here that I've missed.

**Comment by Kilvoctu** [comment]
Oh so it happens on new worlds too? After that PR, my old worlds had errors because there exist in them items that used the old 40mm type. :thinking:

**Comment by MangoKangaroo** [comment]
This was probably a related issue regarding something that got left over when I updated. Now that I've done a fresh install, the error is not occurring. For that reason, I'm closing this issue.
