### ISSUE TITLE
Crafting Recipe Error with salt_water / water_clean on Game Load

### ISSUE THREAD

**Issue by Chronakai** [CleverRaven/Cataclysm-DDA#36932]
# Describe the bug

An error appears when loading the game, when reaching the Crafting Recipes portion of loading. The game still loads and functions as far as can be determined when ignoring.

# Steps To Reproduce

1. Launch the game
2. Load the save

# Expected behavior

The save loads with no issue, since all mods enabled are from the Launcher's listings.

# Screenshots

N/A

# Versions and configuration

- OS: Windows 8.1
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-11179-g57b7dbe [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Garden Pots [growable-pots],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    No Antique Firearms [no_olg_guns],
    No Fictional Guns [no_rivtech_guns],
    No Sci-Fi Equipment [no_scifi],
    Prevent Zombie Revivication [no_reviving_zombies],
    Safe Autodoc [safeautodoc],
    Classes and Scenarios Mod [more_classes_scenarios],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Stats Through Kills [stats_through_kills],
    No Filthy Clothing [no_filthy_clothing],
    Manual Bionic Installation [manualbionicinstall],
    C.R.I.T Expansion Mod [crt_expansion],
    MST Extra [MST_Extra]
]

# Additional context

 DEBUG    : loop in comestible recipes detected: salt_water -> water_clean -> salt_water.  Such loops can be broken by either removing or altering recipes or marking one of the items involved with the NUTRIENT_OVERRIDE flag

 FUNCTION : void recipe_dictionary::find_items_on_loops()
 FILE     : src/recipe_dictionary.cpp
 LINE     : 405

[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4049696/config.zip)
[Elmwood Park.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4049697/Elmwood.Park.zip)

**Comment by ZhilkinSerg** [comment]
Looks like an issue with a third party mod.

**Comment by OliveChukar** [comment]
Tested in ver 0.E-9111-gd1e702b-dirty with all the mods that are still in game from the list in the original report. No error.

Tried testing with save from report and got many error messages that seemed to be from mods.

**Comment by anothersimulacrum** [comment]
Closing as a third party issue.
