### ISSUE TITLE
Foraging Multiplication

### ISSUE THREAD

**Issue by Grubleafeater** [CleverRaven/Cataclysm-DDA#36938]
Some items, when foraged, drop much more than what the notification says they do. For instance, acorns are dropping quadruple.

Steps to hopefully reproduce:

1.create new world
2.set start date to autumn
3.forage oak trees

**Comment by 1n17** [comment]
It's the way default stack sizes (`charges`) are handled, it tells you you got 2 acorns what it means is that you got 2x4 charges of acorns.

**Comment by Fris0uman** [comment]
It might be because it used to be called "handfull of acorns" which made the fact it had 4 charges less surprising.
