### ISSUE TITLE
Rework gunsafe contents.

### ISSUE THREAD

**Issue by Brian-Otten** [CleverRaven/Cataclysm-DDA#36931]
**Is your feature request related to a problem? Please describe.**  
Gunsafes often have guns, but no ammo/ magazines for them, or they have mismatched guns and ammo.

**Describe the solution you'd like**  
Gunsafes would spawn with the pistol and a loaded magazine or two, and maybe sometimes a box of 50 rounds of ammo. a decent portion should have the gun removed, a smaller portion has the magazines/ammo removed.

**Describe alternatives you've considered**  
Leaving gunsafes as is.

**Additional context**  
As requested on the discord, i'll compile a quick list of what the gun distribution of the cata gunsafes in a spawn table might look like.

"most common"
glock 17
m1911A1

Common
glock 22
USP 9mm
S&W Model 10

Uncommon
S&W 629
Browning Hi-Power 9x19mm
Ruger LCR .38
Remington 870 express

Rare
AR-15

Here is where it gets slightly iffy. It used to be larger part of the lore that cataclysm US was far more militarized for civilians than even current US. if we want to keep that we probably also want to add these

Uncommon
uzi 9mm
S&W 500

Rare
SPAS_12

**Comment by tenmillimaster** [comment]
When you say "might look like", you mean these are the guns that are in the safe? Those above, specifically?

**Comment by Brian-Otten** [comment]
These are my suggested guns for in home safes. Feel free to edit as you like and post it up, teamwork makes the dream work.

**Comment by tenmillimaster** [comment]
If you have Hi powers and LCR's as uncommon, let alone 870's, and AR15's as _**rare**_, and believe that civilian ownership of S&W500's and SPAS 12's would be affected by old cata lore to new cata lore, I highly suggest you find better sources.

Glock 19's and AR-15's are the most common firearms in America.

**Comment by mlangsdorf** [comment]
I'd actually expect the guns in an unopened gun safe to be biased toward hunting and target shooting weapons.  Before the Cataclysm, a gun safe might have an AR-15 clone, a Remington 700, a Remington 870, a Keltec KSG, 2x Glock 19s, a Ruger 10/22, and a SIG Mosquito, but the owner is probably going to grab the AR-15, the Keltec, and Glocks and go get killed.  A survivor scrounging later is going to find the hunting rifle, hunting shotgun, and plinking guns.

Some gun safes are going to have the pre-Cataclysm collection, or parts of it, but in general I think gun safes should be biased toward the less useful weapons and towards low caliber, low magazine weapons.

That said, I can't see a situation where you're more likely to find a M1911A1 over a Remington 870 - they're both guns someone would reasonably grab in a deteriorating survivalist situation.

**Comment by Brian-Otten** [comment]
Anyhow, erk said he wanted to implement this semi-soon, He will probably want a full list to use verbatim since guns aren't his thing. Feel free to copy my list and make adjustments, or write a fully different one and suggest him to use that.
