### ISSUE TITLE
Magiclysm - JSONize spellcasting skill

### ISSUE THREAD

**Issue by foulman** [CleverRaven/Cataclysm-DDA#36937]
**Is your feature request related to a problem? Please describe.**  
It's not a "problem" per se, but there's no way to have different levels of ability in different types of magic, much less be able to have things like psionic powers, everything is tied into one skill that is unfortunately hardcoded rather than being defined, unlike almost everything else in the mod. The skill itself is defined in the mod, but spells pointing to it are not. You can't have alternatives in name, much less multiple options.

**Describe the solution you'd like**  
Allow a "spell_skill" field to go along with "spell_class" in spell JSON, spells should by default rely on spellcraft unless otherwise specified. Then new mods can create their own skill in JSON and then spells that rely on it. 
Players that use magiclysm or other mods can then have varying levels of ability, such as Magus: 2 and Stormshaper: 4 (if desired), rather than a general level of magical training applying to all schools/classes. 

**Describe alternatives you've considered**  
Another option would be to optionally allow a spell to set a base difficulty that does not factor in skills or stats, only the specific base number, and spell level, perhaps with chosen modifiers. This would enable spells that fall completely outside the spellcraft system.

Implementation would be more difficult and less versatile overall, though may have its own utility as well for specific uses, depending on the spell designer's intent.

Otherwise, there's no other way around this issue, it's one of the few hardcoded things in magiclysm, and probably one of the oldest, but hopefully not too difficult to un-hardcode. 

**Additional context**  
I know current mods such as Arcana would benefit from opening this up, as well as psionic work I myself am tinkering with, and no doubt other modders would take advantage of it with things like mystical martial arts/Ki. It would additionally be nice to have more control over base failure rates for "spells" if this is in the cards.

**Comment by foulman** [comment]
Additionally, I just realized there might be changes needed to spellbook reading/functionality as well, not sure how it works exactly.

**Comment by KorGgenT** [comment]
merged to dev
