### ISSUE TITLE
0.E is Coming

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#36949]
It's time for 0.E, only about ~three~ ~four~ ~five~ six months later than planned.

#### What does this mean?
We're really for real making a real push toward really releasing the real 0.E.
The release blockers are tracked in the [release project](https://github.com/CleverRaven/Cataclysm-DDA/projects/23).  Once these are addressed, we can proceed to release.
I waited until really late this time, there are very few remaining blockers that we are aware of at this point.

#### What does this change?
We are in *Everything Freeze* now.
We have and are pre-merging some PRs to the dev branch to cut overall merge and conflict management workload, but we are not releasing builds of this branch.

* Going forward, no feature or content or string modifying PRs should be merged.
* Once we enter *Content Freeze*, PRs that add new items/monsters/terrain/etc should not be merged.
* Once we enter *String Freeze*, PRs should not be merged if they edit any strings, even if the strings are slightly wrong.

- [x] Feature Freeze
- [x] Content Freeze
- [x] String Freeze
- [x] Blockers cleared
- [x] Publish release candidate
- [x] Completed Changelog
- [x] Merged Translations
- [x] Merge final Ultica update
- [x] Update credits menu
- [x] Pick Release Name
- [x] Draft Press Release
- [ ] Tag blessed commit
- [ ] Post release announcement

#### Can I help?
If you know about any game-breaking bugs that are not listed [here](https://github.com/CleverRaven/Cataclysm-DDA/projects/23), please leave a comment with a link to the issue.

#### Describe alternatives you've considered
Give up on releases.

**Comment by KorGgenT** [comment]
And we're now in content freeze! We cleared the blockers earlier today totally, but at least one has popped up in the interim. we've got generic guns merged so maybe some more might pop up.

**Comment by ZhilkinSerg** [comment]
#### Useful lists:

- [pull requests](https://github.com/CleverRaven/Cataclysm-DDA/pulls?q=is%3Apr+is%3Aopen+no%3Alabel) that need to be triaged before `0.E`;
- [pull requests](https://github.com/CleverRaven/Cataclysm-DDA/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+-label%3A%220.E+Content+Freeze%22+-label%3A%220.E+Feature+Freeze%22) that still can be merged before `0.E` (also includes untriaged pull requests);
- [pull requests](https://github.com/CleverRaven/Cataclysm-DDA/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+-label%3A%220.E+Content+Freeze%22+-label%3A%220.E+Feature+Freeze%22) that are in **Content Freeze** state and won't be merged before `0.E`;
- [pull requests](https://github.com/CleverRaven/Cataclysm-DDA/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+-label%3A%220.E+Content+Freeze%22+-label%3A%220.E+Feature+Freeze%22) that are in **Feature Freeze** state and won't be merged before `0.E`.

**Comment by tinukedaya** [comment]
@ZhilkinSerg I believe copy&paste played games with you. Fixed the last two links. 

 - [pull requests](https://github.com/CleverRaven/Cataclysm-DDA/pulls?utf8=✓&q=is%3Apr+is%3Aopen+label%3A"0.E+Content+Freeze") that are in Content Freeze state and won't be merged before 0.E;
- [pull requests](https://github.com/CleverRaven/Cataclysm-DDA/pulls?utf8=✓&q=is%3Apr+is%3Aopen+label%3A"0.E+Feature+Freeze") that are in Feature Freeze state and won't be merged before 0.E.

**Comment by l29ah** [comment]
> If you know about any game-breaking bugs that are not listed here, please leave a comment with a link to the issue.

https://github.com/CleverRaven/Cataclysm-DDA/issues/28816 breaks the game for low-str characters.

**Comment by scorpion451** [comment]
Game breaker:
#37586 Creates soft-locks via runaway temperatures with any of the CBM generators that give the Heated status. (Issue also needs the temperature flag added)

**Comment by Ronnie-PL** [comment]
#36833 breaks the game experience: a problem with stairs connecting houses with their basements causing teleportation.

**Comment by KorGgenT** [comment]
> #36833 breaks the game experience: a problem with stairs connecting houses with their basements causing teleportation.

I would say that is an issue that has been papered over for 0.E and is such a large project to fix it probably won't make it in 0.E.

**Comment by ZhilkinSerg** [comment]
> 
> 
> > #36833 breaks the game experience: a problem with stairs connecting houses with their basements causing teleportation.
> 
> I would say that is an issue that has been papered over for 0.E and is such a large project to fix it probably won't make it in 0.E.

We can at least fix peeking teleport (that is mentioned in the comments there).

**Comment by yarbelk** [comment]
i vote for Extinction as the name.  Seems on theme to me.

**Comment by Ramza13** [comment]
I saw a suggestion to add #38325 to the list of blockers and it does seem like a pretty big issue with NPC quests at the moment.

**Comment by l29ah** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/issues/36726 bites me every time i decide to do long actions in a somewhat chaotic environment.

**Comment by ZhilkinSerg** [comment]
In order to reduce backlog, I've started merging pull requests affected by feature and content freeze to `dev` branch (https://github.com/CleverRaven/Cataclysm-DDA/tree/dev). We will update this branch with changes from `master` and will merge it to `master` after stable `0.E` is out.

Following PRs were merged so far (list will be updated):

#26525
#36908
#38474 (as #38592)
#38501
#38520
#38526 
#38550
#38551
#38552

**Comment by jkraybill** [comment]
There have now been three separate reports of #38611 - despite its title, two of the other reports (see #38641) report getting this error immediately upon game start. Don't know if it's blocker-worthy but seems worth consideration. I couldn't repro it, but I only tried a few times.

**Comment by 8street** [comment]
> In order to reduce backlog, I've started merging pull requests affected by feature and content freeze to `dev` branch (https://github.com/CleverRaven/Cataclysm-DDA/tree/dev).

Sorry for necroposting. Is there an automatic `dev` branch build somewhere? Like Jenkins or something. 
It is dangerous to merge all commits into one branch without the possibility of testing them. Then it is very difficult to catch a causes new bugs and errors.

**Comment by ZhilkinSerg** [comment]
We do not use Jenkins builds for mergetesting - PR branches are checked out and built locally.

**Comment by kevingranade** [comment]
@jkraybill If it were reproduceable I'd be looking into it as a blocker, but as it isn't, I've exhausted my options for investigating it and can't justify marking it as a blocker as it's cosmetic.

**Comment by Wuzzy2** [comment]
I see that string freeze has been activated recently. How much time do translators have at least to complete their work?
I see in German, there's a shocking number of ca. 16,000 strings to translate! That can take a while …

**Comment by kevingranade** [comment]
Translations are one thing we typically do point releases for, so if people are willing to complete the translation for a language after initial release, I'll happily do those releases. In order to make it into the initial release though, we're looking at a week or so.

**Comment by Wuzzy2** [comment]
16000/7=2285.

Yeah, I very much doubt I am able to translate 2285 strings per day. I don't know how many other people work on German, however.

**Comment by Gaunah** [comment]
For German I'm able to help and already did a few over the weekend. But yeah, it's quite a lot.

**Comment by Jerimee** [comment]
Do we have a media plan for this? Like a press release or anything?

**Comment by Wuzzy2** [comment]
I am very sad to tell you that I will very likely be unable to contribute translations for this release.

My `curl` script is failing with Transifex, server returns empty response. My guess is that Transifex chokes on large files.

With my only method to update translation gone, I am unable to translate. I am so sorry. :-(

----

For those who are interested, this is the script I am using to download and upload the PO files from Transifex (so I can avoid running proprietary JavaScript code):

https://pastebin.com/ftNvkA1H

And this is how I download and upload a translation:

```
# (NOTE: Before you can use the script, you must edit the lines starting with "USER" and "PASSWORD". Don't share the file with your password (obviously)!)
# First, I download to PO file:
tf.sh GET cataclysm-dda master-cataclysm-dda
# This downloads the file and puts it into download.po
# Then I translate the file
# When I'm done, I upload:
tf.sh PUT cataclysm-dda master-cataclysm-dda
```

The failure happens in the last step, the upload. Sever returns empty response. It has worked flawlessly with Transifex for months now, and it still works for ALL other projects. It also still works with smaller resources.

**Comment by ZhilkinSerg** [comment]
> Do we have a media plan for this? Like a press release or anything?

The usual thing - forum, website and Reddit announcements.

**Comment by ZhilkinSerg** [comment]
@BrettDong Today is very good time for final translations PR before 0.E.

**Comment by Wuzzy2** [comment]
So, any suggestions how I can help with translations anyway, without running proprietary code (Transifex JavaScript)?

**Comment by kevingranade** [comment]
Whoops forgot to close, 0.E is out.
