### ISSUE TITLE
Game crash with MESSAGE: SIGABRT: Abnormal termination

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [CleverRaven/Cataclysm-DDA#36951]
Game straight up crashes! right before recipes.

https://hastebin.com/cimafoqene.pl
https://hastebin.com/wovupoqaqo.cpp
https://hastebin.com/ipulitotic.json

# Steps To Reproduce
Update from 10158 to 10173.

# Expected behavior
Not crashing

# Versions and configuration
Can't do, game crashes.

**Comment by Qrox** [comment]
@jbytheway Seems to be caused by #36657.

**Comment by ZhilkinSerg** [comment]
Does not look like vanilla recipe.

**Comment by Unrepentant-Atheist** [comment]
It isn't a vanilla recipe. It's from a mod, but still. It crashes. How can I fix it?

**Comment by jbytheway** [comment]
Are you the mod author, or in contact with them?  I recommend changing the recipe to be a multi-step process where you have an intermediate item crafted from the following alternatives:
```
    [
      [ "meat_tainted", 36 ],
      [ "dry_meat_tainted", 36 ],
      [ "corpse", 1 ]
    ]
```
and then use four of those intermediate objects in the final recipe.

And then similarly for the
```
    [
      [ "bone_tainted", 8 ],
      [ "bone", 8 ],
      [ "bone_human", 8 ],
      [ "corpse", 1 ]
    ],
```

In parallel, I'll think about whether I can downgrade this assertion to a `debugmsg`.  In the worst case, I guess I could have the game continue but remove that recipe.  But would probably be preferable to have such recipes still be usable, even if they don't quite work perfectly...

**Comment by Unrepentant-Atheist** [comment]
Unfortunately I'm neither the mod author nor in contact with them :(

**Comment by jbytheway** [comment]
The complexity here is the overlapping ingredients.  That makes it much more complex to determine whether a recipe is in fact craftable with the available ingredients.  The game used to just do this wrong.  Now it does so correctly, but the cost is that we prohibit recipes with undue overlap, because they are costly to calculate.

**Comment by jbytheway** [comment]
The crash is resolved now.  The recipe still won't behave quite correctly, but at least you should be able to play the game.  Hopefully the mod author will see the error message and tweak his recipe accordingly.
