### ISSUE TITLE
Skill required to mount weapons are to high.

### ISSUE THREAD

**Issue by TheGamingFox1911** [CleverRaven/Cataclysm-DDA#36964]
The skill necessary to mount weapons on weapon mounts is too high. 

# Steps To Reproduce

1. make a vehicle with a weapon mount
2. get a mountable weapon like an M2 or a MK19
3. The level is at a higher level than it should be

# Expected behavior

It should be easier to mount certain crew served weapons, as in real life they are easily mounted.

# Screenshots
![image](https://user-images.githubusercontent.com/52058797/72220198-e7ede600-3513-11ea-95de-04189222b0ec.png)
![image](https://user-images.githubusercontent.com/52058797/72220200-ee7c5d80-3513-11ea-8536-6979b52b46a0.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-11179-g57b7dbe [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Bens GF recipes [Tolerate_This],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    DinoMod [DinoMod],
    Hydroponics [hydroponics],
    Mining Mod [Mining_Mod],
    Mythical Martial Arts [MMA],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Mapgen Demo [mapgen_demo],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Necromancy [necromancy],
    Bionic Slots [cbm_slots],
    Classes and Scenarios Mod [more_classes_scenarios],
    Classic Roguelike Classes [RL_Classes],
    Disable NPC Needs [no_npc_food],
    Manual Bionic Installation [manualbionicinstall],
    Safe Autodoc [safeautodoc],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Fuji's Military Profession Pack [fuji_mpp],
    Roadheader and other mining vehicles [Heavy miners]
]

# Additional context
https://www.youtube.com/watch?v=XvAZUXrUkBQ

**Comment by kevingranade** [comment]
This represents fitting an arbitrary gun to a generic mount which is very different from installing a gun onto a mount specifically designed for it.

**Comment by TheGamingFox1911** [comment]
Well, how about two separate mounts? One a standard military mount that can mount only military crew-served weapons and a universal mount that can mount anything?

**Comment by kevingranade** [comment]
Get me some information on what mounts in use are interchangeable and we can talk.
