### ISSUE TITLE
Add air to air and ground to air missiles to the game in locations that make sense.

### ISSUE THREAD

**Issue by Brian-Otten** [CleverRaven/Cataclysm-DDA#36961]
**Is your feature request related to a problem? Please describe.**  
Any player that currently wants to play a more explosive oriented build often find himself needing to handcraft various explosives from their base chemicals, or making them from improvised gunpowder. When i was thinking of where the survivor might find some decent amount of explosives in the world i thought of a military munition that probably wasn't used up much or looted during the cataclysm. Air to air and ground to air missiles. 
These would be unusable for their intended purpose (for now, since the game lacks both the coding and the usecases for them, let alone the survivor being able to use them),

But they could be disassembled for their materials, which would include explosives, military electronics, and depending on the rocket perhaps some form of rocket fuel.

**Describe the solution you'd like**  
The missiles will spawn in locations where they make sense and the player can disassemble them for materials

**Additional context**  
I'm going to try and tackle this myself for now, but i will only get started somewhere next week, and it might take me a while to get it working properly. 
Any feedback/ideas/suggestions would be appreciated, and if i abandon this project i'll post an update.

**Comment by thethunderhawk** [comment]
@tenmillimaster tends to be really on the ball with military spec stuff, I bet they’ll have a good idea as to what kind of missiles you’d expect to see where.

You could definitely set up a (relatively rare) humvee variant with an avenger-style anti-air battery. Those are mounted with Stinger missiles, small, short range anti-air missiles most commonly fired from a man-portable launcher. I’m having trouble finding the exact specs of the missile, but again I bet Tenmillimaster could find you a chart. They definitely have a bunch of rocket fuel, explosives, guidance electronics, and sensors in them.
