### ISSUE TITLE
Remote controller can teleport foldable vehicle

### ISSUE THREAD

**Issue by ymber** [CleverRaven/Cataclysm-DDA#36963]
# Describe the bug
A vehicle controller can be used on a foldable remote vehicle to fold the vehicle. The folded vehicle item will then appear on the character's tile.

# Steps To Reproduce
1. Create a foldable remote control vehicle
2. Use a remote vehicle controller to fold the vehicle

# Expected behavior
Vehicles can't teleport.

# Versions and configuration
- OS: Linux
    - OS Version: Kernel 5.4.7-arch1-1
- Game Version: 0.D-11179-gf050457446-dirty [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by CoroNaut** [comment]
I understand this is a bug, but how in the world can the vehicle fold itself? Should probably need to attach small motors to fold it for each foldable frame to allow remote folding lol.
