### ISSUE TITLE
Disassemble Everything Disassembles Disassembly Results

### ISSUE THREAD

**Issue by Grubleafeater** [CleverRaven/Cataclysm-DDA#36978]
If you disassemble everything, disassembled components also get disassembled.

# Steps To Reproduce

Make a stack of electrical equipment of varying types, press 'B', and then select 'disassemble everything.

# Expected behavior

I expect that disassemble everything only disassemble items present when i hit disassemble everything, so i can disassemble large amounts of items and get the components rather than only raw material.

**Comment by Amoebka** [comment]
That's the intended behaviour. What you want is to "disassemble everything once", already in the game.

**Comment by Grubleafeater** [comment]
In that case, there's a issue where disassemble everything once only shows the time it takes to disassemble one of each stack. When I press 'B' over a stack of 10 TVs it says 1 hour to disassemble 1 tv, 10 hours to disassemble everything and 1 hour to disassemble everything once.

**Comment by RobertoVGoulart** [comment]
"disassemble everything" actually disassembles everything, including components.
"disassemble everything once" disassembles everything, but leaves the components alone.

I think your problem is not a lack of function, but an lack of clarity on the descriptions that the game gives of both functions

**Comment by Ker-Nes** [comment]
> 
> 
> "disassemble everything" actually disassembles everything, including components.
> "disassemble everything once" disassembles everything, but leaves the components alone.
> 
> I think your problem is not a lack of function, but an lack of clarity on the descriptions that the game gives of both functions

Lack of clarity and lack of correct time calculations, for both "everything" and "everything once" probably.

**Comment by Inglonias** [comment]
I agree that this could be made more clear, and that the time calculations are sketchy.

**Comment by Karthas077** [comment]
Looking through the code, "Everything Once" is showing the time to disassemble exactly one of each stack, and "All" is showing the time to disassemble all of each stack, but not the resulting components. Actually calculating a proper "All" time is somewhat impractical because the exact number of components recovered depends heavily upon item damage and player skill.
