### ISSUE TITLE
Penalties for gorging

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#36973]
**Is your feature request related to a problem? Please describe.**  
Having a full belly feels nice but it isn't ideal for combat and aerobics. Adding some minor penalties for overeating would help balance out the upper reaches of the food system.

**Describe the solution you'd like**  
I propose that we change the colour of "sated" to yellow, and "engorged" to red.
* Sated should apply a small token penalty to speed, about 2%, and increase fatigue by a small amount.
* Engorged should cause pain, fatigue, and a larger penalty to speed, more like 10%. It should also increase chance to vomit, which further increases as your stamina drops, to represent overexerting yourself on a dramatically overfull stomach.

It might be worth changing the current green "full" to "satisfied", add a new green value "full", and make "sated" into "overfull".

**Describe alternatives you've considered**  
These penalties could be more granular based on stomach contents, rather than on the vague states of "sated" and "engorged". That would be a preferable system if someone wanted to get a little fancier.

**Additional context**  
The system should be designed such that if you want to get really full in the safety of your base so that you have the energy to go hunting later, it's not a problem, but if you do it and then try to fight a horde of zombies you'll regret it.

This goes along with #36972 and shouldn't be done until that feature is done, so that survivors get more feedback on how they've eaten and can't accidentally gorge themselves too easily.

**Comment by Ker-Nes** [comment]
>  The system should be designed such that if you want to get really full in the safety of your base so that you have the energy to go hunting later, it's not a problem, but if you do it and then try to fight a horde of zombies you'll regret it.

Given that there doesn't seem to be any actual penalty for not eating so long you have the calories stockpiled, wouldn't this just incentive even more meta behavior, to eat a few days worth of food instead of actually carrying any? 

Furthermore, it also should be done alongside a rebalancing food's volumes, as there are a number of foodstuffs in the game that have low volume and unrealistically high calories for said volume. Similarly, high volume, low calorie foods (like many vegetables) seem to be fill just as much and take just as long to "pass out" from a character's stomach as eating really "heavy" foods, including all kids of meats. Digestion speed should vary with what type of food one eats for this to be work really well.

**Comment by I-am-Erk** [comment]
Sort of gratifying to see other people on the same track as me really.

**Comment by Alapaga** [comment]
I had the same tought process, as it is easy to lose a lot of weight in the current state of things, but it's hard to lose the "famished" status, even tho you're eating to the point of engorgement at each meal. The biases on what types of food provide what kind of satiety response is also something to consider. I noticed that the sugary foods provide a lot of pleasure compared to the fatty ones, with no drawbacks. Also, there's no decrease to the mood benefits of consuming multiple cookies/toast-ems for example. As a dabbling survivor, your choices for food might depend on your situation, and you're rewarded for the non-choices you have with poor health. I feel like to play cdda without simplified nutrition requires the player to have a degree in sports nutrition in order for their avatar to succeed in not being sick/ill. The average american dies eventually of being too unfit to survive the cataclysm.

**Comment by 1n17** [comment]
Good addition, some secondary effects to consider: increased thermogeneis (+warm), immune stress (-health), cell division promotion (+healing)
and a few more primary ones: lethargy (-focus), restlessness (harder to fall sleep)
