### ISSUE TITLE
Error when loading new game. 

### ISSUE THREAD

**Issue by RobertoVGoulart** [CleverRaven/Cataclysm-DDA#36970]
# Describe the bug 

An error message pops up before character creation screen. Game can continue normally after ignoring or skipping the message.

# Steps To Reproduce

1.Download version 0.D-Windows_x64-Tiles-10174
2.Try to Start a new game

# Expected behavior

No error

# Screenshots

![Image 2058](https://user-images.githubusercontent.com/20757625/72221386-0c0fee00-3539-11ea-891b-132c24f6cbeb.jpg)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-11235-g00699b2 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

Error doesn't happen on "0.D-Windows_x64-Tiles-10173"

**Comment by Kelenius** [comment]
Happens when loading a save file as well.

**Comment by Night-Pryanik** [comment]
Should be fixed by #36958. Please update.
