### ISSUE TITLE
Disappearing Pets

### ISSUE THREAD

**Issue by ashGlaw** [CleverRaven/Cataclysm-DDA#36988]
# Describe the bug

I found that when an animal, in this case a border collie, is in a wooden pet carrier, and the wooden pet carrier is disassembled, the animal in the carrier disappears entirely

# Steps To Reproduce

1. Spawn a wooden pet carrier with an animal in it
    1.5 Or, if that's not possible just spawn a friendly animal and use the empty carrier on it
2. Spawn a toolbox
3. Disassemble the wooden pet carrier
4. Marvel at the disappearing animal

# Expected behavior
The animal should disappear

I expect a loaded animal object to disgorge the animal if it's disassembled or destroyed. If it's destroyed, the animal might take some of that damage, too.

# Versions and configuration

- OS: Windows 10
    - OS Version: 10.0 1903
- Game Version: 0.D-11238-gce2f161 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Bionic Slots [cbm_slots],
    Classes and Scenarios Mod [more_classes_scenarios],
    Sleep Deprivation [sleepdeprivation],
    Stats Through Kills [stats_through_kills],
    Magiclysm [magiclysm],
    Roadheader and other mining vehicles [Heavy miners],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by mlangsdorf** [comment]
I'm pretty sure vehicle mounted carriers special case this; it shouldn't be too hard to migrate that code into iuse.cpp.

**Comment by scrotty** [comment]
Typo in your "Expected behavior" section, @ashGlaw. You meant to type: "The animal **not** should disappear".

**Comment by scrotty** [comment]
What do you think of this solution: https://github.com/CleverRaven/Cataclysm-DDA/pull/37084?
