### ISSUE TITLE
Military Operations map reveals animal shelters

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#36982]
# Describe the bug

Military operations maps reveal nearby animal shelters. I suspect that this is caused by a bad regex that searches for terrain with the word "shelter" in it.

# Steps To Reproduce
1. Find a Military Operations map
2. Use it
3. Observe that animal shelters are revealed.

# Expected behavior
Why are animal shelters important enough to mark on a military map?

# Screenshots
![image](https://user-images.githubusercontent.com/2125926/72224213-ce659200-3545-11ea-81cb-88039f85cc1e.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.D-11235-g00699b2 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    No Rail Stations [No_Rail_Stations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Classes and Scenarios Mod [more_classes_scenarios],
    Simplified Nutrition [novitamins],
    No Ants [No_Anthills],
    No Fungal Monsters [No_Fungi]
]

**Comment by Inglonias** [comment]
Potentially related to #32310

**Comment by Lamandus** [comment]
> Why are animal shelters important enough to mark on a military map?

to boost morale. The world went downhill, but look at that cute puppy!

**Comment by CoroNaut** [comment]
Who knows, there could be a military complex below... with a cute puppy cover story!

**Comment by Inglonias** [comment]
It also reveals silos. Like farm silos for grain. I suspect the cause is similar.

**Comment by Lamandus** [comment]
> 
> 
> It also reveals silos. Like farm silos for grain. I suspect the cause is similar.

"Sir, we located one of the silos!"
"Perfect! Maybe there are still some warheads to be taken care of"
"Oh, THAT kind of silos."
