### ISSUE TITLE
Add effect intensity to spells

### ISSUE THREAD

**Issue by foulman** [CleverRaven/Cataclysm-DDA#36984]
**Is your feature request related to a problem? Please describe.**  
There is currently no way to have the actual ability with spells control the effects on the player or target, you could cast the same spell multiple times and have it stack, but there is no way to connect ability with effect intensity. This limits the usefulness of effects in regard to the spell system and I think they are underutilized because of it.

**Describe the solution you'd like**  
Implement a pass through so that the intensity, based on spell level, is applied when the effect is applied to the target. My suggestion is to create 3 new fields:

"min_effect": 1
"max_effect": 5
"effect_increment": 0.5

This way if you had a spell that made the player drunk, which has 5 intensity levels, and using those numbers, a first level caster would get the player buzzed, a 10th level caster would practically put themselves into a coma. No need to cast it more than once. This will allow more dynamic scaling for numerous existing spells, like Grotesque Enhancement, Haste, Bless, etc, and probably allow them to be nerfed significantly at lower levels while providing even more benefit as the player trains.

**Describe alternatives you've considered**  
Specifying a list of levels and the separately coded effect that would be used rather than the default effect, resembling this: 

"alt_spell_effects": { "haste1": 2, "haste2": 4, "haste3": 6 }

**Comment by FuelType-Memes** [comment]
Should it allow for casters to "control" the intensity? So a lvl 10 caster would be able to cast a lower intensity spell if need be

**Comment by foulman** [comment]
> 
> 
> Should it allow for casters to "control" the intensity? So a lvl 10 caster would be able to cast a lower intensity spell if need be

I would support that in concept, even being allowed to choose the level of the spell rather than just the effect intensity, but I fear it would be too complex to implement without a lot of effort. I can see cases where you might only want or need certain levels of power, and might engage in a trade-off of mana expended for it. 
I've been looking into using spell learning to teach you a Mk. II version of the same spell when it's maxed out so that upgraded results are possible and progression can continue. I think I would be quite satisfied with either of the proposed solutions, and it would lead to less of me having to do tiered spells.
