### ISSUE TITLE
Crashing with segfault in Build 10174+ 

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [CleverRaven/Cataclysm-DDA#36980]
# Describe the bug
Game crashes with segfault https://pastebin.com/AbhSXRmQ after displaying https://pastebin.com/UHFd40dU.

# Steps To Reproduce
Upgrade from Build 10173 to 10174+

# Expected behavior
Not crashing.

# Versions and configuration
Can't do. Game goes kaput

**Comment by eilaattwood** [comment]
Does it crash during load? My game is fine, can't confirm crash.

**Comment by ZhilkinSerg** [comment]
Your update process is invalid. You should not unpack archive of new version to existing folder with old version. You need to unpack to new empty folder.

**Comment by Unrepentant-Atheist** [comment]
True, that what it was. Much obliged.
