### ISSUE TITLE
Butcher/Disassemble UI defaults to first option when selecting with ENTER key

### ISSUE THREAD

**Issue by Kilvoctu** [CleverRaven/Cataclysm-DDA#37000]
# Describe the bug

Butcher/Disassemble UI window defaults to first option when selecting with the ENTER key.

# Steps To Reproduce

1. Have a pile of multiple items
2. Move cursor to any menu option aside from the first
3. Hit ENTER key

# Expected behavior

Selecting a menu option with the ENTER key should correctly choose that option.

# Screenshots

Video demonstration
https://www.youtube.com/watch?v=YDvbukqwMgg

# Versions and configuration

 - OS: Windows 7 SP1 and Windows 10 Pro
 - Game Version: 0.D-11259-g406655c04e
 - Graphics version: Tiles
 - Mods loaded:
  "dda",
  "no_npc_food"

# Additional context

Issue only apparent with hitting ENTER. Selecting each option with their respective keyboard shortcut works properly.

**Comment by Trioct** [comment]
The video was very useful in figuring out that it was the fault of going through the action menu. For now though, pressing the butcher hotkey to directly open the menu should work.

**Comment by Kilvoctu** [comment]
Oh I didn't even think about just using the hotkey .
Thanks for determining the cause and making that PR. I was looking through game.cpp and couldn't figure it out.
