### ISSUE TITLE
Decide (and enforce) where to put new mods for distribution

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#37017]
**Is your feature request related to a problem? Please describe.**  
It's unclear where mods are supposed to go for distribution. We have a few places and mod distribution methods. The most common one I see and the most problematic one in the long term is simply distributing more and more mods with the game itself by including the mods in the game's repo. JSON mods aren't usually all that big in terms of file size, so it's not too big a concern, but it does sort of feel like an endorsement of each and every mod in the game.

We have a [NexusMods page](https://www.nexusmods.com/cataclysmdarkdaysahead/) already, but as far as I can tell, it's pretty barren of mods.

**Describe the solution you'd like**  
A written set of standards for how to contribute mods to the game. Should we have people continue to submit mods as pull requests for distribution with the game files? Should we start making use of the existing NexusMods pages? Should mods be placed in the Discourse or Discord forums for download? Whatever answer is decided on, it should be written down, documented, and most importantly, enforced. I don't think that including every single mod for the game with the repo download is a sustainable practice.

**Describe alternatives you've considered**  
It's possible that I'm making mountains out of molehills here. If the repo maintainers don't see this as a problem, I'm willing to take their word for it and close the issue. I also realize that 0.E's imminent release throws a wrench into any kind of vast mod reorganizing project that would be undertaken, and that this sort of thing might be better tackled after 0.E is finalized.

**Additional context**  
An additional wrinkle is that some mods also make/require source code changes, Magiclysm being the biggest example I can think of. That mod required a whole spellcasting system to be put in the game in order to work. How something like that would be reorganized is beyond me.

**Comment by Zaragata** [comment]
What if mods that don't require changes in master belonged to this new distribution group? While mods that require to be compiled with the game get a new classification, like `expansion`.

**Comment by Inglonias** [comment]
It was pointed out to me that distributing mods in the repo encourages the people who accidentally break the mods to update them as needed, and helps keep them working.

As an example, when I made those battery changes last year, I had to ensure that any battery powered tools added by mods still worked after the overhaul. Without that, it would have fallen to the mod authors to make those changes, which would have resulted in some incompatible mods if those authors were no longer around.

**Comment by KorGgenT** [comment]
So the main reason to add mods to the repo is simple:
people who make changes that can affect the mods have an obligation to make sure the mods still work when they make their changes. This makes mods in-repo almost always up to date with the release they come with, as opposed to mods that are third-party, they could be made for any release whatsoever, and players could get confused and download the wrong version of the mod. 

(i finished writing this before i read the above reply, and it's basically restating it)

**Comment by Inglonias** [comment]
I admit that the main reason this issue exists is because I find it strange that most of the mods for the game are distributed with the game itself (at least if you're using the launcher), but it sounds like this isn't a major concern.

**Comment by KorGgenT** [comment]
I would say the linked PR solves this issue. I have heard that some people are looking into better support for a third party mod manager or something of that nature, as well.
