### ISSUE TITLE
Using electronic cigarette through "a" key won't satisfy nicotine addiction

### ISSUE THREAD

**Issue by Foxtrot-Uniform42** [CleverRaven/Cataclysm-DDA#37039]
# Describe the bug:
Using electronic cigarette through "a" key won't satisfy nicotine addiction

# Steps To Reproduce:
1. Have nicotine addiction drawback
2. Use electronic cigarette via "a" button

# Actual behavior:
Nicotine addition hasn't been satisfied.

# Expected behavior:
Nicotine addition has been satisfied

# Versions and configuration:
- OS: Windows
- OS Version: 10.0 1809
- Game Version: 0.D-11308-g7b2fa6d [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    C.R.I.T Expansion Mod [crt_expansion],
    Icecoon's Arsenal [ew_pack],
    More Survival Tools [More_Survival_Tools],
    Makeshift Items Mod [makeshift],
    Craftable Gun Pack [craftgp],
    Garden Pots [growable-pots],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Mutant NPCs [mutant_npcs],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    Mythical Martial Arts [MMA],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Mapgen Demo [mapgen_demo],
    Urban Development [Urban_Development],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Folding Parts pack [deoxymod],
    Tanks and Other Vehicles [Tanks],
    SpeedyDex [speedydex],
    Prevent Zombie Revivication [no_reviving_zombies],
    Classic Roguelike Classes [RL_Classes],
    Classes and Scenarios Mod [more_classes_scenarios],
    Disable NPC Needs [no_npc_food],
    Fuji's Military Profession Pack [fuji_mpp],
    Stats Through Kills [stats_through_kills]
]

**Comment by Night-Pryanik** [comment]
The same as #20830.

**Comment by Trioct** [comment]
I don't think they're the same as the focus of this issue is that using vs consuming produce different results, consuming ('E') an ecig satisfies nicotine withdrawal, but using ('a') does not.

**Comment by Nedptr** [comment]
this should be in iuse::ecig() and iuse::chew() since caffeinated chew gum also dosnt seem to work as expected.

**Comment by Foxtrot-Uniform42** [comment]
> I don't think they're the same as the focus of this issue is that using vs consuming produce different results, consuming ('E') an ecig satisfies nicotine withdrawal, but using ('a') does not.

Thanks, I should have mentioned that in the first place.
