### ISSUE TITLE
Alloy Plating CBMs add encumbrance, use no slots

### ISSUE THREAD

**Issue by vlad1492** [CleverRaven/Cataclysm-DDA#37032]
Problem: 

Alloy plating adds a layer of armor to the exterior of the body. 
While thin and light this would still add some bulk and interfere with other equipment. 

As it occupies no internal space it should use no slots. 
Right now it adds no encumbrance but does take up internal slots. 

Proposal: 
Change the Alloy Plating CBM to use no slots, instead to add 4 encumbrance to the body part in question. 

**Describe alternatives you've considered**  
Do nothing. 
Remove slot cost without adding encumbrance. 

Additionally the description should include what the armor value is. Other mutations and CBMs include this information, Alloy Plating does not.

**Comment by Fris0uman** [comment]
> adding encumbrance

well maybe, but on the other hand it's subdermal stuff so I guees the idea was that it becomes part of your amr and doesn't hinde your movement.

> removing slot cost

Definitly not, this does take space on your body there's no reason for it to be a free CBM as far as the slot system is concern. Plus it's actually a good CBM I don't think making it free is good balance.

> armor value in description

Yes this would be nice. Even nicer would be to have it automatically display without editing the description.

**Comment by vlad1492** [comment]
Description seems to indicate it is not subdermal. 
'Alloy plating that replaces the flesh on the user's arms/legs/torso/etc'
'Provides passive protection and can be used in conjunction with bionic martial arts ' (For blocking) 
Blocking suggests it is surface as well, the Subdermal Carbon Filament CBM offers no such advantage though it has similar armor values. 

If the point of the system is to encourage meaningful choices within a realistic frame then this works. 
You add permanent irreducible encumbrance for some armor that can't be damaged and adds no weight.  Not free, and also not taking up internal volume. 

This stuff is apparently a nod to 'Robocop', given the bionic police job description.
Armor that makes you tougher but quite visibly a cyborg.
The subdermal stuff  is for the sneaky covert types.

**Comment by vlad1492** [comment]
Also, there is a precedent for using encumbrance to balance CBMS.  A Gasoline Fuel Cell only needs 8 slots in the torso but adds 5 encumbrance there, while an Ethanol Burner CBM adds no encumbrance but requires 26 torso slots. 

I don't know the relative power output offhand. Assuming they are equal, does that mean that 18 slots is worth 5 encumbrance?

**Comment by Amoebka** [comment]
I would like to point out that alloy armors are good cbms only without slots enabled. 3 bash/cut for a third of body part's slots is really bad otherwise.

Whatever superalloy is, it should also probably give more protection than clothing-quality leather (6 bash/cut). It was fine to have small benefits when they were free, but bionics that cost a lot of slots should actually do something.

**Comment by Fris0uman** [comment]
Ethanol burner should probably give encumbrance and/or give out heat, it was made way before Gasoline fuell cell and even if its working was recently changed it was not rebalanced in term of encumberance and slot use.

Maybe  armor plating should take less slot, but not no slot.  I guess since the slot system is currently off by default there's not much attention on it. Slot use as a whole might deserve a good look over.

**Comment by vlad1492** [comment]
I agree
I hesitated asking for a buff to the alloy plating because that seemed like a separate issue. 

Using Cata++  I see that MBR(Empty) is rated Bash 8 and Cut 16.  MBR(Superalloy) adds 8 superalloy sheets to increase the armor to Bash 20 Cut 25.  
Superalloy Dog Outfit uses six sheets and offers 12/12
A single sheet weighs .90kg, the torso CBM weighs 3kg, 

For comparison:  Plate Armor is 16/16, Chainmail 15/15, bone 8/10, leather 8/8 , chitin 12/16

I think bumping it to 9/9 is a good fit. You get some decent protection but are far from bulletproof.

**Comment by Zireael07** [comment]
MBR are being phased out, so aren't a good thing to compare to.

**Comment by vlad1492** [comment]
Question on alloy plating cbm - I am trying to modify it to increase armor and remove slot cost.  I found the slot cost and description part of the json, but can't find where to change the armor value provided.  Help?

**Comment by Fris0uman** [comment]
It's hardcoded, see https://github.com/CleverRaven/Cataclysm-DDA/pull/37558
