### ISSUE TITLE
No sci-fi weapons still spawns sci-fi weapons

### ISSUE THREAD

**Issue by TheGamingFox1911** [CleverRaven/Cataclysm-DDA#37033]
# Describe the bug
Using the no-scifi weapons mod doesn't blacklist newer energy weapons like the PPA-5 or the XM34

# Steps To Reproduce

1. Use the no sci-fi weapons mod
2. open up the spawn lists
3. Choose one of the tables with energy weapons.
4. It will still say energy weapons are going to spawn

# Expected behavior

No-scifi shouldn't spawn any future weapons at all, as that is what it's meant to do

# Screenshots

![image](https://user-images.githubusercontent.com/52058797/72309948-0eac3980-3646-11ea-9d24-48b34605232e.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-11280-gd49026a [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Bens GF recipes [Tolerate_This],
    Craftable Gun Pack [craftgp],
    Garden Pots [growable-pots],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Hydroponics [hydroponics],
    Mining Mod [Mining_Mod],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Mapgen Demo [mapgen_demo],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Bionic Slots [cbm_slots],
    Classes and Scenarios Mod [more_classes_scenarios],
    Classic Roguelike Classes [RL_Classes],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Fuji's Military Profession Pack [fuji_mpp],
    Roadheader and other mining vehicles [Heavy miners],
    No Survivor Armor [no_survivor_armor],
    No Sci-Fi Equipment [no_scifi],
    No Fictional Guns [no_rivtech_guns],
    No Ants [No_Anthills],
    No Bees [No_Bees],
    No Fungal Monsters [No_Fungi],
    No Acid Zombies [No_Acid_Zombies],
    No Big Zombies [No_Big_Zombies],
    No Explosive Zombies [No_Explosive_Zombies]
]

**Comment by ZhilkinSerg** [comment]
Closed in #37034
