### ISSUE TITLE
Hydrogen Fired Engines&Hydrolysis Based Hydrogen Production

### ISSUE THREAD

**Issue by Grubleafeater** [CleverRaven/Cataclysm-DDA#37055]
Essentially, a lategame option to add a long-range non-electric vehicle power that still depends strongly upon infrastructure. Hydrogen would be produced via electrolysis and thus be highly dependent on a power grid(for now, it'd have to be vehicle based) in order to produce in any sort of bulk. On the flip side, it should be easier to store than electrical power is in much larger amounts, allowing you to venture much further from your home base without constantly pausing or moving at low speed.

Additionally, aftershock could add in a fusion engine that provides large amounts of engine power and electrical power.

There would be other uses for hydrogen too. For example, hydrogen was the predecessor to oxyacetylene, and was phased out due to economic concerns. In fact, it's better for some applications which require a pure flame.

Implementation wise, it should be possible by making modified batteries and modified recharging stations, called something like 'Hydrogen Storage Tanks' and 'Electrolysis System' respectively, burning through battery power in order to slowly produce hydrogen.

**Comment by l29ah** [comment]
How do you suggest compressing and storing hydrogen in a post-apocalyptic setting? 70MPa is no joke.

**Comment by kevingranade** [comment]
Uncompressed hydrogen is basically worthless as a fuel and compressed hydrogen is out of reach, not going to be adding this.
