### ISSUE TITLE
Movement physics need tweaking

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [CleverRaven/Cataclysm-DDA#37058]
It seems to me that the physics behind momentum and stuff needs some tweaking. Because I'm being stopped by lousy wooden fences in my 32 ton vehicle while moving at 12-20 km/h.

# Steps To Reproduce

1. Have 32 ton vehicle
2. Move at 12 km/h min.
3. Crash into wooden fence
4. Be stopped.

# Expected behavior
Steamroll the fence to nirvana.

**Comment by Night-Pryanik** [comment]
Long-standing issue. It's taken into consideration in #20111.
