### ISSUE TITLE
Unload changed

### ISSUE THREAD

**Issue by Archemenos** [CleverRaven/Cataclysm-DDA#37061]
# Describe the bug
when unloading nearby objects, the object is added to inventory and the unloaded part is dropped.  inventory is displaced by the unintentionally picked up object.

# Steps To Reproduce
build 10192 
with nearly full volume, go unload a gun on the ground. the gun gets picked up, the ammo is dropped, and some inventory is dropped to accommodate the weapon. 

# Expected behavior
unloading a gun prior to 10191 put the ammo in inventory and left the weapon where it was. inventory should not be displaced to fit the ammo. insufficient space for the unloaded part should just drop the unloaded part

i expect it because whenever i try to pick something up without the space for it i get notified there is no room. and I've unloaded many things without picking up the item.  

# Versions and configuration
windows 10
10192 0.D-11292-ge1f432d (tiles)
aftershock
magiclysm
fujis more  buildings
vehicle additions
crit expansion

only occurs after "fix unload visitable errors" PR

no crash, just very annoying to go reload your gas mask and find you have 3 empty filthy masks and zero gas mask charges. or to grab some needed ammo and then realize you left your halligan bar and pickaxe somewhere, but you have 5 filthy unloaded M4's.

**Comment by KorGgenT** [comment]
to fix this issue i suggest a rework of the unload function as a whole, as the pr in question was the least intrusive way to fix the error it was trying to fix. I agree that we want this to work better than this.

**Comment by RDru** [comment]
+1
This is very annoying
