### ISSUE TITLE
Wrong case in bedding.json for volume units.

### ISSUE THREAD

**Issue by XerxesPST** [CleverRaven/Cataclysm-DDA#37068]
Game version:
0.D-11330-g7fa3275
Build #10195 - January 15, 2020 at 7:51:07 AM +0100

Operating system:
Windows 10

Tiles or curses:

Mods active:

### Actual behavior
 DEBUG    : Error: data/mods//dda/../../json/items/generic/bedding.json: line 28:14: unrecognized volumetric unit

    "description": "Hiding under here will not protect you from the monsters.",
    "weight": "1123 g",
    "volume":
             ^
              "15 l",
    "price": 5500,
    "to_hit": -1,

 FUNCTION : bool main_menu::load_character_tab(bool)
 FILE     : src/main_menu.cpp
 LINE     : 1059

### Steps to reproduce the behavior

Load a saved game.

**Comment by Kilvoctu** [comment]
Update to Build #10196
