### ISSUE TITLE
The absolute state of stimulants

### ISSUE THREAD

**Issue by 1n17** [CleverRaven/Cataclysm-DDA#37069]
# Describe the bug
Stimulants do not provide CNS stimulation effects expressed as stat boosts nor proper fatigue mitigation (~presumably due to sleep deprivation mechanics~).
_PS. After examining sleep deprivation code I removed it from the list of suspects, as everything seems to be properly gated._

# Steps To Reproduce
use stimulants, preferably at fatigue level `tired` or more
examine effects while effect active
examine fatigue after effect ends

# Expected behavior
Stimulants exhibiting remotely accurate approximation of their CNS related effects.

# Additional context / rant begin
Whilst old, stat boosting effects of stimulants weren't perfect they did reasonable job of approximating their effects, but the new model is simply outrageous:
- doing things real stimulants aren't doing - boosting stamina recovery - in reality stimulants only mask 'stamina' type fatigue, if you 'run out of breath' (ie. deplete blood oxygen levels due to cardiovascular system not meeting the demands) while on amphetamine or cocaine you're still out of breath, just might not realize/be able to ignore it until collapsing
 _(NB. proper way to model this would be not losing speed as stamina depletes nor preventing continuing running further once it does, although with static stamina pool and no fitness level tracking that would be somewhat problematic)_
- and either not doing the main thing they are supposed to do and are known for - the CNS **stimulation** part - which in game translates to variety of things mediated by: focus and its recovery rate; various stat, but mainly intelligence and perception rolls; and speed
- or doing it very poorly - fatigue/'tiredness' mitigation. Many factors that make up CNS fatigue experience are effectively negated with stimulant use and while with prolonged use accumulation of remaining factors along with side effects will **eventually** catch up, it should be possible for the determined user to keep perfectly functional and awake for a few days by using stimulants, and low to moderate use should not suffer any fatigue rubber-banding effects that seem to be currently occurring
_(NB. they are invalid anyway - you can't catch up on sleep, but acceptable approximation to toxicity/exhaustion effects that prolonged stimulant use would incur)_

**Comment by Brian-Otten** [comment]
I can somewhat understand why stimulant buffs to the old extent were taken out, but stimulants doing next to nothing right now puts them in a weird place.
As for the focus system mitigating penalties from low focus would be great if possible, letting players keep working effectively (and learning some) under adverse conditions.

**Comment by 1n17** [comment]
> I can somewhat understand why stimulant buffs to the old extent were taken out

Well, it is 'a way' to deal with problems, but one of those 'cure being worse than the disease' type. Problems stemmed from their near infinite stackability and quite generous scaling, and perhaps lack of side effect modeling, not existence of stat boost per se.

**Comment by kevingranade** [comment]
If I'm reading you correctly, you're suggesting stimulant level should temporarally offset or mask fatigue instead of removing it, I agree that's how it should work.
In a similar way, it seems to have a strong case for offsetting focus drain when practicing, the case for increasing focus gain looks weaker.
