### ISSUE TITLE
Error when firing upon turret

### ISSUE THREAD

**Issue by RobertoVGoulart** [CleverRaven/Cataclysm-DDA#37077]
# Describe the bug

When firing upon a turret while debugging, the following error appears:

 DEBUG    : Attempted to fire zero or negative shots using handheld laser cannon

 FUNCTION : int player::fire_gun(const tripoint&, int, item&)
 FILE     : src/ranged.cpp
 LINE     : 370

# Steps To Reproduce

1. Make a player with a gun, magazine, and some ammo.
2. Spawn a laser turret.
3. Fire on it.
 (The error doesn't always happen)

# Expected behavior

No error

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-11335-gcd00378 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

Save file: 
[Rowan.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4065032/Rowan.zip)

**Comment by Night-Pryanik** [comment]
Tested on 0.E-2149. Laser turret fired several hundreds of "shots" at me, no errors popped. 
Closing as unconfirmed.
