### ISSUE TITLE
Butchery and stamina

### ISSUE THREAD

**Issue by 1n17** [CleverRaven/Cataclysm-DDA#37071]
# Describe the bug
Butchery activity drains stamina.

# Expected behavior
Perhaps other than dismemberment, butchery activities not draining any stamina - fatigue costs in activity definitions should be sufficient.

# Versions and configuration
any remotely recent

**Comment by Zireael07** [comment]
This is by design - butchery is meant to drain stamina, it takes a lot of effort.

**Comment by 1n17** [comment]
> it takes a lot of effort

Kinda, few parts actually take serious effort eg. hoisting, chopping/sawing big bones. But otherwise the butcher goes at leisurely pace - certainly not winding himself, unless we taking some accord work for illegals or something.

Then there is absolutely no way to justify dissection draining stamina, especially already going at snails pace of 44 minutes per corpse.

**Comment by Brian-Otten** [comment]
Dissecting could perhaps do with having the stamina cost removed. Butchering using stamina sounds good to me, i want my character to do it as fast as possible in almost all situations, so i would rather not have it cost no stamina and cost slightly more time.

**Comment by TechyBen** [comment]
IIRC using the toggle "run"/"walk" to change from "quick as possible" to "take your time" butchering was discussed previously. No idea how hard/useable/GUI confusing it would be though. The activation text could just use a little "toggle run/walk for effort/casual fatigue on butchering" at the top of the window to help new players if such a change is implemented.

**Comment by 1n17** [comment]
Bah, was about to propose that, but it would only be applicable to quartering, dismembering, skinning, dressing and quick butchery, as there isn't enough effort requiring components to full butchery and dissection to warrant dual speeds nor stamina drains.

**Comment by 1n17** [comment]
NB. slightly off topic - dissection is another can of worms, while taking 40+minutes on your first try might be believable, with any experience/first aid training one should be able to quickly (~10m) open the corpse, scan main cavities for bionics, then either offer removing them in some GUI with additive time costs or instruct the player on having to lug it to autodoc for removal, or even have both options available.

**Comment by l29ah** [comment]
Currently dissecting while running both takes more time and drains stamina, this is fucked up.

**Comment by kevingranade** [comment]
Working as intended.

**Comment by l29ah** [comment]
Can you confirm that doing the same job in the running movement mode is strictly worse than in the walking, this fact is not documented anywhere, only add extra micro-management know-how to the game, and in fact works as intended?
