### ISSUE TITLE
Add clay to lab item spawns.

### ISSUE THREAD

**Issue by scorpion451** [CleverRaven/Cataclysm-DDA#37097]
**Is your feature request related to a problem? Please describe.**  
Only clay crucibles exist now, so lab starts require access to clay.

**Describe the solution you'd like**  
Clay is an extremely common lab material with uses ranging from chemical catalyst to an easy way to jury-rig equipment setups. It really should be a common drop in labs

**Describe alternatives you've considered**  
The partially excavated room could also have clay deposits added as a common feature.

**Additional context**  
In addition to the clay crucible, this opens up limited access to other basic survival tools that have become very important since the lab start option was initially added.

**Comment by anothersimulacrum** [comment]
This is totally backwards logic, clay shouldn't be added to lab spawns because you're no longer able to craft metal crucibles.
Clay should be added to lab spawns if it's something they'd actually have.

**Comment by ZhilkinSerg** [comment]
That is a ridiculous request.
