### ISSUE TITLE
Add 'examine' keybind to all inventory-related menus.

### ISSUE THREAD

**Issue by WeaverThree** [CleverRaven/Cataclysm-DDA#37091]
**Is your feature request related to a problem? Please describe.**  
I sometimes have to go out of dropping/wearing/other selection menus to remember what the heck an item is / is for / can be done with. 

**Describe the solution you'd like**  
A keybind that pops up the item-examine interface (enter in inventory, e in adv. inventory) on items in these windows: 
 - wear 
 - take off
 - sort/re-layer armor
 - wield
 - use 
 - consume and it's eat/drink/medicine variants
 - butcher
 - disassemble
 - maybe the compare items selection screen for least surprise
 - adding it in the main inventory window and advanced inventory on the same key for least surprise

Since many of these need to work with inventory letters, there aren't a lot of options for keys to pick. I'd suggest backtick (`) or F1.

**Describe alternatives you've considered**
Could also be done with an always-on panel displaying the selected item like in the examine-tile and pickup screens, but that would require sacrificing screen space available to things like the consume menu and also reworking more UI flow stuff.

**Comment by scorpion451** [comment]
I'd suggest keeping it as "e", because that's what muscle memory always has me pushing when I reflexively try to do this on the screens where this would apply.
