### ISSUE TITLE
How to implement military rocket fuel.

### ISSUE THREAD

**Issue by Brian-Otten** [CleverRaven/Cataclysm-DDA#37104]
**Is your feature request related to a problem? Please describe.**  
If #37052 gets merged we will be able to disassemble military rockets. What #37052 does not yet add is a component survivors might definitely want to acquire, military rocket fuel.
The question is how we would like to implement this in the game. There are a couple of way i can imagine.

**Describe the solution you'd like**  
I considered the issue and thought of some approaches we might take.

1. Keeping it simplified:
 If we assume the survivor only wants to use the rocket fuel for haphazard constructions or it's incendiary qualities, it might be enough to keep it as simple as "military rocket fuel". This would currently only be used as an alternative fuel in the homemade rocket launcher AFAIK, but there is room for more rocket fuel related recipes later.
 
2. Use military terms and variants:
If we want to reload military grade missiles just using any rocket fuel would not work out, in this case we would probably want to add the exact type of rocket fuel used in each rocket to the game, and let them be used where applicable. This would mean adding potentially over a dozen different rocket fuels and places to use them, and would be a rather big, if interesting project.

3. Decide military rocket fuel is unsuitable
If we think the military rocket fuel is unsuitable the survivors needs, we could exclude it or include it as the "incendiary" item, so it wouldn't be used as rocket fuel but only for its exothermic properties.

**Additional context**  
This issue is intended to open discussion, so i'd love to hear if others had ideas on how to handle this issue, to see what approach might be best implemented into the game.

**Comment by 1n17** [comment]
https://en.wikipedia.org/wiki/Ammonium_perchlorate_composite_propellant
oxidizer powder - ammonium perchlorate
current incendiary - oxy_powder with magnesium/aluminium, so APCP in powder form

Thus question becomes
 - either to leave incendiary as it is (APCP is not completely unsuitable as an incendiary but not something it is used as) 
- or change recipe to match proper incendiary (white phosphorus or magnesium, but that could result in some recipe inconsistencies becoming more pronounced eg. flasbang using white phosphorus - this is not immediately jarring at current level of abstraction),
- or differentiate incendiary further.

Next step would be to provide high range variants of existing ZS/RCandy based rockets that use APCP

**Comment by mlangsdorf** [comment]
I'm pretty sure we don't want people reloading military grade rockets and missiles. Aren't all the military grade rockets and missiles in the game solid fuel?  I don't think it's feasible with the tools that a survivor would have to disassemble a couple of M72 LAWs and create a TOW missile.

I don't have any opinion on the potential use of military grade rocket fuel as an incendiary versus as an explosive.

**Comment by Brian-Otten** [comment]
Yes, as far as i can tell most everything the player can find in the game now uses solid rocket fuel. I personally lean towards having it ingame as "solid rocket fuel", because some cursory research is showing it would not be suitable for most explosives. You could add it as an alternative to the homemade rocket fuel in the improvised rockets to start with, and we could see where the survivor might eventually use it elsewhere.

**Comment by kevingranade** [comment]
I only see two feasible-ish things a survivor would want to do.
1. Harvest a whole rocket motor, so you have a "RPG-7 motor" that can then be incorporated into a homemeade rocket.
2. Harvest the fuel itself, which AFAIK is not going to be suitable to re-packing into a motor, so unless chemical extraction gets involved it can probably be represented as some volume of "solid rocket fuel" as you outline (i.e. we represent more energetic fuels as a larger volume of a lower energy abstract fuel).
