### ISSUE TITLE
Are some labs made to be extremely massive?

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#37101]
# Describe the bug

I found this absolutely massive lab and what is shown in the pictures is probably like 80% of it until I gave up looting the rest of it because it took too many real-life days to go through lol.

It looks like it is a lab that is supposed to be generated because of the very uniform layout on Z-2, but its still upwards of 450 map tiles of lab from Z-2 to Z-9 and is only accessible through subway on Z-4. There is only forest and plains above the lab on Z-0, no structures anywhere nearby.

# Steps To Reproduce

1. Find natural occurance or if its possible to spawn in such a structure?

# Expected behavior

The lab is just too darn big, its absolutely massive, it started getting boring after the first 100 lab tiles, but I just so happen to be a completionist and kept going. I regret it, because its >450 map tiles large. I expect lab to house a reasonable number of scientists, this is very near to an underground CITY.

# Screenshots

Aligned at the blue pointer:
[Z-2](https://user-images.githubusercontent.com/24307650/72493442-06433280-37ef-11ea-9f4e-92b5f2ee42dc.PNG), [Z-3](https://user-images.githubusercontent.com/24307650/72493813-0263e000-37f0-11ea-9638-f95706560eb7.PNG), [Z-4](https://user-images.githubusercontent.com/24307650/72493835-1871a080-37f0-11ea-86a9-40f3cbff6768.PNG), [Z-5](https://user-images.githubusercontent.com/24307650/72493944-62f31d00-37f0-11ea-88f5-2d233757f35e.PNG), [Z-6](https://user-images.githubusercontent.com/24307650/72493950-6ab2c180-37f0-11ea-957f-0c379769ed76.PNG), [Z-7](https://user-images.githubusercontent.com/24307650/72493956-7605ed00-37f0-11ea-9c55-deefda615d0b.PNG), [Z-8](https://user-images.githubusercontent.com/24307650/72493965-7b633780-37f0-11ea-81aa-0722f369e26f.PNG), [Z-9](https://user-images.githubusercontent.com/24307650/72493972-7e5e2800-37f0-11ea-945d-d0ef8cb6c086.PNG)
(the %'s are rock-only map tiles that I revealed with debug clairvoyance artifact looking for a bug)

# Versions and configuration
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-11103-gbd3a2e3 [32-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    No Fungal Monsters [No_Fungi],
    Disable Religious Texts [no_religious_Texts]
]

**Comment by molkero** [comment]
Looks like the central lab complex, it's massive.

**Comment by Brian-Otten** [comment]
I don't think the problem here is the size of the central lab, which i think is a very neat location, but that there is not quite enough variation in tiles/rooms for it to be so large. After 10-20 map tiles you have probably seen most variations the lab has to offer, and after 100+ tiles you are probably bored  but don't want to stop because it is still the best place to loot in the game.

The (central) lab probably needs more variation in some form, for example, i don't think it would be amiss if it was more likely to randomly contain really nasty enemies in the hallways, chosen from a large list.
Think skeletal brute, kevlar hulk, shoggoth, flaming eye, a group of migos, etc.
This would add some more dynamic risk to keep you on your toes rather than the main risk being losing focus and walking into a turret.

**Comment by 1n17** [comment]
> shoggoth

That's probably bit too much. Although I might be biased, since my last encounter with one was in ant infested lab, blasted thing fed on all the rocks and multiplied several times - not fun times.

**Comment by CoroNaut** [comment]
I would disagree with them being the best place to get loot in the game, the military bunkers and normal-size labs are superior. I would even take a frozen normal-size lab and explore 100% of it over this central lab. Introducing new and harder enemies to the central lab would make it more variant which I like, but require the player to take even longer than a real-life week to go through the whole central lab. 

There is also the problem of loot that I didn't mention, I don't take a lot of loot like other players, mainly mutagens, guns/ammo (not a lot of guns), and the occasional rare chemicals, and finales. The high-volume rucksack, one of the highest volume backpacks in the game, still took upwards of 20 trips back to the subway on Z-4 (specifically south subway).  This was the only way out. Then I had to go through the subway (like 70 map tile west and 60 map tile down), through a medium lab, then I got to the surface with my car. I just stashed everything at the subway and took the most valuable loot and just left. 90+% of my loot is still just sitting there. So I would much prefer if the central lab spawned with at least some overmap entrance.

I also used auto move A LOT, but it is a buggy mess and when auto moving through a lab, the algorithm can on average only get you 30% of the way to where you actually want to auto move too. Even the subway is difficult for auto move, it seems like just holding down movement key is faster for some reason.

**Comment by scorpion451** [comment]
Legitimately not the biggest central lab I've explored. I love the big ones like this, they're a blast.

Don't get me wrong, I'd still love to see working elevators and ramps to move bulk loot and vehicles across floors, but really part of the challenge on labs is getting all that shiny stuff out of the lab.

Not normally the place for it, but some advice as it seems directly relevant to your issue with looting the place: One-tile vehicles (preferably the folding variety when you're looting multi-story areas) with some sort of large cargo space are the key to efficient looting of labs and similar sprawling multi-story complexes. Just like in real life, using a cart or sledge lets you move several times more weight and volume than you could trying to carry it yourself.

**Comment by vlad1492** [comment]
Finding the master backup power switch in the basement that fires up the elevators would be awesome.

**Comment by CoroNaut** [comment]
Gonna close as this issue isn't getting any traction.

Overall, seems like a decent idea to have a 400-600 tile lab with >5 finales for some people. As it is, it is just wayyy too big for me even with my late-game character and very fast typing speed to get through it ASAP (took probably 10 hr over 3-4 days and there was still probably 2+ hrs to go). Auto-move was barely helpful as it would only get me 30% of the way to my destination on average before running into any kind of issue with the pathfinding which made it almost as bad as just manually moving the entire way.
