### ISSUE TITLE
Profession-granted food can spawn rotten

### ISSUE THREAD

**Issue by LaVeyanFiend** [CleverRaven/Cataclysm-DDA#37115]
# Describe the bug

Some types of food you spawn with, such as hardtack from Historical Reenactor, starts out rotted.
Also tested with Survivalist Jr., their granola has lost over half its shelf life.

# Steps To Reproduce

1. Pick a profession with perishable food.
2. Notice some is rotten.
3. Debug increase cooking skill to see that the ones that *didn't* spoil have time taken from them.

# Expected behavior

Spawning with non-rotten food.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-11356-g2950b60 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

**Comment by Nedptr** [comment]
seems similar to #35906
