### ISSUE TITLE
Redundant messages while sleeping

### ISSUE THREAD

**Issue by ashGlaw** [CleverRaven/Cataclysm-DDA#37121]
# Describe the bug

When I sleep with a pillow I get 12 messages per full hour of sleep saying "You use your pillow for comfort." Six dozen plus notifications about using a pillow for comfort can't be the intended behavior

# Steps To Reproduce

Sleep on a bed with a pillow. Happens every time for me

# Expected behavior

Ideally also describe *why* you expect it to happen.
I expect one message about using a pillow would be helpful to let me know that my character's sleep will be more restful.

# Screenshots
![You use your pillow for comfort](https://user-images.githubusercontent.com/58862150/72557216-4d243d00-386e-11ea-850a-5e5a7d3519d6.png)

# Versions and configuration

- OS: Windows 10
    - OS Version: 10.0 1903
- Game Version: 0.D-11310-g1fb22bc [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    More City Locations [cityside],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    No Fungal Monsters [No_Fungi],
    Bionic Slots [cbm_slots],
    Classes and Scenarios Mod [more_classes_scenarios],
    Sleep Deprivation [sleepdeprivation],
    Stats Through Kills [stats_through_kills],
    Magiclysm [magiclysm],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Roadheader and other mining vehicles [Heavy miners],
    SpeedyDex [speedydex],
    Amplified @'s Features [amplified_players_features],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

N/A

**Comment by Fris0uman** [comment]
Probably introduced by #34386 , shouldn't be too hard to fix.

**Comment by Fris0uman** [comment]
Actually I can't reproduce that behaviour, tried sleeping on a bench with one pillow, on a bed with one pillow and with 16 pillows and in a car with one pilllows and the message only appear once every time.

**Comment by esotericist** [comment]
I was able to reproduce this on a recent master.

in my case, it was sleeping on the floor (not a bench) of the basement of the evac shelter.

had an unrolled sleeping mat, and a pillow. Got quite a lot of messages about comfort.

**Comment by HunorP** [comment]
Reproduced it in a LMOE shelter. Slept in the rightmost corner where a bed is located using a blanket and a simple pillow.
