### ISSUE TITLE
Zombies not breaking windows/doors

### ISSUE THREAD

**Issue by UndeadMoose** [CleverRaven/Cataclysm-DDA#37139]
# Describe the bug

Zombies are not breaking windows/doors when they are giving chase.

# Steps To Reproduce

1. Alert zombies
2. Run into house
3. Close door and wait

# Expected behavior

Zombies should destroy doors and bust windows to get to you.

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-11393-g704f045
 - Graphics version: Tiles
 - Mods loaded: 
  "no_npc_food",
  "aftershock",
  "Tolerate_This",
  "growable-pots",
  "makeshift",
  "More_Survival_Tools",
  "hydroponics",
  "mutant_npcs",
  "MMA",
  "deoxymod",
  "blazemod",
  "Heavy miners",
  "Tanks",
  "necromancy",
  "speedydex",
  "sleepdeprivation",
  "amplified_players_features"

# Additional context

**Comment by UndeadMoose** [comment]
Just checked and the regular zombies also keep grabbing me but not attacking?

**Comment by UndeadMoose** [comment]
Just checked and for some reason firefighter zombies just grab me but not attack me?

**Comment by l29ah** [comment]
Couldn't reproduce it, can you provide a save?

**Comment by UndeadMoose** [comment]
Here it is
[Chewalla.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4076068/Chewalla.zip)

**Comment by Drakasin** [comment]
Same. Worked in 10204. The world was created in 10204 but I Reset it after updating to 10210. New character created in 10210.
[Selden.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4076985/Selden.zip)
