### ISSUE TITLE
Building a driveable horse-powered wooden vehicle requires welding

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#37147]
# Describe the bug

It is needed to produce vehicle controls (`A steering wheel and accelerator and brake pedals.`), otherwise it's impossible to control a horse. Welder and metal parts are near-unobtainum in a wilderness setting.

# Expected behavior

Dunno, probably a hacky solution like we have with bicycles (i tried to use a `wooden handle` part, but that didn't give me control over my vehicle) will do.

# Versions and configuration

d18fc5dbe9

**Comment by Brian-Otten** [comment]
Just brainstorming, but would a set of "wooden" vehicle controls of some kind that lack the ability to start/stop engines work?

**Comment by sztosz** [comment]
Maybe rather leather vehicle controls like reins?

**Comment by ZhilkinSerg** [comment]
Related: #36373

**Comment by davidpwbrown** [comment]
I like the reins idea.
