### ISSUE TITLE
Tried to set x value to a VOID option

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [CleverRaven/Cataclysm-DDA#37151]
DEBUG    : tried to set an int value to a VOID option

     FUNCTION : void options_manager::cOpt::setValue(int)
     FILE     : src/options.cpp
     LINE     : 824

     DEBUG    : tried to set a float value to a VOID option

     FUNCTION : void options_manager::cOpt::setValue(float)
     FILE     : src/options.cpp
    LINE     : 811

Starting a game, this is what I get. If I ignore it, then my char has 0 stamina. No mods, just cdda, latest build 10210

**Comment by Unrepentant-Atheist** [comment]
Probably related to https://github.com/CleverRaven/Cataclysm-DDA/issues/37138

**Comment by davidpwbrown** [comment]
Yup same thing.

**Comment by davidpwbrown** [comment]
Closing in favour of #37138
