### ISSUE TITLE
Corpses have no organs or skin

### ISSUE THREAD

**Issue by drunkfever** [CleverRaven/Cataclysm-DDA#37153]
Game version: 0.D-11427-g9915387 (tiles)

Operating system: windows

Tiles or curses: tiles

Mods active: DDA, disable npc needs

### Expected behavior
Corpses to have organs and skin

### Actual behavior

![](https://i.imgur.com/TIVadHX.png)

### Steps to reproduce the behavior
Try and butcher anything

This is the first time Ive submitted a bug , sorry if anything is wrong!!

**Comment by davidpwbrown** [comment]
What corpse was it? what type of creature?

**Comment by snipercup** [comment]
It has to have a skin, see #34221

**Comment by drunkfever** [comment]
> What corpse was it? what type of creature?

That screenshot came from when I tried to butcher a regular zombie, but ive gotten that same thing when try to butcher human corpses, animals, other kinds of zombies, ect.

**Comment by davidpwbrown** [comment]
zombies dont have skin or organs, humans dont have skin, but they should have organs iirc

Can you confirm this bug by spawning a ... say.. bear in a testworld, kill it, and try and skin it. If this is the case with animals that are meant to have skin, then its a real bug.

**Comment by scorpion451** [comment]
Being precise it should probably say "usable skin/organs" but that's wordier than required

**Comment by drunkfever** [comment]
Ah i feel stupid now. Bear had organs and skin. I thought I had harvested organs and skin from zombies and humans before my bad!! Sorry about that.

Also turns out the animals I couldn't skin where mod animals

**Comment by davidpwbrown** [comment]
Cool, thanks for confirming, will close.
