### ISSUE TITLE
Can learn old cannibal recipes from SD Card

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#37162]
# Describe the bug

Used SD Card with E-Ink Reader.  Learned Human Stomach and Large Human Stomach recipes. 

# Steps To Reproduce

Too many recipes to reliably reproduce.

# Expected behavior

Obsoleted recipes to not be learnable via SD Card.

# Screenshots

![Stomach](https://user-images.githubusercontent.com/54345792/72653781-8cc85300-395a-11ea-879e-3ebb37ce2430.PNG)![Stomach](https://user-images.githubusercontent.com/54345792/72653781-8cc85300-395a-11ea-879e-3ebb37ce2430.PNG)

# Versions and configuration

 - OS: WIn 7
 - Game Version: O.D-11170-g64b5e04
 - Mods loaded: All basic distro mods but generic guns, modular turrets, and salvaged robots.

# Additional context

**Comment by ZhilkinSerg** [comment]
This looks like on old version where these recipes weren't obsoleted yet.

**Comment by Maleclypse** [comment]
Sorry I put in the build number, 10162 which I think u is s within last seven days rather than the start screen build. Would start screen number be more useful.

**Comment by ZhilkinSerg** [comment]
It is described in issue template:

```
# Versions and configuration

<!-- Please complete the following information; you can now go to:
    - "Main menu (ESC) > Debug Menu > Info > Generate game report" to generate this report.
    - Please update your OS version with a more precise version. -->

 - OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
 - Game Version: [from the main menu, e.g. 0.C-29938-g90f5268437]
 - Graphics version: [Tiles or Terminal]
 - Mods loaded: [e.g.dda, boats, hacktheplanet, StatsThroughSkills]
```
