### ISSUE TITLE
Apostrophes in soundpack display names causes syntax error in options.cpp

### ISSUE THREAD

**Issue by CSHague** [CleverRaven/Cataclysm-DDA#37161]
# Describe the bug

Apostrophe in soundpack display title in soundpack.txt causes a syntax error when loading options files:

18:27:50.344 ERROR : src/options.cpp:811 [void options_manager::cOpt::setValue(float)] tried to set a float value to a VOID option
18:27:50.707 ERROR : src/options.cpp:811 [void options_manager::cOpt::setValue(float)] tried to set a float value to a VOID option

# Steps To Reproduce
Load latest experimental. Download @'s soundpack and select to use. Restart game and attempt to load a game. You will get error spam similar to above. Apostrophe in the display title interferes with the new options.json style.

# Expected behavior

Game world loads normally without errors.

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-11430-g66807fe [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Aftershock [aftershock],
    Bens GF recipes [Tolerate_This],
    Garden Pots [growable-pots],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Makeshift Items Mod [makeshift],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks]
]

# Additional context

Changing the @'s to @s in the soundpack.json fixed the issue. Posted this in the [@'s soundpack thread](https://discourse.cataclysmdda.org/t/soundpack-s-soundpack-vehicle-sounds-licensed-music-and-more/20131/22)

**Comment by ZhilkinSerg** [comment]
Please try reproducing the issue on build 10213 or above.

**Comment by CSHague** [comment]
Yeah, it seems it was a false positive. Or rather I thought I had resolved an issue I was having but it cropped up again later. Updating to 10213+ resolved it. I'll have to revert to repo version of @'s to be certain. Will update.

**Comment by CSHague** [comment]
Okay, it seems I was wrong.  @'s with the apostrophe works just fine after updating. It appears I thought after swapping around the options and how it stopped the VOID error I was having that I had fixed the issue and was eager to report. Sorry for wasting your time with this.
