### ISSUE TITLE
Picking poppy flowers damages bandages

### ISSUE THREAD

**Issue by RarkGrames** [CleverRaven/Cataclysm-DDA#37174]
# Describe the bug
Picking poppy flowers damages the bandages already applied on wounds.

# Steps To Reproduce

1. Have bandages on.
2. Pick a poppy flower.
3. Have a chance to damage the bandages.

# Expected behavior

The fatigue effect not damaging the bandages.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.D-11356-g2950b60 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

[Test World.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4080358/Test.World.zip)

**Comment by Fris0uman** [comment]
This seem to work as intended, the bad effect of poppy damages your legs with their roots wich damage your bandages if you have some on your legs.
See line 1658 in iexamine.cpp

**Comment by RarkGrames** [comment]
Ok, looks like I got it wrong. I thought that the sleep effect damages the bandages, rather than the roots. Closing the issue.
