### ISSUE TITLE
Reading a book makes it yours

### ISSUE THREAD

**Issue by Alapaga** [CleverRaven/Cataclysm-DDA#37181]
# Describe the bug

When you see a book that's belonging to a faction other than the player's, and thus would have the ! about stealing it, reading the book makes it your book. 

# Steps To Reproduce

1. Go to a refugee center and find a book there that you can access
2. Try to read it
3. Congratulations, the book is yours now.

# Expected behavior

Well, since it's someone else's book, I would expect the person owning it to ask the player character to give it back to them, or at least have the option to give it back peacefully to whomever it belongs to once you're done reading it. Also, since some of the refugee center quests revolve around fetching a religious book, it would be nice to have some quests about trading skillbooks.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.D-11440-g82a2eb2 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Generic Guns [generic_guns],
    Alternative Map Key [alt_map_key],
    Cars to Wrecks [cars_to_wrecks],
    Disable Religious Texts [no_religious_Texts],
    No Explosive Zombies [No_Explosive_Zombies],
    Classes and Scenarios Mod [more_classes_scenarios],
    Safe Autodoc [safeautodoc],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Alapaga** [comment]
There's also other things that seem to tigger this issue that are similar. For example the reloading of a crossbow from a dead survivor's faction laying on the ground makes it yours.

**Comment by Amoebka** [comment]
| give it back peacefully to whomever it belongs to once you're done reading it

That's not how it works in real life.

**Comment by TimPollard** [comment]
> > give it back peacefully to whomever it belongs to once you're done reading it
> 
> That's not how it works in real life.

It does if you're at a library. ;-)

Of course how it should work with Cataclysm factions is a bit of a question. For example if a survivor wondered into one of the public areas of the Refugee Camp, picked up a book, spent half an hour flicking through it, and then put it back down before leaving it's hard for me to be sure if it would be more reasonable for the merchants to object or just to tolerate it.

**Comment by kevingranade** [comment]
Critical piece of information, are you doing this where someone from the owning faction can see you?

**Comment by Alapaga** [comment]
No, it happened usually after someone from said faction died. The only thing that I am reporting here is that this seems to override the thief mode settings. My character has no intent of stealing anything that doesn't belong to them, and the items are marked with a red ! when they are just lying there on the ground. The reloading or reading or generally iteracting with the item through the 'r' or 'R' menu seems to override any faction settings and make the said items belong to the player's Faction

**Comment by davidpwbrown** [comment]
I really don't understand the inventory_ui stuff, but if someone else does, all they'd need to do is insert a check somewhere for ```if( !item.is_owned_by( Character, true ) ){```

And if it isnt available to take, then insert a red "!" before its name in the inventory UI list, and a prompt to confirm reading it.  The solution would be general within inventory_ui for all things that gather nearby map and vehicle items - reloading , dissassembling, reading etc

**Comment by jkraybill** [comment]
To clarify this issue a bit more based on my testing, reading or reloading item does have the same effects as stealing it -- i.e. the ownership changing is not a bug per se because that happens when you pick up the item. The bug is that the user doesn't get prompted for stealing like they do when attempting to pick up the item.

**Comment by jkraybill** [comment]
If anyone looks at this before I commit a full fix, I did a (very draft) pass at addressing this here: https://github.com/jkraybill/Cataclysm-DDA/commit/6e700c1d79d3a6c1b09d729d60944f4af114bfe3

That commit fixes this issue for reading and wearing, but those are not the only places this issue exists.

There are also issues with the memory of THIEF_MODE not being properly observed in a few situations.

I found quite a number of closely related issues and this needs a deeper cut to properly fix it. I'm going to ice this for now and come back to it later.

**Comment by sparr** [comment]
Could probably have one consolidated fix with https://github.com/CleverRaven/Cataclysm-DDA/issues/61296 and https://github.com/CleverRaven/Cataclysm-DDA/issues/61294. Unlike those other cases, in this one you'll be interrupted if an NPC is watching.

(copied from dupe)
