### ISSUE TITLE
Restaurant Guides show Desolate Barns on the map for some reason

### ISSUE THREAD

**Issue by kleric42** [CleverRaven/Cataclysm-DDA#37194]
# Describe the bug

After reading an area's Restaurant Guide, it showed everything expected, except there were additionally a bunch of Desolate Barns now on my maps. Seemed wrong.

# Steps To Reproduce

1. Use Restaurant Guide
2. Notice all the Desolate Barns

# Expected behavior

Doesn't seem like Desolate Barns would be in a restaurant guide.

# Screenshots

![Desolate Barns](https://user-images.githubusercontent.com/19361975/72671562-aaa0c100-3a09-11ea-9100-67d1c766b0e8.png)

# Versions and configuration

 - OS: Windows 10
 - Game Version: Build 10215
 - Graphics version: Tiles

**Comment by ZhilkinSerg** [comment]
Probably because of bar in json definition of the guide and incorrect terrain match enum in the code.
