### ISSUE TITLE
Significant main menu filckering on curses

### ISSUE THREAD

**Issue by ifreund** [CleverRaven/Cataclysm-DDA#37191]
# Describe the bug

Top layer elements on the main menu flicker in and out with the background on curses builds.

# Steps To Reproduce

1. Run the game from your terminal emulator
2. Open the credits page of the main menu
3. Observe the flickering

# Expected behavior

There should be no flickering

# Screenshots

https://streamable.com/9qm7m

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.D-11440-g82a2eb2ab5 [64-bit]
- Graphics Version: Curses
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by ifreund** [comment]
Ok, I've done some more investigating and out of the terminal emulators I've tested this flicker is only apparent on [Alacritty](https://github.com/alacritty/alacritty).  This seems to be because Alacritty is *really* fast and is rendering frames that other terminal emulators are dropping.  Slowing down alacritty by running in verbose mode outputting to a file with `alacritty -vvv > out.log` and maximizing the window reduces the observed flickering substantially. 

I would still consider this a bug with cataclysm though, as we should not be redrawing these menus if the state is not changing. 

The only popup on the main menu that does not flicker is the help menu, so we should be able to look at how that is drawn to the screen and apply that to the rest of the main menu popups.

**Comment by ifreund** [comment]
Looks like this issue is rooted in the fact that we are currently attempting to redraw the main menu every 125 milliseconds *no matter what*
https://github.com/CleverRaven/Cataclysm-DDA/blob/82a2eb2ab5d21ac38c0391d557c07ee86a9a7bd2/src/main_menu.cpp#L243-L252
The reason we are currently doing this is because that is how we make sure that the screen is redrawn on resizing the terminal.  This, i should think, obviously not the right way to solve that problem and we probably should be either polling for terminal size change directly or using some type of event handling.

**Comment by 1n17** [comment]
This also manifests on *nix native tty's and wincurses port.

**Comment by 8street** [comment]
I somehow came across such a problem. Try changing `init_windows();` to `game_ui::init_ui();` or `reinitialize_framebuffer();`. Perhaps it will help. I can try it myself much later.

**Comment by ifreund** [comment]
@8street If you want a quick fix switching the `125` to something like `1000` will do the job.  Only downside is that there will then be a delay of up to 1 second when resizing the window before the UI adjusts to the new size.

Maybe that change would be sufficient to declassify this as a release blocker though? A proper fix is a good bit more in depth.

**Comment by 8street** [comment]
> Maybe that change would be sufficient to declassify this as a release blocker though?

Can you build the game with your changes? And what will happen if the user performs actions at intervals of less than 1 second?

**Comment by ifreund** [comment]
Here's the patch.  It builds just fine so feel free to compile and test it yourself
```patch
From b188e9950809a197257c416aec9293b81725cb5a Mon Sep 17 00:00:00 2001
From: Isaac Freund <isaac.a.freund@gmail.com>
Date: Mon, 20 Jan 2020 12:34:03 +0100
Subject: [PATCH] Bump main menu input timeout to 1 second

---
 src/main_menu.cpp | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/src/main_menu.cpp b/src/main_menu.cpp
index 15d4a85372..21ebf6bbdc 100644
--- a/src/main_menu.cpp
+++ b/src/main_menu.cpp
@@ -242,7 +242,7 @@ std::vector<std::string> main_menu::load_file( const std::string &path,
 
 std::string main_menu::handle_input_timeout( input_context &ctxt )
 {
-    std::string action = ctxt.handle_input( 125 );
+    std::string action = ctxt.handle_input( 1000 );
 
     if( action == "TIMEOUT" ) {
         init_windows();
-- 
2.25.0
```
This is only changing the input *timeout*. It doesn't affect responsiveness to input at all, only how long the game waits for input each loop before deciding to move on.  If anything, this patch would marginally increase input responsiveness.

If we had a proper solution to handling resizing as outlined above the timeout could be made infinitely large without issue.

**Comment by Godridge** [comment]
some flickering in alacritty on main menu (0.E), background logo text flashing over stuff like developer credits for a frame

**Comment by ifreund** [comment]
Not too surprised, the patch above was just a hack to make things work slightly better for 0.E. As mentioned, a proper solution would be a good deal more invasive.

**Comment by Leland** [comment]
Someone wanna retest this? That refresh rate was removed entirely in https://github.com/CleverRaven/Cataclysm-DDA/commit/ae68d3feefbb445ec15143f91317260d139496bc in favor of Qrox's ui_adaptor

**Comment by anothersimulacrum** [comment]
Cannot reproduce anymore in TTY, xterm, or alacritty - I think it's been fixed.

**Comment by Siinamon** [comment]
`0.E-2` is doing this for me with `alacritty`: https://boop.icu/QM.webm

**Comment by anothersimulacrum** [comment]
Would you mind testing and seeing if that persists on an experimental build? If not, ae68d3f handled it, otherwise, we may need to be looking at it.
