### ISSUE TITLE
Pit Digging option for NPCs

### ISSUE THREAD

**Issue by CSHague** [CleverRaven/Cataclysm-DDA#37192]
**Is your feature request related to a problem? Please describe.**  
While it is possible to make glass pits from full sized pits using zones, there is no construction available for digging a pit alone now, meaning players must directly dig a pit themselves with potential NPC assistance but cannot order the NPC to dig a pit by themselves. Digging a full-sized pit takes a lot of time and would be a task better suited to NPCs while the player does other useful things. While a construction task for pits used to exist in the game, it was removed because it didn't have matching results compared to a digging tool's iuse function

**Describe the solution you'd like**  
Adding a Shallow and Deep pit digging zone to the NPC zone menu that will allow NPCs to use digging tools to dig deep and shallow pits

**Describe alternatives you've considered**  
Simply adding back the construction task via a mod and getting it to match results with digging proper somehow.

**Comment by blomps** [comment]
You can currently make them dig pits by marking out glass/spike pit zones and making sure they don't have access to glass/spikes (it doesn't return any soil/rock/clay).

**Comment by davidpwbrown** [comment]
Yeah the pit construction still exists, but its hidden by default. It gets used when its a prerequisite for another construction.

A pit digging zone would be the solution, where they use the proper shovel iuse function, with byproducts etc, however there hasnt been much need for it so far, im reluctant to add more zones until the zone UI can have categories at least.

**Comment by CSHague** [comment]
Okay, I think I found where I'm having trouble. I already dug shallow pits and the glass pit construction zone blueprint and NPCs won't start digging a deep pit if a shallow pit already exists anywhere in the zone. I just tested it by swapping zone position to an empty tile 1x1 from a 1x2 with a shallow pit on one side.

**Comment by Nhatorama** [comment]
Does this make sense?

// Referencing the numbers in digging_moves_and_byproducts dig_pit_moves_and_byproducts located // in iuse.cpp
    // Shallow pit: 425 kg / 25 kg/min = 17 minutes
    // Deep pit: 3400 kg / 25 kg/min = 136 minutes
    // Adjusted deep pit: ( 3400 kg - 425 kg ) / 25 kg/min = 119 minutes
    // Referencing the numbers in digging_soil_loam_50L located in json/itemgroups/misc.json
    // 425 / 50 = 8.5
    // 8.5 * the byproduct numbers of digging_soil_loam_50L
    // 3400 - 425 = 2975 
    // 2975 / 50 = 59.5
    // 59.5 * the byproduct numbers of digging_soil_loam_50L
    {
    "type": "construction",
    "id": "constr_pit_shallow",
    "skill": "survival",
    "description": "Dig a Shallow Pit with a Wooden Shovel",
    "category": "DIG",
    "difficulty": 1,
    // Should a "Shallow Pit with a Digging Stick" be added or should the time and qualities be recalculated for the wooden shovel?
    "time": "30m",
    "qualities": [ { "id": "DIG", "level": 1 } ],
    "byproducts": [
      { "item": "material_soil", "count": [ 8, 102 ] },
      { "item": "material_sand", "charges": [ 1, 85 ], "prob": 5 },
      { "item": "clay_lump", "count": [ 1, 34 ], "prob": 5 },
      { "item": "rock", "count": [ 1, 34 ], "prob": 10 },
      { "item": "rock_flaking", "count": [ 1, 34 ], "prob": 2 },
      { "item": "rock_large", "prob": 10 },
      { "item": "pebble", "count": [ 1, 34 ], "prob": 15 }
    ],
    "pre_flags": [ "DIGGABLE", "FLAT" ],
    "post_terrain": "t_pit_shallow"
  },
  {
    "type": "construction",
    "id": "constr_pit",
    "skill": "survival",
    "description": "Dig a Deep Pit with a Wooden Shovel",
    "category": "DIG",
    "difficulty": 1,
    "time": "150m",
    "qualities": [ { "id": "DIG", "level": 2 } ],
    "byproducts": [
      { "item": "material_soil", "count": [ 8, 714 ] },
      { "item": "material_sand", "charges": [ 1, 595 ], "prob": 5 },
      { "item": "clay_lump", "count": [ 1, 238 ], "prob": 5 },
      { "item": "rock", "count": [ 1, 238 ], "prob": 10 },
      { "item": "rock_flaking", "count": [ 1, 238 ], "prob": 2 },
      { "item": "rock_large", "prob": 10 },
      { "item": "pebble", "count": [ 1, 238 ], "prob": 15 }
    ],
    "pre_flags": [ "DIGGABLE", "FLAT" ],
    "post_terrain": "t_pit"
  },
  {
    "type": "construction",
    "id": "constr_pit_shallow",
    "skill": "survival",
    "description": "Dig a Shallow Pit with a Quality Shovel",
    "category": "DIG",
    "difficulty": 1,
    "time": "17m",
    "qualities": [ { "id": "DIG", "level": 3 } ],
    "byproducts": [
      { "item": "material_soil", "count": [ 8, 102 ] },
      { "item": "material_sand", "charges": [ 1, 85 ], "prob": 5 },
      { "item": "clay_lump", "count": [ 1, 34 ], "prob": 5 },
      { "item": "rock", "count": [ 1, 34 ], "prob": 10 },
      { "item": "rock_flaking", "count": [ 1, 34 ], "prob": 2 },
      { "item": "rock_large", "prob": 10 },
      { "item": "pebble", "count": [ 1, 34 ], "prob": 15 }
    ],
    "pre_flags": [ "DIGGABLE", "FLAT" ],
    "post_terrain": "t_pit_shallow"
  },
  {
    "type": "construction",
    "id": "constr_pit",
    "skill": "survival",
    "description": "Dig a Deep Pit with a Quality Shovel",
    "category": "DIG",
    "difficulty": 1,
    "time": "119m",
    "qualities": [ { "id": "DIG", "level": 3 } ],
    "byproducts": [
      { "item": "material_soil", "count": [ 8, 714 ] },
      { "item": "material_sand", "charges": [ 1, 595 ], "prob": 5 },
      { "item": "clay_lump", "count": [ 1, 238 ], "prob": 5 },
      { "item": "rock", "count": [ 1, 238 ], "prob": 10 },
      { "item": "rock_flaking", "count": [ 1, 238 ], "prob": 2 },
      { "item": "rock_large", "prob": 10 },
      { "item": "pebble", "count": [ 1, 238 ], "prob": 15 }
    ],
    "pre_flags": [ "DIGGABLE", "FLAT" ],
    "post_terrain": "t_pit"

**Comment by anothersimulacrum** [comment]
My preferred solution to this would be #42070

**Comment by Nhatorama** [comment]
Nice, I didn't see it when I was looking around.
