### ISSUE TITLE
NPCs can't pass through screen mesh door / climb over screen mesh wall

### ISSUE THREAD

**Issue by Drakasin** [CleverRaven/Cataclysm-DDA#37207]
# Describe the bug

NPCs, (seems like it doesn't matter if friendly or not from various starting), cannot pass through mesh door / climb over mesh wall

# Steps To Reproduce

1. Befriend an NPC
2. Find a house with screen mesh entrance
3. NPC will stand/pace outside, not following you through the open screen mesh door
-> Save file provided below

Alternatively, start in a burning building with a mesh screen, be lucky enough to see it get trapped at a mesh screen entrance, watch the neutral npc burn to death as it cannot get out even though there's a perfectly good mesh screen door right next to it.

# Expected behavior

NPC doesn't fear the mesh screen, it embraces the mesh screen, it wraps itself in its tender polyester and becomes one with the mesh screen.

# Screenshots

![Screenshot](https://user-images.githubusercontent.com/6567381/72677258-b8525700-3a9a-11ea-8411-551d282e7a7e.png)

# Versions and configuration
- OS: Windows 10 Pro 64bit 1903, build 18632
- Game Version: 0.D-11446-gfb9dabb [64-bit]
- Graphics Version: Tiles (UNDEAD_PEOPLE, jan 14)
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Mutant NPCs [mutant_npcs]
]

# Save file
[Cutler Ridge.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4082402/Cutler.Ridge.zip)

**Comment by Hatfish** [comment]
Well mesh screens are intended to keep bugs out, this one included apparently.
