### ISSUE TITLE
Too many items on a tile prevent from making use of the whole space

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [CleverRaven/Cataclysm-DDA#37209]
# Describe the bug

Having 5 pages of items on a tile prevents from making use of the whole L space.

# Steps To Reproduce
Have a tile, don't fill it to the MAX L, but have 5 pages of items on it. And then try to add more stuff to it. Won't be possible.

# Expected behavior
Make use of the whole tile L space.

# Versions and configuration
Build 10217, cdda, aftershock, cata++-

**Comment by ZhilkinSerg** [comment]
What is an `L space`?

**Comment by Qrox** [comment]
Perhaps you hit the 10000 items per tile limit?

**Comment by azraneth** [comment]
I believe what is meant with ```L space``` is the volume of the tile.

**Comment by kevingranade** [comment]
This is working as intended, we limit 5he number of items on the tile to prevent strange error modes.
