### ISSUE TITLE
Batch Unload

### ISSUE THREAD

**Issue by Lamandus** [CleverRaven/Cataclysm-DDA#37224]
**Is your feature request related to a problem? Please describe.**  
When having a high amount of stuff, like cookies in cardboard boxes, it is a clickfest to get them all out of it.

**Describe the solution you'd like**  
Like Multidrop: Multi unload of the whole stack batch, maybe even multiple stacks. Can be counted as drop (10+Unload -> 10 unloads)

**Describe alternatives you've considered**  
Keeping the clickfest

**Comment by ZhilkinSerg** [comment]
Duplicate of #24002

**Comment by CoroNaut** [comment]
I can definitely agree this is a pain with all the keypresses, I can see my thumbs up on that duplicate issue and give this one a thumbs up too. I am all for this idea.
