### ISSUE TITLE
Raw Wasteland Sausage Uncraftable

### ISSUE THREAD

**Issue by whitehorn799** [CleverRaven/Cataclysm-DDA#37223]
# Describe the bug
I have the charcoal smoker stocked with 180 charges. I used the craft menu to craft a raw wasteland sausage. I then attempted to craft the wasteland sausage (edible) using the charcoal smoker item, but I was not able to craft it.

# Steps To Reproduce

1. Use the craft menu (&) to craft a raw wasteland sausage.
2. Get a charcoal smoker loaded with 10 charges.
3. Use the craft menu to attempt to craft a wasteland sausage while near the charcoal smoker.
4. The wasteland sausage is not able to be crafted

# Expected behavior

When I have the raw wasteland sausage in my inventory and I am near a charcoal smoker with 10 charges, I expect to have the edible version of the wasteland sausage. I expect this because the crafting recipe for a wasteland sausage is 
 * a tool with cutting 1 or more
 * a tool with food cooking 1 or more
 * a charcoal smoker (10 charges)

I have the required materials in my inventory or nearby.

# Screenshots

![wasteland](https://user-images.githubusercontent.com/58099194/72685002-9ef3ee00-3b20-11ea-8739-91e163e868a3.png)

# Versions and configuration

<!-- Please complete the following information; you can now go to:
    - "Main menu (ESC) > Debug Menu > Info > Generate game report" to generate this report.
 ^^^^^^^^ This doesn't work for me.

 - OS: Windows 10
 - Game Version: 0.D
 - Graphics version: Tiles
 - Mods loaded: disable npc needs, filthy clothing, simplifid nutrition, more surival tools, modular turrets, salvaged robots, medieval and historical content, makeshift items mod, packaging, growable pots, alternative map key, more locations, fuji's more buildings, boats, necromancy

# Additional context

**Comment by ZhilkinSerg** [comment]
Recipe for wasteland sausages does not include raw wasteland sausage.
