### ISSUE TITLE
Game stops loading when hitting "Mapgen weights"

### ISSUE THREAD

**Issue by JosephJomama** [CleverRaven/Cataclysm-DDA#37225]
# Describe the bug

The loading screen displays an error message once it gets down to "Mapgen weights" and quits back to the main menu.

# Steps To Reproduce

1. Get a fresh install of the latest version (as of right now, 10219).
2. Make a new world with no mods or options changed.
3. Select Custom Character under New Game.
4. Wait for it to get to "mapgen weights".
5. Get the error message and get sent back to the main menu.

# Expected behavior

The game is expected to go to the character creation screen. Instead, it goes back to the main menu with an error message.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-11469-gfd8c0cb
 - Graphics version: Tiles
 - Mods loaded: DDA, Disable NPC Needs

# Additional context

The error message displayed on the loading screen when this issue occurs says:

    DEBUG    : Error: line 173:18: no such item

         "place_items": [  ],
         "place_item": [
           { "item":
                    ^
                     "still", "x": [ 29, 29 ], "y": [ 33, 31 ], "amount": 1 },
           { "item": "fruit_wine", "x": [ 25, 25 ], "y": [ 33, 30 ], "repeat": [ 1, 4 ], "amount": [ 0, 3 ] }
         ],

    FUNCTION : bool main_menu::new_character_tab()
    FILE     : src/main_menu.cpp
    LINE     : 772

There is also an error that appears when quitting the game with the Quit button. This message says:

    The program has crashed.
    See the log file for a stack trace.
    CRASH LOG FILE: ./config/crash.log
    VERSION: 0.D-11469-gfd8c0cb
    TYPE: Signal
    MESSAGE: SIGSEGV: Segmentation fault

The crash log is also attached.
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4083137/crash.log)

**Comment by Kilvoctu** [comment]
This is due to PR #37212 (tools json sorting). It removed the `still` tool, presumably to be re-added in a later part of that project.

**Comment by scorpion451** [comment]
Can confirm an additional case, getting identical error message about the still and fruit wine trying to load an existing character with new build.

**Comment by RarkGrames** [comment]
Sorry for the mess, I moved the still from the first PR to a later PR without realizing that it will be merged gradually and it will be gone until the later PR is merged.
