### ISSUE TITLE
Custom Zone filters impede sorting

### ISSUE THREAD

**Issue by MarceloLaser** [CleverRaven/Cataclysm-DDA#37238]
# Describe the bug

There seems to be an issues with custom filters. I have tried setting a small number of them to sort specific items, and no sorting occurs so long as the custom filters remain active. Removing all of them from the Zone Manager will remove the issue. I'm uncertain of what the cause may be, or even how to replicate the issue, so I am attaching a save that has the issue on it for debugging.

# Steps To Reproduce

1. Open attached save file.
2. Attempt to sort loot, or order NPC companion to sort loot.
2A. Nothing should happen.
3. Remove all Custom zones from the Zone Manager.
3A. Attempt to sort loot, or order NPC companion to sort loot.
3B. Should work perfectly.

# Expected behavior

Sorting should happen with, I assume, priority being given to zones that are further up in the manager. If that is an incorrect assumption, then at the least, some sorting should occur.

# Versions and configuration

19:35:15.080 INFO : Cataclysm DDA version 0.D-11469-gfd8c0cb
19:35:15.121 INFO : Number of render drivers on your system: 4
19:35:15.121 INFO : Render driver: 0/direct3d
19:35:15.121 INFO : Render driver: 1/direct3d11
19:35:15.121 INFO : Render driver: 2/opengl
19:35:15.121 INFO : Render driver: 3/software
19:35:15.123 INFO : Language is set to: 'en'
19:35:15.874 INFO : SDL version used during compile is 2.0.5
19:35:15.874 INFO : SDL version used during linking and in runtime is 2.0.5
19:35:16.182 INFO : Active renderer: 0/direct3d
19:35:16.595 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
19:35:17.067 WARNING : opendir [./mods/] failed with "No such file or directory".
19:35:21.251 WARNING : opendir [./save/Harwinton/mods] failed with "No such file or directory".
19:35:31.839 INFO : Loaded tileset: UNDEAD_PEOPLE

 - OS: Windows 10
 - Game Version: Experimental 10219
 - Mods loaded: DDA, Disable NPC Needs, Aftershock, C.R.I.T., Magiclysm, Vehicle Additions, Tanks and Other Vehicles. In that order.

[manual_backup.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4084346/manual_backup.zip)

**Comment by CoroNaut** [comment]
I assumed priority was given to the custom zones, but I like the idea of just making the zone manager the way to set priorities with the zones' location in the list.
