### ISSUE TITLE
Crafting a item too large to wield in one hand with one hand blocked destroys it

### ISSUE THREAD

**Issue by Grubleafeater** [CleverRaven/Cataclysm-DDA#37249]
# Describe the bug

If you craft a item with one hand blocked which is light enough during crafting to hold in one hand, but not light enough after, it is destroyed

# Steps To Reproduce

1.Equip a briefcase
2.Craft a electric forge(i put it on the ground and ran out of charges on my tool so had to pick it up;possibly related)

# Expected behavior
Item should be put into inventory or dropped.

**Comment by Grubleafeater** [comment]
Whoops. I'm on 11269. Not 100% current, apparently.

**Comment by davidpwbrown** [comment]
Yeah please update to latest experimental and try again.
Feel free to reopen if its still happening on latest experimental.

https://github.com/CleverRaven/Cataclysm-DDA/pull/36230  this was the fix for this issue I believe.
