### ISSUE TITLE
Too high Power consumption of gasoline and diesel engines.

### ISSUE THREAD

**Issue by NEONZARIN** [CleverRaven/Cataclysm-DDA#37248]
**Is your feature request related to a problem? Please describe.**  
At this time, there is too much fuel consumption of car engines. It is simply absurd. And the heavier the car, the more urgent the problem.

**Describe the solution you'd like**  
I think we should rebalance the energy consumption of the engines. Bring these values ​​to the right decision. That would be a car ride as in the old versions. When the fuel in the 60L gas tank was enough for a very long period of time. I'm not sure, but in the discord they wrote to me that this is due to the transition of the waiting time to 1 turn = 1 second. That no one did rebalance under the new time per 1 turn

**Describe alternatives you've considered**  
N/A

**Additional context**  
These are the values
 **"energy_consumption"**
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/vehicleparts/combustion.json

**Comment by Taichi22** [comment]
Gah, calculating the actual physics for this is a pain.
I can do it, if there's any interest, because it's really not all that hard, (if we have any car engineers they'd probably do a better job), but it depends on whether the consensus is to balance for gameplay and just ignore the numbers, or if numbers are wanted first.

**Comment by Night-Pryanik** [comment]
> numbers are wanted first.

This.

**Comment by Ker-Nes** [comment]
If the energy consumption of vehicles are going to to be looked at, it might be good to check the fuel consumption/power curves for engines not operating at max capacity. My experience so far is that for a given speed, so long the engine is not absurdly increasing the weight of the vehicle (meaning either v12s in bikes or turbines in anything but the largest of vehicles), it's _more_ efficient to use the larger engine below max capacity than to use a smaller engine that will reach a similar speed with its max cruising speed. 

That is, with my 3 ton vehicle, going 80 km/h, I use less fuel with a v12 than with a v6, which is not really the behavior I'd expect from it.

**Comment by mlangsdorf** [comment]
So before I approve any requests to rewrite the vehicle fuel consumption system, people are going to need to demonstrate two things:
1.  That you actually know how the current vehicle fuel consumption system works, and
2.  That the current numbers are dramatically out of wack from the real world.

Last I checked, and it doesn't look like the numbers have changed too much, the stock CDDA car with an I4 range running at 60-70 mph consumed a full 60L tank of gasoline in 4-5 hours, which pretty much matches the performance of my real world car.

I'm not saying the system is perfect, and Ker-Nes complaint is a valid issue (but it's not easy to solve either).  But rebalancing based on nostalgia for an old version that may or may not have had any validity either is not an acceptable plan.

**Comment by I-am-Erk** [comment]
I'm going to close this without numbers suggesting there's an actual problem. Ker-Nes, you do seem to have something worth posting but I'd say it's a separate issue.

If you have some numbers to suggest how things should work, add them to the first post and reopen the issue.

**Comment by davidpwbrown** [comment]
> but in the discord they wrote to me that this is due to the transition of the waiting time to 1 turn = 1 second. That no one did rebalance under the new time per 1 turn

You should've kept on reading, shortly after I raised that as a potential throwaway reason for why your perceived numbers were way out of whack, and then me and a few of the other devs looked into the functions and discovered that it couldnt be possible that it was due to the change to 1 second turns.

We explained this to you in the Discord.

**Comment by mlangsdorf** [comment]
When I did the great vehicle physics model rewrite, the majority of vehicle fuel consumption was always based on the assumption that turns were 1 second long, even when they were 6 seconds long.  Moving to 1 second turns had marginal effects on vehicle fuel consumption, which is easily verifiable by reviewing the relevant changelogs.

just as a note: pavement tiles moved by a car in the vehicle efficiency tests:
last value before 1 second turns change: 363,000 tiles
value immediately after 1 second turns change: 530,700 tiles
current value: 481,900 tiles

yes, let's go back to how things were before the 1 second change, when cars had 75% of the range they have now!
