### ISSUE TITLE
Holsters allow duplication of guns

### ISSUE THREAD

**Issue by AlexMooney** [CleverRaven/Cataclysm-DDA#37251]
# Describe the bug

Holsters can be used to produce multiple copies of a gun, including their ammunition.

# Steps To Reproduce

1. Put a holster with a gun on the ground.
2. Have insufficient inventory volume available to pick it up to inventory.
3. Attempt to pick it up, presuming to wield the holster.
4. Get prompted "Do you want to draw from the holster?"
5. Choose yes and get the gun.
6. Holster still contains the gun.

# Expected behavior

Holster on ground is empty.

# Versions and configuration

 - OS: Ubuntu 18.04
 - Game Version: d4900feea156bf7554c91495bcd015f9e900b8b1
 - Graphics version: Tiles
 - Mods loaded: StatsThroughKills, Magiclysm, Disable NPC Needs

**Comment by Trioct** [comment]
Definitely related to #36742.
While I couldn't reproduce that issue when I first tried it, I could reproduce both issues with these instructions.
