### ISSUE TITLE
Add the option to toggle individual Reactors in vehicles.

### ISSUE THREAD

**Issue by DatMeg** [CleverRaven/Cataclysm-DDA#37253]
**Is your feature request related to a problem? Please describe.**  
As it currently stands, the vehicle controls UI has a singular button to turn on all Reactor(s) installed in the vehicle. Now, maybe most people don't have 3 Minireactors installed in their car, but what if someone has a modded Reactor (like the Vortex Reactor), and a Minireactor installed? They have no option to turn on one, or the other.

**Describe the solution you'd like**  
A simple menu change, to match that of the Engine Selection menu (y) could be useful, perhaps relegated to the Electronics Controls menu (E) so not to overly clog up the main vehicle menu.

**Describe alternatives you've considered**  
Alternatively, I'm just nitpicking and it's perfectly fine as it is.

**Comment by l29ah** [comment]
Toggleable aisle lights would be also good.
Probably would be easier to implement by adding actions to `e`xamining corresponding tiles.
