### ISSUE TITLE
Reloading 2.5L Canteen that is marked as "clothing"

### ISSUE THREAD

**Issue by whitehorn799** [CleverRaven/Cataclysm-DDA#37268]
I had an empty 2.5L canteen in my inventory, and it's category is "Clothing". I pressed r to reload the canteen. I do not get the opportunity to select any liquid, but I am standing next to a barrel of unfrozen clean water. 

I get the following bug:

 DEBUG    : Tried to reload liquid container with non-liquid.
 
 FUNCTION : bool item::reload(player&, item_location, long int)
 FILE     : src/item.cpp
 LINE     : 5758

# Steps To Reproduce

1. Get a 2.5L canteen that has nothing in it
2. Be near to unfrozen clean water source from barrel
3. Press r
4. Produce bug

# Expected behavior

I expect to be given the option of what liquid to select to fill the canteen with. If there is only one possible liquid to fill the canteen, I expect the canteen to be filled with that liquid.

# Screenshots

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D
 - Graphics version: Tiles
 - Mods loaded: disable npc needs, filthy clothing, simplifid nutrition, more surival tools, modular turrets, salvaged robots, medieval and historical content, makeshift items mod, packaging, growable pots, alternative map key, more locations, fuji's more buildings, boats, necromancy

# Additional context

**Comment by Trioct** [comment]
I couldn't reproduce on the latest experimental, and ever since #35419, the 2.5L canteen shouldn't be clothing anymore. If you're on 0.D stable, you could update to the latest experimental and see if you can still reproduce the bug.

**Comment by whitehorn799** [comment]
I can confirm this is fixed in experimental!
