### ISSUE TITLE
Random NPCs only spawn in the central overmap

### ISSUE THREAD

**Issue by RydellV** [CleverRaven/Cataclysm-DDA#37284]
# Describe the bug
Random NPCs only spawn within the central overmap. If the player travels away from that overmap then random NPCs will not be encountered.

# Steps To Reproduce

1) Create a fresh world with random NPCs enabled, set random NPC spawn rate to 100x.
2) Create a character and wait 6 hours in game.
3) Check your debug.log to see random NPCs spawning in the starting overmap.
4) Teleport several overmaps away and wait 6 hours in game.
5) Check debug.log again to see random NPCs still spawning only in the starting overmap.

# Expected behavior

Random NPCs spawning all over the world.

# Versions and configuration
- OS: Windows 10 Pro
    - OS Version: 10.0 1809
- Game Version: 0.D-11532-g0696252 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
Possibly related to #35146

**Comment by Inglonias** [comment]
On a whim, I tested this and sure enough, this seems to be the case.
