### ISSUE TITLE
Can know what happens with Hub Security w/o observing them

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#37280]
# Describe the bug

When walking in and around, and seeing no one, i see messages like `Lachlan, Hub Security drops the Marlin 39A.` and `the intercom puts away the crossbow`.

# Expected behavior

No telepathy.
No armed intercoms?

# Screenshots

![](https://pstbin.ru/f/16134/)

# Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.D-11430-g66807feaf6-dirty [64-bit]
- Graphics Version: Curses
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

# Additional context

[2020.01.20.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4093233/2020.01.20.zip)

**Comment by l29ah** [comment]
Saved right before occurring (come to the hub and observe the messages): 
[2020.02.06.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4173873/2020.02.06.zip)

**Comment by wapcaplet** [comment]
Cannot reproduce in 0.F-5143-g 427a349533 with your attached save. Walking around, waiting an hour or more inside the hub, there are no messages about NPCs doing anything. The relevant code appears to be wrapped in `avatar_sees` checks since late in 2020.

**Comment by hexagonrecursion** [comment]
* I can reproduce this in 0.D-11430-g66807feaf6

    - OS: Linux
        - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
    - Game Version: 0.D-11430-g66807fe [64-bit]
    - Graphics Version: Tiles
    - Mods loaded: [
        Dark Days Ahead [dda],
        Disable NPC Needs [no_npc_food],
        Alternative Map Key [alt_map_key],
        No Rail Stations [No_Rail_Stations]
    ]

* but I can not reproduce this in e49949d

    - OS: Linux
        - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
    - Game Version: e49949d [64-bit]
    - Graphics Version: Tiles
    - Game Language: English [en]
    - Mods loaded: [
        Dark Days Ahead [dda],
        Disable NPC Needs [no_npc_food],
        Alternative Map Key [alt_map_key],
        No Rail Stations [No_Rail_Stations]
    ]

* In e49949d the messages *do* show up if I enable debug clairvoyance.

@wapcaplet. This is as close as an experiment can get to confirming that this bug has been fixed. Please close this.
