### ISSUE TITLE
Hub01 Return Field Data mission is offered twice

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#37298]
# Describe the bug

After completing the mission, it is presented again as an exact copy, along with the next mission.

# Steps To Reproduce

1. Load the game.
2. Come to Hub01.
3. `e`xamine the intercom.
4. Talk about missions.

# Expected behavior

Non-duplicating missions/text suggesting why the duplicate is not a bug (a second robot test?).

# Screenshots

![](https://pstbin.ru/f/93376/)

# Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.D-11430-g66807feaf6-dirty [64-bit]
- Graphics Version: Curses
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

# Additional context

[2020.01.20.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4095622/2020.01.20.zip)

**Comment by Qrox** [comment]
Sounds like #37059 didn't properly fix #37056.

**Comment by John-Candlebury** [comment]
This was fixed in #37222.

**Comment by l29ah** [comment]
Nah, i observe the same behaviour on 0.D-11543-g3e11834b57

**Comment by John-Candlebury** [comment]
Would you mind stating which conversation options you followed to reach this bug?

It seems I cant duplicate it on a fresh world.

**Comment by l29ah** [comment]
They're presented on the screnshot.

**Comment by int-ua** [comment]
Screenshots are not loading. Maybe it's a temporary issue.

**Comment by OliveChukar** [comment]
Tested in ver 0.E-9111-gd1e702b-dirty. Was not able to duplicate. Need someone that has seen the problem to write exact instructions including what parts of the quest chain were done and the conversation options that lead to the problem.

**Comment by int-ua** [comment]
@l29ah please comment if it's still relevant and I'll reopen. But you'll have to revise steps to reproduce.
