### ISSUE TITLE
[10232] Unable to disassemble -Inactive- Manhacks, C4, Teargas, firebomb, grenade, flashbang-

### ISSUE THREAD

**Issue by Helldrone** [CleverRaven/Cataclysm-DDA#37291]
![image](https://user-images.githubusercontent.com/49344129/72853255-296b5780-3cb1-11ea-85db-e169fb99aca1.png)

Hello! i'd like to simply report that you are unable to disassemble the current inactive manhack variations.

I've made sure i had all the tools and skills required to do so.
Solder, Solder iron charged, Electronics 6, Mechanic 8, Computer 6, Integrated toolset, workbench, screwdriver set.

![image](https://user-images.githubusercontent.com/49344129/72853329-5b7cb980-3cb1-11ea-85b8-1719130bad72.png)

![image](https://user-images.githubusercontent.com/49344129/72853591-2755c880-3cb2-11ea-8f2a-9124e1c2bd2f.png)

![image](https://user-images.githubusercontent.com/49344129/72853417-a1398200-3cb1-11ea-9efd-e093eb34ffb0.png)

Disassembly is greyed out on all the others aswell.

Here is my modlist if that helps at all.

![image](https://user-images.githubusercontent.com/49344129/72853535-f4abd000-3cb1-11ea-8337-352f70e9d65a.png)

**Comment by CSHague** [comment]
That's a part of Salvaged Robots and apparently something I missed when I had updated it. I'll have to do something about that.
