### ISSUE TITLE
Magiclysm - Spellbooks and scrolls should respect charges

### ISSUE THREAD

**Issue by foulman** [CleverRaven/Cataclysm-DDA#37306]
**Is your feature request related to a problem? Please describe.**  
Spellbooks and scrolls are unlimited use items, even after trying to make them comestibles or set charges: 1, they will always work.

It would be useful if learn_spell action would at least respect the charges option (if no other) if it is set, that way limited use items could be created, such as perhaps for more powerful spells that the players might need to actually practice a lot rather than just sit around and study.
This would also allow situations like only allowing the player to learn one or two spells out of a large /powerful book before it vanishes.

**Describe the solution you'd like**  
Have the "use_action": { "type": "learn_spell", "spells": [  ] } respect and decrement the number of charges set on an item. The book/scroll/item disappearing like water purification, or being marked as "used" like maps, are both acceptable. Maybe force a drop or transform (whichever is easier) into another specified object if that is simple enough to accomplish.

**Describe alternatives you've considered**  
None could be thought of, using cast_spell instead was considered, but spells can't be learned from spells, and granting a trait to give a spell seems like awkward and bloated overkill.

**Comment by FuelType-Memes** [comment]
While I understand the idea behind limited-use scrolls and disappearing books I think it's more of a [Coconut Effect](https://tvtropes.org/pmwiki/pmwiki.php/Main/TheCoconutEffect)

Why would a scroll just suddenly vanish after you read it? How does it know you've read it? What If I copy it, for example, memorize and copy on another piece of paper, take a picture of the book, use my Bionic memory or whatever. _Magic?_

**Comment by foulman** [comment]
In part to somewhat slow the progression of Magiclysm characters, I've seen quite a few people talking about just finding a nice cozy place and studying a couple of scrolls they found for days until they're badasses. It's a little too easy to boost up from level 0 to level 4 or 5 in just a couple of days. That's a bit too rapid of a progression.

I don't think they should just... vanish... I'd prefer they didn't, but it's not exactly out of character for that kind of object. A lot of the magic in magiclysm is based on D&D concepts, some on Angband, but at least in D&D, if you take a scroll you found... you can either use it to cast a spell.. or learn it. Either is a destructive process.
If this were implemented, then all scrolls could be either one use of the spell OR teach you the spell, that would make them more useful if anything, especially for oppositional class magic that you can't use, that would otherwise just pile up. 
However, I was also thinking about more powerful sources of learning spells, more powerful, higher difficulty, spells. 
Find a big book with 20 spells in it... pick 3. poof. done. 
Then you have to practice it. use it.
And yes, _Magic_!

**Comment by KorGgenT** [comment]
how bout instead we give a max level to the scroll/book? could allow for a lot more books.

**Comment by foulman** [comment]
While I do still like the idea of charges being respected for that action (all actions really), that would be a big improvement. We differ on the fundamental point of me preferring a more 'natural' learning process and your preference to have spells via primarily book learning. 
I would be curious to see Vancian magic worked up, what @Kenshkrix was working on, even if it was a little hacky.

**Comment by KorGgenT** [comment]
i've posted an alternative issue, as i have no interest in pursuing this particular implementation.
