### ISSUE TITLE
Application hangs during "Finalizing" prior to character creation - Unknown cause

### ISSUE THREAD

**Issue by HaplessOperator** [CleverRaven/Cataclysm-DDA#37301]
# Describe the bug

The application hangs prior to character generation during the "Finalizing" process, and the application will hang on the red Z logo if restarted without performing a system restart.

# Steps To Reproduce

1. Create [World]
2. Select [New Game]
3. Select [Custom Character]
4. Application hangs during "Finalizing" on Crafting Recipes

# Expected behavior

Character generation takes place following "Finalizing."

# Screenshots

Unable to supply a screenshot.

# Versions and configuration

 - OS: ChromeOS Version 79.0.3945.86 (Official Build) (64-bit), running on a Chromebook XE500C13
 - Game Version: 0.D-11543-g3e11834
 - Graphics version: Tiles
 - Mods loaded: None (issue manifests whether mods are loaded or not)

# Additional context

This issue has occurred with every experimental release I've tried since at least the New Year.

**Comment by Qrox** [comment]
Did it eventually load or did it hang forever? The speed of recipe loading has been low because of some sort of automatical requirement calculation that involves mapgen (or that's what gprof suggests, at least)

**Comment by HaplessOperator** [comment]
It hangs forever. The last time I left it running, I figured it wasn't doing anything after about 25 minutes on the item during finalization.

**Comment by RobertoVGoulart** [comment]
It's probably related to your OS, since that kind of problem would be reported earlier if it was happening with more common OSs.
Can you tell which was the latest version of CDDA that worked on your end? that might help find the problem.

**Comment by HaplessOperator** [comment]
I'll go down through the builds and see if I can find one. So far, the only one I can remember working since I started playing last month, for absolutely certain, is the 0.d Stable configuration. I'll get back to you on that as soon as possible.

**Comment by HaplessOperator** [comment]
Update, I've gone back through to the beginning of December/end of November, around build 10100, and I'm still getting hangs on the Crafting Recipes item; conditions for attempting character creation and game state are no changes to default settings after installation, and with default worldgen settings.

**Comment by BevapDin** [comment]
`get_note_symbol` (in "src/overmap_ui.cpp") only extracts a single `char` from the note to be used as symbol. The game will therefor not show UTF-8 sequences that are encoded with several bytes. This would need to be changed to return arbitrary strings containing a single effective character.

**Comment by Qrox** [comment]
@BevapDin but that's not the topic of this issue. Maybe you intended to reply elsewhere?
