### ISSUE TITLE
aarch64 build fail with new GCC 10

### ISSUE THREAD

**Issue by tim77** [CleverRaven/Cataclysm-DDA#37303]
# Describe the bug

After switching to GCC 10 on Fedora Rawhide `aarch64` arch won't compile anymore:

```
/usr/lib/gcc/aarch64-redhat-linux/10/include/arm_neon.h:34612:10: fatal error: arm_bf16.h: No such file or directory
34612 | #include "arm_bf16.h"
      |          ^~~~~~~~~~~~
```

# Versions and configuration

 - OS: Fedora Rawhide
 - GCC: `10.0.1-0.3.fc32`
 - Game Version: `0.D.10232-ff0f233`
 - Graphics version: Tiles + Terminal

# Additional context

[Full build log](https://kojipkgs.fedoraproject.org//work/tasks/1911/40821911/build.log).

**Comment by ZhilkinSerg** [comment]
I don't think we can help here. It looks like SDL issue for me.

**Comment by tim77** [comment]
@ZhilkinSerg thank you. I should try to report this in SDL upstream probably.

**Comment by ZhilkinSerg** [comment]
Yeah, just to make sure, try compiling CDDA without Tiles support and also try compiling SDL lib alone.

**Comment by tim77** [comment]
Closing. Filed upstream bug
https://bugzilla.libsdl.org/show_bug.cgi?id=4957
