### ISSUE TITLE
Gaps in map memory

### ISSUE THREAD

**Issue by chaoticidealism** [CleverRaven/Cataclysm-DDA#37318]
When exploring, sometimes there are gaps in what the character remembers on the map. I don't mean that they eventually forget it; I mean that they never remember it to begin with. See attached file for an example.

# Steps To Reproduce
Start a game, explore some, and notice that there are places that can't be remembered. This is especially noticeable in large structures, but will happen in one-tile houses too.

# Expected behavior
Map memory shouldn't have gaps.

# Screenshots
![Screenshot_4](https://user-images.githubusercontent.com/7295004/72959861-da3d2980-3d79-11ea-8053-c070f1d08ac1.jpg)
This is a mine level, fully explored except for the spot behind the poison gas. The stairs are off to the left side of the screen; the character entered through those stairs and explored the level. There is a memory gap right next to the stairs, and two more square gaps above the character.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.D-11543-g3e11834 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Garden Pots [growable-pots],
    Generic Guns [generic_guns],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    EZ-Mode Medical [fast_healing],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Mythical Martial Arts [MMA],
    No Fictional Guns [no_rivtech_guns],
    No Flaming Weapons [no_flaming_weapons],
    Classes and Scenarios Mod [more_classes_scenarios],
    Safe Autodoc [safeautodoc],
    Manual Bionic Installation [manualbionicinstall],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

**Comment by shadowsapex** [comment]
I was able to fix the map memory temporarily by quitting out and back in

**Comment by chaoticidealism** [comment]
> 
> 
> I was able to fix the map memory temporarily by quitting out and back in

Good to know, at least there's a temporary fix.

**Comment by kevingranade** [comment]
Based on the symptoms it's something to do with the top level map memory cache.  A tile is only eligible to be memorized the first time you see it, and it's ignored after that, so if you can somehow see a tile but it doesn't draw a memorize-able symbol, it will record nothing.

**Comment by chaoticidealism** [comment]
> 
> 
> Based on the symptoms it's something to do with the top level map memory cache. A tile is only eligible to be memorized the first time you see it, and it's ignored after that, so if you can somehow see a tile but it doesn't draw a memorize-able symbol, it will record nothing.

So maybe the best way to track this one down is to see when the "see a tile" function is called, and then figure out which instances of it don't come with a "memorize tile" afterward?
