### ISSUE TITLE
The age_grow and baby_timer attributes take more time than intended

### ISSUE THREAD

**Issue by RarkGrames** [CleverRaven/Cataclysm-DDA#37324]
# Describe the bug

Animals take 2-3 more time to grow from their young to mature animal than the number specified in their `age_grow `entry. Spawned a calf, a cattle dog puppy, a bulldog puppy, a piglet, a bear cub. They matured in 2-3 times the amount of days given at age_grow.
baby_timer seems to be the same (2-3 times the given value).

# Steps To Reproduce

1. Spawn a calf and teleport 5+ tiles away.
2. Forward the world time by 200 days (calf `age_grow `is 180).
3. Teleport back to the calf.
4. It fails to upgrade.
5. Repeat the above 1-2 more times.
6. The calf is now upgraded.

# Expected behavior

Animals upgrading according to their `age_grow `attribute, reproducing according to their `baby_timer `attribute.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.D-11543-g3e11834 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

See comments in #37283.

**Comment by SirPendrak** [comment]
Maybe its related to default evolution rate being x4 as slow?

**Comment by RarkGrames** [comment]
No, this is a fixed number. Evolution uses a different calculation that is semi-random and based on the evolution speed.
