### ISSUE TITLE
Game crash after withdrawing money

### ISSUE THREAD

**Issue by HunorP** [CleverRaven/Cataclysm-DDA#37327]
# Describe the bug

Game crashes after using the ATM at Percy Shanks underground bunker. 

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-11566-g5e2728e [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Garden Pots [growable-pots],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    Mythological Replicas [nw_pack],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Secronom [secronom],
    Cataclysm++ [Cata++],
    Hydroponics [hydroponics],
    Mythical Martial Arts [MMA],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks],
    No Recreationals [No_Recreationals],
    SpeedyDex [speedydex],
    Classes and Scenarios Mod [more_classes_scenarios],
    Stats Through Kills [stats_through_kills]
]

# Additional context
Crash log:
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4104874/crash.log)
Debug log:
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4104875/debug.log)
Save: Having two characters after restart

[Alaska.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4104909/Alaska.zip)

**Comment by Fris0uman** [comment]
I can't load your save due to it having some third party mods and I cant reproduce the crash in vanilla. Withdrawing cash from an ATM seems to work fine. So the bug might be caused by the mods.

**Comment by Qrox** [comment]
Looking at the crash log, it seem to be a crash during autosave, rather than after withdrawing money.
