### ISSUE TITLE
Put some mania in Pyromania

### ISSUE THREAD

**Issue by vlad1492** [CleverRaven/Cataclysm-DDA#37337]
**Is your feature request related to a problem? Please describe.**  

Watching a vast field of fungus burn in glorious heat and light my pyro said 'meh'. 
Yeah, he got a small mood elevation for lighting the fire and being close to it. 
But I think city-sized blazes should add a large long-lasting mood elevator. 

**Describe the solution you'd like**  
How about +50 on morale for 24-hours if the blaze qualifies as epic? 
Roughly double what an optimist with great music enjoys. 

**Describe alternatives you've considered**  
Do nothing

**Additional context**  
Is it hard to extract 'how many tiles currently have 'fire' in my reality bubble?'

**Comment by kevingranade** [comment]
Pyromania is already on thin ice  no interest in extending it even further.
