### ISSUE TITLE
It's tiome for biomes. It's time for bimes? Work with me.

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#37336]
# Is your feature request related to a problem? Please describe.
Worldgen currently makes an infinite, basically similar eternal region of small towns. There are no large cities, nor any rural areas with no cities.

We have most of what is needed to change this already. Regional settings let us define a lot of details related to how a specific biome might appear. It's possible, for example, to make a rural biome without malls and trinket stores, without labs and mansions and military bases, with more farms and forests and cabins. It's also possible to make a city biome, where farms and cabins don't spawn, swamps are rare, and forests are crisscrossed with trails. Finally, the biome settings allow us to change a region's groundcover, so we can even make sandy wastelands and deserts.

With just a little expansion, we could have distinct biomes, which would allow another level of control, and with the right set of features would dramatically improve mapgen with relatively little work.

# Describe the solution you'd like
There are a lot of long term goals I'm not going to get into here, like revamping city mapgen entirely. With just a few (I think) small additions, though, we can use what we have to accomplish a lot.

Here are the phases I see being necessary.
1. Region settings need a way to at least partially adjust city size and spacing.
2. Region settings could use a way to limit the appearance of particular map specials beyond just whitelist/blacklist.
3. We need a way to weight each set of region settings as a biome list

Once we have those, there are a few possible stretch goals.
4. Stretch goals to biome definitions file

## 1. Region settings for city size and spacing

The current code for what city size and spacing do is bad. The simplest thing to do in region settings, I think, is just to add minimum and maximum caps to the user-set city size and spacing options, so that some biomes will always have sparse or dense cities.

For example, for an urban region:
```
"city_size": [ 12, 16 ],
"city_spacing": [ 0, 2 ]
```
If at worldgen the player had set city size to 8, then the urban biome would automatically pump it to 12. If the player had set 15, then the urban biome wouldn't change it. City spacing works the same.

Conversely, for a rural region, city size might be `[ 0, 2 ]` and spacing `[ 7, 8 ]`, ensuring cities are always small and spaced out.

## 2. Region settings limiting special appearance

Map special appearance is currently defined by two things: settings within the map special itself, and region whitelists and blacklists by map special tag. I would like a third setting allowing a maximum number of appearances of map specials of a particular tag, eg.
```
"special_counts": [
  { "flag": "LAB", "count": 1 },
  { "flag": "MILITARY", "count": 2 }
]
```
This would allow the game to choose specials normally, but as soon as a single special with the LAB flag had spawned, labs were thenceforth treated as blacklisted. Likewise, two military specials could spawn, and any further military specials would be forbidden.

Again, this is a coarse tool, but it would be a good way to allow things like rural mansions while keeping rural biomes from getting overrun with mansions and labs. Eventually, being able to weight each tag would also be nice.

## 3. Biome settings file

In overmap settings we need a biome definitions file that allows us to define how often each biome type appears. It would be a pretty simple thing, at its most basic:

```
"biomes": [
  { "biome": "urban", "weight": 100 },
  { "biome": "suburban", "weight": 300 },
  { "biome": "rural", "weight": 1000 },
  { "biome": "wilderness", "weight": 100 },
]
```
Then, of course, each region_settings entry has to get a `biome` attribute stating its name for this.

At its heart, that's all we'd need for some pretty diverse biomes. We could have overmap-sized megacities, surrounding small towns similar to what we've got, mostly-empty forests with sparse cabins, and rural areas loaded with farms. With a few stretch goals, we could get really crazy, and still not need much more coding.

## 4. Biome setting stretch goals
These are things that could expand power, and wouldn't be too affected by redoing city spawning rules, but aren't really needed for enabling biomes.

### 4a. Adjust weight of biome appearance based on adjacent biomes
Within a region settings definition, a multiplier ratio for what biomes are allowed to appear adjacent would make it so that, for example, urban biomes would tend to be surrounded by suburban or rural, and not wilderness. When we start adding in fancier biomes, like desert, we can use this to ensure a desert biome doesn't, for example, sit adjacent to a frozen biome.

I picture this looking something like:
```
"near_biomes": [
  { "biome": "urban", "multiplier": 1.3 },
  { "biome": "rural", "multiplier": 0.5 },
  { "biome": "wilderness", "multiplier": 0 }
]
```
This would make wilderness biomes never spawn next to the biome in question, rural with half the usual weight, and urban with 1.3 times the usual weight.

### 4b. Adjust weight of biome appearance by cardinal direction.
This is an extension of 4a, that would allow a bunch of super cool things, like hitting the coast when you travel east, and deserts south.
```
"near_biomes": [
  { "biome": "urban", "multiplier": 1.3 },
  { "biome": "rural", "multiplier": 0.5 },
  { "biome": "wilderness", "multiplier": 0 },
  "northeast": [ { "biome": "eastern_shore", "multiplier": 10 } ],
  "east": [ { "biome": "eastern_shore", "multiplier": 20 } ],
  "southeast": [ { "biome": "eastern_shore", "multiplier": 15 } ]
]
```
This example assumes eastern_shore has a very low beginning spawn rate. Then, the eastern_shore biome itself doesn't allow any biomes to spawn further east besides `shallow_ocean`. Thus, once you get a shore biome, it's ocean further out. Until we implement 4c, at least.

### 4c. Allow a max number of times a biome can spawn per game, for unique biomes.
This would probably be a region_settings feature, ie. `"max_instances": 1` for a specific region, one that perhaps contains some unique features.

Having unique biomes would allow at least two things I can think of:
- at long last, we could make the refugee center, hub01, and other specials only spawn once per game... we put them as guaranteed spawns in special overmaps.
- With a bit of tweaking and some new infrastructure, we could think about getting unique, possibly hand-drawn overmaps, such as the island of Nantucket, or the city of Boston.

# Describe alternatives you've considered
Waiting for city and region settings to advance to the point where this happens naturally. There's an argument for this: my suggestion depends on settings like city size and spacing that are likely to get removed. However, I think what I have here would dramatically improve mapgen, leading to giant cities and stretches of farmland or forest.

# Additional context
I've already coded most of the settings for a rural biome. I could do a few more in about an hour. Imagine having to brave the city if you want to get to a mall, or fleeing to a farm in a rural area but knowing the cost of doing so is that it's going to be a long trip anytime you want to go to a lab.

I think this relatively small change could be an enormous positive shift to the game.

**Comment by Hirmuolio** [comment]
Multiple types of forest/field/city in single biome would also be nice. At least unless the biome areas are made really small (which would probably mess with spawning of large cities so I assume biomes would be at least one overmap block).

Forest already has three hardcoded variants "forest", "forest_thick" and "forest_water" (=swamp). It would be nice if there could be more variants within single biome.

**Comment by Diabolus-Engi** [comment]
I'm at a stage now where I've added what you have described and mostly just tinkering around with the blending of overmap borders and debating on keeping biomes the same size as overmaps or with variable sizes with the potential for multiple biomes to be potentially present in an overmap.

I feel that biomes being the size of an overmap may be somewhat restrictive?

**Comment by I-am-Erk** [comment]
I don't think there's much call to make them any smaller... That can be done through maps and map specials. Making them larger would be cool but I assumed that would be something we figured out later using map connectivity somehow

**Comment by Diabolus-Engi** [comment]
Well it’s not so much making them smaller but allowing biomes to “blob” making them less grid-like. But yes, should probably be figured out later. I’ll push a PR with biomes in the next couple of days, just mocking up some region settings to test it more as currently only using the default, desert and rural settings which I’m using desert as the worst case scenario to blend neighbor biome borders with, and adding some polish.

**Comment by LyleSY** [comment]
This is super cool. The EPA has been working on a similar mapping effort that may be helpful, or at least inspire some ideas https://www.epa.gov/eco-research/ecoregion-download-files-region#pane-01  . I'm not clear how well this can work without a coast though, that's crucial for organizing real-world biomes, rivers, etc.

**Comment by I-am-Erk** [comment]
I think this has had its day and we've got better ideas now. I will see about posting tem.
