### ISSUE TITLE
Errors examining or picking up items dropped by dead NPC

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#37339]
# Describe the bug

After I killed NPC Omar Bender inside my base in self-defense, he dropped a bunch of items, including a radio and crossbow that emit errors when I try to `e`xamine or `g`rab them:

```
 DEBUG    : Requested non-existing faction 'solo_Omar Bender'
 FUNCTION : faction* faction_manager::get(const faction_id&, bool)
 FILE     : src/faction.cpp
 LINE     : 456
```

followed by:

```
 DEBUG    : item::get_owner_name() item two-way radio has no valid nor null faction id 
 FUNCTION : std::__cxx11::string item::get_owner_name() const
 FILE     : src/item.cpp
 LINE     : 1087
```

# Steps To Reproduce

1. Kill a hostile NPC
2. See if they drop any items
3. Try to examine or pick up their loot

# Expected behavior

Expected all of dead NPC's items to have similar ownership/faction attributes. Or, if there is some reason his radio and crossbow are owned by another faction, at least there should be no errors trying to examine them.

# Screenshots

Here are the two problematic items once I moved the corpse and clothing aside. Attempting to move them using advanced inventory manager or hauling simply does nothing (which seems fine, if these items aren't mine), but I only see errors if I try to `e`xamine or `g`rab them:

![image](https://user-images.githubusercontent.com/238395/73044020-0bbeff00-3e25-11ea-90eb-311a436a4e05.png)

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch; Distributor ID: Ubuntu; Description: Ubuntu 18.04.3 LTS; Release: 18.04; Codename: bionic; 
- Game Version: 0.D-11480-gdcdef1eefc [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Disable Religious Texts [no_religious_Texts]
]

**Comment by wapcaplet** [comment]
I was able to reproduce this a couple more times in a build from master today (0.D-11818-g2c8919d95b) with these steps:

- Create a new world
- Create a new character
- Debug in invincibility and a nice gun
- Debug spawn NPCs until one is hostile
- Kill NPC and see what they dropped

Once, the faulty item was a pot helmet; another time, a Mossberg 500 Security shotgun.

I have not tried killing friendly NPCs to see if it affects them too, but I might have to take the morale penalty and do it for science.

Attaching save game with a nearby corpse; the Mossberg 500 can't be examined or picked up, and shows up in red text:

![image](https://user-images.githubusercontent.com/238395/73574866-09b3fc00-4434-11ea-8907-d6e3a469fa85.png)

Save game:
[NPCville_CDDA_savegame.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4141433/NPCville_CDDA_savegame.zip)


- OS: Linux
    - OS Version: LSB Version: core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch; Distributor ID: Ubuntu; Description: Ubuntu 18.04.3 LTS; Release: 18.04; Codename: bionic; 
- Game Version: 0.D-11818-g2c8919d95b [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by wapcaplet** [comment]
I located the code that deals with factions after an NPC's death but it'll take some time for me to grok it:

https://github.com/CleverRaven/Cataclysm-DDA/blob/2c8919d95bfe93c3c719464017425ea0eee315d1/src/npc.cpp#L2406-L2417

**Comment by davidpwbrown** [comment]
Cant reproduce, but can reproduce linked issue which is a different circumstance.

**Comment by davidpwbrown** [comment]
Well, either way, the linked PR will fix all future instances of this type of bug, hopefully
