### ISSUE TITLE
In-game text says you can make 8 expansions to a field base, but can only make 6

### ISSUE THREAD

**Issue by LuigiWhatif** [CleverRaven/Cataclysm-DDA#37333]
# Describe the bug

When speaking to NPCs about building camps, they say you can make 8 expansion to a field camp.  However since currently expansions are tied to beds you can only make 6 expansions to a field camp, so the text is incorrect

# Steps To Reproduce

1. Speak to an NPC. select: "Let's talk about faction camps" -> "Tell me how faction camps work" -> "Tell me about building a camp" -> "Tell me about modular field camps" -> "Got it.  Tell me about expansions."
The NPC will say that each camp can have up to 8 expansions.
2. Build all possible beds.  Since each pair unlocks an expansion and you can only build 6 pairs of beds, only 6 expansions are possible.

# Expected behavior

That in-game description should match current mechanics.

# Screenshots

**If applicable**, add screenshots to help explain your problem.

![CataclysmDDA_BaseExpansionText](https://user-images.githubusercontent.com/60243435/73034373-88d47f00-3df9-11ea-88a6-79340f96dcf0.PNG)

![CataclysmDDA_AllBedsBuilt](https://user-images.githubusercontent.com/60243435/73034292-4c088800-3df9-11ea-9da5-3ee8170829b1.PNG)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 7 Professional
- Game Version: 0.D-11568-gfe570fa [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Bens GF recipes [Tolerate_This],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    DinoMod [DinoMod],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    Urban Development [Urban_Development],
    Cars to Wrecks [cars_to_wrecks],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks],
    Mining Mod [Mining_Mod],
    More City Locations [cityside],
    Classes and Scenarios Mod [more_classes_scenarios],
    Manual Bionic Installation [manualbionicinstall],
    Safe Autodoc [safeautodoc],
    Disable NPC Needs [no_npc_food]
]

# Additional context

I don't know how to apply labels but I just want a text change.

**Comment by Soup-de-Loop** [comment]
Forgive me if I'm wrong, but I thought the expansions were to deal with the 8 map tiles around the central map tile, not the number of beds you can add?

**Comment by LuigiWhatif** [comment]
The map tile expansions and the bed construction are separate, but map tile expansions are dependent on bed construction.

**Comment by GGgatherer** [comment]
My biggest gripe with current state of basecamp system is fields-only restriction. When your basecamp is a shelter which has 6 of 8 adjacent overmap tiles as road, it feels... bad.

**Comment by curstwist** [comment]
> 
> 
> My biggest gripe with current state of basecamp system is fields-only restriction. When your basecamp is a shelter which has 6 of 8 adjacent overmap tiles as road, it feels... bad.

I'd love some changes too for transforming both pavement/roads and buildings into fields for expansion.  Maybe make a feature request?
