### ISSUE TITLE
Disassembling 30 bullets gives the components of a single round

### ISSUE THREAD

**Issue by Dziugaske** [CleverRaven/Cataclysm-DDA#37345]
# Describe the bug

If you want to disassemble 5.56 NATO rounds, you can only do so 30 rounds at a time. However, that only gives the components of a single bullet.

# Steps To Reproduce

1. Try to disassemble a round.
2. Get the message that you need 30 rounds.
3. Disassemble 30 rounds.
4. Wonder where 29 bullet casings disappeared off to.

# Expected behavior

30 rounds disassembled = 30 bullet casings.

# Screenshots

![bullet1](https://user-images.githubusercontent.com/42064096/73074798-16c86c80-3ec3-11ea-8f2b-1c7e19d62a00.PNG)
![image](https://user-images.githubusercontent.com/42064096/73074817-28aa0f80-3ec3-11ea-8e6b-8a7d0da570fc.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-11584-g115abba [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

This could be fixed by either reverting to the old way of disassembling a single bullet at a time, or increasing the disassemble materials 30 fold.

**Comment by Rogal-Dorn** [comment]
Can confirm this happens with 7.62x25mm and .38 as well.
