### ISSUE TITLE
Dismantling screen mesh walls tiles turn into a nothing tile

### ISSUE THREAD

**Issue by Illgowiththisname** [CleverRaven/Cataclysm-DDA#37341]
# Describe the bug

Dismantling a (house) screen mesh wall will turn the tile into a (house) nothing tile along with giving you the expected mesh screen, 10 nails and a plank.

# Steps To Reproduce

1. Get tools with hammering of 2 or more and screw driving of 1 or more. 
2. Find house with a screen mesh wall.
3. Shift + 8 for construction menu and select Deconstruct Furniture.
4. Use on screen mesh wall.
5. Wait for character to finish construction task.
6. Tile has turned into nothing tile with expected deconstructed items on it.

# Expected behavior

That tile becomes a Floor tile as smashing down the screen mesh wall will turn it into a floor tile, also the open or closed screen door will turn into a floor tile when disassembled or smashed.

# Screenshots

![cataclysm mesh wall to nothing](https://user-images.githubusercontent.com/60259456/73070658-b9a9d680-3f15-11ea-8c5b-3e8480ab4378.png)

# Versions and configuration

- OS: Windows
    - OS Version: Windows 7 Ultimate
- Game Version: 0.D-11584-g115abba [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Monsters [Only_Wildlife]
]

# Additional context

Don't think there's anything else to add but will add the testing save for well easy testing.

[testing.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4108540/testing.zip)

**Comment by Inglonias** [comment]
The mesh holds back the 𝕍𝕆𝕀𝔻

**Comment by Illgowiththisname** [comment]
also found that you can make these nothing tiles where you want since you can make the screen mesh walls in the construction menu using a mesh screen, 4 planks and 10 nails.
![more mesh stuff](https://user-images.githubusercontent.com/60259456/73111630-e2f75080-3f6f-11ea-97d0-429dcca58eba.png)
