### ISSUE TITLE
Follower won't wear an arm splint cause it's too cumbersome

### ISSUE THREAD

**Issue by Alapaga** [CleverRaven/Cataclysm-DDA#37352]
# Describe the bug

Having a follower with a broken arm and a splint wear something else makes em take off their arm splint. and upon trying to give them the arm splint back they will refuse to wear it back.

# Expected behavior

I would expect the follower to refuse to wear something that I want them to use because it would be too cumbersome for them because of their arm being broken and currently in a splint.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.D-11545-ge497763 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Generic Guns [generic_guns],
    Alternative Map Key [alt_map_key],
    Cars to Wrecks [cars_to_wrecks],
    Disable Religious Texts [no_religious_Texts],
    No Explosive Zombies [No_Explosive_Zombies],
    Classes and Scenarios Mod [more_classes_scenarios],
    Safe Autodoc [safeautodoc],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

https://www.twitch.tv/videos/541066175

**Comment by Alapaga** [comment]
Sorry for The delay, I accidentally hit enter while Ii was busy clipping the issue on video

**Comment by Taichi22** [comment]
I believe you can force-equip any gear you wish through the 'r', or layer menu with the use of 'e'.
Currently, giving them equipment in general is somewhat wonky.

**Comment by KorGgenT** [comment]
all right so this sounds more like a QoL feature request then
