### ISSUE TITLE
Can't use clean water when using washboard

### ISSUE THREAD

**Issue by SSpook** [CleverRaven/Cataclysm-DDA#37357]
# Describe the bug
Washboard and washing kit use only unpurified water.

# Steps To Reproduce
1. Get washboard, clean water, filthy equipment.
2. Use washboard, notice how water counter is at 0.

# Expected behavior
Expected to be able to use clean water to wash stuff, as washing machine can also use clean water.

 - Game Version: 0.D-11480-gdcdef1e
 - Graphics version: Tiles

**Comment by Melodeiro** [comment]
I remember, this was a very old issue. Maybe the reason is for accidentally do not wasting the clean water resources. Would be nice to have a hotkey to enable clean water usage then.
