### ISSUE TITLE
Multi-tile pirate cannon vehicle

### ISSUE THREAD

**Issue by SeventhSandwich** [CleverRaven/Cataclysm-DDA#37355]
**Is your feature request related to a problem? Please describe.**  
I'm interested in developing a pirate cannon for the game, which will function as a 3 tile vehicle. It will fire a powerful projectile capable of going through walls, at the cost of being extremely slow to reload, not aim-able beyond moving the vehicle, and composed of very heavy parts.  

**Describe the solution you'd like**  
I envision three separate pieces, a cannon muzzle, cannon bore, and cannon base, that need to be connected together in a line. After crafting the three parts individually, a player would install the base on a frame, followed by an adjacent bore, followed by the muzzle in line with the previous two tiles. This would require some new fundamental way of handling a vehicle part that can't be placed unless the selected tile is adjacent or positioned relative to another specific tile. 

**Describe alternatives you've considered**  
A single tile part would be far simpler but doesn't properly communicate the scale of a cannon. Also, a three tile cannon points in the direction that it will fire at, while a single tile does not. 

**Additional context**  
The main feedback I'm looking for here is whether developing a part that requires specific adjacent parts is a worthwhile to do for something as small as this project. Is the idea of a multi-tile cannon too out-there to make it into the main game?

**Comment by ZhilkinSerg** [comment]
You are overengineering this thing. Just use a 1x1 vehicle.

**Comment by SeventhSandwich** [comment]
Is the idea of multi-tile vehicle units overengineering in itself? Or is it overengineering for this specific project and viable for other ideas?

**Comment by ZhilkinSerg** [comment]
Existing turrets currently fit in a single tile and I don't see a reason to complicate things and make them larger.

**Comment by SeventhSandwich** [comment]
The thing is that existing turrets aren't realistically the same size as a pirate cannon. I don't think I can communicate the scale/shape of a pirate cannon with only one tile.

**Comment by TechyBen** [comment]
Don't things like handles etc already do this? Only installable on the outside? IIRC there are some part requirements for where/how a part can be installed ("External Cargo Carrier" for example cannot be installed on a frame panel). If you just wish to have multi tile required, that might be a place to start, and RP the shape of the cannon.

**Comment by SeventhSandwich** [comment]
I've come up with a compromise idea that I hope fixes the overengineering issue and also addresses the aesthetic issues of communicating the size and proportions of a ship cannon.

It would work as follows:
1. Place a cannon base part on a vehicle tile with a frame
2. Place a cannon muzzle on a tile with no frame, but adjacent to a frame (i.e. same rules as side mirror or bike rack)
3. Select the cannon muzzle direction using numpad (same way as with headlight)
4. Operate the cannon by interacting with the base. This is the part where it will prevent you from loading or firing it unless it's connected to a muzzle.

This simplifies the design into a much more manageable 2x1 tile unit, instead of 3x1. And there is no need to prevent the user from placing the vehicle parts in any specific order - it just won't fire if a muzzle and base aren't colinear. 

What are the thoughts on this?

**Comment by Rail-Runner** [comment]
Just for reference, it was said before that an 1 lb (or smaller, for that matter) cannon would be fine to add if it was using the current turret system as-is, fitting within one tile and being able to be installed onto a shopping cart. Way smaller than a pirate cannon, but still that's something.

**Comment by kevingranade** [comment]
To reiterate, if you're planning on making anything larger than a one pound cannon craftable, that's very much mod territory.
In practical terms, a more than one meter long cannon is ludicrously impractical for the survivor to use, much less craft,  you're getting into wespons that require a firing crew and dedicated vehicle to fire.
I don't really buy the "only fire in cardinal directions" limitation, cannons take a long time to aim, but you can aim them to an arbitrary precision. 
On the other hand, you seem to be neglecting recoil, you can't simply mount a cannon as large as what you're describing,  it has to be mounted on some kind of carriage or recoil management device.
