### ISSUE TITLE
"Fire nearby" scenerio flag doing nothing

### ISSUE THREAD

**Issue by Presence-Eternal** [CleverRaven/Cataclysm-DDA#37378]
# Describe the bug

Scenarios that contain the "Fire nearby" flag don't start the player in a location that burns down. Sorry if this is a known or deliberate issue.

# Steps To Reproduce

1. Start a new game with the scenario "Really Bad Day" or "Burning building"

# Expected behavior

1. Building should rapidly burn down.

# Versions and configuration

Version: 0.D-11604-g12076fe (tiles)
Build: 10252
All settings at build default.

**Comment by Inglonias** [comment]
Spawned in a burning building scenario with no mods enabled and gave myself a clairvoyance cube. No fire to be seen.

![image](https://user-images.githubusercontent.com/2125926/73142134-60e35680-4059-11ea-8954-f8021f673c97.png)

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.D-11646-g16ef318 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by Presence-Eternal** [comment]
Problem seems to be fixed as of recent builds.
0.D-11792-g5b19149 (tiles) Flag seems to work as expected.
