### ISSUE TITLE
Can't pick up faction items

### ISSUE THREAD

**Issue by Melodeiro** [CleverRaven/Cataclysm-DDA#37376]
# Describe the bug

After killing some bandits, i can't loot their items. Nothing happens, pickup window is just closes, and no items are picked up. In earlier versions (couple of months ago), i remember, there was a warning when you pick up faction items, so you can chose to proceed.

I might be wrong, but there was a spam of warnings, that i am trying to pickup faction items by my auto-pickup settings, and i chosen it to "never show and don't pick up" or something like that. Probably this is also prevents you from manual picking up as well.

Also i didn't found where can i re-enable such warnings.

# Expected behavior

Prevent auto-pickup from picking up faction items, and don't show warnings, while allowing to pick them up manually.

An option to enable warnings about faction items.

# Versions and configuration

- OS: Windows
    - OS Version: Windows 10 1809
- Game Version: 0.D-11588-g8fd783c [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Aftershock [aftershock],
    Арсенал Icecoon'а [ew_pack],
    Вымышленное оружие от DeadLeaves [FIC_Weapons],
    Доп. инструменты для выживания [More_Survival_Tools],
    Садовые Горшки [growable-pots],
    Модульные турели [modular_turrets],
    Ремонт роботов [Salvaged_Robots],
    Mining Mod [Mining_Mod],
    NPC-мутанты [mutant_npcs],
    Альтернативные символы карты [alt_map_key],
    Гидропоника [hydroponics],
    Бета Лагерь Национальной Гвардии [national_guard_camp],
    Больше локаций [more_locations],
    Больше зданий от Fuji [FujiStruct],
    Городская застройка [Urban_Development],
    Набор дополнений для машин [blazemod],
    Горнопроходчик и шахтёрская техника [Heavy miners],
    Набор складных деталей [deoxymod],
    Танки и другой транспорт [Tanks],
    Некромантия [necromancy],
    Безопасный автодок [safeautodoc],
    Быстроловкость [speedydex],
    Мод на классы и сценарии [more_classes_scenarios],
    Отключить потребности у NPC [no_npc_food],
    Пак военных профессий от Fuji [fuji_mpp],
    Ручная установка бионик [manualbionicinstall],
    Упрощённое питание [novitamins],
    Характеристики за навыки [StatsThroughSkills],
    Характеристики за убийства [stats_through_kills],
    Без фунгалоидов [No_Fungi]
]

**Comment by Trioct** [comment]
For re-enabling, you should be able to do it through
Action Menu (Enter) -> Misc -> Toggle thief mode
in the mean time

**Comment by Melodeiro** [comment]
Oh thank you, i see, there is 3 modes. Well, still not very clear when you chose to pickup only faction items, and inventory just closes with no result. I can imagine only 1 rare use case for this, when you chose to "loot all" and wants to ignore faction items. So i would add a prompt when you chose **only** faction items for pickup. Or just ask player, if he is chosing at least 1 faction item (and any non-faction)
