### ISSUE TITLE
Mapgen-defined spawns aren't subject to migration

### ISSUE THREAD

**Issue by tenmillimaster** [CleverRaven/Cataclysm-DDA#37372]
# Describe the bug

Migrations don't apply to map gen defined spawns, such as those in \data\json\mapgen\military\mil_base\mil_base_z0.json

# Steps To Reproduce

Spawn world with generic guns
Choose surrounded start
Choose overrun
Make your way to the armoury
Enjoy the segfault, and behold the m4a1's.

# Expected behavior

Assault rifles instead.

# Versions and configuration

Dark Days Ahead
Disable NPC Needs
Generic Guns

**Comment by Brian-Otten** [comment]
![image](https://user-images.githubusercontent.com/47374323/74030405-44c3ab80-49af-11ea-9044-7c26db26954c.png)
Just confirmed this bug.
