### ISSUE TITLE
Completely destroyed short ropes still combine to make a pristine long rope

### ISSUE THREAD

**Issue by Alapaga** [CleverRaven/Cataclysm-DDA#37370]
# Describe the bug

As title says, this makes short ropes that are XX still usable for crafting long ropes

# Steps To Reproduce

1. Find 5 destroyed XX Short ropes on wreckages
2. Craft a long rope
3. Congratulations you now have II Long rope in your inventory

# Expected behavior

As it is destroyed, i don't think a short rope in that state is usable for crafting purposes. And if it is, the resulting long rope would have to take that into account and have according levels of damage. 

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.D-11592-gbb45b9a [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Generic Guns [generic_guns],
    Alternative Map Key [alt_map_key],
    Cars to Wrecks [cars_to_wrecks],
    Disable Religious Texts [no_religious_Texts],
    No Explosive Zombies [No_Explosive_Zombies],
    Classes and Scenarios Mod [more_classes_scenarios],
    Safe Autodoc [safeautodoc],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Ulysses2** [comment]
XX items aren't destroyed, they're in the very last stage before destruction, but can still be repaired. It's confusing because installed XX vehicle parts actually are unusable and not repairable.

**Comment by TechyBen** [comment]
Also, XX parts in vehicles do, as said above, "still exist", frames etc show, but 1 hp past fall off/crumple (right?).

I guess this is one of the limits to the crafting/content/tracking system so far. At some point I assume we might get to the point damaged parts would result in a damaged end product. :)
