### ISSUE TITLE
"Experience to next level" shows useless value

### ISSUE THREAD

**Issue by Melodeiro** [CleverRaven/Cataclysm-DDA#37397]
Not sure, if its a bug or feature request.

If you enable a mod with stat points via kills, when you have an insufficient XP, you will get a message with the total amount with XP needed to get to the next level up.

Would be much more useful if it will show the remaining amount instead. Just total amount isn't informative at all

# Steps to reproduce:
1. Enable level up through kills mod
2. Try to increase stats to get the warning window

**Comment by Relyksboa** [comment]
you can check the exp you have in the kills menu, if that helps.

**Comment by Melodeiro** [comment]
> you can check the exp you have in the kills menu, if that helps.
Yes i know, but thats extra ~15 buttons in compare to my proposal (well, about 6-7, if you remember hotkeys)

Also the biggest irony is that the amount, you need to get to the level isn't showed there as well. So you have to first open kills, remember current XP, open stats, get the required XP, then substract.

The best solution maybe is to show current/needed XP in both places, like most games are doing.
