### ISSUE TITLE
"Use this item" in NPC dialogue can lead to bugged armor removal

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#37398]
# Describe the bug

When trying to make NPC wear a piece of armor/clothing, it may result in removal of other piece(s) of armor/clothing even when they are on different layer(s).

# Steps To Reproduce

1. Load [save](https://drive.google.com/open?id=1YplTX7J1GxGrjHPokhhEgzzxE9uGi84c). Or create a follower and spawn kevlar vest, swat armor and backpack.
2. Try to make the follower (Soledad Marks in attached save, next to player character) wear all those 3 items via "talk -> use this item" dialogue.
3. Fail horribly:
* armor+vest, try adding backpack, she takes off the vest
* armor+backpack, try adding vest, she takes off the armor
* vest+backpack, try adding armor, she takes off *both* vest and backpack
4. Use "sort armor" window instead -> succeed.

# Expected behavior

Items actually being worn if they don't conflict with each other.

# Versions and configuration

- OS: Windows 7 x64
- Game Version: 0.D-11601-g30a5718 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by TechyBen** [comment]
Getting the same. For example, a backpack equipped will remove torso armour, or visa versa. Can be worked around using the sort armour option and forcing use or trying again at times seems to work.

**Comment by Alapaga** [comment]
I can confirm this being an issue, I reported something similar a couple days ago here https://github.com/CleverRaven/Cataclysm-DDA/issues/37352
Temporary workaround includes trading the items with the NPC and equipping the armor you want them to wear from the sort armor menu.

**Comment by Ramza13** [comment]
How it works is if an NPC tries to equip something and can't, they will take off gear until they can put it on and then do so.

**Comment by Ramza13** [comment]
So having looked at the code right now there is an attempt to have some intelligence around the NPC putting on items.  However its not very fleshed out or effective.  I'm debating the best way to fix this.

I could just remove the logic and force equip like the sort armor window.  
I could remove the option or have it open the sort armor window.  
Or I could try to fix the logic and NPC intelligence but I'm not sure exactly what the desired behavior would be.  

Do we want NPC's to do whatever they are told or to try and resist certain bad ideas?  Not sure yet the best solution.
