### ISSUE TITLE
Zombies seemingly hit Limbs of animals

### ISSUE THREAD

**Issue by Relyksboa** [CleverRaven/Cataclysm-DDA#37391]
# Describe the bug

As seen in the screenshot, the zombie hits legs and arms of the moose.

# Steps To Reproduce

1. spawn a zombie and a moose
2. watch them fight and notice strange messaging

# Expected behavior

Ideally also describe *why* you expect it to happen.

# Screenshots

![moose limb attacks](https://user-images.githubusercontent.com/52992503/73126154-26e45880-3f64-11ea-9e46-ba60c5c206c3.PNG)

**Comment by GGgatherer** [comment]
Well... really fixing this would require adding correct limb names for each and every monster, or at least class of monsters, in the game. Doubt it's high on the "issues-to-fix" list.

**Comment by Ulysses2** [comment]
No, just make them not mention limbs when attacking a monster.

**Comment by kevingranade** [comment]
Probably something is not initializing a limb variable.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-10876.

![изображение](https://user-images.githubusercontent.com/11132525/187021576-dcbd0755-5515-4433-83f5-62562523ecfa.png)
