### ISSUE TITLE
Unable to view clothing modifications if only one option is available

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#37403]
# Describe the bug

When you use tailor's kit and select "modify clothing", you get a menu with several options (fur, leather, steel, etc.). If no options are available, or all of them are available, you may select each one and see what it does. But if only one is available, it is selected by default and you cannot select any other.

# Steps To Reproduce

1. Make a player with charged tailor's kit and some clothing.
2. Try activating TK, select "modify clothing", select a piece of clothing, see all options are in grey but you can check them all.
3. Now spawn an item(s) needed to actually use one of those options and try using TK again. You'll be stuck on the only available option.

# Expected behavior

Let us check what all options do regardless of materials availability.

# Versions and configuration

-    OS: Windows 7 x64
-    Game Version: 0.D-11601-g30a5718 [64-bit]
-    Graphics Version: Tiles
-    Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills]
    ]

**Comment by anothersimulacrum** [comment]
Confirmed as of d978eeb966150794689ea1216d18f00828abc683

**Comment by Fris0uman** [comment]
The option doesn't exist anymore https://github.com/CleverRaven/Cataclysm-DDA/pull/58035
