### ISSUE TITLE
Can't unload any magazine

### ISSUE THREAD

**Issue by RobertoVGoulart** [CleverRaven/Cataclysm-DDA#37409]
# Describe the bug

Any of the magazines i tested can't be unloaded.

# Steps To Reproduce

1. Spawn a full magazine (Tested with STANAG HK417 and Thompson Makeshift)
2. Try to unload it

# Expected behavior

Magazine unloads normally, we get bullets and an empty mag.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-11646-g16ef318 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
Save file:
[Garber.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4113620/Garber.zip)

Bug was not present in build 10257, first appearing in 10258

**Comment by sztosz** [comment]
Maybe reintroduced https://github.com/CleverRaven/Cataclysm-DDA/issues/37326

**Comment by Inglonias** [comment]
Can confirm this is true in my save as well.

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.D-11646-g16ef318 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    No Rail Stations [No_Rail_Stations],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    No Fungal Monsters [No_Fungi],
    Classes and Scenarios Mod [more_classes_scenarios],
    Classic Roguelike Classes [RL_Classes],
    Disable NPC Needs [no_npc_food],
    INT Based Learning [intbasedlearning],
    Simplified Nutrition [novitamins]
]
