### ISSUE TITLE
Aftershock atomic smartphone not playing music

### ISSUE THREAD

**Issue by Entity-y** [CleverRaven/Cataclysm-DDA#37420]
# Describe the bug

The atomic smartphone doesn't play music.

# Steps To Reproduce

1. Use Aftershock mod.
2. Get an atomic smartphone.
3. Activate listen to music.

# Expected behavior

When activated, music should be playing through headphones like with the mp3 or smartphone.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-11598-g075afa3
 - Graphics version: Tiles
 - Mods loaded: Aftershock

**Comment by Unrepentant-Atheist** [comment]
Confirmed.

**Comment by Maleclypse** [comment]
My understanding is this has to do with hard coded mp3 use. If this is a json fixable issue I’m happy to work on it myself.

**Comment by Entity-y** [comment]
Maybe it would make sense to also add the mp3 function to the Wraitheon executive's smartphone as well, since it's custom variation to the atomic smartphone and lacks that feature.

**Comment by eilaattwood** [comment]
> 
> 
> My understanding is this has to do with hard coded mp3 use. If this is a json fixable issue I’m happy to work on it myself.

Exactly. The list of devices capable of playing music is hardcoded into mp3 function. Adding atomic smartphone there is simple, but not an elegant solution that prevents of adding new player devices into the game without C++ code editing.

**Comment by eilaattwood** [comment]
@Maleclypse 
I can make mentioned changes to the code and create PR to quickfix this for now, but as I mentioned above it will still work only for limited list of devices. Should I add just an atomic smartphone, or something else from the mod?

**Comment by Night-Pryanik** [comment]
A quickfix is still a fix, it's better than nothing.
