### ISSUE TITLE
Docs: Explain the difference between tiles and curses

### ISSUE THREAD

**Issue by jtagcat** [CleverRaven/Cataclysm-DDA#37430]
# Describe the bug
On the [releases](https://cataclysmdda.org/releases/) page, describe the difference between the versions.

**Comment by KorGgenT** [comment]
curses can be played in console and has no graphics. tiles has graphics.

**Comment by RobertoVGoulart** [comment]
Yes, and that's comon knowledge for people that already play roguelikes that have a tiles and a console version, but most new players won't know what's the difference.

A visual example, like Dungeon Crawl Stone Soup has on it's download page (https://crawl.develz.org/download.htm) would be nice and probably better than a text explanation.

**Comment by kevingranade** [comment]
Description was added.
