### ISSUE TITLE
Game crashing

### ISSUE THREAD

**Issue by tim77** [CleverRaven/Cataclysm-DDA#37448]
# Describe the bug

Game may crash in some conditions.

# Versions and configuration

 - OS: Fedora 31
 - Game Version: 0.D.10229-1.20200121git0696252
 - Graphics version: Tiles

# Additional context

[Original bug report and backtrace](https://bugzilla.redhat.com/show_bug.cgi?id=1795093).

**Comment by KorGgenT** [comment]
this is not a very helpful bug report. please follow the template properly.

**Comment by tim77** [comment]
I can't send you save file or logs from user machines for obvious reasons. Will close in future all such bugs on RHBZ as `CLOSED UPSTREAM` since they are "not very helpful".

**Comment by codemime** [comment]
The bug report looks good to me. It has a backtrace which clearly says where it crashed and, presumably, why. Sorry about that. Any contribution is welcome.

**Comment by Upsilion-Sigma-Eta** [comment]
This bug does not occur in the latest version of Cataclysm. Some of the merged code seems to be causing the problem.

**Comment by tim77** [comment]
`0.D.10304` pushed to Stable repos. If problem still persist please let developers know and reopen bug.
