### ISSUE TITLE
Vehicles Running/Idling After 20 Years/80 Seasons

### ISSUE THREAD

**Issue by leefy-greens** [CleverRaven/Cataclysm-DDA#37443]
Vehicles are still running/idling after starting 20 years or 80 seasons, post-cataclysm.

1. Launch an experimental version (anything beyond 0.D)
2. Adjust the following default parameters for worldgen:
Initial Day: 0
spawn delay: 1120
season length: 14
3. Start a game with Play Now! (Fixed Scenario)
4. Result in game: Year 20, day: 0, turn: 96796800 (at start/spawn, from Debug Menu)
5. Find a vehicle with idling smoke emitting from the muffler (you'll find them in cities or on roads, randomly)
6. 'E'xamine the vehicle controls tile (driver's seat, typically)
7. Select Control Vehicle
8. Note "Turn off the engine" as an option, as the engine is currently running.

# Expected behavior
Ideally, all the fuel and definitely all the batteries would no longer be viable in any vehicle, after 20 years.

# Versions and configuration
Happens in any version of Experimental that I've tried. The attached save is from build 10188.

# Additional context
The attached save has the player at a vehicle exhibiting this behavior, that is, 20 years after the cataclysm, and the vehicle engine is still running.
[Stumpy Point.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4118404/Stumpy.Point.zip)

**Comment by shadowsapex** [comment]
it's not 20 years if your seasons only last 2 weeks

**Comment by Hirmuolio** [comment]
It would still be about 3 years (with 14 day seasons 20 years = 1120 days. This matches with the turn number.).

**Comment by shadowsapex** [comment]
a car couldn't idle for that long but couldn't they still be functional after that long? Therefore an npc could've turned them on

**Comment by leefy-greens** [comment]
It doesn't matter how long you set it to or how many years later it is, you can make it 40 years at 90 days per season, with or without eternal seasons if you want, you'll still find cars idling / engines running.  None of those numbers actually matter, I just picked the ones I play with as a random example.  I think the crux of the issue is, the first time the reality bubble imposes itself in an area,currently, regardless of the year, the batteries are fine, the fuel is fine, and the engine is running.

Lastly, this also happens with or without NPCs of any kind, with or without monsters of any kind, in 0.D, and also in any experimental version.  In other words, I can't get it NOT to happen. :)

**Comment by Fris0uman** [comment]
Can you change the title of the issue to something like "Simulate passing of time effect on vehicles when spawning new ones", because what you discribe is not as much a bug as a missing feature.

**Comment by ZhilkinSerg** [comment]
We do not simulate world timeline (e.g. like DF does), so it is more like a feature request, than a bug.

**Comment by TechyBen** [comment]
Yeah. For now, some role play can be, survivors/military/bandits *recently* left the car there. Other than that, IIRC metal/vehicles/buildings degrading (and subsequent multiple different systems required for this) seems to be a stretch goal at some point. So it's there in the devs list of things to do.

**Comment by Night-Pryanik** [comment]
For now the chance to spawn vehicles with their engine turned on is based on time after the cataclysm:
https://github.com/CleverRaven/Cataclysm-DDA/blob/f8b23b8fbbbc60b1d89b69b12674164f24889c96/src/vehicle.cpp#L412-L419
So for year 20 the chance would be an EXTREMELY low. 
Tested on 0.F-6416, changed time to year 20, haven't found a single vehicle with its engine turned on.
