### ISSUE TITLE
Allow a specified rotation when placing a nested map

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#37459]
## Is your feature request related to a problem? Please describe.
When I'm designing a map that uses nested mapgen chunks, I often need to rotate them to face a different direction. This leads to a huge amount of duplicated work as I create "north", "south", "east" and "west" versions of a map. For example, in my `+` shaped lab map, I need to make four different versions of every large lab map to go in each of the 'wings'. This is a huge PITA and a massive waste of line counts.

**Describe the solution you'd like**  
Allow me to specify rotation when I place the item, using the syntax `"rotation": x` where x is 0, 1, 2, or 3.
`0`: No rotation compared to nested mapgen file definition.
`1`: 90 degree CW rotation
`2`: 180 degree rotation
`3`: 270 degree rotation (90 degree CCW)

 EG:
The following would place the beautiful_submap at point N, rotated 90 degrees CW.
```
"nested": {
  "N": { "chunks": [ "beautiful_submap" ], "rotation": 1 }
}
```

The following would place the gorgeous_submap and allow it to randomly spawn at either rotation 0 (no rotation), rotation 2 (180 degree rotation), or rotation 3 (270 degree rotation.
```json
"place_nested": [
        { "chunks": [ "gorgeous_submap" ], "x": 3, "y": 10, "chance": 75, "rotation": [ 0, 2, 3 ] }
],
```

## Describe alternatives you've considered
I would also love a way to horizontally or vertically mirror maps, but that gets into some order of operations stuff.

## Additional context 
I can't bring myself to finish my new lab floorplan until this is done, it's just too much repetition of the same design over and over.

**Comment by scorpion451** [comment]
Where in the code does the nested generation stuff live? I think I know a fairly simple and lightweight way to do this (including the mirroring) from my own procedural generation experiments, but I'd need to see the code to figure out how to plug it in. (Ideally, this function would go between reading in the template and passing that to the generator)

**Comment by I-am-Erk** [comment]
There is already an ability to rotate maps in mapgen, we basically just need to call that. Unfortunately I have no idea where that is. @ralreegorganon is probably the biggest expert there.
