### ISSUE TITLE
Make the character less stoic to great pain

### ISSUE THREAD

**Issue by Heaper327** [CleverRaven/Cataclysm-DDA#37456]
**Is your feature request related to a problem? Please describe.**  
Currently, the player controlled character is doom guy level stoic. No matter how much pain the character has, the character never groans or let out any sound. Tossed like a human basketball by a hulk? Completely silent. Almost electrocuted by a shocker? No painful screaming. Burning in blazing fire? No wailing of a burning person. The only time the character screams out of pain is when taking mutagens.

**Describe the solution you'd like**  
The character screams loudly when pain level abruptly increases (e.g. get shocked by a shocker, takes a bullet to the stomach): "The unbearable pain of <action> makes you scream!". The character groans randomly when pain level is above certain value: "You groan as your wounds start to hurt again". Code wise, whenever the pain level changes, check if deltaPain >= deltaPainThreshold * Random (0.75, 1.25) (or something similar), and make the character scream if the check passes. When the pain level is greater than painThreshold, the character groan with a 1 in (pain - painThreshold) * constant chance every turn. 
The formulas used for mutagen screaming and yelling can be used here: higher strength = louder, more mouth encumbrance = quieter, etc. Some traits increase/decrease the screaming and groaning threshold (pain tolerance, pain sensitive, deadened, etc) as well as the volume. Some traits/effects may completely prevent the character from making such noises (adrenaline spike, completely drunk, etc). Some other traits may have more _interesting_ impact on this mechanism (pain junkie makes you _moan_ instead of groan, etc). There could be many interesting interactions
For balance purposes, definitely give player a way to prevent their character from screaming (like biting on a towel or something) or at least lower the volume so that stealth does not get nerfed too much.

**Comment by TechyBen** [comment]
As long as we also have a straight for stoicism. ;) :+1:

**Comment by Marrim** [comment]
Actually, not even Doom guy is completely silent when in pain. Just saying.

**Comment by Brian-Otten** [comment]
Could use the code/idea of muffling yells when having mouth encumbrance to reduce pain sounds. Perhaps also add some gags/ ball gags to the craft system / suitable item groups to artificially encumber the mouth.

**Comment by Reclusive-reptile** [comment]
> 
> 
> Could use the code/idea of muffling yells when having mouth encumbrance to reduce pain sounds. Perhaps also add some gags/ ball gags to the craft system / suitable item groups to artificially encumber the mouth.

Player sound is already muffled by mouth encumbrance.
