### ISSUE TITLE
Pedal-driven bicycles are unrealistically rare

### ISSUE THREAD

**Issue by JerreeLynn** [CleverRaven/Cataclysm-DDA#37451]
**Is your feature request related to a problem? Please describe.**  
Bicycles are very difficult to find despite most households owning at least one in real life.

**Describe the solution you'd like**  
Spawn rates of bicycles should be increased, and should also spawn inside houses and garages.

**Comment by wapcaplet** [comment]
They *do* seem really hard to come by. Hippie vans, meth RVs and Humvees with M249 turrets are a dime a dozen, but I too have had a ridiculously hard time finding a bicycle lately (and the few I do find have busted wheels). I don't think I've ever seen a bicycle in a house garage, but I'm pretty sure one time I spotted a mountain bike in a 5th floor apartment.

Based on a text search in the JSON data, I think this file defines the vehicle drop rates for different areas:
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/vehicle_groups.json

The numbers there look pretty low to me. Electric cars and SUVs are over 3x more likely than a bicycle in "suburban_home", and bicycles don't appear at all in "garage", "city_pileup", "highway", "farm_vehicles", "junkyard_vehicles" and several other groups that arguably should include at least some chance of bikes.

This directory has a lot of map generation `.json` that may include bicycles and other vehicles with varying probability:
[data/json/mapgen](https://github.com/CleverRaven/Cataclysm-DDA/tree/master/data/json/mapgen)

I'll see if I can poke a few more bicycles in there, maybe using the approximate proportions from a real-world survey like https://www.statista.com/statistics/693817/percentage-of-people-in-households-who-own-a-bike-in-us-by-type/

**Comment by wapcaplet** [comment]
So it may be an obsession. I counted the spawn rates just for the `city_vehicles` group in [data/json/vehicle_groups.json](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/vehicle_groups.json) and *very* roughly grouped them by vehicle type. I didn't double-check my math but here's what I got:

- Cars: 34%
- Trucks: 21%
- Vans/buses: 14%
- SUVs: 8%
- Armored vehicles: 7%
- Motorcycles: 6%
- RVs/limos: 6%
- Bicycles: 3%

There is a better chance of finding a Beetle than a bicycle, and Hippie Vans are more than twice as likely. So I think it's fair to say we could do with a lot more bicycles, and maybe fewer armored cars while we're at it (but that's a different issue).

**Comment by curstwist** [comment]
I have added some spawns to city block map (check those alleys) and also some of the house garages.  We could use more though.
