### ISSUE TITLE
Lab turrets don't shoot because of an ammo issue

### ISSUE THREAD

**Issue by Alapaga** [CleverRaven/Cataclysm-DDA#37452]
# Describe the bug

My character encountered a turret in a lab, and then I got an error immediately. The conclusion was, turret can't shoot and it made that lab run trivial for me. Immersion breaking too, cause reading the error I understood that there's gonna be no shooting, and I could safely pepper that turret with arrows. I suspect the new changes to generic guns to be responsible for this, as this character was already shot at by a turret in a previous update. The turrets can't seem to use the ammo they used to, now I suspect them to call for light rifle ammo, and before they used to call for pistol ammo.
There's a similar issue here https://github.com/CleverRaven/Cataclysm-DDA/issues/37077 and it's a different kind of a turret but the error message is similar in nature

# Steps To Reproduce

https://www.twitch.tv/videos/542899678

# Expected behavior

I expected my character to get lit by the turret, it didn't happen that way tho. I expect to at least see the shells on the ground in case of a turret that's out of ammunition, but that's not what happened either. 

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.D-11668-g6a39a45 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Generic Guns [generic_guns],
    Alternative Map Key [alt_map_key],
    Cars to Wrecks [cars_to_wrecks],
    Disable Religious Texts [no_religious_Texts],
    No Explosive Zombies [No_Explosive_Zombies],
    Classes and Scenarios Mod [more_classes_scenarios],
    Safe Autodoc [safeautodoc],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4120117/debug.log)

**Comment by tenmillimaster** [comment]
Everything seems to be in order. 
![image](https://user-images.githubusercontent.com/7764202/78702420-2ce4a700-78ce-11ea-9908-50e74e155d52.png)

I think I fixed this in #37888.
