### ISSUE TITLE
Overworld map is plastered with "Abandoned Drivethrough"s

### ISSUE THREAD

**Issue by AncientSion** [CleverRaven/Cataclysm-DDA#37469]
[Oldenburg.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4123733/Oldenburg.zip)

# Describe the bug

The overworld map is full of abandoned drivethroughs.
In Tiles, the location (GUI) also reads the same, but the buildings are constructed correctly instead.

# Steps To Reproduce

?

# Expected behavior

proper worldmap which allows actually searching for good buildings.

# Screenshots

https://i.imgur.com/IrFL287.jpg

# Versions and configuration

win 10 x64

32 bit version launcher

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-11668-g6a39a45 [32-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Generic Guns [generic_guns],
    More Locations [more_locations],
    Disable Religious Texts [no_religious_Texts],
    No Antique Firearms [no_olg_guns],
    No Fictional Guns [no_rivtech_guns],
    No Flaming Weapons [no_flaming_weapons],
    No Medieval Items [no_medieval_items],
    No Sci-Fi Equipment [no_scifi],
    Simplified Nutrition [novitamins]
]

**Comment by Kilvoctu** [comment]
Might be worth noting that I cannot replicate this issue by resetting the (Oldenburg) world.

**Comment by ZhilkinSerg** [comment]
We can't help you with this save - it looks like you have saved you game in a version which did not do proper migration of houses after they were changed.

**Comment by AncientSion** [comment]
Too bad. Im wondering how that is possible tho. I only started playing cdda like a week ago and that is when i updated and afterwards began the save. Was it very very recently changed ?

**Comment by ZhilkinSerg** [comment]
I can't tell you unless I know specific game versions that you have used.

**Comment by AncientSion** [comment]
yeah, i cant tell. thanks for investigating tho.

**Comment by ZhilkinSerg** [comment]
Did you start on stable or experimental version? Can you upload your debug.log from config folder too?
