### ISSUE TITLE
Streamline brewing times and recipes

### ISSUE THREAD

**Issue by jkraybill** [CleverRaven/Cataclysm-DDA#37464]
**Is your feature request related to a problem? Please describe.**  
I noticed when fixing #33223 that the brew times, and a couple techniques, for various brewables feel arbitrary. The times currently required to brew these recipes are (in order of time taken):

ALCOHOL
Moonshine, Vodka: 6 hours
Beer: 9 hours
Whiskey, Rum, Fruit Wine: 12 hours
Mycus Wine: 15 hours
Dandelion Wine: 1 day 12 hours 40 minutes
Pine Wine: 1 day 16 hours 50 minutes
Mead: 5 days

(Not sure why dandelion and pine wine are so oddly specific.)

OTHER
Yeast Culturing - 2 hours, requires a glass flask
Curdling Milk - 4 hours
Vinegar - 7 hours
Gin (not an actual fermentation - a steeping that requires alcohol and juniper): 24 hours

(The current times for cream / pickles / sauerkraut / pickled eggs look OK to me and appear to be based on 1/3 of RL time.)

Sources I've googled show (in order of time taken):

ALCOHOL
Fruit Wine: 4-7 days primary fermentation (https://www.homebrewit.com/making-wine-with-fresh-fruit-general-instructions-and-tips)
Mycus Wine: not a thing, but presumably similar to fruit wine
Pine Wine: closest I could find is Retsina, but that is just grape wine flavored with pine (https://en.wikipedia.org/wiki/Retsina)
Whiskey: 5-17 days (3-15 days for ferment plus 2 days) (https://moonshiners.club/homemade-whiskey-recipe-and-technology/)
Moonshine Mash: 1-2 weeks (https://milehidistilling.com/how-to-make-moonshine/)
Dandelion Wine: 10-14 days (https://www.thespruceeats.com/how-to-make-dandelion-wine-1327932)
Rum: 3-7 days with raw cane sugar, 12-14 with molasses (https://milehidistilling.com/how-to-make-rum/), scientific sugar beet fermentation 3 days (https://www.hindawi.com/journals/bmri/2016/3154929/)
Vodka Mash: 2 weeks (https://milehidistilling.com/how-to-make-vodka/#fermentingyourmash)
Beer: about 2 weeks (https://www.hoptech.com/pages/homebrewing-questions-and-answers)
Mead: 2-4 weeks (https://meadist.com/making-mead/mead-recipes/hop-head-mead/) (https://meadist.com/making-mead/mead-recipes/home-made-lavender-blackberry-mead-recipe-by-bill-savage/)

OTHER
DIY Yeast Culturing - few days to 2 weeks, and can be done in normal glass jars (https://bootlegbiology.com/diy/capturing-yeast/)
Curdling Milk for Cheese - 10-20 minutes (https://www.thespruceeats.com/how-to-make-homemade-cheese-2215814)
Steeping Gin - 24-48 hours (https://foodanddrink.scotsman.com/drink/beginners-guide-making-gin-home/)
Vinegar - 2 months (https://www.wikihow.com/Make-Your-Own-Vinegar)

I don't think making all these recipes THAT much longer is going to make the game more fun. I'm suggesting streamlining the brewing recipes into three tiers of speed, across a tighter spread of time (1-3 days).

Another oddity is that in the game, fermenting gin mash can be made from homebrew beer and juniper. That seems odd and I could not find any real-life reference to people making gin from beer, other than gin-flavored beer. I did find references to people distilling beer into hard alcohol, but the existing gin recipe in the game is not a distillation, it's just steeping juniper in vodka/whiskey/beer.

**Describe the solution you'd like**  
I'm proposing streamlining the brewing times for these recipes into something like:

Fruit Wine, Mycus Wine ("fruit-based wines"): 1 day
Whiskey, Moonshine, Dandelion Wine, Pine Wine, Rum, Vodka ("distillates and non-fruit-based wines"): 2 days
Beer, Mead: 3 days

Curdling Milk: 1 hour
Yeast Culture: 1 day, change recipe so that you can use glass jars in addition to the glass flask (sterilization already implied by the fact the recipe requires fire)
Gin: 1 day (unchanged), remove beer as an ingredient
Vinegar: 3 days

You could argue that Rum should have a fast recipe with sugar beets (or raw cane sugar if/when that is in the game) and a slow recipe with molasses, but that seems gratuitous and an unnecessary additional recipe.

This does make the super-fast brews take significantly longer but is at least a bit more consistent - right now whiskey/beer/moonshine at 6-9 hours but mead at 5 days seems very odd. The biggest gripe I can see from players who brew is that beer is getting moved from 9 hours to 3 days. If that's a legitimate hassle, this could move to a 2-tier system by making both beer and mead take 2 days.

**Describe alternatives you've considered**  
Keeping as-is, or tweaking on a smaller scale. This seems like a system that doesn't get much attention so it seemed like a better alternative just to revisit the current recipes as a whole.

**Additional context**  
I propose making this change until after the current release is out the door. I'm happy to implement it and have already made several of these changes in my local codebase.

Suggestions and input very welcome, this is my first proposal of any significance.

**Comment by jkraybill** [comment]
Per comments on #37463 and based on some very old Reddit/Discourse comments on the topic, I also propose to reintroduce the culturing of wild yeast using at least 1 of these 3 methods, all 3 if they can be done with a single game recipe and output (pretty sure they can):

https://readynutrition.com/resources/survival-food-series-3-ways-to-naturally-make-yeast_02032011/

This would be similar to the year culture, but not require a flask or yeast, and take a longer time (5 days?)

**Comment by Brian-Otten** [comment]
Having brewing not be like real life brewing always put me off from doing it before, so would love to see it changed to more closely match real life. I'm pretty sure you are correct in that these systems haven't seen attention in a while and could use a solid look.

Reworking the recipes to fit real life should have little controversy, but it will be important to make sure the correct active and idle times are used. Make sure to use the code for leaving stuff to ferment in the background where possible.

**Comment by jkraybill** [comment]
If #37535 is still open when I work on this, I'll plan to resolve that as part of this work.
