### ISSUE TITLE
Pie recipes should require butter.

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#37471]
# Describe the bug
Pie recipes currently require flour, water, and filling. That would make a terrible crust.

# Steps To Reproduce
Go in game and try to bake a pie.
```
"components": [
      [ [ "flour", 30 ] ],
      [ [ "sweet_fruit_like", 8, "LIST" ] ],
      [ [ "sugar", 20 ], [ "syrup", 4 ], [ "beet_syrup", 4 ], [ "molasses", 4 ] ],
      [ [ "water", 1 ], [ "water_clean", 1 ] ]
    ]
```
You won't need butter.

Then go into real life and try to bake a pie.
Enjoy the inedible horror of the butterless crust, you monster.

# Expected behavior
The recipe needs a butter or lard component. Oil is not a sufficient substitute.

# Additional context
I believe this applies to all pie sub-recipes, but I haven't looked.

**Comment by Alapaga** [comment]
I second this, I would consider adding 12/16 units of butter to the recipie of pie, cause that's about half the pack. I also noticed that the butter usage in other recipies is minimal, for exaple cake only requires two units and that is a very small amount. Also, I'm French, so I have that bias going on where I need to put butter in everything.

**Comment by killmepete** [comment]
I'd like to try and tackle this game breaker if I can. Looks like a good first issue :)

**Comment by KorGgenT** [comment]
requirements would be a good thing to use here too

**Comment by Maleclypse** [comment]
Yes, now that butter is no longer a finite resource many recipes should have butter added.

**Comment by RegaliaV** [comment]
It's entirely possible to make pie crust using oil. Maybe it's not as enjoyable to most people, but completely removing the option seems overly limiting when it's a thing people can and do make.

Maybe a separate recipe with the oil crust is the right call if people are opposed to oil being an option along with butter?

**Comment by killmepete** [comment]
I don't see why there would be opposition to oil and butter, seems
consistent with other recipes which let you use an alternative.

**Comment by RarkGrames** [comment]
I think that two different recipes is a good idea to have. What if I want to RP as the fifth horseman of the Apocalypse, riding on my pale horse, burning all the cookbooks I come along to force the remainder of humanity to eat pies with butterless crust, dooming them to eternal torment?

Just kidding... I would never do such a horrible thing. (Or would I? Duh-duh-DUUH)

**Comment by Ezsk** [comment]
How is the calorie at result? maybe terrible than crust.

**Comment by I-am-Erk** [comment]
Apparently some people do make pie crusts with oil. I am not a fan of supporting this kind of moral iniquity in the game, but if someone is that depraved I guess I can't block the PR

**Comment by l29ah** [comment]
I made a pie with sunflower oil just fine IRL.

**Comment by I-am-Erk** [comment]
I think you know how I feel about people like you.

**Comment by Voker57** [comment]
There should be morale modifier based on ingredients used, similar to what is done with vitamins.

**Comment by Eliijahh** [comment]
Can confirm from Italy this supposedly moral iniquity of using oil for pies 🇮🇹
