### ISSUE TITLE
Modding Bionics not possible with either copy-from or override flag

### ISSUE THREAD

**Issue by GennFaol** [CleverRaven/Cataclysm-DDA#37476]
# Describe the bug

It is currently not possible to mod existing bionics using either copy-from or override. Upon loading, the game will complain about missing fields (if using copy-from) or duplicate IDs (if using override).

# Steps To Reproduce

1. Make a mod intended to change something about a bionic included in the game, using the copy-from or override flags.
2. Try to start the game.
3. The game will refuse to start with an error message.

# Expected behavior

The game accepts the modded bionic the same as it would an item, recipe or similar moddable entry.

# Versions and configuration

Issue is independent of OS or game version.

**Comment by Unrepentant-Atheist** [comment]
See more in https://discordapp.com/channels/252365627543519232/365907426270117888/671782920096186378

**Comment by anothersimulacrum** [comment]
Suggested fix: Use `generic_factory` for bionics.
