### ISSUE TITLE
Make reach attacks not care about facing

### ISSUE THREAD

**Issue by Brian-Otten** [CleverRaven/Cataclysm-DDA#37492]
# Is your feature request related to a problem? Please describe.
Reach attacks currently cannot attack true diagonals when using circular distance. with the game usually not taking into account character facing, it makes the game feel very weird when the character can not make reach attacks because enemies approach from diagonals and your character can't face them so he can make a "straight" reach attack.

# Describe the solution you'd like
Reach attacks should be reach attacks in all directions. 

# Describe alternatives you've considered
Let reach weapon players continue to micro during combat to keep enemies in the cardinal directions.

# Additional context
Letting the character attack diagonals simulates having more reach than an unarmed zombie, even if he comes at you diagonally.

Alternatively you could look at the distances involved in a 2 tile reach attack diagonally and see if its a doable distance. 2 tile reach is simulated as ~2.8 meters (~9 feet) in game , rounded down, from the exact corner of one tile to the furthest corner of the other.
Normal spears are about 2.4 (8 foot) long, and can make thrusts at 12 feet (3.65 meter) or more if you extend yourself.

**Comment by Brian-Otten** [comment]
I tried having a look and seeing if i could post a PR resolving this myself but i was not able to figure out how, sadly.

**Comment by JeanLucVanDamme** [comment]
This would be a very welcome improvement.
