### ISSUE TITLE
Rework bladed/blunt polearms

### ISSUE THREAD

**Issue by Brian-Otten** [CleverRaven/Cataclysm-DDA#37501]
# Is your feature request related to a problem? Please describe.
Bladed/blunt pole-arms should be some of the strongest melee weapons available to the survivor, being able to use their leverage and long swings to strike truly devastating blows. However, currently the pole-arms are handled like normal two handed weapons that also have the reach_attack flag.

# Describe the solution you'd like
It would match real life and be quite interesting gameplay wise if we rebalanced the pole-arms for a new niche.
We would make the pole-arms the superior option in damage for the most part (but not in damage/stamina), and remove their ability to make non reach attacks, or somehow give them a weaker attack up close / force unarmed up close.
This would encourage a new style of fighting where you would try to keep zombies at a distance from you so you can maintain your offense, and if they do manage to get close you'd be encouraged to drop your weapon and pull out a sidearm.

Spears should probably not have this function, because spears can be retracted quickly and easily and be stabbed with to full effect. It would be good if the pole-arms with spear tips could have spear attacks up close, versus swing attacks at reach.
# Describe alternatives you've considered
Leave the weapons as is.

# Additional context
If someone knows how to make weapons have different attacks in reach vs up close and could tell me how i would be willing to make this a PR myself, but am not sure how to do that (essential) part of the required work.

#15034 Is a related issue that anothersimulacrum made me aware of.

**Comment by wapcaplet** [comment]
I like the idea of certain polearms being less effective at close range, to simulate being unable to swing them in a full arc, and/or the long handle just getting in the way. I haven’t played with many reach weapons except the naginata and qiang, but those have some pretty remarkable damage and special attacks already, so I dunno that they need buffing much.

Don’t some polearms also have critical attacks like a wide arc damaging 2 enemies? I forget if that applies to reach attacks.

**Comment by c00ya** [comment]
Could this be emulated using the existing style system?

The "force unarmed" style is already available, you'd need to be forcing the "force unarmed" style based on weapon type. A "minimum range" would be need to be implemented though to properly limit its abilities. Any polearm-based styles would also need to be reworked for this approach, but this would open up the avenue of more interesting styles using polearms at close range - I'm thinking special close range attacks using the butt of the polearm and "grappling" styles that would leverage the polearm and wrestle enemies to the ground, stunning them, so you can step back and give them the axe blade to the head.

Just my 2c, I'm thinking of how to recycle existing systems.

**Comment by Brian-Otten** [comment]
@wapcaplet None of the current martial styles work when making reach attacks, sadly.

Force unarmed could be a good way to implement it. As for the style, Fiore di battaglia is pretty much all that minus the butt attack, so should be suitable.

The downside of using such an implementation is that if you are forcing unarmed it will also come out as unarmed damage, which would be too weak for what we are simulating, So you are back to wanting separate damage values for up close and reach attacks.

**Comment by Brian-Otten** [comment]
As for the balance/ amount of damage polearms should do, they should probably be both slower and more damaging than weapons like the longsword, to better emulate real life. The leverage you can apply swinging the blade of a polearm makes a huge difference.
Currently if we compare the glaive

![image](https://user-images.githubusercontent.com/47374323/73524280-14a76600-440d-11ea-8504-40532695adae.png)

To the longsword
![image](https://user-images.githubusercontent.com/47374323/73524308-22f58200-440d-11ea-9396-53624868588d.png)
We can see the longsword is actually delivering much stronger hits than the glaive is.

I would like to implement the downsides of polearms before we make them as strong as they are in real life though, because without them having downsides it would distort the gameplay a bit too much.
