### ISSUE TITLE
Integrated Toolset CBM missing Hand Drill

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [CleverRaven/Cataclysm-DDA#37502]
# Describe the bug

Hand drill is missing from the integrated toolset.

# Steps To Reproduce

1. Have Integrated Toolset CBM
2. Try installing Vehicle Tank 60L into frame

# Expected behavior

To be able to install stuff that needs drilling 2 as tool.

# Screenshots

https://imgur.com/a/uSBonqI

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.D-11709-g9d46c12 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Psychiclysm [psychiclysm],
    Vehicle Additions Pack [blazemod],
    Fallout New England [fallout],
    PKs Rebalancing [PK_REBALANCE],
    Cataclysm++ [Cata++],
    Necromancy [necromancy],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Fujistruct [Graphical_Overmap_Fujistruct],
    Graphical Overmap More Locations [Graphical_Overmap_More_Locations],
    Graphical Overmap Urban Development [Graphical_Overmap_Urban_Development]
]

**Comment by Brian-Otten** [comment]
Please follow/use the form for bug reports when making bug reports.

**Comment by scorpion451** [comment]
I believe this is intentional, if rather frustrating.

I remember a rework ages ago where it was decided that certain tool qualities should be made intentionally inconvenient to access, hence most toolbox-type items lacking drilling capability (even the workshop toolbox, which has several capabilities the integrated toolset lacks.)

**Comment by TechyBen** [comment]
Would an alternate "power tool" CBM be fitting? Like those oversized arms/hands in some cyborg like sci-fis. It would have a power saw and drills, etc. But at the expense of no soldering/fine screwdriver tools etc. Possibility of player not being able to use both when the CBM slots/limits comes into play. Small change for current players who min/max CBMs now?

**Comment by RobertoVGoulart** [comment]
> I believe this is intentional, if rather frustrating.

"Hand Drill" is still listed on the description of the CBM, so the bug is either the lack of the 2 Drilling quality on it or the description.
