### ISSUE TITLE
Canned fruit, canned tomatoes and canned livers not filling the right amounts

### ISSUE THREAD

**Issue by Illgowiththisname** [CleverRaven/Cataclysm-DDA#37504]
# Describe the bug

Canned fruit and canned tomatoes only fill the containers halfway and the canned liver is twice the amount the tin can should be able to contain

# Steps To Reproduce

1. need level 5 or higher cooking, tools with metal sawing 1 or higher, hammering 1 or higher, cutting 1 or higher, food cooking 3 or higher, some form of heat source for cooking, can sealer, canning pot, 3 scrap metal, 3 small opened tins, 2 glass jars, 2 3L glass jars, 30 of a fruit, 8 raw livers, 15 tomatoes and 54 water or clean water
2. Shift + 7 for crafting menu then shift +f search either canned fruit, canned tomato or canned liver (for canned liver only the small tin can version seems weird)
3. craft whichever item you picked.
4. check max amount container could hold vs what is in container.

# Expected behavior

for the livers either make a 4 liver recipe using the small tin can or use the medium sized tin can for the 8 livers since its double the size. for the canned fruit and tomatoes either double the amount put into the container or half the amount of fruit and tomatoes it says the containers can store.

# Screenshots

![food containers](https://user-images.githubusercontent.com/60259456/73356365-1125b900-42ff-11ea-9c97-09064f58995a.png)

# Versions and configuration

  - OS: Windows
    - OS Version: Windows 7 Ultimate
- Game Version: 0.D-11709-g9d46c12 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Monsters [Only_Wildlife]
]

# Additional context

not putting in a save in for this one cause of how messy i made my save checking pretty much every can sealer and canning pot recipe i saw

**Comment by jkraybill** [comment]
Nice catch, thanks @Illgowiththisname! I noticed some other ratio inconsistencies and plan on doing a little project to clean up canning recipes on a larger scale in #37551 .

If you're actively using canning in the game, and have any observations about things you would like to see improved or changed in the future, please leave your input as comments in #37551! I suspect these systems like canning/brewing/smoking don't get a whole lot of use from mainstream players so any feedback from survivalist cooks would help in generating ideas for future changes.
