### ISSUE TITLE
Health monitoring capabilities

### ISSUE THREAD

**Issue by eilaattwood** [CleverRaven/Cataclysm-DDA#37508]
# Is your feature request related to a problem? Please describe.
With new food system implemented and vitamin system mainlined it would be nice to implement some in-game capabilities of monitoring extended health information.

# Describe the solution you'd like
Lab centrifuge and Blood analysis CBM should report character's vitamin and poison levels.
Wearable gear like fitness trackers can provide help in calorie consumption management.
Maybe some portable solution to check vitamins on the go. Like some kind of simple blood test.

# Describe alternatives you've considered
Not critical. Can be left as is.

# Additional context
None

**Comment by scorpion451** [comment]
Definitely a needed feature as all these stats are becoming increasingly important- drives me nuts not having a way to check them.

Fatigue levels might be a good one to add to the list, too.

**Comment by TechyBen** [comment]
Could fatigue be masked as a "heart rate monitor"? An in game/slight IRL idea. I know real life is not quite like that. But if a gameplay mechanic that would need some way to integrate into the lore/world of the game.

**Comment by davidpwbrown** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/36233

**Comment by scorpion451** [comment]
For fatigue, I was thinking more on the lines of a gestalt of things that blood scans can detect. There's no one thing that indicates tiredness, but you can get a general idea of how mentally and physically exhausted someone is by looking at the constellation of factors- lactic acid levels, cortisol levels, changes in various hormones and neurochemicals... basically how badly their body needs a maintenance cycle. X3

**Comment by TechyBen** [comment]
> For fatigue, I was thinking more on the lines of a gestalt of things that blood scans can detect. There's no one thing that indicates tiredness, but you can get a general idea of how mentally and physically exhausted someone is by looking at the constellation of factors- lactic acid levels, cortisol levels, changes in various hormones and neurochemicals... basically how badly their body needs a maintenance cycle. X3

Yeah. IIRC the "dark under your eyes" thing is assumed to be via blood thinning/dehydration etc. So it could be done with a blood test. Just seems a little overkill IMO, when it could be mapped (in game) to something like a smart phone app/fitness tracker (sleep tracking/step counter etc abstracted out to "fatigue readings on the smartphone").
