### ISSUE TITLE
"Arithmetical error" leading to crash

### ISSUE THREAD

**Issue by FeelsBadMatey** [CleverRaven/Cataclysm-DDA#37516]
# Describe the bug

Crash upon starting new character.

# Steps To Reproduce

Make a new character, load in, crash.

# Expected behavior

Possibly related to new build, or conflict between mods.

# Versions and configuration

 - OS: Windows 7
 - Game Version: 0.D-11736-g405d24e
 - Graphics version: Tiles

# Mods loaded: 
Disable NPC needs
Craftable Guns
Pots
Survival tools
Myth replicas
Medieval and Historic classes
Makeshift Items
Modular turrets
Salvaged robots
Hydroponics
More locations
Fuji's more buildings
Beta national guard camp
Mapgen Demo
No railstations
urban development
folding parts
vehice additions
tanks and other
speedydex
stats through skills
classes and scenarios
safe autodoc
sleep deprivation
bionic slots
manual bionic installation
prevent zombie revivication
mundane zombies
fuji military profession
bens gf recipes

# Additional context

As well, I couldn't seem to load build notes, might be related.

The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 0.D-11736-g409d24e
TYPE: Signal
MESSAGE: SIGFPE: Arithmetical error
STACK TRACE:

  #0
    (dbghelp: @0x7c6e26[cataclysm-tiles.exe+0x3c6e26]), 
    (libbacktrace: Z21debug_write_backtraceRSo+0x56@0x7c6e26),
    (libbacktrace: 0x7c6e26    [unknown src]:0    [unknown func]),
  #1
    (dbghelp: @0x79b01f[cataclysm-tiles.exe+0x39b01f]), 
    (libbacktrace: log_crash+0x4af@0x79b01f),
    (libbacktrace: 0x79b01f    [unknown src]:0    [unknown func]),
  #2
    (dbghelp: @0x79bce2[cataclysm-tiles.exe+0x39bce2]), 
    (libbacktrace: signal_handler+0x32@0x79bce2),
    (libbacktrace: 0x79bce2    [unknown src]:0    [unknown func]),
  #3
    (dbghelp: SMPEG_error+0x4b0b1@0x14e1d8d[cataclysm-tiles.exe+0x10e1d8d]), 
    (libbacktrace: gnu_exception_handler+0xed@0x14e1d8d),
    (libbacktrace: 0x14e1d8d    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crt_handler.c:269    _gnu_exception_handler),
  #4
    (dbghelp: _C_specific_handler+0x9c@0x770985c8[ntdll.dll+0x185c8]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #5
    (dbghelp: RtlDecodePointer+0xad@0x770a9d2d[ntdll.dll+0x29d2d]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #6
    (dbghelp: RtlUnwindEx+0xbbf@0x770991cf[ntdll.dll+0x191cf]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #7
    (dbghelp: KiUserExceptionDispatcher+0x2e@0x770d1248[ntdll.dll+0x51248]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #8
    (dbghelp: @0x12eb588[cataclysm-tiles.exe+0xeeb588]), 
    (libbacktrace: ZN10SkillLevel4rustEbi+0x68@0x12eb588),
    (libbacktrace: 0x12eb588    [unknown src]:0    [unknown func]),
  #9
    (dbghelp: @0x6665d5[cataclysm-tiles.exe+0x2665d5]), 
    (libbacktrace: ZN9Character13do_skill_rustEv+0xe5@0x6665d5),
    (libbacktrace: 0x6665d5    [unknown src]:0    [unknown func]),
  #10
    (dbghelp: @0x66d57f[cataclysm-tiles.exe+0x26d57f]), 
    (libbacktrace: ZN9Character11update_bodyEv+0x1f@0x66d57f),
    (libbacktrace: 0x66d57f    [unknown src]:0    [unknown func]),
  #11
    (dbghelp: @0x95473c[cataclysm-tiles.exe+0x55473c]), 
    (libbacktrace: ZN4game7do_turnEv+0x13c@0x95473c),
    (libbacktrace: 0x95473c    [unknown src]:0    [unknown func]),
  #12
    (dbghelp: IMG_LoadWEBP_RW+0x8c935c@0x1e9cedc[cataclysm-tiles.exe+0x1a9cedc]), 
    (libbacktrace: main+0x10fc@0x1e9cedc),
    (libbacktrace: 0x1e9cedc    [unknown src]:0    [unknown func]),
  #13
    (dbghelp: @0x4013ed[cataclysm-tiles.exe+0x13ed]), 
    (libbacktrace: _tmainCRTStartup+0x23d@0x4013ed),
    (libbacktrace: 0x4013ed    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crtexe.c:336    __tmainCRTStartup),
  #14
    (dbghelp: @0x4014fb[cataclysm-tiles.exe+0x14fb]), 
    (libbacktrace: WinMainCRTStartup+0x1b@0x4014fb),
    (libbacktrace: 0x4014fb    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crtexe.c:186    WinMainCRTStartup),
  #15
    (dbghelp: BaseThreadInitThunk+0xd@0x76f7652d[kernel32.dll+0x1652d]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #16
    (dbghelp: RtlUserThreadStart+0x21@0x770ac541[ntdll.dll+0x2c541]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),

**Comment by AMurkin** [comment]
I suppose it's #37281
