### ISSUE TITLE
Give bomb fragments an armor piercing value

### ISSUE THREAD

**Issue by Brian-Otten** [CleverRaven/Cataclysm-DDA#37510]
# Is your feature request related to a problem? Please describe.

Shrapnel grenades are far less powerful than expected against targets wearing any armor.
Some testing will quickly show that the current behavior where grenades produce many small low damage fragments will leave enemies with armor values above 0 far more unharmed than you would expect. zombie soldiers can take 10 military frag grenades from point blank and not die.

# Describe the solution you'd like

Give an armor pierce value to bomb fragments so they are not useless against even lightly armored targets.

# Describe alternatives you've considered
Fragmentation explosives remain weak

Wait for armor values on monsters / players to be reworked so shrapnel that lands on armor can deal blunt damage, and monsters can be hit in places where their armor does not cover.

**Comment by RarkGrames** [comment]
Also, lab turrets have the same thing. Most of the standard military frag grenades do little to no damage to them.

**Comment by CountAlex** [comment]
Let me try to do something about this.

**Comment by ymber** [comment]
This is not a correct approach. The real problem here is monsters not having any kind of armor coverage model. Small fragments being ineffective against armor is intended behavior.

**Comment by CountAlex** [comment]
I'd try to make fragments have relatively low armor penetration values so that they are effective against what would be weak armor and not shred power armor to pieces. If this won't work out, we can always close PR.

**Comment by Brian-Otten** [comment]
Small fragments being weak against any serious armor seems about right, but them being mostly invalidated by doing as little as wearing a leather jacket over a t-shirt seems weird.
And giving them at least some armor pierce value that can be removed/reduced when someone does add a armor coverage model for monsters seems like a good idea to make them usable in the interim.

**Comment by Brian-Otten** [comment]
So i actually found out most of the explosives are working as expected and it's mostly the military frag grenade that was functioning weirdly, and am attempting to fix that in #37585
This issue can probably be closed since fixing that should tide us over until monster armor is reworked.
