### ISSUE TITLE
Cannot siphon from roof-mounted external tank (200l)

### ISSUE THREAD

**Issue by SSpook** [CleverRaven/Cataclysm-DDA#37525]
# Describe the bug
When roof-mounted external tanks are the only kind of tanks with liquid trying to siphon will result in the message "This vehicle has no liquid fuel left to siphon.". When there are other types of tanks with liquids in them you can siphon normally from roof-mounted external tanks.

# Steps To Reproduce

1. Install a roof mounted tank on a vehicle.
2. Siphon all the liquids from the vehicle.
3. Refill the roof-mounted tank with a liquid of your choice.
3. Try to siphon.

# Expected behavior

Expected to be able to siphon.

# Versions and configuration

Game Version: 0.D-11480-gdcdef1e
Graphics version: Tiles
Mods loaded: [dda, aftershock]

**Comment by Unrepentant-Atheist** [comment]
Confirmed
