### ISSUE TITLE
"basement_bionic" error

### ISSUE THREAD

**Issue by araneyl** [CleverRaven/Cataclysm-DDA#37539]
# Describe the bug
On world load or while moving around an error will occur with the following. This seems to only happens with aftershock or desertregion enabled, but there may be others. 

# Steps To Reproduce

1. Create a new world with aftershock.
2. Create a character.
3. Load world.

# Expected behavior
No error.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-11758-gd8e8618 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock]
]

# Additional context

23:31:50.497 ERROR : src/generic_factory.h:384 [int_id<T> generic_factory<T>::convert(const string_id<T>&, const int_id<T>&) const [with T = oter_t]] invalid overmap terrain id "basement_bionic"

**Comment by Night-Pryanik** [comment]
This should be fixed after #37479 and #37527. Please update to the latest version and check if this is still an issue.

**Comment by araneyl** [comment]
This was tested multiple times on the current version, build 10275. ralreegorganon and esotericist (on discord) also confirmed the issue and discussed the fix. It just needs the actual work done.
