### ISSUE TITLE
candle (lit) is not a fire source

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#37537]
- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.D-11601-g30a5718ba6-dirty [64-bit]
- Graphics Version: Curses
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key]
]

**Comment by l29ah** [comment]
Still doesn't work. Repro: 
[2020.01.29.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4135692/2020.01.29.zip)
`e` the nearby stove and see it cannot be lit.

**Comment by ZhilkinSerg** [comment]
#37566 should address that
