### ISSUE TITLE
Bionic lighter can't be used to lit a smoking rack and charcoal kiln.

### ISSUE THREAD

**Issue by eilaattwood** [CleverRaven/Cataclysm-DDA#37543]
# Describe the bug

Finger lighter CBM can't be used to lit up the smoking rack (And charcoal kiln, i believe).

# Steps To Reproduce

1. Have a player with Finger Lighter CBM and enough energy to use it, and no other fire sources.
2. Build smoking rack or charcoal kiln and set it ready to go.
3. Examine it.

# Expected behavior

Smoking rack is lit, bionic energy consumed.

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

 - OS: Windows 7 x64, Linux
 - Game Version: 0.D-11746-g33daec56fa
 - Graphics version: Tiles
 - Mods loaded: [No NPC Needs, Engineering essentials]

# Additional context

None

**Comment by eilaattwood** [comment]
Strange. Just tested it again and it worked. Sorry about that. Closing.

**Comment by ZhilkinSerg** [comment]
Probably you had not enough power?

**Comment by eilaattwood** [comment]
> Probably you had not enough power?

I thought I was full on power. Maybe not.
