### ISSUE TITLE
Tiny or Unassuming characters with Muzzles of any kind have non-existent access to clothing for the 'Mouth' slot without excessive penalties

### ISSUE THREAD

**Issue by Muffindrake** [CleverRaven/Cataclysm-DDA#37553]
# Describe the bug

I had recently done another Tiny/Unassuming character and noticed that all of the Mouth gear that can actually be worn by a tiny muzzled character, which is limited to XL variants of mouth gear, cannot be downsized to fit small characters. This is an issue because the muzzle already locks you out of regular Mouth gear, but if you try to use the XL variant of a given gear piece, you suffer large penalties. The least encumbrance you can currently obtain is _20_ assuming you wear the XL survivor divemask, refit it (which doesn't downsize it) and enable it.

As a side effect, enabling the divemask improves your vision (encumbrance goes from 40 to 20), because mouth and eye encumbrance are incorrectly tied to each other, but that's a matter for another bug report. That's not even a gas mask - the least-encumbrance option for gas masks is at a cool 40 encumbrance (i.e. XL survivor mask).

# Steps To Reproduce

1. Make character with Tiny/Unassuming and any type of Muzzle.
2. Obtain any XL variant of a mask, preferably gas mask.
3. Observe that said equipment can be refitted, if not already made to 'fit', and worn, but can't be downsized to reduce penalties.

# Expected behavior

XL variants of masks should be downsizable. Logically, an XL variant of a mask is still XL in relation to the survivor who makes it. I'm not sure how to feel about goggles of all kinds being resizable.

# Screenshots
![image](https://i.imgur.com/l1lIeBN.png)

# Versions and configuration

- OS: Gentoo Linux x86_64
- Game Version: 0.D-11709-g9d46c1293e
- Graphics Version: Terminal
- Mods loaded: dda, Magiclysm, Garden Pots, Crazy Cataclysm, Bionic Slots

**Comment by Muffindrake** [comment]
In extension, long versions of scarves are also not downsizable, which seems pretty silly.

**Comment by scorpion451** [comment]
I file this under the same heading as the inability to downsize any of the storage items when you already have reduced carrying capacity: basically turns the intended tradeoff penalty into a double-whammy, and in many cases it doesn't make sense that the item couldn't be resized, if just with regard to empty encumbrance.

**Comment by Muffindrake** [comment]
As with the ammunition naming scheme I PR'd earlier, I suggest switching the naming scheme on these masks around as well. How about `survivor mask, muzzled` next to the regular `survivor mask`? Then it'd make more sense to allow downsizing them.

**Comment by Brian-Otten** [comment]
We might not want to make it specifically for the muzzle, because there might be more mouth mutations that need adjusted masks, and having a separate mask for every mutated variant available would bloat the crafting menu too much.

Would be quite interesting if the recipes only showed up if you actually had the relevant mutations though, that would allow for a larger array of personally customized items without bloating the crafting menu.

**Comment by TechyBen** [comment]
Would generalising the resizing be better than making multiple size/shape clothing/masks?
Take away all the xl/mutant recipies for size/shape variation (with exception of unique "tail bow" items that have no "normal" like variants).

Then, any normal clothing that can be "refitted/sized/shaped" would have variations in the resize menu. It would have "adapt for tentacles/small/large/muzzle" and thus 4 or so options for them (or could just be 1 generic "mutant sized", but then I'd expect "tentacles" and XL to use more materials).

This way, the clothing need only have the tag "can be mutant" or "can be mini/mouse/tiny" or "can be tentacles" etc. With either a flat rate % material cost, or a small flag like:
tentacles; rags (8), tin foil (100),

Perhaps descriptions of "you know how to refit this to fit mutations" if it's an item that can be refitted as a hint to players while in the crafting menu? :)

**Comment by scorpion451** [comment]
That'd be a very cool way to do it, opening up the flexibility a lot more. I know quite a bit of the thinking on the blanket "mutation blocking" or "no resizing" thing is often some specific part of the item being conceptually difficult to imagine adjusting for. If armor instead had specific modifications blocked, that would at least mitigate the problem.

The XL variants, meanwhile, could instead be something like "adjustable (insert item)" or "custom (item)", with it accepting more or all of the mutation adjustments.

One of my longstanding and closely related "that just doesn't make sense" things I've wanted to see fixed is that my mouse can craft a given item from scratch, but can't make it in their own size. I can see the argument for not being able to adjust a scavenged suit of power armor to their size, but it's silly that they can't a build a custom backpack that's sized to fit them properly if they're making it from scratch.
