### ISSUE TITLE
Atomic Coffee maker does not make coffee.

### ISSUE THREAD

**Issue by OptimisticNihlist** [CleverRaven/Cataclysm-DDA#37569]
# Is your feature request related to a problem? Please describe.
The Atomic Coffeemaker is useless at the moment, as it lacks the HOTPLATE use action tag. 

In the comments, it states that "It would be nice if this could have a use action to thaw frozen stuff.  It's not hot enough to work as a hotplate." which makes sense, but because there is no THAW use action, this item serves no purpose. In addition, the regular Coffeemaker does have the HOTPLATE use action tag, which makes this make less sense.

# Describe the solution you'd like
In my opinion, the Atomic Coffeemaker either needs to function exactly like the regular coffee maker and allow use as a hotplate, or needs to be obsoleted because it only functions as a kettle at the moment, at least until a new use action for THAW is added.

# Describe alternatives you've considered
Remove the HOTPLATE use action tag from the regular coffeemaker until a THAW use action is implemented.

# Additional context
N/A

**Comment by Muffindrake** [comment]
Huh?

![1580420002](https://user-images.githubusercontent.com/19580030/73492225-8ef5cd00-43b0-11ea-8b1b-e9ebb307820b.png)
![1580420042](https://user-images.githubusercontent.com/19580030/73492276-a59c2400-43b0-11ea-83e9-96eaed1dd62c.png)
![1580420078](https://user-images.githubusercontent.com/19580030/73492313-b77dc700-43b0-11ea-88d3-2fa5b71146ed.png)

The atomic coffee maker has specific exceptions in a few crafting recipes for the simple reason that it would be overpowered to have such an infinite source of hotplate. You can use it in specific recipes, but a resourceless hotplate would be way too strong.

**Comment by OptimisticNihlist** [comment]
🤦

Sorry! I am a moron, and must have missed that.

**Comment by Brian-Otten** [comment]
This issue can probably be closed now.
