### ISSUE TITLE
couldn't parse color: c_grey when trying to view photo from the camera

### ISSUE THREAD

**Issue by eilaattwood** [CleverRaven/Cataclysm-DDA#37562]
# Describe the bug

Error message "couldn't parse color: c_grey" when trying to view photos from the camera

# Steps To Reproduce

1. Make a player with a charged smartphone.
2. Take a selfie
3. Try to view taken photo

# Expected behavior

No error message.

# Screenshots

![Photo_error](https://user-images.githubusercontent.com/28134842/73477972-e3438180-439d-11ea-83b9-6912229f5c26.PNG)

# Versions and configuration

 - OS: WIndows 10 x64
 - Game Version: 0.D-3543-g24f066f
 - Graphics version: Tiles
 - Mods loaded: None

# Additional context
[debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4135637/debug.zip)

**Comment by ZhilkinSerg** [comment]
That's strange - it should be either `light_gray` or `dark_gray`.

**Comment by AMurkin** [comment]
I have a fix.

**Comment by ZhilkinSerg** [comment]
> 
> 
> I have a fix.

Me too :)

**Comment by AMurkin** [comment]
Huh. Mine is darker. :D
