### ISSUE TITLE
ESAPI Plate Carrier Disassembly Issue

### ISSUE THREAD

**Issue by Xanmyral** [CleverRaven/Cataclysm-DDA#37564]
# Describe the bug

Disassembling the ESAPI plate carrier gives back all noted return materials in mint condition regardless of the damage to the ESAPI plate carrier, allowing the player to easily take a broken carrier to a fully fixed carrier in minutes with no tools or skills.

# Steps To Reproduce

1. Kill a soldier zed, take their plate carrier
2. Disassemble the plate carrier (cleaning optional, I didn't clean prior)
3. Note that you get all plates and vest back in mint || condition
4. Clean plates and vest and reassemble (as you can't while they're filthy)

# Expected behavior

Damaged items should give back damaged returns, or no returns at all. I wouldn't expect a \\. ESAPI plate carrier to give me back the vest sometimes, much less working plates.

# Versions and configuration

 - OS: Win 10
 - Game Version: Latest Experimental
 - Graphics version: Tiles
 - Mods loaded: CDDA, No NPC Needs

# Additional context

Not at my computer now so can't give the proper versioning until later

**Comment by shadowsapex** [comment]
It doesn't do so. There's a significant chance of loosing one of the components from disassembling a damaged item. You just got lucky

**Comment by Xanmyral** [comment]
Further review when I was able to get back to my computer did confirm that there is a chance to lose the contents. Disassembled about four of the vests, of the four I lost components from about half of them roughly, the other half dropping their full dissembled contents.

While there might be a point to looking at perhaps making it a bit harder to retrieve working materials from a heavily damaged disassembled, or to have a damaged state be inherited by some of the disassembled components if they could be damaged (in this case the kevlar vest without the plates), that's not the point of this issue so I'll close this as I was incorrect.
