### ISSUE TITLE
the latest 0.D branch compile failed.

### ISSUE THREAD

**Issue by Chillbon** [CleverRaven/Cataclysm-DDA#37579]
# Describe the bug

make NATIVE=osx OSX_MIN=10.12 RELEASE=1 LOCALIZE=1 MACPORTS=1 CLANG=1 LANGUAGES="zh_CN"
/bin/sh: astyle: command not found
#define VERSION "0.D-1-ga3ec4f0470-dirty"
Cannot run an astyle check, your system either does not have astyle, or it is too old.
clang++ -ffast-math -Os  -Wall -Wextra    -fsigned-char -stdlib=libc++ -Werror -std=c++11 -MMD -MP -mmacosx-version-min=10.12 -I/usr/local/Cellar/gettext/0.20.1/include -I/usr/local/prog/ncurses_v6.1/include -Itools/format -Isrc tools/format/format.cpp src/json.cpp -o tools/format/json_formatter.cgi
Unformatted data/core/tips.json
...
Unformatted data/help/texts.json
clang++  -DRELEASE -DMACOSX -DGIT_VERSION -DBACKTRACE -DLOCALIZE -ffast-math -Os  -Wall -Wextra    -fsigned-char -stdlib=libc++ -Werror -std=c++11 -MMD -MP -mmacosx-version-min=10.12 -I/usr/local/Cellar/gettext/0.20.1/include -I/usr/local/prog/ncurses_v6.1/include -c src/action.cpp -o obj/action.o
In file included from src/action.cpp:23:
In file included from src/vehicle.h:13:
src/clzones.h:245:23: error: explicitly defaulted move assignment operator is implicitly deleted [-Werror,-Wdefaulted-function-deleted]
        zone_manager &operator=( zone_manager && ) = default;
                      ^
src/clzones.h:221:19: note: move assignment operator of 'zone_manager' is implicitly deleted because field 'MAX_DISTANCE' is of const-qualified type
      'const int'
        const int MAX_DISTANCE = 10;
                  ^
src/clzones.h:246:23: error: explicitly defaulted copy assignment operator is implicitly deleted [-Werror,-Wdefaulted-function-deleted]
        zone_manager &operator=( const zone_manager & ) = default;
                      ^
src/clzones.h:221:19: note: copy assignment operator of 'zone_manager' is implicitly deleted because field 'MAX_DISTANCE' is of const-qualified type
      'const int'
        const int MAX_DISTANCE = 10;
                  ^
2 errors generated.
make: *** [obj/action.o] Error 1

in the master, I can compile successful.

**Comment by Chillbon** [comment]
clang++ --version                                                                                       ~/Code/github/game/Cataclysm-DDA
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin19.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by ZhilkinSerg** [comment]
Try compiling latest master and see if there is same error.

**Comment by Chillbon** [comment]
I build and run successful in the master, with the same make command.

**Comment by Chillbon** [comment]
and there was the same error with the CLANG=0 flag.

c++  -DRELEASE -DMACOSX -DGIT_VERSION -DBACKTRACE -DLOCALIZE -ffast-math -Os  -Wall -Wextra    -fsigned-char -Werror -std=c++11 -MMD -MP -mmacosx-version-min=10.12 -I/usr/local/Cellar/gettext/0.20.1/include -I/usr/local/prog/ncurses_v6.1/include -I/usr/local/include/lua -DLUA -c src/action.cpp -o obj/action.o
In file included from src/action.cpp:23:
In file included from src/vehicle.h:13:
src/clzones.h:245:23: error: explicitly defaulted move assignment operator is implicitly deleted [-Werror,-Wdefaulted-function-deleted]
        zone_manager &operator=( zone_manager && ) = default;
                      ^
src/clzones.h:221:19: note: move assignment operator of 'zone_manager' is implicitly deleted because field 'MAX_DISTANCE' is of const-qualified type
      'const int'
        const int MAX_DISTANCE = 10;
                  ^
src/clzones.h:246:23: error: explicitly defaulted copy assignment operator is implicitly deleted [-Werror,-Wdefaulted-function-deleted]
        zone_manager &operator=( const zone_manager & ) = default;
                      ^
src/clzones.h:221:19: note: copy assignment operator of 'zone_manager' is implicitly deleted because field 'MAX_DISTANCE' is of const-qualified type
      'const int'
        const int MAX_DISTANCE = 10;
                  ^
2 errors generated.
make: *** [obj/action.o] Error 1

**Comment by ZhilkinSerg** [comment]
We do not backport any changes to previous stable versions, so you will probably need to disable `-Wdefaulted-function-deleted` flag when compiling `0.D`.

**Comment by Chillbon** [comment]
in the master, the compile command actually was below:
clang++  -DRELEASE -DMACOSX -DGIT_VERSION -DBACKTRACE -DLOCALIZE -ffast-math -Os  -Werror -Wall -Wextra -Wmissing-declarations -Wold-style-cast -Woverloaded-virtual -Wsuggest-override -Wno-unknown-warning-option -Wpedantic    -fsigned-char -stdlib=libc++  -std=c++14 -MMD -MP -mmacosx-version-min=10.12 -I/usr/local/Cellar/gettext/0.20.1/include -I/usr/local/prog/ncurses_v6.1/include/ncursesw -c src/action.cpp -o obj/action.o

and in the 0.D was:
clang++  -DRELEASE -DMACOSX -DGIT_VERSION -DBACKTRACE -DLOCALIZE -ffast-math -Os  -Wall -Wextra    -fsigned-char -stdlib=libc++ -Werror -std=c++11 -MMD -MP -mmacosx-version-min=10.12 -I/usr/local/Cellar/gettext/0.20.1/include -I/usr/local/prog/ncurses_v6.1/include -c src/action.cpp -o obj/action.o

can I use the master's Makefile to build the 0.D?

**Comment by anothersimulacrum** [comment]
The issue is probably clang version.
I believe that though Mac offers the gcc, behind the scenes it's just llvm, the same as clang, not actually the gcc.

**Comment by ZhilkinSerg** [comment]
> can I use the master's Makefile to build the 0.D?

Yeah, probably.
