### ISSUE TITLE
"Tried to add a duplicate entry" when eating.

### ISSUE THREAD

**Issue by Kelenius** [CleverRaven/Cataclysm-DDA#37583]
# Describe the bug

When you eat something, an error occurs.

# Steps To Reproduce

1. Stand next to a pile of food.
2. Press 'E'.
3. Eat something.

# Screenshots

![image](https://user-images.githubusercontent.com/6681708/73528271-a3c07800-4425-11ea-94ef-3fda4f80b289.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-11796-g7a0ad59 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Garden Pots [growable-pots],
    Generic Guns [generic_guns],
    Hydroponics [hydroponics],
    Folding Parts pack [deoxymod],
    No Fungal Monsters [No_Fungi],
    INT Based Learning [intbasedlearning],
    SpeedyDex [speedydex],
    Disable NPC Needs [no_npc_food]
]

# Additional context

[Estelline.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4138492/Estelline.zip)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4138512/debug.log)

 DEBUG    : Tried to add a duplicate entry.

 FUNCTION : void inventory_column::add_entry(const inventory_entry&)
 FILE     : src/inventory_ui.cpp
 LINE     : 696

**Comment by Kelenius** [comment]
This is apparently related to the hip flasks, because dropping them on the food tile makes the error disappear.

**Comment by davidpwbrown** [comment]
Its happened with me a few times, eating from the floor, direclty from a vehicle cargo part, and from a worn canteen, so not specific.

**Comment by rickyrich88** [comment]
This happened to me when I craft food while holding and then eat it right after. But if I drop it and eat it, the error disappears.

**Comment by Karthas077** [comment]
This just occurred to me while trying to drink from a canteen on a counter, while wearing a canteen, with additional canteens on the counter. Picking up the canteen I was drinking from made the message go away until the last sip, when it showed up again. Can reproduce it reliably with my current save.

**Comment by KorGgenT** [comment]
I loaded up the save on master and haven't been able to get the debug message to appear.

**Comment by codemime** [comment]
Did you use the same set of mods? I see no merged PR that might have fixed it.

**Comment by KorGgenT** [comment]
yeah, i just loaded up the save file in the zip, it loads up the mods attached. didn't seem to have any mods that aren't in repo either

**Comment by Karthas077** [comment]
Here's my save which does it for me. Drinking the hot water in the canteen on the counter does it.

[Canteen.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4189700/Canteen.zip)

**Comment by KorGgenT** [comment]
well here's the call stack. i'm still scratching my head over it though. the save definitely reproduces it.
![image](https://user-images.githubusercontent.com/30208401/74580776-c39f8200-4f75-11ea-97fd-22aab8802c29.png)
