### ISSUE TITLE
Precision solderer CBM from Aftershock can't be used to craft CBMs

### ISSUE THREAD

**Issue by eilaattwood** [CleverRaven/Cataclysm-DDA#37588]
# Describe the bug

Fake item provided by Aftershock Precision solderers CBM leads to craft failure just after the start due to 'You no longer have a none and can't continue crafting', leaving player with 'in progress' item on 0% completed

Maybe other recipes using fake_item are also broken.
# Steps To Reproduce

1. Create a world with Aftershock
2. Create player with Precision solderers CBM installed and provide him with skills, recipes and ingridients to craft CBMs.
3. Try to craft any CBM from Aftershock (that require precision solderers)

# Expected behavior

Craft completes successfully.

# Screenshots

**If applicable**, add screenshots to help explain your problem.
![Craft_error](https://user-images.githubusercontent.com/28134842/73536471-a2e01400-442e-11ea-8c64-75f1701ec839.png)

# Versions and configuration

 - OS: Linux Mint x64
 - Game Version: 0.D-11798-g1eb07c7d21-dirty
 - Graphics version: Tiles
 - Mods loaded: Aftershock

# Additional context

When you spawn in precision solderer fake item as an actual item you CAN craft.

**Comment by Maleclypse** [comment]
This is a known error that hasn't been successfully fixed yet.  Current suggested fixes include spawning in a `none` object and you discovered a new way by spawning in the fake item.   Any suggestions welcome? Strangely having the integrated toolset and the precision solders does work if I remember correctly.
