### ISSUE TITLE
player positional bug when re-entering a unloaded vehicle

### ISSUE THREAD

**Issue by DaAngus** [CleverRaven/Cataclysm-DDA#37591]
# Describe the bug
If the player loads a bike while on the seat, leaves the seat, unloads the bike and moves on the seat
`debugmsg( "map::board_vehicle: passenger (%s) is already there",`

# Steps To Reproduce

Drive you bike to the bike rack. Stop driving. Load the Vehicle. leave the vehicle and unload it. reenter the vehicle.

# Expected behavior

There should not be any passenger on a loaded vehicle. Its just some pipes and strings.
If we get pulled over we are done

Clear all tags for passengers or prevent loading a vehicle while inside the *loaded* vehicle.
If its to general with "while inside a vehicle" a player cant load while, for example, in the doorframe of the main vehicle. 

# Versions and configuration
- OS: Linux
    - OS Version: Arch
- Game Version: 0.D-11791-g2c159093e7-dirty [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

 DEBUG    : map::board_vehicle: passenger (Jimmy 'Gentle' Nash) is already there

 FUNCTION : void map::board_vehicle(const tripoint &, player *)
 FILE     : src/map.cpp
 LINE     : 958

something something vehicle.cpp line 2368?

**Comment by kevingranade** [comment]
I agree with preventing loading whilecstanding on the vehicle to be loaded.

**Comment by kevingranade** [comment]
It looks like the place to address this is in vehicle_use.cpp:1738, vehicle::use_bike_rack()

The logic to do so escapes me at the moment though.

**Comment by irwiss** [comment]
This is done in https://github.com/CleverRaven/Cataclysm-DDA/commit/4b86beb090377b3d64991a4251fb2032458c2fb1
