### ISSUE TITLE
Diving and Surfacing no longer functioning

### ISSUE THREAD

**Issue by FluffyMagicalUnicorn** [CleverRaven/Cataclysm-DDA#37590]
# Describe the bug

You can't surface or go underwater.  If you get pushed underwater, say by the Zombie Hulk on the Island Prison scenario,,trying to surface gives you  a message that you 'need walls to brace against'.

# Steps To Reproduce
Try to go underwater. Or try to get out of it.

# Expected behavior

You should be able to dive or surface

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-11809-g78e6e40 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion]
]

**Comment by curstwist** [comment]
I tried this in build 10278 also and it isn't working.  I know it worked about 2 weeks ago.

**Comment by Night-Pryanik** [comment]
I guess #37499 is the culprit.
