### ISSUE TITLE
Should electric zombies be dealing HP damage?

### ISSUE THREAD

**Issue by Brian-Otten** [CleverRaven/Cataclysm-DDA#37603]
# Is your feature request related to a problem? Please describe.
Currently getting zapped by the shockwave attack from electric zombies causes your character a lot of pain, which is the main threat, but it also gives you minor hp damage over your entire body.

I think any amount of electric damage that would cause physical injuries that need treatment would almost certainly be so debilitating your character would essentially react as if being tazed, and drop like a sack of potatoes.

# Describe the solution you'd like

Focus on the pain causing effect of the electricity, doubling down on it if needed to keep shocker zombies threatening.

But remove the HP scratch damage done to the entire body. This is not usually a cause of death or a major factor in your demise, but is a constant, extremely hard to avoid, source of small wounds that need treatment, which ends up requiring a lot of player time. 

# Describe alternatives you've considered
Alternatively we could consider having the damage be more focused onto 1 limb rather than all limbs receiving a small amount of damage, to reduce the amount of player input needed to treat the wound.

**Comment by Illgowiththisname** [comment]
did some random calculations based on what i read about how much electrical charge was needed for a shocker zombie to fire the shock attack at you and the only thing that mentioned electricity jumping from one thing to another said it takes 30,000 volts for a centimeter or 75,000 volts an inch and i calculated one tile as 1 meter cause measured the size of my door and ya came up as 98cm with frame so 1 meter is good enough for me also the shock zombie seems to be able to fire its shock attack at 12 tiles away or 12 meters so 30k volts * 100 to turn them into meters * 12 gave me 36000000 so 36 million volts is needed to fire that shock attack at you too bad we have no idea what the amps are in it it can take 0.1 or 0.2 amps to kill you meaning at 0.1 the ohms resistance would need to be anywhere below 360 million R  to cause a fatal shock from that.

Also here's me randomly finding out how close the shocker needs to be to fire its bolt
![shocking](https://user-images.githubusercontent.com/60259456/73587207-f8dfb500-451d-11ea-8489-7d2fbc3b92b8.png)

**Comment by 8street** [comment]
An electrical discharge also causes burns. Also if it is a direct current, then also electrolysis of blood. I vote to leave the damage to the player's hp.

**Comment by Qrox** [comment]
> 36 million volts

Alternatively, a shocker zombie can release a cloud of plasma between it and the player so the electricity can pass through under relatively low voltage.

**Comment by Malorn-Deslor** [comment]
The plasma makes sense, especially given the trail of 'electricity' that is left behind when the shocker fires off an attack. Equally, a certain amount of damage is understandable not just from burns or blood issues, but muscles contracting too strongly and tearing themselves.

Gameplay wise, shocker damage being 'all-over' makes them very different from normal zombies, and that's a good thing. But perhaps the amount of damage might be off? Shockers are already very strong zombies due to the crippling pain they inflict and their ability to attack at range. They also don't 'miss' very often due to the large AoE. 

But I wouldn't say removing damage from them is really logical, and it also has one real gameplay risk. A player could, in theory, be fighting ONLY a shocker. Can your character die of pain? I don't think they can, which means you could end up 'pain-locked' for eternity as the shocker keeps attacking you and never actually harming you. That sounds hilarious once, but as a gameplay mechanic is probably bad.

**Comment by eilaattwood** [comment]
> 36 million volts

Which in real life will go directly to the ground at the shocker's feet, burning it with the step voltage :D

**Comment by Jovus** [comment]
Is the Zapped condition not C:DDA's implementation of what happens when someone gets tased? It sets dex to zero and gives a huge malus to speed.

**Comment by Brian-Otten** [comment]
I think it's somewhat trying to act like being tased right now, but without actually giving the full effects of being tased. Currently suffering the shock of the attack is indeed nasty, but still nowhere close to the almost guaranteed death sentence being tased would be.

**Comment by Brian-Otten** [comment]
@Malorn-Deslor There should be no risk of being painlocked since shocker zombies still have a normal (but admittedly weak) melee attack, and they will happily come over to kill you if you are truly stunlocked.

**Comment by TechyBen** [comment]
> > 36 million volts
> 
> Alternatively, a shocker zombie can release a cloud of plasma between it and the player so the electricity can pass through under relatively low voltage.

Read my mind. Current ideas in testing IRL fire tiny wires (dart etc with coil behind) and then power the wire and turn it into plasma or just use it to carry the charge (as a taser would).

Would having 2 levels of attack be worth it for some balancing? Normal shoker = near no damage from ranged shock, then brute/large shocker damage from ranged shock. Both do damage with melee shocks.
