### ISSUE TITLE
uninstalling destroyed (XX) minigun from gunship yields an intact minigun

### ISSUE THREAD

**Issue by misterprimus** [CleverRaven/Cataclysm-DDA#37618]
# Describe the bug

Uninstalling destroyed (XX) minigun from gunship yields an intact minigun

# Steps To Reproduce

1. Find a downed gunship with a destroyed (XX) condition minigun.
2. Remove it.
3. (optional) Reinstall it.

# Expected behavior

Minigun item should spawn in a condition that correlates to the condition of the vehicle structure. In this case, an XX condition vehicle structure minigun should be removed as an XX condition minigun or perhaps even scrap metal.

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

 - OS: Win7x64
 - Game Version: 0.D-11822-ged3d6dc
 - Graphics version: [Tiles]
 - Mods loaded: none

# Additional context

**Comment by misterprimus** [comment]
The problem appears to be the "breaks_into" sections of the turret.json file. Essentially the code says you should get an intact version of the broken gun that you just removed "sometimes (50/50)." This does not follow the general logic applied to other vehicle parts where uninstalling them always yields the RAW MATERIALS (scrap metal). I'm not sure if this is an oversight or intentional, but it seems to me that uninstalling a BROKEN gun should ALWAYS yield "scrap metal" or something of the sort, NEVER a functional gun. Seems to be an easy fix - I'd just need to change all the "breaks into" in turret.json to "scrap metal" or whatever, but wanted to verify there was no reason why this was done like this (if it was intentional for some reason I'm not seeing).
[broken gun.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4142224/broken.gun.zip)

**Comment by Brian-Otten** [comment]
I can't think of any reason that would be intentional, if you could fix it to give scrap metal that would be great.

**Comment by eilaattwood** [comment]
> 
> 
> The problem appears to be the "breaks_into" sections of the turret.json file. Essentially the code says you should get an intact version of the broken gun that you just removed "sometimes (50/50)." This does not follow the general logic applied to other destroyed (XX) vehicle parts where uninstalling them always yields the RAW MATERIALS (scrap metal). I'm not sure if this is an oversight or intentional, but it seems to me that uninstalling a BROKEN gun should ALWAYS yield "scrap metal" or something of the sort, NEVER a functional gun. Seems to be an easy fix - I'd just need to change all the "breaks into" in turret.json to "scrap metal" or whatever, but wanted to verify there was no reason why this was done like this (if it was intentional for some reason I'm not seeing).

Maybe It's something about breaking the turrent mount or a frame, that should result in more or less intact gun dropping from it?

**Comment by misterprimus** [comment]
> > The problem appears to be the "breaks_into" sections of the turret.json file. Essentially the code says you should get an intact version of the broken gun that you just removed "sometimes (50/50)." This does not follow the general logic applied to other destroyed (XX) vehicle parts where uninstalling them always yields the RAW MATERIALS (scrap metal). I'm not sure if this is an oversight or intentional, but it seems to me that uninstalling a BROKEN gun should ALWAYS yield "scrap metal" or something of the sort, NEVER a functional gun. Seems to be an easy fix - I'd just need to change all the "breaks into" in turret.json to "scrap metal" or whatever, but wanted to verify there was no reason why this was done like this (if it was intentional for some reason I'm not seeing).
> 
> Maybe It's something about breaking the turrent mount or a frame, that should result in more or less intact gun dropping from it?

Possibly, but in all the smashing I've done, the gun ALWAYS broke before the turret took any damage even if the turret was almost destroyed and the gun was brand new when I started bashing.
