### ISSUE TITLE
Cant sheath a carving knife

### ISSUE THREAD

**Issue by NyarlathotepZERO** [CleverRaven/Cataclysm-DDA#37610]
# Describe the bug

Cant sheathe a simple carving knife, but can sheathe other unique shaped blades (eg:meat cleaver)

# Steps To Reproduce

Stand over a pile of knives and use 'sheath' from [a]ction command whilst wearing a sheath

# Expected behavior

Expected to see the option to sheathe

# Screenshots

**not applicable**

# Versions and configuration

0.D-11748-g36402aa 
build 10274

# Additional context

**not applicable**

**Comment by ZhilkinSerg** [comment]
It's all in the interface - just look at the items. Sheath takes items with minimum volume of 250 ml, carving knife has volume of 200 ml.

![image](https://user-images.githubusercontent.com/16213433/73587808-60234800-44d1-11ea-99c7-4a213c899386.png)

**Comment by NyarlathotepZERO** [comment]
> It's all in the interface - just look at the items. Sheath takes items with minimum volume of 250 ml, carving knife has volume of 200 ml.
> 
> ![image](https://user-images.githubusercontent.com/16213433/73587808-60234800-44d1-11ea-99c7-4a213c899386.png)

Why does it allow a meat cleaver which weighs 300g then ? (as opposed to the 250g carving knife ?)
