### ISSUE TITLE
No tool available with Screw Driving 2

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [CleverRaven/Cataclysm-DDA#37624]
Screwdriving 2 is missing a tool. It used to be the screw driver set.

# Steps To Reproduce

Reproduce what? 

# Expected behavior

Have a tool with screwdriving 2.

# Screenshots
https://i.imgur.com/GFJkAM5.png

**Comment by ZhilkinSerg** [comment]
There are no recipes with such requirement.
