### ISSUE TITLE
reinstate "blueprint_autocalc"

### ISSUE THREAD

**Issue by curstwist** [CleverRaven/Cataclysm-DDA#37642]
# Is your feature request related to a problem? Please describe.

#37470 removed the use of `blueprint_autocalc` in favor of adding components to the recipes for improved performance.  This change impacts content additions for faction camps by increasing the 'entry' skill requirement and will increase the amount of work to both create and maintain these features.  

# Describe the solution you'd like
I'm happy to wait until `blueprint_autocalc` can be improved for performance before reintroducing it.

# Describe alternatives you've considered
Not adding more faction camps.
Not testing component requirements as I build maps, or having a toggle option to turn them off as needed.
Setting up an environment to run the unit test and get the output to add, or, figuring out how to use the .py script to generate the components as I work on the maps.

# Additional context
Autocalc was a huge boon to creating faction camps and expansions. 

Some of the ways I rely on it:

- It allows me to easily and quickly add new recipe variations without doing construction cost calculations, or using an outside application to make those calculations.

- Quick testing in game for construction times, costs so I can adjust recipes to fit into manageable chunks for players.

- Making `blueprint_autocalc` false turned off all construction requirements for debug testing.

- When testing, the lack of construction requirements in the build menu pointed out that you have messed up your json entry. 

If motivated, I can switch to using a .py script as I write my json but this will increase the entry requirement for new contributors.  

It will increase the amount of time it takes to make these maps, adjust them and give them the amount of testing I usually do.

**Comment by scorpion451** [comment]
I for one would happily wait an extra few seconds on recipe loading to avoid unnecessary hurdles to content creation.

**Comment by I-am-Erk** [comment]
Yes, this isn't really a feature that can be turned off for optimization.

I'm okay with leaving it off for stable, since we're in content freeze, but it needs to be reverted as soon as we're contributing content again

**Comment by ZhilkinSerg** [comment]
> 
> 
> I for one would happily wait an extra few seconds on recipe loading to avoid unnecessary hurdles to content creation.

It is not just a few seconds - Android devices can hang indefinitely.

**Comment by Aivean** [comment]
Seems to be addressed by #43268
