### ISSUE TITLE
Full butchery of heavy corpses should look for nearby tools instead of requiring them in the inventory

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#37658]
# Is your feature request related to a problem? Please describe.
Every time i need to do a full butchery of a big corpse, i need to take a long rope and a stone adze, then put them back after i've butchered all the corpses. If i forget to do this and dump them in my loot pile, i have to walk to it and back at the next time i need to butcher corpses. Full butchering takes 30+ minutes so it's safe to assume the player has time to pick an item from a nearby tile and put it back like it does with 30s crafting routines.

**Comment by JeanLucVanDamme** [comment]
And if you did this in real life, the objects would be outside of your inventory as you used them. Much like a box of detergent while doing laundry.

**Comment by Saicchi** [comment]
Butchering already looks for the tools in the player crafting radius.
I think it was #42372 who fixed this.

**Comment by KorGgenT** [comment]
This was implemented.
