### ISSUE TITLE
Weapon dropping for seemingly no reason.

### ISSUE THREAD

**Issue by araneyl** [CleverRaven/Cataclysm-DDA#37689]
# Describe the bug

While fighting, or possibly other actions, wielded weapon drops to the ground without apparent cause.

# Steps To Reproduce

 Currently unknown. 

1.  Load the below save.
2.  Turn off Dangerous Pickups. (this may not be necessary)
3.  Attempt to melee attack the nearby zombies.
4.  Repeat attacks until the wielded weapon drops to the ground, this may take 2-5 attacks or may happen on the first. 

# Expected behavior

In theory, you shouldn't randomly drop your weapon without at least a message of why.

# Screenshots
-

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-11912-geccc543 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
[test.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4151659/test.zip)

Several possible ideas were tested to cause the issue in an attempt to find a repeatable action that would show the bug. The legs were broken, strength and dexterity were lowered, alcohol was used to get the character drunk, debug added in the martial art, as well as debugging in items to cause either overweight or overvolume; all as possible causes. I don't know what combination, if any, actually caused the bug to become repeatable. 
I can say, the bug seemed to not exist until I removed debug immunity. The drop doesn't seem to be connected to attacking, being hit, missing, being missed, it seems to just fire randomly but I can't be sure.

**Comment by Brian-Otten** [comment]
Just to check, were you using a metal weapon and near any zombie technicians with their "magnet pull disarm" ability? That attack isn't actually very obvious when it happens (it probably should be changed so it is).

**Comment by Illgowiththisname** [comment]
Hi there, had a look why he drops the knuckles and its always when he gets attacked on either of his legs as i think unarmed weps increase kick related damage and you drop wielded stuff if your arms break so same might go for unarmed weps and legs but ya its weird.
also have some screenshots of the messages when he drops the knuckles
![knucks 1](https://user-images.githubusercontent.com/60259456/73743439-67897080-47b3-11ea-8645-786f38e2d83c.png)
![knucks 2](https://user-images.githubusercontent.com/60259456/73743444-69ebca80-47b3-11ea-9145-105e417df2eb.png)
![knucks 3](https://user-images.githubusercontent.com/60259456/73743449-6d7f5180-47b3-11ea-9168-96beb5c04222.png)

**Comment by araneyl** [comment]
@Brian-Otten no techs, when it happens the weapon drops into the tile you're standing in. its not pulled out of your hands and flown across the screen; plus, there is a message to that effect in the log. here its just a message 'tumbles to the sidewalk' as the above shows. (sorry i should have ss'd it myself when i did the PR >< )

**Comment by Zireael07** [comment]
Does it always coincide with clothes being damaged/destroyed?

**Comment by araneyl** [comment]
No, thats just because of the test character in that world. I tested the drop a few times, which got the character attacked and damaged his clothes. Then made a hard save to post here.
