### ISSUE TITLE
wield moves are incorrectly reported

### ISSUE THREAD

**Issue by araneyl** [CleverRaven/Cataclysm-DDA#37687]
# Describe the bug
Unsure if this is a bug, still looking for possible explainations.

When using 'w'ield to wield a weapon, the far right of the screen shows a number of moves to wield said weapons. When pressing 'enter' to wield the weapon, the report of moves taken by last action (top right of screen) shows a much higher number.

# Steps To Reproduce

1.  Have weapon in inventory
2.  Use 'w' to open wield menu
3.  Look at 'moves' on the far right menu
4.  Press 'enter' to perform the wield action
5.  Compare actual moves needed to wield (top right of screen) against reported moves to wield weapons from step 3.

# Expected behavior

Reported moves to wield should be the actual moves needed to wield.

# Screenshots
![1](https://user-images.githubusercontent.com/57279495/73712162-45222500-46d7-11ea-900a-03be13eaaadc.png)
![2](https://user-images.githubusercontent.com/57279495/73712165-46ebe880-46d7-11ea-8bd6-aec0a6e27a90.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-11796-g7a0ad59 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

As tested by me on a slightly old version, however it is confirmed by multiple people to occur on the current version. I can update and test but it will show the same thing. 

Is it possible that there is something else (intended) going on that I (those of us from vorm's stream) don't know about?

**Comment by KorGgenT** [comment]
i could be wrong, but isn't that column actually telling you "number of moves to attack with this weapon"?

**Comment by araneyl** [comment]
that was brought up as a possible explanation, but no one knew for sure. if you can say with certainty that is true then we can remove this issue.

**Comment by Brian-Otten** [comment]
I'm almost certain it's moves to attack with the weapon. it's used for comparing your melee weapons to see which is best at a glance. 

I have however seen some weirdness in movecosts when drawing/storing in sheaths that left me confused that could be examined some. And some indication of moves to wield from backpack would be nice to have somewhere.

**Comment by Illgowiththisname** [comment]
uhh i think theyre actually right about how the moves shown are wrong the moves per attack of the stone knife i have is 76 while it said 93 with the wielding thing. also note my version is a few days out of date but it still gives the same numbers as theirs

![image](https://user-images.githubusercontent.com/60259456/73744469-b46e4680-47b5-11ea-98b4-1c1194e0f1cb.png)

sooo i guess someones got some fixing to do XD

**Comment by Brian-Otten** [comment]
Moves per attack can be modified by stats/hand encumbrance, but it only shows the modified stats if your melee skill is high enough (2 IIRC)

![image](https://user-images.githubusercontent.com/47374323/73747190-38ddac80-4757-11ea-80bd-1224a391fde1.png)

![image](https://user-images.githubusercontent.com/47374323/73747212-43984180-4757-11ea-9c1f-6c9c46a44106.png)

Weirdly it shows the moves to attack as modified by your stats/encumbrance, but it shows the damage before stats modifiers. (note this is my debug character with 100 strength, thus the weird values)

**Comment by araneyl** [comment]
So it would seem this is a case of the UI not being 100% clear about what its telling us? Is this an opportunity to improve the UI? 
Perhaps make it show the move costs of performing the actions you're about to take rather than after the fact (once a predator has had a chance to leap on you because you didn't know exactly how much time you're going to spend performing X task).
I'm not saying that showing moves to perform an attack isn't a useful piece of information, or that the modified (by skills/stats) is bad. In fact I like both of them. In hindsight, it seems we all should have realized what the UI was showing us; but perhaps this is a chance to make the UI a little better?

**Comment by Brian-Otten** [comment]
Sounds like a plan, probably time to close this issue and open a "show moves required to wield weapon in UI"  issue.

**Comment by araneyl** [comment]
Will do. I'd like to put some thought into the issue before I make it.

**Comment by Fracture64** [comment]
I think issue is what name MOVES is ambiguous because it's not obvious what it's truncated "Moves per attack". Maybe rename it to something like SPEED?

And since a lot of people thought MOVES means time to wield there is need for another column called WIELD to show time to wield?
