### ISSUE TITLE
Integrated toolset missing 'Drill' 

### ISSUE THREAD

**Issue by vlad1492** [CleverRaven/Cataclysm-DDA#37695]
# Describe the bug

Integrated toolset missing 'Drill' quality 
Can't mount a fuel tank without it now. 

# Steps To Reproduce

Start as a Bionic Prepper and try to add a fuel tank to a vehicle with your built-in tools

# Expected behavior

Should be able to. Can't.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-11543-g3e11834 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    More Survival Tools [More_Survival_Tools],
    Makeshift Items Mod [makeshift],
    Icecoon's Arsenal [ew_pack],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    PKs Rebalancing [PK_REBALANCE],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Arcana and Magic Items [Arcana],
    Bionic Slots [cbm_slots],
    Fuji's Military Profession Pack [fuji_mpp],
    Manual Bionic Installation [manualbionicinstall],
    Safe Autodoc [safeautodoc],
    Sleep Deprivation [sleepdeprivation],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Aftershock [aftershock],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs],
    Roadheader and other mining vehicles [Heavy miners],
    Classes and Scenarios Mod [more_classes_scenarios],
    Classic Roguelike Classes [RL_Classes],
    Cataclysm++ [Cata++],
    Urban Development [Urban_Development],
    Misscellaneous Magiclysm Expansios [demon_spider_a],
    INT Based Learning [intbasedlearning]
]

**Comment by Brian-Otten** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/37521
 Update your game and this is fixed. this issue can probably be closed.
