### ISSUE TITLE
Arcana - Wyrmskin Armor should be 'Very Fancy'

### ISSUE THREAD

**Issue by vlad1492** [CleverRaven/Cataclysm-DDA#37694]
# Is your feature request related to a problem? Please describe.
Wyrmskin armor is described as 'well decorated' but has no 'Fancy' oir 'Very Fancy' attribute. 

# Describe the solution you'd like
Make it very fancy

# Describe alternatives you've considered
Forget the coveted brand-name wyrmskin and just wear dingy grey worm-skin like a drudge.

**Comment by Fris0uman** [comment]
Wrong github, Arcana is not part of this project.

**Comment by tenmillimaster** [comment]
What friso said. Apologies, but you'll want to take it up in Arcana's repo.
