### ISSUE TITLE
Unlocking the doors from the inside unless door is impassible.

### ISSUE THREAD

**Issue by morthein** [CleverRaven/Cataclysm-DDA#37708]
a. When you encounter a locked door, you can break into the place through a window, go to the door, and sometimes it still remains locked; even from the inside!

b. Unless the door is barricaded, obstructed, or perhaps even the lock is jammed, it should be able to be opened (unlocked) from the inside.

c. This could open an avenue for using cargo locks on doors, or trapping the doors themselves for more sinister ideas.

Even if the third sentence never comes to be, unlocking a locked door from inside the house seems like it should exist. (If it DOES exist, why do some doors not do it then? More notification perhaps?
:-)

**Comment by Illgowiththisname** [comment]
For this i would say in the real not all doors have a button in the handle or turn thingy to unlock it on one side some don't have locks and some instead have a key lock for both sides of the door in fact i got a interior that proves my point.

![IMG_20200205_111153](https://user-images.githubusercontent.com/60259456/73792075-78b09c80-4808-11ea-9204-665cc0f1cecb.jpg)

![IMG_20200205_110725](https://user-images.githubusercontent.com/60259456/73791929-20799a80-4808-11ea-9f03-54cee0eafc26.jpg)

Anyways saying that there are doors that don't just lock from one side and would need a key or be picked, smashed or pried  open to get through.

**Comment by morthein** [comment]
I'm not sure what you're trying to tell me?  I understand doors can exist with double locked sides, but it *too* common in cataclysm is what i was saying.

**Comment by scorpion451** [comment]
Two-way locks are actually illegal in a lot of places (they're a good way to die in a fire) but as demonstrated there's a lot of older houses that still have them.

The issue is mostly a technical one, as the engine doesn't have a simple way to assign a direction to a locked door at the moment like there is with peepholes.

**Comment by morthein** [comment]
oh ok. it's software limit. That i can accept thank you.  :)
