### ISSUE TITLE
After update, I can no longer interact with dogs/cats unless there are multiple nearby items

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#37711]
Game version: 0.D-11915-g77d26f9 (tiles)

Operating system: Windows 8.1 Pro

Tiles or curses: Not sure what to put here

Mods active: -Dark Days Ahead
-Disable NPC Needs
-C.R.I.T Expansion Mod
-Magiclysm
-Bens GF recipes
-Craftable Gun Pack
-DeadLeaves' Fictional Guns
-Garden Pots
-Icecoon's Arsenal
-Makeshift Items Mod
-Medieval and Historic Classes and Shields
-More Survival Tools
-Mythological Replicas
-Modular Turrets
-Salvaged Robots
-EZ-Mode Medical
-Hydroponics
-Mining Mod
-Mutant NPCs
-Mythical Martial Arts
-More Locations
-Fuji's More Buildings
-Folding Parts pack
-Vehicle Additions Pack
-Roadheader and other mining vehicles
-Tanks and Other Vehicles
-Classes and Scenarios Mod
-SpeedyDex
-Stats Through Kills
-Stats Through Skills

### Expected behavior

This may seem trivial, but I'd like to be able to interact with dogs and cats the way I used to be able to, before the update. This entailed pressing "e" and pressing the button for the direction of the dog/cat, thus bringing up the menu for interactions.

### Actual behavior

Now, when I press "e," one of three things happens:

-If there are no items in any adjacent tiles, I am told that there is nothing to examine, regardless of whether or not a dog/cat is in an adjacent tile.

-If there is one adjacent tile with items in it, I automatically examine that tile upon pressing "e," instead of being given the option to choose the tile I want to examine, and the menu showing the items in that tile pops up, preventing any other interactions with that tile, such as interacting with a dog/cat in said tile.

-If there are multiple adjacent tiles with items in them, only then am I given the option to choose which tile I want to examine, and only then am I able to choose the tile with the dog/cat in it, thus enabling interactions with said dog/cat.

### Steps to reproduce the behavior

Not sure what else to put here, beyond what has already been described.

Again, this is kind of trivial. It's not a game-breaking bug or anything, but I do like being able to have my character play with their pets, and I can't really control which tile they're in, so... yeah. If I could be able to interact with dogs/cats as before without relying on there being multiple adjacent tiles with items in them, that would be much appreciated.

**Comment by wapcaplet** [comment]
Looks like this should be fixed by #37657

**Comment by AmarinReyny** [comment]
> Looks like this should be fixed by #37692

Okay. Thank you!

**Comment by int-ua** [comment]
Don't forget to close the issue?
