### ISSUE TITLE
Application hang on exit

### ISSUE THREAD

**Issue by Soup-de-Loop** [CleverRaven/Cataclysm-DDA#37721]
# Describe the bug

Application hangs when trying to exit.

# Steps To Reproduce

1. Start CDDA on latest experimental.
2. Try to quit the game with Q or Alt-F4.
3. Game hangs, have to use end process.

# Expected behavior

The application to close down properly without having to resort to the nuclear option.

# Screenshots

N/A, no difference from usual.

# Versions and configuration

 - OS: [Windows 7, SP1]
 - Game Version: [0.D-11941-g4bfc1e6]
 - Graphics version: [Tiles]
 - Mods loaded: [None, Main Menu]

# Additional context

N/A

**Comment by eilaattwood** [comment]
Not confirming. Mine is fine under windows 7.

**Comment by Soup-de-Loop** [comment]
Just turned my computer back on and the issue seems to have resolved itself upon turning the computer off and then on again. I'm... Confused, but I'm just as glad that it did not persist. Sorry for wasting any time.
