### ISSUE TITLE
Landmines use old explosives code.

### ISSUE THREAD

**Issue by Brian-Otten** [CleverRaven/Cataclysm-DDA#37724]
# Describe the bug
Landmines still use old explosion code which makes them not behave as the player might expect
in data/json/traps.json, line 363 and 377
"vehicle_data": { "do_explosion": true, "damage": 1000, "shrapnel": 8, "sound_volume": 10 }

# Expected behavior
Game handles landmines like it does the other explosives. example:

"vehicle_data": { "do_explosion": true, "explosion": { "power": 240, "shrapnel": { "casing_mass": 217, "fragment_mass": 0.15 } }

The exact values are less important since i will be reworking landmine components/crafting in the near future, but should be similar to the hand grenade.

# Additional context
I tried implementing myself but it doesn't expect the explosion code in that json and i have no idea how to make it work.

**Comment by CountAlex** [comment]
I believe you should check function `trapfunc::landmine()` at `src/trapfunc.cpp:L605` 
It clearly uses same `explosion()` function but uses preset values so I think that landmine probably does not use JSON set values at all.
