### ISSUE TITLE
Stonefist not equipping properly on cast.

### ISSUE THREAD

**Issue by Grekhaus** [CleverRaven/Cataclysm-DDA#37749]
# Describe the bug

When the Stonefist spell from Magiclysm is cast, the resulting item (a magically created unarmed weapon) starts out as worn rather than wielded. This provides no benefit to the caster, as unarmed weapons need to be wielded in order to improve the user's unarmed attacks.

# Steps To Reproduce

1. Make a Novice Earthshaper character (they start with the spell known). 
2. Cast Stonefist (repeating as needed until casting is successful).
3. Check your inventory to see where the gauntlets end up.

# Expected behavior

When casting the Stonefist spell, the stone gauntlets item should be automatically wielded, in the same way that brass knuckles or other unarmed weapons are wielded. It should not be worn as a clothing item, as this provides no real benefit to the caster.

# Screenshots
None.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 7
- Game Version: 0.D-11911-g1daa54b [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Generic Guns [generic_guns],
    Mythical Martial Arts [MMA],
    No Rail Stations [No_Rail_Stations],
    sees-player icon, retrodays [sees_player_retro],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context
None.

**Comment by KorGgenT** [comment]
should be an easy fix, just make the item not wearable

**Comment by foulman** [comment]
Now that's odd, I'm pretty sure it didn't used to do that...

**Comment by Prkfcmdz** [comment]
I've been under the impression that this is intentional. I feel like you do more damage wearing the gloves than holding them. The only issue is that you need to wield them or something else to smash furniture.

**Comment by Night-Pryanik** [comment]
After #41209 worn gloves (stonefist gauntlets included) are counted as unarmed weapons, so I think this issue can be safely closed.
