### ISSUE TITLE
False "There is nothing that can be examined nearby" message

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#37745]
# Describe the bug

When pressing `e` to "examine" structures, terrain, or furniture around my character, I cannot do it unless at least one of the adjacent tiles has something I can interact with (like a window, bush, door, pet, item on the floor). The message log simply says "There is nothing that can be examined nearby."
 

# Steps To Reproduce

Position character (1) outdoors with no adjacent trees or bushes, or (2) in or near a house with no adjacent doors or windows, and press `e` to examine.

    There is nothing that can be examined nearby.

Now, drop items on at least two nearby tiles, and press `e` to examine again. You will be able to examine all 9 tiles (current tile plus adjacent).

# Expected behavior

Expect current tile, and all 8 adjacent tiles, to be valid targets for examination. When examining nearby structures, terrain, or furniture, expect to see messages about them, for example:

- That is a dresser. It is empty.
- That is a white wall.
- That is a open wood door.
- That is a sofa.
- That is a display rack.
- That is a floor.
- That is a gravel.
- That is a dead grass.

In other words, when pressing `e` to examine, I expect to always be prompted for one of the 9 valid directions for examination.

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch; Distributor ID: Ubuntu; Description: Ubuntu 18.04.4 LTS; Release: 18.04; Codename: bionic; 
- Game Version: 0.D-11977-g6017c7ce25 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Stats Through Skills [StatsThroughSkills],
    No Rail Stations [No_Rail_Stations]
]

# Additional context

This behavior was altered in PR #37597

A configuration setting was added to the "Interface" tab, "Autoselect if exactly one valid target", but setting this to "true" or "false" makes no difference; terrain, furniture, and structures cannot be examined unless one of them is also interactive in some way.

**Comment by esotericist** [comment]
This is usage that look around (`x` or `;` by default) does more smoothly, with fewer keystrokes and with better communication of details. 

The problem we're trying to solve is that `e`xamine was overloaded in purpose. Our current intention is that `e` is for interacting with objects that can be interacted with. So, renaming it to interact might possibly be the next step, to save on confusion for what it is for.
