### ISSUE TITLE
Multi cooker cannot do anything with its stock battery configuration.

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#37747]
# Describe the bug

I got it with a 500-charge battery from the shop, yet it seem to require much more energy to do useful things (1250 for cooked meat, for instance)

# Steps To Reproduce

1. Load the game.
2. Try to use the multi cooker in the inventory.
3. The power requirements exceed the full battery capacity.

# Expected behavior

The tool working w/o mods right from the shop. The customers aren't supposed to mess with its internal circuitry just for it to do anything useful, are they?

# Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.D-11942-ga63aaadb19-dirty [64-bit]
- Graphics Version: Curses
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

# Additional context

[2020.02.03.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4162950/2020.02.03.zip)

**Comment by eilaattwood** [comment]
Yep, that energy levels are strange. You need only 7 charges to cook it on an electric hotplate, and 1250 charges on multi-cooker? That makes no sense.

**Comment by KorGgenT** [comment]
ooh yeah, the hotplate needs rebalancing then. 7 charges is like nothing

**Comment by l29ah** [comment]
Still broken in master.

**Comment by l29ah** [comment]
Still broken in master.

**Comment by l29ah** [comment]
Tested today, cooking a portion of rice takes 600 charges.
