### ISSUE TITLE
Pneumatic weapons are too slow to reload.

### ISSUE THREAD

**Issue by eilaattwood** [CleverRaven/Cataclysm-DDA#37752]
# Is your feature request related to a problem? Please describe.
Pneumatic rifle, pneumatic shotgun and pneumatic bolt driver has reload time of 6000 moves per projectile, while crossbows has reload time between 50 and 600 (except heavy crossbow that also has 6000)

Yep, I understand why their reload time was nerfed, and with the shotgun that makes sense. But not with the bolt driver and rifle. You can shoot the whole magazine without pumping air, but for adding 1 projectile to it you need 6000 moves? That's too much. 

# Describe the solution you'd like
Per-projectile reload time in pneumatic rifle and pneumatic bolt driver should be comparable to the reloading time of the usual crossbow.

# Describe alternatives you've considered
Add weapon mod for pneumatic weapons, "electric pump", that greatly decreases reload time, but requires UPS charges to reload weapon.

# Additional context
None

**Comment by Rivet-the-Zombie** [comment]
>You can shoot the whole magazine without pumping air, but for adding 1 projectile to it you need 6000 moves?

Once charged, the air reservoir has enough power to fire the whole magazine. If you fire a few rounds and then reload another, the reservoir has been partially depleted and now requires re-pressurization to be filled once more.

**Comment by eilaattwood** [comment]
> > You can shoot the whole magazine without pumping air, but for adding 1 projectile to it you need 6000 moves?
> 
> Once charged, the air reservoir has enough power to fire the whole magazine. If you fire a few rounds and then reload another, the reservoir has been partially depleted and now requires re-pressurization to be filled once more.

Yep, I understand that. Still too much time to partially re-pressurize it, in my opinion.

**Comment by Alkheemist** [comment]
Yep, this got 'fixed' in https://github.com/CleverRaven/Cataclysm-DDA/pull/33199 but I don't agree with it either. The Tihar takes fifteen minutes to load because every time you add one bullet, you pump for a full minute. After the first bullet, the other fourteen minutes of pumping don't actually add anything to the already full reservoir, so that argument doesn't work. 

What should be done is what the metro games did: have a magazine and make reloading it take 5 minutes or whatever. 

The real solution would be to implement the multiple ammo types per weapon, but that's definitely not trivial.

If you don't like it, you can just tweak your local json file. It's in data/json/items/ranged.json

**Comment by eilaattwood** [comment]
>If you don't like it, you can just tweak your local json file. It's in data/json/items/ranged.json
Well, I can. I even can add it to my own mod I'm currently working on. But I'd rather add the electric pump weapon mod :)

**Comment by vlad1492** [comment]
Not fun but seems consistent with actual pre-charged pneumatic weapons

Getting a useful reservoir up to 3000psi by hand is no small task. 
"a workout for five minutes "

https://www.pyramydair.com/article/Using_a_hand_pump_May_2006/30

**Comment by eilaattwood** [comment]
> 
> 
> Not fun but seems consistent with actual pre-charged pneumatic weapons
> 
> Getting a useful reservoir up to 3000psi by hand is no small task.
> "a workout for five minutes "
> 
> https://www.pyramydair.com/article/Using_a_hand_pump_May_2006/30

Reloading fully, from 0 ammo to maximum ammo (and empty reservoir to full along with that) for 6000 turns is ok. But not every projectile. Currently it takes **15** minutes to reload pneumatic rifle. 15 balls 1 minute each. Really? Fifteen minutes to reload a weapon for 15 shots? PCP airguns you mentioned can make 50-100 shots after pressurized to the full.

**Comment by kevingranade** [comment]
Working as intended. I did some research into this, outlined here https://discourse.cataclysmdda.org/t/balance-pneumatic-weapons/14488/35?u=kevin.granade
If you find something inaccurate, bring it up, but otherwise actual research trumps opinion.
