### ISSUE TITLE
Lack of information when debugging survivor stories

### ISSUE THREAD

**Issue by la-magra** [CleverRaven/Cataclysm-DDA#37750]
Game version: compiled, master branch (6017c7ce2548e501f0aa34fc6d3363fdec68a65d)

Operating system: Linux x64 (I use Arch by the way)

Tiles or curses: curses

Mods active: none, only Dark Days ahead

### Expected behavior
Debug menu should provide a minimal amount of information in order to ease debugging (trait ids in particular).

### Actual behavior
It does not.

### Steps to reproduce the behavior
Start game, debug menu, p, p, 1, u, click every survivor story to know which one you want to test.

### Code that solves it

```diff
--- a/src/wish.cpp
+++ b/src/wish.cpp
@@ -93,6 +93,10 @@ class wish_mutate_callback: public uilist_callback
                        mdata.valid ? _( "Valid" ) : _( "Nonvalid" ) );
             int line2 = 4;

+            line2++;
+            mvwprintz( menu->window, point( startx, line2 ), c_light_gray,
+                       "ID: " + std::string( vTraits[entnum].c_str() ) );
+
             if( !mdata.prereqs.empty() ) {
                 line2++;
                 mvwprintz( menu->window, point( startx, line2 ), c_light_gray, _( "Prereqs:" ) );

```

If code looks ok/approved I can open a PR, or the diff is free to grab by anyone.

**Comment by anothersimulacrum** [comment]
You should just open a PR. Other than the unnecessary increment (just set it to 5 initially), diff looks fine to me (unfamiliar with that code are though).

**Comment by ZhilkinSerg** [comment]
Yeah, don't need an open issue for debug features - just make a PR with whatever changes necessary.
