### ISSUE TITLE
Fire's weird behavior

### ISSUE THREAD

**Issue by RDru** [CleverRaven/Cataclysm-DDA#37771]
# Describe the bug

A. Fire is not burning whole buildings:
- it leaves patches of not burned floor
- it takes a lot of time for it to spread - it should spread way faster

B. Fire is burning indefinitely after leaving the reality bubble and coming back after long time.
C. Fire is not burning leather clothes but leather patches are burning fine.

# Steps To Reproduce

A. Lit some buildings and watch.
B. Light a piece of paper then leave the area fast. Make sure you are far away, maybe save, load. Come back after day or more.
C. Put leather clothes into a fire.

# Expected behavior

Fire in interiors should spread faster and easier.
There should be some checks when the fire started and if it should still burn.
Leather should slowly burn when put into existing fire.

# Screenshots

A building that is burning for like 4 hours:
![A building that is burning for like 4 hours](https://user-images.githubusercontent.com/26722636/73959749-1a6be280-490a-11ea-94d8-74dfcfbca5b2.png)

Some everlasting fires on the road that are there for who knows how many days already:
![Some everlasting fires on the road that are there for who knows how many days already](https://user-images.githubusercontent.com/26722636/73960000-76366b80-490a-11ea-9ee7-5be72da16137.png)

Another building burning for at least 3 hours already with visible patches without fire:
![Another building burning for at least 3 hours already with visible patches without fire](https://user-images.githubusercontent.com/26722636/73960251-d4fbe500-490a-11ea-906a-d7bf22edbc17.png)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-11962-ge228853 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Classes and Scenarios Mod [more_classes_scenarios],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    No Fungal Monsters [No_Fungi],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Alternative Map Key [alt_map_key],
    Vehicle Additions Pack [blazemod],
    INT Based Learning [intbasedlearning]
]

**Comment by eilaattwood** [comment]
I wonder if leather cloth that cannot burn is actually leather driving suit(that actually cannot burn because of nomex)

**Comment by RDru** [comment]
> I wonder if leather cloth that cannot burn is actually leather driving suit(that actually cannot burn because of nomex)
No. I usually put fire on zombie corpse and whatever he dropped and leather doesn't burn. 

![1](https://user-images.githubusercontent.com/26722636/73963048-d7ad0900-490f-11ea-99a0-a5d37de0d659.png)

**Comment by Brian-Otten** [comment]
I haven't found burning house behaviour to be all "too" weird, but i can confirm some of the everlasting road fires have bugged me before. It might be because the fires are only burning if you are in the reality bubble, but am not sure.

**Comment by scorpion451** [comment]
Leather isn't flammable- that's why blacksmiths traditionally wear leather gloves and leather aprons.

Like wool, it doesn't catch fire, it just sort of slowly chars.

**Comment by RDru** [comment]
> 
> 
> Leather isn't flammable- that's why blacksmiths traditionally wear leather gloves and leather aprons.
> 
> Like wool, it doesn't catch fire, it just sort of slowly chars at extremely high temperatures.

If you put those gloves (with hands or not) into fireplace they will eventually turn into ash. 
I don't know if fire in game has temperature but at least "raging fire" and maybe "fire" should burn the leather.

There is some leather flammability testing here: http://www.ips.lodz.pl/sites/default/files/behaviour_of_leather_in_fire_conditions_and_their_flame_retardancy.pdf

**Comment by scorpion451** [comment]
Correct, note the results of said test: natural leather only ignites in the most technical sense. 
It can be charred, but it never burns.
