### ISSUE TITLE
Auto-move has trouble avoiding thorny bushes.

### ISSUE THREAD

**Issue by Brian-Otten** [CleverRaven/Cataclysm-DDA#37811]
# Describe the bug
Auto-move has trouble avoiding thorny bushes. When using automove through move to forests mainly, it avoids most, but not all bushes, and cancels your automove to ask if you want to move through them.

# Steps To Reproduce

Try to automove through a forest.

# Expected behavior

Automove always avoids the thorny bushes and does not cancel automove to ask if you want to move through them.

# Screenshots
![image](https://user-images.githubusercontent.com/47374323/74054956-59b83300-49df-11ea-87ea-a027f17227d8.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-12029-g29de372 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

**Comment by jkraybill** [comment]
This should be fixed by #37964! Please verify.
