### ISSUE TITLE
Allied NPCs block ladders, making it impossible to leave locked 1x1 rooms

### ISSUE THREAD

**Issue by dissociativity** [CleverRaven/Cataclysm-DDA#37820]
# Describe the bug

Allied NPCs block ladders, making it impossible to leave 1x1 rooms, there is no way to make them move

# Steps To Reproduce

Load attached save.

or:
Go to sewage treatment plant after recruiting shelter npc
climb ladder to roof
emerge in 1x1 room with locked metal door
try to climb down
NPC ally will swear at you, asking you to move, will block any movement
Only real option is suicide.

# Expected behavior

NPC will wait next to ladder and check that the tile above is clear before ascending.
I am able to push NPC out of the way from the floor above, and/or climbing down blocked stairs attempts to push any creature in the way with a strength check perhaps?

# Screenshots

it's a 1x1 room with a ladder underneath the player, nothing complex enough to warrant an image

# Versions and configuration
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-11962-ge228853 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    No Rail Stations [No_Rail_Stations],
    sees-player icon, retrodays [sees_player_retro],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex]
]
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4173452/save.zip)

**Comment by Fris0uman** [comment]
When trying to reproduce this the game lets me move up and down the ladder, but it puts me on the same tile as the NPC.

**Comment by davidpwbrown** [comment]
Yeah I dont get the blockage either, it merges me onto same tile as monster/NPC when they are on the stair tile.
