### ISSUE TITLE
Impossible to install a battery compartment mod to a smartphone

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#37830]
# Describe the bug

```
You can't unload a rechargeable smartphone (UPS) *!
You cancel unloading the tool.
```
I don't see why should it be impossible. I've done that IRL!

And it is impossible for some gameplay balance reasons, why does the dialog offer smartphones in the list of items where the mod can be installed in the first place?

**Comment by Inglonias** [comment]
The smartphone is an oddball tool, especially after the battery rework happened. It's supposed to represent a high-end device with a battery that cannot be removed, and can be recharged via UPS compatible charging stations (and presumably it came with a wall adapter that you can't use after the world ends).

If it were up to me, the solution to this would be to remove the item from the game entirely, and abstract cellphones to represent any given variety of cellphone, flip phone, or basic phone you can buy these days.

**Comment by TechyBen** [comment]
Also, Battery packs are a thing. So having this craft into "Smart Phone with large battery mod" then back into a normal smartphone would not be outside of possibility IRL. Seen some people make 30-60 day battery packs for phones on Youtube. XD

**Comment by eilaattwood** [comment]
Yep, in-game smartphone represent device with irremovable battery. That's why we can't replace nor modify it. Probably should blacklist smartphone for the battery adaptor installable list, or replace smartphone battery with swappable one.

**Comment by Funguss** [comment]
Apple had a monopoly in New England. That's how the cataclysm _really_ started.

In fact, maybe there aren't really any zombies either, they're all just peeps looking for their new pikachu. *cue X-Files theme*

**Comment by kevingranade** [comment]
Irremovable battery.
