### ISSUE TITLE
Typo in tainted blood description

### ISSUE THREAD

**Issue by WeaverThree** [CleverRaven/Cataclysm-DDA#37841]
# Describe the bug

Tainted blood's description: "black sluge ondulate slowly" should be "black sludge undulates slowly"

This is the FUEL category fluid item that comes from butchering zombies.

# Screenshots
 
![cataclysm-tiles — 2020·02·08 — 11·00·16](https://user-images.githubusercontent.com/1582240/74090673-ed7f1300-4a62-11ea-8bba-20cd9ed72e6f.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.D-12062-ge7271b0 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Bens GF recipes [Tolerate_This],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Mapgen Demo [mapgen_demo],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks],
    Classes and Scenarios Mod [more_classes_scenarios],
    Classic Roguelike Classes [RL_Classes],
    Fuji's Military Profession Pack [fuji_mpp],
    Manual Bionic Installation [manualbionicinstall],
    Safe Autodoc [safeautodoc],
    Stats Through Skills [StatsThroughSkills],
    Disable NPC Needs [no_npc_food]
]

# Additional context

I'd submit a PU instead but I haven't had the time to get set up for that.

**Comment by l29ah** [comment]
You can make changes and submit PRs with them entirely from the github web interface.
