### ISSUE TITLE
Give speed bonus when reading or resting on a chair or other seat

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#37842]
# Is your feature request related to a problem? Please describe.

Moving onto chairs is slow, but what if you want to sit? I find it easier to read a book or catch my breath when I'm sitting down.

Unfortunately, in-game, reading a book or catching your breath take the same amount of time, whether you are sitting or standing.

# Describe the solution you'd like

Give a moderate (10-20%) speed bonus for recovering stamina or reading a book, while the character is sitting on a chair (or vehicle seat, or even a couch), similar to how tables/workbenches provide a crafting time bonus.

# Describe alternatives you've considered

Using a chair to catch your breath in the middle of combat would be an interesting countereffect to their movement penalty, but it raises the question of whether you can fight effectively while you're sitting on a chair. In other words, do you mean to sit and rest, or stand and fight?

I thought perhaps "crouch" mode could be interpreted as "sitting down" when you're on a chair tile, but that conflicts with the existing game behavior, when you "crouch" in a vehicle seat to take advantage of nearby obstructions.

I considered proposing "nearby" chairs as eligible for the bonus, but that would be especially problematic for in-combat stamina recovery. For reading, it seems reasonable to require sitting on the chair before reading, to get the bonus.

# Additional context

Chairs are all over the place in the game, but aside for the morale bonus for eating with a chair and table, it doesn't seem like they're useful for much except kindling.

**Comment by shadowsapex** [comment]
I do not find the presence or absence of chairs changes how fast I read

**Comment by JeanLucVanDamme** [comment]
I imagine most people would find reading while standing to be pretty uncomfortable or distracting -- unless they were leaning on a counter or table to stabilize themselves. Which kinda proves the point.

**Comment by shadowsapex** [comment]
you're saying that sitting is what improves reading. And we can sit anywhere. I would rather this particular piece of realism wait for sitting to be implemented, not chairs given a speed bonus. in fact, for now, you can just imagine that your character sits when they do long activities

**Comment by wapcaplet** [comment]
In general, and in short bursts, I can certainly read as well standing up as I can while sitting. I'm thinking of the case where your character is reading for hours at a time, maybe spending the whole day reading books to learn skills.

I'm suggesting that the comfortability of the chair is what makes it easier to rest, and focus on reading, and possibly even do other tasks like sewing, soldering, or crafting. The comfort factor of chairs doesn't seem to be used very much for game effects now.

**Comment by shadowsapex** [comment]
nah floor is fine

**Comment by kevingranade** [comment]
I mostly agree with the opinions that reading speed isn't going to be affected by posture, if anything there might be a comfort or relaxation effect that is orthogonal to reading speed.

Also even if this were the case, we wouldn't apply a speedup on top of the current speed, but rather assess a penalty to reading speed based on improper posture.  The existing reading speed is *nominal*, whichbwould map to typical seated reading posture.

**Comment by wapcaplet** [comment]
Alright, I’ll admit the idea of reading faster on a chair is a little fantastical.

Could their comfortability instead be modeled as a slight morale boost? That would have a similar positive effect on learning speed, and could apply when doing other long-running activities you might find easier to manage while seated (crafting, sewing, or just passing the time) while giving no morale bonus during activities you would probably do just as well or better standing up (cooking, digging, welding, fighting).

Having a chair could provide a partial “table” bonus, by virtue of having a lap when you are sitting down. Small things could be crafted in your lap, as a makeshift crafting spot - not as good as a table, but better than crafting directly in your hands while standing up.

There hasn’t been any comment on the idea of chairs giving a stamina recovery bonus. That seems like their biggest (and most potentially game-changing) attribute.

**Comment by kevingranade** [comment]
AFAICT #37669 covers what you're suggesting, if you want to extend it further it needs to be a more detailed outline of why and how it should work.
