### ISSUE TITLE
Wasted components in recipes with alternatives

### ISSUE THREAD

**Issue by Karthas077** [CleverRaven/Cataclysm-DDA#37847]
# Is your feature request related to a problem? Please describe.
When Meat Soup only cares that you put some type of meat in it, but you run out of "Canned Chicken" partway through by "wasting a component"; the inability to substitute any other valid meat item, or at the very least get the broth back, is extremely frustrating.

# Describe the solution you'd like
If a line in a recipe accepts multiple "equivalent" components, it should be possible to substitute one of those to continue crafting.

# Describe alternatives you've considered
The ability to abort an in-progress craft to reclaim at least some of the involved components.

# Additional context
When you burn the chicken you were going to put in your scrambled eggs, you don't just throw the eggs away because "you only have bacon left".

**Comment by Funguss** [comment]
Just like those uncooked TV dinners that you accidentally ate one of when you hit '3' along with 'e'. But that's a separate issue.
