### ISSUE TITLE
Mapgen sometimes generates completely empty towns

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#37856]
Made of a few roads.

# Expected behavior

Either no town or a populated town.

# Screenshots

![](https://pstbin.ru/f/14294/)

# Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.D-12025-g40c494c222-dirty [64-bit]
- Graphics Version: Curses
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

# Additional context

**Comment by TechyBen** [comment]
Hey, could always make it a feature. Urban planning and all that. A sign stating "Real Estate for Sale" would be nice though if the worldgen can detect it as empty. :P

**Comment by Funguss** [comment]
That's actually an accurate representation of [Gouldsboro, Maine](https://en.wikipedia.org/wiki/Gouldsboro,_Maine). It's kinda scary.

**Comment by Night-Pryanik** [comment]
@l29ah is this issue still valid?

**Comment by l29ah** [comment]
Yes, i just got one: 
![screenshot-empty-town](https://user-images.githubusercontent.com/31852/116960077-e3ac8580-ac8e-11eb-8d5a-4990ebbd08e2.png)

**Comment by Night-Pryanik** [comment]
@l29ah What's your setting for size of cities?

**Comment by l29ah** [comment]
4

**Comment by Night-Pryanik** [comment]
That explains it. According to the code, with size of cities set to 4 or less, there is a fairly high chance to spawn such 1-tile "city".
We might need to increase the minimum size of cities to 2 to fix this issue.
