### ISSUE TITLE
Killer Drive trait balance

### ISSUE THREAD

**Issue by Karthas077** [CleverRaven/Cataclysm-DDA#37867]
# Is your feature request related to a problem? Please describe.
I understand Killer Drive is an extremely cheap starting trait, but getting 5 morale from a single kill and capping at 10 seems a bit too shallow for a character who supposedly gets extreme joy from killing. +10 morale is basically nothing, and it does not scale well when you're mowing through large numbers of zombies in a row. I would expect a character with Killer Drive who just finished off two dozen plus zombies to be incredibly manic.

"I feel like Killer Drive doesn't accurately represent the mental state of a person obsessed with killing"

# Describe the solution you'd like
Ideally, treat it like a stimulant addiction. Let it stack a lot higher and have both a crash and withdrawal. Barring that, decrease the morale gain per kill, increase both the positive and negative cap.

# Describe alternatives you've considered
Increase the cap but raise the point cost.

**Comment by vlad1492** [comment]
How about if it gets low enough you attack nearby NPCs?

**Comment by Karthas077** [comment]
I'm not a huge fan of taking away control from a player like that. I can see making it bad enough that the player would /want/ to attack an NPC, but considering the extreme levels of morale penalty players are willing to put up with when necessary, I don't know how feasible that is.

**Comment by kevingranade** [comment]
We already discussed this and you got a hard no.
