### ISSUE TITLE
 SCENARIO_BLACKLISTS prevents loading a world twice

### ISSUE THREAD

**Issue by ephemeralstoryteller** [CleverRaven/Cataclysm-DDA#37892]
# Describe the bug

When attempting to load a world using the new SCENARIO_BLACKLIST functionality, from #37575, the game returns an error saying that there is already an existing scenario_blacklist and prevents loading. Quitting the game entirely seems to allow for loading as normal.

# Steps To Reproduce

1. Use the example mod provided in #37575.
2. Load in fine
3. Quit to menu and attempt to load again

# Versions and configuration

 - OS: Windows 7
 - Game Version: 0.D-12155-gb7876ca
 - Graphics version: Tiles
 - Mods loaded: Dark Skies Above, a mod I'm working on, however testing with the sample mod provided by #37575 resulted in the same error.

# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4181940/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4181945/debug.log)
[Millgrove save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4181950/Millgrove.save.zip)
[DarkSkiesAbove.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4181953/DarkSkiesAbove.zip)

**Comment by anothersimulacrum** [comment]
Agh! Will look into this, thanks for the report.

**Comment by ephemeralstoryteller** [comment]
No problem! Thanks for your work on the change!
