### ISSUE TITLE
Survivor (and all other) gas masks needs encumbrance rebalance

### ISSUE THREAD

**Issue by Pspiotrek** [CleverRaven/Cataclysm-DDA#37906]
Survivor masks have a problem with encumbrance. While regular gas mask has 20 encumbrance, light survivor mask has 10. While this is lightly reinforced version of gas mask, i don't see why you should be able to breathe easier in it. At the same time, masks provide some basic filtration when cartridge is not inserted. 

# Describe the solution you'd like
Setting survivor mask encumbrance at 20 for light, 25 for regular, 30 for heavy (all fit) (some goes for all survivor masks of appropriate type) when turned on (prepared), and 10 when off. Setting Env protection when mask is not prepared to 3 (2 for regular filter mask).

**Comment by eilaattwood** [comment]
Now we should question why heavy mask is causing more mouth encumbrance than light one if they both use same filter cartridges?

**Comment by RDru** [comment]
All (?) survivor gear is better then their counterparts. What's the point of improving something if it won't get better right?
Also firefighter PBA mask has also 10 encumbrance.

20+ seems like a lot for mouth encumbrance.

**Comment by Pspiotrek** [comment]
> All (?) survivor gear is better then their counterparts. What's the point of improving something if it won't get better right?
> Also firefighter PBA mask has also 10 encumbrance.
> 
> 20+ seems like a lot for mouth encumbrance.

1. Armor protection. Survivor gear items are usually reinforced normal items or custom made ones to fit your own body in a best possible way in which case they should have lower encumbrance. This is not only the case of reinforced regular item, but also matter of very nature of gas mask which puts air through many layers of filters. There is no way of making breathing easier unless you use closed cycle air supply or some high end, near future filter. Neither is used by gas masks in CDDA.
2. 20 is much but, have you ever wear a gas mask with filter on? It's very hard to breathe fast. There is no reason for survivor mask to have lower encumbrance if its giving same env protection. Also, because its much I suggested low encumbrance of 10 when mask is turned off, which is also realistic. Filter mas could even go as low as value of dust mask.

**Comment by RDru** [comment]
Ok. Activation and deactivation should take time and it could simulate having filters attached or not. This would also require lowering mouth encumbrance when mask is turned off.

**Comment by mrkybe** [comment]
@Pspiotrek I don't think you'd need a closed cycle air supply necessarily.  A fan/compressor type deal to force air through the filter would also make it easier to breath.

**Comment by scorpion451** [comment]
Probably the best argument against this is that I clicked it wondering if it was someone else interested in seeing the encumbrance _reduced_ across the board, thus making masks worth using.

As it is, gas masks are treated like they were all the WWI-era surplus sort that were like breathing through a straw. Modern masks have over a century of advancement geared toward protecting people doing sustained strenuous activity in hazardous atmospheres with minimal hindrance.

Now using up charges faster when you're breathing more heavily, on the other hand, is realistic.

**Comment by Funguss** [comment]
On top of this the fact that eye encumbrance also goes up proportionally is a bit weird. Hell, survivor gear in general is a bit weird, but that's a separate point.

**Comment by eilaattwood** [comment]
> As it is, gas masks are treated like they were all the WWI-era-surplus sort that were like breathing through a straw. Modern masks have over a century of advancement geared toward protecting people doing sustained strenuous activity in hazardous atmospheres with minimal hindrance.

Do you have some precise data on this, or was it just a suggestion? Both survivor mask and gas mask use same charcoal cartridges, that *can be crafted*.

What an improvement can be done here? That's still breathing through the filter, anyways. The filter efficiency can only be improved by increasing it's working area, or using air pumps. None of that is possible on face-only mask, without external bulky assembly.

**Comment by Pspiotrek** [comment]
>On top of this the fact that eye encumbrance also goes up proportionally is a bit weird. Hell, survivor gear in general is a bit weird, but that's a separate point.

Its not weird. If its harder to breathe and exchange air in mask, more foggy glass will become.

>As it is, gas masks are treated like they were all the WWI-era-surplus sort that were like breathing through a straw. Modern masks have over a century of advancement geared toward protecting people doing sustained strenuous activity in hazardous atmospheres with minimal hindrance.

I can assure 20 encumbrance is not reflecting WW1-tier gas mask. Its not easy to breathe even in modern ones if you use heavy, proper filter.

New filter types could be introduced too but thats some more work.

**Comment by Funguss** [comment]
> Its not weird. If its harder to breathe and exchange air in mask, more foggy glass will become.
Well, my understanding is that there shouldn't be any fogging unless you're not maintaining your gear properly. On top of this there are design types that are expressly made to prevent fogging, both for dive masks and gas masks, though of course you still have to maintain your gear.

Add to this that the way eye encumbrance works (limiting your sight distance and incurring perception/ranged penalties) the whole thing is wonky. The whole benefit of goggles is that they increase your sight distance (by allowing you to open your eyes) at the cost of a reduced FOV, which may be borderline insignificant. A gas mask would interfere with using a scope, certainly, but unless the glass was scratched and damaged then seeing dead ahead wouldn't be much of a problem.

My point, though, was that the eye protection is a feature of the mask, much like having pockets on jeans. It's better to have an all-in-one piece rather than have two separate items you need to put on when facing a gas attack. If fogging WAS occurring due to a poor design then the survivor variant actually makes sense. There is zero need to ensure airflow to your eyes after all.
