### ISSUE TITLE
Update documentation of seed_data and also document disinfectant_power

### ISSUE THREAD

**Issue by snipercup** [CleverRaven/Cataclysm-DDA#37905]
# Is your feature request related to a problem? Please describe.
The documentation on seed_data is not up to date

# Describe the solution you'd like
Where it says "fruits": "weed" it should be "fruit": "weed" (fruits should miss the s)
There is no documentation on the use_action property disinfectant_power that is used in combination with use_action type:heal. It says  'quality of disinfectant' in the c++ code as a description for disinfectant_power 

# Describe alternatives you've considered
Not adding

**Comment by kevingranade** [comment]
Fixed the "fruits" typo https://github.com/CleverRaven/Cataclysm-DDA/commit/ab75d68fee101c0a6b37ce91d1785523f2bf7052
