### ISSUE TITLE
Regular UPS increases in volume when loaded

### ISSUE THREAD

**Issue by ektoplazm** [CleverRaven/Cataclysm-DDA#37901]
# Describe the bug

Unlike other electronic devices UPS increases in volume when loaded with heavy batteries, which renders it useless for power armor.

# Steps To Reproduce

1. Spawn UPS
2. Spawn different types of heavy batteries
3. Check volume changes on the UPS after loading it

# Expected behavior

The volume of the UPS should not increase since it's an electronic device and batteries are not supposed to protrude from those.

Just checked adv UPS - it behaves normally, loading it with plutonium cells does not increase its volume.

# Screenshots

![image](https://user-images.githubusercontent.com/60448096/74191555-e32c6700-4c64-11ea-9bff-9476dd4325e4.png)

# Versions and configuration

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4183126/debug.log)

    - OS Version: 10.0 1903
- Game Version: 0.D-12166-g0a401c8 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Slots [cbm_slots],
    No Rail Stations [No_Rail_Stations]

**Comment by Funguss** [comment]
In the full description it mentions that the UPS has its' own custom battery that's rechargeable but irremovable. In light of this it's reasonable to suppose the battery is attached via cable than by internal housing...

Was just struck by the realisation that the UPS isn't rechargeable via batteries at all. Not quite sure how you've achieved this.

**Comment by CSHague** [comment]
That's the old description for the UPS in the screenshot so it must be an older version before it was changed. Until recently, you could load batteries into the UPS until it was changed to have its own battery making it slightly higher capacity than a heavy battery, giving the UPS some use.

**Comment by Funguss** [comment]
Oh? How recently? I always used to recharge my UPS via a vehicle port, on the rare occasions I used them at all. I don't think I've recharged them with batteries since back when they came as ammo stacks.

**Comment by ektoplazm** [comment]
The UPS is supposed to be rechargable with heavy batteries in the current experimental build:
https://github.com/CleverRaven/Cataclysm-DDA/blob/999937b55ede91a56cb2ce7e7179991e012b2c6a/data/json/items/tool/electronics.json#L507
http://cdda-trunk.chezzo.com/UPS_off

**Comment by Funguss** [comment]
Aha! Sorry about that! I would say that for power armour there's a CBM for it that allows it to work on bio energy, plus there's a UPS CBM I believe.

**Comment by ektoplazm** [comment]
I found the culprit - in [this PR ](https://github.com/CleverRaven/Cataclysm-DDA/pull/37146/commits/3ba953386df1a0db7eb0c4823cdae742bc8bfd15) the volume of all heavy batteries was increased, while "magazine_well" parameter for the regular UPS remained unchanged at 4 units (i.e. 4L), I'll make a PR shortly.
