### ISSUE TITLE
Examining a bathtub or other receptacle should not immediately ask what to fill it with

### ISSUE THREAD

**Issue by jkraybill** [CleverRaven/Cataclysm-DDA#37920]
# Is your feature request related to a problem? Please describe.
When the player (e)xamines a bathtub or some other receptacles that are empty of liquid, even if they contain items, while holding a liquid, the first menu received is "Store which drink?".

This is non-intuitive to new players, but even in most scenarios the thing you are trying to do when (e)xamining a bathtub with an item icon in it is to see the item in the bathtub, not to pour something into the bathtub.

# Describe the solution you'd like
Instead of immediately getting the "Store which drink?" menu, maybe show a first menu that allows the player to select the action, e.g. "Store Item in (receptacle)" and "Examine (receptacle)". Alternatively, don't do reload/unload actions to things like bathtubs when doing (e)xamine.

# Describe alternatives you've considered
Should storing items in a bathtub even be part of the examine action? Unload and Reload actions already target this case pretty well. This action - pouring, say, a bunch of cough syrup into a bathtub - is rarely the intent of the player when (e)xamining a bathtub.

# Additional context
I'm currently logging issues that I think are obstacles to new player adoption, with the intent of hopefully some of these getting addressed in 0.F. This issue is not a suggestion for 0.E.

**Comment by Draakus** [comment]
"(e)xamining a bathtub with an item icon in it is to see the item in the bathtub, not to pour something into the bathtub."

The underlying problem with this is using 'e' where 'g' should be used. I totally can't get used to it myself yet but I understand why it is that way now.

**Comment by jkraybill** [comment]
@Draakus OK, but I think my use of "e" to view or retrieve things from squares is pretty normal behaviour for a new player, and I also think a player saying "examine" a bathtub shouldn't expect that the first thing the game asks is "what do you want to pour into this bathtub?"

In many other similar cases (e.g. oven), the player isn't told they are doing a default action when multiple actions are possible when (e)xamining -- they are given a pre-menu that asks them what they intend to do. That feels appropriate here. Pouring stuff into a bathtub is non-intuitive as the default action when (e)xamining a bathtub.

**Comment by wapcaplet** [comment]
This one has bothered me for a long time. My answer to “Dump all your (clean water / antiseptic / bleach / Irish whiskey) in the bathtub?” will probably always be “NO.”

Perhaps examining a bathtub could give a menu of options, similar to what you see for a water heater, rather than a yes/no prompt that will be answered “no” in most situations.
