### ISSUE TITLE
Splint usability

### ISSUE THREAD

**Issue by jkraybill** [CleverRaven/Cataclysm-DDA#37925]
# Is your feature request related to a problem? Please describe.
If you break a leg, and then try to disinfect/bandage it, you get a message that the limb is broken and needs a splint. So you craft a splint. The splint does not let you (a)pply it -- you have to (W)ear it, which as a first-time splint user is unintuitive. There is no feedback that you have to (W)ear it, you just get a message like "you can't do anything useful with the splint".

If you break both legs, and then (W)ear splints twice, both splints get applied to the same leg. The splints get auto-applied to the "first" broken limb both times. I had to go into the clothing menu, find the double-splinted leg, and use (c) to change the side of the second splint.

# Describe the solution you'd like
1 - (a)pplying a splint should have the same effect as (W)earing it, and if you have multiple splintable limbs, should ask you where to apply it.
2 - (W)earing a splint, if you have multiple splintable appendages, should ask you where to wear it.
3 - If 1 and 2 above are not implemented, (W)earing a splint should at least never auto-wear it onto an appendage that already is splinted when a non-splinted broken limb exists. And if a non-splinted broken limb does NOT exist, it probably should ask for confirmation before double-splinting.

At the very least, the default behaviour of (W)ear should be to apply to the least splinted appendage, so if I have two broken legs and one is splinted, (W) should not splint the already-splinted one.

Having to go into the clothing menu and use (c) to change sides should never be a required action unless I'm doing something unusual.

# Describe alternatives you've considered
At the very least, the game should not double-splint a splinted limb when an unsplinted broken limb exists.

# Additional context
This is a suggestion for 0.F, does not seem like a 0.E blocker.

To repro this one, break both legs, spawn two splints, and then (W)ear the splints twice. Both get applied to the same limb. If you try to (a)pply the splints, which a new player would expect to work like bandages or antiseptic, note the non-helpful error message.

**Comment by Funguss** [comment]
Very good points. As a heads up, know you can 'c'hange sides in the 'i'nventory now (think that's relatively new at least) and by 'e'xamining in the '/' advanced inventory management menu.
