### ISSUE TITLE
return LUA

### ISSUE THREAD

**Issue by 12347654** [CleverRaven/Cataclysm-DDA#37933]
# Is your feature request related to a problem? Please describe.
Have the mods been deleted? Yes. Then why is there still no lua support in the game?

# Describe the solution you'd like
return LUA.

# Describe alternatives you've considered
What alternatives do you need? Just let the players edit their game themselves.

**Comment by davidpwbrown** [comment]
no

**Comment by 12347654** [comment]
> no

why?

**Comment by davidpwbrown** [comment]
> > no
> 
> why?

 Stop.

**Comment by I-am-Erk** [comment]
On the off chance you're just a troll, because lua was one of the biggest sources of bugs in the game and it was a PITA to maintain.
