### ISSUE TITLE
Preoccupied enemies

### ISSUE THREAD

**Issue by Funguss** [CleverRaven/Cataclysm-DDA#37945]
Occasionally a zombie, or a group of zombies, will idle in a location for no obvious reason and ignore the player. This behaviour suggests that they're targeting enemies nearby, however in most situations I've been unable to identify any... unless they were on a different Z level. This has occurred with zombies targeting sewer snakes or rats in basements to zombies crowding beneath a floating wasps nests in the steel mill. There were no giant wasps in sight, but map editor revealed them all to be chilling at Z10, unconcerned with us ground crawlers.

# Steps To Reproduce

Basically wander about in a city until you see zombies that know you're there but just don't care.

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-12105-gda56791 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    No Rail Stations [No_Rail_Stations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Roadheader and other mining vehicles [Heavy miners],
    No Fungal Monsters [No_Fungi],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct]
]

**Comment by ashGlaw** [comment]
I’ve seen this behavior too
