### ISSUE TITLE
Actors rarely cross Z levels

### ISSUE THREAD

**Issue by Funguss** [CleverRaven/Cataclysm-DDA#37949]
Today I saw a zombie come up the stairs from the subway. First time in a loooong time I've seen anything use stairs. Their friends stayed milling around below. I have a suspicion the zombie only used those stairs as it had no idea I was there. Perhaps it's an issue with stairs and alignment - they'll not pathfind if there aren't properly aligned stairs. Then again, I think the subway stairs were aligned correctly...

# Steps To Reproduce

Try and kite some enemies up or down stairs. They won't do it.

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-12105-gda56791 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    No Rail Stations [No_Rail_Stations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Roadheader and other mining vehicles [Heavy miners],
    No Fungal Monsters [No_Fungi],
    Beta National Guard Camp [national_guard_camp]
]

**Comment by Dacendeth** [comment]
#30297 I reported some oddities about this a while ago, it seems enemies will investigate noise and come down stairs now but it's still it's very easy to just change z levels and most of the time nothing will follow you that had eyes on you. I too think it has something to do with alignment as some areas they will always follow you down, like the evac shelters with the stairs in the middle on both floors.

**Comment by Funguss** [comment]
Wow, it's been about this long? Can't believe it's taken me this long to notice. It's not a bug that's resurfaced?
