### ISSUE TITLE
Hold your breath

### ISSUE THREAD

**Issue by Funguss** [CleverRaven/Cataclysm-DDA#37955]
It's often bugged me that I can see a cloud of smoke, make a conscious decision to walk through it, yet I can't decide to hold my breath for a few seconds until it passes. With exploding smoker zombies I feel like this would also be a reasonable decision. Think you're gonna finish it with one last strike? Hold your breath and stab! It may or may not work, but it's a risk. I think this could be well balanced by penalties to stamina consumption based on adrenaline and a substantially increased malus if unable to hold your breath until the smoke clears or you clear the smoke. Perhaps a fit of unconsciousness? I'm no expert on smoke inhalation. I'm also not sure how this would play with toxic and radioactive gasses, I imagine they'd have an effect regardless, but possibly milder. 

A further consideration (for smoke from fires, at least) would be crouching, or crawling. Smoke from a fire rises due to thermal convection, so one of the tactics when escaping a house fire is to keep low to the ground, thus lowering your smoke inhalation. Currently smoke from house fires in CDDA is the least of your concern (contrary to RL I might point out) but if our simulation gets to the point where that's no longer true then I think introducing a crouching/ducking/crawling mechanic would be appropriate.

**Comment by GGgatherer** [comment]
We already have crouching mechanic in place, we just need to make it work with appropriate fields. To not make it OP, maybe divide smoke into thin smoke, which you can escape/reduce effect of by crouching, and thick smoke, which will choke you regardless.

**Comment by Funguss** [comment]
Haha yeah, that's what I meant, sorry for not being clearer. I'm just not sure that adding that effect to crouching would be the best solution. Regarding smoke thickness we already have different levels of smoke, too, though an issue with this is that crouching causes you to move slower, meaning the smoke may very well become thicker for a moment during which time your crouching will be nullified.

Maybe if holding your breath were a toggle but only occurred when actually in smoke, in a similar fashion to how safe mode only triggers if a hostile enemy is in sight. Feedback on when you start and stop holding your breath would be important in that case.
