### ISSUE TITLE
Vehicle tank shortcuts don't work

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#37962]
#  Steps To Reproduce

1. Try siphoning fuel from a vehicle.
2. Observe letters getting assigned for each tank.
3. Try pressing the keys.
4. Nothing happens.

# Expected behavior

Vehicle tank shortcuts working as they used to.

# Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.D-12174-gfd705dc3ca-dirty [64-bit]
- Graphics Version: Curses
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

# Additional context

**Comment by Ramza13** [comment]
Possibly related to #26467?
