### ISSUE TITLE
Vehicle construction does not accept wire

### ISSUE THREAD

**Issue by Funguss** [CleverRaven/Cataclysm-DDA#37970]
A simple thing that has bugged me for years. When building a vehicle out of wire you first need to use a frame which you later deconstruct, as wire is not a valid component in the construction menu. This should be included in the recipe.

**Comment by Kilvoctu** [comment]
@Soup-de-Loop as this is a vehicle part from blazemod.
Wire will need to be added as a possible component for "Start Vehicle Construction" by giving the `wiring` vehicle part the `INITIAL_PART` flag.

**Comment by Funguss** [comment]
Ah, that so? Is blazemod no longer supported then?

**Comment by Kilvoctu** [comment]
At the moment, blazemod is obsoleted, but it's being reworked by Soup in #37497 to be reborn after 0.E.

If you'd like to add this feature in the meantime, go to the blazemod folder and open blaze_other_parts.json. Then go down to the flags for `"wiring"`. It'll say something like:
`"flags": [ "FOLDABLE", "AISLE" ]`
change it to
`"flags": [ "INITIAL_PART", "FOLDABLE", "AISLE" ]`

**Comment by Funguss** [comment]
Ok, I thought "yeah, this is a simple fix, I should learn how to do a JSON PR at least" but I can't seem to find the tutorial. I'm pretty sure there's one out there? I don't suppose you have a link?

**Comment by Soup-de-Loop** [comment]
I hear and obey, thank you for bringing this up- I thought I knew the flag to add, but it’s still a fantastic attitude to have and it helps relatively newbie contributors like me feel a little less stressed trying to figure out what needs to be done. Should be committed within the hour.

**Comment by anothersimulacrum** [comment]
@Funguss You want this https://github.com/CleverRaven/Cataclysm-DDA/wiki/Guide-to-adding-new-content-to-CDDA-for-first-time-contributors

**Comment by Soup-de-Loop** [comment]
Change pushed to the PR, thanks for bringing this up! :+1:

**Comment by Saicchi** [comment]
Is this issue still valid?
