### ISSUE TITLE
Collapsible requirements breakdown toggle in recipe menu

### ISSUE THREAD

**Issue by Soup-de-Loop** [CleverRaven/Cataclysm-DDA#37984]
# Is your feature request related to a problem? Please describe.
As the number of tools and available components for providing something like `surface_heat` or something smaller like `meat_red` have become easier to add to and represent in recipes, the number of always-listed options in the recipe screen have been becoming increasingly bloated as having more options is starting to bloat the information displayed, which is increasingly limiting how many options we should add for a given component or tool for a recipe.

# Describe the solution you'd like
The ability to toggle recipe required components and tools into displaying the complete breakdown of possible options and charges/units OR simply the abridged requirements name those lists are mostly dependent on now with relevant charges/units, with a key, much like skills/time/dark crafting can be toggled with `m`. 

This presumably should allow a complete breakdown for a player to familiarise themselves with what each requirement represents in shorthand going back and forth, and as they become more familiar with each group use the unabridged form less and less. Additionally, provide less to read for the seasoned veteran who knows what they're looking for.

# Describe alternatives you've considered
1. Allowing recipe creep to continue as-is until user complaints are made.

2. Formalising a "sweet spot" limit for how many options we might have for a task, and limiting requirements and options included in the game based on this format.

# Additional context
Topic broached when talking about a potential contributor's plan to add more types of meat to the game based on different animals, and wrapping them into requirements to be used in recipes (link to fancord discussion on `mod-and-dev-general`: https://discordapp.com/channels/252365627543519232/365907426270117888/677351237020286976).

Screeenshot demonstrating already existant bloat creep from additional options represented after following code:
```json
  {
    "type": "recipe",
    "result": "bratwurst_sausage",
    "category": "CC_FOOD",
    "subcategory": "CSC_FOOD_MEAT",
    "skill_used": "cooking",
    "difficulty": 4,
    "time": "1 h",
    "autolearn": true,
    "batch_time_factors": [ 83, 3 ],
    "qualities": [ { "id": "CUT", "level": 1 }, { "id": "COOK", "level": 1 } ],
    "tools": [ [ [ "surface_heat", 7, "LIST" ] ] ],
    "components": [
      [ [ "meat_red", 2, "LIST" ], [ "can_chicken", 2 ] ],
      [ [ "edible_fat", 1, "LIST" ], [ "edible_tallow_lard", 2, "LIST" ] ],
      [
        [ "salt", 4 ],
        [ "soysauce", 2 ],
        [ "seasoning_italian", 4 ],
        [ "wild_herbs", 4 ],
        [ "seasoning_salt", 4 ],
        [ "pepper", 4 ]
      ]
    ]
  }
```

![2020-02-13 13_53_48-Cataclysm_ Dark Days Ahead - 0 D-12155-gb7876ca](https://user-images.githubusercontent.com/40143107/74400073-9f09b400-4e68-11ea-9e66-383a7f71d5d0.png)
Example of potential output provided by user DocGhast:
![compressed_mockup](https://user-images.githubusercontent.com/40143107/74402105-04f93a00-4e6f-11ea-8ae3-a52a4eaf36c9.png)

**Comment by scorpion451** [comment]
As a complement to this, it would be nice to see more transparency on charged tool qualities (IE, listing things like "Cooking heat source", "Can cut heavy metal", etc on relevant items in the same way as "level 1 boiling" and "Level 2 Welding") 

There's a lot of items that hide important information about their functions, like which of the welding items are able to cut down doors- it took me ages when I started out to realize that the mess kit had a hotplate, for instance.
