### ISSUE TITLE
Option to remove auto-generated number shortcuts from various item menus

### ISSUE THREAD

**Issue by WeaverThree** [CleverRaven/Cataclysm-DDA#37980]
# Is your feature request related to a problem? Please describe.
Movement keys are used as item hotkeys regardless of whether you have auto item letters on or off. I sometimes consume things accidentally because of this. Eventually, I'm going to accidentally drink bleach or something because of it.

It's far worse than accidentally messing up my advanced inventory screens because I forgot that numpad doesn't do cursor control there, and that has value in being that way.

# Describe the solution you'd like
An option in the interface settings that disables the generation of numeric hotkeys in the consume, eat, drink, medical, wear, wield, and disassemble menus, and any others I'm forgetting that have this feature: 

![cataclysm-tiles — 2020·02·12 — 14·44·06](https://user-images.githubusercontent.com/1582240/74384487-38bc5d00-4da6-11ea-913f-ce3aa4b44f84.png)

I think the numbers are only generated for stuff not in the inventory already? Since those would get letters under standard game options.

Also when this option is enabled I'd like the numpad to act as navigation keys for these menus, since there's then no reason for it to not.

# Describe alternatives you've considered
Some people probably want this so just getting rid of it is a bad solution.

Keeping dangerous items away from food might be doable but it depends on the space you're working with and how much effort you want to put into inventory sorting. And it doesn't prevent you from accidentally choosing the wrong thing that is edible.

**Comment by Funguss** [comment]
So you've never tried to drink bleach before?! Well done. FYI you get a confirmation dialogue, so it's not too bad. However, I've frequently eaten things I really didn't want to eat, e.g. uncooked microwave dinners (therefore having just one left, which you're unable to then cook). Eating raw eggs I was leaving to hatch has happened, too, amongst other things I can't recall. It would be nice to have the option to reconfigure them to letters as well, as they are incredibly convenient when the selection decides it's going to reset.

**Comment by scorpion451** [comment]
Being able to blacklist certain letters from auto-assigning in general would be nice, really- I'd leave the feature on if I could blacklist other problematic hotkeys like "e", "w", and "a".

**Comment by Funguss** [comment]
I often assign 'a' to something I apply often, e.g. lockpicks, and for 'w' I set my earplugs or blindfold, depending on. 'e' is for bandages. You could set 'w' to something you can't wear but always carry, and 'a' to something you can't apply. Personally, I prefer this set up. Blacklisting would be a good QOL feature though!
