### ISSUE TITLE
Hard tack takes too long to bake.

### ISSUE THREAD

**Issue by DocGhast** [CleverRaven/Cataclysm-DDA#37986]
# Is your feature request related to a problem? Please describe.
Hard tack currently takes an hour and thirty minutes to cook a single batch, after a discussion on the fan discord came up about it, a little research showed it should take nearly a third of that. Most recipes call for 25-35 minutes of baking, and less than ten minutes of preparation. 

# Describe the solution you'd like
A single batch of hard tack should probably take no more than 40-45 minutes. 

# Describe alternatives you've considered
Continue to spend an hour kneading dough for no reason. 

# Additional context
Just a few of the many sources showing how quick and easy it should be to make. Seems like it spends more time cooling off after baking than anything else. 
https://www.skilledsurvival.com/hardtack-recipe-survival-bread/
https://www.awm.gov.au/learn/schools/resources/hard-tack

**Comment by I-am-Erk** [comment]
I think this is underestimating prep time. Most recipes I found give a 70-90 minute estimate

**Comment by NickGrease** [comment]
> Seems like it spends more time cooling off after baking than anything else.

That's not an optional step. Storing hardtack (in a container) warm will spoil it. It must be free of moisture to store it in a container. The cooking times are meant to encapsulate the whole process, cooling is part of the process, either that or - hardtack that is stored in containers while its warm has its spoil time set to a few hours.

I agree the prep+cook time *could* be less than 45 minutes but at least one link above calls for the dough to rest for 30 minutes prior to forming/cutting. I'd be will to skip this step personally - but it is called for in more then one recipe I found.

**Comment by scorpion451** [comment]
That sounds like a severe overestimation. The only vaguely time-consuming part is poking holes in it, and that's an optional thing.

**Comment by I-am-Erk** [comment]
It's the majority of recipes. We generally believe things like published recipes over people asserting "nah I don't think so".

**Comment by scorpion451** [comment]
Even when said person has done this sort of recipe numerous times before?

Simply baffled as to where these recipes are getting the idea that it takes 40 minutes to pour flour, water, and salt in a bowl, knead it for a couple minutes, roll it out, section it, and poke some holes in it. There's a way more complicated cookie recipe my family does every year that uses a similar process (but splitting the dough into multiple layers that get different flavorings added into them) and that _maybe_ takes 40 minutes if we're doing three or four batches of a couple dozen each. 

The timing simply doesn't make sense from my practical experience.

**Comment by I-am-Erk** [comment]
The recipes I view assume twenty minutes or so to mix, kneed, roll, puncture, and slice, and give an hour of baking time. That sounds pretty reasonable to me, honestly.

**Comment by DocGhast** [comment]
There's no need to knead hardtack dough. Kneading is done to help create air pockets formed by the gasses released by the yeast. There is no yeast used in hardtack. 
 I can't find any recipes that call for more than 40 minutes of bake time. Most range from 25-35 minutes. 
But if you're sure this time is accurate, then perhaps the problem lies with regular bread only taking 20 minutes, despite it requiring kneading and time for the dough to rise before baking.

**Comment by I-am-Erk** [comment]
[Kneading is about agglutination](https://en.m.wikipedia.org/wiki/Kneading), it has nothing to do with yeast.

It's fair to argue that bread should have a longer cook time, for sure. Hardtack takes longer to make than a lot of bread though (notwithstanding rise times), as it has to bake until all moisture is out of the dough.

I don't know how you're not finding hour cooktimes. I got my results from the first several articles when I googled hardtack recipes

**Comment by DocGhast** [comment]
https://www.skilledsurvival.com/hardtack-recipe-survival-bread/  25-35 minute baketime. 
https://www.awm.gov.au/learn/schools/resources/hard-tack 30-40 minute baketime. 
http://cookit.e2bn.org/historycookbook/904-hardtack-ships-biscuits.html 30-40 minute baketime. 
https://www.foodstoragemoms.com/make-hardtack/ one hour baketime.
http://www.americantable.org/2013/06/civil-war-recipe-hardtack-1861/ four hour baketime. 
https://urbansurvivalsite.com/make-your-own-hardtack/ one hour baketime. 

These are my first six results. I guess it's just a matter of the luck of the Google draw.
