### ISSUE TITLE
"You can't crack a safe with earbuds on!"

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#37996]
# Describe the bug

Needless to say, I don't even have earbuds. I do have the stethoscope though.
e: also, sound dampening is off. also, survivor helmet isn't the culprit.

# Steps To Reproduce

Load [save](https://drive.google.com/open?id=194z3daLpnLRbCrxc5Sjba1Oyl7qJgyZ0), try cracking any of 4 safes, get the message.

# Expected behavior

Being able to crack the safe without getting obviously wrong message.

# Screenshots

![cataclysm-tiles_2020_02_13_21_04_30_177](https://user-images.githubusercontent.com/56833396/74443214-620fe280-4ea5-11ea-8349-5370a1dcb0ef.png)

# Versions and configuration

    OS: Windows 7x64
    Game Version: 0.D-12235-g3a8c5fb [64-bit]
    Graphics Version: Tiles
    Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills]
    ]

**Comment by anothersimulacrum** [comment]
Do you have an active mp3 player?

**Comment by wapcaplet** [comment]
This message is from my fix for #36013 but you shouldn’t be seeing it without an mp3 player on.

**Comment by JeanLucVanDamme** [comment]
Those last two options sound better for explaining the conflict.

Another option, why not include the conflicting device in the message?  "You can't crack a safe with earbuds on! (mp3 player - active)". Something like that, I'm sure there's a cleaner way to say it. Make the device name a different color to emphasize that it's the important part, and a variable, in the message.

**Comment by wapcaplet** [comment]
@JeanLucVanDamme I like the idea of indicating which device is active, but unfortunately it looks like I'd need to clutter the safe-cracking code with the same multiple device IDs we already have in the mp3 on/off functions.

I have submitted a PR #38003 that changes the message to "You can't crack a safe while listening to music!" - I hope this is a satisfactory fix.

**Comment by GGgatherer** [comment]
> I loaded up your savegame - your character does have an active mp3 player on. Perhaps the message could be clearer

Actually, that's more like my fault. Non-native English speaker here, so while I was reading (and later writing) ear*buds*, what I was actually thinking of was ear*plugs*, which is an actual in-game wearable item which my character didn't have. :facepalm.bmp:, I guess.
Nevertheless, I agree the message about listening to music will explain the situation much clearer.
