### ISSUE TITLE
Control laptop's IFF protocol override is too tedious to use

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#37997]
# Describe the bug

Sometimes it takes hundreds of trials to pull it off, but you have to spend at least 4 keypresses per each trial.

# Expected behavior

It would be nice if it could be used like a sewing kit: until success, target disappearance or battery emptiness.

# Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.D-12224-gb9b3901483-dirty [64-bit]
- Graphics Version: Curses
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

**Comment by mlangsdorf** [comment]
Since the control laptop is broken anyway and needs to get replaced by a better implementation, this is a less pressing issue but we do need to keep it in mind for the control laptop v2.
