### ISSUE TITLE
Uncanny Dodge spends too much energy on dodge

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#37995]
# Describe the bug

Its description says 6J activation and 6J per turn. And it's true... unless it actually procs, then it'll spend about 80kJ on evade (yes, not just 80J. Eighty **kilo**joules.)

# Steps To Reproduce

Make a character with UD and some energy storage, activate it near melee zeds, see what happens.

# Expected behavior

Either it shouldn't guzzle biopower like there's no tomorrow or it should say it does so in its description.

# Versions and configuration

- OS: Windows 7x64
- Game Version: 0.D-12235-g3a8c5fb [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by GGgatherer** [comment]
I've even found where it is coded, it's src/player.cpp:

`bool player::uncanny_dodge()
{
    bool is_u = this == &g->u;
    bool seen = g->u.sees( *this );
    if( this->get_power_level() < 74_kJ || !this->has_active_bionic( bio_uncanny_dodge ) ) {
        return false;
    }
    tripoint adjacent = adjacent_tile();
    mod_power_level( -75_kJ );
<...>`

It just spends 75kJ each time you u-dodge which is not mentioned *anywhere* in the game. It isn't even hinted at. So, the question remains - is it working as intended?

**Comment by jeremyshannon** [comment]
Yeah, that does kinda seem excessive. Maybe it was a typo and it was supposed to drain 74 joules per dodge?

**Comment by anothersimulacrum** [comment]
No type, Joules didn't exist when the bionic was added, and nobody updated costs since.

**Comment by GGgatherer** [comment]
So I've been thinking about it from "realism" standpoint, and realized that current proc cost isn't so high as it seems.
First, some assumptions:
1) 1 tile equals to 1 meter. If there's exact figure somewhere in the code, feel free to correct me.
2) As UD makes you to evade each and every melee attack, let's say it makes you move away in 0.1 second.
3) For sake of brevity let's assume you accelerate to top speed in half a time, then spend another half "braking" to 0 speed.

Now, some physics
```
s=a*t^2/2 --> a=2*s/t^2
v=a*t=2s/t
e=m*v^2/2=2m*(s/t)^2  /*"m" is survivor's weight + all the gear's weight*/
```
So, kinetic energy you have to accumulate in that 0.05s is 2*m  * (0.5/0.05)^2 = 200m. So even for unencumbered, average weight survivor it'd be about 10-12kJ. Now, judging by UD's description, it doesn't actually spend energy to move you out of the way, it just makes the time flow faster so you have time to assess how exactly to evade. 
But then again, that energy still have to come from somewhere, and in this case it is your calories reserves, but I guess modifying hunger levels would be too much of a hassle so probably better leave it as bionic energy drain.
Anyway, what I am trying to say is even if 75kJ is way high, it shouldn't cost mere joules to evade any and all melee attacks (and even bullets, if you believe UD's description, in which case timeframes should be way way less than 0.1s and energy required would jump into megajoules). Maybe 10kJ per proc?
