### ISSUE TITLE
Error while butchering while too far from corpse

### ISSUE THREAD

**Issue by bug-sniper** [CleverRaven/Cataclysm-DDA#38008]
# Describe the bug

Resuming butchering while not near corpse is allowed to happen, and produces an error. "Tried removing part from object which did not contain it"

# Steps To Reproduce

1. Start butchering a corpse (I was dissecting, but I think field dressing also does this)
2. Get interrupted by an approaching zombie
3. Run away
4. Kill all nearby zombies
5. Catch your breath
6. When given the dialog option to do so, continue butchering

# Expected behavior

You're not allowed to continue butchering, or you walk back and continue

# Screenshots

# Versions and configuration

Unknown. Played on watchcdda.net.

# Additional context

Screenshot attached.

![Screenshot from 2020-02-13 21-50-36](https://user-images.githubusercontent.com/6971612/74505451-ff6e1500-4eab-11ea-91ef-ffaceb9faf5a.png)

**Comment by r7st** [comment]
Version: 0.D-12206-gd134d6e63b

**Comment by jkraybill** [comment]
For these steps, can you please give more detail for reproduction?

> Catch your breath
> When given the dialog option to do so, continue butchering

What command are you issuing to get the "dialog option to do so"? I would like to reproduce and document this issue but it's unclear how I do so.

**Comment by r7st** [comment]
bug-sniper, if you are able to replicate this I could pull the save and share it.

**Comment by bug-sniper** [comment]
Does that dialog option not show up? Maybe you automatically continue butchering after you catch your breath.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
