### ISSUE TITLE
Deadened mutation: inconsistent prevention of showing limb health values

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#38015]
# Describe the bug

I have a character with this mutation. She also have Self-aware as a starting trait. In sidebar, limb status is shown as "good". I asked in forum, and people say Deadened overrides Self-aware for purpose of knowing exact limb health, you can only see either "good" or "damaged"(or w/e). Okay, fine, I guess?
...No. If I try using bandage or antiseptic, the menu with limb choice will show exact health values instead of "good" (or stick indicators).
So, the question is: what is the bug exactly? Deadened overriding Self-aware in sidebar, or bandage/antiseptic usage menu showing exact numbers while it shouldn't?

# Steps To Reproduce

1. Make a character with deadened+selfaware and a bandage
2. Look at the sidebar, see "good"
3. Try using the bandage, see exact limb health

# Expected behavior

Either it should override SA everywhere, or it should not apply at all.

# Versions and configuration

- OS: Windows 7x64
- Game Version: 0.D-12235-g3a8c5fb [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by KorGgenT** [comment]
When you're bandaging yourself, you're specifically examining yourself for first-aid. The sidebar is your general knowledge of how you're doing at that very minute.

**Comment by Funguss** [comment]
Hmm. Does that mean high first aid skill should expose the actual HP of a limb regardless of self aware? As it stands it seems odd to be able to see NPC limb HP but not your own. NPC HP could do with obscurity anyway but I do like the idea of first aid having this effect.

**Comment by GGgatherer** [comment]
> 
> 
> When you're bandaging yourself, you're specifically examining yourself for first-aid. The sidebar is your general knowledge of how you're doing at that very minute.

Except you don't know your exact limb health without self-aware, you only see stick indicators.
Also, somehow you do see exact numbers in sidebar if you aren't deadened... without "specifically examining yourself for first-aid".

**Comment by KorGgenT** [comment]
sure, but self-aware is very gamey and if i were the one to make the choice i'd remove it entirely as totally unrealistic in the first place. you don't know your exact limb health do ya? but you know when you have scratches or a broken arm

**Comment by GGgatherer** [comment]
Self-aware isn't the topic though. You may as well not have SA, and still Deadened character will see only "good/damaged" in sidebar but first aid menu will still show stick indicators.
PS. "When you're bandaging yourself, you're specifically examining yourself for first-aid" - sorry, this excuse doesn't work because it takes 0 in-game time to open this menu and see you limbs status. May as well just put it into sidebar as well.
