### ISSUE TITLE
Secondary experience

### ISSUE THREAD

**Issue by roaringjohn** [CleverRaven/Cataclysm-DDA#38013]
# Is your feature request related to a problem? Please describe.
It seems that secondary skill requirements don't get experience in recipes.

# Describe the solution you'd like
Allow secondary skill requirements to gain (significantly?) reduced experience from recipes, probably depending on the skill. For example, one should not get exp for archery if it's a secondary skill requirement, but one should get exp for cooking.

# Describe alternatives you've considered
Allow multiple main skill requirements?

**Comment by ifreund** [comment]
What should happen imo is that skill gain is proportionate to the impact of the skill on failure chance.  This would mean that same amount of total xp is gained, but distributed among the skills.  With the current numbers this would mean 75% of xp goes to the primary, and the remaining 25% is distributed evenly between the secondary skills.

changes should be isolated to this function: https://github.com/CleverRaven/Cataclysm-DDA/blob/3ea66e7c2a3ed488f9825deb7cbad22d0c797beb/src/crafting.cpp#L800

**Comment by roaringjohn** [comment]
Keep in mind that one should probably want to put in more work than what ifreund suggested, as it makes no sense for combat skills to get xp from crafting. For this, ifreund said on Discord:

> yeah you could special case it, i think we already have some conception of skill categories
> if that route is taken it might make sense to apply the same special casing to failure chance as well

**Comment by kevingranade** [comment]
As you note with archery skill when making as arrows, some secondary skills should not be gaining xp.

The intent is that secondaries act as prerequisites, but are not exercised as part of the craft.  If you want to change this to mean, "skills also exercised by the craft", we need to overhaul a lot of recipes.  Step one would be to blanket remove all combat skills from crafting recipes, which I would fully support.  After that you need to audit the remaining secondaries for whether each recipe provides meaningful practice for that skill, or if it just acts as a prerequisite.  If both of those are occurring in meaningful numbers, we can split secondary into two parameters, with the new one being "prerequisite_skill".

**Comment by scorpion451** [comment]
I could see justification for combat skills getting some experience from lower level recipes, representing learning how to properly maintain and handle the equipment. (Learning how to properly string and store a bow, how to align a gunsight, getting a feel for weapon balance as you craft them, that sort of thing)

**Comment by GGgatherer** [comment]
> 
> 
> I could see justification for combat skills getting some experience from lower level recipes, representing learning how to properly maintain and handle the equipment. (Learning how to properly string and store a bow, how to align a gunsight, getting a feel for weapon balance as you craft them, that sort of thing)

To me, what you're describing looks more like "allow any recipe to train combat skills but up to a set skill level". Like 1 or 2, maybe.

**Comment by KorGgenT** [comment]
we'd definitely need some kind of flag to stop this, as all of my recipes in magiclysm that have spellcraft as a secondary skill are purposefully like that so spellcraft doesn't gain exp.

**Comment by TechyBen** [comment]
> I could see justification for combat skills getting some experience from lower level recipes, representing learning how to properly maintain and handle the equipment. (Learning how to properly string and store a bow, how to align a gunsight, getting a feel for weapon balance as you craft them, that sort of thing)

And balance. Forging a sword would give a lot of knowledge to balance, gait and pose for the sword. Not for much fighting, but for the beginning levels of knowledge and skill.

Who's more dangerous, an experienced builder with a sledge hammer, or a novice swordsman on the first day?

**Comment by kevingranade** [comment]
This was more of a discussion than an issue,  and it has gone stale with no real conclusion.
