### ISSUE TITLE
Magiclysm Old Magus quest crash

### ISSUE THREAD

**Issue by Funguss** [CleverRaven/Cataclysm-DDA#38025]
After accepting the Old Magus' first quest you can speak with him again and select "is there anything I can help you with?" Doing this causes a CTD.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-12105-gda56791 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    No Rail Stations [No_Rail_Stations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Roadheader and other mining vehicles [Heavy miners],
    No Fungal Monsters [No_Fungi],
    Beta National Guard Camp [national_guard_camp]
]

# Additional context

The quest dialogue implies that another NPC should spawn somewhere in the world holding the quest item, but after looking at the JSON it seems this isn't the case. Due to the difficulty of finding any specific spellbook (finding ANY is already pretty hard) the mission should probably generate one, either in the possession of an NPC or with some other way of ascertaining it's location.

**Comment by KorGgenT** [comment]
a save would be really convenient if you have one

**Comment by Funguss** [comment]
Sure thing, here you go! Sadly I'd already accepted the quest prior to saving.

[Dunmore - Copy.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4207764/Dunmore.-.Copy.zip)

**Comment by Funguss** [comment]
@KorGgenT Not sure if this is useful to you, but here's the save prior to accepting the quest. Just keep asking for quests to trigger it. [Shadeland.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4272398/Shadeland.zip)
