### ISSUE TITLE
Auto-drive fails for boats

### ISSUE THREAD

**Issue by Funguss** [CleverRaven/Cataclysm-DDA#38027]
When trying to auto-drive a boat there are three big issues:

1. Path is calculated horizontally and vertically, rather than taking as straight a course as possible.
2. Very, very frequently the boat will try to avoid a non-existent obstacle, or perhaps it's surfacing fish. This results in the boat reversing and auto-drive being cancelled.
3. Boats will drive onto land and become immobile. When this happens auto-drive continues, resulting in spam and wasted time.

These issues aren't limited to boats, however boats are more susceptible to them. Road navigation at bends or forks can result in diagonal movement, but this also entails a lot of superfluous turning and speed changes. Obstacles tend to result in the vehicle coming to a halt with reverse set to max before returning control, leading to greatly reduced fuel efficiency. For vehicles powered by renewables this isn't a huge deal, but it still can lead to adverse situations (dead stop and reversing when encountering hostiles may be significantly more dangerous than swerving and going off road).

# Expected behavior

1. Boats need to avoid running aground in the first place, but if a vehicle hasn't got enough wheels to move auto-drive should give up.
2. Vehicles seem to be obsessed with staying in the centre of the map tile rather than taking a holistic approach. Inanimate objects should be navigable, given space. Animate should likely depend on threat, proximity, path and persuasion. E.g. Fleeing creatures that are on a path that will take them out of the vehicle's path should probably be ignored, or while sailing a boat all neutral fish and birds should be ignored.
3. Pathfinding on the overmap should result in a trajectory based on the directions available to a vehicle. In order to travel in this way point 2 would need to be cleared, I imagine.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-12105-gda56791 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by KorGgenT** [comment]
the three things you mentioned might be better to be three separate issues, as they'd be separated out into three separate PRs.

**Comment by Funguss** [comment]
Oh no :fearful:

**Comment by KorGgenT** [comment]
it's not a huge deal. i appreciate the bug report and it's thorough, though it has a feature request or two in here too, which are equally as valid but as feature requests not bug reports

**Comment by Funguss** [comment]
I get it, I just get sick of writing and formatting bug reports. I'll get around to it eventually... :face_with_head_bandage:

Plus I have an aversion to swamping the issue list, even though I prefer to keep a text file for bugs then do them all at once. Hypocrite!

Thanks for the feedback, I'll be more mindful in the future.

**Comment by wapcaplet** [comment]
The new auto-drive features added in #49772 and its adjuncts now handle amphibious vehicles and boats, as well as the other pathing issues you mentioned. Closing as resolved.
