### ISSUE TITLE
River meets lake bad mapgen

### ISSUE THREAD

**Issue by Funguss** [CleverRaven/Cataclysm-DDA#38036]
Segment of map that's turned out quite, quite wrong. In case it's not obvious from the map, the affected overmap square is Lake Shore, adjacent to River Bank on the east and Lake Shore to the south. Field to N, NW, W, Lake to SE.

# Screenshots

![riverlake](https://user-images.githubusercontent.com/57632331/74584387-a09ebd80-4fc9-11ea-862d-92e3c1534818.png)

# Versions and configuration
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-12105-gda56791 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    No Rail Stations [No_Rail_Stations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Roadheader and other mining vehicles [Heavy miners],
    No Fungal Monsters [No_Fungi],
    Beta National Guard Camp [national_guard_camp]
]

**Comment by wapcaplet** [comment]
Related to #36630
