### ISSUE TITLE
Ethanol burner fills nearby buildings and vehicles with hot air

### ISSUE THREAD

**Issue by DavisBroda** [CleverRaven/Cataclysm-DDA#38057]
# Describe the bug

When ethanol burner is turned on for a while, and then deactivated, nearby buildings end up filled with hot air, raising the temperature well above survivable ranges.

# Steps To Reproduce

1. Ensure a reasonable chunk of bionic power is missing, so ethanol burner can activate (~ 100 should be enough)
2. turn on ethanol burner while standing outside
3. let ethanol burner run for a while
4. turn off ethanol burner
5. check nearby buildings, and find them filled with hot air 4, and well above survivable temperatures

# Expected behavior

Temperature/hot air should either not persist beyond turning the burner off, or should only persist in the immediate vicinity of the player (the same room they were in for instance). 

# Screenshots

Here's the setup I used. PC stood outside the entire duration of the test, and did not move from his square

![cdda_burner_setup](https://user-images.githubusercontent.com/15205060/74598236-ef853b00-503b-11ea-8059-6f3d7bee0d4c.PNG)

# Versions and configuration

- OS: Windows 10
    - OS Version: 10.0 1809
- Game Version: 0.D-12289-g26b2614 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

Based on the fact that every tile in view has hot air 4 when the player activates the ethanol burner (or maybe while they have the heated condition) it appears that the actual implementation of the heat effect is to just generate hot air in every visible tile, and then either delete it when done, or wait for it to disperse naturally (I am unsure how hot air works). However they appear to have neglected to delete it in buildings (or forgotten that it will not disperse naturally in buildings).

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/time-delay-on-ethanol-burner-heat/22718/3

**Comment by jkraybill** [comment]
Probably a good idea to try reproducing this after #38020 is merged. It was hopefully going to fix #37586, which has been hard to reproduce for several of us but sounds closely related to this one.

**Comment by DavisBroda** [comment]
This issue seemed to have been fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/38020, as I can no longer reproduce this

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/constantly-cold-feet/24254/11
