### ISSUE TITLE
No front view in the car so i can not driver car 

### ISSUE THREAD

**Issue by hunjixin** [CleverRaven/Cataclysm-DDA#38054]
# Describe the bug
No front view in the car so i can not driver car 

# Steps To Reproduce
Just enter a car and you'll find that you can only see the contents of the car

# Expected behavior
It should be able to see the front through transparent glass

# Screenshots

# Versions and configuration

![2020-02-16 09-48-48屏幕截图](https://user-images.githubusercontent.com/41407352/74597877-8df7b780-50a1-11ea-9858-7f6abd7edf84.png)

![2020-02-16 09-49-16屏幕截图](https://user-images.githubusercontent.com/41407352/74597887-9ea82d80-50a1-11ea-8537-a507c490ce0f.png)

# Additional context

version: 0.D -12235-g3a8c4fb transifex
os: ubuntu16.04

**Comment by anothersimulacrum** [comment]
Are you crouching?

**Comment by ZhilkinSerg** [comment]
Yeah, change move mode to walking.
