### ISSUE TITLE
Crafting canned fruit juice yield's plastic bottles of fruit juice.

### ISSUE THREAD

**Issue by sharkfinsouperman** [CleverRaven/Cataclysm-DDA#38060]
# Describe the bug

I crafted six cans of fruit juice using raspberries at a vehicle workbench, six medium cans were consumed and six plastic bottles of juice were left on the workbench.

I crafted two more medium cans and repeated the process using strawberries, getting the same result.

# Steps To Reproduce

Craft canned fruit juice using fresh fruit.

# Expected behavior

Medium cans of fruit juice.

# Screenshots

NA

# Versions and configuration

Build 10309
Win7
Mod: No Fungal Creatures

# Additional context

NA

**Comment by jkraybill** [comment]
Good catch. Affects four recipes I could find: apple cider, OJ, cranberry juice, and fruit juice.
