### ISSUE TITLE
Flying corpses / science team corpses spawned on Z+1 level above ground in the air

### ISSUE THREAD

**Issue by Drakasin** [CleverRaven/Cataclysm-DDA#38066]
# Describe the bug

Upon climbing on top of a building, noticed that there are science team corpses flying above the ground.

# Steps To Reproduce

Be (un)lucky

# Expected behavior

Corpses and loot spawn on the ground or on the roof of the building instead of up in the air unbound by gravity.

# Screenshots

![obrazek](https://user-images.githubusercontent.com/6567381/74605566-906e0780-50c9-11ea-9d51-e0503521af7c.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.D-12303-g790301c [64-bit] (in launcher as Build #10335)
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

[Sulphurdale.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4209793/Sulphurdale.zip)

**Comment by shadowsapex** [comment]
clearly some things are beyond human understanding

**Comment by Funguss** [comment]
I've seen a floating wasps nest above a steel mill. It seems that some specials are spawning on higher Z levels but aren't checking there's space for them.

I actually quite like the idea of the corpses / items falling down and being damaged instead of not spawning on air. Would make it seem like something really rough went down.

**Comment by Mister-Cultist** [comment]
it's just reality falling apart due to the cataclysm, nothing to see here

**Comment by Drakasin** [comment]
![obrazek](https://user-images.githubusercontent.com/6567381/75095423-d2e58780-5594-11ea-8792-70db5387df3b.png)
If only there existed Gravity Gun in this game...

**Comment by GennFaol** [comment]
I can confirm this is still an issue as of experimental 10354. I debugged in metal grates to reach the items.
![TakeThatIsaac](https://user-images.githubusercontent.com/60406715/75111918-1dbbd980-563f-11ea-8aaa-f7bb592b2244.png)

**Comment by Funguss** [comment]
Yeah, and I've got burned ground on top of a zoo, in a place where there's nothing to burn.
