### ISSUE TITLE
Crafting canned juice yield's product with varying caloric and nutritional values.

### ISSUE THREAD

**Issue by sharkfinsouperman** [CleverRaven/Cataclysm-DDA#38071]
# Describe the bug

Batch crafted four jars of juice using raspberries, three cans using strawberries, and juice in the normal manner using huckleberries which were stored in two glass bottles.

While the batch of juice in the glass bottles is constant, the other two are not.

# Steps To Reproduce

Batch craft juice in cans and jars using fresh fruit.

# Expected behavior

Juice crafted from a single stack of fruit should produce a consistent end product.

# Screenshots

![image](https://user-images.githubusercontent.com/61106669/74609061-5e05df80-50b4-11ea-8e29-77969f76af88.png)

# Versions and configuration

Build 10309
Win7
Mods: No Fungal Creatures

# Additional context

Note: The plastic bottles of juice are the result of issue #38060.

**Comment by sharkfinsouperman** [comment]
I just noticed they also have different nutritional values even though they were batch crafted from a single stack of fresh fruit.

**Comment by TechyBen** [comment]
The difference from different berries/fruits/foods is working as intended AFAIK. When it comes to stacks, are these multiple ages/qualities, but not displayed to the player? I guess they'd need to be tested in debug mode with values?

**Comment by sharkfinsouperman** [comment]
It was my mistake in not being clear enough. 

I had picked the fruit minutes before crafting each different batch, and I used different fruit for each batch to see if the bug was restricted to specific fruit.

The nutritional difference isn't between different fruit, its between juice from the same kind of fruit, from the same stack, resulting from the same batch craft.

To keep the results current to any game changes made, I have updated my game to 10336 in order to include the recipe change ( #38060 ), harvested two new batches of fruit, batch crafted four cans of juice using Rose hips, and batch crafted four jars of juice using Pears.

Here is the freshly harvested fruit to be used in my inventory:
![image](https://user-images.githubusercontent.com/61106669/74688640-1c556180-51a6-11ea-86a9-bb15eec1078e.png)

Here is a comparison between the two most extreme cases from the batch of four cans:
![image](https://user-images.githubusercontent.com/61106669/74688912-1744e200-51a7-11ea-8b6d-746ede7227cb.png)

Here is a comparison between the two most extreme cases from the batch of four jars:
![image](https://user-images.githubusercontent.com/61106669/74688965-52dfac00-51a7-11ea-9031-9f4b3274447f.png)

From the above images, you see there is a difference between calories and vitamin C content, and in one case the vitamin C content is a negative value.

I hope this helps clear things up.

**Comment by jkraybill** [comment]
@sharkfinsouperman thanks for the excellent notes. This was a bug that would affect any future recipe that has charges, has variable inputs/calories, has by-products, and is batch-crafted. The issue is that the by-products "build up" during batch crafting and their nutrients get deducted from each produced item. So the first item has the right nutrients, but each subsequent item has insufficient nutrients off by the amount of byproducts (in the case of fruit juice, the pulp).

I submitted a fix that works, hopefully it passes code review :)
