### ISSUE TITLE
Zombie corpses cannot be quartered

### ISSUE THREAD

**Issue by Dacendeth** [CleverRaven/Cataclysm-DDA#38078]
# Describe the bug
You cannot quarter zombie corpses because they cant be field dressed now, and it requires that.

# Steps To Reproduce
Try to quarter a zombie with the butcher menu

# Expected behavior
To either be able to quarter it without the field dressing, or for the option to not be selectable  since it never can function.

# Screenshots
![image](https://user-images.githubusercontent.com/26881007/74614034-388fca80-50e2-11ea-864a-153f96b68bc0.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-12276-ge182e64 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    sees-player icon, retrodays [sees_player_retro],
    Classes and Scenarios Mod [more_classes_scenarios],
    Alternative Map Key [alt_map_key],
    Urban Development [Urban_Development],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Beta National Guard Camp [national_guard_camp],
    No Rail Stations [No_Rail_Stations],
    Magiclysm [magiclysm],
    Bionic Slots [cbm_slots],
]

# Additional context

**Comment by Amariithynar** [comment]
For what reason do you want to quarter them? If for things like kevlar hulks so you can butcher them, you can skin them individually instead. If it's just to drag them into place to full butcher them, you can just use the "\" key by default to drag them into place.

I agree that quartering shouldn't require field dressing, though, and should destroy any harvestable organs (like how quartering before skinning results in destroyed skin).
