### ISSUE TITLE
Dismissed NPC's don't do anything

### ISSUE THREAD

**Issue by jkraybill** [CleverRaven/Cataclysm-DDA#38083]
# Describe the bug

If you have an NPC join you, and then you dismiss them, they awkwardly hang around in the same spot for eternity, doing nothing other than yawning and acting tired.

EDIT: this is possibly specific to the "More Locations" mod, more info to come.

# Steps To Reproduce

Find an NPC.
Recruit them.
Bring them back to your base and then dismiss them from your party.
They just stay there forever and act tired most of the time, leading to awkwardness and occasional regret.

# Expected behavior

Dismissed NPC's should probably just leave the area and go somewhere else? At least they should behave less awkwardly, occasionally moving and taking care of their needs.

A cheap solution may be for dismissed NPC's to seek their starting / recruited position after dismissal?

# Screenshots

Poor Chet Corrigan has been hanging out in my kitchen for days, doing nothing but rubbing his eyes and making things awkward. He was recruited from a nearby apartment tower before I decided I wanted to keep things solo.

![image](https://user-images.githubusercontent.com/1361701/74640137-35204000-51c3-11ea-9f33-729115e7554f.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-11809-g78e6e40 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    More City Locations [cityside],
    Urban Development [Urban_Development],
    No Fungal Monsters [No_Fungi]
]

# Additional context

I understand there are many deficiencies with NPC behaviour, but this one seems like it could be some low-hanging fruit. Feel free to close this if it's a duplicate of an issue or upcoming project!

**Comment by Funguss** [comment]
This may be an issue solely with the NPCs from More Locations. I never gave it much of a chance (I really don't like the mod) but from what I recall those NPCs in apartment towers have an error or two. If I ever get an NPC in my current game I'll test it out.

**Comment by jkraybill** [comment]
@funguss definitely possible, I'll do more testing and log some more info!
