### ISSUE TITLE
Auto-drive in car does not avoid basic obstacles

### ISSUE THREAD

**Issue by jkraybill** [CleverRaven/Cataclysm-DDA#38081]
# Describe the bug

When doing auto-move in a car ("W" on overmap), my car was cruising at a speed of around 56mph, and smashed into a regular-sized wreck in the middle of an otherwise open section of road.

In trying to do basic repros in basic cars, I found that more often, the behaviour is to approach the wreck, come to a stop, and then say "Auto-drive cancelled." (Screenshot 1.)

I suspect the difference is in vehicle weight and acceleration/deceleration speed. My accident occurred in a very heavy hotted up SUV with military armor and a V8.

I couldn't reproduce the crash using a military APC, but could easily reproduce the "Auto-drive cancelled" issue. It was pretty easy to reproduce crashing into boulders when doing auto-move on off-road terrain.

I was able to reproduce the crash with an atomic sports car auto-driving down a straight road into a wreck (screenshot 2).

# Steps To Reproduce

Find a section of road that has a wreck in it, and try to automove through it. Or go off-road and auto-drive somewhere that has a bunch of boulders.

# Expected behavior

Auto-drive should never crash into stuff that the user could have at least stopped the vehicle in front of; ideally, auto-drive should navigate around obstacles including crashes and boulders if there are nearby obstacle-free areas.

# Screenshots

![image](https://user-images.githubusercontent.com/1361701/74632231-ff735b00-51b2-11ea-8310-4c727c9d4690.png)

![image](https://user-images.githubusercontent.com/1361701/74632753-36963c00-51b4-11ea-8df8-53767068b660.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-12212-g532719ea83-dirty [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

#38027 is obviously related but I'm not including boat behaviour in the scope of this report.

"Dangerzone maps" (#36983) doesn't solve this issue, in fact it appears to make auto-driving through a road section marked as dangerzone impossible -- after I marked a wreck as dangerous, I couldn't get a path through/around that section.

**Comment by davidpwbrown** [comment]
95% of the time, the vehicle stops when detecting an obstacle, in my experience, the longer/faster the vehicle is, the more risky it can be.

Ideally yes, we'd want the vehicle to navigate around obstacles, this is a hard problem. I am not up to it, I've left the autodrive system where it is, as I just cannot take it any further, as it starts getting very mathy, I would welcome anyone who wanted to approach that area though.
