### ISSUE TITLE
"Updated vehicle dragging" update broke how it worked

### ISSUE THREAD

**Issue by Shibimon** [CleverRaven/Cataclysm-DDA#38104]
Probably works the same with other vehicles but im just testing it and its the exacly same drag a "cart" with casters or without, it just take loads of time and spam "it takes some time to move the vehicle" messages.

1 Find or craft a vehicle that can be dragged and has casters as wheels (like a shopping cart)
2 Drag it.
3 Remove the casters and compare.

Expected behavior:
Casters should work, dragging vehicles was working nice before the update that broke them.

![imagen](https://user-images.githubusercontent.com/43771067/74679025-64bb5200-519b-11ea-95ed-22b1c7631cdb.png)

Versions and configuration:
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-12348-g9aa8765 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    No Fungal Monsters [No_Fungi],
    Vehicle Additions Pack [blazemod],
    No Ants [No_Anthills],
    Garden Pots [growable-pots],
    SpeedyDex [speedydex],
    Manual Bionic Installation [manualbionicinstall],
    Safe Autodoc [safeautodoc]
]

**Comment by Funguss** [comment]
To get your version information and modlist in a convenient format go to the debug menu, select game info, then choose the last item in that menu. Something along the lines of "save report to clipboard". Then you just have to paste it!

**Comment by Shibimon** [comment]
Thanks, i updated the original post

**Comment by wapcaplet** [comment]
I'm seeing the same behavior with a folding cart - it takes the same amount of time to move, whether it has wheels or not:

- Without casters: Rolling drag = 1.32
- With casters: Rolling drag = 0.52

Either way, it takes 323 moves (~3-4 seconds) to push or pull the cart:

![image](https://user-images.githubusercontent.com/238395/74784905-39516980-5266-11ea-84b7-4b8bf97d3b83.png)
