### ISSUE TITLE
Text problem

### ISSUE THREAD

**Issue by Drimday** [CleverRaven/Cataclysm-DDA#38102]
Good day, starting from about the 10320 version of the problem with the text - instead of the text there is an empty black place. Not only in the menu, but in the game itself, it is impossible to play. But this is only if the system language is installed (I have Russian). When I translated into English, French, Polish and some others, the text was. As I understood a similar problem with the Chinese language - it simply is not in the choice of language, there is an empty place. A similar problem did not exist in the 10310 version and earlier.
OS: Windows 7
Game Version: 0.D-12315-g1e0a3b3
Thank you for your attention, I apologize for possible errors - I do not know English, and I use a translator.
![test](https://user-images.githubusercontent.com/61161035/74678353-cc899100-51cb-11ea-9220-18ad5745f87e.jpg)

**Comment by ifreund** [comment]
should be fixed by #37919, which was merged a few hours ago

**Comment by Drimday** [comment]
I apologize, I downloaded the latest version that is, the problem is fixed. Sorry for the noise.

**Comment by ifreund** [comment]
no problem, better than a bug going unreported.

**Comment by Drimday** [comment]
I apologize, I downloaded the latest version that is, the problem is fixed. I apologize for the noise.
