### ISSUE TITLE
Duping Glitch in O.D

### ISSUE THREAD

**Issue by MathTauAthogen** [CleverRaven/Cataclysm-DDA#38101]
# Describe the bug

There's an easy way to dupe items, if you're willing to die. This even works on worlds set to reset after death.

# Steps To Reproduce

1. Have an inventory full of the stuff you wish to dupe
2. Save the game
3. Die, and go all the way to the grave screen
4. Use CTRL-C to quit CDDA
5. Re-enter CDDA and reload the save
6. See that your inventory still has the stuff from the save but there is now the same set of items sitting where you died

# Expected behavior

Only one copy of the inventory should exist, for obvious reasons.

# Screenshots

![Screenshot from 2020-02-17 13-16-04](https://user-images.githubusercontent.com/34319964/74678289-95de5700-5188-11ea-824b-f5fa9a229277.png)

# Versions and configuration

 - OS: Ubuntu 18.04
 - Game Version: 0.D
 - Graphics version: Terminal
 - Mods loaded: Standard, no mods

# Additional context

N/A

**Comment by ifreund** [comment]
Not a valid bug, see #12602
