### ISSUE TITLE
Magiclysm: Spellcraft skill gain not affected by skill training speed option

### ISSUE THREAD

**Issue by Funguss** [CleverRaven/Cataclysm-DDA#38116]
Spellcraft skill isn't modified by the skill training speed in the debug options menu.

# Steps To Reproduce

Set Skill Training Speed to some extreme figure, e.g. 0.01 or 100. Read a scroll. Do a control case if you're not convinced.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-12105-gda56791 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    No Rail Stations [No_Rail_Stations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Roadheader and other mining vehicles [Heavy miners],
    No Fungal Monsters [No_Fungi],
    Beta National Guard Camp [national_guard_camp]
]

**Comment by KorGgenT** [comment]
did you make sure that the scroll you were reading had a difficulty above the spellcraft skill you were trying to level?

**Comment by Funguss** [comment]
Aha, right, I didn't realise just how fast it normally is. That is really is a bit too fast, I think. I play at 0.1x and that felt like 1x training skill speed to me. My fault, I should have tested it at 0.01x before posting!
