### ISSUE TITLE
Magiclysm: spell book iuse should have extra requirements

### ISSUE THREAD

**Issue by KorGgenT** [CleverRaven/Cataclysm-DDA#38112]
# Is your feature request related to a problem? Please describe.
spellbooks are basically a one-and-done deal right now: you find a spell book, and it's the only one you need for that spell. i'd like a bit more variety and limitations, in order for it to make sense for spellbooks to be much more common.

# Describe the solution you'd like
I would like additional json members in the spell learning iuse that have minimum and maximum spell level known in order to use it. Example: you find a spell scroll that you can study with magic missile 0-5; this means it can teach you the spell and that you can use this scroll to learn the spell up to level 5.
requirements:
1. the spell study/learning activity must respect these values. level 0 is a good representation of "this spellbook can teach the spell if you don't know it"
2. the study spell uilist must show these values 
3. the item must show these values in the iteminfo
4. there must be reasonable feedback about why you cannot learn the spell if you don't meet these requirements

# Describe alternatives you've considered
i considered #37306 but i've decided that i don't like that implementation idea.

# Additional context
when writing the feature, it's a really good idea to have a couple of examples json items for easy testing. also, if noone else picks this up, i'll pick it up later.

**Comment by AndrewMcKinney** [comment]
Perhaps spell books could be divided into different authors.

ex: after spending many hours pouring over the notes of Prof X, your knowledge can only be increased by Prof Y or Prof Z's perspective. 

Knowledge of the different perspectives provided by the various academics would be the only way to get a skill to it's max level.

I feel this has the advantage of differentiating spell books from the logic of regular skill books.

**Comment by KorGgenT** [comment]
did some starting work on this, but ran into some unexpected roadblocks for a bit. also nested containers is taking up a lot of my brainspace. commenting here to bump it because i did in fact get some work done though
