### ISSUE TITLE
NPCs should help when moving furniture

### ISSUE THREAD

**Issue by Funguss** [CleverRaven/Cataclysm-DDA#38126]
# Is your feature request related to a problem? Please describe.
I'm currently playing a strength 7 character. As I was trying to push an oven out of a kitchen I recalled the times I'd done this previously, especially the times I'd had help. It's the same with moving all furniture, really. Any time I've had someone else about we've been able to move it a lot quicker than I could on my own (unless we were being a bit incompetent).

# Describe the solution you'd like
If you have any followers the one with the greatest strength in your vicinity (should probably allow five tiles or so) can help with moving the furniture. I'm not sure if this should be modified somewhat or be a flat addition. If it _is_ modified it should probably modify the strength of whoever is weaker - you or the NPC.

# Describe alternatives you've considered
Having an activity for moving furniture. Seems like it would be an interface nightmare.

**Comment by Mister-Cultist** [comment]
I can get behind this, one good idea would to include your npc friends around you in calculating your lifting ability when installing heavy vehicle parts.

**Comment by Funguss** [comment]
> one good idea would to include your npc friends around you in calculating your lifting ability when installing heavy vehicle parts.
This happens already! You can see it as a modified strength variable if an NPC is in range. It's pretty sweet. :smile:

**Comment by Amariithynar** [comment]
I'd honestly just halve the effective weight of an object you're trying to push if you have help, since you're splitting the task between the two of you. Pushing/pulling is much simpler than lifting.

**Comment by Funguss** [comment]
That could lead to some odd situations if the NPC is really, really weak for whatever reason. Also, if the PC is weak (as in my case) then the effect is going to be odd, too. My current playthrough, for example, includes an NPC with phenomenal strength. If they had helped to move an oven when my character had hit four strength (which it did recently) then we would have probably failed pretty often, though in practice the PC would probably have just stood and watched as the oven was effortlessly pushed around. Emulating this would probably be an OTT nightmare, but a message like "Bruno effortlessly pushes the fridge for you" may be a neat approach.

**Comment by Amariithynar** [comment]
They're a follower, a helper, not a "do-stuff-for-you"er. That's how I see it in my mind, hah. They pull their share, you pull yours, basically. I can understand what you want, just for an immediate implementation, halving its effective weight would be easiest to do, I'd think.

**Comment by Funguss** [comment]
Ha! They increase resource consumption by 100% or more each and only help with a _fraction_ of the work. Literally. How is that pulling their share? The implementation of how NPCs help with crafting was very "gamey" in the first place, relied on you needing to batch craft and even the logic that they should only contribute a little to the batch crafting time is spurious at best.

This highlights my point though, it's best to avoid the easy solutions as they tend to stick around. Davidpwbrown's worktable changes are precisely how NPCs should have been helping to craft all along, but it's taken this long for it to happen and won't even make it into this release. But damn I :heart: his work. But introducing an easy fix for this? No thanks! It would break immersion more fully on those outlying occasions than having them stand around and watch you struggle.

**Comment by Amariithynar** [comment]
Fair enough!
