### ISSUE TITLE
Majority of houses are no spawning.

### ISSUE THREAD

**Issue by sharkfinsouperman** [CleverRaven/Cataclysm-DDA#38125]
# Describe the bug

The city is full of empty lots where houses should be.

# Steps To Reproduce

Enter an unexplored city or town.

# Expected behavior

I'd expect houses to spawn where they've been marked on the map?

# Screenshots

This is a zoomed out view of the street where I am in the second image.
![image](https://user-images.githubusercontent.com/61106669/74712169-abd53180-51f3-11ea-85a3-8eedcc190e51.png)

I'm skirting the north perimeter of the city heading west and the greyed out buildings are missing.
![image](https://user-images.githubusercontent.com/61106669/74712279-eccd4600-51f3-11ea-9b53-606c8ca48e1e.png)

# Versions and configuration

Build 10336
Win7
Mod: No Fungal Creatures

# Additional context

Prior to updating to build 10336, I was playing 10309 and though a few houses were missing, the city was still playable. Now its almost nothing but streets, vehicles and zombies.

**Comment by Funguss** [comment]
May be related to #38121 . I've got 5x spawns on so it'll take me a while to run into this, I guess. On your map the houses that are greyed out are affected, correct? Is the map colouring them grey after they've entered the reality bubble?

**Comment by sharkfinsouperman** [comment]
The game didn't grey them out, I did.

I thought it may be a bug when I first entered the city and saw so many houses missing, so I began skirting through the residential area and marking them to get an idea how bad it actually was before submitting a report.

**Comment by sharkfinsouperman** [comment]
Seems the issue was related to when my map was generated and unrelated to current builds, so I'll close this issue.

I'll be more careful before submitting in the future.

**Comment by Funguss** [comment]
For future reference do you know precisely what caused it?

**Comment by sharkfinsouperman** [comment]
@Funguss  I'm a little unsure and unclear as to the details, but it has to do with the recent changes and additions regarding houses and basements, and its my understanding the dev responsible chose to turn the obsolete houses on old maps into empty lots to prevent mod conflicts.

Unfortunately, my world was generated using the build immediately prior to the changes and then I updated, so this is what I get until I generate a new map.

**Comment by DeeUnderscore** [comment]
I couldn't find anything about this being intentional. Is it? Cause if not, it's quite a save compatibility issue.

**Comment by anothersimulacrum** [comment]
#38988 fixes the save compatibility problems.

**Comment by DeeUnderscore** [comment]
Ah, thanks, I missed that one
