### ISSUE TITLE
house_quiverfull stair issues

### ISSUE THREAD

**Issue by Funguss** [CleverRaven/Cataclysm-DDA#38121]
See attached save. Map editor revealed a basement without upstairs. Not sure if this is a design error or what. Seems to be house_quiverfull_south.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-12348-g9aa8765 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    No Rail Stations [No_Rail_Stations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Roadheader and other mining vehicles [Heavy miners],
    No Fungal Monsters [No_Fungi],
    Beta National Guard Camp [national_guard_camp]
]

# Additional context

[Point Blank.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4216999/Point.Blank.zip)

**Comment by curstwist** [comment]
do you have desert region enabled?  That shouldn't be showing up anywhere except there.

**Comment by Funguss** [comment]
Wow, had to check that. I accidentally changed and saved some random setting the other day. But no, no it's not; this is a default world.

Aaaaand it's not `s_restaurant_deserted_test` at all. I thought the overmap tool in mapgen defaulted to the tile selected. Not sure which building it is then, I'll have a browse.

**Comment by Funguss** [comment]
Went through the JSON and compared. Seems like mapgen did an incomplete job of painting over the house it replaced. I didn't know it worked like that, hope that can explain the basement, too.

**Comment by Night-Pryanik** [comment]
I guess this strange issue is a one-time one. Unless someone encounters the same issue once again, I'm closing the issue for now.
