### ISSUE TITLE
Moving furniture is uninterruptible 

### ISSUE THREAD

**Issue by Funguss** [CleverRaven/Cataclysm-DDA#38128]
As stated in title. Similar to other old mechanics the fail/success of moving furniture is decided on attempt, then time passes. If a hostile appears you're stuck watching them tear you a new one. 

# Expected behavior

Obviously, the action should be handled similarly to all others. Sound should likely occur at the start instead, or perhaps periodically.

**Comment by pjf** [comment]
Is this moving furniture with 'G'rab, or has there been another way to redecorate that I've been missing all this time?

**Comment by anothersimulacrum** [comment]
I know `G`rab should be an activity but isn't.

**Comment by Funguss** [comment]
Yeah, talking about grab. As there wasn't another way to do it I didn't bother specifying.

**Comment by sharkfinsouperman** [comment]
> If a hostile appears you're stuck watching them tear you a new one.

I'm not sure if this is directly related, but a survivor was prying nails from a reinforced door, continued doing so after zombies had smashed the reinforcement and destroyed the door, and received numerous attacks before completing the job of pulling nails from a reinforced door that no longer existed.

Should a separate report be opened for this specific situation?
