### ISSUE TITLE
Multiple errors on load game

### ISSUE THREAD

**Issue by Funguss** [CleverRaven/Cataclysm-DDA#38129]
Not sure what's going on here. One error was in loading the safe mode settings. Prior to this there had been some save issues when dragging around a stove, which I think were caused by NPC butchering. Due to #38128 I was quicksaving after every attempt. That's my best guess as to the cause of the issue.

[Point Blank.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4219256/Point.Blank.zip)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-12348-g9aa8765 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    No Rail Stations [No_Rail_Stations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Roadheader and other mining vehicles [Heavy miners],
    No Fungal Monsters [No_Fungi],
    Beta National Guard Camp [national_guard_camp]
]

**Comment by Saicchi** [comment]
I'd ask for more details on the errors but I guess it doesn't matter since the current stable version is `0.E`. Trying to load an old save would just create more problems.
