### ISSUE TITLE
Your in progress clean water (20) (54%) is damaged by the force of the blow!

### ISSUE THREAD

**Issue by Funguss** [CleverRaven/Cataclysm-DDA#38133]
This is unlikely to come up during standard play but I thought it was worth pointing out how weird this whole "in progress" situation is when applied to liquid crafting. You can also throw it on the ground and it doesn't get dirty.

# Steps To Reproduce

1. Start boiling some water,holding it in your hands.
2. Change your mind halfway through and start beating the wall with the water.
3. Throw the water at your friend once you've damaged it a bit.
4. Pick up water and beat your friend to death with it (try not to break your water!)
4. Return to the fire and pretend nothing happened.

# Expected behavior

Liquid crafting should be bound to a container (or multiple). For mixing drinks, say, this could default to the containers the components are stored in. Any cooking should require x amount of pots/containers with x containing quality (or, for things like canning, specifically require multiple canning pots) to satisfy the total volume of the batch. This may help with #34246 and getting NPCs crafting liquids. May be used for sorting out the extreme water needed for canning in general.

# Screenshots

![clean water1](https://user-images.githubusercontent.com/57632331/74741216-4f562e80-5254-11ea-87e4-2d44cf31d440.png)
![clean water2](https://user-images.githubusercontent.com/57632331/74741218-4feec500-5254-11ea-9b7f-de8cb318ce8c.png)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-12348-g9aa8765 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    No Rail Stations [No_Rail_Stations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Roadheader and other mining vehicles [Heavy miners],
    No Fungal Monsters [No_Fungi],
    Beta National Guard Camp [national_guard_camp]
]

**Comment by CoroNaut** [comment]
I like to think you hit him with a pot of boiling water and managed to keep all the water still in the pot.

**Comment by Funguss** [comment]
2 bashing damage is pretty weak for a pot of boiling water! Also note how the pot contains both boiling water and water in this scenario. I can only see it as some kind of schizophrenic break (not that that character has the trait, but whatever).
