### ISSUE TITLE
Enable progromatic version detection of C:DDA binaries

### ISSUE THREAD

**Issue by damien** [CleverRaven/Cataclysm-DDA#38140]
# Is your feature request related to a problem? Please describe.

I'd like to enable version detection of C:DDA binaries. Currently, the only way to do this is to launch the game and look for the version string on the title menu. Lack of other ways to do this without resorting to binary inspection (yuck) or launching the game are problematic for a few reasons:

1. If I have a buggy binary and cannot reach the menu, I cannot determine the version of C:DDA
2. If I want to to interact with C:DDA binaries programmatically, it is useful for me to know what version of C:DDA I'm using
3. If I am working outside of the C:DDA git repository, I have no way of knowing what release I have

# Describe the solution you'd like

1. When building C:DDA, include current version string into the binary. I believe this already happens in order for the version string to be displayed on the title menu
2. Expose the version string outside of the title menu
  a. Add a `--version` string as a flag that can be passed to the C:DDA binary. When provided, print the version and exit
  b. Upon the first launch of C:DDA, write to a file named VERSION in the current directory. This file should consist of a single line that contains the version string of C:DDA

# Describe alternatives you've considered

There are only 3 ways I know of to determine the version of a C:DDA binary, none of which I'm personally a fan of as they all depend additional tooling or pre-existing knowledge of where a binary we retrieved from:

1. Keep track of where a binary was downloaded from and derive the version from either the URL of the download or the filename of the release. I believe this is how [remyroy/CDDA-Game-Launcher](https://github.com/remyroy/CDDA-Game-Launcher/blob/master/cddagl/ui/views/main.py#L821-L824) currently manages this.
2. Inspect the C:DDA binary and attempt to extract the version string. This is only viable on systems that have dev tools present to do this kind of binary inspection. It also seems like overkill for the problem.
3. Launching the game and attempting to capture a frame from the title screen, then attempting extract the version string from the ASCII output of that frame. Let's just not go there.

# Additional context

This is one of several features I'd like to request to enable more robust handling of mod management for C:DDA. Knowing what version we're running is the first step in determining what mods are compatible with a given release of C:DDA.

Related: remyroy/CDDA-Game-Launcher#413

**Comment by ZhilkinSerg** [comment]
We can just export version and build number to a text file during build process, so it would be included to archive.

See https://github.com/narc0tiq/catalysm-mainline-build/blob/master/mainline-build.zsh.

**Comment by ZhilkinSerg** [comment]
Should be resolved with #38144.

Wait until build 10342 is finished and see if `VERSION.txt` in the archive will fit your needs.

**Comment by damien** [comment]
Confirmed, build 10342 includes version info sufficient for programmatic inspection. Thanks @ZhilkinSerg!
