### ISSUE TITLE
Bone Seer NPC still spawns wearing an obsolete Heavy Survivor Helm.

### ISSUE THREAD

**Issue by sharkfinsouperman** [CleverRaven/Cataclysm-DDA#38145]
The Bone Seer NPC spawns wearing a Heavy Survivor Helm.

Seeing as survivor helms were obsoleted by PR #37524, it would be best to remove it from their equipment or replace it to prevent issues arising with this NPC in the future.

**Comment by jkraybill** [comment]
Can you post a screenshot of this and the version? According to current master JSON (NPC_Brigitte_LaCroix.json), she spawns with a tactical helmet. I can't find any current JSON references to helmet_hsurvivor.

**Comment by sharkfinsouperman** [comment]
Unfortunately, I nuked that world before updating so I could have houses again.

I found the file and she does spawn with a tactical helm.

`{
    "type": "item_group",
    "id": "BONE_SEER_Brigitte_worn",
    "subtype": "collection",
    "entries": [
      { "item": "loincloth_leather" },
      { "item": "socks" },
      { "item": "cloak" },
      { "item": "hsurvivor_suit" },
      { "item": "balclava" },
      { "item": "gloves_liner" },
      { "item": "tac_helmet" },
      { "item": "gloves_lsurvivor" },
      { "item": "boots_hsurvivor" },
      { "item": "elbow_pads" },
      { "item": "survivor_goggles" },
      { "item": "survivor_pack" }
    ]
  }`

Chances are I switched it while playing because survivor helms weren't obsoleted yet, and after seeing a comment on reddit, I checked my game, saw the helm and posted this report.

Sorry I wasted your time.
