### ISSUE TITLE
Sky inferno

### ISSUE THREAD

**Issue by Funguss** [CleverRaven/Cataclysm-DDA#38153]
In my current world I'm occupying a zoo. After failing to cremate the corpses around me (I can't remember the last time I bothered to do this) I decided to dismember them all first. After dismembering some twenty-thousand litres of corpses I started a fire and moved all but the fat into it. I think the fire raged about two days. The night it burned out I quit rendering my fat and went to bed.

The next day I woke up and saw the spot where the fire had been was obscured, even when standing next to it. This puzzled me for a while, and while moving some corpses for dismembering I watched the tile blink in and out of view, occasionally seeing smoke. I was mystified by this as there was nothing on the tile, so I turned on map editor and had a look below to see if the fire had got down there somehow. Nope. I quit map editor then thought to turn my gaze to the sky.

Everything above me was out of sight. Huh.

I turned on map editor again and had a look. Sure enough, the tile above the fire was filled with smoke and [raging fire]. That explained it. I took a look at the next Z level out of curiosity. Uh-oh, [raging fire]. Next Z level, [raging fire]. Thankfully, the Z level after that was just good old pink L2 [fire] with nothing over that. Still, that's ~~three~~ four Z levels of fire, just floating in the sky.

That was an _awesome_ bonfire.

Edit: I built another fire in the neighbouring tile and that's gone the same way. Also, after a few days, the second Z level has cleared but now the fire reaches to Z 10, as does the neighbour. This also seems to be generating quite a bit of lag, but it's hard to tell as this world is suffering from a high level of lag regardless.

[Point Blank.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4224888/Point.Blank.zip)

# Steps To Reproduce

1. Kill all the things.
2. Dismember all the corpses.
3. Use autoloot to get you and your NPC feeding a fire like there's no tomorrow (which there may not be after doing this.
4. Bask in the glory of your man-made sun.

# Expected behavior

Mid-air fire should probably die faster than that on the ground. Then again, it should probably not spread that high without spreading across the ground first. Maybe the best solution would incorporate making open air behave a bit more like open air; some strange things are currently possible, such as floating items or creatures. This appears to happen when objects occupy the tile in an unhandled way, such as the destruction of the wall beneath a player transforming the roof they stand on to air (the player floats in this situation), or if a map extra spawns items in the air (they just float there).

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-12348-g9aa8765 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    No Rail Stations [No_Rail_Stations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Roadheader and other mining vehicles [Heavy miners],
    No Fungal Monsters [No_Fungi],
    Beta National Guard Camp [national_guard_camp]
]

**Comment by NetSysFire** [comment]
Fixed by #57224
