### ISSUE TITLE
Chewing gum doesn't show in red for junkfood intolerant characters

### ISSUE THREAD

**Issue by pjf** [CleverRaven/Cataclysm-DDA#38152]
# Describe the bug

Characters with an allergy to junk food see items they should not eat in bright red in inventory listings.

Chewing gum *does not* show in bright red, but still gives a large morale malus upon consumption.

# Steps To Reproduce

1. Make a character with junkfood intolerance.
1. Get some chewing gum
1. Observe it doesn't show red in inventory
1. Eat the gum and be sad

# Expected behavior

Chewing gum should display bright-red like other junk-food items, when viewed by a junkfood intolerant character.

# Versions and configuration

```
- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 16.04.5 LTS; Release: 16.04; Codename: xenial; 
- Game Version: 0.D-12402-g6809b71c82 [64-bit] ( 1d23fcce1e8710494f350f11f99df09da34ef261 with some custom tweaks)
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Filthy Clothing [filthy_morale],
    Alternative Map Key [alt_map_key],
    [DP_MOD] Indicators: REMIX [DP_REMIX_INDICATORS],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Sleep Deprivation [sleepdeprivation],
    Bionic Slots [cbm_slots],
    sees-player icon, -attitude [sees_player_less_attitude]
]
```

**Comment by jeremyshannon** [comment]
Seems to me it just shouldn't have the morale pnealty attached. You don't swallow chewing gum, after all.

**Comment by kholat** [comment]
It was a recent change because of the "material: junk", it used to just be under drugs with no material iirc

**Comment by pjf** [comment]
I imagine `Character::will_eat()` mustn't be getting called with gum, as `will_eat()` displays a warning before eating food with negative consequences, which didn't happen when my junkfood-intolerant survivor started chewing gum.

Without looking into the code, I'm guessing `will_eat()` is checked for food, but not meds.

**Comment by davecwilkinson** [comment]
Since when is chewing gum junk.. what if it's sugar free? Reduces plaque build up people!
