### ISSUE TITLE
Game keeps corrupting worlds

### ISSUE THREAD

**Issue by sgtmind** [CleverRaven/Cataclysm-DDA#38185]
# Describe the bug

Whenever I try to load up a world after about 12 hours in real time, the save always seems to have errors with the world, almost always resulting in the game freezing, and being unable to load

# Steps To Reproduce

Load the save up, and if it doesn't seem to immediately glitch, wait 12 hours after turning off the computer, I do not know what else could cause this.

# Expected behavior

I do not know why it happens, it has happened for long enough that I am beginning to expect it. 

# Screenshots

# Versions and configuration

# Additional context

I am unable to access additional context due to the nature of this bug report

There always seems to be a problem with artifacts.gsav as noted in every crash report.

This has happened across multiple versions, and multiple saves, I have used different mods, all eventually seem to crash like this, I recently updated my game, but the saves should be from last update. 

Crash: if your problem refers to a crash, please add the following files to the "Additional Context" paragraph:
    - From the /config folder (you can zip them both together):
        - crash.log file.
        - debug.log file.
    - Your save file (zipped)

- note #1: you can drag and drop files in this issue post!
- note #2: it is very important for us that you provide a save file in case of a crash. It really helps the developers
    to reproduce the bug and fix it. If possible, try to provide a save file that occurs in the right conditions, just
    before the crash happens. -->

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4233146/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4233147/debug.log)
[Saves.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4233156/Saves.zip)

**Comment by eilaattwood** [comment]
Are you sure this is not your computer's HDD or RAM problem? Because I've never encountered that...

**Comment by ZhilkinSerg** [comment]
Try stable 0.D version and say if issue persists. If it is - it is most definitely environmental issue on your side. Check your hardware (HDD/RAM) for errors in that case.

Also are you installing CDDA on a thumbdrive by chance?

**Comment by Qrox** [comment]
That crash log was from a version 4 months ago, and contains little useful data for debugging. Have you tried reproducing the crash with a more recent version?
