### ISSUE TITLE
Can't continue crafting in-progress forged items when integrated toolset is active

### ISSUE THREAD

**Issue by jkraybill** [CleverRaven/Cataclysm-DDA#38180]
# Describe the bug

EDIT: I have isolated this issue down to when the Extended Toolset is active. Having that active makes this reproducible. Updated the description to reflect that.

I started crafting a nodachi. I stopped crafting because it was taking too much time.

Afterwards, I could not continue crafting -- when I activated the in-progress nodachi, nothing happened, the game acts as if I didn't select anything.

This also happened with in-progress sheet metal in my game.

However, I could not reproduce this issue from a "from-scratch" game. I have included a save game below.

# Steps To Reproduce

(I don't have reliable repro, this is in my attached saved game.)

- Craft a nodachi.
- Stop the crafting in progress (I stopped at 25%).
- Attempt to resume by activating the in progress item in inventory.
- Nothing happens -- the menu exits with no effect.

# Expected behavior

You can resume.

# Screenshots

![image](https://user-images.githubusercontent.com/1361701/74926703-6e0e1e00-542a-11ea-8a6d-57c22daec06f.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-12404-g1d23fcc [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    More City Locations [cityside],
    Urban Development [Urban_Development],
    No Fungal Monsters [No_Fungi]
]

# Additional context

I could not repro this in a fresh game, spawning in items in debug mode. I wonder if it has something to do with having multiple sources of charcoal / forge / tools around? My character had an integrated toolset, so that may be involved. This is a good issue to look into for someone who likes a good mystery. I tried repro'ing this in a fresh game without luck but I suspect it is an interaction with the items I had in my base.

[Yellow Lake.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4230343/Yellow.Lake.zip)

(Affected character is Adam 'Stitch' Patton)

**Comment by davidpwbrown** [comment]
Seems eerily similar to https://github.com/CleverRaven/Cataclysm-DDA/issues/32601

but instead of showing all tools, it just does nothing....

**Comment by jbytheway** [comment]
I don't think it's particularly related to #32601; that one was caused by some crafts needing zero charges to continue, which meant that all tools listed (because you had zero charges available from every tool).

Of course, it is probably a bug in the same part of the code.

**Comment by Fris0uman** [comment]
Extended toolset keeps you from wielding the item is that why it keeps you from continuing crafting?

**Comment by Fris0uman** [comment]
Puting the thing on a table or on a workbenche allows to resume crafting, so it's just a problem of wielding. Adding a message to explain why you can't wield the thing should fix the issue I think.
![image](https://user-images.githubusercontent.com/41293484/75632205-2e012500-5bfa-11ea-9cd6-c61e4d082db4.png)
