### ISSUE TITLE
Turrets are vulnerable to blind fire

### ISSUE THREAD

**Issue by Voker57** [CleverRaven/Cataclysm-DDA#38199]
# Describe the bug

It is very easy to defeat any turret if you crouch behind an object and blind-fire to where the turret is.

# Steps To Reproduce

1. Find a turret holding a hoard of ammo and protecting a valuable place
2. Find a table
3. Push table in front of you and approact turret
4. Crouch and "aim" "precisely" at a tile where the turret is
5. Depending on your weapon, turret will eventually be dead.

# Expected behavior

Turret shoots your table to shreds, or you can't aim at all, or it shoots your hands and weapon while you aim 

# Screenshots

# Versions and configuration
Latest master.

# Additional context

**Comment by eilaattwood** [comment]
Turret shouldn't shoot the player behind cover, because, well, It can't see. But character also shouldn't precisely aim while in the cover.

**Comment by Voker57** [comment]
> Turret shouldn't shoot the player behind cover, because, well, It can't see. But character also shouldn't precisely aim while in the cover.

Turrets can target weapons being aimed. In case of grenade turrets this would be very useful.

**Comment by TechyBen** [comment]
> > Turret shouldn't shoot the player behind cover, because, well, It can't see. But character also shouldn't precisely aim while in the cover.
> 
> Turrets can target weapons being aimed. In case of grenade turrets this would be very useful.

As long as it's balanced. These things should be able to be gamed (it's a game, it can have balance) and should be able to be circumvented to some extent (in real life they are fixed, so would be vulnerable to lots of types of attack, and as said, can also alternatively fire back at certain "events" regardless of vision).

**Comment by kevingranade** [comment]
The turrets, like players, have multiple senses.  If a turret takes damage and then returns fire at a tile that was the origin of a lot of noise recently, that sounds like a fairly reasonable action to take.
