### ISSUE TITLE
Ballroom dancer's lack of pockets

### ISSUE THREAD

**Issue by Scintile** [CleverRaven/Cataclysm-DDA#38207]
#37960 Female ballroom dancer doesnt have pocket to hold a cellphone you start with
When you start the game as female ballroom dancer your cellphone immediately drops on the floor due to the lack of pockets in your dress

Edit - same with professions like Bride (i assume every profession where females start with some sort of a dress and males with tuxedo)

# Steps To Reproduce
1. Choose profession Ballroom dancer when creating a character
2. Switch to female gender
3. Spawn and observe your cellphone falling to the ground

# Expected behavior
Cellphone you start with should remain in your pocket (but you have none)

# Versions and configuration
 - OS: Windows 17
 - Game Version: 10350 experimental, installed from CDDA launcher
 - Graphics version: ChestHole16
 - Ingame language: English
 - Mods loaded: DDA, Disable NPC needs, Mining mod, Cataclysm++, Aftershock, SpeedyDex, BionicSlots, C.R.I.T. expansion mod, Arcana and Magic items, Fuji's military profession Pack

**Comment by KorGgenT** [comment]
would a ballroom dress have pockets? maybe a ballroom dancer would have a small purse though?

**Comment by Scintile** [comment]
Well, Tuxedo (male dancers start with it) has 2L of storage. And its just "dress", not ballroom dress
