### ISSUE TITLE
Unload function picks objects up

### ISSUE THREAD

**Issue by Break-Off** [CleverRaven/Cataclysm-DDA#38206]
# Describe the bug

Often, a player will find items with more useful contents than containers (batteries, ammo, liquids, etc) and by using the 'U'nload function, they can retrieve said contents. Formerly, I remember that the container was left in place and the contents went into the player's inventory (or, if a liquid, prompted with what to do with it). Now, both contents and container are retrieved and they go into the players inventory, cluttering it further and forcing them to drop the container item if they don't want it.

# Steps To Reproduce

1. Find something you want the contents of.
2. 'U'nload the item.
3. Both container and contents are separated and retrieved into the players inventory.

# Expected behavior

Contents retrieved into the players inventory and the container left in place.

# Screenshots

![image](https://user-images.githubusercontent.com/5843433/75049153-fe4f7000-54c9-11ea-8e47-3deebfc141ac.png)
Trying to unload an MP3 player on the floor, so as to retrieve its battery.

![image](https://user-images.githubusercontent.com/5843433/75049192-11624000-54ca-11ea-9e42-fc1eef35b849.png)
Both the batteries and the empty MP3 players are retrieved into the player's inventory.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-12475-g7206b26 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    No Rail Stations [No_Rail_Stations],
    Urban Development [Urban_Development],
    sees-player icon, retrodays [sees_player_retro],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

I don't know if this is a mistake in my part, since I came back to the game recently. Perhaps it's a configurable option, or it has been intentionally changed. If this is the case, please tell me and I will close the issue.

**Comment by Ramza13** [comment]
This is a duplicate of #37061.  Which should probably not be stale and maybe made a bug.

**Comment by Break-Off** [comment]
It's not an exact duplicate, since the referred issue states that contents are dropped and container kept when player's inventory volume is near full. The underlying part of the problem of both cases it's that the container is picked up, regardless of inventory volume. Thanks for noting it, as @KorGgenT commented, a rework of unload function is needed anyway.

**Comment by Ramza13** [comment]
Good point, thanks.

**Comment by Dacendeth** [comment]
Yes please god fix this it's so annoying to unload something off the ground, have it put it in your inventory and make other stuff fumble out of your bag.

**Comment by Soadreqm** [comment]
The absolute worst part is when you try to unload a non-sealable container with liquid in it, which automatically dumps the liquid on the floor with no prompt to pick the container up with your hands instead.

**Comment by AncientSion** [comment]
I like how this would "fix" raiding for batteries (u wouldnt have to drop the electronics stuff you just picked up for the battery unload).

**Comment by TechyBen** [comment]
> The absolute worst part is when you try to unload a non-sealable container with liquid in it, which automatically dumps the liquid on the floor with no prompt to pick the container up with your hands instead.

I've lost so much soup this way (though might be an unrelated/fixed bug that one as accessed from the "eat" menu).
