### ISSUE TITLE
Interact with a space NPC is in

### ISSUE THREAD

**Issue by Break-Off** [CleverRaven/Cataclysm-DDA#38208]
# Is your feature request related to a problem? Please describe.
Sometimes, a player might interact with a space a NPC is in, (a vehicle tile, for example) but can't since the game prioritizes interaction with the NPC. In the case of dropped items in the ground or vehicle storage tiles, the player can use advanced inventory management as workaround, but it's still frustrating for other cases, like using a water faucet to drink from the vehicle's water reserves, or manipulate the dashboard/vehicle electronics without manning the vehicle itself.

# Describe the solution you'd like
An option that lets players choose between interacting with the space tile or the NPC. Perhaps easy to do, an option in the NPC interaction menu that says 'interact with space' or something along those lines.

# Describe alternatives you've considered
Workarounds include using AIM to retrieve contents of tile or swapping places with/pushing away NPCs.

**Comment by sharkfinsouperman** [comment]
Your issue appears to be the need for excessive keystrokes when getting items where an NPC is standing.

Have you considered pressing `g` to get the items?

**Comment by Break-Off** [comment]
Yes, that works for picking up stuff. But I was talking more along the lines of interacting with vehicle tiles.

**Comment by Funguss** [comment]
One example would be when an NPC sits in the driver seat, stopping you from interacting with the dashboard during an emergency of some description. A good fix would likely solve #38269 in the process. I imagine having another menu appear with a list of things to interact with on the given tile, though there may be more elegant solutions.
