### ISSUE TITLE
Allow using furniture as a tool for crafting

### ISSUE THREAD

**Issue by FirebrandCoding** [CleverRaven/Cataclysm-DDA#38209]
# Is your feature request related to a problem? Please describe.
Currently, there aren't many items of furniture in the game that could be used as tools or stations for crafting purposes. The closest we get to such an item would be the anvil, which is treated as an item one can pick up and carry around with them (provided they have the immense strength and the available volume in their backpack to do so, bizarre though it may seem).

There are also separate operations one can do with distinct items of furniture, such as the vehicle-lifting thingie.

What I'd like to see is being able to use stationary items as tools for crafting, to the point where they're seamlessly integrated into the process, without requiring additional setup from the player.

I've recently started working on [a mod](https://github.com/FirebrandCoding/HomesteadInstrumentsInc) that's adds tools and items of furniture useful for crafting and construction, as a modder's resource. Ideally I want to see the mod intergrated into the base game to an extent – such as with common-to-real-world workshop tools and some of the 20-minutes-into-the-future stuff – but I recognize that it wouldn't be possible until I have something to present for consideration.

# Describe the solution you'd like
Allow considering furniture as tools for crafting and construction purposes. This may require a separate field in the recipes JSON definition, or it could be integrated into the common `tools` field. This would allow common-sense interactions with objects that wouldn't be normally movable – not easily, anyway – such as machining tools regular to even home-based workshops.

# Describe alternatives you've considered
Keeping all potential work stations within the "haulable items" category, similar to anvil. While this makes sense as a temporary solution – something that, for example, a modder could do to showcase their ideas – it doesn't square well with the game's stated truth-to-reality, verisimilar approach. There's a difference between furniture and an item of equipment that I can't really put my finger on that nevertheless obviously exists.

# Additional context
Implementing this would also require anvil be made an item of furniture, to keep in line with the rest of the changes. It would still be carriable – draggable, not haulable – and it could still be used in crafting, just as a member of a different category.

There's also a matter of power supply and electric grids that should be addressed. I'm aware of #28289 and how it's supposed to bring power supply into the game, and I can't wait to see it happen.

Meanwhile, it seems prudent to sketch out a possibility of a more laborious, manual approach to having an electric grid where power is generated and there are batteries for the workstations to store it, but it would require replacing the charged batteries from the power generator to the workstation, and vice versa.

Ideally, a furniture overhaul should implement a form of custom interactions powered by JSON, rather than by the modder editing the game engine. One of the examples is the linked mod's planned surgical suite. While it's meant to do pretty much one thing for [a different mod](https://github.com/FirebrandCoding/ProjectAPEX), it could be expanded to fulfill the role of an advanced Autodoc, where it could help with regeneration process, or help with withdrawal, or maintain bionics (if and when such an action should prove a requirement, such as with #28273).

None of this can be done currently, however, because custom interactions are impossible to design. If there's any interest in implementing such a feature, this should be taken as a separate project dependent on this issue's fruition.

**Comment by KorGgenT** [comment]
> Implementing this would also require anvil be made an item of furniture,
Why would this be required?
Would tool qualities be acceptable here?

**Comment by Soadreqm** [comment]
Isn't this already possible? Several of the forge variants are furniture, and the anvil itself could be placed as furniture before #23637 gave it a quality level.

**Comment by GennFaol** [comment]
It would be neat to have a use for the lathes and other things you can find in workshops. Most of them are things a survivor can't easily manufacture themselves, but perhaps if there were ways to disassemble and reassemble them for transport, that could work. I do agree though that the anvil doesn't necessarily need changing, though.

**Comment by FirebrandCoding** [comment]
> Why would [turning anvil into furniture] be required?

The regular anvil item is very heavy, at 54 kg. I seem to remember seeing it weigh something like ~100 kg, which is where I would consider that it's meant to be a permanent installation, since moving that sort of weight requires mechanical support at the least.

50+? I'm no longer sure. I think it's still heavy, but perhaps not so much that it would prompt the survivor to reconsider moving it should this prove necessary.

My consideration was: making it furniture would align with the idea that it's not something one's supposed to carry around with them. I certainly cannot imagine a backpack that would allow a single 54 kg item to be carried inside it.

Even for carrying an anvil by hand, an average (8 pts of strength) character without any support is not even capable of carrying it without straining: it's 9 kg above the natural capacity. A world-class strongman (14 pts, according to the design document) can carry 69 kg - within limits, but still a significant part of one's capacity.

It appears that portable anvils are a thing, and there's even a relatively-lightweight bronze anvil in the game that appears to fill the very role.

> Isn't this already possible? Several of the forge variants are furniture

That's true: there are two types of forges that act as furniture. They do so by containing a pseudo-item which is referenced for crafting purposes (`crafting_pseudo_item`). Both reference charcoal forge, but it's only returned by deconstructing the regular forge furniture, which seems to suggest it isn't necessary to use the pseudo-item in construction to use it as such.

That's great news. I assumed it was impossible because I'd seen it used so rarely and had only ever used the electric forge (an item), which appeared to be easier to acquire by looting.

I suppose this closes the issue? The main subject has been covered. There are still peripheral subjects that are, perhaps, better suited to be discussed in their own separate issues, such as JSON-powered custom interactions with tools and furniture.

**Comment by KorGgenT** [comment]
> I suppose this closes the issue? The main subject has been covered. There are still peripheral subjects that are, perhaps, better suited to be discussed in their own separate issues, such as JSON-powered custom interactions with tools and furniture.
i wholeheartedly agree that the peripheral issues should get their own; if this is already implemented i'd say this issue is solved. Check out the project for furniture power grids, that might be closely related to something you want here.
