### ISSUE TITLE
Survivor utility belt: action menu renders wield shortcut useless

### ISSUE THREAD

**Issue by Break-Off** [CleverRaven/Cataclysm-DDA#38202]
# Describe the bug
When wielding a sheath-like clothing (e.g. survivor utility belt or a scabbard), the user is prompted with a pop-up that says if the user wants to wield the sheath contents instead. In most cases, it works as expected, but in the case of the survivor utility belt, when selecting 'Yes', its action menu is opened, which makes the shortcut redundant since the player has to select 'Use holster' from the action menu anyway. In the end, it's easier to 'a'ctivate the belt and press '8' (Use holster), since it's less keypresses.

# Steps To Reproduce

1. Spawn a survivor utility belt.
2. Spawn a bladed weapon that fits in the survivor utility belt sheath (in my case, survivor machete).
3. Sheath the weapon.
4. Wield the survivor utility belt as to prompt the wield shortcut pop-up and select 'yes'.
5. The action menu for the survivor utility belt will be opened instead and force the player to select 'Use holster' option to unsheath the blade.

# Expected behavior

The player character unsheaths and wields the weapon contained in the belt when selecting 'yes', instead of the action menu opening.

# Screenshots

![image](https://user-images.githubusercontent.com/5843433/75047360-e9bda880-54c6-11ea-90c8-ab1dad7dec35.png)
Wielding the utility belt

![image](https://user-images.githubusercontent.com/5843433/75047402-fe9a3c00-54c6-11ea-91f4-219958f9bebf.png)
Wield shortcut pop-up, selecting yes

![image](https://user-images.githubusercontent.com/5843433/75047440-0b1e9480-54c7-11ea-918e-2388ae75f55e.png)
Action menu opens instead, forcing player to select 'Use holster'

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-12475-g7206b26 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    No Rail Stations [No_Rail_Stations],
    Urban Development [Urban_Development],
    sees-player icon, retrodays [sees_player_retro],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by KorGgenT** [comment]
i'll keep an eye on this issue as i'm working on nested containers, which will directly interact with stuff like this
