### ISSUE TITLE
Gun noises not printed

### ISSUE THREAD

**Issue by Soadreqm** [CleverRaven/Cataclysm-DDA#38200]
# Describe the bug

The sound effects when firing guns aren't printed. Noise still happens, it shows up in the side panel noise meter and can alert creatures and blow out your eardrums and all that, but the text feedback is missing.

# Steps To Reproduce

1. Make a player with a gun
2. Fire gun at nothing in particular
3. No message is printed (unless you hit something)

# Expected behavior

Gun should go "bang", or possibly "blam" or even "kaboom" depending on noise level, so long as the player isn't deaf.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.D-12453-g05940bf [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by eilaattwood** [comment]
That's just flooding the logs with garbage, aren't it? I mean, player obviously knows that he/she is making character to shoot. Why tell that in the logs?

**Comment by Soadreqm** [comment]
The main reason I miss the feature is that it just made gunfights feel cooler, but it also provided instant feedback on how loud a gun was. The noise number is very abstract, and not nearly as visible as the "plink!" or "kerblam!" in the message log.
Was it removed intentionally? I tried searching pull requests, but couldn't find anything relating to it. The noise strings are also still in src/ranged.cpp, with nothing clearly indicating that they're no longer used.

**Comment by anothersimulacrum** [comment]
Sounds on the play tile are not displayed unless they're of a certain type.
