### ISSUE TITLE
Allow adding non-artifact effects to `artifact_data` fields

### ISSUE THREAD

**Issue by FirebrandCoding** [CleverRaven/Cataclysm-DDA#38210]
# Is your feature request related to a problem? Please describe.
Artifact effects are limited in what they can help achieve. They aren't prohibitive, but you want to make so much as a single step beyond the set enums, you're facing a dead end.

If you're someone like me – who can handle JSON for a separate mod but wouldn't dare try editing the game engine with C++ – all that's left to do for you is advocate for the feature before the people actually capable of bringing the change about.

# Describe the solution you'd like
Allow referencing non-artifact effects, including custom effects, in the item's `artifact_data` entry (`effects_when_worn` etc.). Also, increase the range of available options for effects to modify. A short list of possible examples:

* learning speed (enables nootropics and advanced learning devices)
* carry weight (currently restricted to a set number in an artifact effect and to the settings of the item itself)
* carry volume (enables learning packing logistics)
* aim speed
* accuracy (of both throwing and shooting)
* draw speed
* radioactive emissions (currently restricted to a set artifact effect)
* crafting speed
* mutagenic effect (currently restricted to a set artifact effect)

# Describe alternatives you've considered
It's possible to achieve a middle ground that doesn't (seem to) require a major rework of the system. For that, allow setting the values of the effects artifacts provide: for example, rather than state `effects_when_worn: [ "AEP_CARRY_MORE" ]`, allow setting the value for the effect to use: `effects_when_worn: [ [ "AEP_CARRY_MORE", 40 ], [ "AEP_STR_UP", 3 ], "AEP_DEX_UP" ]`, and use default values where none is specified.

# Additional context
Ideally, such a system would not be restricted at all by default because it would calculate the values directly from their `id`s. Rather than require the modder to use `"AEP_STR_UP"`, it would allow referencing the internal `id` of player's strength stat. Ideally.

This isn't to say implementing such a thing would necessarily be easy, nor is it of immediate importance. It would, however, allow more player/modder freedom.

**Comment by KorGgenT** [comment]
See https://github.com/CleverRaven/Cataclysm-DDA/projects/30
The basic plan is you can create both passive and active effects in json.
