### ISSUE TITLE
Safe mode needs to be enabled with boat driving

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#38218]
When i drive my boat, i'm mostly holding `.` since it's really slow and also not many turns need to be done when moving across a water body. On the other hand, every turn a beaver or even some worse creatures may pop up and bite me, while driving ignores any safe mode violations by default, and you effectively skip a few bites before reacting to the challenges from the deep. You need to remember to re-enable safe-mode-in-vehicles every time you jump on a boat.

# Expected behavior

Safe mode enabling automatically when driving slow (muscle-driven?) vehicles.

# Screenshots

![](https://tinystash.undef.im/il/4VK9C6q5TTESLrkFLifK6APSKAQ2CgZ6K4Q2bhEs7q2FetosnqYbf7auHqdvRyMSKBXCghQFjztbaqruu9sqbJhC)

# Versions and configuration
- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.D-12453-g05940bfe3a-dirty [64-bit]
- Graphics Version: Curses
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

# Additional context

**Comment by Dacendeth** [comment]
Safe mode while driving option auto enables for me while piloting a inflatable boat so I dunno what the issue is here.

**Comment by l29ah** [comment]
Check the screenshot. I was just holding `.` back then.
