### ISSUE TITLE
Experimental mutant won't move to attack, but attacks you if you're in the next tile

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#38211]
# Describe the bug

# Steps To Reproduce
Load the game and have fun. I don't know what killed the zombies around.

# Expected behavior

The mutant either being friendly, or chasing you, or being obviously immobile.

# Screenshots

![](https://pstbin.ru/f/63161/)

# Versions and configuration
- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.D-12453-g05940bfe3a-dirty [64-bit]
- Graphics Version: Curses
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key]
]

# Additional context

[2019.07.17-2.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4238224/2019.07.17-2.zip)

**Comment by l29ah** [comment]
Still reproduces on master.

**Comment by Night-Pryanik** [comment]
As of 0.F-10914 experimental mutant moves to attack the player character
![изображение](https://user-images.githubusercontent.com/11132525/187253888-6f19b274-b9f3-401b-a446-b34e68ab7ef1.png)
