### ISSUE TITLE
Ant tunnels only have acidic ants

### ISSUE THREAD

**Issue by StrongEUW** [CleverRaven/Cataclysm-DDA#38229]
# Describe the bug

All anthills spawn acidic ants and acidic soldier ants in the below-ground portion.

# Steps To Reproduce

Start up a new game on a recent experimental and debug into the subterranean portion of a non-sulfurous ant hill - asides from the queen and larvae (specifically in the larva chamber, there'll be a smattering of acidic ant larvae elsewhere in the tunnels), all ants are acidic/acidic soldiers (and the acidic ants will also hence immediately start attacking the queens/larvae).

# Expected behavior

Anthills are filled with appropriate type (acidic/non-acidic) of ant.

# Screenshots

![2020-02-22 12_29_46-Cataclysm_ Dark Days Ahead - 0 D-12404-g1d23fcc](https://user-images.githubusercontent.com/49459628/75092563-dff07f80-5570-11ea-8661-3366066e0d06.png)
![2020-02-22 12_33_44-Cataclysm_ Dark Days Ahead - 0 D-12404-g1d23fcc](https://user-images.githubusercontent.com/49459628/75092564-e121ac80-5570-11ea-9f24-e642d24cdea1.png)

# Versions and configuration

0.D-12404-g1d23fcc (build 10343) with default mods (Dark Days Ahead, Disable NPC Needs).
 -->

# Additional context

This appears to be have been introduced at some point during fixes to anthill generation in early January (see PR 36702, 36736, 36767); did a quick test and seemed to be working as would be expected (regular ants in regular anthills) on build 10009 (15th December).

**Comment by CyanSam** [comment]
Have encountered an issue like this in a recent build with labs that have a nearby "normal" antihill, having acidic ants inside instead of normal ones.

**Comment by sharkfinsouperman** [comment]
I recently began clearing a town near a regular anthill and it has acidic ants in a number of basements within the region occupied by ants above ground.

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-12648-g63d3fb8 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    No Fungal Monsters [No_Fungi]
]
