### ISSUE TITLE
Abstract constructions can't be made in the dark

### ISSUE THREAD

**Issue by Break-Off** [CleverRaven/Cataclysm-DDA#38227]
# Describe the bug

Abstract constructions (like mark firewood source or mark target practice), which serve more a practical purpose rather than being structures, can't be made in the dark.

# Steps To Reproduce

1. Be in darkness.
2. Open construction menu and select mark firewood source.
3. Be notified that you can't construct in the dark.

# Expected behavior

Being able to mark firewood sources in the dark.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-12475-g7206b26 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    No Rail Stations [No_Rail_Stations],
    Urban Development [Urban_Development],
    sees-player icon, retrodays [sees_player_retro],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by anothersimulacrum** [comment]
The firewood source construction should be removed in favor of the zone, but the second one is definitely not proper behavior.
