### ISSUE TITLE
Allow item type inheritance

### ISSUE THREAD

**Issue by FirebrandCoding** [CleverRaven/Cataclysm-DDA#38233]
# Is your feature request related to a problem? Please describe.
Creating an item derived from some sort of an abstract one seems to inherit all of the non-required fields - except `type`. This seems incongruent with how the inheritance model appears to be: inheriting all *but* one generic field.

# Describe the solution you'd like
Allow item type to be inherited. Also allow target items to overwrite the type.

# Describe alternatives you've considered
Not requiring abstract items to have a type. This would indicate that no inheritance is possible for this field. and that `type` must be filled out manually for every target item.

# Additional context
Type inheritance would make writing JSON for items easier, more intuitive, and reduce the resulting mod size a little bit.

Explicitly prohibiting type for abstract items (similar to how `id` is prohibited for items with `abstract` filled out) would also improve the intuitive grasping of the system.

**Comment by KorGgenT** [comment]
there's a reason for this: the `type` field tells the game what loader it's supposed to use. in addition, items with different types are not required to have non-intersecting ids: you can have an item with id "bomb" and an effect with id "bomb" and a spell with id "bomb". it might get confusing for the json, but that's another effect of how generic_factory loads in data.
