### ISSUE TITLE
Item action "repair_myomer" isn't known to the game.

### ISSUE THREAD

**Issue by TheGoatGod** [CleverRaven/Cataclysm-DDA#38259]
# Describe the bug

 DEBUG    : Item action "repair_myomer" isn't known to the game.  Check item action definitions in JSON.

 FUNCTION : void item_action_generator::check_consistency() const
 FILE     : src/item_action.cpp
 LINE     : 207

# Steps To Reproduce

create a world and start-up

**Comment by anothersimulacrum** [comment]
This string doesn't appear anywhere in the base game, sounds like a mod issue (this is why the template is important, so we know if it's a mod issue or not).

**Comment by KorGgenT** [comment]
please complete the template

**Comment by TheGoatGod** [comment]
im going to reinstall the game see if it goes away, i have no mods enabled

**Comment by TheGoatGod** [comment]
its gone after reinstal

**Comment by KorGgenT** [comment]
sounds like an unreproducable issue with some unknown mod then.
