### ISSUE TITLE
Deep water messes up furniture moving

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#38269]
# Describe the bug

It prompts you to dive into the water instead of moving the grabbed furniture.

# Steps To Reproduce
Load the game and try to move the bench to the right without leaving the current tile.

# Expected behavior

The bench moving to the right.

# Screenshots

![](https://tinystash.undef.im/il/4sD7YfBSxr32XBU1GUvXx91jRjuDo1ah5NaQi7SSKr3bKeBSEe5gAyvAUBqbAM62cUD8puqiEHHU2zj7Kxzk5bpq)

# Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.D-12504-g90156182f7-dirty [64-bit]
- Graphics Version: Curses
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

# Additional context
[2020.02.22-1.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4241240/2020.02.22-1.zip)

**Comment by Funguss** [comment]
This also occurs when moving into an NPC. It probably also occurs when moving into fire, traps, anything that opens a dialogue box. Of course, there may actually be situations where one would want to perform an action; can this be handled without cancelling the drag?

**Comment by Night-Pryanik** [comment]
How do you plan to keep the grip of the furniture while being on the tile with deep water?

**Comment by Funguss** [comment]
Good call. Just how deep is deep water? It depends on whether the deep water borders shallow water, too, and the furniture in question, especially the weight and buoyancy. Dragging a small inflatable kayak  into deep water is doable, for sure. Other furniture probably not so much. Not sure what the best solution would be here.

**Comment by Night-Pryanik** [comment]
Kayak is a vehicle, not a furniture. Floatable vehicles should be draggable in the water (if they don't already). In theory floatable furniture should be draggable too, but I'm not sure if it's worth the effort to implement such mechanics.

Deep water is, actually, deep. Its depth is more than human height.

**Comment by Funguss** [comment]
Well, I mentioned the kayak because you can't drag vehicles by moving into deep water either, as is mentioned in passing in another issue.

Just for a little test I tried dragging a camp chair into a river but was prevented because "the camp chair collides with something" so it seems furniture can't be pushed or pulled into any kind of water. This is a bit of a surprise. I quite like the idea of pushing bookcases into the river and watching them either float away or sink, now I think about it.

**Comment by l29ah** [comment]
> How do you plan to keep the grip of the furniture while being on the tile with deep water?
I don't. The issue is that the semantics of movement keys during dragging is changed depending on whether you're near deep water, not that you can't drag something into the water.

**Comment by Night-Pryanik** [comment]
Oh. Now I get it, initially I was looking in the wrong direction. Yes, this is definitely must be fixed.
