### ISSUE TITLE
Free Merchant Solar Power quest does not accept upgraded solar panels

### ISSUE THREAD

**Issue by jkraybill** [CleverRaven/Cataclysm-DDA#38267]
# Describe the bug

The "Solar Power" quest from the Free Merchants requires 10 solar panels, but won't accept upgraded solar panels. It seemed logical that it should.

# Steps To Reproduce

Accept the "Solar Power" quest. Deliver 10 solar panels where at least one of them is an upgraded solar panel. The quest can't be completed.

# Expected behavior

I expected to be able to deliver upgraded solar panels as an acceptable delivery. I expect that any combination of solar panels and upgraded solar panels will fulfill the quest goal.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-12430-g142295b [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    More City Locations [cityside],
    Urban Development [Urban_Development],
    No Fungal Monsters [No_Fungi]
]

**Comment by jkraybill** [comment]
As I've learned, you can deconstruct the upgraded panels to get un-upgraded panels, but if anything that emphasizes why the quest-giver should accept upgraded panels.

**Comment by l29ah** [comment]
Maybe they don't have enough skill to install the upgraded panels? The regular requires mech 4, and the upgraded need 5!

**Comment by jkraybill** [comment]
Heh well that's one explanation, maybe another is that quests should use more flexible item groups :)

It also looks like in the "Find 25 blankets" quest, you have to give blankets, not down-filled, electric, etc.
