### ISSUE TITLE
Construction screen freezes after pressing semicolon

### ISSUE THREAD

**Issue by Scintile** [CleverRaven/Cataclysm-DDA#38266]
Construction screen freezes after pressing semicolon
Entering construction screen (shift+8) and pressing semicolon shows a message "You cant build that!" that cant be closed. From what i observed you have to close the game to get out of that

# Steps To Reproduce
1. Make a character (default survivor in default scenario works well)
2. Open construction screen (shift+8)
3. Press semicolon
4. Observe the message that cant be closed

# Expected behavior
List of all things you can construct should be filtered to only show what you can build at that moment

# Versions and configuration
 - OS: Windows 7
 - Game Version: Experimental version 10355 (also observed on latest version 10356)
 - Graphics version: ChestHole16
 - Ingame language: English
 - Mods loaded: only Dark Days Ahead

**Comment by Qrox** [comment]
Can't reproduce. The code only shows "you can't build that" on confirm action, i'm not sure why pressing the semicolon key would trigger that. Do you have IME on?

**Comment by Scintile** [comment]
Sorry, what is IME?

**Comment by Qrox** [comment]
Input method editor, it's know to mess with game input.

**Comment by Scintile** [comment]
Hm. not that i know about it. use a normal keyboard with no special programs (semicolon worked fine for me like 2 days ago. Since then i didnt install anything new on my computer)

**Comment by Qrox** [comment]
I see, it's likely a recently introduced bug by #38239.

**Comment by Scintile** [comment]
Hey, yeah, i just installed version 10354 and everything works. So it was introduced in 10355, like you siad
