### ISSUE TITLE
False warning spam during zone deconstruction

### ISSUE THREAD

**Issue by Funguss** [CleverRaven/Cataclysm-DDA#38264]
When using construction zones to deconstruct benches in a zoo start I've been spammed with "There is something blocking the location for this task". It appears to generate when beginning deconstruction, not during. Also, any bench that was in a dark location wasn't deconstructed (despite having bright tiles adjacent to them) including some benches that were in a bright location but had a dark tile bordering them.

# Steps To Reproduce

I'm guessing this isn't only applicable to zoo starts. However, it does have a convenient layout for seeing this bug in action.

1. Start in a zoo.
2. Setup a deconstruction zone covering the benches in the main hall. See screenshot below for location.
3. Run construction activity.

# Screenshots

![deconstruct](https://user-images.githubusercontent.com/57632331/75103972-8e8cd280-55fa-11ea-90d6-fa5c14af4675.png)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-12504-g9015618 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    No Rail Stations [No_Rail_Stations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Roadheader and other mining vehicles [Heavy miners],
    No Fungal Monsters [No_Fungi],
    Beta National Guard Camp [national_guard_camp]
]

**Comment by davidpwbrown** [comment]
OK, so when the target of the activity is in a dark tile, then it is correctly not doing it, as it cannot construct in the dark.

And if the bordering tile was in the dark, and thats where the player wants to path to, then itd fail at that too, the player is not clever enough to prioritise a path to a lit tile yet, that can be addressed.

The message "there is something blocking the location for this task" is for every tile in the zone that cannot be reached or there is something there, this will be partially addressed by the work happening on zone activity failure log here https://github.com/CleverRaven/Cataclysm-DDA/pull/37300

**Comment by Funguss** [comment]
Huh? What happened to my reply? I know I replied to this. :confused: 

Well, to repeat myself, the issue is that the rules aren't the same as those for the PC. The PC _can_ deconstruct things in the dark so long as they stand on a lit tile (unless it's via zone activity). Also, the NPC can't deconstruct tiles that contain items, whereas the PC can.

There were one or two other points but I totally forget what they are now. :angry:
