### ISSUE TITLE
Drones, land and aerial

### ISSUE THREAD

**Issue by FirebrandCoding** [CleverRaven/Cataclysm-DDA#38270]
# Is your feature request related to a problem? Please describe.
Survival in *Cataclysm* is difficult, and a lot of it depends on being prepared. Information is naturally limited, so in order to be more prepared, one must utilize every available source of information within their reach. Drones are an easy way to extend one's visual range without exposing yourself to danger from an unexpected enemy or a potentially-malicious artifact.

# Describe the solution you'd like
Introduce vehicular (miniature) and aerial drones. Allow the player to control said drones using a portable device (a tablet, an RC control with a screen mounted on it etc.). Allow the player to see through the cameras installed on the drones, at the expense of having limited awareness of their own immediate surroundings.

# Describe alternatives you've considered
Sticky cameras, like in the *Splinter Cell* game series.

Device-based sight through walls, somewhat like in *Deus Ex: Human Revolution*, but more realistic.

["Optiwand"](https://sketchfab.com/3d-models/optiwand-police-29fcebb514ea44fc896436f115fb4c38), like the one used in the game *SWAT 4*, which allows you to look under doors and around corners without exposing itself. (The "around corners" part is already handled by the peeking mechanic. See below)

Hacking robots to temporarily gain their sight (without gaining control of the robot itself, that being a separate action requiring more expertise).

# Additional context
There's [a great selection of drones on Amazon](https://www.amazon.com/slp/rc-drone/mhykzuxus72ousy), ranging anywhere from $25 to $250 and higher. This suggests that buying a drone in an electronics store in the game's world has not been difficult prior to the Cataclysm (assuming, of course, the same otherwise technological path).

I'm not aware of how difficult it is to build one's own drone out of scratch, but getting out out of the store and assembling it should be easy enough even for a survivor who's an amateur in electronics. Attaching a camera on an otherwise-sightless drone would seem to prove challenging to a newbie, but a handy survivor should have little problem with that project.

Vehicular drones are on the list for two reasons:

1. They're a common sci-fi trope as of recently.
2. Using an aerial drone indoors may prove difficult.

The vehicular drone is presumed to be small enough to fit under a closed door, which may be a stretch of the imagination. Its goal is to be used in elaborate human facilities, such as laboratories, where one door opened too rashly may lead to the character's demise.

An alternative to such a device might be something the *SWAT 4* game calls "optiwand" (there appears to be no device under such name in real life). It's a camera attached to a flexible rod that connects the camera to a screen, so that the user could safely inspect a potentially-dangerous room or corner before moving. Such a concept does not seem too advanced to have in *Cataclysm*.

If an "optiwand" is to be included, a penalty may be imposed on peeking: for example, a chance to be hit in the head by a turret, because it still takes a little time to peek. It feels sadistic to impose such a penalty, given that survival is already a difficult affair for a regular character, but it does seem to reflect the dangers such a situation would enhance the feeling of having to trade between danger and survival the game is built on.

**Comment by Funguss** [comment]
Regarding peeking: it takes a turn for a turret to detect you, another turn to shoot. You don't even need to peek if you have 100 speed, really, but it's good practice and doesn't require you to be on top form.

On the subject of the optiwand... I imagine in most secret labs, to say nothing of other places, the doors in the facility would be fire doors at least, though I expect (given what they were working with) they were designed like this: https://www.recorduk.co.uk/en/product/14/record-clean-k1-a. I'm not aware of any PVC doors that don't form a complete seal, and most building contractors would want a door with good insulation so I assume most wooden doors would be well-sealed. I'm not sure how prevalent letterboxes on doors are in New England, here in Old England they're pretty standard. The tool you're suggesting could be used through those, or on internal doors, but I don't see it having much use really.

Given what @davidpwbrown has been doing with hot air balloons and helicopters he might be able to sort out a drone relatively easily now? I feel a bit hesitant suggesting as he's already doing so many amazing things, I don't want to delay the next surprise!
