### ISSUE TITLE
Cooking canned meat from rotten scraps of meat doesn't get marked as using rotten ingredients

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#38271]
# Describe the bug

And correctly produces a can of rotten meat.

# Steps To Reproduce

Load the game, make canned meat.

# Expected behavior

Canned meat getting the label and the rotten color in the crafting menu as other meat recipes.

# Screenshots

![](https://tinystash.undef.im/il/3AyurWv1jCLrvc3db3YwqS9aJycpCNgodVMPwNpt7XoFXPfdQAbFsav5rp6hfy9jGThJonwT826FYShSUhqA3dXd)

# Versions and configuration
- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.D-12504-g90156182f7-dirty [64-bit]
- Graphics Version: Curses
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

# Additional context

[2020.02.22-1.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4241815/2020.02.22-1.zip)

**Comment by jkraybill** [comment]
Confirmed this affects canned fruit too -- I'd guess any canned good with a rotten ingredient.
