### ISSUE TITLE
Minefields don't spawn

### ISSUE THREAD

**Issue by sharkfinsouperman** [CleverRaven/Cataclysm-DDA#38289]
# Describe the bug

Though the two no longer exist in the game, auto-notes still marks them as though they are there.

A minefield marked west of a railway station.
![image](https://user-images.githubusercontent.com/61106669/75153708-0aaa1780-56da-11ea-8d0b-6aed94c5e054.png)

A minefield marked on the entrance to a farm.
![image](https://user-images.githubusercontent.com/61106669/75153834-552b9400-56da-11ea-9576-9329e345ac69.png)

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-12445-g55cabb7 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    No Fungal Monsters [No_Fungi]
]

**Comment by TimPollard** [comment]
I've noticed it marking "craters" which don't seem to be present as well.

**Comment by Night-Pryanik** [comment]
Neither minefields nor bandit ambushes weren't obsoleted and still exist in the game.

**Comment by TimPollard** [comment]
> Neither minefields nor bandit ambushes weren't obsoleted and still exist in the game.

Possibly it's not that they've been obsoleted then; but something is adding auto-notes for things that don't appear to actually exist. I've noticed it for bandit roadblocks, minefields, and craters.

If it helps here's a save I just made that shows an example of a minefield note without any mines. The character is standing in the middle of a minefield according to the auto-notes feature (check the map), but I don't think there are any mines there; you can walk around in zig-zags and not find anything.

[save_minefield_note_w_no_mines.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4244136/minefield_note_w_no_mines.zip)

---

- OS: Linux
    - OS Version: Slackware 14.2
- Game Version: 0.D-12504-g90156182f7 [64-bit]
- Graphics Version: Curses
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by Night-Pryanik** [comment]
That's really strange because minefields should only spawn at entry of the bridges, not in the middle of nowhere. Ok, I'll reopen, but we need a confirmation from other people.

**Comment by sharkfinsouperman** [comment]
I apologize. My understanding was they had been disabled based on the linked conversation.

https://www.reddit.com/r/cataclysmdda/comments/f654uo/new_players_come_here_weekly_questions_and/filk9rp/?context=3

I've added screenshots of two minefields and the debug report, but I haven't encountered any ambushes yet. Please feel free to change the report's title to something more appropriate.

**Comment by Vormithrax** [comment]
I have been live-streaming CDDA 24 hours per week for a couple years now, always using current experimental branch builds.  I have never once seen a  minefield at a bridge (and i've crossed hundreds at least since this change). I remember when that change was supposedly made (June or so of last year) and can point to a thousand hours of live-stream footage when i say it does NOT actually occur in game. I have not seen a single random field minefield or bridge military roadblock  minefield in all that time.

**Comment by sharkfinsouperman** [comment]
I found an ambush next to a lab and there was a vehicle parked and nobody there, which is consistent with every other ambush I've encountered since I started playing experimental.

I'll also add that I too have never seen a minefield at any bridge I've crossed.

[Sharkfin_no_ambush_or_mines.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4245262/Sharkfin_no_ambush_or_mines.zip)

**Comment by Night-Pryanik** [comment]
Ok, I reworded the title to emphasize the main issue.
