### ISSUE TITLE
Auto-target does not auto-target through display racks

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#38285]
# Describe the bug

As title, also noticed that it doesn't auto-target through unbroken windows

# Steps To Reproduce

1. Display rack between you and enemy
2. Display rack blocks auto-target, but you can still aim at enemy and shoot at enemy like normal

# Expected behavior

Auto target through display rack

# Versions and configuration
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-12476-gfef327b [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    No Fungal Monsters [No_Fungi],
    Disable Religious Texts [no_religious_Texts]
]

**Comment by Night-Pryanik** [comment]
Ranged auto-target or melee ranged auto-target?

**Comment by CoroNaut** [comment]
This is ranged, Melee is a different story for 2-tile reach, but I think it would still be nice to have melee auto-target through display rack and windows, etc

**Comment by Amariithynar** [comment]
I'm pretty sure I saw a recentish (last month or so) PR that went through that made it so that you can't auto-target through terrain marked impassable, so that more serious threats are targeted first in a swarm scenario. You should be able to still manually aim and fire, though.

**Comment by Ramza13** [comment]
> I'm pretty sure I saw a recentish (last month or so) PR that went through that made it so that you can't auto-target through terrain marked impassable, so that more serious threats are targeted first in a swarm scenario. You should be able to still manually aim and fire, though.

Yes that is correct, I added that check to prevent targeting through walls or glass. I'll take a look at this but finding the right logic for targeting though isn't easy, as in I'm not sure what flags or features differentiate a shelf you can stab through from a wall from a glass wall and it might not be doable at present without adding an additional flag.

**Comment by AMurkin** [comment]
Now laser weapons can't auto-target when the enemy is behind a glass wall too.

**Comment by RDru** [comment]
one other thing: auto-target still sometimes targets stuff on other z-levels, through the roof or floor.

**Comment by Ramza13** [comment]
> one other thing: auto-target still sometimes targets stuff on other z-levels, through the roof or floor.

Do you have any special mutations or bionics related to sight?  Really thought those were taken care of.
