### ISSUE TITLE
Missing roof on laundromat

### ISSUE THREAD

**Issue by ashGlaw** [CleverRaven/Cataclysm-DDA#38282]
# Describe the bug
The laundromat spawns without a roof. Saving and loading with it in the reality bubble generates a roof, but it has no furniture.

# Steps To Reproduce

Start a new character. Debug reveal the map and search for a laundromat. If you don't find one you'll need to teleport outside of the revealed area and reveal the map again until you find one. Long range teleport to within a few overmap tiles from it, distance isn't important as long as it's outside of the reality bubble. Walk on over to the laundromat and observe its lack of roof. Save. Load your save. The roof is there, but incomplete.

# Expected behavior

The laundromat should spawn with it roof on, and there should be roof furniture up there like the gutters to match the drainspout a z-level down.

# Screenshots
Laundromat roof before save
![Laundromat Roof Before Save](https://user-images.githubusercontent.com/58862150/75120020-05a38480-5656-11ea-914c-2b64b5c0d5d5.png)
Laundromat roof after load
![Laundromat Roof After Load](https://user-images.githubusercontent.com/58862150/75120023-0805de80-5656-11ea-81e9-ae1e87da5e28.png)

# Versions and configuration

- OS: Windows 10
    - OS Version: 10.0 1909
- Game Version: 0.D-12499-gcbd994a [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Funguss** [comment]
I've noticed a few buildings still without roofs, I assumed they just hadn't been gotten to yet. Should we have a report with a checklist to keep tabs?

**Comment by curstwist** [comment]
> 
> 
> I've noticed a few buildings still without roofs, I assumed they just hadn't been gotten to yet. Should we have a report with a checklist to keep tabs?

report them.  Almost all have been done.  I have a list so I can compare it and see if something wasn't linked properly.

**Comment by Funguss** [comment]
Just done a check on ones I could remember, but they seem to be fine now. What I was trying to get at was if we needed to open a new issue for each and every occurrence, which seemed like a bit of a headache.

I've had a look in the jsons and to be frank I don't understand them at all. I spent (literally) hours the other day searching for the basic lab entrance and couldn't find it, and I don't know what you mean by adding them or how to identify if they're even missing. I've spent a lot of time and energy previously trying to understand the CDDA files, both code and json, and it seems like the exact kind of thing I'll not be able to get my head around or understand without having somebody spend a lot of their time and effort walking me through what's going on. I once managed to get the game to compile after spending an inordinate amount of time trying to get a compiler simply to run, despite going through a step-by-step guide, but even then the game .exe failed to run. Even when I've sought help the answers have been incomprehensible and failed to solve my issues, leading me to feel that I've not only failed someone else, I've wasted _their_ time as well. I thought I'd do some json edits but I couldn't get my head around github or the jsons, beyond editing a line or two in an item, and the entire thing leads to me staring at the screen for hours until I finally give up. It's thoroughly vexing and disheartening, as this is something I'd really love to be able to do but no matter how much I try I ultimately fail in ways that perplex not just myself but everyone I ask for help.

I once tried to learn C++, managed to get through a few chapters of the book written by the guy who wrote C++, and even managed to get a program I wrote from scratch to compile (when I _finally_ stopped trying to get developer suites like Code:Blocks to run) using dos commands. It was a calculator, but it didn't tell you its' calculations. It really, honestly, should have, but it interpreted 'y' as 'n', which should have been impossible.

This is why I just raise issues, it's all incredibly frustrating and disheartening. My limits are piddling little changes that will never travel beyond my PC as I can't even upload them to github.

**Comment by curstwist** [comment]
> 
> 
> Just done a check on ones I could remember, but they seem to be fine now. What I was trying to get at was if we needed to open a new issue for each and every occurrence, which seemed like a bit of a headache.

you could put several in one issue.

**Comment by Funguss** [comment]
Ah, nice one, I'll give that a look tomorrow! Right now it's going straight over my head I'm afraid.

**Comment by curstwist** [comment]
sure. it isn't your responsibility to identify all the roof problems : ).  It sounded like you already had a list earlier.

**Comment by Funguss** [comment]
Ah, no, just a mental one. I spoke up without considering the last instance I saw, which was prior to the font changes (I didn't update until they were fixed, I simply couldn't bring myself to play with that font). IIRC there were a few additions during that time which must have fixed all the ones I'd seen. The original lab was the one that stuck out most, but that may have been done for a long time. I've not had a game reach any kind of lab in quite a long time.

**Comment by Funguss** [comment]
Ah, right, so roofs without gutters and such are ones that need some work? Somehow that went straight over my head. In that case there are a few I know of, though finding them now will be slightly more troublesome.

Original style lab entrances are one, though I have no idea where they're located in the jsons. They don't seem to be anywhere that I can tell.

The neo-whatsit faction's... um... tree farm? The one with the friendly cyber dogs? That didn't have a roof IIRC.

There's at least one city gas station, too, it has three gasoline pumps, a toilet out back, and a large windowed office type space along with a small shop.

Jewellery stores with the blue walls.

Refugee centre.

Apple orchard stall and tree farm (the latter almost got me killed! So I map edited one in).

Used bookstore, though this is a Magiclysm addition IIRC so I'm not sure if it's within your scope.

That's about all for now, but I'll definitely keep my eyes peeled.

**Comment by curstwist** [comment]
Ok thanks, I knew about some but I'll check the others out. Can add cathedral to your mental list. I think thr cyber dogs must be a mod too.

**Comment by Funguss** [comment]
Yeah, probably aftershock. Cathedral roofs should be very interesting, depending on the style. I must admit I don't know what American cathedrals look like, let alone New England ones.

**Comment by curstwist** [comment]
further discussion on these issues should move to a new issue or be covered in a more casual venue like the development discord.  This single issue is fixed and should be closed since it's resolved.
