### ISSUE TITLE
Liquids are copied on player-initiated "spill"

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#38300]
# Describe the bug

# Steps To Reproduce
Load the game, `/`, move the drinking glass to the inventory with Enter, `s`pill, `c` pour into container, plastic bottle, note there's now a plastic bottle full of liquid and also the liquid on the floor.

# Expected behavior

# Screenshots

# Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.D-12517-g92b0b2c36b-dirty [64-bit]
- Graphics Version: Curses
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

# Additional context

[2019.07.17-2.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4244590/2019.07.17-2.zip)

**Comment by jkraybill** [comment]
Is this the right save file? I don't see any drinking glass:

![image](https://user-images.githubusercontent.com/1361701/75225672-3b37a180-57ff-11ea-8651-86167f15f2f3.png)

If you can reduce this bug to a test case that is reproducible in a fresh game using the spawn menu it would be very helpful! More detail such as screenshots etc will help too.

**Comment by l29ah** [comment]
Damn, i've posted a wrong save, and the proper one is gone.
To reproduce it, move to a mansion and find a drinking glass of some wine.
I couldn't make a glass of wine using debug menus.

**Comment by jkraybill** [comment]
OK, and after finding a glass of wine, what are the exact steps to repro? "s" is not a command to spill as far as I can see unless the keybindings are different (it's "smash" for me)?

**Comment by l29ah** [comment]
`s` IS a command to spill if you followed the previous commands i've described.

**Comment by l29ah** [comment]
I've produced a new repro save: 
[2020.02.22-1.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4252857/2020.02.22-1.zip)

**Comment by l29ah** [comment]
Still exists on 0.E-588-g217f4235ab-dirty
