### ISSUE TITLE
Option for auto features to work only when safe mode is on

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#38323]
# Is your feature request related to a problem? Please describe.

It would be nice to have the auto features only work when safe mode is on. For instance, if you have auto-pulp zombies on and want to run away, you may pass by some fallen zombies that get auto-pulped. They get pulped while the zombies chasing you catch up very quick.

# Describe the solution you'd like

Create option nearby the auto features options to enable auto features only when safe mode is on.

# Describe alternatives you've considered

Go into options every time I don't want get surrounded while pulping that pile of 6 corpses all at once.

**Comment by Funguss** [comment]
That's odd. I find auto pulp won't activate if there's a zombie in sight and often find this more annoying than helpful.

**Comment by OzoneH3** [comment]
Alternativley bind the key to "Toggle auto pulp/butcher"
