### ISSUE TITLE
Missions get duplicated when returning to mission-giver

### ISSUE THREAD

**Issue by jkraybill** [CleverRaven/Cataclysm-DDA#38325]
# Describe the bug

I'm not sure exactly how to reproduce this, but I'm finding that it's common for mission-givers to "forget" the mission I've been given when I return after a long absence.

The dialogue state appears reset to where it was before I got my current mission from them. I can get the dialogue state back to getting the mission, but then I get a carbon copy of the mission, and when I complete the mission, the duplicated version remains in my "Active Missions" tab.

![image](https://user-images.githubusercontent.com/1361701/75232566-8e175600-580b-11ea-811a-d2b8967d0b66.png)

In the above screenshot,

- I received the "Missing Caravan" quest, then completed it a long time later (weeks or months), during which period I had received several other quests. When I returned to the merchant, the dialogue state acted like I didn't have a mission. I had to re-request the mission, at which point it became duplicated in my "Active Missions" list. After I completed it, one copy of it remained in "Active Missions".
- Same thing happened with the Dino Dave quest "Bring a roll of duct tape". Here I have the follow-up mission, "Bring 10 medium-sized boxes", but a duplicate copy of the earlier mission is still in the list.
- Same with "Find an Electric Motor" for Jenny Forcette and "Gather bones..." for Brigitte LaCroix.

# Steps To Reproduce

It seems pretty common, but in all cases there was a lot of physical distance and time between when I got the quest and when I completed it. I have not spent time trying to get to a base repro but if I need to, let me know.

# Expected behavior

- quest-givers should not forget that they gave you a mission.
- dialogue state should not reset when you return to complete a mission.

As a failsafe,
- you should never have a duplicate copy of the same mission in your list.
- completed missions that can't be done more than once should not appear in your list when complete.

# Screenshots

Here's the screenshot of my "Completed Missions" tab from the same game, as you can see there are several duplicates of missions in "Active Missions":

![image](https://user-images.githubusercontent.com/1361701/75234240-59f16480-580e-11ea-9e51-44521e670a4f.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-12430-g142295b [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    More City Locations [cityside],
    Urban Development [Urban_Development],
    No Fungal Monsters [No_Fungi]
]

**Comment by jkraybill** [comment]
Just a little more info on this as I've been trying to find a base repro scenario in debug mode.

I thought maybe this was related to #37255, but the fact that I got it with Brigitte LaCroix tells me it's not a mission-chaining issue.

I have not successfully repro'd this in debug mode UNLESS I actually spawn a duplicate of the NPC (e.g. spawning two different religious cemeteries, get the mission from Brigitte 1, and then talk to Brigitte 2, I can get a duplicate).

I went back and checked my game where this was encountered. I do have two separate refugee centers, but I have never visited one of them (it's not even fully revealed on the OM). I could not find a second religious cemetery (not sure if that's possible).

But I wonder if, since there is a duplication scenario where duplicated NPC's don't have awareness of the other NPC's mission states, there is some scenario where, either due to save/load, or to OM generation, there's a situation where an NPC's state gets treated as if it is a different NPC than the one that already gave the mission?

I've looked through the code but it's pretty mind-bending to me.

**Comment by jkraybill** [comment]
A little more info - that particular game was the third character I played in a single world, which could be related?

**Comment by CountAlex** [comment]
> 
> 
> A little more info - that particular game was the third character I played in a single world, which could be related?

I think I've seen statements that playing another character in same world creates a lot of troubles with NPCs and quests so it's likely the case. Can't say much about what causes that but probably quests/NPCs tracking code wasn't made to track new PCs and such.

**Comment by I-am-Erk** [comment]
Does this bug reproduce if there are not multiple characters in the world? Running quests with multiple characters isn't really intended.

**Comment by I-am-Erk** [comment]
![image](https://user-images.githubusercontent.com/45136638/76011141-ed8afb00-5ec8-11ea-9574-70072901cc0d.png)
From discord, sounds like it applies with single characters.

**Comment by jkraybill** [comment]
Per request from @KorGgenT here's my save file with duplicated missions, character "Stitch"":

https://www.dropbox.com/transfer/AAAAAIG_NWUlAODKsY5aSSLbCIosEhSJ1Bol2GFpXpiJGjs2zjqzGi8

**Comment by davidpwbrown** [comment]
Tried reproducing this and could not.
I tried finding a clone of the refugee centre in a differnet location, talking to the clones there, after taking missions, then going back to original centre, missions were not reset.

Tried debug passing a lot of time, no repro.

Tried taking and completing lots of other missions in the intervening time, no repro.

jkraybill and arc confirm that its not due to playing a new character in same world as old one, so I'm kinda at a loss right now as to what could be causing it.

New ideas are here needed :(

**Comment by jkraybill** [comment]
So, I just hit this again, with quite an old mission from before my original bug report. I returned to Jenny Forcette with the 60L tank and she had forgotten that I had the mission. The mission was not active when I spoke to her, but after speaking to her to get the mission again, when I hit "M", both versions of the mission (the original unfulfilled mission, and the newly received duplicate) were both marked "active".

![image](https://user-images.githubusercontent.com/1361701/76939648-d8907c00-694c-11ea-93e2-05819975b776.png)

Here's the save file right after getting the duplicated mission, in case it helps.

https://www.dropbox.com/transfer/AAAAAKlKX5KDaqdXCfde3KCXNLwkAfcvMrxHRlp5kYHH2lxKtIWsUT8

**Comment by bouchacha** [comment]
I'm also encountering this bug. Most commonly I've noticed it happening when NPCs "forget" they gave you a quest. So if you ask for a mission, it just gets duplicated on your list. For example, I got "Kill Zombie Mom" three different times.
![Untitled](https://user-images.githubusercontent.com/19356629/92868658-d1f03800-f3b6-11ea-9401-2702deab0ee5.png)


```
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-5859-g8e8260f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Graphical Overmap [Graphical_Overmap],
    Stats Through Skills [StatsThroughSkills]
]
```
