### ISSUE TITLE
`w`elding things from the ground doesn't increase the carried weight

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#38330]
# Describe the bug

# Steps To Reproduce
Load the game, weld the 200kg storage battery, `i`, see that you apparently only carrying 54kg.

# Expected behavior
254kg.

# Screenshots
![](https://tinystash.undef.im/il/3M1fyRzyWSQdw8RWRzJYjyjGvd1tnhSZNM4aihRt468AP4Ge79aECECtWXre2NUZufJApRzUSoGuVyJYAB2fsDti)

# Versions and configuration
    - OS Version: <unknown>
- Game Version: 0.D-12549-gb54b890a66-dirty [64-bit]
- Graphics Version: Curses
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

# Additional context

[2020.02.22-1.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4250455/2020.02.22-1.zip)

**Comment by Amariithynar** [comment]
Wielding objects still weighs you down, but does not count against your inventory encumbrance or weight, which those two numbers are for. Moving about will take more time for being so overweight and also consume stamina while wielding the storage battery. Use default key "\" to drag it along the ground instead.

**Comment by anothersimulacrum** [comment]
You're near a crane, which prevents the weight penalties from wielded objects. Walk away from the crane and you will experience the weight penalties.
