### ISSUE TITLE
NPC container duplication/disappearence/transmogrification

### ISSUE THREAD

**Issue by Funguss** [CleverRaven/Cataclysm-DDA#38342]
It seems that any container can duplicate or disappear when traded to or from an NPC, including its contents, if any. It appears that, sometimes, another item is overridden, though I can't identify a pattern. It's likely based on how the item is stored in memory. I've not been able to reliably reproduce this, sometimes a trade causes duplication and disappearances, other times nothing. This may be linked with #36884 as both are issues around containers.

Edit: Wrong save! Correct save: [Bentonia.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4263261/Bentonia.zip)

~~I've not been able to identify the trigger but there's a definite duplication when trading liquids to NPCs on occasion. I've only noticed it with liquids that have freshness modifiers but it could occur with water or the like. So far I've only seen it with plastic bottles, specifically mayonnaise and one other I forget. Each duplication causes a copy to be left in the player inventory.~~

~~Edit: In this save, if you go north of the NPC there's a pile of food, including rotten orange and fruit juice. Pick up a few bottles of both and try trading back and forth. Sometimes, one will transform into the other, sometimes they'll duplicate. [Point Blank.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4253829/Point.Blank.zip)~~

~~Edit 2: Nothing to do with freshness as I had a canteen of water disappear while trading multiple. This may be linked with #36884 as both are issues around containers. I'll test out with some dry foods.~~

# Versions and configuration

# Additional context

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-12504-g9015618 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    No Rail Stations [No_Rail_Stations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Roadheader and other mining vehicles [Heavy miners],
    No Fungal Monsters [No_Fungi],
    Beta National Guard Camp [national_guard_camp]
]

**Comment by Funguss** [comment]
Trading a single item seems to work fine all the time. Trading multiple (more than one on either side, or one from each) mostly fails, generating duplicates or becoming copies of a different container already held.

**Comment by MarceloLaser** [comment]
To add to this, the inventory errors may include equipped items, and may involve items marked for trade remaining in origin inventory. To illustrate, I am attaching a save file located in front of the refugee center trader, with an inventory containing 100L worth of filthy items for trade. Attempting to trade all items in inventory will almost always result in an error of some form, and the error may not always be the same, even if items traded are. Bug is still present as of April 10.

[West Lake Hills.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4463866/West.Lake.Hills.zip)

**Comment by int-ua** [comment]
Please try reproducing in latest experimental and/or adding clear and concise steps to reproduce from scratch.
