### ISSUE TITLE
Ammunition name plurals have misplaced s at the end

### ISSUE THREAD

**Issue by snipercup** [CleverRaven/Cataclysm-DDA#38347]
# Describe the bug

The only place I can see where this shows up is when you are dropping things. In other menus I don't see it happening. Please refer to the screenshot below.

# Steps To Reproduce

1. Make a player with ammo, often the reloaded kind.
2. Go to multidrop and drop at least 1 of them.
3. Observe the s is in the wrong place

# Expected behavior

Have proper plural names for ammo. Eighter the s should be in the proper spot in the name or the plural name should be the same as the single name. Alternatively just display the single name for all items when dropping items.

# Screenshots

![image](https://user-images.githubusercontent.com/50166150/75284917-ef442700-5815-11ea-8e25-eb2f37f4d606.png)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-12500-ged49c34e0f [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Bens GF recipes [Tolerate_This],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Roadheader and other mining vehicles [Heavy miners],
    Necromancy [necromancy]
]

**Comment by Funguss** [comment]
Most of those are grammatically sound, though there are a few I'm hesitant about. My comprehension of grammar has noticeably declined the past few years... I do believe that, as they're being used as a noun, it would be acceptable to have "reloadeds" and "sportings", though I can't recall what should happen when you get "caselesss". I believe replacing the final "s" with an apostrophe is correct, but I could easily be wrong. For the FMJ and JHP rounds it's appropriate as they're acronyms, and there's no consensus as to whether an apostrophe is needed. Many American institutions demand no apostrophe in their styling guides, and as it's convenient I recommend leaving that as is. Regarding +p+s, you could read that as "plus pee pluses", which is cumbersome but still viable. I honestly have no idea what the convention on plurality when a sign is part of a noun, if there even is one. I'd guess the sign would be replaced by the word it signifies but this _is_ English, after all.
