### ISSUE TITLE
"Ate with table" morale boost gained without a table.

### ISSUE THREAD

**Issue by sharkfinsouperman** [CleverRaven/Cataclysm-DDA#38351]
# Describe the bug

I can eat a meal with no eating surface present and still get the morale boost.

# Screenshots

I'm eating inside a vehicle with no table, but the boost is present.
![image](https://user-images.githubusercontent.com/61106669/75287960-58617580-57e9-11ea-87a3-9b3902f81eb9.png)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-12445-g55cabb7 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    No Fungal Monsters [No_Fungi]
]

# Additional context

More testing may be needed as this might only occur while inside a vehicle.

**Comment by wapcaplet** [comment]
The kitchen unit in your vehicle counts as a dining table for morale purposes.

**Comment by sharkfinsouperman** [comment]
Sorry, I wasn't aware of the change.

**Comment by wapcaplet** [comment]
@sharkfinsouperman No need to apologize, it’s hardly obvious :-) I only knew about it because of some related stuff I worked on. It is not a very recent change though; looking through the history, vehicle kitchens have had tables since #29177
