### ISSUE TITLE
Inactive craftbuddy can't be used to repair vehicles (welding)

### ISSUE THREAD

**Issue by LlubNek** [CleverRaven/Cataclysm-DDA#38385]
# Describe the bug
The inactive craftbuddy can't be used for vehicle repairs that require welding.

# Steps To Reproduce
1. Get a craftbuddy
2. Add batteries
3. Attempt to repair a vehicle frame

# Expected behavior
Craftbuddy, or any tool with sufficient welding quality and enough charge, should be usable in repairs.  These repairs depend on specific tools with varying amounts of charge though, instead of depending on the welding quality.
I understand that this is to allow different tools to be more or less efficient than others, but it's too easy for a tool to be overlooked this way.  It would be better if the tool itself had an efficiency property which scaled the energy consumption instead of listing every possible welding tool in each recipe.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2004 64-bit
- Game Version: 0.D-12606-g241522e [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    C.R.I.T Expansion Mod [crt_expansion],
    Engineering essentials [EngineeringEssentials],
    Magiclysm [magiclysm],
    Generic Guns [generic_guns],
    MST Extra [MST_Extra],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    [OBSOLETE] Craftable Gun Pack [OBSOLETE_craftgp],
    [OBSOLETE] Garden Pots [OBSOLETE_growable-pots],
    [OBSOLETE] Makeshift Items Mod [OBSOLETE_makeshift],
    [OBSOLETE] Modular Turrets [OBSOLETE_modular_turrets],
    [OBSOLETE] Salvaged Robots [OBSOLETE_Salvaged_Robots],
    Crazy Cataclysm [crazy_cataclysm],
    Mining Mod [Mining_Mod],
    Mythical Martial Arts [MMA],
    [OBSOLETE] EZ-Mode Medical [OBSOLETE_fast_healing],
    [OBSOLETE] Hydroponics [OBSOLETE_hydroponics],
    Alternative Map Key [alt_map_key],
    Dorf Life [Dorf_Life],
    [OBSOLETE] Beta National Guard Camp [OBSOLETE_national_guard_camp],
    [OBSOLETE] More Locations [OBSOLETE_more_locations],
    [OBSOLETE] Fuji's More Buildings [OBSOLETE_FujiStruct],
    [OBSOLETE] Mapgen Demo [OBSOLETE_mapgen_demo],
    [OBSOLETE] Urban Development [OBSOLETE_Urban_Development],
    [OBSOLETE] Folding Parts pack [OBSOLETE_deoxymod],
    [OBSOLETE] Vehicle Additions Pack [OBSOLETE_blazemod],
    [OBSOLETE] Roadheader and other mining vehicles [OBSOLETE_Heavy miners],
    [OBSOLETE] Tanks and Other Vehicles [OBSOLETE_Tanks],
    sees-player icon, retrodays [sees_player_retro],
    Faster Stamina Regen [stamina_regen_buff],
    Fuji's Military Profession Pack [fuji_mpp],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    [OBSOLETE] Manual Bionic Installation [OBSOLETE_manualbionicinstall],
    [OBSOLETE] No Filthy Clothing [OBSOLETE_no_filthy_clothing],
    [OBSOLETE] Perfect Reliability [OBSOLETE_no_faults],
    [OBSOLETE] Prevent Zombie Revivication [OBSOLETE_no_reviving_zombies],
    [OBSOLETE] Safe Autodoc [OBSOLETE_safeautodoc],
    [OBSOLETE] Simplified Nutrition [OBSOLETE_novitamins],
    [OBSOLETE] Classes and Scenarios Mod [OBSOLETE_more_classes_scenarios],
    [OBSOLETE] Classic Roguelike Classes [OBSOLETE_RL_Classes]
 - Ingame language: English

**Comment by KorGgenT** [comment]
i don't know what mod the craft buddy is from.

**Comment by LlubNek** [comment]
It's not just the craft buddy, integrated toolset doesn't work for a lot of things it should too (mostly soldering).

Craftbuddy is from Salvaged_Robots though (grep -ri 'craftbuddy' data/*).

**Comment by Night-Pryanik** [comment]
Tested right now in 0.F-10914: integrated multitool can be used to repair vehicles, for soldering and any other activity it was designed to.
Craft buddy is from third-party mod, so it's not valid for our issue tracker.
