### ISSUE TITLE
A solution for silly spawns from eggs

### ISSUE THREAD

**Issue by Funguss** [CleverRaven/Cataclysm-DDA#38383]
# Is your feature request related to a problem? Please describe.
Yet again I've seen chicks bursting from defunct fridges in town. This feels ridiculous every time I see it, and it's a bit heartbreaking to watch all the little chicks run away from me and into the arms of a hulk. It's literally heartbreaking when they lead a horde back to you. But really, eggs need stable warmth to grow and hatch, and are sensitive to fluctuations. Even if they were fertilised in the first place having been refrigerated, or left unattended, for a day or so would certainly kill the chick.

# Describe the solution you'd like
After considering how the fish trap checks for fish within 'x' tiles for the catch rate it occurred to me something similar could be done with birds and eggs, alongside a flag that's set on whether they've been laid by a creature and aren't some you pillaged from an apartment. Just having chick spawns tied to a living in the vicinity would cut out a lot of nonsense, but the flag would stop any gaming of the system.

# Describe alternatives you've considered
Beyond getting into proper fertilisation this seems like a good medium term approach.

**Comment by kevingranade** [comment]
> a flag that's set on whether they've been laid by a creature

This is the real solution IMO, we can assume viable eggs are in a relatively sheltered environment, I'd rather not add potentially expensive environment checks to try and make things slightly better.
