### ISSUE TITLE
Jack o'lantern requires batteries, not candles

### ISSUE THREAD

**Issue by Funguss** [CleverRaven/Cataclysm-DDA#38399]
As title.

# Expected behavior

Should require candles, as stated in description. Should also be charged to max considering the candle requirement.

# Screenshots

![lantern](https://user-images.githubusercontent.com/57632331/75433126-6200ef80-5947-11ea-948f-c1fed3335150.png)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-12504-g9015618 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    No Rail Stations [No_Rail_Stations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Roadheader and other mining vehicles [Heavy miners],
    No Fungal Monsters [No_Fungi],
    Beta National Guard Camp [national_guard_camp]
]

**Comment by Qrox** [comment]
The description of the lit jack o'lantern says "There is a thick LED candle inside the pumpkin face.", so it's more like the description for the unlit lantern is incorrect.

**Comment by Funguss** [comment]
It's a bit more complicated than that. The recipe requires regular candles and not a single electronic component. Given the lit description mentions an LED it seems like two different implementations got mixed up, so it's hard to say which is correct in this scenario. On top of that, it calls for generic batteries rather than a specific magazine size, and upon examining the lit version I noticed that where the description mentions the LED candle it states it can "burn for a very long time", mimicking the description of a candle. Saying that an LED candle would "burn" is poetic but I doubt it's intended.

**Comment by LlubNek** [comment]
should maybe have a regular jack o'lantern that takes candles and an electric jack o'lantern that's made with a lightstrip

**Comment by Funguss** [comment]
That sounds about right. Is that what you were thinking originally, @Maleclypse ? Maybe the regular one can be made without a candle and so is built unloaded, and the electronic version uses this as an ingredient along with a lightstrip and maybe other electronic gubbins.

**Comment by Maleclypse** [comment]
So yes.  This was one of my first contributions and I seem to remember having a bunch of difficulties with my first implementations of magazines/item charges and transformations.  I think it would be excellent if this were corrected by breaking it into two versions.

**Comment by Funguss** [comment]
Ok, I thought I'd give it a little go and managed to get candles working like ammo and for the lantern to accept them! Sadly, existing candles become ridiculously heavy. Not sure how to overcome that one.

**Comment by Maleclypse** [comment]
Ah, is it because the candles now have charges and each charge weighs what the original weight of the entire candle was?

**Comment by Funguss** [comment]
Yep, and on top of that candles can now be combined and split at will. Also, when lit, candle stacks can now be something along the lines of "candle (lit) (110/100)". I'm thinking this could be handled by turning the candle into a magazine with NO_RELOAD, but I dunno how it would cope on expiry.

**Comment by Maleclypse** [comment]
Sounds like you have solved it?  :)  You are a rockstar!

**Comment by Funguss** [comment]
>Sounds like you have solved it? :) You are a rockstar!

:cry: Nope. I've been messing and messing, but the closest I can come involves thoroughly breaking existing candles in order to make them a magazine. Even then it just looks ridiculous to see candles listed as magazines in the inventory menu. I must say I'm not a fan of having categories decide function, it leads to situations like this. I always wondered why welding gas was categorized as a magazine (even though it is one) and now I know. Similarly, transforming candles into ammo and being able to do the old "batteries" stacking on them is a horrendous idea.

**Comment by Maleclypse** [comment]
What if a specific candle type ammo was made that is separate from existing candles but has a simple recipe like “candle, 1” and “plastic mold, 1” or something else easy to put together? It could be called “lantern candles” and then multiple types of lanterns such as glass lanterns or mirrored lighthouse type lanterns could be created that use that ammo?

**Comment by Funguss** [comment]
Well, in that case, might as well go whole hog and reload via recipe. That doesn't sit well with me as it's a step in the wrong direction, it would be better to have extended code support for scenarios like these.

Thinking about it, having the lantern set as a container which holds the candle would be best, especially with the changes to contained items coming up. Having candles require containment (in a suitable container) in order to protect them from wind when outdoors would be brilliant and also give this item some functionality.
