### ISSUE TITLE
Feature Request: Sounds-like for soundpacks?

### ISSUE THREAD

**Issue by dissociativity** [CleverRaven/Cataclysm-DDA#38397]
Soundpacks increasingly seem to have sounds not work as the game changes, smashing some windows have no sound where smashing the broken windows again does for example, some firearms don't have sounds, only the projectiles do, ect. 
Tilesets have looks-like which keeps everything that's functionally the same looking nice, why not sounds-like?

I'd happily put in json work for this if implemented, though I'm too pathetic at C++ to implement the feature itself.

**Comment by ZhilkinSerg** [comment]
You can probably just add missing sound definitions in soundpacks?

**Comment by sharkfinsouperman** [comment]
Wouldn't it be simpler to help maintain your favourite sound pack(s), or [start and maintain your own sound pack](https://github.com/remyroy/CDDA-Game-Launcher/issues/new?title=Add+this+new+soundpack+to+the+repository&body=%2A+Name%3A+%5BEnter+the+name+of+the+soundpack%5D%0A%2A+Url%3A+%5BEnter+the+Url+where+we+can+find+the+soundpack%5D%0A%2A+Author%3A+%5BEnter+the+name+of+the+author%5D%0A%2A+Homepage%3A+%5BEnter+the+Url+of+the+author+website+or+where+the+soundpack+was+published%5D%0A%2A+Soundpack+not+found+in+version%3A+1.4.4%0A) instead?
