### ISSUE TITLE
Shaving Razor doesn't let you cast blood magic

### ISSUE THREAD

**Issue by yarbelk** [CleverRaven/Cataclysm-DDA#38401]
# Describe the bug

Have shaving razor in inventory.  Try to cast necrotic gaze at C.H.U.D. Get error message "you cannot cast blood magic without a cutting implement"

# Steps To Reproduce

1. Start new game as Wizards Apprentice Necromacer subtype
2. Pick up shaving razor
3. drop stone knife
4. open door and try to cast spell at chud

# Expected behavior

be able too or have a better message.  Could just be me and razors though...
this confusion may be because it says cutting implement.  Which while this sounds nicer, stating without an implement with cutting 1 would possibly be less confusing

# Screenshots

# Versions and configuration

- OS: MacOs
    - OS Version: Name: Mac OS X; Version: 10.15.3; Build: 19D76; 
- Game Version: 0.D-12517-g92b0b2c [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by KorGgenT** [comment]
does a shaving razor not have cutting 1?

**Comment by Sumguy62** [comment]
have you ever cut yourself with a safety razor? you get these nasty shallow parallel cuts. not really what you're probably going for with blood magic anyway.

**Comment by KorGgenT** [comment]
it looks for the "cut 1" quality. not sure how else i can represent it? if it doesn' thave that quality, then it doesn't cut in game.

**Comment by sharkfinsouperman** [comment]
Neither the Shaving Razor nor the razor blade from disassembly have cutting qualities, so I assume this is not a bug and is WAI.
