### ISSUE TITLE
Selling rags to HUB1 trader creates infinite money machine

### ISSUE THREAD

**Issue by Feniks-Gaming** [CleverRaven/Cataclysm-DDA#38400]
# Describe the bug

Playing Build 10359

If you sell rags to trader at HUB1 you get credits in return, you can complete trade, come back and buy them back at $0.00 and then sell them back . Considering you can bring several 100s rags with you you can easily soon generate enough credits to buy out whole tsore. 

# Steps To Reproduce

1. Have Bartering 2 (not sure if need that is what I have)
2. Sell rags to trader at HUB1 for creddits and complete the trade
3. End a trade and re-open conversation
4. Buy Rags back for $0.00
5. End conversation
6. Repeat steps 2-5 for as long as you want to generate impossible profit 

# Expected behavior

You would expect that buying items back brings less profit or breaks even not makes infinitive loop of money.

# Screenshots:

![1](https://user-images.githubusercontent.com/30668026/75435862-8ced4280-594b-11ea-80e3-5ae7c11881b8.PNG)
![2](https://user-images.githubusercontent.com/30668026/75435870-8f4f9c80-594b-11ea-9678-992aa7e234cc.PNG)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-12517-g92b0b2c [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

# Additional context

Save File - 
[Brunson.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4261072/Brunson.zip)

**Comment by Funguss** [comment]
The fact that they want them seems to suggest that they wouldn't just sell them straight back to you regardless. That they do is probably a bug.
