### ISSUE TITLE
Document ammo_effects property

### ISSUE THREAD

**Issue by snipercup** [CleverRaven/Cataclysm-DDA#38412]
# Is your feature request related to a problem? Please describe.
The property ammo_effects used in guns is not documented

# Describe the solution you'd like
Document ammo_effects property

# Describe alternatives you've considered
Not documenting

# Additional context
I think it's strange that the watercannon uses the RECOVER_10 flag in ammo_effects and not flags. The same can be seen in #36955. That's why the documentation should tell me if that's valid.

**Comment by ZhilkinSerg** [comment]
`ammo_effects` are basically specific `flags`. Their properties started to be moved to JSON only recently in #36919.
