### ISSUE TITLE
Planting activity uninterruptible, tile is immediately planted, zone activity plants all adjacent tilled earth simultaneously

### ISSUE THREAD

**Issue by Funguss** [CleverRaven/Cataclysm-DDA#38417]
As with other activities planting remains uninterruptible. Furthermore, when using zone activities to farm, all the tilled tiles are planted at once, resulting in a very long uninterruptible task.

# Versions and configuration
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-12504-g9015618 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    No Rail Stations [No_Rail_Stations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Roadheader and other mining vehicles [Heavy miners],
    No Fungal Monsters [No_Fungi],
    Beta National Guard Camp [national_guard_camp]
]

**Comment by jkraybill** [comment]
Can you clarify this one? Plot Farming is at least usually interruptible. I run gigantic farm plots and have not seen a problem with interrupting tasks there. Can you give some more detail on what you were doing that could not be interrupted and what the farm looked like, or a base repro scenario?

**Comment by Funguss** [comment]
Really?

Ok, just tested it. It's not tilling the earth, just planting seeds. Planting is completed immediately then time passes. In order to reproduce:

1. Debug a 9x9 of dirt mound around your PC.
2. Debug spawn 9 seeds.
3. Activity zone the 9x9 with said seeds.
4. Whack on invulnerability (optional).
5. Spawn some Zs and start the zone activity.
6. You'll be warned the Zs are close, confirm you wish to stop.
7. Don't stop. If you don't have invulnerability, expect death.

If this doesn't work all I can guess is that at 6 you stopped before actually starting, so repeat but say no to the first dialogue.

**Comment by jkraybill** [comment]
Perfect, thanks for the repro.
