### ISSUE TITLE
You find a feather (x7) gives 140 feathers! 🪶

### ISSUE THREAD

**Issue by pjf** [CleverRaven/Cataclysm-DDA#38426]
# Describe the bug

When foraging, finding a single feather produces a stack of 20. My middling-survival character just found "feather (x7)" and now has a tidy 140 feathers.

Given that feathers are assumed to be those suitable for fletching (see #29703), 140 feathers is more than one would expect from a turkey, and an odd find without the rest of the bird.

# Steps To Reproduce

1. Forage until you find some feathers.
1. Look at how many feathers there are.

# Expected behavior

"You find a feather (x7)" gives seven feathers, not 140.

# Versions and configuration

```
GAME REPORT:
- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 16.04.5 LTS; Release: 16.04; Codename: xenial; 
- Game Version: 0.D-12677-g16e628ca10 [64-bit] (d9dbfbef6a3ba6a60ae8c5bb5eb490e2b44456ed with local patches)
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Filthy Clothing [filthy_morale],
    Alternative Map Key [alt_map_key],
    [DP_MOD] Indicators: REMIX [DP_REMIX_INDICATORS],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Sleep Deprivation [sleepdeprivation],
    Bionic Slots [cbm_slots],
    sees-player icon, -attitude [sees_player_less_attitude]
]
```

**Comment by Fris0uman** [comment]
Probably a duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/36938

**Comment by pjf** [comment]
@Fris0uman : Thanks for spotting this, it's absolutely a duplicate! (Closing as such)
