### ISSUE TITLE
15 planks of 2

### ISSUE THREAD

**Issue by TheGoatGod** [CleverRaven/Cataclysm-DDA#38428]
# Describe the bug
15 planks of 2 

# Steps To Reproduce

look at * construction menu and build windows

# Expected behavior

15 planks or 15 planks of 2x4 or 15 planks of 2 by 4

# Screenshots

![image](https://user-images.githubusercontent.com/56883303/75530097-93db8a00-5a0b-11ea-810b-d82caf4f2de0.png)

# Versions and configuration

any version

mods vanilla dda

# considered fix by me

change 2x4 to either 2 by 4 or planks

**Comment by sharkfinsouperman** [comment]
There's nothing wrong here.

You need 15 planks, but you have only two. Hence, "15 of 2" in red.

If you had 16 planks, it would read "15 of 16" and be in green.

**Comment by TheGoatGod** [comment]
im being dumb then haha
