### ISSUE TITLE
New starting profession idea - wheelchair cripple

### ISSUE THREAD

**Issue by SirPendrak** [CleverRaven/Cataclysm-DDA#38427]
# Is your feature request related to a problem? Please describe.

#37314 adds ability for new proffesions to start with their own pristine vehicle spawning on the nearest road chunk. With little modification of code to allow the vehicle spawn directly underneath chcaracter in some cases, you could have profession that starts already on wheelchair or just very close near to it. Also, he/she would start with both legs totally broken, no matter the starting hp from strenght or traits, probably some additional code needed there as well? 

# Describe the solution you'd like

A wheelchair cripple profession with wheelchair, 2 broken legs, 2 leg splints and a sawn-off double barrelled shotgun with 20-40 ammo for it. Survive first 4-5 days driwing your contraption and fighting for your life. Bonus if you start with high mechanic skil and start upgrade your little Deathmobile before your wounds heal up. 

# Describe alternatives you've considered

Not asking for this. But come on. 

# Additional context
Making profession itself is ez but code changes are not for someone with 0 programming knowledge. #37314 needs to be merged first too.

**Comment by GOFLUMPYOURSELFPORCAY** [comment]
wtf is this idea lol

**Comment by Daniel-Chin** [comment]
I like it.

**Comment by anothersimulacrum** [comment]
Are you interested in working on adding this? I can reopen the issue if you are.

**Comment by Daniel-Chin** [comment]
> Are you interested in working on adding this? I can reopen the issue if you are.

TFTI! I am a huge fan of the project. Sadly I don't know much c. TFTI tho! Super lit.

**Comment by anothersimulacrum** [comment]
This would just be in JSON (mostly, I'd be willing to do whatever C++ it requires), and there's [a guide for JSON contributions](https://github.com/CleverRaven/Cataclysm-DDA/wiki/Guide-to-adding-new-content-to-CDDA-for-first-time-contributors).
