### ISSUE TITLE
Metalworking/Metalurgy Skill

### ISSUE THREAD

**Issue by mkikt4743** [CleverRaven/Cataclysm-DDA#38445]
# Is your feature request related to a problem? Please describe.
No, just kinda unrealistic that you can craft wood crafts and gain skill in simple blacksmithing from it. I figured since we're doing chemistry we might as well address this.
# Describe the solution you'd like
A metalworking skill which is used to hand load ammo, forge metal items, and perform welding repairs. Ideally, this can also make it so blacksmith has less of a powerful skill start, since going to college as a blacksmith does not give you knowledge of earlier fab recipes.
# Describe alternatives you've considered
Leaving fabrication as the all around crafting skill.
# Additional context
Figure I'll look into coding, but haven't done it before. Ideally, this would include stuff like makeshift lockpicks and other makeshift metal items as low level items, and would change most smithing books and 'Welding and Metallurgy' to metalworking skill.

**Comment by Funguss** [comment]
Personally, without a more comprehensive skill system I don't see much point, same with the chemistry skill. Having every recipe gated by books would be a start, but not exactly a comprehensive fix. Whenever I'm struck by how unrealistic a skill or recipe is, I'm then struck by how unrealistic it is to get to a professional level in less than two weeks by reading a few books and making loads of fruit wine or the equivalent.

If this just comes down to adding a new skill and splitting existing recipes between them I think it would be more trouble than it's worth while bloating the skill panel even further.

**Comment by FirebrandCoding** [comment]
An extension of the current skill system being worked on for 0.F via #31610. There does not appear to be a metalworking proficiency, so feel free to suggest it.

**Comment by l29ah** [comment]
A bigger problem is that it's impossible to remove a seatbelt from a car or make a wooden wagon before thorough lockpicking practice first.
