### ISSUE TITLE
"NPC completed the assigned task" message when no task was assigned by player

### ISSUE THREAD

**Issue by jkraybill** [CleverRaven/Cataclysm-DDA#38457]
# Describe the bug

I've seen this a few times, I suddenly get a message saying "(NPC) completed the assigned task." when I have had no interaction with the given NPC.

In this example, the 2 NPCs in question were NPC's I very briefly encountered. They were hanging out the back of a gun store I raided. I opened the back door and they got angry, so I immediately closed the door and went back to my business. These two messages appeared quite a bit later (30-60 in-game minutes) when I was around the corner from them doing some work on my car.

I don't know what task they completed to do this, but the player should not get this message if they can't be aware of the task being referred to.

# Steps To Reproduce

Not sure.

# Expected behavior

I should only get a message like this if I assigned the task, or otherwise would have been aware of it.

# Screenshots

![image](https://user-images.githubusercontent.com/1361701/75608271-225a2380-5b52-11ea-8f76-e147787fc62f.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-12681-ga92612b [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    More City Locations [cityside],
    Urban Development [Urban_Development],
    No Fungal Monsters [No_Fungi]
]

# Additional context

I have seen this message several times before, but I'm not sure what causes it to appear.

It's possible this is mod-related.

**Comment by Funguss** [comment]
Ah, I reckon they're pulping corpses. That's the most common source of that message in my experience.
