### ISSUE TITLE
Exception while driving - "set trap funnel on top of terrain downspout which already has a built-in trap"

### ISSUE THREAD

**Issue by jkraybill** [CleverRaven/Cataclysm-DDA#38454]
# Describe the bug

Was driving through a densely-populated city. Hit a couple zeds with my vehicle, and got this crash. I was not doing anything abnormal, and had not been in this city before. I don't have a theory as to why this occurred.

I did get a "you hear crash!" message at the end of the turn this occurred, not sure if it's related.

# Steps To Reproduce

Not sure.

# Expected behavior

No crash.

# Screenshots

Here's my messages log, after the end of the turn in which this occurred.
![image](https://user-images.githubusercontent.com/1361701/75606637-e1a6de00-5b42-11ea-96f3-08d1b4391bbf.png)

Here's the exception.
![sc001376](https://user-images.githubusercontent.com/1361701/75606711-a527b200-5b43-11ea-9317-0744c4f347dc.png)

Debug log below.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-12681-ga92612b [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    More City Locations [cityside],
    Urban Development [Urban_Development],
    No Fungal Monsters [No_Fungi]
]

# Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4270221/debug.log)

**Comment by wapcaplet** [comment]
Observed as well in 0.E-9806-g10ba62cb47

**Comment by actual-nh** [comment]
You would appear to have confirmed it?
