### ISSUE TITLE
Crash when trying to open character info

### ISSUE THREAD

**Issue by iillyyaa2033** [CleverRaven/Cataclysm-DDA#38496]
Segfault when trying to open character info screen by pressing '@' or from ENTER-menu.

# Steps To Reproduce
1. Create new character
2. Start new game
3. Press '@'
4. 'The program has crashed.'

# Expected behavior
No crash, just char info

# Versions and configuration
 - OS: Mint 19.3
 - Game Version: 0.D-8574
 - Graphics version: tiles
 - Ingame language: Russian
 - Mods loaded: dda, disable npc needs, filthy clothing, simplified nutrition

# Additional context
Files:
        - [crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4272049/crash.log)
        - [debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4272052/debug.log)
        - [save.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/4272058/save.tar.gz)

**Comment by ZhilkinSerg** [comment]
We do not backport bugfixes to old stable versions and I cannot reproduce on latest version.
