### ISSUE TITLE
Homicidal beavers

### ISSUE THREAD

**Issue by Funguss** [CleverRaven/Cataclysm-DDA#38495]
It's all in the description. Regularly on lakes you can find beavers that go crazy for you. Sail about a bit and they'll jump out the water on occasion to maul your face. They'll chase you down no matter what, unless something else gets in the way...

![beaver backup](https://user-images.githubusercontent.com/57632331/75627288-d09fb080-5bc6-11ea-9b51-294d813fdee0.png)
![victory](https://user-images.githubusercontent.com/57632331/75627350-3d1aaf80-5bc7-11ea-9094-b9230dcfd3b9.png)

# Steps To Reproduce

1. Find a beaver.
2. Try not to die.

# Expected behavior

They will attack on occasion, but the biggest danger should be rabid ones. These all appear rabid.

Also, they really shouldn't be able to maul a zombie to death without said zombie taking exception.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-12725-ge035f12 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    No Rail Stations [No_Rail_Stations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Roadheader and other mining vehicles [Heavy miners],
    No Fungal Monsters [No_Fungi],
    Beta National Guard Camp [national_guard_camp]
]

**Comment by chrimchim** [comment]
I'll see if reducing the JSON aggression and morale fixes this, working on compiling now...

**Comment by Funguss** [comment]
Hmm... When you frequently wander about severely injured (hooray for Imperceptive Healer!) you find out that a lot of animals will gladly hunt you down, despite being normally quite placid. I think that may be skewing this a bit, though beavers have been giving me hell since before that became one of my standard traits.

My current playthrough has a farm where I saved three pigs from a horde. Thankfully they're trapped by a fence as I get spammed with interruptions when performing there as they glare at me with hostile intent. Aggression and morale may need a bit of tweaking in general terms.

**Comment by pjf** [comment]
Oh! I'd noticed this as well. I'd just assumed they were...

![zombeavers](https://user-images.githubusercontent.com/12072/75966610-79783500-5e7f-11ea-92d8-bbae7e6d32d3.png)
