### ISSUE TITLE
max steadiness does not give precise aim 

### ISSUE THREAD

**Issue by olikant** [CleverRaven/Cataclysm-DDA#38502]
Game version: build 0.D-10380

Operating system: windows 10

Tiles or curses: UNDEAD_PEOPLE

Mods active: Disable npc needs

### Actual behavior: takes less time to reach max steadiness but does not reach precise aim, if i go aim futher away i can reach an aim closer to precise, and then going back to orginal target aim was more then when i orginally aimed on it
 

![Skærmbillede (2)](https://user-images.githubusercontent.com/22219155/75633239-81c43c00-5c03-11ea-8f5e-b34cacd8760c.png)
![Skærmbillede (3)](https://user-images.githubusercontent.com/22219155/75633245-8983e080-5c03-11ea-9ea2-b6c2b9fed31b.png)
![Skærmbillede (4)](https://user-images.githubusercontent.com/22219155/75633248-8b4da400-5c03-11ea-81ca-53f3e69018e2.png)

**Comment by kevingranade** [comment]
This is working as intended for aiming at a space with no target in it. You can aim at the space, but without a target in the tile you can't aim further than that.

**Comment by olikant** [comment]
allright, but it still seems odd i can get a better aim by aiming at a space futher away first and then aiming back at the orginal. Amaybe i just have bad memory but i also remember being able to get precise aim on just an empty tile

**Comment by olanti-p** [comment]
You can also get better aim by aiming at a nearby tile with a creature in it then moving your aim back to the tile you want to shoot.

**Comment by kevingranade** [comment]
> i also remember being able to get precise aim on just an empty tile, but guess that's just me

It's a recent change.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/so-how-does-firearm-aiming-work-internally/22959/1
