### ISSUE TITLE
Full butchery on large animals

### ISSUE THREAD

**Issue by AncientSion** [CleverRaven/Cataclysm-DDA#38500]
If you want to butcher large animals, you need rope and a tree or a table or a meathook etc.
I think you should also be able to use a vehicle Steel Boom to be able to full butcher an animal.

Right now i killed a 380 kg moose in an open field and i cant carry it. I dont want to quarter it and my cars steel boom which i believe SHOULD work in theory, isnt featured yet.

**Comment by Tamiore** [comment]
Are you sure you can't just lift the he moose whole standing with zone of effective of the crane and then simply drive home with said moose in your hands?

**Comment by AncientSion** [comment]
No im not sure thats possible. I didnt think it would be. Even if it was, i would rather still use my steel boom as a tree / hanging replacement.
