### ISSUE TITLE
Prying out nails has no prompt to interupt and stop.

### ISSUE THREAD

**Issue by Dacendeth** [CleverRaven/Cataclysm-DDA#38517]
# Describe the bug
Prying out on a boarded up door can take over 30 seconds, If you start the task and in those 30 seconds a zombie happens to pop up next to you it gets the whole 30 seconds of hitting you as there's not prompt that asks you if you want to stop.

# Steps To Reproduce
1. Stand near a boarded up door
2. Spawn a zombie somewhat close to you
3. Pry out nails and watch as time just fast forwards towards your potential death.

# Expected behavior

For a prompt of zombie spotted/zombie near/you were hurt/etc to give me the option to stop the task.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-12783-gbd7c154 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

**Comment by sharkfinsouperman** [comment]
You'll also keep prying the nails out after zeds have already splintered the door or window.

**Comment by Funguss** [comment]
It should be moved to an activity, basically. Along with lockpicking.
