### ISSUE TITLE
Sourdough recipes allow duping of glass jars.

### ISSUE THREAD

**Issue by Slimyreg** [CleverRaven/Cataclysm-DDA#38524]
# Describe the bug

In  Cataclysm-DDA/data/json/recipes/recipe_food.json a recipe is made to allow for the creation of sourdough cultures, the recipe includes a glass jar. Although it's output is multiplied by two (the result multiplier is 2), this makes two sourdough_split entities.

These are freshly fed sourdough starters, and they can be simply disassembled for another jar. Whilst the sourdough is lost in doing so, a new jar is created. The path which it is uncrafted is simply in data/json/uncraft/food/sourdough.json

data/json/items/comestibles/bread.json Contains the sourdough_split entity itself, which ingame is named freshly fed (etc...)

# Steps To Reproduce

1. Debug in sourdough starter materials.
2. Make dough, wait.
3. Open both resulting freshly fed doughs.

Although the code simply states that you will get two uncraftables, and if it is to be believed at all, you will get two jars. By constantly remaking sourdough you can instead use the dough product to make 'jars' instead of bread.

# Expected behavior

In order for the sourdough to reproduce whilst the jar does not, the jar has to be able to contain the duplicate dough. As it stands, a new jar is manifested because it is multiplied in a recipe. Only the dough itself should reproduce, so a workaround is needed.

# Screenshots

No need.

# Versions and configuration

Every version since sourdough was added I think?

# Additional context

I suspect a form of bacterial evolution has somehow allowed for the transmutation of some elements into others. Blob foul play suspected.

**Comment by Slimyreg** [comment]
What I mean by 'dough reproducing' is actually 'yeast and bacterial cultures', the dough itself should not reproduce. So, given that, if allowed I'll remove the multiplier on creation and call it fixed.

You just have to use up the yeast every time you make sourdough, which is fair?

**Comment by Slimyreg** [comment]
False alarm. The recipe isn't duping jars, the reason that two jars exist is because one jar is used to make the starter that is used in the splitting recipe. When making the split, you use a jar, thus, with one jar accounted for, no duping is done.

**Comment by kholat** [comment]
Well if you make the Jouvenile sourdough recipe and wait for it to be activatable; activating it gives sourdough. Now you can ofc craft bread with this sourdough, but the glass jar is gone into the eternal abyss of your ram? Local power plant? Something along those lines.

**Comment by Slimyreg** [comment]
When you craft the bread, the sourdough is already split. Basically the new sourdough starter you get from cooking bread also contains the jar. The original item is using the jar up in the cooking process, but we're pretending that the jar is just shifted to the new sourdough starter you get when doing the cooking.

**Comment by kholat** [comment]
I still think this isnt fine though.
