### ISSUE TITLE
Zombies hate the player the most and will attack one when have to choose

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#38522]
# Describe the bug

So it's impossible to use NPCs and other neutral animals as a meat shield while fighting zombies.

# Steps To Reproduce

Beat a zombie together with a NPC. Every zombie attack will be directed at you if both of you and the NPC are in the next tile.

# Expected behavior

Zombie attacking a random enemy every time or picking an enemy randomly.

**Comment by Funguss** [comment]
Ah, yeah. This applies to all hostiles I believe, beavers prefer you to zombies if they have a choice, for example.
