### ISSUE TITLE
Magiclysm - Cold damage type spells will not damage creatures lacking WARM flag.

### ISSUE THREAD

**Issue by foulman** [CleverRaven/Cataclysm-DDA#38525]
Cold damage spells such as ice spike, will not do damage to any monster without the 'WARM' flag, this includes things like rattlesnakes, giant roaches, and eyebots. Spell damage will 'reflect' off the monster's hide regardless of damage amount.

# Expected behavior

Cold spells should be intense cold and damage anything and everything.

# Screenshots

# Versions and configuration

# Additional context

**Comment by foulman** [comment]
Traced down to this:

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/monster.cpp#L1444

Oddly this does not stop ranged weapons or melee attacks that deal cold damage, just spells.

**Comment by Fris0uman** [comment]
That cold damage thing seems inherited since more than 6 years ago, I guess it was meant for robots initially.
