### ISSUE TITLE
Aiming near a target with one of the preset aims causes a endless aiming loop until it crashes or something interupts you.

### ISSUE THREAD

**Issue by Dacendeth** [CleverRaven/Cataclysm-DDA#38541]
# Describe the bug

If you aim at the ground with one of the preset aims, precise aim for example while any hostile/npc is in range of your weapon the game will pass turns rapidly until a crash or a hostile hits you. It will not do this if no target is in range of your current weapon.

# Steps To Reproduce

1. Spawn in the evac shelter as a character with a gun, military recruit for example with an npc in the room with you
2. Try to aim at at the floor near the npc and press P for precise aim
3.  The game will hang, constantly spinning aiming at the top until you click the mouse and it crashes, or until enough turns pass for a hostile enemy to wander in and interrupt your aim with damage.

# Expected behavior
For aim to go to full steady and stop.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-12808-g5d392c0 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by KorGgenT** [comment]
Confirmed reproduction.
