### ISSUE TITLE
Dynamo Flashlights

### ISSUE THREAD

**Issue by Ensalt** [CleverRaven/Cataclysm-DDA#38564]
# Issue
I've tried out the latest experimental build just recently and was surprised to find out that no Dynamo (hand-cranked) Flashlight existed yet, at least not in the debug menu. It's not like it's an unrealistic feature, hand-cranked torches have existed for a long time. 

# Solution
I suggest adding a Dynamo Flashlight-variant which will take 10-30 minutes to reload, requires no batteries or external power source, but drains stamina and reload speed should be based on the Strength stat. Perhaps it should even imply a strength penalty for about 30 minutes after reloading it (Simulates hand fatigue). Its light radius should definitely be lower than it's battery-powered counterpart. It should use 1 charge every 20-30 moves (or more) and have a smaller (or bigger?) charge capacity than a battery-powered flashlight. Should probably spawn when disassembling survival kits, or spawn in LMOE shelters, houses, apartments, pawn shops and the like, but would have a smaller spawn chance than a battery-powered flashlight.

# Alternative solutions
Dynamo lamp: lasts longer, takes longer to reload, has a smaller light radius, basically an electric lamp that uses muscle as an energy source.

**PS** (I haven't found any similar posts or suggestions about a dynamo flashlight so I'm not sure if there already is one)

**Comment by Funguss** [comment]
We have the hand charger for batteries now, so while this is a common item I'm not sure there's much call for it. I guess it would give options and could spawn more frequently in houses and such.

**Comment by sharkfinsouperman** [comment]
With the number of batteries that can be unloaded from zed dropped electronics, the hand crank generator is nearly unnecessary as is and I've not needed it once so far. As cool as this idea is, do we need another item added to the game simply because it *can* be, but hasn't?

**Comment by Funguss** [comment]
The more I think on it the more I like it. Would see use in the wilderness, maybe a mine start, low loot drops, any future changes to charges for batteries from zombie loot, night-time crafting when power is scarce (especially winter)... The biggest use I see for it is in camping, especially for wayfarer traits. Would make a good profession item, too.
