### ISSUE TITLE
game crash - unknown issue

### ISSUE THREAD

**Issue by barty68** [CleverRaven/Cataclysm-DDA#38607]
# Describe the bug

Well, my game crashed to desktop and i dont know the issue. I have maintained this save for less than a year(via the cdda-Launcher)  and experienced a lot of errors over this time, and i have nothing done about it. Normally i just hit "i" to ignore error. I'm posting this in hope it helps fixing "issues" with this great game. 
Thanks out to kevin and any other contributor to Cataclysm!

# Steps To Reproduce

Well i guess my savefile is some way before the crash and i don't know the problem, but here is what i have done since last save: 
-fulfilled the quest for 200 2by4´for the prospect place ranch
-drove south to raid town
-killed some Zs
-a skeletal juggernaut smashed on a wreckage
-crash

# Expected behavior

stable game experience...

# Screenshots

none

# Versions and configuration

 - OS: Win10 64-Bit
 - Game Version: 0.D-05939-g7a6b00b]
 - Graphics version: Tiles; dead people
 - Ingame language: english
 - Mods loaded: Dark Days Ahead and disable NPC needs

# Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4301170/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4301171/crash.log)
[Rich Valley.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4301179/Rich.Valley.zip)

best wishes
barty

**Comment by Qrox** [comment]
Your game version is from 8 months ago. That was before backtrace for windows was fully implemented so the crash log isn't very helpful either. Maybe you should update your game and see if you can reproduce the crash?

**Comment by barty68** [comment]
Thank you for the hint Qrox, i got my self fooled by prompt appearing when i hit "update game" in the launcher, wich says "Your game is already up to date. [y]:Update anyway; [n]:I don't need to update." I never checked which actual version I'm running, so apparently i never updated the game.

However i now have updated to "0.D-13003-gd59d380" and experienced another crash to desktop. 
It can be reproduced by unloading the motorbike from the bike-rack. 

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4311824/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4311825/debug.log)
[Rich Valley.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4311829/Rich.Valley.zip)

    OS: Win10 64-Bit
    Game Version: 0.D-13003-gd59d380
    Graphics version: Tiles; MSXdead people
    Ingame language: english
    Mods loaded: Dark Days Ahead and disable NPC needs

I'm guessing this is a bug caused by skipping lots of builds and wouldn't occur with a vehicle build on the latest version, Because of this i didn't open a new issue and put the new crash report here.

Another thing, over the update a lot of my food got rotten, like raw noodles and other long lasting stuff including food in the freezer. I believe this is intended behavior due to changes to shelf life, but its still a little bit odd.

**Comment by Qrox** [comment]
> over the update a lot of my food got rotten

That sounds to be caused by the 1-second turn change (#30253). That initial PR didn't handle migration of saved turn values, so saves created between it and the later fix (#36576) would time-travel forward.
