### ISSUE TITLE
Remove toolmod broken

### ISSUE THREAD

**Issue by IlGriS** [CleverRaven/Cataclysm-DDA#38617]
# Describe the bug

Use toolbox or screwdriver with "Remove tool mod" cause "You don't have any modified tools" always.

# Steps To Reproduce

1. Make a player with 'UPS conversion mod' and flashlight and screwdriver.
2. Install UPS mod on flashlight.
3. Try remove mod with screwdriwer.
4. Get "You don't have any modified tools"  message.

# Versions and configuration

Game Version: bb88c2ed587afa2468baaf84447bed5ef681d004
Mods loaded: None

# Additional context

Obviously this bug added in https://github.com/CleverRaven/Cataclysm-DDA/commit/a8d7ad54364eb592b1779be9503cd6ab0ef8e693 commit

**Comment by sharkfinsouperman** [comment]
@Night-Pryanik, this is not a bug and is working as intended. You cannot remove UPS or battery conversion mods after they've been installed, and it warns you of this when you attempt to install them.

![image](https://user-images.githubusercontent.com/61106669/76147536-5b6f2800-606b-11ea-8edb-917f1eb38660.png)

**Comment by IlGriS** [comment]
But this message was shown before the "remove toolmod" option was broken.
See 4422e40b6a1c46b68f709f0b99261a39efa6add4 3 Aug 2017 been added this message, but 'remove tool mod' option has been normal work.
I believe this message only means that mod cannot be removed without a screwdriver or something like that.

**Comment by sharkfinsouperman** [comment]
> I believe this message only means that mod cannot be removed without a screwdriver or something like that.

[permanently _adverb_ : always and forever](https://dictionary.cambridge.org/dictionary/english/permanently)

So "Permanently install..." means you will not be able to remove it.

This applies to all electronics power source mods and is intended. Tools still remove weapon mods, which is also intended.

**Comment by Night-Pryanik** [comment]
Yeah, invalid.
