### ISSUE TITLE
Keybind issue (Android)

### ISSUE THREAD

**Issue by GiesOther** [CleverRaven/Cataclysm-DDA#38614]
# Describe the bug

Bug does not allow me to add keybinds or use on screen keyboard commands

# Steps To Reproduce

1. Open world and char
2. Open keybind
3. Move a unbound  command to the (a) spot
4. Press + 
5. Try to add a keybind (In my case I was trying to add debug key)
6. Press (a) 
7. At this point it should have added (Backspace) as a key before you could
8. You should also feel your phone vibrate twice like it was pressed twice(but it was only pressed once)

# Expected behavior

I expected to be able to add my custom keybind
*Becuase thats a feature*

# Screenshots

**NOT APPLICABLE**.

# Versions and configuration

 - OS: [Android galexy S5]
 - Game Version: [from the main menu, e.g. 0.C-29938-g90f5268437]
 - Graphics version: [Tiles or Terminal]
 - Ingame language: [English]
 - Mods loaded: [All current mods in experimental]

**Comment by GiesOther** [comment]
If something was done wrong Im sorry this is my first time doing a bug report on github I had to make a acc to do this :D

**Comment by anothersimulacrum** [comment]
All the information is missing from the report for some reason.  Is it there when you click edit?

**Comment by ZhilkinSerg** [comment]
It is there commented out.

**Comment by ZhilkinSerg** [comment]
Can you report exact game version?

Also which keyboard app do you use (was it a stock Samsung keyboard, recommended Hacker's Keyboard or something else)?

**Comment by GiesOther** [comment]
Sorry I have been busy so if I dont answer right away I apologise. I was
using stock Samsung Galaxy S5 keyboard and I think I figured out why this
glitch is occuring.
When I turn of auto correct and next word guessing the game works fine and
how its supposed to.
