### ISSUE TITLE
Fuel count of mounted vehicle is shown in raw units instead of liters/gallons/whatever

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#38620]
# Describe the bug

If you have a vehicle mounted on another vehicle using bike rack, its tank(s?) content is shown not in whatever unit of measurement is selected in options menu but in basic units(milliliters, I guess) instead.

# Steps To Reproduce

1. Make a couple of vehicles, one with bike rack big enough for the other
2. Refill tank of mountable vehicle
3. Mount it on other vehicle
4. 'e'xamine resulting vehicle and look at tank contents.

# Expected behavior

All tank contents shown in uniform units of measure.

# Screenshots

![cataclysm-tiles_2020_03_07_23_00_03_168](https://user-images.githubusercontent.com/56833396/76146845-fcd89700-60c8-11ea-880d-81aa946387b9.png)

# Versions and configuration
- OS: Windows 7 x64
- Game Version: 0.D-12917-gdccc2bf [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Aftershock [aftershock],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills],
    Magiclysm [magiclysm]
]

**Comment by CoroNaut** [comment]
I think I'd prefer the option to have it all in raw units or all in liters/gallons for not only vehicles, but all containers in general. Its hard to figure out how much you are gonna fill a vehicle when some of the handheld containers for liquids are in raw units and then get converted when inside a vehicle.

**Comment by jkraybill** [comment]
I fixed the bug of mounted tanks not showing L volume. @CoroNaut I think your suggestion is decent but probably warrants a spec'd out feature request as I'm not sure how it would best be handled.
