### ISSUE TITLE
Balance: Greatly nerf turret ammo drop, nerf dead soldier dropsite

### ISSUE THREAD

**Issue by AncientSion** [CleverRaven/Cataclysm-DDA#38638]
When you a kill a turret (in a lab) you apparently receive 500 units of NATO ammunition.
In regards to realism, it stands to reason the number should be variable instead of being flat 500. 
In addition, this apparently assumes the turret was fully loaded when the world was stlll fine and the turret apparently never fired a single piece of ammo.
As it stands, the "metagame" (if such a thing exists) is: Find a turret. Kill it. Live long and prosper.
Please nerf this considerably.

In addition, just saying this: If you throw a grenade (1 is enough to kill a turret), you still get 500 pieces of ammo.

On a similar vein, there is a open field tile that spawns 4 to 6 dead soldiers with full gear. Among them tier 1 assault rifles with 2 to 4 mods on them. Again, this is a "metagame" where you find vehicle early game and just drive for some hours to find said tiles. Once you find it, you are set for life.

Lastly, i think the same thing can happen with Heli crash sites, except these are guarded by Operators AFK.

I think both (the first two) of these events / tiles should not be "abusable" as is this right now.
- Change turret fixed ammo in some way or fashion
- strongly nerf dead soldier loot in regards to amount and quality.
- Maybe adding a couple of live Z soldiers to the soldier side can work, but note that people can just lure them away, or kite them to the grab M4 +4 wtih enough ammo that way.

**Comment by Maleclypse** [comment]
Did something change because I thought there was at least one build where turrets started with a thousand rounds and then dropped whatever they hadn’t used by the time you killed them. I recall killing several turrets that were practically empty, though maybe that was mod interactions.

**Comment by Amoebka** [comment]
5.56 CROWS start with 1600 rounds currently.
.50 ones have 400-500, as far as I remember.
This has been discussed before, and the consensus seems to be that the amount should be random and decrease as the world ages (to simulate turrets shooting things over time), but no PR adressing this has been made.

As for rifles being easy to come by, that's unlikely to change. It's realistic to find rifles lying around dead soldiers, and there are a lot of dead soldiers when the world ends. Ideally rifles should be nerfed in some other fashion, for example drastically increasing penalties for making a lot of noise firing (hordes converging on your location in a reasonable amount of time, spawning additional security in labs, etc).

**Comment by AncientSion** [comment]
Perhaps one way to nerf these rifles is that they come in heavily used condition. So they were fired a lot and in addition they had to weather rain and stuff over the weeks when they were laying on the field.

**Comment by mrkybe** [comment]
> Perhaps one way to nerf these rifles is that they come in heavily used condition. So they were fired a lot and in addition they had to weather rain and stuff over the weeks when they were laying on the field.

Most starts are 1-3 days after the cataclysm, so they were laying in that field for at most a week.

**Comment by nphyx** [comment]
Dropping a firearm unceremoniously in the dirt is never a good idea, no need to wait weeks or months. Especially if you fall on top and bleed all over it.

https://github.com/CleverRaven/Cataclysm-DDA/pull/34240 adds more realistic fouling mechanics, and if I'm reading the diff right it looks like you can add fouling probabilities to JSON? So maybe you just need to go add in a high amount of fouling to dead soldier gun drops to solve the problem.

That would already mean they're unreliable when found, and getting them fully functional is gated by access to a gunsmith or firearm repair kit, or at least a pipe cleaner, which you wouldn't have if your metagame was to immediately find a car and then cruise around looking for dead soldiers.

**Comment by EvgenijM86** [comment]
If turrets used their ammo there should be corpses lying around, assuming it was shooting at zeds. Because zeds will just charge at it without any strategy and either zed or the turret will die as a result.

**Comment by sayke** [comment]
Helicopter crash sites are _way_ too common. Some other body sites might be a little too common too but helicopter crash sites are where anybody can relatively easily get an M4, and be basically unstoppable, after just driving around for a while.

Besides, it's not like there should a dozen helicopters falling out of the sky in the same several-square-mile area.

Also, turrets shouldn't have that much ammo. Sure, it's possible to fit a Protector RWS (aka CROWS II) with an ammo box designed to hold 1600 rounds of belted 7.62, but they're often fitted with a 500 round box, so it would be just as realistic (while being better for balance) to do that.

Those two changes would greatly help balance I think.
