### ISSUE TITLE
Moving items into cart caused game to freeze up

### ISSUE THREAD

**Issue by IndirectCell** [CleverRaven/Cataclysm-DDA#38644]
Game freezes when i use , (move all) button in advanced inventory?

# Steps To Reproduce

Requirements: Have a shopping cart your dragging and random items on ground.

/			Open advanced inventory manager.
Shift+D		This changes the first inventory to the Shopping cart.
Tab			Changes the inventory selection.
Shift+A		This changes the second inventory to everything around.
,			This moves everything.
????			Game now freezes

# Expected behavior

All items that was on ground is now in shopping cart.

# Screenshots

<img width="960" alt="crash" src="https://user-images.githubusercontent.com/60559077/76165071-5afe8c00-6154-11ea-946a-721cf347dfed.png">

# Versions and configuration

Build version: 0.D-12846-gd972c1c

# Additional context

If i press enter to select a single item, the game doesn't freeze and performed expected outcome.

Major downside to single item movement is if theres TONS of items as the inventory manager seems to "reset" after picking up a single item, requireing me to setup the inventorys again, Shift-D TAB Shift-A Enter.

I would enter the inventory management resetting itelf after every item as a bug, but usually when i use it i close the inventory after anyway as i only wanted that item, if i wanted multiple ones i would rather want to use the , key and move all items in my filter.

**Comment by Fris0uman** [comment]
How many item did you try to move? Because looting shelves in a grocery store like that I don't get the freezing

**Comment by jkraybill** [comment]
I tried reproducing this and also could not. I thought maybe this could be NPC-related, so I also spawned 12 NPC's immediately before loading the cart. I didn't get this error, and while the cart loading was a bit slower than normal it wasn't actually slow.

However upon loading the cart I did receive this error:

![image](https://user-images.githubusercontent.com/1361701/76182458-1a1c7b00-6219-11ea-917b-e511e9ca7b89.png)

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4304633/debug.log)

As I was loading the cart, before getting this error, I got a whole bunch of "first contact" NPC dialogs that I went through, one per NPC, and none of them turned hostile.

I kinda doubt this is the same error as being reported here but maybe it's somehow related.

**Comment by IndirectCell** [comment]
> 
> 
> How many item did you try to move? Because looting shelves in a grocery store like that I don't get the freezing
> 
> EDIT: I spawned 3000 emrald and sivler ring in three 1000 stack plus the loot from the grocery store and moved everything into the cart and didn't get any freezing

15 items as you can see in the image, i havent tried this yet as i havent found another cart in a different game yet, but im sure to try it again.

**Comment by IndirectCell** [comment]
> 
> 
> I tried reproducing this and also could not. I thought maybe this could be NPC-related, so I also spawned 12 NPC's immediately before loading the cart. I didn't get the issue reported here, and while the cart loading was a bit slower than normal it wasn't slow (maybe 1-2 seconds).
> 
> However upon loading the cart I did receive this error:
> 
> ![image](https://user-images.githubusercontent.com/1361701/76182458-1a1c7b00-6219-11ea-917b-e511e9ca7b89.png)
> 
> [debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4304633/debug.log)
> 
> As I was loading the cart, before getting this error, I got a whole bunch of "first contact" NPC dialogs that I went through, one per NPC, and none of them turned hostile.
> 
> I kinda doubt this is the same error as being reported here but maybe it's somehow related.

I found another shopping cart

<img width="960" alt="crash1_2" src="https://user-images.githubusercontent.com/60559077/76230028-6a003f80-6223-11ea-9a94-b396e9f9e21d.png">

same result the instant i press , hard to tell from your screen but can you take a screenshot prior to pressing , to loot all?

**Comment by KorGgenT** [comment]
Do you have a save with your exact circumstances? that might help us narrow it down.

**Comment by KorGgenT** [comment]
![image](https://user-images.githubusercontent.com/30208401/76375482-54227580-631c-11ea-8666-cfd3a8273136.png)
was unable to reproduce: i spawned a grocery store and filled the cart up with everything in the store with D and A and `,`
