### ISSUE TITLE
Allow in-game customization of map extra auto-note styles

### ISSUE THREAD

**Issue by natsirt721** [CleverRaven/Cataclysm-DDA#38648]
# Is your feature request related to a problem? Please describe.
With the 'auto map extra notes' option enabled, the character/color combination is always a yellow 'x'. When many categories are enabled, this makes it hard to tell at a glance from the map which 'x's correspond to which extras.

# Describe the solution you'd like
Add an option in the Auto Notes Manager to set the character and color of each map extra on the overmap. Possibly let the entire note message be customized. These settings should persist between saves, even though they may not appear in the menu due to not having been discovered by that character yet.

# Describe alternatives you've considered
Mainline a unique set of characters and colors in map_extras.json rather than let the user customize them, but as the json entries for character and color already exist this seems like a halfway solution.

**Comment by jkraybill** [comment]
I would love if extras used different marks on the map, and FWIW I would be totally fine with not being able to customize them in-game (that feature seems like a lot more work than just using different markings).

**Comment by Amoebka** [comment]
As mentioned, you can already customize marks and colors by editing map_extras.json, it's just inconvenient because updating the game overwrites the file every time and you can't separate it into a mod.

**Comment by jkraybill** [comment]
@Amoebka - absolutely. I think it would be nice if the defaults were separated into a few different classes of markers and colors. I took a look at all the markers and I think a handful of different character markers with a few colors each would be pretty viable. I'm not going to do anything about it for now but can take a pass post-0.E if this issue is still open.

**Comment by KurzedMetal** [comment]
> As mentioned, you can already customize marks and colors by editing map_extras.json, it's just inconvenient because updating the game overwrites the file every time and you can't separate it into a mod.

This need a UI despite we can change it from a file, so everyone can access it (they may not know of this file, or they don't know how or what to change)

**Comment by natsirt721** [comment]
I'm going to take a stab at this one, should be a pretty easy way to dip my toes in. Will be gathering feedback about UI on the discord

**Comment by int-ua** [comment]
There is a solution now available at the aforementioned forum thread.
