### ISSUE TITLE
Errors when loading saved game

### ISSUE THREAD

**Issue by snipercup** [CleverRaven/Cataclysm-DDA#38645]
# Describe the bug

This happens ever since I pulled the latest master today. When loading my game these errors show up during load
 DEBUG    : invalid recipe id "mosin44_ebr"

 FUNCTION : const T& string_id<T>::obj() const [with T = recipe]
 FILE     : src/recipe_dictionary.cpp
 LINE     : 60

 DEBUG    : invalid recipe id "mosin44_ebr"
 DEBUG    : invalid recipe id "mosin91_30_ebr"
 DEBUG    : invalid recipe id "l_car_223"
 DEBUG    : invalid recipe id "l_lmg_223"
 DEBUG    : invalid recipe id "l_dsr_223"

Was probably introduced by #37979

# Steps To Reproduce

1. Pull the latest master and  build it
2. Load save game
3. Observe errors

# Expected behavior

Not show any errors

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-12972-g9184b0f260-dirty [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by tenmillimaster** [comment]
I went and double checked that the entries in question were added to `recipes_obsolete`. They're there.

As a test, I deleted those entries from the migration list, and the 'invalid recipe' errors went away.

Thus, I believe the recipes are getting migrated before they're getting obsoleted.

**Comment by JeanLucVanDamme** [comment]
Confirmed, and my game crashes after these messages (save doesn't finish loading.)

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-12968-g89b9a2a [64-bit]
- Graphics Version: Tiles

**Comment by Maleclypse** [comment]
0.D specific error.
