### ISSUE TITLE
Crashing car through roof of mall.

### ISSUE THREAD

**Issue by IndirectCell** [CleverRaven/Cataclysm-DDA#38668]
# Describe the bug

I was driveing and haveing fun on the roof and i accidently went over what i assume is glass.
Infinite sources of "An error has occured!" came afterwards.
I think the car went down a z layer but the driver is still on the roof as im still in controll of vehicle.
I mean if i hold space enough to skipp errors i can still do checks but not movement as that triggers the error to continue.

# Steps To Reproduce

Find a mall, get ontop of it, if it has small vehicles like the ones i found (golf cars?).
Drive over glass.
An error has occured!

# Expected behavior

Eject player from vehicle, drop vehicle and damage it if not downright destroy it, drop player make landing checks, carry on with life without legs or spine or whatever the damage is. (possibly a source of where haveing adamantium skeleton would come in handy.)

# Screenshots

<img width="960" alt="crash2" src="https://user-images.githubusercontent.com/60559077/76227113-15f35c00-621f-11ea-9c6c-81b908de89d4.png">

# Versions and configuration

Platform     : Windows_x64
Graphics     : Tiles
Build number : #10392
Build version: 0.D-12846-gd972c1c
Major version: 0.D

# Additional context

<!-- Add any other context about the problem here.

Standard world, standard citys, but with zombie spawns turned to 0, 9999 duration after cataclysm, start as infected, i noticed slowdowns in areas where there was vast amount of chickens and snakes, also theres fungus enemys about that seems passive.

**Comment by IndirectCell** [comment]
Forgot to mention, i didnt expect to find vehicles on the roof as iv read around on google about vehicles in the game and how they dont interact well with factions\camps ect, not that i was able to find a firestation to setup base in anyway.

**Comment by Funguss** [comment]
Aha, you drove through a skylight I assume, I don't do tilesets. Skylights are really weird. They're an amalgam of roof and open air; sometimes they act like a roof, but mostly they act like open air. Rain falls through them, for example. Nice find!

**Comment by IndirectCell** [comment]
> 
> 
> Aha, you drove through a skylight I assume, I don't do tilesets. Skylights are really weird. They're an amalgam of roof and open air; sometimes they act like a roof, but mostly they act like open air. Rain falls through them, for example. Nice find!

honestly, i wouldnt mind if there was no vehicles to drive around on ontop of rooftops, alternatively i would just remove the skylights and or do like some labs do and give them solar panels and light or something like that. probebly not a fix, and this isnt something thats gona crash a game unless a player does exacly what i did, wich is highly probable the first time they drive on the roof :)

**Comment by Funguss** [comment]
Well, skylights are neat and they make sense for a mall I reckon. Once they're fixed up it should be fine.

I don't really see a problem with someone driving wildly around on the roof of a building accidentally plunging through a skylight, it's just the errors that need solving.
