### ISSUE TITLE
UPS does not use power when UPS and tool are both on ground

### ISSUE THREAD

**Issue by dzerus3** [CleverRaven/Cataclysm-DDA#38662]
# Describe the bug
Using UPS and a tool which uses UPS charge while UPS and tool are on the ground does not use up any UPS charge. Applies both to tools which use UPS by default and modded tools.

# Steps To Reproduce
1. Take a player with a UPS and a tool which uses the UPS (hotplate with UPS conversion mod)
2. Drop the UPS and tool on the ground
3. Attempt to perform an action with the tool while next to the dropped UPS (crafting works as well)
4. UPS power level does not go down

# Expected behavior

UPS power level should go down as it does when the UPS is located in inventory

# Screenshots

**Starting off (UPS has exactly 1238 charge)**
![image](https://user-images.githubusercontent.com/60197566/76183483-98f1c380-61d9-11ea-838b-06abd1403125.png)
**Dropping UPS on the ground**
![image](https://user-images.githubusercontent.com/60197566/76183519-b757bf00-61d9-11ea-9e85-29319975e157.png)
**Crafting Water**
![image](https://user-images.githubusercontent.com/60197566/76183536-ce96ac80-61d9-11ea-8b7f-5232ba5b4126.png)
**Water finishes crafting**
![image](https://user-images.githubusercontent.com/60197566/76183618-1f0e0a00-61da-11ea-85cd-36123edb53af.png)
**UPS power level is still 1238**
![image](https://user-images.githubusercontent.com/60197566/76183649-32b97080-61da-11ea-8cfe-0dab30204c39.png)

# Versions and configuration
- OS: Linux
- Game Version: 0.D-12981-g2dbeade39a [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

Self-compiled on Linux. Also covered in #38618, with poorer formatting. Also may be related to #38661; discovered this while reproducing it.

**Comment by jkraybill** [comment]
Also logged in #38618, this one has more detail.
