### ISSUE TITLE
Craft fails when crafting with adjacently placed UPS

### ISSUE THREAD

**Issue by dzerus3** [CleverRaven/Cataclysm-DDA#38661]
# Describe the bug

Using UPS and a tool which uses UPS charge while UPS is on the ground and the tool is in the inventory fails. Applies to tools modded with the UPS conversion mod.

# Steps To Reproduce

1. Take a player with a UPS and a tool which uses the UPS (hotplate with UPS conversion mod)
2. Drop the UPS on the ground
3. Attempt to craft with the tool while next to the dropped UPS
4. Craft immediately fails because I no longer have a "none"

# Expected behavior

I should be able to craft everything same as I can craft it with the UPS in inventory.

# Screenshots

**Starting with the required tools**
![image](https://user-images.githubusercontent.com/60197566/76182774-35669680-61d7-11ea-9299-f61a2162f343.png)
**Dropping UPS on the ground**
![image](https://user-images.githubusercontent.com/60197566/76182788-48796680-61d7-11ea-9111-b08350c55f24.png)
(Accidentally activated actions menu while taking screenshot)
**Crafting clean water**
![image](https://user-images.githubusercontent.com/60197566/76182905-9f7f3b80-61d7-11ea-8eca-255410767ce4.png)
**Crafting has failed**
![image](https://user-images.githubusercontent.com/60197566/76182945-c3db1800-61d7-11ea-935d-da01c96200db.png)

# Versions and configuration

- OS: Linux
- Game Version: 0.D-12981-g2dbeade39a [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

Self-compiled on Linux. Possibly related to #38662 and #38618

**Comment by jkraybill** [comment]
Also logged in #38618, this one has more detail.
