### ISSUE TITLE
Storage parts of mounted vehicle have 0 storage space

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#38671]
# Describe the bug

If you have vehicle with some container parts (trunk, box, and the like; heck, even seats are affected) and you mount that vehicle on another one via bike rack, parts that had storage space will show that they have 0 storage space. And they will work accordingly, i.e. you would not be able to put anything inside them, be it using AIM which will say no space available or just dropping items on the tile, in which case they will simply drop on the floor.
At the same time, you both can see how much stuff is actually stored in the container if you 'l'ook at the tile, and you can take items from the container (but can't put them back because its volume is still 0).

# Steps To Reproduce

1. Make a couple of vehicles, vehicle A with bike rack big enough for the vehicle B which should have a container part
2. Put some items into veh.B storage
3. Mount veh.B on veh.A
4.1. Try putting something into container part of veh.B.
4.2. Notice you can easily remove items from aforementioned storage.

# Expected behavior

Being able to put things into mounted vehicle's storage space(s). Or not being able to interact with them at all. Just something consistent instead of current one-way interaction.

# Versions and configuration

- OS: Windows 7x64
- Game Version: 0.D-12968-g89b9a2a [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Aftershock [aftershock],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills],
    Magiclysm [magiclysm]
]

**Comment by jkraybill** [comment]
Probably a similar issue to #38620 which I fixed, will take a look.
