### ISSUE TITLE
Magiclysm Mod - Aura of Protection effect does nothing

### ISSUE THREAD

**Issue by Aluminumfoil** [CleverRaven/Cataclysm-DDA#38687]
# Describe the bug

The Aura of Protection spell successfully applies an effect to all body parts. However, the effect doesn't do anything. 

# Steps To Reproduce

Activate the spell. Walk into anything that applies an environmental attack, e.g. Thin Smoke. In this case I equipped a scarf (env protection 2) to compare with Thin Smoke (attack 1d3) to determine if the Aura of Protection had at least 1 env protection, and noted that the Thin Smoke still penetrated the defense. 

# Expected behavior

Aura of Protection effect has at least 1 Environmental Protection.

**Comment by KorGgenT** [comment]
if anyone would like to fix this spell before I do, this is how to do it: change the aura of protection spell to a spawn_item type. delete the aura of protection effect. create an armor that has some environment value, and give it the aura flag (so when it's equipped the encumbrance doesn't do anything)

**Comment by Askethil** [comment]
I will take care of it.
