### ISSUE TITLE
"Replacement item for migration 10mm_casing does not exist"

### ISSUE THREAD

**Issue by Fengren1998** [CleverRaven/Cataclysm-DDA#38682]
# Describe the bug

 DEBUG    : Replacement item for migration 10mm_casing does not exist

 FUNCTION : void Item_factory::finalize_item_blacklist()
 FILE     : src/item_factory.cpp
 LINE     : 599

EDIT: More of it
 DEBUG    : Replacement item for migration 10mm_fmj does not exist

 FUNCTION : void Item_factory::finalize_item_blacklist()
 FILE     : src/item_factory.cpp
 LINE     : 599

 DEBUG    : Replacement item for migration 1895sbl does not exist

 FUNCTION : void Item_factory::finalize_item_blacklist()
 FILE     : src/item_factory.cpp
 LINE     : 599

 DEBUG    : Replacement item for migration 20x66_10_mag does not exist

 FUNCTION : void Item_factory::finalize_item_blacklist()
 FILE     : src/item_factory.cpp
 LINE     : 599

 DEBUG    : Replacement item for migration 20x66_20_mag does not exist

 FUNCTION : void Item_factory::finalize_item_blacklist()
 FILE     : src/item_factory.cpp
 LINE     : 599

 DEBUG    : Replacement item for migration 20x66_40_mag does not exist

 FUNCTION : void Item_factory::finalize_item_blacklist()
 FILE     : src/item_factory.cpp
 LINE     : 599

 DEBUG    : Replacement item for migration 20x66_beanbag does not exist

 FUNCTION : void Item_factory::finalize_item_blacklist()
 FILE     : src/item_factory.cpp
 LINE     : 599

 DEBUG    : Replacement item for migration 20x66_bootleg_flechette does not exist

 FUNCTION : void Item_factory::finalize_item_blacklist()
 FILE     : src/item_factory.cpp
 LINE     : 599

 DEBUG    : Replacement item for migration 20x66_bootleg_shot does not exist

 FUNCTION : void Item_factory::finalize_item_blacklist()
 FILE     : src/item_factory.cpp
 LINE     : 599

 DEBUG    : Replacement item for migration 20x66_bootleg_slug does not exist

 FUNCTION : void Item_factory::finalize_item_blacklist()
 FILE     : src/item_factory.cpp
 LINE     : 599

 DEBUG    : Replacement item for migration 20x66_exp does not exist

 FUNCTION : void Item_factory::finalize_item_blacklist()
 FILE     : src/item_factory.cpp
 LINE     : 599

 DEBUG    : Replacement item for migration 20x66_flare does not exist

 FUNCTION : void Item_factory::finalize_item_blacklist()
 FILE     : src/item_factory.cpp
 LINE     : 599

 DEBUG    : Replacement item for migration 20x66_flechette does not exist

 FUNCTION : void Item_factory::finalize_item_blacklist()
 FILE     : src/item_factory.cpp
 LINE     : 599

....... and so on (there was a lot of them, seemed like ammo)

Some more
 DEBUG    : Tried to get invalid ammunition: ammo_shot

 FUNCTION : const T& string_id<T>::obj() const [with T = ammunition_type]
 FILE     : src/ammo.cpp
 LINE     : 48

 DEBUG    : unknown item pistol_jhp in spawn list of helicopter_wreck_3b

 FUNCTION : static void vehicle_prototype::finalize()
 FILE     : src/veh_type.cpp
 LINE     : 1099

 DEBUG    : unknown item rifle_ball in spawn list of helicopter_wreck_3b

 FUNCTION : static void vehicle_prototype::finalize()
 FILE     : src/veh_type.cpp
 LINE     : 1099

 DEBUG    : warnings for type mosin44:
ammo type ammo_rifle is not known

 FUNCTION : void Item_factory::check_definitions() const
 FILE     : src/item_factory.cpp
 LINE     : 1327

# Steps To Reproduce

Made a template character in a newly-created world with no mods

# Versions and configuration
Build 10409

**Comment by Fengren1998** [comment]
Just realized it was because the template character was made with a different world loaded

**Comment by Night-Pryanik** [comment]
Not a bug then.
