### ISSUE TITLE
Gradually reduce or increase visibility range between cloudy and clear skies

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#38697]
# Is your feature request related to a problem? Please describe.

When moving around at night during a full moon, if the skies are cloudy, visibility may transition suddenly from full night-vision range, down to a few tiles, in only 1 second or step. The same happens when the clouds (or player) move away and visibility is restored in 1 second.

Likewise, the weather indicator changes from "clear" to "cloudy", and light conditions from "bright" to "very dark", in only 1 second.

# Describe the solution you'd like

As clouds approach, visibility should gradually diminish, and the brightness indicator should go through some intermediate states between "bright" and "very dark" as the player moves further into the cloud's shadow. And as the cloud cover moves away, visibility should increase gradually over many seconds or a few minutes, rather than suddenly in 1 second.

*Edit*: The way the light radius gradually increases (tile-by-tile) as the sun rises is a good example of how this could work.

# Describe alternatives you've considered

Always keeping an eye on the sky

# Additional context

I would guess this is one of those seemingly simple things that is fiendishly complicated to solve, which is why I am opening this as a feature request, rather than a bug - though one could easily argue it's a bug, since it is quite immersion-breaking and unrealistic.

![image](https://user-images.githubusercontent.com/238395/76361451-b1023980-62e4-11ea-9f0e-9ca0871b50bc.png)

The sky view similarly goes from full visibility of all nearby clouds, to nothing whatsoever:

![image](https://user-images.githubusercontent.com/238395/76361951-b01dd780-62e5-11ea-9393-928feec1b6c6.png)

**Comment by OldFriendEr** [comment]
4 tiles of visibility sounds like a dense fog instead of cloudy day.

**Comment by wapcaplet** [comment]
For comparison, consider the way the light radius gradually increases (tile-by-tile) as the sun rises in the morning.

**Comment by cainiaowu** [comment]
Feed the outdoor light intensity stream to any low-pass filter would be enough, in theory.

**Comment by wapcaplet** [comment]
Here is a savegame that should make it easy to reproduce the issue. There is a full moon, but the character is just on the edge of the clouds. Walking south into the cloud cover, your visibility range should diminish suddenly to 2-3 tiles.

![image](https://user-images.githubusercontent.com/238395/80320057-4db76280-87d1-11ea-80c9-d779aad676f0.png)

[cloudy-full-moon.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4536485/cloudy-full-moon.zip)
