### ISSUE TITLE
Using a bandage with rigid table manners has food-related morale effects

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#38698]
# Describe the bug

When using a bandage with rigid table manners, morale effects are applied as if the character had just eaten something.

# Steps To Reproduce

1. Create a character with the "Rigid Table Manners" trait
2. Get some bandages
3. Hurt yourself
4. Use bandages with a nearby table and chair: "Ate with table"
5. Use bandages without a nearbly table and chair: "Ate like an animal"

# Expected behavior

Using bandages should not affect morale as if something were eaten.

# Screenshots

![image](https://user-images.githubusercontent.com/238395/76363300-59fe6380-62e8-11ea-8dbc-167a943a25a1.png)

![image](https://user-images.githubusercontent.com/238395/76363306-5e2a8100-62e8-11ea-911e-75b4b9f8275b.png)

# Additional context

Thanks to Chromosome Kun! on the discord chat for raising this. These morale effects are handled in consumption.cpp in [this section of Character::modify_morale](https://github.com/CleverRaven/Cataclysm-DDA/blob/2f83dbec457ec41ee15b55c05a9d922cf0349178/src/consumption.cpp#L982-L997) but I can't imagine why this would be getting invoked for bandages. I will take a crack at a fix.

**Comment by KorGgenT** [comment]
perhaps the block of code with the table manners trait should exclude comestibles with NO_INGEST?
