### ISSUE TITLE
Pseudo tiles during gameplay

### ISSUE THREAD

**Issue by NeonSheepy** [CleverRaven/Cataclysm-DDA#38709]
# Bug description

After updating to the newest experimental. i created new worlds, i started to encounter pseudeo-terrain at the dirtpaths near rural housings and at campsites .**

# Steps To Reproduce

Load up new game, probably with the **rural only mapgen** and observe locations stated,

# Expected behavior

I asked on discord and a usere there told me to report it here.

> Biome stuff is supposed to automatically fill that in with an intended default terrain.
Guessing someone told rural houses to use a pseudo-terrain but nothing was specified for this 
 biome.

# Screenshots
![Bug](https://user-images.githubusercontent.com/54107306/76443544-de251980-63c2-11ea-91f4-f2cd19461ecd.png)

# Versions and configuration

- OS: Windows
    - OS Version: Windows 8 MINGW/CYGWIN/MSYS2 
- Game Version: 0.D-13035-ga9daddc [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    More Survival Tools [More_Survival_Tools],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Mutant NPCs [mutant_npcs],
    No Rail Stations [No_Rail_Stations],
    Fuji's Military Profession Pack [fuji_mpp],
    Stats Through Kills [stats_through_kills],
    Alternative Map Key [alt_map_key],
    Rural-Only Mapgen [ruralbiome]
]

# Additional context

Reloading and changing tilesets does not resolve the issue, nor does creating a new world. Maybe mod load order helps, i havent tested that yet.

This is my first Bug report i hope its fine, i will keep an eye on it and provide new information as i come by.

**Comment by akirashirosawa** [comment]
How does this issue relate to PR 38706? You wrote the number of my PR in the title.

**Comment by wapcaplet** [comment]
I am able to reproduce this by starting a new world with the Rural-Only Mapgen mod, and teleporting to a farm, where there are lots of dirt roads.

Using the `x` key to examine terrain, I see the same "this should never actually show up" message:

![image](https://user-images.githubusercontent.com/238395/76477119-fea4a200-63c9-11ea-9450-953190ba58c7.png)

- OS: Linux
    - OS Version: LSB Version: core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch; Distributor ID: Ubuntu; Description: Ubuntu 18.04.4 LTS; Release: 18.04; Codename: bionic; 
- Game Version: 0.D-13003-gd59d380027 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Rural-Only Mapgen [ruralbiome]
]

**Comment by anothersimulacrum** [comment]
This may have something to do with https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/furniture_and_terrain/terrain-regional-pseudo.json

**Comment by NeonSheepy** [comment]
![FarmPT](https://user-images.githubusercontent.com/54107306/76509332-22123000-6450-11ea-8e12-0da367925675.PNG)
 
I could reproduce it on all dirt road tiles, some farm tiles, and at a campsite, the one multiple tiles big. I tried creating new worlds and changing tilesets the bug persists
