### ISSUE TITLE
Uninstallable gunmods when only 1 weapon in inventory give less feedback than when holding an installable weapon

### ISSUE THREAD

**Issue by jkraybill** [CleverRaven/Cataclysm-DDA#38703]
# Describe the bug

If you have a weapon and a gunmod, and (a)pply the gunmod, and don't meet the requirements to install for any reason (e.g. insufficient skill, or the weapon is still loaded), you get a blank list:

![image](https://user-images.githubusercontent.com/1361701/76406216-74663900-63dd-11ea-9f25-7c0e46e30290.png)

But if you hold multiple weapons, and one is installable, you get useful feedback on the uninstallable weapon:

![image](https://user-images.githubusercontent.com/1361701/76406266-8d6eea00-63dd-11ea-93e0-70953420eae8.png)

![image](https://user-images.githubusercontent.com/1361701/76406292-995aac00-63dd-11ea-94a7-6cff9ed6ae27.png)

# Steps To Reproduce

1. Spawn a H&K MP7A2. Spawn a shoulder strap.
2. While not holding other weapons, try to use the strap. You'll get an empty list because the MP7A2 is loaded.
3. Spawn another weapon that can take a strap, and unload it.
4. Use the strap. You'll get a list with both weapons, and it will inform you of why you can't install on the MP7A2.

Above is also reproducible when you have the necessary skill in one weapon but not another (e.g. spawn a rifle and an SMG, try to install a sight when you have 0 skill in one class but 2+ skill in the other and also have marksmanship 3).

# Expected behavior

It would be great if the game gave feedback regardless of whether any weapon is installable.

At the moment, it's quite confusing -- see #38702, which I even thought was a reproducible bug when I first tried to repro because the weapon was loaded.

# Screenshots

As above.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-13031-g5a76e8e30d-dirty [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by jkraybill** [comment]
As an FYI, this happens in other instances of filtered inventory -- for instance, you don't get options when only attempting to eat while holding powdered milk, but if you hold powdered milk and an edible thing, you get feedback on why you can't eat the inedible thing. This is a bigger issue with gunmods, but maybe there's a way to address this generally?

**Comment by Dacendeth** [comment]
Yeah for whatever reason things that are not valid are not showing up anymore, like if you go to wear shoes while wearing shoes already, you wont see shoes on the list with the message "you can only wear one pair of shoes", instead shoes just doesnt show up in that list at all.
