### ISSUE TITLE
[Android] Magiclym does not load

### ISSUE THREAD

**Issue by Bolrik** [CleverRaven/Cataclysm-DDA#38704]
# Describe the bug

On the latest experimental version from http://dev.narc.ro/cataclysm/jenkins-latest/Android/Tiles/ the world loading screen does not pass the Magiclysm mod but does not throw any exception.

# Steps To Reproduce

1. Download latest experimental version
2. Create new world with Magiclysm active
3. Create new Character on that World

# Expected Behavior

It should load Magiclysm

**Comment by paulo-renzo** [comment]
This started in experimental 10404.

**Comment by KorGgenT** [comment]
does anyone have any ideas? i don't have any way to debug android builds at all.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/magiclysm-a-total-fantasy-overhaul/20612/325

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/magiclysm-a-total-fantasy-overhaul/20612/378

**Comment by paulo-renzo** [comment]
I just tried 0.E stable (cataclysmdda-0.E-10478-armeabi-v7a-release.apk), new world with Magiclysm loaded fine. Installed (cataclysmdda-0.E-10478-arm64-v8a-release.apk), new world with Magiclysm just stuck loading at Magiclysm.

**Comment by paulo-renzo** [comment]
Ok, latest experimental armeabi-v7a works, arm64-v8a hangs. What's the difference between these apks?

**Comment by anothersimulacrum** [comment]
The first one is 32 bit, the second is 64 bit.

**Comment by Alexkun** [comment]
32bit works, while 64bit stuck in 0.E.2 version.
