### ISSUE TITLE
Pebble shotcanister has the wrong material (Steel)

### ISSUE THREAD

**Issue by Lamandus** [CleverRaven/Cataclysm-DDA#38705]
# Describe the bug
The Pebble Shotcanister is shown as Material: Steel 

# Steps To Reproduce

Try to craft it, check the Material.

# Expected behavior

Being Material: Stone

# Screenshots

![grafik](https://user-images.githubusercontent.com/33199510/76421011-524fc500-63a3-11ea-86c9-56b6e75cae54.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-13021-g0840d86 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    SpeedyDex [speedydex],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    No Fungal Monsters [No_Fungi],
    Graphical Overmap [Graphical_Overmap]
]

# Additional context
Change in data\json\items\ammo\shotcanister.json line 33
` 
    "material": [ "steel" ],
`
to

`     "material": [ "rock" ],
`

**Comment by Funguss** [comment]
Ok, can do. :+1:
