### ISSUE TITLE
Science ID only refrences the M240 turret, but not the M2HB turret to be disabled on entrances

### ISSUE THREAD

**Issue by GhostEcho** [CleverRaven/Cataclysm-DDA#38717]
# Describe the bug
If you look at the Science ID reader code, it only references the ID "mon_turret_rifle", which is the M249 turret in lab entrances, but the M2HB can also spawn there, which is "mon_turret_bmg". This means the M2HB does not get triggered to disappear like the M249 does leaving people a nasty .50cal surprise.

# Steps To Reproduce

1. Generate a lab with a M2HB turret guarding the enterance
2. Swipe ID in front of the doors
3. Get head turned into red mist

# Solution

https://github.com/CleverRaven/Cataclysm-DDA/blob/dd7312fa9919054ff25d06525e96993fadba662c/src/iexamine.cpp#L784

This needs to be adjusted to include the M2HB, but should also make sure that any other spawnable turrets also get included

**Comment by Amoebka** [comment]
Reported before in #36415 and allegedly fixed by #36462.
You are probably playing an old experimental or stable.

**Comment by GhostEcho** [comment]
@Amoebka it was in 10412 while watching Vormithrax's stream tonight, KorGen was there was well and we were talking about it

**Comment by GhostEcho** [comment]
Oh actually Im seeing now that it looks like the PR wasnt merged?

**Comment by anothersimulacrum** [comment]
The change in #36462 was to `remove_submap_turrets`, which is a function local to `computer.cpp` and not used in `iexamine.cpp`, where the card reader turret removal occurs.
