### ISSUE TITLE
target_attack spells don't respect effected_body_parts when applying effects

### ISSUE THREAD

**Issue by UristMcSharkbait** [CleverRaven/Cataclysm-DDA#38719]
# Describe the bug

Spells with target_attack that use effect_str to cause an effect don't respect effected_body_parts.
Example:
>  {
    "id": "test_heal_ARM_R",
    "type": "SPELL",
	"name": { "str": "Heal Right Arm" },
    "description": "This spell should heal for 1 point and apply a heal over time effect for 5 minutes, all to your right arm.",
    "valid_targets": [ "self" ],
    "effect": "target_attack",
	"effect_str": "test_heal_over_time",
	"min_damage": -1,
	"max_damage": -1,
	"min_duration": 30000,
	"max_duration": 30000,
    "base_casting_time": 0,
    "max_level": 1,
	"effected_body_parts": [ "ARM_R" ],
    "flags": [ "SILENT", "NO_HANDS", "NO_LEGS" ]
}

This spell does heal the right arm by 1, but the effect is applied to the torso.
Here's the effect too:
>   {
    "type": "effect_type",
    "id": "test_heal_over_time",
    "name": [ "Heal over Time" ],
    "desc": [ "The part targeted by the spell that caused this effect should be being healed by 1 point per second." ],
    "base_mods": {
      "hurt_min": [ -1 ],
      "hurt_max": [ -1 ],
      "hurt_chance": [ 1 ]
    }
  }

Works the same for damage dealing target_attack spells/effects too.
Could be the same for other spell types, but target_attack spells are all I've tested.

# Steps To Reproduce

1. Make a spell that targets a specific body part and applies an effect
2. Cast the spell

Alternatively:
1. Load the attatched save with tiny spell test mod included
2. Cast the spell

# Expected behavior

Effect caused by the spell should be applied to the effected_body_parts, as indicated by the documentation in [https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/MAGIC.md](url)

# Screenshots

N/A

# Versions and configuration

- OS: Windows 7 Professional
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-13021-g0840d86 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Spell Bug Demonstration [Spell_Bug_Demonstration]
]

# Additional context

[save+mod.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4322271/save%2Bmod.zip)

If I'm just being dumb (always possible) and it does work, do tell how.

**Comment by KorGgenT** [comment]
your base spell ha a damage of -1, so it will heal every body part. i'm looking into this anyway to make sure the effect part is applied to the proper place.

**Comment by KorGgenT** [comment]
you misspelled it: it's "affected_body_parts".

**Comment by UristMcSharkbait** [comment]
I misspelled it because that's how its spelled in the documentation, so that should probably be fixed.
