### ISSUE TITLE
internal furnace gas mask glitch

### ISSUE THREAD

**Issue by Mister-Cultist** [CleverRaven/Cataclysm-DDA#38720]
I tried to eat a dead zombie's gasmask with my furnace to power up my bionics when I found that instead of eating the whole thing (which I'm sure that is the intent since it give a large amount of power) I instead only eat 1 charge of the gas mask's filter. It's not a game breaking bug but it makes gas masks one of the best things to carry around to shove into your furnace, also it's interesting to note that it gives less and less power the more charges you eat.

**Comment by Maleclypse** [comment]
@John-Candlebury I went to check if this was JSONized and I noticed that `bio_furnace` only exists in vanilla obsolete and some itemgroups in Aftershock.  So I'm thinking in addition to fixing this issue we should probably add an item in Aftershock that isn't obsoleted?

**Comment by John-Candlebury** [comment]
I'll rather remove its spawns from aftershock actually.

I mean the bionic is fun and all but it behaves in unexpected and illogical ways, just as this issue states. Last time I heard of it, this inconsistency extends to a lot of items. with things like gasoline and diesel giving little power vs stuff like paper and wood.

Personally I'd just remove it, unless you feel like reworking its code to behave more sanely.

**Comment by Maleclypse** [comment]
I’d rather we put time into coherent content for Aftershock than fix items that are fairly buggy. We can keep it obsolete and if we ever decide to try and fix it that’s an option.  Thanks!
