### ISSUE TITLE
throw the contents of the container

### ISSUE THREAD

**Issue by IIverner** [CleverRaven/Cataclysm-DDA#38739]
# Is your feature request related to a problem? 
I thought of this suggestion while putting out a fire with a bottle.

# Describe the solution you'd like
Maybe we could put this function under the U key.Then use the aim menu to aim at the target,It could be a point or a line.
Imagine splashing the water out of the bottle,throwing the magazine out of a gun,splashing gasoline in the distance.I think someone might like this.

# Describe alternatives you've considered
Letting the fire extinguisher range further.

# Additional context
I'm not a native English speaker.

**Comment by iostapyshyn** [comment]
I'm interested. Is this good as a first contribution? How would one go implementing this feature?
