### ISSUE TITLE
Can't see from inside vehicle

### ISSUE THREAD

**Issue by klefenz** [CleverRaven/Cataclysm-DDA#38736]
Verison: Linux x64 curses 10055. I later updated to 10413 and the problem persisted.
Mods: Generic Guns.

Description: Can't see through the windshield while inside a vehicle.

Savefile: [https://drive.google.com/open?id=1_NCJvR-bvyii2pbzuOr4bBrfvaWlJj77](url)

This started to happen after I was repairing/modifying some vehicles, don't know if related.
Before anyone asks, the vehicle in the screenshot has quarterpanels in the front like regular cars, and the error also happens on other cars.

![gguyvhj](https://user-images.githubusercontent.com/12169144/76578556-c1164680-64a7-11ea-8f3b-9ef0b2aaa252.png)

**Comment by anothersimulacrum** [comment]
Are you crouching?

**Comment by wapcaplet** [comment]
This issue has come up so often - part of the problem is that when you are inside a vehicle, the sidebar does not indicate whether you are walking, running, or crouching.

**Comment by klefenz** [comment]
Oh, well, that was it.

Thanks.
