### ISSUE TITLE
NPCs running around for seemingly no reason

### ISSUE THREAD

**Issue by TheGrimMeeper** [CleverRaven/Cataclysm-DDA#38731]
# Describe the bug

At a certain location, NPCs run around like they think a fire is around and it's effectively jamming their pathfinding. Maybe there is a fire on the floor below, or above.

# Steps To Reproduce

1. Load attached save
2. Hold .

# Expected behavior

NPCs follow normally

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-13038-g4cd0cc5 [64-bit]
- Graphics Version: Tiles
-
# Additional context
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4326837/save.zip)

**Comment by Maleclypse** [comment]
If this certain area is a mission location, then I can confirm that I've experienced this.
