### ISSUE TITLE
Old character losing mutations on a game load

### ISSUE THREAD

**Issue by Shiramizu** [CleverRaven/Cataclysm-DDA#38740]
# Describe the bug

I'm having a really weird bug on importing an old character into the new version where I lose my eyes mutation. 
These mutations can't be gained from drinking mutagen (tried 50 doses) and adding them through debug only works for this instance and they're lost net time the character is loaded.
Not sure which part of the save causes the issue.

# Steps To Reproduce

1. Load the attached save.
2. Check the lack of aforementioned mutations.
3. Debug the mutations.
4. Save and Exit.
5. Load again.
6. Mutations still not there.

# Expected behavior

Character loading with proper mutations.

# Versions and configuration

 - OS: Windows 10.0 1903
 - Game Version: 0.D-12974-gf467016
 - Graphics version: Tiles
 - In game language: English

# Additional context
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4328423/save.zip)

**Comment by ZhilkinSerg** [comment]
Vision mutations are cured by vision CBM.

**Comment by Shiramizu** [comment]
I think information like that should be added to the description of the bionic. Something like changing the "Much of of the material..." to "Your eyes were replaced with...". 
Current description implies the eye shape and function are still the same but enhanced, while in reality it makes you lose Nightvision among other things.
This would be useful so that players don't accidentally lose nightvision from installing a CBM.

**Comment by ZhilkinSerg** [comment]
It is in description:

``
... any vision problems you might have had are now gone.
```

**Comment by Shiramizu** [comment]
Most players wouldn't classify Nightvision as a vision problem. Like I said, the item description implies only enhancement of existing eye features and losing Nightvision is a clear detriment.

**Comment by ZhilkinSerg** [comment]
See #38903
