### ISSUE TITLE
player can see through opaque vehicle parts by opening doors

### ISSUE THREAD

**Issue by Heaper327** [CleverRaven/Cataclysm-DDA#38752]
Game version: 0.D - 12808

Operating system: MacOS 10.15.3

Tiles or curses: tiles

Mods active: none

### Expected behavior

player should not be able to see through opaque vehicle parts

### Actual behavior

player can see through opaque vehicle parts after opening doors

<img width="551" alt="截屏2020-03-1314 52 09" src="https://user-images.githubusercontent.com/29885616/76651121-4cd8b300-653a-11ea-842d-5ef0e2212732.png">
completely opaque vehicle

<img width="520" alt="截屏2020-03-1314 52 13" src="https://user-images.githubusercontent.com/29885616/76651138-5530ee00-653a-11ea-9d36-8efc29ecc585.png">
open door

<img width="429" alt="截屏2020-03-1314 52 21" src="https://user-images.githubusercontent.com/29885616/76651159-5a8e3880-653a-11ea-9559-b19f455ba9e5.png">
close door

<img width="419" alt="截屏2020-03-1314 53 44" src="https://user-images.githubusercontent.com/29885616/76651229-72fe5300-653a-11ea-9342-84ef6ab125f4.png">
even opening internal doors gives player x-ray vision

### Steps to reproduce the behavior

1. build a vehicle completely enclosed with boards
2. build a door somewhere in it
2. go inside the vehicle
3. open the door and acquire x-ray vision

**Comment by akirashirosawa** [comment]
Hello. I already noticed this issue #38708 and fixed it #38712. Just update build :)

**Comment by Heaper327** [comment]
That was fast, thanks a lot!

**Comment by akirashirosawa** [comment]
So fast that even a day before 🙂
