### ISSUE TITLE
Make crates more fun and realistic

### ISSUE THREAD

**Issue by gboudrias** [CleverRaven/Cataclysm-DDA#38774]
# Is your feature request related to a problem? Please describe.

I'm always frustrated when I open a sealed crate and there's nothing inside. It seems very unrealistic that someone would seal an empty crate and it breaks my immersion.

This is especially annoying in LMOE shelters, where crates are always present for thematic purposes, yet most if not all of them are empty.

# Describe the solution you'd like
My proposed solution is threefold:

1. Have fewer empty crates, ie more creates with something in them. I assume this is an easily changed value and it wouldn't affect balance much as the average value of items even in filled crates seems very low. Crates are somewhat uncommon anyhow.
2. Have items representing degraded or destroy items instead of crates being empty, such as a random amount of threads, rags, nails, plastic chunks, scrap metal, etc, even rotten food. This would be flavorful and also wouldn't affect balance very much, as these are usually very common. Still, it would be less of a disappointment than an umpteenth sealed empty crate.
3. If the crate actually would be empty, replace it with an unsealed (empty) crate. 

# Describe alternatives you've considered
As I understand it, all crates used to be empty a long time ago. According to #7473, empty crates used to exist, but we opted to delete them instead. So it seems like sealed empty crates were added back somewhere along the way, but I couldn't find an issue for that so maybe it's a bug? The way it is right now seems much less realistic to me than simply having empty crate furniture.

# Additional context
 I can probably figure out the PR if this idea is well-received.

**Comment by gboudrias** [comment]
So as far as I can tell, crates are just ordinary CONTAINERS in terms of what they can contain, individually coded in the JSON for whichever items they can contain (well, coded for specific areas of specific buildings).

Because of this, it's already possible to do this in the JSON, but it would be extremely tedious to look at all the areas with containers and manually adding the odds to get random garbage.

I'm thinking of adding an AUTO_CONTAINS_SCRAP tag and making it so the broken items are figured out automatically based on the possible items. We would still have to go into each relevant area to add the tag, but that's only a one-time effort for added flexibility in the future.

Thoughts?

**Comment by jeremyshannon** [comment]
That sounds like it might also be handy for other things, like making semi-collapsed buildings or what-have-you.
