### ISSUE TITLE
Asthma NPC uses Inhaler but fails...

### ISSUE THREAD

**Issue by PresidentNose** [CleverRaven/Cataclysm-DDA#38772]
Asthmatic NPC has cought, so i used spawn item to give inhaler. Used NPC Commands to "hold this item, NPC procceds to wield inhaler. Told NPC to guard position -> Crash!

# Steps To Reproduce:

1. Have a friendly NPC with Asthma trait.
2. Event Log says: <NPC Name> coughs.
3. Spawn inhaler, procced to give NPC item.
4. NPC wields instead inhaler.
5. Tell NPC to guard position, move away once -> crash appears!

I expected NPC to use inhaler and stop to have an asthmatic episode/ cought.

What i got from the report:

 DEBUG    : Johnna 'Keystone' Dennison tried to heal self but has no healing item

 FUNCTION : void npc::heal_self()
 FILE     : src/npcmove.cpp
 LINE     : 3484

- Don't know why but now my game is in debug an NPC is "asleep"/deactivated.

**Comment by wapcaplet** [comment]
I tried to reproduce this issue but was unable to get an NPC to wield an inhaler, even with 3 STR/DEX (in case that matters) and no other weapon available. When I ask them to "hold onto" the inhaler, they keep it in their inventory, and correctly use it to treat their asthma. And when I ask them to "use this item" with the inhaler, they refuse, saying "Nope. My current weapon is better than this. (new weapon value: 1.8 vs. 1.9)"

**Comment by PresidentNose** [comment]
Sorry for respawning only now. I did not do much after the Issue. Only thing i could add is that i use this version of CDDA Experimental: 0.D-12680-g7d60cda (tiles)/ Version: 10376.

If this doesn't help further, i asume the issue needs to be set on ice - for now?
Sadly i lost the save.... so i don't know if i can be of further help towards this issue?

**Comment by wapcaplet** [comment]
@PresidentNose Can you still recreate the issue in a new game, either in your current version (0.D-12680), or in a more recent experimental build? Without being able to recreate the problem, it would be difficult to diagnose.

Even if you can figure out how to get an NPC to wield an inhaler, that would help.

**Comment by Night-Pryanik** [comment]
No confirmation in more than a year, closing.
