### ISSUE TITLE
Alt monster spawner option

### ISSUE THREAD

**Issue by Midaychi** [CleverRaven/Cataclysm-DDA#38784]
# Is your feature request related to a problem? Please describe.
When using mods like "No fungal" and "No zombies" or whatnot, normally they just straight disable mobs from spawning and this is intentional. What I'd like to see is an option that makes it so that if a mob is disabled via mod, but a disabled monster or groups of monsters would have spawned somewhere normally, the game randomly chooses a vaguely comparable threat level mob or mobs to spawn from both vanilla and currently loaded non-disabled modded mobs.

# Describe the solution you'd like
It doesn't have to be exact and I don't know what metric you'd compare them to, but..

Example: You start in a city in a relatively early-date start, but have zombies disabled. Or if you have spiders disabled, maybe tiny little angry dinosaurs spawn in basements? (dino mod actually sort of does this already I just wanted an excuse to paste the screenshot at the end)
 Maybe the game instead spawns aggressive animals, spiders, bees n wasps, or if you attack a lab, maybe it spawns an angry moose, or magicalysm threats and dinosaurs if you have those mods loaded, etc. Later game, labs could have more robots and npc bandits or something.

# Describe alternatives you've considered
There's not really a direct alternative really besides defining spawns yourself in code. 

# Additional context
![excuse](https://user-images.githubusercontent.com/1968809/76697632-c2d23c80-6656-11ea-9314-f7c59cf7c692.png)

**Comment by kevingranade** [comment]
What you're describing is a conversion mod.  We can work with people interested in making conversion mods to meet their needs with more core features and we'd be happy to host it in the repository, but someone who is willing and able to create such a conversion mod needs to take the lead on that, the main project isn't going to do it.
