### ISSUE TITLE
Monomolecular Blade prevents throwing items

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#38780]
# Describe the bug

When Monomolecular Blade bionic is active it *silently* prevents throwing items.

# Steps To Reproduce

1. Make a player with grenade in inventory and MB CBM
2. Activate MB.
3. Activate grenade.
4. Try throwing it.
5. Try again.
6. Watch last moments of your life?..

# Expected behavior

I'm not really sure why would it prevent throwing items, it only occupies one hand, you still have the other, right? And even if it should prevent throwing items for some reason, at least it should say so when you select an item or even better, prevent opening item selection window and explain why. It does so when you attempt to wield 2h weapon, for example.

# Versions and configuration

- OS: Windows 7x64
- Game Version: 0.D-13133-g1eb14b4 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Aftershock [aftershock],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills],
    Magiclysm [magiclysm]
]

**Comment by kevingranade** [comment]
It's possible this has the same cause as #38807, namely that the message cooldown code is hiding these messages.

**Comment by GGgatherer** [comment]
The thing is, there are no messages at all (in linked issue the message was shown once) so I doubt it's the same issue.
