### ISSUE TITLE
Useless before-sleep warning

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#38785]
# Describe the bug

tried to sleep, and got this warning:
![survivormask](https://user-images.githubusercontent.com/56833396/76697563-49c0fc80-66cb-11ea-904e-30cfdb660b34.png)
My char wasn't even wearing it at the time. 

As far as I know, there is no way to deactivate gas masks, survivor masks and such. So probably this one(okay, two. or 3 if filter mask is also affected) item should be excluded from before-sleep checks.

# Steps To Reproduce

1. Make a player with loaded survivor/gas mask.
2. Activate it.
3. Press '$' and see the warning.

# Expected behavior

No warning because it doesn't serve any purpose.

# Versions and configuration

    OS: Windows 7x64
    Game Version: 0.D-13133-g1eb14b4 [64-bit]
    Graphics Version: Tiles
    Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Aftershock [aftershock],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills],
    Magiclysm [magiclysm]
    ]

**Comment by akirashirosawa** [comment]
fixed in PR #38768

**Comment by Little-119** [comment]
This is still present in 0.E-4-gae54c8c
