### ISSUE TITLE
Item "could be repaired with ." message

### ISSUE THREAD

**Issue by jkraybill** [CleverRaven/Cataclysm-DDA#38788]
# Describe the bug

I selected my ESAPI ballistic vest from inventory, then select (m)end and got a message "The ESAPI ballistic vest doesn't have any faults to mend. It is damaged, and could be repaired with . Press a to use one of these items."

# Steps To Reproduce

Spawn an ESAPI ballistic vest.
(i)nventory.
Select ESAPI vest.
(m)end.

# Expected behavior

I get told what I could actually repair it with, or that I can't repair it.

The first sentence ("...doesn't have any faults...") should not contradict the second sentence ("It is damaged, and could be repaired...").

Not sure if this is specific behaviour to the ESAPI vest. I doubt it.

# Screenshots

![image](https://user-images.githubusercontent.com/1361701/76700970-e22da000-6710-11ea-9590-a9957217c602.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-13133-g1eb14b4 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    More City Locations [cityside],
    Urban Development [Urban_Development],
    No Fungal Monsters [No_Fungi]
]

**Comment by jkraybill** [comment]
The merged PR simply drops the empty "could be repaired with" - there is a little remaining work to be done on this after string freeze to add some clarifying text.

**Comment by jbytheway** [comment]
I opened #40828 to implement @jkraybill's suggestion.
