### ISSUE TITLE
Got messages about Hub security officers I could not see

### ISSUE THREAD

**Issue by jkraybill** [CleverRaven/Cataclysm-DDA#38783]
# Describe the bug

While at the Hub, I got a slew of messages about Hub security officers doing things that I could not see. I had not seen any Hub security officers, and could not see any way that I could have seen this occurring. I was in a room at the Hub with limited visibility. I did not see any NPCs on the map or the overmap either. Screenshots show my location and the messages.

# Steps To Reproduce

Not sure, but presumably hanging around this location at the Hub until you get a similar message.

# Expected behavior

Not getting messages about things I can't see. In this particular case, these messages are telling me that there are armed NPCs nearby before I have seen them.

# Screenshots

![sc001430](https://user-images.githubusercontent.com/1361701/76697328-28bbd400-66ea-11ea-9cc1-152c3b462ae6.png)

![sc001431](https://user-images.githubusercontent.com/1361701/76697330-2bb6c480-66ea-11ea-828c-174ec842dfb8.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-13133-g1eb14b4 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    More City Locations [cityside],
    Urban Development [Urban_Development],
    No Fungal Monsters [No_Fungi]
]

# Additional context

I doubt this is specific to the hub, but I just haven't spent much time in locations where there are close-by NPCs that I can't see.

**Comment by GGgatherer** [comment]
Heh, I had same problem couple months ago. Was exploring a lab, began seeing messages about some bandit which was on the surface in the city (no schizo, he really was there).

**Comment by natsirt721** [comment]
I've seen this one for Hub01 when I tried to kite the prototype robot past the entrance. IIRC they all picked up and then put down their weapons in response to a nearby threat.
