### ISSUE TITLE
Drugs do not improve morale

### ISSUE THREAD

**Issue by Soadreqm** [CleverRaven/Cataclysm-DDA#38799]
# Describe the bug

Items such as tobacco, marijuana, cocaine, meth, heroin, morphine, and LSD do not improve morale when taken.

# Steps To Reproduce

1. Take drugs (tested with the ones listed)
2. Nothing is affecting your morale

# Expected behavior

Drugs should improve morale, as per the enjoyability listed in the item description.

# Screenshots

![cdda_morale](https://user-images.githubusercontent.com/6437763/76711143-050e8300-6716-11ea-9850-ec17b593c719.png)
After smoking a cigarette and a joint, shooting up ten units of morphine and ten units of heroin, snorting ten units of cocaine and methamphetamine and eating ten pink tabs.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.D-13155-gb5bc0a6 [32-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context

Negative morale from withdrawal is still applied correctly.
Possibly related to #38700

**Comment by wapcaplet** [comment]
You are right, this bug was introduced by #38700. Thanks for catching this! I will have a fix shortly.

**Comment by wapcaplet** [comment]
Fixed, with tests galore :-)

![image](https://user-images.githubusercontent.com/238395/76713421-2bb4c580-66e6-11ea-84c7-7ed3d309b17b.png)

**Comment by Soadreqm** [comment]
Cool, that was fast.
