### ISSUE TITLE
After switching the language, nothing changes

### ISSUE THREAD

**Issue by xxkfqz** [CleverRaven/Cataclysm-DDA#38797]
After switching the language, nothing changes.

## Steps To Reproduce
1. Build game from the source
2. Launch it
3. Change language

## Screenshots
![1](https://user-images.githubusercontent.com/52203435/76709555-77d12b80-6721-11ea-8792-67a0ac1550ae.png)
![2](https://user-images.githubusercontent.com/52203435/76709557-7acc1c00-6721-11ea-93b7-b814677ae90d.png)

## Versions and configuration

 - OS: Debian 9 _and_ Gentoo 2.7 (x86)
 - Game Version: 0.D (Cataclysm-DDA experimental build 10424 (source code))
 - Graphics version: Terminal
 - Ingame language: English and Russian
 - Mods loaded: none

Pre-build versions of game did not have that bug.

**Comment by Qrox** [comment]
Did you compile the language files using for example `lang/compile_mo.sh ru`?

**Comment by xxkfqz** [comment]
> Did you compile the language files using for example `lang/compile_mo.sh ru`?

No, but that helped! Thank you!
