### ISSUE TITLE
Application packaging: name directories for curses and tiles versions differently

### ISSUE THREAD

**Issue by colorchestra** [CleverRaven/Cataclysm-DDA#38819]
# Is your feature request related to a problem? Please describe.
I recently tried out CDDA for the first time. I downloaded the Linux stable releases for both the curses and the tiles version to see which one suits me better. Then, this happened:
- Unpack curses version by doing `tar -xzvf cataclysmdda-0.D-8574-Linux-Curses.tar.gz` 
- Directory `cataclysmdda-0.D` gets extracted
- Enter directory, play game for a bit
- `cd ..`
- Unpack tiles version by doing  `tar -xzvf cataclysmdda-0.D-8574-Linux-Tiles.tar.gz`
- Directory `cataclysmdda-0.D` gets extracted and overwrites the old one, destroying my save

# Describe the solution you'd like
Rename the directories inside the respective release archives to `cataclysmdda-0.D-curses` and `cataclysmdda-0.D-tiles`.

# Describe alternatives you've considered
I guess it can be expected from the user to check the name of the directory beforehand or not to extract it in the same directory, so an alternative would be to leave it as it is. But people (like me) tend to make mistakes and this would be an easy way to catch that, and it would make for a nicer experience for people first starting out with CDDA.

**Comment by ZhilkinSerg** [comment]
What do you mean "destroying your save"? You can switch between tiles and curses versions and it should cause no issues. Also unpacking should not clear destination folder

**Comment by colorchestra** [comment]
Ah, forgot about this. You are correct, there is no problem and I was thrown off by another error. Sorry!
