### ISSUE TITLE
Bodkin ammo does not show damage values in crafting menu

### ISSUE THREAD

**Issue by AncientSion** [CleverRaven/Cataclysm-DDA#38830]
Wodden Bodkin Arrows /  Bolt dont show their damage values in the crafting menu.

They should. There could be more ammo items that don
![bodkin](https://user-images.githubusercontent.com/4209179/76806139-eaeda700-67e0-11ea-9ae6-f467b3546edb.png)
t.

**Comment by Dacendeth** [comment]
both the bodkin arrow and bolt lack a prop damage line which is the reason their stats dont show up, also arrow_flamming is messed up too and uses the old flat damage bonus arrow system.

**Comment by anothersimulacrum** [comment]
This is fixed in #37329, but that's a rather big PR that just has that as a side effect.
