### ISSUE TITLE
Games locks up mid aim when target moves out of vision range

### ISSUE THREAD

**Issue by ohan2** [CleverRaven/Cataclysm-DDA#38834]
# Describe the bug

When assaulting three bandits in a house at night for an NPC quest, I had shot one of the bandits, and all three approached my location to investigate the noise before heading toward their original positions. I then auto-aimed and attempted to fire a precise shot at a moving bandit in the dark with a pneumatic bolt driver. The bandit moved out of my vision range before the shot went off, and the game was then caught in a loop as it attempted to fire at a non-visible target.

# Steps To Reproduce

1. Make a player with a pneumatic bolt driver, or similar weapon, and the night vision trait
2. Fire at a quest target in the dark from maximum visible range
3. Wait until the target comes over to investigate the player location and starts to head back toward their originally scripted position
4. Auto-fire a precise shot at the target at maximum visible range, may need to repeat several times
5. At this point, the game should fall into a never ending loop. Attempting to quit the game will likely be unsuccessful, and the OS will prompt to force quit the frozen application

# Expected behavior

The ideal scenario would be that the game would be able to detect the target disappearing from visible, targetable range and responded by exiting the aiming routine. What happened instead was that the game continued the routine, locking the game into a freeze loop.

# Screenshots

https://imgur.com/a/Ei1prjd

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 18.04.4 LTS; Release: 18.04; Codename: bionic; 
- Game Version: 0.D-12846-gd972c1c [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Alternative Map Key [alt_map_key],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex]
]

# Additional context

**Comment by kevingranade** [comment]
This looks like the bug that was addressed by #38701 
Please retest on the latest build.

**Comment by ohan2** [comment]
Okay I see, thanks for the heads up.
