### ISSUE TITLE
Low performance of gettext on MinGW target due to libintl bug

### ISSUE THREAD

**Issue by Qrox** [CleverRaven/Cataclysm-DDA#38849]
# Describe the bug
A libintl caching bug is causing in-game menus to slow down when English language is selected on MinGW target

# Steps To Reproduce
1. Switch in-game language to English
2. Open consuming menu near a huge food pile
3. Sloooooooooow menu response
4. Switch language to a non-English one
5. Noticeable improvement in performance

# Expected behavior
Equal performance for English.

# Versions and configuration
Game compiled from source with MinGW-w64

# Additional context
I filed the bug to the gnu issue tracker (https://savannah.gnu.org/bugs/index.php?58006). But for the 0.E release and for back-compatibility with older libintl versions, we should probably do something about it on our end, even it may be eventually fixed on the libintl end.

Something I can think of is to actually compile a `.mo` file for English, so it correctly triggers the caching of libintl. Given that a `.mo` file is only a few MB this might be a good idea, but I want to hear what other people think before opening a pull request.

Also, this performance issue only seems to happen with MinGW targets, which uses Windows' native `getenv()`. Msys2 supplies `getenv()` in `msys2.dll` instead, which was faster so there wasn't a noticeable change in performance when I switched the language. I'm not sure what's the case with other targets (linux/macos/android).

**Comment by kevingranade** [comment]
We could possibly redefine the _ macro to short circuit out if the language is English.
That wouldn't catch everything, but it should handle the majority of the instances.

**Comment by jkraybill** [comment]
If simply compiling a .mo for English will give a noticeable speed up, I'm very in favor of that as a fix! It's easy and very low risk. Seems strictly better than adding code that treats English as an exception.

Slow menus become noticeable early in the game if you're a hoarder.

**Comment by kevingranade** [comment]
I also wonder if we can create a minimal .mo file that triggers the caching behaviour but doesn't supply any strings?

**Comment by Qrox** [comment]
@kevingranade As I understand the libintl code, caching is currently only triggered when it finds a translation string in the .mo file, so I'm afraid that's not possible.

**Comment by Qrox** [comment]
> Would doing this make fast testing of JSON changes harder by forcing a compilation step? Or would "untranslated" strings not in the .mo just get a cache miss?

@jkraybill Any source string without a translation will be returned by gettext as-is, without triggering the caching. So it still allows fast testing of JSON changes without having to recompile the language files.

**Comment by jkraybill** [comment]
@Qrox yeah awesome, I'm all for it if that's the case! Thanks for looking into this, it's a real annoyance in my games!
