### ISSUE TITLE
Drunken master gives insanely unrealistic damage bonuses.

### ISSUE THREAD

**Issue by Dacendeth** [CleverRaven/Cataclysm-DDA#38873]
# Describe the bug
Drunken master allows for a drunk character with no skill and 4 strength to hit harder than a 20 strength 10 melee/10 unarmed character

# Steps To Reproduce

1. make a character with drunken master, 4 strength, and no skills
2. get wasted and hit a debug monster for inhuman levels of unarmed damage.

# Expected behavior
For drunken master to make you a little better at combat while drunk, not insanely better.

# Screenshots
![image](https://user-images.githubusercontent.com/26881007/76987904-4e2f2480-691a-11ea-9df2-996f83d2a374.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-13183-gabec138 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
This gets even more crazy when a drunken master has skill and an unarmed weapon, hitting 100-200 damage range.

**Comment by jkraybill** [comment]
I'm sure this is a controversial opinion, but given that the game strives for a basis in reality/science, I'd be in favor of removing drunken master entirely.

**Comment by Mecares** [comment]
Moving it to Crazy Cataclysm seems to me like a better option than just removing it.

**Comment by KorGgenT** [comment]
> Moving it to Crazy Cataclysm seems to me like a better option than just removing it.

I'm not sure it's funny enough to fit the requirements of being in crazy cataclysm.

**Comment by Tamiore** [comment]
Another option that will probably work is replacing damage bonus with accuracy bonus. Been crazy accurate when drunk is somewhat unrealistic, sure, but doesn't really necessarily contradict any "hard" logic.

**Comment by jkraybill** [comment]
@Tamiore alcohol is scientifically proven to simply impair both accuracy and speed of cognitive and motor tasks, so unfortunately, yes it does contradict hard logic. There is an incredible volume of studies on the subject, example here: http://www.coping.us/images/Scweizer_et_all_2008_Alcohol.pdf

I'm not lobbying hard for the removal of drunken master, but it's based on a Jackie Chan film and associated myths like Liu Qizan - it has no basis in reality.
