### ISSUE TITLE
Military corpses holster w/ Beretta M9A1 without magazine

### ISSUE THREAD

**Issue by natsirt721** [CleverRaven/Cataclysm-DDA#38910]
# Describe the bug
Looting some military corpses and I found a holster with a Beretta M9A1, but there was no magazine in the gun.

# Expected behavior
As the M4A1s all had magazines in them, I would expect a mag in the Beretta as well.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.D-13313-g59a5acb [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Beta National Guard Camp [national_guard_camp],
    More City Locations [cityside],
    More Locations [more_locations],
    Boats [boats]
]

**Comment by Night-Pryanik** [comment]
I personally see nothing wrong in guns spawning without magazines on corpses. Maybe the absence of magazine was the indirect cause of their death?

**Comment by natsirt721** [comment]
Haha I thought the same thing, the guy is backed into a corner and reaches for his sidearm *click* no mag. The disconnect for me is that his M4 was loaded but his sidearm wasn't. It didn't make sense to have a firearm at the ready like that without a mag in it. Without bullets sure, but without a mag at all?

I think this is an unintended consequence of how the item collection system handles magazines. It only adds a mag if there is ammo/charges, so if the RNG rolls 0 ammo, it doesn't add a mag. 

I added a test group with a single M9 with [0, 1] charges, and ran the test item group debug option.  ~50 of the results were *Beretta M9A1 (9x19mm)* and the other 50 were *Beretta M9A1 (1/15 9x19mm)*. I would naively expect the first one to say *Beretta M9A1 (0/15 9x19mm)*, but that might just be how the strings are handled. Anyway, I don't know how to actually spawn an item from the group to check if the mag is there or not.
