### ISSUE TITLE
Freeze possibly related to NPCs and faction camp

### ISSUE THREAD

**Issue by jeremyshannon** [CleverRaven/Cataclysm-DDA#38917]
# Describe the bug

The game now freezes when I approach my faction camp. It begins using 100% cpu and continues indefinitely.

# Steps To Reproduce

Load the attached save, drive up to the camp. Or approach on foot, either way it begins spinning forever.

# Expected behavior

I'd prefer it if he game would exit out of whatever it's trying to do in under an hour of 100% CPU usage, 'cause I gave up waiting at like 90 minutes. I imagine less zen players would like it to be even sooner.

# Screenshots

# Versions and configuration

Version 0.D-13155-gb5bc0a6654 on Linux, 64 bit
Mods loaded: DDA, Disable NPC Needs, Magiclysm, More Survival Tools, Mythological Replicas, DinoMod, Crazy Cataclysm, Mutant NPCs, Mythical Martial Arts, No Fungal Monsters, various blacklists, Stats Through Kills

# Additional context

Save file: https://anonfiles.com/l596B0i5ob/fablevalley-Mar20-campfreeze.tar_gz

I did erase a bunch of the surrounding map files, hoping to get some of the new Magiclysm content to spawn closer than like five game days' drive, but I've been to and from camp multiple times since that.
 I did enable a bunch of zones and set NPCs to cutting tall grass and working on repairing a vehicle the day before I left the camp, about two in-game days before this save (intending to come back that night, but having a mishap), I suspect it's something to do with all that zone stuff.

**Comment by davidpwbrown** [comment]
Have you updated since https://github.com/CleverRaven/Cataclysm-DDA/pull/38655 was merged 8 days ago?  ( I cant remember how to read those build numbers )

**Comment by jeremyshannon** [comment]
Oh yeah, just yesterday I realized the build was a bit old and updated, and it still freezes up. I should have added that, but I forgot.
 (I used to have trouble with the autogenerated build number too until I realized it has the last commit at the end, you just have to take the g off the front. So that version is up to b5bc0a6654)

**Comment by davidpwbrown** [comment]
I'll look into it.

**Comment by davidpwbrown** [comment]
Ah, found it,  
1. NPC wants to pickup a tool to repair the vehicle, 
2. NPC has no storage space to pick up the tool, NPC bails out of the fetching task.
3.NPC didnt realise that this makes the task impossible.
4. NPC goes back to step 1.
forever.
