### ISSUE TITLE
Glycerol in vehicle tanks shows volume incorrectly

### ISSUE THREAD

**Issue by pjf** [CleverRaven/Cataclysm-DDA#38925]
# Describe the bug

When placed in a vehicle tank, glycerol shows an extremely high volumes.

# Steps To Reproduce

1. Make or find a vehicle with a tank
1. Fill the tank with a gallon of glycerol
1. OMG, what's happened to the volume?

# Expected behavior

Glycerol should show the same volume in both regular bottles and vehicle tanks.

# Screenshots

![How much glycerol?](https://user-images.githubusercontent.com/12072/77232521-c128dd00-6b5e-11ea-86e3-8cc20323ae25.jpg)

This screenshot shows a tank where I've poured just shy of two gallons into it.

# Versions and configuration

eb08a43fd489a9b598670c84a5c988878839692d with custom patches applied.

# Extra notes (edited)

Impacts the following liquids (and maybe more):

- Glycerol
- Dimethyl Sulfoxide
- Phenol
- Ether

**Comment by pjf** [comment]
Bonus fun: The same happens with dimethyl sulfoxide.

**Comment by Pupsi-Mupsi** [comment]
And also:

![grafik](https://user-images.githubusercontent.com/44737997/77238204-89f21480-6bce-11ea-8e3e-b35964009c4f.png)

**Comment by Pupsi-Mupsi** [comment]
Hello @jkraybill!

I'm not 100% sure, but it seems that your PR #38627 was probably causing this little bug. The introduction of fuel bunkers in #25245 may have been the reason why vehicle tanks were not previously shown in L. I hope my intention is not lost in the translation. Could you please take a look at what might have happend? 

![grafik](https://user-images.githubusercontent.com/44737997/77699998-aec1ff80-6fb3-11ea-9fdf-c4957f9b2a24.png)

**Comment by jkraybill** [comment]
@Pupsi-Mupsi yeah that seems plausible. Will take a look.
