### ISSUE TITLE
Woodbow (from Druid spell Nature's Bow) requires arrows

### ISSUE THREAD

**Issue by seraphistus** [CleverRaven/Cataclysm-DDA#38922]
# Describe the bug

The Woodbow generated by the Magiclysm Druid Spell "Summon Nature's Bow" requires arrows as ammunition (as opposed to generating it's own ammo or functioning like the "electric alien frond", for example.

# Steps To Reproduce

Create a new character, dump points into Str, Int, Spellcraft
Spawn a light source
Spawn a "Book of Trees"
Learn spell "Nature's Bow"
Cast "Nature's Bow"
Wield Woodbow
Attempt to fire Woodbow with "f" (Fire Wielded Item) returns
"Your || Woodbow (xx turns) is empty!"
Attempt to reload Woodbow without arrow inventory with "r" (Reload) returns "You don't have any arrows to reload your || Woodbow (xx turns)"

# Expected behavior

Woodbow would either not require ammo, or would generate ammo upon reload, as per spell description

# Versions and configuration

- OS: Windows 10
    - OS Version: 10.0 1903
- Game Version: 0.D-13313-g59a5acb [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm]
]

# Additional context

I have reproduced this issue in multiple game worlds/mod combinations: 
+/- included:
    Arcana and Magic Items
    Stats through Skills

**Comment by seraphistus** [comment]
![BugReportWoodbow](https://user-images.githubusercontent.com/62465495/77225207-1b17ab80-6b3b-11ea-8f42-4e71c26eca53.png)

**Comment by wapcaplet** [comment]
I can reproduce this in 0.D-13323. The bow appears in my inventory as having "(0/1 arrows)":

![image](https://user-images.githubusercontent.com/238395/77241791-f9f79f00-6bbc-11ea-9bd0-c401f8dbb81c.png)


- OS: Linux
    - OS Version: LSB Version: core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch; Distributor ID: Ubuntu; Description: Ubuntu 18.04.4 LTS; Release: 18.04; Codename: bionic; 
- Game Version: 0.D-13323-g3a81a71c6f-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm]
]

**Comment by foulman** [comment]
Yeah, I remember I had to do quite a bit of tinkering to get that working right.

**Comment by wapcaplet** [comment]
By using `git bisect` I determined that commit b86273a5ad7fa from PR #38810 caused this issue.
