### ISSUE TITLE
Cannot switch display monitor / game cannot detect different monitors

### ISSUE THREAD

**Issue by Mastc** [CleverRaven/Cataclysm-DDA#38921]
Game version: 10433 Experimental

Operating system: Windows 10

Tiles or curses: Tiles

Mods active: Just base game

### Expected behavior
Go into the options menu of CDDA, graphics, and switch the display to a different monitor so that it opens on whichever one you choose
### Actual behavior
Go into graphics, but the display only shows "Display 0" and does not change despite pressing enter or attempting to change it in any way
### Steps to reproduce the behavior
Open CDDA, go to the options menu, then graphics, and try to change the display monitor.

I was able to change monitor by version 10313, but every version after that removed the ability to. I've tried redownloading and testing multiple times, but to no avail. 

![Screenshot_1](https://user-images.githubusercontent.com/46696110/77222343-3aeda600-6b20-11ea-890d-1cd247b682db.png)

![Screenshot_2](https://user-images.githubusercontent.com/46696110/77222345-3fb25a00-6b20-11ea-91cd-8735805d4bd3.png)

**Comment by ZhilkinSerg** [comment]
Caused by #37548 - apparently display list is not available while SDL is not initialized yet, so it won't get populated in options and default display is always used.
