### ISSUE TITLE
Compound bow with wooden arrows demolishing brick walls

### ISSUE THREAD

**Issue by githubuser343** [CleverRaven/Cataclysm-DDA#38932]
# Describe the bug

Shot a wooden broadhead arrow using  a compound bow with arrow rest installed, missed a zombie and the arrow hit a brick wall. **The brick wall collapsed from the wooden arrow impact.** Bow was set to medium setting (9 strength requirement)

Character stats:
Strength 10
Dexterity 10
Intelligence 9
Perception 9

Archery 2
Marksmanship 3

# Steps To Reproduce

1. Make a no skill 10 strength character with a compound bow and some wooden broadhead arrows
2. Shoot **wooden** arrows from a compound bow at a **brick wall**
3. Watch brick wall collapse

# Expected behavior

Arrow disintegrating from impact, boinking off of wall or getting stuck in it.

# Versions and configuration

Latest experimental as of this post with no mods.

**Comment by Shodan14** [comment]
Another problem with archery, must be a day that ends with y.

**Comment by CoroNaut** [comment]
It's a feature.
