### ISSUE TITLE
Steel drum (100L) is not mountable to vehicles

### ISSUE THREAD

**Issue by Skmer** [CleverRaven/Cataclysm-DDA#38968]
I'm searching for a bigger tank for my car and was happy i found some 100L steel drums at a military helipad, but as it turns out you can only roof mount 200L drums to your vehicle

My wish: Make 100L drums mountable

Alternatively convert the 100L drums into 200L

Thanks for your work!

**Comment by Pupsi-Mupsi** [comment]
Hello Skmer!

In fact, steel drums can only be used as external tanks.
Can you test if you can install the 100l drum externally?

Please let me know if it worked.

Stay safe!

![grafik](https://user-images.githubusercontent.com/44737997/77691515-56840100-6fa5-11ea-966a-a26aed1ba81e.png)

![grafik](https://user-images.githubusercontent.com/44737997/77691557-6dc2ee80-6fa5-11ea-9ca9-e91584586a48.png)


- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.D-13294-gd863481 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    No Fungal Monsters [No_Fungi],
    GP-Mods [gpmod]
]

**Comment by Pupsi-Mupsi** [comment]
I have to admit that I wasn't aware of it. You can mount 100 or 200 steel drums internally. But first you have to make room for them. So remove the seat or whatever is in the way.

Example:
![grafik](https://user-images.githubusercontent.com/44737997/77696929-30169380-6fae-11ea-9f14-665382b7ae8a.png)

**Comment by Pupsi-Mupsi** [comment]
Sorry, it took me so long to get what you were talking about ;-)
Add roof-mounted external tank (100L) in #39047.
