### ISSUE TITLE
Vehicle coolers do not cool nonvehicle tiles

### ISSUE THREAD

**Issue by ProfessorRich** [CleverRaven/Cataclysm-DDA#38973]
# Is your feature request related to a problem? Please describe.
Vehicle coolers appear only to cool vehicle tiles.

To test - build a one tile vehicle, attach a vehicle cooler and charged battery, turn it on. Use diver's watch to check temperature of tiles. Press 'f' to pay respects to your plan to get through summer without overheating. 

# Describe the solution you'd like
Vehicle coolers should also cool adjacent non-vehicle tiles

# Describe alternatives you've considered
Vehicle coolers can only be installed on enclosed vehicles (making them more like a refrigeration unit)

![image](https://user-images.githubusercontent.com/61430939/77332268-c3836680-6d19-11ea-96ca-8889c5eddc90.png)

**Comment by ZhilkinSerg** [comment]
Please attach a savegame.

There is debug overlay that can display tile temperature. You can also examine tiles (or use map editor in debug menu) to see whether tiles contain cold air fields.

**Comment by Hirmuolio** [comment]
There is also temperature overlay in the debug menu.

IIRC the vehicle cooler is not very powerful and the cooled air it pumps out just dissipates into nothingness in open spaces.

**Comment by ProfessorRich** [comment]
Ok, so after moving things around it is actually affecting other tiles, but seems quite erratic. 

Perhaps intended behaviour IS this? But split seconds of -3 degrees followed by 18 degrees ambient temperature... seems weird behaviour to me. Save attached for you to have a laugh with - don't ask why I'm naked and covered in claw marks... something embarrassing just happened and I'm in the process of rectifying. XD

![image](https://user-images.githubusercontent.com/61430939/77423188-a8226500-6dc6-11ea-8eb6-4c09e3e8faa1.png)
[Ricardo.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4375081/Ricardo.zip)

**Comment by natsirt721** [comment]
This looks like you're trying to cool off by blasting the car's AC and then standing outside with the door open. That's not going to work no matter what planet you're from. Yeah, the area right by the cooler will be cold, but you're just venting all that cold air out into the atmosphere which has basically infinite capability to absorb heat (or lack thereof, I guess)
