### ISSUE TITLE
Sourdough bread creates calories from nothing. 

### ISSUE THREAD

**Issue by gynther** [CleverRaven/Cataclysm-DDA#38981]
Sourdough bread creates calories from nothing. 
The recipe uses 4 flour, 1 sourdough starter and 3 water and creates 8 portions of sourdough bread aswell as an freshly fed sourdough starter.

In my case the flour had a calorie value of 34 so a total of 136 calories of base food was used.
The 8 sourdough bread had a calorie value of 174 each for a total of 1392.

I've confirmed that just 4 flour is used in the crafting process.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.D-13361-g6fc9301 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Alternative Map Key [alt_map_key],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Craftable Gun Pack [craftgp],
    No Fungal Monsters [No_Fungi]
]

**Comment by natsirt721** [comment]
That seems fine to me. I could see the flour input increasing by a bit (4 flour is about half a cup, i would probably double that).  Lots of those calories come from the starter. 

I went on a deep-dive looking at caloric counts for flour and bread in general, and I think that bread from wheat flour should actually be doubled in calorie count - currently it gives 91 kCal per 60g serving, and [this source](https://www.calorieking.com/us/en/foods/f/calories-in-breads-white-bread/MYdVDzj5TemqsaeIZiyMNw) suggests that it should be around 159 kCal. [This one](https://www.nutritionix.com/i/usda/white-bread-1-whole-loaf/566aef3ae5494f506a4ecdd1) says 2000 kCal for 750g, or 160 kCal per serving.

**Comment by gynther** [comment]
I'm not knowledgeable enough to argue game vs real life here, you seem to have done some research.
But I will argue that internal consistency is important. lets compare some other bread recipies. 

Bread: 20 flour (680cal) creates 10 loaves (970 cal)
Flatbread: 11 flour(374cal) creates 2 flatbread (528 cal)
cornbread: 4 cornmeal(188cal) creates 1 cornbread(188cal)
Humblepie: 20 flour(680cal) + 4 liver(276cal) creates 3 pies (1329)
and then sourdough that goes from 136cal to 1392cal

There is absolutely an increase in calorie for the wheat based products, but its about 50% for the others and a 1000% for the sourdough. I dont think the starter can be counted since its reusable and essentially free. And even if it was not reusable the starter costs 1 flour.

Also a quick googling shows several recipies using ~3 cups of flour per loaf, increasing the flour usage by 6 times for the sourdough recipie would bring it up to the same ballpark as the other flour based products.

**Comment by natsirt721** [comment]
Definitely agree about internal consistency. As I mentioned, I would actually like to see calorie increases for bread products in general, but that is largely going by the mass of the final product - reducing the mass (and volume, I suppose) would also 'balance' it, and bring the output more in-line with the amount of input material.  
Sourdough starter is basically dough - you let flour ferment with the natural bacteria and yeasts in the air and keep feeding it flour and water. 
The simplest solution I see is doubling the flour for the recipe and halving the number of portions in the results. Then we have 272 kCal in and 690 kCal out. That's a healthy gain, but you're also using ~half of a 250 mL starter which, as I said, is basically dough itself. So you get a cup of dough for 'free' from the starter, and another cup of flour and some water for the rest. I would also probably increase the amount of flour you need to make the other starters by a lot - probably 8 flour/1 cup each. With both of those changes, the total input is 12 flour or 408 kCal, which brings the gains in-line with the rest of the breads.
