### ISSUE TITLE
exponential growth of ammo-components through (batch) disassemble

### ISSUE THREAD

**Issue by barty68** [CleverRaven/Cataclysm-DDA#38982]
Hey folks, i didn't look for existing bug reports, so apologies if this has been reported already.

# Describe the bug
Using the disassemble menu, accessible via "(" [i believe..], my character disassembled a bunch of unused ammo and obtained components². Specifically i had 50 rounds of .357 magnum, hit "(" and entered in the prompt to disassemble "050" (amount) of .357 magnum and got 2500 .357 magnum casings and about a proportional amount of other components.

If you look up my save-file, the .357 casings are in the character inventory, there is pile of components under the car, right on the square of the character, and 3 to 6 squares to the north-west is a pile of casings i discarded.

I don't know which ammo types are affected, but it are several and this didn't happen before i updated to new experimental from a 8 month old build.

# Steps To Reproduce

1. take or debug some ammo (probably any type, but at least .357, 00shot, birdshot, .22LR, .380)
2. hit "(" to disassemble , select ammo, enter the full amount you have after the leading zero, hit "enter"
3. take a count of components

# Expected behavior

I don't want to cheat this easy. 

# Screenshots
none

# Versions and configuration

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4372445/save.zip)
[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4372447/config.zip)

 - OS: Win10
 - Game Version: 0.D-13361-g6fc9301
 - Graphics version: Loaded tileset: UNDEAD_PEOPLE
 - Ingame language: english

**Comment by gynther** [comment]
Can confirm that the same thing happens to me. Updated from a few day old build which I dont have the time to check right now.

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.D-13361-g6fc9301 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Alternative Map Key [alt_map_key],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Craftable Gun Pack [craftgp],
    No Fungal Monsters [No_Fungi]
]
