### ISSUE TITLE
Cannot quarter corpses with no organs

### ISSUE THREAD

**Issue by githubuser343** [CleverRaven/Cataclysm-DDA#38991]
# Describe the bug

Cannot quarter (butcher method) a giant web spider corpse.

# Steps To Reproduce

1. Try to quarter a giant web spider corpse
2. Get told I need "to perform field dressing before quartering"
3. Try to perform field dressing
4. Cannot perform field dressing because giant web spider corpse does not have any organs

# Expected behavior

Being able to field dress at least quarter a giant web spider corpse.

# Versions and configuration

Latest experimental as of this post with no mods.

**Comment by raithwind** [comment]
Okay, so I have no knowledge of coding in C but I think I know how to make this change work, if someone more knowledgeable in C could check and confirm:

update file:

data\json\items\corpses\corpses.json
add a flag
{ "flags": [ "NO_ORGANS" ]
to the types of creatures that have no organs, if such a flag doesn't already exist. 

then the C part of the change, change the quarter function that checks if the corpse has been quartered to also include:

corpse_item.has_flag( flag_NO_ORGAN )

As a third OR option alongside the current successful and failed field dress options.

**Comment by kevingranade** [comment]
Fixed by #45685
