### ISSUE TITLE
NPCs are impossible to headshot and critically hit.

### ISSUE THREAD

**Issue by Dacendeth** [CleverRaven/Cataclysm-DDA#39008]
# Describe the bug
The headshot critical hit and the normal critical hit mechanics just dont work on npcs anymore. 

# Steps To Reproduce
1. Get a character with any rifle, and even 10 all skills and shoot npcs with max aim over and over.
2. Get only good hits 

# Expected behavior
For the critical hit system to work on all targets.

# Screenshots

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-13374-g5cee241 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
I think #37241 changed how critical hits and headshots work, making them very hard to pull off on zombies and impossible on npcs.

**Comment by kevingranade** [comment]
Yes this is a bug, it is retrieving total HP instead of per-body-part hp, which makes it if not technically impossible to get a crit, worthless as triggering a crit requires dealing enough base damage to destroy the body part outright before the crit multiplier.
