### ISSUE TITLE
DEBUG    : Morale "Masochism" is inconsistent.  FILE     : src/morale.cpp  LINE     : 638

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#39016]
# Describe the bug

 DEBUG    : Morale "Masochism" is inconsistent.

 FUNCTION : player_morale::consistent_with(const player_morale&) const::<lambda(const player_morale&, const player_morale&)>
 FILE     : src/morale.cpp
 LINE     : 638

# Steps To Reproduce

Was running from a zombie and close to 0 stamina.

# Expected behavior
No error

# Screenshots

# Versions and configuration
- OS: Linux
- OS Version: LSB Version: core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch; Distributor ID: Ubuntu; Description: Ubuntu 18.04.4 LTS; Release: 18.04; Codename: bionic; 
- Game Version: 0.D-13361-g6fc9301 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [

    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Stats Through Skills [StatsThroughSkills]
]
# Additional context

debug file attached
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4382379/debug.log)

**Comment by Saicchi** [comment]
Can't replicate in `0.F-4074-g0068ddf27e`.

**Comment by Night-Pryanik** [comment]
Closing as unconfirmed.

**Comment by jimmycapizzi** [comment]
Just happened now to me.

 DEBUG    : Morale "Masochism" is inconsistent.

 FUNCTION : player_morale::consistent_with(const player_morale&) const::<lambda(const player_morale&, const player_morale&)>
 FILE     : src/morale.cpp
 LINE     : 852
 VERSION  : cdda-experimental-2024-12-27-1919 a014c17
