### ISSUE TITLE
Unloading an open container spills the liquid

### ISSUE THREAD

**Issue by BaumgeistOne** [CleverRaven/Cataclysm-DDA#39011]
# Describe the bug

Using the "unload" command on an open container like a drinking glass next to the player puts the container into the inventory and spills the liquid.

# Steps To Reproduce

1. Fill a drinking glass with a liquid, put it on the ground.
2. Try to unload it.
3. Observe the drinking glass being in the inventory and the previously contained liquid spilled on the ground.

# Expected behavior

I'd expect to be asked where to fill the liquid, like when unloading an open container held in hands.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 7
- Game Version: 0.D-13398-g6dc97db [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    No Rail Stations [No_Rail_Stations],
    Alternative Map Key [alt_map_key],
    Bionic Slots [cbm_slots],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by wapcaplet** [comment]
Confirmed in 0.D-13362 - while wielding an open container in the hands, the "Unload" menu gives a prompt for what to do with the contents:

![image](https://user-images.githubusercontent.com/238395/77536554-22ec8e00-6e62-11ea-8426-0500f1e3a016.png)

But if an identical cup of water is sitting on the ground, the "Unload" menu does not prompt after hitting Enter here:

![image](https://user-images.githubusercontent.com/238395/77536582-30097d00-6e62-11ea-9522-46205c9eca5d.png)

The clean water is dumped on the ground, and the empty cup is picked up.

This issue looks suspiciously similar to #38206 related to unloading a gun - and in fact someone has noted the liquid-unloading issue in the comments there as well.

**Comment by wapcaplet** [comment]
Cannot reproduce in 0.E-9737-g511ddcb179. `U`nloading an open/spillable container of liquid on the ground (plastic cup or tin can) correctly prompts for where to dump the liquid.
