### ISSUE TITLE
Holy Blade spell costs too much

### ISSUE THREAD

**Issue by Iron-Tree** [CleverRaven/Cataclysm-DDA#39023]
# Describe the bug
The spell Holy Blade when advanced to spell level four has a casting cost of 12588 māna, which is clearly more than is intended.

# Steps To Reproduce

1. Make a player with the paladins guide to spellcasting.
2. Study until spell level four.
3. Notice that the casting cost is going up.

# Expected behavior

As the player increases in knowledge about the spell it is expected that the casting cost will go down and/or the duration of the sword appearing goes up. It isn't expected that as the player increases knowledge of the spell it goes beyond his ability to cast.

# Screenshots

![image](https://user-images.githubusercontent.com/57273656/77580516-0b380700-6f41-11ea-883a-a69b89e988a0.png)

# Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.D-13348-g7f3a4a4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi]
]

# Additional context

I dunno. It might be due to the fact that the max duration of the sword spawned is 9000 which is somewhat ridiculously low. Surely at max level the sword will stay in the real world for at least an hour or two? Otherwise this cool spell is obsoleted as soon as one finds a library and gets a forge. The spell is too costly to be used repeatedly at it's base cost of 375 māna.

**Comment by anothersimulacrum** [comment]
The spell only costs 1275 mana?

**Comment by Iron-Tree** [comment]
No, 12588 mana is too much for the spell, especially because there is no increasing benifits for higher levels.

**Comment by anothersimulacrum** [comment]
It doesn't cost 12588 mana.

**Comment by Iron-Tree** [comment]
Hang on you were right.
But, the jump to 1275 mana is still a bit much from 375.

**Comment by Iron-Tree** [comment]
Sorry

**Comment by Iron-Tree** [comment]
I tried to fix it by making the max duration 60000 but I still have an insane mana cost...

**Comment by Iron-Tree** [comment]
And here is a screenshot that shows that at max level the spell is intended to be 375 mana.
![image](https://user-images.githubusercontent.com/57273656/77585469-6f5ec900-6f49-11ea-8616-0089821f6c81.png)

**Comment by Iron-Tree** [comment]
Don't worry, I was wrong, casting mana is affected by encumberence.
