### ISSUE TITLE
Dry Dung Fuel

### ISSUE THREAD

**Issue by Beardtongue** [CleverRaven/Cataclysm-DDA#39031]
# Is your feature request related to a problem? Please describe.
The absence of dry dung fuel in Cataclysm isn't a problem, but it may be a valuable alternative fuel for mid-game or challenge runs.

# Describe the solution you'd like
Add dry dung fuel as a recipe from mixing cow pies or manure with straw or withered plants. No tools needed. Finished product to be 2.0c in volume and longer-burning than 2.0c of splintered wood.

# Describe alternatives you've considered
1. Ignore.
Dung is already a passable primitive fuel, and addition is low-priority, if not ornamental.

# Additional context
In my opinion, with growing representation of traditional practices and indigenous sciences in Cataclysm, dry dung fuel would be a fitting addition to low-tech mid-game play.
https://en.wikipedia.org/wiki/Dry_dung_fuel

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/we-make-terrible-suggestions-and-come-up-with-horrible-ideas-round-ii/17444/929
