### ISSUE TITLE
Tried to set invalid ammo of undefined-NULL for matchbook

### ISSUE THREAD

**Issue by snipercup** [CleverRaven/Cataclysm-DDA#39043]
# Describe the bug

I tried to find a similar bug in the issue list but could not find any.

While walking into the military base, I got this message.

```
 DEBUG    : Missing item definition: NULL

 FUNCTION : const itype* Item_factory::find_template(const itype_id&) const
 FILE     : src/item_factory.cpp
 LINE     : 1370
```

Followed by

```
 DEBUG    : Tried to set invalid ammo of undefined-NULL for matchbook

 FUNCTION : item& item::ammo_set(const itype_id&, int)
 FILE     : src/item.cpp
 LINE     : 578
```

I found the bug while testing for the name-to-object conversion for Fuji's profession mod, that's why I tried to reproduce it on master and I could. I compiled the game earlier today using msys2. I don't know if fuji's profession mod has anything to do with this bug..

# Steps To Reproduce

1. Load attached save
2. Reveal map
3. Long teleport to north of the military base
4. Walk south into the military base and keep spamming debug->map->kill monsters
5. Observe the message shows up

# Expected behavior

Not show the debug message

# Screenshots

![image](https://user-images.githubusercontent.com/50166150/77681769-24b76e00-6f96-11ea-91de-aee3f9b233e7.png)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-13426-ge6031408de [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Fuji's Military Profession Pack [fuji_mpp]
]

# Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4389064/debug.log)

Save game (i called it like this because of tests I did specifically for fuji's mod but the bug may or may not also appear on vanilla)
[Fuji profession.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4389065/Fuji.profession.zip)

**Comment by xrogaan** [comment]
Using stable 0.E, I've got this exact issue right after killing a zombie soldier.

Debug log: https://gist.github.com/xrogaan/f165ca076f6a520cd49c30b88f58defa

Mods used:
```json
[
  "dda",
  "aftershock",
  "magiclysm",
  "no_npc_food"
]
```
