### ISSUE TITLE
10457 - Food spoiling in minifridge, freezer and in cans 

### ISSUE THREAD

**Issue by Apuru** [CleverRaven/Cataclysm-DDA#39051]
#38712 
Describe the bug

Food is spoiling at an accelerated pace, overnight while in the minifridge, freezer (while frozen) and while in cans. 

# Steps To Reproduce

1. Make food + canned food
2. Put in fridge/freezer
3. Go to sleep in another Z-level (I usually set alarm for 7 hours)
4. Come back upstairs to see exactly half the fridge rotten, canned food rotten.

[food spoiling.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4391412/food.spoiling.zip)
This save is from stable. Download save, load in latest experimental and go upstairs, check minifridge. Leave reality bubble a bit, come back sleep 7 hours and look at minifridge, half the fridge will be rotten.

# Expected behavior

Food expected to last for a couple seasons shouldn't spoil overnight if put in the freezer or minifridge. Canned food unopened shouldn't spoil at all (it uses can sealer in the recipe).

# Screenshots

https://i.imgur.com/wH3kiCh.png
https://i.imgur.com/yYVMbwC.png

https://i.imgur.com/y7bzcWM.png

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.D-13426-ge603140 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Mundane Zombies [Mundane_Zombies]
]

**Comment by Hirmuolio** [comment]
>This save is from stable. Download save, load in latest experimental and go upstairs, check minifridge. Wait 1 day/Sleep 7 hours and look at minifridge, half the fridge will be rotten.

Could not reproduce.

Loaded save.
Walked to the fridge (it is on same level so no going upstairs).
Looked at the items inside.
Waited.
Looked at the items again. No unnatural rot present.

There are no canned foods (other than one can of sardines) to see food rotting in sealed containers. Also no minifreezer nearby.

**Comment by Apuru** [comment]
You may need to leave the reality bubble instead of waiting nearby and checking after sleeping. 

The unnatural rot was present after my character slept ~7 hours.

**Comment by Hirmuolio** [comment]
Taking a full night of sleep downstairs (out of reality bubble with z-level off) and still no unusual rot.

**Comment by Hirmuolio** [comment]
May be related to #36401, #38353, #34316 and #37952.

**Comment by int-ua** [comment]
Removing bug label until a confirmation status is decided upon.

**Comment by int-ua** [comment]
Please test on 0.E-3 and comment if you are still able to reproduce it. It sounds like https://github.com/CleverRaven/Cataclysm-DDA/commit/2a6ac5bcc085f54a4e483c31f463f0e15d8abe18 so I'll close for now.

**Comment by kholat** [comment]
This still happens, you guys need to not just look at the items but take them out of the fridge, it instantly fast-forwards their spoil time to rotten.

**Comment by Fettoken** [comment]
As kholat mentioned. This happens when leaving food in the freezer for an unknown amount of time for me. The food is fine beforehand. Lets say i butcher a creature and put the chunk of meat in the freezer, and the meat is labeled as frozen. A week later, i take it out, and it is directly labeled as rotten or old. The freezer in question is from Blaze Industries, vehicle freezer.
