### ISSUE TITLE
Ability to strap weapons with shoulderstraps to power armor

### ISSUE THREAD

**Issue by OldFriendEr** [CleverRaven/Cataclysm-DDA#39067]
# Is your feature request related to a problem? 
Right now you can only strap shoulder strapped weapons to a salvaged power armor

# Describe the solution you'd like
The shoulder strap weapons wearable with power armor.

# Describe alternatives you've considered
Leaving the PA as it is

# Additional context

There are quite few power armor fantasies, so people have quite diverging expectations from power armor in CDDA.

Initial considerations: 

* I understand that PA lore intended that PA would not be used for extended missions, hence no strap-ability
* I doubt that a survivor would not find a way to strap stuff ( in this case a weapon) to his PA.
* Strapped gear would interfere with an active defensive system 
* A special weapon mod, could be used to strap or attach weapons to a working PA

I'm planning to solve the feature myself after reading though your opinions, Thank you.

# Stating personal interest:

I'm not a PA  user myself, i usually mutate too much to use them, I only opened this request by participating on discord.

**Comment by kholat** [comment]
What if there is a new craftable* weapon mod added, some kind of "power armor sling" that you add to weapons and then you can only allow weapons with that mod to be we worn. This way you dont disrupt balance of not allowing strapped items to be worn (such as also backpacks not just weapons).

*maybe not craftable? But the way i see it its just a system of some straps on the outside of your armor.

**Comment by 182crazyking** [comment]
With regards to adding a new craftable item, the existing shoulder strap mod has the OVERSIZE flag, implying that there's some kind of slipknot or buckle that lets you resize it. I don't see why it would be okay with large mutated anatomy, but wouldn't work with powered armor, from a logical perspective.

**Comment by OldFriendEr** [comment]
> 
> 
> With regards to adding a new craftable item, the existing shoulder strap mod has the OVERSIZE flag, implying that there's some kind of slipknot or buckle that lets you resize it. I don't see why it would be okay with large mutated anatomy, but wouldn't work with powered armor, from a logical perspective.

keep in mind that current straps works with salvaged power armor, so there could be something else in play

**Comment by OldFriendEr** [comment]
closing this issue as non issue as per ProjectLead comment on discord:

> kevingranade Today(2020 03 27) at 7:36 PM
> they should not work with power armor
