### ISSUE TITLE
Freeze

### ISSUE THREAD

**Issue by Zuzuk-null** [CleverRaven/Cataclysm-DDA#39079]
The game freezes while loading the tileset. Android 9, Wileyfox Swift 2

**Comment by Zireael07** [comment]
How much free space do you have? Also, the device only has 3 GB RAM...

**Comment by ZhilkinSerg** [comment]
Please report game version and tileset used.

**Comment by Zuzuk-null** [comment]
> How much free space do you have? Also, the device only has 3 GB RAM...

Oh, I only have 2GB of RAM

**Comment by NetSysFire** [comment]
No proper report. No information to debug. Also inactive since over a year.
