### ISSUE TITLE
Stacking throwing items have variable "Moves to fire" based on their stack count (bigger stack = more moves)

### ISSUE THREAD

**Issue by KurzedMetal** [CleverRaven/Cataclysm-DDA#39077]
# Describe the bug

If you throw nets, bolas or throwing sticks, the cost of the throw action depends of the numbers of items in the stack.

# Expected behavior

I was expecting the action to have a fixed movement cost (at least for my char with his current bonuses/penalties).

# Steps To Reproduce

1. Debug a stack of 3 bolas, put it in your inventory
2. Use 't' to throw the bolas
3. Check the Moves to fire in the sidebar (in my case it was 174)
4. Throw it
5. Check inventory, in WEAPON HELD you have a stack of 2 in your hand (3 debugged - 1 thrown), this is what triggers the bug.
6. Use 't' to throw another bola.
7. Check the Moves to fire in the sidebar, it's different from point 3. (in my case it was 130)

You can keep throwing, and as the stack gets lower, the cost of movement is reduced.

# Additional context
I did some analysis in the code/JSONs and i think I know what is the issue, but I'm not sure how it would be the best way to fix this because I'm not that experienced with C++ or the class designs...

All the affected items seem to be marked in the JSONs as "AMMO" type and "thrown" ammo_type (example of affected: net/bolas, not affected: throwing axes/knives).

When you wield or try to throw these kind of items, the whole stack goes to your hand in WEAPON HELD slot (in the case of throwing axes, only 1 item of the stack goes to the hand).

Then the code in calculates the attack_time() in item.cpp as:
![image](https://user-images.githubusercontent.com/1426680/77814153-40517000-708d-11ea-8164-b1058c4d8b45.png)
Which use volume()/weight() as part of the formula, and those methods return the volume/weight for the stack instead of a single item, changing the attack cost depending on stack size.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.D-13348-g7f3a4a4 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Alternative Map Key [alt_map_key]
]

**Comment by KorGgenT** [comment]
one fix would be to add `ret /= count_by_charges() ? charges : 1;` right below the first line of that function
