### ISSUE TITLE
npc mission can send player to retrieve software from a pharmacy without a terminal

### ISSUE THREAD

**Issue by Sijko** [CleverRaven/Cataclysm-DDA#39080]
# Describe the bug
sowftware DL quests are bugged

Now it's the third time i was sent by an npc to download a software specificly in the pharmacy, and for the third time there wasn't any terminal

# Steps To Reproduce
accept a quest
have fun

# Expected behavior
a terminal in the pharmacy

# Screenshots

# Versions and configuration
any exp D

# Additional context

**Comment by cirops** [comment]
It seems, looking at /json/mapgen/pharmacy.json, that no pharmacies spawn with terminals anymore. Would it be the case then to remove the NC_DOCTOR clause in src/mission_start.cpp:202?

**Comment by Night-Pryanik** [comment]
Tested right now on latest experimental as of April 14, 2021. The first NPC I met offered me to download software from a console in the pharmacy. I teleported there, and the console was there. So I'm adding a "Need confirmation" tag and removing a "Bug" tag.

**Comment by DemonPikachu** [comment]
I also hit this bug today. Pharmacy has no console. Someone on the forums said to move "top cabinet" to reveal some hidden console so I'm currently in the process of moving everything, but that was from a post 6 years ago.
