### ISSUE TITLE
Different symbols and colors for Autonotes

### ISSUE THREAD

**Issue by KurzedMetal** [CleverRaven/Cataclysm-DDA#39099]
# Is your feature request related to a problem?
There's usually too many autonotes generated and there's no easy way to check them without hovering one by one, which is annoying and time consuming.

# Describe the solution you'd like
There are two things that can improve this:
1. Simpler soltuion: Give different letters / colors by default to autonotes. The only reason why this may be a bad idea is if the player wants to have the letters/color combinations free for their own usage.
2. Complex but complete solution: Give the player the option to assign their custom symbol/color from the Autonotes Manager.

The main reason that I wanted this is for having a big red X for military roadblocks, but having better symbol/color code for the rest of the notes wouldn't hurt either.

**Comment by GGgatherer** [comment]
> Complex but complete solution: Give the player the option to assign their custom symbol/color from the Autonotes Manager.

It is already kinda sorta possible but you have to edit data/json/overmap/map_extras.json for that. Needless to say, it won't survive updating, and restoring it from saved copy is risky because it could've been updated and your copy would not have new map extras.

**Comment by natsirt721** [comment]
related #38648

**Comment by KurzedMetal** [comment]
Ok, I did made a search but didn't find anything, he didn't use the name "autonotes" like the game does. I'll close this since it's pretty much the same as 38648

**Comment by natsirt721** [comment]
good catch, ill update the name to reflect that in case anyone else tries to search
