### ISSUE TITLE
Blankets cut up into too many resources.

### ISSUE THREAD

**Issue by Dacendeth** [CleverRaven/Cataclysm-DDA#39093]
# Describe the bug
Blankets, fur blankets, and down blankets cut up into a really large amount of resources they are made of, way more than you get dissembling them 

# Steps To Reproduce
1. Cut up a fur blanket and note how many resources you get
2. compare it to the lengthy disassembly process and see the difference.

# Expected behavior
Cutting to be the quick inefficient harvest method instead of the quick and bountiful method 

# Screenshots
What disassembly can potentially get you
![image](https://user-images.githubusercontent.com/26881007/77837118-48fc8180-7133-11ea-84f0-5caad5bdd3eb.png)
What cutting up can get you.
![image](https://user-images.githubusercontent.com/26881007/77837127-5580da00-7133-11ea-85e1-84afe0242934.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-13400-gace1923 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

**Comment by cupnooodle** [comment]
Wonder if this is similar to the issue resolved by #39078

**Comment by anothersimulacrum** [comment]
It's not. This is a disparity between the auto-generated results from cutting things up and the human made recipe for disassembling them.
