### ISSUE TITLE
Filthy gear morale after reloading canteen with filthy water

### ISSUE THREAD

**Issue by starytroll** [CleverRaven/Cataclysm-DDA#39102]
# Describe the bug

After reloading a (clean) plastic canteen with water using filthy canteen with water, I got the message

" DEBUG    : Morale "Filthy Gear" is inconsistent.

 FUNCTION : player_morale::consistent_with(const player_morale&) const::<lambda(const player_morale&, const player_morale&)>
 FILE     : src/morale.cpp
 LINE     : 638"

# Steps To Reproduce

Probably, the following steps would reproduce this message:

1. Wear a plastic canteen.
2. Partially fill it with water.
3. Step on a filthy canteen (or other filthy container probably).
4. Reload your canteen using the filthy canteen.
5. Take any action and (probably) observe the debug message.

# Expected behavior

No debug message to appear, but maybe some warning that you are now wearing filthy gear (?)

# Screenshots

![obraz](https://user-images.githubusercontent.com/54743246/77847472-81e13880-71bd-11ea-93ea-1acd818922f7.png)

# Versions and configuration

- OS: Windows
    - OS Version: 8.1
- Game Version: 0.D-13486-g5a52d64 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Generic Guns [generic_guns],
    Alternative Map Key [alt_map_key],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context
I observed it with the canteen, but probably it is a more general case, with any wearable liquid container.

**Comment by nphyx** [comment]
This morale consistency check problem comes up any time you somehow add a morale changing flag to a piece of equipment that you're wearing. I just ran into it with a mod/PR I'm working on while applying "fancy" to worn equipment. The workaround is to not cause it to happen, but maybe this could be handled better in general.

**Comment by Night-Pryanik** [comment]
Fixed by #38965?

**Comment by OliveChukar** [comment]
Tested in ver 0.E-9072-g1bb53ba-dirty with core content pack dark days ahead only and also with the mods from the original report. When I refilled the clean canteen no message appeared. The water that went into the canteen was not dirty as shown in the screenshot.

**Comment by Night-Pryanik** [comment]
Ok, closing them.

**Comment by anothersimulacrum** [comment]
@OliveChukar Thanks for all the testing of issues, it's a great help!
