### ISSUE TITLE
Follower book-reading streamlining: by-skill instead of by-book

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#39129]
# Is your feature request related to a problem? Please describe.
Not a problem per se, it's more QoL request than anything. 
Currently, if you want an NPC to learn skill(s) by reading books, you have to babysit them: feed them those books manually, then tell them to read those books, one by one, skill level by skill level. If you're out in the field, they read till they get skill leveled up once, then they stop. They don't continue reading even if they can still learn more levels from the book. They don't start reading another book on the same subject which can give them more levels. They just stop reading and start procrastinating.

# Describe the solution you'd like
First of all, I'm not proposing removal of current system. It is a good thing if you want them to get some basic knowledge or just that one needed skill level. Now, to proposal.

**Add "read more about \<insert skill name here\>" to activities dialogue.** How it should work:
1) There must be basecamp storage zone defined nearby.
2) There must be books on selected skill in the storage.
3) If there are such books, NPC should check for those with:
-  skill lvl requirement is lower than current skill level
-  gives highest resulting skill level which is higher than NPC's current skill level
-  can fit in NPC's inventory
4) If found, fetch it and start reading.
5) NPC should read until either told to stop or can learn no more from the book.
5.1) *(not really needed but will help if NPCs don't have much carrying capacity)* If NPC can learn no more from the book, return it. Preferably to lootzone:books, if there's one defined inside basecamp storage. 
5) Repeat 3-5 if there are more books to learn from, otherwise finish.

# Describe alternatives you've considered
Continue using current system forever. Which is useful but less hassle is less hassle, right?

**Comment by nphyx** [comment]
It would also be nice if they put the books back after they're done reading them come to think of it. I'm in the habit of playing schoolteacher and gathering them up for recited lessons so I don't have to fish around in their inventories to get my books back :>
