### ISSUE TITLE
Quality color for jacking and lifting

### ISSUE THREAD

**Issue by Pupsi-Mupsi** [CleverRaven/Cataclysm-DDA#39121]
I was wondering why the typical "quality-color-cyan" is not shown in the vehicle menu.
Am I missing something?
**Please tell me what you think!**
<br />
At the moment it looks like this:

![grafik](https://user-images.githubusercontent.com/44737997/77936110-b2ef6500-72b2-11ea-935f-d77c7d10810c.png)

Is there a reason why it doesn't look that way?

![grafik](https://user-images.githubusercontent.com/44737997/77936139-bda9fa00-72b2-11ea-9dfc-bc2369bc9ca8.png)

Old Code:

![grafik](https://user-images.githubusercontent.com/44737997/77936380-1d080a00-72b3-11ea-9f26-54df9f0a46e7.png)

This worked fine. But is it okay to remove/change the code the way I did?

![grafik](https://user-images.githubusercontent.com/44737997/77936490-42951380-72b3-11ea-84dc-f6711dcf89fd.png)

**Comment by mlangsdorf** [comment]
Yes, please go ahead and submit that change.  I'm the vehicles maintainer and I approve your proposal.
