### ISSUE TITLE
Filthy CBM with no_filthy_clothes mod active

### ISSUE THREAD

**Issue by Kedrak** [CleverRaven/Cataclysm-DDA#39138]
Game version:     0.D-13526-g30c7d3c

Operating system:  Windows 10

Tiles or curses:  Tiles

Mods active:
  "dda",
  "no_npc_food",
  "makeshift",
  "More_Survival_Tools",
  "modular_turrets",
  "Salvaged_Robots",
  "alt_map_key",
  "more_locations",
  "FujiStruct",
  "Urban_Development",
  "deoxymod",
  "blazemod",
  "Heavy miners",
  "Tanks",
  "Graphical_Overmap",
  "Graphical_Overmap_Fujistruct",
  "Graphical_Overmap_More_Locations",
  "Graphical_Overmap_Urban_Development",
  "no_filthy_clothing",
  "novitamins",
  "StatsThroughSkills",
  "Cataclysm++",
  "MST Extra"

**Comment by Fris0uman** [comment]
CBM are not cloth, this is working as intended.
See https://github.com/Fris0uman/Easy-CBM-Mods for clean cbm mod

**Comment by Amoebka** [comment]
Steps to reproduce imply that filthy CBMs can't be cleaned when the mod is enabled, which IS a bug if it's true.

**Comment by anothersimulacrum** [comment]
You can't sterilize filthy CBMs in the base game too. The issue makes no mention of attempting to clean the CBM. 
Regardless of this all this mod is no longer supported, so there's no point keeping this issue open.
