### ISSUE TITLE
Problem with aiming at practice target

### ISSUE THREAD

**Issue by starytroll** [CleverRaven/Cataclysm-DDA#39136]
# Describe the bug

When I fire at practice target, the usual way [f] [p] to make the most precise shot is not working correctly. I need to press [p] several times.

# Steps To Reproduce

1. "Build" practice target.
2. Stand few tiles away.
3. Aim at it using [f] [p] and notice how you didn't shoot yet but only increased your aim slightly.

# Expected behavior

Firing after pressing [p] for the first time.

# Screenshots

After pressing [p] twice already:
![obraz](https://user-images.githubusercontent.com/54743246/78015218-66a33400-7349-11ea-9cb5-30ef30cc463a.png)

# Versions and configuration

- OS: Windows
    - OS Version: 8.1
- Game Version: 0.D-13486-g5a52d64 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Generic Guns [generic_guns],
    Alternative Map Key [alt_map_key],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

I was using pistol crossbow, but probably it works so for other ranged weapons as well.

**Comment by Dacendeth** [comment]
This happens when you aim at anything that's not an entity you can see, same thing happen if you try to shoot a wall or any ground tile you can see. Or any tile you cant see that has a monster/turret on it. Just another quirk that #38263 caused.
