### ISSUE TITLE
Inconsistency in move cost between throwing from inventory and wielding before throwing

### ISSUE THREAD

**Issue by esotericist** [CleverRaven/Cataclysm-DDA#39135]
# Describe the bug

If you throw items directly from inventory, the move cost can vary substantially from wielding that item then throwing it.

# Steps To Reproduce

1. note time
2. have a bunch of throwable items (I used 25 throwing knives)
3. throw them at a practice target directly from inventory
4. note elapsed time
5. have a bunch more throwables (25 more throwing knives in my case)
6. painstakingly wield them, one at a time, to throw at the target
7. realize you fumbled wielding halfway through, start over with new time and stack of knives
8. regret life partway through process
9. discover a drastic disparity in time counts

# Expected behavior

Ostensibly, "throw from inventory" should have an implicit wield attached that should cost the same as wielding manually, followed by the same cost to throw as if it's wielded. For some reason, this isn't the case.

# Versions and configuration

built from b10470 / commit 414e4cff92acdd7c53b9f50c389cdf9c2b4dfd75, with two tileset-related PRs for testing 

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 19.10; Release: 19.10; Codename: eoan; 
- Game Version: 0.D-13525-g319a94809222 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    eso_ui_bits [eso_ui_bits],
    Disable NPC Needs [no_npc_food]
]

# Additional context

Personal results from testing:
throwing 25 throwing knives from inventory with 8 strength, 0 throwing, took 45 seconds from clock. Move indicator in sidebar suggested 181 moves per throw, * 25 throws = 4525 moves, for 45 seconds.
throwing 25 throwing knives wielding first with 8 strength, 0 throwing, took ~ 73 seconds from clock. move indicator indicated 224 moves to wield, then 69 moves to throw, for 293 moves per toss, * 25 throws = 7325 moves, for 73 seconds.

math adds up from per-throw and aggregate basis, so we're not dealing with anything like a stack size problem like got fixed in #39090 but there's still something distinct between the code paths.

edit: the original report came from a discord user who experienced *shorter* throw times from wield then throw, than throwing directly from inventory, so it's not just the case that one is always higher than other, it seems like the formula for the two paths are desynced

**Comment by KurzedMetal** [comment]
ACTION_THROW seems to end up calling avatar::wield() for calculating the cost of wielding the item.
ACTION_WIELD seems to be calling game::wield()
Which seem to have quite different logic too

ACTION_WIELD calls loc.obtain_cost() to get the cost of the wield
ACTION_THROW calls Character::item_handling_cost() to get the cost of the wield

I'd bet they calculate different costs for each player action.
Now time to sleep, I'll leave further analysis to someone else.

**Comment by KurzedMetal** [comment]
> Personal results from testing:
> throwing 25 throwing knives from inventory with 8 strength, 0 throwing, took 45 seconds from clock. Move indicator in sidebar suggested 181 moves per throw, * 25 throws = 4525 moves, for 45 seconds.
> throwing 25 throwing knives wielding first with 8 strength, 0 throwing, took ~ 73 seconds from clock. move indicator indicated 224 moves to wield, then 69 moves to throw, for 293 moves per toss, * 25 throws = 7325 moves, for 73 seconds.

Wielding the throwing knives cost 112, throwing 69, the cost of wielding is x2 as expensive when you wield first and the culprit is:

https://github.com/CleverRaven/Cataclysm-DDA/blob/414e4cff92acdd7c53b9f50c389cdf9c2b4dfd75/src/game.cpp#L8485-L8487

and 

https://github.com/CleverRaven/Cataclysm-DDA/blob/414e4cff92acdd7c53b9f50c389cdf9c2b4dfd75/src/game.cpp#L8516

Which is calculating and reducing the cost of manipulating the item a second time, after `u.wield( to_wield )` which is already doing the wield cost.

A solution would be removing lines 8485 and 8516 and let only `u.wield()` process the cost.
