### ISSUE TITLE
Part of russian translation missing

### ISSUE THREAD

**Issue by wingbrother** [CleverRaven/Cataclysm-DDA#39131]
With update 10470 part of russian translation missing
Example heavy battery, there are a lot of such positions

Example of content /lang/po/ru.po before commit  71f1e5906a8ffac523a735bd9619a8824c435e80

#: lang/json/MAGAZINE_from_json.py
msgid "heavy battery"
msgid_plural "heavy batteries"
msgstr[0] "тяжёлая батарейка"
msgstr[1] "тяжёлых батарейки"
msgstr[2] "тяжёлых батареек"
msgstr[3] "тяжёлые батарейки"

after

#: lang/json/MAGAZINE_from_json.py
msgid "heavy battery"
msgid_plural "heavy batteries"
msgstr[0] ""
msgstr[1] ""
msgstr[2] ""
msgstr[3] ""

**Comment by ZhilkinSerg** [comment]
@BrettDong Could it be some error during data export from Transifex?
