### ISSUE TITLE
Kel-Tec PF-9 with magazine changes volume and not fit small holsters

### ISSUE THREAD

**Issue by akirashirosawa** [CleverRaven/Cataclysm-DDA#39137]
# Describe the bug
 When insert a magazine in Kel-Tec PF-9, for some reason it changes its volume (0.360 -> 0.420). With new volume it ceases fit small holsters. Seems, this is a bug. For example, when insert a magazine in Beretta M9A1, it does not change volume (as expected). See screenshots.

# Steps To Reproduce
Generate or find Kel-Tec PF-9 and compare its volume with and without magazine.

# Expected behavior
Kel-Tec PF-9 must fit small holsters and its volume with and without magazine should be same.

# Screenshots
Kel-Tec PF-9 empty
<img width="385" alt="1" src="https://user-images.githubusercontent.com/38557723/78024056-65c9cc80-7360-11ea-80cc-5f13fb51dde2.png">

Kel-Tec PF-9 with magazine
<img width="381" alt="2" src="https://user-images.githubusercontent.com/38557723/78024071-69f5ea00-7360-11ea-9808-e49532ce5d1d.png">

# Versions and configuration
- OS: MacOs
    - OS Version: Name: Mac OS X; Version: 10.15.4; Build: 19E266; 
- Game Version: 0.D commit 49145eea48baed0b494b6412eb34d2470acfbe7b [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations]
]

**Comment by LaVeyanFiend** [comment]
It's missing ``magazine_well``, will fix.

**Comment by akirashirosawa** [comment]
Seems, all Kel-Tec pistols `"copy-from": "kp32"` have this problem.
I think it's need to set `magazine_wel` on `kp32`.
I tried:
```diff
--- a/data/json/items/gun/32.json
+++ b/data/json/items/gun/32.json
@@ -131,6 +131,7 @@
     "dispersion": 480,
     "durability": 8,
     "min_cycle_recoil": 135,
+    "magazine_well": 1,
     "magazines": [ [ "32", [ "kp32mag" ] ] ]
   }
```
Everything works. Thank you. Will you create a PR?

**Comment by LaVeyanFiend** [comment]
About to post it, doing playtest now to see if magazine_well accepts metric strings.
