### ISSUE TITLE
Bad(?) formatting of material in various armor .json files

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#39143]
The current ammo_pouch.json in my version reads:
```
  {
    "id": "tacvest",
    "type": "ARMOR",
.....
    "material": "cotton",
```
where "material" should be:

```
    "material": [ "cotton" ],
```
- OS: Linux
    - OS Version: LSB Version: core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch; Distributor ID: Ubuntu; Description: Ubuntu 18.04.4 LTS; Release: 18.04; Codename: bionic; 
**- Game Version: 0.D-13513-g7294d30 [64-bit]**
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by matt32106** [comment]
I have found several places where the same issue appears. Does that mean that the json parser takes care of it?

**Comment by Qrox** [comment]
I think it's just that the json parser accepts both string and array as input for "material". We could of course make it consistent though.

**Comment by matt32106** [comment]
I'll post a PR.
