### ISSUE TITLE
Survivor Belt Conflicting with Holstered Items

### ISSUE THREAD

**Issue by AFoxInAviators** [CleverRaven/Cataclysm-DDA#39148]
# Describe the bug
When using a Survivor Belt, the stats of the belt itself will always be used over stats from a holstered tool, even when the holstered tool has better qualities than the qualities of the belt itself.

# Steps To Reproduce

Equip a Survivor Belt and holster a Crowbar. If you then attempt to pry things open (such as windows) you will be unable to. I assume this is due to the 1 Prying quality of the belt ovewriting the 3 of the Crowbar, despite both stats being listed when examining the belt with holstered crowbar. Equipping the crowbar in your hands allows you to use it normally.

# Expected behavior

When holstered, the Crowbar should still be used to pry open crates and windows. The same happens with Tool Belts or Firefighter Belts with holstered prying tools, but not with the Survivor Belt.

# Screenshots
![Screenshot_58](https://user-images.githubusercontent.com/50126862/78103545-74d56c80-73aa-11ea-8a33-066c48723fb8.png)
Note how it does not use the holstered Crowbar at all in the dialogue, instead attempting to pry with just the belt, failing, and backing out.

# Versions and configuration

OS: Win10
Version: 0.D-13513-g7294d30 (Tiles)
Language: English
Mods: 
![image](https://user-images.githubusercontent.com/50126862/78103811-0b099280-73ab-11ea-9c67-2241c9b7c0fc.png)

# Additional context

**Comment by EmberDragon** [comment]
This also happens when you have the survivor belt on, and you have a better item in your inventory for prying, such as a Halligan Bar.

**Comment by Termineitor244** [comment]
Survivor belts with tools included have been obsoleted, they are now just containers so this issue can be closed.
