### ISSUE TITLE
Re-add craftable bows / revert removal

### ISSUE THREAD

**Issue by Insanegame27** [CleverRaven/Cataclysm-DDA#39151]
# Is your feature request related to a problem? Please describe.
https://github.com/CleverRaven/Cataclysm-DDA/pull/39128 made recurve, reflex recurve and compound bows, along with compound crossbows, obsolete and removed the crafting recipes because the descriptions referenced modern materials that were erroneously assumed to be out of the ability of the survivor to make.

# Describe the solution you'd like
Revert the aforementioned merge, change the recurve and reflex recurve bows description to reference wood or composite construction and remove references to carbon fibre and fibreglass in the descriptions. The compound bow and compound crossbow recipe was perfectly fine.

# Describe alternatives you've considered
Compound bows could have their material changed to the less common aluminium ingot material for crafting, rather than sheet metal.

# Additional context
A few youtube videos support the making of powerful wooden recurve and reflex bows via heat treating (https://www.youtube.com/watch?v=GCwmo480nKU and https://youtu.be/WEjuuqVw-xM)

Following video shows the casting of a compound bow (except the limbs though aluminium casting should have worked) out of aluminium (https://www.youtube.com/watch?v=CxFIdRoqaFA), including a drop-down arrow rest

**Comment by KorGgenT** [comment]
Clearly in the linked PR Kevin explicitly stated that there will be bows that are craftable. Therefore, "just reverting" it isn't going to happen. As 0.E was released recently this is something that can be worked on without worrying about content freeze.

**Comment by Insanegame27** [comment]
Well closing it without discussing it feels a bit rude, but its obvious to me now that you don't care about the knowledge of a lifelong archer and multiple videos of a respected bowyer offering an opinion on how something could have been done better without killing Archery as a viable skill. No better way to fuck the game raw in the ass

**Comment by KorGgenT** [comment]
OK no, obviously you're arguing in bad faith and not reading our responses. I'm locking this topic too.
