### ISSUE TITLE
Can't leave foodplace break room (The mascot rises scenario)

### ISSUE THREAD

**Issue by maltouzes** [CleverRaven/Cataclysm-DDA#39150]
Game version: 0.E 10478

Operating system: Linux

Tiles or curses: Curses

Mods active: None

### Expected behavior
I just want to leave the place.

### Actual behavior
You must use a card in the card-reader but you have no card...

### Steps to reproduce the behavior
Choose "The mascot rises" scenario with the "survivor" profession

### Solutions
- Remove survivor profession from this scenario (easiest choice)
- Add card item in the inventory of the player for this scenario (best choice)
- jump through the window... and break your legs. (bad choice)
- kill the npc and take his card if he got one... (ethical, moral choice)

**Comment by Fris0uman** [comment]
You don't need a card, you need to put a foodperson's mask on. Just tested it and it works as intended.

**Comment by maltouzes** [comment]
My mistake.
