### ISSUE TITLE
Light sources cause enemys to be unable to see you at specific ranges.

### ISSUE THREAD

**Issue by Dacendeth** [CleverRaven/Cataclysm-DDA#39166]
# Describe the bug
If you have a flashlight near by, or an electronic light wall tile near you at exactly 5 tiles away enemies become unable to see you.

# Steps To Reproduce
This is most easy to reproduce with a turret, but it seems to work on all things.
1. Spawn a turret 5 tiles away from you in the bright daylight
2. Turn on a flashlight or lantern or any non natural light and notice how it cannot see you anymore
3. move around it keeping the distance of 5 and see how it never can tell you're there

# Expected behavior
Lights to not be situational cloaking devices.

# Screenshots
It cant see me.
![image](https://user-images.githubusercontent.com/26881007/78211521-35c31c00-747b-11ea-904f-3a8ac4b1c415.png)
Now with it off it can see me.
![image](https://user-images.githubusercontent.com/26881007/78211543-44113800-747b-11ea-8861-29be797eea90.png)
The light source needs to be within 3 tiles for the magic to happen, it will be able to see me if im one more south.
![image](https://user-images.githubusercontent.com/26881007/78211639-8dfa1e00-747b-11ea-8769-d140ddbb9fe7.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-4-gae54c8c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
I believe this is the issue that #38131 had.

**Comment by Dacendeth** [comment]
Upon further testing it's actually not just range 5, recorded it not being able to see me at ranges 5, 10, 15, 20, 23, 27, 30, 40, 43, 46, and 49.

**Comment by Zireael07** [comment]
Huh, at first it is multiples of 5, but then you have 23, 27, 43, 46 and 49...

**Comment by matt32106** [comment]
and not 33 36?!

**Comment by Tiefoone** [comment]
This doesn't seem to apply to NPCs, I placed an NPC at 15 tiles distance with an Atomic Headlamp on and a turret nailed him, if I stand in the same position I'm still ignored.
