### ISSUE TITLE
Repair vehicle part takes less resources than repairing source item

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#39170]
# Describe the bug

Fixing 60L tank as an item takes welding gas/battery charge and 24 scrap metal per item condition tier. Fixing that same tank when it is a part of a vehicle only takes welding gas/charges, no metal required. Working as designed or a bug?

# Steps To Reproduce

1. Spawn 60L tank, kick it or w/e to make it dented.
2. Try fixing it with arc welder or acetorch, see that you need scrap metal.
3. Find a vehicle, weld the tank onto it and try fixing the tank there. Magically, you only need gas/battery charge, no metal required!

# Expected behavior

Either you shouldn't need scrap metal as an item, or you should need that metal when fixing a vehicle part.

# Versions and configuration

- OS: Windows 7x64
- Game Version: 0.D-13513-g7294d30 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Aftershock [aftershock],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills],
    Magiclysm [magiclysm]
]

**Comment by Dacendeth** [comment]
This technically applies to almost if not all of the metal things that go on vehicles, frames and such.
