### ISSUE TITLE
Cutting up television produces 80 plastic chunks

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#39174]
# Describe the bug

That's definitely more than any IRL TV has.

# Steps To Reproduce

# Expected behavior

# Screenshots

# Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.E-62-g1f7e4acc1b-dirty [64-bit]
- Graphics Version: Curses
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

# Additional context

**Comment by Zireael07** [comment]
IIRC cutting just considers the volume of the item (and IIRC it was reported already)?

**Comment by LaVeyanFiend** [comment]
It probably shouldn't have a cut-up option at all.
