### ISSUE TITLE
Items with charges spawning exactly half-full in chargen

### ISSUE THREAD

**Issue by LaVeyanFiend** [CleverRaven/Cataclysm-DDA#39176]
# Describe the bug

Items with charges, such as magazines, bottles of liquid, or batteries have exactly half their charge when generating a character.

# Steps To Reproduce

1. Select any profession that has a gun or phone.
2. Notice ammo/batteries are always half full.

# Expected behavior

Charge according to their defined amount in character generation.

# Screenshots

![image](https://user-images.githubusercontent.com/51099123/78281751-28dd1180-74e9-11ea-845d-0e1f59050b9b.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-63-g8abe67d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

# Additional context

**Comment by GGgatherer** [comment]
um... what IS that "defined amount" you speak of?

**Comment by LaVeyanFiend** [comment]
The amount specified in professions.json

**Comment by Talvan** [comment]
It's the same with every profession in the game. Quivers and magazines are half full, batteries are half charged, bottles are half full.

**Comment by Talvan** [comment]
It seems that #39620 hasn't fixed the issue.
