### ISSUE TITLE
Bandits should know where their landmines are/NPC trap awareness

### ISSUE THREAD

**Issue by natsirt721** [CleverRaven/Cataclysm-DDA#39189]
# Is your feature request related to a problem?
Bandits (and NPCs in general) should be aware of landmines and other traps set by them (read: generated in their spawn tile/map area). Just had three bandits charge out the front gate of the 4-tile camp and get blasted to smithereens by a landmine.

# Describe the solution you'd like
For map tiles that include static NPCs and hidden traps, NPCs should be aware of the traps.

# Describe alternatives you've considered
Adding a faction tag to traps (similar to items and vehicles) might be a good solution, this would prevent wandering faction members from triggering otherwise friendly traps. Simply giving knowledge of traps in their spawn overmap tile is insufficient due to the increasing number of multi-tile buildings.

**Comment by waveyl** [comment]
also hub01 and their turret, they are hostile to each other
