### ISSUE TITLE
Cannot fill a bucket with water 0.D-13513

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#39183]
# Describe the bug
I try to 'Pour into a container' water from a shallow water pond into a bucket. The UI says 'You don't have a suitable container for carrying water'.

# Steps To Reproduce
Go next to a shallow water pond with a bucket in your inventory. Hit 'e' then 'c'. 

# Expected behavior
The bucket should fill with water.

# Screenshots

# Versions and configuration
- OS: Linux
    - OS Version: LSB Version: core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch; Distributor ID: Ubuntu; Description: Ubuntu 18.04.4 LTS; Release: 18.04; Codename: bionic; 
- Game Version: 0.D-13513-g7294d30 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by anothersimulacrum** [comment]
This issue is invalid. You cannot fill open containers that are in your inventory, only ones on the ground or in your hands.

**Comment by matt32106** [comment]
I confirm that I can fill it when I wield it. But I can fill a bottle without wielding it. I understand the logic of open vs closed containers but it is not intuitive nor UX friendly. Maybe there should be a message saying "open containers need to be wielded/on the ground"?! What do you think?

**Comment by matt32106** [comment]
Feature request #39215 created
