### ISSUE TITLE
Using Ace-Torch to remove metal doors is silent and takes only 17 seconds

### ISSUE THREAD

**Issue by AncientSion** [CleverRaven/Cataclysm-DDA#39182]
When you use an oxy torch to remove any given metal door (lab, police station etc), it will happen within 16 seconds and it will make no noise whatsoever.

I would think that the noise could maybe be like run level (9) but especially the time requirement should be increased.
Now im no expert,but i guess if we assume you just remove the handle and cylinder element it would take maybe like 2 minutes.
For a serious "metal door" where you actually remove the door instead of just the cylinder i would guess its maybe like 30 minutes or something ?
It would also require more oxy then (currently its flat 60).

Perhaps mechanics skill should factor in.

**Comment by Night-Pryanik** [comment]
I'm closing this in favor of #46257 which is essentially the same issue, but has far more information in it.
