### ISSUE TITLE
Losing Night Vision starting trait after reloading save

### ISSUE THREAD

**Issue by solstrom** [CleverRaven/Cataclysm-DDA#39187]
# Describe the bug

Upon reloading a save (Save and quit, then load save again) with the "Night Vision" starting trait/mutation with the "Bionic Sniper" profession (with it's starting CBMs), your night vision mutation disappears. This happens even if you give the mutation via the debug menu as well, mutation still disappears on reload.

I believe it's an issue/conflict with one of the sniper's starting CBMs and Night Vision, but I'm unable to determine which one is causing the issue.

Night Vision seems to work correctly on other professions, loaded up a bog standard "Evacuee ; Survivor" Evac shelter start w/ night vision and trait/mutation stayed after reload.

# Steps To Reproduce

1. Create a new character & world
2. Select "Helicopter Crash" scenario, "Bionic Sniper" profession
3. Take "Night Vision" trait (stats/other traits don't seem to matter)
4. Load into world, then save and quit.
5. Reload save, and you no longer will have the night vision trait

# Expected behavior
Character keeps inherent night vision mutation even if they start with CBMs 

# Screenshots
When first loading into world (haven't quit yet):
![brokennightvision - pre reload](https://user-images.githubusercontent.com/63078596/78309455-96506880-7510-11ea-90ce-6e835577d1f1.png)
After reloading save:
![brokennightvision - post reload](https://user-images.githubusercontent.com/63078596/78309461-994b5900-7510-11ea-9bda-6bbbe25983b1.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-63-g8abe67d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins]
]

# Additional context

**Comment by anothersimulacrum** [comment]
Telescopic eyes removes the night vision mutation.

**Comment by solstrom** [comment]
Oh it does? i did not know that, may close issue then

**Comment by anothersimulacrum** [comment]
It's an issue that it lets you select the mutation, leave it open. I'm working on a fix.

**Comment by solstrom** [comment]
Alright.
