### ISSUE TITLE
Starting game with Magiclysm

### ISSUE THREAD

**Issue by SirClarke** [CleverRaven/Cataclysm-DDA#39199]
DEBUG    : Error: data/mods//Magiclysm/items/recipe_books.json: line 134:12: Expected number

    "intelligence": 9,
    "time": "20 m",
    "fun": "
           ^
            -1"
  },
  {

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 816

<!-- Steps to reproduce the behavior:
1. Start a new character and as it loads I get this ^

Game to start

**Comment by anothersimulacrum** [comment]
There is no line anywhere in the game files that matches the string reported here.

**Comment by SirClarke** [comment]
Damn I just updated and thats what i got anywhere else i should look?

**Comment by SirClarke** [comment]
Never mind I seem to have fixed it by Copying the (recipe_books.json) file off here and saving over my old one no idea how it got messed up but that seems to have been the problem
