### ISSUE TITLE
can study spells while morale is low, unlike studying skill books

### ISSUE THREAD

**Issue by Sassybrah** [CleverRaven/Cataclysm-DDA#39195]
# Describe the bug

You can learn/read spells when morales are low
# Steps To Reproduce

1. Get your morale to go low. Like depress
2. Learn/read a spell
3. Result

# Expected behavior

You can read/learn the spells,even with a very low morale, when you shouldn't be able to

# Screenshots

# Versions and configuration

Game version : Danny experimental release 10399
Android version
Graphic : Tiles
Ingame language : English
Mods loaded : Magicclysm, C.R.I.T expansion mod, Aftershock.

# Additional context

**Comment by GGgatherer** [comment]
Also, it seems studying spells doesn't affect focus (it even regens while you're studying).

**Comment by TandemE** [comment]
I think my experience is related: 
1. starting morale = 1
2. study spellbook for 30 minutes
3. by the end, morale is ~30, then suddenly drops to 1, and I get XP
