### ISSUE TITLE
Profession choice not effecting points

### ISSUE THREAD

**Issue by sick-trigger** [CleverRaven/Cataclysm-DDA#39208]
# Describe the bug
Choosing a different profession when making a new character doesn't give/cost any points
# Steps To Reproduce
1. Start new game with a custom character
2. Be a blackbelt for free
3. Be a tweaker for no reason
# Expected behavior
professions should have different point costs
# Versions and configuration
all default, latest experimental
# Additional context
wasn't present in the recent stable

**Comment by ZhilkinSerg** [comment]
@Qrox I suspect this could be just an UI thing after #38916. Can you please look into this if you have time and desire?
