### ISSUE TITLE
Shooting at an enemy that disappears/dies at the same time causes an infinite aim loop

### ISSUE THREAD

**Issue by TillsterRulz** [CleverRaven/Cataclysm-DDA#39200]
# Describe the bug

If you shoot an enemy (Most commonly spore clouds due to their behavior of poofing away) at the same time it disappears/dies away you will enter an infinite aim loop where the game/time still passes but you're unable to do anything until something else enters your crosshairs or the game crashes, clicking usually causes the game to instantly crash

If your game autosaves during this, the game will load the save with you still be in the infinite aim loop

# Steps To Reproduce

1. Acquire a gun/ammo and go to a zone with a relatively decent amount of fungus, the easiest way to start the bug
2. Go ham (I used 'p'recise aiming) shooting groups of fungaloids and spore clouds
3. Should a spore cloud poof away at the same time you shoot at it, you enter the infinite aim loop unless something else enters your crosshairs

# Expected behavior

For aiming to not continue after something disappears/dies

# Versions and configuration

 - OS: Windows 10 Home Version 1909
 - Game Version: 0.E 64bit
 - Graphics version: Tiles
 - Ingame language: System Language
 - Mods loaded: Dark Days Ahead, Disable NPC Needs, No Rail Stations

# Additional context

Here is my save file that is currently stuck in the infinite aim loop, I'm not sure how useful it will be but once you load in you should crash after a few seconds. Also if anyone could get my character to stop aiming that'd be nice

[Paisley Park.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4425394/Paisley.Park.zip)

There was also a reddit thread about this same bug and spore clouds a couple days before 0.E was released, so the bug is not just a 0.E thing

https://old.reddit.com/r/cataclysmdda/comments/frbjpo/aiming_with_ranged_weapons_frezees_the_game/

**Comment by Tiefoone** [comment]
Haven't fixed the problem but I fixed your savegame:
[Paisley Park.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4425701/Paisley.Park.zip)

**Comment by TillsterRulz** [comment]
I had an instance of this bug happen when an NPC follower killed a zombie I was aiming it so the bug is not exclusive to spore clouds. I updated my post to reflect this
