### ISSUE TITLE
Messages about fishes diving/leaping in the deep water that are impossible to see

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#39217]
# Describe the bug

# Steps To Reproduce

Load the save and go down into the basement.

# Expected behavior
No messages.

# Screenshots
![](https://tinystash.undef.im/il/2oNMXnP5EVVPtksR3w2EgxanpSsTsysRmgovKNn5sSPqaXGf611CKmRd2TArkntucSe144xGWXTx5VuqpCM6pkmb)

# Versions and configuration

# Additional context

[2020.03.06.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4428365/2020.03.06.zip)

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.E-472.
![изображение](https://user-images.githubusercontent.com/11132525/79004503-f032dd00-7b65-11ea-9ced-94af6ac1a65d.png)

Could you please update to latest experimental and check if this is still an issue?

**Comment by l29ah** [comment]
I can reproduce it just fine with the attached save file on 0.E-482-g40a256e688

**Comment by Voker57** [comment]
Can reproduce it too with this save and version.

**Comment by Night-Pryanik** [comment]
Hmm, strange.
Is your 3D-vision turned off?

**Comment by l29ah** [comment]
Dunno, i've never enabled it.

**Comment by Night-Pryanik** [comment]
Still can't confirm on 0.E-10390. Closing for now. If anyone is able to reproduce the issue, ping me.
