### ISSUE TITLE
Add a warning when user tries to pour water into an open container in inventory

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#39215]
# Is your feature request related to a problem? Please describe.
If you try to 'Pour into a container' water from a shallow water pond into a bucket you have in your inventory. The UI says 'You don't have a suitable container for carrying water'. It seems CDDA makes a difference between open and closed containers and that open containers need to be wielded or on the floor to be used for storing water. 

# Describe the solution you'd like
The UI should allow you to choose the bucket that you have in your inventory as a first step and on a second step the program could check if the container is open or not and  throw a "open containers need to be wielded or on the ground to be filled" message to the user.

# Describe alternatives you've considered
Implement only second step from above would not be consistent if the user has both open and closed containers in hisher inventory.

# Additional context
    OS: Linux
        OS Version: LSB Version: core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch; Distributor ID: Ubuntu; Description: Ubuntu 18.04.4 LTS; Release: 18.04; Codename: bionic;
    Game Version: 0.D-13513-g7294d30 [64-bit]
    Graphics Version: Tiles
    Game Language: English [en]
    Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Stats Through Skills [StatsThroughSkills]
    ]

**Comment by KorGgenT** [comment]
no i think i disagree with this: two extra button presses to get a warning you can't do it anyway?

**Comment by matt32106** [comment]
Fair enough so could the warning be made more understandable in that case? "you don't have a suitable container" is not true, you have a suitable container but you don't use it properly.

**Comment by KorGgenT** [comment]
a cup in your pocket isn't a suitable container because it can't hold anything, it'll spill.

**Comment by matt32106** [comment]
I know and I am not complaining about the program logic, what I think can be made better is the **feedback** to the user. 'You don't have a suitable container for carrying water' is false. You can use it but you have to wield it (and this part is not intuitive).

**Comment by robswor** [comment]
I'm looking into this - it seems like a good entry point to the project. I have a few ideas for this.
Do you think it'd be best to:

1. Just tell the user that they need to place open containers on the ground before filling them?
2. Ask the user if they want to place an open container on the ground to fill it, and then open their inventory?
3. Just place one of their open containers on the ground and fill it?

**Comment by anothersimulacrum** [comment]
Either 1 or 2 would be best, in my opinion.

**Comment by matt32106** [comment]
For me, you need to consider 2 cases:
a- the character only has open containers in his inventory and no closed ones
b- the character has both open and closed containers

Option 1 is fine with me (but they need to know that they can also  wield them). Addt'l question, will you display it in both cases a & b above? (I would say yes because if not, a new player would never understand why he can't use his bucket/pot)
I am not a fan of either option 2 or 3 but IMO 2 is better than 3.

**Comment by robswor** [comment]
It looks to me like the way the game handles container detection should automatically handle the case where the player has an item that can be filled, but I'll test for that just to be safe.

And yeah, I would display it for both options a and b, but I think a is probably the way to go.

**Comment by matt32106** [comment]
My point with this FR was just to stress that players who don't know the difference between open and closed containers never get a chance to discover it. Anything that makes them aware of the fact that they have to handle them differently is ok.
