### ISSUE TITLE
Reloading a clean worn canteen with a filthy canteen causes your worn canteen to become filthy

### ISSUE THREAD

**Issue by bcronrath** [CleverRaven/Cataclysm-DDA#39218]
# Describe the bug
Reloading a clean worn canteen with a filthy canteen causes your worn canteen to become filthy
# Steps To Reproduce
1.)  Fill worn cateen with clean water, drink some charges
2.)  Find zombie soldier wearing a canteen of clean water, but filthy since it was on zombie.
3.)  Stand over body and open your worn canteen and select "reload"
4.)  This causes your worn canteen to become filthy, and also produces a bug report if you have the Squeamish trait.
# Expected behavior
I would expect this to not make the canteen filthy, as the ammo you are using isn't the filthy item in this case (as oppose to something like reloading a needle with filthy thread)
# Versions and configuration
latest experimental build

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-10939.
