### ISSUE TITLE
Safe mode bug 

### ISSUE THREAD

**Issue by Bo0g1eMaN** [CleverRaven/Cataclysm-DDA#39227]
When safe mode is off I still get many alerts while trying to do things such as hauling for example, I will get stopped every move I make asking if I want to stop because I hear footsteps or see a hostile creature, the same goes for pulping among other things.

# Steps To Reproduce

1. Turn safe mode off
2. Try to haul or pulp near footsteps or where hostile creatures are in and out of view often

# Expected behavior

 A large amount of messages for every time a hostile creature comes in view or footsteps as well as any other sound such as a window breaking or something hitting a door. This is how it is in my game and I was told by someone in the discord that this was apparently a bug.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-4-gae54c8c [64-bit]
- Graphics Version: Tiles
- Game Language: English
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Bootleg Walkers [Bootleg_Walkers],
    No Freeze [no_freeze],
    DinoMod [DinoMod],
    Draco's Dog Mod [DracoDogMod],
    Draco's Pig Mod [DracoPigMod],
    Secronom [secronom],
    Cataclysm++ [Cata++],
    No Rail Stations [No_Rail_Stations],
    Graphical Overmap [Graphical_Overmap],
    Jury-Rigged Robots [jury_rigged_robots],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    Mutation Changes [Mutation_Changes],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]
I replicated the issue by just hauling the dead cow left and right after turning off safe mode.
[E.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4430000/E.zip)

**Comment by Dacendeth** [comment]
I feel like this isnt a bug, if you dont want to be bothered by noises while doing things just wear earplugs

**Comment by Axema** [comment]
You can also "I"gnore them :wink:

**Comment by Bo0g1eMaN** [comment]
> You can also "I"gnore them

Ignoring doesn't seem to do anything either, as soon as they go out of view then come back into view it's like they're a totally new creature that I never pressed I to ignore on.

**Comment by Axema** [comment]
I usually hold "shift" and "i" until the job is done :)

**Comment by natovan** [comment]
I think this is intended

**Comment by Bo0g1eMaN** [comment]
> I usually hold "shift" and "i" until the job is done :)

that's a bit tedious when I'm trying to haul stuff though.


> I think this is intended

I thought it was as well but kevingranade on the discord said that spotting new monsters should not be triggering when safe mode is off.

**Comment by natovan** [comment]
You, as a player, can't spot any monsters while crafting, but your character can. Player must be notified of enemies while he is out of control over character.
