### ISSUE TITLE
You can still craft bone armor

### ISSUE THREAD

**Issue by ABeligerentMoron** [CleverRaven/Cataclysm-DDA#39234]
# Describe the bug

There exist recipes for 3 sets of bone armor, a vehicle bone armor kit, a leather dog harness with bones and a boiled leather horse barding with bones.

# Expected behavior

Since bone armor was obsoleted, these are expected to be obsoleted too.

# Versions and configuration

# Additional context

The horse armor and the dog armor are described as having the bones for decorative purposes, but they give actual protection increases compared to their non-boned counterparts.

**Comment by ymber** [comment]
The animal armors should stay because the bones on them are cosmetic but bone vehicle armor needs to go.
