### ISSUE TITLE
Changing the fontdata.json doesn't work

### ISSUE THREAD

**Issue by sontallive** [CleverRaven/Cataclysm-DDA#39235]
My system is MacOS, I want to change the font in the gameplay, so I change the [fontdata.json], but what I modified didn't work. The displaying font keeps same.

So I delete the fonts in directory font, only keep my font. It can't launch anymore.

[the fontdata.json]

![image](https://user-images.githubusercontent.com/17899116/78418861-c3b52780-7672-11ea-8de0-bf8b42b7cb21.png)

[the font directory]

![image](https://user-images.githubusercontent.com/17899116/78418906-20184700-7673-11ea-9bab-fef3238a64c2.png)

**Comment by Qrox** [comment]
"data/fontdata.json" is masked by "config/fonts.json". You should change the latter instead. There should probably be an additional comment in "data/fontdata.json" to mention "config/fonts.json" though.

**Comment by sontallive** [comment]
> "data/fontdata.json" is masked by "config/fonts.json". You should change the latter instead. There should probably be an additional comment in "data/fontdata.json" to mention "config/fonts.json" though.

thanks, it works. The config directory is not in the program package in Macos platform, so I misunderstood the function of "data/fontdata.json"
