### ISSUE TITLE
Make it more intuitive to climb down from roofs

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#39245]
# Is your feature request related to a problem? Please describe.
When you move from a roof to the downspout spot where you climbed from, you basically jump from the rooftop instead of climbing down. To actually climb down you have to hit e which is far from intuitive.  

# Describe the solution you'd like
When you move to the top of a downspout (+ the other objects that enable to climb down) the UI should display the same menu as if you had hit e.

# Describe alternatives you've considered
None

# Additional context
-> long term ease of use features

**Comment by Aphegis** [comment]
Yes, a LOT of players dont know this is possible.
