### ISSUE TITLE
Impossible to open curtains of a moving vehicle

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#39242]
# Describe the bug

# Steps To Reproduce
Load the attached save and try to open the curtains on the windshield while the vehicle is still moving.

# Expected behavior

# Screenshots
![](https://tinystash.undef.im/il/XMMP7BpyGskwP38tW1bN4RYPpYeJTQTa6ML5vPxxxx1MTr7eHNtYZY84fXTju1jfJQGXifKnXXubFRHEuw6YG6u)

# Versions and configuration
- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Gentoo; Description: Gentoo Base System release 2.7; Release: 2.7; Codename: n/a; 
- Game Version: 0.E-80-g9e840421c8 [64-bit]
- Graphics Version: Curses
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

# Additional context

[2020.03.06.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4431385/2020.03.06.zip)

**Comment by kholat** [comment]
the workaround is to install door motors and open from the E D menu
