### ISSUE TITLE
Magiclysm- Greater Mana Regeneration isn't available for Manatouched tree's post-threshold

### ISSUE THREAD

**Issue by rioM1** [CleverRaven/Cataclysm-DDA#39257]
Game version: 0.E-238-g6393a6d

Operating system: Windows

Tiles or curses: Tiles

Mods active:
CRIT expansion
Aftershock
Magiclysm

### Expected behavior
The post-threshold mutation Greater Mana Regeneration is obtainable as part of Manatouched mutation tree as it is part of said category along with the Plant category.

### Actual behavior
Greater Mana Regeneration is only available for Plant mutation. 
Inspecting via debug menu's mutation feature shows that Plant is marked as the only required threshold mutation.

### Steps to reproduce the behavior
Attempting to add Greater Mana Reneration via debug menu returns the failure message displayed for lacking the required threshold mutation.

**Comment by KorGgenT** [comment]
oh, this is already fixed.
