### ISSUE TITLE
Duplicate mod ident warning broken in recent experimentals. Causing Segmentation Fault at launch.

### ISSUE THREAD

**Issue by Malkeus** [CleverRaven/Cataclysm-DDA#39258]
# Describe the bug
In 0.E stable, when mods with duplicate idents were present in any combination of cataclysm/mods and/or cataclysm/data/mods, cataclysm gave a warning on launch but was able to continue launching the game. Somewhere between 10478(0.E stable) and 10489(latest experimental as of this issue) this same duplicated mod ident condition causes a segmentation fault on launch without providing any information that would help to resolve the problem.

# Steps To Reproduce
Copy any mod in the mods folder and paste it back into the mods folder, producing 2 folders with different names and identical contents. Launch the game. In stable, you'll get a warning message. In 10489 you'll get a segmentation fault.

# Expected behavior
That the game would continue giving helpful warnings to aid in troubleshooting problems.

# Screenshots
Behavior in 0.E Stable:
https://i.imgur.com/xnhCwPU.png

Behavior in 0.E Experimental 10489:
https://i.imgur.com/tDbO62t.png

# Versions and configuration
0.E Stable 10478 - 
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
logs from above photo.
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4432483/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4432485/debug.log)

**Comment by ZhilkinSerg** [comment]
@Qrox looks like ui_adaptor issue
