### ISSUE TITLE
Enable zooming (z Z keys) while in "look around" mode (x key)

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#39253]
# Describe the solution you'd like
zoom shortcuts (zZ) should be usable while in look around mode (when you have pressed x and moved the cursor)

**Comment by Hirmuolio** [comment]
If you enable the experimental 3d field of view (options -> debug) you can use `<` and `>` to move the view up and down.

**Comment by matt32106** [comment]
When I say zoom, I mean make the view bigger or smaller, not move in the z plane.

**Comment by Pupsi-Mupsi** [comment]
Hi Matt,

it seems to me that zooming while looking around is already working. I pressed **x** to look around. looked around, then pressed **z and Z** to zoom in and out again.

Could you please try again?

---

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-291-gac0d129 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    No Fungal Monsters [No_Fungi],
    GP-Mods [gpmod],
    Magiclysm [magiclysm]
]

**Comment by matt32106** [comment]
I just did try again, it does not work for me. What is alternative map key mod?

- OS: Linux
    - OS Version: LSB Version: core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch; Distributor ID: Ubuntu; Description: Ubuntu 18.04.4 LTS; Release: 18.04; Codename: bionic; 
- Game Version: 0.E-238-g6393a6d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Pupsi-Mupsi** [comment]
I made a video maybe. Need to upload it. Give me a second.

Alternative Map Key [alt_map_key]
-> This is just a different overmap style. I'm just used to it.

Take a look (I'm using a different font for the overmap as well)

![grafik](https://user-images.githubusercontent.com/44737997/78463277-2b9f5880-76db-11ea-9125-f5ad8a34243a.png)

**Comment by Pupsi-Mupsi** [comment]
https://streamable.com/9xsboa

**Comment by Pupsi-Mupsi** [comment]
Maybe it's a linux issue.
Can someone confirm this?

**Comment by ZhilkinSerg** [comment]
It is working for me as well on Windows.

Press ? while in e(x)amine mode and make sure that you have zoom kebindings set.

**Comment by molkero** [comment]
Works for me on linux, vague flashbacks of having to set the keybinds.

**Comment by matt32106** [comment]
Yes, I confirm that the zoom keys were not bound. I assigned the keys and it works. Let me check if it is like this out of the box.

**Comment by matt32106** [comment]
Perfect, in 0.E it works out of the box! I close the request.

**Comment by Pupsi-Mupsi** [comment]
Glad to here that. Have fun and stay safe!
