### ISSUE TITLE
Horse Whisperer trait

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#39265]
# Describe the solution you'd like
This trait reduces the panic distance of horses mounts and when the horse flees he flees less far away.  

Just an idea before I forget it.

**Comment by kevingranade** [comment]
Yea I'll pass, decreasing horse panic is going to require extensive training, not some kind of "knack".

Basically horses are out as combatants for the foreseeable future, that is working as intended.
