### ISSUE TITLE
Monsters can see character despite lighting/structural conditions

### ISSUE THREAD

**Issue by Midaychi** [CleverRaven/Cataclysm-DDA#39279]
Using latest git I am unable to avoid zombies. Even with weak scent, light step, ninjitsu, night vision, starting at 00:00:00 in a dark mall loading area. (Literally, running/walking make 1 sound for this character)
Zombies seem to just auto-home in on them from even behind walls.

# Steps to reproduce 

1. Make a player in a world, 
2. Try to avoid zombies
3. Why are there so many exclamation marks?

# Expected behavior

Ability to sneak around/dodge zombies.

# Versions and configuration
Experimental zlevels: on
3d vision: On, 4 tile height.

06:37:27.481 :  GAME REPORT:
- OS: Windows 10 x64 home
    - OS Version: 10.0 1909
- Game Version: 0.E-327-g0f1e6aa [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

Here's a save maybe I'm just dumb?

[Willow Park.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4433802/Willow.Park.zip)

Load that save up and attempt to leave the mall without getting auto homed in on.

**Comment by natsirt721** [comment]
Weak scent doesn't mask your scent completely, you can see this using the debug menu option (info->toggle display local scents). I'm able to stand in the starting area for about 15 minutes before I got attacked, so they aren't "auto-homing" very well.

If you don't care too much about immersion, I suggest you spawn yourself a clarivoyance artifact and look just how many zeds are around you. I doubt a mouse could make it out of there without being noticed.

**Comment by Dacendeth** [comment]
I tested the save, nothing out of the ordinary seemed to happen with zombie detection.

**Comment by Midaychi** [comment]
![InstantGif_2020 04 06-18 04_01](https://user-images.githubusercontent.com/1968809/78619614-9a42fa00-7832-11ea-9f60-60f756cee939.gif)

**Comment by Dacendeth** [comment]
everything in that gif is normal, zombies have 4 night vision range and can smell you at about 6 even with weak scent, you get chased because of the scent trail you leave behind you as you walk. Also zombies make noises which cause other zombies to investigate the area and pick up on your scent trail as well.

**Comment by Midaychi** [comment]
Alright then. I haven't used cdda in a while so I was concerned that early game stealth is basically no longer viable, but if it was an intentional complete neutering then this isn't really a bug report.
