### ISSUE TITLE
Raging Judge capacity does not match .454 Speedloader capacity 

### ISSUE THREAD

**Issue by miradosamurai** [CleverRaven/Cataclysm-DDA#39280]
# Describe the bug

When loading a save or trying to create a new character I get the following warning:

` DEBUG    : warnings for type raging_judge:
speedloader 454_speedloader5 capacity (5) does not match gun capacity (6).

 FUNCTION : void Item_factory::check_definitions() const
 FILE     : src/item_factory.cpp
 LINE     : 1333
`

# Steps To Reproduce

1. Create new character

# Expected behavior

The character should load/be created without any warnings 

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-327-g0f1e6aa [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

I am fairly certain that this warning is caused by the Build 10491 Raging Judge audit, which changed the guns capacity to 6 without updating the guns speedloader to match.

**Comment by LaVeyanFiend** [comment]
I have a PR ready to give it a seperate speedloader,
