### ISSUE TITLE
Hovering in an electrically powered helicopter uses no fuel

### ISSUE THREAD

**Issue by anothersimulacrum** [CleverRaven/Cataclysm-DDA#39286]
# Describe the bug

Converting a helicopter to electrical power, flying up, and then waiting for some time costs no fuel other than the fuel used in ascending.

# Steps To Reproduce

Spawn in a two seat, remove the fuel tanks and engine, then install a storage battery and super electric motor.
Fill the storage battery, then fly up to some height and wait indefinitely. The helicopter will use no fuel from hovering.

Flying at speed 6 in the helicopter also appears to use no fuel.

Save with helicopter: 
[Otho.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/4434298/Otho.tar.gz)

# Expected behavior

Hovering and flying at low speeds in a helicopter still uses fuel.

# Versions and configuration
- OS: Linux
    - OS Version: Arch Linux, kernel version 5.5.13
- Game Version: 0.E-327-g0f1e6aa36d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/vehicle-question-spooilers-aftershock/24462/23

**Comment by actual-nh** [comment]
Still happening?
