### ISSUE TITLE
Some sentences are not translated

### ISSUE THREAD

**Issue by 939839415** [CleverRaven/Cataclysm-DDA#39290]
# Describe the bug
(in 0.E10478 veison)
Some sentences are not translated.
For example,when you pick up a weapon, the sidebar will have a blue message:
'you grit your teeth and prepare for a good fight'
The language i'm using is chinese(zn ch),this sentences as you see is in english
And another English sentence I found was the radio my charactor heard at the beginning of prison island
But i checked the https://www.transifex.com/cataclysm-dda-translators/cataclysm-dda/language/zh_CN/
which shows 100% translated
is there some thing wrong with the po file?

# Steps To Reproduce

1. change language into chinese
2.Make a player with a weapon
3.press w to handheld a weapon
4.look the sidebar

# Expected behavior

sidebar show this sentences by chinese

# Screenshots
https://s1.ax1x.com/2020/04/06/GrTP3t.jpg
# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E [64-bit]
- Graphics Version: Tiles
- Game Language: 系统语言 []
- Mods loaded: [
    浩劫余生 [dda],
    禁用NPC需求 [no_npc_food],
    替换小地图图标 [alt_map_key],
    发现玩家图标，retrodays版 [sees_player_retro]
]

# Additional context
By the way,Is it scientific to able store sulfuric acid in plastic bottles?I'm not sure

**Comment by Pupsi-Mupsi** [comment]
Just to helpt with this:

CDDA\data\json\martialarts.json

![grafik](https://user-images.githubusercontent.com/44737997/78505773-e54b0780-7775-11ea-9a2b-32a80a723985.png)

**Comment by Kenshkrix** [comment]
IIRC, this is the reason behind things like the name being { "str": "Brawling" } instead of "Brawling"

You might try reformatting it in this manner to see if it works as expected.

If so, somebody would need to go in and reformat all of these values.

**Comment by Qrox** [comment]
{ "str": "Brawling" } is only the new format for strings that have plural forms. The problem here is probably that the strings are not extracted by `extract_json_strings.py`

**Comment by Kenshkrix** [comment]
> { "str": "Brawling" } is only the new format for strings that have plural forms. The problem here is probably that the strings are not extracted by `extract_json_strings.py`
Ah, that makes more sense, it's been awhile since I looked into any of the things dealing with the file system.

**Comment by 939839415** [comment]
update:
some sentences in the computer from shelter is in english too,which had translated in 0.d version
