### ISSUE TITLE
View keybindigs in player info redraw issue

### ISSUE THREAD

**Issue by Pupsi-Mupsi** [CleverRaven/Cataclysm-DDA#39291]
# Describe the bug

Tiny bug: Opening keybindings-menu in player info does not redraw background.

# Steps To Reproduce

- Press @ to open player info.
- Press ? to open keybindings.
- Press ESC to leave keybindings-menu.

... et voila

# Screenshots

![grafik](https://user-images.githubusercontent.com/44737997/78505511-35c16580-7774-11ea-96ee-1fcde1fd4e2e.png)

**Comment by Qrox** [comment]
This will remain an issue for many UIs before they are migrated to the `ui_adaptor` system.

**Comment by Pupsi-Mupsi** [comment]
Thanks! I'm closing this issue.
