### ISSUE TITLE
Killer Drive and Psychopath traits only conflict in one way

### ISSUE THREAD

**Issue by FrogVoice** [CleverRaven/Cataclysm-DDA#39306]
# Describe the bug
It is possible to select both the "Killer Drive" and the "Psychopath" Traits although they are supposed to be conflicting.

# Steps To Reproduce

1. Create a new character using any of the point systems.
2. Go to the "Traits" tab of the character creation
3. select "Killer Drive" trait first.
4. select "Psychopath" trait second.
5. Start the game with both traits in effect.

# Expected behavior

Killer Driver and Psychopath are conflicting and should thus exclude on and another during character creation. As it is only selecting Psychopath first will disable Killer Drive not the other way around.

# Screenshots

![in character Creation](https://i.imgur.com/ELKrsuN.png)

![Ingame](https://i.imgur.com/4qG0yFp.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.E-335-g95973f8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills]
]

# Additional context

Not needed I think.

**Comment by Pupsi-Mupsi** [comment]
I'm not sure. Why should "Killer Drive" and "Psychopath" conflict?

![grafik](https://user-images.githubusercontent.com/44737997/78583520-3cfd7780-7837-11ea-8b23-1742264e91ee.png)

**Comment by FrogVoice** [comment]
> 
> 
> I'm not sure. Why should "Killer Drive" and "Psychopath" conflict?

Well I'm not sure why they should on a fundamental Level either. But fact of the matter is you are apparently not supposed to be able to take both, yet there is a way that doesn't seem intended.

**Comment by Pupsi-Mupsi** [comment]
Tested and changed.

You're right! If you want to test it before the change is merged, change this:

```
{
    "type": "trait_group",
    "id": "trait_group_PSYCHOPATH",
    "subtype": "distribution",
    "traits": [ { "trait": "PSYCHOPATH" }, { "trait": "KILLER" }, { "trait": "PACIFIST" } ]
  },
```
in **CDDA\data\json\npcs\starting_traits.json**

like this:

```
 {
    "type": "trait_group",
    "id": "trait_group_PSYCHOPATH",
    "subtype": "distribution",
    "traits": [ { "trait": "PSYCHOPATH" }, { "trait": "KILLER" }, { "trait": "PACIFIST" } ]
  },
```

**Comment by Pupsi-Mupsi** [comment]
And change

```
  {
    "type": "mutation",
    "id": "PSYCHOPATH",
    "name": { "str": "Psychopath" },
    "points": 2,
    "description": "You don't experience guilt like others do.  Even when you know your actions are wrong, you just don't care.",
    "starting_trait": true,
    "valid": false,
    "social_modifiers": { "intimidate": 5 },
    "cancels": [ "PACIFIST" ],
    "flags": [ "CANNIBAL" ]
  },
```

in **CDDA\data\json\mutations\mutations.json**

```
  {
    "type": "mutation",
    "id": "PSYCHOPATH",
    "name": { "str": "Psychopath" },
    "points": 2,
    "description": "You don't experience guilt like others do.  Even when you know your actions are wrong, you just don't care.",
    "starting_trait": true,
    "valid": false,
    "social_modifiers": { "intimidate": 5 },
    "cancels": [ "KILLER", "PACIFIST" ],
    "flags": [ "CANNIBAL" ]
  },
```

**Comment by Pupsi-Mupsi** [comment]
@FrogVoice 
BTW - Your bug-report was flawless. Well done!
