### ISSUE TITLE
Empty Artifact charges Nones

### ISSUE THREAD

**Issue by Kenshkrix** [CleverRaven/Cataclysm-DDA#39317]
# Describe the bug

Artifact charging for an item with an ammo type charges Nones if the item is empty.

# Steps To Reproduce

Use the Magiclysm mod.
Spawn in an enchanted tailor's kit item.
Unload it of all charges.
Wait for it to recharge, which should take approximately 1 in game hour.
Unload the new charge.

Alternatively:
Add the "artifact_data" { "charge_type": "ARTC_TIME" } property to any tool item with a specific ammo_type and perform the same test.

# Expected behavior

It should gain a charge of thread, which is the thread ammo_type's default ammo.
Currently the code simply increments the charge number, it should instead verify whether there are any charges, and if there are not it should get the ammo_type's default ammo and load that.

# Versions and configuration

Tested on 0.E stable with the Magiclysm mod enabled

**Comment by crazykid080** [comment]
Tested on build 10492, was able to reproduce

**Comment by RenechCDDA** [comment]
Fixed by #42824
