### ISSUE TITLE
Build 10497 - Butchering/Unloading Crash

### ISSUE THREAD

**Issue by AndrXi** [CleverRaven/Cataclysm-DDA#39327]
# Describe the bug

As of updating to build 10497 from build 10492, there's a number of issues that have showed up:
-Butchering anything leads to a crash.
-Unloading containers causes a "warning" and "may" crash the game.

**First Issue:**
After attempting to butcher a bunch of planks it lead to an immediate crash.

Image of reported crash.
![Bug Report 1 - build 10497](https://user-images.githubusercontent.com/44873249/78673882-ada9a000-78da-11ea-970c-111366491dab.png)

**Second Issue:**
After trying to unload the plastic bag of chocolate candies (that dropped from a zombie if it's important)
![Bug Report 3 - build 10497](https://user-images.githubusercontent.com/44873249/78674573-b8b10000-78db-11ea-9f8a-a70167d36c42.png)
leads to a red text warning or a crash
![Bug Report 4 - build 10497](https://user-images.githubusercontent.com/44873249/78674737-fb72d800-78db-11ea-883f-735cf013a1d0.png)
![Bug Report 6 - build 10497](https://user-images.githubusercontent.com/44873249/78675291-bef3ac00-78dc-11ea-8bca-e6e2a57c1802.png)
after continuing or skipping (if it doesn't crash), the game seems to have unloaded the container but instead of getting the empty container and its contents, I get the container with the contents and "unloaded" contents.
![Bug Report 5 - build 10497](https://user-images.githubusercontent.com/44873249/78674907-38d76580-78dc-11ea-912a-2d8c6914c701.png)

# Steps To Reproduce

First issue
1. Attempt to butcher anything.

Second issue
1. Have a container with food in it.
2. Attempt to unload (leads to red text showing up and sometimes a crash).

# Expected behavior

First issue
Be able to butcher.

Second issue
Not causing a red text warning popping up or crashing after.

# Versions and configuration

 - OS: Windows 10 Pro 1909
 - Game Version: 0.E-367-ge03227a
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: [  "dda",  "aftershock",  "crt_expansion",  "magiclysm",  "Mining_Mod",  "cbm_slots", "StatsThroughSkills",  "stats_through_kills",  "speedydex"]

# Additional context
Crash Report:   
- [crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4444739/crash.log)
- [debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4444743/debug.log)
- [save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4444798/save.zip) (I assume this is the right file?)

**Comment by KorGgenT** [comment]
thank you for the save! i'll look into the two issues separately. the crash bug has a higher priority.

**Comment by Drakasin** [comment]
Confirmed latest build on a new world and a new character - start a new game and just press "B", immediate crash.
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4446018/crash.log)

**Comment by KorGgenT** [comment]
just as an aside, when you have two different bugs like this, please open two separate issues.

**Comment by x7GoSu** [comment]
It seems opening the action menu is causing a crash as well. Should I open a separate bug report for this?

**Comment by KorGgenT** [comment]
opening the action menu might be related, due to the things that were actually causing the crash. i'm pretty sure the linked pr will fix that too.
