### ISSUE TITLE
Mod - Secronom Crash

### ISSUE THREAD

**Issue by AndrXi** [CleverRaven/Cataclysm-DDA#39328]
# Describe the bug
The mod seems to have stopped working as of builds 10492 to 10497 with a red text warning.
![Bug Report 10 - build 10497](https://user-images.githubusercontent.com/44873249/78678311-ae453500-78e0-11ea-9d23-2a4fb98524ac.png)

# Steps To Reproduce

1. Make a world with only Secronom.
2. Attempt to skip or continue.

# Versions and configuration

 - OS: Windows 10 Pro 1909
 - Game Version: 0.E-367-ge03227a
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded:  ["dda",  "secronom"]

**Comment by Kenan2000** [comment]
That's because the creator has not updated the mod yet on GitHub although he has fixed it, here's the link to download https://mega.nz/file/uMcmFIZI#sTR9M6lVb8qOMGJs3KlGMV-cifVRs3MX8eFufKimel0

**Comment by Fris0uman** [comment]
Secronom is a third party mod, bug reports related to it should to the mod repo.

**Comment by AndrXi** [comment]
I wasn't sure where to post this issue, but thank you for the replies.
I'll close it then.
