### ISSUE TITLE
Zombie destroys curtains before the door

### ISSUE THREAD

**Issue by Querens** [CleverRaven/Cataclysm-DDA#39324]
# Is your feature request related to a problem? Please describe.
I've been hiding from zombie hulk and he, for some reason, "feels" me inside my armored car and occassionaly hits the door. The door is 100% alright bur curtains are going down... 

# Describe the solution you'd like
Curtains are supposed to be inside the car and get hiting only after doors/ walls are destroyed

# Describe alternatives you've considered

# Additional context
No, the curtains were 100% intact. I was constantly monitoring the damage I get
http://a.tmp.ninja/3xwG2JsdKEUQ.png

**Comment by l29ah** [comment]
I wonder if there should be a vehicle part flag that says the component is "behind" the solid impassable part that is installed on the car so the part couldn't be damaged while the solid part is still present.
