### ISSUE TITLE
Safe Mode warnings after monster is already dead

### ISSUE THREAD

**Issue by gcaliber** [CleverRaven/Cataclysm-DDA#39330]
# Describe the bug

The safe mode warning still comes up for monsters that have already died to ranged weapon fire.

# Steps To Reproduce

1. Get a ranged weapon.
2. Begin aiming while monster is outside of safe mode range.
3. Have monster enter safe mode trigger range while aiming.
4. Fire weapon and kill monster.
5. Still have to add monster to safe mode ignore list to continue.

# Expected behavior

A monster that triggers a safe mode warning should automatically be ignored/removed if they are no longer alive.

# Versions and configuration

11:28:26.201 :  GAME REPORT:
- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 19.0.2; Codename: Kyria;
- Game Version: 0.E-383-gaae48f0740-dirty [64-bit]
- Graphics Version: Curses
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Fris0uman** [comment]
Probably related to #36820

**Comment by natsirt721** [comment]
I have seen this as well, exactly as described.

**Comment by GGgatherer** [comment]
> 
> 
> Probably related to #36820

Yeah, it's the same thing. It's like monsters' state for some purposes, including but not limited to safemode, is recalculated not in current turn but one turn later.

**Comment by Dacendeth** [comment]
You can also toggle safemode on and off to continue for what that's worth.
