### ISSUE TITLE
ammo belts are duplicated upon unloading

### ISSUE THREAD

**Issue by Talvan** [CleverRaven/Cataclysm-DDA#39334]
# Describe the bug
I tried to unload one of my .50 BMG ammo belts and I ended up with two fully-loaded belts after the game threw this:
 DEBUG    : Tried removing item from object which did not contain it

 FUNCTION : item visitable<T>::remove_item(item&) [with T = item]
 FILE     : src/visitable.cpp
 LINE     : 528

# Steps To Reproduce
1. Spawn .50 BMG ammo belt
2. Try to unload it
3. End up with TWO (2) fully-loaded .50 BMG ammo belts 

# Expected behavior
Disassembled ammo belt (belt linkages + actual rounds)

# Screenshots

# Versions and configuration
 - OS: Windows 10
 - Game Version: 0.E-367-ge03227a
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: Aftershock

# Additional context
It seems that I'm unable to mount guns onto turret mounts either this update.
EDIT: I guess this extends to all magazines because I get the same error for every other magazine I try to unload.

**Comment by DatMeg** [comment]
This applies to all magazines, not just the belts.
