### ISSUE TITLE
Armored vehicles can be shot through by enemies

### ISSUE THREAD

**Issue by temporelus** [CleverRaven/Cataclysm-DDA#39338]
# Describe the bug

Two bugs actually, maybe three:

#1  Riot control turrets (and every enemy that can shoot at you I assume) can and will shoot you through a heavy duty quarterpanel and a reinforced windshield without any problem (see video).

#2 Not shown in the video but in order to perform a few verifications I also tried to shoot at my npc standing inside the vehicle from the outside after having replaced the reinforced windshield with a heavy-duty board (board, not quarterpanel). When the game lets me shoot and doesn't freeze (see #3) I'm able to anger the npc and make him hostile (even though he somehow doesn't take damage?).

#3 The game freezes and then crashes when aiming and firing in an unseen area (see video), this happened while testing, the game just gets stuck in an aiming loop that lasts as long as you don't click on the screen, when you click on the screen it crashes.

# Steps To Reproduce

1. Use debug menu to spawn riot control platform in front of an armored vehicle of choice
2. Stand in line of sight of the turret

# Expected behavior

The turret will shoot at the player (or anything really) through a layer of heavy duty quarterpannel and a layer of reinforced windshield.

# Screenshots
https://www.youtube.com/watch?v=P3i76RvJSGg

# Versions and configuration

OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.E [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Alternative Map Key [alt_map_key],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]

# Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4446485/debug.log)

-I don't have a crash file and my save file is too large for github even when compressed on ultra with 7zip :(

**Comment by Dacendeth** [comment]
1. Riot turrets on latest experimental still pierce windows where other turrets don't so this is most likely a problem.
2. Don't think this is an issue, if someone shot at where I was even if they missed i'd be upset.
3. Don't think this one happens on latest experimental, at least I couldn't trigger another instance of this trying to shoot through a curtained window at something.

**Comment by temporelus** [comment]
I've had another occurrence of bots in labs shooting through closed glass doors in the fabricator room when they see me.
This was all on 0.E stable.

**Comment by temporelus** [comment]
![Desktop Screenshot 2020 04 10 - 13 46 58 13](https://user-images.githubusercontent.com/63308196/78988681-f0b18080-7b31-11ea-94fa-863bef3f4e8b.png)
I happened to stumble upon another roadblock and a riot control platform was able to shoot me through the width of a military cargo truck...

**Comment by Dacendeth** [comment]
Oh yeah glass doors almost anything shoots through those for whatever reason.

**Comment by bkinnear** [comment]
Acid sniper zombies will also shoot through reinforced windshields
