### ISSUE TITLE
Cannot choose between ingredients of the same name for nutrient inheritance

### ISSUE THREAD

**Issue by 182crazyking** [CleverRaven/Cataclysm-DDA#39348]
# Describe the bug

There is no (player-facing) way to choose which ingredients a recipe will use if those ingredients are considered the same but different nutrients from prior nutrient inheritance. This leads to situations where the player may have toxin-containing and safe ingredients with the same name and inadvertently crafts toxic food.

# Steps To Reproduce

1. Spawn a chunk of meat, a chunk of human meat, some bread, and a charcoal smoker.
2. Create smoked meat, then smoked mutant meat.
3. Create a meat sandwich; you aren't asked which one to use.

# Expected behavior

A dialog window should ask which ingredient(s) the player would like to use, or which version (nutrient-based) of the final product they'd like.

# Screenshots
[image](https://user-images.githubusercontent.com/60903078/78731237-232e6400-790d-11ea-8427-211fb5bc3133.png)
This screenshot shows the existing dialog given with 4 pieces of healthy smoked meat, 1 piece of smoked mutant meat, and other valid ingredients. Note that I only have one "smoked meat" option, and there are five to choose from.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by int-ua** [comment]
I usually workaround it by putting required ingredient into character storage or having an inaccessible storage location for unneeded ingredients.
