### ISSUE TITLE
Auto-reload the tool your using in an activity

### ISSUE THREAD

**Issue by Fris0uman** [CleverRaven/Cataclysm-DDA#39344]
# Is your feature request related to a problem? Please describe.
Basically the same thing as #30415. It would be very convenient if during a long sewing/repairing/crafting session reloading on battery or thread would happen automatically pulling the appropriate material from an auto-reload zone. Would probably go along well with the tailoring rework and the potential lenghtening of those activities.

# Describe the solution you'd like
Designate an auto-reload zone
Put your thread in it
Starting trying to repair untill sucess or level up
If the next tick will deplete your charges the game check the nearby zone for thread
If there is thread it reload automaticaly and resume sewing
If there is not or it is empty you consume your last thread and the activity stops

# Describe alternatives you've considered
Doing it by default by searching through all tiles in the usual crafting range

# Additional context
This is somewhat related to the other issues from Erk about automation (#28283 #30414)

**Comment by placeybordeaux** [comment]
I'd personally prefer to not add another zone designation, how do y'all feel about making this a safe mode option?

**Comment by Night-Pryanik** [comment]
No discussion in more than a year, closing.
