### ISSUE TITLE
ups_based_armor  use action activate all available use_action on a TOOL_ARMOR type armor.

### ISSUE THREAD

**Issue by rioM1** [CleverRaven/Cataclysm-DDA#39343]
# Describe the bug

A TOOL_ARMOR type armor with ups_based_armor use_action + at least one additional use_action (such as WEATHER_TOOL or TELEPORT) will activate all of its use_action every turn the item is active (via the ups_based_armor activate).

# Steps To Reproduce

Create an armor in TOOL_ARMOR type with use_action set up as described below
"use_action": [       
        "TELEPORT",
        {
            "type": "ups_based_armor",
            "activate_msg": "Your optical cloak flickers as it becomes transparent.",
            "deactive_msg": "Your optical cloak flickers for a moment as it becomes opaque."
        }
    ],
    "flags": [ 
        "ACTIVE_CLOAKING"
    ] 

Teleport will trigger every turn the armor is activated via the ups_based_armor option "Activate/Deactivate".
Note: ACTIVE_CLOAKING flag works in conjunction with ups_based_armor to produce the cloak effect.

# Expected behavior
While activated via the ups_based_armor option "Activate/Deactivate", the armor should not automatically perform other unrelated use_action.

# Screenshots

Not applicable

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-367-ge03227a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    C.R.I.T Expansion Mod [crt_expansion],
    Custom player mod [CUSTOM_PLAYER_MOD],   
    Mythical Martial Arts [MMA],
    DinoMod [DinoMod],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Graphical Overmap [Graphical_Overmap]

# Workaround
Change the item's type to ARMOR.
Although document indicates that activatable armor should be placed in TOOL_ARMOR instead.

**Comment by Night-Pryanik** [comment]
> Change the item's type to ARMOR.

Use that if it works as you need.
