### ISSUE TITLE
Crash upon butchering

### ISSUE THREAD

**Issue by alanarae** [CleverRaven/Cataclysm-DDA#39346]
Game version: 10498

Operating system: Windows

Tiles or curses: 

Mods active: 

Any time I try to butcher by pressing shift B, the game crashes. It has happened when I try to butcher rags to make thread. 

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4447242/crash.log)

**Comment by AbsurdRage** [comment]
I'm having the same problem....trying to make rags as well, haha.
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4447304/crash.log)

**Comment by micage2** [comment]
Same here.
Active mods: Aftershock, StatsThroughSkills
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4447339/crash.log)

**Comment by KorGgenT** [comment]
Fixed with #39335
