### ISSUE TITLE
Unloading contained food crashes game

### ISSUE THREAD

**Issue by Miner239** [CleverRaven/Cataclysm-DDA#39357]
# Describe the bug
Unloading food from its container crashes the game

# Steps To Reproduce
1. Unload the food item

# Expected behavior
Food put into inventory, fluid gets a handling dialog box. It just didn't crash before

# Versions and configuration
Version 0.E-416-g3e8ab06 (tiles) (build 10500)
OS: Windows 10
Language: English
Mods: dda

debug.log included in zip

# Additional context

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4448938/save.zip)

**Comment by buildfailedforallplatforms** [comment]
Also happens when unloading detergent from carboard box

**Comment by ampersand55** [comment]
See https://github.com/CleverRaven/Cataclysm-DDA/issues/39356, which is probably fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/39354
