### ISSUE TITLE
The Infinite Spilling Gallon Jug

### ISSUE THREAD

**Issue by ReynTheLord** [CleverRaven/Cataclysm-DDA#39353]
# Describe the bug

Essentially, I've been attempting to pour out a gallon jug of, first bleach, now almond milk, onto the ground to empty it for use in crafting. Issue is, it puts the dirty substance on the ground, but the container's still just as full as it was before. Got an error message which isnt popping up anymore, something to do with "The item isnt in that container". 

Essentially, I can spill it infinitely, but I can't empty it.

# Steps To Reproduce

# Screenshots

# Versions and configuration

# Additional context
It appears to be allegedly fixed, but I'm not sure. I want the gallon jug for a funnel!

**Comment by ampersand55** [comment]
Also crashes the game occasionally when unloading containers, see https://github.com/CleverRaven/Cataclysm-DDA/issues/39356 and https://github.com/CleverRaven/Cataclysm-DDA/issues/39357

**Comment by AndrXi** [comment]
This is the same as #39327's second issue I posted from build 10497.
It's also present in build 10501.

**Comment by caitisgreat** [comment]
This issue occurred for me as well.  I caught this debug statement.

 DEBUG    : Tried removing item from object which did not contain it

 FUNCTION : item visitable<T>::remove_item(item&) [with T = Character]
 FILE     : src/visitable.cpp
 LINE     : 528

**Comment by bcronrath** [comment]
I suspect this is a bug with the "Unload" functionality altogether, as it appears you also can't remove weapon mods
