### ISSUE TITLE
crash on butcher

### ISSUE THREAD

**Issue by Tenasa-vini** [CleverRaven/Cataclysm-DDA#39359]
was in a cabin about to cut some sheets and game crashed (this can be repeated)

 - OS: win10
 - Game Version: 10497
 - Graphics version: Undead people

mod list-  "dda",
  "no_npc_food",
  "aftershock",
  "ArmUpSurvEx",
  "DracoDogMod",
  "PK_REBALANCE",
  "secronom",
  "alt_map_key",
  "Cata++",
  "ks_variety_pack",
  "more_survivor_stuff",
  "No_Rail_Stations",
  "Graphical_Overmap",
  "speedydex",
  "Mutation_Changes"

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4449482/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4449484/debug.log)
[Muenster.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4449490/Muenster.zip)

**Comment by LaVeyanFiend** [comment]
This was already fixed in 10499.
