### ISSUE TITLE
Loading a save opens all canned items

### ISSUE THREAD

**Issue by Killer-of-Lawyers** [CleverRaven/Cataclysm-DDA#39355]
# Describe the bug
Loading a world in the latest experimental (Build 10499) causes all canned goods to become opened.  

# Steps To Reproduce
Start a fresh world, find canned goods, then save and reload.  The goods will now be opened and start spoiling.

# Expected behavior
Loading a save will keep all canned goods safely unopened.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-414-ge0bf561 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by ZhilkinSerg** [comment]
Nice QoL

**Comment by AndrXi** [comment]
I can confirm as of build 10501, my sealed glass jars were also all open.

**Comment by Apuru** [comment]
I can confirm as well, ported my save to the latest experimental and all my canned foods, sealed glass jars were opened and spoiled. Spilling some food such as dog food or canned ravioli causes the game to crash too. Not quite sure what to do with these spoiled canned foods.

**Comment by caitisgreat** [comment]
Also confirming for 10501

**Comment by cadend** [comment]
This is definitely happening on when loading a save, not when serializing the world. 

Spawned a couple cans of chicken, left one on the ground and one in the character's inventory, then saved.

Checking the JSON shows `can_medium` in both the `.sav` and `.map` files prior to loading, then `can_medium_unsealed` after loading the save and saving a second time.

**Comment by KorGgenT** [comment]
thanks @cadend that really helped me narrow it down quickly!
