### ISSUE TITLE
Gibberish around some text in curses build

### ISSUE THREAD

**Issue by Jookia** [CleverRaven/Cataclysm-DDA#39361]
# Describe the bug

On master in the curses build some text is appended or prepended with junk like '-BM-(', '-b~T~P', '~b-T-~T', 'M-BM-'. Line wraps seem to include garbage too include ampersands. These additional characters cause text to overflow to the next line in some windows in the game like the inventory.

# Steps To Reproduce

Start the game and go to the 'new game' menu. It should have some garbage if your terminal is narrow enough for it to line wrap. Otherwise enter the game itself and look at the UI.

# Expected behavior

I expect the text to look something like the graphics version where there isn't this extra text that looks like escape codes.

# Screenshots

![2020-04-08-202401_1280x1024_scrot](https://user-images.githubusercontent.com/185275/78774896-dedeaa80-7984-11ea-8021-00552775542f.png)

# Versions and configuration

-----------------------------------------
20:40:19.038 : Starting log.
20:40:19.039 INFO : Cataclysm DDA version 0.D-13905-g7afe3c1b8a
20:40:21.908 WARNING : opendir [/home/jookia/.cataclysm-dda/mods/] failed with "No such file or directory".
20:41:04.558 WARNING : opendir [/home/jookia/.cataclysm-dda/save/Lenexa/mods] failed with "No such file or directory".
20:42:12.707 :  GAME REPORT:
- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 10 (buster); Release: 10; Codename: buster;
- Game Version: 0.D-13905-g7afe3c1b8a [32-bit]
- Graphics Version: Curses
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    DinoMod [DinoMod],
    Graphical Overmap [Graphical_Overmap],
    Stats Through Skills [StatsThroughSkills]
]

20:42:24.411 : Log shutdown.
-----------------------------------------

# Additional context

Compiler is arm-linux-gnueabihf-gcc-8, extra build flags are -fsigned-char

# Describe the bug

On master in the curses build some text is appended or prepended with junk like '-BM-(', '-b~T~P', '~b-T-~T', 'M-BM-'. Line wraps seem to include garbage too include ampersands. These additional characters cause text to overflow to the next line in some windows in the game like the inventory.

# Steps To Reproduce

Start the game and go to the 'new game' menu. It should have some garbage if your terminal is narrow enough for it to line wrap. Otherwise enter the game itself and look at the UI.

# Expected behavior

I expect the text to look something like the graphics version where there isn't this extra text that looks like escape codes.

# Screenshots

![2020-04-08-202401_1280x1024_scrot](https://user-images.githubusercontent.com/185275/78774896-dedeaa80-7984-11ea-8021-00552775542f.png)

# Versions and configuration

-----------------------------------------
20:40:19.038 : Starting log.
20:40:19.039 INFO : Cataclysm DDA version 0.D-13905-g7afe3c1b8a
20:40:21.908 WARNING : opendir [/home/jookia/.cataclysm-dda/mods/] failed with "No such file or directory".
20:41:04.558 WARNING : opendir [/home/jookia/.cataclysm-dda/save/Lenexa/mods] failed with "No such file or directory".
20:42:12.707 :  GAME REPORT:
- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 10 (buster); Release: 10; Codename: buster;
- Game Version: 0.D-13905-g7afe3c1b8a [32-bit]
- Graphics Version: Curses
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    DinoMod [DinoMod],
    Graphical Overmap [Graphical_Overmap],
    Stats Through Skills [StatsThroughSkills]
]

20:42:24.411 : Log shutdown.
-----------------------------------------

# Additional context

Compiler is arm-linux-gnueabihf-gcc-8, built with '-fsigned-char' to avoid the build breaking.

**Comment by ZhilkinSerg** [comment]
Please try compiling with LOCALIZE=1 and see if it will display Unicode characters properly.

**Comment by jbytheway** [comment]
It looks like might be related to the terminal escapes used to change colour.  What terminal are you running in?  Do other things which use colour work fine?  What about other curses apps?

**Comment by ZhilkinSerg** [comment]
> 
> 
> It looks like might be related to the terminal escapes used to change colour. What terminal are you running in? Do other things which use colour work fine? What about other curses apps?

I am pretty sure it is because of the following in the Makefile:

```Makefile
  ifeq ($(LOCALIZE),1)
    NCURSES_PREFIX = ncursesw
  else
    NCURSES_PREFIX = ncurses
  endif
```

**Comment by Jookia** [comment]
I'm use xfce4-terminal which reports as xterm-256color. Pretty standard
stuff, and I expect escapes would begin with something like ^[[ for this
terminal, so I'm not sure if that's the case. I'll try under tmux and
screen when I recompile.

I'm currently compiling 0.D to check this isn't a regression (it takes a
while), but I'll definitely see what's up with ncursesw- I'm using CMake
to compile so there could be a problem there.

I really want to emphasise that I'm compiling with -fsigned-char in
CMake

**Comment by anothersimulacrum** [comment]
We had someone yesterday who had this problem when compiling with CMake, but not with Make on the discord.

**Comment by Jookia** [comment]
I haven't gotten CMake to link with ncursesw. This may be linked to
#39053

**Comment by Jookia** [comment]
I worked around it and can confirm that's the bug. Closing and moving discussion there.
