### ISSUE TITLE
Butchery no longer remove the corpse

### ISSUE THREAD

**Issue by bcronrath** [CleverRaven/Cataclysm-DDA#39371]
Describe the bug
Normally when you butcher a corpse the corpse is removed, but in the latest builds this no longer occurs

To Reproduce
-Kill something
-Butcher it, any of the butcher options will do

Expected behavior
Corpse should be removed

Desktop (please complete the following information):
Windows 10

Additional context
Occurs on latest build, suspect it is related to the Butchery fix

**Comment by KorGgenT** [comment]
![image](https://user-images.githubusercontent.com/30208401/78815278-0d1cb400-799e-11ea-9daf-fcb29b0b8ec9.png)
i did a quick butchery on a deer, on current `master`. could not reproduce.

**Comment by Pupsi-Mupsi** [comment]
Did a quick butcher on a zombie. Could not reproduce either.

![grafik](https://user-images.githubusercontent.com/44737997/78823221-a074da00-79dc-11ea-9407-60ba34c360a7.png)

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-419-gbe7ab20 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    No Fungal Monsters [No_Fungi],
    GP-Mods [gpmod]
]

**Comment by bcronrath** [comment]
Hmm weird, I'm able to reproduce on a new game.  I have a save game I just created new to test, killed this rat and when I do quick butchery it still leaves the corpse, if I do it around 3 or 4 times it will finally remove the corpse.  Would it be worth uploading?  If so what all would you need me to upload, the whole map under the "save" folder?

**Comment by DatMeg** [comment]
It does not seem to be totally consistent. Dissection of a Bio-Operator may (or may not) return the BioOp's corpse, along with any of the CBMs I may harvest out of it, essentially giving me double, triple, or even more attempts at that loot pool.
![image](https://user-images.githubusercontent.com/17204395/78824256-10b73780-79ac-11ea-9589-b5d14a6fa9a0.png)

**Comment by Clanf** [comment]
i have same bug and i think it tied to "The Infinite Spilling Gallon Jug" somehow
it appear at same time as unloading and butchering crash was "fixed"
currently (build 10501) i can butcher corpse (zombie/human, didn't try animals) 3-7 times before it disappear

**Comment by Tyralocus** [comment]
I can reproduce this bug.

![bee_in_bee_in_bee](https://user-images.githubusercontent.com/9115556/78824682-0c584200-79df-11ea-9ab4-9d86839579f7.PNG)

There appear to be 4-6 bees hiding within each bee. Matroska bees?

**Comment by anothersimulacrum** [comment]
I can reproduce this with a full butcher, but not a quick butchery.
