### ISSUE TITLE
lake shore map generation bug

### ISSUE THREAD

**Issue by akirashirosawa** [CleverRaven/Cataclysm-DDA#39382]
# Describe the bug
Map generation problem lake shore with a water square. See screenshots.

# Steps To Reproduce
Generate some maps with lake probably...

# Expected behavior
 Lake shore generating without a water square. 

# Screenshots
Lake shore with a water square.
<img width="1280" alt="1" src="https://user-images.githubusercontent.com/38557723/78839923-29523c80-7a02-11ea-8b9c-afcf891283c8.png">
River near by.
<img width="1280" alt="2" src="https://user-images.githubusercontent.com/38557723/78839950-3d963980-7a02-11ea-9a0b-ecd5a33ad423.png">
Map.
<img width="1029" alt="3" src="https://user-images.githubusercontent.com/38557723/78840312-13914700-7a03-11ea-9426-fddd88e3d5a3.png">

# Versions and configuration
- OS: MacOs
    - OS Version: Name: Mac OS X; Version: 10.15.4; Build: 19E266; 
- Game Version: 0.D commit 5712a9a743bd17433032f98a2a7f66368fca4f9e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations]
]

# Additional context
I do not know why the bug is in this place. Maybe because the river is nearby. There are no problems with the lake shore in other places on this map.

UPD
[Savefile.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4453142/Savefile.zip)

**Comment by ralreegorganon** [comment]
Please attach the save.

**Comment by akirashirosawa** [comment]
Created a new world, started a new game. There is a huge mess in the corner of the river.

<img width="1280" alt="1" src="https://user-images.githubusercontent.com/38557723/82138666-df434e80-982a-11ea-82e3-593906b3153d.png">

New world save file: [newSave.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4639837/newSave.zip)

**Comment by chaisawlajatang** [comment]
I can confirm this. 0.E-2230-g6ac712d without mods. Possibly related to https://github.com/CleverRaven/Cataclysm-DDA/pull/39318
![lake1](https://user-images.githubusercontent.com/40278862/82285106-4c79ef80-99a3-11ea-82e9-46c979c12101.png)
![lake2](https://user-images.githubusercontent.com/40278862/82285112-556ac100-99a3-11ea-9b48-5ebc96dfee5a.png)

**Comment by anothersimulacrum** [comment]
```
a9778c1250cee25c2e5a6ca2615db225d03a0984 is the first bad commit
commit a9778c1250cee25c2e5a6ca2615db225d03a0984
Author: ZhilkinSerg <ZhilkinSerg@users.noreply.github.com>
Date:   Sun May 3 19:56:59 2020 +0300

    Declutter waterbody terrains

 .../overmap_terrain/overmap_terrain_waterbody.json | 42 +++++++++++-----------
 1 file changed, 20 insertions(+), 22 deletions(-)
```

**Comment by akirashirosawa** [comment]
I have not seen any more obvious problems with the shores, so I will close this issue.
