### ISSUE TITLE
Crafting concentrated acid from light battery causes crash

### ISSUE THREAD

**Issue by bcronrath** [CleverRaven/Cataclysm-DDA#39392]
Crafting concentrated acid while using light battery as a component appears to crash game in latest build, haven't tested other recent builds.

# Steps To Reproduce

Can create new character with necessary crafting to reproduce the error.  

crash log:

The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 0.E-426-g2dd9110
TYPE: St11logic_error
MESSAGE: basic_string::_M_construct null not valid
STACK TRACE:

  #0
    (dbghelp: @0x62d0d6[cataclysm-tiles.exe+0x22d0d6]), 
    (libbacktrace: Z21debug_write_backtraceRSo+0x56@0x62d0d6),
    (libbacktrace: 0x62d0d6    [unknown src]:0    [unknown func]),
  #1
    (dbghelp: @0x611aef[cataclysm-tiles.exe+0x211aef]), 
    (libbacktrace: log_crash+0x4af@0x611aef),
    (libbacktrace: 0x611aef    [unknown src]:0    [unknown func]),
  #2
    (dbghelp: @0x612749[cataclysm-tiles.exe+0x212749]), 
    (libbacktrace: ZL23crash_terminate_handlerv+0xa9@0x612749),
    (libbacktrace: 0x612749    [unknown src]:0    [unknown func]),
  #3
    (dbghelp: IMG_LoadWEBP_RW+0x1ab5d8@0x13136f8[cataclysm-tiles.exe+0xf136f8]), 
    (libbacktrace: ZN10__cxxabiv111__terminateEPFvvE+0x8@0x13136f8),
    (libbacktrace: 0x13136f8    [unknown src]:0    [unknown func]),
  #4
    (dbghelp: IMG_LoadWEBP_RW+0x5f7493@0x175f5b3[cataclysm-tiles.exe+0x135f5b3]), 
    (libbacktrace: ZSt9terminatev+0x13@0x175f5b3),
    (libbacktrace: 0x175f5b3    [unknown src]:0    [unknown func]),
  #5
    (dbghelp: IMG_LoadWEBP_RW+0x5fe70e@0x176682e[cataclysm-tiles.exe+0x136682e]), 
    (libbacktrace: _cxa_throw+0x6e@0x176682e),
    (libbacktrace: 0x176682e    [unknown src]:0    [unknown func]),
  #6
    (dbghelp: IMG_LoadWEBP_RW+0x5e8ff7@0x1751117[cataclysm-tiles.exe+0x1351117]), 
    (libbacktrace: ZSt19__throw_logic_errorPKc+0x37@0x1751117),
    (libbacktrace: 0x1751117    [unknown src]:0    [unknown func]),
  #7
    (dbghelp: @0x813393[cataclysm-tiles.exe+0x413393]), 
    (libbacktrace: ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12_M_constructIPKcEEvT_S8_St20forward_iterator_tag.isra.1534+0x23@0x813393),
    (libbacktrace: 0x813393    [unknown src]:0    [unknown func]),
  #8
    (dbghelp: @0x81713d[cataclysm-tiles.exe+0x41713d]), 
    (libbacktrace: ZNK4item6typeIdB5cxx11Ev+0x2d@0x81713d),
    (libbacktrace: 0x81713d    [unknown src]:0    [unknown func]),
  #9
    (dbghelp: @0x83f152[cataclysm-tiles.exe+0x43f152]), 
    (libbacktrace: ZN4item19use_amount_internalERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERiRNS0_4listIS_SaIS_EEERKSt8functionIFbRKS_EE+0x32@0x83f152),
    (libbacktrace: 0x83f152    [unknown src]:0    [unknown func]),
  #10
    (dbghelp: @0x83f3b2[cataclysm-tiles.exe+0x43f3b2]), 
    (libbacktrace: ZZN4item10use_amountERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERiRNS0_4listIS_SaIS_EEERKSt8functionIFbRKS_EEENKUlPS_E_clESK_+0x32@0x83f3b2),
    (libbacktrace: 0x83f3b2    [unknown src]:0    [unknown func]),
  #11
    (dbghelp: IMG_LoadWEBP_RW+0x44b221@0x15b3341[cataclysm-tiles.exe+0x11b3341]), 
    (libbacktrace: ZNSt17_Function_handlerIF13VisitResponseP4itemS2_EZN9visitableIS1_E11visit_itemsERKSt8functionIFS0_S2_EEEUlS2_S2_E_E9_M_invokeERKSt9_Any_dataOS2_SG_+0x21@0x15b3341),
    (libbacktrace: 0x15b3341    [unknown src]:0    [unknown func]),
  #12
    (dbghelp: @0xf9878e[cataclysm-tiles.exe+0xb9878e]), 
    (libbacktrace: ZN13item_contents14visit_contentsERKSt8functionIF13VisitResponseP4itemS3_EES3_+0x4e@0xf9878e),
    (libbacktrace: 0xf9878e    [unknown src]:0    [unknown func]),
  #13
    (dbghelp: IMG_LoadWEBP_RW+0x339ccc@0x14a1dec[cataclysm-tiles.exe+0x10a1dec]), 
    (libbacktrace: ZN9visitableI4itemE11visit_itemsERKSt8functionIF13VisitResponsePS0_EE+0x9c@0x14a1dec),
    (libbacktrace: 0x14a1dec    [unknown src]:0    [unknown func]),
  #14
    (dbghelp: @0x83f2e8[cataclysm-tiles.exe+0x43f2e8]), 
    (libbacktrace: ZN4item10use_amountERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERiRNS0_4listIS_SaIS_EEERKSt8functionIFbRKS_EE+0x78@0x83f2e8),
    (libbacktrace: 0x83f2e8    [unknown src]:0    [unknown func]),
  #15
    (dbghelp: @0x9cc0ee[cataclysm-tiles.exe+0x5cc0ee]), 
    (libbacktrace: ZN3map17use_amount_squareERK8tripointRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERiRKSt8functionIFbRK4itemEE+0x1ee@0x9cc0ee),
    (libbacktrace: 0x9cc0ee    [unknown src]:0    [unknown func]),
  #16
    (dbghelp: @0x9cc61d[cataclysm-tiles.exe+0x5cc61d]), 
    (libbacktrace: ZN3map10use_amountERK8tripointiRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERiRKSt8functionIFbRK4itemEE+0x27d@0x9cc61d),
    (libbacktrace: 0x9cc61d    [unknown src]:0    [unknown func]),
  #17
    (dbghelp: @0x5ef2a4[cataclysm-tiles.exe+0x1ef2a4]), 
    (libbacktrace: ZN6player13consume_itemsB5cxx11ER3mapRK14comp_selectionI9item_compEiRKSt8functionIFbRK4itemEERK8tripointi+0x4a4@0x5ef2a4),
    (libbacktrace: 0x5ef2a4    [unknown src]:0    [unknown func]),
  #18
    (dbghelp: @0x5ef53d[cataclysm-tiles.exe+0x1ef53d]), 
    (libbacktrace: ZN6player13consume_itemsB5cxx11ERK14comp_selectionI9item_compEiRKSt8functionIFbRK4itemEE+0x5d@0x5ef53d),
    (libbacktrace: 0x5ef53d    [unknown src]:0    [unknown func]),
  #19
    (dbghelp: @0x5e9c7a[cataclysm-tiles.exe+0x1e9c7a]), 
    (libbacktrace: ZN13craft_command24create_in_progress_craftEv+0xbea@0x5e9c7a),
    (libbacktrace: 0x5e9c7a    [unknown src]:0    [unknown func]),
  #20
    (dbghelp: @0x5f84a3[cataclysm-tiles.exe+0x1f84a3]), 
    (libbacktrace: ZN6player11start_craftER13craft_commandRK8tripoint+0x53@0x5f84a3),
    (libbacktrace: 0x5f84a3    [unknown src]:0    [unknown func]),
  #21
    (dbghelp: @0x5ead36[cataclysm-tiles.exe+0x1ead36]), 
    (libbacktrace: ZN13craft_command7executeERK8tripoint+0x446@0x5ead36),
    (libbacktrace: 0x5ead36    [unknown src]:0    [unknown func]),
  #22
    (dbghelp: @0x5f01cc[cataclysm-tiles.exe+0x1f01cc]), 
    (libbacktrace: ZN6player5craftERK8tripoint+0x5c@0x5f01cc),
    (libbacktrace: 0x5f01cc    [unknown src]:0    [unknown func]),
  #23
    (dbghelp: @0x7cbb29[cataclysm-tiles.exe+0x3cbb29]), 
    (libbacktrace: ZN8iexamine18workbench_internalER6playerRK8tripointRKN4cata8optionalI15vpart_referenceEE+0x979@0x7cbb29),
    (libbacktrace: 0x7cbb29    [unknown src]:0    [unknown func]),
  #24
    (dbghelp: @0x7cc0b8[cataclysm-tiles.exe+0x3cc0b8]), 
    (libbacktrace: ZN8iexamine9workbenchER6playerRK8tripoint+0x18@0x7cc0b8),
    (libbacktrace: 0x7cc0b8    [unknown src]:0    [unknown func]),
  #25
    (dbghelp: @0x7422d5[cataclysm-tiles.exe+0x3422d5]), 
    (libbacktrace: ZN4game7examineERK8tripoint+0x725@0x7422d5),
    (libbacktrace: 0x7422d5    [unknown src]:0    [unknown func]),
  #26
    (dbghelp: @0x7427d5[cataclysm-tiles.exe+0x3427d5]), 
    (libbacktrace: ZN4game7examineEv+0x145@0x7427d5),
    (libbacktrace: 0x7427d5    [unknown src]:0    [unknown func]),
  #27
    (dbghelp: @0x7877ea[cataclysm-tiles.exe+0x3877ea]), 
    (libbacktrace: ZN4game13handle_actionEv+0x5a8a@0x7877ea),
    (libbacktrace: 0x7877ea    [unknown src]:0    [unknown func]),
  #28
    (dbghelp: @0x754eaf[cataclysm-tiles.exe+0x354eaf]), 
    (libbacktrace: ZN4game7do_turnEv+0xb9f@0x754eaf),
    (libbacktrace: 0x754eaf    [unknown src]:0    [unknown func]),
  #29
    (dbghelp: IMG_LoadWEBP_RW+0x67e9c9@0x17e6ae9[cataclysm-tiles.exe+0x13e6ae9]), 
    (libbacktrace: main+0x1199@0x17e6ae9),
    (libbacktrace: 0x17e6ae9    [unknown src]:0    [unknown func]),
  #30
    (dbghelp: @0x4013ed[cataclysm-tiles.exe+0x13ed]), 
    (libbacktrace: _tmainCRTStartup+0x23d@0x4013ed),
    (libbacktrace: 0x4013ed    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crtexe.c:336    __tmainCRTStartup),
  #31
    (dbghelp: @0x4014fb[cataclysm-tiles.exe+0x14fb]), 
    (libbacktrace: WinMainCRTStartup+0x1b@0x4014fb),
    (libbacktrace: 0x4014fb    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crtexe.c:186    WinMainCRTStartup),
  #32
    (dbghelp: BaseThreadInitThunk+0x14@0x7ffe3fb37bd4[KERNEL32.DLL+0x17bd4]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #33
    (dbghelp: RtlUserThreadStart+0x21@0x7ffe40c0ced1[ntdll.dll+0x6ced1]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),

**Comment by ZhilkinSerg** [comment]
Cannot reproduce.
