### ISSUE TITLE
Split Evacuee Start into Broken and Intact

### ISSUE THREAD

**Issue by MarceloLaser** [CleverRaven/Cataclysm-DDA#39393]
# Is your feature request related to a problem? Please describe.
Nope, just a suggestion about the Evacuee start. I know (kinda) recently you guys added a variant to it that starts in a broken evac shelter, and that is REALLY cool, but also, it is a COMPLETELY different start from the regular one. To the point where I feel that it may as well be a different start option altogether. To me, I like the regular evac start, and I feel like the new start becomes something of a nuisance where I just restart until I get a regular one.

# Describe the solution you'd like
I'd like to see an option for an evac shelter start that only includes the intact evac shelter. Call it "evac shelter easy mode" or what have you.

# Describe alternatives you've considered
I understand I could make the change locally, but I'm not savvy enough to mess around in the json files and I'm afraid of removing the evac shelters from the game altogether. Which is NOT what I'm suggesting, I like the broken evac shelters, I just would like the option to always start in an intact one. Given what I said, that the two feel like entirely different starts (particularly with the broken computers and lack of curtains, which make a MASSIVE difference), I reckon it'd be cool to have them separate in the base game.

Another option would be to add one intact computer and a guaranteed couple of curtains on the windows, which would bridge the gap between the two starts and make them feel more like a single cohesive thing. The computer, not so much for the light, but for the quest to find the rescue center, which can sometimes be next to impossible to find without the computer.

**Comment by KorGgenT** [comment]
you can press / to select which you start at in the new character creation menu.

**Comment by Xenomorph-III** [comment]
If you can choose the shelter at least make the names more descriptive.

"Evac Shelter - Intact/Evac Shelter - Vandalized/Evac Shelter - Used"

**Comment by capSAR273** [comment]
Currently specific variants of a starting location can't be picked. You get to pick the category of location (house/barn/etc), but a random variant will be chosen for you. I'd like to be able to pick a variant, but there are some cases where 50+ variants exist for one location. Looking into this now
