### ISSUE TITLE
Irradiated status is fully visible by default. 

### ISSUE THREAD

**Issue by Tamiore** [CleverRaven/Cataclysm-DDA#39415]
# Describe the bug

Irradiated status is visible in character menu ( @ menu) without a Geiger counter, together with the exact radiation dose absorbed.

# Steps To Reproduce

1. Make a character.
2. Go hang around toxic waste dump or any other radioactive location for an hour or two.
3. Check your character menu.

# Expected behavior

Absorbed dose should not be displayed **unless** the character uses Geiger counter or something similar.

# Screenshots

![irradiated](https://user-images.githubusercontent.com/61312205/78914706-79c5aa80-7a93-11ea-8876-f44a8736b324.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Slots [cbm_slots]
]

# Additional context
While it might be somewhat frustrating to new players to have a hidden status effect, just flat out showing the exact dose by default is not the way to go.

At the very least status effect should not be shown under a certain threshold. 
I.e. a character would need to get at least an equivalent of Irradiated [10] to see anything.

**Comment by jbytheway** [comment]
Surely the Geiger counter is for measuring how much radiation there is in the environment, not measuring how much radiation the character has been exposed to.

In other words, the Geiger counter should be telling you how fast that `Irradiated` number will tick up, not its current value.

Something like the radiation badge would be more suitable for the latter.

**Comment by Dacendeth** [comment]
There is the radiation biomonitor watch thingy, but yeah it's also mostly pointless when you can just look at your effects.

**Comment by Tamiore** [comment]
>Surely the Geiger counter is for measuring how much radiation there is in the environment, not measuring how much radiation the character has been exposed to.
Geiger counter explicitly can be used to measure **your** expose level. 

>In other words, the Geiger counter should be telling you how fast that Irradiated number will tick up, not its current value.
But since right now you can just look at your status screen and see **right away** how fast it's actually ticking (and if it's ticking at all),  Geiger counter is redundant in this application as well as long as exposure is just imminently shown.

**Comment by jbytheway** [comment]
> Geiger counter explicitly can be used to measure **your** expose level.

Well, that's also a bug then, I guess.  It shouldn't do that.

> But since right now you can just look at your status screen and see **right away** how fast it's actually ticking (and if it's ticking at all), Geiger counter is redundant in this application as well as long as exposure is just immediately shown.

Looking at it now doesn't tell you how fast it will change in the future.  Sure, if you stand still and make observations every minute or so, then you'd find out, but it's not immediately obvious.

**Comment by Tamiore** [comment]
>Looking at it now doesn't tell you how fast it will change in the future. Sure, if you stand still and make observations every minute or so, then you'd find out, but it's not immediately obvious.

It's not immediately obvious with Geiger counter either: you have to actually go and measure in different tiles within a structure to get an idea if it's safe. And if you are moving from tile to tile within a structure, you might as well look at your status screen and get effectively the same information.

Again, the problem here is that there is no threshold and no delay. You can see that you are being irradiated well before absorbing a dose that you have any noticeable effect, much less developing actual symptoms.

**Comment by Tamiore** [comment]
Update: Another way to handle it (somewhat more new-code-intensive) would be to set a delay (of, say, 8 hours) between absorbing radiation and it actually effecting the character.
That way it would be possible to still absorb huge amounts of radiation without knowing any better, but still communicate the effect to the player when radiation sickness actually sets in.

**Comment by Dacendeth** [comment]
I think if irradiated had to stack at to a point (10 or 20) before it showed up that would probably be fine. That way you can tell when you're really sick without tool assistance and the other tools can be used to help you know when you walk into a hot area before you get to that point.
