### ISSUE TITLE
Segmantation fault when pressing %(Use item menu)

### ISSUE THREAD

**Issue by Koalabog** [CleverRaven/Cataclysm-DDA#39419]
# Describe the bug
The game crashes when carrying a gun and opening the use item menu

# Steps To Reproduce

1. Make a player with a gun and some mod
2. Put said mod on gun
3. press %

# Expected behavior

A menu where you can select which item to activate to appear

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-439-gdf00ef1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    DinoMod [DinoMod],
    MSX Indicators: REMIX [UDP_REMIX_INDICATORS],
    Stats Through Skills [StatsThroughSkills],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food]
]

# Additional context

Tested a few times to open the menu while carrying items other then my sig 552 and it worked fine

Crash log: 
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4457556/crash.log)

Debug log:
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4457560/debug.log)

Save file:
[Erf 121.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4457566/Erf.121.zip)

**Comment by Qrox** [comment]
Wasn't this already fixed by #39408?

**Comment by Koalabog** [comment]
it seems fixed on build 10511 so i guess so?
