### ISSUE TITLE
Character creation name

### ISSUE THREAD

**Issue by Gaunah** [CleverRaven/Cataclysm-DDA#39411]
# Describe the bug
It seems that with the merge of #39385 it's no longer possible to type a custom Character name with 'h', 'j', 'k' or 'l' in it because it will interpreted as hotkey to change focus to the "height" or "age" field.

# Steps To Reproduce

1. Go the character creation menu
2. Try to type an 'h', 'j', 'k', or 'l' in the name field

# Expected behavior

That I can choose a name with the mentioned letters in it.

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.E-457-g3895c92cf0 [64-bit]
- Graphics Version: Curses
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
The capital version of the letters work is intended.

**Comment by ZhilkinSerg** [comment]
@KorGgenT Let's make it a popup text edit box for name entry?

**Comment by KorGgenT** [comment]
oh wow yeah, i didn't even consider hjkl would be cardinal directions
