### ISSUE TITLE
Trigger happy trait doesnt work.

### ISSUE THREAD

**Issue by Dacendeth** [CleverRaven/Cataclysm-DDA#39412]
# Describe the bug
Trigger happy doesnt do anything, I've never seen it trigger, i've had multiple people say it's never triggered, the code for it from a quick glance is two instances of " // TODO: add check for TRIGGERHAPPY" in avatar_action.cpp.

# Steps To Reproduce
1. Get trigger happy and fire a gun forever and never have it do anything.

# Expected behavior
For my character to randomly shoot full auto sometimes.

# Screenshots

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-439-gdf00ef1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

**Comment by RafeHaab** [comment]
Please don't change it, I'm already starved for points as it is, and a free one isn't a bad thing.

**Comment by anothersimulacrum** [comment]
If you're starved for points, change the point limit or use freeform. We shouldn't have things be actively broken because people wanted extra points for starting their character without changing using any of the two existing mechanisms for that.
