### ISSUE TITLE
CRASH: Eating a Medium opened tin can of canned pineapple

### ISSUE THREAD

**Issue by Th3Kh3d1v3** [CleverRaven/Cataclysm-DDA#39416]
Whenever I try to eat a "Medium opened tin can of canned pineapple" the game crashes.  I can eat other things just fine.

# Steps To Reproduce

Eat a "Medium opened tin can of canned pineapple"

# Expected behavior

Not to crash

# Screenshots

# Versions and configuration

Latest experimentals...no mods.

**Comment by LaVeyanFiend** [comment]
Clone of #39394?
