### ISSUE TITLE
Some string formatting tests fail due to regional number formatting

### ISSUE THREAD

**Issue by Hirmuolio** [CleverRaven/Cataclysm-DDA#39423]
# Describe the bug

Some of the tests fail when the game is compiled with OS set to a region that uses "," instead of "." for  decimal separator.

Example:

```
item_tname_test.cpp(276): FAILED:
  CHECK( vtwin.tname() == "1.0L V-twin engine" )
with expansion:
  "1,0L V-twin engine"
  ==
  "1.0L V-twin engine"
```

# Steps To Reproduce
1. Compile CDDA with Visual Studio with computer set to region that uses "," instead of "." for decimal.
2. Run the tests.
3. Observe how some of them fail.

# Expected behavior

Nothing is wrong here and tests should not fail.

# Screenshots

# Versions and configuration

Windows 10
Region: Finland

# Additional context

Log that shows which exact tests fail:
[test_log.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/4457978/test_log.txt)

**Comment by wapcaplet** [comment]
@Hirmuolio I was not able to reproduce this issue on my own machine, however I've submitted a PR #39648 that ought to fix it. Can you please confirm whether it works for you?

**Comment by Hirmuolio** [comment]
@wapcaplet just ran the tests and all passed.
