### ISSUE TITLE
Why do farms not spawn oats?

### ISSUE THREAD

**Issue by SmogReborn** [CleverRaven/Cataclysm-DDA#39422]
Game version: 0.E

Operating system: Windows 10

Tiles or curses: Tiles

Mods active: I doubt they cause this

### Expected behavior
Oats in farms

### Actual behavior
No Oats in farms

### Steps to reproduce the behavior
Head to \data\json\itemgroups\Agriculture_Forage_Excavation open agriculture.json scroll down to the hydro ID and look for oats in the list you will notice that there are no oats. Hydro is used to determine what spawns on dirt mounds in farms. Farms should have oats.

**Comment by LaVeyanFiend** [comment]
Closed via #39426. Can you close this @SmogReborn?
