### ISSUE TITLE
Battery crafting game crash if light battery is loaded in soldering iron

### ISSUE THREAD

**Issue by Caleiyous** [CleverRaven/Cataclysm-DDA#39437]
# Describe the bug

When trying to craft (normal or high-capacity) medium batteries via crafting menu recipes _if you loaded normal or high-capacity light battery in soldering iron_, the game crashes immediately with error message.

# Steps To Reproduce

1. Make fresh world without mods and new character.
2. Spawn all items necessary for crafting standard medium battery.
3. Go to crafting menu and try crafting medium battery.
4. Reload soldering iron with normal or high-capacity light battery.
5. Try crafting medium battery again. 

# Expected behavior

First crafting should be fine as soldering iron spawns with ultra-light battery.
Second crafting of medium battery leads to crash.
I guess the game prioritizes batteries somehow from used tools leading to a conflict during crafting even if enough batteries are around to fulfill crafting requirements.

# Screenshots

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-468-g9e02bc1 Build 10508
 - Graphics version: Tiles
 - Ingame language: [English]
 - Mods loaded: [Disable NPC needs]

# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4460250/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4460256/debug.log)
[Testing.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4460260/Testing.zip)

**Comment by bcronrath** [comment]
I have also noticed this, though it was loaded in a bionic that caused mine to crash I narrowed it down to, so I be it's loading in anything that causes it to crash

**Comment by sbenzaquen** [comment]
I have seen this crash also when trying to install a car battery while a nearby tool has a car battery attached through the `battery compartment mod`.

**Comment by Kaidou10000** [comment]
Is there still that game crash in latest build? (e.g. build 10538)

**Comment by sbenzaquen** [comment]
Seems fixed to me in 10548.
Tried crafting the batteries and installing the car battery and both worked.

**Comment by Night-Pryanik** [comment]
Closing until reconfirmed.
