### ISSUE TITLE
Cannot install weapon in vehicle turrent mount

### ISSUE THREAD

**Issue by OvenBaker** [CleverRaven/Cataclysm-DDA#39436]
# Describe the bug

Unable to install weapons in a vehicle turret mount. Installation menu cannot find item, can find all other ingredients (tools / skills).

# Steps To Reproduce

1. Create new character with tools (e.g. Home Mechanic)
2. Set skills to 10 with debug menu
3. Spawn a new Humvee with debug menu
4. Remove mounted M240
5. Attempt to reinstall M240

# Expected behavior

Installation menu allows installation of turret weapons.

# Screenshots

![turret-bug](https://user-images.githubusercontent.com/5769257/78968886-f42f1280-7b05-11ea-9aeb-98fa69bca25e.PNG)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-468-g9e02bc1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by Dacendeth** [comment]
Can confirm, unable to mount any weapons.

**Comment by Kiktamo** [comment]
Can also confirm. As an addition from what I noticed with another test myself it seems that weapons or at least guns aren't being recognized properly as components in crafting.

Tested by spawning in an M320 GLM and a grenade launcher buttstock. Couldn't craft the M320 standalone launcher as the M320 GLM was still considered missing.

**Comment by Miner239** [comment]
I found build 10497 includes the change that break turret installing and the issue of guns not being recognized as crafting material. Build 10496 works fine.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/mods-unleashed-compilation-for-e-v-1-0-experimental-v-0-01/22725/97
