### ISSUE TITLE
"Item battery_ups was loaded with charges, but can not have any!"

### ISSUE THREAD

**Issue by LordMadness** [CleverRaven/Cataclysm-DDA#39434]
# Describe the bug

UPS tried to recharge when it had a Disposable Battery loaded.

# Steps To Reproduce

1. Build Vehicle with: Frame; Dashboard; Recharging Station; Cargo Space; Small Storage Battery; 4" casters.
2. Load UPS with used Heavy Disposable Battery; Store in the Vehicle;
3. Turn on Recharger;
4. Leave bubble(?); Return. Error should fire now.

# Expected behavior

Wanted to recharge my UPS, but mistakenly loaded a disposable battery in it.

# Screenshots

N/A

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.E [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

# Additional context

![ups](https://user-images.githubusercontent.com/45457447/78959287-801a4d80-7ab8-11ea-8bd7-1dac80f98097.png)

**Comment by Koalabog** [comment]
Unless this 2 different errors, i do not think this is caused by using disposable batteries since i am getting same error and all my UPS are loaded with high capacity rechargeable batteries.

**Comment by Dacendeth** [comment]
Yeah it's just something that happens every now and then, it's seems perfectly safe to ignore thankfully.

**Comment by bcronrath** [comment]
I've noticed though that it can lead to crashing if you leave the battery in and use it to craft something that requires the battery

**Comment by Sijko** [comment]
i just found some ups-es and the next load was this faulty
