### ISSUE TITLE
Electrohack Use Inconsistency

### ISSUE THREAD

**Issue by TempestMaiden** [CleverRaven/Cataclysm-DDA#39446]
# Describe the bug

Strictly speaking, this isn't a bug I encountered during gameplay.

I was examining code to try and figure out if I was willing to have a promising character hack certain cardreaders in a bunker basement when I found the following bit in activity_handlers.cpp:

static int hack_level( const player &p )
{
    ///\EFFECT_COMPUTER increases success chance of hacking card readers
    // odds go up with int>8, down with int<8
    // 4 int stat is worth 1 computer skill here
    ///\EFFECT_INT increases success chance of hacking card readers
    return p.get_skill_level( skill_computer ) + p.int_cur / 2 - 8;
}

The comment says the neutral point for Intelligence should be 8, and that 4 int should be worth a level of computer skill. The code seems to say the neutral point for intelligence is 16, and that 2 int is worth a level of computer skill. 

One of these should probably be changed.

# Steps To Reproduce

Open activity_handlers.cpp and search for hack_level.

# Expected behavior

I expected the code and the comment describing it to be in agreement.

**Comment by mlangsdorf** [comment]
if you can read the code, you can submit a patch to either fix the comment to match the code or match the code to the comment.
