### ISSUE TITLE
Car too bulky to move by hand

### ISSUE THREAD

**Issue by Brytenwalda** [CleverRaven/Cataclysm-DDA#39449]
# Describe the bug

I can't move away from the car and the message says "The electric car is too bulky for you to move by hand."

# Steps To Reproduce

1. I went into the trunk to drop items.
2. I left the trunk.
3. Couldn't leave. 

# Expected behavior

I would expect to be able to walk normally. 

# Versions and configuration

Current version from the launcher, tiles. Unmodded. Windows 10.

**Comment by anothersimulacrum** [comment]
Stop grabbing the car, press G.
