### ISSUE TITLE
Bike rack can be uninstalled with bike loaded

### ISSUE THREAD

**Issue by aujxn** [CleverRaven/Cataclysm-DDA#39457]
# Describe the bug
Was curious to see what would happen if I removed a bike rack from the vehicle with a bike attached. When I walked up to the bike to remove it I got a debug message. Bike is now fused to my rig.

# Steps To Reproduce
1. Install bike rack to vehicle
2. Load bike on rack
3. Remove bike rack

# Expected behavior
Restriction to remove in use equipment.

# Versions and configuration
- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.E [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    SpeedyDex [speedydex]
]

**Comment by DatMeg** [comment]
This can happen when repairing a bike (or other small vehicle) while it is still attached via the bike rack. Any repairs performed on the mounted vehicle instantly fuses it with the car it's attached to. Doesn't matter if it's the Frame, or maybe a battery.
