### ISSUE TITLE
Grant triage perms to DinoMod maintainers

### ISSUE THREAD

**Issue by damien** [CleverRaven/Cataclysm-DDA#39455]
# Is your feature request related to a problem? Please describe.

I'd like to get perms to triage issues to DinoMod maintainers so we can start fielding feature requests and bug reports relevant to DinoMod. Additionally, I'd like to have a new label added to the issue tracker to help organize tickets or project entries relating to DinoMod.

# Describe the solution you'd like

Create the following label in this project's issue tracker: `Mod: DinoMod`. Bonus points if you make it a color related to the [Jurassic Park logo](https://www.google.com/search?client=firefox-b-1-d&q=jurassic+park+logo).

Grant triage permissions to the following Github users (official DinoMod maintainers):
1. @damien 
2. @LyleSY 
3. @ephemeralstoryteller 

# Describe alternatives you've considered

Letting core maintainers worry about ticket assignment.

# Additional context

I was told in Discord triage permissions shouldn't be too big an ask. I'd also like to know, if possible, if such perms allow us to make a mod-specific Project board for DinoMod under the CleveryRaven org or Cataclysm-DDA repo. To the largest extent possible, I'd like us to organize work around in-repo mods in the repo.

**Comment by damien** [comment]
Also made #39456 to formally document DinoMod maintainers in `modinfo.json`.

**Comment by kevingranade** [comment]
Maintainers invited to triage team and label created.
