### ISSUE TITLE
[Magiclysm] Frost Armor spell does nothing

### ISSUE THREAD

**Issue by KorGgenT** [CleverRaven/Cataclysm-DDA#39468]
# Describe the bug

The Frost armor spell does nothing when cast.

# Expected behavior

The spell should create some kind of frost armor: i'd expect an item maybe, with some armor values balanced to the difficulty of the spell and the mana cost.

# Versions and configuration

Current master

# Additional context

Someone on the discord mentioned maybe looking into it, but I decided opening an issue was a good bet too. I'm not really particular on the details of the json here, just that frost armor should do some kind of "frosty armor" ... thing. it could even reduce cold damage via enchantment effects or something.

**Comment by VitorHP** [comment]
Hello. I'm having a look at this. It's my first try at contributing.

For what i've seen so far, the frost_armor spell has its effect set to target_attack and by looking at the Magic doc, it seems to be the wrong one.

By looking at the ice_shield magic, it uses spawn item and there's even an ice_shield item in the ethereal_items list. Other similar magic seems to be implemented in the same fashion.

Maybe this should be implemented as an item too?

**Comment by KorGgenT** [comment]
yes, implementing as an item is perfectly acceptable.
