### ISSUE TITLE
Already learned skill fails silently in (R)ead

### ISSUE THREAD

**Issue by minakitty** [CleverRaven/Cataclysm-DDA#3946]
- Get a cheapie book/mag:  Alpha Male Quarterly is a good one
- Study until you can't learn anymore
- (R)ead it again

It used to be that it would warn that you wouldn't learn anything new and give you a query on if you wanted to read it or not.  Now it fails silently, pretending that you are studying (Even telling you so in the chat) but then it drops you right back to the game.
##

**Comment by sethsimon** [comment]
I think this can be closed. The message when you start reading any book is `Now reading <whatever>, Press . or 5 to stop early.`. There's no explicit warning if you try to read something that you can't learn from, but 1) The book's name in the selection screen is blue if and only if you can learn from it, and 2) The reading uimenu will have the `Read until you gain a level` option disabled if you can't learn from it.
