### ISSUE TITLE
Bullets flying through car wreckage rip it to shreds

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#39473]
I'll just paste a part of message log here:

"The pile-up's XX trunk door breaks into pieces!"
"The pile-up's XX hatch breaks into pieces!"
"The pile-up's XX frame breaks into pieces!"
"The pile-up's XX frame is destroyed!"
"The pile-up's XX trunk breaks into pieces!"
"The pile-up's XX hatch breaks into pieces!"
"The pile-up's XX muffler breaks into pieces!"
"The pile-up's XX roof breaks into pieces!"
"The pile-up's XX frame breaks into pieces!"
"The pile-up's XX frame is destroyed!"
"The pile-up's XX quarterpanel is destroyed!"
"The pile-up's XX windshield breaks into pieces!"
"The pile-up's XX frame is destroyed!"
"The pile-up's XX windshield is destroyed!"
"The pile-up's XX clock is destroyed!"
"Good hit!"
"You hit the tough zombie for 41 damage."
"The pile-up's XX seat is destroyed!"
"The pile-up's XX reclining seat breaks into pieces!"
"The pile-up's XX quarterpanel breaks into pieces!"
"The pile-up's XX seatbelt breaks into pieces!"
"The pile-up's XX roof breaks into pieces!"
"The pile-up's XX frame breaks into pieces!"
"The pile-up's XX extra light frame is destroyed!"
"The pile-up's XX windshield is destroyed!"
"The pile-up's XX door breaks into pieces!"
"The pile-up's XX trunk breaks into pieces!"
"The pile-up's XX reclining seat breaks into pieces!"
"The pile-up's XX seatbelt breaks into pieces!"
"The pile-up's XX controls breaks into pieces!"
"The pile-up's XX dashboard breaks into pieces!"
"The pile-up's XX security system breaks into pieces!"
"The pile-up's XX stereo system breaks into pieces!"
"The pile-up's XX car horn breaks into pieces!"
"The pile-up's XX roof breaks into pieces!"
"The pile-up's XX frame breaks into pieces!"
"The pile-up's XX extra light frame breaks into pieces!"
"The pile-up's XX frame is destroyed!"
"The pile-up's XX seatbelt is destroyed!"
"Good hit!"
"You hit the tough zombie for 39 damage."
"The pile-up's XX solar panel is destroyed!"
"The pile-up's XX 17\" wheel breaks into pieces!"
"The pile-up's XX quarterpanel breaks into pieces!"
"The pile-up's XX wheel hub assembly (steerable) breaks into pieces!"
"The pile-up's XX headlight breaks into pieces!"
"The pile-up's XX frame breaks into pieces!"
"The pile-up's XX extra light frame is destroyed!"

# Steps To Reproduce

Find some wreckage, spawn zombie behind it, give your survivor a rifle and shoot the zombie.

# Expected behavior

If a bullet hits some part of wreckage it should either stop or change its course while losing all/some of its energy (which will result in damaging the part it collided with), it should not fly straight through the wreckage dealing damage at every single tile. Or, as that'd probably take too much time to implement atm, just make bullets not interact with wreckages.

# Versions and configuration

0.E-580-gf594632 (tiles) on win7x64

**Comment by JeanLucVanDamme** [comment]
This must be new behavior. I'm on Build 10425 (3 weeks old), and bullets are usually stopped by the first intact vehicle part they reach, and don't seem to deal damage to that part.

**Comment by olanti-p** [comment]
Maybe bullet impacts do enough damage to destroy broken parts, but not enough to scratch healthy ones? Could be a duplicate of (related to) #39445
