### ISSUE TITLE
Game crashes when using Advanced Inventory to steal faction items with "Thief" protection on

### ISSUE THREAD

**Issue by SgtMustang** [CleverRaven/Cataclysm-DDA#39482]
# Describe the bug

It appears that stealing items with the Advanced Inventory manager crashes the game if Thief mode is set to "Never" allow stealing.

# Steps To Reproduce

- "Thief mode" safety is set to "Never" allow the theft of items.
- An early Free Merchants mission where you must rescue a caravan generates several Bandits & Thugs.
- Items on the corpses of these Bandits are considered Faction items, and taking them is considered theft.
- Attempting to pick up items from the normal "e" menu results in no action (intended).
- Attempting to transfer the items into the player's inventory using the Advanced Inventory manager results in an immediate game crash.

# Expected behavior

Advanced Inventory Management screen should report that you are unable to transfer the items because Thief mode protection has been set to "Never allow".

# Screenshots

# Versions and configuration
 - OS: Windows 10
 - Game Version: 0.D-13484-ga0fe8c1
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: "dda","no_npc_food","aftershock","crt_expansion","Cata++","No_Rail_Stations","Graphical_Overmap","Nonperishable_Overhaul","speedydex","No_Fungi"

# Additional context
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4465097/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4465115/debug.log)

**Comment by OliveChukar** [comment]
Tested in ver 0.E-9072-g1bb53ba-dirty with core content pack dark days ahead only. Attempted to move faction items using advanced inventory with thief mode set to never. Nothing happened items did not move no crash happened and no debug message appeared. Not able to duplicate issue it may be fixed.

**Comment by anothersimulacrum** [comment]
Closing as fixed.
