### ISSUE TITLE
Laser weapons light up the tile they are fired from

### ISSUE THREAD

**Issue by Koalabog** [CleverRaven/Cataclysm-DDA#39481]
# Is your feature request related to a problem? Please describe.
Currently laser weapons light up the entire path to the target and the target but not the tile the weapon is fired from. This makes them much too powerful at night because not only are they very quiet but they also ruin the targets night vision. 

# Describe the solution you'd like
Simply include the tile the weapon is fired from in the area lit by the beam. possibly a louder sound since any laser powerful enough to actually harm anything would probably be quite loud. After further looking into it noise probably wouldnt to too much so ignore that part

# Describe alternatives you've considered
Leaving it as is works if we want lasers to be night raid weapons but its kind of difficult to imagine all creatures not noticing the bright lasers origin to investigate.

**Comment by natsirt721** [comment]
Lasers (and DEW in general) shouldn't light up the path at all unless they hit something that reflects light, like smoke or a tree limb. They probably shouldn't light up the target's nor the shooter's square at all, unless they are using visible frequencies. Most modern-day DEWs don't use visible frequencies at all, so you shouldn't see anything. There are a few exceptions though:
- If a flammable material is encountered, the beam can set fire to the material
- If the power is really high and hits a material of sufficient hardness (a few inches of steel plate perhaps) you can get spallation, which can manifest as sparks
- If the power is really really high, the oxygen in the air can turn to ozone (it does this already a bit, regardless of power), which will look like a sort of 'haze' along the beampath. This is only while the weapon is firing, as the ozone with quickly disperse once the beam is shut off.
- If the beam is focused on one location for a time, or delivers significant energy in a single charge, metallic materials may liquefy and emit light via blackbody radiation.
- If the laser is using a visible frequency and encounters particulates in the air (smoke) or other materials along the way, light can reflect off of the material. 

See [this video](https://www.youtube.com/watch?v=tyUh_xSjvXQ) for a good example of what a laser strike looks like. These are pretty high-power weapons (not man-portable) so you probably won't get the kind of flame-ups shown there. What you definitely won't see is a StarWars-esque 'bolt' of laser or even the more-accurate-but-not-quite-accurate StarTrek 'beam' from a phaser.

That said, I'd be in favor of removing the lighting effects altogether. Even for lasers in visible frequency, unless there are things for the beam to reflect off of, all of the light goes into hitting the target.
