### ISSUE TITLE
Water in vehicle tanks can't be used for cooking

### ISSUE THREAD

**Issue by landslide591** [CleverRaven/Cataclysm-DDA#39498]
**Describe the Bug**

Title pretty much says it, in the newest build water is listed as a missing ingredient when I try to cook with it. Vehicle has tanks of both water and clean water. (I was able to cook with water in my inventory)

**Steps To Reproduce**

- Have a vehicle with water in tanks
- Try to cook some tea or kompot with it (or anything else)
- Water is written in red in the ingredients list

**Expected behavior**

I was expecting to be able to brew some tea with the water in my vehicle, but am unable to

**Screenshots**

![Screenshot (83)](https://user-images.githubusercontent.com/63309034/79073306-2008ee80-7ce6-11ea-8433-f6f71a5f22ba.png)

![Screenshot (84)](https://user-images.githubusercontent.com/63309034/79073315-27c89300-7ce6-11ea-9f7b-8f0419d84b12.png)

**Versions and configuration**

Version 10517
Windows 10
Mod: Dark Days of the Dead

**Comment by Dacendeth** [comment]
I think you need to install a faucet over the tank to use it in recipes.

**Comment by landslide591** [comment]
Hmm, that might be it. I swapped my Kitchen Unit for a FoodCo Kitchen buddy (which doesn't have a faucet), but neither were installed over my water tank.

**Comment by landslide591** [comment]
Yup, you're right. Installed a water faucet and everything is working again. Guess I learned something new today!
