### ISSUE TITLE
Blanket is not used to keep warm while sleeping

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#39495]
# Describe the bug

In a cold car seat.

# Steps To Reproduce
Load the game and sleep. Wake up from aching hands. Wearing the blanket could have prevented that.

# Expected behavior
The character using the blanket on the seat to sleep at a comfortable temperature.

# Screenshots

# Versions and configuration
- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.E-588-g217f4235ab-dirty [64-bit]
- Graphics Version: Curses
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

# Additional context
[2020.02.22.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4466335/2020.02.22.zip)

**Comment by RoyBerube** [comment]
In `Character::fall_asleep() ` it gathers some info on what available items can be used for warmth, but only uses the info to give the player some feedback when falling asleep. It doesn't actually do anything with the blankets.

It looks to me that some restructuring of the code will be needed to apply and then remove the warmth effect while sleeping. Perhaps a sleep activity - an activity is used for falling asleep but is cancelled when entering sleep.

**Comment by RoyBerube** [comment]
I've got a fix for this working. Just need to do some more testing. Should have a PR on it in a day or 2.

**Comment by kevingranade** [comment]
hah, thanks for saying something, I was just about to start looking.
