### ISSUE TITLE
container recharge problem

### ISSUE THREAD

**Issue by Sijko** [CleverRaven/Cataclysm-DDA#39503]
# Describe the bug

whenever i rechage a liquid or food from one container to another (except taking water from natural source or underground pre-genned tank) i have an error

this was in 10517 and 10500, so i rolled back to 10491
# Steps To Reproduce

fill a container with smth into another one

# Expected behavior

you guess

# Screenshots

![unknown](https://user-images.githubusercontent.com/32700053/79076676-ba782a80-7d04-11ea-81a2-923cb34184b6.png)
# Versions and configuration
10500-10517 - for sure
10492-10499 - ???

# Additional context

**Comment by Jerimee** [comment]
me too

And also, I noticed this, if you refill a canteen with cola, the cola should leave the opened aluminum can and now exist in the canteen.  But when I fill a canteen with cola (health nut that I am) I discovered I could still drink from the cans I supposedly just emptied. Doing so gave me the error above.

**Comment by Sijko** [comment]
Jerimee , yes, it always "leaves" 1 unit of liquid in the source, though it adds ok to the dest

**Comment by Sijko** [comment]
10522 - problem still remains
