### ISSUE TITLE
 basic lab analysis kit recipe needs fix

### ISSUE THREAD

**Issue by Sijko** [CleverRaven/Cataclysm-DDA#39502]
# Describe the bug

recipe of basic lab analysis kit is broken

# Steps To Reproduce

if spectrophotometer is charged with a battery, the craft system sees it as absent, and you can't make the BLAK, until you take out the battery from it.

# Expected behavior

the s-p-meter should be visible in the recipe as available

# Screenshots

# Versions and configuration
10491

# Additional context

**Comment by Raikiri** [comment]
The same thing happens to any item that has an ingredient with batteries. For example, welder cannot be crafted from makeshift welders unless you remove batteries from them.

**Comment by PatrikLundell** [comment]
Similarly, some items can not have their batteries replaced while they're turned on, while others can be reloaded (the head lamps can have their batteries replaced while turned on, while I think either/or the IR goggles and NV goggles have to be turned off first).

I've also seen the issue Raikiri mentions, i.e. that you have to remove batteries for the items to be recognized as valid for crafting. I can't swear on it, but think the same goes for flashlights to be installed in vehicles as aisle lights (which logically is another version of crafting).

**Comment by kevingranade** [comment]
Nice to fix, but the easy workaround disqualifies this from being a release blocker.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-10939.
![изображение](https://user-images.githubusercontent.com/11132525/187434592-6e92f34b-a8a1-41a1-b498-aca91271a209.png)
![изображение](https://user-images.githubusercontent.com/11132525/187436282-8167e4f6-bbc9-4cee-9070-8af7c51cdf67.png)
