### ISSUE TITLE
Crash when turning in 2nd quest for Hub

### ISSUE THREAD

**Issue by raiden0488** [CleverRaven/Cataclysm-DDA#39507]
# Describe the bug

When I turn in the quest item for the 2nd quest for The Hub (data card from mind splicing) the game crashes.

# Steps To Reproduce

**Comment by Damdern** [comment]
I'm having the same issue, here's the crash log dump

The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 0.E-642-g7c10b35
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

  #0
    (dbghelp: @0x636c66[cataclysm-tiles.exe+0x236c66]), 
    (libbacktrace: Z21debug_write_backtraceRSo+0x56@0x636c66),
    (libbacktrace: 0x636c66    [unknown src]:0    [unknown func]),
  #1
    (dbghelp: @0x61a9cf[cataclysm-tiles.exe+0x21a9cf]), 
    (libbacktrace: log_crash+0x4af@0x61a9cf),
    (libbacktrace: 0x61a9cf    [unknown src]:0    [unknown func]),
  #2
    (dbghelp: @0x61b6a2[cataclysm-tiles.exe+0x21b6a2]), 
    (libbacktrace: signal_handler+0x32@0x61b6a2),
    (libbacktrace: 0x61b6a2    [unknown src]:0    [unknown func]),
  #3
    (dbghelp: SMPEG_error+0x4b034@0x10807e0[cataclysm-tiles.exe+0xc807e0]), 
    (libbacktrace: gnu_exception_handler+0x70@0x10807e0),
    (libbacktrace: 0x10807e0    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crt_handler.c:223    _gnu_exception_handler),
  #4
    (dbghelp: _C_specific_handler+0x8c@0x77367258[ntdll.dll+0x57258]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #5
    (dbghelp: _chkstk+0x9d@0x7737be9d[ntdll.dll+0x6be9d]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #6
    (dbghelp: RtlInitializeResource+0x53a@0x7735040a[ntdll.dll+0x4040a]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #7
    (dbghelp: KiUserExceptionDispatcher+0x2e@0x7737b53e[ntdll.dll+0x6b53e]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #8
    (dbghelp: @0x821467[cataclysm-tiles.exe+0x421467]), 
    (libbacktrace: ZNK4item6typeIdB5cxx11Ev+0x17@0x821467),
    (libbacktrace: 0x821467    [unknown src]:0    [unknown func]),
  #9
    (dbghelp: @0x8494f2[cataclysm-tiles.exe+0x4494f2]), 
    (libbacktrace: ZN4item19use_amount_internalERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERiRNS0_4listIS_SaIS_EEERKSt8functionIFbRKS_EE+0x32@0x8494f2),
    (libbacktrace: 0x8494f2    [unknown src]:0    [unknown func]),
  #10
    (dbghelp: @0x849752[cataclysm-tiles.exe+0x449752]), 
    (libbacktrace: ZZN4item10use_amountERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERiRNS0_4listIS_SaIS_EEERKSt8functionIFbRKS_EEENKUlPS_E_clESK_+0x32@0x849752),
    (libbacktrace: 0x849752    [unknown src]:0    [unknown func]),
  #11
    (dbghelp: IMG_LoadWEBP_RW+0x457a41@0x15ca091[cataclysm-tiles.exe+0x11ca091]), 
    (libbacktrace: ZNSt17_Function_handlerIF13VisitResponseP4itemS2_EZN9visitableIS1_E11visit_itemsERKSt8functionIFS0_S2_EEEUlS2_S2_E_E9_M_invokeERKSt9_Any_dataOS2_SG_+0x21@0x15ca091),
    (libbacktrace: 0x15ca091    [unknown src]:0    [unknown func]),
  #12
    (dbghelp: @0xfa313e[cataclysm-tiles.exe+0xba313e]), 
    (libbacktrace: ZN13item_contents14visit_contentsERKSt8functionIF13VisitResponseP4itemS3_EES3_+0x4e@0xfa313e),
    (libbacktrace: 0xfa313e    [unknown src]:0    [unknown func]),
  #13
    (dbghelp: IMG_LoadWEBP_RW+0x344efc@0x14b754c[cataclysm-tiles.exe+0x10b754c]), 
    (libbacktrace: ZN9visitableI4itemE11visit_itemsERKSt8functionIF13VisitResponsePS0_EE+0x9c@0x14b754c),
    (libbacktrace: 0x14b754c    [unknown src]:0    [unknown func]),
  #14
    (dbghelp: @0x849688[cataclysm-tiles.exe+0x449688]), 
    (libbacktrace: ZN4item10use_amountERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERiRNS0_4listIS_SaIS_EEERKSt8functionIFbRKS_EE+0x78@0x849688),
    (libbacktrace: 0x849688    [unknown src]:0    [unknown func]),
  #15
    (dbghelp: @0x9d616e[cataclysm-tiles.exe+0x5d616e]), 
    (libbacktrace: ZN3map17use_amount_squareERK8tripointRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERiRKSt8functionIFbRK4itemEE+0x1ee@0x9d616e),
    (libbacktrace: 0x9d616e    [unknown src]:0    [unknown func]),
  #16
    (dbghelp: @0x9d669d[cataclysm-tiles.exe+0x5d669d]), 
    (libbacktrace: ZN3map10use_amountERK8tripointiRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERiRKSt8functionIFbRK4itemEE+0x27d@0x9d669d),
    (libbacktrace: 0x9d669d    [unknown src]:0    [unknown func]),
  #17
    (dbghelp: @0x5f81f4[cataclysm-tiles.exe+0x1f81f4]), 
    (libbacktrace: ZN6player13consume_itemsB5cxx11ER3mapRK14comp_selectionI9item_compEiRKSt8functionIFbRK4itemEERK8tripointi+0x4a4@0x5f81f4),
    (libbacktrace: 0x5f81f4    [unknown src]:0    [unknown func]),
  #18
    (dbghelp: @0x60405c[cataclysm-tiles.exe+0x20405c]), 
    (libbacktrace: ZN6player13consume_itemsB5cxx11ERKSt6vectorI9item_compSaIS1_EEiRKSt8functionIFbRK4itemEE+0xdc@0x60405c),
    (libbacktrace: 0x60405c    [unknown src]:0    [unknown func]),
  #19
    (dbghelp: @0xac90fc[cataclysm-tiles.exe+0x6c90fc]), 
    (libbacktrace: ZN7mission7wrap_upEv+0x42c@0xac90fc),
    (libbacktrace: 0xac90fc    [unknown src]:0    [unknown func]),
  #20
    (dbghelp: @0xc3a6e5[cataclysm-tiles.exe+0x83a6e5]), 
    (libbacktrace: ZNK13talk_effect_t5applyER8dialogue+0x45@0xc3a6e5),
    (libbacktrace: 0xc3a6e5    [unknown src]:0    [unknown func]),
  #21
    (dbghelp: @0xc53618[cataclysm-tiles.exe+0x853618]), 
    (libbacktrace: ZN8dialogue3optER15dialogue_windowRK10talk_topic+0x788@0xc53618),
    (libbacktrace: 0xc53618    [unknown src]:0    [unknown func]),
  #22
    (dbghelp: @0xc5444a[cataclysm-tiles.exe+0x85444a]), 
    (libbacktrace: ZN3npc9talk_to_uEbb+0x82a@0xc5444a),
    (libbacktrace: 0xc5444a    [unknown src]:0    [unknown func]),
  #23
    (dbghelp: @0x7b2a32[cataclysm-tiles.exe+0x3b2a32]), 
    (libbacktrace: ZN8iexamine8intercomER6playerRK8tripoint+0x82@0x7b2a32),
    (libbacktrace: 0x7b2a32    [unknown src]:0    [unknown func]),
  #24
    (dbghelp: @0x74c081[cataclysm-tiles.exe+0x34c081]), 
    (libbacktrace: ZN4game7examineERK8tripoint+0x6c1@0x74c081),
    (libbacktrace: 0x74c081    [unknown src]:0    [unknown func]),
  #25
    (dbghelp: @0x74c5e5[cataclysm-tiles.exe+0x34c5e5]), 
    (libbacktrace: ZN4game7examineEv+0x145@0x74c5e5),
    (libbacktrace: 0x74c5e5    [unknown src]:0    [unknown func]),
  #26
    (dbghelp: @0x790d0a[cataclysm-tiles.exe+0x390d0a]), 
    (libbacktrace: ZN4game13handle_actionEv+0x5a8a@0x790d0a),
    (libbacktrace: 0x790d0a    [unknown src]:0    [unknown func]),
  #27
    (dbghelp: @0x75efff[cataclysm-tiles.exe+0x35efff]), 
    (libbacktrace: ZN4game7do_turnEv+0xb9f@0x75efff),
    (libbacktrace: 0x75efff    [unknown src]:0    [unknown func]),
  #28
    (dbghelp: IMG_LoadWEBP_RW+0x690a98@0x18030e8[cataclysm-tiles.exe+0x14030e8]), 
    (libbacktrace: main+0x10f8@0x18030e8),
    (libbacktrace: 0x18030e8    [unknown src]:0    [unknown func]),
  #29
    (dbghelp: @0x4013ed[cataclysm-tiles.exe+0x13ed]), 
    (libbacktrace: _tmainCRTStartup+0x23d@0x4013ed),
    (libbacktrace: 0x4013ed    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crtexe.c:336    __tmainCRTStartup),
  #30
    (dbghelp: @0x4014fb[cataclysm-tiles.exe+0x14fb]), 
    (libbacktrace: WinMainCRTStartup+0x1b@0x4014fb),
    (libbacktrace: 0x4014fb    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crtexe.c:186    WinMainCRTStartup),
  #31
    (dbghelp: BaseThreadInitThunk+0xd@0x7710556d[kernel32.dll+0x1556d]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #32
    (dbghelp: RtlUserThreadStart+0x1d@0x7736372d[ntdll.dll+0x5372d]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),

**Comment by jbytheway** [comment]
Can either of you provide a save game?

**Comment by raiden0488** [comment]
Someone mentioned after I made this that re-making their character fixed the issue with a newer build so I deleted the world like an idiot.

**Comment by Jerimee** [comment]
I experienced the same error - let me see if I can get you the save game... Github wouldn't let me upload .sav so I zipped it up.

I'm at version VERSION: 0.E-646-g00eebfe

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4472583/crash.log)
[#V2lsYnVyIFN0aWxlcw==.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4472593/V2lsYnVyIFN0aWxlcw.zip)

**Comment by Damdern** [comment]
Ignore my cheater character and hoarder tendencies. I haven't played in a couple years, saw there was a new version of the game and wanted to re-familiarize myself with everything before playing for real. 

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4472570/save.zip)
