### ISSUE TITLE
Update PLAYER_ACTIVITY.md 

### ISSUE THREAD

**Issue by SkuliAdams** [CleverRaven/Cataclysm-DDA#39517]
# Is your feature request related to a problem? Please describe.
Since #37450 introduced activity_actor as the preferred method to create activities, PLAYER_ACTIVITY.md has been out of date, as it describes how to add new activities using the old method.

# Describe the solution you'd like
Update PLAYER_ACTIVITY.md to reflect the new activity_actor system.

# Describe alternatives you've considered
Not documenting the changes in the /doc/ folder.

**Comment by Night-Pryanik** [comment]
Closed by #39636.
