### ISSUE TITLE
Too easy to destroy military turrets by smashing them with a car

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#39519]
Military turrets (especially the anti-materiel ones) should aggressively attack incoming vehicles. Otherwise looting some machine guns and a few thousands of bullets from a military outpost is available to any character that can manage to find a working car.

**Comment by mlangsdorf** [comment]
vehicles can't currently be targeted by monster or NPC AI and fixing that is on my to-do list but is not a trivial project.
