### ISSUE TITLE
Game crashes when installing battery onto solar-rig

### ISSUE THREAD

**Issue by AHolmen** [CleverRaven/Cataclysm-DDA#39522]
# Describe the bug
Whenever i install my car battery onto the solar-rig, the game crashes.

# Steps To Reproduce
build a rig with following items. "#" are wooden frames. (see the provided image for info)

#(x3) from left to right: solar panel, upgraded solar panel
#upgraded solar panel
#upgraded solar panel, controls, car alternator, el controls, recharging station, seat, 0,4l 1-c engine and a 2l tank.

_After this is built, install a car battery in one of the tiles, it will crash and make this error:_
![bilde](https://user-images.githubusercontent.com/54939555/79105765-97d02b00-7d71-11ea-9754-d4f30b735c46.png)

# Expected behavior
The rig should have my battery installed without issues...

# crash log:
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4468764/crash.log)

# Screenshots
![bilde](https://user-images.githubusercontent.com/54939555/79105940-e1b91100-7d71-11ea-8e62-80d72a4f3517.png)

# Settings
 - OS: Windows 10 64 bit
 - Game Version: 0.E-605-g6ffb278
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: DDA, Disable NPC needs, Alternative map, no fungal monsters, stats through skills

**Comment by AHolmen** [comment]
It seems like it also crashes when I install the battery onto my bicycle.

**Comment by ampersand55** [comment]
I've also encountered a similar battery install crash, but I couldn't reproduce it reliably. 

I remember that it worked when installing the battery from inventory, but crashed when the battery was on the ground.

**Comment by AHolmen** [comment]
Update:
It seems like it crashes when installing the battery from "thin air". What is meant by "thin air" is that it's neither in my inventory or in my surrounding areas.

**Comment by AHolmen** [comment]
![bilde](https://user-images.githubusercontent.com/54939555/79109986-c94cf480-7d79-11ea-8573-4c5e1d0710bf.png)
![bilde](https://user-images.githubusercontent.com/54939555/79110040-dd90f180-7d79-11ea-9743-4245e6981635.png)

**Comment by Qrox** [comment]
Could you provide a save that reproduces the crash or test if #39566 fixes the crash?

**Comment by AHolmen** [comment]
Issue is now resolved.

**Comment by ZhilkinSerg** [comment]
Thanks for confirmation.
