### ISSUE TITLE
Alphabetic ordering of weapons in martial arts description

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#39529]
# Is your feature request related to a problem? Please describe.
It is more QoL request than problem fix. Some martial arts have many many weapons they work with, especially if you add mods to the picture. Kinda hard to find if a weapon works with MA or not when the list is unordered.

# Describe the solution you'd like
Alphabetic ordering of compatible weapons list. Surely it's better than no ordering at all.

# Describe alternatives you've considered
Continue searching for needles in a haystack each time you want to check weapon/MA compatibility.

**Comment by Pupsi-Mupsi** [comment]
I know that this is not a solution. More kind of a workaround.

Consider searching for the right weapon - use the crafting menu like this:
![grafik](https://user-images.githubusercontent.com/44737997/79624993-091f2d80-8126-11ea-9e66-5fb83226a49e.png)

Also:

Recipes and items indicate the martial art style with which they could be used.
Take a look at: #39653

**Comment by GGgatherer** [comment]
I agree it is helpful but it applies to craftable weapons only.
I know you can look at the weapon to know which MAs it can be used with but there are not so many MAs to populate those lists, so even if they are unsorted(are they? I honestly never noticed if they are) it isn't much of a problem to look through them. It's the other way around (weapons compatible with MA) that's irritating to use.

Also, I checked martialarts.cpp and it doesn't seem to relate on any specific ordering of "weapons" array which is used to populate used weapons list (would be strange if it did when there's no ordering anyway).
So adding sort command to the end of martialart::load should fix the issue.
