### ISSUE TITLE
notes, books and filters

### ISSUE THREAD

**Issue by Sijko** [CleverRaven/Cataclysm-DDA#39526]
# Is your feature request related to a problem? Please describe.

 i am always frustrated stupidly wasting time in survival games

# Describe the solution you'd like
I would like ask you to add to the game the following features:
-----------Notes and Books

1. add pencil recipe (wood+coal+clay)
1.1 add the ability to write readable notes with the pencil on paper and giving that piece of paper a custom item name, like a book's name
or
1. add a custom book recipe
1.1 attaching 1 paper to a book adds 1 page to it.
1.2. each page can contain 65k symbols
1.3. i see the ui of the book same as the "/" menu
or
1. add a new recipe, like, survivor's laptop
1.1. add the ability to write readable notes
1.1.1. a subfolders system, to not clutter up the screen
1.1.2. 1 file per folder
1.1.3 the access system can be the same as ingame PC's

a bit of formatting (?) like:  B, I, U,  <-, ->, <->, etc.
consider to let us save these notes across the games (and across worlds!!!), for ex. in the templates folder, so when a new char is created we can add these notes in that screen, so the survivor will have this book or notes, or laptop from the start.

--------------------Filters
let us save the custom loot zone filter sets, and choose them in any game, so a player can save time typing all those words every time...

-------------------Filters+
make the craft menu "m:no" command a saving toogle, or add a new submenu to the "*" tab with the unlearned recipes

**Comment by mlangsdorf** [comment]
This is an open source game, you can add new recipes yourself:
https://github.com/CleverRaven/Cataclysm-DDA/wiki/Guide-to-adding-new-content-to-CDDA-for-first-time-contributors

**Comment by Sijko** [comment]
as you can see, this is about functionality and not about recipes
