### ISSUE TITLE
update_zombie_pos: wanted to move the blob to 86,89,0, but new location already has the small blob

### ISSUE THREAD

**Issue by TempestMaiden** [CleverRaven/Cataclysm-DDA#39545]
# Describe the bug

I'm getting a spammy error message in my most recent game, looks like something similar to a bug that was fixed before the 0.E release:

 DEBUG    : update_zombie_pos: wanted to move the blob to 86,89,0, but new location already has the small blob

 FUNCTION : bool Creature_tracker::update_pos(const monster&, const tripoint&)
 FILE     : src/creature_tracker.cpp
 LINE     : 127

I've gotten a related error once on load involving two blobs occupying the same space.

It's not a crash or anything, the "continue" option has worked just fine every time it's popped up so far, but it's happening often enough to be annoying.

It _may_ be related to my leading a security zombie into a blob trap and shutting the door behind me.

# Steps To Reproduce

Not sure what's causing the error, so I've no idea how to reproduce it in a new game.

# Expected behavior

Gameplay shouldn't be regularly interrupted by an error message.

# Versions and configuration

 OS: Windows 10 Home
 - Game Version: [0.E] (there's no further string listed; it's the stable.)
 - Graphics version: [Tiles]
 - Ingame language: [English]
 - Mods loaded: [core DDA, disable NPC needs]
 
# Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4472291/debug.log)
ped)
[Camelot.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4472295/Camelot.zip)

**Comment by TempestMaiden** [comment]
Ok, correction: _now_ it's crashed.

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4472334/crash.log)

**Comment by wapcaplet** [comment]
Sounds like #37683 again, which was resolved by #38497, but perhaps this example has a different root cause.
