### ISSUE TITLE
Broken Vehicle Unloading 2 - Mechanic Boogalo

### ISSUE THREAD

**Issue by MXSteel** [CleverRaven/Cataclysm-DDA#39542]
# Describe the bug

A while back, in 0.D, I had a bug with [vehicle crashing upon unloading](https://github.com/CleverRaven/Cataclysm-DDA/issues/36468).  

It would seem a glitch of the same nature has surfaced again.

[Here](https://drive.google.com/file/d/1QNuzPeEfoUW-N-7LF_c0eM0z0EYlH0F4/view?usp=sharing) is a save of the relevant map tile.  
On this save, you can find a vehicle called Doomobile, with an attached motorcycle.  
The problem is, once you try to unload the motorcycle, one of its tiles stays on the main vehicle.

# Steps To Reproduce

I honestly don't know, but it's possible the frame on that motorcycle tile somehow broke (before all other stuff) while the motorcycle was attached, and it somehow made that specific tile count as a new vehicle?

# Expected behavior

Well, obviously, the whole motorcycle unloading.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on ~~unknown Windows version~~ (actually is 7)
- Game Version: 0.D-13426-ge603140 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by Qrox** [comment]
See #29167, Was the problematic tile added after the motorcycle was attached?

**Comment by MXSteel** [comment]
Funny enough (if you load that map area you'll visually see what I'm talking about), the spiked ram at was "added to the motorcycle after it was attached". 
In reality, it was added to the main vehicle, and was never registered as part of the motorcycle to begin with (as there wasn't even a bike rack at the location it was added). It was, however, added in adjacently to the attached motorcycle - but the tile that stayed on the vehicle was actually 2 tiles away. 
In fact, when you unload the cycle, it unloads in a split state - the offending block that stays laoded is in position [0 1], while the unloaded ones are [0 -1] [0 0] and [0 2], and the spike would be [0 3] but it's actually a part of the main vehicle.
