### ISSUE TITLE
Zombie Children should drop clothing that can only properly fit small, tiny, and unassuming characters.

### ISSUE THREAD

**Issue by Vostokapollo** [CleverRaven/Cataclysm-DDA#39543]
### Problem 1
Characters that have mutations relating to the rodent tree have very limited access to clothing without leveling up the tailor skill.

### Problem 2
Children drop clothing that often fit full-sized characters, despite the game describing them as being "the size of a dog".

### Solution
Set Zombie Child to wear clothing sets in the rodent mutation size range (small, tiny, unassuming).

**Comment by Jerimee** [comment]
Is this a json only fix? 

And/or a good first issue?

**Comment by Vostokapollo** [comment]
It looks like pull request #39514 could be used to accomplish this goal very easily. So maybe a json fix? 

I don't have the skill or access to the tools (trapped in the nightmarescape that is being computerless), so I figured I'd beseech the community on this (honestly pretty old) issue

**Comment by wapcaplet** [comment]
> It looks like pull request #39514 could be used to accomplish this goal very easily.

That pull request only relates to the test cases for height mutations. I’m afraid it does not have any bearing on item drop rates or clothing sizes.
