### ISSUE TITLE
Vehicle-mounted turrets always shoot from driver's seat instead of their own place

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#39557]
# Describe the bug

When trying to shoot a turret (or when it shoots on autotarget) source point of the shot is driver's seat, not the actual turret emplacement.

# Steps To Reproduce

Make a vehicle, install a turret anywhere but driver seat(where vehicle controls are), try shooting it, see where cursor points *from*.

# Expected behavior

Turrets shooting from the places at which they actually reside.

# Versions and configuration

- OS: Windows 7x64
- Game Version: 0.E-635-gef0197a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Aftershock [aftershock],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills],
    Magiclysm [magiclysm]
]

# Additional context

Different from #39445, but military vehicles have armored walls in most directions from driver's seat, so it is probably 2 sides of 1 ugly coin.

Also, seems to be a resurfacing of #22512.

**Comment by olanti-p** [comment]
Actually, this is just a visual bug.
Aiming interface always draws trajectory from the player's position to where they aim at; when actually firing, each turret calculates its own trajectory and fires from its own position.

I'll make a fix for this one

**Comment by GGgatherer** [comment]
Are you absolutely sure about that? Because I could swear turrets were previously showing bullet trajectory originating from their own tiles.

**Comment by olanti-p** [comment]
They still do. Here's me shooting a turret from vehicle controls:
![cdda_fire](https://user-images.githubusercontent.com/60584843/80130482-54f82980-85a1-11ea-9eb6-b1221030bad6.gif)
You can see the bullets coming out of the turret and destroying the wall, despite target selection UI drawing the line from your seat.
