### ISSUE TITLE
Electric chainsaw, too high energy drain and behaves unrealistically.

### ISSUE THREAD

**Issue by ampersand55** [CleverRaven/Cataclysm-DDA#39560]
# Describe the bug

1. Electric chainsaw drains 750-800 battery per use. It comes with a medium battery (500) so you immediately run out of charges after using it once. See #32503.
2. Electric chainsaw should not draw power constantly like a gasoline powered chainsaw, only when you use it. See #35203.

# Steps To Reproduce

Make a survivor, spawn an electric chainsaw, use it.

# Additional context

I was working on what I thought was an easy fix, but I encountered some problems related to using chainsaw as a weapon. 

See https://github.com/CleverRaven/Cataclysm-DDA/compare/master...ampersand55:fix_electric_chainsaw

This fixes both problems outlined in the description, but it introduces new problems with using chainsaw as a weapon.

My first idea was  to make `"chainsaw_on"` a "weapon mode", and have that draw power continuously over time. The problem is that it draws `"charges_per_use"` when you activate it (i.e. turns it into weapon mode) which is set to 1/4 of its total charge. It also makes it inconsistent with `"electric combat chainsaw"` and `"electric chainsaw lajatang"`.

Some random brainstorming ideas:

1. make some c++ changes to allow use_action to not consume charges.
2.  to remove the usage of the "electric chainsaw" as a weapon entirely, and require a conversion to an "electric combat chainsaw" for use as a weapon
3. make it a ranged weapon with range 1 and have it consume battery "ammo" as you use it. 
4. remove all the chainsaw weapons entirely. 
5. accept the initial activation cost for switching to "weapon mode".

Btw, `"electric combat chainsaw"` only has ~3 minutes of use. Regular `"combat chainsaw"` has 30 minutes of use. Is this an oversight?

Sorry for the mess of an issue.

**Comment by mrkybe** [comment]
> Btw, "electric combat chainsaw" only has ~3 minutes of use. Regular "combat chainsaw" has 30 minutes of use. Is this an oversight?

Gasoline is far more energy dense than batteries.  Not sure about the weight proportions between the two chainsaws though.

**Comment by ampersand55** [comment]
True, but electric chainsaws tend to have larger batteries to make up for that. 

I think the main problem is that we assume the chain saws running at full effect for the entire duration. This is rarely the case, and electric motors don't have any energy drain when idle. You could argue that they should be on constant max effect when being used in e.g. "electric chainsaw lajatangs". But not in normal tool usage. It's hard to balance tool use and weapon use, which is my main point.

The electric chain saw has a "power_draw" of 2000000 mW, i.e. 2 kW, which is consistent with my calculations from the previous issue:

* https://github.com/CleverRaven/Cataclysm-DDA/issues/32503#issuecomment-513558844

This chain saw:

* https://www.stihlusa.com/products/chain-saws/battery-saws/msa200cbq/

... has a listed "operating time" of 15 minutes with a AP 100 battery, which should only be 2m 48s at max effect. 

* Battery:  https://www.stihlusa.com/products/accessories/batteries-and-accessories/ap100redesign/
* Math:  https://www.wolframalpha.com/input/?i=2.6+Ampere+h+*+36+v+%2F+2+kW
