### ISSUE TITLE
Ranged weapons can't crit

### ISSUE THREAD

**Issue by ampersand55** [CleverRaven/Cataclysm-DDA#39565]
# Describe the bug

Ranged weapons can't crit. This either makes the changes in #39203 a more severe nerf than intended, or the item description is misleading.

# Steps To Reproduce

1. Make a survivor with archery and marksman skill 10+
2. Spawn a longbow and a bunch of wooden broadhead arrows.
3. Spawn a debug monster
4. Shoot at it with [p]recise aim from point blank range

# Expected behavior

It says in the item description:

Ranged damage: 5x1.5 = 8
Critical multiplier: 10

I interpret that as I should expect to occasionally do 8x10=80 damage as I crit. But I never seem to crit. The best I get is "good hit!" for 17-25 damage.

# Screenshots

![image](https://user-images.githubusercontent.com/9817636/79247466-df8ea980-7e7a-11ea-9c0c-544968590863.png)

![image](https://user-images.githubusercontent.com/9817636/79245955-2085be80-7e79-11ea-8f44-dfdf1b912f6b.png)

# Versions and configuration

```

- OS: Windows
    - OS Version: 10.0 1607
- Game Version: 0.E-680-g668e469 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]
```

# Additional context

https://redd.it/g10dod

**Comment by kevingranade** [comment]
Crits need to deal a significant fraction of the target's HP to trigger now, the debug monster has 10000HP.
