### ISSUE TITLE
Mess kits with loaded batteries lose boiling quality.

### ISSUE THREAD

**Issue by Dacendeth** [CleverRaven/Cataclysm-DDA#39567]
# Describe the bug
While a mess kit or military mess kit has a battery in it, it's boiling quality is not able to be used for crafting, similiar to how a teapot cant be used for boiling when it has a liquid in it the batteries are seemingly being counted just the same. Survivor mess kit works just fine.

# Steps To Reproduce
Spawn a mess kit, try to boil some water wth it.

# Expected behavior
For a battery to not somehow get in the way of boiling.

# Screenshots
![image](https://user-images.githubusercontent.com/26881007/79258286-ed333780-7e58-11ea-916c-d25e50ddf257.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-689-g32e6aab [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

**Comment by wapcaplet** [comment]
Trying to reproduce this today, I have the opposite issue. The regular "mess kit" has boiling quality, with or without batteries; however, the "survivor mess kit" curiously has its boiling quality *only* when it is out of fuel.

With a fully-loaded survivor mess kit, the crafting menu shows my charged mess kit, but says I have no tools with boiling quality:

![image](https://user-images.githubusercontent.com/238395/83331664-a2c51900-a254-11ea-8469-069f9f2f3ce0.png)

When the fuel is empty, I have the boiling quality - but no charges:

![image](https://user-images.githubusercontent.com/238395/83331661-9b9e0b00-a254-11ea-8366-abd563c57d2e.png)

Note, a player on discord brought up a similar issue today, that may have the same cause - the "survivor utility belt" loses all its qualities (for the purpose of crafting) when a knife is put into the sheath. And when no tool is in the sheath, all the belt's qualities become available again.
