### ISSUE TITLE
Can install multiple alternators on a single engine

### ISSUE THREAD

**Issue by OddSkollar** [CleverRaven/Cataclysm-DDA#39578]
# Describe the bug
Player is able to attach multiple alternators to an engine with the E_ALTERNATOR flag.

# Steps To Reproduce
Install multiple alternators. 

# Expected behavior
Should have an error message similar to that if a player attempts to install multiple turrets on the same slot.

# Screenshots
![image](https://user-images.githubusercontent.com/63127974/79289414-66954f00-7e86-11ea-9dcc-0023922c9b00.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-439-gdf00ef1ba6-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    TESTING DATA [test_data]
]

# Additional context
Currently addressing this myself as part of implementation of a new feature which will be PRed soon, just want a paper trail in case I mess it up horribly.

**Comment by l29ah** [comment]
I don't see how is this unbalanced or unrealistic.

**Comment by mlangsdorf** [comment]
Not a bug, working as intended.  You can run multiple alternators off different drive belts driven by the same drive shaft.
