### ISSUE TITLE
Hello, I am first time working at github, and having a problem right now

### ISSUE THREAD

**Issue by martinrhan** [CleverRaven/Cataclysm-DDA#39574]
I downloaded the codes and opened the solution with VS, however all the .cpp and .h scripts are full of errors, red wavy lines under the codes. Why is it like this? Am I missing something?

**Comment by anothersimulacrum** [comment]
Did you follow the [VS instructions](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/COMPILING/COMPILING-VS-VCPKG.md)?

**Comment by martinrhan** [comment]
> Did you follow the [VS instructions](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/COMPILING/COMPILING-VS-VCPKG.md)?

I cannot get it done. It says “Install and configure vcpkg using instruction from vcpkg homepage with following command line”， what does that mean? Does it means copy and paste into CMD?
But that is not valid. I have already installed vcpkg by clone the reposit to my local computer and runned bootstrap-vcpkg.bat what is the next thing to do?

**Comment by ZhilkinSerg** [comment]
> 
> 
> > Did you follow the [VS instructions](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/COMPILING/COMPILING-VS-VCPKG.md)?
> 
> I cannot get it done. It says “Install and configure vcpkg using instruction from vcpkg homepage with following command line”， what does that mean? Does it means copy and paste into CMD?
> But that is not valid. I have already installed vcpkg by clone the reposit to my local computer and runned bootstrap-vcpkg.bat what is the next thing to do?

You need to follow remaining steps of the [guide](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/COMPILING/COMPILING-VS-VCPKG.md) - i.e. run commands after `.\bootstrap-vcpkg.bat`. Continue with  `.\vcpkg integrate install` from step 3, then proceed with `.\vcpkg --triplet x64-windows-static install sdl2 sdl2-image sdl2-mixer[dynamic-load,libflac,mpg123,libmodplug,libvorbis] sdl2-ttf gettext` from step 4 and so on.

**Comment by martinrhan** [comment]
> > > Did you follow the [VS instructions](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/COMPILING/COMPILING-VS-VCPKG.md)?
> > 
> > 
> > I cannot get it done. It says “Install and configure vcpkg using instruction from vcpkg homepage with following command line”， what does that mean? Does it means copy and paste into CMD?
> > But that is not valid. I have already installed vcpkg by clone the reposit to my local computer and runned bootstrap-vcpkg.bat what is the next thing to do?
> 
> You need to follow remaining steps of the [guide](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/COMPILING/COMPILING-VS-VCPKG.md) - i.e. run commands after `.\bootstrap-vcpkg.bat`. Continue with `.\vcpkg integrate install` from step 3, then proceed with `.\vcpkg --triplet x64-windows-static install sdl2 sdl2-image sdl2-mixer[dynamic-load,libflac,mpg123,libmodplug,libvorbis] sdl2-ttf gettext` from step 4 and so on.

how to run commands

**Comment by ZhilkinSerg** [comment]
You start command line processor (e.g. `cmd.exe`), type in (or paste) a command in a prompt and press `ENTER` to execute entered command.

Use https://en.wikipedia.org/wiki/Cmd.exe and https://web.archive.org/web/20150422041137/http://windows.microsoft.com/en-us/windows/command-prompt-faq#1TC=windows-7 for more detailed reference.

**Comment by martinrhan** [comment]
> You start command line processor (e.g. `cmd.exe`), type in (or paste) a command in a prompt and press `ENTER` to execute entered command.
> 
> Use https://en.wikipedia.org/wiki/Cmd.exe and https://web.archive.org/web/20150422041137/http://windows.microsoft.com/en-us/windows/command-prompt-faq#1TC=windows-7 for more detailed reference.

that's exactly what i have done, but the CMD told me it is not command and not executable nor bat

**Comment by ZhilkinSerg** [comment]
Make sure you are running all commands from vcpkg install directory.

**Comment by martinrhan** [comment]
> Make sure you are running all commands from vcpkg install directory.

I think my problem is solved, thank you for you help. I realized that I cannot just simply copy and paste as the cmd cannot identify command "cd vcpkg". In stead I should write a complete directory there.

**Comment by ZhilkinSerg** [comment]
You can use relative paths if you switched to base folder first, e.g.:

```
cd C:\Projects\
cd vcpkg
```

should be equal to:

```
cd C:\Projects\vcpkg
```
