### ISSUE TITLE
Zoom level being reset each load

### ISSUE THREAD

**Issue by crazykid080** [CleverRaven/Cataclysm-DDA#39572]
# Is your feature request related to a problem? Please describe.
Each time I load my game, the zoom level is reset and I have to manually change the zoom level back to what it was before.

# Describe the solution you'd like
The ability for the game to save the zoom level on load

# Describe alternatives you've considered
Resign myself to pressing z to fix it every time I load the game

**Comment by jesus-ramos** [comment]
https://github.com/jesus-ramos/Cataclysm-DDA/commit/560810a633baa5e0de3b4ad186f8e934ff7b0436

Pretty simple to add to always do it, are there times we don't want to save it?
