### ISSUE TITLE
Dehydrated mutant meat loses toxin on further cooking

### ISSUE THREAD

**Issue by Miner239** [CleverRaven/Cataclysm-DDA#39586]
# Describe the bug

Food cooked with dehydrated mutant meat does not inherit toxin from the mutant meat and is safe to consume. 

# Steps To Reproduce

1. Get mutant meat
2. Dehydrate half of the mutant meat
3. Cook a meat-using recipe twice, once with raw mutant meat, once with dehydrated version
4. Compare results

# Expected behavior

Both cooked food have toxin.

# Screenshots

![toxinbug](https://user-images.githubusercontent.com/4686046/79341072-6c0d9a80-7f55-11ea-81d7-18a9a1311383.png)

# Versions and configuration

Version: 0.E-719-g14415de (tiles)
Mods: dda

# Additional context

**Comment by int-ua** [comment]
Did you dehydrate it on a smoking rack? I've noticed odd behavior when mixing default meat with mutant one where whole batch turned into one of these after drying. I bet it's drying that [errorneously] removes toxins, not cooking. Please update the title if my assumption is correct.

**Comment by Miner239** [comment]
I obtained the meat from debug menu, then used a dehydrator to craft the dried mutant meat. There are no normal meat involved in the screenshot, the dehydrated mutant meat magically turns normal. I'd love to have someone else reproduce it and tell me it's just me...

**Comment by Miner239** [comment]
I can't reproduce this in build 10642.
