### ISSUE TITLE
Error while doing missions for Hub 01

### ISSUE THREAD

**Issue by Buteogallus** [CleverRaven/Cataclysm-DDA#39599]
# Describe the bug

I was talking to the Intercom of Hub 01 when the game suddenly crashed. I was giving him the item from the second mission and then the game crashed. I found a second Hub 01 facility and the map marked it as the one where i should end the mission.

# Steps To Reproduce

# Screenshots

# Versions and configuration

# Additional context

**Comment by Qrox** [comment]
Sounds like #39507. Please update to the newest experimental and see if the crash is fixed.

**Comment by Night-Pryanik** [comment]
No confirmation in a year. Closing.
