### ISSUE TITLE
Error: Item battery_ups was loaded with charges, but can not have any!

### ISSUE THREAD

**Issue by githubuser343** [CleverRaven/Cataclysm-DDA#39591]
# Describe the bug

 DEBUG    : Item battery_ups was loaded with charges, but can not have any!

 FUNCTION : void item::io(Archive&) [with Archive = io::JsonObjectInputArchive]
 FILE     : src/savegame_json.cpp
 LINE     : 2363

# Steps To Reproduce

1. Have a UPS loaded with high capacity heavy battery
2. Have a UPS modded mp3 player turned on in inventory
3. Save and load game, wait a while

# Versions and configuration

0.E stable.

**Comment by Pupsi-Mupsi** [comment]
Related to #39434
