### ISSUE TITLE
Some foods are not classified

### ISSUE THREAD

**Issue by 939839415** [CleverRaven/Cataclysm-DDA#39608]
# Describe the bug

Some foods are not classified, such as ghee, and can only be retrieved in the "all" category under the food category at the time of manufacture.I accessed the data，the ghee shows 
SubCategory: CSC_FOOD_DAIRY
which doesn't shows under the "food"category,Causes ghee to be seen only in “all" categories
which  caused some pain  of understanding 

# Steps To Reproduce

get the book《Cooking on a Budget (level 1)》
Start making ghee

# Expected behavior

Ghee is classified into one of the subcategories

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro]

# Additional context

**Comment by int-ua** [comment]
Do you mean the crafting dialog?
