### ISSUE TITLE
Crash as I try to craft a toolbox 

### ISSUE THREAD

**Issue by Zukulini** [CleverRaven/Cataclysm-DDA#39618]
# When I attempt to craft a toolbox, the game crashes.

# Steps To Reproduce

1. Go into the crafting menu with $.
2. Search for "toolbox" and attempt to craft it.
3. The game will crash. 

# Expected behavior

The game will crash, and I don't have the knowledge to explain why.

# Screenshots
![image](https://user-images.githubusercontent.com/26130816/79517478-f0beee00-8013-11ea-9155-7d3490997f98.png)

# Versions and configuration

Please complete the following information; you can now go to:

- OS: Windows 7
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-583-g5619799 [64-bit]
- Graphics Version: Tiles (UnDeadPeople)
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations],
    Graphical Overmap [Graphical_Overmap],
    Bionic Slots [cbm_slots],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]
    

# Additional context
I have set up the save file so that you can immediately attempt to craft the toolbox!

[crash and debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4490216/crash.and.debug.zip)
[Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4490220/Save.zip)

**Comment by Qrox** [comment]
The crash log looks similar to the one in #39509. Please update to the newest experimental and see if it's already fixed.

**Comment by Zukulini** [comment]
Updating solved the issue! Thank you!
