### ISSUE TITLE
CDDA won't load a world with Secronom installed

### ISSUE THREAD

**Issue by Crhodes92** [CleverRaven/Cataclysm-DDA#39634]
# Upon installing secronom, I get a JSON parsing error for Anesthesia. This does not occur until Secronom gets installed. I suspect it has something to do with the item being called Anesthesia kit" now. Granted, it's been a while since I've played. 

# Steps To Reproduce

1. Use the launcher to load up the most recent experimental
2. Create a world with Secronom installed (other mods ok but better to isolate the issue) 
3. Try to create a character in the world and the game will give a JSON parsing error when loading anesthesia when it hits Mapgen Weights. 

# Expected behavior

I'd like the game to load with secronom 

# Screenshots

"https://user-images.githubusercontent.com/39782316/79575670-be4ed880-8087-11ea-91f9-e289a59cc39d.PNG"

Do not take a screenshot of the crashing window. Please provide the crash logs in the "Additional context" 

# Versions and configuration

-- Please complete the following information; you can now go to:
    - "Main menu (ESC) > Debug Menu > Info > Generate game report" to generate this report.
    - Please update your OS version with a more precise version.

"https://user-images.githubusercontent.com/39782316/79575822-fa823900-8087-11ea-9690-84f148a9f23e.PNG"

 - OS: Windows 10 Home, version 1903
 - Game Version: see screenshot
 - Graphics version: TIles
- Ingame language: English
 - Mods loaded: Secronom

**Comment by Fris0uman** [comment]
Secronom is a third party mod, we can't help you with that. Try to update your mod.

**Comment by Crhodes92** [comment]
Ok, thank you for the quick response. Still learning here.
