### ISSUE TITLE
Woodbow from Magiclysm gives an error when it expires

### ISSUE THREAD

**Issue by olanti-p** [CleverRaven/Cataclysm-DDA#39655]
# Describe the bug
Bow spawned by `Nature's bow` spell from Magiclysm gives an error when it expires

# Steps To Reproduce
1. Debug spawn `Scroll of Nature's Bow`
2. Learn the spell
3. Cast the spell
4. See `Woodbow (100 turns)` in your hands
5. Wait for 100 turns

# Expected behavior
No errors

# Screenshots
![image](https://user-images.githubusercontent.com/60584843/79624404-0d4d4a00-812a-11ea-82b7-5d0e1f1d0128.png)

# Versions and configuration
- OS: Linux
    - OS Version: Ubuntu 19.10; Release: 19.10; Codename: eoan; 
- Game Version: 8786b2bf4599dd887e2df81d5a8d9d16ee1d7889 [64-bit]
- Graphics Version: Curses
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm]
]

# Additional context
[backtrace.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4495796/backtrace.log)

**Comment by HarrisonGreenlee** [comment]
I was able to reproduce this bug on Windows 10.

While testing I noticed that Nature's Bow, Finger Firelighter, Wicked Bonespear, Magical Light, and Conjure Throwing Blade 1 also have this issue. The bug appears to affect all spawned items when they try to despawn.

Note: summoned items that do not despawn (ie. crystallized mana) do not cause any errors.

**Comment by olanti-p** [comment]
This may actually be a duplicate of #39402

**Comment by olanti-p** [comment]
Fixed by #40098
