### ISSUE TITLE
Mission "Recruit Tracker" impossible to complete

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#39657]
# Describe the bug

I have found the NPC at the coordinates, gave him deputy badge, he looks like he is my "regular" follower(i.e. normal follower dialogue, and all follower-related actions are available), but quest giver doesn't recognize it - my character can only say "not yet" in regards to quest state.

# Steps To Reproduce

1. Load [attached save](https://drive.google.com/open?id=1R3Rl_BCpta1vDJf5ZxjdSomB8J6MMh4W), it's at the point where I have just recruited target NPC but didn't complete his own mission yet.
2. Either give him a badge straight away, or drive to the farm southeast and give him one from the pile.
3. At this point, he looks like he becomes regular follower but he does have "asked to follow" effect which states in its description it is a bug if we see it.
4. Drive to the farm if you haven't done it yet, or just TP there and speak to NPC in south-eastern bed, he won't recognize mission completion.

# Expected behavior

Quest giver recognizing new recruit he asked for.

# Versions and configuration

- OS: Windows 7x64
- Game Version: 0.E-769-ge90cc91 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Aftershock [aftershock],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills],
    Magiclysm [magiclysm]
]

**Comment by UristMcSharkbait** [comment]
Poking through the .json, this would be fixed by just changing
`"goal": "MGOAL_RECRUIT_NPC_CLASS"`
to
`"goal": "MGOAL_RECRUIT_NPC"`

**Comment by GGgatherer** [comment]
*tips hat* You are absolutely right, sir. It does indeed fixes it. Although the "gunslinger" still have "asked to follow" effect.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/tips-tricks-and-newb-questions-reborn/16870/2413
