### ISSUE TITLE
Military Bunker Turrets Still Hostile After Swiping Military ID

### ISSUE THREAD

**Issue by GordanGeeko** [CleverRaven/Cataclysm-DDA#39661]
Game version: 10536

Operating system: Windows 10

Tiles or curses: Tiles

Mods active: Aftershock, C.R.I.T, More Survival Tools, Craftable Gun Pack, Icecoon's Arsenal, makeshift Items Mod, Disable NPC Needs, Craft Ammo Mags & Belt Links, Medieval and Historical Classes and Shields, Alternative Map Key, Mutant NPCs, Folding Parts pack, No Fungal Monsters, Garden Pots, Packaging, Modular Turrets, Manual Bionic Installation, More  City Locations, Necromancy, Bootleg Walkers, Gun Cotton, Mining Mod

### Steps to reproduce the behavior: Find a military bunker,  swipe a Military ID card in the front door reader, enter and see that turrets are still active and hostile to the player.

Included Save file.

[Mabscott.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4496007/Mabscott.zip)

**Comment by anothersimulacrum** [comment]
This is a bug with modular turrets, which is an unsupported mod.

**Comment by Positronic-Girl** [comment]
Hey going to be upfront: Your issue is probably in that fact that some of your mods that you have are deprecated and obsolete. They were obsoleted for not being maintained and are very buggy; and it seems that you have Modular Turrets which, I'd imagine might be interfering with the current vanilla turrets in the military bunker.

**Comment by GordanGeeko** [comment]
Yeah that was it, I tried removing it and it worked. What else of the mods I have are no longer supported?

**Comment by anothersimulacrum** [comment]
#### Supported:
Aftershock, C.R.I.T, Disable NPC Needs, Alternative Map Key, No Fungal Monsters,

#### Unsupported:
More Survival Tools, Craftable Gun Pack, Icecoon's Arsenal, makeshift Items Mod, Medieval and Historical Classes and Shields,  Mutant NPCs, Folding Parts pack,  Garden Pots,  Modular Turrets, Manual Bionic Installation, More City Locations, Necromancy,

#### Third Party:
Craft Ammo Mags & Belt Links, Packaging, Bootleg Walkers, Gun Cotton, Mining Mod
