### ISSUE TITLE
locale on musl libc library is not working

### ISSUE THREAD

**Issue by nniixxoossccnn** [CleverRaven/Cataclysm-DDA#39673]
Game version: 0.E (stable)

Operating system:  Alpine Linux 3.11

Tiles or curses: curses 

Mods active:

### Expected behavior

It can display Chinese correctly

### Actual behavior

It is not displayed correctly

### Steps to reproduce the behavior

this is my command to compile and install:

```

OPTS="RELEASE=1 LOCALIZE=1 USE_HOME_DIR=1 ASTYLE=1 PREFIX=/usr BACKTRACE=0 CCACHE=1"


make ${OPTS} || exit 1


make localization LANGUAGES="zh_CN zh_TW" ${OPTS} || exit 1


mkdir -pv ${PKG_DIR}/usr/share/locale || exit 1
cp -r ./lang/mo/* ${PKG_DIR}/usr/share/locale/ || exit 1

make ${OPTS} DESTDIR=${PKG_DIR} install || exit 1
```

When I run cataclysmdda, its multilingual display is like the LANG variable is not set correctly on Glibc

I saw it at the moment of starting:
```
You don't seem to have a valid Unicode locale. You may see some weird characters warned.empty boxes or question marks). You have been
```

**Comment by Qrox** [comment]
This also happens on MSYS2, but I'm not sure why it's happening.

**Comment by BrettDong** [comment]
`nl_langinfo(CODESET)` returns `ASCII` instead of expected `UTF-8` on a fresh installed Alpine Linux:
```c
~/Cataclysm-DDA-master # cat locale.c
#include <stdio.h>
#include <langinfo.h>

int main() {
    printf("%s\n", nl_langinfo(CODESET));
    return 0;
}
~/Cataclysm-DDA-master # cc locale.c -o locale && ./locale
ASCII
```

And that [triggers the warning](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/ncurses_def.cpp#L440) you saw in the game:
```c
if( std::strcmp( nl_langinfo( CODESET ), "UTF-8" ) != 0 ) {
        // do not use ui_adaptor here to avoid re-entry
        int key = ERR;
        do {
            const char *unicode_error_msg =
                _( "You don't seem to have a valid Unicode locale. You may see some weird "
                   "characters (e.g. empty boxes or question marks). You have been warned." );
```

Probably need to do some locale configurations to make it `UTF-8`

**Comment by BrettDong** [comment]
It is weird... even when `nl_langinfo(CODESET)` returns `UTF-8`
![螢幕截圖 2020-11-29 22 43 18](https://user-images.githubusercontent.com/21075502/100544981-4dfe6b80-3294-11eb-87f3-66316b92c32d.png)

**Comment by BrettDong** [comment]
Now I think the reason could, probably, be that locale in C++ standard library does not work well on Alpine Linux w/ musl. I wrote two demo code, first one in C and the second one in C++:
```c
#include <ncurses.h>
#include <langinfo.h>
#include <locale.h>
int main()
{
    setlocale(LC_ALL, "");
    initscr();
    printw("LC_ALL: %s\n", setlocale(LC_ALL, NULL));
    printw("CODESET: %s\n", nl_langinfo(CODESET));
    printw("Hello, world!\n");
    printw("你好，世界!\n");
    refresh();
    getch();
    endwin();
    return 0;
}
```
this program prints English and Chinese characters correctly:
![螢幕截圖 2020-11-30 00 56 11](https://user-images.githubusercontent.com/21075502/100548336-d8e86180-32a6-11eb-8f9a-4b6e9881de60.png)

Then I wrote a C++ version of the above program:
```c++
#include <ncurses.h>
#include <langinfo.h>
#include <locale.h>
#include <locale>
using namespace std;
int main()
{
    locale::global(locale(""));
    initscr();
    printw("LC_ALL: %s\n", setlocale(LC_ALL, NULL));
    printw("C++ locale: %s\n", locale().name().c_str());
    printw("CODESET: %s\n", nl_langinfo(CODESET));
    printw("Hello, world!\n");
    printw("你好，世界!\n");
    refresh();
    getch();
    endwin();
    return 0;
}
```
And this one cannot print the Chinese characters correctly:
![螢幕截圖 2020-11-30 01 01 41](https://user-images.githubusercontent.com/21075502/100548452-9d01cc00-32a7-11eb-9a1e-e64f3f755902.png)

When manually specify locale to be `C.UTF-8` through environment variable, an exception occur:
![螢幕截圖 2020-11-30 01 03 45](https://user-images.githubusercontent.com/21075502/100548504-e6eab200-32a7-11eb-9b00-e371539d3f91.png)

**Comment by BrettDong** [comment]
Seems libstdc++ only supports C locale with non-glibc:
https://www.openwall.com/lists/musl/2020/11/30/6

So I think there is nothing we can do to fix this issue.

**Comment by BrettDong** [comment]
Just received a solution [from musl mailing list](https://www.openwall.com/lists/musl/2020/11/30/7) so I write it down here for your reference:

1. Patch GCC with https://github.com/smaeul/portage/blob/c744774a/patches/sys-devel/gcc/gcc-5.4.0-locale.patch, line numbers may differ for newer GCC versions nowadays, anyway the patch is essentially removing the following lines in function `locale::facet::_S_create_c_locale(...)` in `libstdc++-v3/config/locale/generic/c_locale.cc`:

```c++
if (strcmp(__s, "C"))
      __throw_runtime_error(__N("locale::facet::_S_create_c_locale "
			    "name not valid"));
```

2. Build Cataclysm DDA with the patched `libstdc++`, for me I installed the patched GCC in `/opt/gcc` so my build command is `LDFLAGS='-L/opt/gcc/lib64 -Wl,-rpath=/opt/gcc/lib64' make LOCALIZE=1 NATIVE=linux64 BACKTRACE=0 GOLD=1 RELEASE=1`

3. Run Cataclysm DDA with `LANG=zh_CN.UTF-8 ./cataclysm` and, Hooray!

![螢幕截圖 2020-12-01 11 47 14](https://user-images.githubusercontent.com/21075502/100694883-f6165080-33ca-11eb-90d8-05deaa36a83b.png)
