### ISSUE TITLE
Grammar of Healing Notifications

### ISSUE THREAD

**Issue by CDDABen** [CleverRaven/Cataclysm-DDA#39675]
# Describe the bug

Upon healing, it's stated that "Bandaged/Disinfected wounds on your [body part] _was_ healed", as opposed to "_were_ healed". 

# Steps To Reproduce

1. Get injured.
2. Apply healing method.
3. Wait, or sleep, to prompt the healing notification to appear.

# Expected behavior

For it to be phrased as "Bandaged/Disinfected wounds on your [body part] _were_ healed", as the plural "wounds" is what the verb "was" is referring to.

# Screenshots

![image](https://user-images.githubusercontent.com/63902861/79634473-eb95a680-81ad-11ea-9a8b-6e68f20985c9.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-841-gbc93885 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    DinoMod [DinoMod],
    My Sweet Cataclysm [my_sweet_cataclysm]
]

# Additional context

**Comment by wapcaplet** [comment]
I am inclined to remove the word "was" entirely, as the word "healed" alone is sufficient:

"Bandaged wounds on your torso healed."
"Disinfected wounds on your arm healed."

To my eye, this phrasing gives a better sense that the wounds *just now* healed as the message was printed.
