### ISSUE TITLE
Need help with astyle in vs2019

### ISSUE THREAD

**Issue by Pupsi-Mupsi** [CleverRaven/Cataclysm-DDA#39689]
Can someone help me with how to get astyle 3.1 up and running.
I'm new to visual studio 2019 and would very much appreciate any help!

**Comment by anothersimulacrum** [comment]
Disclaimer: I don't use VS, and I'm not on windows, but I've seen this before.

There is an astyle extension for 2019, but it is not on the marketplace like the 2017 version. You can either build it from their github repo (https://github.com/lukamicoder/astyle-extension/releases), or if you trust downloading random zips on the internet, you can grab it from here https://github.com/lukamicoder/astyle-extension/issues/17#issuecomment-537814439.

Alternatively, you can download astyle from [it's website](http://astyle.sourceforge.net/), and use this bat file to run it
```sh
echo off
cd Cataclysm-DDA
astyle --options=.astylerc --recursive src/*.cpp,*.h tests/*.cpp,*.h
```

**Comment by Night-Pryanik** [comment]
https://github.com/lukamicoder/astyle-extension/files/3684809/AStyleExtension.zip worked for my VS2019.

**Comment by Pupsi-Mupsi** [comment]
@anothersimulacrum 
@Night-Pryanik 

**Thanks a lot. Worked fine!**

Did some testing. Loaded a file and formated it with astyle without changing anything.
Is this supposed to like this?
![grafik](https://user-images.githubusercontent.com/44737997/79644004-69ee4a80-81a6-11ea-95ed-0d2e8b8efa1f.png)

**Comment by Pupsi-Mupsi** [comment]
> After that, you can format the text with Edit -> Advanced -> Format Document/Selection (Astyle).

Any chance to assign a keyboard shortcut to this?

**Comment by CountAlex** [comment]
> 
> 
> > After that, you can format the text with Edit -> Advanced -> Format Document/Selection (Astyle).
> 
> Any chance to assign a keyboard shortcut to this?

I don't remember exact actions for this but I was using link Night-Pryanik mentiones above, and settings for the plugin are set to make astyle reformatting on file save.

**Comment by Pupsi-Mupsi** [comment]
You are right!

**Comment by Night-Pryanik** [comment]
> Any chance to assign a keyboard shortcut to this?

![изображение](https://user-images.githubusercontent.com/11132525/79669342-f0695300-81cb-11ea-938c-6e8016b1bb0a.png)

Go to Options -> Environment -> Keyboard. Type "astyle" to quickly find the commands. Use "Press shortcut keys".

**Comment by Pupsi-Mupsi** [comment]
**Thank you very much.** I'm closing this issue. Everything works fine! I tested astyle with the latest changes on #39471. Fingers crossed ;-)
