### ISSUE TITLE
Crash upon completion of Mining Task

### ISSUE THREAD

**Issue by p-dimi** [CleverRaven/Cataclysm-DDA#39704]
Upon completion of a mining task, the game crashes.
This happens when using a Mining zone. The game crashes when the player completes an auto mining task, as well as when a follower completes this task.

Mining manually does not seem to trigger a crash, but uncertain (mining zone is big, too big to manually dig out).

_Note: In the save file, the character is not on location (but just one turn away from being on location and one turn away from the crash).
This happened multiple times, but I thought if I set a follower to do it then it won't be a problem.
So I left on a minor raid, and came back after the task completed (supposedly).
The save file is in a car on the way to base, one turn away from the crash.
Didn't make a save backup :(_

# Steps To Reproduce

1. After digging a hole underground, assign a mining zone, and attempt to auto mine it, or assign zone to be mined by follower.
2. Wait for auto task completion, or if follower is doing it - wait in area until finished.
You don't need to be inside the mine when they finish, just to arrive to the area or be in the area after task completion.

# Expected behavior

The mining task will finish and the assigned mining zone will be mined.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-891-ga664636 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

Debug and Crash logs:
[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4497861/config.zip)

Save file: <= the character is away from the area in the save. However, just keep driving in the same direction at the same speed for just one turn, and it will be in the area and crash.
[Earth II.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4497880/Earth.II.zip)

The crash log:

`The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 0.E-891-ga664636
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

  #0
    (dbghelp: @0x63a736[cataclysm-tiles.exe+0x23a736]), 
    (libbacktrace: Z21debug_write_backtraceRSo+0x56@0x63a736),
    (libbacktrace: 0x63a736    [unknown src]:0    [unknown func]),
  #1
    (dbghelp: @0x61e49f[cataclysm-tiles.exe+0x21e49f]), 
    (libbacktrace: log_crash+0x4af@0x61e49f),
    (libbacktrace: 0x61e49f    [unknown src]:0    [unknown func]),
  #2
    (dbghelp: @0x61f172[cataclysm-tiles.exe+0x21f172]), 
    (libbacktrace: signal_handler+0x32@0x61f172),
    (libbacktrace: 0x61f172    [unknown src]:0    [unknown func]),
  #3
    (dbghelp: SMPEG_error+0x4b034@0x10849e0[cataclysm-tiles.exe+0xc849e0]), 
    (libbacktrace: gnu_exception_handler+0x70@0x10849e0),
    (libbacktrace: 0x10849e0    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crt_handler.c:223    _gnu_exception_handler),
  #4
    (dbghelp: _C_specific_handler+0x98@0x7ffbd66a8048[msvcrt.dll+0x28048]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #5
    (dbghelp: _chkstk+0x11f@0x7ffbd6e211cf[ntdll.dll+0xa11cf]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #6
    (dbghelp: RtlRaiseException+0x399@0x7ffbd6dea209[ntdll.dll+0x6a209]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #7
    (dbghelp: KiUserExceptionDispatcher+0x2e@0x7ffbd6e1fe3e[ntdll.dll+0x9fe3e]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #8
    (dbghelp: @0x8b4046[cataclysm-tiles.exe+0x4b4046]), 
    (libbacktrace: ZN13item_locationdeEv+0x6@0x8b4046),
    (libbacktrace: 0x8b4046    [unknown src]:0    [unknown func]),
  #9
    (dbghelp: @0x425599[cataclysm-tiles.exe+0x25599]), 
    (libbacktrace: ZN17activity_handlers14pickaxe_finishEP15player_activityP6player+0x49@0x425599),
    (libbacktrace: 0x425599    [unknown src]:0    [unknown func]),
  #10
    (dbghelp: @0x45cf80[cataclysm-tiles.exe+0x5cf80]), 
    (libbacktrace: ZNK13activity_type11call_finishEP15player_activityP6player+0xf0@0x45cf80),
    (libbacktrace: 0x45cf80    [unknown src]:0    [unknown func]),
  #11
    (dbghelp: @0xd628bb[cataclysm-tiles.exe+0x9628bb]), 
    (libbacktrace: ZN15player_activity7do_turnER6player+0x189b@0xd628bb),
    (libbacktrace: 0xd628bb    [unknown src]:0    [unknown func]),
  #12
    (dbghelp: @0xc1c73d[cataclysm-tiles.exe+0x81c73d]), 
    (libbacktrace: ZN3npc18do_player_activityEv+0x6d@0xc1c73d),
    (libbacktrace: 0xc1c73d    [unknown src]:0    [unknown func]),
  #13
    (dbghelp: @0xc30790[cataclysm-tiles.exe+0x830790]), 
    (libbacktrace: ZN3npc14execute_actionE10npc_action+0x390@0xc30790),
    (libbacktrace: 0xc30790    [unknown src]:0    [unknown func]),
  #14
    (dbghelp: @0xc346bf[cataclysm-tiles.exe+0x8346bf]), 
    (libbacktrace: ZN3npc4moveEv+0x3cf@0xc346bf),
    (libbacktrace: 0xc346bf    [unknown src]:0    [unknown func]),
  #15
    (dbghelp: @0x7646d7[cataclysm-tiles.exe+0x3646d7]), 
    (libbacktrace: ZN4game7monmoveEv+0x17d7@0x7646d7),
    (libbacktrace: 0x7646d7    [unknown src]:0    [unknown func]),
  #16
    (dbghelp: @0x765d28[cataclysm-tiles.exe+0x365d28]), 
    (libbacktrace: ZN4game7do_turnEv+0x6b8@0x765d28),
    (libbacktrace: 0x765d28    [unknown src]:0    [unknown func]),
  #17
    (dbghelp: IMG_LoadWEBP_RW+0x68f588@0x1805dd8[cataclysm-tiles.exe+0x1405dd8]), 
    (libbacktrace: main+0x10f8@0x1805dd8),
    (libbacktrace: 0x1805dd8    [unknown src]:0    [unknown func]),
  #18
    (dbghelp: @0x4013ed[cataclysm-tiles.exe+0x13ed]), 
    (libbacktrace: _tmainCRTStartup+0x23d@0x4013ed),
    (libbacktrace: 0x4013ed    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crtexe.c:336    __tmainCRTStartup),
  #19
    (dbghelp: @0x4014fb[cataclysm-tiles.exe+0x14fb]), 
    (libbacktrace: WinMainCRTStartup+0x1b@0x4014fb),
    (libbacktrace: 0x4014fb    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crtexe.c:186    WinMainCRTStartup),
  #20
    (dbghelp: BaseThreadInitThunk+0x14@0x7ffbd5b77bd4[KERNEL32.DLL+0x17bd4]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #21
    (dbghelp: RtlUserThreadStart+0x21@0x7ffbd6dece51[ntdll.dll+0x6ce51]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
`

**Comment by Qrox** [comment]
> (libbacktrace: ZN13item_locationdeEv+0x6@0x8b4046),
> (libbacktrace: ZN17activity_handlers14pickaxe_finishEP15player_activityP6player+0x49@0x425599),

The crash happens when dereferencing `item_location` in `activity_handlers::pickaxe_finish`. Probably caused by #37910. @KorGgenT can you look into it?
