### ISSUE TITLE
You now slip while walking up stairs

### ISSUE THREAD

**Issue by Talvan** [CleverRaven/Cataclysm-DDA#39701]
# Describe the bug

You have a chance to fail walking up a flight of stairs.

# Steps To Reproduce

1. Find wooden stairs.
2. Try to walk up wooden stairs a few times.
3. Fail occasionally 

# Expected behavior

Succeeding every time like most humans.

# Screenshots

# Versions and configuration

OS: Windows 10
Game Version: 0.E-886-g074dd18
Mods loaded: Aftershock
# Additional context
Might have been caused by #39635

**Comment by wapcaplet** [comment]
I can reproduce this on the stairs in the starting evac shelter. Out of 40 attempts to climb the stairs, 4 of them failed saying "You slip while climbing and fall down again."

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Pop!_OS 19.10; Release: 19.10; Codename: eoan; 
- Game Version: 0.E-887-gfe9ad2186a-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
