### ISSUE TITLE
"Stay with me" from Talk submenu doesn't override properly "Travel to location" command

### ISSUE THREAD

**Issue by Mrzjadacz** [CleverRaven/Cataclysm-DDA#39712]
# Describe the bug
I wanted to send suicidical NPC to my camp instead of having him follow me and lure zombies, told him to travel there. He started marching happily through infected town, so I run after him and told him to stay with me instead. Everything seemed to work as intended but shortly after that, I relaunched the game and my NPC disappeared from my current location. According to map, he's still at the same map cell as me (note appears on z-level 0), but after using debug clairvoyance artifact and checking upper Z-level he's not there.
I repeated check after few in-game days, results were the same.
His mission still appears, he's still visible under YOUR FOLLOWERS tab (at the screenshot)

# Steps To Reproduce

1. NPC gives you mission which makes them follow you
2. You make NPC join you by using debug_min_control_mutation
3. You order NPC to go to camp
4. You _Talk_ to them and tell them to follow you
5. You relaunch the game

# Expected behavior

NPC to continue to exist

# Screenshots

![image](https://user-images.githubusercontent.com/26396019/79681046-c4bf8a80-8216-11ea-96fc-4ff551df33af.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    No Fungal Monsters [No_Fungi],
    Magiclysm [magiclysm],
    Aftershock [aftershock],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Mining Mod [Mining_Mod],
    No Rail Stations [No_Rail_Stations],
    Graphical Overmap [Graphical_Overmap]
]

**Comment by davidpwbrown** [comment]
Have you got the savegame to upload ?

**Comment by Mrzjadacz** [comment]
[auto_after_end64.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4501575/auto_after_end64.zip)
I don't have save from before or shortly after the event, but Followers menu didn't change.
