### ISSUE TITLE
crash when installing CBM

### ISSUE THREAD

**Issue by buildfailedforallplatforms** [CleverRaven/Cataclysm-DDA#39713]
Game crashes after installing CBM

After a CBM is installed the game crashes

1. Install CBM
2. CBM installs successfully
3. Game crash

CBM should install without crashing the game. 
The first one I noticed was installing Power Storage CBM, it worked after installing Joint Torsion CBM.
The second one was installing Telescopic Eye CBM with far sighted and near sighted mutation.

# Screenshots

# Versions and configuration

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4498462/debug.log)

# Additional context

**Comment by Fris0uman** [comment]
Very likely  related to  #39647
I forgot to check that removing trait with bionic still worked, sorry about that.
