### ISSUE TITLE
Parkour expert "moving onto tall grass is slow" inconsistency

### ISSUE THREAD

**Issue by Relyksboa** [CleverRaven/Cataclysm-DDA#39710]
# Describe the bug
When using parkour expert moving onto tall grass is reported to the player as being slower than usual moving despite not being slower than usual moving

# Steps To Reproduce

1. create a character with the parkour expert trait
2. move normally and document the speed
3. move over tall grass and document the speed
4. notice that the message log is lying to you. 

# Expected behavior
not to report as being slow or the parkour expert trait not applying to tall grass

**Comment by ta-nelson** [comment]
I'd agree with it not applying to tall grass if it is not difficult to implement. Logically parkour won't help you tread grass quicker. Would make more sense to add a "woodsman" trait for that effect, or to wrap it up into outdoorsman or base it on survival skill.

**Comment by Dacendeth** [comment]
I'd argue that this is not a bug and the message is still warranted, as even with parkour moving from a tall grass tile to another tall grass tile is slowed, parkour only helps if it's a single tile of tall grass. This is true for all movement off of any tile with over 200 movecost.
