### ISSUE TITLE
Curtains not tearable in a large amount of newly added window types

### ISSUE THREAD

**Issue by MateuszCzarnowski** [CleverRaven/Cataclysm-DDA#39720]
# Describe the bug

[more windows varienty #38475 ](https://github.com/CleverRaven/Cataclysm-DDA/pull/38475)
When tearing down curtains from windows added in above PR the terrain type is not being changed - the curtains are still attached to the window. However, the curtain materials (stick, sheets, etc.) are being produced anyway, resulting in a potentially infinite amount of them.

Windows added in this PR seem not to be included in _iexamine.cpp_ which checks and sets the terrain accordingly after tearing down action.

Furthermore, metal grate windows lack OPENCLOSE_INSIDE flag, and t_metal_grate_window_with_curtain_open lacks TRANSPARENT flag.

# Steps To Reproduce

1. Examine one of the windows mentioned above
2. Attempt to tear down the curtains
3. Curtains are still attached to the window, curtain materials are generated

# Expected behavior

Curtains are removed from the window (the terrain type is set to a curtain-less window)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.E-937-gc602111 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    sees-player icon, retrodays [sees_player_retro]

**Comment by souricelle** [comment]
Fixed by #48408

**Comment by Fris0uman** [comment]
looking at the json `curtain_transform` seems to be set right where it needs to
