### ISSUE TITLE
Request: Throwing grenades with staff slings

### ISSUE THREAD

**Issue by MirrorMorphMemories** [CleverRaven/Cataclysm-DDA#39746]
# Is your feature request related to a problem? Please describe.
On the subreddit, someone had the idea that there could be an item for throwing grenades farther, like a big slingshot - see https://old.reddit.com/r/cataclysmdda/comments/g2jskh/a_slingshot_for_grenadesdynamite/. That idea morphed into the idea of being able to use slings and staff slings to throw grenades, since slingshots seem too weak for this. I personally think something like this would be very useful, since I'm always throwing my pipe bombs not far enough and getting blown up/riddled with shrapnel.

# Describe the solution you'd like
The simplest solution would probably be to repurpose the Railgun CBM functionality to apply to this situation. The logic would probably go like "If you're wielding a sling/staff sling, you can throw objects 0.25L/0.50L or smaller from your inventory as though you had them in your hand, and throw them 50% farther and with 50% more damage." For comparison, the Railgun CBM works like "If you have the CBM on, when you throw a iron or steel object, you throw it 100% farther and with 100% more bash damage." I think 50% is a good middle ground between the doubling of the Railgun CBM, which should be better since it's a railgun, and ordinary throwing.

# Describe alternatives you've considered
1: Leave things as they are, since they're working acceptably well. I think the implementation of this however should be simple enough that the cost/benefit analysis is favorable.
2: A new weapon that only throws grenades, pipe bombs, and so such. I'm pretty sure that this would be more complicated though then the proposed implementation, since there's nothing like it in the current game. A new weapon whose range and damage depends on the item you're throwing + your strength, which uses ammo that needs to behave identically to the thrown version, and which must always launch them further and with more force than throwing them by hand... it sounds like a lot of work to code.

# Additional context
I collated a bunch of sources indicating that throwing grenades with slings and staff slings is a viable real world practice. To copy and paste the summary I wrote on Reddit,
"I've found plenty of claims that they were used to throw grenades (for example on Wikipedia at https://en.wikipedia.org/wiki/Sling_(weapon) & by Lindybeige at http://www.lloydianaspects.co.uk/ancientWeaponry/theStaffSling.html), but they didn't cite their sources. Thankfully the top answer at https://history.stackexchange.com/questions/33103/were-slings-used-for-throwing-hand-grenades-if-not-why has a picture of a sling grenadier throwing dynamite, citing https://analogue-hobbies.blogspot.com/2012/12/28mm-spanish-civil-war-republican.html as evidence.

I also found a firsthand account at http://slinging.org/forum/YaBB.pl?num=1353551226/3 of someone using a sling to throw grenades (he said he'd do it again, but would practice first on some dummies) and some citations of films of Spanish Civil War sling grenadiers at http://slinging.org/forum/YaBB.pl?num=1267903558/2 (though sadly the films seem to have been lost to time - the Internet Archive can't find them).

Finally, I found a period contemporary reference from a 1917 edition of Scientific American (https://books.google.com/books?id=YuMxAQAAMAAJ&pg=PA340&lpg=PA340&dq=grenade+staff+sling&source=bl&ots=Im_puS7xs6&sig=ACfU3U1RVrUK9Lcwm-0M83BryTRo4nmZRA&hl=en&sa=X&ved=2ahUKEwjujPngnu7oAhVMnJ4KHQdADuEQ6AEwHXoECA4QKQ#v=onepage&q&f=false) for the use of slings and staff slings to throw grenades in World War 1 - see Figures 3, 4, and 5 in the main illustration and the citation of Illustrated War News, Dec 9, 1914.

Update: I was able to find an archived version of the December 9 1914 edition of the Illustrated War News at https://www.britishnewspaperarchive.co.uk/search/results/1914-12-09?NewspaperTitle=Illustrated%2BWar%2BNews&IssueId=BL%2F0001862%2F19141209%2F&County=London%2C%20England. The illustration of contemporary sling grenadiers seems to be on page 24. Unfortunately you need an account to access the page, and I don't want to jump through these sort of hoops when I think I've done a good enough job already."

As to how exactly the code would work... I think that the bonus from the sling/staff sling and the bonus from the Railgun CBM should be mutually exclusive. As in, if you're throwing things from your inventory using the sling or staff sling, you shouldn't also get the bonus from the Railgun CBM - that should only apply when throwing objects in hand. So I think the throwing code should first check if you're using a sling or staff sling to throw small enough objects from your inventory and apply the sling/staff sling bonus accordingly, and if that's not the case proceed to checking whether you have the Railgun CBM and are throwing an object made out of iron or steel.

As for the balancing on the bonus... I think 50% should avoid any weird cases where you can throw a pipe bomb farther than the 20 tiles you can throw a lighter and more aerodynamic rock, or throw a rock from the 't'hrow menu farther and with more force than 'f'iring it from the staff sling, but a bit of testing and fine tuning will probably be necessary.

Addendum: I forgot that molotos are 750ml and it seems reasonable to be able to throw them as well. So I guess it'd be preferrable if the volume limit on staff slings was 750ml instead of 500.

**Comment by Vostokapollo** [comment]
If this relies on throwing skill, I'd like to see this used to throw anything spherical that can be picked up, in case you're running around a table to escape a zombie and you find some eggs or ball bearings.

I feel like you could also expand upon this and add atlatls that rely on throwing skill, which would be pretty fun.

**Comment by MirrorMorphMemories** [comment]
I think the 't'hrowing menu based implementation for the sling and staff sling should already do that, adding a bonus to any thrown item small enough to fit in the sling pouch. You could certainly expand this idea however to a specialized atlatl item, which allows you to 't'hrow any item with the SPEAR or JAVELIN flag with a 50% range and damage bonus regardless of its size.
