### ISSUE TITLE
Finger Pick CBM Stuck Picking Forever

### ISSUE THREAD

**Issue by SolidWarSnake** [CleverRaven/Cataclysm-DDA#39740]
# Describe the bug
When trying to use the Fingerpick a door open it gets stuck in picking the lock. The Yes and No prompts can stop the picking.

# Steps To Reproduce
1. Have a player with the Fingerpick.
2. Activate the Fingerpick in front of a locked door.
3. Player gets stuck trying to pick the lock.

# Expected behavior
Successfully opening the locked door or failing.

# Screenshots
![cataclysm-tiles_2jAbvdNkHB](https://user-images.githubusercontent.com/63990863/79711080-e1020c80-8294-11ea-9b90-c3aaa7d94001.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-960-gec91719 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
Character is Rey Villarreal
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4501121/debug.log)
[CBM Test.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4501124/CBM.Test.zip)

**Comment by alexglasser** [comment]
I reproduced this, looks like even with high lockpicking skill you will spend forever trying to unlock a door with the CBM. My character spent ~20 hours trying to pick a lock before Dead Tired set in and gave me a prompt.

**Comment by Night-Pryanik** [comment]
Activating bionic creates a fake item in thin air, and then destroys it almost immediately, before lockpicking activity finishes its business.
