### ISSUE TITLE
Should we try to fix vehicle crafting station bugs now or wait for new system?

### ISSUE THREAD

**Issue by NaturesWitness** [CleverRaven/Cataclysm-DDA#3975]
As has been mentioned in numerous places, the system that vehicle parts like the RV kitchen, welding rig, and FOODCO buddy use is a little buggy.  Specifically, the virtual tools they provide can be used as components to build duplicate items, which is pretty broken.  The problem is, the only way I know to fix it is to make duplicate "virtual tool" items, and have recipes use those in addition to the regular tools, which creates a lot of clutter and redundancy.  It's been mentioned that once we implement the "CUT=1" system to more tool types this problem will get a lot smaller, but until then, we have this big bug staring us in the face.

My question is, should we try to fix this now (despite all the redundant items it'll make), or just wait until the new system gets finished?

**Comment by kevingranade** [comment]
There haven't been any reports of this happening in forever, is it still a problem?

**Comment by Rivet-the-Zombie** [comment]
As far as I'm aware it's been fixed.
