### ISSUE TITLE
Crash on loading save file: "unrecognised iuse function FITNESS CHECK"

### ISSUE THREAD

**Issue by Eisenknochen** [CleverRaven/Cataclysm-DDA#39759]
# Description
 I wanted to boot up the game and load my save when I got the following error messages:

> DEBUG Recieved unrecognised iuse function FITNESS_CHECK, using none instead
> FUNCTION use_function Item_factory::usage_from_string(const string&) const
> FILE src/item_factory.cpp
> LINE 2861

Here a snippet from the stacktrace;
`17:46:41.543 ERROR : src/item_factory.cpp:2861 [use_function Item_factory::usage_from_string(const string&) const] Received unrecognized iuse function FITNESS_CHECK, using iuse::none instead
17:46:42.209 ERROR : src/main_menu.cpp:1103 [bool main_menu::load_character_tab(bool)] Error: data/mods//dda/../../json/monsters/zed_soldiers.json: line 483:46: Invalid special_attacks

    "armor_cut": 27,
    "harvest": "CBM_OP2",
    "special_attacks": [ [ "BIO_OP_BIOJUTSU",
                                             ^
                                              15 ] ]
  }
]
`

# Steps To Reproduce
I have no idea what might have caused this. I saved the game yesterday and wanted to load today and it won't let me load the game

# Expected behavior

# Screenshots

# Versions and configuration

# Additional context

[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4504730/config.zip)
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4504731/save.zip)

**Comment by ZhilkinSerg** [comment]
You are trying to use new json data with old executable. Reinstall your game.
