### ISSUE TITLE
Sort loot doesn't work

### ISSUE THREAD

**Issue by Brytenwalda** [CleverRaven/Cataclysm-DDA#39767]
# Describe the bug

Sorting out the loot doesn't work - both assigned as a camp job and when I ask an NPC to do that. That all despite loot areas being set and active. 

# Steps To Reproduce

1. Create loot zones.
2. Use the NPC option to sort the loot and/or the camp job. 
3. NPCs will pick up items and drop them immediately. 
4. I would receive a message that so and so NPC sorted every item possible but not one of them is actually sorted. 

# Expected behavior

I would expect NPCs to sort the loot and put it in different zones. 

# Versions and configuration

 - OS Windows 10
 - Game Version: 0.E-1002-g28e603d
 - Graphics version: Tiles
 - Ingame language: English

**Comment by Dacendeth** [comment]
Could not reproduce, setup loot zones, dropped some clothing and weapons in it and talked to the npc and instructed him to sort out some loot. Worked as it should.

**Comment by Pupsi-Mupsi** [comment]
Could not reproduce either.

@Brytenwalda 
-> Would you consider updating to the latest build?

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-1075-g3d0c720 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    No Fungal Monsters [No_Fungi],
    GP-Mods [gpmod],
    Magiclysm [magiclysm]
]

**Comment by int-ua** [comment]
@Brytenwalda after updating please try replicating in a new world, using debug functions to speed it up and writing down all the steps.
