### ISSUE TITLE
Food rotting in ice labs again (0.E)

### ISSUE THREAD

**Issue by int-ua** [CleverRaven/Cataclysm-DDA#39778]
# Describe the bug
Food left in an ice lab unfreezes if left outside of reality bubble.

# Steps To Reproduce
0. Turn on z-levels.
1. Get into an ice lab below ground level.
2. Spawn 1 raw liver (and a super clairvoyance artifact to make testing easier), make sure it's frozen before leaving in a normal way (not teleporting).
3. Move enough overmap tiles to leave it outside of reality bubble (I did 20 which is an overkill).
4. Wait or set time to +10 days. Or maybe 20, I did it twice and with teleporting it didn't work.
5. Go back to the lab in a normal way, see it's cold instead of frozen, try leaving again while it's still not frozen.
6. Come back in another 10 days to see it rot away.

# Expected behavior
Food kept frozen in an ice lab.

# Versions and configuration
 - OS: Ubuntu 18.04
 - Game Version: 0.E
 - Graphics version: Tiles
 - Mods loaded: default

# Additional context
At first glance it looks like the last change was in the #29818
Related: #24208 #24205

**Comment by Hirmuolio** [comment]
I tried to look at it. It has something to do with coordinates, z-levels and floor changes but there are things that make no sense to me and I do not know how the coordinate things work.

You also need to have z-levels enabled to get the bug (you get a different much smaller bug with z-levels off).

Specifically these lines in item.cpp are where the bug starts.

```
const tripoint &local = g->m.getlocal( pos );
int local_mod = g->new_game ? 0 : g->m.get_temperature( local );
```
With z-levels on these seem to always set the local_mod to 0.


With z-levels off things mostly seem to work fine.

With z-levels off you will get the correct local_mod when you change floor levels (in normal gameplay this is the only case where this would matter for underground levels). But it gives again zero for things that are on same level (the above ground room when you walk to it from outside of reality bubble).

With debug time manipulation and z-levels off it will give zero to all items that are on same floor with you.

The weirdest part is that water in toilets seems to always get the correct temperature when z-levels are off.

**Comment by int-ua** [comment]
Yes, I forgot to add that I have z-levels on, sorry.

**Comment by Hirmuolio** [comment]
Chanigng

```
const tripoint &local = g->m.getlocal( pos );
int local_mod = g->new_game ? 0 : g->m.get_temperature( local );
```

into

```
int local_mod = g->new_game ? 0 : g->m.get_temperature( pos );
```

seems to fix it with z-levels on. 
But breaks it for z-level off. Items on same level process right but when you go up/down stairs the items on the new level get wrong temperature.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/0-e-ellison-release-has-arrived/23092/21
