### ISSUE TITLE
Trading item with same type as equipped deletes equipped item, creates dupe.

### ISSUE THREAD

**Issue by YakumoChen** [CleverRaven/Cataclysm-DDA#39774]
# Describe the bug

If you are trying to trade an item, and you also have a similar item equipped (ie: two guns of the same model), your equipped item is deleted, while selling a duplicate of the item you were attempting to trade. You keep the item you intended to trade, which is duplicated.

# Steps To Reproduce

1. Make a player with a gun, like an M4A1. Put a suppressor on it. Equip the gun
2. Make a second M4A1, carry it in your backpack. 
3. Try to trade the unmodded M4A1 in your bag.
4. Your equipped M4A1 vanishes, trader recieves an unmodified M4A1.

# Expected behavior

My equipped gun doesn't bloody vanish

# Screenshots
![image](https://user-images.githubusercontent.com/10399117/79853915-2e2acf00-83b8-11ea-932a-e2edd509ed4a.png)
I try to sell an item, while holding a similar item
![image](https://user-images.githubusercontent.com/10399117/79853944-384ccd80-83b8-11ea-903a-2766820a7554.png)
My item vanishes out of my hand, leaving the item I wanted to sell.
![image](https://user-images.githubusercontent.com/10399117/79853964-40a50880-83b8-11ea-8b32-f8f29a4ef118.png)
Trader now has two vibrators instead of one, but it's fully charged despite my partially charged one being missing.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-960-gec91719 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

This was tested with multiple different traders (happened two times trading with the varying Hub01 traders)

Crash: if your problem refers to a crash, please add the following files to the "Additional Context" paragraph:
    - From the /config folder (you can zip them both together):
        - crash.log file.
        - debug.log file.
    - Your save file (zipped)

- note #1: you can drag and drop files in this issue post!
- note #2: it is very important for us that you provide a save file in case of a crash. It really helps the developers
    to reproduce the bug and fix it. If possible, try to provide a save file that occurs in the right conditions, just
    before the crash happens. -->

**Comment by int-ua** [comment]
Cannot reproduce on latest experimental.
