### ISSUE TITLE
Broken age selection bar at the final submenu of character's creation when selected language is Russian

### ISSUE THREAD

**Issue by CriticallyIncorrect** [CleverRaven/Cataclysm-DDA#39791]
# Describe the bug
The recently added feature of selecting your character's age (located in the final submenu of creating the character) has got little buggy in one of the recent experimantal builds.

This bug appears when selected language is Russian while English language have no problems with it!

For some reasons the bar "Age" stopped showing you the second digit of your age (like you only see "2", "3", "4" or "5" instead of the double-digit age of "23" or "34" or anything you want to make it to be). 
When you select this bar and try to make the char younger or older with arrows, it shows no changes until you cross 20-30-40-50 years border and you notice that only this single first digit changes but you still can't see any second digit). So basically it's working but just not showing you the current second digit of your age.

# Steps To Reproduce
1. Run the latest experimental
2. Change language in settings to "Russian"
3. Create a character and reach the final submenu of creation
4. Select the "Age" bar and try to change it. You will see the problem right away.

# Expected behavior
This must be really small and easy-to-fix bug and clearing it out will make the char creation menu to look nice again :) 

# Screenshots

# Versions and configuration
 - OS: Windows 10
 - Game Version: Latest Experimental (0.E #10551). It appears also in earlier versions (started somewhere between #10500-#10540) but fixing latest will be enough I believe.
 - Graphics version: Tiles
 - Ingame language: Russian
 - Mods loaded: no mods.

# Additional context

**Comment by Pupsi-Mupsi** [comment]
Works fine for me. Could you update to the latest build and try again?

![grafik](https://user-images.githubusercontent.com/44737997/80031526-1d7a7600-84ea-11ea-8461-3a765215c54a.png)

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-1075-g3d0c720 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    No Fungal Monsters [No_Fungi],
    GP-Mods [gpmod],
    Magiclysm [magiclysm]
]

**Comment by CriticallyIncorrect** [comment]
> Works fine for me. Could you update to the latest build and try again?
> 
> ![grafik](https://user-images.githubusercontent.com/44737997/80031526-1d7a7600-84ea-11ea-8461-3a765215c54a.png)
> 
> * OS: Windows
>   
>   * OS Version: 10.0 1909
> * Game Version: 0.E-1075-g3d0c720 [64-bit]
> * Graphics Version: Tiles
> * Game Language: English [en]
> * Mods loaded: [
>   Dark Days Ahead [dda],
>   Disable NPC Needs [no_npc_food],
>   Alternative Map Key [alt_map_key],
>   SpeedyDex [speedydex],
>   Stats Through Kills [stats_through_kills],
>   Stats Through Skills [StatsThroughSkills],
>   No Fungal Monsters [No_Fungi],
>   GP-Mods [gpmod],
>   Magiclysm [magiclysm]
>   ]

Hey buddy-thank you for helping out. This bug for some reason only appears when the selected language is Russian-just switched to english and it worked just fine as on your screenshot. Updating my issue now
