### ISSUE TITLE
AEP_PSYSHIELD's actual effect differs from that in helping document

### ISSUE THREAD

**Issue by RedShakespeare** [CleverRaven/Cataclysm-DDA#39805]
# Describe the bug

In both enums.h and JSON_INFO.md the artifact effect AEP_PSYSHIELD ("Your mental state feels protected") appears to be able to protect players from stare attacks of monster flaming eyes or, the teleglow state. There're no codes, however, to realise this feature.

# Steps To Reproduce

1. Make a player with an item with the artifact effect AEP_PSYSHEILD.
2. Summon a flaming eye.
3. The player is affected by the stare attack and catch a teleglow.

# Expected behavior
The player should be immunized to the stare attack 'cause.

# Screenshots

# Versions and configuration
- OS: Win10
- Game Version: 0.e-1011-gdb44c38
- Graphics Version: Either tiles or terminal
- Ingame language: Any
- Mod loaded: dda, and any other mods

**Comment by Night-Pryanik** [comment]
> In both enums.h and JSON_INFO.md the artifact effect AEP_PSYSHIELD ("Your mental state feels protected") appears to be able to protect players from stare attacks of monster flaming eyes or, the teleglow state.

In both `enums.h` and `JSON_INFO.md` the _exact_ text is `Protection from stare attacks`, period. It doesn't say anything about flaming eyes or teleglow. There are several monster with stare attacks from which this artifact could help, and flaming eyes is not in this list.

**Comment by RedShakespeare** [comment]
> > In both enums.h and JSON_INFO.md the artifact effect AEP_PSYSHIELD ("Your mental state feels protected") appears to be able to protect players from stare attacks of monster flaming eyes or, the teleglow state.
> 
> In both `enums.h` and `JSON_INFO.md` the _exact_ text is `Protection from stare attacks`, period. It doesn't say anything about flaming eyes or teleglow. There are several monster with stare attacks from which this artifact could help, and flaming eyes is not in this list.

But only flaming eye has the ability to make a stare attack...

**Comment by Night-Pryanik** [comment]
> But only flaming eye has the ability to make a stare attack...

There are different types of stare attacks. 
`Amigara horror`, `blood sacrifice`, `flesh angel`, and `gozu` have the stare attack from which this artifact could protect.
`Flaming eye` has a stare attack of different type, and there is no guaranteed protection from it.

**Comment by RedShakespeare** [comment]
> There are different types of stare attacks.
> `Amigara horror`, `blood sacrifice`, `flesh angel`, and `gozu` have the stare attack from which this artifact could protect.
> `Flaming eye` has a stare attack of different type, and there is no guaranteed protection from it.

These monsters listed above make their psychological attacks **with their horrible appearance **according to the texts in game... In other words, these are "**Being-stared-at" attacks** (or "fear-paralyze" as the function name) in which the monsters don't really STARE at anyone themselves (some of them don't even have functional eyes? ) but the players happen to SEE them clearly (no need to "stare at them" either), compared to the actual stare attack (bool mattack::stare(monster)) which can only be made by flaming eyes.

Or, if the admins don't want another protection from flaming eyes, maybe the helping documents could be updated to avoid misunderstanding? Thx for patience.

**Comment by Aloxaf** [comment]
> maybe the helping documents could be updated to avoid misunderstanding?

I agree with this.
Considering that the description of `PSYSHIELD_PARTIAL` is `25% chance to protect against fear_paralyze monster attack when worn`, I suggest changing the description of `AEP_PSYSHIELD` to `Protection from fear paralyze attack` to be consistent with it.
