### ISSUE TITLE
Changes in #39658 allows projectiles to go through more obstacles than they should

### ISSUE THREAD

**Issue by RedShakespeare** [CleverRaven/Cataclysm-DDA#39814]
# Describe the bug

After #39658 was merged bullets seem to be able to go through more barriers than they should be able to, such as ballistic (bulet-proof) glass walls.  (According to some other players, some non-glass wall can be shoot through as well but they don't tell me what kind these walls are)

# Steps To Reproduce
1. Make a player with a gun, magazine, and some ammo.
2. Edit the map to create a little room of ballistic walls, and put a monster in it.
3. Try to shoot the monster.
4. The bullet will get through the ballistic glass wall and hit the monster like the wall doesn't exist.

# Expected behavior
There should be judgement about which obstacles can be shoot through and which don't. Apparently a bullet shouldn't get through a bullet-proof glass (or other solid barriers) 

# Screenshots
![image](https://user-images.githubusercontent.com/44523519/79981541-712f9400-84d7-11ea-9264-fb408f0feb48.png)
Shoot a wolf in the ballistic glass room successfully. Note the upper right corner of the game window. 

# Versions and configuration
- OS: Win10
- Game Version: 0.E-1011-gdb44c38
- Graphics version: Either
- Ingame language: Any
- Mods loaded: dda and any other mods

**Comment by RedShakespeare** [comment]
Update: The very player told me it's concrete that can be shoot through, and my test proved this. 
![image](https://user-images.githubusercontent.com/44523519/79982618-2a429e00-84d9-11ea-8ebe-7a2e9053bf8a.png)

**Comment by anothersimulacrum** [comment]
This isn't due to the changes in #39658 - well, it is,but only because that restored this behavior.
See #33374.

**Comment by RedShakespeare** [comment]
Ah...
So that's really a...thing.  >.<

**Comment by Night-Pryanik** [comment]
Closing as duplicate.
