### ISSUE TITLE
UPS conversion mod not allowing recharge in recharging station?

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#39820]
# Describe the bug
In 0.D I used to put a UPS conversion mod on my tools and when I dropped them in a recharging station they recharged (as per the tutorial#63 of Vormithrax). I just did that on a food processor, dropped it in the recharging station and nothing happens (the same recharging station works OK for batteries). Has the logic changed or am I doing something wrong?

# Steps To Reproduce

# Expected behavior
Work as before or provide explanation on the new way to make it work.

# Screenshots

# Versions and configuration
- OS: Linux
    - OS Version: LSB Version: core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch; Distributor ID: Ubuntu; Description: Ubuntu 18.04.4 LTS; Release: 18.04; Codename: bionic; 
- Game Version: 0.E-238-g6393a6d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Stats Through Skills [StatsThroughSkills],
    Alternative Map Key [alt_map_key],
    No Fungal Monsters [No_Fungi]
]
# Additional context

**Comment by Pupsi-Mupsi** [comment]
Related to #29961
Stale fix #29983

**Comment by matt32106** [comment]
Why things that break previous features are allowed in the main version. Should not the battery overhaul have been rolled out until it works before merging?

**Comment by Pupsi-Mupsi** [comment]
I feel the same way. Came across this bug as well. 
And thought I had misremembered how the UPS mod should work.

I'm sure though no one broke the game on purpose.
Maybe someone will fix this in the near future.

Stay safe

**Comment by GGgatherer** [comment]
Yep, currently you have to unload batteries and put THEM into recharging station.
Or activate Aftershock, it will replace all UPS, even already-generated ones, with its own version which can be recharged in UPSRC but has an integrated battery (i.e. you can't unload/reload it with regular batteries) with 1500 capacity.

**Comment by int-ua** [comment]
Looks like a duplicate of #33968
@matt32106 please close this issue if you agree.

**Comment by matt32106** [comment]
So nice to see this kind of BS: "They really should put it on Releases page in bold so people stop asking silly questions."

**Comment by matt32106** [comment]
Looks like this is "handled" by a staled issue. -> Closed
