### ISSUE TITLE
Extended description shows the health of appendix

### ISSUE THREAD

**Issue by molkero** [CleverRaven/Cataclysm-DDA#39821]
# Describe the bug

Extended description shows the health of player and npc appendix.

# Steps To Reproduce

1. Start a new game.
2. Look at player or npc `x`, use extended description `e`.
3. Observe the appendix is healthy.

# Expected behavior

Unsure, I guess the appendix being healthy is a good thing.

# Screenshots

![Screenshot_2020-04-22_21-31-27](https://user-images.githubusercontent.com/49575273/80020636-0a63a800-84e2-11ea-85cc-5e686dafebdd.png)
![Screenshot_2020-04-22_21-28-47](https://user-images.githubusercontent.com/49575273/80020657-0fc0f280-84e2-11ea-9d0f-e48eca8712a5.png)

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 20.0; Codename: Lysia; 
- Game Version: 0.D-14615-g3d0c720be6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

<!--# Additional context--!>

**Comment by GGgatherer** [comment]
Oh God, does it mean there are plans for setting up certain conditions which would result in a situation where our characters would need it amputated? That'd be so much ---FUN--- for 0-city worlds' dwellers!

**Comment by int-ua** [comment]
No, it was a fallback bodypart since [**the** first commit](https://github.com/CleverRaven/Cataclysm-DDA/commit/69ffbb2953c1e92a9b24d5380dabe7f26066223e).
