### ISSUE TITLE
Bunch of errors about drunken trait after updating to 10568

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#39840]
# Describe the bug

Game throws many similar errors while loading a save from 10550.
Error texts follow:

```
 DEBUG    : invalid trait id "DRUNKEN"
 FUNCTION : const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]
 FILE     : src/generic_factory.h
 LINE     : 376
```

```
 DEBUG    : character  has invalid mutation DRUNKEN, it will be ignored
 FUNCTION : void Character::load(const JsonObject&)
 FILE     : src/savegame_json.cpp
 LINE     : 526
```

# Steps To Reproduce

Make a save where some NPCs have the trait in 10550 or less, try loading it in 10568, I guess? I have [one](https://drive.google.com/open?id=1R3Rl_BCpta1vDJf5ZxjdSomB8J6MMh4W) lying around if needed.

# Expected behavior

If the trait was removed by design, silently ignore it maybe?

# Versions and configuration

- OS: Windows 7x64
- Game Version: 0.E-1142-gd683c5f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Aftershock [aftershock],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills],
    Magiclysm [magiclysm]
]

**Comment by CodeBandit** [comment]
Save incompatibility between versions in experimental isn't really a bug. To fix it, just debug remove drunken from said NPC's

**Comment by GGgatherer** [comment]
> Save incompatibility between versions in experimental isn't really a bug.

I know. I'm reporting it so it doesn't go under the radar and is left in 0.F. Save compatibility between stables is a goal, after all.
