### ISSUE TITLE
Can't start at either the police station or fire station

### ISSUE THREAD

**Issue by ScottyMoDo** [CleverRaven/Cataclysm-DDA#39851]
# Describe the bug

Both the police station and the fire station are missing from the possible starting locations of surrounded.

# Screenshots

![image](https://user-images.githubusercontent.com/64236354/80165066-95a77100-85a8-11ea-9e5e-a6b3dcbf1833.png)

**Comment by Boredone** [comment]
Looks like it got removed in #38151. Probably on accident, since it wasn't a stated change.

**Comment by ScottyMoDo** [comment]
Does that mean it will be added back in in the future?

**Comment by ZhilkinSerg** [comment]
> 
> 
> Does that mean it will be added back in in the future?

Sure thing. That was not an intended change, but copy-paste error.

You can even try to add it back by yourself using that PR as an example. All you need to do is add `sloc_fire_station` and `sloc_police` to scenario in question in `scenarios.json`
