### ISSUE TITLE
Crash upon putting items into the same spot using Advanced Inventory management

### ISSUE THREAD

**Issue by FeelsBadMatey** [CleverRaven/Cataclysm-DDA#39853]
Crash upon doing what is stated below.

# Steps To Reproduce

1. Find two items in different spots.
2. Open advanced inventory, and set both to "surrounding area".
3. Move all of the objects using `,`.
4. Crash.

# Expected behavior

I was intending to put all of the objects in the surrounding area into a shopping cart, however, I had forgotten to define the vehicle. 
Might have caused an infinite loop to occur, it was recognized, and a crash was forced.

# Versions and configuration

 - OS: Windows 7
 - Game Version: [from the main menu, e.g. 0.E-1143-g1ae40f3]
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded:
  "no_npc_food",
  "craftgp",
  "growable-pots",
  "More_Survival_Tools",
  "Medieval_Stuff",
  "makeshift",
  "modular_turrets",
  "Salvaged_Robots",
  "hydroponics",
  "more_locations",
  "FujiStruct",
  "mapgen_demo",
  "No_Rail_Stations",
  "Urban_Development",
  "deoxymod",
  "blazemod",
  "Tanks",
  "more_classes_scenarios",
  "sleepdeprivation",
  "manualbionicinstall",
  "no_reviving_zombies",
  "fuji_mpp",
  "Tolerate_This",
  "StatsThroughSkills",
  "speedydex"
 
# Additional context
- Crash log:
The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 0.E-1143-g1ae40f3
TYPE: Signal
MESSAGE: SIGABRT: Abnormal termination
STACK TRACE:

  #0
    (dbghelp: @0x641d46[cataclysm-tiles.exe+0x241d46]), 
    (libbacktrace: Z21debug_write_backtraceRSo+0x56@0x641d46),
    (libbacktrace: 0x641d46    [unknown src]:0    [unknown func]),
  #1
    (dbghelp: @0x625b6f[cataclysm-tiles.exe+0x225b6f]), 
    (libbacktrace: log_crash+0x4af@0x625b6f),
    (libbacktrace: 0x625b6f    [unknown src]:0    [unknown func]),
  #2
    (dbghelp: @0x626842[cataclysm-tiles.exe+0x226842]), 
    (libbacktrace: signal_handler+0x32@0x626842),
    (libbacktrace: 0x626842    [unknown src]:0    [unknown func]),
  #3
    (dbghelp: raise+0x235@0x7fefef61b65[msvcrt.dll+0x41b65]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #4
    (dbghelp: IMG_LoadWEBP_RW+0x10745b@0x127e44b[cataclysm-tiles.exe+0xe7e44b]), 
    (libbacktrace: wassert+0x10b@0x127e44b),
    (libbacktrace: 0x127e44b    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/misc/wassert.c:61    _wassert),
  #5
    (dbghelp: IMG_LoadWEBP_RW+0x107537@0x127e527[cataclysm-tiles.exe+0xe7e527]), 
    (libbacktrace: assert+0xa7@0x127e527),
    (libbacktrace: 0x127e527    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/misc/wassert.c:31    _assert),
  #6
    (dbghelp: @0x47eeec[cataclysm-tiles.exe+0x7eeec]), 
    (libbacktrace: ZNK17advanced_inv_area11free_volumeEb+0x9c@0x47eeec),
    (libbacktrace: 0x47eeec    [unknown src]:0    [unknown func]),
  #7
    (dbghelp: @0x47aa8c[cataclysm-tiles.exe+0x7aa8c]), 
    (libbacktrace: ZN18advanced_inventory14move_all_itemsEb+0x95c@0x47aa8c),
    (libbacktrace: 0x47aa8c    [unknown src]:0    [unknown func]),
  #8
    (dbghelp: @0x47d7e3[cataclysm-tiles.exe+0x7d7e3]), 
    (libbacktrace: ZN18advanced_inventory7displayEv+0x18c3@0x47d7e3),
    (libbacktrace: 0x47d7e3    [unknown src]:0    [unknown func]),
  #9
    (dbghelp: @0x47e364[cataclysm-tiles.exe+0x7e364]), 
    (libbacktrace: Z19create_advanced_invv+0x24@0x47e364),
    (libbacktrace: 0x47e364    [unknown src]:0    [unknown func]),
  #10
    (dbghelp: @0x79b713[cataclysm-tiles.exe+0x39b713]), 
    (libbacktrace: ZN4game13handle_actionEv+0x5653@0x79b713),
    (libbacktrace: 0x79b713    [unknown src]:0    [unknown func]),
  #11
    (dbghelp: @0x76cccf[cataclysm-tiles.exe+0x36cccf]), 
    (libbacktrace: ZN4game7do_turnEv+0xc5f@0x76cccf),
    (libbacktrace: 0x76cccf    [unknown src]:0    [unknown func]),
  #12
    (dbghelp: IMG_LoadWEBP_RW+0x695d58@0x180cd48[cataclysm-tiles.exe+0x140cd48]), 
    (libbacktrace: main+0x10f8@0x180cd48),
    (libbacktrace: 0x180cd48    [unknown src]:0    [unknown func]),
  #13
    (dbghelp: @0x4013ed[cataclysm-tiles.exe+0x13ed]), 
    (libbacktrace: _tmainCRTStartup+0x23d@0x4013ed),
    (libbacktrace: 0x4013ed    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crtexe.c:336    __tmainCRTStartup),
  #14
    (dbghelp: @0x4014fb[cataclysm-tiles.exe+0x14fb]), 
    (libbacktrace: WinMainCRTStartup+0x1b@0x4014fb),
    (libbacktrace: 0x4014fb    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crtexe.c:186    WinMainCRTStartup),
  #15
    (dbghelp: BaseThreadInitThunk+0xd@0x76aa652d[kernel32.dll+0x1652d]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #16
    (dbghelp: RtlUserThreadStart+0x21@0x76cdc541[ntdll.dll+0x2c541]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),

**Comment by slowleakage** [comment]
Same issue. 

Steps To Reproduce: 
Attempted to move items (books on bookshelves) in advanced inventory all directions to directly below by pressing the , key resulted in CTD.

Expected behavior:
All books moved to directly below.

Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2570-gb8bc6f1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    <color_light_red>Secronom</color> [secronom],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Dark Skies Above [darkskies],
    Nechronica Redux [Nechronica_Redux],
    Cataclysm++ [Cata++],
    Crazy Cataclysm [crazy_cataclysm],
    Mining Mod [Mining_Mod],
    More Survivor Stuff [more_survivor_stuff],
    No Rail Stations [No_Rail_Stations],
    Jury-Rigged Robots [jury_rigged_robots],
    No Recreationals [No_Recreationals],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]



[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4692751/config.zip)
[Graymoor-Devondale.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4692753/Graymoor-Devondale.zip)

**Comment by int-ua** [comment]
Please try reproducing in latest experimental.

**Comment by slowleakage** [comment]
updating did resolve the issue.
