### ISSUE TITLE
Blinking zeds on threat map for zombies that see you 

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#39867]
# Describe the solution you'd like
On the threats map with the z symbols (N S E W...), make the letter of the zombies that see you blinking ones. As this can be unnerving to some players, make it an interface option (blinking Zs on threat map Y/N).

**Comment by matt32106** [comment]
Can you please repoen and tag it for a future revisit of the UI? it looks like a few persons are interested.

**Comment by anothersimulacrum** [comment]
If anyone's actively interested in working on it, I will, but as of right now, I'm not aware of anyone.

**Comment by matt32106** [comment]
I was talking about the upvotes.
