### ISSUE TITLE
Achievements keep tracking scores after they're completed

### ISSUE THREAD

**Issue by sick-trigger** [CleverRaven/Cataclysm-DDA#39879]
# Describe the bug
After you complete an achievement the game continues adding to the score so that it says stuff like `103/1 zombies killed` or w/e. In the case of the 'Rude Awakening' it voids your already completed achievement when you add to the score after the time has expired.

# Steps To Reproduce
1. spawn in, kill a few zombies in the first minute, `3/1 monsters killed`, achievement marked as completed
2. wait until 8:01:01, kill another zombie, `4/1 monsters killed`, achievement VOID

# Expected behavior
when an achievement is completed (or failed by missing requirements) it should stop counting things for it

# Screenshots
zombies killed in first minute
![01 Untitled](https://user-images.githubusercontent.com/1411152/80273464-ba433c00-86c1-11ea-98b4-f47c3064c9d3.png)
wait a minute kill another
![02 Untitled](https://user-images.githubusercontent.com/1411152/80273458-b31c2e00-86c1-11ea-8651-7e4e607d5229.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.E-1182-g9f6568b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by jbytheway** [comment]
The voiding thing is a bug.  Thanks for alerting me.

I was torn about how to deal with display of requirements for completed / failed achievements.  So for example for the first achievement, after it's completed, the requirements could be omitted entirely, or it could be listed just as "1 zombies killed", or it could be "1/1 zombies killed" even after you kill more, or it could be the current status quo.  I wasn't sure, and this was the easiest solution.  I'd welcome other opinions as to the best UX.

**Comment by sick-trigger** [comment]
"1/1 zombies killed" looks neater imo, and is consistent with achievements systems in other games
