### ISSUE TITLE
HTTP data API server (headless mode) for web based frontend rendering

### ISSUE THREAD

**Issue by linonetwo** [CleverRaven/Cataclysm-DDA#39881]
# Is your feature request related to a problem? Please describe.

I hope CDDA can have an HTTP API server.
It will be easy to develop a web-based renderer, make it possible to provide an interaction-rich UI for CDDA (eg. mouse-hover tooltip of items, right-click context menus).

With an HTTP API to get data and sent action to CDDA core, creating UI will be much easier, and the game server setup no longer requires SSH.

# Describe the solution you'd like
Create a server serving data that was passed to the terminal UI, serving them via HTTP to a web frontend.
And use the HTTP server to receive data, pass them to the core as if they are passed from the terminal version of UI.

I am not familiar with the CDDA core, so I don't know which part of it is the interface between core and UI.

If someone gives me some direction, I can try.

# Describe alternatives you've considered
Compile c++ to wasm so it can run in the browser, then directly get data and sent action from JS side to the C++ side.

# Additional context
I'm familiar with React and canvas. If there is a way to get data via HTTP or wasm bridge, I want to create an alternative interface for CDDA, to explore the possibility.

**Comment by ZhilkinSerg** [comment]
CDDA is using ncurses for rendering (and its SDL ports), so all you need is attaching ncurses/SDL webassembly port. There are existing things like https://github.com/ilyaigpetrov/ncurses-for-emscripten and https://github.com/emscripten-ports/SDL2 which you can utilize.

@kevingranade already had emscrpten port building, but there are things to be addressed aside from rendering - see https://www.reddit.com/r/cataclysmdda/comments/8n7l7e/compiling_to_wasm/.

**Comment by ZhilkinSerg** [comment]
Also this - http://watchcdda.net/

**Comment by linonetwo** [comment]
Thank you @ZhilkinSerg , wasm is just an alternative, since we will still need a server to sync saves and configs to the disk.

So instead of running full game in the browser, I'd more like to make it `cataclysm --listen 8080` to get an API server, only send API data. And maybe in the future, `cataclysm --web` to start both API server and an official Web UI.

---

To create an API server, maybe I should look at where ncurses/SDL is used, since they are now consuming data from the core?

**Comment by Zireael07** [comment]
Xterm.js https://xtermjs.org/ can support ncurses, so you don't even need WASM, just figure out how to forward from some ssh server.

**Comment by ZhilkinSerg** [comment]
Apart from forwarding output from SSH server, WASM renderer for SDL or ncurses is the only feasible solution - code for game logic and output are too interleaved and cannot be separated easily. You will need to wrap all the output we do to use some kind of UI toolkit for the start and that alone would be a neverending story.

**Comment by linonetwo** [comment]
Okay, I thought CDDA might be data-driven, so there can be a data store to contain all game states, and data drives the rendering.

If there is no such global game state (ECS or something like Mono), it will be hard to get all info for a frontend...

Maybe I can parse the output in the terminal, to generate a "game state"?

**Comment by linonetwo** [comment]
I think this means a headless mode. I will see how StoneSense achieve this with dwarf fotress.

**Comment by ZhilkinSerg** [comment]
There is no need to use this kind of hacks with CDDA as it has open source. Parsing screen is not a good solution either - a single screen does not contain all the information about current game state.

**Comment by xdrie** [comment]
> There is no need to use this kind of hacks with CDDA as it has open source. Parsing screen is not a good solution either - a single screen does not contain all the information about current game state.

When you say this, what alternative do you suggest? Do you think the next easiest option would be reading from global state? Is there documentation on the data structures or otherwise an overview of what this would entail?

**Comment by ZhilkinSerg** [comment]
> > There is no need to use this kind of hacks with CDDA as it has open source. Parsing screen is not a good solution either - a single screen does not contain all the information about current game state.
> 
> When you say this, what alternative do you suggest? Do you think the next easiest option would be reading from global state? Is there documentation on the data structures or otherwise an overview of what this would entail?

It is open source - anyone interested implememting something can do whatever they want while license permits it.

**Comment by xdrie** [comment]
> It is open source - anyone interested implememting something can do whatever they want while license permits it.

Right, I understand that. I was asking with respect to technical feasibility, and asking about your recommendations as a developer who is familiar with this codebase. I am quite new to the CDDA codebase and was hoping you would have some suggestions on where to modify the code to provide gamestate via a HTTP data API. Thanks!

**Comment by linonetwo** [comment]
I tried to read code recently, each cpp is quite huge...Reading them without a guide will be slow.

I like the docs about JSON files, they are very useful for me to use those JSON definitions. Hope there can be some doc for cpp functions too.

**Comment by ZhilkinSerg** [comment]
There are som Doxygen docs - http://dev.narc.ro/cataclysm/doxygen/index.html
