### ISSUE TITLE
Vehicle negative drag slowdown value

### ISSUE THREAD

**Issue by DillonSimeone** [CleverRaven/Cataclysm-DDA#39880]
# Describe the bug

This error was thrown when I was trying to drive though a pile-up of wreckage while stray titans from the dark skies mod was pushing stuff around. I'm guessing that this is somewhat related to [#28768](https://github.com/CleverRaven/Cataclysm-DDA/pull/28768).

# Steps To Reproduce

Zero or higher drag value for everything! Because if things had negative drag slowdown values... They'd start speeding up forever, one day going beyond the light speed!

THAT'S ILLEGAL!

# Screenshots

Me trying to drive over a pile of wreckage at 8mph, where the error occurred!

![image](https://user-images.githubusercontent.com/21962421/80274218-b990b280-868d-11ea-8b77-9cba4a2da66c.png)

Error message (Debug log and save attached at the end of this report)

![image](https://user-images.githubusercontent.com/21962421/80274418-0e80f880-868f-11ea-99ce-a0dd81fdc336.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-1182-g9f6568b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Dark Skies Above [darkskies],
    Magiclysm [magiclysm],
    XEAS [XEAS],
    Generic Guns [generic_guns],
    DinoMod [DinoMod],
    Crazy Cataclysm [crazy_cataclysm],
    My Sweet Cataclysm [my_sweet_cataclysm],
    More City Locations [cityside],
    No Rail Stations [No_Rail_Stations],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Arcana and Magic Items [Arcana],
    Graphical Overmap [Graphical_Overmap]
]

# Additional context
My save: [Palmer Heights.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4532575/Palmer.Heights.zip)

Debug log: [debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4532583/debug.log)

**Comment by natsirt721** [comment]
That looks like integer overflow. Not that that is particularly helpful in determining the root cause...

**Comment by DillonSimeone** [comment]
Sounds right! Some of the wreckages was spinning really really quickly while I was ramming though everything! Like, spinning a thousand time before it became my turn to move again!

**Comment by dhakim87** [comment]
Replicated without any mods.  Appears with a skeletal juggernaut punching wreckage at me for a couple minutes.  Reproducible if I save scum, which I had to do as touching the car insta gibbed me.  Currently in E-2 stable.  

![Screenshot (17)](https://user-images.githubusercontent.com/26189444/100522288-67050080-315e-11eb-8722-db19ff91f4e1.png)

My guess is it's an issue with vehicle destruction?  There are a few messages about parts of the 4x4 car colliding with each other, finally ending in a collision with a "null part" which I suspect is what triggers it.  

![Screenshot (18)](https://user-images.githubusercontent.com/26189444/100522351-e4307580-315e-11eb-9f84-614dc38b65d6.png)

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-10939 with the provided save.
