### ISSUE TITLE
Crash on PrepNet citizen talk to finish mission

### ISSUE THREAD

**Issue by simmael** [CleverRaven/Cataclysm-DDA#39886]
# Describe the bug

After trying to talk to PrepNet citizen to finish mission, game crash

# Steps To Reproduce

When I made new world/character, It didn't happen.

# Expected behavior

Expected to be able to talk to NPC instead of crash.

# Versions and configuration

 - OS: Windows 10 Pro
 - Game Version: 0.E-1198-g4a304e3
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: dda, aftershock, C.R.I.T expansion mod,Magiclysm, Cata++, Mythical martial arts, Bionic Slots, SpeedyDex, StatsThroughSkills, StatsThroughKills

# Additional context

[config+debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4532847/config%2Bdebug.zip)
[Earth-Z.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4532848/Earth-Z.zip)

**Comment by Maleclypse** [comment]
I’m commenting on this to remind myself to check it.

**Comment by Maleclypse** [comment]
All missions completed fine on 
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-5682-g0f8f059 [64-bit]


Unable to confirm bug.
