### ISSUE TITLE
Suggestion: Add a new City-only Core mod

### ISSUE THREAD

**Issue by RedShakespeare** [CleverRaven/Cataclysm-DDA#39901]
# Is your feature request related to a problem? Please describe.
Some of my friends who is crazy about this game always love to challenge themselves with high difficulties, e.g., 50 times quantity of zombies with 365 days' evolution after the cataclysm begins. One of them tried to set the city distance to 0, but he was disappointed to see there are still lots of space between buildings (such as farms and cabins).
# Describe the solution you'd like
Add a new Coremod where there're nothing but infinite cities and crowds of zombies. Since there's already a rural coremod, how about an urban one as well?

# Describe alternatives you've considered
Maybe we can let the player choose (not) to generate empty space in town.

**Comment by LyleSY** [comment]
I know this is a really popular way to play and it's something I've done and enjoyed. I have my horrific skeletal claws full with DinoMod, but if you or someone else wants to make it happen, I think that's great. https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/MODDING.md You also might find it helpful to talk with the other mod beings on the Discord if you're not already on it https://discord.com/invite/jFEc7Yp
