### ISSUE TITLE
Random error, not sure what causes it

### ISSUE THREAD

**Issue by RafeHaab** [CleverRaven/Cataclysm-DDA#39914]
Here's the log.

-----------------------------------------
21:23:18.007 : Starting log.
21:23:18.008 INFO : Cataclysm DDA version 0.E-1219-gf47f2ee
21:23:18.023 INFO : SDL version used during compile is 2.0.5
21:23:18.023 INFO : SDL version used during linking and in runtime is 2.0.5
21:23:18.121 WARNING : opendir [./sound/] failed with "No such file or directory".
21:23:18.147 INFO : Number of render drivers on your system: 4
21:23:18.147 INFO : Render driver: 0/direct3d
21:23:18.147 INFO : Render driver: 1/direct3d11
21:23:18.147 INFO : Render driver: 2/opengl
21:23:18.147 INFO : Render driver: 3/software
21:23:18.177 INFO : Active renderer: 0/direct3d
21:23:18.461 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
21:23:18.520 INFO : Language is set to: 'en'
21:23:19.447 WARNING : opendir [./mods/] failed with "No such file or directory".
21:23:35.007 WARNING : opendir [./save/Grass Valley/mods] failed with "No such file or directory".
21:23:43.144 INFO : Loaded tileset: retrodays+
21:26:34.936 ERROR : (error message will follow backtrace)
  #0
    (dbghelp: @0x641036[cataclysm-tiles.exe+0x241036]), 
    (libbacktrace: Z21debug_write_backtraceRSo+0x56@0x641036),
    (libbacktrace: 0x641036    [unknown src]:0    [unknown func]),
  #1
    (dbghelp: @0x641aca[cataclysm-tiles.exe+0x241aca]), 
    (libbacktrace: Z8DebugLog10DebugLevel10DebugClass+0x34a@0x641aca),
    (libbacktrace: 0x641aca    [unknown src]:0    [unknown func]),
  #2
    (dbghelp: @0x6453a6[cataclysm-tiles.exe+0x2453a6]), 
    (libbacktrace: Z12realDebugmsgPKcS0_S0_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x76@0x6453a6),
    (libbacktrace: 0x6453a6    [unknown src]:0    [unknown func]),
  #3
    (dbghelp: IMG_LoadWEBP_RW+0x11acfc@0x128dbdc[cataclysm-tiles.exe+0xe8dbdc]), 
    (libbacktrace: Z12realDebugmsgIJEEvPKcS1_S1_S1_DpOT_+0x24c@0x128dbdc),
    (libbacktrace: 0x128dbdc    [unknown src]:0    [unknown func]),
  #4
    (dbghelp: IMG_LoadWEBP_RW+0x34b011@0x14bdef1[cataclysm-tiles.exe+0x10bdef1]), 
    (libbacktrace: ZN9visitableI4itemE11remove_itemERS0_+0xd1@0x14bdef1),
    (libbacktrace: 0x14bdef1    [unknown src]:0    [unknown func]),
  #5
    (dbghelp: @0x83e90e[cataclysm-tiles.exe+0x43e90e]), 
    (libbacktrace: ZN4item7processEP6playerRK8tripointbf16temperature_flag+0x11e@0x83e90e),
    (libbacktrace: 0x83e90e    [unknown src]:0    [unknown func]),
  #6
    (dbghelp: @0x9dd1a2[cataclysm-tiles.exe+0x5dd1a2]), 
    (libbacktrace: ZN3map13process_itemsEbPFbR10item_stackR14safe_referenceI4itemERK8tripointRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEf16temperature_flagESG_.constprop.2330+0x1782@0x9dd1a2),
    (libbacktrace: 0x9dd1a2    [unknown src]:0    [unknown func]),
  #7
    (dbghelp: @0x9dd42a[cataclysm-tiles.exe+0x5dd42a]), 
    (libbacktrace: ZN3map20process_active_itemsEv+0x2a@0x9dd42a),
    (libbacktrace: 0x9dd42a    [unknown src]:0    [unknown func]),
  #8
    (dbghelp: @0x76af50[cataclysm-tiles.exe+0x36af50]), 
    (libbacktrace: ZN4game7do_turnEv+0x680@0x76af50),
    (libbacktrace: 0x76af50    [unknown src]:0    [unknown func]),
  #9
    (dbghelp: IMG_LoadWEBP_RW+0x699178@0x180c058[cataclysm-tiles.exe+0x140c058]), 
    (libbacktrace: main+0x10f8@0x180c058),
    (libbacktrace: 0x180c058    [unknown src]:0    [unknown func]),
  #10
    (dbghelp: @0x4013ed[cataclysm-tiles.exe+0x13ed]), 
    (libbacktrace: _tmainCRTStartup+0x23d@0x4013ed),
    (libbacktrace: 0x4013ed    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crtexe.c:336    __tmainCRTStartup),
  #11
    (dbghelp: @0x4014fb[cataclysm-tiles.exe+0x14fb]), 
    (libbacktrace: WinMainCRTStartup+0x1b@0x4014fb),
    (libbacktrace: 0x4014fb    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crtexe.c:186    WinMainCRTStartup),
  #12
    (dbghelp: BaseThreadInitThunk+0xd@0x770159cd[kernel32.dll+0x159cd]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #13
    (dbghelp: RtlUserThreadStart+0x1d@0x7717385d[ntdll.dll+0x5385d]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
Backtrace emission took 1 seconds.
src/visitable.cpp:531 [item visitable<T>::remove_item(item&) [with T = item]] Tried removing item from object which did not contain it

**Comment by lbnesquik** [comment]
I've suffered this bug multiple times. Sometimes when starting a new world, others when stepping on a particular spot on the map.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/experimental-crashes-tried-removing-item-from-object-which-did-not-contain-it/23447/2
