### ISSUE TITLE
Bug with starting location

### ISSUE THREAD

**Issue by DmitriyAAA** [CleverRaven/Cataclysm-DDA#39929]
"Unable to generate a valid starting location(Refugee Center), please report this failure."

**Comment by DmitriyAAA** [comment]
> Unable to generate a valid starting location(Refugee Center), please report this failure.

**Comment by Zireael07** [comment]
What map settings (city size, etc.)?

**Comment by DmitriyAAA** [comment]
Standard settings, except for the season duration of 31 days, start time of 60 and generation of random NPCs

**Comment by Wolfechu** [comment]
Also had this earlier, default settings, on a 'food truck' start

**Comment by Night-Pryanik** [comment]
Basically the same as #35376.
