### ISSUE TITLE
Magiclysm Suggestion: Move magic creature spawns to later dates?

### ISSUE THREAD

**Issue by HeartwawyHorror** [CleverRaven/Cataclysm-DDA#39925]
# Is your feature request related to a problem? Please describe.
Forests and swamp biomes become much more difficult to survive in due to the new magical creatures. I feel discouraged from playing innawoods due to the combat prowess of owlbears and trolls.

# Describe the solution you'd like
Moving the spawn dates of some of the more difficult creatures to later in the Catalcysm (1 week to 1 month.)

# Describe alternatives you've considered
Not changing spawn dates.

**Comment by KorGgenT** [comment]
I never really considered innawoods viable for magiclysm, as you would have absolutely no way to learn new spells.

**Comment by FuelType-Memes** [comment]
You can learn new spells as innawoods if you come across map specials with book drops
