### ISSUE TITLE
Bug with the mod "Tanks and Other Vehicles mod" using the ID "turretframe"

### ISSUE THREAD

**Issue by TheMrBakit** [CleverRaven/Cataclysm-DDA#39921]
# Describe the bug

The issue is with the mod "Tank" there is some area that use the id "turretframe" and should be something else (my guess is "turret_mount").

# Steps To Reproduce

Load a game with the tank mod (Tanks and Other Vehicles)

# Expected behavior

Don't have the Error on loading the Tanks and Other Vehicles mod.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-1220-g2876ece [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    PKs Rebalancing [PK_REBALANCE],
    PRM++ Patch [noctpk],
    Cataclysm++ [Cata++],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Necromancy [necromancy],
    No Fungal Monsters [No_Fungi],
    PK - No Doom Monsters [PK_No_Doom],
    PK - No Fungal Monsters [PK_No_Fungi],
    PK - No Triffids [PK_No_Triffids],
    Classes and Scenarios Mod [more_classes_scenarios],
    Classic Roguelike Classes [RL_Classes],
    Stats Through Skills [StatsThroughSkills],
    Manual Bionic Installation [manualbionicinstall],
    Disable NPC Needs [no_npc_food],
    Garden Pots [growable-pots],
    Hydroponics [hydroponics],
    Magiclysm [magiclysm],
    Aftershock [aftershock],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots]
]

# Additional context

 DEBUG    : Tried to get invalid vehicle part: turretframe

 FUNCTION : const T& string_id<T>::obj() const [with T = vpart_info]
 FILE     : src/veh_type.cpp
 LINE     : 150

**Comment by anothersimulacrum** [comment]
This mod is no longer supported, and so this issue is invalid.
However, @Soup-de-Loop may be able to provide some sort of guidance for you on how to fix it, or otherwise.

**Comment by Soup-de-Loop** [comment]
Sorry about the late response: For context, known issue: it will not cause a segfault (unless you try to use the turretframe elsewhere) however, due to a smart cookie who added the vanilla turret mount to the tank vehicles at some point on the same slots as where the turretframes are. At most, it will throw an error about a deleted vehiclepart every time a military vehicle from Tankmod is spawned in worldgen- I will PR an already tried and true hotfix for this once I've finished modernising blazemod, it's low priority until I get to actually compartmentalising different features.
