### ISSUE TITLE
Crash when serializing vehicle item location after vehicle is unloaded or destroyed

### ISSUE THREAD

**Issue by Qrox** [CleverRaven/Cataclysm-DDA#39930]
# Describe the bug
As the title says. When serializing `player::ammo_location`, the game can crash if `ammo_location` is a vehicle location.

# Steps To Reproduce
1. Spawn a shopping cart, a sling, and some rpg dice.
2. Put the rpg dice into the cart.
3. Select sling in the inventory menu and `r`eload to select the rpg dice as favorite ammo.
4. Smash the cart until it completely shatters, or walk away from the cart until it's unloaded.
5. Try save the game.
6. Game crashes.

This probably can also happen when the item location is used elsewhere in the code, but I have only tested serialization.

# Expected behavior
Game does not crash.

# Additional context
I think there are multiple issues here that need addressing:
1. `item_location::impl::item_on_vehicle` uses a `vehicle_cursor` to save a pointer to the target vehicle. This pointer can be invalidated anytime and turn into a dangling pointer, which causes the crash.
2. The player shouldn't be able to select favorite ammo from a vehicle, only from their inventory, because vehicle items can be far from the player the next time they fire their weapon.

**Comment by satheon49** [comment]
I could not verify any crashes with the mentioned vehicle smashing. But having an unloaded vehicle as ammo_location is fixed by #50525 so this can probably be closed.
