### ISSUE TITLE
Formula of spell failure not sensible

### ISSUE THREAD

**Issue by martinrhan** [CleverRaven/Cataclysm-DDA#39952]
# Is your feature request related to a problem? Please describe.
I read the document of Magiclysm and found the formula of spell failure not sensible.
the formula is:
`( ( ( ( spell_level - spell_difficulty ) * 2 + intelligence + spellcraft_skill ) - 30 ) / 30 ) ^ 2`
I can understand that ( ( spell_level - spell_difficulty ) * 2 + intelligence + spellcraft_skill ) = the accumulated ability to cast the spell and when it get to 30, the spell is not possible to be failed.
However, when that value grows further, the failure changce get to more than 0 again and when it is 60 it will not be possible to get the spell successfuly casted.
It dosen't make any sense that when I get into a very experienced and skilled degree I become less capable to cast the spell.

# Describe the solution you'd like
I have figured out another formula
`(1- ( ( spell_level - spell_difficulty ) * 2 + intelligence + spellcraft_skill ) / 30 ) `
if negative, change it to 0.
then squre it.

**Comment by martinrhan** [comment]
just checked it out in the game. I edited my character's spellcraft skill to 80, and all the spell's failure chance is 0. That means the document is wrong. It need to be updated

**Comment by KorGgenT** [comment]
see https://github.com/CleverRaven/Cataclysm-DDA/blob/5926e6e99ecae668923857da6f27f476f708fbff/src/magic.cpp#L732-L740

if you would like to update the documentation such that it is explicit about failure chance reaching 0, go ahead, though i see no need to update the formula to something similar enough.
