### ISSUE TITLE
Construction menu ambiguity between "Floor" and "Roof"

### ISSUE THREAD

**Issue by SgtMustang** [CleverRaven/Cataclysm-DDA#39972]
The nomenclature used for floor and roof constructions does not adequately inform the player of their behavior.

Both "_Roof_" and "_Floor_" constructions actually create floor terrain; "_Roof_" constructions are floors **with** the _INDOORS_ flag, and "_Floor_" constructions are floors **without** the flag. In some cases, there is virtually no way of obviously intuiting this distinction in game.

# Describe the solution you'd like

Names and descriptions for the floor/roof construction recipes and their corresponding terrain tiles should be reconciled for clarity. Roofed and Unroofed variants using the same materials should be brought in alignment.

"Roof" should only be used as the name for recipes that create roofs as seen from the current z-level. For example, the shingle roofs or flat roofs you can see when climbing buildings are "true" roofs, but a wooden floor with the _INDOORS_ tag is not a roof.

# Describe alternatives you've considered
I'm not sure there's any alternatives to this one. It's just a point where the construction recipes and in game terrains are not in total alignment and it creates confusion.

# Additional context

Here is an example change to the two wooden floor recipes.

### Build Wooden Floor
Construction ID: "constr_floor_noroof"

Post terrain ID: "t_floor_noroof"

Terrain Name:** "wooden floor"

Terrain Description: "Wooden floor created from boards, packed tightly together and nailed down. ~~Common in patios.~~"

Flags: [ "TRANSPARENT", "FLAMMABLE_HARD", "FLAT", "ROAD" ]

### ~~Build Roof~~ Build Wooden Floor (with roof)
Construction ID: ~~"constr_floor"~~ **"constr_floor_roofed"**

Post terrain ID: ~~"t_floor"~~ **"t_floor_roofed"**

Terrain Name: ~~"floor"~~ "roofed wooden floor"

Terrain Description: "~~Interlocking wooden tiles that are more than likely treated against fire, with wooden posts and beams supporting a roof.~~ Wooden floor created from boards, packed tightly together and nailed down. **_Integrated wooden posts and beams support the roof above._**"

Flags:  ["TRANSPARENT", "FLAMMABLE_HARD", "FLAT", "ROAD", **"SUPPORTS_ROOF"**, **"COLLAPSES"**, **"INDOORS"**]

I have never directly contributed to a Git project before, but if there is no current existing effort on this issue, I would be willing to go through the existing construction recipes and put together a revision that addresses this issue.

**Comment by Night-Pryanik** [comment]
> I would be willing to go through the existing construction recipes and put together a revision that addresses this issue.

Please do.
