### ISSUE TITLE
Cataclysm with curses on Windows becomes unresponsive when using the credits or MOTD windows from the main menu

### ISSUE THREAD

**Issue by luluyume** [CleverRaven/Cataclysm-DDA#39982]
# Describe the bug

Cataclysm becomes unresponsive when moving to either the Message of the Day or the Credits window from the Main Menu. It begins flashing between either of those windows and the Main Menu window. The only way to quit is Ctrl + C or killing the process. It is important to note that I tested on Ubuntu 16.04 LTS and the issue did not appear there on the same version (using make to build the same source).

# Steps To Reproduce

Load game using cataclysm.exe built using CMake with MSYS2 on Windows. Use the arrow keys to move to either the MOTD or the Credits. Game will become unresponsive and flash between those windows and the main menu.

# Expected behavior

There shouldn't be issues with running a curses build through Windows; about a month ago it was working as expected.

# Screenshots

![CCR2n8deUY](https://user-images.githubusercontent.com/43284013/80459433-3b2f4d00-88e7-11ea-8f22-400c95740a56.gif)

![OqhVQ9VHXE](https://user-images.githubusercontent.com/43284013/80459445-3ec2d400-88e7-11ea-862f-7d24359f6b94.gif)

# Versions and configuration

 - OS: Windows 10 version 2004 build 19041.207
 - Game Version: 0.D-14826-g1700745164 (built using CMake on Windows from commit 1700745, should be build 10592)
 - Graphics version: Terminal
 - Ingame language: English
 - Mods loaded: None

**Comment by Qrox** [comment]
I can't reproduce it on my MSYS2 build. Are you building with the ncurses lib from MSYS2 or building the wincurse port?

**Comment by ZhilkinSerg** [comment]
We do not really support Curses version on Windows and endorse using Tiles build (you can play it with disabled tilesets).

**Comment by luluyume** [comment]
@Qrox ncurses with MSYS2 and using CMake to build. Fresh install. I can test on a laptop I have as well in a day or two. 

@ZhilkinSerg That's fine, I'm not expecting this to be fixed at any rate - not like I'm playing on Windows w/ Curses. Just filing this as an issue so it's known.

**Comment by Qrox** [comment]
Well that's weird, it works perfectly fine on my build. Have you tried starting the game from the MSYS2 console?

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
