### ISSUE TITLE
Bleach and Lye share the same name in Spanish (Spain) -TRANSLATIONS-

### ISSUE THREAD

**Issue by Termineitor244** [CleverRaven/Cataclysm-DDA#39981]
# Describe the bug

The items "Bleach" and "Lye" share the same name in the Spanish (Spain) translation of the game, which in turn causes confusion in recipes and other instances.

The name of both of them is "Lejía", they have different descriptions but the name is exactly the same.

# Steps To Reproduce

1. Start a game and debug spawn the items "Bleach" and "Lye"
2. Change the game's language to Español (España)
3. Watch as both of them share the same name
OR
1. Just start the game in spanish and search in the debug "Lejía", there will be two different items with the same name.

# Expected behavior

That two different items be differentiated by two different names.

Why? Well, when you are crafting an item, and the recipe needs "Lejía" (And you don´t know that there are two), you can very well end crafting a different "Lejía" than the one you need (My case)

# Screenshots

In English:
![Lejía English 1](https://user-images.githubusercontent.com/53200489/80461395-d41b9380-88fa-11ea-975c-a90259f3ecd8.png)
![Lejía English 2](https://user-images.githubusercontent.com/53200489/80461404-d54cc080-88fa-11ea-96f6-7b501260b879.png)
In Spanish:
![Lejía Spanish 1](https://user-images.githubusercontent.com/53200489/80461401-d4b42a00-88fa-11ea-96f0-77dff4c07b66.png)
![Lejía Spanish 2](https://user-images.githubusercontent.com/53200489/80461397-d4b42a00-88fa-11ea-91b9-2bc70e9eb6c5.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-1275-g43adeb0 [64-bit]
- Graphics Version: Tiles
- Game Language: Español (España) [es_ES]
- Mods loaded: [
    Dark Days Ahead [dda],
    Desactivar necesidades de los PNJ [no_npc_food],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

# Additional context

This could rather be in the forum (?) for translations, if this shouldn't be here, then tell me and I will close the Issue and ask there.

Note: In Español (Argentina), this is not an issue, since the items are named "Lavandina" (Bleach) and "Lejía" (Lye), in Mexican Spanish a more appropriate name could be "Blanqueador" for bleach, but since this is the Spanish from Spain, I will stop myself from giving any suggestions for a different name.

**Comment by ZhilkinSerg** [comment]
Translations are done via Transifex - see https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/TRANSLATING.md. Anyone can join and participate there.

**Comment by Termineitor244** [comment]
> 
> 
> Translations are done via Transifex - see https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/TRANSLATING.md. Anyone can join and participate there.

The thing is, I´m not from Spain, so I don´t know how is best translated "bleach" and "lye" to differentiate between them, but I will ask later to the translators to see if they have any ideas
