### ISSUE TITLE
sidebar portrait view on phone

### ISSUE THREAD

**Issue by linonetwo** [CleverRaven/Cataclysm-DDA#39985]
# Describe the solution you'd like
Support portrait view on phone, that place sidebar on the top or bottom

# Additional context
Sometimes it's more convenient to hold the phone in portrait view, instead of landscape view.
If this is supported, it will looks like a NDS player.

**Comment by ZhilkinSerg** [comment]
Not really feasible with current UI  and rendering  implementation, but maybe in some distant future...
