### ISSUE TITLE
Crash on persuading NPC

### ISSUE THREAD

**Issue by mattbak00** [CleverRaven/Cataclysm-DDA#39996]
# Describe the bug

When talking to the starting NPC and trying to persuade him to give me a usefull item the game crashes. This happened when starting a new game. The first crash was after I accepted a quest, the second crash happened when I tried to persuade a NPC to give me something usefull for the second time. I have been unable to reproduce the bug after those two times.

# Steps To Reproduce

1. Start a new game
2. Talk to starting NPC
3. Ask for usefull item
4. Persuade
5. Then it crashes

# Expected behavior

That there is no crash.

# Versions and configuration

- OS: Windows 10 version 1909
- Game version: 0.E stable
- Graphics version: tiles
- Ingame language: English
- Mods loaded: dda, boats, stats through skills, generic guns, alternative map key, disable NPC needs, Fuji's military profession pack, SpeedyDex

# Additional context

[CDDA crash logs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4547920/CDDA.crash.logs.zip)

**Comment by Qrox** [comment]
Sounds like #39238. Please test in the latest experimental or 0.E release and see if this still happens.
