### ISSUE TITLE
Smoking rack turning normal meat into mutant meat and vice versa 

### ISSUE THREAD

**Issue by Termineitor244** [CleverRaven/Cataclysm-DDA#40007]
# Describe the bug

When you put smoked meat in a smoking rack, if there was both smoked mutant meat and smoked normal meat, it will combine the two of them and give you in return all the meat but now turned into mutant meat, or all the meat but now only normal meat

# Steps To Reproduce

1. Get a smoking rack, smoked meat and smoked mutant meat (This didn't happened for me when I smoked them first)
2. Insert food for smoking, select the smoked meat (It doesn't differentiates between normal or mutant in the menu) and put all the meat in the smoking rack. 
3. You don't have to wait for the smoking, just empty the rack and all your meat would have turned in normal smoked meat, or mutant smoked meat.

# Expected behavior

To have the smoking rack differentiate between normal and mutant meat.

# Screenshots
![meat 1](https://user-images.githubusercontent.com/53200489/80560353-3bdae880-89a6-11ea-93b5-028b66a0b219.png)
![meat 2](https://user-images.githubusercontent.com/53200489/80560357-3c737f00-89a6-11ea-8ae5-6b292333dfd0.png)
![meat 3](https://user-images.githubusercontent.com/53200489/80560356-3c737f00-89a6-11ea-8c6f-eed68bd5c325.png)
![meat 4](https://user-images.githubusercontent.com/53200489/80560355-3c737f00-89a6-11ea-9afc-e9bc70c53b17.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-1275-g43adeb0 [64-bit]
- Graphics Version: Tiles
- Game Language: Español (España) [es_ES]
- Mods loaded: [
    Dark Days Ahead [dda],
    Desactivar necesidades de los PNJ [no_npc_food],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

# Additional context

[Smoking rack bug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4549737/Smoking.rack.bug.zip)
The save just before putting the meat in the rack.

**Comment by int-ua** [comment]
It can also do the opposite in my experience. It was already reported in #39586 but thank you for confirmation.

**Comment by Termineitor244** [comment]
> 
> 
> It was already reported in #39586 but thank you for confirmation.

Oh, no no no, I searched before doing my report, the problem is similar, but not the same, you see, I **did not** cooked anything, I just put the meat in the rack, and then put it out, without turning on the smoker, the core problem could be the same, but I thought it would be better to provide with a different occurrence in case the core problem is different for both issues.

**Comment by Termineitor244** [comment]
Confirmed that this bug still happens in a recent version of the game, the smoking rack still fuses the two different meats when you put them in...

**Comment by Burnrate** [comment]
Just wanted to say I had this happen in recent experimental:

build type: windows-tiles-x64
build number: 2021-05-14-1915
commit sha: b4db09430a4329ec4f1338eab749de1fedf92eb4
commit url: https://github.com/CleverRaven/Cataclysm-DDA/commit/b4db09430a4329ec4f1338eab749de1fedf92eb4
