### ISSUE TITLE
Unloading items should not pick them up

### ISSUE THREAD

**Issue by molkemon** [CleverRaven/Cataclysm-DDA#40000]
# Is your feature request related to a problem? Please describe.
When I specifically choose to unload an item rather than pick it up, it should be pretty clear that I do not want to pick up that teddy bear, I just want the batteries. It is especially infuriating because sometimes this causes you to exceed volume and drop random stuff. 

# Describe the solution you'd like
Unload the item, put the fuel/magazine/whatever in the inventory and leave the item itself where it is. 

# Describe alternatives you've considered
I guess booze is always a solution...

**Comment by wapcaplet** [comment]
This issue has come up before and unfortunately never met with a fix. One recent related ticket #38206 was closed due to inactivity.

**Comment by RoyBerube** [comment]
This looks like the offending code. The item is picked up and placed in inventory before getting unloaded.

https://github.com/CleverRaven/Cataclysm-DDA/blob/86770f4e5c1f6032e03f56bf2b432d6af5d51a28/src/avatar_action.cpp#L1279-L1282

**Comment by RoyBerube** [comment]
#37023 Was a bug fix a few months ago for unloading items from an adjacent square. Methinks it is related to this issue.
