### ISSUE TITLE
Game crashes upon returning to my base

### ISSUE THREAD

**Issue by LordPancitoFresco** [CleverRaven/Cataclysm-DDA#40001]
# Describe the bug

The game crashes as i auto-walk back into my base, i have no real idea of what it causes it but i suspect something to do with npc's, since i had 3 of them there reading books by themselves. I play with the third party mod named Arcana so this may or may not be something to do with that mod.

# Steps To Reproduce

1-Open Map, directly below of the location of the player its the evac shelter with a note called "My base"
2-Autowalk (or just walk normally) straight south to said evac shelter

# Expected behavior

"i expected the game to not crash"?
i dont understand what this part means, sorry

# Versions and configuration

    -- OS: Windows 8.1 (pretty pirated and cracked, not updated either)
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E [32-bit]
- Graphics Version: Tiles
- Game Language: Español (España) [es_ES]
- Mods loaded: [
    Dark Days Ahead [dda],
    Desactivar necesidades de los PNJ [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Arcana and Magic Items [Arcana],
    Magiclysm [magiclysm],
    DinoMod [DinoMod]

# Additional context
I tried updating to the last experimental version 0.E Tiles-10590 and also the lastest build of the arcana mod but the game still crashes regardless. 
I put the save folder and the crash.log and debug.log all in the same .zip
I took this files from the original 0.E folder, but it still does exactly the same on the experimental version
I had the game in spanish btw.

[save folder + crash and debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4548866/save.folder.%2B.crash.and.debug.zip)

**Comment by ZhilkinSerg** [comment]
Does not crash for me.

**Comment by Dacendeth** [comment]
Crashed for me consistently walking straight south, if i dismounted It wouldnt crash. If I dismounted walked near and got back on before npc trying to heal me got to me  it would crash. If i walked near, debug killed all the npcs and then remounted it wouldnt crash. Debug healed myself to full and moved while mounted south, didnt crash. Just a shot in the dark but maybe something to do with npc trying to path to heal character that is mounted?

**Comment by Qrox** [comment]
It seems that in `npc::execute_action`, `patient` is null when the player is riding a horse. Not sure what exactly caused that to happen.
