### ISSUE TITLE
Massive lag between player inputs while there's line of sight to stacked vehicles

### ISSUE THREAD

**Issue by DillonSimeone** [CleverRaven/Cataclysm-DDA#40020]
# Describe the bug

From time to time, though the game you'll hear a lot of smashing. Easily thousands of times each second...

This is most likely vehicles falling onto top of each other across z-levels, and instead of turning into wreckages, end up smashing against each other inside the same tile thousands of times each second.

No lag occurs until you have line of sight to those stacked vehicles. 

I tried turning off animation, but that did not affect the lag, sadly. My first guess was that the vehicles was turning 100~ time a second.

Default animation time is 10ms... So 10ms * 100 = 1 second lag each second as the vehicles' movements is rendered. 

Disabling Z-level seems to have no effecst too. 

# Steps To Reproduce

(If testing without my save)
1. Make new world, find a noffice tower.
2. Enter office tower, find some office chairs (Or spawn in a bunch)
3. Bring office chairs to windows at the edge, push all chairs off the same ledge on same x and y coords, repeating on the other z-levels.
4. Go down to the ground and view the office chair pile-up. There should be a massive lag between your inputs when you have line of sight to the horrors.

(If testing with my save, attached to this report at the bottom)
1. Start up my save, ignore all of the scary spooky red texts that appears until the world loads.
2. Move east until you have line of view to the office chair.
3. Move back west out of line of sight, notice the difference in the lag between inputs.

# Expected behavior

Office chairs exploding on impact on ground, on each other across z-levels, or just bouncing off each other. 

# Screenshots

![image](https://user-images.githubusercontent.com/21962421/80654681-b6047f00-8a31-11ea-913d-f9179b7591b6.png)

![image](https://user-images.githubusercontent.com/21962421/80654402-ffa09a00-8a30-11ea-94d0-03b49c479805.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-1272-g3bdcb87 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    XEAS [XEAS],
    DinoMod [DinoMod],
    Crazy Cataclysm [crazy_cataclysm],
    My Sweet Cataclysm [my_sweet_cataclysm],
    More City Locations [cityside],
    No Rail Stations [No_Rail_Stations],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Arcana and Magic Items [Arcana],
    Graphical Overmap [Graphical_Overmap],
    Advanced Gear [adv_gear]
]

# Additional context

Save file: 
[Palmer Heights.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4555237/Palmer.Heights.zip)

Mods:
[mods.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4555238/mods.zip)

**Comment by DillonSimeone** [comment]
![image](https://user-images.githubusercontent.com/21962421/81621570-9bbc9080-93a3-11ea-93ae-76a97182b7f7.png)


![image](https://user-images.githubusercontent.com/21962421/81621583-a24b0800-93a3-11ea-85f0-366bdb050ab2.png)

This time, the chairs was bumping against eachother forever on the second floor of the tower. Wandering around on the ground level under the chairs did not cause any issues.

The zombies was being drawn to this square from far and wide. (Wander Spawn enabled)

I noticed that there was a lot of skeleton juggs. Most was falling from the other levels in the office tower down to the ground level under the noisy chair bumpings. Look like the juggs arrived on force on the ground level, knocked out walls while the juggs on the other floors did the same.

**Comment by Aivean** [comment]
I think this was fixed in #45515. I cannot reproduce it now. 

Feel free to reopen if it's still valid.
