### ISSUE TITLE
Getting review rights for RU translation branch of Transifex

### ISSUE THREAD

**Issue by CountAlex** [CleverRaven/Cataclysm-DDA#40032]
It was advised to me in #development channel of official Discord to make my request as GH issue.

# Is your request related to a problem? Please describe.
RU translation branch, at least its current segments, are almost completely unreviewed.

# Describe the solution you'd like
I'd like to get a review rights for RU translation branch aiming at checking and reviewing those entries.

# Describe alternatives you've considered
Giving those rights to someone else willing to work on it.

# Additional context
I've made tangible contribution to this branch so I hope that would back up my request.

**Comment by ZhilkinSerg** [comment]
CC: @BrettDong, @VlasovVitaly

**Comment by VlasovVitaly** [comment]
Hello. Please give your login name or email on transifex

**Comment by VlasovVitaly** [comment]
Done. Please clone

**Comment by CountAlex** [comment]
Thanks, clone what?

**Comment by VlasovVitaly** [comment]
i mean close issue
