### ISSUE TITLE
Increasing any skill increases strength substantially (100+)

### ISSUE THREAD

**Issue by DarkendTheMighty** [CleverRaven/Cataclysm-DDA#40038]
### Expected behavior
Skills increase normally, doesn't affect stats, at least not by increasing them (in this case strength) by the hundreds.
### Actual behavior
Skills increase normally, affects strength, increasing it by well over 100+ depending on how much your skill increases.
EDIT: Also affects NPCs. 
### Steps to reproduce the behavior
Made new world, only with the base game. Increased a single skill (archery) by one via debug menu.
Strength went up by one.
Increased all skills by 10
Strength is now 278
### Additional Context

Game version:0.E-1373-gdcc42a9 (tiles)
Operating system: Windows 10 Home, Build 1809
Mods active: Dark Days Ahead
Screenshot:
![Annotation 2020-04-30 182555](https://user-images.githubusercontent.com/45152594/80765515-351cb480-8b11-11ea-9d64-d572c732b711.png)

Save (along with entire world folder):
[Montmorenci.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4561710/Montmorenci.zip)

**Comment by ZhilkinSerg** [comment]
Did you fiddle with Stat Through Skills mod in a different world before creating this world?

**Comment by DarkendTheMighty** [comment]
Good question, no I did not (reminds me of the "defense" minigame leaking into my real world preventing me from leaving the invisible hospital in the subway). I'm not even sure I have the mod installed. Regardless I haven't used it since 0.C.

**Comment by matt32106** [comment]
Maybe your character is Thor without knowing it.

**Comment by DarkendTheMighty** [comment]
That would explain why my character always finds "Weapons of Asgard" relatively quickly...

**Comment by DarkendTheMighty** [comment]
Found the problem. Apparently another mod leaked into my worlds. The mod in question was something called "StatsAreBullshit". The mod ingame is called "Anime Bullshit". I have no idea how that mod affected my game or why I even have it. Looking at the "modinfo.json" it has:

    "type": "skill_boost",
    "stat": "str",
    "skills": [ "mechanics", "swimming", "bashing", "cutting", "melee", "throw", "driving", "survival", "tailor", "traps", "dodge", "stabbing", "unarmed", "barter", "computer", "cooking", "electronics", "fabrication", "firstaid", "speech", "archery", "gun", "launcher", "pistol", "rifle", "shotgun", "smg", "magic", "spellcraft" ],
    "skill_offset": 0,
    "scaling_power": 1.0

Apparently this mod made my strength scale with my stats. Pretty cool but not really my thing. Apparently made by Chaosvolt with the description "This is a terrible idea".
Pretty funny now that I think about it. Broken, but funny.

[StatsAreBullshit.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4562134/StatsAreBullshit.zip)
Enjoy if you want it. Consider my problem fixed until I somehow break the game again.
