### ISSUE TITLE
NPCs with Langourus get movespeed bonus.

### ISSUE THREAD

**Issue by Dacendeth** [CleverRaven/Cataclysm-DDA#40045]
# Describe the bug
If a npc has Languorous they receive a pretty sizable bonus to move speed. My guess is it's not properly updating and their current stamina is above their max stamina causing a speed bonus.

# Steps To Reproduce
Spawn an npc, check his current move cost and then mutate him with Languorous and watch his move cost improve and stay improved.

# Expected behavior
For a negative trait of poor stamina to not make my companion run faster.

# Screenshots
![image](https://user-images.githubusercontent.com/26881007/80788202-74212900-8b56-11ea-88b8-63ac4aa3291c.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-1373-gdcc42a9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

**Comment by anothersimulacrum** [comment]
If stamina is the case, then something is wrong with `Character::get_stamina_max()`.
In `npc::process_turn()`, the stamina is set to `get_stamina_max()` every minute if their stamina is less than the value returned by `get_stamina_max()`.

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/npc.cpp#L2783-2785
This is `get_stamina_max()` for reference. It should be accounting for mutation stamina modifiers.
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/character.cpp#L7237-L7244

**Comment by Dacendeth** [comment]
Well I can tell you if you mutate them to have more max stamina, they will be initially slowed but will regenerate their stamina up to their new max, and interestingly if you mutate them to languorous after that they will be even faster.
