### ISSUE TITLE
Bug with starting location

### ISSUE THREAD

**Issue by DmitriyAAA** [CleverRaven/Cataclysm-DDA#40051]
The bug with starting location "Refugee Center" is still relevant. It is unable to generate it.

**Comment by ZhilkinSerg** [comment]
Please do not ignore issue template. At a bare minimum report game version and reproduce steps.

**Comment by DmitriyAAA** [comment]
Version 0.E-1426-g0d2a3d9(tiles). I tried to generate world with scenario Safe Place and starting location Refugee Center. And it didn't work. The map settings are standart.

**Comment by Night-Pryanik** [comment]
Closing as a duplicate of #35376.
