### ISSUE TITLE
NPC's strength too low to use its starting weapon

### ISSUE THREAD

**Issue by mon-pad** [CleverRaven/Cataclysm-DDA#40058]
# Describe the bug

An NPC follower has 7 base strength, but the default weapon it was equipped with was a crossbow, requiring 8 strength to use. Despite being unable to use it, when trying to give them a worse weapon it says "My current weapon is better than this".

# Steps To Reproduce

# Expected behavior

Either for an NPC's default weapon to be one it is capable of using, or for them to accept a worse weapon on the condition that they cannot use their current weapon.

# Screenshots

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.E-1404-g1268e85 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Monsters [No_Fungi]
]

# Additional context

**Comment by natsirt721** [comment]
I've seen this happen with crossbow-wielding bandits too. Makes some of the early bandit-hunting missions very easy when they can't even shoot back.

**Comment by gcaliber** [comment]
This happens quite frequently with the starting NPC having a crossbow and low strength so they can't use it. They also refuse all other weapons that are not better than a crossbow and will continue to wield the crossbow and use it in melee when told not to use ranged weapons.

**Comment by actual-nh** [comment]
Would weapon_value (in melee.cpp - does both guns and melee weapons) checking meets_stat_requirements (in character.cpp), and returning 0.0 value for not meeting this, fix this for followers, at least? Or is there something more complex than that?
