### ISSUE TITLE
Item duplication while hauling and peeking upstairs

### ISSUE THREAD

**Issue by cirops** [CleverRaven/Cataclysm-DDA#40052]
# Describe the bug

If I have items on the ground on an upstairs, I press **\\** to start hauling them and I peek upstairs, it duplicates the items when I cancel out of peeking. 

# Steps To Reproduce

1. Go into an upstairs tile.
2. Put some items on the ground.
3. press the haul items key (**\\**).
4. Peek upstairs (**Shift+x**, **<**).
5. Press **Esc** to cancel out of peeking. 

# Expected behavior

Items do not get duplicated.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-1361-g6fb0324 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

I haven't been able to reproduce the bug on other savefiles, so I'm attaching the savefile/log in which this is occuring.

[bug-savefile.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4564343/bug-savefile.zip)

**Comment by int-ua** [comment]
Did you mean "peek downstairs" or are you in a three-story building? Are the stairs aligned?

**Comment by cirops** [comment]
I'm in a lab, level -1, on the up stairs tile, and I'm peeking upstairs (level  0/ ground). I suspect this has to do with the recent "nested container" mechanics infrastructure, because the error message I get similar to that of #39402

**Comment by wapcaplet** [comment]
I could not reproduce this in 0.E-9737-g511ddcb179. Peeking upstairs or downstairs causes hauling to be stopped, but the items are not duplicated.
