### ISSUE TITLE
Ability for snippets to change item names

### ISSUE THREAD

**Issue by LaVeyanFiend** [CleverRaven/Cataclysm-DDA#40059]
# Is your feature request related to a problem? Please describe.
I wanted to use snippets to show various manufacturers' variants on guns, without bloating the loot tables with duplicates of the same gun. However, you can only override item _descriptions_ currently.

# Describe the solution you'd like
Additional optional field on snippets that changes the name of the item.

# Describe alternatives you've considered
Not adding it.

# Additional context

**Comment by tenmillimaster** [comment]
This has other applications too, like all those potato chip duplicates, different sporty trainers (Nike, addidas, etc), and adding titles to all the various books.
