### ISSUE TITLE
SIGABRT when NPC/player suffers damage from fire

### ISSUE THREAD

**Issue by olanti-p** [CleverRaven/Cataclysm-DDA#40061]
# Describe the bug
The game crashes when NPC or player suffers damage from fire (or hot air?)

# Steps To Reproduce
1. Debug spawn a molotov
2. Light it
3. Drop it
4. Ignore the debug message about `visitable`, that is a separate bug
5. Take a stroll through the flames
6. Watch the game crash

I've also reproduced this crash by shooting near myself / an NPC with `fusion blaster rifle` or `XM-P plasma rifle`

# Expected behavior
Successful self-immolation

# Versions and configuration
- OS: Linux
    - OS Version: Ubuntu 20.04 LTS;
- Game Version: 0.E-1408-g61bbbe8a38 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4565877/crash.log)
[backtrace from gdb](https://github.com/CleverRaven/Cataclysm-DDA/files/4565884/bt.log)

**Comment by Dacendeth** [comment]
Previously the behavior of being on fire only damaged your legs and couldnt hurt you after your legs broke, now it seems to crash when your legs break.

**Comment by olanti-p** [comment]
Looks to be fixed as of f125d6ef. I just incinerated a dozen NPCs, and the crash didn't occur.

**Comment by kevingranade** [comment]
You monster.

**Comment by olanti-p** [comment]
OwO
