### ISSUE TITLE
[Magiclysm] Disproportionate crafting times for demon chitin and black dragon armor.

### ISSUE THREAD

**Issue by anothersimulacrum** [CleverRaven/Cataclysm-DDA#40070]
# Describe the issue

The time costs to create black dragon and demon chitin armor are fairly disproportionate:
The time taken for black dragon armor is generally upwards of a day:
(the 340 hour ones are the suits)
```
data/mods/Magiclysm/recipes/dragon_black.json:    "time": "70 h",
data/mods/Magiclysm/recipes/dragon_black.json:    "time": "340 h",
data/mods/Magiclysm/recipes/dragon_black.json:    "time": "30 h",
data/mods/Magiclysm/recipes/dragon_black.json:    "time": "30 h",
data/mods/Magiclysm/recipes/dragon_black.json:    "time": "30 h",
data/mods/Magiclysm/recipes/dragon_black.json:    "time": "30 h",
data/mods/Magiclysm/recipes/dragon_black.json:    "time": "30 h",
data/mods/Magiclysm/recipes/dragon_black.json:    "time": "30 h",
data/mods/Magiclysm/recipes/dragon_black.json:    "time": "70 h",
data/mods/Magiclysm/recipes/dragon_black.json:    "time": "340 h",
data/mods/Magiclysm/recipes/dragon_black.json:    "time": "30 h",
data/mods/Magiclysm/recipes/dragon_black.json:    "time": "30 h",
data/mods/Magiclysm/recipes/dragon_black.json:    "time": "30 h",
data/mods/Magiclysm/recipes/dragon_black.json:    "time": "30 h",
data/mods/Magiclysm/recipes/dragon_black.json:    "time": "30 h",
data/mods/Magiclysm/recipes/dragon_black.json:    "time": "30 h",
```
While the time costs for demon chitin armor are generally much lower:
(the really long one there is horse armor)
```
data/mods/Magiclysm/recipes/armor.json:    "time": "4 h",
data/mods/Magiclysm/recipes/armor.json:    "time": "2 h",
data/mods/Magiclysm/recipes/armor.json:    "time": "4 h",
data/mods/Magiclysm/recipes/armor.json:    "time": "2 h 40 m",
data/mods/Magiclysm/recipes/armor.json:    "time": "2 h",
data/mods/Magiclysm/recipes/armor.json:    "time": "17 h 30 m",
data/mods/Magiclysm/recipes/armor.json:    "time": "5 h",
```

# Expected behavior

Crafting time is somewhat similar between the two sets of armor. I don't think that it's intentional that black dragon armor takes so much time, when demon chitin does not, even if one is intended to be more complicated or harder to create than the other.

# Additional context

This could totally be an invalid issue. I asked @KorGgenT about it, and he asked me to make a github issue.

**Comment by KorGgenT** [comment]
i'm suspecting the chitin armor is too short. I did the dragon armor from very approximate leatherworking articles online.

**Comment by KorGgenT** [comment]
I imagined the chitin armor being worn over some kind of other armor to fill in gaps, where the armor itself just has leather straps to hold it in place, rather than a full-on leather armor like the dragonhide. I don't know exactly the impact that could have on the crafting time though.
