### ISSUE TITLE
You can't climb down ladders if there is a friendly NPC standing underneath it.

### ISSUE THREAD

**Issue by lbnesquik** [CleverRaven/Cataclysm-DDA#40078]
# Describe the bug
I was at a water washing station with a friendly NPC who were following me close. I went up a ladder inside a 1 tile wide space, only to be met with a doorway that was impossible for me to open. I couldn't come down EITHER because the NPC was in the way. 

My only option was to save scum or maybe endlessly wack at one of the concrete walls or metal door until it gave away. 

I should just be able to move down the ladder.

# Steps To Reproduce
1. Get a friendly NPC.
2. Go in a place such as this 
![image](https://user-images.githubusercontent.com/24830358/80869082-8dcd8800-8c9e-11ea-8192-ecdf17b6025d.png)
3. Get stuck because your dumbass '''''''friend'''''' wants to come up and doesn't understand you can't let them up.

# Expected behavior
NPC's should try and clear the way when you go down, regardless of their hostility honestly. 

# Screenshots

![image](https://user-images.githubusercontent.com/24830358/80869097-a0e05800-8c9e-11ea-9be7-cbf846194a0a.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-1404-g1268e85 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]

**Comment by natsirt721** [comment]
Possible dup of #37820

**Comment by lbnesquik** [comment]
Strange, it should be fixed.
