### ISSUE TITLE
Big zombies' corpses have unrealistically low density

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#40076]
# Describe the bug

Exactly what it says on the tin, their corpses are at 0.2-0.4 kg/L. What are they made of, feathers?

# Steps To Reproduce

Go find/summon skelly jugg or kevlar hulk, kill them, see their corpses are 200/875 and 200/625 kg/L respectively.

# Expected behavior

Regular zeds (and survivors, for that matter) are somewhat more dense than water. Seeing as hulks and skelejuggs are just big zombies with additional armor (which, too, shouldn't be weightless), their corpses should either take less space or weigh more. Which one exactly is, I think, for lorekeepers to decide.

# Versions and configuration

- OS: Windows 7x64
- Game Version: 0.E-1420-g7e4b8ce [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Aftershock [aftershock],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills],
    Magiclysm [magiclysm]
]

**Comment by ampersand55** [comment]
As I understand it, game volume is a measure of how much space is typically required to pack an object, not how much air it displaces, so it makes sense for skeletons to have low density as e.g. the interior of the ribcage also counts as its volume.

That doesn't explain the low density of kevlar hulks though.
