### ISSUE TITLE
[Magiclysm] Thermal dissipation CBM and internal climate control doesn't prevent demon spider fire damage

### ISSUE THREAD

**Issue by KingApep** [CleverRaven/Cataclysm-DDA#40088]
# Describe the bug
Using the thermal dissiption cbm which in theory prevents up to 2000 degrees farhenheit yet doesnt block the 'on fire' damage from the demon spider which must be considerably less than 2000 degrees fahrenheit or the damage wouldn't only be 24dmg/tick.

After activating both the thermal dissipation cbm and internal climate control the fire damage still continues until death.

# Steps To Reproduce

Activate Internal climate control and thermal dissipation cbms
Walk towards demon spider
Let it use fire spell on player character
Fire still burns PC to death

# Expected behavior

Thermal dissipation should block heat damage entirely but not melee damage or other abilities of the demon spider still allowing for a challenging but counterable if prepared fight.

# Versions and configuration
Magiclysm as of 03/05/2020

# Additional context

First bug report so please be forgiving of any mistakes and let me know improvements for going forward, cheers.

**Comment by KorGgenT** [comment]
from a balance perspective i'm not sure i like it. the thermal dissipation and internal climate control CBMs are more for "environment" while the demon spider is attacking you with magical fire damage. It makes sense that these would protect you from, say, standing in a laval tunnel or an ice lab however, but blocking fire damage should be more specific to magical items i think.

**Comment by kevingranade** [comment]
2000F is hyperbole, that's above the melting point of many metals.  If you want consistency it's the bionic description that needs fixing.

**Comment by Inglonias** [comment]
That's... a hell of an issue title, there. Imagine seeing that without context.

**Comment by KingApep** [comment]
Korgen just for future reference then; are you hoping to make magiclysm be balanced and have counters from only within magiclysm? I.e. spells vs spells rather than being able to use bionics/mutations to also overcome certain encounters? 
I just would have thought that allowing the player to have more options in preparing for encounters i.e. demon spiders in magiclysm, would be a good thing. But it's your creative project at the end of the day.

**Comment by KorGgenT** [comment]
not strictly, but these two CBMS totally nullifying all fire damage seems pretty bad from a balance perspective
