### ISSUE TITLE
[Magiclysm] Black Dragon Fear Aura stunlock

### ISSUE THREAD

**Issue by KorGgenT** [CleverRaven/Cataclysm-DDA#40083]
# Describe the bug

The Black dragon fear aura stunlocks you. The description of the stunlock is that you lose speed indefinitely, so perhaps the speed mod is being applied repeatedly. 

# Steps To Reproduce

Spawn an adult black dragon and stand in its fear aura. Debug invincibility advised.

# Expected behavior

You should just gain the debuffs once, at that level of intensity of the aura you're standing in. A majority of the aura is intensity 2.

# Versions and configuration

Magiclysm, as of 5/2/20

# Additional context

There are two possibilities I can think of right off the bat:
1. I wrote the json for the effect wrong
2. The field is applying the effect wrong

The first would be a json fix, but the second would require some more in depth C++ debugging.

**Comment by wapcaplet** [comment]
Could not reproduce in 0.E-7357-g86a33cec95. With a black dragon nearby, I was not stunned and had no trouble moving around while it attacked me:

![image](https://user-images.githubusercontent.com/238395/98431006-0d357d00-206f-11eb-88c2-7f2b686afd33.png)
