### ISSUE TITLE
Hauling while sorting is counter productive.

### ISSUE THREAD

**Issue by RogueYun** [CleverRaven/Cataclysm-DDA#40104]
# Describe the bug

After hauling loot into my basement base I often forget to turn off hauling before sorting and then a lot of laughable regrets ensue.

# Steps To Reproduce

- Stand on a pile of unsorted misc stuff.
- Turn on hauling with the backslash key
- Autosort with Shift + o, then o
- Chuckle a bit while all your hard sorting work goes down the tubes.

# Expected behavior

Hauling should be automatically toggled off before sorting. (no sense hauling while sorting)

# Screenshots

N/A

# Versions and configuration

0.E-63-g8abe67d (tiles)

# Additional context

N/A

**Comment by wapcaplet** [comment]
Can you be more specific about what happens after you initiate sorting with `O` then `o`?

When I set up some zones, haul items into the "Unsorted" zone, then sort with `O`, `o`, all the items are sorted correctly into the zones I have set up (Food, Books, Containers etc.). If some items remain unsorted on the ground, then my character keeps hauling them next time I move a space (and all the items I have already sorted remain in their places). So I cannot seem to reproduce the surprising behavior you are seeing, though I am only using a few items and a very simple zone setup.

That said, I agree that it makes sense for the hauling action to be stopped (either automatically or via a prompt) when you begin sorting items.

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Pop!_OS 19.10; Release: 19.10; Codename: eoan; 
- Game Version: 0.D-14971-gfd4f55c02b-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by RogueYun** [comment]
Hrmm. It might be that it goes wonky when you pass over already sorted zones? I admit I'm also using a slightly outdated version as well. Not by choice really. What seems to happen is that it attempts to sort and by the time it's done it's dragged everything to one spot. It also get's laggier and makes time pass faster as it progresses as it gets more and more things to haul.
