### ISSUE TITLE
Reloading bugs

### ISSUE THREAD

**Issue by mrkybe** [CleverRaven/Cataclysm-DDA#40118]
# Describe the bug

Have DIY revolver-shotgun.  Have buckshot in bandolier.  Press 'r' to reload, shotgun remains empty, ammo appears on the ground for some reason.  Pick up ammo from ground.  It's automatically placed in the bandolier, and is now negative somehow.

![image](https://user-images.githubusercontent.com/1518466/80933671-bcc52600-8d92-11ea-95e3-151acf1eae4c.png)

Save & Quit, reload the same file.

![image](https://user-images.githubusercontent.com/1518466/80933695-d36b7d00-8d92-11ea-8f4b-223c754ab464.png)

Saving and quitting keeps topping up the shotgun to 20/6 ammo.

# Versions and configuration

Version 0.E-1662-g686104e

# Additional context

Save: [Pocatello.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4572631/Pocatello.zip)

Add this mod to mods to not have errors, it just makes the cargo-capacity of vehicle most parts very extremely high.  [kybesmod.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4572633/kybesmod.zip)

**Comment by anothersimulacrum** [comment]
In the future, you can stick that mod in `mods/` in your save folder, and it'll automatically be loaded.
