### ISSUE TITLE
Liquid issues with #39406

### ISSUE THREAD

**Issue by RedShakespeare** [CleverRaven/Cataclysm-DDA#40119]
# Describe the bug

1. When trying to drink liquid with "[a]pply or use item", all liquid in container will leak onto the ground including the unit just drunk by the player.
2. One can [d]rop liquid item directly without unpacking the container, which gives access to **empty but sealed** tin cans or other things.
3. Same kind of containers will appear in one line in [e]xamine or "picking up"[g] lists, no matter whether they contain items or not. 

# Steps To Reproduce

Problem 1:
1. Make a player with a gallon jug of cheap wine.
2. Use [a]pply list to drink a unit of wine.
3. You will find the gallon jug empty and all wine on the ground dirty.

Problem 2:
1. Make a player with a medium tin can of broth.
2. Use [d]rop or [D]rop list to directly drop the broth instead of the can.
3. The broth is dropped onto the ground but the can remains sealed.

Problem 3:
1. Make a player with a plastic bottle of water and an empty plastic bottle.
2. Drop both bottles onto the ground.
3. [e]xamine the bottles.
4. You will find only one line named either "plastic bottles" or "plastic bottles with water", determined by the order of dropping.

# Expected behavior

... just what it should be

# Versions and configuration

- Game Version: 0.E-1713-gd15c896

# Additional words
Just need some adjustment about #39406

**Comment by BenlyAZ** [comment]
I also found myself unable to drink water from a jar using the (E)at command, as the game considered it spilled liquid.

**Comment by RedShakespeare** [comment]
> I also found myself unable to drink water from a jar using the (E)at command, as the game considered it spilled liquid

This problem may have been fixed in #40108 before I raise this issue so I didn't mention it here ... but yes, that's a related problem too. Thx for supplementary.

**Comment by Rivet-the-Zombie** [comment]
Liquids seem all kinds of wonky right now.

**Comment by RedShakespeare** [comment]
Yes...

Update:
Problem 1 can only be triggered by some very types of liquid like water, cheap wine and ammonia, but not liquid like clean water or broth. 
And...if the former kinds of liquid is spawned with containers ( either by debug menu or by spells ), when [a]pply-ing a debugmsg will occur.

![image](https://user-images.githubusercontent.com/44523519/80946104-e37d6e00-8e1f-11ea-9f2c-b61e64f89a96.png)

Looks like it is because the spawned items haven't get a location yet when the player trys to consume them. May also be related to `item::in_its_container()`  in item.cpp

**Comment by DillonSimeone** [comment]
Testing this on build 10689...

Select can of curry, `a`active... 

This menu comes up now. You can't consume it.

![image](https://user-images.githubusercontent.com/21962421/82745680-f529a580-9d3b-11ea-8c78-55ebb0653e0a.png)

*dumps onto floor*

Unloading them results in the same thing.

`E`ating them don't cause this weirdness, though. Selected a bottle of orange soda(2), then `E`at. 

![image](https://user-images.githubusercontent.com/21962421/82745700-2bffbb80-9d3c-11ea-8777-915b0ea23275.png)

Drank one unit of orange soda, leaving the rest in the bottle.

**Comment by DillonSimeone** [comment]
Hm, just noticed that if I eat a clam chowder, which is in a can, I get this error.

![image](https://user-images.githubusercontent.com/21962421/82745723-708b5700-9d3c-11ea-959a-75fd04008dda.png)

Trying to eat it afterward doesn't rigger this error again, oddly. Maybe it was the act of unsealing the can that got the code to go wonky?

**Comment by DillonSimeone** [comment]
Can confirm that you can drop stuff out of sealed cans/jars without unsealing them. Look at the message log on the right, notice that I dropped the jam, and that the jam can in my inventory is still sealed despite being empty. 

![image](https://user-images.githubusercontent.com/21962421/82745813-5b62f800-9d3d-11ea-8014-14a66daf2297.png)

**Comment by KorGgenT** [comment]
that should be opened as a different issue.

**Comment by DillonSimeone** [comment]
All right. I'm trying to cause the can bug to occur via the overmap editor now. 

Placing house_01 on the overmap in ungenerated areas then teleporting over.
![image](https://user-images.githubusercontent.com/21962421/82745928-b3e6c500-9d3e-11ea-8281-736c80f401af.png)

![image](https://user-images.githubusercontent.com/21962421/82745948-f3adac80-9d3e-11ea-80ee-46d7643580d2.png)

Walk into a placed house with a fridge AND cans in it, then attempt to pick up a can...
![image](https://user-images.githubusercontent.com/21962421/82745961-1e980080-9d3f-11ea-9b0f-1478df407de9.png)

![image](https://user-images.githubusercontent.com/21962421/82745954-0fb14e00-9d3f-11ea-96b6-38c3d8b59f4b.png)

Double check that I'm in the houses I placed...

![image](https://user-images.githubusercontent.com/21962421/82745970-33749400-9d3f-11ea-97fb-541a885aeadd.png)
