### ISSUE TITLE
Item disappears when you try to insert it into a partially-filled container

### ISSUE THREAD

**Issue by FuelType-Memes** [CleverRaven/Cataclysm-DDA#40115]
# Describe the bug
My aluminum bat disappears when I try to put it into my partially-filled utility vest

# Steps To Reproduce
1. Spawn an aluminum bat, a utility vest and 10 baseballs
2. Put on your vest
3. Pickup 10 baseballs
4. Wield your bat
5. Go to your inventory and try to insert the bat into the vest

# Expected behavior
I should get a notification that there is not enough space in my vest and keep the bat

# Versions and configuration
 - OS: Windows 10
 - Game Version: 0.E-1662-g686104e
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: None
 -->

# Additional context

**Comment by KorGgenT** [comment]
I'm currently looking into why it shows up in the screen where you holster the item, because can_contain() should return false

**Comment by KorGgenT** [comment]
so apparently there's some shenanigans where the holster item (the item you're trying to put the bat into) gets copied with no contents, making it seem like it actually can contain it. i've spent myself today, though, so i'll have to get back to it later if someone else doesn't get to it first.

**Comment by Erozaxx** [comment]
> so apparently there's some shenanigans where the holster item ....

Please check my issue reffered above (#40133) I think it is the same problem and there is no "holster" involved in my case. Yet the behaviour is simillar.

Also I think this:
> I'm currently looking into why it shows up in the screen where you holster the item, because can_contain() should return false

Is completely separate issue. In my case, if I wield in hands Quarterstaff and use "w" to unwield it, I get offered only the option to drop it on ground. But if I wield the Duffelbag with items inside, I get option to store it in inventory, which in turn autoinserts the Duffelbag into the Backpack, which does not have enough space and the item disappears.
