### ISSUE TITLE
Segmentation fault when attempting to wield item stored in wielded container

### ISSUE THREAD

**Issue by aoae23** [CleverRaven/Cataclysm-DDA#40129]
# Describe the bug

I observed a segmentation fault when attempting to wield an item stored in a wielded container. The items in question were a crowbar and a 3L glass jar. I had been screwing around with debug mode but upon encountering this crash, I did some testing and managed to reproduce it.

# Steps To Reproduce

1. Wield a 3L glass jar. Drop all clothes that can store equipment.
2. Pick up a crowbar with the 3L glass jar wielded.
3. Try to wield the crowbar. Select "Drop item" when prompted.
4. Observe the segmentation fault and feel a twinge of pain in your heart for Korg.

I also tested this with a makeshift crowbar and managed to reproduce it. I also reproduced it using a regular glass jar and a combat knife (which fits in the jar). So I think the second item can be anything that fits in the container.

# Expected behavior

The lack of a crash.

# Screenshots

N/A

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-1713-gd15c896 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    Graphical Overmap [Graphical_Overmap],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills]
]

# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4573207/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4573208/debug.log)
[Rheem Valley.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4573161/Rheem.Valley.zip)

**Comment by RedShakespeare** [comment]
> and feel a twinge of pain in your heart for Korg

wwwwwww that really hurts!
