### ISSUE TITLE
longbow can't crit

### ISSUE THREAD

**Issue by waveyl** [CleverRaven/Cataclysm-DDA#40121]
# Describe the bug

Supplement to #39565 . when shooting normal zombie with longbow or other less damage bow, I can't crit too. This makes most of makable bows useless in fact.
Sorry for my poor English.
# Steps To Reproduce

1.Make a survivor with archery and marksman skill 10+
2.Spawn a longbow and a bunch of wooden broadhead arrows.
3.Spawn some zombies
4.Shoot at it with [p]recise aim from point blank range

# Expected behavior

I interpret that as I should expect to occasionally do 8x10=80 damage as I crit. But I never seem to crit.
# Screenshots

![image](https://user-images.githubusercontent.com/22638873/80934688-df3f5980-8dfb-11ea-8bbe-d4df5114416e.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.E-1713-gb15c896 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]
# Additional context

**Comment by Dacendeth** [comment]
With the way the system works you can only crit things with max health around 65 with a longbow and a broadhead arrow, which for zombies are only crawling zombies, decayed zombies, and children. Not that I agree with that but that is how it works now if you want to crit more types of zombies you need a better bow.

**Comment by waveyl** [comment]
Yes, my purpose is just point this out. I think it needs some change.

**Comment by Tamiore** [comment]
>I think it needs some change,because not everybody can find compound bows, the best they could use is longbow.

The best you can always craft (because it's crafted from sticks and a few bones) is a composite bow.
And it has MUCH higher damage than a longbow.

Composite bow can and will crit most enemies that are not explicitly highly armored and/or have huge HP pools).

**Comment by waveyl** [comment]
> The best you can always craft (because it's crafted from sticks and a few bones) is a composite bow.
> And it has MUCH higher damage than a longbow.
> 
> Composite bow can and will crit most enemies that are not explicitly highly armored and/or have huge HP pools.

Oh, I ignore composite bow because it needs 12 strength which I always can't reach. So  if I want to pleasantly play with bow , I must have 12 strength, it's designed like this.  Right?

**Comment by Tamiore** [comment]
>Oh, I ignore composite bow because it needs 12 strength which I always can't reach. So if I want to pleasantly play with bow , I must have 12 strength, it's designed like this. Right?

Effectively, yes.

Damage is directly dependent on bow's poundage. Max poundage a character can draw depends on strength.  Thus, you do need high strength to use high damage bows.

**Comment by waveyl** [comment]
Understand,thank you.
