### ISSUE TITLE
When picking up items, they go in the "items worn" section of the inventory 

### ISSUE THREAD

**Issue by Noomene** [CleverRaven/Cataclysm-DDA#40122]
# Describe the bug

I left the game running in the background for some time, then when I returned I noticed two things: 

1- similar items which are normally grouped together (with the number in front of the name of the item) are now all separate and appear separately in the inventory, and 

2- when I pickup something it appears as worn instead of going to the inventory. Like when I pickup aspirin, it appears as if I wore the aspiring!! I also noticed that my inventory capacity is bigger than normal and 

3- I noticed that the memory usage of the game fell drastically, from 900mb to 100mb (I think memory was used by other foreground apps when I left CDDA running in the background)

I saved and quit, then reloaded the game. When the game reloaded I got the error message.

` DEBUG    : error: tried to put an item into a pocket that can't fit into it while loading.  err: No success
 FUNCTION : void item_contents::combine(const item_contents&)
 FILE     : src/item_contents.cpp
 LINE     : 85`

# Steps To Reproduce

1. Leave the game running for a long time.
2. Restart playing.

# Expected behavior

Usually similar items are grouped. And usually when you pckup something it does not get worn even though it was not meant to be worn. Like wearing Aspirin!!

# Screenshots

![image](https://user-images.githubusercontent.com/11027939/80935314-ab2f4e80-8d91-11ea-9593-09d016d6c854.png)

# Versions and configuration

- OS: Windows 7 x64
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-1662-g686104e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    C.R.I.T Expansion Mod [crt_expansion],
    Disable NPC Needs [no_npc_food],
    Stats Through Skills [StatsThroughSkills],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    MSX Alternative Floor Tiles [UDP_Old_Floor],
    No Fungal Monsters [No_Fungi]
]

# Additional context

**Comment by FuelType-Memes** [comment]
1. #40114 seems like a potential fix
2. This is the new inventory interface after #39406. Everything is stored like it's a holster. It will take some time to improve this interface
3. Not a CDDA bug? Please provide more info

**Comment by Noomene** [comment]
I was not aware that this was a new feature (nested inventory) being added and will probably take some time before it's completely ironed out.

However, I still had behaviour that was not supposed to happen: a "none" item appears in the inventory and can be dropped but does not, as the name suggests, drop anything.
