### ISSUE TITLE
Bleach and ammonia are spawning with incorrect units by default

### ISSUE THREAD

**Issue by aoae23** [CleverRaven/Cataclysm-DDA#40128]
# Describe the bug

Bleach and ammonia are spawned by default in gallon jugs. However, they only contain 0.50 L of content upon spawning - even though gallon jugs should store 3.75 L. This applies to both in-game spawning (such as in well stocked evac shelter basements) and debug spawning.

I suspect that other liquids that spawn in gallon jugs, such as milk, may have this problem as well - but I haven't tested it yet.

# Steps To Reproduce

1. Debug spawn bleach or ammonia with a container.
2. Marvel at the low volume of bleach and ammonia present.

# Expected behavior

Brand-new gallon jugs of bleach and ammonia contain 3.75 L, not 0.50 L, of liquid.

# Screenshots

Bleach: 
![image](https://user-images.githubusercontent.com/42950339/80941790-34498400-8d98-11ea-88f9-93d4d3907a2b.png)

Ammonia: 
![image](https://user-images.githubusercontent.com/42950339/80941820-40cddc80-8d98-11ea-86b9-d60b7f6ee7ae.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-1713-gd15c896 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    Graphical Overmap [Graphical_Overmap],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills]
]

# Additional context

**Comment by ymber** [comment]
I already fixed this once in #36723. Probably changes to the same code that reintroduced it.
