### ISSUE TITLE
Rename the projectile "Critical hit" as "Overkill"

### ISSUE THREAD

**Issue by RedShakespeare** [CleverRaven/Cataclysm-DDA#40124]
# Is your feature request related to a problem? Please describe.
In #39203 the projectile critical hit mechanism has been rewritten and now only if **critical damages 
 are larger than the monsters' max hp** will a critical hit appear. This is not in the least the definition of "critical hit" in common sense, nor is it the same as critical hit in melee attacks.

# Describe the solution you'd like
If the members have decided to change the mechanism like what it is anyway, maybe the projectile "critical hit" should be renamed as "overkill" to distinguish from melee critical hit and critical hit in any other games. 

# Describe alternatives you've considered
Adjust the critical hit again ( looks like this wouldn't get preference )

# Additional context
Not quite related to this issue, but it seems that neither do players need a current "critical hit" or overkill when hunting fragile animals, nor they are able to get one when fighting giant monsters. A white elephant if I may say so.

**Comment by kevingranade** [comment]
No thanks, sticking with critical hit.
