### ISSUE TITLE
Cannot reload the sewing kit with thread. Thread is gone, no reloading. 

### ISSUE THREAD

**Issue by romanpogosov-usa** [CleverRaven/Cataclysm-DDA#40125]
Cannot reload the sewing kit with thread. Thread is gone, no reloading. 

DEBUG    : tried to put an item in a container that cannot contain it

 FUNCTION : int item::fill_with(const itype&, int)
 FILE     : src/item.cpp
 LINE     : 8146

# Steps To Reproduce

1. Try to reload sewing kit with thread.
2. After reload - sewing kit is empty, thread is gone.

# Expected behavior

Reload should reload thread in a sewing kit.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-1713-gd15c896 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    Mining Mod [Mining_Mod],
    More Survivor Stuff [more_survivor_stuff],
    More City Locations [cityside],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

DEBUG    : tried to put an item in a container that cannot contain it

 FUNCTION : int item::fill_with(const itype&, int)
 FILE     : src/item.cpp
 LINE     : 8146

**Comment by Kouwed** [comment]
Same happened to me with wooden needle at latest update. Did not matter if i had wielded the needle or if it was in backpack

**Comment by Ivan-Shestakov** [comment]
Still happens on latest build. Neither wooden needle nor hobo stove can be loaded with charges. The charges (thread and tinder respectively) disappear.

**Comment by Stephen2** [comment]
Still happening in latest at hash 702b0b402d

**Comment by Ivan-Shestakov** [comment]
Yep, happens for all thread related tools - bone needle, wood needle, sewing kit, tailor's kit. 
Makes it impossible to fix-up clothing and backpacks :(

**Comment by Emotions211** [comment]
Also happens to repair kits. Misc. Repair kits will consume up to 200 duct-tape per try but never load it. Practically removes the ability to ever repair many items as repair kits don't spawn with charges and sewing/tailor kits on spawn with 50.

**Comment by kwl01skz** [comment]
the same bug on  oil lamps #40652 

I found the suspicious code at #39406 
@ZhilkinSerg

**Comment by Stephen2** [comment]
Legends!!!

**Comment by romanpogosov-usa** [comment]
Yay, can play now with the new code. thanks!!!!
