### ISSUE TITLE
Bucket problems (not sure if bug or feature)

### ISSUE THREAD

**Issue by Kouwed** [CleverRaven/Cataclysm-DDA#40136]
# Describe the bug

When you wield a bucket and pick up something you put it in the bucket in my case 7 withered plants showing 7 times.

# Steps To Reproduce

1.Wield empty bucket
2. Pick something up

# Expected behavior

Prompt or putting things in pack not in the bucket

# Screenshots

![image](https://user-images.githubusercontent.com/64781480/80961071-ce4e1280-8e12-11ea-8af2-21f1092d2398.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-1734-g6f79dc9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

<!-- Add any other context about the problem here.

**Comment by JerryLin1** [comment]
Getting fixed by that pr ^
