### ISSUE TITLE
Sell low and sell high, Hub 01 Gold Coin

### ISSUE THREAD

**Issue by oyydd** [CleverRaven/Cataclysm-DDA#40135]
# Describe the bug
Hub 01 Gold Coins selling price is more than 50

# Steps To Reproduce

1. bartering skill: 4
2. HUB 01 merchants nearby
3. Exchange  Hub 01 Gold Coin for Hub 01 Gold Coin
4. My price: 52.50, TA's price: 50
5. so....

# Expected behavior

# Screenshots
![2020-05-04 18-47-29屏幕截图](https://user-images.githubusercontent.com/34313916/80960274-2862ce00-8e3b-11ea-92e5-54fda42a80b4.png)

![2020-05-04 18-47-29屏幕截图](https://user-images.githubusercontent.com/34313916/80960336-3add0780-8e3b-11ea-9398-4abd11534579.png)

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 18.04.4 LTS; Release: 18.04; Codename: bionic; 
- Game Version: 0.E [64-bit]
- Graphics Version: Tiles
- Game Language: 中文 (天朝) [zh_CN]
- Mods loaded: [
    浩劫余生 [dda],
    替换小地图图标 [alt_map_key],
    发现玩家图标，retrodays版 [sees_player_retro]
]

# Additional context

[save.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/4609556/save.tar.gz)

**Comment by Night-Pryanik** [comment]
Please fill in the `Expected behavior` section.
