### ISSUE TITLE
Advanced inventory creates item called none

### ISSUE THREAD

**Issue by Kouwed** [CleverRaven/Cataclysm-DDA#40134]
When you try to move objects with advanced inventory game says it cannot find it and moves item none. This none item can be moved afterwards like any other item don't know its specifications.

It can also be placed in refrigerator.

# Steps To Reproduce

1. Open advanced inventory
2. Choose from your inventory to someplace
3. Move item

# Expected behavior

Item moves from my inventory to place i tried to move it with advanced inventory.

# Screenshots

![image](https://user-images.githubusercontent.com/64781480/80959956-87f7b400-8e10-11ea-9954-8fc871a117a7.png)

![image](https://user-images.githubusercontent.com/64781480/80960054-c1c8ba80-8e10-11ea-91b6-e8cc1e7b0991.png)

![image](https://user-images.githubusercontent.com/64781480/80960464-9abeb880-8e11-11ea-80b6-980179f98401.png)

Do not take a screenshot of the crashing window. Please provide the crash logs in the "Additional context" -->

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-1734-g6f79dc9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by sdp0et** [comment]
I get this along with an error.  I tried to move an item from  my inventory to the under a vehicle trunk or  the trunk itself.
![image](https://user-images.githubusercontent.com/5922308/81039601-261a6700-8e6f-11ea-8e52-f22308a2ff7d.png)
![image](https://user-images.githubusercontent.com/5922308/81039625-32062900-8e6f-11ea-8d14-59850fa265d3.png)

and if the tile already has a "none" in it, this extra error:
![image](https://user-images.githubusercontent.com/5922308/81039674-4ea26100-8e6f-11ea-9a32-0aae7b98e897.png)

**Comment by sdp0et** [comment]
Possible workaround: Looks like if I drop something with the drop command I can use Advanced Inventory to move things from the inventory to ground or storage for a while.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-10939.
