### ISSUE TITLE
Plastic bottles can be put in gallon jugs

### ISSUE THREAD

**Issue by RedShakespeare** [CleverRaven/Cataclysm-DDA#40130]
# Describe the bug

Plastic bottles and many more items can be put in containers like gallon jugs with large volume but rather smaller bottleneck caliber (in real world).

# Steps To Reproduce

1. Make a player with a gallon jug wielded.
2. Spawn a plastic bottle and drop it on the ground.
3. Try to pick up the bottle.
4. The bottle will be inside the jug.

# Expected behavior

There might be some more attributes which decides which items can be put in certain containers and which not. 

# Screenshots
![image](https://user-images.githubusercontent.com/44523519/80947044-e9744e80-8e21-11ea-90db-b8d218cbcb83.png)

# Versions and configuration

- Game Version: 0.E-1713-gd15c896
- Mods: dda and any other mods

**Comment by mrkybe** [comment]
At least with those really thin-plastic poland springs water bottles, you could probably get them into a gallon jug by twisting them up.  I don't imagine getting them out will be very practical though.

**Comment by Wolfechu** [comment]
Had it happen to me too; inadvertent fumbling with the new system left me with a bottle of forest honey inside a gallon jug; then somehow, I got the bottle out but the honey stayed inside the jug. I'm now available to do conjuring tricks at children's parties ;)

**Comment by woutershep** [comment]
![2020-05-04-134355_300x799_scrot](https://user-images.githubusercontent.com/11578180/80962524-7cef5480-8e0d-11ea-813b-2fc640219241.png)
:D

**Comment by Lamandus** [comment]
![grafik](https://user-images.githubusercontent.com/33199510/80987658-aa022e00-8e32-11ea-8b3e-0db24f1e8a77.png)

**Comment by ennob** [comment]
Maybe containers could have a stat that keeps track of the maximum size of individual objects that can be put in them, independent form the maximum storage capacity.

**Comment by Lamandus** [comment]
> 
> 
> Maybe containers could have a stat that keeps track of the maximum size of individual objects that can be put in them, independent form the maximum storage capacity.

we already got that. with Item_lengh and max_lengh.

**Comment by Zireael07** [comment]
@Lamandus: Item length implementation postdates this issue. Now that item length PR is merged, I believe this issue can be closed?

**Comment by Lamandus** [comment]
> 
> 
> @Lamandus: Item length implementation postdates this issue. Now that item length PR is merged, I believe this issue can be closed?

I am fully on your side here, but I am not the OP.

**Comment by RedShakespeare** [comment]
Fixed in #40186 & #40214
