### ISSUE TITLE
default datadir does not obey the PREFIX makeflag.

### ISSUE THREAD

**Issue by mssx86** [CleverRaven/Cataclysm-DDA#40140]
# Describe the bug
binary of the latest stable release looks for the game data under `/usr/share/cataclysm-dda` even if `PREFIX` is set to something other than `/usr` during make.

# Steps To Reproduce
1. build and install with:
`make ZLEVELS=1 RELEASE=1 LOCALIZE=0 BACKTRACE=0  USE_XDG_DIR=1 PREFIX="/opt/cataclysm-dda-0.e"`
2. simply run the `catacylsm` under `$PREFIX/bin/`.

# Expected behavior
for the game to look under `$(PREFIX)/share/catacylsm-dda` instead of `/usr/share/catacylsm-dda` by default.

# Versions and configuration
 - OS: x86_64 musl linux host
 - Game Version: 0.E (source obtained from [here]( https://github.com/CleverRaven/Cataclysm-DDA/archive/0.E.tar.gz))
 - Graphics version: ncurses
 - Ingame language: english but not relevant
 - Mods loaded: none

**Comment by mssx86** [comment]
interestingly, i rebuilt using with these flags instead, and it automatically looked at `/opt/cataclysm-dda-0.e/share/cataclysm-dda` for game data:
```
make \
 LUA=1         \
 ASTYLE=0      \
 ZLEVELS=1     \
 RELEASE=1     \
 LOCALIZE=0    \
 BACKTRACE=0   \
 USE_XDG_DIR=1 \
 LUA_BINARY="/usr/bin/lua5.2"    \
 PREFIX="/opt/cataclysm-dda-0.e"
```

**Comment by anothersimulacrum** [comment]
This is the relevant are of code [main.cpp:148-179](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/main.cpp#L148-L179).

**Comment by mssx86** [comment]
i've rebuilt once more with my original makeflag setup and it seems that i messed something up because it does look at the correct path for datadir.

i sincerely apologize.
