### ISSUE TITLE
Ammo pouch don`t accept pebble or marbles (bullet crossbow ammo)

### ISSUE THREAD

**Issue by Katanasoul91** [CleverRaven/Cataclysm-DDA#40146]
Ammo pouch don`t accept pebble or marbles

1. Get peebles or marbles in your inventory.
2. Select insert in the Ammo Pouch.
3. This problem only occurs with those two kinds of ammunition so far (bullet crossbow ammo)

Version 10622, problem already present since 201618

**Comment by KorGgenT** [comment]
![image](https://user-images.githubusercontent.com/30208401/82745327-fca77980-9d50-11ea-9a4b-1ed25a778cc3.png)
must be fixed.

**Comment by Katanasoul91** [comment]
I later found out the problem isn`t the type of ammo but an "all or nothing problem". Meaning if you have room for 10 of X item and you have 12 of it, the containers don`t allow you to put 10 in it, and 2 in somewhere else.
In 10614 (before the nest system) if you have 120 marbles and load the ammo pouch you have 60 in the pouch and the other 60 were in the inventory.
