### ISSUE TITLE
Drop leg pouches don't have any pockets.

### ISSUE THREAD

**Issue by Lamandus** [CleverRaven/Cataclysm-DDA#40142]
# Describe the bug
As said, drop leg pouches can't be used to carry items and are useless.

# Steps To Reproduce

Get drop leg pouches

# Expected behavior

Having pockets.

# Screenshots
![grafik](https://user-images.githubusercontent.com/33199510/80988834-57c20c80-8e34-11ea-990e-f625599d1221.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-1734-g6f79dc9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Graphical Overmap [Graphical_Overmap],
    Fewer Farms [Fewer_Farms]
]

# Additional context

**Comment by KorGgenT** [comment]
Yup, they sure don't.

**Comment by Orange01gaming** [comment]
Mine are loading magazines just fine.

**Comment by Maleclypse** [comment]
in the same vein police belts only have a single holster while the description lists multiple pouches (pockets) plus a holster.
