### ISSUE TITLE
Game systems don't deplete battery when the "Play anything for a while" option is used.

### ISSUE THREAD

**Issue by Moxanity** [CleverRaven/Cataclysm-DDA#40148]
# Describe the bug
Playing any kind of game system (handheld, game watch) via the "Play anything for a while" consumes no battery charge. Battery is consumed as normal when playing any of the games themselves.

# Steps To Reproduce
1. Use a game watch/handheld game system/etc.
2. Select "6 Play anything for a while."
3. Observe that battery has not depleted.

# Expected behavior
Battery to deplete as normal.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Jamuro-g** [comment]
looks like it is working now (build 11503)

**Comment by casswedson** [comment]
Fixed by #46693
