### ISSUE TITLE
Charcoal smoker gains no charges but consumes charcoal when reloaded

### ISSUE THREAD

**Issue by DeclanFrost** [CleverRaven/Cataclysm-DDA#40152]
Charcoal smoker gains no charges but consumes charcoal when reloaded. Tried with charcoal from a container, from a nearby surface, and from wielded charcoal.

# Steps To Reproduce

1. Spawn charcoal smoker.
2. Spawn charcoal.
3. [R]eload charcoal smoker.

# Expected behavior

Smoker gains charges, I lose charcoal.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-1734-g6f79dc9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Stats Through Kills [stats_through_kills]
]

**Comment by ZhilkinSerg** [comment]
Duplicate of #40125
