### ISSUE TITLE
Bandolier starting gear starts a -1 ammo

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#40166]
# Describe the bug

Profession starts with bandoliers of ammo.  Instead game starts with -1 ammo in each.

# Steps To Reproduce

1. Make a player with a uplifted enforcer, starts with bandoliers, and some ammo.
2. open your inventory.
3. See negative 1 for ammo. 
4. Walk around and drop exponential negative ammo with every step.  Might be related or separate bug.

# Expected behavior

Anything other than this.

# Screenshots

![Bandoliers at negative 1](https://user-images.githubusercontent.com/54345792/81026451-c8225b00-8e3f-11ea-9e6d-cd3864ed9148.png)
![duping multiplying negative ammo](https://user-images.githubusercontent.com/54345792/81026454-c9538800-8e3f-11ea-94c9-4a7da63c4eaf.png)

[Swatodon Test.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4578466/Swatodon.Test.zip)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-1739-g5de957a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Crazy Cataclysm [crazy_cataclysm],
    Mythical Martial Arts [MMA],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

 - OS: Windows 10

# Additional context
[Swatodon Test.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4578508/Swatodon.Test.zip)

Saved game attached

**Comment by Maleclypse** [comment]
Sidenote: you can load a gun with negative ammunition.  It doesn't work though.

**Comment by KorGgenT** [comment]
![image](https://user-images.githubusercontent.com/30208401/81212720-464b4280-8fa3-11ea-8d09-3cc59d98afba.png)
just a heads up when i checked this out this debug message popped up
