### ISSUE TITLE
Favored pockets

### ISSUE THREAD

**Issue by dissociativity** [CleverRaven/Cataclysm-DDA#40169]
# Is your feature request related to a problem? Please describe.
We've got nested containers now and that's neat.
So let's say I prefer my loot goes in a backpack or other large storage item until that's full unless otherwise specified instead of whatever clothing I happen to be wearing, I should to either make a numbered list of preferred pockets to put items in, or just a single favorite will do for now.

# Describe the solution you'd like
Allow one to set favored pockets for item pickups to default to, ideally a numbered priority list, I can organize my pant pockets and such later

# Describe alternatives you've considered
Don't do this and just favour largest pockets first? Just lemme fill my starting messenger bag with junk til it's full thanks so I can drop it loaded with stuff in combat.

**Comment by KorGgenT** [comment]
couple ideas: priority number that overrides, override for categories of item you can place in the pocket, overrides for item id you can put into the pocket, override for only putting favorited items into the pocket

**Comment by GGgatherer** [comment]
Another idea - including a pocket into 'autosort loot' activity so (you don't have to drop things from it in the ground first).

...actually, come to think of it, how does autosort currently work if you drop a container with different item types in the autosort zone?

**Comment by MarceloLaser** [comment]
Adding to this: it's also important to allow one to choose which pocket to insert items into. If a container has different Base moves to remove item in different pockets, such as the military rucksack, then it is important to be able to place different items in different pockets. I may be okay with putting food in Pocket 1, which takes 300 moves to access, but I want my gun to be in either Pocket 3 or 4, which takes 120 moves to access.

**Comment by 124as** [comment]
For clothing, this would work well with the 'sort armor' menu.

**Comment by hexagonrecursion** [comment]
There should also be a reasonably obvious way to empty the pockets of your jeans before dropping them (e.g because you found better jeans).

**Comment by KorGgenT** [comment]
you mean Unload?

**Comment by dsmky117** [comment]
I don't think it's been specifically mentioned in this thread yet, but I'd like to be able to blacklist items with pockets so that items are never inserted. Or, better yet, use a tailor's kit to modify the clothing to completely remove the pockets.

**Comment by KorGgenT** [comment]
closed via #41061
