### ISSUE TITLE
[Magiclysm] Can't target self with ranged spells.

### ISSUE THREAD

**Issue by BenlyAZ** [CleverRaven/Cataclysm-DDA#40176]
Describe the bug

I can't target myself with Cure Light Wounds or Blessing. Presumably other spells are also affected.

# Steps To Reproduce

1: Make a character, learn Cure Light Wounds
2: Cast it. At level 0 its range is self, and it works properly.
3: Cast it again. Since it leveled up to 1 from the first casting, its range is now 1 and it refuses to target the player.

# Expected behavior

Buff and healing spells should be self-castable.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-1758-g7161a41 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm]
]

**Comment by olanti-p** [comment]
Caused by #39785. I'll make a fix
