### ISSUE TITLE
Trading with NPCs does not update the Volume/Weight indicator for contained items

### ISSUE THREAD

**Issue by Resok** [CleverRaven/Cataclysm-DDA#40175]
# Describe the bug

When trading with an NPC, the volume only updates when trading their currently worn/equipped items. This also includes items that are currently providing their storage capacity.

# Steps To Reproduce

1. Equip NPC and make them friendly (either through normal gameplay or debug commands)
2. Open trade menu with NPC
3. Select trade items from their side (left side)
4. Observe Volume and Weight indicators

# Expected behavior

When I'm attempting to remove an item from an NPC that is contained within their worn containers then the Volume/Weight indicator should update with the new totals. Trading that removes an item with storage should also not preview that it's adding available volume to the NPC.

# Screenshots

![image](https://user-images.githubusercontent.com/5217673/81033806-c6f62b80-8e49-11ea-8670-1c1e591e8d5c.png)

![image](https://user-images.githubusercontent.com/5217673/81033957-54d21680-8e4a-11ea-84dd-c28450da2969.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-1758-g7161a41 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    Stats Through Skills [StatsThroughSkills],
    Mutant Animals [mutant_animals],
    Mutant Insects [mutant_insects],
    Classes and Scenarios Mod [more_classes_scenarios],
    Sleep Deprivation [sleepdeprivation]
]

# Additional context

This seems to be related to the recent containers inventory logic not meshing well with the NPC inventory/trade UI.

**Comment by Nhatorama** [comment]
Followers will agree to wear storage items containing items heavy enough to overburden them.

**Comment by hexagonrecursion** [comment]
* When you mark items inside a leather backpack to be bought that does not free up space even though it should
* When you mark the shoes the NPC is wearing to be bought that magically frees up space even though it should not
* When you mark the backpack to be bought that does not reduce space even though it should

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 8051d7d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]
