### ISSUE TITLE
Can no longer unload or reload canteens/flasks/containers with liquid contents

### ISSUE THREAD

**Issue by Resok** [CleverRaven/Cataclysm-DDA#40179]
# Describe the bug

When attempting to interact with a bottle, canteen, etc. I can no longer unload/reload contents from them. Say I have a canteen in my inventory, or worn - I can no longer fill this with the contents from another bottle.

# Steps To Reproduce

1. Use debug menu to spawn in an empty plastic canteen
2. Use debug menu to spawn in a container of hydrogen peroxide
3. Open player inventory and attempt to unload the contents of the plastic bottle of hydrogen peroxide

Result:

Message 'The liquid can't be unloaded in its current state' is displayed and the UI option for unload/reload/part reload is greyed out.

# Expected behavior

User should be able to unload containers with liquids into other containers of the same liquid or empty containers that can contain liquids.

# Screenshots

![image](https://user-images.githubusercontent.com/5217673/81035340-6d90fb00-8e4f-11ea-83ed-661cca1ad449.png)

![image](https://user-images.githubusercontent.com/5217673/81035378-8e595080-8e4f-11ea-9ad0-be74495285c3.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-1758-g7161a41 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Stats Through Skills [StatsThroughSkills],
    Mutant Animals [mutant_animals],
    Mutant Insects [mutant_insects],
    Classes and Scenarios Mod [more_classes_scenarios],
    Sleep Deprivation [sleepdeprivation]
]

# Additional context

Note that the hydrogen peroxide item is now considered a container only for purposes of sorting and categories. This makes just about any kind of chemical/liquid to be sorted as a container, which is not useful.

Edit -

Looks like some containers work as expected - Gallon jugs appear fine to unload?

**Comment by KorGgenT** [comment]
This is a slightly different bug than advertised - the hydrogen peroxide is frozen, and you can't unload frozen liquids.

**Comment by RoyBerube** [comment]
This has been addressed with PR#44186. Pretty sure it is no longer a problem. Unloading is also working quite well now.
