### ISSUE TITLE
Construction menu: Page up/Page down not working

### ISSUE THREAD

**Issue by RoyBerube** [CleverRaven/Cataclysm-DDA#40178]
# Describe the bug
Page up and page down are non functional in the construction menu.

# Steps To Reproduce
1. Enter construction menu with numpad *
2. Attempt to use the page up or page down buttons.
3. The cursor location does not change.

# Expected behavior

The menu displayed should move up or down by a page length.

# Screenshots

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1607
- Game Version: 0.E-1758-g7161a41 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Cataclysm++ [Cata++],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills]
]

# Additional context

A look at the source code for construction.cpp suggests that this feature was once working as PAGE_UP and PAGE_DOWN are accepted as input.

**Comment by ZhilkinSerg** [comment]
These actions are working and moving through construction stages now. Did you test older versions? Was it working differently there?

**Comment by RoyBerube** [comment]
Ok I did some more checking and my understanding of how the keys functioned was wrong. I now see how it works on multi stage recipes on the right pane and not the left.

Issue closed as far as I'm concerned.
