### ISSUE TITLE
Previously sealed containers with liquid are no longer sealed?

### ISSUE THREAD

**Issue by Resok** [CleverRaven/Cataclysm-DDA#40180]
It appears that all cans containing liquids that were previously sealed and carryable before the recent update are now showing the flag -

![image](https://user-images.githubusercontent.com/5217673/81036361-b185ff00-8e53-11ea-9526-31340761dbc4.png)

# Steps To Reproduce

1. Existing game, after the update.
2. Attempt to pick up any existing container that was holding liquids and considered sealed before the recent update.
3. Note message below:

User is prompted with 'Can't stash aluminum can of beer while it's not empty', with the options of:

Wield aluminum can of beer
Spill contents of aluminum can of beer, then pick up aluminum can of beer

# Expected behavior

Containers that were previously able to be moved and picked up without issue should remain so.

# Screenshots

![image](https://user-images.githubusercontent.com/5217673/81035841-87334200-8e51-11ea-8f91-e9e6d5fe5a46.png)

![image](https://user-images.githubusercontent.com/5217673/81035810-679c1980-8e51-11ea-990e-88cf563db5a3.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-1758-g7161a41 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Stats Through Skills [StatsThroughSkills],
    Mutant Animals [mutant_animals],
    Mutant Insects [mutant_insects],
    Classes and Scenarios Mod [more_classes_scenarios],
    Sleep Deprivation [sleepdeprivation]
]

# Additional context

Appears related to this -

![image](https://user-images.githubusercontent.com/5217673/81036446-00339900-8e54-11ea-8a8e-41b07c6bf5f6.png)

If I debug spawn in a new can of beer, it shows fine -

![image](https://user-images.githubusercontent.com/5217673/81036436-f6119a80-8e53-11ea-8038-e8db4d7ddf95.png)

**Comment by RedShakespeare** [comment]
See #40127.

**Comment by Resok** [comment]
Thanks, didn't see that one.

Closing as it's a dupe.
