### ISSUE TITLE
An option to rearrange martial arts menu and reassign keys

### ISSUE THREAD

**Issue by Nvemri** [CleverRaven/Cataclysm-DDA#40184]
As it stands, the order of your martial arts list and the keys they are associated with is totally dependent on the order you learn them and cannot be changed.
In practice, a player will generally tend to favor 2-3 martial forms that suit his playstyle and switch between them depending on tactical situation.

(As a side note, it is generally good practice to switch between martial arts in melee quite often, because buffs tend to "carry over" for a couple turns and it is possible to get buffs from 2 martial forms for a short while. I am not sure if it is intended, but interesting mechanic.)

Now, because you can't rearrange the martial arts list and reassign keys the switching process can get a bit frustrating.

**Comment by buildfailedforallplatforms** [comment]
Also the option to rearrange cbms? 
I know you can change the hot key but there doesnt seem to be an option to rearrange outright.
