### ISSUE TITLE
Gasoline powered tools cannot be reloaded (You don't have any gasoline to reload your [tool])

### ISSUE THREAD

**Issue by angstr0m** [CleverRaven/Cataclysm-DDA#40188]
# Describe the bug

Tools that use gasoline can no longer be reloaded (for example chainsaws or power cutters) even if a container with enough gasoline is nearby or in the inventory. The user will get the message "You don't have any gasoline to reload your [tool]!".

# Steps To Reproduce

1. Make a player with a chainsaw and a jerry can filled to capacity with gasoline.
2. Try to reload the chainsaw.
3. Observe the message "You don't have any gasoline to reload your chainsaw (off)!".

# Expected behavior

I would expect the chainsaw to be reloaded with the gasoline from the container in the inventory.

# Screenshots

<img width="1440" alt="bug_0" src="https://user-images.githubusercontent.com/733176/81044601-eecea900-8eb4-11ea-9be6-e1ca670d7988.png">
<img width="1440" alt="bug_1" src="https://user-images.githubusercontent.com/733176/81044606-f0986c80-8eb4-11ea-8904-12dc53fda935.png">
<img width="1440" alt="bug_2" src="https://user-images.githubusercontent.com/733176/81044613-f3935d00-8eb4-11ea-91cd-349ac05af024.png">

# Versions and configuration

- OS: MacOs
    - OS Version: Name: Mac OS X; Version: 10.15.4; Build: 19E287; 
- Game Version: 11714a3e86 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by RoyBerube** [comment]
Am getting the exact same bug with a lamp oil cooker. Holding a half full gallon jug of lamp oil does not help.

**Comment by akirashirosawa** [comment]
I have the same bug.
Cannot recharge a gas lamp by recharging (by pressing **"R" key**).
If you fill the lamp manually by pressing **"U" key** on the canister with gasoline and pouring it into the lamp, the **gasoline** (0.5 liter) simply **disappears**, and the **charges** in the lamp are **not increased**.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/cant-reload-oil-lamp/24889/3
