### ISSUE TITLE
Unable to refuel Battery System CBM.

### ISSUE THREAD

**Issue by Monochromatica** [CleverRaven/Cataclysm-DDA#40183]
# Describe the bug

Unable to consume battery charge to fuel Battery System CBM.

# Steps To Reproduce

1. Have the Battery System CBM.
2. Try to consume batteries when low/out of charge with shift+e.
3. Unable to consume batteries in inventory or on the ground.

# Expected behavior

Able to consume batteries to refuel the Battery System CBM.

# Screenshots

![image](https://user-images.githubusercontent.com/64795198/81039415-3bac8280-8ea9-11ea-9301-b13d476284ca.png)
![image](https://user-images.githubusercontent.com/64795198/81039435-4d8e2580-8ea9-11ea-84c4-46a9f072fee5.png)
![image](https://user-images.githubusercontent.com/64795198/81039473-6a2a5d80-8ea9-11ea-807c-fc766e9b780a.png)

# Versions and configuration

  - OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-1778-g781ca2e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    No name () [],
    No name () [],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

    - Please update your OS version with a more precise version.

 - OS: Windows 10 Home 64-bit (10.0, Build 18362)
 - Game Version: 0.E-1778-g781ca2e
 - Graphics version: MSX Undead_People
 - Ingame language: English

# Additional context

This save was updated from the most recent version prior to the nested inventory update, so if the issue stems from me being a silly goose, I apologise. I tried crafting a new battery and seeing if that did anything, but was still unable to consume it after briefly charging it in a recharging station.

**Comment by Fris0uman** [comment]
fxed by #42187 ?

**Comment by anothersimulacrum** [comment]
Probably.
