### ISSUE TITLE
Advanced Inventory displays wrong information

### ISSUE THREAD

**Issue by CMDaddyPig** [CleverRaven/Cataclysm-DDA#40196]
# Describe the bug

When trying to [e]xamine an object in your inventory, from inside the Advanced Inventory screen, you will either get the information for a piece of worn clothing, or nothing.

# Steps To Reproduce

1. Open Advanced Inventory
2. Switch to own inventory
3. [E]xamine an item in your inventory
4. Wonder why you're reading about your scarf, instead of some aspirin or whatever

# Expected behavior

Well, the info for the correct item to be displayed

# Screenshots

![Screenshot at 2020-05-05 16-26-28](https://user-images.githubusercontent.com/17231438/81084022-3f61f880-8eed-11ea-85b5-3ecf2f79007a.png)

![Screenshot at 2020-05-05 16-26-01](https://user-images.githubusercontent.com/17231438/81084073-543e8c00-8eed-11ea-82c6-c7f10398b51f.png)

# Versions and configuration

 - OS: Ubuntu 20.04
 - Game Version: 0.E-1785-g50810da9a3
 - Graphics version: Terminal
 - Ingame language: English
 - Mods loaded: DDA, Disable NPC Needs, Alt Map Key, No Fungal Monsters, No Rail Stations
# Additional context

**Comment by Resok** [comment]
Was just about to report the same problem, in fact when you try to move items with the advanced inventory it transfers the wrong item as well.

I also get an error when moving some objects -

src/visitable.cpp:60 [item* visitable<T>::find_parent(const item&) [with T = Character]] Tried to find item parent using an object that doesn't contain it

**Comment by l29ah** [comment]
Seems to work okay in ff1ff7ea9f

**Comment by anothersimulacrum** [comment]
Possibly fixed by #41353?

**Comment by Night-Pryanik** [comment]
Closing until reconfirmed.
