### ISSUE TITLE
Attempting to consume certain items related to CBMs from containers causes the game to crash.

### ISSUE THREAD

**Issue by Monochromatica** [CleverRaven/Cataclysm-DDA#40192]
# Describe the bug

The game crashes when attempting to consume certain items related to CBMs. So far both a plastic bottle with gasoline and a glass bottle with denatured alcohol has made the game crash for me.

# Steps To Reproduce

1. Have a container with gasoline or ethanol.
2. Attempt to consume the item.

# Expected behavior

Consuming the item doesn't make the game crash.

# Versions and configuration

OS: Windows

OS Version: 10.0 1903
Game Version: 0.E-1778-g781ca2e [64-bit]

Graphics Version: Tiles

Game Language: System language []

Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
C.R.I.T Expansion Mod [crt_expansion],
No name () [],
No name () [],
Fuji's Military Profession Pack [fuji_mpp],
SpeedyDex [speedydex],
Stats Through Kills [stats_through_kills],
Stats Through Skills [StatsThroughSkills]
]

Please update your OS version with a more precise version.
OS: Windows 10 Home 64-bit (10.0, Build 18362)

Game Version: 0.E-1778-g781ca2e

Graphics version: MSX Undead_People

Ingame language: English

# Additional context

Crash: if your problem refers to a crash, please add the following files to the "Additional Context" paragraph:
    - From the /config folder (you can zip them both together):
[Crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4580178/Crash.zip)

[Twin Brooks.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4580196/Twin.Brooks.zip)

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-10939.
