### ISSUE TITLE
UPS in Aftershock doesn't work

### ISSUE THREAD

**Issue by RedShakespeare** [CleverRaven/Cataclysm-DDA#40190]
# Describe the bug

UPS in Aftershock doesn't work at all.

# Steps To Reproduce

1. Create a world with Aftershock mod.
2. Make a player with an UPS and an A7 laser rifle.
3. Try to shoot something.
4. Debugmsg occurs.

# Expected behavior

Tools with "USE_UPS" flag should use energy inside ups.

# Screenshots
![image](https://user-images.githubusercontent.com/44523519/81048775-8b15a180-8eef-11ea-8623-525208e3d86b.png)

# Versions and configuration
Game Version: 0.E-1778-g781ca2e(build 10627, but should have been existing since much earlier)
Mod: dda, Aftershock, Any other mods which don't modify UPS.

# Additional context
UPS in Aftershock is "copy-from" UPS in dda but its type is changed to "TOOL_ARMOR". Guess this is related to the bug.

**Comment by GGgatherer** [comment]
It was most probably caused by new pocket system. Roll back to 10614, AS UPSes work there.

**Comment by Maleclypse** [comment]
UPS works on 
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-5682-g0f8f059 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Cataclysm++ [Cata++],
    Mythical Martial Arts [MMA],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Arcana - UndeadPeople Tileset [ArcanaUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    DinoMod - UndeadPeople Tileset [DinoModUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]
