### ISSUE TITLE
Pudding crash bug report

### ISSUE THREAD

**Issue by piatsa** [CleverRaven/Cataclysm-DDA#40195]
when eating a cup of pudding the game crashes and closes itself 

1. wield a full, open pudding cup
2. ensure the pudding is fresh
3. try to eat the pudding
4. midway through eating the pudding you game should crash

![begrep](https://user-images.githubusercontent.com/49489422/81076830-0e30fa80-8ee4-11ea-9166-923c22580241.PNG)

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-1778-g781ca2e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Stats Through Skills [StatsThroughSkills]

reports:
[crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4581295/crash.zip)

Save game:
[Hanlontown.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4581309/Hanlontown.zip)

**Comment by GOFLUMPYOURSELFPORCAY** [comment]
it doesn't happen for me, could you post the save?

**Comment by piatsa** [comment]
sorry about that I messed up the formatting so half the report could not be seen the save is right at the bottom, hope it helps.

**Comment by anothersimulacrum** [comment]
Eating the pudding in that save did not crash the game.

**Comment by piatsa** [comment]
anything else I can do to help figure it out?

**Comment by piatsa** [comment]
update: i get the same error when I eat ice cream from a tub and yogurt from a pot. It might have something to do with the nested inventory but IDK.

**Comment by ZhilkinSerg** [comment]
It was probably resolved since the issue was introduced - I cannot resolve it on latest version. Please report if you can still reproduce it.
