### ISSUE TITLE
Picking up arrows with worn quiver results in negative count for arrows (and other oddities)

### ISSUE THREAD

**Issue by Resok** [CleverRaven/Cataclysm-DDA#40207]
# Describe the bug

Negative values for arrows are occurring when picking up arrows in to quivers.

# Steps To Reproduce

1. Load attached save
2. Wear large quiver to the north
3. Pickup arrows from ground to the north

Check inventory and note that the quiver is showing negative values for number of arrows.

# Expected behavior

1st - Picking up arrows should prioritize placement into quivers. This matches previous behaviors.
2nd - Item counts should not go negative

# Screenshots

![image](https://user-images.githubusercontent.com/5217673/81111628-39aae980-8ed2-11ea-8eea-e959c5df8397.png)

![image](https://user-images.githubusercontent.com/5217673/81111764-6e1ea580-8ed2-11ea-90a7-01d4f81f2e0a.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-1778-g781ca2e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context

Note also that you cannot 'reload' the quiver like you could before.

Note: My old saves that contain quivers loaded with arrows are not showing proper arrow counts either (some cases it appears they disappeared?).

[Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4583426/Save.zip)

**Comment by AN3223** [comment]
On 0.E-1806-g3140d3fda0
New Game -> Custom Character -> Profession -> Bow Hunter -> Finish Character Creation

Character starts with a quiver containing 4 carbon fiber arrows. Wait one turn and that turns into -8 arrows, wait another and it turns into -44, keep waiting for a little while and the number eventually underflows.

Try dropping the stack and picking up just 10 arrows and receive the error:

`tried to put an item in a container that cannot contain it`

The quiver says it has a volume capacity of 0 and a weight capacity of 0.
