### ISSUE TITLE
Items duplicate if unloaded from dropped container while arms broken

### ISSUE THREAD

**Issue by Lum4r** [CleverRaven/Cataclysm-DDA#40202]
If a container becomes too heavy to wield due to arm injury, dropping it on the ground and unloading it will result in the container's contents being duplicated.

# Steps To Reproduce

1. Drop a loaded container
2. Break or severely injure one or both arms
3. Unload (u) container while it's on the ground
4. Continue unloading container indefinitely

# Expected behavior

Containers shouldn't continue to contain items after the items have been removed.

# Screenshots

![bug report](https://user-images.githubusercontent.com/5982057/81102103-1b96b680-8edd-11ea-89cc-4f147320ecd2.jpg)

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-1783-g3ba1852
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: dda, Disable NPC Needs

**Comment by KorGgenT** [comment]
![image](https://user-images.githubusercontent.com/30208401/82766757-83ab2f00-9def-11ea-8cee-4598c797a926.png)
had a pair of jeans with 800 aspirin and broke both of my arms, then tried to unload it. it unloaded properly.
