### ISSUE TITLE
Vehicle Welding Rig... Not enough charge

### ISSUE THREAD

**Issue by fallout2077** [CleverRaven/Cataclysm-DDA#40203]
When trying to use the Vehicle Welding Rig the game tells me that the tool doesn't have enough charge, despite being installed in a vehicle with 100% charge. I am using the latest experimental build 10628.

**Comment by Resok** [comment]
I'm seeing this also with the Vehicle forge rig.

**Comment by Resok** [comment]
To provide a bit more detail, this was with an old save - I'm no longer able to use the hotplate, welding rig, forge rig, etc. They do not appear to be showing up as valid options for either crafting or vehicle mechanics interactions.

I can attach a save if it would help track things down.

**Comment by DillonSimeone** [comment]
I'm having the same issue too.

Can't use the welder.

![image](https://user-images.githubusercontent.com/21962421/81112976-56482100-8ed4-11ea-9367-80efd7d04578.png)

Unuseable for crafting too.

![image](https://user-images.githubusercontent.com/21962421/81113032-68c25a80-8ed4-11ea-94c8-58cae99b80e2.png)

Batteries have plenty of power in them. 
![image](https://user-images.githubusercontent.com/21962421/81112995-5ea05c00-8ed4-11ea-813e-15a0baaba8c8.png)

You can grab my saves and mods from this different issue to quickly test it. That save still have the welding rig installed instead of the masterforge I made and installed to try to bypass this bug.

https://github.com/CleverRaven/Cataclysm-DDA/issues/40154

**Comment by DillonSimeone** [comment]
It appears that the nested update broke all of this somehow.

Strange thing, hotplates works just fine.

![image](https://user-images.githubusercontent.com/21962421/81113924-d622bb00-8ed5-11ea-826b-68e4578ff4e4.png)

**Comment by Resok** [comment]
You're right, Hotplates are fine. Edited my previous comment.

**Comment by fallout2077** [comment]
> I'm seeing this also with the Vehicle forge rig.

There isn't even an option for me to use the forge rig when examining it.

**Comment by mrkybe** [comment]
Can confirm, ran into the same issue.

**Comment by Resok** [comment]
I did some debugging of this issue today and figured out that the core issue.

Basically inventory::form_from_map() creates a psudo item for the vehicle part it finds and assigns charges to the top level item, but no contents or magazines. Looking at the same kind of item data from a functioning welding rig, it has no charges at the top level - but instead a magazine that contains a charge.

**Comment by fallout2077** [comment]
> I did some debugging of this issue today and figured out that the core issue.
> 
> Basically inventory::form_from_map() creates a psudo item for the vehicle part it finds and assigns charges to the top level item, but no contents or magazines. Looking at the same kind of item data from a functioning welding rig, it has no charges at the top level - but instead a magazine that contains a charge.

Wow, amazing work investigating the issue... I wouldn't have even known where to begin to try and find out what was causing the bug. Thank you for devoting time and effort to this issue!

**Comment by Resok** [comment]
Validated a quick fix for one half of the problem (charge was being set on the root item, and no 'magazine' was being created with charge). Looking into the other half.

**Comment by fallout2077** [comment]
> Validated a quick fix for one half of the problem (charge was being set on the root item, and no 'magazine' was being created with charge). Looking into the other half.

Hopefully your fix gets committed sooner rather than later... it's the only thing stopping me and many other players from playing the darn game.

**Comment by fallout2077** [comment]
I figured I'd state here that, with the fix, I can use the vehicle welding rig as an arc welder in crafting recipes, but I still see the "not enough charges" message whenever I try to use the welder directly from the examine menu.
