### ISSUE TITLE
Dropping keys when streaming/recording

### ISSUE THREAD

**Issue by Pluckyduck** [CleverRaven/Cataclysm-DDA#40211]
# Describe the bug

at the 30 minute mark, the client stops accepting key strokes and will force to use another key strong to unlock.

I am unable to find the starting point, just around 30 minutes seem to only doing it when streaming/recording.  no problems with when not streaming, I have tested with recording and works fine.  Local recording only has not had a problem, only with streaming.  
example would be walking, if I tap the left direction button and it will move that direction and then tap again, it will not do anything.  If I tap the up arrow, it will move as it is supposed to and then part of the time, I can then move back to the left.  This example works the same for all keys.  I was unable to use the up and down arrows to select anything to drop into the ground and it would just move one time a back and forth but unable to move past. 
 Outside of window during this event is the same.  If i type into a chat window or use the keyboard for anything, it blocks it with the same actions as in game.  the last one, i had to fully restart the computer to get the functions back on the keyboard.  Today 5 may 2020, I was able to stop the client and got the keyboard back to full use.  I have tested a second working keyboard and follows on to the working one as well.  I use this keyboard daily and using it right now as well. 

# Steps To Reproduce

so far, i have unable to reproduce... but have video that I am working to show. 

# Expected behavior

To maintain control of keyboard. 

# Screenshots

# Versions and configuration

**Comment by KorGgenT** [comment]
we need reproduction steps, version info, all that jazz.

**Comment by Pluckyduck** [comment]
> we need reproduction steps, version info, all that jazz.

working on the recording now.

**Comment by Pluckyduck** [comment]
So doing a restart before I started the stream/recording has made it run clean for two long runs.  I am going to close this out and update.
