### ISSUE TITLE
[Magiclysm] Casting bless on a friendly NPC will result in hostility

### ISSUE THREAD

**Issue by Resok** [CleverRaven/Cataclysm-DDA#40215]
#Describe the bug

Casting a beneficial spell like bless on a currently friendly NPC will result in them immediately becoming hostile and attacking the player.

# Steps To Reproduce

1. Load attached save
2. Cast bless on the friendly NPC

Observe resulting hostile response.

# Expected behavior

A beneficial spell that buffs a target should not immediately cause the NPC to attack me as if I've betrayed them.

# Screenshots

![image](https://user-images.githubusercontent.com/5217673/81119862-7978cd80-8ee0-11ea-985c-4e7ebd932dfa.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-1778-g781ca2e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm]
]

# Additional context

[Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4583815/Save.zip)

**Comment by anothersimulacrum** [comment]
Caused by #39785

**Comment by KorGgenT** [comment]
oh drat, did that pr cause the bug that makes it impossible to aim at yourself too?

**Comment by olanti-p** [comment]
Yeah, its #39785, sorry. I'll make a fix
