### ISSUE TITLE
Using antiseptic from a bottle in the inventory wastes the leftovers/returns them to the inventory incorrectly

### ISSUE THREAD

**Issue by mrkybe** [CleverRaven/Cataclysm-DDA#40228]
# Describe the bug

If you use antiseptic from a bottle in your inventory, the remaining charges either end up on the ground, or in your inventory, outside of their bottle.

# Steps To Reproduce
1.  Damage limb.
2.  Have bottle of antiseptic in your inventory and `a`pply it to the limb.
3.  Observe puddle of antiseptic on the floor/in your pocket.

![image](https://user-images.githubusercontent.com/1518466/81131368-f758cb00-8f18-11ea-86fc-2ad83a00a89f.png)

**Comment by KorGgenT** [comment]
![image](https://user-images.githubusercontent.com/30208401/82745360-43956f00-9d51-11ea-9d45-d6016d57426d.png)

**Comment by KorGgenT** [comment]
please reopen if the bug still exists
