### ISSUE TITLE
Unable to see outside of vehicle windshield

### ISSUE THREAD

**Issue by JeremyParson** [CleverRaven/Cataclysm-DDA#40229]
#The Bug

After entering a vehicle, driving, exiting, and re-entering, I could no longer see outside the vehicle.
The only information I had was the memory of my surroundings and I could only perceive the 8 tiles that surrounded me.
This occurred while driving a semi-truck, and a military cargo vehicle.

# Steps To Reproduce

1. Have 0.E Ellison installed 
2. Install the following mods in a new world:
- Dark Days Ahead
- Craftable Gun Pack
- Safe Autodoc
- C.R.I.T Expansion Mod
- Cataclysm++
- Alternative Map Key
- Graphical Overmap
- sees-player icon, retrodays
2. Create a new random character
3. Find an operatable vehicle and begin driving
4. Exit the vehicle after a brief period of driving and re-enter it
5. The bug should then occur upon re-entering the vehicle.

# Expected behavior

Once you reach step 5 you should no longer be able to see through the windshield of a vehicle. The only tiles that you can see should be the 8 surrounding tiles and the one below you. All other tiles should be unrevealed or memory tiles. When driving at certain angles a cone of vision will be revealed but this only occurs when driving. When driving into unrevealed territory a trail of memory tiles should appear behind you.

# Screenshots
![Screenshot (36)](https://user-images.githubusercontent.com/30035175/81131874-835ef880-8f01-11ea-9fdf-cf9e9a21367e.png)
![Screenshot (47)](https://user-images.githubusercontent.com/30035175/81131933-ad181f80-8f01-11ea-95f3-8c91b0d24eb0.png)
![Screenshot (48)](https://user-images.githubusercontent.com/30035175/81131917-a5587b00-8f01-11ea-9d1c-2841c345b918.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Craftable Gun Pack [craftgp],
    Safe Autodoc [safeautodoc],
    C.R.I.T Expansion Mod [crt_expansion],
    Cataclysm++ [Cata++],
    Alternative Map Key [alt_map_key],
    Graphical Overmap [Graphical_Overmap],
    sees-player icon, retrodays [sees_player_retro]
]

# Additional context
I am a newer player and have searched extensively for an answer. I apologize if this is expected behavior.

**Comment by anothersimulacrum** [comment]
It looks like you're crouching, press `"` to change move mode.

**Comment by JeremyParson** [comment]
That immediately fixed the problem. I can't believe I didn't notice that, thank you very much.
