### ISSUE TITLE
"Are you sure you want to die?" non-Permadeath option.

### ISSUE THREAD

**Issue by Zombiemanpig** [CleverRaven/Cataclysm-DDA#40238]
# Is your feature request related to a problem? Please describe.
The game is buggy and characters can die due to bugs. An option to disable perma-death would solve bug deaths. Something in the options or enabled by the debug menu.

# Describe the solution you'd like
Someway to disable permadeath. A message that would come up when you die that asks:

Are you sure you want to die?

And hitting Y would be normal death and N would set all your hp back to full and reset your hunger and thirst, stamina, etc. It would be off by default and need to be enabled either through options or on a per-character basis.

# Describe alternatives you've considered
Once you die all you can do is alt-f4 if you die to something such as not being able to stop mining in stable E (not sure if still around)

**Comment by anothersimulacrum** [comment]
This is addressed in the FMS: <https://github.com/CleverRaven/Cataclysm-DDA/wiki/Frequently-Made-Suggestions#rogue-like> - this would fall under an option that facilitates it.

**Comment by Zombiemanpig** [comment]
> This is addressed in the FMS: https://github.com/CleverRaven/Cataclysm-DDA/wiki/Frequently-Made-Suggestions#rogue-like - this would fall under an option that facilitates it.

This has nothing to do with save scumming and has to do with preventing bugs from negatively affecting user experience.

**Comment by KorGgenT** [comment]
Then you need to make a bug report, not ask for invincibility.
