### ISSUE TITLE
Thief mode contained bad value.

### ISSUE THREAD

**Issue by Rakshiba** [CleverRaven/Cataclysm-DDA#40231]
I can disable thief mode for a few seconds but then starts picking people stuff up soon after

# Steps to reproduce the behavior:

I'm using Build #10612. I bound the hotkey to "k" and using it resulted in this. I don't know what else could be contributing to the error.

# Expected behavior

This is my first time using the function.

# Screenshots

![TheifAskError](https://user-images.githubusercontent.com/64879538/81133362-62a59b80-8f1f-11ea-8333-805fc03e5327.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-1448-gdd87a23 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Aftershock [aftershock],
    Anti-fungal tower [aft],
    Blaze Industries [blazeindustries],
    Dark Skies Above [darkskies],
    Mythical Martial Arts [MMA],
    Mining Mod [Mining_Mod],
    More Monsters [mo_monsters],
    More Insects [mo_insects],
    Mutant Insects [mutant_insects],
    DinoMod [DinoMod],
    No Rail Stations [No_Rail_Stations],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    Space Heater [space_heater],
    Bionic Space Expander [Bionic_Space_Expander],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    Dried Fruits [dried_fruits],
    Expanded Archery [ExArch],
    Large capacity storage CBMs [eps_cbm],
    Pure Offal Sausage [offal-sausage],
    You're gonna get canned! [can_mod],
    Shrub it off [shrub_mod],
    Folding Parts pack [deoxymod],
    Jury-Rigged Robots [jury_rigged_robots],
    Compatible Add Bandits [GOV_BANDITS],
    More Armors [More_Armors],
    Bootleg Walkers [Bootleg_Walkers]
]

Sorry to bother if it's an issue of too many mods or some obsoleted mods. I'm still learning.

**Comment by ZhilkinSerg** [comment]
Introduced in #39297.

https://github.com/CleverRaven/Cataclysm-DDA/blob/e1ada1df2bd44d3052093f1621e78c91ba3153cf/src/activity_actor.cpp#L490

Should be `THIEF_ASK` instead.
