### ISSUE TITLE
Range of 2 appears as 3 (Circular distances is off)

### ISSUE THREAD

**Issue by mon-pad** [CleverRaven/Cataclysm-DDA#40243]
# Describe the bug

When using any ranged weapon I am unable to attack a zombie from two diagonal spaces away. This was not an issue in the last build I had (I think it was v10606, but I'm not 100% sure). I have always had circular distances turned off - I'm not familiar with it but I assume if it was on this would be normal behavior. 

# Steps To Reproduce
1. Have circular distances off
2. Get any ranged weapon and try to shoot/attack two diagonal spaces away

# Expected behavior
It should say Range 2/2 instead of Range 3/2 and allow you to attack.

# Screenshots
![Screenshot](https://i.imgur.com/mLYznS1.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.E-1783-g3ba1852 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Monsters [No_Fungi]
]

**Comment by Lamandus** [comment]
Cannot reproduce. This is with nailgun
![grafik](https://user-images.githubusercontent.com/33199510/81144171-cd80c200-8f73-11ea-85fc-291509ca444c.png)
and with a steel spear.
![grafik](https://user-images.githubusercontent.com/33199510/81144245-f43ef880-8f73-11ea-95cd-e0ee65e61684.png)

**Comment by Dacendeth** [comment]
On the latest experimental I can trigger this.

**Comment by Lamandus** [comment]
I feel ashamed. I used my old version.
Yes, I can trigger it on the new one as well. Nvm

**Comment by olanti-p** [comment]
Apparently a function that was there for the sole purpose of selecting between circular/square distances failed to do its single purpose. Derp.
