### ISSUE TITLE
Regular crashes on 0.E-924-gcba

### ISSUE THREAD

**Issue by NobodyWorthwhile** [CleverRaven/Cataclysm-DDA#40241]
# Describe the bug

Rarely on world generation or, much more often waking from CBM installation, there is a high likelihood The game will crash. 
# Steps To Reproduce

1. Begin Installation of Any CBM
2. Receive crash error. Game closes after confirmation

# Expected behavior

1. Begin installation of any CBM
2. Gameplay continues as normal, with player statistics updated with results of operation.

This is just, what's expected to happen.

# Screenshots

None applicable. the crash popup window is inconsiquential, I've been told.

# Versions and configuration

 - OS: Windows 10, much to my chagrin.
 - Game Version: 0.E-924-gcba
 - Graphics version: MSX++UnDeadPeopleEdition
 - Ingame language: English
 - - OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-924-gcba9b9f [32-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Cataclysm++ [Cata++],
    Magiclysm [magiclysm],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    DinoMod [DinoMod],
    Youkai Enemies [Youkai_Disco],
    Alternative Map Key [alt_map_key],
    Crazy Cataclysm [crazy_cataclysm],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Mythical Martial Arts [MMA]
]

# Additional context

relavent files:

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4584905/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4584904/crash.log)
[Crazy Days Ahead.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4584903/Crazy.Days.Ahead.zip)

**Comment by Night-Pryanik** [comment]
That's a rather old version you're playing. Please update and check if crashes still occur.

**Comment by Night-Pryanik** [comment]
No confirmation in almost a year, closing.
