### ISSUE TITLE
Holstering/Storing items that are too large destroys them

### ISSUE THREAD

**Issue by Dendygaar** [CleverRaven/Cataclysm-DDA#40240]
When holstering or storing items in containers (tested fast draw holster/cowboy boots) that are too or go over the containers maximum volume the items will be, seemingly, obliterated. 

Equip cowboy boots or fast draw holster.
Either pick an item that is too large (tested with explosively pumped flux compression generator, and with uberti cattleman revolver. 
attempt to holster the EPFCG in boot, or attempt to holster pistol in fast draw holster that has any stuff in it (used rocks to test partial fill in both cases during my little testing)

# Expected behavior

I expect the EPFCG to be rejected as an item that can go into my boot instead of completely deleted
I expect the revolver holster to not fill with garbage so that using it to holster its gun results in vaporization of said revolver, or destruction of said revolver under any circumstances. Perhaps the inappropriate goods are ejected when the appropriate item is inserted, but this does not happen. 

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-1808-g0da8625 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Craftable Gun Pack [craftgp],
    Magiclysm [magiclysm],
    Whaleys Collectables [collectablemod],
    Gun Cotton [guncotton],
    DinoMod [DinoMod],
    Mythical Martial Arts [MMA],
    Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
    Alternative Map Key [alt_map_key],
    Blaze Industries [blazeindustries]
]

 - Windows 7
 - 0.E 1808-g0da8625
 - Tiles, undead people
 - English

# Additional context

[#QWxleCBLcnVlZ2Vy.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4584865/QWxleCBLcnVlZ2Vy.log)

**Comment by MarceloLaser** [comment]
Simpler way to replicate: Start game as Survivor profession, attempt to insert jeans into plastic bottle.

Secondary issue, probably related: Start game as Survivor profession, attempt to insert socks into plastic bottle. Socks will be successfully inserted, despite not being a liquid.

**Comment by FuelType-Memes** [comment]
> Secondary issue, probably related: Start game as Survivor profession, attempt to insert socks into plastic bottle. Socks will be successfully inserted, despite not being a liquid.

I see no problem with putting socks into a bottle, as they're soft. I see more problems with actually getting them out without a tool
