### ISSUE TITLE
Holstering item in survivor utility belt causes it to loose tool qualites

### ISSUE THREAD

**Issue by Brinabavd** [CleverRaven/Cataclysm-DDA#40251]
# Describe the bug

Holstering item in survivor utility belt causes it to lose tool qualities

# Steps To Reproduce

1. spawn survivor utility belt (with sheath), knife, and steel frame.
2. Sheath knife. Attempt to disassemble steel frame. Nothing happens. "You need a tool with fine metal sawing of 1 or more".
3. Remove knife. Attempt to disassemble steel frame. Behavior as expected.

Same results with holster variant

# Expected behavior

Utility belt should work regardless of whether or not there is a blade in it.

# Screenshots

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-1826-g771188a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Alternative Map Key [alt_map_key],
    Crazy Cataclysm [crazy_cataclysm],
    Mythical Martial Arts [MMA],
    Disable NPC Needs [no_npc_food],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    No Rail Stations [No_Rail_Stations],
    Craftable Gun Pack [craftgp],
    Graphical Overmap [Graphical_Overmap]
]
# Additional context
Same results with holster variant

**Comment by KorGgenT** [comment]
![image](https://user-images.githubusercontent.com/30208401/81221214-87961f00-8fb0-11ea-8127-204ae3a2f3a9.png)
put a dive knife in the survivor utility belt; could not reproduce this bug.

**Comment by Brinabavd** [comment]
Seems to be fixed in the latest version

**Comment by KorGgenT** [comment]
all righty then! if it breaks again you can open a new issue.
