### ISSUE TITLE
Inventory screen swaps from nested back to category format upon reopening

### ISSUE THREAD

**Issue by gisaku33** [CleverRaven/Cataclysm-DDA#40257]
After using the ";" key to change the inventory format from by category to by the container, closing and reopening the inventory causes it to revert back to the category format.

# Steps To Reproduce

1. Download newest experimental version.
2. Create new character, open their inventory, and press ; to change the formatting.
3. Re-open inventory, see the inventory is back to categories, despair.

# Expected behavior

The inventory remaining in the last-set format, which seems intuitive because it was the one last toggled to.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-1821-g3fc82b4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    DinoMod [DinoMod],
    Cataclysm++ [Cata++],
    Mythical Martial Arts [MMA],
    No Fungal Monsters [No_Fungi],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by KorGgenT** [comment]
to boil this down: save the choice you made (somewhere... where?) for layout of the inventory screen

**Comment by drachs** [comment]
I'd also like to mention I didn't even know nested was an option because there's no hotkey hint for it in the bottom bar, just "/" for filter.
