### ISSUE TITLE
Togglable option to prevent Player character death from 0 HP in Head and/or Torso

### ISSUE THREAD

**Issue by Zombiemanpig** [CleverRaven/Cataclysm-DDA#40254]
IT IS NOT IN THE GAME, DEBUG INVINCIBILITY MAKES YOU TAKE NO DAMAGE RUINING THE GAME.

IF I report the mining bug will a fixed Stable E come out with the fix or will I have to wait for stable F? That is useless to me I rather have a solution that solves all future bug issues that comes with F. Closing this with no discussion just shows how big Nazi's you guys are.

My threads keep being closed with lies as the reason. There is nothing like this in game. There is not FAQ related to this. Why are you closing this issue? Why can't you leave it open? What does leaving this issue open do? Maybe someone will implement it.... Oh wait that is what you are trying to block for some reason but are ok with debug invincibility in the game... Just no Debug undying so you can play normally and not worry about bugs...

Is your feature request related to a problem? Please describe.

The game is buggy and characters can die due to bugs. An option to disable dying when your HP hits 0 in the head or torso enabled by debug or option would solve this.

Describe the solution you'd like

A way to prevent character death from Torso or Head hitting 0 hp points. Probably a toggle option.

Describe alternatives you've considered

Once you get stuck in a bug such as not being able to stop mining in stable E, you are pretty much dead and all your progress lost cause of a BUG. You start mining and a rat walks up or a cloud of smoke appears and your character dies and there is nothing you can do about it other than alt-f4'ing out of the program which can cause unexpected behavior. If you could simply have your character not die when their hp hits 0 this problem would be solved, as all the other problems caused by it (other than the hours of wasted ingame time mining) can be fixed through de-bug to prevent user experience from being negative due to bugs in a game full of bugs.

**Comment by GOFLUMPYOURSELFPORCAY** [comment]
stop being an asshole. it's a bug, ok. we get it. save scum then.
