### ISSUE TITLE
Togglable option to prevent Player character death from 0 HP in Head and/or Torso

### ISSUE THREAD

**Issue by Zombiemanpig** [CleverRaven/Cataclysm-DDA#40252]
Is your feature request related to a problem? Please describe.

The game is buggy and characters can die due to bugs. An option to disable dying when your HP hits 0 in the head or torso enabled by debug or option would solve this.

Describe the solution you'd like

A way to prevent character death from Torso or Head hitting 0 hp points. Probably a toggle option.

Describe alternatives you've considered

Once you get stuck in a bug such as not being able to stop mining in stable E, you are pretty much dead and all your progress lost cause of a BUG. You start mining and a rat walks up or a cloud of smoke appears and your character dies and there is nothing you can do about it other than alt-f4'ing out of the program which can cause unexpected behavior. If you could simply have your character not die when their hp hits 0 this problem would be solved, as all the other problems caused by it (other than the hours of wasted ingame time mining) can be fixed through de-bug to prevent user experience from being negative due to bugs in a game full of bugs.

**Comment by KorGgenT** [comment]
yeah that's called debug invincibility, it's already in the game.

**Comment by GOFLUMPYOURSELFPORCAY** [comment]
dude stop being so angry, you posted on reddit today too, if you see you are going to die, just debug it.

**Comment by Zombiemanpig** [comment]
> dude stop being so angry, you posted on reddit today too, if you see you are going to die, just debug it.

You can't debug while mining, you can't do anything, the whole game is frozen till you are done mining, nice stable version.

**Comment by Zombiemanpig** [comment]
> yeah that's called debug invincibility, it's already in the game.

I just looked, does not exist.

![image](https://user-images.githubusercontent.com/47362783/81202169-35df9b80-8f94-11ea-873e-dcbaea7722d5.png)

![image](https://user-images.githubusercontent.com/47362783/81202180-3bd57c80-8f94-11ea-86e9-065a02b3d1ee.png)

Why are you lying just to close my issue?

**Comment by anothersimulacrum** [comment]
Make a bug report for that bug, don't ask for unrelated features.
It's a mutation.

**Comment by kevingranade** [comment]
Just as a FYI, creating copies of closed issues will get you banned from the repo immediately. We don't have time to clean up spam.
