### ISSUE TITLE
Can no longer holster rifle into Survivor Harness

### ISSUE THREAD

**Issue by throttlekitty** [CleverRaven/Cataclysm-DDA#40261]
# Describe the bug

The sling from a Survivor Harness is showing an incorrect list of items 

# Steps To Reproduce

1. Have a Survivor Harness equipped.
2. Have a rifle and army helmet in your inventory. A SIG 552 in my case.
2. Activate the harness.
3. The helmet can be chosen but not the rifle.

# Expected behavior

Same behavior as before; rifle goes on the sling, not armor.

# Screenshots

n/a

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-1826-g771188a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    No Fungal Monsters [No_Fungi],
    Classes and Scenarios Mod [more_classes_scenarios],
    Bionic Slots [cbm_slots],
    Zetsukaze's Hair Extensions! [zets_hair_extensions],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots]
]

# Additional context

**Comment by KorGgenT** [comment]
if it's modded it makes the rifle bigger/heavier, and the survivor harness has a weight limit.

**Comment by throttlekitty** [comment]
My bad! I see that info now and my gun is too heavy.
