### ISSUE TITLE
Prison scenario lockpicking issue.

### ISSUE THREAD

**Issue by KaiserWilhelmIV** [CleverRaven/Cataclysm-DDA#40267]
# Describe The Bug

The Prison starting scenario is impossible, since you can't craft lockpicks to open the bar doors without fine hammering/bolt turning and metal sawing tools anymore.

# Steps To Reproduce

1. Make a character with Prison as the starting scenario.
2. Try to craft lockpicks to pick the bar doors leading outside.
3. Try to break the reinforced glass in the visitor center.
4. There's no way to pick the doors or break through the reinforced glass.

# Expected behavior

There needs to be some way to exit the prison. Starting the prison professions with lockpicks or having them spawn in one of the accessible areas should fix it. Alternatively, adding the tools needed to craft makeshift lockpicks would also solve the issue.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-1828-g7e2c59c
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: DDA, Zetsukaze's Hair - 0.E EDIT, Graphical Overmap, Stats Through Kills, Stats Through Skills.

# Additional context

This happened because of the change to the improvised lockpick recipe having higher tool requirements.

This is the world with the soft-locked save, in case it's useful.
[Teaneck.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4589556/Teaneck.zip)

**Comment by cirops** [comment]
About item 4 in your steps: homewrecker is craftable from inside the prison, and it destroys both jail gates and reinforced glass... it is a mighty pain to get 2400 thread though.

**Comment by Dacendeth** [comment]
god that would take 30 hours taking apart rags for that much thread but I guess if you could find the light to do that that's one way to escape still.

**Comment by KaiserWilhelmIV** [comment]
So the homewrecker does indeed work to get out, even though it does require 30 hours of work. You aren't actually guaranteed to have any objects with the cutting quality spawn in the playable area, but occasionally scissors spawn on prisoner zombies or some of the counters.

That still leaves a pretty large number of saves theoretically locked, though, since it doesn't seem you can make anything with cutting without using rags. It's not literally impossible, but I think it could use some tweaking, since 30 hours of work just to get out of the prison seems excessive.

**Comment by Night-Pryanik** [comment]
Challenge scenarios ain't guaranteed to be winnable at all. There IS a method to get out, so if in one particular run one wasn't able to do this,  it doesn't necessarily mean that scenario requires balancing or other changes to make it easier.

**Comment by cirops** [comment]
I do agree 30 hours is excessive, and I'd definitely do something to address this current issue.
As for the "You aren't actually guaranteed to have any objects with the cutting quality spawn in the playable area" (supposing none of the desired items drop from monsters), you can:
1. get a plank.
2. get pipe and a chunk of steel from lockers and shelves (1 hammering quality).
3. bash down visitor door.
4. craft spike with the chunk of steel.
5. craft makeshift knife from spike and rag (get a rag from the bed upstairs). (1 cutting).
6. craft homewrecker from tedious rag disassembling.

**Comment by KaiserWilhelmIV** [comment]
Yeah, that was my fault, I forgot you could get a rag from the bed.

Prison isn't marked as a challenge scenario, though. Unless all scenarios that give points/aren't Evacuee are supposed to be challenge scenarios.

**Comment by cirops** [comment]
I think at this point this is just a matter of tweaking some sort of variable in this scenario to make it more.. "refined" (fun?). If I were to do something, my preferred solution would be something in the mapgen, e.g:

- Add some sort of hidden way of finding a lockpick in some toilet;
- Add a toolshed/prison work area where you would have to kill a bunch of zombies, in exchange to finding the tools necessary to craft the pick.

Both of course require work, so we'd have to wait for some knowledgeable contributor wanting to implement it.

**Comment by kevingranade** [comment]
> Unless all scenarios that give points/aren't Evacuee are supposed to be challenge scenarios.

You're supposed to figure that out from context. It's staggeringly obvious that starting locked in a prison is a challenge.

As a rule, we do not arbitrarally change scenarios to guarantee they're survivable. One of the main reasons is that frequently when a scenario is reported as being impossible, the reporter is mistaken, and it's entirely too much work to audit reports like this.

If there is a mechanism a player should be able to use to escape, i.e. using a spike to scrape mortar out of a brick wall and removing bricks, or other kinds of improvised demolitions, feel free to make those suggestions, but just giving players resources to defeat the scenario is a non starter.

**Comment by kevingranade** [comment]
Specifically, no to the mapgen suggestion as well, since tuned mapgen is fragile and subject to reversion due 5o unrelated reasons.
