### ISSUE TITLE
Containers within other containers will show the user that they have more free space than actually available

### ISSUE THREAD

**Issue by Resok** [CleverRaven/Cataclysm-DDA#40265]
# Describe the bug

When storing a container in another already worn container, the players free 'storage' listing is increased, but it is not used when picking up new items.

# Steps To Reproduce

1. Load attached save.
2. Examine west space containing a backpack
3. Note inventory volume available - 16.2 L
4. Pickup backpack (will be put into the currently worn backpack)
5. Open inventory (i) again and note the storage increased to 31.2

# Expected behavior

Storage totals should not include containers that are inside other containers.

# Screenshots

Before Pickup -

![image](https://user-images.githubusercontent.com/5217673/81230222-ebffb100-8fa5-11ea-8c0b-389dd92e7d8d.png)

After pickup -

![image](https://user-images.githubusercontent.com/5217673/81230150-cffc0f80-8fa5-11ea-8cde-f3a32a54dd2b.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-1830-g14d8da3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context

[Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4589549/Save.zip)

This also results in errors when attempting to pickup what the UI shows as valid, but it gives you an error when attempting to fill that space that is only provided by containers inside other containers (not worn containers).

**Comment by Resok** [comment]
When attempting to pick up items in the above scenario when over your 'real' capacity -

![image](https://user-images.githubusercontent.com/5217673/81231021-5cf39880-8fa7-11ea-9e5d-ca04bc27e31b.png)

You get for example - not enough capacity to stash X

![image](https://user-images.githubusercontent.com/5217673/81231058-6a108780-8fa7-11ea-8838-8b00f2b7b289.png)

**Comment by jbytheway** [comment]
Just want to point out that if you have a rigid container in your backpack then you should be able to put stuff in it.  I'm not quite sure how that would presently be handled.

**Comment by aerrant** [comment]
This issue is no longer valid: nested containers don't count towards overall volume anymore.

**Comment by wapcaplet** [comment]
No longer reproducible in 0.E-9603-g42468f6cab. Total volume is determined by the containers being worn; having additional containers inside those containers does not add to total volume.
