### ISSUE TITLE
[BUG] Eating or drinking from a container crashes the game

### ISSUE THREAD

**Issue by AGasCanister** [CleverRaven/Cataclysm-DDA#40268]
# Describe the bug
The game will crash when your character tries to drink or eat from something that's in a container

# Steps To Reproduce

1. Have a character that has food or a drink in a container
2. Try to eat or drink it
3.  Game crashes

# Expected behavior
Expected behavior is that the game shouldn't crash when my character eats or drinks like it used to happen before this new inventory upgrade

# Screenshots
![image](https://user-images.githubusercontent.com/55928412/81229020-70c2ed00-8fef-11ea-847c-7234d3b6c077.png)

![image](https://user-images.githubusercontent.com/55928412/81229040-79b3be80-8fef-11ea-9130-c8edcf323f48.png)
If you try to eat either the can with the chicken or directly the chicken, it will still crash.
If you try to directly drink from the bottle instead of directly drinking the liquid, the game will also crash

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-1830-g14d8da3 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

[Crash Debug and Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4589572/Crash.Debug.and.Save.zip)

**Comment by AGasCanister** [comment]
Just found out that trying to Eat (E) the canned chicken will crash the game, but if I activate it, it won't crash the game

**Comment by KorGgenT** [comment]
are you trying to Eat it through the consume menu, or through the item directly?

**Comment by AGasCanister** [comment]
Item directly, didn't knew there was an item menu, so via inventory

**Comment by DillonSimeone** [comment]
Hmm, this bug seems to still be in play. The game just crashed when I tried to eat something.

![image](https://user-images.githubusercontent.com/21962421/81640804-5d8b9500-93d4-11ea-9da9-d7f249ad1a27.png)

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4613517/crash.log)

The crash occurred when I took some dry meat into my inventory, then carried it over to my table in the middle of my mobile fort and press `E`.

**Comment by DillonSimeone** [comment]
![image](https://user-images.githubusercontent.com/21962421/81661825-879f8000-93f1-11ea-93e5-f17bed47f74b.png)


Argh... This just happened. I thought I was safe by eating outside!

**Comment by DillonSimeone** [comment]
!!

It appears that this killed my savefile. This is what shows up for me now when I try to load up my save.

![image](https://user-images.githubusercontent.com/21962421/81662152-02689b00-93f2-11ea-8dd4-cb652f062ee9.png)

[Palmer Heights.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4614353/Palmer.Heights.zip)

[mods](https://github.com/CleverRaven/Cataclysm-DDA/files/4613545/mods.zip)

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4614362/crash.log)

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4614365/debug.log)

**Comment by AGasCanister** [comment]
oof, big F. Not sure if devs are gonna notice about this, might as well do a new issue or ping them directly just in case. Rip your save
![image](https://user-images.githubusercontent.com/55928412/81706635-6df14d80-9470-11ea-86b1-9d9edc4674a4.png)

**Comment by kevingranade** [comment]
No meming in issues please.

**Comment by DillonSimeone** [comment]
I just triggered this again.

![image](https://user-images.githubusercontent.com/21962421/81757646-6cc21f80-9474-11ea-9b2e-9dd4fe830d4b.png)

I suspect that the blood CBM I filled with tainted blood a few minutes before this occured have something to do with the crash. 

Oddly, it didn't destroy my save this time. Woke up to the last time the autosave kicked in, before I filled my blood CBM with tainted blood. Will press on without putting blood into that CBM to see if this occurs again.

![image](https://user-images.githubusercontent.com/21962421/81757727-adba3400-9474-11ea-8ab1-c595332cffb0.png)

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4619095/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4619097/debug.log)

**Comment by DillonSimeone** [comment]
Maybe it's me making x10 clean water and drinking everything in one go then eating something is triggering this... The game seems weird about drinking that much water so quickly. Before nested, drinking that much at once was painless. 

While drinking more than 1 water at a time, I go from `Very hungry` to `Engorged`... Flipping back and forth as I drink more water.

**Comment by DillonSimeone** [comment]
The issues I had here for the most part may not be related to containers! See #40505.

**Comment by Ramza13** [comment]
> The issues I had here for the most part may not be related to containers! See #40505.

I looked at the crash logs and I think these are related to containers as opposed to the consume changes.  

The lines around the crash are: error: tried to put an item into a pocket that can't fit into it while loading.

**Comment by KorGgenT** [comment]
I cannot reproduce this. i spawned in a 30 gallon barrel, filled it up with water, and tried to drink from it in both the consume menu and by the item itself. the barrel was wielded.
