### ISSUE TITLE
Advanced Inventory: Move all to player freezes game.

### ISSUE THREAD

**Issue by throttlekitty** [CleverRaven/Cataclysm-DDA#40262]
# Describe the bug

My game is freezing when moving all from the world to player inventory. The game never crashes, but never recovers so I don't get a crashlog. I do see constant CPU activity from the cdda process that ends when I finally kill it. Doesn't seem to be related to type of item, nor number or weight. Moving all from world to world works as expected.

May be related to:
https://github.com/CleverRaven/Cataclysm-DDA/issues/40196

# Steps To Reproduce

1. In advanced Inventory, set one pane to player inventory, and the other to anywhere in the world containing an item.
2. Press , (comma) to move all.
3. Game Freezes.

# Expected behavior

No freeze and items are transferred.

# Screenshots
n/a

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-1826-g771188a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    No Fungal Monsters [No_Fungi],
    Classes and Scenarios Mod [more_classes_scenarios],
    Bionic Slots [cbm_slots],
    Zetsukaze's Hair Extensions! [zets_hair_extensions],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots]
]

# Additional context

**Comment by throttlekitty** [comment]
Sorry for the delay in getting back to this. I no longer have this freeze, but I'm on a new OS with a fresh cdda install on a new save with a minimal set of mods.

**Comment by Night-Pryanik** [comment]
Closing until reconfirmed.
