### ISSUE TITLE
Oxyacetylene cannot be crafted

### ISSUE THREAD

**Issue by SSpook** [CleverRaven/Cataclysm-DDA#40275]
# Describe the bug

Oxyacetylene recipe uses oxygen as a material, however oxygen tanks, cylinders and emergency oxygen packs have charges and do not contain oxygen. 

# Steps To Reproduce

1. Find a recipe for oxyacetylene.
2. Find an oxygen tank, oxygen cylinder or an emergency oxygen pack.
3. Check oxyacetylene recipe, notice how oxygen is not available.

# Expected behavior

Expected to be able to craft oxyacetylene.

# Versions and configuration

 - Game Version: 0.E

# Additional context
Changing the recipe to use charges from tanks seems to work. A working recipe is included in the attachment. 
[weldgas.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4589907/weldgas.zip)

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/oxyacetylene-crafting-cant-use-regular-oxygen-tanks-and-emergency-packs/21467/6

**Comment by zantanzuken** [comment]
popping in here to suggest something, currently oxyacetylene cannot be crafted simply due to how oxygen tanks work (charges instead of gas), but also due to the compression process of both oxygen and acetylene gas (you can craft acetylene into a tank, but theres no way to find an 'acetylene compressor' currently)

suggest that we create a new 'welding gas' recipe which uses other materials? i've been reading up on it and welding torches will also work with mixtures of gasoline as well as propane (though likely not as effectively as oxyacetylene)

**Comment by int-ua** [comment]
Confirmed on latest experimental. Please add the list of books that contain the recipe.

**Comment by zantanzuken** [comment]
all of the related info's under data\json\recipes\ammo\weldgas.json

oxyacetylene and acetylene uses [ "textbook_chemistry", 4 ], [ "textbook_gaswarfare", 4 ], [ "atomic_survival", 3 ] for recipe guides.

oxygen cant be crafted, but is found in 'emergency oxygen pack', 'oxygen cylinder' and 'oxygen tank', where it is in charge form (not actually containing oxygen gas, so cannot be transfered/used in the recipe for oxyacetylene, though changing the recipe slightly fixes that, as shown above.)

**Comment by int-ua** [comment]
Yes, I know. I want to help anyone else trying to confirm it, please add the book IDs to the main description by editing it so that everyone else will not spend time searching for the recipe.

**Comment by int-ua** [comment]
@SSpook Please change title to something like "It's impossible to craft oxyacetylene"

Edited previous comment.

**Comment by zantanzuken** [comment]
i mean i -would-

**Comment by int-ua** [comment]
Oh, I glossed over that, thanks, I'll make a PR.
