### ISSUE TITLE
(E)at menu closes after consuming one item

### ISSUE THREAD

**Issue by mopb3** [CleverRaven/Cataclysm-DDA#40273]
# Describe the bug

(E)at menu closes after consuming a single item

# Steps To Reproduce

Open (E)at menu and consume an item, menu will close

# Expected behaviour

Menu to stay open to allow for rapid consumption of many items

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-1830-g14d8da3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

Tested with many consumables, seems to consistently occur.

**Comment by Ichthysdekilt** [comment]
The menu now (10677) reopens but only closes again when re-selecting something to consumE.

**Comment by hexagonrecursion** [comment]
Can not reproduce. Was this fixed?

**Comment by Night-Pryanik** [comment]
Closing until reconfirmed.

**Comment by Ramza13** [comment]
This was fixed by #41316
