### ISSUE TITLE
Automining: Doesn't stop mining when answering YES at the prompt to do so.

### ISSUE THREAD

**Issue by Malkeus** [CleverRaven/Cataclysm-DDA#40289]
When automining, you are unable to stop mining a wall after trying to move into it. If you answer YES, the percentage is reset to 0 and it continues mining. I suspect a larger issue since I was told one is unable to stop ANY auto-action once its started.

# Steps To Reproduce
Toggle on autoactions and ensure automining is enabled. Wield a pickaxe and move into any wall to begin mining. Try to stop using any method, either voluntary via keypress or involuntary due to damage. Answer YES at the prompt to stop. The mining percentage will reset to zero and mining will begin anew.

# Expected behavior

For it to stop and wait for further input from the user.

# Versions and configuration

GAME REPORT:
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-1251-gcaf81ee [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [ none ]

Tested and confirmed on 0.E Stable release as well.

# Additional context

https://i.imgur.com/fZWWyfm.png

**Comment by ZhilkinSerg** [comment]
Automining activity is in backlog after, so it is resumed through `resume_backlog_activity` after queried to cancel activity:

![image](https://user-images.githubusercontent.com/16213433/81305385-f04fcb00-9086-11ea-96ec-ffdc484151e3.png)
