### ISSUE TITLE
Container unload on floor can hang

### ISSUE THREAD

**Issue by Adomatic** [CleverRaven/Cataclysm-DDA#40281]
# Describe the bug

A container that is on the floor cannot successfully be unloaded using the <U>nload command. If you try (on my Mac) it spinny-cursor-of-deaths. I am not sure what (if any) other aggravating factors there are, but it appears that if there are no containers in your inventory or worn on your person at all, and the item is one you can carry, then the crash does not occur.

Note that I wouldn't expect "U"nloaded items to even be put into inventory at all from a container that's on the floor. I'd expect them to be dumped on the floor. Unless there is some other command that does that.

# Steps To Reproduce

1. Add at least one very small, very light item to a container.
2. Drop the container.
3. "U"
4. Choose the container.

(To reproduce the non-crash, do the same thing as above, but at 2.5 you get rid of all of the containers of any kind on your person, including clothing.)
# Expected behavior

The items in the container land on the floor next to the container. (In your inventory would be okay but not what I would expect. If I say 'unload' on an item on the floor, to me that's the equivalent of 'dump the contents of this box onto the floor'.)

# Versions and configuration

- OS: MacOs
    - OS Version: Name: Mac OS X; Version: 10.15.4; Build: 19E287; 
- Game Version: 14d8da3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    No Fungal Monsters [No_Fungi],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context
[World_presumably_with_saves.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4590219/World_presumably_with_saves.zip)

[Process_sample_cataclysm.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/4590221/Process_sample_cataclysm.txt)

**Comment by RoyBerube** [comment]
Here is how unload currently works:
It first transfers the item to the player inventory and then unloads it. If it finds there is no space then it dumps some random object on the ground to make space.

It looks like not having any random object to drop in order to make space is where it crashes.

What I'd prefer is to unload in place and then only transfer the unloaded object to inventory if there is space. It is annoying to unload a radio on the ground and end up having both the radio and battery in inventory.

**Comment by KorGgenT** [comment]
![image](https://user-images.githubusercontent.com/30208401/85066944-db824f00-b17d-11ea-8ccf-b446f5873395.png)
put a marker in a tuxedo and unloaded it just fine naked.
