### ISSUE TITLE
Dropping magazines from multidrop menu (sometimes) causes crash.

### ISSUE THREAD

**Issue by Sumguy62** [CleverRaven/Cataclysm-DDA#40293]
# Describe the bug

Dropping magazines from the multidrop menu causes a crash, most often when I have a whole bunch of them in my inventory. I'm not really sure what pockets the magazines are in when I was dropping them, though. Also, nested containers don't show up in either the inventory or multidrop menu most of the time. I'm unaware of what does even allow them to show up in the first place. It could be that only the ones in the rucksack show up. I seem to have a lot of stuff go straight into my army jacket or pants, and many more mags in the tac vest than expected.

# Steps To Reproduce

1. Drop a bunch of mags from the multidrop menu
2. crash

# Expected behavior

Not crashing. 
All plastic bags and other containers showing up in the inventory and multidrop menus.
Tac vest only holding 4 or so magazines, maybe 8 stanag tops.

# Versions and configuration

- OS: MacOs
    - OS Version: Name: Mac OS X; Version: 10.14.6; Build: 18G95; 
- Game Version: 0.E-1830-g14d8da3 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi],
    Disable NPC Needs [no_npc_food],
    Fuji's Military Profession Pack [fuji_mpp],
    Stats Through Kills [stats_through_kills],
    Blaze Industries [blazeindustries]

# Additional context
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4593881/crash.log)
[Fort Douglas.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4593885/Fort.Douglas.zip)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4593895/debug.log)

**Comment by KorGgenT** [comment]
tried to reproduce today, got a different bug but not one from dropping all of the mags. could you try to confirm this for me?

**Comment by wapcaplet** [comment]
I could not reproduce this in 0.E-9737-g511ddcb179, with more than 50 magazines stored in a tac vest, army jacket, army pants, backpack, and high-volume rucksack. I picked up and dropped various magazines (and all magazines) several times and had no errors or other problems.
