### ISSUE TITLE
Auto-drink sometimes prefers alcohol and bleach over clean water; bleach shouldn't be comestible

### ISSUE THREAD

**Issue by kaeroku** [CleverRaven/Cataclysm-DDA#40290]
Game version: 0.E-1272-g3bdcb87

Operating system: Win 7 Home 64-bit

Tiles or curses: ChestHole16

Mods active: Disable NPC Needs, Stats Through Skills, No Fungal Creatures, 

### Expected behavior

Auto-drink won't drink bleach and won't choose non-clean-water beverages over clean water.

### Actual behavior

Auto-drink will include bleach as an option if it is in range of auto-drink zones and will sometimes choose non-clean-water beverages over clean water.

### Steps to reproduce the behavior

Launch game. Set auto-drink zone. Include clean water and other alcoholic and bleach items. Engage in a long activity like crafting that auto drinks. Repeat with various stacks of liquids and clean water.

**Comment by DillonSimeone** [comment]
![image](https://user-images.githubusercontent.com/21962421/81264064-a8349800-8ff5-11ea-9679-415435b3a12c.png)

This is what happened to the poster. Autodrink forced him to drink himself to death!

**Comment by ZhilkinSerg** [comment]
Related to #14855
Related to #14851

**Comment by MadmanMartian** [comment]
From looking into this, I'm not sure it was autodrink that caused this to happen, but autoeat.

Autodrink checks for quenching to be greater than 15 points, which fancy hobo only gives 4 points.
However, Autoeat checks if kcal gained from eating is greater than 50, which fancy hobo gives 52 kcal.
