### ISSUE TITLE
Kitchen unit in vehicle not considered "hot plate" while crafting

### ISSUE THREAD

**Issue by Psiclops** [CleverRaven/Cataclysm-DDA#40307]
cooking recipes which require "hot plate" or other fire based cooking do not recognize the vehicle kitchen unit as valid and will not craft.

When (e)xamining the kitchen unit, "use hot plate" functionality works, but only heats items. Crafting food items that require the hot plate will show "hot plate (2 charges)" in red text and is not available to craft. Vehicle has power, standing right next to kitchen unit.

# Expected behavior

These recipes should be able to craft using the kitchen unit hot plate.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-1864-gb8fb092 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

**Comment by mrkybe** [comment]
I think this is the same issues as here:

https://github.com/CleverRaven/Cataclysm-DDA/issues/40203
