### ISSUE TITLE
Coal can be "Cut up" into wood

### ISSUE THREAD

**Issue by Salty-Panda** [CleverRaven/Cataclysm-DDA#40306]
# Describe the bug

I looked at a pile of junk, clicked [B] and saw the option to disassemble coal.
_Hmm, curious_
...got splintered wood as a result. I could argue that it could be sort of possible for charcoal, but coal?
No way.

I debugged more coal and it can't be disassembled if it's the only item in pile. The option is available only when there is a variety of items on the ground.
There were a few thousands of pieces of coal. The prompt said _Cut up coal (1)_, but all coal was lost and I got 670 pieces of Splintered wood (10 coal to one splintered wood)

# Steps To Reproduce

Get some coal and random other items, at least one thing must be possible to cut up/disassemble, drop on the ground. Open butchering window, disassemble coal.

# Expected behavior

Coal can't be turned into wood unless some new mod with advanced alchemy is introduced.

# Screenshots

![image](https://user-images.githubusercontent.com/26396019/81337234-01123800-90ab-11ea-9a17-797615f0135e.png)
![image](https://user-images.githubusercontent.com/26396019/81337310-18e9bc00-90ab-11ea-9ad9-ec052a2f3c61.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-1231-g4968f19 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    No Fungal Monsters [No_Fungi],
    Magiclysm [magiclysm],
    Aftershock [aftershock],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Mining Mod [Mining_Mod],
    No Rail Stations [No_Rail_Stations],
    Graphical Overmap [Graphical_Overmap]
]

**Comment by nexusmrsep** [comment]
Probable culprit: made of wood. Coal (and perhaps charcoal too) should have carbon as a (new) material type.

**Comment by aerrant** [comment]
This issue is no longer valid: `coal` and `charcoal` have got materials of their own, and disassembly of `unfinished charcoal` yields wood splinters as expected.
