### ISSUE TITLE
(0.E): when wearing CRIT arm and leg guards and wielding non-block weapon, I block everything with my leg guards

### ISSUE THREAD

**Issue by Adomatic** [CleverRaven/Cataclysm-DDA#40318]
# Describe the bug
This is in 0.E release version, since 0.E+ seems to be pretty much unplayable right now, so it could easily have already been fixed.

My character is wearing a CRIT outfit (due to the lucky discovery of a dead relative of his). This includes arm and leg guards.

All of his blocks seem to be done with his legs. In particular, this just seems wrong:

- You batter the zombie security guard for 25 damage. Critical!
- You block some of the damage with your \. pair of CRIT leg guards!
- The zombie security guard hits your right arm, but your armor protects you.

My leg guards are nearly destroyed (as you can see) but my arm guards are pristine. And if I do a search in my message log, every single block that I see is with my leg guards, none with my arm guards, even when the attack is against my head.

Fighting style is brawling, weapon is CRIT hatchet.

Possibly you can't block with your arms if you are wielding a non-blocking weapon? Although that seems ridiculous.

# Steps To Reproduce

Honestly here I don't know. Is this just with CRIT equipment? Is it any time you're wearing blockable arm-and-leg armor but wielding a non-blockable weapon? Is it something else? Not sure.

# Expected behavior

Mostly arm blocks. Occasional leg blocks. Probably occasional foot blocks (crescent kicks aren't that hard to learn even if you don't know karate). Certainly occasional hand blocks if you're wearing decent hand armor.

# Screenshots

Demolished leg armor, no blocks otherwise.

# Versions and configuration

- OS: MacOs
    - OS Version: Name: Mac OS X; Version: 10.15.4; Build: 19E287; 
- Game Version: 0.E [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    No Fungal Monsters [No_Fungi],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]
# Additional context

**Comment by Soupster89** [comment]
Let me check my stuff, this sounds quite odd.

**Comment by Night-Pryanik** [comment]
CRIT mod is obsoleted and no longer supported.
