### ISSUE TITLE
Tools that are containers can disappear when stacking wrong

### ISSUE THREAD

**Issue by Psiclops** [CleverRaven/Cataclysm-DDA#40312]
Teapot filled with clean water pick up using advanced inventory management (/)
look at inventory, teapot with clean water shows up under tools.
Teapot emtpy picked up using (/)
both are gone.
OR
Craft clean water, fill a nearby teapot
using (/) see that it is in the nearby tile called teapot of clean water
in inventory is a teapot, not filled with water
using (g), pick up the teapot of clean water
in inventory, now there are two items called teapot, no teapot of clean water
Use (E)at to consume the clean water (1) and both teapots are gone.

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-1864-gb8fb092 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by MamuelMamington** [comment]
Same happened with ammo magazines in my experience.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-10962.
