### ISSUE TITLE
Items not shown in inventory

### ISSUE THREAD

**Issue by enaantd** [CleverRaven/Cataclysm-DDA#40311]
# Describe the bug

Items are not shown in the inventory even though they are visible in the bag they are in.

# Steps To Reproduce

I'm not sure how to reproduce this.

# Expected behavior

Items are shown in the inventory

# Screenshots

2 first aid kits in a sling pack:

![Screenshot_2020-05-07_23-31-20](https://user-images.githubusercontent.com/64151602/81346805-39ba0d80-90bb-11ea-8cc5-a42f9db47081.png)

they are not shown in the inventory:

![Screenshot_2020-05-07_23-31-29](https://user-images.githubusercontent.com/64151602/81346807-3b83d100-90bb-11ea-8487-ecd7fd496b62.png)

I can't find them even if I search for them:

![Screenshot_2020-05-07_23-31-37](https://user-images.githubusercontent.com/64151602/81346811-3d4d9480-90bb-11ea-9732-4c19d0638658.png)

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.E-1879-gd354a17e12 [64-bit] (this is my config commit, actual commit is 0466c67b3a9ee10254c824a4a2b54a7799aa0c02)
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

none

EDIT: added a save file with the same problem. In this save file, 2 cash cards are replaced in the inventory with stacks of antibiotics
[Lantana.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/4605948/Lantana.tar.gz)

**Comment by KorGgenT** [comment]
I can see all of the items in the screenshot.

**Comment by KorGgenT** [comment]
Gave it another look and it's actually the stacking bug that was fixed a couple days ago.
