### ISSUE TITLE
Objects stack with unrelated objects

### ISSUE THREAD

**Issue by BenlyAZ** [CleverRaven/Cataclysm-DDA#40319]
# Describe the bug

Sometimes, objects will stack with an unrelated object, creating what appears to be a larger stack of the second object until the stack is forcibly broken up.

# Steps To Reproduce

I do not know how to consistently and specifically cause this to happen. It is happening frequently in my current save.

# Expected behavior

Objects should be what they are.

# Screenshots
In the first shot, there appears to be a stack of three Ham Radio magazines in my inventory.
![Screenshot (73)](https://user-images.githubusercontent.com/51046470/81359162-60217e00-90a6-11ea-93be-d7efa90c2813.png)

I try to drop one of them.
![Screenshot (74)](https://user-images.githubusercontent.com/51046470/81359175-6879b900-90a6-11ea-9556-688fef9d68e5.png)

Two of them were actually switchblades, one of which has dropped along with the one real magazine.
![Screenshot (75)](https://user-images.githubusercontent.com/51046470/81359186-6fa0c700-90a6-11ea-8471-2629ad13cfbf.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-1864-gb8fb092 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Garden Pots [growable-pots],
    Makeshift Items Mod [makeshift],
    DinoMod [DinoMod],
    EZ-Mode Medical [fast_healing],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    Tanks and Other Vehicles [Tanks],
    Classes and Scenarios Mod [more_classes_scenarios],
    Prevent Zombie Revivication [no_reviving_zombies],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Simplified Nutrition [novitamins],
    No Fungal Monsters [No_Fungi],
    No Rail Stations [No_Rail_Stations],
    Gun Cotton [guncotton],
    No Explosive Zombies [No_Explosive_Zombies],
    Necromancy [necromancy],
    Fuji's Military Profession Pack [fuji_mpp],
    Arcana and Magic Items [Arcana],
    Blaze Industries [blazeindustries],
    Mining Mod [Mining_Mod],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    MST Extra [MST_Extra]
]

**Comment by KorGgenT** [comment]
[Vanilla.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4606917/Vanilla.zip)
here's a save with this behavior
