### ISSUE TITLE
Activated items disappear from inventory

### ISSUE THREAD

**Issue by Drew4484** [CleverRaven/Cataclysm-DDA#40317]
# Describe the bug

Activating stack of bandages in inventory, first bandage is used properly (selected limb bandaged properly). Remaining stack disappears from inventory. Not dropped to ground.

# Steps To Reproduce

1. Debug bandages into inventory (tested with stack of 15).
2. Use bandage on injured limb.
3. Check inventory for remaining bandages.

# Expected behavior

Unused bandages should remain in inventory.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-1864-gb8fb092 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]

[Glenham.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4596413/Glenham.zip)

**Comment by KorGgenT** [comment]
![image](https://user-images.githubusercontent.com/30208401/82745677-164ac000-9d55-11ea-9100-70226acfcc48.png)
used two bandages: one from the `a`ctivate menu, one from clicking on the item and pressing `a`ctivate. cannot reproduce. please reopen if the reproduction steps were not correct.
