### ISSUE TITLE
Pickaxe stamina and fatigue

### ISSUE THREAD

**Issue by TheDarkMaster13** [CleverRaven/Cataclysm-DDA#40331]
# Describe the bug

When using a pickaxe to break up rocks, the player does not become tired faster than normal or lose any stamina.  The player may spend an entire day breaking rocks and not become fatigued earlier than they would have if they'd spend that day sitting around.

# Steps To Reproduce

1. Make a player with a pickaxe.
2. Find some rocks on the map.
3. Spend the day using the pickaxe on those rocks.

# Expected behavior

Using a pickaxe should cost the player stamina down to a certain level, like most other forms of manual labor in the game such as chopping trees.  This should also cause the player to become tired more quickly and need sleep.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Generic Guns [generic_guns],
    No Fungal Monsters [No_Fungi]
]

**Comment by wapcaplet** [comment]
Testing in 0.E-2382-g48f8edf705, I used the debug menu to view `p`layer `n`eeds, and see how the "fatigue" number changed over time. I compared just sitting around (passing time with `|`) with pickaxing through concrete:

- 2 hours waiting: +24 fatigue
- 2 hours pickaxing: +88 fatigue
- 2 hours waiting: +24 fatigue

I didn't test over the course of multiple days of game time to see whether a day full of pickaxing would make me tired sooner than a day of resting; it seems hard to check that without a lot of other factors being involved. But at least it seems to be adding fatigue as expected.
