### ISSUE TITLE
Gallon Jug Woes

### ISSUE THREAD

**Issue by drachs** [CleverRaven/Cataclysm-DDA#40339]
I'm having lots of problems with gallon jugs.  It seems to be related to having multiple jugs in my inventory.   I've had the jugs disappear and only the liquid inside them show up in my inventory.  I've had the jugs stack merge inappropriately many times, so that a full jug merges with an empty jug and now I have 2 empty jugs.  I've also had jugs just disappear.   For example, I put 3 empty jugs into a trunk with 1 full jug.   Then I had 2 full jugs in the trunk.  I took them out and I had 2 empty jugs on the ground.

# Steps To Reproduce
Make a character

1. Spawn 4 empty jugs
2. Spawn a large tactical backpack
3. Wear the backpack
4. Put all your jugs in your backpack.  I had 1 stack of 1 jug (From wielding) and 1 stack of 3 jugs from picking up off the ground.
5. Start filling jugs with water from a puddle and notice jugs start disappearing and water starts showing up as inside random items in your inventory when switched to nested mode.
6. After filling 2 jugs I had 1 jug of water (frozen).   1 empty jug.  And "inside" my hardtack I had vinegar (16), water (15) and water(15).   All the water was frozen.

# Expected behavior
Would like to be able to fill and empty multiple jugs without jugs or contents dissapearing.

# Screenshots
This screenshot was taken after filling two jugs with water twice from a pond as above.  I expect 2 full jugs and 2 empty jugs, instead I get 4 jugs worth of water inside my hardtack, 1 jug of water and 1 empty jug.

![image](https://user-images.githubusercontent.com/450381/81369446-4e8ca600-90a7-11ea-8772-29841d94ca72.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-1864-gb8fb092 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Stats Through Kills [stats_through_kills]
]

**Comment by KorGgenT** [comment]
this is already fixed
