### ISSUE TITLE
Cheese spread makes stuff disappear

### ISSUE THREAD

**Issue by JerryTheCool** [CleverRaven/Cataclysm-DDA#40343]
# Describe the bug

if you try to insert a small tin of cheese spread into anything and it will disappear. I have tried lots of different items and even inserting the item into things that you cant store stuff in, it will make the item disappear. I do not know if this has to do with the small tin of cheese spread itself, or if this affects all other small tin items.

# Steps To Reproduce

1. create a character (duh)
2.  spawn in a backpack and a small tin of cheese spread. (or you can spawn in literally any other storage or even non storage item.)
3. try to insert the cheese spread into the backpack/item.

# Expected behavior

id expect the cheese spread to go into the backpack/ other storage medium.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-1864-gb8fb092 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    Graphical Overmap [Graphical_Overmap],
    Fuji's Military Profession Pack [fuji_mpp]
]

**Comment by KorGgenT** [comment]
This should have been fixed with the multi-insert function.
