### ISSUE TITLE
Using "^" key does not work properly

### ISSUE THREAD

**Issue by Hirmuolio** [CleverRaven/Cataclysm-DDA#40347]
# Describe the bug

"^" is a dead key on some keyboard layouts and does not work the way you would expect bound keys to work.

# Steps To Reproduce

1. Have an action bound to "^".
2. Press "^". Nothing happens.
3. Press some other unrelated key (For example spacebar. Not "a", "i", "o" or other kay that creates different letter when used with "^"). 
4. Suddenly the "^" press is registered.

# Expected behavior

If "^" is bound to an action pressing "^" should do that immediately.

That is probably not easy fix. So the "^" key should probably be replaced with some other key in default keybindings.

# Screenshots

# Versions and configuration

OS: Windows 10 (Finnish)  
Keyboard: [Finnish multilingual](https://en.wikipedia.org/wiki/QWERTY#Finnish_multilingual_keyboard)

# Additional context

"^" is a dead key on many keyboard layouts to allow inputting special letters like â, î and ô. This is probably the cause for the problem. 
Wikipedia says that the basic US keyboard layout does not have any dead keys directly on the keyboard so "^" probably works without issues on those.

Other dead keys  probably also have same problem; "¨", "~", "´", "`". I don't think these are used as default key for anything.

**Comment by Qrox** [comment]
This is a known issue, see #22664. I think someone mentioned in another issue that the problem lies in the fact that the current code takes character input instead of key code input, but I can't find the exact issue at the moment.
