### ISSUE TITLE
Padding a back pack diminishes encumbrance

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#40368]
# Describe the bug
I use a tailor kit to modify a survivor rucksack. The window that pops up says that  encumbrance will go from 14 -> 5

# Steps To Reproduce
Summon tailor kit and rucksack. Use tailor kit to modify the bag.

# Expected behavior
Encumbrance shouldn't diminish when you add material.

# Screenshots
![Capture d’écran_2020-05-09_02-12-45](https://user-images.githubusercontent.com/7557986/81458430-a526dc80-919a-11ea-9d86-6c9efd8c2ba3.png)

**Comment by matt32106** [comment]
If I modify the bag then the encumbrance increase to 16. So it is the message which is  wrong.

**Comment by RoyBerube** [comment]
This probably happens only with variable encumbrance gear such as backpacks. Will look into it.

**Comment by anothersimulacrum** [comment]
It's very likely displaying the max encumbrance in the first part, and the normal encumbrance in the second.

**Comment by RoyBerube** [comment]
Is this happening on the stable branch? The screenshot displays the storage capacity which is no longer shown in the latest experimental branch. That section of code has been removed - probably because it can never change.

Anyway, it seems that variable encumbrance is not changing for backpacks now in experimental. So I can't replicate this problem due to that.

**Comment by matt32106** [comment]
OP here: sorry, I forgot to mention my version:
- OS: Linux
    - OS Version: LSB Version: core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch; Distributor ID: Ubuntu; Description: Ubuntu 18.04.4 LTS; Release: 18.04; Codename: bionic; 
- Game Version: 0.E-238-g6393a6d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Stats Through Skills [StatsThroughSkills],
    Alternative Map Key [alt_map_key],
    No Fungal Monsters [No_Fungi]
]

**Comment by matt32106** [comment]
Closing as "section of code has been removed" from experimental.
