### ISSUE TITLE
Ammo pouch more problems.

### ISSUE THREAD

**Issue by Katanasoul91** [CleverRaven/Cataclysm-DDA#40364]
The Ammo pouch multiple issues.
---------------------------------
Ammo pouch lack of Volume and Weight Capacity.

Ammo pouch overlooks any loose ammo if you have more than 60.

Ammo pouch doesn't accept multiple kinds of ammo unless it is from auto-assign from the pickup.

Ammo pouch item destruction.

Ammo pouch contents are considered a different pile from the same kind of ammo.

Ammo pouch can't reload manually.
------------------------------
# Steps To Reproduce

Ammo pouch lack of Volume and Weight Capacity.
1. You can see it in the inventory

Ammo pouch overlooks any loose ammo if you have more than 60.
1. Get different kinds of loose ammo in the inventory.
2. Wear the Ammo pouch (to prevent having to unload it)
2. Select Insert in the Ammo pouch options.
3. Any and all pile with more than 60 amount isn't notice by the pouch.

Ammo pouch doesn't accept multiple kinds of ammo unless it is from auto-assign from the pickup.
1. Wear Ammo pouch.
2. Pick up different loose ammo, but the sum mustn't be higher than 60.
3. Open Ammo pouch and see different kinds of ammo here.

Ammo pouch item destruction.
1. Insert any kind of loose ammo in the pouch.
2. The amount doesn't matter.
3. Select insert from the pouch and a different window will open, this one ignores the "only loose ammo" rule.
4. Select anything to go into the pouch.
5. The selected item is destroyed.

Ammo pouch contents are considered a different pile from the same kind of ammo.
1. Insert any kind of loose ammo into the pouch.
2. Grab more than ammo, the sum of the picked ammo plus the on the in pouch must be higher than 60.
3. Look at the inventory, the ammo in the pouch is considered apart from the rest of your inventories.

Ammo pouch can't reload manually.
1. Put some ammo into the pouch
2. Grab the same type of ammo but the sum between the pouch and the grabbed must be higher than 60.
3. Drop or use the ammo until you have 60 of said ammo or less.
4. Select insert on the pouch and select the ammo in your inventory (the sum must be lower than 60)

-------------------------------
# Expected behavior

Ammo pouch lack of Volume and Weight Capacity.
- Should set a Volume and Weight, this lack of thereof could be the reason for all the following problems.

Ammo pouch overlooks any loose ammo if you have more than 60.
- This is related to the original use of the pouch where it limit was 60 to a single type of loose ammo, with the implementation of Weight and Capacity this should be obsolete.

Ammo pouch doesn`t accept multiple kinds of ammo unless it is from auto-assign from the pickup.
- If you can`t insert the ammo you want into it, the system shouldn`t be able to do so.

Ammo pouch item destruction.
- Not only this should look for loose ammo, but the destruction shouldn`t happen.

Ammo pouch contents are considered a different pile from the rest.
-The ammo as a whole should be taken into consideration.

Ammo pouch can`t reload manually.
-The pouch before the individual containment, allowing you to use the "r" to reload the Ammo pouch, which was a quick way to use it.

-----------------------------------
# Versions and configuration

Version 10640
Windows 10 64 bits.    

Final Note:
Personally, I think if you consider the Ammo pouch as a magazine or treat the pouch as a container only for those things with an ammunition type restriction it could resolve must of the problem.

**Comment by KorGgenT** [comment]
All of the bullet points have either been addressed recently or are not valid as misunderstandings of the nested container system.
