### ISSUE TITLE
[BUG] [U]nloading a container from a container will make a duplicate and then crash the game if you try to unload it again

### ISSUE THREAD

**Issue by AGasCanister** [CleverRaven/Cataclysm-DDA#40365]
# Describe the bug 
Basically what the title says, if you try to directly to [U]nload a container that's inside a container, the container will drop but with a duplicate inside the container, then if you try to [U]nload the container again, the duplicate will crash the game. Let me make it a bit more clear.

# Steps To Reproduce
Container B is in container A, you [U]nload container A, container B is now on the ground, but there's a copy of container B in container A, you [U]nload container A again, the game crashes.

# Expected behavior
The idea is that you should be able to unload container A without making a duplicate of container B, because even the volume and weight value still applies.

# Screenshots (A video actually)
https://cdn.discordapp.com/attachments/458150341742166017/708431344060989511/Desktop_2020.05.08_-_23.06.44.02.mp4

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-1933-gdba5bd1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
[Save Debug and Crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4601805/Save.Debug.and.Crash.zip)

**Comment by KorGgenT** [comment]
![image](https://user-images.githubusercontent.com/30208401/82745703-5611a780-9d55-11ea-86db-c17ec40c7468.png)
could not reproduce - had bandages inside a large plastic bottle and tried to unload it. it placed it itno the backpack.
