### ISSUE TITLE
Aftershock: Sterile Crafted CBMs

### ISSUE THREAD

**Issue by TheDarkMaster13** [CleverRaven/Cataclysm-DDA#40363]
# Describe the bug

A newly crafted CBM starts with the 'sterile' tag.

# Steps To Reproduce

Craft any CBM.

# Expected behavior

Crafted CBMs should have to be sterilized in an autoclave before they can be installed.  The player should have to first pack them and then run them through an autoclave after they've been crafted.

**Comment by Maleclypse** [comment]
Probably going to have to resolve this by adding tools and items to CBM recipes rather them being created non-sterile. This is due to json limits compared to C++.
