### ISSUE TITLE
Cannot attatch gun mods to guns

### ISSUE THREAD

**Issue by Thomasasia** [CleverRaven/Cataclysm-DDA#40376]
# Describe the bug

I am unable to put gun mods onto guns. Specifically, I tried to put a shoulder strap on a double barrel shotgun and a flintlock rifle, but on both occasions when I (a)ctivate the mod to put it on the weapon, the selection screen says "there are no available choices".

# Steps To Reproduce

1. Make a player with a gun and a gun mod
2. Activate the gun mod, in order to attach it to a gun
3. No guns are shown in the selection screen.

# Expected behavior

What should happen is the possible guns to attach the mod to should show up, and then be able to select the gun you want. 

# Screenshot

![Screenshot from 2020-05-09 02-24-40](https://user-images.githubusercontent.com/19173387/81466024-4febca80-919c-11ea-9787-8a67fe3151a7.png)

This is what I see after activating the shoulder strap, while I have a valid gun in hand.

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.E-1942-g54e575fca5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

Not sure if it helps, but here is the debug.log:
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4602820/debug.log)

And here is my save file:
[Test Place.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4602822/Test.Place.zip)

**Comment by Resok** [comment]
Did you try with the gun unloaded? I believe this is a requirement. I was able to attach gunmods to a weapon in the latest build, but only after removing any cartidges.

**Comment by Thomasasia** [comment]
> Did you try with the gun unloaded? I believe this is a requirement. I was able to attach gunmods to a weapon in the latest build, but only after removing any cartidges.

Thanks, that appears to have been an issue. 

Back in _my_ day, the gun would shoot you if you tried to modify a loaded gun, haha.

**Comment by hexagonrecursion** [comment]
The UI should be improved. It should display loaded guns in the menu, but grayed out with a message explaining that you should unload the gun first. Otherwise it is hard for a new player to figure this mechanic out.
