### ISSUE TITLE
Full Butchery using a Steel Boom

### ISSUE THREAD

**Issue by JovialEvil** [CleverRaven/Cataclysm-DDA#40386]
Trying to use a Vehicle Mounted Steel Boom as a part for the action of Full Butchery.

1. Set up Leather Tarp and Table, and have Long Rope in your inventory with Butchery Tool.
2. Have a Carcass that requires an object to suspend or hoist it from with the Long Rope to perform the Full Butchery Action.
3. Try to use a Vehicle Mounted Steel Boom as the object to suspend or Hoist the Carcass.
4. Game responds with, "You need to suspend this corpse to butcher it. while you have a rope to lift the corpse, there is no tree to hang it from."

# Expected behavior

I expected the Vehicle Mounted Steel Boom to be able to suspend or Hoist a Carcass into the air with the Long Rope for Full Butchery.

# Screenshots

![unknown](https://user-images.githubusercontent.com/45611714/81474067-b090fc80-91c8-11ea-929c-c2118685ac81.png)

# Versions and configuration

May 5th Experimental on Windows 8

**Comment by ZhilkinSerg** [comment]
Was it working in any of previous versions?

**Comment by cirops** [comment]
I believe he wants this as a feature, which doesn't currently exist in the game, basically making a crane work like current hanging meathook, but for vehicles.

**Comment by wapcaplet** [comment]
This appears to be addressed by #40400
