### ISSUE TITLE
Animal tying kills backpack

### ISSUE THREAD

**Issue by DeclanFrost** [CleverRaven/Cataclysm-DDA#40393]
# Describe the bug

When tying a horse down with a long rope from a travelpack, the travelpack disappears along with its contents.

# Steps To Reproduce

1. Tie down horse using long rope from travelpack.
2. Check inventory.

# Expected behavior

It shouldn't take a backpack to tie down a horse.

# Screenshots

![Screenshot (164)](https://user-images.githubusercontent.com/41840942/81484889-eb1d8800-920e-11ea-8270-eabf58f060f1.png)

![Screenshot (162)](https://user-images.githubusercontent.com/41840942/81484897-f7a1e080-920e-11ea-9fe6-4dd7fcb31389.png)

![Screenshot (163)](https://user-images.githubusercontent.com/41840942/81484901-fe305800-920e-11ea-9bf7-2f50cc5b4d84.png)

# Versions and configuration

OS: Windows
OS Version: 10.0 1903
Game Version: 0.E-1933-gdba5bd1 [64-bit]
Graphics Version: Tiles
Game Language: System language []
Mods loaded: [
Dark Days Ahead [dda],
Magiclysm [magiclysm],
Disable NPC Needs [no_npc_food],
Stats Through Kills [stats_through_kills]
]

# Additional context

[horsechicken.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4604480/horsechicken.zip)

**Comment by Fadragnir** [comment]
I'm having the same issue 
Game version: 0.E-2844-gede5ff2 (tiles)

**Comment by bloodraven983** [comment]
happened to me too when i tied a rabbit in my shelter, couldn't reproduce the bug
