### ISSUE TITLE
Taurus Spectrum magazine is too small for Ankle Ammo Pouch

### ISSUE THREAD

**Issue by voidus** [CleverRaven/Cataclysm-DDA#40394]
This is on 0.E. My best guess is that this is a consistency bug, but please feel free to make this a discussion or say it's as intended.

The Taurus Spectrum magazine has a volume of 0.074L, while the ankle holster has an item volume range from 0.08L to 0.25L, which excludes the Taurus Spectrum magazine.

My understanding is that the ankle ammo pouch should be able to hold the smallest magazines, and wearing a spare subcompact mag on an ankle seems reasonable to me (but then again, my firearms-related knowledge is very limited.

I cannot tell whether the ankle holster should allow smaller mags, the mag size should be increased, or this is working as intended.

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.E [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro]
]

**Comment by voidus** [comment]
I guess this is related (or part of?) to #37374

**Comment by LaVeyanFiend** [comment]
> I cannot tell whether the ankle holster should allow smaller mags, the mag size should be increased, or this is working as intended.

Option 1 most likely, option 2 won't happen since that _is_ the volume of the magazine 🤷

**Comment by NetSysFire** [comment]
![image](https://user-images.githubusercontent.com/59517351/150864516-208e51da-5181-4551-8794-e109d8a2bd51.png)

Looks like it actually works now in master.
