### ISSUE TITLE
Build #10644 - Item on drop issue

### ISSUE THREAD

**Issue by CrankyUnicorn** [CleverRaven/Cataclysm-DDA#40397]
# Describe the bug
I 'm using Dark Skies mod the native one

1# Item "none" is create every time I try to drop a specific book, forgot name. The book doesn't disappear from inventory.

2# After that droped some guns and they disappear on the floor.

00:35:37.005 ERROR : src/visitable.cpp:60 [item* visitable<T>::find_parent(const item&) [with T = Character]] Tried to find item parent using an object that doesn't contain it
00:35:37.005 ERROR : src/character.cpp:2407 [item Character::i_rem(const item*)] did not found item none to remove it!

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4604916/debug.log)

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-10962.
