### ISSUE TITLE
Hot Dog Car Floor Cloning

### ISSUE THREAD

**Issue by MrMakkie** [CleverRaven/Cataclysm-DDA#40409]
Game version: 10647

Operating system: Windows 10

Tiles or curses:

Mods active: Aftershock, Blaze Industries, C. R. I. T, Mutation Changes, Stats through Skills, No Freeze, Dinomod, Alternative Map Key, Cataclysm++, Mythical Martial Arts, No Rail Stations, Graphical Overmap

### Expected behavior
When placing a stack of hot dogs on a car seat while not having inventory space, one should be able to pick them up and wield them with no issue. 
### Actual behavior
When attempting to pick up a stack of 10 hot dogs from the floor of a car, you are prompted to wield them due to minimal space. When you say you wish to wield them, you're suddenly asked if you wish to drop the stack of 10 hot dogs to wield... The stack of 10 hot dogs. If you cancel out, you will mysteriously be carrying 10 hot dogs, but there will also be 10 hot dogs on the car floor. Spooky Sausages, Batman! 
### Steps to reproduce the behavior
1: Get nakey. 
2: Drop a stack of hotdogs, unpackaged, onto the bed of a vehicle.
3: Attempt to pick them up again.
4: When prompted, say you wish to wield them.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-10962.
