### ISSUE TITLE
Washing items only cleaning one item per stack selected.

### ISSUE THREAD

**Issue by ussdefiant60** [CleverRaven/Cataclysm-DDA#40404]
# Describe the bug

If i'm trying to wash a stack of filthy rags or plastic chunks or other such things i get out of 
cutting up zombie drops, i only get one clean item back per stack i'm trying to wash. the rest of the stack just returns to my inventory as filthy stuff. I get charged the amount of soap as though it'd washed the full stack, too.

Notably, if the items are split up into multiple stacks due to pocket space limitations or the like, one item out of each stack are cleaned.

# Steps To Reproduce

1)Have a washboard with soap next to a water source.
2)Acquire filthy rags/plastic chunks/leather patches/other stackable things via whatever method you desire.
3)Attempt to clean stacks of filthy things.

# Expected behavior

1)All the items in the stack of filthy stuff should be cleansed instead of just one.

# Versions and configuration

This is on build 10644, Win 10 64-bit. Mods are Dinomod, Blaze Industries, Aftershock, Magicclysm, and Stats Through Kills.

**Comment by Katanasoul91** [comment]
I think it is a problem with the stacking system because when I try to drop the patches and other parts it has to be taken one by one from the inventory and drop it on the floor, so dropping 60 leather patches took me several minutes in-game.
