### ISSUE TITLE
Unloading Clothing Bug

### ISSUE THREAD

**Issue by buildfailedforallplatforms** [CleverRaven/Cataclysm-DDA#40406]
Unloading clothing causes all items with a charge to have 1 charge, e.g. lighter with a charge of 100/100 will have 1/100, this is the same with all items. 

Droping them normally doesn't seem to affect them only unloading clothing.

**Comment by buildfailedforallplatforms** [comment]
Running build - 10645

Mods
Dark Days Ahead
Aftershock
CRIT expansion
Magiclysm

**Comment by KorGgenT** [comment]
cannot reproduce - please open a new issue if the error still persists, with new reproduction steps. lights have changed recently so i tried with medical gauze.
