### ISSUE TITLE
More powerful turret

### ISSUE THREAD

**Issue by yuganxia** [CleverRaven/Cataclysm-DDA#40419]
**Is your feature request related to a problem? Please describe.**
The turrets in game is quiet powerful at beginning of the game,but a little bit easy to deal with when you armed up.
Some special tactics even make them like dummy at the very beginning of the game( such like use of large cardboard boxes ---SNAKE POWER LOL).
Some of the tactics works because turrets have poor sensors of detection,which should not that poor in a world full of bionic,automata and mutation.
There should be some more tricky torrents to make important place harder to access at all game time.

**Describe the solution you'd like**
Maybe we could increase the ability of detection to make turrets more deadly.

We could add some advanced turrets
- Night vision turrets
- Infrared vision turrets
- EMP proof turrets
- Hack proof turrets
- Self-destructive turrets (if detected player , use fire/explosion to destroy resources near by)

**Describe alternatives you've considered**
The special effects above should never appeared in one turret more than three.
A hack proof, infrared vision, fire self-destructive turret can be a game play destroyer.

**Comment by cirops** [comment]
I have no opinion on trying to make even stronger turrets, but I do think they should be configured to destroy their ammo upon being destroyed, because getting 1000's of powerful rounds for turrets that can, like you said, be cheesed in some situations, is too much.

If this was the direction decided, it is just a matter of removing the "DROPS AMMO" flag from them.

**Comment by Sumguy62** [comment]
Turrets are planned to have improved AI at some point. Turrets self-destructing when disabled is very game-y, and I doubt that's ever going to happen. The ammo piñata aspect will likely not change, but they'll probably become harder to crack open once they get someone to work on them.

**Comment by Testudo-Cultu** [comment]
Turrets don't need to be stronger overall, in my opinion. They're the main hazard in pretty much any place you'll find them already. We just need bigger threats alongside.

**Comment by yuganxia** [comment]
Maybe director have their own concern.Maybe they want turrent to be redeployable.Maybe they think player turrent on car need that amount of ammo.
But i think there is some other way to make ammo piñata thing invalidate.
Just make dropped ammo less common (NOT .223 .308 .50).Or make dropped ammo useful via reloaded or use some other formula.
Or further,make dropped ammo only can be used by turrents.That will solve most of the problem.

**Comment by anothersimulacrum** [comment]
It doesn't solve the problem because it doesn't make sense. Why would the army introduce up to 3 different new ammo types that their soldier's guns can't fire? That introduces a bunch of entirely pointless new logistics work.

**Comment by waveyl** [comment]
Infrared vision is a good idea, because I can kill turrents by spear and large cardbord box without counterattack. It means turrent don't realize he is stabbing until he died. It sounds magic.

**Comment by Mecares** [comment]
> 
> 
> Infrared vision is a good idea, because I can kill turrets by spear and large cardbord box without counterattack. It means turret don't realize he is stabbing until he died. It sounds magic.

Maybe the returning fire code that already is in the game could be adapted to also react to melee attacks from "invisible" attackers.
