### ISSUE TITLE
Crash when dropping protein rations and paper wrappers at the same time

### ISSUE THREAD

**Issue by AzyWng** [CleverRaven/Cataclysm-DDA#40428]
# Describe the bug

When dropping protein rations in paper wrappers and the paper wrappers at the same time, the game crashes.

# Steps To Reproduce

1. Pick up some of paper wrappers of protein rations.
2. Enter the multidrop menu and select both the protein rations in the Food category and the paper wrappers in the containers category. The paper wrappers that contain the protein rations may simply appear as "paper wrapper" rather than "paper wrapper of protein ration".
3. The game crashes.

# Expected behavior

I expected the protein rations and paper wrappers to be dropped as separate items.

# Screenshots

No applicable screenshots.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-1970-g3278b58
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: Dark Days Ahead, Disable NPC Needs, No Rail Stations, Graphical Overmap, No Fungal Monsters

# Additional context

<!-- Add any other context about the problem here.

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4607227/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4607228/debug.log)

Unfortunately, I didn't save before the crash occurred.

**Comment by mrkybe** [comment]
Do you have a save where this happens consistently?  I wasn't able to reproduce it.

**Comment by KorGgenT** [comment]
the thing that's supposed to happen in the inventory code is disallowing you to select a container and its contained items

**Comment by AzyWng** [comment]
Unfortunately, the game crashed before an autosave triggered. I'll see if I can't try to reproduce the bug on my own and get a save file of it that way.

**Comment by hexagonrecursion** [comment]
I could not reproduce this bug.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 0.F-2004-gada3852d39 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]
