### ISSUE TITLE
Connected vehicle doors close even if there is a monster in the way

### ISSUE THREAD

**Issue by cirops** [CleverRaven/Cataclysm-DDA#40422]
# Describe the bug

If you have connected vehicle doors (e.g triple humvee trunk doors), and there is a monster in one of them, and you try to close the specific door in which the monster is at, the game forbids because the monster is in the way. However, if you try to close the other two, the game doesn't check if all connected doors are clear, thus slamming the door shut and pushing the monster away.

# Steps To Reproduce

1. Get a Humvee (e.g. debug spawn).
2. Open back trunk door.
3. Spawn a Kevlar Hulk in the middle trunk door.
4. Try to close that door in which Hulk is, without success.
5. Try to close any of the other two, and watch how gigantic hulk is just shoved aside by trunk door.

# Expected behavior

When trying to close connected doors, the game should check for all tiles connected for occupants, and not let the player close if any is blocked. 

# Versions and configuration

Tested for builds 10639 and 10614, with or without mods, last test config below:

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-1915-g97e3499 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    sees-player icon, retrodays [sees_player_retro],
    Magiclysm [magiclysm],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

(shallow code-diving as practice)
I suspect, in **gates.cpp:260**:
```
    const Creature *const mon = g->critter_at( closep );
    if( mon ) {
        if( mon->is_player() ) {
            who.add_msg_if_player( m_info, _( "There's some buffoon in the way!" ) );
        } else if( mon->is_monster() ) {
            // TODO: Houseflies, mosquitoes, etc shouldn't count
            who.add_msg_if_player( m_info, _( "The %s is in the way!" ), mon->get_name() );
        } else {
            who.add_msg_if_player( m_info, _( "%s is in the way!" ), mon->disp_name() );
        }
        return;
    }
```
this should test for all connected tiles, just like it does for checking further doors to close right below:
```
if( optional_vpart_position vp = m.veh_at( closep ) ) {
        vehicle *const veh = &vp->vehicle();
        const int vpart = vp->part_index();
        const int closable = veh->next_part_to_close( vpart,
                             veh_pointer_or_null( m.veh_at( who.pos() ) ) != veh );
```
Not sure about the exact details (hence not just submitting a PR instead of a bug report).

**Comment by irwiss** [comment]
Likely already fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/46536 it no longer closes multitile doors on monsters
