### ISSUE TITLE
[BUG?]Very simple vehicle can be used as ladder.

### ISSUE THREAD

**Issue by yuganxia** [CleverRaven/Cataclysm-DDA#40427]
**# Describe the bug**
Very simple vehicle can be used as ladder.

**# Steps To Reproduce**
1. Create a vehicle with whatever frame
2. Attach a wing mirror/spike/wooden spike or whatever foldable and climbable vpart next to the frame.
3. Remove the frame
4. Put it next to a building step on it 
5. now you can climb the building by press <.
6. This little ladder even can be folded and put into your bag.

**# Expected behavior**
That is kind of hilarious.
I can climb on a building by step on a thing which less than 0.5L after folded.
That make stepladder in game useless.

**# Screenshots**

![Snipaste_2020-05-11_09-50-12](https://user-images.githubusercontent.com/31246176/81517812-a7da2b00-936e-11ea-84e1-648fcc888b6c.png)
![Snipaste_2020-05-11_09-51-14](https://user-images.githubusercontent.com/31246176/81517815-aa3c8500-936e-11ea-9f3e-b89b146bbd45.png)
![Snipaste_2020-05-11_09-51-01](https://user-images.githubusercontent.com/31246176/81517829-b0326600-936e-11ea-8b3c-ff8a54fb077a.png)

**# Versions and configuration**
- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.E-1970-g3278b58 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**# Additional context**
Game will crash in #10647 (which will not in 0.E stable) when you try to step on  your fodable ladder.

```
src/generic_factory.h:404 [int_id<T> generic_factory<T>::convert(const string_id<T>&, const int_id<T>&) const [with T = ter_t]] invalid terrain id "wing_mirror"
09:50:26.335 ERROR : src/generic_factory.h:404 [int_id<T> generic_factory<T>::convert(const string_id<T>&, const int_id<T>&) const [with T = ter_t]] invalid terrain id "wing_mirror"
09:50:27.775 ERROR : src/generic_factory.h:404 [int_id<T> generic_factory<T>::convert(const string_id<T>&, const int_id<T>&) const [with T = ter_t]] invalid terrain id "wing_mirror"
09:50:28.297 ERROR : src/generic_factory.h:404 [int_id<T> generic_factory<T>::convert(const string_id<T>&, const int_id<T>&) const [with T = ter_t]] invalid terrain id "wing_mirror"
09:50:34.936 ERROR : src/generic_factory.h:404 [int_id<T> generic_factory<T>::convert(const string_id<T>&, const int_id<T>&) const [with T = ter_t]] invalid terrain id "wing_mirror"
09:50:35.472 ERROR : src/generic_factory.h:404 [int_id<T> generic_factory<T>::convert(const string_id<T>&, const int_id<T>&) const [with T = ter_t]] invalid terrain id "wing_mirror"
09:50:49.991 ERROR : src/generic_factory.h:404 [int_id<T> generic_factory<T>::convert(const string_id<T>&, const int_id<T>&) const [with T = ter_t]] invalid terrain id "wing_mirror"
09:50:51.592 ERROR : src/generic_factory.h:404 [int_id<T> generic_factory<T>::convert(const string_id<T>&, const int_id<T>&) const [with T = ter_t]] invalid terrain id "wing_mirror"
09:51:07.879 ERROR : src/generic_factory.h:404 [int_id<T> generic_factory<T>::convert(const string_id<T>&, const int_id<T>&) const [with T = ter_t]] invalid terrain id "wing_mirror"
09:51:08.615 ERROR : src/generic_factory.h:404 [int_id<T> generic_factory<T>::convert(const string_id<T>&, const int_id<T>&) const [with T = ter_t]] invalid terrain id "wing_mirror"
09:51:38.136 ERROR : (error message will follow backtrace)
```

**Comment by int-ua** [comment]
Still an issue in latest experimental.
