### ISSUE TITLE
#38056 Bug when using disabled Tilesets on Tiles CDDA Version.

### ISSUE THREAD

**Issue by BBarian** [CleverRaven/Cataclysm-DDA#40434]
When dragging a shopping cart, there's a line of shopping carts left behind in the memory map. Tried with Sepia memory map.

# Steps To Reproduce

1. Load up #10648 and set Use Tiles: False in Graphics settings. 
2. Spawn/Acquire a shopping cart and drag in a dark area, inside a grocery store, underground, outside, etc.

# Expected behavior
Ideally the shopping cart should not remain in the memory map while being dragged.

# Screenshots
![image](https://user-images.githubusercontent.com/65096483/81526994-2d39ed00-9327-11ea-9b34-71a6bc73444b.png)

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-1992-g6913049
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: DDA, Aftershock, Blaze Industries, CRIT Expansion, Magicalysm, Stats through Kills, Stats through Skills, SpeedyDex, Fuji's Military Profession Pack

# Additional context
Related to #38056 and #37460, potentially.

**Comment by Night-Pryanik** [comment]
Duplicate of #28512?

**Comment by BBarian** [comment]
Not a duplicate I would hope, I was told that the issue was solved for tiles, but not for ascii rendering, since the code is different for both methods. Memory map draw is not bugged when using tiles in this manner, but is bugged when turning tiles off.
