### ISSUE TITLE
Debugmsg occurs when player activates elevator on a vehicle

### ISSUE THREAD

**Issue by RedShakespeare** [CleverRaven/Cataclysm-DDA#40445]
# Describe the bug

When player who's on board tries to activate an elevator, debugmsg occurs.
This bug is of two parts:
- When player stand on a vehicle (in elevator) and activate the elevator to move up-/downwards and then move to other blocks, debugmsg says the player tries to unboard a vehicle that is not found.
- When the player uses elevator to go back and tries to get on the vehicle again, another debugmsg bursts out to say the player has already been on the vehicle.

# Steps To Reproduce

1. Make an elevator (of two levels) with an elevator control, a vehicle in one of the elevator and a player on the vehicle.
2. [e]xamine the elevator control and choose [Y] to confirm.
3. Move to any direction. First debugmsg.
4. [e]xamine the elevator control and confirm again.
5. Get on the vehicle again. Second debugmsg.

# Expected behavior
Either the vehicle should be moved with the player, or a judgement should be there to avoid this condition.

# Screenshots
First:
![image](https://user-images.githubusercontent.com/44523519/81567393-d2f46700-93ce-11ea-8fec-ddc122160185.png)

Second:
![image](https://user-images.githubusercontent.com/44523519/81567362-cb34c280-93ce-11ea-844c-1814d03ee27d.png)

# Versions and configuration

- Game Version: build 10613 or 0.E-1461-gcf7473e
- Mods: dda and any other mods

**Comment by Night-Pryanik** [comment]
Fixed by #58840.
