### ISSUE TITLE
Negative number of item after stacking overflow max limit.

### ISSUE THREAD

**Issue by Erozaxx** [CleverRaven/Cataclysm-DDA#40444]
# Describe the bug
I wanted to pickup 100 aspirins, but my inventory already contained some aspirins in the pocket and stacking would bring the number over 100 which would overflow the pocket. My inventory accepted the 80 aspirins and I got a message saying stacking would not fit in the pocket with the number -20 which corresponded to the difference. The aspirins left on the counter have now this negative value as its count, as well as the negative volume and negative weight if you inspect it. I can pickup the item and carry it over.

# Steps To Reproduce

1. Have some amount of aspirins in your pocket
2. Try to pickup amount of aspirins which would bring your pocket amount over the max limit.
3. Aspirins leftover after unsuccessful stacking should have negative value.

# Expected behavior

I'd expect the remaining items not collected would have the amount corresponding to the remaining number of items which did not fit in the pocket. Definitely a positive value.

# Screenshots
[https://imgur.com/a/zvPmcHD](https://imgur.com/a/zvPmcHD)

# Versions and configuration
 - OS: Windows 10 x84
 - Game Version: 0.E-2036-gf6d85ac
 - Graphics version: Tiles (DEADPEOPLE)
 - Ingame language: English
 - Mods loaded: Disable NPC Needs, No Fungal Monsters

# Additional context
Savegame provided

**Comment by Erozaxx** [comment]
I've just realized on another save, that when I hold in hands the item with negative number and drop the original stack, which was in my pocket, the item I hold in hands reverts to non-negative item. This time I picked up raw pelt where 3 ended in my pocket, filled the pocket up and in my hand I was holding pelt (-1). As soon as I've dropped the pelts from pocket into the drawer, the pelt in my hands turned to standard single item.

**Comment by DillonSimeone** [comment]
I just encountered this.

![image](https://user-images.githubusercontent.com/21962421/82009129-5908eb80-9623-11ea-9531-730f446b4193.png)
![image](https://user-images.githubusercontent.com/21962421/82009135-5e663600-9623-11ea-9f8d-b283e0cfb504.png)

**Comment by DillonSimeone** [comment]
I just noticed that this triggered a really strange bug after unloading my inventory.

![image](https://user-images.githubusercontent.com/21962421/82010262-725f6700-9626-11ea-86f6-cfd998e72b37.png)
![image](https://user-images.githubusercontent.com/21962421/82010268-77241b00-9626-11ea-9460-5264c3b4d712.png)

Each time I take a step, my character tries to pick up a 0 casting and wield it!

**Comment by Erozaxx** [comment]
> ![image](https://user-images.githubusercontent.com/21962421/82010614-78097c80-9627-11ea-8bdf-681156b308de.png)

I love your

**Comment by Erozaxx** [comment]
Sorry, misclick

**Comment by p-dimi** [comment]
Same thing happening here. I recorded and uploaded it for a quick demonstration.
After foraging acorns from a tree, despite having sufficient volume - I cannot hold onto all the acorns harvested. Instead every time one acorn is picked up, the previous acorn (held in hand) only gives me the option of dropping it.
After the pick up new acorn / drop old acorn cycle, the ground has a negative amount of acorns , and so does my character's hand. The acorns give a negative weight and volume as well.

Video (38 seconds long): https://www.youtube.com/watch?v=-_Ad407wEuA
It's a bit weird because the bug kinda stucked my computer and made the recording software not responsive, but it demonstrates the issue.

**Comment by PlatoSoft** [comment]
This just happened to me on the latest build, game crashed when i tried to drop & pick up the negative stack.

**Comment by KorGgenT** [comment]
reproduced it fine yesterday, but when i sat down to try to work through it today i couldn't get the aspirin to go negative.
