### ISSUE TITLE
The      "      key keeps disappearing on android, forcing me to pull the keyboard and press the key there to stop running (or crouching).

### ISSUE THREAD

**Issue by rafaelkb** [CleverRaven/Cataclysm-DDA#40449]
# Describe the bug

The comma disappear from the keys when i kill all enemies on the screen forcing me to press my keyboard.

# Steps To Reproduce

<!-- Steps to reproduce the behavior:

1- Toggle run when engaging in combat.

1- kill all enemies.

3- now you need to MANUALLY toggle run.

# Expected behavior

I expect the key to not vanish the screen and be there all time.

# Additional context

I have no problems with the key g and the key > or <. They appear all the time,

**Comment by ZhilkinSerg** [comment]
Did you try reassigning the key for this action? Is it disappearing with a different keybinding too?

Did you try putting this key to "Default gameplay shortcuts" in options?

What are your values of "Auto-manage contextual gameplay shortcuts", "Move contextual gameplay shortcuts to front", "Turns to remove unused gameplay shortcuts" and "Shortcuts persistence" options?
