### ISSUE TITLE
Mutation Changes mod prevents game from loading.

### ISSUE THREAD

**Issue by Kanexan** [CleverRaven/Cataclysm-DDA#40458]
# Describe the bug

Upon trying to load a world with the Mutation Changes mod installed, there is an error in the Chimera entry that forces a return to the main menu.

# Steps To Reproduce

1. Create a world that includes the Mutation Changes mod
2. Attempt to create a new character in that world or load a previously-existing character in that world.

# Expected behavior

The game to load correctly and not crash, with the mod loading as expected.

# Screenshots
N/A
# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-2037-g2abca8f
 - Graphics version: Tiles
 - In-game language: English
 - Mods loaded: DDA, No NPC Needs, Mutation Changes

# Additional context

Save file is not applicable; crash occurs before character can be created.
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4611580/debug.log)

**Comment by anothersimulacrum** [comment]
Mutation changes mod is third party.

**Comment by Kanexan** [comment]
Huh. Did not realize that.
