### ISSUE TITLE
contents-item doesn't spawn an item

### ISSUE THREAD

**Issue by ymber** [CleverRaven/Cataclysm-DDA#40456]
# Describe the bug
Items that are specified by `contents-item` in itemgroups do not spawn.

# Steps To Reproduce
1. Spawn with bionic prepper profession
2. Crossbow has no sling

# Expected behavior
`contents-item` works properly.

# Versions and configuration
- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.E-2037-g2abca8ff23-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
`contents-group` works as expected.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-10953.
![изображение](https://user-images.githubusercontent.com/11132525/187451427-768ab0f3-5a1d-44a2-81f5-5a8f0945b734.png)
