### ISSUE TITLE
First Aid Kit liquids spawning without containers

### ISSUE THREAD

**Issue by bbborracho** [CleverRaven/Cataclysm-DDA#40462]
Describe the bug
When using first aid kits, liquids spawn without containers and spill onto the floor. 

1. Find a first aid kit.
2. [a]ctivate the kit to receive its contents.
3. Antiseptic and saline solution spill onto the floor.

Expected behavior
The antiseptic and saline solution from first aid kits previously spawned in plastic bottles.

Versions and configuration
Wasn't able to do generate the report as requested, as the character who experienced bug died of infection. Bug happened in version  on , tiled version
  - OS: Windows 10
 - Game Version: 0.E-2037-g2abca8f
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: 
        -Dark Days Ahead
        -Disable NPC Needs
        -Speedy Dex
        -Stats Through Kills
        -Stats Through Skills
        -Aftershock
        -Magiclysm
        -Generic Guns
        -C.R.I.T. Expansion Mod
        -Crazy Cataclysm
        -Alternative Map Key
        -Mining Mod
        -Mythical Martial Arts
        -Graphical Overmap

**Comment by KorGgenT** [comment]
my ideal fix: first aid kits become containers with an itemgroup that spawn the items in them.

**Comment by bbborracho** [comment]
So, I've played a bit since this and it's pretty inconsistent when this happens.

Any tips on avoid this sort of this thing happening in the meantime?

**Comment by DillonSimeone** [comment]
This isn't happening for me. Tested with damaged kits to check if you could lose the bottle but still recover the liquids, didn't happen. 

![image](https://user-images.githubusercontent.com/21962421/82745490-e3df9980-9d39-11ea-88c7-540bf15babd8.png)

![image](https://user-images.githubusercontent.com/21962421/82745491-e8a44d80-9d39-11ea-8c86-3cfefcbe73d0.png)

**Comment by KorGgenT** [comment]
cannot reproduce - even when i don't have space for the saline it drops to the floor in its bottle.
![image](https://user-images.githubusercontent.com/30208401/82745766-054e7e80-9d56-11ea-9e2c-4fb28abe5a38.png)
