### ISSUE TITLE
"Israel" is misspelled "Isreal"

### ISSUE THREAD

**Issue by MichaelMacha** [CleverRaven/Cataclysm-DDA#40461]
A number of NPCs, presumably with the name Israel, have it mis-spelled "Isreal", as in, "Is ... real", which is incorrect.

This is purely a spelling correction.

# Steps To Reproduce

# Expected behavior

Characters should have properly spelled names.

# Screenshots

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: LinuxMint; Description: Linux Mint 19 Tara; Release: 19; Codename: tara; 
- Game Version: 0.E-1180-g4a5feda [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    C.R.I.T Expansion Mod [crt_expansion],
    Aftershock [aftershock],
    Mythical Martial Arts [MMA],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

**Comment by kevingranade** [comment]
It is spelled correctly.

**Comment by anothersimulacrum** [comment]
There is both `Israel` and `Isreal` as a name in the list.
