### ISSUE TITLE
Rust Zombies

### ISSUE THREAD

**Issue by CrankyUnicorn** [CleverRaven/Cataclysm-DDA#40488]
I propose a lineage of Ferrous Zombies, starting with the lowest in tier called Rust Zombie.

----
Rust Zombie is a first tier zombie.

"A zombie impaled with a multitude of metal fragments that are covered with a thick layer of rust that seams to propagate to other parts of the body."

This zombie have resistance to slash and piercing but is sloppy on is melee attacks. May cause Tetanus Disease on a Critical Attack. Tetanus Status must be healed with an Anti-Tetanus shot.

----
Rust Plated is the second tier

"A slow moving statue of a zombie covered with a scaly layer of rust. Each step clangs with the sound of metal"

This zombie is hard to damage with bludgeoning, slashing and piercing weapons but is rather slow. It haves advantage when breaking doors and windows. This monster attacks may cause Tetanus Disease. 

----
Rust Urchin Zombie is a second tier zombie

"A spiked horror of a zombie covered in 3 foot long rusty spikes. It will damage unharmed attackers or have a chance to damage any weapon that is not metal."

This zombie is a bit slow and haves resistance against unharmed and bludgeoning attacks. It will reflect unharmed damage back to the attacker and will damage non metal weaponry. This monster attacks may cause Tetanus Disease. 

----
Rust Fist Brute is a Third Tier Zombie

"This monstrosity is covered in patches of rust. His arms long and strong drag fists that are nothing more then great balls of rust. On closer look bits of chain drop from his wrists, lucky it doesn't seam to be very perceptive." 

This Zombie is a bit slow and almost as perceptive as a brainless zombie but can destroy walls like a hulk. A punch can send the attacker flying. This monster attacks may cause Tetanus Disease. 

----
Siren Zombie Second Tier Zombie 

"This monstrosity head is a ball of rust, his torso deprived of arms and covered in heavy rust , his lips extend to form a cone of rusty material. A constant Siren wails amasses a multitude of other zombies around him."

Just a but hard to crit since. It doesn't attack with melee attacks but will daze and deafen the attacker.

----
Rust Shelled Crawler is a First Tear Zombie

"This mangled body seams to developed a rusty spiked shell in his back."

It s almost impossible to crit and have defensive advantage in any melee damage against him but moves very slowly. This monster attacks may cause Tetanus Disease. 
----
Engine Zombie ??? tier

"A monstrous revived corpse seams to be a victim of a motorcycle or chainsaw accident. A layer of rust spreads from the engine."

The engine may starts with a hit and make something impressible like blow up in flames, jump to life and damage the player or simply rip the zombie apart. This monster attacks may cause Tetanus Disease.

**Comment by ymber** [comment]
Ages ago someone suggested a zombie type that had fused with metal dust and stuff to spawn in steelworks. I never could find the proposal again but I like these kinds of zombie concepts.

**Comment by RickyVanz** [comment]
Siren Zombie..

currently there is a popular creepypasta on the internet about a creature called "Siren Head"

would love to see that in-game.

**Comment by DillonSimeone** [comment]
>The engine may starts with a hit and make something impressible like blow up in flames, jump to life and damage the player or simply rip the zombie apart.

HAH, I like this!

What about zombies fused to cars? Mobile Fortress zombies?

**Comment by CrankyUnicorn** [comment]
To DillonSimeone: That's a great idea and that reminds me that maybe it would be fun create a list of car related monsters/zombies.

The first tier would be the "Driver Zombie". A zombie that as maybe a taxi driver or other car aficionado, so much so that it would still have the habit of getting inside cars and sit behind the wheel. This is supper annoying specially if you trying to steal a car and find that you have to kill this zombie first. Also this zombie will hook the horn if it sees you. 
The evolved form would probably be able to run cars against stuff or open the hood and mess up you vehicle... I don't know got to reflect more about it

**Comment by CrankyUnicorn** [comment]
Also there a lot of horror movies about cars that are sapiens and start to kill people like https://en.wikipedia.org/wiki/Christine_(novel) and others

See also
    "Killdozer!", 1944 science fiction novella written by Theodore Sturgeon
    "Sally", a 1953 short story by Isaac Asimov
    "You Drive", a 1964 episode of the original The Twilight Zone series
    My Mother the Car, the 1965-6 sitcom about a spirit-possessed (but well-meaning) car
    The Love Bug, motion picture (1968) and its numerous sequels and spinoffs about Herbie the benevolent sentient Volkswagen
    ""Trucks"", a 1973 short story by Stephen King, featuring homicidal sentient trucks
    The Car, a 1977 horror film about a killer car
    The Twilight Zone: Season 2, Episode 15 "Joy Ride", aired 21 May 1987
    "Alice", a 1999 episode of Star Trek: Voyager about a shuttlecraft with its own artificial intelligence
    Futurama: Season 2, Episode 18 "The Honking" (2000)
    From a Buick 8 (2002), another novel by Stephen King about a mysterious car
    Black Cadillac, a 2003 film about a car that stalks its victims relentlessly
    "Route 666", a 2006 episode of Supernatural about a possessed truck
