### ISSUE TITLE
Make the window that is showing up dont disappear when i choose an option.

### ISSUE THREAD

**Issue by rafaelkb** [CleverRaven/Cataclysm-DDA#40482]
Some examples: 

The wear item window (W). When i wear an item the window closes making me open it again when i want to wear multiple clothes.

The Consume item window (E) closes after i consume one item. I need to re-open it several times if i want to consume multiple items.

And in the consume window when i want to consume a Bandage, the mini-window that lets you choose wich part of the body you want to apply the bandage to closes every time that i use it, forcing me to re-open the Consume window and then choose to consume  the bandage again to apply it to multiple limbs.

The solution would be keep the window open after the player choose an option.

**Comment by molkero** [comment]
If someone chooses to implement this behavior, please also remove the `Never mind.` spam to log, as it (in my opinion) offers no useful information to the player.
