### ISSUE TITLE
UNLOCK DOOR keeps showing even when you already have unlocked it

### ISSUE THREAD

**Issue by CrankyUnicorn** [CleverRaven/Cataclysm-DDA#40486]
When you UNLOCK a door via a Terminal Console it keeps the console open and with the option to UNLOCK the door... its kind of a small detail.

About Consoles,  when you get shocked it should show an damage animation or something more obvious...

**Comment by Night-Pryanik** [comment]
It's a limitation of current implementation. The console doesn't keep track of doors it's opened. On `unlock doors` action all locked doors are simply converted into unlocked ones.
