### ISSUE TITLE
M249 Crows turret returns fire farther than it can see at night

### ISSUE THREAD

**Issue by soggylithe** [CleverRaven/Cataclysm-DDA#40496]
# Describe the bug

Shining a light on a turret at night lets you shoot at them from outside of their nightvision range but they they also shoot back into the darkness at you. 

I reproduced this using military helipad turrets.

# Steps To Reproduce

1. Find military helipad at night
2. Light up turret and stand outside "Hostile Detected" range
3. Fire weapon of choice at turret. (Throwing does not trigger)
4. If the shot hits pray you don't get hit by return fire.

# Expected behavior

The turrets cant see where the player is so should not be able to target them to return fire. 

Also if there is some justification for them being able to return fire then they should do it any time they detect they are being shot at and not only when they are actually hit.

# Screenshots

![Pre fire](https://user-images.githubusercontent.com/3830480/81741540-590ebd00-9464-11ea-9447-6ebc2bd6bfca.png)
![Post fire](https://user-images.githubusercontent.com/3830480/81741534-58762680-9464-11ea-84f7-c59ce0148efa.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2037-g2abca8f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by MechaJeb** [comment]
Both image links show "Non-Image content-type returned"

**Comment by soggylithe** [comment]
Yep just saw that Ty

**Comment by Night-Pryanik** [comment]
> The turrets cant see where the player is so should not be able to target them to return fire.

This is a wrong assumption. Their return-fire is a blind fire, turrets return-fire based on sound, not on visibility.

**Comment by Zireael07** [comment]
@Night-Pryanik: Do we have an in-game snippet/note saying that turrets shoot based on sound? It might help with that confusion...

**Comment by Night-Pryanik** [comment]
> Do we have an in-game snippet/note saying that turrets shoot based on sound?

AFAIK no.

**Comment by latogato** [comment]
I'm sure a message state that shots are blind responses.
