### ISSUE TITLE
'drop all' when carrying containers of liquid will drop the liquids first, then the emptied containers.

### ISSUE THREAD

**Issue by Wolfechu** [CleverRaven/Cataclysm-DDA#40498]
See title. Specifically when dropping using d or D <direction>, then hitting comma <,> to drop all non-favorited items. 

A sub-bug of this: also appears to happen with sealed jars of food (e.g. a glass jar of jam will also dump the jam first, then the jar), although the empty jars remain sealed after being dropped. There doesn't seem to be any obvious way to repurpose an empty sealed jar, either - it can't be opened or refilled.

Expected behavior: Liquids probably shouldn't be treated as a droppable item except through the unload command.

Version: Experimental 10654

**Comment by morthein** [comment]
This is pretty annoying at first, an easy work around is just to "D"rop all, use the category select option, and drop the containers first. What's left in the "food" category are the things that are not in containers.

**Comment by mutability** [comment]
More generally, contained liquids (which are now listed in addition to the container) should not be trivially droppable. Dropping the contained liquid is almost never what's wanted, and it's too easy to accidentally drop the liquid and not the container right now.

Could turn dropping a liquid into the usual `u`nload-to-where? query, or filter out contained liquids from the drop selection entirely.

AIM has a similar problem where it's easy to accidentally move the raw liquid, not the container.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-10953.
