### ISSUE TITLE
An option to not auto pickup in hands (wield form ground)

### ISSUE THREAD

**Issue by TheMrBakit** [CleverRaven/Cataclysm-DDA#40497]
# Is your feature request related to a problem? Please describe.
When i play, i alway set my auto pickup with some items, but when you want to play unarmed (whitout a weapon) you have to drop the wielded item each time.
# Describe the solution you'd like
I'd like an option in the settings/options menu like "do not auto pickup in hands (wield)"
# Describe alternatives you've considered
toggle off the auto pickup.

**Comment by CoroNaut** [comment]
1. Hit ESC
2. Action menu...
3. Combat...
4. Select Martial Arts Style
5. Keep hands free (on) is what you want

**Comment by TheMrBakit** [comment]
I thought that option was a martial art by itself. Thanks @CoroNaut
