### ISSUE TITLE
food/drink containers spawning with odd amounts in them

### ISSUE THREAD

**Issue by Wolfechu** [CleverRaven/Cataclysm-DDA#40499]
Examples: Gallon jugs of milk seem to only spawn with a single 'serving' of milk, rather than 15.

As another example, a 3L jar of jam in my inventory has 87 servings, rather than the 15 a full jar usually has.

Expected behavior: While you could argue that it'd be fine if containers were less than full when found - I imagine most of us have a less-than-full bottle of milk in the fridge right now -, I don't think this was the intended result, and certainly not several times the maximum amount the container was able to hold.

Version: 10654

**Comment by KorGgenT** [comment]
there are at least 2 open issues that are the same as this one
