### ISSUE TITLE
Cannot use the finger lighter CBM to fire a smoking rack

### ISSUE THREAD

**Issue by TheDarkMaster13** [CleverRaven/Cataclysm-DDA#40500]
# Describe the bug

The finger lighter CBM is not a valid fire source to fire a smoking rack.

# Steps To Reproduce

1. Spawn a character with the finger lighter CBM and bionic power.
2. Setup a smoking rack.
3. Make sure your character is not carrying any other fire sources than their finger lighter CBM.
4. Attempt to fire the smoking rack.

# Expected behavior

The finger lighter CBM should qualify as a valid fire source to fire a smoking rack.

#Version and OS

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Generic Guns [generic_guns],
    No Fungal Monsters [No_Fungi]
]

**Comment by nexusmrsep** [comment]
Could not reproduce. With enough bionic power bionic available lighter lights up the smoking rack with no problem.

**Comment by MasterLiKhao** [comment]
Might require another issue to be opened, but Finger Lighter CBM cannot be used to light candles / molotov cocktails.

**Comment by sam0jones0** [comment]
> 
> 
> Might require another issue to be opened, but Finger Lighter CBM cannot be used to light candles / molotov cocktails.

+1 here, can't use finger lighter to light candle. Should I make a separate bug or no?

**Comment by MilosRasic** [comment]
I've encountered a problem where game will refuse to use Finger Lighter CBM to light a new candle or fire up the smoking rack if there is a lit candle in inventory with 0 charges left. If I drop the 0-charge lit candle, it works fine.

@TheDarkMaster13 @MasterLiKhao @sam0jones0 maybe you're running into the same problem?

**Comment by int-ua** [comment]
Please either open a new issue or update the description.
