### ISSUE TITLE
Trying to (E)at with fuel for an installed CBM in range causes a crash.

### ISSUE THREAD

**Issue by cthuloid9** [CleverRaven/Cataclysm-DDA#40512]
# Describe the bug

Attempting to (E)at with valid fuel in range for a CBM you have installed causes a crash. Unloading the container and using "fuel bionic" option from that menu works, though.

# Steps To Reproduce

1.) Have/install a CBM that accepts some form of fuel.
2.) (E)at with a valid fuel for that CBM in range (in inventory, or on an adjacent tile).
3.) Crash.

# Expected behavior

Expected attempting to (E)at to bring up the (E)at menu.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-2124-g6b93842 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by homebass** [comment]
Can confirm that this is an issue. Happens with the Battery System CBM, making it impossible to charge properly.

**Comment by Ramza13** [comment]
There's a good chance this is related to #40160 or #40177.  I'll take a look at it later today.
