### ISSUE TITLE
ATM bug

### ISSUE THREAD

**Issue by buildfailedforallplatforms** [CleverRaven/Cataclysm-DDA#40515]
Withdrawing money from an ATM to a cash card wipes all money, deposting works fine.

Also adding an ingame wallet container would be a good alternative and way of storing cash cards, id cards, etc.

**Comment by ZhilkinSerg** [comment]
Probably z duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/40125

**Comment by KorGgenT** [comment]
it is a duplicate, and i happen to have run across this bug and fixed it in the linked pr
