### ISSUE TITLE
Sudden error, not sure what causes it

### ISSUE THREAD

**Issue by RafeHaab** [CleverRaven/Cataclysm-DDA#40528]
The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 0.E-1404-g1268e85
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

  #0
    (dbghelp: @0x6436f6[cataclysm-tiles.exe+0x2436f6]), 
    (libbacktrace: Z21debug_write_backtraceRSo+0x56@0x6436f6),
    (libbacktrace: 0x6436f6    [unknown src]:0    [unknown func]),
  #1
    (dbghelp: @0x6273ff[cataclysm-tiles.exe+0x2273ff]), 
    (libbacktrace: log_crash+0x4af@0x6273ff),
    (libbacktrace: 0x6273ff    [unknown src]:0    [unknown func]),
  #2
    (dbghelp: @0x6280d2[cataclysm-tiles.exe+0x2280d2]), 
    (libbacktrace: signal_handler+0x32@0x6280d2),
    (libbacktrace: 0x6280d2    [unknown src]:0    [unknown func]),
  #3
    (dbghelp: SMPEG_error+0x4b034@0x1085bc0[cataclysm-tiles.exe+0xc85bc0]), 
    (libbacktrace: gnu_exception_handler+0x70@0x1085bc0),
    (libbacktrace: 0x1085bc0    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crt_handler.c:223    _gnu_exception_handler),
  #4
    (dbghelp: _C_specific_handler+0x8c@0x77397388[ntdll.dll+0x57388]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #5
    (dbghelp: _chkstk+0x9d@0x773abf7d[ntdll.dll+0x6bf7d]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #6
    (dbghelp: RtlInitializeResource+0x53a@0x7738043a[ntdll.dll+0x4043a]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #7
    (dbghelp: KiUserExceptionDispatcher+0x2e@0x773ab61e[ntdll.dll+0x6b61e]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #8
    (dbghelp: @0x9d083a[cataclysm-tiles.exe+0x5d083a]), 
    (libbacktrace: ZN3map18remove_submap_campERK8tripoint+0xa@0x9d083a),
    (libbacktrace: 0x9d083a    [unknown src]:0    [unknown func]),
  #9
    (dbghelp: @0x6d1cd1[cataclysm-tiles.exe+0x2d1cd1]), 
    (libbacktrace: ZN8basecamp12abandon_campEv+0x241@0x6d1cd1),
    (libbacktrace: 0x6d1cd1    [unknown src]:0    [unknown func]),
  #10
    (dbghelp: @0xc68258[cataclysm-tiles.exe+0x868258]), 
    (libbacktrace: ZN13talk_function12abandon_campER3npc+0x48@0xc68258),
    (libbacktrace: 0xc68258    [unknown src]:0    [unknown func]),
  #11
    (dbghelp: @0xc47625[cataclysm-tiles.exe+0x847625]), 
    (libbacktrace: ZNK13talk_effect_t5applyER8dialogue+0x45@0xc47625),
    (libbacktrace: 0xc47625    [unknown src]:0    [unknown func]),
  #12
    (dbghelp: @0xc60558[cataclysm-tiles.exe+0x860558]), 
    (libbacktrace: ZN8dialogue3optER15dialogue_windowRK10talk_topic+0x788@0xc60558),
    (libbacktrace: 0xc60558    [unknown src]:0    [unknown func]),
  #13
    (dbghelp: @0xc6138a[cataclysm-tiles.exe+0x86138a]), 
    (libbacktrace: ZN3npc9talk_to_uEbb+0x82a@0xc6138a),
    (libbacktrace: 0xc6138a    [unknown src]:0    [unknown func]),
  #14
    (dbghelp: @0xc6540f[cataclysm-tiles.exe+0x86540f]), 
    (libbacktrace: ZN4game4chatEv+0xbef@0xc6540f),
    (libbacktrace: 0xc6540f    [unknown src]:0    [unknown func]),
  #15
    (dbghelp: @0x798749[cataclysm-tiles.exe+0x398749]), 
    (libbacktrace: ZN4game13handle_actionEv+0x1329@0x798749),
    (libbacktrace: 0x798749    [unknown src]:0    [unknown func]),
  #16
    (dbghelp: @0x76e01f[cataclysm-tiles.exe+0x36e01f]), 
    (libbacktrace: ZN4game7do_turnEv+0xc5f@0x76e01f),
    (libbacktrace: 0x76e01f    [unknown src]:0    [unknown func]),
  #17
    (dbghelp: IMG_LoadWEBP_RW+0x6a1918@0x1819348[cataclysm-tiles.exe+0x1419348]), 
    (libbacktrace: main+0x10f8@0x1819348),
    (libbacktrace: 0x1819348    [unknown src]:0    [unknown func]),
  #18
    (dbghelp: @0x4013ed[cataclysm-tiles.exe+0x13ed]), 
    (libbacktrace: _tmainCRTStartup+0x23d@0x4013ed),
    (libbacktrace: 0x4013ed    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crtexe.c:336    __tmainCRTStartup),
  #19
    (dbghelp: @0x4014fb[cataclysm-tiles.exe+0x14fb]), 
    (libbacktrace: WinMainCRTStartup+0x1b@0x4014fb),
    (libbacktrace: 0x4014fb    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crtexe.c:186    WinMainCRTStartup),
  #20
    (dbghelp: BaseThreadInitThunk+0xd@0x772359cd[kernel32.dll+0x159cd]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #21
    (dbghelp: RtlUserThreadStart+0x1d@0x7739385d[ntdll.dll+0x5385d]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4623045/crash.log)

**Comment by aoae23** [comment]
Could you try reproducing it?

**Comment by DarkendTheMighty** [comment]
I believe I have something similar to this.
The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 0.E-2203-g30952d6
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

  #0
    (dbghelp: @0x64f366[cataclysm-tiles.exe+0x24f366]), 
    (libbacktrace: Z21debug_write_backtraceRSo+0x56@0x64f366),
    (libbacktrace: 0x64f366    [unknown src]:0    [unknown func]),
  #1
    (dbghelp: @0x630c9f[cataclysm-tiles.exe+0x230c9f]), 
    (libbacktrace: log_crash+0x4af@0x630c9f),
    (libbacktrace: 0x630c9f    [unknown src]:0    [unknown func]),
  #2
    (dbghelp: @0x631972[cataclysm-tiles.exe+0x231972]), 
    (libbacktrace: signal_handler+0x32@0x631972),
    (libbacktrace: 0x631972    [unknown src]:0    [unknown func]),
  #3
    (dbghelp: SMPEG_error+0x4b034@0x10b0ac0[cataclysm-tiles.exe+0xcb0ac0]), 
    (libbacktrace: gnu_exception_handler+0x70@0x10b0ac0),
    (libbacktrace: 0x10b0ac0    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crt_handler.c:223    _gnu_exception_handler),
  #4
    (dbghelp: _C_specific_handler+0x98@0x7fffecbc8068[msvcrt.dll+0x28068]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #5
    (dbghelp: _chkstk+0x11f@0x7fffef95479f[ntdll.dll+0xa479f]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #6
    (dbghelp: RtlWalkFrameChain+0x14bf@0x7fffef8b4bef[ntdll.dll+0x4bef]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #7
    (dbghelp: KiUserExceptionDispatcher+0x2e@0x7fffef95350e[ntdll.dll+0xa350e]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #8
    (dbghelp: IMG_LoadWEBP_RW+0x262482@0x1404db2[cataclysm-tiles.exe+0x1004db2]), 
    (libbacktrace: ZN18wish_item_callback6selectEP6uilist+0x12@0x1404db2),
    (libbacktrace: 0x1404db2    [unknown src]:0    [unknown func]),
  #9
    (dbghelp: @0xf143b9[cataclysm-tiles.exe+0xb143b9]), 
    (libbacktrace: ZN6uilist10filterlistEv+0x399@0xf143b9),
    (libbacktrace: 0xf143b9    [unknown src]:0    [unknown func]),
  #10
    (dbghelp: @0xf14742[cataclysm-tiles.exe+0xb14742]), 
    (libbacktrace: ZN6uilist11inputfilterEv+0x332@0xf14742),
    (libbacktrace: 0xf14742    [unknown src]:0    [unknown func]),
  #11
    (dbghelp: @0xf14eaf[cataclysm-tiles.exe+0xb14eaf]), 
    (libbacktrace: ZN6uilist5queryEbi+0x64f@0xf14eaf),
    (libbacktrace: 0xf14eaf    [unknown src]:0    [unknown func]),
  #12
    (dbghelp: @0xfef128[cataclysm-tiles.exe+0xbef128]), 
    (libbacktrace: ZN10debug_menu8wishitemEP6playerRK8tripoint+0x308@0xfef128),
    (libbacktrace: 0xfef128    [unknown src]:0    [unknown func]),
  #13
    (dbghelp: @0xff0776[cataclysm-tiles.exe+0xbf0776]), 
    (libbacktrace: ZN10debug_menu8wishitemEP6player+0x26@0xff0776),
    (libbacktrace: 0xff0776    [unknown src]:0    [unknown func]),
  #14
    (dbghelp: @0x664f6f[cataclysm-tiles.exe+0x264f6f]), 
    (libbacktrace: ZN10debug_menu5debugEv+0x64cf@0x664f6f),
    (libbacktrace: 0x664f6f    [unknown src]:0    [unknown func]),
  #15
    (dbghelp: @0x7abafd[cataclysm-tiles.exe+0x3abafd]), 
    (libbacktrace: ZN4game13handle_actionEv+0x32bd@0x7abafd),
    (libbacktrace: 0x7abafd    [unknown src]:0    [unknown func]),
  #16
    (dbghelp: @0x77388f[cataclysm-tiles.exe+0x37388f]), 
    (libbacktrace: ZN4game7do_turnEv+0xc5f@0x77388f),
    (libbacktrace: 0x77388f    [unknown src]:0    [unknown func]),
  #17
    (dbghelp: IMG_LoadWEBP_RW+0x6b4ce8@0x1857618[cataclysm-tiles.exe+0x1457618]), 
    (libbacktrace: main+0x11a8@0x1857618),
    (libbacktrace: 0x1857618    [unknown src]:0    [unknown func]),
  #18
    (dbghelp: @0x4013ed[cataclysm-tiles.exe+0x13ed]), 
    (libbacktrace: _tmainCRTStartup+0x23d@0x4013ed),
    (libbacktrace: 0x4013ed    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crtexe.c:336    __tmainCRTStartup),
  #19
    (dbghelp: @0x4014fb[cataclysm-tiles.exe+0x14fb]), 
    (libbacktrace: WinMainCRTStartup+0x1b@0x4014fb),
    (libbacktrace: 0x4014fb    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crtexe.c:186    WinMainCRTStartup),
  #20
    (dbghelp: BaseThreadInitThunk+0x14@0x7fffecdb7974[KERNEL32.DLL+0x17974]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #21
    (dbghelp: RtlUserThreadStart+0x21@0x7fffef91a271[ntdll.dll+0x6a271]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),

**Comment by anothersimulacrum** [comment]
@DarkendTheMighty You have a separate issue, your game is crashing in the wish menu, theirs appears to be abandoning a basecamp.

**Comment by DarkendTheMighty** [comment]
> 
> 
> @DarkendTheMighty You have a separate issue, your game is crashing in the wish menu, theirs appears to be abandoning a basecamp.

Ah, my bad. Ignore me then. I just searched my issue and this looked similar, plus it was relatively recent.

**Comment by int-ua** [comment]
It looks similar because it doesn't have any details. @RafeHaab did you remove the issue template when creating this issue or was it opened without an issue template? Can you still reproduce this?
