### ISSUE TITLE
To have a more flavoured start as an option.

### ISSUE THREAD

**Issue by CrankyUnicorn** [CleverRaven/Cataclysm-DDA#40529]
Would be nice in some scenarios to have the option to start with a bunch of NPCs around the PC players character.

Imagine your PC starts in a mall or in the center of an highly populated zone it would make sense if this is the start of the cataclysm to have some other non NPC victims around, specially useful to distract the zombies and monsters.

This NPC would not give a fight at least most of them. Different behaviors would be nice but not essential, the importance would be more in the story telling then in other thing. 

Would be nice to have this NPC turn into zombies if left unattended for a long period.

I suggest that the number of let call them "Victim" NPCs would be a fraction of 1:10 to 1:20 of the surrounding zombies.

It would be nice also to have this Victims appear in first appearances of a new monster to demonstrate the danger of some high lever monster. That or have them pop sometimes just to have some flavor. Also if you save some of them would be nice to have them give you some info and then go their way or join your camp.

**Comment by Ramza13** [comment]
Take a look at #37869 and maybe comment there

**Comment by ZhilkinSerg** [comment]
You already can create a scenario with start location set to a overmap terrain which spawn multiple NPCs (see refugee center for example).

**Comment by CrankyUnicorn** [comment]
Hum... ZhilkinSerg it's not the same thing... Is like saying a butter knife and a cleaver are the same thing... yes both are knives but they are different in shape and purpose and not to be confused

**Comment by ZhilkinSerg** [comment]
> 
> 
> Hum... ZhilkinSerg it's not the same thing... Is like saying a butter knife and a cleaver are the same thing... yes both are knives but they are different in shape and purpose and not to be confused

You want to implement a thing to allow something which already can be achieved by some other means.

**Comment by CrankyUnicorn** [comment]
Let me ask you a question: Here can I do that in game?

**Comment by mrkybe** [comment]
> > Hum... ZhilkinSerg it's not the same thing... Is like saying a butter knife and a cleaver are the same thing... yes both are knives but they are different in shape and purpose and not to be confused
> 
> You want to implement a thing to allow something which already can be achieved by some other means.

I think what he's talking about is more like, NPCs that aren't full on 'survivors'.  NPCs that are essentially doomed to die and have simplistic AI that ultimately gets them killed on purpose.  Then you could do something like a "Besieged Evac Shelter" start, where there's dozens of NPCs in there with you, but because they aren't all survivors, they still get rekt by even basic zombies.  So in the scenario, the doors would break open, and even though the horde outside would be massive and completely inescapable for a single player, the target rich environment would distract enough of the horde that you can escape.

**Comment by ZhilkinSerg** [comment]
> 
> 
> Let me ask you a question: Where can I do that in game?

You do development and modding outside of the game.

**Comment by ZhilkinSerg** [comment]
> 
> 
> > > Hum... ZhilkinSerg it's not the same thing... Is like saying a butter knife and a cleaver are the same thing... yes both are knives but they are different in shape and purpose and not to be confused
> > 
> > 
> > You want to implement a thing to allow something which already can be achieved by some other means.
> 
> I think what he's talking about is more like, NPCs that aren't full on 'survivors'. NPCs that are essentially doomed to die and have simplistic AI that ultimately gets them killed on purpose. Then you could do something like a "Besieged Evac Shelter" start, where there's dozens of NPCs in there with you, but because they aren't all survivors, they still get rekt by even basic zombies. So in the scenario, the doors would break open, and even though the horde outside would be massive and completely inescapable for a single player, the target rich environment would distract enough of the horde that you can escape.
> 
> Although, maybe this is already do-able with the normal NPCs?

I am pretty sure it should be possible to spawn a bunch of weak NPCs.

**Comment by CrankyUnicorn** [comment]
I thin MrKybe explained it better then me.
