### ISSUE TITLE
Quiver item info display shows no storage and does not show that it can store arrows

### ISSUE THREAD

**Issue by Nadario** [CleverRaven/Cataclysm-DDA#40521]
# Describe the bug

Quivers have one pocket with 0.00 storage max size and weight.
They also cannot be activated to store arrows.
When looking at arrows it says "can be stored in: bow sling, back holster, hiking backpack, and golf bag" with no mention of quivers.

# Steps To Reproduce
Craft a quiver and try to store arrows.

# Expected behavior

You will be unable to store the arrows.

# Screenshots
![quiver](https://user-images.githubusercontent.com/65289503/81812534-8fad0c00-9526-11ea-8c50-e8d4ba732b75.png)
![arrow](https://user-images.githubusercontent.com/65289503/81812542-92a7fc80-9526-11ea-98d3-42482ace38eb.png)

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-2125-g7d04bfa
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: 
 -->Dark Days Ahead
-Disable NPCs Needs
-SpeedyDex
-Stats Through Skills
-sees-player icon, retrodays
-Fuji's Military Proffesion Pack
-MSX Indicator: REMIX
-Zetsukaze's Hair - O.E EDIT

**Comment by KorGgenT** [comment]
you don't activate them - you either put things in them automatically with the best pocket algorithm or you can `i`nsert. the 0.0 storage is a display thing that i probably need to remove as this has been reported as a bug multiple times now.

**Comment by Nadario** [comment]
> 
> 
> you don't activate them - you either put things in them automatically with the best pocket algorithm or you can `i`nsert. the 0.0 storage is a display thing that i probably need to remove as this has been reported as a bug multiple times now.

I tried to use insert while having the arrows in the inventory and I could not put them in the quiver, same when they are on the ground. It worked with best pocket when I tried to pick up just 20, but not when i I tried with 100.
Also the description of the quiver should be changed as it says "Activate to store arrows.".

**Comment by wapcaplet** [comment]
I have an idea of how to fix this - I think it affects any item using `ammo_restriction` to define what it can hold, since the size of that ammo will determine the container's total capacity.

However, it only works when the pocket type is `MAGAZINE`. The quivers have `ammo_restriction` but are not `MAGAZINE` type. I'll try patching this in the JSON data and open a PR if it works out.
