### ISSUE TITLE
Dubug issues

### ISSUE THREAD

**Issue by patwiz74** [CleverRaven/Cataclysm-DDA#40525]
Dubug options worked, then after updating and experimenting with cbm's, Debug Intallation, and Debug carry weight no longer work

src/mutation.cpp:132 [void Character::toggle_trait(const trait_id&)] my_traits and my_mutations were out of sync for DEBUG_STORAGE
09:35:11.582 ERROR : src/mutation.cpp:132 [void Character::toggle_trait(const trait_id&)] my_traits and my_mutations were out of sync for DEBUG_BIONICS

Same with vinilla game or modded.

08:46:38.919 : Starting log.
08:46:38.919 INFO : Cataclysm DDA version 0.E-2131-g3ac02c5
08:46:38.935 INFO : [main] C locale set to C
08:46:38.935 INFO : [main] C++ locale set to C
08:46:38.935 INFO : SDL version used during compile is 2.0.5
08:46:38.935 INFO : SDL version used during linking and in runtime is 2.0.5
08:46:39.192 INFO : Number of render drivers on your system: 4
08:46:39.192 INFO : Render driver: 0/direct3d
08:46:39.192 INFO : Render driver: 1/direct3d11
08:46:39.192 INFO : Render driver: 2/opengl
08:46:39.192 INFO : Render driver: 3/software
08:46:39.200 INFO : [options] C locale set to C
08:46:39.200 INFO : [options] C++ locale set to C
08:46:39.209 INFO : Active renderer: 0/direct3d
08:46:39.545 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
08:46:40.847 INFO : Language is set to: 'en'
08:46:40.847 INFO : [translations] C locale set to English_United States.1252
08:46:40.847 INFO : [translations] C++ locale set to C
08:46:41.241 WARNING : opendir [./mods/] failed with "No such file or directory".
08:47:14.203 WARNING : opendir [./save/Cannon Town/mods] failed with "No such file or directory".
08:47:23.362 INFO : Loaded tileset: UNDEAD_PEOPLE
08:50:55.313 ERROR : (error message will follow backtrace)
  #0
    (dbghelp: @0x64fae6[cataclysm-tiles.exe+0x24fae6]), 
    (libbacktrace: Z21debug_write_backtraceRSo+0x56@0x64fae6),
    (libbacktrace: 0x64fae6    [unknown src]:0    [unknown func]),
  #1
    (dbghelp: @0x65057a[cataclysm-tiles.exe+0x25057a]), 
    (libbacktrace: Z8DebugLog10DebugLevel10DebugClass+0x34a@0x65057a),
    (libbacktrace: 0x65057a    [unknown src]:0    [unknown func]),
  #2
    (dbghelp: @0x653b86[cataclysm-tiles.exe+0x253b86]), 
    (libbacktrace: Z12realDebugmsgPKcS0_S0_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x76@0x653b86),
    (libbacktrace: 0x653b86    [unknown src]:0    [unknown func]),
  #3
    (dbghelp: @0xbc6ac6[cataclysm-tiles.exe+0x7c6ac6]), 
    (libbacktrace: ZN9Character12toggle_traitERK9string_idI15mutation_branchE+0x366@0xbc6ac6),
    (libbacktrace: 0xbc6ac6    [unknown src]:0    [unknown func]),
  #4
    (dbghelp: IMG_LoadWEBP_RW+0x266af9@0x1409f09[cataclysm-tiles.exe+0x1009f09]), 
    (libbacktrace: ZN20wish_mutate_callback3keyERK13input_contextRK11input_eventiP6uilist+0x169@0x1409f09),
    (libbacktrace: 0x1409f09    [unknown src]:0    [unknown func]),
  #5
    (dbghelp: @0xf165d4[cataclysm-tiles.exe+0xb165d4]), 
    (libbacktrace: ZN6uilist5queryEbi+0x854@0xf165d4),
    (libbacktrace: 0xf165d4    [unknown src]:0    [unknown func]),
  #6
    (dbghelp: @0xfeb2df[cataclysm-tiles.exe+0xbeb2df]), 
    (libbacktrace: ZN10debug_menu10wishmutateEP6player+0x34f@0xfeb2df),
    (libbacktrace: 0xfeb2df    [unknown src]:0    [unknown func]),
  #7
    (dbghelp: @0x663b1f[cataclysm-tiles.exe+0x263b1f]), 
    (libbacktrace: ZN10debug_menu5debugEv+0x492f@0x663b1f),
    (libbacktrace: 0x663b1f    [unknown src]:0    [unknown func]),
  #8
    (dbghelp: @0x7ac73d[cataclysm-tiles.exe+0x3ac73d]), 
    (libbacktrace: ZN4game13handle_actionEv+0x32bd@0x7ac73d),
    (libbacktrace: 0x7ac73d    [unknown src]:0    [unknown func]),
  #9
    (dbghelp: @0x77e01f[cataclysm-tiles.exe+0x37e01f]), 
    (libbacktrace: ZN4game7do_turnEv+0xc5f@0x77e01f),
    (libbacktrace: 0x77e01f    [unknown src]:0    [unknown func]),
  #10
    (dbghelp: IMG_LoadWEBP_RW+0x6b4808@0x1857c18[cataclysm-tiles.exe+0x1457c18]), 
    (libbacktrace: main+0x11a8@0x1857c18),
    (libbacktrace: 0x1857c18    [unknown src]:0    [unknown func]),
  #11
    (dbghelp: @0x4013ed[cataclysm-tiles.exe+0x13ed]), 
    (libbacktrace: _tmainCRTStartup+0x23d@0x4013ed),
    (libbacktrace: 0x4013ed    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crtexe.c:336    __tmainCRTStartup),
  #12
    (dbghelp: @0x4014fb[cataclysm-tiles.exe+0x14fb]), 
    (libbacktrace: WinMainCRTStartup+0x1b@0x4014fb),
    (libbacktrace: 0x4014fb    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crtexe.c:186    WinMainCRTStartup),
  #13
    (dbghelp: BaseThreadInitThunk+0x14@0x7ffb4cbb3034[KERNEL32.DLL+0x13034]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #14
    (dbghelp: RtlUserThreadStart+0x21@0x7ffb4f523691[ntdll.dll+0x73691]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
Backtrace emission took 1 seconds.
src/mutation.cpp:132 [void Character::toggle_trait(const trait_id&)] my_traits and my_mutations were out of sync for DEBUG_STORAGE
09:35:11.582 ERROR : src/mutation.cpp:132 [void Character::toggle_trait(const trait_id&)] my_traits and my_mutations were out of sync for DEBUG_BIONICS

Sry if wrong way to report first time reporting, TYVM

**Comment by Qrox** [comment]
Please follow the issue template.

**Comment by KorGgenT** [comment]
if this is post nested containers experimental, debug storage does not do anything anymore and could possibly have caused the crash.

**Comment by wapcaplet** [comment]
Cannot reproduce the crash, but the `DEBUG_STORAGE` mutation still exists and should be removed.
