### ISSUE TITLE
Expedient Killing.

### ISSUE THREAD

**Issue by CrankyUnicorn** [CleverRaven/Cataclysm-DDA#40533]
Contrary to what the title says this would make the game harder and not other wise.

Abstract:
"To kill is not in the nature of most men now a days. Things have changed and demand tremendous acts of gore and violence that no one should be required to fulfill.  Adaptation to this new reality will not come easy, the fear and horror that wait us are surmountable, but is essential to keep on fighting.  As we your forefathers learned to adapt to a new world and so do will us also. ...The hunter learn to prey a new game, the soldier to fight against a new enemy and the General to defeat armies with strategy and wit."

Mechanic: 
When your Player Character kill a type of monster for the first time it haves disadvantage in the fight.
It may be necessary for the Player Character to get used to fight each kind of enemy and also sometimes to learn more about it. 

Implementations:
Since the monster type kills is already logged its easy to implement a penalty related to a low number of kills. I would propose less then 10 kills give disadvantage to CRIT or halves the damage.
Also propose the need to make a Dissection/Butchering to understand the critical point of each type of enemy. 
I would propose a TRAIT called "Horror Connoisseur" or "Horror Fan" that would make you not have this disadvantage or have only to kill halve the requested monster to be a Expedient Killer.

**Comment by DillonSimeone** [comment]
This is a neat idea. What about the advantages you get against them, and dissecting them? What happens when you get 1000 kills of a monster? Become effortless to kill them, and dissecting them takes ten minutes?
