### ISSUE TITLE
Optional Player Character Abillity to Identify Monsters 

### ISSUE THREAD

**Issue by CrankyUnicorn** [CleverRaven/Cataclysm-DDA#40530]
The concept may be strange at first but bare with me.

Abstract:
Imagine that you Player Character is experiencing the Cataclysm for the very first time. 
For him everything is new and strange like a "Jamais Vu". 
The identification of what is friend and foe is not clear.  
You observer some strange behavior but do not infer what is wrong until you know what an enemy is or not.

Mechanic:
You will observe "zombies" and "zombie type" as a "human" or "strange human". Until the zombie is close by or attacks you, you can not discern other wise. 
After you kill one or a few you start to get familiarized with them and what their type and abilities.

Requirement:
To have the Zombie title, tile and description changed by several others labels depending on the degree of knowledge.
I proposes four levels: Unknown human or humanoid, strange human or humanoid, zombie or monster, and finally the known zombie with nickname.

It would be interesting to even have the possibility to nickname the zombies but that may reflect an heavy burden on playability.

**Comment by MikuMiddo** [comment]
Good thinking,but we should take the first-personly view of the Character,when you see a strange "human"  walking to you with strange step,dirty and untidy cloths,may have some blood on his  head or head,would you still think his is a strange"human"?
By the way,the nickname.You see a smoke zombie on you screen,may you Character call it "smoker"or"smoky asshole",this name is shown to you,not your Character,may you Character call it "smoke babe" instead,but all you should KNOW is smoke zombie not other nickname.

**Comment by CrankyUnicorn** [comment]
The problem is if the player knows what it is by observation or description the player character knows too. I mean you could META the character but that's for me is kind of strange because even if you want to imagine that you don't know what it is you already know. Look this is more for kicks than anything else because it forces the player to take special care when entering a fight and that is a huge adrenaline kick.

**Comment by kevingranade** [comment]
I'm not opposed, but I'm also not super excited about it.

The concept is that with each game, you can re-experience some of the thrill of discovery of encountering new enemies. Maybe some are extra dangerous, maybe some are particularly bad for certain play styles, but you've essentially introduced a new type of enemy you have to deal with, the "unknown" enemy.

As for meta knowledge, yes the player (not the character) will know that certain types of enemies exist, but they won't know which are which unless they've learned to recognize the enemy on this particular playthrough.

**Comment by CrankyUnicorn** [comment]
I think is something to brew on, never seen the mechanic in any game and that could be something new to bring some interest to the game as an options since I see a lot of people to hate it. But would be a nice challenge to the veterans
