### ISSUE TITLE
Whistle can't be used - "tool doesn't have enough charges"

### ISSUE THREAD

**Issue by AzyWng** [CleverRaven/Cataclysm-DDA#40543]
# Describe the bug

The whistle cannot be used.

# Steps To Reproduce

1. Acquire a whistle. They're commonly found in Evac shelters and in people's homes.
2. Attempt to use the whistle.
3. In the activate menu, the whistle cannot be selected, instead displaying a message saying "This tool doesn't have enough charges". If the whistle is activated by selecting the item and pressing "a", the message "This tool doesn't have enough charges" is displayed, and nothing happens.

# Expected behavior

I expected the whistle to be usable.

# Screenshots
None
# Versions and configuration

    OS: Windows 10
    Game Version: 0.E-1970-g3278b58
    Graphics version: Tiles
    Ingame language: English
    Mods loaded: Dark Days Ahead, Disable NPC Needs, No Rail Stations, Graphical Overmap, No Fungal Monsters

# Additional context

**Comment by hexagonrecursion** [comment]
Can not reproduce. Was this fixed?

**Comment by AzyWng** [comment]
Yes, this issue was fixed. I can't recall when it was, however.

**Comment by anothersimulacrum** [comment]
Probably #41152
