### ISSUE TITLE
Nested Bike Racks causes mounted vehicles to merge permenantly

### ISSUE THREAD

**Issue by Kilarin** [CleverRaven/Cataclysm-DDA#40547]
# Steps To Reproduce

1. Mount a bike rack on the back of a motorcycle or bike.
2. Mount another vehicle to the back of the bike (like a shopping cart)
3. Put 4 bike racks on the back of a car.  
4. Mount the bike with the currently mounted shopping cart to the back of the car
5. Unmount the bike and shopping cart from the car (this may take several tries)
6. Now the shopping cart is no longer detachable from the bike, they have merged into one vehicle permanently.

# Expected behavior
Either the shopping cart should still be dis-mountable from the bike after the bike is dis-mounted from the car, OR, nested mounts should be blocked and the bike should not be allowed to be mounted while it has a shopping cart mounted to it.

# Versions and configuration
 - OS: Xubuntu 18.04
 - Game Version: 0.E
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: Nothing extra

**Comment by kevingranade** [comment]
Simplest fix is to scan the vehicle being mounted for mount points and prohibit mounting if if it finds one.

**Comment by Kilarin** [comment]
Very true, and possibly the most reasonable way to do it.  But I WOULD miss being able to haul my shopping cart around behind my bike. :)
