### ISSUE TITLE
Brain Tanning

### ISSUE THREAD

**Issue by jackknife402** [CleverRaven/Cataclysm-DDA#40548]
# Is your feature request related to a problem? Please describe.
I noticed several people saying their isn't much use for brains. Then I noticed there isn't an option for brain tanning.

# Describe the solution you'd like
A recipe for tanning using brains.

# Describe alternatives you've considered
Do nothing.

# Additional context
Here's a simple link to an article about brain tanning, however the knowledge is extensive so all you need to do is search for other sources if you don't like mine: http://livetheoldway.com/brain-tanning-deer-hides/

**Comment by raithwind** [comment]
#https://github.com/CleverRaven/Cataclysm-DDA/compare/master...raithwind:patch-1

Proposed change to recipe, set brains needed to 1:3 ratio based on a little testing on brain recovery rate vs hide recovery rate. Research shows that most medium to large mammals brains is enough to tan their hide, and this seems to be about the right ratio based on a 10 survival butchery of 10 mooses (meese?).

**Comment by anothersimulacrum** [comment]
Implemented in #41415
