### ISSUE TITLE
Crash when Eat menu is opened in vehicle. Seg Fault

### ISSUE THREAD

**Issue by DillonSimeone** [CleverRaven/Cataclysm-DDA#40557]
# Describe the bug

This bug turned up [here](https://github.com/CleverRaven/Cataclysm-DDA/issues/40506#issuecomment-627948374) in issue #40506. It might have not been related to that issue the whole time!

In my game, when you try to eat inside my vehicle, the game crashes.

The only error message the game gives me in the debug.log at the end seems related to #40122

```
02:30:37.765 ERROR : src/item_contents.cpp:87 [void item_contents::combine(const item_contents&)] error: tried to put an item into a pocket that can't fit into it while loading.  err: No success
```
# Steps To Reproduce

1. Load up my game, ignore all error messages. (Should just be messages about the nano mod I have using legacy damage types, and pockets)
2. Press E inside my car.
3. :thonk:

# Expected behavior

Eat menu opens up, showing me items I can eat.

# Screenshots

![image](https://user-images.githubusercontent.com/21962421/81918575-8013de80-958b-11ea-8e57-12bb37da1d3e.png)

![image](https://user-images.githubusercontent.com/21962421/81918137-f5cb7a80-958a-11ea-95cd-cdc0d48a48a9.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2131-g3ac02c5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    XEAS [XEAS],
    DinoMod [DinoMod],
    Crazy Cataclysm [crazy_cataclysm],
    No Rail Stations [No_Rail_Stations],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Arcana and Magic Items [Arcana],
    Graphical Overmap [Graphical_Overmap],
    Advanced Gear [adv_gear],
    Blaze Industries [blazeindustries]
]

# Additional context

[Palmer Heights.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4627313/Palmer.Heights.zip)
[mods.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4627255/mods.zip)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4627330/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4627332/debug.log)

**Comment by DillonSimeone** [comment]
@KorGgenT Maybe this is another mystery dragon spawned by the nested update? 

I've heard from other people that the pocket error message I get is common and doesn't cause a crash for them, oddly.

**Comment by DillonSimeone** [comment]
This is no longer occurring for me now. Odd. Maybe add the unconfirmed tag to this issue, or just close it?

**Comment by Ramza13** [comment]
Can you still reproduce this?  I just downloaded save and tried with latest version and it didn't crash.  On the off chance it matters I have tiles off while testing.

**Comment by BrettDong** [comment]
Tried to reproduce this in latest `master` branch and it does not crash.
