### ISSUE TITLE
Unresonable Advantage on Some Stairs

### ISSUE THREAD

**Issue by CrankyUnicorn** [CleverRaven/Cataclysm-DDA#40564]
# Describe the bug
While on the stair tile Player Character can hit the creature bellow but never get hit. This also work if Player Character is a Z level bellow and hits creatures on the upper level. Only got hit once by a Jurgonaut but most of the hits were very very light even being bellow his z level. This works in most stair but in some doesn't.
This seam to happen since 0.e until now

**Comment by CrankyUnicorn** [comment]
Once I killed an entire horde give or take more then 100 zombies with this tactic.

**Comment by mrkybe** [comment]
This also works if you're multiple Z levels up, like standing on the roof of a 3 story build, you're able to hit zombies at ground level, while unarmed.

**Comment by matt32106** [comment]
Zombies can't flex their neck so they don't know what attacks them (like when you fire arrows at them at night) and can't hit back in return. (me trying to find some reason not to fix it... :) )

**Comment by Dacendeth** [comment]
Pretty sure this is just the z level vision option auto attack bug that's been around way before 0.E

**Comment by actual-nh** [comment]
Any known pattern in what stairs this does/doesn't work on?
