### ISSUE TITLE
Solder: That's not how it works.

### ISSUE THREAD

**Issue by instrangeland** [CleverRaven/Cataclysm-DDA#40560]
# Is your feature request related to a problem? Please describe.
Nope. It just strikes me as unrealistic when, somehow, with a soldering iron, disassembling a electronic item yields solder. Especially without a specific solder-sucking iron. Anyway, solder is in a pretty hard to use form after you remove it from something, and you generally have to add a flux to use it again, as well as re-forging into a wire again. 

# Describe the solution you'd like
I think that adding a solder-sucker is a bit overkill for this issue. However, making solder that you remove from devices unusable until you do a second step, perhaps with a basic forge? Solder has a low enough melting point to be able to be melted by a fire, so perhaps even have it be a recipe that requires being next to an open flame to re-forge of the solder. 

# Describe alternatives you've considered
Perhaps instead of requiring it to be 'reforged,' we make two types of solder: fluxed (which is the kind you'd find around the world) and unfluxed (which is the kind you'd get from a device you've disassembled.) And then you could only use unfluxed solder if you also had a flux pen.

(Also sorry, I have no idea how to add labels...)

**Comment by ZhilkinSerg** [comment]
[We know](https://github.com/CleverRaven/Cataclysm-DDA/issues/25576). Someone just needs to work on this.

**Comment by instrangeland** [comment]
Is this something I can take over? It would end up mostly being JSON manipulation, right?

**Comment by ZhilkinSerg** [comment]
> 
> 
> Is this something I can take over? It would end up mostly being JSON work, right?

Yes, please take a look if you can do something. This should mostly be json, but also possibly require some new code (to fix returning some items from `using` in `uncraft` recipes).

**Comment by Rivet-the-Zombie** [comment]
We've already got a system to prevent some materials from being returned via un-crafting, like the way that duct tape currently works.

**Comment by Dacendeth** [comment]
Perhaps if you changed getting solder back to getting tin scraps back to be used in recrafting solder.

**Comment by RoyBerube** [comment]
Manufactured solder has a flux core surrounded by the solder. I can't see this being crafted by someone without specialized manufacturing equipment. Instead, player crafted solder would realistically be the lead/tin solder by itself and the flux as another needed material when soldering.

On a related note - welding should really use welding rods. With different rods for acetylene and arc welding. And player crafted would need to add a flux coating. Not as complex to manufacture as solder as it is just a coating on an inflexible rod.

**Comment by kevingranade** [comment]
Yes I want all of those things in the game.

**Comment by Rivet-the-Zombie** [comment]
>Manufactured solder has a flux core surrounded by the solder.

Not all manufactured solder is flux-core; a lot of it actually works like this:

>Instead, player crafted solder would realistically be the lead/tin solder by itself and the flux as another needed material when soldering.

So yeah, that would totally work.

**Comment by Night-Pryanik** [comment]
Closing as duplicate.
