### ISSUE TITLE
Found something weird in the code, probably a mistake but not sure

### ISSUE THREAD

**Issue by martinrhan** [CleverRaven/Cataclysm-DDA#40575]
# Describe the bug
When reading the code I found that in activity_handler.cpp the function
```
void activity_handlers::start_fire_do_turn( player_activity *act, player *p )
```
has its begining lines of code very strange, perhaps a fault:
```
    if( !g->m.is_flammable( act->placement ) ) {
        try_fuel_fire( *act, *p, true );
        if( !g->m.is_flammable( act->placement ) ) {
            p->add_msg_if_player( m_info, _( "There's nothing to light there." ) );
            p->cancel_activity();
            return;
        }
    }
```

# Steps To Reproduce
N/A

# Expected behavior
Maybe it should be like this?
```
    if (g->m.is_flammable(act->placement)) {
        try_fuel_fire(*act, *p, true);
    }
    else {
        p->add_msg_if_player(m_info, _("There's nothing to light there."));
        p->cancel_activity();
        return;
    }
```

# Screenshots
N/A

# Versions and configuration
N/A
  
# Additional context
N/A

**Comment by martinrhan** [comment]
if alright, i am going to make a pull request

**Comment by jbytheway** [comment]
It looks reasonable to me: if there are no flammable materials, then try to provide some.  If there are still none, then fail.  What about it seems wrong to you?

(I haven't examined the code in more detail to determine whether that's *actually* what's happening, but it's my first impression from that extract.)

**Comment by martinrhan** [comment]
> It looks reasonable to me: if there are no flammable materials, then try to provide some. If there are still none, then fail. What about it seems wrong to you?
> 
> (I haven't examined the code in more detail to determine whether that's _actually_ what's happening, but it's my first impression from that extract.)

I understood the code after posting this, that 's why I just closed this.
