### ISSUE TITLE
0.E save file not loading

### ISSUE THREAD

**Issue by Esllen** [CleverRaven/Cataclysm-DDA#40579]
# Describe the bug

The bug appears to be a memory leak that prevents the game from loading my save file, loading in perpetuity, and eventually taking the entire memory of my computer, resulting in having to terminate the program.

# Steps To Reproduce

1. Launch game and load world + character file
2. Game boots, mod list boots
3. Reaches loading save file window and remains there.

# Expected behavior

I expected the game to load my save correctly, I suppose?

# Screenshots

Screenshot would just be the loading screen, not very helpful

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: DarkDaysAhead, DisableNPCNeeds, C.R.I.T.ExpansionMod, Magiclysm, DinoMod, AlternativeMapKey, StatsThroughKills, StatsThroughSkills

# Additional context

Prior to the issue I'm having now, I had three error reports that tried to resolve before the program iced itself. Those three appeared to be corrupted map data, and after purging those files at the advice of the Discord channel, those error messages disappeared, but the soft crash still happens. The version of my save file here is prior to clipping those out.

[Schuchk.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4632365/Schuchk.zip)

**Comment by MechaJeb** [comment]
This doesn't solve the issue, but I managed to get it to load by deleting some more of the map, folder -14.16.0 and file -14.16-4/-442.519.-4.map.  Nice car :3

**Comment by DillonSimeone** [comment]
Yep, I got his save working. Deleted the majority of the map folders in the unstable version, and managed to push it through into the world.

Then I deleted everything inside the save folder, then quicksaved ingame to fill that folder back up. Added the modlist from a copy of the old save, zipped that sucker up and sent it to him.

It didn't work with his game even when he updated to my current build... Oddly, me zipping up my whole game folder and sending that to him resolved the issue!

**Comment by ZhilkinSerg** [comment]
Debug messages should appear (or go into `debug.log`) when loading the game similar to this one:

```
 DEBUG    : Failed to read from "./save/Schuchk/maps/-14.16.-4/-442.519.-4.map": line 1:513: invalid character inside string

oad_tie","t_railroad_rubble","t_railroad_track","t_railroad_track_on_tie",["t_railroad_track",2],"t_railroad_track_on_tie",["t_railroad_track",2],"t_railroad_track_on_tie",["t_railroad_track",2],"t_railroad_track_on_tie","t_railroad_track","

 FUNCTION : read_from_file
 FILE     : C:\Projects\Cataclysm-DDA\src\cata_utility.cpp
 LINE     : 434

```
If you look into the file mentioned you will see a lot of NUL characters inside. That means you had some disk failure (either software or hardware) during the save.

There are multiple files affected by the issue:

![image](https://user-images.githubusercontent.com/16213433/82022732-cf463600-9695-11ea-8a08-19a349a3d2ef.png)

There is little we can do here, but I suggest checking your machine hardware (RAM and disk drive) and software (OS and drivers). Also make sure to do regular backups of your save game.

You can restore loading of the game by deleting affected files from the screenshots (you will lose some map cells and some saved options).
