### ISSUE TITLE
Lab computers displaying the same research log on each hacks

### ISSUE THREAD

**Issue by DillonSimeone** [CleverRaven/Cataclysm-DDA#40577]
# Describe the bug

When you're hacking lab computers to read the research logs, you'll get the same log on each hacks. 

# Steps To Reproduce

1. Break into a lab.
2. Find a working computer in lab.
3. Hack the research log over and over, noting that you're getting the same log each time.

# Expected behavior

Different logs are shown at random.

I know about the other logs because that was how it used to be a long time ago, with your odd of failure going up the more you hacked to get at the deeper logs. 

# Screenshots

![image](https://user-images.githubusercontent.com/21962421/82006133-f4965e00-961b-11ea-925a-76afc31cc6cb.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2131-g3ac02c5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    XEAS [XEAS],
    DinoMod [DinoMod],
    Crazy Cataclysm [crazy_cataclysm],
    No Rail Stations [No_Rail_Stations],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Arcana and Magic Items [Arcana],
    Graphical Overmap [Graphical_Overmap],
    Advanced Gear [adv_gear],
    Blaze Industries [blazeindustries]
]

# Additional context

**Comment by Qrox** [comment]
For some reason the random engine used in `snippet_library::random_from_category` returns the same value for different seed values.
