### ISSUE TITLE
Recharging station should recharge foldable vehicles

### ISSUE THREAD

**Issue by colinmarc** [CleverRaven/Cataclysm-DDA#40573]
Game version: 0.E Ellison
Operating system: MacOS
Tiles or curses: Tiles
Mods active: None

I built a sleek, fast and stylish foldable electric scooter, but there's no simple way to charge the storage battery on it. Swappable storage cases aren't FOLDABLE, for instance. Jumper cables would work, but those are a pain and not very satisfying. I thought it would be believable/nice if I could pop it into the recharging station on my larger vehicle (it fits), but it doesn't seem to charge.

A quick glance at the [recharging code](https://github.com/CleverRaven/Cataclysm-DDA/blob/7c650388912249e15937b4af4def2d66c2b0cd62/src/map.cpp#L4393-L4421) makes it seem like this would be a reasonably straightforward addition to call [charge_battery](https://github.com/CleverRaven/Cataclysm-DDA/blob/c60211130594c916ef891c6431689008685f4a1e/src/vehicle.cpp#L4885), at least for someone familiar with the codebase. I'm happy to take a stab at it if this seems like a good idea.

**Comment by colinmarc** [comment]
On the other hand, it looks like folded vehicles are good and [frozen](https://github.com/CleverRaven/Cataclysm-DDA/blob/ecc602c0dd2d91610c81dae0952f0712f607966f/src/vehicle.cpp#L6494), so it might be a bit difficult.

**Comment by MechaJeb** [comment]
I would love if all the things with rechargeable batteries in them would charge when in the recharger, I mean, if the take rechargeable batteries, chances are they have a charger port, right?

**Comment by GGgatherer** [comment]
Would it recharge if you mount it on a bike rack of your larger vehicle?
