### ISSUE TITLE
Take off your mask while eating

### ISSUE THREAD

**Issue by eJ0opb** [CleverRaven/Cataclysm-DDA#40576]
# Is your feature request related to a problem? Please describe.
You can't eat, drink, or smoke while wearing a gas mask or closed helmet.  Not without taking it off or opening it first, giving up protection while you are consuming.  Find environmental safety first, then pop those painkillers.

# Describe the solution you'd like
Make the Eat action automatically take off gear covering the mouth before eating, and put it back on after eating.

# Describe alternatives you've considered
Prevent the player from eating while the mouth is covered.  People will probably complain that this is tedious, so maybe only if the mouth has environmental protection.  Also, NPCs wearing masks might be too dumb to figure out how to drink, so maybe only restrict the player.

# Additional context
There doesn't seem to be a good way to check if a comestible goes through the mouth, the eyes, the skin, or somewhere else, so there probably needs to a property or flags to indicate how the comestible is administered if not through the mouth.

**Comment by Barhandar** [comment]
Modern gasmasks include drinking systems (i.e. a hose with a cap for the bottle to suck fluid in through). Therefore any food in liquid or sufficiently-liquid-to-suck-in state should be edible without taking gasmask off, as well as any medications that can be dissolved or suspended in fluid. But then you need the fluid too.

**Comment by eJ0opb** [comment]
> Modern gasmasks include drinking systems (i.e. a hose with a cap for the bottle to suck fluid in through). Therefore any food in liquid or sufficiently-liquid-to-suck-in state should be edible without taking gasmask off, as well as any medications that can be dissolved or suspended in fluid. But then you need the fluid too.

That's interesting, and I did not know that; however,
* You still can't consume if you don't have the compatible canteen attached
* You still have to prepare the canteen *before* entering environmental dangers.  That may sound like a minor detail, but it is the same reason I put on my seatbelt before I start driving instead of the moment before the crash
* Unless the gear has a drinking apparatus intentionally built into it, it is still true that in general, you generally cannot consume through the mouth while wearing a closed mask or helmet.
