### ISSUE TITLE
Loaded "Flash Light(300/300)" behaving like a open container can only be wield

### ISSUE THREAD

**Issue by CrankyUnicorn** [CleverRaven/Cataclysm-DDA#40583]
Loaded "Flash Light(300/300)" behaving like a open container, can only be wield!!!

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4634113/debug.log)

**Comment by CrankyUnicorn** [comment]
Okey... after this I tried to Unload the flash light and it Crashed with error message.

debug.log was open may not have write permission so I guess it will not show

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4634123/debug.log)

**Comment by CrankyUnicorn** [comment]
was able to replicate the error see #14 instance of log

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4634129/debug.log)

**Comment by SirClarke** [comment]
ya had the same problem

**Comment by scalpelenema** [comment]
same here & it happens with many items. aslo I don't know if it's related but from time to time I get drink/pour/load liquid dialogue when just moving around

**Comment by CrankyUnicorn** [comment]
Ok I tried something new and got no crash. 
1# I dropped the flash light (on or off) and then shortcut to Wield and it gave me the option to Wield the batteries that are inside of the flashlight I did so with no crash.
By the way the flashlight was "(ON 300/300)" while I took the batteries and still "ON" in the description after but produces no light also shows "(ON 0/300)" even without battery.
2# Now I tied to Unload and it didn't crash. 0.0!!!
Now shows flashlight (off) but still can not put it on my inventory rather then wield it.
3# Drop a bunch of items and tried again with the advance inventory to put it in the inventory from the floor but this time it vanished.

Going to exit using Crtl+F4 and reload the game and try again
Can reproduce batteries seams to have unloaded from the flashlight and lost all charge? (0/300)
At least I can put it in the inventory now.

Did a reload again
This time I unload all my items. I the Drop menu a strange error occurs when pressing "," then unselecting an item and then pressing "," again the selection went scrambled. Then got an error message. Going to post this error in a new issue thread after checking this one.

Load again
1# drop everything less the cargo pants. certified that were no items in pants.
2# debug screen create item flashlight (on). created a flashlight(on 300/300)
3# dropped and tried to put in inventory but only could wield it... 
4# wield it
5# unload batteries... didn't crash, flashlight description still says on tile show flashlight (ON) and light still shows, illuminated tiles are shown in scene...
6# dropped the flashlight(on) to floor 
7# try to put it in the inventory... success and no crashes or errors messages still says on.
8# try to turn flash light OFF but cant it says that it needs charge to turn in ON 0.0!? 
9# throws flash light away. indeed is the flash light that is illuminating and not the character
 

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4634291/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4634299/debug.log)

**Comment by wapcaplet** [comment]
I could not reproduce the "behaving like an open container, can only be wielded" issue in 0.E-9737-g511ddcb179.

Any issues produced after Alt+F4 or by debug-spawning an already-on flashlight with no battery may not be valid unless they can also be reproduced during normal gameplay.

However, I can drop a `flashlight (on)` on the ground, then `w`ield the battery from inside it, resulting in an unlit `flashlight (on)` with no battery. This action is not possible when the flashlight is in the inventory. The battery in a flashlight on the ground should not be displayed in the `w`ield menu - this is a bug.

**Comment by Night-Pryanik** [comment]
Can't confirm any of mentioned issues in 0.F-10939.
