### ISSUE TITLE
Certain actions do not scale with stats logically

### ISSUE THREAD

**Issue by Testudo-Cultu** [CleverRaven/Cataclysm-DDA#40584]
# Describe the bug

Throwing, smashing, and wielding do not logically take stats into account for their calculations

# Steps To Reproduce

Create a character, set their stats to anything. In my case I used absurd values, but I also tested at lower values. Throw stuff with different stats, smash stuff with different items and stats, etc.

# Expected behavior

Throwing should be affected by strength enough that a sufficiently bionic (e.g. hydraulic muscles) or mutated person could feasibly throw objects they otherwise couldn't. In my testing, this character is strong enough to smash down a wooden wall in seconds with their hands but cannot throw a child.

Here is a snippet of code showing that dexterity influences attack_cost, while strength does not. While this makes sense to a degree, it neglects strength. When it comes to throwing a bowling ball, being strong will matter.

   `const int base_move_cost = to_throw.attack_time() / 2;`
   ` const int throw_skill = std::min( MAX_SKILL, c.get_skill_level( skill_throw ) );`
   ` ///\EFFECT_THROW increases throwing speed`
  `  const int skill_cost = static_cast<int>( ( base_move_cost * ( 20 - throw_skill ) / 20 ) );`
 `   ///\EFFECT_DEX increases throwing speed`
 `   const int dexbonus = c.get_dex();`
  `  const int encumbrance_penalty = c.encumb( bp_torso ) +`
                              `      ( c.encumb( bp_hand_l ) + c.encumb( bp_hand_r ) ) / 2;`
  `  const float stamina_ratio = static_cast<float>( c.get_stamina() ) / c.get_stamina_max();`
 `   const float stamina_penalty = 1.0 + std::max( ( 0.25f - stamina_ratio ) * 4.0f, 0.0f );`

`    int move_cost = base_move_cost;`
`    // Stamina penalty only affects base/2 and encumbrance parts of the cost`
  `  move_cost += encumbrance_penalty;`
`    move_cost *= stamina_penalty;`
`    move_cost += skill_cost;`
 `   move_cost -= dexbonus;`
`    move_cost *= c.mutation_value( "attackcost_modifier" );`

  `  return std::max( 25, move_cost );`

Here, throw_difficulty is based on the mass of the object, volume of the object, the skill of the player, and the player's strength stat. It neglects dexterity, and since it flatly bases dispersion on the object's mass and the player's strength, it illogically means that the player will be more accurate when throwing anything, including objects that aren't particularly heavy, due to strength and not dexterity.

`  int throw_difficulty = 1000;`
   ` // 1000 penalty for every liter after the first`
   ` // TODO: Except javelin type items`
  `  throw_difficulty += std::max<int>( 0, units::to_milliliter( volume - 1_liter ) );`
 `   // 1 penalty for gram above str*100 grams (at 0 skill)`
`    ///\EFFECT_STR decreases throwing dispersion when throwing heavy objects`
   ` const int weight_in_gram = units::to_gram( weight );`
   ` throw_difficulty += std::max( 0, weight_in_gram - get_str() * 100 );`
``
   ` // Dispersion from difficult throws goes from 100% at lvl 0 to 25% at lvl 10`
  `  ///\EFFECT_THROW increases throwing accuracy`
  `  const int throw_skill = std::min( MAX_SKILL, get_skill_level( skill_throw ) );`
  `  int dispersion = 10 * throw_difficulty / ( 8 * throw_skill + 4 );`
`    // If the target is a creature, it moves around and ruins aim`
`    // TODO: Inform projectile functions if the attacker actually aims for the critter or just the tile`
 `   if( critter != nullptr ) {``
       ` // It's easier to dodge at close range (thrower needs to adjust more)`
      `  // Dodge x10 at point blank, x5 at 1 dist, then flat`
        `float effective_dodge = critter->get_dodge() * std::max( 1, 10 - 5 * rl_dist( pos(),`
                        `        critter->pos() ) );`
       ` dispersion += throw_dispersion_per_dodge( true ) * effective_dodge;`
`    }`

Though it makes sense for strength to help the player accurately throw heavier objects, strength not playing a role in the time does not, and it makes even less sense for throw_difficulty to be unaffected by dexterity when it affects throwing time.

This is going on too long, so I will give much less information on the next issues. Firstly, smashing uses the mass of the object being used into account for stamina calculations, but not the player's strength. Using a heavy object to smash something is just as tiring as it is with 100 strength as it is with 10. Wielding an object takes just as long to do regardless of strength and dexterity as well.

I could go on about the other issues, but this report is long enough. I would create a PR for it myself, but I feel that this is an issue that would be better addressed (or dismissed) by someone with more experience in Cataclysm's development. 

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

While most of the stats I tested with aren't attainable in real gameplay, this still indicates an issue with how stats are factored into certain actions.

**Comment by kevingranade** [comment]
Need a filled out expected results. What items ro you think the character should be able to throw at what strengths?

If you have more elaboration to do on the non-throwing issues, please make them in a new issue, but from what you've said here there is no problem.
"Using a heavy object to smash something is just as tiring as it is with 100 strength as it is with 10" is fine, both because strength 100 is not valid and because increased strength does not reduce fatigue.

In general, if you're testing with stats above 30, that is out of scope for the game.
