### ISSUE TITLE
Liquid Duplication

### ISSUE THREAD

**Issue by Cratelord** [CleverRaven/Cataclysm-DDA#40582]
# Describe the bug

[Green Springs - Copy.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4633698/Green.Springs.-.Copy.zip)

When transferring liquid from one tank to another tank, the liquid can be "transferred" infinitely without consuming anything.

# Steps To Reproduce

1. Obtain two tanks
2. Open advanced inventory
3. Transfer liquid (in this case gasoline) into other tank. 

# Expected behavior

Expected liquid to not be infinite.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2133-g9bb14f6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    XEAS [XEAS],
    No Freeze [no_freeze],
    Mythical Martial Arts [MMA],
    Alternative Map Key [alt_map_key],
    More City Locations [cityside],
    No Rail Stations [No_Rail_Stations],
    Graphical Overmap [Graphical_Overmap],
    Compatible Nimian Manufacture Guns [NM_wpns],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

# Additional context

[Green Springs - Copy.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4633706/Green.Springs.-.Copy.zip)

**Comment by int-ua** [comment]
I cannot reproduce it. Please comment if it's still an issue and improve steps to reproduce.
