### ISSUE TITLE
Eating an item and applying the same item take different amounts of time.

### ISSUE THREAD

**Issue by Dacendeth** [CleverRaven/Cataclysm-DDA#40589]
# Describe the bug
1. Items that can be used in both the apply and eat menu have different times to consume. 
 2. When used through the eat menu Bandages take time to choose where to apply, and more time to actually apply.
3. All or most food item can be inspected and then activated to be consumed in 0 seconds.

# Steps To Reproduce
1. Eat some morphine, and apply some morphine, see that eating takes 5 minutes and applying takes about 6 seconds
2. Eat some bandages and watch the clock jump forward 30 seconds or so before you even apply them.
3. inspect cake, apply cake in 0 seconds.

# Expected behavior
For consuming drugs to not take a crazy amount additional time when used through the eat menu and activating food to not consume it in 0 seconds.

# Screenshots

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2157-gf1e2374 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

**Comment by Zireael07** [comment]
Er, how come bandages still show up in 'E'at menu?

**Comment by Ramza13** [comment]
> Er, how come bandages still show up in 'E'at menu?

Pretty sure it's really the Consume menu so it has everything.

Either way looks like this was an oversight on my part for making consume take time so I'll handle it.
