### ISSUE TITLE
Can't 'e'xamine items in '/' advanced inventory

### ISSUE THREAD

**Issue by lordmatiz** [CleverRaven/Cataclysm-DDA#40592]
# Describe the bug

Some items can't be examined after picking up.

# Steps To Reproduce

1. Start new game (overrun scenario).
2. Grab some items.
3. Try to 'e'xamine them in advanced inventory.
4. On try - some items show detailed info, while others do not.

# Expected behavior

All items show detailed data uppon pressing 'e'.

# Versions and configuration

 - OS: Win8.1
 - Game Version: 0.E-2157-gf1e2374
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: ![image](https://user-images.githubusercontent.com/16430038/82079282-e3645480-96e2-11ea-858b-71756e425118.png)

**Comment by molkero** [comment]
I can `e`xamine all other items in advanced inventory, only items in the `i`nventory tab show either the worn item they are in or some other worn item. They are shown correctly using the `w`orn tab to `e`xamine and `o`pen worn items.

**Comment by KorGgenT** [comment]
#40610
is a related issue and probably a result of the same bug. as such, i'm going to close this one as a duplicate, as that one's reproduction steps were clearer.
