### ISSUE TITLE
Setting up and taking down tents takes no time

### ISSUE THREAD

**Issue by Thonikum** [CleverRaven/Cataclysm-DDA#40599]
# Describe the bug

Setting up and taking down a tent takes no time.

# Steps To Reproduce

1. find a tent (campsite start)
2. examine middle tile to deconstruct
3. notice that no time has passed
4. activate to set it up again
5. repeate step 3

# Expected behavior

I know  that setting up and taking down a tent should take at least some time, due to prior experience with camping and incompetent people.

# Screenshots

setting up:
![before](https://user-images.githubusercontent.com/35609873/82093749-02231500-96fc-11ea-9a73-5992c1b9b4db.jpg)
![after](https://user-images.githubusercontent.com/35609873/82093752-03ecd880-96fc-11ea-8588-4ceb2ef651f9.jpg)

taking down:
![before](https://user-images.githubusercontent.com/35609873/82093010-95f3e180-96fa-11ea-8018-b7d73835a341.jpg)
![after](https://user-images.githubusercontent.com/35609873/82093017-9a1fff00-96fa-11ea-8167-88400e29957f.jpg)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-2157-gf1e2374 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by wapcaplet** [comment]
Still partially reproducible in 0.E-9737-g511ddcb179. Setting up a tent takes 0 time (if you start with the tent being wielded, which  ensures there is no movement cost for picking up the tent or taking it out of your backpack).

Taking down a tent appears to take 2 seconds, but those 2 seconds only pass after pressing `Esc`ape from the pick-up menu that is displayed after the tent is collapsed.

A proper fix would be to make both setting up and taking down into an activity, so it can take a reasonably long time while still being interruptible.
