### ISSUE TITLE
current master does not compile

### ISSUE THREAD

**Issue by KorGgenT** [CleverRaven/Cataclysm-DDA#40602]
# Describe the bug
![image](https://user-images.githubusercontent.com/30208401/82102080-5ddda600-96dc-11ea-835e-8e17eeb938ad.png)

# Steps To Reproduce
Try to compile. I used VS 2019. I made sure to close and reopen VS, and clean and rebuild.

# Versions and configuration
short hash: 96b6e0db59

# Additional context
@Qrox I think it may have something to do with UI adaptor

**Comment by kwl01skz** [comment]
There are a lot of bugs in using mutagen  now.
It does not work where it should work, it works where it should not.
