### ISSUE TITLE
Pistols, Magazines increase volume when loaded, causes problems with professions

### ISSUE THREAD

**Issue by sanfordmadness** [CleverRaven/Cataclysm-DDA#40609]
# Describe the bug

A pistol with ammo and/or a magazine has the combined volume of the ammo/magazine.
Magazines also increase volume when loaded.
This is also true for revolvers.
This also causes a problem where some professions that start with a holstered gun don't get the gun because their guns are too large.

# Steps To Reproduce

The volume glitch:
1. Make a player with a pistol, magazine, and some ammo.
2. Take note of the volume of the pistol
3. Unload the pistol and magazine
4. The combined volume of the pistol, magazine, and ammo is the same

The profession glitch:
1: Start a game with the Bionic Sniper profession
2: They start with an empty holster
3: Edit professions.json to give the Bionic Sniper a usp .45 in an "XL_holster" instead of a "holster"
4: Start a new game with the Bionic Sniper
5: They have a usp .45

# Expected behavior

The pistol and magazine should not increase in volume when loaded.
Professions with holstered pistols should be able to contain those pistols in their holsters

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-2174-g57b3b55 [64-bit]
- Graphics Version: Tiles
- Game Language: English
- Mods loaded: 
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    Stats Through Kills [stats_through_kills]

**Comment by KorGgenT** [comment]
this will need to wait until #40399 to be able to fix, but after that it's all JSON.

**Comment by wapcaplet** [comment]
Tested OK in 0.E-5926-g a883429 by starting a new game with the Bionic Sniper profession. All guns and their ammo were correctly spawned in their holsters:

![image](https://user-images.githubusercontent.com/238395/93533518-55061680-f900-11ea-8e57-08a1ce30c7da.png)

Other professions checked and working fine in #41551 and #41969. Closing issue.
