### ISSUE TITLE
The repeating crossbows, and other crossbows might be in need of a balance rework

### ISSUE THREAD

**Issue by lbnesquik** [CleverRaven/Cataclysm-DDA#40605]
# Describe the bug
This crossbow usefulness is terrible compared to other similar 'tech' weapons in game, for how much you could expect from it and for how much effort you put into getting it.

My defining example, featured in the screenshots, for this is using the [repeating crossbow](https://cddawiki.chezzo.com/cdda_wiki/index.php?title=Repeating_crossbow) and with [simple metal bolts](https://cdda-trunk.chezzo.com/bolt_metal). They have utterly pathetic damage for what is a bolt entering zombies flesh. 
The bolts even bounce on fat zombies, which is pretty ridiculous when pebbles from a bullet crossbow somehow go through.
Especially depressing when the target is just a regular [shady zombie](https://cdda-trunk.chezzo.com/monsters/mon_zombie_shady), yet 3 bolts out of 10 still bounce off harmlessly.

Meanwhile, the bullet crossbow takes no skills to craft, is lighter, smaller, has much more range, has basically infinite and lighter ammo because it is rocks, does consistent damage of around 10 to 16 and has the magical ability to go through fat zombies reliably.

In my opinion, it needs a serious skill decrease or a buff to range, damage and some basic armor piercing to be really considered by anyone. 

# Screenshots

![image](https://user-images.githubusercontent.com/24830358/82106529-e92d5a80-9721-11ea-9c2f-74336fb22986.png)

![image](https://user-images.githubusercontent.com/24830358/82106540-06622900-9722-11ea-9167-fd1d15d4bfc3.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-1477-g8cea0fc [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by kevingranade** [comment]
Yea the bullet crossbow got ignored in the overhaul, it needs a big nerf.

**Comment by dissociativity** [comment]
a bullet crossbow irl isn't meaningfully any more powerful than a sling, it's just for hunting small game, it's not a viable 'weapon', a repeating crossbow is only useful with poison coated bolts on living human people, it's a glorified toothpick launcher with very little strength used by eunuchs, noble ladies and well off farmers for self defense, or assasinations with poisoned bolts.

**Comment by BenlyAZ** [comment]
If the repeating crossbow is intentionally too weak to take down a humanoid target, shouldn't its description mention that instead of just calling it "A custom-made crossbow with a clever mechanism that loads and fires bolts in a single motion"? That description makes it sound like a regular crossbow with added stuff and not a "glorified toothpick launcher".
