### ISSUE TITLE
Jackhammer is too short

### ISSUE THREAD

**Issue by KorGgenT** [CleverRaven/Cataclysm-DDA#40614]
# Describe the bug
![image](https://user-images.githubusercontent.com/30208401/82112265-5092dc80-9719-11ea-9ab2-699f7c385235.png)
I don't know much about jackhammers, but i'm fairly confident in saying that they are longer than 17 cm. It might be wise to look at their volume too.

# Steps To Reproduce
View a jackhammer's item info.

# Expected behavior
Not sure, maybe 2 or 3 feet or something? 

# Versions and configuration
985a5eb25d
Compiled with VS2019

# Additional context

Might be reasonable to do a larger audit, but this is a pretty low-hanging fruit for someone who wants to get their feet wet doing json.

**Comment by DillonSimeone** [comment]
🤔 I also see that the weight is a bit low for a proper jackhammer.

![image](https://user-images.githubusercontent.com/21962421/82112407-790edc80-9701-11ea-8381-6f990dd4486d.png)

**Comment by Nannaquin** [comment]
Having a hard time locating where the length is in the jackhammer entry in its respective json. Is length calculated from volume or something of that nature?

**Comment by KorGgenT** [comment]
it doesn't currently have one, so it's calculated from volume. it needs an override.

**Comment by matt32106** [comment]
Maybe the length should be removed from the UI until it has something relevant to display?! Is the length supposed to be used for some game mechanism BTW? AFAIK only volume and weights count so far.

**Comment by Nannaquin** [comment]
How could I do this override? I searched through the item length pr and files, even added a length attribute but it doesn't seem to change anything. Is it possible this is more than a JSON edit?

**Comment by KorGgenT** [comment]
it's definitely json only. i believe the item example i made in the PR was the pool cue.
