### ISSUE TITLE
'U'nloading jars yields infinite items.

### ISSUE THREAD

**Issue by MechaJeb** [CleverRaven/Cataclysm-DDA#40616]
# Describe the bug

Unloading jars puts their content in your inventory, but does not remove it from the jar.  
Maybe related to this PR #40541 ? Because I haven't noticed this before.  

edit: Not sure how to change the title, but I should specify this applies to jars on the floor, works fine with jars in inventory.

# Steps To Reproduce

Get a jar with, for example, sugar, drop it on the floor, 'U'nload it several times.

# Expected behavior

It should yield only the contents of the jar, and an empty jar.

# Screenshots

![cataclysm-tiles_2020-05-16_12-36-41](https://user-images.githubusercontent.com/47293991/82116514-11917500-9773-11ea-9d32-b389fb867918.png)
![cataclysm-tiles_2020-05-16_12-36-12](https://user-images.githubusercontent.com/47293991/82116515-12c2a200-9773-11ea-97c5-499d9068cb7b.png)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-2181-g985a5eb [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    DinoMod [DinoMod],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    Stats Through Skills [StatsThroughSkills],
    Mining Mod [Mining_Mod],
    No Fungal Monsters [No_Fungi],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion]
]

**Comment by kwl01skz** [comment]
And "Load" will make the item disappear.
Let me guess where is the problem...
