### ISSUE TITLE
Selecting 'Shelter' as a start location can start you in a Vandalized Shelter.

### ISSUE THREAD

**Issue by MechaJeb** [CleverRaven/Cataclysm-DDA#40613]
Selecting 'Shelter' in the menu can start you in a Vandalized Shelter anyway.

# Steps To Reproduce

Start a new game, select Shelter as a start location. not Vandalized Shelter. Sometimes you start in a vandalized shelter anyway.

# Expected behavior

You should start in a Non-vandalized shelter.

# Screenshots

![cataclysm-tiles_2020-05-16_08-23-48](https://user-images.githubusercontent.com/47293991/82111855-83a49280-9750-11ea-8a64-9146204ab209.png)

![cataclysm-tiles_2020-05-16_08-30-45](https://user-images.githubusercontent.com/47293991/82111857-84d5bf80-9750-11ea-8f2d-960f33cede06.png)

# Versions and configuration
OS is Windows 7, not sure why it isn't detecting that.
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-2174-g57b3b55 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    DinoMod [DinoMod],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    Stats Through Skills [StatsThroughSkills],
    Mining Mod [Mining_Mod],
    No Fungal Monsters [No_Fungi],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion]
]

Reference: #39427

**Comment by ZhilkinSerg** [comment]
You need to use `"om_terrain": "fire_station", "om_terrain_match_type": "TYPE"` syntax in `start_locations.json` for `sloc_shelter_vandalized`.

**Comment by Pupsi-Mupsi** [comment]
Can confirm the bug!

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-1404-g1268e85 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    No Fungal Monsters [No_Fungi],
    GP-Mods [gpmod],
    Magiclysm [magiclysm]
]

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/selecting-non-vandalized-shelter-starting-in-vandalized-shelter/23682/2

**Comment by waffel183** [comment]
![image](https://user-images.githubusercontent.com/15922303/82586757-60d30d80-9b98-11ea-888c-7690ffd5c747.png)
I tried with all 3 parameters of "om_terrain_match_type" (CONTAINS, TYPE, PREFIX) and it does not fix the problem, there is still chance to spawn in a vandalized shelter when selecting 'shelter'.

So the problem lies with something else, but I'm not sure where.

**Comment by ZhilkinSerg** [comment]
You need to use different match type for sloc_shelter then.

**Comment by waffel183** [comment]
I tried every match type for both sloc_shelter and sloc_shelter_vandalized. Same results.
Could you tell me the difference between these 3 types? Maybe that will help.

**Comment by ZhilkinSerg** [comment]
> 
> 
> I tried every match type for both sloc_shelter and sloc_shelter_vandalized. Same results.
> Could you tell me the difference between these 3 types? Maybe that will help.

https://github.com/CleverRaven/Cataclysm-DDA/blob/7fcce2cbaf37c67b76ab6ba980346b52f6f0fd91/src/enums.h#L53-L72

***

So, it looks like there is no bug with starting location selection, but normal shelters have vandalized-like used mapgen chunks 50% of the time.

**Comment by ZhilkinSerg** [comment]
#41095
