### ISSUE TITLE
Poisoned effect is way too long (or strong for its duration)

### ISSUE THREAD

**Issue by cirops** [CleverRaven/Cataclysm-DDA#40629]
# Describe the bug

Not sure if related to the recent time changes, but the duration of poison seems way too long. My character became poisoned after tangling with a bloated zombie going down some stairs, and after a few (say, 20 steps) inside the gas field, my head started hurting and I've probably suffered 100 points of damage in the head through 24 hours of "Your head hurts!"

# Steps To Reproduce

1. Head face first into bloated zombie.
2. Stay a relatively short time inside his field (say, 20 seconds).
3. Watch how your character slowly ticks to his death.

# Expected behavior

Either dial down the duration, or decrease the percentage chance of each poison "tick" dealing damage, or leave the damage part to the "badly poisoned" effect and only stat reduction to "poisoned"
# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-1477-g8cea0fc [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

After shallow code-diving, I see that _emit_toxic_leak_ from bloated zombie gives a field intensity of 3, but I couldn't understand exactly where this is processsed, although in **/data/json/field_type.json:365**, the effect _"name": "thick toxic gas"_ applies both _"effect_id": "poison"_ and _"effect_id": "badpoison"_, both of which say "max_duration": "3 minutes", which is definitely less than the 24 hours of poisoning I got. _"badpoison"_ wore off pretty quickly though, so perhaps "poison" is not respecting a cap?

**Comment by Dacendeth** [comment]
Strange that poison gas hurts the head, you'd think it would be harming your torso as it wrecked your lungs or every part of your body as it's just inside you.  Perhaps someone could add breathing in pure oxygen from tanks as that's a real world treatment for toxic gas inhalation.

**Comment by Barhandar** [comment]
IIRC you already can breathe oxygen directly to stave off asthma - in place of an inhaler, or get a temporary buff.

**Comment by morthein** [comment]
When you get poisoned, does it only reset the timer to 3 minutes or does it stack?  
I'm asking because it seems like if i take on poisonous hits in the same limb, it's almost like the poison stacks the 3 minutes PER time/move
Maybe this is wrong, just a thought.
