### ISSUE TITLE
game built at my computer is very slow comparing to released game downloaded from web

### ISSUE THREAD

**Issue by martinrhan** [CleverRaven/Cataclysm-DDA#40622]
# Describe the bug
I have everything prepared, including vcpkg installed and SDL2 library and whatever, but once I try to run the game by pressing the play button in VS, i took  a long time. That building time is till acceptable, but in game, every operation takes a long time to react, and loading a save also take an extremly long time, unlike when I am playing the version downloaded from release website. This is happending despite I run with debug or not.

# Steps To Reproduce
I don't know are other people facing this problem or not, but for me, it is just build and run the game.

# Expected behavior
The game should be as fluent as normal.

# Screenshots
N/A

# Versions and configuration
My project is the updated to the newest master branch, with a little bit of code edited but I don't think this is the reason as I also tryed to build and run a game that i never edit at all.

**Comment by MechaJeb** [comment]
I did not notice any differences last time I compiled it. Try closing VS and then running the compiled game, does that make a difference?

**Comment by ZhilkinSerg** [comment]
You need to build Release instead of Debug configuration.

**Comment by Barhandar** [comment]
As Zhilkin said, downloading source without changes will build it with debug flags enabled which has a lot more debug code (obviously) and hence runs slower.

**Comment by martinrhan** [comment]
OK, this time I build release, then it worked fine.
