### ISSUE TITLE
Corpses below diggable rubble are smashable

### ISSUE THREAD

**Issue by cirops** [CleverRaven/Cataclysm-DDA#40639]
# Describe the bug

If you _s+direction_ try to smash a zombie corpse below wreckage/rubble, it allows you even though you can't see them neither butcher them. 

# Steps To Reproduce

1. Go beside a pile of rubble.
2. Spawn a zombie in that tile.
3. Murder said zombie on that tile.
4. press s+the direction of the pile.
5. Watch how it allows you to smash it.

# Expected behavior

Nothing should be doable to anything below a pile of wreck/rubble, if the idea is that it is inaccessible. An exception could be something really heavy passing over it, or heavy explosives, but that would be beside the point of this issue.

An alternative could be that bodies stay on top of piles if they died after the wreck happened, which would solve the annoying situation of zombies (especially dangerous ones) dying and you having no way of clearing the rubble, so they would eventually revive.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-1477-g8cea0fc [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
After some shallow code-diving, I see that, in **handle_action.cpp:767**, after it tries to smash any furniture/etc, it checks with map if any existing items are in the pointed tile:
```
 for( const auto &maybe_corpse : m.i_at( smashp ) ) { 
```
But i_at() doesn't seem to care if the items on the tile are obstructed by wrecks, so it passes them on to the code below which pulps the corpses. this loop could be made to run if it passes an obstruction check, like in **game.cpp:8284**, butcher checks if the tile is sealed:
```
if( m.has_flag( "SEALED", u.pos() ) ) {
```
So a tentative solution could be:
```
if( !m.has_flag( "SEALED", smashp ) ) {
    for( const auto &maybe_corpse : m.i_at( smashp ) ) {
        if( maybe_corpse.is_corpse() && maybe_corpse.damage() < maybe_corpse.max_damage() &&
            maybe_corpse.get_mtype()->has_flag( MF_REVIVES ) ) {
            // do activity forever. ACT_PULP stops itself
            u.assign_activity( ACT_PULP, calendar::INDEFINITELY_LONG, 0 );
            u.activity.placement = g->m.getabs( smashp );
            return; // don't smash terrain if we've smashed a corpse
        }
    }
}
```
though I don't know enough about the inner workings to say if this works.

**Comment by FuelType-Memes** [comment]
There should be a difference between "under rubble" and "on top"

Plus I think zombies under a pile of rubble should not be able to stand

**Comment by cirops** [comment]
Yeah, that would be one way to go about it, although all this depends on what the game designers envision a "Pile of rubble" or "Wreckage" to be. For instance, it could be a compacted pile of dirt/debris, relatively walkable if you're careful, (which would make it impossible to reach whats buried underneath), or it can be a wrecked mess of bent metal, with jagged pointy stuff as tall as, say, 1.5m. That would be a nightmare to traverse, but corpses scattered in the midst of it would be fairly accessible to pulp.
