### ISSUE TITLE
Eating takes time even if you end up not eating

### ISSUE THREAD

**Issue by DillonSimeone** [CleverRaven/Cataclysm-DDA#40640]
# Describe the bug

~~EDIT: It's the action of taking your foods out of your bags that's moving the time forward, not the game thinking that you've already eaten the foods, or used the first-aids whatever!~~ **???**

If you're engorged, and try to eat something then cancel eating when you're asked if you really want to eat/drink the food/drink, you still spend time eating.

# Steps To Reproduce

1. Spawn in some space cakes and a watch
2. Eat until engorged
3. Check the time
4. Try to eat and cancel when you get the `You're already full and will be forcing yourself...` promo
5. Check the time
6. :thonk:

# Expected behavior

Check if you ate the food before moving the time forward!

# Screenshots

![image](https://user-images.githubusercontent.com/21962421/82136371-2c3f0a80-97c2-11ea-98ee-aa89d3129693.png)
And there! A whole minute just passed without anything happening!
![image](https://user-images.githubusercontent.com/21962421/82136375-382acc80-97c2-11ea-8732-9980d851d0d1.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2191-g152f402 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    XEAS [XEAS],
    DinoMod [DinoMod],
    Crazy Cataclysm [crazy_cataclysm],
    No Rail Stations [No_Rail_Stations],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Arcana and Magic Items [Arcana],
    Graphical Overmap [Graphical_Overmap],
    Advanced Gear [adv_gear],
    Blaze Industries [blazeindustries],
    <color_light_red>Secronom</color> [secronom]
]

# Additional context

**Comment by DillonSimeone** [comment]
I just noticed that this happens with other stuff too.

![image](https://user-images.githubusercontent.com/21962421/82137299-a6c05800-97cb-11ea-921c-f348b9fcd60b.png)
Watch the time...
![image](https://user-images.githubusercontent.com/21962421/82137305-b3dd4700-97cb-11ea-8c06-6d400e12f687.png)
Time moves forwar--

Wait, I think I know why this is happening. It's the action of pulling the item out of bags!

**Comment by DillonSimeone** [comment]
Maybe not? It appears that if you eat foods and stuff off the floor, time gets used up even if you end up not eating/using the item on the floor.

**Comment by MechaJeb** [comment]
Maybe it's the time it takes to pick the food up from the ground, or you assume dude just gets on all fours and slurps it? Try with food already in hand?

**Comment by Ramza13** [comment]
No this is a known issue although the too full case is pretty bad.  Basically you finish eating an item and then it gets "consumed" where some of these checks are happening.  It's partially by design but some of these do need fixing
