### ISSUE TITLE
Sepia Dark Memory filter should be a colder color like Blue

### ISSUE THREAD

**Issue by CrankyUnicorn** [CleverRaven/Cataclysm-DDA#40655]
The new Sepia Dark filter for memory tiles is indeed is a great tuning but I think that a colder/cooler color should be use the represent the memory that or desaturating the color on those tiles.

**Comment by ZhilkinSerg** [comment]
Sepia is not Blue.

**Comment by CrankyUnicorn** [comment]
Yes Sepia it's not blue its "yellowish" tint and I think is not the right color to represent the memory tiles. Specially when sometimes the tile itself is more unsaturated then the tint added by the Sepia filter. I would use the Saturation value and and transform the hue value to the spectrum blue.

**Comment by ZhilkinSerg** [comment]
Add another hardcoded color transformation template then until someone makes this thing configurable through options.

**Comment by CrankyUnicorn** [comment]
This is some options that I found ideal
![image](https://user-images.githubusercontent.com/51274028/82159781-b487e300-9888-11ea-9082-c45f50586b3b.png)

**Comment by CrankyUnicorn** [comment]
![image](https://user-images.githubusercontent.com/51274028/82160041-64aa1b80-988a-11ea-995e-3ba0c0d4117c.png)

**Comment by DillonSimeone** [comment]
I like this. The memory filter should be JSONized. Make it so we could put a .png or something with alpha in a folder to set the filter's color.

**Comment by nexusmrsep** [comment]
Until its json-ized I'd be happy to add blue tint overlay for you. Can you provide rough RGB values for the color you aim for? I'll then try to reproduce it also using the examples provided.

**Comment by CrankyUnicorn** [comment]
Can you point me to the cpp code so I can have an idea how do you implement I tried to find it but had little luck.

if you are picking each pixel and changing it I would transform all the RGB values to the lower one first or sum and div by 3 and then give  5-10% incresse in the B value this will desaturate and then tint ... also if needed decrease all values by percentage or strict value to get the lower to get lower brightness

Example: pixel color value is RBG 240, 54, 87 
Transform pixel color value to be that "A" is the tint of blue 5% of the total scale in this case 12  and "B" the dark tint effect of 2,5% or 6:
 R = (int)(240+54+87)/3-(A/2)-B , 
 G = (int)(240+54+87)/3-(A/2)-B  
 B = (int)(240+54+87)/3+(A)-B, 

a faster process would be to calculate once the average "desaturate" and just use value A on the R and G channel as follows:
M= (int)(240+54+87)
R= M-A:
G= M-A:
B= M: 

...and then clamp values 256<R>-1, 256<B>-1,  256<G>-1
memory RGB more or less 120,120.140

**Comment by CrankyUnicorn** [comment]
you could also instead of full desaturation use one part desaturartion
F = 0,3f;
M = ((R*(1-F)+G*(1-F)+B*(1-F)))/3
MR=(int) R*F + M - Alpha
MG=(int) G*F + M - Alpha
MB=(int) B*F + M


I may have made some mistakes and this is no anyway optimized

**Comment by CrankyUnicorn** [comment]
a really quick fix would be to

const SDL_Color sepia_dark = { 19, 23, 39, color.a};
