### ISSUE TITLE
Cannot stash cans

### ISSUE THREAD

**Issue by Elpyfo** [CleverRaven/Cataclysm-DDA#40658]
# Describe the bug

When attempting to pick up cans, the following message appears:
"Can't stash aluminum can of beer while it's not empty". 
The can in question shouldn't be open. 

# Steps To Reproduce

1. Roll a new character.
2. Loot a house's fridge.
3. Try to grab a can out of the house's fridge. 

# Expected behavior

I expect to be able to grab the can out of the fridge and place it in my backpack by using "e" to examine the fridge, pressing the hotkey for the can and then hitting enter.

# Screenshots

![CanBug1](https://user-images.githubusercontent.com/65512264/82160592-c7a1af80-9896-11ea-83db-1a5d0fe370c4.PNG)
![CanBug2](https://user-images.githubusercontent.com/65512264/82160595-cc666380-9896-11ea-8426-b363b9103e91.PNG)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-2203-g30952d6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Crazy Cataclysm [crazy_cataclysm],
    Cars to Wrecks [cars_to_wrecks],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

Adding a save file with the can of beer in the fridge for your convenience
[Lawton.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4641101/Lawton.zip)

**Comment by Emotions211** [comment]
Related to #40127 

Work around for now is to wield the can and then select a container to (i)nsert it into.

**Comment by Elpyfo** [comment]
> Related to #40127
> 
> Work around for now is to wield the can and then select a container to (i)nsert it into.

Well, that works for now! Is it beneficial to keep this open or should this be closed with the master ticket open?
