### ISSUE TITLE
Siphoning fuel requires hose but ignores leather hose

### ISSUE THREAD

**Issue by nikow** [CleverRaven/Cataclysm-DDA#40654]
# Describe the bug

When i examine vehicle and i want siphon fuel from tanks, game requires hose and ignores leather hose which i already have. When wield Leather hose and use it manually, it works correctly.

# Steps To Reproduce

1. Craft leather hose.
2. 'e'xamine car
3. 's'iphon

# Expected behavior

I except that leather hose will be used as normal hose.

# Screenshots

https://cdn.discordapp.com/attachments/642349261320880128/711651845465964544/unknown.png

# Versions and configuration

20:35:09.628 INFO : Cataclysm DDA version 0.E-2191-g152f4029ed
20:35:09.629 INFO : [main] C locale set to pl_PL.utf8
20:35:09.629 INFO : [main] C++ locale set to pl_PL.utf8
20:35:09.643 INFO : [options] C locale set to pl_PL.utf8
20:35:09.643 INFO : [options] C++ locale set to pl_PL.utf8
20:35:09.899 WARNING : opendir [./mods/] failed with "No such file or directory".
20:35:15.222 WARNING : opendir [./save/Laura/mods] failed with "No such file or directory".

 - OS: Fedora release 31 (Thirty One)
 - Game Version: Cataclysm DDA version 0.E-2191-g152f4029ed
 - Graphics version: Tiles and Terminal
 - Ingame language: English

**Comment by ZhilkinSerg** [comment]
It is hardcoded:

https://github.com/CleverRaven/Cataclysm-DDA/blob/a5cfac0bda21cd18ec1ae6a9eb74a2afb1220ade/src/veh_interact.cpp#L579

**Comment by nikow** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/7e2c59cc86396d3d8950151b78a23df9f1b1b2a5/data/json/items/tool/workshop.json#L1074 

And that's the item. Should i hardcode second item or there is a easy way to check if player has the item with 'use_action': 'SIPHON'? Hardcoding has a plus, because message to player will 'You need a hose or leather hose to siphon liquid' instead of 'You need a siphon able item to siphon liquid'. If hardcoding second item is an option i think i will be able to fix it myself.

**Comment by ZhilkinSerg** [comment]
Hardcoding additional item id is easier and quicker option, but you can also go a little harder way:

- add new `HOSE` item quality;
- assign `SIPHON` item action to it via `usages` node;
- add new `HOSE` quality to all hose-like items;
- remove `SIPHON` item action from item definition (it would be added automatically through `HOSE` quality);
- change code to check `HOSE` item quality instead of hardcoding item id.

**Comment by jbytheway** [comment]
...and you can search items for those with `HOSE` quality to dynamically construct a helpful failure message listing all of them for the player, if that's not considered too spoilerific.
