### ISSUE TITLE
RM 13 combat armor use of nuclear batteries is wrong

### ISSUE THREAD

**Issue by luo-zi** [CleverRaven/Cataclysm-DDA#40669]
# Describe the bug
English：
A plutonium battery,
Putting him in the car will produce 5k of electricity,
When the plutonium battery was placed in the combat armor, the nuclear battery was used directly as a depletion unit, generating only 500 power reserves in the armor, which resulted in the unusually rapid depletion of the plutonium battery and the need for ten plutonium batteries to fill it
But the description of the plutonium battery says that it's not a reactor, it's a special battery that's stabilized with radioactive material,
Therefore, it should have the same effect on the vehicle as on the combat armor
Chinese：
一个钚电池，
将他放入车内使用将会产生5k的电，
当钚电池放入战斗装甲时，直接以消耗单元的方式使用核电池，在装甲内仅产生了500的电力储备，这导致钚电池的消耗异常地快速，并且需要十个钚电池才能填满它
但是钚电池的描述中有提到，钚电池并非是反应堆，而是使用放射性材料稳定的特殊电池，
所以，在车上使用和在战斗装甲上使用，应该是同样的效果

# Steps To Reproduce
1.Put a plutonium cell into RM 13 combat armor
2.500 units of energy were mistakenly provided

# Expected behavior
A plutonium cell should provide RM 13 combat armor with 5k of energy，
There are two reasons for this: it is using up energy too quickly, unlike a large storage battery.
The plutonium battery provided much more energy when used on the vehicle than when used on RM 13 combat armor, and he had no reason for the difference

# Screenshots

# Versions and configuration

# Additional context
At first we thought the onboard reactor was better, allowing it to provide a higher output,well,a wait, look is not is that。
Plutonium batteries use a certain amount of plutonium to stabilise a particular substance (plutonium-244 has no huge power-generating potential, just enough to act as a stable light source), in which the storage of electrical energy is carried out by a nanomaterials, and the amount of electricity released should be the same

**Comment by Rivet-the-Zombie** [comment]
Sounds fine to me.

**Comment by Dacendeth** [comment]
it uses the same plutonium to stored power ratio as an advanced UPS, 1 cell = 500 power. it's not something you're supposed to have on all the time. A full charge of 10 cells lasts about 24 hours which is pretty generous i'd say.

**Comment by Barhandar** [comment]
Why does putting same thing in the vehicle produce 10x the number? If it's supposed to be the same unit, either vehicles need to get 1/10 the energy from it or the armor needs to have ten times the storage and the consumption.

**Comment by luo-zi** [comment]
> 
> 
> it uses the same plutonium to stored power ratio as an advanced UPS, 1 cell = 500 power. it's not something you're supposed to have on all the time. A full charge of 10 cells lasts about 24 hours which is pretty generous i'd say.
Consistency is the reason why I issue this issue, either 500 or 5k (I love this option).

**Comment by Dacendeth** [comment]
Well the thing is the engine being 10x is an aftershock thing im pretty sure, so it's less likely the base game will change for a mod.

**Comment by luo-zi** [comment]
> 
> 
> Well the thing is the engine being 10x is an aftershock thing im pretty sure, so it's less likely the base game will change for a mod.

I try to reduce the consumption of RM13 or increase the energy provided by plutonium fuel cell to RM13. I feel extremely difficult. I think the benefit is far less than the cost, so I plan to close this issue
