### ISSUE TITLE
Pin reamer (reaming lvl 2) required to make workshop toolbox (lvl 1)

### ISSUE THREAD

**Issue by Adomatic** [CleverRaven/Cataclysm-DDA#40667]
# Describe the bug

The only way to make a workshop toolbox includes a pin reamer as one of the consumables. Presumably that's the thing doing the reaming. So why does the toolbox have level 1 and the reamer itself level 2?

Not that anything uses reaming right now. But still.

# Steps To Reproduce

Look at the JSON.

# Expected behavior

The toolbox should inherit the correct level from its components. (Not literally, that sounds like work, but in json.)

# Versions and configuration

Tested on 0.E but per cdda-trunk.chezzo.com this is still an issue for the latest version.

**Comment by Barhandar** [comment]
A work that is already being performed; with container inventory system having a dedicated "solid" toolbox item is unrealistic when it could be toolbox container with tools inside instead.
