### ISSUE TITLE
"Wearing earphones" effect active even after mp3 player is turned off and dropped

### ISSUE THREAD

**Issue by p-dimi** [CleverRaven/Cataclysm-DDA#40671]
# Description:

After turning off mp3 player, the **Wearing earphones** effect is still active. Even after dropping the mp3 player and waiting for an hour, the effect is still active.

# Steps to reproduce:
1. Use mp3 player to listen to some music while reading.
2. When done, turn off mp3 player and drop it.
3. You will still have **Wearing earphones** effect.

# Expected behavior

The **Wearing earphones** effect should go away as soon as the mp3 player is turned off.

# Screenshots

Screenshots below demonstrate character with completely empty inventory, mp3 player dropped on the floor, and still experiencing the effect:

![Screenshot (135)](https://user-images.githubusercontent.com/41579855/82229245-7e02a480-992a-11ea-8ce1-fcdf18f6ab67.png)
![Screenshot (134)](https://user-images.githubusercontent.com/41579855/82229251-8064fe80-992a-11ea-9408-91f2367aa957.png)
![Screenshot (136)](https://user-images.githubusercontent.com/41579855/82229260-81962b80-992a-11ea-924b-0c311b9bd67d.png)

# Versions and configuration:

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2203-g30952d6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Blaze Industries [blazeindustries],
    Graphical Overmap [Graphical_Overmap]
]

# Additional context

Save file (zipped):
[Diffinitum I.0.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4644973/Diffinitum.I.0.zip)

**Comment by p-dimi** [comment]
After looking at the .sav file of the character, the effect duration of the earphones (& of the music) was over 29 thousand turns. Looks like the issue is with how the duration of the "Wearing earphones" effect is calculated / stacked when the mp3 player is being used?

**Comment by cirops** [comment]
Perhaps this is somehow related to what I've noticed in regards to very long "poisoned" times in #40629 ? Both effect_types "poison" and "earphones" in **data/json/effects.json** have no explicit max_duration, which means it defaults to 0 ( no limit), and maybe with recent changes in how turns are processed, some conditions lead the code to stack the effects faster than they decay with time?

**Comment by wapcaplet** [comment]
Sounds (no pun intended) similar to #39155
