### ISSUE TITLE
Hauling Space not lockable anymore?

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#40673]
# Describe the bug

Seems like it lost its "LOCKABLE_CARGO" tag relatively recently (after 0.E or right before it, maybe?). Was it intended or an oversight?

# Steps To Reproduce

Try installing cargo lock on hauling space, see it isn't even in the list of things to install.

# Expected behavior

Kinda can't see why it would be not lockable, it's just a very big container after all.

# Versions and configuration

- OS: Windows 7
- Game Version: 0.E-1477-g8cea0fc [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills],
    Magiclysm [magiclysm]
]

**Comment by anothersimulacrum** [comment]
Both the hauling space and the part it copies from haven't had their flags flags adjusted in months.
3ef243b383e
522b6a81251

**Comment by GGgatherer** [comment]
That's... strange. I have a save made in March when I started in a world with Aftershock, and there's a deathmobile with locked hauling space in that world. It couldn't have been constructed before that so I somehow managed to install lock set on HS in March or April. I wonder how exactly that happened.

**Comment by Pupsi-Mupsi** [comment]
Take a look at #40606. It appears that the hauling space has been completely removed from the game right?

**Comment by anothersimulacrum** [comment]
Yes, but it will still exist on old vehicles.

**Comment by kevingranade** [comment]
Hauling space should not be lockabble as it's a giant open area to store cargo in.  It is not contained at all. Iif you want a cargo space to be secure you need to build vehicle walls around it and lock those
