### ISSUE TITLE
Links are wrong for 0.E-1 Ellison-1 release on cataclysmdda.org

### ISSUE THREAD

**Issue by remyroy** [CleverRaven/Cataclysm-DDA#40697]
# Describe the bug

If you browse to https://cataclysmdda.org/releases/ and you click on one of the 0.E-1 Ellison-1 download links, you will get a Not Found 404 error on GitHub.

# Steps To Reproduce

1. Browse to https://cataclysmdda.org/releases/
2. Click on one of the 0.E-1 Ellison-1 download links
3. Notice the Not Found/404 error

# Expected behavior

When you click on one of the 0.E-1 Ellison-1 download links, your browser should start downloading the game.

# Versions and configuration

Unrelated

# Additional context

The release assets should probably be the ones in https://github.com/CleverRaven/Cataclysm-DDA/releases/0.E-1/ . I'm guessing @ZhilkinSerg will want to be pinged for this.

**Comment by ZhilkinSerg** [comment]
It would be fixed eventually - the site is being rebuilt automatically and last time it happened before release assets were changed.

**Comment by ZhilkinSerg** [comment]
Should be resolved with https://github.com/CleverRaven/Cataclysm-DDA/commit/6c79e7fb41d7aeac567314d189389453900334d7
