### ISSUE TITLE
Activities for practice/self-training

### ISSUE THREAD

**Issue by eJ0opb** [CleverRaven/Cataclysm-DDA#40699]
# Is your feature request related to a problem? Please describe.
Mastering certain skills is tedious, in both the game and real life.  If emulating the tedium of repetitive training isn't one of the objectives of the game, it might be preferable that only the character, but not the player, experiences the tedium of training.

# Describe the solution you'd like
Implement some activities for tedious training activities, e.g. "Swim laps", and "Practice with trap".

# Describe alternatives you've considered
Continue to ignore skills that are too tedious to learn.  This is a legitimate choice most people make in real life.

# Additional context
Tedious practice should probably take the place of most book learning.  Books in real life can give you knowledge that can help you develop skills, but they can't teach you the skills themselves.  This is also not a proposal to auto-train skills that can't be gained in auto-pilot (e.g. melee skills).

With practice activities, it would also be a reasonable possibility *lower* the experience gain from certain activities, mitigating the issue of becoming a master of anything in two weeks.  (If this were possible, why isn't everybody a master of everything?  Why has everybody been wasting their lives up to this point?)  The idea is it becomes only feasible/worthwhile to train a few hours a day over several months.  Also, avoid turning into one of those dumb games where you just click on things and watch numbers go up.

**Comment by kevingranade** [comment]
Redundant with https://github.com/CleverRaven/Cataclysm-DDA/projects/5
