### ISSUE TITLE
SIGFPE when moving all when sorting by category through AIM

### ISSUE THREAD

**Issue by NOTtheMessiah** [CleverRaven/Cataclysm-DDA#40690]
# Describe the bug

When you use `.` to move all while sorting by category in the AIM, the game crashes.

# Steps To Reproduce

1. Drop item on ground
2. Enter Advanced Inventory Manager
3. Sort by category
4. Press `,` to pick up everything

# Versions and configuration

 - OS: Linux
 - Game Version: 0.E experimental commit: 8cc5cbf882b28e6c68d3e42e7c96c5ba3d608c8a
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: dda

# Additional context

VERSION: 0.E
TYPE: Signal
MESSAGE: SIGFPE: Arithmetical error
STACK TRACE:

    cataclysm-tiles(_Z21debug_write_backtraceRSo+0x44) [0x5637cbc30a2a]
    cataclysm-tiles(+0x661432) [0x5637cbc1f432]
    cataclysm-tiles(+0x661699) [0x5637cbc1f699]
    /usr/lib/libc.so.6(+0x3bd70) [0x7fd36f3c3d70]
    cataclysm-tiles(_ZN23advanced_inventory_pane8paginateEm+0x61) [0x5637cbac9ed7]
    cataclysm-tiles(_ZN18advanced_inventory11recalc_paneENS_4sideE+0x40c) [0x5637cbab8176]
    cataclysm-tiles(_ZN18advanced_inventory14move_all_itemsEb+0x1cf) [0x5637cbab83a7]
    cataclysm-tiles(_ZN18advanced_inventory7displayEv+0x441) [0x5637cbab9927]
    cataclysm-tiles(_Z19create_advanced_invv+0x32) [0x5637cbab9e6d]
    cataclysm-tiles(_ZNKSt8functionIFvP15player_activityP6playerEEclES1_S3_+0x25) [0x5637cbaae5af]
    cataclysm-tiles(_ZN15player_activity7do_turnER6player+0x243) [0x5637cc1a15d1]
    cataclysm-tiles(_ZN4game16process_activityEv+0x83) [0x5637cbcd63a7]
    cataclysm-tiles(_ZN4game7do_turnEv+0x527) [0x5637cbd08c3f]
    cataclysm-tiles(main+0x133c) [0x5637cb9c2320]
    /usr/lib/libc.so.6(__libc_start_main+0xf3) [0x7fd36f3af023]
    cataclysm-tiles(_start+0x2e) [0x5637cba5195e]

    Attempting to repeat stack trace using debug symbols…
    debug_write_backtrace(std::ostream&)
    ??:?
    init_crash_handlers()
    ??:?
    init_crash_handlers()
    ??:?
    ??
    ??:0
    advanced_inventory_pane::paginate(unsigned long)
    ??:?
    advanced_inventory::recalc_pane(advanced_inventory::side)
    ??:?
    advanced_inventory::move_all_items(bool)
    ??:?
    advanced_inventory::display()
    ??:?
    create_advanced_inv()
    ??:?
    std::function<void (player_activity*, player*)>::operator()(player_activity*, player*) const
    ??:?
    player_activity::do_turn(player&)
    ??:?Crash when
    game::process_activity()
    ??:?
    game::do_turn()
    ??:?
    main
    ??:?
    __libc_start_main
    ??:?
    _start
    ??:?

**Comment by wapcaplet** [comment]
I could not reproduce this in 0.E-9737-g511ddcb179. Using AIM and sorting by category, the `,` move all function works as expected with no crash or errors.

**Comment by int-ua** [comment]
Please comment if you ever experience it again
