### ISSUE TITLE
Companions bug

### ISSUE THREAD

**Issue by Brytenwalda** [CleverRaven/Cataclysm-DDA#40701]
# Describe the bug

The game can't track companions properly - two additional companions I'd never met popped in the camp menu as available for work assignments. I was able to assign them to jobs, but the option to recover them was unavailable. One of them (or with the exact same name and nickname at least) would spawn when I created a new character (following the first one's death) and would immediately start walking away, unlike other default NPCs. 

EDIT: I followed the NPC, thinking he might be going to the job I assigned him as the previous character but no, he moved to an LMOE shelter about 20 tiles away. 

# Steps To Reproduce

1. Create a camp.
2. Find two NPCs you've never met as available for job assignment. 
3. Character died, one of these NPCs is the first one he meets in the shelter. 

# Expected behavior

Only have your current companions in the camp menu.

# Versions and configuration

0.E-2278-gf8f9f52
Windows 10

**Comment by mrkybe** [comment]
Can you provide the save file?  I think it might be particularly helpful in this case.

**Comment by Brytenwalda** [comment]
Will it work if I already reset the world?
