### ISSUE TITLE
Advance Inventory 'e'xamine will not examine the right item on the inventory 

### ISSUE THREAD

**Issue by CrankyUnicorn** [CleverRaven/Cataclysm-DDA#40703]
Game version: Build #10681

Operating system: Windows7 64

Tiles or curses: Tiles
Mods active: None

### Expected behavior
To be able to 'e'xamine the right item trough the advance inventory. 

### Actual behavior
When 'e'xamine inventory items in the '/' advance inventory the items in the [I] player character inventory will not show when button is pressed or will show some other item.

### Steps to reproduce the behavior
start fresh grab items try the previous point.

###
Since I see that I can examine item that the player character is wearing (not usual in the normal adv. inventory [I]) I guess those items are being added to the array/list/vector ...seams it may be some copied code from the regular 'i'nventory into the adv. inventory.

**Comment by KorGgenT** [comment]
by the description it is not exactly a duplicate but the same code causes this that causes #40610
