### ISSUE TITLE
Clean suit has no head coverage

### ISSUE THREAD

**Issue by p-dimi** [CleverRaven/Cataclysm-DDA#40716]
# Description

The clean suit item has no head coverage

# Steps To Reproduce

1) Spawn clean suit
2) It does not cover the head

# Expected behavior

The clean suit would cover the torso, arms, legs, and head.

# Screenshots

![Screenshot (137)](https://user-images.githubusercontent.com/41579855/82441195-e0c87d00-9a9d-11ea-9e19-e249024565c4.png)
![Screenshot (138)](https://user-images.githubusercontent.com/41579855/82441205-e45c0400-9a9d-11ea-807c-b8c72b281e8d.png)
![Screenshot (140)](https://user-images.githubusercontent.com/41579855/82441222-e9b94e80-9a9d-11ea-97bb-8b93ba0799bb.png)

# Versions and configuration

    OS: Windows
        OS Version: 10.0 1903
    Game Version: 0.E-2203-g30952d6 [64-bit]
    Graphics Version: Tiles
    Game Language: English [en]
    Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    ]

**Comment by Barhandar** [comment]
It has a hood and as far as I can see it was never intended to permanently cover head.

**Comment by p-dimi** [comment]
This only extends to warming the head however, and not to offering environmental protection to it. I see wapcaplet however is addressing this.
