### ISSUE TITLE
No such item group-Miltiary Mapgen Weights

### ISSUE THREAD

**Issue by No-Noise1** [CleverRaven/Cataclysm-DDA#40713]
DEBUG    : Error: line 81:19: no such item group

        { "group": "map_extra_military", "x": 4, "y": 12, "chance": 95 },
        { "group": "map_extra_military", "x": 7, "y": 17, "chance": 95 },
        { "group":
                  ^
                   "map_extra_military", "x": 12, "y": 22, "chance": 95 }
      ],
      "place_fields": [

 FUNCTION : bool main_menu::load_character_tab(bool)
 FILE     : src/main_menu.cpp
 LINE     : 1188

# Describe the bug
Bug occurs on load after update. Prior to this, the game segfaulted out when attempting to remove an item from NPC hands due to consistent issues with nested containers and got error "Item moved on save/load cycle!"

The game doesn't load and stops on world load at mapgen weights with this error.

# Steps To Reproduce
Boot game from Launcher, load save.

# Versions and configuration

# Additional context
This has happened since nested containers were introduced, intermittently. Disabling the Fuji military mod in the launcher fixed it once, but not since. 

Crash: if your problem refers to a crash, please add the following files to the "Additional Context" paragraph:
    - From the /config folder (you can zip them both together):
        - crash.log file.
        - debug.log file.
    - Your save file (zipped)
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4654653/save.zip)

- note #1: you can drag and drop files in this issue post!
- note #2: it is very important for us that you provide a save file in case of a crash. It really helps the developers
    to reproduce the bug and fix it. If possible, try to provide a save file that occurs in the right conditions, just
    before the crash happens. -->
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4654660/save.zip)

**Comment by anothersimulacrum** [comment]
This is due to one of your third party mods, such as Cataclysm++, Secronom, Arcana, Medieval Mod, MST Extra, More Survivor Stuff, or Dorf Life.

We don't have anything to do with this mods, and as such, can't fix it. If you can figure out which mod it's from, I'd contact the mod developer about it.
