### ISSUE TITLE
Collectible maps do not add information to map 

### ISSUE THREAD

**Issue by Rjtheperson** [CleverRaven/Cataclysm-DDA#40724]
# Describe the bug
Maps found through looting do not add information to the overmap when (R)eading or (a)ctivating 

# Steps To Reproduce

1. Find or debug spawn a map
2. Read the map once to get the overview that books get.
3. Read the map a second time which provides a morale boost and passes time.

# Expected behavior
 The map should add information to your overmap such as landmarks, roads or trails. 
# Screenshots
Map before reading Nobleboro trail guide
![image](https://user-images.githubusercontent.com/65632694/82493124-4451ab00-9a9c-11ea-8955-7e23c408e7ed.png)

Map after reading Nobleboro trail guide
![image](https://user-images.githubusercontent.com/65632694/82493190-651a0080-9a9c-11ea-9296-1a160df0076a.png)

# Versions and configuration
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 7 Professional
- Game Version: 0.E-2285-g2647a67 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    Graphical Overmap [Graphical_Overmap],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

 Maps were recently changed to behave similarly to books

**Comment by wapcaplet** [comment]
Confirmed; I can reproduce this with various maps. They take 0 seconds to read, and require having enough morale to read (like books), and furthermore don't do anything - no locations are added to the map.

![image](https://user-images.githubusercontent.com/238395/82616541-b7d1e600-9b8a-11ea-8fea-a51fe160ec76.png)

I tested without the changes from #40634 and maps worked correctly once again. So something about changing the type to `BOOK` caused them to stop behaving as maps.

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Pop!_OS 19.10; Release: 19.10; Codename: eoan; 
- Game Version: 0.E-2320-g7545a5a3ae-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
