### ISSUE TITLE
UPS cant be reloaded in any shape or form

### ISSUE THREAD

**Issue by rafaelkb** [CleverRaven/Cataclysm-DDA#40721]
UPS dont reload, i dont know why but they dont. I think this is a bug since UPS are now useless. Please fix this bug, i want to use my lazergun.

**Comment by Inglonias** [comment]
UPS requires heavy batteries to reload. They don't hold a charge on their own anymore.

**Comment by rafaelkb** [comment]
> UPS requires heavy batteries to reload. They don't hold a charge on their own anymore.

Too bad, i cant reload them as i said before, even with heavy batteries.

**Comment by John-Candlebury** [comment]
Not a bug if you are using the aftershock mod. Since that version has its own integral battery, place it into a recharging station to recover charge.

Please use the bug reporting template in the future, there's no way for us to help you without it.

**Comment by rafaelkb** [comment]
I do have Aftershock but i cant recharge it either

**Comment by KorGgenT** [comment]
use the issue template so it can be fixed properly.
