### ISSUE TITLE
[DinoMod] Dinosaur bodies disappearing after death

### ISSUE THREAD

**Issue by LyleSY** [CleverRaven/Cataclysm-DDA#40728]
# Describe the bug

Dinosaurs with this line in their code:
    "harvest": "mammal_large_leather",
...disappear after death, leaving no corpse at all.

# Steps To Reproduce

1. Spawn a dino with that harvest entry (I used triceratops)
2. Murder it (I used a combat chainsaw)
3. Behold, vanished.

# Expected behavior

Large corpse that can be butchered for tasty remains.

# Screenshots

# Versions and configuration

Most recent experimental on Mac, only DinoMod running, otherwise vanilla

# Additional context

Confirming bug report noted here: https://www.reddit.com/r/cataclysmdda/comments/gmtnvh/dinomod_check_in/fr5yw9e/

**Comment by anothersimulacrum** [comment]
I expect that may be due to corpse size of these monsters. There are no tiles that can hold an item that large.

**Comment by LyleSY** [comment]
Okay, so as a hack I might just make all dinos cap at 4000 L for now. Does that make sense or break another thing?

**Comment by anothersimulacrum** [comment]
Still probably too large.
