### ISSUE TITLE
Folding stocks increase aim speed.

### ISSUE THREAD

**Issue by Dacendeth** [CleverRaven/Cataclysm-DDA#40725]
# Describe the bug
Folding stocks reduce a guns volume with the intent so it can fit in holsters or be smaller in your iventory, but because of how aimspeed is calculated this gives a strange increase to how fast you can shoot the gun.

# Steps To Reproduce
Compare a loaded m4a1 without the stock to a loaded m4a1 with the stock.

# Expected behavior
For something that makes the gun smaller for storage reasons to not make me aim really fast with it.

# Screenshots
![image](https://user-images.githubusercontent.com/26881007/82502085-63643300-9ac4-11ea-8381-c758ccab1e4b.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2278-gf8f9f52 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

**Comment by SirPendrak** [comment]
In past it made some kind of "sense" now that guns are getting real life volume, folding stock should not reduce the volume, and only should reduce lenght of firearm.
