### ISSUE TITLE
"Look around" cursor stuck

### ISSUE THREAD

**Issue by CEHA** [CleverRaven/Cataclysm-DDA#40726]
When i press "x" and try to look around cursor isn't moving.

# Steps To Reproduce

1. Clear all app data. 
2. Start new game:
     When i hold a joystick - character and cursor speed it similar. 
3. Press "Z" one time to zoom out: 
     character speed 2-3 tile per second;
     cursor is not moving when holding but i can do fast sliding and it's move pretty fast.
The same problem is when try change tile w/h similar to zoom out. 

# Versions and configuration

- OS: Android
    - OS Version: Manufacturer: HUAWEI; Model: SLA-L22; Release: 7.0; Incremental: C10B156; 
- Game Version: 0.E-2 [32-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
Default settings - even don't open options menu.

**Comment by Night-Pryanik** [comment]
Can't confirm on latest experimental as of 23 November 2024.
