### ISSUE TITLE
Launcher bug

### ISSUE THREAD

**Issue by buildfailedforallplatforms** [CleverRaven/Cataclysm-DDA#40743]
The latest update available is the previous build, I noticed this for the last couple of builds. Is it just a mislable?
The launcher is upto date.

![Behind launcher](https://user-images.githubusercontent.com/62628815/82633094-a269c400-9c3d-11ea-9519-63599de07e3d.png)

**Comment by Night-Pryanik** [comment]
Launcher is a third-party application.
