### ISSUE TITLE
Moving liquid into vehicle cargos makes it impossible to remove or consume them.

### ISSUE THREAD

**Issue by DillonSimeone** [CleverRaven/Cataclysm-DDA#40746]
# Describe the bug

Turns out that if you drop liquids from your inventory, the liquids gets dropped while the containers stays behind in your inventory. Non-issue until you accidentally drop the liquid into a vehicle cargo space!

# Steps To Reproduce

1. Get bottle filled with liquids.
2. Drop only liquid into a vehicle cargo spot
3. :thonk: as you try to figure out how to get the liquid out of the cargo without uninstalling the cargo

# Expected behavior

The container and the liquid gets dropped. I expect this to be the case with the nested update because `U`nload is still in the game.

# Screenshots

Attempting to move liquid out of cargo onto the ground.
![image](https://user-images.githubusercontent.com/21962421/82656690-08703000-9bd9-11ea-9274-61667c5cba11.png)

Attempting to consume the liquid in the cargo.
![image](https://user-images.githubusercontent.com/21962421/82656714-132ac500-9bd9-11ea-9ee1-47f0957a4b24.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2320-g7545a5a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    XEAS [XEAS],
    DinoMod [DinoMod],
    Crazy Cataclysm [crazy_cataclysm],
    No Rail Stations [No_Rail_Stations],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Arcana and Magic Items [Arcana],
    Graphical Overmap [Graphical_Overmap],
    Advanced Gear [adv_gear],
    Blaze Industries [blazeindustries],
    <color_light_red>Secronom</color> [secronom]
]

# Additional context

**Comment by Cratelord** [comment]
You can use mops to clean them up, since the game treats them as spills

**Comment by DillonSimeone** [comment]
Huh. I figured that mops only worked on liquids on the floor. Mopping up worked on the hauling space/
