### ISSUE TITLE
Damaged minireactor drops 'none' item

### ISSUE THREAD

**Issue by Miner239** [CleverRaven/Cataclysm-DDA#40768]
# Describe the bug

Minireactors have `none` as charge. Thus, `none` is dropped when it is damaged to the point of draining.

# Steps To Reproduce

1. Spawn a vehicle with minireactor
2. Bash the reactor until it drains

# Expected behavior

Drop nothing, or drop plutonium slurry.

# Versions and configuration

Version: 0.E-2382-g48f8edf (tiles)
Mods: dda

**Comment by irwiss** [comment]
Bashing reactor on 593e21a until it leaked produced plutonium slurry
