### ISSUE TITLE
 Disassembling flammable arrow (1/5) yields 5 wooden bodkin arrows

### ISSUE THREAD

**Issue by eJ0opb** [CleverRaven/Cataclysm-DDA#40763]
# Describe the bug

 Disassembling flammable arrow (1/5) yields 5 wooden bodkin arrows.

# Steps To Reproduce

1. Spawn a flammable arrow and bow
2. Activate and shoot 4 of the arrows
3. Get 5 wooden bodkin arrows back

# Expected behavior

Receive only 1 arrow per remaining arrow

# Screenshots

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 10 (buster); Release: 10; Codename: buster; 
- Game Version: 0.E-2278-gf8f9f522dc-dirty [64-bit]
- Graphics Version: Curses
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

Flammable arrows are a hack.  They are implemented as a tool with 5 charges, each producing a flaming arrow.  Presumably the disassemble code knows nothing of this and happily disassembles the flammable arrows "tool" into its recoverable parts.

See also #40761.  Same conceptual problem (disassembling items with nominal count > 1), different implementation failure.

**Comment by int-ua** [comment]
Please just add the full list of arrow types that can be used like this to #40761
