### ISSUE TITLE
 Disassembling one explosive arrow yields components for five

### ISSUE THREAD

**Issue by eJ0opb** [CleverRaven/Cataclysm-DDA#40761]
# Describe the bug

 Disassembling one explosive arrow yields components for five.

# Steps To Reproduce

1. Disassemble an explosive arrow
2. Receive 5 explosive arrowheads and 5 wooden bodkin arrows (regardless of type of arrow originally used in crafting)
3. Those components can be used to craft a set of 5 explosive arrows
4. Repeat for infinite explosive arrows and wooden bodkin arrows

# Expected behavior

Receive only 1 explosive arrow head and arrow (which ever type it was actually made of) per disassembled explosive arrow.

# Screenshots

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 10 (buster); Release: 10; Codename: buster; 
- Game Version: 0.E-2278-gf8f9f522dc-dirty [64-bit]
- Graphics Version: Curses
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

This bug has existed since at least 0.E.

This looks like a problem with the `reversible` recipe property not taking the `count` item property into account.  Also, I'm not sure why explosive arrows need to be crafted in sets of 5.

**Comment by int-ua** [comment]
Confirmed on latest experimental.

**Comment by lancewf** [comment]
Confirmed on master (commit 90f9945d362ce9e423fbc0c94c12ec13f2a66559) on 2021-05-09.
