### ISSUE TITLE
Items of type MAGAZINE cannot be reloaded if ammunition is liquid

### ISSUE THREAD

**Issue by Axema** [CleverRaven/Cataclysm-DDA#40766]
# Describe the bug
Magazines whose contents are intended to be liquid, such as pressurized fuel tanks for flamethrowers, cannot be reloaded. Attempting to reload them will result in the message that you do not have the available ammunition, even if correct ammunition is presently available. This occurs even if the magazine in question is given the proper watertight magazine `pocket_data`.

Airtight magazines, if added, are also affected but behave slightly differently (see below).

# Steps To Reproduce
1. Check that pressurized fuel tanks have appropriate `pocket_data`, it should presently as of https://github.com/CleverRaven/Cataclysm-DDA/pull/40295.
2. Debug spawn in a pressurized fuel tank. Note that it will spawn 
  2b. Alternatively, were you to test this with a magazine containing gaseous ammunition (I do not recall if any exist in vanilla) with the appropriate `airtight` boolean, take note that it will spawn empty instead. This is the only difference in behavior observed thus far.
3. Unload the napalm it spawns with into an available empty container.
4. Attempt to reload the magazine. It will report that no ammunition is available, despite having just unloaded it.

# Expected behavior
The magazine will recognize the presence of available ammunition if properly contained (excluding uncontained/spilt liquids), as magazines do if the expected ammo is solid.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.E-2382-g48f8edf [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
The normal message for failure to load under current functionality is to instead state that the item in question cannot be loaded.

**Comment by KorGgenT** [comment]
the fix is simple: add "watertight" to the pocket.

**Comment by KorGgenT** [comment]
upon further inspection, it already is watertight. did you test this or are you going on hearsay? https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/items/magazine/chemical_spray.json#L19

**Comment by Axema** [comment]
It still does not function, as of my recent test on the said build: https://cdn.discordapp.com/attachments/709600070810730518/713608674823634944/unknown.png

```
"pocket_data": [ { "pocket_type": "MAGAZINE", "ammo_restriction": { "flammable": 500 }, "watertight": true } ]
```

**Comment by KorGgenT** [comment]
![image](https://user-images.githubusercontent.com/30208401/82722520-94e02880-9c95-11ea-8d7d-beef7be27eb4.png)
cannot confirm on latest master.

**Comment by Axema** [comment]
Retested on the next build that was released, current latest available version. This is still present.

￼

From your screenshot, the lack of a secondary container suggests you did not test actually loading a magazine, just spawning one. As already noted in the inital, they correctly spawn fully-loaded, but cannot be reloaded once emptied (or if naturally spawned empty in the world).

Please re-test this and follow the listed steps, ensuring that you have a valid container to unload the fuel tank's contents into to attempt reloading the fuel tank.

**Comment by Axema** [comment]
It seems this was fixed in either build 10689 or 10688, which were not available in releases as of last test.

![Sowwy](https://cdn.discordapp.com/attachments/709600070810730518/713723086377058374/unknown.png)

Apologies for the mistake.
