### ISSUE TITLE
Smoking rack and forge can't be used for crafting anymore

### ISSUE THREAD

**Issue by Lamandus** [CleverRaven/Cataclysm-DDA#40771]
# Describe the bug
My reloadedsmoking rack can't be used for crafting anymore.

# Steps To Reproduce

1. Have reloaded charcoal smoker.
2. Try to cook

# Expected behavior
Cook

# Screenshots
![grafik](https://user-images.githubusercontent.com/33199510/82731079-a57bb780-9d04-11ea-9d6d-ef5a7159b2fb.png)
![grafik](https://user-images.githubusercontent.com/33199510/82731083-add3f280-9d04-11ea-80a4-4be632bc11dd.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2411-g7fcce2c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Graphical Overmap [Graphical_Overmap],
    Fewer Farms [Fewer_Farms]
]

# Additional context

**Comment by Tosscoble** [comment]
I believe that the Rock Forge is in the same. It says on the construction menu that is used as a Charcoal Forge on crafting recipes, but i cant cant craft anything with it.

**Comment by Lamandus** [comment]
> 
> 
> I believe that the Rock Forge is in the same. It says on the construction menu that is used as a Charcoal Forge on crafting recipes, but i cant cant craft anything with it.

Can confirm, also the Forge doesn't work

**Comment by AndrXi** [comment]
As of build 10732 (0.E-2899-g0ff7d77), can confirm that rock forge is still not working.

**Comment by jkoudys** [comment]
Just built on master from 0ff7d773a2344752630a61353cf091454bb849fe . Still no rock forge/smoking rack.

**Comment by bloodraven983** [comment]
at this moment there is no workaround other than cheat and spawn an item substitute for the furniture tool

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/rock-forge-not-elligible-for-making-anvil/23949/2

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/rock-forge-does-not-consume-charcoal/24007/1

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/cant-load-rock-forge-or-clay-kiln-with-charcoal/26711/3
