### ISSUE TITLE
Intermediate zoom level

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#40785]
# Describe the solution you'd like
It would be nice to have an intermediate zoom level between the 20ish and the 40ish squares radius zoom levels. User customisable zoom levels would be the best in the long term I guess, but just adding a 30ish square radius zoom would be a big step (at least for me).

**Comment by Hirmuolio** [comment]
The zoom levels are 0.5x, 1x, 2x, 4x and 8x.

I am not sure where you would want the extra zoom levels. How far these levels allow you to see depend on the size of the used tileset.

3x, 5x, 6x and 7x zooms would probably be easy. Non integer zoom levels would probably look bad without some extra work.
