### ISSUE TITLE
Inhaler has unlimited charges.

### ISSUE THREAD

**Issue by EvgenijM86** [CleverRaven/Cataclysm-DDA#40781]
Inhaler has unlimited charges and charges are not displayed. When asthma attack happens it says that inhaler still has 100 charges left, despite being manually activated 200+ times in a row.

![image](https://user-images.githubusercontent.com/430076/82737728-9f94cf00-9d22-11ea-8055-a9623c9ca698.png)

I am using latest git pull on master branch at the time of writing this.

**Comment by KorGgenT** [comment]
how to fix this: create a new ammotype for the inhaler (albuterol i suppse) and add a magazine pocked to the inhaler that takes albuterol. then remove the "charges" stuff.

**Comment by DillonSimeone** [comment]
I'm now in the process of making a PR that fixes this.
