### ISSUE TITLE
Reload bug

### ISSUE THREAD

**Issue by buildfailedforallplatforms** [CleverRaven/Cataclysm-DDA#40788]
Game spawns gun with no mag. Relaoding gun with mag crashes game

1. Spawn a gun from debug (it has no mag)
2. Spawn a mag in debug
3. Reload gun with mag, it is able to shoot.
4. View gun with mag in 'i'nventory
5. Game crashes

**Comment by anothersimulacrum** [comment]
Please follow the template, it's there for a reason.
Duplicate of #40779
