### ISSUE TITLE
crash or stuck when unequip

### ISSUE THREAD

**Issue by waveyl** [CleverRaven/Cataclysm-DDA#40796]
# Describe the bug

crash or stuck when unequip

# Steps To Reproduce

1.create a survivor.
2.press '+'
3.unequip armors from top to bottom , crash when 'u' winter boots
4.different order leads to different results. In other cases, it may stuck and fan is spinning wildly.

# Expected behavior

return to normal.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.E-2421-g8fc0363 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

[crash+debuglog.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4673442/crash%2Bdebuglog.zip)

**Comment by PlatoSoft** [comment]
Was able to reproduce this. Crashed when reaching the boots, starting on the top.
