### ISSUE TITLE
Segmentation fault when trying to inspect or (e)xamine M4A1

### ISSUE THREAD

**Issue by EirenexTheDragon** [CleverRaven/Cataclysm-DDA#40798]
# Describe the bug
When playing as Military recruit, trying to examine your starter rifle results in a seg fault.

# Steps To Reproduce

1. Start a Safe place scenario, pick Military recruit , location shouldnt matter ( i used hermit shack).
2. press I and select your M4A1.
3. Enjoy Crashmessage 

# Expected behavior
To let me use the Gun as usual

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-2421-g8fc0363 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Tankmod: Revived [Tankmod_Revived],
    Pixel's Various Fuckery [Pix's Shit],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    Faster Stamina Regen [stamina_regen_buff]
]

# Additional context
I can select the Rifle to multidrop it, but when examining it it causes a crash. 

I also tested this without any mods and it still happens. so the mods loaded shouldnt matter. 

[Config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4673555/Config.zip) (debug and crash is inside)

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4673550/save.zip) its a modded one, keep in mind

**Comment by wapcaplet** [comment]
Possible duplicate of #40779

**Comment by EirenexTheDragon** [comment]
I used the latest build so i thought i was up to date already. alright, closing this one for now.
