### ISSUE TITLE
Repeating Crossbow is misleading

### ISSUE THREAD

**Issue by BenlyAZ** [CleverRaven/Cataclysm-DDA#40793]
# Is your feature request related to a problem? Please describe.

A semi-recent argument made clear that the weakness of the repeating crossbow is intentional, with the item based on the zhuge nu and described as a "glorified toothpick launcher". This is fine, but the description calls it "A custom-made crossbow with a clever mechanism that loads and fires bolts in a single motion", leaving out any mention that it is a last-ditch defense weapon and useless for zombie hunting. It also uses standard crossbow bolts, instead of the much smaller (and usually poisoned) darts fired by the zhuge nu.

# Describe the solution you'd like
A more accurate item description and ammunition. The pistol crossbow should probably use the new ammunition as well. Also, since it's a Chinese weapon, the recipe should be in Arms & Armor Of Imperial China instead of Swords Of The Samurai.

# Describe alternatives you've considered
People continuing to complain about the repeating crossbow's ineffectiveness before receiving lectures about the zhuge nu, I guess?

**Comment by Fris0uman** [comment]
It should be pretty easy to fix https://github.com/CleverRaven/Cataclysm-DDA/wiki/Guide-to-adding-new-content-to-CDDA-for-first-time-contributors

**Comment by EvgenijM86** [comment]
Here is a modern repeating crossbow - https://www.youtube.com/watch?v=P2WhUu15B5E&t=19s

270 fps, ~30 joules, 5-6 shots per magazine. It definitely is not a toothpick launcher.

**Comment by BenlyAZ** [comment]
Regardless, it was made clear in a previous issue that the repeating crossbow currently in the game is intended to be a zhuge nu specifically. A modern repeating crossbow with a different recipe would presumably be a new item. This kind of confusion is specifically what I would like to see prevented.

**Comment by Zireael07** [comment]
The description clearly does NOT state it's zhuge nu. From what I remember, it was supposed to be a MODERN thing, not an old fashioned 'toothpick launcher'.

**Comment by BenlyAZ** [comment]
I think you've misunderstood. The problem that the repeating crossbow is too weak relative to its description was raised in issue #40605 and the responses made clear that it is intentionally very weak, and is judged by the standards of the zhuge nu. KG weighed in on the thread and did not seem to think that the fix should be making it stronger. Therefore, the problem is with the in-game description, which should make clear that it is not a modern, useful crossbow.

**Comment by Zireael07** [comment]
In that case, that's a pretty radical change from back when it was introduced, but whatever - it wasn't my contribution. Carry on! ;)

**Comment by EvgenijM86** [comment]
And here is the wooden prototype in case anyone is thinking that it is impossible to be made without a modern factory - https://www.youtube.com/watch?v=drDoHLz1QyI

It lacks the quick reload that was shown in previous video, but I am sure the whole quick-reload mechanism can be recreated with a bunch of scrap metal welded together. It would weight more and have less power than factory produced crossbow, but it would still be more powerful than what we have in the game.

**Comment by BenlyAZ** [comment]
I would absolutely love to see the game implement a high-fabrication modern repeating crossbow, but it's been made clear as far as I can tell that the current repeating crossbow is intended to be the ancient weapon, and will not be "fixed" by making it stronger. Therefore I would at least like to see this confusion eliminated.
Ideally, I would like to see this also lead into the introduction of poisoned bolts and arrows, but that is a much more complicated issue.

**Comment by EvgenijM86** [comment]
Well, if the game is set in the future that means that mechanism that Joerg Sprave have created should become even more popular than it is now. I see no reason why would anyone tried to replicate less efficient Chinese model, when superior design have already been known for many years. Unless you are roleplaying a historical cosplayer who are into Chinese culture I guess.

**Comment by EvgenijM86** [comment]
And the whole sliding magazine was also first made from wood, but for bows - https://youtu.be/URwuU0bRMpU?t=250

So it should be entirely possible to replicate the whole factory model with makeshift welder and wood sawing tools.

**Comment by kevingranade** [comment]
The description block includes damage output, it is not necessary to put every detail of the item in the description itself.  

If you have a specific proposal, make it in a PR, but I'm not going to leave an issue lying around for it as it's not in any way a bug.

**Comment by BenlyAZ** [comment]
Is the "wrong ammo" thing not a valid issue?
