### ISSUE TITLE
Refugee Center Doctor Mission #1 Impossible To Complete 

### ISSUE THREAD

**Issue by gmlacrosse** [CleverRaven/Cataclysm-DDA#40802]
# Describe the bug
1) The mission to get the blood kit sample doesn't work because you can't draw blood with the blood kit. Also it spawns about 10 zombies in the room with the centrafuge making it likely that it or the console will be destroyed by the time you get to it.

# Steps To Reproduce

1) Spawn a new character at the refugee center location
2)Talk to the Doctor to get the mission to analyze zombie blood
3)Use the debug menu to long range teleport to the hospital
4)Use the debug menu to kill all monsters
5)Try to use the blood draw kit the doctor gives you

# Expected behavior

When you stand on or near a zombie corpse and use the blood draw kit. It should be filled with the zombie blood sample.  Zombies should not spawn on top of the mission target.

# Screenshots
![doctor1](https://user-images.githubusercontent.com/3780675/82759297-1d53eb80-9db2-11ea-8177-dd2040a4e79d.png)
![doctor2](https://user-images.githubusercontent.com/3780675/82759298-1f1daf00-9db2-11ea-86ec-0b79a3d80048.png)

# Versions and configuration

 - OS:Windows 10
 - Game Version: 0.E-2203-g30952d6
 - Graphics version: MXotto+
 - Ingame language: English
 - Mods loaded: Dark Days Ahead, Disable NPC needs

**Comment by johnstoecker** [comment]
I can successfully draw zombie blood -- I am unable to reproduce this bug.

For the second part of zombies destroying the centrifuge, I believe the duplicate issue https://github.com/CleverRaven/Cataclysm-DDA/issues/41683 will fix it.

I recommend to close this issue.
