### ISSUE TITLE
Starting Equipment has no charges

### ISSUE THREAD

**Issue by MarceloLaser** [CleverRaven/Cataclysm-DDA#40819]
# Describe the bug

Matchbook and Cellphone of Survivor profession are spawned unloaded, that is, Matchbook 0/20 and Cellphone without battery.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-2450-g2c49679 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Cataclysm++ [Cata++],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food]
]

# Additional context

Have not tested other professions, but I imagine this would happen across the board for similar items.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/items-especially-nonrechargeable-ones-spawning-with-0-charges/23909/2
