### ISSUE TITLE
Can not load Tailor's Kit from floor

### ISSUE THREAD

**Issue by Kurrisum** [CleverRaven/Cataclysm-DDA#40814]
# Describe the bug
Unable to load thread in Tailor's Kit from the floor or adjacent tile
Only able to "reload" from Inventory
Unsure if actually a bug or just the new way of thing

# Steps To Reproduce
1. Have unloaded Tailor's kit
2. Stand near thread, hit reload button,  "Nothing to Reload"
3. Stand on thread, hit reload button, "Nothing to Reload"
4. Pick up thread, hit reload button,  Reload works as normal

# Expected behavior

Previous versions one could load items while adjacent or on top of their "ammo"

# Screenshots
![image](https://user-images.githubusercontent.com/16447312/82768813-eb18ad00-9df6-11ea-957a-b91e03fae152.png)

![image](https://user-images.githubusercontent.com/16447312/82768829-0388c780-9df7-11ea-8847-4d387355fb81.png)

![image](https://user-images.githubusercontent.com/16447312/82768841-18655b00-9df7-11ea-8622-801ea50dccbd.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2411-g7fcce2c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    Mining Mod [Mining_Mod],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]

# Additional context

**Comment by anothersimulacrum** [comment]
Fixed, but not closed, in #40805
