### ISSUE TITLE
Pocket knife cannot be stored in leather belt

### ISSUE THREAD

**Issue by MarceloLaser** [CleverRaven/Cataclysm-DDA#40822]
# Describe the bug

Pocket knife cannot be stored in leather belt pocket, despite being of appropriate length, weight and volume. It can be stored in Windbreaker pocket of same specifications.

# Steps To Reproduce

1. Spawn a pocket knife, leather belt and windbreaker.
2. Attempt to insert pocket knife in leather belt
2a. Should show that inventory is empty (or otherwise not show pocket knife as option)
3. Attempt to insert pocket knife in windbreaker
3a. Works as intended.

# Expected behavior

Pockets of equal specifications should be able to fit identical items.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-2450-g2c49679 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Cataclysm++ [Cata++],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food]
]

**Comment by wapcaplet** [comment]
Although the leather belt has sufficient volume and weight for the pocket knife, the belt pocket is restricted to items with the `BELT_CLIP` flag - which tools like the hammer, crowbar, and folding knife have, but smaller tools like the pocket knife and Swiss Army knife do not.

My guess is that it’s intended to simulate belt storage not being fully a enclosed pocket, but rather being kind of holster or attachment, which tools need to mate with.
