### ISSUE TITLE
Fungal Juggernauts attack Fungal Spire.

### ISSUE THREAD

**Issue by EvgenijM86** [CleverRaven/Cataclysm-DDA#40829]
I was near fungal tower, watching zombie vs mushroom action, and I noticed that Fungal Spire died despite there was almost no zombies near the fungals towers themselves. I reloaded the save to see how it got killed, and this is what I discovered:

![image](https://user-images.githubusercontent.com/430076/82809529-d0d4e280-9e7b-11ea-82a6-6a2f8f446046.png)

I don't know if this is a bug or intended behavior, but I decided to report it just in case.

**Comment by EvgenijM86** [comment]
And it seems that Fungal Juggernauts attack pretty much anything fungal related:

![image](https://user-images.githubusercontent.com/430076/82811037-5f972e80-9e7f-11ea-9d6b-c1c33d9b39ad.png)

At the very least they should avoid killing towers imo. Unless it is intentional that they are hostile to both factions at the same time.

**Comment by GGgatherer** [comment]
Well, regular juggernauts attack mobs that interfere with their movement. Maybe this one was on other side of the spire when you walked into his vision? And then  decided to deal with the obstacle in the only way juggernauts can?

**Comment by EvgenijM86** [comment]
Yes, I checked in the debugger and they attacked those towers simply because they were in the way of whatever the Fungal Juggernaut was trying to reach. I did a pull request above.
