### ISSUE TITLE
Hammerspace crafting gets stuck at 4%

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#40825]
Crafting certain items using hammerspace gets stuck at 4% with a message "You no longer have a none and can't continue crafting".

# Steps To Reproduce

1. debug -> player -> mutate -> Debug Hammerspace
2. flintlock rifle

# Expected behavior

A flintlock rifle is crafted.

# Versions and configuration

- OS: Linux
    - OS Version: Fedora release 32 (Thirty Two)
- Game Version: 0.E-2411-g7fcce2c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

none

**Comment by Fris0uman** [comment]
Debug spawn a none to proceed, also I don't think we track issues linked to debug menu.

**Comment by hexagonrecursion** [comment]
> spawn a none to proceed

I can confirm that the workaround works.

**Comment by KorGgenT** [comment]
Fris is right, debug menu is not supported by the issue tracker (though we may fix bugs with it if it interferes with development)
