### ISSUE TITLE
Cash cards spawn with 0 money

### ISSUE THREAD

**Issue by mft-dev** [CleverRaven/Cataclysm-DDA#40837]
# Describe the bug

Cash cards spawn with 0 charges/money. Presumably because itype_id "money" isn't actually an ammo type, and the game tries to set charges via ammo_set()

# Steps To Reproduce

1. Create a new game
2. Set a break point at line 583 in item.cpp
3. Kill stuff until a monster drops a cash card.
4. Break point triggers
5. Observe that qty is set correctly to a random value
6. Observe that the method exits early for lack of ammo->ammo

# Expected behavior

Cash cards should have cash in them as they normally do. At least some of them.

# Screenshots

![image](https://user-images.githubusercontent.com/566154/82832456-6c397800-9ebb-11ea-8a13-af8a2a365570.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2470-g43652d2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Monsters [No_Fungi]
]

# Additional context

**Comment by kwl01skz** [comment]
Such as lighters, tailor kits

debug automatically generates full items.
And the game automatically creates empty items.

It seems that the default value in json is not recognized correctly.
