### ISSUE TITLE
Properly communicate the effects of leg and foot encumbrance on movement cost to the player

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#40836]
# Describe the bug

On the info > view player info [@] screen in the "encumbrance and warmth" section the game specifically mentions **running** movement point cost for leg and foot encumbrance, but makes no mention of **walking** movement point cost. For example if you have foot encumbrance 30 (fitted turnout boots) it claims that there is a penalty of 15 points to your running movement point cost. This is inconsistent with my observations: both walking and running movement point cost appear to be affected and for running the actual penalty appears to be cut in half and rounded down (7 in my example).

# Steps To Reproduce

1. Take off everything that creates leg or foot encumbrance
2. Wear fitted turnout boots
3. Press @ to open the player info screen
1. Select "encumbrance and warmth"
1. Scroll down to "Feet"
4. Note that the description makes no mention of **walking** movement point cost and claims that there is a penalty of 15 to **running** movement point cost
5. Walk a space
6. Note that the point cost is 115 instead of 100
7. Switch to running
8. Run a space
9. Note that the point cost is 57 instead of 65

# Expected behavior

The effects of leg and foot encumbrance on movement cost should be properly communicated to the player.

# Screenshots

none

# Versions and configuration

- OS: Linux
    - OS Version: Fedora release 32 (Thirty Two)
- Game Version: 0.E-2411-g7fcce2c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

none

**Comment by anothersimulacrum** [comment]
Tiny bit too late: #40784
