### ISSUE TITLE
crash when doing anything

### ISSUE THREAD

**Issue by waveyl** [CleverRaven/Cataclysm-DDA#40830]
# Describe the bug

invalid recipe id “ ”

# Steps To Reproduce

1. enter game.
2. walk, drink, throw or other
3. error report.
4. press space bar to continue
5. crash.

# Screenshots

![2020-05-25 194038](https://user-images.githubusercontent.com/22638873/82809890-b6245d00-9ebf-11ea-822e-2a82be634ae2.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.E-2469-gacc65c6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

[debug+crashlog.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4677021/debug%2Bcrashlog.zip)

**Comment by vvasyliev** [comment]
Reproduced on OS X with latest experimental `acc65c6f9c` with hitting 'r' while having a sewing kit in inventory, also crashes when I try to access the sewing kit.

**Comment by l2evy** [comment]
Reproduced on Windows, Tiles, 0.E-2469-gacc65c6 . Default character start, Any movement causes this error, then a segfault CTD
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4677667/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4677668/crash.log)
