### ISSUE TITLE
Error whenever the avatar dodges a Zombie attack

### ISSUE THREAD

**Issue by jbytheway** [CleverRaven/Cataclysm-DDA#40841]
# Describe the bug

debugmsg whenever the avatar dodges a Zombie attack (details and stack trace below).

# Steps To Reproduce

1. Generate a new game.
2. Spawn a Zombie
3. Fight and look for dodge events.

# Expected behavior

No debugmsg.

# Versions and configuration

 - OS: Linux
 - Game Version: Current master (86407041) (actually I'm on a branch from that version with some local changes, but I'm 90% sure my changes shouldn't affect anything related to this).
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: DDA, Disable NPC needs

# Additional context

@Fris0uman probably related to your bodypart changes.

Stack trace:
```
15:21:52.610 ERROR : (error message will follow backtrace)
    ./cataclysm-tiles(_Z21debug_write_backtraceRSo+0x38) [0x56312810703d]
    ./cataclysm-tiles(_Z8DebugLog10DebugLevel10DebugClass+0x303) [0x563128107a10]
    ./cataclysm-tiles(_Z12realDebugmsgPKcS0_S0_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x69) [0x56312810a54f]
    ./cataclysm-tiles(_Z10convert_bp9body_part+0x6bd) [0x563127efce8c]
    ./cataclysm-tiles(_ZN7monster12melee_attackER8Creaturef+0x302) [0x563128a0cac4]
    ./cataclysm-tiles(_ZN7monster12melee_attackER8Creature+0x20) [0x563128a0e29e]
    ./cataclysm-tiles(_ZN7monster9attack_atERK8tripoint+0x124) [0x5631289e1874]
    ./cataclysm-tiles(_ZN7monster4moveEv+0x189c) [0x5631289ee898]
    ./cataclysm-tiles(_ZN4game7monmoveEv+0xd19) [0x5631282f4b0f]
    ./cataclysm-tiles(_ZN4game7do_turnEv+0x1071) [0x563128304a0f]
    ./cataclysm-tiles(main+0x159f) [0x563127ce616d]
    /lib/libc.so.6(__libc_start_main+0xeb) [0x7fdaf61d4f2b]
    ./cataclysm-tiles(_start+0x2a) [0x563127ce276a]

    Attempting to repeat stack trace using debug symbolsâ¦
    debug_write_backtrace(std::ostream&)
    â¦/src/debug.cpp:777
    DebugLog(DebugLevel, DebugClass)
    â¦/src/debug.cpp:943
    realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    â¦/src/debug.cpp:115
    void realDebugmsg<body_part&>(char const*, char const*, char const*, char const*, body_part&)
    â¦/src/debug.h:79
    convert_bp(body_part)
    â¦/src/bodypart.cpp:176
    monster::melee_attack(Creature&, float)
    â¦/src/monster.cpp:1389
    monster::melee_attack(Creature&)
    â¦/src/monster.cpp:1351
    monster::attack_at(tripoint const&)
    â¦/src/monmove.cpp:1404
    monster::move()
    â¦/src/monmove.cpp:972
    game::monmove()
    â¦/src/game.cpp:4427
    game::do_turn()
    â¦/src/game.cpp:1621
    main
    â¦/src/main.cpp:697
    __libc_start_main
    ??:?
    _start
    ??:?
Backtrace emission took 1 seconds.
.../Cataclysm-DDA/src/bodypart.cpp:176 [const bodypart_str_id& convert_bp(body_part)] Invalid body part token 22065
15:22:26.698 ERROR : .../Cataclysm-DDA/src/bodypart.cpp:176 [const bodypart_str_id& convert_bp(body_part)] Invalid body part token 22065
```

**Comment by Fris0uman** [comment]
I've just tried it and got the dodges without errors, could there be somethign else involved in getting the error?

**Comment by anothersimulacrum** [comment]
I can't reproduce this by dodging, but I do get it when a monster attacks another.

**Comment by jbytheway** [comment]
Based on some quick debugging, looks like this chunk of code is at fault:
https://github.com/CleverRaven/Cataclysm-DDA/blob/86407041753ac701dadcb4ad451869c332e1b48b/src/monster.cpp#L1384-L1389
There's a default-initialized `dealt_damage_instance` which will have an uninitialized `bp_hit` value.  That doesn't get set to anything if the `if` statement isn't entered (maybe even if it is; unsure), and then the uninitialized value is used.

**Comment by anothersimulacrum** [comment]
That fits with my debugging. I tracked it down to that area, but couldn't figure out why the breakpoint I was setting in that area was always giving me valid bodyparts. I didn't think about what happened if that didn't happen.
