### ISSUE TITLE
Crash when using soldering iron to repair recurve bow

### ISSUE THREAD

**Issue by Arkko002** [CleverRaven/Cataclysm-DDA#40842]
# Describe the bug
The game throws a sigsegv without any warnings after trying to repair recurve bow with a soldering iron.

# Steps To Reproduce

1. Create a new world and a new character with no mods
2. Spawn a recurve bow, soldering iron, plastic chunks and a battery.
3. Damage the bow by smashing it into something.
4. Try repairing the bow with soldering iron.

# Expected behavior

A repair pop-up should appear. 

# Screenshots

None.

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux bullseye/sid; Release: 9.12; Codename: stretch; 
- Game Version: 0.E-2475-g8640704 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4678753/debug.log)

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4678752/crash.log)

**Comment by mutability** [comment]
I think this condition is inverted: https://github.com/CleverRaven/Cataclysm-DDA/blob/684733184adc29f0b8e552741c1aef513758b35e/src/activity_handlers.cpp#L2775

**Comment by meladath** [comment]
Can confirm mutabilities fix works, removing the ! causes soldering iron to repair again!
