### ISSUE TITLE
Rock Forge Not Working For Metalworking Recipes

### ISSUE THREAD

**Issue by TonyBony123** [CleverRaven/Cataclysm-DDA#40848]
Description:

When trying to craft recipes requiring the use of a rock forge, it doesn't recognize that there is one present. Reloading/unloading the rock forge doesn't fix it. The description of the rock forge states that it works as a charcoal forge when crafting, but that isn't the case at the moment.

Steps To Reproduce:

1. Make a player with the debug hammerspace mutation from the debug menu.
2. Build rock forge and spawn in a few hundred charcoal.
3. Reload rock forge with spawned in charcoal.
4. Go to the debug menu and reveal all recipes.
5. Remove the debug hammerspace mutation.
6. When trying to craft an item requiring a charcoal forge, the reloaded rock forge does not count towards the craft.

The expected result would be the reloaded rock forge would count towards the craft requiring a charcoal forge, as the description of the rock forge says so.

Versions and configuration:

 - OS: Windows 10
 - Game Version: Experimental Version 10694
 - Graphics version: UNDEAD_PEOPLE Tileset
 - Ingame language: English
 - Mods loaded: Disabled NPC Needs

The issue does not refer to a crash.

**Comment by Lamandus** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/issues/40771
I already reported that.

**Comment by TonyBony123** [comment]
> #40771
> I already reported that.

Ah alright, this is the first time bug reporting for me.

**Comment by Lamandus** [comment]
No Problem. Keep them coming.

**Comment by Night-Pryanik** [comment]
Closing as duplicate.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/cant-load-rock-forge-or-clay-kiln-with-charcoal/26711/3
