### ISSUE TITLE
Nested container deletion on tie up

### ISSUE THREAD

**Issue by Kurrisum** [CleverRaven/Cataclysm-DDA#40850]
# Describe the bug

Using a short rope from a nested container to tie up an animal consumes or deletes saod container as well all other contents of it.

# Steps To Reproduce
1. Tame animal
2. Acquire rope
3. Nest rope in a container 
4. Tie up animal using rope in the container (in this case a cow)
5. Watch said container disappear
6. Untie animal, only receive short rope back

# Expected behavior

Using only the short rope from a container to tie up an animal without the container being deleted 

# Screenshots
![image](https://user-images.githubusercontent.com/16447312/82848401-ecaaa980-9eb8-11ea-95f3-53fd1674cd44.png)
![image](https://user-images.githubusercontent.com/16447312/82848423-fdf3b600-9eb8-11ea-953b-1d68dec0aaa5.png)
![image](https://user-images.githubusercontent.com/16447312/82848443-11068600-9eb9-11ea-9586-09a037757109.png)
![image](https://user-images.githubusercontent.com/16447312/82848458-211e6580-9eb9-11ea-88f5-bcecacce6cb1.png)
![image](https://user-images.githubusercontent.com/16447312/82848466-2c719100-9eb9-11ea-839e-ad0d8f1f61f9.png)

# Versions and configuration

 - OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2475-g8640704 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    Mining Mod [Mining_Mod],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

**Comment by rtizzy** [comment]
I'm running into this as well on the latest build ([Build #10786](http://gorgon.narc.ro:8080/job/Cataclysm-Matrix/10786/changes)) with no mods.

**Comment by RoyBerube** [comment]
This one looks fixed to me. Tested on a domesticated cow with short rope in a messenger bag. Bag and rope recovered after the cow was untied; no items were lost.

Also tested with a container inside another container. No items lost.
