### ISSUE TITLE
add a zombie horse

### ISSUE THREAD

**Issue by howmokas** [CleverRaven/Cataclysm-DDA#40857]
How about adding a tractable zombie horse?Or zombie wolf.

**Comment by morthein** [comment]
That'd be cool - i feel like it'd be pretty easy.

Copy existing animals
change their loot to the mutant versions of fat/meat so on.
Make them hostile to all, with additional hatred towards players with *Animal Discord* (maybe they chase you until death?)
slight graphics changes to the existing sprites.
Ooh, and their bites all can cause infections.   ugh, that'd be devilishly bad.

**Comment by RafeHaab** [comment]
It doesn't make much sense, wolves and horses are fast and timid, they would outrun the zombies and not get attacked.

**Comment by morthein** [comment]
You underestimate hunger and fear.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by TechyBen** [comment]
> It doesn't make much sense, wolves and horses are fast and timid, they would outrun the zombies and not get attacked.

Animals tire. The blob does not.

**Comment by howmokas** [comment]
I want to drive a zombie horse,because it so cool

**Comment by morthein** [comment]
I kinda want an undead horse pulling my wagon with laser turrets on it now.

**Comment by kwl01skz** [comment]
Next we need a frostmourn？

**Comment by morthein** [comment]
:) he gets it. Lol

Sent from Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by Yunatan** [comment]
Zombie wolfs are already in the game: http://cdda.chezzo.com/monsters/mon_zolf
