### ISSUE TITLE
RX11 stimulant delivery system no longer consumes charges

### ISSUE THREAD

**Issue by ektoplazm** [CleverRaven/Cataclysm-DDA#40861]
# Describe the bug

RX11 stimulant delivery systems no longer consumes charges (it can be used indefinetely without any charges loaded) and it's not possible to reload it with actual charges (RA10K stimulant modules)

# Steps To Reproduce

1. Spawn and wear RX11 stimulant delivery systems 
2. Spawn RA10K stimulant modules
3. Try to reload the system, - "you can't reload" message in the log. 
4. Try to use it without any charges loaded - success, you have infinite stimulants.

# Expected behavior

RA10K stimulant modules are consumed and required to use the delivery system. 

# Screenshots

![image](https://user-images.githubusercontent.com/60448096/82904757-921e5580-9f6b-11ea-8ef5-438e02adf3a5.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-2476-g1b2af09 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

**Comment by hexagonrecursion** [comment]
Can not reproduce. Was this fixed?

**Comment by anothersimulacrum** [comment]
Probably fixed by #41152
