### ISSUE TITLE
Light Plutonium Battery last forever and turns into *none* after installed.

### ISSUE THREAD

**Issue by morthein** [CleverRaven/Cataclysm-DDA#40863]
# Describe the bug

Loading some items with a *Light Plutonium fuel battery* causes it to show it's loaded with *none* instead of it's name AND it doesn't use it's charges, ever. (just like any of the Atomic items)

# Steps To Reproduce

1. Make a player with a mining helmet and light plutonium battery
2. reload the mining helmet.
3. turn on the helmet and have free light forever. (even though the battery lists 1000/1000 for it's energy)

# Expected behavior

The helmet should show what battery is in it instead of *none* and it should slowly drain when used.

# Screenshots
![ya](https://user-images.githubusercontent.com/50846380/82913207-03deab00-9f3c-11ea-89b2-8afe21d15c8a.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2475-g8640704 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Crazy Cataclysm [crazy_cataclysm],
    No Rail Stations [No_Rail_Stations],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    No Fungal Monsters [No_Fungi],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]
# Additional context

**Comment by hexagonrecursion** [comment]
# I can confirm that-

1. Reloading a mining helmet with a light plutonium battery produces a log message "You reload the mining helmet with none"
2. The name of the item becomes "mining helmet with none"
3. After turning the mining helmet on and waiting for 1 hour it says it still has 1000/1000 charge

# Narrowing the scope of the bug down

1. Unloading the helmet produces a light plutonium battery - the battery is not turned into none permanently
2. The "contents of this item" section of the item description correctly lists that the helmet contains a light plutonium battery
3. Not all powered items are affected - flashlight and cellphone do drain charges

# Versions and configuration

- OS: Linux
    - OS Version: Fedora release 32 (Thirty Two)
- Game Version: 0.E-2476-g1b2af09 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by RoyBerube** [comment]
Did some testing with this today and cannot reproduce the bug. The bug may have been fixed since this issue was created.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-10939.
![изображение](https://user-images.githubusercontent.com/11132525/187442557-f4b691d8-1cdd-4f62-8d17-9bdda38dbcf5.png)
