### ISSUE TITLE
Sealed items open across save

### ISSUE THREAD

**Issue by Librarymans** [CleverRaven/Cataclysm-DDA#40876]
Sealed items open themselves after loading.

Containers that are sealed will be not sealed after saving and loading.

# Steps To Reproduce

1. Make a player with vaccum sealer, salt water, plastic bag and vegtables and some cooking skill
2. Make salted Veggie chunks. Bag will be sealed
3. Save and quit. Then reload, bag will be unsealed and veggies will start to spoil

# Expected behavior

Bags and other containers stay sealed after saving and loading. Otherwise no point in preserving food.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2476-g1b2af09 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    DinoMod [DinoMod],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    Stats Through Skills [StatsThroughSkills]

# Additional context

**Comment by TheMasterGear** [comment]
I can confirm on the latest builds windows 64 that with or without mods, canned items will open after a reload.
**Steps To Reproduce**
Make a new character and start at a safe place, choose a cabin for location. Find canned food in the said cabin, it will be sealed. Save the game and go to the menu or alt f4. Reload the game and all cans will be open and spillable.
![bug 1](https://user-images.githubusercontent.com/60374171/83337394-e76aa780-a288-11ea-91ca-380877a260bc.png)
![bug 2](https://user-images.githubusercontent.com/60374171/83337397-eafe2e80-a288-11ea-8acc-3e26f1df46bb.png)

**Comment by Resok** [comment]
Yup, I'm seeing this also. Within the same session as long as I don't quit out and reload the item remains sealed.

For example -

![image](https://user-images.githubusercontent.com/5217673/83362573-41ca3d80-a347-11ea-8f50-523bcd6bc198.png)

This is what the savegame data for this item looks like -

![image](https://user-images.githubusercontent.com/5217673/83362718-44796280-a348-11ea-916f-78126790514c.png)

`{ "pocket_type": 0, "contents": [ { "typeid": "plastic_bag_vac", "bday": 5245113, "owner": "your_followers", "last_rot_check": 0, "last_temp_check": 0, "relic_data": null, "contents": { "contents": [ { "pocket_type": 0, "contents": [ { "typeid": "apple_sugar", "charges": 7, "bday": 5245113, "owner": "your_followers", "active": true, "rot": 31836, "last_rot_check": 5245134, "last_temp_check": 5245134, "components": [ { "typeid": "water", "charges": 1, "bday": 5233911, "active": true, "last_rot_check": 5233911, "last_temp_check": 5244729, "specific_energy": 98201056, "temperature": 29063934, "relic_data": null }, { "typeid": "bag_plastic", "bday": 5233903, "owner": "your_followers", "last_rot_check": 0, "last_temp_check": 0, "relic_data": null }, { "typeid": "blueberries", "charges": 4, "bday": 5233903, "owner": "your_followers", "active": true, "rot": 10612, "last_rot_check": 5244721, "last_temp_check": 5244721, "specific_energy": 87719880, "temperature": 29064072, "relic_data": null }, { "typeid": "sugar", "charges": 14, "bday": 5233911, "active": true, "last_rot_check": 5233911, "last_temp_check": 5244729, "specific_energy": 36402924, "temperature": 29064948, "relic_data": null } ], "specific_energy": 88698496, "temperature": 29315000, "recipe_charges": 7, "relic_data": null } ] } ] } } ] }`

but as soon as I reload my game -

![image](https://user-images.githubusercontent.com/5217673/83362750-7d193c00-a348-11ea-8622-024a30f579cd.png)

Attached is my save with all of the components to recraft this same supposedly sealed item.

To repro, simply load save and craft the fruit slice recipe again.

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4708475/save.zip)
