### ISSUE TITLE
Lock a container to prevent program putting items into it automatically.

### ISSUE THREAD

**Issue by waveyl** [CleverRaven/Cataclysm-DDA#40885]
# Is your feature request related to a problem? Please describe.
Now, system will allocate storage space automatically without player involvement.
# Describe the solution you'd like
Allow player to lock and unlock some containers to achieve different container for different function.
For example, I have 3 armors, one for battle, one for tools, one for collection, I'd like to put new items I get into the third, instead of confusing them,or increasing encumbrance of my battle armor. so I lock first and second.
# Describe alternatives you've considered
 A better solution.

**Comment by anothersimulacrum** [comment]
Duplicate of #40169 (this would be a feature of favored pockets)
