### ISSUE TITLE
Atomic lights produce no light.

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#40884]
# Describe the bug

All atomic lights produce no light.

# Steps To Reproduce

1. Spawn in atomic headlamp, phone, reading light, etc.
2. Activate it.
3. Stand in darkness.

# Expected behavior

There is light. 

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2476-g1b2af09 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock]
]

# Additional context

**Comment by ZhilkinSerg** [comment]
Should be fixed in #40888
