### ISSUE TITLE
Acoustic guitar produces no music

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#40889]
# Describe the bug

Playing acoustic guitar, electric guitar or harmonica gives no morale boost and produces no messages in the log. mp3 player works as intended though.

# Steps To Reproduce

1. Wish for an acoustic guitar
2. Activate it
3. Wait for 5 minutes
4. [v]iew morale
5. See that there is no morale bonus

# Expected behavior

Playing music should give a morale bonus.

# Screenshots

none

# Versions and configuration

- OS: Linux
    - OS Version: Fedora release 32 (Thirty Two)
- Game Version: 0.E-2476-g1b2af09 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

none

**Comment by wapcaplet** [comment]
I can reproduce this in O.E-2623-g8889927af6 - immediately after I start playing an acoustic guitar or harmonica, I see the "Playing an instrument" effect, and get a 100% morale bonus for music:

![image](https://user-images.githubusercontent.com/238395/83317965-14b64780-a1ee-11ea-8ca5-d42961c26f34.png)

But 5 minutes later both the status effect and morale bonus are gone. The instrument remains active, but it's no longer having an effect.

I went back and checked the 0.E-2 build, and the guitar gives an ongoing morale bonus and effect as expected, but there are still no messages about music being played.

**Comment by wapcaplet** [comment]
This is fixed in my PR #40997 as a funny side-effect of fixing gas mask filters.

![image](https://user-images.githubusercontent.com/238395/83470166-ca77d500-a43e-11ea-94e2-63284cf2ae6e.png)
