### ISSUE TITLE
Zombie Clowns

### ISSUE THREAD

**Issue by Dendygaar** [CleverRaven/Cataclysm-DDA#40882]
Problem: Lack of zombie clowns

Add Zombie Clowns: Rare(r) spawn
Zombie clowns gently honk and move slower than normal. Nearby zombies are likely to cluster around a rogue clown if not taken down quickly. Unfortunately most conventional means of removal don't work so great, as smacking it will make louder honks. Do you let it be and let a horde form? Or do you risk melee to kill it and potentially attract a horde from an even larger area (due to louder honking impact honking) 
Like other special infected there is a method to the madness: chemical, and incendiary methods don't honk them. Piercing attacks have a lower chance. 

No alternatives unfortunately, this is non negotiable.

Essentially these bad boys act as slow moving living sirens that require a bit of creativity to handle, or the ability to handle a potential horde forming from nearby otherwise not alerted enemies. Kill him before he becomes a Clown Hulk, who honks louder, moves faster, and is much less funny than his smaller kin

![220px-Clown_chili_peppers](https://user-images.githubusercontent.com/64884619/82967082-ca388f00-9f91-11ea-9c16-c9b4d6cb5fa5.jpg)

**Comment by ymber** [comment]
We already have the shrieker evolution line that fills this role better.
