### ISSUE TITLE
Fleet-Footed + Languorous gives permanent winded

### ISSUE THREAD

**Issue by Centac** [CleverRaven/Cataclysm-DDA#40909]
# Describe the bug

If you have Fleet-Footed and Languorous and you use up all of your stamina, you get a permanent winded debuff and you will have zero stamina regen.

# Steps To Reproduce

Make a character with Fleet-Footed and Languorous.
Run around until you have zero stamina and you get the winded debuff.

# Expected behavior

Normally speaking, when a character loses stamina, it reduces down to :----, you receive a winded debuff that will go away after ~30 seconds and you will regen stamina after that. However, when the character has both Fleet-Footed and Languorous, the stamina will go down to -----, the winded debuff is permanent, and you will completely stop gaining stamina. After days of waiting, winded will still not go away and the stamina is permanently stuck at -----.

P.S. Once you get to -----, you can remove Fleet-Footed and the condition stays. You only need Fleet-Footed to help get from :---- to -----. It doesn't directly cause the issue. However, removing Languorous when at ----- will fix the condition. You will catch your breath and the game will run normally.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-2570-gb8bc6f1
- Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: dda, Disable NPC Needs

# Additional context
Saved game
[Testworld.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4693324/Testworld.zip)

**Comment by hexagonrecursion** [comment]
I was able to reproduce this with only Languorous - Fleet-Footed is completely optional.
