### ISSUE TITLE
Character Creation Crash in Magiclysm

### ISSUE THREAD

**Issue by XamXam02** [CleverRaven/Cataclysm-DDA#40913]
# Describe the bug
During character generation the game will spit out a quick
" DEBUG    : can't set ammo null in inhaler as it is not an ammo

 FUNCTION : item& item::ammo_set(const itype_id&, int)
 FILE     : src/item.cpp
 LINE     : 579"
and then crash

# Steps To Reproduce

Make a world with the Magiclysm mod, and then make a character with the "wizard's apprentice" scenario. it doesn't matter what class or anything else ive found just that you start with in that scenario.

# Expected behavior

i expected to be able to load up a new world, loot my basement and be on my marry way. i imagine this has something to do with the charges of an inhaler which id take a gander is an item in the starting location, but that just a guess made from an untrained eye.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-2570-gb8bc6f1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm]
]

# Additional context

[crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4693852/crash.zip)

i feel this step in rather redundant. the nature of the crash will stop the game before anything can be generated . i ran the bug and saved the file anyways, but i doubt it will help much
[The One That Crashes.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4693846/The.One.That.Crashes.zip)

**Comment by KorGgenT** [comment]
probably fixed by #40790 please reopen if it is still broken
