### ISSUE TITLE
Items disappear when pick-up is cancelled

### ISSUE THREAD

**Issue by DarkDaskin** [CleverRaven/Cataclysm-DDA#40916]
# Describe the bug

When inventory is full and an item is picked up, a prompt will appear. Cancel it and the item on ground disappears.

# Steps To Reproduce

1. Make a player wearing some clothing with pockets.
2. Fill your pockets with stuff.
3. Wield some item.
4. Try to pick some items from ground.
5. An prompt to get rid of wielded item will appear. Press ESC.
6. The item on ground will disappear.

# Expected behavior

The item on ground remains intact.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-2566-gbf8581b
 - Graphics version: Tiles

**Comment by Ramza13** [comment]
Could not reproduce

**Comment by DarkDaskin** [comment]
Checked it on the save where I initially found the bug, it now behaves as expected.
