### ISSUE TITLE
Autoclave pouch recipe

### ISSUE THREAD

**Issue by 124as** [CleverRaven/Cataclysm-DDA#40914]
### Is your feature request related to a problem? Please describe.
Autoclave pouches are uncraftable.  It would be more realistic if they were craftable- reasoning below.

Autoclave pouches must be 'FDA' approved in real life, which I guess is why they are uncraftable in-game. Only FDA-approved pouches are allowed in medical practice to prevent liability and lawsuits- that's why your doctor will show you the tools they will use before surgery, still sealed in their sterilization pouches.  

In reality, the pouches are very simply made.  They are made of an alcohol-rinsed paper-nylon-plastic blend designed to let the steam from the autoclave permeate the pouch. The only thing special about them is each one is inspected for tears by an FDA quality inspector.  In a post-apocalyptic environment, you should be able to craft and inspect the pouch yourself, given enough skill.

### Describe the solution you'd like
Create an autoclave pouch crafting recipe, probably learned from a book since it must be crafted to a certain standard.  'Guide to Advanced Emergency Care' seems like the best book.
I'd say something like this makes the most sense:

> Primary Skill: First Aid(5)
> Required Skill: Cooking(3)
> Materials: Paper, Plastic
> Required tools:  
> - A tool with level 3 Chemical making quality
> - A tool with level 1 boiling
> - Heat source (fire, mess kit, etc)

> Similar components to a plastic bottle but with additional paper and alcohol components:
> Plastic parts, paper parts, denatured alcohol.

### Describe alternatives you've considered
Different recipe
Autolearnable?
Use a vacuum sealer?

### Additional context
Further reading: [https://www.rdhmag.com/infection-control/personal-protective-equipment/article/16407763/selfadhesive-sterilization-pouches](url)

**Comment by Fris0uman** [comment]
How do you turn a page from a phone book and a plastic bag into "an alcohol-rinsed paper-nylon-plastic blend designed to let the steam from the autoclave permeate the pouch."?

**Comment by 124as** [comment]
> How do you turn a page from a phone book and a plastic bag into "an alcohol-rinsed paper-nylon-plastic blend designed to let the steam from the autoclave permeate the pouch."?

Check out [this link](https://www.oralhealthgroup.com/features/steam-sterilization-bag/)- it has some more info. Also [this video](https://www.youtube.com/watch?v=1dlcoCdqNy0) and [others like it](https://duckduckgo.com/?q=sterilization+pouch+making+machine&atb=v200-1i_&ia=videos&iai=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D1dlcoCdqNy0&pn=1) show a bit of the process on the industrial scale. 
Take a quick look at the video if you can, it does a good job framing what has to be done.  From what I can tell the important parts are 

1.  The laminate plastic and paper
2.  The treatment on the plastic (which the cdda recipe covers with chemical making tools)
2.  The heat and pressure applied to attach the laminate and paper product.

**Comment by Fris0uman** [comment]
What I'm getting from this is that pouches are not craftable by a survivor in the post appocalypse. You don't have access to any of those machines, maybe we could add the material used to make them, but then you're probably still better off finding the pouch than crafting them anyway.

**Comment by 124as** [comment]
I disagree.  There is an irl industrial machine for everything you can make in cataclysm, but that doesn't matter.  A survivor can't make stuff on an industrial scale, but individual recipes are different.
Crafting them post-apocalypse would be relatively simple, in terms of real-life.  Anyone- literally someone like you or me- who knows how it's done (who has read the book) would have no problem with it.
It really is just:

1.  Cook the paper and plastic in an alcohol
2.  Stretch the material into a sheet
3.  Heat the sheets and melt them together,

There's not much special about the bags. They are just clean baggies made of paper and plastic.

**Comment by Dacendeth** [comment]
Perhaps the autoclave only accepts factory made pouches, but I dont see why a player made variant couldnt be skillfully crafted that would meet the standards for the tacoma doctor to install them in you.

**Comment by 124as** [comment]
An autoclave doesn't really need to accept anything.  It's a box that sprays steam over whatever is inside it to disinfect it.  You could put anything that will fit into an autoclave and the autoclave will sanitize it.  
Technically you shouldn't even need the pouch, if you use the CBM right after you sanitize it.  The pouch is keeping things sanitized only.  A real autoclave will disinfect something inside the autoclave pouch, but will only let the steam inside under heavy heat, so handling the bag at room temperature afterwards wouldn't make its contents dirty.

**Comment by anothersimulacrum** [comment]
> Perhaps the autoclave only accepts factory made pouches, but I dont see why a player made variant couldnt be skillfully crafted that would meet the standards for the tacoma doctor to install them in you.

I don't know what you're trying to say here.
The doctor doesn't want autoclave pouches, it wants sterilized CBMs, which you only get from finding or sterilizing non-sterile ones in an autoclave.

>  A real autoclave will disinfect something inside the autoclave pouch, but will only let the steam inside under heavy heat, so handling the bag at room temperature afterwards wouldn't make its contents dirty.

Yes, this is how it's simulated in game?

**Comment by Dacendeth** [comment]
I was trying to say that a craftable autoclave pouch could be used to create a sterlized CBM that was sterilized in a way that the doctor would approve of but the machine would detect it as being unsterilized because you used the wrong sort of pouch.

**Comment by anothersimulacrum** [comment]
You mean the autodoc, not the autoclave then. That makes more sense.

**Comment by Dacendeth** [comment]
Oh right my bad yeah autodoc.

**Comment by 124as** [comment]
> Yes, this is how it's simulated in game?

In game you need the pouch to disinfect something, which doesn't reflect reality.  A real autoclave can disinfect something just fine without the pouch, the pouch is just for storage after it's disinfected.  In game it would make more sense to have the CBM stay sterile for a little bit after coming out of the autoclave, and then lose the Sterile quality after some time, or if it moves to a different container.  

That would fix some gameplay hiccups too.  Sterilizing CBMs is prohibitive right now because you still need to find an arbitrary item with a low-spawn rate.  The change I just mentioned would probably be the best fix (and would best simulate reality), but making a pouch recipe fixes it too, and still makes the game more realistic.

**Comment by Fris0uman** [comment]
> real autoclave can disinfect something just fine without the pouch,

That's how it was initially implemented but I got rid of it because it was unecessary complications and a lot of players where confused as to why the CBMs were sterile only for a moment.

**Comment by 124as** [comment]
> That's how it was initially implemented but I got rid of it because it was unecessary complications and a lot of players where confused as to why the CBMs were sterile only for a moment.

Great!  If the system was confusing, then it's good you changed it.  I'm glad we agree the current system doesn't reflect reality.  Adding a recipe for autoclave pouches reflects reality better than not crafting it at all, and will help make gameplay better.

**Comment by 124as** [comment]
I don't know what this 'confused' stuff is about.  

He said he had the system set up to simulate reality (sterile CBMs without bags).  He changed it because it was confusing and difficult to implement.  So the current system doesn't reflect reality.  

In order to bring it back to a more realistic state, adding an autoclave pouch recipe would fix the realism problem and the gameplay problems.  

That's all I'm saying.  The system is not perfect, according to the person who created the autoclave system.  Adding a pouch recipe would fix several problems with the system.

**Comment by anothersimulacrum** [comment]
I reacted that way because it seemed like you were putting words in his mouth - "We both agree that my proposed solution would make this better" - but I see now that I just misread what you said, sorry.

**Comment by Fris0uman** [comment]
I'm still not convinced that the pouch are craftable, at least not from plastic and paper. Maybe from the right kind of pastic and the right kind of paper, but then you've replaced looking for pouch by looking for pouch components so gameplay wise it doesn't change much.

**Comment by 124as** [comment]
Fair enough.  I'll do some more digging and see if I can find something more concrete info.

If I found a materials list or reached out to manufacturers would that be convincing enough?

**Comment by Sumguy62** [comment]
On the other hand, paper autoclave pouches that work just fine _do_ exist. ВИНАР sells them, and at least claims that they meet the ISO standards. So, all you really need is paper that's of the right porosity and thick enough to not tear when it gets wet and glue that doesn't come undone when it gets steamed. So, paper (since we don't have different kinds of paper) and I guess superglue, although you'd need more superglue when sealing it.

**Comment by DillonSimeone** [comment]
https://www.quickmedical.com/healthmark-instrument-sterilization-paper-bags.html

Hmm... Seems legit. 


- medical-grade paper
- Bags can be folded or taped closed

![image](https://user-images.githubusercontent.com/21962421/83318789-eb48ec00-a1ec-11ea-8de9-778cee84396f.png)


https://www.kjsp.co.jp/english/products/mep.html

**Comment by kevingranade** [comment]
As @Fris0uman points out, there is no, "from common, household materials" kind of recipe for this, it requires *very specific* materials, and that defeats your stated purpose of streamlining acquisition of these items. If you want to add those specific materials and such, go ahead, but bnb it's not going to solve your problem.

It would probably be more productive to look through mapgen locations and find places that would have the pouches on hand, such as veterinarians, tattoo parlors, etc.
