### ISSUE TITLE
Get XP by completing missions which you can spend on stats or skills

### ISSUE THREAD

**Issue by gmlacrosse** [CleverRaven/Cataclysm-DDA#40923]
# Is your feature request related to a problem? Please describe.
When you complete a mission in CDDA you only get a mission complete, and sometimes a small reward. This seems like an insufficient motive for doing missions which could help keep the player interestered in the game.

# Describe the solution you'd like
When you complete a mission you would get some XP (similar to stats through kills) that you can spend on stats or skills.

# Describe alternatives you've considered
Only spend on stats or have it do it automatically as a reward. Maybe get an item that when activated boosts a random stat or skill.

# Additional context
Missions with incentives like improving stats is more fun

**Comment by anothersimulacrum** [comment]
This is available under the `Maybe you can teach me something as payment?` dialogue option.

**Comment by ZhilkinSerg** [comment]
Infrastructure is already there (see https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/MISSIONS_JSON.md) and you just need to add missions with interesting rewards.

**Comment by KorGgenT** [comment]
this idea doesn't seem like something that fits at all with vanilla, as even your example of stats through kills is a very game-ified mod. as sim mentioned, you can also ask the mission giver to reward you by teaching you a skill (in the form of a skill level up)
