### ISSUE TITLE
Segfault when firing a flaregun and glowstick dying too fast

### ISSUE THREAD

**Issue by Medecube** [CleverRaven/Cataclysm-DDA#40937]
# Describe the bug

A. Firing a flare gun raises a SIGSEGV: Segmentation fault.
B. Glowstick goes out after ~10 in game turns.

# Steps To Reproduce

A1. Spawn in a loaded flare gun/obtain a flare gun.
A2. Shoot it anywhere.

B1. Obtain a glowstick.
B1. Activate it.
B2. After around 10-20 turns (12 turns on my tries), it goes out.
B3. Saving, existing and opening the game presents this error:

   DEBUG    : Item glowstick_dead was loaded with charges, but can not have any!

   FUNCTION : void item::io(Archive&) [with Archive = io::JsonObjectInputArchive]
   FILE     : src/savegame_json.cpp
   LINE     : 2325

# Expected behavior

No SIGSEG crash.

The glowstick should last a couple hours.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-2532-gf4bb830 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

[logs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4699801/logs.zip)

**Comment by Weker01** [comment]
Is this one bug or two? If this is about two different bugs it should be split in two, so that they can be individually closed.

**Comment by anothersimulacrum** [comment]
The first bug it's about is resolved, now it's just glowsticks.

**Comment by ThePotatomancer** [comment]
can reproduce glowstick bug, effects any item with turns_per_charge that has no ammo attribute in json (in lighting it affects glowstick, torch, candle and handflare, might affect non lighting items as well)
adding any ammo to those items fixes the bug.
I could probably solve by adding a generic charge ammo, that may not be reloaded. either that or we implement a generic charge behavior in the c++ code (which would also fix issues with any other unknown problematic items)

**Comment by ThePotatomancer** [comment]
further inspection shows that the issue originates from ammo_consume defined in items.cpp file.
it has code to handle tools without ammo type, that doesn't seem to work as expected. more delving to understand why is required
