### ISSUE TITLE
Cant attach battery mods to makeshift arc wielder and arc wielder.

### ISSUE THREAD

**Issue by rafaelkb** [CleverRaven/Cataclysm-DDA#40948]
# Describe the bug

Cant attach battery mods to makeshift arc wielder and arc wielder.

# Steps To Reproduce

1. Make a player with makeshift arc wielder
2. Try to attach a battery mod.
3. There's no way to attach a battery mod.

# Expected behavior

I expect to be able to attach a baterry mod to my makeshift arc wielder.

# Versions and configuration

 - OS: Windows 10
 - Game Version: Cataclysm-DDA experimental build #10707

 - Graphics version: Tiles
 - Ingame language: english
 - Mods loaded: no npc needs, no zombie revivication, Aftershock.

**Comment by Pupsi-Mupsi** [comment]
Confirmed. 



- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-2809-g75e9425a27-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by wapcaplet** [comment]
Confirmed here as well, and not just with the arc welder - I cannot install any battery mods to any tools. Tried light, medium, and heavy battery mods, with hotplate, flashlight, arc welder, mp3 player and vibrator. In all cases, trying `a` to activate the battery mod, I get the message "You don't have compatible tools."

![image](https://user-images.githubusercontent.com/238395/83978594-e7d8f300-a8c5-11ea-866f-3bd267b23b65.png)

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Pop!_OS 19.10; Release: 19.10; Codename: eoan; 
- Game Version: 0.E-2872-g95b72cd4e5-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by aragonasx** [comment]
Same thing happened to me an annoying bug
