### ISSUE TITLE
Reloading items in inventory unexpectedly drops the item

### ISSUE THREAD

**Issue by mutability** [CleverRaven/Cataclysm-DDA#40960]
# Describe the bug

When a carried item is reloaded, its volume might change.

If the new volume exceeds the pocket capacity of the item's current location, the item is silently dropped, even if there is other available container/inventory space.

# Steps To Reproduce

1. Create a test character, strip off existing clothes and items
2. Spawn and wear cargo pants
3. Spawn soldering iron (volume 0.5L). It should end up in one 0.5L pocket of the cargo pants.
4. Spawn light disposable battery (volume 0.04L). It should end up in a different 0.5L pocket
5. `i`nventory -> soldering iron -> `r`eload
6. Reloaded soldering iron (now with volume 0.54L) is silently dropped on the ground.

# Expected behavior

Reloaded soldering iron should be moved to one of the larger available pockets.

If there is no available pocket, player should be notified, and ideally prompted for what to do with the item (wield / drop / etc).

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch; Distributor ID: Ubuntu; Description: Ubuntu 18.04.4 LTS; Release: 18.04; Codename: bionic; 
- Game Version: 0.E-2607-ga3c5c682ad-dirty [64-bit]  (Based on upstream 14dcde8731fc33c5aec8e98d907e71f36bb9c6c7)
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by wapcaplet** [comment]
Cannot reproduce in 0.E-9572-g483cd09a89.

The soldering iron is now only 0.1 L, so I tried to reproduce this using cargo shorts, a handheld game system, and a light disposable battery. Starting with the game and battery in separate pockets:

![image](https://user-images.githubusercontent.com/238395/107724514-41898c80-6ca1-11eb-885a-729f9f6b1e9a.png)

`r`eloading the game system correctly loaded the battery without dropping anything.

Spawned an mp3 player and a second light battery, reloaded and unloaded both devices a few times - nothing was dropped. I think this is fixed.
