### ISSUE TITLE
When Flesh pouch despawns it takes all items with it

### ISSUE THREAD

**Issue by Elkator** [CleverRaven/Cataclysm-DDA#40962]
# Describe the bug

If the flesh pouch cast by the spell despawns the items in it despawn as well. Probably because of the inventory update.

# Steps To Reproduce

1 Get Scroll of flesh pouch
2 learn and cast it
3 put an item in it
4 wait until duration ends

# Expected behavior

The items remain, either redistributed in the inventory or fall on the ground.

# Screenshots

# Versions and configuration
    - - OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2684-g2bb4c7f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    Mining Mod [Mining_Mod],
    Mythical Martial Arts [MMA],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Bionic Slots [cbm_slots],
    Stats Through Skills [StatsThroughSkills]
]

    - Please update your OS version with a more precise version.

 - OS:  Windows 10
 - Game Version: 0.E-2684-g2bb4c7f [64-bit]
 - Graphics version: Tiles
 - Ingame language: English

**Comment by kwl01skz** [comment]
This is not just a problem with Mod. If we eat a "hide bag" (or wait for it to rot), the items inside will disappear.
@KorGgenT

**Comment by KorGgenT** [comment]
should all the items inside an item you're eating be eaten? i think "maybe"

**Comment by kwl01skz** [comment]
All.
All items contained in hide_bag, including things that are not food, disappeared.
hide_bag can be eaten and is also a container.
I think "eating" and "timeout" are the same.
That is, the container "disappeared", and the result is that the items in it also "disappeared",
