### ISSUE TITLE
Magiclysm: Laevateinn cannot be contained in spear strap or Belt of Weaponry

### ISSUE THREAD

**Issue by Adomatic** [CleverRaven/Cataclysm-DDA#40979]
# Describe the bug
The flags for Laevateinn do not contain SHEATH_SPEAR, which other staves and spears and so forth do. And the Belt of Weaponry does not contain it either, although it's not terribly clear to me what governs that. (The sensible thing to have done would be to make the Belt of Weaponry contain anything that any other weapon container can, using the same flags, but that doesn't seem to be the case, so I presume it )

It is not entirely clear what Laevateinn is:

- It is called a staff, but it does more cutting damage than bashing
- It is created out of an iron-shod quarterstaff, a tiny bit of gold, and more orichalcum, but when it is finished it is composed of gold and steel. (Of course, an 'ironshod quarterstaff' is made with steel, not iron, so... heh. But we're still missing wood and orichalcum).
- it is a staff-length weapon that does cutting damage, but it does not have reach. The only other staff-length weapons that do cutting damage but don't have reach are the lajatang and the scythe, and one can't help but suspect that if it were meant to resemble either of them, the description would say so.

Outside the game, very little mythological reference to it exists. Its original name is Hævateinn, amended as Lævateinn (literally, 'damage twig', which some people consider to be a sidelong reference to a sword and others a staff or wand). We seem to have picked one, 'staff', and I can just about see how a weapon of Loki would have a 'cutting surprise' when used, although I'd more expect fire or cold damage.

But in any case, if we assume that it is either a staff or a polearm/spear with a cutting blade which is too short to have reach, then it certainly should be able to be contained in a spear strap. And since the Belt of Weaponry states it is "a wide girdle that fits around your waist, you can sheath or holster any weapon into it in the blink of an eye, and it seemingly stores them somewhere else." and this is, in fact, a weapon, it should presumably be able to contain Laevateinn as well.

If it is a sword, then it should be notated as such, and should be stored in the appropriate scabbard, and be added to the appropriate martial arts. (And BTW if it's a staff it should also probably be added to ninjutsu, since quarterstaffs are there.)

# Steps To Reproduce

1. Craft Laevateinn
2. Look at its description and note that it doesn't say it can be stored in anything.
3. Craft a spear sling.
4. Activate it and note that Laevateinn cannot be stored in it.
5. debug-create a belt of weaponry (since I have no idea where to get one otherwise) and note that it also cannot contain Laevateinn.

# Expected behavior

Assuming we keep this as a spear, then for the spear sling, two alternatives: most reasonably, it absolutely should be able to contain Laevateinn. Alternatively, Laevateinn should clearly explain in its description why it cannot. (Sharp blades sticking out of both sides, some huge weird blade sticking out that gets in the way, disintegrates anything it touches, whatever. Although I will note that the idea that a magic staff would look like a lajatang or a scythe is just soooo against any kind of Norse sensibility that I can't even. In the stories, they all look like walking staffs. Always. They look innocent until they're used.)

No matter what this ends up being, the belt of weaponry is a magic item that was expressly designed to contain weapons. There is absolutely no reason that it should be able to contain a spear and Mjolnir but not Laevateinn.

# Versions and configuration

The spear sling problem is true of both 0.E and top-of-tree. The belt of weaponry I did not test on top of tree but I suspect it is probably there too.

**Comment by KorGgenT** [comment]
it sounds like you really know what you're talking about, so i would be happy to accept a pull request. all of this should be doable easily in json. generally, the mythological weapons aren't _perfectly_ in magiclysm's lore, but they seem neat enough to keep around. i'm pretty sure it's supposed to be a spear, and not being able to put it in a spear strap is an oversight.

**Comment by Adomatic** [comment]
I don't think the belt of weaponry is doable in JSON?

**Comment by Adomatic** [comment]
Actually I think maybe the belt of weaponry has already been fixed in top-of-tree anyway, by the new container code.
