### ISSUE TITLE
Rocks multiplying

### ISSUE THREAD

**Issue by Tosscoble** [CleverRaven/Cataclysm-DDA#40978]
# Describe the bug

The rocks i'm using as ammo for my sling are multiplying. Every rock i pick up count as two on my inventory.

# Steps To Reproduce

I couldn't reproduce it, i started a new world, spawned some rocks and a sling, but it worked just fine.

# Expected behavior

Every rock i pick should give me one.

# Screenshots

![rocks](https://user-images.githubusercontent.com/65551836/83340011-c23a6100-a2a9-11ea-8859-0f56f148b2d9.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2702-ge4d9a10 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Stats Through Kills [stats_through_kills],
    Magiclysm [magiclysm]
]

 -->

# Additional context

Here is the save

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4706672/save.zip)

**Comment by wapcaplet** [comment]
I can reproduce the issue using your attached save game - either by dropping 1 rock and picking it up (I get 2 back), or by killing a zombie and getting the rocks back from their corpse (I picked up 3 and got 6 back). I couldn't determine steps to make it happen in a new game world.

**Comment by EvgenijM86** [comment]
@KorGgenT what is the intention of this code?

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/character.cpp#L2309
```
    } else {
        pocket->add( it );
        ret = &pocket->back();    <---- this line here
    }
```
Is it supposed to return the item that was added to a pocket? Or just the last item in the pocket?

It calls restack() inside add(), thus, it can return a totally different item than the one we were adding.

**Comment by Ataman** [comment]
Not sure #41042 fixed the problem. I keep picking up two arrows instead of one when collecting my fired arrows from the ground.

![image](https://user-images.githubusercontent.com/419241/83981172-d6223a80-a91b-11ea-8a5e-562c1833b904.png)

Also interesting, the MP5 was always just sitting in my inventory without being used but the log says I'm picking the MP5 up. (What I'm really picking up are arrows though).

Used version: 0.E-2947-g8c946f2 (tiles), should be build #10736

**Comment by EvgenijM86** [comment]
I tested with provided save just now, shot about 30+ rocks, picked them up and the total number of rocks where 46 - same as I started with. So that seems fixed, unless the bug is more rare. Can you upload your own save? It might be specific to your pocket configuration that your character is wearing.

**Comment by Ataman** [comment]
Just made a completely new world with only default mods. I spawned in a short bow and some makeshift wooden arrows as well as the H&K MP5A2 with an extended magazine. 

I spawned in exactly 50 makeshift wooden arrows. After shooting a bit at the ground and 2 zombie dogs, I ended up with: 49 + 5 makeshift wooden arrow and 1 _wooden broadhead arrow_ Not only did the game produce arrows out of thin air, it even produced one of a different kind...

World save attached.

[Alsuma (DEBUG).zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4747536/Alsuma.DEBUG.zip)

**Comment by EvgenijM86** [comment]
I have killed 6 more zombie dogs and could not replicate this. I ended up with 1 less arrow that I started with. Are you sure you have compiled latest code? I.e. git pull on master branch.

**Comment by Ataman** [comment]
I'm not compiling the code myself, I use the CDDA Launcher which, as far as I know, pulls the binaries from the releases section of this github. In this case this one: https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-jenkins-b10736

**Comment by EvgenijM86** [comment]
The last commit of that build was at 2020-06-07 20:48:03.
My bugfix was merged in at 2020-06-07 23:47:29.
My conclusion is that your build simply does not have that bugfix.

**Comment by Ataman** [comment]
You're right my bad, I saw that the fix was 6 days old and merged, thus I wrongly assumed the latest release (from that time) had the fix in it.

**Comment by int-ua** [comment]
Comments above indicate this was fixed.
