### ISSUE TITLE
Survivor utility belt tool qualities not usable when sheath contains a knife

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#40973]
# Describe the bug

When a knife is inserted into the sheath of the survivor utility belt, all the inherent qualities of the belt (screw driving, bolt turning, metal sawing etc.) become unusable for crafting and vehicle maintenance.

# Steps To Reproduce

1. Spawn a survivor utility belt
2. Spawn a hunting knife, dive knife, or other knife compatible with the belt's sheath
3. Check crafting and vehicle construction menus - belt's qualities are available
4. Insert knife into the utility belt sheath (with `a`ctivate or `i`nsert)
5. Check crafting and vehicle construction menus - belt's qualities are *not available*

# Expected behavior

Qualities provided by the belt should be available, whether or not there are items stored in the sheath.

# Screenshots

Belt qualities with nothing in the sheath, and crafting menu for the "antenna" showing metal sawing quality in green / available:

![image](https://user-images.githubusercontent.com/238395/83334308-d018c380-a262-11ea-999c-bc80eeb82e44.png)

Same belt with a dive knife in the sheath - all qualities are shown in the item description, but the belt no longer gives metal sawing quality in the crafting menu, indicated as red / unavailable:

![image](https://user-images.githubusercontent.com/238395/83334315-db6bef00-a262-11ea-9b9d-068c2d80cab1.png)

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Pop!_OS 19.10; Release: 19.10; Codename: eoan; 
- Game Version: 0.E-2702-ge4d9a10e67 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

- Related issue with survivor belt conflicting with holstered items: #39148
- Survivor mess kits lose their boiling quality when filled with fuel: #39567 
- Cordless drill having screw driving quality even when unloaded: #39246

**Comment by wapcaplet** [comment]
While testing this, I noticed also that the survivor utility belt's defined `"use_action"` doesn't seem to work:

```json
"use_action": [ { "type": "holster", "holster_prompt": "Sheath blade", "holster_msg": "You sheath your %s" }, "CROWBAR", "HAMMER" ],
```

The message "You sheath your ..." is not shown when sheathing a knife. I'm not sure what the "CROWBAR" and "HAMMER" flags are supposed to do here, but neither a crowbar nor a hammer may be stored in the belt.

**Comment by ThePotatomancer** [comment]
seems that no check is called for survivor belt qualities when there are items in pockets. 
the CROWBAR and HAMMER tag mean that you can do crowbar and hammer actions with the tool belt (pry), so they work as intended.
seems like for some reason container qualities are skipped if they are not empty

**Comment by kevingranade** [comment]
Now that the tool holding containers are nested containers, this is no longer an issue, right?

**Comment by wapcaplet** [comment]
I can still reproduce this in 0.E-8226-g0f48ccd485, although it is peculiar to which method is used to put the knife in the survivor belt.

Using `i`nsert from the survivor belt, after inserting a trench knife, all the belt's qualities are available for crafting and vehicle maintenance

However, when I am wearing an empty survivor belt, and picking up the same trench knife from the ground, when it is *auto-inserted* into my survivor belt sheath, the problem manifests itself - the belt's qualities become unavailable from the crafting and vehicle menus.

Furthermore, if the knife is *removed* from the belt by being explicitly `i`nserted into another container (such as my backpack), the belt's qualities *remain* unavailable for crafting and vehicles, even though its sheath is empty.

**Comment by wapcaplet** [comment]
> Now that the tool holding containers are nested containers, this is no longer an issue, right?

I see now what I did not notice when retesting this before - what was formerly known as the "survivor utility belt" was obsoleted in #45302 and replaced with the item named `survivor belt` (id `survivor_belt_notools`), which no longer has any tool qualities to begin with. So this bug is indeed no longer valid, since the only affected item is obsolete and cannot appear in the game anymore.

The `survivor_belt` requirement still appears in some recipe requirements; those should also be removed.
