### ISSUE TITLE
Czech Translation

### ISSUE THREAD

**Issue by MvC-182** [CleverRaven/Cataclysm-DDA#40974]
Hello all,

sorry to bother you all with this, but I was advised on the Discourse to ask here instead.

Would it please be possible to make the Czech language available for translation on CDDA's Transifex? Czech is not available as a language as of now and my request to have it added, as advised by the translation readme.md, went unanswered to this day.

I would be very grateful if anybody could help me with this. Assuming, of course, that a Czech localization is needed at all :-)

Thank you all in advance,

M.

Game version: Does not matter

Operating system: Whichever

Tiles or curses: As you like it

Mods active: Given the current nonexistent state of the translation, probably none.

**Comment by ZhilkinSerg** [comment]
CC: @BrettDong

**Comment by MvC-182** [comment]
@ZhilkinSerg Thank you!

**Comment by BrettDong** [comment]
Czech is now added on Transifex.

**Comment by anothersimulacrum** [comment]
Looks like this is resolved then.

**Comment by MvC-182** [comment]
Indeed it is! Thank you all for your help and assistance.

Well, let us get cracking then, shall we.

M.
