### ISSUE TITLE
NPCs won't obey commands

### ISSUE THREAD

**Issue by rockygr** [CleverRaven/Cataclysm-DDA#40980]
# Describe the bug

 NPCs won't follow the combat commands, specifically the engagement rules. NPCs will always charge an enemy, regardless of your settings and (C)hat commands.

# Steps To Reproduce

1. Start a game on a map with the "Starting NPCs spawn" set to always.
2. Convince the NPC to join you.
3. Set their combat>engagement rules to "don't fight unless your life depends on it.
4. Roam around to find a hostile NPC, like a zombie, and run away. Your NPC will charge the zombies, ignoring your command.

# Expected behavior

 NPCs would ignore enemies and flee with you, only fighting if they're surrounded or grabbed.

# Versions and configuration

 OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-2702-ge4d9a10 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Stats Through Kills [stats_through_kills]
]

 - OS: Windows 7
 - Game Version: 0.E-2702-ge4d9a10 (tiles) (experimental)
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Stats Through Kills [stats_through_kills]

**Comment by mlangsdorf** [comment]
NPCs consider monsters next to them as a "your life depends on it" issue.  You want the "follow close" command, which is also bugged at this time.
