### ISSUE TITLE
Problem with putting items into inventory - H&K MP7A2 Example

### ISSUE THREAD

**Issue by Fadragnir** [CleverRaven/Cataclysm-DDA#40988]
Game version:
0.E-2475-g8640704 (tiles)
Operating system:
Win 10 64bit
Tiles or curses:
tiles
Mods active:
DDA
Disable NPC Needs
Secronom 
Blaze Industries
CRIT Expansion Mod
Magiclysm
Bootleg Walkers 
Craft Ammo Mags & Belt Links 
PKs Rebalancing
Alternative Map Key
Mining Mod
My Sweet Cataclysm
Mythical Martial Arts
Graphical Overmap
Graphical Overmap Magiclysm
sees-player icon, HitButton_iso
sees-player icon, retrodays
No Rail Stations
Compatible Nimian Manufacture Guns
Jury-Rigged Robots
Fuji's Military Proffession Pack
Mutation Changes
SpeedyDex
Stats Through Kills
Stats Through Skills
### Expected behavior
I can put my H&K MP7A2 to inventory into my MOLLE pack.
### Actual behavior
I can't
I can only wield it
### Steps to reproduce the behavior
Find a H&K MP7A2
Try to pick it up.
Wield it.
Try to insert it to a MOLLE pack.
H&K MP7A2 is missing on the list.

There's also a problem with putting canned food or other containers to inventory. I have to use insert option of my backpack

![image](https://user-images.githubusercontent.com/51527809/83355200-30d8f680-a35e-11ea-9fe9-00620d8c358e.png)
![image](https://user-images.githubusercontent.com/51527809/83355209-45b58a00-a35e-11ea-90ac-dbf32f2eea26.png)

[Fetters Hot Springs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4707809/Fetters.Hot.Springs.zip)

**Comment by KorGgenT** [comment]
can you show screenshots of the iteminfo of the molle pack and the gun, showing the available space in the molle pack and the size and length of the gun

**Comment by Fadragnir** [comment]
Right, weapon is too long.
But it's the definition of being "compact" is a little incorrect when
I can put 6in RM298 HMG to my backpack and a flamethrower.

![image](https://user-images.githubusercontent.com/51527809/83401474-1f96f500-a405-11ea-9468-0fe2fe18bbbc.png)
![image](https://user-images.githubusercontent.com/51527809/83401525-3b020000-a405-11ea-9a8c-8d20ed1f5731.png)
![image](https://user-images.githubusercontent.com/51527809/83401755-d2ffe980-a405-11ea-811e-6582f637195b.png)
![image](https://user-images.githubusercontent.com/51527809/83401805-e9a64080-a405-11ea-87a8-56606cf0eaed.png)

**Comment by KorGgenT** [comment]
all right, so trying to put an item that is too long for the pocket is working as expected.
