### ISSUE TITLE
Mr. Stem cell issue

### ISSUE THREAD

**Issue by Retoet** [CleverRaven/Cataclysm-DDA#40987]
Describe the bug

Whenever I try to create a new custom character the game crashes back to the main menu.

Steps To Reproduce

1. Download latest experimental build
2. Create a custom character after selecting mods/creating a world

Expected behavior

I'm able to access the character creation menu.

Versions and configuration

I'm using experimental build 12716
 - OS: Windows 10
 - Game Version: 0.E-2633-g6a45cf7
 - Graphics version: Retrodays
 - Ingame language: English
 - Mods loaded: "dda",
  "secronom",
  "aftershock",
  "aft",
  "Arcana",
  "battle_maid",
  "crt_expansion",
  "darkskies",
  "EngineeringEssentials",
  "magiclysm",
  "Nechronica_Redux",
  "mutant_npcs_10492",
  "psychiclysm",
  "collectablemod",
  "XEAS",
  "adv_gear",
  "advtech",
  "a_mutated_arsenal",
  "anti_fungal_gears",
  "ArmUpPAUtil",
  "ArmUpSurvEx",
  "arsenal_breach",
  "modular_turrets_remake",
  "civilian_salvaged_robots",
  "robot_automation",
  "bioco",
  "Bionic_Space_Expander",
  "bio_recipes",
  "Bootleg_Walkers",
  "camping_tools",
  "canals",
  "CBM_Arms",
  "CIVILIANPOWAAA",
  "climate_defying_farming",
  "powder_disinfectant",
  "dried_fruits",
  "Medieval_Stuff",
  "Dumb Sabaton Memes Mod",
  "Alchemic_Bomb_ALC",
  "fallout",
  "fern mod",
  "antifunguskit",
  "guncotton",
  "incinerator",
  "eps_cbm",
  "light_ammo",
  "Mad-Cyber-Science",
  "materials_plants",
  "metal_elemental",
  "demon_spider_a",
  "Pix's Shit",
  "portable_cooler",
  "Power_Armor_Additions",
  "pressure_weapon",
  "offal-sausage",
  "futurearmory",
  "beamswordmod",
  "service_weapon",
  "SM",
  "shardstuff",
  "shardstuffgoat",
  "Survivors_Lost_item",
  "surv_crowbar",
  "CerealMod",
  "VermilionMod",
  "thermal_ups",
  "with_extra_mushrooms",
  "can_mod",
  "your_automation",
  "crazy_labs",
  "DracoDogMod",
  "DracoPigMod",
  "modular_turrets",
  "modular_turrets_no_blacklist",
  "Cata++",
  "DinoMod",
  "GOV_BANDITS",
  "jury_rigged_robots",
  "PK_REBALANCE",
  "porawep",
  "Salvaged_Robots_10511",
  "vamp_stuff",
  "MGCPatch",
  "Youkai_Disco",
  "alt_map_key",
  "convenientconstructions",
  "crazy_cataclysm",
  "crazypets",
  "even_more_mutations",
  "fast_healing",
  "Mining_Mod",
  "monstergirl_professions",
  "more_survivor_stuff",
  "my_sweet_cataclysm",
  "mycus_tomodati",
  "MMA",
  "sarcophagi_access",
  "makeshift",
  "add_mutant",
  "toki_sillyclasses",
  "vamp_stuff+arcana",
  "basement_extension",
  "P_Caches",
  "Dorf_Life",
  "more_locations",
  "FujiStruct",
  "More_crops",
  "morlock_village",
  "randomized_mall",
  "water_towers",
  "whaleys_tallbuild",
  "deoxymod",
  "blazemod",
  "Heavy miners",
  "shrub_mod",
  "Tanks",
  "necromancy",
  "Graphical_Overmap",
  "Graphical_Overmap_Fujistruct",
  "Graphical_Overmap_Magiclysm",
  "Graphical_Overmap_More_Locations",
  "Urban_Development",
  "Graphical_Overmap_Urban_Development",
  "sees_player_hitbutton",
  "ProjectKawaii",
  "Red's Odd Additions",
  "sci_turret",
  "shardsOtherStuff",
  "Touyou",
  "Touhou",
  "xtal",
  "no_religious_Texts",
  "No_Acid_Zombies",
  "No_Explosive_Zombies",
  "No_Gigantic_Naked_Mole-Rats",
  "No_Shady_Zombies",
  "No_Smoker_Zombies",
  "ZSFIXED_cddaxp",
  "temp_effects_reduced",
  "stats_through_kills",
  "speedydex",
  "speedydexbuffs",
  "novitamins",
  "shinigamimod",
  "wet_morale_removed",
  "psychopath_morale",
  "no_reviving_zombies",
  "Odds_N_Ends",
  "necro_find",
  "Nonperishable_Overhaul",
  "stamina_pool_buff",
  "more_char_creation",
  "fuji_mpp",
  "stamina_regen_buff",
  "no_npc_food",
  "RL_Classes",
  "winning_dda",
  "StatsAreBullshit",
  "Anesthesia_Crafting

Additional context

src/main_menu.cpp:909 [bool main_menu::new_character_tab()] Error: line 87:66: invalid enumeration value

        "7": {
          "name": "Mr. Stem Cell",
          "options": [ { "name": "Stem Cell Treatment", "action":
                                                                 ^
                                                                  "stemcell_treatment" } ],
          "failures": [ { "action": "alarm" } ]
        }

[debug.log]
(https://github.com/CleverRaven/Cataclysm-DDA/files/4707524/debug.log)

**Comment by Fris0uman** [comment]
Mr stem cell doesn't exist anymore, looking at the lenght of your modlist one them is probably tries to use it which makes the game unhappy.

**Comment by Night-Pryanik** [comment]
It's definitely not vanilla issue.

**Comment by DrPariah** [comment]
For anyone else who stumbles on this issue, it's Touhou that's the root cause of this. The Forever Pavillion map JSON references Mr Stem Cell.
