### ISSUE TITLE
Segmentation fault on examining a few specific vehicles (Atomic SUV/Fire Engine/Survivor's Militarized RV)

### ISSUE THREAD

**Issue by Hauntmachine** [CleverRaven/Cataclysm-DDA#40991]
# Describe the bug

When examining an Atomic SUV that I found, upon examining the vehicle which normally takes you to the vehicle customization screen, my game crashes with a Segmentation fault every time. Every other vehicle I've come across has enabled me to examine it just fine. I've experimented by debug spawning in a variety of vehicles - including Atomic SUV's, but they all work just fine. It's just the Atomic SUV that I came across that's giving me an issue. 

EDIT: It seems to be Atomic SUV's that I find naturally on the map are the issue. I found another one just teleporting around the map, and it gives me the same problem as the other Atomic SUV did. Spawned in Atomic SUV's are fine.

2nd EDIT: Creating a new world from scratch and finding/examining an Atomic SUV produces the same results.

3rd EDIT: The "Fire Engine" and "Survivor's militarized RV" vehicles are also giving me the same crash if I find them naturally. Spawning the vehicles in through debug menu enables me to examine them as normal.

# Steps To Reproduce

1. Find a naturally spawned Atomic SUV ingame. 
2. Press [e] on Atomic SUV
3. Press [e] again to examine the vehicle
4. Crash

# Expected behavior

Entering the vehicle customization menu. 

# Screenshots

![image](https://user-images.githubusercontent.com/66216947/83358752-aaafb680-a343-11ea-8f01-326e5bc8b865.png)

# Versions and configuration

OS: Windows 10
Version: 0.E-2733-g6a45cf7
Graphics version: Tiles
Ingame language: English
Mods loaded: Aftershock, Dark Days Ahead, Disable NPC Needs, Secronom, Arcana and Magic Items, Blaze Industries, C.R.I.T Expansion Mod, Magiclysm, XEAS, No Freeze, DinoMod, Cataclysm++, More Survivor Stuff, My Sweet Cataclysm, Mythical Martial Arts, No Rail Stations, Graphical Overmap, Graphical Overmap Magiclysm, Mutation Changes, Tankmod: Revived. 
# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4708092/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4708095/debug.log)

**Comment by Hauntmachine** [comment]
My issue seems similar to that of #40843

**Comment by anothersimulacrum** [comment]
Yeah, looks to be a duplicate. But thanks for the report!
