### ISSUE TITLE
`i`nsert-ing partial stacks of items duplicates items

### ISSUE THREAD

**Issue by mutability** [CleverRaven/Cataclysm-DDA#41004]
# Describe the bug

When `i`nserting stackable items into a container, selecting less than the full number of items takes the correct number of items from the source stack, but inserts the full stack into the container, duplicating items.

# Steps To Reproduce

1. Create a test character, drop all items/clothes
2. Spawn and wear cargo pants
3. Spawn and drop 20 scrap metal
4. `i`nventory -> cargo pants -> `i`nsert -> `10` `right-arrow` scrap metal.
Shows `ITEMS TO INSERT: 10 of 20 scrap metals (20)`.
5. Now there is 10 scrap metal left on the ground, and __20__ scrap metal in inventory.

# Expected behavior

10 scrap metal on the ground, 10 scrap metal in inventory.

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch; Distributor ID: Ubuntu; Description: Ubuntu 18.04.4 LTS; Release: 18.04; Codename: bionic; 
- Game Version: 0.E-2607-ga3c5c682ad-dirty [64-bit] (upstream bd62ef6ad96c6c828f996b2e03b22f1b795bec6e)
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by stopple** [comment]
encountered this issue in Game Version: 0.E-3894-g4929649 [64-bit]
