### ISSUE TITLE
Cannot `i`nsert items if the _total_ item stack volume is too large for any pocket

### ISSUE THREAD

**Issue by mutability** [CleverRaven/Cataclysm-DDA#41005]
# Describe the bug

When `i`nserting items into a container, item stacks where the total item stack volume is larger than the largest pocket are not available for selection, even if less than the full stack would fit.

# Steps To Reproduce

1. Create test character, drop items/clothes, move away.
2. Spawn and wear cargo pants
3. Spawn and drop 30 scrap metal
4. `i`nventory -> cargo pants -> `i`nsert items
5. no items are available for selection.

If there is <= 28 scrap metal on the ground (28 scrap has volume 0.70L, the largest pocket available), it becomes available for selection.

# Expected behavior

The stack of 30 scrap metal should be available for selection, limited to inserting at most 28 of 30.

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch; Distributor ID: Ubuntu; Description: Ubuntu 18.04.4 LTS; Release: 18.04; Codename: bionic; 
- Game Version: 0.E-2607-ga3c5c682ad-dirty [64-bit] (upstream bd62ef6ad96c6c828f996b2e03b22f1b795bec6e)
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by kevingranade** [comment]
This has been fixed, the stacks are split now.
