### ISSUE TITLE
AIM miscounts items in inventory

### ISSUE THREAD

**Issue by mutability** [CleverRaven/Cataclysm-DDA#41008]
# Describe the bug

The advanced inventory item count for carried items does not match the actual number of items carried in some cases.

# Steps To Reproduce

1. create test character, drop all items/clothes
2. spawn and wear cargo pants
3. spawn 10 rags
4. Look in `i`nventory, confirm there are 10 rags carried
5. Look in '/' (AIM) -> 'i'nventory. Only 9 rags are shown.
6. Move rags one at a time to the ground using the AIM.
7. After moving 8 rags, the AIM shows one rag remaining (blank "amt" column) in inventory, and 8 rags on the ground.
8. After moving the 9th rag, the AIM still shows one rag remaining, and 9 rags on the ground.

# Expected behavior

The item count shown in AIM should be 10, not 9.

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch; Distributor ID: Ubuntu; Description: Ubuntu 18.04.4 LTS; Release: 18.04; Codename: bionic; 
- Game Version: 0.E-2607-ga3c5c682ad-dirty [64-bit] (upstream bd62ef6ad96c6c828f996b2e03b22f1b795bec6e)
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by FeepingCreature** [comment]
The AIM code does some wacky linked list logic that's bugged for stacks. I'll refactor it completely when I get home in an hour.
