### ISSUE TITLE
Inventory / AIM do not merge display of identical items in separate pockets

### ISSUE THREAD

**Issue by mutability** [CleverRaven/Cataclysm-DDA#41009]
# Describe the bug

If the same stackable item is carried in two (or more) different pockets, two (or more) entries for the item appear on `i`nventory / in the AIM. 

# Steps To Reproduce

1. Create a test character, drop all items/clothes
2. Spawn and wear cargo pants
3. Spawn and drop 500 thread
4. Pick up 250 thread.
5. Pick up 250 thread.
6. Check `i`nventory. There will be two entries for `thread (250)`, and the cargo pants are described as `cargo pants with 2 items`.
7. Check AIM. There will be two entries for thread.
8. examine the cargo pants. The two separate thread stacks are in different pockets.

# Expected behavior

`i`nventory / AIM should merge identical item stacks into a single displayed entry even if carried in separate pockets. As it stands the extra entries don't give more information (you can't, for example, determine which pocket they're in) and you can't really do anything useful with them that you couldn't do with a single entry, and it's not obvious that the reason for the duplication is that they're in different pockets.

(Calling this a bug because it's a UI regression; it could also be fixed by enhancing the UI to provide more context to distinguish the two apparently redundant entries)

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch; Distributor ID: Ubuntu; Description: Ubuntu 18.04.4 LTS; Release: 18.04; Codename: bionic; 
- Game Version: 0.E-2607-ga3c5c682ad-dirty [64-bit] (upstream bd62ef6ad96c6c828f996b2e03b22f1b795bec6e)
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by KorGgenT** [comment]
this is not a bug since the two items in different pockets are in different locations and can have different access times.

**Comment by mutability** [comment]
Ok, but the current display tells the player nothing about that, so it's mostly theoretical. If you're going to distinguish items in different pockets, then they have to be _distinguished_ somehow, or how is the player going to choose which item to manipulate?

**Comment by mutability** [comment]
Here's an example of what I mean:

![Screenshot from 2020-06-01 22-42-08](https://user-images.githubusercontent.com/3055062/83420541-5dbe0400-a459-11ea-84aa-567bdb7f22b8.png)

Based on that screenshot - what's the difference between the two lots of asprin? What about the two lots of multivitamins?

(There probably _is_ a difference with access time for the multivitamins, since one lot is in a bottle and the other is loose in clothing somewhere - but I can't tell which is which from the inventory display)

**Comment by KorGgenT** [comment]
would it really be good UX to put the "activation cost" here? (wield cost) that's the question we really need to answer. and i don't mean a personal opinion, but if it's objectively good UX

**Comment by kevingranade** [comment]
I think it's necessary to tell people which instance of duplicate items to interact with.

**Comment by mutability** [comment]
> would it really be good UX to put the "activation cost" here?

Identifying the containing pocket might be a better option? (Not sure how you'd handle nested pockets without a lot of verbosity, though)
