### ISSUE TITLE
Game unclosable after hibernation or being left alone too long

### ISSUE THREAD

**Issue by cirops** [CleverRaven/Cataclysm-DDA#41019]
# Describe the bug

I've experienced this a few times at this point, starting like 2 years ago. Basically, if the computer goes into hibernation and goes back, or sometimes even letting the game on and leaving for 1 hour or 2, when I come back the game hangs and the only way I can get rid of it being deadlocked is by restarting the whole OS. I can't reproduce this reliably, as It only happens very occasionally.

# Steps To Reproduce

1. Hibernate your OS or let it sit for a few hours.
2. Games enters deadlock and is unclosable.

# Expected behavior

Game should be closable at least by killing the task on windows.

# Versions and configuration

OS: Windows
OS Version: 10.0 1903
Game Version: 0.E-1477-g8cea0fc [64-bit]
Graphics Version: Tiles
Game Language: English [en]
Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food]
]

# Additional context

I've done a bit of research into absolutely unclosable/deadlocked programs on Windows, and microsoft's support forum states that killing the process on the task manager is the most hardcore way of closing a program, and if that doesn't work there is some effed up connection from the process to some buggy driver in the os, which causes the driver to go unresponsive/deadlocked as well. This to me means it is very low-level, resource-handling part  of the game that I don't have the slightest idea of how it works by looking at the code.

I can't even generate a crash log because the game simply dies and comes back as an unkillable zombie. 

An additional piece of info, this has never happened to me on Linux, so it has something to do with how windows deals with the cdda process (or vice-versa).

**Comment by kevingranade** [comment]
I can only imagine something in SDL, either video or audio is acquiring a
resource that causes this.
