### ISSUE TITLE
Tool-rigs (welder, kitchen) attached to vehicles claim to have 0 charges

### ISSUE THREAD

**Issue by LordKaaven** [CleverRaven/Cataclysm-DDA#41018]
# Describe the bug

When  directly (e) using vehicle tool-rigs such as Kitchen Unit or Vehicle Welding Rig, the game claims that they have zero charges, even when the vehicle is properly powered via a charged battery and can be used normally indirectly, for crafting.  

# Steps To Reproduce

1. Create a functional, powered vehicle with a tool-rig, ie. Kitchen Unit
2. Try to (e) use it to activate it (ie. to activate it's Hotplate)
3. There game claims the tool has no charges.

# Expected behavior

The in-built tool should activate and consume charges from vehicle's battery

# Versions and configuration

    OS: Win 7
    Game Version: 0.E 2769-gf387ce8
    Graphics version: Tiles
    Ingame language: English

    Mods loaded: DDA, Disable NPC Needs, Blaze Ind., Magiclysm, No Rail Stations, Graphical Overmap, Graph. Overmap Magiclysm, No Fungal Monsters, Stats Through Skills

**Comment by CptFail92** [comment]
I think the problem is in vehicle_use.cpp but it's going to take me a lot of head scratching to figure it out. Not going to make a PR until I have a clue. Just commenting in case anyone smarter than me wants to drop a tip.

**Comment by throttlekitty** [comment]
0.E-3583-gf76836a

Noting that on this build, trying to examine/use the welding rig gives a message that the healing item isn't compatible with my biology.
