### ISSUE TITLE
Loading save from pre-NC build after updating to post-NC build removes some items' contents

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#41015]
# Describe the bug

Loading save made in 10614 into latest experimental (currently 10718) removes "charges" from some items. At the moment the list is:
- cash cards, they all become 0$ worth;
- welding tanks, both small and large, they get from full to 0/80 and 0/240 welding gas;
- flamethrower fuel tanks also get to 0 charges;
- vehicle turrets lose their ammo belts (M60 and M2HB, at least);
- guns' magazines vanish into thin air. Note that magazines not loaded into guns keep their contents and do not vanish (well, except aforementioned FT tanks).
- USB drives with software become USB drives with none.

# Steps To Reproduce

- make a save in ye olden version, or just in 0.E stable
- wish for some of those items
- or make a vehicle with a turret and load it with ammo belt
- update to latest experimental
- behold the mass item extinction.

# Expected behavior

Items keeping their contents.

# Versions and configuration
- OS: Windows 7
- Game Version: 0.E-2769-gf387ce8 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by RDru** [comment]
I want to add to the list:
- anesthesia kits
- lighters
- matchboxes
- combat armor and such, probably every item that uses plutonium charges
Also I got some food containers "with none" after updating.

**Comment by molkemon** [comment]
The zombie blood kit for the quest which I had a save with zombie blood in it now also says "with none"
