### ISSUE TITLE
All clothes fully protect from radiation

### ISSUE THREAD

**Issue by molkero** [CleverRaven/Cataclysm-DDA#41023]
# Describe the bug

All clothing fully protects from radiation if wearing power armor suit or power armor helmet.

# Steps To Reproduce

1. Start game.
2. Check description on some clothes.

# Expected behavior

Only the power armor suit and power armor helmet would work like this.

# Screenshots

![Screenshot_2020-06-01_23-44-41](https://user-images.githubusercontent.com/49575273/83453254-d2e20700-a462-11ea-908d-277e4d2b5f59.png)
![Screenshot_2020-06-01_23-53-59](https://user-images.githubusercontent.com/49575273/83453614-792e0c80-a463-11ea-957b-d3a93ba55ce1.png)

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 20.0.1; Codename: Lysia; 
- Game Version: 0.E-2769-gf387ce890a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by wapcaplet** [comment]
Thanks for reporting - I know exactly what caused this, and who (it was me). Fix incoming shortly.
