### ISSUE TITLE
Can `d`rop raw liquids directly into vehicle cargo

### ISSUE THREAD

**Issue by mutability** [CleverRaven/Cataclysm-DDA#41029]
# Describe the bug

`d`ropping a raw liquid when standing on a vehicle part that can hold items results in the raw liquid being placed into the part; it's then impossible to remove the liquid.

# Steps To Reproduce

1. spawn a cube van
2. spawn water in a container (`plastic bottle of water`). Wait for it to unfreeze (unrelated bug..)
3. stand on the cube van seat
4. `d`rop -> `water (2)`. (`"You put your water in the Cube Van's seat"`)
5. now there is uncontained water in the vehicle seat, where it should not be.

The water is not dirty, but is considered "spilt" and can't be moved via AIM ("you can't pick up a liquid") and most other interactions fail.

Trying to pick up the water results in it silently being moved to the ground.

# Expected behavior

Dropping a raw liquid when on a cargo part should either be forbidden, or should behave like `U`nloading the container (i.e. prompt to pour onto ground etc).

# Versions and configuration
- OS: Linux
    - OS Version: LSB Version: core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch; Distributor ID: Ubuntu; Description: Ubuntu 18.04.4 LTS; Release: 18.04; Codename: bionic; 
- Game Version: 0.E-2763-gcef737c3ae-dirty [64-bit] (upstream bd62ef6ad96c6c828f996b2e03b22f1b795bec6e)
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by zeropol** [comment]
Replicated on 0.E-9859-g661c627 [64-bit]
Except when trying to picking the water up, it is not moved to the ground and stay in the cargo ( tried with cargo space ).

**Comment by Qrox** [comment]
I believe you can remove the liquid using a mop?
