### ISSUE TITLE
Translation strings duplication

### ISSUE THREAD

**Issue by CountAlex** [CleverRaven/Cataclysm-DDA#41035]
# Is your feature request related to a problem? Please describe.
Some entries extracted for translation have duplicating keys - such as `Military`, `Speed`, `Armor`.
The resulting translation may vary depending on context but there can only be used a single variant - meaning that it would be correct in one case and wrong/weird/confusing in other(s).

# Describe the solution you'd like
A way to have duplicating entries separeated. For example male/female professions and their respective descriptions are separated with a comment. Similar application of comments to duplicates would help increase translation quality.

# Describe alternatives you've considered
#23434 would help a lot if done right

# Additional context
If adding comments to duplicates will be used, it would create new entries for every duplicate as far as I understand Transifex processing. So adding commentary to every entry instead of duplications only would most likely make all progess be lost. That's not a good outcome, obviously.

**Comment by jbytheway** [comment]
There are two separate things used for translations: comments and contexts.  You seem to be confusing the two.  Contexts separate the string into two different keys for translation.  Comments do not.  In the source code contexts are added using `pgettext` (or related functions) and comments are added via `//~`.  Contexts should already be supported in any places where we extract strings for translation.  Feel free to add contexts where they seem necessary.  I don't think a global solution is necessary beyond that.

I don't think #23434 would help.  Even with multiple files, there will still be only one universe of keys.

**Comment by CountAlex** [comment]
You are right, I mixed that up. However, I am not sure how this exactly works so I wil figure this out and try to clean up duplicating cases with comments.
