### ISSUE TITLE
Lava Bomb spell is incorrectly classless

### ISSUE THREAD

**Issue by Morat2255** [CleverRaven/Cataclysm-DDA#41043]
# Describe the bug

The Lava Bomb spell is classless in game.

# Steps To Reproduce

1. debug in the Scroll of Lava Bomb
2. Attempt to learn the spell. Note that reading the scroll lists it as a classless spell.
3. Wait until character finishes learning spell. Note that there is no warning message about being locked in to the earthshaper class and restricted from technomancer spells.

# Expected behavior

The Lava Bomb spell is described in Earthshaper.json, and the Scroll of Lava Bomb entry in spell_scrolls.json includes the comment "//": "Earthshaper spell", all of which seems to indicate that the lava bomb spell is intended to fall under the Earthshaper school.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2769-gf387ce8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA],
    sees-player icon, retrodays [sees_player_retro],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Alternative Map Key [alt_map_key],
    No Fungal Monsters [No_Fungi],
    Modular Turrets Remake [modular_turrets_remake],
    Civilian Salvaged Robots [civilian_salvaged_robots],
    Automations [robot_automation],
    DinoMod [DinoMod],
    Blaze Industries [blazeindustries]
]

# Additional context

Should be an easy fix. I think just adding the line

"spell_class": "EARTHSHAPER",

in the relevant entry in earthshaper.json should fix it.

**Comment by Morat2255** [comment]
How do I tag this as mod:magiclysm?

**Comment by anothersimulacrum** [comment]
You can't apply labels, so you just need to ask for someone to.
