### ISSUE TITLE
Game uses 1 full CPU core while I do nothing

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#41058]
# Describe the bug
CDDA uses one full core even if doing nothing. 

# Steps To Reproduce
On my computer, I just launch my current save and the CPU usage rises to 23-25% and stays there (4 cores processor). 

# Expected behavior
Use close to nothing when doing nothing. 

# Versions and configuration
- OS: Linux
    - OS Version: LSB Version: core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch; Distributor ID: Ubuntu; Description: Ubuntu 18.04.4 LTS; Release: 18.04; Codename: bionic; 
- Game Version: 0.E-1477-g8cea0fc [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Stats Through Skills [StatsThroughSkills],
    Alternative Map Key [alt_map_key],
    No Fungal Monsters [No_Fungi]
]

# Additional context
I use Build number : #10614 (the last one before nested inv) from here https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-jenkins-b10614.

EDIT: save attached + config
[Rockypoint.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4726364/Rockypoint.zip)
[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4726379/config.zip)

**Comment by ZhilkinSerg** [comment]
Attach your save please.

**Comment by matt32106** [comment]
Done

**Comment by mark7** [comment]
Past comment of mine that may be relevant.

https://github.com/CleverRaven/Cataclysm-DDA/issues/22375#issuecomment-459858420

**Comment by matt32106** [comment]
> Past comment of mine that may be relevant.

Yes, looks really like the same issue.

**Comment by BrettDong** [comment]
Does CPU usage improve if you turn off SCT animation?

**Comment by Night-Pryanik** [comment]
I'm closing this for now, on 0.F-10939 on my rig in idle mode the game consumes ~1.5% of CPU. If this is still an issue, ping me to reopen.
