### ISSUE TITLE
Arithmetic Error (using Transfer All option)

### ISSUE THREAD

**Issue by evankimori** [CleverRaven/Cataclysm-DDA#41052]
CTD when attempting to used (,) Transfer All option with current game and mod configuration.

# Steps To Reproduce

Have items on the floor, open Advanced Inventory (/), change item destinations from (A)ll to a direction and attempt to use the (,)Transfer All option.

# Screenshots
![arithmetic error](https://user-images.githubusercontent.com/43046067/83671185-44749f00-a5a2-11ea-9486-0cd0ba5a3aa7.png)

# Versions and configuration
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4725278/debug.log)

 - OS: Win10x64
 - Game Version: 10725
 - Graphics version: [Tiles or Terminal]
 - Ingame language: English
 - Mods loaded:
  "dda",
  "magiclysm",
  "Mining_Mod",
  "No_Fungi",
  "stats_through_kills",
  "StatsThroughSkills",
  "Graphical_Overmap",
  "classic_zombies",
  "Graphical_Overmap_Magiclysm"

Crash: if your problem refers to a crash, please add the following files to the "Additional Context" paragraph:
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4725277/crash.log)
[Brazos Country_4.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4725281/Brazos.Country_4.zip)

**Comment by KorGgenT** [comment]
I assume you mean in advanced inventory?

**Comment by evankimori** [comment]
> I assume you mean in advanced inventory?

Whoops. That's what I get for writing report whilst sleepy. Correcting now.

**Comment by hexagonrecursion** [comment]
I could not reproduce the crash with clang address and undefined behavior sanitizers. Note: I do not have the Mining_Mod mod

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 0.F-2004-gada3852d39 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    No name () [],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Graphical Overmap [Graphical_Overmap],
    Dark Days of the Dead [classic_zombies],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm]
]

**Comment by evankimori** [comment]
I think this issue is Closed at this time anyway. No one else has reported it since my last update and we've long moved past this game version.

Closing this issue as it cannot be replicated currently. If anyone experiences it: feel free to PM to reopen discussion.
