### ISSUE TITLE
Hoofs freezing

### ISSUE THREAD

**Issue by TheMasterGear** [CleverRaven/Cataclysm-DDA#41066]
#Hoofs freezing
A clear oversight that hoofs will get just as cold as going barefoot normally. Plus you can't wear shoes, only things like blankets will work.

# Steps To Reproduce
1. Start your world during the winter or early spring.
2. Make a player with a starting trait with hoofs, like a lab experiment.
3. Now there's no way to keep your hoofs from freezing off.

# Expected behavior

Having hoofs act like wearing shoes.

![shot](https://user-images.githubusercontent.com/60374171/83706627-faada800-a5e5-11ea-9991-5fa92b47e13c.png)

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-2827-g1c8edcc [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    <color_light_red>Secronom</color> [secronom],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Mythical Martial Arts [MMA],
    Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    MSX Indicators: REMIX [UDP_REMIX_INDICATORS],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex]

**Comment by cirops** [comment]
Hooves give you 4 points, extra melee attacks and remove the barefoot penalty to speed, so the "freezing your feet to death in winter, deal with it" seems to be the intended downside.

**Comment by TheMasterGear** [comment]
> 
> 
> Hooves give you 4 points, extra melee attacks and remove the barefoot penalty to speed, so the "freezing your feet to death in winter, deal with it" seems to be an intended downside.

But do you really ever see hoses have their hoofs freeze off? XD

**Comment by cirops** [comment]
That is actually a fair point, Hooved animals rarely freeze their hooves in winter...

I'd suggest: make hooves give just enough insulation to protect from mild winter, and take 1 point away from the negative trait.

**Comment by TheMasterGear** [comment]
I agree, it could even be more points than that.

**Comment by Solusphere** [comment]
You can wear stuff on hooves. Any item with the oversize flag can be worn with them, notably foot wraps. In my recent lab game with a mutant with hooves, cold was a minor issue which I countered by making two pairs of leather foot wraps. Fur foot wraps are better when you can get them giving you a warmth option on par with shoes, albeit much less protective. Any footwear labelled with "XL" works too.

**Comment by kevingranade** [comment]
[Citation needed]

**Comment by Fris0uman** [comment]
> [Citation needed]

Definitly, but naïvely I think that since hooves are not as fleshy and have probably less blood vessels than other bodyparts (at least less than human feet) it would make sense for them to be less sensitive to cold.

**Comment by cirops** [comment]
To add to my  participation in this issue:
About being able to wear the XL stuff, yeah, I forgot about that, which makes Hooves even stronger, leaving only the "I can't wear full body suits nor a few shoes that actually matter" as a negative side for a 4-points negative trait.
Also, about some references on the "Horses don't freeze their hooves in winter", this is one thing I've found:
https://ker.com/equinews/cold-weather-adaptations-keep-horses-comfortable/#:~:text=Though%20horses%20sometimes%20stand%20in,that%20don't%20freeze%20easily.
I realize this is not some definite source like a scientific paper, but I've pieced together the info on this article and my very limited experience with horses in winter RL to infer that they indeed are more resistant to cold than us in their lower limbs in general. I haven't looked into all ungulates, so this is by no means an attempt at a generalization to the whole clade, but as current implementation suggests an orientation to Hooves being cattle-like, I've also found this:
https://www.nptelegraph.com/lifestyle/how-do-animals-deal-with-the-cold/article_0e892f1e-42b6-11e9-bf14-7b5fc0125b69.html#:~:text=Hooves%20are%20basically%20toe%20nails,frozen%20ground%2C%20snow%20or%20ice.

Finally, if the solution I've suggested,   
> make hooves give just enough insulation to protect from mild winter, and take 1 point away from  the negative trait.

were to be implemented, looking at data/json/mutations/mutations.json I haven't found a way to add insulation to specific body parts through json, only to the whole body with **bodytemp_modifiers**. There is the bodypart-separated **wet_protection**.

So in src/mutation_data.cpp we would have to either separate the current full-body
```
    if( jo.has_array( "bodytemp_modifiers" ) ) {
        auto bodytemp_array = jo.get_array( "bodytemp_modifiers" );
        bodytemp_min = bodytemp_array.get_int( 0 );
        bodytemp_max = bodytemp_array.get_int( 1 );
    }
```

to work something like:
```
    for( JsonObject wp : jo.get_array( "wet_protection" ) ) {
        int ignored = wp.get_int( "ignored", 0 );
        int neutral = wp.get_int( "neutral", 0 );
        int good = wp.get_int( "good", 0 );
        tripoint protect = tripoint( ignored, neutral, good );
        protection[bodypart_str_id( wp.get_string( "part" ) )] = protect;
    }
```

**Comment by GroeneAppel** [comment]
So a couple of google searches related to horse hoofs taught me a couple of things:

1. Cold temperatures can harm hooves and cause sore and lameness, this mainly if they wear metal horseshoes:
https://horse-canada.com/magazine/hoof-care/winter-hoof-care-woes/
https://equusmagazine.com/horse-care/prevent-ice-balls

Most harm seems appear from prolonged walking on icey paths, and from snow accumulating under the hooves (mainly due to metal horseshoes), causing sores and even infections. 

Overall I've not seen temperature mentioned as a main issue anywhere. It feels like overall cold should have far less of an effect on hooves, but extended movement should.

2. Hoof boots exist:
https://www.hoofwear.com/
https://www.cavallo-inc.com/

Having hoof boots spawn in stables/farms occasionly wouldn't be a bad idea. For the mutated player having a simple craftable hoof boot would be helpfull too. Perhaps a recipe in a horse magazine?
https://pocketmagscovers.imgix.net/horse-magazine-january-2018-cover.jpg?w=362&auto=format

**Comment by mark7** [comment]
Is it actually the hoof that's getting cold, or the area just above the hoof?  I mean, if one wants to be technical about it, as I recall, the biological analog of the part *above* the hoof is the part that's equivalent to the hand in a human.

https://en.wikipedia.org/wiki/Pastern

> The pastern is a part of the leg of a horse between the fetlock and the top of the hoof. It incorporates the long pastern bone (proximal phalanx) and the short pastern bone (middle phalanx), which are held together by two sets of paired ligaments to form the pastern joint (proximal interphalangeal joint).[1][2] Anatomically homologous to the two largest bones found in the human finger, the pastern was famously mis-defined by Samuel Johnson in his dictionary as "the knee of a horse". When a lady asked Johnson how this had happened, he gave the much-quoted reply: "Ignorance, madam, pure ignorance."[3]

https://en.wikipedia.org/wiki/Fetlock

> While sometimes the fetlock is colloquially referred to as an "ankle", even by horse experts, that terminology is not correct. The fetlock is a metacarpophalangeal joint which corresponds to the human upper knuckle, such as that on the ball of the foot. 

and on the rear legs of the horse, corresponds to the to the upper bones in the human foot:

https://en.wikipedia.org/wiki/Metatarsal_bones

https://en.wikipedia.org/wiki/Skeletal_system_of_the_horse

This shows the bones -- the part equivalent to the human lower arm is marked "radius" and the part equivalent to the human lower leg "fibula".

That being said, I don't suppose that it's actually essential to be technical about it -- just saying that if one desires a "realism explanation" for the existing behavior, that'd seem to me to provide it.
