### ISSUE TITLE
Current gorging system is unrealistic.

### ISSUE THREAD

**Issue by EvgenijM86** [CleverRaven/Cataclysm-DDA#41060]
# Is your feature request related to a problem? Please describe.
It is way too easy to stuff yourself with food to the point you are starting spewing it all out. In real life you kinda know when to stop. It was also like that before the most recent patch, when the game warned that any more and you might throw up. Now you just eat some food until it says full (or even just satisfied), then you stop, do a couple of steps and it says that you engorged, as if you have eaten some construction foam and it expanded in your stomach.

# Describe the solution you'd like
Game warning you like it did before.

# Describe alternatives you've considered
Rolling back gorging penalties completely.

# Additional context
None.

**Comment by kwl01skz** [comment]
Maybe we should add a feature "I don't know I'm full" and use the current code.

**Comment by cthae** [comment]
I want to add to that. Gourmand is something I liked a lot since it protected you from overeating/drinking. It doesn't do so anymore. Not sure if it's a bug or meant to be nerfed.

**Comment by EvgenijM86** [comment]
Some foods are impossible to eat without getting engorged btw. Like cheeseburger, if I am remembering correctly. And if you are engorged you are pretty much guaranteed to throw up.

**Comment by squiddy555** [comment]
from my experience, stomach volumes are unrealistic as well
eating 3 * 0.25L portions makes my character vomit

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/pb-j-causes-you-to-go-from-very-hungry-to-engorged/23997/10
