### ISSUE TITLE
Segfault related to modded gun. (Possible pocket assignment problem during saving/loading)

### ISSUE THREAD

**Issue by Menschheit** [CleverRaven/Cataclysm-DDA#41064]
# Describe the bug
The rifle (shown as "HK417 A2+1") is always generated with an adjustable stock , which disappears after saving and loading (and we will have a "HK417 A2" without "+1" after that). This may cause segmentation fault error if the player has reloaded the original "HK417 A2+1" with a magazine before "Save and Quit".

# Steps To Reproduce
1. Generate(or loot) a HK417 A2 +1.
2. Reload "HK417 A2 +1" with an appropriate magazine. (Skip this step if there is one in it already)
3. Save and Quit. Then load the save file.
4. You will see that the rifle becomes a "Hk417 A2" without any mods. Now `u`nload the gun.
5. The game crashes any time you examine the gun (`i`ventory, `e`xamine and so on) without a magazine in it.

# Expected behavior
The adjustable stock should not disappear, game should not crash.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-2827-g1c8edcc [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
If the "HK417 A2 +1" was kept unloaded before it becomes "HK417 A2" after saving and loading, no crash will occur.

crash.log:
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4726804/crash.log)

debug.log:
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4726805/debug.log)

save file(the nearest gun above can cause crash):
[TEST WORLD.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4726812/TEST.WORLD.zip)

**Comment by CptFail92** [comment]
I get a crash if I unload the RM51 or SIG 552 and then (a)ctivate on this save. It may be related.
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4729113/crash.log)

[Arredondo.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4729132/Arredondo.zip)

**Comment by MikuMiddo** [comment]
In fact,any modified guns ,bow,crossbow or any other modified weapon will make the game Segfault crash after you restart the game then [U]nload them.

**Comment by Menschheit** [comment]
> In fact,any modified guns ,bow,crossbow or any other modified weapon will make the game Segfault crash after you restart the game then [U]nload them.

True, all gun mods are lost after loading, better to stick to my fire axe for now.

**Comment by Menschheit** [comment]
Additional Info:
1. Guns of the same type but with different mods can stack in `i`ventory.

2. Can't find anything about attached gun mods in the save file.
In older version, the attached mods are listed with a "contents" tag after the gun infomation.  

3. Get the massage "error: tried to put an item into a pocket that can't fit into it while loading." after loading saves.
![2](https://user-images.githubusercontent.com/28317565/83809626-1339c300-a6b7-11ea-835b-f00e26b6d76f.PNG)

**Comment by Menschheit** [comment]
Additional Info:
1. The gunmods are written into save only if there is a magazine in the gun. Otherwise all information about mods are lost. 
2. Assume that the gun is always loaded with magazine and we save the game. In the saved file the magazine is assigned with `"pocket_type": 2` ; the gun mods are assigned with `"pocket_type": 3`. Now load the save, and save again immediately. Check the saved file, gunmods are now assigned with `"pocket_type": 4` .

So I think there is sth, wrong with pocket assignment during saving/loading, hope this get fixed soon.

**Comment by meladath** [comment]
Crash occurs here: 
![image](https://user-images.githubusercontent.com/4256844/84658950-94425700-af0e-11ea-9468-ac707f4bf92d.png)

Whilst trying to get the item's name here:
![image](https://user-images.githubusercontent.com/4256844/84658993-a3290980-af0e-11ea-9c10-a7384f3df6b5.png)

Will try to investigate further.

**Comment by Menschheit** [comment]
This PR [https://github.com/CleverRaven/Cataclysm-DDA/pull/41420](url) noly fixes the crash, didn't fix gunmod disappearing.

 

> Crash occurs here as contents are null
> ![image](https://user-images.githubusercontent.com/4256844/84658950-94425700-af0e-11ea-9468-ac707f4bf92d.png)
> 
> Whilst trying to get the item's name here inside item::display_name
> ![image](https://user-images.githubusercontent.com/4256844/84658993-a3290980-af0e-11ea-9c10-a7384f3df6b5.png)
> 
> Will try to investigate further.

This PR [https://github.com/CleverRaven/Cataclysm-DDA/pull/41420](url) only fixes the crash, didn't fix gunmod disappearing.

Actually there are two problems:
1. The contents are "combined" to pockets after loading, but since guns dont have a `"pocket_type": "MOD"` defined in .json so there are some chaos on pocket asignment. I don't know how exactly it is processed (I have no coding experience and the source codes lack comments) but it seems that adding a `"pocket_type": "MOD"` in json file (for all guns) may solved the problem.

2. In savegame_json.cpp
![a](https://user-images.githubusercontent.com/28317565/85206348-c21a0800-b321-11ea-9155-15258f11d2a3.PNG)
The function `item_contents::empty()` just ignores mods. So if there is no magazine or magazine_well in a gun, the gun will be considered as "empty" hence the contents will not be serialized. We need another funtion here to check if an item is really "empty".
