### ISSUE TITLE
ALL liquids fall out of containers when hauled.

### ISSUE THREAD

**Issue by Themorbidmoose** [CleverRaven/Cataclysm-DDA#41076]
# Describe the bug

All liquids fall from containers floor when hauling items.

# Steps To Reproduce

Have any liquid in a container, use the \ to haul everything from one space to another.

1. Have multiple different liquids, sealed and unsealed in different containers on the floor in a basement.
2. Try to haul from one place to another with the backslash shortcut.
3. The containers move but the liquids stay put/spill to the floor.

# Expected behavior

That liquids stay in their containers when hauled with backslash from one tile to another.

# Screenshots 
![screenshot of liquids](https://user-images.githubusercontent.com/66440259/83801539-9bb16700-a6a9-11ea-9de6-c8afa313be63.jpg)

**Comment by 12347654** [comment]
delete your mods

**Comment by wapcaplet** [comment]
Cannot reproduce in 0.E-6518-g8e6077ef45.
