### ISSUE TITLE
Weapon mods disappear on load.

### ISSUE THREAD

**Issue by cthae** [CleverRaven/Cataclysm-DDA#41084]
# Steps To Reproduce

get some mods on any weapon. Save. Load. No mods.

# Versions and configuration

 - OS: Windows 10 
 - Game Version: build 10730
 - Graphics version: [Tiles]
 - Mods loaded: cata++ and a bunch of others. It's been happening to other people too.

**Comment by buildfailedforallplatforms** [comment]
Also, guns that have had their mods disapear crash the game when mag is unloaded

**Comment by wapcaplet** [comment]
Cannot reproduce in 0.E-8292-g00db780b. Gun mods persist across save and load.

**Comment by hexagonrecursion** [comment]
# To reproduce
I tried the following in two versions of cdda:
1. wish for glock 19 and a compact suppressor
2. attach the suppressor to the glock
3. put the glock in a pocket
4. save
5. load

# Old version
Following the above steps successfully reproduces the bug in a865ac0

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 32 (Thirty Two); Release: 32; Codename: ThirtyTwo; 
- Game Version: 0.E-2870-ga865ac0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Most recent build
I could **not** reproduce the bug in the most recent build ad3141d

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 32 (Thirty Two); Release: 32; Codename: ThirtyTwo; 
- Game Version: 0.E-8968-gad3141d-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]
