### ISSUE TITLE
Segmentation Fault Crash when opening inventory

### ISSUE THREAD

**Issue by DalenHealy** [CleverRaven/Cataclysm-DDA#41080]
# Describe the bug

Game crashes, providing a segmentation fault error when trying to open inventory, activate items, or any activity that utilizes items in the players inventory. this began after picking up a shoulder strap.

# Steps To Reproduce

open inventory or try to activate, throw, or reload an item (or any similar action involving the player's inventory)

# Expected behavior

Game should not crash upon taking the stated action

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2844-gede5ff2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm]

# Additional context

- Crash and Debug
[Crash and Debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4733340/Crash.and.Debug.zip)

 - Save file
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4733347/save.zip)

**Comment by enaantd** [comment]
I have a similar problem in my own game and did some investigation. In my case, if I unload a weapon that is in my inventory and then open the inventory, or if I unload a weapon to the ground and then examine the tile or list all items, I get a segfault.

I tried to reproduce in a test world but it didn't crash there, so I spawned a M4A1 in my world to compare it with my own.
The difference is that only one of them has fouling:

![Screenshot_2020-06-08_11-22-55](https://user-images.githubusercontent.com/64151602/84014612-e9182780-a97a-11ea-8179-82d26c96335d.png)

Hence, I think this is related to #41048: unloading a weapon that was obtained before this PR seems to produce a segfault.

**Comment by dsmky117** [comment]
I was having this same problem: my game crashed every time I unloaded my HK416 A5 and then opened my inventory. My gun didn't _appear_ to have any fouling, but it did have gun mods on it at some point but those mods are no longer visible. When I spawned a new gun, it did not have any issues.

Here is how I see the gun in my inventory:
![image](https://user-images.githubusercontent.com/19257672/84345685-fd774280-ab7b-11ea-9f8b-b17f8db2f07e.png)


Here is the cursed gun's data from my character save:
```json
{
    "typeid": "h&k416a5",
    "item_vars": {
        "dirt": "956",
        "magazine_converted": "1",
        "shot_counter": "888.000000"
    },
    "owner": "your_followers",
    "faults": [
        "fault_gun_dirt"
    ],
    "relic_data": null,
    "contents": {
        "contents": [
            {
                "pocket_type": 2,
                "contents": [
                    {
                        "typeid": "stanag20",
                        "owner": "your_followers",
                        "relic_data": null
                    }
                ],
                "_sealed": false
            },
            {
                "pocket_type": 4,
                "contents": [
                    {
                        "typeid": "folding_stock",
                        "item_vars": {
                            "shot_counter": "162.000000"
                        },
                        "owner": "your_followers",
                        "relic_data": null
                    },
                    {
                        "typeid": "acog_scope",
                        "item_vars": {
                            "shot_counter": "162.000000"
                        },
                        "owner": "your_followers",
                        "relic_data": null
                    },
                    {
                        "typeid": "pistol_grip",
                        "item_vars": {
                            "shot_counter": "162.000000"
                        },
                        "owner": "your_followers",
                        "relic_data": null
                    },
                    {
                        "typeid": "suppressor",
                        "item_vars": {
                            "shot_counter": "28.000000"
                        },
                        "owner": "your_followers",
                        "relic_data": null
                    }
                ],
                "_sealed": false
            }
        ]
    }
}
```

**Comment by dsmky117** [comment]
I can confirm that weapon mods are "corrupting" guns when you save and reload. They appear to not have any attachments and segfault either when unloading or after unloading and opening the inventory.

**Comment by wapcaplet** [comment]
I could not reproduce this in 0.E-9737-g511ddcb179. I attached a couple gunmods to a Mosin-Nagant, saved and loaded, and the mods persisted with no errors viewing inventory. Many players use guns and gunmods all the time, and we would have certainly heard more reports of this bug in the last 8 months if it still existed.
