### ISSUE TITLE
Non-makeshift 40x46mm grenades do not provide casings when disassembled.

### ISSUE THREAD

**Issue by Solusphere** [CleverRaven/Cataclysm-DDA#41086]
# Describe the bug

40x46mm  M1006, 40x46mm M433, 40x46mm 576 and 40x46mm M651 do not provide their respective casings when disassembled, despite dropping them when fired.

Weirdly, the M1006 DOES leave behind a single .38 Special casing. 

The makeshift 40x46mm Buckshot, Slug and Flechette rounds do all provide the casings used to make them when disassembled.

# Steps To Reproduce

1: Fire one of the above grenades. Note the casings they leave behind.
2: Disassemble one of the above grenades. They leave behind primers, powder and fuzes, but no casing (except for the .38 casing left by the M1006).

# Expected behavior

Disassembling the grenades should provide the same casing that firing them does, and definitely not a .38 casing.

# Screenshots

None
![image](https://user-images.githubusercontent.com/19789267/83858480-25674000-a74f-11ea-8cc2-3797d18e624d.png)

# Versions and configuration
N/A, using data from latest experimental. Verified ingame.

# Additional context

On a possibly-related note, the M118 and M199 can both be used to craft the various makeshift 40x46mm rounds, but the M195 and M212 can not, and currently have no use ingame. I'm not sure if this is intentional or an oversight.

**Comment by anonchan** [comment]
The M1006 is a less-lethal sponge grenade, which is intended for crowd control. [It should have a 32 caliber casing in it.](https://bulletpicker.com/pdf/TM 43-0001-28, Artillery Ammunition.pdf#page=632)
I'll see what I can do with the JSON to fix that up.

**Comment by anonchan** [comment]
I've made a PR but as it says, haven't tested it yet. I was going to grab the travis CI build to test it but travis is complaining about JSON linting. I don't expect any issues as it looks like it's just a simple JSON edit and I don't see anything wrong, but if someone wants to download and build the latest experimental to verify the fix works, that'd be great.

**Comment by anothersimulacrum** [comment]
As was commented on the PR, you used tabs instead of spaces, and there's a web linter to fix such mistakes.
