### ISSUE TITLE
Grabbing large amounts of items is broken

### ISSUE THREAD

**Issue by cthae** [CleverRaven/Cataclysm-DDA#41083]
# Describe the bug
When you try and [g]rab large amounts of items that won't fit your inventory, you get odd errors.
https://i.imgur.com/66WlzVt.png
https://i.imgur.com/iLBO0Td.png

Also even if it fits the inventory, it still looks very broken: https://i.imgur.com/GXjyxPL.png

# Versions and configuration

 - OS: Windows
 - Game Version: Build 10730
 - Graphics version: Tiles
 - Ingame language: English 
 - Cataclysm++ and a lot of mods from the repo.

# Additional context

This is new. It was totally fine a few days ago. The bug was introduced in the last few builds.

**Comment by anothersimulacrum** [comment]
Related to #40968?

**Comment by cthae** [comment]
Yes, it is related indeed. Only I describe how to get to that lonely aspirin. And yes, you get a segmentation error if you try to do some things with that lonely item that is supposed to be hundreds of it.

I've got segmentation errors when tried to put it in containers or doing other things with it.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-10939.
![изображение](https://user-images.githubusercontent.com/11132525/187441419-367ad4ce-5e9b-4489-bcdf-911045aa2579.png)
