### ISSUE TITLE
Maximum inventory volume is wrong

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#41092]
# Describe the bug

Exactly what it says on the tin - maximum available volume in inventory window shows wrong numbers. Like, way, way off the charts.

# Steps To Reproduce

- to be added later. Probably just put some empty non-rigid container(s?) inside others, that's my current guess.

# Expected behavior

Volume calculations returning correct result.

# Screenshots

![cataclysm-tiles_2020_06_05_21_48_34_328](https://user-images.githubusercontent.com/56833396/83891441-5bb8b580-a777-11ea-899a-160633ea806b.png)
I guess it just summed all of my containers' max possible volumes? Or something?

# Versions and configuration

- OS: Windows 7x64
- Game Version: 0.E-2899-g0ff7d77 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by wapcaplet** [comment]
Do you have other items in your inventory (not ones you are wearing) that also have containing capacity? I think the total includes capacity of everything you are carrying.

For a simpler example, here I am wearing a rucksack with 25-liter capacity, containing the harness, canteen, and survivor suit adding another 16.5 L to the total, even though I am not wearing them:

![image](https://user-images.githubusercontent.com/238395/83930410-b2f95e80-a754-11ea-904b-667bc3020a24.png)

**Comment by GGgatherer** [comment]
Yes, that's probably it. There are some foldable bottles and condoms in my rucksack.

**Comment by meladath** [comment]
![image](https://user-images.githubusercontent.com/4256844/83950981-831a8b80-a826-11ea-85f9-372f7fd4b63e.png)
Commenting out that code fixes this issue and makes the character volume behave as you expect from pre-nested container change. After reading through the code, I think this should be intended behaviour anyway, as you cannot carry the volume of every container COMBINED.
