### ISSUE TITLE
Recipies found only in books that do not spawn.

### ISSUE THREAD

**Issue by Librarymans** [CleverRaven/Cataclysm-DDA#41094]
# Describe the bug

Recipies that are located in books that have not been added to spawn list

Specifically the books You Can Can at home, The Vinegar Maker's Handbook and  others.

# Steps To Reproduce

1.Create new world with large city and Turn item spawn to max.
2.Spawn in missed scenario in library.
3. Spawn clairvoyance artifact for speed.
4. View nearby items. Books not spawning.
5. Teleport around looking for books. Book stores, Other Libraries. Other Stores. Homes.
6. See books do not spawn.

# Expected behavior

Books would spawn somewhere.

# Screenshots

# Versions and configuration

# Additional context

**Comment by Zireael07** [comment]
I don't think this is the correct way to check for spawns. Are the books listed in one of the spawn lists?

**Comment by cirops** [comment]
manual_canning and vinegar_maker are not in any item group.

**Comment by Maleclypse** [comment]
@Maleclypse tagging myself to fix this.
