### ISSUE TITLE
Total/current weight/volume of opened container is wrong

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#41093]
# Describe the bug

It always shows values from main inventory screen, not values of the container.

# Steps To Reproduce

Just make a char with 2 backpacks, put something in each one and open either.

# Expected behavior

It should show values related to the container. I already know total values because to get to the container screen I have to go through the main inventory.

# Versions and configuration

- OS: Windows 7x64
- Game Version: 0.E-2899-g0ff7d77 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by wapcaplet** [comment]
Confirmed in 0.E-2899-g0ff7d773a2. With a backpack holding one item, I see it has a single 15-liter pocket, and the wristwatch takes up 0.25 L, and 0.05 kg. But when I select "open":

![image](https://user-images.githubusercontent.com/238395/83929799-e71f5000-a751-11ea-8ebb-c70b54ca5d97.png)

The popup shows weight (kg) "2.5 / 45.0", and volume (L) "0.50/30.00" - none of these numbers are correct:

![image](https://user-images.githubusercontent.com/238395/83929842-0f0eb380-a752-11ea-95d6-ac7b7454f4a8.png)
