### ISSUE TITLE
Item Get message log shows incorrect information

### ISSUE THREAD

**Issue by SilverTemper** [CleverRaven/Cataclysm-DDA#41115]
# Describe the bug

Picking up items sometimes says I picked up a different number of items.
For instance, I picked up a first aid kit, and it said I'd picked up fifty (can't reproduce), and when I pick up seeds or pills, it says I picked up zero but shows the number of charges correctly.  When attempting to reproduce, four instances of oat seeds appeared as small plastic bottles of multivitamins in log - items received were still oat seeds.

# Steps To Reproduce

1. Spawn in seeds with map editor (Tested with oat seeds, specifically)
2. Collect seeds

# Expected behavior

Collected items should appear in log as one stack each of oat seeds with four charges.

# Screenshots

![Untitled](https://user-images.githubusercontent.com/32205726/83945076-1f687200-a7d6-11ea-8bfc-685fe6d02038.png)
![Untitled](https://user-images.githubusercontent.com/32205726/83945093-46bf3f00-a7d6-11ea-8a5f-d4e2ce1f708e.png)

# Versions and configuration
 
    -- OS: Windows 7
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 7 Home Premium 64-bit (6.1, Build 7601)
- Game Version: 0.E-2844-gede5ff2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Lighting Ammo [light_ammo],
    MST Extra [MST_Extra],
    Space Heater [space_heater],
    Alternative Map Key [alt_map_key],
    Mining Mod [Mining_Mod],
    Mythical Martial Arts [MMA],
    More Survivor Stuff [more_survivor_stuff],
    NPC Recruitment Options [recruitment_options],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    No Fungal Monsters [No_Fungi],
    Faster Stamina Regen [stamina_regen_buff],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4740081/debug.log)

**Comment by Jerimee** [comment]
I think this is related to the bug I experienced too.  Activating a first aid kit results in 0 aspirin (10), 0 bandages (6), 0 medical gauze (6), etc.

Worse yet, the 0 aspirin appears in inventory as simply aspirin: no quantity given because presumably just one... but if I take it the game hard crashes with seg fault arithmetic error...

**Comment by wapcaplet** [comment]
Cannot reproduce in 0.F-5143-g 427a349533 with multivatmins, aspirins, and oat seeds.

![image](https://user-images.githubusercontent.com/238395/148868016-952195d1-0c19-42fb-959a-c69eeae03ed3.png)
