### ISSUE TITLE
Slapping hand damage should be off when an implicit item is wielded.

### ISSUE THREAD

**Issue by cthae** [CleverRaven/Cataclysm-DDA#41111]
like a monomolecular blade, hooves or whatever. @kevingranade I see it's your recent commit. Would be great if you could add a fix.

I'm on 10732

**Comment by wapcaplet** [comment]
Please use the issue template for reporting bugs and feature requests. Any other contributor besides Kevin might like to solve this problem, and it would help them to have a clear description of what the issue is, and steps to reproduce the bug (if it is a bug).

**Comment by cthae** [comment]
pew. Still hasn't been fixed

**Comment by ZhilkinSerg** [comment]
> pew. Still hasn't been fixed

Yeah, and it won't be unless you are willing to provide some input from your side, starting with filling issue template.
