### ISSUE TITLE
Guns in 'V' menu show ranged damage of 0 despite "using ammo X as default"

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#41116]
# Describe the bug

Subj. Doesn't apply to all guns, though. Affected are:
- M1911
- Glock 17 and 19
- PTR 603
- Cx4 Storm
- Marlin 39A

Unaffected are single barrel shotgun and Winchester model 70.
So most probably it affects all guns which are loaded with magazines instead of directly with bullets.

# Steps To Reproduce

Find a gun store, press V, look at the damage.

# Expected behavior

Showing actual damage numbers.

# Screenshots

![cataclysm-tiles_2020_06_06_20_33_22_862](https://user-images.githubusercontent.com/56833396/83945554-b0bb0100-a835-11ea-9384-119f6e35edb7.png)

# Versions and configuration

- OS: Windows 7x64
- Game Version: 0.E-2899-g0ff7d77 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by kevingranade** [comment]
Possibly related to #45705
