### ISSUE TITLE
Too easy to accidentally pore out liquids.

### ISSUE THREAD

**Issue by TheMasterGear** [CleverRaven/Cataclysm-DDA#41126]
# Too easy to accidentally pour out liquids.

With the inventory overhaul, it's far too easy to pour out liquid now that you can directly drop liquid out from your inventory menu. This can really be a problem when you're loaded up from a raid and you want to drop your food items. But oops, you pour out all your drinks and condiments
 all over the floor.

![1](https://user-images.githubusercontent.com/60374171/83953844-f49c0f00-a811-11ea-9bb3-25457e614a10.png)
![2](https://user-images.githubusercontent.com/60374171/83953854-fe257700-a811-11ea-9412-045d943a1ae2.png)

# Describe the solution you'd like
A popup message to warn you if your sure you want to pour out your liquids.

**Comment by Medecube** [comment]
Now that #41514 has been merged, maybe this isn't be that big of a problem anymore.

**Comment by dreukrag** [comment]
The way the inventory was implemented, the edge case, dropping a liquid or emptying a container, has been made the default one. This should be changed, the old behavior of showing the item as "plastic bottle of water" was better for gameplay as it made it more easy to sort items.
