### ISSUE TITLE
Crash when attempting to repair binoculars

### ISSUE THREAD

**Issue by mark7** [CleverRaven/Cataclysm-DDA#41129]
# Describe the bug

I attempted to apply a soldering iron to a pair of binoculars in my inventory.  The game crashed.  I was able to reliably reproduce this.

# Steps To Reproduce

I've attached a save game to reproduce this that was both created and played only under a build of hashref 975fc771d00444268e9081b56f08dbf551c17b20.  Hit (a)pply, choose the soldering iron, and choose the binoculars.

# Expected behavior

No crash.

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux bullseye/sid; Release: testing; Codename: bullseye; 
- Game Version: 0.E-2901-g975fc771d0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations],
    Fuji's Military Profession Pack [fuji_mpp],
    Aftershock [aftershock],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Kills [stats_through_kills],
    Blaze Industries [blazeindustries]
]

# Additional context

I've attached a saved game to reproduce the problem along with the crash.log and debug.log file.  I've run a repro under valgrind; this shows an invalid reference prior to the stack trace containing the segfault.  I've not looked into this particular crash, but when I've seen similar prior Cataclysm crashes (probably not specifically related to this one), they often result from mutating containers while iterating over them.  Relevant part of valgrind log attached.

[Burnham.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/4741189/Burnham.tar.gz)
[config.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/4741193/config.tar.gz)
[valgrind.txt.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/4741199/valgrind.txt.gz)

**Comment by ZhilkinSerg** [comment]
Should be resolved in https://github.com/CleverRaven/Cataclysm-DDA/pull/41121

**Comment by mark7** [comment]
Thanks; will close.

**Comment by mark7** [comment]
Just as a followup, cannot reproduce with a build of 08d679223b74e6fc0ddb7f28b03c1ecf4ba9be8c, so that was indeed probably the problem.
