### ISSUE TITLE
Prison riot turrets don't fire, despite having ammo

### ISSUE THREAD

**Issue by Guldane2** [CleverRaven/Cataclysm-DDA#41137]
# Describe the bug

On a prison start, when reaching areas with riot control platforms spawned they will not fire, either at the player or zombies. When destroyed, they drop six ammo.

# Steps To Reproduce

Start in a prison, move to riot control platforms.

# Expected behavior

Turrets should shoot at players/zombies.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2927-g08d6792 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations],
    Graphical Overmap [Graphical_Overmap],
    sees-player icon, retrodays [sees_player_retro],
    No Fungal Monsters [No_Fungi]
]

**Comment by Maleclypse** [comment]
I’m currently not seeing any turrets fire.

**Comment by l29ah** [comment]
It's still an issue. Save file for easy repro: 
[2020.04.12.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5610021/2020.04.12.zip)
