### ISSUE TITLE
Can not automaticly drink from a bottle

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#41141]
# Describe the bug
Automatic drinking and eating zones do not consume food and drink from containers (eg bottles and cardboard boxes).

# Steps To Reproduce

1. Setup an "auto drink" zone
2. Drop a bottle of clean water into the zone
3. Wait for several hours
4. Nothing happens

# Expected behavior

@ automatically drinks water from the bottle

# Screenshots

none 

# Versions and configuration
- OS: Linux
    - OS Version: Distributor ID: Fedora; Description: Fedora release 32 (Thirty Two); Release: 32; Codename: ThirtyTwo; 
- Game Version: 0.E-2919-g000ecc6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Workaround
* Dump food on the ground 
* Put water in a standing tank

**Comment by hexagonrecursion** [comment]
I think this bug is back again. Just now I managed to dehydrate a character to death on purpose by waiting next to an "auto drink" zone with 10 plastic bottles of clean water.
```
- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 32 (Thirty Two); Release: 32; Codename: ThirtyTwo; 
- Game Version: 0.E-4395-g83ce24e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
```

**Comment by Ramza13** [comment]
Just tried to reproduce this and my character drank the water.
