### ISSUE TITLE
Automatic eating and drinking interrupts the current activity

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#41143]
# Describe the bug

If you automatically eat or drink while doing something (eg waiting, reading, crafting) you stop doing what you were doing before. This completely defeats the point of automatic eating and drinking.

# Steps To Reproduce

1. Setup an "auto eat" zone
2. Drop a 10 cookies into the zone. Note: make sure the cookies are not wrapped (see #41141)
3. Try waiting for a day or two
4. Your waiting will be interrupted with a chat message "you eat a coolie" and will not be automatically resumed

# Expected behavior

The current activity should be resumed after automatic eating and drinking.

# Screenshots

none

# Versions and configuration

    OS: Linux
        OS Version: Distributor ID: Fedora; Description: Fedora release 32 (Thirty Two); Release: 32; Codename: ThirtyTwo;
    Game Version: 0.E-2919-g000ecc6 [64-bit]
    Graphics Version: Tiles
    Game Language: System language []
    Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
    ]

# Additional context

none

**Comment by supachai19** [comment]
Nothing to preview

**Comment by supachai19** [comment]
ไม่มีอะไรให้ดูตัวอย่าง
