### ISSUE TITLE
Automatic drinking overcompensates

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#41145]
# Describe the bug

After you become thirsty enough for automatic drinking to kick in you drink as soon as you try to do something that takes time (eg waiting, crafting, reading). This eventually overcompensates and you throw up.

# Steps To Reproduce

1. Setup an "auto drink" zone
2. Build a standing tank in the zone and fill it with clean water. Note: water bottles won't work (see #41141)
3. Wait for several hours. You will eventually be interrupted with a message "you drink your clean water" due to #41143
4. Try waiting for 5 minutes
5. See the message "you drink your clean water" again
6. Repeat 4 and 6 several times
7. Throw up

# Expected behavior

Automatic drinking should not cause you to throw up.

# Screenshots

none

# Versions and configuration

    OS: Linux
        OS Version: Distributor ID: Fedora; Description: Fedora release 32 (Thirty Two); Release: 32; Codename: ThirtyTwo;
    Game Version: 0.E-2919-g000ecc6 [64-bit]
    Graphics Version: Tiles
    Game Language: System language []
    Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
    ]

# Additional context

none

**Comment by solifuge** [comment]
I've noticed similarly odd behavior with eating in general, where the UI doesn't seem to update immediately, nor accurately reflect your hunger value. These may be related? (See #41249)

**Comment by supachai19** [comment]
Nothing to preview

**Comment by supachai19** [comment]
ไม่มีอะไรให้ดูตัวอย่าง
