### ISSUE TITLE
No hostile creature in reach when meleeing in Labs

### ISSUE THREAD

**Issue by OverBlaze07** [CleverRaven/Cataclysm-DDA#41193]
I have noticed in multiple labs in version 10742, that it is very hard/impossible to hit enemies in melee once down a level in the labs. It will generate the "No hostile creature in reach" note, despite being adjacent to your target.

To reproduce, make a new world, start in a lab or teleport into a lab. Then try to use your fists/ katana / whichever melee weapon. 95% of melee attacks will result in No hostile creature in reach.

_(EDIT: Done some more testing. Problem is the Auto Attack feature (TAB button). You can walk into enemies to attack just fine. Also seems to occur below Z level 0. So not game breaking - just an inconvenience)_

Expected Behaviour? To hit it XD

Below is an example of the issue.

![Brute Fist](https://user-images.githubusercontent.com/60805958/84162700-03a1ec00-aab4-11ea-8547-d27093a456fe.PNG)

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-3074-gd071e91 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Graphical Overmap [Graphical_Overmap],
]

**Comment by ZhilkinSerg** [comment]
Duplicate or resurface of #37904.

**Comment by SirClarke** [comment]
Had this problem when using the safe mode black and white list and it seemed to work just fine when I turned that off not sure if it was just a coincidence or not I was in a lab start and underground
