### ISSUE TITLE
Filling vehicle tanks

### ISSUE THREAD

**Issue by SilverTemper** [CleverRaven/Cataclysm-DDA#41225]
# Describe the bug

Adding any amount of liquid to a vehicle tank fills it completely.

# Steps To Reproduce

1.  Find vehicle with empty tank
2.  pour in one unit of water
3.  Magic happens
4.  Get full tank of water.

# Expected behavior

Transfer one unit of water into vehicle tank

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 7 Home Premium 64-bit (6.1, Build 7601)
- Game Version: 0.E-3074-gd071e91 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Lighting Ammo [light_ammo],
    MST Extra [MST_Extra],
    Space Heater [space_heater],
    Alternative Map Key [alt_map_key],
    Mining Mod [Mining_Mod],
    Mythical Martial Arts [MMA],
    More Survivor Stuff [more_survivor_stuff],
    NPC Recruitment Options [recruitment_options],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    No Fungal Monsters [No_Fungi],
    Faster Stamina Regen [stamina_regen_buff],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by hexagonrecursion** [comment]
duplicate: 40369
