### ISSUE TITLE
SEGV when harvesting Lotus or Lilypad

### ISSUE THREAD

**Issue by sawoodall** [CleverRaven/Cataclysm-DDA#41227]
# Describe the bug

When attempting to harvest water plants Lotus or Lilypad, game crashes SIGSEGV. Does not crash for harvesting Cattails.

# Steps To Reproduce

1. Make a new world, start new character
2. Teleport to Swamp area
3. Search for pink Lotus or green Lilypad
4. Examine lotus (prompts "Pick lotus?")
5. Answer (Y)es
.... crash

# Expected behavior

If not crashing , should drop Lotus Bud or Lotus Flower items I think.

# Screenshots

Last moment before crash....
![{D8A1F26D-E407-437E-A92C-B70F6C9AA11C}](https://user-images.githubusercontent.com/66768947/84354770-75029d00-ab8f-11ea-8f03-3f31969b41d5.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-3098-g95abb14 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4763000/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4763002/crash.log)
[WhyNoLotus.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4763137/WhyNoLotus.zip)

**Comment by sawoodall** [comment]
traceback looks like maybe caused by:

https://github.com/CleverRaven/Cataclysm-DDA/pull/41190

**Comment by bloodraven983** [comment]
Every kind of procedure of foraging causes the crash, tried autoforaging, went near a bush and BAM

**Comment by sawoodall** [comment]
I wondered if there were more, and did try harvesting cattails which worked ok; I got "cattail stalk (fresh) (frozen)", so it may be a lot of things but not everything

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/error-hard-crash-on-flower-pickup/23924/7

**Comment by sawoodall** [comment]
confirmed fixed for me in build: 0.E-3197-g1a292a9
http://gorgon.narc.ro:8080/job/Cataclysm-Matrix/10756/changes

Thanks!
