### ISSUE TITLE
Bags or items attached to animals disappear when removed

### ISSUE THREAD

**Issue by Odieman1** [CleverRaven/Cataclysm-DDA#41233]
# Describe the bug

Whenever you attach a bag to an animal (In my case a horse), it works just fine.  Upon taking it off, it also works just fine.  After mounting the animal again or moving around a bit, the bag seems to just go up in smoke.  This includes all the things in said bag as well.

# Steps To Reproduce

1. Acquire a friendly horse and a backpack
2. Put the bag on the horse
3. Take off the bag, move around, mount the horse, things a player would normally do afterwards
4. Bag disappears

# Expected behavior

Bag+contents shouldn't vanish

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-3076-g753ad2a [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Mining Mod [Mining_Mod],
    Graphical Overmap [Graphical_Overmap],
    Jury-Rigged Robots [jury_rigged_robots],
    No Fungal Monsters [No_Fungi],
    Bionic Slots [cbm_slots],
    Nonperishable Overhaul [Nonperishable_Overhaul]

# Additional context

There are no error messages when this happens, it just sort of goes poof.  Be aware of that.  I have been able to reproduce this.  For now, don't put bags on a horse!  Cheers.

**Comment by Centac** [comment]
Did you tie your horse up at all? It is a known bug that whenever you tie up your animal, whatever bag you take your rope out of will vanish.

**Comment by Ramza13** [comment]
The bag and its contents did not vanish when I tried to reproduce this.

**Comment by Saicchi** [comment]
I can not reproduce this in Game Version: 0.E-8821-ged07fdc0a9 [64-bit].
I gave the horse a leather backpack with a water bottle inside, mounted the horse, walked around a bit, dismounted and removed the bag with the items still there. Tying and untying the horse did not affect the items.
