### ISSUE TITLE
NPC entering infinite loop when trying to reload M1903 Springfield

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#41230]
# Describe the bug

Subj. When NPC tries reloading her weapon it leads to "NPC can't reload M1903 with .30-06 clip" error; if you choose to 'i'gnore it, that NPC enters infinite loop.

# Steps To Reproduce

Load [save](https://github.com/CleverRaven/Cataclysm-DDA/files/4764807/Grand.Meadow.10746.zip), press 5 to wait 1 turn, see reloading error. Choose to ignore it, see infinite loop error.

# Expected behavior

NPCs being able to reload their weapons if they have some ammo.

# Versions and configuration
- OS: Windows 7
- Game Version: 0.E-3101-g483a50f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills]
]

# Additional info
Tried spawning M1903 and .30-06 clip, and it turns out it is not reloadable with the only clip it should be reloadable with (yes, the clip was full). Probably another NC-related issue.

**Comment by kevingranade** [comment]
Possibly related to #45705

**Comment by hexagonrecursion** [comment]
I can confirm that the error is **not reproducible** in 618a3be
```
- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 32 (Thirty Two); Release: 32; Codename: ThirtyTwo; 
- Game Version: 0.E-8740-g618a3be [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
```
I can see the below message in the chat log and the game continues just fine afterwards
```
Krista 'Dopey' Dooley, Bandit reloads their M1903 Springfield
```

I can confirm that the error was reproducible in a3e5f32
```
- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 32 (Thirty Two); Release: 32; Codename: ThirtyTwo; 
- Game Version: 0.E-4329-ga3e5f32 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
```

**Comment by mlangsdorf** [comment]
I can't reproduce the error on current master. The NPC successfully loaded the rifle in the save game, and also in a fresh game world.
