### ISSUE TITLE
(Aftershock) Haunting Forest Walker, and potentially other mobs in the mod, need a balance pass

### ISSUE THREAD

**Issue by PogoMarimo** [CleverRaven/Cataclysm-DDA#41248]
As of build 10745, the Haunting Forest Walker is an extremely strong mob that spawns at normal game start. At game start, it is far too quick and, short of excellent use of cover and running or perhaps a lucky shotgun start, will likely result in a game over. I had back to back Burning House spawns at the normal start date that ended when I walked out the back door into a forest and ran into the Haunting Forest Walker, however, I'm not sure if this problem is exclusive to this mob alone or if some of the other Uplifted Zeds need a tweak as well.

I would expect the best tweak would be to delay it's spawn time a bit, or lower it's speed so it's not quite as tenacious in pursuit.

**Comment by Maleclypse** [comment]
Both of those are in a branch I'm working on currently.  Speed was doubled when I meant to double HP and spawn time is increased to about 45 days in.  This branch has a bunch of other work in it and I can't guarantee it will be in the game this month.
