### ISSUE TITLE
รายงานข้อผิดพลาด

### ISSUE THREAD

**Issue by supachai19** [CleverRaven/Cataclysm-DDA#41252]
# Describe the bug

# Steps To Reproduce

# Expected behavior

# Screenshots

# Versions and configuration

# Additional context

**Comment by supachai19** [comment]
Nothing to preview

**Comment by anothersimulacrum** [comment]
This between
`<!--` and `-->` won't be displayed.

**Comment by supachai19** [comment]
ไม่มีอะไรให้ดูตัวอย่าง

**Comment by KorGgenT** [comment]
there doesn't seem to be anything here

**Comment by supachai19** [comment]
ไม่มีอะไรให้ดูตัวอย่าง
