### ISSUE TITLE
Unexpected crash a few hours into a save

### ISSUE THREAD

**Issue by bbborracho** [CleverRaven/Cataclysm-DDA#41263]
# Describe the bug

Game was going along fine. Had some non-fatal errors at startup. Was able for a few hours. Game Suddenly crashed and wouldn't reload.

# Steps To Reproduce

??? Unsure

# Expected behavior

Game to continue running as normal, load from save

# Versions and configuration

Cannot generate game report, as save will not reload

 - OS: Windows 10
 - Game Version: 0.E-3101-g483a50f
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: DDA, Aftershock, Blaze Industries, C.R.I.T. Expansion Mod, Magiclysm, Disable NPC Needs, SpeedyDex, Stats Through Kills, Stats Through Skills, Generic Guns, Mining Mod, More Survivor Stuff, Mythical Martial Arts, Graphical Overmap, Graphical Overmap Magiclysm
[Debug and Crash logs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4773626/Debug.and.Crash.logs.zip)

# Additional context

[Debug and Crash logs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4773631/Debug.and.Crash.logs.zip)

**Comment by bbborracho** [comment]
I'm sorry that the links are in weird places. I'm very new to github

**Comment by hexagonrecursion** [comment]
Could you please upload your save file too?

**Comment by I-am-Erk** [comment]
Closing as stale
