### ISSUE TITLE
Crash when trying to unload M240

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#41268]
# Describe the bug

Trying to unload M240 installed on a Humvee leads to crash.

# Steps To Reproduce

Load attached save, try unloading M240 on adjacent Humvee, crash.

# Expected behavior

Unloading without crashing.

# Versions and configuration

- OS: Windows 7
- Game Version: 0.E-3128-gb880329 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

[crash+debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4773829/crash%2Bdebug.zip)
[Grand Meadow.10751.1.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4773830/Grand.Meadow.10751.1.zip)

upd. if you remove M240 from the turret mount, unloading it as a regular gun works fine.

**Comment by olanti-p** [comment]
Can reproduce on ab977f7074fb832ddaeab7e0f994dd80ae42b324, but not on de1a6ccc325e0682983f3f19446822e4c8e5a514. Seems to be fixed.
