### ISSUE TITLE
Bandits (all NPCs, probably?) do not get damaged in very hot air

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#41266]
# Describe the bug

Decided to kill some bandits with tried and true tactic of "kill it with fire". The problem is, the house is burning but they are ignoring it. Temperatures inside are in range of 120-250 Celsius everywhere, and those dudes are just walking here and there as if it's nothing special.

# Steps To Reproduce

Load [Grand Meadow.10751.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4773742/Grand.Meadow.10751.zip) and see for yourself. The house has been burning for about 20 minutes now. Only one of the three died, and I'm not sure it was because of fire or not.

# Expected behavior

They should die, duh. Or try running outta house through the flames.

# Screenshots

![cataclysm-tiles_2020_06_13_07_24_20_169](https://user-images.githubusercontent.com/56833396/84555840-331d5680-ad49-11ea-8901-10d05b3e3b53.png)

# Versions and configuration

- OS: Windows 7
- Game Version: 0.E-3128-gb880329 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Kurrisum** [comment]
The trade off is that all of the "people" in "certain towers" aren't flat out cooked to death before intervention

**Comment by GGgatherer** [comment]
Nope. Those cells have normal temps inside. At least they did before related temperature patch but I doubt it was changed.
