### ISSUE TITLE
sealed jar of sauerkraut disappears when activated

### ISSUE THREAD

**Issue by bloodraven983** [CleverRaven/Cataclysm-DDA#41275]
# Describe the bug

Sealed jar of sauerkraut doesn't work like intended, it should become an opened jar of sauerkraut when activated and yet it becomes an empty jar

# Steps To Reproduce

spawn or find a sealed jar of sauerkraut
activated it
end up with an useless empty jar

# Expected behavior

you should have an opened jar with usable sauerkraut

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-3159-g3f48507 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi]
]

**Comment by RoyBerube** [comment]
This appears to have been fixed since being reported. The container can no longer be activated - just the sauerkraut, which is eaten on activation.
