### ISSUE TITLE
Fish traps act as if unloaded

### ISSUE THREAD

**Issue by Centac** [CleverRaven/Cataclysm-DDA#41288]
# Describe the bug

Plastic fish traps filled with bait cannot be set, and you receive the error message "Fish are not foolish enough to go in here without bait."

# Steps To Reproduce

1) Acquire a plastic fish trap
2) Fill it with bait
3) Attempt to activate fish trap

# Expected behavior

Fish traps filled with bait should be able to be set.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-3189-g8b2d5e7 or build 10755
 - Graphics version: Tiles
 - Mods loaded: DDA, Disable NPC Needs

**Comment by evankimori** [comment]
Tested this issue in build 10863  with stripping character naked, swimming far away from shore, wielding filled trap (with bait) and still won't deploy. Not sure of that can be of any use or assistance.

**Comment by Yurameki** [comment]
Still exists as a bug in 10891

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/plastic-fish-trap-not-working/24389/1
