### ISSUE TITLE
File did not contain the expected submap

### ISSUE THREAD

**Issue by Kelenius** [CleverRaven/Cataclysm-DDA#41292]
# Describe the bug

At some point of playing the game, this error will start popping up. The game starts behaving weirdly after that, resetting an area that had my stash at one point (in a save game I did not archive), and spawning monsters.

# Steps To Reproduce

I was not able to find specific steps to reproduce it, but starting a new game and playing for a while produced it in two cases out of two. The error appears again after loading, disappears after saving.

# Screenshots

![изображение](https://user-images.githubusercontent.com/6681708/84580950-e2f3d200-ade4-11ea-91fd-8ec1215406a3.png)

This is right after load. There might be cars in a different position.

![изображение](https://user-images.githubusercontent.com/6681708/84580962-ec7d3a00-ade4-11ea-8885-01f07c39dce6.png)

After moving up, zombies appear out of thin air.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-3188-ga9385fc [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Generic Guns [generic_guns],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills],
    Disable NPC Needs [no_npc_food]
]

# Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4775648/debug.log)
[Lares.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4775649/Lares.zip)

**Comment by anothersimulacrum** [comment]
Fixed by #41279, probably - the build's before it.
