### ISSUE TITLE
Repairing eyeglasses requires fabrication 10 

### ISSUE THREAD

**Issue by pescepalla** [CleverRaven/Cataclysm-DDA#41302]
# Describe the bug

Repairing eyeglasses requires at least 10 in fabrication. This seems excessive as  fabrication 10 can be used to create a nodachi.

# Steps To Reproduce
1. Make a four-eyed character
2. Get your eyes poked by zombies
3. Find a soldering iron
4. Try to repair your glasses
5. Fail because you're not a legendary blacksmith

# Expected behavior

Repairing eyeglasses should require a middling fabrication skill. It certainly should not be as complicated as forging a Japanese two-handed sword from metal scrap. 

# Screenshots

# Versions and configuration

<!-- Please complete the following information; you can now go to:
    - "Main menu (ESC) > Debug Menu > Info > Generate game report" to generate this report.

 - OS: Arch Linux
 - Game Version: 0.E-1
 - Graphics version: both
 - Ingame language: English
 - Mods loaded: None

**Comment by kevingranade** [comment]
Skills default to 10 if there is no point of reference for it such as an assembly or disassembly recipe.

**Comment by pescepalla** [comment]
True, but the result is rather unintuitive.

**Comment by pescepalla** [comment]
By the way, some crazed weirdo managed to make prescription glasses from scratch. 

It's hard, but it can be done: https://www.youtube.com/watch?v=Ef2_aaYpZSI

**Comment by anothersimulacrum** [comment]
To fix this, you can add a `repairs_like` to the eyeglasses item that references an item with a recipe that it can use to get a skill level.
