### ISSUE TITLE
about profession"blackbelt"

### ISSUE THREAD

**Issue by mMaisi** [CleverRaven/Cataclysm-DDA#41323]
i am confused about the profession "blackbelt".
look these codes"skills": [ { "level": 8, "name": "melee" }, { "level": 8, "name": "unarmed" }, { "level": 8, "name": "dodge" } ],
why a blackbelt can get 3 level 8 skill
in total it need 45 points in custom game-playing..
3 level 8 skill make it even like “Saitama” or "Kenshiro"
if the annotation has some words like "Kenshiro" might be better.（make it more balanced?）
:) i dont know how to express that feeling.....
because in daily life a blackbelt can not behave like that....

**Comment by meladath** [comment]
It's supposed to be an overpowered starting profession, thats kinda the point of why its there. 
Saitama would have 10 unarmed, no doubt, not 8.

There are many many overpowered starting professions, don't pick them if you don't like them. Thats the beauty of a single player game.

**Comment by kevingranade** [comment]
Wow yeah that's really overboard that would still be a pretty decent deal if you set those skills to 4 or so.
