### ISSUE TITLE
UPD2: Empty Fuel bunker/minireactor causes crash

### ISSUE THREAD

**Issue by methanolium** [CleverRaven/Cataclysm-DDA#41321]
# Describe the bug

A car with empty fuel_bunker or minireactor crashes a game in a few ways. Since I think crashes are coupled I'll put them here together.

UPD2: Look at the picture:
![image](https://user-images.githubusercontent.com/45267967/84794683-380b3000-afff-11ea-8c79-3cafe47aba70.png)

- The red rectangle is what you get in your save right after you install empty fuel_bunker or minireactor and where you get crashes described below. 
- The green rectangle is a fuel_bunker filled with some charcoal. If you set it to 0 then you'll be able to fill it, remove tank with gas and will see no crashes.
- The yellow rectangle is a fuel_bunker after all charcoal is burned out. Why yellow? Because you cannot change fuel to coal anymore which I believe is another bug.

# Steps To Reproduce

Type One:
1. Spawn a Bubble Car
2. Examine it, Unload (note that no fuel spawns [EDIT: actually you get 20x plutonium fuel cells]) and exit examine screen
3. Examine it again and watch crash

Type Two:
1. Spawn a Car
2. Spawn minireactor, unload it [EDIT: here you get 10000x plutonium fuel cells] and install into Car
3. Examine Car, try to Refill it and watch crash

[UPDATE for vanilla stuff without any aftershock/blaze]
Type Three:
1. Spawn a Car
2. Install Steam engine instead of default gas engine and Fuel Bunker instead of any passenger seat
3. Examine Car, try to Refill it and watch crash

Type Four:
1. Spawn a Car
2. Install Steam engine instead of default gas engine and Fuel Bunker instead of any passenger seat
3. Try to remove fuel tank with gasoline and watch crash

# Expected behavior

No crashes expected

#Screenshots

![image](https://user-images.githubusercontent.com/45267967/84621098-5d564c00-aee2-11ea-9446-7d60a365d6eb.png)

![image](https://user-images.githubusercontent.com/45267967/84620855-c12c4500-aee1-11ea-8066-d93db31ca570.png)

UPDATE:
![image](https://user-images.githubusercontent.com/45267967/84739942-2dc44400-afb5-11ea-93ff-7d2353cc68e7.png)

![image](https://user-images.githubusercontent.com/45267967/84739462-5435af80-afb4-11ea-83da-e43e5b0fad84.png)

# Versions and configuration

UPDATE: Note that Fuel Bunker bugs were catched without Aftershock+Blaze Industries

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-3223-g4919f51 [64-bit]
- Graphics Version: _Both_
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries]
]

# Additional context

Savegame archive with testing enviroment of excavator, arc welder, toolbox, Car and Bubble Car
[Grover Hill.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4778171/Grover.Hill.zip)

UPDATE: Save for Fuel Bunker bugs
[Vanilla Winter Low Evo.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4784843/Vanilla.Winter.Low.Evo.zip)

**Comment by Nannaquin** [comment]
Great find, dude. Ill look into this.

**Comment by Nannaquin** [comment]
@anothersimulacrum I don't know if I imagined this in the past but should it be possible to unload minireactors, installed or otherwise?

**Comment by anothersimulacrum** [comment]
I'm not sure. I'd guess yes, but I think we should look at what was possible in 0.E or earlier.

**Comment by Nannaquin** [comment]
I'm gonna retract that cause I'm looking into the code for unloading and it seems like that action is facilitated for the minireactor case.

**Comment by methanolium** [comment]
I have updated issue with vanilla only staff crashing the game. Basically same things which were seen with minireactor are seen with fuel bunker.

**Comment by methanolium** [comment]
I have updated the issue with quotes from save files.

**Comment by Nannaquin** [comment]
Apparently this crash has been solved by #41339

**Comment by methanolium** [comment]
@Nannaquin yep, but now you cannot refill fuel_bunker/minireactor :)
