### ISSUE TITLE
Make hand-strapped containers (Briefcases etc) wearable in Power armor

### ISSUE THREAD

**Issue by Broken27** [CleverRaven/Cataclysm-DDA#41348]
Currently you can only wear Hauling frames when using an exoskeleton. This makes sense - the servomotors would quickly trash any clothing or backpack.

What doesn't make a lick of sense is that you can't use a briefcase or shopping bag in your free hand.

(You can, of course, wield one, but you can't wear one in the left hand and wield another item).

**Comment by Broken27** [comment]
Mo

**Comment by redditguy11111** [comment]
Hello throwaway account from a redditor here...

I don't see any reason to close this PR. It's a good PR.

- While in Power armor a character can operate an ar-15.

- Operating an ar-15 includes manipulating the trigger, selector switch, and charge handle. It also includes removing magazines, inserting magazines, and loading magazines with ammunition. While firing one must aim and compensate for recoil. All of this is done during the heat of battle.

- A character can accurately fire the ar-15 as if they were wearing any other armor of equivalent encumbrance.

- Wielding a briefcase involves grasping the handle and lifting the briefcase.

- It is less difficult to wield a briefcase than it is to operate an ar-15

- Therefore, one can wield a briefcase while in power armor.
