### ISSUE TITLE
.50BMG cannot be put into inventory

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#41350]
# Describe the bug

Subj. If you try using AIM or 'i'nsert command it will outright deny you saying there's not enough free space even if you have plenty. If you try picking them up using 'g', you end up with them all in your hands even if you have spawned half a thousand of them.

# Steps To Reproduce

1. Make a player with some carrying capacity, regular backpack should do.
2. Spawn 100 of .50 BMG ball.
3. Try picking them up, see what happens.

# Expected behavior

Being able to put things into my backpack or w/e other container I have if there's enough space in it. Other ammo seems to work fine.

# Versions and configuration

- OS: Windows 7
- Game Version: 0.E-3253-gb10b72a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by anothersimulacrum** [comment]
Cannot reproduce
![image](https://user-images.githubusercontent.com/42699974/84790089-cfdc3000-afa5-11ea-9476-48ef5949b510.png)

**Comment by GGgatherer** [comment]
Did you just spawn them? They spawn already in the backpack. Drop them on the floor and try putting them back :)

**Comment by anothersimulacrum** [comment]
I did spawn them, but I put them on the floor, then spawned a backpack, and picked them up.

**Comment by GGgatherer** [comment]
Hmm... you know what, I actually cannot reproduce it now that I tried again. Strange. I was trying for 5 minutes to get them from one vehicle to another via my inventory and only managed it by holding them in hands, but now at the same character it just works. What the hell is going on?.. Oh well, I guess it should be closed as it isn't reproducible.
