### ISSUE TITLE
Crash when loading game

### ISSUE THREAD

**Issue by Heikelol** [CleverRaven/Cataclysm-DDA#41352]
# Describe the bug

Crash when loading game

# Steps To Reproduce

Load the game.

# Expected behavior

Not crash :)

# Screenshots

# Versions and configuration

    OS: Windows
        OS Version: 10.0 1909
    Game Version: 0.E-3253-gb10b72a [64-bit]
    Graphics Version: Tiles
    Game Language: Idioma del sistema []
    Mods loaded: [
    Dark Days Ahead [dda],
    Desactivar necesidades de los PNJ [no_npc_food],
    Aftershock [aftershock],
    Dark Skies Above [darkskies],
    Magiclysm [magiclysm],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Mythical Martial Arts [MMA]
    ]

# Additional context

https://i.gyazo.com/7379ef47979d8ae2c25070ada1ade63a.png
https://i.gyazo.com/7e60806d042a15b8950d1d4ad8391595.png
https://i.gyazo.com/265e18ba4e897c9c03a08e27bcc4a693.png

Uploaded crash, debug and save.

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4787451/save.zip)

**Comment by anothersimulacrum** [comment]
Here's a version that loads: [Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4787538/Save.zip)

It appears that the way that activities are saving/generating item locations in incorrect.

**Comment by Heikelol** [comment]
RNGesus bless you!

**Comment by ZhilkinSerg** [comment]
Does not crash on latest game version. Please try again and report if you still face this issue.
