### ISSUE TITLE
Nested container volume bug

### ISSUE THREAD

**Issue by GreatLurdo** [CleverRaven/Cataclysm-DDA#41356]
# Describe the bug

Found this strange bug. Not sure how general it is. Piece of clothing unable to hold some object is suddenly able to contain it if a permanent marker (?!) is stored first.

# Steps To Reproduce

1. Create a player wearing only a tuxedo (nothing more in the inventory).
2. Wield a big object that cannot be stored in the tuxedo: canning pot of water, longbow,...
3. Access \<i\>nventory.
4. Select the tuxedo.
5. Hit \<i\>insert. As expected, you cannot insert the big object.
6. Now grab the permanent marker: it is stored in the tuxedo (forced move) 
7. Again, in the inventory, select the tuxedo and hit \<i\>nsert.
8. The large object is now available to be stored.
9. If stored, the large object disappears.

# Expected behavior

a. An object that doesn't fit in a tuxedo shouldn't fit if a permanent marker is stored first, in particular.
b. An object cannot be stored in a pocket with insufficient size, in general.
c. In any case, objects should not disappear.

# Screenshots

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-3253-gb10b72a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

I am deeply sorry not to generalize past the extent of a tuxedo and a pen, but I already spent a disproportionate (my fault) amount of time going from "hey, my longbow has disappeared AGAIN?!?" to the actual reproduction of the issue (in general, I've noticed some strange behavior using the \<i\>nsert inventory command).

NB: had to replicate it crafting the longbow: due to some reason, spawning a longbow from the debug menu causes its reloading behavior to be very strange (but not sure if debug menu stuff deserve specific issue reports).

**Comment by wapcaplet** [comment]
Confirmed, using your steps:

![image](https://user-images.githubusercontent.com/238395/84847881-537e3700-b00f-11ea-852f-74e96d44cbd7.png)

This behavior is suspiciously similar to a problem I've been having with installing batteries in modded tools (part of  #41161 and only reproducible in that branch) - the batteries simply vanish when they are inserted. I suspect there is a more general issue here with inserting items into pockets of any kind. Would love to know if anyone finds more generalized examples to reproduce it.

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-3243-ga213a75e91 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by KorGgenT** [comment]
I tried reproducing it in order to fix it, but i couldn't.
![image](https://user-images.githubusercontent.com/30208401/85066734-81818980-b17d-11ea-82e4-a6ffafc761b9.png)
![image](https://user-images.githubusercontent.com/30208401/85066743-86463d80-b17d-11ea-8722-4a7d80fffcab.png)

**Comment by wapcaplet** [comment]
I could no longer reproduce this in version 0.E-3359-g77a3af0a91
