### ISSUE TITLE
Problem with containers having both flag-restricted and non-restricted pockets.

### ISSUE THREAD

**Issue by johnrdconnolly** [CleverRaven/Cataclysm-DDA#41357]
# Describe the bug

When items contain both regular pockets and holster/flag restricted pockets, if holster pockets are before regular pockets then items stored in the regular pocket are ejected on loading the game when holster pockets are not all full.

Issue comes from `void item_contents::combine(const item_contents&)` line of `src/item_contents.cpp`, which returns the debug error: tried to put an item into a pocket that can't fit into it while loading.  err: item does not have correct flag.
(full debug copy pasta in additional context)

#41456 was a quick patch to reorder the pockets of the tool belt as to avoid this. Needs full fix.

# Steps To Reproduce

1. Spawn and wear a tool belt.
2. Spawn an item under 1L.
3. Place the item in your tool belt. (see screenshots 1&2)
4. Save and quit.
5. Load, get message, item is gone from tool belt (see screenshots 3&4)
6. The item should then be dropped upon moving.

In the attached save file steps 1-4 have already been done. However, if you repeat 1-5 again you should get the same error and results.

Additionally, I am unable to reproduce the effects with other pockets I have tried such as jeans, winter jacket, and day pack.

# Expected behavior

The item should stay inside the pocket on loading.

# Screenshots

The tool belt with wrapper protein ration after step 3.
1: ![Before A](https://user-images.githubusercontent.com/59102789/84819994-c5359100-afcd-11ea-8b1f-dcac5e324bfe.png)
2: ![Before B](https://user-images.githubusercontent.com/59102789/84819990-c49cfa80-afcd-11ea-882d-bc0d489aa442.png)

The tool belt after completing step 5.
3: ![After A](https://user-images.githubusercontent.com/59102789/84819989-c36bcd80-afcd-11ea-9e05-fcd30c876ff7.png)
4: ![After B](https://user-images.githubusercontent.com/59102789/84819986-c23aa080-afcd-11ea-8cc4-3b4301a7feb4.png)

# Versions and configuration

 - OS: Windows 10 64 bit
 - Game Version: 0.E-3253-gb10b72a
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: Disable NPC needs

# Additional context

Error message on load.

DEBUG    : error: tried to put an item into a pocket that can't fit into it while loading.  err: item does not have correct flag

 FUNCTION : void item_contents::combine(const item_contents&)
 FILE     : src/item_contents.cpp
 LINE     : 111

Save File:

[Test World.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4788784/Test.World.zip)

**Comment by johnrdconnolly** [comment]
I just experienced the same issue involving a butane lighter also. So it seems to be something involving containers being inside the 5th pocket on the tool belt.

**Comment by hexagonrecursion** [comment]
Strange. The game does remember which pocket an item was in when saving (see below). Why does it check other pockets?

1. Wear a tool belt
2. Wish for a dive knife
3. Now you have a dive knife in the pocket number 2
4. Save and Load
5. See that the dive knife is still in the pocket number 2
6. Wish for 6 more dive knifes
7. Now you have a dive knife in every pocket
8. Mark one knife as favorite
9. Now the dive knife in the pocket number 1 is favorite
10. Drop all the dive knifes except the one in the first pocket
11. Unfavorite the dive knife
3. Now you have a dive knife in the pocket number 1
4. Save and Load
5. See that the dive knife is still in the pocket number 1

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 32 (Thirty Two); Release: 32; Codename: ThirtyTwo; 
- Game Version: 0.E-8968-gad3141d-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by hexagonrecursion** [comment]
Correction: it appears the problem was fixed. I'll post a more detailed report soon.

**Comment by hexagonrecursion** [comment]
It appears the problem was fixed.

# Old version
The below steps reproduce the issue in b10b72a

1. Start cdda version 0.E-3253-gb10b72a
1. Wear a tool belt
2. Wish for an apple
3. Now you have an apple in the pocket number 6
4. Save and Load
5. See error message (see below)
6. Wait one turn
7. The apple is now on the floor
```
 DEBUG    : error: tried to put an item into a pocket that can't fit into it while loading.  err: item does not have correct flag

 FUNCTION : void item_contents::combine(const item_contents&)
 FILE     : src/item_contents.cpp
 LINE     : 111
```

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 32 (Thirty Two); Release: 32; Codename: ThirtyTwo; 
- Game Version: 0.E-3253-gb10b72a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Most recent version
Same steps fail to reproduce the issue in the most recent version (ad3141d)

1. Revert the commit bd93e07
1. Wear a tool belt
2. Wish for an apple
3. Now you have an apple in the pocket number 6
4. Save and Load
3. The apple is still in the pocket number 6

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 32 (Thirty Two); Release: 32; Codename: ThirtyTwo; 
- Game Version: 0.E-8968-gad3141d-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by hexagonrecursion** [comment]
I have done more testing similar to above and it appears the game used to forget the pocket the item was stored in, but now it remembers (see https://github.com/CleverRaven/Cataclysm-DDA/issues/41357#issuecomment-760936383).

# Proof that the game used to forget the pocket
1. Wear a tool belt
2. Wish for 2 dive knifes
3. Drop one dive knife
4. Now you have a dive knife in pocket number 2
5. Save and Load
6. The dive knife moved into pocket number 1
- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 32 (Thirty Two); Release: 32; Codename: ThirtyTwo; 
- Game Version: 0.E-3253-gb10b72a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
