### ISSUE TITLE
Power stations (like gas stations but for electricity)

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#41365]
# Describe the solution you'd like
A new building type (I guess technically this would be a vehicle) used pre-cataclysm to replenish electric cars. This could be deconstructed and provide batteries and a jumper cable. 
Some of those stations would still have a little residual charge that could be used to replenish a vehicle (with a credit card like the gas stations) by connecting the station jumper cable to the vehicle.
They would be mostly one use only but crafty survivors could modify the building/vehicle to add a (set?) minimum number of solar panels or turbines and change them into working power stations.
The 'civilian' version (without the credit card stuff) could also be found in some houses garage.

Not sure if this can be done in json only?!

**Comment by Yunatan** [comment]
I think IRL recharging stations rely solely on infrastructure network and don't use storage batteries

**Comment by ZhilkinSerg** [comment]
New building - yes (maybe for AFS, not vanilla), but it should not really be working after power grid goes offline.

**Comment by jbytheway** [comment]
[Mobile EV chargers](https://thedriven.io/2019/12/02/tesla-deploys-mobile-ev-superchargers-powered-by-new-megapack-battery/) exist that don't rely on the grid.

And [some fixed chargers](https://electrek.co/2019/07/18/tesla-v3-supercharger-station-las-vegas-solar-power-battery/) have local solar and battery so they *could* work without the grid (don't know if they actually do).

**Comment by matt32106** [comment]
> 
> 
> I think IRL recharging stations rely solely on infrastructure network and don't use storage batteries

Yes you are right. It means that only a small fraction of stations should be fixed chargers as described by @jbytheway below. The vast majority wouldn't work without modification with solar panels and batteries.
