### ISSUE TITLE
Jury-rigged robots bug

### ISSUE THREAD

**Issue by StefanMiletic994** [CleverRaven/Cataclysm-DDA#41363]
# Describe the bug

When trying to create new character during loading mods screen error pops out and return you to main menu when try to continue(ignore). Same thing when trying to load the saved game.

# Steps To Reproduce

-Try to create new character, or load old one

# Expected behavior

Should load the saved game or load the character creation menu.

# Screenshots

![Error](https://user-images.githubusercontent.com/49565306/84834374-7faaaf80-b031-11ea-8167-46f046dd2599.jpg)

# Versions and configuration

![System](https://user-images.githubusercontent.com/49565306/84835137-32c7d880-b033-11ea-9bb9-48a54bc6ef7e.jpg)

 - OS: [Windows 10 ]
 - Game Version: [0.E-3253-gb10b72a]
 - Graphics version: [Undead People Tileset]
 - Ingame language: [System language(English)]
 - Mods loaded: [Dark Days Ahead, Disable NPC Needs, Aftershock, Blaze Industries, C.R.I.T Expansion Dod, Alternative Map Key, More City Locations, Jury-Rigged Robots, Bionic Slots, Speedy Dex]
 -->

# Additional context

[crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4789420/crash.zip)
[debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4789422/debug.zip)

[Rose Valley.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4789428/Rose.Valley.zip)

 

Im not genius, just stating, ive tried by deleting control laptop from blacklist hoping it would fix it but doesnt. Did this before in Modular turrets too to enable hacktop recipe - it worked - when it wasnt merged in with other stuff.

**Comment by anothersimulacrum** [comment]
Thanks for the report, but this is a third party mod, we can't do anything about it.

To fix that error, you need to add `"whitelist": false,` to the blacklist.

**Comment by StefanMiletic994** [comment]
Ok, dont know anything about that but did the thing you said and works, thanks!
