### ISSUE TITLE
Salvaging kevlar sheets from kevlar sheets should not be possible

### ISSUE THREAD

**Issue by Heikelol** [CleverRaven/Cataclysm-DDA#41378]
When you try to salvage a lot of kevlar-based items stacked, you end salvaging the salvaged kevlar sheets again. This results in a yield of kevlar sheets very inferior to the quantity expected.

# Steps To Reproduce

1. Stack a lot of military combat boots 
2. Cut them all
3. Notice that you salvage again the salvaged kevlar sheets

# Expected behavior

Salvaged kevlar sheets should remain intact, and the yield of cutting a stack of kevlar-based equipment should be similar to cutting items one to one and putting the kevlar sheets in your inventory.

# Screenshots

https://i.gyazo.com/09b5d65c15b8d1507f2b7136fe3c76b0.png

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-3257-g8e6f6c6 [64-bit]
- Graphics Version: Tiles
- Game Language: Idioma del sistema []
- Mods loaded: [
    Dark Days Ahead [dda],
    Desactivar necesidades de los PNJ [no_npc_food],
    Aftershock [aftershock],
    Dark Skies Above [darkskies],
    Magiclysm [magiclysm],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Mythical Martial Arts [MMA]
]

# Additional context

I provide a saved file before the unexpected behaviour, with a stack of boots ready to cut.

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4791228/save.zip)

**Comment by wapcaplet** [comment]
This appears to have been fixed by #41494
