### ISSUE TITLE
Blood draw kit doesnt work

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#41408]
# Describe the bug

Subj. It is empty even after activating on a zombie corpse.

# Steps To Reproduce

Get a BDK, kill a zombie, activate it(kit, not zombie), see activation message, see BDK being empty regardless.

# Expected behavior

BDK actually drawing the blood from the corpse.

# Versions and configuration

- OS: Windows 7
- Game Version: 0.E-3334-g4a8349f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Medecube** [comment]
Same problem as #41226 most probably
