### ISSUE TITLE
become a stone by magic

### ISSUE THREAD

**Issue by howmokas** [CleverRaven/Cataclysm-DDA#41401]
If an alchemy accident turns @ into a magical creature whose body is made of stone, it has a stone body, but it moves slowly, it will be damaged by the weather, but it has a new magical ability, will not bleed but break Limbs need stone recovery, but since the body is stone, there is no way to add cbms

**Comment by howmokas** [comment]
I don’t think much because I see that mutation can keep players from bleeding

**Comment by howmokas** [comment]
But blood analysis tells you that you have blood volume

**Comment by Valares** [comment]
Since this report is missing any and all templates, tags and labels... Is this a bug report? Or a suggestion? An idea? A new mod? An addition to an existing mod? ...

**Comment by howmokas** [comment]
a idea

**Comment by howmokas** [comment]
There are tree man, so I wonder if there can be stone  man
