### ISSUE TITLE
Make wooden doors and curtains quieter (Closing curtains and doors making too much noise)

### ISSUE THREAD

**Issue by oragnesmen** [CleverRaven/Cataclysm-DDA#41404]
# Is your feature request related to a problem? Please describe.
Curtains, despite being sheets attached to wooden rods with strings (source: taking down curtains), they make 11 noise when closed, which is close to the sound you make when running/bashing furniture. This is both unrealstic and makes day raids way more risky.

Wooden doors make 11 noise when closed like they are being slammed shut. Any survivor with over 10 IQ would understand that slamming a door shut in an apocalypse where there are noise sensitive zombies everywhere would be a VERY bad idea. This is also unrealstic (you cannot close doors slowly and quietly) and makes both day and night raids risky if you wish to close any doors.

# Describe the solution you'd like
Instead of making a whopping 11 noise, curtains should make around 5 noise (or lower!) when closed. It would be a nice touch to make this not apply for characters with Clumsy trait and make them still loudly close curtains.
We should have an option to close doors slowly and quietly which costs more action points but makes you make less noise when closing doors. This can be a lifesaver in risky raids.

# Describe alternatives you've considered
We should have an option to close doors slowly and quietly which costs more action points but makes you make less noise when closing doors. This can be a lifesaver in risky raids. 

# Additional context
https://www.youtube.com/watch?v=C1ytqhCQxN0

**Comment by bloodraven983** [comment]
In my game, opening door or curtains make 5 noise and closing them makes 9
apart from that, I already discussed this topic on discourse a while ago, they said that the mechanism of a door and metal ring on a curtain rod would make enough noise to justify that value

**Comment by matt32106** [comment]
Devs may also want to consider implementing rolling shutters in place or with curtains. Those make an awful lot of noise :)
