### ISSUE TITLE
Starting NPC "Tiers" for difficulty selection

### ISSUE THREAD

**Issue by MarceloLaser** [CleverRaven/Cataclysm-DDA#41402]
Something that bothers me a tad is the starting Static NPCs from certain scenarios. While we're able to choose starting scenario and starting profession, which very much tunes the difficulty of the game, something that can be wildly unbalancing is the NPC that starts next to you. Those NPCs can range from being a naked, weak human, to being a high-strength mutant carrying assault rifles and literally hundreds of explosives (all of these actually happened to me). They can also range from completely willing to follow you, all the way down to being nearly impossible to get as a follower.

# Describe the solution you'd like
Solving this is heavily dependent on how NPC spawning is done, but one alternative would be to have an option of which "tier" or "tiers" of starting scenario NPCs. A player would be able to select a tier, or a range of tiers, that they consider "acceptable" to start with. Want an easy start? Select a high tier scenario NPC spawn and start with an explosive-laden mutant who loves you. Want it to be more challenging? Select lower tier scenario NPCs for a "regular survivor" or even a towel-wearing weakling.

# Describe alternatives you've considered
Another way to go about it would be to give some NPCs a kind of "evolution factor" like zombies have. The rationale is that over time, NPCs will have had the chance to loot more advanced gear and mutate into stronger variants. With this solution, the player would select an evolution factor and starting evolution level for NPCs, which would affect the starting scenario NPC. This would also help tune bandit encounters to be more challenging later in the game, and would make rescuing Mi-go prisoners more of a bounty. It would need to be made so it doesn't affect certain NPC factions, like those in the Refugee Center, as they are specifically tuned to certain missions.

**Comment by ZhilkinSerg** [comment]
NPC will eventually loot buildings and use better equipment.

**Comment by dissociativity** [comment]
I think NPC spawns should start off basically regular people generally, and vary a lot more, become tougher over time, just as the player does, just pools depending on how long it's been since the cataclysm, unskilled and weak npcs are less likely to survive so it makes little sense to spawn them often later into the cataclysm.

**Comment by MarceloLaser** [comment]
I want to note that this is even more important now than it was 3 weeks ago, since it is no longer possible to turn off static NPCs from the scenario. I recognize I can just ignore the NPC, or debug-remove them from existence, but really ideally if the scenario's difficulty is inherently connected to the starting NPC's being there or not, then I'd say it's even more connected to how strong that starting NPC is. As I said in the original post, a scenario with a towel-wearing asthmatic with an infection is going to be immeasurably more difficult than a scenario with a super-strong, grenade-toting mutant.
