### ISSUE TITLE
Teleporting without warning when the stairs are occupied.

### ISSUE THREAD

**Issue by Centac** [CleverRaven/Cataclysm-DDA#41411]
# Describe the bug

When going up or down the stairs and it is occupied by a monster, you instead move to an adjacent tile if one is available. While that is good, there needs to be some kind of warning saying that you won't be standing on the stairs and can't immediately retreat. Something like, "Attempt to push past the monster in the way? Yes/No". But the bigger issue is when you attempt to peek. Peeking down a set of stairs should be completely safe, but if you do it while the stairway is occupied, you can't return to your original level, and you are stuck on the level you peeked at.

# Steps To Reproduce

1) Attempt to go or peak up/down stairs that is occupied.
2) Be teleported to an adjacent tile without warning. 

# Expected behavior

1) Warn the player when moving up/down the stairs onto an adjacent tile instead of the stairway.
2) When peeking through a stairway, allow the player to return to the original level. If you can't do that, then saying you can't peek because there is a monster in the way is probably best.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-3334-g4a8349f
 - Graphics version: Tiles
 - Mods loaded: DDA, Disable NPC Needs

**Comment by meladath** [comment]
I agree entirely, this has killed me on multiple occasions. Odd theres no warning for it when you consider the other warnings we have related to moving up/down levels, e.g broken stairs
