### ISSUE TITLE
SIGSEGV fault possibly caused by containers/reloading

### ISSUE THREAD

**Issue by OptimisticNihlist** [CleverRaven/Cataclysm-DDA#41412]
# Describe the bug

The game crashes when I attempt to pick up more than one item (g) from a pile of items on the ground next to me.

# Steps To Reproduce

1. Load save.
2. press [g]. [I]. [r], or use the advanced inventory menu to move more than one item from the pile of items on the ground. It does not seem to matter which item is moved. 
3. The game crashes with sigsegv fault

# Expected behavior

I could pick up items and manage inventory normally without error

# Screenshots

 N/A

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-3312-g25a6e36
 - Graphics version: [Terminal]
 - Ingame language: English
 - Mods loaded: dda, no_npc_food, aftershock, blazeindustries, classic_zombies_remux, speedydex, stats_through_kills, StatsThroughSkills, fuji_mpp

# Additional context

Crash: [crashreports.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4798913/crashreports.zip)
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4798918/save.zip)

**Comment by KorGgenT** [comment]
![image](https://user-images.githubusercontent.com/30208401/85068059-bb538f80-b17f-11ea-8791-908e947be118.png)
well here it is, but it's definitely baffling why it's crashing instead of skipping the for loop.
