### ISSUE TITLE
ALRIGHT WHY DO I GET SEGMENTATION FAULT

### ISSUE THREAD

**Issue by slingring** [CleverRaven/Cataclysm-DDA#41427]
# the game is being retarded again

I GET SEGMENTATION fault after tryna craft a MISC repair kit

# Steps To Reproduce

1. load save
2. craft misc repair kit
3. crash

# Expected behavior

game crashes

# Screenshots

# Versions and configuration

<!-- Please complete the following information; you can now go to:
    - "Main menu (ESC) > Debug Menu > Info > Generate game report" to generate this report.
    - Please update your OS version with a more precise version.
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-680-g668e469 [32-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Aftershock [aftershock],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills]

# Additional context
please dont ban me i wanna live

**Comment by slingring** [comment]
what the frick it didnt post my steps

**Comment by mlangsdorf** [comment]
Thanks for playing, we were tired of your slurs when you were being abusive on the Discord.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/what-was-my-ban-reason/23279/71
