### ISSUE TITLE
Game places forage results on the ground after foraging, in contrary to harvesting, which places results into inventory

### ISSUE THREAD

**Issue by Stephen2** [CleverRaven/Cataclysm-DDA#41424]
# Describe the bug
When you have auto-pickup set, foraging (manually or with auto-forage) from a bush doesn't pick up the items.

You _do_ auto-pickup items foraged from trees (pine boughs etc...)

# Steps To Reproduce
1. Auto pickup enabled = True
2. Auto picked adjecent = True
3. Forage (or auto-forage) a bush that gives an item

# Expected behavior
Expected items to be picked up

# Versions and configuration
- OS: Linux
    - OS Version: Fedora32
- Game Version: 0.E-3327-geba273ab9a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context
I built from Git hash 9037665ce6

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
