### ISSUE TITLE
Cannot store items within SOFTWARE type containers

### ISSUE THREAD

**Issue by John-Candlebury** [CleverRaven/Cataclysm-DDA#41422]
# Describe the bug
Hardcoded attempts to store items within software type pockets currently fail, with the inserted item transforming into a 'none'. 

Both hardcoded attempts `COMPACT_DOWNLOAD_SOFTWARE` and `activity_handlers::mind_splicer_finish` use the `put_in()` function and both fail, so the bug might be related to that.

# Steps To Reproduce

1. Spawn an NPC and give them the 'Retrieve Software' mission. Receive an empty usb.
2. Travel to the mission target computer and chose the download software computer option
3. Notice that the usb given at mission start is now a: 'usb with none'

# Expected behavior

The software item is spawned inside the usb, instead of the none.

# Versions and configuration

Game Version: 0.E-3310-gc21e10593

# Additional context
This is also the source of the bug described in #41226
Likely related to issue #41410 although that one refers to software indicated in item lists not spawning into the world.

**Comment by Ichthysdekilt** [comment]
Related to #41410 ?
