### ISSUE TITLE
Can't seem to move item stack from Advanced inventory management any more

### ISSUE THREAD

**Issue by Stephen2** [CleverRaven/Cataclysm-DDA#41425]
# Describe the bug
Using `M` to move item stack in advanced management screen only moves 1 item at a time

# Steps To Reproduce
1. Have 21 pinecones
2. Open advanced inventory management screen `/`
3. Have side 1 as inventory `I`
4. Have side 2 as floor next to you (East in my case)
5. Press `M` to try and move whole stack of pinecones
6. Note that only 1 moves at a time

# Expected behavior
All the items move at once.

# Versions and configuration
- OS: Linux
    - OS Version: Fedora32
- Game Version: 0.E-3327-geba273ab9a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context
Built from hash 9037665ce6

Also, dropping a stack of items (e.g., 20 pinecones) gives a "1 by 1" message style:
`You drop your pinecone on the floor.`
`You drop your pinecone on the floor.`
`You drop your pinecone on the floor.`
etc...

And it goes very slowly.  Not sure if related.

**Comment by Stephen2** [comment]
Well, just went outside to firewood and moved a stack of 21 pine boughs to an empty square, all as a stack.  So it's intermittent.

Inside, my problem with pinecones was moving them from my Inventory, into a mega-loot square, full of tons of random things.

**Comment by zeziba** [comment]
From the way item handling works it is intentional.

It goes through a while loop as it attempts to insert the item into the receiving item/place.

**Comment by FeepingCreature** [comment]
The one-by-one is intentional; the broken mass-move is not.

**Comment by l29ah** [comment]
Seems to be fixed now.
