### ISSUE TITLE
Charcoal smoker can only load 200 charcoal

### ISSUE THREAD

**Issue by Lamandus** [CleverRaven/Cataclysm-DDA#41435]
# Describe the bug
the furniture charchoal smoker can now only load 200 charges instead of "infinite". Which makes smoking 20 l of stuff impossible (needed 500). If setting anything higher than 200, it won't reload it.

# Steps To Reproduce
Have a charcoal smoker, load it with charcoal, check charges.

# Expected behavior
Loading at least 500 charcoal

# Screenshots
![grafik](https://user-images.githubusercontent.com/33199510/85096261-26d74480-b1f4-11ea-8ebb-78bd5a053989.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-3369-gc738dee [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Graphical Overmap [Graphical_Overmap],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    Fewer Farms [Fewer_Farms]
]

# Additional context

**Comment by KorGgenT** [comment]
i'm willing to bet this is an easy json change, but i am not in a position to confirm that. try adding pocket data to the pseudo item, and if it uses a regular pseudo item then make a new pseudo item with a larger magazine pocket.
