### ISSUE TITLE
Sweet new on-dispersion effects for one time use items like grenades

### ISSUE THREAD

**Issue by zeziba** [CleverRaven/Cataclysm-DDA#41433]
# Is your feature request related to a problem? Please describe.
####One Time Use Items!
Have you ever wondered how your 4'9" mighty warrior can take on the relentless hordes of school children? Well wonder no more as you can completely enamor these wandering desiccated diminutive post-apocalyptic tenderfeet with the new and exciting product from Super Smell Smellerson Inc., trademark pending. By using this product which is dubbed the ramshackle oblivion consciousness smasher, or R.O.C.S. for short, you will be able to traverse the wastes worry free as swarms of the questionably living flock towards or glorious product.

SSS and affiliated are not responsible for any and all damages or accidents that may occur from the use of out product. Use at your own risk.

# Describe the solution you'd like
Create an ability for one-time use items that would create dispersion of unique effects and effectors.

Such as the following
> Grenade type items that disperse a scent cloud for a long period of time
> Above but adds a frenzy type buff to the zeds whom enter so if the player or other gets close they will get an effective speed buff to catch them as its not safe to go around a swarm of interested zeds
> Grenade type item that disperses traps onto the ground which slow/slow+damage those whom walk over

Effects such as these would add an interesting play style to the game as it is common in hunting to use calls and baits to entrap animals. Using this logic in the post apocalypse seems like a would be thing to do!

# Describe alternatives you've considered
Praying to my lord and savior physics-man to do all this so I wouldn't have to!

# Additional context
None as of yet!

**Comment by kevingranade** [comment]
The issue tracker has way too many entries in it for us to keep around what amounts to brainstorming prompts. Feel free to flesh out a concrete idea elsewhere and post it as a new issue.
