### ISSUE TITLE
UPS not showing charges/not recharging

### ISSUE THREAD

**Issue by petervanblerkom** [CleverRaven/Cataclysm-DDA#41449]
# Describe the bug
UPS is not showing any charges (not 0/1500, just no charge indication) and so cannot be recharged

# Steps To Reproduce
Find or spawn UPS

# Expected behavior
UPS should have charges and be rechargeable

# Screenshots
![recharger_noups](https://user-images.githubusercontent.com/46461939/85171594-881b0a00-b22c-11ea-911d-a5f692132a8d.png)

# Versions and configuration
Game Version: 0.E-3373-gcf80ae0 (Tiles)4
OS: Windows 10
Mods loaded: [dda,no_npc_food,zets_hair_extensions_undead,aftershock,blazeindustries,Graphical_Overmaps,StatsThroughSkills,speedydex]

# Additional context

**Comment by IFailAtGaming** [comment]
this is an aftershock issue, i know that much
