### ISSUE TITLE
Seg Fault when fully taking apart any vehicle 

### ISSUE THREAD

**Issue by Kurrisum** [CleverRaven/Cataclysm-DDA#41464]
# Describe the bug
Seg fault occurs whenever you remove the last bit of any vehicle 

# Steps To Reproduce
1. Start a vehicle with any frame
2. Examine vehicle
3. Use O menu to removes the last piece
4. Experience crash
(Vehicle to direct south in the save)

# Expected behavior
Being able to fully dismantle a vehicle without a crash

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-3388-gc2cd66c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    Mining Mod [Mining_Mod],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

[Crash-Debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4807276/Crash-Debug.zip)

[Seg Fault save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4807277/Seg.Fault.save.zip)

**Comment by anothersimulacrum** [comment]
Reverting the changes in #41360 fixes this.

**Comment by Ichthysdekilt** [comment]
Also seeing this in 10792.

**Comment by SageB** [comment]
I am experiencing this in 10973.
