### ISSUE TITLE
standing in bright tile cannot see dark tiles nearby

### ISSUE THREAD

**Issue by martinrhan** [CleverRaven/Cataclysm-DDA#41472]
# Describe the bug
I am playing lab scenario as start of the game, and such things usually happen. For example I am standing in a bright area, I can only see bright places around me, and I need to walk into darkness to see the things in dark area. If the dark area consist of only a unpassable tile, then I will not be able to see it without an extra light source.

# Steps To Reproduce
Just play a game like what I said.

# Expected behavior
such things should not be happening. Maybe this is simulating the fact that people hard to see things in darkness from brightness, but a least nearby thing should be visible.

# Screenshots
N/A

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-3388-gc2cd66c [64-bit]
- Graphics Version: Tiles
- Game Language: 系统语言 []
- Mods loaded: [
    浩劫余生 [dda],
    禁用NPC需求 [no_npc_food],
    C.R.I.T 扩展 [crt_expansion],
    变形怪工业 [blazeindustries],
    大魔法 [magiclysm],
    余波未尽 [aftershock],
    神话武术 [MMA],
    替换小地图图标 [alt_map_key],
    移除火车站 [No_Rail_Stations],
    图形版大地图 [Graphical_Overmap],
    图形版大地图（大魔法） [Graphical_Overmap_Magiclysm],
    技能提升属性 [StatsThroughSkills],
    敏捷速度加成 [speedydex],
    杀怪提升属性 [stats_through_kills],
    Magiclysm No Class Limit [magiclysm_no_class_limit]
]

# Additional context
nothing

**Comment by heebejeebes** [comment]
I believe this is by design for precisely the reason you suggested. If you are standing in an area of bright light looking into a very dark area you should not be able to make out anything.

**Comment by martinrhan** [comment]
@heebejeebes but it is not sensible that this block is bright then an adjacent peace of space suddenly become very dark

**Comment by Ichthysdekilt** [comment]
It does make some sense that there would be a dropoff of light intensity.  Very Bright to Bright to Dark to Very Dark.  While looking from somewhere very bright to somewhere very dark would definitely make it hard or impossible to see, looking from somewhere very bright to an adjacent tile with a roof overhead should not be completely obscured as it is.
