### ISSUE TITLE
Make the player be able to jump over one block when he runs

### ISSUE THREAD

**Issue by rafaelkb** [CleverRaven/Cataclysm-DDA#41475]
# Describe the solution you'd like

Do you know when you jump in Dwarf fortress adventure mode? That.

# Describe alternatives you've considered

Nothing.

# Additional context

Just look at how the player can jump in the adventure mode in df.

**Comment by anothersimulacrum** [comment]
You can already jump over one open air tile, examine the tile you want to jump over.
