### ISSUE TITLE
Using comestible items with 'cast_spell' action no longer function

### ISSUE THREAD

**Issue by Axema** [CleverRaven/Cataclysm-DDA#41482]
# Describe the bug

Spellcasting comestible items like the `Cat's Grace` potion doesn't provide the effect after being consumed.

# Steps To Reproduce

1. Spawn a potion that modifies your stats when eaten.
2. (E)at it.
3. The potion is consumed, but doesn't provide any effects.

# Expected behavior

After being consumed, the spellcasting comestible item should cast whatever spell it has.

# Screenshots

![](https://cdn.discordapp.com/attachments/709600070810730518/724031167833047131/unknown.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.E-3388-gc2cd66c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm]
]
# Additional context

**Comment by KorGgenT** [comment]
This issue is worded in such a way that it would seem like it's a Magiclysm issue specifically, but it's not. I stepped through it, and the comestibles _do_ properly invoke the iuse actor, but it looks like the eat activity somehow overwrites the spellcasting actor, so i'm willing to bet this is an issue for all comestibles that have a use action.

**Comment by Axema** [comment]
Looking into this further, it seems you're correct. Evidently Chaosvolt had discovered this [bug](https://www.reddit.com/r/cataclysmdda/comments/h971ny/comestibles_that_cast_spells_when_used_are/) recently as well.

**Comment by kevingranade** [comment]
Please do not link to ChaosVolt's posts, he's an incredibly unreliable and spammy bug reporter, and bug reports are not welcome from him, either directly or via intermediaries.

**Comment by wapcaplet** [comment]
I can reproduce this - spawn all of the following stat-modifying potions:

- Cat's Grace
- Eagle's Sight
- Ogre's Strength
- Fox's Cunning

Drink them all:

![image](https://user-images.githubusercontent.com/238395/85216344-a114df80-b340-11ea-8012-9614905a8b2b.png)

No effect on stats:

![image](https://user-images.githubusercontent.com/238395/85216350-be49ae00-b340-11ea-9ee9-b89ec0843e16.png)

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-3417-gc1e33efa75 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm]
]

**Comment by Kenan2000** [comment]
> so i'm willing to bet this is an issue for all comestibles that have a use action.

I've decided to test comestibles with the `consume_drug`, `heal`, `mutagen`, `firestarter`, `deploy_tent`, and `PICK_LOCK` use actions respectively. Three of these use actions that are commonly associated with comestibles, the other three are normally used by tools as far as I know

What I sort of managed to figure out from testing is that only comestibles that use `cast_spell` are affected
