### ISSUE TITLE
Abnormal Termination when launching the game.

### ISSUE THREAD

**Issue by Enderlordalatreon** [CleverRaven/Cataclysm-DDA#41487]
Upon trying to open the game, I would get this error and the game would refuse to launch.

Game won't launch, instead getting this error:
![Annotation 2020-06-20 223446](https://user-images.githubusercontent.com/66154890/85215413-4a120900-b346-11ea-9ed0-0f925414563e.png)

# Steps To Reproduce

Launch game>crash.

# Expected behavior

Game would launch normally, any error afterwards being unrelated.

CRASH LOG BELOW
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4808847/crash.log)

# Versions and configuration
Cataclysm DDA version 0.E-3388-gc2cd66c

# Additional context

Nothing to add, just suddenly happened.

**Comment by anothersimulacrum** [comment]
Try renaming your `config/` directory.

**Comment by Enderlordalatreon** [comment]
Nothing.
I even moved the config to a different folder, same issue.

**Comment by anothersimulacrum** [comment]
How about `save/`?

**Comment by Enderlordalatreon** [comment]
Same crash, again I moved the folder to another folder.

**Comment by ZhilkinSerg** [comment]
Something is off with tilesets. Your fresh install should work.

**Comment by Enderlordalatreon** [comment]
> 
> 
> Something is off with tilesets. Your fresh install should work.

I figured as much, did a reinstall of everything, had an issue which I solved (if you have one mod in the root cdda mods folder and that same mod in data/mods it would cause a black screen, and infinite loading). Works now, that's for the help folks.

**Comment by anothersimulacrum** [comment]
I'll close this since this appears to be resolved then.
