### ISSUE TITLE
Segmentation fault when installing a fuel bunker 

### ISSUE THREAD

**Issue by Yunatan** [CleverRaven/Cataclysm-DDA#41492]
# Describe the bug

Segmentation fault when installing a fuel bunker on a vehicle 

# Steps To Reproduce

1. Make a one tile vehicle 
2. Spawn a fuel bunker and necessary tools, get mechanics 1 
3. Try to install a fuel bunker on a vehicle 
4.  ![image](https://user-images.githubusercontent.com/6611291/85216921-52446580-b393-11ea-95f2-9946d7ee670a.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.E-3388-gc2cd66c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    No Fungal Monsters [No_Fungi]
]

# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4808925/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4808926/debug.log)

**Comment by olanti-p** [comment]
Can reproduce on c2cd66c9ca07995c7e6d5eb102d1e9e9c4ccde3c (version in the report) but not on de1a6ccc325e0682983f3f19446822e4c8e5a514. Seems to be fixed.

**Comment by AMurkin** [comment]
Not crashing on 1ea5556a41 (build #10847).
But cannot reload/fill the installed fuel bunker.
