### ISSUE TITLE
Autoclave Item requires too many battery charges

### ISSUE THREAD

**Issue by bloodraven983** [CleverRaven/Cataclysm-DDA#41499]
# Describe the bug

Autoclave, not mounted on a vehicle, requires 8200 battery charges for a single cycle

considering that only a plutonium cell would have such capiency... i think it should be toned down a bit

# Steps To Reproduce

spawn an autoclave and activate it

# Expected behavior

I don't know what your plans are for battery balancement but consindering how rare these items are, this requirement should be tuned down a bit...

# Screenshots

![image](https://user-images.githubusercontent.com/66170818/85226971-8f801600-b3da-11ea-8db8-eb0c780a812a.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-3388-gc2cd66c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi]
]

**Comment by Fris0uman** [comment]
Yes this is normal, autoclaves use a lot of energy and making a battery powered autoclave is a terrible idea that's why it doesn't exist irl. Use the vehicle mounted version.

**Comment by bloodraven983** [comment]
> Yes this is normal, autoclaves use a lot of energy and making a battery powered autoclave is a terrible idea that's why it doesn't exist irl. Use the vehicle mounted version.

oh I will, when the refill bug will be solved :P it requires water in the vehicle tank and i can't install a full tank and can't refill it, so I tried to use the autoclave as stand alone

thanks for reply

**Comment by anothersimulacrum** [comment]
I'm going to close this as invalid - the battery charges are intentional, and the refill bug you're talking about is a separate bug.
