### ISSUE TITLE
Auto save backup before saving.

### ISSUE THREAD

**Issue by Proluiz** [CleverRaven/Cataclysm-DDA#41500]
# Is your feature request related to a problem? Please describe.
Yes, it's related to the segmentation fault on loading, when the game autosave during a task if you close and load the save it'll crash. 

# Describe the solution you'd like
Why not having a feature that do a backup of the save before saving, just in case of something going wrong, this also should be a feature in menu, enable by default on development version and disabled by default on stable (with the ability to turn it on if the player want).
Note: a new folder "backup\" should be nice to do this task too

# Describe alternatives you've considered
Not saving during a task when playing in the dev version?

# Additional context
If you load and it crash, you reopen the game go in world <World name> Restore backup 
(if an backup is avaliable) else it wont appear/work on menu. 

![image](https://user-images.githubusercontent.com/6380147/85227883-6d749c80-b3b6-11ea-911b-8b41992cab0a.png)

**Comment by Proluiz** [comment]
Forget to mention when the save lead to segment fault it's impossible to load the save anymore, and this world is lost, unless if you have a backup of it.

**Comment by Zireael07** [comment]
IIRC it was suggested before - and I agree, especially for experimental versions it would be a very welcome addition.

**Comment by leemuar** [comment]
I would like to suggest the save algo:

- there is a "current save file pointer", pointing to the current save file
- when the game saves, it creates a new save file, it does not overwrite the current one
- if save is successful - modify "current save file pointer" to point to a newly created save; delete old save file

**Comment by Proluiz** [comment]
your suggestion just prevent you losing the save if a crash on pc or energy drop happens during the save pogress, but my poblem is not really it, this version that i'm using is successfully saving a buggy version of the save, overtaking the other save, so if you try to use this save to start the game, you can't do it, thus losing this world.
My intend is to aways keep an older save as backup if somehow the game saved a buged version, so you wont lose the world.

- Copy content from ../save/world1/
- Paste in ../Backup/world1/ (overide existing bakup save)
- Save the actual game ../save/world1/

So if something goes wrong and you cant open the save: Go in world and choose to restore to backup (or revert to backup)
- Delete the save ../save/world1/
- Copy ../Backup/world1/
- Paste in ../Save/world1/

Only if you're really unlucky to having 2 bugged saves. and lose the world.

**Comment by leemuar** [comment]
Oh, i see now what's the problem.
Maybe instead of a backup we should allow multiple save slots? Like 5-10? Every time the game saves - it saves to a new slot.

**Comment by kevingranade** [comment]
The problem with this feature is it would be unusably slow.  Dda creates very large saves, and making a copy of it on every save instead of updating it in-place as happens now would be prohibitively expensive.
If you want do do out-of-band backups, that is pretty trivial to set up without adding it to the game.

**Comment by Proluiz** [comment]
Well at some point i mentioned it to be a function on menu setting, that you can disable or enable as you wish, but we can change it to be off by default in any version so.
also about the save time it depends much on the machine, because so far on my father's laptop it takes like 1 minute to save, while on my main pc it just take less than 2 seconds.

**Comment by leemuar** [comment]
Lets look at the problem from a different angle: what causes a save file to become "corrupted"? Do you have a corrupted save file example? Or some steps to reproduce?

**Comment by Proluiz** [comment]
It happens MOSTLY whit autosaves during an task too.
on load it bugs out saying something like a item is missing its destination and them crash to segmentation fault.
i think i can redo the same conditions to make it happen again, give me a minute i'll come with details in a hour or minutes.

On my case it saved while i was droping a massive amount of items in a kart.

**Comment by matt32106** [comment]
> The problem with this feature is it would be unusably slow.

Can't you make hard links of the files?

**Comment by Proluiz** [comment]
I was successful in reproducing the error, steps for reproduction:
- debug give you a backpack for higher storage.
- give you 100 rags.
- Keep droping and picking it up until the game decides to autosave during the droping/picking process.
- Wait he finish whatever he's doing and close the game.
- Try opining the save.

Expected: Game to load where he saved.
Result: game crash.

![image](https://user-images.githubusercontent.com/6380147/85343184-997d4400-b4c2-11ea-9e2c-a3ba9fd65a51.png)
[Charlotte Park.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4815954/Charlotte.Park.zip)

version: 0.E-3373-gcf80ae0

**Comment by leemuar** [comment]
> I was successful in reproducing the error, steps for reproduction:

Good job, thanks!
I think a good fix might be:
- figure out why does this actually leads to segfault and fix it
- restrict autosave to save during bulk actions

**Comment by GGgatherer** [comment]
> 
> 
> > The problem with this feature is it would be unusably slow.
> 
> Can't you make hard links of the files?

What would be the point? If some files are changed, hardlinks will also point to changed data. If those changes result in corrupted save, hardlinks will also point to that data and the "backup" will also be corrupted.

**Comment by GGgatherer** [comment]
> 
> 
> I was successful in reproducing the error, steps for reproduction:
> 
>     * debug give you a backpack for higher storage.
> 
>     * give you 100 rags.
> 
>     * Keep droping and picking it up until the game decides to autosave during the droping/picking process.
> 
>     * Wait he finish whatever he's doing and close the game.
> 
>     * Try opining the save.
> 
> 
> Expected: Game to load where he saved.
> Result: game crash.
> 
> ![image](https://user-images.githubusercontent.com/6380147/85343184-997d4400-b4c2-11ea-9e2c-a3ba9fd65a51.png)
> [Charlotte Park.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4815954/Charlotte.Park.zip)
> 
> version: 0.E-3373-gcf80ae0
> 
> If this error happen this world is gone.

IIRC Korggent said he could not reproduce that error. It may be worth making a separate bug report or at least PMing him about it.

**Comment by leemuar** [comment]
Lets convert this issue to a bug report

**Comment by hexagonrecursion** [comment]
> Why not having a feature that do a backup of the save before saving, just in case of something going wrong, this also should be a feature in menu, enable by default on development version and disabled by default on stable (with the ability to turn it on if the player want).
Note: a new folder "backup" should be nice to do this task too

My personal solution involves git and a systemd timer. There are many backup programs capable of making incremental backups. What would we gain from integrating this functionality into the game?

**Comment by leemuar** [comment]
On the latest stable build item_location lost error forces game to create a new save file:

![image](https://user-images.githubusercontent.com/5869791/85933811-1bff6c80-b8e4-11ea-9f78-117b337fef6c.png)
