### ISSUE TITLE
Visual Studio requires a setting change to compile CDDA

### ISSUE THREAD

**Issue by Hirmuolio** [CleverRaven/Cataclysm-DDA#41506]
# Describe the bug

EDIT: Setting "Use static libraries" to "yes" makes things work.
This should be set by default in the project or mentioned in the documentation for building.

Visual Studio can't compile CDDA.

When the project is opened there are multiple errors:  
`warning  : Wildcards are not supported in vc projects, they have been replaced with explicit files.`

Trying to build results in:

1>------ Build started: Project: Cataclysm-lib-vcpkg-static, Configuration: Release x64 ------
1>Get version string
1>Done
1>Generating "version.h"...
1>VERSION defined as "0.C-54579-g2bb549b143-dirty"
1>Using triplet "x64-windows" from "D:\programming stuff\vcpkg\installed\x64-windows\"
1>stdafx.cpp
1>D:\programming stuff\Cataclysm-DDA\msvc-full-features\stdafx.h(80,16): fatal error C1083: Cannot open include file: 'SDL2/SDL.h': No such file or directory
1>Done building project "Cataclysm-lib-vcpkg-static.vcxproj" -- FAILED.
2>------ Build started: Project: Cataclysm-vcpkg-static, Configuration: Release x64 ------
3>------ Build started: Project: Cataclysm-test-vcpkg-static, Configuration: Release x64 ------
4>------ Build started: Project: JsonFormatter, Configuration: Release x64 ------
2>Using triplet "x64-windows" from "D:\programming stuff\vcpkg\installed\x64-windows\"
2>stdafx.cpp
2>D:\programming stuff\Cataclysm-DDA\msvc-full-features\stdafx.h(80,16): fatal error C1083: Cannot open include file: 'SDL2/SDL.h': No such file or directory
2>Done building project "Cataclysm-vcpkg-static.vcxproj" -- FAILED.
========== Build: 0 succeeded, 4 failed, 0 up-to-date, 0 skipped ==========

# Steps To Reproduce

1. Install latest version of Visual Studio.
2. Try to compile CDDA.

# Expected behavior

It just works.

# Screenshots

# Versions and configuration

Visual Studio 1.6.2

# Additional context

Probably related: https://github.com/microsoft/terminal/issues/6214

**Comment by Menschheit** [comment]
Try manually setting "Use static libraries" to "yes".

**Comment by Hirmuolio** [comment]
Changing that setting seems to work. It is compiling.

**Comment by ZhilkinSerg** [comment]
As for dropped wildcard support - it is a pretty controversial change from VS side and I really hope it will be reverted (or made optional) in the future, so we don't have to track individual source files explicitly in VS project files.

As for Vcpkg options - it looks like it is something new and there were no `vcpkg` related options in configuration properties in previous versions of VS. We just kept triplet settings in a global property named `VcpkgTriplet`:

https://github.com/CleverRaven/Cataclysm-DDA/blob/ea2928fe5bb868fcf8e79c86f65a86d0459bbe06/msvc-full-features/Cataclysm-lib-vcpkg-static.vcxproj#L27-L28

**Comment by nexusmrsep** [comment]
From my experience: MSVS also resolves wildcards and forcefully edits vcxproj files, that in general makes it easy to accidentally commit them.
However `git update-index --skip-worktree <file_name>` will suppress this, but it will also make them invisible to MSVS to resolve the wildcards and thus it will not compile.

**Comment by Night-Pryanik** [comment]
Game compiles successfully as of 2022.08.31. Should we keep this issue open?

**Comment by mqrause** [comment]
This was fixed ages ago, see #41894.
