### ISSUE TITLE
Debug message on trying to craft near some furnitures

### ISSUE THREAD

**Issue by Trioct** [CleverRaven/Cataclysm-DDA#41516]
# Describe the bug

A debug message appears when opening the crafting menu/examining/probably other stuff near boulders, gravestone, or anvils, although nothing appears to break.
I'm pretty sure you can just remove the else statement from #41417 inventory.cpp (aka the debug message), but I didn't look into it too heavily

# Steps To Reproduce

Craft near a small/medium boulder, gravestone, or anvil (furniture)
If you can't get the message to reappear, you have to move, probably to clear a cache or something

# Expected behavior

I don't have to press i to ignore the message >:(

# Screenshots

![thing](https://user-images.githubusercontent.com/4079502/85319332-f5c27280-b486-11ea-91d2-09abc7c29af8.png)

# Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.E-3441-g60e22a33e0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by Qrox** [comment]
Fixed by #41586.

**Comment by Trioct** [comment]
Oh, it really was as easy as removing the debug message.
