### ISSUE TITLE
Game crashes loading character

### ISSUE THREAD

**Issue by buildfailedforallplatforms** [CleverRaven/Cataclysm-DDA#41531]
# Describe the bug

Game crashes loading character

Game crashes loading character

# Steps To Reproduce

1. Make new character/load old character
2. 

Game crashes

# Expected behavior

Game does not crash

# Screenshots

![Untitled](https://user-images.githubusercontent.com/62628815/85354598-49e45a00-b54e-11ea-9087-42b79e1c5f6d.png)

# Versions and configuration

# Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4816735/debug.log)

**Comment by sawoodall** [comment]
Editing the json by deleting the space after the 'L' in the quotes allows mine to load 
```
 folded_volume: "2 L "
                    ^
```

**Comment by ZhilkinSerg** [comment]
Fixed in #41528
