### ISSUE TITLE
Items disappear when manually inserted

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#41536]
# Describe the bug

Under very specific conditions items disappear when you manually insert them into a worn container. 100% reproducible in a clean save.

# Steps To Reproduce

1. Start "naked and afraid"
2. Wish for a duffel bag
3. Wear the duffel bag
4. Wish for a pot
5. Wish for 17 pairs of pants
6. Note that you now have 16 pairs of pants in the duffel bag and one pair in your hands
7. Open inventory
8. Select the duffel bag
9. [i]sert
10. Select the last pair of pants
11. Press enter
12. The pants in your hands mysteriously vanish

# Expected behavior

Items should not vanish

# Screenshots

none

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 32 (Thirty Two); Release: 32; Codename: ThirtyTwo; 
- Game Version: 0.E-3470-ga87254b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

While messing around with the setup I also managed to delete the pot and duplicate the pants several times.

**Comment by hexagonrecursion** [comment]
Possibly related: 40312

**Comment by KorGgenT** [comment]
![image](https://user-images.githubusercontent.com/30208401/85517747-8e630a80-b5cd-11ea-96bd-b052a2301705.png)
what kind of pants? i wished in army pants and it won't let me insert.

**Comment by KorGgenT** [comment]
![image](https://user-images.githubusercontent.com/30208401/85518002-d08c4c00-b5cd-11ea-98be-e9ec6c9e61e4.png)
work pants also don't let me insert

**Comment by KorGgenT** [comment]
aha, work pants

**Comment by hexagonrecursion** [comment]
Sorry. I should have specified. Regular pants.
