### ISSUE TITLE
Crash when opening inventory near hexamine

### ISSUE THREAD

**Issue by heebejeebes** [CleverRaven/Cataclysm-DDA#41539]
# Describe the bug

When trying to open an inventory menu near contained hexamine will cause a game crash.

# Steps To Reproduce

1. Debug Reveal Map
2. Teleport to a mil. surplus
3. Use [g], [/], or [V] to open inventory when standing next to an item containing hexamine
4. Observe crash

# Expected behavior

Game should display inventory and not crash if hexamine is present.

# Screenshots

Not applicable

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-3470-ga87254b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Alternative Map Key [alt_map_key]
]

# Additional context

This bug produces a crash.

[Logs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4820902/Logs.zip)
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4820904/save.zip)

Save file is in mil. surplus near the shelf with "cardboard box of hexamine" shelf is directly north of character on far right side. Pressing [/] next to the shelf or [V] from loading position will produce the crash

**Comment by Maleclypse** [comment]
Looks like the log is listing hexamine as an invalid ammunition type.  So probably someone just needs to add hexamine to the ammo_type.json file.

**Comment by hexagonrecursion** [comment]
The json looks fine. The bug is somewhere else.
https://github.com/CleverRaven/Cataclysm-DDA/blob/6313122ed023889f6385d5e9dd4ba883de93fde7/data/json/items/ammo_types.json#L638-L643

**Comment by wapcaplet** [comment]
Possibly related to / caused by #41519
