### ISSUE TITLE
I am eating a lot of calories and they are not being stored.

### ISSUE THREAD

**Issue by BenlyAZ** [CleverRaven/Cataclysm-DDA#41549]
# Describe the bug

I have been cramming down a ton of high-calorie food and still getting messages about not enough calories. I have been eating 500-calorie pemmican or 400-calorie dehydrated meat every time I dip below satisfied (hence every half hour or so) for the past few in-game days, thus consuming very nearly the maximum possible amount it is physically possible for me to consume. I finally checked debug (I was hesitant to do so because I don't like disabling achievements) and it turns out I had 35836 stored kcal as of the time of the posted save. Since then I have spent two more in-game days eating pemmican every time I went below satisfied (read books one chapter at a time until the hunger went blank, then ate and became full), and my stored kcal have only gone up to 37000. I have taken antiparasitics so it's not that.

# Steps To Reproduce

I do not know how to reliably reproduce this.

# Expected behavior

I would expect to get sufficient calories from eating the maximum possible amount of meat and fat.

# Screenshots

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-3470-ga87254b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Magiclysm No Class Limit [magiclysm_no_class_limit],
    DinoMod [DinoMod],
    Cataclysm++ [Cata++],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Mythical Martial Arts [MMA],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Safe Autodoc [safe_autodoc]
]

# Additional context

Here's the save.

[Speonk.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4822464/Speonk.zip)

**Comment by anothersimulacrum** [comment]
Loading the save and consistently eating, your character plummets to about 17000 calories, then starts to recover from there.

**Comment by BenlyAZ** [comment]
That is very strange, because despite eating 8000 kcal/day for four days since the uploaded save my stored kcal have only gone up by about 3000.

**Comment by anothersimulacrum** [comment]
Okay, I've figured it out - because walking is a `MODERATE_EXERCISE` activity, and the player is always walking, even when standing still, you're using 7000 calories just at rest.

**Comment by BenlyAZ** [comment]
Okay, that makes sense as the source of the problem.

**Comment by digitCruncher** [comment]
[Tularosa.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4824236/Tularosa.zip)

Here is another save with this problem (using build #10783, which should have fixed the walking as a MODERATE_EXERCISE bug). I calculated that I consumed 36 cracklings (14,832 Calories) (and about 1.5 liters of water), and my stored calories + stomach calories increased from 41,027 to 46,532 . This means I consumed 9,327 Calories in 12 hours.

**Comment by anothersimulacrum** [comment]
Nothing has fixed anything related to this bug yet, build 10783 is no more fixed than the build this was introduced in, 10781.
