### ISSUE TITLE
"You need to eat more calorie dense food" at 35000 stored kcal

### ISSUE THREAD

**Issue by BenlyAZ** [CleverRaven/Cataclysm-DDA#41548]
# Describe the bug

I have been cramming down a ton of high-calorie food and still getting messages about not enough calories. I finally checked debug (I was hesitant to do so because I don't like disabling achievements) and it turns out I have 35836 stored kcal.

# Steps To Reproduce

I do not know how to reliably reproduce this.

# Expected behavior

I would expect the warning messages to accurately reflect my situation (barring hallucinations and such).

# Screenshots

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-3470-ga87254b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Magiclysm No Class Limit [magiclysm_no_class_limit],
    DinoMod [DinoMod],
    Cataclysm++ [Cata++],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Mythical Martial Arts [MMA],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Safe Autodoc [safe_autodoc]
]

# Additional context

Here's the save.

[Speonk.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4822464/Speonk.zip)

**Comment by anothersimulacrum** [comment]
This is expected behavior. That message appears at any stored calorie value less than 44k.

**Comment by anothersimulacrum** [comment]
You need to continue to eat high calorie foods over a long period, and keep in mind that it takes 52 hours to fully digest food.

**Comment by BenlyAZ** [comment]
Sorry, I should clarify in the initial report: I'm eating 500-calorie pemmican every time my fullness dips below satisfied to blank, so I'm consuming several thousand kcal per day and have been for the past few days. Will edit initial post to reflect that.

**Comment by BenlyAZ** [comment]
I opened a new issue with a clearer title.

**Comment by anothersimulacrum** [comment]
We'd prefer you didn't make new issues, just asked for them to be reopened, but it's not big deal in this case.
