### ISSUE TITLE
<bug> Marlin 39A can`t be reloaded

### ISSUE THREAD

**Issue by Katanasoul91** [CleverRaven/Cataclysm-DDA#41547]
# Describe the bug
The Marlin 39A can`t be reloaded with it compatible magazine

# Steps To Reproduce
1. Spawn the Marlin 39A with some .22 19-round tube loader.
2. Try to reload.

# Versions and configuration
 OS: Windows 10
Game Version: 0.E-2993-gd2b512e
Graphics version: Tiles
Mods loaded: 
![imagen](https://user-images.githubusercontent.com/62341576/85475139-06a8dc00-b58c-11ea-9339-fcc3e2c8abc7.png)

**Comment by Menschheit** [comment]
This must be related to speedloader.
Some guns dont need a magazine, so the pocket_type of that gun should be "magazine". But for the ones which there is an appropriate speedloader, the pocket_type is defined as "magazine_well". I think that is the problem.
