### ISSUE TITLE
JSONize "multi_attack" type specials 

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#41542]
# Is your feature request related to a problem? Please describe.
It is presently difficult/impossible to give a monster various special attacks to use in a semi-rational way, such as picking an attack to use against large targets, or an attack to use at short range.

However, there are some hard-coded attacks that do this. Specifically I am looking at "MULTI_ROBOT", defined on line 3905 of monattack.cpp. I believe "CHICKENBOT" on line 3823 is similar, but haven't read it as much.

# Describe the solution you'd like
I'd like to refactor and JSONize this so that monsters can be given simple multiattacks where they choose a special based on a couple of basic constrained principles. I'd say the basic choices should be:
- large_enemy (enemy more than 200L in volume, or in a vehicle)
- surrounded (more than 3 enemies within 5 squares)
- long range (range 30+ tiles away)
- medium range (range 15-30 tiles away)
- short range (range 3-14 tiles away)
- point-blank range (range 1-2 tiles away)

Debatably it might be nice to be able to specify ranges, size cutoffs, and what counts as ' surrounded', but I think we can make do with a few hard coded ones. It could also be fun to have a weapon for 'clustered enemies' but that requires a lot more clever algorithms than just checking how near the enemies are.

I am picturing something like
```json
{ "MULTI_ATTACK": [
  { "type": "large_enemy", "special": "name of special" },
  { "type": [ "long_range", "medium_range" ], "special": "a different special"  },
  { "type": [ "short_range", "point_blank_range" ], "special": "FLAMETHROWER" }
] }
```
In this example, 'surrounded' is undefined so the monster would not use any particular special attack if surrounded.

# Describe alternatives you've considered
Kevin says all this would be handled by behavioural trees, but the exodii can't wait for that dammit!

**Comment by I-am-Erk** [comment]
I think we can call this done by the spells system at this point.

**Comment by I-am-Erk** [comment]
Was gonna close but then I remembered we still need the multiple range ai stuff

**Comment by bombasticSlacks** [comment]
This was all cleared in a couple of seperate PRs
