### ISSUE TITLE
Missing Containers and items from starting professions all vanilla +shipped mods

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#41551]
# Describe the bug

1. Security guard missing M9 Beretta
2. Police Officer missing USP handgun and baton
3. Bionic Operator missing USP handgun.
4. Military Rifleman missing handgun unknown.
5. Gangster missing Glock 9mm
6. Archeologist missing .38 special
7. Military Automatic Rifleman missing handgun unknown
8. Military Grenadier missing handgun and grenade launcher
9. Breacher missing handgun and storage error removes sledgehammer
10. Operator Undercover missing FN-57
11. K-9 Officer missing USP and baton
12. Police Detective missing .357 handgun
13. Wild West Gunslinger missing Colt .45
14. Military Marksman missing handgun unknown.
15. Operator Recon missing M1911.
16. SWAT Officer missing USP
17. SWAT CQC missing USP.
18. Police Sniper missing rifle and USP
19. Riot Control Officer missing USP
20. Operator Sniper missing M1911
21. Operator Hacker missing M1911.
22. Operator CBRN missing M1911
23. Uplifted Enforcer missing USP
24. Bionic Sniper missing USP
25. Bionic Gangster missing Glock 9mm 

# Steps To Reproduce

1. Make a player from one of the above professions, have missing equipment or hit storage error.

# Expected behavior

Someone needs to add these items in json or otherwise alter professions. 

# Screenshots

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-3407-g845884a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

Hoping this list will help a new contributor with some easy starting points.

**Comment by ZhilkinSerg** [comment]
Bisecting shows issue appeared after #40295.

**Comment by wapcaplet** [comment]
In some cases, these guns do not spawn with the starting professions because their holster does not have enough `max_item_length` to fit the gun's `longest_side`. For instance the Police Detective gets a standard "holster" that can only fit a 25 cm gun, but their S&W 619 gun is 27.8 cm in length.

In other cases, the gun itself does fit in the holster, but the gun's `MAGAZINE_WELL` pocket is not `"rigid": true`, OR the pocket does not have a `"magazine_well": "NN cm"` specifying the internal space of the well - meaning these guns get larger when a magazine is inserted. For example the Security Guard's Beretta M9A1 is only 0.53 L, which would fit in the holster, but when a magazine is inserted, the gun's total volume becomes 0.85 L, so it no longer fits in the holster, and won't spawn.

**Comment by meladath** [comment]
Hopefully a lot of the the pistols are fixed now that #41476 has been merged. I think the standard holster needs to be increased to 30cm, either that or lots of guns need to be made a bit smaller as right now we have quite a few guns that I dont really consider worthy of only being able to fit in an Xl holster that are >25 and <30 cm.

**Comment by Hulkninja** [comment]
Gunslinger still borked. Wouldn't this be circumvented by spawning in with the weapon wielded?

**Comment by wapcaplet** [comment]
Spot-checked several of these in 0.E-5926-g a883429bdd - except for an occasional missing baton, they seem to be working now:

1. Security guard has M9A1 Beretta:
![image](https://user-images.githubusercontent.com/238395/93398151-448a6900-f838-11ea-83fd-895466357adc.png)

5. Gangster has Glock 19:
![image](https://user-images.githubusercontent.com/238395/93398374-afd43b00-f838-11ea-8012-4f6cc570d208.png)

6. Archaeologist has S&W 619:
![image](https://user-images.githubusercontent.com/238395/93398447-d7c39e80-f838-11ea-8386-46aa325cdc98.png)

11. K9 Officer has USP .45, but *no baton*
![image](https://user-images.githubusercontent.com/238395/93398567-0ccff100-f839-11ea-9e08-b0b97364411b.png)

12. Police Detective has S&W 619:
![image](https://user-images.githubusercontent.com/238395/93398642-2ffaa080-f839-11ea-84fe-9d6d7727fdb0.png)

17. SWAT CQC has USP 9mm *and* baton:
![image](https://user-images.githubusercontent.com/238395/93398734-5c162180-f839-11ea-8010-09b7f23f2198.png)

19. Riot Control Officer has USP .45 *and* tonfa
![image](https://user-images.githubusercontent.com/238395/93398893-a26b8080-f839-11ea-960c-de2cd0c1463d.png)
