### ISSUE TITLE
Favorite pockets interface fix/improvement

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#41550]
# Describe the bug

If there's too much crap in a pocket, priority/whitelist section is not shown because items take all screen space.

# Steps To Reproduce

Make a player, generate many small different items, put them into backpack, try setting rules for its pocket. 

# Expected behavior

Rules list actually visible regardless of how many items are in the pocket. This section should be at the top, not under pocket description/contents. Or maybe under pockets list - that one will most probably never have much height.

# Screenshots

![cataclysm-tiles_2020_06_24_09_03_29_922](https://user-images.githubusercontent.com/56833396/85489494-45757b00-b5fa-11ea-88f1-00b2d3fc4698.png)

# Versions and configuration

- OS: Windows 7
- Game Version: 0.E-3478-g28fa7cb [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/prevent-loot-from-going-into-armor/25491/2
