### ISSUE TITLE
The Outpost Knife Spear Quest Bug

### ISSUE THREAD

**Issue by BKryth** [CleverRaven/Cataclysm-DDA#41560]
# Describe the bug
I made 12 Knife Spears with this recipe and when I went to the quest giver, he wouldnt accept the knife spears i made 
![image](https://user-images.githubusercontent.com/67372229/85549810-eee85b00-b652-11ea-9d9d-6f50e88c965b.png)
![image](https://user-images.githubusercontent.com/67372229/85549984-17705500-b653-11ea-8bdb-6cf8fadc23f8.png)
![image](https://user-images.githubusercontent.com/67372229/85550008-1d663600-b653-11ea-8f44-ca06f6e26ef3.png)

# Steps To Reproduce
1. Make Knife Spear from that recipe
2. Talk to quest giver

# Expected behavior

Quest giver accepts those 12 knife spears

# Screenshots

Already sent

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Graphical Overmap [Graphical_Overmap],
    Stats Through Skills [StatsThroughSkills],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion]
]
# Additional context
No crashes

**Comment by anothersimulacrum** [comment]
This NPC is looking for the `spear_knife`, which is called a simple knife spear in game. They should probably want `spear_knife_superior`, which is called a knife spear.

**Comment by MatiasFito** [comment]
I've been wanting to contribute, start with something easy to get accustomed to the PR submission process i will take on this bugfix as my first issue!

**Comment by MatiasFito** [comment]
PR ready, thanks @anothersimulacrum for pointing me in the right direction for this :clap: !
