### ISSUE TITLE
Messy building spawn

### ISSUE THREAD

**Issue by VityaPinguinus** [CleverRaven/Cataclysm-DDA#41562]
# Describe the bag
Fire station spawned right next to a house. There's no free space in between both buildings 

# Steps To Reproduce
Explore the world

# Expected behavior
Different buildings should be at least 1 square away from each others
# Screenshots

![Untitled](https://user-images.githubusercontent.com/33584808/85556360-6f956000-b62f-11ea-90ed-07f5bbfbea60.jpg)
![Untitled2](https://user-images.githubusercontent.com/33584808/85556535-9bb0e100-b62f-11ea-8eb4-91873c4f7e9b.jpg)

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-2
 - Graphics version: - (not sure how to check) 
 - Ingame language: English
# Additional context

None

**Comment by Maddremor** [comment]
While I agree that the bricked up windows look a bit strange, I don't see it as obvious that all buildings should be separated by alleys.

**Comment by matt32106** [comment]
> Different buildings should be at least 1 square away from each others

I'd rather say: buildings without alleys in between shouldn't have windows on those walls
