### ISSUE TITLE
URGENT CONTENT FIX NEEDED: there are no vegetarian deluxe nachos

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#41566]
# Is your feature request related to a problem? Please describe.
HELL YES IT'S RELATED TO A PROBLEM.
We have cheese nachos, meat nachos, and meat and cheese nachos, but no nachos with beans and veggies on them.
What the hell cataclysm? Literally unplayable.

# Describe the solution you'd like
Make me some damn nachos, that's what I'd like!
We should have "veggie nachos" that have tortilla chips, beans, and one of a selection of veggies (tomatoes, peppers, corn at least).
Then we should have "veggie deluxe nachos" that are the above plus cheese.

# Describe alternatives you've considered
Deleting the repository and calling it quits, I mean really.
Or doing it myself, but this is a good one for a starter to take the reigns on.

**Comment by meladath** [comment]
Cheese nachoes should be ok for veggies right? No vegan support though!

**Comment by I-am-Erk** [comment]
Sure they're edible for vegetarians, but why wouldn't vegetarians get tasty deluxe nachos

**Comment by esotericist** [comment]
shouldn't we also add veggie-based meat substitute that can be used for meat nachos?

**Comment by I-am-Erk** [comment]
Some day perhaps but for now we just need nachos like the kind I just ate

**Comment by raithwind** [comment]
Pull request merged, vegetarian nachos are now in the game. Issue can be closed.
