### ISSUE TITLE
Reload time not affected by the access time of the pocket the ammo is in.

### ISSUE THREAD

**Issue by Brian-Otten** [CleverRaven/Cataclysm-DDA#41563]
# A clear and concise description of what the bug is:

Access time to your pocket does not affect reload times.

# Steps to reproduce the behavior:

1. Make a player with a gun, magazine, and some ammo.
2. Put ammo for the gun in two pockets with different access times.
3. Moves to reload is the same.

# Expected behavior
Having your ammo in your jean pockets is a better idea than having it at the bottom of your duffel bag.

# Screenshots
![image](https://user-images.githubusercontent.com/47374323/85557723-54732200-b628-11ea-8537-22f4223a67d7.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-3486-ge60e4d8 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

**Comment by Menschheit** [comment]
And the reload time exists even if there is no magazine to load into the gun or whatever if the reloading fails.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-6401, see https://github.com/CleverRaven/Cataclysm-DDA/issues/44944#issuecomment-1040412805.
