### ISSUE TITLE
Liquids freezing become "none" item

### ISSUE THREAD

**Issue by TheJazziestCat** [CleverRaven/Cataclysm-DDA#41574]
# Describe the bug

Liquids in containers that freeze and then thaw become a "none" item that cannot be removed from the container.

# Steps To Reproduce

1. Obtain a bottle of water
2. Let it freeze overnight
3. Drop it in the basement to thaw
4. Find "plastic bottle with none."
Optionally:
5. Attempt to 'U'nload the bottle with no result.

# Expected behavior

Ideally, clean water (frozen) should thaw into clean water (cold) rather than thawing into none.

# Versions and configuration

- OS: Debian "buster"
- Game Version: 0.E-3407-g845884a
- Graphics Version: Terminal

# Additional context

This happens with fluids other than water and containers other than plastic bottles, too—I've seen it happen with milk in a gallon jug and dark cola in large plastic bottles.

Probably related in some way to [this issue.](https://github.com/CleverRaven/Cataclysm-DDA/issues/41403#issue-641021017)

**Comment by bloodraven983** [comment]
Hhmmm... I have a freezer in my base, I could put in it some plastic bottles of water and see what happens

but when i posted that bug I found that the "none" content was about non freezing content like multivitamin pills, oxydizing powder and chemical that shouldn't freeze and thaw

**Comment by akirashirosawa** [comment]
I started game from 0 day of spring and got the same bug. All liquids in the evac shelter froze and turned to `none` after load save. I will try to fix it.

**Comment by akirashirosawa** [comment]
@anothersimulacrum I think, It is not a `Mechanics: Temperature`, it is `Items: Containers`. Frozen liquid cannot get into the bottle, because the neck is too narrow :)
