### ISSUE TITLE
Change Shovel/Digging Stick to Use from Adjacent 

### ISSUE THREAD

**Issue by evankimori** [CleverRaven/Cataclysm-DDA#41571]
# Is your feature request related to a problem? Please describe.
Reason I brought this up is because if a character has a broken arm or not enough carrying capacity, they cannot Wield/carry a shovel or digging implement and with current system in PR10785 is that it drags the (tool) under the character's square if (A)ctivated which in turn blocks the character from being able to dig a pit in the first place.

# Describe the solution you'd like
Requesting that these Digging tools be changed to 'Use from Adjacent' functionality since having said broken arm or no carrying/wield capacity is basically a death sentence making a character unable to dig pits to find Stone, Clay etc for Deserted Island and Wilderness scenarios etc being exposed to excess cold which breaks limbs quickly if you're unable to make fire.

**Comment by mlangsdorf** [comment]
Shovels don't have ALWAYS_TWOHAND, so having a broken arm shouldn't prevent you from wielding them.

On the other hand, having a broken arm should pretty much prevent you from using a shovel to do any serious digging.

I also don't see the relationship between digging and making a fire.

Finally, having a broken arm while being on a deserted island in the early New England spring should be pretty close to a death sentence so I think, overall, things are working just fine as they are.

**Comment by anothersimulacrum** [comment]
Fires in deep pits won't spread to other tiles if they don't contain deep pits.

**Comment by mlangsdorf** [comment]
I can maybe see how you could scrape out a shallow pit with a shovel and a broken arm, but a deep pit is not feasible.

**Comment by evankimori** [comment]
Well given those stances: is it fair really to ask for a 'Use from Adjacent tile' function for situations where you cannot wield the item due to damage of limbs? 

From current testing: limbs less than 10HP cannot wield tools (e.g. (Naked & Afraid scenario) Digging Stick to dig Fire Circle/Improvised Shelter pit) and damage to those limbs from Cold will deplete them further quickly if not covered. I understand the stance on realism where if you cannot wield or have the tool in an inventory space that it cannot be used, esp since using said tool drags it into the same space as the character and Pits cannot be dug once any item is in the same space as the pit. Same applies to having the tools within usable range (referencing the N&A scenario again) where this particular item has to be Dragged around or wielded but essentially a death sentence if cold cripples you quite quickly for one reason or another.

Another option I'd like to ask considered is if pits can be set to be dug even with items in the same space and displace/drop those items into the same pit. Or...is this not within fairness/design goals?

**Comment by matt32106** [comment]
>  cannot Wield/carry a shovel or digging implement

Then how are you supposed to dig in that case? Allow adjacent digging would make no difference, or am I missing something?

**Comment by evankimori** [comment]
> > cannot Wield/carry a shovel or digging implement
> 
> Then how are you supposed to dig in that case? Allow adjacent digging would make no difference, or am I missing something?

Currently, if you are unable to wield or Inventory the Shovel/DS: it drags it under you to use but then you cannot execute a dig because (the item) is now in the way of the pit.

Now if you have a backpack etc, you can use and dig with TWO broken arms but I assume there's some kinda time/energy penalty but I haven't tested it personally. 

The current way I think is a little unfair in some ways that two broken arms and and Inventory system of some caliber still allows you to dig but unable to wield/two broken arms/no inventory basically is a death sentence because of how it drags the item under you instead as there isn't a 'Use from Adjacent' function instead where it does not need to be pulled into Inventory/hands/under the character...which impedes the pit digging in the first place.

**Comment by matt32106** [comment]
>  you cannot execute a dig because (the item) is now in the way of the pit.

not only, even if the object was not there, you could not dig because you cannot *wield* the object

nevertheless I agree that if having a bag is enough to let you dig even with no arms, it should be a bug

**Comment by evankimori** [comment]
Well seems like I found a bug then if it is that this whole situation isn't intended game design or behavior. Should I recreate a ticket in Bugs for adjusting this since according to input here that this behavior shouldn't be normal in the first place? 

Because then dig items would have to be adjusted to be auto-wield if it is this change has to be made.

**Comment by kevingranade** [comment]
This should be failing the attempt immediately when the wield check fails. In particular that means that other tools should *also* fail to activate if you can't wield them, and it should also be failing even if you have carrying capacity.
