### ISSUE TITLE
Items in containers in inventory don't get auto inventory letters & can't be favorited

### ISSUE THREAD

**Issue by redwing0** [CleverRaven/Cataclysm-DDA#41570]
# Describe the bug

Items being carried in inventory (anything that isn't being worn or wielded) do not get inventory letters assigned when the "auto inventory letters" option is enabled. Also setting the item as a favorite only works on worn & wielded items. 

When you drop and pick up a wielded item that's been assigned a letter, it keeps the letter but duplicate letters are assigned when you wield another item.

Items retain favorite status when dropped and picked back up into inventory. 

# Steps To Reproduce

Set the "Auto inventory letters" option in Options > Interface  to "Enabled"
Drop an item not being worn or wielded, and pick it back up.
Use the "*" key to favorite items in inventory.

Drop and pick up items, and wield and wear/take off items. 

# Expected behavior

Inventory letters assigned to all items in inventory when the option is enabled. Favorites being favorited. Inventory letters assigned are not duplicated.

# Versions and configuration

-----------------------------------------
14:18:44.166 : Starting log.
14:18:44.166 INFO : Cataclysm DDA version 0.E-3489-g6e97042
14:18:44.168 INFO : [main] C locale set to en_US.UTF-8
14:18:44.168 INFO : [main] C++ locale set to en_US.UTF-8
14:18:44.171 INFO : [options] C locale set to en_US.UTF-8
14:18:44.171 INFO : [options] C++ locale set to en_US.UTF-8
14:18:44.247 WARNING : opendir [./mods/] failed with "No such file or directory".
14:18:50.166 WARNING : opendir [./save/Camden-on-Gauley/mods] failed with "No such file or directory".
14:18:59.813 :  GAME REPORT:
- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.E-3489-g6e97042 [64-bit]
- Graphics Version: Curses
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

14:19:38.238 : Log shutdown.
-----------------------------------------

Linux 5.7.4-arch1-1 #1 SMP PREEMPT Thu, 18 Jun 2020 16:01:07 +0000 x86_64 GNU/Linux

**Comment by TimPollard** [comment]
I'm seeing this as well (also on Linux, so it's hypothetically Linux only). Interestingly the start off equipment seems to work OK, but anything new you pick up doesn't have an inventory letter.

```
18:34:08.508 :  GAME REPORT:
- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.E-3547-g7d8b01612f [64-bit]
- Graphics Version: Curses
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    DinoMod [DinoMod],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp]
]
```

**Comment by maxestorr** [comment]
I have this problem after updating to the latest experimental on Windows, I can corroborate that starting equipment is fine, and even equipment that had auto-assigned letters from the previous version (0.E stable) keep their letters, but any new equipment both on my previous save and any new games fails to receive automatic letter assignment.

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-3923-g7063a53 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
