### ISSUE TITLE
Can't add liquids to any vehicle tank.

### ISSUE THREAD

**Issue by Enderlordalatreon** [CleverRaven/Cataclysm-DDA#41587]
# Describe the bug
Whenever I try and fuel vehicles it says "No parts can be refilled". I have the fuel and an empty tank yet nothing.

Something is preventing refueling, when pressing the F key to refill a tank, I get the message "No parts can currently be refilled".

# Steps To Reproduce

Spawn vehicle, remove tank and replace with empty tank, try to refuel it, get message.

# Expected behavior

To refill a close to empty tank or simply fill an otherwise empty tank with any liquid, not just fuel.
![Annotation 2020-06-25 124809](https://user-images.githubusercontent.com/66154890/85762865-294d0900-b6e2-11ea-8fcb-4bf77a41e37f.png)

# Versions and configuration
Windows 10
Cataclysm-DDA experimental build #10786

# Additional context
Mods:
  "dda",
  "no_npc_food",
  "aftershock",
  "Arcana",
  "crt_expansion",
  "M.A.G.Armory",
  "magiclysm",
  "Cata++",
  "Malkeus_Enhancement_Mod",
  "Nechronica_Redux",
  "blazemod",
  "pneumo_fun",
  "mutant_npcs_10492",
  "psychiclysm",
  "collectablemod",
  "XEAS",
  "TCW_BOX",
  "AAA",
  "adv_gear",
  "advtech",
  "aftermarket_leadworks",
  "ArmUpPAUtil",
  "ArmUpSurvEx",
  "bioco",
  "Bionic_Space_Expander",
  "bio_recipes",
  "bsam",
  "ExArch",
  "Mad-Cyber-Science",
  "Medieval_Mod_Reborn",
  "extgear",
  "demon_spider_a",
  "modern_weapon",
  "More_Armors",
  "More_Tools",
  "more_survive_notes",
  "mo_veh",
  "Pix's Shit",
  "pizza_delivery",
  "WHALEYHAIR1",
  "Graphical_Overmap",
  "Graphical_Overmap_Magiclysm",
  "Merchant",
  "ProjectKawaii",
  "NM_wpns",
  "Red's Odd Additions",
  "sarcophagi_access",
  "amplified_players_features",
  "UDP_No_Debug_Tile",
  "Tankmod_Revived",
  "oa_early_game_mutations_mod",
  "morlock_village",
  "cityside",
  "Dorf_Life",
  "P_Caches",
  "zets_hair_extensions_undead",
  "MMA",
  "MMA_Magiclysm",
  "recruitment_options",
  "monstergirl_professions",
  "more_survivor_stuff",
  "Youkai_Disco",
  "PK_REBALANCE",
  "noctpk",
  "modular_turrets_remake",
  "DinoMod",
  "GOV_BANDITS",
  "modular_turrets_no_blacklist",
  "Xeno's SAS4",
  "Thrown",
  "VermilionMod",
  "Survivors_Lost_item",
  "shardstuffgoat",
  "shardstuff",
  "sonic",
  "rubber_band_sheath",
  "beamswordmod",
  "Power_Armor_Additions",
  "fallout",
  "secronom",
  "Akimbo_Mod",
  "Medieval_Stuff",
  "npc_traits",
  "mxocosmetics",
  "zets_hair_extensions",
  "more_locations",
  "zets_hair_ext_more_locations",
  "zets_hair_ext_pk_rebalance",
  "Arts' Guns",
  "xtal",
  "boats",
  "Mining_Mod",
  "DP_No_Debug_Tile",
  "winning_dda",
  "stamina_pool_buff",
  "stamina_regen_buff",
  "moonsword-mod" <---- Mod made by [u/2Sc00psPlz](https://www.reddit.com/r/cataclysmdda/comments/hbkb5k/my_current_run_right_now_im_a_season_in_so_far/) on Reddit, good mod.

**Comment by Enderlordalatreon** [comment]
WHOOPS pressed enter too fast, one sec let me fill it in.

**Comment by anothersimulacrum** [comment]
Cannot reproduce 
![image](https://user-images.githubusercontent.com/42699974/85766307-c5b7e100-b6cb-11ea-9745-d0d2d9ee68d3.png)

Likely an issue with whatever mod has those tanks.

**Comment by Enderlordalatreon** [comment]
Maybe, however there are other people having this issue as well.
https://www.reddit.com/r/cataclysmdda/comments/hd5jkx/cant_refuel_boat_with_jerrycan/

**Comment by anothersimulacrum** [comment]
That was fixed in build 10781, see #41469

**Comment by Enderlordalatreon** [comment]
I see, however I'm on build #10786
I just made a "vanilla" world and...
![Annotation 2020-06-25 131106](https://user-images.githubusercontent.com/66154890/85766961-88604d00-b6e5-11ea-9810-d8a6be7011cc.png)
![Annotation 2020-06-25 131128](https://user-images.githubusercontent.com/66154890/85767016-94e4a580-b6e5-11ea-91ff-0a98f4d275c1.png)
I'll update again and see if that works.

**Comment by anothersimulacrum** [comment]
It's important to follow the instructions in the template, it'll generate more accurate version information than what build you're on.

**Comment by Enderlordalatreon** [comment]
I see. I will read it again, thank you.

**Comment by Enderlordalatreon** [comment]
I Scorched Earth the install directory, reinstalled the game again, works like a charm, sorry for the trouble. Must have been some something left when I originally updated.

**Comment by anothersimulacrum** [comment]
No worries, glad it's sorted out!
