### ISSUE TITLE
Seg Fault when reloading with shotgun speedloader

### ISSUE THREAD

**Issue by Tevervin** [CleverRaven/Cataclysm-DDA#41582]
# Describe the bug

Trying to reload m1014, Wingmaster and other similar shotguns (with speedloader chute mod attached) with shotgun speedloader (6- or 8-round) results in a seg fault crash.

# Steps To Reproduce

1. Spawn a shotgun with loading port mod slot (like m1014 or Remington 870 Wingmaster), speedloader chute, shotgun 8-round speedloader.
2. Unload shotgun.
3. Modify shotgun with speedloader chute. 
4. Press reload button, select shotgun.
5. Seg fault crash.

# Expected behavior

Rounds from speedloader should transfer to shotgun.

# Versions and configuration

- OS: Windows
    - OS Version: Windows 8.1
- Game Version: 0.E-3486-ge60e4d8 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

Also crashes on default mod world.

# Additional context

[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4831093/config.zip)

As for revolver's speedloader - they just doesn't work. Maybe that is another issue.

**Comment by wapcaplet** [comment]
Confirmed - with a shotgun modded with a speedloader chute, and a 6-round speedloader full of ammo, selecting `r`eload on the shotgun gives a segfault crash.

![image](https://user-images.githubusercontent.com/238395/85807781-26690d00-b710-11ea-8916-cf3d08543a30.png)

Note: This crash does *not* occur if the 6-round speedloader is empty; in that case I am prompted to reload with individual shot/slug rounds.

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-3502-g6313122ed0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

Save game to reproduce:
[shotgun-speedloader.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4834459/shotgun-speedloader.zip)
