### ISSUE TITLE
Seg fault when exame esbit_stove

### ISSUE THREAD

**Issue by MikuMiddo** [CleverRaven/Cataclysm-DDA#41580]
# Describe the bug
When you [e]xame or [v]iew the esbit stove,the game seg fault

# Steps To Reproduce
1.found one in somewhere(you can't spawn one in debug menu because you will get a debug information even when you select it)
2.exame it
3.the game crash

# Expected behavior
normal exame it as usual.

# Screenshots
![image](https://user-images.githubusercontent.com/53809752/85688518-6924e800-b704-11ea-9025-a34cd32773ec.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-3489-g6e97042 [64-bit]
- Graphics Version: Tiles
- Game Language: 系统语言 []
- Mods loaded: [
    浩劫余生 [dda],
    禁用NPC需求 [no_npc_food],
    C.R.I.T 扩展 [crt_expansion],
    变形怪工业 [blazeindustries],
    大魔法 [magiclysm],
    余波未尽 [aftershock],
    恐龙世界 [DinoMod],
    Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
    疯狂大灾变 [crazy_cataclysm],
    神话武术 [MMA],
    移除真菌类怪物 [No_Fungi],
    Fuji的军事职业Mod [fuji_mpp],
    技能提升属性 [StatsThroughSkills],
    敏捷速度加成 [speedydex],
    杀怪提升属性 [stats_through_kills],
    余震个人用强化模组 [After_Shock_Personal_UsageMod],
    无限手套 [Infinity_Gauntlet]
]

# Additional context
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4830144/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4830145/crash.log)

**Comment by KorGgenT** [comment]
#41539 possibly related?
