### ISSUE TITLE
Show the quantity of the resulting item already available

### ISSUE THREAD

**Issue by Duck13Tales** [CleverRaven/Cataclysm-DDA#41592]
# Is your feature request related to a problem? 

It is sometimes hard to keep track of all the things you are crafting and that still need to be done so this would help a lot. This feature isn't related to a problem but would be a good improvement in the "quality of life".

# Describe the solution you'd like
When we select an item to craft, it would be great if the game showed how many of that is available in the crafting range the same way it shows how many ingredients you have on reach.

# Describe alternatives you've considered
Show somewhere in the crafting window how many of that item you already have.

# Additional context
There is the print that shows that the game tells me how many flatbread I have when using it as an ingredient but there isn't a way to know it when I am cooking flatbread besides looking somewhere else.

![flatbread total](https://user-images.githubusercontent.com/67176313/85796367-32ed6580-b710-11ea-8c70-647c159c8e15.png)

**Comment by matt32106** [comment]
This could be displayed in parenthesis just after the product name in the left column:
`
flatbread (16)
`
