### ISSUE TITLE
Death upon loading old save

### ISSUE THREAD

**Issue by meladath** [CleverRaven/Cataclysm-DDA#41604]
# Describe the bug

Death upon load.

# Steps To Reproduce

1. Load any game save made before 10787.
2. Observse instant death.

# Expected behavior

Not dying as soon as you load in.

# Versions and configuration

Current master, build 10787, no mods.

# Additional context

Most likely related to #41194

Note, this does stop you creating a new char and playing/saving/loading that save. But loading an old save will result in everything being dead.

**Comment by hexagonrecursion** [comment]
also related: #41600

**Comment by Fris0uman** [comment]
Yes #41600 will fix it

**Comment by ifreund** [comment]
closed by #41600
