### ISSUE TITLE
Calorie Usage Too High

### ISSUE THREAD

**Issue by Ichthysdekilt** [CleverRaven/Cataclysm-DDA#41615]
# Describe the bug
Apologies if this was in another bug - some searching didn't reveal anything.

Currently it's impossible to keep my survivor alive due to needing to constantly eat more than is possible with 200kcal+ foods.  This seems to have occurred at some point in the recent experimentals and possibly as a result of doing multiple types of exercise (waiting, running, walking, melee and bow combat) in rapid succession, or as a result of going from XXXL flaw to a normal weight.

# Steps To Reproduce

1. Make a character with XXXL flaw
2. Lose weight to normal range
3. Perform lots of different activities with varying exercise levels in rapid succession
4. Wait until hungry
5. Keep constantly Full with 200+kcal foods 
6. Chow down on some anti-parasitics to ensure that's not causing any issues
7. Starve
8. Repeat over a few days until dead

# Expected behavior

Regardless of exercise, staying constantly Full on candy should cause you to gain weight, not starve to death.

# Screenshots

# Versions and configuration

 - OS: Win10
 - Game Version: 10786
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: dda, disable NPC needs, CRIT Expansion, Alternate Map Key, Crazy Cataclysm, MMA, Grahpical Overmap, sees-player retro, Fuji's Military, SpeedyDex, StK, StS

# Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4839448/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4839449/crash.log)

**Comment by anothersimulacrum** [comment]
You're on the build right before the fix #41567.
