### ISSUE TITLE
Hexamine error crash

### ISSUE THREAD

**Issue by StefanMiletic994** [CleverRaven/Cataclysm-DDA#41618]
# Describe the bug

When trying to get something from the rack hexamine error pops out and crashes.

# Steps To Reproduce

Examine the southwest rack with items.

# Expected behavior

Should give item list.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-3489-g6e97042
 - Graphics version: Undead People Tiles
 - Ingame language: English
 - Mods loaded: 
Disable NPC Needs
Aftershock
Blaze Industries
C.R.I.T Expansion Mod
Alternative Map Key
More City Locations
Jurry-Rigged Robots
Bionic Slots
Speedy Dex

# Additional context

[crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4839606/crash.zip)
[debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4839607/debug.zip)
[Rose Valley.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4839619/Rose.Valley.zip)

**Comment by wapcaplet** [comment]
This should have been fixed in #41590, just patched yesterday.

@StefanMiletic994 please update your build and let us know if the error still occurs.

**Comment by StefanMiletic994** [comment]
Sorry for the delay, it works.
