### ISSUE TITLE
Cannot learn fencing by reading "the modern swordsman", bug or not?

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#41616]
# Describe the bug
I cannot learn fencing by reading "the modern swordsman", I keep getting messages saying I failed to learn. See image below:
![image](https://user-images.githubusercontent.com/7557986/85906293-28b19100-b80e-11ea-91e8-c73d8bc00178.png)

# Steps To Reproduce
Read the modern swordsman. Shift-R + read until level or tired.

# Expected behavior
Learn the fencing martial art.

# Screenshots
Character stats
![image](https://user-images.githubusercontent.com/7557986/85906441-9cec3480-b80e-11ea-9d35-93718b48ae24.png)

Martial arts
![image](https://user-images.githubusercontent.com/7557986/85906473-b55c4f00-b80e-11ea-8d59-dbd19401edee.png)

# Versions and configuration
Last version between nested inv.
- OS: Linux
    - OS Version: LSB Version: core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch; Distributor ID: Ubuntu; Description: Ubuntu 18.04.4 LTS; Release: 18.04; Codename: bionic; 
- Game Version: 0.E-1477-g8cea0fc [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Stats Through Skills [StatsThroughSkills],
    Alternative Map Key [alt_map_key],
    No Fungal Monsters [No_Fungi]
]

**Comment by wapcaplet** [comment]
I could not reproduce the issue in a newer experimental build 0.E-3531. Created a new character in a new world, with 0 skills, and managed to learn Fencing from "The Modern Swordsman" in just 20 seconds:

![image](https://user-images.githubusercontent.com/238395/85908566-d1da9600-b7d2-11ea-821b-752254d5b564.png)


- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-3531-gff1ff7ea9f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by matt32106** [comment]
Err, it's a joke or what, I was getting the char ready for a save so that I could post it for testing and this just happened while I was hitting a key to stop the current batch of learning:
![image](https://user-images.githubusercontent.com/7557986/85908730-9a8dd880-b816-11ea-80c4-d79223e16181.png)

I had been looking at those failure messages for ages it semmed, just had to be really patient I guess. 

Sorry for the trouble.
