### ISSUE TITLE
repairing a backpack requiring variable amount of patches

### ISSUE THREAD

**Issue by bloodraven983** [CleverRaven/Cataclysm-DDA#41612]
# Describe the bug

amount of leather patches required for repairing a tactical leather backpack varies every time i pickup some leather patches

# Steps To Reproduce

I don't honestly know how to reproduce it

# Expected behavior

An item should have a fixed amount of materials required for mending and repairing

# Screenshots

it was less patches required before
![image](https://user-images.githubusercontent.com/66170818/85891105-de6ce780-b7ee-11ea-802b-d4b343dff805.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-3489-g6e97042 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi]
]

**Comment by EvgenijM86** [comment]
Do you always do some crafting/repair job perfectly in real life? Or do you sometimes waste material? I think some randomness is appropriate.

**Comment by anothersimulacrum** [comment]
Randomness may be appropriate, but this appears to be linked to the volume contained in the item.

**Comment by bloodraven983** [comment]
how about no?

what kind of repair (at tailoring 7 so not a noob ingame) requires half the material for one stage of repair? it's clearly a bug

**Comment by wapcaplet** [comment]
Confirmed - the number of patches required appears to be related to the current "Volume" of the backpack you want to repair, which for non-rigid backpacks, will vary based on how full of stuff it is.

For example I have this damaged leather backpack that is 2.0 L in volume when empty:

![image](https://user-images.githubusercontent.com/238395/85895234-85cc2900-b7b3-11ea-9e5d-7557ffa85069.png)

When I `a`ctivate a sewing kit and try to repair the backpack, I get
```
You don't have enouth leather patches to do that.  Have: 0, need: 1
```

However, if I stuff a bunch of items into the backpack, its total volume is increased to 21.0 L:

![image](https://user-images.githubusercontent.com/238395/85895387-dba0d100-b7b3-11ea-831d-e80b0e4fc163.png)

Trying to `a`ctivate the sewing kit and repair it now, I need 9 patches: 

```
You don't have enouth leather patches to do that.  Have: 0, need: 9
```

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-3531-gff1ff7ea9f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
