### ISSUE TITLE
Throwing axe recipe with twice the same "tool required"

### ISSUE THREAD

**Issue by Duck13Tales** [CleverRaven/Cataclysm-DDA#41622]
I noticed that the recipe for the throwing axe states twice the "pair of metal tongs" in the "tools required" section.

You only need to try to craft to see the recipe.

I am using using the CDDA 0.E-2 with the mods:

DDA
Disable NPC needs
Stats through skills
Stats through kills
SpeedyDex

![throwing axe recipe](https://user-images.githubusercontent.com/67176313/85913444-53e6b100-b80b-11ea-89f1-9a3a2a60e163.png)

**Comment by hexagonrecursion** [comment]
One is from `"tools": [ [ [ "tongs", -1 ] ] ]`

https://github.com/CleverRaven/Cataclysm-DDA/blob/169da945519697e3b9d8427b1e07a90d099fd9ac/data/json/recipes/recipe_weapon.json#L1574-L1587

Another is from `"using": [ [ "blacksmithing_standard", 3 ], ...]`

https://github.com/CleverRaven/Cataclysm-DDA/blob/de2971d1663b6fbb1fefa332298cb23714f5656d/data/json/requirements/toolsets.json#L38-L44
