### ISSUE TITLE
'A'ctivating a First Aid Kit led to the antiseptic being on the floor spilled 

### ISSUE THREAD

**Issue by Stephen2** [CleverRaven/Cataclysm-DDA#41628]
# Describe the bug
Had 2 first aid kits - used `a` to `Get content`
Then the antiseptic & saline solution ended up spilled on the floor

# Steps To Reproduce
1. Have First Aid Kit
2. `a`ctivate to Get Content
3. See that antiseptic is on floor

# Expected behavior
Antiseptic is in a neat little bottle in your inventory.

# Screenshots
![image](https://user-images.githubusercontent.com/4276422/85920335-2276ef80-b8b6-11ea-9dc1-e3ee648fe421.png)

![image](https://user-images.githubusercontent.com/4276422/85920327-1854f100-b8b6-11ea-80ef-2a532c4d694a.png)

# Versions and configuration
- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.E-3550-g6770666a22 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context
Built from hash `fc61c75b43`

**Comment by Stephen2** [comment]
There was also a `bottle of antiseptic`!  :partying_face: 

I guess this way of showing the antiseptic on the floor is a side-effect of the containered inventory work going on?

I'll leave this here, in case you didn't actually want things to display in this way.

It was confusing for me to be honest.

**Comment by hexagonrecursion** [comment]
Can not reproduce
- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 32 (Thirty Two); Release: 32; Codename: ThirtyTwo; 
- Game Version: 0.E-3553-ge888413 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by bloodraven983** [comment]
> There was also a `bottle of antiseptic`! 🥳
> 
> I guess this way of showing the antiseptic on the floor is a side-effect of the containered inventory work going on?
> 
> I'll leave this here, in case you didn't actually want things to display in this way.
> 
> It was confusing for me to be honest.

not  a bug, everything works, just pay attention to your surroundings

**Comment by hexagonrecursion** [comment]
I figured out how to reproduce it.
1. Wish for a first aid kit
2. [a]ctivate it
3. open the [w]ield menu
4. See "can't wield spilt liquids"

Another one:
1. --/--
1. --/--
1. open the [a]ctivate menu
1. See "can't pick up spilt liquids"

Notes:
- the [E]at menu lists the antiseptic, and allows is to be consumed. It also does not list the bottle
- the [g]: "pick up nearby items" menu does not list the antiseptic
- the [/]: AIM menu does not list the antiseptic

I agree with @Stephen2: the game UI could use some more consistency.

**Comment by anothersimulacrum** [comment]
Looks like liquids in containers on the floor are counted as spilled in some contexts.

**Comment by wapcaplet** [comment]
Cannot reproduce in 0.E-9603-g42468f6cab as described in the original bug report. Activating a first aid kit correctly drops all components onto the ground, with the antiseptic still in its bottle. Nothing is spilled.

The fact that the `w`ield menu includes liquids at all is certainly a bug. I opened #47488 for this.
