### ISSUE TITLE
activating liquid in containers without the "resealed" flag spills the liquid

### ISSUE THREAD

**Issue by Duck13Tales** [CleverRaven/Cataclysm-DDA#41637]
If you put a liquid in a container that don't have the "resealed" flag then store the container in a cupboard or the like, when you try to "a"ctivate the liquid you don't use it, store the container in your inventory and spill the liquid. In the case I used the cattail jelly as an example.

It happens with any item that can be used as a container but don't have the "resealed" flag. Just store a liquid in the container and then put it in a cupboard etc and when you "a"ctivate the liquid you won't use it and instead store the container in the inventory and spill the liquid.

I think that the correct would be prompt the action to wield the container if needed, but spilling the liquid on the floor can be annoying.

I am using using the CDDA 0.E-2 with the mods:

DDA
Disable NPC needs
Stats through skills
Stats through kills
SpeedyDex

![aluminum can with cattail jelly](https://user-images.githubusercontent.com/67176313/85926828-6b0fb800-b878-11ea-8912-9a3a4caf7c59.png)

**Comment by ZhilkinSerg** [comment]
Please try reproducing in latest experimental version too.

**Comment by Duck13Tales** [comment]
I just tried updating to the newest experimental, for this I only copied my folder and unpacked the the newest package to it overwriting any files but then it is giving an error due to the tutorial.json:

> DEBUG    : Error: data/mods//dda/../../json/tutorial.json: line 3:12: unrecognized JSON object
> 
> [
>   {
>     "type":
>            ^
>             "tutorial_messages",
>     "messages": [
>       "Welcome to the Cataclysm tutorial!  As you play, pop-ups like this one will appear to guide you through the basic game actions.  Pressing spacebar will close the pop-up.",
> 
> 
>  FUNCTION : bool main_menu::load_character_tab(bool)
>  FILE     : src/main_menu.cpp
>  LINE     : 1155
> 

How do I solve this?

Is there an easier way to update to the latest experimental? Do we usually are able to keep our character and world when updating the experimentals?

**Comment by anothersimulacrum** [comment]
To update you should just copy over your save/ and config/ files into a the new folder.

**Comment by Duck13Tales** [comment]
Just did as you said but it prompted the message:

 

> DEBUG    : Item rm13_armor was loaded with charges, but can not have any!
> 
>  FUNCTION : void item::io(Archive&) [with Archive = io::JsonObjectInputArchive]
>  FILE     : src/savegame_json.cpp
>  LINE     : 2363

It said the same thing about the bone flute though I was able to start the game.

Will it cause any problems?

**Comment by Duck13Tales** [comment]
I was able to go on and drop my inventory after pressing "space" a few times. It seems to have solve the problem.

**Comment by Duck13Tales** [comment]
In the newest build when I put the plastic bottle in a table and try to "a"ctivate it says that "I can't pickup spillt liquids", though the cattail jelly is all right in the plastic bottle over the table.

![cattail jelly](https://user-images.githubusercontent.com/67176313/85933364-90b6b480-b8ac-11ea-8f1b-617b975205be.png)
