### ISSUE TITLE
misleading "a"ctivation

### ISSUE THREAD

**Issue by Duck13Tales** [CleverRaven/Cataclysm-DDA#41636]
If you have a cast-iron frying pan with cattail jelly in it and try to "a"ctivate it will open the activation window with the option to Apply the cattail jelly to the wounds but if you select it you will instead try to heat food with the frying pan.

It happens with any item that can be used to heat food but has cattail jelly in it.

I think that instead it should open the window with the "heat food" activation or open with the "..." that prompt a second window with all the possible "a"ctions like in the second print.

I am using using the CDDA 0.E-2 with the mods:

DDA
Disable NPC needs
Stats through skills
Stats through kills
SpeedyDex

![cast-iron pan with antiseptic](https://user-images.githubusercontent.com/67176313/85926222-4a456380-b874-11ea-81c6-b760a0cb6d7d.png)

Here is a print that shows the "..." option.

![cast-iron frying pan](https://user-images.githubusercontent.com/67176313/85926204-326ddf80-b874-11ea-8c69-e36ab7740d25.png)

**Comment by ZhilkinSerg** [comment]
Please try reproducing in latest experimental version too.

**Comment by Duck13Tales** [comment]
In the newest build (b10792) when I am with the frying pan in hand I am able to select to use the cattail jell or "heat up food" with the frying pan, but I am unable to use the cattail jelly when the frying pan is in a cupboard or over a table.

Now this problem is mostly like the one in #41637 

![frying pan cattail jelly](https://user-images.githubusercontent.com/67176313/85933487-dcb62900-b8ad-11ea-85df-15d890d476fa.png)

**Comment by KorGgenT** [comment]
i'm not clear what's misleading here - you're activating a cast iron pan and expecting it to heal your wounds?

**Comment by Duck13Tales** [comment]
The frying pan has cattail jelly stored in it...
