### ISSUE TITLE
Tone in monster descriptions, and suggested changes

### ISSUE THREAD

**Issue by GlyphGryph** [CleverRaven/Cataclysm-DDA#4163]
We need to discuss what sort of tone we're looking for in Monster descriptions, how much variance we want in that tone and when it might be acceptable to diverge, what determines divergence and where we should diverge to, and a bunch of other things having to do with conveying descriptions to the player in at least something approaching a consistent way.

**Comment by illi-kun** [comment]
Closing due to lack of interest.
