### ISSUE TITLE
Transparency doesn't update after destroying a web

### ISSUE THREAD

**Issue by Fris0uman** [CleverRaven/Cataclysm-DDA#41641]
# Describe the bug

Light is still block by a tile even after removing the web from it

# Steps To Reproduce

1. Place some max intensity web field
2. Walk on it
3. Free yourself
4. The web is gone but your view is still blocked

# Expected behavior

After removing the web the view should be clear

# Screenshots
Before:
![image](https://user-images.githubusercontent.com/41293484/85933415-09cb0180-b8d7-11ea-8f3c-4a15b20439cf.png)

After:
![image](https://user-images.githubusercontent.com/41293484/85933422-10f20f80-b8d7-11ea-9a10-130c5ef617b4.png)

# Versions and configuration

 - OS:  Windows 10 
 - Game Version: compiled from master, 41108 is the last PR merged
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded:   "dda",
  "no_npc_food",
  "my_sweet_cataclysm"

# Additional context

**Comment by Menschheit** [comment]
![temp](https://user-images.githubusercontent.com/28317565/86297835-a0136600-bbfc-11ea-9c07-4a458a452273.PNG)

The second if-condition prevents transparency updating after you destroyed a web. I don't understand why this condition should exist.

**Comment by Menschheit** [comment]
Update: Got it.
![temp](https://user-images.githubusercontent.com/28317565/86299487-b4f1f880-bc00-11ea-891a-4a5cc6e597f1.PNG)
