### ISSUE TITLE
deluxe veg beans and rice makes you engorged with very hungry status

### ISSUE THREAD

**Issue by bloodraven983** [CleverRaven/Cataclysm-DDA#41653]
# Describe the bug

this recipe makes you engoged even when you are with a very empty stomach

# Steps To Reproduce

the content of the recipe I used are:

dried beans
dried rice
plant marrow
salt

# Expected behavior
maybe it should fill stomach a bit less

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-3555-ge061dbb [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi]
]

**Comment by anothersimulacrum** [comment]
Confirmed
![image](https://user-images.githubusercontent.com/42699974/85953215-9ac7ca00-b923-11ea-80fd-ec36cde92667.png)

**Comment by bloodraven983** [comment]
beans and rice made me full too but i drank some pine needle tea before so wasn't so empty

**Comment by bloodraven983** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/41662

grats to the devs and contributors!
