### ISSUE TITLE
Infinite Farmer Credit Farm

### ISSUE THREAD

**Issue by MathTauAthogen** [CleverRaven/Cataclysm-DDA#41665]
I can get infinite farmer credit with zero effort whatsoever.

# Steps To Reproduce

1. Acquire exactly 1 log.
2. Find a farmer NPC who gives you chits.
3. Deliver 1 log.
4. Follow the prompts.
5. Receive 1 chit for your log.
6. Talk to farmer again.
7. Deliver 1 log.
8. Follow the prompts.
9. Receive 1 chit for your log.
10. Talk to farmer again.
11. Deliver 1 log.
12. Follow the prompts.
13. Receive 2 chit (?!) for your log.
14. Repeat ad infinitum for infinite credit

# Expected behavior

One would expect, logically, for you to lose your log after the first delivery and not be able to immediately return to the menu and redeliver the same log without losing it. However, you get the chits and don't lose the log, and for some reason, while you would expect that what the NPC says you get is what you get, you begin to receive not 1 chit as the farmer says but instead "2 chit".

# Screenshots

![Screenshot from 2020-06-28 19-14-35](https://user-images.githubusercontent.com/34319964/85960756-f4f07b80-b973-11ea-977f-7fe05f94e083.png)
![Screenshot from 2020-06-28 19-15-13](https://user-images.githubusercontent.com/34319964/85960758-f752d580-b973-11ea-89e0-689a6025e25d.png)
![Screenshot from 2020-06-28 19-16-04](https://user-images.githubusercontent.com/34319964/85960761-fb7ef300-b973-11ea-8531-99319bc5bc87.png)

The second and third screenshots are from different dialogs, after I exited and redid the conversation. I did nothing between them except for go back and talk again to the NPC.

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 18.04.4 LTS; Release: 18.04; Codename: bionic; 
- Game Version: 0.E-2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context

**Comment by RoyBerube** [comment]
The bug happens when you are wielding the item to be delivered. Tested with 2000 nails - in inventory is fine, but when wielded it does not delete them. A log is just more likely to be wielded due to its size.
