### ISSUE TITLE
Deconstruct/remove last part of a vehicle crashes the game

### ISSUE THREAD

**Issue by Duck13Tales** [CleverRaven/Cataclysm-DDA#41688]
If you create a vehicle and then try to disassemble/deconstruct the last part of it you crash the game. For it you just need to do:

1 - Craft a wooden frame or foldable wooden frame
2 - Start Vehicle construction with your frame
3 - "e"xamine your vehicle
4 - rem"o"ve your frame
5 - CRASH!

I am using using the CDDA 0.E-b10792 with the mods:

DDA
Disable NPC needs
Stats through skills
Stats through kills
SpeedyDex

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4848302/crash.log)

**Comment by SageB** [comment]
Seems like a duplicate of [https://github.com/CleverRaven/Cataclysm-DDA/issues/41464](https://github.com/CleverRaven/Cataclysm-DDA/issues/41464). I made a PR with a fix for that, and it's been merged, but I don't think it's in the latest build yet.

**Comment by Duck13Tales** [comment]
Sorry. I searched but couldn't find. Then since it isn't in the latest build should I close or keep open till it is fixed in the next build?

**Comment by Duck13Tales** [comment]
Just tried in the latest experimental and it worked.
