### ISSUE TITLE
@ can wield butane

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#41682]
# Describe the bug

If you drop a lighter on the ground you can wield the butane.

# Steps To Reproduce

1. Wish for a lighter
2. [d]rop it
3. open the [w]ield menu
4. see "butane"
5. wield the butane
6. see a log message: "it takes you a long time to wield your butane"

# Expected behavior

It should not be possible to hold butane with your bare hands

# Screenshots

none

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 32 (Thirty Two); Release: 32; Codename: ThirtyTwo; 
- Game Version: 0.E-3564-g618677d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    sees-player icon, retrodays [sees_player_retro]
]

# Additional context

none

**Comment by MatiasFito** [comment]
Lol wow, this sounds intresting i will look into this, let you know what i find. Thanks for the report! :+1:

**Comment by MatiasFito** [comment]
Found the issue, the butane ammo was missing the **phase: liquid** attribute in ammo.json, i checked and it did have it in the android folder structure. Issue is that now that the butane is a liquid the lighter and butane can are crashing the game because they were prepared to store the bugged non liquid butane (so now you can't store the correct liquid butane anywhere lol), I will work on this and send the PR as soon as i checked everything properly.

**Comment by anothersimulacrum** [comment]
The fix to that will be to add watertight to the pockets.

**Comment by hexagonrecursion** [comment]
Here is the odd part: you can only wield the butane if the lighter is on the ground. You can't wield it when it is in your inventory. Also: the lighter has NO_UNLOAD.
https://github.com/CleverRaven/Cataclysm-DDA/blob/07b95d3500e4c955b1f066e02385f7796bf016cd/data/json/items/tool/fire.json#L92-L110

**Comment by MatiasFito** [comment]
@anothersimulacrum oh i didnt see this message last night!, but i found the solution, i looked up the flamethrower to look for differences and found that beutiful "waterright" attribute. I already checked and the lighters are working perfectly again. @hexagonrecursion  Now i'm curious is the NO_UNLOAD incorrect?, i don't remember you could unload non refillable lighters :thinking: . If any maintainer can confirm this flag is incorrect i can fix it too before creating the PR. Let me know, i'll be back in a few hours cheers!  :wave:
