### ISSUE TITLE
Improve "Analyze Zombies Blood" quest description to be more clear to novice players

### ISSUE THREAD

**Issue by leemuar** [CleverRaven/Cataclysm-DDA#41683]
# Describe the bug

I took "Analyze Zombie Blood" quest from a Doctor in Free Merchant base. Went to a hospital marked on a quest map, there were A LOT of zombies inside so I thought it would be a good idea to save ammo by burning an entrance. Turned out I've burned the entire hospital down. With all equipment inside: no more computers or centrifuge, all destroyed by fire. I can not analyze the blood there any more

Problem is the quest is still active, not marked as "failed", and the quest marker on map still points to this hospital, now destroyed

# Steps To Reproduce

1. Go to Free Merchant base, talk to Doctor, get "Analyze Zombie Blood" quest
2. Go to a hospital marked on map, destroy all equipment inside
3. Open map, make sure the quest marker still points to a destroyed hospital where you can not finish the quest

# Expected behavior

Remove quest marker if required equipment is destroyed.
Make it clear to a player what to do if this happens: maybe Doctor's new dialogue option to point to another hospital

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.E-2 [64-bit]
- Graphics Version: Tiles
- Game Language: Системный язык []
- Mods loaded: [
    Тёмные Дни Впереди [dda]
]

**Comment by mlangsdorf** [comment]
Not a bug.  You can analyze the blood at any centrifuge with a working computer; it doesn't have to be that one.

**Comment by leemuar** [comment]
From player's perspective it is a bug: pointing to a location where it's impossible to finish the quest. It is confusing and misleading. It is not clear to a unexpierenced player what to do.

I suggest:

- (minimum) to expand the quest's description, add info about hospitals, computer and centrifuge. My current quest description only shows "analyze the blood, coords: X Y"
- (OK) quest marker should disappear if required equipment is destroyed
- (best) all above + add dialogue option to a Doctor to request another hospital location if the first one is destroyed

If you don't like the "Bug" label - lets assign "Feature/improvement" and reopen this issue

**Comment by leemuar** [comment]
@mlangsdorf mlangsdorf reopen please with "feature/suggestion" label

**Comment by leemuar** [comment]
What is the difference between
`data/json/npcs/refugee_center/surface_staff/NPC_old_guard_doctor.json`
and
`data/json/npcs/missiondef.json` ?

I've added mission's description to NPC_old_guard_doctor.json, and it worked for me.
But Im not sure where missiondef.json is used, should I make changes to it too?

**Comment by UmbralReaper** [comment]
```missiondef.json``` contains the generic version of the mission. If you want to alter all missions about analyzing zombie blood,  ```missiondef.json``` is the place to go. ```NPC_old_guard_doctor.json``` contains the old guard exclusive version of the mission.

**Comment by leemuar** [comment]
After getting more experienced in the game here are my thoughts on the issue:

1. Unexperienced players quickly forget what should be done. We should expand the mission description to include:
- how to get the blood from zombie
- mention centrifuge and a computer as a required hardware to look for
- mention data on a flashdrive as a quest result

2. Hospital is not the only place to analyze the blood. Unexperienced players do not know that. We should mention in the mission description:
- hospital is not the only place to go, it's just a convenient starting point, there are other places. If something happen to the centrifuge - look in other places
- what hardware to look for
- hint on what places to look for (labs, medical buildings, etc)

3. Mission pointer on world map is both helpful and misleading. It helps new players to find a starting POI, but if something happen to a centrifuge - players get confused: it points to a location you can not complete the quest in. Player have no idea what to do in that case.

I think the solution is to write a **good helpful mission description**. It should hint where too look for the required hardware and what to do with it

**Comment by leemuar** [comment]
Is there a way to highlight some words in mission description screen in the game? Like **making some words bold** or highlighting with colors?

**Comment by leemuar** [comment]
Answering to myself: yes, there is! using <color_X></color> tag we can highlight important words in quest description. This will help create some hint on important statements/words in the quest's description 

![image](https://user-images.githubusercontent.com/5869791/120938057-ae75d600-c719-11eb-9820-14342242fe1d.png)


> 
> 
> Is there a way to highlight some words in mission description screen in the game? Like **making some words bold** or highlighting with colors?
