### ISSUE TITLE
Unexpected msg "Your biology is not compatible with that healing item"

### ISSUE THREAD

**Issue by akirashirosawa** [CleverRaven/Cataclysm-DDA#41699]
# Describe the bug
When try to use any item (with 0 charges) in hands (using `Shift + A`), get the message: `"Your biology is not compatible with that healing item."`
# Steps To Reproduce
Using item in hands (`Shift + A`) with `0` charges.
# Expected behavior
Do not show msg `"Your biology is not compatible with that healing item."`
# Screenshots
<img width="354" alt="1" src="https://user-images.githubusercontent.com/38557723/86120777-98a96b00-badd-11ea-92f2-c13170dac393.png">
<img width="354" alt="1" src="https://user-images.githubusercontent.com/38557723/86120794-9e06b580-badd-11ea-987f-cee5f4d7551c.png">

# Versions and configuration
- OS: MacOs
    - OS Version: Name: Mac OS X; Version: 10.15.5; Build: 19F101; 
- Game Version: 0.E 8f973a75f624af86cc2ba742dc942fc42a6ef82c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations]
]

# Additional context
As I wrote in [ comment](https://github.com/CleverRaven/Cataclysm-DDA/pull/41651#discussion_r447611399) to PR #41651, I think, this is related with code:
```cpp
    if( !has_enough_charges( *used, true ) || ( used->is_medication() &&
            !can_use_heal_item( *used ) ) ) {
        add_msg_if_player( m_bad, _( "Your biology is not compatible with that healing item." ) );
```

**Comment by Fris0uman** [comment]
Right, I'll try to fix it later today. Thanks for the report
