### ISSUE TITLE
# Game crushed everytime I load my save.  The first time the game crashed when I began to eat royal jelly while listening to enemies.

### ISSUE THREAD

**Issue by 4uniquemind** [CleverRaven/Cataclysm-DDA#41696]
# The first time the game crashed when I began to eat royal jelly while listening to enemies.

# Eat royal jelly while listening to many Plastic Golems in wizard tower cause crush.

# Crush because segmentation issue

# No Screenshots

# Versions and configuration
Windows 10
 - Game Version: 0.E-3489-g6e97042
 - Graphics version: RetroDays+
 - Ingame language: [Russian]
 - Mods loaded: [DDA, Maglicysm, C.R.I.T, Mythical battle styles, Graphical map, Graphical map Maglicysm]

# Additional context in attachment
[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4851111/config.zip)

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4851118/save.zip)

**Comment by olanti-p** [comment]
It looks like `consume_location` of `consume_activity_actor` went bad between the start of the activity and an autosave. Or during an autosave?
Removing current activity (`ACT_CONSUME`) fixes the crash: [save-fixed.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4861061/Gulf.zip)

**Comment by 4uniquemind** [comment]
Thanks!
Perhaps the autosave began its work, but I did not see. 
By the way, at the very top of the tower, distillation apparatus also creates errors when playing for a new character.

**Comment by olanti-p** [comment]
As a note, looks like a case of #41352
