### ISSUE TITLE
Add longest_side to JSON data for GUN items

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#41691]
# Is your feature request related to a problem? Please describe.

Since the concept of "length" was added to the game, many of the guns are now displayed with hilariously short default lengths, such as the 17 cm M2HB Browning:

![image](https://user-images.githubusercontent.com/238395/86068743-65130600-ba35-11ea-8db1-872d965cd7ac.png)

or the Taurus Spectrum, which at less than 3 inches long is tiny even for a subcompact:

![image](https://user-images.githubusercontent.com/238395/86068955-d05cd800-ba35-11ea-8443-e69e02ea5876.png)

# Describe the solution you'd like

For all the GUN type items to have an explicit "longest_side" defined, instead of using the default length based on the cube root of volume.

Adding these will support the completion of #37374 - see that issue for a tutorial on determing gun dimensions.

# Describe alternatives you've considered

I could sit down and do all of these myself with a lot of Googling, but work like this is an easy entry point for new contributors, as well as an opportunity for non-programmers to get more involved.

# Additional context

Here is a spreadsheet that summarizes all the GUN items, with their "id", along with existing dimensions and description:

https://docs.google.com/spreadsheets/d/1khFX131u-_tLsrFTaZvN_XA34JRTWaX2bxb5DSD_4EU/edit?usp=sharing

As of this writing, about 250 of them do not have a longest_side.

If you have Python installed, you can use the `table.py` tool in the CDDA repository to generate your own copy of that CSV data, using this command:

```
tools/json_tools/table.py --type=TOOL --format=csv id weight volume longest_side description
```

See also similar PR #41621 for TOOL items

**Comment by feinorgh** [comment]
I'm working on compiling a comprehensive overview of all the weapons in the game, including some that should be but aren't currently, and some that are, but probably shouldn't be. Later on, maybe a more comprehensive review of the firearms in the game could be done.

This would include firearms that are unlikely to be in the US/New England in the first place (like fully automatic AK type rifles), but might have civilian available alternatives (semi-automatic, limited magazines), and firearms that are currently in use with US Armed Forces, government agencies, and police, updated with more current versions.

Also, the plethora of available firearms available for civilians could be updated to reflect more current models, with more variety. I don't know if this is desirable and/or feasibly within the resources available.

Either way, I'm compiling data, including images for use with the ImageJ method above (with any protruding magazines, scopes, etc) edited away, in a Google Sheet, including calculations for volume and longest_side in the spreadsheet itself. I have some preliminary python code that reads off the sheet and compares the in-game data with the sheet as well, but this is far from production read. My idea is to automate, or at least assist the process of auditing/editing the gun data in the game based off of the sheet.

This is currently (mid July 2020) in progress, but the Google Sheet is available here: https://docs.google.com/spreadsheets/d/10TeuTTjwusbWB9SaH-nq03bMWDyILylU9Btvtu3uTDM/edit?usp=sharing

If anyone would like to participate and discuss it, I'd be happy to invite you to comment and edit the data.

Drop me a line on Discord if you like, too.
