### ISSUE TITLE
Loaded M2010 ESR prevents modding of any weapons (including itself)

### ISSUE THREAD

**Issue by rtizzy** [CleverRaven/Cataclysm-DDA#41703]
# Describe the bug

Attempt to attach a shoulder strap to a M2010 ESR. 

It will not be shown as an option for attachment. 

# Steps To Reproduce

1. Get a M2010 ESR (For example by spawning as a Biosniper)
2. Spawn in a shoulder strap. 
3. `a`pply the shoulder strap
4. M2010 ESR is not provided as an option.

# Expected behavior

The M2010 ESR should be provided as an option and the strap should be attachable. 

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-3612-gccc0313 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context

Also see https://github.com/CleverRaven/Cataclysm-DDA/issues/41702

**Comment by rtizzy** [comment]
Alright, I think there is some weird behavior occurring here that might be related to the JSON for the m2010. The M2010 seems to have different options than almost every other gun. 

I loaded a Ar-15 to test and it does show things and provides the message "Must be unloaded before installing this mod" 

After further testing I discovered that having the M2010 ESR loaded AT ALL will cause NO OPTIONS to display (even other weapons that allow modding).

**Comment by olanti-p** [comment]
Looks like a duplicate of #41010.
Attaching shoulder strap to an unloaded M2010 ESR
![image](https://user-images.githubusercontent.com/60584843/87258694-36257700-c4ae-11ea-8ec5-6a13d20307f9.png)
Trying to attach to a loaded M2010 ESR
![image](https://user-images.githubusercontent.com/60584843/87258707-4fc6be80-c4ae-11ea-9a7e-0efe2aa008ec.png)
Same thing, but with #42074
![image](https://user-images.githubusercontent.com/60584843/87258831-48ec7b80-c4af-11ea-9c1a-1dceb0127c53.png)


>even other weapons that allow modding

Didn't encounter that. If multiple weapons cannot be modded - yeah, they all don't show up in some cases, but the moddable ones were always there.
