### ISSUE TITLE
small plastic bottle with none

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#41725]
# Describe the bug

I was walking around a new world when i found a `small plastic bottle with none` in a house.

# Steps To Reproduce
dunno

# Expected behavior

small plastic bottle? small plastic bottle with proper stuff?

After saving and reloading it's now a `small plastic bottle with 2 items` (two `none`'s?).

# Screenshots

# Versions and configuration
- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.E-3643-ga1e694840a-dirty [64-bit]
- Graphics Version: Curses
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

# Additional context
[2020.06.30-41724.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4857928/2020.06.30-41724.zip)

**Comment by anothersimulacrum** [comment]
This was supposed to be fixed in #41608, but you appear to be using a version after it.
