### ISSUE TITLE
Increase the weight the Firefighter Belt can store to 12lbs

### ISSUE THREAD

**Issue by SgtCookie** [CleverRaven/Cataclysm-DDA#41738]
# Is your feature request related to a problem? Please describe.
The Halligan Bar, a common firefighter piece of loot, cannot be stored in the firefighter belt due to the belt having insufficent weight capacity. 

# Describe the solution you'd like
Increase the weight capacity of the firefighter belt to 12lbs, the current weight of the halligan bar.

# Describe alternatives you've considered
Lighten the weight of the halligan bar down to 8,80 lbs, but this would affect the move cost to use the halligan bar changing its strength as a weapon.

**Comment by MatiasFito** [comment]
The alternative you suggested got me curious and browsing a bit i've found that around 8 lbs is a much more realistic for a 60cm halligar bar. There are bigger bars but the one in the game has it's **longest_side: 60cm** so i based of that, here is a picture i think summarizes what i've found spread accross a few firefighter and hardware supplier sites:
![Screenshot from 2020-07-01 20-32-22](https://user-images.githubusercontent.com/7430004/86301131-69792380-bbdb-11ea-85c0-dd89bc2e27c6.png)
The 61cm weights around 4 if we round up, and 4kg is around 8.8lbs so it would make sense. Also right now the weight is 5.4kg for 60cm looks like a lot, so maybe a rework of the halligan is not inacurate, it's not a heavy tool but it can apply a lot of force that could be considered when tweaking damage, maybe it should not be reduced drastically even if adapted.

**Comment by GroeneAppel** [comment]
Looking at the provided images, i'd like to mention that the Halligan bar appears to pack a mean spike too. 
Not just that, the tool is mentioned of being designed to be able to puncture. Perhaps if the weapon is reworked, the ability to deal piercing damage should be considered. It appears that the halligan bar is essentially a battle pickaxe, with a crowbar and even a cutting function on it.

**Comment by MatiasFito** [comment]
Yeah i was very surprised, [this site](https://ironsandladders.com/2015/04/23/halligan-by-the-numbers/) even has a thorough explanation on how to use it properly to apply the most force with the least effort and it show how it can easely puncture wood like it's noting.
