### ISSUE TITLE
Game fails to load the island escape challenge

### ISSUE THREAD

**Issue by elsxf** [CleverRaven/Cataclysm-DDA#41735]
# Bug description

The game fails to load the island escape challenge, get bad stack alloc crash

# Steps to reproduce

make a character with the island escape challenge scenario

# Expected behavior

worldgen should occur and the game should start

# Versions and configuration
 - OS: Windows 10
 - Game Version: 0.E-2
 - Graphics version: tiles
 - Ingame language: english
 - Mods loaded: disable npc needs, aftershock, C.R.I.T expansion mod, Magiclysm, Generic guns, Mythic martial arts, no fungal monsters, bionic slots, statsthroughskills

# Additional context

no save file available, as the game crashes while trying to create a new save
[New folder.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4860272/New.folder.zip)

**Comment by Silook** [comment]
did you have always enable starting npc?

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.E-10390.
