### ISSUE TITLE
Battery System CBM does not allow consumption of batteries in inventory

### ISSUE THREAD

**Issue by Silook** [CleverRaven/Cataclysm-DDA#41744]
# Describe the bug

The Battery System CBM does not allow consumption of batteries in the inventory.

# Steps To Reproduce

1. Spawn 2 disposable light batteries
2. Pick up one, leave the other one on the ground beside you
3. [E]at
4. Only the battery not in your inventory will show up

# Expected behavior

Player should be able to consume batteries whether they're in the inventory or not

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.E-3547-g7d8b016 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: 
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Stats Through Kills [stats_through_kills],
    No Rail Stations [No_Rail_Stations],
    Mythical Martial Arts [MMA]

**Comment by chphilli** [comment]
I noticed this behavior also last week and then today I'm unable to consume batteries no matter where they are. Is this just me or did something change for the worse?

**Comment by anothersimulacrum** [comment]
Likely a result of #42095

**Comment by UrbanCMC** [comment]
Can confirm that reverting #42095 restores the previous behavior.

I think it would be a better solution to instead show the actual battery "magazine" instead of its ammo, though.
That would make it possible to distinguish battery types, which I think is desirable.
