### ISSUE TITLE
Should balance the trap since now it's too OP

### ISSUE THREAD

**Issue by MikuMiddo** [CleverRaven/Cataclysm-DDA#41757]
# Is your feature request related to a problem? Please describe.
The trap seems too powerful when it gets enought amount around you.  you can easily kill dozens of zombies with 16 spike traps that set at the four main directions.Also it's cheap enought to get in earily game.
After this fright,you can take them back brand-new due to the traps set on ground will not get damage even a zombie bear stand on 
them.
# Describe the solution you'd like
The trap set at ground should get damage base on the volume of the monster.The trap such as the bear trap should have a chance to stuck on the monster's body，you should kill it to take your trap back.
Also the trap should have malfunction，such as the springs loose,the nail bent. A trap shouldn't kill hundreds of zombies but still works as new.

# Describe alternatives you've considered
Add the chance that damage will be add to the trap when monster step on them due to the volume of monster.
Add the malfunction to trap after too many times uses.
Decrease the damage of traps when its durability reduced.

# Additional context
![timg](https://user-images.githubusercontent.com/53809752/86354717-1dda7e80-bc9c-11ea-8718-93083db4ef8c.jpg)
This thing should easily get damage after dozens of steps and should do less and less damage when it becomes breaking.

**Comment by anothersimulacrum** [comment]
The mechanism for a nailboard trap killing zombies is a little suspect - it should stick in their feet, impair their movement, but it can't do much more than hurt the feet and make it harder for them to move.
