### ISSUE TITLE
10x+ slowdown due to process_fields (85%) and spread_gas (45%)

### ISSUE THREAD

**Issue by FunnyMan3595** [CleverRaven/Cataclysm-DDA#41750]
# Describe the bug

My savegame has become exceedingly slow recently, with a 5-minute reading step taking about 3 real seconds.  This is a 10x+ slowdown, as a fresh save with the same options and character template-copied over will get over an hour of reading progress in the same real time.

# Steps To Reproduce

1. Load attached save.
2. Begin reading.
3. Observe lag.

# Expected behavior

The game may slow down as the save gets more complex, but hopefully not *this* far without exceptional circumstances.

# Screenshots

There's very little nearby, just my car (with a bunch of loot) and the entrance to a cold lab (which is partially raided, but fairly unexceptional):
[image](https://user-images.githubusercontent.com/98381/86317557-88c87e80-bbe4-11ea-8b14-b1680e113335.png)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 8.1
- Game Version: 0.E-2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    No Monsters [Only_Wildlife],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

Save: [Laggy_East_Walthill.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4862025/Laggy_East_Walthill.zip)

**Comment by FunnyMan3595** [comment]
After further experimentation, heading ~15 map tiles south down the road does restore my reading speed to approximately normal, which strongly suggests that it's the cold lab to blame for the lag.

**Comment by kevingranade** [comment]
Need to retest this one, I made some pretty aggressive adjustments to field processing performance.

**Comment by Aivean** [comment]
I profiled the attached savefile, the issue appears to be resolved. On my fairly old machine the simulation speed is ok:
![image](https://user-images.githubusercontent.com/2865203/102805657-6718aa80-4370-11eb-993f-1493146a3e13.png)

Field processing takes a significant amount of time percent-wise, but that is expected:
![image](https://user-images.githubusercontent.com/2865203/102805764-90d1d180-4370-11eb-838d-2bef7a00fecf.png)

**Comment by Night-Pryanik** [comment]
Closing as resolved.
