### ISSUE TITLE
Sealed glass jars not functioning appropriately

### ISSUE THREAD

**Issue by Ktmi** [CleverRaven/Cataclysm-DDA#41768]
# Describe the bug

Sealed glass jars and sealed 3L glass jars can have their contents consumed/unloaded, without unsealing the jar.
Additionally items can be inserted into sealed jars without unsealing it.

# Steps To Reproduce

1. Get a sealed glass jar of jam or some other contents.
2. Consume or unload the contents
3. Insert other item or fluid into jar.
4. See that the jar still is labeled as sealed.

# Expected behavior

Consuming, unloading, or inserting all require opening the jar.
Doing so *should* result in the jar being unsealed.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-3656-gabf16ce [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by RoyBerube** [comment]
42442 has addressed sealed containers, and so it seems this issue is fixed.

**Comment by anothersimulacrum** [comment]
Should be fixed in #42442
