### ISSUE TITLE
Game regularly crashes

### ISSUE THREAD

**Issue by souricelle** [CleverRaven/Cataclysm-DDA#41775]
# Describe the bug

Often, usually while I'm traveling in unfamiliar areas (but sometimes just whenever) the game crashes and gives this error message.

The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 0.E-2
TYPE: St9bad_alloc
MESSAGE: std::bad_alloc

This has happened in the subway tunnels (where I was on foot) and aboveground (where I was on a motorcycle) and also while I was sitting at home reading.

If I check the task manager while any of my saves are loaded, I will see that Cataclysm is hogging over 1gb of memory. I have a brand new gaming PC so it's not a problem for my system but that seems odd.

# Steps To Reproduce

1. Try playing my attached save and see if it crashes. The best way is probably to hop in a car and head down the road in an unexplored direction.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-2 [32-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills]
]
# Additional context

I have gone through the .json files and removed group_bash from the zombies.

Save:
[Philbrook.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4866389/Philbrook.zip)

Crash and debug logs:
[souricellecrashlog.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4866386/souricellecrashlog.zip)

**Comment by souricelle** [comment]
This is possibly a memory issue and is now happening during normal play, not just when I'm traveling.

**Comment by olanti-p** [comment]
Have you tried x64 version of the game? You can grab it from the official website
https://cataclysmdda.org/releases/

**Comment by souricelle** [comment]
Wow I feel dumb. This works, closing the issue!
