### ISSUE TITLE
Resources used for washing filthy containers differ depending on the contents' volume

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#41772]
# Describe the bug

If you unload your filthy backpack, it will take much less soap to wash.

# Steps To Reproduce
Get a filthy military rucksack from a zombie, wear it, get a lot of loot, try to wash it with and without the loot.

# Expected behavior

# Screenshots

# Versions and configuration

# Additional context

**Comment by anothersimulacrum** [comment]
Fix is similar to #41612, probably.
