### ISSUE TITLE
"fire_station_1" (All rotations) not available location for faction camp creation

### ISSUE THREAD

**Issue by Termineitor244** [CleverRaven/Cataclysm-DDA#41788]
If you try to create a faction camp in a fire station, one of two things can happen:
1._ You found a "fire_station", and you can create your faction camp
2._ You found a "fire_station_1" (No idea what is the difference) and you **can not** create a faction camp

# Steps To Reproduce

1. Edit the map, place a "fire_station" and a "fire_station_1" (North, east, etc. doesn't matter).
2. Teleport to the "fire_station", create a NPC, seduce that NPC so that it starts to follow you, attempt to create a faction camp.
3. You are able to create a faction camp (You are presented with the option).
4. Teleport to the "fire_station_1".
5. Repeat step 2.
6. You are not presented with the option to create a faction camp in that place.

# Expected behavior

To be able to create a faction camp in a normal fire station.

# Screenshots

![imagen](https://user-images.githubusercontent.com/53200489/86426505-7d8d5580-bcad-11ea-8958-723740147da0.png)
That is what happens if you try to create a faction camp in the "fire_station_1"

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-1448-gdd87a23 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

# Additional context

I tested this in an old version of mine (A version from before nested containers), so this could have been fixed... I will test it in a recent copy of the game and confirm later.

Edit: Confirmed in a recent version of the game (0.E-3669-g1c69950), this is a version from today in the morning.

**Comment by curstwist** [comment]
It isn't available because it doesn't exist.  Only 1 fire station is faction camp capable right now (the older one without windows along the back wall).  Also, one shelter (of 3) isn't faction-able.  

These are high on my priority list to add once `autocalc` can be re-enabled for faction camp recipes (was disabled due to performance issues).

**Comment by Night-Pryanik** [comment]
Not a bug, just isn't implemented yet.

**Comment by Termineitor244** [comment]
Oh, ok, thanks for the explanation then!
