### ISSUE TITLE
Using Vehicle welder to repair items causes Seg Fault

### ISSUE THREAD

**Issue by Kurrisum** [CleverRaven/Cataclysm-DDA#41784]
# Describe the bug
A Seg fault occurs when using the "use the welding rig" from a Vehicle welding rig command to repair items

# Steps To Reproduce
1."e"axmine vehicle rig welder
2. Select "use the welding rig"
3. Have correct repair materials near by
4. Select item to repair
5. Seg Fault

# Expected behavior
Be able to repair with the Vehicle welding rig without a crash

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-3669-g1c69950 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    Mining Mod [Mining_Mod],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]

# Additional context
[Crash-Debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4867132/Crash-Debug.zip)

[Seg Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4867134/Seg.Save.zip)
(Welding rig adjacent with a damaged crow bar in inventory with scrap nearby to do the steps)

**Comment by Menschheit** [comment]
It is again the activity assignment thing. I can fix the crash but it won't use any charges during long term activity.
