### ISSUE TITLE
Game crash, segmentation fault

### ISSUE THREAD

**Issue by Kelenius** [CleverRaven/Cataclysm-DDA#41799]
# Describe the bug

Game crashes.

# Steps To Reproduce

1. Load the attached save.
2. Move south-east towards the road (just hold 3 on numpad).
3. Crash.

# Expected behavior

No crash.

# Versions and configuration

10804

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-3681-g7194cdc [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Generic Guns [generic_guns],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills],
    Disable NPC Needs [no_npc_food]
]

# Additional context

[Lares.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4868780/Lares.zip)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4868775/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4868776/debug.log)

**Comment by Kelenius** [comment]
Seems to work in 10805, however. Was anything related merged?

**Comment by olanti-p** [comment]
Yeah, 4db33b10f9951a0b7bb5386adbc9e0d4bd009fbb fixes it.

Relevant frames:
```
  #7
    (dbghelp: KiUserExceptionDispatcher+0x2e@0x7ffb2479fe3e[ntdll.dll+0x9fe3e]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #8
    (dbghelp: @0xbacc68[cataclysm-tiles.exe+0x7acc68]), 
    (libbacktrace: ZNK7monster8attitudeEPK9Character+0x298@0xbacc68),
    (libbacktrace: 0xbacc68    [unknown src]:0    [unknown func]),
  #9
    (dbghelp: @0xb9d1eb[cataclysm-tiles.exe+0x79d1eb]), 
    (libbacktrace: ZN7monster4planEv+0x16b@0xb9d1eb),
    (libbacktrace: 0xb9d1eb    [unknown src]:0    [unknown func]),
```

**Comment by ZhilkinSerg** [comment]
Resolved.
