### ISSUE TITLE
Blood draw kit can't gather blood

### ISSUE THREAD

**Issue by eilaattwood** [CleverRaven/Cataclysm-DDA#41794]
# Describe the bug
Blood draw kit can't gather blood from zombies

# Steps To Reproduce

1. Obtain blood draw kit and zombie of acid zombie corpse
2. Stand on the corpse and activate blood drawn kit
3. Check the report in the log that sample was gathered
4. Blood draw kit is still empty

# Expected behavior

Blood draw kit should be filled with zombie blood(for regular zombie) or acid (for acidic zombie)

# Screenshots

None

# Versions and configuration

 - OS: Windows 7
 - Game Version: 0.E-3681-g7194cdc
 - Graphics version: Tiles
 - Ingame language: Russian
 - Mods loaded: [
  "dda",
  "no_npc_food",
  "blazeindustries",
  "EngineeringEssentials",
  "aftershock",
  "crt_expansion",
  "Mining_Mod",
  "speedydex",
  "StatsThroughSkills",
  "stats_through_kills"
]

# Additional context
Gathering blood from self is not working either.

**Comment by LucasHoage** [comment]
This is an issue with the maximum contained weight a blood draw kit can hold. It can hold the volume correctly though. I will make a fix in a little bit.
