### ISSUE TITLE
on ios use ish app to run it

### ISSUE THREAD

**Issue by ccvvv** [CleverRaven/Cataclysm-DDA#41803]
ish app is alpine system.i compile game。make is no error.
but when i run game 

ERROR: Couldn't find cataclysm game binary in '/root/Cataclysm-DDA'

**Comment by ZhilkinSerg** [comment]
Can you elaborate more please?

While we want to add IOS to list of supported systems (see #28404 and https://github.com/ralreegorganon/Cataclysm-DDA/tree/ios-days-ahead), we do not currently support it.

**Comment by ZhilkinSerg** [comment]
Is that it what you are using - https://github.com/ish-app?

Maybe you need to move some files after you've built CDDA?

It would probably help if you will provide more details on how you built CDDA - command line used and such.

**Comment by ccvvv** [comment]
> Is that it what you are using - https://github.com/ish-app?
> 
> 
> 
> Maybe you need to move some files after you've built CDDA?
> 
> 
> 
> It would probably help if you will provide more details on how you built CDDA - command line used and such.


on ish.
i download the git.and use git download the cdda game.
i read that help .download the gcc . make. g++. astyle.  ncurese. 
then i built the game . but error  libintl.h no found.
so .i download  the  gettext-dev.
then i built the game succesc .
but no  binary file. i just can found cataclysm-launcher.

**Comment by ccvvv** [comment]
LLVM ERROR: out of memory
Stack dump:
0.      Program arguments: /usr/bin/clang-9 -cc1 -triple i586-alpine-linux-musl -emit-obj -disable-free -disable-llvm-verifier -discard-value-names -main-file-name activity_actor.cpp -mrelocation-model pic -pic-level 2 -pic-is-pie -mthread-model posix -menable-no-infs -menable-no-nans -menable-unsafe-fp-math -fno-signed-zeros -mreassociate -freciprocal-math -fno-trapping-math -ffp-contract=fast -ffast-math -ffinite-math-only -masm-verbose -mconstructor-aliases -fuse-init-array -target-cpu pentium4 -dwarf-column-info -debugger-tuning=gdb -momit-leaf-frame-pointer -coverage-notes-file /root/Cataclysm-DDA/obj/activity_actor.gcno -resource-dir /usr/lib/clang/9.0.0 -D RELEASE -D GIT_VERSION -D BACKTRACE -D LOCALIZE -internal-isystem /usr/bin/../lib/gcc/i586-alpine-linux-musl/9.2.0/../../../../include/c++/9.2.0 -internal-isystem /usr/bin/../lib/gcc/i586-alpine-linux-musl/9.2.0/../../../../include/c++/9.2.0/i586-alpine-linux-musl -internal-isystem /usr/bin/../lib/gcc/i586-alpine-linux-musl/9.2.0/../../../../include/c++/9.2.0/backward -internal-isystem /usr/local/include -internal-isystem /usr/lib/clang/9.0.0/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -Os -Wall -Wextra -Wformat-signedness -Wlogical-op -Wmissing-declarations -Wmissing-noreturn -Wnon-virtual-dtor -Wold-style-cast -Woverloaded-virtual -Wpedantic -Wsuggest-override -Wunused-macros -Wzero-as-null-pointer-constant -Wno-unknown-warning-option -Wredundant-decls -Werror -std=c++14 -fdeprecated-macro -fdebug-compilation-dir /root/Cataclysm-DDA -ferror-limit 19 -fmessage-length 0 -stack-protector 2 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -faddrsig -o obj/activity_actor.o -x c++ src/activity_actor.cpp 

1.      <eof> parser at end of file
2.      src/debug.h:76:13: instantiating function definition 'realDebugmsg<const std::__cxx11::basic_string<char> &, std::__cxx11::basic_string<char> >'
3.      src/string_formatter.h:416:20: instantiating function definition 'string_format<const std::__cxx11::basic_string<char> &, std::__cxx11::basic_string<char> >'
4.      src/string_formatter.h:405:20: instantiating function definition 'string_format<const std::__cxx11::basic_string<char> &, std::__cxx11::basic_string<char> >'
5.      src/string_formatter.h:329:14: instantiating function definition 'cata::string_formatter::parse<const std::__cxx11::basic_string<char> &, std::__cxx11::basic_string<char> >'
6.      src/string_formatter.h:261:14: instantiating function definition 'cata::string_formatter::read_conversion<const std::__cxx11::basic_string<char> &, std::__cxx11::basic_string<char> >'
7.      src/string_formatter.h:249:12: instantiating function definition 'cata::string_formatter::get_nth_arg_as<const char *, 0, const std::__cxx11::basic_string<char> &, std::__cxx11::basic_string<char> >'
8.      src/string_formatter.h:249:12: instantiating function definition 'cata::string_formatter::get_nth_arg_as<const char *, 1, std::__cxx11::basic_string<char>>'
clang-9: error: unable to execute command: Aborted
clang-9: error: clang frontend command failed due to signal (use -v to see invocation)
Alpine clang version 9.0.0 (https://git.alpinelinux.org/aports 90a9ec8f51c05b381653e49d63616ac0e29193b6) (based on LLVM 9.0.0)
Target: i586-alpine-linux-musl
Thread model: posix
InstalledDir: /usr/bin

InstalledDir: /usr/bin
clang-9: note: diagnostic msg: PLEASE submit a bug report to  and include the crash backtrace, preprocessed source, and associated run script.
clang-9: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-9: note: diagnostic msg: /tmp/activity_actor-bfc521.cpp
clang-9: note: diagnostic msg: /tmp/activity_actor-bfc521.sh
clang-9: note: diagnostic msg: 

********************
make: *** [Makefile:870: obj/activity_actor.o] Error 254
make: *** Waiting for unfinished jobs....

**Comment by ccvvv** [comment]
> Is that it what you are using - https://github.com/ish-app?
> 
> 
> 
> Maybe you need to move some files after you've built CDDA?
> 
> 
> 
> It would probably help if you will provide more details on how you built CDDA - command line used and such.

问题解决了。原来原因是make j4...，这个命令的数字太大，苹果手机运行吃力。刚刚用的make j1，手机编译了一晚上。但是可以成功编译。
而且发现后续需要安装grep和xargs的依赖。
