### ISSUE TITLE
Load Vehicle command

### ISSUE THREAD

**Issue by MarceloLaser** [CleverRaven/Cataclysm-DDA#41817]
I'd like to have a special type of zone in the zone manager system that is just like a "Loading Bay" or "Vehicle Cargo" zone. This zone would work by taking all items from "Unsorted" that do not have a defined zone for them. It would allow a player to set an "Unsorted" zone with a large amount of loot, say, when looting a Lumber Mill for example, and just load everything onto their truck, regardless of item category. It'd also allow one to order their NPC followers to load up a vehicle in a similar way.

**Comment by hexagonrecursion** [comment]
It is already possible to achieve a similar effect:
- It is possible to designate a zone inside a vehicle cargo space by placing a one-tile zone over it. Note: this only works when creating a new zone, you can not move an existing zone into a cargo space.
- If you create a "Loot: Custom" zone with an empty filter, it will accept everything

The only limitation is that if you have 50 cargo spaces, you have to create 50 separate one-tile zones
