### ISSUE TITLE
spear strap cloned my weapon

### ISSUE THREAD

**Issue by bloodraven983** [CleverRaven/Cataclysm-DDA#41810]
# Describe the bug

SO I don't really know what happened and how and when but i created a spear strap to store my glaive and somehow... the spear strap cloned the glaive, so now I have two of them

# Expected behavior

Containers like holsters shouldn't clone objects

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-3697-g9582e33 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi]
]

**Comment by Duck13Tales** [comment]
It seems to be the same as in #41776. There is already a PR to fix it.
