### ISSUE TITLE
Pocket priorisation/whitelist doesn't seem to be working at all

### ISSUE THREAD

**Issue by molkemon** [CleverRaven/Cataclysm-DDA#41816]
# Describe the bug

Despite setting a pocket (or several pockets) whitelisted for something and increasing the pocket priority, picking up an item of that category puts it into an entirely different container

# Steps To Reproduce

1. Spawn a hiking backpack, army pants a butcher knife and some grenades and a joint
2. Wear the hiking backpack and the army pants
3. Set pocket 4 of the hiking backpack to whitelist drugs and increase it's priority
4. Set pockets 5 and 6 of the hiking backpack to whitelist weapons and increase their priorities
5. pickup the joint, the butcher knife and the grenades
6. all items will be put into army pants pockets

# Expected behavior

The items should be added to their increased priority whitelisted pockets

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-3706-g16fb746 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

Whitelisting specific items, ie the joint doesn't work either
Maybe I just don't understand how the system works correctly, or maybe all the tested bags are somehow restricted, but at least from the hiking backpack description, I can't see any restrictions to the pockets. Also I'm pretty sure pocket 1 of the backpack should take everything, but it doesn't work with that pocket either.
If there are any restrictions they should be clearly shown, and ideally the pocket interface shouldn't allow to set whitelists for categories/items that cannot go into that pocket

**Comment by molkemon** [comment]
Update: Ok after several reloads, it seems to be sorta, a bit working now? The joint does get put into the correct pocket now. However, if i set hiking backpack pocket 5 to whitelist weapons prio 20, and pocket 6 with nothing, the butcher knife is still put into pocket 6. Only if I additionally blacklist weapons for pocket 6 will the knife be put into pocket 5.... something is certainly still amiss...

**Comment by GGgatherer** [comment]
Yeah it works but just like you described, kinda sorta. Some items go in preferred pocket - seems to work better with small items like bandages and so. But even at magazines, the troubles already start.
2 pockets with different everything, whitelist specifically says magazines should go in 2nd (and even with higher priority), pick up 3 mags, 2 of those go where they should be, 1 ends up in 1st pocket... while there's enough place for 4 more in the 2nd.
