### ISSUE TITLE
Graphic options not changing 

### ISSUE THREAD

**Issue by Sevaaas1** [CleverRaven/Cataclysm-DDA#41826]
Graphics option in the Settings menu is bugged and reverts to default

# Steps To Reproduce

1. Start CDDA
2. Go to Settings->Options->Graphics
3. Modify line 9 and 10
4. Restart CDDA

Now the settings are default and never applied

I expect for the resolution of the game to be changed

# Versions and configuration
Version: 0.E-3706-g16fb746 (tiles)
Build: 10806 

Windows 10 Home Version 1909 Build 18363.900

Fixed, wasnt a bug, game was set to windowed borderless

**Comment by anothersimulacrum** [comment]
> Fixed, wasnt a bug, game was set to windowed borderless

Closing this then.
