### ISSUE TITLE
 Segmentation fault while sleeping

### ISSUE THREAD

**Issue by cinead** [CleverRaven/Cataclysm-DDA#41828]
# Describe the bug
Went to sleep in-game, slept for much of the night, then encountered a segmentation fault that generated a crash.log.

# Steps To Reproduce

Unable to repro.
After the segfault, I zipped the save file that was taken just prior to sleeping (see context).
However, after loading that save file and sleeping again, the seg fault did not occur. 

# Expected behavior

I just wanna wake up.

# Screenshots

# Versions and configuration

# Additional context

Linux64 Mint 19 Tara
Terminal graphics in Gnome Terminal

Active World Mods

    Dark Days Ahead
    Alternative Map Key
    No Rail Stations
    Graphical Overmap
    sees-player-icon, HitButton_iso
    sees-player icon, retrodays
    Magiclysm
    Graphical Overmap Magiclysm

CRASH.LOG

The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 15a37481
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

    ./cataclysm(_Z21debug_write_backtraceRSo+0x37) [0x55d4b57d3a3e]
    ./cataclysm(+0x80ff44) [0x55d4b57aaf44]
    ./cataclysm(+0x810ad9) [0x55d4b57abad9]
    /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7fec46f45f20]
    ./cataclysm(_ZNK17active_item_cache5emptyEv+0x2b) [0x55d4b5430a71]
    ./cataclysm(_ZN3map13process_itemsEv+0x1ee) [0x55d4b5da359c]
    ./cataclysm(_ZN4game7do_turnEv+0xf14) [0x55d4b599fd8a]
    ./cataclysm(main+0x1968) [0x55d4b5d65c27]
    /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7fec46f28b97]
    ./cataclysm(_start+0x2a) [0x55d4b53f9e9a]

    Attempting to repeat stack trace using debug symbols…
    debug_write_backtrace(std::ostream&)
    …/src/debug.cpp:777
    log_crash
    /usr/include/c++/7/bits/basic_string.h:149
    ??
    /usr/include/c++/7/bits/basic_string.h:422
    ??
    /usr/include/c++/7/sstream:168
    ??
    /usr/include/c++/7/sstream:638
    log_crash
    …/src/crash.cpp:79
    signal_handler
    …/src/crash.cpp:117
    ??
    ??:0
    active_item_cache::empty() const
    …/src/active_item_cache.h:16
    ??
    /usr/include/c++/7/ext/new_allocator.h:136
    ??
    /usr/include/c++/7/bits/alloc_traits.h:475
    ??
    /usr/include/c++/7/bits/stl_list.h:575
    ??
    /usr/include/c++/7/bits/stl_list.h:1801
    ??
    /usr/include/c++/7/bits/stl_list.h:1133
    ??
    /usr/include/c++/7/bits/stl_list.h:1730
    ??
    /usr/include/c++/7/bits/stl_list.h:655
    ??
    /usr/include/c++/7/bits/stl_pair.h:292
    active_item_cache::empty() const
    …/src/active_item_cache.cpp:51
    map::process_items()
    …/src/map.cpp:4536 (discriminator 1)
    game::do_turn()
    …/src/game.cpp:1548
    main
    …/src/main.cpp:697
    __libc_start_main
    /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:344
    _start
    ??:?

DEBUG.LOG afterwards
21:17:37.219 : Starting log.
21:17:37.220 INFO : Cataclysm DDA version 15a37481
21:17:37.220 INFO : [main] C locale set to en_US.UTF-8
21:17:37.220 INFO : [main] C++ locale set to en_US.UTF-8
21:17:37.222 INFO : [options] C locale set to en_US.UTF-8
21:17:37.222 INFO : [options] C++ locale set to en_US.UTF-8
21:17:37.411 WARNING : opendir [./mods/] failed with "No such file or directory".
21:17:44.320 WARNING : opendir [./save/Harmony/mods] failed with "No such file or directory".

![Segfault_gnome_terminal](https://user-images.githubusercontent.com/16060264/86504970-15ee0d80-bd74-11ea-93c8-2bafb0a58d0e.png)

[Harmony_savefile_segfault_on_sleep.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4872118/Harmony_savefile_segfault_on_sleep.zip)

**Comment by Fris0uman** [comment]
Load save > sleep > nothing happens > wait 18h more > nothing happens
Repeat two first steps 4 times > nothing happens
