### ISSUE TITLE
Milkshake problems: Tried to add a duplicate entry while Shift-E a melted milkshake

### ISSUE THREAD

**Issue by cinead** [CleverRaven/Cataclysm-DDA#41829]
# Describe the bug

Viewed a melted milkshake on the ground and decided to try and eat it by pressing Shift-E. The game didn't respond, so pressed Shift-E again. Received an error:

DEBUG Tried to add a duplicate entry.
FUNCTION void inventory_column::add_entry(const inventory_entry&)
FILE src\inventory_ui.cpp
LINE 760
```

void inventory_column::add_entry( const inventory_entry &entry )
{
    if( std::find( entries.begin(), entries.end(), entry ) != entries.end() ) {
        debugmsg( "Tried to add a duplicate entry." );
        return;
    }
    const auto iter = std::find_if( entries.rbegin(), entries.rend(),
    [ &entry ]( const inventory_entry & cur ) {
        const item_category *cur_cat = cur.get_category_ptr();
        const item_category *new_cat = entry.get_category_ptr();

        return cur_cat == new_cat || ( cur_cat != nullptr && new_cat != nullptr
                                       && ( *cur_cat == *new_cat || *cur_cat < *new_cat ) );
    } );
```

# Steps To Reproduce

Was able to repro by pressing space to clear the error, and then pressing Shift-E again.
At this point, I saved the game (save file attached, which represents save just before screenshot).
Reloaded the game, picked up the melted milkshake and then shift-E. Received the same error. 

Try it! This savefile reproduces the error: get the milkshake. Press Shift-E. Suffer the consequences of an evil god: no you will not eat this milkshake.

# Expected behavior

I think I should be able to eat a melted milkshake, if I really feel like it. I even have a spoon nearby.
I tried removing my foodperson mask (*shudder*) but I still receive the error when I try to Shift-E(at). 

#Screenshots

![GotMeAMeltedMilkshake](https://user-images.githubusercontent.com/16060264/86505688-d8da4900-bd7c-11ea-8c27-59a856f7d65a.png)

# Versions and configuration

Linux64 Mint 19 Tara
Terminal graphics in Gnome Terminal

# Additional context

DEBUG:
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4872162/debug.log)

SAVEFILE that repros:
[Harmony_savefile_tried_duplicate_error.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4872159/Harmony_savefile_tried_duplicate_error.zip)

**Comment by cinead** [comment]
I got the the same error again after successfully eating the melted milkshake. 

There are no milkshakes in heaven.

**Comment by Ramza13** [comment]
Can't reproduce this on latest version.  Pick up the milkshake and press shift-E with no issue.  Consume milkshake and no errors.

**Comment by hexagonrecursion** [comment]
It looks like the bug was fixed

# Old version
I can confirm that the bug **was reproducible** in 16fb746 using the [attached save](https://github.com/CleverRaven/Cataclysm-DDA/files/4872159/Harmony_savefile_tried_duplicate_error.zip).

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 32 (Thirty Two); Release: 32; Codename: ThirtyTwo; 
- Game Version: 0.E-3706-g16fb746 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations],
    Graphical Overmap [Graphical_Overmap],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player icon, retrodays [sees_player_retro],
    Magiclysm [magiclysm],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm]
]

# New version
I was **unable to reproduce** the bug in ad3141d using the attached save file

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 32 (Thirty Two); Release: 32; Codename: ThirtyTwo; 
- Game Version: 0.E-8968-gad3141d-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations],
    Graphical Overmap [Graphical_Overmap],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player icon, retrodays [sees_player_retro],
    Magiclysm [magiclysm],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm]
]

**Comment by hexagonrecursion** [comment]
For the record: the milkshake was innocent. :) I managed to reduce the testcase to:
1. Wear a hoodie
2. Put a glass jar in the hoodie
2. Put 2 units of clean water in the jar
3. Drop the hoodie on the ground
4. [E]at

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 32 (Thirty Two); Release: 32; Codename: ThirtyTwo; 
- Game Version: 0.E-3706-g16fb746 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

Can not reproduce this variant in the most recent version either

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 32 (Thirty Two); Release: 32; Codename: ThirtyTwo; 
- Game Version: 0.E-8968-gad3141d-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]
