### ISSUE TITLE
Replace the inventory UI

### ISSUE THREAD

**Issue by Sevaaas1** [CleverRaven/Cataclysm-DDA#41827]
# Is your feature request related to a problem? Please describe.
I have been trying to play the experimental version of the game to play with the nested containers, however i have found it irritating that to see how much space each piece of clothing has available i have to open that clothing, or do the same to see what items is inside that clothing

# Describe the solution you'd like
Modify the current inventory UI so that it only lists pieces of clothing and available capacity in a drop down type of list, one would be able to press a button to Expand or Collapse the option to see what is inside

# Describe alternatives you've considered
List only pieces of clothing and available capacity, press enter to open another menu that has all the items contained inside 
# Additional context
Rough mock-up of my idea: https://imgur.com/JmiFZj2

This could be modified to be used for pickup, and drop menu, listing the loss of storage capacity, or the gain capacity respectively

With a system like this, the hassle of knowing where every single item is stored would be solved, sadly, as im not a programmer yet, i can't assist with making this a reality

**Comment by placeybordeaux** [comment]
The loss of the amount of storage added by wearing something in the wear item inventory use screen is pretty painful IMO. I'd love to see anything that restores that.
