### ISSUE TITLE
Object was loaded with charges, but can not have any!

### ISSUE THREAD

**Issue by cinead** [CleverRaven/Cataclysm-DDA#41821]
# Describe the bug

While playing the game (version 15a37481, built on Linux64 Mint 19), I received the error:
DEBUG: Item acoustic_guitar was loaded with charges, but can not have any!
FUNCTION: void item::io(Archives&) [with Archive = io::JsonObjectInputArchive]
FILE: src/savegame_json.cpp
LINE: 2390

I believe this occurred in the middle of an auto-save event.

At the time the save began, I may have been walking. There were no acoustic guitars in the room, as far as I can tell, and I was not interacting with one at the time. 

# Steps To Reproduce

The guitar should not be loaded with, or maybe should not bother checking for, charges, I guess. Because: it can not have any!

However, it is not limited to guitar. See context below, and:

After saving and quitting (I tried to generate a game report and although it said it did, it did not produce an object in the config folder, despite multiple attempts), I started the game again, and this debug.log file was created:

> -----------------------------------------
> 19:29:30.269 : Starting log.
> 19:29:30.269 INFO : Cataclysm DDA version 15a37481
> 19:29:30.269 INFO : [main] C locale set to en_US.UTF-8
> 19:29:30.269 INFO : [main] C++ locale set to en_US.UTF-8
> 19:29:30.272 INFO : [options] C locale set to en_US.UTF-8
> 19:29:30.272 INFO : [options] C++ locale set to en_US.UTF-8
> 19:29:30.503 WARNING : opendir [./mods/] failed with "No such file or directory".
> 19:29:37.685 WARNING : opendir [./save/Harmony/mods] failed with "No such file or directory".

Furthermore, I got another LINE 2390 error upon entering the game:
```
Item handflare was loaded with charges, but can not have any!
void item::io(Archive&) [with Archive = io::JsonObjectInputArchive]
src/savegame_json.cpp
LINE 2390
```

# Screenshots

# Versions and configuration

Active World Mods

> Dark Days Ahead
> Alternative Map Key
> No Rail Stations
> Graphical Overmap
> sees-player-icon, HitButton_iso
> sees-player icon, retrodays
> Magiclysm
> Graphical Overmap Magiclysm

# Additional context

> Ungenomoldic  Today at 6:23 PM
> Yeah, that error is everywhere in my game
> ''Item stanag_mag_10 was loaded with charges, but can not have any!''
> ''Item mask_gas was loaded with charges, but can not have any!''
> ''Item inhaler was loaded with charges, but can not have any!''
> You name it, there is a ''was loaded with charges!'' for it

**Comment by cinead** [comment]
Got a debug.info from a harmonica-holder object that exhibited this error:

-----------------------------------------
20:24:29.476 : Starting log.
20:24:29.476 INFO : Cataclysm DDA version 15a37481
20:24:29.477 INFO : [main] C locale set to en_US.UTF-8
20:24:29.477 INFO : [main] C++ locale set to en_US.UTF-8
20:24:29.478 INFO : [options] C locale set to en_US.UTF-8
20:24:29.478 INFO : [options] C++ locale set to en_US.UTF-8
20:24:29.673 WARNING : opendir [./mods/] failed with "No such file or directory".
20:24:38.626 WARNING : opendir [./save/Harmony/mods] failed with "No such file or directory".
20:25:57.956 ERROR : (error message will follow backtrace)
    ./cataclysm(_Z21debug_write_backtraceRSo+0x37) [0x55d4b57d3a3e]
    ./cataclysm(_Z8DebugLog10DebugLevel10DebugClass+0x2fb) [0x55d4b57d43fa]
    ./cataclysm(_Z12realDebugmsgPKcS0_S0_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x73) [0x55d4b57d4ef6]
    ./cataclysm(_ZN4item2ioIN2io22JsonObjectInputArchiveEEEvRT_+0x388a) [0x55d4b6498368]
    ./cataclysm(_ZN4item11deserializeER6JsonIn+0x1e4) [0x55d4b6469044]
    ./cataclysm(_ZN6JsonIn4readI4itemEEDTcmcldtfp_11deserializedefpTELb1EERT_b+0x11) [0x55d4b64989bb]
    ./cataclysm(_ZN6submap4loadER6JsonInRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi+0x107c) [0x55d4b64778bc]
    ./cataclysm(_ZN9mapbuffer11deserializeER6JsonIn+0x188) [0x55d4b5e06e18]
    ./cataclysm(_ZNSt17_Function_handlerIFvR6JsonInESt5_BindIFM9mapbufferFvS1_EPS4_St12_PlaceholderILi1EEEEE9_M_invokeERKSt9_Any_dataS1_+0x20) [0x55d4b5e07cac]
    ./cataclysm(_ZNKSt8functionIFvR6JsonInEEclES1_+0xe) [0x55d4b5621c52]
    ./cataclysm(+0x682547) [0x55d4b561d547]
    ./cataclysm(_ZNKSt8functionIFvRSiEEclES0_+0xe) [0x55d4b5621c3a]
    ./cataclysm(_Z14read_from_fileRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt8functionIFvRSiEE+0x1dc) [0x55d4b5621691]
    ./cataclysm(_Z23read_from_file_optionalRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt8functionIFvRSiEE+0x27) [0x55d4b56219a2]
    ./cataclysm(_Z28read_from_file_optional_jsonRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt8functionIFvR6JsonInEE+0x2f) [0x55d4b56219d3]
    ./cataclysm(_ZN9mapbuffer19unserialize_submapsERK8tripoint+0x8ec) [0x55d4b5e05c9e]
    ./cataclysm(_ZN9mapbuffer13lookup_submapERK8tripoint+0x138) [0x55d4b5e07bf8]
    ./cataclysm(_ZN3map5loadnERK8tripointb+0x299) [0x55d4b5da0795]
    ./cataclysm(_ZN3map5shiftERK5point+0x4c8) [0x55d4b5da1506]
    ./cataclysm(_ZN4game10update_mapERiS0_+0x14e) [0x55d4b59935a6]

    Attempting to repeat stack trace using debug symbols…
    debug_write_backtrace(std::ostream&)
    …/src/debug.cpp:777
    DebugLog(DebugLevel, DebugClass)
    …/src/debug.cpp:943
    realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    …/src/debug.cpp:115
    void realDebugmsg<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(char const*, char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    …/src/debug.h:79
    void item::io<io::JsonObjectInputArchive>(io::JsonObjectInputArchive&)
    …/src/savegame_json.cpp:2389
    item::deserialize(JsonIn&)
    …/src/savegame_json.cpp:2420
    decltype ((({parm#1}.deserialize)(*this)),(true)) JsonIn::read<item>(item&, bool)
    …/src/json.h:306
    submap::load(JsonIn&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)
    …/src/savegame_json.cpp:3979
    mapbuffer::deserialize(JsonIn&)
    …/src/mapbuffer.cpp:291
    std::_Function_handler<void (JsonIn&), std::_Bind<void (mapbuffer::*(mapbuffer*, std::_Placeholder<1>))(JsonIn&)> >::_M_invoke(std::_Any_data const&, JsonIn&)
    /usr/include/c++/7/bits/std_function.h:318
    std::function<void (JsonIn&)>::operator()(JsonIn&) const
    /usr/include/c++/7/bits/std_function.h:707
    std::_Function_handler<void (std::istream&), read_from_file_optional_json(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (JsonIn&)> const&)::{lambda(std::istream&)#1}>::_M_invoke(std::_Any_data const&, std::istream&)
    /usr/include/c++/7/bits/std_function.h:318
    std::function<void (std::istream&)>::operator()(std::istream&) const
    /usr/include/c++/7/bits/std_function.h:707
    read_from_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (std::istream&)> const&)
    …/src/cata_utility.cpp:528
    read_from_file_optional(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (std::istream&)> const&)
    …/src/cata_utility.cpp:561 (discriminator 1)
    read_from_file_optional_json(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (JsonIn&)> const&)
    …/src/cata_utility.cpp:570
    mapbuffer::unserialize_submaps(tripoint const&)
    …/src/mapbuffer.cpp:261 (discriminator 4)
    mapbuffer::lookup_submap(tripoint const&)
    …/src/mapbuffer.cpp:95
    map::loadn(tripoint const&, bool)
    …/src/map.cpp:6729
    map::shift(point const&)
    …/src/map.cpp:6594 (discriminator 2)
    game::update_map(int&, int&)
    …/src/point.h:58
    game::update_map(int&, int&)
    …/src/game.cpp:11165
Backtrace emission took 2 seconds.
src/savegame_json.cpp:2390 [void item::io(Archive&) [with Archive = io::JsonObjectInputArchive]] Item harmonica_holder was loaded with charges, but can not have any!

**Comment by cinead** [comment]
[Harmony_savefile_Bug_41821.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4872174/Harmony_savefile_Bug_41821.zip)

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/error-in-build-10820/24132/3

**Comment by anothersimulacrum** [comment]
Whoops

**Comment by matt32106** [comment]
In 10826 I got
 DEBUG    : Item handflare was loaded with charges, but can not have any!

 FUNCTION : void item::io(Archive&) [with Archive = io::JsonObjectInputArchive]
 FILE     : src/savegame_json.cpp
 LINE     : 2390

**Comment by Marrim** [comment]
Confirming.
Evident in the Overrun scenario because it always has gas masks in the warehouse where the player begins. I can start the game and play normally but if I save and reload near the warehouse I get a message about
`Item mask_gas was loaded with charges but can not have any!`
However, it does not seem to trigger again for those particular masks.

**Comment by matt32106** [comment]
In version 10852 I got this:

 DEBUG    : Item guitar_electric was loaded with charges, but can not have any!

 FUNCTION : void item::io(Archive&) [with Archive = io::JsonObjectInputArchive]
 FILE     : src/savegame_json.cpp
 LINE     : 2408

**Comment by matt32106** [comment]
In version 10852 I got this when opening a save:

DEBUG    : Item mask_bunker was loaded with charges, but can not have any!

 FUNCTION : void item::io(Archive&) [with Archive = io::JsonObjectInputArchive]
 FILE     : src/savegame_json.cpp
 LINE     : 2408

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/musical-instruments-random-charges/24205/2

**Comment by Marrim** [comment]
It seems that the bug affects solely items with "initial_charges" json property. Items that are supposed to be generated with charges, are instead generated with 0 charges, and spew the error message.

As is evident with gas masks. However, if I pick one mask up, reload it with gas mask filter, drop it (or keep it in inventory), then save and load game, it does not lose charge.

Perhaps the item generation code does not register item charges properly from the json? I haven't followed the development for a while but it seems there was a rework of how charges are handled. That could be the culprit.

**Comment by matt32106** [comment]
In version 10860
 DEBUG    : Item mask_filter was loaded with charges, but can not have any!

 FUNCTION : void item::io(Archive&) [with Archive = io::JsonObjectInputArchive]
 FILE     : src/savegame_json.cpp
 LINE     : 2466

**Comment by matt32106** [comment]
In version 10882
 DEBUG    : Item mask_bunker was loaded with charges, but can not have any!

 FUNCTION : void item::io(Archive&) [with Archive = io::JsonObjectInputArchive]
 FILE     : src/savegame_json.cpp
 LINE     : 2467

**Comment by Marrim** [comment]
I just wanna ask... is there a way to permanently suppress this message? It's a real dealbreaker when even considering playing the current experimental. Does not seem to register the skip option when "I" is pressed, probably because it affects multiple types of items?

It also makes non-reloadable items unusable, such as flares, because they now spawn with 0 charges.

Unfortunately from just looking at the code so far I can't seem to even work out how the new pocket system works. (I assume that's what probably created the bug.)

**Comment by matt32106** [comment]
> EDIT: I found something interesting!
Which version are you using?

**Comment by Marrim** [comment]
I think it was on 10845. I'm going to verify it on a fresh install and see if this behavior persists.

**Comment by wapcaplet** [comment]
Here is a save game that *should* reproduce the bug for every possible item: [no-charges-big-pile.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5081579/no-charges-big-pile.zip)

After loading this save game, walk directly to the left until you find the giant pile of everything (literally one of each item) in front of the evac shelter. (don't mind the zombies, you're invisible and invulnerable). When I do this in `0.E-5059-g10b23155f1`, there are only three items that give the error: `handflare`, `handflare_lit`, and `rx11_stimpack`.
