### ISSUE TITLE
Seg Fault crash crossing bridge

### ISSUE THREAD

**Issue by ZaricaDemoni** [CleverRaven/Cataclysm-DDA#41836]
# Describe the bug
Crossing the bridge crashes the game about halfway across, This bridge was generated using the pre-Z level change to them.

# Steps To Reproduce
Load game
Begin walking left
Crash almost exactly halfway across.

# Expected behavior
Continue walking without issue until reaching the other side.

# Versions and configuration

 - OS: Windows 8.1
 - Game Version: 0.E-3725-g69cf449
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: "dda", "no_npc_food", "blazeindustries", "crt_expansion", "magiclysm", "DinoMod", alt_map_key", "MMA", "cbm_slots", "fuji_mpp", "speedydex", "stats_through_kills", "StatsThroughSkills"

# Additional context
Verified this happens on the latest experimental as well, but I did manage to cross the bridge. it just crashed when i went back across.

Included save, as well as crashlog and debug

[Save & Crashlog.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4873509/Save.Crashlog.zip)

**Comment by EvgenijM86** [comment]
Same as #41804
Temporary fix:
```
@@ -1274,8 +1274,8 @@ bool mattack::science( monster *const z ) // I said SCIENCE again!
         valid_attacks[valid_attack_count++] = att_shock;
     }
 
-    Character *const foe = dynamic_cast<Character *>( target );
-    if( ( foe->is_avatar() ) && dist <= 2 ) {
+    player *const foe = dynamic_cast<player *>( target );
+    if( static_cast<void *>( foe ) == static_cast<void *>( &g->u ) && dist <= 2 ) {
         valid_attacks[valid_attack_count++] = att_radiation;
     }
```

**Comment by anothersimulacrum** [comment]
Closing as duplicate
