### ISSUE TITLE
Crash to desktop, random areas

### ISSUE THREAD

**Issue by Deveakkaizen** [CleverRaven/Cataclysm-DDA#41840]
Game version: 10809 but noticed the crashes several versions ago

Operating system: Windows 10

Tiles or curses: Tiles

Mods active:  Disable NPC needs, Aftershock, blaze industries, no fungal monsters, speedy dex and stats for kills

### Steps to reproduce the behavior
Walk around the map long enough

My crash log
The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 0.E-3726-g8aaf68f
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

  #0
    (dbghelp: @0x65c3d6[cataclysm-tiles.exe+0x25c3d6]), 
    (libbacktrace: Z21debug_write_backtraceRSo+0x56@0x65c3d6),
    (libbacktrace: 0x65c3d6    [unknown src]:0    [unknown func]),
  #1
    (dbghelp: @0x63c53f[cataclysm-tiles.exe+0x23c53f]), 
    (libbacktrace: log_crash+0x4af@0x63c53f),
    (libbacktrace: 0x63c53f    [unknown src]:0    [unknown func]),
  #2
    (dbghelp: @0x63d212[cataclysm-tiles.exe+0x23d212]), 
    (libbacktrace: signal_handler+0x32@0x63d212),
    (libbacktrace: 0x63d212    [unknown src]:0    [unknown func]),
  #3
    (dbghelp: SMPEG_error+0x4b034@0x10d8480[cataclysm-tiles.exe+0xcd8480]), 
    (libbacktrace: gnu_exception_handler+0x70@0x10d8480),
    (libbacktrace: 0x10d8480    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crt_handler.c:223    _gnu_exception_handler),
  #4
    (dbghelp: _C_specific_handler+0x98@0x7fff49298048[msvcrt.dll+0x28048]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #5
    (dbghelp: _chkstk+0x11f@0x7fff4ae611cf[ntdll.dll+0xa11cf]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #6
    (dbghelp: RtlRaiseException+0x399@0x7fff4ae2a209[ntdll.dll+0x6a209]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #7
    (dbghelp: KiUserExceptionDispatcher+0x2e@0x7fff4ae5fe3e[ntdll.dll+0x9fe3e]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #8
    (dbghelp: @0xb70736[cataclysm-tiles.exe+0x770736]), 
    (libbacktrace: ZN7mattack7scienceEP7monster+0xc6@0xb70736),
    (libbacktrace: 0xb70736    [unknown src]:0    [unknown func]),
  #9
    (dbghelp: @0xba5dd8[cataclysm-tiles.exe+0x7a5dd8]), 
    (libbacktrace: ZN7monster4moveEv+0x418@0xba5dd8),
    (libbacktrace: 0xba5dd8    [unknown src]:0    [unknown func]),
  #10
    (dbghelp: @0x7757b1[cataclysm-tiles.exe+0x3757b1]), 
    (libbacktrace: ZN4game7monmoveEv+0x241@0x7757b1),
    (libbacktrace: 0x7757b1    [unknown src]:0    [unknown func]),
  #11
    (dbghelp: @0x782188[cataclysm-tiles.exe+0x382188]), 
    (libbacktrace: ZN4game7do_turnEv+0x6b8@0x782188),
    (libbacktrace: 0x782188    [unknown src]:0    [unknown func]),
  #12
    (dbghelp: IMG_LoadWEBP_RW+0x6ee878@0x18b8b68[cataclysm-tiles.exe+0x14b8b68]), 
    (libbacktrace: main+0x11a8@0x18b8b68),
    (libbacktrace: 0x18b8b68    [unknown src]:0    [unknown func]),
  #13
    (dbghelp: @0x4013ed[cataclysm-tiles.exe+0x13ed]), 
    (libbacktrace: _tmainCRTStartup+0x23d@0x4013ed),
    (libbacktrace: 0x4013ed    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crtexe.c:336    __tmainCRTStartup),
  #14
    (dbghelp: @0x4014fb[cataclysm-tiles.exe+0x14fb]), 
    (libbacktrace: WinMainCRTStartup+0x1b@0x4014fb),
    (libbacktrace: 0x4014fb    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crtexe.c:186    WinMainCRTStartup),
  #15
    (dbghelp: BaseThreadInitThunk+0x14@0x7fff4a3e7bd4[KERNEL32.DLL+0x17bd4]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #16
    (dbghelp: RtlUserThreadStart+0x21@0x7fff4ae2ce51[ntdll.dll+0x6ce51]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
Sorry I am new to this.

**Comment by EvgenijM86** [comment]
`(libbacktrace: ZN7mattack7scienceEP7monster+0xc6@0xb70736),`
Same as #41804
