### ISSUE TITLE
Letting an emp grenade explode in your hands is harmless

### ISSUE THREAD

**Issue by Rjtheperson** [CleverRaven/Cataclysm-DDA#41847]
# Describe the bug

Activating an EMP grenade in your hand and letting it explode is completely harmless, even if you have cbms installed.

# Steps To Reproduce
1. Find or spawn an EMP grenade
2. Wield the EMP grenade
3. Activate the EMP grenade and wait until it explodes while you are wielding it.

# Expected behavior
EMP grenade hurts me in some way.

# Screenshots
None.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 Windows 7 Professional Version 6.1 Service Pack 1
- Game Version: 0.E-3726-g8aaf68f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Mythical Martial Arts [MMA],
    Graphical Overmap [Graphical_Overmap],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

# Additional context
None.

**Comment by esotericist** [comment]
Bare minimum: there needs to be some impact from having an EMP go off in your vicinity, if you have installed bionics.

further: we need a better notion of exactly how the sci-fi EMP grenade is meant to function. The EMP bomb has a theory of operation that is pretty well understood (being based off of real-world devices), and that results in "conventional explosion with larger EMP radius"

if the sci-fi emp grenade is not in some fashion using a conventional explosive, there should be an explanation for how it functions. personally, i would expect some kind of damaging electrical consequence while it's in your inventory if it isn't a boom-bearing object.

If it is a boom-bearing object, we could treat it as a really weak/crappy frag grenade. (probably harmless a couple tiles away, likely to be mildly harmful a tile away if you aren't wearing heavy clothes or armor, bad bad news in your hand/inventory)

**Comment by EvgenijM86** [comment]
I remember throwing one of the variants of this bomb/grenade at the turrets and then I got heavily irradiated, because I was near the explosion. Then they patched showing you how irradiated you are, so you won't notice side-affects immediately.

**Comment by anothersimulacrum** [comment]
These don't make you irradiated.

**Comment by EvgenijM86** [comment]
I guess it was the bomb variant then.

**Comment by Rjtheperson** [comment]
Fixed in #41851
