### ISSUE TITLE
Cellphone starts without battery

### ISSUE THREAD

**Issue by MarceloLaser** [CleverRaven/Cataclysm-DDA#41842]
# Describe the bug

Cellphone starting item spawned without a battery (at least for Evacuee/Survivor, have not tested others).

# Expected behavior

Cellphone should be initialized with a battery, even if it is an empty one. No one carries around a cellphone without a battery in it.

# Versions and configuration

10809

16:08:05.436 :  GAME REPORT:
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-3726-g8aaf68f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Cataclysm++ [Cata++],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food]
]

**Comment by Duck13Tales** [comment]
It seems that cellphones use disposable batteries, so if this has 0 then it is the same as having nothing. If you "load" it with the disposable batteries then you can "unload" and get the disposable batteries that still can be used.

**Comment by LucasHoage** [comment]
It looks like the definition for cell phone allows for the maximum value of charges to either be whatever was the last entry in the item group or it uses whatever the maximum battery charge is based on the magazine choices available.

I will make a fix and try to submit it

**Comment by Tamiore** [comment]
This issue is still very much present. 
And it's not just cellphones, it's pretty much anything that should have a battery (flashlight, etc).

**Comment by casswedson** [comment]
This was mostly fixed by  #33912 and #41643 apart from the hardened scavenger profession starting with only one mag for their scar-h everything else looks fine.
