### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by NBBloodhound** [CleverRaven/Cataclysm-DDA#41843]
# Describe the bug

After a seemingly random amount of time, the game crashes, with the attached crash log

# Steps To Reproduce

N/A, seems totally random, although driving a car may be a part of it

# Expected behavior

not crashing?

# Screenshots

# Versions and configuration

windows 10
0.E-3726-g8aaf68f (tiles)
english
dda, C.R.I.T. , blaze industries, MSX indicators, disable NPC needs
# Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4874224/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4874226/crash.log)

[Sterling Run.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4874227/Sterling.Run.zip)

**Comment by MarceloLaser** [comment]
I've had a very similar crash. I am attaching the crash.log to hopefully help figure out the source.

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4874461/crash.log)

10809

16:08:05.436 :  GAME REPORT:
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-3726-g8aaf68f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Cataclysm++ [Cata++],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food]
]

**Comment by olanti-p** [comment]
Both are instances of #41804
