### ISSUE TITLE
Profession starting guns start with the wrong mags

### ISSUE THREAD

**Issue by YourCompanionCube** [CleverRaven/Cataclysm-DDA#41865]
# Describe the bug
Guns given with a profession seem to default to a magazine (based on type of ammo) regardless of how many charges are supposed to be loaded

# Steps To Reproduce
Create a character and select military recruit as your profession, you will see the M4A1 is loaded with a 10 round mag despite having 30 rounds specified in the Professions.json and the Special Operator with 30 rounds in a 50 round magazine

# Expected behavior
That guns be loaded with mags appropriate for the number of rounds specified, or at least have the correct magazines specified in Professions.json

# Screenshots

![M4 wrong load](https://user-images.githubusercontent.com/26364270/86537203-3d9bbd80-bebb-11ea-82f7-9b99a2045b1f.png)
![MP5 Wrong load](https://user-images.githubusercontent.com/26364270/86537216-5310e780-bebb-11ea-909f-a9fe3bfb399b.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-3769-g1f55aa9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Alternative Map Key [alt_map_key],
    Disable NPC Needs [no_npc_food],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    No Rail Stations [No_Rail_Stations],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    More Survivor Stuff [more_survivor_stuff]
]

# Additional context

**Comment by kevingranade** [comment]
Probably fixed by #45705

**Comment by hexagonrecursion** [comment]
Can not reproduce
* military recruits spawn with M4A1+1 (30/30 .223)
* special operators spawn with H&K MP5A2+3 (30/30 9x19mm)
