### ISSUE TITLE
When I save it always says Failed to write 

### ISSUE THREAD

**Issue by Mybachhertz** [CleverRaven/Cataclysm-DDA#41862]
# when I save it says Failed to write

# Steps To Reproduce

# Expected behavior

**Comment by Muffindrake** [comment]
Please follow the template outlined here

https://github.com/CleverRaven/Cataclysm-DDA/issues/new?template=bug_report.md

In particular for an issue like this, game version and operating system are very important information that we could use to help. Posting the debug.log after you attempt a save may also shed light.

**Comment by ZhilkinSerg** [comment]
That is an environmental issue we cannot really help you with besides some common advices. Make sure you have enough free disk space, path to game executable is not too long and you have write access to game folder location.
