### ISSUE TITLE
Washing a dirty container (e.g. backpack) with items inside requires more charges of water & soap then needed if empty

### ISSUE THREAD

**Issue by placeybordeaux** [CleverRaven/Cataclysm-DDA#41864]
# Describe the bug

If you have a filthy backpack, load it with items and then go to wash it, the washing screen will count the number of charges correct, but when you go to wash it it will fail with something like "you need 200 charges of water to wash these items

# Steps To Reproduce

1. Make a player with a filthy backpack and multiple other items that can be put inside it. As well as a gallon of water, a soap bar and a washing kit.
2. Fill the backpack with those items
3. Attempt to wash the backpack, observe that it allows you to start the action but fails.

# Expected behavior

The backpack is washed.

# Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.E-3725-g69cf4495c2-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Graphical Overmap [Graphical_Overmap],
    sees-player icon, retrodays [sees_player_retro],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Night-Pryanik** [comment]
#41801 should've fixed this bug. Could you please update to latest experimental and check if this still an issue?

**Comment by anothersimulacrum** [comment]
Closing as resolved in #41801.
