### ISSUE TITLE
Can't use filthy rags to craft anything

### ISSUE THREAD

**Issue by Duck13Tales** [CleverRaven/Cataclysm-DDA#41878]
# Describe the bug

I got a bunch of rags (filthy) I can't craft anything with those even though in the description screen it says that I know a dozen of things to make with them.

# Steps To Reproduce

Kill some zombies, loot them and then disassemble/cut their filthy clothes to get filthy rags and then try to craft something with them.

# Expected behavior

To be able to craft things with filthy components, even if the result is something filthy, or at least say somewhere that you can't craft anything with filthy components.

# Screenshots

Not needed.

I am using using the CDDA 0.E-b10798 with the mods:

DDA
Disable NPC needs
Stats through skills
Stats through kills
SpeedyDex

**Comment by anothersimulacrum** [comment]
The game should communicate somewhere that you can't craft things with filthy components.

**Comment by Night-Pryanik** [comment]
Unable to use filthy components for crafting is intended. Just wash them before using.

**Comment by Duck13Tales** [comment]
Yes, but it would be easier for new people if the game said this. If possible state this everywhere possible hahaha
