### ISSUE TITLE
Martial art grab break techniques not activating

### ISSUE THREAD

**Issue by harison86** [CleverRaven/Cataclysm-DDA#41876]
# Describe the bug

Grab breaks from martial arts do not trigger when the player is grabbed.

# Steps To Reproduce

1. Make a character with any martial art that includes a grab break technique (e.g. Muay Thai), and sufficient skill levels to use the technique.
2. Find/spawn a grab-capable enemy (e.g. most zombies).

3. Engage the enemy in melee combat.
4. Observe that the player character will not use martial art techniques to break grabs. They will not use a technique to break grabs at the instant they are grabbed, when they attack while grabbed, nor when they attempt to walk away.

# Expected behavior

The player character should break grabs with martial art techniques if they have sufficient skill. If I recall correctly, this is supposed to happen at the moment the enemy grabs the player. A unique message would also be displayed in the message log when the player uses martial arts to escape a grab.

# Screenshots

![grab test](https://user-images.githubusercontent.com/32041963/86541773-9714e400-bedd-11ea-934d-31bc6fe741a7.png)

# Versions and configuration

 - OS: Windows 7
 - Game Version: 0.E-3770-g879889a (latest experimental as of writing)
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: dda, no_npc_food

# Additional context

**Comment by anothersimulacrum** [comment]
Fixed #42698
