### ISSUE TITLE
Calcium shouldn't be so hard to get

### ISSUE THREAD

**Issue by TheMasterGear** [CleverRaven/Cataclysm-DDA#41872]
# Is your feature request related to a problem? Please describe.
Every time I play cataclysm, after a few months my character always gets low calcium despite eating food that would in real life give more than calcium. Like dandelions, bone broth, and most vegetables. This then results in them binge eating vegetables or using calcium pills so I don't get too much iron or vitamin A.

![needs](https://user-images.githubusercontent.com/60374171/86539183-91f96a00-bec8-11ea-9c03-971aa7203c0a.png)

# Describe the solution you'd like
Revised calcium values for most food.

# Describe alternatives you've considered

- Bone broth should have a lot of calcium.
- Let us grind bones into a powder to eat for more calcium.
- Dandelion tea should have some vitamin continent, including calcium. The same can be said about most of the teas in the game.

# Additional context
Personally in real life, I don't take calcium pills unless if it's very low and you also need to take vitamin K for it to get used by your body. That's why eating vegetables is the best way to get calcium because it also has vitamin K in it.

**Comment by TheMasterGear** [comment]
After a bit of research, I found that bone broth its self doesn't have much calcium in it as the bones are discarded in the process. So bone broth should have a byproduct of cooked bones, which would be soft enough to eat. Plus, they would also have marrow, which would have a lot of iron as well.

**Comment by TheMasterGear** [comment]
After editing bones and bone meal. I found out that powder can't be eaten, even if its comestible type is food.

**Comment by MatiasFito** [comment]
Hmm maybe then add alternative recipes for some already existing ones, but with 10 bone meal added, and with extra calcium values? :thinking:

**Comment by Rjtheperson** [comment]
[http://cdda-trunk.chezzo.com/bonemeal_tablet/craft](url) Have you tried making your own vitamins?
