### ISSUE TITLE
Improve support for alternate vehicle part views

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#41873]
# Is your feature request related to a problem? Please describe.
The current vehicle part installation menu for vehicle parts with multiple positional versions gives only an ASCII character representation of the part to be installed, which may not easily inform the tileset appearance of that sprite. For example, `|` places the part with the name `vp_whatever_vertical` and `H` places `vp_whatever_vertical2`. This is limited and nondescriptive to the player.

Additionally, for some directional parts there are too few or too many options for what shapes to place.

# Describe the solution you'd like
Allow JSON definition of both what ASCII characters to use for each part, and allow a name to be specified in part selection. Eg:
```
"Parts_names": [
{ "part_type": "vertical", "symbol": "|", "description": "vertical panel, left side" }
{ "part_type": "vertical2", "symbol": "|", "description": "vertical panel, right side" }
]
```
In this example, we'd no longer see the `H` option at all, only a second vertical bar that would correspond to the right sided vertical panel.

Ideally this would allow the declaration of new part types so that we could have eg `vertical_right`, `vertical_left`, and `vertical_internal` each with its own sprite and potentially with different ASCII character representation as well.

With arbitrary declaration of different part views, we could even have things like windshields that look different for pickup trucks versus cars, or that terminate nicely with a border if they're the frontmost panel of the car.

# Describe alternatives you've considered
An automatic system for defining this would be amazing, but in many ways it's actually better if players can choose the part so that homemade deathmobiles don't get weird behaviour.

An ideal system would just *display* the graphic for the part we're installing, but I know better than to ask for that.

# Additional context
With arbitrary parts lists I could get pickup trucks look as good as I can already make sedans:
![image](https://user-images.githubusercontent.com/45136638/86539913-45f0fa00-beb5-11ea-911d-faf760f7ab4b.png) ![image](https://user-images.githubusercontent.com/45136638/86539912-3c679200-beb5-11ea-9776-a6e869e80721.png)
And much, much more.

This stage is possible thanks to @mrkybe's work with parts already.

**Comment by I-am-Erk** [comment]
So it appears the arbitrary number of parts thing is already in place. All we need is better support for the description of the vehicle part to be added.

**Comment by Qrox** [comment]
> An ideal system would just display the graphic for the part we're installing

I think this can be done by using `game::redraw_callback_t` and graphic override used currently by debug preview.

**Comment by I-am-Erk** [comment]
I forgot to close this issue when I learned how to do most of what I want. There is a separate issue here but I will write it as its own thing.
