### ISSUE TITLE
Dynamite bundle for demolition purposes

### ISSUE THREAD

**Issue by pantherpusher** [CleverRaven/Cataclysm-DDA#41882]
# Is your feature request related to a problem? Please describe.
Whenever I wanna blow open a wall, C4 is my only option it seems, whilst dynamite has been used for centuries to demolish stuff. It seems as though no explosives besides C4 can be used for the purpose of breaching.

# Describe the solution you'd like
I would like to see implemented a recipe to craft a new kind of explosive, a dynamite bundle. The recipe would require three sticks of dynamite and either tape or string or glue to bind the sticks together. The fuse length would be the same as a single stick of dynamite unless there's some standard for fuses I don't know, although some kind of version with a timer that uses some wire and solder and a watch of some kind would be cool. Everyone knows the classic bundle of dynamite with the clock on it.

# Describe alternatives you've considered
Making explosives whose primary method of damage is not shrapnel able deal bash damage like C4, which would probably be a good change, but I'd still want to see a dynamite bundle

**Comment by Duck13Tales** [comment]
It would be nice! Dinamite is a historical explosive used to explode walls though though "explosion proof" modern walls and equipment would only be breached by C4 or higher grade explosives.
