### ISSUE TITLE
Plutonium Fuel Cell Duplication

### ISSUE THREAD

**Issue by DatMeg** [CleverRaven/Cataclysm-DDA#41883]
# Describe the bug

This appears to be a reemergence of #25697 from late 2018, where loading a Minireactor, then unloading it would duplicate Fuel Cells. A little surprised to see this one come back.

# Steps To Reproduce

1. Spawn the Atomic Sports Car
2. Attempt to Unload the Minireactor while it's attached to the vehicle (get 20 cells)
3. Reload the Minieactor, then remove it from the vehicle
4. Unload the detached Minireactor vehicle part (get 10,000 cells)

# Expected behavior

If we were going to be breeding fissionable material, I'm not sure a Minireactor is the place to do it.

# Screenshots
![image](https://user-images.githubusercontent.com/17204395/86545178-0fd66900-befb-11ea-8bcb-7e926e0cab23.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-3770-g879889a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by hexagonrecursion** [comment]
Related  #41329
