### ISSUE TITLE
When the player chooses to dig a pit over a clay or sand patch the game should extact it instead

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#41893]
# Is your feature request related to a problem? Please describe.
For some time now I was confused about how the sand and clay tiles are supposed to function. I'd stand on one, activate my shovel, see the "dig pit here" (sic) action and select it, but it would yield the same amount of clay or sand as digging anywhere else.

Recently thanks to Vormithrax I discovered the "extract clay" and "extract sand" options in the "Construct Terrain" menu. I think it would be better for new players if the UI was less confusing.

# Describe the solution you'd like
Digging a pit over regular soil should continue to work as normal, but trying to dig a pit over clay or sand should extract it instead.

# Describe alternatives you've considered
- Add a separate extract sand/clay action to the shovel activation menu
- Move the "dig pit here" action to the "Construct Terrain" menu. Note: this will require adding some kind of hint to the shovel description or use action menu because it is not obvious to a new player that they should look for those options in the "*Construct* Terrain" menu.

# Additional context
none

**Comment by Night-Pryanik** [comment]
@nexusmrsep any progress on this?

**Comment by Zireael07** [comment]
Do we have a Quality of Life label? This is a prime candidate...
