### ISSUE TITLE
Add a ranged aiming interruption check for Friendly NPCs within line of fire.

### ISSUE THREAD

**Issue by sharkfinsouperman** [CleverRaven/Cataclysm-DDA#41895]
Aiming will be interrupted with an option to stop if a foe enters LOS, even if it is 60 spaces away, but there is none if an NPC happens to reposition into line of fire while the player is aiming. This results in unnecessary friendly fire.

In addition, picking up items have more risk-check interruptions than potential friendly fire does.

I think a check for friendly fire would be a great improvement to QOL.

**Comment by Duck13Tales** [comment]
Sure! Or at least one right before firing.

**Comment by anothersimulacrum** [comment]
Being worked on actively.
