### ISSUE TITLE
Arachnid can't lay web

### ISSUE THREAD

**Issue by SatanHellLord** [CleverRaven/Cataclysm-DDA#41900]
# Describe the bug

As an Arachnid, you can not lay Webs, be it with the Web Weaver or Web Spinner mutation: the cobweb spawns, but stays stuck to your character. They neither level up to webs or thick webs, making it basically impossible to sleep if you don't find "natural" thick webs. You still consume food and water while it is activated.

I tested in multiples worlds with and without additional mods, on the latest Experimental Branch, and the issue stays.

# Steps To Reproduce

1. Become an Arachnid and obtain the Web Spinner or Web Weaver perk.
2. Activate the Web Weaver perk (Web Spinner always activated as it is a bad trait)
3. The cobweb stays stuck at your feet and follows you, never growing but still consuming food and water.

# Expected behavior

The web should stick to the ground and grow to the later stages.

# Screenshots

N/A

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-3780-g54cde4b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    No Fungal Monsters [No_Fungi],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Fris0uman** [comment]
Probably caused by #41032 that changed the way web field behaves.
