### ISSUE TITLE
Several items that can't be disassembled

### ISSUE THREAD

**Issue by Duck13Tales** [CleverRaven/Cataclysm-DDA#41906]
# Is your feature request related to a problem? Please describe.

There are some mundane items that can't be disassembled but there are similar items that can, and some of those can't even be cut or smashed and I did some experience with them and they sometimes even seem indestructible. For example the bottle and can openers.

# Describe the solution you'd like

Create recipes for the disassemble of those items and maybe some other recipes that use those items. Maybe even giving some "action" for those items.

# Describe alternatives you've considered

Create some recipes or equipment that "use" those and produce something else, though they can exist and still we have a way to disassemble or smash/cut those items.

# Additional context

It is hard to think that in the CDDA environment there would exist something that we really couldn't make any use of it, and that those entities are sometimes almost indestructible.

# Suggestion

Can I make a PR with some of those disassemble recipes? Is it hard? Or is there someone else working on it?

**Comment by Zireael07** [comment]
If you don't list all of those items, how can people tell if they're working on it?

**Comment by Duck13Tales** [comment]
For example there is the bottle opener and the can opener. The basketball that you can cut but can disassemble and several others.

**Comment by Duck13Tales** [comment]
I can make a list of some of the items that I found but most of them are like the bottle opener, the can opener or the basketball. Do you really want?

**Comment by UmbralReaper** [comment]
The basketball can be cut but not disassembled because disassembling it will lead to much the same resources. The bottle and can opener cannot be disassembled or cut because no real usable resources will come out of breaking them into pieces (maybe a scrap metal and a plastic chunk?).

> I can make a list of some of the items that I found


Please do.

**Comment by Duck13Tales** [comment]
Here is a list with some items that can't be disassembled, those that have the asterisk (*) at least can be cut/smashed:

bread knife
butcher knife
carving knife
chef knife
dive knife
meat cleaver
paring knife
survival knife
switch blade
vegetable cleaver
X-Acto knife
harmonica with a holder
whistle
Swiss Army knife
bathroom scale
bottle jack
clamp
entrenching tool
hammer
pair of metal tongs
pet carrier
pliers
pocket knife
scissor jack
screwdriver
screwdriver set
sewing kit
steel frying pan
wood axe
wood saw
wrench
advanced electronic cigarette
water faucet
10" small wheel
17" wheel
whisk
bottle opener
butter knife
can opener
carving fork
corkscrew
garlic press
ladle
potato masher
toilet brush
vegetable peeler
small lock and key
condensor coil
evaporator coil
light battery
steel chain
plastic sheet*
frisbee*
barometer*
blood draw kit*
bubble wrap*
compressed air horn
folded emergency blanket*
folded poncho*
funnel*
pair of scissors
permanent marker
scrub brush*
shaving kit*
sponge
umbrella
arrow rest
saddle
toothbrush
comb
golf ball*
hair curler
hairbrush
kiddie bowl
kiddie spoon
plastic fork
plastic knife
plastic plate*
plastic spoon
plastic tumbler*
pool ball*
professional plunger*
sippy cup
soap dish
toilet brush
hydration pack*

As you can see most of them would have no use if they can't at least disassemble. Even if it is only a chunk of plastic or a scrap of metal it would be very useful for a survivor. It is kind of immersion breaking having things that can't have any use, not even being disassembled or smashed for their most basic components. And it feels quite incomplete for example being able to disassemble a football but not a basketball...

I am trying to make my first anvil and was looting some houses and then gathered EVERYTHING that I could put my hands on and made back to my LMOE. Then I got everything that was made of steel and got ready to make some scraps of metal out of them just to find that instead most things had no use at all.

I was thinking of getting those chunks of plastic or scrap of metal based in the item weight would be fair enough!

**Comment by Duck13Tales** [comment]
So do you think it is a thing? Can I make it or is someone else working on it?

**Comment by UmbralReaper** [comment]
There's no active PR as to this, so go ahead (please, I too have often wondered why some of these items are unbreakable.). 
Just consider the relative sizes of the plastic items - a lot of them will not make one plastic chunk :
```
plastic chunk: 250 ml

professional plunger: 2400ml
frisbee: 500ml
plastic tumbler: 262ml
plastic plate: 262ml
sponge: 250 ml
scrub brush: 250ml
kiddie bowl: 131ml
sippy cup: 131ml
potato masher: 75ml
garlic press: 75ml
ladle: 75ml
comb: 50ml
soap dish: 50ml
toothbrush: 50ml
hairbrush: 50ml
plastic fork: 25ml
plastic knife:  25ml
plastic spoon: 25ml
hair curler: 25ml
kiddie spoon: 12.5ml
```
To a lesser degree, it also effects metal items with their smallest denominator ```scrap metal: 250ml```

**Comment by Duck13Tales** [comment]
I just did the PR but I want to change some other things too. Like: it takes a good amount of time, skill and resources to a nice weapon from a bunch of metal scraps but it would take far less time to turn that weapon in a lump of metal if you have a good hammer and the will to do so.

Basically I think it is ok to spend some time to disassemble something into it's nice and delicate components but it would take way less to get some crude raw materials.

So I would like to change some recipes so that the "disassemble" takes less time than to create some of the items for those that the disassemble result is only some crude raw materials. Is it ok to work on it?

And how can I "save" what materials I used in crafting but when I disassemble I get some of them different? For example: there are some recipes that have "reversible": true but they use superglue for example, it is ok to get back the materials used but not the superglue from the disassemble. Is there a way to do it?

**Comment by UmbralReaper** [comment]
>For example: there are some recipes that have "reversible": true but they use superglue for example, it is ok to get back the materials used but not the superglue from the disassemble. Is there a way to do it?

I have no idea. You could make a disassemble recipe but I can see that having problems with recipes with multiple options. 

> So I would like to change some recipes so that the "disassemble" takes less time than to create some of the items for those that the disassemble result is only some crude raw materials. Is it ok to work on it?

Yeah, go ahead. It would be unrealistic if it took 3.5 hours just to smash a knife with a hammer.

**Comment by UmbralReaper** [comment]
> For example: there are some recipes that have "reversible": true but they use superglue for example, it is ok to get back the materials used but not the superglue from the disassemble. Is there a way to do it?

Yes! Check out wapcaplet's updated docs at #42084. All you have to do is add the "NO_RECOVER" flag to the item you do not want to be recoverable. It will end up looking like this, 
```"components": [ [ [ "item_a", 4 ], [  "superglue", 2, "NO_RECOVER" ] ] ]```
