### ISSUE TITLE
Add an option to send debug reports directly to a dev controlled mailbox/site

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#41909]
# Is your feature request related to a problem? Please describe.
It takes quite some time to make a proper bug report when encountering a debug message. I think (but I may be wrong)  that most of them are never posted on github and those that are posted are often missing one of the  requested information which causes a loss of time for the devs/triage...

# Describe the solution you'd like
An option to set this process to automatic so that the crash.log, debug.log and save are automatically posted when a debug message happens (this option could be on by default for experimental and off by default for stable?).

**Comment by ZhilkinSerg** [comment]
Spamming is a really bad idea.

**Comment by Leland** [comment]
If we get the macOS version onto the App Store (which is a process out of scope for this issue) we can start collecting [anonymous crash reports](https://help.apple.com/xcode/mac/current/#/dev675635e70) automatically!

For other platforms, I'd probably advocate we use an existing tool to handle this since guaranteeing anonymity is hard.

Know some folks (rightfully) get spooked from this kind of stuff, but getting basic, anonymous information about crash and usage data on an opt-in basis is a good thing in my book.

**Comment by kevingranade** [comment]
Agreed that mandatory or opt-out is a no-go.  We would essentially need some kind of hosted option for the crash reports, though if they are backtraces rather than core dumps, simply posting them anonymously to a known location like a pastebin could be sufficient.

**Comment by matt32106** [comment]
The current debug window could be modified to add a user prompt "press S to send the bug report to pastebin/whatever"

**Comment by ZhilkinSerg** [comment]
> 
> 
> The current debug window could be modified to add a user prompt "press S to send the bug report to pastebin/whatever"

That is not the hard part. There should a process, infrastructure supporting it and most importantly people who will be involved in that process.

**Comment by matt32106** [comment]
>  people who will be involved in that process.
Not necessarily, the same people as in today process will just have access to more precise information or use it as a complementary source of information (ex: A reports debug message X but don't say which version he is using, bug fixer can check if the bug X was reported in the automated list and get technical information there, versions). 

> That is not the hard part. 
Thanks for this helpful and friendly comment, but this is not your first.
