### ISSUE TITLE
Cooking broth with different ingredients yield always the same nutrition

### ISSUE THREAD

**Issue by Duck13Tales** [CleverRaven/Cataclysm-DDA#41929]
# Describe the bug

I tried cooking "broth" with different ingredients but I always got the same Iron (3%), then I looked into the recipe in comestibles\soup.json and found the line "vitamins": [ [ "iron", 3 ] ] in the "broth" recipe. Then I deleted it but now I always get Calcium (1%), Vitamin A (10%) and Vitamin C (5%) with any ingredient.

The Calcium (1%), Vitamin A (10%) and Vitamin C (5%) is the same thing I get from "broth" when spawning it from the debug menu.

Anyone knows how can I fix it? I want to make the "broth" inherit the nutrition or part of the nutrition of the used ingredients.

I noticed that the recipe in the json also has ""calories": 13," and I tried deleting it but then I always get 0 calories instead of the ingredient's calories.

# Steps To Reproduce

1 - Try cooking broth with different ingredients and notice that it always has Iron (3%)
2 - Go to the json\items\comestibles\soup.json and delete the "vitamins": [ [ "iron", 3 ] ] in the broth recipe
3 - Try cooking broth again with different ingredients and notice that it always has Calcium (1%), Vitamin A (10%) and Vitamin C (5%) with anything.

# Expected behavior

The recipes should inherit the nutrition from its components.

# Screenshots

![broth](https://user-images.githubusercontent.com/67176313/86829132-6e6e2500-c06a-11ea-9c34-68951b82b95a.png)

# Versions and configuration

I am using using the CDDA 0.E-b10798 with the mods:

DDA
Disable NPC needs
Stats through skills
Stats through kills
SpeedyDex

**Comment by Duck13Tales** [comment]
I just did the exact same test in the stable version and it worked perfectly. Then I tried in a fresh install of experimental b10815 without modifying any json and it didn't work.

It seems that somewhere in the way it got broken.

**Comment by danielkwinsor** [comment]
May have been fixed.  I cannot reproduce, with 1 unit of cattail stalk and 1 unit of bird egg.  different calories and RDA.

**Comment by RenechCDDA** [comment]
Cannot reproduce on https://github.com/CleverRaven/Cataclysm-DDA/commit/c94dc0387513d5bba49eb7d74b2b51a7a4d8c4a0
