### ISSUE TITLE
[Android] Udead People tileset crash the game

### ISSUE THREAD

**Issue by ChtulhuBeast** [CleverRaven/Cataclysm-DDA#41925]
# Describe the bug
When installing a tileset and starting my save, the game crashes without error.

# Steps To Reproduce
1. Set tileset in settings
2. Start loading
3. Wait until the end

# Expected behavior
Not a game crash. Perhaps this is due to the new version, before everything was fine.

# Screenshots

# Versions and configuration
OS: Android 7.1.1
Game version: 0.E-2
Graphics version: Tiles
Ingame language: Russian
Mods loaded: dda, no npc food, Mining Mod, C.R.I.T Expansion Mod, Alternative Map Key, FewerFarms, Nonperishable Overhaul, speedydex, Fuji's Military Profession Pack, StatsThroughSkills, stats through kills, no reviving zombies.

# Additional context
I tried changing the tileset right during the game, changing in the main menu and then going to my save game, creating a new world without mods. Nothing worked, please help.

[debug.log.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4885604/debug.log.zip)

**Comment by anothersimulacrum** [comment]
We don't have anything to do with this tileset, so we can't make changes to it. Your phone likely does not have the memory to support this tileset, which we similarly can't do anything about.

**Comment by ChtulhuBeast** [comment]
> Your phone likely does not have the memory to support this tileset, which we similarly can't do anything about.
Why then in the experimental version between the last stable and this one everything worked for me?

**Comment by Zireael07** [comment]
Most likely because there are more and more things added to the game, therefore requiring tileset authors to add more tiles. More tiles = more memory needed.
