### ISSUE TITLE
Autodoc makes the character fall asleep and wakeup repeatedly while performing operation

### ISSUE THREAD

**Issue by Suneku666** [CleverRaven/Cataclysm-DDA#41930]
Game version: 0.E-3783-g754b89e (10815)

Operating system: Windows 10

Tiles or curses: 

Mods active: Magiclysm, alternative map key, speedyDex, Mythical Martial Arts.

### Expected behavior
The autodoc should put you under and wake up after finishing operation.
### Actual behavior
Autodoc puts you under and then repeatedly wakes up and puts under like in the screenshot.  

### Steps to reproduce the behavior
Was not able to reproduce with a new character. 
I attach the current save I use that can reproduce the bug every time autodoc is used. (autodoc is in the nearby lab on Lvl -3) 

[Woodstown.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4887036/Woodstown.zip)
![unknown](https://user-images.githubusercontent.com/11499516/86839897-ec95f000-c099-11ea-890e-a99a6669c635.png)

**Comment by Suneku666** [comment]
Update: did some more testing and it appears that only the autodoc in lab on the screenshot was doing that. I tried with some others on the same savegame and they worked properly. 

Apparently this autodoc had a hostile nurse bot on spawn that got killed.

**Comment by Fris0uman** [comment]
So I can reproduce it with your save and that Autodoc, if I spawn an autodoc somewhere else it doesn't happen. This is very weird

**Comment by Fris0uman** [comment]
I think I found the problem
![image](https://user-images.githubusercontent.com/41293484/87873503-5e3b3b80-c9c2-11ea-9263-b2f2bd84ef74.png)
