### ISSUE TITLE
Item deletion bug/wielded item wierdness 

### ISSUE THREAD

**Issue by elsxf** [CleverRaven/Cataclysm-DDA#41936]
- OS Version: Distributor ID: Ubuntu; Description: Ubuntu 16.04.6 LTS; Release: 16.04; Codename: xenial; 
- Game Version: 0.E-1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA],
    No Fungal Monsters [No_Fungi],
    Bionic Slots [cbm_slots],
    Stats Through Skills [StatsThroughSkills]
]

### Steps to reproduce the behavior
While wielding multiple stackable items (e.x. pebbles, sand, soil),
![Screenshot from 2020-07-07 17-20-55](https://user-images.githubusercontent.com/26252111/86850389-d296e600-c076-11ea-9de4-de8f042d4ded.png)

 drop one of these items on the ground.
![Screenshot from 2020-07-07 17-21-10](https://user-images.githubusercontent.com/26252111/86850401-d62a6d00-c076-11ea-8600-28fc9923e0e8.png)

 use the pick up items at players feet while having no inventory space. The game asks you if you would like to dispose of your wielded item to wield the item at your feet.
![Screenshot from 2020-07-07 17-21-23](https://user-images.githubusercontent.com/26252111/86850408-d88cc700-c076-11ea-8f15-7d7ae3910535.png)

### Expected behavior
upon pressing enter, the wielded item is dropped, and the one at the player's feet is wielded instead

### Actual behavior
the current wieled item is deleted and the item at the players feet is wielded

save file:
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4887443/save.zip)

**Comment by Qrox** [comment]
Probably caused by #37267. Also see #33422 and #35353.
