### ISSUE TITLE
Allow acid for water cannons/squirt guns

### ISSUE THREAD

**Issue by souricelle** [CleverRaven/Cataclysm-DDA#41931]
There are a few acid-related weapons in the game, but not very many. We can craft lots of acid and there are enemies that use it on us, we should be able to do the same. I tried filling a water cannon with acid but it wouldn't take it as ammo and this made me very sad.

Good acid would probably melt a standard kid's squirt gun or a fire engine's water cannon, but chemists should be able to rig parts up out of acidproof plastics, copper, and glass. The vehicle and handheld versions of these weapons could function much like the acid spit that some ants and zombies use, possibly with smaller acid pools generated for the handheld version.

We can already use traps and fire to kite zombies into areas that passively damage them, so I feel like this wouldn't be a balance issue, and there's always the risk that you'll miss and wind up standing in acid or having to run through your own acid pools to escape. One factor to consider is that it's very easy to get concentrated acid just by endlessly boiling salt water, so maybe that should do less damage or evaporate more quickly than things like nitric acid. Also if your vehicle's acid tank breaks that might be bad news for your car and everyone in it.

**Comment by kevingranade** [comment]
Rather than extending the usefulness of acid further I would say we would be far more likely to make it much more difficult to acquire and store concentrated acids.

Please provide some sources supporting the existence and craftability of concentrated acid projectors.

**Comment by souricelle** [comment]
The game is full of zombies that produce massive quantities of acid and have no problem storing and projecting it from a human body that does not appear to be made of special tissue, but here are some real world examples: 

https://en.wikipedia.org/wiki/Blister_agent - Acid and other corrosive compounds have been used in warfare for over a century and when it's the burning type rather than the choking type, we call it a blister agent. There's already a book on chemical warfare in game that should cover this.

https://www.dailymail.co.uk/news/article-5853101/Pupil-filled-water-pistol-deadly-hydrochloric-acid-squirted-terrified-classmate.html - A kid loaded a water pistol with some crap he found in his school science lab and almost blinded one of his schoolmates.

https://www.cdc.gov/mmwr/preview/mmwrhtml/mm5228a3.htm - It's very easy to make bombs by mixing household chemicals. There's at least one incident involving mustard gas here which causes severe chemical burns.

Usually when acid kills people it's due to lung damage or acidosis, a metabolic issue where your blood PH dips too low and your body shuts down. Zombies probably wouldn't care about that as they don't seem to rely on the host organism's metabolism to survive, however in Cataclysm we clearly have enormous amounts of readily available chemical compounds that dissolve flesh in a much more cartoonish way. Just watch zombies go to war with acid ants or get nuked by an experimental lab bot.

Even just limiting ourselves to realistic acid you can get all kinds of compounds that burn and blister flesh and blind enemies in a matter of seconds. We don't use them in real-world warfare very often because it's horrible and usually a violation of international law but you absolutely can put acid in a squirt gun as long as the gun is made from the right kind of plastic.

**Comment by kevingranade** [comment]
You're reinforcing my point. There are various options for doing chemical warfare but none of them boil down to "adjust a water sprayer to instead spray acid". It's more nuanced than that.
