### ISSUE TITLE
Base move cost should be more transparent

### ISSUE THREAD

**Issue by FunnyMan3595** [CleverRaven/Cataclysm-DDA#41941]
# Is your feature request related to a problem? Please describe.
"So my character has a very slow move speed, and I'm not sure why"
[image](https://user-images.githubusercontent.com/98381/86870742-ce29f780-c08d-11ea-81a9-5fe09e211032.png)
The speed modifiers are clear, but the Base Move Cost of 134 is opaque.

# Describe the solution you'd like
Find somewhere to break down Base Move Cost, so that it's obvious that (for instance) having damaged legs slows you down.

# Describe alternatives you've considered
n/a

# Additional context
n/a

**Comment by GGgatherer** [comment]
>Find somewhere to break down Base Move Cost

You don't even have to search, there's already place for it right where all other things are explained - 2nd horizontal section (strength explanation in your screenshot). 
Would also be nice to see speed modifiers explanation moved there in case of more such modifiers added in the future. Or, at least, for standardization of character screen.
