### ISSUE TITLE
Smart controller lore and UX — discussion

### ISSUE THREAD

**Issue by Aivean** [CleverRaven/Cataclysm-DDA#41958]
Follow up for #41780.

I was suggested to further improve the smart controller, in particular I need to incorporate it into the game lore 
and introduce it to the players. I'd like to run some ideas through dev team and community, especially the lore.

So far I've got [an input](https://github.com/CleverRaven/Cataclysm-DDA/pull/41780#issuecomment-653394329) from @nexusmrsep :

> It doesn't have to be here and now, but consider adding a pamphlet, a news article, snippets/tips etc. to hint players of its functionality and benefits.

> Idea from watching your videos (big thumbs up) - perhaps (as a future feature) smart controller could be instructed by the driver to cut off electrical engines at given battery capacity (ex. 20%) and re-enable them after battery is restored to another given capacity (ex. 95%). This would allow prolonged support from electric engines while reserving some battery for gas/diesel engines to start.

What I'm thinking:
* introduce a new corporation that specializes in AI/automation, something like "AI Corp" (I'm bad with names). Perhaps I can reuse existing one?
* add one or more fliers with advertisements for the Smart Controller from "AI Corp" 
   * I would appreciate the help with the flavor
* (optional?)  replace single on/off switch in "control vehicle" UI  with dedicated submenu, with following options:
   * on/off switch
   * single slider that separates three "battery zones", where electric motor:
      * never turns on
      * turns on depending on the load/charging rage
      * is preferred
   * user manual — another window with the short text description of the features of the smart controller, and perhaps some examples of the common use cases

I think stylized ASCII interface panel will look cool, but I might be mistaken and I'm not sure if it fits with other UI (or if it might lead to the problem with translation). Here is the mockup that I came up with:

```
+-------------------------------------+
|                                     |
|                                     |
|      Smart Controller ®             |
|                  by AI Corp         |
|                                     |
|                        __           |
|  >   OFF  +XX+-+  ON  (__)          |
|                                     |
|                                     |
|                                     |
|      Electric Motor Use             |
|      (% battery, tab to switch)     |
|                                     |
|         25%         65%             |
|  >   +---+X+-------+X+---+          |
|      Never           Always         |
|                                     |
|                                     |
|                                     |
|                                     |
|                                     |
|  >   User manual                    |
|                                     |
|                                     |
+-------------------------------------+
```

**Comment by UmbralReaper** [comment]
I would love to be able to alter the percentage at which it switches from electric to gas (so, dedicated submenu). It would also be nice to have the option to completely disable a specific engine or engine type.

**Comment by Xenomorph-III** [comment]
You might be able to flavour the controller as being developed by Hub 01 - who developed dimensional heuristics AI before the cataclysm.

Or some other fictional corp.

**Comment by anothersimulacrum** [comment]
This is just used to implement hybrid cars, no? I don't see any reason why it needs lore, it's just a computer optimizing what a car is doing.

**Comment by Aivean** [comment]
> This is just used to implement hybrid cars, no? I don't see any reason why it needs lore, it's just a computer optimizing what a car is doing.

Hybrid car is one of the possible use cases, but there are benefits of using smart controller in any multi-engine cars. Maybe adding "lore" is an overkill, but I want to make people more aware of this particular feature within the game. Currently, in order to find it, player either needs to stumble upon it in vehicle construction menu (in the specific "on controls" location), or find "Hybrid car" and check it's internals.

**Comment by methanolium** [comment]
Not sure if it applies here, but AFAIK Swedish Navy has Gotland class submarines were built in the beginning of 1900. They are powered by Diesel-electric MTUs and Stirling AIP engines and are very automated. Which means they are somehow hybrid and have Smart Controller (TM). Correct me since I can easily lie. Also US nuclear submarines have aux diesel engine, I mean you probably can find an example and write something like "SAAB enters US civil market" or "US Navy production looks at civil cars", etc

**Comment by jkopesky** [comment]
Adding a flyer advertising it, as well as perhaps a survivor's note ("Damn, those hybrid cars are efficient. If only I was smart enough to finagle that smart engine controller out of it...") would help address the player visibility issues. I don't think that they would need to be developed by Hub 01 or be a rare, freshly introduced government project. Hybrid cars are fairly common today, and the technology has been around for decades.

**Comment by Aivean** [comment]
Thanks for all the suggestions! 

Here is what I have so far:

* "Smart Controller®" is not going to be tied to any specific company fictional or not
* Flyer/Poster text:
   > This is a poster advertising a brand of a hybrid gas-electric vehicle.  Poster claims that hybrid car is the "best of two worlds" with acceleration capabilities of a sport car and fuel consumption of  a compact car. Something called "Smart Controller®" is mentioned several times, which, if you are to believe the poster, is some kind of military technology adapted for civilian market and it makes the magic happen. You are not sure if this is something actually useful or just a marketing bullshit.
* Survivor  note:
   > Damn, those hybrid cars are efficient. Wish I was smart enough to finagle that engine controller out of it... Rumor is that Scrapper Joe put one in his four engine deathmobile and now doesn't care about gas at all. But then again, Joe is full of shit...
* also, smart controller UI is probably happening sooner or later

**Comment by methanolium** [comment]
> also, smart controller UI is probably happening sooner or later
Can you explain the mockup please? I think I understand the electro motor part, but I don't get the `OFF  +XX+-+  ON  (__)`

**Comment by Aivean** [comment]
> > also, smart controller UI is probably happening sooner or later
> 
> Can you explain the mockup please? I think I understand the electro motor part, but I don't get the `OFF +XX+-+ ON (__)`

In my head it looked like this (in ASCII): 
![image](https://user-images.githubusercontent.com/2865203/87183266-ab206300-c29a-11ea-8792-10ac6c27891a.png)

Seems like I need to make it more obvious.

**Comment by methanolium** [comment]
> Seems like I need to make it more obvious.

Yes, please, since if it's simple ON/OFF switch then why there are "+XX+-+" and "(__)" and why it's different from other switches in CDDA UI.
Probably I need to know the user story behind this. 
So far as I understand Smart Controller can be enabled on 1 to 5 engines. So in my head it looks like

```
+-------------------------------------+
|                                     |
|                                     |
|      Smart Controller ®             |
|                                     |
|                               Use   |
|      Medium steam engine      [ ]   |
|  >   Enhanced electric motor  [X]   |
|      2.8 diesel engine        [X]   |
|                                     |
|                                     |
|      Electric Motor Use             |
|      (% battery, arrows to change,  |
|      tab to switch between min/max) |
|         25%         65%             |
|  >   +---->=========<----+          |
|      Never           Always         |
|                                     |
|                                     |
|                                     |
|                                     |
|                                     |
|  >   User manual                    |
|                                     |
|                                     |
+-------------------------------------+
```

**Comment by methanolium** [comment]
Another view, sorry for my English
```
+-------------------------------------+
|                                     |
|         Smart Controller ®          | // Note that if more then one SC is available for vehicle then we need to List 'em
|    Use                              | 
|    [ ]  Medium steam engine         | // this should be greyed out since it's self made engine without electronic brains
|    [X]  2.8 diesel engine           | // this engine is under control, select it and hit Space to switch On/Off 
|  > [X]  Enhanced electric motor     | // ">" means that this is an option currently selected by user (up and down keys)
|                                     | // I'd add possibility here for user to be able to check engine details
|                                     | // like how much battery power or fuel here is available, but it's kinda overkill
|    Electric Motor Use               | 
|    (% battery, arrows to change,    | // user can use horisontal arrows to change min value, 
|      tab to switch between min/max) | // then Tab to switch to max value 
|         25%         65%             | // and then again horisontal arrows 
|    [---->========<------]           | // 20 positions between "[" and "]", ">" means strict more then 25%. 
|     Never         Always            | // How shall we show <=100 here? Probably replace "]" with "<"
|                                     | // Now some dreams for Future Advanced Vehicle Controller ®
|    [X] Advanced option Alpha        | // Turn off electronics if battery power is nearly not enough to start engines                               | 
|    [X] Advanced option Beta         | // Turn off headlights if zero speed after N minutes
|                                     |
|                                     | 
| ? for help, up down arrows to select| // here should be UI related legend like CDDA has almost anywhere
| an option, bla-bla-bla              |  
+-------------------------------------+
```

**Comment by Aivean** [comment]
Here is what I have so far (still WIP):
![sc-demo](https://user-images.githubusercontent.com/2865203/87265000-58030780-c476-11ea-80e9-871d90463a34.gif)

SC manual text draft:
[sc.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/4910309/sc.txt)

**Comment by Aivean** [comment]
Closing the discussion, as PR is on it's way: #42110
