### ISSUE TITLE
Crash while repairing with integrated toolset

### ISSUE THREAD

**Issue by Drew4484** [CleverRaven/Cataclysm-DDA#41961]
[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4893951/config.zip)
[Glenham.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4893953/Glenham.zip)

# Describe the bug
Crash to segfault while activating integrated toolset to repair metal. 

# Steps To Reproduce
Activate integrated toolset.
Select repair metal.
Select item to repair (reproduced by selecting damaged pair of heavy survivor gloves).

# Expected behavior

Item is repaired or requests materials to repair item.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-3894-g4929649 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context
Reproduced with chainmail armor plus other miscellaneous items. Still crashes if item not worn or if repair materials are available or not. Does not crash if using a vehicle welding rig to perform same task.

Save/debug/config attached

**Comment by UmbralReaper** [comment]
Can confirm, though I used extended toolset.
