### ISSUE TITLE
Small Towns generate a lot of monsters with wander spawns

### ISSUE THREAD

**Issue by waffel183** [CleverRaven/Cataclysm-DDA#41977]
# Describe the bug

When Wander spawns are turned on, small or medium-sized towns spawn far more monsters than can be expected from the size of the town. I've seen them cluster around each other (see pic), run in small groups to the left side (always left).

I've seen the same happen to a medium-sized town, but the problem there was that the monsters just kept coming to the side of the town I was at, I did not see any slowdown or reduction of the monsters after I cut at least 70-80 monsters down (without using explosives or guns)

My world is on day 91 if that is relevant.

# Steps To Reproduce

1. Use Wander Spawns
2. Create a new character
3. Wait a few days
4. Go to a town that is not close to the starting position
5. Marvel at the amount of hordes/monsters present

# Expected behavior

Small towns should have small monster population.
Medium-sized towns should have medium-sized monster populations, enz...

Populations should not be this clustered together, but spaced out more.

# Screenshots

Image of the horde:
![image](https://user-images.githubusercontent.com/15922303/87050027-06504800-c1fe-11ea-9c78-40ad5c54a5d5.png)

This is the entire town:
![image](https://user-images.githubusercontent.com/15922303/87050115-23851680-c1fe-11ea-88e9-541dc1a0edd8.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-3911-g312db57 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

My World save file:
[VanillaWorld.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4897380/VanillaWorld.zip)

**Comment by waffel183** [comment]
This isn't the only big horde I found in that small town, there is also at least 1 other in the northern street

**Comment by TheMasterGear** [comment]
Isn't this normal? I had a town with only two houses, and there was about just as many zombies spawning.

**Comment by Duck13Tales** [comment]
I think it quite strange... I have a small town with no active horde but still the city has way more zombies than it would have humans inhabiting it... I think it would be ok to have 4 or 5 zombies for each house but there are so many zombies roaming around that it isn't a natural.

**Comment by Profugo-Barbatus** [comment]
Zombies aren't natural. Maybe a bunch of less than competent survivors got slaughtered in the area, lots of folks running from the apocalypse all over the place. Could just be a migratory herd of Canadian zombies heading south for the winter. Lots of entirely plausible reasons for there to be an excess of zombies in any one location.
