### ISSUE TITLE
Game freezes when unwielding bucket filled with multiple food items

### ISSUE THREAD

**Issue by Qrox** [CleverRaven/Cataclysm-DDA#41978]
# Describe the bug
Game freezes when unwielding bucket filled with multiple food items

# Steps To Reproduce
1. Wield a bucket and make sure you have enough inventory space to stash the bucket
2. Examine the bucket and `i`nsert several different food items into it (or debug spawn some different food items which should be added to the bucket automatically)
3. Un`w`ield the bucket
4. Choose to spill the content
5. Game freezes

# Expected behavior
Items added to the inventory or dropped, game does not freeze.

# Versions and configuration
Current master at 312db57cf0c0dcf5a974516c987e66143c41c14a

# Additional context
There's no crash log because the game only freezes. Debugging the game suggests that the freeze happens due to infinite loop inside `item_pocket::handle_liquid_or_spill`. I suspect that calling `i_add_or_drop` adds the food items back to the bucket which invalidates the content vector of the item pocket and causes the infinite loop.

**Comment by UmbralReaper** [comment]
may be fixed by #41988.

**Comment by mqrause** [comment]
Doesn't fix it, must be a different problem.
