### ISSUE TITLE
Default mods on M24 fail to be installed when weapon spawns

### ISSUE THREAD

**Issue by esotericist** [CleverRaven/Cataclysm-DDA#41971]
# Describe the bug

starting a character with an M24 or spawning one in with wish results in an M24 lacking both its default rifle scope and bipod.

strangely, i couldn't reproduce this with any other weapons with default or built-in mods.

# Steps To Reproduce

1. open wish menu
2. search for M24
3. observe default mods showing up in wish preview
4. actually wish item into existence
5. observe lack of default mods.
6. repeat process for M110A1, observe default mods do spawn

# Expected behavior

weapon with default mods installed

# Screenshots

wish menu, showing default mods
![image](https://user-images.githubusercontent.com/1569754/87024832-77f0ad80-c18e-11ea-8076-2d4ca6056ae5.png)

resultant item, no mods
![image](https://user-images.githubusercontent.com/1569754/87024895-8c34aa80-c18e-11ea-8152-e4e13203806a.png)

# Versions and configuration

OS: Linux
OS Version: Distributor ID: Ubuntu; Description: Ubuntu 19.10; Release: 19.10; Codename: eoan;
Game Version: 0.E-3911-g312db57cf0c0d-dirty [64-bit]
Graphics Version: Tiles
Game Language: System language []
Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
Magiclysm [magiclysm]
]

# Additional context
the fact i can't seem to reproduce this with other weapons so far baffles me.
near as i can tell the primary difference is that the M24 is set up with an integral magazine (has a magazine pocket, instead of a magazine well pocket), but i can't imagine why that matters

**Comment by wapcaplet** [comment]
Still reproducible in 0.E-5926-g a883429bdd
