### ISSUE TITLE
Adrenaline lasts too long and the effect can be chained without side effects.

### ISSUE THREAD

**Issue by Broken27** [CleverRaven/Cataclysm-DDA#41972]
# Describe the bug

Adrenaline rush lasts around 20 minutes-this is an INMENSE amount of time in combat. Most combats last less than two minutes - A very long encounter may last ten. Twenty minutes is more than enough time to murder a zombie horde in melee, and adrenaline will make you immune to be winded all along.

I suspect this is a side effect of the turn-duration change - Before that change, 20 minutes was only 200 turns, and the duration was much more adequate to combat time-frames.

On top of this, the adrenaline comedown effect can be nullified with another adrenaline shot, giving another twenty minutes of effectively infinite stamina with no side effects at all.

(There is a "Your heart spams" message, but it doesn't seem to do anything at all. I tested it taking twenty shots of adrenaline in a row).

# Steps To Reproduce

Wish for an stack of adrenaline shots, take one, wait 20 minutes for the comedown, take another, wait 20 minutes, etc. It can be repeated forever.

# Expected behavior

Adrenaline should be a powerful-ish but short lived buff that gives some time to end the encounter before the side effects kick in, not a source of effectively infinite stamina. Reduce the duration to 2-3 minutes - Optionally buffing it a bit. It should get a perception bonus at least.

It certainly shouldn't be chainable without side effects.

# Screenshots

![](https://i.ibb.co/tzNcxrk/Screenshot-09-07-2020-14-48-40.jpg)

# Versions and configuration

Tested in cataclysmdda-0.E-Windows_x64-Tiles-b10795, no mods.

# Additional context

Nothing.

**Comment by chronicpayne** [comment]
Another person pointed this out, so correct me if I'm wrong, but doesn't it lower health by 20?
```
    if( p->has_effect( effect_adrenaline ) ) {
        p->add_msg_if_player( m_bad, _( "Your heart spasms!" ) );
        // Note: not the mod, the health
        p->mod_healthy( -20 );
```
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/iuse.cpp#L5983

**Comment by Broken27** [comment]
The health penalty is a very mild downside for such a powerful effect. Taking one shot of adrenaline after another should eventually kill you, or cripple you at least.

As it is now, as long as you have enough shots, you can keep going forever without being winded, which is ridiculous.

Still, fair enough - I didn't catch the health penalty effect when testing this.

**Comment by Broken27** [comment]
Solved by ![42414](https://github.com/CleverRaven/Cataclysm-DDA/pull/42414)
