### ISSUE TITLE
Followers can craft all items.

### ISSUE THREAD

**Issue by RafeHaab** [CleverRaven/Cataclysm-DDA#41981]
# Is your feature request related to a problem? Please describe.
As it is now, follower npc are a waste of food... or its source, but they are practically useless as companions.

It would be good if they were able to craft every item available.

# Describe the solution you'd like
Dialog to ask companion to craft an item is added.

Requests are either accepted or rejected based on needs levels.

Components must be provided/be nearby, and are destroyed; a countdown begins until the item is done, at which point it shows up in the npc's pockets or on the floor under it if it's too big.

Dialog happens to let the player know the item is ready.

# Describe alternatives you've considered

The npc actually crafting the item just like the player would do, but that would be harder to add. My method of destroying the components and creating the resulting item from nothing is easier.

**Comment by CoroNaut** [comment]
It would also be nice to be able to hand an npc an in-progress craft to continue or finish.
