### ISSUE TITLE
Armour Sort and Inventory QOL Update

### ISSUE THREAD

**Issue by VaneFox** [CleverRaven/Cataclysm-DDA#41983]
# Is your feature request related to a problem? Please describe.
Equipped gear management is somewhat cumbersome and disorganised. Gear is already marked as yellow if it conflicts on your body, but unless you keep track of everything you tend to forget what layers are occupied in cases.

# Describe the solution you'd like
A basic QOL feature that I always think about when managing equipment. I made some mock-up solutions in Photoshop.

I compacted the armour sorting menu for ease of use. I suppose with a significant amount more gear equipped it could fill the screen, I have no issue whatsoever with a scroll though.

![CDDAarmourMockup](https://user-images.githubusercontent.com/67852696/87091473-11968880-c27d-11ea-8009-da90bf5fdfd1.jpg)

I swapped the (Innermost) and (Outermost) keys at the top and bottom since "outermost" being the "upper" layer makes more sense to me at a glance. However I didn't change the order of the armour in the mock-up but generally they would now be on opposite sides, eg. Headlamp above fedora. Sunglasses above eyeglasses.

Armour layer is listed. Total storage is listed (in my case, litres and kg) along with the current storage levels. The selected piece of equipment retains the yellow arrows, however if it is equipped across multiple categories (right and left leg) then the part you don't have selected will be marked with blue arrows to make it easy to differentiate where you are.

I listed every other storage as 00.00 to save time but the first two give the idea.

![CDDAInvMockup](https://user-images.githubusercontent.com/67852696/87092253-756d8100-c27e-11ea-91e7-279615fa1932.jpg)

As for the equipped inventory screen, something I would really really love is the same equip view that's in the armour sorting screen.

**Comment by matt32106** [comment]
Suggestion for a more comprehensive display:

- encumbrance & warmth can be attached to the body part
- properties & protection can be displayed alongside the item
- things that you want to display for the selected item can go to the bottom of the screen
- the layer column can be reduced by using a 1-letter code if needed
- the storage column can be optimized too

![cdda](https://user-images.githubusercontent.com/7557986/87229695-a4811100-c3aa-11ea-8389-d10fd8a0e6b4.png)

As the columns titles would need to be shortened, a help screen would probably be needed.

**Comment by Zireael07** [comment]
nitpick: 1-letter code for layers would make it difficult to translate. Otherwise, yes, good feedback.

**Comment by matt32106** [comment]
It could be 0 1 2 3 4 also?! (feels appropriate for layers)

**Comment by matt32106** [comment]
Check the Wear item window also, it displays more or less what I suggested above for the right part of the screen:
![cdda](https://user-images.githubusercontent.com/7557986/87234406-c8574d80-c3d0-11ea-9c61-0a5d8a4beaab.png)

**Comment by VaneFox** [comment]
Those are great ideas. I'll have to make another mock-up. I'd absolutely love to consolidate all the equipment info if possible but as it is, the wear screen is pretty huge as it is. I'll wrack my brain and see what I can do with it. If you have any ideas for simplifying the storage too, please let me know.

**Comment by matt32106** [comment]
Also now that we have nested inv, I think that it would be super nice to have a key that displays the content of the highlighted item. For instance like when you click + in groups in excel:

Normal display
```
>>>Striped pants with 2 items
   Leather chaps
```
Display after you click the show content key:
```
>>>Striped pants with 2 items
   ...Bandages (4)
   ...Pocket knife
   Leather chaps
```

Later, it would then be easy to add another key to move the contained objects from one container to another.
