### ISSUE TITLE
Bridge Savegame Migration Generates New Bridgeheads Every Load

### ISSUE THREAD

**Issue by KamikazieBoater** [CleverRaven/Cataclysm-DDA#41987]
# Describe the bug

Loading a save in a world generated after the addition of z+1 bridges (#41135) results in new bridgeheads being generated between the existing ones.

# Steps To Reproduce

1. Create a new world in the latest build (post-merge of #41914)
2. Start with a new character, reveal the map, save and quit to menu.
3. Reload the game. Any sufficiently long bridges previously visible will now have 2 bridgeheads instead of the original 1.
4. Note that every save+reload will generate a new set of bridgeheads between the existing ones as long as there is space to do so.

# Expected behavior

Bridges that already have bridgeheads should not have new ones added.

# Screenshots

New world load:
![image](https://user-images.githubusercontent.com/3307459/87096704-3dbbf600-c1f8-11ea-8ee9-cdc4466270c5.png)

After saving+loading:
![image](https://user-images.githubusercontent.com/3307459/87096730-4f050280-c1f8-11ea-84ae-07ef8e779596.png)

Double bridgehead in person:
![image](https://user-images.githubusercontent.com/3307459/87096751-5cba8800-c1f8-11ea-98af-d73ddebbd445.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-3911-g312db57 [64-bit]
- Graphics Version: Tiles
- Game Language: English
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional Notes

Testing with the proposed fix appears to work for bridges of at least 2 tiles, including those immediately adjacent to other bridges, as saving and reloading does not generate extra bridgeheads.

overmap.cpp, lines 1818-1824:
`        const bool is_bridge_north = is_ot_match( "bridge", oter_ground_north, ot_match_type::type ) || is_ot_match( "bridgehead_ground", oter_ground_north, ot_match_type::type );`
`        const bool is_bridge_south = is_ot_match( "bridge", oter_ground_south, ot_match_type::type ) || is_ot_match( "bridgehead_ground", oter_ground_south, ot_match_type::type );`
`        const bool is_bridge_east = is_ot_match( "bridge", oter_ground_east, ot_match_type::type ) || is_ot_match( "bridgehead_ground", oter_ground_east, ot_match_type::type );`
`        const bool is_bridge_west = is_ot_match( "bridge", oter_ground_west, ot_match_type::type ) || is_ot_match( "bridgehead_ground", oter_ground_west, ot_match_type::type );`
`        const int adj_bridge_count = ((is_bridge_north) ? 1 : 0) + ((is_bridge_south) ? 1 : 0) + ((is_bridge_east) ? 1 : 0) + ((is_bridge_west) ? 1 : 0);`

`        if( adj_bridge_count == 1 ) {`

- 1-tile bridges will need a separate fix, as no terrain types exist that would be appropriate. Potential fixes would either be ground-level bridges for single-tile, or 2 new terrains (e.g. bridge_mini_ground and bridge_mini_ramp) and the associated code changes to incorporate them

**Comment by RafeHaab** [comment]
That's not all, one-tile bridges (as in, no bridge, just one bridgehead) don't generate the bridgehead properly.

**Comment by KamikazieBoater** [comment]
Looking into the terrain generation code, the generation of additional bridgeheads could probably be resolved with the following changes in overmap.cpp:

![image](https://user-images.githubusercontent.com/3307459/87163106-b3b57100-c27b-11ea-9c01-7d714945b5de.png)

With these changes, existing bridgeheads would exclude the addition of new ones facing the same direction in the adjacent tile, and it should allow 2-tile bridges to still generate correctly in world save conversion.

As for the issue with single-tile bridges, that would likely require a new terrain type (bridge_mini or something to that effect) with both up and down ramps on the same tile.

Since I'm not too comfortable jumping straight into making changes to core C++ files in the main project, and since @mlangsdorf was involved in the z+1 bridge conversion, if you could sanity check these changes and implement (or correct and implement if there are issues), it should close this issue for bridges longer than 1 tile.

**Comment by EvgenijM86** [comment]
I've been screwing around with new bridges and fell into water on my bicycle. To my surprise I could drive in deep water just fine. I then re-entered the water from the shore to see if this was specific to new bridges, but it turns out that no:

![image](https://user-images.githubusercontent.com/430076/87177956-fef77000-c2cb-11ea-9182-e3b7b2f8918b.png)

**Comment by KamikazieBoater** [comment]
Further testing showed strange behaviour with adjacent bridges, which has lead me to the following fix. Since we only want to add bridgeheads when the reference tile is a bridge and there is exactly one adjacent bridge tile (ignoring single-tile bridges, we can do the following:

`overmap.cpp`
![image](https://user-images.githubusercontent.com/3307459/87181372-110aeb80-c297-11ea-83f9-fc5fdffcda71.png)

This should resolve the issue in all but the single-tile bridge case, which will need either 2 new terrains (e.g. bridge_mini_ground and bridge_mini_ramp) and updates to the associated map generation code, or will remain ground-level.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/bridges-are-a-bit-broken/24198/2
