### ISSUE TITLE
Loading error related to size of item pocket (molded pot)

### ISSUE THREAD

**Issue by MarceloLaser** [CleverRaven/Cataclysm-DDA#41991]
# Describe the bug

>  DEBUG    : warnings for type molded_pot:
> is bigger on the inside.  consider using TARDIS flag.
> 
> 
>  FUNCTION : void Item_factory::check_definitions() const
>  FILE     : src/item_factory.cpp
>  LINE     : 1387

Not sure what a TARDIS flag is, or what molded_pot is from, but I've been getting this for several versions now. I assume it is caused by a mod, but since I don't know which mod, and I know most mod creators are also contributors here, I'm putting it down here.

# Steps To Reproduce

Just load the game by selecting "Custom Character", while in a world containing the mods listed below.

# Versions and configuration

10820, but been having it since at least a week ago.

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-3911-g312db57 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Cataclysm++ [Cata++],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food]
]

**Comment by anothersimulacrum** [comment]
This is an issue with the Cataclysm++ mod, which is third party. It looks like they have a fix underway.
