### ISSUE TITLE
The mods which added to items can [change or add] more properties as the effect of installing them

### ISSUE THREAD

**Issue by MikuMiddo** [CleverRaven/Cataclysm-DDA#42007]
# Is your feature request related to a problem? Please describe.
This feature request is an extend of #42006 
The mods that add to items such as the melee weapon can have special effection.

# Describe the solution you'd like
Such as you can add the [electric tape] to your melee weapon,the melee weapon should become non-conductive.
Also add titanium grip to items can make the item have the flag "STURDY",make it harder to break.
The mods added can also effect the bash,cut,ect. these basic properties of items.
Add new use-action,for example,add a capacitor to weapon can make this weapon has the use-action "electroshock"

# Describe alternatives you've considered
It's quite similar to the mods of guns,but can be more modifier.
Instead of using crafting system,this could be a better way to let player make their unique doomsday companion.MORE REALISTIC due to you can make yourself own one,not the one written on the book.

# Additional context
**Axe +4** ["electric tape","titanium grip","sharpen blade","capacitor"]
![image](https://user-images.githubusercontent.com/53809752/87163541-19e0d900-c2fa-11ea-90da-f77e47e0883e.png)

**Comment by anothersimulacrum** [comment]
With regard to melee weapon mods, that is covered in the [Frequently Made Suggestions](https://github.com/CleverRaven/Cataclysm-DDA/wiki/Frequently-Made-Suggestions#player-abilities) document.

**Comment by ZhilkinSerg** [comment]
You can already implement enhanced weapons using recipes.

**Comment by MikuMiddo** [comment]
> You can already implement enhanced weapons using recipes.

Can there be more modifier such as 
```json"color_modifier": "light_gray","name_modifier": { "str": "Titanium Fire axe" },```
that mods can influence the items properties?

**Comment by ZhilkinSerg** [comment]
Sure - your resulting item can have a different name, color and any other properties. It is basically a new item type with its own definition (that can be copied from original item and inherit most of its properties only changing a few).

**Comment by kevingranade** [comment]
You can also look into enchantments as implemented for Magiclysm for this kind of thing, but we are unlikely to implement a system similar to gunmod for melee weapons.
