### ISSUE TITLE
Constructed Skylights Not Letting in Sunlight

### ISSUE THREAD

**Issue by Ktmi** [CleverRaven/Cataclysm-DDA#42008]
# Describe the bug

Constructed skylights do not allow any sunlight into the tiles below them.

# Steps To Reproduce

1. Get on the roof of a house or other building.
2. Build a skylight frame over one of the rooms.
3. Build a skylight on the skylight frame.
4. Block out all other light sources to room with skylight built over it.
5. See that skylight is not letting in any light at all.

# Expected behavior

Skylight should let in sunlight. The general idea behind adding one is to be able to let in sunlight,
without exposing player to line of sight with windows.

# Screenshots

Built Skylight:

![Built Skylight](https://user-images.githubusercontent.com/46541367/87169543-27687580-c29e-11ea-894d-6ab108f459ca.png)

Unlit room with Skylight:

![Unlit room with Skylight](https://user-images.githubusercontent.com/46541367/87169708-60084f00-c29e-11ea-941c-081408689ecb.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-3923-g7063a53 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by AMurkin** [comment]
Is it remains the same after saving and loading the world?

**Comment by Ktmi** [comment]
Reloading the world results in the same problem.

**Comment by chronicpayne** [comment]
Can confirm this lack of sunlight when installing skylights, even after reloading the game.

Also (and perhaps out of scope with this report) a player can fall/move through a skylight and the glass pane its made out of does not break.
