### ISSUE TITLE
Should Jsonize the mod_locations

### ISSUE THREAD

**Issue by MikuMiddo** [CleverRaven/Cataclysm-DDA#42006]
# Is your feature request related to a problem? Please describe.
As I have been playing the game for long time,I notice melee weapons never have the mods,so I want make a mod for my melee weapon,but I found out that I can't make a new mod_locations by json.

# Describe the solution you'd like
The modder can add their own mod_location by json.
I don't want to use the given ones,because It would be weird if a melee weapon had a scope position on it,won't it?

# Describe alternatives you've considered
The modder can add the mod_locations as they add the "flag" in json.
The mod should also can add "flag" to weapon,such as you can use "electric tape" 

# Additional context
**The handaxe +1**
![image](https://user-images.githubusercontent.com/53809752/87154080-26aa0080-c2eb-11ea-99b4-b991e2b434a2.png)

Here are the example of json code.
```JSON
[
  {
    "id": "Axe_Grip",
    "type": "json_mod_locations",
    "context": [ "GENERIC", "TOOL" ]
  },
  {
    "id": "fire_axe",
    "type": "TOOL",
    "name": { "str": "fire axe" },
    "description": "This is a large, two-handed pickhead axe normally used by firefighters.  It makes a powerful melee weapon, but is a bit slow to recover between swings.",
    "weight": "2520 g",
    "volume": "2 L",
    "price": 20000,
    "longest_side": "90 cm",
    "price_postapoc": 1500,
    "bashing": 17,
    "cutting": 34,
    "material": [ "steel", "wood" ],
    "symbol": "/",
    "color": "light_gray",
    "techniques": [ "WBLOCK_1", "BRUTAL", "SWEEP" ],
    "qualities": [ [ "AXE", 2 ], [ "PRY", 3 ], [ "BUTCHER", -30 ] ],
    "flags": [ "DURABLE_MELEE", "NONCONDUCTIVE", "BELT_CLIP", "SHEATH_AXE" ],
    "use_action": [ "CROWBAR" ],
    "valid_mod_locations": [
      [ "Axe_Grip", 1 ]
    ],
	"default_mods": [ 
	  "wood_grip"
	]
  },
  {
    "id": "Titanium_Grip",
    "type": "MOD",
    "name": "Titanium Grip",
    "description": "A Titanium Grip",
    "weight": 500,
    "volume": 2,
    "price": 300000,
    "material": [ "Titanium" ],
    "symbol": ":",
    "color": "light_gray",
    "location": "Axe_Grip",
    "mod_targets": [ "WEAPONS", "TOOL" ],
    "bashing_modifier": 5,
    "cutting_modifier": 5,
    "min_skills": [ [ "melee", 2 ] ]
  }
]
```

**Comment by howmokas** [comment]
Add a super alloy  to my explosion-proof shield. I think it is necessary
