### ISSUE TITLE
Chainmail Crafting Time Inconsistency

### ISSUE THREAD

**Issue by Ichthysdekilt** [CleverRaven/Cataclysm-DDA#42019]
# Describe the bug
Perhaps more of an audit request than a true bug, but when I was putting together my faraday suit today I noticed an outlier.  See if anything stands out below:

(Note: all of these values may be influenced by my char's INT score)

- Chainmail Chausses - 20 min crafting time
- Chainmail Gloves - 20 min crafting time
- Chainmail Coif - 20 min crafting time
- Chainmail Leggings - 40 min crafting time
- Chainmail Vest - 1 hr 40 min crafting time
- Chainmail Sleeves - **14 hrs** crafting time

# Steps To Reproduce
Get yourself a copy of the DIY Compendium and check the recipes.

# Expected behavior
They honestly all probably need a little tweaking.  14 hours is perhaps a bit too long, but 20 min for a pair of gloves is likely too short.  Just to have a suggestion out there for a starting point, here are some comparable values for the same skill level:

(Note: all of these values may also be influenced by my char's INT score)

- Chainmail Chausses -> Survivor Wetsuit Boots - 2 hrs crafting time
- Chainmail Gloves -> Survivor Wetsuit Gloves - 1 hr crafting time (hard to find a similar one here, maybe 2-3 hrs?)
- Chainmail Coif -> Galea - 7 hrs 12 min crafting time
- Chainmail Leggings -> Steel Leg Guards - 3 hrs 10 min crafting time
- Chainmail Vest -> Lorica Segmentata - 7 hrs 28 min crafting time
- Chainmail Sleeves -> Steel Arm Guards - 15 hrs crafting time (this also seems a bit high, so maybe more like 7-8 hrs?)

# Screenshots

# Versions and configuration

 - Game Version: 10823

# Additional context

**Comment by anothersimulacrum** [comment]
The chainmail sleeves has been audited as part of the tailoring overhaul the other ones have not. They should follow in it's footsteps.
