### ISSUE TITLE
The learning martial arts feature of the CQB bionic is broken for some styles.

### ISSUE THREAD

**Issue by Broken27** [CleverRaven/Cataclysm-DDA#42029]
# Describe the bug

The CQB bionic can be used to permanently martial arts - You get a chance of learning the art you are using each time you hit an enemy with it active, depending on int.

This works for all the CQB martial arts except Aikido, Tai chi and Zui quan.

# Steps To Reproduce

Start a new game, install the CQB bionic and some power in yourself.

Rise your intelligence to 100. Debug spawn a turret to use as a training dummy.

Activate the bionic, hit an enemy with a martial art active. You will learn the art after a few hits - Except for Aikido/Tai chi/Zui Quan. You won't learn those no matter how much time you pass hitting the turret.

# Expected behavior

The CQB bionic learning feature should work the same way for all the martial arts it gives.

# Versions and configuration
Tested in cataclysmdda-0.E-Windows_x64-Tiles-b10823, no mods

# Additional context

None.

**Comment by Broken27** [comment]
@Hymore246 this may interest you.

**Comment by Hymore246** [comment]
Testing it now. I was able to reproduce the bug but I was able to learn Tai Chi by pausing first. Why? Doing that lets you execute the style's TECHNIQUES. Aikido and Zui Quan do not have direct attack techniques and that seems to be the carrier for learning the style. You can learn both styles via the block and dodge counters.

I am going to look into moving the code to learn the style somewhere else. While I consider this to be ok behavior, if a style that comes a long with no techniques at all, it will be impossible to learn the style from the bionic.

**Comment by Broken27** [comment]
@Hymore246 

Oh, ok then. If you can learn it via counters that is fine.

Anyway, if you are changing the code, i would suggest to make the message when you learn an art more visible. Right now it only gives a very easy to miss message in the log - A pop up informing you would be nice.

**Comment by Hymore246** [comment]
That falls outside of the scope of the bug fix. A similar problem could be said about increasing skill levels. I am not sure if a constant barrage of popups would be a good idea but I'll leave that for someone else to figure out.
