### ISSUE TITLE
Non-sealable containers should not spill non-liquid content when put into vehicle storage space

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#42032]
# Is your feature request related to a problem? Please describe.
So, let's say we have canning pot. Or orichalcum cauldron from Magiclysm. Those are big pots, 15 or 20 liters. Obviously, they are non-sealable. It makes sense. What does NOT make sense is I cannot put some boxes, bandages, bottles or w/e inside them and then put them into vehicle cargo without all the crap from them spilling out. Like, what, my char doesn't have enough brain cells to not put it into vehicle upside down (or something)?

# Describe the solution you'd like
They should not spill the crap out when put into vehicle cargo. Liquid, sure. Non-liquid, please leave it where it was. It is already working if the pot/cauldron is wielded (you can fill it to the brim with loot and it won't spill out) so it can be done.

# Describe alternatives you've considered
Continue wasting considerable amount of storage space when it should not work like this.

**Comment by kevingranade** [comment]
Just to be clear, in the scenario your outlining those liquids should spill as soon as the vehicle starts moving but you want it to refrain from spilling until the vehicle is in motion. That would be fine but I think you can see that this is a self-defeating proposition because it simply adds more complexity in order to achieve the same status quo.

**Comment by GGgatherer** [comment]
Nonono, I was not speaking about them spilling liquids, that's totally fine, and them doing so on putting them into vehicle cargo is ok. What I am talking about is them spilling *non*-liquid contents. Which, frankly, doesn't make any sense even if the vehicle is moving.
