### ISSUE TITLE
Blood loss has no effect on blood cells or vitamins until after saving and loading the game

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#42039]
# Describe the bug

When one or more body parts are bleeding, and after I see several "You lose some blood" messages, my character needs (from debug menu) shows that I have not lost any blood cells or vitamins.

# Steps To Reproduce

Starting with a new game in a new world (not loaded from a saved game):

1. Check debug menu, `p`layer, edit `p`layer/NPC, view `n`eeds - see blood and vitamins are at 0
2. Use the debug menu, `p`layer, `b`leed self
3. Apply 1000 bleeding to one or more body parts
4. Wait 30 minutes
5. Check debug menu, `p`layer, edit `p`layer/NPC, view `n`eeds - blood and vitamins still at 0

# Expected behavior

Expected "You lose some blood" messages to be associated with a decrease in the amount of blood and vitamins shown in the needs screen.

# Screenshots

Bleeding from all limbs:

![image](https://user-images.githubusercontent.com/238395/87231671-55b98400-c376-11ea-9296-11cee43c27d5.png)

Needs displayed after 1 hour of level-1000 bleeding from all limbs:

![image](https://user-images.githubusercontent.com/238395/87231682-62d67300-c376-11ea-97d8-6337bd121dac.png)

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-3959-gc876885a3a-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

I see the lack of bleeding effects manifest in a *new* game, but not when loading an existing saved game.

**Comment by wapcaplet** [comment]
I see now that by passing time with `|` waiting, messages like "You attempt to put pressure on the bleeding wound" are displayed. These messages outnumber the "You lose some blood" messages, and apparently are enough to completely prevent blood loss:

![image](https://user-images.githubusercontent.com/238395/87231813-80580c80-c377-11ea-996f-5a7d0b7ececd.png)

However, by walking around instead of simply `|` waiting for time to pass, the "You attempt to put pressure" messages are not displayed, and blood loss does occur (leaving splotches of blood on the ground):

![image](https://user-images.githubusercontent.com/238395/87231792-5acb0300-c377-11ea-8a74-ef826b8af7e0.png)

**Comment by wapcaplet** [comment]
I see similar behavior when experiencing blood loss after being bitten by a slavering biter:

![image](https://user-images.githubusercontent.com/238395/87232069-70412c80-c379-11ea-8acc-6f453f279b25.png)

Save game, after being bitten, bleeding, and walking around: [Bite-bleeding.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4907502/Bite-bleeding.zip)

**Comment by wapcaplet** [comment]
On further testing, I see that `n`eeds panel blood/vitamin loss only begins *after* I save and load my game.

Following the below steps, all the relevant `n`eeds indicators remain at 0:

1. Start a new game in a new world, character with 0 skill and no traits
2. Use the debug menu to `b`leed self at a high level (to induce "Heavy Arterial Bleeding")
3. Walk around and see blood spilt everywhere
4. Check `n`eeds - no blood or vitamin loss

**Comment by I-am-Erk** [comment]
@nexusmrsep tagging for attention

If the problem here is related to effectiveness of pressure, we may want to consider refining how we apply pressure to wounds while fixing it 

- probably only able to apply pressure to your worst injury
- may want to make the pressure application more effective the higher your first aid skill
- may want to make it based not on waiting, but on Activity Level.

**Comment by nexusmrsep** [comment]
It's was pinpointed by @anothersimulacrum to be an old bug with vitamin_levels not being initialized unless loaded from a save file, and we're expecting a quick fix for that.

**Comment by nexusmrsep** [comment]
@I-am-Erk 
It already applies it to only one, worst bleeding wound, and utilizes first aid skill for that. Not sure what you mean by activity level, but you might take a look how it's implemented here: https://github.com/CleverRaven/Cataclysm-DDA/blob/237b16ed2078e562d6ddad1fdaa1bf5b033a89d2/src/player.cpp#L813

**Comment by I-am-Erk** [comment]
If it's not pressure related no worries, the current code is plenty fine. The activity level thing I was thinking would be related to if you were putting on pressure while doing things other than holding still, but it's a granularity we don't need at the moment
