### ISSUE TITLE
Allow wielding & using 2 one-handed objects at the same time

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#42034]
# Is your feature request related to a problem? Please describe.
My PC wields a cudgel (60 cm long so I assume it is one handed). If I try to take a flashlamp I cannot wield it in my off-hand, I have to drop the cudgel.

![cdda](https://user-images.githubusercontent.com/7557986/87226789-77c2fe80-c396-11ea-8b0b-21df211fe4c8.png)

# Describe the solution you'd like
Allow wielding and using 2 one-handed items simultaneously.

**Comment by meladath** [comment]
This isnt a bad idea however I imagine would open a huge can of worms, especially in regards to combat.

**Comment by matt32106** [comment]
Combat is not a priority IMO.  What is a priority is that if for instance you start naked, you should be able to wield a knife/cudgel in the right hand and a flashlight/bottle of water in the left hand. As a first step, it would be nice if the off hand would be considered as a container of sorts?! (a pouch that can hold only one item with no limit on the length of the object worn - you should be able to grab a rebar/staff and drag it around). Not sure it makes sense with the code base though, just an idea.

**Comment by matt32106** [comment]
I think this issue should be reopened, I am curious about the feasibility of what I suggested 3 comments above: https://github.com/CleverRaven/Cataclysm-DDA/issues/42034#issuecomment-659016231 @KorGgenT I think it's you who worked containers?! what do you think?

**Comment by KorGgenT** [comment]
i think you'll have to pay me a lot of money to implement this feature
