### ISSUE TITLE
Fall in pit while digging pit

### ISSUE THREAD

**Issue by rickyrich88** [CleverRaven/Cataclysm-DDA#42049]
# Describe the bug

When digging a pit from a shallow pit, you trigger the pit you dug.

# Steps To Reproduce

1. Spawn player and entrenching tool.
2. Dig pit.
3. Dig pit again.
4. Trigger the pit and hurt yourself.

# Expected behavior

You shouldn't trigger the pit since you're digging it.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-3783-g754b89e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Arcana and Magic Items [Arcana],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA],
    No Rail Stations [No_Rail_Stations],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

**Comment by Ichthysdekilt** [comment]
Can confirm this in 10832.
