### ISSUE TITLE
Add "barefoot" status to make movespeed penalty from lack of shoes more clear.

### ISSUE THREAD

**Issue by ConnorMartin** [CleverRaven/Cataclysm-DDA#42046]
# Is your feature request related to a problem? Please describe.
It's pretty easy to forget that you aren't wearing shoes and are suffering a movespeed penalty.

# Describe the solution you'd like
Add a "barefoot" status that states that the player's lack of footwear is reducing their movement speed.

# Describe alternatives you've considered
Not adding a status.

**Comment by Duck13Tales** [comment]
But why would a gel or a snake need boots?

**Comment by ConnorMartin** [comment]
My bad, I hadn't updated the title when I figured out what was wrong with my movespeed.
