### ISSUE TITLE
Second use of voodoo dolls cause crash

### ISSUE THREAD

**Issue by MutaMan** [CleverRaven/Cataclysm-DDA#42043]
# Describe the bug

Using a voodoo doll twice crashes the game. 

# Steps To Reproduce

1. Spawn or obtain voodoo doll.
2. Activate it to spawn friendly zombies.
3. See that you can activate it a second time and do so again.
4. Have your game crash on activation of the voodoo doll.

# Expected behavior

Either the doll should disappear on the first use or if it's intended for it to have multiple uses then subsequent uses should go through the spell casting process and not crash the game.

# Screenshots

No screenshots are applicable according to this:
"Do not take a screenshot of the crashing window. Please provide the crash logs in the "Additional context" -->"

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-3964-g237b16e
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: DDA, Magiclysm

# Additional context

Logs:
[crash and debug logs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4907585/crash.and.debug.logs.zip)
Save:
[Merryville.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4907588/Merryville.zip)

**Comment by wapcaplet** [comment]
Confirmed in O.E-3964-g237b16ed20
- Spawn zombie voodoo doll
- Activate voodoo doll (ok, zombie summoned)
- Activate voodoo doll again (game crash)

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4907776/debug.log)

**Comment by KorGgenT** [comment]
i seem to remember coming across something similar _possibly_, can you tell me off the top of your head if the number of charges in the stack was 0, or if it didn't show any charges? i remember something like that happening when i was testing mutagens but couldn't spare any time for it at the time i found that.

**Comment by MutaMan** [comment]
There was a (1) next to the voodoo doll on first use, on second use the (1) was gone but the item still there.
