### ISSUE TITLE
Antibiotics not working and strange behavior of infection

### ISSUE THREAD

**Issue by YourCompanionCube** [CleverRaven/Cataclysm-DDA#42041]
# Describe the bug

My survivor got bitten and i didn't have antiseptic so he got an infection. I had antibiotics and took them once it went from "deep bite" to "infected" but the infection continued to get worse despite taking them every 12 hours and then when i finally 'succumbed' to the infection i didn't die

# Steps To Reproduce

1. get a character infected
2. take antibiotics
3. wait

# Expected behavior

for antibiotics to stop infection

# Screenshots
![bug report](https://user-images.githubusercontent.com/26364270/87232758-83f78d80-c38f-11ea-9809-1ec629301600.png)

![bug report2](https://user-images.githubusercontent.com/26364270/87232783-aee1e180-c38f-11ea-8e57-8aca0391fb84.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-3964-g237b16e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Alternative Map Key [alt_map_key],
    Disable NPC Needs [no_npc_food],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    No Rail Stations [No_Rail_Stations],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    More Survivor Stuff [more_survivor_stuff]
]

# Additional context
[Save File.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4907533/Save.File.zip)

**Comment by Fris0uman** [comment]
Could be related to https://github.com/CleverRaven/Cataclysm-DDA/pull/41686
might have messed up the thing that's supposed to set ur hp to zero when you succumb

**Comment by Fris0uman** [comment]
I can't reproduce this, I did the very bad day scenario, waited until the infection got really bad and died.
But I've found that dying from the infection deals 500 dmg instead of just killing you so I can change that.
