### ISSUE TITLE
Workout for stat increase

### ISSUE THREAD

**Issue by Katanasoul91** [CleverRaven/Cataclysm-DDA#42042]
Summary: Use the implemented PR #41409 to increase your stats

# Describe the solution you'd like
Use the work out to make progress in the Strenght of the character making them progress like they were another skill.

# Describe alternatives you've considered
I could like to see if there are other kinds of "workouts" that could be implemented to increase the other stats, like meditation for intelligence, juggling for dexterity, and I`m blank for perception, but stuff to work your situation awareness could do the trick.

**Comment by Tamiore** [comment]
While I like this idea in general, it really shouldn't operate as "skills 2.0". 
There is a good game-balance reason why stats are not interchangeable with skills. 

As such, "workout"-related stats bonuses should really be limited to +1 normally, +2 at the absolute best, and they should always actively decay if not maintained via training. 
(+2 to a stat is an equivalent of super-high-tech CBM, it really don't think mere training should be able to outperform an actual dedicated CBM.)
Also, I think it would be beneficial to include an element of a choice: e. g. if you get +2 to a single stat you can't get a bonus to any other. So it's +2 to one stat, or up to +1 for all four.

**Comment by Ichthysdekilt** [comment]
An alternative to this might be that, instead of increasing your strength you increase your max stamina.

**Comment by Katanasoul91** [comment]
I want to make it as a replacement of Stats through skills because I think even if you can increase them like that it could be more organic and require an effort on it own, where skills could be useful to get them all in high level.
