### ISSUE TITLE
Plastic Fish trap says it can't be set without bait even though it has been loaded with bait.

### ISSUE THREAD

**Issue by ZaricaDemoni** [CleverRaven/Cataclysm-DDA#42051]
# Describe the bug
The plastic fish trap I have refuses to be set, telling me I dont have bait.

# Steps To Reproduce
Load plastic fish trap with bait
Attempt to set plastic fish trap
Be told fish are not dumb enough to fall for a trap without bait, despite it having bait.. fish are too smart now.

# Expected behavior
Fish trap should be set.

# Screenshots
![image](https://user-images.githubusercontent.com/32645137/87237672-30e10300-c3ae-11ea-8099-7a8d6de5d9ad.png)

# Versions and configuration

 - OS: 8.1
 - Game Version: 0.E-3964-g237b16e
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: "dda", "no_npc_food", "blazeindustries", "crt_expansion", "magiclysm", "DinoMod", alt_map_key", "MMA", "cbm_slots", "fuji_mpp", "speedydex", "stats_through_kills", "StatsThroughSkills"

# Additional context
Save with fish trap, bait, and pond with fish all ready to reproduce the issue.
[Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4907928/Save.zip)

**Comment by ZaricaDemoni** [comment]
Changed title to be more specific.

**Comment by olanti-p** [comment]
A duplicate of #41288 ?

**Comment by ZaricaDemoni** [comment]
I tried finding that and couldn't find it here. so closing as duplicate.
