### ISSUE TITLE
Looking at the sky is broken

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#42050]
# Describe the bug

Looking at the sky doesn't show anything relevant. It doesn't seem to be affected by binoculars or telescopic eyes, too. Also, when you move the view around, it leaves a trail of "@"s. Unless you move too fast, then it doesn't.

# Steps To Reproduce

Make a player who can see the sky. Look at the sky. Try moving around.

# Expected behavior

Feature working as usual.

# Screenshots

![cataclysm-tiles_2020_07_12_09_17_00_013](https://user-images.githubusercontent.com/56833396/87237541-aa660900-c421-11ea-9631-969e4b5a023e.png)

# Versions and configuration

- OS: Windows 7
- Game Version: 0.E-3964-g237b16e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by GGgatherer** [comment]
Seems to be fixed in b10864. Can be closed, I guess?

**Comment by int-ua** [comment]
Please reopen, I see it on later builds and here is a fresh complaint: https://www.reddit.com/r/cataclysmdda/comments/ia06q6/is_the_look_at_the_sky_command_currently_broken/

**Comment by int-ua** [comment]
What symbol is used for the blackness? I'm not running the game right now, but I guess that the problem is isolated to one type of weather that uses some symbol or or color that's used for something else on the overmap.

**Comment by int-ua** [comment]
@Ramza13 can you please take a look again? When I set glyph for `clear` weather all glyphs just become random symbols that change on every load. Is `[0]` used correctly here https://github.com/CleverRaven/Cataclysm-DDA/blob/2dcc333432989cfcc22e6dd494ac0f7eec9979cc/src/weather_type.cpp#L170 ?

**Comment by anothersimulacrum** [comment]
I said it on discord, but I'll say it here too:
That should use the proper unicode character reading function, instead of reading a string and cribbing a character from it, see this for an example.
https://github.com/CleverRaven/Cataclysm-DDA/blob/2dcc333432989cfcc22e6dd494ac0f7eec9979cc/src/move_mode.cpp#L49

**Comment by int-ua** [comment]
Using `unicode_codepoint_from_symbol_reader` and converting `glyph` to `uint32_t` didn't change anything unfortunately. It didn't break more but it's still has this glitch.

**Comment by ZhilkinSerg** [comment]
It works for me after getting rid of `char` in favor of `std::string` and `unit32_t`:

![image](https://user-images.githubusercontent.com/16213433/90761421-0eff6800-e2ec-11ea-91f3-54c5c91e9c79.png)
