### ISSUE TITLE
Backpacks randomly disappear

### ISSUE THREAD

**Issue by Hulkninja** [CleverRaven/Cataclysm-DDA#42059]
# Describe the bug

On several occasions, the backpack my character is currently wearing disappears entirely. It's not destroyed, as the log doesn't record it as such, and no items are dropped anywhere near where I've been fighting recently.

# Steps To Reproduce

1. Make a character and wear a backpack.
2. Fill the backpack to the brim with good loot.
3. Have fun, enjoy the game, go for a drive, fight zombies
4. Eventually realize your backpack has vanished
5. Panic, because that backpack contained all your best loot
6. Check the log, and backtrack everywhere you've been meticulously
7. Angry cry

# Expected behavior

That I would either keep my backpack on, be notified that I've dropped it, be notified that it's been destroyed, or at the very least be able to find it somewhere I've previously beeen.

# Screenshots

Don't know what I could screencap that would help in this scenario. I don't notice the problem until it's already happened.

# Versions and configuration

- OS: Windows 10
    - OS Version: 10.0 1909
- Game Version: 0.E-3964-g237b16e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Graphical Overmap [Graphical_Overmap]
]

# Additional context

I can provide two save files, one with a backpack and one without. I think the backpack in question is a military backpack, although I did also lose a MOLLE pack earlier with the same character. Both of them were filled with items at the time of disappearance, possibly to the point where my character had passed his carry-weight limit, and I suspect I had been driving my electric SUV (marked as remembered in both saves) around the time the backpacks vanished.

Save upon realizing the military backpack was gone:
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4908517/save.zip)

Save from yesterday, precaution taken after failing to locate my MOLLE pack after hours IRL of searching:
[auto_before_launch2.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4908518/auto_before_launch2.zip)

**Comment by KorGgenT** [comment]
This could really use reproduction steps, because as of now it is basically impossible for someone doing testing rather than playing to determine if this bug is fixed.

**Comment by Hulkninja** [comment]
> This could really use reproduction steps, because as of now it is basically impossible for someone doing testing rather than playing to determine if this bug is fixed.

I'm not really sure what steps I took, exactly. I apologize. I was just playing, enjoying the game, and suddenly realized that my backpack was gone. I remember having it equipped during the previous encounter, fighting zombies. Then I got into my car, drove to a remote cabin, and when I checked my inventory, I noticed some items were missing. So I checked my list of worn clothing/armor, and the backpack was gone.

I also lost my pants, at least once, maybe twice, in sort of the same manner. I can't recall if I had been driving recently before noticing the lost gear on all occasions, but it's certainly possible. Although, most times I'd go for a drive, everything went smoothly. The pants had pockets, so I guess the bug is related to storage somehow.

What should I look for to provide accurate reproduction steps? I'm willing to go back into the game and try to trigger it a third time.

**Comment by Hulkninja** [comment]
I'm closing this issue. I think it's resolved, assuming the fix made by @Trioct has been merged into the latest experimental build, which I think it has, but it's not mentioned in the changelog for the windows build, only the android one.

I've started a new game where I avoid pets entirely, and so far the issue has been totally absent. 99% sure it's the tie/untie thing that caused it.
