### ISSUE TITLE
Sawn-off shotguns don't lose length

### ISSUE THREAD

**Issue by souricelle** [CleverRaven/Cataclysm-DDA#42079]
You can use a hacksaw to cut down the barrel of a shotgun. Ostensibly this is to reduce its length, however all that changes is a minor reduction in volume and increased noise and dispersion.

# Steps To Reproduce

1. Spawn two shotguns and a hacksaw (I used a Remington 870 Express for this)
2. Activate the hacksaw to cut down the barrel of one shotgun and then compare the two.
3. The sawn-off shotgun loses .02L and .04 lbs, but remains 38 inches long

# Expected behavior

Sawing off the barrel seems like it should reduce the overall length of the weapon by several inches. This looks like a simple oversight.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-3974-g078a56c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Ichthysdekilt** [comment]
Cutting 4-6" of barrel off should probably reduce weight and volume by more than that, too.  Imagine the difference between this and a version where the barrel ends at the same length as the fore-end.

**Comment by cosmo-naut** [comment]
This should also apply to folding stocks

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/sawn-off-shotgun-length-was-not-reduced-after-sawing-barrels/25481/2
