### ISSUE TITLE
Battery UPS bug

### ISSUE THREAD

**Issue by dan83m** [CleverRaven/Cataclysm-DDA#42081]
DEBUG    : Item battery_ups was loaded with charges, but can not have any!

 FUNCTION : void item::io(Archive&) [with Archive = io::JsonObjectInputArchive]
 FILE     : src/savegame_json.cpp
 LINE     : 2363

windows 10 
Version game stable E.2

![image](https://user-images.githubusercontent.com/26160782/87260935-86073c80-c4b4-11ea-9dc0-cce026d3d79e.png)

**Comment by dan83m** [comment]
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4910038/debug.log)

**Comment by Duck13Tales** [comment]
I think that this should be fixed by #41917

**Comment by int-ua** [comment]
Please use the issue template next time.
