### ISSUE TITLE
Vehicles not functioning 10826

### ISSUE THREAD

**Issue by VaneFox** [CleverRaven/Cataclysm-DDA#42087]
# Describe the bug

This appears to be quite an old bug going back as far as 2013.
https://discourse.cataclysmdda.org/t/map-board-vehicle-passenger-null-is-already-there/2908/4

https://discourse.cataclysmdda.org/t/re-map-board-vehicle-passenger-null-is-already-there/9235

All the details are essentially in there, but basically, you can start your engine and do everything normally, but the game doesn't allow you to control the car in any way, you just walk off the seat, it treats every seat with control like a passenger seat. 2 recurring errors in every car I try to use are-

src/map.cpp:1009 [void map::board_vehicle(const tripoint&, Character*)] map::board_vehicle: passenger (Claire) is already there

src/map.cpp:1031 [void map::unboard_vehicle(const vpart_reference&, Character*, bool)] map::unboard_vehicle: passenger not found

This all started to occur the next day after loading save, no update applied.
The first occurs when I attempt to enter a driver seat, the second when I move within 5 or so spaces within the radius of a car.
Assigning the passenger seat to my follower now also crashes the game.

--
Following the steps of the link doesn't appear to work as it would appear the vehicle display in the map file has changed from what they seem to have. I couldn't find the numbered lines as were described. As for the second link, I am using a fully electric car if that makes any difference.

# Steps To Reproduce

Unfortunately I am unsure what caused it. I saved outside of the vehicle. with nobody in it. This bug persists now with any vehicle I try to use.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-3941-g6695d25 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Fuji's Military Profession Pack [fuji_mpp],
    Bionic Slots [cbm_slots],
    Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
    More City Locations [cityside],
    C.R.I.T Expansion Mod [crt_expansion],
    Blaze Industries [blazeindustries],
    Nechronica Redux [Nechronica_Redux],
    <color_light_red>Secronom</color> [secronom],
    Whaleys Collectables [collectablemod],
    Graphical Overmap [Graphical_Overmap],
    Stats Through Skills [StatsThroughSkills],
    Mutation Changes [Mutation_Changes],
    SpeedyDex [speedydex]
]

# Additional info

This is the file for my vehicle. I doubt there is anything in there that will help however, since this is a persistent error across all forms of vehicles.

https://freetexthost.net/VLfUWhD

EDIT: Added crash log for assigning passenger.
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4912171/crash.log)

**Comment by int-ua** [comment]
Please update title to better represent the issue.

**Comment by irwiss** [comment]
This has no save file attached to reproduce, and seems to be filed on one of 0.E experimentals, will be hard to have anything actionable
