### ISSUE TITLE
Hidden feature: handbrake

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#42086]
# Is your feature request related to a problem? Please describe.
I recently discovered a hidden feature: cars in cdda have handbrakes. Pressing [s] will activate a handbrake bringing the car to a stop rather quickly. As far as I can tell this feature is hidden - there is nothing in the UI to tell the player about it.

# Describe the solution you'd like
Change the "?" menu when @ is driving to advertise the handbrake command.

# Describe alternatives you've considered
Add handbrake to the "^" menu

# Additional context
none

**Comment by Qrox** [comment]
Handbrake is handled via `ACTION_SMASH`. Would make more sense if it is handled via a separate action.

**Comment by ZaricaDemoni** [comment]
this was very interesting to learn, and now I wished I had a seat-belt in my car, but a quick look at the wiki it is mentioned there that s is indeed a hand break. but an in-game showing of it would be nice.
