### ISSUE TITLE
Wallet

### ISSUE THREAD

**Issue by Entity-y** [CleverRaven/Cataclysm-DDA#42097]
# Is your feature request related to a problem? Please describe.
Cash cards flooding inventory screen

# Describe the solution you'd like

Wallet as a nested container to hold all cash cards, id cards, and eventually paper money
# Describe alternatives you've considered

Going back to stacking cash cards as one item
# Additional context
Maybe wallets could have infinite storage capacity for QoL instead of only realistically holding 10 cards or so.

**Comment by EvgenijM86** [comment]
If I remember correctly cash cards stacked previously and displayed as a single stack of items, displaying a total sum of money in all of them.

**Comment by Entity-y** [comment]
That used to be the case, yes. Now that we have nested containers, having a wallet to contain these just makes sense. It could be found on zombies or npcs, sometimes in dressers. Wallets may even contain pictures of family to boost morale or even a condom for whatever use you may find for that.

**Comment by EvgenijM86** [comment]
So, only the wallet should display them as stack? If you use a simple plastic bag and insert cash cards in it then they should be displayed as separate cash cards? 

If yes, should the same principle apply to other items, such as arrows? I.e. arrows only become a stack inside quiver, and displayed separate in any other non-specialized container.

If no, then wallet does nothing really, because any other container would work the same for the purpose of displaying them as stack.

**Comment by Entity-y** [comment]
I think any nested container should show it as a stack, multiple entries of cash cards at a glance would mean that they are split between different pockets. The wallet would just be a more appropriate solution for organization, everyone has one and we all choose to put bank cards there rather than stuffing in a plastic bag or thrown in the bottom of a backpack.

**Comment by Ichthysdekilt** [comment]
A wallet does still make sense from a realism perspective, even if you can achieve the same thing with a sandwich baggy.  That's exactly like real life, where you could easily walk around with either a sandwich baggy or a wallet but you have the choice of both.

**Comment by EvgenijM86** [comment]
I think in Cataclysm setting I could care less where I would store my cards, because scenarios where I would use them are pretty rare. Unlike in real life, where you purchase stuff and show your ID multiple times per day.

**Comment by Entity-y** [comment]
The idea here is to stuff them into your wallet and forget about it until you need it, not being reminded that you're carrying 43 cash cards. It makes it slightly more interesting taking a wallet off of a body and pulling a cash card or other stuff out than to just see a cash card basically in the zombies hand.

**Comment by meladath** [comment]
Yes, this is more of a "please add a new screen that removes my cash cards from my inventory". I agree though, a wallet isnt exactly a bad idea. Absolutely shouldn't have infinite storage though.
