### ISSUE TITLE
Unusual behaviour when mounting or dismounting something to a bike rack

### ISSUE THREAD

**Issue by Olaroll** [CleverRaven/Cataclysm-DDA#42092]
# Describe the bug
When mounting something onto a bike rack, it teleports to a different location on the parent vehicle.

When dismounting, the mounted vehicle seems to just disappear

The mounted vehicle returns to where it should be once you move away a couple of tiles

# Steps To Reproduce
1. Spawn a Welding Cart and Car
2. Install a bike rack somewhere on the car
3. Try to mount the Welding Cart onto the bike rack

# Expected behavior
The rack-mounted vehicle shouldn't be teleporting around.

# Screenshots
![cataclysm-tiles_rrPY4PJRsO](https://user-images.githubusercontent.com/13151772/87313242-45e2a100-c52a-11ea-98f8-0b25482a29c5.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-3978-g8c1d7fd [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [ Dark Days Ahead [dda] ]

# Additional context
For convenience, here is a save file with everything set up until installing the bike rack: [Bike rack test.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4912824/Bike.rack.test.zip)

**Comment by olanti-p** [comment]
Might be related to caching. Mounted cart, despite teleporting inside the car, shows up properly in vehicle menu
![image](https://user-images.githubusercontent.com/60584843/87461323-f037f280-c616-11ea-99d2-122eb9c86b8c.png)
Also, taking a stroll around the car makes the cart magically snap back to where it's supposed to be
