### ISSUE TITLE
Require hotwiring for cars

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#421]
Cars should have some security measures requiring hotwiring, finding the key, or similar.

Keys requires adding a key item and a matching system between keys and cars and to be reasonable a spawning method to make keys spawn near their vehicles.

Hotwiring is much easier, it would just require appropriate tools and skill checks, and possibly run the risk of breaking the vehicle controls or triggering an alarm.

**Comment by illi-kun** [comment]
It seems that now we have hotwiring. Do we need any further activity on this request?

**Comment by Coolthulhu** [comment]
Maybe put it into more cars? Due to scarcity of working and/or secured cars, it isn't used much.

**Comment by mugling** [comment]
We have `engine_fault_immobiliser` which pretty much fixes this?

**Comment by kevingranade** [comment]
I'll close this and open a new one for the key sub-issue, it's not car specific.
