### ISSUE TITLE
Can't treat feet

### ISSUE THREAD

**Issue by andrei8l** [CleverRaven/Cataclysm-DDA#42105]
Game version: 0.E-4042-gcd7577a652

Operating system: linux

Tiles or curses: tiles

Mods active: Dark Days Ahead

### Expected behavior
Wounded feet can be bandaged, disinfected, and splinted, either independently or as part of legs as in older versions

### Actual behavior
Feet can't be treated in any way. Possibly related to https://github.com/CleverRaven/Cataclysm-DDA/pull/39068

### Steps to reproduce the behavior
1. Use map editor to add a pool of acid on a tile
2. Stand in pool of acid until you get the "your limb breaks!" message
3. Try to bandage, disinfect, splint, or use the autodoc to treat your feet.
![Screenshot from 2020-07-14 01-17-11](https://user-images.githubusercontent.com/68240139/87359590-c5935e80-c570-11ea-8dae-25d04284770d.png)
![Screenshot from 2020-07-14 01-17-38](https://user-images.githubusercontent.com/68240139/87359595-c7f5b880-c570-11ea-8c98-433d79887064.png)
![Screenshot from 2020-07-14 01-17-50](https://user-images.githubusercontent.com/68240139/87359600-c9bf7c00-c570-11ea-84a1-c7a7aadf2e4d.png)
![Screenshot from 2020-07-14 01-17-59](https://user-images.githubusercontent.com/68240139/87359605-cc21d600-c570-11ea-92d2-5e02b5af13d1.png)

**Comment by MatiasFito** [comment]
Hmm but on the screenshots you have no damage to your limbs so it makes sense you cannot treat them. I think the bug is that you are getting all the pain from stepping on acid, but no actual damage to your leg limbs :thinking: .

**Comment by ZaricaDemoni** [comment]
That would make sense if it didn't say "Your limb breaks" in the message log, which means his foot is defiantly broken. this could potentially be related to #42041 because if his left foot is what was actually infected, would explain why he couldn't disinfect it.

**Comment by andrei8l** [comment]
> Hmm but on the screenshots you have no damage to your limbs so it makes sense you cannot treat them. I think the bug is that you are getting all the pain from stepping on acid, but no actual damage to your leg limbs thinking .

The feet are indeed damaged as you can see from the debug menu to set hitpoints (the entry for "all" shows 0 which means there is some hidden broken limb). They also get cold from critical damage and breaking them fails the "Structural Integrity" achievement. This also affects hands as far as I can tell, but those are harder to test.

**Comment by Hulkninja** [comment]
Now that you mention it, my character did have his mouth break from frostbite yesterday...

This seems to apply to all body parts that aren't legs, arms, torso or the head.

**Comment by Tamiore** [comment]
Can confirm, body parts are COMPLETELY out of wack in experimental. 
And as soon at these "phantom" body parts start taking damage, it just snowballs: the more damaged they get, the easier they soak up even more damage from things like frostbite. But since it does effect ACTUAL limb hit points it's VERY hard understand that's actually going on.

**Comment by andrei8l** [comment]
I think this can be fixed as a stopgap by using `mutate_to_main_part( bp )` in `Creature::deal_damage` at `creature.hpp:839`. There are a lot of places to check though...
