### ISSUE TITLE
Removing allied NPC gear causing segfault

### ISSUE THREAD

**Issue by aoae23** [CleverRaven/Cataclysm-DDA#42106]
# Describe the bug

When I try to unequip my NPC ally's sleeveless leather trenchcoat, a segfault occurs.

I managed to reproduce it with a new world on a NPC with a tool belt.

It only happens when you remove gear with storage, so I suspect it may have to do with storage/nested containers.

# Steps To Reproduce

1. Create a world/save with static NPCs enabled

2. Mutate Debug Mind Control

3. Try to strip your starter NPC 

# Expected behavior

Game does not segfault

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-3780-g54cde4b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Mythical Martial Arts [MMA],
    Vampiric Stuff [vamp_stuff],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    Alternative Map Key [alt_map_key]
]

# Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4915755/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4915756/crash.log)
[Siasconset - Copy.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4915771/Siasconset.-.Copy.zip)

This was for my NPC's own good. I wanted to swap out their gear for a nice set of chitin armour

**Comment by hexagonrecursion** [comment]
I could not reproduce the crash with clang address and undefined behavior sanitizers. I tried removing the sleeveless leather trenchcoat both via the "sort armor" menu and via the trading interface. Note: I do not have the vamp_stuff mod

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 0.F-2004-gada3852d39 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Mythical Martial Arts [MMA],
    No name () [],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    Alternative Map Key [alt_map_key]
]
