### ISSUE TITLE
Age restriction range for select professions

### ISSUE THREAD

**Issue by LaVeyanFiend** [CleverRaven/Cataclysm-DDA#42109]
# Is your feature request related to a problem? Please describe.
Profession choice has no impact on the allowed age range, allowing for absurdities as slight as 16yo military professions to as major as 16yo Senior Citizens.

# Describe the solution you'd like
Ability to restrict the age range for certain professions. This should be able to override the 16-55 general age range, for certain cases as Senior Citizen.

# Describe alternatives you've considered
Removing any profession assuming an age range & altering the allowed range to 17+ to cover military professions.

**Comment by EvgenijM86** [comment]
What if you are an immigrant from poor African country, where warlords buy young boys and train them as soldiers as soon as they hit puberty?

**Comment by EvgenijM86** [comment]
And also - we have bionic implants that teaches you martial arts, even if you had no clue how to throw punches previously. I see no reason why something similar cannot be installed on a child to make him a capable soldier.

Limiting roleplay to only what you normally encounter in 99% cases in real life is a bad idea imo.
