### ISSUE TITLE
Reloading a flashlight crashes to desktop

### ISSUE THREAD

**Issue by ColdWetNoodles** [CleverRaven/Cataclysm-DDA#42102]
# Describe the bug

Reloading an empty flashlight crashes the game

# Steps To Reproduce

1. Pressed "r" to reload
2. Selected flashlight (off)
3. Selected light battery
4. Game crashes and closes
# Expected behavior

To not crash to desktop just by reloading a flashlight

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-4043-gd684e56 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Crazy Cataclysm [crazy_cataclysm],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Fuji's Military Profession Pack [fuji_mpp]
]

# Additional context

[crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4914966/crash.zip)
[Telogia.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4914968/Telogia.zip)

**Comment by ZaricaDemoni** [comment]
most likely connected with #42089 as multiple items crash when reloading right now it seems.
