### ISSUE TITLE
(Magiclysm) Novice Necromancer and the stone knife fix

### ISSUE THREAD

**Issue by ZaricaDemoni** [CleverRaven/Cataclysm-DDA#42117]
# Is your feature request related to a problem? Please describe.
Novice Necromancer is fun but when starting out with the recent item length additions its become nearly impossible to do anything upon accidentally equipping your starting knife as a stone knife is too big to fit in either the jeans, or the hoodie.

# Describe the solution you'd like
Simply changing the stone knife to a bone shiv, would fix this problem as its already listed in game as 7in, the maximum length a hoodie can have in it, plus it is very thematic for a necromancer to have such a thing.

# Describe alternatives you've considered
Simply changing the stone knife to say a pocket knife or anything under 7in would also work, but would be less thematic. Even increasing the hoodies max item length by 2in would fix it as well, I use to be able to fit my whole 9in gym shoe into my own hoodie in high school afterall.

# Additional context
I also just learned the bone shiv cant even fit inside the hoodie, despite it being able to from listed details, so may stumbled upon a bug with this.

![image](https://user-images.githubusercontent.com/32645137/87421574-0187ed00-c58c-11ea-9bda-314c3fa20f12.png)

**Comment by Maleclypse** [comment]
What about belt and a sheath?

**Comment by ZaricaDemoni** [comment]
really just anything that prevents the endless loop of "You cant cast spell while holding item" and being unable to store in inventory which causes the "You need an item to cut yourself" message would work.
