### ISSUE TITLE
 DEBUG    : can't set ammo null in matchbook as it is not an ammo

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#42118]
# Describe the bug
 DEBUG    : can't set ammo null in matchbook as it is not an ammo

 FUNCTION : item& item::ammo_set(const itype_id&, int)
 FILE     : src/item.cpp
 LINE     : 590

# Steps To Reproduce
Activate a candle with a matchbook.

# Expected behavior

# Screenshots

# Versions and configuration
- OS: Linux
    - OS Version: LSB Version: core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch; Distributor ID: Ubuntu; Description: Ubuntu 18.04.4 LTS; Release: 18.04; Codename: bionic; 
- Game Version: 0.E-3941-g6695d25 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

**Comment by MatiasFito** [comment]
This sounds interesting I have not used matches in experimental yet, i'll take a look when i get back from work today. Cheers!

**Comment by matt32106** [comment]
I don't remember exactly but maybe there was only 1 match left before this?!

**Comment by MatiasFito** [comment]
So i've found the repro it was a bit tricker, it only throws the error when **you have an empty matchbook and a matchbook with charges in your inventyory**. Also this is failing for any action **lit** (i.e: turning on the oil lamp is failing too) but not if you select the matchbook with charges and use the **start a fire quickly**.
Another side note, If you only have a matchbook in your inventory and use it to lit candles until you run out of charges it does not fail, and it does not let you lit the candle without charges.
I think it's looping through the possible fire starters, it always take the one with less charges, in this case it's not validating if it has charges so it lights up the candle with 0 charges and then tries to substract from 0 and set the charges to null. I have not yet fiddled with C++ code but i'll see what i can do, it should be relatively easy to spot, and a good opportunity to get started with the real code.

**Comment by matt32106** [comment]
Good find Sherlock! ;) No wonder I couldn't reproduce this one...

**Comment by Night-Pryanik** [comment]
Can't confirm on latest experimental as of September, 15, 2021.
