### ISSUE TITLE
Migrate vehicle parts from Aftershock to Blaze mod

### ISSUE THREAD

**Issue by harison86** [CleverRaven/Cataclysm-DDA#42129]
# Is your feature request related to a problem? Please describe.
Many of the vehicle parts in Aftershock are not suggestive of a sci-fi setting. The fact that they are in Aftershock is frustrating for those who wish to use the vehicle parts but do not wish to add the sci-fi elements of Aftershock to their world. The parts are more like expanded versions of vanilla vehicle content, which would likely fit better in the Blaze Industries mod than in Aftershock. 

# Describe the solution you'd like
The vehicle parts should be migrated from the Aftershock mod to the Blaze Industries mod.

# Describe alternatives you've considered
Making the Aftershock vehicle parts vanilla content. The cargo trough and crude plating are little more than sheet metal welded on to the vehicle in a certain way. Larger refrigerators and freezers than the vanilla mini-sized ones certainly exist IRL in RVs and food trucks. Whether or not the consolidated vehicle crafting stations fit vanilla depends on how much "stuff" can fit into one vehicle space.

**Comment by anothersimulacrum** [comment]
@John-Candlebury @Maleclypse

**Comment by John-Candlebury** [comment]
Yeah I agree. 
I'll eventually get down to transfering them, certainly befor 0.F, but I've other things I want to add to aftershock first.

If you are up to it, feel free to move them.

**Comment by Soup-de-Loop** [comment]
Sorry this is quite a bit later, I can do the muscle for this if people desire it.
