### ISSUE TITLE
Firestations spawn a lot more zombies than defined in JSON (possibly other locations too)

### ISSUE THREAD

**Issue by BlueTigah** [CleverRaven/Cataclysm-DDA#42126]
# Describe the bug

Firestation variant "fire_station_1" uses
"place_monsters": [ { "monster": "GROUP_FIRE", "x": 10, "y": 16, "chance": 1 } ]
to place a single GROUP_FIRE

```
 {   "name": "GROUP_FIRE",
    "type": "monstergroup",
    "default": "mon_zombie_fireman",
    "monsters": [
      { "monster": "mon_zombie_fireman", "freq": 100, "cost_multiplier": 2, "pack_size": [ 3, 5 ] },
      { "monster": "mon_zombie", "freq": 40, "cost_multiplier": 1 }
    ] }
```

However in practice on normal game settings, using debug to teleport around and use clarivoyance artifact, one will find that the firestations will spawn as many as 6-18 zombie fireman. 

# Steps To Reproduce

# Expected behavior

I do not fully understand the monster spawn system but discussing it with some of the Dev team it doesn't seem normal for a 3-5 pack to be able to spawn over 10 firezombies so consistently. 

# Screenshots

https://cdn.discordapp.com/attachments/598529174302490644/732615621933531136/ea6ed6158b323ae1067d75523ccf1ffe.png

# Versions and configuration

 Windows 10
 Game Version: [0.E-2]
 Graphics version: [Tiles]
 ingame language: English
 Mods loaded: []

# Additional context

This problem was discussed on the discord 2020-07-14 at 5 PM CET in #dev-help and may not only be limited to firestations. The other firestation variant which uses very similar definitions (difference is that it spawns within an area rather than a point) also seems to spawn much higher numbers than intended. Having teleported around with default settings to firestations across the map the smallest number of zombies I've seen was once 5 and once 6, most times over 10. Having checked somewhere around 20-30 stations.

**Comment by kevingranade** [comment]
Tracing the code and data a bit, the place monster entry inherits the
monster density from the building, which gets the in-city default, which is
2, then it looks like when placing the monster spawns it looks like it
picks a random number based on that that can be significantly higher than 2.
Other than the fact that the documentation is obscure, I think this is
working correctly.
