### ISSUE TITLE
Stop making things vanish below a vehicle when dropping them inside

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#42124]
# Is your feature request related to a problem? Please describe.
If I drop several items in a vehicle container, the items that exceed the container capacity are dropped on the ground (they magically teleport outside the vehicle and creep under it). This is not necessarily detected by the player right away and leads to unnecessary frustration.

# Describe the solution you'd like
Stop dropping/moving the gear if the receiving container can not store it, or prevent the move altogether. But in any case don't make the items fall below the vehicle.

# Describe alternatives you've considered
Filing this as a bug.

# Additional context

**Comment by esavier** [comment]
this could be nice, if for example exceeding the trunk/box volume, the rest of the items would not inherit vehicle inertia while moving.
