### ISSUE TITLE
 Attempted to fire zero or negative shots using M249   / stable version E.2 windows 10 x64

### ISSUE THREAD

**Issue by dan83m** [CleverRaven/Cataclysm-DDA#42121]
DEBUG    : Attempted to fire zero or negative shots using M249

 FUNCTION : int player::fire_gun(const tripoint&, int, item&)
 FILE     : src/ranged.cpp
 LINE     : 435

![image](https://user-images.githubusercontent.com/26160782/87432725-a6d0ae80-c5e8-11ea-9142-4104341bb193.png)

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4919159/debug.log)

**Comment by ZaricaDemoni** [comment]
Not trying to sound rude but I've looked at the posts you've made regarding issues as they have popped up. none of them really follow proper reporting (things like mods used, even if no mods are used its good to know this), plus I'm not sure reporting a bug from the stable that doesn't seem to be present in the current experimental build (at least to my knowledge and testing) is going to make it any easier to fix current issues as they don't seem to be game-breaking.

Again sorry if I am coming off as rude there, just an observation, and potentially helping in regards to why it doesn't seem like anyone has taken notice the issues you've posted.

**Comment by dan83m** [comment]
> Not trying to sound rude but I've looked at the posts you've made regarding issues as they have popped up. none of them really follow proper reporting (things like mods used, even if no mods are used its good to know this), plus I'm not sure reporting a bug from the stable that doesn't seem to be present in the current experimental build (at least to my knowledge and testing) is going to make it any easier to fix current issues as they don't seem to be game-breaking.
> 
> Again sorry if I am coming off as rude there, just an observation, and potentially helping in regards to why it doesn't seem like anyone has taken notice the issues you've posted.

hi, i'm new in this kind of things i just wanted to report the bug appearing on my normal game, i dunno then where to post the bug if you kindly link me the exact section.  I repeat i'm new never did this before, if is too much an hassle then i think i just stop doing it, and just play the game without reporting any bug i encounter and just enjoying the game, so i just ignore them

**Comment by ZaricaDemoni** [comment]
your posting the bug int he right place, its mostly just formatting and I'm unsure if posting problems from the stable version of the game is going to get a fix that may already be fixed. is it for some reason not giving you the formatting template for bug reports? (below is snippet of the template it normally gives upon posting new issues)

# Describe the bug
Example description

# Steps to Reproduce
1
2
3
EXT

**Comment by olanti-p** [comment]
Most likely fixed by #39785, but it's hard to say without a save file and/or steps to reproduce

**Comment by dan83m** [comment]
> Most likely fixed by #39785, but it's hard to say without a save file and/or steps to reproduce

ah ok next time i provide the save file

**Comment by ZaricaDemoni** [comment]
also, remember to add description, steps to reproduce, game info such as tiles or symbols for textures (you clearly use tiles), language, mods used and the like. will help out a lot.

**Comment by KorGgenT** [comment]
Seeing the conversation, I am closing this as resolved.
