### ISSUE TITLE
It should be possible to put items on the floor of a vehicle

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#42123]
# Is your feature request related to a problem? Please describe.
I put books in a duffel bag. Now, if I put the duffel bag in my vehicle on an aisle, it falls to the ground.

# Describe the solution you'd like
It should be possible to put items on the floor of a vehicle without them falling on the ground below. 

# Describe alternatives you've considered
To keep things interesting/FUN, if the gear put on the floor is not in a container (vehicle or PC container), there could be a random chance to lose the item (this actually happens without a feature these days... :)).

# Additional context

**Comment by martinrhan** [comment]
that's called bug as feature LOL
