### ISSUE TITLE
Dissecting Hub 01 head of security no longer provides bionics

### ISSUE THREAD

**Issue by ConnorMartin** [CleverRaven/Cataclysm-DDA#42135]
# Describe the bug

Dissecting the Hub 01 Head of Security no longer provides a chance at the bionics he uses.

# Steps To Reproduce

Butcher the Hub 01 head of security.
Observe lack of bionics.

# Expected behavior

Dissecting the head of hub 01 security should provide a chance at the bionics (monomolecular blade, CQB CBM, alloy plating) that he uses, as was possible in 0.D.

# Screenshots

![image](https://user-images.githubusercontent.com/19824381/87471401-493e6100-c5ec-11ea-9203-6c7c08cef1ba.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-3726-g8aaf68f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key]
]

**Comment by Fris0uman** [comment]
Can you dissect a prototype Cyborg NPC and see what happens?

**Comment by Broken27** [comment]
Apparently it didn't even produced human meat?

Going by the screenshot above.

**Comment by Night-Pryanik** [comment]
Bionics were removed from Earth humans in #56552.
