### ISSUE TITLE
Moonshine Mash Recipe Produces Crapton of Methanol

### ISSUE THREAD

**Issue by Ichthysdekilt** [CleverRaven/Cataclysm-DDA#42130]
# Describe the bug
Completing one instance of the "moonshine mash" recipe generates 68750 methanol.  That's... that's a whole lot of something it probably shouldn't be producing at all.

# Steps To Reproduce
Get the recipe for moonshine mash and look at the byproducts.

# Expected behavior
Probably no methanol as a byproduct, or much much less of it.

# Screenshots
![2020-07-14_14-17-29](https://user-images.githubusercontent.com/63475824/87461311-40de2a00-c5dc-11ea-8e50-a82aa766ee99.png)

# Versions and configuration

# Additional context

**Comment by BenlyAZ** [comment]
Moonshine production often does produce a small amount of methanol, but that seems like too much and is definitely the wrong place in the process for it to show up. Probably the distillation step should produce a small amount of "moonshine foreshot" that can be distilled down to a smaller amount of usable methanol.

**Comment by Cimanyd0** [comment]
From other issues about methanol, it looks like this bug was fixed by #55015 and then made obsolete by #58149.
