### ISSUE TITLE
Water Sorts As Food, Not As Drink

### ISSUE THREAD

**Issue by Grubleafeater** [CleverRaven/Cataclysm-DDA#42144]
# Describe the bug

Bottles of water sort into food, not drink.

# Steps To Reproduce
Make a food zone and a drink zone, drop water into a unsorted zone, sort.
# Expected behavior
Water and other drinks should sort as food only when no drink zone is active.

# Additional context
Suspect nested inventory is to blame here.

**Comment by ZhilkinSerg** [comment]
Is it working differently in a latest stable?

**Comment by buildfailedforallplatforms** [comment]
This is still a problem as of build 10913
