### ISSUE TITLE
Switchblade can't fit inside army pants

### ISSUE THREAD

**Issue by stopple** [CleverRaven/Cataclysm-DDA#42167]
# Describe the bug

A switchblade (vol .05L, weight .22 lb, length 5 in.) can not fit inside

Army Pants  (2 pockets, vol .7L, weight 6.6lb, max length 5 in.)

# Steps To Reproduce

Be naked. Wear army pants. Pickup switchblade.

# Expected behavior

Switchblade should fit inside one of the two pockets having length up to 5 in.

# Screenshots

![capacity_bug](https://user-images.githubusercontent.com/19255442/87580869-1bb5ee00-c6a6-11ea-91e8-6926a6140b3b.JPG)

# Versions and configuration

- OS: Windows - OS Version: 10.0 1809
- Game Version: 0.E-4155-g9f82fd3 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [ Dark Days Ahead [dda], Disable NPC Needs [no_npc_food] ]

**Comment by ZaricaDemoni** [comment]
I noticed this issue when making #42117 it seems if item length = maximum length the item wont fit. Still testing more items to see if this is indeed the care myself.

**Comment by stopple** [comment]
\src\item_pocket.cpp line 968 ?

**Comment by Duck13Tales** [comment]
I can't put my trench knife in my kimono.

**Comment by KorGgenT** [comment]
the display shows 5 inches but it's saved in millimeters. it's probably a length thing.

**Comment by Duck13Tales** [comment]
Sure! But even when showing both in the same measure scale one is shown in centimeters and the other in milimeters what is prone to confusion. Is it possible to always shows both in the same measure unit?

![store kimono](https://user-images.githubusercontent.com/67176313/87617920-e8e41800-c6ee-11ea-9060-979107fd0d74.png)

**Comment by stopple** [comment]
switching interface -> distance units from imperial to metric revealed the issue

switchblade length is 15cm (150mm)

army pants largest pocket max length is 127mm

it is worth noting that a 150mm (5.9 inch) object is rounding down to "5 inches" in the UI

**Comment by KorGgenT** [comment]
> Is it possible to always shows both in the same measure unit?

no, not really. the ui doesn't know what you're looking at, it just tries to show lengths in the largest possible unit. metric conversions to other metric units are confusing?

**Comment by ZaricaDemoni** [comment]
switching to metric even showed the issue with the bone shiv and hoodie - bone shiv as its description also says is 20cm (7.8in), but the hoodie can only handle 18.3cm (7.2in) so a good fix for this situation on items that don't fit could be simply round them to the next higher inch. or simplify their metric number a tiny bit.

**Comment by jbytheway** [comment]
We should round up for lengths and round down for pocket sizes.

**Comment by meladath** [comment]
How difficult would it be to make inches no longer a thing in the code base and simply a ratio to mm, then you can display X.X inches?

**Comment by jbytheway** [comment]
> How difficult would it be to make inches no longer a thing in the code base and simply a ratio to mm, then you can display X.X inches?

That's already the case.  It would just be a display change.
