### ISSUE TITLE
Modifying some weapons removes ability to load it afterward

### ISSUE THREAD

**Issue by esavier** [CleverRaven/Cataclysm-DDA#42161]
# Describe the bug

Some weapons that have been modified can not be loaded with any ammunition or clips.

# Steps To Reproduce

1. get latest build, compile
2. new game, spawn mosin rifle, some mods (i've used suppressor)
3. reload/shoot weapon to check if it works
4. unload weapon, it shows "Mosin-Nagant 1891/30 (0/5 7.62x54mm)" (proper message)
4. attach suppressor
3. weapons shows now: "Mosin-Nagant 1891/30 (7.62x54mm)" (improper message)
2. weapon can not be loaded neither with clip or loose ammo

# Expected behavior

obviously, ability to load weapon after modification

# Screenshots

![obraz](https://user-images.githubusercontent.com/5251231/87554178-18c1fa00-c6b4-11ea-96ed-b44707a63b28.png)

# Versions and configuration

 - OS: Gentoo Linux
 - Game Version: 0.E-4155-g9f82fd3034
 - Graphics version: Terminal
 - Ingame language: English (default)
 - Mods loaded: [ Aftershock, Blaze industries, Disable NPC Needs, CRIT Expansion, Stats through Skills, Fuji's military profession pack, Alternate Map Key, No Fungal monsters ]

**Comment by esavier** [comment]
Additional info i noticed, not sure if its related:

#### Error while reloading broken gun
16:21:49.710 ERROR : src/item_contents.cpp:682 [item& item_contents::first_ammo()] Error: Tried to get first ammo in container not containing ammo

#### Error while shooting, (not modified gun)
16:16:37.692 ERROR : src/ranged.cpp:797 [int player::fire_gun(const tripoint&, int, item&)] Unexpected shortage of ammo whilst firing Mosin-Nagant 1891/30

**Comment by Hulkninja** [comment]
Having the same issue reloading an unmodded Mosin 1891/30. Can't load it at all, even though I have the proper clip AND ammo for it.

Maybe it's specifically the Mosin-Nagant 1891/30..?

Your top Mosin, the one that shows ammo count, says "M44 EBR" instead of "1891/30". Is it maybe a different model? Not a gun expert, nor a DDA expert, so if my question's dumb I apologize in advance.

**Comment by esavier** [comment]
doesn't matter, there are 4 variants of mosin riffle and neither works, i belive i also tried that with remington700 or maybe 24 (also bolt action rifle) but i am not sure

**Comment by esavier** [comment]
checked it again against most recent build
0.E-4329-ga3e5f32500
it appears only some guns are affected, this was testsed with modified rifle scope instead
![obraz](https://user-images.githubusercontent.com/5251231/88054398-9034d500-cb5d-11ea-8591-ddeef0c87ba5.png)

**Comment by misterprimus** [comment]
My Mosin doesn't reload, period. Zed dropped guns are always spawning empty. Reloaded items or holsters on the ground spit out errors on load. Seems to be some sort of issue with nested containers.

**Comment by HudsonMC16** [comment]
To provide some additional information for this, to maybe help in the bug hunting: 

When you reload a weapon experiencing this problem, the ammo from your inventory is consumed, but nothing goes into the gun. Then, after a bit of time or some action (I haven't pinpointed this trigger) the missing ammo spawns on the ground under you. At this point, the gun can be reloaded, and the ammo from the ground picked up, but you have more ammo than you started with. Some or all of the ammo involved in this whole process is duped.

**Comment by Hulkninja** [comment]
> To provide some additional information for this, to maybe help in the bug hunting:
> 
> When you reload a weapon experiencing this problem, the ammo from your inventory is consumed, but nothing goes into the gun. Then, after a bit of time or some action (I haven't pinpointed this trigger) the missing ammo spawns on the ground under you. At this point, the gun can be reloaded, and the ammo from the ground picked up, but you have more ammo than you started with. Some or all of the ammo involved in this whole process is duped.

Wait... That's not what happens for me, at all. No ammo goes missing, none respawns, and the gun still can't be reloaded. Did you get any error message(s)?

**Comment by esavier** [comment]
> 
> 
> > To provide some additional information for this, to maybe help in the bug hunting:
> > When you reload a weapon experiencing this problem, the ammo from your inventory is consumed, but nothing goes into the gun. Then, after a bit of time or some action (I haven't pinpointed this trigger) the missing ammo spawns on the ground under you. At this point, the gun can be reloaded, and the ammo from the ground picked up, but you have more ammo than you started with. Some or all of the ammo involved in this whole process is duped.
> 
> Wait... That's not what happens for me, at all. No ammo goes missing, none respawns, and the gun still can't be reloaded. Did you get any error message(s)?

Thats was also my experience to this point. weapon after modifying it was unable to hold ammo at all (i.e. look at the screen there is no [5/5] marker). If this is repeatable that may be separate, but related bug.

**Comment by misterprimus** [comment]
> > > To provide some additional information for this, to maybe help in the bug hunting:
> > > When you reload a weapon experiencing this problem, the ammo from your inventory is consumed, but nothing goes into the gun. Then, after a bit of time or some action (I haven't pinpointed this trigger) the missing ammo spawns on the ground under you. At this point, the gun can be reloaded, and the ammo from the ground picked up, but you have more ammo than you started with. Some or all of the ammo involved in this whole process is duped.
> > 
> > 
> > Wait... That's not what happens for me, at all. No ammo goes missing, none respawns, and the gun still can't be reloaded. Did you get any error message(s)?
> 
> Thats was also my experience to this point. weapon after modifying it was unable to hold ammo at all (i.e. look at the screen there is no [5/5] marker). If this is repeatable that may be separate, but related bug.

I think I saw a bug like that elsewhere. I don't think this is related to weapon mods since the gun is broken as soon as I spawn it without doing anything to it. Possibly related, but appear to be different bugs.

**Comment by HudsonMC16** [comment]
> > To provide some additional information for this, to maybe help in the bug hunting:
> > When you reload a weapon experiencing this problem, the ammo from your inventory is consumed, but nothing goes into the gun. Then, after a bit of time or some action (I haven't pinpointed this trigger) the missing ammo spawns on the ground under you. At this point, the gun can be reloaded, and the ammo from the ground picked up, but you have more ammo than you started with. Some or all of the ammo involved in this whole process is duped.
> 
> Wait... That's not what happens for me, at all. No ammo goes missing, none respawns, and the gun still can't be reloaded. Did you get any error message(s)?

Yeah, I get the same "unexpected ammo shortage" error message.

**Comment by kevingranade** [comment]
Need to double check this, I vaguely recall something being done about this.

**Comment by LaVeyanFiend** [comment]
Cannot be replicated by Steps to Reproduce anymore, this can be closed.

## Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-8626-g6b09767 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by hexagonrecursion** [comment]
I can confirm that the bug is **not reproducible** in c4efd9e. I was successfully able to reload and shoot Mosin-Nagant 1891/30 after attaching a suppressor

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 32 (Thirty Two); Release: 32; Codename: ThirtyTwo; 
- Game Version: 0.E-8924-gc4efd9e-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

I can confirm that the bug was reproducible in 9f82fd3

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 32 (Thirty Two); Release: 32; Codename: ThirtyTwo; 
- Game Version: 0.E-4155-g9f82fd3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by hexagonrecursion** [comment]
On a related note: I grabbed an official binary from github. Why is it saying "Game Version: 0.E-8924-gc4efd9e-dirty"? I thought the releases are uploaded by CI.

**Comment by Zireael07** [comment]
@hexagonrecursion: Something something about newer translations and checkouts, is the explanation I saw on another PR.
