### ISSUE TITLE
Feral Humans throw infinite bricks

### ISSUE THREAD

**Issue by EirenexTheDragon** [CleverRaven/Cataclysm-DDA#42169]
#Describe the bug

Feral Humans are supposed to only have 6 bricks, yet they can be seen throwing infinite bricks 

# Steps To Reproduce
1. Start or teleport in a prison 
2. spawn a feral human in the cell (you can apparently spawn 3 kind, but it doesnt matter)
3. Wait and see how they throw past their 6 bricks theyre supposed to have

# Expected behavior

Per json, they should have only 6 bricks to throw

# Screenshots
![grafik](https://user-images.githubusercontent.com/41762755/87593675-19768280-c6ec-11ea-9362-c346a43fbb4f.png)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-4155-g9f82fd3 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

doesnt matter which of the 3 feral humans you spawn, they all throw infinite bricks. (and sadly the thrown items dont drop on impact either)

**Comment by Maleclypse** [comment]
```    "flags": [
      "PRIMITIVE_RANGED_WEAPON",
      "NEVER_JAMS",
      "NONCONDUCTIVE",
      "NO_REPAIR",
      "WATERPROOF_GUN",
      "NO_SALVAGE",
      "NO_UNLOAD",
      "NO_AMMO"
    ]```
The `NO_AMMO` flag needs to be removed in the monstergun item file.  I think.

**Comment by UndeadMoose** [comment]
Still having this happen even after the PR above was merged. Tested with debug and one hit me well above 50 times with bricks.

**Comment by wapcaplet** [comment]
Confirmed, still occurring in 0.E-9572-g 483cd09a89

**Comment by actual-nh** [comment]
I have to wonder whether this is related to the obverse situation, #46780, and whether Goblin slingers have infinite rocks.

**Comment by actual-nh** [comment]
Do turrets run out of ammo?

**Comment by anothersimulacrum** [comment]
It's very easy to test with the talon bots, they do indeed run out of ammo. The fake gun used for feral human attacks probably does not consume ammo, like it should.

**Comment by aerrant** [comment]
Figured this out: the `special_attacks` object needs to have `ammo_type` specified, and, consequently, the fake gun needs `clip_size`. I'll do a PR once I figure out how to prevent the fake gun from making "Click" noises on no ammo.
