### ISSUE TITLE
Zombies bleeding

### ISSUE THREAD

**Issue by Duck13Tales** [CleverRaven/Cataclysm-DDA#42172]
# Describe the bug

I got the newest experimental and noticed that I can easily get the zeds to bleed. Is this intended?

# Steps To Reproduce

1 - Grab a trench knife (or probably any weapon with a good pierce) and start trashing the zombies around.
2 - With level 5 on melee and unarmed I notice that I constantly get the zombies to bleed.

# Expected behavior

Usually zombies are immune or really resistant to bleed since they or already don't have much blood or don't need it at all.

# Screenshots

If you wish I can post screenshots but it is happening very frequently.

# Versions and configuration

I am using using the CDDA 0.E-b10839 with the mods:

DDA
Disable NPC needs
Stats through skills
Stats through kills
SpeedyDex

# Additional context

I think that only 1 died from bleed till now but still zombies bleeding so that it has any effect on them usually is quite uncommon on most lores.

**Comment by Proluiz** [comment]
yes i've noticed this mechanic happening while using bows, i was preparing to sht my next arrow them the zombie died out by bleed, seens very easy to make them bleed with arrows

**Comment by nexusmrsep** [comment]
Yes, zombies bleed, and this is intended. They always had the flags in the code that stated that. They didn't bleed before just because there was no mechanics implemented for that.

**Comment by anothersimulacrum** [comment]
Higher tier zombies should probably stop using blood, but lower tier ones definitely make sense to bleed.

**Comment by Duck13Tales** [comment]
It is just that in most lores the zombies don't need blood for anything and even in CDDA the description of many zombies states that their bodies are heavily damaged or even have open gaps, like the brainless zombie, just like the zombies in CDDA don't need the blood and not even organs at times.
