### ISSUE TITLE
Rotten items disappearing

### ISSUE THREAD

**Issue by Duck13Tales** [CleverRaven/Cataclysm-DDA#42182]
# Describe the bug

If you save and load, it is quite common to rotten items disappear. Is it intended?

It seems that the carrion spawn were disabled so then are the rotten things too?

# Steps To Reproduce

1 - Place some stacks of rotten food/meat/cow pies around
2 - Save and load.
3 - Notice that most if not all disappeared.

# Expected behavior

No idea.

# Screenshots

Not applicable.

# Versions and configuration

I am using using the CDDA 0.E-b10839 with the mods:

DDA
Disable NPC needs
Stats through skills
Stats through kills
SpeedyDex

**Comment by Hirmuolio** [comment]
Rotten items despawn once they have 2x the rot required to be marked as rotten. (or after 10 days worth of rot for corpses)

**Comment by Duck13Tales** [comment]
Haha, I was indeed wondering why some things always disappeared and others sometimes didn't, but in the end everything disappeared haha

I was trying to get some fat and cow pies to make fertilizer batches but it kept disappearing so now at least I know why haha

Thanks a lot!

**Comment by Duck13Tales** [comment]
Is there a FAQ anywhere to those silly questions?
