### ISSUE TITLE
Quarterstaff disappears on Crafting

### ISSUE THREAD

**Issue by james-wash** [CleverRaven/Cataclysm-DDA#42192]
Game version: 0.E-2

Operating system: Windows 8.1

Tiles or curses: Tiles

Mods active: Stats through skills, Stats through kills, SpeedyDex

### Expected behavior

After crafting a quarterstaff in the character's hands, it should either be in their inventory or dropped onto the floor and is retrievable.

### Actual behavior

Quarterstaff is dropped when finished and promptly disappears - no tile on or around the character has the quarterstaff.

### Steps to reproduce the behavior

Craft a quarterstaff in hands. I tried this at night, next to a computer monitor and next to a fire, with similar results both times.

**Comment by Duck13Tales** [comment]
Just tried it in this version with almost the same mods and it worked. Take a look if it wasn't stored in a cupboard or another storage near to you just like happened to me.

![quarterstaff](https://user-images.githubusercontent.com/67176313/87738410-b2240580-c7b3-11ea-816b-5c34902e9d68.png)

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-6398.
![изображение](https://user-images.githubusercontent.com/11132525/155757924-ad9291ac-bd54-4387-8c7b-a6141d3225f7.png)
