### ISSUE TITLE
Player falls into just dug deep hole

### ISSUE THREAD

**Issue by Alex-Folts** [CleverRaven/Cataclysm-DDA#42193]
# Describe the bug

When dig deep hole, just after action finishes player falling into hole and get injured.

# Steps To Reproduce

1. in new world with new player or on existing save, spawn shovel
2. go to dirt tile
3. use showel's action "dig pit here" to dig shalow pit
4. use showel's action "dig pit here" to dig deep pit
5. character will fall in deep pit and get injured

# Expected behavior

After digging hole charater should be on its bottom, thats how you dig hole in the ground.

# Screenshots

![Scr1137](https://user-images.githubusercontent.com/5638906/87696699-d8d54280-c799-11ea-90d5-59d4231ef869.jpg)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-4197-g3b15cc4 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

**Comment by woutershep** [comment]
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/42049 ?

**Comment by Alex-Folts** [comment]
Seems so, i havent seen it before.

**Comment by nexusmrsep** [comment]
Will be solved by #42070

**Comment by andrei8l** [comment]
Woops, didn't notice your comment before I opened my PR (https://github.com/CleverRaven/Cataclysm-DDA/pull/42197). Looks like you just removed that function instead of moving it (it was introduced in https://github.com/CleverRaven/Cataclysm-DDA/commit/15c39c9425f961176c5671fcf2fb5ef5101b727f)

**Comment by nexusmrsep** [comment]
@andrei8l  Yes, but your solution might be better, so keep it.

**Comment by Alex-Folts** [comment]
Fixed in https://github.com/CleverRaven/Cataclysm-DDA/pull/42197
