### ISSUE TITLE
Cannot consume 'clean water' that I just made by boiling it

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#42201]
# Describe the bug
Cannot consume 'clean water' that I just made by boiling it (the line is not there in the menu):
![cdda](https://user-images.githubusercontent.com/7557986/87728154-c0c5e900-c7c2-11ea-964e-d810685a29e9.png)

Also, I am in a minus temp place (dead of winter) and a side effect is that if I put this clean hot water in a container it is instantly frozen and I have to heat it up again in order to be able to consume it.

# Steps To Reproduce
Light fire
Build menu
Clean water 

# Expected behavior
1. Offer to drink the water straightaway as before. 
2. Clean water just boiled should stay hot for some time.

# Versions and configuration
- OS: Linux
    - OS Version: LSB Version: core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch; Distributor ID: Ubuntu; Description: Ubuntu 18.04.4 LTS; Release: 18.04; Codename: bionic; 
- Game Version: 0.E-4156-gc884f02 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by anothersimulacrum** [comment]
It is expected behavior that you need to put your crafted liquids in a container before using them.

**Comment by Hirmuolio** [comment]
The water freezing is same as #40732

**Comment by anothersimulacrum** [comment]
Okay, then closing as duplicate/intentional.
