### ISSUE TITLE
Large Amount of Rifles too Short

### ISSUE THREAD

**Issue by Bulletfang** [CleverRaven/Cataclysm-DDA#42205]
# Describe the bug
A large amount of rifles are far too short, I've noticed a lot of guns are only 14 cm long and skimmed through the .json files for them. They either do not have their "longest_side" set and have no "copy-from", or the gun they "copy-from" has its "longest_side" not set, or something else went wrong that I have no understanding of. These are the rifles I found who are definitely too short, none of them are longer than 20 cm (double-checked in-game):

3006.json:
_M1 Garand
M1903 Springfield
Browning Automatic Rifle
Remington 700_

762R.json:
_Mosin-Nagant M44
Mosin-Nagant M44-EBR
Mosin-Nagant 1891/30
Mosin-Nagant 1891/30-EBR_

700nx.json:
_Elephant gun_

500.json:
_Big Horn Model 89_

84x246mm.json:
_M3 recoilless rifle
AT4 (has "copy-from" for the M3 recoilless rifle)_

66mm.json:
_M202A1 FLASH_

50.json:
_Barrett M107A1 (opened an issue for this one exclusively the other day, I don't know how to link issues)
M2HB Browning HMG
.50 caliber rifle
AI AS50
McMillan TAC-50
Serbu BFG-50
(I noticed that some of these have "copy-from" for "rifle_base" but are still way too short and their length is also varying wildly)_

40x53mm.json:
_Mark 19 grenade launcher_

40x46mm.json:
_tube 40mm launcher
M320 standalone launcher
M79 launcher
Milkor MGL
RM802 grenade launcher
triple-barrel 40mm launcher_

22.json:
_American-180
Marlin 39A
pipe rifle .22 (?)
Ruger 10/22_

20x66mm.json:
_RM120c shotgun
RM20 autoshotgun
RM228 PDW_

8x40mm.json:
_RM11B scout rifle
RM2000 submachine gun
RM298 HMG
RM51 assault rifle
RM614 LMG
RM88 battle rifle_

5x50.json:
_RM216 SPIW
RM232 IDW (it's a machine pistol but 9 cm still seems a bit short, not sure about this one since the gun is fictional)_

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-4197-g3b15cc4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by ZaricaDemoni** [comment]
Having held and fired an M1 Grand in real life, plus being a gun nut. I can tell you its full length is 43.5 in (1,100 mm) roughly. so yeah, much more than 200mm

**Comment by UmbralReaper** [comment]
See #41691

**Comment by Bulletfang** [comment]
I see, this issue is redundant then.
