### ISSUE TITLE
Disassembling steel frames takes 7 game hours.

### ISSUE THREAD

**Issue by Rjtheperson** [CleverRaven/Cataclysm-DDA#42210]
# Describe the bug

Disassembling a steel frame into lumps of steel takes 7 hours.

# Steps To Reproduce
1. Procure a steel frame.
2. Use ( or B to disassemble the steel frame
3. Spend a typical work day disassembling a single steel frame

# Expected behavior
 Taking apart a steel frame should go way faster than forging it.

# Screenshots

![image](https://user-images.githubusercontent.com/65632694/87751969-1a72e700-c7b4-11ea-8c8e-2195dcc096b5.png)

# Versions and configuration
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 7 Professional
- Game Version: 0.E-4197-g3b15cc4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Graphical Overmap [Graphical_Overmap],
    Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Mythical Martial Arts [MMA]
]

# Additional context
#41881

**Comment by Hulkninja** [comment]
Can confirm this, though I thought it was intended. Doesn't make sense if the craft time is way quicker, though.

**Comment by Rjtheperson** [comment]
The craft time is long without the proficiency and that's fine, but I've already brought this up in the Discord and I was told that this disassembly time is wrong. 
![image](https://user-images.githubusercontent.com/65632694/88252145-04f13780-cc62-11ea-903a-d45d15e39e4f.png)
