### ISSUE TITLE
Battery CBM

### ISSUE THREAD

**Issue by buildfailedforallplatforms** [CleverRaven/Cataclysm-DDA#42216]
# Describe the bug

Can't consume batterys
Can't remove battery cbm

# Steps To Reproduce

1. Install battery cbm
2. Consume battery, no option to consume
3. Uninstall battery cbm, successful removal
4. Battery cbm still installed

# Expected behavior

Should be able to consume batteries to power bionics
Should be able to remove cbms

# Screenshots

# Versions and configuration

# Additional context

**Comment by Fris0uman** [comment]
There's two issue here, one is a duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/41744

And the other is the removale bug, can you complete the issue template with the list of mods you're using and everything?

**Comment by buildfailedforallplatforms** [comment]
Submitted new issue
