### ISSUE TITLE
Crash when reloading battery in food processor

### ISSUE THREAD

**Issue by xned** [CleverRaven/Cataclysm-DDA#42224]
Game crash when reloading battery in food processor. 

# Steps To Reproduce

<!-- Steps to reproduce the behavior:
1. Use the reload menu to reload battery in the food processor.

# Expected behavior

# Screenshots

<!-- **If applicable**, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/22093390/87810667-a260fb80-c85d-11ea-8eea-727a9624ff55.png)

# Versions and configuration

Windows 8.1 game version 10847

# Additional context

Crash log:
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4939041/crash.log)

**Comment by Duck13Tales** [comment]
Sorry but just did it with a medium battery and it worked just fine. Unloaded and reloaded.

**Comment by xned** [comment]
Sorry my bad. 
Problem was in build 10844, not 10847. Just updated and can confirm that it works now.
Thanks for the quick respons!
