### ISSUE TITLE
Talking to neutral NPC causes crash

### ISSUE THREAD

**Issue by ColdWetNoodles** [CleverRaven/Cataclysm-DDA#42229]
# Describe the bug
Trying to talk to a gardener NPC I found causes a crash to desktop

# Steps To Reproduce

1. Walk up next to NPC
2. Pressing "C" for talk
3. Select "Talk to"
4. Select Gardener NPC
5. Crash

# Expected behavior
To actually talk to the NPC and not crash

# Screenshots

![image](https://user-images.githubusercontent.com/68250720/87819899-09b98400-c83b-11ea-8178-072e58cfacc4.png)
This happens when I load up my save, the NPC has a laser finger as a weapon
# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-4226-g1ea5556 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Crazy Cataclysm [crazy_cataclysm],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Fuji's Military Profession Pack [fuji_mpp]
]
[crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4939571/crash.zip)
(Sent in wrong save file, fixed it) 
[Bogalusa.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4939734/Bogalusa.zip)

# Additional context

**Comment by andrei8l** [comment]
Is that the right save file? I can't find your NPC. The one in the basement doesn't have the finger gun and doesn't seem to crash the game.

**Comment by ColdWetNoodles** [comment]
> 
> 
> Is that the right save file? I can't find your NPC. The one in the basement doesn't have the finger gun and doesn't seem to crash the game. I am missing a few of the mods though.

Fixed

**Comment by andrei8l** [comment]
I've fixed the crash, but the error message requires other changes. I'm looking into that now. The first commit is up in the mean time, if you want to continue your save.
