### ISSUE TITLE
Bionic removal bug

### ISSUE THREAD

**Issue by buildfailedforallplatforms** [CleverRaven/Cataclysm-DDA#42222]
# Describe the bug

Cannot remove cbms

# Steps To Reproduce

1. Install cbm
2. Uninstall cbm successful
3. CBM still installed

# Expected behavior

CBMs should be removed after successful unistall

# Screenshots

![mods](https://user-images.githubusercontent.com/62628815/87788400-a0f4fa80-c880-11ea-89b6-f8fe5d9f32f1.png)

# Versions and configuration

# Additional context

**Comment by Fris0uman** [comment]
Trying to reproduce the issue I get a error, but the CBM is properly removed
```
this item location type has no parent
```

**Comment by int-ua** [comment]
Please test with latest version and fill the template with information.

**Comment by OliveChukar** [comment]
Tested in ver 0.E-9111-gd1e702b-dirty. When CBM was removed it was placed under the player not in inventory.  CBM removal action did remove the CBM from the character.

**Comment by Fris0uman** [comment]
This was fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/44985 , sorry I missed that issue I should have pinged it in the PR
