### ISSUE TITLE
Metal Portable Smoking Rack Ammo Capacity

### ISSUE THREAD

**Issue by hughesdylan** [CleverRaven/Cataclysm-DDA#42223]
# Is your feature request related to a problem? Please describe.

I noticed the metal portable smoking rack doesn't store enough charges to smoke all the food you can load into it. Not sure if this is intentional. I did some digging in data/json/furniture_and_terrain/furniture-tools.json and noticed the pseudo_tool for the regular smoking rack was different than the metal portable one, and might be causing the issue. Not sure if this is intended behavior or an actual bug.

# Steps To Reproduce

1. Place metal smoking rack
2. Try to load charcoal
3. Notice maximum charges is very low

# Describe the solution you'd like
Change the Pseudo tool listing in the above file for the portable rack to the same as the stationary rack

# Describe alternatives you've considered
It's possible this is intended behavior. If so please close this. Another solution would be to make a new pseudo-tool that has a somewhat smaller volume of charcoal capacity but also enough to smoke the entire rack contents

# Additional context

The metal rack has a smaller food capacity than the stationary one and that seems totally fine. But I would expect the rack to at least be able to smoke its full loadable volume of food. Currently loading maximum food volume then trying to smoke it results in a "not enough charges" message.

**Comment by esavier** [comment]
not sure, but i also noticed that fully loaded smoking rack can be loaded only to around 200 charges but requires much more to start smoking process ( around  400 i think )
