### ISSUE TITLE
Preview of character image

### ISSUE THREAD

**Issue by IIverner** [CleverRaven/Cataclysm-DDA#42234]
# Is your feature request related to a problem? Please describe.
  If I want to see the character, I have to wait until the game starts. Some of the tilesets provide more detail on the image, I think it would be better if you could preview the characters in the create character screen

# Describe the solution you'd like
  You can see the image when you create the character instead of when the game starts

# Describe alternatives you've considered
 Don't do it

# Additional context

**Comment by Entity-y** [comment]
This made me think of the Pokemom intro where you see your character and they shrink down into a sprite.

![tenor (1)](https://user-images.githubusercontent.com/50155659/88211804-38ad6c80-cc24-11ea-9112-6216a963f7ab.gif)


Having a system like that would be great. Then having the ability to go back and see the full detail version at will to really appreciate mutations, bionics, and the gear you're wearing.
