### ISSUE TITLE
Bandits do not bleed to death

### ISSUE THREAD

**Issue by Rjtheperson** [CleverRaven/Cataclysm-DDA#42233]
# Describe the bug
Bandits do not bleed to death

# Steps To Reproduce
1. Find a bandit.
2. Make the bandit bleed.
3. Bandit does not bleed to death even when the message log says they do.

# Expected behavior
Bandit dies when losing enough blood.

# Screenshots

![image](https://user-images.githubusercontent.com/65632694/87837425-4f307e00-c848-11ea-97d3-59a6cb456fa1.png)

# Versions and configuration
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on  Windows 7 Professional
- Game Version: 0.E-4226-g1ea5556 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Graphical Overmap [Graphical_Overmap],
    Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Mythical Martial Arts [MMA]
]

# Additional context
None

**Comment by anothersimulacrum** [comment]
Fixed in #42383
