### ISSUE TITLE
Mitten Warmth, and being hot and cold at the same time.

### ISSUE THREAD

**Issue by ZaricaDemoni** [CleverRaven/Cataclysm-DDA#42244]
# Describe the bug
So noticed when i got on today after updating and walking around outside, My character was warm with the cold skin (player image), and after checking was both warm and cold under status. Checked my layering settings and then noticed mittens are only warming one hand.

# Steps To Reproduce
1st issue
Equip a pair of mittens
Check laying to see warmth
Only one hand is warm

2nd issue (not easy to reproduce, tempature upon noticing this was 64F, from linked sreenshot i had on the same items minus the sweatshirt)
Be around day 10 summer
be outside around 12pm with standard summer clothing
Become cold but also have heat slowdown.

# Expected behavior
not being hot, and cold during summer & both hands being nice and toasty.

# Screenshots
Layering screen for warmth and encumbrance.
![image](https://user-images.githubusercontent.com/32645137/87854963-310b6200-c8ca-11ea-93d9-9b1859e249ef.png)

# Versions and configuration

 - OS: Windows 8.1
 - Game Version: 0.E-4228-gcc2533c
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: "dda", "no_npc_food", "blazeindustries", "crt_expansion", "magiclysm", "DinoMod", alt_map_key", "MMA", "cbm_slots", "fuji_mpp", "speedydex", "stats_through_kills", "StatsThroughSkills"

**Comment by ZaricaDemoni** [comment]
Two more images, as I manage to reproduce the chilly and warm bit again.

![image](https://user-images.githubusercontent.com/32645137/87857775-370b3e00-c8de-11ea-8602-26a816903360.png)

![image](https://user-images.githubusercontent.com/32645137/87857809-691ca000-c8de-11ea-9101-07713e06562f.png)

It seems the passive state of warmth for my hand is -25, which i don't think is suppose to be the case here. even if the watch is causing this.

**Comment by andrei8l** [comment]
Could be the same as https://github.com/CleverRaven/Cataclysm-DDA/issues/42105. Can you check with the debug menu whether one of your character's hands is broken? (debug menu -> player -> edit player -> you -> set hitpoints -> "all" shows a lower number than the other entries)

**Comment by ZaricaDemoni** [comment]
while yes something was injured it wasn't broken (almost burned my right hand off,) as I've been paying attention to that since the first post. changing it only made my hand colder. not warmer. it went down to -35 upon healing.

![image](https://user-images.githubusercontent.com/32645137/87858347-1644e780-c8e2-11ea-95ff-e06b6d67cad9.png)

**Comment by ZaricaDemoni** [comment]
so with resent change to body-parts and fixing the other issue my hand is no longer in the negative however. I'm not sure my hand is suppose to be warmer for just wearing a silver watch.

![image](https://user-images.githubusercontent.com/32645137/87879952-bcf0bd00-c9a2-11ea-886a-b93f3b873048.png)

**Comment by ZaricaDemoni** [comment]
closing as this seems to have been fixed from all the testing i can see in game.
