### ISSUE TITLE
NPC can't teach skill as mission reward

### ISSUE THREAD

**Issue by Hulkninja** [CleverRaven/Cataclysm-DDA#42248]
Upon completing a mission for an NPC, I asked them to teach me a skill as a reward. The mission was marked as completed, but the NPC couldn't teach me a skill, and upon speaking to them again they behave as if the mission hasn't been completed yet.

# Steps To Reproduce

1. Find NPC that can give you a quest, in my case a "kill their mom" quest
2. Do the quest
3. Turn in the quest, ask for skill training as reward
4. Get error message

# Expected behavior

Get my skill trained.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-4228-gcc2533c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: 
Dark Days Ahead [dda],
Graphical Overmap [Graphical_Overmap]

# Additional context

Error Message:
"DEBUG    : start_training with no valid skill or style set FUNCTION : void talk_function::start_training(npc&) FILE     : src/npctalk_funcs.cpp LINE     : 955"

Save file, in case it's helpful:
[San Joaquin.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4942218/San.Joaquin.zip)

**Comment by Madrawn** [comment]
Having the same problem on 0.E-4226-g1ea5556 (tiles) 64-bit.

**Comment by Hulkninja** [comment]
#42249 Looks like a solution to this issue. We'll have to wait for it to get merged. Hopefully will happen by next build.
