### ISSUE TITLE
ID Cards Reworked

### ISSUE THREAD

**Issue by Entity-y** [CleverRaven/Cataclysm-DDA#42257]
# Is your feature request related to a problem? Please describe.
Currently military and science ID cards are one time use consumable items.

# Describe the solution you'd like
Make ID cards persistent and have incremental levels of access. 

For example, you have a Level 1 science ID card. With this you can gain access to the lab but still be restricted from prisoner containment until you find a Level 2 science ID card. Barracks would require Level 3, Armory and finale room Level 4. This would add an alternative to hacking computers by finding a high level ID card. High level military cards could also be used to gain access to a lab armory.

Low level cards would be found on scientists, higher tier ones maybe deep in the lab in an office drawer or maybe have the ability to print your own high level access card.
![Hbe29dc0b950c4fb0be67104f49449fa22](https://user-images.githubusercontent.com/50155659/87862922-45c81400-c923-11ea-94ff-5933db1e622a.jpg)

# Describe alternatives you've considered
Just having ID cards persistent without the varying levels of access.

# Additional context
Similar to how city maps reveal that particular city, these ID cards could have limited access to the area they are found in and not work in another city's lab or military base.

Once the system is in place, other places that would realistically be restricted could also recieve the same treatment. Places like factories, hazardous waste facilities, office towers, parts of hospitals and doctors offices, prisons, etc.

**Comment by nexusmrsep** [comment]
Idea is fine, but there would be technical issues with this idea. Game wide persistent ID cards would be unbalanced, and unrealistic at the same time unless you'd provide a good explanation why someone could access any site. Therefore ID cards should be site-related. So you can use Lab A Access Card to access Lab A, but not Lab B nor Lab C. The off hand idea how to  make such a distinction is implementing access cards like game maps, that are bound to the nearest town, and don't work outside its boundaries. It has a quirk though - if you spawn an Id card on a random scientist zombie in a town with no lab, and it would inherit this area as relevant site, it would be useless by default.

**Comment by hexagonrecursion** [comment]
@nexusmrsep I don't think that is how maps work. As far as I can tell a map always displays the name of the town you are currently closest to regardless of where you found it and activating a map always reveals an area centered on you. This is most likely a feature on one got around to implementing yet.

**Comment by Galon345M** [comment]
Since the map has coordinates maybe we could implement that when a card is spawned the coordinates of a lab are imprinted on it so that it can only be used at those coordinates resulting in lab specific cards.

**Comment by anothersimulacrum** [comment]
@hexagonrecursion it is tied to the town closest to where you found it, not just the closest one.

**Comment by Entity-y** [comment]
Using coordinates on the card wouldn't be a bad idea, even if it is hidden to the player but used to determine the closest lab, much like how an evac shelter tells the location of the nearest refugee center. An alternative to that would be to start giving labs generic randomly generated names and tying that in with the relevant ID card, this would cut out a lot of the confusion as to which lab the card goes to if there are multiple labs in a town.

**Comment by andrei8l** [comment]
If they're tied to certain labs, they're still effectively single-use but you have to throw them in a fire instead of having the game delete them for you automatically, at least with current lab types.

**Comment by Entity-y** [comment]
@andrei8l not necessarily, there are multiple areas where an access card could be used in a single lab. Multiple prisoner containments, barracks, and vaults. Some labs have a rail system connected to other labs, couldn't we think of this as one corporation, surely a scientist could have access to those branches of labs as well.

**Comment by DialoMalison** [comment]
Also, if we made the lab doors require an ID card each time you go through it (like they do IRL), then ID cards tied to a specific lab would not be the same as single use cards.

**Comment by Entity-y** [comment]
Having the keycard reader open the barrier for a few moments then automatically close would make the building or room feel more premium and secure.

**Comment by hexagonrecursion** [comment]
I was wrong. Maps spawned via the debug menu (which is what I used when testing) behave how I described. Maps spawned naturally on the other hand do remember where they were found.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/id-cards-and-scanners/25428/14
