### ISSUE TITLE
Segfault firing woodbow at zombies

### ISSUE THREAD

**Issue by Sumguy62** [CleverRaven/Cataclysm-DDA#42250]
# Describe the bug

I fired the woodbow at zombies, and it worked fine for a while, then it segfaulted on firing another time. Don't know what was special about it.

# Steps To Reproduce

Fire the woodbow at zombies?

# Expected behavior

Not crashing, I guess.

# Versions and configuration

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4942302/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4942303/debug.log)

**Comment by andrei8l** [comment]
Can you provide a save file please? I wasn't able to reproduce it and the crash.log is incomplete and only gave me a vague idea of the problem
