### ISSUE TITLE
Being on Down Staircase blocks Item Detection

### ISSUE THREAD

**Issue by Boredone** [CleverRaven/Cataclysm-DDA#42260]
# Describe the bug
While standing on a Downward Staircase (Not upward), you can't access nearby items for crafting or construction purposes, with the game acting like they don't exist while you are on the tile.

# Steps To Reproduce
1. Get materials to build/craft something.
2. Lay items/tools on the ground near a downward staircase.
3. Attempt to craft/build something while on the same tile as the staircase.

# Expected behavior
To be able to easily craft/build stuff with nearby items unless something was in the way.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-4241-g36ba9f8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA],
    No Rail Stations [No_Rail_Stations],
    Stats Through Kills [stats_through_kills],
    No Fungal Monsters [No_Fungi]
]

# Additional context
Quick test reproduced it in vanilla as well, so not a mod problem.
Stuff in your inventory works just fine, but most of the tests had the items only one tile away, so obviously should of worked fine.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-6398, see testing in https://github.com/CleverRaven/Cataclysm-DDA/issues/48517#issuecomment-1051003365.
