### ISSUE TITLE
Ability to sort CBM/Bionics list

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#42279]
# Is your feature request related to a problem? Please describe.
I'm often frustrated when I get more than a few bionics and they're listed only in order of installation.

# Describe the solution you'd like
I'd like to be able to group the list into power generating, no cost, and power using CBM's. Being able to sort by cost/turn would be lovely. 

# Describe alternatives you've considered
Not doing any specific sorting, but making it possible to move them up or down in the list would be very helpful to let people sort the list themselves.

**Comment by ZhilkinSerg** [comment]
Fixed in #42296
