### ISSUE TITLE
You should not be able to know precise kcal of food except on canned/packed food

### ISSUE THREAD

**Issue by Galon345M** [CleverRaven/Cataclysm-DDA#42271]
# Is your feature request related to a problem? Please describe.

We should not be able to know the precise kcal for food. You don't know how much a slab of meat from a animal or a piece of vegetables has and as such that information should be hidden for new characters. Exception should be canned foods since they have labels on the cans, and packed food like chips or candy which have information on the wrappers.
# Describe the solution you'd like
I want to implement a system that hides or generalizes the kcal values in the eat screen and the information screen of items by linking the knowledge to survival or cooking skills. As an example lets say we have a food item thats not labeled that has 1491 kcal. We can make the information the player sees diffrent by using rounding up/down depending on the skills. So for example:

Survival 0: No information on how many kcal the item has. 
Survival 1: Item has 1000 kcal (1491 is rounded down to 1000 - 1 number information)
Survival 2: Item has 1500 kcal (1491 is rounded to 1500 2-number rounding)
Survival 3: Item has 1490 kcal (1491 is rounded to 1490 3-number rounding)
Survival 4: Item has 1491 kcal (1491 is rounded to 1491 4-number rounding)
and so on.

# Describe alternatives you've considered
Not doing it and leaving the system as is, but thats less realistic.

# Additional context
See example given above.

**Comment by Fris0uman** [comment]
We might want to hold off on tht for a bit as a lot of players seem very confused by what's going on with the calorie system.

**Comment by ZaricaDemoni** [comment]
Another problem with this besides the fact I can kill myself in a week if I'm not paying attention to the calorie system. A lot of items in the game are packaged (all drinks, candies, canned goods, packs of bacon. anything in a box, bottle or bag), and things you can make from cookbooks telling you calories are proper in most cases as there are cookbooks with calories written in them.

It would make the amount of items affected realistically very low, and confuse people more as to why a small group of items are missing calories but this larger group is not at lower survival levels.

**Comment by Qrox** [comment]
> 2 items in the game of "plastic bottle of herbal tea".

We can just add a flag to items when they are supposed to come with packages with calorie info. For player crafted items, perhaps we can describe them as "very", "somewhat", "a little bit"/"oily", "umami", "sweet", "bland" etc instead of precise calorie values. I'm not sure how players would perceive such a change though, it can be confusing if not carefully implemented.

**Comment by ZaricaDemoni** [comment]
Didn't realize a flag could be used for that, but yeah the confusion is the main concern here from me.

**Comment by esavier** [comment]
i think it would be hard to keep up with how much you need in terms of food to survive. Survival skill adjusting how much calories you think there are may ok-ish, but maybe some kind of indicator on your daily calories progress would be nice?

**Comment by Qrox** [comment]
Maybe we can relate the hunger indicator with recent caloric consumption? So if you are involved in heavy activity you feel hungry more intensely and more quickly, similar to how people eat more in real life after heavy activity.

**Comment by esavier** [comment]
> Maybe we can relate the hunger indicator with recent caloric consumption? So if you are involved in heavy activity you feel hungry more intensely and more quickly, similar to how people eat more in real life after heavy activity.

Theoretically good idea, i thought about it myself, but that would work weirdly with drinking/ingestion mechanic, since right now hunger is tied to how much volume of matter is inside player's stomach (i.e. you can water-drink yourself to fullness but no calories will be absorbed). That's why i think there should be some kind of separate indicator or at least something in status screen, unfortunately my English is not as exquisite as to know how to name those indicators.

**Comment by EvgenijM86** [comment]
Realistically speaking, if Cataclysm happened tomorrow I would know most of the kcal values, because I played Cataclysm before it became reality.

**Comment by Qrox** [comment]
That should be made into a new starting profession "C:DDA Guru"
