### ISSUE TITLE
Generic Guns: pistol is not accepting ammunition.

### ISSUE THREAD

**Issue by Torbenbeta** [CleverRaven/Cataclysm-DDA#42280]
# Describe the bug

The generic pistol 'defensive pistol' includes the magazine 'pistol magazine' which only accepts 9x19mm JHP munition, instead of  'Pistol ammo, JHP' which it ought to. Spawning in a loaded pistol magazine (15/15 9x19mm), loading it (which works) and trying to fire it, results in the message 'The defensive pistol can't be fired while loaded with incompatible ammunition 9x19mm JHP'. 

Further observations: 
Upon loading the save, the loaded magazine is unloaded. 
The sniper rifle has the same problem.
The antique pistol works fine.

On a maybe related note, trying to spawn in a AR pistol, Assault rifle +1, a pipe rifle or a pipe rifle .223 results in a null pointer.

Generic Gun magazines do not accept their generic munition.

# Steps To Reproduce
1. Make a player
2. Spawn in a defensive pistol or sniper rifle, plus their respective magazine and generic ammo.
3. Try to reload

# Expected behaviour

Defensive pistols should accept their ammunition. 

# Versions and configuration

 - OS:  Linux Mint 19.3
 - Game Version: 0.E-4254-gfea0266
 - Graphics version: Terminal
 - Ingame language: English
 - Mods loaded: dda, Generic Guns

**Comment by Hulkninja** [comment]
Having the same issue with the Mosin Nagant, and a similar one where a Marlin 38A permanently lost the capability to be reloaded after being modded. Removing the mods don't fix the issue.

Seems like guns, magazines, and/or reloading/firing in general is broken for a vast number of guns.

**Comment by esavier** [comment]
please check out if this is the same issue: #42161
