### ISSUE TITLE
Perpetual timeskip moving coffin

### ISSUE THREAD

**Issue by ZaricaDemoni** [CleverRaven/Cataclysm-DDA#42282]
# Describe the bug
Yeah I don't know what happened entirely other than the world file included in this (Jina the character) is now semi-unplayable after something went catastrophically wrong when trying to bury someone. When moving the coffin I noticed the contents spilled and at the same time it moved back onto the contents and an autosave happened. After constantly reloading the game and alt-f4ing, it eventually gave control back for me after a long time had passed

# Steps To Reproduce
I have no idea if this is repeatable

# Expected behavior
Not getting stuck passing seconds panicking until it eventual gives back control or you die.

# Versions and configuration

 - OS: 8.1
 - Game Version: 0.E-4254-gfea0266
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: "dda", "no_npc_food", "blazeindustries", "crt_expansion", "magiclysm", "DinoMod", alt_map_key", "MMA", "cbm_slots", "fuji_mpp", "speedydex", "stats_through_kills", "StatsThroughSkills"

 

# Additional context
(character again is Jina) Also, I do apologize for the number of edits, panicking, lack of sleep and caffine do not go well together when reporting a bug.

[Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4944668/Save.zip)

**Comment by UrbanCMC** [comment]
For reference, the character's save file (#SmluYSAjOTc4Mw==.sav) had a value of `-115848` for the `moves` field, which is the number of moves until the current activity is complete and the player regains control.

**Comment by ZaricaDemoni** [comment]
that's a lot of moves. given how far i had moved the coffin before this happened, I'm curious to what could have caused the massive spike. When I did get control back, it seemed to have resealed the corpse into the coffin as well.

**Comment by UrbanCMC** [comment]
Alright, looks like this is pretty easily reproducible. After resetting the `moves` field in the linked save file to 0:

1. Drag the coffin to the right. There's a huge pile of soil here, weighing > 2000 kg.
2. For some reason, everything on that field is put inside the sealed coffin.
3. Dragging the coffin now has an insane strength requirement of > 500 according to `game_furn_move` in game.cpp.
4. The game calculates the moves it takes to drag the coffin using `std::pow(str_req, 2.0) + 100`.
5. Have fun dragging for a couple of hours.

**Comment by ZaricaDemoni** [comment]
Must have grabbed a lot of items when the body fell out and I didn't see that. Well, that's definitely a nasty little bug.

**Comment by Alex-Folts** [comment]
I'm not sure what is happening, but i noticed some time ago when you drag stuff into tile where already almost no free space, it will throw exess stuff in neighbour tiles to prevent overflowing of the tile. Maybe when you drag coffin into tile full of dirt it trying do the same, but find coffin as storage where it could potentially put dirt and doing so fill it whole with dirt...

500 str require to lift 5 tons of mass when you modifying vehicle. 5 tons of dirt wont even fit in one tile, density of dirt  1.3kg/liter(1.3ton/tile). There is really something strange...

**Comment by anothersimulacrum** [comment]
Moving furniture should be converted to an activity, not just directly subtract moves.

**Comment by hexagonrecursion** [comment]
1. You move a coffin onto a tile that already has items on it
2. The contents of the coffin "fall out"
3. The items that were on the tile end up in the coffin

This all reminds me of a similar bug when dragging safes #35374
