### ISSUE TITLE
Migrate CRIT to use relic_data instead of artifact_data

### ISSUE THREAD

**Issue by KorGgenT** [CleverRaven/Cataclysm-DDA#42299]
# Is your feature request related to a problem? Please describe.
#42203 removes the old artifact code, and i noticed that CRIT is a perfect place to use relic_data for a variety of things. Artifact recharging isn't _quite_ implemented yet but should be fairly soon.

# Describe the solution you'd like
Update the json of all items that use artifact_data to use relic_data instead, according to the documentation here
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/ARTIFACTS.md
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/MAGIC.md#allowed-id-for-values

# Describe alternatives you've considered
deleting the items, doing it myself

# Additional context
@Soupster89 as you are the maintainer of the mod, it's probably good to get familiar with relic_data for any additions to CRIT in the future. Also i couldn't figure out your nickname on discord so i pinged you here.

**Comment by Maleclypse** [comment]
Working on Crit.  It looks like there is no equivalent of AEP_SAP_LIFE? I've left notes of what the old artifact code did especially in cases where there is no matching value such as recharging batteries.  I'll link the PR to this.
