### ISSUE TITLE
Sound Dampeners / Enhanced Hearing description issue

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#42293]
# Describe the bug

The Sound Dampeners description says that it will dampen sound slightly if turned on while Enhanced Hearing is activated, but activating Sound Dampeners deactivates Enhanced Hearing, and vice-versa. This means you only have incredible hearing or none, leaving out the possibility of having regular-ish hearing.

# Steps To Reproduce

Install Enhanced Hearing, See the Sound Dampeners description, see that they toggle as opposed to being able to be used simultaneously.

# Expected behavior

There should be three levels of hearing sensitivity here: Enhanced, where you can hear very very well when only EH is active, Deaf, when only SD is active, and normal+, when both are active. 

Or take out the description that says it's possible to have that middle option.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-4249-g70028b7 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Disable NPC Needs [no_npc_food],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs],
    No Fungal Monsters [No_Fungi],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm]
]

**Comment by Night-Pryanik** [comment]
The description of Sound Dampeners bionic was changed to `When this bionic is active, you can block hearing completely.`
