### ISSUE TITLE
Worn Bags and Backpacks Vanish when interacting with pets

### ISSUE THREAD

**Issue by Varg739** [CleverRaven/Cataclysm-DDA#42300]
Worn bags and backpacks vanish when interacting with pets

Either at random or whenever interacting with pet's inventory ("tie" and "untie" as well as "get all items") player-worn bags and backpacks vanish completely (nowhere to be found so assuming it just disappears entirely). The pet in question is my summoned Hunting Horror (got it in a Peculiar Shrine with a summoning item so im assuming its from a mod, though I do not know which one)

# Steps To Reproduce

1.have a bag with many items in it
2.have a friendly pet
3.attach a different bag to said pet
4.insert an amount of items into said pet's bag
5.tie/untie/load/unload the pet

# Expected behavior

the player's worn bag should disappear.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-3770-g879889a
 - Graphics version: deadpeople
 - Ingame language: english
 - Mods loaded: dda, disable npc needs, secronom, aftershock, arcana and magic items, blaze industries, c.r.i.t expansion mod, magiclysm, nechronica redux, whaleys collectables, dinomod, my sweet cataclysm, mythical martial arts, whaleys hair mod
 -->

# Additional context
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4947574/save.zip)

- note #1: you can drag and drop files in this issue post!
- note #2: it is very important for us that you provide a save file in case of a crash. It really helps the developers
    to reproduce the bug and fix it. If possible, try to provide a save file that occurs in the right conditions, just
    before the crash happens. -->

**Comment by andrei8l** [comment]
This should have been fixed in https://github.com/CleverRaven/Cataclysm-DDA/pull/42077. Can you try with a newer build? I wasn't able to reproduce your bug in a quick test
