### ISSUE TITLE
 #41877 broke warmth of body parts

### ISSUE THREAD

**Issue by sztosz** [CleverRaven/Cataclysm-DDA#42302]
Body warmth, especially arms and torso, is being reduced when you were some clothes over it, while it should increase

# Steps To Reproduce

1. Load save. 
2. Make a move
3. Observer Torso warmth, it's way below zero.
4. Take off Flannel Jacket (or any other item on torso, like ruscksack or vest)
5. Observer Torso warmth, it increases instead of decrease.

# Expected behavior

Wearing clothes over torso should increase warmth in short (it's not a bug about proper insulation from heath and cold after all)

# Versions and configuration

Any version after https://github.com/CleverRaven/Cataclysm-DDA/pull/41877/commits

# Additional context

https://drive.google.com/file/d/1sjPB3I7CScXjxX0hVFKi0hzgEdDnWKDU/view?usp=sharing

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/my-torso-and-arms-warmth-drops-to-insane-levels-after-loading-a-save/24201/6

**Comment by Fris0uman** [comment]
So it's because drench_capacity is set to 1 for every limb, you have 6 wetness on the torso, this leads to 600% wetness which makes you very cold.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/my-torso-and-arms-warmth-drops-to-insane-levels-after-loading-a-save/24201/8
