### ISSUE TITLE
Can no longer dissasemble toolbox

### ISSUE THREAD

**Issue by ZaricaDemoni** [CleverRaven/Cataclysm-DDA#42305]
# Describe the bug
After the recent addition of disassembly recipes, it seems to have broken the toolbox preventing it from being dissembled.

# Steps To Reproduce
May be an old world related issue before update? if not skip step 2, and just grab toolbox on newer version.
1 grab a toolbox in previous version. (before 10854)
2 load the game in newer version. (10854 or newer)
3 get told recipe for toolbox is invalid (seen in screenshot)
4. Can no longer deconstruct the toolbox if you needed too for whatever reason or found a spare you wanted to take apart for nails.

# Expected behavior

# Screenshots

Invalid error
![image](https://user-images.githubusercontent.com/32645137/87945358-7740fc80-ca55-11ea-93a4-a0bac3e45524.png)

No disassemble mention. it also doesn't appear in disassemble menu.
![image](https://user-images.githubusercontent.com/32645137/87945273-60020f00-ca55-11ea-93f4-d73d89b4bc40.png)

# Versions and configuration

<!-- Please complete the following information; you can now go to:
    - "Main menu (ESC) > Debug Menu > Info > Generate game report" to generate this report.
    - Please update your OS version with a more precise version.

 - OS: Windows 8.1
 - Game Version: 0.E-4297-g3c67e80

 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: "dda", "no_npc_food", "blazeindustries", "crt_expansion", "magiclysm", "DinoMod", alt_map_key", "MMA", "cbm_slots", "fuji_mpp", "speedydex", "stats_through_kills", "StatsThroughSkills"
 

# Additional context
Debug for error if needed. (there is also 2 other errors that i myself am responsible for, by changing some ingame colors that may be in this debug, if anyone would kindly tell me how to fix them that would be appreciated as well. Had to change green to a brighter green due to semi-colorblind making darker greens hard to see on black which caused them)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4948080/debug.log)

**Comment by Alex-Folts** [comment]
I think its related to this PR https://github.com/CleverRaven/Cataclysm-DDA/pull/42181

**Comment by ZaricaDemoni** [comment]
so possibly not related to the new recipe additions. stretched thin this morning so wasn't able to fully check all 3 builds right now.

**Comment by Hulkninja** [comment]
So basically, toolboxes just got nerfed into being generic containers..?

Damn.

**Comment by KorGgenT** [comment]
i believe a good solution for this is to add an "unpack" action to the now obsolete toolbox. We can also add some other varieties of toolbox now that are larger and can contain more.

**Comment by ZaricaDemoni** [comment]
More variants would be nice, as the only other one right now is the workshop toolbox. this toolbox contains all of the same items as the old one, plus a clamp and pinreamer, and is the same size as the current new container, but weighs more.

**Comment by misterprimus** [comment]
Seems like with the new nested containers system, toolboxes really should just be generic containers with roughly enough space to accommodate the tools they used to contain. Earlier "toolboxes" were abstractions needed only because we *didn't* have nested containers.

**Comment by anothersimulacrum** [comment]
Relevant: #42181
