### ISSUE TITLE
Brass Catcher Does Not Actually Collect Spent Rounds

### ISSUE THREAD

**Issue by BrokenPaw-0-1** [CleverRaven/Cataclysm-DDA#42313]
# Describe the bug
No crash or error report or any message here really, but I've noticed that the brass catcher does not actually collect the casings that are fired from a firearm. Specifically, I have been using a reclaimed M16A4 with 5.56 NATO M855A1. I have fired probably over 1000 rounds with this gun and have had the brass catcher on for most of those, yet I have seen none of those rounds appear in my inventory or the brass catcher. I even disassembled it thinking I was just being dumb, but the only items yielded from the disassembly were rags and thread. There's no bullet casings to be found. I'm not sure where they are going.

# Steps To Reproduce
1) Get firearm.
2) Put brass catcher on firearm.
3) Shoot the bad guys.
4) The casings are nowhere to be found??

# Expected behavior
Spent casings to be located in the player inventory or brass catcher or to appear on the ground or player inventory upon disassembly of the brass catcher.

# Screenshots
n/a

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-4297-g3c67e80 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Alternative Map Key [alt_map_key],
    My Sweet Cataclysm [my_sweet_cataclysm],
    No Fungal Monsters [No_Fungi],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context
n/a

**Comment by Hulkninja** [comment]
Guns in general seem to be rather broken currently. Especially in relation to ammo/reloading/modding.

There are a couple of similar issues on here, if you want to find out some more.
Basically, mods don't always work, or they break the guns so they can't be used, or the guns can't be used regardless of mods, or they won't fire ammo they should be able to fire, etc. etc.

**Comment by BrokenPaw-0-1** [comment]
> 
> 
> Guns in general seem to be rather broken currently. Especially in relation to ammo/reloading/modding.
> 
> There are a couple of similar issues on here, if you want to find out some more.
> Basically, mods don't always work, or they break the guns so they can't be used, or the guns can't be used regardless of mods, or they won't fire ammo they should be able to fire, etc. etc.

Thanks for the heads up... I guess I'll try to be careful and save-scum to get around goofy BS.
