### ISSUE TITLE
Endless Aiming

### ISSUE THREAD

**Issue by Bulletfang** [CleverRaven/Cataclysm-DDA#42318]
# Describe the bug
Character was stuck in auto-aim until frostbite set in, which took a long time.
I found myself in a state of aiming that was uninterruptible, mashed every button on my keyboard in a wild panic, see screenshot for the exact positioning of actors (various manhacks, their dispenser vehicles and the player character). It went as following:

# Steps To Reproduce

1. Stand in the doorway to a Barracks in a Lab, where there are 2 manhack spawning enemies.
2. Aim at a manhack that emerges from one of the two Northtrop manhack dispenser enemies (it was the riot control version in my case. though it still dispensed C4 and Grenade hacks, feel like that stuff doesn't belong in a non-or-less-lethal unit?) (the most precise aim option was used, I should mention).
3. When you are still aiming and a new manhack is spawned, ignore the prompt you are given to stop aiming.
4. Player character never reaches full steadiness, dispensers keep spawning manhacks until their limit is reached, process of aiming can't be interrupted by any means.

This happened to me in an ice lab (on the first level, so it wasn't too cold and my character had just entered the lab and was still comfortable (falling) when it happened), and my character aimed until he got a hurt prompt that was caused by frostbite, none of the manhacks, flashbang hacks, grenade hacks, C4 hacks, etc ever put a scratch on me. It might've been that the first few manhacks in front of me were retreating as manhacks do, but couldn't get far away to trigger their attack pattern because they were blocked in by the mountain of other manhacks.

# Expected behavior

Not sure, as this seems like a pretty convoluted bug, maybe add a time limit that the player character can spend automatically aiming, then give him a prompt that he's not making any progress in getting the target into his crosshairs or something like that. The steadiness meter went up and down like a wild rollercoaster, but never managed to reach the max, which was needed to fire.
Or just make the auto-aim interruptable with 5 like crafting and other activities. Normally you don't see this mode much since it takes less than a second (irl) to auto-aim and fire but I was stuck in that mode for about 60 irl seconds.

# Screenshots

![Untitled](https://user-images.githubusercontent.com/45204409/87986798-e104e900-cadd-11ea-89ee-586ce39973d6.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-4226-g1ea5556 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Bionic Slots [cbm_slots],
    Blaze Industries [blazeindustries]
]

# Additional context

My character got away by running about 20 tiles back to the exit at 34 speed, somehow none of the explosive manhacks triggered as I ran, not sure if this means anything since I don't know the exact behavior of manhacks apart from that hit-and-run strategy they employ. I very strongly feel like if any manhack had triggered I would've lost my character, and I also feel like they should've triggered, given the situation, they were kinda hugging me for many in-game minutes.

**Comment by Vorlent** [comment]
I've encountered this problem a few weeks ago while I was fighting a huge swarm of fungaloids with a short bow near a river. It was pretty consistent and I had to forcibly close the game a dozen times.
