### ISSUE TITLE
Empty Guns that can take speed loaders break either on spawn or when reloading from save.

### ISSUE THREAD

**Issue by MatJone** [CleverRaven/Cataclysm-DDA#42324]
Empty guns that would load from speed loaders become unable to be reloaded after spawning or reloading save.
So far applies to build #10852+

# Steps To Reproduce

From spawning.
1. Spawn or find say an sks that is not loaded.
2. Attempt to reload it either through stray rounds or loaded speed loader.
3. Get errors (see screenshots), get message saying "Can't reload the sks."

From save loading.

1. Spawn or find say an sks that is loaded.
2. Either unload or fire gun until empty.
3. Save and quit.
4. Reload save.
5. Get errors from 3. from spawning.

# Expected behavior

When finding or reloading a save with an empty gun that can accept speed loaders you should be able to reload them with either loose rounds or loaded clips.

# Screenshots

![Screenshot (3)](https://user-images.githubusercontent.com/49188917/88000254-13005600-cab2-11ea-8e9b-2317ca8f21b9.png)

![Screenshot (1)](https://user-images.githubusercontent.com/49188917/88000275-1abffa80-cab2-11ea-9439-bb66443eecad.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-4254-gfea0266 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Crazy Cataclysm [crazy_cataclysm],
    Mythical Martial Arts [MMA],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

Tests in later builds only had the base game and the no NPC needs mods.
Testing has so far only been done with marlin 39a, mosin-nagant 1891/30 and sks but issue is presumed for all guns with internal magazines and speed loaders

**Comment by esavier** [comment]
maybe related:  #42161 and #42280

**Comment by kevingranade** [comment]
Might be related to #45705

**Comment by MatJone** [comment]
This issue has been resolved by merging of #44235
