### ISSUE TITLE
Heating water with pot action menu doesn't clean water.

### ISSUE THREAD

**Issue by NotHereCDDA** [CleverRaven/Cataclysm-DDA#42322]
# Describe the bug

Heating up a pot of water doesn't clean the water. Crafting clean water in the craft menu still does though.

# Steps To Reproduce

1.Find a pot
2.Fill pot with water
3.Activate the pot near fire and choose the water

# Expected behavior

Water should become "clean water"

# Versions and configuration

Build 10856
No mods

**Comment by Qrox** [comment]
Maybe heating only heats the water to below-boiling temperature which is not enough to clean the water?

**Comment by NotHereCDDA** [comment]
As a new player i see no reason to have it act like that unless there is a mechanical purpose to it. Why give the option to heat it like that if it doesn't produce any result? Unless there is some use for non-clean hot water it just seems pointless being there and frustrating for newer players that don't know how to use the crafting menu yet. More ways of doing the same thing lets people choose what works for them. That said, if it is intentional, then it's intentional and i will just deal :P

**Comment by andrei8l** [comment]
> As a new player i see no reason to have it act like that unless there is a mechanical purpose to it.

Some foods and drinks are more enjoyable while hot (`EATEN_HOT` flag - it's also mentioned in the item info). You can also heat up things if they're frozen. This isn't a bug

**Comment by NotHereCDDA** [comment]
That's expected behavior. It just seems odd that heating water doesn't actually do anything. But if it's intentional like i said, i will just deal i guess. gonna go ahead and close this one.
