### ISSUE TITLE
Error messages from automated turret on vehicle

### ISSUE THREAD

**Issue by Bulletfang** [CleverRaven/Cataclysm-DDA#42325]
# Describe the bug
Setting a vehicle mounted gun to fire automatically results in several error messages when firing. It's not game breaking and the gun still damages enemies. This problem didn't exist when a turret control unit was not required for letting a gun fire automatically.

# Steps To Reproduce

1. Install turret control unit on a vehicle mounted gun. (I used XM34 EMP projector)
2. Set gun to fire automatically.
3. See several error messages when it fires.

# Expected behavior

No error messages. The error messages are really just a mild inconvenience, as everything appears to function correctly if you choose to ignore them.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-4226-g1ea5556 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Bionic Slots [cbm_slots],
    Blaze Industries [blazeindustries]
]

# Additional Info

Edit:
It's not just when firing, this pops up constantly when the turret is active:
![Untitled](https://user-images.githubusercontent.com/45204409/88012455-36f78200-cb1a-11ea-9877-fd469960f840.jpg)

**Comment by Fris0uman** [comment]
The "Solution" Is to find where in the code the fake turret NPC is made and use set_body() to give it a body, with at least an arm in it, but a full body would do.

**Comment by Night-Pryanik** [comment]
Fixed by #44026.
