### ISSUE TITLE
DEBUG    : error: tried to put an item into a pocket that can't fit into it while loading.  err: holster does not accept this item type

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#42321]
# Describe the bug

 DEBUG    : error: tried to put an item into a pocket that can't fit into it while loading.  err: holster does not accept this item type

 FUNCTION : void item_contents::combine(const item_contents&)
 FILE     : src/item_contents.cpp
 LINE     : 305

# Steps To Reproduce

was just driving

# Versions and configuration
10852

**Comment by KorGgenT** [comment]
attach a save please?

**Comment by matt32106** [comment]
sorry cannot reproduce, if only bug reports were automated...
