### ISSUE TITLE
Some sort of hint for Handbrake

### ISSUE THREAD

**Issue by NotHereCDDA** [CleverRaven/Cataclysm-DDA#42330]
# Is your feature request related to a problem? Please describe.
I found out about this feature completely by accident. From what i can tell it isn't mentioned anywhere? 

# Describe the solution you'd like
Some sort of hint that it exists or menu choice to use the handbrake so that it is well known. Drifting cars seems so much fun and it feels almost criminal that it's not mentioned anywhere ingame (That i could find so far, so apologies if it is clear and I'm just being dumb again lol)

**Comment by Qrox** [comment]
See #42086.
