### ISSUE TITLE
Body temperature overflow

### ISSUE THREAD

**Issue by SteelIndustries** [CleverRaven/Cataclysm-DDA#42339]
# Describe the bug

Character with grey fur mutation wearing any clothes with warmth value during the summer results in the character having freezing body temperature.

# Expected behavior

Body temperature increases when wearing clothes.

# Screenshots

![Screenshot (1)](https://user-images.githubusercontent.com/68602103/88068959-0e639c80-cb9b-11ea-9398-cebbe6041c8f.png)
![Screenshot (2)](https://user-images.githubusercontent.com/68602103/88068952-0c014280-cb9b-11ea-88bd-d5f8f1aa8b06.png)
![Screenshot (3)](https://user-images.githubusercontent.com/68602103/88068958-0dcb0600-cb9b-11ea-930f-9a74964e45d2.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-4309-gb81636e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Graphical Overmap [Graphical_Overmap],
    Mutant NPCs [mutant_npcs],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    No Rail Stations [No_Rail_Stations],
    No Acid Zombies [No_Acid_Zombies]
]

# Additional context

**Comment by sztosz** [comment]
Some comments here https://discourse.cataclysmdda.org/t/my-torso-and-arms-warmth-drops-to-insane-levels-after-loading-a-save/24201/10 My conclusion is that's because of dealing with wetness has some bug in it.
