### ISSUE TITLE
Game fails to load, crash on exit

### ISSUE THREAD

**Issue by Tr-T** [CleverRaven/Cataclysm-DDA#42334]
After upgrading from10852 to 10859 save fails to load, the following error message is displayed, followed by a segmentation fault crash on quitting game:

 DEBUG    : Error: data/mods//dda/../../json/mapgen_palettes/house_general_palette.json: line 73:13: duplicate entry in json object

      "Ø": "f_pinball_machine",
      "Æ": "f_arcade_machine",
      "∞":
            ^
             "f_foot_locker",
      "≠": "f_chest",
      "ʭ": "f_ladder"

 FUNCTION : bool main_menu::load_character_tab(bool)
 FILE     : src/main_menu.cpp
 LINE     : 1159

# Steps To Reproduce

1. Try to load game from version 10852
2. Try to quit from main menu.

# Expected behavior

Game loads

# Screenshots

# Versions and configuration

10859

Mods:
-NPC Needs Disabled
-Alternative Map Key

# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4953002/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4953003/debug.log)
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4953009/save.zip)

**Comment by ZhilkinSerg** [comment]
Fixed in https://github.com/CleverRaven/Cataclysm-DDA/commit/a3e5f3250059c9019372dbe8f2c11707d119c9c1
