### ISSUE TITLE
Blobs and Slimes completely broken

### ISSUE THREAD

**Issue by Bulletfang** [CleverRaven/Cataclysm-DDA#42346]
# Describe the bug
Blobs and Slimes all fight each other endlessly, completely ignore the player until he moves into melee range.

# Steps To Reproduce

1. Play latest update. (see Versions and Configurations)
2. Witness the slime civil war.

# Expected behavior

Blobs don't fight each other.

# Screenshots

![sli](https://user-images.githubusercontent.com/45204409/88088863-61355800-cb8b-11ea-9cc0-812ae112ee23.jpg)

![sli2](https://user-images.githubusercontent.com/45204409/88089076-b70a0000-cb8b-11ea-9eb7-c5af26cb6dc1.jpg)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-4329-ga3e5f32 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Bionic Slots [cbm_slots],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm]
]

**Comment by matt32106** [comment]
could be linked to #42342? if there is something wrong with the faction...
