### ISSUE TITLE
Marlin 39A Loading Bug

### ISSUE THREAD

**Issue by Hillanoko** [CleverRaven/Cataclysm-DDA#42340]
# Describe the bug

Cant load the Marlin 39A

# Steps To Reproduce

Get a Marlin 39A
cant be reloaded via single bullet nor speedloader

# Expected behavior

Normally reloadable single loading 19 Round 22LR chamber that can be loaded either single bullet or via speedloader.
neither works atm

# Screenshots

![bugbug2](https://user-images.githubusercontent.com/67777885/88073147-270d8b80-cb76-11ea-82eb-6495001b38b0.png)
![bugbug](https://user-images.githubusercontent.com/67777885/88073151-283eb880-cb76-11ea-96b2-afed4add10fa.png)

# Versions and configuration

Newest Experimental
Tiles
Windows 10
English

# Additional context

-

**Comment by Hulkninja** [comment]
I had this EXACT SAME bug, but what's even weirder is, my Marlin worked fine for a long while. Even managed to take out about a dozen zombies with it, if not more. After I fully unloaded the thing and put a couple of mods on it, the thing broke, permanently.

Guns are broken in current experimental. They're also seemingly one of the most complex things to fix, if I'm not totally mistaken.

My Marlin has been broken for quite a few updates though, so whatever's causing it wasn't recently introduced. It's at least 6-7 builds old, likely older still.

**Comment by qurvax** [comment]
Can confirm that in the latest build (10918) this issue also affects M1903 Springfield, but does not affect M1 Garand.

**Comment by souricelle** [comment]
I ran into a similar issue with a Mosin Nagant on  0.E-4811-g90e0c8b [64-bit]. An NPC spawned with an empty Mosin that couldn't be reloaded, then I debug spawned one that I could reload and successfully fire, but I'd get this message every time:

 DEBUG    : Unexpected shortage of ammo whilst firing Mosin-Nagant 1891/30

 FUNCTION : int player::fire_gun(const tripoint&, int, item&)
 FILE     : src/ranged.cpp
 LINE     : 794

**Comment by digitCruncher** [comment]
As far as I can tell, there is no save associated with this bug report. Here is my save with the same problem with an SKS that spawned with a clip. I unloaded the clip to attach the shoulder strap, but after that there was no way I could find that would allow me to reload the gun.

[Richmond Highlands.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5152591/Richmond.Highlands.zip)

Reproduced with build 10967

**Comment by wapcaplet** [comment]
Per issue #44228, this problem appears directly caused by attaching a mod to the gun.

1. Load game
2. Give self shoulder strap and Marlin 39A
3. Apply shoulder strap to gun
4. Try to reload the gun - fails, because it now has no internal magazine
