### ISSUE TITLE
Survivor headlamp does not work when converted to UPS 

### ISSUE THREAD

**Issue by ektoplazm** [CleverRaven/Cataclysm-DDA#42349]
# Describe the bug
Survivor headlamp does not work when converted to UPS power source, the non-converted option (with a light battery) works fine
# Steps To Reproduce
1. Spawn a survivor headlamp
2. Convert it to UPS
3. Activate the headlamp 
4. The headlamp is shown as activated, but there does not actually become a light source

# Expected behavior
The headlamp works

# Screenshots
![image](https://user-images.githubusercontent.com/60448096/88099682-30ade800-cba4-11ea-88f0-78c0c0547a30.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-4329-ga3e5f32 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations],
    Alternative Map Key [alt_map_key]
]

# Additional context

**Comment by andrei8l** [comment]
Part of the reason is that the UPS mod doesn't add a battery well. I've solved that issue but noticed that `player::process_items` is actually a mess so I'm trying to simplify that. You can use the commit above in the meantime
