### ISSUE TITLE
DEBUG    : invalid monfaction id blob

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#42342]
# Describe the bug

 DEBUG    : invalid monfaction id blob

 FUNCTION : int_id<T> string_id<T>::id() const [with T = monfaction]
 FILE     : src/monfaction.cpp
 LINE     : 49

# Steps To Reproduce
load save

# Versions and configuration
10860
- OS: Linux
    - OS Version: LSB Version: core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch; Distributor ID: Ubuntu; Description: Ubuntu 18.04.4 LTS; Release: 18.04; Codename: bionic; 
- Game Version: 0.E-4329-ga3e5f32 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context
[Uploading save.zip…]()
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4954785/debug.log)

**Comment by anothersimulacrum** [comment]
Please fill out the template. The versions and configuration info is entirely lacking, and would be very helpful in figuring this out.

**Comment by matt32106** [comment]
Why can't this be automatic?

**Comment by Hulkninja** [comment]
> Why can't this be automatic?

Why can't you fill out the template?

But yeah, I'm having this issue as well, in the latest experimental build. My guess is it has something to do with the recent name change of "blobs" into "slimes": #42287

**Comment by kevingranade** [comment]
My guess is that we need to migrate the faction string here https://github.com/CleverRaven/Cataclysm-DDA/blob/c876885a3a750df20611c80524aa254b5f0e2a1b/src/savegame_json.cpp#L2047

**Comment by ZhilkinSerg** [comment]
Also change occurrences of `species_BLOB` (and its definition) with `species_SLIME`, e.g.:

```
  C:\Projects\Cataclysm-DDA\src\monattack.cpp  (4 hits)
	Line 150: static const species_id species_BLOB( "BLOB" );
	Line 150: static const species_id species_BLOB( "BLOB" );
	Line 2395:         if( z->get_speed_base() > 40 && othermon.type->in_species( species_BLOB ) ) {
	Line 2453:         if( candidate.type->in_species( species_BLOB ) && candidate.type->id != mon_blob_brain ) {
```
