### ISSUE TITLE
Can't bleed out, Can't Succumb to infection, Can't keep limbs broken

### ISSUE THREAD

**Issue by NotHereCDDA** [CleverRaven/Cataclysm-DDA#42359]
Bleeding out just makes it so that i can't move. I don't die. Infection let's me move but refuses to claim my life. Limbs refuse to stay broken.

# Steps To Reproduce

inflict these onto your character till they should die. And try to break a leg for a full day.

# Expected behavior

Death or limbs taking longer to heal

# Screenshots

![WTF](https://user-images.githubusercontent.com/66968118/88119519-bf176f00-cb8e-11ea-8e1a-9f09a89beaad.PNG)

# Versions and configuration

Build 10860

# Additional context

[Pleasant View.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4957107/Pleasant.View.zip)

**Comment by I-am-Erk** [comment]
I have no mouth, and I must scream

**Comment by Fris0uman** [comment]
Looks like https://github.com/CleverRaven/Cataclysm-DDA/issues/42041 but with some extra stuff.
That's very weird because dying from infection sets all your limbs to 0 but here they're set to 1, what happens if you only have the infection?

**Comment by Fris0uman** [comment]
So bleeding to death and the thing about breathing both set your torso hp to 0, dying from infection sets all your parts to 0 and yet in this save all your parts are stuck at 1Hp for some reason.

**Comment by NotHereCDDA** [comment]
this isn't the first time it happened. it's not a problem limited to this save file
