### ISSUE TITLE
Zombie resurrection cleans items.

### ISSUE THREAD

**Issue by Cynthius** [CleverRaven/Cataclysm-DDA#42353]
# Description:

When a zombie resurrects on the same tile as any filthy items, all filthy items are reset to a "clean" state.

# Steps To Reproduce:

Kill a zombie, confirm that it's dropped filthy items. Leave it there until it resurrects. Congrats! You've invented the world's first Zombie Launder!

# Versions and configuration:

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-4329-ga3e5f32 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded:
   - Dark Days Ahead [dda],
   - Disable NPC Needs [no_npc_food]

**Comment by hexagonrecursion** [comment]
Could not reproduce.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: f50b6be [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by anothersimulacrum** [comment]
Very old, and no reproduction
