### ISSUE TITLE
Zombull balance

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#42358]
# Describe the bug
The zombull, added in #42159, has a few balance issues, and I didn't review the PR in time to catch this stuff.

It is a game-start level zombie, ie. it does not evolve but can be encountered on day 1, with higher melee damage than a skeletal juggernaut (SJ is 3d6 at skill 5, ZB is 4d6 at skill 6), equal to a zombear. It has a speed of 150, substantially faster than a migo or zombear (120 for comparison) and thus cannot be escaped by a player and will make those high power attacks more frequently than any of the creatures listed for comparison. It has a higher bash/cut armour than a zombear or antlered horror, and HP equivalent to an antlered horror, which should be at least 50% larger. Plus it has a smash attack.

# Expected behavior
I realize this is a rare zombie encounter, but these stats are out of line, particularly in a zombie that once encountered cannot even be fled. It isn't fun game design to explore a farm and suddenly and inescapably die.

We should avoid power creep in game-start level zombies. A zombie bull would be similar to or less dangerous than a zombie moose. Some of the proposed speed and damage could be represented with some kind of CHARGE special, which would be a cool thing to have, but should have a cooldown and probably require some open space to work. As it stands this creature is substantially more deadly in every metric to any other game-start zombie and would hold its own against many late-stage evolved zombies.

# Additional context
In reviewing this I noticed that we could use an audit of the weights of a lot of zombie animals, the zombie moose is bizarrely listed as weighing 125 kg.

Also the zoose has an aggression of 50, I'm not sure why that would be.

**Comment by Night-Pryanik** [comment]
>It has a higher bash/cut armour than a zombear or antlered horror, and HP equivalent to an antlered horror, which should be at least 50% larger.

Being larger doesn't mean it should have more HP; being massive, in my opinion, justifies having high HP and high armor. Quick googling reveals that moose bulls weight 540 kg on average, male bears weight 150 kg on average, while cattle bulls weight 750 kg on average. Cattle bulls are way larger than these animals, thus zombulls have more HP and more armor.

Ok, maybe we should reduce its speed to 120 and maybe we should restrict its spawn to day 72 (like zombear or zoose) to make it less deadly. But I think its other features are fine and don't need nerfing.

Also I personally don't see nothing wrong in having a very deadly enemy right from the game start, especially if it spawns rather rarely and only in one location.

Also I wouldn't consider this issue as a _bug_ that require fixing.

**Comment by I-am-Erk** [comment]
Reducing the spawn to match the zombear would be a good start, but I still think having a bull doing multiple goring attacks per second is way over the top for a bull.

**Comment by Amoebka** [comment]
> Also I personally don't see nothing wrong in having a very deadly enemy right from the game start, especially if it spawns rather rarely and only in one location.

Very deadly is fine, inescapable isn't. Only one spawn location doesn't change anything, a new player wouldn't know where that is. One can reasonably assume something like a secret underground lab is dangerous, farm seems like it should be safe.

**Comment by Night-Pryanik** [comment]
We have several other monsters which could be considered inescapable: zooses, mi-gos and some others. And they spawn almost anywhere, including places which player could think of as safe.

**Comment by GGgatherer** [comment]
> Quick googling reveals that <...> male bears weight 150 kg on average

Where did you find that number? Wikipedia says 180/135kg(m/f) on lower side, and 217/152 as worldwide average. Granted, that's including polar bears but still, 150kg seems too low.

**Comment by Night-Pryanik** [comment]
I used black bear as a reference. Wikipedia says `Adult males typically weigh between 57–250 kg (126–551 lb), while females weigh 33% less at 41–170 kg (90–375 lb)`.

**Comment by GGgatherer** [comment]
Well, I thought about grizzly bears which are definitely [bigger](https://en.wikipedia.org/wiki/Grizzly_bear#Appearance) than that, but it turns out there are (almost?) no grizzlies in New England :(

**Comment by cainiaowu** [comment]
Are we really want to bring back the good ol day 1 tankbot? IIRC one bad design doesnt justfy other one to exist.

**Comment by I-am-Erk** [comment]
Mi-go are right at the upper limit of what's reasonable to see on day 1, and that's pushing it. This thing is presently much harder to escape and much more aggressive. You have quite a long time to look at a mi-go and decide to walk the other way before it hacks you to pieces

**Comment by Night-Pryanik** [comment]
> one bad design doesnt justfy other one to exist.

I agree, but the thing is that I personally don't consider having deadly monsters right from the start as "bad design".

**Comment by nexusmrsep** [comment]
Maybe a poor eyesight / vision range for the zombull could be a balancing factor? So it would still be strong but wouldn't notice you across the map. Other way would be making it have a special attack where instead of instantly charging it woud first prepare the charge, give a warning by scraping the ground with it's hoof? Or make it respect the fences? I'm aware some of those ideas fit more for a living bull rather then undead one, but still worth considering. 

Strong enemy day 1 is not necessarily a problem. In this case however a strong living animal would be restricted in its movement and still trapped after zombification. Think a lion in a zoo. Perhaps simply put it behind metal fencing or something and let the player decide if they are cocky enough to let it free.

**Comment by EvgenijM86** [comment]
@cainiaowu I would absolutely love to see day 1 tankbot - that was a lot of fun and presented unique challenges and opportunities (like making it fight a crowd zombies by leading them into each other with noise). And it makes no sense for robots to become stronger with time.
