### ISSUE TITLE
Feet always cold nomatter the warmth when you are wet

### ISSUE THREAD

**Issue by MikuMiddo** [CleverRaven/Cataclysm-DDA#42364]
# Describe the bug
The feet always feel cold and evently become frostbite nomatter how many warmth you have on feet.

# Steps To Reproduce
1. start at winter
2.wear warmth enought on feet
3.get yourself wet
4.stand out side wait hours
5.see the "warmth" at "@"menu
6.use towels to dry yourself up
7.see the "warmth" at "@"menu,it becomes normal

# Expected behavior
It should have normal warmth when you get wet.Even if you get wet,you shouldn't have a frostbite due to it.

# Screenshots
![TORLNII`LAB }Y} $I~7 Y](https://user-images.githubusercontent.com/53809752/88123452-7ea30a00-cbfd-11ea-9daf-f65401590e5a.png)
![OM GKO`J6M FN~E5C7WSYY](https://user-images.githubusercontent.com/53809752/88123461-8367be00-cbfd-11ea-9cd3-aa670b29d9cc.png)
![J9A@HD6ZE_ONGC~B@$6JKGD](https://user-images.githubusercontent.com/53809752/88123467-8498eb00-cbfd-11ea-94dc-ed800814519b.png)
![image](https://user-images.githubusercontent.com/53809752/88128153-e52d2580-cc07-11ea-98ad-91105ce5aadf.png)
![image](https://user-images.githubusercontent.com/53809752/88128165-eb230680-cc07-11ea-91fa-d1c123cc1008.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-4329-ga3e5f32 [64-bit]
- Graphics Version: Tiles
- Game Language: 系统语言 []
- Mods loaded: [
    浩劫余生 [dda],
    禁用NPC需求 [no_npc_food],
    C.R.I.T 扩展 [crt_expansion],
    Blaze 载具工业 [blazeindustries],
    大魔法 [magiclysm],
    余波未尽 [aftershock],
    恐龙世界 [DinoMod],
    Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
    疯狂大灾变 [crazy_cataclysm],
    神话武术 [MMA],
    移除真菌类怪物 [No_Fungi],
    Fuji的军事职业Mod [fuji_mpp],
    技能提升属性 [StatsThroughSkills],
    敏捷速度加成 [speedydex],
    杀怪提升属性 [stats_through_kills],
    余震个人用强化模组 [After_Shock_Personal_UsageMod],
    无限手套 [Infinity_Gauntlet]
]

# Additional context
debug.log is too big to upload

**Comment by moxian** [comment]
Sounds like #42302 
Try updating to the latest version and see if it helps.

**Comment by Bulletfang** [comment]
Check if your character is wet, if so, making him dry himself off with a towel might circumvent the bug.

**Comment by MikuMiddo** [comment]
> Sounds like #42302
> Try updating to the latest version and see if it helps.

actually it's the latest version

**Comment by MikuMiddo** [comment]
> Check if your character is wet, if so, making him dry himself off with a towel might circumvent the bug.

It works,I will change the issue to report the bug

**Comment by ZaricaDemoni** [comment]
#42309 seems to have not fixed the issue properly but #42347 should when it is released hopefully.

**Comment by Fris0uman** [comment]
Is it still happening? Should be fixed now

**Comment by zanraptora** [comment]
Can confirm still happening on the most recent build

Another strange detail: The more warmth I added, the worse the chilling effect got: Throwing on a blanket put the temperature delta at a balmy blue -150.

Toweling off solved the problem.

**Comment by Fris0uman** [comment]
Can you provide a save?

I think part of the bug was due to drench_capacity and that's fixed but there might be another thing where wetness is unbound and can stack infinitly maybe #42422
