### ISSUE TITLE
Trading interface needs improvement.

### ISSUE THREAD

**Issue by Cynthius** [CleverRaven/Cataclysm-DDA#42363]
# Is your feature request related to a problem? Please describe.
The trade interface is currently extremely user-unfriendly, with controls that lack standard features found in every other menu in the game (save the chat interface). Every item is displayed separately, and can only be selected with letters. Selecting an amount like in the drop menu is not supported, so to sell 50 rags you must a,b,c,d 50 times, along with changing pages, and charge items like thread can only be sold all or nothing. Having identical items displayed separately makes navigating the list cumbersome as well, filling entire pages with every instance of a single item. Inventory capacity is only shown for one party in the trade, which leads to purchases of more than can be carried. Currency items in a trade have to be selected manually, with no automatic suggestion/balance feature, using the same item-by-item selection previously mentioned.

# Describe the solution you'd like
The biggest improvement would likely come from consolidating identical items into a single (numbered) listing and enabling amount selection, including for "charge" items. Secondary to that would be controls more in-line with the rest of the game's current menus. A capacity readout could be put over the other party's tab as well, mirroring the existing layout on the left side. A "balance trade" feature, while convenient, isn't really necessary, but could work by filling out the trade with whatever currency item the player chooses, up to the value of the offer, with a prompt before finalizing the trade. Or it could just be a "select->balance deal with item" function instead.

**Comment by esotericist** [comment]
anyone tackling this should also probably be aware of #44449 since if you're fixing the npc trade UI, you're probably refactoring the NPC trade initialization anyway.

**Comment by DericHuynh** [comment]
those people should also be aware of #45436
