### ISSUE TITLE
Zombie blood loss deaths caused by your weapons don't count as kills by you

### ISSUE THREAD

**Issue by Captain-Fwiffo** [CleverRaven/Cataclysm-DDA#42367]
I noticed a zombie child bleeding out while in combat with me didn't give me a morale hit. I tested letting fat zombies bleed out from wounds caused by my spear, and when they bled out, they didn't increment the "Fat zombie" kill counter.

Thus the bug doesn't count blood loss kills as kills.

1. Attack zombie until near death.
2. Wait for blood loss to take its course.

Expected behavior

Zombies with blood loss caused by you should count as kills by you. Perhaps if you wounded them in the last 5 minutes, or if you got them down a certain percentage, it would count as your kill.

Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-4329-ga3e5f32 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
   Running Windows 10, 64 bit.
   Version is 0.E-4329-ga3e5f32, using Tiles version, English, only using DDA and Disable NPC Needs.

**Comment by howmokas** [comment]
Sometimes I kill zombies with fire,But it's not my killing.I think  is right.

**Comment by Nhatorama** [comment]
I think the last entity that lands a hit should get the kill if the target dies from damage over time or similar mechanics.
