### ISSUE TITLE
gear get's damaged when it snows

### ISSUE THREAD

**Issue by isnaka** [CleverRaven/Cataclysm-DDA#42373]
# Describe the bug

walking aroun wile it's snowing damages worn gear.

# Steps To Reproduce

1. get you character outside in open air
2. make it snow
3. move around some and observe as your gear starts ripping itself apart

# Expected behavior

gear not getting destroyed

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-4329-ga3e5f32 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    More Survivor Stuff [more_survivor_stuff],
    Bionic Slots [cbm_slots],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    No Rail Stations [No_Rail_Stations]
]

# Additional context

tried to reproduce without mods to be sure and it still happens

**Comment by Fris0uman** [comment]
Do you get any message while your gear gets damaged?

**Comment by isnaka** [comment]
yeah the normal ''your xxx is ripped!'' messages

**Comment by FuelType-Memes** [comment]
> 
> 
> Do you get any message while your gear gets damaged?

This is basically the issue I was talking about some time ago in Discord, so here is some additional info:
If you take off all your clothes you don't get any messages. It only happens with snowing weather, rain does no damage, Turning animations off does not fix it

**Comment by ZhilkinSerg** [comment]
This code probably:

https://github.com/CleverRaven/Cataclysm-DDA/blob/56ebb81bd0741ad799c1c5d991a4c45096642d83/src/weather.cpp#L593-L600

**Comment by Mister-Cultist** [comment]
can confirm, my clothes were being shredded by light snow

**Comment by kevingranade** [comment]
Not fixed by $42389, but a json change might be sufficient now.

**Comment by Mister-Cultist** [comment]
wait this is still happening? It seemed to be fixed on my end a bit ago.

**Comment by Buffered** [comment]
I believe it's happening on loading:

https://github.com/CleverRaven/Cataclysm-DDA/blob/7e30783ef1d0f04a3d6ebe02f509c7d1c2bcbf6b/src/weather_type.cpp#L216

Since existing definitions for thunder storms, etc. have no damage field, assign() will go through the fallback block to always give a damage_instance with 1 damage. Returning to optional with an empty damage_instance() constructor seems to work for the moment.

**Comment by ZhilkinSerg** [comment]
It should be initialized with 0, not 1.
