### ISSUE TITLE
Below freezing, in summer.

### ISSUE THREAD

**Issue by ZaricaDemoni** [CleverRaven/Cataclysm-DDA#42377]
# Describe the bug

Got on this morning to play, walked outside about 20 steps before i became chilly. Decided to check the temperature using my diving watch and got told it was flat out 0F, in the middle of summer.

# Steps To Reproduce
Load Jina in the included save
use divers watch
get told 0F temperature,
Have visible confusion as you slowly freeze to death in what is essentially June.

# Expected behavior
not below freezing in the middle of summer?

# Screenshots
![image](https://user-images.githubusercontent.com/32645137/88174697-8f418900-cbd9-11ea-9075-7957f9ddda95.png)

# Versions and configuration

 - OS: Windows 8.1
 - Game Version: 0.E-4335-g436ee03
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: "dda", "no_npc_food", "blazeindustries", "crt_expansion", "magiclysm", "DinoMod", alt_map_key", "MMA", "cbm_slots", "fuji_mpp", "speedydex", "stats_through_kills", "StatsThroughSkills"

# Additional context
If i remember correctly from reading up on the game it supposedly takes place in a version of England? (correct me if I'm wrong), but the lowest temperature they have ever had during this time was 47 degrees F

[Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4959899/Save.zip)

**Comment by anothersimulacrum** [comment]
It takes place in New England, which is the north east portion of the United States.

**Comment by ZaricaDemoni** [comment]
thanks for the correction, updated tempature is still 42F as record low for New England in june.

**Comment by ZaricaDemoni** [comment]
Additional note: For whatever reason upon loading the game it seems to want to default the temperature to 0 flat regardless of season it seems. This is pretty dangerous as it will cause very quick frostbite in the dead of summer. I tested on a new character with the same mods and without, for the just released build. character had proper heating upon entering the world but on saving exiting and reloading all set temperature was in negatives.

**Comment by GGgatherer** [comment]
Same here. Updated from 10855 and bam, -17 Celsius on Autumn 29, daytime. It was usually about... +5 or so, I think? Definitely not freezing.

**Comment by ZaricaDemoni** [comment]
A temporary way around dying to this nasty little issue. is to use debug to refresh the weather after loading (if its clear, make sure its set to clear in debug). this immediately fixes the temperature.

Debug - map - change weather, choose the same current weather.

**Comment by GGgatherer** [comment]
> 
> 
> A temporary way around dying to this nasty little issue. is to use debug to refresh the weather after loading (if its clear, make sure its set to clear in debug). this immediately fixes the temperature.
> 
> Debug - map - change weather, choose the same current weather.

Worked in 10855 but in 10876 it doesn't work anymore :( Neither changing it to another type nor resetting it to the same have any effect.

**Comment by ZaricaDemoni** [comment]
it does require you to move at least 1 step for the body to register the temp change.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/keep-getting-weird-temperature-issues/24303/6

**Comment by int-ua** [comment]
Confirming. Can someone bisect? At first glance #42138 looks relevant.

**Comment by int-ua** [comment]
There is a workaround patch here: https://github.com/CleverRaven/Cataclysm-DDA/issues/42563#issuecomment-667051092

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/migrated-from-0-e-3-to-0-f-and-its-11c-in-summer/26603/1
