### ISSUE TITLE
Crash in proficiency display.

### ISSUE THREAD

**Issue by shacknetisp** [CleverRaven/Cataclysm-DDA#42387]
# Describe the bug

Attempting to focus the proficiency display in the player display when there are no proficiencies causes a crash.

I think this is because https://github.com/CleverRaven/Cataclysm-DDA/blob/56ebb81bd0741ad799c1c5d991a4c45096642d83/src/player_display.cpp#L362-L370 accesses `sorted_proficiencies( guy )[line]` without ensuring that `line` is within the lower bound of that vector, as the other `draw_*_info` methods do with their own vectors.

# Steps To Reproduce

1. Start a new character without proficiencies.
2. Press @ to open the player display.
3. Press Shift+Tab to focus the proficiencies tab.

# Expected behavior

The tab will be selected without a crash.

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 18.04.4 LTS; Release: 18.04; Codename: bionic; 
- Game Version: 0.E-4362-g56ebb81bd0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

[logs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4962497/logs.zip)
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4962493/save.zip)

**Comment by anothersimulacrum** [comment]
Aagh, must have tested it poorly when adding descriptions.
