### ISSUE TITLE
Installing roof tanks breaks car parts description window.

### ISSUE THREAD

**Issue by NotHereCDDA** [CleverRaven/Cataclysm-DDA#42394]
# Describe the bug
After installing a 200L or 100L tank on the roof i can't scroll through that tiles carparts? tested on another spot on the car just to make sure. It shows me the frame and then this on the right side.

# Steps To Reproduce

Install a tank on the roof and then try to scroll through that sections parts.

# Expected behavior

Description of all parts present.

# Screenshots

![descript says no](https://user-images.githubusercontent.com/66968118/88247025-4b4a9480-cc6a-11ea-8298-aa8f07a20185.PNG)

**Comment by Jamuro-g** [comment]
couldn't reproduce (build 11504)
![image](https://user-images.githubusercontent.com/76928284/109854368-3fd73700-7c57-11eb-953d-edf5ca94c908.png)
