### ISSUE TITLE
Taking down Downspout funnel does nothing.

### ISSUE THREAD

**Issue by NotHereCDDA** [CleverRaven/Cataclysm-DDA#42404]
# Describe the bug

After examining a Downspout the prompt "There is a Downspout Funnel there. Take down?" pops up. If you choose yes the Log states "The downspout funnel is taken down." But it remains intact entirely with no items dropped. 

# Steps To Reproduce

Examine a downspout and attempt to take it down.

# Expected behavior

It goes down.

# Versions and configuration

10862

**Comment by Night-Pryanik** [comment]
Downspout is no longer examinable.
