### ISSUE TITLE
Infection does not kill player (directly)

### ISSUE THREAD

**Issue by Michael1993** [CleverRaven/Cataclysm-DDA#42407]
# Describe the bug

I've looked at the code and the line `"You succumb to the infection"` is commented with
`// Death happens` - this makes me think that the player is supposed to die at this point.
This does not happen - the message appears, all your limbs go to 0 HP and freezing but
the player character does not _die_.

# Steps To Reproduce

1. Make a character
2. Spawn a zombie
3. Repeatedly get bitten until you get a deep bite or two
4. De-spawn zombie and wait for death

# Expected behavior

I expected death. Did not happen. The fact that the player "succumbs to the infection"
every turn means this is not something you can recover from, that's why I expected it.

# Screenshots

![crop](https://user-images.githubusercontent.com/4085611/88276158-de251680-ccde-11ea-965f-04237bfc87c0.png)

# Versions and configuration

- OS: MacOs
    - OS Version: Name: Mac OS X; Version: 10.15.5; Build: 19F101; 
- Game Version: 0.E-4155-g9f82fd3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Fris0uman** [comment]
Can you provide a save? Because this should have been fixed already

**Comment by Michael1993** [comment]
Terribly sorry, I see that there was a recent merge (#42383) and my build is about ~1 week old. Closing this as it seems fixed.
