### ISSUE TITLE
Store keys pressed since last save

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#42416]
# Is your feature request related to a problem? Please describe.
It maybe difficult to remember exactly what you did before a game crash. This means lost time for bug fixers who have to verify and maybe follow false leads and a PITA for players who have to spend several minutes rewriting what they think they remember as their last course of actions.

# Describe the solution you'd like
The game being turn based, it is easy to get the EXACT key pressed sequence since the last save so that crashes can be reproduced exactly. Those should be saved in a file near crash.log.
EDIT following @ZhilkinSerg  comment: In order to be able to reproduce random events, this recording needs also to memorize the seed used for the pseudo rng. The process could be: save/generate new seed/store new seed/memorize keys sequence. The game should now be reproducible at least on similar OS systems (it is rng implementation dependent).

# Describe alternatives you've considered

# Additional context

**Comment by ZhilkinSerg** [comment]
While commands can be saved, I do not think that would actually help as things that happen around player are not predetermined, so same actions can actually lead to different results on different reloads of same savegame.

**Comment by CoroNaut** [comment]
That is true, but for issues that do happen in a predetermined way even if it is 10% or 1% or less of the time, saving the key presses will be a benefit. If you are sure that the code is safe from these bugs, then it would be a waste of time.

**Comment by matt32106** [comment]
> things that happen around player are not predetermined,

In that case, what I am used to do in order to get repeatable experiences from processes using pseudo random generators is to memorize the seed used. So what could be done is Save/generate new seed/store new seed/memorize keys sequence.

I know that pseudo RNG don't have the same implementation on all systems so this does not guarantee that a windows user can reproduce a Mac user experience, however this should work for comparable OS.

**Comment by jbytheway** [comment]
We use the same RNG on all platforms specifically so that things are reproducible. so this is probably possible by saving the RNG state in the savegame too.  I'd bet there are a bunch of corner cases where things wouldn't quite work as expected, though.
