### ISSUE TITLE
Wild West Gunslinger does not start with a gun

### ISSUE THREAD

**Issue by HudsonMC16** [CleverRaven/Cataclysm-DDA#42413]
# Describe the bug

Despite the flavor text suggesting otherwise, the gunslinger does not spawn with his characteristic six-shooter. 

# Steps To Reproduce

Create character with wild west gunslinger profession.

# Expected behavior

# Screenshots

# Versions and configuration

Latest experimental on Android. 

# Additional context

**Comment by Hulkninja** [comment]
Known bug, been around for a while.

As I recall, the holster can't fit the gun, so the gun just disappears.

**Comment by HudsonMC16** [comment]
It does not appear to be listed in the inventory in the character creation screen either. Not sure if this screen shows items in containers, though. 

If it is an issue with the hostler, is this related to the containerized inventory system?

**Comment by HudsonMC16** [comment]
On a bit of further investigation, looks like the [holster ](https://github.com/CleverRaven/Cataclysm-DDA/blob/f76836a5985b66d75dc4dbb7fe46df3952710e3a/data/json/items/armor/holster.json#L128) cannot hold items longer than 20 cm, and the [colt ](https://github.com/CleverRaven/Cataclysm-DDA/blob/a58a5448e6d5170388b989f300637d69346dc6ff/data/json/items/gun/45colt.json#L66) is 208 mm long. This is my first time looking throught the code base, is my assessment correct?

**Comment by PudgyElderGod** [comment]
Wild West Noneslinger.

> On a bit of further investigation, looks like the [holster ](https://github.com/CleverRaven/Cataclysm-DDA/blob/f76836a5985b66d75dc4dbb7fe46df3952710e3a/data/json/items/armor/holster.json#L128) cannot hold items longer than 20 cm, and the [colt ](https://github.com/CleverRaven/Cataclysm-DDA/blob/a58a5448e6d5170388b989f300637d69346dc6ff/data/json/items/gun/45colt.json#L66) is 208 mm long. This is my first time looking throught the code base, is my assessment correct?

It's been a little bit since I poked through the code, but I believe so. You can try adjusting the holster to hold items 25cm in length and see if that fixes it.
