### ISSUE TITLE
Buttered Popcorn Engorges

### ISSUE THREAD

**Issue by Grubleafeater** [CleverRaven/Cataclysm-DDA#42425]
# Describe the bug

Eating 2 servings of buttered popcorn shortly after waking engorged my character, despite their .25l volume.

# Steps To Reproduce

Start game, debug spawn in buttered popcorn, eat.

# Expected behavior

Stomach should be able to contain more than .5l of food.

# Screenshots

# Versions and configuration

# Additional context

**Comment by UmbralReaper** [comment]
Could you please provide a save?

**Comment by gkarfakis19** [comment]
Based on the source code, let's calculate the effective volume of buttered popcorn in the stomach.
I am basing my calculations on the source code itself, and at @DoctorVanGogh's calculation over at #44365 

CAL/kg: 6250 -> ratio = 6.25
Volume per charge =0.25L
So:
Effective Volume:  0.25*sqrt(3*6.25)= 1.08L
So eating 2 buttered popcorn fills your stomach 2.16L, while your stomach has a capacity of 2.5L.

The mathematics behind it is correct, but an argument could be made that the actual values are a bit absurd. Nevertheless, eating 2 entire bags of buttered popcorn would be filling..

**Comment by casswedson** [comment]
Fixed by #45106
