### ISSUE TITLE
Trading with NPC's does not update their volume indicator

### ISSUE THREAD

**Issue by Survivor1998** [CleverRaven/Cataclysm-DDA#42432]
# Describe the bug

When trading with an NPC, after taking all their items, the volume indicator was still at 0.

# Steps To Reproduce

1. Convince the starter NPC on the sheltered scenario to travel with you
2. Ask this NPC to trade with you
3. Take all of their items through trading
4. Notice that their volume indicator is still at 0.

# Expected behavior

I expected to remove items from the NPC, and then give other items back after the available volume was updated. The item I attempted to give in the example below was a pair of boxer shorts.

# Screenshots
In this screenshot I took all the NPC's stuff
![image](https://user-images.githubusercontent.com/68749203/88421489-f4b79480-cde8-11ea-8b72-01169bf258bc.png)

In the second screenshot I attempted to give back some shorts, which doesn't work
![image](https://user-images.githubusercontent.com/68749203/88421639-30eaf500-cde9-11ea-965f-ac7a6cec5885.png)

# Versions and configuration

 - OS: Windows 10.0 1903
 - Game Version: 0.E-4395-g83ce24e [64-bit]
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: dda, disable npc needs, StatsThroughSkills]
 

# Additional context

I hope this was helpful, this is my first ever bug report and English is not my first language.

**Comment by GGgatherer** [comment]
Interesting. Looks like NPCs cannot recognize when they should wear given items instead of trying to stash them into already-worn items. Which, of course, they do not have in this case.
Did you try giving the shorts via 'use this item' dialogue option? Or maybe 'hold on to this item'?

**Comment by hexagonrecursion** [comment]
When you start trading with an NPC the volume is always zero even if she **is wearing** a container eg a duffel bag. This affects both neutral NPCs and followers. Does not affect the refugee center merchant (volume precisely 5000L).

Possibly related: https://github.com/CleverRaven/Cataclysm-DDA/issues/40175

Workaround for equipping followers:
* Use "I want you to use this item" to make sure he is **wearing** a backpack
* Use "Hold onto this item" to give items to the NPC

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 8051d7d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]
