### ISSUE TITLE
broken torso and extreme cold.

### ISSUE THREAD

**Issue by coolmanabdul** [CleverRaven/Cataclysm-DDA#42441]
# Describe the bug
I some how have a broken and splinted torso my torso functions normally to my knowledge but i cannot heal the torso even if it is damaged. Also I get extreme cold if i get wet but it does not alert me to being wet and some how it eventually reaches the point that i reach -300 to -400 warmth. Taking my clothes off returns you to survivable levels though towels manage to fix the problem.

# Steps To Reproduce
1.get wet through any means
2.wait an large amount of time half a day to quarter of a day
3.check you status periodically
4.watch as your warmth levels on your character drastically decreases
second bug
I have no idea exactly how to reproduce the broken torso splint glitch but i have some guesses
1. you splint a broken limb like a leg or arm
2.game assumes this is also the torso
3.splints the torso assuming its broken like the leg or arm

# Expected behavior
You get wet then have debuffs from it morale and warmth if you use a towel or try out through air drying these debuffs to don't get worse and slowly are removed from the character.
second bug
you break your torso you instantly die. or you break you leg and your splint does not copy onto your torso

# Screenshots
![image](https://user-images.githubusercontent.com/68766211/88449091-24c75d80-ce12-11ea-9ae7-df3b5cea0acb.png)
https://media.discordapp.net/attachments/642349261320880128/736434830073397248/unknown.png?width=1262&height=169

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-4395-g83ce24e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Dark Skies Above [darkskies],
    Bootleg Walkers [Bootleg_Walkers],
    DinoMod [DinoMod],
    More Survivor Stuff [more_survivor_stuff],
    No Rail Stations [No_Rail_Stations],
    Cars to Wrecks [cars_to_wrecks]
]

# Additional context
This is my first time doing a bug report sorry if it seems organized or not following the rules properly.

**Comment by Fris0uman** [comment]
The freezing part has already been reported.
The fact that your not dead with a torso at 0 hp is the new bug.

**Comment by rtizzy** [comment]
@Fris0uman If this is similar to the bug I run into it seems that if you have a splinted arm or leg then your torso will show up in the manner @coolmanabdul screenshot demonstrates. 

If memory serves it (torso) showed up properly in the health GUI on the upper right

**Comment by rtizzy** [comment]
On an unrelated note, I'm trying to get a demonstration but it seems the latest experimental has messed up the biosniper helicopter crash a bit (I keep dying instantly due to a messed up necessary part like the head or torso)

Not sure if there is any testing added for "Is a scenario/char combo survivable on turn 1" but that might be worth adding to check for bugs like this (wasn't seeing this in the past).

![image](https://user-images.githubusercontent.com/523926/88686211-271e0600-d0f7-11ea-8a0c-59574bdced85.png)

**Comment by rtizzy** [comment]
@Fris0uman 

>The fact that your not dead with a torso at 0 hp is the new bug.

**Replication:**

1. Spawn in as any character. 
2. Damage the torso below maximum health (amount does not matter) 
3. Damage an arm or leg to where it's broken. 
4. Spawn a splint and then splint the broken body part. 
5. Spawn a bandage and apply. 

You'll see the torso showing as "broken"

![image](https://user-images.githubusercontent.com/523926/88687091-1ae67880-d0f8-11ea-9748-2b031a235396.png)

Health GUI in Upper right is still correct. 

![image](https://user-images.githubusercontent.com/523926/88687137-2e91df00-d0f8-11ea-9660-53764ac052c2.png)
