### ISSUE TITLE
Register NumPad keys separately from Regular Number keys

### ISSUE THREAD

**Issue by Daevinski** [CleverRaven/Cataclysm-DDA#42445]
### The Problem?

Right now when customizing the keybindings, the keys from 1 to 0 are registered without distinction between the Regular Number Keys (above QWERTY) and NumPad Keys (on the right side), what forces you to have the same commands in both sets.

This is a waste of opportunity, especially considering the high number of commands necessary to play the game.

### The Solution!

If possible, adjust the game to Register NumPad keys separately (usually registered as "Numpad1", and etc, in other games) from Regular Number keys, so we can have, for example, Movement on one set and HotKeys on the other set.

This can make the access to Items, Weapons, Spells or Action Menu Items easier through customization of the keybindings.

**Comment by Qrox** [comment]
Will be solved on SDL by #41866. Not sure whether it's possible on curses.
