### ISSUE TITLE
A change to crafting limitations due to morale.

### ISSUE THREAD

**Issue by RoachLoach** [CleverRaven/Cataclysm-DDA#42449]
**# Is your feature request related to a problem? Please describe.**
While the restrictions to crafting make sense at first (Oh, i'm so depressed right now I don't want to craft a spear/tailor a suit/make a burger/boil water), in practice it leads the player to taking strange actions. Since morale doesn't limit a characters movement to a great degree, a survivor with low mood may be completely unwilling to boil water, but is more than happy to spend hours looking for fresh water instead of spending the 5 seconds it would take to place a pot of water onto a burning fire. the hard limit of the morale system also means that a survivor will swear off spending 12 hours crafting a complex mechanical masterpiece at the exact same moment that they decide they'd rather die than spend a few seconds turning a blanket into a sling. 

**# Describe the solution you'd like**
Limits to activity based on morale most likely need to be put onto different tiers based on item difficulty, and if a character is unwilling to perform even basic survival activities that take under a minute they probably should have some kind of movement debuff as well, or at least some serious stat penalties. 

**# Describe alternatives you've considered**
1.Keep the system as it is but whitelist a few simple recipes, this seems like the quickest solution but is sort of only a band-aid.
2.Make the effects of low mood take a long time to manifest to properly simulate the kind of hopelessness that would be required to refuse to boil water/tie a knot/sharpen a stick

**# Additional context**
I understand that many people have a personal connection to extreme sadness/depression and intend no offence to anyone with this or any discussion that extends from it. My primary concern isn't that "this isn't how depressed people act" its that the current implementation has some strange side effects on the way the game is played, and makes playing while a character is suffering drug withdrawal arguably more punishing than it should be.

**Comment by Nhatorama** [comment]
You could have a "Survival Instinct" character sheet Effect appear that allows a player to do any task whenever a player is suffering one of the following:

- Freezing/Scorching?
- Starving
- Parched
- Bleeding
- Any imminent life threatening condition

No batch crafting allowed.

**Comment by meladath** [comment]
This would also make the tweaker start actually not completely terrible too. Not a bad idea to have some crafts that our survivor would ignore the "you are too upset to do this" effect.

**Comment by Fosheze** [comment]
What about simply lowering effective skill values the more depressed your character is. I don't have any hard numbers here to work off of but you could have various morale tiers and for every one below neutral (0) apply a -1 to all skills. That way the character will still be able to complete tasks which they would find "simple" for their skill level and the tasks that are borderline they would be worse at because their mind isn't in it.

You could also make all crafts that only require level 0 skills exempt from that rule. That way a character will always be able to manage basic survival however anything beyond that will require that all of their basic needs are met.
