### ISSUE TITLE
Discussion: Fine hammering or revisiting recipes that rely on it

### ISSUE THREAD

**Issue by Sammmmm** [CleverRaven/Cataclysm-DDA#42459]
In the latest experimental fine hammering is no longer on makeshift hammers, and stone hammers have been removed.  I recently started playing again, so I'm not sure when these changes were made.  I've been running Island Prison Break, which is a challenge I've really enjoyed in the past.  I usually try to work my way up to being able to build a wood boat hull starting with no crafting skills or very limited crafting skills.  This is still technically doable, though depending on luck might rely on which tools spawn in the prison workshop.  There's certainly other ways off the island as well, but the whole challenge feels a bit more limited than it did previously as there is no way to craft improvised lock picks, which can really limit your ability to explore the prison unless you can smash the cell block gates with a homewrecker or otherwise get through them. 

Making workable lock picks from sheet metal obviously should require more advanced tools, but it doesn't seem like you would need bolt turning or fine hammering to make a workable tension wrench from a wire.  There aren't a lot of "early game" recipes that you're locked out of by not having access to fine hammering, mostly it's the improvised lockpick and the makeshift hand drill.  So, I'm wondering if this was an intentional consequence of the decision to limit fine hammering, or an unintentional side effect.  It makes sense that you shouldn't be able to craft the gun and bow mods that require fine hammering, but there aren't a lot of other recipes in between these makeshift/improvised tools and more sophisticated mods that require it.

**Comment by Hulkninja** [comment]
I think maybe the whole "Island Prison" scenario could use an update. Comparing it to the normal "Prison" one, the Island Prison feels lacking in both size as well as variety.

Just my opinion though. Alcatraz was a big place, after all.

**Comment by Sammmmm** [comment]
I agree, but I do think part of that scenario is figuring out how to harvest the limited furniture, prison gear, workout benches, etc to build up a progression of better gear and tools, and it feels like some of the recent changes have made that natural crafting progression without outside tools or exotic resources less interesting/plausible.

**Comment by kevingranade** [comment]
Please put some thought into what things naturally should be ways out of a prison if you aren't being watched closely and propose those instead of fixating on things like lockpicks. 
Prisons are one of the few places where door locks should actually be prohibitively difficult to pick, so making your way out via some shoddily improvised lockpicks never made sense inbthe first place.
