### ISSUE TITLE
It seems that plutonium isn't radioactive

### ISSUE THREAD

**Issue by Duck13Tales** [CleverRaven/Cataclysm-DDA#42458]
# Describe the bug

I just deconstructed a plutonium generator and it dropped a "plutonium". I just freaked out due it's description and because I thought that as I was deconstructing the generator in its perfect shape and not simply blowing it up I supposed that I would get the plutonium in it's casing, shell, whatever, but instead I got it "raw"...

Anyway, I got geiger counter and used it but got 0 rads. Used it in the tile where the plutonium was and got 0 rads. Picked up the plutonium and measured once again on me and 0 rads. Activated the geiger counter and he couldn't get anything for a while... The wrist thing got no radiation from me too and my radiation badge was still "green".

As it seems my NPC was completely safe as well.

So shouldn't the plutonium radiate though it's "ominous" description? Or it isn't really radiating at all? Or aren't any radiation instruments working?

# Steps To Reproduce

1 - Deconstruct a plutonium generator or wish for a plutonium
2 - Walk merrily around with your fancy plutonium necklace
3 - Check radiation with any instrument you wish and at least think that everything should be ok

# Expected behavior

Probably the plutonium should be radiating or the description changed a bit, though I wished that at least the one we got from deconstructing a perfect plutonium generator should be relatively safe until something !!FUN!! happens to it.

And we surely need something to "encase" it, and effective ways to deal with it!

It seems that the plutonium has no use at all, so can I make some recipes that "use" it or at least "get rid" of it?

# Screenshots

Not applicable.

# Versions and configuration

I am using using the CDDA 0.E-b10865 with the mods:

DDA
Disable NPC needs
Stats through skills
Stats through kills
SpeedyDex

**Comment by buffog** [comment]
Using 0.E-b1086**3**. Plutonium is radioactive.

**Comment by andrei8l** [comment]
Radioactive items in inventory must have been broken since the inventory system overhaul and it looks like an easy fix. I'm not sure if items on the map were ever radioactive, but I'm still investigating.

**Comment by andrei8l** [comment]
After looking into this a little bit, I think it's more realistic to keep the broken mechanic lol. The absorbed dose rate from most of the current `RADIOACTIVE` items would be on the order of nSv/s, while the game only tracks at mSv/s (i.e. ~1000000 times higher). The only really radioactive items would be a broken `RTG_coffee`, `cobalt_60`, and possibly the poorly specified `plutonium` (*not* `plut_cell`), all of which are so rarely encountered that IMHO it's not worth putting the effort into fixing this mechanic (you'd also have to keep it consistent somehow with the mapgen radioactivity and `fd_nuke_gas`).

I've pushed a quick fix for radioactive items in inventory though, if anyone is willing to work on this.

**Comment by anothersimulacrum** [comment]
`plutonium` is supposed to be a vaguely specified raw nuclear material (of whatever type it is where you can find it), so it would count among those ones.

I think it's worth fixing on the map, but I understand if you don't.

**Comment by Duck13Tales** [comment]
Thanks a lot @anothersimulacrum, @andrei8l and @buffog !

**Comment by andrei8l** [comment]
Keep this open please. It's still a valid bug

**Comment by Duck13Tales** [comment]
Oh sorry @andrei8l , wasn't sure if someone still needed it so I closed.

Thanks for reopening @Night-Pryanik !

**Comment by Night-Pryanik** [comment]
You're welcome.

**Comment by NetSysFire** [comment]
Fixed by #58449
