### ISSUE TITLE
Advanced UPS and RM_13 Armor use wrong battery heavy_atomic_battery_cell instead of plutonium_cells

### ISSUE THREAD

**Issue by MikuMiddo** [CleverRaven/Cataclysm-DDA#42473]
# Describe the bug
I don't know if it is a bug or not,but since I haven't seen any issue or PR about this change.I decided to report it.
According to the discribe of the Advanced UPS and RM_13 Armor,they should use plutonium_cells as ammo,but now they are using the heavy_atomic_battery_cell

# Steps To Reproduce
1.summon a Advanced UPS or RM_13 Armor
2.see It's ammo.

# Expected behavior
They should use plutonium_cells again.

# Screenshots
![image](https://user-images.githubusercontent.com/53809752/88496524-f69f7480-cfef-11ea-8212-0a07e314a415.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-4395-g83ce24e [64-bit]
- Graphics Version: Tiles
- Game Language: 系统语言 []
- Mods loaded: [
    浩劫余生 [dda],
    禁用NPC需求 [no_npc_food],
    C.R.I.T 扩展 [crt_expansion],
    Blaze 载具工业 [blazeindustries],
    大魔法 [magiclysm],
    余波未尽 [aftershock],
    恐龙世界 [DinoMod],
    Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
    疯狂大灾变 [crazy_cataclysm],
    神话武术 [MMA],
    移除真菌类怪物 [No_Fungi],
    Fuji的军事职业Mod [fuji_mpp],
    技能提升属性 [StatsThroughSkills],
    敏捷速度加成 [speedydex],
    杀怪提升属性 [stats_through_kills],
    余震个人用强化模组 [After_Shock_Personal_UsageMod],
    无限手套 [Infinity_Gauntlet]
]

# Additional context

**Comment by andrei8l** [comment]
This was changed intentionally in https://github.com/CleverRaven/Cataclysm-DDA/pull/41599 and the description wasn't updated to match

**Comment by MikuMiddo** [comment]
> This was changed intentionally in #41599 and the description wasn't updated to match

Okay.I got,Thank you
