### ISSUE TITLE
Dissection Requiring Tool with Surface Quality

### ISSUE THREAD

**Issue by Quantum-Thorn** [CleverRaven/Cataclysm-DDA#42485]
# Describe the bug

Unable to dissect the corpse of a Zombie Bio-Operator, either pulped or un-pulped, whilst in possession of a scalpel. Prompted with a message detailing the requirement of a tool with the 'Surface' quality of '3'.

# Steps To Reproduce

1. Stand over corpse with a scalpel in inventory.
2. Bring up Butchery menu with 'B'.
3. Select dissection with 'd'.

# Expected behavior

Successful dissection of the Zombie Bio-Operator corpse without the requirement of any tools other than one with the 'Fine Cutting' quality.

# Screenshots

![butcher-dissection](https://user-images.githubusercontent.com/68865273/88567780-91528000-cffd-11ea-9692-7ed3f36bb0eb.png)

# Versions and configuration

 - OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-4457-g92af4ff [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    DinoMod [DinoMod],
    No Rail Stations [No_Rail_Stations],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    C.R.I.T Expansion Mod [crt_expansion],
    Blaze Industries [blazeindustries],
    No Fungal Monsters [No_Fungi]
]

# Additional context

Performed similar dissections without the requirement of 'Surface' quality tools before updating from version '10798' to '10872'.

**Comment by Rjtheperson** [comment]
Read  #42372

**Comment by Quantum-Thorn** [comment]
The JSON additions at #42372 indicate that a Brick Kiln is currently the only item providing the necessary Surface quality to butcher large bodies. I assume this will change sometime in the near future, but for now I will resort to using what is currently working.

**Comment by FuelType-Memes** [comment]
> 
> 
> The JSON additions at #42372 indicate that a Brick Kiln is currently the only item providing the necessary Surface quality to butcher large bodies. I assume this will change sometime in the near future, but for now I will resort to using what is currently working.

No. According to that PR workbench, fiber mat, leather tarp or a plastic groundsheet should work

**Comment by Quantum-Thorn** [comment]
You're correct. The changes made to furniture-surfaces.json grant those items a 'large_surface_psuedo' flag which may very well mean they possess a Surface quality of 3. Laying down a leather tarp allowed me to dissect the corpse in the end.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/butchering-in-0-e/24288/4
