### ISSUE TITLE
flails despite being long two handed pole weapons are not storable in spear strap.

### ISSUE THREAD

**Issue by logros13** [CleverRaven/Cataclysm-DDA#42482]
# Describe the bug

peasant flail and war flail despite being two handed reach attack weapons can not be stored in the spear strap unlike other pole weapons, this seems inconsistent. 

For a two handed flail it also seems oddly short at just 60 cm, that seems more like a one handed flail than a two handed weapon?

(speaking of oddly short, when checking the storability of other pole weapons i noticed that the makeshift glaive is only 14 cm long...)

 - Game Version: 0.E-4457-g92af4ff (tiles)

**Comment by ZaricaDemoni** [comment]
an example of a two handed war flail. the length for every weapon mentioned so far kind of needs to be re-looked at a tiny bit. As the blade for a glaive alone typically ranged 40cm long, (18 inches)

![image](https://user-images.githubusercontent.com/32645137/88548724-4d975080-cfd4-11ea-9ad3-5cdff8fc1497.png)
