### ISSUE TITLE
Buying a filled container off an NPC and then unloading it gets you accused of stealing

### ISSUE THREAD

**Issue by SolidMilk19** [CleverRaven/Cataclysm-DDA#42490]
# Describe the bug

When you purchase a filled container (including clothes with pockets) off an NPC through the trading system and then unload it in front of them, you get accused of stealing from their faction. No matter which option you pick in the dialogue, you keep the items, but the NPC will hate you afterwards.

# Steps To Reproduce

1. Create a character with a scenario that spawns a friendly NPC nearby.
2. Talk to the NPC and trade your belongings for whatever filled container they have on them.
3. Unload this container in front of them and get accused of stealing from their faction.

# Expected behavior

You bought the container with its contents; there's no reason they shouldn't be your property.

# Screenshots

![Capture](https://user-images.githubusercontent.com/68878873/88601112-3017c480-d070-11ea-9357-6900c1ce8a84.PNG)

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-4457-g92af4ff
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: Dark Days Ahead [dda], Disable NPC Needs [no_npc_food]

**Comment by ZaricaDemoni** [comment]
Buying the container doesn't actually seem to buy the items in it. I noticed this when unloading a pack that contained an item to bit to be held in my inventory. it dropped to the floor and picking it up would have been stealing.

**Comment by placeybordeaux** [comment]
Just got bit by this in the middle of the free merchants out post. I'll take a short crack at it, but it'd be my first issue on here in 5 years so no promises.
