### ISSUE TITLE
Sort Armor menu not showing coverage or encumbrance in the middle

### ISSUE THREAD

**Issue by airportation** [CleverRaven/Cataclysm-DDA#42508]
# Describe the bug

In the middle part of the Sort Armor menu, coverage and encumbrance always show up as 0 no matter the piece of clothing selected. The encumbrance on the right part is however correct. The items' descriptions also correctly note the coverage and encumbrance.

# Steps To Reproduce

1. Have clothing, for instance a cassock.
2. Open "Re-layer Armor/Clothing" menu.
3. Scroll through all your clothing and observe how coverage and encumbrance stay at 0.

# Expected behavior

The menu should be showing everything properly.

# Screenshots

![image](https://user-images.githubusercontent.com/67428677/88689717-21c2ba80-d0fb-11ea-9cba-ed37023e9830.png)
With the Aftershock mod installed as per Versions and configuration below.

![image](https://user-images.githubusercontent.com/67428677/88690769-4bc8ac80-d0fc-11ea-9d4e-e6e6554b3ee5.png)
Different world, same version, mods are also the same except no Aftershock. As you can see the bug is not caused by Aftershock's presence.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-4463-g344d6de [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Graphical Overmap [Graphical_Overmap],
    Aftershock [aftershock]
]

**Comment by andrei8l** [comment]
This only happens for `<< All >>` and it displays appropriate values if you switch body parts (left/right keys by default). Not exactly a bug, but I do agree that it's weird/confusing. Maybe it should display average values for `<< All >>`?

**Comment by Fris0uman** [comment]
Caused by https://github.com/CleverRaven/Cataclysm-DDA/pull/41522
It uses `tabindex` to generate bodypart_id to look up coverage and encumbrance, when in the ALL tab tabindex is num_bp and therefore the code can't get the encumbrance or coverage of the items.
