### ISSUE TITLE
Items with "ACT_ON_RANGED_HIT" set with cast spell use doesn't center on the spot upon activation 

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#42506]
# Describe the bug

When I throw an item that activates a spell after it hits something, the spellcasting is centered to the player, as if I activated it by hand.

This also occurs to the items that activates out of player's inventory.

# Steps To Reproduce

1. Spawn an item with said flag and any cast spell.
2. Throw it.
3. Spellcasting is done by you.

# Expected behavior

It should activate on the spot where it landed.

# Versions and configuration

- OS: Android
    - OS Version: Manufacturer: OPPO; Model: A1601; Release: 5.1; Incremental: 1577332894; 
- Game Version: 0.E-4329-ga3e5f32 [32-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    AVTest [avtest]
]

# Additional context

I'm hoping for magical grenades :)

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
