### ISSUE TITLE
Removing a “survivor headlamp (on)” from a follower through the “r Sort armor” menu causes a crash/segmentation fault. EDIT: there's the 0F temperature bug as well.

### ISSUE THREAD

**Issue by Nhatorama** [CleverRaven/Cataclysm-DDA#42503]
# Describe the bug
Removing a “survivor headlamp (on)” from a follower through the “r Sort armor” menu causes a crash/segmentation fault.

# Steps To Reproduce
1. Wake or don’t wake the follower.
2. Move into the follower.
3. Choose “r Sort armor”
4. Select the “survivor headlamp (on)”
5. Press u
6. Press y

# Expected behavior
The game should not crash when removing a followers’ worn items.

# Versions and configuration
- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 20.0.3; Codename: Lysia; 
- Game Version: 0.E-4458-g8cf46cdb44 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context
Debug and crash logs [cataclysm-dda.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4988706/cataclysm-dda.zip)
Save file [Alta Vista.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4988712/Alta.Vista.zip) this is "a save file that occurs in the right conditions, just before the crash happens."
To take off the “survivor headlamp (on)” from the follower without causing a crash you need to remove everything else before removing the survivor headlamp.
Alas trying to remove the military rucksuck that contains the "survivor headlamp (on)” also causes a crash.

**Comment by andrei8l** [comment]
```diff --git a/src/armor_layers.cpp b/src/armor_layers.cpp
index 0c3b77a318..eb64c4ff56 100644
--- a/src/armor_layers.cpp
+++ b/src/armor_layers.cpp
@@ -878,6 +878,7 @@ void player::sort_armor()
                     }
                     player_character.cancel_activity();
                     selected = -1;
+                    leftListIndex = std::max( 0, leftListIndex - 1 );
                 }
             }
         } else if( action == "ASSIGN_INVLETS" ) {
```
I don't think I'll PR this one
