### ISSUE TITLE
Extending and collapsing either type of baton takes no time

### ISSUE THREAD

**Issue by airportation** [CleverRaven/Cataclysm-DDA#42507]
# Describe the bug

Extending and collapsing expandable batons doesn't cause time to pass whatsoever. Same thing with the PR-24 baton.

# Steps To Reproduce

1. Wield an expandable baton.
2. Press shift+A and keep that pressed.
3. Time doesn't pass but you still get the messages "You snap open your baton." and "You collapse your baton."

# Expected behavior

Both actions taking an appropriate amount of time.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-4463-g344d6de [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Graphical Overmap [Graphical_Overmap],
    Aftershock [aftershock]
]

**Comment by jeremyshannon** [comment]
Aren't these things supposed to be able to snap open rapidly? Like press the catch button, flick your wrist, and you're ready to start swinging in under a second? One of their selling points for police and security is that you don't have to fumble with them when somebody's coming at you.
 Retracting ought to take a second or two though.
