### ISSUE TITLE
Guns spawned on dead soliders have no magazines or ammo

### ISSUE THREAD

**Issue by XxX69Krhal69XxX** [CleverRaven/Cataclysm-DDA#42528]
# Describe the bug
Guns spawned on dead soldiers found in fields have no magazines or ammo.

# Steps To Reproduce
Wander around until you find the dead soldiers.
Pick up their guns

# Expected behavior
Should have magazines of various ammo counts.

# Versions and configuration
Build #10876
No mods

# Additional context

**Comment by Duck13Tales** [comment]
I once opened a issue about it but closed to make more tests and there was a fix about to come to fix magazines and containers nesting.

It seems that when a gun need bullets sometimes they could have bullets but when it needed a magazine it never had one.

I am not sure in the newest version but it seems that they still never spawn with magazines.

**Comment by Duck13Tales** [comment]
Sorry, I was testing with zombie soldiers, not sure how I can spawn those dead soldiers with the debug menu.

**Comment by XxX69Krhal69XxX** [comment]
I'll upload a save next time I come across it.

**Comment by Duck13Tales** [comment]
This build that you mention seems quite old. If possible use the latest experimental as there was a fix for spawning items with magazines quite recently.

**Comment by RoachLoach** [comment]
Hi, Im using the latest experimental and have experienced the exact same bug.
![gun_weird](https://user-images.githubusercontent.com/52650109/89556707-c91cad00-d7df-11ea-9351-66e56e709232.PNG)
Guns spawn with the corpses of a soldier, but no ammo or magazines. I thought it might be a problem with the corpses rising and taking the mags/ammo with them, but they still dont drop any ammo or mags when put back down.
