### ISSUE TITLE
Loophole when "wearing" and canceling the "stop wielding" prompt

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#42525]
# Describe the bug

When I `W`ear any item of clothing, and I don't have enough space in my inventory to pick up the thing before wearing it, I get a prompt to stop wielding my current weapon, which seems good and proper since I need my hands free to put it on.

However, if I press ESC to cancel this prompt, I end up wearing the item anyway, and the weapon remains wielded (with fewer total moves than if I had dropped my weapon).

# Steps To Reproduce

1. Drop everything (get nekkid)
2. Wield something (anything)
3. Try to wear something (anything) - get "Stop wielding xxx?" prompt
4. Press ESC
5. Check inventory - wielded item remains wielded, and other item is now worn

This is the simplest use case, but it is the same regardless of what you're already wearing or carrying - if you don't have enough storage to hold the item you're trying to `W`ear, the "Stop wielding" prompt will appear, and can be cheated with ESC to wear the item anyway, with no additional movement penalty.

# Expected behavior

ESC should cancel the action of attempting to wear the item; the wielded item should remain wielded, and the desired item should not be worn afterwards.

# Screenshots

Wearing nothing, wielding a pocket knife:

![image](https://user-images.githubusercontent.com/238395/88753165-ca334780-d118-11ea-8083-81e823a6b2ac.png)

Pressing `W` to wear a nearby item:

![image](https://user-images.githubusercontent.com/238395/88753176-d15a5580-d118-11ea-8aaa-89395214c77f.png)

Prompt for what to do with the pocket knife - there is only one option, and I do not like it:

![image](https://user-images.githubusercontent.com/238395/88753247-f9e24f80-d118-11ea-8bb8-404c1878c139.png)

When I press ESC, the backpack gets worn anyway, while still wielding the pocket knife:

![image](https://user-images.githubusercontent.com/238395/88753290-141c2d80-d119-11ea-8cfe-6918eeb52f8d.png)

![image](https://user-images.githubusercontent.com/238395/88753309-1f6f5900-d119-11ea-9a37-696507d54bf5.png)

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-4551-geb830227c0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by gcaliber** [comment]
This game needs less prompts like this in general. I would say the bug is the fact the prompt comes up at all since you don't need to put an item in your inventory in order to wear it. The game should, at worst, automatically handle dropping and picking up any wielded item by just making it take slightly longer. You could also include a message in the log about it taking a little longer if you don't have your hands free, a bit like is done for hauling items.

**Comment by wapcaplet** [comment]
This can be reproduced as well from the `+` sort armor screen. Press `e` to equip/wear an article of clothing, then `ESC` at the "drop wielded item" prompt.
