### ISSUE TITLE
Dismembering corspes without a cutting tool

### ISSUE THREAD

**Issue by pepesito1122** [CleverRaven/Cataclysm-DDA#42530]
# Is your feature request related to a problem? Please describe.
As of the date typing this, dismembering a corpse require a tool that can cut and also has a butchering value. I doubt you need a knife to destroy a corpse. 

# Describe the solution you'd like
Get rid of the cutting stipulation for dismembering a corpse, allowing anything with some form of butchering to destroy corpses for scraps
# Describe alternatives you've considered
Remove flint from the game?

# Additional context
none

**Comment by Duck13Tales** [comment]
To dismember a corpse you probably would need a cutting tool, unless you are unbelievably strong to just rip it apart.

But you can always "S"mash corpses. You don't need a cutting tool for this but it seems that high bashing makes this faster.

**Comment by Duck13Tales** [comment]
Sorry but I just was able do dismember a corpse with my bare hands, so I really don't know what exactly is needed.

**Comment by kevingranade** [comment]
Can you be more specific about what tools should be usable for dismembering but aren't?

**Comment by KorGgenT** [comment]
> I doubt you need a knife to destroy a corpse.

This is called `s`mash
