### ISSUE TITLE
Crash while loading a save game.

### ISSUE THREAD

**Issue by Nhatorama** [CleverRaven/Cataclysm-DDA#42542]
# Describe the bug
Crash while loading a save game.

# Steps To Reproduce
1. Start the game.
2. Load the game.

# Expected behavior
The game shouldn’t crash while loading a save game.

# Versions and configuration
- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 20.0.3; Codename: Lysia; 
- Game Version: 0.E-4405-ge092a04d93 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context
[cataclysm-dda.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4996309/cataclysm-dda.zip)
[Alta Vista.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4996310/Alta.Vista.zip)

**Comment by andrei8l** [comment]
```diff --git a/src/map.cpp b/src/map.cpp
index d31a65e4d2..ab2e7f74a9 100644
--- a/src/map.cpp
+++ b/src/map.cpp
@@ -1322,7 +1322,11 @@ furn_id map::furn( const tripoint &p ) const
     point l;
     submap *const current_submap = get_submap_at( p, l );
 
-    return current_submap->get_furn( l );
+    if( current_submap != nullptr ) {
+        return current_submap->get_furn( l );
+    }
+
+    return f_null;
 }
 
 void map::furn_set( const tripoint &p, const furn_id &new_furniture )
@@ -1447,7 +1451,11 @@ ter_id map::ter( const tripoint &p ) const
     point l;
     submap *const current_submap = get_submap_at( p, l );
 
-    return current_submap->get_ter( l );
+    if (current_submap != nullptr) {
+        return current_submap->get_ter( l );
+    }
+
+    return t_null;
 }
 
 uint8_t map::get_known_connections( const tripoint &p, int connect_group,
@@ -2279,8 +2287,12 @@ bool map::has_flag_ter_or_furn( const ter_bitflags flag, const tripoint &p ) con
     point l;
     submap *const current_submap = get_submap_at( p, l );
 
-    return current_submap->get_ter( l ).obj().has_flag( flag ) ||
-           current_submap->get_furn( l ).obj().has_flag( flag );
+    if (current_submap != nullptr) {
+        return current_submap->get_ter( l ).obj().has_flag( flag ) ||
+               current_submap->get_furn( l ).obj().has_flag( flag );
+    }
+
+    return false;
 }
 
 // End of 3D flags
```
this lets you load the save but doesn't solve the issue. No idea where the real problem is. Either there's a bug in de/serialization or cosmic rays ate your save file.
