### ISSUE TITLE
Add background colors to ASCII art

### ISSUE THREAD

**Issue by Ununsept117** [CleverRaven/Cataclysm-DDA#42543]
# Is your feature request related to a problem? Please describe.
Currently you can add background colors to ASCII art, but they will behave badly:
1. Color tags with background colors count towards character limit in single line, producing errors about line length.
2. Color tags with background colors don't apply to next lines, so you have to add them every new line. Such behavior is inconvenient and inconsistent - color tags without background colors apply to next lines.
3. Many foreground and background color combinations can't be used - I think the problem is that they aren't defined in src/color.cpp. 
# Describe the solution you'd like
Make color tags with background colors not count towards character limit in a single line, make them apply to next lines, and add more foreground and background combinations.
# Describe alternatives you've considered
Leave it as it is.
# Additional context
This idea was suggested during my discussion with Kyzrati, the developer of REXPaint, an ASCII art tool. Soon he'll release a new version of REXPaint, which will include support for exporting art in a format readable by CDDA. This will include foreground and background colors, but for the background colors to work, they have to be implemented in the game first.

**Comment by ZhilkinSerg** [comment]
Point 1 works fine for me:

![image](https://user-images.githubusercontent.com/16213433/88847828-49e01580-d1f0-11ea-9af8-47993d6b3ed3.png)

```JSON
[
  {
    "type": "ascii_art",
    "id": "glass_bottle",
    "picture": [
      "",
      "",
      "",
      "<color_white_red>              ║   ║",
      "              ║   ║",
      "              ║   ║",
      "            ╔═╝   ╚═╗",
      "           ╔╝      #╚╗",
      "          ╔╝     ### ╚╗",
      "          ║    ####   ║",
      "          ║   ####    ║",
      "          ║  ####     ║",
      "          ║######     ║",
      "          ║####       ║",
      "          ║###        ║",
      "          ║#          ║",
      "          ║           ║",
      "          ║           ║",
      "          ║           ║",
      "          ║           ║",
      "0123456789012345678901234567890123456789A"
    ]
  }
]
```

**Comment by ZhilkinSerg** [comment]
Regarding point 1 - it is not unique to color tags with background color. Image is displayed fine in the end, despite error messages, but check code actually needs to be updated to check line with stripped color tags.

![image](https://user-images.githubusercontent.com/16213433/88848116-afcc9d00-d1f0-11ea-9b56-66b22719ce4b.png)

```JSON
[
  {
    "type": "ascii_art",
    "id": "glass_bottle",
    "picture": [
      "",
      "",
      "",
      "<color_white_red>              ║   ║",
      "              ║   ║",
      "              ║   ║",
      "            ╔═╝   ╚═╗",
      "           ╔╝      #╚╗",
      "          ╔╝     ### ╚╗",
      "          ║    ####   ║",
      "          ║   ####    ║",
      "          ║  ####     ║",
      "          ║######     ║",
      "          ║####       ║",
      "          ║###        ║",
      "          ║#          ║",
      "          ║           ║",
      "          ║           ║",
      "          ║           ║",
      "          ║           ║",
      "<color_green>0123456789012345678901234567890123456789A",
      "<color_red_white>0123456789012345678901234567890123456789A"
    ]
  }
]
```

**Comment by Ununsept117** [comment]
The picture above looks fine, but when I did this
```
  {
    "type": "ascii_art",
    "id": "cashcard",
    "picture": [
      "",
      "",
      "",
      "       <color_white_red>╔═══════════════════╗",
      "       ║                   ║</color>",
      "       <color_white>║</color> <color_yellow>╔═   ╔═╔═╗╔═║ ║</color>   <color_white>║",
      "       <color_white>║</color> <color_yellow>║═ ┼ ║ ║═║╚╗║═║</color>   <color_white>║",
      "       <color_white>║</color> <color_yellow>╚═   ╚═║ ║═╝║ ║</color>   <color_white>║",
      "       <color_white>║                   ║",
      "       <color_white>║   RIVTECH TRUST   ║",
      "       <color_white>║                   ║",
      "       <color_white>║                   ║",
      "       <color_white>║ 555 993 55221 066 ║",
      "       <color_white>╚═══════════════════╝"
    ]
  },
```
 
it looked like that:
![colorbug](https://user-images.githubusercontent.com/63505222/88850152-38e0d580-d1eb-11ea-84eb-0abb41dc4b2b.png)

**Comment by ZhilkinSerg** [comment]
That is very strange. Here is what I see with same json:

![image](https://user-images.githubusercontent.com/16213433/88851129-fe7c3600-d1f4-11ea-9550-dcd524a051ac.png)

Which game version and OS are you on?

**Comment by Ununsept117** [comment]
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-4529-gb82b0cb [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]

**Comment by ZhilkinSerg** [comment]
Point 3 is related to curses and terminals. It looks like there are different limits for color pairs on different terminals (https://linux.die.net/man/3/init_pair).

We can probably add more color pairs to the code, but they won't guaranteed to work on all terminals.
