### ISSUE TITLE
Use of "relative" for book fields

### ISSUE THREAD

**Issue by LaVeyanFiend** [CleverRaven/Cataclysm-DDA#42557]
# Is your feature request related to a problem? Please describe.
While converting books to use abstracts to set up a looks-like hierarchy for Erk, my playtesting showed that multiple book attributes cannot be used with "relative" to change them from the parent abstract.

# Describe the solution you'd like
Usage of relative for:
-"intelligence"
-"chapters"
-"time"
-"fun"
-"required_level"
-"max_level"

# Describe alternatives you've considered
Declaring every field for every book that isn't exactly the same as the parent abstract.

# Additional context
Books added by #37377, #40630, #40675, and #40756 are broken by the lack of this.

**Comment by Jerimee** [comment]
I've submitted this before as a bug at least twice, and people have said that it ought to be fixed.  See #39570

That said, I think that the "cascade" of relative copy-from I attempted to implement has been decided to be more trouble than it is worth. 

At the risk of quoting him out of context, KG said this about #40274 

> Here's the thing, this kind of hierarchy of inheritance arguably makes edits easier (I actually disagree, it makes one easy kind of edit easier, and it makes other more difficult edits harder), but it makes reading and understanding the data much more difficult. I've tried to review this PR at least five times now, and I keep getting frustrated and giving up because this is too complicated, you have to cross-reference multiple entries to find out the values of a single book, and then if you want to look at balance, you have to repeat that across multiple different books, and essentially recreate the level of redundancy you're trying to eliminate.
I need to write up some guidelines for data inheritance, but it's getting grossly overused already in areas like this and getting really unwieldy.

>There are two situations where copy-from should be used in mainline.

>Two things are nearly identical variants of each other.
>A group of entities always (not almost always, always) shares some set of properties, then one or two levels of abstracts can set up a very shallow and narrow hierarchy.

**Comment by anothersimulacrum** [comment]
#43144 Will do at least some of this.
