### ISSUE TITLE
Copy-from support for harvest lists

### ISSUE THREAD

**Issue by LyleSY** [CleverRaven/Cataclysm-DDA#42560]
# Is your feature request related to a problem? 

Copy-from is not yet implemented for harvest lists and it would be helpful for modding, possibly base game also

# Describe the thing 

Looks like this would require some coding work to add support

# Describe alternatives
Not essential, harvest lists still work

# Additional context
Discovered working on #42474

**Comment by LyleSY** [comment]
Sorry for any weirdness, posting on mobile

**Comment by KorGgenT** [comment]
additional info related to harvest lists: they are not currently implemented via generic_factory and should be. and then copy-from special keywords need to be added to generic_factory's `mandatory` and `optional` functions.
