### ISSUE TITLE
Ignoring the Inhaler mission eventually leads to persisting error

### ISSUE THREAD

**Issue by pescepalla** [CleverRaven/Cataclysm-DDA#42561]
# Describe the bug

If the player ignores the inhaler mission for long enough, it will fail, leading to an error every time the savegame is loaded.

The error:
>  DEBUG    : Requested non-existing faction 'solo_Ronnie 'Bio' Redman'

> FUNCTION : faction* faction_manager::get(const faction_id&, bool)
> FILE     : src/faction.cpp
> LINE     : 456

# Steps To Reproduce

1. Accept the Inhaler mission
2. Ignore it for a couple of weeks
3. Mission fails (maybe Ron dies?) and an error message is shown every time the savegame is loaded

# Expected behavior
Ronnie "Bio" Redman shouldn't be able to taunt the player from the grave.

# Versions and configuration
- OS: Arch Linux
- Game Version: O.E-2
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: Disable NPC Needs, No Rail Stations, sees-player icon (retrodays), Bionic slots, Alternative map keys

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-6398. However, I tested it through debug time fast-forward, so my testing could be invalid. 
I'm closing it for now, but if this is still an issue, ping me and I'll reopen it.
