### ISSUE TITLE
Wearing leg clothing lowers temperature

### ISSUE THREAD

**Issue by esavier** [CleverRaven/Cataclysm-DDA#42563]
# Description

Wearing more pieces of clothing lowers bodypart temperature

# Steps To Reproduce

0. optionally i was in lmao shelter
1. start the game, legs are cold, found fur trousers
2. wear trousers
3. legs temp drop from -60 to -90

# Expected behavior

duh... 
i guess the opposite to the effect mentioned above

# Versioning :

 - OS: gentoo linux
 - Game Version:  - terminal, 0.E-4611-ga5b97a8087
 - Ingame language: system (english)
 - Mods loaded: [dda, no_npc_food, crt_expansion, blazeindustries, aftershock, alt_map_key, no_Fungi, stats_through_kills, speedydex]

# screenshots:
## general state
![obraz](https://user-images.githubusercontent.com/5251231/89017272-5496c980-d31a-11ea-83f7-efc30b6d878d.png)
![obraz](https://user-images.githubusercontent.com/5251231/89017396-890a8580-d31a-11ea-9bba-9cf5a0333112.png)

## before
![obraz](https://user-images.githubusercontent.com/5251231/89017306-64161280-d31a-11ea-88b9-9c840cb86fec.png)
## afrer
![obraz](https://user-images.githubusercontent.com/5251231/89017332-71330180-d31a-11ea-8a9c-16aa14f681a0.png)

**Comment by ZhilkinSerg** [comment]
What are fur trousers? We do not have them in vanilla or in-repo mods.

**Comment by Duck13Tales** [comment]
It seems that as soon as you load a game you get temperatures way lower than what should. Sometimes I save with a part at 25 warmth and load with the same part at -60. It makes some food "cold" or even "frozen".

**Comment by esavier** [comment]
> What are fur trousers? We do not have them in vanilla or in-repo mods.

pardon sir, "fur pants", i also say armour and colour :smirk: 
and i was reporting from memory since i was unable to access my worstation
i am updating request

**Comment by esavier** [comment]
issue persist on 
`0.E-4643-gb31fb27112`
as @Duck13Tales mentioned this actually may be related to saving game since i just loaded it, but this cost me my leg and arm before save so i am not sure

**Comment by andrei8l** [comment]
There's currently a bug with setting weather on save game load.
This workaround solves the issue in my tests, but I'm not sure yet if it's the right solution:
```diff --git a/src/game.cpp b/src/game.cpp
index d581bef62e..836221693b 100644
--- a/src/game.cpp
+++ b/src/game.cpp
@@ -2935,6 +2935,8 @@ bool game::load( const save_t &name )
     validate_camps();
     validate_linked_vehicles();
     update_map( u );
+    weather.set_nextweather( calendar::turn );
+
     for( auto &e : u.inv_dump() ) {
         e->set_owner( get_player_character() );
     }
```

**Comment by esavier** [comment]
i am not sure if this will not have any long term side effets
however, good call :)
i will look into it tomorrow,

**Comment by Maleclypse** [comment]
Have you tried using a towel to see if the clothes are wet and thus causing the infinite wetness/cold?

**Comment by esavier** [comment]
> Have you tried using a towel to see if the clothes are wet and thus causing the infinite wetness/cold?
it deceases the amount of cold from -61 to -31, however there is no indicator what kind of clothing is actually wet? Also fur pants were spawned inside the shelter to debug the issue so i am sure those are not wet. There may be issue that some other parts of clothing can be wet and contribute to overall coldness.
I took everything covering my legs and i still have -54, after that wearing fur pants which should provide 80 warmth, makes my leg warmer but not much, from -54 to -30, however using tower in that setup actually makes my fur pants viable (to +14). i am guessing something is wrong in how the calculations are performed?

**Comment by anothersimulacrum** [comment]
@Ramza13 Could I request your review on the proposed patch above? You've been in the weather code recently.

**Comment by Ramza13** [comment]
So this is probably related to my weather changes.  I changed the way weather is updated and I think on game load that some values aren't getting updated.  I'll try to fix it.

**Comment by anothersimulacrum** [comment]
#45482 looks like the same issue, but has a save and can be reproduced.
