### ISSUE TITLE
Removing CBM from self yields a (filthy) item

### ISSUE THREAD

**Issue by pescepalla** [CleverRaven/Cataclysm-DDA#42568]
# Describe the bug

Removing a CBM from my own body produces a (filthy) item.

# Steps To Reproduce

1. Install CBM
2. Remove CBM

# Expected behavior
Removing a CBM from oneself should produce a faulty, non-sterile item. Even though C:DDA lore says that everyone is contaminated with the blob, not-yet-zombified people do not wear filthy clothing and do not yield tainted meat. Likewise, uninstalled CBMs should not be filthy.

# Versions and configuration

- OS: Arch Linux
- Game Version: O.E-2
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: Disable NPC Needs, No Rail Stations, sees-player icon (retrodays), Bionic slots, Alternative map keys

**Comment by Fris0uman** [comment]
Working as intended

**Comment by pescepalla** [comment]
@Fris0uman Why does butchering humans yield non-tainted meat then? Why aren't my clothes filthy? 

The (filthy) tag should be associated with zombified entities.

**Comment by Fris0uman** [comment]
Filthy is general organic messiness, if the CBM comes out of you it's going to be covered in blood and other unpleasant things hence the fillthy tag.

**Comment by pescepalla** [comment]
As I mentioned earlier, this would imply that any butchering or clothing found on dead bodies should be (filthy). But this is not the case.

There's another observation to be done: CBMs returned to user after an installation failure are not filthy and yet they are supposed to have been inside the character. For consistency, they should be also filthy, but they aren't.

**Comment by Fris0uman** [comment]
> user after an installation failure are not filthy 

They're not? That's a bug then.

> clothing found on dead bodies should be (filthy)

I gues they could be, depending on how fresh the corpses are.

But CBM extracted from a body being filthy is not a bug it's the intended behaviour.

**Comment by pescepalla** [comment]
But filth isn't found on not on dead bodies, no matter how fresh or old the bodies are, nor it's not on live NPCs, not even after they're gored and butchered. (Not that I would expect the average post-apocalyptic survivor to shower often).

Filth is always and only associated with zombies.

**Comment by pescepalla** [comment]
> feel free to open a feature request for that, or make the change yourself if you're able

Why should I? To me, filth is a consequence to the blob. I'm fine with it being only on zombies.

**Comment by Fris0uman** [comment]
> Why should I? To me, filth is a consequence to the blob. I'm fine with it being only on zombies.

Ok, but you're wrong. See previous comment `Filthy is general organic messiness`. If you think this is too confusing you could open a feature request (or rename this one) to change the name of the filthy flag so someting else `(bloody)` or `(gory)` maybe.

**Comment by pescepalla** [comment]
> Filthy is general organic messiness

Yep, that's what you said, however, with all due respect, the game's subtext seems to prove the opposite.

Don't get me wrong, I would be fine if the community decided that your opinion is the correct one, but as filth is represented now in-game, the association with blob infection is simply too strong.

Take for instance the `bloody rag` item. It's not filthy. It's a bloody rag.
Clothing on corpses? It's clean as far as "filth" is concerned.

Deciding that filth is simple gore contradicts too many aspects of the game as it is now.

**Comment by Fris0uman** [comment]
All right we're going in circle. So regarding CBM extracted from a body being filthy and requiring to be washed ( because that's the important part) that's not a bug that's intended behaviour. Now if you want to start a project to harmonise filthy, bloody and other adjectives accross the game feel free to do so.

**Comment by pescepalla** [comment]
Closing as per discussion on #42574.
