### ISSUE TITLE
What is filth anyway?

### ISSUE THREAD

**Issue by pescepalla** [CleverRaven/Cataclysm-DDA#42574]
# Is your feature request related to a problem? Please describe.
Filth is at the moment exclusively found on zombies, however @Fris0uman at #42568 suggests that it is not specifically blob-filth but simply gore. As a consequence, most clothing found on corpses should have the `filthy` tag. I can't imagine all those soldiers and scientists having died a peaceful death.

# Describe the solution you'd like
All the clothing found on corpses should be `filthy`. The only non-filthy clothing should be found on NPCs, in homes and in stores.

# Describe alternatives you've considered
The alternative would be to consider filth to be a byproduct of blob infection. In that case, CBMs extracted from a living character should not be `filthy` (see #42568).

**Comment by Duck13Tales** [comment]
But even if not filthy it would still probably be non-sterile and "faulty". So I don't see much difference if this is the only change... 

Clothes would become dirty and need to be cleaned regularly or we would need to poop or pee from time to time, but... I don't see much point into this...

**Comment by ZhilkinSerg** [comment]
Filth is something non-clean. The source of filth is currently irrelevant (and is actually different in different contexts) - it could be dirt, blood (or other body fluids), toxins, infectious agents, chemicals, whatever.

**Comment by pescepalla** [comment]
@Duck13Tales That was my whole point in #42568. For the difference, see my conclusion to this comment.

@ZhilkinSerg Fair enough, even though as to now the game suggests otherwise by associating filth with zombies only. C:DDA is full of non-clean, dirty, bloody, toxic, infectious stuff that is not filthy. Random corpses are one example, the "bloody rag" item is another, which should be a `rag (filthy)`. NPCs should drop filthy clothing when killed.

What I want to say is that the game is not at all consistent on how it determines whether something is filthy or not.

**Comment by ZhilkinSerg** [comment]
Yeah we know. Most things implemented before FILTHY tags was implemented will not be using it. Just start working on getting rid of these inconsistencies.

**Comment by ZhilkinSerg** [comment]
For the start I suggest extending `Item_group` group class (and related json loading code) with a new parameter that will allow spawning groups/items with custom flags. Then update corpses mapgen extra groups in json with `FILTHY` flag.
