### ISSUE TITLE
Tileset composer wont recognize offsets for sprites that are the default dimension.

### ISSUE THREAD

**Issue by John-Candlebury** [CleverRaven/Cataclysm-DDA#42576]
# Describe the bug

Using the tool compose.py, wont recognize the offeset fields for sprites that have the same dimensions as the tileset default.

# Steps To Reproduce

1. Go to  the cuteclysm repository https://github.com/pixel-32/CDDA-tileset
2. Compose the tileset using the script at  `Cataclysm-DDA\tools\gfx_tools`
3. Notice that despite especifying an offset in `tile_info.json` the `creatures.png` sprite sheet has no offset defined in the script geneated `tile_config.json` file.

# Expected behavior

Offset field is respected

**Comment by int-ua** [comment]
At first glance it seem like intended behavior? What's the use case of having offset for default-sized tiles?

**Comment by John-Candlebury** [comment]
The offset helps reinforce the illusion of visual depth within the set. especially when character/monster sprites are offset. As, the tileset is curently trying, but failing, to do

**Comment by int-ua** [comment]
I may be able to help with that a bit later. Can you meanwhile please add a screenshot to demo what result you want compared to what you get with current version?

**Comment by John-Candlebury** [comment]
Sure thing.

This is what I have.
![image](https://user-images.githubusercontent.com/5290912/89049247-32974a00-d30e-11ea-80b9-77e007d2d4a5.png)

vs the offset I'd like
![image](https://user-images.githubusercontent.com/5290912/89049085-f368f900-d30d-11ea-8a58-47e4020b7c0b.png)

**Comment by mlangsdorf** [comment]
so it looks like removing the explicit check for standard() should do what you want.

if I could just get vips to work on one of my machines I would be able to test that.
