### ISSUE TITLE
Items like batteries can be unloaded in the advanced inventory menu

### ISSUE THREAD

**Issue by AzyWng** [CleverRaven/Cataclysm-DDA#42573]
# Bug Description

When in the advanced inventory menu, items that are loaded into other items - batteries loaded into headlamps, for example - can be dropped in the advanced inventory menu, causing the battery to be unloaded.

# Steps To Reproduce

1. Load an item with a battery.
2. Open the advanced inventory menu and press I to bring up your inventory.
3. The battery that is loaded into the item should appear in the advanced inventory menu.
4. Select a different tile and drop the battery.
5. Your item should be unloaded, and the battery should be dropped.

# Expected behavior

The battery loaded into the item should not appear in the Advanced Inventory Menu, preventing players from accidentally unloading their items.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-4598-gf128070
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: dda, Disable NPC Needs, sees-player icon, retrodays, No Rail Stations, No Fungal Monsters

**Comment by Inglonias** [comment]
This is much more problematic for things like sealed cans of food, where simply dropping the food from your inventory also opens the cans.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.E-10390.
![изображение](https://user-images.githubusercontent.com/11132525/114922648-f9bbe880-9e3c-11eb-8863-251352fe3e3a.png)

Closing until reconfirmed.
