### ISSUE TITLE
Suggestion: Be possible to continue butchering instead of starting over from the beginning

### ISSUE THREAD

**Issue by Duck13Tales** [CleverRaven/Cataclysm-DDA#42586]
# Describe the bug

Sometimes when you are butchering or dissecting you need to stop midway to eat or deal with a random zed but when you do so it seems that you need to start over from the beginning.

It would be really nice if you could star from where you left just like with the recipes.

# Steps To Reproduce

1 - Start butchering or dissecting something
2 - Stop in the middle of the task
3 - Stark again and take note that you will need full time to finish the task at hand

# Expected behavior

When you are skinning, dissecting or butchering a corpse but you take a break in the middle, if you want to continue you usually will not need the same amount of time as if you were doing it from the start.

# Screenshots

Not needed.

# Versions and configuration

I am using using the CDDA 0.E-b10865 with the mods:

DDA
Disable NPC needs
Stats through skills
Stats through kills
SpeedyDex

# Additional context

I think it would be nice if it was the same for most tasks that allow you to stop in the middle.

**Comment by jbytheway** [comment]
This used to be possible, although it was a bit flaky.  So if it's not possible now I think this is a regression.

**Comment by Djinn247** [comment]
i agree that this needs to be looked at.
it does not make sense if you stop 40 minutes after starting full butcher that you have to spend another hour, making the total a maximum of double the intended amount of time for butchering.
