### ISSUE TITLE
 DEBUG    : error: tried to put an item into a pocket that can't fit into it while loading.  err: item too big

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#42609]
# Describe the bug

 DEBUG    : error: tried to put an item into a pocket that can't fit into it while loading.  err: item too big

 FUNCTION : void item_contents::combine(const item_contents&)
 FILE     : src/item_contents.cpp
 LINE     : 297

# Steps To Reproduce
just driving

# Expected behavior

# Screenshots

# Versions and configuration
10882
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5009239/debug.log)

# Additional context

**Comment by Night-Pryanik** [comment]
Unreproducible issue, closing until reconfirmed.
