### ISSUE TITLE
DEBUG    : Tried removing item from object which did not contain it

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#42619]
# Describe the bug
 DEBUG    : Tried removing item from object which did not contain it

 FUNCTION : item visitable<T>::remove_item(item&) [with T = item]
 FILE     : src/visitable.cpp
 LINE     : 542

# Steps To Reproduce
I was unloading the 5.56 bullets from a 5.56*45 ammo belt picked up from a humveee

# Expected behavior

# Screenshots

# Versions and configuration
10882
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5010551/debug.log)

# Additional context

**Comment by KorGgenT** [comment]
not enough information to fix
