### ISSUE TITLE
DEBUG    : tried to set ammo for jumper_cable which does not have ammo or a magazine

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#42618]
# Describe the bug

 DEBUG    : tried to set ammo for jumper_cable which does not have ammo or a magazine

 FUNCTION : void Item_modifier::modify(item&) const
 FILE     : src/item_group.cpp
 LINE     : 355

# Steps To Reproduce

# Expected behavior

# Screenshots

# Versions and configuration
10882

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5010423/debug.log)
# Additional context

**Comment by Night-Pryanik** [comment]
Unreproducible issue, closing until reconfirmed.
