### ISSUE TITLE
DEBUG    : item marloss_seed has zero volume (if zero volume is intentional you can suppress this error with the ZERO_WEIGHT flag)

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#42617]
# Describe the bug

 DEBUG    : item marloss_seed has zero volume (if zero volume is intentional you can suppress this error with the ZERO_WEIGHT flag)

 FUNCTION : void Item_factory::finalize_pre(itype&)
 FILE     : src/item_factory.cpp
 LINE     : 226

# Steps To Reproduce

# Expected behavior

# Screenshots

# Versions and configuration

10882

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5010398/debug.log)

# Additional context

**Comment by FuelType-Memes** [comment]
Please provide all the context, especially mod list

**Comment by matt32106** [comment]
The debug.log is attached

**Comment by FuelType-Memes** [comment]
Does it somehow invalidate the bug report template?

**Comment by matt32106** [comment]
if you want always the same format, automate the reporting. I am bored to copy paste, I prefer to play.
