### ISSUE TITLE
Crash When unloading container

### ISSUE THREAD

**Issue by sadSader** [CleverRaven/Cataclysm-DDA#42624]
# Describe the bug
Crash. 

# Steps To Reproduce

1. Have tin cup with inserted items.
2. Drop to tile with other items
3. Have space to store cup.
4. Do multiple pick up (',')
5. Choose "Spill liquid ..."

# Expected behavior
No crash, no spill liquid choice (cup had matchbook and lighter).

# Screenshots

# Versions and configuration

Platform     : Windows_x64
Graphics     : Tiles
Build number : #10885
Build version: 0.E-4667-g1d4ea08
Major version: 0.E

Ingame language: English
Mods dda, StatsThroughSkils, NoNPCNeeds
# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5010855/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5010857/debug.log)
[Arona.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5010863/Arona.zip)

**Comment by andrei8l** [comment]
I wasn't able to reproduce the crash from your save (after inserting the matchbook and lighter into the tin cup) with a linux build. Crash log appears to show a segfault in `item()` copy constructor which is pretty odd.

**Comment by Duck13Tales** [comment]
Did you try with the latest build in experimental?

**Comment by sadSader** [comment]
I can't reproduse same bug now, but shurely something wrong with cups.(Not checked reproducing)Same save1. insert purity ring, drop cup.2. Picked, chose spill.3. Ring duplicated, imposible insert ring in shown as empty cup. Also 10 stack of aspirin doesn't fit in cup.4. Insert 1 aspirin, duplicated. Shoud I update issue? 02.08.2020, 11:21, "andrei" <notifications@github.com>:
I wasn't able to reproduce the crash from your save (after inserting the matchbook and lighter into the tin cup) with a linux build. Crash log appears to show a segfault in item() copy constructor which is pretty odd.

**Comment by sadSader** [comment]
Updated game. No crash, but in fresh world:
1. Debug spawned tin cup, lighter, matchbook. 
2. Inserted lighter and matchbook in cup
3. Droped to flour all inventory.
4. Picked up, chose spill
5.  Lighter and matchbook was duplicated

**Comment by sadSader** [comment]
Fixed in recent builds.
