### ISSUE TITLE
Aftershock UPS can't be reloaded

### ISSUE THREAD

**Issue by souricelle** [CleverRaven/Cataclysm-DDA#42623]
UPS in Aftershock are different from vanilla, so this is Aftershock-specific. The UPS item in Aftershock states that it can be reloaded with standard batteries, but won't except light, medium, or heavy rechargable or disposable batteries, nor will it take storage batteries or plutonium fuel cells.

# Steps To Reproduce

1. Make a character in an Aftershock game
2. Spawn a UPS and any batteries you like
3. Try to reload the UPS. It should say that you do not have any batteries to recharge your UPS.

# Expected behavior

At least some types of batteries should charge the UPS. If that's not intended, then the item description should be updated and the reload command removed or reworded.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-4598-gf128070 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Hauntmachine** [comment]
I'm having the exact same issue. I've spawned every single battery possible through the debug menu, and none of them work. All I get is the "You don't have any batteries to reload your UPS" message. 

OS: Windows 10
Game Version: 0.E-5187-gb60a422
Graphics Version: Tiles
Game Language: System language
Mods loaded: 
Dark Days Ahead
Disable NPC Needs
Secronom
Aftershock
Arcana and Magic Items
Blaze Industries
C.R.I.T Expansion Mod
Magiclysm
XEAS
No Freeze
DinoMod
Cataclysm++
More Survivor Stuff
My Sweet Cataclysm
Mythical Martial Arts
No Rail Stations
Tankmod: Revived
Graphical Overmap
Graphical Overmap Magiclysm
Mutation Changes

**Comment by venum4k** [comment]
It looks like the problem is the UPS ammo type is set to "battery" which means it can be reloaded with the generic battery ammo but not directly from actual batteries. I spawned some and it worked fine. 
![image](https://user-images.githubusercontent.com/1928247/91598811-61c8c780-e95d-11ea-8be8-0b1befeba637.png)
So unless batteries get modified to transfer charge without it having to be unloaded I don't think it'll work.

**Comment by Maleclypse** [comment]
Doesn't the Aftershock UPS recharge in the recharging station?

**Comment by Maleclypse** [comment]
Confirmed UPS recharges in recharging station vehicle part.
