### ISSUE TITLE
M249 Crows II should not fire at fishes

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#42622]
# Is your feature request related to a problem? Please describe.
CROWS II units fire at fishes. While enjoyable to watch, it seems a bit dumb.

# Describe the solution you'd like
CROWS II (and maybe others automated units) should not fire at targets smaller than x.

# Describe alternatives you've considered
CROWS II (and maybe others automated units) should not fire at targets in the water.

# Additional context
Version 10882

**Comment by Nhatorama** [comment]
Someone might be able to have turrets pull the safemode manager information whenever there are targets withing range that need to be engaged or ignored.
