### ISSUE TITLE
git log missing tags cdda-jenkins-b10884 and cdda-jenkins-b10885

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#42630]
just did a pull from here and I see that the tags for cdda-jenkins-b10884 and cdda-jenkins-b10885 are missing from git log

**Comment by andrei8l** [comment]
Are you sure?
```
❯ git tag|rg 'cdda-jenkins-b1088[45]'
cdda-jenkins-b10884
cdda-jenkins-b10885
```

**Comment by matt32106** [comment]
I believe you but for some unknown reason I don't see them in my local log:
(base) hippo@hippo-camp:~/git/Cataclysm-DDA$ git tag|grep 'cdda-jenkins-b1088'
cdda-jenkins-b10880
cdda-jenkins-b10881
cdda-jenkins-b10882
cdda-jenkins-b10883

**Comment by matt32106** [comment]
I fixed that with
```
git fetch --tags upstream master
```
It looks like `pull` does not always do it.
