### ISSUE TITLE
Some non-Ascii characters are not shown correctly

### ISSUE THREAD

**Issue by Keepoccino** [CleverRaven/Cataclysm-DDA#42638]
# Describe the bug

Non-Ascii characters, like the german umlauts (ä, ö, ü) and some characters from other languages like the ñ as in español are shown either as some other characters or just as an empty box. (See screenshots below)

I suspect this is probably an issue with the encoding.

I have tested this on Windows, Android and Linux, but I can only reproduce it on Windows 10 and Android. Linux seems not to be affected by this issue.

# Steps To Reproduce

**Steps to reproduce for the screenshot below:**
1. Go to your settings under Interface -> Language and set it to german (Deutsch).
2. Open up the settings menu again.
3. There will be some texts that are not displayed correctly.

**Alternative steps to reproduce:**
1. Go to your settings under Interface -> Language.
2. You will see that in the description at the top where the languages are listed, some words like español will not be displayed correctly.

# Expected behavior

Those characters should be displayed correctly.

# Screenshots

I have underlined the incorrectly displayed characters in red.

![optionsMenu](https://user-images.githubusercontent.com/18090416/89110670-688f1800-d44d-11ea-9107-01a2b49bb054.png)

![ingame](https://user-images.githubusercontent.com/18090416/89110673-6d53cc00-d44d-11ea-9652-0e429ae1c06c.png)

![small](https://user-images.githubusercontent.com/18090416/89110726-e521f680-d44d-11ea-93a6-f76acdc1f078.png)

On android the characters look the same:
![android](https://user-images.githubusercontent.com/18090416/89110676-72188000-d44d-11ea-9e58-560e989b1f36.png)

# Versions and configuration

 - OS: Windows 10, Android 10 and also tested under openSuse 15.1, but the bug does not happen there.
 - Game Version: latest (0.E-4667-g1d4ea08)
 - Graphics version: Tiles
 - Ingame language: German

**Comment by Qrox** [comment]
Can you please post the content of you `config/fonts.json`?

**Comment by Keepoccino** [comment]
Sure, it should still be on a unmodified state.

```
{
  "typeface": [ "Terminus", "unifont" ],
  "map_typeface": [ "Terminus", "unifont" ],
  "overmap_typeface": [ "Terminus", "unifont" ]
}
```

The content of my `data/font` folder contains both, the `terminus.fon` and `unifont.ttf`.

**Comment by Qrox** [comment]
Hmm, if you remove "Terminus" and leave only "unifont" does it render correctly?

Like this:
```
{
  "typeface": [ "unifont" ],
  "map_typeface": [ "unifont" ],
  "overmap_typeface": [ "unifont" ]
}
```

**Comment by Keepoccino** [comment]
Yes, after the change the texts are rendered correctly

**Comment by Qrox** [comment]
It seems to be something wrong with the `terminus.fon` (encoding perhaps?). I downloaded a ttf version of `terminus` and it rendered correctly.

**Comment by Keepoccino** [comment]
For me it also renders correctly with the ttf version of terminus.

Is there a reason why `terminus.fon` is used instead of the ttf version?
If not, it might be better to use the ttf version per default as it doesn't have these issues.

**Comment by Keepoccino** [comment]
I have tried to compile the `.fon` version of terminus myself. The file does not have those those issues, but the downside is that it only supports font size 14, since I dont know how to add the other font sizes to a `.fon` file.

Additionaly I have exported a version of `terminus.fon` with fontforge, which supports other sizes than 14, but I guess those have been upscaled from the font size 14. The error does not happen there as well.

Both can be found in [Terminus.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5085811/Terminus.zip)


I think that it has something to do with the mapping inside the original Terminus font.

### Here are my findings for the mappings in the original font so far:

The characters till U+00BF ( ¿ ) are being printed correctly.

After that till U+00DE ( Þ ) all characters are just displayed as boxes, so its hard to tell where they are being mapped to, but they should be displayable, so the mapping is definitely wrong there.

The character U+00DF ( ß ) is probably mapped to U+2017 ( ‗ ).

The whole block U+00E0 ( à ) - U+00FF ( ÿ ) is mapped to hebrew characters U+05D0 ( א ) - U+05EF.

Maybe this information is somehow helpful, but I do not really see a pattern there.

**Comment by EvgenijM86** [comment]
I don't know if its related by cars now show empty spaces instead of graphics or symbols, despite having components installed in those spaces:

![image](https://user-images.githubusercontent.com/430076/90510993-5ef2f900-e14b-11ea-921f-94c1a37de626.png)
