### ISSUE TITLE
Bodypart related crash when approaching NPC's corpse

### ISSUE THREAD

**Issue by ScarPan** [CleverRaven/Cataclysm-DDA#42644]
# Describe the bug

When approaching a certain point of current sub-map, error messages of Bodypart of a certain NPC's corpse will pop-up and crash the game.

# Steps To Reproduce

1. Load Save provided
2. Go straight north for 10 steps

# Expected behavior

Aforementioned error messages will pop-up and segmentation fault crash follows.

# Screenshots

![](https://aws1.discourse-cdn.com/standard11/uploads/cataclysmdda/original/2X/5/5180cdd1c570034a43b17d78269e29654f967f16.png)
, below error message would pop up related to Bodypart.
![](https://aws1.discourse-cdn.com/standard11/uploads/cataclysmdda/original/2X/8/83ffee36b8e7731c170047a5baf9d6207a3880f4.png)
[Rion.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5011852/Rion.zip)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-4687-g96f3a03 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    <color_light_red>Secronom</color> [secronom],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    PKs Rebalancing [PK_REBALANCE],
    Alternative Map Key [alt_map_key],
    Cataclysm++ [Cata++],
    Crazy Cataclysm [crazy_cataclysm],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Mythical Martial Arts [MMA],
    Caches [P_Caches],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    Infinite Stamina [InfStamina],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

- Save File
- Crash Log
[Rion.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5011854/Rion.zip)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5011855/crash.log)

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/bodypart-related-crash/24334/8

**Comment by Fris0uman** [comment]
I can't reproduce it. Loading save an walking north untill getting stuck in a web in the forest and nothing happened. This might have been caused by one of your third party mods.

**Comment by ScarPan** [comment]
> I can't reproduce it. Loading save an walking north untill getting stuck in a web in the forest and nothing happened. This might have been caused by one of your third party mods.
> 
> EDIT: Actually I can't find any corpse

Thank you for helping look into this.

Oh well, I will change loaded mods and see if anything changes.

**Comment by Chailles** [comment]
I was having a similar issue with the Mutation Changes mod, it wasn't updated for the changes made in #39068

Basically the mutations.json in it was referencing body parts that don't exist anymore. From the look of your modlist, PKs Rebalancing is the most likely candidate. 

From what it looks like, the body parts just need to be lower case now, so "arm_l" instead of "ARM_L" and so on. I've not done any extensive testing on that solution, but it's stopped the crashes for me at the very least.

**Comment by ScarPan** [comment]
> I was having a similar issue with the Mutation Changes mod, it wasn't updated for the changes made in #39068
> 
> Basically the mutations.json in it was referencing body parts that don't exist anymore. From the look of your modlist, PKs Rebalancing is the most likely candidate.
> 
> From what it looks like, the body parts just need to be lower case now, so "arm_l" instead of "ARM_L" and so on. I've not done any extensive testing on that solution, but it's stopped the crashes for me at the very least.

Thank you! I will try to manually change PK's Re-balancing mod's data and see if that fixes it. Or I could just wait for the mod update.

Much appreciated for the help!
