### ISSUE TITLE
Basal Metabolic Rate issue?

### ISSUE THREAD

**Issue by MrWoot** [CleverRaven/Cataclysm-DDA#42651]
As I began construction of a longsword, I noticed I would become famished within an hour from full.  I checked debug info, and saw my metabolic rate as 7196, which seems abnormally high.  I did some further testing and calculating with some online calculators, and testing in the game.  I ran a debug after sleeping and got 1832, which seems close enough the calculated rate of 1717 I got online.  I walked outside and checked again, and recorded a whopping 14656!  

# Steps To Reproduce

Checking metabolic rate

# Expected behavior

Metabolic rate should be in-line (or at least within a spitting distance)

 with real-world values, so that one isn't famished after an hour

# Screenshots

![CharStats](https://user-images.githubusercontent.com/20099648/89126502-04536f00-d4b4-11ea-961f-94f2ce9d528b.png)
![AfterSleeping](https://user-images.githubusercontent.com/20099648/89126505-0b7a7d00-d4b4-11ea-8193-87f4f81aa82e.png)
![WalkedOutside](https://user-images.githubusercontent.com/20099648/89126508-0e756d80-d4b4-11ea-95e7-e1d3e79da076.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-4703-g8fa6d13 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Mining Mod [Mining_Mod],
    Mythical Martial Arts [MMA]
]

# Additional context

Attached is save game

[manual_backup_bug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5012368/manual_backup_bug.zip)

**Comment by anothersimulacrum** [comment]
There is no issue with those rates, they are what you get for continuing whatever the most strenuous activity of the last 5 minutes was for 24 hours, and are calculated from real world values. What activity levels certain activities are may be erroneous, however.

**Comment by MrWoot** [comment]
Ok, but 14000?  After walking?  Really?

It seems like metabolic rate should be capped at some multiple of BMR; I'm seeing 1.9 for professional athletes and marathon runners.

**Comment by anothersimulacrum** [comment]
Walking is the same as crafting, it's about 8000 to walk for 24 hour hours sraight.
14000 is running, and yes, that's what you'd get for running 24 hours straight.

**Comment by Zireael07** [comment]
Yyy, why is the game assuming the character is running for 24 h WHILE crafting?

**Comment by anothersimulacrum** [comment]
It's not, I don't know where you got that.
