### ISSUE TITLE
Default key for Toggle Full Screen mode.

### ISSUE THREAD

**Issue by NathanGibbs3** [CleverRaven/Cataclysm-DDA#42657]
# Unable to switch out of full screen mode on new install.
Found this a bit frustrating. :smile:
When running on a dual monitor system, the game starts on one screen in full screen mode.
I wish to move it to the other screen.
I had to assign a key to the toggle full screen command before I was able to switch out of full screen mode and move the game window.
It would be really nice if a key was already assigned to that function on a new install.

# Describe the solution you'd like
Assign a key to this function in future versions.
For Example Firefox uses F11 for this.

**Comment by ZhilkinSerg** [comment]
Display can be set through options menu.

**Comment by ZhilkinSerg** [comment]
Also this commands need to start working before game starts to be really useful.

**Comment by NathanGibbs3** [comment]
Thank You for pointing out where to find the setting for that. :smile:
