### ISSUE TITLE
Analyze Zombie Blood

### ISSUE THREAD

**Issue by Pathfinder118** [CleverRaven/Cataclysm-DDA#42652]
When using the computer terminal to analyze zombie blood with a blood kit (and a usb in inventory) the computer gives the standard option to analyze the blood, however when selecting this option, you are presented with press any key to continue, which only brings back up the menu to analyze the blood resulting in an infinite loop that never completes the analysis. 

The terminal arrives in a press any key loop that allows you to select analyze blood as option 1, no matter wither pressing 1 or enter or return it arrives at press any key, bringing back up the analyze blood option in an unending loop. (blood kit with zombie blood is in centrifuge, and usb in inventory)

# Steps To Reproduce

1. Make a player the only unique thing im doing is playing the medieval challenge, and I may have cheated a bit to teleport around, but I have replicated this issue with a character that is/has done neither of those.

# Expected behavior

The computer will not add the information to the usb even though its in the inventory instead running a loop indefinitely. 

# Screenshots

# Versions and configuration

Please complete the following information; you can now go to:
    - OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-4703-g8fa6d13 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Cataclysm++ [Cata++],
    Bionic Slots [cbm_slots]
]

 - OS: windows 10
 - Game Version: the one listed above and the three previous versions (all experimental)
 - Graphics version: Tiles (undead person legacy)
 - Ingame language: english
 - Mods loaded: dda, cataclysm ++, bionic slots, disable npc needs
 -->

# Additional context

the game does not crash, it just gets into a loop preventing the mission from being completed.

I have edited my save a bit by adding mutations to the churl class (mostly becoming a fey and giving myself the option to read) I have however replicated this issue with a character class that is not the medieval peasant although that character has also mutated a bit.

I have solved the issue on my end by editing the mission as completed but it would be nice to not have to disable achievements to progress the storyline, thanks for any effort made to solve this issue, maybe its just me!

**Comment by Bulletfang** [comment]
I've encountered this bug as well, despite having everything, analyzing the blood doesn't progress the quest. I've had to depopulate half a town of zombies to get to the centrifuge, very frustrating.

**Comment by DrewTuber** [comment]
I cleared out an entire 3x3 hospital and 5 levels of a Lab before finding a centrifuge before running into the exact issue described here. Just stuck in an infinite loop of Analyze Blood > Press any key... > Analyze Blood > etc.

On the plus side I got a lot of guns now.
