### ISSUE TITLE
Riot control platforms have arms, legs and torsos

### ISSUE THREAD

**Issue by PenceGL** [CleverRaven/Cataclysm-DDA#42676]
# Describe the bug

Wandering along and noticed a zombie attacking a riot control platform on its legs, arms, and torso which seemed really goofy. I assume that these are supposed to be immobile turrets that don't have arms and legs, since their description states they need a human to relocate them, and they also have many tags in common to the CROWS turrets.

I'm not sure of an easy way to check if this is happening with other turrets too, but is probably worth a look.

# Steps To Reproduce

Witness an NPC attacking a riot control platform.

# Expected behavior

Instead of "_The zombie bites the riot control platform's right arm/leg/torso_" 

it should just be

 "_The zombie bites the riot control platform_"

# Screenshots

![cataclysm-tiles_6P0bkWKvi6](https://user-images.githubusercontent.com/8877847/89219569-9e3f1880-d595-11ea-9166-d55b2188f78f.png)

# Versions and configuration

- OS: Windows 10.0 1903
- Game Version: 0.E-4787-g5cc59e1 [64-bit]
- Graphics Version: Tiles
- Game Language: English
- Mods loaded: 
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key]

**Comment by Fris0uman** [comment]
That's just how the text is displayed, it actually only has a torso and a head like every other monster.

**Comment by PenceGL** [comment]
> That's just how the text is displayed, it actually only has a torso and a head like every other monster.

So are you saying it's correct? Even if it only had a torso and head, the text is still showing arms as well. It breaks immersion because it looks ridiculous.

**Comment by Fris0uman** [comment]
No just saying that's only a display bug and nothing deeper. This issue is a duplicate of this one https://github.com/CleverRaven/Cataclysm-DDA/issues/37391

**Comment by PenceGL** [comment]
Thanks for linking those. I always try searching for a few things before making a new issue post, but I think I was being too specific. Guess this one can be closed then.
