### ISSUE TITLE
Egg required recipes dont use bird's eggs

### ISSUE THREAD

**Issue by sashakiller33** [CleverRaven/Cataclysm-DDA#42673]
# Describe the bug

Recipies that require eggs cannot use bird eggs to cook them.

# Steps To Reproduce

1. Make your cooking skill big enought to make omlet.
2. Look at recipe of it.
3. See there are no bird egg in it.

# Expected behavior

Expected that i could make omlet using egg from chicken and not dinosaur.

# Screenshots
![image](https://user-images.githubusercontent.com/1785731/89200672-8dfd5c80-d5da-11ea-860d-5efbd0ab0b01.png)
![image](https://user-images.githubusercontent.com/1785731/89200734-a2d9f000-d5da-11ea-972b-8f43cc683ace.png)

# Versions and configuration
Used last experimental version 10890

 - OS: Windows 10
    - OS Version: 10.0 1903
- Game Version: 0.E-4787-g5cc59e1 [64-bit]
- Graphics Version: Tiles
- Game Language: Русский [ru]
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у NPC [no_npc_food],
    Aftershock [aftershock],
    Магиклизм [magiclysm],
    Miscellaneous Magiclysm Expansions [demon_spider_a],
    PKs Rebalancing [PK_REBALANCE],
    Cataclysm++ [Cata++],
    Графическая карта [Graphical_Overmap],
    <color_light_red>Secronom</color> [secronom],
    Arcana and Magic Items [Arcana],
    Blaze Industries [blazeindustries],
    Расширение К.Р.И.Т. [crt_expansion],
    PK Wildlife Beta 2.0 [PK_Wildlife],
    Modular Turrets Remake [modular_turrets_remake],
    Civilian Salvaged Robots [civilian_salvaged_robots],
    Automations [robot_automation],
    More Makeshift Stuff [makeshift_stuff],
    Packaging [Packaging],
    ДиноМод [DinoMod],
    Draco's Pig Mod [DracoPigMod],
    Мифические стили ближнего боя [MMA],
    Caches [P_Caches],
    Набор военных профессий от Fuji [fuji_mpp],
    Характеристики за убийства [stats_through_kills],
    Mining Mod [Mining_Mod],
    Без ж/д станций [No_Rail_Stations],
    Графическая карта - Маглицизм [Graphical_Overmap_Magiclysm],
    Генерация карты без городов [ruralbiome]
]

# Additional context

Look's like in one of the update of dino mod deleted reference to birds egg used to cook recipes.

**Comment by MasterLiKhao** [comment]
I have also noticed that unfertilized bird eggs are unavailable when you want to prepare any cooking recipe that uses eggs of some kind. You can eat them directly, though, which doesn't cause food poisoning even though you are eating RAW EGGS, which something that even IRL is almost guaranteed to give you salmonella.

**Comment by Maleclypse** [comment]
@LyleSY.  Let me know if there is something I can do to help.

**Comment by Rivet-the-Zombie** [comment]
>You can eat them directly, though, which doesn't cause food poisoning even though you are eating RAW EGGS, which is something that even IRL is almost guaranteed to give you salmonella.

[It's actually really rare to contract salmonella from eggs.](https://slate.com/technology/2014/03/salmonella-and-raw-eggs-how-ive-eaten-tons-of-cookie-dough-and-never-gotten-sick.html)

**Comment by LyleSY** [comment]
Ugh, thanks. Looks like requirements lists don't work like other lists. I'll get a fix going tonight if no one beats me to it.
