### ISSUE TITLE
Helicopter Crash scenario can result in a turn zero death.

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#42678]
# Describe the bug

When starting with the helicopter crash scenario, you can sometimes just die instantly after the game starts

# Steps To Reproduce
Create a character using the Helicopter crash scenario. If you don't start off dead, you got lucky. Try again.

# Expected behavior
Not dying on turn zero

# Screenshots

![image](https://user-images.githubusercontent.com/2125926/89221964-2deac400-d5a2-11ea-980a-a136fbde424b.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-4796-gda25633 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi],
    Disable NPC Needs [no_npc_food]
]

# Additional context

**Comment by TheMasterGear** [comment]
I guess you didn't survive the crash then?

**Comment by Inglonias** [comment]
I understand that from a realistic perspective but from a story perspective its utterly pointless.

**Comment by anothersimulacrum** [comment]
It's not realistic, if it were realistic, you wouldn't be allowed to start as someone already dead.

**Comment by TheMasterGear** [comment]
All fair points, I was only joking though when I made my post.
