### ISSUE TITLE
Segment Fault Crash on Load

### ISSUE THREAD

**Issue by Orange01gaming** [CleverRaven/Cataclysm-DDA#42684]
# Describe the bug

 After updating the game via Remroy's Luancher, I try to launch the game and it kicks me back to the main menu when I try to load up an old save.  

# Steps To Reproduce

Load up attached save file with current build

# Expected behavior

Game launches 

# Versions and configuration

 - OS: Windows 10.0 1909
 - Game Version: 0.E-4795-g20b4523 (tiles)
 - Graphics version: Tiles
 - Ingame language: English
 - Mods Loaded:
    Dark Days Ahead [dda],
    PKs Rebalancing [PK_REBALANCE],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Mutant NPCs [mutant_npcs]

# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5017820/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5017823/debug.log)

Save file was too big to upload, link to drive file: 
https://drive.google.com/file/d/1LpxVp8nkb4AHl3_P25O0GhtwZHHLTYMp/view?usp=sharing

**Comment by ZhilkinSerg** [comment]
Are you using PK mod version which is compatible with game version?

**Comment by Orange01gaming** [comment]
It is a few weeks old.

**Comment by Night-Pryanik** [comment]
@Orange01gaming have you encountered this issue since then?
