### ISSUE TITLE
Mutation Fur bodytemp_modifiers is working backwards 

### ISSUE THREAD

**Issue by TheMasterGear** [CleverRaven/Cataclysm-DDA#42696]
**Describe the bug**
 I have been editing the JSON for a few weeks now and wanted to make my own mutations mod. This all started when I was a bear mutant and I was getting oh so very overheated during the late spring.

![BodyTem](https://user-images.githubusercontent.com/60374171/89239618-b596f980-d5c7-11ea-8964-f8d1e29668b2.png)

"bodytemp_modifiers": [ 750, 1500 ],
In the JSON file, "750" value will add 15 points of warmth in-game when not overheating,
And "1500" will add 30 points of warmth when overheating. This seems to me to be the opposite of what's implied in the comment highlighted in the image above. This makes fur a worst version of clothes in every way minus the slight encumberments.

**Environment**
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 2020.06-283-gb4f71b8f2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]

*This still happens in newer releases*

**To Reproduce**
1. Start a new game during the winter and summer
2. give the player a fur mutation of any kind
3. Fur will use the 750 heating value during the winter and 1500 value during the summer.

**Expected behavior**
bodytemp_modifiers for fur should use inverse bodytemp_modifiers values.
"bodytemp_modifiers": [ 1500, 750 ],

**Comment by Fris0uman** [comment]
Quick look at the code suggest those two values [ 750, 1500 ] are useless since the code only uses (1500 - 750), inverting them would just make fur give a negative heat bonus.

```cpp
            if( desired < get_part_temp_conv( bp ) ) {
                // Too hot, can't help here
            } else if( desired < get_part_temp_conv( bp ) + bonus_warmth ) {
                // Use some heat, but not all of it
                set_part_temp_conv( bp, desired );
            } else {
                // Use all the heat
                mod_part_temp_conv( bp, bonus_warmth );
            }
```
This seem to be the code you want to look at: if you're colder than comfortable you get a bumped up to comfortable, if you're too hot you don't get anything and in every other case you get the full bonus.

**Comment by TheMasterGear** [comment]
Well with changing the mutation JSON file, this is what I got.

Mid Summer at noon, no fur
![no fur](https://user-images.githubusercontent.com/60374171/89740857-9e8a5880-da5a-11ea-93fb-9536c3d63e14.png)



Mid Summer at noon, with fur set to  [ 1500, 750 ] 
![fur mod](https://user-images.githubusercontent.com/60374171/89740861-a2b67600-da5a-11ea-8188-7b0a5f5e31f1.png)

Mid Summer at noon, with fur set to  [ 750, 1500 ] 
![fur normal](https://user-images.githubusercontent.com/60374171/89740873-b82ba000-da5a-11ea-86d7-278357562b77.png)


Mid winter 8 in the morning, no fur 
![no fur cold2](https://user-images.githubusercontent.com/60374171/89740633-6da92400-da58-11ea-9613-20f1ba6155dc.png)

Mid winter 8am, fur set to  [ 1500, 750 ] 
![fur mod cold](https://user-images.githubusercontent.com/60374171/89740644-887b9880-da58-11ea-8043-7150328bfc14.png)

Mid winter 8am, fur set to  [ 750, 1500 ] 
![furry unmoded cold](https://user-images.githubusercontent.com/60374171/89740637-78fc4f80-da58-11ea-8ed7-740b7c1ff83c.png)

It seems that the 1500 value is always used in the cold, but if it's swapped the 750 is used during the summer.
