### ISSUE TITLE
Survivor Utility Belt Qualities not working

### ISSUE THREAD

**Issue by Yurameki** [CleverRaven/Cataclysm-DDA#42702]
# Describe the bug
The tool qualities of the "Survivor Utility Belt" do not function for crafting or actions. Despite displaying as having the laundry list of qualities of the tools used to assemble it.

# Steps To Reproduce
1.Produce a survivor utility belt
2. Discard any remaining tools and take only the utility belt.
3. Be far enough away they can't be involved in crafting / actions. 
4.Attempt an action or craft, for instance craft an improvised lockpick. 
5. Note that you cannot because you don't have a tool with the correct qualities despite the utility belt either being nearby, in your inventory or on your person.

# Screenshots

[imgur screenshots](https://imgur.com/a/dLIfnCu)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-4795-g20b4523 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Arcana and Magic Items [Arcana],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Nechronica Redux [Nechronica_Redux],
    Add Rice [rice],
    Alexs Mutant Power Armor [a_mutated_arsenal],
    Animal Summoner Item [Summons_animals],
    Modular Turrets Remake [modular_turrets_remake],
    Civilian Salvaged Robots [civilian_salvaged_robots],
    Automations [robot_automation],
    BioCo Content [bioco],
    Bionics Systems Recipes [bio_recipes],
    Camping tools [camping_tools],
    CBM Equipment [CBM_Arms],
    CIVILIAN POWER ARMOR [CIVILIANPOWAAA],
    Craft Ammo Mags - ERG [SD_Magcrafting_Realguns_Extension],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    Garden Pots [growable-pots],
    Gun Cotton [guncotton],
    Homemade Fungicide [homemade_fungicide],
    Incinerator [incinerator],
    Large capacity storage CBMs [eps_cbm],
    Makeshift engine hoist [makeshift_engine_hoist_mod],
    Miscellaneous Magiclysm Expansions [demon_spider_a],
    More Armors [More_Armors],
    More Survival Tools [More_Survival_Tools],
    More Vehicles [mo_veh],
    Portable Coolers [portable_cooler],
    Power_Armor_Additions [Power_Armor_Additions],
    Realistic Fridge Size [Realistic_Fridge_Size],
    Space Heater [space_heater],
    Survivor's Lost item [Survivors_Lost_item],
    Survivor crowbar [surv_crowbar],
    The Cool Mod [cool_mod],
    The Glory Of Cereal! [CerealMod],
    Thermal Electric UPS [thermal_ups],
    Thrown Armor & Weapon Pack [Thrown],
    More Insects [mo_insects],
    More Monsters [mo_monsters],
    Alternative Map Key [alt_map_key],
    Cataclysm++ [Cata++],
    Even More Mutations [even_more_mutations],
    Mining Mod [Mining_Mod],
    More Survivor Stuff [more_survivor_stuff],
    Mythical Martial Arts [MMA],
    Mythical Martial Arts - Magiclysm [MMA_Magiclysm],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Vampiric Stuff [vamp_stuff],
    Vampiric Stuff + Arcana Mod Extension [vamp_stuff+arcana],
    Alternative Basement Layouts [basement_extension],
    Caches [P_Caches],
    More City Locations [cityside],
    Tankmod: Revived [Tankmod_Revived],
    Necromancy [necromancy],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    sees-player icon, retrodays [sees_player_retro],
    Artyoms' Gun Emporium - Reloaded [Arts' Guns],
    Sunken Bridges [sunken_bridges],
    Fuji's Military Profession Pack [fuji_mpp],
    More Character Creation Choice [more_char_creation],
    SpeedyDex [speedydex],
    SpeedyDex Buffs [speedydexbuffs],
    Stats Through Skills [StatsThroughSkills],
    Arcana - UndeadPeople Tileset [ArcanaUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP],
    ZSFIXED_C:DDA Extra Professions & Gears [ZSFIXED_cddaxp]
]

# Additional context

**Comment by ZhilkinSerg** [comment]
Try reproducing it in vanilla without any mods.

**Comment by Yurameki** [comment]
> Try reproducing it in vanilla without any mods.

Good call @ZhilkinSerg, it works in vanilla with no mods. Now I wonder how I go about finding out which mod is breaking it...any suggestions?

**Comment by ZhilkinSerg** [comment]
Just search for affected item id in your mods folders.

**Comment by Yurameki** [comment]
> Just search for affected item id in your mods folders.

So the item ID appears to be "survivor_belt", which I checked for, and it only shows up in "copy-from" statements, except for aftershock which seems to have it also in it's obsolete json. But I'm not running Aftershock. So I'm really at a loss here :-\

**Comment by ZhilkinSerg** [comment]
> 
> ... and it only shows up in "copy-from" statements

You have found the offending mods then - they copied that vanilla item and made some settings to them which caused the issue.

**Comment by Yurameki** [comment]
> > ... and it only shows up in "copy-from" statements
> 
> You have found the offending mods then - they copied that vanilla item and made some settings to them which caused the issue.

Sorry, I wasn't very clear, the only mod that has copy-from for that specific ID is Aftershock, which I'm not running in this world. The next closets is CRIT expansion which copies the survivor_belt_notools, which isn't the same item, and is in fact the precursor item that you use to make the utility belt.

The only entry in a mod I'm running is this one, which is a recipe that uses the belt in it, unless I'm mistaken?

`  {
    "result": "cddaxp_survrbelt",
    "type": "recipe",
    "category": "CC_ARMOR",
    "subcategory": "CSC_ARMOR_OTHER",
    "skill_used": "fabrication",
    "difficulty": 4,
    "skills_required": [ "tailor", 6 ],
    "time": 10000,
    "reversible": false,
    "autolearn": true,
    "byproducts": [ [ "leather", 6 ] ],
    "using": [ [ "filament", 10 ] ],
    "qualities": [ { "id": "SEW", "level": 1 } ],
    "components": [ [ [ "survivor_belt", 1 ] ], [ [ "e_tool", 1 ] ], [ [ "halligan", 1 ] ], [ [ "sholster", 1 ] ] ]
  }`

**Comment by Yurameki** [comment]
Verified that this is actually a vanilla issue!

Qualities work if you have nothing in the pocket, but once I throw a weapon into the pocket the qualities no longer function!

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/survivor-utility-belt-qualities-not-working-0-e/24326/6

**Comment by andrei8l** [comment]
IMHO, the survivor belt should be deprecated in favor of tool belt. The other survivor gear have some logic behind them, but there's no way our survivor can make a better tool belt from scraps.
![Untitled](https://user-images.githubusercontent.com/68240139/89707241-09f9fa80-d975-11ea-9f80-e1d8d564e0b6.png)

**Comment by Yurameki** [comment]
> IMHO, the survivor belt should be deprecated in favor of tool belt. The other survivor gear have some logic behind them, but there's no way our survivor can make a better tool belt from scraps.
> ![Untitled](https://user-images.githubusercontent.com/68240139/89707241-09f9fa80-d975-11ea-9f80-e1d8d564e0b6.png)

Strongly disagree, it should probably have a mild use time penalty. However, a tool belt is made for quick access to tools, without really worrying much about encumbrance in real life. The survivor utility belt is as described, an armoured belt piece, think like a paramilitary cummberbund design, with pockets and hangars for the tools. The intention is to minimize encumbrance while still having them reasonably available. That means it takes a bit longer to access them, but they're there. And that's an entirely reasonable thing for someone to stitch together out of some nylon and kevlar, as much as any other item is in the game. I'm not particularly skilled at sewing and other needed skills, but my partner could throw one together in an afternoon if she had the scrap material together.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/survivor-belt-tools-not-applying-to-crafting/24748/2
