### ISSUE TITLE
Sourbread starters don`t give back the glass jar

### ISSUE THREAD

**Issue by Katanasoul91** [CleverRaven/Cataclysm-DDA#42707]
# Describe the bug
Both the juvenile sourbread starter and the freshly fed sourbread starter consume the jar you use to create them and don`t return the item after the process is done.

# Steps To Reproduce
1. Spawn or craft both items.
2. Wait until they are both done.
3. Activate them.

# Expected behavior
Each of them should give back the Glass Jug used in their crafting when they become Sourbread Starters.

# Suggestion
When you craft a freshly fed sourbread starter they give you two of them per crafting, add "Portions: 2" in the description and change crafting recipe to 2 glass jug so each of these can give back their respective glass jug

**Comment by Profugo-Barbatus** [comment]
Glass adds volume, texture and crunch to the final product of the bread. Its an acquired, coppery taste.

**Comment by venum4k** [comment]
It looks like it's supposed to emulate splitting the starter so you're adding another jar to the mix (2 jars total) and getting 2 starters. You can disassemble them to get the jars back.

**Comment by wapcaplet** [comment]
After a lot of playtesting on 801b7869, I think the sourdough starters are mostly working as intended. The glass jar used in the initial crafting becomes an explicit part of each phase of the starters (and is in the description, and even the looks_like). The jar stays an integral part of the starter unless you `D`isassemble it (at the juvenile or freshly-fed phase), at which time you get back the jar (but lose the starter).

Crafting the initial `juvenile sourdough starter` consumes a jar, along with the flour and water. After 6 days it's ready to activate.

When `a`ctivating the `juvenile sourdough starter`, it is converted to a `freshly fed sourdough starter` (still in the jar). After 1 more day, it will be ready to activate.

When `a`ctivating the `freshly fed sourdough starter`, it becomes a `sourdough starter` (mature, ready to bake with - and still in the jar).

Crafting sourdough bread from a mature `sourdough starter` yields the bread, and a byproduct `freshly fed sourdough starter` (again, still in the jar).

You can `D`isassemble the starter when it is `juvenile` or `freshly fed` to get the jar back (but you will lose the starter). I don't know why there is no equivalent disassembly for the mature `sourdough starter`, but after all that waiting you'd be better off baking some bread with it first, then diassemble the new `freshly fed` starter to get back your jar.

There are a lot of things weird and unrealistic about this process (for example there's nothing special about a jar - IRL you can make and keep a starter in a tupperware or coffee mug if you're so inclined) but this part looks to me like it's working correctly.

Game Version: 0.E-5499-g801b7869d6 [64-bit]
