### ISSUE TITLE
Sealed yeast culture don`t give you yeast

### ISSUE THREAD

**Issue by Katanasoul91** [CleverRaven/Cataclysm-DDA#42708]
# Describe the bug
The item Sealed yeast culture doesn`t give you the promised yeast making a net lost.

# Steps To Reproduce

1. Spawn or make s Sealed yeast culture
2. Wait the needed time.
3. Activate it.

# Expected behavior
They should give you at least 2 portions of yeast, one you first used to make the culture and the rest from the process itself.

# Additional context
Have the reverse problem from the sourbread starter, they give you the flask back, but not the cultive.

EDIT: The build used is 10860

**Comment by Tamiore** [comment]
Have you, by any chance, tried this one? http://cdda-trunk.chezzo.com/young_yeast/craft

**Comment by Katanasoul91** [comment]
I don`t have it actually. It is strange, it said the recipe is auto learn, but I have Cooking 7 and Survival 6 and it isn`t in the list.

**Comment by Tamiore** [comment]
Try creating a new character and see if this recipe shows up for that one in your build?

**Comment by Tamiore** [comment]
> 
> 
> Try creating a new character and see if this recipe shows up for that one (in your build)?

**Comment by Katanasoul91** [comment]
In newest updates the issue was resolved, but the wild yeast don`t give me anything no matter how long I wait.

**Comment by Tamiore** [comment]
Are you actually *fermenting* them? In fermentation vat (or the like)?
