### ISSUE TITLE
"Pocket_type" multiple entrys

### ISSUE THREAD

**Issue by TheGoatGod** [CleverRaven/Cataclysm-DDA#42713]
# Is your feature request related to a problem? Please describe.
im trying to make a crossbow fire a single bolt and be able to add a magazine,

# Describe the solution you'd like
to beable to code like this with pocket_data
"pocket_data": [
      { "pocket_type": "MAGAZINE", "ammo_restriction": { "small_bolt_crossbow": 1 } },
      {
        "pocket_type": "MAGAZINE_WELL",
        "holster": true,
        "max_contains_volume": "5 L",
        "max_contains_weight": "5 kg",
        "item_restriction": [ "crossbow_hybrid_mag", "crossbow_hybrid_mag_extended" ]
      }
    ]
# Describe alternatives you've considered
leave it be and ill make different versions of the same crossbow

**Comment by Qrox** [comment]
As far as I know you can already specify multiple pockets in json currently. If that didn't work then it's more like something to do with the ranged weapon code.

**Comment by KorGgenT** [comment]
you cannot specify multiple pockets that have MAGAZINE and/or MAGAZINE_WELL. that is what the multi-mag feature will implement.
