### ISSUE TITLE
BMG_TUR and SMG special attacks appear to be broken

### ISSUE THREAD

**Issue by LyleSY** [CleverRaven/Cataclysm-DDA#42711]
# Describe the bug

Special attacks BMG_TUR and SMG documented in https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON_FLAGS.md throw load errors when applied in a mod. Not sure if they're broken completely or just for mods

# Steps To Reproduce

1. Add a special attack to monster in JSON and put it in base game or mods folder
2. Load a game
3. Error

# Expected behavior

Monsters shoot, no load error

# Versions and configuration

Mac, newest experimental, DinoMod enabled

# Additional context

Ended up using another special attack, not time sensitive

**Comment by Night-Pryanik** [comment]
There are no traces of `BMG_TUR` or `SMG` special attacks in the source code. Seems like these are remnants of some very old code that was eventually removed. 
I guess this issue could be closed, as everything we need to do is to remove mentions of these attacks from docs.

**Comment by actual-nh** [comment]
> There are no traces of `BMG_TUR` or `SMG` special attacks in the source code. Seems like these are remnants of some very old code that was eventually removed.
> I guess this issue could be closed, as everything we need to do is to remove mentions of these attacks from docs.

More precisely, it can be closed after the documentation is fixed. 🙃
