### ISSUE TITLE
zed weapon drops are still bugged

### ISSUE THREAD

**Issue by misterprimus** [CleverRaven/Cataclysm-DDA#42725]
# Describe the bug

Zeds don't drop guns as would reasonably be expected.

# Steps To Reproduce

1. Make a player with a gun, magazine, and some ammo.
2. Spawn some soldier zeds and keep firing until they drop holsters with guns and other weapons.
3. The guns don't spawn as they should.

# Expected behavior

I **expect** to find one or more of these:
1. Holsters with handguns, mags, and ammo of varying quantity.
2. Guns with ammo between 0 and maximum mag capacity.
3. Guns of varying dirtiness.
4. No errors on load.

What I **get**:
~~1. Holsters with handguns that never have mags OR ammo in them.~~
2. ~~Guns and~~ items with ~~ammo/~~ charges of 0 or max capacity; never inbetween.
3. Guns don't show a dirtiness meter - this may be intended as an invisible feature; not sure.
4. ![image](https://user-images.githubusercontent.com/45959491/89373331-64196800-d6b6-11ea-96e4-305bfb5cf7f8.png)

# Screenshots

Do not take a screenshot of the crashing window. Please provide the crash logs in the "Additional context" -->

# Versions and configuration

 - OS: Win7x64
 - Game Version: 0.E-4851-g7d816ea
 - Graphics version: Tiles
 - Ingame language: Eng
 - Mods loaded: Default NPCs need no food mod.

# Additional context

**Comment by misterprimus** [comment]
As an update, it looks like guns and holstered guns have been fixed, but items like lighters and gas masks still spawn only with either 0% or 100% charges.

**Comment by Fris0uman** [comment]
Spawn 9 zombie soldier > debug kill them > look at loot
![image](https://user-images.githubusercontent.com/41293484/99147235-b12ab400-267f-11eb-8812-0277aa354cb9.png)

there's a gun in the holster, and stuff have partial charges

Is this issue actually solved?

**Comment by misterprimus** [comment]
> Spawn 9 zombie soldier > debug kill them > look at loot
> ![image](https://user-images.githubusercontent.com/41293484/99147235-b12ab400-267f-11eb-8812-0277aa354cb9.png)
> 
> there's a gun in the holster, and stuff have partial charges
> 
> Is this issue actually solved?

Looks like most of these went away over the weeks. But do any guns show fouling? Haven't seen the fouling meter lately, so maybe they are just not fouled enough? I remember months ago guns would constantly spawn fouled.

**Comment by anothersimulacrum** [comment]
They are fouled, just lightly.
![image](https://user-images.githubusercontent.com/42699974/99154947-926cf300-2668-11eb-9915-6f67f3709487.png)
![image](https://user-images.githubusercontent.com/42699974/99154958-a7498680-2668-11eb-8bdb-b0f55114f95a.png)
![image](https://user-images.githubusercontent.com/42699974/99154961-ad3f6780-2668-11eb-93ba-89b4f09a09a1.png)

**Comment by misterprimus** [comment]
OK, probably a "zero" level column meter state, then. Then yeah I guess it's fixed until I notice something else wrong with this.
