### ISSUE TITLE
Bridge fast travel

### ISSUE THREAD

**Issue by Darkenlord1** [CleverRaven/Cataclysm-DDA#42727]
# Describe the bug
Character goes under the bridge.

# Steps To Reproduce
Find bridge and set fast travel on other side of it.

# Expected behavior
Character performing fast travel on bridge.

# Versions and configuration
    OS: Windows
        OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
    Game Version: 0.E-4811-g90e0c8b [64-bit]
    Graphics Version: Tiles
    Game Language: Системный язык []
    Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у NPC [no_npc_food],
    Графическая карта [Graphical_Overmap]
    ]

**Comment by ZhilkinSerg** [comment]
Not a bug - 3D pathfinding is not currently supported.

**Comment by Darkenlord1** [comment]
Maybe, for now, make bridges not passable with fast travel? I dont like when my character getting wet with clothes.
