### ISSUE TITLE
Random NPCs do not spawn

### ISSUE THREAD

**Issue by FlyingVolvo** [CleverRaven/Cataclysm-DDA#42741]
# Describe the bug

Wandering NPCs do not spawn according to random NPC spawn time in world settings.

# Steps To Reproduce

Attempt to locate any NPC on the overmap with the debug clairvoyance trait in adjecent overmap tiles.

# Expected behavior

For random NPCs to appear, period.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-4856-ga05e3e8 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    No Fungal Monsters [No_Fungi]

# Additional context

At one point in experimental a month or so ago, this issue seemed to be fixed and random NPCs seemed to spawn in evacuation shelters that wasn't your starting NPC with some regularity, at some point, this behaviour ceased.

This issue is anecdotal, and I am incredibly frustrated by my inability to prove a negative which would substantiate this issue more then a anecdote. 

If this is an issue that can not be corroborated, or is insufficent for a bug report, this issue can be closed.

**Comment by ZhilkinSerg** [comment]
Do you have a savegame?

**Comment by Duck13Tales** [comment]
I think it is happening with me, unless the NPC likes to spawn in the middle of a horde only to be immediately slaughtered.

Is there any way to know if a NPC has ever spawned in my save?

**Comment by Duck13Tales** [comment]
I am playing with random NPC spawn rate at 4 and the debug says that I have 29 NPC's spawned, and 28 of them are static and I suppose ALL of them are from the Hub 01, but the one that isn't seem to be the NPC that I started the game, is this ok?

Maybe the game is taking into account the 28 static NPC's to calculate the spawn rate, is this right?

**Comment by gcaliber** [comment]
Anecdotally, I've yet to have a random NPC spawn since I started playing again recently.

**Comment by Duck13Tales** [comment]
After trying for quite a bit it seems that I was able to spawn a NPC, but only once. NPC's spawning seems to be quite rare, even on the first days of the game after just 20 days.
