### ISSUE TITLE
Tileset Issue

### ISSUE THREAD

**Issue by TealcOneill** [CleverRaven/Cataclysm-DDA#42742]
# Describe the bug
All of the standing machine tools in generated sawmills are missing if you use the BrownLikeBears tileset. 

# Steps To Reproduce
1. Turn on the BrownLikeBears tileset in graphics options.
2. Find a sawmill.
3. Walk around near the conveyor belts until you run into the invisible tile.
4. Use the look around tool to see that there is something in that tile.

# Expected behavior
I expected not to run into invisible and impassable objects. I think that all the tilesets should have at least a letter icon for all the items in the game.

# Screenshots
![exscuseme](https://user-images.githubusercontent.com/45678006/89507566-e7f05480-d789-11ea-8611-79aa522b1c7c.png)
![exscuseme2](https://user-images.githubusercontent.com/45678006/89507587-ef176280-d789-11ea-8744-6cf22b91213b.png)
![exscuseme3](https://user-images.githubusercontent.com/45678006/89507590-f0488f80-d789-11ea-9eab-ab726ae632d3.png)

# Versions and configuration
0.E-2 Stable build
<!-- Please complete the following information; you can now go to:
    - "Main menu (ESC) > Debug Menu > Info > Generate game report" to generate this report.
    - Please update your OS version with a more precise version.

 -- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Graphical Overmap [Graphical_Overmap]
]

# Additional context
As you can see in the ASCII tileset, the number 7 represents all the tools missing. The tool names were something like; planer, bandsaw, mitersaw, jointer, and a couple others.

<!-- Add any other context about the problem here.

**Comment by ZhilkinSerg** [comment]
Is it displayed on latest experimental?

**Comment by TealcOneill** [comment]
> 
> 
> Is it displayed on latest experimental?

I have no clue, I just noticed while playing a normal world.

**Comment by Fris0uman** [comment]
I can confirm that bandsaw is invisible on latest experimental with BLB tileset but not with the other tilesets.

**Comment by Fris0uman** [comment]
Should be fixed soonish
![image](https://user-images.githubusercontent.com/41293484/89741072-7fa5b980-da8e-11ea-8d56-c076b42d44d9.png)
