### ISSUE TITLE
NPC hands player liquid contents of container rather than container, spilling it on the ground

### ISSUE THREAD

**Issue by kenneth-ellis** [CleverRaven/Cataclysm-DDA#42760]
# Describe the bug

When an NPC tries to give player a liquid item such as a bottle of cough syrup, the NPC tries to give just the liquid contents instead of the bottle, resulting in the liquid just being poured out on the ground and wasted, instead.

# Steps To Reproduce

1. Use the "Want to share some useful items with me?" option on an NPC who has a bottle of liquid in inventory.
2. Watch as they dump the contents of the bottle on the ground at your feet.

# Expected behavior

NPCs should generally hand you the container a liquid is in along with the content rather than dumping it on the ground.  Probably the same should be true of small items like a bottle of aspirin, etc.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-4875-g97984d6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Monsters [No_Fungi]
]

**Comment by Duck13Tales** [comment]
NPC:

![trollface](https://user-images.githubusercontent.com/67176313/89580283-7b1d9e80-d80b-11ea-9932-61978e841ed9.jpg)

**Comment by kenneth-ellis** [comment]
@Duck13Tales - lol, yeah that's pretty much how I imagined it -- NPC just looks at me with a big troll-face grin and says, "Oh, you really need some cough syrup huh? Here ya go!" and pours it all over my boots. 😁

**Comment by wapcaplet** [comment]
Confirmed, still an issue in 0.E-6177-g 9f4a1b841d

**Comment by Maleclypse** [comment]
Would this be fixed by making liquids `NO_TRADE` but still adding their value to the container's value?
