### ISSUE TITLE
DEBUG    : mission::wrap_up called, player 28 was assigned, but current player is 1

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#42779]
# Describe the bug
 DEBUG    : mission::wrap_up called, player 28 was assigned, but current player is 1

 FUNCTION : void mission::wrap_up()
 FILE     : src/mission.cpp
 LINE     : 286

followed by 
 DEBUG    : completed mission 7 was not in the active_missions list

 FUNCTION : void avatar::on_mission_finished(mission&)
 FILE     : src/avatar.cpp
 LINE     : 259

# Steps To Reproduce
unknown was trying to open a door in the basement of a house.

# Expected behavior
?

# Screenshots
# Versions and configuration
10900
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5042981/debug.log)

# Additional context
The only active mission is "reach refugee center" which is 300 squares away.
Completed mission: reach the mansion, find antibiotics, no failed mission.

**Comment by KorGgenT** [comment]
not enough information to reproduce. I suspect this is a result of alt+f4 ing the character on death or something?
