### ISSUE TITLE
Time automatically passing even when paused

### ISSUE THREAD

**Issue by seasection** [CleverRaven/Cataclysm-DDA#42781]
# Describe the bug

Time passes by itself when idle. If a menu (crafting, options, etc) is opened, time will pause until menu is closed, afterwards it will speed up to catch up with where it would have been had the menu not been opened (i assume).

# Steps To Reproduce

No idea, but the last thing I recall doing was...

1: Sleeping
2: Setting display window from 240/67 to 120/33
3: Save and Quit

# Expected behavior

Time flows regardless of whether or not the (.) key is pressed

# Screenshots

# Versions and configuration

# Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5043062/debug.log)

-

**Comment by andrei8l** [comment]
Did you enable `Realtime turn progression` perhaps? It's in global settings -> General

**Comment by seasection** [comment]
Ah, yes that was it! Thank you sir.
