### ISSUE TITLE
Gallon Jugs (or containers?) holding Bleach and Ammonia disappear, dumping their contents on the ground and wasting them

### ISSUE THREAD

**Issue by Valiant-Storm** [CleverRaven/Cataclysm-DDA#42780]
# Describe the bug

Gallon Jugs (or containers?) holding bleach and ammonia disappear, dumping their contents on the ground and wasting them. This may occur with other containers and other fluids, but I store these in by far the largest volume, and in their original packaging. 

# Steps To Reproduce

1: Collect a large number of gallon jugs containing bleach and/or ammonia, and set them on the group, perhaps by debug spawning a large number of laundromats. 

2: Deposit the filled jugs on the ground within crafting range of a workbench on separate tiles. 

3: Wait, while engaging in standard base activities - mostly long-term crafting of large volumes (several hundred) targeted mutagens and their serum products. 

4: After some days or weeks, some of jugs should have disappeared, resulting in puddles of dirty fluid on the ground.

# Expected behavior

Non-perishable items should be persistent unless noted otherwise. Factory packaging should contain items properly under normal circumstances. 

# Screenshots

**
![image](https://user-images.githubusercontent.com/69361414/89671299-bd4ceb80-d8b0-11ea-928b-541a66f3aa52.png)
**

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp]
]

# Additional context

[Galicia.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5042865/Galicia.zip)

**Comment by RoyBerube** [comment]
It suspiciously looks like it is related to crafting that uses bleach and/or ammonia.

Did you ever have to suspend crafting and resume later, as when it gets too dark? This could give a clue to what is happening.

**Comment by Valiant-Storm** [comment]
Yes, I did - is there a reason that would be relevant?

**Comment by RoyBerube** [comment]
Interesting. Not a definite cause at this point, but could be. My suspicion is that it is a relatively rare event that is causing the bug, such as resuming a suspended mutagen craft activity.

Will look into it.

**Comment by Duck13Tales** [comment]
Maybe it is something related with the "picking up" and "storing" containers with liquid. I've notice this happen when I am looting around. Depending in the options chosen, instead of storing you spill the liquid in the floor and store the recipient.

It mostly happens with containers that don't have the "watertight" flag but sometimes happens even with them, for example when you try to put the liquid in something that is in your inventory and more commonly when you try to put it in something that is "inside" some other container in your inventory.
