### ISSUE TITLE
Ability to grab 1 item from a container on the ground

### ISSUE THREAD

**Issue by NotHereCDDA** [CleverRaven/Cataclysm-DDA#42785]
# Is your feature request related to a problem? Please describe.
Currently to the best of my knowledge there is no way to get 1 specific item out of a container while it's on the ground. The closest thing i know of is using unload but that empties out the whole container instead of just 1 item.

# Describe the solution you'd like
Some sort of way to grab just 1 thing out of a container on the ground (mostly for bags)

# Describe alternatives you've considered
None, but i'm always open to suggestions/discussion :)

**Comment by Duck13Tales** [comment]
Is it in any way related to #40163?

**Comment by gcaliber** [comment]
Advanced inventory still has a container option which is only for liquids. It seems like this should be changed to work with any container now.

**Comment by NotHereCDDA** [comment]
> Is it in any way related to #40163?

That seems to be talking about how long it takes to grab an item from a container that you are wearing/wielding. While i do think it should take some time to grab 1 item from a container on the ground, No it isn't related.
