### ISSUE TITLE
40mm grenades deal no  fragmentation/splash damage. 

### ISSUE THREAD

**Issue by Purdurabo3456** [CleverRaven/Cataclysm-DDA#42795]
# Describe the bug

40mm grenades, both High explosive and incendiary versions deal no fragmentation / fire splash damage. This appies to both the hand and vehicle launcher 40mm varieties. 

# Steps To Reproduce

Fire any of the 40mm frag or incendiary grenade and notice they only do damage to a single target with 0 fragmentation or fire after effects. Fire the same grenade onto the square next to you and notice you take 0 damage.

# Expected behavior
There should be some fragmentation or fire splash damage from these 40mm grenades.

# Screenshots

# Versions and configuration

Game version O.E-4920-g6a34646

# Additional context

Tried the grenade launcher on a fresh world with no mods and still have the exact same issue.

**Comment by ZhilkinSerg** [comment]
Please make sure to fill game version and mod information.

**Comment by jacobmwood** [comment]
As I don't know how long it will take for the original person to reply, here's my information, and I'm having the same issue: 
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-4920-g6a34646 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    No Fungal Monsters [No_Fungi],
    Graphical Overmap [Graphical_Overmap]
]

**Comment by shadowonwhite** [comment]
> Please make sure to fill game version and mod information.

The cause appears to be that the function -- "extend": -- is not working properly.
I can confirm that it's incapable of adding any effects or tool qualities to items 

`  {
    "type": "GENERIC",
    "category": "tools",
    "id": "pan",
    "name": { "str": "cast-iron frying pan" },
    "description": "A cast-iron pan.  Makes a decent melee weapon, and is used for cooking.",
    "copy-from": "base_cookpot",
    "material": [ "iron" ],
    "color": "dark_gray",
    "weight": "2628 g",
    "volume": "1335 ml",
    "bashing": 12,
    "to_hit": -3,
    "pocket_data": [
      {
        "max_contains_volume": "1 L",
        "max_contains_weight": "1 kg",
        "watertight": true,
        "open_container": true,
        "rigid": true
      }
    ],
    "delete": { "qualities": [ [ "COOK", 3 ] ] },  
    "extend": { "qualities": [ [ "HAMMER", 1 ], [ "COOK", 2 ] ] }    <---------------------------{ doesn't work }
  },`
(cast-iron frying pan should have a cooking quality of 2 based on the code, but bear a cooking quality of 3 in-game.)

Adding explosion effects to the 40mm grenade files without using "extend" make the grenades explode on impact again, so it's not a problem in "ammo_effects.json".

I thought the grenades not exploding was intentional when i was playing a few months back, so things most likely haven't been working properly for a long time now.

**Comment by shadowonwhite** [comment]
Seriously though, how did this fly under the radar for so long?

**Comment by RoyBerube** [comment]
Extended effects from json file are not loading correctly. Replace the following line:

https://github.com/CleverRaven/Cataclysm-DDA/blob/9e9fec8babdc50ea064ca50719b056194085a715/data/json/items/ammo/40x46mm.json#L43

with `"effects": [ "COOKOFF", "NEVER_MISFIRES", "EXPLOSIVE_m433" ]`

And the ammo explodes.
