### ISSUE TITLE
Rural-Only Mapgen

### ISSUE THREAD

**Issue by TealcOneill** [CleverRaven/Cataclysm-DDA#42792]
# Describe the bug

Game is unable to generate a starting location.

# Steps To Reproduce

Uh, I was kind of messing around and was curious what would happen if you did select that scenario so I guess it kind of did what I was expecting. I just didn't know why that scenario was an option when you have the mod in the first place.

# Versions and configuration

<!-- Please complete the following information; you can now go to:
    - "Main menu (ESC) > Debug Menu > Info > Generate game report" to generate this report.
    - Please update your OS version with a more precise version.

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Rural-Only Mapgen [ruralbiome],
    Graphical Overmap [Graphical_Overmap],
    Alternative Map Key [alt_map_key]
]

**Comment by KorGgenT** [comment]
Bug report has incomplete template and incomplete information.
