### ISSUE TITLE
Coilgun flechette ammunition has wrong stats.

### ISSUE THREAD

**Issue by cyborg29x** [CleverRaven/Cataclysm-DDA#42802]
# Describe the bug

The coilgun flechettes' armor penetration, range and dispersion values are different from those intended by the values set in items\ammo\nail.json. Additionally, the loaded coilgun shows its ammunition as being nails in inventory, despite being loaded with flechettes.

# Steps To Reproduce

Create a character with a coilgun and both types of ammunition.
Load both ammunition types into the weapon and compare the armor penetration, range and dispersion values with those intended by the nail.json file.

# Expected behavior

As the flechette (referenced in the nail.json file as _combatnail_) is a "copy-from" of the nail ammunition with the price, range, base damage, armor penetration and dispersion modified by the "proportional" group of parameters, the values should be the following:

-Price: 3000 ($30 per stack of 100);
-Range: +6 (total of 18 tiles of range);
-Base damage: +6 (total of 7 base damage);
-Armor penetration: 3;
-Dispersion: 90 (for a total of 270).

However, of these only the base damage and price appear as intended, with the remaining three parameters showing incorrect values, as can be seen in the screenshots below.

Additionally, the coilgun should reflect the type of ammunition it is currently loaded with when viewed in the inventory, which is not the case.

# Screenshots

The first screenshot shows the stat card for the coilgun with a magazine of nails loaded:
![nails](https://user-images.githubusercontent.com/22873153/89715575-60c7fa00-d99e-11ea-8f9b-f50505082327.PNG) 

The second screenshot shows the stat card for the flechettes, with the incorrect AP (which is zero), range and dispersion values (same as those for nails):
![flechettes](https://user-images.githubusercontent.com/22873153/89715630-e0ee5f80-d99e-11ea-97cb-4837d3c0bb45.PNG)

# Versions and configuration

- OS: Windows
    - OS Version: 7 SP1 Ultimate 
- Game Version: 0.E-4667-g1d4ea08 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context

The following zip includes a test world with a coilgun, two magazines (one with each ammunition type, with flechettes already loaded into the weapon) and two stacks of 100 nails and 100 flechettes each, as well as a copy of the relevant .json file.

[Sandbox.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5045735/Sandbox.zip)

**Comment by venum4k** [comment]
Alright so I've managed to get the correct values to show up but it's not an ideal solution and I haven't managed to pin down the cause yet. The proportional section of the flechette ammo .json wasn't changing the values from the basic nail ammo for some reason. 
![image](https://user-images.githubusercontent.com/1928247/91590798-cc750580-e953-11ea-9749-04c04aa76da2.png)

**Comment by anothersimulacrum** [comment]
#43144 Might be the more complete fix here.

**Comment by TealcOneill** [comment]
I believe #51439 fixes the last issue mentioned here, so this should be fine to close.
