### ISSUE TITLE
Bug with stomach volume increased due eaten food

### ISSUE THREAD

**Issue by Duck13Tales** [CleverRaven/Cataclysm-DDA#42811]
# Describe the bug

When you eat something it has an estimated volume, it seems that the volume increased in the stomach is way higher than it should be. As you can see in the prints the expected volume of a flatbread would be 250ml, but instead once I eat my stomach content increased by around 700ml (probaly 700 but part of it was reduced by the digestion of what I already had in my stomach).

# Steps To Reproduce

1 - Use the debug menu to see how much you have in your stomach
2 - Eat a flatbread
3 - Use the debug menu to see hot much increased in your stomach contents

# Expected behavior

It should increase the stomach content as much as expected from what you have eaten.

# Screenshots

![flatbread](https://user-images.githubusercontent.com/67176313/89721560-6977fa80-d9b5-11ea-8b66-dbb8ba12dff8.png)

![food volume](https://user-images.githubusercontent.com/67176313/89721565-7399f900-d9b5-11ea-8ad4-ebccfa5efb0e.png)

# Versions and configuration

I am using using the CDDA 0.E-b10900 with the mods:

DDA
Disable NPC needs
Stats through skills
Stats through kills
SpeedyDex

# Additional context

Maybe it is what is causing the unbalance in the food system as it is too hard to meet the calories eating needs.

**Comment by anothersimulacrum** [comment]
![image](https://user-images.githubusercontent.com/42699974/89721650-fa8aa980-d994-11ea-9edb-ca8093d72f04.png)
Working as expected. The effective stomach volume of food is scaled by the ratio of their calories/weight, until that ratio hits 3, at which point it's sqrt( 3  * ratio ).
