### ISSUE TITLE
Segment fault at autosave start while interacting with a vehicle.

### ISSUE THREAD

**Issue by Xindage** [CleverRaven/Cataclysm-DDA#42810]
# Describe the bug
Playing the game normaly, them I was got the idea of trying to add a second wire basket to my bike so I reached a broken bike and I decided to start removing the components of it, I started by the wheel of it and them I selected to remove it, after the vehicle status menu disapeared the game tryed to autosave and well, nothing happened for a minute until I noticed that the game crashed whit segfault. Seens like the game tried to save in same turn that i tried to interact whit the vehicle and it made the game to crash.

# Steps To Reproduce
I'm not 100% sure that will work because i cant decide when the game is about to autosave, but there's:
- Check a vecicle.
- Try to remove/add a conponent in same turn that the game is about to autosave.
- Segfault.

# Expected behavior
Expected to the autosave do its thing and I be able to remove the wheel.

# Versions and configuration
- OS: Windows
    - OS Version: Windows 7
- Game Version: 0.E-4875-g97984d6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [Dark Days Ahead [dda], Disable NPC Needs [no_npc_food], Stats Through Skills [StatsThroughSkills]]

# Additional context
Logs: [logs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5046497/logs.zip)

# Additional note about the save file.
The crash caused something strange with the save (There's now 2 chars with same name) and as I'm writing there I'll post the actual state of the save file and IF POSSIBLE (because I dont even know if the save file is recoverable) another one on the exactly place where the bug happened.
Actual state of the save file: [Olney.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5046500/Olney.zip)
I tryed my best to reproduce all i did until i reached this place where the bug happened, use the below character from the save, since it's still duplicated...)
Another save on the place where the bug happened: [Olney.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5046555/Olney.zip)

Exist a slight chance of this crash dont be even related to the fact of interacting with the vehicle but this i dont know, i just reported what it seems to be.

**Comment by andrei8l** [comment]
Not using pimpl in `item_pocket` would solve this and many other similar edge cases. An alternative would be to point to a static object instead of nullptr by default, or litter `item_pocket.cpp` with nullptr checks.

Can't quite figure out why pimpl is used in this case.

**Comment by jbytheway** [comment]
`pimpl` pointers should never be null.  Even when moved-from they're not null.

**Comment by andrei8l** [comment]
Sure, however the crash log shows that the `data` pointer is null in a `pocket.is_type()` call

**Comment by jbytheway** [comment]
How do you infer that?  All I see is a segfault in `item_contents::all_items_top`.

**Comment by andrei8l** [comment]
This is the last stack entry before the segfault:
`(libbacktrace: ZNK13item_contents13all_items_topB5cxx11EN11item_pocket11pocket_typeE+0x25@0x8c6f45),`
the names are mangled but it shows an `item_pocket::pocket_type` was pushed to the stack after `item_contents::all_items_top()` was called. You can then look at the code in `item_contents.cpp:929` and trace the segfault to the pointer access in `item_pocket.cpp:1352`. A real debug log would show it more clearly, but I wasn't able to reproduce it from the save file.

I've been debugging this way for some time, but please correct me if you're seeing something else.

**Comment by jbytheway** [comment]
That's not what that says.  `ZNK13item_contents13all_items_topB5cxx11EN11item_pocket11pocket_typeE` is just the mangled name of one of the `item_contents::all_items_top`.  The `pocket_type` is there only because it's an argument to that function.  You can't assume one is on the stack.

All you know is that there was a segfault in that function.  We do have the offset, so you could SRE the binary to find out what instruction crashed.  Would be nicer if our backtraces had line numbers, of course, but currently they don't.

Even if you did know that the crash was related to the pointer access in `item_pocket.cpp` that still wouldn't imply a null pointer.  Lots of other things can cause segfaults besides null pointers.

**Comment by andrei8l** [comment]
> That's not what that says. `ZNK13item_contents13all_items_topB5cxx11EN11item_pocket11pocket_typeE` is just the mangled name of one of the `item_contents::all_items_top` overloads. The `pocket_type` is there only because it's an argument to that function. You can't assume one is on the stack.

Yeah, you're right. Thanks

**Comment by YourCompanionCube** [comment]
think i got the same thing when starting a craft
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5238869/crash.log)

**Comment by anothersimulacrum** [comment]
Cannot reproduce. Even if I force the game to save _every turn_, nothing happens when interacting with a vehicle.
Patch to make the game autosave every turn.
```diff
diff --git a/src/game.cpp b/src/game.cpp
index 1eacd5055d..7d60200171 100644
--- a/src/game.cpp
+++ b/src/game.cpp
@@ -1411,6 +1411,7 @@ void game::calc_driving_offset( vehicle *veh )
 // Returns true if game is over (death, saved, quit, etc)
 bool game::do_turn()
 {
+    moves_since_last_save += 1;
     if( is_game_over() ) {
         return cleanup_at_end();
     }
@@ -1459,11 +1460,13 @@ bool game::do_turn()
     u.update_body();

     // Auto-save if autosave is enabled
+    /*
     if( get_option<bool>( "AUTOSAVE" ) &&
         calendar::once_every( 1_turns * get_option<int>( "AUTOSAVE_TURNS" ) ) &&
         !u.is_dead_state() ) {
-        autosave();
-    }
+    */
+    autosave();
+    //}

     weather.update_weather();
     reset_light_level();
@@ -12191,9 +12194,11 @@ void game::quickload()
 void game::autosave()
 {
     //Don't autosave if the min-autosave interval has not passed since the last autosave/quicksave.
+    /*
     if( time( nullptr ) < last_save_timestamp + 60 * get_option<int>( "AUTOSAVE_MINUTES" ) ) {
         return;
     }
+    */
     quicksave();    //Driving checks are handled by quicksave()
 }
```
