### ISSUE TITLE
"Spetsnaz Knife Techniques" useless for knife-fighting

### ISSUE THREAD

**Issue by LordKaaven** [CleverRaven/Cataclysm-DDA#42822]
# Describe the bug

Almost all knives in the game are classified as piercing weapons, with a small side-damage of bashing. The book "Spetsnaz Knife Techniques" however, teaches the reader a cutting skill, making it completely useless for training fighting with knives.

# Steps To Reproduce

1. Make a player with a knife
2. Acquire and read the book "Spetsnaz Knife Techniques"
3. Feel lacks of gains from reading it

# Expected behavior

A book about fighting with knives should provide adequate skill gains. We can acheive that by either making most knives cut or by switching the book to train piercing weapon combat.

# Versions and configuration

 - OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
 - Game Version: 0.E-4928-g92c0ee0
 - Mods loaded: vanilla game
 -->

# Additional context

As someone mentioned in the Reddit topic I made about the issue: 
https://www.reddit.com/r/cataclysmdda/comments/i69np5/knives_not_cutting/

Some knives, like tanto and kirpan, as well as maybe few other more common ones like chefs knife, are really made for cutting and not stabbing and should probably be reviewed to loose the STAB flag.

**Comment by Hulkninja** [comment]
I always did feel knives were a bit... Odd.

Irl, knives are almost exclusively used to cause cutting or piercing damage, with some leaning more towards one or the other.

I've never heard of someone suffering blunt force trauma from a knife attack. 

The trench knife has a built-in knuckle duster, so in that case it makes sense, but that's the only exception I can think of.

**Comment by WeisserRitter** [comment]
It's definitely an interesting dilemma. However, I can think of an outside the box solution. We know knives are good for both stabbing AND cutting, so would it not be possible to make the Spetnaz Book train both skills? Or would that be too challenging source code wise?

**Comment by LordKaaven** [comment]
@Hulkninja 
The trick is that, as far as I've been told, weapons in Cata can be either cutting or piercing but not both. So the bash damage is there just as a filler: 1/2 damage cause it can be. But we cannot have cutty-stabby knife, sadly.

@WeisserRitter 
There are no books in the game that teach 2 skills at the same time, so my assumption is that's not possible right now. And it wouldn't make sense anyway, since there are no cutting knives in the game (outside of cleavers, I believe). See above for reason why.

Generally the easiest band-aid fix is to simply change the book to pierce damage. Proper solution would be to allow weapons to be of stab/cut type and fine-tune the knives to that new scale. But that's a re-work of the entire weapons system, which is far beyond of what's doable, I assume.

**Comment by LordKaaven** [comment]
2 small updates: 
1) there is another book, called "knife fighter's notes" which also trains cutting skill

2) as someone mentioned in the linked reddit thread, simply changing the books from cutting to piercing might create a new problem, namely that there will be no books to train actual cutting skill above level 1.
