### ISSUE TITLE
Crash to desktop (segmentation fault) on savegame load

### ISSUE THREAD

**Issue by Asseverater** [CleverRaven/Cataclysm-DDA#42849]
# Describe the bug

Loading the attached savegame causes a crash, with "MESSAGE: SIGSEGV: Segmentation fault". No obvious cause springs to mind.

# Steps To Reproduce

Try to load the savegame, observe the crash.

# Expected behavior

Game loads without crashing to desktop.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-4951-g9af1a35 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

- [crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5052808/crash.log)
- [debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5052809/debug.log)
- [zipped savegame](https://github.com/CleverRaven/Cataclysm-DDA/files/5052813/Port.Orford.zip)

**Comment by andrei8l** [comment]
This is the same issue as in https://github.com/CleverRaven/Cataclysm-DDA/issues/42844. The game saved while you were eating something (player activity `ACT_EAT_MENU`) and the target wasn't cleared properly before serialization so now your character has a backlog of eating something out of an empty can.

I've manually fixed your broken save here:
[#QXJ0.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5053094/QXJ0.zip)
(or you can just load it with the workaround in the other issue, then save to fix it)
I haven't had the time to figure out a proper fix and the relevant code is kinda confusing.

**Comment by DrewTuber** [comment]
I've got a similar issue, but I was driving a vehicle when I saved. I had recently eaten some food out of the trunk beforehand, however. Not sure if its the same issue.

[auto_before_launch.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5053654/auto_before_launch.zip)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5053656/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5053657/debug.log)
