### ISSUE TITLE
Segfault / crash on attempt to load save file

### ISSUE THREAD

**Issue by kenneth-ellis** [CleverRaven/Cataclysm-DDA#42844]
# Segfault crash on attempt to load save file attached

# Steps To Reproduce
Load the attached save file.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E.4943-ge0136e2
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: Disable NPC Needs, No Fungal Monsters

[Fernan Lake Village.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5049225/Fernan.Lake.Village.zip)
[crash-logs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5049226/crash-logs.zip)

**Comment by andrei8l** [comment]
This lets you load the save but does not address the cause of the crash:
```diff --git a/src/item_location.cpp b/src/item_location.cpp
index fa12d9a3cc..cd8cfc8ec2 100644
--- a/src/item_location.cpp
+++ b/src/item_location.cpp
@@ -719,6 +719,9 @@ void item_location::deserialize( JsonIn &js )
         }
         const std::list<item *> parent_contents = parent->contents.all_items_top();
         auto iter = parent_contents.begin();
+        if ( iter == parent_contents.end() ) {
+            return;
+        }
         std::advance( iter, idx );
         ptr.reset( new impl::item_in_container( parent, *iter ) );
     }
```
The real issue is probably in the serialization chain somewhere. Do you remember what you were doing when the game last saved?

**Comment by kenneth-ellis** [comment]
IIRC just standing in the Evac Center, had saved and quit normally without any issues, no crashes or errors while actually playing before that.

**Comment by andrei8l** [comment]
Looks like the crash is caused by a sealed, but empty, `can_medium`. I've identified one way to cause that but there might be more. Do you remember how you obtained the deluxe beans out of the tin can?

**Comment by kenneth-ellis** [comment]
Oh! Yes, I cooked up some Deluxe Vegetarian Beans & Rice from a recipe not
too long before making that save, I think.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/segmentation-fault-0-e-4920-g6a34646-loading-into-game/24391/9

**Comment by kenneth-ellis** [comment]
I just ran a quick test and reproduced this issue on a freshly generated world & character.  Used debug menu to spawn in materials to cook up "Rice & Beans" recipe using "Canned Beans".  Saved the game after that, then attempted to load it back up & got another segfault/crash.

**Comment by kenneth-ellis** [comment]
[crash-logs2.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5054199/crash-logs2.zip)
[Wilderville.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5054200/Wilderville.zip)

**Comment by kenneth-ellis** [comment]
One thing I noticed is that after cooking the recipe, I had the "Rice & Beans" but I _didn't_ have an empty can in my inventory or anywhere in sight.

**Comment by kenneth-ellis** [comment]
Also just tried another test where I just spawned in a "canned beans" simply ate it without cooking anything.   Then saved/quit, and reloaded... this time I didn't get a segfault / crash but instead got a series of errors during load:

1. failed to find item_location owner with character_id 1
2. item_location lost its target item during a save/load cycle
3. parent location does not point to valid item

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/segmentation-fault-0-e-4920-g6a34646-loading-into-game/24391/16

**Comment by kenneth-ellis** [comment]
So I just tested again after updating to the latest build (10911) and so far I'm no longer able to reproduce the segfault/crash by crafting "rice and beans" from canned beans then saving/reloading.  Seems better now! It may have changed in any of the lat several builds, not sure which.

**Comment by olanti-p** [comment]
>Also just tried another test where I just spawned in a "canned beans" simply ate it without cooking anything. Then saved/quit, and reloaded... this time I didn't get a segfault / crash but instead got a series of errors during load:
>
>    1. failed to find item_location owner with character_id 1
>    2. item_location lost its target item during a save/load cycle
>    3. parent location does not point to valid item

Might be related to #41352
