### ISSUE TITLE
Game crash when dropping an item in a specific way

### ISSUE THREAD

**Issue by Olaroll** [CleverRaven/Cataclysm-DDA#42852]
# Describe the bug

Game crashes when you follow the steps to reproduce

# Steps To Reproduce

1. Wield any item
2. Open drop (d) dialogue
3. Mark wielded item as to-drop
4. Search (/) for the wielded item
5. Mark the wielded item again (this shouldn't be possible)
6. Confirm the drop
7. Game crashes

# Expected behavior

After searching, the game should remember which items were already marked and update the UI accordingly.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-4928-g92c0ee0 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [ Dark Days Ahead [dda] ]

# Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5075286/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5053788/crash.log)

**Comment by wapcaplet** [comment]
Confirmed in 0.E-5371-g2ea5e2e970 using the steps in the issue description.

This only occurs with *wielded* items. When following the same procedure while dropping a worn item, or an item in inventory (container), the selected item is dropped without incident.
