### ISSUE TITLE
Barbed Wire Doesn't Cause Bleeding

### ISSUE THREAD

**Issue by Grubleafeater** [CleverRaven/Cataclysm-DDA#42857]
# Describe the bug

Enemies that step in barbed wire fencing don't bleed

# Steps To Reproduce
Just....lure a zombie into a barbed wire fence.

# Expected behavior

Barbed wires should cause bleeding.

**Comment by kevingranade** [comment]
That's expected, barbed wire is a pain-based deterrent, not a lethal obstacle.
