### ISSUE TITLE
Scout trait not working properly

### ISSUE THREAD

**Issue by ConnorMartin** [CleverRaven/Cataclysm-DDA#42853]
Even with the scout trait, my character's map vision is still 5 tiles.

# Steps To Reproduce

Create a character with the scout trait
Walk around for a little while on a field
Observe the 5-tile map vision (should be 10 with scout)

# Expected behavior

Scout states that it improves map vision range, so the trait should do that.

# Screenshots

![image](https://user-images.githubusercontent.com/19824381/89838672-d916f280-db39-11ea-8a6a-d795ac8f1116.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-4942-gc8ac471 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    Aftershock [aftershock]
]

# Additional context

**Comment by wapcaplet** [comment]
@ConnorMartin Did you happen to also have the "Self-Aware" trait? I can confirm this issue, but only when I also have "Self-Aware".

The counterpart of the "Scout" trait that should reduce overmap sight range ("Topographagnosia") also has no apparent effect.

With "Scout" and "Self-Aware",  overmap vision is 5 overmap tiles:

![image](https://user-images.githubusercontent.com/238395/90303591-73de3c80-de6c-11ea-9ae5-6dac75c06d2f.png)

With "Topographagnosia" and "Self-Aware", overmap vision is still 5 overmap tiles:

![image](https://user-images.githubusercontent.com/238395/90303599-80629500-de6c-11ea-83b0-fd3083067d7f.png)

However, *without* the "Self-Aware" trait, I am getting a distinct increase (~7 tiles) with "Scout", and a significant decrease (~2-3 tiles) with "Topographagnosia":

![image](https://user-images.githubusercontent.com/238395/90303630-b3a52400-de6c-11ea-8da2-4078668efa5d.png)

I don't know if this is intended behavior, but it's pretty strange.

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-5007-g80e32f911b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by wapcaplet** [comment]
Worth repeating here from comments on #42923 - the "Self-Aware" trait was a red herring; it turns out the "Scout" visibility range was nullified by having *any* other trait; in other words, "Scout" only worked if it was the only trait you had. Problems like this may be mitigated in the future by this change to mutation/trait modifiers: #42932
