### ISSUE TITLE
DIY Paper Maps (non-overmap)

### ISSUE THREAD

**Issue by FeepingCreature** [CleverRaven/Cataclysm-DDA#42863]
# Is your feature request related to a problem? Please describe.
When you come back to your lab base after a short trip, you have somehow forgotten where everything is. This is unsatisfactory.

# Describe the solution you'd like
Players should be able to sketch the known layout of a level on a piece of paper, creating a map. Reading the map should refresh/restore your knowledge of that level.

# Describe alternatives you've considered
Better memory for a place the longer you stay there would also do, but probably be too memory intensive.

# Additional context
You could hang them on the wall to create evacuation maps. Those could also spawn during mapgen.

**Comment by GGgatherer** [comment]
It should also allow remote use so you can drop it at the entrance and use it whenever you return w/o needing to either take it with you or drop it back after using it.

**Comment by gcaliber** [comment]
I'm trying to think of how this would actually work in game. Would it save map memory for the surrounding X by X tiles, a set of player selected tiles from the overmap, or what exactly?

**Comment by FeepingCreature** [comment]
I'd think it'd save map memory for some radius around the player when the map is created, same as the player's memory itself works. (Note: I don't know how the player's memory works.) A piece of paper is about as large as a monitor, so maybe something like a monitorful of distance? If more radius is required, you can always hang up more maps.

**Comment by DialoMalison** [comment]
Why not have a "home" zone that you can designate using the zone manager. Then all the terrain in the zone would remain in memory until/unless you delete the zone.

**Comment by FeepingCreature** [comment]
That would also solve the problem, but I'd still prefer maps on aesthetic grounds.

Also if maps pre-spawned on walls near stairs, as would be expected in public buildings, it would add both realism and a bit of payoff for exploration.

**Comment by Ununsept117** [comment]
Note that maps in public buildings generally show only the layout of the building, without all the details like furniture which would be visible if you just revealed the whole building. Also I don't know how it would handle for example destroyed walls - would it reveal the original layout of the building, or the present?

**Comment by FeepingCreature** [comment]
I'd assume original layout, but I don't know how destruction is applied. If it's a scripted step, the map would have to be generated beforehand. And yeah, filtering furniture makes sense (as long as player-drawn maps would still have it).
