### ISSUE TITLE
Crash on cooking attempt with bag on arm

### ISSUE THREAD

**Issue by Darkenlord1** [CleverRaven/Cataclysm-DDA#42866]
# Describe the bug
While wearing only swag bag or straw basket or any bag, that covers arm start cooking any food, it will put it in bag and ask you to free your arms, then drop bag and continue crafting.

# Expected behavior
No crash.

# Versions and configuration
- OS: Windows
- Game Version: 0.E-4977-g292d63c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Graphical Overmap [Graphical_Overmap],
    No Rail Stations [No_Rail_Stations]
]

**Comment by Proluiz** [comment]
seems like the same bug i reported #41669 
When i pick the wild vegetables (0%) the game automaticaly place it inside my makeshift pot so when you active it the games prompt me to drop the wilded item and if i accept it crash.

are we talking about the same bug?

# Steps To Reproduce

1. Have a naked wielding anything that can countain an item.
2. Have any started crafting (x%) in that countainer.
3. Active this craft to start crafting it.
4. Accept dropping the countainer.
5. Crash.

# Screenshot
here's an example screenshot last step beforing the crash, accept the drop and it crash, use the log in the screenshot for information in game.
![image](https://user-images.githubusercontent.com/6380147/89960924-ad1d6f00-dc16-11ea-8860-bc96f4047840.png)

# Save game example
Here's a save file example, just attemp to active the in progress tomato seeds (0%)
[Debug world.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5060004/Debug.world.zip)

**Comment by Darkenlord1** [comment]
Seems like it.
