### ISSUE TITLE
Wearing at item that is too big to fit in your inventory prompts you to discard any wielded item

### ISSUE THREAD

**Issue by gcaliber** [CleverRaven/Cataclysm-DDA#42871]
If you attempt to wear clothing that will not fit in your current inventory while wielding an item you will be prompted to drop or put away your wielded item. Pressing escape will close this menu and still allow you to wear the clothes and the time taken to do so is the same as when not wielding an item, so the prompt doesn't actually do anything if you ignore it.

**Comment by wapcaplet** [comment]
Same issue as #42525
