### ISSUE TITLE
Dropping a wielded activated CBM weapon actually drops the weapon on the floor

### ISSUE THREAD

**Issue by SolidMilk19** [CleverRaven/Cataclysm-DDA#42884]
# Describe the bug

When you activate a CBM weapon (Monomolecular Blade in this example, but the same thing happens to the Monomolecular Sword from Cataclysm++) and drop the wielded pseudo-item from your inventory, it actually ends up on the floor while still getting displayed as active in your Bionics menu. You can then pick it up and carry it around in your inventory. De- and reactivating the CBM means you get a new weapon, that you can then also drop if you like. You can't trade them away since they have no value, but it's a great way to outfit your followers. Probably not intended to be like this, especially since the 'weapon' on the floor is using the same tile as the installable CBM itself.

# Steps To Reproduce

1. Make a Bionic Assassin.
2. Activate your Monomolecular Blade from the Bionics Menu.
3. Either open your inventory, select the wielded weapon and drop it from there, or do the same via Multidrop.
4. Look at the weapon on the floor. Marvel at the gameplay possibilities.

# Expected behavior

The CBM deactivates like it would if you picked up an item that's too big to fit into your backpack and needs to be wielded.

# Screenshots

![01](https://user-images.githubusercontent.com/68878873/89976628-378ebe80-dc69-11ea-9654-65f9d07fe8d5.PNG)
![02](https://user-images.githubusercontent.com/68878873/89976633-3a89af00-dc69-11ea-8577-3fc7469c8fff.PNG)
![03](https://user-images.githubusercontent.com/68878873/89976641-3e1d3600-dc69-11ea-90dd-6aa0bda4a487.PNG)

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-4977-g292d63c
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: dda, no_npc_food

**Comment by AMurkin** [comment]
Related #42831

**Comment by Fris0uman** [comment]
Probably caused by #41968
