### ISSUE TITLE
Handheld game system uses no battery with "Play anything for a while"

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#42892]
# Describe the bug

When using a handheld game system and choosing "Play anything for a while" (instead of picking a particular game), after the activity completes, no battery has been used.

# Steps To Reproduce

1. Get a portable game system
2. Load it with a charged battery and note how many charges it has
3. `a`ctivate the game system
4. Choose "Play anything for a while"
5. Wait until activity finishes (1 hour)
6. Check battery - no charges depleted

# Expected behavior

Game system should use battery power when playing any game.

# Screenshots

![image](https://user-images.githubusercontent.com/238395/90078196-53be4a00-dcc1-11ea-8571-3f12f276890f.png)

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-4984-ga364725156 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

When playing specific games, battery power is consumed at a rate of 15 per 15 minutes of play. Only "Play anything" does not consume batteries.

**Comment by casswedson** [comment]
Fixed by #46693

**Comment by wapcaplet** [comment]
Duplicate of #40148
