### ISSUE TITLE
When selecting a tool from the "activate" menu and cancelling, time passes anyway

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#42893]
# Describe the bug

When using the `a` to activate certain items from the "Use item" menu, selecting an item, then pressing ESC to cancel (choosing to do nothing with the item), some amount of time passes anyway.

# Steps To Reproduce

1. Have some items in the inventory that can be activated (but do not have inventory open)
2. Press `a` to open the "Use item" popup menu, showing all items that can be activated/used
3. Select an item and press Enter
4. When prompted for "Light where?" or "What do you want to play?" press ESC
5. Notice that several seconds of time pass, even though you have not done anything

This is true for a number of items with a secondary prompt for where/what to do with the item, including:
- lighter or refillable lighter (1-2 seconds)
- hammer (5 seconds)
- handheld game system (5 seconds)

# Expected behavior

When pressing ESC to cancel an action, I expect 0 time to pass, since I have not done anything.

# Screenshots

Here at 12:40:30 PM, I have pressed `a` and selected my lighter:

![image](https://user-images.githubusercontent.com/238395/90078705-f925ed80-dcc2-11ea-8653-314e7b7b0c74.png)

Press Enter on the lighter to get the "Light where?" prompt (still 12:40:30 PM)

![image](https://user-images.githubusercontent.com/238395/90078726-0511af80-dcc3-11ea-9413-d130c59d249a.png)

Now pressing ESC cancels the prompt, but it's now 12:40:31 PM:

![image](https://user-images.githubusercontent.com/238395/90078769-25da0500-dcc3-11ea-93fb-fa3a6010f31d.png)

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-4984-ga364725156 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

**Important note** - This behavior does *not* occur when `a`ctivating an item from the `i`nventory screen. Activing an item directly from inventory, then cancelling, no time passes. It is only when activating directly from the "Use item" popup that cancelling causes time to pass.

**Comment by NotHereCDDA** [comment]
Nice catch!

**Comment by mqrause** [comment]
It seems like the use item menu always needs a bit more time than activating an item from the inventory.

Inventory:
![i](https://user-images.githubusercontent.com/38702195/90081518-dd940480-dd0d-11ea-90d7-aea3ee4b8c27.png)

Use item:
![a](https://user-images.githubusercontent.com/38702195/90081534-e7b60300-dd0d-11ea-8b39-a4ac21da15b3.png)

**Comment by mqrause** [comment]
On further testing, the time difference and time passing on cancelling the action is actually the moves required to get the item from your inventory. Currently it's free when activating from inventory.

Apart from that one could maybe argue that you actually took the item from your inventory before cancelling and time should pass accordingly. I personally wouldn't say it's something that needs to be penalized.

**Comment by GGgatherer** [comment]
Same thing with medical items. Select bandage or antiseptic, activate it then bail out of selecting body part -> time spent on nothing.

**Comment by wapcaplet** [comment]
Something else I noticed about this while testing #43174 - when using the `a`ctivate menu, and selecting an item on the ground nearby (such as a tool belt with a hammer in it, or the hammer itself), then cancelling the "What to do with ...?" prompt with `ESC`, the item *is picked up* (without any message saying it has been picked up), and goes into my inventory during the seconds that pass while cancelling.

**Comment by mqrause** [comment]
That must be part of `item_location::obtain`, since that's executed before using the item (and uses the time that passes).

**Comment by wapcaplet** [comment]
@mqrause I have just been testing this and coming to the same conclusion. `avatar_action::use_item` in `avatar_action.cpp` calls `loc.obtain` (L1014), which could be one of the `item_location::obtain` functions - which subtracts moves immediately, and `i_add`s the item to inventory. This appears to happen before the "What do you want to do ...?" or "Light where?" or "What do you want to play?" prompt.

I'm still playing around with breakpoints and debugging `cout`s to dig further.

**Comment by Ramza13** [comment]
So I think this is a two step process.  First is call obtain on an item we activate through the inventory, to make the time use consistent. Then we can tweak obtain if we want to change the time passing and affect all the cases at once.

Second part of this is the fact that invoking an item can cause an item to open a menu and let the user cancel the use.  We probably need to create something like an optional can_invoke/gather_user_feedback method to be called before we pass the time.

I'm gonna try and take a stab at this, @wapcaplet I noticed you self assigned a while back, if you are already working on a solution i can drop this one.

**Comment by Ramza13** [comment]
Having taken a longer look at this its a thorny problem with a number of factors.  What happens at the moment is that you obtain the item before activating it.  This takes time even if in your inventory which isn't really unreasonable.  The problem is that iuse methods are not guaranteed to happen.  So when activating the tool there is no way to know before hand if it will happen.  

Solutions I can see:

1. Remove time to obtain items in inventory
Pros: Nice quick easy.
Cons: Band-aid on real problem, and once pulling things from inventory is an activity/takes longer will come back.  Might affect other obtains.

2. Prevent obtaining item until after we have activated it and know whether it happened.
Pros: Not super easy but not super hard.
Cons: Seems hacky and likely to cause bugs elsewhere

3. Split iuse methods into 2 methods: Gather input/validate and execute.  Before obtaining the item call gather input/validate to test whether the item can be used and if so gather all needed data from the player.  Then if its time to use the item obtain it and activate it.  
Pros:  Solves problem without likely causing issues in related systems.
Cons: A LOT OF WORK!  I started trying to do this solution but in addition to having to refactor 4000 odd lines of iuse methods the way everything is setup makes it harder than it seems to handle obtaining the item or not.  While it shouldn't break other systems the amount of refactoring involved guarantees adding more bugs in items.

4. Prevent cancelling item activation. 
Pros: Safe change unlikely to cause more bugs.
Cons:  Only handles some cases, annoying to user.

5.  Call it a feature.  Your character just pulled out a game console, thought about it said nah and put it back.  That takes a second or two.

**Comment by actual-nh** [comment]
> 5. Call it a feature.  Your character just pulled out a game console, thought about it said nah and put it back.  That takes a second or two.

In that case, something may need to be done about (player-viewpoint, not character-viewpoint) variations in object access methods causing variable time taken.

**Comment by mqrause** [comment]
It's been a while since I looked at the code, but wouldn't a 6th option be to catch cancelled activations and add the moves to obtain the item back to the character?

**Comment by Ramza13** [comment]
> 
> 
> It's been a while since I looked at the code, but wouldn't a 6th option be to catch cancelled activations and add the moves to obtain the item back to the character?

Just did a quick test and yes in fact that does work and is much better than my suggestions.  Working on making it a PR atm.

**Comment by Ramza13** [comment]
> 
> 
> > It's been a while since I looked at the code, but wouldn't a 6th option be to catch cancelled activations and add the moves to obtain the item back to the character?
> 
> Just did a quick test and yes in fact that does work and is much better than my suggestions. Working on making it a PR atm.

I spoke too soon.  The concept works but I ran into another problem, there is no way to tell whether an iuse method failed or not.  I had thought a return of 0 meant that but it doesn't.

I now think the only real solution to this is an obscene amount of refactoring mentioned in my above post as number 3.

**Comment by actual-nh** [comment]
> I spoke too soon. The concept works but I ran into another problem, there is no way to tell whether an iuse method failed or not. I had thought a return of 0 meant that but it doesn't.

Sigh...

> I now think the only real solution to this is an obscene amount of refactoring mentioned in my above post as number 3. Or possibly just refactoring the iuse methods to return -1 on failure and then doing another solution. Still a lot of work though.

Failure, or cancellation?

**Comment by Ramza13** [comment]
> 
> 
> > I spoke too soon. The concept works but I ran into another problem, there is no way to tell whether an iuse method failed or not. I had thought a return of 0 meant that but it doesn't.
> 
> Sigh...
> 
> > I now think the only real solution to this is an obscene amount of refactoring mentioned in my above post as number 3. Or possibly just refactoring the iuse methods to return -1 on failure and then doing another solution. Still a lot of work though.
> 
> Failure, or cancellation?

Well failure in the sense that some items test if they can be used in the iuse method.  So for example fungicide won't work underwater.  To me that stuff probably also shouldn't take time.  That said its probably a little less important and thinking about all of this maybe its not as much work to change the returns to negative one as I thought.  I might try that solution out after all.

**Comment by anothersimulacrum** [comment]
I'm not sure how extensive it will be, but could I recommend changing the return to`cata::optional<int>` (or even `ret_val<int>`) for iuses? -1 as a failure return seems a little fragile to me.
