### ISSUE TITLE
Non-rigid containers cannot hold more than their own "empty" volume

### ISSUE THREAD

**Issue by eilaattwood** [CleverRaven/Cataclysm-DDA#42898]
# Describe the bug

Volume capacity of non-rigid containers (like the canvas sack) is actually limited to their own volume, not by their reported capacity.

# Steps To Reproduce

1. Obtain canvas sack and 12000 (15 L) of detergent.
2. Try to insert all of the detergent into the sack. Fail.
3. Try to insert 81 of the detergent. Fail.
4. Try to insert 80 (exactly 1 L) of the detergent into the sack. Success.
5. Become sad.

# Expected behavior

Canvas sack and other non-rigid contaners are able to hold as much as they pretend to hold.

# Screenshots
![sack1](https://user-images.githubusercontent.com/28134842/90097451-9bcf8200-dd3e-11ea-9339-92eb8e61ad31.png)
![sack2](https://user-images.githubusercontent.com/28134842/90097455-a25df980-dd3e-11ea-9923-70fa6f1cd067.png)

# Versions and configuration

 - OS: Windows 7
 - Game Version: 0.E-4986-gb92c9f4
 - Graphics version: Tiles
 - Ingame language: [English]
 - Mods loaded: [
  "dda",
  "no_npc_food",
  "blazeindustries",
  "EngineeringEssentials",
  "aftershock",
  "crt_expansion",
  "Mining_Mod",
  "speedydex",
  "StatsThroughSkills",
  "stats_through_kills",
  "AftershockUDP",
  "BlazeIndustriesUDP",
  "crt_expansionUDP"
]

# Additional context

**Comment by AMurkin** [comment]
Non-rigid, you mean?

**Comment by mqrause** [comment]
The amoung of things you can put into a container also depends on the volume of the pocket said container is in. When wielding the canvas sack or having it in a pocket with at least 16l volume, you can fill it up completely.

**Comment by eilaattwood** [comment]
> 
> 
> Non-rigid, you mean?

Sure. Just found out that my English sucks.

**Comment by eilaattwood** [comment]
> 
> 
> The amount of things you can put into a container also depends on the volume of the pocket said container is in. When wielding the canvas sack or having it in a pocket with at least 16l volume, you can fill it up completely.

Yes. You are right. However, I think, there should be a warning about this particular issue, because that is really not obvious.
