### ISSUE TITLE
UPS-powered tools doesn't consume charges when not wielded

### ISSUE THREAD

**Issue by Antrocon** [CleverRaven/Cataclysm-DDA#42909]
# Describe the bug
UPS-modded tools doesn't consume UPS charges when UPS & tools not wielded (i.e. lying in vicinity) and used in craft

# Steps To Reproduce
1. spawn UPS, heavy battery high-capacity, UPS mod, mess kit, raw sausages (2)
2. apply ups mod to mess kit, reload UPS with battery
3. drop UPS & mess kit in nearby cell
4. craft "cooked sausage"
5. observe craft completed, UPS charges not change from 1250
6. pick up UPS & mess kit
7. repeat craft
8. observe UPS charge go down 2 points to 1248 as expected

# Expected behavior
UPS charges deplete depending on craft regardless of whether it's wielded or lying around.
1248 charges expected on step #5, 1246 charges expected on step #8

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-4997-gaf19ae1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context
Unlimited powah!

**Comment by RoyBerube** [comment]
This problem has been fixed in PR #45781.
