### ISSUE TITLE
Can't recharge batteries outside the reality bubble

### ISSUE THREAD

**Issue by Duck13Tales** [CleverRaven/Cataclysm-DDA#42911]
# Describe the bug

It seems that in the latest experimentals, when outside the reality bubble the "battery charger" and the "recharging station" don't recharge any battery.

# Steps To Reproduce

1 - Install a battery charger and a recharging station in a vehicle with enough battery to make the charging.
2 - Activate them and put a battery "on them".
3 - Go away till they are out of your reality bubble.
4 - Wait 8 hours or more and come back.
5 - Notice that they didn't recharged even a bit of the battery power.
6 - Try waiting 8 hours or more near them and notice that they recharged a lot of energy to the battery.

# Expected behavior

Those parts should update once they get into your reality bubble, calculating how much energy was recharged and drained for this as needed.

# Screenshots

Not needed.

# Versions and configuration

I am using using the CDDA 0.E-b10900 with the mods:

DDA
Disable NPC needs
Stats through skills
Stats through kills
SpeedyDex

# Additional context

None.

**Comment by Mister-Cultist** [comment]
oh so that's why it's taking forever to charge my ups
