### ISSUE TITLE
Vehicle mounted gun repairs itself when uninstalled

### ISSUE THREAD

**Issue by Bulletfang** [CleverRaven/Cataclysm-DDA#42919]
# Describe the bug

A vehicle mounted gun that is broken by prolonged use is instantly repaired when uninstalled from its turret mount.

# Steps To Reproduce

1. Install weapon on car.
2. Use it extensively until it has the "xx" modifier, which makes it unusable.
3. Uninstall the "xx" weapon and see that the gun returns to its condition it was in prior to installation.

# Expected behavior

Weapon condition is consistent between installed and uninstalled states.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-4920-g6a34646 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    Bionic Slots [cbm_slots],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion]
]

# Additional context

I used an M4A1, installed it while it was in perfect condition, used it until it was broken, uninstalled it from the car to repair or throw it away and saw that it was perfectly fine again without me touching it. I then reinstalled the gun on the vehicle and it stayed in top condition.

**Comment by irwiss** [comment]
No longer reproducible on f0d7703 - firing blackpowder until gun is XX and removing it now produces metal chunks
