### ISSUE TITLE
Cutting quality discussion / Stone chopper skill requirements

### ISSUE THREAD

**Issue by Darkenlord1** [CleverRaven/Cataclysm-DDA#42916]
# Is your feature request related to a problem? Please describe.
Replace `fabrication` 3 skill to make stone chopper with 1 lvl of `survival`, cuz this craft is pointless on 3 fabrication in my opinion.

# Describe the solution you'd like
Replace skill requirement from `fabrication` 3 to `survival` 1-2.

# Describe alternatives you've considered
Remove `cutting` requirement from butchering and (or) replace it with `butchering`?
Or go further and add another type of butchering, which has only `butchering` quality requirement and gives bones and more butchering refuse.

# Additional context
Right now, without looting cities and etc. cutting can be obtained only with finding bone in bushes.

**Comment by Zireael07** [comment]
>  this craft is pointless on 3 fabrication in my opinion.

"it is pointless" is not an explanation. Why do you think it is pointless?

**Comment by Darkenlord1** [comment]
I think it's pointless because too level up to this level of fabrication you anyways need tool with cutting.
Only way to get tool with cutting is find bone in bushes.
I'm talking about "inawood" gameplay.

**Comment by Zireael07** [comment]
"innawoods" is not the only gameplay style used in CDDA, so this single fact does not make this "pointless". Also from my limited understanding, the stone axe/stone chopper is NOT easy to make if it is supposed to be effective at all.
A better solution would be to invent a different, easier to make cutting tool for "innawoods" style. Any ideas?

**Comment by Darkenlord1** [comment]
Maybe add recipe that require 1 level anvil, 1 level of hammering, flaking rock and survival level 1-2 requirement.

**Comment by Alex-Folts** [comment]
What about glass shard, can we make glass shard have cutting quality? Make improvised knife of glass shard?
You can find glass shards in bushes, you can find in bushes glass bottle or jar and break them for shards.

**Comment by Tamiore** [comment]
To be honest, it feels like large part of this issue stems from the fact that "cutting 1" is the ONLY cutting that exists.

So a sharp rock (something you can most definitely make/find in a forest) is as good for cutting as a steel hunting knife.

**Comment by Zireael07** [comment]
@Tamiore: Good point, and I was sure there was a preexisting issue about this, but I can't find it.

Definitely, an expansion of cutting levels would help. I'd give the knife or scissors cutting 3, and makeshift stuff cutting 1.

**Comment by danielkwinsor** [comment]
I have strong feelings in favor of expanding the levels of cutting, and to be honest, quite possibly more skills.  I have not raised them because it could be a large overhaul and I am in the doghouse with my own suggested change about the stone chopper.

I agree with the OP about stone chopper; I have a ticket that was rejected and I have a pull request https://github.com/CleverRaven/Cataclysm-DDA/pull/42812 that express similar ideas.
