### ISSUE TITLE
Magiclysm freezes when loading curious structure after visiting them once

### ISSUE THREAD

**Issue by thehdmicord** [CleverRaven/Cataclysm-DDA#42914]
# Describe the bug

Essentially what the title says. Every time I approach a curious structure in my modded Cataclysm with Magiclysm enabled, my game freezes and becomes totally unresponsive, to where I have to Alt+F4 to close it out. Oddly enough, the first time I visit a curious structure is when the game plays well for the most part, it's when I leave the curious structure, save away from it, and return that it freezes upon entering a certain radius of it. Even worse, my first Cataclysm character I spent over a week on just got his save bricked because I was unlucky enough to save inside of a curious structure; every time I try to load the save, it's stuck on loading and becomes unresponsive.

# Steps To Reproduce

1. Approach any curious structure
2. Explore curious structure partially, whether it's to the first basement level or the surface level
3a. Leave the curious structure and save the game
3b. Alternatively, save the game inside the structure
4. Try to load the save after it is made. If you are outside the curious structure and not within a certain distance of it, your game will freeze upon approaching it again. If you saved inside the structure, your save will not load at all and is now bricked.

# Expected behavior

The game to not freeze or brick saves

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-4997-gaf19ae1
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: dda, no_npc_food, aftershock, Arcana, crt_expansion, magiclysm, Bootleg_Walkers, no_freeze, DinoMod, No_Rail_Stations, Graphical_Overmap. Mutation_Changes, Cata++

**Comment by anothersimulacrum** [comment]
Magiclysm does not have a structure called 'Curious Structure', but it appears the third party mod Arcana does. We can't do anything about issue with third party mods.
