### ISSUE TITLE
Inhaler starts empty on asthmatic character creation

### ISSUE THREAD

**Issue by purgatorios** [CleverRaven/Cataclysm-DDA#42937]
# Describe the bug

Inhaler starts empty when asthmatic trait is taken.

# Steps To Reproduce

1. Make a player with the asthmatic trait.
2. Check inventory for albuterol charges in inhaler.

# Expected behavior

Player with asthmatic trait starts with inhaler full of albuterol.

# Screenshots

[image](https://user-images.githubusercontent.com/55556857/90317361-be4bd180-dedd-11ea-9e9e-2d972f32cf46.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-5001-gec1deea [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by wapcaplet** [comment]
Still reproducible in 0.E-6050-g 74636a72f8
