### ISSUE TITLE
Question on a stable working release

### ISSUE THREAD

**Issue by TychaiosIlithios** [CleverRaven/Cataclysm-DDA#42930]
# Is your feature request related to a problem? Please describe.
Can't easily find any releases with semi okay quality and lack of breaking bugs.

# Describe the solution you'd like
Have any single release reasonably fixed and its stability being noted in releases page. Dunno, maybe besides 'stable' add 'playable'.

# Describe alternatives you've considered
Not showing cataclysm to newbies 'cuz them lame casuals can't handle a good ol' bug every now and 'en. 

# Additional context
Hello, I used to play and enjoy one of the last experimental releases pre adaptation to 1 second turns. Loved it - some bugs but many features and generally The feel of a good sandbox.  Then experimentals went to a new level which led to waves of bugs related to firstly - change of turn pace, then to great but new camping system - incredible but not newbie friendly. So in another attempt to show some good to the newbies recently had a run on stable versions. 

Starting with Danny - best mods were there, i.e. dinomod and more survival tools, decent tileset. All usable, workable, stable, enjoyable - was finishing up the setup when blam - right to ma face the bug of reverse npc camp craft levels, i.e. when upgrading camp blacksmith reduces the number of recipes available. 

Then checked others - in notes it says that Ellison 2 is the most stable Ellison ever hoorah. Okay, downloading - the result contains tiny limited set of mods and font-tileset decisions that during standard config setup to large monitor (235x65 terminal) make eyes bleed out.

This was pretty much the end of attempts.

Here I'm not a developer, not a contributor, just an ebil greedy consumer and just noting that currently nothing in releases thread feels consumable or adaptable to an easy showcase for first time players. 

Suggestions?

either/ (easiest?) get some latest pre 1sec turn experimental to releases page
or/ (easiest?) get Danny that fix cuz that bug causes all stable time investment to complete sadness 
or/ get some other stable release actually usable for different sizes of monitors without extensive tweaking

Minecraft in its glory days had many patches but had stable versions that hosted mods and modding community for years while development of main version went on - and I see no such islands here, making this game quite similar to xcom-piratez - the genius creation that is not being played cuz everyone is waiting for the next patch. 

At the moment proper playing cataclysm involves either the survivalist zomboid style of enjoy the early dying till you somehow survive the first year or demands that player knows how to edit all of the json files from saves to mods just to be able to undo engame bugs. And problem is that many gamers want game as complex as cataclysm to play it sandbox style closer to the endgame - or at least to see someone play it and have a goal of reaching such peaks. Well - peaks are bugged, goal not existent, attempts to motivate people to share ma hobby failing. It is easier to persuade people to play zangband - which in comparison is old, primitive - but not bugged. And less players means less potentially invested people to modding or even programming level. 

And just for your fun reading - I sorta kinda lost ma fav version of the game long ago due to system crash, then from time to time tried to adapt to newer versions, have a bunch of ma own mods to keep the better stuff in collection. And my friends know of this hobby and of attempts to advertise it - but due to lack of any solid bugless version they are treating me as a mouse, resolute on chewing a cactus - respect with traces of mental concerns. Also I keep sending them quotes from this forum and they treat you guys as titans of thought, people of inhuman dedication to the cause,  focal points of admiration.... and keep playing other games like japanese grinders which are dumb but workable and bugless time dumps.

**Comment by Zireael07** [comment]
There is no such thing as a 'bugless' version, even the previous 'stable' versions were not bug free.

And regarding your other issue, Cata was for years designed for 80x24 terminals and only recently upgraded to take into account bigger screens and bigger terminals. Default fonts/tiles cannot be too big, because there is the Android port to consider, which must fit the game and the sidebar onto a phone screen...

**Comment by ZhilkinSerg** [comment]
You can find stable and latest experimental downloads here - https://cataclysmdda.org/releases/.

If you want to download a specific experimental build, you can use Github release page - https://github.com/CleverRaven/Cataclysm-DDA/releases/.

**Comment by Zireael07** [comment]
Also existence of this thread is proof that 'stable' naming is misleading, see #42814

**Comment by ZhilkinSerg** [comment]
> 
> 
> Also existence of this thread is (one more) proof that 'stable' naming is misleading, see #42814

I do not agree that personal tastes in fonts, tilesets and mods make `0.E-2` unstable. There are certainly bugs left there, but we've moved too far away to spend efforts backporting bugfixes to `0.E`.

**Comment by Zireael07** [comment]
I didn't mean his tastes in fonts and tilesets, I mean the fact that he rightly points out that 'stable' isn't bugfree even though he expects them to be so.

**Comment by Proluiz** [comment]
man i'm about to copy paste a list of lot of famous games that have a stable version but still has lot of bugs and even fatals ones, boy bugs exist in EVERY games.
Tell me why sometimes people get banned from online games with the reason "explot, bug abuse"?

Just stop thinking that a game must be bug-free, this is impossible!

**Comment by ZhilkinSerg** [comment]
> I didn't mean his tastes in fonts and tilesets, I mean the fact that he rightly points out that 'stable' isn't bugfree even though he expects them to be so.

Well, that is kinda invalid expectation - stable version provides most possible bug-free experience, but it was never intended to be (or advertised as) 100% bug-free. Anyway, they are yet to tell which major game breaking bugs exist in 0.E-2 - it is unlikely, but not impossible, there will be 0.E-3.

**Comment by KorGgenT** [comment]
> maybe besides 'stable' add 'playable'.

All of our stable versions are playable, that's the whole point of the freeze and release cycle.you mention dinomod, but that's in the current version as well so idk. It sounds to me it's what ZS says, that it's your taste in mods and features that are clashing with what you attribute to the loose term "playable". There are 3rd party mods all over the place, but most of them as far as i'm aware keep up with experimental and are not developed for older versions.

**Comment by kevingranade** [comment]
I'm in favor of this happening and fully support your endeavor to backport bugfixes to 0.E, thanks for volunteering.

Looking forward to those PRs.
