### ISSUE TITLE
CBMs not using power correctly

### ISSUE THREAD

**Issue by Bulletfang** [CleverRaven/Cataclysm-DDA#42938]
# Describe the bug
Installed 4 CBMs, 3 of which consume power when used. All 3 of those do not use power correctly in one way or another.
The first one, Dielectric Capacitance System does not consume any power at all, I can have it running 24/7 with no drain whatsoever.
The  Second one is Leukocyte Breeder System, It seems to use power correctly, but the advertised power consumption is wrong, saying it needs 5 J/turn, which is obviously not intended, or the case.
The third is the Monomolecular Blade, which should cost 50 power units per activation according to its tooltip, but also doesn't consume any at all.

# Steps To Reproduce

1. Install the above mentioned CBMs.
2. Use them.
3. Witness incorrect power usage.

# Expected behavior

Correct power usage.

# Screenshots

![123132](https://user-images.githubusercontent.com/45204409/90318340-1e6b6380-df30-11ea-886f-f9c696a64921.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-4920-g6a34646 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    Bionic Slots [cbm_slots],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion]
]

# Additional context

Considering that 3 out of 3 power consuming CBMs, which I did not cherrypick, do not consume power correctly in one way or another, I'd say it is reasonable to assume that there are more who have similar problems.

**Comment by Fris0uman** [comment]
Just tested it on latest build: leucocyte breeder and dielectric capacitance do both consume 5J/turn as advertised and Monomolecular blade does consume 50J per activation.
Maybe you are confusing `J` and `kJ`

**Comment by Bulletfang** [comment]
@Fris0uman You are right, I did confuse them. I apologize.
