### ISSUE TITLE
Not enough equipment or resizing for small characters

### ISSUE THREAD

**Issue by Mister-Cultist** [CleverRaven/Cataclysm-DDA#42931]
I've been preparing to make a mouse build in the game but ran into the problem that barely any storage gear can be made to fit them, I can't even craft or modify any kind of backpack to make it the right size for me.

while I can modify my survivor trenchcoat to be the size for me I can't do the same to a backpack that I custom built for my character, at that skill level you'd think you could build somthing the right size from spare parts, you can't even make somthing simple like a smaller axe loops or modify cloth face coverings for your muzzle like a zentai or balaclava.

**Comment by souricelle** [comment]
They make little kid backpacks, lunch pails and purses IRL. Tiny makes you kid sized. Some kid-sized containers could be added to the child zombie loot pool and to schools and other areas.

**Comment by Mister-Cultist** [comment]
I've looked into it further and I can't even downsize a scarf to make it wearable, I could do that with a knife.

**Comment by Amoebka** [comment]
Mutant clothing is just a total mess in general. Hopefully at some point someone overhauls the whole system to use actual clothing sizes, because this whole ad-hoc OVERSIZE, VARSIZE business is extremely error-prone and requires a lot of item/recipe duplication.

**Comment by Mister-Cultist** [comment]
yeah as of now being a mutant that changes your size can make the game nearly unplayable, mouse boys just die of frostbite to their exposed noses in the winter
