### ISSUE TITLE
Revolvers do not drop/add casings to inventory upon reloading or unloading

### ISSUE THREAD

**Issue by surprisinglyeasey** [CleverRaven/Cataclysm-DDA#42941]
# Describe the bug
Same as the title, Revolvers do not seem to give back casings. tested with Uberti cattleman, S&W 619, S&W 629, S&W model 10, and S&W 500

# Steps To Reproduce
1. make a player with "wild west gunslinger" or "police detective" profession to start with a revolver or use debug to add one
2. shoot a full cylinder and reload/unload the gun
3. no casings are dropped or added to the characters inventory

# Expected behavior
after shooting a cylinder, reloading the gun or unloading it should give back casings as revolvers obviously don't destroy the casing when fired. perhaps there is potential room for a mechanic where reloading is slower if you have to pull the casing out to add another round and for loading speedloaders you need to first fully (U)nload the revolver of spent casings

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-5001-gec1deea [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by carmakazi** [comment]
This seems to be true for every gun that does not automatically eject a casing, but instead you are supposed to get a casing upon reloading.  Specifically I've found this to be true with the Ruger LCR .22, Single barrel shotgun, double barrel shotgun, and Winchester M37.

**Comment by wapcaplet** [comment]
Same / related to #44090 and #44230

**Comment by Marrim** [comment]
Here's the message accompanying the bug (I was using a Milkor MGL):
`ERROR : src/item.cpp:1102 [ret_val<bool> item::put_in(const item&, item_pocket::pocket_type)] tried to put an item (40x46mm_m118_casing) count (1) in a container (mgl) that cannot contain it: pocket with type (CONTAINER) not found`

In the game files, Milkor MGL has
`"pocket_data": [ { "pocket_type": "MAGAZINE", "rigid": true, "ammo_restriction": { "40x46mm": 4 } } ]`
so apparently it can _only_ contain grenades, not casings.

The bug appears for all weapons with `RELOAD_EJECT`.
