### ISSUE TITLE
Cannot store certain items in a tool belt that claim they can be stored in.

### ISSUE THREAD

**Issue by AfroSGT** [CleverRaven/Cataclysm-DDA#42953]
# Describe the bug
Cannot store items, in this case the scrub brush and duct tape, in the tool belt, even though both items claim that they can be stored in a tool belt, and the scrub brush even going so far as to be categorized as a tool. It seems you CAN store them in pocket 1 on the belt, but pockets 2-6 seem to arbitrate what tools or items you can store in them. 

# Steps To Reproduce

Have Tool belt and the scrub brush tool
try to put brush in pockets 2-6
fail

# Expected behavior

If something has the tool category, and fits the physical size limits of the pocket, it should go on the tool belt

# Versions and configuration
windows 10
version 10914
build 0.E-5001-gec1deea

# Additional context

This is my first time playing with he new inventory system, and first time posting, so hopefully i have done so correctly.  The fact that i cannot seem to directly mandate what goes into what pocket is immensely frustrating. Why on earth even restrict the tool belt to only accepting tools if you cant put tools in that say you can put them in! The scrub brush is categorized as a tool, its size fits, and it says in its own description that i can be stored in the tool belt. Also, side note, i seem to have to tell the tool belt to accept tools?? Through the autopick up menu on the tool belt.

**Comment by KorGgenT** [comment]
If you can put it in one of the pockets, then the item isn't lying; you _can_ put it in the tool belt.

**Comment by AfroSGT** [comment]
> 
> 
> If you can put it in one of the pockets, then the item isn't lying; you _can_ put it in the tool belt.

the issue with that is pocket 1 on the toolbelt can store *anything,* its an unrestricted inventory, which is not what the specific inventory tags on items are supposed to be for.  there is no point in saying a specific tool can be put in the tool belt if anything can be put in pocket 1, its intended that pockets 2-6 are for tools and specific weapons. a wrench and the scrub brush fall within the same qualities to be stored in a tool specific pocket, yet the scrub brush cannot. that would be a bug.

**Comment by kevingranade** [comment]
Your rationale is incorrect, if an item says it fits in some article of clothing, all it means is it can fit *somewhere*.

However, the scrub brush could get the belt clip flag.
