### ISSUE TITLE
Add context to encumbrance effects UI

### ISSUE THREAD

**Issue by bouchacha** [CleverRaven/Cataclysm-DDA#42966]
The encumbrance UI is rather opaque. For example, mouth encumbrance of 8 means "Stamina Regeneration: -1". How significant is this? How much does my character normally regenerate stamina? Is -1 a lot? I'm helpfully told that arm encumbrance of 32 is "Melee stamina cost: +64". Ok. Is that a lot? How much stamina do melee attacks normally use? If it's 30, then +64 is a huge deal. If it's 500, maybe not so much. I don't know what the baseline is, so the encumbrance information is near useless.

Two possible solutions:
1. Simplest would be changing all the modifiers into percentages. "-10% stamina regeneration" is far more scrutable than "-32" or whatever. I can see this being insufficient when the percentage modifier is affecting a variable you also don't understand. For example, +30% dispersion doesn't tell you what the baseline dispersion is.
2. The ideal solution would be to include the baseline stat. For example "132 - 1 stamina regeneration" is infinitely more useful than either one on their own.

**Comment by kevingranade** [comment]
Another option is to remove the numbers and replace with descriptive text, the numbers are leaking internal game state.

**Comment by Night-Pryanik** [comment]
No discussion in over a year, closing.

**Comment by Zireael07** [comment]
Again, project page claims it was done, which it wasn't. The current state of things requires players to find out what the numbers mean on the wiki or on discord - this should be clear in-game.

**Comment by Night-Pryanik** [comment]
Sure, improvements would be good, but it isn't worth an open discussion-type issue.

**Comment by Zireael07** [comment]
Keeping issues open might be worth it if the alternative is misleading people browsing the project page into thinking this is done
