### ISSUE TITLE
Hungarian language error

### ISSUE THREAD

**Issue by davidkiraly1** [CleverRaven/Cataclysm-DDA#42969]
Regarding the Hungarian language: The Hungarian language does not work well if I exit the game and then change the accented characters (letters) to signs and I can only correct this by deleting the game but until I exit the game again and so my map is lost. For example, I think it replaces á: `, but it happens with every accented" Hungarian "letter. thanks for fixing this in 0.E this in a quick reissue
platform: android

**Comment by ZhilkinSerg** [comment]
Duplicate of #42638
