### ISSUE TITLE
Deciding how far back the game needs save compatibility and removing save compatibility with very old game versions

### ISSUE THREAD

**Issue by Hirmuolio** [CleverRaven/Cataclysm-DDA#42973]
# Is your feature request related to a problem? Please describe.
There is large amount of code that exists only to make it possible to load old saves.

Most of the time this code just sits there. It makes reading through code more tedious.

Sometimes new features require changes to old compatibility code. Most likely the developer that encounters this would rather just remove the old compatibility code but without knowing if it needs to be kept or not they may instead just patch something in to keep it working.

# Describe the solution you'd like
It should be decided how far back save file compatibility should be maintained.

Compatibility with two latest stable releases is probably enough. So 0.E and 0.F after 0.F is released. Probably not good idea to start messing with this code now since we are already in feature freeze.

# Describe alternatives you've considered
Leave as is.

# Additional context

**Comment by kevingranade** [comment]
The policy for long time has been one stable version although I don't think that's in documentation anywhere just what I've kept saying.

**Comment by jbytheway** [comment]
(Probably shouldn't ask this on a closed issue, but I will anyway)

Do we make a distinction between the savegame and the saved map data?  Because we don't offer a means to upgrade old map data, so players are much more likely to encounter map data from older versions if they have long-running worlds.
