### ISSUE TITLE
attemping to shot the mod "rail-mounted crossbow" cause a bug.

### ISSUE THREAD

**Issue by Proluiz** [CleverRaven/Cataclysm-DDA#42979]
# Describe the bug
I decided to apply a rail-mounted cross bow to my own compound crossbow and after trying to use the second shot like i expected instead firing it bumped out to bedug screen. "Attempted to fire zero or negative shots using compound crossbow+2"

# Steps To Reproduce
1. Have a compound crossbow
2. Install the Rail-mounted crossbow mod on it.
3. Load two bolts in the crossbow.
4. Try firing twice.

# Expected behavior
Expected a second shot.

# Screenshots
none.

# Versions and configuration
- OS: Windows 7
- Game Version: 0.E-4942-gc8ac471 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [Dark Days Ahead [dda],    Disable NPC Needs [no_npc_food],    Stats Through Skills [StatsThroughSkills]]

# Additional context
[debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5081677/debug.zip)
[Olney.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5081682/Olney.zip)

**Comment by olanti-p** [comment]
To be more precise, you've fired the compound crossbow, and than you've tried to fire it again. There was a bug that allowed you to try to fire an empty crossbow part of the gun if there was some other non-empty part of the gun (e.g. empty crossbow + loaded rail-mounted crossbow, or a loaded assault rifle + empty rail-mounted crossbow). That should be fixed now.

The rail-mounted crossbow can actually be fired even without this fix, you just have to switch your crossbow from firing in it's base  mode to firing from the gunmod (press `s` or `F` while aiming, or press `F` before firing)
