### ISSUE TITLE
Encumbrance Doesn't Upon Dropping Items

### ISSUE THREAD

**Issue by HarleyLorenzo** [CleverRaven/Cataclysm-DDA#42983]
# Describe the bug

Encumbrance does not update when you drop items from a container. It only updates upon unloading or taking off/re-wearing the container.

# Steps To Reproduce

1. Put items into a worn container such as a backpack
2. Drop the items, don't unload
3. Notice the encumbrance did not update upon dropping the items, keeping the encumbrance it had at whatever it was when it was filled up.

# Expected behavior

Encumbrance should update as containers are emptied via dropping items from them, as otherwise you'll have an encumbrance 26 backpack with nothing in it.

# Screenshots

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.E-5060-gd0982ce735 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Stats Through Kills [stats_through_kills],
    Fuji's Military Profession Pack [fuji_mpp]
]

# Additional context

**Comment by int-ua** [comment]
Confirming. At least it was like this in experimentals a week ago.

**Comment by wapcaplet** [comment]
Confirmed as well in 0.E-5236-ge7434cff45

**Comment by wapcaplet** [comment]
This issue was partly resolved by #43108 - encumbrance now updates correctly when dropping with `d` or `D`.

However, the issue still occurs when dropping items with advanced inventory manager.
