### ISSUE TITLE
Z-levels bug: extra level of ceiling auto-generated for auto-generated floor (where said floor should already be the roof). 

### ISSUE THREAD

**Issue by Tamiore** [CleverRaven/Cataclysm-DDA#42987]
Let's say you have a cave. Walls made of "solid rock" tiles. Z-levels generation algorithm assigns "rock floor" to Z+1 level to represent the top layer of those walls. (So far so good.)
However, since it's rock FLOOR, not rock ROOF that's been assigned, the algorithm does NOT stop there. It now assigns a ROOF tile to Z+2 level for every rock floor tile created. 
So what you end up with is a cave with a layer of ceiling floating above it at Z+2 level.

# Steps To Reproduce

1) Go to a cave (or something similar) with Z-levels enabled, save the game, load to the game. (Algorithm only assigns tiles when engine is initially loaded.)
2) Witness the glory of floating ceiling.

# Expected behavior

Algorithm should stop once it has created "rock roof" on level Z+1.

# Screenshots

![John __11-25-02_Russia TZ 2 Standard Time](https://user-images.githubusercontent.com/61312205/90391234-7374ba00-e095-11ea-9de2-9ea041271800.png)
Ceiling above a character already standing on top of the cave.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-4997-gaf19ae1 [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Slots [cbm_slots]
]

# Additional context

I'm pretty sure similar thing is also happening for many naturally-occurring structures, not just for caves.

**Comment by Night-Pryanik** [comment]
Seems like it was fixed some time ago, as I can't confirm it neither on caves, nor mound of dirt (location) on 0.F-6401. If this is still an issue, ping me, and I'll reopen it.
