### ISSUE TITLE
Zone Autosort Sorts Containers Of Food/Drink/Etc Not By Their Contents

### ISSUE THREAD

**Issue by HarleyLorenzo** [CleverRaven/Cataclysm-DDA#42995]
# Describe the bug

When you autosort using zones, it is expected, that containers of food, drink, etc get sorted by their contents. A gallon of milk should go into the food category, not in the containers category. However, this is currently not the case, and a gallon of milk will go into the wrong category.

# Steps To Reproduce

1. Get a container of a food or drink, set up an appropriate category (such as food or drink) as well as a custom category with the filters -c:food, -c:drink
2. Sort
3. Notice that the food/drink in a container gets sorted with containers, not as food or drink

# Expected behavior

It should go into the appropriate category of its contents, such as food or drink, and not containers.

# Screenshots

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.E-5063-ga894861be0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Stats Through Kills [stats_through_kills],
    Fuji's Military Profession Pack [fuji_mpp]
]

# Additional context

Edited because I'm not sure if it gets sorted with containers or not, doing more testing.

**Comment by int-ua** [comment]
I'm almost sure it will have no effect, but have you tried with P.food and P.drink zones defined? P is for perishable.

**Comment by HarleyLorenzo** [comment]
> Have you tried with P.food and P.drink zones defined? P is for perishable.
> 
> https://github.com/CleverRaven/Cataclysm-DDA/blob/f47593f8c0051e20d4975a26b7aad2f940971132/data/json/loot_zones.json#L15

If I disable my custom stockpile, it sorts properly with p. food and p. drink stockpiles, but my custom stockpile should have them disabled anyhow, unless -c:food and -c:drink do not affect perishables anymore (I'm 99% sure they at least used to back a few months ago.)

**Comment by esotericist** [comment]
Near as i can tell the original issue described here has been resolved (albeit replaced with a different problem as of #44245 )

closing accordingly.
