### ISSUE TITLE
Excessive blood generation from butchering human corpses

### ISSUE THREAD

**Issue by Stretop** [CleverRaven/Cataclysm-DDA#42997]
There is around 5 litres of blood in average human body. In current experimental version the amount of human blood gained via full butchering is such, that one can **fill whole 60L tank** mounted on a vehicle _and still have some to spare_.

# Steps To Reproduce

1. Get a human corpse.
2. Get a vehicle with empty 60L tank mounted.
3. Get all the tools needed for the full butchery (including butcher knife with "butchery 25" quality).
4. Perform full butchery on the human corpse.

# Expected behavior

Products of the butchery process obey the Laws of Conservation of Mass.

# Observed behavior

You can fill 60L tank completely and still have to pour on the ground 796 units (around 200 L) of blood.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-5001-gec1deea [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    <color_light_red>Secronom</color> [secronom],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Engineering essentials [EngineeringEssentials],
    DinoMod [DinoMod],
    Modular Turrets Remake [modular_turrets_remake],
    Tankmod: Revived [Tankmod_Revived],
    Cataclysm++ [Cata++],
    Alternative Map Key [alt_map_key],
    Crazy Cataclysm [crazy_cataclysm],
    Mythical Martial Arts [MMA],
    More Survivor Stuff [more_survivor_stuff],
    Vampiric Stuff [vamp_stuff],
    Vampiric Stuff + Arcana Mod Extension [vamp_stuff+arcana],
    Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
    Whaleys Hair Mod (UDP Tweaks) [WHALEYHAIR_UDP],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Arcana - UndeadPeople Tileset [ArcanaUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Crazy Cataclysm - UndeadPeople Tileset [CrazyCataclysmUDP],
    DinoMod - UndeadPeople Tileset [DinoModUDP],
    Graphical Overmap [Graphical_Overmap],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by KorGgenT** [comment]
can you confirm that it is the same with no mods?

**Comment by Stretop** [comment]
No, without mods there is no blood harvested via butchery.
