### ISSUE TITLE
[Dinomod] Stegosauruses don't fight back against zombies.

### ISSUE THREAD

**Issue by ussdefiant60** [CleverRaven/Cataclysm-DDA#42996]
# Describe the bug

I kited about 5 bog-standard zombies into a couple of Stegos that were hanging around near the edge of town. They killed a Stego without getting attacked back once. 

# Steps To Reproduce

1. Load attached save, take about 50 turns of idling, witness no attacks from Stego on zombies.

# Expected behavior

Stegosaurus should at least attempt to attack the zombies attacking it with Big Stompy Feet and Big Spiky Tail.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-5063-ga894861 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Stats Through Kills [stats_through_kills]
]

[Arredondo.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5085817/Arredondo.zip)

**Comment by anothersimulacrum** [comment]
@LyleSY heads up.
