### ISSUE TITLE
smite spell does no damage

### ISSUE THREAD

**Issue by shadowsapex** [CleverRaven/Cataclysm-DDA#43005]
# Describe the bug
casting smite causes following error, does no damage

DEBUG    : monster::deal_damage_handle_type: illegal damage type DT_NONE

 FUNCTION : virtual void monster::deal_damage_handle_type(const damage_unit &, bodypart_id, int &, int &)
 FILE     : /var/lib/jenkins/workspace/Cataclysm-Android/android/app/jni/src/../../../../src/monster.cpp
 LINE     : 1573

# Steps To Reproduce
cast smite on hostile target

# Expected behavior
deals damage

# Screenshots

# Versions and configuration
- OS: Android
    - OS Version: Manufacturer: LGE; Model: LM-X210CM; Release: 8.1.0; Incremental: 200921745b0f0; 
- Game Version: d0982ce [32-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm]
]

 

# Additional context

**Comment by ZhilkinSerg** [comment]
Probably needs

```
    "damage_type": "true"
```

to be added to `\data\mods\Magiclysm\Spells\animist.json`
