### ISSUE TITLE
generic_factory.h (body part error)

### ISSUE THREAD

**Issue by CHJKDM51** [CleverRaven/Cataclysm-DDA#43007]
# Describe the bug

 DEBUG    : invalid body part id ""

 FUNCTION : int_id<T> generic_factory<T>::convert(const string_id<T>&, const int_id<T>&) const [with T = body_part_type]
 FILE     : src/generic_factory.h
 LINE     : 436

# Steps To Reproduce

download save
move to map note "BUG"
(yellow N north-north-west from character position)

# Expected behavior

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-5109-g0e73b88 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

Its not a crash, just an error spam.

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5088112/debug.log)

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5088114/save.zip)

**Comment by Fris0uman** [comment]
Please list your mods
