### ISSUE TITLE
reloaded .45-70 cannot be disassembled

### ISSUE THREAD

**Issue by BQurious** [CleverRaven/Cataclysm-DDA#43011]
# Describe the bug

.45-70 ammo that is found ("industrial"/pre-cata ones) can be disassembled, but ones that were hand-loaded/reloaded by the survivor cannot.

# Steps To Reproduce

1. Observe a .45-70
2. Spawn in casing or disassemble the above
3. Craft .45-70
4. Observe that the result cannot be disassembled.

# Expected behavior

Either both should be disassemblablable or neither should be.
If there is a specific reason why only reloaded cannot be disassembled, add that reason to JSON comments?

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by BQurious** [comment]
So uh... Does this mean I have the green light to PR for this?

**Comment by anothersimulacrum** [comment]
Yes.
