### ISSUE TITLE
[Magiclysm] Forge Lords offering various items for free/other pricing oddities.

### ISSUE THREAD

**Issue by ussdefiant60** [CleverRaven/Cataclysm-DDA#43018]
# Describe the bug

So, i've encountered the Forge Of Wonders from Magiclysm for the first time, and some of the stuff the Forge Lord is offering to sell seems a bit wacky on pricing in various ways, and i'm not aware of any pricing guidelines to offer a fix PR myself:

Stuff being offered for outright free:
Everburning Torches (somewhere in the 2k area?)
Spider Box 
Enchanted Tailor Kit
The Tome Of The Hollow Earth
A Bog-Standard Empty Lighter from the shopkeep's personal inventory (vanilla issue?)

Items that seem to have no value on their contents/effects:
a)Glass Flask Of Liquid Mercury (I have no idea what the value of this stuff is)
b) Endless Flask (Freely Spawning Whiskey should be worth more than 0.20. 2-5k?)
c) Escape Boots (Not sure if the $10 value on it just is copied from something else. One/day items seems like it needs an extra zero on it or something)

Item Categories that're the same price across all items.

a)All lesser wands are $480, greater is $720, no matter what type of spell or the number of charges in them. 
b)Rings are $120, no matter the price or precise + on it (Rings of Prot +6/+8 are the same)

# Expected behavior

I have no real experiences with actually using any of Magiclysms' toys, so i don't feel confident with making a PR to adjust the value of any of these things, they just caught my eye when browsing through the offerings from the shopkeeper.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-5096-gd31f35a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Stats Through Kills [stats_through_kills]
]

**Comment by Moumix3** [comment]
I know for sure that for some items (enchanted tailor's box, spider box), it's to do with it having 0 charges. As soon as those items have 1 charge, their price goes back to the price set in the JSON files (around $1000). I'm not sure how this can be fixed in JSON though :/

Everburning torches have a price set to 0 in the JSON file which seems like an oversight and is easily fixed. :)

For the other items, I can only confirm the issues mentioned.

**Comment by Maleclypse** [comment]
I believe this issue is closed by #47238

**Comment by actual-nh** [comment]
Are the 0-charge item prices fixed?

**Comment by KorGgenT** [comment]
i'll do a brief check on this today.

**Comment by Saicchi** [comment]
It's hard to check some items they are not being solved. I believe #47206 will help with this.

**Comment by Maleclypse** [comment]
I fixed every zero charge item I could find in a previous pr
