### ISSUE TITLE
Make a tool to detect or lint errors like this sieve

### ISSUE THREAD

**Issue by danielkwinsor** [CleverRaven/Cataclysm-DDA#43029]
# Describe the bug

{
    "result": "sieve_primitive",
    "type": "recipe",
    "category": "**CC_ARMOR**",
    "subcategory": "CSC_OTHER_TOOLS",
    "skill_used": "fabrication",
    "skills_required": [ [ "survival", 1 ], [ "tailor", 2 ] ],
    "difficulty": 3,
    "time": "45 m",
    "autolearn": true,
    "components": [ [ [ "straw_pile", 3 ], [ "birchbark", 5 ] ] ]
  },

# Screenshots
<img width="1920" alt="Annotation 2020-08-18 210821" src="https://user-images.githubusercontent.com/2822992/90591303-a69f7200-e197-11ea-8722-184ab8b0ecb8.png">

**Comment by anothersimulacrum** [comment]
Please fill out the template, it's very easy to look over what's wrong there (an invalid category is specified).

This should be incorporated into the recipe loading code to give an error at load time.

**Comment by jbytheway** [comment]
I think the category isn't invalid, but it's mismatched with its subcategory.

**Comment by anothersimulacrum** [comment]
Sorry, I meant subcategory, yes.
