### ISSUE TITLE
Survivor Profession need a revision up.

### ISSUE THREAD

**Issue by Xindage** [CleverRaven/Cataclysm-DDA#43028]
# Is your feature request related to a problem? Please describe.
Not a problem but can be for beginners.
As a recommended starting profession with evacuee scenario and default settings. You start in late spring with a “warm” clothes and for a player who don't understand much of the game, this is not really a good way to begin. So my request is why don't have 2 profession to it? One focuses to more a default start, with balanced clothes for a moderate temperature because right now the survivor class already start with raising temperature due boots and the winter coat. And a new profession focused on a cold environment start for who uses the survivor for this.

# Describe the solution you'd like
Rethink the starting survivor class, keeping the actual inventory and just changing the clothes. And for a winter starting profession something similar to that inventory but with changes to match the style of start, with warm clothes and things related to it, for example he having a flint and steel in place of matchbooks.

# Describe alternatives you've considered
Just edit the survivor profession.

# Additional context
I could add a set example of clothes but i think it can be better did for who already know better the game than me.

**Comment by SpadeDraco** [comment]
Replacing the winter boots with standard boots, and the scarf with a bandanna would work. The winter jacket could probably be replaced with a Light Jacket without unbalancing anything. Will have to hop on and test whether that actually results in a "comfortable" survivor.

**Comment by Proluiz** [comment]
good point.

**Comment by venum4k** [comment]
I'm testing this right now and with the changes SpadeDraco suggested the temperature's comfortable after standing outside the evac shelter for 30 minutes in clear weather.
![image](https://user-images.githubusercontent.com/1928247/91639869-7b2b4b80-ea11-11ea-8f8e-4ed3b8f9114f.png)
