### ISSUE TITLE
Magiclysm: Wildshape + Genetic Chaos

### ISSUE THREAD

**Issue by WhelpCub** [CleverRaven/Cataclysm-DDA#43034]
# Describe the bug

Genetic Chaos will gain "Wildshape: Deer" mutation.

# Steps To Reproduce

1. Choose Genetic Chaos as start trait.
2. Wait Genetic Chaos to gain random mutation, until gain "Wildshape: Deer".

# Expected behavior

Genetic Chaos should not gain wildshape mutation, also the mutation do not remove even I do not wear the cloak (from the beginning).

# Versions and configuration

 - OS: Windows
 - Game Version: 0.E-5186-g810fe7d [64-bit]
 - Graphics version: Tiles
 - Ingame language: Chinese (Traditional)
 - Mods loaded: [
    Dark Days Ahead  [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion [crt_expansion],
    Magiclysm [magiclysm], 
    Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
    Crazy Cataclysm [crazy_cataclysm],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Crazy Cataclysm - UndeadPeople Tileset [CrazyCataclysmUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Whaleys Hair Mod (UDP Tweaks) [WHALEYHAIR_UDP]
    ]

**Comment by anothersimulacrum** [comment]
Needs `"valid": false` #29352
