### ISSUE TITLE
EMP blasts don't care about Z-levels

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#43032]
# Describe the bug

I'm in science lab tower, at z-level 6. There's incandescent hulk on ground floor. Each time I go over its location I get hit by EMP blast.

# Steps To Reproduce

Well, I guess, spawn high enough building, spawn incandescent hulk on ground level, go to the top level, move around where it is on the ground, see bionic energy drained.

# Expected behavior

As their fields are about 4-5 tiles wide, and I recall Kevin just recently [saying](https://discourse.cataclysmdda.org/t/make-creatures-with-the-leap-ability-able-to-jump-up-one-z-level/24404/4) z-distances are about x5 "regular" distances, it probably should only reach to adjacent z-levels, at the very most +2. Not 5 levels up (I guess it just doesn't check z coordinate).

# Versions and configuration

- OS: Windows 7
- Game Version: 0.E-5059-g10b2315 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by kevingranade** [comment]
Yea I agree the vertical part should be scaled, probaly to nothing in this case.
