### ISSUE TITLE
Reload glitch

### ISSUE THREAD

**Issue by CHJKDM51** [CleverRaven/Cataclysm-DDA#43059]
# Describe the bug
reloading shotgun wastes ammunition but does not add it to weapon.

# Steps To Reproduce
1. Download save
2. Hit reload
3. Select wielded weapon
4. Hit Enter

# Expected behavior
Expected to add ammunition to weapon internal mag.

# Screenshots

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-5228-g8731f05 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5101823/save.zip)

**Comment by kevingranade** [comment]
Fixed by #46000
