### ISSUE TITLE
Missing "BLACKPOWDER" flag from some black powder ammo

### ISSUE THREAD

**Issue by BQurious** [CleverRaven/Cataclysm-DDA#43055]
# Describe the bug

As per comment: 
https://github.com/CleverRaven/Cataclysm-DDA/blob/8731f0528a287552fabc4948f7b869f2a8dde6a2/data/json/items/ammo/4570.json#L80

Searching for ammo with "black powder" in the name, but not _extended_ by a BLACKPOWDER flag also turned up:
https://github.com/CleverRaven/Cataclysm-DDA/blob/8731f0528a287552fabc4948f7b869f2a8dde6a2/data/json/items/ammo/shot.json#L197

I don't even know what this flag does... I will try firing said ammo from some weapons, but idk what it implies.

# Steps To Reproduce

??

# Expected behavior

Add the flags, remove the comment in JSON.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

Digging through the code now to find out what it does, but it's probably better if someone who knows what the flag is about tells me/us.

**Comment by BQurious** [comment]
Aww man... Hit submit by mistake. Editing...

**Comment by eilaattwood** [comment]
>I don't even know what this flag does... I will try firing said ammo from some weapons, but idk what it implies.

It does [this](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON_FLAGS.md#effects)
