### ISSUE TITLE
Tool belt encumbrance

### ISSUE THREAD

**Issue by CHJKDM51** [CleverRaven/Cataclysm-DDA#43058]
# Describe the bug

Tool belt torso "encumbrance when full" is 36. Full backpack for example have only 25 max encumbrance.

# Steps To Reproduce

# Expected behavior
Expected less encumbrance (at least less than a backpack).

# Screenshots

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-5228-g8731f05 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

**Comment by kevingranade** [comment]
Need an outline of WHY it should be lower, my understanding is the weight on your hips plus tools swinging all over the place makes a toolbelt unusually encumbering.

**Comment by CHJKDM51** [comment]
> Need an outline of WHY it should be lower, my understanding is the weight on your hips plus tools swinging all over the place makes a toolbelt unusually encumbering.

1. Weight is a different game mechanic and have nothing to do with encumbrance.
2. Tools are not "swinging all over the place" in modern tool belts. 

I thought it would be obvious that belt with tools on your waist should have less encumbrance than an average backpack crammed with items.

![61mXj3NEsSL _AC_SL1181_](https://user-images.githubusercontent.com/58046029/90862508-2f83fc80-e396-11ea-9574-0d12fa61e803.jpg)
