### ISSUE TITLE
Missing movement sound

### ISSUE THREAD

**Issue by CHJKDM51** [CleverRaven/Cataclysm-DDA#43057]
# Describe the bug
Missing character surface movement sound.

# Steps To Reproduce
Move character on surface (grass, dirt, pavement,sidewalk and many more).

# Expected behavior
Expected to have sound.

# Screenshots

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-5228-g8731f05 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
Otopack. Problem occurred in recent builds.

**Comment by ZhilkinSerg** [comment]
We do no support thrid-party soundpacks here. You better contact that soundpack author.

**Comment by CHJKDM51** [comment]
@ soundpack also have that problem. What soundpacks do you support then?

**Comment by ZhilkinSerg** [comment]
> 
> 
> @ soundpack also have that problem. What soundpacks do you support then?

Only default one that is included in the repo.

**Comment by anothersimulacrum** [comment]
We do support soundpacks defining sounds for walking, which it sounds like is no longer working, so this issue is valid.

**Comment by Kenan2000** [comment]
Thank you for reopening this issue, @anothersimulacrum , I truly appreciate it!

Just to clarify as in my other closed issue
> As of experimental version 10922 while using @'s, 2ch, Otopack, my personal updated Otopack, CO.AG soundpacks - the sounds of walking barefoot, walking on dirt, metal, tarmac are missing even though all the soundpacks code is intact and fine and it worked perfectly fine in 10921 and ANY version BEFORE 10922

It seems that this is caused by 10922 which is very weird because it did not change anything in ```sounds.cpp```, it works just fine and perfectly on older experimental versions such as 10921, 10920, 10919 and etc

**Comment by anothersimulacrum** [comment]
2766dd0274079de7cabe87c1666eb50e9ca925ff appears to have accidentally removed the code for walking making sound.
