### ISSUE TITLE
Trying to grind strand of endochitin in the wind mill causes a crash

### ISSUE THREAD

**Issue by eilaattwood** [CleverRaven/Cataclysm-DDA#43090]
# Describe the bug

Trying to grind strand of endochitin in the wind mill causes a crash

# Steps To Reproduce

1. Construct wind mill and obtain some strands of endochitin
2. Insert endochitin into the mill
3. Start milling

# Expected behavior

No crash

# Screenshots

None

# Versions and configuration

- OS: Windows
    - OS Version: Win7 x64
- Game Version: 0.E-5241-g89c6d05 [64-bit]
- Graphics Version: Tiles
- Game Language: Русский [ru]
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у NPC [no_npc_food],
    Blaze Industries [blazeindustries],
    Engineering essentials [EngineeringEssentials],
    Aftershock [aftershock],
    Расширение К.Р.И.Т. [crt_expansion],
    Mining Mod [Mining_Mod],
    Скорость от ловкости [speedydex],
    Характеристики за навыки [StatsThroughSkills],
    Характеристики за убийства [stats_through_kills],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP]
]

# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5107107/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5107108/debug.log)

**Comment by ZhilkinSerg** [comment]
```PATCH
diff --git a/src/item.cpp b/src/item.cpp
index 977b2c4583..291fda402a 100644
--- a/src/item.cpp
+++ b/src/item.cpp
@@ -6650,38 +6650,34 @@ const mtype *item::get_mtype() const
 
 float item::get_specific_heat_liquid() const
 {
-    if( is_corpse() ) {
-        return made_of_types()[0]->specific_heat_liquid();
+    if( is_comestible() ) {
+        return get_comestible()->specific_heat_liquid;
     }
-    // If it is not a corpse it is a food
-    return get_comestible()->specific_heat_liquid;
+    return made_of_types()[0]->specific_heat_liquid();
 }
 
 float item::get_specific_heat_solid() const
 {
-    if( is_corpse() ) {
-        return made_of_types()[0]->specific_heat_solid();
+    if( is_comestible() ) {
+        return get_comestible()->specific_heat_solid;
     }
-    // If it is not a corpse it is a food
-    return get_comestible()->specific_heat_solid;
+    return made_of_types()[0]->specific_heat_solid();
 }
 
 float item::get_latent_heat() const
 {
-    if( is_corpse() ) {
-        return made_of_types()[0]->latent_heat();
+    if( is_comestible() ) {
+        return get_comestible()->latent_heat;
     }
-    // If it is not a corpse it is a food
-    return get_comestible()->latent_heat;
+    return made_of_types()[0]->latent_heat();
 }
 
 float item::get_freeze_point() const
 {
-    if( is_corpse() ) {
-        return made_of_types()[0]->freeze_point();
+    if( is_comestible() ) {
+        return get_comestible()->freeze_point;
     }
-    // If it is not a corpse it is a food
-    return get_comestible()->freeze_point;
+    return made_of_types()[0]->freeze_point();
 }
 
 template<typename Item>
```
