### ISSUE TITLE
Stone hammer requirements too restrictive

### ISSUE THREAD

**Issue by FeelsBadMatey** [CleverRaven/Cataclysm-DDA#43104]
# Is your feature request related to a problem? Please describe.
Stated item require disproportionate amount of survival (4) to craft.

# Describe the solution you'd like
For the requirements to be lowered below 4.

# Describe alternatives you've considered
Leaving it be.

# Additional context
Stone hammers and makeshift hammers are the same principle (and the recipe is a tad ridiculous for such a simple item).

**Comment by wapcaplet** [comment]
Confirmed in 0.E-6177-g 9f4a1b841d.

The 3-hour crafting time is a bit excessive too:

![image](https://user-images.githubusercontent.com/238395/94096137-9145e500-fde0-11ea-986a-82e8fc201d9d.png)

**Comment by NetSysFire** [comment]
This was addressed in #53564.
