### ISSUE TITLE
The Bicycles engine fails to start.

### ISSUE THREAD

**Issue by ZaricaDemoni** [CleverRaven/Cataclysm-DDA#43119]
# Describe the bug
Being told the engine fails to start on my bicycle with a damaged pedal.

# Steps To Reproduce
1. Find a bicycle with damaged pedals (not fualty)
2. attempt to use bicycle until it decided to fail an engine start.
3. Question how a non-faulty part is causing an issue, and why it says engine for bicycle pedals.

# Expected behavior
Only having start failure on faulty parts?

# Screenshots
![image](https://user-images.githubusercontent.com/32645137/90950814-16b52e80-e40a-11ea-96ab-6c5f4ad69f03.png)
![image](https://user-images.githubusercontent.com/32645137/90950923-f043c300-e40a-11ea-930a-4c259b69a483.png)

# Versions and configuration

 - OS: Windows 8.1
 - Game Version: 0.E-5283-ga1a0bf0
 - Graphics version: Tiles
 - Ingame language: Egnlish
 - Mods loaded: "dda", "no_npc_food", "blazeindustries", "crt_expansion", "magiclysm", "DinoMod", alt_map_key", "MMA", "cbm_slots", "fuji_mpp", "speedydex", "stats_through_kills", "StatsThroughSkills"

# Additional context
While I can understand the gear refusing to turn sometimes, its strange to get that message from a damaged, yet not faulty pedal on a bicycle.

**Comment by wapcaplet** [comment]
Still reproducible in 0.E-7073-g8d4cd2f280

**Comment by lancewf** [comment]
I can still reproduce this on commit 7bd98499abf2374a37e4fd32036f91b1f3c67a0d. I think I found the problem in the below code. `fuel_type_muscle` fuel type should to added to the not allow list like the `fuel_type_battery` fuel type. 
https://github.com/CleverRaven/Cataclysm-DDA/blob/3446d6cf8a65477e23a371d3f76ee1f41b449deb/src/vehicle_use.cpp#L1056-L1061
I will try to create some tests with the fix.
