### ISSUE TITLE
Food in medium tin cans becomes rotten

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#43110]
# Describe the bug

Well, exactly what it says on the tin.

# Steps To Reproduce

Spawn a tin can of pork and beans and wait for several days? It spoils even in the fridge so I doubt you'd have to wait for too long...

# Expected behavior

It should not spoil.

# Versions and configuration

- OS: Windows 7
- Game Version: 0.E-5282-gc2e5682 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

I know it spoiled in either current or my previous (build 10931) version because I cleared out the fridge right before that. So, if it was fixed in between, okay. But I didn't see anything in changelog directly mentioning food spoilage.

e: oh wait. seems like the old bug is back. When I try to pick it up it says I can either wield it or spill its contents. So it doesn't count as sealed for some reason?

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/all-tin-cans-operating-like-open-containers/24960/2

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-10973.
