### ISSUE TITLE
Provide feedback when zone sorting is ignored due to crowded tiles

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#43126]
# Is your feature request related to a problem? Please describe.
Borderline issue between bug and feature.

I've had problems with zone sorting as both the NPC and the PC claim to have sorted everything even though there's stuff left to sort. Eventually I used a debugger to figure out why, and it appears that tiles have both an item count limit (4096 item stacks) and a volume limit (don't know the value), and apparently the spare parts junk I'd hauled back over 3 months clashed with the latter limit.

# Describe the solution you'd like
Primarily, remove the volume limit for open tiles. It just causes frustration, making it harder to find things (which tile could the thing I'm after happen to be in), with limited play benefit (note that I'm not talking about vehicle storage: weight/volume restrictions make sense there).
Secondarily, provide a feedback that items couldn't be moved to zone X because the tile is full. That's needed for vehicles even if open tiles have their limits lifted (I don't know if there is a feedback for vehicles, though, as I've used zones only for unloading).
I'd prefer to see messages that zone X, Y, and Z are full, but building on the current functionality a message for each stack replacing the current movement message with "Foo couldn't be moved because zone Bar is full" (repeated times 200 for rags...) would be acceptable, although I'd prefer a warning/error color indication for the failure messages.

# Describe alternatives you've considered
The alternative I can think of is in the previous section.

# Additional context
While it's convenient to have things teleported, it makes more sense to have the character performing the job actually do that, i.e. fill up inventories and hands and walk with the stuff to the destination to drop them, while dragging heavy items. That's really a separate issue, though and requires some logic to get the characters do do that in a somewhat intelligent manner (sorting the items based on destination so things that go to the same location are transported together, with spare inventory used to move things to a neighboring pile).

Similarly, it comes as a rude surprise to find that half the day goes by as you just move your pile of various patches from one tile to another (manually in my cases, but the "drop one item at a time * million issue is the same for unstacked items regardless of whether it's manual or done as a part of a zone action). That's also a separate issue, however.

**Comment by PatrikLundell** [comment]
While DeltaEpsilon7787's comment didn't concern the suggestion as such, it still provided some useful info for a newbie such as myself.

**Comment by moll** [comment]
I've stumbled upon the same issue lately, as described in https://github.com/CleverRaven/Cataclysm-DDA/pull/54308#issuecomment-1036624992. I think this definitely needs to be better communicated as it's relatively easy to end up with over 4k items on a single tile, given tiny items like sheets, paper, sugar or salt.
