### ISSUE TITLE
Segfault when butchering corpses

### ISSUE THREAD

**Issue by MrWoot** [CleverRaven/Cataclysm-DDA#43125]
# Describe the bug

A repeatable segfault occurs when attempting to butcher a Young Black Dragon

# Steps To Reproduce

1. Load attached save
2. Attempt to butcher Dragon (directly underneath player)
3. Segfault occurs

# Expected behavior

A segfault should not occur.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-5302-g140d023 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Mining Mod [Mining_Mod],
    Mythical Martial Arts [MMA]
]

# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5112299/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5112300/debug.log)
Link to save:
https://drive.google.com/file/d/1KNBeEq5vffGMgBqVe9Yh6aosw42WyzWw/view?usp=sharing

**Comment by NoahGoldFox** [comment]
I had this happen to me when i tried butchering a sheep, and it also like corrupted my save too! the save wont load anymore
