### ISSUE TITLE
Solar Sensitivity deals damage to all limbs despite 100% coverage.

### ISSUE THREAD

**Issue by Bulletfang** [CleverRaven/Cataclysm-DDA#43133]
# Describe the bug
The mutation Solar Sensitivity, and some of its connected mutations, Light Sensitive, Very Light Sensitive and Troglobite, do not seem to take clothing coverage into account, resulting in Solar Sensitivity dealing damage to all limbs and the lesser versions of it applying negative effects to stats and pain.

# Steps To Reproduce

1. Get Solar Sensitivity mutation.
2. Equip Thermal Electric Outift (convenient 100% coverage on all bodyparts except eyes), equip sunglasses. (Alternatives: ANBC Suit or Zentai)
3. Step into the sun and witness the damage received.

# Expected behavior

Clothing coverage is taken into account, just like with the Albino trait. If the sun doesn't reach the skin, it can't deal damage.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-4920-g6a34646 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context

The sun, it burns. _Hissss!_

**Comment by wapcaplet** [comment]
Based on a quick glance at the code, you are right - the "Solar Sensitivity" suffering code simply does `hurtall` unless the avatar has an umbrella:

https://github.com/CleverRaven/Cataclysm-DDA/blob/678cab457a3713bd9e03e730366c01f12b64e0ee/src/suffer.cpp#L763-L770

I had a character with this trait recently, and can confirm that a simple umbrella is enough to prevent all injury with this mutation. The TROGLO/2/3 mutations are handled in the same section, also in a simple way that does not check body part coverage.

On the other hand the `suffer_from_albinism` function does a complete coverage calculation for all body parts. This calculation should be factored out so it can be used for the other sun-sensitivity mutations as well.

I will work on this.
