### ISSUE TITLE
Crafting doesn't deplete focus

### ISSUE THREAD

**Issue by Duck13Tales** [CleverRaven/Cataclysm-DDA#43147]
# Describe the bug

When you craft anything to increase your skills your focus isn't decreased.

# Steps To Reproduce

1 - Craft anything
2 - Notice that though you are getting skill points/levels you focus isn't decreasing

# Expected behavior

When you learn anything your focus should decrease unless the related skills are "disabled to learn". Unless it is an intended recent change.

# Screenshots

Not needed.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-5302-g140d023 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

# Additional context

Unless it was a recent change, everything that improve your skills should decrease your focus.

**Comment by Duck13Tales** [comment]
I am reopening this anyway to ask because when we learn from books it depletes way more our focus than most crafts, specially longer and "big batch" ones. So I would like to ask if it is working as intended and if it is balanced, because this shouldn't use as much focus as reading from a book?

Thanks anyway!

**Comment by anothersimulacrum** [comment]
This is because crafting practices skill a total of 20 times, and reading many more, and the focus loss is based on how many times you practice skill, not how much.

**Comment by Duck13Tales** [comment]
Thank you!

**Comment by anothersimulacrum** [comment]
That wasn't saying this is an invalid issue, I think that definitely could use looking at, that's just how it works.
