### ISSUE TITLE
Can't dig downstair

### ISSUE THREAD

**Issue by Duck13Tales** [CleverRaven/Cataclysm-DDA#43146]
# Describe the bug

I am inside a house which has a basement and I am trying to dig or mine downstair. Though I have all the requirements I can't dig no matter what. Even if I choose the option and then a place I still can't dig downstair.

And I can't mine downstair either because there isn't a "rock floor" which is needed for it. 

Edit: I noticed that if I break a nearby wall and the ground become "dirt" then I can dig. If it is a "floor" I can't but most houses have "floor".

# Steps To Reproduce

1 - get all the required components to a house which have a basement
2 - Try to dig downstair and notice that though you have everything needed the option still is grayed out
3 - Choose the option anyway and be prompted to choose "where", then choose and notice that you receive the notice that "you cannot build there!"

# Expected behavior

Once you have everything needed you should be able to dig downstair.

# Screenshots

![dig downstair](https://user-images.githubusercontent.com/67176313/90976228-90840f80-e511-11ea-8b64-16713b0efd08.png)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-5302-g140d023 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

# Additional context

None.

**Comment by eilaattwood** [comment]
That's because to DIG downstaris you need to have a tile with dirt floor, and to MINE downstairs you explicitly need rock floor. No other floor types will actually meet a requirement.

**Comment by anothersimulacrum** [comment]
That should be communicated.

**Comment by eilaattwood** [comment]
Also, offtop for this PR, but also about building requirements: I find it extremely frustrating that you can't build concrete walls and other structures that require a pit, because you can't dig a pit in the stone underground.

**Comment by Duck13Tales** [comment]
But then how can we create a basement in an existing house or anywhere else which doesn't has a dirt or stone floor?

**Comment by Zireael07** [comment]
@Duck13Tales: I believe you can't do that in CDDA. Consider that creating a modern basement IRL is a huge undertaking - I find it exceedingly unlikely that a survivor would be able to create a basement.

A root cellar, on the other hand, should already be a construction option.

**Comment by Duck13Tales** [comment]
At first it would seem right @Zireael07 but in CDDA right now this makes no sense... Our survivors already can make concrete walls without much problem, even reinforced concrete buildings without much trouble, so creating a basement off concrete walls shouldn't pose much of a challenge since we can already build concrete walls and dig through stone.

Anyway I can smash a wall and then it's tile will become "dirt" and then I can dig down without problem, or I can build a wall or something and smash it and it will become a "dirt" tile too, or I can even start digging from outside the house in any "dirt" tile and the survivor can create it's own basement, so in the end there is no reason other than pure bureaucracy that our survivors can't dig "floors" but can dig "dirt" or "stone floor"...
