### ISSUE TITLE
Steel rail ammo density is too high.

### ISSUE THREAD

**Issue by TheMasterGear** [CleverRaven/Cataclysm-DDA#43156]
While checking steel density I found that the material density fluctuated hugely depending on the item. The rail is one of the worst having a g/cm3 of 80!

# Steps To Reproduce

1. Look at a steel rails weight and liters volume
2. 1 liter = 1000 cm3, so 1600 cm3/ 20 cm3= 80 g/cm3

# Expected behavior

Density similar too [steel](https://amesweb.info/Materials/Density_of_Steel.aspx)

# Screenshots

![steel rail](https://user-images.githubusercontent.com/60374171/90986376-73226600-e550-11ea-8f22-9872f6a036bc.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-5001-gec1deea [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by Alex-Folts** [comment]
> I found that the material density fluctuated hugely depending on the item.

Just to make it clear.
You probably confused volume of complex shape object and volume of material this object made.
Volume here mostly used for inventory system, to make sure object will fit and how many objects will fit.
Ofc if density of steel object is higher than density of steel itself - it would be bug, but not always lower density is a bug. Less density usually is fine unless you have solid cube/cubiod.
While your changes seems fine in this case, keep in mind that this ultra precise mass to volume ratios not always hold for real objects.

**Comment by TheMasterGear** [comment]
> 
> 
> > I found that the material density fluctuated hugely depending on the item.
> 
> Just to make it clear.
> You probably confused volume of complex shape object and volume of material this object made.
> Volume here mostly used for inventory system, to make sure object will fit and how many objects will fit.
> Ofc if density of steel object is higher than density of steel itself - it would be bug, but not always lower density is a bug. Less density usually is fine unless you have solid cube/cubiod.
> While your changes seems fine in this case, keep in mind that this ultra precise mass to volume ratios not always hold for real objects.

Yeah, that's why I think it'll only work with an object that is only one material and is compacted in shape. Arrow and other ammo will have to be done differently, which what we'll need to find out one day.
