### ISSUE TITLE
battle axe

### ISSUE THREAD

**Issue by CHJKDM51** [CleverRaven/Cataclysm-DDA#43179]
# Describe the bug
battle axe dmg type is bash.

# Steps To Reproduce

# Expected behavior
Expected to be cut or pierce.

# Screenshots

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-5336-gd3cb7ff [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

**Comment by ZhilkinSerg** [comment]
Make sure you are checking correct battle axe - there are three of them and one is cheap dull replica which bashes, but not cuts.

**Comment by CHJKDM51** [comment]
![pp](https://user-images.githubusercontent.com/58046029/91055967-067d9900-e62e-11ea-88b2-d51c8033b173.png)

**Comment by Zireael07** [comment]
"Budget steel" and "axe heads aren't seated properly" should be fairly big hints. You're indeed looking at the cheap replica item, as @ZhilkinSerg says.

**Comment by CHJKDM51** [comment]
> "Budget steel" and "axe heads aren't seated properly" should be fairly big hints. You're indeed looking at the cheap replica item, as @ZhilkinSerg says.

No. It is not.
http://cdda.chezzo.com/battleaxe_inferior
http://cdda.chezzo.com/battleaxe_fake

**Comment by CHJKDM51** [comment]
Wrong again: Its not a "fake" one its "inferior" version. It's made of "Budget Steel" and have a sharp edge thus must have cutting dmg, even if it would be lower that "real" version of battleaxe.

**Comment by ZhilkinSerg** [comment]
So, what your concern is exactly? That inferior axe has 10 cutting damage (e.g. same as butcher knife) and 38 bashing damage (compared to 19 and 38 on regular battle axe). Inferior axe is not honed, but it is still heavy, so damage is lower a little and shifted to bashing, but still cuts.

**Comment by CHJKDM51** [comment]
It have tree cutting ability so I imagined it as a cheap sharp axe. Guess "not honed" part should be added to description then.
