### ISSUE TITLE
Bad design (mansion)

### ISSUE THREAD

**Issue by CHJKDM51** [CleverRaven/Cataclysm-DDA#43178]
# Describe the bug
Some rooms in mansion 2nd floor can be accessed only through windows.

# Steps To Reproduce

# Expected behavior
Expected to have valid architecture and access via doors.

# Screenshots

![bad_design](https://user-images.githubusercontent.com/58046029/91042630-b9dc9280-e61a-11ea-81b1-05ac82d98ac4.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-5336-gd3cb7ff [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

**Comment by ZhilkinSerg** [comment]
Mansions consist of chunks and can make impassible combinations. Someone needs to add code to random selection of chunks in mansion specials (right now there are just several predefined mansions) and as a hotfix we need to find that botched predefined layout and fix it manually.

**Comment by MasterLiKhao** [comment]
This reddit post is related, seems there are more than just one botched predefined layout: https://www.reddit.com/r/cataclysmdda/comments/icbhfz/questionable_architectural_decisions_in_this/

**Comment by Night-Pryanik** [comment]
Fixed by #44197.
