### ISSUE TITLE
(PC-Android) "Contact us" in the evac shelter computer menu spawns error

### ISSUE THREAD

**Issue by kapacek** [CleverRaven/Cataclysm-DDA#43175]
# Describe the bug

An error message appears after a while of waiting when using the terminal. Reproducible in PC and on Android

# Steps To Reproduce

1. Load a game with a save provided
2. Ride towards the Evac Shelter to the South
3. Enter a building (for some reason door state isn't the same each time, sometimes 1 of the doors is damaged, sometimes both, sometimes both are okay, but that's not the case now).
4. Use evac shelter terminal (sometimes it is saying that "there is nothing to display and just won't work). 
5. On a successfully opened terminal choose "Contact Us"
6. Wait 

# Expected behavior

I expect it not to show the error message. After closing it it shows regular terminal message about camp coordinates and such
So I'm not sure that my savefile integrity is OKAY at all thus idk whether to continue playing with this particular save

# Screenshots

This bug is reproducible in both android and PC
* (ANDROID) https://www.youtube.com/watch?v=55ckT0P2bUI

* (PC) https://www.youtube.com/watch?v=jiIIZoYSE3Q

# Versions and configuration

***ANDROID***
- OS: Android
    - OS Version: Manufacturer: HUAWEI; Model: YAL-L21; Release: 10; Incremental: 10.1.0.231C10; 
- Game Version: 0.E-2 [64-bit]
- Graphics Version: Tiles
- Game Language: Русский [ru]
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у NPC [no_npc_food],
    Альтернативные символы карты [alt_map_key],
    Темные Дни Мертвых [classic_zombies],
    Характеристики за навыки [StatsThroughSkills]
]

***PC***
- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: openSUSE; Description: openSUSE Leap 15.1; Release: 15.1; Codename: n/a; 
- Game Version: 0.E-2 [64-bit]
- Graphics Version: Tiles
- Game Language: Системный язык []
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у NPC [no_npc_food],
    Альтернативные символы карты [alt_map_key],
    Темные Дни Мертвых [classic_zombies],
    Характеристики за навыки [StatsThroughSkills]
]

# Additional context
***The error message***
DEBUG    : Unable to find and assign mission target refctr_S3e.

 FUNCTION : cata::optional<tripoint> find_or_create_om_terrain(const tripoint &, const mission_target_params &)
 FILE     : /var/lib/jenkins/workspace/Cataclysm-Android/android/app/jni/src/mission_util.cpp
 LINE     : 240

I will add a save file anyway for this matter
VVVVVVVV
[Нигде.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5116681/default.zip)
^^^^^^^^^^^

**Comment by Fris0uman** [comment]
Damn customer service, alwasy down at the worst time! ><

**Comment by ZhilkinSerg** [comment]
Related to #43457

**Comment by wapcaplet** [comment]
Confirmed in 0.E-6177-g 9f4a1b841d with the save game attached to the original report.

**Comment by kapacek** [comment]
I noticed i never had this error pop up when generating a world WITHOUT classic zombies. It says it doesn't use some structures when enabled. Could be that?

**Comment by anothersimulacrum** [comment]
Yes, classic zombies prevents the refugee center from spawning, meaning the computer fails to locate it.

**Comment by Night-Pryanik** [comment]
Can't confirm on latest experimental as of 23 November 2024. Tested with `Dark Days of the Dead` mod. Choosing "Contact us" in evac shelter computer doesn't gives an error. The text `REFUGEE CENTER FOUND!` should/must be changed for this mod, since refugee center didn't actually spawn, but this is another issue.

**Comment by NetSysFire** [comment]
I think this happened because the refugee center was not guaranteed to spawn in the next couple of overmaps. Now it pretty much is.
