### ISSUE TITLE
Game crashes when trying to Butcher

### ISSUE THREAD

**Issue by insidio118** [CleverRaven/Cataclysm-DDA#43185]
Game crashes when trying to Butcher. This happened when I tried to butcher a moose, then I tried to butcher a wild boar and the same thing happened. And continiously happen when i try to shift+b on a boar/moose corpse. Constant and instant crash.

I’m playing on a Windows 10 x64 latest experimental. (10946 build). No mods.

Steps To Reproduce: find a random wild boar or moose, kill it and try to butcher.

Expected behavior:

There should be no crashes when you try to butcher.

`Here is the crash log:

The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 0.E-5332-g39272e1
TYPE: St12out_of_range
MESSAGE: map::at
STACK TRACE:

#0
(dbghelp: @ 0x59a29b[cataclysm-tiles.exe+0x19a29b]),
(libbacktrace: _Z21debug_write_backtraceRSo+0xd9@0x59a29b),
(libbacktrace: 0x59a29b [unknown src]:0 [unknown func]),
#1
(dbghelp: @0x5874ad[cataclysm-tiles.exe+0x1874ad]),
(libbacktrace: log_crash+0x2d7@0x5874ad),
(libbacktrace: 0x5874ad [unknown src]:0 [unknown func]),
#2
(dbghelp: @ 0x58776d[cataclysm-tiles.exe+0x18776d]),
(libbacktrace: _ZL23crash_terminate_handlerv+0x101@0x58776d),
(libbacktrace: 0x58776d [unknown src]:0 [unknown func]),
#3
(dbghelp: IMG_LoadWEBP_RW+0x18a5a0@0xfb2110[cataclysm-tiles.exe+0xbb2110]),
(libbacktrace: _ZN10__cxxabiv111__terminateEPFvvE+0x40@0xfb2110),
(libbacktrace: 0xfb2110 [unknown src]:0 [unknown func]),
#4
(dbghelp: IMG_LoadWEBP_RW+0x3bf511@0x11e7081[cataclysm-tiles.exe+0xde7081]),
(libbacktrace: ZNKSt3mapI13creature_sizeS_I12butcher_type9string_idI16requirement_dataESt4lessIS1_ESaISt4pairIKS1_S4_EEES5_IS0_ESaIS7_IKS0_SB_EEE2atERSD+0x45@0x11e7081),
(libbacktrace: 0x11e7081 [unknown src]:0 [unknown func]),
#5
(dbghelp: @ 0x4be7f0[cataclysm-tiles.exe+0xbe7f0]),
(libbacktrace: _ZNK21butchery_requirements24get_fastest_requirementsERK9inventory13creature_size12butcher_type+0x142@0x4be7f0),
(libbacktrace: 0x4be7f0 [unknown src]:0 [unknown func]),
#6
(dbghelp: @0x61db1a[cataclysm-tiles.exe+0x21db1a]),
(libbacktrace: ZZL15butcher_submenuRKSt6vectorIN4cata6colonyI4itemSaIS2_EtE15colony_iteratorILb0EEESaIS6_EEiENKUl12butcher_typeE_clESB+0x8e@0x61db1a),
(libbacktrace: 0x61db1a [unknown src]:0 [unknown func]),
#7
(dbghelp: @ 0x63d5a7[cataclysm-tiles.exe+0x23d5a7]),
(libbacktrace: _ZL15butcher_submenuRKSt6vectorIN4cata6colonyI4itemSaIS2_EtE15colony_iteratorILb0EEESaIS6_EEi+0x5c4@0x63d5a7),
(libbacktrace: 0x63d5a7 [unknown src]:0 [unknown func]),
#8
(dbghelp: @ 0x65eb0b[cataclysm-tiles.exe+0x25eb0b]),
(libbacktrace: _ZN4game7butcherEv+0x13df@0x65eb0b),
(libbacktrace: 0x65eb0b [unknown src]:0 [unknown func]),
#9
(dbghelp: @ 0x69282c[cataclysm-tiles.exe+0x29282c]),
(libbacktrace: _ZN4game13handle_actionEv+0x46fe@0x69282c),
(libbacktrace: 0x69282c [unknown src]:0 [unknown func]),
#10
(dbghelp: @ 0x65306c[cataclysm-tiles.exe+0x25306c]),
(libbacktrace: _ZN4game7do_turnEv+0x714@0x65306c),
(libbacktrace: 0x65306c [unknown src]:0 [unknown func]),
#11
(dbghelp: IMG_LoadWEBP_RW+0x6a7a19@0x14cf589[cataclysm-tiles.exe+0x10cf589]),
(libbacktrace: main+0x19fa@0x14cf589),
(libbacktrace: 0x14cf589 [unknown src]:0 [unknown func]),
#12
(dbghelp: @ 0x4013e2[cataclysm-tiles.exe+0x13e2]),
(libbacktrace: _tmainCRTStartup+0x272@0x4013e2),
(libbacktrace: 0x4013e2 /home/narc/src/mxe/tmp-gcc-i686-w64-mingw32.static/gcc-5.4.0.build/mingw-w64-v5.0.2/mingw-w64-crt/crt/crtexe.c:336 __tmainCRTStartup),
#13
(dbghelp: BaseThreadInitThunk+0x19@0x759a6359[KERNEL32.DLL+0x16359]),
(backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
(backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
#14
(dbghelp: RtlGetAppContainerNamedObjectPath+0xe4@0x776b7c24[ntdll.dll+0x67c24]),
(backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
(backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
#15
(dbghelp: RtlGetAppContainerNamedObjectPath+0xb4@0x776b7bf4[ntdll.dll+0x67bf4]),
(backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
(backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),`

**Comment by DoctorVanGogh** [comment]
Duplicate of #43125

A fix is in and an appropriate build _should_ come out "soon"(TM).

**Comment by insidio118** [comment]
> Duplicate of #43125
> 
> A fix is in and an appropriate build _should_ come out "soon"(TM).

sry, didnt know what "segfault" means. Ty.
