### ISSUE TITLE
Is it possible to implement diagonal movements like in ADOM?

### ISSUE THREAD

**Issue by apollovy** [CleverRaven/Cataclysm-DDA#43181]
Game version:
0.E

Operating system:
MacOS Mojave 10.14.6 (18G4032), from Homebrew

Tiles or curses:
Curses

Mods active:
Defaults (DDA, Disable NPC Needs)

### Expected behavior
In ADOM pressing both "up" + "left" makes character make diagonal movement. Is it possible (without lots of changes) to implement it? AFAICS there are switch cases for `keysym.sym` (like [here](https://github.com/ZhilkinSerg/Cataclysm-DDA/blob/master/src/sdltiles.cpp#L1187), so I suppose the worse, but maybe I'm wrong, because I'm not a C++ guru at all.

### Actual behavior
Varies from DIAG_MOVE_WITH_MODIFIERS_MODE  setting

### Steps to reproduce the behavior
Try to press both arrows simultaneously — get 2 moves, instead of 1 diagonal.

Thank you.

**Comment by Zireael07** [comment]
I do not think our backends support this?

**Comment by gcaliber** [comment]
I'd think you would have to modify the key event system to parse a queue of key presses and not one at a time in order for this to work. The current system just uses SDL key events IIRC.

**Comment by Qrox** [comment]
SDL already sends key down / up events so all we have to do is to keep a list of currently pressed keys and return a multi-key event. `input_event` itself already supports storing multiple key presses (but was never actually implemented). Curses on the other hand probably cannot support it because we can only get text input there.

**Comment by DeltaEpsilon7787** [comment]
Is a third way of moving diagonally necessary? Numpad works.

**Comment by Qrox** [comment]
There are keyboards without a keypad.

**Comment by apollovy** [comment]
Frankly there's no necessity in this, just a question about how easy/hard it would be to implement, and if not very hard, I'd try to do it myself. Just to ease the adoption of ADOM'ers like me.
It appears that in a couple of days I'm already pretty comfortable with the options already there, so this question might be closed, especially if it's not so trivial to implement :)
