### ISSUE TITLE
Fix too tight timeouts on Jenkins build bot

### ISSUE THREAD

**Issue by DoctorVanGogh** [CleverRaven/Cataclysm-DDA#43184]
# Build system issue:

Currently the Jenkins build bot at https://ci.narc.ro has a 10 minute timeout for fetching from the master repo.
It seems there are situations where fetching the repo takes **significantly** longer.

# Steps To Reproduce

Check https://ci.narc.ro/job/Cataclysm-Matrix/10947/console - excerpt:

```
...
16:58:08  > /usr/bin/git fetch --tags --progress git://github.com/CleverRaven/Cataclysm-DDA.git ${REPO_REFSPEC} # timeout=10
17:08:08 ERROR: Timeout after 10 minutes
...
17:08:08 remote: Counting objects:   2% (1/42)        
...
Receiving objects:  26% (135755/515124), 407.46 MiB | 721.00 KiB/s   
Receiving objects:  26% (135755/515124), 408.41 MiB | 781.00 KiB/s   
error: index-pack died of signal 15

...

17:08:08 ERROR: Error cloning remote repo 'origin'
17:08:08 Retrying after 10 seconds
...
17:08:18  > /usr/bin/git fetch --tags --progress --prune git://github.com/CleverRaven/Cataclysm-DDA.git +refs/heads/master:refs/remotes/origin/master # timeout=10
17:18:18 ERROR: Timeout after 10 minutes
...
17:18:18 remote: Counting objects:   2% (1/42)
...
Receiving objects:  24% (126424/515124), 323.70 MiB | 536.00 KiB/s   
Receiving objects:  24% (126614/515124), 324.14 MiB | 523.00 KiB/s   
error: index-pack died of signal 15

...
```
Currently there are multiple further partial and aborted `fetch` attempts in that log - I think the job is on it's _sixth_ aborted attempt at the time I'm writing this issue.

# Expectations:

Timeout should *not* be set at 10 minutes.

Some ballpark back of the head calculations put the *current* repo history size at 1.2GB (ish). To transfer that fully within 10 minutes necessitates an average transfer speed **above** 2MB/s. *That is clearly not guaranteed*.

# Suggestions:

Loosen timeout significantly.

While 10 minutes may have been fine when the repo was smaller, the current size clearly can cause issues here. And the repo will only ever get bigger.

---
Alternatively: Dont grab a full history, just pull an appropriate snapshot.

**Comment by DoctorVanGogh** [comment]
# Addition

Yeah, just checked... a simple `wget https://github.com/CleverRaven/Cataclysm-DDA/archive/563026348d9ae2d51c9c8a9fafee01be129e865f.zip` (the build jobs associated commit) will put a measly 75 MB over the wire, not try to grab 1.2 GB.

Unless there is a compelling reason why the build bot *needs* the whole history... I'd advocate for the snapshots.

**Comment by Zireael07** [comment]
I don't think the bot needs the whole history, a `git clone --depth=1` should just pull the most recent commit (why is the build bot using git fetch over git clone?)

**Comment by ZhilkinSerg** [comment]
It needs history for changelog probably.

**Comment by DoctorVanGogh** [comment]
> It needs history for changelog probably.

https://api.github.com/repos/CleverRaven/Cataclysm-DDA/commits?per_page=100

![image](https://user-images.githubusercontent.com/324067/91088278-08595380-e652-11ea-8769-35803f89a8cf.png)
