### ISSUE TITLE
The cephalopod mutations Shell and Roomy Shell do not provide any storage space.

### ISSUE THREAD

**Issue by sleepingdreams** [CleverRaven/Cataclysm-DDA#43192]
# Describe the bug
Shell and Roomy Shell do not provide the 16Ls of storage space that the description implies.
# Steps To Reproduce
Use Shower Victim profession
Open the debug menu and get the Shell mutation
Check your available storage space.
Open debug again, get the Cephalopod threshold and Roomy Shell mutation.
Check your available storage space.
# Expected behavior
I expect the shell to give you the 16Ls of storage space that the description says it would.
# Screenshots
![Screenshot (128)](https://user-images.githubusercontent.com/70165847/91081347-fad1a880-e614-11ea-9409-6a40a8c86ada.png)
# Versions and configuration
 - OS: Windows 10
 - Game Version: 0.E-5331-g678cab4
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: dda, No NPC Needs.

# Additional context
N/A

**Comment by Zireael07** [comment]
Probably was lost in the move to pocket inventory? @KorGgenT @wapcaplet

**Comment by wapcaplet** [comment]
Yes, the `SHELL` and `SHELL2` storage modifiers were removed in nested containers commit 09ee4e1b.

**Comment by anothersimulacrum** [comment]
The descriptions should be modified.

**Comment by Mysteriou85** [comment]
Do you think I should try put back the storage, or it's not required ?
