### ISSUE TITLE
Change Max Trait Points to not limit choosing more negative trait

### ISSUE THREAD

**Issue by WhelpCub** [CleverRaven/Cataclysm-DDA#43190]
# Is your feature request related to a problem? Please describe.
There is a option of max trait points, default is 12. The limitation is for prevent create a too strong start character.
However for roleplay reason, or for challenge, I may want to choose more negative trait but not for more points.

# Describe the solution you'd like
No limitation on choosing negative trait, but limit on how many points you can get from negative trait.
If the max trait points is set on 12, even you choose lots of negative trait to get -99 points, the result will still be -12 points.

**Comment by Fris0uman** [comment]
Play freeform mode, this is not a real issue.

**Comment by Zireael07** [comment]
I think that's what freeform mode is for?

EDIT: Ninja'd.
