### ISSUE TITLE
When searching the debug spawn item menu, j/k move up and down

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#43201]
# Describe the bug

When using the debug: spawn item menu, and searching for an item, the letters `j` and `k` move the cursor up and down, instead of being entered as part of the item name.

# Steps To Reproduce

1. Open the debug menu
2. `s`pawn, `w` to spawn item
3. Search with `/` for "backpack" - `bacpac` entered
4. Search for `jack` - `ac` entered

# Expected behavior

The letters `j` and `k` should be entered like any other letter here, not used for cursor movement.

# Screenshots

Searching for "bottle jack":

![image](https://user-images.githubusercontent.com/238395/91115158-d393cf00-e646-11ea-9224-b511b7b79225.png)

For "backpack":

![image](https://user-images.githubusercontent.com/238395/91115236-0342d700-e647-11ea-9276-543f05c03076.png)

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-5357-g7e30783ef1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

**Comment by Qrox** [comment]
Probably caused by my recent change to make debug menus use input actions instead of input events. I'll look into it.
