### ISSUE TITLE
Butchery without tool (or with pistol bayonet) cause game crash

### ISSUE THREAD

**Issue by WhelpCub** [CleverRaven/Cataclysm-DDA#43202]
# Describe the bug

While butchering (B) without any butchering tool, or pistol bayonet, will cause the game crash.

# Steps To Reproduce

1. Kill a zombie
2. Be sure do not carry any butchering tool
3. Butchering (B) the zombie, game will crash
4. Try again, but this time with pistol bayonet in your bag

# Expected behavior

Cannot butchering without butchering tool.
Can butchering with pistol bayonet.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-5336-gd3cb7ff [32-bit]
 - Graphics version: Tiles
 - Ingame language: Chinese (Traditional)
 - Mods loaded: [
Dark Days Ahead [dda]
]

# Additional context

> The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 0.E-5336-gd3cb7ff
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
>
>  #0
    (dbghelp: @0x59a29b[cataclysm-tiles.exe+0x19a29b]), 
    (libbacktrace: _Z21debug_write_backtraceRSo+0xd9@0x59a29b),
    (libbacktrace: 0x59a29b    [unknown src]:0    [unknown func]),
  #1
    (dbghelp: @0x5874ad[cataclysm-tiles.exe+0x1874ad]), 
    (libbacktrace: log_crash+0x2d7@0x5874ad),
    (libbacktrace: 0x5874ad    [unknown src]:0    [unknown func]),
  #2
    (dbghelp: @0x58780f[cataclysm-tiles.exe+0x18780f]), 
    (libbacktrace: signal_handler+0x52@0x58780f),
    (libbacktrace: 0x58780f    [unknown src]:0    [unknown func]),
  #3
    (dbghelp: SMPEG_error+0x3daf3@0xd4dc55[cataclysm-tiles.exe+0x94dc55]), 
    (libbacktrace: _gnu_exception_handler@4+0x55@0xd4dc55),
    (libbacktrace: 0xd4dc55    /home/narc/src/mxe/tmp-gcc-i686-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crt_handler.c:223    _gnu_exception_handler@4),
  #4
    (dbghelp: UnhandledExceptionFilter+0x192@0x766fda22[KERNELBASE.dll+0x1bda22]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #5
    (dbghelp: RtlCaptureStackContext+0x1d7b5@0x77234d15[ntdll.dll+0xa4d15]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #6
    (dbghelp: RtlGetAppContainerNamedObjectPath+0xb4@0x771f7474[ntdll.dll+0x67474]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),

**Comment by anothersimulacrum** [comment]
Cannot reproduce.

**Comment by WhelpCub** [comment]
[Testing World.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5121417/Testing.World.zip)

It seems cannot be naked to trigger the crash, maybe the problem is cause from other items?

**Comment by anothersimulacrum** [comment]
I cannot select any of the butchery options to start butchery, I lack the requirements.
I've tried in both Chinese variants and English, in case language happened to be an issue.

**Comment by WhelpCub** [comment]
I try to reproduce from a clean build #10946, game is still crash.
This is the save from it.
[save_file.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5121472/save_file.zip)

Also I try make a clear step to reproduce.
1. Create a world with only [dda] mod, keep all setting default, name the world "Testing World".
2. Create a character, scenarios "Wilderness", profession "Shower Victim", start location "Field".
3. Keybinding "Debug Menu" as backspace.
4. Debug Menu, Spawn monster "zombie".
5. Debug Menu, "Kill all monsters".
6. Move character to the same tile as the dead zombie.
7. Press "Butcher" button (Default key is "B"), select "zombie".
8. Game crash.

**Comment by DoctorVanGogh** [comment]
Very likely duplicate of #43125

Should be fixed from build 1094**9** onward.

**Comment by WhelpCub** [comment]
I have try this on build 10950, game do not crash.
Seems this problem have been solved.

**Comment by anothersimulacrum** [comment]
Aagh, I did not notice that. The commit fixing the crash when butchering a corpse is before the commit from this version, but the merge commit is after, so I thought you were on a version with the fix.
