### ISSUE TITLE
[QoL] Autonomous Surgical Scalpels should count for butchering value even when inactive

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#43211]
# Is your feature request related to a problem? Please describe.
Try making glazed tenderloin with ASS inactive, see you don't have 20 butchery. Activate it, see you now have it. 

# Describe the solution you'd like
As ASS don't have activation cost it should be silently assumed "always" working for butchery-related tasks. Just a minor QoL, but each little bit helps, right?

# Describe alternatives you've considered
Continue manually activating and deactivating it each time I want to make some food or dissect a corpse.

**Comment by Fris0uman** [comment]
Great acronym! 
So you're saying that ASS has 20 butchery quality? That sounds like a bug, I don't think a set of dissection/surgery tools would be too good for actual butchery.

**Comment by GGgatherer** [comment]
They have 50 :) 20 is requirement for glazed tenderloin.
