### ISSUE TITLE
Some Magazines Are Too Large for Leg Ammo Pouches

### ISSUE THREAD

**Issue by Shinino** [CleverRaven/Cataclysm-DDA#43226]
Not all magazines fit in leg ammo pouches.  This is due to the maximum length on the ammo pouch being set to the length of the ammo pouch, requiring the magazine to be smaller. 

# Steps To Reproduce

<!-- Steps to reproduce the behavior:
1. Have M1911 Magazine.
2. Have Leg Ammo Pouch
3. Enter Inventory
4. Cursor to the leg pouch and press 'i'
5. The M1911 magazine is not an available option to insert.

# Expected behavior

It is expected that magazines larger than the leg ammo pouch should fit, as per images on this website: https://tacticalgear.com/pistol-ammo-pouches

# Screenshots

https://cdn.discordapp.com/attachments/720777153959952434/747959640486182974/unknown.png
https://cdn.discordapp.com/attachments/720777153959952434/747962435998318693/unknown.png

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1709
- Game Version: 0.E-5334-gcafbb28 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm]

# Additional context
this is not how ammo pouches typically work.  Most ammo pouches have the top of the magazine sticking out for easy removal and insertion.  https://tacticalgear.com/pistol-ammo-pouches shows a number of options here.

**Comment by ScritchFox** [comment]
After extensively investigating this and testing this -- along with .json reviews, I'm pretty sure this is working 100% as intended.

The leg ammo pouch has two pockets, each of which can hold 500ml of volume weighing no more than 2kg. The length of these pockets is 4 inches.

I reviewed mags in the .json and in the debug menu -- and I was unable to find a single magazine that should fit in the leg ammo pouch, but did not fit.

All of the magazines that didn't fit were above .5L in volume, above 2kg in weight, or had the MAG_BULKY flag. The leg ammo pouch can only contain MAG_COMPACT and magazines without flags.

**Comment by Shinino** [comment]
I'm not saying it isn't working as intended.  I'm saying it's not working how leg ammo pouches actually do in reality.  They're not meant to entirely encapsulate the magazine, they're meant so the top of the magazine sticks out for easy removal/insertion.   The M1911 magazine is the specific one that caused me to do this.

**Comment by Shinino** [comment]
This basically just needed sanity checking IMO -- actual leg pouches aren't meant to be bigger than the magazines.  Increasing the max length allowed by a couple of inches would make sure that compact mags can fit (including the M1911, which is 5").

**Comment by kevingranade** [comment]
That depends, if you search "ammo pouch" on google images, the first hundred results or so are fully enclosed until you get to this: https://2v93qe3ibmc72n5db01ripp4-wpengine.netdna-ssl.com/wp-content/uploads/2019/08/Chase-Tactical-5_56-Open-Top-Mag-Pouch-Triple-MC-compressed.jpg which still wraps around the magazine, but isn't fully enclosed.

I haven't dug into the length extensively, so I don't have a strong opinion one way or the other, but 4" does seem rather short for this use case.

**Comment by ScritchFox** [comment]
> This basically just needed sanity checking IMO -- actual leg pouches aren't meant to be bigger than the magazines. Increasing the max length allowed by a couple of inches would make sure that compact mags can fit (including the M1911, which is 5").

From research; it seems that the specific drop pouch being modeled is this one:
https://www.amazon.com/Condor-Drop-Leg-Mag-Pouch/dp/B00865N60W

As you can guess, this should obviously hold more than 4 inches -- so you're dead right. What is surprising; is that most of our STANAG magazines are set to 2/3 inches -- real world magazines are 7 inches roughly for 30rd mags, which this drop pouch is rated to hold.

Sorry for not noticing that sooner! But in addition; this means a lot of our magazines are improperly sized -- with the M1911 mag being the only one particularly sized in an accurate manner. I'm going to go ahead and look over these things!

**Comment by Shinino** [comment]
I'll be quite happy to help here.

I was looking in the .json files for magazines and ... I couldn't find anything referencing length.  If I know where that is, I can absolutely fix this.

**Comment by skeolan** [comment]
Related: after firing up a new game (build 11044) with the Generic Guns mod enabled, the generic 30rd Rifle Magazine that's supposed to be getting loaded into the leg pouches instead throws an error.

Not sure if this counts as a separate bug; it sure seems like a different manifestation of the same problem.

Repro steps:
* Create a New World with the Generic Guns mod enabled
* Select New Game and Custom Character
* Freeform [tab] Evacuee [tab]
* Press Up arrow a few times to cycle quickly around to Bionic Soldier
* Error text:
```
 DEBUG    : tried to put an item (rifle_mag) count (1) in a container (legpouch_large) that cannot contain it: pockets unacceptable because item too big

 FUNCTION : ret_val<bool> item::put_in(const item&, item_pocket::pocket_type)
 FILE     : src/item.cpp
 LINE     : 1102
```
