### ISSUE TITLE
Dialog option for selecting a mission from a list always selects the last offered mission.

### ISSUE THREAD

**Issue by John-Candlebury** [CleverRaven/Cataclysm-DDA#43228]
# Describe the bug

When an NPC offers two missions, its impossible to select the first one, with the second mission being always selected.

# Steps To Reproduce

1. Complete the first intercom mission at HUB 01
2. lntercom offers two new missions, `Iron Safari` and Steal a `Dead mans Mind`.
3. `lron Safari` is always offeered no matter your imput.

# Expected behavior

Offer the mission you selected.

# Versions and configuration

Windows 10
Game Version 0.e 5366-g7f91078d14

**Comment by Fris0uman** [comment]
So for some reason after selecting the mission properly this code in `talker_npc::update_missions` line 197 oftalker_npc.cpp runs:
```cpp
    if( me_npc->chatbin.mission_selected != nullptr ) {
        if( me_npc->chatbin.mission_selected->get_assigned_player_id() != charID ) {
            // Don't talk about a mission that is assigned to someone else.
            me_npc->chatbin.mission_selected = nullptr;
        }
    }
```
and remove the mission, which is then replaced somewhere by the default mission which is Iron safari for the Intercom

**Comment by Fris0uman** [comment]
The problem might be that the player is not assign to the mission yet since they didn't even get to read it.
