### ISSUE TITLE
npcs have negative values for liquids when trading

### ISSUE THREAD

**Issue by ScritchFox** [CleverRaven/Cataclysm-DDA#43239]
# Describe the bug
NPCs seem to apply a negative value to liquids such as bleach, cough syrup, and other things. Effectively, this allows you to gain credit for trading just by telling them to pour out the liquid on the ground. When traded this way, even if you add the liquids containers to the trade, they'll still pour them on the ground, while giving you the empty containers.

# Steps To Reproduce
1) Create character until you find a starting npc with liquid in their inventory
2) Open trade menu with the NPC
3) Observe negative value, and ability to 'buy' the liquids in order to get credit towards other things.

# Expected behavior
There should not be a negative value assigned to liquids -- and they should probably not even be trade-able -- the containers they're in should be trade-able. Furthermore; the containers the liquids are in seem to have their prices set accounting for a full bottle. This should be changed to inherit the value from the amount of liquid inside.

# Screenshots
![image](https://user-images.githubusercontent.com/70253423/91269272-d7a61680-e744-11ea-8ab8-7f582ed5a2f2.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-5407-g8b385a2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language English
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    No Rail Stations [No_Rail_Stations],
    Alternative Map Key [alt_map_key]

**Comment by wapcaplet** [comment]
Still reproducible in the new trading UI. NPC with a glass bottle of vodka worth negative $13.37:

![image](https://user-images.githubusercontent.com/238395/141685471-6f30e053-2a38-4a18-8f06-ce5459c4156c.png)

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-3853-g564d632595 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by wapcaplet** [comment]
As noted on the duplicate #45436, the probable cause of this is here in `npc.cpp` at the top of `npc::value`:

https://github.com/CleverRaven/Cataclysm-DDA/blob/564d632595faa5feb47c7dc9d34a9a5b932e8c08/src/npc.cpp#L2062-L2066
