### ISSUE TITLE
Inhaler has 0 charges when starting a new game with asthma trait. It should have 100. 

### ISSUE THREAD

**Issue by W5Rusk** [CleverRaven/Cataclysm-DDA#43245]
Inhaler has 0 charges when starting a new game with asthma trait. It should have 100.

I am using latest git pull on master branch at the time of writing this. I know that you are closing such complaints as already completed, but you are not, the problem still exists. It seems that this applies in general to all balloons.

**Comment by Tamiore** [comment]
I have s strong feeling this is still the same issue, in essence: https://github.com/CleverRaven/Cataclysm-DDA/pull/41856

**Comment by ScritchFox** [comment]
Yeah, I also put this in here, in reference to lighters and gas mask cartridges: #43237

Pretty sure these are all the same issue.

**Comment by Fosheze** [comment]
I'm going to make an argument from the realism perspective that maybe the amount should be randomized. Whose to say that the person had a full inhaler when the cataclysm struck. From a pure gameplay perspective though it definitely shouldn't be zero.

**Comment by W5Rusk** [comment]
Anyway, I just want to fix this bug, it is very extensive, affects a huge number of items and spoils the gameplay.

**Comment by Tamiore** [comment]
>I'm going to make an argument from the realism perspective that maybe the amount should be randomized. 

Randomized is pretty pointless/annoying for starting equipment (you can restart in an instant and get more/less). 

I'd argue the amount of charges should simply decrease with starting day. So if you start on day 1 of cataclysm you get 80% of charges in everything,  and it decreases to the minimum, say, 20% of charges left or so but the end of first year.

**Comment by EvgenijM86** [comment]
@Tamiore And if you start the game in 3+ years you start dead I assume?

**Comment by Tamiore** [comment]
> And if you start the game in 3+ years you start dead I assume?

*Undead*, you mean?

On a more serious note: no, 20% is the minimum.

**Comment by ScritchFox** [comment]
I actually think that's a really good idea -- and for realism sake you
could just give them random ranges, if that's something that is desired.

Like 80-100% Day 1 scaling down to like 10-30% after 1 year.

**Comment by EvgenijM86** [comment]
One inhaler lasts 1-2 months with 100 charges. If we are talking about realism either someone is using or it's never been found yet. I just can't imagine that a random asthmatic survivor will find inhaler, take a poof and just leave it there for someone else, so that it would simulate charges decreasing over time. Unless inhalers leak their content over time in real life, which I don't know for sure.

**Comment by Tamiore** [comment]
Maybe it wasn't clear enough, but:

we are talking about the items you START with. I.e. the inhaler/flashlight/cellphone/etc you have in your inventory as you start.
So, yes, someone IS using it. That "someone" being your character before you take it under you direct control.

**Comment by Tamiore** [comment]
Can we, maybe, add the main issue (charges missing from most starting items) to 0.F blocker list?

**Comment by wapcaplet** [comment]
Still reproducible in 0.E-6050-g 74636a72f8
