### ISSUE TITLE
Crafting menu does not recognize Survivor toolbelt qualities when belt is in inventory

### ISSUE THREAD

**Issue by slitherrr** [CleverRaven/Cataclysm-DDA#43248]
# Describe the bug

When I have a survivor utility belt in my inventory (either worn or not), I am unable to perform the Improvised Lockpick craft, and the `metal sawing 2` requirement is highlighted red. When I drop the belt and try the craft after doing so, I am able to perform the craft. If I pick the belt back up, I am once again unable to perform it.

# Steps To Reproduce

1. Create a survivor utility belt from a survivor belt and the various tools (screwdriver set, wrench, hacksaw, wood saw, hammer)
2. Gather materials for the improvised lockpick recipe scrap metal version (1 scrap metal. Note that the "2 wires" version does not require metal sawing and thus does not cause this behavior).
3. Ensure no other tools are present.
4. Put the survivor utility belt in inventory and attempt the improvised lockpick craft. Note it is unavailable, and note that its "metal sawing 2" requirement is in red text.
5. Drop the survivor utility belt and attempt the craft. Note that it is now available.

# Expected behavior

I would expect the metal sawing 2 quality to be available as long as the tool is in reach, regardless of whether it is in my personal inventory or elsewhere.

# Screenshots
![image](https://user-images.githubusercontent.com/6572257/91360372-df69c780-e7e5-11ea-86b3-6b633d364c99.png)
![image](https://user-images.githubusercontent.com/6572257/91360381-e395e500-e7e5-11ea-8543-59256484a4ea.png)

Do not take a screenshot of the crashing window. Please provide the crash logs in the "Additional context" -->

# Versions and configuration

 - OS: Windows 10 x64
 - Game Version: 0.E-5407-g8b385a2 and 0.E-5332-g39272e1
 - Graphics version: Tiles
 - Ingame language: English (US)
 - Mods loaded: DDA, Disable NPC Needs, Blaze Industries, Aftershock, Magiclysm, No Fungal Monsters

**Comment by mqrause** [comment]
The code says `// can't craft with containers that have items in them`, so the reason is you have a knife sheathed in the belt. It doesn't really make sense for items used as tools, though. Plus this check is missing for items you don't carry or wear, which is why it works when you drop the belt.

**Comment by danielkwinsor** [comment]
Happens with butchering too, where  the reported butchering level may be invalid, when the best tool is stored in a container.

**Comment by mqrause** [comment]
@danielkwinsor Can you make a separate issue for that with steps to reproduce it? Butchering works different than crafting, so it requires a different fix.

**Comment by slitherrr** [comment]
(for drive-bys, mqrause is referring to the section here: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/crafting.cpp#L558-L564)

That does make sense. Well, from a code standpoint at least, it's silly from a logic standpoint.

**Comment by wapcaplet** [comment]
Possible duplicate or related to #42702

**Comment by bouchacha** [comment]
> (for drive-bys, mqrause is referring to the section here: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/crafting.cpp#L558-L564)
> 
> That does make sense. Well, from a code standpoint at least, it's silly from a logic standpoint.

Is there an elegant solution? I'm not a programmer so please excuse if any of this is fanciful. Seems like that check should only apply to "container" containers (e.g. cooking pots, metal tanks, etc.) and nothing else (e.g. survivor toolbelts). Does this mean the only solution is manually editing every single item with a new attribute "can only be used when empty"? That sounds maybe tedious, but is probably best for the long run. The other thing that comes to mind is the check you linked to only triggers when a recipe requires either of the following:
- food cooking
- chemical making
- boiling
- containing
I think that would probably approximate the solution, but then there are recipes where this won't make sense. For example, thyme oil requires boiling of 2 and hammering of 1.

**Comment by mqrause** [comment]
> Is there an elegant solution?

Definitely. It just needs a proper definition of all the expected behavior. It's not necessarily something you just slap a solution on for whatever item you come across.

**Comment by Icantthinkofanameforthis** [comment]
Could a solution be adding the qualities of the container to the contained items qualities? like it thinks its holding itself plus anything put into it.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.E.-10390.

![изображение](https://user-images.githubusercontent.com/11132525/115047490-9c31a580-9ee9-11eb-99b1-870a4c5e3e53.png)

![изображение](https://user-images.githubusercontent.com/11132525/115047541-aa7fc180-9ee9-11eb-9263-9c024652c53b.png)
