### ISSUE TITLE
when starting a laboratory with a broken cyborg, guard turrets will not spawn.

### ISSUE THREAD

**Issue by W5Rusk** [CleverRaven/Cataclysm-DDA#43256]
when starting a laboratory with a broken cyborg, guard turrets will not spawn. playing the latest version.

**Comment by snakehand223** [comment]
They don't spawn in any of the lab starts, not just the cyborg one. Not sure if bug or intended.

**Comment by Xenomorph-III** [comment]
It was intended, they removed all turret spawns sometime ago, replacing them with zombie guards

**Comment by anothersimulacrum** [comment]
Intentional #40063
