### ISSUE TITLE
Item duplication with glass containers

### ISSUE THREAD

**Issue by SSpook** [CleverRaven/Cataclysm-DDA#43252]
# Describe the bug

Items in glass containers can be duplicated by throwing the container. The contents of the glass container will appear where the container is thrown as well as the still intact container with all it's contents.

# Steps To Reproduce

Find a glass bottle or jar.
Insert items into it.
Throw it.
Inspect the tile the container landed in.

# Expected behavior

Expected the container to break and disappear.

# Versions and configuration

 - Game Version: 0.E-5366-g7f91078
 - Mods loaded: dda, no npc needs

# Additional context

Liquids in containers within the glass container will also spill, for example you can put a plastic bottle with water in a 3l glass jar and get a puddle and the plastic bottle with water still inside.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-6268.
