### ISSUE TITLE
Joint Torsion Ratchet does not work on a bicycle

### ISSUE THREAD

**Issue by Kniotic** [CleverRaven/Cataclysm-DDA#43260]
# Is your feature request related to a problem? Please describe.
Not really a problem, and I don't know if it is supposed to happen, but I noticed that the Joint Torsion Ratchet CBM does not generate power while on a bicycle, which is something that should happen, I think. Even if only the legs are doing any actual movement, it's still more than just walking around, so I think it should generate power.

# Describe the solution you'd like
Maybe have the cbm generate power depending on the speed you are going, while also draining stamina accordingly (if the CBM is ON).

**Comment by Night-Pryanik** [comment]
Martial arts, especially those with extensive legwork, also should generate power when fighting.

**Comment by cosmo-naut** [comment]
In the real world cycling does use less energy than walking, so I imagine it would comparatively generate less energy than walking/running also.

Source: https://www.exploratorium.edu/cycling/humanpower1.html

**Comment by gkarfakis19** [comment]
I do not know whether this has been fixed since or not, but cycling most definitely charges up the joint torsion ratchet. Just tested on a debug world.
