### ISSUE TITLE
Headlamp batteries listed in Advanced Inventory.

### ISSUE THREAD

**Issue by skoormit** [CleverRaven/Cataclysm-DDA#43265]
# Describe the bug

When wearing a headlamp, the headlamp's batteries are listed as an inventory item in the Advanced Inventory interface.

# Steps To Reproduce

1. Put batteries in a headlamp.
2. Wear it.
3. Open the Advanced Inventory interface.

# Expected behavior

Batteries installed in items carried or worn should not be listed as inventory items.

# Screenshots

(none)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-5434-gaaf7bf0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

(none)

**Comment by Bulletfang** [comment]
Gasmask Cartridges that are loaded into active Firefighter PBA Masks are also listed in the same way batteries are.

**Comment by l29ah** [comment]
It's even worse: they are getting dropped from inventory on `,` AND it's impossible to favorite them: `e` in AIM does nothing while they don't show up in the regular inventory.

**Comment by Jamuro-g** [comment]
looks like it already got fixed

![image](https://user-images.githubusercontent.com/76928284/109859616-7748e200-7c5d-11eb-9b41-9d9e1aa92f6a.png)

**Comment by Night-Pryanik** [comment]
Yeah, can't confirm it either.
