### ISSUE TITLE
JSON inheritance between types: is it an error?

### ISSUE THREAD

**Issue by int-ua** [CleverRaven/Cataclysm-DDA#43274]
# Describe the bug

```js
    "id": "acid_spray",
    "type": "GUN",
    "copy-from": "fake_item",
```
```js
    "abstract": "fake_item",
    "type": "GENERIC",
```

# Expected behavior

JSON inheritance working only within one `type`.

**Comment by jbytheway** [comment]
I agree that this is perhaps unintuitive.  It's another side-effect of how our item loading code is weird and inconsistent with more recent conventions.  I think inheriting a non-GENERIC item from a GENERIC item will work (as this example suggests), somewhat by accident more than design.  I'm unsure whether this is something we explicitly want to support or not.

Certainly something like inheriting a recipe from an item would be wrong.

**Comment by ZhilkinSerg** [comment]
I am pretty sure it only works for items object types as there are plenty of them and they only differ by islots.

**Comment by anothersimulacrum** [comment]
I'm going to say this is resolved. There's nothing actively causing a problem connecting to this, and it likely only does anything for items. While we might want to change those to one type with explicit islot objects in the future, this isn't the issue for that.
