### ISSUE TITLE
Item Dupe and error while unloading needle

### ISSUE THREAD

**Issue by danielkwinsor** [CleverRaven/Cataclysm-DDA#43270]
# Describe the bug

While unloading a partially loaded, wielded wooden needle, the item remains in the needle and is also present in inventory

# Steps To Reproduce

Load needle with 30 plant fiber
Wield needle
Wear straw Basket
Unload Needle

# Expected behavior

Unloaded

# Additional context

 DEBUG    : Tried removing item from object which did not contain it

 FUNCTION : item visitable<T>::remove_item(item&) [with T = item]
 FILE     : src/visitable.cpp
 LINE     : 544

Savegame available upon request

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.E-10390. Closing until reconfirmed.
