### ISSUE TITLE
Length, volume and weight of makeshift knife

### ISSUE THREAD

**Issue by Darkenlord1** [CleverRaven/Cataclysm-DDA#43279]
Length, volume and weight of spike is 6 cm, 0.25L and 0.55 kg
This stats of craftable from spike makeshift knife 20 cm, 0.25L and 0.55 kg...
I dont think it is _ok_, cuz rag or cordages or etc cant add 14 cm to length and dont increase weight and volume.

Maybe set length of makeshift knife to 7 cm, volume to 0.3L and weight to 0.6 kg?

**Comment by miningape** [comment]
Hi, I think this is a good fix. I figured out where the problem is + how to fix it. Right now its super late where I am so I'm gonna sleep, but tomorrow ill fix it so long as no one says not too :)
