### ISSUE TITLE
Add Sand Deposits just like clay deposits

### ISSUE THREAD

**Issue by danielkwinsor** [CleverRaven/Cataclysm-DDA#43272]
# Describe the solution you'd like
We have random overmap clay deposits.  In the same way, we could have sand deposits too.  There is precedent for this, since you can dig anywhere and have a chance at getting sand.

# Describe alternatives you've considered
Sift soil for sand.
Crush pebbles further into sand.

**Comment by souricelle** [comment]
{
    "type": "terrain",
    "id": "t_sand",
    "name": "sand",
    "description": "A large area of fine sand that could be useful in a number of ways, if it was extracted properly.",
    "symbol": ".",
    "color": "yellow",
    "move_cost": 3,
    "flags": [ "TRANSPARENT", "DIGGABLE", "FLAT" ],
    "bash": { "sound": "thump", "ter_set": "t_null", "str_min": 50, "str_max": 100, "str_min_supported": 100, "bash_below": true }
  },

Looks like we have these. Go check near the water.

**Comment by danielkwinsor** [comment]
I think the thing I'm referring to is an overmap overlay, or something.  Just like how there can be a supply drop or a grove randomly added on the overmap.

**Comment by souricelle** [comment]
Go walk along the riverside and you'll see lots of sand tiles. The clay tiles you're thinking of only spawn in forests, they're biome specific.

**Comment by danielkwinsor** [comment]
Are there any of these, but for sand?

<img width="1070" alt="cd" src="https://user-images.githubusercontent.com/2822992/91624231-e1519900-e953-11ea-9e49-7ea79c2b82dd.png">
