### ISSUE TITLE
Ink Glands and Enchantment Muts

### ISSUE THREAD

**Issue by souricelle** [CleverRaven/Cataclysm-DDA#43280]
Describe the bug

Ink glands is a mutation that sometimes squirts ink in the eyes of enemies who attack you in melee. It uses the new enchantment/spell system, however there are a couple of areas where it falls flat.

1) It's free. There's no calorie cost on producing or squirting out ink. Spells have a built-in calorie cost but this gets skipped if the spell is activated via an enchantment.

2) The mutation says you need your torso uncovered to use it, however you can put on an XL survivor suit and use your ink just fine, so some requirement akin to long fingernails and gloves should be included here. The requirement itself is also a bit odd as cephalopod ink glands are part of their gill structure and on a cephalopod mutant, those are behind the ears. I suggest this gets moved to mouth as that can either simulate the facial area in general or the messaging is changed so that the mutant spits the ink out. It's not quite how squids do it but we're not quite a squid.

# Steps To Reproduce

1. Make a player and give them the ink glands mutation.
2. Cover up your torso, then spawn some enemies and let them attack you.
3. Free blindness-inducing counterattacks all day long.

# Expected behavior

A covered bodypart should impede ink squirting, possibly with a funny message, and there should be a way to optionally make spells activated by enchantments come at a cost.

# Versions and configuration

Tested on other versions but most recently on:

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-4819-gbe0dda49b4-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by OldFriendEr** [comment]
uhhh.. I should think of something and fix this.. my honor hands on this.
All of your points are valid
