### ISSUE TITLE
Wielding items from "holster" displays negative action point cost and passes no time.

### ISSUE THREAD

**Issue by VitreousEyes110** [CleverRaven/Cataclysm-DDA#43286]
# Describe the bug

When a "holster" type container(can be 'a'ctivated to store/wield particular items, for example spear strap, back holster.) is 'a'ctivated and an item is wielded from it, the cost of the action is displayed as negative, and no time passes.

# Steps To Reproduce

1. Create character with watch, spear strap, quarterstaff
2. Activate spear strap, holster quarterstaff
3. Activate spear strap again, draw quarterstaff
4. See negative movement point cost displayed, and no time passing

# Expected behavior

Drawing a weapon from its holstered container should cost the displayed "base moves to remove item" cost in action points, and pass time appropriately for that cost.

# Screenshots

![negative movement point cost](https://user-images.githubusercontent.com/45680256/91615396-71daaa00-e951-11ea-8368-e16d413d8757.PNG)
Negative movement point cost being displayed for previous action

![basemoves](https://user-images.githubusercontent.com/45680256/91615930-aef36c00-e952-11ea-9179-1e02f6942df4.PNG)
Example of base moves to remove item for spear strap

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1607
- Game Version: 0.E-5457-gaeb89fd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

Originally found when using quarterstaff+spear strap in normal play. Tested with other spears in spear strap, as well as M1911 in holster, same issue. May not be true for every single "holster" item in the game. Definitely not specific to items with holster in their name, specific to (at least some) items which can be 'a'ctivated to store/wield specific items.

**Comment by LcsTen** [comment]
May be caused by #42450.

**Comment by mqrause** [comment]
> May be caused by #42450.

That didn't cause it, it's related to #42893.
