### ISSUE TITLE
Ammo types that have damage defined through 'proportional' field don't display damage when being examined

### ISSUE THREAD

**Issue by int-ua** [CleverRaven/Cataclysm-DDA#43293]
# Describe the bug

```js
    "id": "shot_bird",
    "proportional": { "damage": { "damage_type": "bullet", "amount": 0.3 }, "recoil": 0.6, "loudness": 0.8 },
```

When examining ammo that have damage defined like this the damage is not shown.

# Steps To Reproduce

1. Wish for shot_00, shot_beanbag, shot_bird.
2. Compare their damage in the game by examining them.

Also noticed on 9x19, must be much more types.

# Expected behavior

~~Since it's widely used maybe it's better to implement support for it. But I will be even happier if only the JSON and docs are fixed.~~ @KorGgenT pointed out that support for it was implemented in `assign.h`. But the damage is not displayed.

# Additional context

#43287

Chezzo wiki also does not support such inheritance http://cdda-trunk.chezzo.com/shot_bird can you just mention the maintainer here?

**Comment by int-ua** [comment]
```sh
$ grep proportional data/ -r | grep damage_type | wc -l
111
```

**Comment by anothersimulacrum** [comment]
Possibly duplicate of #41564?

**Comment by int-ua** [comment]
Definitely.
