### ISSUE TITLE
Random crash when taking mutagen

### ISSUE THREAD

**Issue by CShigaki** [CleverRaven/Cataclysm-DDA#43296]
# Describe the bug

Random crash occurs when taking an unspecified mutagen (flask of mutagen). Maybe there's a bugged mutation?

# Steps To Reproduce

Get a flask of unspecified mutagen and use/reload until crash happens

# Expected behavior

No crash and a new mutation added

# Versions and configuration

```
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-5243-gf05c854 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    More City Locations [cityside],
    Alternative Map Key [alt_map_key],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Graphical Overmap [Graphical_Overmap]
]
```

# Additional context

Log
[logAndDebug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5144998/logAndDebug.zip)
Save
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5144999/save.zip)

**Comment by olanti-p** [comment]
From the backtrace, looks like a duplicate of #43107. Can you check on latest build?

**Comment by wapcaplet** [comment]
Could not reproduce in 0.E-7073-g8d4cd2f280 with a new game, using regular mutagen (drinkable) or mutagenic serum (injected with syringe).
