### ISSUE TITLE
Having Liquid poured on you by npc when requesting gear after accepting a quest.

### ISSUE THREAD

**Issue by FrostyWumpus** [CleverRaven/Cataclysm-DDA#43307]
# Describe the bug
After accepting a quest from an NPC (in my case it was the trader in the refugee center) and asking for some equipment to help out I was given hydrochloric acid which was poured onto my character.

# Steps To Reproduce

1. Accept a quest from an NPC who has a liquid
2. Successfully ask the NPC to share equipment.
3. If the NPC chooses to share a liquid it may be poured onto your character. (I am unsure if the container the liquid is in is important).

# Expected behavior

I expected to receive a container with acid instead of having the trader pour acid on me.

# Screenshots

![cddaissuescreenshot](https://user-images.githubusercontent.com/70447147/91643092-44980580-e9fe-11ea-9ae3-0d4e41fea26b.png)

# Versions and configuration

 - OS: Windows 10
 - Game Version: [0.E-5407-g8b385a2]
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: [dda, no_npc_food, magiclysm, aftershock, SD_Magcrafting, guncotton, No_Rail_Stations, StatsThroughSkills]

**Comment by kevingranade** [comment]
Fixed by #45737
