### ISSUE TITLE
Sunlight doesn't behave correctly in vehicles

### ISSUE THREAD

**Issue by irwiss** [CleverRaven/Cataclysm-DDA#43303]
# Describe the bug

Sunlight penetrates vehicles

# Steps To Reproduce

1) Start new world, no mods, debug spawn intact cube van, set hour to sunlight
(or security truck but install a curtain on door)
2) Get inside the cargo area, close the door
3) You're fully lit inside a vehicle with roofs/floors and boards

# Expected behavior

No sunlight inside vehicle if it's covered

# Screenshots

![image](https://user-images.githubusercontent.com/6560075/91640871-5cd14a00-ea29-11ea-9a5c-9305c6d9ee25.png)

# Versions and configuration

Vanilla world, play fixed scenario on commit 75d3ed1d0e2784aab19c99080c1b88660ceca0d2

**Comment by bouchacha** [comment]
I was wondering about this as well, is it ever possible to create pitch darkness inside a vehicle?

**Comment by anothersimulacrum** [comment]
Probably a result of #42830

**Comment by ApriamAsh** [comment]
This has been bugging me for a while now, can't get sleep without blindfolds. Hope it gets fixed soon!
