### ISSUE TITLE
Feed cows with straw to produce milk, when they are tied down.

### ISSUE THREAD

**Issue by EvgenijM86** [CleverRaven/Cataclysm-DDA#43305]
# Is your feature request related to a problem? Please describe.
Cows are an easy and unlimited food source. If you have 2 cows you can produce more calories than you need with fast metabolism trait, indefinitely.

# Describe the solution you'd like
When cows tied down they should either not produce milk at all, or produce milk at a greatly reduced rate. Or you can release cows into the wild and they will produce milk at normal rates, simulating them eating grass, but you are risking zombies and wildlife eating them in return. And you should be able to feed pile of straws to cows if they are tied down, so that they can produce milk at normal rates for a limited time, even when in complete safety and not moving. Piles of straw is a limited resource, so I think its balanced that way.

# Describe alternatives you've considered
Simplified easy-to-code version, of them just not producing milk if they are tied down, without ability to eat piles of straw.

# Additional context
None.

**Comment by paulenka-aleh** [comment]
It might worth a separate issue, but in general a requirement to feed pets is imperative. For example the same way horse provides infinite motive power.

**Comment by Night-Pryanik** [comment]
No discussion in almost a year, closing.
