### ISSUE TITLE
Gun Modifications are Often Counterintuitive

### ISSUE THREAD

**Issue by DanteTorn** [CleverRaven/Cataclysm-DDA#43319]
# Describe the bug

The weight or volume changes that mods have on weapons makes modifications act counterintuitively a lot of the time. Eg: Adding a holographic sight nerfs aim speed despite claiming to buff it. Adding a folding stock actually makes wield time better despite claiming it makes it worse because of the volume difference.

# Steps To Reproduce

1. Get a gun and some modifications.
2. Compare stats of gun before and after applying modifications.
3. Adding mods often appears to make the gun worse because the weight added by, say, a brass catcher reduces aim speed by 20.

# Expected behavior

Some change in handling from weapon weight is expected, but adding just a few mods to a weapon can nerf its aim speed drastically which is an extremely important stat.

# Screenshots

![Screenshot_135](https://user-images.githubusercontent.com/35230199/91651420-5fad5880-ea84-11ea-9335-003cb20b7ba5.png)
![Screenshot_137](https://user-images.githubusercontent.com/35230199/91651545-f0386880-ea85-11ea-8eba-0dc0f9cb13ac.png)

# Versions and configuration

- OS: Windows 7
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Garden Pots [growable-pots],
    MST Extra [MST_Extra],
    Wild Living [WildLiving],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Hydroponics [hydroponics],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Mythical Martial Arts [MMA],
    Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
    Folding Parts pack [deoxymod],
    Whaleys Hair Mod (UDP Tweaks) [WHALEYHAIR_UDP],
    Vehicle Additions Pack [blazemod],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    DinoMod - UndeadPeople Tileset [DinoModUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP],
    My Sweet Cataclysm - UndeadPeople Tileset [My_Sweet_CataclysmUDP],
    No Acid Zombies [No_Acid_Zombies],
    No Gasoline Boomers [No_Gasoline_Boomers-DANTE],
    No Fungal Monsters [No_Fungi],
    Classes and Scenarios Mod [more_classes_scenarios],
    Faster Stamina Regen [stamina_regen_buff],
    Simplified Nutrition [novitamins],
    Stats Through Kills [stats_through_kills]
]

# Additional context

This has seemingly been a problem for a very long time and I'm not sure why it hasn't been addressed yet. It makes sense that adding weight to a weapon would make it handle worse but a lot of people are saying the just don't bother modifying their guns at all because of these issues. Something needs overhauled here.

**Comment by DanteTorn** [comment]
For folding stocks in particular, I feel that simply changing the description so that it states it reduces both volume and wield time would be appropriate.

**Comment by SirPendrak** [comment]
Nah, folding stocks needs complete rework.

**Comment by Hirmuolio** [comment]
There is also iron sights. They do nothing for any gun since the base aiming stats are same as iron sights.
Except if the gun has another mod that blocks sights from working. Then iron sights work even if they shouldn't.

**Comment by Bulletfang** [comment]
Damn, I didn't even notice. I always just slapped everything on my gun that wasn't bolted down expecting it to improve performance...

**Comment by jbytheway** [comment]
This seems like a great space for someone to write some unit tests.  Should be relatively straightforward to write tests verifying that mods actually move gun stats in the intended direction.

**Comment by RoyBerube** [comment]
Increasing weight of the rifle contributes to reduced aim time. The brass catcher in the middle two panels of the top image is making the gun handling worse for no benefit. Also using a scope slows down aiming for increased accuracy. A decent trade-off.

The three aim mods iron sights, holographic sight, and red dot sight all have an aim speed of 6. The difference is in sight dispersion, with iron sights being the worst and holographic sight the best. The increased weight is a factor here in making them aim slower than iron sights.

Personally I feel that iron sights should be significantly slower to aim than the red dot and holo sights.
