### ISSUE TITLE
Fungal zombie will attack other fungal creature

### ISSUE THREAD

**Issue by WhelpCub** [CleverRaven/Cataclysm-DDA#43310]
# Describe the bug

After fungal zombie stay around with other fungal creature, the fungal zombie will start attacking those creature.

# Steps To Reproduce

1. Create character with Mycus trait
2. Spawn fungal blossom
3. Spawn fungal zombie next to the blossom
4. Press 5 to wait
5. The fungal zombie will start attack fungal blossom

# Expected behavior

I do not know the setting of those fungal zombie, but as it is friendly toward Mycus player, I think fungal zombie is controlled by Mycus, so fungal zombie should not attack other Mycus creature.

# Versions and configuration

- OS: Windows 10
- Game Version: 0.E-5451-g83d3b85 [64-bit]
- Graphics Version: Tiles
- Game Language: Chinese (Traditional)
- Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food]
]

**Comment by wapcaplet** [comment]
Confirmed in 0.E-6177-g 9f4a1b841d - I spawned several fungal zombies, and they fight each other:

![image](https://user-images.githubusercontent.com/238395/94095969-1a105100-fde0-11ea-93d4-e2f88b44829d.png)

**Comment by deane-c64** [comment]
this behavior also happens with Towers and the Walls that surround them. sometimes mycus will attack player, but its only once.
