### ISSUE TITLE
Undefined behaviour in map::build_seen_cache()

### ISSUE THREAD

**Issue by anothersimulacrum** [CleverRaven/Cataclysm-DDA#43313]
# Describe the bug
src/lightmap.cpp:1194:9: runtime error: index -1 out of bounds for type 'float [132][132]'
The same error can also occur on line 1212.

https://github.com/CleverRaven/Cataclysm-DDA/blob/801b7869d6f0f0154bbc5d008e2997ef5c1dfe6b/src/lightmap.cpp#L1194
https://github.com/CleverRaven/Cataclysm-DDA/blob/801b7869d6f0f0154bbc5d008e2997ef5c1dfe6b/src/lightmap.cpp#L1212

The tripoint `origin` was `x: -1, y: 0, z: 0` for the first case, and `x: -1, y: 0, z: ?` (I didn't capture the z) for the second.

# Steps To Reproduce
1. Compile the game with UBSan.
2. Create a new character in a new world.
3. Recieve the error.

# Expected behavior
No undefined behavior.

# Versions and configuration
I could not load into the world, but here's the info as close as I can match:
37c078789a800a703b52350d4fc50db20fc742ba

 - OS: Linux Arch Linux, kernel version 5.8.1
 - Game Version: 37c078789a800a703b52350d4fc50db20fc742ba
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: dda, no npc needs

**Comment by jbytheway** [comment]
I'm concerned that this is not being caught by our UBSan CI job.  I wonder if perhaps we're not exercising this code in the tests?  But I would have expected we were; there are quite a few tests around the lighting code...

**Comment by BrettDong** [comment]
Duplicate of #36570.
