### ISSUE TITLE
Gathering water into wielded container do not change weight

### ISSUE THREAD

**Issue by starytroll** [CleverRaven/Cataclysm-DDA#43328]
# Describe the bug

It seems that pouring water from a pool to wielded tank does not change weight of carried item, so that I can travel with it without additional pain/stamina cost.

# Steps To Reproduce

1.  Wield metal tank.
2. 'e'xamine water tile and put the water into tank.
3. Check 'i'nventory and see that total weight remains unchanged.

# Expected behavior

The carried mass should change after filling the container.

# Screenshots

![obraz](https://user-images.githubusercontent.com/54743246/91657919-5e505000-eac5-11ea-8b86-3c1c472e4ba2.png)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-5457-gaeb89fd [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key]
]

# Additional context

Probably it is the case for other containers as well.

**Comment by mqrause** [comment]
Seems like an issue with the weight cache not always being up to date. With a bunch of tries, I can pick up a filled 60l tank without adding any weight to my inventory. The issue solves itself after a while, though.

**Comment by wapcaplet** [comment]
I can reproduce this issue in 0.E-5679-g446c750473.

Starting with the 4.0 kg of clothes I'm wearing:

![image](https://user-images.githubusercontent.com/238395/92281549-119bb900-eeb9-11ea-85ec-55a803d74fb6.png)

Picking up and wielding an empty 60L tank (5.67 kg), my weight is up to 9.7 kg:

![image](https://user-images.githubusercontent.com/238395/92281648-427bee00-eeb9-11ea-89de-1aacdfcbb865.png)

Going down to the river and filling up the 60L tank completely, I see my weight has not changed:

![image](https://user-images.githubusercontent.com/238395/92281710-6dfed880-eeb9-11ea-9586-6f7aa9cf6560.png)

My total inventory weight has still not changed after walking around a bit.

Looking at the tank, it shows its own weight correctly as 65.67 kg:

![image](https://user-images.githubusercontent.com/238395/92281781-971f6900-eeb9-11ea-988a-3c1dfae8fc28.png)

If I drop the tank, then pick it up (and wield it) again, it becomes weightless, and I am back to my original 4.0 kg:

![image](https://user-images.githubusercontent.com/238395/92281846-bd450900-eeb9-11ea-8e16-054e38c2f02b.png)

*However*, if I get another empty 60L tank, and fill it up from the toilets in the evac shelter basement:

![image](https://user-images.githubusercontent.com/238395/92281967-f54c4c00-eeb9-11ea-8b0e-a82f368d737a.png)

It is not enough units to completely fill the tank, and I see the weight correctly updates in my inventory:

![image](https://user-images.githubusercontent.com/238395/92282013-0b5a0c80-eeba-11ea-9d92-0d32a1a511bc.png)

Dropping and picking up this partly full (partly empty) tank, my inventory weight is correctly updated.

So it seems this only affects *full* tanks for some reason.

**Comment by RoyBerube** [comment]
Some testing I've done indicates that if you have enough space to put the item in inventory, then the weight is calculated correctly. It does not apply just to fluid tanks. 

For example with a hiking backpack that cannot be held in inventory, wearing it adds no weight. Adding items to it can trigger the weight to be displayed properly but not always. With a car battery and hammer contained and wearing it from the floor, it adds no weight. Unloading the backpack then shows the correct weight.
