### ISSUE TITLE
mon_zombie_skull is not part of any monster group and not used in any map

### ISSUE THREAD

**Issue by Fris0uman** [CleverRaven/Cataclysm-DDA#43329]
# Describe the bug

mon_zombie_skull is not part of any monster group and not used in any map

# Steps To Reproduce

Search for `mon_zombie_skull` in the repo
See it's used in retrodays, blacklisted in aftershock and that's it

# Expected behavior

Actually using the monster we have defined ^^

# Additional context

We could alos just get rid of it.

**Comment by anothersimulacrum** [comment]
The listener zombie upgrades into it.
https://github.com/CleverRaven/Cataclysm-DDA/blob/9dbd68aca40080c48dfed2c021f80dcdd288547a/data/json/monsters/zed_misc.json#L285
