### ISSUE TITLE
[Crazy Cataclysm] Too much SpOreos

### ISSUE THREAD

**Issue by WhelpCub** [CleverRaven/Cataclysm-DDA#43320]
# Is your feature request related to a problem? Please describe.
As SpOreos will spawn randomly when every spore pop out, when you stay around those fungaloid too long, all tile around fungaloid will cover by SpOreos.

![9](https://user-images.githubusercontent.com/69908199/91651532-740f4680-eac0-11ea-935c-6bb3b539edbd.png)

# Describe the solution you'd like
When spore pop out, and the random number check is success and ready for spawn SpOreos, add a new requirement. Check about 10 ~ 20 tile around the spore, if there is other SpOreos already, stop spawn new SpOreos.

# Describe alternatives you've considered
Remove random spawn from spore, and add a new random.
When flower turns into fungal flower, there is a chance to become SpOreos. (or long grass, or other things)

**Comment by WhelpCub** [comment]
I have check the code, the spawn of SpOreos is in line 1717 of monattack.cpp, fungus_corporate()

For how to check is there others SpOreos in the map, I find something like that but not confirm, as still not understand how the code work.

1. line 2549 of character.cpp, nearby()
2. line 166 of item_location.cpp, item_on_map()

Hope these can help.

**Comment by anothersimulacrum** [comment]
This patch makes them 10x more rare. The number can be changed however for whatever rarity.
```cpp
diff --git a/src/monattack.cpp b/src/monattack.cpp
index e3700c7b58..e202d5d72a 100644
--- a/src/monattack.cpp
+++ b/src/monattack.cpp
@@ -1717,7 +1717,7 @@ bool mattack::fungus( monster *z )
 
 bool mattack::fungus_corporate( monster *z )
 {
-    if( x_in_y( 1, 20 ) ) {
+    if( one_in( 200 ) ) {
         sounds::sound( z->pos(), 10, sounds::sound_t::speech, _( "\"Buy SpOreos(tm) now!\"" ) );
         if( get_player_view().sees( *z ) ) {
             add_msg( m_warning, _( "Delicious snacks are released from the %s!" ), z->name() );
```
