### ISSUE TITLE
Shotgun Bandolier can only hold 5 round of shot ammo 

### ISSUE THREAD

**Issue by esavier** [CleverRaven/Cataclysm-DDA#43337]
# Explanation
For some reson i can not load 00 Shot ammo to either waist nor torso shotgun bandolier. From what i tested it seems that slug ammo is still permitted.

edit:
it seems that only 5 rounds of 12 gauge are permitted instead of 25,
also if i try loading more than 5 (max capacity), the activity fails without loading any

# How to reproduce
* spawn bandolier, 
* spawn some 00 shot ammo (12gauge)
* spawn some slug ammo (12gauge)
bugs:
* try inserting 70 shots (fails - should load 25, loads 0)
* try inserting 25 shots  (fails - should load all)
* try inserting 5 shots (succeeds)
* try inserting 1 shot  (succeeds)

# Screenshots

![obraz](https://user-images.githubusercontent.com/5251231/91667911-506fee80-eb08-11ea-972e-1b5055d13b86.png)
![obraz](https://user-images.githubusercontent.com/5251231/91667919-739a9e00-eb08-11ea-8ad1-ccb807476cd4.png)

# Versions and configuration
0.E-5492-g37c078789a
* disable npc needs
* CRIT expansion mod
* blaze industries
* aftershock
* alternative may keys
* stats trhrough skills
* fuji military professions
* no fungal monsters

# Additional Context
please correct me if i am doing something wrong, but last time i was playing as a shotgun slayer i was able to use shotgun bandolier to hold any shotgun ammo, not only slugs. If that is not the case anymore, please update the description. If i am mistaken please close the ticket with explanation.

* second screen is AFTER i spawnd and inserted slug round

**Comment by ZhilkinSerg** [comment]
Cannot reproduce on latest version in vanilla. Are you using any mods?

**Comment by esavier** [comment]
> Cannot reproduce on latest version in vanilla. Are you using any mods?

updated request

**Comment by esavier** [comment]
on latest build it seems that if there is too many of the shots, inserting those results in error.
i.e.
inserting 4 shots succeeded
inserting 70 shots failed,

i would expect that enough shots would be deduced to fill the container. i.e. inserting 70 shots would fill the bandolier, but it would fail to insert them all. I would end up with 25 shots in belt, and 45 in hand/inventory

**Comment by wapcaplet** [comment]
Confirmed in 0.E-6177-g 9f4a1b841d

The torso shotgun bandolier says it will hold only 20x66mm caseless, .410 shot, shot, or signal flare:

![image](https://user-images.githubusercontent.com/238395/94328024-6be5e200-ff6c-11ea-9993-8faf95044ce2.png)

I can load it with 15 signal flares:

![image](https://user-images.githubusercontent.com/238395/94328073-ec0c4780-ff6c-11ea-9d18-5d98d0b8896a.png)

Or I can load it with 15 00 shots:

![image](https://user-images.githubusercontent.com/238395/94328097-0ba37000-ff6d-11ea-9c83-babee813786b.png)

Or 15 shotgun slugs:

![image](https://user-images.githubusercontent.com/238395/94328138-32fa3d00-ff6d-11ea-8e9e-367a4f44782c.png)

However, if I try to load all three:

![image](https://user-images.githubusercontent.com/238395/94328148-41e0ef80-ff6d-11ea-987a-7db2441da558.png)

Then I get multiple error messages:

```
 DEBUG    : tried to put an item (shot_00) count (15) in a container (torso_bandolier_shotgun)
 that cannot contain it: pocket unacceptable because item is not the correct ammo type

 DEBUG    : tried to put an item (shot_slug) count (15) in a container (torso_bandolier_shotgun)
 that cannot contain it: pocket unacceptable because item is not the correct ammo type
```

and only the signal flare is loaded. At this point, the bandolier only contains the 15 signal flares, and if I try to `i`nsert again, it says I have nothing available:

![image](https://user-images.githubusercontent.com/238395/94328183-91272000-ff6d-11ea-8767-d52f84ceb5df.png)

**Comment by lancewf** [comment]
I am not able to reproduce the originally reported bug from @esavier. 
I am able to load the "waist shotgun bandolier" with 25 shotgun slugs or 25 00 shots (shown below). 
![image](https://user-images.githubusercontent.com/1679247/118220293-3543d580-b430-11eb-8d5b-b4d7e4cac56a.png). 

What @wapcaplet described sounds like a different bug, but I can reproduce it. I can not load different types of the allowed ammo types in either the "waist shotgun bandolier" or "torso shotgun bandolier". I can load the same time of ammo up to the total capacity. 

I would like to confirm that the feature we want to add is the ability to add different types of the allowed ammo types into these storage clothes.

**Comment by lancewf** [comment]
This looks like this is a known restriction from the definition of containers. 
The "waist shotgun bandolier" json is below. 
```
  {
    "id": "bandolier_shotgun",
    "type": "ARMOR",
    "name": { "str": "waist shotgun bandolier" },
    "description": "A leather bandolier worn around the waist for keeping shotgun shells close to hand.",
    "weight": "140 g",
    "volume": "500 ml",
    "price": 1900,
    "price_postapoc": 1500,
    "material": [ "leather" ],
    "symbol": "[",
    "looks_like": "leather_belt",
    "color": "dark_gray",
    "covers": [ "torso" ],
    "coverage": 10,
    "encumbrance": 2,
    "material_thickness": 1,
    "pocket_data": [ { "ammo_restriction": { "410shot": 25, "shot": 25, "20x66mm": 25, "signal_flare": 25 }, "moves": 25 } ],
    "flags": [ "WATER_FRIENDLY", "WAIST", "OVERSIZE" ]
  },
```
from https://github.com/CleverRaven/Cataclysm-DDA/blob/b991a1bab26d0fb8a6f9068ab4e9c9639ab76e26/data/json/items/armor/bandolier.json#L88

The "pocket_data" has the "ammo_restriction" defined so the below definition fits. 
``
"ammo_restriction": { "ammotype": count }, // Restrict pocket to a given ammo type and count.  This overrides mandatory volume, weight, watertight and airtight to use the given ammo type instead.  A pocket can contain any number of unique ammo types each with different counts, and the container will only hold one type (as of now).  If this is left out, it will be empty.
```
from https://github.com/CleverRaven/Cataclysm-DDA/blob/3cd92bed7f2acd4b49fe82da77119c3b5454b308/doc/JSON_INFO.md#containers

**Comment by esavier** [comment]
Bug was tested pretty long time ago, i will check if this is happening again or was it magically resolved along the way.
I was certain that i could not use the shotgun bandolier properly and needed to search  for another option.

**Comment by esavier** [comment]
Lets close this, probably this bug is not there anymore.
