### ISSUE TITLE
Pupating Zombie dying causes raptors to spawn on top of character

### ISSUE THREAD

**Issue by Maverick4783** [CleverRaven/Cataclysm-DDA#43340]
# Describe the bug
A pupating zombie dies roughly a maptile away, but the flesh raptors it spawns will appear around the player.

# Expected behavior
The flesh raptors should appear around where the pupating zombie was, since they are coming out of the pupating zombie

# Screenshots

![Before](https://user-images.githubusercontent.com/48425232/91670313-3de6bc80-eaea-11ea-8f46-149677a30c80.png)
![Raptors](https://user-images.githubusercontent.com/48425232/91670289-0710a680-eaea-11ea-88b6-b6f7d5564196.png)
![Corpse](https://user-images.githubusercontent.com/48425232/91670324-58b93100-eaea-11ea-911c-ab656a6169fd.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-5518-g9dbd68a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]
# Additional context
[CDDA save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5147651/CDDA.save.zip)
Walk North, Pupating zombie is to the North East, near the corner of the collapsed tower. The zombie will die and you will be swarmed by raptors despite being far away.

**Comment by kenneth-ellis** [comment]
Just wanted to +1 this report with some extra notes.  Not only do the flesh-raptors spawn adjacent to the player when the pupating zombie dies far away -- apparently the flesh-raptors will also instantly *teleport* through solid walls and unbroken windows to appear within 2-3 tiles of you.  I just had a pupating zombie explode *outside* to the east of the hardware store I was standing in the middle of with all doors/windows shut.... 7 flesh-raptors instantly teleported inside surrounding me somehow without breaking any of the walls or windows.  I can provide a save for this if helpful.

**Comment by anothersimulacrum** [comment]
Whaaaaat? That sounds perfectly intentional.

**Comment by Darkenlord1** [comment]
And maybe nerf them a bit? They penetrate chitin armor like nothing and causing very hard bleeding in 3 or five turns, and its almost insane to hit them.
