### ISSUE TITLE
[Aftershock] Solar Panel CBM does not work as of latest build

### ISSUE THREAD

**Issue by drhead** [CleverRaven/Cataclysm-DDA#43362]
# Describe the bug

As of the latest experimental build (10967) the Solar Panel CBM from Aftershock no longer charges bionic power.

# Steps To Reproduce

1. Start a game with Aftershock enabled.
2. Install Solar Panel CBM alongside some bionics.

# Expected behavior

Bionic power should go up in clear or sunny weather since that's what the CBM has always done.

# Versions and configuration

Experimental Build 10967, Windows x64 Tiles.

The last build I used was 10950, and the bionic worked fine.

# Additional context

I suspect the bug may have something to do with the refactor in commit eba792f63a6a3d71febd62fc6eaf1544e21abed4 as it is a recent change affecting bionic power.

**Comment by Qrox** [comment]
Probably it's because I forgot to check `is_remote_fueled` when multiplying fuel efficiency with solar pack efficiency. I'll test and push a fix.
