### ISSUE TITLE
Crash to desktop when using basecamp garage chop shop function.

### ISSUE THREAD

**Issue by drhead** [CleverRaven/Cataclysm-DDA#43385]
# Describe the bug

When I use a basecamp garage's chop shop task, the game crashes when I move afterwards.

# Steps To Reproduce

1. Load the included save file.
2. Go to the bulletin board.
3. Select "Chop Shop" on the southwest garage.  There is already a car in the garage.  I assigned Liliana Faust to the task.
4. After assigning the task, move one tile (or wait a turn) and the game will crash.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-5554-gc3fc83e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Crazy Cataclysm [crazy_cataclysm],
    Crazy Cataclysm - UndeadPeople Tileset [CrazyCataclysmUDP],
    Blaze Industries [blazeindustries],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    Aftershock [aftershock],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    No Fungal Monsters [No_Fungi],
    Prevent Zombie Revivication [no_reviving_zombies]
]

# Additional context

[Save File - Moss Hill.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5159243/Moss.Hill.zip)

Unfortunately, debug.log and crash.log did not generate anything relevant to this crash.  I tailed debug.log while reproducing the crash several times and no lines were printed at the time of the crash, and crash.log had no lines printed either.

**Comment by jeremyshannon** [comment]
As a workaround, you can just set up a vehicle desconstruct zone inside the chop shop, park a vehicle in there, and order your NPCs to disassemble it. It's actually more efficient than using the bulletin board function, which should probably be remove and replaced with an automated zone assignment function. Especially if it causes crashing now.

**Comment by anothersimulacrum** [comment]
Yes, that function should be removed, and the unused `difficulty` member of vehicle parts with it (unused because it's only used there).

**Comment by jeremyshannon** [comment]
How I'd like to see it work ideally is the shop gets assigned a vehicle repair zone and a vehicle deconstruct zone overlapping, and you assign some workers to it from the billboard, with the first one added being the foreman. Then when you pull a vehicle in and park, the foreman steps up and says "Hey, boss, you want we should fix this thing up, or are we tearing her down?" and then jobs are assigned to the workers accordingly.
 Though the really tricky part would be detecting the vehicle's arrival, I don't think we have any code that could handle that.

**Comment by sumpfralle** [comment]
Just for the sake of completeness - this is the crash log:

```
The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 0.E-8007-gf58e7a4
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

    ./cataclysm-tiles(_Z21debug_write_backtraceRSo+0x38) [0xc0794f]
    ./cataclysm-tiles() [0xbf18dc]
    ./cataclysm-tiles() [0xbf1a5e]
    /lib/x86_64-linux-gnu/libc.so.6(+0x3bcc0) [0x7fc887fa0cc0]
    ./cataclysm-tiles(_ZNK8tripointplERKS_+0) [0xa22c06]
    ./cataclysm-tiles(_ZNK7vehicle16global_part_pos3ERK12vehicle_part+0x34) [0x139793a]
    ./cataclysm-tiles(_ZNK7vehicle16global_part_pos3ERKi+0x1a) [0x1397978]
    ./cataclysm-tiles(_ZN7vehicle25check_falling_or_floatingEv+0x81) [0x13c6a3f]
    ./cataclysm-tiles(_ZN7vehicle10gain_movesEv+0x60) [0x13ae8be]
    ./cataclysm-tiles(_ZN3map7vehmoveEv+0x112) [0xf30760]
    ./cataclysm-tiles(_ZN4game7do_turnEv+0x86a) [0xcf5340]
    ./cataclysm-tiles(main+0x139c) [0x923c64]
    /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xea) [0x7fc887f8bcca]
    ./cataclysm-tiles(_start+0x29) [0x9f50b9]

    Attempting to repeat stack trace using debug symbols…
    debug_write_backtrace(std::ostream&)
    ??:?
    log_crash
    crash.cpp:?
    signal_handler
    crash.cpp:?
    ??
    ??:0
    tripoint::operator+(tripoint const&) const
    ??:?
    vehicle::global_part_pos3(vehicle_part const&) const
    ??:?
    vehicle::global_part_pos3(int const&) const
    ??:?
    vehicle::check_falling_or_floating()
    ??:?
    vehicle::gain_moves()
    ??:?
    map::vehmove()
    ??:?
    game::do_turn()
    ??:?
    main
    ??:?
    ??
    ??:0
    _start
    ??:?
```

It happens exactly like described by the bug reporting.
