### ISSUE TITLE
Game crashes when mopping bug splatter and hemolymph

### ISSUE THREAD

**Issue by Skakhl** [CleverRaven/Cataclysm-DDA#43386]
# Describe the bug

Whenever I try to mop bug splatters or hemolymph splatters, the following debug message appears, and the game crashes.

 DEBUG    : invalid field types id "393223"

 FUNCTION : const T &generic_factory<field_type>::obj(const int_id<T> &) const [T = field_type]
 FILE     : src/generic_factory.h
 LINE     : 393

# Steps To Reproduce

1. Spawn a cockroach or other type of bug
2. Kill it 
3. Mop up the spill

# Versions and configuration

- OS: Linux
- OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.1 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-5574-g006bfcd7da-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Graphical Overmap [Graphical_Overmap],
    No Rail Stations [No_Rail_Stations],
    Blaze Industries [blazeindustries]

# Additional context

[CDDA crash info.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5159383/CDDA.crash.info.zip)

**Comment by ZhilkinSerg** [comment]
I cannot reproduce the issue.
