### ISSUE TITLE
Web weaver mutation cannot make web inside vehicle

### ISSUE THREAD

**Issue by MasterLiKhao** [CleverRaven/Cataclysm-DDA#43380]
# Describe the bug

When activating the Web Weaver mutation while inside a vehicle, the web is not spun inside the vehicle. Instead, it is placed on the ground below the vehicle. Leaving the mutation active for 3 turns does not progress the web past cobwebs.

# Steps To Reproduce

1. Create character with web weaver mutation.
2. Spawn vehicle, move character into vehicle.
3. Activate web weaver mutation, wait 3x
4. Check vehicle tile for webs, move vehicle, see web appear on ground below vehicle
5. Examine tile, see cobwebs

# Expected behavior

For activating the web weaver mutation and waiting 3x inside a vehicle making thick webs appear inside the vehicle. 

# Screenshots

![grafik](https://user-images.githubusercontent.com/68699341/91887050-8d63ee80-ec8a-11ea-8d18-11633b660694.png)

# Versions and configuration

- OS: Windows
    - OS Version: Windows 7
- Game Version: 0.E-5567-gc353346 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Cataclysm++ [Cata++],
    Mythical Martial Arts [MMA],
    Graphical Overmap [Graphical_Overmap],
    SpeedyDex [speedydex],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP]
]

**Comment by SatanHellLord** [comment]
Caused by #42253
