### ISSUE TITLE
Camp food crafting does not seem to remove ingredients from camp root cellar

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#43398]
I've used the camp orders to ordering crafting of cheese from curdled milk stored in the camp built root cellar (set up as a camp resource zone), and the milk does not disappear from the cellar. Similarly, I've ordered crafting of pemmican, and berries stored in the root cellar do not disappear, while they do disappear when dropped in the "normal" resource zone. I believe lard and dehydrated meat stored in vehicle fridges disappear on pemmican making orders (these fridges set up as resource zones).

I haven't tried any other recipes/orders.

# Steps To Reproduce

- Drop curdled milk in a camp built root cellar (camp built = constructed as part of camp construction by a companion).
- Have the root cellar set up as Basecamp: Storage zone.
- Have a kitchen camp expansion (to make food production orders available)
- Order the making of cheese from the menu in the kitchen zone (batch 9, typically, as the curdling order takes 15 raw milk->18 curdled milk).
- Wait until the order is done.
- Order the companion to return, resulting in cheese being dropped.
- Note that the curdled milk is still in the root cellar.
- Keep producing cheese from the same milk until it rots...

Note that there may be something odd going on with the kitchen orders, as I've had cases where available resources don't show up, only to show up (in the form of an available recipe) later, with nothing moved.

# Expected behavior

Input resources for cooking should be consumed regardless of whether they're taken from a root cellar, a vehicle fridge, or a zone on open ground.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]

# Additional context
None. My game has just ordered the last of the lard to be used for pemmican, and I've got no curdled milk (cheese making turns out to consume about as many calories as it converts into cheese, and so is rather pointless, unless you want to withdraw camp calories and convert them into player mid term storage calories). I should be able to produce curdled milk easily, though, if requested.

**Comment by Saicchi** [comment]
Can't reproduce this on 0.E-9419-g5146b8f10d.
Materials were properly consumed even when inside containers.

**Comment by PatrikLundell** [comment]
Including in root cellars?

**Comment by Saicchi** [comment]
Yes. The materials were inside the root cellar. Could you try updating your game and seeing if it still happens if possible?

**Comment by PatrikLundell** [comment]
Does no longer happen when I tried to repeat it.

I've updated the game to whatever the current experimental is and copied my save over (with a lot of popups about things that have changed). I ended up debug spawning curdled milk rather than making it (and waiting), dropped the curdled milk into the root cellar and set a companion to work. Debug forwarded the time 10 hours (a bit more than the work took), and recalled the companion. The root cellar now contains a bunch of empty small waterskins in addition to ones filled with curdled milk (bb crafting now says 72 curdled milk, while it was 108 before the crafting).

Thus, it seems something has fixed the issue over the last ½ year.

**Comment by esotericist** [comment]
thanks for reporting back.

**Comment by PatrikLundell** [comment]
A guess is that it might have been fixed when the bug that caused charges not to be removed properly when the items weren't in the inventory. It's a somewhat similar situation in that resources were correctly identified when the task was initiated, but weren't found when they should be deducted (the case for the failure to remove the food is a guess, of course)
