### ISSUE TITLE
Cooked food not grouped with other food

### ISSUE THREAD

**Issue by Bulletfang** [CleverRaven/Cataclysm-DDA#43391]
# Describe the bug

(This is a minor QoL bug, I'm not even certain whether this is actually a bug or not, feel free to nuke this issue from orbit.)
Cooked food isn't grouped with other scavenged food items when opening the consume menu with (E). Food is conveniently placed at the top, but cooked meat, lard, tallow and cracklins are not. 

# Steps To Reproduce

1. Cook above mentioned foods.
2. Open eat menu to eat them.
3. Witness the cooked food not together with scavenged food.

# Expected behavior

Cooked food at the top, grouped with other food.
The entire food block is ordered by shelf-life, which is extremely convenient and useful, not having things like cooked meat, with its very short 24 hour shelf-life, in there sorted with everything else is... irksome.

# Screenshots
Screenshots are me sifting through my entire food and drug supply in order to find my meat.

![QoL1](https://user-images.githubusercontent.com/45204409/91924943-47337d00-ecd4-11ea-8805-f6447820f4f5.png)

![QoL2](https://user-images.githubusercontent.com/45204409/91924951-4b5f9a80-ecd4-11ea-900a-8c6927d84279.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-5366-g7f91078 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion]
]

# Additional context

None.

**Comment by jbytheway** [comment]
Looks like the distinction here is that the food at the top is in another container, whereas the food at the bottom is just loose in your vehicle.  This is affecting the consumption menu sort order somehow.  I think it is not intended behaviour.
