### ISSUE TITLE
wrong wall tile

### ISSUE THREAD

**Issue by CHJKDM51** [CleverRaven/Cataclysm-DDA#43403]
# Describe the bug
One of interior tiles is a sidewalk instead of wall, which makes it possible to see 'hidden' safe from kitchen.

# Steps To Reproduce

# Expected behavior
Expected to be wall instead of sidewalk.

# Screenshots
![wrong tile](https://user-images.githubusercontent.com/58046029/92018245-95409300-ed5d-11ea-99b0-3cccfc0e3102.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-5620-gc4627a8 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

**Comment by Night-Pryanik** [comment]
Fixed by #44094.
