### ISSUE TITLE
The 'F'avorite function of the inventory only works individually.

### ISSUE THREAD

**Issue by Aphegis** [CleverRaven/Cataclysm-DDA#43404]
# Is your feature request related to a problem? Please describe.

Example that explains this Quality of Life suggestion:
I crafted 40 lockpicks (but it behaves the same with any item) and tried to favorite them, but it only works individually, so it's really slow/inefficient/tedious to favorite itens in there are many of them in your inventory.
![a1](https://user-images.githubusercontent.com/34956440/92024492-a628de80-ed34-11ea-9070-5061a54408f3.PNG)
![a2](https://user-images.githubusercontent.com/34956440/92024495-a6c17500-ed34-11ea-9e21-b1bf9cdbd845.PNG)

# Describe the solution you'd like

Favorite the 40 lockpicks at the same time.

# Additional context

The image shows a bug in the autoletters system, but this is already reported.

**Comment by Valares** [comment]
Having the "f" key reserved to mark only a single item as favorite makes sense in my opinion, as I personally don't necessarily want to get the whole stack of screwdrivers I've picked up favored.

If you want to favorize the whole stack, you can open your inventory, move the selection bar over to the stack you want to favorize and press the asterisk symbol (*) on your keyboard. This also works in the advanced inventory and the disassembly menu (for some reason)...

**Comment by Aphegis** [comment]
Oh i didn't knew that the '*' worked on the inventory as well! My suggestion would be then, to somehow say/show/explain that this is possible in the inventory interface.

**Comment by GGgatherer** [comment]
> If you want to favorize the whole stack, you can open your inventory, move the selection bar over to the stack you want to favorize and press the asterisk symbol (*) on your keyboard

The thing is, as soon as some of that stack of favorized lockpicks change their durability, they are removed from favorites list.
