### ISSUE TITLE
Slimes don't make slime sounds anymore.

### ISSUE THREAD

**Issue by Bulletfang** [CleverRaven/Cataclysm-DDA#43415]
# Describe the bug

Slimes used to make very distinct slime sounds, one could easily discern whether there were slimes on the other side of that wall or normal zombies. However since that one change to the slime faction a couple weeks back, the one where all slimes started fighting each other, they started making normal footsteps, like the average zombie.

# Steps To Reproduce

1. Find or spawn slimes.
2. Lock them in a room.
3. Listen through the walls for their footsteps. (They used to make unique slime sounds)

# Expected behavior

_Glorp, schlorp, slurp, squelch_, or something along the lines of these, I don't remember the exact words anymore, but they definitely did not make normal footstep sounds.

# Screenshots

A suspicious room, I suspected slimes because what was inside did not break through the fragile glass doors despite me luring them around by making noises on purpose:
![slim](https://user-images.githubusercontent.com/45204409/92065009-18cea400-ed9f-11ea-9736-603df57bd16a.png)

What's inside:
![slim2](https://user-images.githubusercontent.com/45204409/92065059-313ebe80-ed9f-11ea-8d90-57950e5f0e3f.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-5620-gc4627a8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion]
]

# Additional context

None.

**Comment by Amoebka** [comment]
It was "you heard plop" I believe.

**Comment by ZhilkinSerg** [comment]
Slimes have multiple species assigned - `NETHER` and `SLIME`. Footsteps are taken from the first species found. We should either have primary species allowed to be defined for monster types or remove `NETHER` from slimes.
