### ISSUE TITLE
Secubots deployed by failed hacking attempt can't fire.

### ISSUE THREAD

**Issue by Bulletfang** [CleverRaven/Cataclysm-DDA#43414]
# Describe the bug

Failing a hacking attempt with the result of a **M16A4 autonomous TALON UGV** deploying has that bot unable to fire its weapon for some reason.

# Steps To Reproduce

1. Fail hacking attempt (not with the hacking tool).
2. Let security robot deploy.
3. Witness how that bot can't use its weapon.

# Expected behavior

Security robot can fire its weapon.

# Screenshots

![secubnot](https://user-images.githubusercontent.com/45204409/92063750-39e1c580-ed9c-11ea-851a-14182d49346e.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-5620-gc4627a8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion]
]

# Additional context

None.

**Comment by Theundyingcode** [comment]
"You hear a chk!" is the notification that gets displayed when it attempts to fire its gun(s) without any ammo...

**Comment by valihanov** [comment]
Reproducible in 0.G
