### ISSUE TITLE
Very short weapons/items.

### ISSUE THREAD

**Issue by Bulletfang** [CleverRaven/Cataclysm-DDA#43420]
# Describe the bug

Found some items that are still too short and probably just need their longest side declared. 

# Screenshots

![sho1](https://user-images.githubusercontent.com/45204409/92077265-57268c00-edbc-11ea-8f57-be9d0f900466.png)
![sho2](https://user-images.githubusercontent.com/45204409/92077273-5aba1300-edbc-11ea-92ed-5c8690ceed66.png)
![sho3](https://user-images.githubusercontent.com/45204409/92077276-5c83d680-edbc-11ea-85da-6871ecbba9d3.png)
![sgo](https://user-images.githubusercontent.com/45204409/92078593-d6b55a80-edbe-11ea-9bc0-abf172bf4f74.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-5620-gc4627a8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion]
]

# Additional context

Guns all seem to have been properly lengthened now, these items need the same treatment.

**Comment by wapcaplet** [comment]
The particular items mentioned in this issue all have `longest_side` defined now:

- compound hunting bow (150 cm), modern recurve bow (152 cm), short bow (132 cm) and many others in #43424 
- pickaxe (91 cm) in #43441 

Other tool lengths will continue being tracked in #41691, so I am closing this as resolved.
