### ISSUE TITLE
Crafted Liquids Don't Prompt a Consume Option

### ISSUE THREAD

**Issue by SibilantScream** [CleverRaven/Cataclysm-DDA#43426]
# Describe the bug

Crafting a liquid used to prompt an option to consume right off, that option has disappeared leaving the store in a receptacle & pour onto ground options.

# Steps To Reproduce

1. Craft water
2. after finishing crafting it won't prompt you with consuming it right away

Version     0.E-5620-gc4627a8 (tiles)
Build        10973
OS            Win7 x64bits

**Comment by Ramza13** [comment]
Duplicate of #42226

**Comment by SibilantScream** [comment]
also noticed opening sealed non-wielded containers prompts you to put the content into a different container without the consume option in the same window it shows you when done crafting.

**Comment by RoyBerube** [comment]
SibilantScream - is that happening on latest experimental? The fix for that problem was merged last week.

**Comment by SibilantScream** [comment]
it was on 10973 & also on 10978
