### ISSUE TITLE
Vehicle Tank Diesel Goes to 0.0 L Instead of Disappearing

### ISSUE THREAD

**Issue by SibilantScream** [CleverRaven/Cataclysm-DDA#43428]
The first vehicle in an Armored Car (happens to have a 3rd tank installed, both 2nd & 3rd tank have JP8 fuel) is stuck with 0.0 Diesel in it, attempting to drain it onto the ground drops 250 diesel but the tank still reads 0.0 & no way to store lake water in it.

However, reloading the save makes the tank read 0.3 & empties normally when drained with a rubber hose (2nd pic).

Version     0.E-5620-gc4627a8 (tiles)
Build        10973
OS            Win7 x64bits

![image](https://user-images.githubusercontent.com/61993103/92133105-af877900-ee10-11ea-8226-9489e2ce2a65.png)
![image](https://user-images.githubusercontent.com/61993103/92133347-eeb5ca00-ee10-11ea-98c9-9e545813f513.png)

**Comment by Profit0004** [comment]
I also noticed this while running a vehicle off of lamp oil.
