### ISSUE TITLE
Game crashes when using the 'd' (full description of resulting item) function in the crafting interface.

### ISSUE THREAD

**Issue by Aphegis** [CleverRaven/Cataclysm-DDA#43425]
# Describe the bug

Game crashes after trying to filter the crafting recipes with the 'd' function. (Only the 'd' function is bugged).

![a2](https://user-images.githubusercontent.com/34956440/92124785-982a9a80-edd4-11ea-887d-c1ced3fda230.PNG)

# Versions and configuration

    Build: 10973
    Graphics Version: Undeadpeople
    Game Language: English [en]
    Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Mythological Replicas [nw_pack],
    DinoMod [DinoMod],
    Mythical Martial Arts [MMA],
    [DeadPeople] Zombie Revival Indicator [DP_ZOMBIE_REVIVAL_INDICATOR],
    No Fungal Monsters [No_Fungi],
    Disable NPC Needs [no_npc_food]
    ]

**Comment by ZhilkinSerg** [comment]
Cannot reproduce. Which search term did you use to cause crash?

**Comment by Aphegis** [comment]
Analyzing it better i noticed that it's not exactly a crash, it's a (really weird) 10-20 seconds freeze (that i previously assumed was a crash), it's probably happening because i'm playing the game in a old setup: intel i3 2120, and 4gb ram (really slow frequency), so probably this 'd' function is doing something weird in the code, that makes the game freeze for a while in slower processors, i assume? The other options works instantly. 

I created a fresh world (no mods) with a fresh character and the 'd' function only freezes for 2-3 seconds, i assume it's because of the drastically smaller amount of possible crafting recipes in this new character if compared to the previous one. Really weird, i dont experience this kind of behaviour in anything in the entire game using this old pc setup.

**Comment by jbytheway** [comment]
It's expensive to generate the description of every item in the game, so this is a known risk of this feature (that's why it warns you that it might be slow).  But perhaps we could improve the situation by at least giving some visual feedback as to progress.

**Comment by esotericist** [comment]
what this probably needs is for the algorithm to be resumable, and to be able to early-return after so many steps so that visual updates and refreshes can happen upstream while the search is still in progress.

**Comment by jbytheway** [comment]
Or we might be able to do it via a progress callback of some kind?
