### ISSUE TITLE
The Spear strap does not hold several weapons it should. 

### ISSUE THREAD

**Issue by Profit0004** [CleverRaven/Cataclysm-DDA#43448]
The Halberd and the lucerne hammer are supposed to be able to be holstered in the spear strap but cannot fit due to volume being lower than they are.  (Why is there a volume restriction on a strap anyhow? The object goes out both ends) 

I would just make the change myself pushing the volume up to 4 L and make a pull request I am not exactly sure how to make a conforming one. 

Using cataclysmdda-0.E-Windows_x64-Tiles-b10977

**Comment by wapcaplet** [comment]
You are correct, a simple increase of the spear strap pocket's "max_contains_volume" should be all that's needed. I agree 4 L or even 5 L would be reasonable.

https://github.com/CleverRaven/Cataclysm-DDA/blob/76117e4b5a8ab7fc1dd62f51bad950ac5167fb67/data/json/items/armor/sheath.json#L210
