### ISSUE TITLE
Crafting with sealed ingredients won't unseal the container

### ISSUE THREAD

**Issue by SaltGin** [CleverRaven/Cataclysm-DDA#43446]
# Describe the bug

When crafting items with items in the sealed containers like cans, glass jars, the container would remain sealed.

# Steps To Reproduce

1. Spawn a medium tin can of condensed milk.
2. Craft reconstituted milk with it.
3. The reconstituted milk crafted with the condensed milk inside the can, but the tin can remained sealed.

# Expected behavior

Crafting items should also open the sealed containers, just like the way the character consumes the items inside of it.

# Screenshots

Here is an example of this issue; 2 units of condensed milk have already been used in crafting, but the can remains sealed.
![image](https://user-images.githubusercontent.com/21094775/92198448-43fdd580-ee29-11ea-9e56-bb0b72c25919.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-5650-g379a306 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Slots [cbm_slots],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

**Comment by RoyBerube** [comment]
I'm on this. Have a fix working, but want to test it some more tomorrow.

**Comment by RoyBerube** [comment]
PR #43996 is fundamentally addressing unseal code, so I will hold off on submitting my solution for now.
