### ISSUE TITLE
"Made of" fileld in the item information often shows runtime error message as a part of the string when game language is set to Russian

### ISSUE THREAD

**Issue by eilaattwood** [CleverRaven/Cataclysm-DDA#43454]
# Describe the bug

"Made of" fileld in the item information often shows error message as a part of the string when game language is set to Russian

# Steps To Reproduce

1. Set game language to Russian
2. Observe some crafted items, that has "made of" field in the info, or observe my screenshots.
3. ...
4. PROFIT!

# Expected behavior

Clear description without error messages.

# Screenshots

![image](https://user-images.githubusercontent.com/28134842/92231907-40fcf680-eeb6-11ea-9fec-8ccf08db9979.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-5650-g379a306 [64-bit]
- Graphics Version: Tiles
- Game Language: Русский [ru]
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у NPC [no_npc_food],
    Blaze Industries [blazeindustries],
    Engineering essentials [EngineeringEssentials],
    Aftershock [aftershock],
    Расширение К.Р.И.Т. [crt_expansion],
    Mining Mod [Mining_Mod],
    Скорость от ловкости [speedydex],
    Характеристики за навыки [StatsThroughSkills],
    Характеристики за убийства [stats_through_kills],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Disable Bionic Slots [disable_cbm_slots]
]

# Additional context

**Comment by ZhilkinSerg** [comment]
If there is no error in English language, this should be resolved on Transifex.

**Comment by eilaattwood** [comment]
> 
> 
> If there is no error in English language, this should be resolved on Transifex.

In English everything looks fine. What should I do then? This error has been here at least for few weeks.

**Comment by GGgatherer** [comment]
There's also "clear" weather and "never mind" at the very end of message log.

**Comment by AMurkin** [comment]
It's fixed now.
PR #43471
Build https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-jenkins-b10981

**Comment by Night-Pryanik** [comment]
Closing then.
