### ISSUE TITLE
Bars of soap weigh nearly 8 pounds

### ISSUE THREAD

**Issue by mikeomni** [CleverRaven/Cataclysm-DDA#43452]
# Describe the Bug
One bar of soap with ( 40 ) charges weighs 7.94 pounds. A full toolbox weighs 7.76 pounds. Given that it takes 40 charges of soap to wash a single clothing item, I would take soap(40) to be a single bar of soap, and so it would seem that incredible weight is an oversight.

# Steps To Reproduce
Have both soap and eyes

# Expected behavior
Bars of soap usually weigh around 4-5 ounces.

# Screenshots
<img width="583" alt="Screen Shot 2020-09-04 at 1 10 23 AM" src="https://user-images.githubusercontent.com/6571414/92225780-973b4c80-ee58-11ea-9c9b-7202db17c090.png">

![Wait a minute](https://user-images.githubusercontent.com/6571414/92225831-a7532c00-ee58-11ea-99a0-1e7b0273eaa0.png)

# Versions and configuration
 - OS: OSX 10.15.6 Catalina
 - Game Version: 0.E-2 Stable
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: 

# Additional context

**Comment by CountAlex** [comment]
I really appreciate visual demonstration.

**Comment by DanteTorn** [comment]
I'd be willing to PR the change for this if we can decide what a reasonable weight for one unit of soap is, based on how many units denotes a full bar of soap.

**Comment by Theundyingcode** [comment]
@DanteTorn Some googling tells me that most soap bars are about 3.5 x 2.5 x 1 inches and, between 3.5oz and 4.5oz with the "normal" store stuff tending to be 3.5oz and the fancier/handmade stuff trending to 4.5oz.

Personally, I'd go with 3.5oz as our standard soap bar.  0.E stable (playing stable and, too lazy to swap branches and build an experimental)  soap bars have 10 charges according to the debug menu so, a charge would be 0.35oz or 9.922333 --> 10g.
