### ISSUE TITLE
Wield nail gun disappear while you have already wearing briefcase

### ISSUE THREAD

**Issue by WhelpCub** [CleverRaven/Cataclysm-DDA#43456]
# Describe the bug

In some situation, wield nail gun while player already wearing briefcase will cause error message, and nail gun disappear.

# Steps To Reproduce

1. Put briefcase and nail gun on the ground
2. Examine (e) the briefcase,
3. Wear (W) the briefcase.
4. Examine (e) the nail gun
5. Open inventory (i), choose nail gun, wield (w) it.

![image](https://user-images.githubusercontent.com/69908199/92246278-1e8bcd00-eef8-11ea-90af-1bdd1b481765.png)
![image](https://user-images.githubusercontent.com/69908199/92246305-28153500-eef8-11ea-86c4-80d671fba04a.png)

# Expected behavior

Display you cannot wear this item instead of error message

**Comment by Ramza13** [comment]
Could not reproduce this.  Correct message is displayed and nothing disappeared.

**Comment by anothersimulacrum** [comment]
No news in close to 3 weeks? Probably resolved.
