### ISSUE TITLE
Infinite cannabis

### ISSUE THREAD

**Issue by eilaattwood** [CleverRaven/Cataclysm-DDA#43453]
# Describe the bug

High quality distillate (heads) recipe yields 10 times more high quality distillate (tails) as byproduct than it should yield. In some variant it yuilds more tails than it consumes as an ingredient.

# Steps To Reproduce

1. Learn all the recipes.
2. Observe high quality distillate (heads) recipes in the crafting window.
3. Wish it was real.

# Expected behavior

Well, actually I quite like it the way it is now, but that's definitely an error in the Universe.

# Screenshots

![image](https://user-images.githubusercontent.com/28134842/92229980-fded5400-eeb2-11ea-8d2e-c2b2c8c3791c.png)
![image](https://user-images.githubusercontent.com/28134842/92230117-368d2d80-eeb3-11ea-89c4-976ec832162f.png)
![image](https://user-images.githubusercontent.com/28134842/92230163-502e7500-eeb3-11ea-8767-9b719a0529d2.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-5650-g379a306 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    Engineering essentials [EngineeringEssentials],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Mining Mod [Mining_Mod],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Disable Bionic Slots [disable_cbm_slots]
]

# Additional context
The recipes seems okay.
```
 {
    "type": "recipe",
    "activity_level": "fake",
    "result": "hi_q_distillate_heads",
    "category": "CC_CHEM",
    "subcategory": "CSC_CHEM_DRUGS",
    "skill_used": "chemistry",
    "difficulty": 4,
    "charges": 600,
    "time": "180 m",
    "byproducts": [ [ "hi_q_distillate_tails", 300 ] ],
    "batch_time_factors": [ 90, 1 ],
    "book_learn": [ [ "textbook_extraction", 4 ] ],
    "qualities": [ { "id": "FINE_DISTILL", "level": 1 } ],
    "tools": [ [ [ "vac_pump_on", -1 ] ] ],
    "components": [ [ [ "hi_q_crude_oil_filtered", 100 ] ] ]
  },
  {
    "type": "recipe",
    "activity_level": "fake",
    "result": "hi_q_distillate_heads",
    "id_suffix": "using lo_q_crude",
    "category": "CC_CHEM",
    "subcategory": "CSC_CHEM_DRUGS",
    "skill_used": "chemistry",
    "difficulty": 4,
    "charges": 533,
    "time": "180 m",
    "byproducts": [ [ "hi_q_distillate_tails", 267 ] ],
    "batch_time_factors": [ 90, 1 ],
    "book_learn": [ [ "textbook_extraction", 4 ] ],
    "qualities": [ { "id": "FINE_DISTILL", "level": 1 } ],
    "tools": [ [ [ "vac_pump_on", -1 ] ] ],
    "components": [ [ [ "lo_q_crude_oil_filtered", 100 ] ] ]
  },
  {
    "type": "recipe",
    "activity_level": "fake",
    "result": "hi_q_distillate_heads",
    "id_suffix": "using_tails",
    "category": "CC_CHEM",
    "subcategory": "CSC_CHEM_DRUGS",
    "skill_used": "chemistry",
    "difficulty": 4,
    "charges": 633,
    "time": "180 m",
    "byproducts": [ [ "hi_q_distillate_tails", 317 ] ],
    "batch_time_factors": [ 90, 1 ],
    "book_learn": [ [ "textbook_extraction", 4 ] ],
    "qualities": [ { "id": "FINE_DISTILL", "level": 1 } ],
    "tools": [ [ [ "vac_pump_on", -1 ] ] ],
    "components": [ [ [ "hi_q_distillate_tails", 1000 ] ] ]
  }
```

**Comment by Rjtheperson** [comment]
Can confirm that this recipe still violates the law of conservation of mass as of time of this post.

**Comment by Night-Pryanik** [comment]
Apparently high quality distillate (heads) recipe was removed some time ago, as there is not such recipe in latest experimental as of 23 November 2024.
