### ISSUE TITLE
Shady zombies have increased vision during the day depending on weather and time.

### ISSUE THREAD

**Issue by Saicchi** [CleverRaven/Cataclysm-DDA#43479]
# Describe the bug

Shady zombies have increased vision during the day depending on weather and time.

# Steps To Reproduce

1. Create a new default word, 91 days per season.
2. Spawn in a shady zombie at least 4 blocks away from the player. ( Use the debug mutations to remove your sound and smell if necessary )
3. Change time of the day to spring on day 17, 19, 31 or 61 ( I did not test all of them ).
4. Change the weather to clear
5. Move closer to the shady zombie and observe how he can see you from more than 10 blocks away during the day.

# Expected behavior

Shady zombies should have poor vision range during the day.

# Screenshots

![issue](https://user-images.githubusercontent.com/47158232/92299025-40e80f80-ef25-11ea-8508-b0c54499a9c8.png)

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.E-5641-g4e9b49558f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

Cloudy weather reduces their visibility range during the day but it is still much higher than the expected.
Zombie nightstalkers also seem to have the same issue.

**Comment by wapcaplet** [comment]
Confirmed; I can reproduce this in 0.E-5681-g2345fc2470

I started on the first day of Spring (day 61), at 8:00 am. I used the debug menu to spawn a shady zombie far away, and then set the weather to "Cloudy". The shady zombie could not see me from far away, but when they got within 4 tiles, they noticed me:

![image](https://user-images.githubusercontent.com/238395/92318318-b3113080-efc7-11ea-84d2-d0b7f49d7f91.png)

Setting the weather to "Clear", I found the shady zombie was able to see me from 39 tiles away:

![image](https://user-images.githubusercontent.com/238395/92318342-33379600-efc8-11ea-85b7-c11452b5bff2.png)

**Comment by Hirmuolio** [comment]
Does not seem to happen anymore.
