### ISSUE TITLE
Laundromats?

### ISSUE THREAD

**Issue by ianestrachan** [CleverRaven/Cataclysm-DDA#4347]
I noticed there are washers and dryers defined in the furniture list, but never used anywhere.

They could appear in people's basements or kitchens, but a laundromat building would be... well, I don't know about *interesting*, but certainly different.

Would probably be a source of:
* Bleach
* Shopping carts?
* Clothes
* Magazines
* Plastic bags, backpacks, messenger bags - whatever else people carry laundry in

**Comment by mugling** [comment]
Has since been implemented
