### ISSUE TITLE
Land Use Codes mode on the map spoils special features hidden in forest tiles.

### ISSUE THREAD

**Issue by drhead** [CleverRaven/Cataclysm-DDA#43476]
Several map features (like the central lab entrance and special cabins) are disguised as regular forest tiles -- they show as a dark green F named "forest".  Using Land Use Codes mode makes these features appear as a conspicuous white F.

# Steps To Reproduce

1. Debug reveal map
2. Turn on Land Use Codes mode (Shift+A)
3. Look in forests for white F forest tiles.

# Expected behavior

I would expect special features to be disguised in land use code mode as well as normal mode to prevent spoiling special features.

# Screenshots

![image](https://user-images.githubusercontent.com/1313496/92298332-c1067900-ef15-11ea-8a1b-251025ff6136.png) 

Just a normal forest? Wrong:

![image](https://user-images.githubusercontent.com/1313496/92298367-f7dc8f00-ef15-11ea-9b11-77f4961471a2.png)

The white F tile is a central lab entrance.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-5650-g379a306 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Crazy Cataclysm [crazy_cataclysm],
    Crazy Cataclysm - UndeadPeople Tileset [CrazyCataclysmUDP],
    Blaze Industries [blazeindustries],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    Aftershock [aftershock],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    No Fungal Monsters [No_Fungi],
    Prevent Zombie Revivication [no_reviving_zombies]
]

**Comment by Night-Pryanik** [comment]
Secret lab entrance issue resolved by #52191.
