### ISSUE TITLE
Boarding up a window that has glass effectively destroys the glass and curtains.

### ISSUE THREAD

**Issue by GhostWulve** [CleverRaven/Cataclysm-DDA#436]
If the player boards up a window that still has glass, when he removes the boards the glass is no longer there along with any curtains.  If possible, the board up window action could check which tile the window is (window, domestic, or empty) and create a similarily named boarded up version.

Currently the only way to save the window is to deconstruct it before it is boarded up and there is still a loss of nails (minor) in that process.

**Comment by BevapDin** [comment]
Wasn't this fixed by 28d8ab176e85bef6d5a2ff42ace084b50dbb0e4c (the player get the curtains back) and by Rivet, for example with 1d9dc73a4f1f342aba4e6774ed0237b76dbaeb3b (separate terrains for boarded with glass and boarded without glass).

**Comment by qbradq** [comment]
Confirmed that #2622 fixes this. Now when boarding up the window the sheets, heavy stick, long string and (4) nails are dropped on the ground. Smashing the boarded up window converts the tile into a smashed window with sharp glass and produces wood splinters and glass shards.

Please close this issue.

**Comment by Rivet-the-Zombie** [comment]
Thank you for going through our backlog like this, @qbradq; It really helps a lot!
