### ISSUE TITLE
Game watch modded for UPS won't activate, reports "batteries are dead"

### ISSUE THREAD

**Issue by kenneth-ellis** [CleverRaven/Cataclysm-DDA#43974]
# Describe the bug

I used a UPS conversion mod on a game watch, resulting in "game watch+1 (UPS)".  When I try to activate it to play a game, however, it says "The game watch+1 (UPS)'s batteries are dead" -- even though I have a fully charged UPS in my inventory, and all my other UPS modded electronics and tools work fine.

# Steps To Reproduce

1. Spawn a game watch.
2. Spawn a UPS conversion mod.
3. Spawn a UPS and load it with a charged heavy battery.
4. Install UPS conversion mod on game watch.
5. Activate game watch to play game, instead get "batteries are dead" error message.

# Expected behavior

game watch+1 (UPS) should successfully draw power from a charged UPS in inventory as any other UPS modded device does.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.E-5681-g2345fc2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Monsters [No_Fungi]
]

**Comment by bouchacha** [comment]
I've encountered this issue as well. I also encounter this issue with the handheld game system with a UPS conversion mod where it won't even let me active it because it doesn't have a charge. Those two devices have been the only ones affected (e.g. Mp3 player works just fine via UPS).

**Comment by zeropol** [comment]
I've the exact same ame issue ( with 0.E-7232-gee0a92c )

**Comment by Terrorforge** [comment]
I'm having the same problem with other items. RM13 combat armor is giving me the same error. I _was_ having problems with a Thermal Electric Suit as well, but I've been exiting and reloading while testing this problem, and now when I install the UPS mod it works fine?
