### ISSUE TITLE
NPCs completing their task when they should not

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#43982]
# Describe the bug

They stop reading a book as soon as you change z-level and skip a second in there.

# Steps To Reproduce

1. Load [save](https://drive.google.com/file/d/1PKqLl29ilK9ywSRwBPvpa3HdddDK7oUZ/view?usp=sharing), check that NPC nearby is reading.
2. Go downstairs (or use stepladder to get to the roof, doesn't matter).
3. Skip a turn.
4. See new message in the log, return to see she's now following you. Obviously not reading anymore.

# Expected behavior

They should not stop doing their task because I'm using a stair/stepladder/whatever.

# Versions and configuration
- OS: Windows 7
- Game Version: 0.E-5679-g446c750 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by GGgatherer** [comment]
Another case: same save, move away outside RB (take a Scouter and drive to the silos to the west, for example), then return. She will stop reading and start following without even noticing it in message log.

**Comment by GGgatherer** [comment]
Turns out it doesn't affect all activities. For example, NPC constructing something is not interrupted by PC leaving NPC's z-level, nor by leaving reality bubble.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/how-to-get-npcs-to-stay-put-while-doing-activities/25171/4

**Comment by natsirt721** [comment]
I'm still seeing this on 0.E-7424-gcbcf5fd with reading and sorting activities.

**Comment by Mrzjadacz** [comment]
Another case:
![image](https://user-images.githubusercontent.com/26396019/101259665-7372f580-372a-11eb-84fb-480686b74326.png)
NPC ordered to guard.
After some activity (after a few times I'm still not sure whether triggered after some time or on z-level change)
She drops her weapon, starts wielding army helmet, and enters "follow" mode.
Tried a few weapons, after she lost some permanently, tried giving sheaths, nothing helped.

**Comment by wapcaplet** [comment]
I am seeing this occur simply when moving outside of the NPC's line of sight.

- Assign NPC to read a book
- Walk around a corner - NPC follows

**Comment by EvanBalster** [comment]
This sort of stuff is still happening.  My NPCs will complete (ie, interrupt) their crafting tasks whenever I go to sleep nearby, go up or down a Z-level.

**Comment by ZhilkinSerg** [comment]
It is 3 years old bug. Would be better to create a new issue.
