### ISSUE TITLE
NPC dialogue bug (npctalk.cpp:dynamic_line)

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#43980]
# Describe the bug

Either the NPC is mad (without having whatever-schizo-is-called-now trait), or the dialogue is broken.

# Steps To Reproduce

1. Load [save](https://drive.google.com/file/d/1muwfWEzUMtaH91nWKqgt8YDQFkyRKoyB/view?usp=sharing)
2. Make Florine a follower.
3. Choose to talk about her "surviving the Cataclysm" story.
4. Behold.
Or just behold the screenshot below.

# Expected behavior

Either "i don't want to talk about it" or an actual story. Or she should have madness trait.

# Screenshots
![cataclysm-tiles_2020_09_06_09_04_25_062](https://user-images.githubusercontent.com/56833396/92316592-9523ea00-f020-11ea-9eac-970e59ede2da.png)

# Versions and configuration

- OS: Windows 7
- Game Version: 0.E-5679-g446c750 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Maleclypse** [comment]
Please mark this for Aftershock bugs.
