### ISSUE TITLE
getting around a faulty starter motor

### ISSUE THREAD

**Issue by stabliser** [CleverRaven/Cataclysm-DDA#43993]
# Describe the bug

Selecting a different fuel for a vehicle allows circumventing the faulty starter motor.
The engine seems to default to ON after selection, so taking control and driving is possible without fixing the starter motor 

# Steps To Reproduce

<!-- Steps to reproduce the behavior:
1. Find vehicle with a faulty starter motor that would otherwise run.
2. Examine vehicle controls
3. v Control vehicle
4. y Control Individual engines
5. enter, enter to deselect and deselect fuel type, escape
6. ^  take control of vehicle
You are now driving a vehicle that shouldn’t have started

# Expected behavior

Engine should stay in the same ON/OFF state that it was in before selecting a fuel

# Versions and configuration

 - OS: Windows 10
 - Game Version:  0.E-5679-g446c750 and some other prior experimental versions
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: StatsThroughSkills

**Comment by RoyBerube** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/8e8260f158e35f7d8047261d0fb30d3cbc3dc8d4/src/vehicle_use.cpp#L370-L372

This looks like the guilty line. Engine is being enabled without any checks.
