### ISSUE TITLE
Slowdown in 0.E upon going outdoors

### ISSUE THREAD

**Issue by Aenye** [CleverRaven/Cataclysm-DDA#43990]
Recently updated from 0.D (build 10192) to 0.E (build 10930) and started a new save in a lab scenario. Seeing normal / slightly slower performance (about 0.5-1s delay between moves) while still in the lab. Upon exiting the lab and going outside of the building, the performance plunges (each turn is followed by a delay of approx. 20-30s). Suspected new chunks being generated so explored and mapped the near surroundings (no further observable drop in performance), but the issue persists. Repeated on multiple saves and whenever the character is in a room without outside view, the performance is almost normal, but whenever there is a view outside or the character is outdoors, performance drops. This is significantly affected by the numbr of items I'm carrying around - the less, the better performance - empty inventory and outdoors results in a 15-20s delay between turns, while doing the same with 4 pages of inventory results in a delay above 1 minute between turns.

Tried changing the renderer (direct3d default to direct3d11, opengl and software (with and without hardware acceleration)), disabling all animations, dropping the force redraw option and even disabling the use of tiles (was using the MSX dead people tileset, but tried with the default ultica as well) and trying a save without any mods enabled - no noticeable changes. 

# Steps To Reproduce

1. Make any kind of character.
2. Go indoors / outdoors and compare real time delay between turns.
3. Same as above with empty / full inventory

# Expected behavior

No significant difference in performance regardless of whether character is indoors or outdoors . Perhaps this is due to some issues with the view range of the characters?

# Versions and configuration

- OS: Windows 7
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-5228-g8731f05 [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Dark Skies Above [darkskies],
    Magiclysm [magiclysm],
    Crazy Cataclysm [crazy_cataclysm],
    Mythical Martial Arts [MMA],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Dark Skies Above - UndeadPeople Tileset [DarkSkiesAboveUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

# Additional context

Attaching the config file - perhaps I've stupidly marked down some option, which results in the slowdown?

**Comment by Aenye** [comment]
Link for the configs - seems to be an issue with uploading them to git atm: [LINK](https://app.box.com/s/lvs51josoraiandvn663jw0bidez9wwo)

**Comment by Aenye** [comment]
Link for the configs - seems to be an issue with uploading them to git atm: [LINK](https://app.box.com/s/lvs51josoraiandvn663jw0bidez9wwo)

**Comment by matt32106** [comment]
Did you try the save without mods to compare?

**Comment by Aivean** [comment]
Please try the most recent build, there were major performance improvements in the last couple of days.

**Comment by Aivean** [comment]
@Aenye , I cannot reproduce the issue.  Can you please try reproduce the issue yourself using the latest build, and if it's still reproducible, attach the savefile?

**Comment by Aenye** [comment]
Sorry for the late reply. I'm seeing an improvement since build 11007 and upon testing with the recent build 11015, the difference between inside / outside seems to have become significantly smaller (still noticeable, but it's on the order of 1s indoors / 2-3s outdoors). New characters / worlds seem to be behaving this way as well.

**Comment by Aenye** [comment]
Sorry for the late reply. I'm seeing an improvement since build 11007 and upon testing with the recent build 11015, the difference between inside / outside seems to have become significantly smaller (still noticeable, but it's on the order of 1s indoors / 2-3s outdoors). New characters / worlds seem to be behaving this way as well.

**Comment by Aenye** [comment]
Sorry for the late reply. I'm seeing an improvement since build 11007 and upon testing with the recent build 11015, the difference between inside / outside seems to have become significantly smaller (still noticeable, but it's on the order of 1s indoors / 2-3s outdoors). New characters / worlds seem to be behaving this way as well.

**Comment by Aivean** [comment]
I think that the difference between indoor/outdoor indeed might be caused by having more stuff to render. However, having even 1 second delay between turns seem wild. 

Do you have any kind of non-standard setup with your hardware or software?  
Please answer following:
1. What kind of CPU do you have?
2. It says game build is 32 bits. Do you have 32 bit operation system/architecture?
3. Where did you get your build from? Did you compile if yourself?

**Comment by Aenye** [comment]
Thanks for the answer - my setup is fairly standard, if a bit old (hence I do not mind the 1s delays overly), as I'm running Cataclysm on a store-standard HP laptop.
1. AMD E-450 APU running at its standard 1.65GHz,
2. 32-bit Windows 7 version, as preinstalled on the laptop (there has been virtually no customisation done and barely any non-default software has been installed),
3. Downloaded the precompiled ones from the C:DDA website.

**Comment by Aivean** [comment]
@Aenye , is this issue still relevant after the recent performance improvements?

If yes, please attach the save file.
