### ISSUE TITLE
Wheat is so abundant, other forms of gathering food are severely underwhelming

### ISSUE THREAD

**Issue by acepleiades** [CleverRaven/Cataclysm-DDA#44007]
# Is your feature request related to a problem? Please describe.
Wheat is the second most common item in the game, surpassed only by rocks. It is unperishable, can be eaten raw for 500 calories, spawns in the common rural houses which usually don't have zombies, and makes all other sources of food gathering underwhelming in comparison.

# Describe the solution you'd like
The following solution is by no means the best solution, but the best that I could come up with:
Remove wheat from farm plots in rural houses. The untended wheat from farm plots would probably be eaten away by fauna. There are considerable amounts of wheat in silos, and breaking into them could be a rewarding, fun challenge (they're made out of metal walls).
Additionally, make zombies always spawn in all rural houses, and preferably a good amount of them. These zombies likely were attempting to flee the cities when the cataclysm happened. Currently, rural houses serve as safe spots akin to evac shelters. If zombies didn't make it to them, where are their owners?

# Describe alternatives you've considered
Alternatively, simply turning down the occurrence of rural houses with wheat farm plots substantially, by around 75%. There are various other rural houses that could appear instead. If only this is done, wheat would still be the 14th most common item in the game, which still sounds high to me, because the next most common food item is canned food, at 25th.

# Additional context
Top 10 most common items in the game, according to the UltiCa progress tracker:
![top10](https://user-images.githubusercontent.com/69649956/92335451-70099880-f06d-11ea-98e3-15f54f3525ed.png)

**Comment by Amoebka** [comment]
To be fair food is just generally infinite and easy to obtain in CDDA. I don't remember a single post-0.C run where my character starved or a single time somebody else mentioned starvation. Nerfing wheat yields won't really accomplish anything by itself, you will switch to infinite meat or infinite MREs instead. Not to mention in summer and autumn you can harvest infinite berries/fruits. And fishing is also an infinite risk-free source of food. You get the idea.

**Comment by anothersimulacrum** [comment]
Wheat is just too common, that's not really what should be being farmed in Massachusetts:

```
 Top Crops in Acres:
Forage (hay/haylage), all    79,004
Vegetables harvested, all    19,014
Land in berries              14,994
Corn for silage or greenchop 13,689
Cranberries                  13,555
```
```
All hay/forage/silage: 79004

All hay:                  57965
- Alfala hay:                10410
- Other dry hay:             47555
Haylage/Greenchop/Silage: 24131
- From alfalfa:               4964
- Not alfalfa:               19185

~20% alfalfa hay
Other dry hay would be things like clover,  fescue, lespedeza,   timothy,   Bermuda   grass,   Sudangrass, sorghum hay, and other types of legumes (excluding alfalfa) and tame grasses. For 2017, data include small grains  harvested  for  hay  including  barley,  oats,  rye, and wheat as well as wild hay.
```

**Comment by acepleiades** [comment]
While there are other forms of getting plenty of food, they require you to do something: to get meat, you need to kill a sizeable animal; to get MREs, you need to find them (and deal with enemies on your way to get them, like canned food); to harvest infinite berries/fruit, you need to survive the default season of the game; to fish, you need to get fishing rods or traps and level your survival skill. Gathering wheat from rural houses require you to do nothing, takes no skill, and is much better than all of that.

**Comment by Amoebka** [comment]
None of those methods require any skill, that's kinda where the problem is. Getting food in CDDA isn't risky, it's just tedious. Click a 1000 bushes to get bird/lizard eggs and wild vegetables (works in spring). Click on your fishing rod 1000 times to get fish. Click on a moose once with your free(tm) .223 milspec rifle and then collect 1000 rocks and 1000 logs to smoke it all.

As sad as it might be, wheat is a sanity saver because it allows to bypass a disfunctional game system completely.

**Comment by acepleiades** [comment]
Underbrush yields became very low on calories recently, I don't think just foraging is very efficient for getting food anymore. I just tend to do it to boost my health value. The fishing fast-forwards time like sleeping, and large fish like salmon can give a lot of meat,  so I don't think it's tedious if you have the items and skills. Killing a moose will provide you with meat for a very long time, so you won't have to do that again for a while.

If you can do one of these things once and become strong enough to raid the cities, you'll have infinite canned food, but at least there is a progression required to do so. Would it really be so bad if canned food became your next go-to food source if wheat was brought down to realistic levels?

**Comment by Profit0004** [comment]
Humans.  We have a lot of food options in the modern era.  I am not for even worrying about this, in real life if something like this happened it would be decades before food started getting low, and that is simply because cans and the warehouses started rusting through.  When you have a population that drops from millions to tens of people, the existing food supplies are more limited by their longevity than their amounts.

**Comment by acepleiades** [comment]
That is true, for things such as canned food, MREs, etc. There is a lot of canned food in the cities, and lots of MREs in military bases, the only problem being the zombies in the way to them. There is around 4x as much wheat than canned food in rural houses though, and no zombies guarding them, so not only is this unrealistic, it's unbalanced.

**Comment by Profit0004** [comment]
You can say it is unbalanced, but you cannot say unrealistic, maybe not wheat but field corn for example are often left in the fields over winter and a single field probably has several human lifetimes of calories.

**Comment by EvgenijM86** [comment]
Most of the wheat is hidden behind metal walls inside silos and is not accessible in early game, unless you are willing to smash your vehicle to get it. You can get more calories in early game by finding a swamp or a river - they have a TON of cattail stalks, 250 calories each. And late game food is a non-issue, because if you butcher a cow with a butchering kit and high survival skill it can give you enough meat to you for many month. I often end up with 1000+ chunks of meat and 200+ chunks of fat after visiting a single animal farm, and they generate quite often.

**Comment by EvgenijM86** [comment]
There if far too much food in Cataclysm for a single survivor and you don't really burn that much calories. Now that I think about it attempting mutations should burn A LOT of calories, because you are literally rebuilding your body. And some mutation should probably be only attempted if you are fat or very fat, unless you don't want to stuck with near-death hunger state and 50% penalty to speed for several days.

**Comment by Lovewyrm** [comment]
Wheat is simply imbalanced IRL, just like spears/polearms/guns. Some things are just better than others.

**Comment by acepleiades** [comment]
> You can say it is unbalanced, but you cannot say unrealistic, maybe not wheat but field corn for example are often left in the fields over winter and a single field probably has several human lifetimes of calories.

According to the list of crops farmed in Massachusetts, it would make more sense if the wheat was replaced with corn (or even more so, hay or vegetables), that's something we can agree with, but the fields are left untended, except for the occasional rural houses with dogs. For any season other than winter, the wildlife would love to eat it too, especially the mutant, giant kind.

> You can get more calories in early game by finding a swamp or a river - they have a TON of cattail stalks, 250 calories each. And late game food is a non-issue, because if you butcher a cow with a butchering kit and high survival skill it can give you enough meat to last you for many month. I often end up with 1000+ chunks of meat and 200+ chunks of fat after visiting a single animal farm, and they generate quite often.

The swamps usually have some dangerous animals in them, so I believe it's well balanced. Wheat from fields is still so much better though, and mostly free of risk.

> Wheat is simply imbalanced IRL, just like spears/polearms/guns. Some things are just better than others.

I agree, I don't want to nerf wheat. If stored without moisture, grain will last forever. The problem is that the game has too much wheat fields it's unrealistic. Rural houses usually have no zombies too, which seems like an oversight to me. These problems make all the mechanics for gathering food that have been programmed into the game unnecessary, which sounds like a loss for me.

**Comment by Profit0004** [comment]
I agree there should at least be some token zombies in those farm houses, as they would be the first infected with the Xewhatever because of their reliance on groundwater that is specifically infected according to lore.

**Comment by EvgenijM86** [comment]
> These problems make all the mechanics for gathering food that have been programmed into the game unnecessary, which sounds like a loss for me.
If you only care about calories then yes, but raw wheat does lower your morale. If you only consume raw wheat for calories you will get something like 30-50 morale reduction, which is a significant penalty to your skill growth. And if you want to cook wheat it can take significant early game time, because you would have to grind it manual with something like mortar and pestle. But maybe morale penalties from raw wheat should be harsher? I don't know.

**Comment by meelock** [comment]
I personally think wheat on its own should be inedible (because raw wheat is in something akin to shells on harvest, irl afaik), and make it harder to refine wheat into flour (requiring more steps, such as washing after mortering).

**Comment by anothersimulacrum** [comment]
That's a good point. Is it actually feasible to eat raw wheat without processing?

**Comment by EvgenijM86** [comment]
It is dangerous to eat raw wheat if you don't know what you are doing - https://en.wikipedia.org/wiki/Ergotism
Although, it is as much as dangerous to process raw wheat by yourself if you don't know of what you are doing. Someone who is not a farmer would probably not know about Ergotism.

**Comment by anothersimulacrum** [comment]
> Removal of ergot bodies is done by placing the yield in a brine solution; the ergot bodies float while the healthy grains sink.[

This sounds like something that should be done before raw grains are fit for consumption (well, without causing said poisoning).

**Comment by cainiaowu** [comment]
We can make Ergotism a thing like current mutant meat poison, you can eat it raw, but longtime consumption will lead to undesirable effect.

**Comment by Lovewyrm** [comment]
> This sounds like something that should be done before raw grains are fit for consumption (well, without causing said poisoning).

I'm all for that ...in a version where such a process can be left unattended.
So many dishes/crafts etc that shouldn't need supervision, or at least minimal supervision.

Perhaps there could be a hack, you know how fire burns out, and there are firewood fuel zones your character goes to?
And fire has fuel requirements to trigger the throwing of fuel into it?

Give crafts an attention fuel value that can be satisfied by automatic processes like crafting nearby, or via alerts if one doesn't do something automatic.

"You think about your (craft in process), which needs your attention"

And manually, it's a thing of various turn length, ranging from a few seconds (like stirring a pot) to some abstract(or concretely described) action like scooping scum or slag of some molten/boiling thing, etc"

**Comment by Rivet-the-Zombie** [comment]
>We can make Ergotism a thing like current mutant meat poison, you can eat it raw, but longtime consumption will lead to undesirable effect.

Most wheat isn't infected with ergot, and you can't just cook it out of it when it is infected.

**Comment by kholat** [comment]
Wheat should have a shelf life, makes no since for it to be infinite.
