### ISSUE TITLE
Mutations and CBM's should have less of a immediate impact

### ISSUE THREAD

**Issue by Giagantic** [CleverRaven/Cataclysm-DDA#44022]
I think this is probably something often discussed but as it stands Cataclysm-DDA has the big issue of being at it's hardest right out of the gate and then quickly becoming trivial in nature. One of the big contributors to this (there are others) is the impact that both Bionics and Mutations have on your character and in a game where realism is chased there is a strange aspect in regards to this impact. The issue is both of the aforementioned mechanics almost immediately bolster your character in ways that go against the very notion of realism and this also effects the flow of the game in such a way that it almost feels like you are skipping the ramping up from mid-game to end-game immediately.

I suggest that instead of being immediate, both Bionics and Mutations should be more gradual in nature as follows:

1. Mutations don't immediately grant their full effect and take several in-game weeks upwards to months to build up to what we have now. This feels more natural and realistic in several regards as these changes to our character are extreme and for it to immediately happen after taking a mutagen is extremely unrealistic. A caterpillar will pupate and change it's entire body structure over time before emerging as a butterfly, for our transhuman evolution we shouldn't be immediately going from Human to Transhuman in such as rapid, unnatural way. There should be various stages to mutating, dependent on the type of mutation you are receiving, and in a similar vein purifiers shouldn't just immediately remove said mutations especially the more body altering kinds. 

2. CBM's shouldn't cause Death, instead there should be longer term implications and maintenance required. First off, CBM's should have a fairly lengthy period of post surgery recovery as it isn't realistic to expect to gain the benefits of a bionic immediately when your body has just undergone a potentially extreme modification (dependent on the type of CBM). Modifications of the body should be followed by pain, and other issues including the increased potential for infections and should require post-opt care from you. This should then be followed by more maintenance required on your part to ensure the CBM is working optimally and the consequences of this being varied such as degrading performance and errors arising from poor care. 

This is just my 2 cents, but I feel that once you dip into either CBM's or Mutations you rapidly becoming stronger in ways that feel unnatural to the flow of the game. There are other such sources of this but most others have more restrictions (Armour requires maintainence and high skill in Fabrication or Tailoring, Guns require the right ammo type and there is really only 1 major glaring problem in this area coughturretshaving1500ammocough) but with both CBM's and mutations the restrictions are strange, obviously there are many negative Mutations which serve to balance it out but even with those in mind you will typically become a juggernaut of some sort and it is very easy to game the mutation system through closing CDDA without saving which would become much harder if they were to gradually reveal themselves. 

One of the main reasons for this suggestion was when upon retrospect I realized, I never once went from default spring to winter because by late spring-early summer I was a monster that could only be stopped through stupidity or turrets. This made me somewhat sad as the challenges each season should bring is integral to a survival game like CDDA. I realized that the flow was interrupted heavily by bionics and mutations and though I think they are both one of the most interesting aspect of the game they simply feel too gamey in how they are implemented.

**Comment by anothersimulacrum** [comment]
1. #28277 Addresses much of this.

2.
> CBM's shouldn't cause Death, instead there should be longer term implications and maintenance required. 

For the kind of risky surgeries that our current CBM installation is, there no real real rationale for it not being something that can kill you.

> CBM's should have a fairly lengthy period of post surgery recovery

Yep, totally.

Also relevant: #28273

**Comment by Giagantic** [comment]
> 
> 
>     1. #28277 Addresses much of this.
> 
> 
> > CBM's shouldn't cause Death, instead there should be longer term implications and maintenance required.
> 
> For the kind of risky surgeries that our current CBM installation is, there no real real rationale for it not being something that can kill you.
> 
> > CBM's should have a fairly lengthy period of post surgery recovery
> 
> Yep, totally.
> 
> Also relevant: #28273

Oh I think you misunderstand, I get that the death component of CBM installation is realistic but I also think it clashes with the game itself. I'd rather there be death brought by post-operation issues such as infection and sepsis, internal bleeding and so forth which could be somewhat managed by proper care and knowledge. I get that the whole death at installation is somewhat realistic, considering the invasive nature of it all but it is also a bit too RNG in nature, at least according to my perception. Then again my post is basically about other aspects of CBM's and Mutations rather then the death component, and is as such just a little part of my suggestion / feedback.

**Comment by Zireael07** [comment]
@Giagantic, that's a fairly good point re: instant death. Replacing instant death with sepsis/internal bleeding is a much better idea from gameplay point of view and I believe it works with the lore, too.

**Comment by anothersimulacrum** [comment]
Our current installation system is not planned to stick around for very long, but you can't really do much about wounds suffered while under anesthetic.

**Comment by Profit0004** [comment]
Well technically you could turn on your repair nanobot CBM 🤣🤣🤣

**Comment by Nandorianen** [comment]
Besides mutations taking time to manifest and your body healing after CBM-surgery there are other things to consider.
Even if you could grow an extra pair of arms or change your legs into tentacles instantly, this won't be a useful (or even useable) change until you learn how to handle your changed body. If your center of mass shifts or the way your limbs operate changes, I imagine you are going to be extremely disoriented, possibly fumbling and puking all over the place. Only after your low-level body skills that we all take for granted (like the ability to walk and manual dexterity) catch up you can start to get any use out of mutations.

This could be made a special skill, like "body affinity". By default you have level 10 of it, which means you are using your body normally. Mutations drop this skill depending on how severe they are. Skill levels lower than 10 should give you various problems depending on which mutations you have, but the skill should be trainable (maybe even naturally).
Or this could be a "skill" innate to a specific mutation, like "tentacle legs (5/10)".

Some bionics might also require you to get the hang of them before you get full benefits.
