### ISSUE TITLE
Fried Dandelion recipe is a bit wonky. 

### ISSUE THREAD

**Issue by Profit0004** [CleverRaven/Cataclysm-DDA#44025]
Fried Dandelion requires oil or butter but does not use any and the breading should absorb at least that much maybe more.  
The description also says it is deep fried but you cannot do that with a single charge of oil. 

The recipe should probably be changed to use one charge of oil or butter (or raw butter or ghee) and not just have it present. 
The description should also probably be changed to "Pan fried" or just "fried" as deep frying in a single charge of oil is impossible.

*A bit nit picky but should also require one charge of water or clean water to make the batter. 

Using version cataclysmdda-0.E-Windows_x64-Tiles-b10989

![bug5](https://user-images.githubusercontent.com/15096894/92411895-b7e4fa00-f117-11ea-8b3e-b8d735b2804a.png)

**Comment by Kmozcan1** [comment]
To add: Batter Fried Fish, Fried Morel Mushroom, Fried Burdocks and Fried Dandelions and Burdock recipes have the same issue (oil as a tool instead of component, battering doesn't increase the volume)

**Comment by RoyBerube** [comment]
`"//": "the cooking oil isn't supposed to be expended since you can recycle it after frying the dandelions",`

Looks like it is intentional. I agree that the oil should be used up by being absorbed in the breading.

**Comment by Profit0004** [comment]
The pull request does not actually fix all of it, only description.

**Comment by Profit0004** [comment]
Note: The full fix requires BOTH pull requests as the description and the recipe needed changing.
