### ISSUE TITLE
SMGs shouldn't have their own skill

### ISSUE THREAD

**Issue by Rogal-Dorn** [CleverRaven/Cataclysm-DDA#44029]
# Summary
Submachine guns are a niche weapon usually used either to plink targets (in the form of pistol caliber carbines) or by special forces/SWAT teams and similar operating in situations where overpenetration is a real issue and rapid rate of fire and low recoil are desirable. 
From the perspective of actually operating SMGs there are two broad categories; "normal" submachineguns such as the MP5 
![image](https://user-images.githubusercontent.com/52333807/92415113-75c2b500-f125-11ea-97a7-f526a5ace3f7.png)
These are held in more or less the same way as a rifle or carbine 
![image](https://user-images.githubusercontent.com/52333807/92415135-86732b00-f125-11ea-9fc0-4675d7ee0a8a.png)
with one hand on the pistol grip and the other on the handguard or foregrip. The magazine is locating in more or less the same location (forward of the trigger) and the most notable difference is that submachineguns fire pistol calibers. This breaks down a bit when you consider Pistol Caliber Carbines of which this AR is one
![image](https://user-images.githubusercontent.com/52333807/92415185-c89c6c80-f125-11ea-888c-6e06ddc1b49c.png)
and the HK SP5 (a semi-only version of the MP5) is considered. 
I argue that the difference between these is so little as to have no gameplay use. 
The other broad category of SMG are machine pistols. 
![image](https://user-images.githubusercontent.com/52333807/92415282-321c7b00-f126-11ea-8b6a-0684743c4576.png)
This is an SP5 in the MP5K configuration which is meant to be held away from the body like a pistol. 
![image](https://user-images.githubusercontent.com/52333807/92415324-5bd5a200-f126-11ea-8c5b-67fc98bbcfba.png)
This is a mac 10 which has a magazine well inside the pistol grip like most pistols do. Note that mac 10s can also come with wireframe stocks, these rules are not absolute. 

I would suggest that these criteria be followed to decide what skill a gun uses.
Is it meant to be fired from the shoulder? If yes it's either a rifle or a shotgun.
Does it usually fire multiple projectiles per round of ammunition used? It's a shotgun, otherwise it's a rifle.
Is it meant to be fired at arms length without the use of a stock? It's a pistol.
# Describe alternatives you've considered
Combining rifles and shotguns as well so the above is changed to;
Is it fired from the shoulder? It's a rifle
Is it fired at arms length? It's a pistol

# Additional context
I am unfamiliar with weapons tests so I do not know what this would entail other than deleting SMG tests. I presume the weapons that used to be SMGs would still need to be tested.

**Comment by kevingranade** [comment]
We can consider consider changing the name of the skill, but SMG covers actual submachine guns plus assault rifles and arguably machine pistols if they have a stock.

The rifle skill is more about handling a hunting rifle, sniper rifle or anti materiel rifle

**Comment by Rogal-Dorn** [comment]
I'm rather confused by your first statement, but your second gives me an idea.
SMG as a definition certainly does not cover assault rifles as assault rifles don't use pistol rounds. The two are very similar in handling as I mentioned, 
As for your second statement, "hunting rifle" or "sniper rifle" don't carry enough information to say whether they should be in separate categories or not. An AR-10 makes a fine hunting rifle but if you put a red dot sight on it it can perform the same role as an AR-15 albeit worse due to lower ammunition capacity, more recoil etc. The same thing can be said about the M14 which is used by many organizations as a dedicated marksman's rifle. I assume, and forgive me if I'm wrong, when you say "hunting rifle" you're assuming something that is bolt action and does not have a pistol grip, and when you say "sniper rifle" you thinking of something like an Accuracy International Arctic Warfare 
![image](https://user-images.githubusercontent.com/52333807/92419098-63eb0d00-f139-11ea-9b9e-8aac61a60a75.png) or another similar precision weapon usually mounted with a high power telescopic sight. There are absolutely different skills used to take shots with a rifle at 500+ meters with a single shot calculated shot vs rapidly taking shots within 100 meters or adjusting fire at intermediate ranges, but fundamentally using any long gun is very similar to using any other long gun. Working the action of a bolt-action rifle quickly and efficiently and taking repeat shots also requires separate skills from using a semi-automatic weapon.
I believe I have previously read about plans for long range/precision shooting skill/proficiency someone else has laid the groundwork for. 

Anyways, my suggestion and what you said seem to have similar hearts; semi-automatic shoulder fired firearms should generally speaking use the same skill regardless of if they're firing 9mm or 5.56. Do I understand that correctly?

**Comment by FuelType-Memes** [comment]
So basically you're proposing combining current skills into 2 categories:
[Long guns](https://en.wikipedia.org/wiki/Long_gun)
> Examples of various classes of small arms generally considered long arms include, but are not limited to: rifles, carbines, shotguns, muskets, blunderbusses, submachine guns, personal defense weapons, wall guns, and musketoons

[Handguns](https://en.wikipedia.org/wiki/Handgun):
> A handgun is a short-barrelled firearm that can be held and used with one hand. The two most common handgun sub-types in use today are revolvers and semi-automatic pistols, although other handguns like machine pistols and derringers also see infrequent usage.

Sounds reasonable

**Comment by WhelpCub** [comment]
Long guns divide into Long guns(Single/Burst) and Long guns(Full auto) will better?

**Comment by Rogal-Dorn** [comment]
> 
> 
> Long guns divide into Long guns(Single/Burst) and Long guns(Full auto) will better?

I could maybe see LMGs being a different skill but that's sort of stretching it. An M4A1 absolutely uses the same skills as an AR-15, however, when on semi auto. Changing skills because you changed the fire selector would be very strange.

**Comment by ANickelN** [comment]
The most accurate separation of firearms I can classify is into rifles, shotguns and handguns.  The original request is correct that the skills used to handle a rifle don't change that much dependent on barrel length and caliber, so having the submachine gun skill just seems like a waste.

**Comment by anothersimulacrum** [comment]
Is using a shotgun that different from firing a rifle?

**Comment by ANickelN** [comment]
A little bit yes, you have different sighting techniques and hold it differently than a rifle.  Most shotguns are loaded differently than most magazine loaded rifles and handguns too.

**Comment by Nandorianen** [comment]
I would say that changing skills used when switching fire modes would absolutely make sense, the same way switching from firing to using bayonette would. Precision-aiming over long distances sounds like a very different skill than managing recoil and hitting things with automatic fire.

Would this kind of differentiation make sense?
- Sniping (firing from the shoulder, focusing on careful aiming to make the most precise and impactful shots over long distances);
- general shooting (firing from the shoulder over medium distances, balancing between precision and speed);
- handguns? (short-range firing with extended arms?);
- hip-firing (short-range two-handed dakka);
- special weapons / launchers (where your general marxmanship skills don't matter).
Alternatively:
- shoulder-fire aiming;
- hip-fire aiming;
- recoil control.
Then use them and train them in different proportions with different weapons and fire modes.
