### ISSUE TITLE
morale hit on kill puppy or kitten

### ISSUE THREAD

**Issue by Jerimee** [CleverRaven/Cataclysm-DDA#44058]
# Is your feature request related to a problem? Please describe.
No

# Describe the solution you'd like
If you kill a puppy or a kitten, character morale is significantly lowered.  Unless you have trait **Psychopath**

# Describe alternatives you've considered
Maybe not just limited to pets, all infant animals?  Maybe extend trait exceptions to include "Prey Animal."

# Additional context
I don't intend, in the near future, to code this feature request myself.  Just volunteering the idea in case someone is interested.

**Comment by Theundyingcode** [comment]
This used to be the case for dogs but got removed as not everyone are exactly dog lovers especially since they could attack.

 Personally, i'd be more in favor of a "animal lover" trait that did this rather than applying it as default.

**Comment by Jerimee** [comment]
Good to know. Should I close this?
