### ISSUE TITLE
Cattail Jelly quest bugged pocket

### ISSUE THREAD

**Issue by danielkwinsor** [CleverRaven/Cataclysm-DDA#44066]
# Describe the bug

Cannot put liquid cattail jelly inside zipper bag

# Steps To Reproduce

Complete quest

# Expected behavior

quest reward

# Additional context

src/item.cpp:1103 [ret_val<bool> item::put_in(const item&, item_pocket::pocket_type)] tried to put an item (cattail_jelly) count (7) in a container (bag_zipper) that cannot contain it: pocket unacceptable because can't contain liquid

**Comment by Fris0uman** [comment]
zipper bag can contain liquid now
