### ISSUE TITLE
Candles, lighters, and inhalers not spawning with random charges anymore.

### ISSUE THREAD

**Issue by UndeadMoose** [CleverRaven/Cataclysm-DDA#44071]
# Describe the solution you'd like
Having candles, lighters, inhalers, matchbooks, and other items have random charges again. 

# Describe alternatives you've considered
Leaving them how they are in a black and white phase of either having a full charge or no charge whatsoever.

# Additional context
Seems odd that items are no longer spawning with random charges anymore. Wasn't sure if I should have put this as a bug report because I vaguely remember a PR getting merged (for lighters and candles) that made it so that items are either black and white with their charges (either 0/100 or 100/100). This also had the effect of making an asthmatic character slightly harder to play due to having full inhalers spawn at such a low rate. Seems weird from a realism perspective that there is no variation with charges on some of these items either.

**Comment by Tamiore** [comment]
Somewhat related, it's probably important to make sure that the solution to this shouldn't effect player's **starting** inventory, or at least shouldn't effect it as strongly. 
I.e. if you start with inhaler, you never randomly start with zero (or next to zero) charges left.

**Comment by wapcaplet** [comment]
Most items appear to be working correctly in 0.E-5845-g5247a5f3ee. Inhalers and lighters I am not sure about, but all the others you mention (and more) are spawning with random charges in my testing.

Visiting random house kitchens, I find candles, matchbooks, and markers are definitely getting random charges:
![image](https://user-images.githubusercontent.com/238395/92806589-60dd6000-f377-11ea-88cf-2e863d7bf578.png)
![image](https://user-images.githubusercontent.com/238395/92806875-9f731a80-f377-11ea-87a0-011b4fc78fb1.png)

Batteries and electronic devices are as well:
![image](https://user-images.githubusercontent.com/238395/92806693-76eb2080-f377-11ea-87fd-811921f72f05.png)
![image](https://user-images.githubusercontent.com/238395/92806933-ac900980-f377-11ea-97f2-d1775c2ab202.png)
![image](https://user-images.githubusercontent.com/238395/92807887-7dc66300-f378-11ea-8e99-66d159407416.png)

All the lighters I have seen so far were either full or empty. All the inhalers I could find were empty. Possibly I have not looked hard enough yet.
![image](https://user-images.githubusercontent.com/238395/92809449-dba77a80-f379-11ea-9026-1857ec64d75b.png)
![image](https://user-images.githubusercontent.com/238395/92807251-f11ba500-f377-11ea-83e9-4cfd48a82fd8.png)
![image](https://user-images.githubusercontent.com/238395/92809724-1d382580-f37a-11ea-9f09-051538b84fd5.png)

**Comment by UndeadMoose** [comment]
I'm trying the most current build and it looks like like random charges started appearing again. I'm not sure if something changed but I'm even seeing candles, lighters, and inhalers with random charges again. In earlier builds most items would either be empty or full. The only exception were guns.

**Comment by UndeadMoose** [comment]
I have also tried checking for items with charges that may do this.

* Spray cans like lighters are either spawning with empty or full charges
* Voltmeters are spawning with no batteries

Ill keep a lookout for anymore and add to the list.

**Comment by cwilkinson6** [comment]
I think this is because of item group entries lacking both the "charges-min" and "charges-max" properties. I haven't managed to track down where in the C++ code this is handled, but it's pretty easily verifiable through inhalers. Every possible spawn for them where those properties are not defined results in empty inhalers, but the one spawn where those are defined (inside of house bathrooms) results in inhalers with proper amounts of albuterol. It looks like there are two solutions to this: add those properties to every single appropriate item spawn or adjust the code that checks for those properties.

**Comment by KorGgenT** [comment]
according to the comment from undeadmoose on sept 10th, this issue is solved already. please let me know if i'm closing this in error.

**Comment by casswedson** [comment]
I was under the impression that this issue refers to most item spawn, items spawning with the same amount of charges or without charges or magazines etc thus my interest in adding more randomization to items/itemgroups, see #44713 #44654 #44629 #44592 #44554 there are still some places where items still spawn empty and/or full always, not sure if this is a good enough argument to keep this issue open but I wanted to finish this branch https://github.com/casswedson/Cataclysm-DDA/tree/more-rando basically the same as the other pull request I mentioned, but a bit bigger, that will fix some charge/magazine issues, npc inventories, and other misc things I felt this issue refers to, such as the warehouse at the military base always spawning tons of empty batteries.

![milbase](https://user-images.githubusercontent.com/58050969/101208741-9e811a80-3640-11eb-843f-1612931a6f93.png)
