### ISSUE TITLE
Repeated messages causing massive slowdown

### ISSUE THREAD

**Issue by UndeadMoose** [CleverRaven/Cataclysm-DDA#44075]
# Describe the bug

Certain messages like the one provided in the screenshot and others like "you see the fish dive into the water, the x fly's over the water cause massive slowdown. There are a lot of these messages in game.

# Steps To Reproduce

1. Go near anything that may cause these spammy messages

# Expected behavior

I shouldn't see constant new messages about me needing painkillers, fish diving into the water, ducks flying over the water, a Mi-Go screaming 4 z-levels down at the top of their lungs. Maybe the messages shouldn't generate a new message instead it something like "Your hands are shaking you need painkillers 999" even though this causes slowdowns too but considerably less than new messages being generated on the log.

# Screenshots

![Screenshot (3183)](https://user-images.githubusercontent.com/56947231/92555957-bf390e80-f2a3-11ea-8fc2-f6c194b714b5.png)

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-5791-gc9d731b
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: None

# Additional context

This is especially hell when you have a character addicted to any manner of things as you try to get comfy and read a book on how to make spaghetti and it takes 10 upwards to 20 minutes of irl time just to finish the book.

**Comment by ZhilkinSerg** [comment]
Please provide a save with an adddicted character nearby pond with fish and ducks.

**Comment by UndeadMoose** [comment]
Here you go

[Wentzville.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5193048/Wentzville.zip)

**Comment by CoroNaut** [comment]
Message spam slowing down the game has been an issue for years, perhaps it isn't so easy to come up with a solution.

**Comment by Aivean** [comment]
For clarity, log messages by themself don't cause slowdown, the slowdown is usually caused by processing whatever is producing these log messages (e.g. monsters).

In the attached save file I don't see any problem:
![image](https://user-images.githubusercontent.com/2865203/100685237-df232000-3330-11eb-9ebb-4c0a0c26bf8f.png)

It already is simulated at 3.5 IRL seconds / in-game hour on my machine, which is fast enough.
