### ISSUE TITLE
Ursine Vision nearsighted in all situation

### ISSUE THREAD

**Issue by WhelpCub** [CleverRaven/Cataclysm-DDA#44084]
# Describe the bug

As the description, nearsighted should be only when light. Result always as nearsighted.
Also without glasses when you choose Ursine Vision as start trait.

# Steps To Reproduce

1. Create a character with Ursine Vision
2. Skip to night time
3. Check the max sight
4. Wear glasses, check the max sight again

# Expected behavior

Can be 1 of them:

1. Change the Ursine Vision description, and add glasses when choose as start trait
2. Only nearsighted when direct light

# Screenshots

![image](https://user-images.githubusercontent.com/69908199/92625618-78770300-f2fb-11ea-9761-71bc769336bb.png)
![image](https://user-images.githubusercontent.com/69908199/92625764-a9efce80-f2fb-11ea-8b0b-7b3a16ee64e9.png)

# Additional context

Max sight of Ursine Vision is define from here:
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/character.cpp#L1984-L1986

**Comment by WhelpCub** [comment]
just check the code, seems this can check player is under sunlight or not
g->is_in_sunlight( pos() )

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/character.cpp#L5945

**Comment by wapcaplet** [comment]
Confirmed in master 5247a5f3, and I remember a playthrough from before 0.E that had this issue as well. I will look into a fix.
