### ISSUE TITLE
Bridges are generating incomplete

### ISSUE THREAD

**Issue by PapaPetro** [CleverRaven/Cataclysm-DDA#44085]
# Describe the bug
Been experiencing a few z-level bridge generations that are incomplete and unable to traverse. The bridges generate with a noticeable gap in the middle that drops directly to the z-level bellow, then the bridge continues with a ramp back up to the original z-level above and completes.

This renders vehicular traversal impossible over the bridge as the vehicle will crash at the drop off where this is no safe ramp going downward.

I've ran into a few of these so it has lead me to believe that this wasn't a one-off issue but a problem with bridge generation.

# Steps To Reproduce
Find a z-level bridge that crosses a river on the overworld across and try to traverse it.

# Expected behavior
Bridges have traditionally always generated as complete and traversable across rivers.

# Screenshots
![image](https://user-images.githubusercontent.com/29907309/92635929-982f0c80-f2a4-11ea-9dff-3a3d6110851c.png)

![image](https://user-images.githubusercontent.com/29907309/92637055-5737f780-f2a6-11ea-8677-214f96d614f1.png)

# Versions and configuration
 - OS: Win-7 x64
 - Game Version: 0.E-5791-gc9d7b1b
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded:  
  "dda",
  "no_npc_food",
  "magiclysm",
  "MMA",
  "blazeindustries",
  "No_Fungi",
  "stats_through_kills",
  "no_reviving_zombies"

# Additional context
Save file included.

[Bridge Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5197183/Bridge.Save.zip)

**Comment by PapaPetro** [comment]
Here is some more of the rest of the bridge segments.
![image](https://user-images.githubusercontent.com/29907309/92638141-d974eb80-f2a7-11ea-90e5-1c1d680301b4.png)
![image](https://user-images.githubusercontent.com/29907309/92638167-e265bd00-f2a7-11ea-96d9-567ce5b85f08.png)
![image](https://user-images.githubusercontent.com/29907309/92638202-ee517f00-f2a7-11ea-9eae-1c9d3d07af2b.png)
![image](https://user-images.githubusercontent.com/29907309/92638280-07f2c680-f2a8-11ea-86ce-b340152a4299.png)

**Comment by ZhilkinSerg** [comment]
Do you see it in a fresh world generated by last version?
