### ISSUE TITLE
Input delay is usually too low to input accent characters (^, ´, `,)

### ISSUE THREAD

**Issue by mqrause** [CleverRaven/Cataclysm-DDA#44082]
# Describe the bug

Using German qwertz keyboard layout.
To create accent characters, you need to input two keys. For example you press `^` and then `a` to create `â` or `^` and `space` to just create `^`. The input delay is usually set to 125ms, which means you need to input those two keys in extremely quick succession to create those characters.

It works normally in input fields like the name in character creation or the search when crafting, since those set the delay to -1, meaning infinite delay.

# Steps To Reproduce

1. Use a keyboard layout that has this issue
2. Try inputting the characters normally
3. Accents don't appear

# Expected behavior

Press two keys that combine into one character with an appropriate delay.

# Versions and configuration

- Game Version: 0.E-5799-gd2843c7920 [64-bit]
- German qwertz keyboard layout
- Symbol input mode (because key code assumes qwerty, so strange things happen anyway)

# Additional context

This also affects input outside of the game (like here for example) if the game is running in the background.

**Comment by ZhilkinSerg** [comment]
> This also affects input outside of the game (like here for example) if the game is running in the background.

That is quite strange. Which OS are you on?

**Comment by mqrause** [comment]
I'm on Win10 2004.

**Comment by Alienmen1** [comment]
Hello I just discovered I had this problem today.
O/S: Windows 10 professionnal 
French Canadian QWERTY Layout
I can do the accent on some letter only if I press them at the same time... and it persist outside of CDDA. I had to restart my PC to fix it

**Comment by mqrause** [comment]
> I had to restart my PC to fix it

Are you sure that was necessary? Simply closing the game _should_ be enough.

**Comment by Alienmen1** [comment]
Turns out you are absolutely right, closing CDDA fixes it. I assumed it was a problem with my computer at first, not CDDA...
It never crossed my mind that this problem and CDDA would be linked together. The very fact that I asked on the discord about this problem and found this bug is nothing short of a miracle

**Comment by mqrause** [comment]
Closing this since it stopped happening at some point.
