### ISSUE TITLE
Can't create new world!

### ISSUE THREAD

**Issue by pogoralex** [CleverRaven/Cataclysm-DDA#44086]
# Describe the bug

Recently reinstalled OS and CDDA from launcher, and tried to create new world , but nothing happens.
When i hit TAB after all the steps , the world didn’t appear in the list .

# Steps To Reproduce

To create world and after a character

# Screenshots

This is the message from the debug file:

Unable to create or open world[Лорд] directory for saving
22:42:27.418 : Log shutdown.

# Versions and configuration

 - OS: Win 10 x64
 - Game Version: tried both latest stable and many of experimental
 - Graphics version: Tiles
 - Ingame language: Russian
 - Mods loaded: no mods
 -->

# Additional context

<!-- Add any other context about the problem here.

Crash: if your problem refers to a crash, please add the following files to the "Additional Context" paragraph:
    - From the /config folder (you can zip them both together):
        - crash.log file.
        - debug.log file.
    - Your save file (zipped)

**Comment by ZhilkinSerg** [comment]
It is an environmental issue we cannot help you with other than giving an advice to install your game to a location you have write access to.
