### ISSUE TITLE
Getting review rights for RU translation branch of Transifex

### ISSUE THREAD

**Issue by akirashirosawa** [CleverRaven/Cataclysm-DDA#44095]
### Describe the bug
Long time ago I registered on the `transifex.com` to download the latest translations for the game. Then I began to find errors, typos in the game and immediately correct them on transifex. Started translating untranslated strings I encountered in the game. So by improving my own gaming experience, I improved it for everyone else. I do the same thing here on github, when I create PRs with fixes.

But now all lines on transifex are protected from editing. To make obvious fixes, every time I have to write to @CountAlex personal messages, which is not very convenient both for me and for him.

### Steps To Reproduce
Here are some recent examples of issues I've found:
```
#: src/item.cpp
#, c-format
msgctxt "components count"
msgid "%d x %s"
msgstr "%s x %d"
```
Messed up `%s` and `%d` (original, translation, fix):
<img width="397" alt="mop" src="https://user-images.githubusercontent.com/38557723/92704536-af7d0100-f35b-11ea-9005-aef166f302a8.png">
```
#: src/player_display.cpp
#, c-format
msgctxt "speed penalty"
msgid "Pain                -%2d%%"
msgstr "Боль                   -%2d%%"
```
The number of spaces is not the same as in the original (original, translation, fix):
<img width="688" alt="pain" src="https://user-images.githubusercontent.com/38557723/92705123-1f8b8700-f35c-11ea-988a-a59ce954a794.png">

Latin characters in Russian words and vice versa found using  regex `[A-Za-z][А-Яа-яËё]` or `[А-Яа-яËё][A-Za-z]`, revealed many typos. I formatted the results and sent @CountAlex in a personal message, although it would be much easier to fix them myself.
### Describe the solution you'd like
I'd like to get a `review` rights for RU translation branch to fix errors and typos, and (sometimes) adding a new translation. For convenience, I have created a new user associated with this github account with the same login and email as here.
### Describe alternatives you've considered
May also remove protection from all strings and leave only on 100% checked. There were no cases of trolling or same thing in the RU branch. I think that protection of all strings is not so necessary.
# Additional context
The transifex web interface is quite inconvenient and slow. Is there a workflow when you can perform translation in your favorite editor like `Sublime Text`/`VS code`/etc and then upload the translation file to the transifex using terminal?

**Comment by CountAlex** [comment]
@VlasovVitaly

**Comment by ZhilkinSerg** [comment]
and maybe @BrettDong

**Comment by BrettDong** [comment]
@VlasovVitaly has the permission to change user's roles on Transifex

**Comment by VlasovVitaly** [comment]
Hello.

I give you review rights. Strange... I can remember time when any string can be changed by anyone.

@BrettDong You should have same rights as i. I check this.

**Comment by VlasovVitaly** [comment]
Close issue when you can change strings.

**Comment by VlasovVitaly** [comment]
Btw, Second screenshots pack should be fixed in source code (NO space calculations in translated|source strings).

**Comment by akirashirosawa** [comment]
> Btw, Second screenshots pack should be fixed in source code (NO space calculations in translated|source strings).

I agree, I also thought about it, since `Full`/`Сытый` is translated without spaces and is displayed correctly. It is worth changing the code in the future.

**Comment by akirashirosawa** [comment]
> Close issue when you can change strings.

done

**Comment by BrettDong** [comment]
> @BrettDong You should have same rights as i. I check this.

I am a _Project Maintainer_ on Transifex that can read/write translation data, but cannot manage users' roles. I think you should be _Organization Administrator_ so you have full access to everything about the project on Transifex.
