### ISSUE TITLE
reloading a gun with a magazine sometimes causes an error

### ISSUE THREAD

**Issue by misterprimus** [CleverRaven/Cataclysm-DDA#44110]
# Describe the bug

reloading a gun with a magazine sometimes causes an error

# Steps To Reproduce

1. Reload wielded rifle with the 30-round STANAG mag in inventory.
2. Get error.

Additional info: looks like it happens when your inventory is full. I think the game tries to reload the wielded item, but the ejected mag ends up in your hands due to lack of inventory and the rifle moves somewhere else, so the game is trying to reload what you're holding and what you're holding is no longer the reloadable rifle.

# Expected behavior

No error.

# Versions and configuration

 - OS: Win7x64
 - Game Version: 0.E-5864-ga252c83
 - Graphics version: Tiles
 - Ingame language: Eng
 - Mods loaded: Only disable NPC needs

# Additional context
Save attached. **Rename extension to _.7z_ to use.**
[brokenreload.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5205941/brokenreload.zip)

Brand new game, btw. Not some old save from a year ago that I updated, so whatever is causing this will be happening to everyone I would imagine.

I'm not sure, but I think this is connected with reloading something with a mag that then ejects the empty mag and places it in your hands, which displaces your wielded item originally flagged to be reloaded.

UPDATE: Seems to also affect unloading of an ammo belt. Throws the error, generates the loose ammo, but the loaded belt remains, effectively cloning the ammunition.

**Comment by DalenTalas** [comment]
Confirming.

Issue noticeable since build #11176. To recreate:

1) Load attached save.
2) Enter the HMWVV to the right of the character.
3) Reloading the turreted M249 results in a SEGFAULT.

Also noticed earlier when trying to reload a wood crossbow with a bolt on the ground.

[Gladewater.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5577127/Gladewater.zip)

**Comment by DalenTalas** [comment]
Possibly related to #45545.

**Comment by RoyBerube** [comment]
This kind of problem was fixed in PR #45194. Unloaded magazines with a full inventory are now handled in a way that the weapon stays wielded. The situation that caused the bug is not allowed to happen now.

I should have added this one to the list of issues fixed on the PR but failed to notice it.
