### ISSUE TITLE
Taking a Firefighter Coat in the Armor Window Crashes

### ISSUE THREAD

**Issue by SibilantScream** [CleverRaven/Cataclysm-DDA#44115]
Wearing nothing but generic firefighter gear then taking the coat off (covering torso & arms) crashed the game.

Build 10998 Win7 x64

![image](https://user-images.githubusercontent.com/61993103/92958227-856a3280-f472-11ea-94aa-64778683b245.png)
![image](https://user-images.githubusercontent.com/61993103/92958234-88fdb980-f472-11ea-877b-825283a481f7.png)
![image](https://user-images.githubusercontent.com/61993103/92958243-8d29d700-f472-11ea-9df4-0edf46227b20.png)

**Comment by Night-Pryanik** [comment]
I think this should be resolved by #47648. Closing until reconfirmed.
