### ISSUE TITLE
Discrepancy between disassembly with proficency

### ISSUE THREAD

**Issue by danielkwinsor** [CleverRaven/Cataclysm-DDA#44123]
# Describe the bug

Displayed time to disassemble short string when you don't know fibers prof is 5*4 minutes, but actual time taken is 5 minutes.

# Steps To Reproduce

New char without prof
Get watch
View short string description
Disassemble short string

# Expected behavior

Expected either 5 minutes
OR 20 minutes and proficiency gain

# Additional context

#44089 

CC @I-am-Erk

**Comment by anothersimulacrum** [comment]
Should have CC'd me. I'll look into it, I thought I fixed this.

**Comment by I-am-Erk** [comment]
Disassembly shouldn't be shortened by proficiency in this case. We may need a flag to determine which behaviour is appropriate: with electronics for example, it should be affected.

**Comment by Night-Pryanik** [comment]
@anothersimulacrum any progress on this?

**Comment by kevingranade** [comment]
Looks like it was fixed, spawned with a random character, verified they had no fiber-related proficiencies, and attempted to disassemble string.
Menu said 5 minutes to disassemble and it actually took 5 minutes.
![Screenshot from 2023-12-19 10-39-44](https://github.com/CleverRaven/Cataclysm-DDA/assets/860276/3b3ccd43-c5ab-4355-b407-b168b35804d1)
![Screenshot from 2023-12-19 10-39-21](https://github.com/CleverRaven/Cataclysm-DDA/assets/860276/aaaf61aa-3e71-4d17-96dd-e2a0213868e9)
