### ISSUE TITLE
Vehicles expelling exhaust on a different z level

### ISSUE THREAD

**Issue by Kniotic** [CleverRaven/Cataclysm-DDA#44122]
# Is your feature request related to a problem? Please describe.
I wanted to create a walk-in freezer under my base, which was easy enough, just dig a small 3x3 and slap a powered vehicle cooler in there. Then I discovered that vehicle exhaust is a thing, and here is where the problem appears.
The hot and cold air produced by the cooler cancel each others out, so I obviously want to separate them. But with what the game lets me do currently (either that or I missed something), the only solution I can think of it to dig a long tunnel from my cooler, building a vehicle along the way, and putting a muffler at the end, hoping that the hot air doesn't reach back where my cellar is.

# Describe the solution you'd like
I was wondering if it would be possible to implement something like a muffler that releases smoke/air in the z level above it. So I could just dig a hole close to my cellar, put a grate on top, and have all the exhaust forced to come out of there, without it just amassing downstairs.

# Describe alternatives you've considered
Another idea I tried was to just dig another room close to the cellar, and release all the hot air in there, trapping it. Unfortunately all the vehicle parts I tried couldn't stop the hot air from passing through the crevice that connected cooler and muffler. 
If there was something like an insulating wall I could use to stop the hot and cold air from moving through, that would also solve my problem, even if in a slightly uglier way.

**Comment by ZhilkinSerg** [comment]
Use a ramp and span your vehicle across several different z-levels if you want too.

**Comment by Kniotic** [comment]
That probably would have worked as a solution, but unfortunately (from what I tried) you can't create a ramp from underground to the surface, because it requires shallow pits, that are impossible to dig underground (I think). If there was a way to create a down-heading ramp from the surface, then it could be done.

**Comment by Profit0004** [comment]
For now you can install a windshield between the sides of your vehicle and it will block the air movement.  Created my freezer room by doing this.   I agree it would be nice to have some form of multi-z "vehicles"

**Comment by ZhilkinSerg** [comment]
> 
> 
> For now you can install a windshield between the sides of your vehicle and it will block the air movement. Created my freezer room by doing this. I agree it would be nice to have some form of multi-z "vehicles"

Vehicles can already span across multple z-levels.
