### ISSUE TITLE
Making juice of rotten oranges result in 'edible' orange juice.

### ISSUE THREAD

**Issue by Xindage** [CleverRaven/Cataclysm-DDA#44125]
# Describe the bug
Being Saprovore make me immune to rotten food so i decided someday make a orange juice from some rotten oranges that i had around my base, and after finishing the juice well the result was a non-rotten juice, this was strange for me

# Steps To Reproduce
1. Make orange juice from rotten oranges

# Expected behavior
Expected rotten juice since the oranges was already rotten.

# Versions and configuration
- OS: Windows 7
- Game Version: 0.E-5859-g8e8260f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [Dark Days Ahead [dda],Disable NPC Needs [no_npc_food],Stats Through Skills [StatsThroughSkills]]

**Comment by danielkwinsor** [comment]
I had the same surprise on Old meat turned into meat jerky, or maybe it was smoked meat.
