### ISSUE TITLE
prevent essential items to drop from your inventory when doing "," for drop all

### ISSUE THREAD

**Issue by AHolmen** [CleverRaven/Cataclysm-DDA#44133]
# Is your feature request related to a problem? Please describe.
At times we all gather up lots of stuff in-game. It can be overwhelming at certain points when you have to manually drop all the stuff you don't need while skimming over what you want to keep in your inventory.

# Describe the solution you'd like
Make a shortcut for a new menu for inventory-items that you want to hinder from being dropped under the "," drop all command.

**Comment by irwiss** [comment]
, won't drop items marked favorite, does that help?

**Comment by AHolmen** [comment]
I didn't know about that one... Thanks!
