### ISSUE TITLE
Expand shoulder straps to all items, add wrist straps

### ISSUE THREAD

**Issue by Aivean** [CleverRaven/Cataclysm-DDA#44132]
# Is your feature request related to a problem? Please describe.

In my opinion it's inconsistent that you can attach shoulder strap to the fairly large guns, but you have no way of attaching it to other similar-sized items, such as crowbar, plank, or anything non-gun.

Additionally, in the real world, if you have a cordage, it's relatively easy to devise a way to tie unwieldy stuff together to carry it, while in CDDA if you have two items that don't fit in your pockets, you are limited to carrying only one of them at a time.

# Describe the solution you'd like

Expand the ability to attach shoulder straps to all (or perhaps, selected) items. 
Also, introduce wrist straps, that work similar to shoulder straps, but are weared around arms/hands and have higher encumbrance coefficient (don't outright prohibit their usage for large items, but penalize it).

# Describe alternatives you've considered

I was also thinking about going the opposite route, so that rope is used to create additional XL pockets in the bags (possibly via "clothing modification" menu), but shoulder strap solution seems easier to implement, as it utilizes current mod system.

# Additional context

If nobody jumps in on that and if there are no objections, I will take this on myself in a couple of days.

[Ohh, I've even found a relevant video! :)](https://youtu.be/h1ujcztYkjg)

**Comment by KashouC** [comment]
I agree with this and I've even contemplated just making alternate recipe and item variations of everything I want to be able to tie a rope to. Imo the (at least at a glance) easiest way, or at least most versatile way, would be to just expand mods to any item and simply apply mod slots to them. The issue I could see is if it creates unexpected behaviors if you for example create a custom armor or melee weapon and give it a mod slot that would give it increased range or something (scope etc), but honestly I don't really think it would be a real problem practically, as it's just up to what you add to the item.

**Comment by paulenka-aleh** [comment]
To a mop.

The one item you would like to have and sometimes carry around but which being 152cm cannot fit in 150cm longarm bags... As a survivor I definitely would cut 2cm off, accept that it doesn't fit well or attach strap to it, but I wouldn't be carrying it around in hands when I travel by foot.

**Comment by Mrzjadacz** [comment]
Possibly something based on item weight/volume.
In the future, it could be extended to allow clip hooks to e.g. wear a geiger counter strapped to the waist.
