### ISSUE TITLE
Magiclysm - Apprentice start scenario - Secret room door not activating

### ISSUE THREAD

**Issue by Savora** [CleverRaven/Cataclysm-DDA#44130]
# Describe the bug

Starting in the basement related to the wizard apprentice start, can't activate the trap located under the coat rack to cause the secret door to open.

# Steps To Reproduce

Start a new world with the wizard apprentice start, grab the coat rack and move it out of the way. Stand on the spot the coat rack was located.

# Expected behavior

The trap should trigger and cause a map_regen, turning the wall with the graffiti into carpet and a beaded door

# Versions and configuration

  - OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-5869-ga818624 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Cataclysm++ [Cata++],
    Alternative Map Key [alt_map_key],
    More Survivor Stuff [more_survivor_stuff],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by curstwist** [comment]
I confirmed this on build 11002.  the update_mapgen trap also doesn't work in the lab's shifting hallway in vanilla, so this isn't mod related.

It was working on build 10965 if that helps.
