### ISSUE TITLE
Activating autoclave pouches gives error, destroys whole stack

### ISSUE THREAD

**Issue by Nandorianen** [CleverRaven/Cataclysm-DDA#44147]
See title.
DEBUG: Failed to obtain target item
FUNCTION: void avatar_action::iuse_item(avatar&, item_location&)
FILE: src/avatar_action.cpp
LINE: 1016

# Steps To Reproduce

1. Get latest experimental, hit Play now.
2. Debug create a stack of autoclave pouches.
3. Activate, get error message, watch pouches melt before your eyes.

# Versions and configuration

- OS: Win 10
- Game Version: 0.E-5877-g963edfd [64-bit]
- Graphics Version: Tiles
- Game Language: English
- Mods loaded: 
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]

**Comment by wapcaplet** [comment]
I was unable to reproduce this issue in the same version 0.E-5877-g963edfda5d in a new game world.

Given pouches and a non-sterile CBM, using the `a`ctivation menu:
![image](https://user-images.githubusercontent.com/238395/93019549-face2400-f594-11ea-9243-e5395f9e21e9.png)

Correctly prompted to choose CBM to pack:
![image](https://user-images.githubusercontent.com/238395/93019553-002b6e80-f595-11ea-847c-ec45cc4a6816.png)

CBM successfully packed, remaining pouches remain:
![image](https://user-images.githubusercontent.com/238395/93019568-1802f280-f595-11ea-90c3-3b4ae758571b.png)

Activating pouch without any non-sterile CBMs to pack gives a message that I have no CBMs:
![image](https://user-images.githubusercontent.com/238395/93019582-2cdf8600-f595-11ea-8a16-c838922548f9.png)

Thinking maybe the location of the items has an effect, I tried dropping pouches and CBM on the adjacent tile, then activating - it still works as expected:

![image](https://user-images.githubusercontent.com/238395/93019711-ee969680-f595-11ea-99cc-66df7dfe0e79.png)

I see the same behavior whether I use the `a`ctivate menu, or select the item from `i`nventory and then `a`ctivate the pouch.

The lines of `src/avatar_action.cpp` from your reported error message come from a recent fix (#43406) for item activation from the inventory screen. Maybe there is some other special case of item-activation that I did not try which could lead to this error.

@Nandorianen Did you activate the pouch from the inventory screen, or from the `a`ctivate menu? And did you have any packable CBMs in your inventory at the time?

**Comment by Nandorianen** [comment]
@wapcaplet, I didn't think it's important, but I am activating things via advanced inventory screen. This way you'll get the error regardless of having any CBMs or not.
I tried activating autoclave pouch via 'a'ctivate command and through a simple inventory, and indeed it works then. This raises a question: why does it matter from which screen you activate the same function?

**Comment by wapcaplet** [comment]
> I didn't think it's important, but I am activating things via advanced inventory screen. This way you'll get the error regardless of having any CBMs or not. 
> (...) This raises a question: why does it matter from which screen you activate the same function?

Thanks, I did not even know it was possible to activate items this way - but I can confirm the same error when activating the pouches from the advanced inventory screen, and the whole stack of pouches disappears.

**Comment by l29ah** [comment]
Same problem when trying to use medical gauze from within the AIM.
