### ISSUE TITLE
Turning on scuba tank gives undefined item

### ISSUE THREAD

**Issue by 321nick** [CleverRaven/Cataclysm-DDA#44148]
# Describe the bug
I turned on a scuba tank that was filled with compressed air, 60 units. when i did, i got an error and an undefined item:

# Steps To Reproduce

1. spawn a player, find a naturally spawning scuba tank (spawning one in might work aswell but idk)
2. Try too activate
3. get an undefined scuba tank item instead of active one 

# Expected behavior

as is intended, you get a turned on scuba tank and can wade underwater without suffocating.... i think.. 

# Screenshots

 **If applicable**, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/19196462/93013674-afa61800-f578-11ea-8a5a-93c93e12075b.png)

Do not take a screenshot of the crashing window. Please provide the crash logs in the "Additional context"

# Versions and configuration

# Additional context
had a couple mods active, most are either from the updated Goatsmod compilation or packaged with the game by default
![image](https://user-images.githubusercontent.com/19196462/93013728-3529c800-f579-11ea-82cc-ebbc6ce6ba6c.png)

Crash: if your problem refers to a crash, please add the following files to the "Additional Context" paragraph:
    - From the /config folder (you can zip them both together):
        - crash.log file.
        - debug.log file.
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-5877-g963edfd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    Armor Up! Survivor Expansion [ArmUpSurvEx],
    Gun Cotton [guncotton],
    Homestead Instruments Inc. [homestead],
    Locked and Loaded [Locked_and_Loaded],
    MST Extra [MST_Extra],
    Pneumatic Guns [pneumatic],
    Private Defense [private_defense],
    PKs Rebalancing Goats edit [PK_REBALANCE],
    sees-player icon, retrodays [sees_player_retro],
    Bionic Slots [cbm_slots]
]

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5213788/debug.log)

    - Your save file (zipped)
[Morro Bay.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5213785/Morro.Bay.zip)

**Comment by Night-Pryanik** [comment]
Should be fixed by #47376.
