### ISSUE TITLE
Chris Isherwood mission dialogue loop crash

### ISSUE THREAD

**Issue by DanteTorn** [CleverRaven/Cataclysm-DDA#44143]
# Describe the bug

When getting the mi-go tower quest from Chris Isherwood, I asked him if he had any advice and then I got the "If you join up with me, we can go check it out, I want to see what they are doing" option, leading to "I'll do it!" again, which if you select causes the game to crash with this error:

 DEBUG    : strange: player is already assigned to mission 17

 FUNCTION : void mission::assign(avatar&)
 FILE     : src/mission.cpp
 LINE     : 215

# Steps To Reproduce

1. Talk to Chris Isherwood.
2. Take his quest.
3. Ask for advice.
4. Repeat dialogue choices
5. Game error and crash.

# Expected behavior

Dialogue tree shouldn't be able to loop like this.

# Screenshots

![image](https://user-images.githubusercontent.com/35230199/93009943-8f795780-f57e-11ea-879e-5ff05fcf425a.png)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Safe Autodoc [safeautodoc],
    Garden Pots [growable-pots],
    MST Extra [MST_Extra],
    Wild Living [WildLiving],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Mythical Martial Arts [MMA],
    Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
    Folding Parts pack [deoxymod],
    Whaleys Hair Mod (UDP Tweaks) [WHALEYHAIR_UDP],
    No Acid Zombies [No_Acid_Zombies],
    No Gasoline Boomers [No_Gasoline_Boomers-DANTE],
    No Fungal Monsters [No_Fungi],
    Classes and Scenarios Mod [more_classes_scenarios],
    Faster Stamina Regen [stamina_regen_buff],
    Simplified Nutrition [novitamins],
    Stats Through Kills [stats_through_kills],
    DinoMod Extended [DinoModExt],
    Whaleys Collectables [collectablemod],
    Armor Up! Survivor Expansion [ArmUpSurvEx],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Roadheader and other mining vehicles [Heavy miners]
]

# Additional context

I'm running Stable E and this may have been since fixed, but I couldn't find any issues relating to Chris Isherwood so I assume this is the first time it's come up.

**Comment by Relvl** [comment]
Same but with crash report dialogue

**Comment by LeahLuong** [comment]
There are many cases of accepting missions twice causing crashes, some resolved, some not. Whack-a-bug seems to be the preferred method of resolution rather than checking for this possibility when new missions are introduced or creating a circumvention for it such as ignoring the assignment of dupe active/failed/completed missions.

**Comment by RenechCDDA** [comment]
Can't reproduce on https://github.com/CleverRaven/Cataclysm-DDA/commit/c94dc0387513d5bba49eb7d74b2b51a7a4d8c4a0

It doesn't loop the dialogue, it properly exits.
