### ISSUE TITLE
PE070 "Raptor": Proposal

### ISSUE THREAD

**Issue by WhelpCub** [CleverRaven/Cataclysm-DDA#44149]
# Describe the bug

English is not my first language so I do not confirm it is wrong or not.
In the description in PE070, it said it is a proposal for focusing PE065.

1. It means it is a extended experiment on PE065, result in PE070.
2. Or the description wrong?

# Screenshots

![image](https://user-images.githubusercontent.com/69908199/93017962-1f5ee600-f5ff-11ea-9fec-d8b992549a6c.png)

**Comment by Amoebka** [comment]
As your own screenshot shows, PE065 is Chimera. It's a very unstable mutation strain, so presumably PE070 (Raptor) is their attempt at refining it. No error here.
