### ISSUE TITLE
8x40mm ammunition

### ISSUE THREAD

**Issue by CHJKDM51** [CleverRaven/Cataclysm-DDA#44159]
# Describe the bug
8x40mm HVP
8x40mm JHP
Have same stats.

# Steps To Reproduce
check 8x40mm ammunition.

# Expected behavior
Expected to have different stats.

# Screenshots

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-5882-g98879b8 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
Also "8x40mm caseless" and "8x40mm tracer" seems to have same stats.

**Comment by BrettDong** [comment]
Has been fixed:
| HVP | JHP |
|---|---|
|<img width="392" alt="螢幕截圖 2021-01-08 上午10 11 14" src="https://user-images.githubusercontent.com/21075502/104030750-da585400-5199-11eb-9bff-367239ad6b83.png">|<img width="394" alt="螢幕截圖 2021-01-08 上午10 11 27" src="https://user-images.githubusercontent.com/21075502/104030761-dfb59e80-5199-11eb-8ed2-11126e7558a8.png">|
