### ISSUE TITLE
Pocket bug happening to a weapon in a pile of clothes.

### ISSUE THREAD

**Issue by Proluiz** [CleverRaven/Cataclysm-DDA#44154]
# Describe the bug
I have no idea in what is happening but when i examine this pile of clothers in my feet the make prompt to a debug error screen.
"pocket unacceptable because holster already contains an item"

# Steps To Reproduce
1. Load the save.
2. Examine the floor at your feet.

# Versions and configuration
- OS: Windows 7
- Game Version: 0.E-5882-g98879b8 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [Dark Days Ahead [dda],Disable NPC Needs [no_npc_food],Stats Through Skills [StatsThroughSkills]]

# Additional context
[debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5214466/debug.zip)
[Shady Side.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5214467/Shady.Side.zip)

**Comment by wapcaplet** [comment]
Possible duplicate of #44158
