### ISSUE TITLE
RM11B scout rifle

### ISSUE THREAD

**Issue by CHJKDM51** [CleverRaven/Cataclysm-DDA#44158]
# Describe the bug
 DEBUG    : tried to put an item (8x40_10_mag) count (1) in a container (rm11b_sniper_rifle) that cannot contain it: pocket unacceptable because holster already contains an item

 FUNCTION : ret_val<bool> item::put_in(const item&, item_pocket::pocket_type)
 FILE     : src/item.cpp
 LINE     : 1102

# Steps To Reproduce
1) have "RM11B scout rifle" with "RMGP10 8x40mm stick magazine" in it.
2) open "i"nventory
3) select said gun
4) press enter

# Expected behavior

# Screenshots

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-5882-g98879b8 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
also same thing on m2010 esr with empty magazine:

 DEBUG    : tried to put an item (m2010mag) count (1) in a container (m2010) that cannot contain it: pocket unacceptable because holster already contains an item

 FUNCTION : ret_val<bool> item::put_in(const item&, item_pocket::pocket_type)
 FILE     : src/item.cpp
 LINE     : 1102

**Comment by Fosheze** [comment]
This seems to be an issue with multiple guns at the moment. Mainly I've had it happen with various pistols as well.

**Comment by wapcaplet** [comment]
Confirmed in 0.E-5926-g a883429 with the RM11B (`rm11b_sniper_rifle`)

It seems to occur only if the magazine is empty. When the magazine has at least one bullet, I can inspect the item from inventory with no errors. But if the magazine is empty, selecting the gun in inventory and pressing Enter gives the error

```
 DEBUG    : tried to put an item (8x40_10_mag) count (1) in a container (rm11b_sniper_rifle)
  that cannot contain it: pocket unacceptable because holster already contains an item
 FUNCTION : ret_val<bool> item::put_in(const item &, item_pocket::pocket_type)
 FILE     : src/item.cpp
 LINE     : 1102
```

**Comment by wapcaplet** [comment]
Same issue as #44247:

```
DEBUG : tried to put an item (ump45mag) count (1) in a container (hk_ump45) that cannot contain it:
pocket unacceptable because holster already contains an item
```

And #44091, happening with AR-15, coilgun etc.:

```
DEBUG : tried to put an item (mp5mag) count (1) in a container (hk_mp5) that cannot contain it:
pocket unacceptable because holster already contains an item
```
