### ISSUE TITLE
Minireactor plutonium duplication

### ISSUE THREAD

**Issue by Laeras** [CleverRaven/Cataclysm-DDA#44150]
# Describe the bug

Removing a minireactor that has plutonium charges in it from a vehicle, then unloading the reactor causes it to create a number of plutonium fuel cells equal to the charges in the reactor.  as each fuel cell item can be used to put 500 charges into the reactor when it is in a vehicle, this can be used to mass-generate fuel cells by removing and replacing the reactor.

This bug was found on version #11000, but I don't see anything in the changelogs that indicate that it would be fixed.

# Steps To Reproduce

Install minireactor onto a vehicle
fill with plutonium cells
remove minireactor from vehicle
unload
you now have many many fuel cells

# Expected behavior
I'd expect it to either give me the charge / 500 rounded down worth of fuel cells, as unloading it while it's in the vehicle does, or to give me nothing.  I expect it to do so because with its current behaviour, it can be used to make infinite plutonium cells

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-5869-ga818624 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Graphical Overmap [Graphical_Overmap],
    Alternative Map Key [alt_map_key],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Stats Through Kills [stats_through_kills]
]

**Comment by Melodeiro** [comment]
In older version you was getting the empty reactor after removing from vehicle.

Also if reactor is not empty, you can't install it in a car (says you have no reactor), so another solution is might be just banning user from unloading it, but you need to fix that issue first

**Comment by nulman** [comment]
just ran into this myself, it is still an issue
