### ISSUE TITLE
Sleeping should be faster.

### ISSUE THREAD

**Issue by Xindage** [CleverRaven/Cataclysm-DDA#44157]
# Describe the bug
Sleeping should be fast in game, because right now it's taking way too long, like i've discussed in the discord it took almost 18 minutes in real life just to the character wake up after being put to sleep it's actually way too much to just wait.

# Steps To Reproduce
1. Load the save.
2. Put the character to sleep.
3. Wait, I really mean to wait.

# Expected behavior
took at least 1 to 4 minutes at most.

# Versions and configuration
- OS: Windows 7
- Game Version: 0.E-5882-g98879b8 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [Dark Days Ahead [dda],Disable NPC Needs [no_npc_food],Stats Through Skills [StatsThroughSkills]]

# Additional context
Again the save when i was about to sleep.
[Shady_Side.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5214736/Shady_Side.zip)

**Comment by kevingranade** [comment]
Too nonspecific to address. We're working on performance and we don't need people reminding us of that without any additional details.

**Comment by kevingranade** [comment]
My bad, I was reading issues on my phone and didn't see the attached save.

**Comment by Aivean** [comment]
On my 2016 macbook pro with some of the latest optimizations it takes ≈16 RL seconds per 30 in-game minutes. So 8 hour sleep would be ≈ 4 minutes IRL. 

Here's the overview:
![image](https://user-images.githubusercontent.com/2865203/93025758-9d969a80-f5b5-11ea-988a-2746ff5bd34e.png)

Here is the expanded view (with small % times filtered out):
![image](https://user-images.githubusercontent.com/2865203/93025790-da629180-f5b5-11ea-957c-b32ebc1ad56e.png)

So, major dominators here are:
```
28.69 s   52.0%	23.00 ms	 	 game::monmove()
12.49 s   22.6%	125.00 ms	 	 map::process_items()
```

**Comment by Aivean** [comment]
Worth noting that since my previous measurement performance on this particular savefile improved by ≈25%. 

Previously one in-game hour was taking ≈32 seconds, currently it's ≈24 seconds.

**Comment by MerMerMerMer** [comment]
Here is a save file which I believe exhibits the same behavior. I am near a lab in the save, but the issue has been happening when not near a lab. It took 5 minutes to sleep through the night. I used to play on stable versions and the change from stable to experimental was jarring for wait times.
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5427168/save.zip)

Version.txt content:
Platform     : Windows
Graphics     : Tiles
Build number : #11106
Build version: 0.E-6961-g7ff5d41
Major version: 0.E

**Comment by Aivean** [comment]
@MerMerMerMer, I finally got to profile your save.
First thing to note, you're positioned above the lab and labs are notoriously slow, especially for monster simulation.

On my laptop waiting 6 hours results ≈16.5s / in-game hour in the (somewhat) current game version. 
Here are profiling details:
![image](https://user-images.githubusercontent.com/2865203/97052905-b9874780-1536-11eb-9bcd-3618648e8e03.png)

The good news are that we have some performance improvement planned (some of them mine, some from other people, like #45026)  that together bring the simulation down to 9.6s / in-game hour (on the same savefile, on my laptop). That's more than 40% improvement in simulation time. But it would be progressively harder to improve from there.

**Comment by kevingranade** [comment]
Oh I have plans for monmove()...

**Comment by Aivean** [comment]
So, with #45346 the original savefile is down to 11.2 s/hour:
![image](https://user-images.githubusercontent.com/2865203/98774312-9c100580-239f-11eb-884f-d52ab909d6ae.png)

**Comment by Aivean** [comment]
Ok, after the last bunch of NPC-related fixes we have a new record, ≈9.0s/hour

![image](https://user-images.githubusercontent.com/2865203/100494936-77d05a80-30fb-11eb-93a8-70f83457d5b7.png)

**Comment by leemuar** [comment]
Performance was improved significantly, not only for sleeping but every long action (like reading a book).
Should this still be opened?

**Comment by Night-Pryanik** [comment]
None of the savefiles in this issue are loadable anymore, but I conducted tests on new world. I debug-set fatigue to 1000 and made my character sleep in 23:00. He woke up in 09:00, after 14 IRL seconds
![изображение](https://user-images.githubusercontent.com/11132525/187916390-f4648159-655c-42c4-b21f-8fb4b10f5aab.png)
