### ISSUE TITLE
Examing an autodoc whit an NPC on couch result in bug.

### ISSUE THREAD

**Issue by Xindage** [CleverRaven/Cataclysm-DDA#44156]
# Describe the bug
Choosing to uninstall a bionic in a friendly npc results in a bug. "this item location type has no parent"

# Steps To Reproduce
1. Have a friendly npc in autodoc couch. (in my case a friendly proto cyborg)
2. Exaime the autodoc and choose to uninstall a bionic.
3. error.

# Additional context
Use the same save in #44154 there's my npc just in the north of the map you can put him ou couch and check.
[debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5214494/debug.zip)

**Comment by Fris0uman** [comment]
Basically caused by a hack introduced in https://github.com/CleverRaven/Cataclysm-DDA/pull/31498 that puts CBMs in your inventory to build the uninstall menu. But now that inventory is not a nebulous meta space the game is not happy about it
