### ISSUE TITLE
Purifier removes NPC starting traits

### ISSUE THREAD

**Issue by DanteTorn** [CleverRaven/Cataclysm-DDA#44175]
# Describe the bug

I was playing with mutating NPCs in a debug save and found that you can purify their starting traits away.

# Steps To Reproduce

1. Befriend an NPC who has traits/mutations.
2. Get purifier serum and a syringe.
3. Trade them the syringe then ask them to use the purifier serum in your inventory.
4. The NPC loses all their traits and mutations.

# Expected behavior

Starting traits are not meant to be purifiable on the player, so I would assume that NPCs are meant to work the same way.

# Screenshots

![image](https://user-images.githubusercontent.com/35230199/93038323-923a8200-f63c-11ea-9c0d-e8abd9fbf6af.png)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Garden Pots [growable-pots],
    MST Extra [MST_Extra],
    Wild Living [WildLiving],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Mythical Martial Arts [MMA],
    Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
    Folding Parts pack [deoxymod],
    Whaleys Hair Mod (UDP Tweaks) [WHALEYHAIR_UDP],
    No Acid Zombies [No_Acid_Zombies],
    No Gasoline Boomers [No_Gasoline_Boomers-DANTE],
    No Fungal Monsters [No_Fungi],
    Classes and Scenarios Mod [more_classes_scenarios],
    Faster Stamina Regen [stamina_regen_buff],
    Simplified Nutrition [novitamins],
    Stats Through Kills [stats_through_kills],
    DinoMod Extended [DinoModExt],
    Whaleys Collectables [collectablemod],
    Armor Up! Survivor Expansion [ArmUpSurvEx],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Roadheader and other mining vehicles [Heavy miners]
]

# Additional context

Another user tested this on latest experimental version for themself and it worked the same way.

**Comment by ZhilkinSerg** [comment]
> Starting traits are not meant to be purifiable on the player

I am not sure that is a valid assumption.

**Comment by DanteTorn** [comment]
Starting traits on a PC aren't normally purifiable, and I assumed that this is due to that being the "genetic default" that the purifier is meant to reset to. I have noticed some inconsistency with some mutations overwriting starting traits getting either purified into nothing or returning back into the starting trait though.

It's unclear to me what is intended and what is a bug about these things. All I do know is that starting traits aren't purifiable on their own on the PC but they are on NPCs which seems like an inconsistency that may or may not need to be addressed.

**Comment by DoctorVanGogh** [comment]
Chiming in here: **Every** version of the wiki on Mutations *since the very first* had some version of "Purifier does not remove starting stuff".

http://cddawiki.chezzo.com/cdda_wiki/index.php?title=Mutation

*Current*:
> purifier won't remove any starting traits, positive or negative, that you selected when building your character

*2013 version*:
> Note, that purifier will not remove a trait that you took upon character creation

Either the wiki was always wrong, or sometime during development it was decided that this was no longer true. In that case the wiki deserves an update.

**Comment by ZhilkinSerg** [comment]
The wiki is not a reliable source just because it has less people working on it than on development. It could be correct, but there is not guarantee.
