### ISSUE TITLE
Incorrect recipe corruption with large savegame

### ISSUE THREAD

**Issue by danielkwinsor** [CleverRaven/Cataclysm-DDA#44184]
# Describe the bug

Recipe for Hemostatic Powder corrupted, see savegame at end

# Steps To Reproduce

Load save
View hemo powder recipe

# Expected behavior

Recipe contains ammonia / lye powder

# Screenshots

<img width="950" alt="hemostaticPowder" src="https://user-images.githubusercontent.com/2822992/93151625-4b3aa400-f6b1-11ea-81ba-8ed76bdb5e94.png">

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-5924-gc631331 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Alternative Map Key [alt_map_key]
]

# Additional context

I can stop bloodloss with water :D 

Very large map, probable memory corruption.  Reproducible, which tells me it's not likely a threading issue.

[New Hartford - 30AnvilCreated.7z.003.renameto7z.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5221839/New.Hartford.-.30AnvilCreated.7z.003.renameto7z.zip)
[New Hartford - 30AnvilCreated.7z.001.renameto7z.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5221840/New.Hartford.-.30AnvilCreated.7z.001.renameto7z.zip)
[New Hartford - 30AnvilCreated.7z.002.renameto7z.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5221841/New.Hartford.-.30AnvilCreated.7z.002.renameto7z.zip)

**Comment by danielkwinsor** [comment]
rename to .7z.001, .002, .003

**Comment by ZhilkinSerg** [comment]
Recipe details aren't saved in savegames. What you see on screenshot is recipe from #42589.

**Comment by anothersimulacrum** [comment]
The recipe's JSON definition is just set up incorrectly.

**Comment by danielkwinsor** [comment]
Alright, sounds correct.  I just thought it was corruption because I loaded up a different savegame in order to compare.
