### ISSUE TITLE
Enable randomize button in character creation traits menu

### ISSUE THREAD

**Issue by KashouC** [CleverRaven/Cataclysm-DDA#44182]
I enjoy making characters with randomized scenarios, professions, and traits in a controlled environment, letting me skip an option that doesn't work for me. This is to create roleplaying experiences and thanks to the negative traits it's a rather powerful tool to add some depth to characters, but unless you do a full randomization you have to manually randomize it by using some kind of RNG generator and just counting the total amount of entries. Due to there being mutations and other special starts and professions it's hard to just use the full randomization with edits as a work around.

All I'd want is to enable the randomize button [*] as it works in scenarios and professions, but in the traits menu so it's easier to roll random entries in each column.

**Comment by ZhilkinSerg** [comment]
Related to #37869
