### ISSUE TITLE
Translocator Gate on the vehicle

### ISSUE THREAD

**Issue by linonetwo** [CleverRaven/Cataclysm-DDA#44194]
# Describe the solution you'd like

Add a buildable vehicle part that is a translocator gate, so we can travel in the car, and portal between home and the moving frontier.

# Describe alternatives you've considered
Maybe add a spell to teleport to a vehicle?

# Additional context
This may balance the explore part and also the base building part, encourage the player to do both of them.

Currently every time you translocate to home, you have to abandom the car you drived last time...

**Comment by Zireael07** [comment]
Mod content rather than core IMHO - maybe for Aftershock or Magiclysm, depending on whether you want to fluff it as scifi or magic.

**Comment by linonetwo** [comment]
Yeah, I was looking at Magiclysm.

I didn't know there is a working scifi version of translocator gate...

**Comment by linonetwo** [comment]
@KorGgenT Can you consider this again? I think if we have this we can encourage the user to do both vehicle building and base construction and map exploration.

If we can't deconstruct Translocator Gate (yes, we can only destroy it), and can't have a mobile Translocator Gate, then it would be embarrassing that:
when we travel a distance, and we translocate back home, then we have to abandom our car in the far distant...

**Comment by linonetwo** [comment]
https://www.reddit.com/r/cataclysmdda/comments/c5pvw8/psa_translocators_in_magiclysm/es3espb?utm_medium=android_app&utm_source=share&context=3

I can see the feature request 1 yr ago...

**Comment by KorGgenT** [comment]
> But every time you translocate home you lost a car, that is unacceptable

The correct answer is not to make a translocator gate to put on a car, the correct answer is to allow the translocate spell to translocate your car.

**Comment by linonetwo** [comment]
> the correct answer is to allow the translocate spell to translocate your car.

that is fair, hope we can have this.

**Comment by linonetwo** [comment]
> allow the translocate spell to translocate your car

Not the same case I think, because this will make it hard to drive back to the location you just explored.

I will be nice to have both!
