### ISSUE TITLE
Crash in item assignment operator called from npc::wield_better_weapon()

### ISSUE THREAD

**Issue by anothersimulacrum** [CleverRaven/Cataclysm-DDA#44196]
# Describe the bug
The game crashes.

# Steps To Reproduce
Load this save
[crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5226364/crash.zip)
Don't interrupt the in-progress waiting, just keep waiting.
Game crashes.

# Expected behavior
Game does not crash.

# Versions and configuration
- OS: Linux
    - OS Version: Arch Linux, kernel version 5.8.5
- Game Version: 0.E-5975-g0fc6ebb6e7 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
    debug_write_backtrace(std::ostream&)
    …/src/debug.cpp:823
    log_crash(char const*, char const*)
    crash.cpp:?
    signal_handler(int)
    …/src/crash.cpp:117
    ??
    ??:0
    addr2line: DWARF error: could not find variable specification at offset 18bb06
    favorite_settings
    …/src/item_pocket.h:75
    item_pocket
    …/src/item_pocket.h:38
    void __gnu_cxx::new_allocator<std::_List_node<item_pocket> >::construct<item_pocket, item_pocket const&>(item_pocket*, item_pocket const&)
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/ext/new_allocator.h:150
    void std::allocator_traits<std::allocator<std::_List_node<item_pocket> > >::construct<item_pocket, item_pocket const&>(std::allocator<std::_List_node<item_pocket> >&, item_pocket*, item_pocket const&)
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/alloc_traits.h:512
    std::_List_node<item_pocket>* std::__cxx11::list<item_pocket, std::allocator<item_pocket> >::_M_create_node<item_pocket const&>(item_pocket const&)
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/stl_list.h:637
    void std::__cxx11::list<item_pocket, std::allocator<item_pocket> >::_M_insert<item_pocket const&>(std::_List_iterator<item_pocket>, item_pocket const&)
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/stl_list.h:1912
    void std::__cxx11::list<item_pocket, std::allocator<item_pocket> >::emplace_back<item_pocket const&>(item_pocket const&)
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/stl_list.h:1227
    void std::__cxx11::list<item_pocket, std::allocator<item_pocket> >::_M_initialize_dispatch<std::_List_const_iterator<item_pocket> >(std::_List_const_iterator<item_pocket>, std::_List_const_iterator<item_pocket>, std::__false_type)
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/stl_list.h:1840
    list
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/stl_list.h:738
    item::item(item const&)
    ??:?
    item
    …/src/item.cpp:489
    addr2line: DWARF error: could not find variable specification at offset 12818f
    addr2line: DWARF error: could not find variable specification at offset 18e4da
    addr2line: DWARF error: could not find variable specification at offset 18e23e
    addr2line: DWARF error: could not find variable specification at offset 1ea297
    std::_List_node<item>* std::__cxx11::list<item, std::allocator<item> >::_M_create_node<item const&>(item const&)
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/stl_list.h:641
    void std::__cxx11::list<item, std::allocator<item> >::_M_insert<item const&>(std::_List_iterator<item>, item const&)
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/stl_list.h:1912
    void std::__cxx11::list<item, std::allocator<item> >::emplace_back<item const&>(item const&)
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/stl_list.h:1227
    void std::__cxx11::list<item, std::allocator<item> >::_M_initialize_dispatch<std::_List_const_iterator<item> >(std::_List_const_iterator<item>, std::_List_const_iterator<item>, std::__false_type)
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/stl_list.h:1840
    list
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/stl_list.h:738
    item_pocket
    …/src/item_pocket.h:38
    void __gnu_cxx::new_allocator<std::_List_node<item_pocket> >::construct<item_pocket, item_pocket const&>(item_pocket*, item_pocket const&)
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/ext/new_allocator.h:150
    void std::allocator_traits<std::allocator<std::_List_node<item_pocket> > >::construct<item_pocket, item_pocket const&>(std::allocator<std::_List_node<item_pocket> >&, item_pocket*, item_pocket const&)
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/alloc_traits.h:512
    std::_List_node<item_pocket>* std::__cxx11::list<item_pocket, std::allocator<item_pocket> >::_M_create_node<item_pocket const&>(item_pocket const&)
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/stl_list.h:637
    void std::__cxx11::list<item_pocket, std::allocator<item_pocket> >::_M_insert<item_pocket const&>(std::_List_iterator<item_pocket>, item_pocket const&)
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/stl_list.h:1912
    void std::__cxx11::list<item_pocket, std::allocator<item_pocket> >::emplace_back<item_pocket const&>(item_pocket const&)
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/stl_list.h:1227
    void std::__cxx11::list<item_pocket, std::allocator<item_pocket> >::_M_initialize_dispatch<std::_List_const_iterator<item_pocket> >(std::_List_const_iterator<item_pocket>, std::_List_const_iterator<item_pocket>, std::__false_type)
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/stl_list.h:1840
    list<std::_List_const_iterator<item_pocket>, void>
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/stl_list.h:806
    std::__cxx11::list<item_pocket, std::allocator<item_pocket> >::empty() const
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/stl_list.h:1056
    std::_List_iterator<item_pocket> std::__cxx11::list<item_pocket, std::allocator<item_pocket> >::insert<std::_List_const_iterator<item_pocket>, void>(std::_List_const_iterator<item_pocket>, std::_List_const_iterator<item_pocket>, std::_List_const_iterator<item_pocket>)
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/list.tcc:138
    item::operator=(item const&)
    ??:?
    item_contents::operator=(item_contents const&)
    …/src/item_contents.h:35
    item::operator=(item const&)
    …/src/item.cpp:492
    npc::wield(item&)
    …/src/npc.cpp:1164
    npc::wield_better_weapon()
    ??:?
    npc::move_pause()
    …/src/npcmove.cpp:2699
    npc::execute_action(npc_action)
    ??:?

Way down the line, it crashes calling and item_pocket::favorite_settings::favorite_settings

**Comment by sparr** [comment]
From a Discord user:

In npcmove.cpp the npc::wield_better_weapon method looks for a better weapon with a lambda and if it finds one calls npc::wield in npc.cpp. To wield an item the npc needs to unwield whatever they're wielding first which happens in npc::stow_item.
In the case where it crashes, they wield an item they can wear that also contains the item they want to wield.
I'm pretty sure this will only break if the wielded item contains the item they want to wield, but I didn't look into it deeper. Might break only for wearable containers, might break for any containers.
But the reference to the item they want to wield will be gone when npc::stow_item was called in npc::wield.
