### ISSUE TITLE
Death screen tombstone shows time since midnight on first day instead of start time

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#44206]
When you die your tombstone says how long you survived. It counts from midnight the morning of your first day, rather than the time you started.

# Steps To Reproduce

1. Start a game.
2. Die ASAP

# Expected behavior

Tombstone says you survived a few seconds or minutes, rather than the 8 hours (with default settings) it currently says.

**Comment by wapcaplet** [comment]
Confirmed in 0.E-5926-ga883429bdd by starting a new game and pressing `QYY` to commit suicide. The tombstone says I survived for 8 hours:

![image](https://user-images.githubusercontent.com/238395/93335128-3a8a4b00-f7e3-11ea-916b-3955a917e112.png)
