### ISSUE TITLE
Sidebar panels Needs and Needs_Alt both enabled by default

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#44204]
The default sidebar configuration has both the Needs and Needs_Alt panels enabled, which leads to duplicated rows and wasted screen space.

# Steps To Reproduce

1. Build CDDA from git
2. Run it with no pre-existing config
3. Start a game

# Expected behavior

Only one of Needs or Needs_Alt are enabled, so Pain, Rest, Heat etc are only shown once

# Screenshots

https://i.imgur.com/0Z9LiMv.png

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.E [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex]
]

# Additional context

I used the Arch aur/cataclysm-dda-git package to build the source from git. There is a small chance this introduced a patch without documenting it.

**Comment by wapcaplet** [comment]
Confirmed in 0.E-5926-ga883429bdd by removing my `config` directory and loading a game.

![image](https://user-images.githubusercontent.com/238395/93335585-ee8bd600-f7e3-11ea-9a8a-8b045a1c63dc.png)

![image](https://user-images.githubusercontent.com/238395/93335495-c56b4580-f7e3-11ea-863e-f1403388075c.png)

This appears to have been introduced by commit 0fd4cc444b4, and should be easy to fix by changing the last argument `true` to `false` in this line of `initialize_default_label_panels`:

https://github.com/CleverRaven/Cataclysm-DDA/blob/b8bbd5ad5a78f8476a97169c5ebe40cd21912706/src/panels.cpp#L2151-L2152
