### ISSUE TITLE
Fuji's military profesions still use MBR vests

### ISSUE THREAD

**Issue by YourCompanionCube** [CleverRaven/Cataclysm-DDA#44207]
# Describe the bug

MBR vests were removed by [#36920](https://github.com/CleverRaven/Cataclysm-DDA/pull/36920) but the Fuji professions never got updated leading to an error where mags are put into non-existent items (see additional context)

# Steps To Reproduce
Make a world with Fuji's professions and hover over one of them such as military rifleman

# Expected behavior
That these professions would have been updated along with the vanilla ones

# Screenshots

# Versions and configuration
Experimental tiles version 11006 downloaded by launcher
Windows 10 64-bit

# Additional context
 DEBUG    : tried to put an item (stanag30) count (1) in a container (modularvestceramic) that cannot contain it: pocket with type (CONTAINER) not found

 FUNCTION : ret_val<bool> item::put_in(const item&, item_pocket::pocket_type)
 FILE     : src/item.cpp
 LINE     : 1102

and

 DEBUG    : tried to put an item (mp5mag) count (1) in a container (modularvestkevlar) that cannot contain it: pocket with type (CONTAINER) not found

 FUNCTION : ret_val<bool> item::put_in(const item&, item_pocket::pocket_type)
 FILE     : src/item.cpp
 LINE     : 1102

**Comment by Maleclypse** [comment]
I’ll try and fix this
