### ISSUE TITLE
Segfault after cancelling dissection when prompted & getting stuck dissecting nearby unwanted corpses

### ISSUE THREAD

**Issue by kenneth-ellis** [CleverRaven/Cataclysm-DDA#44217]
# Describe the bug

Segfault after cancelling dissection due to enemy approaching & getting repeated prompts to cancel butchering again while moving a few tiles.

# Steps To Reproduce

Not entirely certain; was dissecting a zombie scientist with a lot of other corpses nearby.  A shrieker started approaching & I was prompted to cancel butchering, to which I said Yes.  I then moved onto another tile with a different corpse and was prompted to stop butchering *that* corpse as the shrieker was approaching  Said yes to cancel, moved another tile onto another corpse -- prompted to cancel butchering *that* .   Moved another tile, and then Segfault.

# Expected behavior

1. Not automatically starting butchering / dissecting other corpses on other tiles after cancelling dissecting the first.  I did not have any automatic butchering options enabled.
2. Not segfaulting.  :)

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5236754/crash.log)
[Fernan Lake Village.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5236758/Fernan.Lake.Village.zip)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5236759/debug.log)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.E-5988-gb8bbd5a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Monsters [No_Fungi]
]

# Additional context

Crash/debug logs & most recent save file attached.

**Comment by RoyBerube** [comment]
I have the suspicion that refactoring butchering to be an activity actor from a handler would solve this problem. The problem being that handlers do not redirect a cancel to a cancel function specific to the activity - so we are left with a generic cancel which is not adequate.

**Comment by Saicchi** [comment]
Can't replicate this issue in 0.E-9355-g203e8c942c.

**Comment by OliveChukar** [comment]
Tested in 0.E-9570-gb09447e. With provided save after multiple attempts  dissecting did restart after canceling but there was no crash.  Tested with fresh world and could not get it to happen. 

I have encountered something similar to this in 0.E stable.  If I am interrupted when pulping or butchering and I cancel many other actions will cause pulping/butchering to resume. The  most common example is walking around with autopickup on then starting to pulp something being interrupted and when autopickup grabs things I will resume pulping even if I am not near a corpse. When this happens the initial corpse that I was pulping before interruption will get pulped despite me not being near it.

**Comment by actual-nh** [comment]
> Tested in 0.E-9570-gb09447e. With provided save after multiple attempts dissecting did restart after canceling but there was no crash. Tested with fresh world and could not get it to happen.

Could not get which to happen? Crash, or undesired restarts?

**Comment by OliveChukar** [comment]
In 0.E-9570-gb09447e I was unable to replicate any part of this issue with fresh save.

**Comment by anothersimulacrum** [comment]
Closing, then.
