### ISSUE TITLE
Tool Must Have Cutting To Butcher

### ISSUE THREAD

**Issue by CamIce2002** [CleverRaven/Cataclysm-DDA#44212]
# Describe the bug

Despite having a butchering quality, items without any cutting ability can not be used to butcher. Even in items like flint, where the description specifically says that it can be used to butcher as a last resort, it cannot be used.

# Steps To Reproduce

1. Spawn a survivor
2. Spawn flint
3. Spawn deer and kill it
4. Try to butcher deer
5. Get message that you need cutting 1 or more

# Expected behavior

Be able to use items that have a butchering quality but no cutting to butcher.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-5988-gb8bbd5a
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: dda

**Comment by CoroNaut** [comment]
You can smash with all items, perhaps this is what the description meant since when smashing animals you can get at least some meat chunks out of the corpse. It isn't quite butchering but it gets the job done.
