### ISSUE TITLE
NPC Surgeons are basically forever unusable after one or less surgeries

### ISSUE THREAD

**Issue by mikeomni** [CleverRaven/Cataclysm-DDA#44221]
# Describe the bug

NPC Surgeons have no equipment to give them storage capacity for the purposes of trade- CBM surgery is generally very expensive and so after 1 low end surgery or zero expensive surgeries they basically can never be used again because they don't have storage or weight capacity to take trades for the surgery.

I would argue this is a larger problem with merchants in general though. If I had to fix this system myself, my suggestion would be to make an on-site, off-character furniture storage for the purposes of merchant trade that that particular merchant is directly linked to, and leave merchants personal inventories out of it, that's their own gear.  You're conceptually separating the merchant the person and the store of that facility or faction from each other.  The store trade is no longer dependent on 'the entire stockpile of this free merchants facility is what i can fit in my trenchcoat pockets' and on-site physical store stock still allows the player to be a piece of shit should they so choose and kill everyone to get their cheddar.

Generally, this isn't too much of a problem until you get to the NPC surgeon though, in that case, it's basically breaking the functionality entirely of a surgeon which is kind of a big deal as the ways to get CBMs into you have seriously narrowed since Danny. Not to mention levelling up the ranch until you can get a surgeon is no small feat for a really disappointing payoff in the surgeon being basically functionally broken. (and the ability to do multiple surgeries in one trade/operation would be vastly appreciated if anyone is interested in taking that on.)

**Comment by Maleclypse** [comment]
Could this be fixed by giving them the merchant enum mission (3?) that let's them use the space around them as trade space?
