### ISSUE TITLE
Shooting method lock

### ISSUE THREAD

**Issue by MikuMiddo** [CleverRaven/Cataclysm-DDA#44223]
# Is your feature request related to a problem? Please describe.
Nope.
# Describe the solution you'd like
Add a new switch between the three shooting method.To change the default(simplely press 'f')shooting method.
In most of the time,we use the [p] shooting method.When I using the gun to kill huge amount of zombies,I have to press fpfpfpfpfpfpfpfpfpfpfp,And always mistakely call the bionic window.

# Describe alternatives you've considered
May be can add this setting to guns,different gun attach to different default shooting method.

# Additional context
Nope

**Comment by olanti-p** [comment]
Requested in #28366
