### ISSUE TITLE
Perishable items in containers don't get sorted correctly 

### ISSUE THREAD

**Issue by YourCompanionCube** [CleverRaven/Cataclysm-DDA#44245]
# Describe the bug
when setting zones for sorting perishable and nonperishable food/drink, foods in paper wrappers and plastic bags go into the nonperishable zone and perishable drinks are being sorted as nonperishable foods

# Steps To Reproduce

1. make a zone for Unsorted loot, one for Food, one for P. Food, and one for P. Drink
2. spawn a bag of popcorn and a bottle of fruit juice in the unsorted loot zone
3. sort loot and see they go into the Food zone 
4. unload the plastic bag and put the popcorn back in the unsorted zone
5. sort and see it ends up in the P. Food zone

# Expected behavior
that food is sorted as perishable in containers that don't prevent spoilage and drinks are sorted properly 

# Screenshots

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-5927-g27d4c34 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context

**Comment by esotericist** [comment]
just ran into this personally with my water being sorted with my food.

**Comment by Xpyder** [comment]
I'm investigating this. based on the comment in post #42995 here's the current breadcrumb trail

I'm guessing it's going to be in `item_category.cpp` or `item_category.h`, though it could be in one of the others.
Notably `item.cpp`/`item.h` show up a lot as one would expect so they should at least be checked
Also The lines I started from are at the bottom

`get_food()`
src\item.cpp
src\item.h

`goes_bad()`
src\item.cpp
src\item.h

`cat.get_id()`
src\inventory_ui.cpp
src\item.cpp
src\item_category.cpp
src\item_category.h
src\itype.h

`item_category_food`
src\clzones.cpp
src\item.cpp

`get_comestible()`
src\item.cpp
src\item.h


Here's the starting point:
```
src\clzones.cpp

    if( cat.get_id() == item_category_food ) {
        // skip food without comestible, like MREs
        if( const item *it_food = it.get_food() ) {
            if( it_food->get_comestible()->comesttype == "DRINK" ) {
                if( it_food->goes_bad() && has_near( zone_type_id( "LOOT_PDRINK" ), where, range ) ) {
                    return zone_type_id( "LOOT_PDRINK" );
                } else if( has_near( zone_type_id( "LOOT_DRINK" ), where, range ) ) {
                    return zone_type_id( "LOOT_DRINK" );
                }
            }

            if( it_food->goes_bad() && has_near( zone_type_id( "LOOT_PFOOD" ), where, range ) ) {
                return zone_type_id( "LOOT_PFOOD" );
            }
        }

        return zone_type_id( "LOOT_FOOD" );
    }
```

**Comment by Xpyder** [comment]
Here's the relevant section of `src/item.cpp`

If you spot what's wrong but not how to fix it feel free to point it out and tag me and I'll see if I can fix it. (it's currently past midnight and over 90 in my room so I gotta quit for the night)

```
bool item::goes_bad() const
{
    if( item_internal::goes_bad_cache_is_for( this ) ) {
        return item_internal::goes_bad_cache_fetch();
    }
    if( has_flag( flag_PROCESSING ) ) {
        return false;
    }
    if( is_corpse() ) {
        // Corpses rot only if they are made of rotting materials
        return made_of_any( materials::get_rotting() );
    }
    return is_food() && get_comestible()->spoils != 0_turns;
}
```

**Comment by Xpyder** [comment]
Side note: `item_internal::goes_bad_cache_is_for` will probably need to be reviewed after the initial changes take place to make sure a container that currently has a perishible (like milk) doesn't forever get tagged as perishable (if you fill it with say lamp oil)

**Comment by Xpyder** [comment]
Trail probably leads into <type>.comestible for `item` which is probably going to be in a .h somewhere that leads to another .cpp.  I'll have to do more tracing when I get home

**Comment by Xpyder** [comment]
Maybe it when sorting loot, it should separate layered containers (so a [bag with flour and [a bottle of juice]] becomes [a bag with flour] and [bottle of juice])

Not certain about this nor that it would simplify this fix at all but wanted to note it for the future before I forget

**Comment by Xpyder** [comment]
Here's a prototype for a contains_perishible() function.  It should probably go in `src/item_contents.cpp` and be added to the logic of the item::goes_bad() in `src/item.cpp`

current problems:
There's some definitions in the function header I don't understand that need to be filled out
I'm not sure what the echo in `item_contents.h` should be
I probably forgot a type declaration or two
I don't know the linting style for this project so spacing should be double checked
I don't have a compiler so I can't test
And I'm flying kind of blind so I'm not sure I declared the temporary function correctly.  I forget what they're called, but it's the `[] (parameter){instructions}` part

```
const cata::something<something> &item::contains_perishable() const
{
	contains_perishable = false
	std::list<const item *> all_contents = container->contents.all_items_ptr();
	std::for_each(
		all_contents.begin(),
		all_contents.end(),
		[](const itype & child) {
			if( child->goes_bad() ) {
				contains_perishable = true
				// 2 possible optimizations here, but given the item counts while sorting the value is questionable
				// we could just return true if that won't leave anything dangling (I don't know C++ enough to be sure of this)
				// or we could break the loop early (not sure the command for this)
			}
		}
	)
	return contains_perishable
}
```

**Comment by Xpyder** [comment]
Here's the loop code I was tearing from in case there's something in it that can help fix my prototype (it's from `src/item_location.cpp`):

```
	std::list<const item *> all_items = container->contents.all_items_ptr();
	auto iter = all_items.begin();
	std::advance( iter, idx );
	if( iter != all_items.end() ) {
		return const_cast<item *>( *iter );
	} else {
		return nullptr;
	}
```
