### ISSUE TITLE
Many gun modifications are missing installation/removal time

### ISSUE THREAD

**Issue by olanti-p** [CleverRaven/Cataclysm-DDA#44298]
# Describe the bug
Many gunmods (e.g. all grip modifications) are missing installation/removal time, and default to zero seconds.

# Steps To Reproduce
Go through all files in `data/json/items/gunmod/` and look for `install_time` entry. Some gunmods don't have it, and some gunmods have it commented out.

# Expected behavior
Gunmods should have at least a few seconds of installation time - ideally, close to how much it takes to perform the same modification IRL. Some gunmods (e.g. integrated stuff) can be neither installed nor removed - those can probably be ignored.
Specifying installation time is easy - just add `install_time` entry.
Removal time is calculated automatically as half of the installation time.

In the future, it would be nice to make `install_time` entry mandatory to prevent this kind of inconsistency.

# Versions and configuration
Build 11019 (aka 59eb5ef8917a495e9991e8eb53cae3644118c937)

# Additional context
Looks like a candidate for "Good First Issue" - It is purely json modification, and requires more source hunting than testing/debugging.

**Comment by rasmuskarlback** [comment]
Hello! I would like to start contributing to this project and thought this would be a good first issue, is it possible that you can assign me to it? :)

**Comment by anothersimulacrum** [comment]
Done!
