### ISSUE TITLE
#11019 NPCs can't walk through mesh screen doors

### ISSUE THREAD

**Issue by KrunkySmokin** [CleverRaven/Cataclysm-DDA#44294]
=-=-=-=-=
Bug: NPCs are not able to walk through screen mesh doors, but they can close them if you push them through or swap positions.
=-=-=-=-=

Steps to reproduce:
1. Surround NPC with mesh screen walls and one door
2. Open mesh door
3. Order NPC to follow
4. They cannot cross through the mesh door.

=-=-=-=-=
In the preview below, the NPCs are set to follow at 2 tiles.
![catabug](https://user-images.githubusercontent.com/49448025/93717552-8ec75f00-fb44-11ea-8a94-6330456d3af7.gif)

Version: O.E-6090-g59eb5ef
Modlist: DDA
Disable NPC Needs

**Comment by Olaroll** [comment]
They cannot climb over mesh walls either

**Comment by PatrikLundell** [comment]
I've seen they're unable to follow the PC through the turnstiles (or whatever it is) in subway stations, although you can get them to follow through the ticket booth building (0.E2 stable).

**Comment by ElfLeaderMike** [comment]
Just commenting to say this is still a problem on the below version. 
Screen doors too scary for NPCs to walk through.

- OS: Windows
- OS Version: Windows 7 Professional 64-bit
- Game Version: 0.E-7938-g8736e6b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]
