### ISSUE TITLE
Prioritizing storage equipment/ability to drop to container in advanced inventory

### ISSUE THREAD

**Issue by Misanthropologist** [CleverRaven/Cataclysm-DDA#44290]
In order to deal with encumberance, players often drop their backpack or other such items before engaging in melee. Currently making sure the items you pick up go to a backpack is kind of a pain. If there was a way to manually mark a container as a priority container or at least open the container and move stuff into it with the 'c' command in advanced inventory, it would make this much smoother.

Alternatives: automatically prioritizing backpacks/large containers, This is not a great solution. The current autosorting into containers is the most efficient, and may be preferred by many.

**Comment by NicholasDM** [comment]
If you press _i_ to view your inventory, select the container (backpack in this case) to look at your item, and then _v_, you enter the container menu. From there, you're able to set priorities (numerically) compared to other containers, add whitelists/blacklists etc.

That said, I would really like for the inventory menu itself to be updated to make things like this easier, and in particular resorting items through multiple containers.
