### ISSUE TITLE
Burdock does not spawn on fields

### ISSUE THREAD

**Issue by danielkwinsor** [CleverRaven/Cataclysm-DDA#44295]
# Describe the bug

Burdocks are supposed to be magenta f flowers, but are not present

# Steps To Reproduce

Start game
Search fields

# Expected behavior

Burdocks in fields

# Additional context

https://github.com/CleverRaven/Cataclysm-DDA/pull/38515

**Comment by anothersimulacrum** [comment]
They appear to have been only set to spawn in the rural biome mod.
