### ISSUE TITLE
Wearyness gameplay quirks

### ISSUE THREAD

**Issue by irwiss** [CleverRaven/Cataclysm-DDA#44299]
# Describe the bug

Wearyness shows 2 separate debuffs, wearyness messages appear while character is sleeping

# Steps To Reproduce

1) Get weary
2) Start sleeping
3) During sleep you get wearyness messages
4) On wakeup you have 2 weary-ness debuffs in @

Save attached if it helps

# Expected behavior

One wearyness debuff, no messages during sleep

# Screenshots

![image](https://user-images.githubusercontent.com/6560075/93721993-49cf1700-fb9c-11ea-9438-ef2a2a897ec2.png)
![image](https://user-images.githubusercontent.com/6560075/93721995-4b98da80-fb9c-11ea-8e51-224c74badc3a.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-6108-g9a07fb7dcd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA],
    No Rail Stations [No_Rail_Stations],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Arcana - UndeadPeople Tileset [ArcanaUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP],
    _CustomTweaks [_CustomTweaks]
]

# Additional context

[Nectar.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5252598/Nectar.zip)

**Comment by RoyBerube** [comment]
I haven't dug into the code, but it seems that something like a moving average is being used to calculate weariness. If doing strenuous activities before sleep, the avatar's weariness can get worse for a few hours. It seems odd to say the least.

The double message must be just a bug. I've seen it too.

**Comment by anothersimulacrum** [comment]
Weariness is calculated by calories burnt and taken in. While sleeping or doing NO_EXERCISE activities, the trackers of calories taken in and burnt will decrease, decreasing weariness.

Yeah, there's a bug where the effects aren't removed. I'm not sure what's up there.

**Comment by DoctorVanGogh** [comment]
Just piling on here... weariness is wonky currently. Character had double `weary`and `very weary` effects. Went to sleep, got lots of messages about too strenuous activity, woke up `extremely weary` 😩 

![image](https://user-images.githubusercontent.com/324067/94353005-78516400-006c-11eb-9c7e-7ddef3f12604.png)

**Comment by paulenka-aleh** [comment]
My character also woke up extremely weary. I spent entire day reading fiction only to find out that actually despite extremely weary status is still displayed, I can craft again to get 2nd little weary status and addition to extremely weary.

**Comment by Xpyder** [comment]
Might be related to #44604 but not sure so I created a separate issue with a saved game attached

**Comment by Xpyder** [comment]
I've confirmed this is indeed the case.  There's a lot more diagnostic info in  #44604  including the specific .cpp files that need to be corrected and most of the relevant functions for easy searching.
