### ISSUE TITLE
Extendable baton and PR-24 baton can be extended in a pocket that would not normally house their full length

### ISSUE THREAD

**Issue by cosmo-naut** [CleverRaven/Cataclysm-DDA#44308]
# Describe the bug

The two extendable baton items (and possibly more items that change length) do not fit in many standard pockets in their extended form, but do in their retracted form. The player character can place the retracted item ("longest_side": "20 cm") inside a backpack ("max_item_length": "40 cm"). Using the 'a'ction menu, the player character can select 'Extend' on the baton, turning it's longest_side to 60 cm, while remaining in the bag.

# Steps To Reproduce

1. Spawn the extendable baton and backpack
2. Wear backpack, insert baton into it.
3. Press 'a' and peform the action for the baton, extending it

# Expected behavior

Either the player should be told they are not able to extend the baton, or it should automatically fall on the ground.
There is already a precedence for items falling on the ground due to certain weight restrictions or pockets being destroyed, however a message preventing the player from performing the action would be a nicer user experience.

# Versions and configuration

Current experimental

# Additional context

I know a little about C++ and I'm pretty good with json. Would be interested in looking into this issue if nobody is currently working on the multitude of max_item_length issues. Perhaps someone can point me in the right direction.

**Comment by kenneth-ellis** [comment]
I noticed the same issue and came to post a new bug but found this already posted, so +1

**Comment by Night-Pryanik** [comment]
This should be closed by #45873.
