### ISSUE TITLE
Straw basket does not use Basket weaving, but sandals do

### ISSUE THREAD

**Issue by KashouC** [CleverRaven/Cataclysm-DDA#44315]
# Describe the bug

Basically the title. Straw Basket seems to not use any proficiency for crafting, while pair of Straw Sandal uses Basket Weaving. They are both the same skill level so I just figured that they should either both use it, or somehow it got attached to the wrong recipe, unless I am mistaken.

# Screenshots

![image](https://user-images.githubusercontent.com/17066488/93774791-ec7da900-fc21-11ea-92ba-2a63b9ea559e.png)

![image](https://user-images.githubusercontent.com/17066488/93774836-f8696b00-fc21-11ea-84a6-bbf4b34cf8d4.png)

# Versions and configuration

 - OS: Windows 10 x64 Pro
    - OS Version: 10.0 1909 (10.0.18363 Build 18363)
- Game Version: 0.E-6111-g97d34d2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    Graphical Overmap [Graphical_Overmap]
]

**Comment by RobertoVGoulart** [comment]
It seems this one was fixed on #44214

**Comment by mlangsdorf** [comment]
Closed in #44214
