### ISSUE TITLE
Strict Humanitarian should conflict with Cannibal

### ISSUE THREAD

**Issue by LlubNek** [CleverRaven/Cataclysm-DDA#44318]
# Describe the bug

The description for "Strict Humanitarian" says "You'd never eat people, ..." but you can still take strict humanitarian with Cannibalism.

# Steps To Reproduce

1. Create a new player character
2. During character creation, go to the traits tab
3. Enable Cannibalism and Strict Humanitarian

# Expected behavior

Strict Humanitarian should probably evolve into Cannibalism instead, which would cancel Strict Humanitarian, or the description for Strict Humanitarian should change.

# Screenshots
![image](https://user-images.githubusercontent.com/313762/93782728-e921f780-fbf8-11ea-93cc-e9fa608beacb.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-6130-gb825e3a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by ZhilkinSerg** [comment]
These two traits are not related.

**Comment by anothersimulacrum** [comment]
Could also change the flavour text.

**Comment by cosmo-naut** [comment]
I think the Strict Humanitarian trait is very unclear about what it actually does for you.
