### ISSUE TITLE
Pipe fittings are too rare in the world, should be recoverable from more things

### ISSUE THREAD

**Issue by Nymall** [CleverRaven/Cataclysm-DDA#44323]
# Is your feature request related to a problem? Please describe.
At the moment, Pipe fittings are only acquirable from the following sources: workbench, muffler, seat, leather seat, electric kiln, plow

4 of those elements require access to vehicles and the ability to disassemble seats, which is a strange bar. There are lots of other things in the environment that should give these when disassembled, such as the furnace, hot water tank, washer, fridge and sink.

# Describe the solution you'd like

Several items should already need pipe fittings during destruction/deconstruction. A small, non-exhaustive list follows:

- [x] Fridge
- [x] Glass Door Fridge
- [x] Freezer
- [x] Sink
- [x] Furnace
- [x] Hot Water Heater
- [x] Pump
- [x] High-gauge pump
- [x] Cooling Unit
- [x] Heating unit
- [x] Satelite Dish
- [x] Cell Phone Signal Booster
- [ ] Still
- [x] Monkey Bars
- [x] Park Slide
- [ ] All engines(even through the use of rubber hoses, there still should be usable coupling components)
- [ ] Fuel tanks
- [x] Stove
- [x] Rotary Clothes Dryer Line
- [x] Shower
- [ ] Hydraulic Press
- [x] Chain Link Fence(The top bar would still be connecting to the metal posts through T fittings)
- [x] Dishwasher
- [x] Floor Lamp
- [ ] Skate Park Railing

# Describe alternatives you've considered

- Removing pipe fittings in exchange for a required welding material of some kind( eg PVC glue)

**Comment by Xenomorph-III** [comment]
You can still get pipe fittings from fridges, dishwashers, dryers and other household appliances. That was my scope when doing the pipe fittings PR.

**Comment by anothersimulacrum** [comment]
Eyebots are quadcopters.

**Comment by Nymall** [comment]
Hmm... must be on a outdated version. According to the JSON, these already have fittings:

f_dishwasher
f_glass_fridge
f_fridge
f_washer
