### ISSUE TITLE
More Nuance to Weariness is Needed

### ISSUE THREAD

**Issue by Giagantic** [CleverRaven/Cataclysm-DDA#44326]
# Is your feature request related to a problem? Please describe.

Weariness is a good idea one that fundamentally addresses the previous "infinite work stamina" that CDDA characters had prior but as it stands there are many adjustments needed to nail it without it becoming negative factor on the gameplay itself. 

# Describe the solution you'd like
Weariness should be split into 2 different categories that at times overlap and other times don't, namely, **Mental Weariness** and **Physical Weariness**. Both of these categories as previously mentioned overlap at times but not necessarily always, a person can be physically weary but relatively acute mentally and inversely you can be mentally exhausted but at the same time physically well. 

However, the key for balance would probably be to make either form of weariness have somewhat of an impact on the other. If you build up your mental weariness inevitably you would be somewhat affected physically, especially if your mental state is quite negative in regards to morale, basically adding a psychosomatic effect. Likewise, extreme physical weariness should  have an impact on your mental acuity, especially in the case of those with poor morale. Examples of this in real like are boundless and I am sure many here understand this and if we are aiming for realism I think separating these into two categories is important. 

# Additional context
Was playing with the weariness on a new character and was struck with how strange it was to have both your mental and physical shape jumbled together. I was reading a lot of books and when I got weary I went for a walk but the weariness got worse and I was continually assaulted with the warnings of this. Ironically, in real life a person may very well go on a walk to solve their mental exhaustion, even physically working out to get through it.

**Comment by Fallout48** [comment]
If this was implemented, you could even have certain enemies effect your weariness. Like some psychic nether beast that slowly builds up your mental weariness with their attacks.

**Comment by kenneth-ellis** [comment]
@Fallout48 that is a pretty cool idea :)

**Comment by Nymall** [comment]
Yeah, this is kinda a bummer right now. Roleplaying wise, it would be nice to have a reason to always have a fiction novel or something in the backpack to wind down after some intensive combat or heavy lifting, but at the moment _even reading fiction novels leads to worsening weariness._

I'm at a loss on how to improve, apart from studying spells and sleeping, but even sleep seems to increase it at the moment.

**Comment by Kenan2000** [comment]
Indeed, splitting the weariness into Mental and Physical is definitely important, reading books to learn skills or learning spells is not supposed to give you Physical weariness just like sleeping or doing something fun and basically no physical energy consuming
I sincerely hope that the devs will be able to patch up the weariness system and make it properly balanced and working really nicely :-)

**Comment by anothersimulacrum** [comment]
Weariness increases as a result of losing calories. When reading, you are actively recovering from weariness, but perhaps not quite fast enough.

**Comment by ektoplazm** [comment]
"Mental weariness" sounds a lot like the current morale/focus system to me.

**Comment by Giagantic** [comment]
> 
> 
> "Mental weariness" sounds a lot like the current morale/focus system to me.

Mental Weariness is by all accounts, similar to focus. but I personally think Focus is kinda flawed as is and the Weariness system is a better way to go about day to day exhaustion both physical and mental. As it stands, focus is just a homogeneous combination of Mental and Physical exhaustion and how it effects the efficacy of skill gain. I personally argue that both the Weariness system and Focus are as such interconnected but need more depth so that it isn't just a way to gimp characters but to add more layers. 

By adding these layers you give other systems in the game a chance to have a greater purpose, such as working out, personal hygiene, differing forms of relaxation both already in the game and newer editions down the road.

**Comment by Nymall** [comment]
> Weariness increases as a result of losing calories. When reading, you are actively recovering from weariness, but perhaps not quite fast enough.

So, how do we decrease it then? If it's STILL ticking up while we are doing restful activates, that doesn't make sense. Binge high calorie food and sleep? Even then, the messages it gives gives the impression you are getting MORE weary instead of LESS - it's hard to determine exactly what you can do to remedy the situation.

**Comment by KashouC** [comment]
You decrease it by resting, which might in some cases include just waiting for 30-60 minutes (lunch break), but most importantly you need to eat calories. Personally I reduced all exercise values one step for all crafting and it made the system a lot more enjoyable. I'm still around moderate weariness A LOT but it at least lets me boil some water and some dandelions without collapsing. I've already seen (i think erk) talk about limiting the amount of "you are becoming weary" messages that pop up. I also think it needs to have a "you are recovering" variant for when it's triggering text from actually going down. But perhaps not every 2 in game minutes.

**Comment by I-am-Erk** [comment]
We've already got plans for basically this. However it's not a "splitting up". Weariness isn't mental at all. The plan, basically, is for focus to be the stamina of the brain and for another stat as yet unnamed to work like weariness to gate your overall brain capacity for stuff like study fatigue
