### ISSUE TITLE
No recipes use Garment Closures proficiency

### ISSUE THREAD

**Issue by dsmky117** [CleverRaven/Cataclysm-DDA#44322]
Game version:
Build 11022

Operating system:
Windows 10 2004

Tiles or curses:
Tiles

Mods active:

### Expected behavior
Some items would allow you to gain the Garment Closures proficiency, which is required for cobbling and fabric water proofing.

### Actual behavior
prof_closures is not found on any items, though it is present in a few starting professions. If my understanding of the system is correct, then it is not possible to gain this proficiency unless you start as those professions, which may be intentional.

**Comment by Nymall** [comment]
This is presently being spear-headed by @I-am-Erk at the moment - you can see the total progress here: #42476

Are there some items that you believe this skill should be used on?

**Comment by I-am-Erk** [comment]
It's a large multi-pr project, give me a few minutes.
