### ISSUE TITLE
No items spawning in upper floor of the Vault

### ISSUE THREAD

**Issue by junknowny** [CleverRaven/Cataclysm-DDA#44336]
# Describe the bug

The Vault has items on the lower floor but none at all on the upper floor. 

# Steps To Reproduce

1. Debug reveal map.
2. Find a necropolis.
3. Teleport to the first floor of the vault, observe that there is no items whatsoever.
4. Teleport to the lower floor, observe that items spawn normally. 

# Expected behavior

There should be items on the top floor of the vault just like it is on the lower floor.
It makes no sense for the first floor to be completely devoid of items while the bottom floor has a normal item spawn rate.

# Versions and configuration

 - OS:  Windows 10
 - Game Version: 0.E-6131-gdba2207, experimental build 11023
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: None

**Comment by Maleclypse** [comment]
Vault is obsoleted
