### ISSUE TITLE
Adding mineral oil into the game, both commercial and as a salvage liquid

### ISSUE THREAD

**Issue by Nymall** [CleverRaven/Cataclysm-DDA#44338]
# Is your feature request related to a problem? Please describe.
Despite how it is mentioned in t_oil_circ_brkr_l and t_oil_circ_brkr_s, mineral oil is not presently part of the game. This is fortunately a very useful chemical to have, as it is non-reactive and great for storing more reactive or dangerous chemicals. This request is based off of White Mineral Oil, the most common availbile for industrial and food grade use. For more about the above HV Oil Breakers, please see here: https://www.electrical4u.com/oil-circuit-breaker-bulk-and-minimum-oil-circuit-breaker/

# Describe the solution you'd like
Two seperate oil liquids added:
- Contaminated Mineral Oil: Salvaged from machinery(such as the breakers above), not good for use in food-safe applications
- Mineral Oil: Liquid in bottles - is presently used in many applications, including as a laxitive'.

Potential Uses:
- Cell and Microbial culturing
- Creation of lotions and ointments(such as to sooth burns or recover rash)
- Non-conductive coolant and lubricant
- Hydraulic Fluid
- Curing and preserving of wood
- Can be used in place of a penetration oil
- Preserving Eggs: https://www.preparednesspro.com/safely-preserving-eggs

# Describe alternatives you've considered
Changing the HV breaker to a different type, however this already aligns with the Chemistry Project.

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
