### ISSUE TITLE
Save file corruption,

### ISSUE THREAD

**Issue by Zeebuoy** [CleverRaven/Cataclysm-DDA#44341]
my saves in both experimental and stable E-2 being corrupted, either crashing, or causing all items/(also vehicles and nearby carts to dissapear) and resetting the conditions of nearby buildings such as the vandalized evac centre having all of it's supplies back in place.

additionally, this error does not seem to affect the save files of the world, tried making a new character in a world that encountered the issue, no issue yet, 

despite it saying

 DEBUG    : Failed to read from "./save/Flat/artifacts.gsav": line 1:1: tried to start array, but found '

 FUNCTION : bool read_from_file(const string&, const std::function<void(std::basic_istream<char>&)>&)
 FILE     : src/cata_utility.cpp
 LINE     : 434

# Steps To Reproduce

It tends to happen rather quickly and only after saving and quitting , have not found a consistent way of reproducing, tried not unabling magiclysm to see if it'd help, but no, still runs into issues.

# Expected behavior

items, and vehicles in vicinity, current radius unknown, dissapearing, including bikes that were currently being ridden, despite that nearby vehicles that I haven't interacted with have not been affected,

in the event of crashes, it says segmentation fault

# Screenshots

can't provide those at the current time, will try to edit those in later

# Versions and configuration

   - OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-6052-gfacb03d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA]
]

# Additional context

the error message displayed when playing vanilla was different, and ended with a crash and a pop up saying segmentation fault, as opposed to missing items

- note #1: you can drag and drop files in this issue post!
- note #2: it is very important for us that you provide a save file in case of a crash. It really helps the developers
    to reproduce the bug and fix it. If possible, try to provide a save file that occurs in the right conditions, just
    before the crash happens. --> 

(still trying to figure out how to do note #2 sorry, am new to this,)

**Comment by ZhilkinSerg** [comment]
It is something in your environment. We can only advice you to backup your saves regularly, check your hardware and operating system for errors.

**Comment by olanti-p** [comment]
This looks similar to #41632, which was a silent file corruption due to low free space on disk. Did you run stable or experimental when it was saved?

**Comment by Zeebuoy** [comment]
> This looks similar to #41632, which was a silent file corruption due to low free space on disk. Did you run stable or experimental when it was saved?

um, I had both experimental and stable files (in their seperate folders) on my pc when the errors happened, also happened when I only had one or the other

**Comment by olanti-p** [comment]
> you're saying that clearing out more file space should stop the issue, right?

If your partition is almost full (less than, say, 2GB free), than yeah. Other thing to check is the location of the game: putting it somewhere in the system directory (Program Files...) would break the saving, and putting it on a usb drive and pulling it out without safe removal might too.

But ZhilkinSerg is right, that's definitely something on your end. The game should show a "Failed to write file..." error when saving if it's something with the hdd (though stable version sometimes silently fails instead - that was the issue I linked)
