### ISSUE TITLE
Diesel vehicles with JP8 fuel use wrong engine type

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#44349]
# Describe the bug

Diesel-powered vehicles with JP8 or other non-diesel fuel in their tanks cannot be started up at first, saying "Looks like the 4.5L V8 diesel engine is out of diesel."

# Steps To Reproduce

1. Get a working diesel-powered vehicle (i.e. spawn a Humvee in perfect condition)
2. Try to start the engine (fails saying it's out of diesel)
3. Try to start the engine again (works fine)

# Expected behavior

Diesel engines should work with JP8 without needing to specifically configure the engine to use JP8.

# Screenshots

Before starting the engine, if I `e`xamine the driver's seat, `v` (control vehicle), `y` (control individual engines), I see that the "diesel" engine is the default, not the JP8 engine:

![image](https://user-images.githubusercontent.com/238395/93941607-0d123580-fcec-11ea-850c-e5446f47bdff.png)

Without changing anything, if I try to start the engine, it always fails the first time with an error about being out of diesel:

![image](https://user-images.githubusercontent.com/238395/93941412-a4c35400-fceb-11ea-86f5-e7c462ceb505.png)

However, after the first attempt at starting the engine, "control individual engines" has the correct (JP8) engine type selected:

![image](https://user-images.githubusercontent.com/238395/93941527-e5bb6880-fceb-11ea-9aa1-f3ab9c5e80d5.png)

Or, I can select the JP8 engine from "control multiple engines", then the engine will start on the first try.

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-6164-g1d5c31e102 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by cosmo-naut** [comment]
How do hybrid cars currently work? Do they automatically detect whether to use the other engine if out of gasoline/electricity? I know there's a vehicle part that's meant to automate that

**Comment by anothersimulacrum** [comment]
Hybrid cars use that vehicle part, but I'm not sure how that relates to this issue.

**Comment by cosmo-naut** [comment]
It's related in the sense that we already have snippets of code that perform the desired behaviour; switching to the appropriate engine based on accessible resources. 
It just not currently implemented in the diesel engines which have multiple potential fuel sources.

**Comment by anothersimulacrum** [comment]
I am fairly sure that will not be related to the solution to this issue.

**Comment by wapcaplet** [comment]
Similar issue is occurring when starting a helicopter.
