### ISSUE TITLE
Arrow Keys and NumPad Keys don't work on the main menu after rebinding

### ISSUE THREAD

**Issue by Daevinski** [CleverRaven/Cataclysm-DDA#44346]
# Describe the bug

After changing the "Move" keys to work globally with both the Arrow Keys and the NumPad Keys, is not possible to navigate the main menu with any of these sets anymore. It works in any other menu and in-game, except the main menu.

EDIT: The keys don't work in the regular Inventory Menu (i) as well.

# Steps To Reproduce

1. Edit keybindings.
2. Update the "Move" keys with both Arrows and NumPad.

# Expected behavior

Once set all the keys globally, the new keys should work in all menus, including the main menu.

# Versions and configuration

```
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-6131-gdba2207 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Graphical Overmap [Graphical_Overmap],
    Whaleys Hair Mod (UDP Tweaks) [WHALEYHAIR_UDP],
    Bionic Slots [cbm_slots],
    Fuji's Military Profession Pack [fuji_mpp],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]
```

**Comment by ZhilkinSerg** [comment]
Attach your `keybindings.json` from `config` folder.

**Comment by Daevinski** [comment]
Both the file you asked for and the config the way I see on the options.

[keybindings.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5263411/keybindings.zip)

![cataclysm-tiles_o5xVzT2UQf](https://user-images.githubusercontent.com/68783194/93924243-dab40880-fcea-11ea-8c20-6d933ee4e8ac.png)

**Comment by Qrox** [comment]
I think the problem is that main menu is not yet migrated to support keycode (due to the way it is currently implemented), so when you removed and rebound movement hotkeys, you removed the symbol mode keybinings, and that's why main menu no longer works. I suppose as a temporary measure I can change the code to only remove keybindings of currently enabled input mode.

**Comment by t-e-m-a** [comment]
> I think the problem is that main menu is not yet migrated to support keycode (due to the way it is currently implemented), so when you removed and rebound movement hotkeys, you removed the symbol mode keybindings, and that's why main menu no longer works. I suppose as a temporary measure I can change the code to only remove keybindings of currently enabled input mode.

Main menu must support keycode
