### ISSUE TITLE
"Black Error Screen" when trying to add an item on a full container

### ISSUE THREAD

**Issue by Daevinski** [CleverRaven/Cataclysm-DDA#44352]
# Describe the bug

A "Black Error Screen" appears when I try to add an item on a full container that I'm wearing, especially if it's another smaller container. For example, if I try to add a can of coke inside a sling.

# Steps To Reproduce

1. Get an item. Any item.
2. Open your Inventory.
3. Select a Makeshift Sling (for example) and choose "Insert" (i).
4. Select an Item or another Smaller Container to put inside the Sling.

# Expected behavior

A simple message should appear on the Log (in the sidebar) stating the target container is already full.

# Versions and configuration

```
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-6161-gac84e5c [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Graphical Overmap [Graphical_Overmap],
    Whaleys Hair Mod (UDP Tweaks) [WHALEYHAIR_UDP],
    Bionic Slots [cbm_slots],
    Fuji's Military Profession Pack [fuji_mpp],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]
```
# Additional context

```
 DEBUG    : tried to put an item (can_drink) count (1) in a container (makeshift_sling) that cannot contain it: pocket unacceptable because not enough space

 FUNCTION : ret_val<bool> item::put_in(const item&, item_pocket::pocket_type)
 FILE     : src/item.cpp
 LINE     : 1102
```

**Comment by wapcaplet** [comment]
Confirmed in 0.E-6176-g f550509083

1. Take off all clothing
2. Spawn and wear a fanny pack
3. Get a pile of items at your feet (any kind of item; they do not need to be containers)
4. Go to inventory, select the fanny pack and `i`nsert
5. Select more items from the ground than will fit in the fanny pack, and press Enter - error occurs

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-10973.
Game aborts inserting items if there's no more free space in a container
![изображение](https://user-images.githubusercontent.com/11132525/187857107-53e1ea74-fcff-4daa-bd23-d58228e892eb.png)
![изображение](https://user-images.githubusercontent.com/11132525/187857298-7c3edd23-cedb-4553-ac31-e5edeafbf44d.png)
