### ISSUE TITLE
Stone Adze missing 'activate' functionality

### ISSUE THREAD

**Issue by KashouC** [CleverRaven/Cataclysm-DDA#44350]
# Describe the bug

The Stone Adze (http://cdda-trunk.chezzo.com/primitive_adze) has wood sawing 1 but it cannot be activated to saw planks unlike a wood saw. You have to saw planks via the construction menu.

# Steps To Reproduce

Make a Stone Adze, chop down a tree, try to turn a trunk or a log into planks by hitting 'a' to activate the Adze.

# Expected behavior

I expected to be able to turn logs into planks, like with the wood saw. But it doesn't do anything when you hit activate.

# Screenshots

![image](https://user-images.githubusercontent.com/17066488/93945383-14126580-fd37-11ea-8c41-86345ebaa79f.png)

# Versions and configuration

<!-- Add any other context about the problem here.

- OS: Windows
    - OS Version: 10.0 Pro x64 1909 (10.0.18363 Build 18363)
- Game Version: 0.E-6152-g89c9b44 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    Graphical Overmap [Graphical_Overmap]
]

**Comment by cosmo-naut** [comment]
The wood saw has a wood sawing level of 2. I believe that is necessary to actually 'saw' wood.
The Stone Adze and the Survival Knife, Multitool and a couple others have Wood Sawing 1. This is more akin to light wood working. You don't have the ability to chop a log into fine, even planks, but you are able to cut stout branches and things more evenly than if you were using your hands or a knife that is designed for cutting such as a kitchen knife.

**Comment by KashouC** [comment]
This would make sense if you couldn't actually just head into the construction menu and get the expected functionality through there.

![image](https://user-images.githubusercontent.com/17066488/93947045-14146480-fd3b-11ea-8ec7-60d4aa97076d.png)

The tool is still usable for what I needed it for, and expected it could do, but doing it was very roundabout and I expected it to work like other tools.

**Comment by anothersimulacrum** [comment]
The construction should require wood sawing 2.

**Comment by anothersimulacrum** [comment]
Sorry, my bad, I thought this was the logs->planks this, it's trunks to logs. Disregard my previous comment.

**Comment by KashouC** [comment]
Yeah was just about to say, if the Adze wouldn't allow you to make planks from neither trunks nor logs then I'm not sure it'd have functionality. Plus making a plank already feels hard enough in a wilderness survival scenario without scouring civilization for modern tools, which would again make it obsolete.

Also it's trunks -> planks via the construction, which means the tool doesn't let you make logs which I suppose makes sense.

**Comment by anothersimulacrum** [comment]
Oh, that is into planks. That should not be allowed then. Trunks->logs is fine, but an adze is not a suitable tool for making planks. The things for which planks are used in wilderness survival scenarios should be using something else, not planks (#28071).
