### ISSUE TITLE
Apis Spawns in Mi-Go Encampment

### ISSUE THREAD

**Issue by CamIce2002** [CleverRaven/Cataclysm-DDA#44355]
# Describe the bug

Described in title

# Steps To Reproduce

1. Create test world
2. Find a mi-go encampment
3. Witness the bee queen herself captured

# Expected behavior

Not find a bee hive mutant boss in an alien prison camp

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-6161-gac84e5c
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded:
 --> dda

**Comment by anothersimulacrum** [comment]
@I-am-Erk am I correct in the assumption this is not a bug?

**Comment by I-am-Erk** [comment]
Well, I mean, Apis is kind of a bug. But this is intended.
