### ISSUE TITLE
Make cutting up items with buttons give buttons.

### ISSUE THREAD

**Issue by somepersondunno** [CleverRaven/Cataclysm-DDA#44361]
# Is your feature request related to a problem? Please describe.
I'm confused as to why, if I want buttons to make items that require them, I need to spend 5 hours (in the case of cargo pants) or 4 hours (in the case of cargo shorts) to disassemble them down to their very base materials. Buttons are uncraftable, so it's not like I can just make them. I'm aware that short strings can be used as replacements but that's not a viable alternative long-term as short strings can be very resource-intensive to make/collect.

# Describe the solution you'd like
Cutting up items like boots already gives leather, rubber, kevlar in the case of combat boots. Cutting up items that can be disassembled to net you buttons should give you the base material (kevlar, rags, leather, etc.) plus a small amount of buttons. This can be easily done even by hand, as many broken buttoned items I own can attest to. This could also be extended to zippers, but buttons are far simpler. 

# Describe alternatives you've considered
Making buttons by hand, spending 5 hours disassembling a pair of cargo shorts, just using short strings.
# Additional context
I _may_ be affected by proficiencies WRT cargo pants, but adding the ability to get back hard pieces like zippers or buttons from cutting up items is a no-brainer.

**Comment by anothersimulacrum** [comment]
It's decently complicated to make cutting things up give fasteners, but it'd be a pretty simple JSON task to allow them to be disassembled more quickly for them.

**Comment by I-am-Erk** [comment]
I've been adding a lot of reversible recipes for this reason... But we probably should look into jsonizing the 'cut up' results so that you can get laces from boots and buttons from shirts.
