### ISSUE TITLE
Proficiencies: Learning time uses basic crafting time, not actual time spent crafting

### ISSUE THREAD

**Issue by DoctorVanGogh** [CleverRaven/Cataclysm-DDA#44377]
# Description 
Crafting an item with a not yet learned proficiency involved will only credit the *basic* (unpenalized) crafting time toward "time spent learning this proficiency", **not** actual time spent on crafting.
This feels off. If a character spends an hour performing a recipe that involves a proficiency they should get an hour of practice in that proficiency.

# Steps To Reproduce

* Make a new character, teach them all recipes.
* Spawn in tools:
  * electric forge
  * metal tongs
  * pipe
  * heavy battery
  * crucible
  * sheet metal
* Spawn in materials:
  * glass shards (3+)
  * sulfur
  * scrap metal
  * charcoal
* Save (and maybe make a backup of the save so you can go back)
* Craft a `glass flask`, takes **an hour** - note the proficiency gain is about **4%** (possible scaled by focus)
* Craft a `pair of tinted glass`, takes **an hour** - note the proficiency gain is about **6%** (possible scaled by focus)

# Expected behavior

Both examples of glassblowing recipes take an hour (without glassblowing proficiency). They should give the same amount of proficiency.
I'd even be willing to argue that the more complicated recipe (flask here, since it has a `3x`multiplier instead of the `2x`for the tinted glass) could give _more_ experience since it if harder (or more involved) with the proficiency.

# Versions and configuration
```   
- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.E-6161-gac84e5c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]
``` 

# Additional context

Looking at raw numbers here it seems only base recipe time is credited to proficiency practice. (8h practice needed to learn glassblowing, 1h should give 12.5%, 4% gain for the flask is a third of that hour (unpenalized time for the recipe), 6% for the tinted glass is half an hour (again unpenalized time for the recipe).

This "inverse" application of the duration penalty towards experience gain can get quite significant but is even obvious in this simple comparison of two recipes.

**Comment by anothersimulacrum** [comment]
This is intentional. The recipes can have proficiencies defined so that they give a bonus to learning speed for more complex tasks or to avoid this if wanted.

**Comment by DoctorVanGogh** [comment]
Well, I'm not going to re-argue my point about excessive values, although this exacerbates those in my mind. What I will say instead is:

**This could do with some sort of hint for the player**. Like add a second line under "This will take XYZ% of the normal crafting time..." for example something like

```
This recipe will take 750% of the normal time because you lack some of the proficiencies used.
Completing a craft, you may gain the following amounts of knowledge: Foo (4%), Bar (7%) ...
```

**Comment by anothersimulacrum** [comment]
That's a good idea. Similarly, proficiencies do a poor job of communicating when you will not learn them because they're dependent on another one you do not know.

**Comment by I-am-Erk** [comment]
Regarding that last point, actually I think if a recipe required a proficiency you lack the prereqs for, we may want to consider giving you some xp in the prereq for doing it, even if the prereq isn't part of the recipe. That, or we need some more complicated relationships than just prerequisites such as "learning this proficiency is easier with proficiency X, but doesn't require it". Personally I prefer the first one.
