### ISSUE TITLE
Survivor map reveals destroyed cabin road

### ISSUE THREAD

**Issue by natsirt721** [CleverRaven/Cataclysm-DDA#44371]
# Describe the bug
When using a survivor map, the 'hidden' dirt road tiles leading up to the destroyed cabin and barn are revealed as being part of the road network. Because no other Forest tiles are revealed when the map is used, it is immediately apparent that something unique is there and is worth investigating. 

# Steps To Reproduce
1. Find a destroyed cabin
2. Note the location, spawn a new survivor and get near enough that a survivor map would reveal it but that the character hasn't revealed the cabin area
3. Spawn a survivor map and use

Observe that the four dirt road tiles (F on the map, to blend with the surrounding forest) are revealed as part of the road network.

# Expected behavior
The hidden dirt road is not revealed as being part of the road network.

# Screenshots
Unfortunately I didn't think to screenshot the map before I explored the area :/  I can do some more investigation if that is warranted.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-6176-gf550509 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Beta National Guard Camp [national_guard_camp],
    More City Locations [cityside],
    More Locations [more_locations]
]

# Additional context
It is definitely possible that this is intentional, perhaps the survivor that wrote the map was based at the destroyed cabin. Given the frequency at which radio towers with survivor maps are found in the rural areas these days, it makes it pretty easy to discover these otherwise totally hidden areas and their quality early-game loot.

**Comment by Amoebka** [comment]
To be fair, the "hidden" cabin shouldn't be hidden at all. Secret locations with the same overmap notation as forests is an extremely gamey thing. It a building the same size as other cabins, it should be visible the same way then when surveying the land with binoculars.
