### ISSUE TITLE
note_96a doesn't make sense with current mechanics

### ISSUE THREAD

**Issue by meelock** [CleverRaven/Cataclysm-DDA#44383]
# Describe the bug       
` "text": "\"Check your friends for bites, don't let them hide it and turn on you.  Only way out is to shoot em in the head.\""`
Does not make sense, as bites are currently treatable with any manor of antiseptics.

# Steps To Reproduce

None

# Expected behavior

Survivor notes to make sense with the game's lore and game mechanics.

**Comment by Qrox** [comment]
May the survivor who wrote it down didn't know bites could be cured (watched too many zombie movies but didn't play CDDA, presumably), their friend died, and then came back as a zombie later.

**Comment by ZhilkinSerg** [comment]
That is a non-issue.
