### ISSUE TITLE
Haul Functionality to Get Menu [Request] [QoL]

### ISSUE THREAD

**Issue by CodyForrester** [CleverRaven/Cataclysm-DDA#44412]
# Describe the solution you'd like
"Drag to Self and Start Hauling" to be added to the Get Menu when you try to grab an item and cannot store it, as an alternative to "Dispose of X and wield Y"
![unknown](https://user-images.githubusercontent.com/3632265/94277198-3662d980-ff17-11ea-8e7a-de3a83fc321b.png)
It would be added to the above menu as a second option, where it then drags the item onto your square and you start hauling as normal.

Current functionality requires you to use the `/` advanced management window to do this yourself which _does_ work, but could be made smoother.

**Comment by gkarfakis19** [comment]
This sounds like a large non-trivial change in code. I'd be happy to give it a shot.
