### ISSUE TITLE
Leatherworking proficiency not levelling up

### ISSUE THREAD

**Issue by Torres84f** [CleverRaven/Cataclysm-DDA#44423]
# Describe the bug

When crafting anything with Leatherworking proficiency the status screen shows no progress towards acquiring it, I was able to get many others but leatherworking won't even show up.

# Steps To Reproduce

Craft anything leather related

# Expected behavior

# Screenshots

# Versions and configuration

 - OS: Win10 x64
 - Game Version: 0.E-6185-ge9f4d04
 - Graphics version: Undeadpeople
 - Ingame language: English
 - Mods loaded:  "dda","no_npc_food", "blazeindustries","crt_expansion","aftershock","Mining_Mod","more_survivor_stuff","P_Caches","Dorf_Life"

# Additional context

**Comment by anothersimulacrum** [comment]
You cannot learn a proficiency if you lack it's prerequisites, which for Leatherworking is "Principles of Leatherworking". This should be communicated when it happens (#44377).

**Comment by Asseverater** [comment]
I think it's a display problem. The "Leatherworking" proficiency does not seem to show up on the proficiency screen. To see it, it's necessary to TAB a few times until the cursor moves to the recipe list, then press UP to move the cursor to where the Leatherworking proficiency invisibly sits.
