### ISSUE TITLE
A weariness indicator should be in the sidebar

### ISSUE THREAD

**Issue by dsmky117** [CleverRaven/Cataclysm-DDA#44428]
# Is your feature request related to a problem? Please describe.
Since weariness can drastically multiply the amount of time certain activities take, I think it should be something the player is able to be aware of at a glance, so they can monitor it without having to interrupt their 'cool down' activity.

# Describe the solution you'd like
Add some indication of weariness to the sidebar. With the current, build 11035, implementation of weariness, I have to regularly interrupt my reading/waiting to check if my level of weariness has gone down. Log messages are helpful, but can be hard to keep track of when the ~~goddamn ducks keep flying over the flowing deep water~~ log is filled with other messages, and it's not always straightforward to translate a lack of log messages to mean that I am no longer weary.

# Describe alternatives you've considered
Keep interrupting my waiting to check the character sheet.

# Additional context
None.

**Comment by anothersimulacrum** [comment]
It should also display current activity level.

**Comment by AlexMooney** [comment]
I've got a weariness sidebar display hacked up this morning, though it will surely conflict with #45316.  I expect to have a PR up this week, after I've got all of the layouts working, but it's likely going to have to wait on the activity tracking improvements.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/weariness-information/25406/6

**Comment by Scintile** [comment]
Have to say it - there should also be more indications what weariness actually does. Like decreased speed. I once kept getting killed by a giant fly - it was attacking me like 20 times during my 1 attack and i couldnt understand why. Turned out i was extremely weary

**Comment by anothersimulacrum** [comment]
@AlexMooney Are you still working on this? If you are, I'd recommend you put up your PR, conflicts can be resolved later.

**Comment by AlexMooney** [comment]
I've been sitting on it waiting for the other PR.  There doesn't seem to be a good way of displaying how tiring the current activity is, but I think that will change with #45316.  I'll put the PR up though.

**Comment by Scintile** [comment]
Any chance we can get an indication of how weariness actually affects you? Like in the "Speed" tab having something like "Moderately Weary -30% speed"

Because i once was very confused why i was getting killed by a large fly that was attacking me 10-20 times for my 1 attack.

**Comment by anothersimulacrum** [comment]
As soon as activity is displayed. It's effect is entirely dependent on the activity level of an action, so it cannot go in the speed tab.

**Comment by anothersimulacrum** [comment]
(Of note, activity feedback won't be super useful until #45316, but it'll be at least something that people are aware of and so is reasonable to provide feedback based on).

**Comment by Scintile** [comment]
Im not 100% sure i understand how weariness works, but i thought it just makes it so your actions are slower? Like decrease in speed stat

You are saying weariness affects different tasks differently? Like you attack twice as slow, but do something else only 20% slower?

**Comment by anothersimulacrum** [comment]
Yes.
If you get yourself extremely weary, you'll attack with 1000% of the original cost, but sewing or other light activities would only be 200% of the original cost.
If you're just lightly weary, it's 125% for attacking and other extremely exerting activities, but all other activities are unaffected.

**Comment by Scintile** [comment]
Thanks a lot for the explanation, wish it was a bit more clear in the game itself

**Comment by anothersimulacrum** [comment]
Yeah, it's dreadfully opaque, and it should not be.
