### ISSUE TITLE
Codeblocks apparently still won't compile

### ISSUE THREAD

**Issue by ModDownloading** [CleverRaven/Cataclysm-DDA#44425]
Related to #44387, the error still seems to be here and is preventing Codeblocks from compiling the game properly:

![Error1](https://user-images.githubusercontent.com/25691743/94325939-02b39e00-ff6f-11ea-88d6-cf8898a28975.PNG)
The error message in the build log

.
![Error2](https://user-images.githubusercontent.com/25691743/94325946-12cb7d80-ff6f-11ea-8fa8-ad1382590ce6.PNG)
The location of the error in animation.cpp

# Steps To Reproduce

1. Download the Cataclysm DDA source code from github
2. Extract the code, open CataclysmWin.cbp with Codeblocks
3. Build the code

The code I used was github a61d912, on 9/25/2020

**Comment by ZhilkinSerg** [comment]
Clear `obj` folder before compiling.

**Comment by ModDownloading** [comment]
Where exactly would I find the obj folder? There doesn't seem to be any folders like that appearing when I try searching for it in the Cataclysm-DDA-master code I downloaded.

**Comment by ModDownloading** [comment]
Ok, I've located the Clean and Clean Workspace options in Codeblocks and ran them, it printed out "Cleaned Cataclysm - Release", but when I then tried to compile it the same issue appeared.

**Comment by ZhilkinSerg** [comment]
Which CB version are you using?

**Comment by ModDownloading** [comment]
Codeblocks 17.12, I will install the new update though, sorry about that.

**Comment by ModDownloading** [comment]
Ok, updated to 20.03 but the issue is still there for some reason.

**Comment by ZhilkinSerg** [comment]
Check `#defines` tab in project build options. It should look like this:

![image](https://user-images.githubusercontent.com/16213433/94354064-1d296c80-0080-11eb-88ca-9e714ad20f53.png)

If it is not - you are not using latest version with fixed CBP file.

Also try using git to fetch changes instead of downloading zip-archive.

**Comment by ModDownloading** [comment]
Checked Codeblocks in the place you indicated, it looks the same to me:

![Project Build Options](https://user-images.githubusercontent.com/25691743/94367786-cab37480-00ae-11eb-8ced-dde32d532567.PNG)

Cloning the source through git now though, going to see if that fixes it.

**Comment by DDSNA** [comment]
Bumping this because I am still encountering the precise same situation and errors but on the current version
