### ISSUE TITLE
Moving item stack from one container to the other leaves empty stacks behind (causing crash)

### ISSUE THREAD

**Issue by sumpfralle** [CleverRaven/Cataclysm-DDA#44424]
# Describe the bug

Moving stacked items (e.g. a number of seeds) from one container to the other ("insert into the target") properly increases the item count in the target, but leaves a zero-stack of the item behind (zero count, zero weight, zero volume). Dropping ("d") such zero-stacks is impossible (cannot be selected for dropping). Trying to drop them via the advanced inventory ("/") window causes a crash.

# Steps To Reproduce

1. Move some seeds of the same kind into a backpack and another few of them into another container (e.g. a bag).
2. Select the bag in the inventory window ("i").
3. Press "i" for inserting more items into the bag.
4. Select the other seeds (being in the backpack).
5. Confirm the selection.
6. Drop the target container (the bag).
7. Open the inventory and try to move the zero-count stack of seeds onto the ground.
8. Crash occurs.

# Expected behavior

There should be no remaining zero-count stack after inserting the seeds into the other container.

# Versions and configuration

* working version: https://github.com/CleverRaven/Cataclysm-DDA/tree/cdda-jenkins-b11033
* broken version: https://github.com/CleverRaven/Cataclysm-DDA/tree/cdda-jenkins-b11034
    * maybe 1f54dfe6e1d87f02a1b2b16788f69646171d6f27 is the culprit

 - OS: Debian testing
 - Game Version: https://github.com/CleverRaven/Cataclysm-DDA/tree/cdda-jenkins-b11034
 - Graphics version: tiles
 - Ingame language: English
 - Mods loaded: default

# Additional context

[save-container-bug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5285577/save-container-bug.zip)

In the save game the character wields a "Seed Bag" and wears a MOLLI backpack. Press "i", select the Seed bag, press "i", select the seeds, confirm the move. Drop the Seed bag.

Confirm that you are still carrying zero-count stacks of the seeds that were moved.

Try to put these stacks onto the ground (in the advanced inventory window).

**Comment by Xpyder** [comment]
Note, if this happened to you and you have the "empty" items, you should be able to destroy them by doing the following (if they're not cleaned automatically):

drop the containers that hold the empty items onto a fire pit
Unload on ground the items (U by default I think)
move everything you want to keep out of the fire pit
[note, at this point you can use the advance inventory "move all" to move the empty items if you need to reposition]
light a fire there

Note: metal dupes may require a very hot fire to destroy, but if you have another way to destroy them (maybe move them into a trash container then throw that into lava)
