### ISSUE TITLE
Bugged items giving infinite charges

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#44440]
# Describe the bug
there's a weird quintessential asprin that can't be inserted into stuff, and respawns a full stack of asprin when the game reloads.
it happened with a couple other items too, so it's probably some sort of overflow error related to either item stacking or something in the inventory system

# Steps To Reproduce
not sure to reproduce in other saves
Load the attached save
insert the asprin into the pouch
note that there's a quintessential asprin still on the ground
try to insert the quintessential asprin into the pouch
note the error message
save, exit, reload
note that the pouch now has more asprin, and the asprin on the ground has respawned
try to move the new asprin to the pouch
note the quintessential asprin again stays on the ground

Feel free to experiment moving it and the other quintessences to see what weird effects you can create.
For example you can move the quintessences using the Advanced Inventory move all but they stay bugged
Or after moving the items, try consuming the quintessential asprin left behind

How did it happen?
Not sure
In my save, it crashed a few times while interacting with inventory even across saves and game restarts, so I decided to try and "refresh" my inventory by dropping and unloading everything, then re-wearing and inserting stuff into my clothing.  that's when I encountered this.

# Expected behavior
when I pick up a stack, for it to move all items and not leave behind a plato's shadow.
when I reload a save, I expect it to not spawn a new stack of items

# Screenshots
Start of example test
![1 - start](https://user-images.githubusercontent.com/12039454/94351456-802deb80-000d-11eb-9917-8064c6322266.png)

Inserting items into pack
![2 - inserting](https://user-images.githubusercontent.com/12039454/94351465-8f149e00-000d-11eb-80a7-f93847c87a94.png)

Quintessential shadows left behind (note the 0 volume and 0 weight for all)
![3 - quintessences](https://user-images.githubusercontent.com/12039454/94351469-9b98f680-000d-11eb-8bd4-955939d28157.png)

Trying to insert the shadows into the pack (take note of how even though they're selected, the icon didn't change to +)
![4 - re-inserting (note that while selected they don't have +)](https://user-images.githubusercontent.com/12039454/94351474-a9e71280-000d-11eb-87f9-f033b2ac1a38.png)

Errors after tying to insert the shadows into pack
![5 - error log](https://user-images.githubusercontent.com/12039454/94351480-c1be9680-000d-11eb-87cd-b320bb815c39.png)

Item counts after saving and reloading.  (Note how total counts differ from the start of test by exactly the amount we started with, but not 1 stack worth of items for each)
![6 - after reload](https://user-images.githubusercontent.com/12039454/94351489-d69b2a00-000d-11eb-9454-31cb1037dd65.png)

# Versions and configuration
- OS: Microsoft Windows 10 Pro
    - OS Version: 10.0 1909
- Game Version: 0.E-6259-g34af6ba [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key]
]
![0 - launcher config](https://user-images.githubusercontent.com/12039454/94351514-51644500-000e-11eb-8596-c0699a01eab7.png)

# Additional context

World attached
[Caliente.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5287417/Caliente.zip)

Here are the crash logs, the crashes were earlier today, but I did a bunch of save and reloads so I don't know if they still have anything useful.
[crash logs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5287420/crash.logs.zip)

**Comment by natsirt721** [comment]
Dupe of #44424, just wait for the next build to be available on the launcher.

**Comment by Xpyder** [comment]
Just reproduced by inserting from pack to pouch, and trying to move on advanced inventory did indeed crash.  I concur this appears to be a duplicate (didn't find that in my original search).

Closing as dupe
