### ISSUE TITLE
Weird rendering error's in ASCII

### ISSUE THREAD

**Issue by Phenomphear** [CleverRaven/Cataclysm-DDA#44445]
![8fMRtOHMeQ](https://user-images.githubusercontent.com/28910998/94355224-4b368e80-0037-11eb-94de-049c98674d93.gif)

Not sure how to explain this, but there seems to be some issue with the screen drawing in ASCII mode.

Windows 10
Experimental 11037 

[
"dda",
  "no_npc_food",
  "aftershock",
  "blazeindustries",
  "crt_expansion",
  "magiclysm",
  "DinoMod",
  "Cata++",
  "No_Rail_Stations",
  "stats_through_kills",
  "StatsThroughSkills",
  "fuji_mpp"
]

It more noticeable on bridges, the right side # symbol displaces 1 tile to the left and follows the vehicle. This also happens on foot in some areas. An entire line of the screen will displace 1 to the left.

**Comment by Phenomphear** [comment]
Also My gif making skills suck, so give the gif a second to start moving and watch the right side of the tree line.

**Comment by Qrox** [comment]
What does it say if you examine this tile?
![image](https://user-images.githubusercontent.com/11890223/94356852-a1521300-00c5-11eb-845e-74d6b029f15d.png)

**Comment by Phenomphear** [comment]
Oh, um, let me check. It says it has a frame
![image](https://user-images.githubusercontent.com/28910998/94356888-7d9cb780-0048-11eb-91ee-fc3afe48f3fc.png)
