### ISSUE TITLE
Sudden game slowdown

### ISSUE THREAD

**Issue by ZemZamano** [CleverRaven/Cataclysm-DDA#44452]
# Describe the bug

The game was running smoothly until at one point, it slowed to a crawl. the usual suspects like lots of zombies or items are ruled out since its a wilderness playtrough. i'mtalking about slowdown while sleeping or crafting

# Steps To Reproduce

i attached my save file. just craft a recipe that needs like an hour or so to [complete.]

# Versions and configuration

 - OS: Win 10
 - Game Version: 0.E-6259-g34af6ba
 - Graphics version: Tiles. tried undead people and ultica, same result
 - Ingame language: English
 - Mods loaded: [e.g.dda, boats, hacktheplanet, StatsThroughSkills]

edit:forgot the save file here's the link: https://gofile.io/d/2SO0tQ

**Comment by ZemZamano** [comment]
in addition things that seem weird and may be connected: my minimap is covered in a strange grid. also continuing on my chitinous armguards does not give me proficiency even though i have all requirements

**Comment by anothersimulacrum** [comment]
2/3rds of the time spent in game::do_turn (which is by far where the most time is spent), is in game::npc_overmap_move. Reminds me of #30288

**Comment by Aivean** [comment]
@ZemZamano , if this is still valid, please re-attach the save file. You can drop files directly into the github comment window.

**Comment by ZemZamano** [comment]
@Aivean 
Here is a the save file in question. just start a craft that requires some time. In this particular world there is nothing around that could tank the performance other then the NPCs

[slowdown.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5625911/slowdown.zip)

**Comment by Aivean** [comment]
Thanks you.

I can reproduce it. I wouldn't call simulation speed here excessively slow, but yes, as anothersimulacrum above pointed out, `game::overmap_npc_move()` is taking up 81% of simulation time, which is not ideal. 

![image](https://user-images.githubusercontent.com/2865203/100816340-b6fff380-33fa-11eb-958e-3942bca584c8.png)

I'll see what I can do.

**Comment by Aivean** [comment]
On my machine:
![image](https://user-images.githubusercontent.com/2865203/100816458-ef073680-33fa-11eb-80dd-4aa27d5a5225.png)
