### ISSUE TITLE
Stringed/Bowed instruments update

### ISSUE THREAD

**Issue by Nijiru** [CleverRaven/Cataclysm-DDA#44468]
# Is your feature request related to a problem? Please describe.
Having put forward #44454 last night and doing a bit of research, I've noticed some issues with instrument measurements.  A guitar is less than a third the length of a violin according to the game for instance.

# Describe the solution you'd like
1) verifying and updating sizes for various instruments / instrument cases
possible 2) add a quality of instrument between "cheap, factory-made" violin and the Golden Violin
possible 3) add cello/viola/kid's cardboard violin

# Describe alternatives you've considered
1) make this part of a luthier (instrument maker) upgrade/addition
2) leave it all alone as it is a minor, background item

# Additional context
![cdda elec guitar](https://user-images.githubusercontent.com/52872107/94375509-61912880-00d1-11eb-8096-e06fbc241250.PNG)
![cdda violin](https://user-images.githubusercontent.com/52872107/94375510-6229bf00-00d1-11eb-8f51-b0ed66cb33af.PNG)
![cdda acou guitar](https://user-images.githubusercontent.com/52872107/94375511-6229bf00-00d1-11eb-93f8-8682c41ddeb8.PNG)

**Comment by MichaelMacha** [comment]
19 cm for a guitar, even just the body, is surprisingly low. If it was more like 19 _inches_ I could understand that, but the neck is another concern. I'm thinking this was a typo.

**Comment by MichaelMacha** [comment]
I'm trying to fix this but can't seem to find any length flags for the electric guitar or acoustic guitar. In fact, in my own game the guitars are listed at "7 in", which is closer to 18 cm. I'm wondering if the length is automatically calculated somehow, and that's throwing it off?

**Comment by wapcaplet** [comment]
Electric and acoustic guitars had `longest_side` added in #44530 , but I see the bagpipes and saxophone in the same file also need a longest side defined.
