### ISSUE TITLE
Trying to pick .22 casings lags the whole game to a halt

### ISSUE THREAD

**Issue by Torres84f** [CleverRaven/Cataclysm-DDA#44469]
# Describe the bug

Picking up unused .22 caliber casings makes the game incredibly sluggish and it becomes impossible to play as the task takes forever and you just have to ALT+F4

# Steps To Reproduce

1.Provided save in additional context, load it if you wish (character in base on top of the .22 to dissasemble and try and pick after that)
2. Dissasemble .22 caliber bullets.
3. Try and grab them even with the advanced inventory manager in any significant quantities.
4. It'll take an ethernity as the game lags unendingly.

# Expected behavior

I expected some time to pick small casings but no as if I was picking individual grains of sand :D haha

# Screenshots

# Versions and configuration

- OS: Windows
- OS Version: 10.0 1903
- Game Version: 0.E-6185-ge9f4d04 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Aftershock [aftershock],
    Mining Mod [Mining_Mod],
    More Survivor Stuff [more_survivor_stuff],
    Caches [P_Caches],
    Dorf Life [Dorf_Life]
]

# Additional context

Provided save here: https://mega.nz/file/A7xw2IzC#Qv4YCHNXTdAM2G3vR127rMKcam4CufcYikB7ALmM04Y

**Comment by Aivean** [comment]
I can confirm this issue. When picking up large number of casings (2000+) game becomes unresponsive.

![pick_up](https://user-images.githubusercontent.com/2865203/100648419-c21d2b80-32f5-11eb-9a2d-8906f4599ecb.gif)

It's not immediately clear what's going on:
![image](https://user-images.githubusercontent.com/2865203/100648486-d52ffb80-32f5-11eb-99ea-26da8feeceb9.png)

I'll take a closer look later.
