### ISSUE TITLE
Headless Horror spawns seem very high.

### ISSUE THREAD

**Issue by somepersondunno** [CleverRaven/Cataclysm-DDA#44477]
# Describe the bug

Headless horrors, a zombie hulk version of the headless zombie from Aftershock, are spawning incredibly frequently as of recently. Both of my deaths in the last 2 saves I've played have been related to them, as they're a very high threat enemy. In my last game, I was on day _5_ when I first saw a Headless Horror, and almost none of the zombies near it were evolved like you'd expect if you were getting Headless Horrors spawning. Similarly, the other time I died unexpectedly to a Headless Horror, I was under my first week of play.

I don't know if this is just me being unlucky but I've talked to several people who are also having this issue.

# Steps To Reproduce

1. Make a game. 
2. Encounter a headless horror very early, I suppose?

# Expected behavior

Zombie evolution typically takes some time, though if I recall correctly it can happen sooner than later. Aftershock currently seems to have the Headless Horror spawn rate skewed.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-6333-g7f98932 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    No Fungal Monsters [No_Fungi],
    No Rail Stations [No_Rail_Stations]
]

# Additional context

This might be entirely perception-based, but it feels unintentional.

**Comment by Scintile** [comment]
Can confirm this problem. Definetly seeing a lot of headless horrors on the first day (regular start, regular evolution speed). Although in my quick test using just a core mod and aftershock i noticed that i only found horrors near apartment towers and dense urban blocks. Although this might be just a coincedence

**Comment by Maleclypse** [comment]
The same number of headless horrors have always spawned in Aftershock but they previously were taking less monster slots. So there will appear to be more because you are assuming the number of total zombies is the same.  There are in fact less zombies appearing currently and therefore a larger percentage are headless horrors.  I'm adjusting this anyway.

**Comment by Scintile** [comment]
But shouldnt they be just an evelved version of a headless zombie? And i actually have not seen a single headless zombie in my game
