### ISSUE TITLE
Error: invalid overmap terrain id "magic_basement_south" without Magiclysm

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#44475]
# Describe the bug

Seemingly random error occurred:

```
DEBUG    : invalid overmap terrain id "magic_basement_south"

 FUNCTION : int_id<T> generic_factory<oter_t>::convert(const string_id<T> &, const int_id<T> &) const [T = oter_t]
 FILE     : src/generic_factory.h
 LINE     : 462
```

I am *not* using the Magiclysm mod; there should be no magic basements in this game, so I don't know why there would be any references to one.

# Steps To Reproduce

Unknown; error did not correspond to anything I was doing at the time.

# Expected behavior

No magic errors when not using Magiclysm mod.

# Screenshots

Not applicable

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-6333-g7f98932ca4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

Error first occurred after killing a random zombie; occurred again a day or two later after waking up from sleep.

Debug log: [debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5289249/debug.log)
Save game: [NoMagiclysmError.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5289255/NoMagiclysmError.zip)

**Comment by anothersimulacrum** [comment]
Kinda a shot in the dark (the stack trace in the area talk about achievement related infrastructure), but could it be due to #42731? E.g. it's loading data (ids) from past games and then realizing that data doesn't match anything currently loaded? Both the events in the additional context are things that are checked for achievements.

**Comment by wapcaplet** [comment]
> Kinda a shot in the dark (the stack trace in the area talk about achievement related infrastructure), but could it be due to #42731?

@anothersimulacrum Good guess! Indeed, one of my past games in the `memorial` directory had Magiclysm enabled, and includes a reference to `magic_basement_south`.

**Comment by jbytheway** [comment]
Yep, that sounds like it's very plausibly the problem.  I'll try to look into it.
