### ISSUE TITLE
Breaks, as a way to make long crafting more believable

### ISSUE THREAD

**Issue by Scintile** [CleverRaven/Cataclysm-DDA#44489]
# Is your feature request related to a problem? Please describe.
With the introduction of proficiencies i sometimes find myself crafting clothing for hours. Even before that my character would sometimes spend hours crafting stuff like flour, salt, mutagen. I cant imagine that anybody would be able to do anything like that for hours with no breaks (also it might help with weariness, although i dont understand that feature well enough)

# Describe the solution you'd like
Put an option somewhere to set how often your character would take a break during long tasks, For example - "Take X minute break every Y minutes of crafting". During those breaks your character would do nothing special (basically same as Catching your breath)

# Describe alternatives you've considered
An alternative would be to just leave everything as it is now

# Additional context
Thinking about school/university. In my country schools should have at least 10 minute breaks for every 45 minutes of classes, and university has (i think) 10 minutes for every 90 minutes of classes. That is supposed to be a good enough break for tasks that are not physical, but require a lot of mental power (english is not my first language, i dont know how to explain it better)

Quick google about taking breaks during exercise tells me that you should take 3-4 minute breaks between reps. This is harder to judge, because everybody is different, and some exercise takes longer, but i think that for hard physical activity breaks should be the same (or a bit shorter) then actual activity. Although i cant remember any serious physical activity in the gmae. Maybe some crafting with vehicles?

**Comment by TechyBen** [comment]
I wonder if a toggle to avoid breaks would also be a nice addition, with the obvious moral debuf caused by it (and possibly exhaustion/weariness too). This way the character could do small bursts of intense crafting/building, in emergencies, but with a larger cost.

**Comment by pescepalla** [comment]
Or the character could simply stop crafting after a certain time with a massage about feeling tired. The player would have then the option to resume, or to go do something else for the time being.

**Comment by Scintile** [comment]
Im not a fan of manualy stoping tasks because It just feels.. weird. I have to either keep track of how long my character was crafting, or keep track of message log. And it might not be as popular as i think, but i usually alt tab to read/work/do something else when im doing long crafts
And now that im 99% sure wearines means physical tiredness (i thought it means you are mentaly tired) im even more convinced that we should have 2 systems for being tired - physical and mental. Because studying/crafting and other activities that require a lot of thought are impossible to do for a long time irl without breaks

**Comment by pescepalla** [comment]
There is have "focus" already for mental tiredness.

**Comment by Scintile** [comment]
But you only lose it directly if you are leveling up skills. And if your mood is low. And even with skill leveling your focus will not drop too low, so you can craft for a LONG time and your focus will be around 50. There is no penaly for crafting with low focus and there is no real penalty on focus for crafting for a long time

**Comment by pescepalla** [comment]
Perhaps that would be an argument for reworking focus, and perhaps for interrupting crafting when focus is too low.

**Comment by Scintile** [comment]
Then this suggestion would be more relevant if the focus will be reworked. Yeah, i agree

**Comment by Zireael07** [comment]
I am not sure if focus is going to be reworked, so I would keep this open at least until you get some sort of a feedback from the core team.

**Comment by Scintile** [comment]
I do feel like there should be a system to punish hours long crafting with no breaks. Focus might be a good place to start, but my ideas would require it to fluctuate a LOT. For example doing something for 2 hours would tank your focus, but then 15 minute break should get you close to normal. So maybe set focus to change a lot when you are doing things that require a lot of thought, and rename current system to something else (because current system is more like morale system)

**Comment by pescepalla** [comment]
I like this. Alternatively, crafting with low focus (or whatever the community will decide to implement) should increase the chance of failure by temporarily affecting the skill itself. Perhaps the character should warn the player with some message, e.g. "I feel tired, I should take a break or I could really mess up". Then the player could decide if it's worth it. This penalty could become worse and worse in time until a character is too worn out to perform even a simple task. On the other hand, I could see myself pushing it if was my only chance to escape a horde of zombies, so it should really be up to the player to decide.

**Comment by Krwak** [comment]
I have nothing against making this more realistic but increasing crafting times and punishing players even more seems excessive. You could add roleplaying messages of a type 'You take a short pause to stretch yourself.' and the likes to give it more flavor. Everything on top of that will discourage players from crafting even more.

**Comment by Scintile** [comment]
First - i think we should avoid using the word Tired. Tired should be reserved to physical tiredness, not "mental". 
And second - i think the punishment should be slightly longer crafting. Like 20% longer maximum (maybe 10%). Or people would riot. Chance to fail the craft would be too harsh. You can also make it so you can work with no breaks, but then your character might be a morale debuff and just refuse to craft for some time.

So either you take a bit longer to craft, or you risk blocking yourself from crafting for some time and a morale debuff

**Comment by Krwak** [comment]
I fail to see what is this adding to the game and how it makes it more realistic. Long crafting is one problem and now as a solution to make it more realistic you propose to make it last even longer or else player is punished? I feel like this is a joke.
If anything you should go with the opposite approach. If player takes a break from crafting he would be able to work faster and more efficiently.

**Comment by Zireael07** [comment]
I missed the fact that the breaks, as proposed, are basically 'catch your breath' - they would be more useful if they allowed you to e.g. eat, drink or take a quick nap.

**Comment by Scintile** [comment]
@Krwak  By saying "make crafting longer" i mean keep the original crafting time and add time for automatic breaks. One possible solution (although i cant think of a good way to implement it witout going over all crafting recepies) is to make crafting time faster then priginal, so that new crafting time + time for breaks = or is a bit longer then original speed

**Comment by kevingranade** [comment]
I don't see any reason to be explicit about this or especially have the player interact with it.  Just assume breaks are happening in the background.
