### ISSUE TITLE
Possible plan for tileset fallback handling

### ISSUE THREAD

**Issue by GlyphGryph** [CleverRaven/Cataclysm-DDA#4448]
This primarily addresses issue where new content added to the game is untiled, but could also easily double as a method to easily create a new tileset from scratch without having to individually define anything.

This issue and the reasons for this sort of thing were most recently brought up by #4236 and the frustration other tileset makers have experienced trying to catch up and keep up with the addition of new content.

What we need is a capable (and editable) format for a high quality fallback system that can be used to dynamically tile new content, as it's added, without the need for creating new resources.

I've looked into it, and the only thing I can see working is something I brought up way back in the day when we first started. An index/icon pairing system.

It works like this: 
We decide on a standard for png indexing - I think 8 colors should be enough. The index must be the same for every image, so it has to be decided in advance how many we'll use. We could implement it so that this only matter within-set though, and a later higher-color default could still be swapped in.
We define a pallet (indexed colour pairs), for each colour defined in-game.
We create an individual image for each ascii acharacter. The colours used here don't matter, though their indexes do.

Then we create an individual image for every ascii character using any colours (it doesn't matter which) so long as there's the right index of different colours or less.

When we come across an object that has no tile definition explicitly set to it, we read the color and symbol from the definition, grab the appropriate image and plug in the appropriate pallet. This will work, correctly, even for colour/symbol pairs that have never before existed in the game.

This can be changed by a tileset maker as part of their tileset, so if they wish they can have a customized look for "default" tiles. Our standard default should probably be a decent looking ascii-like.

PNGs do support indexing, so that wouldn't need to change.

This would also mean for many of the minimal tilesets, defining 16 color groups and 100 odd images would be the ONLY work the person would ever have to make - that's attractive, as a potential tileset designer!
##

**Comment by kevingranade** [comment]
This hasn't been reported as a problem recently, it seems like the current fallback mechanisms are sufficient.  If you're a tileset author and disagree, feel fre to repoen this.
