### ISSUE TITLE
Finishing quest reports crash

### ISSUE THREAD

**Issue by Torres84f** [CleverRaven/Cataclysm-DDA#44488]
# Describe the bug

Finished a quest for the doctor of the refugee center, the one about going to analyze a zombie blood sample and got an error message
` DEBUG    : Attempted a recipe with no available components!

 FUNCTION : comp_selection<item_comp> Character::select_item_component(const std::vector<item_comp>&, int, inventory&, bool, const std::function<bool(const item&)>&, bool)
 FILE     : src/crafting.cpp
 LINE     : 1613
`

# Steps To Reproduce

Other than doing the quest and going there to report it I don't know...

# Expected behavior

# Screenshots

# Versions and configuration

- OS: Windows
- OS Version: 10.0 1903
- Game Version: 0.E-6333-g7f98932 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Aftershock [aftershock],
    Mining Mod [Mining_Mod],
    More Survivor Stuff [more_survivor_stuff],
    Caches [P_Caches],
    Dorf Life [Dorf_Life]
]

# Additional context

Can't upload debug.log or even a .rar of it.

Uploaded it to Mega https://mega.nz/file/hzIA2bBb#SuMYf8CxNBUZsoBsNnLyr4z9LvJ-tGq53HSwf5GuL3M

Someone please let me know if it's a privilege or permissions issue because I have deactivated uBlock so I don't know why I can't upload files.

**Comment by ZhilkinSerg** [comment]
Use zip

**Comment by OliveChukar** [comment]
Could this be the same as issue  #44830 (Cannot Submit Infection Data for Analyze Zombie Blood Quest)?

**Comment by anothersimulacrum** [comment]
The debugmsg/crash seem to be separate symptoms.

**Comment by OliveChukar** [comment]
When I was testing this quest for issue #39475 a few days ago I did not have any problems. It looks like Torres84f is using mods that do not come with the game could that be the problem?

**Comment by anothersimulacrum** [comment]
Possibly.

**Comment by int-ua** [comment]
@Torres84f please comment if you are available for reproducing it and trying to figure out what mod caused this and I'll reopen this.
