### ISSUE TITLE
Javelin bag can't hold javelins, and is bulkier than a full duffel bag

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#44482]
# Describe the bug
Javelin bag both can't hold javelins (they're too long for it) and it's encumbrance when filled (with the 6 theoretical javelins) is the same as a full dufflebag which seems to be wrong

# Steps To Reproduce
Spawn 10 javelins of each type (wood, metal) and a javelin bag
try to put the javelins in the bag through either Reload, Insert, or Advanced Inventory

# Expected behavior
Javelin bags should be able to hold the one thing they're designed to hold
Javelin quivers should be nowhere near 35 torso encumbrance based on historical designs

# Screenshots

Encumberance
![1 - equipped encumberance](https://user-images.githubusercontent.com/12039454/94390481-ac2d9780-0107-11eb-8e53-f58a833be08d.png)

Javelin length is too big for bag (also volumes don't match pockets)
![2 - iron javelin stats](https://user-images.githubusercontent.com/12039454/94390522-c4051b80-0107-11eb-9292-d6e3463aed21.png)
![2 - wood javelin stats](https://user-images.githubusercontent.com/12039454/94390524-c49db200-0107-11eb-8af1-6220c4a0feed.png)
![3 - javelin bag pockets](https://user-images.githubusercontent.com/12039454/94390525-c49db200-0107-11eb-8602-5920d06bbee7.png)

Can't insert Javelins
![4 - can't load javelins](https://user-images.githubusercontent.com/12039454/94390540-cd8e8380-0107-11eb-8064-5e7861059a2b.png)

Can't pickup javelins with bag equipped
![4 - can't pickup javelins](https://user-images.githubusercontent.com/12039454/94390556-d54e2800-0107-11eb-9cf3-3ea98fb3c106.png)

# Versions and configuration
- OS: Windows
    - OS Version: Microsoft Windows 10 Pro
- Game Version: 0.E-6333-g7f98932 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key]
]

# Additional context
Looks like it's an issue with length, though the encumbrance needs to be re-balanced and the pocket volumes should probably be updated but unless it confuses the encumbrance check that's probably minor

**Comment by Wishbringer** [comment]
Can confirm that javelin bag is indeed missing max_item_length entries.

**Comment by Maleclypse** [comment]
Do you have a link to the historical javelin bags you mention preferably with pictures of how they are worn?

**Comment by EirenexTheDragon** [comment]
#24766 has more input about the Javelin bag and to give an picture of its appearance.
