### ISSUE TITLE
Crash when towing over a ramp

### ISSUE THREAD

**Issue by Venera3** [CleverRaven/Cataclysm-DDA#44485]
# Describe the bug

Crash when trying to cross onto a bridge overpass with a towed vehicle.

# Steps To Reproduce

1. In the provided save attach the Bike to the Hippie Van.
2. Try driving on the bridge

# Expected behavior

Not crashing.

# Screenshots

![Initial Setup](https://user-images.githubusercontent.com/72006894/94403640-06614380-016e-11eb-84b6-8e20f626747c.jpg)
![Crash](https://user-images.githubusercontent.com/72006894/94403657-0a8d6100-016e-11eb-8677-42c8ad86d631.jpg)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-6184-g44ea230 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context

World + Character initially from Build #11000, updated with the launcher.
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5290639/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5290640/debug.log)
[Frewen.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5290718/Frewen.zip)

Both vehicles can be individually driven up the ramp, as expected. 
Attaching the cable when the Van is on the upper Z-level causes a crash when the Bike reaches the ramp.
Attaching the cable when the Van is partly on the ramp causes the half already on the upper level to disappear from the world, no change in the 'e'xamine vehicle window.
Possibly unrelated, but one can also not drag the Bike up the ramp.

**Comment by Venera3** [comment]
The last problem (half the van disappearing) seems to be unrelated to towing, see  Issue #44534.

**Comment by anothersimulacrum** [comment]
Fairly short one:
```
#0  vehicle::tow_cable_too_far (this=0x0) at src/vehicle.cpp:6241
#1  0x0000555556584242 in map::move_vehicle (this=<optimized out>, veh=..., dp=..., facing=...) at src/map.cpp:689
#2  0x0000555556bf8e36 in vehicle::act_on_map (this=0x55556b4139f0) at src/vehicle_move.cpp:1870
#3  0x00005555565830b9 in map::vehproceed (this=0x555557710990, vehicle_list=std::vector of length 2, capacity 2 = {...})
    at src/map.cpp:443
#4  0x0000555556582de3 in map::vehmove (this=<optimized out>) at src/map.cpp:389
#5  0x0000555556220f92 in game::do_turn (this=<optimized out>) at src/game.cpp:1573
#6  0x0000555556574e9c in main (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:707
```

**Comment by Qrox** [comment]
Now it doesn't seem to crash, but the tow cable will snap off when towing over a ramp.

**Comment by hexagonrecursion** [comment]
Could not reproduce the crash with clang address and undefined behavior sanitizers - the heavy duty tow cable snaps off

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 0.F-2004-gada3852d39 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]
