### ISSUE TITLE
Randomly grabs and releases bicycle controls on the same button press

### ISSUE THREAD

**Issue by KashouC** [CleverRaven/Cataclysm-DDA#44504]
# Describe the bug

When I press the "Control Vehicle" hotkey while sitting on this bicycle, it will both grab and release the controls in one button press, but randomly it will work.

# Steps To Reproduce

1. Sit on bike
2. Hit Control Vehicle hotkey (not via examine)
3. If you successfully mount, stop driving, then repeat until it triggers.

# Expected behavior

I expect to reliably be able to grab the controls.

# Screenshots

![image](https://user-images.githubusercontent.com/17066488/94557628-1ad13900-025f-11eb-8b82-5858ddac0a20.png)

Video of the bug:
https://youtu.be/HO0gHcPu1w8

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909 (Version	10.0.18363 Build 18363) x64
- Game Version: 0.E-6346-g722966a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    Graphical Overmap [Graphical_Overmap]
]

I also edited the hand_axe recipe to require different things but doubt that's relevant.

# Additional context

Save file (i hope, never sent one before)
[Flushing.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5298880/Flushing.zip)

I'm also using a Swedish keyboard layout, but I have tried swapping to the English one, and I also had an extra keybind set so it said "# or ^", but I cleared it and set it to only "#" which is shift+3 for me, and it made no difference.

**Comment by KashouC** [comment]
Tried moving it to a non-shift hotkey just for testing purposes but still does it.

**Comment by wapcaplet** [comment]
Confirmed in 0.E-6411-gf08120bad9 (though I have seen this problem dating back before 0.E as well). It seems to occur more often (perhaps even exclusively) when the bicycle's pedals are damaged.

![image](https://user-images.githubusercontent.com/238395/94960689-8b22c900-04b0-11eb-84be-2751d5f04805.png)

Sometimes, an extra message is shown like "The Bicycle's engine fails to start" but not always:

![image](https://user-images.githubusercontent.com/238395/94960605-6af30a00-04b0-11eb-8838-c336fc305505.png)

**Comment by KashouC** [comment]
Ah so it's actually just me smashing the "ignition" for the bike until it works? Lmao.

Yeah I can confirm that's the case. I just got an arc welder an hour ago and I tried repairing the pedals now and it works fine.

**Comment by wapcaplet** [comment]
Related to #43119

**Comment by Vasil-Dimitrov** [comment]
Can confirm this behavior still happens on experimental version 0.E-10395-g4525b4f, build 11581. 
The bicycle isn't in perfect condition, the pedals are almost broken, so it could really be a missing log of engine failing to start as was mentioned in the above comments.
