### ISSUE TITLE
Ascending from Z-level 9 to 10 with helicopter causes game crash

### ISSUE THREAD

**Issue by Iceblade02** [CleverRaven/Cataclysm-DDA#44503]
# Describe the bug

Ascending 9 Z levels from the ground in a helicopter and then ascending once more will cause the game to crash.

Not really related, but starting a helicopter always fails on the first try. Also, height has no influence on damage caused by crashing. I also crashed a helicopter going at 410 kph (onto flat ground) and walked out completely unscathed.

# Steps To Reproduce

1. Enter helicopter
2. Ascend 9 levels
3. Ascend 1 level more
4. Game Crashes

Doing the same thing in debug mode on a new world with a spawned helicopter also causes the game to crash in the same way (though I did once get a different crash...)
1. New world with a pilot character
2. Spawn helicopter with fuel
3. Ascend 9 levels
4. Ascend 1 level more
5. Game crashes

# Expected behavior

The game not crashing. A simple fix could be to simply prevent ascending further?

# Screenshots

# Versions and configuration

(From the cdda launcher)

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-6365-gb19f1e7 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    sees-player icon, retrodays [sees_player_retro],
    Alternative Map Key [alt_map_key],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

The Rosepine world was generated in the previous experimental build, but the bug exists with worlds generated on the most recent build as well (0.E-6365-gb19f1e7 (tiles))

[Rosepine.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5298637/Rosepine.zip)
[debug_crash_logs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5298633/debug_crash_logs.zip)

**Comment by jbytheway** [comment]
There is an achievement for reaching level 10, so if this is forbidden then the achievement should probably change.

**Comment by wapcaplet** [comment]
Confirmed in 0.E-6411-g f08120bad9, game crashed on reaching z-level 10.

The failure to start the engines on the first try appears to be the same issue as #44349

**Comment by anothersimulacrum** [comment]
```
#0  map::get_vehicles (this=0x555557685a70, start=..., end=...) at src/map.cpp:943
#1  0x0000555556582039 in map::get_vehicles (this=0x5fc) at src/point.h:159
#2  0x000055555651bfff in map::generate_lightmap (this=<optimized out>, zlev=<optimized out>) at src/lightmap.cpp:501
#3  0x0000555556233275 in game::draw (this=0x5555580f4970) at src/game.cpp:3571
#4  0x0000555556b67f68 in std::function<void (ui_adaptor const&)>::operator()(ui_adaptor const&) const (this=0x5555583b0bf0, __args=...) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/std_function.h:622
#5  ui_adaptor::redraw_invalidated () at src/ui_manager.cpp:251
#6  0x0000555556b68134 in ui_manager::redraw_invalidated () at src/ui_manager.cpp:297
#7  0x00005555565842fe in map::move_vehicle (this=<optimized out>, veh=..., dp=..., facing=...) at src/map.cpp:699
#8  0x0000555556bf8e36 in vehicle::act_on_map (this=0x555567b716e0) at src/vehicle_move.cpp:1870
#9  0x00005555565830b9 in map::vehproceed (this=0x555557685a70, vehicle_list=std::vector of length 2, capacity 2 = {...}) at src/map.cpp:443
#10 0x0000555556582de3 in map::vehmove (this=<optimized out>) at src/map.cpp:389
#11 0x0000555556220f92 in game::do_turn (this=<optimized out>) at src/game.cpp:1573
#12 0x0000555556574e9c in main (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:707
```
In game::draw, we call `map::build_map_cache( 10 )`, which appears to be where the problem starts (see that in frame one `this=0x5fc`, meaning `this` is not valid), and I'm not sure if we're valid in frame 2 or not.

**Comment by hexagonrecursion** [comment]
Reproduced in a fresh save:

<pre>=================================================================
<font color="#C01C28"><b>==3399==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x631002d11844 at pc 0x000003099e5c bp 0x7fff873ed3d0 sp 0x7fff873ecb80</b></font>
<font color="#12488B"><b>WRITE of size 16 at 0x631002d11844 thread T0</b></font>
    #0 0x3099e5b in __asan_memcpy (/home/user/QubesIncoming/cdda-cpp/out/cataclysm-tiles+0x3099e5b)
    #1 0x507d3cf in __gnu_cxx::__enable_if&lt;!(__is_scalar&lt;four_quadrants&gt;::__value), void&gt;::__type std::__fill_a1&lt;four_quadrants*, four_quadrants&gt;(four_quadrants*, four_quadrants*, four_quadrants const&amp;) /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/stl_algobase.h:861:11
    #2 0x507d380 in void std::__fill_a&lt;four_quadrants*, four_quadrants&gt;(four_quadrants*, four_quadrants*, four_quadrants const&amp;) /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/stl_algobase.h:914:7
    #3 0x507d340 in four_quadrants* std::__fill_n_a&lt;four_quadrants*, int, four_quadrants&gt;(four_quadrants*, int, four_quadrants const&amp;, std::random_access_iterator_tag) /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/stl_algobase.h:1065:7
    #4 0x507b0ab in four_quadrants* std::fill_n&lt;four_quadrants*, int, four_quadrants&gt;(four_quadrants*, int, four_quadrants const&amp;) /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/stl_algobase.h:1094:14
    #5 0x50875aa in map::build_sunlight_cache(int) /home/user/Cataclysm-DDA/src/lightmap.cpp:303:13
    #6 0x508835e in map::generate_lightmap(int) /home/user/Cataclysm-DDA/src/lightmap.cpp:430:5
    #7 0x52da28c in map::build_map_cache(int, bool) /home/user/Cataclysm-DDA/src/map.cpp:8053:9
    #8 0x44a715a in game::draw() /home/user/Cataclysm-DDA/src/game.cpp:3034:7
    #9 0x4569e7e in game::create_or_get_main_ui_adaptor()::$_50::operator()(ui_adaptor const&amp;) const /home/user/Cataclysm-DDA/src/game.cpp:2860:16
    #10 0x4569e32 in void std::__invoke_impl&lt;void, game::create_or_get_main_ui_adaptor()::$_50&amp;, ui_adaptor const&amp;&gt;(std::__invoke_other, game::create_or_get_main_ui_adaptor()::$_50&amp;, ui_adaptor const&amp;) /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:60:14
    #11 0x4569ddc in std::enable_if&lt;__and_&lt;std::is_void&lt;void&gt;, std::__is_invocable&lt;game::create_or_get_main_ui_adaptor()::$_50&amp;, ui_adaptor const&amp;&gt; &gt;::value, void&gt;::type std::__invoke_r&lt;void, game::create_or_get_main_ui_adaptor()::$_50&amp;, ui_adaptor const&amp;&gt;(game::create_or_get_main_ui_adaptor()::$_50&amp;, ui_adaptor const&amp;) /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:153:7
    #12 0x4569cbc in std::_Function_handler&lt;void (ui_adaptor const&amp;), game::create_or_get_main_ui_adaptor()::$_50&gt;::_M_invoke(std::_Any_data const&amp;, ui_adaptor const&amp;) /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/std_function.h:291:9
    #13 0x6be83dc in std::function&lt;void (ui_adaptor const&amp;)&gt;::operator()(ui_adaptor const&amp;) const /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/std_function.h:622:14
    #14 0x6be4b7d in ui_adaptor::redraw_invalidated() /home/user/Cataclysm-DDA/src/ui_manager.cpp:282:21
    #15 0x6be54d0 in ui_manager::redraw_invalidated() /home/user/Cataclysm-DDA/src/ui_manager.cpp:328:5
    #16 0x52557a2 in map::move_vehicle(vehicle&amp;, tripoint const&amp;, tileray const&amp;) /home/user/Cataclysm-DDA/src/map.cpp:689:9
    #17 0x6e1fa3c in vehicle::act_on_map() /home/user/Cataclysm-DDA/src/vehicle_move.cpp:1885:17
    #18 0x5252e3c in map::vehproceed(std::vector&lt;wrapped_vehicle, std::allocator&lt;wrapped_vehicle&gt; &gt;&amp;) /home/user/Cataclysm-DDA/src/map.cpp:441:30
    #19 0x5251e4a in map::vehmove() /home/user/Cataclysm-DDA/src/map.cpp:387:14
    #20 0x40fbf62 in do_turn() /home/user/Cataclysm-DDA/src/do_turn.cpp:970:7
    #21 0x5218a84 in main /home/user/Cataclysm-DDA/src/main.cpp:710:17
    #22 0x7a07806121e1 in __libc_start_main (/lib64/libc.so.6+0x281e1)
    #23 0x2ff76fd in _start (/home/user/QubesIncoming/cdda-cpp/out/cataclysm-tiles+0x2ff76fd)

<font color="#26A269"><b>0x631002d11844 is located 0 bytes to the right of 69700-byte region [0x631002d00800,0x631002d11844)</b></font>
<font color="#A347BA"><b>allocated by thread T0 here:</b></font>
    #0 0x30cfe47 in operator new(unsigned long) (/home/user/QubesIncoming/cdda-cpp/out/cataclysm-tiles+0x30cfe47)
    #1 0x52fc51b in std::_MakeUniq&lt;pathfinding_cache&gt;::__single_object std::make_unique&lt;pathfinding_cache&gt;() /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/unique_ptr.h:962:30
    #2 0x524bc20 in map::map(int, bool) /home/user/Cataclysm-DDA/src/map.cpp:155:15
    #3 0x45941f6 in map::map(bool) /home/user/Cataclysm-DDA/src/map.h:317:37
    #4 0x447121b in game::setup() /home/user/Cataclysm-DDA/src/game.cpp:602:9
    #5 0x52337ba in main_menu::new_character_tab() /home/user/Cataclysm-DDA/src/main_menu.cpp:856:28
    #6 0x5231100 in main_menu::opening_screen() /home/user/Cataclysm-DDA/src/main_menu.cpp:622:37
    #7 0x52189e9 in main /home/user/Cataclysm-DDA/src/main.cpp:704:23
    #8 0x7a07806121e1 in __libc_start_main (/lib64/libc.so.6+0x281e1)

SUMMARY: AddressSanitizer: heap-buffer-overflow (/home/user/QubesIncoming/cdda-cpp/out/cataclysm-tiles+0x3099e5b) in __asan_memcpy
Shadow bytes around the buggy address:
  0x0c628059a2b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c628059a2c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c628059a2d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c628059a2e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c628059a2f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=&gt;0x0c628059a300: 00 00 00 00 00 00 00 00[04]<font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font>
  0x0c628059a310: <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font>
  0x0c628059a320: <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font>
  0x0c628059a330: <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font>
  0x0c628059a340: <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font>
  0x0c628059a350: <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font> <font color="#C01C28"><b>fa</b></font>
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       <font color="#C01C28"><b>fa</b></font>
  Freed heap region:       <font color="#A347BA"><b>fd</b></font>
  Stack left redzone:      <font color="#C01C28"><b>f1</b></font>
  Stack mid redzone:       <font color="#C01C28"><b>f2</b></font>
  Stack right redzone:     <font color="#C01C28"><b>f3</b></font>
  Stack after return:      <font color="#A347BA"><b>f5</b></font>
  Stack use after scope:   <font color="#A347BA"><b>f8</b></font>
  Global redzone:          <font color="#C01C28"><b>f9</b></font>
  Global init order:       <font color="#2AA1B3"><b>f6</b></font>
  Poisoned by user:        <font color="#12488B"><b>f7</b></font>
  Container overflow:      <font color="#12488B"><b>fc</b></font>
  Array cookie:            <font color="#C01C28"><b>ac</b></font>
  Intra object redzone:    <font color="#A2734C"><b>bb</b></font>
  ASan internal:           <font color="#A2734C"><b>fe</b></font>
  Left alloca redzone:     <font color="#12488B"><b>ca</b></font>
  Right alloca redzone:    <font color="#12488B"><b>cb</b></font>
  Shadow gap:              cc
==3399==ABORTING
</pre>

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 0.F-2004-gada3852d39 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]
