### ISSUE TITLE
Reloaded item inside pocket gives error "cannot fit into pocket while loading: item too big" and disappears

### ISSUE THREAD

**Issue by paulenka-aleh** [CleverRaven/Cataclysm-DDA#44505]
# Describe the bug

You can reload items inside small pockets which makes them no longer fit inside. After saving and loading with such a pocket item disappears and error is generated.

# Steps To Reproduce

1. Create a world with no mods, create a character.
2. Drop all items and clothing.
3. Spawn waistcoat and tailor's kit.
4. Wear the waistcoat.
5. Unload tailor's kit.
6. Put tailor's kit into waistcoat's pocket (it should fit)
7. Reload tailor's kit (you might need a couple of tries if it appears on the ground, there was one time when I somehow dropped it automatically while trying to reproduce, but usually you can reload it).
8. Observe that loaded tailor's kit no longer fits into your pocket.
9. Save.
10. Load.
11. Observe "src/item_contents.cpp:324 [void item_contents::combine(const item_contents&, bool)] error: item tailors_kit cannot fit into pocket while loading: item too big"
12. Move around. Your tailor's kit and 400 thread are gone for good.

# Expected behavior

1. You shouldn't be able to load/reload, activate/deactivate or manipulate item anyhow without taking it out of the pocket (well there might be some exceptions, but they're more exceptions than the rule). So if you want to load, unload, activate or deactivate something, make a check afterwards that the item still fits into the pocket and, if not, ask the player what to do with it (drop, wield. store in inventory).
2. Ensure items do not disappear on load. there might be many reasons why item size has changed (normally a bug or a change related to capacity of the container's pockets or size of the item. There might a another not yet discovered bug that could cause similar error. My character had a spare tailor's kit, but in some cases losing an item on load might be a death sentence. Drop item on the ground or generate a message but keep it in the pocket, it won't be a game-breaker.

# Screenshots

![image](https://user-images.githubusercontent.com/4825508/94594580-4a4d6900-0292-11eb-8d01-9cc45ae9a6d0.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-6384-ge4f17b2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [] (English)
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Bionic Slots [cbm_slots],
    No Rail Stations [No_Rail_Stations]
]

# Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5300847/debug.log)

Save file has empty world with a waistcoat-wearing character, tailor's kit and 400 thread. Reload tailor's kit to reproduce.
[Pocket issue replicator.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5300873/Pocket.issue.replicator.zip)

**Comment by throttlekitty** [comment]
Having this very issue with an acetylene torch loaded with gas.

v 0.E 7357 g86a33e
Shared mod with OP is Bionic Slots.
