### ISSUE TITLE
No weather animations

### ISSUE THREAD

**Issue by halfahermit** [CleverRaven/Cataclysm-DDA#44510]
# Describe the bug

I don't see rain/snow animations in experimental. "Animations" and "Rain animation" are both true in settings. The problem is in all tilesets and ascii.

**Comment by wapcaplet** [comment]
Confirmed in 0.E-6411-g f08120bad9 - no rain or snow are visible in UltiCa, RetroDays+, BrownLikeBears, or ASCIITiles.
