### ISSUE TITLE
Butchery of short strings takes 20 minutes, when disassembly takes 5

### ISSUE THREAD

**Issue by tivec** [CleverRaven/Cataclysm-DDA#44528]
# Describe the bug

Disassembly of short string into thread takes 5 minutes via the disassembly menu, but 20 minutes via the butcher menu.

# Steps To Reproduce

1. Place a single short thread on the ground.
2. Open disassembly menu to see the expected 5 minutes work time to make 50 thread. Close the menu.
3. Press B for butcher while standing on top of the string. Watch the time show 20 minutes.

# Expected behavior

Butchery of short strings should take as long as disassembly of strings.

# Screenshots

Butcher window:
![image](https://user-images.githubusercontent.com/717574/94691961-42450600-0332-11eb-9b83-713cca3073b2.png)

Disassembly window:
![image](https://user-images.githubusercontent.com/717574/94691918-35281700-0332-11eb-8406-ac4ae348eed4.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-6389-g6b0ba7e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    C.R.I.T Expansion Mod [crt_expansion],
    DinoMod [DinoMod],
    Graphical Overmap [Graphical_Overmap],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Fuji's Military Profession Pack [fuji_mpp],
    Mining Mod [Mining_Mod],
    More Survivor Stuff [more_survivor_stuff],
    Blaze Industries [blazeindustries],
    Bionic Slots [cbm_slots],
    No Rail Stations [No_Rail_Stations]
]

# Additional context
N/A

**Comment by esotericist** [comment]
this looks like a consequence of some of the recent proficiency work. i don't know if it's due to proficiency logic itself, or how the new recipes were implemented, but the fact butchery and disassembly have substantially different opinions on the time is definitely concerning.
