### ISSUE TITLE
Integer overflow is triggered when the time for crafting exceeds or equal to 1 year

### ISSUE THREAD

**Issue by Kenan2000** [CleverRaven/Cataclysm-DDA#44542]
# Describe the bug

Integer overflow is triggered when the time for crafting exceeds or equal one year, happens for some reason when one checks the recipe and one lacks the necessary proficiencies, the value is correct - in days and seasons - when one possesses the required proficiencies though

# Steps To Reproduce

1. Make a crafting recipe, make the crafting time equal or greater to 1 year
2. Launch the game, find the new recipe while lacking proficiencies required in that recipe
3. One can see that the crafting time value is subject to integer overflow
4. Now acquire the necessary proficiencies
5. Open the recipe again and notice that now the crafting time is displayed correctly in days and seasons

# Expected behavior

Crafting recipe is displayed properly just like in the case of possessing the proficiencies - in days and seasons - even when the crafting time in the JSON code of the recipe exceeds or equal to 1 year

# Screenshots

![Bug](https://user-images.githubusercontent.com/43505148/94833841-aba34280-0420-11eb-8232-6141b03c1d4a.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-6414-g994a2c3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    <color_light_blue>BL9</color> [BL9],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Crazy Cataclysm [crazy_cataclysm],
    Mythical Martial Arts [MMA],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Fuji's Military Profession Pack [fuji_mpp],
    No Fungal Monsters [No_Fungi],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Crazy Cataclysm - UndeadPeople Tileset [CrazyCataclysmUDP],
    DinoMod - UndeadPeople Tileset [DinoModUDP],
    Whaleys Hair Mod (UDP Tweaks) [WHALEYHAIR_UDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP],
    Bionic Space Expander [Bionic_Space_Expander],
    CBM Equipment [CBM_Arms],
    Mining Mod [Mining_Mod],
    More City Locations [cityside]
]

# Additional context

The JSON file with the recipe itself [message.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5313398/message.zip)

**Comment by CoroNaut** [comment]
I'm pretty sure a crafting time of 1 year was on nobodies mind, but dam that 141750% time increase is big. Probably should cap that or just make it impossible to craft after a certain amount.

**Comment by RoyBerube** [comment]
I would prefer if the calculations were additive instead of multiplicative. This craft time in this example would increase by 2250% instead of this insane amount.

And it would reduce the likelihood of integer overflow happening.

**Comment by RoyBerube** [comment]
I think I see the problem. recipe.time is stored at 100 per second. When divided by 100 it can store at most 21,474,836 seconds in a 32 bit signed int. That is 35.5 weeks.

On a positive note, the recipe penalties have been reduced by a lot since this issue was submitted. The longest recipe I can find- with no proficiencies - is oversized winter survivor boots at 4 weeks 4 days.

**Comment by anothersimulacrum** [comment]
Seems like recipe time should be a `time_duration`, instead of an `int` (moves).
The recipe shown here is for some sort of third party mod, I'm not sure this was every an issue in core.

**Comment by RoyBerube** [comment]
> 
> 
> Seems like recipe time should be a `time_duration`, instead of an `int` (moves).
> The recipe shown here is for some sort of third party mod, I'm not sure this was ever an issue in core.

That would work. And change time_duration internally to int64_t to squash the bug. Will get on that - should not take long.

**Comment by anothersimulacrum** [comment]
> > Seems like recipe time should be a `time_duration`, instead of an `int` (moves).
> > The recipe shown here is for some sort of third party mod, I'm not sure this was ever an issue in core.
> 
> That would work. And change time_duration internally to int64_t to squash the bug. Will get on that - should not take long.

There be some resistance to that [(see the code style guidelines)](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/CODE_STYLE.md#code-guidelines). Are you sure there is no other way to fix it than that?

An easy alternative is to just divide the time taken by `INT_MAX`, and check that the proficiency multipliers are not greater than that.

**Comment by RoyBerube** [comment]
As it turns out time_duration is fine with an int for internal storage. The simplest approach is to change about 4 methods to return int64_t, and change a few static casts to int64_t. No changes needed to any logic.

Maybe I'm being lazy today, but the simplest approach seems like the best right now. Will do a PR with what I've done.
