### ISSUE TITLE
Feasibility of making Cooking more realistic 

### ISSUE THREAD

**Issue by Giagantic** [CleverRaven/Cataclysm-DDA#44540]
# Is your feature request related to a problem? Please describe.

As it stands Cooking is no different from other forms of crafting ie, stand there and wait till X's percent raises to 100% but that is especially incongruous in relation to Cooking. Cooking often involves a lot of waiting in real life, like letting a meat stew in order to break down the sinew and tenderize the meat. Other examples include bread needing to be proofed, soups and sauces needing to be reduced, the list goes on and on but the current system is very anemic and stale on top of being woefully inaccurate. 

# Describe the solution you'd like

Cooking should have a greater emphasis on less active involvement of the player and not all recipes should require the player to wait til the percent reaches 100% as you stand there "crafting". Instead, Cooking should work similar to smoking food in that there is a element of time involved without the players active involvement, this being said certain dishes should require occasional input such as stirring, adjusting temperature, making sure it isn't burning and so forth. 

One of the more obvious examples of the strangeness of the current Cooking is that of Tea which requires your total concentration to craft when in reality one can boil water without standing there like a hawk. We should be able to do other things whilst the water boils and our intervention into this process should decide whether the end result is simply clean water or tea. 

**Hypothetical Cooking Scenario Soup**
Step 1: Prep the food which could include the prepared stock, the bouquet garni, or the mise en place  
Step 2: Bring the Stock to a simmer
Step 3: Add the ingredients
Step 4: Let Simmer for X amount of time based on recipe 
Step 5: Serve or prepare for storage

Each step and how high you cooking skill is would determine the end result and the overall quantity and quality of the product. There would also be consequences to cooking without paying attention which includes potentially ruining your dish by overcooking or burning, the need to ensure the source of heat is kept on or turned off in order to not waste energy or supplies. 

Step's 2 and 4 would basically occur in the background enabling you to go about other things such as reading or crafting other stuff even starting other cooking project though not necessarily on the same fire. This would mean that you may have to make another source of heat or at least have one prepared such as having 2 or more hotplates at hand. This would also enable us to batch craft in a more natural manner then what is current in game (basically non-existent outside of the whole NPC bonus to crafting time). 

I also think that this addition would play to the games emphasis on consequence of not paying attention as an inattentive cook is likely to spoil their product or even make them sick due to undercooking meat.

Positives of this system:
1. Ability to multitask on various different projects
2. More realistic way to go about cooking and more player involvement in ways that are actually compelling
3. Works well with the new systems of proficiency and Weary-ness as the downtimes wouldn't unnecessarily tax your abilities if you choose to relax in the downtime and would be a more effective use of the time itself. 

Negatives of this system:
1. Could become tedious depending on implementation and how far you take the various steps of cooking
2. May add a large number of mid-stages that further clutter your inventory with "In-Progress" tags

**Comment by OtpalTS** [comment]
I feel like the example you have of making tea could be solved by making it like a jar of saurkraut or tanning hides. But while I enjoy cooking in real life, simulating it in detail in CDDA would probably not be worth it. Just the image of making bread scares me.  Mostly cause IRL I can easily tell how much time has passed but in Cataclysm I lose track way too often. Especially when ending a session.
