### ISSUE TITLE
Re-order Profession list and display point cost

### ISSUE THREAD

**Issue by GlyphGryph** [CleverRaven/Cataclysm-DDA#4455]
I'd like to display the point cost in the name of the professions, and re-order the profession list by Profession Cost. The further you move down, the more expensive they would get.

It would still be alphabetical within items of the same cost, and survivor would still be selected by default, but I think it would be useful to be able to see, at a glance, what cost group an item belongs in. There are a LOT of professions, so it's important people be able to get as much information from the listing as they can without having to select each one individually, and (at least in my experience) the cost of a profession is a more useful metric to group them than what letter it begins with.
##

**Comment by illi-kun** [comment]
Sorting by points is already implemented, but showing of points close to the profession names is tricky due to lack of free space.

**Comment by mugling** [comment]
Effectively resolved in `master`
