### ISSUE TITLE
Food Satiety - ideas for UI additions

### ISSUE THREAD

**Issue by DoctorVanGogh** [CleverRaven/Cataclysm-DDA#44560]
Now that #44490 has been merged, I'd like to suggest discussing where else the "Satiety" information should be displayed (or not).

# Rationale
For food items the game always (well, mostly)[1] shows calories, mass, volume & vitamins/toxins. Now that we have a display element for food satiety (which derives from all those base values) I think that element could be reused in other places to display that information.

# Suggestion
Reuse the satiety indicator in the "consumption" block of item details:
![image](https://user-images.githubusercontent.com/324067/94918793-91667480-04b3-11eb-8a63-4d1e83f527bf.png)
[Mockup - not real values]

This would allow better prioritization in food pickup without having to toggle to one specific "magic" menu just to extract certain values.

### Other (re)-use options:
- Crafting output view, although with the variable calories in food cooking this might need a `|\... - |||\.` range display similar to calories.
- Ingredient selection popup
  ```
  + Use which component? --+
  | 1 Fat         |\...    |
  | 2 Tallow      ||...    |
  | 3 Lard        ||||.    |
  +------------------------+
  ```
  Although this might need an extended discussion on which "preview" properties deserve inclusion in the selection view.
- Component subset selection popup
  (This might similarly need a dedicated discussion on which properties to display for a preview)
---
[1] Food in (sealed) containers shows a preview for the _container_. While it is nice to know how well a player can bash zombies with that can of tuna, this type of preview is somewhat putting the ~~cart~~can before the ~~horse~~fish.

**Comment by gkarfakis19** [comment]
Amazing ideas. 
I can start working on displaying the satiety bar on the inventory item menu.
In the meantime, I've already started a PR to discuss when the exact values should be displayed on the (E)at menu.

**Comment by gkarfakis19** [comment]
I've implemented the first 2 proposed implementations. In regards to the ingredient selection popup, I think calories at the very least should be displayed there, perhaps even satiety, but implementing that seems quite a bit more difficult, so I am going to open a separate PR on it.
