### ISSUE TITLE
Ether flask bottle with only 1 ml in lab

### ISSUE THREAD

**Issue by Krwak** [CleverRaven/Cataclysm-DDA#44568]
# Describe the bug

Glass bottles that are found in one floor labs contain only 1ml of ether inside of them. 

# Steps To Reproduce

1. Make a new character in the world.
2. Find a Lab.
3. Find glass bottle of ether and see how much content is inside.

# Expected behavior

Glass bottle of ether ought to contain 750 ml of ether as it's stated so in the item description.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-6411-gf08120b [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Hauling Space [hauling_space],
    Aftershock - UndeadPeople Tileset [AftershockUDP]
]

# Additional context

When spawning a new bottle with debug mode it contains 750 ml as supposed.

**Comment by RoyBerube** [comment]
#40854 looks like the last to touch the code related to this problem.

**Comment by RoyBerube** [comment]
#40854 was the last to touch this issue. It looks like the intention is to spawn the minimum amount when no  minimum is supplied in the json file responsible for spawning the items. 

Here is an example. Bleach and ammonia will spawn with random amounts. Ether - and many others - spawns with the minimum amount. 

https://github.com/CleverRaven/Cataclysm-DDA/blob/f70482e6e8e56f4f7506987a06f4be39ce76faa5/data/json/itemgroups/science_and_tech.json#L9-L12

I see either of two ways to tackle this: 
1. Go through the json files for each spawn location and add charges data.
2. Change the source code to randomize the amount during spawn.

I'm thinking that the first option will give better control over the spawn, and does not alter the spawn issue that 40854 was addressing.
