### ISSUE TITLE
Mismatched doors on vehicles upon saving and loading.

### ISSUE THREAD

**Issue by Xenomorph-III** [CleverRaven/Cataclysm-DDA#44573]
# Describe the bug

One some vehicles, the doors will be mismatched with the rest of the vehicle. Attempting to remove/replace it with debug results in the door reverting to its mismatched state.

# Steps To Reproduce

1. Open the saved game.
2. Walk forwards and wait for the helicopter to spawn.
3. Save and quit.
4. Load back into the save.
5. Observe mismatched door.
6. Remove mismatched door with "Debug Hammerspace".
7. Add the correct door.
8. Save and load again.
9. Observe mismatched door.

# Expected behavior

The doors are not mismatched and retain their original state across saves and loads.

# Screenshots

<img width="960" alt="vehcile" src="https://user-images.githubusercontent.com/25373560/94982810-2348ad00-059a-11eb-89eb-446bda8a3071.PNG">

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-6388-g9c1c464
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: dda, no_npc_needs, no_fungal, no_rail_stations

# Additional context

[Gardner.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5321051/Gardner.zip)

**Comment by esotericist** [comment]
I had noticed this in play but hadn't caught on to the save/load step being part of it. thanks due reporting that
