### ISSUE TITLE
lumbermill_0_1 generates a huge puddle of gasoline

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#44578]
# Describe the bug

It used to have a tank of gasoline, now it has a broken generator with a puddle of gasoline in front of it

# Steps To Reproduce

Find a lumber mill or spawn it with debug.

# Expected behavior

Salvageable gasoline.

# Screenshots

# Versions and configuration
```
- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.E-6389-g6b0ba7ec31-dirty [64-bit]
- Graphics Version: Curses
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]
```

# Additional context

**Comment by Fosheze** [comment]
Can confirm. Noticed this while playing yesterday but kind of glossed over it at the time as I wasn't sure what that area was supposed to look like.
