### ISSUE TITLE
Inventory rearranged after viewing an item

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#44579]
# Describe the bug

When viewing the `i`nventory screen, if I press Enter to examine an item, then Escape to return to the inventory screen, the items are shuffled around and appear in a different order.

# Steps To Reproduce

1. Have some items in worn pockets/containers
2. Go to the `i`nventory screen
3. Select any item and press Enter
4. Press Escape

# Expected behavior

Inventory items remain in the same order before and after viewing item details.

# Screenshots

Initial inventory view on the left, after Enter/Escape on the right:

![image](https://user-images.githubusercontent.com/238395/94996713-7ce1b500-0563-11eb-964a-600504efbbf4.png)

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-6461-gf70482e6e8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by esotericist** [comment]
did some additional testing.

observations:
1.  the inventory sequencing that you get when you open the inventory window is consistent (see image a)
2.  the inventory sequencing you get after closing the details window for a specific item is *also* consistent, but different from 1.
3.  there appears to be a very strong association in the sorting for 2. with worn items (see image b)

image a: item sequencing on initial opening of inventory window
![image](https://cdn.discordapp.com/attachments/598535827169083403/762011674881818635/unknown.png)

image b: item sequencing after closing details window for an item
![image](https://media.discordapp.net/attachments/598535827169083403/762012036233560074/unknown.png)

**Comment by Qrox** [comment]
Fixed by #46451.
