### ISSUE TITLE
proficiency/survivors and the new order of things P-1

### ISSUE THREAD

**Issue by Lucewithnootherideas** [CleverRaven/Cataclysm-DDA#44575]
OKAY with the new proficiency system coming into place and an increased focus on other people of the apocalypse (by extension mission hubs) we I believe there should be discussion on both aspects and i would like to share a few ideas I have for it

Okay so the first major thing I wish to speak about is proficiency's as they are a major addition to the game, I Believe that instead of the know it or not mentality they should be treated like skills In levels and capping out there levels at lv 10 (aka mastery of that proficiency) with each level making the proficiency quicker and easier to do possibly increasing the quality of the end product. with that note I believe that disconnecting proficiency from the main skills isn't the best thing we can do instead we should make them interconnected where as lets say someone new to fabrication is trying to learn woodcarving that process will go slow for a while but as they increase there levels of proficiency in woodcarving they will also increase there ability to do fabrication (AKA as there lvs in wood carving go up they also get a set amount of exp for each lv increasing as the lvs get higher instead of just the difficulty of the item they are making) and if someone who is a master or better at making things try's his hand at wood carving his proficiency in that skill will increase far faster than it otherwise would (aka the higher your fabrication LV is the quicker you'll learn a new proficiency) and i'm not saying that mastering wood carving would be super quick in ether case but it would give another reason to master a proficiency and make it so masters of a skill don't have to spend as long focusing on one. I Also believe that combat skills should also have a proficiency system because using a spear is fundamentally different than using a dagger and swigging a bat is different than using a war hammer even though the core concepts are the same (spear and dagger both create holes and a bat and war hammer both break bones) as well as proficiency's for all styles (because you shouldn't simply know how to do all of tiquando right after learning it even if your a master at unarmed combat) and i have came up with a list of skills and there connected proficiency that i have came up with so far
chemistry/science-
chemical mixing
explosives
experimentation (figuring out what does what and how to use that thing for specific other things)
anatomy (how the creature is built what its weaknesses are and how efficient you are at dissecting something(could also fit into first aid)
cooking- increasing levels in this proficiency might increase speed but will increase the taste and possibly the nutrition of the end product
grilling
baking
electronics-
wiring (for the future housing mechanic and also a little to do with cars)
hardware (making/setting of circuit board and stuff for programmable electronics)
bioelectronics (connecting electronic systems with biological systems AKA CBMs(could also be a part of health or science)
Nuclear power systems
fabrication-this already has had a quite a bit of effort put into it by the creators/programmers so i thank them for there work and will be adding what i already know is in there
woodcarving
plastic working
knapping (possibly connected to survival)
pottery
-pottery glazing
blacksmithing (so this will be the generally working with hitting various types of hot metals with the next few things actualy being proficiency of this proficiency)
-blade smithing
-armor smithing
-chain garments
-joint manipulation (possibly something to do with mechanics)
-bronseworking
-steelworking
-finemetalsmithing
-masterworking (possibly for when you max out blacksmithing this will allow you to create mystical weapons/sufficiency advanced science while also increasing your end products with other blacksmithing tasks)
-light metals(aluminum and such
-hard metals(titanium and such)
plastic working
glassblowing
survival-
foraging
fishing
plant identification (mostly used for mushrooms and various lesser known plants untill more plant life is added in)

survival trap setting (your ability to build, set, disarm and hide various none-mechanical hunting and pit traps)

trap spotting (because i think this is a survival based skill with a large focus on perception)

stealth (possibly goes with dodging essentially your ability to use stealth in various applications (mostly starting with 
hunting/standing still but at higher levels you could actively be stealthy on the move))

farming (this will give a measure on plant growth and how your character tells how the plants are doing, like with the beginning levels you will be guessing "I think this plant looks dehydrated and sick" vs higher levels being a precise layout of what the plant needs "water 10/48 currently infested with fly larvae could use a smoker to remove them" and higher levels will also increase the output (ether being in calories, taste and or amount depending on the plant)

forest walking ( how quickly you can move though bushes, long grass, swampland and thorns and as the lv's increase you will be less likely to take damage from thornes and at higher levels it will removed completely)

tailoring- this has also had a lot of work put into it and i honestly cannot think of anything to add to it because i have very little knowledge of this field of skill so i will only be adding what is currently in the game so far (again thank the hardworking programmers for all of the work they put in so far)
fiber twisting
-basketweaveing
-ropemakeing
leatherworking
-principles of leatherworking
millinery
advanced polymer sewing
fabric waterproofing
sewing
-speed sewing
furriery
chitinworking
garment closing
cobbling
 computers- (now this is a confuseing one because the computers skill is basicaly just a hacking skill)
-programming/soft ware (getting a machine to do anything specific like show a number or do a specific action (basically do anything but tern on or off)
driveing-
heavy machinery- (basically how maneuverable a vehicle with treads is to you)
boating
helicopter piloting
airplane piloting
first aid (may be known as healthcare later)
suturing
surgery
wound wrapping
medicine knowledge (because your character wouldn't  know what pill does what when he has no knowledge of pills
medicine making
lock picking- this i honestly thing should be a proficiency of mechanics mainly because i cannot think of any proficiency's for it bedsides the honestly loosely connected safe cracking)
safe cracking
 mechanics-
car tuning (making it so vehicles run better and done break down near as often when done regularly with high skills)
vehicle maintenance (the fixing of said breakdowns whenever they happen without having to replace the corresponding part)
welding (it could be argued that this should be in fabrication as it will mostly only be done on none mechanical parts)
mechanical trap setting (the building arming and disarming of mechanical based traps)
plumbing (also primary focus on the possible new building infrastructure and a little in vehicles, the basic purpose of it is getting liquid or possibly air from one place to the other using mechanical means)
gun maintenance (how good you are at maintaining your guns condition and possibly improving it)
clockmakeing (because why not?)
swimming- (i honestly cannot think of anything to do with this besides maybe deep diving and honestly think it should be a proficiency of dodging)
deep diving
trapping- (i believe i've already divided this skill into proficiency's of survival and mechanical)
bashing weapons-
short blunt (this should focus on short blunt objects making it as you get higher in it parry and stunning begin to happen more frequently with the possibility of causing a fracture or break in foes with bones or breakable things (reduceing there combat ability for a while and possibly downing them also attacks faster than average)
-any style that works with short blunt weapons
long blunt- (would focus on stunning with additional blocking and parrying with a higher chance to break something than short blunt but attacking slower)
-any style that focuses on long blunt weapons
hammers (this will focus on breaking bones and everything lessening the combat ability of opponents big/strong enough to take a hit from one also very slow to attack)
-any style that focuses on hammers
cutting weapons-
long swords (focuses on large cutting attacks and causing bleeding and dismemberment with weaker opponents works very well with a shield)
-any style focusing on long swords
axes (focuses on making large gaping wounds with a higher chance of dismemberment and as the skill grows better the chance of getting stuck in is less and the time it takes to get unstuck is less)
-any style focusing on axes
great swords (focuses on attacking multiple opponents in a single attack or a powerful swing on a single one causing bleeding and dismemberment slow to swing)
-any style focusing on great swords 
glaves (focuses on causing bleeding on many opponents at once while maintaining distance and mobility)
-any style focusing on glaves
dodging- (honestly i think this should be renamed to agility because it would focus on moving your body in various ways)
parkour (yes i know this is already a trait but it is actually what i would call a proficiency because it is something you would learn how to do, as the lv's get higher moving across furniture is quicker and you have less of a chance of tripping yourself on them when running and at higer levels might allow you to go up a story by running at a wall with low encumbrance)

-freerunning (this is actually different than parkour in the fact that its more of a style than a method to get around faster i would say it should allow for unique combat moves when coming off of something that is affected by parkour (aka kicking something while moving over a table)
climbing (basically how good you are at scaling buildings or getting out of holes unless mountains are added)
crawling (how good you are at getting up off of the ground and how fast you are at maneuvering while off of your feet)
melee-
blocking (how good you are at blocking things with whatever is on hand, reducing damage and adding a chance to parry with shields)
grit (this is the ability to fight through the pain causing it and other negative things to have less affects in combat and at higher levels possibly allow you to keep fighting with negative health and maybe adding a headbutt attack to stun opponents (because its fun))
-unkillable ( unlocked after mastering grit it will increase the time and negative damage you sustane before you pass out or die from it making it easier to get out of a fight and time to heal yourself afterwords (aka what surgery is for))
misc objects or bar brawling (aka the ability to fight with whatever is around you i think the programmers should have fun with this one)
-drunken fist (i think drunken fist should be included with this because its sort of Jackie Chan's style)
brawling
piercing weapons-
spears (okay I think this would be unbalanced compared to other ones but i think spears should focus on holding the line and keeping the baddies back (aka keeping them your attack length away) and higher levels will let you keep more or stronger back for longer and at the higher levels should allow you to keep two spaces under lock down, this will also get a significant buff if you have two or more people holding the line with spears)

-any style focusing on spears
short swords (focuses on getting in and out wile causing puncture wounds that cause bleeding and getting out of attack range soon after works well with smaller shields)
-any style focusing on short swords
rapier (more focused on in and out quicker and without a shield bonus)
-styles focused on rapier (maybe an additional pirate style to go with fencing)
daggers (focuses on causing massive bleeding woulds while causing lower damage)
-any style that focuses on daggers
unarmed-
all styles of unarmed combat should be considered a proficiency i say mayhaps categorized by what the style focuses on?
archery-
short bows (rapid firing with decent damage more levels faster you fire and could allow you to carry multiple arrows on hand to fire faster with mastery coming with the ability to fire multiple at once)
long bows (long range and slow fire rate increasing levels allows for farther distances and additional damage)
crossbows
handguns-
quickdrawing- (increases the speed of pulling out your pistol and aiming down the sights 21 Foot rule be dammed!)
quick shooting (aka fan the hammer, it increase your ability to fire faster accurately and works really well with revolvers)
launchers-
grenade launcher
rocket launcher
other?
marksmanship-
speed loading (makes reloading your weapon quicker can be activated to fully reload a weapon without a mag (so you don't need to press R over and over to reload your shotty)
mounted guns
rifles-
sniping (how good you are at making head shots are very long distances and acquiring a new target while maintaining your aim)
machine gunning (allows you to keep your accuracy better while going full auto)
shotguns-
autoshottys (how good you are at maintaining your aim while going full auto with a shotgun)
sub machine guns- (I think this should become a proficiency of pistols)
throwing-
blunt object throwing (how fast you can throw rocks at your opponent)
blade throwing (makes it so you hit with the blade more often)
slinging (allows you to hit harder and at a farther distance with your slings (maybe have a windup meter while aiming one that dictates damage and range)
bartering- (I believe that it should be a proficiency of speaking)
speaking-
negotiation- (this will allow you to make it so aggressive people turn none hostile)
lying- (how good you are at not telling the truth with a straight face (bad liar will make this unattainable or harder to obtain))

# Describe alternatives you've considered
ignore this completely as i cannot put my code where my mouth is considering i have no skill in computer or proficiency with coding

# Additional context
this will be part one of my post because its already very long and could cause a lot of discussion so I'm splitting it into two
I will also try and watch the comments and update this post with additional ideas, i could also crosspost this into the discourse forum as well if requested

**Comment by ZhilkinSerg** [comment]
Discussion on proficiencies is here - #31610.

Also try to format your post - it is hardly unreadable now.

**Comment by kevingranade** [comment]
This issue is essentially brainstorming, that needs to happen elsewhere and the idea needs to be refined to something detailed enough to be implementable before posting on github.

As for the top level ideas:
We've discussed having levels to proficiencies and we don't want them.
I don't see a benefit or rationale for trying skill learningvspeed to proficiency gain.
Melee proficiencies are a possibility, but it's more likely we'd make the martial art technique system more detailed instead.
