### ISSUE TITLE
List items screen `V` shows same charges for items with different charges

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#44594]
# Describe the bug

When using `V` to view items in the current surroundings, all charged items of the same type such as inhalers will appear to have the same charges, even if they are all different.

# Steps To Reproduce

1. Load the provided save game [ViewInhalerSameCharges.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5322463/ViewInhalerSameCharges.zip)
2. Use `g`rab or advanced inventory to check out the two nearby inhalers - see they have different charges
3. Move closer to the top inhaler and press `V` to view surrounding items, and arrow key left and right to see the inhalers - both appear to have the same charges as the top inhaler (37)
4. Move closer to the bottom inhaler and press `V` again - see they both appear to have the bottom inhaler's charges (47) now

More generally:

1. Have two or more nearby charged items with different charges (refillable lighter, for another example)
2. Drop them both in different spots on the ground
3. Use `V` to view them both - see they seem to have the same charges

# Expected behavior

Items appear to have correct charges when viewed with `V`.

# Screenshots

Two inhalers with different charges, visible using `g`rab:

![image](https://user-images.githubusercontent.com/238395/95003898-8b4ec180-05a1-11eb-9d8e-fef5f8076318.png)

They appear to have the same charges when viewed from `V`iew items:

![image](https://user-images.githubusercontent.com/238395/95003906-a28daf00-05a1-11eb-83c1-520771724d13.png)

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-6461-gf70482e6e8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

Many item drops do not correctly have any charges, or do not have different random charges, per #44071 - it may be necessary to define `charges-min` and `charges-max` in the death-drop JSON to get different charges for item drops.

Save game: [ViewInhalerSameCharges.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5322463/ViewInhalerSameCharges.zip)

**Comment by casswedson** [comment]
> Many item drops do not correctly have any charges, or do not have different random charges, per #44071 - it may be necessary to define charges-min and charges-max in the death-drop JSON to get different charges for item drops.

I am slowly addressing this at the moment, but it should have it's own issue.

**Comment by SunshineDistillery** [comment]
You could just remove the ability to see charges with view. There's no reason a player should be able to eyeball how full an inhaler or gun is from across the street.

**Comment by wapcaplet** [comment]
> You could just remove the ability to see charges with view. There's no reason a player should be able to eyeball how full an inhaler or gun is from across the street.

I agree, that would be an entirely reasonable solution.
