### ISSUE TITLE
New quest from NPCs wrong wording

### ISSUE THREAD

**Issue by Krwak** [CleverRaven/Cataclysm-DDA#44605]
# Describe the bug

When asking any NPCS for a quest they tell the player: "I have another job for you. Want to hear about it?"
This implies that character has already done a quest for said NPC while in fact he/she didn't.
This is immersion breaking.

# Steps To Reproduce

1. Make a character in a new world.
2. Meet NPC and ask for job.

# Expected behavior

If character is seeing an NPC for the first time and haven't done any job for it previously the proper answer would be. "I have a job for you. Want to hear about it?"

# Screenshots

![image](https://user-images.githubusercontent.com/72284934/95010498-196e8a80-062a-11eb-8f88-9399afe521fd.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-6411-gf08120b [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Hauling Space [hauling_space],
    Aftershock - UndeadPeople Tileset [AftershockUDP]
]

# Additional context

I have tried talking to different NPCs  in different worlds or versions and this problem persists.

**Comment by wapcaplet** [comment]
This has bothered me for ages but I never bothered to try and fix it. Simply "I have a job for you" would be appropriate no matter how many jobs you have done before.

It should be as easy as changing this part of `data/json/npcs/TALK_COMMON_MISSION.json`:

https://github.com/CleverRaven/Cataclysm-DDA/blob/089c59fe229593d189b71292c1021d8d014ad93d/data/json/npcs/TALK_COMMON_MISSION.json#L54
