### ISSUE TITLE
The Speed King/Queen (And others) profession's clothing is a mess

### ISSUE THREAD

**Issue by Termineitor244** [CleverRaven/Cataclysm-DDA#44619]
# Describe the bug

The clothing from the Speed King profession is in conflict with one another, no normal person would have two different motorcycle sets of clothing that encumber the same spots, much less a "Speed King" which, I assume, would want to be as little encumbered as possible to drive as fast as possible.

That and it has two pieces of clothing for the legs next to the skin.

As a side note... The problem is worse if you create a "Speed Queen" since it would give you a sports bra, which conflicts with the compression top... And the "boy shorts" retain the same problem with the compression shorts in the legs...

# Steps To Reproduce

Just create a Speed King and press "+" to see the problems with its armor. Or see the screenshots below.

# Expected behavior

To have just one set of motorcycle clothing, maybe just the leather touring suit? It covers the legs (which the other clothing does not) and it sounds more appropriate to the profession because of its name and its low encumbrance...

The boxer shorts should be gone to, the compression shorts are clearly what the author intended with this profession (A Speed King).

In the case of the Speed Queen... I don´t know, do Speed Queens use compression sets of clothing too? Or is more appropriate a bra and boy shorts (Or maybe some panties)?

# Screenshots

The clothing:
![Speed King 1](https://user-images.githubusercontent.com/53200489/95024785-fbfde880-064a-11eb-8746-9b6ae7a49965.png)
The torso (and arms) problems:
![Speed King 2](https://user-images.githubusercontent.com/53200489/95024788-fd2f1580-064a-11eb-972d-4354a88b2a09.png)
The legs problem:
![Speed King 3](https://user-images.githubusercontent.com/53200489/95024786-fc967f00-064a-11eb-93d6-a937dc26cae9.png)

Speed Queen problems:
![Speed Queen](https://user-images.githubusercontent.com/53200489/95025022-50559800-064c-11eb-8732-38f8c0acbb6f.png)

# Additional context

I checked the other professions that @Fallout48 created just to be sure... And the problem repeats itself...

Combat Medic (Female):

![Combat Medic](https://user-images.githubusercontent.com/53200489/95025159-7cbde400-064d-11eb-9589-f65639e62940.png)

But maybe in this case this is what was intended? Since the Military Recruit (In which this profession is based) has a similar configuration and problems when you select it as a female...

![Military Recuit](https://user-images.githubusercontent.com/53200489/95025535-08d10b00-0650-11eb-8dc3-82903b4f32a4.png)

The Paramedic has a stethoscope that conflicts with another clothing, but I think that is just a thing of putting the stethoscope in the inventory, nothing serious. 
The EMT, Relief Volunteer and Heroin Addict professions are fine.

This professions were added in #42297 and #41211

**Comment by Fallout48** [comment]
Thanks for pointing this out, I'll try and put out a fix when I get the chance.

I think I might've gotten confused when adding the clothes, because I wasn't sure if the touring suit is something you wear over normal clothes, or if you wear it instead of a t-shirt/jeans. I also didn't realize people wear the compression clothes in place of underwear, instead of over underwear. So I'll remove the boxer/boy shorts and sports bras.

For the Paramedic, I think that's just the layering system being funky because the stethoscope and the messenger bag are both on the "Strapped" layer. It's pretty silly that they overlap each other when it should only look like this.
![female-paramedic-with-bag-on-white-background-2BF5EWR 1](https://user-images.githubusercontent.com/66659071/95026315-e696b780-0666-11eb-9af2-b98f9103858b.jpg)

Same thing with the Combat Medic/Military Recruit. Aren't people able to wear bras under their undershirts? I know some people don't do it, but still. And nearly all pictures and videos I've seen of soldiers show them wearing their vest over their uniform jacket. Though in that case that would probably be encumbering.

**Comment by Termineitor244** [comment]
> 
> 
> Thanks for pointing this out, I'll try and put out a fix when I get the chance.
> 

Thanks to you! I noticed it the other day that I wanted to play as a Speed Queen, and noticed all of the extra encumbrance... I mean, some people play with several sets of clothing, but it seemed weird to see it in the starting clothing of a profession, specially one that searches for speed above all else. 

> I think I might've gotten confused when adding the clothes, because I wasn't sure if the touring suit is something you wear over normal clothes, or if you wear it instead of a t-shirt/jeans. I also didn't realize people wear the compression clothes in place of underwear, instead of over underwear. So I'll remove the boxer/boy shorts and sports bras.
> 
The clothing system could do a better job at handling many clothes haha...

> For the Paramedic, I think that's just the layering system being funky because the stethoscope and the messenger bag are both on the "Strapped" layer. It's pretty silly that they overlap each other when it should only look like this.
> 
Yeah, I too think it´s pretty silly, one should not conflict with the other.

> Same thing with the Combat Medic/Military Recruit. Aren't people able to wear bras under their undershirts? I know some people don't do it, but still. And nearly all pictures and videos I've seen of soldiers show them wearing their vest over their uniform jacket. Though in that case that would probably be encumbering.

I do think it's possible (It's possible in-game if you don't mind a little extra encumbrance), but I'm not sure what should be the standard of female underwear in CDDA... Or if that even matters, it just seemed weird when I created the character, since it doesn't happens in other professions.

And the jacket and vest... Maybe? I don't have a strong opinion on the matter.
