### ISSUE TITLE
Partly empty jugs of milk are still "sealed"

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#44624]
# Describe the bug

In house refrigerators, when a "gallon jug of milk (fresh) (sealed)" or "gallon jug of almond milk (fresh) (sealed)" appears, it may be partially empty, despite still being "sealed".

# Steps To Reproduce

1. Go to a house and find the refrigerator
2. Check for gallon jugs of milk - they appear "sealed"
3. Check contents - they are not full

# Expected behavior

Any container that is still "sealed" should be full, as if it came from the factory that way. Any container that is not full should be "unsealed". Jugs of milk in the refrigerator should (usually) be "unsealed" and partially empty.

# Screenshots

![image](https://user-images.githubusercontent.com/238395/95029082-e1d00480-0662-11eb-8bcd-af8157a4c9c7.png)

![image](https://user-images.githubusercontent.com/238395/95029094-0330f080-0663-11eb-8697-a6853634f00a.png)

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-6518-g8e6077ef45 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

The gallon jugs of bleach and ammonia you can often find under the sink are correctly "unsealed", being partially empty:

![image](https://user-images.githubusercontent.com/238395/95029116-3b383380-0663-11eb-8197-26e82bd197bc.png)

**Comment by esotericist** [comment]
i've also experienced this with water bottles. and, shockingly, even after drinking the last of the water in a "sealed" water bottle, it remained sealed.

the evac shelters are also full of full water battles which are unexpectedly unsealed
