### ISSUE TITLE
Proficiencies aren't displayed correctly if progress rounds to 100%

### ISSUE THREAD

**Issue by Kelenius** [CleverRaven/Cataclysm-DDA#44637]
# Describe the bug

If a proficiency is close to 100% and rounds up to it, it will take more than one line, pushing the last one on the list off-screen.

# Screenshots

![image](https://user-images.githubusercontent.com/6681708/95080727-346ff600-0721-11eb-99d7-17328c81d886.png)
![image](https://user-images.githubusercontent.com/6681708/95080736-389c1380-0721-11eb-8c84-9479112d2d7d.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-6496-gef5a06d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Generic Guns [generic_guns],
    No Fungal Monsters [No_Fungi],
    Disable NPC Needs [no_npc_food]
]

# Additional context

[Tusculum.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5327381/Tusculum.zip)

**Comment by molkero** [comment]
I have this same issue with completed Principles of Leatherworking taking two lines like in issue #44668. Guessing the more two-line proficiencies you have, more get pushed off the list.
