### ISSUE TITLE
Interior of car is bright/dark when driving

### ISSUE THREAD

**Issue by Krwak** [CleverRaven/Cataclysm-DDA#44658]
# Describe the bug

When driving in a car which is sealed from light, the interior of the car changes from dark to bright each time the car moves. It will start dark, changes to bright mid movement and is again dark after the end of the turn. This cause rapid flashing when one holds '5' to continue driving. This behavior is mostly visible during night-time. Upon further inspection car doesn't have to be sealed from light for this.

# Steps To Reproduce

1. Spawn a new world.
2. Find a car that is devoid of light.
3. Wait for the night.
3. Drive and observe.

# Expected behavior

Lighting inside the car shouldn't change while driving and should stay the same, that is dark.

# Screenshots

![image](https://user-images.githubusercontent.com/72284934/95175793-4b175b00-07bc-11eb-9098-ee212f400ab8.png)
![image](https://user-images.githubusercontent.com/72284934/95175853-5f5b5800-07bc-11eb-96ff-1ce3dd29e337.png)
![image](https://user-images.githubusercontent.com/72284934/95175902-6c784700-07bc-11eb-95e4-8b73c818919b.png)
![image](https://user-images.githubusercontent.com/72284934/95175948-7732dc00-07bc-11eb-8b7e-1276653af4d0.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-6524-gccff323 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Hauling Space [hauling_space],
    Aftershock - UndeadPeople Tileset [AftershockUDP]
]

# Additional context

I have tested this further and found out that it doesn't matter if the car is devoid of light. The flashing is there with or without curtains closed or camera system on/off. Screenshots added.
First pair of screenshot is with curtains up and using night vision.
Second pair is  with curtains closed, camera system on and using headlights.

**Comment by cosmo-naut** [comment]
Can you add some screenshots please

**Comment by Krwak** [comment]
I have added screenshots as requested and found out also that curtains don't have to be closed for this behavior to be seen. Also this effect is mostly visible during night time, even in day time some appliances in the car are flashing.

**Comment by esotericist** [comment]
i was able to experience this as well with an RV.

**Comment by Aivean** [comment]
Are you referring to this (unseen section in the back of RV is temporarily revealed for one frame):
![flicker](https://user-images.githubusercontent.com/2865203/95955850-55d08200-0db2-11eb-927d-39a7166657fc.gif)
or is it something else?

**Comment by Krwak** [comment]
Yes, that's it. The unseen and blinking area can be larger or smaller depending on conditions.
