### ISSUE TITLE
UI Problem with Proficiency Display

### ISSUE THREAD

**Issue by Giagantic** [CleverRaven/Cataclysm-DDA#44668]
# Describe the bug

Proficiencies won't properly update with Principles of Welding and Manual Tooling and instead can only be found by scrolling up to "PROFICIENCIES" and to pay attention to the description wherein you will find your percent 

# Steps To Reproduce

Try to increase the percentage of either Manual Tooling or Principles of Welding (this also applies to the higher tier Welding as well). 

# Expected behavior

For the proficiency to properly increase in pecentage till you reach 100% wherein it should be highlighted. 

# Screenshots
![image](https://user-images.githubusercontent.com/69474797/95209876-d68eed00-07b8-11eb-9845-7188aa30a09d.png)

Do not take a screenshot of the crashing window. Please provide the crash logs in the "Additional context" -->

# Versions and configuration

    - OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-6537-gaa91542 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key],
    Cataclysm++ [Cata++],
    Mythical Martial Arts [MMA],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    Cataclysm++ - UndeadPeople Tileset [Cata++UDP],
    Graphical Overmap [Graphical_Overmap],
    sees-player icon, retrodays [sees_player_retro]
]

**Comment by molkero** [comment]
Principles of Leatherworking and Principles of Metalworking both take two lines, pushing bottom two proficiencies off the list.
