### ISSUE TITLE
Mounted flamethrowers don't see fuel tanks as ammo

### ISSUE THREAD

**Issue by vityav** [CleverRaven/Cataclysm-DDA#44672]
Game version:
Experimentals from b545981c506fed41a3974eb04c22c6ac683ff34c through the last month if not more

Operating system:
Arch Linux 5.8.13

Tiles or curses:
Curses

Mods active:
Aftershock
Blaze Industries
C.R.I.T
Stats through skills

### Expected behavior
Vehicle-mounted flamethrowers (or mounted RM451 flamethrowers) should see built-in tanks of gasoline/napalm and use them as fuel.

### Actual behavior
Flamethrowers think they have no ammo and have no way to be manually loaded and/or fired

### Steps to reproduce the behavior
Build a vehicle containing a tank with flammable liquid, turret mount, mounted flamethrower, and optionally a turret control unit. Attempt to fire in any mode/configuration.

**Comment by emptytriangle** [comment]
mounted flamethrowers are still unusable

**Comment by andrei8l** [comment]
This happens because the flamethrower has a `MAGAZINE_WELL` instead of a `MAGAZINE` (like `watercannon` for example). Here's a hacky fix:
```diff
diff --git a/src/turret.cpp b/src/turret.cpp
index f4fa694b1d..e897ce0227 100644
--- a/src/turret.cpp
+++ b/src/turret.cpp
@@ -153,10 +153,17 @@ std::set<itype_id> turret_data::ammo_options() const
     } else {
         for( const auto &e : veh->fuels_left() ) {
             const itype *fuel = item::find_type( e.first );
-            if( fuel->ammo && part->base.ammo_types().count( fuel->ammo->type ) &&
-                e.second >= part->base.ammo_required() ) {
-
-                opts.insert( fuel->get_id() );
+            if( fuel->ammo ) {
+                std::size_t count = 0;
+                const itype_id mag_type = part->base.magazine_default();
+                if( mag_type.is_null() ) {
+                    count = part->base.ammo_types().count( fuel->ammo->type );
+                } else {
+                    count = item( mag_type ).ammo_types().count( fuel->ammo->type );
+                }
+                if( count && e.second >= part->base.ammo_required() ) {
+                    opts.insert( fuel->get_id() );
+                }
             }
         }
     }
```
However, I'm not sure that this should be allowed. Can our unspecified, unmodified flamethrower feed from an unpressurized tank? IMO a better solution is to remove the `USE_TANKS` flag from the mounted flamethrower and possibly add a new recipe that produces a flamethrower that *can* use unpressurized tanks (mechanically, it would produce an item with a `MAGAZINE` pocket instead of `MAGAZINE_WELL`)

Any thoughts?

**Comment by anothersimulacrum** [comment]
I agree with you that your proposed better solution is a better solution.

**Comment by vityav** [comment]
Thanks for the temporary fix. I'd also be good with your proposed solution, though I do appreciate the current distinction between base flamethrower and RM451 flamethrower so perhaps two recipes? Alternately, adding a distinct vehicle mounted pressurized tank that could apply to both flamethrowers and water cannons with a `USE_PRESSURIZED_TANKS` flag, but then you'd want the whole range of sizes for pressurized tanks too.

**Comment by emptytriangle** [comment]
what if we add a fuel pump part that can be installed on a turret using a tiny electric motor that can take fuel from an unpressurized tank to a turret?

Bonus points if it can be activated from the vehicle control menu and you can choose which type of fuel to use. Water turrets should be able to shoot any kind of liquid and flamethrowers should only be able to use gasoline and napalm.
