### ISSUE TITLE
Consider defaulting to --user-dir on windows

### ISSUE THREAD

**Issue by irwiss** [CleverRaven/Cataclysm-DDA#44707]
# Is your feature request related to a problem? Please describe.
Every time i git clean -fdx I lose vs settings and have to yet again
remember I need to set --user-dir="" in startup params to see
my settings/savegames/tilesets etc

# Describe the solution you'd like
Consider defaulting to user directory, as far as I can see #35091 was the blocker to this
which is now solved. This would keep project directories tidy and even people using
launcher might see a better experience ( if launcher still unzips straight into game folder
and if they're willing to change it ).

# Describe alternatives you've considered
It's not a big deal to do this once in a while but seems fairly harmless
to have it on by default

# Additional context

**Comment by jbytheway** [comment]
To clarify your request: are you suggesting that the `USE_HOME_DIR` setting in the `Makefile` / `CMakeLists.txt` default to on, rather than off?

**Comment by irwiss** [comment]
I'm suggesting this block to have flags with opposite meaning, so user dir (or xdg) is the default and dumping stuff into game folder is the exception rather than the rule 

https://github.com/CleverRaven/Cataclysm-DDA/blob/b451654d30bed39aa3b8cf33f51ef43336eaf23a/src/main.cpp#L536-L544

But it seems there's flags at play in other OSes - may be it's too much of a hassle

**Comment by anothersimulacrum** [comment]
There's something that I consider a viable use case here of having the game be 'portable', e.g. on a flashdrive or similar, and all the data transfer with it. AFAIK, having a binary with USE_HOME_DIR set makes this impossible without running it with command line arguments (or copying the data from your home dir, which is complicated).

That said, I think using the home dir makes a lot of sense in other cases (probably all other cases), but I just don't want to disable that other use case.
