### ISSUE TITLE
Hypovolemia doesnt have a cure other than waiting. Blood can be drawn but not infused.

### ISSUE THREAD

**Issue by ShinWinddreamer** [CleverRaven/Cataclysm-DDA#44703]
After getting malled and bleeding hard i got severe hypovolemia. I drew blood earlier just in case but even though the status of the effect itself tells you to transfuse blood to not die, you can't. I tried everything but my character can not transfuse blood. the means for which  (blood bag and syringe) are there but it's not possible. And due to it being severe he will die no matter how much meat I eat or water I drink.
My complaint: Don't implement a debuff into a game that is game breaking when you haven't fletched out the counter to it, i.e. make blood transfusions possible first!

# Steps To Reproduce

1.get hammered to loose blood
2.bandage up the wounds
3.loose enough blood for severe hypovolemic shock

# Expected behavior

Loose a lot of blood and be able to replace it with blood transfusions with all the bells and whistles or remove the debuf outright until the counter has been fletched out. Because with the blood rework came also the change that you start to bleed extremely easily, no matter the armor.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-6537-gaa91542 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    No Rail Stations [No_Rail_Stations],
    Tankmod: Revived [Tankmod_Revived],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex]
]

Safe is attached
[Dark Providence.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5344251/Dark.Providence.zip)

**Comment by kevingranade** [comment]
Nothing against adding blood storage and transfusions, but their lack is not a bug, and no, we aren't going to consider rolling back bleeding.
