### ISSUE TITLE
ASCIITiles Car bug

### ISSUE THREAD

**Issue by barswine** [CleverRaven/Cataclysm-DDA#44711]
# Describe the bug
When using the tile set ASCIITiles all vehicles appear as # signs

# Steps To Reproduce
Download any of the latest experimentals and switch your tileset to ASCIITiles then find a car

# Expected behavior
The direction mapping needs to be updated

**Comment by Fris0uman** [comment]
This is a bit more complicated than for the other tilesets since it's mostly using fallbacks.  I think the issue needs c++ to be fixed.

**Comment by barswine** [comment]
Thank you im sorry

**Comment by Fris0uman** [comment]
Don't be sorry it's not your fault X) . We'll fix it eventually, but I'm just saying it might take some time.

**Comment by mlangsdorf** [comment]
![BetterIHope](https://user-images.githubusercontent.com/8007405/98021895-819bc200-1dca-11eb-8809-c61570b04b75.png)

I don't use ASCIITileset normally, so I don't know how this is supposed to work.  This image shows a patched game, with an atomic sports car turning left and some other vehicle (a sedan of some sort) SE of it, facing north.  Is this how things are supposed to look or do you want more distinction on the panel parts than "=" or "H" ?

**Comment by barswine** [comment]
More direction please, I can upload an image from the stable to show you, im sorry if this is difficult im sorry

**Comment by mlangsdorf** [comment]
An image from stable would help, yes.  I think I know the issue but it will take some thought to fix it.

**Comment by mlangsdorf** [comment]
![HowIsThis](https://user-images.githubusercontent.com/8007405/98046496-efa6b000-1def-11eb-9c7a-cf8f32f862b8.png)

Pulling the symbol from the symbols array and it looks better but possibly not perfect.

**Comment by mlangsdorf** [comment]
Alternately, if I can't get a screenshot from stable, confirmation that the latest screenshot is better would also be helpful.

**Comment by barswine** [comment]
![Capture](https://user-images.githubusercontent.com/6932457/98187663-14298780-1ed7-11eb-9767-dee24d7611be.PNG)

**Comment by barswine** [comment]
![Capture](https://user-images.githubusercontent.com/6932457/98187824-68346c00-1ed7-11eb-9664-9da2d01fe5e4.PNG)
