### ISSUE TITLE
Musical intruments can be activated regardless of their inventory position

### ISSUE THREAD

**Issue by casswedson** [CleverRaven/Cataclysm-DDA#44714]
# Describe the bug

Musical instruments can be activated from any position in the player's inventory. additionally a presumably infinite number of musical instruments can be activated at the same time.

# Steps To Reproduce

1. Spawn different types of musical instruments, flutes, guitars, harmonicas.
2. Wear, wield or have in inventory as many instruments as possible.
3. Activate them.

# Expected behavior

Playing a flute, prevents or cripples my ability to play a guitar. 
Can't play an instrument from backpack.

# Screenshots

![image](https://user-images.githubusercontent.com/58050969/95409353-0805d680-08e7-11eb-8ff3-c05fb19baa94.png)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-6537-gaa91542 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context

**Comment by wapcaplet** [comment]
Confirmed; still reproducible in 0.E-9603-g42468f6cab
