### ISSUE TITLE
Birchbark quiver (capacity 20) doesn't accept crude wooden arrows and hangs the game if you "insert" them into it.

### ISSUE THREAD

**Issue by Scorch-Mechanic** [CleverRaven/Cataclysm-DDA#44723]
Birchbark quiver (capacity 20) doesn't accept crude wooden arrows and crashes the game if you "insert" them into it. I haven't tried other kinds of arrows, but the large birchbark quiver (capacity 60) ~~seems to work fine~~ nope that one crashes if you wear it and try to insert arrows as well.

# Steps To Reproduce

1. Have a birchbark quiver (capacity 20), and wear it.
2. Wield crude arrows.
3. Open the insert menu for the birchbark quiver you're wearing.
4. Select the crude wooden arrows.
5. Process stops responding and has to be closed.

The attached save file has my character right next to a couple of birchbark quivers and they have crude arrows already in hand. You should be able to Wear a quiver and reproduce the issue immediately.

# Expected behavior
Obviously I would like the game to not crash on me when I try use a quiver for its intended purpose. 

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-6546-g51130a4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Mythical Martial Arts [MMA],
    Graphical Overmap [Graphical_Overmap],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro]
]

# Additional context

It looks like arrows only become available to insert into quivers when you're wearing them. If you try to insert arrows into a quiver that's on the ground or just in your inventory somewhere, the insert menu for the quiver (large or small) doesn't show anything available to insert, even though I have crude wooden arrows literally in my hand.

I've been able to force arrows into my quivers (all sizes) by wielding the arrows and then wielding something else and choosing "store in inventory", but only for relatively small piles of arrows. Something really weird is going on here.

# Attached files
No crash log is generated or available, the process just hangs and has to be closed.

[crude arrow birchbark quiver crash + debug log.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5345801/crude.arrow.birchbark.quiver.crash.%2B.debug.log.zip)

**Comment by Pupsi-Mupsi** [comment]
Confirmed.

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-6622-g4b4b108c28 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    GP-Mods [gpmod],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP]
]
