### ISSUE TITLE
Game freeze in overmap::place_roads

### ISSUE THREAD

**Issue by irwiss** [CleverRaven/Cataclysm-DDA#44736]
# Describe the bug

Game often freezes in `overmap::place_roads`, the problem is visible in normal
gameplay - often when using one of the map items the game freezes, breaking
with a debugger shows main thread spinning inside one of the 4 loops in
practically every case of a game freeze in last month.

Now it hit me when test suite needed to generate new world - I believe at least
a few of the "no output has been received" in the CI pipeline that i've been seeing
sometimes are spinning inside these loops too

Loops are located here: https://github.com/CleverRaven/Cataclysm-DDA/blob/ca4148daec284a19377da16f0fbb2cb4b3206da9/src/overmap.cpp#L2748-L2776

I don't believe this will help much - the dump is in the middle of modifying code
but you can grab a visual studio process dump from here:
https://static.karmaflux.com/a53ca1a90194d1ee.7z

# Steps To Reproduce

I've no exact steps to reproduce but seems likely this loop becomes infinite
if noise generates lake that's larger than expected

# Expected behavior

No freeze

# Screenshots

![image](https://user-images.githubusercontent.com/6560075/95498242-31d50100-09ac-11eb-8589-69425ee000e7.png)

# Versions and configuration
 - OS: patched Win10
 - Game Version: latest master commit (DIRTY), at this time it's ca4148daec284a19377da16f0fbb2cb4b3206da9
However I've seen the bug for a few weeks now
 - Graphics version: ~~[Tiles or Terminal]~~ Test suite
 - Ingame language: English
 - Mods loaded: Test suite with --mods=aftershock

# Additional context

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/crash-when-reading-road-trail-ect-maps/24899/7

**Comment by Mekhasheyfe** [comment]
I've been having the same issue

**Comment by Melodeiro** [comment]
Happened to me as well
