### ISSUE TITLE
Flesh Pouch consumes items when it fades

### ISSUE THREAD

**Issue by MorphingE** [CleverRaven/Cataclysm-DDA#44755]
# Describe the bug

The Flesh Pouch spell for Biomancers consumes any item inside it when the timer runs out, making them cease to exist.

# Steps To Reproduce

1. Get Flesh Pouch spell
2. Cast, and put items into it
3. Wait for the timer to go out

# Expected behavior

I don't really know what the expected behavior is, but I would imagine all the items spilling onto the ground.

# Screenshots

![image](https://user-images.githubusercontent.com/71299075/95550281-7c12ae00-09bd-11eb-8eea-dcc0b89a303c.png)

![image](https://user-images.githubusercontent.com/71299075/95550413-b4b28780-09bd-11eb-8adc-494f9b4b8b29.png)

![image](https://user-images.githubusercontent.com/71299075/95550475-d0b62900-09bd-11eb-8e4f-9b42c3e090c1.png)

![image](https://user-images.githubusercontent.com/71299075/95550498-da3f9100-09bd-11eb-8a7c-674f3b586065.png)

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-6546-g51130a4 Build 11076
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: 
![image](https://user-images.githubusercontent.com/71299075/95550601-05c27b80-09be-11eb-8e9b-34c0cf8f3712.png)

**Comment by Light-Wave** [comment]
This bug also affects hide bag, and presumably items that are removed when charges are depleted or a countdown is completed, although I'm not sure if vanilla has any such items with inventory. It seems like the item_pocket::process() functions should process inventory of such items before they destroy them, in a similar fashion as Character::absorb_hit processes worn_remains.
