### ISSUE TITLE
Game crash Segmentation fault

### ISSUE THREAD

**Issue by Rewliz** [CleverRaven/Cataclysm-DDA#44764]
The game crash while i craft.
I have not been able to see an exact reason for the crash.
If i save and start crafting and get the crash and reload and do the same thing again it might not crash again.
For example in the save i have a pickax that i'm crafting, i get the crash when i try to complete it.
Not at the end of the craft but sometime during the crafting process.

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5357178/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5357157/crash.log)
[North Bennington.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5357158/North.Bennington.zip)

**Comment by Rewliz** [comment]
Just reset the Toxins level of my character and i do not seem to get the crash anymore.

**Comment by Trioct** [comment]
Looks a lot like #43214, like the toxins are making you drop your wield item while you're using it. I assume they can do that at least.
If someone wants to fix this (may end up being me), Character::can_drop/can_unwield/drop/unwield are probably good places to start when thinking of a solution.
