### ISSUE TITLE
Junkfood Intolerance should be adjusted 

### ISSUE THREAD

**Issue by Giagantic** [CleverRaven/Cataclysm-DDA#44765]
I've been using it as of late and some of the things that are considered "Junkfood" is extremely weird and very nonsensical. It seems many of the things that are considered junkfood are merely done so due to stereotype when in reality it is entirely false to assume that they are always junkfood, for example:

A homemade hot dog with meat + casing + seasoning is apparently junkfood according to the game when in reality, just because it is a hot dog does not necessarily make it a bad thing to eat. It is merely a type of sausage, obviously many of the store bought versions are bad for you due to their dubious quality and the overall abusive industry that is meat production but that is a side-point. I could understand hot dogs you scavenged from some grocery store being bad but ones you make yourself should not be grouped together with those kinds.
![hotdog](https://user-images.githubusercontent.com/69474797/95630893-a792a880-0a50-11eb-8881-93cf9528a7f3.png)

Overall, the Junkfood tag is just slapped onto anything that MAY be unhealthy, other examples include Maple Syrup, most condiments (even the homemade variants), and so forth. Everything is unhealthy in excess but many of the things such as Maple Syrup (the real kind) have positive sides as well which are well [documented](https://www.healthline.com/nutrition/maple-syrup), obviously drinking straight Maple Syrup is bad for you but that doesn't mean it is junkfood. 

According to the in-game description: 
**Junkfood Intolerance:**
  "Something in those **heavily processed foods** doesn't agree with you.   It's possible for you to eat them, but you will suffer morale penalties  and obtain less nutrition from them."  

Should mean that you only suffer from stuff made prior to the Cataclysm for it is precisely the manufactured nature of these products that you are reacting too. From a gameplay standpoint nothing changes in regards to how you picking this trait are gonna live besides it being more accurate when you have the capacity to make your own homemade condiments, hot dogs, and so forth. 

### Table of Craftable Junkfood vs Craftable "Not Junkfood"
Here's a list of some of the things that are considered Junkfood in terms of what we can craft and some things that strangely aren't:

Craftable Junkfood | Craftable Food that for some reason aren't labeled Junkfood
------------ | ------------- 
Cake / Cookies |  Brownie / Sponge Cake 
Mexican Hot Chocolate  | Lemonade /Sweetened Versions of Coffee, Tea, etc...

The list goes on and the reasons for labeling things "Junkfood" seem very arbitrary, one fried recipe will be considered Junkfood and another won't, one thing with chocolate is junk yet another isn't. I propose just changing the Junkfood tag to only pre-cataclysm productions which could include certain ingredients such as Artificial Sugar. The point is that Junkfood by our standards isn't purely related to their fat, salt, and sugar content but also a combination of the numerous other things that are added in our industrial culture in order to both preserve, appeal, and cause cravings. Anything that is homemade and has good healthy ingredients should not be considered Junkfood as such, it being unhealthy is another thing entirely though typically it is a relationship of excess where the problems become prominent.

**Comment by lcy03406** [comment]
“Healthy” is different in game world and in reality. In reality we think those foods with high calories and artificially good taste but no vitamins or other nutritions, are unhealthy. In reality we eat too much junkfood and become overweighted.

But in the game, we and other NPC surviviors struggle in finding enough calories. Food is not too abundant to be junk. Instead, food is the currency in running our camps.

**Comment by Marrim** [comment]
Also need to consider the fact there is a line of traits relating Junkfood to refined sugar.

**Comment by Zireael07** [comment]
A better and quicker fix than overhauling the whole junkfood tag would be to make homemade hotdogs and so forth not to count as junk food.

**Comment by AdamBrezik** [comment]
Maple syrup is healthy, if you don't drink 2 litres or whatever.
Hot dog is always unhealthy because mixing fat and starch makes your liver suffer, dummy.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
