### ISSUE TITLE
Playback of music from external media player when the player character can hear music

### ISSUE THREAD

**Issue by mz2212** [CleverRaven/Cataclysm-DDA#44761]
# Is your feature request related to a problem? Please describe.
The basic idea of this feature would be to either play or pause a running media player's music when your character starts/stops hearing music. Please note that I'm not suggesting that volume is even attempted to be controlled as that could lead to potentially bad results.

# Describe the solution you'd like
The first way I thought of doing this would be to fire off a keystroke (XF86AudioPlay on Linux) that a media player can pick up and use to play/pause music. It wouldn't keep it in sync, but ideally the player should have manually enabled the feature and would know to not have their music playing before loading up a character.  

Another potential solution would be to write the state of the music in game to a file/pipe and let a helper program handle it from there. I think the solution would be less complex codewise and open up a window for other status effects to be written to a similar/the same file (say for haptic feedback or an external display).

# Describe alternatives you've considered
I guess an alternative would be to press the keyboard key myself, but I think that this way would be far more immersive.

# Additional context
An example as to how the keypress might be done under Linux can be found [here](https://shanetully.com/2012/07/simulating-mediakey-presses-in-x11/) and for Windows, I figure that the [SendInput](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-sendinput) function of the WinAPI would be used.  

If the file writing approach were to be used, I think that something similar to the save file system would work. It'd even be a good choice for the companion program because (afaict) there's already a json marsaller in place.

My C(++) is kind of rusty and I don't know what libraries are (already) in use, but I should be able to hack something together if desired. My only real sticking point is that this is a really large project and I'm not so sure where I should be looking to start.

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
