### ISSUE TITLE
Full cyborgs can not be operated in lab's autodoc

### ISSUE THREAD

**Issue by sashakiller33** [CleverRaven/Cataclysm-DDA#44773]
# Describe the bug

Cyborgs can not be restored in lab autodocks

# Steps To Reproduce

1. Disable an cyborg
2. Bring his body to laboratory autodoc 
3. Use it while body on couch
4. Get an message that autodock XI can't operate

# Expected behavior

If i remember correctly lab's autodoc should be able to restore cyborgs.

# Screenshots

![image](https://user-images.githubusercontent.com/1785731/95656445-aa68c880-0b38-11eb-99b5-57f8639a85b3.png)
![image](https://user-images.githubusercontent.com/1785731/95656458-c0768900-0b38-11eb-9346-006c8a301602.png)
![image](https://user-images.githubusercontent.com/1785731/95656468-cf5d3b80-0b38-11eb-99a8-78904ef51512.png)

Do not take a screenshot of the crashing window. Please provide the crash logs in the "Additional context" -->

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-6537-gaa91542 [64-bit] 11072
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    PKs Rebalancing [PK_REBALANCE],
    Cataclysm++ [Cata++],
    Graphical Overmap [Graphical_Overmap],
    <color_light_red>Secronom</color> [secronom],
    Arcana and Magic Items [Arcana],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Modular Turrets Remake [modular_turrets_remake],
    Civilian Salvaged Robots [civilian_salvaged_robots],
    Automations [robot_automation],
    Packaging [Packaging],
    DinoMod [DinoMod],
    Draco's Pig Mod [DracoPigMod],
    Mythical Martial Arts [MMA],
    Caches [P_Caches],
    Fuji's Military Profession Pack [fuji_mpp],
    Stats Through Kills [stats_through_kills],
    No Rail Stations [No_Rail_Stations],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Joerge Spraves Inventions [JoergSpraveMod],
    Mining Mod [Mining_Mod],
    Crazy Cataclysm [crazy_cataclysm],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Abrahms Recipes 1 [AbrahmsRecipes1],
    <color_light_blue>BL9</color> [BL9]
]

# Additional context

It look like problem is in not so long update with addition of cyborg clinic autodocks, but i could be wrong.

**Comment by Fris0uman** [comment]
That's not a bug, broken cyborgs can't be restored. You're confusing them with prototype cyborgs.

**Comment by sashakiller33** [comment]
Prototype cyborgs give same message. Or they should be on couch in alive state?

**Comment by sashakiller33** [comment]
And i'm also cocern that in message is wrong autodoc version. Inside the lab is XVI and not XI

**Comment by Fris0uman** [comment]
Dead prototype cyborg can't be saved either but the message should tell you that the patient is dead. You can only rescue deactivated prototype cyborgs.

**Comment by Fris0uman** [comment]
I just checked with aftershock on and autodoc XVI is able to rescue prototype cyborgs. The prompt says `Mk XI` because that part is hardcoded but that's just a display inconsistency with the mod.

**Comment by Night-Pryanik** [comment]
Seems like working as intended, closing.
