### ISSUE TITLE
Acid ant hills spawn regular ant queens

### ISSUE THREAD

**Issue by CamIce2002** [CleverRaven/Cataclysm-DDA#44778]
# Describe the bug

Instead of acid ant queens, acid ant hills have regular ant queens

# Steps To Reproduce

1. Find an acid ant hill
2. Teleport to the queen chamber
3. See regular ant queens fighting acid ants

# Expected behavior

Acid ant hills have acid ant queens

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-6689-g0c537af
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: dda
 -->

**Comment by wapcaplet** [comment]
Thanks for reporting. Looks like same issue as #41770
