### ISSUE TITLE
Technical idea: a (better?) alternative to the current string/int ids (suggestion/discuss)

### ISSUE THREAD

**Issue by Aivean** [CleverRaven/Cataclysm-DDA#44770]
## General idea:

Make `string_id` a `shared_ptr` to its `std::string` identity.

Use the semantics of the shared_ptr to ensure that while at least one instance of `string_id` exists, its `std::string` identity also exists and is shared among the equal `string_ids` .

Equality and all comparisons operations on `string_id` are delegated to the inner shared_ptr (which is shared among all equal `string_ids` ), and thus are very fast.

[Prototype](https://gist.github.com/Aivean/1c6402ea23ddd051e4926fc3b1f2b9a5) (note: this is NOT a production code)

### Benefits:

- simplicity: a single class that represents ids  (as opposed to the the duality of string/int ids)
- correctness: "id" instance is always correct (same as string_id currently, but different from int_id, which becomes invalid during and after game reloading)
- as fast as `int_id`¹ when used as an element of std::set, cata::flat_set, etc
- as fast as `int_id`¹ when used as a key in std::map
- saves lots of heap memory (unique strings are stored only single time)

¹ - according to my benchmarks on my machine

### Drawbacks:

- doesn't have natural ordering by string value (now ordering is pointer-based)
- slightly larger shallow memory footprint compared to int_id (16 bytes vs 4 bytes)
- a hidden overhead of internal shared_ptr on copy/construct/destruct?  (need to test)

----
## Additional context

Sizeof (64 bit macos, clang 10):
id_v2: 16
flag_id: 4
flag_str_id: 40

I've spend some time benchmarking the prototype, so far, it looks pretty good performance-wise.

Conclusion: so far, it seems like a good middle ground between string and int ids, that offers comparable performance and benefits where it matters. The absence of the natural string ordering doesn't seem like a big drawback to me.

**Comment by lcy03406** [comment]
The natual ordering is needed in some UI, eg. proficency name list.

**Comment by lcy03406** [comment]
Using shared_ptr as id requires all ids are unique.

But if we can ensure all ids are unique, why not just use string_id*  ?

**Comment by Aivean** [comment]
> Using shared_ptr as id requires all ids are unique.
> 
> But if we can ensure all ids are unique, why not just use string_id* ?

That's a valid question. The only reason is to limit the lifetime of the strings in "central storage" and handle the potential misuse of ids when unique short-lived ids are generated repeatedly.  There are simpler (but less robust) ways to handle this scenario, like put a hard limit on the number of unique ids, and in this case smart pointers are not required.

**Comment by Aivean** [comment]
For the record, we discussed this issue with Kevin on discord:
https://discord.com/channels/598523535169945603/598535887801810944/764268571735883777

**Comment by lcy03406** [comment]
So you want to keep the `string_id `interface and store a` shared_ptr<xxx>` in `string_id`.

But shared_ptr is not for sharing, it's for deleting.  If you just want to intern the strings, we can use `xxx*` and forget the overhead of  shared_ptr.

**Comment by Aivean** [comment]
> So you want to keep the `string_id `interface and store a` shared_ptr<xxx>` in `string_id`.
> 
> But shared_ptr is not for sharing, it's for deleting. If you just want to intern the strings, we can use `xxx*` and forget the overhead of shared_ptr.

`share_ptr` here is used here for memory management. When certain unique string is no longer used, `shared_ptr` semantics would ensure it's also removed from "global interned string ids storage".  This is specifically added to combat the situation when the lots of short-lived unique ids are created and pollute the "global string storage". 

If this situation is of no concern (i.e. we have other mechanism to ensure correctness, like put the limit on the number of unique ids, or if we know all the possible values for ids in advance), we can simplify the design and use  `std::string*` instead of shared_ptr.

**Comment by lcy03406** [comment]
The number of all _valid_ ids should be finite, as long as we don't concat arbitrary strings and intern it as if it is an id.

Valid ids exist either in JSON or in C++ code. JSON files are loaded in memory, contain a large but finite number of ids. C++ code contains a small set of IDs, and most of them are defined as static const.

Sometimes we want to check if some ids are valid. If you intern them _after_ checking json data, invalid ones won't pollute the global string storage.

Maybe I'm too optimistic and forget something.

**Comment by Aivean** [comment]
You are right _in theory_. 

I've spend some time today thinking if we can pull this off (by "this" I mean substitute shared_ptr with simple ptr and external validation).

It's possible to store some flag `is_valid_id` along with the interned string value and mark ids loaded from json as "valid', when entities are loaded from json (in init.cpp). In the end of the finalization phase go through all interned ids and ensure that everything is marked as "valid".

It's even possible to make this work in case of valid "dynamic" ids (see "LIGHT_[X] flag), although it would require manually handling them as an exception.

However, that would also limit the _genericity_ of `string_id`. Currently it's possible to use it to represent something that's not loaded from json, and it would be hard/impossible to do so with the "simple pointer" implementation. With this limitation I doubt Kevin and other core devs would accept this change (see discord).

**Comment by lcy03406** [comment]
Yes it's hard without modifying the interface. The current constructor of string_id cannot tell if it should be something in json or just a string id.
