### ISSUE TITLE
[Crash] Segmentation fault when dropping wielded medium battery during reloading process

### ISSUE THREAD

**Issue by Valares** [CleverRaven/Cataclysm-DDA#44772]
# Describe the bug

Wielding a medium sized battery and trying to reload something with said battery while not having enough space in the inventory to hold the battery, the thing that's reloaded and the unloaded battery all at the same time will "force" the player to drop the battery that's used during the reload process and causes a segmentation fault crash.

# Steps To Reproduce

There are multiple ways to reproduce this error, this describes (the easier) one of them:
1. Spawn in 2 medium batteries using the debug menu.
2. Spawn in 1 device that uses said batteries, for example a (makeshift) vacuum sealer.
3. Reload the (empty) device with one of the batteries.
4. Wield your other medium battery.
5. Either fill your inventory with some things (rags, for example) or undress and drop all your clothes that have pockets.
6. Press [r] to reload and select your device.
7. Select "Drop item" - the only active option. This will crash the game.

# Versions and configuration

- OS: Windows 7 64-Bit
- Game Version: 0.E-6546-g51130a4 [64-bit] (last sucessful Windows 64-Bit build, as of this writing)
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context

If - instead of selecting the only available (visible) option on step 7 - ESC is pressed, the game will not crash and the unloaded battery drops to the ground.
Having enough free pocket volume in the inventory does not lead to this behavior.
I've "tested" this with a tazer (this was the way I found out during normal play), and both vacuum sealers. Using light batteries and a flashlight, an MP5 and a magazine or a magazine and ammunition does not produce the same result (as in; a crash - or an error at all), as far as I can tell.
Doing it the other way around, as in reloading the wielded device without having enough space for handling it and dropping it, will throw two errors but not crash the game (probably related to #44110).

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5358592/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5358593/debug.log)

**Comment by Aivean** [comment]
Thanks for detailed instructions, reproduced successfully. Will try to dig into.
