### ISSUE TITLE
Mall Bug

### ISSUE THREAD

**Issue by slimeboy460** [CleverRaven/Cataclysm-DDA#44787]
# Describe the bug

There is constant smashing from the lower levels in the mall, into the 100s per turn. In either a 4x4 or a 6x6 zone (The zone is filled with ears).

# Steps To Reproduce

1. There isn't any real clear reason why this happened, all I did was sleep
2.  Large Building, Mall start

# Expected behavior

Smashing shouldn't be in such a consise area with no reason nor trigger. Especially not with such a constant smashing effect.

# Screenshots

![image](https://user-images.githubusercontent.com/68845349/95667913-36aec780-0b08-11eb-8001-dcb4b7136a13.png)

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-6720-g672652c
 - Graphics version:  Tiles
 - Ingame language: English
 - Mods loaded: alt_map_key, StatsThroughSkills, speedysex

# Additional context

[Myles - Copy.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5360444/Myles.-.Copy.zip)

**Comment by wapcaplet** [comment]
Possible duplicate of #44265.
