### ISSUE TITLE
(0.E-2) "Electric blanket (on)" disappears after being used

### ISSUE THREAD

**Issue by kapacek** [CleverRaven/Cataclysm-DDA#44781]
# Describe the bug

"Electric blanket (on)" disappears when awakened after the sleep. 

# Steps To Reproduce

1. Have a turned on electric blanket worn on the body
2. Go to sleep, then awake
3. It disappears entirely from the inventory

# Expected behavior

I expect it NOT to disappear, but to turn into "electric blanket (off)" with medium batteries inside depleted

# Screenshots
Before
https://filedn.com/le5y28USRPa0EAg8QLxKklH/blanket%201.png
After
https://filedn.com/le5y28USRPa0EAg8QLxKklH/blanket%202.png

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: openSUSE; Description: openSUSE Leap 15.1; Release: 15.1; Codename: n/a; 
- Game Version: 0.E-2 [64-bit]
- Graphics Version: Tiles
- Game Language: Русский [ru]
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Характеристики за навыки [StatsThroughSkills]
]

# Additional context

Doesn't depend on a language, reproducable both on Russian and English

Save file included 

[Котельники.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5360033/default.zip)

**Comment by Valares** [comment]
Can confirm this bug for 0.E-2, but this was/is apparently fixed in experimental.
Can no longer reproduce this behavior in the newest experimental as of the time writing this (build 11076, 0.E-6546-g51130a4).

**Comment by kapacek** [comment]
> Can confirm this bug for 0.E-2, but this was/is apparently fixed in experimental.
> Can no longer reproduce this behavior in the newest experimental as of the time writing this (build 11076, 0.E-6546-g51130a4).

So I guess I can close the issue?

**Comment by KorGgenT** [comment]
fixed in experimental
