### ISSUE TITLE
Frozen liquids spill when you interact with inventory

### ISSUE THREAD

**Issue by Marrim** [CleverRaven/Cataclysm-DDA#44792]
# Describe the bug
After updating to 0.E-6751-g9d6708b, I started noticing that water from my worn canteen started inexplicably spilling in seemingly random places. I managed to isolate that it happens only to frozen liquids whenever you pick something up.

# Steps To Reproduce
Variant 1
Choose any winter start scenario, e.g. "Sheltered".
Drop a bottle of water outside, wait for it to freeze, try to pick it up.
Bottle is picked up, but frozen water stays on ground.

Variant 2
Have a bottle of water in your inventory.
Stay outside until it freezes.
Try to pick something up. Observe that your bottle is suddenly empty and all the water is on the ground.

# Expected behavior
Frozen water should still be in the bottle in either of the two cases.

# Versions and configuration
0.E-6751-g9d6708b
Ubuntu 18.04.5 LTS.
Mods: default + StatsThroughKills

# Additional context
Works with any liquid that freezes.
Happens also when dropping items, or using advanced inventory, as long as you have a container with frozen liquid in your inventory.
You can safely haul such containers along the ground, though, or reheat the liquid.

**Comment by somepersondunno** [comment]
I can verify that this still happens in the current version.

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-6779-gc3caa74 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    No Fungal Monsters [No_Fungi],
    No Rail Stations [No_Rail_Stations]
]

**Comment by ApriamAsh** [comment]
Yes, Happened to me too. Should be a blocker for 0.F.

**Comment by morthein** [comment]
+1 this, was coming on here to make a ticket about this exact issue actually.  
It feels game-breaky when the cold sets in.

**Comment by wapcaplet** [comment]
Confirmed in 0.E-6893-g4e0e1f4c05

Starting with a bottle of clean water (frozen), I drop it on the ground in an adjacent tile, then pick it up. The bottle (empty but still sealed) goes into my inventory:

![image](https://user-images.githubusercontent.com/238395/96321265-fd77cb00-0fd1-11eb-9f81-8e8ae70406ec.png)

The clean water (now dirty) falls to the ground at my feet:

![image](https://user-images.githubusercontent.com/238395/96321276-0b2d5080-0fd2-11eb-98d1-1b10439a4d93.png)

**Comment by l29ah** [comment]
0d91a001a12cb7e7f906dd661ecf3e15f85a0d70 is the first bad commit
@lcy03406

**Comment by kholat** [comment]
Wasnt this because of some set of commits that attempted to stop the case where having frozen liquids inside a container (not full) would then allow normal items to go in that container as well, which had weird behaviour. Just thinking out loud here,

**Comment by lcy03406** [comment]
@l29ah Thank you and sorry but I don't know why my code is related to this issue. I thought can_contain is used when puting something into a container.
