### ISSUE TITLE
Unable to refill RV water tank

### ISSUE THREAD

**Issue by tivec** [CleverRaven/Cataclysm-DDA#44791]
# Describe the bug

I am unable to fill a vehicle tank with cold clean water when it apparently contains clean hot water.

# Steps To Reproduce

1. Load attached save
2. Batch craft clean water, choose to fill nearby vehicle Luxury RV. 
3. Water goes into tank as expected.
4. Examine vehicle and choose refill, pick the vehicle tank with clean water.
5. Pick the plastic bottle of clean water, get the following error:

```
DEBUG    : tried to put an item (water_clean) in a container (metal_tank) that cannot contain it

 FUNCTION : int item::fill_with(const item&, int)
 FILE     : src/item.cpp
 LINE     : 8787
```
# Expected behavior
Clean water should go into the tank.

This seems to be a regression introduced with https://github.com/CleverRaven/Cataclysm-DDA/pull/44539

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-6751-g9d6708b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    C.R.I.T Expansion Mod [crt_expansion],
    DinoMod [DinoMod],
    Graphical Overmap [Graphical_Overmap],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Fuji's Military Profession Pack [fuji_mpp],
    More Survivor Stuff [more_survivor_stuff],
    Blaze Industries [blazeindustries],
    Bionic Slots [cbm_slots],
    No Rail Stations [No_Rail_Stations]
]

# Additional context

[Hayden.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5360617/Hayden.zip)

**Comment by irwiss** [comment]
Disabling components check allows the stack, for some reason one of the water_clean's has uncraft components

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/item.cpp#L1097-L1104

**Comment by tivec** [comment]
> Disabling components check allows the stack, for some reason one of the water_clean's has uncraft components

The water boiling recipies are as follows:
```
  {
    "type": "recipe",
    "activity_level": "LIGHT_EXERCISE",
    "result": "water_clean",
    "category": "CC_FOOD",
    "subcategory": "CSC_FOOD_DRINKS",
    "skill_used": "cooking",
    "time": "5 m",
    "autolearn": true,
    "batch_time_factors": [ 20, 1 ],
    "qualities": [ { "id": "BOIL", "level": 1 } ],
    "tools": [ [ [ "water_boiling_heat", 3, "LIST" ] ] ],
    "components": [ [ [ "water", 1 ] ] ]
  },
  {
    "type": "recipe",
    "activity_level": "LIGHT_EXERCISE",
    "result": "water_clean",
    "category": "CC_FOOD",
    "id_suffix": "using_water_purifier",
    "subcategory": "CSC_FOOD_DRINKS",
    "skill_used": "cooking",
    "time": "9 s",
    "autolearn": true,
    "tools": [ [ [ "water_purifier", 1 ], [ "pur_tablets", 1 ], [ "char_purifier", 1 ] ] ],
    "components": [ [ [ "water", 1 ] ] ]
  },
```

When I encountered this, I've been batch crafting, but other than that I can't find anything that would say why it should get uncraft components.

**Comment by PaulBlay** [comment]
I have two 60L tanks. One contains 11L of clean water, the other contains 3.75L of clean water. I can't empty one of the tanks into the other. Both tanks are loose - unconnected to vehicles or whatever. Same bug?

**Comment by irwiss** [comment]
@PaulBlay attach a save if possible

**Comment by PaulBlay** [comment]
I'm not sure file attachment is working on this browser. BTW, I'm using a custom profession so I don't know if that will cause errors on opening the save.

**Comment by Th3AlleyCat** [comment]
The same thing happens with diesel. I had to unload all the diesel from my Humvee and then refill, but it accepted only 10 L. Plastic Jerricans full (10L.).
 My gallon jug with 2.4L. of diesel failed to go in the tank, though log message said I've refilled the tank.
Sorry for the bad English.....

**Comment by emptytriangle** [comment]
Fluids crafted by the player aren't mixing with other fluids in my game. So if I find an RV with clean water in its tank and I craft clean water, I can't put it in that tank. If I craft some animal cooking oil from fat, then try to put a gallon jug of animal cooking oil from someone's kitchen in my tank that also will not mix. It seems to be independent of fluid type.

**Comment by PaulBlay** [comment]
I would like to point out my 'wall of text' comment in https://github.com/CleverRaven/Cataclysm-DDA/issues/46091 which is relevant to discussion on how to handle this bug. :)

**Comment by BrettDong** [comment]
Link: https://github.com/CleverRaven/Cataclysm-DDA/issues/46091#issuecomment-748438592

**Comment by RoyBerube** [comment]
I'm getting this bug consistently with crafted clean water. While wearing a plastic canteen with some clean water - canteen is not full - it will not be an option of where to store newly crafted clean water. From the storage drum, the new clean water cannot be unloaded into the  partially full canteen or reloaded by the canteen.

All of the water involved is crafted.
