### ISSUE TITLE
Wraitheon Sentinel-lx Beam Causes Segfault

### ISSUE THREAD

**Issue by Fosheze** [CleverRaven/Cataclysm-DDA#44797]
# Describe the bug

When a Wraitheon Sentinel-lx uses its ranged weapon it causes a segfault.

# Steps To Reproduce

1. Load attached save.
2. Spawn zombie about 10 tiles away.
3. Pass turns until Wraitheon Sentinel-lx uses ranged weapon.
4. Witness Segfault.

# Expected behavior

Wraitheon Sentinel to use ranged weapon without segfault

# Versions and configuration

- OS: Windows 10 Pro for Workstations
    - OS Version: 10.0 1903
- Game Version: 0.E-6751-g9d6708b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    No Rail Stations [No_Rail_Stations],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP]
]

# Additional context

[World.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5361262/World.zip)
[Logs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5361263/Logs.zip)

**Comment by Fosheze** [comment]
It appears the feral humans are causing this crash as well when they use their ranged attack.

**Comment by Daimiou** [comment]
It seems that any projectile attack using "imagined" ammo (feral human rocks, acid zombie darts, vehicle battery powered energy weapons) cause the segfault.

**Comment by Savengrr** [comment]
Problem exists for weapons using UPS batteries as well, Hard Light long bow, v29 laser pistol, Dazzle Rifle, etc.

**Comment by keampe** [comment]
Could it be trying to add a casing or shell for weapons that simply don't have them?

   - Shane

**Comment by meelock** [comment]
hopefully fixed with #44810

**Comment by Trioct** [comment]
Yep, missed this issue, crash.log looks exactly like all the others. Should be fixed

**Comment by Fris0uman** [comment]
Load save > spawn zombie > wait > zombie gets cut down by lasers, no crash

**Comment by Fosheze** [comment]
Sorry for the massive delay. Real life got in the way. This issue has been resolved under every circumstance I have tested on the latest version.
