### ISSUE TITLE
Non-default color scheme causes Json error: assignment does not update value

### ISSUE THREAD

**Issue by Marrim** [CleverRaven/Cataclysm-DDA#44793]
# Describe the bug
On loading the world, frequently an error message is observed:
```
ERROR : src/assign.h:48 [void report_strict_violation(const JsonObject&, const string&, const string&)] (json-error)
Json error: data/mods//dda/../../json/overmap/overmap_terrain/overmap_terrain_mall.json:96:13: assignment does not update value

    "copy-from": "generic_mall",
    "name": "mall - loading bay",
    "color":
            ^
             "i_light_red"
  },
```
From what I understand, the game is not happy that generic_mall and all other mall submaps have the same color, which implies that specifying color after copy_from is not necessary.
However, _they do have different colors_ in json. It is merely that in my color scheme `i_red` and `i_light_red` are set to the same terminal color. (I use the "no_bright_background.json" color scheme because bright background displays as blinking in my terminal.)

# Steps To Reproduce
In Settings > Colors choose to load from [T]emplate and pick "no_bright_background.json".
Start a new game or load a game where a mall is present. Seems to also trigger on subway stations.

# Expected behavior
Should probably compare the json values, not what these values resolve to in terminal.

# Versions and configuration
0.E-6751-g9d6708b
Ubuntu 18.04.5 LTS.
Mods: default + StatsThroughKills
No tiles, the issue is with colors in the terminal.

**Comment by ZhilkinSerg** [comment]
Related to #26102
