### ISSUE TITLE
Game Crashes when entering area

### ISSUE THREAD

**Issue by bouchacha** [CleverRaven/Cataclysm-DDA#44801]
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-6751-g9d6708b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Graphical Overmap [Graphical_Overmap],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    Aftershock [aftershock],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries [blazeindustries],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod [crt_expansion],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Crazy Cataclysm [crazy_cataclysm],
    Crazy Cataclysm - UndeadPeople Tileset [CrazyCataclysmUDP]
]

### Expected behavior
Game shouldn't crash when heading further south into the city (either on foot or by car).

### Actual behavior
Game crashes.

### Steps to reproduce the behavior
Follow the road south (either by foot or car) and the game will crash about 1/4 down the football field.

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5361470/crash.log)

[Stebbins.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5361467/Stebbins.zip)

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5361476/debug.log)

**Comment by BroseidonMOO** [comment]
I can confirm this with a similar but not identical mod list, while my crash.log looks identical, I am uploading my information as well, in hopes that it will provide helpful information.

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5361684/debug.log)

[Bala.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5361689/Bala.zip)

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5361682/crash.log)
