### ISSUE TITLE
can no longer randomize name without randomizing gender (and other things)

### ISSUE THREAD

**Issue by esotericist** [CleverRaven/Cataclysm-DDA#44802]
# Describe the bug

with the new "randomize all the things" keybinding

# Steps To Reproduce

1. get to the end of character creation
2. select gender
3. randomize name
4. reselect gender, because it changed
5. randomize name
6. reselect gender, because it changed again

# Expected behavior

being able to randomize name without randomizing everything else, like i used to be able to

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 19.10; Release: 19.10; Codename: eoan; 
- Game Version: 0.E-6560-g1a15bff14d8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    MSX Pawns [MSX_Pawns]
]

(current version from testing a PR a few commits removed from b11076)

**Comment by Pupsi-Mupsi** [comment]
Recently "re-added" this in: #44532

Seems to work just fine in:
![grafik](https://user-images.githubusercontent.com/44737997/95690381-9c3da980-0c17-11eb-92b2-ad1cd970b8b2.png)

Let me know if it's what you were looking for.

![grafik](https://user-images.githubusercontent.com/44737997/95690457-33a2fc80-0c18-11eb-9aee-cf1b6e3d93aa.png)

**Comment by esotericist** [comment]
well, that's embarassing. i think i bounced off of the change because in my eyes, `*` is the "rename character" key, and i was looking for a change that returned it to that functionality, rather than looking for a new key that did the old function.

still, it clearly got addressed adequately. thank you for pointing out my oversight.
