### ISSUE TITLE
Aftershock: sunesthesia doesn't work as anesthesia 

### ISSUE THREAD

**Issue by Aivean** [CleverRaven/Cataclysm-DDA#44809]
# Describe the bug

sunesthesia (`afs_sunesthesia`) is a `COMESTIBLE` with an non-existing (and non-supported in c++) flag `ANESTHESIA` (see #44706). 

Currently `ANESTHESIA` is a tool quality and not an item flag. To make "sunesthesia" be treated as anesthesia charges, it has to become an ammo of type `anesthetic`.

# Steps To Reproduce

1. spawn some sunesthesia
2. try to install bionics
3. "available anesthetic: 0ml"

# Expected behavior

sunesthesia's description should be consistent with it's behavior.

# Screenshots

![image](https://user-images.githubusercontent.com/2865203/95693552-d12f0980-0be1-11eb-948f-7c7bb15ef0e3.png)

# Versions and configuration

- OS: MacOs
    - OS Version: Name: Mac OS X; Version: 10.14; Build: 18A391; 
- Game Version: 0.E-6739-gab731d9319-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Fuji's Military Profession Pack [fuji_mpp]
]

**Comment by Aivean** [comment]
ping @Maleclypse @John-Candlebury

**Comment by John-Candlebury** [comment]
This item should probably be removed. 

If craftable anesthetic is somehow needed is probably just better to add a mod recipe for it.
