### ISSUE TITLE
Segfault when hit by feral's ranged attack

### ISSUE THREAD

**Issue by AMahinko** [CleverRaven/Cataclysm-DDA#44812]
Game version: 0.E-6751-g9d6708b

Operating system: Win 7

Tiles or curses: Tiles

Mods active: Aftershock, Blaze Industries, CRIT expansion, Magiclysm, More Survivor Stuff, Stats Through Skills, SpeedyDex

### Actual behavior
Feral Human's rock attack crashes game on contact.

### Steps to reproduce the behavior
Come into range of feral human, let him hit you with a rock
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5362398/crash.log)

**Comment by esotericist** [comment]
same as all the other issues that #44810 aims to address
