### ISSUE TITLE
a7 laser rifle segmentation fault

### ISSUE THREAD

**Issue by meelock** [CleverRaven/Cataclysm-DDA#44813]
# Describe the bug
Segmentation fault on fire of a7 laser rifle in latest version with mods.

# Steps To Reproduce

Spawn in a a7 laser rifle, shoot it, crash on projectile impact.

# Expected behavior

No hard crashes on use of items.

# Screenshots

![image](https://user-images.githubusercontent.com/6434568/95695010-de4ff680-0be9-11eb-80e8-38b3c3720dc5.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-6751-g9d6708b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    MST Extra [MST_Extra],
    Cataclysm++ [Cata++],
    Mythical Martial Arts [MMA],
    Dorf Life [Dorf_Life],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Arcana - UndeadPeople Tileset [ArcanaUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP],
    sees-player icon, retrodays [sees_player_retro],
    Whaleys Hair Mod (UDP Tweaks) [WHALEYHAIR_UDP],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Tankmod: Revived [Tankmod_Revived],
    Tankmod: Revived - UndeadPeople Tileset [Tankmod_RevivedUDP],
    Cataclysm++ - UndeadPeople Tileset [Cata++UDP],
    Dorf Life - UndeadPeople Tileset [Dorf_LifeUDP],
    MST Extra - UndeadPeople Tileset [MST_ExtraUDP],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Bionic Professions [package_bionic_professions]
]

# Additional context
  [crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5362433/crash.log)
   [testworld.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5362555/testworld.zip)

**Comment by meelock** [comment]
hopefully fixed with #44810

**Comment by Trioct** [comment]
Looking at the crash log, it looks like it should be fixed in the next build, yes.

**Comment by meelock** [comment]
Fixed.

**Comment by Roet718** [comment]
Looks like its back ?
![A7crash](https://user-images.githubusercontent.com/19896899/98607481-dea5e500-22ae-11eb-9f7f-070f3bfa036a.PNG)

**Comment by anothersimulacrum** [comment]
@Roet718 You have #45323
