### ISSUE TITLE
Seg Fault when inspecting "In Progress" foods.

### ISSUE THREAD

**Issue by Savengrr** [CleverRaven/Cataclysm-DDA#44811]
# Describe the bug
 Seg fault when attempting to hover over an in-progress craft of "Dehydrated Meat" inside vehicle freezer.

# Steps To Reproduce

1. Enter vehicle
2. Open freezer
3. Attempt to highlight/hover over in progress dehydrated meat. 

# Expected behavior

Expected to hover over object and interact with it as normal within a container.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-6751-g9d6708b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Bionic Slots [cbm_slots],
    Fuji's Military Profession Pack [fuji_mpp]
]

# Additional context

- Have tried removing from container via take all command, successfully transferred item. Can hover over the item while in inventory. dropped the item onto the ground, hover over causes crash again. 
- Crash happened again when trying to place into vehicle workbench and look at the item in said container.
- Crash also occurred with in progress vegetable cooking oil, cookies, and fruit slice.
- Assumption is that error extends to ~~all food crafts, or food crafts in particular that seem to have greyed out names.~~ **_any craft where the product has satiety or calorie information (Bleach gives the same problems where bone meal does not.)._**
- The craft can be finished with no issues and later inspected giving proper information and no crashes, **issue seems specific to when a food is still an unfinished craft and inspected**

[Zion.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5362343/Zion.zip)
[crash files.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5362344/crash.files.zip)

**Comment by meelock** [comment]
might be related to: #44810 ?

**Comment by Savengrr** [comment]
Can't test as launcher says new builds 11090 is unavailable to me.

**Comment by Savengrr** [comment]
Either way it doesn't immediately seem like they would be connected, as this crash happens simply by hovering over the item while in a container. My own guess would be it has something to do with retrieval of information on the item while stored anywhere not on player.
