### ISSUE TITLE
A flashing cursor when moving

### ISSUE THREAD

**Issue by IIverner** [CleverRaven/Cataclysm-DDA#44815]
# Describe the bug

Sometimes a flashing cursor appears when moving

# Steps To Reproduce

It suddenly appears
Move up, down, left and right

# Expected behavior

The cursor should not appear

# Screenshots

gif
![ezgif com-gif-maker](https://user-images.githubusercontent.com/52432761/95723634-eff7d380-0ca7-11eb-9273-78ded74ee72b.gif)

# Versions and configuration

 - OS: Windows 10 
 - Game Version: 0.E-6524-gccff323
 - Graphics version: Tiles
 - Ingame language: Chinese (Simplified) 
 - Mods loaded: ["dda", "no_npc_food",  "No_Rail_Stations",  "crt_expansion",  "crt_expansionUDP",  "MMA",  "MMAUDP",  "stats_through_kills", "cbm_slots"]

# Additional context

[尼古湖.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5363919/default.zip)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5364030/debug.log)

**Comment by IIverner** [comment]
I restart the game and the cursor doesn't appear

**Comment by ZhilkinSerg** [comment]
You have probably shifted your view. There is a command to center view point on character.

**Comment by IIverner** [comment]
Thanks
