### ISSUE TITLE
Game Segmentation Fault - Arithmetical Error

### ISSUE THREAD

**Issue by GorillaxJax** [CleverRaven/Cataclysm-DDA#44822]
# Describe the bug

I was butchering 2 giant wasps on the second story of a building while exhausted/extremely weary. Game crashed and segfaulted. Now there are two characters on my world and it will instantly crash upon launching the world.

# Steps To Reproduce

Launch either the original or duplicated character

# Expected behavior

Launch the save and play.

# Screenshots

# Versions and configuration

 - OS: Windows 10 Version 10.0.19041 Build 19041
 - Game Version: 0.E-6779-gc3caa74 build 11094
 - Graphics version: MSX++UnDeadPeopleEdition
 - Ingame language: English
 - Mods loaded: [Stats Through Kills, Stats through skills, magicalysm, bionics, speedy dex]

# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5367403/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5367404/debug.log)
[Haynes.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5367433/Haynes.zip)

**Comment by Trioct** [comment]
Even though you say it was butchering, it looks like the crash has to do with digging and probably a division by zero. Not sure, I'll probably poke around at it, no promises though.
I also fixed your savefile if you want it, not sure if it's how you left it, but it's what I got out of it: 
[Haynes.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5368294/Haynes.zip)

**Comment by Aivean** [comment]
From the crash log it's probably caused by division by zero when activity progress is calculated. Here is how to quick fix it:

```diff
Index: src/activity_actor.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/activity_actor.cpp	(revision 6b8630bcf90c3d8a40d2e3b70dd120ab6cb8b390)
+++ src/activity_actor.cpp	(date 1602553937065)
@@ -80,6 +80,12 @@
 
 static const activity_id ACT_EAT_MENU( "ACT_EAT_MENU" );
 
+static std::string get_percentage_string( int left, int total )
+{
+    const int pct = total > 0 ? ( ( total - left ) * 100 ) / total : 100;
+    return string_format( "%d%%", pct );
+}
+
 aim_activity_actor::aim_activity_actor()
 {
     initial_view_offset = get_avatar().view_offset;
@@ -395,8 +401,7 @@
 
 std::string dig_activity_actor::get_progress_message( const player_activity &act ) const
 {
-    const int pct = ( ( act.moves_total - act.moves_left ) * 100 ) / act.moves_total;
-    return string_format( "%d%%", pct );
+    return get_percentage_string( act.moves_left, act.moves_total );
 }
 
 void dig_activity_actor::serialize( JsonOut &jsout ) const
@@ -468,8 +473,7 @@
 
 std::string dig_channel_activity_actor::get_progress_message( const player_activity &act ) const
 {
-    const int pct = ( ( act.moves_total - act.moves_left ) * 100 ) / act.moves_total;
-    return string_format( "%d%%", pct );
+    return get_percentage_string( act.moves_left, act.moves_total );
 }
 
 void dig_channel_activity_actor::serialize( JsonOut &jsout ) const
```

However it may be worth it to figure out how `act.moves_total` became zero in the first place.

**Comment by Trioct** [comment]
Yeah, of course there's easier ways around it than a more in depth inspection, and maybe that's a fine enough patch for now if someone wants to make the pr. But to your last sentence, yeah, I'm more curious how it got to this state in the first place.

**Comment by Aivean** [comment]
I'm sorry, I didn't intend to interject. I saw the issue and checked the code before I noticed your comment. So when I saw that you're already working on it I decided to share  what I had so far and move on.

**Comment by GorillaxJax** [comment]
I did get interrupted about 5 times trying to dig a pit in the same spot by zombies and wasps. I forget if I finished it. Does that help? 

Thank you for the fix!

**Comment by BrettDong** [comment]
I am unable to reproduce the crash in the latest experimental. Is the issue still present for you?

**Comment by hexagonrecursion** [comment]
It appears that the fix suggested above was implemented:
https://github.com/CleverRaven/Cataclysm-DDA/blob/7f73bd02fafe5a77df10c225e79fca1b8099b78c/src/activity_actor.cpp#L122-L130
