### ISSUE TITLE
Crash when loading save

### ISSUE THREAD

**Issue by Torres84f** [CleverRaven/Cataclysm-DDA#44826]
# Describe the bug

Game crashed when I loaded it saying something about untraceable stuff (provided both debug and crash logs below)

# Steps To Reproduce

# Expected behavior

# Screenshots

# Versions and configuration

# Additional context

Platform     : Windows_x64
Graphics     : Tiles
Build number : #11061
Build version: 0.E-6496-gef5a06d
Major version: 0.E

Crash and Debug log here -> https://mega.nz/file/liYh3S7A#JHRtGxTd-2sGYex3ovg3yZtbMCXiFOqSbo0ZpsQgj58

**Comment by BrettDong** [comment]
The mega.nz link you provided seems expired. Can you attach your save file directly on GitHub?

**Comment by Night-Pryanik** [comment]
Non-reproducible issue, closing after half-year of no confirmation.
