### ISSUE TITLE
Cannot Submit Infection Data for Analyze Zombie Blood Quest

### ISSUE THREAD

**Issue by KeaneCarotenuto** [CleverRaven/Cataclysm-DDA#44830]
# Describe the bug
I collected some zombie blood using the blood draw kit,
Went to the specified hospital,
Analyzed the zombie blood,
Downloaded the data onto a USB,
Returned to the doctor,
But he will not give me the option to hand in the USB, my only options are saying that I don't have the data yet.

Attempting to complete this quest using the debug menu also fails.

# Steps To Reproduce

1. Start Analyze Zombie Blood Quest (Science Rep 1?)
2. Collect Zombie Blood Sample
3. Analyze and download data
4. Try to hand in USB with infection Data
5. Fail :(

# Expected behavior

That the doctor accepts the Infection data for the quest.

# Screenshots

![image](https://user-images.githubusercontent.com/16412361/95840140-4b0cf180-0da0-11eb-8a75-0f6e29c6d0d0.png)

![image](https://user-images.githubusercontent.com/16412361/95840164-4fd1a580-0da0-11eb-824a-5cccb6e33971.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-6779-gc3caa74 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    No Freeze [no_freeze],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    More City Locations [cityside],
    Compatible Nimian Manufacture Guns [NM_wpns],
    No Fungal Monsters [No_Fungi],
    Clean CBMs [clean_cbm],
    Fuji's Military Profession Pack [fuji_mpp],
    Manual Bionic Installation [manualbionicinstall],
    Mutation Changes [Mutation_Changes],
    Portable Autodoc [portable_autodoc],
    Safe Autodoc [safe_autodoc],
    Safe Portable Autodoc [safe_portable_autodoc],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by AlexMooney** [comment]
I've had the same problem with this quest and also the Hub 01 Steal a Dead Man's Memories quest, where I have the data card in my inventory.

**Comment by kevingranade** [comment]
Fixed by #45434
