### ISSUE TITLE
Internal Furnace broken, research inside

### ISSUE THREAD

**Issue by DoctorGoat** [CleverRaven/Cataclysm-DDA#44846]
# Describe the bug
Two things are currently wrong with the internal furnace. It's on the chopping block unless it gets fixed, and I really like it. So I've done everything in my current power to debug what's going on with it.

1) In #42187, a new function is used to determine how much battery power you get from an item with any CBM. This function is completely nonfunctional with the furnace. Here's a link to the function change in question:
https://github.com/CleverRaven/Cataclysm-DDA/commit/b20439eed95b5686b41d2adf53c4fd0ef094ba30#diff-c72bee5362c8d763c2abe4924204951bedee05da734fd722d49f8d6b4b057602R632

As far as I have been able to tell, `p.get_fuel_capacity( item_type ) <= 0` has never been able to allow the use of the internal furnace in any way. I've never been able to get it to return anything but 0, in fact. Reverting this allows the CBM to see items again and acquire the correct values for them, but not yet work.

2) Drastically more confusing. Something is stopping the eating of items that have values, within the same general area, which is why this is a issue instead of a pull request. 

[help.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/5374784/help.txt)

This is the patch that I'm using to play right now. It has absolutely broken other CBMs, but I feel like I've helped by narrowing it down this far.

# Steps To Reproduce

1. Make a new character with an internal furnace. This requires Aftershock. 
2. Activate it and attempt to eat your clothes.

# Expected behavior

You should see the items as having furnace values, instead of red `No space to store more item name here` text.

If you apply the patch above to the current build, you will be able to eat them, but you will also see furnace values on comestibles. I am entirely unsure of what else is breaking with it, unfortunately.

# Screenshots

Unpatched 10850. 
![unknown](https://user-images.githubusercontent.com/11859483/95928663-f9f50180-0d8f-11eb-9f64-731bf1bff545.png)

Half-fixed modern experimental. Note the food item being seen as a furnace item; this is a glitch and eating it will.. eat it, but not in a furnacy way.
![unknown (1)](https://user-images.githubusercontent.com/11859483/95928707-109b5880-0d90-11eb-9dc8-5c0ec4f29848.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
Game version: Anything after Jenkins build 10850 will have these problems.
Mods: Aftershock, dda
- Graphics Version: Tiles
- Game Language: System language []  (??? unsure why this is, I'm playing in English)

**Comment by Maleclypse** [comment]
I appreciate your help looking into this!

**Comment by DoctorGoat** [comment]
Everything except CBMs categorized as "other" is broken and will require a complete rewrite. Fortunately, there are two whole CBMs that aren't categorized as other (??) and one of them is obsolete and the other is Aftershock-only.

Existing code could be used to get furnace to work like how the battery CBM was reworked, which would move it to ::other, which would make the entirety of CBMs now in the other category.

Other possible fix is to wrap the broken  if( get_fuel_capacity( item_type ) <= 0 ) { with an if statement for furnace but that's silly.
