### ISSUE TITLE
Alloy Plating - Legs Bionic id "bio_armor_head", instead of "bio_armor_legs",

### ISSUE THREAD

**Issue by Ezioblade12** [CleverRaven/Cataclysm-DDA#44857]
# In the \data\json\bionics.json line 94

# Steps To Reproduce

<!-- Steps to reproduce the behavior:
1. Open \data\json\bionics.json
2. go to line 94
3. read ID

# Expected behavior

The ID is supposed to be "bio_armor_legs", as stated by description and "bio_armor_head", already in use.

# Screenshots
![Capture](https://user-images.githubusercontent.com/32436403/96021856-9c0afd00-0e15-11eb-8d23-4b5c30406826.PNG)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA],
    Graphical Overmap [Graphical_Overmap],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Fris0uman** [comment]
Please follow the template

**Comment by Pupsi-Mupsi** [comment]
Can't find any issues with that.
You may wanna update if you are on experimental.

![grafik](https://user-images.githubusercontent.com/44737997/96031824-29723f80-0e5e-11eb-9d00-d3a0fe209b5f.png)

**Comment by wapcaplet** [comment]
The `data/json/bionics.json` file looks fine to me in regards to `bio_armor_*` items. With no other info to go on, not much point in keeping this issue open.
