### ISSUE TITLE
Toolboxes have a volume of 2.5L

### ISSUE THREAD

**Issue by sapphicsithis** [CleverRaven/Cataclysm-DDA#44868]
# Describe the bug

`toolbox_empty` and `toolbox_workshop` in `data/json/items/tool/workshop.json` have a volume of 2.5L and thus a max item length (along the diagonal; the pocket is assumed to be a cube) of 19 cm. I found this out when the game attempted to put a `saw` with length 46 cm into a `toolbox_empty` when I was driving through a town.

# Steps To Reproduce

Look at `toolbox_empty` and `toolbox_workshop` in `data/json/items/tool/workshop.json` (and `saw` in `data/json/items/tool/woodworking.json`).

# Expected behavior

`toolbox_empty` and `toolbox_workshop` should be bigger than 2.5L. For example, [this toolbox](https://www.amazon.com/dp/B08HV9CNDL/) can fit the `saw` and it is about 15L.

# Versions and configuration

 - Game Version: 0.E-6830-g61a68f975c but

**Comment by AntonO-kalas** [comment]
By making the volume 30 Liters instead (which makes more sense) you can still only fit a 43 cm large item in the toolbox since the toolbox is assumed to be a cube.  Is the toolbox really a cube, or are its dimensions calculated somewhere using the volume?

**Comment by Rivet-the-Zombie** [comment]
Most portable toolboxes IRL are rectangular, to avoid this sort of problem.

**Comment by Zireael07** [comment]
Agreed, I haven't seen a square one and my father is a DIY sort of a man so I have seen loads of 'em around

**Comment by esotericist** [comment]
a fix for the error message can be found in #44721

we shouldn't be making just one or two huge toolboxes, and instead should have a lot of different size toolboxes and a lot of different itemgroups based on context, like we do with other SUS things

**Comment by ParaplegicRacehorse** [comment]
Actually... toolboxes should properly be "metal box" or "wooden box" and we should simply fill them with whatever we want.
