### ISSUE TITLE
toolboxes spawn broken sometimes

### ISSUE THREAD

**Issue by misterprimus** [CleverRaven/Cataclysm-DDA#44869]
# Describe The Bug
Toolboxes don't spawn correctly sometimes due to insufficient space for tools.

# Steps To Reproduce
Encounter an area with a toolbox spawn with too many items.

# Expected behavior
No error.

# Versions and configuration

 - OS: Win7x64
 - Game Version: 0.E-6823-g214e756 (tiles) - Build 11095
 - Graphics version: Tiles
 - Ingame language: Eng
 - Mods loaded: No NPC needs

# Additional context

Error text:
```
DEBUG: tried to put an item (sandpaper) count (1) in a container (toolbox_empty) that cannot contain it: pocket unacceptable because not enough space.
FUNCTION: ret_val<bool> item::put_in(const item&, item_pocket::pocket_type)
FILE: src/item.cpp
LINE: 1132
```
In this particular case, the error was followed up with another entry for a hacksaw.

**Comment by esotericist** [comment]
the toolbox isn't actually "broken", it's just giving an advisory error that it couldn't spawn an item
a fix for the error message (and spilling the item onto the ground) can be found in #44721
