### ISSUE TITLE
Segmentation fault when crafting

### ISSUE THREAD

**Issue by Konoshka** [CleverRaven/Cataclysm-DDA#44884]
# Describe the bug

A segmentation fault occurs when crafting on a spot that's under an "Unsorted" zone and has a nearby "Other" zone. It looks like NPC's will try to sort the in progress craft while it's being worked on causing the crash.

# Steps To Reproduce

1. Spawn as survivor profession in evacuee scenario
2. Recruit NPC and make a camp in the shelter, enable sorting priority for the NPC
3. Set an Unsorted zone over a counter and an Other zone elsewhere
4. Craft anything, I used a batch of soap flakes. It depends on the NPC actually sorting during the craft so the longer running the better
5. Crash occurs

# Expected behavior

No crashes. Sorting for an in-progress, actively being worked on item should be ignored or crafting just interrupted when the item is taken away

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.E-6889-g0af511e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5388555/config.zip)
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5388565/save.zip)

**Comment by Trioct** [comment]
I think #45049 should've fixed this
