### ISSUE TITLE
Water from shallow water frozen since 'Poured item has no defined temperature'

### ISSUE THREAD

**Issue by joris1972** [CleverRaven/Cataclysm-DDA#44909]
# Describe the bug
I poured water from shallow water into 2 60L tanks. One empty, one partially full (75/240). The empty one filled up normally. Pouring water into the partially filled tank gave an error message: 'Poured item has no defined temperature'. Checking the tank, I saw that the water in the tank is frozen. 

# Steps To Reproduce
1. Have a 60 L tank with some water in it (mine had 75)
2. Go to a shallow water
3. 'e'xamine the shallow water
4. Choose the option 'Pour into a container'
5. Choose the partially filled tank

# Expected behavior
In words: the temperature of water in the tank is the average of the temperature of the two quantities of water, proportionate to their quantities. 

In formula: 
The water in the tank has a temperature of [(# of water currently in tank x temperature of water+# of water added to the tank x temperature of water source)/(# of water currently in tank + # of water added to the tank ]

# Screenshots

# Versions and configuration
OS: Windows 10 Pro build 19041.572, Windows Feature Experience Pack 120.2212.31.0
OS Version: 10.0 2004
Game Version: 0.E-2 [64-bit] 10478? not sure where I can find the 'main menu' but the menu called up by ESC or ENTER doesn't give me that info
Graphics Version: Tiles
Game Language: English [en]
Mods loaded: [
Dark Days Ahead [dda],
Graphical Overmap [Graphical_Overmap],
Disable NPC Needs [no_npc_food]
]

# Additional context
I had been taking water from the shallow water for some time. This was the third or so haul, with two tanks. This waas the only time that one of the tanks still had some water in it. 

Debug log added. 
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5396435/debug.log)

**Comment by Hirmuolio** [comment]
Already fixed in master branch.
0.E just didn't get this one backported.

**Comment by GGgatherer** [comment]
> not sure where I can find the 'main menu'
It's the starting screen, with [MotD], [New game], [Load game] and so on. The version string is between game logo and those menu items.
