### ISSUE TITLE
Feral Humans drop human flesh, stomach and bone, but not human fat

### ISSUE THREAD

**Issue by Morat2255** [CleverRaven/Cataclysm-DDA#44903]
# Describe the bug

Feral humans are living, albeit crazed, humans, not zombies, which is why they drop human flesh, non-filthy clothes, carry weapons, etc. However, they seem to not yield the item "human fat" when butchered. Instead they drop normal fat, which gives no morale bonus to cannibals and is edible by non-cannibals.

# Steps To Reproduce

1. Kill and full butcher a feral human
2. Check the drops
3. Try cooking lard or cracklins, notice that it gives no cannibalism bonuses or penalties

# Expected behavior

I would expect the fat to be human too.

# Screenshots

[Three feral humans butchered](https://i.imgur.com/TbICWGK.png) (using a +1 combat knife at survival 3, if that matters)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-6779-gc3caa74 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA],
    No Fungal Monsters [No_Fungi],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    sees-player icon, retrodays [sees_player_retro]
]

**Comment by RobertoVGoulart** [comment]
It works as intended without mods, but with the mods loaded the bug appears.
