### ISSUE TITLE
Segmentation fault on autosave during taking a wheel off a vehicle.

### ISSUE THREAD

**Issue by AelundNolen** [CleverRaven/Cataclysm-DDA#44915]
# Describe the bug
I was taking wheels off of a Humvee, in the process of taking off the third, my game started to autosave, and that caused a segfault. 

# Steps To Reproduce
1. Start taking wheels off of the Humvee that my character is near in the save
2. Somehow force an autosave during the process of taking a wheel off
Hopefully that reproduces it. I couldn't make it save like that so don't know if it's a one off thing.

# Expected behavior

Obviously I didn't expect to crash.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-6779-gc3caa74 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    More Survivor Stuff [more_survivor_stuff],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    More Locations - UndeadPeople Tileset [more_locationsUDP],
    No Fungal Monsters [No_Fungi],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5396894/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5396895/debug.log)
[Londonderry.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5396899/Londonderry.zip)
The crash duplicated my character, one of them is parked near the humvee in question.

**Comment by hexagonrecursion** [comment]
Could not reproduce with clang address and undefined behavior sanitizers. Note: I don't have non-mainline mods used in the save

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 0.F-2004-gada3852d39 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    No name () [],
    No name () [],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    No name () [],
    No name () [],
    No name () [],
    No name () [],
    No Fungal Monsters [No_Fungi],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]
