### ISSUE TITLE
Segmentation fault in Throw action

### ISSUE THREAD

**Issue by AlexMooney** [CleverRaven/Cataclysm-DDA#44912]
# Describe the bug

Segmentation fault when attempting to throw something.

# Steps To Reproduce

Make a character and hit 't'.  Doesn't matter if you have anything available to throw or not.

# Expected behavior

Bringing up the throwing object selector.

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.1 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-6973-gfb5750b643 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations],
    Stats Through Kills [stats_through_kills],
    Graphical Overmap [Graphical_Overmap]
]

# Stack trace

```
    Attempting to repeat stack trace using debug symbols…
    debug_write_backtrace(std::ostream&)
    …/src/debug.cpp:892
    log_crash(char const*, char const*)
    crash.cpp:?
    signal_handler(int)
    …/src/crash.cpp:117
    ??
    ??:0
    item::is_null() const
    …/src/item.cpp:759
    item::made_of_from_type(phase_id) const
    …/src/item.cpp:6609
    Character::can_wield(item const&) const
    …/src/character.cpp:9534
    ret_val<bool>::success() const
    …/src/ret_val.h:71
    avatar_action::plthrow(avatar&, item_location, cata::optional<tripoint> const&)
    …/src/avatar_action.cpp:860
    cata::optional<tripoint>::reset()
    …/src/optional.h:157
    ~optional
    …/src/optional.h:102
    game::handle_action()
    …/src/handle_action.cpp:2101
    game::do_turn()
    …/src/game.cpp:1497
    main
    …/src/main.cpp:707
    __libc_start_main
    /build/glibc-ZN95T4/glibc-2.31/csu/../csu/libc-start.c:342
    _start
    ??:?
```

**Comment by AlexMooney** [comment]
The first commit that has this problem is e51f68d1db5d2f1b86d6f106e07ee577ea0cb93c from #44808.

**Comment by wooksterru** [comment]
I also receive this problem, no mods, fresh character, latest experimental build.

**Comment by Termineitor244** [comment]
Same problem when trowing with "t"
