### ISSUE TITLE
You can close a multi-tile door entity onto yourself if you click on a tile where you are not standing

### ISSUE THREAD

**Issue by misterprimus** [CleverRaven/Cataclysm-DDA#44919]
# Describe the bug
You can close a multi-tile door entity onto yourself if you click on a tile where you are not standing
# Steps To Reproduce
1. Find a car with a 2-tile trunk.
2. Open the trunk and stand on one of the trunk tiles.
3. Issue the close command to the other tile.
4. Trunk closes on you, but you can phase through it somehow.
# Expected behavior
You get the same "some buffoon is in the way" error message you do if you issue the command on the tile where your character is.
# Versions and configuration

 - OS: Win7x64
 - Game Version: [from the main menu, e.g. 0.C-29938-g90f5268437]
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: disable npc needs

**Comment by Zireael07** [comment]
Been reported already but I can't find the issue # at the moment.

**Comment by wapcaplet** [comment]
Took me a few minutes to find it because it is such an old issue (5 years ago) - this is a duplicate of #13388
