### ISSUE TITLE
Make Chimera Immune to becoming Weary 

### ISSUE THREAD

**Issue by Giagantic** [CleverRaven/Cataclysm-DDA#44914]
# Is your feature request related to a problem? Please describe.
Chimera is, in essence, a unrelenting abomination that must keep moving in order to avoid self-destruction. The entire set of mutations emphasizes the need to continually devour and be on the move or demise is inevitable and weariness does not fit it at all.  

# Describe the solution you'd like
Make it so a Chimera gains near immunity to weariness as a result of mutations that already exist such as:

- Restless (Chimera specific evolution of Antsy): "Spending any amount of time in familiar places makes you miserable. Must. Keep. Moving." 

or

- -Hyper-Metabolism: "You metabolize nutrients so rapidly that you can convert food directly into useful tissue. Excess nutrition will convert to HP, rather than being wasted. Activate to skip prompt for overeating." 

The only thing that should result in weariness for a Chimera is if they do something that is uncharacteristic of a Chimera such as crafting which could be tied into mutations like Apex Predator.

**Comment by kevingranade** [comment]
As stated, no, if they try to just keep going full speed indefinitely they will wear out. Mutations in this direction, but stopping well short of "immunity to weariness" would be fine.

Even if they *must* keep going, there's nothing that says they can't slow down to recuperate.

To be more concrete, perpetual melee combat is right out, perpetual walking would be fine, the real balance point is somewhere in between.
