### ISSUE TITLE
[magiclysm] forge of wonders provides unlimited riches to a player with an `*` key

### ISSUE THREAD

**Issue by esotericist** [CleverRaven/Cataclysm-DDA#44923]
# Describe the bug

by heading to the forge of wonders, a player can deconstruct demon forges (as an easy deconstruct!) to get extremely valuable mats, at no risk

# Steps To Reproduce

1. find forge of wonders
2. find demon forge
3. deconstruct demon forge
4. repeat
5. profit

# Expected behavior

so in an ideal world, the various creatures in the forge of wonders would count for 'doing things the faction doesn't like', and deconstructing valuable things (like the demon forges) would get a warning/escalating response

that's a bit hard to do, so probably the short term solution is preventing the player from ransacking the forges in the forge of wonder

# Screenshots

definition for demon forge, including easy construct flag and valuable prizes for doing so
![image](https://user-images.githubusercontent.com/1569754/96363439-4c645400-10e9-11eb-8950-e42b907c031c.png)

`valuable prize (x14)`
![image](https://user-images.githubusercontent.com/1569754/96363509-ba108000-10e9-11eb-955e-e3aca3ee3d1b.png)

placement of demon forges in the map, showing six separate demon forges to profit from
![image](https://user-images.githubusercontent.com/1569754/96363465-6dc54000-10e9-11eb-9ea8-ee307afaf570.png)

# Additional Context

if a player grabs them all, the result is a total of $12,789 in post-apocalypse barter capacity, which is fairly immense. add a decent speech score, and you can swipe a lot of the forge lord's salables with the raw mats for the forge lord's own equipment as the trade good

**Comment by KorGgenT** [comment]
quick and easy fix is to make a new furniture that has all the same qualities that show up in the forge but can't be disassembled

**Comment by esotericist** [comment]
the furniture appears literally nowhere else, and i see no evidence can be constructed as furniture.

so, like, i guess we could, if you want to add a construction recipe or other spawn locations that do allow it?

**Comment by Maleclypse** [comment]
A demon Forge is required to make orichalcum ingots.  I'll look at what I can do about the furniture version.
