### ISSUE TITLE
[Magiclysm] Auras give morale penalty when wet

### ISSUE THREAD

**Issue by molkero** [CleverRaven/Cataclysm-DDA#44924]
# Describe the bug

Magical auras give morale penalties when the character is wet.

# Steps To Reproduce

1. Make a wizard.
2. Cast aura spell, dive in water.
3. Observe morale penalties.

# Expected behavior

Partially intangible magical auras shouldn't give morale penalties if wet.

# Screenshots

![Screenshot_2020-10-18_13-06-44](https://user-images.githubusercontent.com/49575273/96364756-d392e580-1144-11eb-9bda-62746b4734d7.png)
![Screenshot_2020-10-18_13-08-44](https://user-images.githubusercontent.com/49575273/96364759-d8f03000-1144-11eb-8853-517188edf365.png)
![Screenshot_2020-10-18_13-09-14](https://user-images.githubusercontent.com/49575273/96364761-dee61100-1144-11eb-80a7-e788eb8e32ca.png)

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 20.1.1; Codename: Mikah; 
- Game Version: 0.E-6984-g80909092ec [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm]
]

# Additional context

I don't think any of the water related flags work here as the aura shouldn't protect the character from getting wet or give morale buffs when wet.

**Comment by GGgatherer** [comment]
Those aura items don't have "(wet)" in their descriptions. Does wet penalty appear after you swim completely naked? If it does then auras don't have anything to do with the penalty.

**Comment by molkero** [comment]
First picture is swimming naked, last with auras on. I think the auras are treated as clothing items without the water friendly tag.
