### ISSUE TITLE
Reloading container with liquids is bugged

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#44931]
# Describe the bug

In some cases (well, at least one), the log will say container holding the liquid was loaded while it actually was not.

# Steps To Reproduce

1. Load [save](https://drive.google.com/file/d/1UP79hpf70vyQW8irovliISB0jkWIzsf0/view?usp=sharing).
2. Open inventory, select canteen with tea, try reloading it (from any of two foldable bottles with exact same tea).
3. See what happens.
4. Drink the tea from canteen and one of foldable bottles.
5. Try reloading canteen with tea again, see that it is working fine now.

# Expected behavior

Reloading actually doing what it is supposed to do.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-6982-g6fb2e49 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills],
    Bionic Professions [package_bionic_professions]
]

**Comment by RoyBerube** [comment]
```
 DEBUG    : item_location lost its target item during a save/load cycle

 FUNCTION : ensure_unpacked
 FILE     : D:\Cataclysm Master\Cataclysm-DDA\src\item_location.cpp
 LINE     : 105
```
This is the error message when reloading the canteen in the save.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-10973.
