### ISSUE TITLE
reloading from military rucksack and from leg ammo pouch takes equal time

### ISSUE THREAD

**Issue by jarmush** [CleverRaven/Cataclysm-DDA#44944]
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-6984-g8090909 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

Press "r", choose a weapon to reload and get magazine selection window. All magazines has the same moves to reload.

![image](https://user-images.githubusercontent.com/6452938/96393888-2dd58a00-11c9-11eb-92bf-12910bc96fdc.png)

**Comment by jarmush** [comment]
Downloaded latest experimental, started new game with "bionic soldier" profession. Moved one magazine from the leg ammo pouch to the pants, tried to reload. Same result.

![image](https://user-images.githubusercontent.com/6452938/96417704-50cc6200-11fa-11eb-90bd-cf5a336b2000.png)

**Comment by RobertoVGoulart** [comment]
I can confirm it's happening with another weapon and magazine, and several different containers too.
On the container description "base moves to remove item" appear as different values, but it doesn't seems to change anything when reloading, but they do change the move cost when wielding
![Image 421](https://user-images.githubusercontent.com/20757625/96461902-54141d80-11fb-11eb-9c17-92442a4b3cc3.jpg)


![Image 420](https://user-images.githubusercontent.com/20757625/96461572-e9fb7880-11fa-11eb-923d-0353fb372955.jpg)

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-6126.
![изображение](https://user-images.githubusercontent.com/11132525/154093627-a1a8f92a-82cf-4e2f-8ea1-798c9e9fc1a9.png)
