### ISSUE TITLE
Segfault While Throwing Objects

### ISSUE THREAD

**Issue by Anon902** [CleverRaven/Cataclysm-DDA#44943]
# Describe the bug
Attempting to throw any object results in game crash. What is available to be thrown seems to have no effect. Works across all saves - included is clean save with randomly genned character.

# Steps To Reproduce
1. Attempt to throw something.

# Versions and configuration
 - OS: Ubuntu 20.04 LTS
 - Game Version: 0.E-6984-g8090909
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: Disable NPC needs, Bionic Professions

# Additional context
[ThrowCrash.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/5398437/ThrowCrash.tar.gz)

**Comment by GGgatherer** [comment]
#44912, already fixed by #44921.
