### ISSUE TITLE
Containers with a single item in them have naming issues

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#44950]
# Describe the bug

Instead of "\<container name\> with \<item name\>" it is "\<item name\> (\<container name\>)". It is okay for things holding liquids and such but I'd prefer seeing my backpack with a cloak as backpack with a cloak, not a "cloak (backpack)".

# Steps To Reproduce

Well, I guess, make a character, make a backpack and another item, put that item into the backpack and look at the inventory.

# Expected behavior

For liquids? Sure, it's great thing. Because (currently) there can only be one liquid in a container, and players are generally more interested in it than the container itself. For other things it should work as "x with y", not "y (x)".

# Screenshots

![cataclysm-tiles_2020_10_19_21_14_09_060](https://user-images.githubusercontent.com/56833396/96463228-ae8b9900-1250-11eb-8853-7da26eedbd71.png)

It looks especially weird in nested view mode:
![cataclysm-tiles_2020_10_19_21_13_56_651](https://user-images.githubusercontent.com/56833396/96463251-b4817a00-1250-11eb-82f9-b284143b7eef.png)

# Versions and configuration

- OS: Windows 7x64
- Game Version: 0.E-7008-gf8d184a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills],
    Bionic Professions [package_bionic_professions]
]

**Comment by wapcaplet** [comment]
This behavior was introduced with #44705. I agree it can disrupt readability, especially when reading through the items I'm wearing - note my leather belt, ankle sheath, and spear strap are all parenthesized, being pre-empted by the crowbar, trench knife, and quarterstaff, respectively:

![image](https://user-images.githubusercontent.com/238395/97108964-5ca2a300-1696-11eb-8125-5e96b5e73cac.png)

**Comment by dchieh222** [comment]
I agree, this has caused chaos where I droppd my main suit of armor because I saw only "filthy" things in it. Its an immense pain.

**Comment by GGgatherer** [comment]
BTW, trade screen takes this to a new level of cringe:

![cataclysm-tiles_2020_11_06_11_47_52_722](https://user-images.githubusercontent.com/56833396/98327664-aab88e80-2026-11eb-93c9-142cc2c70301.png)

**Comment by anothersimulacrum** [comment]
Fixed in #45767
