### ISSUE TITLE
[Generic Guns]  Profession starting gear throws errors: rifle_mag is too big for pockets in legpouch_large

### ISSUE THREAD

**Issue by skeolan** [CleverRaven/Cataclysm-DDA#44959]
# Describe the bug

Certain starting professions are supposed to have one or more `STANAG 30-round magazine`s (volume 290mL) stored in a `leg ammo pouch`, which has two pockets of 500mL each.

With the Generic Guns mod applied, those STANAG30 magazines get swapped for the generic "standard rifle magazine" (copied from `falbigmag`) which is 750mL.

When these professions get loaded by the UI during New Game character creation, the game generates an error message (below) and loses the extra magazines that were supposed to be in the leg pouch.

# Steps To Reproduce
* Create a New World with the Generic Guns mod enabled
* Select New Game and Custom Character
* Freeform [tab] Evacuee [tab]
* Press Up arrow a few times to cycle quickly around to Combat Medic
Error text:
```
 DEBUG    : tried to put an item (rifle_mag) count (1) in a container (legpouch_large) that cannot contain it: pockets unacceptable because item too big

 FUNCTION : ret_val<bool> item::put_in(const item&, item_pocket::pocket_type)
 FILE     : src/item.cpp
 LINE     : 1121
```
* Press `space` two times to clear the error message (it's the same error two times).
* `Enter` to select the Profession despite the errors.
* Press `space` two *more* times due to the same errors again.
* `Tab` through the rest of the New Game UI to start play.
* Press `space` two *more* times due to the same errors again.
* [`i`]nventory
  * Note empty leg pouch and no extra rifle magazines
* [`U`]nload the "assault rifle +3"
* [`/`] Advanced Inventory Management
  * Note "standard rifle magazine" has volume of 0.75L
  * Note "leg ammo pouch" pocket volume is 0.50L

# Expected behavior
Professions should not throw errors because of their starting gear; and extra mags should be part of the character's inventory when the game starts.

# Screenshots
![image](https://user-images.githubusercontent.com/970655/96509167-7cf2dd80-1210-11eb-8c57-d1d5868d4f5f.png)
![image](https://user-images.githubusercontent.com/970655/96509228-93009e00-1210-11eb-99c0-fccada1ecc79.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-7008-gf8d184a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Generic Guns [generic_guns],
    Alternative Map Key [alt_map_key],
    Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
    No Rail Stations [No_Rail_Stations],
    Graphical Overmap [Graphical_Overmap],
    No Acid Zombies [No_Acid_Zombies],
    No Ants [No_Anthills],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Prevent Zombie Revivification [no_reviving_zombies],
    Bionic Professions [package_bionic_professions]
]

**Comment by skeolan** [comment]
Sort-of-related issue: #43226

**Comment by kevingranade** [comment]
Issue no longer occurs :+1:
