### ISSUE TITLE
NPCs vanish when Faction Base bulletin board is selected

### ISSUE THREAD

**Issue by Rayeneth** [CleverRaven/Cataclysm-DDA#44978]
Game version:
0.E-7000-gf8d184a
Operating system:
Win10
Tiles or curses:
Tiles
Mods active:
DDA, Disable NPC Needs, Bionic Professions, Stats through skills, Stats through kills, SpeedyDex, Blaze Industries, Magiclysm
### Expected behavior
When I select a duty on the board I expect a choice of who to send out on a mission.
### Actual behavior
Every NPC in my base vanishes without a trace. 
### Steps to reproduce the behavior
Select 3rd Kaijen from Magitown (character duplication bug happened here too,) interact with board, watch 3 NPCs vanish. 
[Magitown.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5408278/Magitown.zip)

**Comment by Rayeneth** [comment]
Things got stranger after I started poking around.  Selecting the board makes all NPCs vanish, even unallied ones. However, NPCs seem to return randomly as turns progress only to vanish again once the board is interacted with. enemies and non-hostile monsters are unaffected.

**Comment by Rayeneth** [comment]
I believe this bug is directly related to the fire department faction camp, as I created a new camp and it the board did not vanish my NPCs.

**Comment by Ramza13** [comment]
I found the line that this happens at.  https://github.com/CleverRaven/Cataclysm-DDA/blob/996543b7af7942321cfab367cf179db263697aa0/src/faction_camp.cpp#L2282
Comment that out and they don't vanish.  But I don't understand mapgen enough to know what exactly that means or how to fix.

**Comment by Rayeneth** [comment]
Cheers.

**Comment by Erios909** [comment]
I had this bug come out when I started a fire station basecamp in my latest game in experimental, it started happening after I built the Farm Expansion. 

I also had problems with my set zones rotating inside the fire station.

**Comment by actual-nh** [comment]
Ping: @jbytheway, @mlangsdorf?

**Comment by anothersimulacrum** [comment]
start:
```
Lashay Caldwell : 62 67 0
Johnathan Newman : 62 76 0
Terrell Deal : 64 67 0
```

transformations (from map::rotate):
Each pair corresponds to one call to `map::rotate`.
```
Lashay Caldwell : 62 67 0
Lashay Caldwell : 9 4 0

Lashay Caldwell : 9 4 0
Lashay Caldwell : 2 7 0

Lashay Caldwell : 2 7 0
Lashay Caldwell : 9 4 0
```

```
Johnathan Newman : 62 76 0
Johnathan Newman : 9 7 0

Johnathan Newman : 9 7 0
Johnathan Newman : 2 4 0

Johnathan Newman : 2 4 0
Johnathan Newman : 9 7 0
```

```
Terrell Deal : 64 67 0
Terrell Deal : 7 4 0

Terrell Deal : 7 4 0
Terrell Deal : 4 7 0

Terrell Deal : 4 7 0
Terrell Deal : 7 4 0
```

end:
```
Lashay Caldwell : 10 5 0
Johnathan Newman : 10 7 0
Terrell Deal : 7 4 0
```

One of the rotations in `map::rotate` is not being undone.
