### ISSUE TITLE
Counters stun-lock the player

### ISSUE THREAD

**Issue by Kelenius** [CleverRaven/Cataclysm-DDA#44986]
# Describe the bug

If a character capable of counterattacking gets attacked multiple times, they can get locked into counters, doing nothing but counterattacking for several turns in a row.

# Steps To Reproduce

1. Load the attached save.
2. Press 5 a few times, maybe walk into the zombie crowd, watching the time. It doesn't happen every time, if the zombies die before the lock is triggered, reload the save.

# Expected behavior

Not this.

# Screenshots

![изображение](https://user-images.githubusercontent.com/6681708/96634131-bca9ea00-1322-11eb-9918-b95b68556dce.png)
Pressing 5 once (note the time):
![изображение](https://user-images.githubusercontent.com/6681708/96634149-c29fcb00-1322-11eb-9a92-938a9bced6ac.png)
Logs (note that "Saving game" was 10 seconds ago):
![изображение](https://user-images.githubusercontent.com/6681708/96634180-cf242380-1322-11eb-8b35-277a2aac1ef8.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-7029-gdff5e4e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Generic Guns [generic_guns],
    No Fungal Monsters [No_Fungi],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

[Tusculum.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5411050/Tusculum.zip)

#44533 probably broke it.

**Comment by Kelenius** [comment]
Additional thoughts: even the way it is intended to work, wasting moves on a counter may be undesirable, e.g. if the survivor is escaping a horde of zombies, he doesn't want to waste any amount of movies attacking them. Maybe a better way to handle counters would be to mark/highlight the zombies that make attacks that open them for counters, and make counters performable by attacking marked zombies.

**Comment by SSpook** [comment]
Can confirm. I spent 4 minutes roundhouse kicking ants at a military outpost after walking up some stairs. It seems like a high encumbrance is part of the cause. With 100 torso encumbrance and 20 on other bodyparts it takes 30 seconds if a giant ant attacks you compared to the 1 second at low encumbrance.
