### ISSUE TITLE
Crash when crafting(batch) in camp

### ISSUE THREAD

**Issue by D728-hub** [CleverRaven/Cataclysm-DDA#44988]
When in camp and near npcs the game crashes

# Steps To Reproduce

1. Just craft  something that takes a while
2.Game crashes 

# Expected behavior

Complete crafting without crash

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-7029-gdff5e4e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Slots [cbm_slots],
    Graphical Overmap [Graphical_Overmap]

# Additional context
[crashdebug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5411180/crashdebug.zip)

[Decherd.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5411253/Decherd.zip)
Batch craft cracklins and it should crash
I think its  because i have unnerving symptoms and that somehow leads to a crash

**Comment by hexagonrecursion** [comment]
Could not reproduce with clang address and undefined behavior sanitizers

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 0.F-2004-gada3852d39 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Slots [cbm_slots],
    Graphical Overmap [Graphical_Overmap]
]
