### ISSUE TITLE
Stairs and all objects that allow traversing Z levels off center

### ISSUE THREAD

**Issue by grenz1** [CleverRaven/Cataclysm-DDA#44995]
# Describe the bug

Updated the game through the launcher build 11113 to 11116.

Seems that all the objects that you can use to get up/down Z levels are shifted out of place.

Reverting to 11113 fixes this.

Also, starting a new game with the build also has this bug.

# Steps To Reproduce

1. Update 11113 to 11116 using launcher.
2 Create new world or load up existing game from previous save.
3. Stairs, gutters, and other objects that allow travel between Z levels are off center!
4. Exiting out of program then reverting to 11113 using launcher fixes this.

# Expected behavior

Z level objects should be on center.

# Screenshots

![image](https://user-images.githubusercontent.com/73207803/96665817-5c637a00-131b-11eb-87b1-963c11421728.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-7038-gfc4a2a8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    MSX Indicators: REMIX [UDP_REMIX_INDICATORS]
]

 - OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
 - Game Version: [from the main menu, e.g. 0.C-29938-g90f5268437]
 - Graphics version: MSX Deadpeople
 - Ingame language: English
 - Mods loaded: Aftershock, Magiclysm, MSX Aftershock, MSX Magiclysm, 
 -->

**Comment by ZhilkinSerg** [comment]
Check whether it happens with a different tileset too.

**Comment by grenz1** [comment]
I loaded Ultica, Retrodays, and another version of undead people's set that was in options. The problem disappeared.

None of the tilesets seem to have this issue except the MSX version of UndeadPeople's tileset.

It appears this is a third party tileset issue and not a problem with CataclysmDDA.

Thanks, and I will close this issue.

**Comment by ZhilkinSerg** [comment]
You have probably updated tileset version while you updated game version (and rolled back tileset version together with game version), so it looked like it is related to game update.

**Comment by grenz1** [comment]
Thanks. i was really worried I messed up my game when I googled around and saw no one else was having this issue.

Thanks for taking time to help with this issue.
