### ISSUE TITLE
Proficiencies: Multiplication and excessive time and failure rates

### ISSUE THREAD

**Issue by Robik81** [CleverRaven/Cataclysm-DDA#44996]
# Is your feature request related to a problem? Please describe.
Recipes that use multiple proficiencies tends to end up with ridiculous times and failure rates.

# Describe the solution you'd like
Lets use the Leather seat recipe to illustrate the problem. 

The time got multiplied to 13.5 times the original. The failure rate got multiplied to 781.25 times the original.

The problem is twofold.

First, in my opinion, it should add multiplicators together, not multiply multiplicators with each other. Using addition (either with subtracting 1 from each proficiency during the calculation, or in recipes themselves, and adding _1_ only once), we reach these values:

Original time of the recipe is 6h

multiplicator of time for all proficiencies put together would be
**1** + .5 + .5 + 1.5 + 1 + 1.5 = 6 (total time is 36h in comparsion to 81h)

multiplicator of failure rate for all proficiencies put together would be
**1** + 4 + 4 + 1.5 + 4 + 1.5 = 16 (total FR multiplier in comparsion to 781.25)

Second problem is that all proficiencies are used during the entire process of crafting. Which should not be the case, at least not in all recipes.

In our case, we might say that 6 hours of crafting time is splitted into
2 hours of metalworking
2 hours of welding
2 hours of leatherworking

Thus, welding proficiencies should not be used to multiply 6h, but only 2h, etc. Now, this would probably be more complicated to implement than it deserves, so values in .json could be set lower to reflect this in such kind of recipes instead.

# Describe alternatives you've considered
Tweak values in .json to achieve similar result, though needed values would probably end up all over the place...

# Additional context
Image of the leather seat recipe used in the example
![image](https://user-images.githubusercontent.com/6969268/96686162-771b0a80-137e-11eb-8036-5bf272f47405.png)

**Comment by I-am-Erk** [comment]
There is room for debate here, but this has been brought up before, and I still don't consider it behaving inappropriately.

Your character knows:
- nothing about metalworking
- nothing about welding
- nothing about leatherworking
- not that much about building things at all.

In that context you are trying to weld a metal frame and upholster it with leather. Why would you expect that to have any reasonable chance of success? And if you do succeed it's going to take you ages, 81 hours is in fact insanely optimistic (as are all our crafting times even after the change). You wouldn't start playing guitar by trying to slam a classic Hendrix riff while riding a motorcycle, which you also don't know how to do.

In my opinion, the problem here is primarily that we don't yet have any way besides learning the proficiency to adjust these penalties, [and we totally need it](https://github.com/CleverRaven/Cataclysm-DDA/issues/44680). The penalties themselves are IMO totally appropriate. If I bought a sheet of leather, a welder, and some pipes, and went into my shop to build a seat for my car, I would probably burn my house down and I would definitely not successfully build a seat.

**Comment by Robik81** [comment]
I think that penalty calculation is wrong on fundamental level as it is. If forementioned leather seat was splitted to several parts and each part had its own recipe with only related proficiencies applied to it, I believe that result would be closer to my formula.

If you have problem with how quick the item is crafted, then change its basic crafting time.

In any case, if the goal is to eliminate crafting, because in cataclysm scenario, quickest and most reliable way to get the item is to loot the item, not craft the item, current approach is a way to go.

Just like the pursuit or realism AFAIK eliminated farming. Crafting seems to be another fun part of the game to follow.

**Comment by I-am-Erk** [comment]
> I think that penalty calculation is wrong on fundamental level as it is. If forementioned leather seat was splitted to several parts and each part had its own recipe with only related proficiencies applied to it, I believe that result would be closer to my formula.

There is definitely some merit to what you're talking about here, and I wonder if we can work out a way to group proficiencies. Using this as an example, the leatherworking and metalworking parts are separate. An ideal solution would have the multipliers for all the metalworking portions multiplied together, and all the leatherworking multiplied together, and then get the end result back.

> If you have problem with how quick the item is crafted, then change its basic crafting time.

I *don't* have a problem, that's my point. I think it taking much longer when you don't know any of what you're doing is totally appropriate, and the numbers we're getting are still well within reasonable timeframes - or even unreasonably short - for crafting something like this from scratch.

> In any case, if the goal is to eliminate crafting, because in cataclysm scenario, quickest and most reliable way to get the item is to loot the item, not craft the item, current approach is a way to go.

The goal - balance-wise - is largely to discourage you from crafting complex items in the early game, forcing you to rely on looting or makeshift stuff, and then allowing you to build more and more of what you want as you advance. If you just want to drive your vehicle and don't want to go hunting for stuff, you can craft a wooden vehicle seat, so this still fits that paradigm perfectly. 

> Just like the pursuit or realism AFAIK eliminated farming. Crafting seems to be another fun part of the game to follow.

I have no idea what you're talking about here. Farming hasn't changed much at all afaik except to become much less tedious.

**Comment by Robik81** [comment]
Oh, farming is definitely less tedious, than it was, and I also did my best to help make it less tedious... to stroke my own ego a bit ;-)

My issue with farming is, that it takes too long for a harvest to occur since season length was changed, that it is not worth to even bother with it (unless something changed and I am not aware of it).

And that is my main fear with crafting. It takes time to gain proficiencies. I feel that if you take into an account the amount of time needed to gain proficiencies until you can feasibly craft the thing you want, you might end up deciding that it is not even worth the effort and just go almost pure looting route. Then, once you looted the stuff, there is no longer any reason to craft anymore.

And I don't think you can take leisurly inefficient route, while the zombies are evolving around you. Well, you probably can, but you are certainly incentivised / rairoaded to one style of play (combat + loot) instead of having several efficient choices to pick from.

**Comment by I-am-Erk** [comment]
> Oh, farming is definitely less tedious, than it was, and I also did my best to help make it less tedious... to stroke my own ego a bit ;-)

You deserve the ego boost, some of the best changes ever.

> My issue with farming is, that it takes too long for a harvest to occur since season length was changed, that it is not worth to even bother with it (unless something changed and I am not aware of it).
>
> And that is my main fear with crafting. It takes time to gain proficiencies. I feel that if you take into an account the amount of time needed to gain proficiencies until you can feasibly craft the thing you want, you might end up deciding that it is not even worth the effort and just go almost pure looting route. Then, once you looted the stuff, there is no longer any reason to craft anymore.
> 
> And I don't think you can take leisurly inefficient route, while the zombies are evolving around you. Well, you probably can, but you are certainly incentivised / rairoaded to one style of play (combat + loot) instead of having several efficient choices to pick from.

You are essentially hitting all the pixels and missing the image.

- farming takes longer
- crafting takes longer
- evolution and zombie spawns take longer
- seasons last longer

Do you see where this is going? The goal is to remove all the artificially deflated times so that we no longer have to balance a bunch of arbitrarily fake numbers and instead just say "irl how long should thing take to do" and then have the time for thing be that. Then all we need to balance for gameplay is the zombie evo timer and other fictional stuff.

**Comment by Robik81** [comment]
Okay, I just hope that the game where everything takes the same time as it would in the RL is actually fun to play.

Well, I said my piece and changes you are proposing would help. If they are easy enough to do and make enough difference to matter before #42556 is implemented, I don't know.

**Comment by I-am-Erk** [comment]
I can't see why it wouldn't. Personally I'm very interested in feeling like holing up for the winter two years after the zombie apocalypse is a real achievement. We're almost done now, and only a few perf and automation improvements away from passing days to weeks quite quickly if need be.
