### ISSUE TITLE
Crafting Search for Proficiency Broken

### ISSUE THREAD

**Issue by rickyrich88** [CleverRaven/Cataclysm-DDA#45002]
# Describe the bug

When in the crafting menu, searching for recipes by proficiency doesn't work.

# Steps To Reproduce

1. Make player and learn all recipes
2. Search by proficiency in crafting menu
3. Search returns nothing.

# Expected behavior

Search should and used to return recipes using said proficiency.

# Versions and configuration

- OS: Windows 10
    - OS Version: 10.0 2004
- Game Version: 0.E-7026-g87ee0ff [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by rickyrich88** [comment]
Worked perfectly fine in this version:

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-6539-gfec5a27 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by Pupsi-Mupsi** [comment]
You are right. Has been fixed in #44974.
Update the game and everything will be just fine ;-)

**Comment by Robik81** [comment]
As @Pupsi-Mupsi wrote, it is fixed. I confirmed that the proficiency search works properly in current version of the game (Win64) from releases.
