### ISSUE TITLE
Using an oxytorch from a pulled trolley or on the ground does not consume charges

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#45018]
# Describe the bug
When using an oxytorch placed in a pulled (foldable, only kind tried) trolley to cut down a metal door no charges are consumed, while doing the same from the inventory does consume charges. Placing the torch on the ground beside (only place tested) the action also fails to consume charges.

# Steps To Reproduce
- Place an acetylene torch ("oxytorch") in a (foldable) trolley (pulled) by the PC (character too weak to carry torch and weapon/armor).
- Check the number of charges in the torch.
- Activate the torch with 'a' to cut up a metal door (aim it at a door if multiple targets).
- Check the number of charges in the torch. It remains unchanged.

or
- Place an acetylene torch on the ground beside the character (location probably not important, but that's what I tested after pulling it from the trolley).
- Repeat the further actions above, with the same result.

Note that I did try to use the torch in the same manner when it was placed in the character's inventory, with the normal charge deduction result.

# Expected behavior
Resources should be consumed regardless of whether the torch is in the inventory or used from some other nearby location.

# Versions and configuration

<!-- Please complete the following information; you can now go to:
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: Please install `git` to generate VERSION [64-bit] (0.E2 stable, with debug output for vehicle dismantling bug identification as the single modification [reported separately]). Note that the debugging was prompted by the same behavior in the downloaded, precompiled 0.E2 stable version.
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
I've tried debugging the issue, and can see that the call "it.ammo_required()" on the line
"const int charges_used = std::min( act->values[0], it.ammo_required() );" of the operation
"activity_handlers::oxytorch_do_turn" in activity_handlers.cpp returns 0 in the bugged cases and 4 in the correct one.
I've also seen that the debugger claims it.type.tool (one or more of the '.' should probably be '->') is empty in the bugged cases and contains something in the working one. It can be noted that both the working and bugged cases correctly report that the torch had 190 charges before the action.

I don't believe the trolley being pulled at the time is important, as I think I've done it both ways. Nor do I think foldable is important, but that's typically what you have down in places where the doors are....

This issue may or may not be related to other cases where resources are not consumed, such as #43398, and base camp orders to butcher corpses returning one or more corpses together with the butchery results (seems to be one of each kind of corpse if batched, or the only one if a single corpse).

**Comment by Xpyder** [comment]
Something similar happens with UPS modded items like the makeshift welder and hotplate.

I'd assumed it was UPS specific but given this issue maybe it's something with all remotely used items that consume charges?

**Comment by RoyBerube** [comment]
It looks fixed for me. Tested with an acetylene torch in a shopping cart, and cut open some sealed up gun store windows. 40 charges are used each time I try - either in inventory, on the ground, or in the shopping cart.
