### ISSUE TITLE
Completing a quest for rabbit-tender makes you indebted as a reward

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#45014]
# Describe the bug

# Steps To Reproduce

# Expected behavior

# Screenshots
![](https://tinystash.undef.im/il/2tss3ph1G8wD5qrQ8u1eVhifCDKSvrfgEmLqKM6LmAJoZjn5yHneq9Rgpv4zVHzLD9ZaQhUsGHpvPnji1RE3qSkX)

# Versions and configuration
- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.E-7041-gdb7d1378fa-dirty [64-bit]
- Graphics Version: Curses
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

# Additional context

**Comment by Maleclypse** [comment]
I was unable to reproduce this on windows build.
