### ISSUE TITLE
"Iron safari" mission 

### ISSUE THREAD

**Issue by NiktoNekto** [CleverRaven/Cataclysm-DDA#45016]
Guys, I'm sorry. 

Intercom in center 01 issued an "iron safari" mission, a rifle, a UPS and a heavy battery (1000). 

Reloaded UPS, saved, exited, entered - caught the following: 
ERROR: src / item_contents.cpp: 324 [void item_contents :: combine (const item_contents &, bool)] error: item UPS_off cannot fit into pocket while loading: item is too large. 

The charged UPS accordingly disappeared from the inventory.

**Comment by int-ua** [comment]
Removing the `Bug` label until a fresh confirmation. @NiktoNekto please use the issue template.

**Comment by OliveChukar** [comment]
Tested in ver 0.E-9111-gd1e702b-dirty. Started iron safari reloaded the UPS that intercom gave me then saved and closed the game. When loading in again nothing happened and I could not confirm the problem.
