### ISSUE TITLE
Not Interrupted while Grabbing and moving furniture

### ISSUE THREAD

**Issue by kaffo** [CleverRaven/Cataclysm-DDA#45010]
# Describe the bug

When you `G`rab some furniture and try to move it, the character is not interrupted if approached or attacked by an enemy

# Steps To Reproduce

1. `G`rab something heavy (fridge, counter, bookcase...)
2. Drag it towards a group of enemies
3. Don't get asked to stop when they approach/attack you

# Expected behavior

The player gets asked if they wish to stop the activity like any other activity when an enemy is nearby/attacking them.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-7041-gdb7d137 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Generic Guns [generic_guns],
    Generic Guns - UndeadPeople Tileset [Generic_GunsUDP],
    Graphical Overmap [Graphical_Overmap],
    Bionic Slots [cbm_slots],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

I assume the Grabbing mechanics need to be moved to a `player_activity` so they can be properly interruptable.

**Comment by anothersimulacrum** [comment]
> I assume the Grabbing mechanics need to be moved to a player_activity so they can be properly interruptable.

Bingo!
