### ISSUE TITLE
Impossible to consume heroin w/o a syringe

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#45017]
Cataclysm implies heroin is only usable via injection, even though injection is about the worst route from the medical point of view: https://en.wikipedia.org/wiki/Heroin#Routes_of_administration

**Comment by Rivet-the-Zombie** [comment]
I think snorting, smoking, and boofing are the most common ROAs for entry-level users. By the time most folks reach the stage where they're banging it they're already really deep into it.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
