### ISSUE TITLE
Satiety appears to be backwards

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#45025]
# Describe the bug

Satiety appears to be implemented backwards.  Lower satiety makes you full, high satiety doesn't

# Steps To Reproduce
- Make yourself very hungry (like work out very hard, then sleep without eating)

Save the game
- Summon Buttered Popcorn
- Note the satiety is minimal (as it should be for popcorn, irl you can eat a LOT of this in one sitting)
- Eat 2 unit (2/4 of 1 bag)
- Note you are now engorged and in pain

Reload so you're at the same hunger level
- Summon something with high satiety
- Eat an equivalent volume of food
- note you're not engorged

# Expected behavior
Popcorn shouldn't overfill your stomach so easily

Also expressed satiety on the eat menu should correspond to how much of an item you can eat.  Intuitively a fuller bar should indicate a fuller stomach

# Screenshots

![image](https://user-images.githubusercontent.com/12039454/96962349-7340d280-14bb-11eb-9977-65c615d7a39b.png)

# Versions and configuration

- OS: Windows 10
    - OS Version: 10.0 1909
- Game Version: 0.E-7041-gdb7d137 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    Stats Through Kills [stats_through_kills]
]

# Additional context

The satiety values are super all over the place.  If they're autogenerated I'd guess they should be based primarily on volume adjusted by weight as very low density foods tend to shrink in your stomach (popcorn being a super obvious one, but Fried Rice being a good irl example).  (Technically chemistry has a lot to do with it too, high carb foods dissolve more completely in the stomach but not sure how we could represent that... unless it starts to take the materials into account like Wheat and Junk Food)

**Comment by GGgatherer** [comment]
I don't see how this is "backwards". Satiety = calories/ volume, meaning low satiety = the food takes up much space and provides little calories. Which is exactly what happened in your case.

**Comment by DoctorGoat** [comment]
it's really weird that a high satiety meter means it isn't filling and a low meter means it is

**Comment by Xpyder** [comment]
> I don't see how this is "backwards". Satiety = calories/ volume, meaning low satiety = the food takes up much space and provides little calories. Which is exactly what happened in your case.

That's counter-intuitive but I'm willing to explore the idea with you for a ways, assuming that's true then how his popcorn very filling with low calories?

**Comment by natsirt721** [comment]
> it's really weird that a high satiety meter means it isn't filling and a low meter means it is

That's not true necessarily - the disconnect is that satiety isn't equivalent to food volume. One can imagine a food with low volume but very high satiety, a food that wouldn't be filling but would provide a large amount of calories.

**Comment by Xpyder** [comment]
> That's not true necessarily

The specific line you quoted actually is talking about how the meter is reversed from what it implies.  When I see a food with a high Satiety that tells me it fills you up, not that it leaves you feeling hungry.  I think if it was called kcal/vol that would make more sense

Given the rest of your comment though I think maybe you're talking about the mechanics not the orientation of the meter


> One can imagine a food with low volume but high in calories - thus having very high satiety.

I assume you're talking about a food that has a low volume but high calories and thus leaves you feeling full, but I'm having trouble coming up with an IRL example for this, do you have one off hand?

**Comment by Zireael07** [comment]
@Xpyder: Satiety is calories/volume, so low volume and high calories gives you high satiety, e.g. many snacks IRL.

**Comment by GGgatherer** [comment]
> That's counter-intuitive 

It is counter-intuitive because you assume "satiation" is "filing the volume of your character's stomach" while it is instead "amount calories'.

> but I'm willing to explore the idea with you for a ways, assuming that's true then how is buttered popcorn very filling with low calories?

...because it is high-volume, therefore filling your stomach with very few portions. And each such portion provides very few calories. So, low calories/high volume = low satiety.

**Comment by dustan1** [comment]
The actual problem here seems to be that popcorn IRL is full of air which drastically increases its volume in the bag, but shrinks down to roughly the same size as any other corn product in the stomach. I don't know if food volume can be divorced from stomach volume, but that would be the proper solution for this.

**Comment by Xpyder** [comment]
> The actual problem here seems to be that popcorn IRL is full of air which drastically increases its volume in the bag, but shrinks down to roughly the same size as any other corn product in the stomach. I don't know if food volume can be divorced from stomach volume, but that would be the proper solution for this.

This says better what I was trying to get at.  Stated more generally Popcorn has a high volume but a low density and when dissolved in stomach acid shrinks dramatically.  Weight is a better indicator of total mass than volume generally.

That being said, if this really is just a problem with popcorn it's probably not worth doing an entire rework just for that.  The calories for popcorn are still incorrect, though not as badly as I first assumed.  Popcorn is apparently mostly fiber.  From the research I've been able to turn up 1 cup (about 0.25 L) of air popped popcorn has about 100 calories not 50, and 1 cup of buttered popcorn is closer to 150-300 (not 80) depending on the butter/oil and how much you use.

That being said I'm not a nutritionist and the websites I'm using as reference are definitely not scholarly so I'd want a second person to weigh in on this before I'd be comfortable changing the calories by so much.

**Comment by Xpyder** [comment]
> It is counter-intuitive because you assume "satiation" is "filing the volume of your character's stomach" while it is instead "getting as much calories as possible".

That's because "the feeling or state of being sated" is the literal definition of Satiation.  I can and will adapt but that doesn't make it the incorrect descriptor

**Comment by Zireael07** [comment]
The name "Satiation" was chosen because all the alternatives were too long to be displayed in the consume menu.

**Comment by Xpyder** [comment]
> The name "Satiation" was chosen because all the alternatives were too long to be displayed in the consume menu.

This makes a lot of sense, I've had significant trouble coming up with a concise alternative.  The best I've been able to come up with so far are "Caloric Density" or "Consumability"

While there is value to having the bar oriented the way it is and changing the descriptor to match, after giving this quite a bit of thought I'm not so sure that that's really the core of the issue.

I think because Hunger and Fullness are actually separate that they should be independently presented on the interface and leave the judgement on whether high caloric density is desirable or not up to the player.  So rather than satiety I would present that bar could instead be for "Filling" as in how full it makes you.

**Comment by Xpyder** [comment]
If that seems sensible to people I'll close this and present it as a separate issue as I think that might be both less contentious and better for the game in the long run

**Comment by Xpyder** [comment]
Since my core issue here has fundamentally changed and this has gotten a bit contentious (for which I share responsibility) I'm gonna close this issue.
