### ISSUE TITLE
Odd character/item dup glitch in death

### ISSUE THREAD

**Issue by wizardjian** [CleverRaven/Cataclysm-DDA#45024]
# Dead player body spawns when closing game at grave screen.

I was messing with the debug menu when I accidently killed myself. I than press esc and went to the grave screen after the "would you like to see how you died" when I loaded back in, I was alive at my previous save and a dead copy of me by my side with all the items I had on. 

# Steps To Reproduce

1. Make a quick save.
2. Go to debug menu and set head/torso HP to 0 or just do damage to self.
3. Press Esc at the "would you like to watch your last moments" and stay on the tombstone screen.
4. Tab out and close the game.
5. Launch the game and go to the same world, should show you the character still there.
6. Go back in game and a clone of your character and all their items are dead on the ground.

# Expected behavior

Not sure but my guess is that when you die, the game creates a dead body of your character but only saves the death after the tombstone screen. So by quitting the game after the creation of the dead body and before saving the death to the character causing a delete which results in a copy of yourself on the ground while your character can still be loaded. 

# Screenshots

N/A Pretty simple steps, retested myself and it works just as how I described it.

# Versions and configuration

Experimental Build #11117 default world setting

**Comment by ZhilkinSerg** [comment]
Not a bug - you closed the game before it managed to erase your player character.
