### ISSUE TITLE
Shell carriers

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#45021]
# Is your feature request related to a problem? Please describe.
Spare ammo cannot be carried on a firearm, despite the ability to do so via mounted shell carriers or inherent storage compartments. It cannot currently be accomplished by adding a container pocket to the gun's definition or attempting to use item mods from #41917 to add the storage compartments; when attempted, it fails to recognize the ammo in the gun mod/second pocket when attempting to reload. The itemmod option also cannot be refilled without taking it off of the gun, while the inherent second pocket can be but shows an "over max volume" error if the ammo's volume goes over the player's other storage.

# Describe the solution you'd like
Guns are able to support a container pocket's contents being shifted to its magwell pocket on reload.

# Describe alternatives you've considered
Gunmods can modify the pocket of the gun to add a second compartment, and inherent storage is just handled as an irremovable mod.

# Additional context
Shell carrier example
https://www.sportsmansguide.com/product/index/mesa-tactical-sureshelltrade-6-shell-carrier-for-m4-sopmod-stock?a=641820
Springfield Armory M6 Scout has a storage compartment in its stock for fifteen .22 Long Rifle cartridges and four .410 shotshells.
![image](https://user-images.githubusercontent.com/51099123/96937416-10891000-1496-11eb-98cb-5c6e0f26170a.png)

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
