### ISSUE TITLE
Character Generation Rework 1: "Hobbies" selection

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#45031]
# Problem
Players need some flexibility in starting proficiency choices, especially when we start changing some of the starting mutations that should actually be proficiencies, like parkour. Adding a flat ability to select proficiencies is hard to balance for cost: proficiencies like basic leatherworking are not worth a full point. On the other hand there'd be a lot of minmax temptation for certain high value proficiencies. 

# Solution
This fits with a larger desire to overhaul character generation completely, and provides what I think is a great first step.

Add a "hobbies and details" segment to chargen, after professions. These would be small packages similar to professions, that add a few proficiencies, skill XP, and a bit of equipment.

Many current professions could be migrated to hobbies instead, clearing up the profession interface a bit. In the process we'd probably reduce the contents of some professions to encourage fleshing out details with hobbies. As an example, "cosplayer" is fine as a hobby. If you want to play a professional cosplayer you'd be best suited choosing something like "model" as your profession and "cosplay" as your hobby, getting a more detailed and interesting explanation of your character and setting them apart from the "high schooler" profession with "cosplay" hobby in immediately noticeable ways.

As part of this, I suggest that we change the way skill levels are granted in character generation to instead grant starting XP. This would discourage minmaxing, since the xp bonuses would generally be limited to get you up a couple levels and would drop off a lot to stop you racking up bonuses and starting at level10. However by making it xp based you still get all the benefits, starting at level 3 + 20% or whatever: you don't lose a bonus entirely because you didn't get quite enough points to put you over the threshold.

Similarly we should allow attribute buffs from hobbies, which would obey the current diminishing returns attribute points formula.

## Interaction with professions
Hobbies/details get an array of "tags", such as "military" or "arts and crafts". We add the same tags to professions as well (really I suspect hobbies are just going to be professions in the code side and we're actually talking about allowing more than one profession). Professions and hobbies then have either "permit" and "forbid" lists. Certain hobbies and details could be flagged to only appear as options if something else you've selected Permits them. On the flip side if you have a profession that forbids a particular hobby set, those options get closed off.

This feature would be a bit limited in use to start, but becomes critically important in the next phase when we use these details to build your survivor story.

## Example "hobby" JSON entry
Watch this space, coming soon!

## Longer Term
Eventually we would want to expand this segment to also include aspects of your survival story, and from there help you to create a full background with associated mechanical benefits.

In the longer term it would also be really neat if certain hobbies/professions/details could be unlocked by achievements in previous playthroughs. This would be especially appropriate for challenge starts and late game starts.

# Additional Notes
This is the product of many conversations with lots of people but a lot of it is @esotericist's concepts.

This system would also help form the basis for much more interesting randomized NPCs, especially if we make unique dialogue for NPCs based on what hobbies they have interacting with their background traits.

For consideration, but not really for discussion in this issue:
<Details>There is some debate over whether or not we'd want to keep the "adjust skills and attributes yourself" phase... I am of the opinion that if we remove it we should have hobbies that accomplish similar changes, like "bodybuilder" granting +2 strength, etc. The end result would be the same but it would give some helpful feedback on your character power level if you're selecting "honours student", "bodybuilder", "marathon runner", and "gymnast" all together to achieve the level of attributes you want.</details>

**Comment by Night-Pryanik** [comment]
Should be closed after #50262?
