### ISSUE TITLE
[Magiclysm] Blood Power Generator CBM using charges instead of volume

### ISSUE THREAD

**Issue by Arkaile** [CleverRaven/Cataclysm-DDA#45040]
# Describe the bug

Blood power generator CMB does not measure the volume of blood it contains, but instead treats blood as charges, with each charge being 0.25L (250mL) which is well beyond what the item's description states being its maximum capacity, that being 100mL. This works out to requiring 25L of blood to fill the generator. Simple math, I know, but I just had to type that out because it's absurd enough to be funny.

# Steps To Reproduce

1. Install blood power generator CBM and a power storage CBM.
2. Spawn a flask of human blood. It should contain 0.25L of blood.
3. Consume it and see how many charges it added to the CBM. From my experience, it should only add one charge.

# Expected behavior

A 250mL flask should be able to refill the CBM's storage two and a half times, but that just isn't the case. I'm not sure how this could be done, but, with its current description, the generator should be treating each mL of blood as a charge.

Perhaps its efficiency could be increased and its capacity changed to one or two litres? As it stands, this generator is not worth using whatsoever.

 - OS: Windows 10
 - Game Version: 0.E-7041-gdb7d137 [64-bit]
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: 
  "dda",
  "no_npc_food",
  "package_bionic_professions",
  "secronom",
  "aftershock",
  "Arcana",
  "blazeindustries",
  "crt_expansion",
  "magiclysm",
  "XEAS",
  "DinoMod",
  "Cata++",
  "Mining_Mod",
  "more_survivor_stuff",
  "MMA",
  "Chibi_Ultica",
  "Graphical_Overmap",
  "Graphical_Overmap_Magiclysm",
  "speedydex",
  "stats_through_kills"

**Comment by Xpyder** [comment]
Can I ask how you determined it's using charges instead of volume?  I've been trying to debug this but I the code trail for bionics that use ammo seems excessively knotted

**Comment by anothersimulacrum** [comment]
The blood generator still requires 25L of blood.

**Comment by hexagonrecursion** [comment]
Note: the CBM currently does not accept human blood (id: blood) (see https://github.com/CleverRaven/Cataclysm-DDA/issues/54030) so I used animal blood (id: animal_blood) instead.

This is what I see after putting 250ml of animal blood into the CBM:

![DeepinScreenshot_select-area_20220104145753](https://user-images.githubusercontent.com/52621858/148056119-87e6608e-4e33-423a-be6c-84ee9cd52d66.png)

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: eacb7d9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]
]
