### ISSUE TITLE
"Silent alarm clock" from CBM doesn't work when deaf, no silent alarms in the game

### ISSUE THREAD

**Issue by Mrzjadacz** [CleverRaven/Cataclysm-DDA#45044]
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-1231-g4968f19 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    No Fungal Monsters [No_Fungi],
    Magiclysm [magiclysm],
    Aftershock [aftershock],
    DinoMod [DinoMod],
    Mining Mod [Mining_Mod],
    No Rail Stations [No_Rail_Stations],
    Graphical Overmap [Graphical_Overmap],
    Arcana and Magic Items [Arcana]
]

### Expected behavior

`Internal Chronometer` provides you with a silent alarm clock functionality, it should work when `Sound Dampeners` CBM is enabled or when you are deaf.
There should be a spawn or a craft for some silent alarm clock, like  `alarm clock` + `vibrator`/`smart lamp`.

### Actual behavior
![image](https://user-images.githubusercontent.com/26396019/97083255-03dbf780-160f-11eb-8f62-ec83d0545789.png)
![image](https://user-images.githubusercontent.com/26396019/97083258-06d6e800-160f-11eb-8a74-1c0165d3fabd.png)
After engaging `Sound Dampeners` I get the info that I won't be woken up by alarm due to deafness.

### Steps to reproduce the behavior

Install/debug those two CBMs, enable `Sound Dampeners`, then attempt to fall asleep.

**Comment by Pupsi-Mupsi** [comment]
Silent alarm seems to work just fine. I installed "Internal Chronometer" and activated "Sound Dampeners". Went to bed and set an alarm. Alarm woke me up after 3 hours. 
![grafik](https://user-images.githubusercontent.com/44737997/97095038-db79ea80-165a-11eb-9796-0b3a39f151b4.png)

I could change the "deaf-hint" to something like this:

(The player is in fact deaf so he does not notice a sound but has an active silent alarm.)
![grafik](https://user-images.githubusercontent.com/44737997/97095036-d9179080-165a-11eb-84e2-cfcbcf94c688.png)


What do you think?

<hr />

Sucessfully tested:

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-7073-g8d4cd2f280-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    GP-Mods [gpmod],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Bionic Professions [package_bionic_professions],
    Aftershock - UndeadPeople Tileset [AftershockUDP]
]

**Comment by Mrzjadacz** [comment]
I tested it when my pawn was less tired.
It seems the alarm doesn't work for me cause I overuse atomic coffee and other stimulants, so my character just sleeps through any distractions.
I'm closing this issue and opening a feature request for a silent alarm.
