### ISSUE TITLE
Lockpicking gives huge amounts of experience at high device level

### ISSUE THREAD

**Issue by SSpook** [CleverRaven/Cataclysm-DDA#45043]
# Describe the bug

Picking locks gives increasing amounts of experience depending on the devices level of the character.
At level 8 it takes around 12 locked bar doors to increase devices level.
At level 10 it takes only 7.
After level 14 or so you get a level each time you open a door.

# Steps To Reproduce
Find a prison.
Find a lockpick or hairpin, get devices level to 8 or higher.
Close, lock and pick open some bar doors.
Observe the devices level.

# Expected behavior

Expected devices level to increase by a very small amount or not at all.

# Versions and configuration

 - Game Version: 0.E-6779-gc3caa74
 - Mods loaded: dda

**Comment by I-am-Erk** [comment]
Hm, interesting. I didn't touch Device xp but I bet that's the problem, it probably draws from one of the variables I changed.
