### ISSUE TITLE
can't set ammo null in hm12 dazzle rifle as it is not an ammo

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#45041]
# Describe the bug

# Steps To Reproduce
Load the game, try to trade with the intercom.

# Expected behavior
No error messages.

# Screenshots

# Versions and configuration
- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.E-7041-gdb7d1378fa-dirty [64-bit]
- Graphics Version: Curses
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

# Additional context
[2020.10.21.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5432505/2020.10.21.zip)

**Comment by neosulc** [comment]
Issue still persists

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-8549-gad21647 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by hexagonrecursion** [comment]
Could not reproduce using the attached save
- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 17b9ea1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

**Comment by I-am-Erk** [comment]
Closing as stale
