### ISSUE TITLE
Adding a silent alarm more attainable than a Internal Chronometer CBM.

### ISSUE THREAD

**Issue by Salty-Panda** [CleverRaven/Cataclysm-DDA#45052]
# Is your feature request related to a problem? Please describe.
Alarm clocks make lots of noise, it's less of a problem if they wake you up, but if you sleep through it, it might lure zombies to you.

# Describe the solution you'd like
There should be a spawn or a craft for some silent alarm clock, like `alarm clock` + `vibrator`/`smart lamp` or maybe wearable item: blindfold with processor, diode and small battery.
It would wake you up without making noise and would be significantly easier to get than a fairly rare CBM.

# Describe alternatives you've considered
A trait like `Disciplined sleep` (possibly auto-obtained at reaching sufficient survival level) that would substitute alarm clock via self-discipline, but less precise. Would require C++ though.

**Comment by Zireael07** [comment]
Silent (vibrating) alarm clocks are actually a thing IRL and they are extremely hard to sleep through.

Source: am profoundly deaf and use one of those

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
