### ISSUE TITLE
Countering while weary seems to cause more delay before next action leading to stunlocking

### ISSUE THREAD

**Issue by Rayeneth** [CleverRaven/Cataclysm-DDA#45064]
# Describe the bug

Countering while weary seems to cause more delay before next action leading to stunlocking

# Steps To Reproduce

be weary, have a high counter chance and heavy armor (to survive the hits)

# Expected behavior

I expect to not put my life at risk from countering.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-7041-gdb7d137 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

**Comment by GGgatherer** [comment]
This, combined with #45100, is a recipe for disaster. Countering drains stamina and makes you more weary, you cannot run/walk away fast enough (and you stay in place for several turns for each counter) so more zombies can come at you making you counter more... until you can't.

**Comment by anothersimulacrum** [comment]
#44533 does not appear to check for weariness penalties.
