### ISSUE TITLE
Cranium bomb CBM put torso on fire

### ISSUE THREAD

**Issue by zeropol** [CleverRaven/Cataclysm-DDA#45061]
Game version: 0.E-7143-g19c7921 build 11119

Operating system: Windows 10 x64

Tiles or curses: Tiles

Mods active:
dda
no_npc_food
aftershock
blazeindustries
aftershockudp
blazeindustriesudp
speedydex
statsthroughskills

### Expected behavior
The bomb explode after about a month

### Actual behavior
The bomb put torso on fire really early on ( I got put on fire on day 3 )

### Steps to reproduce the behavior
- Choose Bionic Operator profession.
- Survive a few days
- Have no luck ( reverting an autosave showed me the bomb don't trigger the fire at the same time )

### Note
If it is the intended behavior for the cranium bomb, the description of the CBM could suggest the bomb will cause problems before the 1 month dead man switch.

**Comment by Maleclypse** [comment]
The description that you are short on days is in the profession.  The bomb also uses an intermittent spell so it can go off anytime after start.  It has an average explosion time per the spell of five days.  It could in a given playthrough never go off but it most likely will have gone off by day ten.  I'm seeing these fire posts pretty frequently which makes me think I've made the damage too low.  It's supposed to be fatal in all but around 5% of instances.

**Comment by zeropol** [comment]
Thanks for the insight. Should I delete this issue ?

Thanks for your work btw.

( only took this profession once. Got lit on fire on night 2. Reverted autosave because I thought it was a bug. On Discord I was said it was related to the cranium bomb and someone told me to bug report here. After reverting the save I got the fire on day 3, not on night 2. Then, on day 4, and it killed me )

**Comment by John-Candlebury** [comment]
Although you have the final say, Maleclypse,  I think its perfectly fine if you make the cranial bomb going off definetively kill you in all instances.

It would aslo be less prone to random issues like this.

**Comment by Maleclypse** [comment]
I'll change the profession text and the CBM text and set it to kill.  Please leave this issue open to help me remember to make a PR that closes it.  :)
