### ISSUE TITLE
Proficiencies not all displayed correctly due to a wrap-around text

### ISSUE THREAD

**Issue by kleric42** [CleverRaven/Cataclysm-DDA#45067]
Game version: 0.E-7071-g00daf3a

Operating system: Windows10

Tiles or curses: Tiles

Mods active:

### Expected behavior
Ability to see all proficiencies with progress on them.

### Actual behavior
Due to a word-warp on the Spring-powered Guns and Crossbows Prof., it blocks the display of another prof.

### Steps to reproduce the behavior
Not sure if it always happens or not, but when Spring-powered... is the 5th Prof., I can't see the 6th Prof.,
See screenshot.

![image](https://user-images.githubusercontent.com/19361975/97126879-b68a8380-16fd-11eb-9a45-c411b3d25ace.png)

**Comment by Pupsi-Mupsi** [comment]
Please update the game. Should have been fixed in #44728.
