### ISSUE TITLE
Supply crates map special spawns only open crates with nothing in them

### ISSUE THREAD

**Issue by kholat** [CleverRaven/Cataclysm-DDA#45073]
# Describe the bug

Supply crates map special spawns only open crates with nothing in them.

# Steps To Reproduce

Make a new world and walk/run/teleport around with map notes enabled and you will see that all the supply drops have open crates with nothing in them always.

# Expected behavior

They should spawn closed, and have stuff in them at least some of the time.

# Screenshots

Self explanatory.

# Versions and configuration

- OS: Windows 10 64 bit
    - OS Version: 10.0 2004
- Game Version: 0.E-7143-g19c7921 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Blaze Industries [blazeindustries],
    More Survivor Stuff [more_survivor_stuff]
]

# Additional context

none

**Comment by Night-Pryanik** [comment]
What time has passed since _the Cataclysm_? The chance for supply crates to spawn open (=looted by someone else) increases greatly with every passed day.

**Comment by Night-Pryanik** [comment]
I can't confirm this on latest experimental as of 26th of October. Debug-spawned supply drop map extra, and crates were closed and unlooted on Spring, day 31 of year 1.
![изображение](https://user-images.githubusercontent.com/11132525/97201062-6f6ac400-17cb-11eb-8a9a-6fdb96db6add.png)

**Comment by kholat** [comment]
OOOOOH i didnt know this is a function of time passed now, very cool, my bad then you can close the issue it was a winter start so almost 1 year passed
