### ISSUE TITLE
Should foods show Filling rather than Satiety?

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#45077]
# Is your feature request related to a problem? Please describe.
Context: 
In the current system Hunger and Fullness are not opposite sides of a single bar, but in fact separate systems.  Hunger being a long term representation of calories stored, and Fullness being a short term representation of the volume of stomach contents.  This is much closer to IRL than the old system, and I generally approve of this way of handling it

At Present:
On the Eat menu currently we show Satiety.  This was chosen because Satiety was the simplest descriptor we could find for kcal/vol (whether eating a lot of it will satisfy hunger long term) even though it appears backwards at first glance.

Issues: 
However the way it's currently presented implies that higher calories is always better, which isn't necessarily the case
Also it takes out some of the thought players need to put into choosing foods (just pick the one with the biggest green bar)

# Describe the solution you'd like
I would present that instead it should show how Filling a food item is, leaving the judgement of whether High caloric density is desirable up to the player (this would be more impactful if there was a morale penalty to being hungry that got worse either over time or with intensity)

It would also require more thoughtfulness on behalf of the player; and do so hopefully without increasing fiddlyness in late game characters as I think a lot of people converge on making only a small number of optimal foods (or just eating everything in sight regardless of stats depending on mutations)

# Describe alternatives you've considered
Leaving it as it is, but there might be other options too

# Additional context

My underlying assumption in a game like this is that it's usually better to have a larger number of *meaningful decisions and a smaller number of **meaningless decisions (provided it follows the [pacing chart](https://www.gamasutra.com/view/feature/132242/gameplay_fundamentals_revisited_.php))

*meaningful decisions in this context is a decision that is both impactful and for which you have (or can have) enough knowledge to consider outcomes

**meaningless decisions in this context is a choice either who's optimal outcome is already decided for you, or who's difference in outcome is effectively insignificant/irrelevant or for which you don't have (and can't have) enough information to consider the ramifications of the choice presented

In this case, balancing the Fillingness of food against it's calories/vitamins on one hand, and the hunger penalty on the other hand being a meaningful decision

and just spamming whichever food has the fullest green bar being a meaningless decision

This evolved out of a discussion in #45025 (that turned a bit contentious, but I do agree with some of the points presented and they successfully caused me change my underlying position)

**Comment by natsirt721** [comment]
Personally, I find neither satiety nor fillingness meaningful factors when it comes to me choosing what to eat. Both are proportional to the volume of the food, for which I find is rarely something I consider when planning my meals. For long-term or volumetrically constrained storage satiety is useful, but at that point you can run the numbers yourself and determine what you should be stashing. I suppose fillingess as a percentage of total stomach space may be useful (i.e. if you eat this, your stomach fullness will increase by x%), but that's just a different way to represent the volume of the portion, and is a little gamey by assigning a hard number to an otherwise hidden statistic.

**Comment by GGgatherer** [comment]
We already have food volume for that. So please, no.

**Comment by dchieh222** [comment]
I have to admit that Satiety was immensely confusing to me.

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
