### ISSUE TITLE
Non floating vehicles drive on water

### ISSUE THREAD

**Issue by angstr0m** [CleverRaven/Cataclysm-DDA#45084]
# Describe the bug

Non floating vehicles (like regular cars) can drive on water like boats. The player won't drown or sink as long as he doesn't let go of the controls and moves inside the vehicle.
When the player lets go of the controls and moves inside the car, he sinks.

Cars that should float (by using enough metal boat hulls) show the same behavior.

Normal boats (like canoes) seem to work just fine.

# Steps To Reproduce

1. Create a new character.
2. Get a regular car.
3. Drive the car onto deep water.
4. Stop driving when the car is completely on the deep water.
5. Observe:
  - The player does not drown.
  - The vehicle does not sink.
6. Let go of the vehicle controls and move inside the vehicle.
7.  Repeat the process with the same vehicle. But this time add enough metal boat hulls to make it float.

# Expected behavior

Regular cars should sink when they drive onto deep water. The player inside the vehicle should drown.

The player should be able to move inside amphibious cars (with metal boat hulls) without sinking.

# Screenshots

<img width="1680" alt="float_bug_0" src="https://user-images.githubusercontent.com/733176/97232433-6be03880-17dd-11eb-81b8-554657d9ff95.png">
<img width="1680" alt="float_bug_1" src="https://user-images.githubusercontent.com/733176/97232441-6f73bf80-17dd-11eb-99d0-36dff63aa9e4.png">
<img width="1680" alt="float_bug_2" src="https://user-images.githubusercontent.com/733176/97232453-74d10a00-17dd-11eb-9436-bd6b4f6bf90b.png">
<img width="1680" alt="float_bug_3" src="https://user-images.githubusercontent.com/733176/97232460-77cbfa80-17dd-11eb-884b-aa7c72117b38.png">

# Versions and configuration

- OS: MacOs
    - OS Version: Name: Mac OS X; Version: 10.15.7; Build: 19H2; 
- Game Version: ee57532467 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

none

**Comment by mlangsdorf** [comment]
I think Kevin over-optimized the check for floating or falling vehicles.  A vehicle currently counts as floating if at least half of its wheels are in not on terrain with the NO_FLOOR flag.  Water tiles do not have the NO_FLOOR flag.  I think I have a simple fix that won't cause performance regressions, though.
