### ISSUE TITLE
Look up or down Z level

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#45082]
# Is your feature request related to a problem? Please describe.
We should be able to look up or down z-levels.  

# Describe the solution you'd like
Maybe while in e[x]plore mode use the 'up stairs' and 'down stairs' keys to change z-levels
and long term ideally be able to fire across z-levels (though firing up/down with arrows would likely require some range modifiers)

# Describe alternatives you've considered
not sure.  Currently you can get a rough idea what's below you by looking out over empty space, but nothing specific

# Additional context
Some mods might be affected by this too like Magiclysm where certain effects only make sense if anchored on the ground (like Vegetative Grasp) while others can work across empty space (like Wooden Shaft)

**Comment by natsirt721** [comment]
> Maybe while in e[x]plore mode use the 'up stairs' and 'down stairs' keys to change z-levels

I'm pretty sure this is already implemented, at least to some extent? I believe you can shoot as well but I think it is broken or otherwise not behaving as intended, at least in some circumstances.

**Comment by Xpyder** [comment]
> I'm pretty sure this is already implemented, at least to some extent?

I'll try again tonight, but I'm pretty sure last time I tried it didn't work.  from a high z level you can see what kind of terrain is below you, but not objects or any detail

**Comment by molkero** [comment]
Turn on experimental 3d field of vision in debug options.

**Comment by Xpyder** [comment]
> Turn on experimental 3d field of vision in debug options.

Interesting, I assumed that z-level was mostly fleshed out and didn't still need to be debug enabled.

I'll take a look at that

**Comment by Xpyder** [comment]
I've tested and confirmed this does seem to do what I was asking.
