### ISSUE TITLE
Allow (base camp) recipes to calculate the requirements from the palette, and the recipes to define the palette to be used with a template.

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#45098]
# Is your feature request related to a problem? Please describe.
Looking at modifying the base camp layouts, I've found that you have to manually calculate time, resources, materials, etc. required to "craft" those recipes. Given that the recipes specify that tiles should be modified to becomes specified tiles for which there already exist crafting recipes, it would make sense to specify what to do, and let the computer calculate all the derived info.
Similarly, making a recipe for a construction using a second palette instead of a previous one means copying the complete definition file and replacing the template plus some description. It's fairly easy to do, but a pain to maintain, as any change will then have to be done number of palette times to get the constructions for different materials align.

# Describe the solution you'd like
A keyword in the recipe that states it should derive resulting fields from the construction recipes for those tiles. Similarly, a keyword in the recipe that specifies the palette to use. When supplied, it would override any palette specified for that map description, or, even better, the ability to actually have the palette to use as part of the construction choices.  This would require the palette selection to be performed in a step prior to the material selection, as the latter set of info is dependent on the palette. However, it would cut down on the confusing number of entries in the list (build Foo, rather than build Foo from Bar * palettes).

# Describe alternatives you've considered
Brute force and bugs, i.e. do it manually, as well as a script that modifies the files based on the dependencies.

# Additional context
There are at least three complications involved:
- Transitive recipe dependencies. The construction of a window requires the presence (and thus construction) of an empty window. The logic should follow the dependency chain to come up with the compound requirements.
- Non construction dependencies: Some recipes require e.g. (shallow) pits, and other construction work not available via the construction menu. I'd consider adding those to the construction menu.
- Non available dependencies: The base camp workshop allows you to create a drop hammer, which is an item you can't construct in any other way (as far as I know). I would either consider adding such items to the set of craftable constructions, or define the recipes for those in their "base" recipe files marked as non learnable recipes.

An advantage of the suggested derived requirement calculation is that any changes done to the recipes depended upon would propagate to the top level recipes automatically, rather than relying on manual maintenance to keep them in sync.

**Comment by ZhilkinSerg** [comment]
There is blueprint autocalc - see https://github.com/CleverRaven/Cataclysm-DDA/pull/43268

**Comment by PatrikLundell** [comment]
Great. It looks like the bigger issue had been dealt with before I wrote the suggestion (although I don't know how the "additional context" issues are handled currently).

Thus, it looks like this suggestion should be shifted to only suggest palette selection as part of the blueprint usage process.

**Comment by SunshineDistillery** [comment]
Are you talking about palettes or mapgen updates?

**Comment by PatrikLundell** [comment]
Sorry, I'm not sure how to interpret the comment, and so the answer may be off.

Assuming the comment refers to my previous post (as opposed to the complete post):
Currently the palette to use is part of the mapgen templates, which means that it's not possible to apply the same layout part of the template to any other palette than the one that's part of the definition. Instead, you have to make a copy of the complete template and change the palette.

The suggested change would be to either allow the template to leave the palette section blank, which should then force any recipes that use that template to specify the template to use, or allow for the recipe to override the palette specified by the template with a template supplied by the recipe (that may be either "hard coded" or the result of a recipe palette selection, with the former probably being of little use).
For that to work, the template logic would need to have an additional, optional, step where the palette to use with the template is selected, before the recipe requirements can be presented. It would be good if the palette selection part of the recipe indicated the palette selections that have their materials requirements fulfilled (as the current selection does).

From a player point of view, it would mean a less cluttered list of build options, so instead of "Build X from A", Build X from B", ... "Build X from H" followed by a range of "Build Y from *" options (where the 0.E2 recipes have several cases where the building material isn't specified, so the player has to guess based on the ingredient lists), you get "Build X", "Build Y",... at the cost of having the building material set (i.e. palette) selected as an extra step after selecting what to build.

You might even consider the possibility of having either palettes or complete templates as the intermediate step. This might be used as "Build beds in room X", followed by the selection of straw beds or proper beds, followed by the requirements list for the current base camp recipes, or "Tape up window" followed by a selection of which type of window you want to tape up in the current construction menu, or for that matter, a "Start building a wall" followed by the selection of the type of wall, but that's complicated by the continuation of the wall building, as there's at most one legal continuation. It might be possible to go directly to the building materials if there's exactly one legal option based on the preconditions, but the player should always have the ability to preview the requirements for all alternatives to allow for planning (in the case of auto selection of the only legal alternative you'd have to apply the recipe to a tile that doesn't match any requirement.

**Comment by ZhilkinSerg** [comment]
Palettes are used for mapgens. There are no palettes in recipes.

**Comment by PatrikLundell** [comment]
The proposal was to add palette usage to recipes.

**Comment by ZhilkinSerg** [comment]
> 
> 
> The proposal was to add palette usage to recipes.

What would that solve/achieve?

Mapgen palette contains mapping between symbol used in a visual blueprint and various mapgen objects (terrain, furniture, item/monster spawn, etc). Recipes do not need that mapping - result of the basecamp recipe is id of mapgen object (which already can use mapgen palette).

**Comment by PatrikLundell** [comment]
It would allow a single recipe to use a single blueprint to generate the "same" item/building from different materials.
E.g. Build base camp section X->select palette->base camp section X generated using the "stone", "metal", "resin", etc. palette as per the player's palette choice.
The current method has the player select from a (potentially rather long) list consisting of a set of the "same" recipes that differ only by the material (it didn't help that a number of 0.E2 stable base camp recipes failed to state which materials they used in their description, so selection had to be done by comparing building materials used).
It also has the benefit on the maintenance end that changes (by blueprint modifications or as a result of an engine changes) wouldn't have to be repeated manually on each copy of the blueprint as you could make do with a single blueprint.

**Comment by ZhilkinSerg** [comment]
So, your issue is more about reducing number of entries in UI and creating submenu with all possible variants?

E.g. changing

```
kitchen (wood)
kitchen (stone)
kitchen (metal)
```

to

```
kitchen
```
plus some kind of submenu
```
wood
stone
metal
```

**Comment by PatrikLundell** [comment]
Correct, that's the first half of it. The second half is a reduction of the number of blueprints to one per set of materials, rather than one per material.

I guess the UI end would be less messy if there was some kind of human understandable logic behind the placement of the entries, rather then having them scattered all over the long list, but even an improvement to that, I'd still prefer to see a top level reduction of the number of entries.

**Comment by ZhilkinSerg** [comment]
You won't reduce number of blueprints - blueprint results are unique.

**Comment by PatrikLundell** [comment]
Pity the palettes can't be factored out, as that was the second half. Still, I think the first half still has merit.

**Comment by ZhilkinSerg** [comment]
"Palettes" won't help when recipe results have different patterns. Say, "metal" kitchen is:
```
abc
  a 
bbb
```

and "wooden" kitchen is:

```
ccc
bbb
aaa
```

You can't combine these two in a single recipe with multiple "palettes" for values `a`, `b` and `c`.

**Comment by PatrikLundell** [comment]
True. It would only work when you actually use the same blueprint layout and apply a different palette to it.

**Comment by jbytheway** [comment]
I've finally started an attempt at implementing parametric basecamp expansions to allow one layout to be used with multiple materials.  I have a couple of questions I'm hoping @PatrikLundell could answer:

* What's the easiest way to test basecamp expansions?  I've never actually set one up in-game, and I'm not sure what the shortest path to get there is (assuming free use of the debug cheats menu).
* My initial plan is to merge `fbmh_2_wood_room_NE_1` and `fbmh_2_log_room_NE_1` into a single mapgen entry.  Does that sound like a good place to start?

**Comment by PatrikLundell** [comment]
Thanks!

I'm making a description a that's a bit more detailed than I think you need, both because of just in case, and because someone else might find the rambling useful.

The easiest way is to recruit a companion (I just use a standard start and retry until successful, but it can be debugged), move to an open field (away from swamps, wasp nests, etc. to avoid having to kill the pests off with the debug menu all the time), buff all the companion's skills to 10, order the companion to set up a camp of the desired type (field camp version 2 should work for everything except the tent option, as that doesn't have any windows), spawn tools and building materials (soil is a royal pain, as you have to keep spawning the stuff again and again because so much is used) and then save. With auto saving off, you can then use that as the starting point (and you can make a backup of it to have a "clean" starting position, just in case). I tend to spawn additional tools and materials in successive attempts and save the save to incrementally get what's needed.
From then on it's mainly boring: Order the companion to construct, debug time passing, check that what was constructed matches the expectations, order the companions to construct, ... (or kill the game and reload the "clean" save for the next attempt, of course).
Note that my testing has mainly been with one material/template set at a time, so I only spawn "common" materials in the save, such as glass, hinges, nails, etc. Spawning everything for all versions fully constructed would be a major pain.
When spawning materials I typically spawn 100 at a time (pressing to repeat until the area is filled), with the exception of some things that supported in higher numbers (pebbles, nails), as a too high a number seems to just spawn nothing.

Any of the rooms except the tent should work (they still have the same footprint in version 2 though, but not in version 1). I would use Mi-Go resin (or alien resin, as it's actually called) as one of them. It's my go-to because it's the fastest to construct and the one that uses the lowest number of tools and materials (just resin and a metallic smoother). In your case it also has the advantage that none of its construction elements is shared with any other material variant, so errors ought to be reasonably easy to spot. The disadvantage is that both the "windows" and "doors" are somewhat difficult to see (but not invisible), and I think the rammed earth "windows" likewise don't stand out much.

**Comment by jbytheway** [comment]
I failed to comment when this was marked stale, but it is still planned, even implemented; just waiting on 0.G freeze to be over.

**Comment by jbytheway** [comment]
Bump to avoid staleness.
