### ISSUE TITLE
CDDA crashes (abnormal termination) in refugee center during waiting  or sleeping.

### ISSUE THREAD

**Issue by PseudoDork** [CleverRaven/Cataclysm-DDA#45101]
# Describe the bug
CDDA crashes while waiting or sleeping in the refugee center.

# Steps To Reproduce
(To immediately reproduce)
1. Load save file and the game should be in an active waiting period that shortly leads to a crash.

(To reproduce from a fresh spawn)
1. Acquire the refugee center mission from the terminal in the evac shelter.
2. Travel/Teleport to the refugee center.
3. Wait or sleep within the complex.

# Expected behavior

I expected to be able to wait, sleep or perform time advancing activities without the game crashing in the refugee center.

# Screenshots

# Versions and configuration

 - OS: Windows 7 64 bit home premium
 - Game Version: 0.E-7193-g1ae4a80
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: Default  [core dda, disable NPC needs, bionic professions]

# Additional context

So I've been able to reproduce this issue across the 3 latest experimental builds (pre 0.E-7193).  In the beginning I was actually
playing the game as intended, but lately I've been using the debug menu to try different things to isolate
the reason for the crash. The crash occurs with or without tiles, and irrespective of what tileset is used.
I've started new characters and new worlds, teleported to the location and reproduced the crash every time. 
I would just wait and sleep elsewhere to circumvent this, but on some occasions I get segmentation faults without waiting or sleeping at all.  
<NOTE: I generally have my PCs audio device disabled as I typically run an external interface for music playback, I enabled it and
still no dice>
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5448285/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5448287/debug.log)
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5448304/save.zip)

**Comment by Ramza13** [comment]
So I'm working on a fix for this.  It is caused by NPC's trying to equip weapons that are null or messed up.  It should only happen once every hour sleeping, waiting or not and is related to at least one NPC trying to equip something in a sheath.

**Comment by PseudoDork** [comment]
Glad to know, much appreciated. 

On loading a bugged save during some test runs, the debug system would log things along the line of "can't set ammo null in <<firearm type>> as it is not an ammo". Not sure if that is insightful or not, but it seems pertinent to what you said.

**Comment by Ramza13** [comment]
Looks like someone beat me to it.  #44832 seems to have fixed this.

**Comment by PseudoDork** [comment]
I tested with the latest win x64 tiles build and can confirm that this issue has been solved.
Thanks for addressing it!!!!
