### ISSUE TITLE
Crash when sleeping

### ISSUE THREAD

**Issue by Hexyes** [CleverRaven/Cataclysm-DDA#45116]
game crashed when i sleep (occurs at 5:30)

# Steps To Reproduce

1 load save file (link below, character is Lowell Tapia
2 sleep

# Expected behavior

game continues to run

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-6779-gc3caa74 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [] (it's english)
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Tankmod: Revived [Tankmod_Revived],
    No Fungal Monsters [No_Fungi]
]
* that's odd, that mods loaded doesn't show stats through skills. I thought I had that loaded

# Additional context
 currently I have an NPC dissasembling a vehicle to the north west of me, that may be related as I know right now faction camps are not the most stable

drobox requires sign up but here's a google drive link. zip has save file and the crash and debug logs https://drive.google.com/file/d/1gyEbAQuXwX1lD4dC-MxRZKvteMmLmKYu/view?usp=sharing

**Comment by Hexyes** [comment]
so I had the npc follow me and was able to get past that point. I know you guys said you weren't working faction camps at the moment.

**Comment by BrettDong** [comment]
Tried multiple times and I am still unable to reproduce this in the latest experimental. Is this issue still present for you?
