### ISSUE TITLE
Farm silo missing second, third z-level ladders

### ISSUE THREAD

**Issue by natsirt721** [CleverRaven/Cataclysm-DDA#45119]
# Describe the bug
Some farm silos are missing the second and third tier of ladders. The one at ground level exists, but a warning is displayed when trying to climb it, and if you proceed you immediately fall back to the ground

Probably related to #45097 

# Steps To Reproduce
1. Find a farm - the one with two 2x4 sections with a road down the middle
2. Attempt to climb the silo ladder
3. Observe warning, proceed to climb
4. "You triggered a ledge" and fall to the ground.

# Expected behavior
I end up safely on the second story of ladder

# Screenshots
The map showing the offending farm - other farms in the area with silos were successfully climbed prior to today.
![image](https://user-images.githubusercontent.com/6325435/97466285-4f491b00-1919-11eb-8279-71d76ca326d7.png)

Next to the silo
![image](https://user-images.githubusercontent.com/6325435/97466510-90d9c600-1919-11eb-84e0-c6d7dc67ae52.png)

e[x]amining up one z-level (experimental z-levels enabled) Note the lack of ladders
![image](https://user-images.githubusercontent.com/6325435/97466400-71429d80-1919-11eb-8673-d197e64f49f2.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-7200-gfc2388e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Beta National Guard Camp [national_guard_camp],
    More City Locations [cityside],
    More Locations [more_locations]
]

# Additional context
I'm guessing that the aforementioned farms update forgot to add the ladders to the second and third z-levels.

**Comment by RobertoVGoulart** [comment]
I tried replicating on version 0.E-7200-gfc2388e and it worked normally, there were ladders all the way to the top.
But i did notice you are using some mods that are currently obsolete, so i guess your world is kinda old? your bug might be related to that.

**Comment by curstwist** [comment]
This is probably related to older mapgen areas where the building wasn't fully generated yet.  I recently working on these silos, which could have caused this inconsistency.  We saw something similar during the roof additions.  I double-checked and they work fine in newer worlds.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.E-10390.
