### ISSUE TITLE
Last stages of infection makes you freeze to death

### ISSUE THREAD

**Issue by Scintile** [CleverRaven/Cataclysm-DDA#45113]
Game version:  11124 

Operating system: Windows 10

Tiles or curses: Tiles

Mods active: None, only the base game

### Expected behavior 
Last stages of infection shoud not make you freeze to death with 2 blankets on your body

### Actual behavior 
When you get to "Pus filled" stage of the infection you get progressively more and more cold. My test character had around -200 in character sheet on all body parts, my main character died with around -400 on all body parts.

### Steps to reproduce the behavior
1.  Create a character with an infection (using Infected scenario is easiest. My main character had a head infection, test character had torso infection)
2. Wait untill you get to "pus filled" stage
3. Wait some more - you will get cold, then start to freeze. For my test character i took 3 pills of Ambien to speed up waiting process by sleeping

![1eabed5e8f891f81b3e8745942b75ab5](https://user-images.githubusercontent.com/61324239/97437303-516ca300-1934-11eb-8316-63baab5612ae.png)

Screenshot of my main character an hour before death from freezing. This is modded character. Test one with no mods, no traits is similar

**Comment by int-ua** [comment]
Removing the `Bug` label until a fresh confirmation.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/pc-is-way-too-cold/25730/4
