### ISSUE TITLE
Segmentation Fault 0.E-7041-gdb7d137 When using spider mutagen

### ISSUE THREAD

**Issue by KisuPL** [CleverRaven/Cataclysm-DDA#45126]
I've been chugging a bunch of mutagens trying to create a desired mix of mutations from many different trees and now whenever i use a spider mutagen, the game gives me a segmentation error and crashes. I tried changing tilesets, removing some of the mutations and using the mutagen then (it worked but only for one use, then it crashed again). I was hoping there was a way to fix the isssue without having to remove the mutations. Here's the log, hope you can help

> **-----------------------------------------**

22:20:34.470 : Starting log.
22:20:34.471 INFO : Cataclysm DDA version 0.E-7041-gdb7d137
22:20:34.486 INFO : [main] C locale set to C
22:20:34.486 INFO : [main] C++ locale set to C
22:20:34.486 INFO : SDL version used during compile is 2.0.5
22:20:34.486 INFO : SDL version used during linking and in runtime is 2.0.5
22:20:34.863 INFO : Number of render drivers on your system: 4
22:20:34.863 INFO : Render driver: 0/direct3d
22:20:34.863 INFO : Render driver: 1/direct3d11
22:20:34.863 INFO : Render driver: 2/opengl
22:20:34.863 INFO : Render driver: 3/software
22:20:34.868 INFO : [options] C locale set to C
22:20:34.868 INFO : [options] C++ locale set to C
22:20:34.894 INFO : Active renderer: 0/direct3d
22:20:35.359 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
22:20:35.482 INFO : Language is set to: 'en'
22:20:35.482 INFO : [translations] C locale set to English_United States.1252
22:20:35.482 INFO : [translations] C++ locale set to C
22:20:35.926 ERROR : (error message will follow backtrace)
  #0
    (dbghelp: @0x67c5d6[cataclysm-tiles.exe+0x27c5d6]), 
    (libbacktrace: Z21debug_write_backtraceRSo+0x56@0x67c5d6),
    (libbacktrace: 0x67c5d6    [unknown src]:0    [unknown func]),
  #1
    (dbghelp: @0x67d01c[cataclysm-tiles.exe+0x27d01c]), 
    (libbacktrace: Z8DebugLog10DebugLevel10DebugClass+0x2fc@0x67d01c),
    (libbacktrace: 0x67d01c    [unknown src]:0    [unknown func]),
  #2
    (dbghelp: @0x681b50[cataclysm-tiles.exe+0x281b50]), 
    (libbacktrace: Z12realDebugmsgPKcS0_S0_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x50@0x681b50),
    (libbacktrace: 0x681b50    [unknown src]:0    [unknown func]),
  #3
    (dbghelp: IMG_LoadWEBP_RW+0x11cef4@0x1382014[cataclysm-tiles.exe+0xf82014]), 
    (libbacktrace: Z12realDebugmsgIJPKcEEvS1_S1_S1_S1_DpOT_+0x344@0x1382014),
    (libbacktrace: 0x1382014    [unknown src]:0    [unknown func]),
  #4
    (dbghelp: @0xb90c25[cataclysm-tiles.exe+0x790c25]), 
    (libbacktrace: ZN11mod_manager12load_modfileERK10JsonObjectRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x1f5@0xb90c25),
    (libbacktrace: 0xb90c25    [unknown src]:0    [unknown func]),
  #5
    (dbghelp: @0xb91b9c[cataclysm-tiles.exe+0x791b9c]), 
    (libbacktrace: ZZN11mod_manager13load_mod_infoERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEENKUlR6JsonInE_clES9_+0xac@0xb91b9c),
    (libbacktrace: 0xb91b9c    [unknown src]:0    [unknown func]),
  #6
    (dbghelp: @0x54f087[cataclysm-tiles.exe+0x14f087]), 
    (libbacktrace: ZNSt17_Function_handlerIFvRSiEZ28read_from_file_optional_jsonRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt8functionIFvR6JsonInEEEUlS0_E_E9_M_invokeERKSt9_Any_dataS0_+0x87@0x54f087),
    (libbacktrace: 0x54f087    [unknown src]:0    [unknown func]),
  #7
    (dbghelp: @0x552dd3[cataclysm-tiles.exe+0x152dd3]), 
    (libbacktrace: Z14read_from_fileRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt8functionIFvRSiEE+0x143@0x552dd3),
    (libbacktrace: 0x552dd3    [unknown src]:0    [unknown func]),
  #8
    (dbghelp: @0x55310d[cataclysm-tiles.exe+0x15310d]), 
    (libbacktrace: Z28read_from_file_optional_jsonRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt8functionIFvR6JsonInEE+0x6d@0x55310d),
    (libbacktrace: 0x55310d    [unknown src]:0    [unknown func]),
  #9
    (dbghelp: @0xb8e9c3[cataclysm-tiles.exe+0x78e9c3]), 
    (libbacktrace: ZN11mod_manager13load_mod_infoERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x83@0xb8e9c3),
    (libbacktrace: 0xb8e9c3    [unknown src]:0    [unknown func]),
  #10
    (dbghelp: @0xb8ed6b[cataclysm-tiles.exe+0x78ed6b]), 
    (libbacktrace: ZN11mod_manager14load_mods_fromERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x4b@0xb8ed6b),
    (libbacktrace: 0xb8ed6b    [unknown src]:0    [unknown func]),
  #11
    (dbghelp: @0xb8f8f5[cataclysm-tiles.exe+0x78f8f5]), 
    (libbacktrace: ZN11mod_manager16refresh_mod_listEv+0x105@0xb8f8f5),
    (libbacktrace: 0xb8f8f5    [unknown src]:0    [unknown func]),
  #12
    (dbghelp: @0xb94905[cataclysm-tiles.exe+0x794905]), 
    (libbacktrace: ZN11mod_managerC1Ev+0xd5@0xb94905),
    (libbacktrace: 0xb94905    [unknown src]:0    [unknown func]),
  #13
    (dbghelp: @0x10b71e9[cataclysm-tiles.exe+0xcb71e9]), 
    (libbacktrace: ZN12worldfactoryC2Ev+0x79@0x10b71e9),
    (libbacktrace: 0x10b71e9    [unknown src]:0    [unknown func]),
  #14
    (dbghelp: @0x79cc02[cataclysm-tiles.exe+0x39cc02]), 
    (libbacktrace: ZN4gameC1Ev+0xa82@0x79cc02),
    (libbacktrace: 0x79cc02    [unknown src]:0    [unknown func]),
  #15
    (dbghelp: IMG_LoadWEBP_RW+0x809847@0x1a6e967[cataclysm-tiles.exe+0x166e967]), 
    (libbacktrace: main+0x1077@0x1a6e967),
    (libbacktrace: 0x1a6e967    [unknown src]:0    [unknown func]),
  #16
    (dbghelp: @0x4013ed[cataclysm-tiles.exe+0x13ed]), 
    (libbacktrace: _tmainCRTStartup+0x23d@0x4013ed),
    (libbacktrace: 0x4013ed    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crtexe.c:336    __tmainCRTStartup),
  #17
    (dbghelp: @0x4014fb[cataclysm-tiles.exe+0x14fb]), 
    (libbacktrace: WinMainCRTStartup+0x1b@0x4014fb),
    (libbacktrace: 0x4014fb    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crtexe.c:186    WinMainCRTStartup),
  #18
    (dbghelp: BaseThreadInitThunk+0x14@0x7ffa5fbd7c24[KERNEL32.DLL+0x17c24]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #19
    (dbghelp: RtlUserThreadStart+0x21@0x7ffa61b2cea1[ntdll.dll+0x6cea1]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
Backtrace emission took 1 seconds.
(continued from above) ERROR : src/mod_manager.cpp:216 [void mod_manager::load_modfile(const JsonObject&, const string&)] there is already a mod with ident BL9
22:21:06.550 ERROR : src/mod_manager.cpp:216 [void mod_manager::load_modfile(const JsonObject&, const string&)] there is already a mod with ident BL9
22:21:06.950 WARNING : opendir [./mods/] failed with "No such file or directory".
22:21:32.263 INFO : Loaded tileset: UNDEAD_PEOPLE_BASE
22:21:38.311 WARNING : opendir [./save/Kittredge/mods] failed with "No such file or directory".
22:21:44.092 INFO : Loaded tileset: UNDEAD_PEOPLE_BASE
22:21:44.441 ERROR : (error message will follow backtrace)
  #0
    (dbghelp: @0x67c5d6[cataclysm-tiles.exe+0x27c5d6]), 
    (libbacktrace: Z21debug_write_backtraceRSo+0x56@0x67c5d6),
    (libbacktrace: 0x67c5d6    [unknown src]:0    [unknown func]),
  #1
    (dbghelp: @0x67d01c[cataclysm-tiles.exe+0x27d01c]), 
    (libbacktrace: Z8DebugLog10DebugLevel10DebugClass+0x2fc@0x67d01c),
    (libbacktrace: 0x67d01c    [unknown src]:0    [unknown func]),
  #2
    (dbghelp: @0x681b50[cataclysm-tiles.exe+0x281b50]), 
    (libbacktrace: Z12realDebugmsgPKcS0_S0_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x50@0x681b50),
    (libbacktrace: 0x681b50    [unknown src]:0    [unknown func]),
  #3
    (dbghelp: @0x91381c[cataclysm-tiles.exe+0x51381c]), 
    (libbacktrace: ZNK12Item_factory17check_definitionsEv+0x294c@0x91381c),
    (libbacktrace: 0x91381c    [unknown src]:0    [unknown func]),
  #4
    (dbghelp: @0x83c436[cataclysm-tiles.exe+0x43c436]), 
    (libbacktrace: ZN17DynamicDataLoader17check_consistencyER10loading_ui+0x1816@0x83c436),
    (libbacktrace: 0x83c436    [unknown src]:0    [unknown func]),
  #5
    (dbghelp: @0x83d8e3[cataclysm-tiles.exe+0x43d8e3]), 
    (libbacktrace: ZN17DynamicDataLoader20finalize_loaded_dataER10loading_ui+0x12f3@0x83d8e3),
    (libbacktrace: 0x83d8e3    [unknown src]:0    [unknown func]),
  #6
    (dbghelp: @0x7a26f7[cataclysm-tiles.exe+0x3a26f7]), 
    (libbacktrace: ZN4game19load_world_modfilesER10loading_ui+0x567@0x7a26f7),
    (libbacktrace: 0x7a26f7    [unknown src]:0    [unknown func]),
  #7
    (dbghelp: @0x7b86ab[cataclysm-tiles.exe+0x3b86ab]), 
    (libbacktrace: ZN4game5setupEv+0xdb@0x7b86ab),
    (libbacktrace: 0x7b86ab    [unknown src]:0    [unknown func]),
  #8
    (dbghelp: @0xa2b706[cataclysm-tiles.exe+0x62b706]), 
    (libbacktrace: ZN9main_menu18load_character_tabEb+0x556@0xa2b706),
    (libbacktrace: 0xa2b706    [unknown src]:0    [unknown func]),
  #9
    (dbghelp: @0xa33187[cataclysm-tiles.exe+0x633187]), 
    (libbacktrace: ZN9main_menu14opening_screenEv+0xdc7@0xa33187),
    (libbacktrace: 0xa33187    [unknown src]:0    [unknown func]),
  #10
    (dbghelp: IMG_LoadWEBP_RW+0x809ea5@0x1a6efc5[cataclysm-tiles.exe+0x166efc5]), 
    (libbacktrace: main+0x16d5@0x1a6efc5),
    (libbacktrace: 0x1a6efc5    [unknown src]:0    [unknown func]),
  #11
    (dbghelp: @0x4013ed[cataclysm-tiles.exe+0x13ed]), 
    (libbacktrace: _tmainCRTStartup+0x23d@0x4013ed),
    (libbacktrace: 0x4013ed    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crtexe.c:336    __tmainCRTStartup),
  #12
    (dbghelp: @0x4014fb[cataclysm-tiles.exe+0x14fb]), 
    (libbacktrace: WinMainCRTStartup+0x1b@0x4014fb),
    (libbacktrace: 0x4014fb    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crtexe.c:186    WinMainCRTStartup),
  #13
    (dbghelp: BaseThreadInitThunk+0x14@0x7ffa5fbd7c24[KERNEL32.DLL+0x17c24]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #14
    (dbghelp: RtlUserThreadStart+0x21@0x7ffa61b2cea1[ntdll.dll+0x6cea1]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
Backtrace emission took 0 seconds.
(continued from above) ERROR : src/item_factory.cpp:1460 [void Item_factory::check_definitions() const] warnings for type mss_survivor_axeheadmod:
gunmod does not specify install time

**Comment by Ramza13** [comment]
Any chance you can upload your save game?

**Comment by KisuPL** [comment]
Thanks for the interest, I used the debug menu to add the mutations I wanted bc I wasn't sure how long I'd have to wait for help and after quickly checking, the issue seems to have been resolved in the process.  The game no longer crashes when I use the serum

**Comment by Ramza13** [comment]
Hmm if you happen to have the save where you can cause this issue still around I'd love a look but if not no worries.

**Comment by KisuPL** [comment]
I don't, sorry :/
