### ISSUE TITLE
[Magiclysm] Demon Spider seems a bit overpowered

### ISSUE THREAD

**Issue by Moumix3** [CleverRaven/Cataclysm-DDA#45127]
# Describe the bug

Demon Spiders have 20d8 damage, which is 20 to 160 damage per hit (basically can one shot any body part even with the best armor in the game), with a melee skill of 9, and 435hp. This means they're basically impossible to engage in melee for 99.99% of characters.

# Steps To Reproduce

1. Create a character with good stats and a good armor (heavy survivor suit or heavy exoskeleton armor for example)
2. Go fight **one** demon spider in melee
3. See the damage received through the armor (can easily reach 30+ damage per hit through heavy exoskeleton armor)

# Expected behavior

Demon Spiders having the "size of a car" should be though and dangerous even for well-geared & high skilled characters, but maybe not to *that* point?

# Screenshots

Check Vormithrax's video starting at 1:11:00: https://www.twitch.tv/videos/779499463

# Versions and configuration

Build #11103

Mods:
- Core
- Magiclysm

# Additional context

The Spider Queen also inherits the number of damage dices from the demon spider, and she has d20 as damage, so she has 20d20 damage (20 to 400 damage per hit), with a 10 melee skill.

This is a boss fight, so that might be intended, but just giving this as additional context if this would need fixing too.

**Comment by Moumix3** [comment]
Tagging @KorGgenT as it's Magiclysm.

**Comment by KorGgenT** [comment]
demon spiders should not be engaged in melee.
