### ISSUE TITLE
Staff sling cannot acquire a length characteristic from json

### ISSUE THREAD

**Issue by dchieh222** [CleverRaven/Cataclysm-DDA#45122]
# Describe the bug

The item with the id "staff_sling" is unable to be given a "longest_side" inside of its json file and have it utilized in-game. If provided with one, it will ignore it. This behavior was replicated by the developer "mlangsdorf" on Discord in #dev-help.

# Steps To Reproduce

1. Edit the staff_sling entry in slings.json
2. Add "longest_side": "180 cm"
3. Create a new character with a new world, and debug spawn the item. 
4. You will notice that the staff sling fits in any backpack 

# Expected behavior

Editing the JSON file should permit the item to acquire a length. As suggested by the SHEATH_SPEAR flag, this should be considered a "quarterstaff" and require a spear sheath in order to utilize effectively. 

# Screenshots

Screenshots do not provide much insight for this. If desired, please edit your \data\json\items\ranged\slings.json and this behavior will be replicated. 

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-6777-g4c39b3d [32-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

Attached please find my modified json. 
[slings.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5454516/slings.zip)

**Comment by KorGgenT** [comment]
this is because the staff sling has leather as a material, which is soft. items that are soft do not display a length because that length is what is used to determine if an item can fit.

Therefore, the logic to item::is_soft() needs to be update to not be soft if any of the components are not soft, rather than being soft if any of the components are soft.

**Comment by J-Cieplinski** [comment]
I could try to sort this out if available.
