### ISSUE TITLE
Anesthesia kit generated with 6k charges instead of 3k

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#45134]
# Describe the bug

An-kit in freshly generated military bunker (homebase type, not storage type) had 6000 charges. 7.72L volume in 3.25L volume container.

# Steps To Reproduce

I guess, walk around until you find such a bunker and hope it decides to spawn the kit?

# Expected behavior

It having 3k charges (or less).
# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-7193-g1ae4a80 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills],
    Bionic Professions [package_bionic_professions]
]

# Additional context
It was a freshly generated part of overmap (and therefore freshly generated local map) so not an artifact of some old build.

**Comment by Pupsi-Mupsi** [comment]
You are right.
This has been changed in ##44899.
