### ISSUE TITLE
(for Dark Days of the Dead) ACHILLES_HEEL_STRICT and ACHILLES_HEEL flag for enemies

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#45142]
# Is your feature request related to a problem? Please describe.
I have left Dark Days of the Dead sitting for a bit too long, thanks to COVID.

DDotD is supposed to simulate a romero zombie movie. It actually does this pretty well in many ways, but it is missing one very important thing: Zombies are *way* too easy to kill. The goal would be to have a nearly unstoppable horde that slowly advances.

# Describe the solution you'd like
You must destroy the brain!

Add two ACHILLES_HEEL flags to enemies. Enemies with this flag:
* Only take HP damage on a critical hit. In ACHILLES_HEEL, massive damage sufficient to gib the target also counts. In ACHILLES_HEEL_STRICT it does not.
* Damage that isn't a critical hit or gib-level attack instead reduces the target's move.
* If the target's move is reduced to zero by damage, it is knocked down and stops taking further move damage.

ACHILLES_HEEL_STRICT *only* allows damage through critical hits. ACHILLES_HEEL allows you to harm the enemy with HP damage with effects, so that they can be lit on fire to kill them.

# Describe alternatives you've considered
* Eventually CDDA core wants a more complex damage system that might be able to flex into this system with some data-driven stuff, but I'd like DDotD to be properly set up much sooner and I don't think this is a big ask.

# Additional context
* I also want to be able to increase critical hit chance for DDotD, and to allow a Coup de Grace if you melee a knocked down zombie. Those can wait though.
* It would be lovely but unlikely to have a way to turn a zombie into a crawling zombie if it received high but not massive damage.
* This could actually lead to some interesting enemies in core DDA as well.

I suspect if I could get the DDotD feel working right, I'd be sufficiently excited to start working on a special storyline pack for it.

**Comment by Giagantic** [comment]
Make a Zombie like the best Romero Zombie:

![returnofthelivingdeadbanner-e1544038523966](https://user-images.githubusercontent.com/69474797/97644711-6f640180-1a21-11eb-87c3-3651d49adbba.jpg)

**Comment by I-am-Erk** [comment]
That's a russo zombie.

**Comment by dchieh222** [comment]
This could improve tactical options.

**Comment by I-am-Erk** [comment]
Weakpoints are better and already almost done.
