### ISSUE TITLE
[Magiclysm] Segfault on casting Spells

### ISSUE THREAD

**Issue by ThePotatomancer** [CleverRaven/Cataclysm-DDA#45144]
# Describe the bug

Casting some spells successfully crashes the game
Crashing spells tested: [Magic Missile, Bless, Fireball, Summon Zombie]
Non crashing spells tested: [Magical Light]
Tried with level 0 and level 1 spells,
And with 0, 10, 20 Spellcraft levels

# Steps To Reproduce

1. Learn bless.
2. Set Spellcraft to level 10 or just cast it till successful
4. Crash to desktop

# Expected behavior

Casting Bless, gaining buff and earning spell exp.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 8
- Game Version: 0.E-7242-gb71918d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm]
]

# Additional context

logs:
[logs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5460846/logs.zip)

Save: 
[crashyBoy.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5460887/crashyBoy.zip)

Either cast Bless or cast Magic Missile on Breather

**Comment by hexagonrecursion** [comment]
Could not reproduce
- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 0.F-2004-gada3852d39 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm]
]
