### ISSUE TITLE
S_lot crashes game

### ISSUE THREAD

**Issue by Theawesomeboophis** [CleverRaven/Cataclysm-DDA#45146]
Summary: S_lot spawning in world causes memory error and game crashes.

 When S_lot spawns in world it says invalid mapgen location and crashes due to memory error, worlds where s_lot doesn't generate don't do this and start normally.
This is my first issue, if I did something incorrectly feel free to notify me.

1. Start new save.
2. Create character
3. Start game
4. If s_lot generates, it will crash game, S_lot usually spawns on 4th save, which crashes game

# Expected behavior
 World load normally with S_lot

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5461053/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5461054/debug.log)
[Boophis' World.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5461108/Johnathan.s.World.zip)

**Comment by Night-Pryanik** [comment]
Which version you are on? This issue should be fixed in latest experimentals.

**Comment by Theawesomeboophis** [comment]
I am on latest experimental. Here are specs:
Windows 8.1
8GB Ram
161GB hard drive space

**Comment by Theawesomeboophis** [comment]
This bug started about 3 days ago, and I don't know which update caused it.

**Comment by Theawesomeboophis** [comment]
It states a memory error has occurred and CTDs.

**Comment by Theawesomeboophis** [comment]
0.E-7220-ge5383cc (tiles) here is actual name of version in case it is needed.

**Comment by Theawesomeboophis** [comment]
It says Invalid Overmap Id S_Lot and the problem is on Line 433

**Comment by Night-Pryanik** [comment]
Could you please provide a list of mods you're using?

**Comment by ZhilkinSerg** [comment]
It is a third party mod issue.

```15:29:06.486 ERROR : src/overmap.cpp:963 [void overmap_special::check() const] In overmap special "Camp Ground Small", terrain "s_lot" is invalid.```

```0.E-7220-ge5383cc```

```
[
  "dda",
  "blazeindustries",
  "crt_expansion",
  "magiclysm",
  "DinoMod",
  "Graphical_Overmap",
  "Graphical_Overmap_Magiclysm",
  "sees_player_hitbutton",
  "sees_player_retro",
  "my_sweet_cataclysm",
  "crazy_cataclysm",
  "aftershock",
  "secronom",
  "Arcana",
  "vamp_stuff",
  "vamp_stuff+arcana",
  "Medieval_Mod_Reborn",
  "MMA",
  "PK_REBALANCE",
  "Cata++",
  "more_survivor_stuff",
  "fuji_mpp",
  "Bootleg_Walkers",
  "AftershockUDP",
  "ArcanaUDP",
  "BlazeIndustriesUDP",
  "crt_expansionUDP",
  "CrazyCataclysmUDP",
  "DinoModUDP",
  "MagiclysmUDP",
  "My_Sweet_CataclysmUDP",
  "MMAUDP",
  "PK_REBALANCE_UDP",
  "secronom_UDP",
  "zets_hair_extensions_undead",
  "Cata++UDP",
  "Arts' Guns",
  "Dorf_Life",
  "Dorf_LifeUDP",
  "fallout",
  "Fallout_CDDA_UDP",
  "Arts' GunsUDP",
  "WHALEYHAIR_UDP",
  "collectablemod",
  "BL9_100monres"
]
```

**Comment by ZhilkinSerg** [comment]
Search for overmap special with name "Camp Ground Small" in your mods and replace any occurrences of "s_lot" with "s_lot_north" there.

**Comment by Theawesomeboophis** [comment]
> It is a third party mod issue.
> 
> `15:29:06.486 ERROR : src/overmap.cpp:963 [void overmap_special::check() const] In overmap special "Camp Ground Small", terrain "s_lot" is invalid.`
> 
> `0.E-7220-ge5383cc`
> 
> ```
> [
>   "dda",
>   "blazeindustries",
>   "crt_expansion",
>   "magiclysm",
>   "DinoMod",
>   "Graphical_Overmap",
>   "Graphical_Overmap_Magiclysm",
>   "sees_player_hitbutton",
>   "sees_player_retro",
>   "my_sweet_cataclysm",
>   "crazy_cataclysm",
>   "aftershock",
>   "secronom",
>   "Arcana",
>   "vamp_stuff",
>   "vamp_stuff+arcana",
>   "Medieval_Mod_Reborn",
>   "MMA",
>   "PK_REBALANCE",
>   "Cata++",
>   "more_survivor_stuff",
>   "fuji_mpp",
>   "Bootleg_Walkers",
>   "AftershockUDP",
>   "ArcanaUDP",
>   "BlazeIndustriesUDP",
>   "crt_expansionUDP",
>   "CrazyCataclysmUDP",
>   "DinoModUDP",
>   "MagiclysmUDP",
>   "My_Sweet_CataclysmUDP",
>   "MMAUDP",
>   "PK_REBALANCE_UDP",
>   "secronom_UDP",
>   "zets_hair_extensions_undead",
>   "Cata++UDP",
>   "Arts' Guns",
>   "Dorf_Life",
>   "Dorf_LifeUDP",
>   "fallout",
>   "Fallout_CDDA_UDP",
>   "Arts' GunsUDP",
>   "WHALEYHAIR_UDP",
>   "collectablemod",
>   "BL9_100monres"
> ]
> ```

Which mod is it caused by?

**Comment by ZhilkinSerg** [comment]
Whichever introduced "Camp Ground Small" overmap special. Try searching in mods folder for this text.

**Comment by Theawesomeboophis** [comment]
Ok

**Comment by Theawesomeboophis** [comment]
Should I Submit this to Goat God, because that is where the mods come from.

**Comment by Night-Pryanik** [comment]
I think Goat God will appreciate it if you inform him.

**Comment by Theawesomeboophis** [comment]
Thanks for replying, will do.
