### ISSUE TITLE
moth mutagen

### ISSUE THREAD

**Issue by chad-code** [CleverRaven/Cataclysm-DDA#45141]
you can find it in labs and you can make it with cotton. you get b mood buffs for being in light and a mood debuff if your not in the light. you have  setae on your body and even more on your neck and you can eat clothes with cotton in them. and you have wings that spook things. also extra joy from sweet stuff and alcohols like beer.
could be like the insect tree

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
