### ISSUE TITLE
Hub Mercenary Mission "Retrieve chunks of gold" prevents "Active Noise Control" from completing

### ISSUE THREAD

**Issue by Noodleboom** [CleverRaven/Cataclysm-DDA#45140]
# Describe the bug

After clearing the radio tower for the Hub Mercenary mission "Activate Noise Control," the linked mission to return to Hub 01 is being generated correctly. However, after returning, the NPC is only asking about the concurrent "Retrieve chunks of gold" mission before going to the active dialogue for Noise Control. This makes it impossible to complete the Noise Control mission without first resolving an open Retrieve Gold mission.

I spawned in enough gold to complete the Retrieve Gold Mission, which allowed the completion dialogue for Noise Control to appear.

# Steps To Reproduce

1. Accept the "Retrieve chunks of gold" mission from the Hub Mercenary NPC
2. Accept the "Active Noise Control" mission from the Hub Mercenary NPC
3. Complete the "Active Noise Control" mission
4. Return to the Hub 01 tile indicated in the "Active Noise Control" mission
5. Talk to the NPC

# Expected behavior

Ideally, the NPC will handle two ongoing quests better. Some behavior that would make sense:

- Pausing the ongoing/recurring quest (retrieve gold) while the one-and-done (noise control) is ongoing
- Recognize that there are two quests and cycle through

# Screenshots

![image](https://user-images.githubusercontent.com/28692644/97601673-0a33f000-19d0-11eb-8512-2fdfe3f86256.png)
The missions screen after returning to Hub 01 with the mercenary. Note that we're in the target map tile.

![image](https://user-images.githubusercontent.com/28692644/97601707-13bd5800-19d0-11eb-9cd4-707ad957fdfa.png)
Talking to the NPC first prompts the gold retrieval prompt...

![image](https://user-images.githubusercontent.com/28692644/97601793-2cc60900-19d0-11eb-970c-13f85b4eb338.png)
...before returning to the dialogue for an active Noise Control mission.

![image](https://user-images.githubusercontent.com/28692644/97602145-96deae00-19d0-11eb-9bb9-75acdca2ddb9.png)
Completing the gold mission...

![image](https://user-images.githubusercontent.com/28692644/97602236-afe75f00-19d0-11eb-8c9c-9b0f66f0e25f.png)
Allows for the completion dialogue for Noise Control.

# Versions and configuration

 - OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-7220-ge5383cc [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

May be related to #41226

**Comment by John-Candlebury** [comment]
Did you transfer your save from a previous version. I'm pretty certain that the way the mercenary dialogue is structured should prevent you from accepting both missions at the same time.

**Comment by SunshineDistillery** [comment]
Looks like merc_1_main has a reply with a condition where the 'and' should be an 'or'.

Fixing that won't deal with the underlying bug. Are there any other places where an npc offers multiple quests at once? There are talk topics for many missions, but I cant think where they're used.

**Comment by SunshineDistillery** [comment]
Looks like the merc and intercom are the only dialogs that use add_mission. It's not even in the npc doc. Everything else uses assign_mission and follow up missions to move through a linear queue. There are no complex branching mission paths yet where this bug would be seen.

**Comment by John-Candlebury** [comment]
Those are the only NPCs that can give you more than a mission at once. So it doesnt really surprise me that there are issues with that.

**Comment by SunshineDistillery** [comment]
It might work by changing the merc's response with talk_mission_inquire topic to talk_mission_list_assigned. Some of this stuff isn't migrated to jsons so it's hard for me to tell what's going on.

**Comment by Noodleboom** [comment]
> Did you transfer your save from a previous version? I'm pretty certain that the way the mercenary dialogue is structured should prevent you from accepting both missions at the same time.
> 
> If you managed to accept both missions at the same time, I would appreciate if you could share the dialogue steps you followed. So that I can correct it.

My save was transferred from a previous version, but I hadn't interacted with the mercenary NPC until the version indicated in this report.

Sorry, I don't have the exact dialogue steps. I've saved at a later point. My best recollection is:

- completing the gold mission the first time
- "do you have any jobs for me?"
- I accepted one, but I'm not sure if it was Noise Control or Gold Retrieval again. Sorry,
- "do you have anything else for me to do?"
- accepting the other mission

**Comment by Noodleboom** [comment]
> Looks like the merc and intercom are the only dialogs that use add_mission. It's not even in the npc doc. Everything else uses assign_mission and follow up missions to move through a linear queue. There are no complex branching mission paths yet where this bug would be seen.

Now that you mention it, I had a similar issue with the Intercom. I simultaneously accepted Iron Safari and Dead Man's Mind, but couldn't complete Dead Man's Mind until Iron Safari. Same issue as the Mercenary; it would only give the completion dialogue for Iron Safari until it was completed.

**Comment by John-Candlebury** [comment]
> Sorry, I don't have the exact dialogue steps. I've saved at a later point. My best recollection is:

I think those are good enough. I'll look into it this weekend.
