### ISSUE TITLE
Add Mod support to Ultica

### ISSUE THREAD

**Issue by Theawesomeboophis** [CleverRaven/Cataclysm-DDA#45147]
# Describe the solution you'd like
Ultica should add minor support for Mods, I will submit this to mod authors as well as I know Erk stated previously that he had no interest in adding mod tiles.

# Describe alternatives you've considered
Submitting this request to mod authors.

**Comment by DoctorGoat** [comment]
There's probably a way to use the UndeadPeople mod tiles since they're effectively xotto tiles, but my attempts with tweaking the json led nowhere.

**Comment by Theawesomeboophis** [comment]
Thanks for replying, I'm new to the repository and thought that I would submit some suggestions.

**Comment by ZhilkinSerg** [comment]
TIleset submissions go through https://github.com/I-am-Erk/CDDA-Tilesets

**Comment by Theawesomeboophis** [comment]
> TIleset submissions go through https://github.com/I-am-Erk/CDDA-Tilesets

Thank you, I will submit this request there.
