### ISSUE TITLE
Fire Heat Depends On Amount Of Fuel

### ISSUE THREAD

**Issue by Theawesomeboophis** [CleverRaven/Cataclysm-DDA#45149]
# Describe the solution you'd like
Campfire Heat Depends on the amount of Fuel just like in real life, the more fuel you add the longer it will last and the hotter it will be.

**Comment by Theawesomeboophis** [comment]
I don't know if this is already a feature, please notify me if it is and I'll close this.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
