### ISSUE TITLE
Expanding requirements to include optional tools and components 

### ISSUE THREAD

**Issue by dchieh222** [CleverRaven/Cataclysm-DDA#45157]
# Is your feature request related to a problem? Please describe.
Recipes are awkward insofar as they always have a set execution time, are indifferent to the quality of the tools used, and do not permit any optional components. The only way, for example, to use food processors to get faster flour is to create an additional recipe for flour with food processor. 

# Describe the solution you'd like
Recipes should permit consumption of optional components if available(with additional prompt by user) as well as the appropriate optional tools.  The use of different tools may also impact the project in other ways, or the items used.

For example, a clothing project may use a sewing machine instead of hand sewing to save time. Using a specific item like "scissors" instead of generic cutting 1 instrument will also save time and reduce failure rate.  On the component side, using a handcrafted wooden needle may increase rolls to damage the makeshift needle.  Having the correct books with patterns should also save time.

Likewise, using additional multiple components for a deluxe egg dish of seasoning, meat jerky and mushrooms should give you a better dish.   This also permits the creation of more calorie dense food such as adding animal fats to meat stews, and thus reducing the "oil drinking meta."

# Describe alternatives you've considered
Sewing machine with charges, and doubled recipes for hand-sewing versus machine-sewing. This is viable but unwieldly.

# Additional context
Spun off speculation originating from #24180.  Related to ongoing mentions of powered sewing machines in Tailoring Overhaul project. May interact with food and item quality levels as indicated in #44740 &  #35533.

**Comment by ZhilkinSerg** [comment]
That's a lot (a gigafuckton actually) of work, so the earlier you start working on it - the sooner it hits the players.

**Comment by jbytheway** [comment]
See also #42556.
