### ISSUE TITLE
Magiclysm: Ogres and Orcs, The green beasts

### ISSUE THREAD

**Issue by Theawesomeboophis** [CleverRaven/Cataclysm-DDA#45169]
# Describe the solution you'd like
Add Orcs and Ogres to Magiclysm.

# Describe alternatives you've considered
Not doing this.

**Comment by KorGgenT** [comment]
the reason they're not in right now is that noone has written them yet, and i'm not really exactly the champion of json content additions. so please, make new monsters and locations. it will make for a larger and more complete mod.

**Comment by Theawesomeboophis** [comment]
I'm making it, should I make orcs and ogres their own factions?

**Comment by Theawesomeboophis** [comment]
And also should I make them unique weapons or is their preexisting weapons that would fit these monsters?

**Comment by Xpyder** [comment]
That's probably up to you, thought I'd double check with the mod author to make sure your lore integration is consistent.

I would guess Ogres would be solitary (or 2-4 member pack) and Orcs would be gregarious (communal) if you're going with newer lore, or solitary if you're going with older ones.

If you get really into it you might make variants, maybe smaller ogres that move in packs, or a mountain ogre which is closer to a giant, maybe a couple orc factions with different item preferences that are hostile between each other (I'm envisioning a copy paste job with some adjustments in description and items between them to expand flavor for less effort)

**Comment by Xpyder** [comment]
And if you want to lean on past works, some of Pathfinder (specifically the [PRD](https://legacy.aonprd.com/updates.html)) is public domain has it's roots in D&D.  Probably don't want to copy verbatim, add some CDDA and Magiclysm flavor but it's probably a good place to get ideas

Keep in mind not all of Pathfinder is public domain.  Be cautious of anything you find outside of the PRD to make sure it's not copywritten.  (sometimes you can look for an [OGL](https://en.wikipedia.org/wiki/Open_Game_License) to tell what you can take)

**Comment by Theawesomeboophis** [comment]
its not working properly, I'll send text.
  "default_faction": " orcs"
 "hp": 82,
  "color": "green",
the : symbol is red in these three lines.

**Comment by Xpyder** [comment]
is it json?

**Comment by Theawesomeboophis** [comment]
Yes.

**Comment by Xpyder** [comment]
give me a sec

**Comment by Theawesomeboophis** [comment]
I put .json at the end of the file name.

**Comment by Xpyder** [comment]
sorry, where can I find the code you're working on?

**Comment by Theawesomeboophis** [comment]
Do you need link to fork?

**Comment by Xpyder** [comment]
I see a couple listed under your profile but not sure which one and which file

**Comment by Theawesomeboophis** [comment]
https://github.com/Theawesomeboophis/Cataclysm-DDA-Boophis
its in Cataclysm-DDA-Boophis/data/mods/Magiclysm/monsters/

**Comment by Xpyder** [comment]
ok, looking

**Comment by Theawesomeboophis** [comment]
This will be default fork for all of my commits btw.

**Comment by Theawesomeboophis** [comment]
Also, how do I open an issue tab, so that way I can fix problems with the fork.

**Comment by Xpyder** [comment]
> Also, how do I open an issue tab, so that way I can fix problems with the fork.

Not sure, I'm not deeply familiar with github atm I just muddle through

**Comment by Xpyder** [comment]
I think this might have an answer: https://stackoverflow.com/questions/29692626/why-is-issues-tab-not-present-in-my-repos-github-page

You have to enable the Issues first. You can do that by clicking to Settings and enable the Issues section. Then you can use it. [screenshot on the URL page]

**Comment by Theawesomeboophis** [comment]
Activated Issues and gave you access to the fork.

**Comment by Theawesomeboophis** [comment]
Still working on this.

**Comment by actual-nh** [comment]
Still working on - hopefully close to finishing.
