### ISSUE TITLE
After death body-glitch

### ISSUE THREAD

**Issue by Krwak** [CleverRaven/Cataclysm-DDA#45160]
# Describe the bug

https://discordapp.com/channels/699895400253095956/699896121027461137/771669742306066462
When character dies and game asks whether to show last moments of life, choosing 'no' and hitting alt+f4 right after that, will save the game and quit. Save will remain there though and it's possible to load the game again, char alive but with the dead twin under the feet.
This basically duplicates all items and leaves the char on the brink of death.

# Steps To Reproduce

1. Create a new char in a new world.
2. In options have Deathcam set to 'ask'.
3. Spawn a jug of ammonia or other poisonous substance that will kill your char....
4. Get killed by drinking ammonia
5. On the prompt to watch the last moments choose no and hit alt+f4 right after.
6. Game will save and then quit.
7. Start the game again and load your save
8. Watch your char's dead twin under the feet.

# Expected behavior

You shouldn't be able to load the save after a death of character and certainly not find a dead twin.

# Screenshots

![image](https://user-images.githubusercontent.com/72284934/97693176-0fad3b00-1aa1-11eb-8b73-16414f266e2f.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-7232-gee0a92c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

**Comment by Zireael07** [comment]
One: did you search? That was reported already fairly recently, and closed as the devs think you are not supposed to alt-f4 at the tombstone.

**Comment by Krwak** [comment]
Sorry, didn't notice a previous bug report about this. If that's the verdict then i can close it as well.
