### ISSUE TITLE
Dinomod: Obscure Dinos

### ISSUE THREAD

**Issue by Theawesomeboophis** [CleverRaven/Cataclysm-DDA#45162]
There are many dinosaurs that I think would be cool to see in Dinomod
# Describe the solution you'd like
Add More Obscure dinosaurs such as:
Qianzhousaurus
Nothronychus
Kosmoceratops
Amargasaurus
Bonus Prehistoric Creature: Triadobatrachus( Giant Prehistoric Frog and the first modern frog, just seemed to fit Dinomod)

# Describe alternatives you've considered
Not doing this.

**Comment by Theawesomeboophis** [comment]
The frog is from late Triassic, but it isn't a dinosaur, so I see why you don't want that one, thanks for replying and giving feedback.

**Comment by Drafting-Goblin** [comment]
I'm fairly new to contributing to CDDA, but I would be interested in trying to add one of these to the mod.

**Comment by Theawesomeboophis** [comment]
I'm considering creating a mod with non-dino Prehistoric creatures, the frog would probably fit that better( if I finish it).

**Comment by LyleSY** [comment]
@Drafting-Goblin check out https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/mods/DinoMod/DESIGN.md
I made that as clear as I could but I'm neck deep in this stuff so any feedback is helpful. I also try to check in on the various modding Discords on there if you have questions

**Comment by Theawesomeboophis** [comment]
Is there a monster creation template somewhere, because actually programming the monsters correctly is what I have trouble with.

**Comment by LyleSY** [comment]
The doc is here https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/MONSTERS.md .  That has some example code but I find I learn the most by grabbing pieces from https://github.com/CleverRaven/Cataclysm-DDA/tree/master/data/json/monsters

**Comment by Drafting-Goblin** [comment]
Thanks! I appreciated the help and I will definitely start there.

**Comment by Theawesomeboophis** [comment]
Thanks, I'll read it and try to get it to work properly.

**Comment by Theawesomeboophis** [comment]
Qianzhousaurus is broken, please tell me how I can fix these lines.
"symbol": "D",
"volume": "5000 ml",
},
The : symbol is red and I want to know how to fix it for future reference.

**Comment by Theawesomeboophis** [comment]
Fork is Theawesomeboophis
/
Cataclysm-DDA-Boophis

**Comment by LyleSY** [comment]
@Theawesomeboophis i know that error. You’re using a common text editing app instead of a JSON editor. JSON is really picky about that. There are a few good options depending on what platform you use, I just use a Chrome plugin

**Comment by Theawesomeboophis** [comment]
Thanks, I'll find a Json editor and try again.

**Comment by Drafting-Goblin** [comment]
Notepad++ is pretty good in my experience, and it's free.

**Comment by Theawesomeboophis** [comment]
Thanks, do you have link for Notepad++?

**Comment by Drafting-Goblin** [comment]
https://notepad-plus-plus.org/downloads/

**Comment by Theawesomeboophis** [comment]
Thanks. I downloaded it.

**Comment by Theawesomeboophis** [comment]
I lowered weight and volume to be more appropriate.
