### ISSUE TITLE
Bottom of Mine Scenario

### ISSUE THREAD

**Issue by DEADPUNKNTRL** [CleverRaven/Cataclysm-DDA#45174]
I'm not doing your template. It's simple, it says that it's incapable of generating a valid starting point for Bottom of a Mine [sloc_mine_finale] in a radius of 3 overmaps. I tested to see if because of updates my world was just fucked, and made a new world to test it again. I did the same thing, minus the addition to stats, traits, and any character information (blood type, height, etc.), and it didn't work once again.

The mods I was using for each world 👍 
![urmom](https://user-images.githubusercontent.com/73724968/97766073-e01f2280-1ae2-11eb-8b6d-aff84b8de09d.png)

**Comment by DEADPUNKNTRL** [comment]
was due to graphical overmap being on mod list.

**Comment by Theawesomeboophis** [comment]
So its an issue with graphical overmap, you should mention this to devs so they can fix mod instead of trying to fix base.
