### ISSUE TITLE
Unable to fill partially full vehicle tanks

### ISSUE THREAD

**Issue by Dullahan3579** [CleverRaven/Cataclysm-DDA#45191]
# Describe the bug

Trying to fill a 60L vehicle tank with gasoline when tank is partially filled  throws an error.

# Steps To Reproduce

1. Find a vehicle with a partially filled tank.
2. Attempt to fill the partially filled tank.
3. Observe error. 

# Expected behavior

Filling a partially filled tank should increase the amount of liquid in the tank.  

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-7240-gb165e21 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English UK]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations]
]

# Additional context
The bug occurs  when trying to fill from a jerrycan or a gasoline pump.
None of the liquid amounts change.
Emptying the tank and then filling does not return an error.
I've included my save with my vehicle with a partially filled next to a gasoline pump.
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5470049/save.zip)

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5470046/debug.log)

**Comment by wapcaplet** [comment]
Confirmed in a new game:

- Get a container of gasoline (debug spawn gasoline will appear in a jerrycan)
- Find a vehicle with a gasoline tank, and `E`xamine it
- Select the gasolink tank and `f`ill it from the container

After pressing enter to select the container, the "interacting with vehicle, press 5 to cancel" popup may be shown for a moment, before this error occurs:

```
 DEBUG    : tried to put an item (gasoline) in a container (metal_tank) that cannot contain it

 FUNCTION : int item::fill_with(const item &, const int)
 FILE     : src/item.cpp
 LINE     : 8701
```

This is the same error I see at the end of your debug.log.

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-7257-ged747025b8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by mqrause** [comment]
Gasoline in a vehicle has no flags while gasoline spawned from the debug menu has the `NO_REPAIR` flag and gasoline from a pump has the `DIRTY` flag. That is preventing them from being combined. No idea where those flags come from, though.

**Comment by Zireael07** [comment]
Wasn't there a PR that was supposed to fix the gasoline in pump being DIRTY, though?

**Comment by mqrause** [comment]
Oh yeah, it works with gas pumps in a new world. Maybe the fix doesn't work for already existing pumps and the provided save came from an older version?

**Comment by BrettDong** [comment]
Cannot reproduce on latest `master` branch (`0.E-8660-gb9ce7b4d8a`). I created a new world, spawned a gas station, bought a gallon jug of gasoline on gas pumps, refilled to a car and no problem occurred.
