### ISSUE TITLE
Batons can be extended while stored (should not)

### ISSUE THREAD

**Issue by Xindage** [CleverRaven/Cataclysm-DDA#45200]
# Describe the bug
While you have a bag (eg: MOLLE pack) you cant store a baton (eg: PR-24 baton/expendable baton) if it's extended, so you can retract it to be able to store it on the said pack, but while stored you can expand it again without having to drop it, keeping it extended inside the bag, but you cant store it while extended.

# Steps To Reproduce
1. Have a molle pack and a baton.
2. Notice that you cant store it while extended.
3. Retract and store it on the molle pack.
4. Use the active menu to extend the baton. 

# Expected behavior
Prompt the player to choose to drop it or wield it, since it cannot fit in the molle pack anymore.

# Screenshots
![image](https://user-images.githubusercontent.com/6380147/97809768-c2ba9780-1c4d-11eb-807a-27f65cd953d5.png)

# Versions and configuration
- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.1 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-7239-gf5bd4da [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [Dark Days Ahead [dda],Disable NPC Needs [no_npc_food],Bionic Professions [package_bionic_professions],Stats Through Skills [StatsThroughSkills]]

**Comment by Night-Pryanik** [comment]
This should be closed by #45873.
