### ISSUE TITLE
Segmented encumbrance discussion

### ISSUE THREAD

**Issue by kholat** [CleverRaven/Cataclysm-DDA#45206]
# Is your feature request related to a problem? Please describe.

When the change was made that clothing can have different encumbrance on different body parts, most of them stayed the same except masks/full face helms.
 Does it always make sense that say a trenchcoat or a suit should also add arm encumbrance as it gets full in other words, I dont think many clothing items actually have arm pockets IRL, for instance lets consider 2 items in game the trenchcoat and the duster, they both have the same encumbrance (7 to 15), they both have the same volume of storage (6l), however one does cover the legs while the other doesnt; does that one have pockets on arms and torso to have the same volume? But why does it have the same encumbrance then; furthermore the sleeveless versions have no arms therefore no arm encumbrance, yet the same litreage for storage. 

# Describe the solution you'd like

I am talking about changing lots of clothing items to not have scaling encumbrance on parts that do not make sense.
If devs say this is alright, I will make a PR after my currently public PRs get reviewed.

# Describe alternatives you've considered

Ideas from comments to this issue.

# Additional context

Me saying "removing scaling encumbrance on parts that do not make sense" might need more thought, because for instance a duster and trenchcoat make sense to not have scaling arm encumbrance, but hand crafted gear such as survivor, scavenger, nomad etc might actually have arm pockets due to the nature of the items idea 'to give maximum storage' so that probably needs discussion.

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
