### ISSUE TITLE
Unfolding foldable bike duplicates it

### ISSUE THREAD

**Issue by quasar101** [CleverRaven/Cataclysm-DDA#45207]
# Describe the bug

Unfolding foldable bike unfolds and duplicates it leaving folded one laying on the ground. 
Bike schematics: 
3 tiles, 3 light foldable frames, a foldable shopping cart above each wheel (2 total).
pedals, bike horn, bike generator, foldable seat in the middle tile

English in the name of the bike causes same error.

debug.log:
18:29:40.855 ERROR : src/character.cpp:2907 [item Character::i_rem(const item*)] did not found item <color_c_yellow>|\В </color>СЃР»РѕР¶РµРЅРЅС‹Р№ Р’РµР»РёРє to remove it!

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5476167/save.zip)
# Steps To Reproduce

Weld such a bike, fold, unfold

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-7242-gb71918d [64-bit]
- Graphics Version: Tiles
- Game Language: Р СѓСЃСЃРєРёР№ [ru]
- Mods loaded: [
    РўС‘РјРЅС‹Рµ Р”РЅРё Р’РїРµСЂРµРґРё [dda],
    РћС‚РєР»СЋС‡РёС‚СЊ РїРѕС‚СЂРµР±РЅРѕСЃС‚Рё Сѓ NPC [no_npc_food],
    РђР»СЊС‚РµСЂРЅР°С‚РёРІРЅС‹Рµ СЃРёРјРІРѕР»С‹ РєР°СЂС‚С‹ [alt_map_key],
    Р“СЂР°С„РёС‡РµСЃРєР°СЏ РєР°СЂС‚Р° [Graphical_Overmap],
    Р·РЅР°С‡РѕРє РІРёРґРёС‚-Р»Рё-РёРіСЂРѕРєР°, HitButton_iso [sees_player_hitbutton],
    Р·РЅР°С‡РѕРє РІРёРґРёС‚-Р»Рё-РёРіСЂРѕРєР°, retrodays [sees_player_retro]
]

**Comment by BrettDong** [comment]
Cannot reproduce this in latest experimental version. Folding and unfolding Велик works perfectly fine.
