### ISSUE TITLE
Grabbing and moving heavy furniture is not interrupted by monster sighting or attacks

### ISSUE THREAD

**Issue by ThePotatomancer** [CleverRaven/Cataclysm-DDA#45212]
# Describe the bug
When `G`rabbing a heavy object and trying to move it, it may take a long time (up to several minutes), but cannot be interrupted by a monster being sighted, getting too close, or attacking.

# Steps To Reproduce
1. Find a heavy yet movable object (first experienced it by moving crates in lumberyards).
2. Lure/Find/Spawn nearby zombies/hostiles.
3. `G`rab it.
4. Try to move it to adjacent tile - get insta-killed by nearby zombies.

# Expected behavior
Expected a similar prompt to when I do any other long-running activity like reading, crafting, or dropping a bunch of items - if a new monster is sighted, or gets too close, or begins attacking me, I should get a popup like The zombie is dangerously close! Stop moving object?

# Screenshots
Scenario:
![image](https://user-images.githubusercontent.com/52547005/97910943-2e3a5d00-1d53-11eb-8b51-c8e601b0e15f.png)
Aftermath of moving crate:
![image](https://user-images.githubusercontent.com/52547005/97911113-6fcb0800-1d53-11eb-8258-fe663c2d6dd0.png)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 8 version
- Game Version: 0.E-7242-gb71918d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
save file for easy reproduction: 
[HeavyDeadlyBoy.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5477600/HeavyDeadlyBoy.zip)

pretty much the same as #43475 but for dragging furniture (even shamelessly copied most of the issue). I assume the fix would be similar to #45009.

**Comment by Zireael07** [comment]
Dupe of #45010 (did you do a search?)

**Comment by ThePotatomancer** [comment]
Sorry, it's a dupe. Didn't see it in release blockers and forgot that search is a thing. I'm closing for now and will update #45010 tommorow with some of the new info here (mostly the save and screenshots)
