### ISSUE TITLE
Apartment Tower Bookshelves spawn too much.

### ISSUE THREAD

**Issue by Pyritefoolsgold** [CleverRaven/Cataclysm-DDA#45219]
# Describe the bug

Apartment Tower bookshelves have far too many books.

# Steps To Reproduce

1. Generate new maps until you find one with an apartment tower.
2. Go to the apartment tower and check the bookcases. 
3. Observe that a great many books spawn in the bookcases, with some spawning around 30 recreational books and others spawning multiple copies of various crafting books.

# Expected behavior

A similar number of books as what you find in the bookshelves in houses, usually 2-6 total books. As is, clearing out an apartment tower is basically a guarantee of getting every relevant book in the game.

# Screenshots

![Books](https://user-images.githubusercontent.com/9997796/97953534-a4d85a00-1d55-11eb-8324-f1aba94728ca.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-7242-gb71918d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

I like books, but it feels cheap for them to be this easy. I can find dramatically more books in an apartment tower than in a library or mansion, and it's rather easy to control the pace of zombie fights in an apartment tower. They're already a huge boon for food, but this bug makes it just too much. And from a realism point of view, if anything apartments should have fewer books than houses.

**Comment by Xaleth** [comment]
Well. Why not just... add more variety to books?

**Comment by Pyritefoolsgold** [comment]
Variety will also spawn sometimes. This is really just an issue of overspawning. Bookcases in houses never have this many.

**Comment by natsirt721** [comment]
I think the solution there is to add more books to more places, make the information contained in them more disparate, and make the ones that can really bootstrap your -cooking- food handling skill rare. None of those books can get you past level three (IIRC), although I haven't explored the high-tier food handling and the implications now that it has been split from chemistry. There are 17 books on that bookshelf, which seems like a perfectly reasonable number. It is a little odd that they are all cooking focused, but not unbelievable. I mean, I wouldn't consider myself a well rounded book owner but my tiny apartment has well over 30 books, about equally split between fiction and nonfiction. I think that the number seen there is perfectly reasonable, and that the item group there is preparing for the eventual dilution of book learning. People don't buy bookshelves to store one or two books, and expecting only one or two per shelf is unrealistic.

**Comment by anothersimulacrum** [comment]
I agree, we have too few books elsewhere.

**Comment by Xaleth** [comment]
It‘s ironic that it has more books than the largest library variant

**Comment by PaulBlay** [comment]
I just cleared out an apartment tower and a library in the same town. The tower had quite a few, it's true, but the great majority of the skill / recipe books I got were from the library.

**Comment by Xaleth** [comment]
bumping this because this is a broken aspect
