### ISSUE TITLE
Overtuned Frog Mother Enemy

### ISSUE THREAD

**Issue by Giagantic** [CleverRaven/Cataclysm-DDA#45222]
# Is your feature request related to a problem? Please describe.
Currently the Frog Mother added in #43183 is an enemy that is a bit overtuned in that it has an obscene amount of HP regeneration. Even if brought down to 1 hp it'd quickly regenerate back to full in a few short turns. To top things of it is seemingly immune to bleed and spawns tadpoles that spawn on top of you and can do a mini-grappler grab to prevent you from chasing it down and finishing it off. The only solace is the relatively low damage output but this isn't really saying much considering the sheer amount of disruptive quality that a single Frog Mother is capable of putting out. The regen is so insane that only something that is relatively powerful and full-auto has the ability to consistently deal with a Frog Mother, everything else is a roll of the dice and this is with 10's in all skills. 

In melee you will almost always run out of stamina and be heavily interfered with by the tadpoles and due to the counterattack system, will often fail to recover any stamina due to the infinite tadpoles. 

Even a 50. Cal only has a chance of killing a Frog Mother with 5 shots and that is if you get multiple criticals. By the time you reload the Frog Mother will typically be back to full HP. 

# Describe the solution you'd like
There are several ways of making the enemy fairer without removing it's abilities to disrupt.

Any one of the  following would make the Frog Mother a fairer but still disruptive enemy:
- Make bleed effect the Frog Mother's regen 
- Add a longer cooldown to the tadpole spawn
- Reduce the regen
- Make the grab of the tadpoles weaker and easier to break out of

# Additional context
Ring-a-ling @KorGgenT

**Comment by kevingranade** [comment]
None of the things you outlined are problems. The frog mother is a boss-tier enemy, and from your description, shes working as intended.

**Comment by MichaelMacha** [comment]
Respectfully, I'm having a hard time seeing how it's meant to be boss tier. It's a massive frog, after all. Is it tied to a quest by any chance?

I'm currently working with a character at 13 strength, with shotgun slugs, molotovs, and a naginata, and I cannot damage the thing. It literally heals faster than the molotov fire hurts it.

I love the idea, but even as a boss it should be surmountable. It went from "cool challenge" to "frustrating blockade" pretty quickly. It seems like the enemy is under ripe.

**Comment by kevingranade** [comment]
> a character at 13 strength, with shotgun slugs, molotovs, and a naginata,

This isn't much firepower at all.  The shotgun deals big bursts of damage, but at really wide intervals, the naginata is similar in that it hits fairly hard but it's pretty slow, and yea the molotovs should help, but we don't want them to be the one and only thing you need to take on any enemy.
