### ISSUE TITLE
[Magiclysm] Cannot reload from dimensional storage belt.

### ISSUE THREAD

**Issue by DeadLeaves** [CleverRaven/Cataclysm-DDA#45229]
# Describe the bug
Anything in the dimensional storage cannot be used to reload.

# Steps To Reproduce

1. Spawn dimensional tool belt.
2. Spawn flashlight + battery
3. Put battery in dimensional tool belt.
4. Try to reload the flashlight

# Expected behavior

The flashlight should grab the battery from the belt and reload.

# Versions and configuration
experimental 11128

**Comment by DoctorGoat** [comment]
It's not even magiclysm specific. I'm fairly sure I've had the wyrmskin armor from arcana do the same thing.

**Comment by LaVeyanFiend** [comment]
Confirmed by [a Devcord user](https://discordapp.com/channels/598523535169945603/642349261320880128/776692031560613898) with the same issue.

**Comment by DoctorGoat** [comment]
The entire inventory system has been replaced since then. I'd be shocked if it had still been an issue.
