### ISSUE TITLE
Pupating zombie crawler considered harmful with unsupported tileset (segmentation fault when nearby) 

### ISSUE THREAD

**Issue by arockperson** [CleverRaven/Cataclysm-DDA#45226]
# Describe the bug
Almost every time I am near a pupating zombie crawler, the game crashes with a segmentation fault. I'm pretty sure this is because the tileset doesn't have support for the explosion, since it doesn't crash in ASCII. 

# Steps To Reproduce

Using an old tileset, spawn a pupating zombie crawler, the one with #391 in the debug menu. Observe the crash when it tries to break free.

I just did this twice and it reliably crashes after moving around for a few seconds with the pupating crawler nearby.

# Expected behavior

The game doesn't crash when in the glorious presence of the pupating zombie crawler, even if the tileset doesn't have proper graphics for it.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-7242-gb71918d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
MESSAGE: SIGSEGV: Segmentation Fault

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5482425/crash.log)

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
