### ISSUE TITLE
Cutting up clothing in a cargo space results in the products ending up on the ground

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#45228]
# Describe the bug

# Steps To Reproduce
Load the attached save, cut up daypack, observe the products spawning under the vehicle to the right of you.

# Expected behavior
No phasing through the floor and subsequent destruction by moving wheels.

# Screenshots

# Versions and configuration
- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.E-7312-g97896c2bc9-dirty [64-bit]
- Graphics Version: Curses
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

# Additional context

[2020.06.30.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5483591/2020.06.30.zip)

**Comment by OliveChukar** [comment]
Tested in ver 0.E-9111-gd1e702b-dirty. In provided save cutting up items dropped products on the ground to the east and north east despite the player standing on a vehicle space that could hold the items. 

Tried a clean save with core content pack Dark Days Ahead [dda] only spawned a vehicle put cloth items in its trunk then stood on the trunk activated a tool and cut them up. Products ended up on the ground directly under me not in the trunk.
