### ISSUE TITLE
Mapgen - House spawns with non-working garage door

### ISSUE THREAD

**Issue by RydellV** [CleverRaven/Cataclysm-DDA#45233]
# Describe the bug
Found a house with a non-working garage door. Using the garage winch displays "You turn the handle...Nothing happens.". I asked in Discord and was told by Wist that it was because the house is made of adobe brick which does not support the winch functions. Wist requested a screenshot of the layout so they can track the issue down.

# Steps To Reproduce

Spawn a house with adobe brick and a garage. Attempt to open the garage and see that it fails.

# Expected behavior
Expected the garage door to work properly.

# Screenshots
![House](https://user-images.githubusercontent.com/15075317/98055939-a6188e00-1e0c-11eb-9371-241af129d1e0.PNG)
Here is a layout of the house. Please don't tell anyone how I live.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-7242-gb71918d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    Disable NPC Needs [no_npc_food],
    sees-player icon, retrodays [sees_player_retro],
    No Fungal Monsters [No_Fungi]
]

**Comment by Night-Pryanik** [comment]
Fixed by #45709.
