### ISSUE TITLE
Item duplication by standing in a window

### ISSUE THREAD

**Issue by AlexMooney** [CleverRaven/Cataclysm-DDA#45242]
# Describe the bug

By wielding something and standing in a window you can duplicate worn containers and their contents.

# Steps To Reproduce

1. Make a player with a backpack and something to wield.
2. Stand in an open window (presumably any terrain that can't contain objects).
3. Drop the backpack in an adjacent tile.
4. Attempt to wear the backpack.  This should prompt you to store/drop/wear the wielded object.
5. Repeatedly hit escape instead of choosing an option.
6. The backpack and all of the contents have been duplicated on the floor.

# Expected behavior

Don't duplicate things, sure, but also don't prompt to drop wielded objects when attempting to wear something.  I've become accustomed to just hitting escape to keep the object in my hands, which led to this bug.

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.1 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-7333-g63860a4305 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by RoyBerube** [comment]
```
DEBUG    : Tried removing item from object which did not contain it

 FUNCTION : remove_item
 FILE     : D:\Cataclysm Master\Cataclysm-DDA\src\visitable.cpp
 LINE     : 545
```
Item is both worn and dropped following these steps. 

Will look into it further over the next few days.

**Comment by utechenko-v** [comment]
I have item duplication bug, but without standing in window and pressing ESC. I'm taking saber in scabbard from shopping cart, then through few menus I wield saber, but shopping cart still has "saber in scabbard", so I have sabers duplicated.
Is it the same bug, or another?
Build number : #11150, Build version: 0.E-7424-gcbcf5fd
_(I can provide saves and more details if needed)_

**Comment by RoyBerube** [comment]
I think it is another bug, because it looks like a different sequence of events. 

I suggest you make a new issue and outline the steps to reproduce the bug, or just wait a few days until PR #45290 merges and see if it is fixed (not likely imo).
