### ISSUE TITLE
Burning items should set flammable liquids on fire while laying on the same tile as them.

### ISSUE THREAD

**Issue by Vaaankas** [CleverRaven/Cataclysm-DDA#45248]
Things like burning lighters, chemical flares etc. do not ignite napalm or gas while being dropped on them. I was told the lit cigar does that using the LITSIG flag, so why not add it to other things?

**Comment by XygenSS** [comment]
Although LITCIG flag does make an item set things on fire when dropped, it also turns it into a smokeable item (like a cigarette). It is also not intended to be tacked onto any item, as the flag is "...not assigned in JSON by content contributors, they are set programatically." (JSON_FLAGS.md) 

We'd need a seperate flag with setting fire part but without the smoking part.

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
