### ISSUE TITLE
Tutorial notification at based game.

### ISSUE THREAD

**Issue by AnonimusC** [CleverRaven/Cataclysm-DDA#45244]
When you are about to exit from a tutorial there is only one 
exit option - exit with saving, and there a warning pops up 
(do not load the tutorial world, it will start to operate the 
game mechanics of the normal game world and everything 
can start to dance upside down and so on); this warning does
 not disappear when you then enter the normal world and 
then try to exit. The game thinks that we are still in training, 
or, moreover, it thinks that we are in training and imposes 
some restrictions of tutorial. game version is 0.E-2

**Comment by Aivean** [comment]
I did the following sequence:
1. Loaded tutorial
2. Saved and exited tutorial (warning showed up)
3. Loaded normal game
4. Saved and exited normal game (warning didn't show)

Can't reproduce for now.

**Comment by Aivean** [comment]
Quoting Kevin:
> We don't do backporting this close to the stable release.
