### ISSUE TITLE
Robots use special attacks on you when switching from combat mode to passive mode

### ISSUE THREAD

**Issue by Fosheze** [CleverRaven/Cataclysm-DDA#45254]
**Update:**
I'm going to leave the previous issue text as is because it is still the best way to demonstrate the issue. I did some further testing and found that this problem applies to all hackable bots and that while those bots won't directly attack you they will still use special attacks on you such as the Sentinels punting you or a skitterbot trying to shock you. The period of time that they are allowed to use their special attacks on you is the time it takes to activate the control device. I discovered this by nesting bodybags and putting the executive smartphone in the innermost body bag to pump up the access time to a ridiculous degree. During the entire time the character was accessing the smartphone they were being shocked by a "tame" skitterbot. The problem is just most prevalent with the sentinels because they can use their special attacks so rapidly.

# Describe the bug

When switching the Wraitheon Sentinel-lx from combat mode to passive mode using the executive smartphone (will test with control laptop later) it will first turn hostile for a moment before it actually turns passive. Considering that they stand directly next to you while in combat mode this usually means that your fragile imperceptive healer executive gets absolutely launched by one of them before they switch to passive mode.

# Steps To Reproduce

1. Start new game as Wraitheon Executive.
2. Stand adjacent to Wraitheon Sentinel-lx.
3. Use executive smartphone to toggle all following robots to passive mode.
4. Observe as Wraitheon Sentinel gets tired of bodyguarding you and yeets you away.

# Expected behavior

For my high end robotic bodyguards to not punch me in the face.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-7347-g20d1078 [64-bit]
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: Mods loaded: [
Dark Days Ahead [dda], 
Disable NPC Needs [no_npc_food], 
Aftershock [aftershock],
Aftershock - UndeadPeople Tileset [AftershockUDP]
]

# Additional context

-This problem may or may not apply to other bots as well. I did not get a chance to test that this morning but I will tonight. 

-I have a similar list of strangeness I noticed with these and other bots here https://github.com/CleverRaven/Cataclysm-DDA/issues/45227#issue-735512495 but I figured this deserved it's own issue because it seems like an actual bug.

**Comment by Maleclypse** [comment]
As a mostly json person I have no idea what would cause this but it is funny.

**Comment by Xenomorph-III** [comment]
Your character's bots got tired of their crap.  Alternatively... is a robot uprising canon in aftershock?

**Comment by ektoplazm** [comment]
I don't know whether it's related but I had the same issue with standard crow turrets half a year ago.

**Comment by Fosheze** [comment]
> I don't know whether it's related but I had the same issue with standard crow turrets half a year ago.

It likely is the same issue. I had planned to test it last night but I have the memory of a goldfish. I'll check it out tonight.

**Comment by Fosheze** [comment]
So I'm a rookie when it comes to github but I did find the chunk of code that switches the robots to passive. and at least to me everything there looks good.

https://github.com/CleverRaven/Cataclysm-DDA/blob/71e5516bc4fb58a2a704a3fbd05b733dd74db5ff/src/iuse.cpp#L6079-L6113

And here is the code I found for docile in monster attitude.

https://github.com/CleverRaven/Cataclysm-DDA/blob/20d1078faeb20662134239137571a6621102d864/src/monster.cpp#L1052-L1061

I can't make much out of monster.ccp but from what little I can tell, a monster when set to docile is no longer friendly rather it is switched over to passive. I'm guessing that somewhere somehow there is a turn passing where the monster was switched off friendly but not yet switched to passive so it becomes hostile.

**Comment by Fosheze** [comment]
Edited the main post with an update. The issue is even stranger than I thought.

**Comment by linonetwo** [comment]
I can confirm this, today sentinel-lx hits me.

**Comment by John-Candlebury** [comment]
Cant reproduce this anymore. Let me know if theres some other way to trigger this
