### ISSUE TITLE
Character hunger is never "Hungry", only "Very Hungry"

### ISSUE THREAD

**Issue by natsirt721** [CleverRaven/Cataclysm-DDA#45257]
# Describe the bug
Character is never hungry - hunger status goes from Nothing to Very Hungry, skipping Hungry along the way

# Steps To Reproduce
I'll admit I don't have a definite repro case, but my last few characters have been exhibiting this. See screenshot attached for character settings. I took note of the timing after eating breakfast and working on crafting a leather wallet.

0945 - Ate chili con carne and clam chowder, hunger level was "Satisfied"
1005 - Hunger level to Normal (blank)
1245 - Hunger level to Very Hungry

Weariness level was Lightly Weary at 1245, after starting the day without weariness.

# Expected behavior
My character gets Hungry before getting Very Hungry

# Screenshots
Character Sheet
![image](https://user-images.githubusercontent.com/6325435/98292068-15f85700-1f7a-11eb-94be-41062667b011.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-7200-gfc2388e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Beta National Guard Camp [national_guard_camp],
    More City Locations [cityside],
    More Locations [more_locations]
]

# Additional context
I have been running myself to weariness every day, so that may have something to do with it. I was under the impression that hungriness was affected by stomach contents so it seems odd that I was consistently skipping Hungry each time.

E: definitely possible that this is related to Light Eater

**Comment by GGgatherer** [comment]
"hungry" means you're overweight and want to eat
"very hungry" means you're *not* overweight and want to eat

Does it make sense? Kinda. Is it possible to guess WTF is happening with hunger state if you don't know it already? Absolutely not.

**Comment by natsirt721** [comment]
Ok, I have played a lot of cata on and off since 0.5, and as long as I can recall I got "hungry" before "very hungry". If this is the new way of the world then I guess I'll have to change with the times. 
That said, it is very confusing though to change that up - I don't think I would have ever made that association without someone explaining it, and the in-game help certainly was of no use in this case. Do we know why the decision was made to remove the "hungry" status for people of normal weight?

**Comment by Fosheze** [comment]
> Ok, I have played a lot of cata on and off since 0.5, and as long as I can recall I got "hungry" before "very hungry". If this is the new way of the world then I guess I'll have to change with the times.
> That said, it is very confusing though to change that up - I don't think I would have ever made that association without someone explaining it, and the in-game help certainly was of no use in this case. Do we know why the decision was made to remove the "hungry" status for people of normal weight?

I can't remember the entire discussion right now but this was implemented when the stomach contents system was implemented. There were a lot of discussions on the topic of wording for this as the phrasing for hunger after that got really confusing and this is just what we have for now. It is far from perfect but it works better than it did at the time. Essentially the way is is now is that when your stomach is empty it will cause the hungry or very hungry status depending on weather you are overweight or not respectively. Hungry/Very Hungry has no relation to actual caloric intake anymore (this part was deliberate), it only reflects the physical volume of food consumed. The whole point was to obfuscate hunger to make it more realistic. Realistically you don't intrinsically know how many calories you ate or **exactly** how much you could eat. The problem being that it's really hard to describe different hunger feelings in a sufficiently descriptive but still concise way.

This all definitely needs to be explained better and could use better wording but last time I saw a discussion on this no-one could figure out how to show the hunger status in a more clear matter and still be concise enough to show in the sidebar. I'm also not sure how often the help information is actually updated.

**Comment by natsirt721** [comment]
I guess the question is, why bother changing the wording based on whether or not you're overweight? The implication there is that being overweight causes you to feel less hungry then someone of normal weight for a given amount of stomach volume? Why not just "hungry" regardless of weight?

**Comment by wapcaplet** [comment]
I agree it is very strange for the "overweight" threshold to influence the hunger status in this way, and for the "Hungry" state to simply be skipped over; I am quite surprised to learn that it is this way by design. There is more info and discussion on #41889.
