### ISSUE TITLE
Sleep for animals/monsters

### ISSUE THREAD

**Issue by RelMayers** [CleverRaven/Cataclysm-DDA#45258]
Every creature in game doesn't seem to have sleep at all, seems unrealistic. 

# Describe the solution you'd like
Rather than creatures being active all time have some of them go into "sleep" mode that after some trigger like sound/smell

# Describe alternatives you've considered
Have them lowered activity instead. 

# Additional context
It should add additional realism to game as right example of cows walking around house all night seems ridiculous.

**Comment by Fallout48** [comment]
I think this would probably cover this.
https://github.com/CleverRaven/Cataclysm-DDA/issues/36832

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
