### ISSUE TITLE
Blackpowder fouling does not damage guns

### ISSUE THREAD

**Issue by Hirmuolio** [CleverRaven/Cataclysm-DDA#45263]
# Describe the bug

Guns with Blackpowder fouling fault should get damaged over time. 
They never take damage.

# Steps To Reproduce

Fire blakpowder ammo from gun not designed for that.
Wait.
Observe no damage.

# Expected behavior

There should be damage.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-7357-g86a33ce [64-bit]
- Graphics Version: Tiles
- Game Language: Deutsch [de]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Monsters [Only_Wildlife]
]

# Additional context

To make the damage apply there needs to be `it->faults.count( fault_gun_blackpowder )` added into `item::needs_processing()`.

But doing that will cause guns to take massive damage from blackpowder fouling. A |\ gun can go to XX in less than hour. 
The gun takes 1000 damage every time the fault is triggered (1/2000 chance per turn).
So the amount of damage that this fault causes needs to be balanced too.

**Comment by hexagonrecursion** [comment]
Confirmed. I fired 30 5.56 NATO, black powder from an M16 auto rifle and then waited for one day. It did not rust

**Comment by kholat** [comment]
I have a save rn in 610e7d5 (tiles) and my gun just rusted in about 1.5 hours 2 times out of 2.

Website wont allow me to upload the zipped save.

https://mega.nz/file/Q6hASYbJ#gW_sJruPMYuMfF9OfnuX0Vjhn17zkS6aaoMub2Zwx1M
 Just take the mossberg in the inventory, shoot a bit, pass a bit of time, should happen again.
