### ISSUE TITLE
Auto-travel uses vehicle unsafe speed

### ISSUE THREAD

**Issue by natsirt721** [CleverRaven/Cataclysm-DDA#45260]
# Describe the bug
Auto-travel with a vehicle will set the cruise control to the vehicle maximum speed, resulting in vehicle damage over time

# Steps To Reproduce
1. Find a vehicle, engage cruise control
2. Find a long stretch of straight road, attempt to use auto-travel to navigate to the end
3. Observe that the cruise control is set to the vehicle max speed 

# Expected behavior
Auto-travel should use the vehicle's max safe speed rather than its highest achievable speed

# Screenshots
Vehicle in cruise control showing the unsafe speed color indicator while using auto-drive
![image](https://user-images.githubusercontent.com/6325435/98294254-a3897600-1f7d-11eb-8824-f3e0ab8fd4ff.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-7200-gfc2388e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Beta National Guard Camp [national_guard_camp],
    More City Locations [cityside],
    More Locations [more_locations]
]

# Additional context
I did not test this without cruise control on beforehand, as my test vehicle was a wagon without a speedometer and I couldn't see the current speed

**Comment by wapcaplet** [comment]
Confirmed. This appears to affect low-speed vehicles like bicycles, especially. Here is a regular bicycle with 22 km/h safe speed, being driven with auto-drive at 29 km/h:

![image](https://user-images.githubusercontent.com/238395/99157953-c527e300-268a-11eb-8c61-ffc252cc1438.png)

![image](https://user-images.githubusercontent.com/238395/99157956-cbb65a80-268a-11eb-826f-398b25984343.png)

A children's tricycle has a safe speed of 11 km/h, but auto-drive pushes it to the max 19 km/h:

![image](https://user-images.githubusercontent.com/238395/99157965-e12b8480-268a-11eb-9b1f-be8e5227b173.png)

![image](https://user-images.githubusercontent.com/238395/99157963-dec92a80-268a-11eb-8506-b3090e5ffaf2.png)

This electric bicycle has safe/top of 35/39. Auto-drive makes it go 39:

![image](https://user-images.githubusercontent.com/238395/99157973-f43e5480-268a-11eb-84a4-4fdca62c5ed7.png)

![image](https://user-images.githubusercontent.com/238395/99157976-f9030880-268a-11eb-9f19-19bf96375af5.png)

With a regular car (such as beetle or Humvee) having a top speed over 100 km/h, the maximum speed I observed in auto-drive was 56 km/h (35 mph), well within the vehicle's safe limit.

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-7515-gbcdd3a2561 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by actual-nh** [comment]
I am suspecting, from an examination of [src/vehicle_move.cpp#L1415](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/vehicle_move.cpp#L1415) (and [src/vehicle_move.cpp#L1256](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/vehicle_move.cpp#L1256)), that the problem may specifically happen when the difference between safe and max speeds is less than 40 mph (if I'm getting the speed units used right - looks to be 0.1 mph). (Note: The terminology is a bit confusing; there is a difference between auto-travel and auto-drive!) It is also possible the prior speed (on cruise control prior to engaging auto-travel) makes a difference.
