### ISSUE TITLE
Separate mending from the fault

### ISSUE THREAD

**Issue by Hirmuolio** [CleverRaven/Cataclysm-DDA#45267]
# Is your feature request related to a problem? Please describe.
Faults are fixed by mending them.
The requirements and other attributes of the mending action are defined inside the fault. 
For example gun faults in https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/items/gun/faults_gun.json

It would be better if the mending action was defined separately.
This way multiple different faults could use the same mending action without the action needing to be  redefined for all of them.

Mending is also limited into fixing two faults (the fault that it is defined in plus one another).

# Describe the solution you'd like
Move the mending action out of the fault.
Allow the mending action to define multiple faults that it fixes.

# Describe alternatives you've considered
Use crafting recipes to define the mending action. They have strong overlap.

# Additional context

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
