### ISSUE TITLE
Limit the item names visible to the player only to those (s)he had the chance to see/know of

### ISSUE THREAD

**Issue by Aivean** [CleverRaven/Cataclysm-DDA#45262]
# Is your feature request related to a problem? Please describe.

Currently player/avatar has the omniscient knowledge of all item types that exist in the world, specifically, it shows in the item description:
<details>
<summary>screenshot of the fresh character</summary>

![image](https://user-images.githubusercontent.com/2865203/98328943-d5193600-1fab-11eb-980d-1b738b816afa.png)

Recipes:
![image](https://user-images.githubusercontent.com/2865203/98329624-81a7e780-1fad-11eb-90ad-51a931c31187.png)

</details>

There are item types that are uncommon enough to assume that an average joe (random character) shouldn't know about their existence.

# Describe the solution you'd like

* Keep track of item types that the player had chance to see or know of
* When showing any list of items to the player, filter it using that set
* When player sees an item, or reads about it in the book (sees recipe) add the corresponding item type to the tracked set

Note: that tracked set is different from the list of autolearned recipes (it's actually a superset of known recipes). E.g: player can know of something without the ability to craft it.

# Challenges

* There should be a way to initially populate that set, i.e. have some kind of item group or item flag that marks an item as a "common knowledge"
* Perhaps, some professions should have additional item groups added to that initial set. E.g., military professions should know about military items, bionic professions should know about bionics, etc.

**Comment by dchieh222** [comment]
It should probably feed off from skills and proficiencies. Ideally, in JSON, you should be able to append alternate descriptions. e.g. a int 3 character sees a shillelagh as "big hurting stick" or someone with no knowledge of guns should only be able to tell a weapon is "handgun" or "rifle."

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
