### ISSUE TITLE
We can stand on the same tile as an animal (when we leave water)

### ISSUE THREAD

**Issue by Zeropol** [CleverRaven/Cataclysm-DDA#45261]
# Describe the bug
We can stand on the same tile as an animal if the animal is tied next to a deep water tile and the player, initialy in water, move on the animal position. The animal stay visible, the player is invisible.

# Steps To Reproduce
1.Tie an tamed animal on a tile next to a deep water tile
2.Go swimming
3.Walk on the animal

# Expected behavior
The animal is pushed or the animal is displaced on water

# Screenshots

[https://cdn.discordapp.com/attachments/598523535169945607/774088049742708776/walkingThroughChick.gif](https://cdn.discordapp.com/attachments/598523535169945607/774088049742708776/walkingThroughChick.gif)
# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-7232-gee0a92c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Fuji's Military Profession Pack [fuji_mpp]
]

**Comment by natsirt721** [comment]
I have seen a similar error happen with bridge ramps - while ascending the ramp my horse in a horse-drawn wagon was displaced by an otter at the top, which ended up displacing me out of the drivers seat into the back of the wagon. Managed to stop the vehicle, re-hitched the horse, and when I tried to re-enter the drivers seat got an error like "the player is already driving this vehicle" or something. Figured fringy enough to be not worth the bug report, but this seems similar enough to mention it.

**Comment by Zeropol** [comment]
This bug had at some time been solved.

Today I tried : 
- Moving into a (friendly) chicken position from _shallow_ water : chicken was displaced on the water.
- Moving into a (friendly) chicken position from _deep_ water : got message " you cannot move the chicken out of the way"
