### ISSUE TITLE
Clothing modification menu navigation inconsistency

### ISSUE THREAD

**Issue by Aivean** [CleverRaven/Cataclysm-DDA#45274]
# Describe the bug

When all items in "clothing modification menu" are inactive, up and down keys behave inconsistently:
* "up" key works as intended: moves cursor one line up
* while "down" key always moves cursor to the beginning of the list

# Steps To Reproduce

1. spawn tailors kit and socks
2. don't have any materials around
3. `a`ctivate tailor's kit and select "modify clothing"
4. ensure that all items in the menu are greyed out
5. observe the behavior of up and down keys

# Expected behavior

"Down" key should move cursor one line at a time, similar to "up" key.

# Screenshots

![modif_bug](https://user-images.githubusercontent.com/2865203/98421110-79978880-203d-11eb-8c35-d47c8b434f39.gif)

# Versions and configuration

- OS: MacOs
    - OS Version: Name: Mac OS X; Version: 10.14; Build: 18A391; 
- Game Version: 0.E-7368-g891488a81b-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm]
]

# Additional context

Might be a good first issue for those who want to start with C++.

**Comment by Pupsi-Mupsi** [comment]
This one's on me. I accidentally introduced this in #45201.
