### ISSUE TITLE
Potential inconsistency for LOVES_BOOKS(Bookworm) and HATES_BOOKS fun bonuses

### ISSUE THREAD

**Issue by sacrificerXY** [CleverRaven/Cataclysm-DDA#45272]
https://github.com/CleverRaven/Cataclysm-DDA/blob/891488a81bd58099a8d7b852b519bc06ee121616/src/player.cpp#L2313-L2345

This function returns the enjoyability of a book. From what I understand, it's interface differentiates between the reader and the listener, like so:
```
int listener_book_fun_value = reader.book_fun_for( book, listener );
```
The reader and the listener is the same in most cases. This is when the player or an npc reads a book alone.

However, when the player is reading with other npcs, the way the loves/hates books traits seems wrong. Starting at line 2330, you can see that reader (the `this` object) is actually the one imparting the bonuses to the listener. The listener having the loves/hates books traits doesn't affect the bonus calculations.

| reader | listener | listener fun |
| --- | --- | --- |
| no trait | no trait | no bonus |
| no trait | has trait | no bonus |
| has trait | no trait | gets bonus |
| has trait | has trait | gets bonus |

At the very least, I would expect that a character would receive bonuses based on *their own traits* regardless if they're alone or in a group. Although maybe the reader's love/hate for books could affect the listener's experience.

**Comment by sacrificerXY** [comment]
I tested some things in-game. Here is what I observed:
- The reader, whoever it may be, gets a morale effect from its loves/hates books trait.
- If the reader is the player and the listener is an npc, the npc gets morale effect as if they have the loves/hates books trait of the player. If the player doesn't have the trait, the npc gets no morale effect. In either case, the npc having the loves/hates books trait did not matter.
- If the reader is an npc and the listener is the player (player can't read), the player gets morale effects from its own trait.

The 2nd and 3rd points are inconsistent with respect to the listener. In one, the listener's traits mattered while in another it did not.

**Comment by Inglonias** [comment]
I wrote the book_fun_for method by trial and error, basically. I didn't seriously test how it behaves in reading groups.

**Comment by sacrificerXY** [comment]
I see. Then I suppose this is not set in stone yet. My only issue is that the players seems to get preferential treatment. ~~*Which is not okay because equality smh. As an NPC Rights Activist, I demand*~~ every character should get at least the baseline fun bonuses/penalties from their own traits for reading.

Just an idea but, I would think that group reading might be more fun for all the characters involved. During the session, everyone would engage, make jokes, or socialize in general (Social skill?). Maybe everyone (except book haters) just gets a +1 to simulate that. When NPCs gets fleshed out more, perhaps things could go wrong and a fight breaks out or something.
