### ISSUE TITLE
Ammo belt "melts when not in a very cold climate"

### ISSUE THREAD

**Issue by natsirt721** [CleverRaven/Cataclysm-DDA#45270]
# Describe the bug
Ammo belts appear to have a json flag that identifies them as a cold food, and the bulleted qualities section in their item description reads "This food melts when not in a very cold climate, and tasted must better when frozen".

# Steps To Reproduce
1. Spawn an ammo belt, either .50 BMG, .223, or .308 (although others may behave the same way)
2. Observe the description indicating that the belt is similar to ice cream and should be kept frozen

# Expected behavior
I don't get temptations to eat my bullets.

# Screenshots
![image](https://user-images.githubusercontent.com/6325435/98409787-769e9700-2041-11eb-837a-6de6fe59bbd0.png)
Shown is the .50 belt, the .223 and .308 exhibited a similar trait.

Do not take a screenshot of the crashing window. Please provide the crash logs in the "Additional context" -->

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-7200-gfc2388e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Beta National Guard Camp [national_guard_camp],
    More City Locations [cityside],
    More Locations [more_locations]
]

**Comment by Hirmuolio** [comment]
The flag `MAG_DESTROY` has wrong description.

https://github.com/CleverRaven/Cataclysm-DDA/blob/d10f768cdba15dd6a42d17be5bdc1514d883bb5d/data/json/flags.json#L390

**Comment by Aivean** [comment]
My bad, in #44706 I added `MAG_DESTROY` flag with wrong description.
