### ISSUE TITLE
Advanced Inventory Management Container Menu Duplicates Instead of Moving Liquids

### ISSUE THREAD

**Issue by Kongron** [CleverRaven/Cataclysm-DDA#45287]
# Describe the bug

When using the Advanced Inventory Manager, moving liquids to a container duplicates the liquid instead of moving it, essentially giving the player the ability to dupe liquids infinitely.

# Steps To Reproduce

1. Create a new default character in default world. 
2. Spawn a separate liquid container and a liquid.
3. Open advanced inventory manager.
4. Select the empty container, press C for container menu.
5. Move liquid into [C]ontainer.
6. The liquid from the original container of said liquid does not disappear.

# Expected behavior

When using the [C]ontainer option, liquid moved into the new container should disappear instead of simply spawning more of the same liquid into the new container. As it stands, this lets a player infinitely dupe liquids of value in moments. It also ruins the functionality of the [C]ontainer option in the advanced inventory manager for people who just want to move all of their liquids of one type into one container.

# Screenshots

![a](https://user-images.githubusercontent.com/74102203/98442697-6f8d8c80-2106-11eb-8992-8153904e4597.png)
![b](https://user-images.githubusercontent.com/74102203/98442701-72887d00-2106-11eb-98c4-915ad9f06e1b.png)
![c](https://user-images.githubusercontent.com/74102203/98442702-74524080-2106-11eb-8a47-20bd463f5e3e.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-7357-g86a33ce [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

I remember running into this bug early into 0.E experimental, but thought it would have been noticed by now. I can attach save file if necessary, but I have moved PC rigs in between the two playthroughs, so I suspect it should be easily reproduced on any 0.E experimental.

**Comment by RoyBerube** [comment]
I've never used this feature; I suspect it is rarely used. Anyway, the bug is easily reproduced when the empty container is on the floor.
