### ISSUE TITLE
Wildly incorrect calculation of charges for lamp oil cooker/duplicated selection

### ISSUE THREAD

**Issue by dchieh222** [CleverRaven/Cataclysm-DDA#45285]
# Describe the bug

When attempting to cook with a lamp oil cooker, the number of charges displayed for the lamp oil cooker is both wildly incorrect and the singular tool is duplicated for reasons

Attempting to use a lamp oil cooker which I have causes it to ask "which tool" of two lamp oil cookers to use, even though I only have one lamp oil cooker. Furthermore, it calculates the charges as wildly incorrect - it asks which one of 6/800 charges I want to use, when I have 800 charges of lamp oil.

# Steps To Reproduce

1. Attempt to cook something that requires use of a lamp cooker.
2. Consider the prompt.

# Expected behavior

It should use the lamp cooker as the only option. It should not ask to select a secondary nonexistent item. It should not have incorrect charges calculated.

# Screenshots

Screenshots attached with demonstrated error.

![bug1](https://user-images.githubusercontent.com/54109532/98438794-2f042380-20b2-11eb-804d-e443d2dd90bf.png)
![bug2](https://user-images.githubusercontent.com/54109532/98438797-33304100-20b2-11eb-9ca6-edd6bf902202.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-7357-g86a33ce [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap]
]

# Additional context

Save game attached in case it can provide more diagnostic information. 

[Cloneville.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5504579/Cloneville.zip)

**Comment by AntonOro-projects** [comment]
I will start looking into this bug if it's okay. Could you assign it to me?

**Comment by anothersimulacrum** [comment]
Unfortunately you need to be a member of CleverRaven to be assigned to things. It's not something I'm a huge fan of, but it's the way it is.

**Comment by Zireael07** [comment]
That's because CDDA does not generally "assign" bugs - you're free to start fixing it without being formally "assigned"

**Comment by dchieh222** [comment]
Let me know if I can provide any information to assist.

**Comment by dchieh222** [comment]
This has been long resolved, thank you.
