### ISSUE TITLE
[balance] [discussion] Plastic mold should be autolearned

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#45293]
Note: There's a more fundamental issue (acknowledged at the bottom) but this is about accepting it as is not discussing a fundamental rework

Problem:
Plastic molds are VERY widespread in recipes, making them on par with Hammer or Screwdriver but for electronics projects
But they don't spawn in the world
And the recipe only appears in a single book (so far as I can tell)

------------------------

Based on this PR #32883, The original creator intended them to represent a Clamshell mold made from 2 plastic bowls
[1] This style of clamshell mold is not difficult to understand.  A basic description (or pictures from which it can be derived) could easily be inferred from the description of any crafting project that uses them

Therefore I present that they should be Autolearned (or at least available in a very wide variety of books) not relegated to a single recipe in a single book.

NOTE:
[1] These are NOT injection molds (they're not made out of metal or clay, nor are they unique to each project) and they are NOT 2 part silicon/resin molds (they are re-usable and re-formable for each project, and made from plastic not epoxy).  They're just 2 thin plastic shells, heated to softness so they can form around something and then left to cool.  This property is fundamental to all plastic as that's literally what the name means and is intrinsic to it's use.  As such any project that uses plastic would by inference assume the foundational knowledge from which you could (with experience) derive the nature of a clamshell mold.

------------------------

There's also a more fundamental problem with the mold in that the purpose is actually to allow mass reproduction of parts that melt at lower temperatures, based on a mother model that takes longer to create.  This means it should be a permanent unique mold for each part, and better suited to replicating _subcomponents_ used by several different crafts (like shells, fittings, clips, buttons, etc) rather than a single tool reused for final object production (like the coilgun).

As such I think it's being used incorrectly, and people are intending to mean a "plastic block" component meant to be carved, heated, shaped, and sanded into custom pieces unique to that particular craft.  These blocks would be produced ahead of time, then consumed as a component and produce Plastic Chunks as a byproduct of the plastic you cut away.

But that's a major shift in how it's used, and better left until after 0.F

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/should-plastic-mold-recipe-be-in-more-books/25310/5

**Comment by I-am-Erk** [comment]
There are a number of complex factors that need to go into making a plastic mold, it's not something you should be able to do without being taught somehow. When we can tie recipes to proficiencies then someone who understands plastic working might autolearn it.

It sounds like your problem is that plastic molds don't spawn in the world and the books are too rare. Those are easy problems to fix.

**Comment by Xpyder** [comment]
> There are a number of complex factors that need to go into making a plastic mold

There are many different kinds of molds.  Which style are you thinking of for this?

**Comment by Zireael07** [comment]
As the original author, I am thinking that they should be available in more books (DIY Compendium comes to mind), but not autolearned (and their use cut down to very simple things like bottles, bags and more molds, they are certainly not fit for complex electronics.

As an aside, it's making me wish we had a way to add a programmer's equivalent of "translator notes"....

**Comment by I-am-Erk** [comment]
I'm generally opposed to the DIY compendium because it's already an overdone book with something like 100 recipes, and it gets made the default for any "i'm not sure where else to put this" recipe. 101 crafts might be okay, I can see there being a bit in there about mold making.

> There are many different kinds of molds. Which style are you thinking of for this?

That is, in fact, one of the complex factors that needs to go into making a plastic mold. presently all types of plastic are abstracted as "plastic chunk". Until we split plastic into at least a few different subtypes I assume that part of making and using a plastic mold is figuring out what type of plastic you're working with and what sort of a mold you would need.

**Comment by Xpyder** [comment]
> As the original author, I am thinking that they should be available in more books (DIY Compendium comes to mind), but not autolearned

That works for me then.

As for which books I'd suggest cross referencing electronics books for recipes that use plastic molds.  That would give us a starting list from which we can pick sensible choices

Once I have free time and energy I'll try to put the list up, assuming no one beats me to it.

**Comment by Xpyder** [comment]
Pivoting issue, closing this one

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/should-plastic-mold-recipe-be-in-more-books/25310/17
