### ISSUE TITLE
adobe wall strange construction

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#45296]
Game version: 0.E

Operating system: ArchLinux

Tiles or curses: Both

Mods active: None

### Steps to reproduce

* Build "half-built adobe" and then "adobe wall".
* Build "half-build wooden stairs" next to it and then "wooden stairs".
* Climb that stairs.
* Look at the adjacent "adobe wall" tile.

### Actual behavior

The tile on top of the wall is an "open air" and nothing can be built on top of it.

### Expected behavior

The tile should be a roof or something that can have a floor buildable on it.

### The result of the behavior

Suppose you build a house with ground floor of 4x4 tiles. You can build a roof of 2x2 inside of it. The first floor becomes restricted to inner 2x2 which is probably not intended. In the past I've built a two-floor 4x4 house with wood walls and the second floor using the available 4x4 tiles. But I can't remember whether I built roof over the walls or not.

### Possible fix

Allow building a roof over an adobe wall.

**Comment by aimnadze** [comment]
Take a look a the save:
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5505733/save.zip)
