### ISSUE TITLE
AppVeyor is (probably) not set up correctly

### ISSUE THREAD

**Issue by andrei8l** [CleverRaven/Cataclysm-DDA#45301]
# Describe the bug

As you can see in [this build failure](https://ci.appveyor.com/project/kevingranade/cataclysm-dda/builds/36188380#L176), the compiler on AppVeyor appears to be using a MS dialect instead of conformal C++14. 

# Steps To Reproduce

# Expected behavior
AppVeyor compiles for standard C++14 like the rest of CI
# Screenshots
# Versions and configuration
# Additional context
A quick search suggests that it simply needs the `/Za` flag, but I don't know anything about MS compilers or AppVeyor

**Comment by ZhilkinSerg** [comment]
There is nothing wrong with Appveyor - it takes language standard settings from the project. Something is wrong (from VC++ POV) in the code - for example you are using alternative logical operator tokens. Do not use them.

**Comment by andrei8l** [comment]
Please add that to the [style guideline](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/CODE_STYLE.md) if it's a hard requirement. IMHO you shouldn't be using a MS dialect for a cross-platform project though.

**Comment by ZhilkinSerg** [comment]
> 
> 
> Please add that to the [style guideline](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/CODE_STYLE.md) if it's a hard requirement. IMHO you shouldn't be using a MS dialect for a cross-platform project though.

What do you mean by "MS dialect"? We are not using something unique to MS.

**Comment by andrei8l** [comment]
Alternative operators have been in C++ since the beginning (or at least since before C++98). From what I can gather, Visual Studio doesn't support them by default (without the conformance flag) for compatibility with C89.

**Comment by ZhilkinSerg** [comment]
Yeah, these alternatives are there for those 7-bit desperadoes. We do not need to use them.

**Comment by andrei8l** [comment]
I prefer them because they are cleared and harder to mistype. Since they are part of the language, please update the coding guide if they can't be used for this project.

**Comment by ZhilkinSerg** [comment]
Nah, I am good.

**Comment by andrei8l** [comment]
Please stop spamming my PR now. I don't understand why this simple request triggered you in such a way. Thank your assistance

**Comment by ZhilkinSerg** [comment]
What do you mean? I am reviewing your PR and making suggestions.

**Comment by andrei8l** [comment]
Thanks; I appreciate it. At this point though, I would prefer to get feedback on code quality and then I can change the overall coding style at the end if the PR is acceptable.
