### ISSUE TITLE
Dump command: being able to unload all items from a container into a container of your choosing, or onto the ground

### ISSUE THREAD

**Issue by arockperson** [CleverRaven/Cataclysm-DDA#45310]
# Is your feature request related to a problem? Please describe.
Frequently I want to empty out a container, for example, a backpack full of loot. However, (U)nloading the container will put it into other containers in your inventory, frequently things like your armor which you don't want to be full of items. Being able to easily dump out the contents of a container into another container or onto the ground would make things so much easier. Right now, as far as I know, the only way to automatically empty a container onto the ground is to take off all your clothing that can give storage, which is a hassle.

# Describe the solution you'd like
A new command that would empty a container into another container, or onto the ground. Maybe it could be like unloading a liquid container, where it firsts asks whether you want to put it into another container or onto the ground, and then you choose where to put it.

# Describe alternatives you've considered
Just using (U)nload--but I don't think that's nearly as useful as this would be.

# Additional context
This has been my #1 most wanted feature ever since I first tried out nested inventory. I think it would massively improve user-friendliness.

**Comment by RoyBerube** [comment]
This is something that needs to be implemented. Great idea.

My vote is for extending the (U)unload command to behave similar to when unloading a liquid. Less complexity from a user's perspective.

**Comment by natsirt721** [comment]
Partial workaround for this - you can change the inventory to display items by their container (including worn items) using `;`, and then all the things in your backpack are in a nice block and ready to be multi`D`ropped.

**Comment by Daimiou** [comment]
Would it be possible to implement container management into AIM? Just like it allows moving items between vehicle/ground cell to vehicle/ground cell, there should be an option to open a container item and have it function like any other area that can store items.

**Comment by Night-Pryanik** [comment]
As of 0.F-10973 we have `Unload container` action, unbinded by default.
