### ISSUE TITLE
Exception:  Item acidchitin_piece was loaded with charges, but can not have any

### ISSUE THREAD

**Issue by sumpfralle** [CleverRaven/Cataclysm-DDA#45326]
# Describe the bug

An exception is raised after loading a game. It is possible to ignore this message. The game continues without issues.

```
    void item::io<io::JsonObjectInputArchive>(io::JsonObjectInputArchive&)
    ??:?
    item::deserialize(JsonIn&)
    ??:?
    decltype ((({parm#1}.deserialize)(*this)),(true)) JsonIn::read<item>(item&, bool)
    ??:?
    submap::load(JsonIn&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)
    ??:?
    mapbuffer::deserialize(JsonIn&)
    ??:?
    std::_Function_handler<void (std::istream&), read_from_file_optional_json(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (JsonIn&)> const&)::{lambda(std::istream&)#1}>::_M_invoke(std::_Any_data const&, std::istream&)
    cata_utility.cpp:?
    read_from_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (std::istream&)> const&)
    ??:?
    read_from_file_optional_json(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (JsonIn&)> const&)
    ??:?
    mapbuffer::unserialize_submaps(tripoint const&)
    ??:?
    mapbuffer::lookup_submap(tripoint const&)
    ??:?
    map::loadn(tripoint const&, bool, bool)
    ??:?
    map::load(coords::coord_point<tripoint, (coords::origin)1, (coords::scale)1> const&, bool)
    ??:?
    game::unserialize(std::istream&)
    ??:?
    read_from_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (std::istream&)> const&)
    ??:?
    game::load(save_t const&)
    ??:?
    main_menu::load_character_tab(bool)
```

# Steps To Reproduce

1. load the attached savegame
2. enjoy the error message

# Expected behavior

No error message.

(I appreciate, that it is not fatal - thanks!)

# Versions and configuration

 - OS: Debian testing
 - Game Version: 0.E-7472-g7f7deed
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: default

# Additional context

* [segfault-handle_gun_damage-log.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5513037/segfault-handle_gun_damage-log.zip)
* [segfault-handle_gun_damage-savegame.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5513038/segfault-handle_gun_damage-savegame.zip)

**Comment by wapcaplet** [comment]
Sounds like the same error that has occurred in the past for other items, such as #41821. It is related to loading a save game, while we are gradually phasing out many of the items that previously had "charges".

I made fixes for some such items back in #42976 and added some [closing comments](https://github.com/CleverRaven/Cataclysm-DDA/pull/42976#issuecomment-675205199) about possible future items that would need similar fixes. But you are correct, the error is not fatal - and after you save again, it should go away on future loads.

**Comment by PaulBlay** [comment]
As of 11271 this bug still present for hydrogen sacs from giant insects.

 DEBUG    : Item mutant_bug_hydrogen_sacs was loaded with charges, but can not have any!

 FUNCTION : void item::io(Archive&) [with Archive = io::JsonObjectInputArchive]
 FILE     : src/savegame_json.cpp
 LINE     : 2493

**Comment by hexagonrecursion** [comment]
I tried to create a fresh save that would reproduce this by following this instructions, but failed.

https://github.com/CleverRaven/Cataclysm-DDA/pull/42976#issue-468519499
> 
>     1. Debug-spawn a pile of 1 of every item (press `E` from the debug-spawn-item menu)
> 
>     2. Teleport 9 overmap squares away
> 
>     3. Save game, quit and reload
> 
>     4. Walk toward the pile of items - "loaded with charges but can not have any" errors will occur unles items are in the `charge_removal.json` list.
