### ISSUE TITLE
Persistent Crash when approaching same area

### ISSUE THREAD

**Issue by rurridurriburri** [CleverRaven/Cataclysm-DDA#45323]
**Describe the bug**

When going NNW from my base, on my bike the game crashes. Taking a more westerly approach make it happen faster while still in the field pretty much directly west of my farm.  Doesn't _appear_ to happen when I briefly tried to go SSW. 

**Steps To Reproduce**

Start forward on bike, heading west from my farm house base.
North through fields then follow edge of forest until there is a clearing between two patches of forest and enter the clearing. Seems to happen quicker if you take an approach nearer the road.

**Expected behavior**

Expected to have notifications of military zombies punching turrets and spotlights in this area as there is a roadblock on the road just west of here and that is usually what happens. Quite often see the spotlights wandering around in the field as well. Then I would head north through the fields above the airport and there is a small horde there south of a mi-go scout tower and a military outpost I pass by on my way to the mansion I am headed to.

**Screenshots**

This is roughly the area of the initial crashes. If you head more directly west before turning north it seems to happen more south of here in the fields.

![overmap](https://user-images.githubusercontent.com/74201567/98574390-78ed3500-227d-11eb-9ae1-6d279cba55b6.png)

**Versions and Configuration**

Debug.log included below

 - OS: [Windows 10]
 - Game Version: 0.E-7472-g7f7deed
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: dda, no_npc_food, package_bionic_professions, Graphical_Overmap, No_Fungi
 

**Additional Context**
![thething](https://user-images.githubusercontent.com/74201567/98576431-219c9400-2280-11eb-9b39-1f482a20bf29.png)
Logs:
[crash_debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5512260/crash_debug.zip)
Save: (What I believe is the save?)
[Niter.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5512312/Niter.zip)

**Comment by ektoplazm** [comment]
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5512721/crash.log)
getting the same-ish crash log on different characters in different locations

**Comment by throttlekitty** [comment]
Also getting the same, it's a new neighborhood and I have no insight to a cause.

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5512878/crash.log)

- OS: Win 10
- Game Version: 0.E-7472-g7f7deed (tiles) 64-bit
- Mods: [ "dda", "No_Fungi", "filthy_morale", "more_classes_scenarios", "cbm_slots", "zets_hair_extensions" ]

**Comment by andrei8l** [comment]
Culprit is likely https://github.com/CleverRaven/Cataclysm-DDA/pull/45264. It probably just needs a nullptr check at `item.cpp:641` to replace the flag check that was removed

**Comment by coverthesilence** [comment]
Started getting the same segfault with latest version
Happens when bilious soldier zombie tries to shoot player. Recreated this on default world settings with different character spawning him with debug so I don't think my save is nessesary
