### ISSUE TITLE
Half-done transition from "rags"-based tailoring to "cotton sheets"-based.

### ISSUE THREAD

**Issue by Tamiore** [CleverRaven/Cataclysm-DDA#45322]
# Describe the bug

At some point there was a PR that started a transition from "rags"-based tailoring
- e.g. http://cdda-trunk.chezzo.com/long_undertop/craft 800 equivalent thread, 60 minutes craft time

to "cotton sheets"-based based
- e.g. http://cdda-trunk.chezzo.com/long_underpants/craft 110 equivalent thread, 180 minutes craft time

The problem is, it was half-done at best. Now some recipes accept ONLY "rags", some "cotton sheets" and "patchwork cotton clothing parts" interchangeably, and some ONLY "cotton sheets". 
So, as of right now, there is no rime or reason behind what-requires-what, how much equivalent thread similar item now require, and what the crafting times for them are. 

# Steps To Reproduce

.json-level issue with the recipes, all current recipes can be looked up at http://cdda-trunk.chezzo.com

# Expected behavior

Most tailoring-based cotton items (that aren't explicitly made of rags) should require "cotton sheets" or "patchwork cotton clothing parts" interchangeably.

# Versions and configuration

.json issue with the recipes, effects all recent experimental versions

# Additional context

I've only explicitly included two items, but the issue spawns across dozens (if not hundreds) of recipes.

**Comment by ZhilkinSerg** [comment]
Yeah, there is unfinished project - https://github.com/CleverRaven/Cataclysm-DDA/projects/25. Feel free to participate.

**Comment by EvgenijM86** [comment]
I think you should be able to cut curtains in windows into cotton sheets, because they literally are just a very big cotton sheet. It will be a slower process than cutting them into random shaped rags, but it should be possible to do.

**Comment by Fosheze** [comment]
> I think you should be able to cut curtains in windows into cotton sheets, because they literally are just a very big cotton sheet. It will be a slower process than cutting them into random shaped rags, but it should be possible to do.

You already can. Sheets can be disassembled into cotton sheets and sheets are what the gam uses for curtains.
