### ISSUE TITLE
Incorrect analysis of the building "Lay the floor cable"

### ISSUE THREAD

**Issue by Qsppl** [CleverRaven/Cataclysm-DDA#45320]
# Describe the bug
When building "Lay floor cable", 4 copper wires are spent.
After disassembling this structure, 800 copper wires are returned.

# Steps To Reproduce
1. Go to the build menu and select Lay Floor Cable. Build this structure.
2. Go to the building menu and select "Expand Furniture". Disassemble the "floor cable".
3. At the site of disassembly, 800 units of copper wire remain

# Expected behavior
At the site of disassembly, 4 units of copper wire remain

# Screenshots
![image](https://user-images.githubusercontent.com/22717464/98547986-05155180-22aa-11eb-8632-6b7ce44daf15.png)
![image](https://user-images.githubusercontent.com/22717464/98548026-11011380-22aa-11eb-94f7-5dda2ef9e9f8.png)
![image](https://user-images.githubusercontent.com/22717464/98548041-178f8b00-22aa-11eb-8e66-aca5d3aa2fe3.png)
![image](https://user-images.githubusercontent.com/22717464/98548063-1f4f2f80-22aa-11eb-94d8-b513be1a789a.png)
![image](https://user-images.githubusercontent.com/22717464/98548085-25451080-22aa-11eb-8deb-96990f7ddcd7.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-7242-gb71918d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Alternative Map Key [alt_map_key],
    Aftershock [aftershock],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP]
]

# Additional context

**Comment by anothersimulacrum** [comment]
The deconstruction in the furniture definition is likely using `count` instead of `charges`.
