### ISSUE TITLE
UPS welder welding but not consuming charges (infinite battery)

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#45330]
# Describe the bug
Welder modified for UPS doesn't consume charges unless both are in inventory

# Steps To Reproduce

Setup
Modified Makeshift Welder to use UPS
Modified UPS (taken from disassembling electric jackhammer) to accept small storage batteries

Tests:
```
+ welder and ups in inventory - can use, Charges consumed
- Welder nearby and UPS in inventory - can use, no charges consumed
- Welder in inventory and UPS nearby - can use, no charges consumed
- welder and UPS both nearby - can use, no charges consumed
+ welder nearby and UPS far away - can't use, not enough charges
```

# Expected behavior

The algorithm appears to correctly identify when a UPS is nearby that has charges it *could* consume
I would expect it to consume those charges when used

# Screenshots
Ask if needed

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-7424-gcbcf5fd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    Stats Through Kills [stats_through_kills]
]

# Additional context
Example save attached for easy testing
[Mont Clare.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5514714/Mont.Clare.zip)

**Comment by PatrikLundell** [comment]
I'd suspect it's the same issue as #45018

**Comment by Xpyder** [comment]
Interesting, I assumed it was something in the UPS patch that came through so I only searched for UPS issues.  But it's certainly possible.

fwiw this also happens with ups hotplates when cooking so it's not just welders.

**Comment by wapcaplet** [comment]
Confirmed in 0.E-7424-gcbcf5fd with a UPS-modded hotplate (and powered UPS on the ground nearby). I can cook food with the hotplate without consuming any UPS charges.

**Comment by PaulBlay** [comment]
Not checked in latest experimental, but UPS electric jackhammer does not use any charges to (a)ctivate in experimental 11142.

**Comment by RoyBerube** [comment]
Some unexpected behavior happens when crafting with a UPS tool. In this case an arc welder.

- UPS in inventory and arc welder on ground: crafting fails at 4% with message "You no longer have a none and can't continue crafting"

- UPS and arc welder both on the ground in the same location: craft completes but without consuming any UPS charge.

**Comment by RoyBerube** [comment]
I'm close to making a PR for this. Needs a little more work - some charge usage is inconsistent depending on the location of the UPS and tool.

**Comment by Raikiri** [comment]
@RoyBerube yes, I had very similar experience. However, I sometimes had more weirdness when an arc welder with UPS mod just kept showing very little charges in crafting menu (like 20 or so), so I could not start a craft with it even though there was a UPS around.

There's even more weirdness to this problem coming from a bionic that gives integrated UPS -- I literally could not make it work in crafting at all.
