### ISSUE TITLE
Pupating crawlers, etc. being "classical zombies"

### ISSUE THREAD

**Issue by Lamandus** [CleverRaven/Cataclysm-DDA#45331]
# Describe the bug
I usually play with Dark Days of the Dead. But the pupating zombies are not only getting on my nerves with their trails everywhere, but I don't know why they spawn exactly.
` {
    "id": "mon_zombie_crawler_pupa_decoy",
    "type": "MONSTER",
    "name": { "str": "pupating zombie crawler" },
    "description": "This half of a human corpse is wrapped in sticky black fibers that cover everything neck down.  Beneath the wrapping there is strange rhythmic movement grotesque to behold.",
    "copy-from": "mon_zombie_crawler",
    "armor_bash": 7,
    "armor_cut": 5,
    "armor_bullet": 5,
    "special_attacks": [ { "type": "bite", "cooldown": 3 } ],
    "regenerates": 10,
    "extend": { "flags": [ "SLUDGETRAIL", "SLUDGEPROOF" ] }
  },`
They don't have the "Classic" or "Wildlife" tag and they still spawn

# Steps To Reproduce
1. Play Dark days of the dead
2. see pupating zombies.
3. Cry

# Expected behavior
Not having them in.

# Screenshots
![grafik](https://user-images.githubusercontent.com/33199510/98641039-692c2a00-232b-11eb-860e-be9e7bd7d00c.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-7486-g34527a6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Dark Days of the Dead [classic_zombies],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    meins [mine]
]

# Additional context
I would do that myself, but I don't get why they spawn, they don't have the tag and
 `  {
    "type": "MONSTER_WHITELIST",
    "mode": "EXCLUSIVE",
    "categories": [ "CLASSIC", "WILDLIFE" ]
  },`
is pretty clear to me.

**Comment by Hirmuolio** [comment]
The `mon_zombie_crawler_pupa_decoy` has `"copy-from": "mon_zombie_crawler"` so I assume it also copies the `"CLASSIC"` category from it.

**Comment by Lamandus** [comment]
> 
> 
> The `mon_zombie_crawler_pupa_decoy` has `"copy-from": "mon_zombie_crawler"` so I assume it also copies the `"CLASSIC"` category from it.

is there a way to rewrite the category? Maybe leaving it blank?

**Comment by anothersimulacrum** [comment]
Probably `"delete": { "categories": [ "CLASSIC" ] }` would do it. Or just adding another categories field and leaving it blank.

**Comment by Lamandus** [comment]
> 
> 
> Probably `"delete": { "categories": [ "CLASSIC" ] }` would do it. Or just adding another categories field and leaving it blank.

seems to check out. Making pull request.
