### ISSUE TITLE
Huge log file due to broken bone spam

### ISSUE THREAD

**Issue by halfahermit** [CleverRaven/Cataclysm-DDA#45337]
# Describe the bug

The game logs a huge number of broken bones:  https://www.reddit.com/r/cataclysmdda/comments/ji05pt/674975_broken_bones/

I think maybe it logs each action taken with a broken bone as a new broken bone?

Each broken bone adds a line in the log, so this leads to a huge log file. In my case, I had a 2 million line / 200mb log file, which reduced down to 900 lines/90kb after cutting out all the broken bone messages.

**Comment by wapcaplet** [comment]
Confirmed in 0.E-7424-gcbcf5fd9bd. Breaking my left leg once results in 6 "broken left leg" events. Waiting 1 turn with a broken left leg adds 1 more "broken left leg" event.

![image](https://user-images.githubusercontent.com/238395/98832730-68ae9480-23fa-11eb-94fa-48f9b3883e7e.png)

Waiting 5 minutes adds 300 more "broken left leg" events to the log. So indeed; it appears to be recording a new broken bone with every turn.

**Comment by Fosheze** [comment]
This probably explains the 1GB log file that I had and couldn't open the other day. My character did have all 4 limbs broken at the time.
