### ISSUE TITLE
Segmentation fault by foodperson mask

### ISSUE THREAD

**Issue by Bark0805** [CleverRaven/Cataclysm-DDA#45349]
# Describe the bug

Segmentation fault caused by foodperson mask

# Steps To Reproduce

1. Take 'true foodperson' character(maybe optional)
2. Activate mask
3. Take battery out using advanced inventory
4. Wait for 1 ingame minute
5. Crash

# Expected behavior

remove mask battery from advanced inventory menu when mask is on

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-7496-gc78f54f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]

# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5523963/crash.log)

**Comment by wapcaplet** [comment]
Confirmed in 0.E-7424-gcbcf5fd9bd. "True foodperson" profession is not required, just the mask and battery.

**Comment by RoyBerube** [comment]
Checking for a loaded battery in iuse::foodperson avoids the crash, but it has the side effect of allowing the mask to be taken off once the battery is removed. Not the ideal solution.

Another approach would be to prevent removal of the battery in AIM. I'm not sure how to do that but will take a look.
