### ISSUE TITLE
Potential improvement to firearms gameplay.

### ISSUE THREAD

**Issue by greatjailb8** [CleverRaven/Cataclysm-DDA#45341]
# Is your feature request related to a problem? Please describe.
Standing and shooting aren't the only practical ways of using a firearm. Standing and shooting aren't the only things one can do in real life and in game.

# Describe the solution you'd like
A character can crouch, walk, and run. They should also be able to increase their hit probability when firing a firearm from the crouch position. Lying prone should also be implemented, and it should significantly increase the hit probability of a firearm since having a stable firing platform increases target acquisition and reduces sway. One final feature to have would be to give the character the ability to mount any small arm on a table, corner of a wall, half built wall, backpack etc. 

The character would be able to lie prone, crouch, and mount weapons on most surfaces and hit probability would increase as a result of increased stability.

# Describe alternatives you've considered
An alternative to have would be to increase range for small arms in addition to hit probability, as tiles significantly makes the range in game appear very short. For example, I suggest pistols be bumped to 20, assault rifles to 40, and shotguns to 30. The probability of missing shots from any firearm should be reduced marginally.

# Additional context
Add a probability of striking the spinal cord or brain stem when shooting a monster without armor. If a round hits anywhere here, the monster is immediately incapacitated; set hit probability to low chances unless the monster is close enough to the player. Also add a bleeding effect to striking previously vital organs with firearms; Shooting a heart for example, would create more blood loss.

**Comment by natsirt721** [comment]
- Crouching should definitely increase base accuracy, as well as accuracy at maximum steadiness (flat accuracy buff for entire range of steadiness)
- Crouching should make you harder to hit with ranged attacks.
- IMO Prone is too niche to be implemented solely for gunplay reasons, as there are very few other reasons to go prone
  - Not opposed to it in general though
- Having the bipod modification work as an actual deployable mod (massively reduced recoil in exchange for space and setup time) would be very nice
  - Having this work with items (as opposed to terrain) would be very hard to implement correctly
- Agree that (in general) firearm ranges are too short, but the exact nature of what they "should be" given the warped nature of the map is up for debate.
- We already have critical hits (which recently went through a rebalance of their own), so adding a 'super critical' on top of that seems unnecessary

**Comment by Xelat84** [comment]
Just curious is this possible at all to create some background activity when you give command to shoot, and run it alongside with movemend or idling, with ability to avoid moving/idling and just shoot. Like you specified target to shoot, and affter that just move, and character will shoot that much times as available for single tile movement, something like that. Of course movement and stance will affect accuracy.

**Comment by dissociativity** [comment]
taking more time to aim assumes you're doing whatever possible to get the best possible aim, so it's assumed your character is crouching or going prone with a bipod if that helps, there's no reason for more manual input to make more tedious keypresses

**Comment by greatjailb8** [comment]
> taking more time to aim assumes you're doing whatever possible to get the best possible aim, so it's assumed your character is crouching or going prone with a bipod if that helps, there's no reason for more manual input to make more tedious keypresses

As many controls as there are in cdda, anybody could learn and master the controls eventually, and could learn more if they wanted to. Adding more mechanics to make firearm gameplay more entertaining isn't a burden. If one doesn't like it they don't have an obligation to use it.

**Comment by natsirt721** [comment]
> taking more time to aim assumes you're doing whatever possible to get the best possible aim, so it's assumed your character is crouching or going prone with a bipod if that helps, there's no reason for more manual input to make more tedious keypresses

Strongly disagree with this - if my character is standing I expect them to be shooting standing up, same for crouched. Stance should not be assumed at any point, especially if we have the ability to select stance.

**Comment by dissociativity** [comment]
So you're saying you want combat to take more keypresses for no reason?
> 
> Strongly disagree with this - if my character is standing I expect them to be shooting standing up, same for crouched. Stance should not be assumed at any point, especially if we have the ability to select stance.

**Comment by Squishums** [comment]
Is crouching during a fight a meaningful decision for the player to make, or is it just another thing for people to only do when they can be bothered to make the key presses? Having sniper rifles or something which can only be fired from the prone position could be interesting, if it makes kiting impossible.

Hitting random body parts sounds like it's building into a more comprehensive coverage system for monsters, which I think is part of [this issue](https://github.com/CleverRaven/Cataclysm-DDA/issues/31957)?

**Comment by Kelenius** [comment]
Crouching is instant currently, isn't it?

**Comment by anothersimulacrum** [comment]
Yes, cycling to any move mode is instant.

**Comment by Kelenius** [comment]
Then making crouching increase accuracy would just make it a free bonus and add busywork to switching it on and off between shooting and moving. I agree with

> taking more time to aim assumes you're doing whatever possible to get the best possible aim, so it's assumed your character is crouching or going prone with a bipod if that helps, there's no reason for more manual input to make more tedious keypresses

**Comment by dissociativity** [comment]
> 
> 
> Then making crouching increase accuracy would just make it a free bonus and add busywork to switching it on and off between shooting and moving. I agree with
> 
> > taking more time to aim assumes you're doing whatever possible to get the best possible aim, so it's assumed your character is crouching or going prone with a bipod if that helps, there's no reason for more manual input to make more tedious keypresses

crouching has no reason to increase accurace if a better aim assumes the character is taking steps to have a better aim which may or may not include crouching, please use your imagination sometimes, this will in no way improve gameplay.

**Comment by dchieh222** [comment]
Movement mode switching should have a cost.
