### ISSUE TITLE
It's possible to spawn floating in buildings with open air tiles

### ISSUE THREAD

**Issue by kingluan612** [CleverRaven/Cataclysm-DDA#45355]
# Describe the bug

Spawned floating in mid-air in a school gymnasium

# Steps To Reproduce

Build 11150
Default world settings except npc spawn set to 0.50
Burning building start, random spawn, looks like it chose school

# Expected behavior

Everything went as expected except I spawned in open air

# Screenshots

https://cdn.discordapp.com/attachments/642349261320880128/776169380655661117/unknown.png

# Versions and configuration

OS: windows 10
Game Version: 0.E-7424-gcbcf5fd
Graphics: Tiles
Mods: magiclysm, no fungal monsters, and default world mods

# Additional context

**Comment by int-ua** [comment]
Confirmed by limiting the locations of a bad day profession to school only. The spawning code doesn't check if it's an open air tile.

Please change the title to something like 
```
It's possible to spawn floating in buildings with open air tiles.
```
