### ISSUE TITLE
Vehicle-mounted cooler produces hot air as well as cold air

### ISSUE THREAD

**Issue by 182crazyking** [CleverRaven/Cataclysm-DDA#45354]
# Describe the bug

A vehicle-mounted cooler item spits out "cold air 2" and "hot air 2." The net effect is that it changes the temperature of surrounding tiles inconsistently, heating or cooling them by several degrees F, or not at all. These values seem to fluctuate on a per-second basis with no apparent consistency and after the cooler is allowed to run for several hours continuously. In practical terms, this means that standing in front of an air conditioner in summer can sometimes cause painful warmth.

# Steps To Reproduce

1. Spawn parts necessary to craft a single-tile vehicle with a vehicle-mounted cooler.
2. Set up the vehicle and activate the cooler.
3. Enable temperature display.
4. Watch surrounding tiles; some will be cooler than ambient, some will be warmer than ambient.

# Expected behavior

A vehicle cooler should act like an air-conditioner: ambient air is taken in by a fan, compressed, and allowed to cool as it expands. The ambient air temperature should lower slightly, but consistently, in the vicinity of the cooler. If the warm air is supposed to be modeling the warmer exhaust, it should be produced behind the tile (and perhaps there should be an option to install with directionality like headlights?).

# Screenshots

![image](https://user-images.githubusercontent.com/60903078/98856615-aa4b3980-2412-11eb-9894-7b09e8f33e7a.png)
Screenshot of the problem: ambient temperature is 73; the cooler is 69 degrees (-4), 1N of the cooler is 89 degrees (+15), and 1NW is 57 (-6).

# Versions and configuration

- OS: Windows 10
    - OS Version: 10.0 2004
- Game Version: 0.E-7496-gc78f54f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by anothersimulacrum** [comment]
Use a muffler to move the hot air. Producing both types of air is intentional, because coolers aren't just magic cooling boxes.

**Comment by emptytriangle** [comment]
the vehicle cooler is not an air conditioner unit, it is like a box truck freezer. Last I tested it, it produced enough to freeze everything in an area at least as big as the box truck

**Comment by sparr** [comment]
> A vehicle cooler should act like an air-conditioner: ambient air is taken in by a fan, compressed, and allowed to cool as it expands. 

That's not how an air conditioner works. The refrigerant being compressed in an A/C is in a closed loop. The ambient air on one side is expelled colder, and on the other side is expelled hotter.
