### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Jeraldon** [CleverRaven/Cataclysm-DDA#45350]
# Game crash

# It happens at 17:00:00 ingame time

# dont crash
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5524143/crash.log)

# Screenshots

#- OS: Windows
    - OS Version: Win 7

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5524184/save.zip)

- Game Version: 0.E-7239-gf5bd4da [32-bit]
- Graphics Version: Tiles
- Game Language: Системный язык [russian]
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у NPC [no_npc_food],
    Бионические профессии [package_bionic_professions]

# Additional context

**Comment by RoyBerube** [comment]
Be aware: I attempted to download the save file and the Windows 10 detected a virus.

I suggest closing this issue and removing the save file.

**Comment by BrettDong** [comment]
Tried to reproduce this on latest `master` branch. An NPC dropped his professional camera at 17:00:00 in-game time. The game does not crash and continues normally.
