### ISSUE TITLE
Control laptop crafting bug

### ISSUE THREAD

**Issue by StefanMiletic994** [CleverRaven/Cataclysm-DDA#45358]
# Describe the bug

When crafting control laptop crafting stops at 4% saying you dont have a none, cant continue.

# Steps To Reproduce:

1. Try crafting control laptop.

# Expected behavior

Should make the item or fail based on skill and proficiency.

# Screenshots

![Screenshot_1](https://user-images.githubusercontent.com/49565306/98884627-bd9cea00-2490-11eb-8284-85d0601a8bc5.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/49565306/98884640-c5f52500-2490-11eb-9d3e-b7d4066e5793.jpg)

# Versions and configuration

 - OS: [Windows 10]
 - Game Version: 0.E-7486-g34527a6
 - Graphics version: [Tiles]
 - Ingame language: English
 - Mods loaded: 
Dark days ahead
Aftershock
Disable NPC needs
Bionic proffesions
CRIT Expansion
Alternative map key
More City locations
Jurry-rigged robots
Bionic Slots
Speedy dex

# Additional context

[crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5527739/crash.zip)
[debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5527740/debug.zip)
[Silverthorne Monster.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5527744/Silverthorne.Monster.zip)

**Comment by Pupsi-Mupsi** [comment]
Can't confirm.


- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-7491-ge884feb389-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Aftershock - UndeadPeople Tileset [AftershockUDP]
]

**Comment by Pupsi-Mupsi** [comment]
@StefanMiletic994: Would you try - if not already the case - having hackPRO inside your inventory while crafting.

**Comment by StefanMiletic994** [comment]
Yeah it was in inventory all the stuff i needed to craft. I even tried if there was some difference if its on table or just floor crafting but yielded no result.

PS. There is also a bug with with npc hunger level is ERROR! forgot to mention or should i make another issue report?

**Comment by Pupsi-Mupsi** [comment]
> 
> 
> Yeah it was in inventory all the stuff i needed to craft. I even tried if there was some difference if its on table or just floor crafting but yielded no result.
- Thank for your feedback.

Would you mind deactivating jury_rigged_robots mod and than try again?

How to remove the mod:

Make a backup of your "mods.json" (-> Cataclysm-DDA\save\Silverthorne Monster\mods.json


And than change it using any text-editor.
Its content currently looks like this.

[
  "dda",
  "no_npc_food",
  "package_bionic_professions",
  "aftershock",
  "crt_expansion",
  "alt_map_key",
  "cityside",
  "jury_rigged_robots",
  "cbm_slots",
  "speedydex"
]

Remove `  "jury_rigged_robots",`
The file should look like this when your done.

[
  "dda",
  "no_npc_food",
  "package_bionic_professions",
  "aftershock",
  "crt_expansion",
  "alt_map_key",
  "cityside",
  "jury_rigged_robots",
  "cbm_slots",
  "speedydex"
]


> PS. There is also a bug with with npc hunger level is ERROR! forgot to mention or should i make another issue report?
- Please use another issue report.

**Comment by StefanMiletic994** [comment]
Sorry for the delay, no its still not working if i did it correctly.



![Screenshot_3](https://user-images.githubusercontent.com/49565306/99014672-6b70cd00-2553-11eb-9974-f89d3a6608cc.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/49565306/99014685-73307180-2553-11eb-9c86-6369cb3630e7.jpg)

**Comment by Pupsi-Mupsi** [comment]
Don't worry. Actually, thank you for helping me with this.

HackPRO seems to be causing this.
It works fine with "Debug Hammerspace" - that's how I tested this at first - and it works fine as well as long as one removes HackPRO from the recipe ("tools": [ [ [ "software_hacking", -1 ] ] ]).

  {
    "type": "recipe",
    "activity_level": "fake",
    "result": "control_laptop",
    "category": "CC_ELECTRONIC",
    "subcategory": "CSC_ELECTRONIC_TOOLS",
    "skill_used": "electronics",
    "skills_required": [ "computer", 4 ],
    "difficulty": 7,
    "time": "25 m",
    "book_learn": [ [ "recipe_lab_elec", 7 ], [ "textbook_robots", 7 ] ],
    "using": [ [ "soldering_standard", 14 ] ],
    "qualities": [ { "id": "SCREW", "level": 1 } ],
    **"tools": [ [ [ "software_hacking", -1 ] ] ],**
    "components": [ [ [ "laptop", 1 ] ], [ [ "receiver", 2 ] ], [ [ "e_scrap", 2 ] ], [ [ "antenna", 1 ] ] ]
  },

Quick-fix would be to remove this line  **"tools": [ [ [ "software_hacking", -1 ] ] ],** from this file  **Cataclysm-DDA\data\mods\Aftershock\recipes\recipes.json**. At least then you'll be able to craft the control laptop and continue with your game


I'm not sure what's really causing it and I'm already pretty tired ;-) I'll try to pick up on this tomorrow. Any hint is very much appreciated.

related files:
Cataclysm-DDA\data\json\items\software.json
Cataclysm-DDA\data\json\items\generic.json

**Comment by anothersimulacrum** [comment]
Something pocket related? Software is stored in special pockets.

**Comment by StefanMiletic994** [comment]
Thanks for the help and info. :) I believe you its 4 am here in serbia atm.  🧛

**Comment by Pupsi-Mupsi** [comment]
> 
> 
> Something pocket related? Software is stored in special pockets.

Yes, I believe you're right. Unfortunately I know not much about the pocket-system.

**Comment by Pupsi-Mupsi** [comment]
> 
> 
> Thanks for the help and info. :) I believe you its 4 am here in serbia atm. 🧛

;-)

**Comment by Entity-y** [comment]
I had this "you no longer have none" issue happen while crafting something else, it turned out that my UPS soldering iron was out of charge.

**Comment by zeropol** [comment]
I had the same issue crafting the control laptop. ( stopped at 4%, _you no longer have a none_. ) I used vehicle vehicle welding rig with way enough charges.

Additionnaly, (after debug spawning the item ), and adding a UPS conversion mod to it, I had _the control laptop+1 (UPS) batteries are dead, like in the issue #43974 .
The "no batteries" error only happened with the actions : play a game, turn music on. All the others actions did not ended up with this message.

( maybe not a bug : I wanted to test the "hack robot - set to passive" action with a friendly police bot, while it worked without battery message, my two mechs (X-01 and X-03) also were set to passive, then combat when I tested the other mode. I don't know if it is the wanted behavior, because the mech do not move by themselves. ( or I don't know how to make them move by themselves ) Sorry if this last report is irrelevant )

tested in 0.E-7232-gee0a92c

**Comment by Roet718** [comment]
Had the same problem. Saw some people talking about it being the result of a pocket system problem so i dropped all the items on the ground and it was able to craft. Might be a good workaround for those who don't want to lose achievements by spawning a none with debug.

**Comment by Entity-y** [comment]
You can re-enable achievements in the debug menu, there's no reason to work around it.

**Comment by Roet718** [comment]
I did not know that, cool. Still would rather not use the debug menu though.

**Comment by John-Candlebury** [comment]
I can successfully and normally craft this Item in current experimental.  Its likely the original issue has been fixed due to improvements in the handling of SOFTWARE type pockets

**Comment by anothersimulacrum** [comment]
Yep, looks like #45434 got it.
