### ISSUE TITLE
Be able to position buttons anywhere in the screen on android. Move them around and choose wich button are wich key.

### ISSUE THREAD

**Issue by rafaelkb** [CleverRaven/Cataclysm-DDA#45362]

**Comment by ZhilkinSerg** [comment]
You already can control position of virtual keys (to a certain degree). Keybindings can be rebind however you want just like in desktop version. Long press on a virtual key shows a popup with command name.

**Comment by kevingranade** [comment]
Incomplete issue, please use issue template
