### ISSUE TITLE
Graphical Overmap not displaying properly

### ISSUE THREAD

**Issue by Theawesomeboophis** [CleverRaven/Cataclysm-DDA#45363]
Graphical Overmap does not load properly

Graphical overmap seems to not be working properly, not sure if it's a launcher issue or not, Has default overmaps.

 Steps To Reproduce
1. Make World with graphical overmap installed
2. Open map
3. It does not display graphical overmap specials
Don't know if this is a known issue, I looked at issues and nothing seems to appear.

# Expected behavior
Graphical Overmap Loads properly
# Versions and configuration
 - OS:  Windows 8.1
 - Game Version: 0.E-7499-gb48a967 (tiles)
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: [
  "dda",
  "blazeindustries",
  "crt_expansion",
  "magiclysm",
  "DinoMod",
  "Graphical_Overmap",
  "Graphical_Overmap_Magiclysm",
  "sees_player_hitbutton",
  "sees_player_retro",
  "my_sweet_cataclysm",
  "crazy_cataclysm",
  "aftershock",
  "secronom",
  "Arcana",
  "vamp_stuff",
  "vamp_stuff+arcana",
  "Medieval_Mod_Reborn",
  "MMA",
  "PK_REBALANCE",
  "Cata++",
  "fuji_mpp",
  "Bootleg_Walkers",
  "AftershockUDP",
  "ArcanaUDP",
  "BlazeIndustriesUDP",
  "crt_expansionUDP",
  "CrazyCataclysmUDP",
  "DinoModUDP",
  "MagiclysmUDP",
  "My_Sweet_CataclysmUDP",
  "MMAUDP",
  "PK_REBALANCE_UDP",
  "secronom_UDP",
  "zets_hair_extensions_undead",
  "Cata++UDP",
  "Arts' Guns",
  "Dorf_Life",
  "Dorf_LifeUDP",
  "fallout",
  "Fallout_CDDA_UDP",
  "Arts' GunsUDP",
  "WHALEYHAIR_UDP",
  "collectablemod",
  "BL9_100monres",
  "Bootleg_WalkersUDP",
  "Medieval_Mod_RebornUDP",
  "vamp_stuff_UDP",
  "package_bionic_professions",
  "alt_map_key"
]

**Comment by Theawesomeboophis** [comment]
I have loaded with alt_map_key off and still have the same problem.

**Comment by Dacendeth** [comment]
Doesnt this mod come with special instructions it tells you to follow, did you follow those?

**Comment by Theawesomeboophis** [comment]
Where are those instructions, that might be problem.

**Comment by Theawesomeboophis** [comment]
Nevermind, not an issue, I just didn't see instructions.

**Comment by Theawesomeboophis** [comment]
Sorry for the inconvenience.
