### ISSUE TITLE
Discussion: Playstyles

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#45371]
I'd like to have a discussion about some of the different playstyles.  What people are enjoying doing (not just what's optimal, but what's fun), and what we'd like to support

And to both support different styles and to encourage you to branch out of just a single approach and try and mix in a bit of other styles

**Comment by Xpyder** [comment]
I think these would be better posted on the forum, looking for the right place now

**Comment by anothersimulacrum** [comment]
[Game Talk: The Library](https://discourse.cataclysmdda.org/c/game-talk/the-library/13) is probably where.

**Comment by Xpyder** [comment]
Ty, I'm starting with The Drawing Board and we'll see if it needs to get moved as it evolves
