### ISSUE TITLE
[MSC]: Licorice Snake

### ISSUE THREAD

**Issue by Theawesomeboophis** [CleverRaven/Cataclysm-DDA#45373]
# Describe the solution you'd like
Add a Licorice Snake enemy to My Sweet Cataclysm

# Describe alternatives you've considered
Adding licorice furniture, possibly a vine to forest

**Comment by Theawesomeboophis** [comment]
Added monster and faction, it gave me a syntax error while linting, how do I fix that?

**Comment by anothersimulacrum** [comment]
You can use [this site](https://jsonlint.com/) to find JSON errors. This won't format it correctly, but does tell you when your syntax is correct.

**Comment by Theawesomeboophis** [comment]
thanks.

**Comment by Theawesomeboophis** [comment]
Working on getting this to a mergeable state.
