### ISSUE TITLE
Discussion: Creating value in both Static Bases and Exploration, and balancing the tension between them

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#45370]
[Forum link](https://discourse.cataclysmdda.org/t/the-future-creating-value-in-both-static-bases-and-exploration-and-balancing-the-tension-between-them/25245)
I think there's value in creating an tension between having (desire/need) for a home base you return to and (desire/need) to get out there and see the world.

My underlying philosophy here is that true vitality comes from the ebb and flow of opposing forces pushing back and forth against each other.  With an eye towards supporting different playstyles while encouraging diversity and trying new things.

If this sounds like a good idea to other people, I'd like to open a series of discussions about the direction we'd like to go with this

[A discussion](https://discourse.cataclysmdda.org/t/the-future-playstyles/25246) about some of the different playstyles, which ones we want to support, and what we can do to encourage you to branch out of just a single approach and try and mix in a bit of other styles

[Things we can do](https://discourse.cataclysmdda.org/t/the-future-making-static-bases-desirable/25247) to encourage static bases and make them valuable and interesting, with an eye towards the different play styles

[Things we can do](https://discourse.cataclysmdda.org/t/the-future-keeping-exploration-desirable/25249) to maintain the desire to go out and see the world even as static bases become desirable, with an eye towards the different play styles

[A possible rework](https://discourse.cataclysmdda.org/t/rebalance-tool-qualities/25250) of the levels of tools to represent not just the quality of the tool itself but whether they're improvised, skillfully crafted, or found;  common, uncommon or rare; mobile, temporarily deployed, rooted to a static location.  I think this would give us a lot more ability to encourage both static bases (some car parts only being repairable with a built vehicle garage) and exploration (some especially difficult tasks may require tools that can only be found and brought back to base (not made), or require equipment tied to a single location similar to the auto docs)

Needless to say this would not be implemented before the next stable release, but something we work towards after.

Originally based off [this post](https://discourse.cataclysmdda.org/t/what-is-the-benefit-of-having-a-base/15319/68) from the forums

**Comment by anothersimulacrum** [comment]
I think this is probably still more appropriate for the forums than a github issue. There's not a whole lot of super actionable stuff here.

**Comment by Xpyder** [comment]
I've moved this to the forum, but put links here for any interested parties.  If it's ok I'd like to leave this open for a little while for visibility by other people who actually do the development.  I know I don't usually scan the forums myself
