### ISSUE TITLE
"tried to put an item" in a container that cannot fit it error when picking up large stacks

### ISSUE THREAD

**Issue by misterprimus** [CleverRaven/Cataclysm-DDA#45374]
# Describe the bug
Get error when picking up large stack of small items, only some of which can fit into your inventory

# Steps To Reproduce
1. Make a player with a backpack.
2. Spawn 5,000 coal.
3. Pick up all coal.

# Expected behavior
No error.

# Versions and configuration
 - OS: Win7x64
 - Game Version: 0.E-7515-gbcdd3a2
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: no bionic specialties, no NPC needs

**Comment by natsirt721** [comment]
This seems to happen to me when I try to put an item into a soft nested container, by which the inner soft container has enough space to insert the item, but doing so would increase the inner container's volume and exceed the outer container's max volume. Interestingly (to me) this repro case does not mention nested containers, but I figured I'd add my two cents.

**Comment by kevingranade** [comment]
Can't reproduce as stated.

**Comment by misterprimus** [comment]
> Can't reproduce as stated.

From memory, I recall a recent game I played where this behavior seems to have been corrected, so I'm closing this until it happens again.
