### ISSUE TITLE
Missing rain sprites in Ultica

### ISSUE THREAD

**Issue by Noodleboom** [CleverRaven/Cataclysm-DDA#45385]
# Describe the bug

Rain tiles are not implemented in Ultica. When raining, they appear as blue question marks.

# Steps To Reproduce

1. Load the Ultica tileset
2.  Wait for or cause it to rain.

# Expected behavior

Rain has sprites.

# Screenshots

![image](https://user-images.githubusercontent.com/28692644/99042018-38c1d700-2549-11eb-9819-b867791b27d8.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-7515-gbcdd3a2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by ZhilkinSerg** [comment]
I guess that's rain animation.

**Comment by ZhilkinSerg** [comment]
Yeah, it is rain. Ultica tileset is missing rain sprite yet.

**Comment by Noodleboom** [comment]
....OH. Well, I feel silly now. Didn't even see the weather.

**Comment by sumpfralle** [comment]
I guess, this issue can be closed?

**Comment by anothersimulacrum** [comment]
It has been fixed?

**Comment by sumpfralle** [comment]
> It has been fixed?

Maybe I misunderstood the last comment from @Noodleboom. I thought, he just misinterpreted the rain drop visualization.

**Comment by anothersimulacrum** [comment]
My interpretation was that it was just them learning what those tiles are. If they still lack a proper tile, then this issue is still valid.

**Comment by sumpfralle** [comment]
> If they still lack a proper tile, then this issue is still valid.

That sounds reasonable.

@Noodleboom: maybe you want to rename this issue?

**Comment by Fris0uman** [comment]
This has been fixed, Ultica has rain sprite now.
