### ISSUE TITLE
Crashes Caused by Corrosive Zombie

### ISSUE THREAD

**Issue by ComradeKarny** [CleverRaven/Cataclysm-DDA#45387]
When i get too close to a corrosive zombie, the game crashes and an the error code
"The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ,/config/crash.log
VERSION: 0.E-7472-g7f7deed
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault"

Pops up and closes the game. Not too big of a problem, I am just going to disable a few mods and disable acidic zombies.

Though, speaking of mods. I have alot that could be causing an issue, 2 of which are not from base game file mods.
Those two are C++, and Arcana. (Arcana has already caused a few crashes, so it may be responsible) 

# Steps To Reproduce
1. Install a fuckton of mods, that are probably out of date
2. Get within range of Corrosive zombie 

# Expected behavior
The game will crash, or atleast it has for me after an hour of testing it myself.

(I can confirm its the corrosive zombie. as there are two of them. and i was able to kill on off at range, before it could launch an attack. Ive tested in 3 different locations, and with several different types of zombies around.)

# Screenshots

![image](https://user-images.githubusercontent.com/43627442/99064427-92d39400-256b-11eb-960c-c4d1cf89f29e.png)

(I dont know how to link images, so i hope that works)

Do not take a screenshot of the crashing window. Please provide the crash logs in the "Additional context" -->

# Versions and configuration

**Comment by dissociativity** [comment]
could you provide the mod list?

**Comment by BrettDong** [comment]
Could you post `crash.log`?

**Comment by Night-Pryanik** [comment]
Non-reproducible issue, no confirmation is half-year, closing.
