### ISSUE TITLE
Cannot generate world with non-ASCII name on Windows even with file path encoding conversion

### ISSUE THREAD

**Issue by AlexiusIX** [CleverRaven/Cataclysm-DDA#45393]
A strange problem interrupt me from starting game.
Everything works in the menu, saves, settings, etc. The tutorial starts. Even a special "survival" gamemode starts. But when I try to generate a world or just start the classic mode by default with the "go straight to the game" button, nothing happens. I mean after confirming the question of the world generation settings "are you sure" it's thrown me into the main menu and does nothing else. In case of pressing the button "immediately into the game", nothing happens at all, except the sound of pressing the button. No crashes and errors. just ignores attempts to create the world.

It is very strange considering that it is training and survival that start normally and generate their own worlds and saves for their modes.

I tried the following treatment methods: compatibility modes with all Windows, run as administrator, remove the "read-only" checkboxes in the explorer from all folders and files, changed paths, tried different discs, path to the game folder with and withoit spaces , with and without Cyrillic, various settings, with and without of mods, different world generation settings.
I tried all this on various versions of the game, on stable branches, on experimental branches of varying degrees of novelty, I even tried to install it with a separate installer from the launcher, install the version with tiles and terminal - no difference, they all do not work the same. And still trying with fresh versions.
Even tried on Win 7 and Win 10 - no differences.
Ingame language: Russian.

**Comment by BX442** [comment]
Не запускаются скачанные версии и скомпилированные вручную?
Что говорит ".../Cataclysm/config/debug.log"?
Используются ли моды?

**Comment by AlexiusIX** [comment]
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5542161/debug.log)
В общем-то компилировать толком не умею, хотя попробовал бы теперь, если поможет. Так что пользуюсь скачанными. Лог прикрепил, собственно не удается ему создать директорию для сейва. Странно, от имени админа пускал, "только для чтения" снимал. Даже только что пробовал вручную создать папку с именем, которое позже ввел для генерации, даже такой костыль не помог.

**Comment by AlexiusIX** [comment]
Собственно, потыкавшись ещё денёк, нашёл причину. В общем проблема оказалась проста - по-умолчанию он даёт мирам имена на кириллице, и собственно папку видимо так же назвать пытался на кириллице и что-то у него не получалось, с кодировками или ещё что. В общем вручную назвал мир на латинице, и генерация мира пошла. Как бы и хорошо, все работает.
Но вот не знаю закрывать тему или нет, потому, что с одной стороны фигня, а не баг и походу только я пока что с ним столкнулся. С другой стороны все же это настоящий и неизвестно сколько пользователей не смогло поиграть в CDDA и не стали обращаться сюда.

**Comment by Theawesomeboophis** [comment]
> Собственно, потыкавшись ещё денёк, нашёл причину. В общем проблема оказалась проста - по-умолчанию он даёт мирам имена на кириллице, и собственно папку видимо так же назвать пытался на кириллице и что-то у него не получалось, с кодировками или ещё что. В общем вручную назвал мир на латинице, и генерация мира пошла. Как бы и хорошо, все работает.
> Но вот не знаю закрывать тему или нет, потому, что с одной стороны фигня, а не баг и походу только я пока что с ним столкнулся. С другой стороны все же это настоящий и неизвестно сколько пользователей не смогло поиграть в CDDA и не стали обращаться сюда.

Don't close issue, this might be an actual problem. (Used google translate by the way).
Actually, after poking around for another day, I found the reason. In general, the problem turned out to be simple - by default, he gives the worlds names in Cyrillic, and apparently he tried to name the folder in the same way in Cyrillic and something did not work for him, with encodings or something else. In general, I manually named the world in Latin, and the generation of the world went. As good as it is, everything works.
But I don’t know whether to close the topic or not, because on the one hand there is garbage, and not a bug, and I’m just running into it so far. On the other hand, it is still real and it is not known how many users could not play CDDA and did not contact here. This is what you said, right? Don't know how accurate translate is.

**Comment by Zireael07** [comment]
Не закрывайте тему пожалуйста. ето очевидно настоящий баг с кодировками

Please don't close, it's apparently a real bug to do with encoding.

(Hit me with an @ if there's something wrong with my Russian, as it's really rusty and probably very Polish-flavored :P )

**Comment by AlexiusIX** [comment]
Ok. I'll not close the topic yet.
Rus to Eng translate was close enough, i think. But still add translate on my post. Sorry for I didn't think to do it at once.
Your Russian was also understandble, that's the main thing.
I'm not too acquainted with GitHub, so don't know can only me or not to close the topic. I"ll search this topic time to time to check it to solution. And I don't mind test something, if it's needed. Because Eng languaged PCs will have a problem with testing, i think.

**Comment by Theawesomeboophis** [comment]
Switched in game language to Russian and world generated. Don't know why though.

**Comment by BrettDong** [comment]
There is an option named "file path encoding conversion" or something alike under Debug tab. Does it make a difference if you turn it off?

**Comment by AlexiusIX** [comment]
> There is an option named "file path encoding conversion" or something alike under Debug tab. Does it make a difference if you turn it off?

No, it’s not. No difference. I suspected something around it, so I tried the options with combinations of these first.

**Comment by int-ua** [comment]
Please add more details to title, I suggest something like "Cannot generate world with non-ASCII name on Windows even with file path encoding conversion"

**Comment by BrettDong** [comment]
Probably fixed by
https://github.com/cataclysmbnteam/Cataclysm-BN/pull/335

**Comment by AlexiusIX** [comment]
> Probably fixed by
> [cataclysmbnteam#335](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/335)

Yeah. Now everything works as expected. At first, it really did not work at all, but I quickly found the reason - the Undead tileset began to crash the game, apparently it was necessary to update it, but everything works with the standard ones now and generating with any symbols, thank you all. How does the topic close here ...

**Comment by BrettDong** [comment]
Do you mean Cataclysm DDA works with Russian world names?

**Comment by AlexiusIX** [comment]
> Do you mean Cataclysm DDA works with Russian world names?

Yes. Now it is.

**Comment by AlexiusIX** [comment]
> Do you mean Cataclysm DDA works with Russian world names?

Yes. Now it is. I already tested it.

**Comment by BrettDong** [comment]
Can reproduce with Jenkins build 11454 Windows x64 Tiles version on Windows 10 ARM64:
<img width="1136" alt="螢幕截圖 2021-02-09 下午4 13 30" src="https://user-images.githubusercontent.com/21075502/107429291-c0d85e00-6af1-11eb-8d71-e5a517c00c12.png">

**Comment by BrettDong** [comment]
Turning off experimental file path encoding conversion solves the issue for me.

**Comment by BrettDong** [comment]
Conclusion so far: the use case of "file path encoding conversion" is when Windows system region and language is the same to the game language.
