### ISSUE TITLE
Specifying z-lvl in assign_mission_target is not working (or it should be added)

### ISSUE THREAD

**Issue by El-Jekozo** [CleverRaven/Cataclysm-DDA#45390]
# Describe the bug
The `assign_mission_target` object specifies the criteria for finding (or creating if
necessary) a particular overmap terrain and designating it as the mission target. One of the parameters is "z" that can be used to specify what z-lvl should be searched for om_terrain id. For example, for searching for any house ground floors via
```
        "om_terrain": "house",
        "om_terrain_match_type": "PREFIX",
        "z": 0
```
But in reality, it still searches on any z-lvl, and with example above, it can choose as mission terrain house_roof, or house_basement.

# Steps To Reproduce

# Expected behavior
It should search for om_terrain only on that z-lvl, so it can be used to search for any variations of one type of terrains or specials, such as houses.

# Screenshots

# Versions and configuration
- OS: Windows
    - OS Version: Win 7 64-bit
- Game Version: 0.E-7357-g86a33ce [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    testing [testing]
]

# Additional context
Not sure if it's a bug or just missing feature that can be added.

**Comment by ZhilkinSerg** [comment]
Yeah, the code that does the search searches on all Z-levels. I think that's correct when mission target is specific overmap terrain - it can be located on any z-level.

**Comment by Fosheze** [comment]
> Yeah, the code that does the search searches on all Z-levels. I think that's correct when mission target is specific overmap terrain - it can be located on any z-level.

This issue is most likely referring to https://github.com/CleverRaven/Cataclysm-DDA/pull/45015#issue-508412145. In which case the dog should never be spawning on the roof.
