### ISSUE TITLE
Single item in car seat can't be viewed before it is picked up

### ISSUE THREAD

**Issue by ArikVhedrovix** [CleverRaven/Cataclysm-DDA#4540]
Windows SDL Experimental Build #144
Version 0.9-751-g1e76da3
Windows 7 64 Bit

When picking up a single item from a car seat by using the ',' key, the only option is to get it without first seeing what it may be. When I try to use the 'x' key to "look" at the square with the item, I only see the car parts that are there. However, if there are two or more items in the car seat, then I get the same letter delineated pickup screen as for other containers. When using the 'e' key to examine the spot, the multiple pickup screen is shown, even if there is only the one item. 
##

**Comment by eliotcougar** [comment]
Is it even an issue?..
`e-5-g` shows selection even with 1 item
`g-g` picks up 1 item, shows selection if multiple
`,-g` picks up 1 item, shows selection if multiple
If there are no items, all three shortcuts behave as "Examine" (`e-5`, `g` and `,` on an empty seat)
There's also an AIM interface...

**Comment by mugling** [comment]
Closing it because its ancient
