### ISSUE TITLE
Wrong skill id in class.json

### ISSUE THREAD

**Issue by FlyingPlum** [CleverRaven/Cataclysm-DDA#45403]
Magiclysm/npc/classes.json:
`line 87:        { "skill": "marksmanship", "bonus": { "rng": [ 2, 4 ] } }`
There is no such skill in original game files.

**Comment by anothersimulacrum** [comment]
The correct skill is `gun`.

**Comment by Theawesomeboophis** [comment]
Fixed it and sent pull request.
