### ISSUE TITLE
Item error in Expermintal 11157 MacOS (Probably from Arcana mod, checking)

### ISSUE THREAD

**Issue by linonetwo** [CleverRaven/Cataclysm-DDA#45433]
# Describe the bug

Two error when loading "Items"

 DEBUG    : tried to put an item (flintlock_ammo) count (30) in a container (flintlock_pouch) that cannot contain it: pocket unacceptable because tried to put too many charges of ammo in item

 FUNCTION : ret_val<bool> item::put_in(const item &, item_pocket::pocket_type)
 FILE     : src/item.cpp
 LINE     : 1050

---

 DEBUG    : in modifier for entry within breaks_into for vpart electrothermal_arc_cannon_part: tried to set ammo for plastic_chunk which does not have ammo or a magazine

 FUNCTION : void Item_modifier::modify(item &, const std::string &) const
 FILE     : src/item_group.cpp
 LINE     : 448

This works fine previously, and occur after upgrade to the latest experimental

# Steps To Reproduce

1. ~~use my save~~  Just create and use use a brand new character
1. Try open the latest mac experimental 11157

[阿加德-11-15.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5542102/-11-15.zip)

# Versions and configuration
 - OS: MacOS
 - Game Version: E.11157
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: ["dda", "no_npc_food", "Arcana", "blazeindustries", "crt_expansion", "aftershock", "magiclysm", "alt_map_key", "MMA"]

# Additional

I know this is probably a JSON error instead of a cpp error, but from the error message, I don't know which JSON I can investigate to fix, and why should that JSON to be changed...

**Comment by ZhilkinSerg** [comment]
`electrothermal_arc_cannon_part` is not from vanilla or any in-repo mods.

**Comment by ZhilkinSerg** [comment]
Flintlock pouch issue is probably from a third party mod either - e.g. custom profession tries to put 30 pcs to a pouch while it can only hold 14.

**Comment by linonetwo** [comment]
Got it, I will try search it inside this repo next time!
