### ISSUE TITLE
Unable to play games on UPS powered devices

### ISSUE THREAD

**Issue by Entity-y** [CleverRaven/Cataclysm-DDA#45443]
# Describe the bug
Converting any gaming device to UPS powered will prevent the gaming function, generating a message saying the batteries are dead.

# Steps To Reproduce
1. Get any laptop or gaming device
2. Convert to UPS powered and get a charged UPS
3. Try to play a game

# Expected behavior
Should be able to play games on UPS powered device so long as you have a charged UPS.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-7560-g165a25c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Shard's Additions [shardstuff],
    Gun Cotton [guncotton],
    Graphical Overmap [Graphical_Overmap],
    MSX Indicators: REMIX [UDP_REMIX_INDICATORS],
    Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Whaleys Hair Mod (UDP Tweaks) [WHALEYHAIR_UDP]
]

**Comment by andrei8l** [comment]
UPS interactions almost always need some kind of hack unfortunately. Quick fix:
```diff
diff --git a/src/activity_handlers.cpp b/src/activity_handlers.cpp
index 6a70b6264a..c793ccf989 100644
--- a/src/activity_handlers.cpp
+++ b/src/activity_handlers.cpp
@@ -1802,11 +1802,15 @@ void activity_handlers::game_do_turn( player_activity *act, player *p )
 
     //Deduct 1 battery charge for every minute spent playing
     if( calendar::once_every( 1_minutes ) ) {
-        game_item.ammo_consume( 1, p->pos() );
+        if( game_item.has_flag( flag_USE_UPS ) ) {
+            p->use_charges( itype_UPS, 1 );
+        } else {
+            game_item.ammo_consume( 1, p->pos() );
+        }
         //1 points/min, almost 2 hours to fill
         p->add_morale( MORALE_GAME, 1, 100 );
     }
-    if( game_item.ammo_remaining() == 0 ) {
+    if( game_item.units_remaining( *p ) == 0 ) {
         act->moves_left = 0;
         add_msg( m_info, _( "The %s runs out of batteries." ), game_item.tname() );
     }
diff --git a/src/iuse.cpp b/src/iuse.cpp
index 1ab1ea97b2..2d078fccff 100644
--- a/src/iuse.cpp
+++ b/src/iuse.cpp
@@ -4551,7 +4551,7 @@ int iuse::portable_game( player *p, item *it, bool active, const tripoint & )
     if( p->has_trait( trait_ILLITERATE ) ) {
         p->add_msg_if_player( m_info, _( "You're illiterate!" ) );
         return 0;
-    } else if( it->ammo_remaining() < 15 ) {
+    } else if( it->units_remaining( *p ) < 15 ) {
         p->add_msg_if_player( m_info, _( "The %s's batteries are dead." ), it->tname() );
         return 0;
     } else {
```
didn't test much
