### ISSUE TITLE
Last line in pickup menu is partially covered

### ISSUE THREAD

**Issue by Kelenius** [CleverRaven/Cataclysm-DDA#45452]
# Describe the bug

Last line in pickup menu is partially covered if the list is sufficiently long

# Steps To Reproduce

1. Gather a lot of items in a pile
2. Examine it

# Screenshots

![image](https://user-images.githubusercontent.com/6681708/99245467-abb2a280-2814-11eb-8a53-9a747307d127.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-7560-g165a25c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Generic Guns [generic_guns],
    No Fungal Monsters [No_Fungi],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

#45377

**Comment by Pupsi-Mupsi** [comment]
You are right. @anothersimulacrum has already fixed that in #45439.
