### ISSUE TITLE
Writing utensils and journals

### ISSUE THREAD

**Issue by Entity-y** [CleverRaven/Cataclysm-DDA#45459]
# Is your feature request related to a problem? Please describe.
Writing on an item is a good way to keep your gear organized but not so great at organizing thoughts or making tasks lists.

# Describe the solution you'd like
Journals added to the item pool along with pencils and new types of pens and markers.

# Describe alternatives you've considered

- The journal would open up a multi paged interface with the amount of paper inside dictating how many pages are available for writing in

- Individual pages could be ripped out or have new pages added with pieces of paper

- Larger font sizes reduce the character capacity of a page

- Different writing utensils produce different font

- ### **Charcoal being bold and the largest font size of the lot**

- Markers could either be fine tipped or **bold and have a larger font size** than pens and pencils

- _Fancy pens write in italicized_

- **_Calligraphy pens write bold and italicized at a slightly larger font_**

- Varying colored markers, pens, and pencils to produce different font colors

- Multicolor pen to have several colors available at the tip of your thumb

- Highlighter to change the backdrop of characters

- Art kit added to the item pool that contains all of the colored pencils, charcoal, and different types of markers and pens

- Activating the art kit would prompt what style and color of font you want to use for writing in a journal or on anything else

- Notepad function on a laptop with complete font customization

**Comment by natsirt721** [comment]
I'd be satisfied with a way to keep daily notes, regardless of font, hilighting, and color details. That adds a nice touch of 'situation' to using a notebook, but might run into issues (namely with varying font size - pretty sure that isn't going to work any way you spin it).

**Comment by ZhilkinSerg** [comment]
No font changes are feasible in curses.

**Comment by Entity-y** [comment]
I could see different colored font still being feasible, adding flavor to notes and making labels stand out in the inventory.

**Comment by GGgatherer** [comment]
Journals, heh. For now, I'd be glad if we could at least [make different notes on pieces of paper](https://github.com/CleverRaven/Cataclysm-DDA/issues/42505) instead of just one (barring dropping papers on different tiles)

**Comment by dchieh222** [comment]
Journals should allow you to remember more of the map while you were holding them. That seems like it should be possible. 

I would like other notes to be possible as well.

**Comment by kevingranade** [comment]
Map memory limits are a performance issue, to increase it meaningfully you need to address that.

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
