### ISSUE TITLE
[0.9-707-g0666f92] Cooked meat remained hot indefinitely.

### ISSUE THREAD

**Issue by tsuma534** [CleverRaven/Cataclysm-DDA#4546]
Yesterday, when I had cooked a few chunks of meat, the ones I haven't eaten remained hot on the next day. When those finally rotted they were still hot, and when I checked my garbage heap on the next day they remained so.
Unfortunately I don't know what triggered the bug. The next cooked batch, cooled down like usual.

This occured at Windows XP, curses version.
I was cooking using fire surrounded by rocks.

**Comment by mugling** [comment]
Closed as approaching 6 months without confirmation
