### ISSUE TITLE
<Android> Game crashes when finishing character creation

### ISSUE THREAD

**Issue by JaxMutt** [CleverRaven/Cataclysm-DDA#45484]
Game version: 11153 and 11150

Operating system: Android arm64

Tiles or curses: Tiles

Mods active: non

Every time I go to thr "Description" tab in character creation it will immediately crash, I tried reinstalling and still get the same problem, any way known to fix this?

**Comment by Zireael07** [comment]
Duplicate of #45312. It's already fixed, but I guess there's no Android build with the fix out yet?

**Comment by ZhilkinSerg** [comment]
It is resolved in 11158.

**Comment by JaxMutt** [comment]
> It is resolved in 11158.

Where can I find it?
the latest android build I saw on the Experimental Releases page is 11153

**Comment by JaxMutt** [comment]
> Duplicate of #45312. It's already fixed, but I guess there's no Android build with the fix out yet?

changed the terminal width to 95 and it's now working, thanks!
