### ISSUE TITLE
Firearm repair kit should act as a soldering iron

### ISSUE THREAD

**Issue by Scintile** [CleverRaven/Cataclysm-DDA#45486]
# Is your feature request related to a problem? Please describe.
You need a soldering iron to make a firearm repair kit (as a component, not as a tool), so i think you should be able to use charged firearm repair kit to do things like disassemble certain objects, craft electronics and in general use it instead of a regular soldering iron

# Describe the solution you'd like
When a soldering kit is required have an option to use firearm repair kit

# Describe alternatives you've considered
Leaving everything as is

# Additional context
From its description it seems that firearm repair kit is like an old toolbox - just a container with tools, so it should be possible to use soldering iron separately (Because it uses medium batteries and soldering iron uses light (and soldering iron being the only tool in the kit that uses power) i think we should add a Medium battery mod to the list of components required to make a repair kit. Or something like a power converter/some solder and wires)

**Comment by leemuar** [comment]
I agree on making Firearm repair kit usable as soldering iron though, nice idea!

I think we should not include Medium battery as a required component for Firearm repair kit. We are making a toolbox - a box with some tools in it. The box also have room to install replaceable medium battery. But it should be possible to craft the box without battery, just place soldering iron in the box without any batteries and swap batteries when you need to.

**Comment by Scintile** [comment]
Well, i think something like a medium battery mod or some basic stuff like solder is needed because you are not making a simple toolbox - you also switch soldering iron from taking small batteries to big ones

**Comment by PaulBlay** [comment]
On the subject of battery use - the Firearm repair kit uses 100 charges when you (a)ctivate it to cut metal. (Experimental 11142). 

I think all you are actually doing is opening the box and taking out a hacksaw, so this seems rather unfair.

**Comment by leemuar** [comment]
> 
> 
> On the subject of battery use - the Firearm repair kit uses 100 charges when you (a)ctivate it to cut metal. (Experimental 11142).
> 
> I think all you are actually doing is opening the box and taking out a hacksaw, so this seems rather unfair.

Interesting! Im reviewing firearm kit now to figure out the fix

**Comment by anothersimulacrum** [comment]
The issue is `iuse::hacksaw`'s `return it->type->charges_to_use()`. There's isn't really an easy fix here without disabling powered hacksaws (which admittedly, I am not sure are used).

**Comment by PaulBlay** [comment]
The only powered component of the Firearms Repair Kit is the soldering iron. Do powered hacksaws even exist?

Is there any way to check for electronic tools with "SAW_M" or "SAW_M_FINE" ? I tried a quick grep, but there are tons of recipes that require it so it's hard to see which tools provide it.

**Comment by leemuar** [comment]
ok, I suggest to split problems to a different issues. We have:

- make firearm kit usable as soldering iron (current issue)
- think about why FK can be used to cut metal and fix it
- think about changing FK recipe and components

Those problems could be solved separately imho

**Comment by XygenSS** [comment]
why do they even have hacksaws, wrenches and chisels? Wrenches I can probably understand, but the other two don't make sense for me.

Also, would it make sense to require an empty toolbox in the crafting recipe? Current recipe implies that it's just a collection of tools.

**Comment by leemuar** [comment]
> Also, would it make sense to require an empty toolbox in the crafting recipe?

Yes, I think so too! I would make much more sense to have a toolbox you can put the tools and the battery in

**Comment by Scintile** [comment]
About tools in the kit - I would leave everything as is, but change wrench for pliers and add a metal fileset

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
