### ISSUE TITLE
Wearing Leather Armor Gauntlets subtracts warmth from my hands.

### ISSUE THREAD

**Issue by Rjtheperson** [CleverRaven/Cataclysm-DDA#45482]
# Describe the bug

As stated in the title, wearing these gloves has reduced the warmth of my hands. From +22 to -45.

# Steps To Reproduce

1. Get leather armor gauntlets.
2. Wear gauntlets.
3. Hands are now colder than without gauntlets.

# Expected behavior
 
Hands become warmer

# Screenshots
Putting gauntlets on
![image](https://user-images.githubusercontent.com/65632694/99472902-6a96bd00-28fe-11eb-8ba9-9f6bd39768b3.png)
Taking gauntlets off
![image](https://user-images.githubusercontent.com/65632694/99472937-7b473300-28fe-11eb-842d-a00b63268caa.png)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 7 Professional 
- Game Version: 0.E-7587-g8d87f15 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    No Rail Stations [No_Rail_Stations],
    Graphical Overmap [Graphical_Overmap],
    Mythical Martial Arts [MMA]
]

# Additional context

The gauntlets are ++ reinforced 

Save file included:

[Hershey.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5557277/Hershey.zip)

**Comment by anothersimulacrum** [comment]
I can reproduce it.

**Comment by andrei8l** [comment]
Looks like you're losing the bonus warmth from the pockets of the winter survivor suit when you put on the gauntlets. Not sure if this is a bug or just poor feedback. Relevant code is at `character.cpp:6511-6524`

**Comment by anothersimulacrum** [comment]
Ah, I see. Yes, probably separate.
I'm not sure where this is between bug or communication failure either.
I think some sort of communication on clothing pockets/hoods/collars in general would be good, and that would address the communication part of this issue at least.

**Comment by hexagonrecursion** [comment]
I am observing something strange: in the above save hand warmth oscillates between -45 and +40 when I pass turns. Taking off the pair of leather armor gauntlets causes warmth to stabilize at +22. I could not reproduce the oscillation in a fresh save file even with all the same mods.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 2970a2f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    No Rail Stations [No_Rail_Stations],
    Graphical Overmap [Graphical_Overmap],
    Mythical Martial Arts [MMA]
]

**Comment by Maleclypse** [comment]
Could not be reproduced in fresh save.
