### ISSUE TITLE
-2000 warmth on some NPC limbs, those limbs are broken.

### ISSUE THREAD

**Issue by freijie** [CleverRaven/Cataclysm-DDA#45483]
Previously healthy NPC got -2000 warmth on several limbs, those limbs are broken.

After checking why NPC didnt follow 'deconstruct vehicle' directive(may be unrelated) after disassembling single tile, noticed abnormal negative warmth on NPC limbs, those limbs were broken. Temperature at the moment of screenshot was 11*C.

# Steps To Reproduce

Unfortunately I don't know when it happened and how to reproduce it.

# Expected behavior

Healthy NPC

# Screenshots
![изображение](https://user-images.githubusercontent.com/25095102/99503703-944bf480-298f-11eb-8052-dae023444960.png)
![изображение](https://user-images.githubusercontent.com/25095102/99504060-0b818880-2990-11eb-87dd-33ac35b5dfa5.png)

# Versions and configuration
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5558713/debug.log)
Cataclysm DDA version 0.E-7557-g64b8950 tiles
Windows 10
Save:
[Northern Tyris.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5558720/Northern.Tyris.zip)

**Comment by BrettDong** [comment]
I think this is the symptom of red cells anaemia: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/player_hardcoded_effects.cpp#L1009

**Comment by I-am-Erk** [comment]
Closing as stale unless this can be confirmed as glitchy behaviour
