### ISSUE TITLE
NPC performance (EPIC)

### ISSUE THREAD

**Issue by Aivean** [CleverRaven/Cataclysm-DDA#45497]
Game is slow when there are multiple NPCs around.  
This is an aggregate issue (EPIC) to track all npc-related performance improvements.

Related issues:
* #42899
* #27159

### Baseline: Experimental build from Nov 13

Waiting Hub 01: 
![image](https://user-images.githubusercontent.com/2865203/99615023-8ddd6d00-29cf-11eb-84d8-e4e02202af44.png)

Refugee Center
![image](https://user-images.githubusercontent.com/2865203/99615145-bd8c7500-29cf-11eb-994b-20d368a10476.png)

**Comment by Aivean** [comment]
After:
* #45423
* #45424
* #45444
* #45445
* #45446
* #45461
* #45462
* #45463
* #45346
* #45426
* #45481 

Hub01:
![image](https://user-images.githubusercontent.com/2865203/99615642-9e421780-29d0-11eb-8937-70b47b0b224f.png)

≈42% speedup from baseline

**Comment by Aivean** [comment]
After:  #45491 

![image](https://user-images.githubusercontent.com/2865203/99615747-ccbff280-29d0-11eb-9bf4-cd344140fcac.png)

≈60% speedup from baseline

**Comment by AnonimusC** [comment]
semi-top(offtop?):
About the game code - i found a good [CDDA analysis via PVS-Studio](https://habr.com/ru/company/pvs-studio/blog/449472/), can it help at some way? More globally than this problem. (original link: https://habr.com/ru/company/pvs-studio/blog/449472/ )

**Comment by Zireael07** [comment]
@AnonimusC: Those are related to code quality, not speed. AND most if not all of those have already been fixed.

**Comment by Aivean** [comment]
@AnonimusC , ZhilkinSerg commented on the original article and I think he regularly uses PVS-studio or similar static analysis tool to find and fix such issues.

**Comment by AnonimusC** [comment]
@Zireael07, @Aivean
 Impressive; didn't notice his comment, thank you.

**Comment by Night-Pryanik** [comment]
No need to have this issue in the tracker.
