### ISSUE TITLE
[Balance] Basecamp hunting yield lowers over time, yields more mutant meat as catacylsm progresses

### ISSUE THREAD

**Issue by dissociativity** [CleverRaven/Cataclysm-DDA#45499]
# Is your feature request related to a problem? Please describe.
I can't do the coding myself but know enough that this would be fairly simple.
Basecamps yield reliable hunting/fishing stock, your camp would naturally deplete the wildlife, hunting should be something one only does heavily when starting the base or you'd deplete the wildlife completely

# Describe the solution you'd like
A starting value of 100% hunting viability, decreasing every time you have NPCs go off on hunts, with an increasing chance of both failure to find anything or lower yeilds as the number decreases, simulating depleted wildlife.

The yields contain more of a % of mutant meat as time after catacylsm progresses, and hunting gets a tad more dangerous for said NPCs over time.
Add option to tell NPCs to not hunt mutants so that you only get the lower yield of more viable meat from non-mutant animals, this takes long as the NPC is trying to avoid mutant animals in theory, but is less risky that hunting mutant animals as well.

# Describe alternatives you've considered
Just nerf base camp hunting output I suppose to make it a less sustainable source of food, increase reliance on agriculture, we invented it for a reason after all.

**Comment by Fosheze** [comment]
You could probably adapt the fishing system to this. Just have each wild animal/mutant animal have a wildlife "pool" that your hunters can hunt from (i.e. just generate corpses like with fishing). As the actual animals deplete/mutate then so would the hunting yields.

**Comment by PatrikLundell** [comment]
The same logic ought to apply for foraging. Once you've combed an area for things it will take a fair while for regrowth to replenish resources, resulting in gradually lower amounts of resources gathered over time as the foragers have to go further and further away, eventually reaching an balance point where resources have been replenished enough in the area first covered to allow a second harvest (which still have lower yields than on the first pass). I suspect forageables (I don't think there is such a word) could have pools as well, in the manner suggested by Fosheze.

A very long term solution would be to have companions have their own reality bubbles in which they could forage, fish, hunt, patrol, etc. using the same resources the PC would encounter (the PC going to kill that moose that is loitering in "that" area may find that it's already been hunted and killed by the companions, for instance).

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
