### ISSUE TITLE
(E)ating with *favorited* items in inventory brings a warning about eating said items.

### ISSUE THREAD

**Issue by morthein** [CleverRaven/Cataclysm-DDA#45509]
# Describe the bug

Updating to version 11170 and playing a previous save threw up a prompt, when attempting to eat, asking if I wanted to eat suchandsuch item. It also prompted for every other item that was in my favorites before opening the Eating menu of nearby food.

# Steps To Reproduce

1. Find any couple of tools.
2. flag them as favorites in your inventory.
3. Using the (E)at function near food.

# Expected behavior

Things that are not in your favorites work fine, but tools that are, are flagged as food also somehow.

# Screenshots

![what](https://user-images.githubusercontent.com/50846380/99716662-62fa2400-2a76-11eb-8b20-0dfad430e12a.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-7619-g4f7bfb5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Alternative Map Key [alt_map_key],
    Cataclysm++ [Cata++],
    Crazy Cataclysm [crazy_cataclysm],
    No Rail Stations [No_Rail_Stations],
    Cars to Wrecks [cars_to_wrecks],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Cataclysm++ - UndeadPeople Tileset [Cata++UDP],
    Crazy Cataclysm - UndeadPeople Tileset [CrazyCataclysmUDP],
    Graphical Overmap [Graphical_Overmap],
    Mutation Changes [Mutation_Changes],
    Mutation Changes - UndeadPeople Tileset [Mutation_ChangesUDP],
    No Fungal Monsters [No_Fungi],
    Bionic Slots [cbm_slots],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]

**Comment by Fris0uman** [comment]
Very likely caused by #45196
Should not be too hard to fix

**Comment by Pyritefoolsgold** [comment]
I wanted to add that in my issue, I was also able to cause a crash by favoriting a protein ration. That might be worth looking into separately.
