### ISSUE TITLE
No can has cheeseburger with brioche bun!

### ISSUE THREAD

**Issue by Pyritefoolsgold** [CleverRaven/Cataclysm-DDA#45501]
# Describe the bug

A hamburger can be made with a brioche bun, but mysteriously a cheeseburger cannot. I can't think of a good reason for this.

# Steps To Reproduce

1: Get a character with food handling 3
2: Open the craft menu and search for 'burger'.
3: Observe the recipes for hamburger and cheeseburger and note that brioche is not allowed for cheeseburger. If necessary, spawn all other necessary ingredients as well as brioche and note that you cannot craft a cheeseburger.

# Expected behavior

A cheeseburger should have exactly the same recipe as a hamburger, plus a piece of cheese.

# Screenshots

![NoCanHasCheezeburger](https://user-images.githubusercontent.com/9997796/99630380-a315c400-29ee-11eb-9b14-1e6f81f6b3bb.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-7590-g6c46204 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key]

# Additional context

Because of this issue I cannot has cheeseburger.

**Comment by leemuar** [comment]
Nice find! Fixed it for you

**Comment by Pyritefoolsgold** [comment]
Thank you! Looking back over at the recipes, I see that lettuce is a valid ingredient for Cheeseburgers but not hamburgers. Could that be folded in too unless there's somehow a good reason for it?

**Comment by leemuar** [comment]
> 
> 
> Thank you! Looking back over at the recipes, I see that lettuce is a valid ingredient for Cheeseburgers but not hamburgers. Could that be folded in too unless there's somehow a good reason for it?

Yes, chef! Right away, chef!
Added lettuce and irradiated lettuce as hamburger components just like in cheeseburger recipe
