### ISSUE TITLE
Pulling shopping cart leaves a trail of its icon, at night or in the dark, outside the range of vision. Daylight removes trail. Using Terminal

### ISSUE THREAD

**Issue by dihaskins** [CleverRaven/Cataclysm-DDA#45517]
At night, or in any dark area, pulling the shopping cart leaves a trail of its icon outside the range of current vision. Daylight seems to remove this trail.

# Steps To Reproduce

At night Grab a shopping cart and walk in any direction.  Outside the short range of night vision, a trail of the icon for the shopping cart remains on every location that it was pulled through. Walking back through the trail at night will make the portion in your vision range go away until it leaves the vision area again, then the trails return. Daylight seems to remove the trails permanently.

# Expected behavior
The shopping cart should not leave a trail everywhere that it has bin that is visible outside the range of current vision.

# Screenshots
![Screenshot from 2020-11-19 18-53-45](https://user-images.githubusercontent.com/74750850/99754266-e464ad00-2a9c-11eb-820d-f07eac352df5.png)

# Versions and configuration

 - OS:  SMP Debian 4.19.152-1 (2020-10-18)
 - Game Version:  Cataclysm DDA version 0.E-7640-gc764d46aac [64-bit]
 - Graphics version: Terminal
 - Ingame language: English
 - Mods loaded: none

**Comment by Christer2222** [comment]
This also applies to pulling furniture. Tried it with a bookcase.

**Comment by GGgatherer** [comment]
Very old issue, the problem being tile where dragged item was before dragging isn't visible from the new character's position.

**Comment by Night-Pryanik** [comment]
This looks like a resurrection of #28512, this time on curses.

**Comment by Cimanyd0** [comment]
I still have #28512 happen in tiles as well.

**Comment by actual-nh** [comment]
@Night-Pryanik: This would appear to have been confirmed (now).
