### ISSUE TITLE
Dark skies above deletes scenarios

### ISSUE THREAD

**Issue by Demonheim** [CleverRaven/Cataclysm-DDA#45510]
# Describe the bug

Dark skies above deletes scenarios

the original issue remains that it deletes scenarios however.

# Steps To Reproduce

Simply adding the mod with dda, disable npc needs, bionic professions, blaze industries and crit expansion causes this issue.

# Expected behavior

expected the game to work

# Screenshots

![Screenshot_13](https://user-images.githubusercontent.com/42292405/99718977-52937a80-2a71-11eb-8edb-8e1b593d8d14.png)
![Screenshot_14](https://user-images.githubusercontent.com/42292405/99719029-650db400-2a71-11eb-9cbf-d2cd81e7910b.png)
![Screenshot_15](https://user-images.githubusercontent.com/42292405/99719040-6a6afe80-2a71-11eb-9534-8f5b380cb50a.png)
![Screenshot_16](https://user-images.githubusercontent.com/42292405/99719043-6ccd5880-2a71-11eb-925d-622a7fc8a91b.png)

Do not take a screenshot of the crashing window. Please provide the crash logs in the "Additional context" -->

# Versions and configuration

do not have a generate game report under debug.

 - OS: win 10
 - Game Version: 0.E-7619-g4f7bfb5 (tiles)
 - Graphics version: tiles
 - Ingame language: english
 - Mods loaded: dda, disable npc needs, bionic professions, blaze industries, crit expansion, dark skies above

# Additional context

Also corrupts the game as in creating a new world crashes the world loading upon creating a new character even without dark skies above mod but i havent been able to replicate it because it is colliding with a mod and I am not sure which one. sometimes having it and another mod I have not been able to find crashes the launcher as well.

**Comment by ZhilkinSerg** [comment]
Mods blacklisting/whitelisting certain scenarios (and other game entities) is intended and valid behavior.

**Comment by Fris0uman** [comment]
To expand a bit on what Zhilk said Dark Skies Above as a short whitelist of scenarios: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/mods/Dark-Skies-Above/blacklists/scenario_blacklist.json and black list the rest. It's not a bug it's intended behaviour as part of the design of the mod. I think there's no CBM in this mod lore so it make sense to remove the cbm scenarios.
