### ISSUE TITLE
Crash on dropping newly cooked food

### ISSUE THREAD

**Issue by Christer2222** [CleverRaven/Cataclysm-DDA#45519]
# Describe the bug
Crash after I dropped some newly cooked food in a fridge with other food items. 
I struggled to get a fire going, but eventually was able to. 
I also had recently dumped some water into a bathtub and tried to pick it up again through the 1st option.

# Steps To Reproduce
Was not able to reproduce.

# Versions and configuration

 - OS:  Windows 10
 - Game Version: 0.E-7619-g4f7bfb5 (tiles)
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: dda, disable npc needs, bionic professions

# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5571339/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5571340/debug.log)
[Long.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5571345/Long.zip)

**Comment by int-ua** [comment]
Looks like there is no useful info in logs. Please comment if you still experience this issue and I'll reopen.
