### ISSUE TITLE
Rear door shapes backwards in diagram

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#45520]
# Describe the bug
When installing vehicle door (only checked basic door) the Rear Left and Rear Right are swapped (compare to front)

# Steps To Reproduce

Try to install a car door
When it asks what shape, check the pics

# Expected behavior

The shapes should be correct

# Screenshots

![image](https://user-images.githubusercontent.com/12039454/99768320-682c9280-2ab9-11eb-91da-037761054f73.png)

Red = bad
Green = good
(Presumably)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-7590-g6c46204 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    Stats Through Kills [stats_through_kills]
]

# Additional context
Don't know if it affects any tile sets or just the gui
Don't know if it affects any other door types like heavy or opaque

**Comment by wapcaplet** [comment]
Still reproducible in 0.E-9603-g42468f6cab
