### ISSUE TITLE
Smoked Sausage recipe tweaks

### ISSUE THREAD

**Issue by AirRice** [CleverRaven/Cataclysm-DDA#45528]
<h2>Description of Issue</h2>
A "raw sausage" (<b>sausage_raw</b> in json) can not be smoked into a "smoked sausage" (<b>sausage</b> in json) via a constructed smoking rack. Furthermore there is no recipe to turn a raw sausage into a smoked sausage at all. This goes against the recipe's description which indicates that it has been "prepared for smoking", despite there being no way to do so.

<h2>Describe the solution you'd like</h2>
Being able to insert a "raw sausage" item into a constructed smoking rack and receive a smoked sausage after the smoking process is complete. In addition, a separate "smoked sausage" recipe where you can simply take a raw sausage and smoke it using a charcoal smoker or equivalent should be added.

<h2>Describe alternatives you've considered</h2>
Leave the current system as is.

<h2>Additional context</h2>
There is an argument to be made that the current "raw sausage" does not seem to have any casing on it which implies it is a skinless sausage. For the most part it seems like it is merely just a mush of tallow, meat and spices molded into a somewhat sausage-like shape. Although, if that was the case, it should still be possible to make a smoked sausage since the smoked sausage recipe requires the same ingredients as the raw sausage, only it is smoked during creation.

In addition, "wasteland sausage" recipes exist that can be smoked from a raw state (did not test constructed smoking racks), so perhaps this change is unnecessary.

<h4>Current recipe for raw sausage</h4>
<img src="https://user-images.githubusercontent.com/13725542/99798120-559d7200-2b28-11eb-87ae-6f1602bd7237.png">
<h4>Current recipe for smoked sausage</h4>
<img src="https://user-images.githubusercontent.com/13725542/99798144-5fbf7080-2b28-11eb-8f54-6f1302c8d2ec.png">

**Comment by Scorch-Mechanic** [comment]
Er, what? I've made hundreds of smoked sausages by preparing "raw sausage" and then examining a smoking rack, inserting the raw sausages, and smoking them for six hours. Granted I haven't done that on the extremely most recent version, but it worked quite recently. Am I reading your bug report wrong?

**Comment by AirRice** [comment]
@Scorch-Mechanic I went into debug mode on the newest build on the default mod values, and you're right. I have no idea why it didn't work during my playthrough recently but regardless, it seems to work as intended and there are no further problems.
I guess this issue can be closed, my bad for not testing it more thoroughly the first time.
