### ISSUE TITLE
Defuse hostile NPCs

### ISSUE THREAD

**Issue by Entity-y** [CleverRaven/Cataclysm-DDA#45544]
# Is your feature request related to a problem? Please describe.
Missing a speech check can ruin the acquisition of a potential follower, turning them instead hostile. Getting caught stealing could also turn into a huge battle with the faction.

# Describe the solution you'd like
With higher speech comes the ability to calm a hostile npc down to be able to speak to them in a civilized manner once again.

# Describe alternatives you've considered
Making chloroform and other tranquilizers craftable.

The ability to use unarmed attacks to knock out and tie up npcs with rope to negotiate peace.

Pacifying bandits to become allies. 

Really high speech could calm a feral human to fight with you for a set duration before ultimately becoming a zombie.

# Additional context
If countless hours of playing Metal Gear has taught me anything it's that lethal force isn't the only option, or even the best one. The man builds an army through capturing his enemies.

**Comment by Vzor-** [comment]
I also think a bandit would be a lot more willing to talk if he was heavily injured (and you are not).

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
