### ISSUE TITLE
Font handling broke between b11164 and b11177

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#45546]
# Describe the bug

Game ignores `config/fontlist.txt` and instead searches font by its name in `config/fonts.txt`. Win64x problem, maybe others, didn't test.
It is not a problem with my config - I'm using the launcher so I compared it to previous_version and they are exactly the same.

# Steps To Reproduce

Use `"typeface": "Consolas"` in your `config/fonts.txt`. There's an entry for it in `config/fontlist.txt`: 

    Consolas
    C:\Windows\fonts/consola.ttf

Start the game, see it using default font. Look in the debug.log and see

    (continued from above) ERROR : src/sdl_font.cpp:258: Not found ./font/Consolas.ttf
    12:30:46.020 ERROR SDL : src/sdl_font.cpp:258: Not found Consolas.ttf
    12:30:46.020 ERROR SDL : src/sdl_font.cpp:258: Not found data/font/Consolas.ttf
    12:30:46.020 ERROR SDL : src/sdl_font.cpp:258: Not found Consolas.ttf
    12:30:46.020 ERROR SDL : src/sdl_font.cpp:258: Not found C:\Windows\fonts\Consolas.ttf

# Expected behavior

Game using the font it was using previously without errors.

# Versions and configuration

- OS: Windows 7x64
- Game Version: 0.E-7674-gd4a0263 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills],
    Bionic Professions [package_bionic_professions],
    Ultica cursor replacement [ultest],
    Hauling space revived [hspace]
]

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5577080/debug.log)

**Comment by anothersimulacrum** [comment]
#45319 removed support for fontlist.txt
Where is your consola.ttf font file on your system? It doesn't appear to be in one of the places being searched.

**Comment by anothersimulacrum** [comment]
Ah, nevermind. Your fix would be to change `Consolas` to `consola` in your `config/fonts.json`.
I'm going to close this issue as resolved, but if you have anything more that you think deserves examination or think it should be reopened, please let me know.
