### ISSUE TITLE
Items with relic_data don't stack

### ISSUE THREAD

**Issue by MikuMiddo** [CleverRaven/Cataclysm-DDA#45542]
# Describe the bug
Usually,the completly same item(same attributes) will stack together to save the looking-space of invertory.
but now,if the item has a relic_data,It will be showen one by one in your invertory,even if they have the same attributes

If you have 20 strenght-ring in your pockets,in the past,it will show '20 strenght-rings'in one line,but now,it will show 'strenght-ring' for 20 lines,it makes the invertory menu ugly and hard to use.

# Steps To Reproduce
1.debug for 30 strenght-ring(with Magiclysm mod)
2.open [i]nvertory menu.

# Expected behavior
They should stack together again.

# Screenshots
![image](https://user-images.githubusercontent.com/53809752/99864141-ba1a0900-2bdc-11eb-99ab-1cd05eb11a00.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-7642-gac49e40 [64-bit]
- Graphics Version: Tiles
- Game Language: 系统语言 []
- Mods loaded: [
    浩劫余生 [dda],
    禁用NPC需求 [no_npc_food],
    C.R.I.T 扩展 [crt_expansion],
    Blaze 载具工业 [blazeindustries],
    大魔法 [magiclysm],
    余波未尽 [aftershock],
    恐龙世界 [DinoMod],
    Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
    疯狂大灾变 [crazy_cataclysm],
    神话武术 [MMA],
    移除真菌类怪物 [No_Fungi],
    Fuji的军事职业Mod [fuji_mpp],
    技能提升属性 [StatsThroughSkills],
    敏捷速度加成 [speedydex],
    杀怪提升属性 [stats_through_kills],
    余震个人用强化模组 [After_Shock_Personal_UsageMod],
    坦克mod:复活 [Tankmod_Revived],
    阻止僵尸复活 [no_reviving_zombies_fix],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    DinoMod - UndeadPeople Tileset [DinoModUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP],
    Tankmod: Revived - UndeadPeople Tileset [Tankmod_RevivedUDP],
    Crazy Cataclysm - UndeadPeople Tileset [CrazyCataclysmUDP]
]

# Additional context

**Comment by anothersimulacrum** [comment]
Should probably be replaced with `is_relic() && *relic_data == *rhs.relic_data`.
The relic datum might need an equality operator or other way to check equality implemented. 
https://github.com/CleverRaven/Cataclysm-DDA/blob/d4a0263c47860e87a298b9d0ae7eed3c7b6a2646/src/item.cpp#L948

(C.C. @KorGgenT if this solution sounds correct)

**Comment by KorGgenT** [comment]
i agree. possibly we want items that have relic charges to still not stack, but i can also see a reason to have them still stack

**Comment by Fris0uman** [comment]
Yeah i just put the is_relic() check because I though relic were unique.

**Comment by Maleclypse** [comment]
I know that previously when they stacked it caused the procedurally generated relics once stacked to be identical in effects.
