### ISSUE TITLE
Hide/show container's content in inventory view

### ISSUE THREAD

**Issue by Salty-Panda** [CleverRaven/Cataclysm-DDA#45553]
# Is your feature request related to a problem? Please describe.

Before the nested containers update, we could group certain tools with qualities into one item with more qualities (toolbox).
Now we can manually put certain tools into a container but it's a play-pretend and doing that causes a mess in inventory view.

# Describe the solution you'd like
Keybinding to show/hide container's content in inventory and drop view - things inside TOOLBAG wouldn't be displayed (the way how it works for containers in advanced inventory/pickup view):
![image](https://user-images.githubusercontent.com/26396019/99880062-59f18a00-2c11-11eb-997b-cc8ad49b58dd.png)
It would help with medicine-dedicated containers too, I always carry certain meds and bandages but inventory view shuffles them with random `DRUGS` I looted.

# Describe alternatives you've considered
Option to bind items in a container and the container into a single piece:

- Its content wouldn't be displayed
- It could be `a`ctivated to enter activation menu where we would only see its content. Basically the way tool belt, survivor's belt and toolbox used to work. 
- No item can be inserted or removed until unbinding.

![image](https://user-images.githubusercontent.com/26396019/99879197-77bbf080-2c0b-11eb-989d-71bd3841f780.png)

# Additional content
![image](https://user-images.githubusercontent.com/26396019/99880198-3bd85980-2c12-11eb-8244-c2c70c996d95.png)

**Comment by Entity-y** [comment]
I was just thinking about how nice that would be, having an inventory without 10 pages of stuff. My work around was to just rename my usual carry stuff to "my ..." then everything that I actually use is all stacked on top of each other in my inventory. It makes sorting after looting much smoother.

**Comment by RoyBerube** [comment]
Vormithrax was complaining about this exact issue not long ago. It would certainly help to reduce information overload for the player.

**Comment by sumpfralle** [comment]
I think, a partial solution for this problem (*looted* stuff vs. *preferred* stuff) is the *favorite* label, that can be attached to any item (keyboard shortcut *asterisk* in the inventory view). This label is respected by the *drop* and *multi-drop* activity. Thus it solves this specific problem nicely for me.

Maybe this is already sufficient for your use-case?

**Comment by I-am-Erk** [comment]
This got called to my attention and I think it's a great idea. I'd suggest that we have a "show hide" per container and also a "show/hide all containers" toggle. The individual container show/hide settings should be remembered when closing opening inventory, and show/hide all should *not* override individual settings.
