### ISSUE TITLE
Crafted disposable batteries coming out not charged

### ISSUE THREAD

**Issue by scraw-darkblade** [CleverRaven/Cataclysm-DDA#45551]
# Description 
Any batteries that are crafted coming out 0 charged therefore cannot be used. 

# Steps To Reproduce

1. Go to crafting screen (&) 
2. Select (Electric Tab) 
3. Craft any type of battery that is disposable. 
4. Result will come out as zero charge. 

# Expected behavior

Disposable batteries should come out as already charged. 

# Versions and configuration

- OS: Android
    - OS Version: Manufacturer: HUAWEI; Model: MRD-LX2; Release: 9; Incremental: 9.1.0.327C636; 
- Game Version: 0a99e86 [32-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by RoyBerube** [comment]
Unable to replicate the bug on the latest experimental build on Windows 64 bit. All the crafted disposable batteries start with a full charge.

**Comment by int-ua** [comment]
You may have had that impression when you were crafting near a table surface and the crafted item was placed at the table while you had a discharged battery in your inventory. Or it was a bug that may have been fixed. Please try reproducing the issue again and comment if it's still a problem.
