### ISSUE TITLE
A way to not add wildcards to the keyword while filtering

### ISSUE THREAD

**Issue by Salty-Panda** [CleverRaven/Cataclysm-DDA#45554]
# Is your feature request related to a problem? Please describe.
I want to see what I can make out of corn, so I filter by "corn" and see what? Recipes that include corn, or cornmeal, or corner.
I filter by "metal sawing" quality and also get recipes using "fine metal sawing".
It happens both in the crafting menu and inventory/pick up views.

# Describe the solution you'd like
To be able to enclose a phrase with `"` signs to only search for specific keyword

# Describe alternatives you've considered
More special characters (like `-` to ignore results matching the following keyword) and making filter in all views uniform, but I don't think those are needed as much.

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
