### ISSUE TITLE
NPCs in faction camp develop obesity

### ISSUE THREAD

**Issue by sumpfralle** [CleverRaven/Cataclysm-DDA#45557]
# Describe the bug

Two of the NPCs in my faction camp recently gained overweight (*obese* and *morbidly obese*).

I could imagine, that this is related to the abundant food storage of the camp (around 150 days).

I do not think, that #35494 is related (since I am not aware of a plant mutation).

# Expected behavior

NPCs should only eat as much as necessary. In a perfect world they would slowly move towards *normal* weight. But even just keeping their level of weight would be fine.

# Versions and configuration

 - OS: Debian testing
 - Game Version: 0.E-7667-g6bc3296
 - Graphics version: tiles
 - Ingame language: English
 - Mods loaded: default

# Additional context

[npc-camp-obesity.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5578186/npc-camp-obesity.zip)

**Comment by scraw-darkblade** [comment]
I will confirm that I experiencing this one as well.

- OS: Android
    - OS Version: Manufacturer: HUAWEI; Model: MRD-LX2; Release: 9; Incremental: 9.1.0.327C636; 
- Game Version: 0a99e86 [32-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by anothersimulacrum** [comment]
Save ([Cooke_City.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5578510/Cooke_City.zip)) from @scraw-darkblade

**Comment by misterprimus** [comment]
Truth in video games?

**Comment by sumpfralle** [comment]
btw: the first NPC, that joined my camp still has its original state of hunger (*very hungry*). All NPCs, which joined later show the hunger state *ERROR* (in the list of followers dialog (`#`)).

I do not know, whether this is related to the tendency towards obesity.

**Comment by anothersimulacrum** [comment]
Fixed by #47030
