### ISSUE TITLE
Dialogue missing stuff

### ISSUE THREAD

**Issue by CountAlex** [CleverRaven/Cataclysm-DDA#45567]
# Describe the bug
@I-am-Erk asked me to make this issue and point out a missing line of dialogue [here](https://github.com/CleverRaven/Cataclysm-DDA/blob/53bb2eb1a7c7b77e6a7fb1183f1606742b9bfedc/data/json/npcs/refugee_center/surface_refugees/NPC_Jenny_Forcette.json#L319)

# Steps To Reproduce
Check the dialogue file at the link.

**Comment by I-am-Erk** [comment]
Thanks, this will help me remember it when I am available to contribute again

**Comment by AnonimusC** [comment]
kinda like that
![image](https://user-images.githubusercontent.com/73962707/100125749-2b341780-2e8e-11eb-8716-a5b789b2962d.png)
