### ISSUE TITLE
Not able to finish "Find Antibiotics" NPC mission (does not accept re-named drugs?)

### ISSUE THREAD

**Issue by LordKaaven** [CleverRaven/Cataclysm-DDA#45562]
# Describe the bug

My starting spot NPC gave me a "find antibiotics" mission. After acquiring both varieties (broad- and narrow-spectrum antibiotics) and bringing those to the NPC, he reacts as if I still don't have what is necessary, making the quest not finishable.

# Steps To Reproduce

1. Re-start a new game (in basic shelter scenario) until the start NPC gives you the antibiotics quest 
2. Spawn both versions of the drug
3. Try and yet be unable to finish the quest

# Expected behavior

At least one of the two variants should be accepted. Broad-spectrum one probably, since the description makes it sound stronger.

# Versions and configuration

 - OS: Windows 7
 - Game Version: 0.E-7759-gf3a1933
 - Graphics version: Tiles
 - Mods loaded: disable NPC needs, bionic professions, blaze industries, no rail stations, no fungal monsters

# Additional context
On separate not, the naming scheme for antibiotics is pretty confusing. "Weaker <-> Stronger" or "Over-the-counter <-> Prescription" antibiotics would be much easier to recognize / understand.

**Comment by anothersimulacrum** [comment]
You need just `antibiotics`, the third variety. This mission should be expanded to accept more (it should at least accept broad-spectrum anti-biotics in addition) or clarified.

**Comment by LordKaaven** [comment]
Now, that's just silly. So there are both broad- and narrow-spectrum antibiotics on top of JUST antibiotics?

In this case, I would also ask to rename the simply antibiotics to fit with the naming scheme. "Mid-spectrum" or something like that, if that's even a thing irl. Cause right now, its like having "9mm bullets", "7.62mm bullets" and then just "bullets".

**Comment by ZhilkinSerg** [comment]
It has nothing to do with rename - it was broken even before that. Missions operate on an item id and "FInd Antifiotics" mission only accepts one specific item id (`antibiotics`).
