### ISSUE TITLE
Make sprite replacement mods work again

### ISSUE THREAD

**Issue by Olaroll** [CleverRaven/Cataclysm-DDA#45563]
# Is your feature request related to a problem? Please describe.
All sprite replacement mods no longer work correctly, as they used to. No sprites that already exist in the main tileset can be replaced by mods. The only way to modify existing tiles is to create an entirely separate tileset.

# Describe the solution you'd like
Sprites should be replaced correctly, as was the case in earlier experimental versions and 0.E stable.

See `Additional context` for a demo

# Describe alternatives you've considered
Abandoning support for sprite replacement mods.

I explained why that wouldn't be the best approach in a comment below, which I've now copied here:
>
>
>[...] The way I see it, sprite replacements are a big boon to the long-term health of all tilesets. The reason for this being that tileset mods are a great way to get acquainted with the game's tile system.
>
>A player who is unsatisfied with the way a certain tile looks may try to fix it themselves by creating a tileset mod. This would serve as their introduction to the game's graphics and basic JSON. From there, they might keep making tileset mods, help out the main tileset, or contribute JSON in other areas.
>
>In fact, I say this from experience, because that is exactly what happened to me. Essentially, I think it's similar to the Good First Issue label here. It serves as a good stepping stone to more contributing, and surely that's worth something, right?

In addition, there's also the benefit of being able to mix-and-match different tileset tweaks, as opposed to having an entirely separate tileset for every option.

# Additional context
As this was a bug report before, I'll leave the steps to reproduce and relevant image here:

1. [Make a world with this mod](https://github.com/CleverRaven/Cataclysm-DDA/files/5578764/SpriteReplacementTest.zip)
2. Make sure you are using Ultica, Chibi Ultica, UDP or MSXotto+
3. Note that the player skin sprite is offset to the right, as proof that the sprite replacement mod is set up correctly.
4. Note that the player skin has not been replaced with a test sprite

![Untitled](https://user-images.githubusercontent.com/13151772/99891635-bb971000-2c74-11eb-8b13-25a2b76b6fb6.png)
Both images were made with the exact same mod.

**Comment by Fris0uman** [comment]
So the wrong offset is not the bug? The bug is that your custom mod doesn't work?

**Comment by Fris0uman** [comment]
Just tried it using `sees_player_retro` mod and it doesn't show the sight indicator over monsters so it does seem busted for our mods too.

**Comment by Olaroll** [comment]
> 
> 
> So the wrong offset is not the bug? The bug is that your custom mod doesn't work?

Yes, the offset is there to verify that the mod is actually set up correctly. Otherwise, it would look just as if the mod was not active at all.



> 
> 
> Just tried it using `sees_player_retro` mod and it seems to work:

I'm not that familiar with the RetroDays tileset, but it seems to me that the `sees_player_retro` mod adds a **new** sprite. The problem specifically occurs when you try to **replace** a tile that is already set by the main tileset.

**Comment by Fris0uman** [comment]
> The problem specifically occurs when you try to replace a tile that is already set by the main tileset.

Sure but it seems that there's nothing in the repo doing that. So I think you'd have a better chance to get a fix by talking to people on the dev discord.

**Comment by Olaroll** [comment]
Fair enough, but I'd still hope the issue is considered at least. The way I see it, sprite replacements are a big boon to the long-term health of all tilesets. The reason for this being that tileset mods are a great way to get acquainted with the game's tile system.

A player who is unsatisfied with the way a certain tile looks may try to fix it themselves by creating a tileset mod. This would serve as their introduction to the game's graphics and basic JSON. From there, they might keep making tileset mods, help out the main tileset, or contribute JSON in other areas.

In fact, I say this from experience, because that is exactly what happened to me. Essentially, I think it's similar to the `Good First Issue` label here. It serves as a good stepping stone to more contributing, and surely that's worth something, right?

**Comment by Fris0uman** [comment]
I guess you could rephrase and re title your issue as a feature request instead of a bug report

**Comment by Zupercharged** [comment]
So for what its worth, I can confirm the specifics of this issue.

My mod uses the same additional tileset to both replace existing textures and add them to new items, the new item textures still apply fine but the replaced textures don't apply. Worth noting that the y offset I apply to the replacements for the existing textures still applies so the end result is that the original texture doesn't get replaced, but it also floats 16 pixels above where its supposed to be.

**Comment by olanti-p** [comment]
Possible fix: https://github.com/cataclysmbnteam/Cataclysm-BN/commit/f7127ad16b354bac1aa5d02b06da6262401abc96
It did the job both for this issue and for #48819 in BN.

**Comment by Fris0uman** [comment]
#51080 Probably fixed this

**Comment by anothersimulacrum** [comment]
Will close until a report there is still a problem.
