### ISSUE TITLE
Sleep deprivation to cause hallucinations

### ISSUE THREAD

**Issue by Entity-y** [CleverRaven/Cataclysm-DDA#45577]
# Is your feature request related to a problem? Please describe.
Advanced sleep deprivation should cause hallucinations, further encouraging the player to try and sleep.

# Describe the solution you'd like
After reaching late stages of sleep deprivation the player begins to lightly hallucinate, then only get more intense until sleeping.

# Describe alternatives you've considered
Getting 6 or more hours of sleep every night.

# Additional context
This would add an extra layer of challenge to insomniac, while adding realism.

**Comment by Ramza13** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/42786 will make this doable via json once it is merged for next version.

**Comment by actual-nh** [comment]
Note possible interactions with stimulants. It is somewhat unclear to me to what degree stimulants relieve symptoms of sleep deprivation in the game - likely **_not_** relieving this particular symptom, however! (An exception, if added into the game - desirable, given military use - would be modafinil/Provigil/Nuvigil.) For a fully realistic treatment, one would need to get into things like catecholamine deficit (why caffeine doesn't work after too much sleep deprivation, and why L-Tyrosine (or, probably better, L-DOPA) helps... for a bit).

**Comment by actual-nh** [comment]
I suggest adding "0.F Feature Freeze" as a tag to this one.

**Comment by anothersimulacrum** [comment]
It is not a PR, just a suggestion issue.

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
