### ISSUE TITLE
Closed metal doors can't be drilled

### ISSUE THREAD

**Issue by Cenness** [CleverRaven/Cataclysm-DDA#45574]
# Describe the bug

Character can't drill closed metal doors with a jackhammer, starting from build 111800.E-7759-gf3a1933
Game shows "You can't drill there" message.

# Steps To Reproduce

1. Make a player with a jackhammer, make sure it has enough charge
2. Find closed door
3. Try to (a)plly your jackhammer to it
3. Door is still there

# Expected behavior

I can drill through a door.

# Screenshots

Next two are from a previous version:
![image](https://user-images.githubusercontent.com/9906246/99912473-bc798180-2d08-11eb-932d-ecf4962fa9c2.png)
![image](https://user-images.githubusercontent.com/9906246/99912744-cef3bb00-2d08-11eb-9d2a-fd135ffcc1bd.png)

And from 11180:
![image](https://user-images.githubusercontent.com/9906246/99912928-dadf7d00-2d08-11eb-8ee6-bf07b72de53a.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-7759-gf3a1933 (tiles)
 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [    Dark Days Ahead [dda]]

# Additional context

Save file: [Drills.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5579997/Drills.zip)

**Comment by anothersimulacrum** [comment]
Expected behavior #45489

**Comment by Cenness** [comment]
But I'm using a motorised equipment to destroy door, not a pick-axe.

**Comment by anothersimulacrum** [comment]
That PR focuses specifically on pickaxes, but it is intended that you cannot mine doors with any mining equipment.
