### ISSUE TITLE
Water heater had water (0). Tried to remove charges that do not exist, removing maximum available charges instead.

### ISSUE THREAD

**Issue by AnonimusC** [CleverRaven/Cataclysm-DDA#45585]
I found a water heater and examined it, it turned out to be clean water(0) (description of object: clean water (0), filled to 0%). I drank water (0) and got an error (a clarification: (number) means the quantity of servings in the container, while the volume of one serving for each object is different). I assume that if the portions are 0, then there need to delete the object, i.e. do not allow its generation at all. [debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5582415/debug.zip)

Still the game did not crash and even texted me: 
```
You drank clean water. 
You squeeze the last drops of clean water from the water heater.
```

Other information:
 - OS: Windows 7 64bit
 - Game Version: 0.E-2
 - Ingame language: System (Russian)
 - Mods loaded: [dda, StatsThroughSkills, ...]

Screenshot (as expected, the game did not translate the log into eng.):
![image](https://user-images.githubusercontent.com/73962707/100105739-befae900-2e78-11eb-9b69-b4cfdc6914e3.png)

Very similar topics (a cursory examination did not reveal the same):

1. https://github.com/CleverRaven/Cataclysm-DDA/issues/39489
2. https://github.com/CleverRaven/Cataclysm-DDA/issues/39402
3. https://github.com/CleverRaven/Cataclysm-DDA/issues/39451
4. https://discourse.cataclysmdda.org/t/experimental-bugs-tried-removing-item-from-object-which-did-not-contain-it/23447/3
5. https://github.com/CleverRaven/Cataclysm-DDA/pull/32756

**Comment by AnonimusC** [comment]
Still the game did not crash and it even texted me: 

```
You drank clean water. 
You squeeze the last drops of clean water water from the water heater
```

**Comment by int-ua** [comment]
Please update title to better reflect the issue, something like "Water heaters can spawn with 0 charges of clean water but not empty"

**Comment by int-ua** [comment]
Confirmed by setting possible water amount in `lighthouse.json` to `[0, 0]` and creating a new world.
