### ISSUE TITLE
Problems with auto-move

### ISSUE THREAD

**Issue by Kelenius** [CleverRaven/Cataclysm-DDA#45587]
# Describe the bug

Auto-move has numerous problems.

- It's only an activity (and, therefore, interruptable) when it's checking for a path to the next overmap tile, handled in activity_handlers.cpp, `activity_handlers::travel_do_turn`. Actual movement is handled in handle_action.cpp, `game::handle_action()`.

This is the biggest problem, because the survivor can easily walk into monsters, get attacked or shot, and continue moving without stopping.

- Overmap pathfinding is strange and often makes weird paths.
- It cannot make diagonal paths on the overmap.

The game uses the same pathfinding algorithm for the player that NPCs use. It's optimized for speed. When the player is choosing a path, it doesn't need to be optimized for speed, because the path is only made when the player requests it, which happens in a menu. It has a lot of difficulty navigating around the forests.

- It moves the player to the center of the next overmap, which is suboptimal and creates a jagged path when not moving in a straight line.
- If the center is unreachable, it stops. This is common in forests and severs.

# Expected behavior

- The entire movement should be handled as an activity. Adding it to `handle_action()` is a weird hack that causes problems.
- The game should use a slower but more accurate pathfinding method for the overmap.
- The method should take into account diagonal movement. While it isn't always possible to move from one overmap tile to another diagonally, the game should, instead of making a path like
```
56789
4OOOO
3OOOO
2OOOO
1OOOO
```
prefer
```
OOO89
OO67O
O45OO
23OOO
1OOOO
```
- Instead of moving the player to the center of the overmap tile, it should just move him to any cell on it. Also, it should try to move closer to the next overmap. In the example above, when moving from 1 to 2, it should take into account that 3 is to the right from 2, and aim to arrive to the right edge of 2; but as soon as the player arrives to 2, it should start moving towards 3, while aiming at the top edge, because 4 is to the top.

**Comment by Maddremor** [comment]
Dpwb, Kevin, and I had a [discussion](https://discord.com/channels/598523535169945603/598535827169083403/609440905425846272) on the subject a little over a year ago. Might be relevant, despite my ineloquence.

**Comment by actual-nh** [comment]
Would the change from activity_hander to activity_actor (note #46317, for instance) help with this? And is max_dist used with the player auto-move pathfinding?

**Comment by RoyBerube** [comment]
A refactoring to an actor would make coding the solution easier. I think it should definitely be done if the activity is to be updated. Using an activity actor makes it a lot cleaner to transition to when it is cancelled for example.
