### ISSUE TITLE
Human Lard, Cracklins non human

### ISSUE THREAD

**Issue by Sir-Kernicus** [CleverRaven/Cataclysm-DDA#45599]
# Describe the bug
When making human lard, the side product of Cracklins aren't considered Human flesh in latest experimental.

# Steps To Reproduce

<!-- Steps to reproduce the behavior:
1. Make a player cook human fat into human lard
2. Eat the side product Cracklins
3. Check (v) morale and find no penalty

# Expected behavior

A morale penalty was expected upon eating Cracklins made using human fat

**Comment by wapcaplet** [comment]
Confirmed in 0.E-7774-g785124ce2d

**Comment by adamkad1** [comment]
mmm, human fat
