### ISSUE TITLE
Cooling suits and devices

### ISSUE THREAD

**Issue by Entity-y** [CleverRaven/Cataclysm-DDA#45593]
# Is your feature request related to a problem? Please describe.
Without bionics, staying cool while wearing lots of layers or heavy armor is out of the question during the summer. Overheating in a fight is crippling.

# Describe the solution you'd like
Add gear that cools the player down like a fan built into a chestpiece. These types of devices already exist for working in hot environments like a factory. 

This wouldn't be too efficient by itself, but by weaving it into a wetsuit and including a hydration pack for example it could wet and cool the player. One charge of water could last like an hour or two of cooling.

# Describe alternatives you've considered
The ability to pour liquids from a container onto myself.

Advanced device that have bits and pieces from a refrigerator to cool even more efficiently.

All-in-one self regulating cooling and heating suit that you can flick on and forget about nonextreme external temperatures.

# Additional context
Being wet from this device would have to feel good, otherwise it would be countered by negative mood penalties on top of encumbrance.

**Comment by ZhilkinSerg** [comment]
Try using CLIMATE_CONTROL flag in your mod.

**Comment by Entity-y** [comment]
That flag might work for the all-in-one temperature regulating suit. Though it wouldn't make sense being at a comfortable temp with just a cooling gear turned on in freezing temperatures. Unless that CLIMATE_CONTROL flag is strictly for cooling down, a new flag would probably need to be made.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/cool-clothing-also-multiple-clothing-layers/26893/7

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
