### ISSUE TITLE
Multiple Segfaults when dealing with ammo belts/ammo belt linkages

### ISSUE THREAD

**Issue by JustCoda** [CleverRaven/Cataclysm-DDA#45597]
# Describe the bug

1. Segfault when trying to reload the M240 in the Humvee
2. Segfault when trying to activate .308 linkages to create a 7.62x51 ammo belt.

# Steps To Reproduce

A. )
1. Make a player with a 7.62x51 ammo belt
2. Spawn Humvee with M240
3. Reload M240 mounted on Humvee with ammo belt
4. Segfault

B. )
1. Make a player with a 100 belt links and 100 ammo of matching type
2. Activate links to make ammo belt
3. Segfault

# Expected behavior

To be able to reload a vehicle mounted ammo belt, or to create an ammo belt.

# Versions and configuration

- OS: Windows 7
- Game Version: 0.E-7759-gf3a1933 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context

Seems to happen regardless of mounted belt fed weapon or linkages used.  Linkage issue does not happen when trying to reload partially filled ammo belt

[SAVE.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5586041/SAVE.zip)

**Comment by andrei8l** [comment]
Should be fixed in master. Please try again with a newer build

**Comment by JustCoda** [comment]
@andrei8l If you can confirm this is no longer an issue I will gladly close and wait for launcher to update to next build. (currently using latest build available from launcher 11181)
