### ISSUE TITLE
[Chibi Ultica] Vehicles look like wrecks, and wreckages look like new

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#45601]
# Describe the bug

This only affects the *Chibi Ultica tile set*

Working and mint-condition vehicles have all their parts rotated, and look like wreckages. On the other hand, actual wreckages look like good-condition vehicles.

# Steps To Reproduce

1. Switch to the Chibi Ultica tileset
2. Spawn or find any vehicle in good condition
3. Find a wreckage

# Expected behavior

Non-wrecked vehicles don't look wrecked, and wrecked vehicles do.

# Screenshots

Brand new Luxury RV looking wrecked:

![image](https://user-images.githubusercontent.com/238395/100030216-39ac0180-2db0-11eb-9e19-cc9d27557f07.png)

Wreckage looking like new:

![image](https://user-images.githubusercontent.com/238395/100030197-30229980-2db0-11eb-919c-605bcd98ba57.png)

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-7774-g785124ce2d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by Fris0uman** [comment]
Did it start after #45586 ?

**Comment by wapcaplet** [comment]
> Did it start after #45586 ?

@Fris0uman Yes, it looks that way - I checked out the revision just before it was merged, and vehicles look OK. I can also confirm that the fix in #45608 works for me.
