### ISSUE TITLE
Balance belts

### ISSUE THREAD

**Issue by carlom5** [CleverRaven/Cataclysm-DDA#45606]
# Describe the bug
Related to #45468 i think that more items should go trough the rebalancing process, stuff like belts in general or even bandoliers have very high encoumbrance values especially if compared with most backapacks or even clothing that could carry the same items, a full tool belt has an encoubrance of 36 that's almost as much as a full hikingbackpack that has 40 on it's max capacity 

# Steps To Reproduce

simply compare various in game values 

# Expected behavior
Items like tool belts, and police belts should be if not useful items to wear at least a vaild strategy as the game stands right now you've basically no reason to wear those type fo equipment unless it's super early on and you've have no other means of carrying items. On the other hand we know that in RL such items even while full are not that uncofortable and barerly encoumbrant 

# Versions and configuration

    -- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-7759-gf3a1933 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by SirPendrak** [comment]
I might look into this in a few days

**Comment by carlom5** [comment]
> 
> 
> I might look into this in a few days

thanks a lot for your help! i do think that all the ''less used'' containers need some rebalance i do really appriciate people like you working on it! thanks again

**Comment by AnonimusC** [comment]
One can just add the tag "lost stiffness", "torn", which will be adding encumbrance: do lower the constraint values of all such things by [number] (or by 1/[number]) and this tag, if things are damaged, will return their values to the current ones.

**Comment by Headjack** [comment]
Tool belts are also usually stiff in my experience, I dont think theyd get more or less cumbersome with being full.

**Comment by carlom5** [comment]
> Tool belts are also usually stiff in my experience, I dont think theyd get more or less cumbersome with being full.

well sure but you still gotta factor the fact that now you've the handle of an hammer sticking out of what used to be just an empty loop and stuff like that.. . but everything considered tool belt and police belts should not be as encoumbring as a hiking pack, same goes for bandoliers

**Comment by Kelenius** [comment]
I think the best thing to do here would be to look at their pre-pocket update encumbrances and set them to that.

**Comment by emptytriangle** [comment]
I ditched my halligan bar belt today because encumbrance 9 was just waaaay too savage on top of an MBR vest. It's better to bash down doors than to wear that

**Comment by Mrzjadacz** [comment]
The encumbrances values should be reduced but not too much.
Instead I would drastically increase time needed to wield item from backpacks.
E.g. runner pack: 
![image](https://user-images.githubusercontent.com/26396019/100629673-daa73900-3329-11eb-88ea-beec368cf43a.png)
The base value to wield item from it is barely 300 moves.
So like 4s to grab a pistol. Impossible in my opinion.  The main, big pockets on backpacks should have access times starting from 10s.

**Comment by AnonimusC** [comment]
> The encumbrances values should be reduced but not too much.
> In addition I would drastically increase time needed to wield item from backpacks.
> E.g. runner pack:
> ![image](https://user-images.githubusercontent.com/26396019/100629673-daa73900-3329-11eb-88ea-beec368cf43a.png)
> The base value to wield item from it is barely 300 moves.
> So like 4s to grab a pistol. Impossible in my opinion. The main, big pockets on backpacks should have access times starting from 10s.
> 
> Keeping something on your belt, bumping against your leg as you walk IS LESS comfortable that keeping it stuffed in some big bag.

This makes sense, you are right, but, btw, the backpack could be worn in the front, where the time could be significantly less. I think it could be worn in the front without significant stiffness, depending on its fullness, at least, and size, and cdda is exactly where wearing in the front, according to the "philosophy" of the game (how other things are implemented), should be allowed.
