### ISSUE TITLE
Energy saber not dealing cutting and/or heat damage

### ISSUE THREAD

**Issue by Torres84f** [CleverRaven/Cataclysm-DDA#45615]
# Describe the bug

Once I activate my UPS converted energy saber it shows as to deal less damage as it did before I updated and it shows as bashing damage

# Steps To Reproduce

Spawn energy saber (UPS converted) and check stats

# Expected behavior

# Screenshots
![1](https://user-images.githubusercontent.com/15707408/100161805-149bb980-2eaa-11eb-9136-968571060180.jpg)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-7794-gdf54339 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Mining Mod [Mining_Mod],
    Blaze Industries [blazeindustries],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod [crt_expansion],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Aftershock [aftershock],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Dorf Life [Dorf_Life],
    Dorf Life - UndeadPeople Tileset [Dorf_LifeUDP],
    DinoMod [DinoMod],
    DinoMod - UndeadPeople Tileset [DinoModUDP],
    Magiclysm [magiclysm],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP]
]
# Additional context

**Comment by John-Candlebury** [comment]
Correction here:

The active energy saber does deal the damage especified in its json file. (Which is 20 stab + 50 heat damage)

However, the item description UI is not updated to show these adjusted values.

**Comment by RenechCDDA** [comment]
Now that damage types are JSONified this can be easily resolved by removing the energy saber's enchantment and simply giving it the damage directly.

https://github.com/CleverRaven/Cataclysm-DDA/blob/10cdb0ceaf13187d5489e95355861c8c9bd66093/data/mods/Aftershock/items/weapons.json#L62
