### ISSUE TITLE
"EMITTER" flag doesn't work for terrain

### ISSUE THREAD

**Issue by Positronic-Girl** [CleverRaven/Cataclysm-DDA#45614]
# Describe the bug

Currently the "EMITTER" flag when applied to terrain does not emit any fields.

# Steps To Reproduce

1. Make a simple piece of terrain that has the emitter flag and a simple emissions
2. Spawn it in via the map editor
2. Wait
3. Nothing happens

# Expected behavior

From what I was told in the discord, while the "EMITTER" flag only mentions furniture, it works for fields, items, monsters, and terrains, and I figured as well as the structure of both furniture vs terrain in json is very similar, down to using the same list of flags for some things that "EMITTER" and "EMISSIONS": would work for it as well.

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-7759-gf3a1933 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock]
]

**Comment by ZhilkinSerg** [comment]
`EMITTER` flag only works for furniture (see https://github.com/CleverRaven/Cataclysm-DDA/pull/32101) and vehicle parts (https://github.com/CleverRaven/Cataclysm-DDA/pull/31913).
