### ISSUE TITLE
Tin can size discrep.

### ISSUE THREAD

**Issue by Headjack** [CleverRaven/Cataclysm-DDA#45618]
Recipes for some canned goods use 'small tin can' but produce items in, or at least described as, 'medium tin can' such as canned offal

# Steps To Reproduce

check the recipe

# Expected behavior

no can size change

# Screenshots

# Versions and configuration

latest experimental

**Comment by leemuar** [comment]
Could you please provide couple examples of these recipes?

**Comment by Headjack** [comment]
Looks like it's Canned Offal and Canned Liver, as provided in the book Can Sealer Instructions
