### ISSUE TITLE
Braziers hurt firestarting

### ISSUE THREAD

**Issue by Headjack** [CleverRaven/Cataclysm-DDA#45619]
I know it's harder to start fires now, but using a brazier with my normal method of campfire setting (5 tinder and 5 splintered wood) causes the fire to go out whereas it normally stays lit. somehow the brazier makes it less likely to catch fire. This doesnt happen if you set a fire and THEN place the brazier on top of it, which is also odd. Is it also true on fire rings, ovens, etc? unsure.

compare brazier firestart to non-brazier

# Expected behavior

same or easier to start

# Screenshots

# Versions and configuration

experimental b11153

**Comment by ZhilkinSerg** [comment]
Update to latest available version and test whether there is still an issue.

**Comment by Headjack** [comment]
Did so and it still seems like it's happening

**Comment by satheon49** [comment]
The fire seems to work fine (Game Version: 0.E-8010-g9147e7d191 [64-bit]).

Test setup:
1. Spawn brazier, lighter, 10 tinder, 10 splintered wood
2. Activate brazier and drop 5 tinder/splintered wood into it
3. Drop 5 tinder/splintered wood on another square a bit away
4. Light fire in brazier and fire on square.
5. Brazier fire burnt for about 45min, fire on square burnt fuer about 55min

**Comment by kevingranade** [comment]
Considering the timing I suspect this was resolved by  #45431
