### ISSUE TITLE
 AIM "move all items" action is broken again

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#45613]
# Describe the bug

# Steps To Reproduce

Load the attacked save, `/`, `,`, reopen `/` and see that nothing is moved.

# Expected behavior
`,` moving stuff into my inventory.

# Screenshots

# Versions and configuration
- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.E-7784-g373536a1e8-dirty [64-bit]
- Graphics Version: Curses
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

# Additional context
[2020.04.12.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5592873/2020.04.12.zip)

**Comment by andrei8l** [comment]
I can reproduce this with 0.E-2 so it's not a new bug. It looks like it fails because the source is [A] but the items are actually in a vehicle - it works fine if you switch the left pane to the appropriate vehicle square.

(btw my AIM rewrite doesn't have this problem)

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-11014.
