### ISSUE TITLE
Unable to quarter skeletal monsters' corpses 

### ISSUE THREAD

**Issue by RedShakespeare** [CleverRaven/Cataclysm-DDA#45624]
# Describe the bug

Players are not able to quarter skeletal monsters' corpses because skeletons have no organs for field dressing.

# Steps To Reproduce
1. Make a player with butchering tools.
2. Summon a skeleton and kill it.
3. Try to quarter the corpse.
4. Message shows that you need to perform field dressing first.
 

# Expected behavior
Player can quarter a organ-less monster directly.

# Screenshots
![image](https://user-images.githubusercontent.com/44523519/100233941-59d0f180-2f65-11eb-9d5d-6cfb0b587148.png)

![image](https://user-images.githubusercontent.com/44523519/100233978-66554a00-2f65-11eb-85cf-cc16bef9aecf.png)

# Versions and configuration
- OS: Any
- Game Version: 0.E-7808-g3825720 or 0.E-b11185

**Comment by Giagantic** [comment]
All Skeletal variants of zombies actually do have organs. The skeleton is merely an external carapace or bony structure that formed as a result of the blob and it's mutagenic attributes.

**Comment by RedShakespeare** [comment]
Yes...?
What I mean is that skeletal corpses have the attribute 'has no organs', and this attribute causes the bug. The descriptions may not help a lot...

**Comment by Giagantic** [comment]
Woops my bad, I missed that part of your issue, seems like an oversight.

**Comment by wapcaplet** [comment]
Confirmed in 0.E-7804-g98d7868836. The `skeleton` monster as well as the skeletal dog, wolf, brute, juggernaut, and zombear cannot be quartered, because they cannot be field dressed:

![image](https://user-images.githubusercontent.com/238395/100256339-ea75e600-2f01-11eb-9aa3-3f787f90109f.png)
