### ISSUE TITLE
Segmentation fault while dropping item when there are two favourited stack of it in the same pocket

### ISSUE THREAD

**Issue by Mrzjadacz** [CleverRaven/Cataclysm-DDA#45633]
# Describe the bug

As a substitute solution for #45553 I marked some everyday consumable DRUGS as favourites so they won't get shuffled together with random things I pick up. Then I used `/` view to grab a few more, they entered the same pocket but weren't favorite. I marked them as such but they still didn't stack (despite being in the same pocket). I decided to drop one stack and pick it back up, game crashed upon clicking Enter.

# Steps To Reproduce

Get some stackable item (tested only for bandages) and put it in a pocket (priority and whitelist it to a specific pocket or test on an item with only one pocket, haven't tested what happens if they are in different pockets)
Favourite it (tested for invlet, changes nothing)
Insert more of the same item, but not favourited into the pocket
Favourite the second stack
Open dropping view
1) select only one stack, game crashes
2) select both stacks, only the first stack selected is dropped. It can be picked up and stacks up properly with the one in the pocket

# Expected behavior

The stacks were displayed separately because only one was favourited. After favouriting the other one they should stack up together.
When grabbing/picking up/transfering items non-favourite should stack up with favourited ones.

# Screenshots

![image](https://user-images.githubusercontent.com/26396019/100282369-c0f1a480-2f6b-11eb-9806-b99eea5785dc.png)

![image](https://user-images.githubusercontent.com/26396019/100282399-ce0e9380-2f6b-11eb-8d3f-8ff7b25ce7c2.png)

![image](https://user-images.githubusercontent.com/26396019/100282414-d535a180-2f6b-11eb-9d8a-0c3b823b094b.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-7864-g26d2ef6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Mythical Martial Arts [MMA],
    C.R.I.T Expansion Mod [crt_expansion],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Bionic Professions [package_bionic_professions],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP]
]

# Additional context

[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5599302/config.zip)
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5599304/save.zip)

**Comment by andrei8l** [comment]
> When grabbing/picking up/transfering items non-favourite should stack up with favourited ones.

I don't agree with this bit, but the rest were trivial fixes

**Comment by Mrzjadacz** [comment]
> Start with a plastic bag. Insert 10x aspirin, then favorite the aspirins. Insert one more aspirin then favorite the aspirin (1). The aspirins should be stacked now.
This is fine too, thanks
