### ISSUE TITLE
Climate Control CBM - Automatic Settings

### ISSUE THREAD

**Issue by ElfLeaderMike** [CleverRaven/Cataclysm-DDA#45642]
# Is your feature request related to a problem? Please describe.
I found turning Climate Control on and off a whole bunch to save power seemed a bit tedious. Since, for example, the Ethanol Burner has automation options regarding when it's turned on. It felt strange for this specific CBM to not have a similar feature.

# Describe the solution you'd like
Automation options on climate control.

For turning on automation either:
When not comfortable, enable climate control.
When temp (greater than, less than) (exact temp or warm/cold/etc)

For turning off automation, simply an option to auto turn off when ambient temp would result "Comfortable" status.

# Describe alternatives you've considered
I have not considered alternatives.

# Additional context
Assuming the automated power management is a intended part of bionic lore, it doesn't seem like such a far stretch that most bionics would have various conditional triggers.

**Comment by Fris0uman** [comment]
Sounds like a good idea but it would be cool to add a generic system for auto activating CBMs instead of harcoding it just for Climate Control. Maybe using something similar to the trigger system implemented for mutations in https://github.com/CleverRaven/Cataclysm-DDA/pull/40803

**Comment by Fosheze** [comment]
> Sounds like a good idea but it would be cool to add a generic system for auto activating CBMs instead of harcoding it just for Climate Control. Maybe using something similar to the trigger system implemented for mutations in #40803

Something else that would be interesting for CBMs is allowing them to alter their power draw based on different factors. For example the climate control CBM would use more power keeping you warm in a deep freeze lab than it would while warding off a mild chill.

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
