### ISSUE TITLE
"M4A1" + "Combat knife" = broken aiming mode. [gunmods]

### ISSUE THREAD

**Issue by AnonimusC** [CleverRaven/Cataclysm-DDA#45644]
I combined an M4A1 and a combat knife, while the rifle already had a shoulder strap. When trying to aim, the game spam notifications that there is not enough skill in using a knife, does not allow switching to automatic firing mode by directly clicking on this mode, instead, it switches if you press the number 5 corresponding to the current, semi-automatic, firing mode, and then does not allow switching to semi-automatic mode in any way. The game also forces you to press the aiming mode selection 3 times before finally firing at 4 pressings.

Steps To Reproduce: upload the attached [save file](https://github.com/CleverRaven/Cataclysm-DDA/files/5601585/Debug.Save.zip) and jump in, or:
1) Start the new game with mi-go camp challenge.
2) Combine the M4A1 and the combat knife.
3) Try to aim.

Commentary:  in the attached save file there are 2 characters, 1 of them with the piercing weapon skill, the other without. The one who has a skill, this does not happen, and who does not - it happens.

# Versions and configuration
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version (upd: Windows 7 64-bit)
- Game Version: 0.E-7804-g98d7868 [64-bit] (upd: buld 11184)
- Graphics Version: Tiles
- Game Language: Системный язык [ ] (upd: Russian)
- Mods loaded: [
    Тёмные Дни Впереди [dda]
]
# Additional context & Screenshots
I. When this happened for the first time to me, for some reason, unlike the bug described in the post, I did not need to press the aiming mode several times: shooting started immediately after pressing "f", "a", "c" or "p" buttons. Then I assumed that instead of 3 shots in front of 4, the character tried to stab: 

![image](https://user-images.githubusercontent.com/73962707/100329996-714cc080-2fdf-11eb-9b71-d24eb7eed9e4.png)
(3 missing knife skill notifications and 1 crit. hit)

II. Observations: (1) these warnings pop up 4 or 3 times: 1 time at the start of aiming and 1 time each time when you switch or select the same aiming mode only if there was no shot after it.

(2) For some reason, when you need to press the aiming mode many times, the current aiming (which will shoot at the "f" button) changes, but not to the selected aiming mode (a, c or p), but a little to another, without reaching them on accuracy:

![image](https://user-images.githubusercontent.com/73962707/100331943-d4d7ed80-2fe1-11eb-8630-ca10ce9671df.png)
(initial aiming)

and

![image](https://user-images.githubusercontent.com/73962707/100332013-e8835400-2fe1-11eb-9124-ce7e5ec1328c.png)
(after pressing "a" button)

(3) If you hold a discharged M4A1 with a combat knife attached
![image](https://user-images.githubusercontent.com/73962707/100333006-22a12580-2fe3-11eb-9a69-76f8bd308a44.png)
and try to enter aiming mode it will write the following:
![image](https://user-images.githubusercontent.com/73962707/100332885-000f0c80-2fe3-11eb-97b6-6a1b18876719.png)
(now you cannot fire your weapon (combat knife))

(4) Despite the lack of the required minimum skill for a knife, the character still uses it (writes: you pierced the enemy, you cut the enemy), although this improves (if I was not mistaken) the skill of impact weapons (bats, sledgehammers, blow with a rifle butt).

(5) By the way, the combat knife says requires the skill of hand-to-hand combat=1 and piercing weapon=2, but if there is no piercing skill, then the notification is not written at all when with a knife in hand.

(6) Still works on buld 11190.

(7) Perhaps the solution to [this problem](https://github.com/CleverRaven/Cataclysm-DDA/issues/45589) in the past did not take into account some interactions.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-11014.
