### ISSUE TITLE
`invalid bionic id "null"` when opening the `E`at menu

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#45641]
# Describe the bug

# Steps To Reproduce
Load the save, press `E`, observe the warning.

# Expected behavior

# Screenshots

# Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.E-7820-g7c1533deb6-dirty [64-bit]
- Graphics Version: Curses
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

# Additional context

[2020.04.12.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5600959/2020.04.12.zip)

**Comment by Kelenius** [comment]
I get this without battery system. I have fingerpick, arms alloy plating, fingertip razors, and anti-glare compensators. I think it's not related to your bionics.

**Comment by CAHEK7** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/commit/5583a5d17f3817119c1d5d3750163cbefd1d447a#r44541671
