### ISSUE TITLE
Items from container disappear if container deployed on the ground.

### ISSUE THREAD

**Issue by CAHEK7** [CleverRaven/Cataclysm-DDA#45651]
# Describe the bug

Items from container disappear if container (large cardboard box) deployed on the ground.

# Steps To Reproduce

0. Spawn large cardboard box.
1. Grab it into your hands.
2. Insert something into it (through inventory-carboard-insert).
3. Deploy it through actions.
4. All inserted stuff disappear. 
5. At least it can't be found on the ground, in the inventory or inside container.

Or just deploy cardboard from the save file: [test_cardboard.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5604887/test_cardboard.zip)

# Expected behavior

It should stay inside deployed container or at least should be dropped on the ground.

# Screenshots

![1](https://user-images.githubusercontent.com/489073/100389700-24003b80-303f-11eb-918f-509f3299a290.png)
![2](https://user-images.githubusercontent.com/489073/100389699-24003b80-303f-11eb-8b28-73ae8cac7aa2.png)
![3](https://user-images.githubusercontent.com/489073/100389698-2367a500-303f-11eb-991f-8bcdf5943f53.png)
![4](https://user-images.githubusercontent.com/489073/100389697-2367a500-303f-11eb-9c13-d6cad2c3211d.png)
![5](https://user-images.githubusercontent.com/489073/100389692-1fd41e00-303f-11eb-87c3-48fa53273ef9.png)

# Versions and configuration

 - OS: Ubuntu 18.04
 - Game Version: 0.E-7877-g5fdd9f42f9
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Monsters [Only_Wildlife]
]

# Additional context

**Comment by andrei8l** [comment]
This should fix it:
```diff
diff --git a/src/iuse_actor.cpp b/src/iuse_actor.cpp
index 8e4a20a451..a4e4ccc02b 100644
--- a/src/iuse_actor.cpp
+++ b/src/iuse_actor.cpp
@@ -1084,6 +1084,7 @@ int deploy_furn_actor::use( player &p, item &it, bool, const tripoint &pos ) con
     }
 
     here.furn_set( pnt, furn_type );
+    it.spill_contents( pnt );
     p.mod_moves( to_turns<int>( 2_seconds ) );
     return 1;
 }
```

**Comment by CAHEK7** [comment]
Just figured this out too and can confirm that it helps, thanks. Do you submit PR?

**Comment by andrei8l** [comment]
I can't test very much atm so feel free to take over
