### ISSUE TITLE
Cars with backseats?

### ISSUE THREAD

**Issue by Pupsi-Mupsi** [CleverRaven/Cataclysm-DDA#45654]
I feel like most cars should have real back seats instead of just normal "front seats".
Here's a mockup of how it would look like. **What do you think?**
This change would be mostly cosmetic.

Mockup:

![car-back-seat-mockup](https://user-images.githubusercontent.com/44737997/100393512-2dd37000-303a-11eb-929c-fd804b7c74f1.jpg)

This is how cars look right now:
![car-back-seat](https://user-images.githubusercontent.com/44737997/100393514-30ce6080-303a-11eb-9857-ea3398623d0a.jpg)

**Comment by Pupsi-Mupsi** [comment]
Thanks for all your feedback.

@l29ah what's bothering / confusing you about this idea?

**Comment by l29ah** [comment]
Never mind, i thought it would require us to create a separate kind of seats, but after looking carefully at the outside-touching windshields, i guess it would be possible to programmatically decide that all the seats that have seats in front of them or backseats at the sides can be drawn as backseats.

**Comment by Pupsi-Mupsi** [comment]
I see. Now I understand.

I would prefer it to be a separate seat though and I'm willing to invest the time.

Some cars and smaller trucks have "benches" in the front-row of the vehicle. Creating a separate seat that copies most standard seat characteristics and makes use of "looks_like" is what I would do. I think this way it's easier to handle exceptions such as buses and rv's.

![1979Impalabenchseat_1500](https://user-images.githubusercontent.com/44737997/100518823-58d1d700-3194-11eb-9766-a4cb11a3bee6.jpg)

**Comment by l29ah** [comment]
Okay, then it would be nice if such a benchy seat could fit a blanket.

**Comment by Pupsi-Mupsi** [comment]
Good idea. I'll try to come up with something.

**Comment by Fosheze** [comment]
> Okay, then it would be nice if such a benchy seat could fit a blanket.

As someone who has slept on truck bench seats before they aren't that bad and I second this idea.
