### ISSUE TITLE
Game crashes if explosive's explosion destroys the container which contained the explosive

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#45662]
# Describe the bug
Game crashes if explosion destroys the container which contained explosive.

# Steps To Reproduce
1. Light the fuse of the dynamite;
2. Put the dynamite inside the RC car;
3. Drop the car on the ground;
4. Dynamite's explosion destroys the RC car;
5. Game crashes.

# Expected behavior
No crash.

# Screenshots
![1234](https://user-images.githubusercontent.com/11132525/100412603-93e9e280-308e-11eb-8f16-482dae49777b.gif)

In this example I used radio-modded dynamite which I put inside the RC car (but this works for non-radio-modded explosive and any container which is destroyed by the explosion). I pressed the red button and waited for 20 turns. The dynamite then explodes and destroys the RC car. A lit dynamite is briefly seen lying on the ground after the explosion. I guess this is the culprit of the crash. Then game silently crashes. No errors show up. Debug log doesn't show anything. 

# Versions and configuration
 - OS: Windows 10 x64.
 - Game Version: 0.E-7884.
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: default only.

# Additional context
Discovered while working on #45661.

**Comment by andrei8l** [comment]
This one seems pretty tricky. I don't think `item`, `item_pocket`, or `item_pocket::process()` can be (cleanly) modified to handle the explosion deleting items/pockets/`this`. The best solution might be to just defer the explosions, like this:
<details>
<summary>patch</summary>

```diff
diff --git a/src/explosion.cpp b/src/explosion.cpp
index 655720f0af..0c6581c8cf 100644
--- a/src/explosion.cpp
+++ b/src/explosion.cpp
@@ -501,6 +501,11 @@ void explosion( const tripoint &p, float power, float factor, bool fire,
 }
 
 void explosion( const tripoint &p, const explosion_data &ex )
+{
+    g->queue_explosion( p, ex );
+}
+
+void _explosion( const tripoint &p, const explosion_data &ex )
 {
     const int noise = ex.power * ( ex.fire ? 2 : 10 );
     if( noise >= 30 ) {
diff --git a/src/explosion.h b/src/explosion.h
index dd70d0a4b0..4267e13158 100644
--- a/src/explosion.h
+++ b/src/explosion.h
@@ -64,6 +64,7 @@ void explosion(
 );
 
 void explosion( const tripoint &p, const explosion_data &ex );
+void _explosion( const tripoint &p, const explosion_data &ex );
 
 /** Triggers a flashbang explosion at p. */
 void flashbang( const tripoint &p, bool player_immune = false );
diff --git a/src/game.cpp b/src/game.cpp
index 751228c6c3..4f24d24d45 100644
--- a/src/game.cpp
+++ b/src/game.cpp
@@ -1573,6 +1573,9 @@ bool game::do_turn()
     m.vehmove();
     m.process_fields();
     m.process_items();
+    for( auto &ex : _explosions ) {
+        explosion_handler::_explosion( ex.first, ex.second );
+    }
     m.creature_in_field( u );
 
     // Apply sounds from previous turn to monster and NPC AI.
@@ -12287,6 +12290,11 @@ bool game::slip_down( bool check_for_traps )
     return false;
 }
 
+void game::queue_explosion( const tripoint &p, const explosion_data &ex )
+{
+    _explosions.emplace_back( p, ex );
+}
+
 namespace cata_event_dispatch
 {
 void avatar_moves( const tripoint &old_abs_pos, const avatar &u, const map &m )
diff --git a/src/game.h b/src/game.h
index 7e944d613a..92aa7f8af9 100644
--- a/src/game.h
+++ b/src/game.h
@@ -23,6 +23,7 @@
 #include "creature.h"
 #include "cursesdef.h"
 #include "enums.h"
+#include "explosion.h"
 #include "game_constants.h"
 #include "item_location.h"
 #include "memory_fast.h"
@@ -194,6 +195,8 @@ class game
          */
         void on_options_changed();
 
+        void queue_explosion( const tripoint &p, const explosion_data &ex );
+
     protected:
         /** Loads dynamic data from the given directory. May throw. */
         void load_data_from_dir( const std::string &path, const std::string &src, loading_ui &ui );
@@ -961,6 +964,7 @@ class game
 
         map &m;
         avatar &u;
+        std::vector<std::pair<tripoint, explosion_data>> _explosions;
         scent_map &scent;
         const scenario *scen = nullptr;
 
```
</details>

This seems to work in the situation presented above, but I haven't tested too much. Furthermore, this comment [here](https://github.com/CleverRaven/Cataclysm-DDA/blob/f780ab97238ca35232a257f5554ad5b87bf83a41/src/map.cpp#L4757) suggests that some of the code expects items to explode in line. Any thoughts?
