### ISSUE TITLE
UPS can be loaded with disposable heavy battery after applying heavy battery mod and it recharges

### ISSUE THREAD

**Issue by Torres84f** [CleverRaven/Cataclysm-DDA#45673]
# Describe the bug

I got a UPS, applied the heavy battery mod and then reloaded with a disposable heavy battery... now the charge is 2500 I think? it's more that's for sure and twice the volume and all that but it also recharges

# Steps To Reproduce

1-. Grab normal UPS
2.- Apply heavy battery mod
3.- You now have a UPS+1 with no charge or anything
4.- Reload it with a heavy DISPOSABLE battery
4.- Now you have a 2500 battery UPS that can be recharged if put in the recharge station.

# Expected behavior

# Screenshots
![1](https://user-images.githubusercontent.com/15707408/100524529-d7d50880-31b0-11eb-88dc-1539ef7bcf15.jpg)

# Versions and configuration

GAME REPORT:
- OS: Windows
- OS Version: 10.0 1909
- Game Version: 0.E-7866-ga66cf52 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    XEAS [XEAS],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Mining Mod [Mining_Mod],
    Dorf Life [Dorf_Life],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    DinoMod - UndeadPeople Tileset [DinoModUDP],
    Dorf Life - UndeadPeople Tileset [Dorf_LifeUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP]

# Additional context

**Comment by andrei8l** [comment]
What is the bug here? An UPS can be reloaded with a heavy disposable battery whether modded or not. I tried recharging a modded UPS, loaded with a disposable battery, in a recharging station but it didn't gain any charges. Can you please clarify how you recharged it?

**Comment by Torres84f** [comment]
> 
> 
> What is the bug here? An UPS can be reloaded with a heavy disposable battery whether modded or not. I tried recharging a modded UPS, loaded with a disposable battery, in a recharging station but it didn't gain any charges. Can you please clarify how you recharged it?

Updated it with a screenshot and better verb (r)eload instead of insert

**Comment by andrei8l** [comment]
I see, thanks. Didn't know Aftershock's UPS was different.

**Comment by int-ua** [comment]
Please comment if you are still able to reproduce it and we'll reopen this issue.
