### ISSUE TITLE
Adding Holiday Themed Monsters

### ISSUE THREAD

**Issue by Theawesomeboophis** [CleverRaven/Cataclysm-DDA#45672]
# Describe the solution you'd like
Add Monsters for the different holidays.
# Describe alternatives you've considered
Not Doing This.
# Additional context
Will be split up into multiple PRs as this is a multi-mod project.
Monsters so far:
MSC:
Living Pumpkins(Halloween)
Candy Cane Themed Monster (Christmas) (Suggestions for what vanilla monster best suits the candy cane theme welcome)
Magiclysm:
Leprechaun( St Patrick's Day/ Leprechaun's Day)
Workshop Elves/ Christmas Elves(Christmas)
Yule Cats(Christmas) ( Best fit Magiclysm due to Icelandic Folklore origins)
Vanilla: Reindeer/Caribou(Christmas)
Note: Turkey Removed due to it already existing in game.

**Comment by Xaleth** [comment]
I like the idea that they would spawn at specific times of the year.

**Comment by Theawesomeboophis** [comment]
> I like the idea that they would spawn at specific times of the year.

Yes, they will spawn during the seasons in which their holidays occur. Unfortunately I cannot make them spawn on specific days due to the lack of a month system currently.

**Comment by Theawesomeboophis** [comment]
Not sure which animal to convert into a candy cane themed monster yet.

**Comment by Theawesomeboophis** [comment]
Thinking about adding Yule Cats as well, but not sure which mod they would fit in or if they would fit in vanilla.

**Comment by Theawesomeboophis** [comment]
Reindeer is complete, gonna test now.

**Comment by emptytriangle** [comment]
immersion break, no reindeers in new england. I hate to be the guy to shit on your idea but I don't like it being in core

**Comment by Theawesomeboophis** [comment]
https://en.wikipedia.org/wiki/Boreal_woodland_caribou
research-related-to-boreal-caribou-habitat-restoration-economics-british-columbia.pdf
https://en.wikipedia.org/wiki/List_of_mammals_of_New_England
1st is a article regarding a species of Caribou that roamed New England until 2018
2nd is a document from a conservation effort to restore said species former range, which includes New England
3rd is a list of Mammals in New England, the Boreal woodland Caribou is labeled under deer

**Comment by Theawesomeboophis** [comment]
Also there are still a large number of Caribou in Quebec, which is one of the borders of New England, and I believe they may visit New England during migration.

**Comment by emptytriangle** [comment]
I saw your arguments in the PR - I agree you are correct and rescind my objection

**Comment by Fosheze** [comment]
As an actual game mechanic it would probably be best if the changes were cosmetic only/optional. I can't speak for everyone but I know that I am not a fan of wacky new creatures suddenly appearing in my long term world because of a real life holiday or an in game holiday happening long after the cataclysm began. To me that seems like a Crazy Cataclysm feature. Something like swapping zombie tiles with Santa hat zombie tiles though I am all for I am all for. 

It would actually be interesting if there was a way to have the game automatically switch to alternate holiday themed tiles if available in your tileset. This gives another tool to tileset creators and that way if you didn't want those tiles you would just use a tileset without them or remove them from the tileset on your own.

**Comment by Theawesomeboophis** [comment]
Only reindeer are vanilla, all others are being put in mods.

**Comment by Theawesomeboophis** [comment]
Gonna get back to working on this as soon as Orcs And Ogres is finished.

**Comment by Theawesomeboophis** [comment]
Still working on this, will start Part III after Part II is ready to be
merged.

**Comment by Theawesomeboophis** [comment]
I will begin work on Part III after freezes are over, I will be shifting to helping third party mods until then.

**Comment by Theawesomeboophis** [comment]
I am continuing work on this now that freezes are over.
