### ISSUE TITLE
Multi-cooker doesn't work with UPS mod

### ISSUE THREAD

**Issue by Entity-y** [CleverRaven/Cataclysm-DDA#45678]
# Describe the bug
Attaching a UPS conversion mod to a multicooker renders it useless as it says low battery.

# Steps To Reproduce
1. Spawn multicooker, UPS conversion mod, and a charged UPS.
2. Attach mod and try and use the multicooker.

# Expected behavior
Device would work as if it had a charged battery.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-7886-g76fd581 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Shard's Additions [shardstuff],
    Gun Cotton [guncotton],
    Graphical Overmap [Graphical_Overmap],
    MSX Indicators: REMIX [UDP_REMIX_INDICATORS],
    Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Whaleys Hair Mod (UDP Tweaks) [WHALEYHAIR_UDP],
    Original Drug Names [OG_Drugs]
]

**Comment by Maleclypse** [comment]
Does multi cooker have the remote use flag and if so is it appropriate to use UPS for remote use items?

**Comment by Entity-y** [comment]
I don't see a allows remote use flag on the multi cooker, the pressure cooker has it though. UPS is appropriate for most tools, the logic is if it's close enough to plug into the UPS then it should function as a power source, the exception I could see is a RC car or something that wouldn't stay plugged into a UPS while you use it.

**Comment by Raikiri** [comment]
I think the same problem happens to a makeshift arc welder. I think it always shows 20 charges for me for some reason in the crafting menu.

Soldering iron with a UPS mod that's sitting nearby sometimes works for some time when crafting something big, but in the middle of crafting process says something like "the recipe requires none to continue" where "none" is supposed to be the name of the component that it actually requires, but it just says "none". However, with soldering iron it seems to work fine if I pick up a charged ups and hold in my inventory (contrary to using one on the floor nearby). With arc welder it does not work.

I think all these can be parts of the same issue that UPS modded items in general incorrectly calculate number of charges that they have in crafting screen.
