### ISSUE TITLE
Save past filters for advanced inventory screen

### ISSUE THREAD

**Issue by ElfLeaderMike** [CleverRaven/Cataclysm-DDA#45684]
# Is your feature request related to a problem? Please describe.
Small nitpicking, but I enjoy using a variety of filters while looting. Sometimes I want to quickly swap off the filter but then have to re-add the whole thing. Why do I have to retype this filter for the 100th time! Madness!

# Describe the solution you'd like
When I'm focused on the filter bar, simply allow the player to press up arrow to use previously entered filters. Quickly return to that ultra specific filter you love! Bounce between many filters instantly!

# Describe alternatives you've considered
A system for saving custom filters and assigning them to hotkeys while focused on the filter window, but the up arrow idea seemed like a simple and solid addition.

# Additional context

**Comment by ZhilkinSerg** [comment]
There is AIM overhaul underway which probably needs to go in before filter can be added - #45243.

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
