### ISSUE TITLE
Unpowered electric blankets don't regulate temperatures when waiting on them

### ISSUE THREAD

**Issue by ElfLeaderMike** [CleverRaven/Cataclysm-DDA#45683]
# Describe the bug
When waiting on an unpowered electric blanket to stop freezing, there is no temperature change. 

# Steps To Reproduce
Get to cold/freezing.
Wait on electric blanket on a bed.
Freeze

# Expected behavior
Even unpowered, electric blankets still function as blankets (at least from the ones I've used). They should be able to help you reach comfortable temperatures, just not keep you EXTRA warm and cozy. Normal blankets work fine even in the coldest of temperatures at the moment.

# Screenshots

# Versions and configuration
 - OS: Windows 7
 - Game Version: 0.E-7886-g76fd581
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: DDA, Disable NPC Needs, Bionic Professions, Magiclysm

# Additional context

**Comment by satheon49** [comment]
Seems to work fine for me. My test setup:
1. Go underground and get naked (constant temperature of 6 °C)
2. Wait a while without any blanket -> Chilly
3. Move onto bed tile with blanket and wait -> Comfortable
4. Wait a while without any blanket -> Chilly
5. Move onto bed tile with electric blanket and wait -> Comfortable

**Comment by ElfLeaderMike** [comment]
I went back and checked on the footage that made me think this, I think I was wrong.
https://clips.twitch.tv/SpikyEagerPotStinkyCheese

I may have had to wait longer on the blanket to heat up, but I didn't noticed I went from very cold to chilly which looks like temp stabilization. Ice lab tricked me!

Sorry about that!
