### ISSUE TITLE
NPCs unable to activate and reload gas masks

### ISSUE THREAD

**Issue by Salty-Panda** [CleverRaven/Cataclysm-DDA#45699]
# Describe the bug

NPC wearing PBA(100/100) mask stands in smoker zombie's cloud. I hear heavy coughing and upon inspection, NPC has `smoke(mouth)` affliction. Had to enable mask myself and have her wear it again.

# Steps To Reproduce

Have an NPC wearing a gas mask-like equipment and any gas hazard at the same tile.
Wait till NPC get related affliction.

Have NPC with (0/100) gas mask of any sort near appropriate filters.
Check if NPC will reload its mask.

# Expected behavior

NPC reloads his equipment (I guess the same problem might be affecting electrical items).
There are already dialog settings for reloading CBMs.

NPC activates his equipment as needed (gas mask, shooter's earmuff, etc).

# Screenshots

![image](https://user-images.githubusercontent.com/26396019/100521916-2f6e7680-31a7-11eb-8d59-76706fbba4d7.png)
![image](https://user-images.githubusercontent.com/26396019/100521919-372e1b00-31a7-11eb-97f2-9ce595c838bd.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-7886-g76fd581 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Mythical Martial Arts [MMA],
    C.R.I.T Expansion Mod [crt_expansion],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Bionic Professions [package_bionic_professions],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP]
]

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
