### ISSUE TITLE
Smoking a ciggie causes Hiarchy view in inventory

### ISSUE THREAD

**Issue by slimeboy460** [CleverRaven/Cataclysm-DDA#45706]
# Describe the bug

From my findings with another player, smoking a cigarette causes it to swap over to hierarchy view (Accessible by pressing ; ). With that being said, wielding the cigarette causes it to be set back to the normal inventory, same with pressing ;.

# Steps To Reproduce

Have any list of items in your inventory
cigarette and a way to light it
smoke it using quick access (wielding an item doesn't matter)

# Expected behavior

The inventory should stay normal, rather than swapping to hiarchy view.

# Screenshots

# Versions and configuration

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-11014.
