### ISSUE TITLE
Wheel repair inconsistency

### ISSUE THREAD

**Issue by neosulc** [CleverRaven/Cataclysm-DDA#45719]
Wheels on a car can be fixed only with glue and plastic, when wheel is removed from the car it can be fixed by an arc welder.

Try to repair 17" wheel on a car, recipe asks for glue and plastic chunk.
Remove the 17" wheel, activate arc welder on a vehicle, repair the wheel without plastic chunks.

# Expected behavior

Allow repairing the wheel with an arc welder when on a vehicle.

# Versions and configuration

0.E-7920-ge62c502

**Comment by Hirmuolio** [comment]
The problem is that it is not possible to specify what is required to repair an item. IIRC is comes directly from the material of the item.

For installed vehicle parts the repair requirements can be specified.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
