### ISSUE TITLE
Unable to inject serum on NPC

### ISSUE THREAD

**Issue by Xaleth** [CleverRaven/Cataclysm-DDA#45718]
# Describe the bug
I had the insect serum and syringe in my inventory, and when I went to Apis in the beehive to use the serum on him, it doesn't show.

# Steps To Reproduce
Have insect serum and syringe
Go to NPC
Use item on yields no results on serum

# Expected behavior
Inject NPCs

# Versions and configuration

 - OS: Ubuntu 20.04
 - Game Version: experimental build #11192
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: dda

**Comment by Fris0uman** [comment]
You need to be allied to an NPC, and they nneed to trust you, to be able to give them mutagen. Apis is hostile so you can't do that.
