### ISSUE TITLE
Characater always "Very hungry"

### ISSUE THREAD

**Issue by Hazcap** [CleverRaven/Cataclysm-DDA#45715]
Character always seems to need food no matter what I feed them. After eating until Satisfied or full, the Very Hungry marker shows up after two-three in game hours, Hungry and Peckish have never showed up, instead instantly going from Satisfied to nothing to Very Hungry. Also sleeping While satisfied or full will switch the character to Very hungry after a few hours and show *I need to eat more calorie Dense food*, while the food eaten is not lacking of calories.

# Steps To Reproduce

Characters is Very Hungry
Eat Food until "Very Hungry" marker goes away or is replaced
Character is Very Hunger again after unreasonable amount of time

# Expected behavior

Characters is Very Hungry
Eat Food until "Very Hungry" marker goes away or is replaced
Character stays satisfied with food for reasonable amount of time
Character shows "Hungry" or "Peckish" before switching to "Very hungry"

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-7920-ge62c502 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Mythological Replicas [nw_pack],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by emptytriangle** [comment]
I have observed that only characters who are overweight can become "hungry". If you are not overweight, you are always very hungry. Peckish has never appeared in recent experimentals in any circumstance for me.

Despite having "light eater" and also the stomach CBM I am constantly shoveling MREs down my gullet to stay overweight, if I miss a day of eating I instantly become normal weight again. The only reason I am even alive is because I have alcohol metabolism and found a 30 gallon barrel of homebrew beer.

**Comment by natsirt721** [comment]
See #45257 and #41889. The fact that this keeps occurring indicates that it probably needs to be changed.

**Comment by KorGgenT** [comment]
you need to post your calorie tracker.

**Comment by anothersimulacrum** [comment]
To do that, open the debug menu, go to info, press check game state, and share the first thing that pops up.
You can then go into the game category of the menu, and re-enable achievements.

**Comment by emptytriangle** [comment]
![image](https://user-images.githubusercontent.com/74749287/100675734-83a76100-3335-11eb-863b-54b88c2a72c6.png)

**Comment by KorGgenT** [comment]
what happened on day 36? did you have a faster metabolism trait for part of that day?

**Comment by emptytriangle** [comment]
On day 36 I was probably stuck in a missile silo sleeping and recharging my CBMs with metabolic interchange while eating junk food from the kitchen and becoming heavily irradiated.

**Comment by KorGgenT** [comment]
ahh, metabolic interchange explains everything.
As you can see by the calorie tracker, you just aren't eating enough calories to replace the amount you use per day, on average. Very Hungry isn't a bug, it's literally telling you that you're very hungry and that you need to eat more calories. The metabolic interchange surely isn't helping.

**Comment by emptytriangle** [comment]
that doesn't explain why I never get hungry when I'm not overweight and it goes straight from not hungry at all to very hungry

**Comment by Nakilon** [comment]
I eat like 10 times per day and has the same "instant very hungry" issue. My "check game state" does not have such popup like you guys have on your screenshots. I also tried to find there anything about parasites but could not.
