### ISSUE TITLE
`Move all items` in the inventory in AIM removes magazines from worn guns

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#45717]
# Describe the bug

I use `,` when i want to drop all the loot from my inventory to my deathmobile. Accidentally that ejects magazines from the carried guns, even though the guns themselves are favorited. Curiously, the magazines loaded in the said guns cannot be `e`xamined in AIM, so the workaround (favoriting them) is cumbersome, requiring you to unload your gun first.

# Steps To Reproduce
Load the game, `/`, `,`, observe the magazine getting dropped from the inventory.

# Expected behavior
Guns, tools, and other things that can be loaded with some expendables shouldn't be unloaded like regular inventory pockets on `,`. 

# Screenshots

# Versions and configuration
07:47:37.837 :  GAME REPORT:
- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.E-7937-g2015b37956-dirty [64-bit]
- Graphics Version: Curses
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

# Additional context

[2020.04.12.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5611659/2020.04.12.zip)

**Comment by anothersimulacrum** [comment]
Fixed by #46203
