### ISSUE TITLE
Refrigerated tank (60L) isn't cooling liquids

### ISSUE THREAD

**Issue by Entity-y** [CleverRaven/Cataclysm-DDA#45710]
# Describe the bug
Using a refrigerated tank doesn't actually cool liquids and instead functions as a standard tank only with a power draw, maybe the insulation feature still works with it. In my current playthrough I'm just getting to the end of summer, water stayed hot inside of the refrigerated tank, not once have I been prompted to fill up with cold water.

# Steps To Reproduce
1. Set season to summer, spawn a vehicle, give hammerspace mutation.
2. Install refrigerated tank, fill with water.
3. Wait a few days with the tank turned on.
4. Fill a container with liquid and see that it's still water (hot)

# Expected behavior
Refrigerated tank should keep liquids inside cold.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-7886-g76fd581 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by AdamChirnside** [comment]
I've just discovered that the water inside the fridge-tank is cold.
Somehow the faucets are heating it up when it is dispensed.
