### ISSUE TITLE
Expand accepted food items at refugee center

### ISSUE THREAD

**Issue by Cddaissuereport** [CleverRaven/Cataclysm-DDA#45729]
# Is your feature request related to a problem? Please describe.
Not being able to turn in protein rations to the Broker is a real bummer.

# Describe the solution you'd like
Make the people of the refugee center recognize the value of protein rations. 

# Describe alternatives you've considered
Maybe add some more food items alongside the protein rations. 

# Additional context
If these 100 protein rations in my inventory are from a mod instead of the base game its understandable that they can't be traded in. If so, never mind.

**Comment by Xaleth** [comment]
@anothersimulacrum why the thumbs down?

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
