### ISSUE TITLE
Transition nutrition to kcal for good

### ISSUE THREAD

**Issue by Fris0uman** [CleverRaven/Cataclysm-DDA#45720]
# Is your feature request related to a problem? Please describe.

https://github.com/CleverRaven/Cataclysm-DDA/blob/90cab7a331b389510751d2dae621e6275f15ca58/src/character.cpp#L4989-L4993

Internally `mod_stored_nutr()` converts nutrition number to kcal before apllying the modification, but it means that values used in json, like the `cost` entry of mutation are still in `nutrition` instead of kcal it also means that each time the code calls `mod_stored_nutr()` it has to use `nutrition` value to avoid conveting twice.

# Describe the solution you'd like
Change all json value and internal value to kcal and remvoe the convertion from `mod_stored_nutr()`

# Describe alternatives you've considered
Maybe introduced cal as a `unit`

# Additional context
This is not high priority but I think it will make the code easier to maintain.

**Comment by Xaleth** [comment]
Or not convert to kcal at all and just display calories. Going through around a thousand different foods to change to kcal is imo a bit excessive for something so trivial.

**Comment by anothersimulacrum** [comment]
We already use kcal for all our food??

**Comment by Fris0uman** [comment]
Maybe food is in kcal, but from that snippet of code not everything is yet.

**Comment by Xaleth** [comment]
What if you just have `kcal` and `cal` as options in the world menu?

**Comment by KorGgenT** [comment]
i believe there are only a very small number of things that use nutrition, so it should be fairly painless to transition. i don't believe there is a single example of json that's using "nutrition" instead of calories.

**Comment by Fris0uman** [comment]
Any mutation that uses "hunger" as a cost is using nutrition, I don't know how many that is though.
