### ISSUE TITLE
Crash when trying to re-establish an abandoned camp

### ISSUE THREAD

**Issue by rawrmanawr** [CleverRaven/Cataclysm-DDA#45731]
I did not know how to add or edit zone in a faction camp, so I decided to abandon it and to create it again. At the time it did not have any upgrades, or anything else, except for a few loot zones. After being abandoned, my NPC had a dialog option: "We need to abandon this camp", which did nothing when clicked. He also had an option: "Something-something, this is your new job at the faction camp", which prompted "Enter the new camp name", and upon entering the name and pressing 'y', the game crashed.

Attached is the save with the bug. To reproduce, load in the only character there and head to the nearest shelter. Then talk to the NPC there.
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5613378/save.zip)

**Comment by BrettDong** [comment]
Crashed at `basecamp::parse_expansion` in `basecamp.cpp`
```c++
expansion_data basecamp::parse_expansion( const std::string &terrain,
        const tripoint_abs_omt &new_pos )
{
    expansion_data e;
    int last_bar = terrain.find_last_of( '_' );
    e.type = terrain.substr( base_camps::prefix_len, last_bar - base_camps::prefix_len );
    e.cur_level = std::stoi( terrain.substr( last_bar + 1 ) );
    e.pos = new_pos;
    return e;
}
```
where `terrain == "faction_base_camp_0_north"` so `std::stoi` fails.
