### ISSUE TITLE
Cannot reload water cannon

### ISSUE THREAD

**Issue by Xelat84** [CleverRaven/Cataclysm-DDA#45736]
# Describe the bug

Water cannon cannot be reloaded using water. It stays with zero charges. Neither pressing 'r' key nor selecting 'reload' option in item menu didn't do anything.

# Steps To Reproduce

1. Spawn 'fire_engine' vehicle.
2. Dismantle water cannon.
3. Have any source of water nearby, water well or river or gallon jug full of water.
4. Wield water cannon and press 'r'.

# Versions and configuration

- OS: Windows 7
- Game Version: 0.E-7914-g534b4dd [64-bit]
- Graphics Version: Tiles
- Game Language: Русский [ru]
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у NPC [no_npc_food],
    Simplified Nutrition [novitamins_fixed],
    Характеристики за навыки [StatsThroughSkills]
]

**Comment by emptytriangle** [comment]
also cannot be fired from vehicle turret, sees no ammo per #44672

**Comment by Xelat84** [comment]
> also cannot be fired from vehicle turret, sees no ammo per #44672

Weird, actually I have no problems using water cannon when it's mounted as a turret, at least in manual mode and of course if vehicle has some water in tanks. I have issues only when trying to use it alone from hands.

**Comment by kevingranade** [comment]
The water cannon is just a kind of nozzle, it's fully expected that you need water in vehicle tanks to use it, and there's no mechanism for operating it as a separate item.
