### ISSUE TITLE
Blood harvesting (in relation to Magiclysm mod)

### ISSUE THREAD

**Issue by Gremilcar** [CleverRaven/Cataclysm-DDA#45739]
# How often do you see this screen pop up?
![5bc8dae1c49c2ddf1597a0ca1ad618eb](https://user-images.githubusercontent.com/37850810/100650252-a6278300-3311-11eb-8227-8248a91768e5.png)

For many of us - way too much. While blood procurement is fine the UI handling of it deserves better.

# Describe the solution you'd like
@Fris0uman suggested, and I agree completely, to move corpse blood harvesting into a specialised option akin to skinning.

# Additional context
Butchering without draining blood would yield usual drops, sans blood, which would remove unnecessary clutter. Or for additional immersion, the blood can be instantly spilled on the ground and unrecoverable 

The aforementioned solution can be incorporated into the main game and provide a lot of features down the line.
- NPCs (dead or alive) can be drained of healthy blood, which can be used for blood infusions. This can allow bleeding wounds instead of damaging limbs to use something similar to health mechanic in terms of blood.
- Blood (Human/Animal/Zombie) can be used as an ingredient for cooking or chemistry.
- Expanded transfusion\injection mechanics (develop serums\antibodies, perform experiments banned by geneva convention etc)

# Describe alternatives you've considered
- Remove blood altogether and use some solid drops as magiclysm ingredients.
- Drop tainted blood in blood sacks 
- Make blood valuable enough that players would anticipate the additional menu pop up

**Comment by emptytriangle** [comment]
can we not just harvest it with a blood draw kit on a corpse

**Comment by Gremilcar** [comment]
We could, and it is an option too. Although I feel like a blood draw kit is something rather rare and would be better used to draw blood from willing participants (or as a sterile\precise sampling from a specimen). This is more about bulk harvesting imho.
