### ISSUE TITLE
Bionic armors provide more protections & more encumbrance

### ISSUE THREAD

**Issue by RedShakespeare** [CleverRaven/Cataclysm-DDA#45735]
# Is your feature request related to a problem? Please describe.
Bionic armors now provide 3 bash_protec, 3 cut_protec and 3 bullet_protec, which is directly inherited from Cataclysm and never changed since, while other statistics about melee attack have changed a lot. This cause a funny situation that these **sci-fi alloy plating armor** provides protections same as **paper armors** do, and in real game-play experience players rarely install these CBMs to their characters. 

# Describe the solution you'd like
Let bionic armors (XXX Alloy Plating CBM) provide more protections whilst cause more encumbrance(in order to rebalance game data).

# Describe alternatives you've considered
No alternatives yet...

# Additional context
Some pics.
![image](https://user-images.githubusercontent.com/44523519/100607701-48615e00-3346-11eb-9a6b-b18a4cfb9da2.png)
Paper armor

![image](https://user-images.githubusercontent.com/44523519/100607797-6fb82b00-3346-11eb-8c7b-caaf41f9815c.png)
Alloy plating CBM

**Comment by Fris0uman** [comment]
It's just json, do the edit and back it up with some argument and it might happen. here's the doc https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON_INFO.md#bionics you need to edit `bash_protec` and `cut_protec` maybe `bullet_protec` too.
And here's is the start json for those cbms https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/bionics.json#L41

**Comment by RedShakespeare** [comment]
> It's just json, do the edit and back it up with some argument and it might happen. here's the doc https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON_INFO.md#bionics you need to edit `bash_protec` and `cut_protec` maybe `bullet_protec` too.
> And here's is the start json for those cbms https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/bionics.json#L41

`bionics.json` can't do much about encumbrance...?
And yes maybe I should raise a pr rather than issue. Thx a lot!

**Comment by RedShakespeare** [comment]
Just found encumbrance in JSON_INFO.md. Thanks a lot!

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
