### ISSUE TITLE
Cannot craft mushroom seed from morel mushroom.

### ISSUE THREAD

**Issue by neosulc** [CleverRaven/Cataclysm-DDA#45741]
# Describe the bug

Cannot craft mushroom spores from morel mushroom, but can still cook the mushroom.
![The recipes mentioned:](https://i.imgur.com/tGdB1d0.png)

# Steps To Reproduce

Acquire mushroom. Try to craft seeds/spores, recipe is invalid.

# Expected behavior

Be able to craft mushroom seeds.

# Versions and configuration

0.E-7938-g8736e6b

**Comment by neosulc** [comment]
Addendum: said morel mushroom is in the freezer, frozen.

**Comment by PatrikLundell** [comment]
Many seed recipes are unavailable when the "plants" they would work on are frozen. Some work, but not all. I assume that is by design. I'd suggest you try to thaw your morel shroom and try again.

**Comment by neosulc** [comment]
> Many seed recipes are unavailable when the "plants" they would work on are frozen. Some work, but not all. I assume that is by design. I'd suggest you try to thaw your morel shroom and try again.

Thawing the mushrooms worked. 

I still consider this as a bug, as the UI does not show why it didn't work.

Proposed solution: Allow the recipe to be selected/started, and fail early with a message "The $item is too cold to be processed that way" before actually creating the "in process mushroom spores" and consuming the ingredients.

**Comment by PatrikLundell** [comment]
It's the same with a lot of recipes. Neither frozen milk nor frozen water can be used in a number of cases, and rotten items are usually not possible to use either. It's also similar to some recipes refusing to recognize items with battery charges in them, requiring that you first remove the battery or turn them off (some things can't even replace batteries unless they're turned off first).

I wouldn't call it a bug, but possibly an opportunity for an improved UI.

**Comment by neosulc** [comment]
> I wouldn't call it a bug, but possibly an opportunity for an improved UI.

Fair enough.
