### ISSUE TITLE
minireactor BUG v11203

### ISSUE THREAD

**Issue by TaTalia** [CleverRaven/Cataclysm-DDA#45747]
# Describe the bug
if minireactor is reloaded  with 10 charges of plutonium,
minireactor will have 5000 charges of plutonium!!!
I can get **5000 charges of plutonium** if unload minireactor!!!!!!!!!!!!!!!
It's big bug!!!  

# Steps To Reproduce

<!-- Steps to reproduce the behavior:
1. prepare 10 charges plutonium and 1 minireactor(no plutonium).
2. reload minireactor with 10 charges plutonium.
3. unload minireactor.
4. get 5000 charges plutonium.

**Comment by emptytriangle** [comment]
more info in #45702

**Comment by anothersimulacrum** [comment]
Duplicate of #45702
