### ISSUE TITLE
Salvaged Power Armor Tweaks

### ISSUE THREAD

**Issue by Vzor-** [CleverRaven/Cataclysm-DDA#45744]
# Is your feature request related to a problem? Please describe.
As I understand it, salvaged power armor is power armor with the internals removed. Currently depowered_armor gives a coverage of 95 as per a26a665 of #3489. This seems odd to me since it is still the same armor, just lighter and without environmental controls. I see this as a problem because due to the high encumbrance, this is likely the only piece of protection someone wears. With a 1 in 20 chance of taking full damage this armor is terrible since the nature of high armor/encumbrance means you will be taking many hits and losing stamina. 

# Describe the solution you'd like
The solution I do not think is as easy as changing the 95% to a 100%. There are some points to discuss.

1. With 100% coverage, the 6 environmental protection kicks in, should stripped armor still have 6 environmental protection?
2. This armor allows layering, should it? Will this armor be too powerful if it has both 100% coverage and layering?
3. This armor is only a 7% drop chance from armored zombies, is that too low for a zombie in power armor?

I like this item, it gives us something to drop from armored zombies without throwing around end game items. I think the drop chance should be 100% on the armor with something like a 60% on the helm. I also think rather then dropping this item it should drop a damaged (right now this item seems to only drop at full repair) 'Ruined Power Armor' that has a disassembly recipe just like normal power armor. Salvaged armor would then only be obtainable via disassembly. I would also assume 'Ruined Power Armor' would not be repairable, this makes salvaged armor a little rarer due to the recovery not being guaranteed from a damaged item.

# Describe alternatives you've considered
For the layer issue, I have heard 2 explanations as to why power armor is unlayerable. For outer layers, the armor is large (like mutant anatomy) and cumbersome making most items impracticable. For inner layers it is due to the armor being like a body glove. 
I understand why the layering limitation was removed, there is a lot more room in there now, but it seems like it only applies to the inner layers. It would take some cpp coding, but it would be pretty cool if this armor allowed items close to the skin, but not normal, outer or strapped.

# Additional context
In the future it would be interesting to allow items that are strapped and compatible with mutant anatomy to be worn with power armor. I just like the idea of wearing a cloak and power armor.

I also like the idea of eventually using this item to craft refurbished power armor using similar ingredients to that of a police bot.

**Comment by Vzor-** [comment]
These are my opinions on the issue

> 1. With 100% coverage, the 6 environmental protection kicks in, should stripped armor still have 6 environmental protection?

Yes, I think it should. Power armor that is turned off has it, so why not this.

> 2. This armor allows layering, should it? Will this armor be too powerful if it has both 100% coverage and layering?

I do not think this armor should be layerable, though it would be nice if we could wear things close to the skin or maybe even normal layer.

> 3. This armor is only a 7% drop chance from armored zombies, is that too low for a zombie in power armor?

I think and armored zombie should have a 100% chance of wearing some kind of armor. For balancing, the disassembly recipe takes time an tools while not guaranteeing the armor. Even with that, I would consider this a giant buff to the drops of armored zombies.

**Comment by Vzor-** [comment]
Some tests with different armors,

I stood in a field with a katana and spawned a size 5 mob of tough zombies. All stats are 10 and skills are 5. I held tab without moving, these are the results.

Kills with power armor: all, no damage takes.
Kills with salvaged armor: 11
Kills with survivor armor: 57
Kills with no armor: 5

It is worth noting that with hit and run tactics, the salvaged armor would have done even worse compared to the others due to the mobility and stamina issues.

**Comment by anothersimulacrum** [comment]
Total zombies: 121

**Comment by Vzor-** [comment]
As a note, I can make most of these changes myself. I just want a "go ahead" before making a pr that changes something that was intentionally tweaked.

**Comment by jokermatt999** [comment]
I would like to do a rework of armored zombies anyway. I was thinking they could use a hydraulic grab crush attack, armor/speed tweaks and maybe some CBM drops (but those may not work with Exodii lore?). Currently salvaged power armor is pretty useless. IIRC, current lore is power armor is supposed to be more exo skeletal as current tech is used for hauling. Would a makeshift power armor hauling frame be a feasible survivor project? Combine it with a large frame backpac , and used mostly for scavenging runs.

**Comment by anothersimulacrum** [comment]
> As a note, I can make most of these changes myself. I just want a "go ahead" before making a pr that changes something that was intentionally tweaked in a balancing commit.

My input, FWIW, is that if they're getting 100% coverage, they need to drop the ability to wear other clothes with it like other power armors.

> I would like to do a rework of armored zombies anyway. I was thinking they could use a hydraulic grab crush attack, armor/speed tweaks and maybe some CBM drops (but those may not work with Exodii lore?).

Yes, no new CBM drops.

**Comment by Vzor-** [comment]
I always imagined the outer armor being a very advanced articulated suit. kind of like the hideous ax-5 space suits from NASA.

**Comment by Vzor-** [comment]
"There is an integrated chemical resistant bodyglove that precludes wearing other clothing." that settles it, 6 env protection = no layering.

**Comment by kevingranade** [comment]
The rationale for the bad coverage was that the joint parts, being the most complex and difficult to articulate parts, are stripped out, therefore creating gaps.

The real underlying problem here is that you can operate in unpowered power armor, period.  The whole point of the stuff is that "you can carry an amount of armor it's infeasible to carry without assistance".  If it's not powered, it shouldn't be usable at all, but we erred on the side of permissiveness at some point in the past. That was IMO a mistake because it causes a ton of inconsistencies.

There's an intermediate weight that would be something you could wear/carry, but perhaps not fight in reasonably (ignoring the fact that this is completely opposite of what e.g. the US military is trying to do with exoskeletons).  Possibly it could have unsustainable encumbrance and weight, but if you're strong enough you could suffer through it for a while.

This is part of the reason for the mech suit, this acts a lot more like a powered exoskeleton is supposed to, and the intent was to get mech suits working and then *remove the other powered armor suits*, but we haven't gotten there yet.

**Comment by Vzor-** [comment]
> 
> 
> The rationale for the bad coverage was that the joint parts, being the most complex and difficult to articulate parts, are stripped out, therefore creating gaps.
> 
> The real underlying problem here is that you can operate in unpowered power armor, period. The whole point of the stuff is that "you can carry an amount of armor it's infeasible to carry without assistance". If it's not powered, it shouldn't be usable at all, but we erred on the side of permissiveness at some point in the past. That was IMO a mistake because it causes a ton of inconsistencies.
> 
> There's an intermediate weight that would be something you could wear/carry, but perhaps not fight in reasonably (ignoring the fact that this is completely opposite of what e.g. the US military is trying to do with exoskeletons). Possibly it could have unsustainable encumbrance and weight, but if you're strong enough you could suffer through it for a while.
> 
> This is part of the reason for the mech suit, this acts a lot more like a powered exoskeleton is supposed to, and the intent was to get mech suits working and then _remove the other powered armor suits_, but we haven't gotten there yet.

Am I god to peruse this as an interim solution?

**Comment by kevingranade** [comment]
> The final intention of power armor is out of scope of my abilities, for now I just want to bring this in line with current mechanics.

The current state of salvaged power armor is a compromise, you can't look at individual features in isolation and "fix inconsistencies" without addressing the compromise as a whole.  That kind of thing is how power creep happens.

> As it stands, the basic power armor can move its joints without power,

Sure let's fix that.

> Increase coverage to 100%

This is very much not ok, that makes it staggeringly good.

> Add 'Ruined Power Armor' as a drop in leu of this, with a disassembly recipe to get salvaged armor.

What are the stats of "ruined power armor"? Just power armor without the function to turn it on?

**Comment by Fosheze** [comment]
> > Add 'Ruined Power Armor' as a drop in leu of this, with a disassembly recipe to get salvaged armor.
> 
> What are the stats of "ruined power armor"? Just power armor without the function to turn it on?

From what I understand the ruined power armor that they're referring too would just be an unusable item dropped from armored zombies which could be disassembled in an attempt to get a suit of salvaged power armor. It couldn't be worn directly.

Also I personally agree with Kevin on the 100% coverage. It makes it far too good for what it is. However to your point 95% coverage overall makes it pretty pitiful in combat. So what about using the new individual body part coverage system. For parts of the body where there would not have been as many moving parts to remove such as the head, eyes and torso you could set the coverage to 100%. For the mouth you could set the coverage to 99% to basically show that while the mouth is completely covered it is no longer sealed to gasses. Personally I'm just imagining that as the survivor having drilled a bunch of breathing holes in the helmet to bypass the busted air filtration system. For body parts that require a higher degree of flexibility such as the legs, arms, and feet the coverage could stay set at 95% to represent the new weak points around the stripped down joints. As far as the hand go it would probably be best to remove hand coverage entirely. I don't see any way you could have unpowered gloves that have that heavy of armor/coverage and still remain maneuverable enough to so much as open a door. This would also serve to make the salvaged power armor more like a more heavily armored version of a real life EOD suit.
![Temp](https://user-images.githubusercontent.com/50811445/100790196-1222ed80-33dd-11eb-9bc0-52f41c8d65dd.jpg)
You might "survive" bomb blast in it but you still will be missing far to may bits of yourself to be comfortable. Likewise this would keep a player "alive" with the 100% torso and head coverage but they could still be whittled down enough to be rendered entirely ineffective.

**Comment by Vzor-** [comment]
Can we do coverage numbers that are not in increments of 5? I agree the armor is too good with a 100% coverage, though it is also important to remember than killing an armored zombie in the mid-game is no simple task. Also you are correct, the ruined armor would be seized up suit, unusable and unrepairable. The only use would be to disassemble it for components and potentially depowered_armor.

My goal here is to take salvaged power armor and make it a viable (good, even) option for mid game. It is a very interesting item thematically.

100% coverage is over powered, but on an item you cant layer, 95% is terrible. Would a possible solution be increasing the encumbrance?

Right now the combat exoskeleton is 100L and 121lbs. 100L is only about 60% more voluminous than a person, so ~17% longer, wider and deeper, and ~37% more surface area.  The 121 lbs seems low, but taking that number at face value, it isn't an unreasonable weight to walk in. according to https://www.jstor.org/stable/resrep20409 some soldiers carry 160lbs. It would definitely be encumbering, but with the drive motors removed from the joints, it wouldn't be impossible to move. 

It is a bit off topic, but a 10"x12" level IV ballistic plate weighs 6lbs. A human has just under 3,000 in^2 of surface area. If we increase that by 37% for the size increase mentioned earlier we get 4,110 in^2. That means it would take around 35 of those plates to cover this suit, totaling 210lbs. This is an over estimation of course, not every inch needs to be level IV.  So I guess 121 lbs seems within the realm of possibility, though definitely low. The weight of the motors would also need to be added.

**Comment by Vzor-** [comment]
Ok, I think this discussion is way outside of the scope of this issue. I want to start a thread about the future of power armor somewhere and possibly take on the task. From there I can come back to this issue and come to a more appropriate solution to making salvaged armor interesting and useful. Where would be an appropriate place, a GitHub issue?

**Comment by kevingranade** [comment]
If you want a discussion instead of a proposal for a fix, the two main options are the [discourse](https://discourse.cataclysmdda.org) and the [discord](https://discord.gg/jFEc7Yp)

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
