### ISSUE TITLE
Vehicle blueprints: save vehicle designs as blueprints to reconstruct or share

### ISSUE THREAD

**Issue by arockperson** [CleverRaven/Cataclysm-DDA#45743]
# Is your feature request related to a problem? Please describe.
You can tell NPCs to deconstruct or repair vehicles, but not actually build them. This would solve that, and potentially be useful for many other things.

Another problem this would solve is having to recreate (non-folding and non bike rackable) vehicles for easy storage. For example, you could save a blueprint of a hauling vehicle that you store in a bigger vehicle as raw materials, then quickly reconstruct it from the blueprint when needed.

# Describe the solution you'd like
The ability to save a vehicle design from the vehicle construction menu, to be recreated later or shared, etc. You could place a blueprint with Start Vehicle Construction From Blueprint in the construction menu. NPCs would be able to construct vehicles from blueprints, perhaps in a Vehicle Construction Zone. 

It would be really cool if vehicle designs could be stored as JSON (as in json/vehicles/vehicleblueprints/mycoolcar.json), so that you could use the same design in multiple playthroughs or easily share designs.

# Describe alternatives you've considered
Make it so you can add parts to a vehicle as blueprints, in order to plan future additions, or just to create a blueprint from scratch. This would be really cool, of course, but it seems like the kind of thing that would need a rework of the vehicle construction system.

# Additional context
Sorry to be the "idea guy" so much here. This is certainly not an original idea, but I couldn't find anything about it on github.

I understand that there already is some kind of blueprint system for vehicles in the game, so hopefully it would be possible for player blueprints to tie in to that system / make it accessible in game.

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
