### ISSUE TITLE
Monster(s?) increased diagonal move speed with Circular Distances, not decreased.

### ISSUE THREAD

**Issue by Whiskiz** [CleverRaven/Cataclysm-DDA#45768]
# Describe the bug:
Some enemies such as the Bio-Operator moves not only not slower when moving diagonally with Circular Distances enabled, but faster - similar but a little slower speed stats with the player and it moving diagonally while the player is moving straight and it will actually catch up quickly still.

Disabled Circular Distances will see both keep about the same space in a straight line and diagonally alike like it should, going by the numbers.

# Steps To Reproduce
Make a base character, go out onto an open field, spawn a Bio-Operator diagonally 10 or so spaces away and while you run away in a straight line - notice how not only is he not slower while running at you diagonally, but he’s actually going faster and again catches up to you in short order.

# Expected behavior
Bio running diagonally with the player running straight, CD enabled, the player should easily outpace the Bio. Straight lines and CD enabled and you keep similar pace, disabled both keep similar pace - it just seems to be diagonal movement with CD enabled.

build 11203 from 2 days ago - 0.E-7938-g8736e6b (tiles) but has been like this for a week or so, so a few experimentals at least.

**Comment by AnonimusC** [comment]
View discussion here: https://discourse.cataclysmdda.org/t/have-zombies-speed-been-increased/25431/5
Maybe including this in the terms of topic? I would be to delete my message then.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/have-zombies-speed-been-increased/25431/34

**Comment by anothersimulacrum** [comment]
Could not reproduce.
Here's a save file for each case, I got the same behavior walking to the west in the second example as I did walking to the southwest in first (the bio-operator didn't touch me). 
[diagonal.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5630444/diagonal.zip)
[straight.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5630445/straight.zip)

**Comment by kevingranade** [comment]
Also could not reproduce.  I did see some jitter occasionally where the bio-op would "leap" ahead by two tiles and then not move the following turn, but that's expected because when moving diagonally the character is regularly missing turns and so is the bio-op.
