### ISSUE TITLE
When buying container item it might contain items you paid with

### ISSUE THREAD

**Issue by Mrzjadacz** [CleverRaven/Cataclysm-DDA#45772]
# Describe the bug

Bought a dimensional toolbelt from Forge Lord.
It contained items I paid him with.

# Steps To Reproduce

Spawn Forge Lord (the best to test this specific bug due to the high amount of expensive items and not wearing separate storage items)
Trade high volume of items while buying containers he's wearing/using
The items you paid with will be in the bought container

# Expected behavior

Items traded are only stored in containers after the trade is finished

# Screenshots

![image](https://user-images.githubusercontent.com/26396019/100850879-bb70ee80-3484-11eb-87eb-58e0076af198.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-7886-g76fd581 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Mythical Martial Arts [MMA],
    C.R.I.T Expansion Mod [crt_expansion],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Bionic Professions [package_bionic_professions],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP]
]

**Comment by RoyBerube** [comment]
Am working on this. It is mostly done; I just need to do some cleanup and testing.
