### ISSUE TITLE
Basket Weaving Unlearned?

### ISSUE THREAD

**Issue by slimeboy460** [CleverRaven/Cataclysm-DDA#45776]
# Describe the bug

Whenever you do proficiency crafting in the category of basket weaving it will cause it to go down into the negative numbers.

# Steps To Reproduce

Simply make any object requiring basket weaving
I did straw sandals and a straw hat.

# Expected behavior

It should tick up, not tick down.

# Versions and configuration

# Additional context

**Comment by anothersimulacrum** [comment]
Cannot reproduce
