### ISSUE TITLE
Magiclysm - Similar Stat Rings of different values (+1/+2/+3/+4) can all be worn at the same time

### ISSUE THREAD

**Issue by ElfLeaderMike** [CleverRaven/Cataclysm-DDA#45774]
# Describe the bug
You can equip multiple rings of STR/DEX/INT/PER  of the same stat as long as the enchantment is different.

# Steps To Reproduce
Put +4 ring on.
Put +3 ring on.
Put +2 ring on.
Put +1 ring on.
Bam +10 to a stat.

# Expected behavior
A message saying you can only equip one ring of this type and preventing you from equipping said "bonus" rings.
You are not allowed to stack stat rings of the same value (no 2x +4 rings) so I don't believe stacking different values is intended.

# Screenshots
![image](https://user-images.githubusercontent.com/22645231/100868499-b18dc200-3469-11eb-9b07-4f8f08c167e9.png)

# Versions and configuration

- OS: Windows
- OS Version: Windows 7 Professional 64-bit
- Game Version: 0.E-7920-ge62c502 [64-bit]
- Graphics Version: Tiles
- Game Language: English
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP]
]

# Additional context
The hand the rings are equipped on doesn't seem to matter, can stack it all on one hand or split rings between both hands.

**Comment by casswedson** [comment]
Fixed by #47518
