### ISSUE TITLE
make [/usr/local/android-sdk/ndk ... arm64-v8a/objs/main/relic.o] Error 1

### ISSUE THREAD

**Issue by linonetwo** [CleverRaven/Cataclysm-DDA#45770]
# Describe the bug

https://ci.narc.ro/job/Cataclysm-Android/11079/console

<img width="1443" alt="截屏2020-12-02 下午4 18 57" src="https://user-images.githubusercontent.com/3746270/100846943-17a23580-34ba-11eb-860b-29ed1f871762.png">

# Steps To Reproduce

Recent Android build all failed...

# Expected behavior

Android build success with all the MacOS build.

# Versions and configuration

 - OS: Android
 - Game Version: Experimental 11203

# Additional context

I view https://cataclysmdda.org/experimental/ and hope there is an Android release everyday...

**Comment by BrettDong** [comment]
Build machine ran out of disk space. 😅 

In the meantime there is a guide of cross-compile from Linux to Android in [COMPILING.md](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/COMPILING/COMPILING.md#cross-compile-to-android-from-linux) you can try if you want.

**Comment by linonetwo** [comment]
I have Mac Machine, I tried to use Android studio in MacOS to compile Android apk today, but didn't figure out how to do...When open CDDA repo using Android Studio, the ▶️ button is gray can't click.

**Comment by linonetwo** [comment]
What can we do to help this out of disk problem?

**Comment by BrettDong** [comment]
A possible way is to build Android apk on Travis CI or GitHub Action, if you can figure out how to do so.

**Comment by BrettDong** [comment]
Closing this as Android experimental builds successfully in https://ci.narc.ro/job/Cataclysm-Android/11115/

**Comment by BrettDong** [comment]
I found this guide that may help: https://www.aloxaf.com/2020/11/cdda_compile_android/

**Comment by linonetwo** [comment]
Great! I think if it fails constantly next time, I will try this. But signing is a pain. To switch from official build to custom build, I have to do a backup and uninstall reinstall and restore saves and mods, which is annoying.

So I always hoping the official build can be constant.
