### ISSUE TITLE
Attempting to light a fire drops logs from firewood source next to oven, instead of inside.

### ISSUE THREAD

**Issue by nathanbigbob** [CleverRaven/Cataclysm-DDA#45788]
# Describe the bug
I have a couple logs in a firewood source along with tinder, a few tiles away from an oven I have used to cook for the last few days now. I attempt to light a fire with a fire drill on the empty oven tile, and the logs get dropped in the corner next to it on a cupboard, and I get the message "There's nothing to light there." This worked as expected yesterday. I haven't updated since the last experimental build 4 days ago.

# Steps To Reproduce

1. Find an oven
2. Mark a firewood source nearby and drop some logs inside with tinder
3. Try to light a fire on the oven
4. Honestly I don't think this is that easy to reproduce, this works as expected if I grab and move the oven and put it back, but only for about 3 fires.
5. Other houses with ovens work totally fine with the exact same setup.

# Expected behavior
The fire starting should definitely work 100% of the time, especially since it worked fine just yesterday and before that.

# Screenshots

![Screenshot (34)](https://user-images.githubusercontent.com/75422252/100996860-95e8f100-3527-11eb-823b-5db4f434efc0.png)
Fire source with logs and oven^
![Screenshot (35)](https://user-images.githubusercontent.com/75422252/100996869-997c7800-3527-11eb-9ba2-e676208e7cef.png)
Attempting to light fire with fire drill^
![Screenshot (36)](https://user-images.githubusercontent.com/75422252/100996882-9c776880-3527-11eb-9f08-becd239dd006.png)
Logs are dropped next to oven in the corner. "There is nothing to light there" ^

Sorry I didn't zoom in more.

# Versions and configuration

 - OS: Version	10.0.18363 Build 18363
 - Game Version: 0.E-7938-g8736e6b        Build 11203
 - Graphics version:  Retrodays+ (is that right?)
 - Ingame language: English
 - Mods loaded: StatsThroughSkills, Dark days of the dead, Crit Expansion, Speedydex, Graphical Overmap, Alt map key

# Additional context

This is my first post so I don't know If I did it right, I apologize for any problems. I don't how to post my save file, I assume I need to compress it into a zip file first, if you really need it.

**Comment by adamdeno** [comment]
The logs have more volume than the oven , break the logs with an axe into smaller pieces

**Comment by nathanbigbob** [comment]
> The logs have more volume than the oven , break the logs with an axe into smaller pieces

Hey that makes a lot of sense! I could have sworn I could put logs in the oven a few days ago, but I could have just been putting in random sticks left in the wood pile instead. That's pretty embarrassing.

I think there should be a message telling me the logs don't fit though. I know for a fact you could put logs in an oven on the last stable branch.

**Comment by Zireael07** [comment]
Logs volume was increased recently because one of the recipes to create them violated conservation of mass.
