### ISSUE TITLE
Can setup ladders inside vehicles which causes weird behaviour 

### ISSUE THREAD

**Issue by adamdeno** [CleverRaven/Cataclysm-DDA#45784]
# Describe the bug

if you have a stepladder in the ground and activate then place it inside a vehicle , you wont be able to retrieve it back , until you remove the vehicle parts on said ladder , idk about vehicle movement? i moved ONCE and it didn't change position "i assume"

# Steps To Reproduce

1. find a vehicle with a tile that has (aisle , roof , frame )
2. get a step ladder
3. you can activate it inside a vehicle

# Expected behavior

you shouldnt be allowed to even place it in a vehicle anyways

# Screenshots

no need for screen shots , self explanatory 

# Versions and configuration

 - OS: Windows 10 
 - Game Version: 0.E-7938-g8736e6b
 - Graphics version: Tiles
 - Ingame language: default
 - Mods loaded: city mod , stats through s/kills (both) , more military professions

**Comment by emptytriangle** [comment]
wonder if it's the same for cots, atomic butter churn, etc

**Comment by Tairesh** [comment]
![image](https://user-images.githubusercontent.com/1105196/120806730-a6bf0180-c560-11eb-95c6-534b89df6742.png)

You can place the stepladder in any tile where you can move, including vehicle doors, seats, containers, etc. After placing stepladder become inaccessible and can't be removed or used to climb up. When a vehicle starts moving it's just smashing the stepladder.

Bug still exists in fe42098 at least
