### ISSUE TITLE
Add filter/lookup to traits window of character creation

### ISSUE THREAD

**Issue by ElfLeaderMike** [CleverRaven/Cataclysm-DDA#45786]
# Is your feature request related to a problem? Please describe.
The trait list is starting to get pretty long! Sometimes I know what traits I want to add but I have to page down/scroll through the whole list to get to them. Who knows how many traits we'll have in 5/10/15/etc years!

# Describe the solution you'd like
Use AIM like filters to quickly sort/list traits.
Maybe with search options like....
p:+3 (points filter, all traits that give +3 points) 
d:movement (description filter, all traits that include movement in its description)

# Describe alternatives you've considered
I have not considered alternatives.

# Additional context
There's likely plenty of ways traits can be organized and sorted. In the future I imagine the list will be MUCH longer and a lot scarier for less hardcore folks to look through. Although the list is still fairly easy to navigate, it only grows with time.

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
