### ISSUE TITLE
Please add the ability to install curtains on quarterpanels

### ISSUE THREAD

**Issue by Torres84f** [CleverRaven/Cataclysm-DDA#45780]
# Is your feature request related to a problem? Please describe.
I've always wondered why was I unable to install windows there since they're not full panels but 3/4 solid and 1/4 window, I tend to sleep nomad style inside my car because I usually travel a lot for specific looting places like bases and such.

The actual option is to carry a blindfold and blind myself to sleep if I happen to tire out while there's light instead of not letting mobs from see the interior of the car 

# Describe the solution you'd like
Unless there's an issue a simple "WINDOW" tag on quarterpanels solved it for me 

# Describe alternatives you've considered
Still learning the basics so I'm a bit lost with downloading the GIT and doing a pull request so I'm just requesting it  =)

# Additional context
![curtains EVERYWHERE](https://user-images.githubusercontent.com/15707408/100957761-fe79a300-3512-11eb-82d6-ab3685cbd7aa.jpg)

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
