### ISSUE TITLE
Available build not loading

### ISSUE THREAD

**Issue by SirClarke** [CleverRaven/Cataclysm-DDA#45792]
It will not load past the Available build number 11203

Open the Launcher

Download the new update

![image](https://user-images.githubusercontent.com/31796878/101052588-cdba5d80-3554-11eb-9b7c-691165500074.png)

Not sure how much this helps

**Comment by SirClarke** [comment]
Not sure this helps but on here http://gorgon.narc.ro:8080/job/Cataclysm-Matrix/ It says some of the builds have failed but I don't know if that matters...

**Comment by anothersimulacrum** [comment]
We don't have any relation to the launcher, you should report this at their repo https://github.com/remyroy/CDDA-Game-Launcher/issues.

**Comment by SirClarke** [comment]
Thanks for the help still I'll give it a try
