### ISSUE TITLE
when using the console inside a church to ring bells , doesnt force quit the console when selecting once , and sound adds up as you spam enter.

### ISSUE THREAD

**Issue by adamdeno** [CleverRaven/Cataclysm-DDA#45796]
# Describe the bug

in one of the churches was a console , upon showing the 3 bell options , pressing enter doesnt quit the page , you have to manually leave the page by pressing esc or something , HOWEVER if you spam enter on all the choice multiple times then quit the page.... sound gets super high almost gave me a heart attack

# Steps To Reproduce

1. find a church (the one i found had a really high tower)
2. find a working console 
3. proceed with caution as you might injure your ears from spamming it  (if you have @'s soundpack on)

# Expected behavior

ONCE, only ONCE and it should force quit the console not to unexpectedly scare me

# Screenshots

![image](https://user-images.githubusercontent.com/41305926/101079727-89f54180-35b0-11eb-8d8b-63761799356d.png)

# Versions and configuration

   - OS: Windows 10
   - Game Version: 0.E-7938-g8736e6b
   - Graphics version: Tiles
   - Ingame language: default
   - Mods loaded: city mod , stats through s/kills (both) , more military professions

# Additional context

the sound also is played multiple times when its only one bell if you play a sound then quit page then play a sound again and again

**Comment by anothersimulacrum** [comment]
Fixed in #47987
