### ISSUE TITLE
Make tails not prevent wearing kneepads/leg guards

### ISSUE THREAD

**Issue by KittyTac** [CleverRaven/Cataclysm-DDA#45793]
# Is your feature request related to a problem? Please describe.
It always bothered me. Why would having a tail prevent wearing things that don't cover your buttocks? It doesn't affect balance much (kneepads and leg guards are pretty weak armor) but it would give mutants a minor buff as well as adding realism.

# Describe the solution you'd like
Give those categories of legwear a flag that allows wearing them while having a tail mutation.

# Describe alternatives you've considered
None? This is the easiest and most practical way to solve the issue as far as I understand it.

**Comment by emptytriangle** [comment]
Magiclysm cloaks are also prevented from being worn by tails

**Comment by Mrzjadacz** [comment]
Current implementation blocks you from wearing leg-covering items not made entirely of soft textiles (maybe only cotton).
Maybe it could be replaced with a flag for a tail?

**Comment by satheon49** [comment]
The cloak(s) are probably an oversight. Most cloaks have the OVERSIZE flag that allows them to be worn by any mutant and I could find only a single cloak that does not have that flag: cloak_morthylla.

As for knee pads/leg guards another solution could be to just have leg items on the BELTED layer not interfere with mutations of type "TAIL". Skimming through the list of BELTED leg armor there are only 2 candidates for which this change would be strange: suitcase and giant novelty backback. 
The suitcase is OVERSIZE anyway so could be worn with a tail regardless leaving only the giant novelty backpack.
