### ISSUE TITLE
Arrows and bleeding

### ISSUE THREAD

**Issue by dissociativity** [CleverRaven/Cataclysm-DDA#45805]
# Is your feature request related to a problem? Please describe.
Currently a bow is no better at causing bleeding than a slingshot, a lot of meaningful bow damage to a living, bleeding organism that doesn't hit anything vital would no doubt be caused by bleeding, at least with arrows that aren't relatively blunt and are reasonably well constructed.

# Describe the solution you'd like
bleeding scaling factor to ammunition, bladed/sharp ammo types with large surface area being particularly effective for the damage they do at this.
ie: at "2" an arrow that has done 10 damage will cause the equivilant bleeding status as if it had done 20.

# Describe alternatives you've considered
Having bows be worse than slingshots for characters that aren't in peak human condition, and all arrows be seemingly blunt
An alternate overhaul of bows, making them less absurdly underpowered even with high end arrows, and making them more feasible for characters that aren't olympic class athletes.

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
