### ISSUE TITLE
NPC shouldn't talk when you sleep and if they need it, go to sleep at the same time as you

### ISSUE THREAD

**Issue by Salty-Panda** [CleverRaven/Cataclysm-DDA#45809]
# Describe the bug

I go to sleep, my NPC (Sadie from Aftershock) can't stop talking. When I wake up, she's sleeping.
Of course, I prefer to be able to sleep without resolving to deafening myself.

# Steps To Reproduce

Get an NPC or a few, go to sleep, get disturbed by them.
Either by random mumbling or by those "Move aside"

# Expected behavior

NPC stays quiet when you sleep.

In addition: If NPC is sleepy, it should go to sleep when you do (though you might want your group to take turns using a specific bed). If the player wants an NPC to keep guard, an override order can be used.

# Screenshots

![image](https://user-images.githubusercontent.com/26396019/101187422-a64aba00-3654-11eb-958a-1274ab820b4a.png)
Sadie's traits:
![image](https://user-images.githubusercontent.com/26396019/101187664-f1fd6380-3654-11eb-9840-6e321534e05a.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-8007-gf58e7a4 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Mythical Martial Arts [MMA],
    C.R.I.T Expansion Mod [crt_expansion],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Bionic Professions [package_bionic_professions],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP]
]

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
