### ISSUE TITLE
Robotic tow trucks and robo-scrapyards

### ISSUE THREAD

**Issue by narc0tiq** [CleverRaven/Cataclysm-DDA#4580]
In an IRC discussion, I was reminded of #4403 making some progress towards making vehicles able to tow other vehicles, and paired this with the stated intent to have AI-driven vehicles to create... the Robo-Tow!

These robotic tow trucks would start at a "home" location and slowly scan around a section of the map, picking up abandoned vehicles and bringing them back to their home site.

Uncertain how to decide whether a vehicle is abandoned -- probably check it for lack of engine/wheels/fuel, perhaps also a "must not be stopped in the middle of the road" check? It might make parking lots useful if they're exempt from the abandoned vehicle check (player should leave car in a parking lot if they don't want it towed away).

**Comment by illi-kun** [comment]
We need reliable towing before this suggestion can happen so let's postpone this for some time.
