### ISSUE TITLE
NPC stops reading to follow me when I go downstairs

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#45819]
# Describe the bug

After asking my NPC friend to study from a book, when I go downstairs, a few moments later the NPC follows me downstairs, though they should still be reading and learning from the book.

# Steps To Reproduce

1. Have an NPC follower
2. Give them a book they can learn a skill from
3. Tell the NPC to study from the book
4. Wait a few minutes, wander around and see they continue reading
5. Go downstairs, and wait a few turns - NPC follows you down
6. Ask about their activity, and they will say "I'm not doing much currently"

# Expected behavior

NPC should continue reading until they reach the next level of the book's skill, unless they are interrupted by a hostile or a loud noise. They don't need to stop reading and follow me downstairs - it's none of their business what I do down there!

# Screenshots

German claims to be reading:

![image](https://user-images.githubusercontent.com/238395/101223829-2b7ca180-364a-11eb-8b43-7c2513b3bdba.png)

Go downstairs, and three seconds later... hey German, weren't you reading a book?

![image](https://user-images.githubusercontent.com/238395/101223870-451de900-364a-11eb-9d40-df0a499c46d4.png)

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-7956-gd2975b6f98 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

**Comment by olanti-p** [comment]
#43982
