### ISSUE TITLE
Be considered crouched while sleeping

### ISSUE THREAD

**Issue by satheon49** [CleverRaven/Cataclysm-DDA#45817]
# Is your feature request related to a problem? Please describe.
I got the idea from #45780 and my own tendency to crouch inside cars before sleeping or to break line of sight. 
Currently we are basically sleeping on our own two feet instead of lying down and benefiting from whatever cover we have nearby.

# Describe the solution you'd like
While trying to fall asleep or sleeping your movement mode should be set to crouch and set back to whatever it was before when waking up.

# Describe alternatives you've considered

Giving sleep its own cover threshold (probably even better than crouching and keeping it disconnected from movement modes.

**Comment by thomasrwisneski** [comment]
Make me wonder if in addition to crouching, there should be a prone option as well?

**Comment by J-Cieplinski** [comment]
Can we get the stale label off?
