### ISSUE TITLE
Game hangs for a couple seconds when approaching my base after being far away from it.

### ISSUE THREAD

**Issue by Scorch-Mechanic** [CleverRaven/Cataclysm-DDA#45822]
# Description 

I can always tell when I'm close to my base when returning from a raid because the game hangs for a couple seconds when I get close enough to it that the floodlight starts rendering visibly. I remarked about the slowdown when I approached my base in the #CDDA-Discussion channel on the dev discord and KorGgenT told me I should submit my save file and computer specs for profiling. You'll find both attached at the bottom.

# Steps To Reproduce

1. From the loaded save, travel directly northwest. On foot, or take the Raid SUV if you like. Either should work.
I've scribbled on the ground where to start, and approximately the point where the slowdown occurs from that starting point.
2. Observe a slowdown.
3. Optionally, travel very far away from my base (traveling southeast past the lab entrance a bit works for me).
4. Return to my base, observing the slowdown again.

# Expected behavior

The game to not hang for a couple seconds while I'm driving at 50 mph towards my base (AKA: big solid thing I don't want to crash into), or generally at any time I get close to it after being far away from it for a while.

# Versions and configuration

Tileset: Brown Like Bears

18:56:34.277 :  GAME REPORT:
- OS: Windows
    - OS Version: 10.0 1909 
- Game Version: 0.E-8007-gf58e7a4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Mythical Martial Arts [MMA],
    Alternative Map Key [alt_map_key],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    No Fungal Monsters [No_Fungi]
]

# Specs
Motherboard: MS-7A12
CPU: i5-6600K @ 3.50 GHz, running a mild preset overclock to 4 GHz
RAM: 16 gigabytes
Graphics: NVIDIA GTX 2080 Super 
SSD: Operating system and game are both kept on an SSD.

# Additional Context

[slowdown save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5646388/slowdown.save.zip)

**Comment by satheon49** [comment]
Here is a performance analysis from executing the described action:
![perf_analysis](https://user-images.githubusercontent.com/75445240/101237605-81008f00-36da-11eb-9707-51244db54bd6.png)

**Comment by ZhilkinSerg** [comment]
Let me guess you are a hoarder (like basically all the rest).

**Comment by Scorch-Mechanic** [comment]
Like all the rest, yes.

**Comment by Aivean** [comment]
I remember we discussed not saving empty pockets, perhaps it's time to actually implement that.

**Comment by int-ua** [comment]
Should be fixed by #46763
