### ISSUE TITLE
Your joint is quenched by water (when in a boat)

### ISSUE THREAD

**Issue by emptytriangle** [CleverRaven/Cataclysm-DDA#45827]
# Describe the bug
When you smoke in a boat, your stoge goes out.

# Steps To Reproduce
Burn one down in a boat. It will get wet and go out.

# Expected behavior
Survivors can row out into a lake and smoke while fishing.

**Comment by thomasrwisneski** [comment]
Working on this currently.

**Comment by emptytriangle** [comment]
thanks for the fix my dudes
