### ISSUE TITLE
Multiple ammunition types in magazine/cylinders.

### ISSUE THREAD

**Issue by thomasrwisneski** [CleverRaven/Cataclysm-DDA#45832]
# Is your feature request related to a problem? Please describe.
Magazines are unable to be loaded with more than one type of compatible ammunition.

# Describe the solution you'd like
Weapon magazines should be able to accommodate multiple types of compatible ammunition. For instance, one should be able to load several 9x19mm JHP rounds into a magazine, followed by several 9x19mm FMJ rounds. To add even more complexity/realism, if one had a revolver with multiple ammunition types loaded in the cylinder, one could rotate the cylinder to select the next type of ammunition.

# Additional context
It's something that is possible and is done (uncommonly) in real life, usually in handguns and shotguns. This change would allow consolidating ammunition in a single magazine when ammunition is scarce. It would also allow the player the flexibility to have their first shot be of one ammo type, second of another, etc. as desired.

**Comment by anothersimulacrum** [comment]
Please follow the issue template.

**Comment by kevingranade** [comment]
Loading multiple ammo subtypes into guns, sure, that prevents artificial limitations on being able to fully load magazines when ammo is scarce.
Adding a UI for any kind of select-fire management, no thanks.  It's a very micromanagey thing that isn't a particularly reasonable thing to attempt in combat.

**Comment by actual-nh** [comment]
Actually, in terms of tracers (whether flame or smoke), it's by no means uncommon to mix things (although not with any selectivity in mind!). The standard mix is 1 in 5, as far as I know.
