### ISSUE TITLE
Creating huge numbers of 3L bone broth on workbench labeled "too heavy"

### ISSUE THREAD

**Issue by Torres84f** [CleverRaven/Cataclysm-DDA#45839]
Crafted 19 units of 3L bone broth using the workbench but it was labeled as too heavy and gave me a penalty to crafting

# Steps To Reproduce

1.-Create 19 units of 3L bone broth on the workbench

# Expected behavior

# Screenshots
![1](https://user-images.githubusercontent.com/15707408/101266806-5f3ef080-374a-11eb-9517-7000fc061322.jpg)

# Versions and configuration

22:34:39.065 :  GAME REPORT:
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-8007-gf58e7a4 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Mining Mod [Mining_Mod],
    Dorf Life [Dorf_Life],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    DinoMod - UndeadPeople Tileset [DinoModUDP],
    Dorf Life - UndeadPeople Tileset [Dorf_LifeUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm]

# Additional context

**Comment by PatrikLundell** [comment]
When starting to craft something an "in progress" item is generated. If you break off crafting for any reason, you can only continue by picking this item up and then activate the item, thus continue crafting in your hands. The issue here is that you can't activate the item while it's still on the workbench (if your fire burns out while you're boiling water, you similarly have to pick up the "in progress" warm water to continue the process once you've got a fire again).

For "remote" activation to work properly, there would have to be some kind of logic to determine whether it's possible to craft the item in that location.

**Comment by Torres84f** [comment]
> 
> 
> When starting to craft something an "in progress" item is generated. If you break off crafting for any reason, you can only continue by picking this item up and then activate the item, thus continue crafting in your hands. The issue here is that you can't activate the item while it's still on the workbench (if your fire burns out while you're boiling water, you similarly have to pick up the "in progress" warm water to continue the process once you've got a fire again).
> 
> For "remote" activation to work properly, there would have to be some kind of logic to determine whether it's possible to craft the item in that location.

I didn't break crafting though I hit the dot to stop the screen to get the message when it showed in that bright red color, but I get what you mean.
I reported a similar thing happening with storage batteries and it got fixed.

**Comment by Zireael07** [comment]
Pressing . or 5 to interrupt means exactly 'to break crafting'.

**Comment by Torres84f** [comment]
> 
> 
> Pressing . or 5 to interrupt means exactly 'to break crafting'.

Have you tried? can you confirm it or not?

**Comment by Joar80** [comment]
I'm having the same issue crafting wooden panels. If I try making too many at a time I'll get the message about in-progress wooden panel being too large and/or heavy to work on comfortably, and I'm working slowly. 
10 at a time works fine. 20 is too many.

Also you can continue an in-progress item if it is on a table(and I assume workbenches and similar), Examining the table and choosing Work on craft.


- OS: Windows 10
    - OS Version: 10.0 2004
- Game Version: 0.E-8079-g47fa519 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

**Comment by NetSysFire** [comment]
Can not reproduce.
