### ISSUE TITLE
Mending faulty CBMs will not give skill xp

### ISSUE THREAD

**Issue by neosulc** [CleverRaven/Cataclysm-DDA#45834]
# Describe the bug

Mending CBMs should reward some skill xp, alas it does not.

# Steps To Reproduce

1. Have health care skill 4. 
2. Get pre-owned CBMs.
3. Wash them.
4. Mend them. 
5. Observe that health care xp has not increased even after mending 4-5 cbm.

# Expected behavior

Skill level increases somewhat.

# Versions and configuration

8007-gf58e7a4

**Comment by thomasrwisneski** [comment]
Noticed a possible typo in faults_bionic.json:
"mend_fault_bonic_salvaged_reset"
Not sure if it's related. Investigating

**Comment by thomasrwisneski** [comment]
Typo appears unrelated. Currently implementing a fix. Should also add skill xp for mending guns.

**Comment by Entity-y** [comment]
CBM mending shouldn't increase health care, instead it should raise mechanics skill.

**Comment by thomasrwisneski** [comment]
The change I'm currently testing will have mending skill up whatever skills are necessary to do the mending. One detail I'm not sure on is what kind of skill increase is appropriate for something like this. I currently set it to a value of 5, but I don't really have much context for what that means.

**Comment by thomasrwisneski** [comment]
Upped the xp to 10 and submitted the change
