### ISSUE TITLE
`REACTOR`+`PERPETUAL` flags' combination in `vehicle_part` does not generate power as intended

### ISSUE THREAD

**Issue by Kenan2000** [CleverRaven/Cataclysm-DDA#45846]
# Describe the bug
`REACTOR`+`PERPETUAL` flags' combination in arbitrary `vehicle_part` does not generate power upon being turned on 

# Steps To Reproduce

1. Make a fuel, ammo-fuel, generator `vehicle_part`, add `REACTOR` and `PERPETUAL` flags to the generator `vehicle_part` as well.
2. Install the generator `vehicle_part` to an arbitrary vehicle.
3. Turn on the generator and notice how it produces no electrical energy/power no matter what.

# Expected behavior

Turning the generator on would produce electrical energy/power because it is stated so in the `JSON_FLAGS.md`:
```PERPETUAL - If paired with REACTOR, part produces electrical power without consuming fuel.```

# Screenshots
None

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-8013-g170da18 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context
Moreover, I've tried removing `location` part of the JSON code of the `vehicle_part`, replacing `engine_block` with `fuel_source`, replacing `fuel_type: uberpower` with plain `fuel_type: null` - none of that worked in this case

This is the JSON code of the vehicle part that I've generated that I'm currently testing and which is not working as intended, as stated above:

```[
{
    "type": "material",
    "id": "uberpower",
    "name": "uber core",
    "copy-from": "pseudo_fuel",
    "fuel_data": { "energy": 1, "perpetual": true }
  },
  {
    "id": "uberpower",
    "type": "AMMO",
    "category": "chems",
    "name": { "str_sp": "uber core" },
    "description": "Seeing this is a bug.",
    "weight": "3 g",
    "volume": "3 ml",
    "bashing": 1,
    "phase": "solid",
    "material": [ "uberpower" ],
    "flags": [ "PSEUDO", "PERPETUAL" ],
    "symbol": "?",
    "color": "magenta",
    "count": 1,
    "ammo_type": "uberpower"
  },
  {
    "id": "ubergen",
    "type": "vehicle_part",
    "name": { "str": "uber generator" },
    "item": "ubergen1",
    "location": "engine_block",
    "fuel_type": "uberpower",
    "symbol": "8",
    "broken_symbol": "x",
    "color": "magenta",
    "broken_color": "magenta",
    "durability": 400,
    "power": 100,
    "epower": 37300,
    "size": 100,
    "damage_modifier": 10,
    "breaks_into": [
      { "item": "scrap", "count": [ 4, 12 ] },
      { "item": "steel_chunk", "count": [ 2, 5 ] },
      { "item": "plastic_chunk", "count": [ 2, 8 ] }
    ],
    "requirements": {
      "install": { "skills": [ [ "mechanics", 6 ] ], "time": "60 m", "using": [ [ "welding_standard", 5 ] ] },
      "removal": { "skills": [ [ "mechanics", 4 ] ], "time": "30 m", "using": [ [ "vehicle_weld_removal", 1 ] ] },
      "repair": { "skills": [ [ "mechanics", 7 ] ], "time": "60 m", "using": [ [ "welding_standard", 5 ] ] }
    },
    "flags": [ "REACTOR", "PERPETUAL" ]
  }
]```

**Comment by Kenan2000** [comment]
According to one of the feedback providers that has been testing this issue:

> So i did some further testing. And i think this might be just a visual bug. I set up a large amount of batteries on a vehicle and ran them down to about 80% and left a power draw of about 500. Then i switched on the reactor and although the batteries still stated that they were at -500 W like before,  after spending a few hours reading a book all batteries were full.

So good news is that apparently it works, but it does not provide any cues in the vehicle menu

**Comment by anothersimulacrum** [comment]
Using
```  {
    "id": "vortex_generator",
    "type": "vehicle_part",
    "name": { "str": "vortex generator" },
    "item": "vortex_generator",
    "location": "engine_block",
    "fuel_type": "vortex_power",
    "symbol": "8",
    "broken_symbol": "x",
    "color": "magenta",
    "broken_color": "magenta",
    "durability": 400,
    "//": "Here power is a multiplier on power efficiency, though ignored because of the PERPTUAL flag",
    "power": 100,
    "epower": 37300,
    "size": 100,
    "damage_modifier": 10,
    "breaks_into": [
      { "item": "spiral_stone" },
      { "item": "foot_crank", "count": [ 0, 2 ] },
      { "item": "chain", "count": [ 0, 4 ] },
      { "item": "hose", "count": [ 0, 4 ] },
      { "item": "scrap", "count": [ 4, 12 ] },
      { "item": "steel_chunk", "count": [ 2, 5 ] },
      { "item": "plastic_chunk", "count": [ 2, 8 ] }
    ],
    "requirements": {
      "install": { "skills": [ [ "mechanics", 6 ] ], "time": "60 m", "using": [ [ "welding_standard", 5 ] ] },
      "removal": { "skills": [ [ "mechanics", 4 ] ], "time": "30 m", "using": [ [ "vehicle_weld_removal", 1 ] ] },
      "repair": { "skills": [ [ "mechanics", 7 ] ], "time": "60 m", "using": [ [ "welding_standard", 5 ] ] }
    },
    "flags": [ "REACTOR", "PERPETUAL" ]
  }
```
Could not reproduce
![image](https://user-images.githubusercontent.com/42699974/101284878-3a249f00-3797-11eb-85a3-2d7afd0616da.png)

**Comment by Kenan2000** [comment]
It worked?It successfully generated the energy?Nice, I guess it works after all :-)
