### ISSUE TITLE
Dodging can be physically trained without getting weary

### ISSUE THREAD

**Issue by Xindage** [CleverRaven/Cataclysm-DDA#45850]
# Describe the bug
Counting the fact that I can get weary if I fight against an enemy, the same should happen if I just defend against one too.
So basically, training dodge is tireless at the moment.

# Steps To Reproduce
1. Have an enemy incapable of causing damage at you.
2. Let him attack you for a half hour.
3. Profit, without drawbacks.

# Expected behavior
Getting weary, because I'm doing something, the character is not just standing still.

# Versions and configuration
- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.1 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-7239-gf5bd4da [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [Dark Days Ahead [dda], Disable NPC Needs [no_npc_food], Bionic Professions [package_bionic_professions], Aftershock [aftershock], Stats Through Skills [StatsThroughSkills]]

**Comment by l29ah** [comment]
You can also read books or craft jewelry while you're at it.

**Comment by RenechCDDA** [comment]
Resolved by #64224

After this PR, dodging costs both stamina *and* sets your activity level to `EXTRA_EXERCISE`, which impact weariness.
