### ISSUE TITLE
Healing item for creature type followers

### ISSUE THREAD

**Issue by Entity-y** [CleverRaven/Cataclysm-DDA#45854]
# Is your feature request related to a problem? Please describe.
There isn't a way to heal creature type followers, they are forced to be left behind when dealing with threats or risked being slain. 

# Describe the solution you'd like
Med-kits for creature type followers that heals hit points immediately, craftable with a bandage and antiseptic. Could work like placing food when taming creatures. 
# Describe alternatives you've considered

- Activating a bandage or antiseptic prompts to either apply on self or adjacent follower. Consuming rather than activating would only use on self to eliminate an unwanted prompt.

- Instead of healing instantly it could just improve rate of healing as one would expect.

- Repair-kit made with scrap metal/electronics for mechs, alternatively welders and soldering irons could be used to repair adjacent mechs.

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
