### ISSUE TITLE
Copper Wire Dupe

### ISSUE THREAD

**Issue by Slartibax** [CleverRaven/Cataclysm-DDA#45864]
# Describe the bug
Copper wire construction dupe. 
When you construct a decorative ground cable you consume 4 copper wire items. When you deconstruct decorative ground cable object you get back a 800 copper wire items.

# Steps To Reproduce
1. Construct a decorative ground cable object.
2. Deconstruct a decorative ground cable object.

# Expected behavior
When you deconstruct a decorative ground cable, you must get back a 4 copper wire or less;  

# Screenshots
![1](https://user-images.githubusercontent.com/56679558/101276654-ff475900-37e0-11eb-8714-e7200ddcaaa3.png)
![2](https://user-images.githubusercontent.com/56679558/101276655-040c0d00-37e1-11eb-9d38-68aa015de790.png)
![3](https://user-images.githubusercontent.com/56679558/101276656-05d5d080-37e1-11eb-8a86-5f7727363844.png)

# Versions and configuration
 - OS: [Windows 7]
 - Game Version: [from the main menu, e.g. 0.E-7419-g24677646]
 - Graphics version: [Tiles]
 - Ingame language: [Russian, but changed to take a screenshots]
 - Mods loaded: [dda, no_npc_food, package_bionic_professions]

# Additional context

**Comment by Pupsi-Mupsi** [comment]
Cannot confirm on current build. Constructed and deconstructed a bunch of decorative ground cables. Deconstruction yield was 4 or less.


- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-8034-g73b5cf62a8 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    GP-Mods [gpmod],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Bionic Professions [package_bionic_professions],
    Aftershock - UndeadPeople Tileset [AftershockUDP]
]

**Comment by satheon49** [comment]
Was fixed in #45334.
