### ISSUE TITLE
Relic Recharge types 

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#45860]
# Is your feature request related to a problem? Please describe.
Add relic `recharge_info` for blood drain from PC, on hit to mobs, and in Magiclysm (this may already be possible) reloadable relic magazines with the existing bloods fuels.  
 
# Describe the solution you'd like
I'd like to be able to recharge a relic by taking some amount of blood loss.  It could let me know a rough idea of how fast I'm losing blood but I don't want to know I'm in dangerous territory until I start seeing anemia effects.  

# Describe alternatives you've considered
None.  I'm putting it here in case someone decides they like the idea before I manage to learn how to do it. 

# Additional context
I am confused about the fuel amounts per blood item after seeing the following
`"//": "Weapon materials and 1000 energy from blood suitable for the Decaying Boneclub spell",
    "components": [
      [ [ "blood", 4 ], [ "tainted_blood", 200 ], [ "dragon_blood", 20 ] ]`

I would have thought dragon blood to have a higher fuel value than normal blood.

**Comment by Maleclypse** [comment]
@Mikenyes I thought I saw a PR where you were adding some extra recharge types but now I can't find it.  Was I confused?

**Comment by Mikenyes** [comment]
I believe you saw the PR where I'm preparing for that, by expanding the debug spawning for Artifacts to easily test them.  I am working on that, but I haven't made a PR for it yet because it's not quite ready!

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
