### ISSUE TITLE
M249 Autonomous Crows II does not drop belt, only ammo

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#45861]
# Describe the bug

The M249 Autonomous Crows II turret does not drop a belt when it is disassembled, only ammo. Apparently this used not to be the case.  In any case, as discussed here https://discourse.cataclysmdda.org/t/m249-autonomous-crows-ii-generates-matter-from-nothing/25464 , there is no reason to expect an M249 inna box to fire using loose rounds of ammunition. 

Note that it does drop loose rounds of ammo linkage every time it fires.

I took apart four broken turrets, all dropped ammo none dropped belts.

# Steps To Reproduce

1. Shoot a M249 Autonomous Crows II turret from a safe-ish distance (I recommend at night with infrared goggles on and a gun with a good long range)
2. Disassemble the broken turret.
3. Note the items dropped.

# Expected behavior

Should drop one partial ammo belt, and probably one or more 500 round full ammo belts.

# Versions and configuration

- OS: Windows 8.1
- Game Version: 0.E-7353-g967d80c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    No Fungal Monsters [No_Fungi],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]

# Additional context

RL turrets use normal guns as well. You can find photos of them with ammo belts shown.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/m249-autonomous-crows-ii-generates-matter-from-nothing/25464/8
