### ISSUE TITLE
Animals don't cross bridge

### ISSUE THREAD

**Issue by Dyuden** [CleverRaven/Cataclysm-DDA#45874]
# Describe the bug

Tamed animals follow player on bridge across river, but after player enters other side of river animals don't follow and stuck on bridge. I can hear how they walk on bridge location but never show up on my side.

# Steps To Reproduce

1. Tame animal.
2. Walk with them to the bridge.
3. Somehow they follow on bridge.
4. Animals don't quit bridge location from any side after.

# Expected behavior

 Animals successfully leave bridge after me just like zombies chase player if he enters bridge. 

# Screenshots

 Attached 

# Versions and configuration

Please complete the following information; you can now go to:
    - "- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-7427-g895bbd8 [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

    - Please update your OS version with a more precise version.

 - OS: [Windows 10 ]
 - Game Version: [0.E-7427-g895bbd8 [32-bit]]
 - Graphics version: [Tiles]
 - Ingame language: [Russian and English]
 - Mods loaded: [ Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]]

# Additional context

- note #1: you can drag and drop files in this issue post!
- note #2: it is very important for us that you provide a save file in case of a crash. It really helps the developers
    to reproduce the bug and fix it. If possible, try to provide a save file that occurs in the right conditions, just
    before the crash happens. -->
![own](https://user-images.githubusercontent.com/75585223/101291112-80214780-3817-11eb-9626-9cbebc74a018.png)

**Comment by Dyuden** [comment]
Update: managed to cross bridge with animals by loading animals in vehicle.

**Comment by PatrikLundell** [comment]
The rope trick might work as well: tie the animal down with a rope. Walk into it to switch places. Continue until you reach the destination.

There have also been reports about issues with animals that follow the player up or down stairs, but then won't follow the player back (and then often stand on the stairs, blocking the player from using the stairs from then on). This issue may be related to the issue behind those reports.

**Comment by actual-nh** [comment]
Are they now crossing bridges properly?
