### ISSUE TITLE
Friendly NPCs don't make reach attacks from vehicles

### ISSUE THREAD

**Issue by ElfLeaderMike** [CleverRaven/Cataclysm-DDA#45889]
# Describe the bug
Friendly NPCs won't make reach attacks on nearby "valid" targets when attempting drive by attacks. They will attack only if they are in the adjacent tile. 

# Steps To Reproduce
Give NPC a spear.
Grab a bike and put them on a seat behind you
Drive within reach attack distance of enemy
Watch your NPC ignore free attacks.

# Expected behavior
I expect the NPCs to joust the zombies with their spears as I drive by on my bike. It's something I can do so it "should" be something they can do as well.

# Screenshots
In this image, NPCs would not attack the enemies no matter what I attempted to change regarding their engagement rules or if I attacked first.
![image](https://user-images.githubusercontent.com/22645231/101367008-a83e9400-3873-11eb-9760-c9310151394e.png)

# Versions and configuration

- OS: Windows
- OS Version: Windows 7 Professional 64-bit
- Game Version: 0.E-7938-g8736e6b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context
It's entirely possible I missed a behavior rule, but I did attempt to change almost every combat related rule to see they would attack.

**Comment by anothersimulacrum** [comment]
It will probably work if you are not on the vehicle (I know that doesn't help much).

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
