### ISSUE TITLE
Sludge trails warning while walking in vehicles.

### ISSUE THREAD

**Issue by Joar80** [CleverRaven/Cataclysm-DDA#45897]
**# Describe the bug**
While walking around on/in a vehicle you are still asked if you really want to step into the thick sludge trail. The sludge isn't removed and you get asked each time you walk onto the same tile.

**# Steps To Reproduce**

Park vehicle over sludge trail. Walk on slugded tiles.

**# Expected behavior**

Not be warned of sludge on ground while in/on a vehicle.

**# Screenshots**

![Sludge trail in vehicle](https://user-images.githubusercontent.com/74970000/101446429-a03e2d00-3923-11eb-9dfb-bc522a2f1525.png)

**# Versions and configuration**

- OS: Windows 10
    - OS Version: 10.0 2004
- Game Version: 0.E-8036-g966ab2d [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

**Comment by Jamuro-g** [comment]
tested and can confirm.
It happens when you step onto frames above a dangerous field.
