### ISSUE TITLE
Why is Aftershock so wet?

### ISSUE THREAD

**Issue by satheon49** [CleverRaven/Cataclysm-DDA#45905]
# Is your feature request related to a problem? Please describe.
Aftershock doubles the chance of lakes and rivers 
`("river_scale": 2.0` (up from 1) and `"overmap_lake_settings": { "noise_threshold_lake": 0.12 }` (down from 0.25 and lower is more in this case)

While I like the mod overall I think changing these world settings is intrusive. I also read the design document and it does not contain a reason for this change. I imagine that it is a simulation of climate change but there is no indication of it in the document. If anything I would assume the mod to manipulate city size and city spacing (both higher to simulate the mega/hive cities).

# Describe the solution you'd like
Expose river and lake settings as options in world gen and remove the overrides from Aftershock.

# Describe alternatives you've considered
An explanation for the increase in water in the design document. I suppose it could be climate change, but that does not make much sense in my opinion since the amount of water would mostly increase in coastal regions while water levels in rivers/lakes are more likely to drop because of more arid conditions.

Another more complex option would be to allow mods to set world options when they are selected during world gen, for example
1. select aftershock
2. dialog with "Allow Aftershock to change your world gen settings. Yes/No"
3. If yes Aftershocks set world gen options for the "World Options" tab. You can still tweak them afterwards.

**Comment by Mom-Bun** [comment]
This is related to #43474 and future plans for Aftershock

The intention was for this to be part of the Megacity orientated overmap for Aftershock, as these changes make it easier to play in a megacity, but with new plans its probably not going to stay for long and get removed in the future in the transition.

**Comment by satheon49** [comment]
I am on the fence whether I should close this. On one hand I now know why Aftershock changes these settings on the other hand changing river/lake density during world gen would still be useful ...

**Comment by anothersimulacrum** [comment]
Setting lake settings to low values can cause a fair bit of problems, so it'd be better that it's not configurable during worldgen to avoid those problems.
