### ISSUE TITLE
Can't alt-tab out of loading screen

### ISSUE THREAD

**Issue by Raikiri** [CleverRaven/Cataclysm-DDA#45902]
# Describe the bug

While loading a game if I alt-tab, then windows enter a limbo state where technically a different window is focused, but CDDA still renders on top of everything so I can't see that window anyway. Coincidentally, long loading times make it very tempting for the user to do something else while the game is loading (like, write a bug report?), but it's unfortunately not possible due to the game rendering on top of everything.

Additional problem is that if you do try to alt-tab of the game while it's loading and enter that limbo state, once the game is actually done loading, no keyboard input commands are processed because all user input is directed to some other window. 

# Steps To Reproduce

1. Launch the game
2. Load a character
3. While the game is on the "Loading files" menu, press alt+tab (needs some other window present on the desktop).
4. Observe that no active change happens
5. (optional) once the game is done loading, try moving the character. It'll fail because technically some other window is focused 

# Expected behavior

The game should alt-tab regardless of its current state including loading. I'm pretty sure the problem can be solved by running some window events processing occasionally during the loading screen. Just a 
`    while ( SDL_PollEvent(&event) ) {game->ProcessEven(event)}
`
somewhere in the loading screen game state should do the trick.

# Screenshots

# Versions and configuration

Happens in all game versions

# Additional context

**Comment by ZhilkinSerg** [comment]
Which are `Fullscreen` setting are you using?

**Comment by satheon49** [comment]
On my windows machine it only happens in "Borderless window" mode.

**Comment by Raikiri** [comment]
I'm using the default one (Windowed borderless)

**Comment by ZhilkinSerg** [comment]
Did you try showing your desktop with Win+D instead of using Alt-Tab?

**Comment by PatrikLundell** [comment]
It's the same thing when debugging the game in the default mode (on Windows) if you hit a breakpoint in the display loop. You can't get to the debugger because the game refuses to release the top screen layer, and you can't interact with the game because you have to release it from the debugger (not that it would help, as it would immediately hit the same breakpoint again)... The workaround of using a maximized window works, though.

**Comment by Raikiri** [comment]
I just checked and turns out I can also repro this in fullscreen mode. So both borderless and normal fullscreen are affected.

**Comment by Qrox** [comment]
The loading UI calls `SDL_PumpEvent` instead of handling the event loop after drawing, which might be related.

**Comment by GGgatherer** [comment]
> 
> 
> Did you try showing your desktop with Win+D instead of using Alt-Tab?

I tried it (borderless window mode). Sometimes it works, sometimes it doesn't, sometites it does after multiple attempts. What *does* work is opening task manager - thank God it ignores cdda's "imma gonna be on top of everything else" attitude - right-clicking game task and choosing "minimize". It actually minimizes game "window", thus stopping it from blocking the desktop.

**Comment by PatrikLundell** [comment]
Task manager is defeated by the screen hogging as well, unless task manager is configured to always be on top, at least in my experience.
