### ISSUE TITLE
Scenarios with explicit winter start actually start "whenever". (Including years before the charater was even born.)

### ISSUE THREAD

**Issue by Tamiore** [CleverRaven/Cataclysm-DDA#45901]
# Describe the bug

Tried starting with "ambush" scenario and "sheltered" scenario. 
Both end up flinging you into random season of a random year. Or just crashing outright on world generation.
And I do mean **completely** random. Like, "years before the character was even born" random.
And it's not even winter.
 
Maybe or may not be related to https://github.com/CleverRaven/Cataclysm-DDA/pull/45466

# Steps To Reproduce

1) Create a fresh world in latest experimental. 
2) Start with "ambush" scenario and "sheltered" scenario. 
3) Look at the time.

# Expected behavior

You start during the winter of the first year. 

# Screenshots

![random_year](https://user-images.githubusercontent.com/61312205/101486469-c092d980-396d-11eb-96d8-e234a94c7bbf.png)
Default bionic prepper start.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-8087-g643d8c2 [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots]
]

**Comment by satheon49** [comment]
Yes it's related, hour/day/season/year are set to random values (0-23, 0-SEASON_LENGH, 0-3 and 0-9999) if they are not set in custom_initial_date for a scenario. I am not sure that this is a sensible default. It even crashes the game if the year roll is too high (even 2^31 only allows for a bit over 68 years of turns, then it crashes between 68 and 136, then it overflows TWICE and works again and so on ...)

I will see if I can fix it. Is the randomization of time really desired? I would expect custom initial date to initialize each time component not explictly set to be default and the set properties to be an offset from the default date, i.e. `{ "season": "winter" }` means first winter after cataclysm (AC).

**Comment by l29ah** [comment]
Got a crash in Ambush. It was an assertion failure so it should have produced a nice backtrace (and indeed produced one to stdout, but ofc in a garbled form because no one cares enough to reset the terminal before printing such stuff), so i just reseted it. As of course, i get a core dump. But it is somehow useless, even though the symbols are in:
```
Core was generated by `/usr/bin/cataclysm'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f7599fc5eb1 in ?? ()
(gdb) bt
#0  0x00007f7599fc5eb1 in ?? ()
#1  0x0000000000000000 in ?? ()
```
Maybe something exploded /after/ our initial explosion?
There's nothing in debug.log as well.

**Comment by l29ah** [comment]
Got the same crash creating a non-Ambush game in the same world, so there it is for repro sake: 
[2020.12.12-45901.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5682020/2020.12.12-45901.zip)

**Comment by satheon49** [comment]
What non-Ambush scenario did you use?
