### ISSUE TITLE
Remove prompt for walking on sludge

### ISSUE THREAD

**Issue by Entity-y** [CleverRaven/Cataclysm-DDA#45915]
# Is your feature request related to a problem? Please describe.
Once the pupating zombies start wandering around, the whole city gets annoyingly filled with sludge. Walking through it brings up a prompt which can end up seriously breaking the flow of gameplay, especially if it's left to roam around.
# Describe the solution you'd like
Remove the prompt for stepping in sludge, which does nothing but slow the player down. 
# Describe alternatives you've considered
Having an option to turn off all prompts, if you run into a trap and die then you die, be more careful next time.

Make sludge only slightly slowing like walking in tall grass or moving around on furniture as to not trigger the prompt.

Make sludge dissipate much faster to not be a lasting hindrance.

Remove their regenerative ability and only allow pupating crawlers to freely move around on sludge covered tiles, otherwise as they move around they lose health until eventually killing themselves off.
# Additional context
It's an interesting concept and the element isn't necessarily unwelcomed, the prompts are what kill this creature for me.

**Comment by satheon49** [comment]
Couldn't we have a customizable whitelist for terrain features similar to the safe mode manager? So walking into fire, acid, sludge or off ledges could be a life style choice (albeit a very short one).

**Comment by Entity-y** [comment]
That'd be nice.

**Comment by emptytriangle** [comment]
I also don't like the messages but the slime is lethal and walking into it accidentally is somewhat likely to kill you in a lot of situations

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
