### ISSUE TITLE
Container length system makes early game archery unusable. 

### ISSUE THREAD

**Issue by lgordon85** [CleverRaven/Cataclysm-DDA#45919]
# Describe the bug

Using the survival bow with crude arrows is all but impossible unless you have the tailoring skill and means to create a legit
quiver. The arrow length is longer than almost every single wearable container.

Incidentally, bolts never had any lengths at all added to them in the JSON, so they all fit.

# Steps To Reproduce

Attempt to carry any amount of arrows without a quiver for use in archery. Player is unable to do anything but wield the arrows due to length.

# Expected behavior

While I understand the back and forth that already occurred about long arms in bags, it seems pretty inconceivable in "reality" that a survivor would be utterly unable to carry arrows unless they had a purpose built quiver (which also happens to be open ended)

While arrows shouldn't fit in fanny packs or ammo pouches, they should certainly fit in backpacks or some sort of makeshift sack. Putting together a cloth pouch to carry arrows would be pretty trivial with a cloth and a needle and thread.

The length system in this case completely veers away from "reality" and destroys a game mechanic (unable to carry ammunition for archery very early on before a survivor might be able to make a legitimate quiver"

I have personally changed the length of arrows to be just over half their actual length, to reflect that bag the contains at least that much of the arrow is going to hold it without issue.

**Comment by Aivean** [comment]
Could be partially alleviated by #45916

**Comment by ZhilkinSerg** [comment]
How exactly they should fit into a backpack if arrow length is bigger than backpack length? We do not support things hanging out of backpack (yet).

**Comment by lgordon85** [comment]
I understand the logistical issues if you don't support hanging out, but it seems like a pretty big hamper on early gameplay. Again, its not a huge deal as its a simple JSON change, but it does kind of make quivers absolutely required.

(And for consistency, none of the bolts have any length)

It would seem that the existence of some sort of lower level, possibly flimsy pouch for pre- leather quiver use would maybe solve  the issue. Though the above as far as lashing would indeed help a little.

I even looked around at some bowhunting forums, and it is indeed common for hunters to pack in extra arrows, as common hunting quivers only hold 3-5.

**Comment by Aivean** [comment]
If would be very helpful if you could submit some of your suggested changes in the form of PR, as you already did the research, have familiarity with JSON and have the incentive.

**Comment by lgordon85** [comment]
> If would be very helpful if you could submit some of your suggested changes in the form of PR, as you already did the research, have familiarity with JSON and have the incentive.

Perhaps I will, though I'd have to figure out how the heck git works first!

**Comment by Aivean** [comment]
> > If would be very helpful if you could submit some of your suggested changes in the form of PR, as you already did the research, have familiarity with JSON and have the incentive.
> 
> Perhaps I will, though I'd have to figure out how the heck git works first!

If you're not aware [there is a development discord](https://discord.gg/jFEc7Yp), where you can ask all sorts of questions, including git-related.

**Comment by Night-Pryanik** [comment]
#44951 should also help.

**Comment by kevingranade** [comment]
A more basic quiver recipe would probably be fine, but we aren't making any changes to make arrows fit in more generic containers, especially as they have sharp and/or fragile tips that are either going to damage the bag or the arrowheads.
