### ISSUE TITLE
Bright in the dead of night

### ISSUE THREAD

**Issue by DalenTalas** [CleverRaven/Cataclysm-DDA#45918]
# Describe the bug

Character awakens at 1-2 am, with an "It's too bright to sleep" message. Outdoor light levels show as "bright".

# Steps To Reproduce
1. Fall asleep near a window.
2. Get awakened with the above message.

Save file attached.
[Gladewater.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5662879/Gladewater.zip)

# Expected behavior

No weird lights in the sky should appear preventing the character from sleeping, unless moon phases, auroras, or extra-bright UFOs have been implemented.

# Screenshots

![image](https://user-images.githubusercontent.com/74809740/101559733-baadf000-398f-11eb-9215-5658818f4cae.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-8087-g643d8c2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Graphical Overmap [Graphical_Overmap]

**Comment by Raikiri** [comment]
As far as I know, moon phases have always been in the game. You can view them by enabling them in the UI options ("}" button). So yes, sometimes the moon can greatly extend your visibility outdoors. However, I seriously doubt that in reality it could actually make you unable to sleep.

**Comment by DalenTalas** [comment]
After loading the "glitched" save and enabling the interface options, it did indeed turn out it was the full moon. Possibly additionally affected by the Insomniac trait on the char.

Guessing this issue is officially Not A Bug. Closing as such.
