### ISSUE TITLE
Bloodbank Mosquito can push vehicles

### ISSUE THREAD

**Issue by throttlekitty** [CleverRaven/Cataclysm-DDA#45928]
Bloodbank Mosquitos can push cars while going about their business. So far they've pushed a Car across the street, and are taking a Beetle into the swamp.

# Steps To Reproduce

Spawn and observe their movement.

# Expected behavior

I get that they're giant and mutated, but they shouldn't have the mass or wing power to do this.

# Screenshots
https://i.imgur.com/psUYDhX.jpg

# Versions and configuration
Game version:  0.E-8013-g170da18

# Additional context

**Comment by DalenTalas** [comment]
Can someone clarify whether Mosquitoes hunt other insects? If that is true, then dragging off a Beetle could be considered emergent expected behavior. :)

**Comment by Venera3** [comment]
Short answer: I'm gonna get around to them, but it will come after 0.F. The mega insects have some teething problems across the board.
For the long answer see #45030 .

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
