### ISSUE TITLE
Wooden barrels act as non-rigid containers.

### ISSUE THREAD

**Issue by DalenTalas** [CleverRaven/Cataclysm-DDA#45920]
# Describe the bug

Wooden barrels add the volume of the liquid contained to the total volume of the item.

# Steps To Reproduce

1. Find a wooden barrel.
2. Fill it with some sort of a liquid.
3. Observe the volume change.

Same issue is not observed on 100L steel barrels filled with grapes (did not test on liquid-filled ones).

# Expected behavior

Being rigid, barrels should not change their volume when filled. 

# Screenshots

![image](https://user-images.githubusercontent.com/74809740/101564174-a5898f00-3998-11eb-9127-4fd105d91816.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-8087-g643d8c2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Graphical Overmap [Graphical_Overmap]

# Additional context

IRL, AFAIK, a wooden barrel's volume may change based on temperature and humidity, but the change should be negligible enough to disregard it in-game.

**Comment by DalenTalas** [comment]
The wooden barrels also act non-rigid when filled with solids.

**Comment by anothersimulacrum** [comment]
This probably applies to more barrels that just this one.

**Comment by emptytriangle** [comment]
30 gallon barrel might be affected

**Comment by DalenTalas** [comment]
30 gallon barrel is NOT affected. I can also see the "this item is rigid" message in the item description for it.

Said description is missing for the wooden barrel, so may be that this is simply the case of a missing tag.
