### ISSUE TITLE
Game crashing in crafting armor tab

### ISSUE THREAD

**Issue by DonCentral** [CleverRaven/Cataclysm-DDA#45922]
# Describe the bug

Whenever i go into the armor tab of crafting and scroll down the game crashes.

# Steps To Reproduce

1. Go to crafting tab.
2. Go to armor.
3. Scroll Down.
# Expected behavior

Game should crash, it's been happening to me for about 10 days on numerous builds.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-8095-g949ecdf [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    More Survivor Stuff [more_survivor_stuff],
    C.R.I.T Expansion Mod [crt_expansion]
]

# Additional context

 DEBUG    : invalid body part id "MOUTH"

 FUNCTION : int_id<T> generic_factory<T>::convert(const string_id<T>&, const int_id<T>&, bool) const [with T = body_part_type]
 FILE     : src/generic_factory.h
 LINE     : 464

 DEBUG    : invalid body part id "EYES"

 FUNCTION : int_id<T> generic_factory<T>::convert(const string_id<T>&, const int_id<T>&, bool) const [with T = body_part_type]
 FILE     : src/generic_factory.h
 LINE     : 464

There is also an "invalid body part id "HEAD" message but I could not replicate it easily.
[crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5663195/crash.zip)
 
[Bronaugh_copy.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5663198/Bronaugh_copy.zip)

**Comment by anothersimulacrum** [comment]
Does it occur without the `More Survivor Stuff [more_survivor_stuff],` mod?

**Comment by DonCentral** [comment]
> Does it occur without the `More Survivor Stuff [more_survivor_stuff],` mod?

Not sure, haven't tried. Should I make an effort?

**Comment by anothersimulacrum** [comment]
Yes. I heavily suspect that it is at fault.
If it is, I'm sorry, we can't do anything about it, it's a third party mod.
If it's not, we can track it down and fix it.

**Comment by DonCentral** [comment]
Alright thanks, I'll give it a shot.

**Comment by DonCentral** [comment]
Whaddaya know, works fine without it. Thanks again.

**Comment by anothersimulacrum** [comment]
Okay, my best advice is to go to wherever you got the mod in the first place, and redownload it, hopefully the author will have fixed it.
If not, and you're up to some manual editing, replacing all uppercase bodyparts with their lowercase equivalents will probably fix it.
This should be all the body parts, by the way - you may have FEET or LEGS or HANDS or ARMS or similar that need to be replaced with both the left and right variant. 
```
"head", "torso", "mouth", "eyes", "arm_l", "arm_r", "hand_r", "hand_l", "leg_l", "foot_l", "foot_r"
```

I'm going to close this issue as invalid, because it stems from a third party mod.
