### ISSUE TITLE
A lot of books lack a looks_like

### ISSUE THREAD

**Issue by int-ua** [CleverRaven/Cataclysm-DDA#45926]
# Describe the bug

At least most books in the game don't have a `looks_like` and it requires a lot of work to get a tileset looking decent. I'm preparing a new Ultica tileset release and have other things to do, unfortunately, please help with these books.

**Comment by int-ua** [comment]
#37377

**Comment by ZhilkinSerg** [comment]
Related to https://github.com/CleverRaven/Cataclysm-DDA/pull/40274 and https://github.com/CleverRaven/Cataclysm-DDA/pull/37934

**Comment by xerenogan** [comment]
I'd like to work on this one.
