### ISSUE TITLE
Repair Nanobots should switch themselves off when they are done

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#45938]
Or just cease consuming bionic power at least. Otherwise it only adds cumbersome micromanagement to avoid wasting bionic power at full health.

**Comment by Hirmuolio** [comment]
Looking at the code the repair nanobots also consume way too much power.

First they consume power as defined in JSON (4 J/turn), then they consume more hardocded power (40 J/turn).

**Comment by andrei8l** [comment]
This bionic is meant to be kept on at all times in dangerous situations, with a token standby energy consumption (lower than leukocyte breeder) that simulates active scanning for wounds. Take a look at the discussion in the PR that balanced it last https://github.com/CleverRaven/Cataclysm-DDA/pull/35021

**Comment by Hirmuolio** [comment]
4 J/s is pretty big for standby power. 
Big enough that it doesn't make sense to keep it running constantly. Forcing the player to micromanage it.

Anyways. This here makes it use 40 J/turn when healing and 0 J/turn when not healing https://github.com/Hirmuolio/Cataclysm-DDA/pull/88

**Comment by anothersimulacrum** [comment]
Consider dropping the power consumption to mJ instead?

**Comment by Hirmuolio** [comment]
If it is low enough to be insignificant then I think it is also low enough to not exist.
If it is not insignificant it is just annoying micromanagment.

Also I think the power consumption shown in UI should be power used for healing. Currently it shows the standby power there.

**Comment by anothersimulacrum** [comment]
I disagree, we have mJ precision for a reason.

**Comment by Hirmuolio** [comment]
Well according to quick search "mJ" is not used for anything anywhere . So not so sure about its reason.

But maybe the upper limit for standby power that doesn't require micromanaging would be around 100 mJ/t. That would eat about 4 kJ over 12 hours. Effectively burning 4% of mk1 power storage capacity in exchange for not doing bionic micromanagment. Still high enough that in tight spot you wouldn't be able to just keep it running when not needed.

**Comment by Voker57** [comment]
There is no point in having standby power if it just can be instantly switched on and off instead. If it had some wind-up period, sure. Otherwise, just disable it.

**Comment by anothersimulacrum** [comment]
I am not saying it should not automatically turn on and off in addition to power draw, I just think that it is better for it to have some small standby power draw.

Though, I have looked at it again now, and see that the 40J is a basically a per turn cost while damaged, instead of a per point of healing, like I thought (I didn't read that PR very thoroughly, evidently).

I think there are UX concerns with it automatically switching off.

If it switches off from being fully healed, it should turn back on when you've been damaged.
If you manually turn it off, it should not turn back on when you've been damaged.
But you should also be able to turn it off manually and tell it to turn back on automatically when damaged, after the next time you heal from full (this is complicated).

**Comment by actual-nh** [comment]
If the nanobots are to respond instantly to even slight damage, then it makes some sense to have a continuous power drain (and it probably should confer SELFAWARE while on), although probably not 4 J/s. If they were only dealing with larger-scale trauma (including bleeding), then it should not take nearly as much. (Are they still in contact with sensors in an area? Is the BP in the area appropriately close to that in other areas of the body? If the answer is "no" to either, there's a problem.) If combined with the bionic painkiller, any wound causing pain should be detectable (definitely without more expenditure of energy than the 2 kJ used by the painkiller!).

I am, in other words, suggesting that they should have a setting of "high-sensitivity" (picking up on anything wrong that they can treat, immediately) with a continuing power cost, or "low-sensitivity" (picking up on anything causing bleeding, anything more than some percentage of HP in an area (likely with a lower threshold for the head), and possibly anything causing significant pain - not sure as to the definition of this) with no continuing power cost.

**Comment by Hirmuolio** [comment]
I think that as long as player is able to deactivate and reactivate the nanobots any time at no major cost the idle power is completely pointless feature.

It makes the choice into non-choice. You can choose to keep the CBM on to darin power for nothing. But you would never choose to do that. So there is no need to offer that choice.

To make turn that into actual choice there are two options:

Change the nanobot CBM behavior into something more complex (delayed start, ramping up effect, multiple modes).

Or the activation cost would need to be large. (I think that would only punish players)

So unless someone wishes to rewrite the nanobot CBM behavior I'll just open the pull that removes idle cost.
