### ISSUE TITLE
Running indicator is not displayed.

### ISSUE THREAD

**Issue by Qsppl** [CleverRaven/Cataclysm-DDA#45935]
# Describe the bug

In the game with the UndeadPeople tileset, the running indicator is not displayed in the following languages:
![image](https://user-images.githubusercontent.com/22717464/101629008-b803d700-3a31-11eb-925f-c61be434d1b4.png)
![image](https://user-images.githubusercontent.com/22717464/101629105-dff33a80-3a31-11eb-8274-66498ef6b567.png)
![image](https://user-images.githubusercontent.com/22717464/101629155-f5686480-3a31-11eb-9d19-abc5dfcd9897.png)

# Steps To Reproduce

Select one of the above languages ​​in the game settings and go to run mode.
There will be no running indicator above the character's head.
![image](https://user-images.githubusercontent.com/22717464/101629672-c3a3cd80-3a32-11eb-89c8-ade74095d503.png)

# Expected behavior

Running indicator appears above your head
![image](https://user-images.githubusercontent.com/22717464/101640407-8430ad80-3a41-11eb-9de0-0521106255c4.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-8102-gaf6a4aa [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Alternative Map Key [alt_map_key],
    Aftershock [aftershock],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP]
]

# Additional context
Other tilesets that have indicators have a similar problem.
For instance:
Chibi_Ultica
HitButton iso
UltiCa

**Comment by XygenSS** [comment]
UDP is third-party, you should post your issue on [their repository](https://github.com/SomeDeadGuy/UndeadPeopleTileset).

**Comment by Qsppl** [comment]
> UDP is third-party, you should post your issue on [their repository](https://github.com/SomeDeadGuy/UndeadPeopleTileset).

UndeadPeople creator says the bug is in the game itself, not in the tileset

**Comment by Zireael07** [comment]
@Qsppl: Then try to replicate it with a different tileset, otherwise it'll be closed.

**Comment by Qsppl** [comment]
> @Qsppl: Then try to replicate it with a different tileset, otherwise it'll be closed.

A similar problem on the following tilesets:
Chibi_Ultica
HitButton iso
UltiCa
Other tilesets do not have such indicators

**Comment by satheon49** [comment]
Works for me on 0.E-8102-gaf6a4aa (tiles)
![Running](https://user-images.githubusercontent.com/75445240/101659719-a842bd80-3a46-11eb-8e25-741b86593d0d.PNG)

Can you provide a save?

**Comment by satheon49** [comment]
I can confirm that this problem exists. The reason is that those languages translate movement modes which in case of spanish causes "run" to become "correr" which no longer matches the concatenated tileset string (overlay_female_run would have to be overlay_female_correr).

**Comment by ZhilkinSerg** [comment]
I guess movement mode ids should be used, instead of potentially translated names.

**Comment by satheon49** [comment]
Yep, working on it.
