### ISSUE TITLE
Office tower mapgen bugged

### ISSUE THREAD

**Issue by FeelsBadMatey** [CleverRaven/Cataclysm-DDA#45943]
# Describe the bug

Befitting the name, office towers are meant to be more than 1 z-level tall. However, they aren't.

# Steps To Reproduce

1. Acquire the 'debug nightvision' (this mutation seems to reveal the map completely, but that's not the focus) and 'debug clairvoyance' mutations.
2. Open the long range teleport menu. Skim around the map until you come across an office tower.
3. Teleport there.
4. Look upwards.

# Expected behavior

Before #45738 , office towers were several z-levels tall. They aren't, anymore.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-8095-g949ecdf [64-bit]
- Graphics Version: Tiles
- Game Language: English
- Mods loaded: 
    Dark Days Ahead [dda],
    No Rail Stations [No_Rail_Stations],
    Stats Through Skills [StatsThroughSkills],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    No Fungal Monsters [No_Fungi]

# Screenshots
![officetower1](https://user-images.githubusercontent.com/49824434/101679320-33af5500-3a2d-11eb-9f4f-10e7762e1152.png)

![officetower2](https://user-images.githubusercontent.com/49824434/101679349-3ca02680-3a2d-11eb-9bec-75852431817d.png)

**Comment by Night-Pryanik** [comment]
You're mistaken this tower with various other office towers which indeed have several upper levels. This particular variant, despite being named office _tower_, doesn't have any upper levels, only one underground level with a parking.
