### ISSUE TITLE
PC goes through solid car parts when going backwards with animals.

### ISSUE THREAD

**Issue by Svankensen** [CleverRaven/Cataclysm-DDA#45944]
Going backwards in a car with unsecured cattle will cause it to push you through the vehicle.

# Steps To Reproduce

Get some sheep to stand around you inside your car. Go backwards.

# Expected behavior

I shouldn't go through the windshield

# Screenshots

![image](https://user-images.githubusercontent.com/5623801/101681168-86463c80-3a40-11eb-824c-faf33010abe2.png)
 
DEBUG    : map::unboard_vehicle: vehicle not found

 FUNCTION : void map::unboard_vehicle(const tripoint&, bool)
 FILE     : src/map.cpp
 LINE     : 1052

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-8109-g9953469 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]
]

**Comment by satheon49** [comment]
The actual reason for you are going through the windshield is your broken backseat because standing on that square counts as outside your vehicle so by driving backwards the stationary sheep gets pushed onto your square and you are not moved with the vehicle.

The debug message aside, I think that is hilarious and also not totally unrealistic.

**Comment by satheon49** [comment]
Joke aside, what should happen to the player? Should he be smashed against the windshield? What happens to the sheep?

If you collide with monsters while on a motorcycle you either displace the monster (in case of a zombie) or you and the monster gets displaced (in case of a zombie hulk). So I guess the correct result would be for the sheep to collide with the vehicle and gets displaced?

**Comment by int-ua** [comment]
Confirmed on latest experimental.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-11021.
