### ISSUE TITLE
Handle powders out of containers more realistically (like liquids)

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#45954]
# Is your feature request related to a problem? Please describe.
Powders aren't treated differently to discreet solid objects. This is actually convenient, but highly unrealistic.

You shouldn't really be able to pour out salt, sugar and potassium cyanide onto the same patch of ground then make a cup of tea with one of them. (I recommend the potassium cyanide for that post apocalyptic almondy taste)

# Describe the solution you'd like
The simplest approach would be to make them (dirty) when dropped to the ground, and not allow them to be placed in inventory or storage outside of containers (bottles, jars, tupperware, whatever). Dirtied powders would not be able to be picked up, but could be removed using mops (like liquids are). You should get a warning when you drop a powder that you may not be able to get it back.

# Describe alternatives you've considered
Alternatively, you could allow powder to be picked up from the ground but with some loss. Have a log message like "You scrape up the [name] as best you can, but some is too dirty to use."

# Additional context
This would make all those 'small bottles' and 'small cardboard boxes' have some actual use instead of them all being emptied as soon as you get a bunch of them.

**Comment by lcy03406** [comment]
Problem:
What if the surface is not dirty? If there is a quilt on the ground, pour salt onto a quilt and scrape it back, should it be totally imposible? And should it lost less than on bare ground?

**Comment by satheon49** [comment]
I am not totally against this but before anything like this gets implemented I would like to have a convenient way to see the total amount of a certain contained item on a square.

While looting I go around unloading all non-liquid items and leaving the containers just because it makes it easier to get a sense of the amount you have. For liquids this process is already a bit more involved. I usually put them in the smallest sized container that can hold their total volume (think gallon jug of energy cola or steel jerrycan of cooking oil). With this change the same would need to be done for powder if you don't want to sum up the content of all the partially filled sugar cardboxes you have.

**Comment by PaulBlay** [comment]
> What if the surface is not dirty
That's a fair point. I was already thinking that allowing one type of powder on a work surface without loss might be reasonable (workbench, table, etc.). It might be a good look for labs, etc. if you sometimes find heaps of various powder left out on the side ready to use.

I think fine tuning loss on quilts vs turf is a bit much, though. Nobody would want to do that sort of micro-management for what is essentially already a 'mistake'. Especially if your player has dumped out his sugar after the UI warns him not to.

> I would like to have a convenient way to see the total amount of a certain contained item on a square.
I think there already is one, although it maybe isn't that convenient. Just try a craft recipe that uses sugar and it will tell you how much sugar is nearby. 

And, yes, I also stuff all my Sulfuric Acid into one gallon jug (or glass bottle, etc.) Having to do that for powders as well as liquids may be a bit inconvenient, but the present state is really S.O.D. breaking.

**Comment by anothersimulacrum** [comment]
#28038

**Comment by PaulBlay** [comment]
I suppose a first step would be to have 'r'eload on containers include nearby powders as a possible selection. 'r'eload from another container would be as normal, 'r'eload from loose piles of powder would get somewhere between 75 and 90% with a message like 'You scrap together as much of the [powder] up from the [ground] as possible'.

**Comment by ThePirate42** [comment]
I've added this suggestion on FeatHub.
https://feathub.com/CleverRaven/Cataclysm-DDA/+35

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
