### ISSUE TITLE
Disassembly takes too long and requires too much.

### ISSUE THREAD

**Issue by lcy03406** [CleverRaven/Cataclysm-DDA#45956]
# Describe the bug

Disassembly takes too long and requires too much. It is useless in game AND not simulating reality.

# Steps To Reproduce

Get a crowbar or other iron things and read its description.

# Expected behavior

Breaking things into lumps should not require an anvil. @satheon49 suggests it requires level 1 metal sawing.

# Screenshots

![image](https://user-images.githubusercontent.com/3512151/101729329-f2817880-3af2-11eb-9de8-14502d60c984.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.E-8109-g9953469 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    DinoMod [DinoMod],
    Mythical Martial Arts [MMA],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Fuji's Military Profession Pack [fuji_mpp],
    Stats Through Skills [StatsThroughSkills],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Bionic Slots [cbm_slots]
]

# Additional context

**Comment by Zireael07** [comment]
Disassembly is NOT "breaking things into lumps" - that is what smashing is for. Disassembly is for getting working basic parts, like you disassembling your desk to fit new legs in.

**Comment by satheon49** [comment]
Default tool qualities and disassembly times are taken from the available crafting recipe unless there exists an "uncraft" recipe. In my opinion an uncrafting recipe for a crowbar would either use metal sawing and return 2 lumps of steel or as you suggested a hammer but should only return a single lump.

**Comment by lcy03406** [comment]
> In my opinion an uncrafting recipe for a crowbar would either use metal sawing and return 2 lumps of steel or as you suggested a hammer but should only return a single lump.

We don't need 2 disassembly recipes, metal sawing is a better idea than hammer.

For metal things, in my opinion "disassembly" is only to "treat it as scrap". “lump” is a measurement of the amount of steel, its shape is not important. In cataclysm world we don't use standard bars/sheets of steel. a lump is just some random shaped steel that we want to smelt and forge info usefull things.

**Comment by Raikiri** [comment]
There are multiple items that don't have (I'm not aware of) a way of getting their components without spending hours and hours on disassembling them. For example cotton clothing can be very painfully disassembled into cotton sheets but if you just cut it, you only get rags.

Very often 100% careful disassembling is not really needed, I just need to break down an item to get some of its components, but I don't think such option exists.

**Comment by Zireael07** [comment]
Nope, there is no such option. Disassembly is for carefully taking something apart to get components. Just smashing or cutting is faster, but doesn't get you pristine components. This is, AFAIK, completely intended.

**Comment by Aivean** [comment]
Maybe we need to introduce an intermediate "quick disassembly" (conceptually similar to quick butchering) that applies to certain items and is a tradeoff in terms of yields and time between smashing/cutting and full disassembly.

**Comment by anothersimulacrum** [comment]
This case appears to be that the crowbar recipe was made reversible for some reason, and it probably shouldn't be.
If it should have a deconstruction recipe at all, it should be a separate recipe, not a reversible one.

**Comment by lcy03406** [comment]
> This case appears to be that the crowbar recipe was made reversible for some reason, and it probably shouldn't be.
> If it should have a deconstruction recipe at all, it should be a separate recipe, not a reversible one.

Yes, the current state is so wierd. It is better to not have deconstruction recipe at all. Nobody really need to get 2 steel from a crowbar.

**Comment by GGgatherer** [comment]
Is this topic about crowbar specifically or disassembly at large? Because crowbar is not the singular mind-boggling item. 
For example, wooden boat hull:
![cataclysm-tiles_2020_11_08_12_52_13_366](https://user-images.githubusercontent.com/56833396/102705197-522c1080-42b7-11eb-876a-c83062df6cfe.png)
Consists of 5 planks and 30 nails. idk about you but it would take me far less than an hour to disassemble that.

**Comment by Zireael07** [comment]
What I find funnier is the length of **23** cm...

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
