### ISSUE TITLE
Add multi select to reload/unload action

### ISSUE THREAD

**Issue by satheon49** [CleverRaven/Cataclysm-DDA#45957]
# Is your feature request related to a problem? Please describe.
If you want to get a sense of the amount of stuff you have you usually put them into the smallest container that can contain all of it. 
For liquids this process usually involves unload->pour into a container (or reload-> select container) for every single item 
For solids/powder you still have to unload each item (at least until some version of  #45954 gets implemented)
All these actions are quite tedious.

# Describe the solution you'd like
Add multi select to reload and unload so you can select all items you want to use for reloading/unloading. In case of liquids ask for a proper container for the total amount of liquid unloaded so you can freely redistribute it. 
Batch unloading should prevent you from selecting any incompatible items (if they must be stored in a container) after selecting the first one or even better yet filter those out.

# Describe alternatives you've considered
Have a toggle for reload showing the aggregated view of compatible items, so instead of showing 6 bottles of salt water that you have to reload one after the other, show 12 salt water.

Just an UI improvement that let you see the total amount of a certain item on a square even if instances of that item are contained in different containers.

Have a new action called "fill" on containers that acts similar to the "Store which drink?" dialog of furniture containers. However there are already reload and insert that serve very similar purposes for items.

**Comment by Night-Pryanik** [comment]
We have `Unload container` action which can make batch unload.
