### ISSUE TITLE
Internal Unified Power System CBM seems to not work at all

### ISSUE THREAD

**Issue by Raikiri** [CleverRaven/Cataclysm-DDA#45965]
# Describe the bug
I tried using internal UPS with arc welder with attached UPS mod and whatever I did, it always showed as if arc welder had no charges even though I have plenty of bionic energy stored

# Steps To Reproduce

1. Get interan unified power system CBM
1.5 *Activate the CBM*
2. Get an arc welder with UPS mod
3. Try crafting anything that requires welder charges

# Expected behavior

I expect internal UPS to do at least something

# Screenshots

# Versions and configuration
Current experimental

**Comment by XygenSS** [comment]
just to make sure, you did turn it on right?

**Comment by Raikiri** [comment]
yes. also updated repro steps.

**Comment by emptytriangle** [comment]
I'm pretty sure I've been using UPS charges in the food dehydrator and a couple other tools, this might be related to the arc welder specifically or very recent. Will test tonight

**Comment by emptytriangle** [comment]
Yeah, food dehydrator with UPS cannot be used to craft in latest experimental. This must be a recent change.

**Comment by emptytriangle** [comment]
internal UPS can power a vibrator though
![image](https://user-images.githubusercontent.com/74749287/102423629-7518a500-3fd7-11eb-98ff-5994db2d3ae0.png)
![image](https://user-images.githubusercontent.com/74749287/102423647-82ce2a80-3fd7-11eb-823e-ad8c4dee6efd.png)
![image](https://user-images.githubusercontent.com/74749287/102423678-9083b000-3fd7-11eb-85c3-0991de5269f3.png)
![image](https://user-images.githubusercontent.com/74749287/102423701-9e393580-3fd7-11eb-8647-b8ebf193c745.png)

but still, even though I have my internal UPS on:
![image](https://user-images.githubusercontent.com/74749287/102423756-b4df8c80-3fd7-11eb-9e81-9518ddb55f40.png)

all the recipes have the food dehydrator disabled:
![image](https://user-images.githubusercontent.com/74749287/102423806-cb85e380-3fd7-11eb-8401-d4ffe9ebb68d.png)

if I spawn an actual UPS item, the recipes are available again:
![image](https://user-images.githubusercontent.com/74749287/102423868-f4a67400-3fd7-11eb-9d8d-1708ac45428b.png)

**Comment by Raikiri** [comment]
That's the behaviour I was suspecting as well: items that use charges directly (like, using UPS'd thermal suit or a soldering iron to fix something) seem to work fine. But crafting recipes most of the time don't detect charges. "most of the time" because I think sometimes it does work, no explanation why yet, but I suspect it might be related to other UPS's (external ones) sometimes becoming available when I get in range.

**Comment by int-ua** [comment]
Confirmed with food dehydrator on latest experimental.
