### ISSUE TITLE
Find Lab Tunnels refugee center mission is bugged and uncompletable. 

### ISSUE THREAD

**Issue by ifffrt** [CleverRaven/Cataclysm-DDA#45973]
# Describe the bug

The last Refugee Center doctor mission is bugged at start and can't find a suitable target console for the mission. Thus the mission is unfinishable.

# Steps To Reproduce

1. Do all the Refugee Center doctor mission until the last one.
2. Try to accept the last mission.
3. The game will throw up an error saying the mission will fail.

# Expected behavior

The mission should progress normally.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version [Windows 8.1 Pro build 9600]
- Game Version: 0.E-8109-g9953469 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key],
    Graphical Overmap [Graphical_Overmap],
    sees-player icon, retrodays [sees_player_retro],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    Mythical Martial Arts [MMA],
    More Survivor Stuff [more_survivor_stuff],
    Fuji's Military Profession Pack [fuji_mpp],
    Mutation Changes [Mutation_Changes],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP]
]

# Additional context

Error Message:

 DEBUG    : Could not find a computer in the lab train depot, mission will fail.

 FUNCTION : static void mission_start::reveal_lab_train_depot(mission*)
 FILE     : src/mission_start.cpp
 LINE     : 738

[Sabattis.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5676294/Sabattis.zip)

**Comment by hexagonrecursion** [comment]
I can tell you why it fails. mission_start::reveal_lab_train_depot() selects the closest overmap tile of type "lab_train_depot" and searches it for a console. If the console is missing (eg it was destroyed), the function should try searching in a different overmap tile, but this is not currently implemented.

https://github.com/CleverRaven/Cataclysm-DDA/blob/b285a130801aee625fa888df27382e843bf12f84/src/mission_start.cpp#L718-L740
