### ISSUE TITLE
Mi-go camp walls cannot be mined by pickaxe or jackhammer.

### ISSUE THREAD

**Issue by ifffrt** [CleverRaven/Cataclysm-DDA#45974]
# Describe the bug

The game does not let you mine mi-go resin walls for resin chunks.

# Steps To Reproduce

1. Try to mine mi-go resin walls with a pickaxe.
2. The game will tell you "You can't mine there".

# Expected behavior

You should be able to mine mi-go resin walls just like on previous experimental versions.

# Screenshots

![New Bitmap Image (3)](https://user-images.githubusercontent.com/74819253/101844735-b1837580-3b7f-11eb-8712-96874b6ab831.jpg)

# Versions and configuration

    OS: Windows
        OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version [Windows 8.1 Pro build 9600]
    Game Version: 0.E-8109-g9953469 [64-bit]
    Graphics Version: Tiles
    Game Language: English [en]
    Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key],
    Graphical Overmap [Graphical_Overmap],
    sees-player icon, retrodays [sees_player_retro],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    Mythical Martial Arts [MMA],
    More Survivor Stuff [more_survivor_stuff],
    Fuji's Military Profession Pack [fuji_mpp],
    Mutation Changes [Mutation_Changes],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP]
    ]

# Additional context

**Comment by satheon49** [comment]
According to the git history it has never been mineable since its inception in August 2019. Only the resin cage is.

**Comment by Qrox** [comment]
The message could be changed to something like "the material is so hard that you hardly make a dent" so it's clear that the tile is intentionally not mineable.

**Comment by actual-nh** [comment]
> The message could be changed to something like "the material is so hard that you hardly make a dent" so it's clear that the tile is intentionally not mineable.

Should this be done in all cases of trying to mine something not marked as "MINEABLE" (probably moved to the last check in `iuse::pickaxe`), or only some?

**Comment by Qrox** [comment]
From a quick look at the json code, floor tiles also don't have the "MINEABLE" flag, so a separate flag is needed.
