### ISSUE TITLE
Tile selection look indicator invisible when on a vehicle

### ISSUE THREAD

**Issue by Szara-ManOfHonor** [CleverRaven/Cataclysm-DDA#45979]
# Describe the bug
The look indicator icon, on Ultica the four white corners which show where you have selected when looking with ; or x, is invisible when the player character is on a vehicle. Driving not necessary, just be on a vehicle tile.
Checked with Ultica and MSXotto+ to check for it being a tileset issue.

# Steps To Reproduce

1. Get on a vehicle, LOOK around.
2. No indicator, be sad.

# Expected behavior
Have the look indicator.

# Screenshots

Have the indicator when not on a vehicle-
https://gyazo.com/9c0064f0d71a4fb6e368b2c113fee32a.png

Don't have the indicator when standing on a vehicle-
https://i.gyazo.com/8ba4f85656c311495c5ab380467dc7e8.png

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-8095-g949ecdf [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context

**Comment by satheon49** [comment]
Works fine for me. Have you tried upgrading? I believe #45951 should have fixed it.

**Comment by Szara-ManOfHonor** [comment]
Yeah, just updated again and that update yesterday fixed it.
