### ISSUE TITLE
Fix separation of liquid and solid food in "Consume item" list.

### ISSUE THREAD

**Issue by Salty-Panda** [CleverRaven/Cataclysm-DDA#45989]
# Describe the bug
Currently game displays liquid and solid food separately
![image](https://user-images.githubusercontent.com/26396019/101929242-e1aa3300-3bd6-11eb-9f87-7aa2c3784bb7.png)

# Steps To Reproduce

Put both liquid and solid items on the same tile, hit `E`.

# Expected behavior

Food listed together, since it's the same category.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-8109-g9953469 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Mythical Martial Arts [MMA],
    C.R.I.T Expansion Mod [crt_expansion],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Bionic Professions [package_bionic_professions],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP]
]

**Comment by Pupsi-Mupsi** [comment]
I'm confused. Food and drinks are actually grouped together. Drugs and Chemicals are shown in separate categories. 
But maybe it's a mere misunderstanding.


![grafik](https://user-images.githubusercontent.com/44737997/101946638-7caf0700-3bef-11eb-9af3-bffd4d0f0839.png)

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-8109-g9953469cf3 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    GP-Mods [gpmod],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Bionic Professions [package_bionic_professions],
    Aftershock - UndeadPeople Tileset [AftershockUDP]
]

**Comment by satheon49** [comment]
I think I understand the problem: Category view is only used for stuff that is either in your inventory or in a container. Loose items are displayed by location. Contained items being shown in the category is probably a side effect of #40143 which added contained items to the inventory list.

The question is which behavior should we aim for? Removing contained items from food/drink/drugs categories and moving them back to their respective locations or showing every item in food/drink/drugs?
