### ISSUE TITLE
Invisible pine trees

### ISSUE THREAD

**Issue by DalenTalas** [CleverRaven/Cataclysm-DDA#45996]
# Describe the bug

Pine trees are not rendered and only become visible after interacting with them.

EDIT: See temporary fix below.

# Steps To Reproduce

1. Load the attached save, character Rona.
2. (e)xamine the square directly to Rona's north.
3. Pick a pine tree.
4. Watch a pine tree mysteriously fade into existence, using a "full-grown tree" sprite.

# Expected behavior

Pine trees, being relatively low-tech plants, should not be using optical camouflage.

# Screenshots

![invisible pine](https://user-images.githubusercontent.com/74809740/101958894-3f884c00-3bd2-11eb-9e38-c877ff0ab2b1.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-8133-g5beedea [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap]
]

# Additional context
Save file: [Open Road.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5681783/Open.Road.zip)
New release of Ultica with the fix: https://github.com/I-am-Erk/CDDA-Tilesets/releases

**Comment by int-ua** [comment]
Confirming, thank you for reporting
https://github.com/I-am-Erk/CDDA-Tilesets/issues/340

**Comment by DalenTalas** [comment]
Since you mentioned offset sprites in the linked thread, I went back to see if any other trees have a similar offset. Nothing so far, other than what's listed below, but will keep an eye out.

Dead pine trees use sprites for live ones.
Chestnut trees seem to be using the same sprites as the dead pines (not sure if that's intended).

**Comment by int-ua** [comment]
> Dead pine trees use sprites for live ones.
> Chestnut trees seem to be using the same sprites as the dead pines (not sure if that's intended).

Yes, two positions to the right:
![fillergiant_](https://user-images.githubusercontent.com/1585431/101967583-bef23b80-3c23-11eb-8e01-7e3e58e1d6d4.png)

But I don't understand how the pine in invisible. Unless I debug-spawned a wrong pine? I don't think so.

**Comment by DalenTalas** [comment]
So, to clarify: a "picked" pine uses the 6th sprite from the left in the image above. So do "dead" ones.

**Comment by int-ua** [comment]
Looks like it has to do with empty tilesheets being present before the fillergiant. Cause: #44932
I did not notice that `compose.py` added an empty sprite at the start of every sheet. Working on a fix.

**Comment by int-ua** [comment]
Please update your Ultica: https://github.com/I-am-Erk/CDDA-Tilesets/releases

**Comment by DalenTalas** [comment]
Updated. Issue resolved, and closing. Thank you for the prompt fix. Screenshot below:

![works](https://user-images.githubusercontent.com/74809740/101969597-2774f480-3bf3-11eb-825f-875abac4f2f7.png)

**Comment by int-ua** [comment]
Technically, it's not yet fixed, please reopen until the new Ultica release is pushed into CDDA master.

**Comment by DalenTalas** [comment]
Thank you for the suggestions. New to Git, not too familiar with the process.

**Comment by int-ua** [comment]
You can close this now
