### ISSUE TITLE
More convenient nest containers and cans, jars, etc.

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#45992]
# Is your feature request related to a problem? Please describe.
As I played last experimental I found nested containers awkward because there are containers where are many items and you sometimes have a lot of these containers and it's cluttery and I thought why not to add something like this. I think it'll be better if there will be ability to collapse and expand container's item list or as for cans and other containers for liquids make them "not container" because they can't store more than one liquid at time.

How does it looks now?
As example an aluminium can of soda:

```
aluminium can (sealed) > cream soda (cold)
cream soda cold
```
But there's also containers what stores bunch of items and there is also a container showed in inventory what does not make a sense and unconvenient as we have them.

# Describe the solution you'd like
How may it look like?

expanded:

```
[-] container
     - content
     - content
     - content
```
collapsed:

`[+] container`

# Describe alternatives you've considered
None.

# Additional context
I think it will be more convenient so why not?

**Comment by Aivean** [comment]
I'm not sure what you're asking for. 

There are two inventory layouts, one is grouped by category and another one is nested:

![image](https://user-images.githubusercontent.com/2865203/101992739-3fd42600-3c6a-11eb-9055-d275f1dcd3e5.png)

![image](https://user-images.githubusercontent.com/2865203/101992742-4367ad00-3c6a-11eb-83cd-c67b7ac93b98.png)

You can switch between them by pressing `;` hotkey.

The "grouped" layout requires items to fit into a single line, so it's not possible to add tree structure there. 

The "tree" layout currently doesn't have an option of collapsing, are you suggesting to add one? If yes, can you be more specific what problem would it solve?
