### ISSUE TITLE
NPCs with 'stay close, no matter what' rule do not fight back when guarding position

### ISSUE THREAD

**Issue by olanti-p** [CleverRaven/Cataclysm-DDA#46009]
# Describe the bug
NPCs with 'stay close, no matter what' rule do not fight back when guarding position

# Steps To Reproduce
1. Get yourself an NPC with melee weapon (or no weapon)
2. Do one of the following:
    * Tell them to 'stay close, no matter what'
    * Issue a temporary order for the whole party to 'stay close, no matter what'
3. Tell the NPC to guard a position
4. Spawn a zombie. Zombie approaches the NPC, and NPC fights back
5. Move a few tiles away. NPC believes they need to catch up, and ignores any further attacks from the zombie.

# Expected behavior
NPC fights back.

# Versions and configuration
Build 11249 (aka 6a9c6ee0f00e30347fc5c8b6a5d53bb4e304d991)

# Additional context
Potential culprit: https://github.com/CleverRaven/Cataclysm-DDA/blob/6a9c6ee0f00e30347fc5c8b6a5d53bb4e304d991/src/npcmove.cpp#L390-L391

**Comment by actual-nh** [comment]
"Stay close" and "guard this position" would appear to be somewhat contradictory - or is there something I'm missing?

**Comment by olanti-p** [comment]
They are contradictory - and yet, from what I can see, danger assessment code uses 'stay close' regardless of whether NPC is guarding or following. In fact, adding `is_walking_with() &&` right after `=` fixes the bug for case 2a.
