### ISSUE TITLE
Laser weapon fouling. 

### ISSUE THREAD

**Issue by Joar80** [CleverRaven/Cataclysm-DDA#46004]
**# Describe the bug**

The shoddy laser rifle and V29 laser pistol both have fouling and need to be cleaned. Needed to clean them both several times now.

**# Steps To Reproduce**
Fire guns until fouling shows.

**# Expected behavior**

No gunpowder, so no fouling. Maybe some other type of degredation.

**# Screenshots**
![laser fouling](https://user-images.githubusercontent.com/74970000/101979681-5923a500-3c5f-11eb-8e7f-c5050a2c3d92.jpg)

**# Versions and configuration**
- OS: Windows 10
    - OS Version: 10.0 2004
- Game Version: 0.E-8131-g1599f6c [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

**# Additional context**
Screenshot shows V29 in a turret, but it happens when handfiring as well.

**Comment by Joar80** [comment]
Realized the previous issue on this was stale, and not actually fixed. Should I report this there instead?
[https://github.com/CleverRaven/Cataclysm-DDA/issues/36731](https://github.com/CleverRaven/Cataclysm-DDA/issues/36731)

**Comment by Hirmuolio** [comment]
They seem to be different bugs (kind of).

Spawned laser pistol fouling seems to be due to "and" check instead of "or".
Shot laser pistol fouling seems to be due to wrong flag on it. Not-fouling-gun flag and not-fouling-ammo flag should probably be the same to avoid them being mixed up.
