### ISSUE TITLE
Monster loading prior to spell loading can cause "invalid spell id errors"

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#46011]
# Describe the bug

Valid spell and monster with fake spell jsons can cause error `"11:00:21.034 ERROR : src/generic_factory.h:433 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = spell_type]] invalid spell id "cone_cold"` due to folder structure.

# Steps To Reproduce

Place spell file `data/mods/Aftershock/spells/spells.json` and monster file `data/mods/Aftershock/mobs/mutant.json`.  Error ensues.  Move monster file one folder down or spell file one folder up and it will be fixed.  

# Expected behavior

Spells to ignore folder depth.  Or documentation to mention the need for spells to load before monsters that use spells and how to accomplish it. 

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-7938-g8736e6b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock]
]

# Additional context

Notes from anothersimulacrum 

"It's a load order issue. Either spells.json needs to be moved up one level, the file with monsters using spells needs to be moved down one level, or the monster spellcasting actor needs some refactoring to delay the spell loading."

"Yes, the two solutions I mention are moving data/mods/Aftershock/spells/spells.json to data/mods/Aftershock/spells.json or moving data/mods/Aftershock/mobs/mutant.json to data/mods/Aftershock/mobs/delay/mutant.json"

**Comment by anothersimulacrum** [comment]
The problem occurs when this fake spell has get_spell called.
https://github.com/CleverRaven/Cataclysm-DDA/blob/6a9c6ee0f00e30347fc5c8b6a5d53bb4e304d991/src/mattack_actors.cpp#L167-L174
The fake spell should be stored in the actor, then wait until a finalization step (once all spells are loaded), to call this.
