### ISSUE TITLE
Allow mutations to check for CBMs (if they don't already do so)

### ISSUE THREAD

**Issue by meelock** [CleverRaven/Cataclysm-DDA#46013]
# Is your feature request related to a problem? Please describe.
I'm not entirely certain how difficult it would be to allow mutations to check for CBMs on addition, as I was told it was currently impossible, but CBMs can already do this the other way. Also, I don't know how needed this is, but I thought it would be interesting to add if a moxpore mutation line gets added, so that the mutations can adapt to the CBMs currently installed (as moxpores are machines, I figured it would be cool if they interfaced with other machines).

# Describe the solution you'd like
Allow mutations to check for CBMs on addition, similar to how CBMs can check for mutations on installation.

# Describe alternatives you've considered
Not doing this, probably because it would be too hard.

# Additional context
NA

**Comment by KorGgenT** [comment]
check for what exactly? this is pretty vague

**Comment by actual-nh** [comment]
Perhaps move to Discussions?

**Comment by Mom-Bun** [comment]
I don't exactly fully understand this issue, and it might fit better in discussions imo (like actual-nh said) but this issues mentions MoxPhores mutation line, which is something I thought about including in the future.

While the idea of CBMs and mutations playing together is potentially interesting, as far as I know, in Aftershock, CBMs will be human tech, and the MoxPhore mutation line will be an alien virus changing you, and so there would be no real... "interaction" there as far as I know? 

Aftershock lore is still very early and work in progress so I don't want to say for 100% certainty, but I'd like to state that stuff like the "MoxPhore mutation line" is very very far in the future.

**Comment by anothersimulacrum** [comment]
I'm doing this as part of #47822
