### ISSUE TITLE
Handling .22 reloaded FMJ caliber bullets slow you down and exhaust you 

### ISSUE THREAD

**Issue by Torres84f** [CleverRaven/Cataclysm-DDA#46015]
# Describe the bug

Either disassembling .22 bullets or moving the casings is taking insane amounts of time, I've tried having many kinetic bullet pullers so my NPC's can use them, I'm being helped by 3 NPC's with decent fabrication skills and even after having a full day's rest and having some coffee the whole situation snowballs and tires you out in fewer than 2 hours, even moving the casings with the advanced inventory manager or the normal inventory dropping the casings makes the game almost freeze.

# Steps To Reproduce

1. Take a full day's rest
2. Get some NPC's to help
3. Try and disassemble any quantity of .22 reloaded higher than 100 units and you'll get incredibly exhausted

# Expected behavior

# Screenshots

# Versions and configuration

00:23:44.241 :  GAME REPORT:
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-8133-g5beedea [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Mining Mod [Mining_Mod],
    Dorf Life [Dorf_Life],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    DinoMod - UndeadPeople Tileset [DinoModUDP],
    Dorf Life - UndeadPeople Tileset [Dorf_LifeUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm]

# Additional context

**Comment by Aivean** [comment]
Savefile and steps to reproduce would help immensely.

**Comment by Torres84f** [comment]
> Savefile and steps to reproduce would help immensely.

can edit with steps but my save is 1.5Gb :/

**Comment by Aivean** [comment]
> > Savefile and steps to reproduce would help immensely.
> 
> can edit with steps but my save is 1.5Gb :/

Thank you. I'll try to reproduce in the test world.

**Comment by Aivean** [comment]
Still can't reproduce:
![disasm](https://user-images.githubusercontent.com/2865203/102002837-4dfb6400-3cb5-11eb-91d3-40a6aadc7be8.gif)

Can you please create a fresh world and try to reproduce the issue there?

**Comment by Torres84f** [comment]
> 
> 
> Still can't reproduce:
> ![disasm](https://user-images.githubusercontent.com/2865203/102002837-4dfb6400-3cb5-11eb-91d3-40a6aadc7be8.gif)
> 
> Can you please create a fresh world and try to reproduce the issue there?

Could you please try with the .22 FMJ reloaded? I'll try a new world and debug I can't understand this...

Thanks for your help!

**Comment by Torres84f** [comment]
> 
> 
> Still can't reproduce:
> ![disasm](https://user-images.githubusercontent.com/2865203/102002837-4dfb6400-3cb5-11eb-91d3-40a6aadc7be8.gif)
> 
> Can you please create a fresh world and try to reproduce the issue there?

I'm going to try now in a new world.

Here as you can see I got a full night's sleep, fully fed, decent focus, NPC's around and .22 FMJ reloaded aaaaand...
![resized](https://user-images.githubusercontent.com/15707408/102005618-1bcc1f80-3d12-11eb-8323-8bfec22e1cb7.gif)

**Comment by actual-nh** [comment]
Savefile from test world (smaller I trust)?

**Comment by Torres84f** [comment]
> 
> 
> Savefile from test world (smaller I trust)?


[Canyon City.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5685414/Canyon.City.zip)

Made a new one after the gif but the problem is still the same, the tiring you out part was because it takes long hours and the character doesn't seem to be resting in between which in turn seems to snowball

Thanks!

**Comment by int-ua** [comment]
Does it happen in a world without all these mods? If not I suggest using bisect search to speed up determining which mod causes this.

**Comment by hexagonrecursion** [comment]
I loaded the save with only mainline mods, but could not reproduce this bug

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 8051d7d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    No name () [],
    No name () [],
    No name () [],
    No name () [],
    No name () [],
    No name () [],
    No name () [],
    No name () []
]

**Comment by int-ua** [comment]
It's an old issue and may have been resolved elsewhere, please comment if you can reproduce it. I'll close this for now.
