### ISSUE TITLE
Inconsistent item rejection behaviour in loot zones

### ISSUE THREAD

**Issue by WeaverThree** [CleverRaven/Cataclysm-DDA#46019]
# Describe the bug

My expectation: Sorting out loot will remove any item from a tile if it does not match any zone in that tile if there is a matching or unsorted tile available to put it in. 

Actual behavior: Sorting out loot only removes non-matching items if there is a non-custom loot zone to move the items to.

This feels like a regression from older behavior, where sorting loot would at least move non-matching items to Unsorted tiles. Perhaps I am misremembering? In any case, these are how I epect things to work vs what actually happens:

# New steps to 

# Steps To Reproduce

1. Make 2 custom zones: A=`c:food,-(rotten)` and B=`(rotten)`, inside an unsorted zone.
2. Put a piece of rotten food on A.
3. Auto sort. Nothing happens.
4. Drag the rotten food off of A.
5. Auto sort. Rotten food moves to B.
---
1. Make 1 custom zone: A=`c:food,-(rotten)`, inside an unsorted zone.
2. Put a piece of rotten food on A.
3. Auto sort. Nothing Happens.
---
1. Make 1 zone: A=`Loot: Drugs` , inside an unsorted zone.
2. Put a food item on A
3. Auto sort. Nothing Happens
---
1. Make 2 zones: A=`Loot: Drugs`, B=`Loot:Food` , inside an unsorted zone.
2. Put a food item on A
3. Auto sort. Item moves to B as expected. This is the one working case.

# Expected behavior

1. Make 2 custom zones: A=`c:food,-(rotten)` and B=`(rotten)`, inside an unsorted zone.
2. Put a piece of rotten food on A.
3. Auto sort. Rotten food moves from A to B
---
1. Make 1 loot zone: A=`c:food,-(rotten)`, inside an unsorted zone.
2. Put a piece of rotten food on A
3. Auto sort. Rotten food moves from A to a non-full unsorted zone square.
---
1. Make 1 zone: A=`Loot: Drugs` , inside an unsorted zone.
2. Put a food item on A
3. Auto sort. Food moves from A to a non-full unsorted zone square.
---
Expected = Actual for 4th case

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-8138-g3b97eed [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    MSX Black Military Cars [UDP_BlackMilitaryCars],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP],
    Disable NPC Needs [no_npc_food],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    No Fungal Monsters [No_Fungi],
    Better Lupine (wvr) [wvr_lupine] (Just changes some mutation flags)
]

**Comment by satheon49** [comment]
> Sorting out loot will remove any item from a tile if it does not match any zone in that tile if there is a matching or unsorted tile available to put it in.

Your expectation is only partially correct: If there is a zone matching the item it should get moved there but nothing gets moved to an unsorted zone (unless there is another targeted zone on top). Unsorted zones are only potential sources for sorting loot.
However the first case in "Steps to reproduce" still sounds like a bug.
