### ISSUE TITLE
Peeking through curtain not working - Build #11250 

### ISSUE THREAD

**Issue by Egifer** [CleverRaven/Cataclysm-DDA#46022]
# Peeking through curtain not working as of Build #11250 

Using peek through curtain doesn't show any mobs behind the window

# Steps To Reproduce

1. Make character.
2. Use peek through curtain option at window with closed curtains with mob behind window.
3. Mob will not show either visualy or in the mob list.

# Expected behavior

Mob should show either visualy or in the mob list.

# Screenshots

![obrazek](https://user-images.githubusercontent.com/6621108/102006167-4ec8e000-3d1f-11eb-8859-26e9ab1e8ccb.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-8138-g3b97eed [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

**Comment by kevingranade** [comment]
Confirmed here too.
Some debugging points to has_potential_los() as the issue, it seems that it is not being invalidated while peeking, and this prevents seen(monster) from working.

**Comment by kevingranade** [comment]
Confirmed by disabling has_potential_los() check and re-testing, monster becomes visible again, looking into forcing invalidation.

**Comment by kevingranade** [comment]
Candidate fix incoming, if we bypass the has_potential_los() check when the viewer is on an opaque tile, peeking can see monsters again.  I mostly need to figure out where to put the check.
