### ISSUE TITLE
Modable clothes and armor

### ISSUE THREAD

**Issue by DalenTalas** [CleverRaven/Cataclysm-DDA#46034]
# Is your feature request related to a problem? Please describe.
Currently, the only options for tinkering with clothes/armor are reinforcing them, or crafting new items through recipes (e.g., nomad outfit).

# Describe the solution you'd like
Implement a system similar to modding firearms. Clothing items will have a number of modification slots (e.g., "large pocket", "small pocket", "chest", "back", "shoulder", "s/m/l/xl lining", "visor", etc.). Mod items could then be craftable through recipes and attached to the clothing or armor. The item reinforcement option could then be shifted into crafting items for the "lining" slot.

This will allow for creation of such custom items as:
- An army helmet with a flashlight or a set of night-vision gear attached.
- A HUD attachable to a helmet.
- Electric lining for to winter clothing.
- Strike plates mounted onto ballistic vests.
- A shoulder-mounted flashlight.
- Stitch-on pockets.

# Describe alternatives you've considered
Admittedly, the layers/pockets system already does a decent job at this and a lot of my ideas could be implemented by introducing additional crafting recipes. See also #44866 for an alternate concept.

**Comment by Maddremor** [comment]
It would be pretty hard to make a system where all those modifications make sense, and where the derived item statistics are reasonable. The current reinforcement/padding options are questionable as they are.

**Comment by Svankensen** [comment]
I agree with Maddremor. There's no need to attach the night vision or flashlight, when we have items that already do that. Hell, flashlights work from your pockets, you can make assumptions. Some of yours could be implemented in the current system tho. thermal lining sounds like something you should be able to do just like adding wool. Honestly, I'd much rather have a more modular system that allows you to REMOVE stuff. So many times I find some armor that is great, but covers the arms or hands when I don't want it to, etc.

**Comment by kevingranade** [comment]
See https://github.com/CleverRaven/Cataclysm-DDA/issues/19936#issuecomment-272247977
