### ISSUE TITLE
"Rest" not displaying under Needs

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#46038]
# Describe the bug

The "Rest" item underneath Needs does not appear to be updating properly.

# Steps To Reproduce

Do things until the game notes that you're tiring out.

# Expected behavior

I expected the game to note that I am tired in the Rest line.

# Screenshots
![TiringOut](https://user-images.githubusercontent.com/13796683/102027626-5ca85080-3d73-11eb-8e2b-ded2bba6439b.png)

# Versions and configuration

- OS: Windows 10 20H2
- Game Version: 0.E-8128-gc363e33 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded:
-- Dark Days Ahead [dda],
-- C.R.I.T Expansion Mod [crt_expansion],
-- No Fungal Monsters [No_Fungi],
-- Disable NPC Needs [no_npc_food],
-- Alternative Map Key [alt_map_key],
-- SpeedyDex [speedydex],
-- Stats Through Kills [stats_through_kills],
-- Stats Through Skills [StatsThroughSkills]

**Comment by satheon49** [comment]
Those messages do not refer to "rest". They refer to "weariness".

Rest means you have a desire to sleep.
Weariness technically refers to the amount of calories you burned in a short period of time. for example you are exhausted after a marathon but not necessarily sleepy.

**Comment by Fris0uman** [comment]
It's not the first time the confusion comes up, so maybe there's something to be done here. Add a weariness indicator below rest and/or rename rest to sleepyness or something similar.

**Comment by satheon49** [comment]
True, though I think #44428 already aims at improving this.

**Comment by anothersimulacrum** [comment]
Confusion about weariness messages, should be resolved since.
