### ISSUE TITLE
Add zoom keys to list-all-items-around-the-player mode

### ISSUE THREAD

**Issue by WeaverThree** [CleverRaven/Cataclysm-DDA#46032]
# Describe the solution you'd like

While examining nearby items and monsters, I often find myself wanting to zoom in for a better look or zoom out for a better understanding of distance, so, I would like to be able to bind keys to zoom in and zoom out inside the "List all items around the player" interface mode. It should be possible to make z/Z the default, as well -- I don't think there's anything that would conflict with that going on, and it would bring parity with the look-around and aim-weapon modes.

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
