### ISSUE TITLE
UI Addition: Disassemble-ability flag in look-at info

### ISSUE THREAD

**Issue by WeaverThree** [CleverRaven/Cataclysm-DDA#46043]
# Is your feature request related to a problem? Please describe.
It's somewhat annoying to not have this info accessable.

# Describe the solution you'd like

I'd really like it to say "Disassemblable" or "Easily Disassemblable" in the look-at info where it already says things like "Smashable. Flat. Mountable." already, so I don't have to have tools and open the construction.

# Describe alternatives you've considered
The text is rather long. Maybe "Dis'able" or similar to not take up too much space.

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.

**Comment by Zireael07** [comment]
This is one of the QoL things that are worth implementing and shouldn't be closed.

**Comment by Night-Pryanik** [comment]
Most of suggestions are worth implementing, this doesn't mean that they should clutter the issue list.

**Comment by Zireael07** [comment]
Hm, maybe add a 'salvageable' label (or something similar) to those issues that could be picked up again? That's a solution I saw on some other repo - and it solves the problem of people not knowing which issues are closed because fixed, and which are NOT fixed.
