### ISSUE TITLE
Cooperative gaming

### ISSUE THREAD

**Issue by PavelPoltavets** [CleverRaven/Cataclysm-DDA#46065]
Sorry for doubling, this is for FeatHub page...
# Is your feature request related to a problem? Please describe.
No cooperative...

# Describe the solution you'd like
Player1 - P1, Player2 - P2, global world ticks - GWT
For start lets take GWT = 0, and P1 action cost = 100 ticks per action , P2 action cost = 47 ticks per action, Players tactic - always make actions.
GWT: 0
GWT: 47 - P2 made an action
GWT: 94 - P2 made an action
GWT: 100 - P1 made an action
GWT: 141 - P2 made an action
lets take GWT = 0, and P1 action cost = 100 ticks per action , P2 action cost = 47 ticks per action, Players tactic - always make actions, but after P2  first action, P1 want to change action(still cost 100).
GWT: 0
GWT: 47 - P2 made an action
GWT: 94 - P2 made an action
GWT: 141 - P2 made an action
GWT: 147 - P1 made an action
lets take GWT = 0, and P1 action cost = 100 ticks per action , P2 action cost = 50 ticks per action, Players tactic - always make actions.
GWT: 0
GWT: 50 - P2 made an action
GWT: 100 - P1 and P2 made an action

# Additional context
Cooperative not Multiplayer because a lot of players have to wait each other...
And i am proposing to add "wait another player action" to "wait" menu.
I chose this idea because players with it can do actions in the same world (game) time and it don't break any game logic.

**Comment by ZhilkinSerg** [comment]
I am not sure how you want to implement all this in an engine that is not designed to support multiplayer.

**Comment by Xaleth** [comment]
This will require an incredibly major rewrite to be something like TomeNET, and it is a radical direction away from this project's scope. If we did do this, it will affect a crap ton of aspects to the game and I don't think anyone would be up to it. If you really want it implemented, a fork of this project is always an option--it's open source after all.

**Comment by xerenogan** [comment]
From a gameplay perspective,
when I try to imagine actually playing it multiplayer/cooperative, it doesn't even seem that much fun. Accidentally stacking actions you didn't mean to make, or just sitting there waiting while your erstwhile companion mulls over their inventory or something. Not fun. Also, like ZhilkinSerg said, this is not built at all to support multiplayer.
If you mean local multiplayer, then that's not any better. I've actually done a kind of local multiplayer with myself in the driver seat and my co-player telling me what to do. It boiled down to me having a rather talkative backseat driver that went nowhere.
Implementing a mechanic where I _have_ to slide the keyboard over to him when I could have done that anyway seems pointless.

**Comment by kevingranade** [comment]
This has come up [many times](https://discourse.cataclysmdda.org/search?q=multiplayer), and it simply can not be added to DDA.
- The game loop of DDA includes a large number of activities that pass a large amount of time with no or minimal player input.
  - You propose requiring coop mode, but that doesn't change the fact that there are huge number of scenarios where a player gets stuck with nothing to do for an extended amount of time.
  - This isn't just the obvious things like crafting and sleeping, but simply moving around tactically and examining the inventory and examining surroundings and menu interaction are not streamlined for short turn times.  This has implications for every part of the game, and I am not interested in making those adjustments.
- The synchronization issues go much deeper than you seem to think they do, and resolving them would require overhauling most of the core game code.
- I'm not interested in dealing with the security issues inherent in multiplayer network support.

**Comment by ThomasLinkin** [comment]
ngl, the security issues are what most multiplayer games nowadays facing. so yeah, best not to have a multi mode
