### ISSUE TITLE
Crash while trying to pick up items in the vehicle

### ISSUE THREAD

**Issue by ektoplazm** [CleverRaven/Cataclysm-DDA#46063]
# Describe the bug

Game crashes while trying to **g**et or **e**xamine any tile in the vehicle with item storage.
Driving the vehicle for a few meters does not solve the issue. 
Trying to pick up items from tiles outside the vehicle works fine, AIM works fine. 

# Steps To Reproduce

1. Examine a tile with storage inside the vehicle
2. Game crashes

# Expected behavior

CDDA allows me to pick up items in my vehicle. 

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-8214-ga69de80 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations],
    Alternative Map Key [alt_map_key]
]

# Additional context
I'm attaching only the surrounding part of the save file since its full size is 700 MB. 
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5697057/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5697058/debug.log)

[Felwood.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5697097/Felwood.zip)

**Comment by satheon49** [comment]
Here is a stacktrace with symbols of the crash. It seems to be related to relic comparison:
<details>

```
__GI_raise 0x00007fe85419218b
__GI_abort 0x00007fe854171859
crash_terminate_handler crash.cpp:146
<unknown> 0x00007fe85455447c
std::terminate() 0x00007fe8545544e7
__cxa_throw 0x00007fe854554799
std::__throw_out_of_range(char const*) 0x00007fe85454b3be
std::map<enchant_vals::mod, int, std::less<enchant_vals::mod>, std::allocator<std::pair<enchant_vals::mod const, int> > >::at stl_map.h:548
operator== magic_enchantment.cpp:523
operator== relic.cpp:710
item::stacks_with item.cpp:948
inventory::add_item inventory.cpp:287
inventory::operator+= inventory.cpp:176
vpart_position::form_inventory vehicle_use.cpp:1958
inventory::form_from_map inventory.cpp:541
inventory::form_from_map inventory.cpp:466
inventory::form_from_map inventory.cpp:437
Character::crafting_inventory crafting.cpp:552
item::final_info item.cpp:3976
item::info[abi:cxx11](std::vector<iteminfo, std::allocator<iteminfo> >&, iteminfo_query const*, int) const item.cpp:4101
item::info[abi:cxx11](bool, std::vector<iteminfo, std::allocator<iteminfo> >&, int) const item.cpp:1175
item::info[abi:cxx11](bool, std::vector<iteminfo, std::allocator<iteminfo> >&) const item.cpp:1170
Pickup::<lambda(const ui_adaptor&)>::operator()(const ui_adaptor &) const pickup.cpp:688
std::_Function_handler<void(const ui_adaptor&), Pickup::pick_up(const tripoint&, int, Pickup::from_where)::<lambda(const ui_adaptor&)> >::_M_invoke(const std::_Any_data &, const ui_adaptor &) std_function.h:300
std::function<void (ui_adaptor const&)>::operator()(ui_adaptor const&) const std_function.h:688
ui_adaptor::redraw_invalidated ui_manager.cpp:251
ui_adaptor::redraw ui_manager.cpp:210
ui_manager::redraw ui_manager.cpp:292
Pickup::pick_up pickup.cpp:1080
game::pickup game.cpp:6036
game::pickup game.cpp:6025
game::handle_action handle_action.cpp:1942
game::do_turn game.cpp:1506
main main.cpp:709
__libc_start_main 0x00007fe8541730b3
_start 0x0000563d8301e8de
```
</details>
The code in magic_enchantment.cpp is quite new. Might be related to #45878. AIM is bit more robust but crashes too when trying to select the square with the offending relic (cargo space behind the minifreezer on the non driver side)
