### ISSUE TITLE
More realistic blood type distribution (following #40986)

### ISSUE THREAD

**Issue by actual-nh** [CleverRaven/Cataclysm-DDA#46066]
# Is your feature request related to a problem? Please describe.

The blood type distribution is currently **extremely** unrealistic, and needs fixing if want to consider doing blood transfusions.

# Describe the solution you'd like

This is from #40986 - @anothersimulacrum asked me to open a new issue for it. 

The current distribution used is a uniform one for both ABO and Rh. This is rather different from the actual blood type distribution, either on Earth, in the US as a whole, in New England, or in Massachusetts (MA). There are, most notably, far too many characters with blood type AB (universal recipient) and too few with blood type O (universal donor); in any population, AB is going to be the least common type. In other words, the PC is **_much_** more likely to have the highly beneficial (for _getting_ blood transfusions ) blood type AB.

Regarding Rh (the +/- part of a blood type), ~85-90% of people are Rh positive in most populations (around 90% of the one in question - see below). The effects of the current system (50/50) vs this on gameplay are more mixed, but this is rather easier to fix.

The approximate racial/ethnic distribution in use (for appearance) is from MA, as seen  in [json/npcs/appearance_trait_groups.json](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/npcs/appearance_trait_groups.json).

At least for people admitted to a (major) MA hospital recently with COVID-19 symptoms, the distribution can be found in [this freely-available article](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7354354/); it would need to be corrected for racial/ethnic distribution - hopefully that would account for the age distribution also (and/or it could be put together with US overall data, ideally also corrected for racial/ethnic distribution differences). It appears to agree that ~90% of the population is Rh positive (and likely even closer to 90% on the dot once race/ethnicity is figured into it, from effects on AB).

Correcting Rh to have a more usual distribution should then be as simple as substituting "!one_in( 10 )" for "one_in( 2 )". (I am **not** proposing to get into the whole Rh blood type system, which has 18 different subtypes.)

I don't know what the preferred way (for this project) is to do a randomized distribution for an enum (and the numbers for the distribution should probably be in a JSON file anyway). If there is eventually a use for blood types in the game, further refinement vs the NPC's appearance/racial/ethnic group would be nice - particularly for alternate-region mods such as (the future version of) Aftershock.

# Describe alternatives you've considered

Discard the idea of having (realistic) blood transfusions be part of the game (no thanks, particularly with changes re bionic availability coming down the pike).

# Additional context

See further discussion in #40986.

**Comment by Svankensen** [comment]
Small nitpick: You got it backwards, Rhesus negative is the rare one, which sucks for them. Otherwise, good issue!

**Comment by actual-nh** [comment]
Oops! (Rather embarrassing - positive is dominant, making it a lot more likely - not certain! - to be more common...) Correcting.

**Comment by Igryn** [comment]
Would be nice if there was also some minor risks/penalties for transfusing compatible but not the same exact blood type as your character has

**Comment by actual-nh** [comment]
If you had to receive a **_massive_** blood transfusion - as in probably unlikely to survive the need for it - you might have to start worrying about whether the antibodies in the, say, Type O blood you received might attach to your Type A/B/AB blood cells... but you also wouldn't have very many of your own blood cells to attack at that point! (This would only apply to Rh- blood going into an Rh+ person if the former had been exposed to Rh+ antigens - on Rh+ blood cells - earlier; otherwise, no antibodies would be formed against the Rh+ antigen. Someone with type O blood will have antibodies vs Type A and Type B (and thus Type AB) antigens (essentially, things that the body makes antibodies against or similarly "thinks" is hostile) because those happen to look a lot like ones in various minor infections that practically everyone gets at some point. Someone with Type A/B/AB blood will have manufactured antibodies against these infections that don't attack their own cells - hopefully! - but someone with Type O blood wouldn't have any pressure to avoid attacking A/B/AB antigens. (AB means the red blood "cells" have both A and B antigens, BTW.))

More of a penalty is that, if you use some nice Type O (universal donor) blood when you have something else (including some other donor) available that would also work (e.g., is the same blood type as the patient), you no longer have that Type O blood (or a Type O donor able to donate again right away).

Another would be with Rh+ into Rh-; yes, it can work **_once_**... but do you know for sure that patient hasn't had an emergency blood transfusion with Rh+ previously (or a woman exposed due to carrying an Rh+ fetus, possibly not to term)? Particularly if the patient is unconscious and can't tell you, even if _they_ know?
