### ISSUE TITLE
Character extremely weary an hour after starting game, with no considerable activity

### ISSUE THREAD

**Issue by John-Candlebury** [CleverRaven/Cataclysm-DDA#46073]
# Describe the bug

I was testing an unrelated robot attack by getting shot by a laser with debug invisibility. After debug killing the monster, my character suddenly became extremely weary. Consumed calories debug info shows that I have  somehow gained 1 calorie without having eaten anything.

# Steps To Reproduce
I dont personally know what triggered this. Might have been a by product of doing an advanced calendar start, since i spawned surrounded by several evolved zombies (which I also debug killed). I have included the savegame in hope its of any use

# Additional context
Heres the save file:
[Springboro.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5700475/Springboro.zip)

**Comment by Raikiri** [comment]
They usually need to have a reliable repro to debug something like this

**Comment by John-Candlebury** [comment]
I know but at least with the savefile, there can be awareness that an issue exists.

**Comment by Raikiri** [comment]
The weariness system is quite new and it's known that it has a lot of problems. Issues like this one are reported very frequently and they always ask for a repro case to investigate.

**Comment by anothersimulacrum** [comment]
You are 450 years old, and have a negative BMR (probably as a result).
![image](https://user-images.githubusercontent.com/42699974/102313785-1ba46d80-3f26-11eb-98b3-da0c0f3c2bce.png)
You are not only extremely weary, but are at weariness level 119 million.

**Comment by anothersimulacrum** [comment]
The bug might lie in your advanced scenario starting you many hundreds of years advanced?

**Comment by satheon49** [comment]
Can you check if you started this character before or after #45908 got merged? Before that PR most scenarios that advanced time started between 0-999 years after the cataclysm.

**Comment by John-Candlebury** [comment]
Yeah looking at the save, it looks like the 'Lets Play' option randomly chose to start the game in the `Ambushed` scenario, which caused the very advanced starting year.

 
> Can you check if you started this character before or after #45908 got merged (about 3 days ago)? Before that PR most scenarios that advanced time started between 0-999 years after the cataclysm.

I'm in 0.E-8137-g6a9c6ee0f0, which is from a few hours before that PR got merged. The random year issue is probably fixed (I'll check with an updated version later today).

**Comment by John-Candlebury** [comment]
Couldnt reproduce this after uprgading and testing it again.
Just forgot to close this Issue
