### ISSUE TITLE
Artifacts need their effects updated.

### ISSUE THREAD

**Issue by Varg739** [CleverRaven/Cataclysm-DDA#46075]
# Describe the bug

The "use relic" action is being added to all items with relic_data, when the use action is useless unless an activatable spell is part of that relic data.

# Steps To Reproduce

Utilize an artifact with the "ARTC_PORTAL" effect.

# Expected behavior

Nothing happens.

# Screenshots

# Versions and configuration

# Additional context

**Comment by anothersimulacrum** [comment]
Please fill in the rest of the report. This was fixed in #45409

**Comment by kevingranade** [comment]
Don't forward nonsense bug reports for people that have been banned from the project in part for filing nonsense bug reports, thanks.
