### ISSUE TITLE
Herb volumes too large - reduce or add drying

### ISSUE THREAD

**Issue by DalenTalas** [CleverRaven/Cataclysm-DDA#46080]
# Is your feature request related to a problem? Please describe.
Herbs (chamomile, bee balm, etc.) have the volume of 0.25 L when collected / used. That's about a cup. As far as collection goes, that may be realistic. However, when brewing teas IRL (personal experience here), the volume used per cup of brew is about 1-2 teaspoons (0.01-0.02 L or so).

# Describe the solution you'd like
Reduce the volume (and possibly the weight) of the items to match black/green tea leaf. Flowers may then drop several of them when collected.

# Describe alternatives you've considered
As an alternative, add a "dried" counterpart for each herb, and associated recipes. Update the tea recipes to use either fresh or dried herbs. Add the ability to place the herbs into smokers. Possibly, add spoilage to fresh herbs.

Possibly give rose hips the same treatment. Possibly create a recipe for fruit tea made out of dehydrated fruit.

**Comment by Owlblocks** [comment]
Think I'll try my hand at this. It's my first time working with Cataclysm JSONs, but I should be able to manage it :)

**Comment by Owlblocks** [comment]
I made changes to chamomile and bee balm to have less mass and volume. They're more than the tea bags, as they're fresh, and it has the added benefit of making the tea bags (which you find as loot, I believe) very slightly "better" in terms of mass. It does mean that it will be easier to make tea and seeds, as the underbrush/plant drop 4-8 now (I have to go back and see about drops from the farmed crops... I didn't modify those, and I assume the bee balm at least doesn't use the same drops). In addition, I modified the lotus slightly, to weigh less and make more tea, as it as to be made in a batch of 4 (as it's the flower tea, my understanding is that it's made in a larger amount, using the whole flower which is very big).
Does this sound like a good solution? I'm a bit unsure of myself, I suppose, but it would be good to get feedback on the changes to make sure they solve the problem.
https://github.com/Owlblocks/Cataclysm-DDA/tree/herb-weight

**Comment by anothersimulacrum** [comment]
> Does this sound like a good solution? 

Sounds so to me.

> I'm a bit unsure of myself, I suppose, but it would be good to get feedback on the changes to make sure they solve the problem.

The best way to do that is to make a PR :).

**Comment by DalenTalas** [comment]
I'd say, the batch size for lotus tea would be 8 for realism. See here for reference, that's at least a 2-L bowl: https://en.wikipedia.org/wiki/Lotus_tea#Lotus_flower_tea

However, IMO, 4 works great for balance reasons.
