### ISSUE TITLE
Heavy locker movement performance 

### ISSUE THREAD

**Issue by Aivean** [CleverRaven/Cataclysm-DDA#46088]
# Describe the bug

Moving a locker filled with corpses takes considerable time IRL.

Discovered [here](https://www.reddit.com/r/cataclysmdda/comments/ke8pm0/the_heaviest_locker_in_the_world/)

# Steps To Reproduce

1. Fill locker with corpses
2. Grab locker
3. Move locker
4. Observe slow simulation

# Expected behavior

Simulation speed should be the same as for other long-time operations, like waiting and crafting.

# Screenshots

![locker_move](https://user-images.githubusercontent.com/2865203/102441536-54e8e600-3fd7-11eb-8928-96b9abb2fc7a.gif)

# Versions and configuration

- OS: MacOs
    - OS Version: Name: Mac OS X; Version: 10.14; Build: 18A391; 
- Game Version: 0.E-8160-g80e3ea9caf-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm]
]

# Additional context

Here's the profile of the locker movement:
![image](https://user-images.githubusercontent.com/2865203/102441694-a1342600-3fd7-11eb-9059-767242a0977f.png)

The solution would be to use `activity_actor` for furniture movement (as, apparently it can take long time).

**Comment by kevingranade** [comment]
Need to re-test this now that #45840 is merged.

**Comment by Aivean** [comment]
Confirmed, fixed by #45840
![move2](https://user-images.githubusercontent.com/2865203/102666463-d8234c80-413b-11eb-9322-44e3a8a41dbc.gif)
