### ISSUE TITLE
Text Mis-wrapping

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#46087]
# Describe the bug

Improper text wrapping, possibly due to incorrect padding.

# Steps To Reproduce

Enter the Disassemble Item menu with Ammo on the ground nearby.

# Expected behavior

Expected the text not to wrap.

# Screenshots
Note the red "e." on the left; this is a continuation of the previous line's warning about bullet pulling.
![textwrap](https://user-images.githubusercontent.com/13796683/102424830-0426bc80-3fda-11eb-95e1-d7a04e071118.png)

# Versions and configuration

- OS: Windows 10 20H2
- Game Version: 0.E-8214-ga69de80 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded:
-- Dark Days Ahead [dda],
-- C.R.I.T Expansion Mod [crt_expansion],
-- No Fungal Monsters [No_Fungi],
-- Disable NPC Needs [no_npc_food],
-- Alternative Map Key [alt_map_key],
-- SpeedyDex [speedydex],
-- Stats Through Kills [stats_through_kills],
-- Stats Through Skills [StatsThroughSkills]

# Additional context

There could be other places where a bug similar to the one causing this is happening.
I suspect this display is similar; note the text of the sign appearing deflected one row up and one column over.
![SignError](https://user-images.githubusercontent.com/13796683/102424785-eb1e0b80-3fd9-11eb-8046-0f161477a27d.png)

**Comment by Valares** [comment]
Probably related to / of the same origin as issue #34928.

**Comment by BrettDong** [comment]
What is your terminal size?

**Comment by ToxiClay** [comment]
> What is your terminal size?

Terminal width is 320; terminal height is 90. This corresponds to my 2560x1440 display.

**Comment by BrettDong** [comment]
Is this issue still present for you in latest experimental version? I am unable to reproduce this:

<img width="2672" alt="螢幕截圖 2021-01-01 上午11 57 14" src="https://user-images.githubusercontent.com/21075502/103442963-804f1000-4c28-11eb-8e7d-5f0f48b56696.png">

**Comment by ToxiClay** [comment]
Yes, this issue is still present as of `0.E-8560-ga3bf351`.

![image](https://user-images.githubusercontent.com/13796683/103443232-171ccc00-4c2b-11eb-9ecb-c195494fe53f.png)

**Comment by BrettDong** [comment]
Can I have your save file?

**Comment by ToxiClay** [comment]
The problem seems to occur because the game is able to look at a bullet held within a magazine held within a gun as a valid target for disassembly, which nudges the entry over, causing the wrap. Observe the single .357 SIG JHP bullet: unloading it from the magazine causes it to move down to the Floor section and no longer wrap.

![image](https://user-images.githubusercontent.com/13796683/103443301-ba6de100-4c2b-11eb-9b7f-2bad89169cdd.png)


[Fort Bidwell.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5759194/Fort.Bidwell.zip)
