### ISSUE TITLE
Prices when trading bugged. Literally money for nothing.

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#46081]
# Describe the bug

Prices when trading depend on various factors (I presume), however merchants will trade at a clear loss which is not right.

# Steps To Reproduce

1. Find someone willing to trade.
2. Have reasonable social skill? (I had Social 6) Be on good terms with Merchant's faction? (Free Merchants view me as 'Highly Valued')
3. Trade an identical item for one in the Merchant's stock

Result: Merchant will buy the object for more than he sells it for, giving you credit for a meaningless transaction.

In my case, I was buying a Hub 01 Gold coin for $50 while selling one for $67.50. 

![bargain](https://user-images.githubusercontent.com/54060142/102382218-1a288300-3fc2-11eb-88d5-7aa8cf3ae051.png)

# Expected behavior

The best you should be able to get is that you can trade items either way for exactly as much as the merchant considers them to be worth. e.g. 'Trading at cost'.

# Versions and configuration

- OS: Windows 8.1
- Game Version: 0.E-7353-g967d80c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    No Fungal Monsters [No_Fungi],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by PaulBlay** [comment]
On a related note, NPCs will train you in 'bartering' which doesn't seem to be an actual skill anymore?

**Comment by misterprimus** [comment]
IMO NPCs should only trade an item or two they are willing to give up and only for a specific item or two that they want. For example, a character with an M4A1 shouldn't be willing to trade it away, but he might trade away some food in exchange for .223 rounds. Open ended trading like we have is way too abusable. You can literally just pick up some junk laying around the NPC and get him to give up anything he has.

**Comment by actual-nh** [comment]
@misterprimus: An absolute "this item will not be tradable" is currently possible, but doesn't really fit circumstances like traders. If someone has more than one M4A1 (or multiple comparable weapons), trading some of the "extra" for, say, ammunition or medical supplies is perfectly sensible.

What seems to be required is for social skill to increase (but not above 100%) what _proportion of "fair value"_ an NPC will pay for what you're selling them, and decrease (but not below 0%) their _markup_ on what you're buying from them.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/beretta-px4-storm-9x19mm-has-no-barter-value/25533/3

**Comment by andrei8l** [comment]
Other games solve this by biasing the prices against the player, but here both NPC and player are on equal ground and use the same formula. I've tried to figure out a way to solve this without a bias (ex: cache prices), but there's always a way to game it.

**Comment by andrei8l** [comment]
Fixed in #57706
