### ISSUE TITLE
Make fire/raging fire cook off bullets in turrets

### ISSUE THREAD

**Issue by KittyTac** [CleverRaven/Cataclysm-DDA#46097]
# Is your feature request related to a problem? Please describe.
So I set the lab corridor with the turret on fire at the end of my lab run. The turret was unscathed. I don't think this makes much sense considering the heat, if it didn't ruin the electronics, would just blow up the ammo reserves. 

# Describe the solution you'd like
Make fire under a turret have a chance to make it cook off (small fires are excluded). This empties the turret's ammo reserves and causes an explosion that destroys or heavily damages the turret, rendering it harmless.

# Describe alternatives you've considered
None.

# Additional context
Turret just chilling in an inferno:
![image](https://user-images.githubusercontent.com/52408044/102477717-4c53e680-408f-11eb-9130-f6aceade999c.png)

**Comment by satheon49** [comment]
Isn't that almost the same as just making turrets susceptible to fire? The end result would be the same: destroyed turret and no ammo.

IF turrets can be destroyed by fire (either directly or by destroying its ammo reserve) it should only happen for raging fires so you can't just take out turrets by throwing a molotov at them.

**Comment by actual-nh** [comment]
> IF turrets can be destroyed by fire (either directly or by destroying its ammo reserve) it should only happen for raging fires so you can't just take out turrets by throwing a molotov at them.

Raging fires should, yes; lesser fires, probably only with an already-damaged turret. Fire could also disrupt their targeting (I don't remember if it currently does or not).

**Comment by J-Cieplinski** [comment]
@KittyTac could you send over a save file for that?

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
