### ISSUE TITLE
[Magiclysm] - Add more magical focus

### ISSUE THREAD

**Issue by Askethil** [CleverRaven/Cataclysm-DDA#46099]
# Is your feature request related to a problem? Please describe.

- Allow wand to cast a spell.
- Add "lesser" and "greater" version of  "staff of the magi".
- Add recipe for "staff of the magi"

# Describe the solution you'd like

- [x] Add the "MAGIC_FOCUS" flag on wands
- [x] Add or update each version of the magi staff( minor,lesser,greater)
- [x] Add recipe for Magi staff using bulette pearl as main ingredient.
- [x] Add missing ingredient for the recipe
- [x] Add new Recipe book and ingredient in itemgroups

# Describe alternatives you've considered
I'm considering to change the passive effect of magi staff to MANA_REGEN instead of MAX_MANA.
MAX_MANA is more pratical on item you can wear.

# Additional context
I can make the change without a problem. I just want someone to review my idea.

**Comment by anothersimulacrum** [comment]
CC @KorGgenT

**Comment by KorGgenT** [comment]
magic focus on wands is a 100% yes do it

the staff's a good point about wearables being better - maybe swap the staff and the wizard hat? i like the idea of the bulette pearl usage, though it should totally only be for one of the tiers.

**Comment by Askethil** [comment]
Thank for you suggestion, after some thought :
- Minor staff :   Stout Branch, small mana crystal , 100 crystalized mana 
- Lesser staff : "Magic Pearl", Stout Branch,  300 crystalized
- Greater staff : Bulette Peal, Stout Branch,  2000 crystalized

the minor staff should be easy to craft to let the player step into magic early. 
The Magic Pearl would be a craftable ingredient, a man made invention to imitate bulette pearl to a lesser extent.
The use of crystalized mana are for the enchantment on the staff.

And good point about switching wizard hat mana regen to max mana.
