### ISSUE TITLE
Make corn millable

### ISSUE THREAD

**Issue by DalenTalas** [CleverRaven/Cataclysm-DDA#46090]
# Is your feature request related to a problem? Please describe.
Processing corn into cornmeal takes an extensive amount of time. AFAIK, IRL it is millable.

# Describe the solution you'd like
Allow mechanization of this labor by enabling corn to be milled into cornmeal in wind- and watermills.

**Comment by PatrikLundell** [comment]
A significant difference between corn and other cereals is that the "others" group is fairly dry and can be milled once threshed. Corn, however, is full of water, so any attempt to grind it directly after getting it off the cobs should result in some kind of paste, i.e. you'd need a drying phase for corn (possibly through a smoker) before it would be ready for grinding.

**Comment by Svankensen** [comment]
It can be oven or sun dried. Oven drying takes about 8 hours at low temps, so... uhhh, let's do it in some way that doesn't require players atention?

**Comment by PatrikLundell** [comment]
I completely agree it's silly to have the player sit and watch while a dehydrator operates. Tossing it into a smoker doesn't require much work and is a functionality that already exists in the game, while it's probably harder to code in a functionality for a mill to take longer (and use up the facility) for things that need a drying session first.
I'm not opposed to tarp drying, but, again, someone would need to make a recipe for it (i.e. a start the process, walk off, and then finish it when the processing is done one).

**Comment by DalenTalas** [comment]
This was resolved in one of the later updates.
