### ISSUE TITLE
Hostile zombie masters can "upgrade" friendly zombies. 

### ISSUE THREAD

**Issue by DocGhast** [CleverRaven/Cataclysm-DDA#46093]
# Describe the bug

Friendly skeletons summoned using magiclysm can be upgraded to juggernauts by hostile zombie masters. 

# Steps To Reproduce

1.Summon some skeletons
2.Spawn in a zombie master (or three)
3.Wait. 

# Expected behavior

Masters probably shouldn't target creatures that are hostile to it with a buffing ability. 

# Additional context

This is honestly a bit of a rare occurrence. You need to have skeletons out, while a master is around and doesn't have any other targets. They do despawn at the end of the spell duration as expected.

**Comment by lcy03406** [comment]
We say this is a feature that perfectly simulates zombie brains.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.E-10390. Summoned dozens of skeletal zombies, debug-spawned zombie master. The latter didn't try to upgrade my friendly skeletons.
