### ISSUE TITLE
Human blood is much heavier than it should be.

### ISSUE THREAD

**Issue by gisaku33** [CleverRaven/Cataclysm-DDA#46109]
# Describe the bug
Human blood is listed at 0L per unit, but weighs .58lbs. 

# Steps To Reproduce
1. Spawn in or otherwise look at human blood.
2. See that it's much heavier than it's volume would suggest.

# Expected behavior
A unit of human blood being an accurate weight, either by increasing the volume of each unit or decreasing the weight.

# Screenshots

# Versions and configuration

# Additional context

**Comment by actual-nh** [comment]
The question being what the "unit" is supposed to represent. 0.58 lbs of water would be ~263 mL.

**Comment by Svankensen** [comment]
A blood unit is a standard half a liter. 520ml in volume to be precise. 450 ml of blood plus about 70ml of anticoagulants. The bag weighs about 50 grams, depending on brand and what-not. for simplicity's sake let's assume it is half a kg. Blood in reality weights 6% more than water, but the anticoagulant is considerably less dense than water, yada yada.

**Comment by hexagonrecursion** [comment]
Is this the item you are talking about? volume: 250 ml, weight: 262 g i.e. slightly denser then water (250 g).
https://github.com/CleverRaven/Cataclysm-DDA/blob/b20ada9ea7f44c984862f64a7fecfa3b9046b01c/data/json/items/comestibles/carnivore.json#L720-L738
