### ISSUE TITLE
"Eternal season" setting forces Spring season

### ISSUE THREAD

**Issue by airportation** [CleverRaven/Cataclysm-DDA#46115]
# Describe the bug

During world creation, choosing "Eternal season" to be true with an Initial Day above 91 causes the season to always be Spring instead of the desired season. This bug exists with multiples of 91 too, for instance an eternal winter world cannot be created either, and will also default to Spring.

# Steps To Reproduce

1. Create a new world with the world options "Eternal season: true" and "Initial day: 101", change no other settings.
2. Start a new game in the world, using any scenario that uses the default calendar.
3. Check the date. It will be Spring, day 11.

Doing the same steps without eternal season starts the game on Summer, day 11, as expected.

# Expected behavior

Initial day of 101 should start the player on Summer day 11.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-8291-gf768c07 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by wapcaplet** [comment]
Confirmed on dev Discord, using build 11290.
