### ISSUE TITLE
Cannot reload any battery or magazine without removing current magazine/battery first

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#46122]
# Describe the bug

When any battery-powered device has a battery installed, using the `r`eload action on the device says `You can't reload anything with the ammo you have on hand`.

# Steps To Reproduce

1. Get a cell phone, cordless drill, arc welder, or vibrator
2. Get 2 or more compatible batteries for each device(s)
3. Select the empty device and `r`eload a battery into it - works OK
4. Select the same device (now with battery), and try to `r`eload another battery into it - denied

Workaround: `U`nload the battery first, then `r`eload it with another one

# Expected behavior

I should be able to select any compatible battery to reload the device with, whether it already has a battery in it or not.

Also, the message should not be talking about "ammo" when reloading batteries.

# Screenshots

![image](https://user-images.githubusercontent.com/238395/102670699-9bac1c80-414c-11eb-906e-67f0ff8ad882.png)

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-8292-g00db780b75 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

~~Possibly introduced~~ by 2c73e87acc

Confirmed, this bug was introduced with the above commit in #46000

**Comment by ToxiClay** [comment]
This bug does not appear to be present in build 11259, at least in my save.

Contents of inventory:
1. Cordless drill (500/500)
2. Makeshift arc welder (492/500)
3. 2x medium battery (500/500)

`r`eloading the arc welder acts as expected, swapping the 492 battery with one of the held 500s.

[Woodcock.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5718600/Woodcock.zip)

**Comment by wapcaplet** [comment]
That agrees with my testing - the bug was introduced more recently than build 11259. Builds up to 11263 should work, but I expect 11264 and later will be affected by this bug.

**Comment by ToxiClay** [comment]
Oh whoops, I should have looked at the actual date the linked commit was _merged_ and not simply _made._ Today I am the dumb.

Quickly updating to 11265 for verification...

And confirmed, 11265 exhibits this behavior.

**Comment by Svankensen** [comment]
It is affecting guns too. A partially spent magazine inside a rifle won't allow the rifle to be reloaded unless you manually remove the clip.

**Comment by wapcaplet** [comment]
> It is affecting guns too. A partially spent magazine inside a rifle won't allow the rifle to be reloaded unless you manually remove the clip.

Confirmed. It seems to be trying to reload individual *bullets* into the magazine - I cannot `r`eload the entire magazine into the gun unless it is completely empty. However, if I have spare bullets for the magazine in question, then I can `r`eload them directly into the gun (without taking the magazine out).

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/reloading-batteries-changed-recently/25546/3

**Comment by zantanzuken** [comment]
it seems that the overall error here is that the battery in an object is treated as a magazine, and such, if you need to 'reload' it, it looks for any spare charge in your inventory (but thats impossible, as its all stored in batteries)

the same for weapon magazines, its attempting to load single bullets into the magazine, but allows you to swap out an empty mag for a new one as its completely empty.

working from this idea, i grabbed a spare flashlight i had with a disposable empty battery, put the empty battery into the flashlight then tried to reload it and it allowed me to swap it out for a new battery no problem. its specifically when the battery/magazine is partially empty.

**Comment by kevingranade** [comment]
Probably caused by #46000, it's at least very adjacent.
