### ISSUE TITLE
Freeze in  `item::deserialize` (during `submap::load`)

### ISSUE THREAD

**Issue by Aivean** [CleverRaven/Cataclysm-DDA#46127]
# Describe the bug

When loading submap game freezes.

From the brief debugging I think it tries to deserialize invalid item json, fails, and then probably fails to advance parsing cursor, infinitely retrying to deserialize the invalid item.

# Steps To Reproduce

1. Load the savefile from this issue #41220
2. Walk diagonally in the NE direction (see gif)
3. Observe freeze

![freeze](https://user-images.githubusercontent.com/2865203/102678081-ea60b300-415a-11eb-9d07-bce49c9e43ad.gif)

# Expected behavior

If that is indeed caused by invalid item, the item should be skipped and error displayed, no freeze should happen.

# Screenshots

Profiling:
![image](https://user-images.githubusercontent.com/2865203/102678107-15e39d80-415b-11eb-80e8-ec3f29ddd050.png)

# Versions and configuration

- OS: MacOs
    - OS Version: Name: Mac OS X; Version: 10.14; Build: 18A391; 
- Game Version: 0.E-8298-g838ce8c564 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    No Rail Stations [No_Rail_Stations],
    Graphical Overmap [Graphical_Overmap]
]

# Additional context

I'm not 100% sure, but that might be a regression from #45617 or #45635.

**Comment by Aivean** [comment]
@anothersimulacrum , if you have a chance, please take a look.

**Comment by anothersimulacrum** [comment]
So far, I think I need to go through and note down/fix all the places this is failing to visit members. Past that, we'll see what's up.
