### ISSUE TITLE
Character drops granola from tin can

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#46133]
# Describe the bug

When `E`ating granola from a tin can, the character dumps it on the ground after eating a unit.

# Steps To Reproduce

1. Load attached save.
2. Open inventory and observe that the granola is in the medium tin can.
3. `E`at granola.
4. Wonder why your character dumped the granola on the ground.

# Expected behavior

I expected the character to not carelessly dump his food on the ground, but rather to leave the rest in the tin, as happens with other food types.

# Versions and configuration

- OS: Windows
    - OS Version: Windows 10 20H2 (build 19042.685)
- Game Version: 0.E-8214-ga69de80 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded:
    - Dark Days Ahead [dda],
    - C.R.I.T Expansion Mod [crt_expansion],
    - No Fungal Monsters [No_Fungi],
    - Disable NPC Needs [no_npc_food],
    - Alternative Map Key [alt_map_key],
    - SpeedyDex [speedydex],
    - Stats Through Kills [stats_through_kills],
    - Stats Through Skills [StatsThroughSkills]

# Additional context

[GranolaWhy.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5718976/GranolaWhy.zip)

**Comment by anothersimulacrum** [comment]
Perhaps they are not a fan.

**Comment by ToxiClay** [comment]
If my character doesn't like peanut butter granola with maple syrup, I don't want anything to do with them! :)

**Comment by wapcaplet** [comment]
Confirmed in a new game; eating a single serving of granola automatically moves the remaining granola out of the container it was in, but only for some containers and not others:

- small tin can (0.25L, rigid): removed
- medium tin can (0.5L, rigid): removed
- large tin can (3L, rigid): stays in
- small cardboard box (2L, rigid): stays in
- plastic bag (6L, non-rigid): stays in
- fanny pack (2.5L, non-rigid): stays in

**Comment by DalenTalas** [comment]
Seems like this is tied to items that spill upon placing them into another storage container.

**Comment by emptytriangle** [comment]
5 second rule, it's still good

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.E-10390. Put granola in a wielded medium tin can. Ate some granola. The rest of it stays in the can.
Also tested small tin can - the rest of the granola stays in the can.
