### ISSUE TITLE
Erroneous "completely refilled" message

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#46143]
# Describe the bug

Game log erroneously indicates "completely refilled" when I dump a gallon jug of water into a 60L tank.

This situation can also lead to a resurgence of #46091 if you attempt to use a sealed plastic bottle of water, demonstratable in the attached save.

# Steps To Reproduce

Refill a vehicle-mounted 60L tank with a gallon jug from within the car.

# Expected behavior

I expected the game to not say that the tank was completely refilled.

# Screenshots

![RefillLies](https://user-images.githubusercontent.com/13796683/102686539-59b7c080-41b6-11eb-93c8-4e97da648cd7.png)
![RefillProof](https://user-images.githubusercontent.com/13796683/102686540-5c1a1a80-41b6-11eb-8eff-faa8f14f973f.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 20H2 (build 19042.685)
- Game Version: 0.E-8214-ga69de80 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded: 
    - Dark Days Ahead [dda],
    - C.R.I.T Expansion Mod [crt_expansion],
    - No Fungal Monsters [No_Fungi],
    - Disable NPC Needs [no_npc_food],
    - Alternative Map Key [alt_map_key],
    - SpeedyDex [speedydex],
    - Stats Through Kills [stats_through_kills],
    - Stats Through Skills [StatsThroughSkills]

# Additional Context
[Water Lies.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5719165/Water.Lies.zip)

**Comment by wapcaplet** [comment]
Confirmed in 0.E-8292-g00db780b75 in a brand new world/character:

- Spawn a vehicle with a 60L fuel tank, gallon jug, and rubber hose
- Siphon some of the vehicle's fuel into the gallon jug (tank starts only 3/4 full)
- Refill the vehicle tank from the gallon jug: "You completely refill the ... vehicle tank (60L)"

**Comment by ToxiClay** [comment]
Interesting addendum: this message does _not_ appear if I dump a plastic canteen into it.
