### ISSUE TITLE
Zones can no longer ber rearranged #11273

### ISSUE THREAD

**Issue by soggylithe** [CleverRaven/Cataclysm-DDA#46158]
# Describe the bug
Zones in the 'Y' Zone Menu can no longer be moved up and down with the hotkey shown (+/-)

# Steps To Reproduce

1. Create world
2. Add 2 random zones
3. Be unable to rearrange them

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-8333-gf4ad3b9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

When loading up an older save it also undoes any ordering that was previously done on zones.

**Comment by wapcaplet** [comment]
Likely caused by my PR #46054 that changed them to sort by name.
