### ISSUE TITLE
[Tiles] Vehicle Construction Interface Preview

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#46154]
# Is your feature request related to a problem? Please describe.
As my ability to interact with the game has grown, one pain point I've found lies in the vehicle construction interface. The interface is represented with console graphics irrespective of what the player is actually looking at, which can lead to frustration when the glyph used to display a part in vehicle construction matches with a tile that looks very strange.

# Describe the solution you'd like
There's a large amount of empty space in the ~~middle and right~~ all three panes of the interface; invoking part installation where the part can have multiple shapes could put a representation of the car in the player's chosen tileset in that space, allowing the player to see what each shape selection looks like in tiles.

# Describe alternatives you've considered
The tileset representation could be invoked separately by a button press, if need be.

# Additional context
See screenshot; the space on the right is completely unused, and the middle pane's part list is irrelevant while the shape selection menu is invoked.

Edit: Even the space on the left, underneath the console representation, is irrelevant for the duration that the shape selection menu is invoke.
![VehicleInterface](https://user-images.githubusercontent.com/13796683/102697428-b5f50180-4203-11eb-8b41-7017aad58d1c.png)

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
