### ISSUE TITLE
`mod_tileset.json` files throw errors despite correct core game format of JSON

### ISSUE THREAD

**Issue by Kenan2000** [CleverRaven/Cataclysm-DDA#46166]
# Describe the bug
When using `mod_tileset.json` files and using the core `mod_tileset.json` format that can be found in mainlined mods `sees_player_retro`, `sees_player_hitbutton`, `Chibi_Ultica`, the game throws JSON errors despite using 100% same format (Error itself is provided below in Additional Context)

# Steps To Reproduce
1. Make a test mod, make a `mod_tileset.json` file inside of it and fill in the `"compatibility":` JSON line according to the core game `mod_tileset.json` format as can be seen in the attached images with whatever existing tilesets - whether mainlined or not - does not matter
2. Launch the game and wait until the loading reaches `Tileset`
3. The game throws errors despite the correct format of JSON

# Expected behavior
The game does not throw errors because the used JSON format is correct, since exactly the same format works in the core `mod_tileset.json` files in mainlined mods

# Screenshots
![555555555](https://user-images.githubusercontent.com/43505148/102702558-95698d80-427d-11eb-8705-7b53c184c9fe.png)
VS
![33333333333](https://user-images.githubusercontent.com/43505148/102702561-9b5f6e80-427d-11eb-9234-d4bce1ff8ad8.PNG)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-8333-gf4ad3b9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Test Mod [test_mod]
]

# Additional context
I've tried everything, none of which worked:

1) "un-linting" entirely  the compatibility lines and trying to remove space after `:`;

2) removing the tileset `id`s one by one - I've tried only Chibi_Ultica, OR only UltimateCataclysm, OR only UDP tileset, OR only retrodays, OR only MSXotto - nothing worked at all;

3) putting mod's tileset files outside of the `mod_tileset` folder so that the format corresponds with the official mainlined `mod_tileset` using mods

Here is 1) the JSON code that I'm using in the test mod and 2) the error that I'm getting

As you can see in the images above, the `mod_tileset.json` format that I'm using is the same as in the official repository's mainlined mods, so I'm puzzled, why it throws these errors, moreover, the graphics and tiles in both mainlined and non-mainlined mods all work well irregardless of the used tileset - whether it is mainlined or not mainlined - all the graphics and tiles load up well and work nicely, yet the error in the code below persists despite the correct format, as I've already stated: 

```{
    "type": "mod_tileset",
    "compatibility": [
      "Chibi_Ultica",
      "UltimateCataclysm",
      "MshockXottoplus",
      "UNDEAD_PEOPLE",
      "UNDEAD_PEOPLE_BASE",
      "UNDEAD_PEOPLE_LEGACY",
      "UlticaShell",
      "MshockXottoplus12",
      "MSX++DEAD_PEOPLE",
      "MXplus12_for_cosmetics"
    ],
    
    
   09:30:21.495 ERROR : src/json.cpp:120 [void JsonObject::report_unvisited() const] (json-error)
Json error: <unknown source file>:4:21: Failed to visit member compatibility in JsonObject`  {
    "type": "mod_tileset",
    "compatibility":
                    ^
                     [
      "Chibi_Ultica",
      "UltimateCataclysm",

**Comment by GGgatherer** [comment]
Same here. Happened after updating from 11262 to 11270. Same "Failed to visit member compatibility in JsonObject" error.
File follows:
```[
  {
    "type": "MOD_INFO",
    "id": "ultest",
    "name": "Ultica cursor replacement",
    "description": "Changes the cursor of the UltiCa tileset.",
    "category": "graphical",
    "dependencies": [ "dda" ]
  },
  {
    "type": "mod_tileset",
    "compatibility": [ "UltimateCataclysm" ],
    "tiles-new": [
      {
        "file": "ultica_cursor.png",
        "tiles": [
          { "id": "cursor_season_spring", "fg": 0 },
          { "id": "cursor_season_summer", "fg": 0 },
          { "id": "cursor_season_autumn", "fg": 0 },
          { "id": "cursor_season_winter", "fg": 0 },
          { "id": "line_target_season_spring", "fg": 0 },
          { "id": "line_target_season_summer", "fg": 0 },
          { "id": "line_target_season_autumn", "fg": 0 },
          { "id": "line_target_season_winter", "fg": 0 },
          { "id": "animation_line_season_spring", "fg": 1 },
          { "id": "animation_line_season_summer", "fg": 1 },
          { "id": "animation_line_season_autumn", "fg": 1 },
          { "id": "animation_line_season_winter", "fg": 1 }
        ]
      }
    ]
  }
]
```
