### ISSUE TITLE
Allow the "vehicle controls" key to interact with the electronics control unit.

### ISSUE THREAD

**Issue by Svankensen** [CleverRaven/Cataclysm-DDA#46165]
# Is your feature request related to a problem? Please describe.
I'm always frustrated when I have to turn something on or off in the other end of the car, and have to press "e", a direction, pick the electronics control unit, and then interact with the rest of the components series of keys to do so. It is often simpler to walk to the other end of the car and hit "{"  (my prefered vehicle start key).

# Describe the solution you'd like
Allos the vehicle control key to interact with the electronics control unit if there are no vehicle controls immediately around.

**Comment by Raikiri** [comment]
I'm not sure how you intend for this thing to work if there's multiple devices in one tile or if a device is inside an unwalkable tile (say, you put a stereo into a wall).

**Comment by Svankensen** [comment]
> I'm not sure how you intend for this thing to work if there's multiple devices in one tile or if a device is inside an unwalkable tile (say, you put a stereo into a wall).

Oh, I meant it just for the electronics control unit. You can interact with vehicle controls from the tiles around it too.

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
