### ISSUE TITLE
Achievements window is full of `M-!` stuff

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#46168]
# Describe the bug

See the screenshot.
# Steps To Reproduce
It's always like that!

# Expected behavior

No shit.

# Screenshots
![](https://tinystash.undef.im/il/ME3P95Tz7je5q813dBoWiSrLeSqLdYx2gncsE4MFukRCeZLzWB7ANyFbwECdzzDX7YkDbicDoJu82PmwYoXPkZR)

# Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.E-8333-gf4ad3b91c3-dirty [64-bit]
- Graphics Version: Curses
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

# Additional context

**Comment by anothersimulacrum** [comment]
Did you build it yourself? If so, can you run ldd and see if you linked to ncurses or ncursesw?

**Comment by ZhilkinSerg** [comment]
See https://github.com/CleverRaven/Cataclysm-DDA/issues/39361

**Comment by l29ah** [comment]
libncursesw.

**Comment by BrettDong** [comment]
Are you using a UTF-8 locale?

**Comment by l29ah** [comment]
```
‰ locale
LANG=en_DK.UTF-8
LC_CTYPE="en_DK.UTF-8"
LC_NUMERIC=POSIX
LC_TIME="en_DK.UTF-8"
LC_COLLATE="en_DK.UTF-8"
LC_MONETARY="en_DK.UTF-8"
LC_MESSAGES="en_DK.UTF-8"
LC_PAPER="en_DK.UTF-8"
LC_NAME="en_DK.UTF-8"
LC_ADDRESS="en_DK.UTF-8"
LC_TELEPHONE="en_DK.UTF-8"
LC_MEASUREMENT="en_DK.UTF-8"
LC_IDENTIFICATION="en_DK.UTF-8"
LC_ALL=
```

**Comment by BrettDong** [comment]
What is your distribution? How did you build the game? I am unable to reproduce this on a fresh Ubuntu 20.04 LTS install.

**Comment by l29ah** [comment]
Gentoo GNU/Linux. Via https://github.com/leycec/raiagent/blob/master/games-roguelike/cataclysm-dda/cataclysm-dda-9999-r9.ebuild

**Comment by BrettDong** [comment]
Do you have `unicode` in your `USE` flag?

**Comment by ZhilkinSerg** [comment]
I can see it shows `ncurses`, not `ncursesw` in ebuild file. Is that okay?

**Comment by l29ah** [comment]
> Do you have unicode in your USE flag?

Yes.
