### ISSUE TITLE
Locks for vehicle doors

### ISSUE THREAD

**Issue by LordZanos** [CleverRaven/Cataclysm-DDA#46160]
# Is your feature request related to a problem? Please describe.
Currently, human enemies can open the doors of a vehicle. Not a big deal normally, but when fighting hordes mixed with feral humans, who can use doors, it's quite annoying to have them simply walk up and open your armored vehicles door and hop in. And by annoying I mean lethal.

# Describe the solution you'd like
We currently have cargo locks that allow you to lock some vehicle storage containers to prevent NPCs from opening them, it would be nice to have a door lock part as well.

# Describe alternatives you've considered
Well, I could remove all the doors from my car and just weld myself into it, killdozer style. 

# Additional context
As a side note I think it's weird that enemies can just hop into fast moving vehicles if they happen to be next to a door while it's open.

**Comment by kevingranade** [comment]
Sure, it could have the tradeoff that it increases how long it takes to open and close the door since you have to retrieve your keys and use them to lock or unlock the door every time you interact with it.  Ideally this would be coupled with a system that hands out a unique id to different keys and locks so they're paired and you can only unlock doors that you have the key for.

**Comment by Svankensen** [comment]
Or locking/unlocking a door could be an action like closing curtains. That way you could still forget to lock the door, like the chump you know you are.

**Comment by emptytriangle** [comment]
There seems to be a rudimentary implementation of this in-game already with the cargo_lock item. This makes the storage space inaccessible to npcs, does that also make them unable to open the door? All vehicle doors have at least some storage so will always be valid targets for cargo_lock,

**Comment by LordZanos** [comment]
I don't believe it makes the doors unopenable, and cargo_lock is only applicable to specific items, not any item with storage space. It doesn't work on doors.

**Comment by matt32106** [comment]
I second the idea that doors locking work like curtains as explained in the comments above.

**Comment by actual-nh** [comment]
See #48902 (@Igryn) for further comments.

**Comment by Numbuh474** [comment]
#61087 was attributed to a different issue but almost perfectly matches this one, taking the "curtain style" approach from the comments.
