### ISSUE TITLE
Unexpected behavior when picking up a long object

### ISSUE THREAD

**Issue by Dunqann** [CleverRaven/Cataclysm-DDA#46163]
Interface shows that the object (makeshift crowbar) will fit in my inventory.  
Vol 39.88/84.90 INDV Vol 1.00/25.00  Lng 23.62/27.56  
![image](https://user-images.githubusercontent.com/43284492/102701883-bba51400-4210-11eb-8cbe-bec94ab1f6f3.png)

But when I try to actually pick it up - it fails and says I can only wield it.

I assume that the long pocket is full (wearing Military Rucksack and Backpack and Cargo Shorts & Pants).

Suggested behavior would be for the interface to give me an indication of how my inventory capacity is failing to meet the requirements.

**Comment by Dunqann** [comment]
Appeared to be caused by my Leather Belt which could handle a 27.56 length item but not the volume and nothing else could carry something that long.

Would be helpful to get some sort of indication of where the limitation is coming from to avoid having to tear apart one's inventory.

**Comment by Aivean** [comment]
An idea for brainstorm: maybe we should display limitations on per-item basis?  Something along the lines of:

![image](https://user-images.githubusercontent.com/2865203/102724540-29127c80-42c5-11eb-80c4-4ccc6da0ee59.png)

Or:
![image](https://user-images.githubusercontent.com/2865203/102724591-7858ad00-42c5-11eb-81f9-00247723342c.png)

**Comment by Raikiri** [comment]
Can it be related to a hidden minimum item volume requirement like here https://github.com/CleverRaven/Cataclysm-DDA/issues/45802 ?

**Comment by mqrause** [comment]
Can be closed. This issue was related to the old pickup menu. The new one doesn't allow selecting items that fit no pocket and has info on why it can't be picked up.
