### ISSUE TITLE
Invalid recipe for toolbox_workshop

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#46176]
# Describe the bug

When loading CDDA builds past 11268, the game presents a non-failing error while finalizing save loading.

```
 DEBUG    : invalid recipe id "toolbox_workshop"

 FUNCTION : const T& string_id<T>::obj() const [with T = recipe]
 FILE     : src/recipe_dictionary.cpp
 LINE     : 66

```

# Steps To Reproduce

Load a savefile created in a build prior to 11268 in a game past build 11268.

# Expected behavior

I expected no error to occur.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 20H2 (build 19042.685)
- Game Version: 0.E-8291-gf768c07 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded:
    - Dark Days Ahead [dda],
    - C.R.I.T Expansion Mod [crt_expansion],
    - No Fungal Monsters [No_Fungi],
    - Disable NPC Needs [no_npc_food],
    - Alternative Map Key [alt_map_key],
    - SpeedyDex [speedydex],
    - Stats Through Kills [stats_through_kills],
    - Stats Through Skills [StatsThroughSkills]

# Additional context

I believe that this was introduced as a result of PR #46048, which brought other changes to the workshop toolbox, but it is impacting saves made in a previous version and then updated.

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5720636/debug.log)

**Comment by Fris0uman** [comment]
Probably just need to obsolete the old recipe

**Comment by ToxiClay** [comment]
How would I do that locally? And what change specifically needs to be made?
