### ISSUE TITLE
Weightless Storage Battery

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#46178]
# Describe the bug

A Storage Battery has no weight. This is replicated across two such batteries.

# Steps To Reproduce

1. Drag a storage battery out of a car.
2. Notice that it reports a weight of 400 pounds.
3. Grab that sucker off the ground and it's now weightless.

# Expected behavior

I expected to see the weight properly reflected.

# Screenshots

![StorageBatteryCarried](https://user-images.githubusercontent.com/13796683/102707853-77dff800-426c-11eb-89fb-095e4bda1f15.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 20H2 (build 19042.685)
- Game Version: 0.E-8214-ga69de80 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded:
    - Dark Days Ahead [dda],
    - C.R.I.T Expansion Mod [crt_expansion],
    - No Fungal Monsters [No_Fungi],
    - Disable NPC Needs [no_npc_food],
    - Alternative Map Key [alt_map_key],
    - SpeedyDex [speedydex],
    - Stats Through Kills [stats_through_kills],
    - Stats Through Skills [StatsThroughSkills]

# Additional context

[WeightlessBattery.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5720654/WeightlessBattery.zip)

**Comment by anothersimulacrum** [comment]
Are you standing near a crane?

**Comment by ToxiClay** [comment]
Huh, that must have been it. I had an internal boom crane tile on my vehicle, and I must have been within two or four tiles of it. I didn't know that the crane would take the weight if it existed at all.

However, in verifying this I've encountered another problem: the boom crane appears 'sticky' in that if you pick up a storage battery while within range of a crane's influence, and then you leave that area, the battery remains weightless (build 11259). This issue persists in 11273; dropping and picking up the battery when outside the crane's influence properly applies the weight.

![StickyBoomCrane](https://user-images.githubusercontent.com/13796683/102724283-89f97f00-42dc-11eb-9579-9bd318d459b2.png)

**Comment by anothersimulacrum** [comment]
Ah yeah, the weight cache won't be cleared.

**Comment by ToxiClay** [comment]
Is this possibly related to #46130 and #44661 being incompletely or non-universally applied?

**Comment by anothersimulacrum** [comment]
Yes, those are all traditional places where you'd change weight. This is a case where just moving around the map will change how much an item weighs.

**Comment by ToxiClay** [comment]
I've discovered something else. This weightless battery issue is NOT sticky _in the drop menu._

![stickyBatteryWeight1](https://user-images.githubusercontent.com/13796683/102810561-f2eefe80-4391-11eb-9fbf-4781d96e5e2a.png)
![stickyBatteryWeight2](https://user-images.githubusercontent.com/13796683/102810568-f5515880-4391-11eb-92b3-e77edbac67bc.png)
