### ISSUE TITLE
You don't have any NULL to reload your [GUN]

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#46186]
# Describe the bug

When attempting to reload a gun you can get a message missing a word.

# Steps To Reproduce

1. Have an AR-10 loaded with an empty AR-10 20-round magazine.
2. Have no relevant ammo.
3. Attempt to 'r'eload your gun.

The message given is "You don't have any  to reload your AR-10!".
(N.B. There are two spaces between 'any' and 'to' but that doesn't show up in the github post)

# Expected behavior

I expected the message "You don't have any .308 to reload your AR-10!"

# Versions and configuration

- OS: Windows 8.1
- Game Version: 0.E-8307-g3628f8c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Blaze Industries [blazeindustries]
]

# Additional context

Note 1: It is arguable that it should not be possible to reload a gun that requires a magazine directly without first removing the magazine (See https://github.com/CleverRaven/Cataclysm-DDA/issues/46151 )
Note 2: If you do remove the magazine, then attempt to reload the magazine you get the message 
"You don't have any .308 to reload your AR-10 20-round magazine!" (which is as expected)
Note 3: This presumably happens with other guns that use magazines, but I have not checked.

**Comment by PaulBlay** [comment]
Note that you also get this message if you attempt to reload a gun that does not take any ammo or magazine (e.g. Laser pistol / rifle)

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/infinite-loop-npc/25891/2

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.E-10390.

![изображение](https://user-images.githubusercontent.com/11132525/115100130-c4ea8700-9f4b-11eb-8e7e-b7a77693de7c.png)
