### ISSUE TITLE
Some animals lack interactions

### ISSUE THREAD

**Issue by OliveChukar** [CleverRaven/Cataclysm-DDA#46196]
# Describe the bug
Animals that spawn friendly lack the interaction menu that lets you pet them or tie them up.
This affects animals spawned with debug and also dermatik larvae spawned from the ovipositor special attack.

# Steps To Reproduce
1. Spawn a dermatik. 
2. Let it attack you until it sinks its ovipositor into your body.
3. Wait until larvae burst out of you. You should save scum to until you get a friendly larvae.
4. Try to interact with the larvae with the use key.
5. Use debug to spawn bird food and a non friendly chicken.
6. Use bird food on chicken. It should become friendly.
7. Use the use key on the chicken. It will have the appropriate menu.
8.  Debug spawn an already friendly chicken. It will also lack the menu. 

# Expected behavior
All friendly animals should have the same interaction options. Unless there is a clear reason for them not to. For example slimesprings are not solid and so could not be tied up.

# Screenshots

# Versions and configuration

# Additional context

**Comment by OliveChukar** [comment]
It looks like some of the info got cut off so here it is.

 OS: Windows 10
 - Game Version: .E-8214-ga69de80
 - Graphics version: Tiles 
 - Ingame language: English
 - Mods loaded: Tested with no mods

**Comment by actual-nh** [comment]
Do you mean with the default mods (such as "dda")?

**Comment by OliveChukar** [comment]
I tested this issue with core content pack dark days ahead only.
