### ISSUE TITLE
Half of my keyboard doesnt work.

### ISSUE THREAD

**Issue by Nelrea** [CleverRaven/Cataclysm-DDA#46191]
Half my keyboard isnt working. The letters and numbers do but arrows, spacebar, tab and esc etc don't work anymore. I've tried to get around this by reinstalling the game, going back to old versions, not using the launcher and its still happening. my keyboard with other games still and crome. the only mods I was using was a tilepack and I tried without that and still. i just get spammed with errors ingame like the screenshot shows. 

# Steps To Reproduce

# Expected behavior

# Screenshots

https://imgur.com/LPqhWLd

# Versions and configuration

# Additional context

**Comment by Svankensen** [comment]
Fill the rest of the info. Version, operating system, etc.

**Comment by Nelrea** [comment]
- OS: Windows 10
 - Game Version: 0.E-8356-g9a349ec (tiles) (But i did try all the versions from the last week plus the stable branch)
 - Graphics version: Tiles
 - Ingame language: En_US
 - Mods loaded: MSX++UnDeadPeopleEdition (tilepack) ( but I did try it vanilla too)

**Comment by PaulBlay** [comment]
> (But i did try all the versions from the last week plus the stable branch)

Just to be super clear - you tried 0.E-3 Ellison-3 (the latest stable release) and it didn't work either?
Did it change after a hardware or software change to your computer?

**Comment by Raikiri** [comment]
Are you sure you're using English layout and you don't have Caps Lock on? The game does not read keyboard scancodes (as most other games do), it reads input characters, and both change with layout and/or caps lock.

**Comment by Nelrea** [comment]
Yep i tried the stable branch on the launcher and the website download still the same thing happens. sometimes on a rare occasion the button will work but only very rarely.

Yep to the English layout and iv tried with and without caps locks. same thing every time.

**Comment by Nelrea** [comment]
FINALLLY! after 3 days of trying to fix this i have got it. I'm so sorry about this but my steering wheel was connected and it counts as a controller.  Normally CDDA ignores it so i don't know what changed. Im really sorry guys :S
