### ISSUE TITLE
Joystick no longer does anything when held down in any direction

### ISSUE THREAD

**Issue by Nigglos** [CleverRaven/Cataclysm-DDA#46205]
# Describe the bug
In the past, when you held the joystick in any direction, the character will travel continously in that direction. But now, it treats it as a single swipe. This applies in the options menu as well. Previously, I could hold swipe down to cycle through the options quickly, yet now I have to swipe each time to go down.

Joystick only does singular swipe actions now.

# Steps To Reproduce
Pull the joystick in any direction, it does nothing.

# Expected behavior
Continous input.

# Screenshots

# Versions and configuration
Android version arm32 b11276

# Additional context

**Comment by ZhilkinSerg** [comment]
Most probably was broken in #45909
