### ISSUE TITLE
One-tile forests and boarded-up buildings should have autonote defined

### ISSUE THREAD

**Issue by Cimanyd0** [CleverRaven/Cataclysm-DDA#46208]
# Describe the bug

There are one-tile forests, and also tiny boarded-up buildings full of rubble, that show up in what the overmap calls "field". Even with auto-notes turned on, no notes are added to the map.

# Steps To Reproduce

With the "Auto notes (Map extras)" option on, start as an EMT or something and drive around until you see something like the screenshots.

# Expected behavior

My character should be able to see a one-tile forest at the same range as normal forest tiles.

There is also the option of an autonote, like the small pond map extra, but I would only expect this for something that can't be seen from a longer distance. 

# Screenshots

(Ultica, zoomed out to avoid huge images)

![CDDA invisible forest](https://user-images.githubusercontent.com/74877667/102748238-6d366900-4327-11eb-88c8-cca74abbdd4c.png)

![CDDA invisible building](https://user-images.githubusercontent.com/74877667/102748313-8c34fb00-4327-11eb-8dbd-6c118727d444.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-8359-gbb2b16f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

I wasn't sure what template to use. This seems halfway between a feature request and a bug.

**Comment by ZhilkinSerg** [comment]
These are not map extras probably, just field mapgens with low chance.

**Comment by int-ua** [comment]
Title update suggestion: `s/that don't appear on overmap/should have autonote defined/`

**Comment by Cimanyd0** [comment]
I still think those trees would be visible at the same range as any forest, but an autonote would be better than nothing.

The only reason I care is because I have to drive around them, and with big tiles like Ultica I don't see very far on my screen.

**Comment by int-ua** [comment]
Is there an implemented way to change map icons by these mini-forests and abandoned barns?

**Comment by int-ua** [comment]
> The only reason I care is because I have to drive around them, and with big tiles like Ultica I don't see very far on my screen.

Are you aware you can zoom in and out with `z`/`Z`? I guess you are, mentioning just to be completely sure.

**Comment by NetSysFire** [comment]
These one-tile forests are called copses and are waaay to common and unremarkable to be marked. This one is a wontfix.

The fallen shed will be marked by default, so closing as fixed.

**Comment by Cimanyd0** [comment]
Yeah, it's nice to have autonote on derelict sheds (and I agree that #49784 solves that half of the issue), and it might not be a good idea on copses.

I still think it would make more sense to have them show up on the overmap itself. Fields, forests, roads and houses are all common, but if you see "road" on the map you wouldn't expect to have a bunch of trees in the middle of it, and if you see "forest" you don't expect to drive a car through it. The problem is they're map extras and not overmap terrain.

If copses are too common and unremarkable to be marked, I would also remove the autonote from Dead Vegetation, Burned Ground, and Casings, and possibly also Grove, Shrubbery, and/or Clearcut. I didn't consider them an issue because you can turn off individual extras in the Auto notes manager. You can't turn on an extra if it doesn't have an autonote to begin with.
