### ISSUE TITLE
Cutting up hiking backpacks for infinite leather patches.

### ISSUE THREAD

**Issue by jumjummju** [CleverRaven/Cataclysm-DDA#46211]
# Describe the bug

The hiking backpack requires 25 leather patches to craft, and gives just as many when disassembled, but gives upwards of 55 patches when just cut up.

# Steps To Reproduce

Just cut up a hiking backpack with a cutting tool. Works even with a basic survivor with no skills using a pocket knife and a debug-spawned hiking backpack.

# Expected behavior

For a hiking backpack to only give 25 or less leather patches when cut up.

# Screenshots

https://media.discordapp.net/attachments/598523535169945607/790511761886543892/unknown.png

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-8201-gc49b2cc [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]

**Comment by anothersimulacrum** [comment]
It's weight needs to be decreased.

**Comment by acbcodetribulations** [comment]
Each leather patch is 0.1 kg so times 25 is a bit over the 2.3 kg weight of the backpack itself. That might work for balance purposes. Disassembly seems fine, but cutting it up works differently from disassembly. Weight changed nothing, but reducing volume is reducing the amount of materiel given. 

A fresh character with a hunting knife could get 57 patches. Changing the volume to 7000 gave about 27 patches, and a volume of 6500 gave 25. So the cutting up value seems to be based on volume size. A patch is 0.25 L, which times 25 is 6250 and implies a bit of rounding or lost materiel? A plain backpack can give up to 7 rags, which is 1.75 L and close to the 2 L backpack.

Simply changing the volume gives a tardis error, which probably means something is larger on the inside than it should be. Even if we accept that quick fix, it may be preferable to change the cut up method instead.

**Comment by actual-nh** [comment]
Cutting up size for something like a backpack should be (mostly) from surface area - not volume.

**Comment by anothersimulacrum** [comment]
Oh whoops, I thought that was in.

**Comment by actual-nh** [comment]
> Oh whoops, I thought that was in.

Heh. So did I...
