### ISSUE TITLE
Ability to bring item menu in AIM

### ISSUE THREAD

**Issue by Raikiri** [CleverRaven/Cataclysm-DDA#46213]
# Is your feature request related to a problem? Please describe.
Currently AIM is a powerful tool that allows lots of item management utility, but for whatever reason it lacks the most obvious function: to interact with items. For example, sometimes I enter a complicated search term into my AIM panel, find the item that I'm looking for and ideally I want to, say, disassemble it. Right now I need to exit the AIM, hit disassemble, look for that item _again_ by its name or by the same search term, etc. It's also very non-intuitive that I can't just bring the item menu from AIM itself.

Another use-case: say, I want to (U)nload all my small cardboard boxes of random crap to save space. Currently I have to do that one by one typing "small cardb" for every cardboard box around me, that's very tedious considering there can be dozens of them around my storage. Ideally I want to write that search term into my AIM and just unload things from there.

# Describe the solution you'd like
Well, first step is to just give item menu to individual items. However, I'd love to also be able to select multiple items in the AIM and for example disassemble them, but maybe this feature is beyound the scope of this request.

# Describe alternatives you've considered
Suck it up and close AIM every time I want to interact with an item.

# Additional context

**Comment by anothersimulacrum** [comment]
See `Examine:`
![image](https://user-images.githubusercontent.com/42699974/102797335-68dc7100-4364-11eb-88d9-89607fbc1c3c.png)

**Comment by WeaverThree** [comment]
> See `Examine:`

I'd never realized that that would show the interaction menu because it doesn't if the item isn't in your inventory. Having that menu available on items on the ground would  be super amazing, really.

**Comment by anothersimulacrum** [comment]
> Having that menu available on items on the ground would be super amazing, really. 

I just tested it with that, it works with items on the ground.

**Comment by Raikiri** [comment]
I just tested it as well and it works for items in inventory and does not work for items in containers or on the ground. So since there's apparently already an interaction menu for player inventory items, is the same thing supposed to work for all other items too? Should it be a bug report instead of a feature request then?

**Comment by wapcaplet** [comment]
Confirmed, when using `e` or `E` from advanced inventory, for items on the ground nearby, only the item description is displayed, not the ineraction menu.

![image](https://user-images.githubusercontent.com/238395/102805466-7dc2ff80-4378-11eb-8808-95f393987a05.png)

Items in the inventory include the menu for doing things with the item:

![image](https://user-images.githubusercontent.com/238395/102805497-89162b00-4378-11eb-9991-25a98fa432c4.png)

**Comment by anothersimulacrum** [comment]
Oh, I see, I misunderstood.
