### ISSUE TITLE
(Magiclysm) Hand emcumbrance increase mana cost instead of difficulty and casting time

### ISSUE THREAD

**Issue by SariusSkelrets** [CleverRaven/Cataclysm-DDA#46219]
# Describe the bug

Hand encumbrance only raises the mana cost of spells instead of difficulty and casting time

# Steps To Reproduce

1. Create characther with spells
2. Wear gloves
3. Notice the identic success rate and the huge mana cost. 

# Expected behavior

Hand encumbrance should raise difficulty and casting time as your fingers can't do the gestures as well with gloves instead of spending more mana to reach the same effect

# Screenshots

naked characther
![2020-12-21 11_05_38-Cataclysm_ Dark Days Ahead - 0 E-7938-g8736e6b](https://user-images.githubusercontent.com/68650913/102798132-ac43d900-437e-11eb-99da-79190d1885a3.png)

with 2 cut resistant gloves
![2020-12-21 11_06_03-Cataclysm_ Dark Days Ahead - 0 E-7938-g8736e6b](https://user-images.githubusercontent.com/68650913/102798148-b06ff680-437e-11eb-8b1c-d455f933ea8b.png)

a verbal only spell and a naked characther
![bu](https://user-images.githubusercontent.com/68650913/102798107-a4843480-437e-11eb-95b7-923974bea4e5.png)

with 2 cut resistant gloves
![2020-12-21 11_04_53-Cataclysm_ Dark Days Ahead - 0 E-7938-g8736e6b](https://user-images.githubusercontent.com/68650913/102798105-a2ba7100-437e-11eb-9ce3-8540a1978ccf.png)

# Versions and configuration

 - OS: Windows 10 
 - Game Version: 0.E-7938-g8736e6b
 - Graphics version: Tiles
 - Ingame language: French
 - Mods loaded: 
    dda
    package_bionic_professions, 
    no_npc_needs, 
    magiclysm

# Additional context

Edit: it also applies to hp-costing spells, meaning that you could lose dozens of hp to get the same effect that would've cost you 2 hp (wearing gloves make you cut deeper?)

**Comment by anothersimulacrum** [comment]
CC @KorGgenT

**Comment by KorGgenT** [comment]
Yes, that's correct.

**Comment by SariusSkelrets** [comment]
I don’t understand if it’s intended or not

**Comment by KorGgenT** [comment]
it's intended
