### ISSUE TITLE
Ad-hoc barter value (price_postapoc)

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#46214]
# Is your feature request related to a problem? Please describe.

A number of items, possibly a bit under 10%, have the Price set but not the Barter Value (price_postapoc). Trading for these items uses the Price (I presume) instead of the (non-existent) Barter Value, which is not great because they are usually very widely different.

# Describe the solution you'd like

I would suggest that trading such items would use an 'ad hoc' barter value of Price/20 (rounded to the nearest $0.50). That is roughly in line with the massive post apocalypse deflation. 

When examining such items this ad hoc number could be displayed as "Est. barter value: " instead of "Barter value: " as a hint that the item .json could do with an actual number being assigned by a human being.

# Describe alternatives you've considered

Someone could go through all the item .json files and manually add price_postapoc wherever it is missing. *cough* Not it *cough*

# Additional context

The discussion where I started thinking about this.
https://discourse.cataclysmdda.org/t/beretta-px4-storm-9x19mm-has-no-barter-value/25533

**Comment by anothersimulacrum** [comment]
Alternatively, I think we should make `price_postapoc` mandatory.

**Comment by PaulBlay** [comment]
Making price_postapoc mandatory for new content seems like a good idea (although I don't know how you'd specify the 'new' bit). Making it mandatory for existing content would require a suitable volunteer to bell the cat.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
