### ISSUE TITLE
Magiclysm - standardize magical effect with new flags

### ISSUE THREAD

**Issue by Askethil** [CleverRaven/Cataclysm-DDA#46210]
# Is your feature request related to a problem? Please describe.

Simplify and standardize magical effect on items. It will be easier to balance item later when more magic items will be added.

# Describe the solution you'd like

Create new flags wich will : 
 - add the desired effect
 - each effect will be declined in several version ( MANA_REGEN_1,MANA_REGEN_2....)
 - add effect description on the item with different text for each ( barely/slightly/greatly/immensely... increases your mana regeneration )

# Describe alternatives you've considered

Maybe something like `"using": [ [ "forging_standard", 1 ] ]` instead of flag.
Open to suggestion,  i don't know about the difficulty. 

# Additional context

i just start with mana flags for now. I will add more  flags later (elemental_resistance, physical_resistance etc...)

Flags :

- `MITEMS_REGEN_MANA_X`  : regen mana
- `MITEMS_ADD_MANA_X`      : add mana    
- `MITEMS_MULT_MANA_X`    : add mana (multiplicative value)
- `MITEMS_MOVE_COST`         : reduce move cost
- `MITEMS_SPEED`                   :  add speed
- `MITEMS_PHYSYCAL_DEF`     :  add ARMOR_CUT,ARMOR_BASH,ARMOR_STAB,ARMOR_BULLET

Text description for each tiers :

- T0 `barely` 
- T1 `slightly` 
- T2` ???` 
- T3`greatly` 
- T4`immensely` 

Value for each tiers :

| Tiers | MITEMS_REGEN_MANA_X| MITEMS_ADD_MANA_X| MITEMS_MULT_MANA_X |
| --- | --- | --- | --- |
| 0 | 0.25 | 200 | 0.05 |
| 1 | 0.75 | 400 | 0.10 |
| 2 | 1.25 | 600 | 0.15 |
| 3 | 2 | 800 | 0.20 |
| 4 | 3 | 1200 | 0.25 |

| Tiers| MITEMS_MOVE_COST | MITEMS_SPEED |
| --- | --- | --- |
| 0 | 5 | 3 |
| 1 | 10 | 5 |
| 2 | 20 | 7 |
| 3 | 30 | 10 |
| 4 | _ | _ |

| Tiers | MITEMS_PHYSYCAL_DEF (CUT) | MITEMS_PHYSYCAL_DEF (BASH) | MITEMS_PHYSYCAL_DEF (STAB) | MITEMS_PHYSYCAL_DEF (BULLET) |
| --- | --- | --- |  --- |  --- |
| 0 | -2 | -2 |  -2 |  -1 |
| 1 | -4 | -4 |  -4 |  -2 |
| 2 |  _ | _ |  _ |  _ |
| 3 |  _ | _ |  _ |  _ |
| 4 | _ | _ |  _ |  _ |

**Comment by anothersimulacrum** [comment]
CC: @KorGgenT
