### ISSUE TITLE
You can obtain the same mutation twice

### ISSUE THREAD

**Issue by Mrzjadacz** [CleverRaven/Cataclysm-DDA#46217]
# Describe the bug

![image](https://user-images.githubusercontent.com/26396019/102785773-c5f51880-439e-11eb-8cee-a45f8c3d983a.png)
I already had it, was disabled when I took more mutagen.
![image](https://user-images.githubusercontent.com/26396019/102785814-d86f5200-439e-11eb-851d-3de2226cce92.png)

# Steps To Reproduce

Get Photophore, keep it inactive, drink insect mutagen until you get it again.

# Expected behavior

There no such problem with Nigh Vision or Insect Wings.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-8244-g56e7545 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Mythical Martial Arts [MMA],
    C.R.I.T Expansion Mod [crt_expansion],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Bionic Professions [package_bionic_professions],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP]
]

**Comment by ZhilkinSerg** [comment]
Technically these are two mutations.

**Comment by actual-nh** [comment]
Turning it on switches mutations instead of also leaving the "off" version?

**Comment by actual-nh** [comment]
What happens if you try to turn on the non-active one?
