### ISSUE TITLE
Rotten item coloration ignored if in container

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#46222]
# Is your feature request related to a problem? Please describe.
If a container is holding an item with the (rotten) tag, it currently does not change color to indicate this in the `g`et interface because the container itself is not rotten.

# Describe the solution you'd like
I think the game should color either the item or the entire container>item entry.

# Describe alternatives you've considered
No alternatives.

# Additional context
![rottenJam](https://user-images.githubusercontent.com/13796683/102807699-267b5a00-438d-11eb-967b-3aa01f90ea96.png)

**Comment by Night-Pryanik** [comment]
Fixed by #47426.
