### ISSUE TITLE
Field-dressed carcass not flagged as rotten

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#46223]
# Describe the bug

A field-dressed animal carcass will not display a (rotten) tag, but will yield rotten product.

# Steps To Reproduce

1. Kill a cerbearus.
2. Field-dress it for transport.
3. Forget about it for a bit.
4. Go back to finish the job.
5. Be sad.

# Expected behavior

I expected the game to notify me that the carcass is rotten.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 20H2 (build 19042.685)
- Game Version: 0.E-8214-ga69de80 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded:
    - Dark Days Ahead [dda],
    - C.R.I.T Expansion Mod [crt_expansion],
    - No Fungal Monsters [No_Fungi],
    - Disable NPC Needs [no_npc_food],
    - Alternative Map Key [alt_map_key],
    - SpeedyDex [speedydex],
    - Stats Through Kills [stats_through_kills],
    - Stats Through Skills [StatsThroughSkills]

**Comment by Hirmuolio** [comment]
The corpse rotten status is shown with assumption that the corpse has shelf life of 24 hours (same as chunk of meat).

If the corpse gives products with shorter shelf life then those can be rotten before the corpse shows as rotten. But the meat that comes out of it should have same state as the corpse.

**Comment by int-ua** [comment]
@ToxiClay which one is it? :point_up:

**Comment by ToxiClay** [comment]
I'll have to find an animal and play around with it. I'll put a 📌in this to update it when I find one and remember to replicate this.

**Comment by I-am-Erk** [comment]
Closing as stale
