### ISSUE TITLE
AIM move-all command fails in vehicles

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#46228]
# Describe the bug

The move-all command, `,`, when used to move items between storage tiles in a vehicle, does nothing.

EDIT: Specifically, move-all-_from-area._

# Steps To Reproduce

1. Load attached save
2. Open AIM
3. Attempt to use `,` to move all items
4. Cry.

# Expected behavior

I expected all items to move.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 20H2 (build 19042.685)
- Game Version: 0.E-8214-ga69de80 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded:
    - Dark Days Ahead [dda],
    - C.R.I.T Expansion Mod [crt_expansion],
    - No Fungal Monsters [No_Fungi],
    - Disable NPC Needs [no_npc_food],
    - Alternative Map Key [alt_map_key],
    - SpeedyDex [speedydex],
    - Stats Through Kills [stats_through_kills],
    - Stats Through Skills [StatsThroughSkills]

(oh god wow I'm dumb ignore that)

# Additional context

[AIMVehMove.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5726438/AIMVehMove.zip)

**Comment by wapcaplet** [comment]
Confirmed in the attached save, as well as in a new game in 0.E-8366-gafe3659f78.

This seems to occur most predictably when moving all items from `a`ll surrounding tiles into a single destination tile or cargo space.

When moving all items from a *single* tile or cargo space to another tile or cargo space, the move-all command works as expected.

**Comment by ToxiClay** [comment]
It seems to work reliably if I'm doing it on the ground, but never if I'm moving into a cargo space.

**Comment by Raikiri** [comment]
I have a Barret rifle that always interrupts move-all command when I move a bunch of items into a shopping basket vehicle. It transfers items in the item list until the transfer command reaches that specific rifle and then it stops. If I transfer all again after that, it transfers the rifle as well as the rest of the items. Not sure, maybe this could be related.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-11021.
