### ISSUE TITLE
Random 'initial day' setting also affects player spawn delay

### ISSUE THREAD

**Issue by sick-trigger** [CleverRaven/Cataclysm-DDA#46232]
# Describe the bug
Setting the initial day to -1 randomises the starting day/season (as intended) but also impacts how many days after the cataclysm that the player spawns, leading to inconsistent zombie evolution and food rot.
# Steps To Reproduce
1. Make new world with spawn delay set to 0 (default) and initial day set to -1
2. Make new default char and teleport into town, food has rotten away and the place is full of skeletal juggernauts and necro-boomers.
3. Reset world, repeat last step, food is fresh and the zombies are all a light green Z
# Expected behavior
Starting day should randomise, but food should be fresh and zombies should start with some minor upgrades
# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-8371-gef8afe2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
# Additional context
Was introduced in #45908 i think

**Comment by ZhilkinSerg** [comment]
It was like that before #45908 - when scenario did not define start season `INITIAL_DAY` affected cataclysm start, while `SPAWN_DELAY` affected additional player spawn delay:

https://github.com/CleverRaven/Cataclysm-DDA/blob/cb02195d9fb5ba71f35a105be4104c3d8883065c/src/game.cpp#L11490-L11540

**Comment by sick-trigger** [comment]
random initial day is meant to pick a random date for the cataclysm to start on and then spawn the player on that day (assuming spawn delay is 0 and you're playing a normal scenario). since build 11253 (first one with #45908) it has been picking a random date for the cataclysm and the spawning the player on a totally different day, often "before" the cataclysm it seems, with zero evolution and only bog-standard zombies populatng cities,

per initial day's description 'This does not advance food rot or monster evolution'. if it is set to -1 then it will affect those things

**Comment by sick-trigger** [comment]
appears to have been fixed at some point
