### ISSUE TITLE
Get stuck dissecting if low on stamina

### ISSUE THREAD

**Issue by Aurake** [CleverRaven/Cataclysm-DDA#46234]
# Describe the bug
If you are dissecting and are low on stamina that you have to catch your breath you can get stuck dissecting and be unable to quit the action, even while fighting.

# Steps To Reproduce

1. Be somewhere that you will be attacked before you finish dissecting but not immediately after starting (inside of a city that is not completely cleared).
2. Be low on stamina
3. Have mouth encumbering equipment on so that you will run out of stamina while dissecting, necessitating the need to stop to catch your breath.
4. Start dissecting a body.
5. Be interrupted by an zombie while you are in the "catching your breath" state.

# Expected behavior

You should be able to stop dissecting and choose what to do, after completing that action you should NOT be automatically dissecting any more.

# Actual Behavior

When you are interrupted in the "catching your breath state" you can take a different action, but you after completing it you will automatically resume dissecting until you are interrupted again, either by another monster or by being attacked. This means you cannot run away and it means you cannot attack again until you are attacked. Even if you move off the corpse you will continue to dissect it.

# Screenshots

# Versions and configuration

# Additional context

What seems to be happening is if a long duration action is suspended in order for your character to catch their breath and then they are interrupted during the "catch your breath" section, the code that re-initiates the long running action is still run even though it should have been cancelled when catch your breath was cancelled. NOTE, this may not happen if you interrupt during the initial "catch your breath". This can also cause weirdness when manually trying to stop a long running process that causes you to run out of stamina. If you do it at the wrong time during the process it just automatically restarts the process.

This bug happens to me fairly regularly if I try and dissect with a survivor mask on and at low stamina. Something will interrupt me and I'll be stuck trying to fight things while still dissecting.

**Comment by PaulBlay** [comment]
I encountered this bug when dissecting a stack of zombie corpses with 'quick dissect'. 

You can also get some weird behaviour if the game autosaves while you are dissecting and then you reload. Once I ended up fighting zombies when I reloaded and moved quite some distance before suddenly having dissect click back into action (even though the corpses weren't near me any more).
