### ISSUE TITLE
Test/CI builds (intermittently) failing on field, possibly weary tests (unrelated to pull requests)

### ISSUE THREAD

**Issue by actual-nh** [CleverRaven/Cataclysm-DDA#46256]
# Describe the bug

Travis and/or general build-matrix builds for unrelated pull requests are intermittently (?) failing on the weary and/or fields test, with variations on under which compiler/etc combination is involved:
```
../tests/weary_test.cpp:122: FAILED:
  CHECK( info.transition_minutes( 4, 3, 550_minutes ) == Approx( 550 ).margin( 0 ) )
with expansion:
  520 (0x208) == Approx( 550.0 )
with messages:
  
Digging Pits 8 hours, then waiting 8:
  Transition: Weariness from 0 to 1 at 120 minutes
  Transition: Weariness from 1 to 2 at 250 minutes
  Transition: Weariness from 2 to 3 at 360 minutes
  Transition: Weariness from 3 to 4 at 465 minutes
  Transition: Weariness from 4 to 3 at 520 minutes
  Transition: Weariness from 3 to 2 at 640 minutes
  Transition: Weariness from 2 to 3 at 660 minutes
  Transition: Weariness from 3 to 2 at 670 minutes
  Transition: Weariness from 2 to 1 at 875 minutes
  Transition: Weariness from 1 to 2 at 890 minutes
  Transition: Weariness from 2 to 1 at 905 minutes
  Weariness: 1712 Max Exertion: ACTIVE_EXERCISE Mult: 0.8
  BMR: 1708 Intake: 1093 Tracker: 2259 Thresh: 893 At: 1
  Calories: 50444
Log messages during failed test:
12:07:12AM: You eat your holy SPAM of debugging (fresh).
12:07:12AM: You start walking.
0.686 s: Heavy tasks
0.686 s: weary_recovery
1.480 s: 1 day vehicle work
1.481 s: weary_recovery
1.387 s: Waiting 24 hours
1.387 s: weary_24h_tasks
0.834 s: Digging 24 hours
0.834 s: weary_24h_tasks
2.467 s: weather realism
```
Note: 520 instead of 550 is **_quite_** consistent.

And another seen multiple times:
```
../tests/field_test.cpp:44: FAILED:
  CHECK( count_fields( field_type ) == Approx( 8712 ).margin( 200 ) )
with expansion:
  8493 (0x212d) == Approx( 8712.0 )
Log messages during failed test:
12:00:00PM: You're covered in acid!
12:00:00PM: You're covered in acid!
12:00:00PM: The acid burns your legs and feet!
1.359 s: acid_field_expiry_on_map
```
<!--
There may also be a problem with the ranged_balance test, although failures of it are less frequent:
```
../tests/ranged_balance_test.cpp:219: FAILED:
  CHECK( good_stats.avg() > 0.5 )
with expansion:
  0.34375 > 0.5
with messages:
  Normal: [ 24 ]
  Linear: [ 5 2 45 37 ]
  Range: 15
  Max aim speed: 78
  Min aim speed: 0
  good_stats.n() := 128
  good_stats.margin_of_error() := 0.1561331185
``` -->

# Steps To Reproduce

(I have commented out old Weary cases since some may be fixed by #46906.) Already reproduced multiple times (commit tags given to find the right one in multi-commit PRs; generated links are not consistently related):

- #46996 (02c43dd - Fields, Travis)
- #46949 (2638e9e - Fields, general)
- #46934 (7db2c80 - Fields, Travis)
- #46913 (e6afa81 - Fields, Travis)
- #46908 (a9f28bc - Fields, Travis)
- #46837 (baaed94 - Fields, general)
- #46821 (c1ca5a7 - Fields, on Appveyor)
<!-- - #46820 (20589a3 - Weary, Travis) -->
- #46831 (72da9df - Fields, Travis)
<!-- - #46750 (a48274d - Weary, Travis) -->
- #46750 (e693355 - Fields, Travis)
- #46726 (3ddf94a - Fields, Travis)
<!-- - #46681 (1bc9399 - Weary, general)
- #46596 (e2d228b and 0f9e36b - Weary, general)
- #46646 (af6e5a6 - Weary, Travis) -->
- #46554 (ebedbe1 - Fields, general)
- #46549 (85501ed - Fields, Travis)
- #46514 (a32d490 - Fields, general)
- #46426 (c12aaa8 - Fields, Travis)
- #46405 (b512c18 - Fields, Travis)
<!-- - #46388 (8051136 - Weary, Travis)
- #46381 (afe343f - Weary, Travis)
- #46367 (6b9e33d - Weary, general build matrix; not most recent)
- #46366 (c430495 - Weary, general build matrix)
- #46353 (497cc6f - Weary, general build matrix) -->
- #46350 (4c9eb7b - Fields, general build matrix)
- #46329 (8152d40 - Fields, general build matrix)
<!-- - #46329 (8152d40 - Weary, general build matrix)
- #46326 (5b6c1db - Weary, Travis)
- #46304 (1283424 - Weary, general build matrix) -->
- #46299 (493b571, 13dfee2 - Fields, Travis)
<!-- - #46296 (1bbfbb6 - Weary, general build matrix; not most recent) -->
- #46295 (04a5d26 - Fields, Travis)
- #46275 (4b60302 - Fields, Travis)
<!-- - #46272 (15723a4 - Weary, general build matrix) -->
- #46266 (6155b32 - Fields, Travis)
<!-- - #46251 (93b4ca6 - Weary, Travis)
- #46245 (7a3a9cb - Weary, Travis)
- #46241 (5d31a2c - Weary, Travis; not most recent) -->
- #46220 (25b9fd7 - Fields, Travis)
<!-- - #46206 (5ca5abe - Weary, Travis)
- #46204 (bf1e3d9 - Weary, Travis)
- #46200 (a3b8ab0 - Weary, general build matrix; not most recent)
- #46187 (6397884 - Weary, general build matrix)
- #46183 (3a6e3c1 - Weary, Travis) -->
- #46181 (8381e8f - Fields, general build matrix)
- #46156 (eb1a0c8 - Fields, Travis; not most recent)
<!-- - #46079 (d8d3f60 - Weary, Travis)
- #45830 (35b8804 - Weary, Travis)
- #45760 (ec7edff - general build matrix for Weary, -->
- #45760 (ec7edff - Fields, Travis)
<!-- - #45273 (6457a32 - Weary, Travis) -->

# Expected behavior

Consistent test results when no change was made to C++ code or JSON files drawn upon.

# Additional context

Ping: @kevingranade (fields test)

**Comment by Mrzjadacz** [comment]
Also #45760

**Comment by actual-nh** [comment]
> Also #45760

Thanks! I've put it in the list.

**Comment by int-ua** [comment]
This may be alleviated a bit by #46272
Especially if someone will help me limit the general build matrix further. If it's possible.

**Comment by actual-nh** [comment]
That could help with the general build matrix; I suspect the only ones needed to check for this sort of error are ones that could alter arithmetic optimization (e.g., roundoff). A lot of the Travis tests (possibly the majority) are failing on the very first configuration, however - and the tests in question do need to be run (AFAIU) when there are JSON changes, since a lot of what they're checking for uses values from JSON files. OTOH, the statistical tests are going to have some risk of a false positive, and the more you run them, the more likely you are to get a false positive.

**Comment by actual-nh** [comment]
What I now think is an example of a statistical false positive is the archery test fail I've now commented out in the Issue, BTW.

**Comment by actual-nh** [comment]
> Especially if someone will help me limit the general build matrix further. If it's possible.

@int-ua: Is further work needed on that?

**Comment by int-ua** [comment]
Not sure. Should it ignore more than ```
    - 'doc/**'
    - 'lgtm/**'
    - 'tools/**'
``` ?

**Comment by actual-nh** [comment]
I suspect utilities/** also, unless they're running tests of creating/redoing tilesets. Do any of them build the doxygen documentation? If not, doxygen_doc can be ignored. Ditto for object_creator and msvc-object_creator. If android is only tested via the appveyor builds, then that directory could be ignored. They don't seem to currently be building on OSX, so build-data/osx should be ignorable.

**Comment by int-ua** [comment]
You have more insight into that matrix, will you implement the suggested changes?

**Comment by actual-nh** [comment]
I can do the first paragraph, and mention the second paragraph in the PR.

**Comment by actual-nh** [comment]
I've just added to the initial part the observation that the "weary" test failure is very consistent in terms of numbers - 520 instead of the expected 550. Anyone have any idea why? @anothersimulacrum? @I-am-Erk?

**Comment by I-am-Erk** [comment]
I am not sure why the weariness recovery is quicker in that test but it might be reasonable to add an acceptable deviation to those tests.

**Comment by actual-nh** [comment]
It is actually possible that **520** is the correct value, not 550; see #46384.

**Comment by int-ua** [comment]
```
acid_field_expiry_on_map

-------------------------------------------------------------------------------

../tests/field_test.cpp:27

...............................................................................

../tests/field_test.cpp:44: FAILED:

  CHECK( count_fields( field_type ) == Approx( 8712 ).margin( 200 ) )

with expansion:

  8496 (0x2130) == Approx( 8712.0 )
```

**Comment by actual-nh** [comment]
> #46405

Thanks! Have put in.

**Comment by Aivean** [comment]
Regarding the flaky fields test. 

It's filling the whole z-level in acid and waiting "half-life" time (only 2 minutes for acid) to ensure that approximately half of the acid fields had decayed.

The problem is that the `Approx.margin = 200` in the check of the number of alive fields was probably chosen arbitrary, and apparently it's not large enough to account for the variance in the half-life decay.

Our only options here are to try and reduce the variance:
1. run test multiple times and average the results (tests performance will suffer)
2. use field with longer half-life time (also performance hit)
3. use larger margin

Another option would be to seed the rng for the decay process, but I don't think it's a good solution.

**Comment by actual-nh** [comment]
I am going to close this issue, I think; hopefully the two patches (by @anothersimulacrum and @Aivean; thanks very much!) have reduced these down (or possibly even eliminated, in the case of the weary tests). Anything further on weary tests will likely be on #46384 (or others as appropriate). Thanks everyone!
