### ISSUE TITLE
Constant crashes

### ISSUE THREAD

**Issue by Dyuden** [CleverRaven/Cataclysm-DDA#46258]
# Describe the bug

I am looting city, on NW side of me starts gunfire and zombies walking towards it. Game is unplayble because after a while it crashes all the time even if i try to proceed in other direction (If you load save file you can see on W from me book market or library where I willing to go). But also I want to investigate gunfire 

# Steps To Reproduce

Just walk around for a while and you get crash.

# Expected behavior

Game not crashes and I see what the hell happening in the middle of the city at the midnight.

# Screenshots

-

# Versions and configuration

 Please complete the following information; you can now go to:
    - "Main menu (ESC) > Debug Menu > Info > Generate game report" to generate this report.
    - Please update your OS version with a more precise version.

 - OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-7427-g895bbd8 [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
# Additional context

[logs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5731377/logs.zip)

[savefilezipped.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5731387/savefilezipped.zip)

  Sorry if it is a problem that save file in cyrillic name.

**Comment by anothersimulacrum** [comment]
I cannot reproduce a crash.

**Comment by Dyuden** [comment]
Maybe I am missing something with files...If I could read crash report to know what's wrong...
Until this problem resolved I can't play game. Maybe I can somehow check game files or something?

**Comment by anothersimulacrum** [comment]
I tried reading the crash report, unfortunately it is useless.
The most helpful thing would be for you to attach the game to a debugger or something to get a full report of where the crash comes from, but that's complicated and not really something that can happen unless you already know how to do that.

There is some possibility it is windows specific, in which case someone on windows (I am not) could reproduce it, or it may be specific to your system.

How much memory do you have?

**Comment by Dyuden** [comment]
-How much memory do you have?
You mean RAM or drive memory? 16gb and 21,4 gb of free space respectively.
Well looks like I'll have to wait for someone who uses windows. I'll go for bed and hope tomorrow it's resolved itself or someone got solution. See you folks after 16 hours.

**Comment by Dyuden** [comment]
No more replies in a day... My run is doomed

**Comment by actual-nh** [comment]
I'm guessing you've tried a machine reboot?

**Comment by Dyuden** [comment]
Yes. Maybe reinstall game , or verify game files?

**Comment by actual-nh** [comment]
I'd try a reinstall.

**Comment by Dyuden** [comment]
Yeah looks like it worked. I saw that it was autonomouse security turrets shots and game didn't crashed. Thanks.
