### ISSUE TITLE
Is it possible to provide experimental build key store?

### ISSUE THREAD

**Issue by linonetwo** [CleverRaven/Cataclysm-DDA#46250]
# Is your feature request related to a problem? Please describe.

We are trying to build the latest experimental .apk for our QQ group ( chat group similar to Telegram group ), but the .apk we build have different signing to official experimental build, so our friends can't simply install the .apk. ( https://github.com/CleverRaven/Cataclysm-DDA/discussions/46249 )

# Describe the solution you'd like

Do you think it is possible to provide the key that you used in the jenkins CI to us? So we can use it to build the latest apk in our laptop and share it to the QQ group.

<img width="604" alt="截屏2020-12-22 下午6 51 15" src="https://user-images.githubusercontent.com/3746270/102880672-acc79700-4486-11eb-98a4-c5474deb6f6d.png">

# Describe alternatives you've considered
Or make .apk in http://dev.narc.ro/cataclysm/jenkins-latest/Android/Tiles/ be unsigned, so we can simply install our apk on it.

# Additional context
We just want to play the latest version as the Desktop one. The official .apk release is too slow https://github.com/CleverRaven/Cataclysm-DDA/issues/45770

**Comment by ZhilkinSerg** [comment]
You can generate a key and use it for signing. It won't be possible to update existing installation signed with a different key, but you should be able to uninstall existing app and install new version of same app signed with a different key (don't forget to backup user data first - save, config, etc).

**Comment by ZhilkinSerg** [comment]
Unsigned APK is not really an option - you cannot install unsigned apps to most devices, so you would need to sign it by yourself first, but it would be the same outdated APK that is already provided just unsigned.

**Comment by linonetwo** [comment]
Okay, I've updated the post in https://github.com/CleverRaven/Cataclysm-DDA/discussions/46249

It will be annoying that we have to uninstall and reinstall instead of a direct overwrite install, but I think that is the only way.

**Comment by ZhilkinSerg** [comment]
You only have to uninstall it only once - if wanna to install version with a different signing key. Further updates (if you will use same signing key) won't require prior uninstalling and you can update normally.

You can also change `applicationId` in gradle file before doing your local build, so CleverRaven version and your version could be installed side-by-side and won't interfere whatsoever.
