### ISSUE TITLE
 No batch time savings on select recipes

### ISSUE THREAD

**Issue by Narwhal8** [CleverRaven/Cataclysm-DDA#46262]
# Describe the bug

Scrambled eggs, Deluxe Scrambeled eggs and meat/tofu fried rice have no time reduction for batch production

# Steps To Reproduce

1. Look at recipes

# Expected behavior

For Both Egg Scrambles probably should get a discount after 2 batches of %50. The time to make is 6 minutes and you could easily make 4 or more eggs in a pan at a time. Meat fried rice probably 1/2 of 2 or more batches for same reason.

# Versions and configuration

<!-- Please complete the following information; you can now go to:
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by actual-nh** [comment]
This brings to mind that large-scale batch recipes should really require a higher skill (or a separate proficiency, as mentioned in #46206). I can do a simple stir-fry... unless I try to make it bigger by putting too many things in the pan, and it starts going all over the place every time I try to mix it.
