### ISSUE TITLE
Game erroneously reported insufficient charges

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#46265]
# Describe the bug

The game reported that I had insufficient welder charges when I absolutely did not. I had to reactivate the craft in order to make it recognize that I did.

# Steps To Reproduce

I attempted to craft an electric forge.

# Expected behavior

I expected to see no error message.

# Screenshots

![logOutput](https://user-images.githubusercontent.com/13796683/102943027-f0210600-4484-11eb-8118-edf755e14a77.png)
![forgeRecipe](https://user-images.githubusercontent.com/13796683/102943032-f31bf680-4484-11eb-9e0d-10af9a25629e.png)
![chargeTotal](https://user-images.githubusercontent.com/13796683/102943035-f57e5080-4484-11eb-893a-23bfae93ffb7.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 20H2 (build 19042.685)
- Game Version: 0.E-8214-ga69de80 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded:
    - Dark Days Ahead [dda],
    - C.R.I.T Expansion Mod [crt_expansion],
    - No Fungal Monsters [No_Fungi],
    - Disable NPC Needs [no_npc_food],
    - Alternative Map Key [alt_map_key],
    - SpeedyDex [speedydex],
    - Stats Through Kills [stats_through_kills],
    - Stats Through Skills [StatsThroughSkills]

**Comment by PaulBlay** [comment]
I've seen the 'insufficient charges' warning at seemingly random times and not been able to work out what the problem was. I have a mounted vehicle forge and three, full, storage batteries so I don't think running out of battery charge is at all likely.

**Comment by PatrikLundell** [comment]
I've had the issue (0.E2 stable) that the game decided that it should use the tool I had for crafting as one of the tools included in the crafted item, thus failing to have enough power (I think I was trying to use a makeshift arc welder to construct a forge rig out of makeshift arc welders, but it was some time ago, so the memory can't be relied upon). I believe I worked around it by loading one of the intended "component" items with a battery.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
