### ISSUE TITLE
Tailor's Kit Modifying Military Rucksack without materials, producing error and yes modifying, no removing mats

### ISSUE THREAD

**Issue by iamomnivore** [CleverRaven/Cataclysm-DDA#46264]
# Describe the bug

Attempt to Modify [Military Rucksack] item, using [Tailor's Kit] item (loaded with charges), and am given the option to layer on leather. I have the thread but, do not have enough leather (that is clean.) The game displays the option as good to go and I select it, to receive the error I'm reporting but, the game does not crash and the modification is _successfully_ applied to the bag. Additionally, the required materials are not consumed. 

I believe this is occurring because I have a stack of [Filthy] leather, in an adjacent space. The game must be taking a total, adding the 2 clean leather I have and the [Filthy] version but, ultimately disallowing the USE of the [Filthy] version. This error fails to catch (maybe partially) and the function resolves successfully but, whatever materials consumption/removal there is fails to resolve.

Error:
 "DEBUG    : Attempted a recipe with no available components!

 FUNCTION : comp_selection<item_comp> player::select_item_component(const std::vector<item_comp>&, int, inventory&, bool, const std::function<bool(const item&)>&, bool)
 FILE     : src/crafting.cpp
 LINE     : 1529"

# Steps To Reproduce

1. Have clean and dirty leather nearby. Make sure not enough clean leather, to reinforce a Military Rucksack is present but, the total amount of leather present is enough. Ensure enough thread. 
2. Use Tailor's Kit, loaded with thread, to modify a Military Rucksack.
3. Option to reinforce should be available (even though you don't have enough clean leather) and select it. Error occurs. 

# Expected behavior

Expect the modification to return a response indicating I don't have the required materials (or for the option to even be disallowed, as per standard game behavior.)

# Versions and configuration

<!-- Please complete the following information; you can now go to:
    - "Main menu (ESC) > Debug Menu > Info > Generate game report" to generate this report.
    - Please update your OS version with a more precise version.

 - OS: Windows
    - OS Version: 10.0 2009
 - Game Version: 0.E-3 [64-bit]
 - Graphics version: Tiles
 - Ingame language: English US
 - Mods loaded: Enhanced Map Overlay, No NPC Needs

# Additional context

The character in use, at the time of this error, _does_ possess the SQUEAMISH trait.

**Comment by iamomnivore** [comment]
The character in use, at the time of this error, _does_ possess the SQUEAMISH trait.

**Comment by PatrikLundell** [comment]
I've had a somewhat similar check/use mismatch when cooking in 0.E2 stable. When cooking I couldn't make X batches of something, as I didn't have enough (liquid) water, but when crafting a number of batches small enough to use the water in the carried canteen I was given the option to use the frozen water in the luxury RV's tanks.
