### ISSUE TITLE
Bread made with lard

### ISSUE THREAD

**Issue by Svankensen** [CleverRaven/Cataclysm-DDA#46279]
# Is your feature request related to a problem? Please describe.
At least in my country, about half the bread that is sold in cities includes lard as an ingredient. It can also be made with vegetable oil. In rural, isolated areas, people buy veritable buckets of lard (rectangular, 15ish lt container) to make bread for months. It would also give us more uses for animal fat.

# Describe the solution you'd like
A recipe that includes lard/tallow/vegetable oil for more calorie dense bread. IRL the lard/flour proportion is 1/10  by weight. According to wikipedia, the bread is similar to scones, whatever those are. Bread is savory, not sweet tho. 

# Describe alternatives you've considered
Not doing it.

# Additional context
https://en.wikipedia.org/wiki/Hallulla

**Comment by Maleclypse** [comment]
Shouldn't the bread in #46282 have lard as an ingredient?

**Comment by actual-nh** [comment]
Ping: @ToxiClay?

**Comment by ToxiClay** [comment]
> Ping: @ToxiClay?

I....can't find it in the codebase anymore? What?

**Comment by Maleclypse** [comment]
> > Ping: @ToxiClay?
> 
> I....can't find it in the codebase anymore? What?

It’s in the 0.F -dev branch. I think.

**Comment by ToxiClay** [comment]
> > > Ping: @ToxiClay?
> > 
> > 
> > I....can't find it in the codebase anymore? What?
> 
> It’s in the 0.F -dev branch. I think.

Oh, did they switch where the master branch is pointing? That's not confusing. 🙃 Lemme check out the 0.F dev branch I guess, lmao.

**Comment by ToxiClay** [comment]
Success! Now, am I PRing this against `0.F-dev`, because that's where it lives right now?

```
{
    "type": "recipe",
    "activity_level": "LIGHT_EXERCISE",
    "result": "hallula",
    "category": "CC_FOOD",
    "subcategory": "CSC_FOOD_BREAD",
    "skill_used": "cooking",
    "difficulty": 3,
    "charges": 8,
    "time": "30 m",
    "batch_time_factors": [ 50, 5 ],
    "book_learn": [ [ "family_cookbook", 1 ], [ "baking_book", 2 ], [ "cookbook", 2 ] ],
    "qualities": [ { "id": "COOK", "level": 3 } ],
    "tools": [ [ [ "surface_heat", 8, "LIST" ] ] ],
    "components": [
      [ [ "flour", 3 ] ],
      [ [ "yeast", 2 ] ],
      [ [ "sugar", 1 ] ],
      [ [ "salt", 1 ] ],
      [ [ "water", 1 ] ],
      [ [ "any_butter_or_oil", 2, "LIST" ], [ "edible_lard", 1, "LIST" ] ]
    ],
    "//": "I'm not sure whether this should also be rewritten to use a portion of charges, or scaled up so that the smallest component in the recipe becomes a single charge.",
    "//2": "Since milk is only used sparingly in the creation of hallula, to give it a glazed appearance, Cataclysm practicality suggests omitting it."
  }
```

![image](https://user-images.githubusercontent.com/13796683/116794919-ef395a00-aa9e-11eb-8cbc-d7ed0854d98c.png)

**Comment by ToxiClay** [comment]
#48728

**Comment by actual-nh** [comment]
> > It’s in the 0.F -dev branch. I think.
> 
> Oh, did they switch where the master branch is pointing? That's not confusing. 🙃 Lemme check out the 0.F dev branch I guess, lmao.

Not quite. The master branch still has bugfixes and a few updates (e.g., tilesets) happening, but is being prepped to be 0.F. The 0.F-dev branch (which has been intermittently rebased vs the master branch) will be merged with it after 0.F is out.

**Comment by pjf** [comment]
Now that #48728 has been merged, can this issue be closed? :bread:
