### ISSUE TITLE
Clothing tags don't show what freakishly large can't wear.

### ISSUE THREAD

**Issue by WeaverThree** [CleverRaven/Cataclysm-DDA#46271]
# Describe the bug

There are clothes marked (poor fit) or no tag that I can't wear with the freakishly huge mutation. 

# Steps To Reproduce

1. Create a new character
2. Debug on "Freakishly huge" mutation
3. Debug up a unitard
4. Look at Wear menu

# Expected behavior

I expect everything I can't wear because of the mutation to be marked as (too small), most items are.

# Screenshots

![cataclysm-tiles — 2020·12·22 — 14·15·49](https://user-images.githubusercontent.com/1582240/102956739-8d803800-448d-11eb-955d-9ec27a5061ba.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-8371-gef8afe2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
