### ISSUE TITLE
Getting two effects of weariness, and one not decaying

### ISSUE THREAD

**Issue by dico422** [CleverRaven/Cataclysm-DDA#46270]
# Describe the bug

When I open the char's panel, I got two of the same effect in different proportions. Where only one disappear and the other stay on "Extremely Weary".

# Steps To Reproduce

Cant know for sure, but I was experimenting with the Beast Mutation tree, and after some time after getting the achievement for the beast path, I noticed the weary effect was not disappearing. And some time or another,  I was getting the usual weary increasing when doing physical labor, but the other staying on "Extremely".

# Expected behavior

Was expected the Extremely Weary to decay, and not stack with others

# Screenshots

![image](https://user-images.githubusercontent.com/38257342/102986498-af120b80-44ef-11eb-9ab4-d29d1cc41aad.png)

# Versions and configuration

- OS: Windows 10
 - Game Version: 0.E-8333-gf4ad3b9
 - Graphics version: Tiles
 - Ingame language: English22
 - Mods loaded: dda, no_npc_food, package_bionic_professions

**Comment by casswedson** [comment]
Pretty sure weariness decays over time on current master, and having different stages of weariness at the same time was fixed by #44662
