### ISSUE TITLE
Sort Loot not working

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#46277]
# Describe the bug

Invoking the "sort out loot" function is occasionally failing.

# Steps To Reproduce

1. Load attached save.
2. Observe that some loot sits in the unsorted zone.
2. Invoke the "sort loot" function.
3. Observe that some loot will not move, when it should.

# Expected behavior

After fixing the free space issue, I expected the sort function to finish carrying all my loot.

# Screenshots

Observe here my Zone Manager, showing both apartments covered by an Unsorted Loot zone.

Note also that several items have not been moved over, even after issuing a Sort Loot command.

However, even if I drag the loot pile below me into the other room, the Sort Loot command fails to process it. I made sure that both dressers are marked as Source: Firewood, and that sufficient space remains in the right-hand one.
![image](https://user-images.githubusercontent.com/13796683/103026078-1eecba00-4521-11eb-8b43-42d846dcc420.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 20H2 (build 19042.685)
- Game Version: 0.E-8214-ga69de80 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded:
    - Dark Days Ahead [dda],
    - C.R.I.T Expansion Mod [crt_expansion],
    - No Fungal Monsters [No_Fungi],
    - Disable NPC Needs [no_npc_food],
    - Alternative Map Key [alt_map_key],
    - SpeedyDex [speedydex],
    - Stats Through Kills [stats_through_kills],
    - Stats Through Skills [StatsThroughSkills]

# Additional context

It took me a while to pick up on the fact that some of the items were failing to move due to insufficient room on the floor for a couple of zones. Perhaps that can somehow be made more clear during a loot-sort operation.

[LootSorting.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5736626/LootSorting.zip)

**Comment by ToxiClay** [comment]
I think I've figured it out: I'm an idiot.

"Source: Firewood" is not a zone into which the game will _put_ wood; it's only a zone from which the game will _take_ wood when needed. It needs to be paired with one or more "Loot: Wood" zones.

**Comment by int-ua** [comment]
Should it be closed then?

**Comment by ToxiClay** [comment]
Yes, it should. I was leaving it open so that people could quickly find it again and see that I'm a moron.
