### ISSUE TITLE
Samoyed drops mutant meat

### ISSUE THREAD

**Issue by Svankensen** [CleverRaven/Cataclysm-DDA#46285]
Samoyed drops mutant meat when butchered.

# Steps To Reproduce
Kill a samoyed and a mongrel. Mongrel will drop normal meat, samoyed will drop mutant meat.

# Expected behavior

Animals that aren't evidently mutant should drop normal meat.

#Game data

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-8385-g9504d41 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP]
]

**Comment by ZhilkinSerg** [comment]
I cannot reproduce it - both breeds produce regular meat when butchered.

**Comment by Svankensen** [comment]
> I cannot reproduce it - both breeds produce regular meat when butchered.

Yeah, I'm getting strange behaviours from the dogs I picked from a farm where I killed an NPC. Any dog I spawn behaves normally, but the one I adopted there I can't seem to equip armor. It also wasn't healing until I left him out of the reality bubble. Both dogs were really hurt from fighting with zombies, wonder if something got mixed up at some point due to the dogs becoming agressive from me killing their NPC? My character has animal discord for what is worth.

**Comment by actual-nh** [comment]
Savefile?

**Comment by Svankensen** [comment]
Here it is, it happened in the apple orchard, I labeled it "suspect farm".

[Odd dogs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5739486/Odd.dogs.zip)

**Comment by actual-nh** [comment]
Oops - forgot about this (recovering from procedure at the time...). I can try to take a look at the save file, but it may be a bit - lots of other things...

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.E-10390. Opened your save, and assuming the pile of gore to the north-east of you is a butchered samoyed, it has normal,  non-mutant meat.

![изображение](https://user-images.githubusercontent.com/11132525/115100421-8a81e980-9f4d-11eb-8950-848d53067ee8.png)
