### ISSUE TITLE
Can't equip armor on Great Pyrenees

### ISSUE THREAD

**Issue by Svankensen** [CleverRaven/Cataclysm-DDA#46288]
Can't equip Grand pyrenees with armor. (No adecuate item at hand) Other dog breeds seem to work fine except the rotweiler. Considering the armor is tailor-made, it shouldn't matter the size of the dog. If it does matter, the message should be more clear. Spawned another dog of the same breed and all different dog armors just in case my dog in particular was bugged (it wasn't healing while it was in my reality bubble), but it seems to be only related to the breed.

No dog seems capable of equiping the biosilified harness, it says it is too heavy for them.

**Comment by wapcaplet** [comment]
Confirmed in 0.E-8509-g35c0af53e0. Tested with these dog armors:

- leather dog harness (2.15 kg)
- Kevlar dog harness (4.29 kg)
- chitin dog mesh harness (5.36 kg)
- biosilicified chitin dog mesh harness (5.36 kg)

These dog species can wear all of the above armors:
- Chihuahua (2.2 kg): cannot wear any harness: "You don't have the necessary item at hand."
- border collie (16 kg): leather harness OK, but Kevlar and chitin are too heavy
- bulldog (25 kg): Kevlar OK, but chitin is too heavy
- Labrador mutt (30 kg), German Shepherd (35 kg): Can wear biosilicified and regular chitin, kevlar and leather

So far so good - the bigger dogs can wear heavier armors. But sure enough, the biggest dogs of all cannot wear any of the armors, as if they were mere anklebiters:
- Great Pyrenees (52.5 kg), rottweiler (50 kg): Cannot equip any armor: "You don't have the necessary item at hand."

![image](https://user-images.githubusercontent.com/238395/103176874-9e84cc80-4832-11eb-9d0b-d95aee07a71c.png)

**Comment by Svankensen** [comment]
Damn, thanks for doing such a thorough work. Maybe there should be something that tells you what armors dogs can wear? I can totally understand a chihuahua not being able to wear anything, but I imagine it can be frustrating to find out the hard way for some of the larger dogs.
