### ISSUE TITLE
Can't load napalm into napalm?

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#46280]
# Describe the bug

The game says I have no suitable containers for carrying napalm. while trying to unload napalm into a container with napalm in it.

# Steps To Reproduce

1. Load attached save
2. Attempt to `U`nload the jug of napalm into the 3L fuel tank.

# Expected behavior

Expected tank to reload.

# Screenshots

![image](https://user-images.githubusercontent.com/13796683/103037680-6d5a8280-453a-11eb-8d5e-25a15a1ffd6a.png)
![image](https://user-images.githubusercontent.com/13796683/103037692-73506380-453a-11eb-8adb-40a3fa608f2f.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 20H2 (build 19042.685)
- Game Version: 0.E-8388-gb85c4a9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded:
    - Dark Days Ahead [dda],
    - C.R.I.T Expansion Mod [crt_expansion],
    - No Fungal Monsters [No_Fungi],
    - Disable NPC Needs [no_npc_food],
    - Alternative Map Key [alt_map_key],
    - SpeedyDex [speedydex],
    - Stats Through Kills [stats_through_kills],
    - Stats Through Skills [StatsThroughSkills]

**Comment by PaulBlay** [comment]
Well, the 3L tank says it contains 'flammable liquid' not 'napalm'.

**Comment by ToxiClay** [comment]
But if you enter the item description, it does indeed contain napalm. Plus, I've done it before.

**Comment by ToxiClay** [comment]
Check #46261 for a save file where you can verify that.

**Comment by Qrox** [comment]
IIRC the 3L tank is a magazine so you can probably `r`eload it.

**Comment by PaulBlay** [comment]
Okay, two things.

One, this is probably just another expression of this bug
https://github.com/CleverRaven/Cataclysm-DDA/issues/46122

Two, you probably shouldn't be able to reload a pressurised container using a non-pressurised source without specialized equipment. You open it up, cold napalm sprays everywhere, you try frantically to stop it as it splashes all over your clothes and skin while simultaneously somehow pouring more into it from a normal gallon jug. That should be a different bug, though.

**Comment by ToxiClay** [comment]
> I guess I should google "how to make flamethrowers" and end up on every FBI / MI5 watch list.

Lol! Yeah, that sounds about right.

> Two, you probably shouldn't be able to reload a pressurized container using a non-pressurized source without specialized equipment.

I'll grant this, but because I was able to do it and now I'm not, it _feels_ like a regression at the moment.

**Comment by zantanzuken** [comment]
seems to be fixed with the newest version (as far as reloading is concerned) but you cannot 'unload' a fuel from the tanks you have it in into another tank, just reload it.

that said, while it is strange a pressurized tank can be refueled without any specialized tools... anyone wanna make a compressor item specifically for reloading flamethrower tanks/other tanks that have compressed gasses? (i'd imagine that'd be a bit difficult)

**Comment by ToxiClay** [comment]
> seems to be fixed with the newest version (as far as reloading is concerned) but you cannot 'unload' a fuel from the tanks you have it in into another tank, just reload it.
> 
> that said, while it is strange a pressurized tank can be refueled without any specialized tools... anyone wanna make a compressor item specifically for reloading flamethrower tanks/other tanks that have compressed gasses? (i'd imagine that'd be a bit difficult)

I can't `r`eload a tank with another tank (on build 11287); it says I don't have any.

**Comment by zantanzuken** [comment]
yeah, because both the tanks are considered magazines, and therefore loaded, so y'gotta unload the ammo from one to reload it in the other. thats a thing with all weapon magazines

**Comment by PaulBlay** [comment]
So, should this be closed now?

Or are we trying to fix loading magazines from magazines (Can't Load 3L pressurized fuel tank from 3L pressurized fuel tank)?

I mean, everything is going to be a bit weird unless someone fixes things regarding how pressurized tanks are actually refuelled in flamethrowers and implements something closer to reality. Which should probably be a suggestion or go straight to PR do not pass go do not collect 200 price_postapoc.

https://science.howstuffworks.com/flamethrower.htm#pt3

So liquid based flamethrower uses gravity (do not try using while standing on your head) and a flammable pressurized gas (butane or whatever) to push the fuel out. 'Pilot light' is supplied by the same flammable pressurized gas. Butane is not refillable without specialist equipment, but new canisters should be readily available from hardware stores and/or on camp sites (gas fired barbeque, heating). You lose some butane each time you turn off the gas supply and open up the liquid tank but I wouldn't bother coding that. Flamethrowers now need two different things tracked - gas and liquid.

**Comment by zantanzuken** [comment]
i mean... if you wanted to create a 'loading system' for the napalm canisters, i guess you could just not have them refillable at all unless they're completely empty, and then 'craft' a full one using the amount of flamethrower fuel you need plus a single canister of butane

... that'd be an easy fix but it wouldn't mesh at all with how current weapon magazines work.... kevin's doing stuff with that right now so putting that on the backburner (so to speak.)

**Comment by DalenTalas** [comment]
@PaulBlay 
> [y]ou probably shouldn't be able to reload a pressurized container using a non-pressurized source without specialized equipment.

> My guess without googling is that the tank that contains the napalm actually has some sort of piston that is pushed along inside it by a disposable safe pressurant like nitrogen gas, maybe?

Not a piston, the fuel tank is pressurized by propellant gas, usually stored in a separate bottle. So the issue you are describing have been solved as far back as WWII. I know for a fact that Soviet ROKS flamethrowers have been refueled in the field with fuel made on the spot, with the recipe adjusted based on the environmental conditions. And, AFAIK, the propellant bottle can simply contain air pressurized with a hand pump. Furthermore, at least the ROKS used pyrotechnic charges in a revolver drum to ignite the fuel.

So yeah, (WWII) flamethrowers were simpler to reload than you may think. At the same time, the simulation has some (acceptable) breaks from reality.

See here:
https://en.wikipedia.org/wiki/M1_flamethrower
https://world-war-2.wikia.org/wiki/ROKS-2_Flamethrower
https://www.wikiwand.com/en/ROKS_flamethrowers
https://guns.fandom.com/wiki/LPO-50 (uses an explosive charge to propel the fuel, and electric ignition)

**Comment by ToxiClay** [comment]
> Not a piston, the fuel tank is pressurized by propellant gas, usually stored in a separate bottle.

So it's the deadliest bottle of whipped cream ever. 🙃 

> ...so putting that on the backburner (so to speak.)

I see what you did there.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
