### ISSUE TITLE
dissoluted devourer  breaks mission

### ISSUE THREAD

**Issue by OliveChukar** [CleverRaven/Cataclysm-DDA#46283]
# Describe the bug
A dissoluted devourer can fuse with the target of the kill mom mission making the mission impossible to finish.

# Steps To Reproduce
1. Spawn NPCs and ask them for missions until you get KILL_ZOMBIE_MOM.
2.  Go to target location.
3. Spawn dissoluted devourer near the mission target zombie.
4.  Wait for the mission target to fuse with the dissoluted devourer.
5.  Kill the dissoluted devourer. the mission status will not change.
6.  Return to the NPC. It will not let you complete the mission.

# Expected behavior
Either the target zombie fuseing with the dissoluted devourer should finish the killing step of the mission or killing the dissoluted devourer should.
Letting random monster interactions make quests impossible to finish seems frustrating.

# Screenshots

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-8383-g96f400e
 - Graphics version: Tiles 
 - Ingame language:  english
 - Mods loaded: dda core content pack only

# Additional context
I think I have had the same issue with the zombie master in the KILL_HORDE_MASTER mission but that one seems more difficult to replicate. This problem probably affects any mission with a target that needs to be killed and can fuse with a dissoluted devourer.

**Comment by Qrox** [comment]
`monster::die` returns too early if `death_drops` is false so `mission::on_creature_death` does not get called.
