### ISSUE TITLE
Vehicle interface displays misleading fill percentages when other vehicles are racked

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#46298]
# Describe the bug

My car's electric battery isn't gaining charge the way it feels like it should.

# Steps To Reproduce

1. Load the attached save.
2. Note that the battery charge is at 68%, and nothing is draining power.
3. Wait for six hours.
4. Note that the battery charge is _still_ 68%.

# Expected behavior

I expected to see my battery levels rise.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 20H2 (build 19042.685)
- Game Version: 0.E-8388-gb85c4a9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded:
    - Dark Days Ahead [dda],
    - C.R.I.T Expansion Mod [crt_expansion],
    - No Fungal Monsters [No_Fungi],
    - Disable NPC Needs [no_npc_food],
    - Alternative Map Key [alt_map_key],
    - SpeedyDex [speedydex],
    - Stats Through Kills [stats_through_kills],
    - Stats Through Skills [StatsThroughSkills]

# Additional context

[Woodcock.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5740280/Woodcock.zip)

**Comment by PaulBlay** [comment]
What's supplying the power - alternator with the engine running, solar panels?

**Comment by ToxiClay** [comment]
> What's supplying the power - alternator with the engine running, solar panels?

Solar panels. Conditions are bright, and remained bright during the entire time I was waiting.

**Comment by PaulBlay** [comment]
Your batteries are already 100% charged. 

I think what may be happening here is that the storage battery in the bike is being included in the 'how much charge can this vehicle hold' thing but not included in 'how much charge does this vehicle have'. That is because bikes loaded in bike racks are have their vehicle component 'disabled'. 

I unloaded your bike and BAM 100%

**Comment by ToxiClay** [comment]
> I think what may be happening here is that the storage battery in the bike is being included in the 'how much charge can this vehicle hold' thing but not included in 'how much charge does this vehicle have'. That is because bikes loaded in bike racks have their vehicle component 'disabled'.

Ohhhhhhh. That makes a good deal of sense, but it's also worthy of someone fixing it up. That's a little beyond my abilities, though.

> P.S. Repair your solar panels!

I want to! I need more solar cells!

I also want to reinforce them....and replace the steel plating with military composite...

**Comment by PaulBlay** [comment]
Maybe the title of this should be changed?

"Misleading fill% display on sidebar when bike loaded on rack"

I think you get the same problem for gasoline when there is a fuel tank on your bike as well, right?

**Comment by ToxiClay** [comment]
> Maybe the title of this should be changed?
> 
> "Misleading fill% display on sidebar when bike loaded on rack"
> 
> I think you get the same problem for gasoline when there is a fuel tank on your bike as well, right?

I would imagine so -- I've never tried, since the only thing i use liquid fuel for is my power grid.
