### ISSUE TITLE
Zinc from zinc powder for disposable battery crafting

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#46309]
# Is your feature request related to a problem? Please describe.

The disposable battery recipes require zinc. One obvious source of zinc is zinc powder, but there is no way to craft zinc from zinc powder. 

# Describe the solution you'd like

Add a crafting recipe for zinc from zinc powder. I think something like the following:

Zinc

Primary skill: fabrication (2)
Other skills: none
Proficiencies: Principles of Metalworking
Time to complete: 15 minutes
Batch time savings: 90% at >4 units
Dark craftable? Impossible

Tools required:
* electric forge (10 charges)
* crucible or clay crucible

Components required: 
* zinc powder (1150)

Recipe learned from:
ICSC (International Chemical Safety Cards)

# Describe alternatives you've considered

Allow crafting recipes for disposable batteries to use zinc powder instead of zinc. I don't even know how that zinc is being used in there, so I can't say if this is stupid or genius.

# Additional context

Zinc melts at 419.5 C, this is quite low and easily reached by forges or might even be managed by a pan on a stove top. However 460 C is the 'auto ignition' temperature, and you do not want to reach that.

The crafting method for zinc from zincite should probably have "coal (1) or charcoal (2)" instead of just "coal (1)".

[EDIT] Changed recipe based on discussion below. 1150 zinc powder (1.66 lbs) allows for a bit more 'loss' from oxidize slag, etc. The recipe produces 100 zinc (1.54 lbs). Note: Ideally, you should have a thermocouple - either integrated to the electric forge crafting recipe, or as a required tool.

I would like to restrict to electric forge for the (presumed) improved temperature control, but I don't actually know how to specify that in the recipe.

**Comment by PaulBlay** [comment]
I tried experimenting with this. I honestly don't know why the following code produces 100 zinc instead of 1, but 100 zinc is 1.54 lbs and 1100 zinc powder is 1.59 lbs so the maths is about right (I presume there is a little wastage in the process). I think it belongs in the 'materials.json'.

```
  {
    "result": "zinc_metal",
    "type": "recipe",
    "activity_level": "ACTIVE_EXERCISE",
    "category": "CC_OTHER",
    "subcategory": "CSC_OTHER_MATERIALS",
    "skill_used": "fabrication",
    "difficulty": 2,
    "time": "15 m",
    "batch_time_factors": [ 90, 4 ],
    "autolearn": true,
    "using": [ [ "forging_standard", 1 ] ],
    "proficiencies": [ { "proficiency": "prof_metalworking" }],
    "tools": [ [ [ "crucible", -1 ], [ "crucible_clay", -1 ] ] ],
    "components": [ [ [ "chem_zinc_powder", 1100 ] ] ]
  },
```

**Comment by Svankensen** [comment]
The melting temperature of zinc is about 450 °C, well within the reach of a normal campfire. It is however also it's oxidation temperature, which would surely cause some waste. These papers seem to indicate the oxidation rate is quite low tho, so it seems to be quite feasible even without a forge or crucible.

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4671534/
https://nvlpubs.nist.gov/nistpubs/jres/28/jresv28n5p593_A1b.pdf

**Comment by PaulBlay** [comment]
> The melting temperature of zinc is about 450 °C,

419.5, as I said.

> It is however also it's oxidation temperature, which would surely cause some waste.

Ah, that's a rather bigger potential problem than you make it out to be. The question isn't so much 'how much zinc will be lost to oxidization' as 'will the zinc powder burn to dust in a blinding fire'. The auto-ignition point is, apparently, 460 C. So, yeah, you probably can melt it down but careful temperature control would be a must, I guess. No throwing it on a campfire unless you want to potentially get blinded and have your camp burn down.

**Comment by Svankensen** [comment]
Right, it is powder we are talking about! I forgot that "detail". I just thought of molten metal surface oxidation.

So, thermometer and hot plate/electric forge? Cause a charcoal forge seems like asking for trouble, unless they naturally deplete most oxygen from air. And that would be a beefy thermometer. A vacuum pump could work.

Also, found this report on a zinc powder explosion. It seems to be very rare, from what is shared here.

http://www.saimm.co.za/Conferences/BM2005/087-96_VanNiekerk.pdf

**Comment by PaulBlay** [comment]
OK, so this ended up being a bit more involved than I expected. @Svankensen Are you interested in writing up a suggestion for the book? It seems like it would be a nice addition. A book on all the ways to accidentally kill yourself (or, in CDDA, deliberately kill something else). Otherwise I could try to wrangle something together myself in a few days.

P.S. Happy Christmas! (OK, I'm late).

**Comment by Svankensen** [comment]
Hmm, will give it a spin and look at the other applied sciences/fabrication recipes and see what could be gleaned from solid first principles and raw data. This is my discord username too, I will be needing some aid.
