### ISSUE TITLE
Vanilla format Tileset files throw errors ONLY when mod_tileset/compatibility/tiles-new appear more than once

### ISSUE THREAD

**Issue by MutaMan** [CleverRaven/Cataclysm-DDA#46305]
Describe the bug:
In mod_tileset.json files that use the core game format, the game throws JSON errors when "mod_tileset"/"compatibility"/"tiles-new" lines appear more than once in these files, the issue does not appear when the mod_tileset.json file consists of "mod_tileset"/"compatibility"/"tiles-new" lines that appear ONLY once throughout the entire file

Steps to reproduce:
1. Create a test mod folder, put a mod_tileset.json file inside of it and fill in the "mod_tileset"/"compatibility"/"tiles-new" JSON lines according to the core game mod_tileset.json format with any tilesets;
2. Launch the game and wait until the loading reaches Tileset;
3. The game throws 0 errors - everything works as intended;
4. Now add second, third, etc "mod_tileset"/"compatibility"/"tiles-new" JSON lines to your existing mod_tileset.json in the test mod folder;
5. Launch the game and wait until the loading reaches Tileset - the game is throwing errors now 

Expected behavior:

The game does not throw errors when there are more than one "mod_tileset"/"compatibility"/tiles-new" JSON lines - just like in the case when when it contains one of each lines
Versions and configuration:
- OS: Windows
- OS Version: 10.0 2009
- Game Version: 0.E-8446-ga4d28d9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Test [test]
]

Additional Context: 

Here are the errors:
```
03:22:27.167 ERROR : src/json.cpp:120 [void JsonObject::report_unvisited() const] (json-error)
Json error: <unknown source file>:4:21: Failed to visit member compatibility in JsonObject

  {
    "type": "mod_tileset",
    "compatibility":
                    ^
                     [
      "Chibi_Ultica",
      "UltimateCataclysm",
```
```
03:22:30.904 ERROR : src/json.cpp:120 [void JsonObject::report_unvisited() const] (json-error)
Json error: <unknown source file>:16:17: Failed to visit member tiles-new in JsonObject

      "MXplus12_for_cosmetics"
    ],
    "tiles-new":
                ^
                 [
      {
        "file": "mod_tileset/test_normal.png",

**Comment by ZhilkinSerg** [comment]
Why do you want to add these lines?

**Comment by actual-nh** [comment]
> Why do you want to add these lines?

Did you take a look at the @chaosvolt commit referenced above?

**Comment by anothersimulacrum** [comment]
That commit doesn't do anything referenced in this issue. If they're having issue with other things, they should report that.

**Comment by kevingranade** [comment]
Do not open proxy issues for people banned from the project.

**Comment by ZhilkinSerg** [comment]
> > Why do you want to add these lines?
> 
> From the @chaosvolt commit referenced above, they're having problems with mod tilesets using multiple image files, different sprite sizes, and offsets.

All I could see there is some rant.
