### ISSUE TITLE
Strange behavior with loot sorting after 46159

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#46301]
PR #46159 introduced strange behavior, and is an incomplete fix.

# Steps To Reproduce

1. Load attached save
2. Open Zone Manager.
3. Use the +/- keys.
4. Observe that the displayed order is not changing.
5. Also observe that when closing the manager, the game asks you if you want to save changes. Something has changed; it's simply not being displayed.

# Expected behavior

After the PR, I expected to be shown the order changing.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 20H2 (build 19042.685)
- Game Version: 0.E-8388-gb85c4a9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded:
    - Dark Days Ahead [dda],
    - C.R.I.T Expansion Mod [crt_expansion],
    - No Fungal Monsters [No_Fungi],
    - Disable NPC Needs [no_npc_food],
    - Alternative Map Key [alt_map_key],
    - SpeedyDex [speedydex],
    - Stats Through Kills [stats_through_kills],
    - Stats Through Skills [StatsThroughSkills]

# Additional context

[Woodcock.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5740376/Woodcock.zip)

**Comment by ToxiClay** [comment]
Addendum: I can manually adjust the order if they're named exactly the same (see the two zones labeled "Armor"), but if they're not, I can't.

**Comment by wapcaplet** [comment]
#46159 did nothing but revert part of #46054 so I don't see how it could have introduced a new bug that wasn't there before. Could you try a build from before my earlier PR and see if it has the same behavior? I think commit 49aca58b should be just before it was merged.

**Comment by olanti-p** [comment]
@ToxiClay The version in your report (b85c4a9) came out before #46159 was merged (e4d047a5b5a917abfc4fd70a5e7cd26518b076ec), it was still affected by #46158.

**Comment by anothersimulacrum** [comment]
Closing without a new confirmation.
