### ISSUE TITLE
Scuba tanks not working and suggested fix

### ISSUE THREAD

**Issue by acepleiades** [CleverRaven/Cataclysm-DDA#46303]
# Describe the bug
Scuba tanks don't work

# Steps To Reproduce

- Acquire scuba tank or small scuba tank (they do spawn naturally in the game);
- Activate it;
- Error pops up and it turns into undefined-scuba_t and undefined-small_scuba_t.

The error:
 DEBUG    : Missing item definition: scuba_t

 FUNCTION : const itype* Item_factory::find_template(const itype_id&) const
 FILE     : src/item_factory.cpp
 LINE     : 1521

# Expected behavior

They should work

Active scuba tank exists and you can spawn it through the debug menu, but it appears the inactive tank is not turning into the active one. The active turns into inactive correctly when activated

# Versions and configuration

- OS: Windows 10
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-8446-ga4d28d9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Monsters [Only_Wildlife]
]

# Additional context

I also believe the scuba tanks should replace rebreather masks. Some relevant discussion: https://discord.com/channels/598523535169945603/598614717799596055/785301278015094855

Rebreather masks don't work realistically. Currently, they are masks with filters made out of oxidizer powder and charcoal/coal that recycle exhaled oxygen. Real-life rebreather systems do recycle exhaled oxygen but are used with oxygen tanks and not a single filter cartridge (I can't confirm if they even use filter cartridges and whether or not they're made out of oxidizer and charcoal/coal). 
Rebreather masks don't seem to spawn anywhere in the game (except for rebreather filter cartridges, because they have a frequency value of 2 in the Ultica Tileset Sprites Progress Tracker) so I suggest simply disabling the recipes for them. These are the IDs for rebreather masks, rebreather mask cartridge, and "survivor divemasks":
- rebreather
- rebreather_on
- rebreather_xl
- rebreather_xl_on
- rebreather_filter
- mask_h20_survivor
- mask_h20_survivor_on
- mask_h20_survivorxl
- mask_h20_survivorxl_on

Additionally, the diving gear in-game seems to be missing glasses. Here's a relevant remark: https://discord.com/channels/598523535169945603/598614717799596055/791430327444439080

My suggestion is for eye coverage to be added to activated scuba tanks. A neat detail is that they currently add mouth coverage when activated. Either that or a "diving mask" item to be added into the game.

**Comment by int-ua** [comment]
Confirming.

**Comment by acepleiades** [comment]
Proposed sprite for scuba with eye coverage
![scubaman](https://user-images.githubusercontent.com/69649956/103110969-89d3e900-4626-11eb-9acb-2a3f7f58b972.png)
