### ISSUE TITLE
More location mod is not loaded

### ISSUE THREAD

**Issue by linonetwo** [CleverRaven/Cataclysm-DDA#46315]
# Describe the bug

It is now shown in the mod list when creating a new world.

# Steps To Reproduce

1. Creaate a new world
2. See available mod list

or

1. add more location mod to existing save mods.json
2. it will say json error when loading the save

# Expected behavior

No JSON error

# Versions and configuration

Cataclysm-DDA experimental build #11292

Timestamp: 2020-12-24 19:47:51 UTC

    cataclysmdda-0.E-OSX-Tiles-b11292.dmg

**Comment by ZhilkinSerg** [comment]
This mod is obsolete - do not expect too much support for it.

**Comment by actual-nh** [comment]
What is the JSON error? (And are all the locations already in the game, or what? Lack of an active curator for the mod?)

**Comment by linonetwo** [comment]
```log
(continued from above) ERROR : src/json.cpp:120 [void JsonObject::report_unvisited() const] (json-error)
Json error: data/mods//More_Locations/tpalettes.json:470:53: Failed to visit member damage in JsonObject

    "id": "tri_tower_stuff",
    "items": {
      " ": { "item": "trash", "chance": 1, "damage":
                                                    ^
                                                     [ 0, 2 ] },
      ".": [
        { "item": "trash", "chance": 1, "damage": [ 0, 2 ] },

22:50:20.493 : Log shutdown.
```

Looks somehow similar to https://github.com/CleverRaven/Cataclysm-DDA/issues/46216  , maybe this is duplicated.

**Comment by PaulBlay** [comment]
Ah, my limited understanding of the situation is that the mod probably wasn't working before but you only started to notice because recently (Dec 18?) a change was made to catch and report more errors that were previously not displayed. 

Is it (was it) a good mod? Because you might be able to get a third party interested in patching it up (like the numerous mods maintained in Goats Mod Compilation
https://github.com/TheGoatGod/Goats-Mod-Compilation

**Comment by Maleclypse** [comment]
Much of this mod has been or is in process of being mainlined.

**Comment by PaulBlay** [comment]
Huh, it actually already is one of the ones in TheGoatGod's Goats-Mod-Compilation. Last updated in October.
https://github.com/TheGoatGod/Goats-Mod-Compilation/tree/Experimental-Mod-Pack/data/Mainline_mods/Mods/More_Locations

You could post an issue on his github
https://github.com/TheGoatGod/Goats-Mod-Compilation/issues
