### ISSUE TITLE
Ghee should not set off lactose intolerance

### ISSUE THREAD

**Issue by Xailiax** [CleverRaven/Cataclysm-DDA#46321]
Simple really, game even says it's "free from milk solids..."

It should not be flagged as "milk" after the process is complete.

That while the Wikipedia article for "Clarified Butter" is not a primary source, it says the following:

"....It has negligible amounts of lactose and casein and is, therefore, acceptable to most who have a lactose intolerance or milk allergy...."

As a moderately lactose intolerant person, butter is of little consequence, and ghee is of no objection whatsoever. Thus: Alternatively, perhaps make it suffer a greatly reduced lactose penalty?

**Comment by Aiden-Koorsen** [comment]
So you want me to go and remove the lactose intolerance in the food item Ghee?

**Comment by Xailiax** [comment]
Actually, if you could, that would be great.

The alternative would be that we're looking more like "full on lactose
allergy to a goofy extent" otherwise a bunch of other items like bread and
chocolate and such would also fit the bill, which would be silly, but
consistent.
