### ISSUE TITLE
A leather backpack worth of leather can only craft a single leather pouch.

### ISSUE THREAD

**Issue by NeviNovat** [CleverRaven/Cataclysm-DDA#46324]
# Describe the bug

Leather pouches take 7 leather patches to craft, but only hold 1.5L. Now leather _**backpacks**_ take 10 leather patches to craft and can hold 25L.
So one crafting recipe or the other is not right.

# Steps To Reproduce

1. Use debug menu to give yourself all recipes.
2. Compare the recipes.
3. (Optional) Cut a leather backpack and see you can only craft 1 leather pouch.

# Expected behavior

For a backpack worth of leather to be able to craft at least 4 leather pouches?

# Screenshots
Pouch:
![image](https://user-images.githubusercontent.com/51816321/103141828-ba895080-4702-11eb-957c-cdfd4d9d862e.png)
Backpack:
![image](https://user-images.githubusercontent.com/51816321/103141825-a9d8da80-4702-11eb-90c9-b5a7e094ef5b.png)

# Versions and configuration

 - OS: Windows 10
 - Game Version: build 11265
 - Graphics version: Tiles
 - Mods loaded: only CDDA base

# Additional context

There are probably other inconsistencies like this. IDK what a "leather patch" is supposed to be and I don't have time search for that right now that's why this is not a PR. If you know how much each item should have you can tell here then others will have an easy way to fix this.

**Comment by kevingranade** [comment]
Yes there are inconsistencies, reporting them without an associated fix isn't helpful.

Feel free to open a PR increasing the backpack recipe requirements.
