### ISSUE TITLE
Metabolic CBM and weariness.

### ISSUE THREAD

**Issue by Zigoos** [CleverRaven/Cataclysm-DDA#46322]
**# Describe the bug** 

CBM Metabolic Interchange causes a "weariness" effect even when you are asleep. I noticed this because of turning on the auto-charge at night.

**# Steps To Reproduce**

1. Enable Metabolic Interchange.
2. Done. You weariness.

**# Expected behavior**

CBMs should not cause weariness.

**# Versions and configuration**

Win7
0.E-8428-g3d13801
DDA only

**Comment by Fris0uman** [comment]
Burning calories cause weariness, MI burns calories so it causes weariness.

**Comment by Svankensen** [comment]
> Burning calories cause weariness, MI burns calories so it causes weariness.

Yeah, but that is an artifact of the system. Metabolic fatigue happens because of the expenditure of localized energy stores and accumulation of metabolites in the **muscles**. There's no need for metabolic interchange to pull calories from the muscles themselves.

**Comment by actual-nh** [comment]
> Yeah, but that is an artifact of the system. Metabolic fatigue happens because of the expenditure of localized energy stores and accumulation of metabolites in the **muscles**. There's no need for metabolic interchange to pull calories from the muscles themselves.

It could be pulling glucose from the bloodstream, which may come from broken-down liver glycogen. (This can't happen with muscles - their glycogen is solely for use by that muscle.) However, this could also stimulate the liver to build up more glycogen stores when it could.

**Comment by kevingranade** [comment]
The exact functioning of the MI CBM is a mystery, but fatigue is a reasonable side effect.
