### ISSUE TITLE
Firearm CTH display can be misleading

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#46333]
# Describe the bug

While standing on a roof and aiming at an enemy right next to the building, 100% CTH is displayed, but no shot connects.

# Steps To Reproduce

1. Load attached save.
2. Invoke `f`ire menu.
3. Observe listed 100% chance to hit.
4. Take the shot.
5. Observe no result.

# Expected behavior

I expected to blow the enemy to kingdom come.

# Screenshots

![image](https://user-images.githubusercontent.com/13796683/103145423-333edb80-4708-11eb-9f3d-bec70fb82e47.png)

![image](https://user-images.githubusercontent.com/13796683/103145421-27531980-4708-11eb-9f71-8d9c159fe82e.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 20H2 (build 19042.685)
- Game Version: 0.E-8388-gb85c4a9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded:
    - Dark Days Ahead [dda],
    - C.R.I.T Expansion Mod [crt_expansion],
    - No Fungal Monsters [No_Fungi],
    - Disable NPC Needs [no_npc_food],
    - Alternative Map Key [alt_map_key],
    - SpeedyDex [speedydex],
    - Stats Through Kills [stats_through_kills],
    - Stats Through Skills [StatsThroughSkills]

# Additional context

[Woodcock.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5742686/Woodcock.zip)

**Comment by PaulBlay** [comment]
Yeah, you're shooting through the roof there. Sometimes it will show your line of fire going through the corner of a wall. What does the CTH display show then?

**Comment by int-ua** [comment]
AFAIU path take by the projectile do no always match the line perfectly as there is always _some_ spread in accuracy. Does it fail 100% of the time if you try shooting a lot of times?

**Comment by ToxiClay** [comment]
Yeah, it failed 100% of the time.

**Comment by Mrzjadacz** [comment]
A sidenote:
The same happens while throwing grenades/casting spells at something below & one tile away, to be exact
__Projectiles hit the tile you're on__

**Comment by actual-nh** [comment]
> One could possibly check this by using spell/attack that ignores walls/surfaces?

Try the Magus Magic Missile spell (has the `NO_PROJECTILE` flag).

**Comment by Cyprex** [comment]
Without any z-level stuff you can sometimes <tab> to select targets that actually have a wall in the way.

**Comment by PaulBlay** [comment]
@Cyprex 

> Without any z-level stuff you can sometimes to select targets that actually have a wall in the way.

Yeah, I was going to say something like that. Then I actually tried firing (burst mode) at a target that supposedly had a corner wall in the way and it got shot up nicely. Which is what int-ua was talking about ...

> AFAIU path taken by the projectile [does] not always matches the line perfectly as there is always some spread in accuracy. 
> Does it fail 100% of the time if you try shooting a lot of times?

**Comment by Night-Pryanik** [comment]
I think this is fixed by #52386. Closing until reconfirmed.
