### ISSUE TITLE
inserting too many items into toolbox produces an error; wood saw cannot be added to toolboxes

### ISSUE THREAD

**Issue by misterprimus** [CleverRaven/Cataclysm-DDA#46334]
# Describe the bug
inserting too many items into toolbox produces an error; wood saw cannot be added to toolboxes
# Steps To Reproduce
1. Make a player with a toolbox, some tools, and a wood saw.
2. Try to put as much stuff as possible into the toolbox.
3. Get error and don't even get the option to add wood saw to the toolbox.
# Expected behavior
No debug error.
# Versions and configuration
 - OS: Win7x64
 - Game Version: 0.E-8469-ga94a537
 - Graphics version: tiles
 - Ingame language: Eng
 - Mods loaded: Disable NPC needs
# Additional context
Perhaps a way to solve this is to have the insert menu:
1. Exclude all items with a longest side that does not fit into the selected container.
2. Show a ratio displaying the total volume of items selected (x) / remaining volume in the container (y).
3. Display a msgbox type "error" (not the debug error) if x > y instead of proceeding with the insertion of the items into the box.

**Comment by StStep** [comment]
I was about to make this issue but I see it's already here. I would recommend making it more generic, I see this when using the insert menu for any container if you try and add too much to it. I second doing some kind of real-time calc of what can fit if possible, like what exists with the get menu.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-11021.
