### ISSUE TITLE
Military pants cannot be fitted

### ISSUE THREAD

**Issue by FlyIN11** [CleverRaven/Cataclysm-DDA#46348]
0.f3a1933

It is not possible to wear non-woven leg gear such as military trousers and knee pads while having a tail

**Comment by actual-nh** [comment]
Well, without tailoring, that's reasonable for the trousers. I had thought the knee pads were already fixed; see #45898 - it went in ~9 days ago.

**Comment by DalenTalas** [comment]
I'll just say that the furry community has done extensive research on designing lower body garments that accommodate tails. And they do, in general, appear to require significant alterations to the standard humanoid pattern.

I will leave the search for references as an exercise to the reader. :)

**Comment by int-ua** [comment]
Please include mutation info in the title to better reflect the problem. Did you remove the provided issue template before writing the description?
