### ISSUE TITLE
Acidic zombie dog and blistered horror drop human meat not zombie meat.

### ISSUE THREAD

**Issue by NeviNovat** [CleverRaven/Cataclysm-DDA#46341]
# Describe the bug

Acidic zombie dog and blistered horror (the upgraded version of the acidic zombie dog) drops human meat/fat/bone/stomach when butchered.

# Steps To Reproduce

1) Debug an acidic zombie dog/blistered horror.
2) Kill it with the debug menu (or any other way).
3) Butcher/dismember the acidic zombie dog/blistered horror.

# Expected behavior

For the zombie mops to drop normal zombie meat/stuff?

# Screenshots
Acidic zombie dog:
![image](https://user-images.githubusercontent.com/51816321/103158380-be31db80-47c5-11eb-912c-2be074045e5d.png)
![image](https://user-images.githubusercontent.com/51816321/103158360-85920200-47c5-11eb-8a1d-420700bedff1.png)
Blistered horror:
![image](https://user-images.githubusercontent.com/51816321/103158427-647de100-47c6-11eb-8fe8-c8ddb32db7b5.png)

Here is the control, this is a _**normal zombie dog**_:
![image](https://user-images.githubusercontent.com/51816321/103158461-c2aac400-47c6-11eb-9a25-afb8d37a0b00.png)

# Versions and configuration

 - OS: Windows 10 
 - Game Version: build 11265 
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: just CDDA game base

# Additional context

Here is the PR that added them: "Content: Acidic zombie dog evolution line #45271"

**Comment by Saicchi** [comment]
Oops. Can't believe I forgot to add that, sorry.
