### ISSUE TITLE
Suddenly keyboard input stops working (Windows IME UI problem).

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#46356]
# Describe the bug

From time to time keyboard input in CDDA almost entirely stops working.

# Steps To Reproduce

1. Be a Windows PC user
2. Have a language pack installed that uses the IME (Input Method Editor). Chinese, Japanese, probably Arabic, etc.
3. While playing, accidentally switch the IME away from standard ascii characters. [ALT]+[CAPS LOCK] does this by default, but there are other methods.
4. Be confused when nothing you type does what it should without any visible warning as to what's going on.

# Suggested behaviour

Would it be possible to either have input mode forced to plain ascii for the general gameplay but allow other input modes when entering free text? (filters, searches and setting names). Additionally would it be possible to show the current text input mode as a sidebar content option? I honestly don't know. The guys who work on and fix translations might.

It is possible to disable the IME entirely for specific applications when you program them. But that would mess things up for people playing in other languages. 

I tried playing in Japanese and it's a bit of a nightmare. Whenever you want to enter text (filter, search, setting names, etc.) you have to be in one mode but then none of the keys to control the game actually work until you switch back to the plain ascii input mode. I suppose you get used to it.

# Versions and configuration

- OS: Windows: Windows x64 8.1
- Game Version: 0.E-8307-g3628f8c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Blaze Industries [blazeindustries]
]

# Additional context

NOTE! Windows users with IME - typing [ESC] then \\ (backslash twice) will (probably) fix this until you next accidentally activate the IME.

**Comment by Qrox** [comment]
We have an experimental keycode mode in the interface settings that bypasses the IME and keypad in non text input UIs. It currently only supports qwerty keyboard though, so you can try it out if you're using qwerty.

**Comment by PaulBlay** [comment]
@Qrox nice! Thanks for pointing that out. I shall have to try it out.

**Comment by PaulBlay** [comment]
Okay, the experimental keycode mode works just fine so far. You can bump this down the priority list a bunch. 

It might be nice to have some sort of 'Keyboard input trouble? Have you tried Options -> Interface -> Keycode mode' prompt show up the first time someone gets a ton of unrecognized input in a row during a game session.
