### ISSUE TITLE
Aero-Evaporator CBM is misnamed

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#46351]
# Describe the bug

The Aero-Evaporator CBM is a bionic device that condenses vapour from the air and injects it as water into your blood stream. Evaporation is the process of liquid turning into vapour, what the Aero-Evaporator does is the exact opposite. 

# Steps To Reproduce

1. Check CBM name in game.
2. Consult a dictionary.

# Suggested action

Rename to "Atmospheric Water CBM" or "Atmospheric Water Generator CBM"

# Versions and configuration

- OS: Windows x64 8.1
- Game Version: 0.E-8307-g3628f8c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Blaze Industries [blazeindustries]
]

# Additional context

Alternative: I could just admit that sometimes things have stupid names and not let it bug me.

**Comment by Dekker3D** [comment]
Aero-condensator? That way, people will still recognize it easily.

**Comment by PaulBlay** [comment]
@Dekker3D That name sounds good, although a condensator is an old word for an (electrical) capacitor. I'd take it, I guess.

Or we could use water condenser.
https://www.treehugger.com/njord-portable-water-creator-condenses-drinking-water-air-reymin-de-leon-4857184

It's a bit confused because 'water condenser' is used both to mean the use of cool water to condense vapour (of any kind) back to liquid from a boiling container as well as the, more recent and less common, use above.

**Comment by kevingranade** [comment]
It's a brand name, it doesn't have to make sense.
