### ISSUE TITLE
Add Real Snow

### ISSUE THREAD

**Issue by Theawesomeboophis** [CleverRaven/Cataclysm-DDA#46354]
# Describe the solution you'd like
Snow should be it's own terrain, currently winter has grass like any other season.

# Describe alternatives you've considered
Leaving winter grass and not adding snow.

# Additional context
Thanks to @SomeDeadGuy for bringing this to my attention in https://github.com/SomeDeadGuy/UndeadPeopleTileset/issues/40

**Comment by ZhilkinSerg** [comment]
Sure, pick this up for the headstart - https://github.com/CleverRaven/Cataclysm-DDA/pull/28227

**Comment by Theawesomeboophis** [comment]
> Sure, pick this up for the headstart - #28227

Should I add the commits from that PR into mine or do it from scratch?

**Comment by actual-nh** [comment]
Also see #46328; ping @Aivean.

**Comment by Theawesomeboophis** [comment]
https://github.com/Theawesomeboophis/Cataclysm-DDA-Boophis/tree/Real-Snow
Branch Created.

**Comment by Theawesomeboophis** [comment]
What files need to be altered for proper implemtation?

**Comment by Theawesomeboophis** [comment]
Which files should I use for proper implementation?

**Comment by actual-nh** [comment]
From the discussion in #46328, probably weather.cpp/h and/or field.cpp/h and/or field_types.cpp/h and/or map.cpp/h. The earlier try (#28227) was rather too complicated to start; just something triggering the use of alternative tiles - without worrying about the player's ability to clear snow, needing snowshoes, etc - would be fine as an initial PR.

**Comment by Aivean** [comment]
My current plan (partially outlined in #46328) is following:
* For all submaps store two ints or floats:  
    * current accumulated precipitation level (updated from weather)
    * "actualized" precipitation level
* In "active" submaps store snow presence either as a bit matrix or as a `field`
* when submap is loaded, the difference between "current" and "actualized" precipitation level is added or removed from the "active snow" matrix in submap
* for loaded submaps this "actualization" is performed periodically (e.g. every one minute).
* during the rendering, if snow flag is present, it overrides the season suffix, i.e. first the "tile_name_with_snow" is searched, with fallback to the current tile search logic


@Theawesomeboophis , I thought of implementing this myself, but if you want to take a shot at this, you're welcome. However, I'd ask you to outline your detailed plan first. 

For example, 
> Snow should be it's own terrain

Doesn't sound as the right decision.

**Comment by Theawesomeboophis** [comment]
My plan was to add json terrain lines and program additional functions in
C++, but it seems this needs more work to be made functional, I will
attempt to implement it using the discussion as well as the proper
tutorials, but this may be beyond my capability.

My current plan (partially outlined in #46328
<https://github.com/CleverRaven/Cataclysm-DDA/discussions/46328>) is
following:

   - For all submaps store two ints or floats:
      - current accumulated precipitation level (updated from weather)
      - "actualized" precipitation level
   - In "active" submaps store snow presence either as a bit matrix or as a
   field
   - when submap is loaded, the difference between "current" and
   "actualized" precipitation level is added or removed from the "active snow"
   matrix in submap
   - for loaded submaps this "actualization" is performed periodically
   (e.g. every one minute).
   - during the rendering, if snow flag is present, it overrides the season
   suffix, i.e. first the "tile_name_with_snow" is searched, with fallback to
   the current tile search logic

@Theawesomeboophis <https://github.com/Theawesomeboophis> , I thought of
implementing this myself, but if you want to take a shot at this, you're
welcome. However, I'd ask you to outline your detailed plan first.

For example,

Snow should be it's own terrain

Doesn't sound as the right decision.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/CleverRaven/Cataclysm-DDA/issues/46354#issuecomment-751542020>,
or unsubscribe

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
