### ISSUE TITLE
NPC can teach you bartering

### ISSUE THREAD

**Issue by Salty-Panda** [CleverRaven/Cataclysm-DDA#46364]
# Describe the bug

I helped an NPC, asked her to teach me, among offers was bartering
![image](https://user-images.githubusercontent.com/26396019/103178188-e8949f00-4880-11eb-967a-9decf754fe61.png)

My social skill (6th lvl; 0%) didn't change

# Steps To Reproduce

Complete quest, get offered to be taught bartering.

# Expected behavior

Bartering should be removed from whatever lsit is used

#Screenshots
![image](https://user-images.githubusercontent.com/26396019/103178229-42956480-4881-11eb-96f2-5394868fbc02.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-8469-ga94a537 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Mythical Martial Arts [MMA],
    C.R.I.T Expansion Mod [crt_expansion],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Bionic Professions [package_bionic_professions],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP]
]

**Comment by wapcaplet** [comment]
Confirmed; I recently had an NPC offer to teach lockpicking, which is also an obsoleted skill.

**Comment by actual-nh** [comment]
Was the NPC offering to teach barter a bartender, junk shopkeeper, or Jack Isherwood? They're currently down as having barter skill.

**Comment by PaulBlay** [comment]
> Confirmed; I recently had an NPC offer to teach lockpicking, which is also an obsoleted skill.

Lockpicking is an obsoleted skill, but it is not an obsoleted proficiency. I'm like 50% sure I had my lockpicking proficiency increased by 12% from being taught by an NPC. (Only 50%, because I didn't check for sure I didn't have any proficiency beforehand).

**Comment by Mrzjadacz** [comment]
> Lockpicking is an obsoleted skill, but it is not an obsoleted proficiency. I'm like 50% sure I had my lockpicking proficiency increased by 12% from being taught by an NPC. (Only 50%, because I didn't check for sure I didn't have any proficiency beforehand).

NPCs can teach skills, martial arts, spells, and proficiencies (not really, just according to code), so lockpicking may appear and work properly.

The code to get teachable skills, profs etc. is in npc.cpp : 1476

**Comment by wapcaplet** [comment]
Here is a save game with a friendly NPC who does not have any proficiencies, yet can teach lockpicking and bartering:
[teach-proficiency.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5805226/teach-proficiency.zip)

![image](https://user-images.githubusercontent.com/238395/104383346-ec652a00-54ec-11eb-99e9-a716257a053a.png)

**Comment by Termineitor244** [comment]
Confirmed in the most recent version (Build 11451), attached save with npc offering to teach me both bartering and lockpicking.

[Spartanburg.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5949719/Spartanburg.zip) (Same save as in #47366 )

This world was made with a version of the game from like 3 - 4 days ago, so the npc should not be appearing with obsoleted skills.
I was going to do a different bug report, but I see it is already reported.

**Comment by actual-nh** [comment]
This is labeled as being for the 0.F milestone, but is not listed in the corresponding [project](https://github.com/CleverRaven/Cataclysm-DDA/projects/37)?
