### ISSUE TITLE
Give gas sacs a use as part of a craftable buoyancy aid.

### ISSUE THREAD

**Issue by DalenTalas** [CleverRaven/Cataclysm-DDA#46360]
# Is your feature request related to a problem? Please describe.
I have accumulated a large amount of junk gas sacs (which are supposedly filled with hydrogen) out of butchered insects, and there is currently no use for them. And, since I was building a boat, I figured making flotation aids out of those would make sense.

# Describe the solution you'd like
Implement a recipe for the following item:
**gas sac buoyancy cell**
Weight: 34.4 kg
Volume: 125 L
Length: 1 meter
Materials: Flesh, Plastic

**Recipe:**
tool with cutting
288 clusters of gas sacs
12 plastic bags (for bundling the sacs)
12 short strings or 12 short cordage pieces or the appropriate number of ropes/fiber/sinew/thread (for tying the sacs off)
2 rigid plastic sheets

**When installed in a vehicle:**
Mounting point TBD: same slot as the boat hull, or as gas tank, or outside the hull.
Increases the vehicle buoyancy (see calculations below).

# Describe alternatives you've considered
Implementing this myself. However, I can't be bothered to learn the game data format and how to operate Git, so I shall leave this to minds better equipped / inclined to do so. :)

Not sure if the buoyancy bonus is the best way to simulate this. Maybe would just be easier to make this an item that adds FLOATS, similar to the raft boat hull.

# Additional context
Calculations were as follows:

A single gas sac cluster has the volume of 0.25 L and the weight of 0.05 kg. Construction is a rectilinear volume 1m x 1m square x 0.1m high (100 L total volume), with a number of gas sacs gathered into bags and possibly sandwiched between two sheets of rigid plastic. Actual total volume of the item would be 125 L to account for the volume of the plastic sheets.

Assuming the densest possible packing (see [hexagonal close packing](https://mathworld.wolfram.com/HexagonalClosePacking.html)), only 0.7405 of the volume would be filled with the sacs (see [here](https://mathworld.wolfram.com/SpherePacking.html)). Round this down to 0.72 to account for the sac shape irregularities, survivor inefficiency, and to get a nice round number. This gives us 72 liters of gas sacs, or 288 of them.

Total weight of the item is then: 34.4 kg
2x 14.88 kg for the plastic
2x 0.12 kg for the strings and bags
288x 0.05 kg for the sacs = 14.4 kg

The buoyancy force acting on the item when fully submerged in water F[b] = V x D[H20] x g = 0.125 m^3 x 997 kg/m^3 x 9.8 m/s^2 = **1221.325 newtons (kg*m/s^2)**. As a sanity check, the item's density is 275.2 kg/m^3, so it will in fact float in water.

Subtracting the weight of the item should give the net buoyancy. I am having trouble here, since I can't figure out if, in the physics sense, the game operates with mass or weight of the item. However, looking at the way the game handles flotation calculations, this should not be necessary - simply plug in the item's weight and buoyancy bonus into the function.

If/when flight is implemented, a similar item, with much larger volume (about 1m^3). The lift force for flight calculations is calculated in the similar fashion, assuming air at STP and discounting the air density change at high altitudes (I doubt that the game will ever be concerned with flight anywhere above 500 ft.). For the item listed in the above recipe only, it will be F[l] = V x D[air] x g = 0.125 m^3 x 1.225 kg/m^3 x 9.8 m/s^2 = **1.500625 newtons (kg*m/s^2)** - definitely not enough to lift even its own weight. However, a larger cell may be able to actually achieve positive lift, and would need to be recalculated.

**Comment by PaulBlay** [comment]
This is actually a sensible idea.

Have you thought about also having a wearable vest type arrangement for people who have trouble swimming without sinking like a stone?

**Comment by kevingranade** [comment]
A bag of balloons isn't a sensible flotation aid for watercraft. Moreover, unless the extracted gas cells are more buoyant than air, placing them in a hull is no better than having an empty hull.

**Comment by PaulBlay** [comment]
@kevingranade If they aren't lighter than air, then they literally have no reason to exist. Although if someone suggested that they don't have a reason to exist I would be inclined to agree.

**Comment by anothersimulacrum** [comment]
They exist to allow insects to fly, do they need more reason?

**Comment by PaulBlay** [comment]
Just that the stated reason wouldn't actually work. It's like putting helium balloons inside an APC to make it float.

**Comment by anothersimulacrum** [comment]
They aren't the sole thing, but they decrease the amount of work required for the insect to power it's own flight.

**Comment by DalenTalas** [comment]
@kevingranade 
> A bag of balloons isn't a sensible flotation aid for watercraft. Moreover, unless the extracted gas cells are more buoyant than air, placing them in a hull is no better than having an empty hull.

@PaulBlay 
> Just that the stated reason wouldn't actually work. It's like putting helium balloons inside an APC to make it float.

I was certainly considering this, and guess I neglected to properly clarify another alternative. Have them placed _outside_ the hull.

The question is, does that expand the gameplay options that the player has?
