### ISSUE TITLE
Craft aluminum ingot from aluminum cans

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#46362]
# Is your feature request related to a problem? Please describe.

There is currently no recipe for making aluminum ingots. Said ingots are used in a number of recipes, including basics like extra-light frames.

# Describe the solution you'd like

New recipe for smelting aluminum from cans. Aluminum melts at 660.3 °C, higher than zinc but much lower than iron. One ingot is 675g, 54 aluminum cans is 702g. I tried the following recipe in materials.json it seems to work.

```
  {
    "result": "material_aluminium_ingot",
    "type": "recipe",
    "activity_level": "ACTIVE_EXERCISE",
    "category": "CC_OTHER",
    "subcategory": "CSC_OTHER_MATERIALS",
    "skill_used": "fabrication",
    "difficulty": 2,
    "time": "20 m",
    "batch_time_factors": [ 90, 4 ],
    "autolearn": true,
    "using": [ [ "forging_standard", 1 ] ],
    "proficiencies": [ { "proficiency": "prof_metalworking" }],
    "tools": [ [ [ "crucible", -1 ], [ "crucible_clay", -1 ] ] ],
    "components": [ [ [ "can_drink", 54 ] ] ]
  },
```

# Describe alternatives you've considered

Collecting and deconstructing heavy flashlights.

**Comment by DalenTalas** [comment]
Looks like you have everything to make a PR.

**Comment by kevingranade** [comment]
Aluminum cans use an alloy it is unfit for any usage present in the game. The exclusion of aluminum cans from ingot crafting is intentional.

**Comment by PaulBlay** [comment]
@kevingranade Could you elaborate or point to a discussion which covers the relevant points?
