### ISSUE TITLE
Having current route displayed in sidebar maps

### ISSUE THREAD

**Issue by D33pfield** [CleverRaven/Cataclysm-DDA#46372]
It is tedious to constantly have to swap to the full screen map to view your current route

I'd like to be able to view my current route from the sidebar. I think having it be in the Env map area would be less intrusive than having it be displayed in the sidebar map. Coloring the road a different color might work. 

I can't really think of any other way to display the route other than the sidebar maps.

Possible example:
No route shown
![no_route](https://user-images.githubusercontent.com/14086090/103209809-988dfa80-48c9-11eb-9436-10de21755633.png)

Route in Env map
![route](https://user-images.githubusercontent.com/14086090/103210025-1ce07d80-48ca-11eb-9c4a-87d7f651a680.png)

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
