### ISSUE TITLE
Segmentation fault error when loading save

### ISSUE THREAD

**Issue by teffekai** [CleverRaven/Cataclysm-DDA#46373]
# Describe the bug

Game crashes upon loading save. There were no errors during saving.

# Steps To Reproduce

Load the save and it should give the error.

# Versions and configuration

OS: Windows 10 Pro version 1909
Game Version: 0.E-8531-gea3e6a3
Graphics: Tiles (ASCIITiles)
Ingame language: English

# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5747778/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5747788/debug.log)
[Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5747797/Save.zip)

**Comment by BrettDong** [comment]
Your attached save file seems incomplete. Could you please zip the entire save folder with your world name?

**Comment by teffekai** [comment]
Forgive my ignorance, But the ENTIRE folder? With maps that's close to 30mb zipped.

**Comment by teffekai** [comment]
Here's the save https://drive.google.com/file/d/1B7coeNEltaEiz_oWMIMmydWc2LdfNFj5/view?usp=sharing
