### ISSUE TITLE
Weariness fluctuating unexpectedly/inconsistently in weary tests

### ISSUE THREAD

**Issue by actual-nh** [CleverRaven/Cataclysm-DDA#46384]
# Describe the bug

The following is from a run of the weary_recovery test case on my computer:

Digging Pits 8 hours, then waiting 8:
  Transition: Weariness from 0 to 1 at 115 minutes
  Transition: Weariness from _**1 to 0**_ at 120 minutes
  Transition: Weariness from 0 to 1 at 125 minutes
  Transition: Weariness from 1 to 2 at 250 minutes
  Transition: Weariness from 2 to 3 at 360 minutes
  Transition: Weariness from 3 to 4 at 465 minutes
  Transition: Weariness from 4 to 3 at 520 minutes
  Transition: Weariness from 3 to 4 at 540 minutes
  Transition: Weariness from 4 to 3 at 550 minutes
  Transition: Weariness from 3 to 2 at 640 minutes
  Transition: Weariness from 2 to 3 at 655 minutes
  Transition: Weariness from 3 to 2 at 670 minutes
  Transition: Weariness from 2 to 1 at 880 minutes
  Transition: Weariness from _**1 to 2**_ at 890 minutes
  Transition: Weariness from 2 to 1 at 910 minutes
  Weariness: 1726 Max Exertion: ACTIVE_EXERCISE Mult: 0.8
  BMR: _**1722**_ Intake: 1093 Tracker: 2273 Thresh: _**901**_ At: 1
  Calories: 52535
(This part of the test shows no errors on my computer, but has in a number of other cases - see #46256.) Note that the weariness level goes up and down throughout the test - digging was, at least at times, resulting in a **lower** weariness level (e.g., at 120 minutes), and waiting was, at least at times, resulting in a **higher** weariness level (e.g., at 890 minutes). (This also happens, but to a lesser degree, in runs which **_do_** show an error in this part - again, see #46256.) There are also problems (compared to other outputs) with the various statistics, which are gathered at the end of the 16 hours total; see below.

The second part of the weary_recovery test, which is done on the same test character, does show one failure on my computer, although other aspects of the results are actually more of interest:

../tests/weary_test.cpp:135: FAILED:
  CHECK( info.transition_minutes( 2, 1, 740_minutes ) == Approx( 740 ).margin( 5 ) )
with expansion:
  750 (0x2ee) == Approx( 740.0 )
with messages:
  
3 meals, 10h vehicle work, 4h reading, 10h sleep, 16h waiting
  Transition: Weariness from 0 to 1 at 325 minutes
  Transition: Weariness from 1 to 2 at 620 minutes
  Transition: Weariness from 2 to 1 at 750 minutes
  Transition: Weariness from 1 to 2 at 755 minutes
  Transition: Weariness from 2 to 1 at 770 minutes
  Transition: Weariness from 1 to 0 at 995 minutes
  Weariness: 0 Max Exertion: EXTRA_EXERCISE Mult: 1
  BMR: _**1712**_ Intake: 855 Tracker: 0 Thresh: _**1708**_ At: 0
  Calories: 51159

Note that:
- BMR is 10 calories less (likely due to weight loss after ditch-digging; an expansion of `debug_weary_info` - in character.cpp - to give Fatigue, Morale, and Weight would help, as would "Max Exertion" being changed to "Max Full Exert" or similar.
- However, the weary threshold has gone from 901 to 1708. This is both an **extreme** change and in the exact _opposite_ direction to the expected one, going down - very slightly - with BMR. (Such changes in the threshold are likely a major cause of the fluctuating weary level.)

These findings are consistent across different seeds (none, 609109782 (from #46366; admittedly different OS, so the RNG may well be different), and time (1609191397)).

# Steps To Reproduce

Run `tests/cata_test weary_recovery --success` (optionally with --rng-seed time or whatever). This may or may not yield all of the above; it appears to definitely depend on the OS, compiler, etc - possibly due to -ffast-math implementation differences.

For other cases of unexpected behavior (most notably weary levels going **up** during rest), also see #46256 for a listing of (unrelated) PRs (e.g., #46366) with weary_recovery test results at least partially available. #46380 (50685d4 is the abbreviated hash; see [https://github.com/CleverRaven/Cataclysm-DDA/pull/46380/checks?check_run_id=1619606026](https://github.com/CleverRaven/Cataclysm-DDA/pull/46380/checks?check_run_id=1619606026)) is a related case.

# Expected behavior

Weary thresholds (and, for that matter, BMR) should change only gradually. While doing significant exertion, weary levels should not decrease (even if the exertion's intensity is forced to decrease due to weariness). While resting, weary levels should not increase. Tests should check for this expected behavior. (I suspect part of the demand for more detailed weariness info inside the game - see #46193, #46340, and #46284 - may be accentuated by such unpredictable behavior.)

# Versions and configuration

 - OS: OS X 10.12.6; compiler:
 - - Apple LLVM version 8.1.0 (clang-802.0.42)
 - - Target: x86_64-apple-darwin16.7.0
 - - Thread model: posix
 - Game Version: 0.E-8388-gb85c4o930b; compiled with:
 - - make NATIVE=osx OSX_MIN=10.12 CLANG=1 MACPORTS=1 USE_HOME_DIR=1 DEBUG_SYMBOLS=1
 - Graphics version: Terminal
 - In-game language: N/A (testing; C locale)
 - Mods loaded: dda (testing; did not use --mods= to load any, thus cata_test inserted dda)

# Additional context

Ping: @anothersimulacrum (weary_recovery test author), @I-am-Erk (weariness system)

**Comment by anothersimulacrum** [comment]
> Digging Pits 8 hours, then waiting 8:
> Transition: Weariness from 0 to 1 at 115 minutes
> Transition: Weariness from _**1 to 0**_ at 120 minutes
> Transition: Weariness from 0 to 1 at 125 minutes
> Transition: Weariness from 1 to 2 at 250 minutes
> Transition: Weariness from 2 to 3 at 360 minutes
> Transition: Weariness from 3 to 4 at 465 minutes
> Transition: Weariness from 4 to 3 at 520 minutes
> Transition: Weariness from 3 to 4 at 540 minutes
> Transition: Weariness from 4 to 3 at 550 minutes
> Transition: Weariness from 3 to 2 at 640 minutes
> Transition: Weariness from 2 to 3 at 655 minutes
> Transition: Weariness from 3 to 2 at 670 minutes
> Transition: Weariness from 2 to 1 at 880 minutes
> Transition: Weariness from _**1 to 2**_ at 890 minutes
> Transition: Weariness from 2 to 1 at 910 minutes
> Weariness: 1726 Max Exertion: _ACTIVE_EXERCISE_ Mult: 0.8

Digging pits is `EXTRA_EXERCISE`, there's something up here.

**Comment by actual-nh** [comment]
> > Weariness: 1726 Max Exertion: _ACTIVE_EXERCISE_ Mult: 0.8
> 
> Digging pits is `EXTRA_EXERCISE`, there's something up here.

#46380 has digging pits for 12 hours being considered `NO_EXERCISE`...

**Comment by actual-nh** [comment]
> > Digging Pits 8 hours, then waiting 8:
> > Transition: Weariness from 0 to 1 at 115 minutes
> > Transition: Weariness from _**1 to 0**_ at 120 minutes
> > Transition: Weariness from 0 to 1 at 125 minutes
> > Transition: Weariness from 1 to 2 at 250 minutes
> > Transition: Weariness from 2 to 3 at 360 minutes
> > Transition: Weariness from 3 to 4 at 465 minutes
> > Transition: Weariness from 4 to 3 at 520 minutes
> > Transition: Weariness from 3 to 4 at 540 minutes
> > Transition: Weariness from 4 to 3 at 550 minutes
> > Transition: Weariness from 3 to 2 at 640 minutes
> > Transition: Weariness from 2 to 3 at 655 minutes
> > Transition: Weariness from 3 to 2 at 670 minutes
> > Transition: Weariness from 2 to 1 at 880 minutes
> > Transition: Weariness from _**1 to 2**_ at 890 minutes
> > Transition: Weariness from 2 to 1 at 910 minutes
> > Weariness: 1726 Max Exertion: _ACTIVE_EXERCISE_ Mult: 0.8
> 
> Digging pits is `EXTRA_EXERCISE`, there's something up here.

That turns out not to be a problem - it is indicating what level of exercise one can actually do.

**Comment by actual-nh** [comment]
And now I'm seeing different results depending on whether all tests, or only specific tests are run - see #46404.

**Comment by actual-nh** [comment]
I have determined (probably most of) the cause for the threshold fluctuations - in the second weary recovery test, fatigue goes down to -1000... and fatigue being lower means a higher threshold. See #46473 for data.

**Comment by actual-nh** [comment]
I have extended the #46473 version to include information during the test on not only weariness level, but precise weariness and weariness thresholds. The instability is (at least with the fatigue fix) due to fluctuating weariness, not weariness threshold; for instance, from the most recent appveyor tests:

```
weary_24h_tasks
  Digging 24 hours
-------------------------------------------------------------------------------
C:\Projects\Cataclysm-DDA\tests\weary_test.cpp(170)
...............................................................................
C:\Projects\Cataclysm-DDA\tests\weary_test.cpp(177): FAILED:
  CHECK( info.transition_minutes( 1, 2, 255_minutes ) == Approx( 255 ).margin( 5 ) )
with expansion:
  245 == Approx( 255.0 )
with messages:
  Weariness: 0 Max Full Exert: EXTRA_EXERCISE Mult: 1
  BMR: 1738 Intake: 0 Tracker: 0 Thresh: 1038 At: 0
  Cal: 55000/55000 Fatigue: 0 Morale: 0 Wgt: 76562 (BMI 25.0)
  Transition: Weariness lvl from 0 to 1 at 115 min (W 1066 Th 1019)
  Transition: Weariness lvl from 1 to 0 at 120 min (W 1013 Th 1020)
  Transition: Weariness lvl from 0 to 1 at 125 min (W 1073 Th 1019)
  Transition: Weariness lvl from 1 to 2 at 245 min (W 2021 Th 1000)
```

**Comment by actual-nh** [comment]
See #46473 (end) for more on this.

**Comment by RenechCDDA** [comment]
I haven't seen any problems with the weariness test in years so I think it's safe to close this. The author already has repository permissions to reopen if needed.
