### ISSUE TITLE
Rebar crowbar: bridging the gap?

### ISSUE THREAD

**Issue by Svankensen** [CleverRaven/Cataclysm-DDA#46382]
# Is your feature request related to a problem? Please describe.
We are all familiar with the (justifiable) ineffectiveness of the makeshift crowbar. So I remembered this old thing that has always been in my house:
![image](https://user-images.githubusercontent.com/5623801/103251280-fd436680-4956-11eb-8b01-5e60f8cb484f.png)

It is a combination hammer crowbar made out of rebar. We could do without the hammer part to keep things simple.

# Describe the solution you'd like
I would like an easy to craft rebar crowbar. Anvil 1, acetylene torch or electric forge (40 charges?), hammering 2, fabrication 2, autolearned. No need for glare protection, since it doesn't really shine bright. Unless you use an arc welder I guess? No idea if an arc welder would be up to the task honestly.

Found this video of someone making a rebar crowbar. It took him about an hour, going by the duration of the 50x speed montage. He used a loose piece of rail that jumped around. Crappy anvil, jumping around, so I'd say it is anvil 1? Maybe this suggests railroads should have anvil quality 2? I'm not sure if the anvil rating comes from the sturdiness or the special holes and whatnot. Anyway, this thing, mine at least, is quite sturdy, so it should have at least prying 2, which would allow us to again be able to open doors and windows. It is considerably more involved than smashing a pipe with a rock, but doesn't take 8 hours and a completely equiped forge, nor considerable skill. Heat the metal, hit the thing. It was the youtuber's "first time forging something".

https://www.youtube.com/watch?v=rzMPAD3mAVo

# Describe alternatives you've considered
Not including it.

**Comment by Mom-Bun** [comment]
With the items you provided for this recipe, you could just craft a regular crowbar.

This just seems like a waste.

**Comment by Svankensen** [comment]
> With the items you provided for this recipe, you could just craft a regular crowbar.
> 
> This just seems like a waste.

Crowbar requires anvil 3, chisseling 3, and hammering 3. This requires anvil 1, no chisseling, and hammering 2. Basically, you need to find an acetylene torch and a large rock.

**Comment by NeviNovat** [comment]
![image](https://user-images.githubusercontent.com/51816321/103252228-8f159880-4984-11eb-80d9-72c92e016fbf.png)
![image](https://user-images.githubusercontent.com/51816321/103252335-16630c00-4985-11eb-9722-9246b44224e0.png)

These items are sturdy and have anvil quality 1. So the quality might be related to how well an anvil will serve in making complex forms and straight edges.

I suggest making the rebar crowbar have prying quality of 3 like the normal crowbar. ( the claw bar, pretty much a smaller crowbar has a prying quality of 2 ) 
But make it be quite a bit more heavy then a normal crowbar and have a volume of 1.25L instead of 1L.

**Comment by DalenTalas** [comment]
Yeah, as far as I know, the advantage of using a full anvil vs an anvil-shaped object (c)purgatoryironworks , is that you can use the horn and hardy holes on it to form shapes beyond the basic drawing / upsetting / bending. Or, makes it more convenient.

See here: https://youtu.be/SHWd0bMVSOU

**Comment by kevingranade** [comment]
Mostly trivia, the reason anvils are made of one fuck off huge chunk of metal is it has elastic qualities that make forging significantly less physically demanding and therefore significantly faster.  Basically the hammer rebounds off the work piece and doesn't require the smith to lift the hammer as much with each swing.  As we don't have speed changes based on tool qualities, we can't really represent this.

Overall, give the rebar crowbar prying 2 and call it a day.  It's *not* a forged crowbar, why that is important is left as an exercise for the reader.

**Comment by Svankensen** [comment]
> Mostly trivia, the reason anvils are made of one fuck off huge chunk of metal is it has elastic qualities that make forging significantly less physically demanding and therefore significantly faster. Basically the hammer rebounds off the work piece and doesn't require the smith to lift the hammer as much with each swing. As we don't have speed changes based on tool qualities, we can't really represent this.

Huh, we were just talking in the discord about how some tools had higher ratings than any recipe requires. Would be cool for the future.


> Overall, give the rebar crowbar prying 2 and call it a day. It's _not_ a forged crowbar, why that is important is left as an exercise for the reader.

Will do. I have the JSON entries ready, but I haven't had time to figure all the related github PR stuff. Will get to it during the weekend. Thanks for the feedback!

**Comment by kasanryukin** [comment]
> https://www.youtube.com/watch?v=rzMPAD3mAVo

That dude could have done it in about 10 minutes or less if that railroad track was actually on something that isn't the grass.  He was losing 90% of the power of his hammer strikes to rebound from the soft surface.  Blacksmithing on an anvil is all about the mass; it's why anvils are heavy and generally securely affixed to something even heavier.  Mine in my backyard is driven with rail spikes into a half ton log I buried.

**Comment by kevingranade** [comment]
No movement in about a year, feel free to implement as outlined here.
