### ISSUE TITLE
MREs, entrees, dessert packs, and accessory packs should be containers

### ISSUE THREAD

**Issue by emptytriangle** [CleverRaven/Cataclysm-DDA#46383]
# Is your feature request related to a problem? Please describe.
When you activate or disassemble an MRE, it drops all the contents into the car seat you're sitting in or on the ground. Then the dessert pack and accessory pack drop their contents onto the ground, too.

Also, when you open an MRE bag, the entree is a perishable item. Like there's just a brick of food in there. You can eat the entree directly without opening it up, and it will rot if left alone.

# Describe the solution you'd like
An MRE should be a container which is a sealed plastic bag that prevents spoilage containing:
- 1 heat pack 
- 1 sealed plastic bag containing: (entree pack)
  - 1 perishable food entree (usually spaghetti-like consistency but sometimes it's like a taco shell and some meat)
- 1 sealed plastic bag containing: (spread)
  - 1 cheese spread **or** 1 peanut butter spread
- 1 sealed plastic bag containing: (fiber)
  - 2 crackers **or** 2 "snack bread" that are basically identical to the crackers
- 1 sealed plastic bag containing: (dessert pack)
  - 1 dehydrated fruit
  - 1 chocolate bar
  - 1 chocolate candy
  - 1 cookie
- 1 pack, wrapper, or sealed plastic bag or whatever sounds good containing: (accessory pack)
  - 6 water purification tablet
  - 1 gummy vitamin
  - 1 matchbook
  - 2 chewing gum
  - 8 paper _(should be toilet paper but we don't have individual sheets of toilet paper as an item. Fix?)_
  - 1 spork
  - 1 plastic beverage bag
  - **random two of**:
    - 1 protein shake mix
    - 1 instant coffee mix
    - 1 lemonade drink mix
    - 1 tea bag (lower chance than others?)

# Describe alternatives you've considered
Leave the entree alone but make it nonperishable (hacky/weird).
Do not add peanut butter spread to MREs.
Do not change drink mix or add tea bag, leave as 1x instant coffee mix and 1x lemonade drink mix in every MRE.
Do not add possibility of snack bread.
Do not add 2nd cracker.
Change 8 paper to 8 toilet paper sheet (new item?) which is essentially the same as paper. But this might have further implications (what is a toilet paper, can you disassemble it, etc.) so maybe leave this for a TP change.

# Additional context
## Possible bugs:
Imagine a chocolate bar is inside a paper wrapper which does not prevent spoiling.
And the paper wrapper is inside a plastic bag which does prevent spoiling.
Does the plastic bag prevent the chocolate bar from spoiling?

Does not matter for this issue if a sealed plastic bag is used for all containers in the MRE.

**Comment by emptytriangle** [comment]
if MREs become pockets this might be a problem:
#45251

**Comment by emptytriangle** [comment]
maybe we should have a "plastic heat shrink wrap" bag that prevents spoiling and can contain any volume of item but cannot be reused in recipes that call for a plastic bag. Then MREs won't suddenly generate a lot of useful plastic bags if this change is made. The plastic bags MREs and items in them come inside irl are not useful

**Comment by actual-nh** [comment]
From what I've read, soldiers (special ops types especially) in/going into the field sometimes take apart the MREs into the separate sealed containers and wrap the most useful ones of them up in a bundle secured with duct tape (military variety - 100-mph tape is one name for it). This reduces both weight and bulk.

> maybe we should have a "plastic heat shrink wrap" bag that prevents spoiling and can contain any volume of item but cannot be reused in recipes that call for a plastic bag.

Point.

> The plastic bags MREs and items in them come inside irl are not useful

Except as waste containers, yes.

**Comment by casswedson** [comment]
I am gonna go ahead and say I will turn MREs into containers. It's not something with high priority for me (not a high priority for anyone it seems), so it's gonna take me some time to get to it, but if you dear reader, you want to do it, please let me know :)

**Comment by actual-nh** [comment]
Is there any existing type of sealed container that turns into plastic scrap once opened?

**Comment by Fosheze** [comment]
> Is there any existing type of sealed container that turns into plastic scrap once opened?

It's probably easier to just make a separate item that can just be disassembled into plastic scrap. Similar to the wrapper item except made of plastic instead of paper.

**Comment by actual-nh** [comment]
I've got a lot on my plate, as the saying goes, but I'll try to get around to making such an item (unless someone else does so first, which I'd be perfectly happy with).
