### ISSUE TITLE
Crash in scenario selection menu on smaller terminal height

### ISSUE THREAD

**Issue by RelMayers** [CleverRaven/Cataclysm-DDA#46392]
# Describe bug 

Game crashes when going into scenario select menu 

# Steps To Reproduce

Create new character, go to next screen from pool point selection. OR
Create new random character go back to scenario menu 

# Expected behavior

It shouldn't crash but display posibble scenarios 

# Screenshots

# Versions and configuration

# Additional context

**Comment by ZhilkinSerg** [comment]
![image](https://user-images.githubusercontent.com/16213433/103291235-544f4700-49fc-11eb-9ad5-118e8a2bd0ec.png)

**Comment by ZhilkinSerg** [comment]
Increase Terminal Height in settings menu as a workaround.

**Comment by ZhilkinSerg** [comment]
Affects other platforms as well.
