### ISSUE TITLE
Segmentation error during reading.

### ISSUE THREAD

**Issue by Stoopedhooy** [CleverRaven/Cataclysm-DDA#46397]
# Describe the bug

Segmentation error happening when reading the book for a long time.

# Steps To Reproduce

1. Load the save. 
2. Start reading the book.
3. At random period of time segmentation error happens and game crashes.

# Expected behavior

No segmentation errors.

# Screenshots
![1](https://user-images.githubusercontent.com/76749054/103308170-00fce900-4a3c-11eb-892c-10e7fe77f752.PNG)

# Versions and configuration
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-8531-gea3e6a3 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

The issue seemingly manifested itself after consuming gamma globulin drug in attempt to counter toxins & bringing the fresh haul of books from the school library. 

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5751867/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5751868/debug.log)
[full save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5753214/full.save.zip)

**Comment by BrettDong** [comment]
Your attached save file seems incomplete. Could you please zip the entire save folder?

**Comment by Stoopedhooy** [comment]
My bad! Updated the file. Thank you.

**Comment by Ramza13** [comment]
This seems very similar to #43214 and #44764.  Both of those were crashes when you lost the item you were crafting.  

In this case I am guessing either the toxins or gamma shot caused you to drop the book but not cancel the activity.
