### ISSUE TITLE
Garages should provide lifting when parked close enough/inside

### ISSUE THREAD

**Issue by busterbogheart** [CleverRaven/Cataclysm-DDA#46398]
# Describe the solution you'd like
Parking inside a garage ought to give automatic lifting, given that most (all?) use lifts.  Some pop out of the floor, some are built into 2 posts, etc:

![2020-12-29 15_02_40-Types of Auto Lifts _ Automotive Lift Types](https://user-images.githubusercontent.com/19196781/103310944-ef3d2680-49e6-11eb-82ba-b26f1742153d.png)

**Comment by ZhilkinSerg** [comment]
There is no power.

**Comment by busterbogheart** [comment]
Really salient point.

Ok.

**Comment by Shodan14** [comment]
> There is no power.
Aren't there like big manual crank/hydraulic ones in garages?

**Comment by ZhilkinSerg** [comment]
> > There is no power.
> 
> Aren't there like big manual crank/hydraulic ones in garages?

Most are probably hydraulic - they still need power.

**Comment by actual-nh** [comment]
I would not be surprised if some motorcycle shops had crank or similar unpowered ones; I don't think CDDA has specifically motorcycle garages, however.

**Comment by Zireael07** [comment]
I think the lift my Dad has in the garage is one of those simple unpowered ones - it doesn't lift very high, just enough to change a wheel.

**Comment by Shodan14** [comment]
> 
> 
> I think the lift my Dad has in the car garage is one of those simple unpowered ones - it doesn't lift very high, just enough to change a wheel.

Any chance you could find a picture of something like that?

**Comment by busterbogheart** [comment]
They probably mean a hydraulic floor jack

**Comment by Shodan14** [comment]
> 
> 
> They probably mean a hydraulic floor jack

Oh yeah, that would make sense and work. Like a heavier and bulkier jack? Or a whole new one tile vehicle?

**Comment by busterbogheart** [comment]
From the JSONs i see the only items are a bottle jack and scissor jack.  A floor jack rated 3 tons might be a good addition.
![56642_W3](https://user-images.githubusercontent.com/19196781/103382858-950f9480-4abe-11eb-8b28-fc9fcfe52c04.jpg)

**Comment by actual-nh** [comment]
I've seen a manual jack that's more like a U-shape, I think.

**Comment by Shodan14** [comment]
We already have pallet lifters so could possibly base it on that?

**Comment by busterbogheart** [comment]
Not sure.  In the end it I think should be a 60-lb item (or so) that spawns in pro garages and some home garages.

**Comment by emptytriangle** [comment]
The way this is done IRL with no power is by digging a pit under the vehicle so you can access the underside from a standing position. There are garages with pits that are built fancy with concrete and steel plates. Here's an example of a pit from the mechanics garage in the Freedom base in STALKER:

Garage:
![image](https://user-images.githubusercontent.com/74749287/103446274-c5386e00-4c4b-11eb-8d35-9a2d232b7793.png)

Pit (stairs down into pit near player)
![image](https://user-images.githubusercontent.com/74749287/103446282-e39e6980-4c4b-11eb-9e59-bdf6424be721.png)

Truck under maintenance parked over pit:
![image](https://user-images.githubusercontent.com/74749287/103446300-0892dc80-4c4c-11eb-86eb-45a5a05de679.png)

**Comment by Shodan14** [comment]
@emptytriangle I was think about that before, but it does nothing to help access the wheels, which is what the jacking quality does.

**Comment by PaulBlay** [comment]
@Shodan14 

> it does nothing to help access the wheels, which is what the jacking quality does.

Actually, you can (but shouldn't in real life) use a pit to access the wheels wheel easy. All you need to do is drive onto the pit so that one corner of your vehicle is hanging over the pit. Don't forget to make sure to pile up a load of crap in the opposite corner so it doesn't tip over.

Penn and Teller use this principle to run someone over with a lorry without squishing them. (No pit required, just fake wheel and all the weight of the lorry balanced on the other side).

**Comment by Shodan14** [comment]
> 
> 
> @Shodan14
> 
> > it does nothing to help access the wheels, which is what the jacking quality does.
> 
> Actually, you can (but shouldn't in real life) use a pit to access the wheels wheel easy. All you need to do is drive onto the pit so that one corner of your vehicle is hanging over the pit. Don't forget to make sure to pile up a load of crap in the opposite corner so it doesn't tip over.
> 
> Penn and Teller use this principle to run someone over with a lorry without squishing them. (No pit required, just fake wheel and all the weight of the lorry balanced on the other side).

You're right, never thought about that.

**Comment by busterbogheart** [comment]
More "official" examples are described in this Marine Corp manual:


![2021-01-02 09_57_17-CH22 PDF - Adobe Acrobat Reader DC](https://user-images.githubusercontent.com/19196781/103460137-f5325080-4ce1-11eb-82b6-c53e3341d681.jpg)
![2021-01-02 09_58_55-CH22 PDF - Adobe Acrobat Reader DC](https://user-images.githubusercontent.com/19196781/103460138-f5cae700-4ce1-11eb-8875-675aa5d9a548.jpg)


But we're getting off topic.

**Comment by busterbogheart** [comment]
So, for this ticket, maybe we just need to add a floor jack item with more lifting strength than a bottle jack?

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
