### ISSUE TITLE
Crafting does not destroy ingredients in specific conditions

### ISSUE THREAD

**Issue by neosulc** [CleverRaven/Cataclysm-DDA#46396]
# Describe the bug

Crafting boiled makeshift bandage creates new boiled makeshift bandage as expected, but does not destroy makeshift bandage held in hand.

# Steps To Reproduce

Open attached savefile.
Craft 1 stack of boiled makeshift bandage.
Boiled makeshift bandage appears on workbench as expected.
Makeshift bandage x3 is not consumed from the character.

# Expected behavior

Makeshift bandage x3 is removed from chararcter.

# Versions and configuration

0.E-8533-g16e9590

Mods loaded: disable npc needs, bionic professions.

# Additional context

 DEBUG    : Tried to remove a item not in inventory.

 FUNCTION : item inventory::remove_item(const item*)
 FILE     : src/inventory.cpp
 LINE     : 578

[Mullins.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5751873/Mullins.zip)

**Comment by zantanzuken** [comment]
tested, diffrent character same conclusion, wielding bandages in hand results in craft giving error 'src/inventory.cpp:578 [item inventory::remove_item(const item*)] Tried to remove a item not in inventory.', leaving you with bandages in hand (that you then discard to clear your hands for the recipe)
