### ISSUE TITLE
Floating amphibious vehicle disappears when a part is installed over a terrain

### ISSUE THREAD

**Issue by Mrzjadacz** [CleverRaven/Cataclysm-DDA#46399]
# Describe the bug

Had a car, floating on the water near a lab. Wanted to quickly add a new frame and install an autoclave on it. Instead, it went PUFF

# Steps To Reproduce

Have boat/vehicle that floats. Park it on water next to the ground. Add a frame to it so that it's placed on a ground tile. Try to install any component on the newly added frame.

# Expected behavior

Vehicle to continue its existence

# Screenshots

![image](https://user-images.githubusercontent.com/26396019/103311671-43fa9480-4a1b-11eb-96ed-67c334d1e2e0.png)
![image](https://user-images.githubusercontent.com/26396019/103311586-0d247e80-4a1b-11eb-90b1-438a23992a96.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-8469-ga94a537 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Mythical Martial Arts [MMA],
    C.R.I.T Expansion Mod [crt_expansion],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Bionic Professions [package_bionic_professions],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP]
]

# Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5752043/debug.log)

**Comment by Mrzjadacz** [comment]
Ok. After adding this frame (which previously was in the car's cargo so total weight should stay the same), the vehicle got just heavy enough (Clearance -0.00m) to sink. Probably happened in the background during installing the part on it.

**Comment by zantanzuken** [comment]
yeah i was gonna say... probably sank into the lake. autoclave's heavy!
