### ISSUE TITLE
Wearable guns don't display encumbrance

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#46391]
# Describe the bug

# Steps To Reproduce
Load the attached game and select the worn gun in the inventory.

# Expected behavior
Numbers showing up.

# Screenshots
![](https://tinystash.undef.im/il/cvM5RFK27CGFvNG5nHdDpGqdGXfd3xBfyvJvBb4toHX5gs7V2eMioEU2aTf1erDak5mRq6QW4vGKgAVvwPxyUse)

# Versions and configuration
- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.E-8531-gea3e6a3837-dirty [64-bit]
- Graphics Version: Curses
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

# Additional context
[2020.12.19.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5750488/2020.12.19.zip)

**Comment by Owlblocks** [comment]
I'll take a look at this when I can.

**Comment by Jamuro-g** [comment]
checked the save, seems to be fixed already

**Comment by Owlblocks** [comment]
Huh, maybe someone else did it. Anyone know the commit, so we can (potentially) close this issue? I hadn't realized how late it was getting; I looked into it and found the source, but the code regarding wearable guns is very hacky, and I wasn't sure if there was more to it than appeared.

**Comment by anothersimulacrum** [comment]
I can still reproduce this by spawning an m4a1, unloading it, and then attaching a shoulder strap to it.
