### ISSUE TITLE
Vehicles can drive through multiple single open doors / gates in ways that defy geometry

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#46403]
# Describe the bug

You can drive vehicles that are three tiles or more wide through three or more open gates/doors. This should not be possible (without lots of crash sounds and debris). Specifically, normal doors / gates are hinged on the left or right side and held up by a wall / post on that side. You can have a left opening door next to a right opening door to get a two tile wide vehicle through without crashing, however there is no combination for three or more doors/gates that will allow a three or more wide vehicle to drive through without having to smash a post.

NOTE: I am not talking about multi-tile gates and barriers that are opened by pulleys or mechanisms. We can presume that these either go up or slide across as a whole unit. These are multiple single doors/gates that can be opened and closed individually.

# Steps To Reproduce

1. Find or place a line of six normal split panel gates (or pretty much any other standard single tile gate)
2. Open the gates.
3. Drive a vehicle through them.

# Expected behavior

There should be crashes, smashes, and scrap metal flying.

Sometimes it is clear that the maps want a line of single gate to 'pretend' to be a single long gate so trucks can get into / out of a farm yard. These should really be a single multi-tile gate. Currently the best way to handle those cases would probably be a variation on the rope pulley / gate used in the Ranch.

There is currently no method to handle a multiple tile gate that is opened manually by pulling / pushing on one side. You could imagine handling it something like having a 5x1 vehicle that is turning. 

# Versions and configuration

- OS: Windows: Windows x64 8.1
- Game Version: 0.E-8531-gea3e6a3 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

# Additional context

The most jarring example was when I drove my Luxury RV out of the mall through a line of open glass doors.

**Comment by Svankensen** [comment]
In reality, it depends on the door that is intended to be represented by the multiple gates together. In the car show for example, they represent a car gate. Same in ranches.

**Comment by zantanzuken** [comment]
the open glass doors thing is an example of 'well they had to get that inside -somehow-, in real life they'd remove the doors and expand the gateway, but smaller cars should be able to fit through two double doors.. in cata thats represented by 1 block, where a car is multiple.

**Comment by PaulBlay** [comment]
> the open glass doors thing is an example of 'well they had to get that inside -somehow-',

That doesn't really make sense. If the answer to 'somehow' is 'they removed the doors and dismantled the door frames' then you shouldn't be able to get out without removing the door and dismantling the door frames.

> In reality, it depends on the door that is intended to be represented by the multiple gates together. 

But there are actual means to open multiple tiles at once (rope pulleys and mechanisms). There could be more means (multi-tile dragging to diagonal then fully open) but the existing ones are still better than "it's actually just one gate, squint your eyes and pretend".

**Comment by l29ah** [comment]
I hope this won't be addressed before monsters cease being able to phase through diagonal vehicle walls ;)

**Comment by zantanzuken** [comment]
no but [this](https://www.youtube.com/watch?v=WHVnMtw-mWk) is what i mean, the mall doors are certainly big enough to fit a car through them under normal circumstances, just not a cataclysm car, because size is funky.

... it also depends on the door of the mall, quite [often](https://lh3.googleusercontent.com/proxy/NUA4InQaexbYfVHX9-IhwZLK5R8TC36fFWZqmcp15Q8CIugpM09CeEPL5x8Qumdgi6JBxWhrsjj544l8rFAWcaSGSHaBSyWEXzTkODJpfO_b3tuqo-IfCWfgf3g) the mall doors have just regular windows above the main doors, and at least [one](https://lh3.googleusercontent.com/proxy/tdzVKkpg0A5fIgEnupAo6slnEVUb8H7CuESrKBUbMRpXj1kTH_qbG_CZakKUQlccO1-LCz4HGii7y9upUlAz1DfmW6dZlM5k_zQIscPMpb-S3XSimhnRY_kl4C8) of them have removable/slidable ones (showrooms use these too) so they can get big things in and out easily. you CAN drive an RV in/out through a [mall door](https://image.shutterstock.com/image-photo/glass-automatic-sliding-doors-entrance-260nw-1127283056.jpg), under normal circumstances, without using these doors... there'd just be a lot of glass.

**Comment by PaulBlay** [comment]
> no but this is what i mean, the mall doors are certainly big enough to fit a car through them under normal circumstances, just not a cataclysm car, because size is funky.

That would be a two tile wide vehicle if it wasn't for vehicle walls / door taking up an entire tile in CDDA. My luxury RV sure wouldn't have fitted there.

> ... it also depends on the door of the mall, quite often the mall doors have just regular windows above the main doors

Broken link on 'often'.

> and at least one of them have removable/slidable ones (showrooms use these too) so they can get big things in and out easily.

I was disappointed that you couldn't deconstruct the mall glass doors - but that's a different issue.

> you CAN drive an RV in/out through a mall door, under normal circumstances, without using these doors... there'd just be a lot of glass.

The funky relative fragility of things in CDDA and how one wing-mirror can stop a whole cube van from moving is also a different issue.

@I29ah I hope that isn't one of those "X is more important than Y, so don't fix Y before X" arguments. Because while I would also like to be able to turn my vehicle without having mobs eat me there is no such guideline on changes. Mainly because it depends on how difficult X and Y are to fix and whether anybody is interested in working on them.

**Comment by zantanzuken** [comment]
the often link is just the 'one' link with closed doors... weird
[is this](http://www.crl-arch.com/systems/storefronts/elephant_doors/img/1.png)
[better?](http://www.crl-arch.com/systems/storefronts/elephant_doors/img/2.png)

**Comment by PaulBlay** [comment]
> (you cant make winch doors yourself can you?)

I thought you could? At least the garage door style. Maybe I'm imagining it.

**Comment by PatrikLundell** [comment]
You can make palisade gates yourself (I believe: they're present in the construction menu) and make base camp blueprints that produce them (definitely: I've also tested that the pulleys will actually open/close them, although there are some weird issues with closing them again sometimes).
The metal gates (e.g. found in private resorts) can be operated but do not seem to have construction blueprints for them.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
