### ISSUE TITLE
Fuji's Military Profession Pack throwing errors on load

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#46408]
# Describe the bug

When instantiating a world with Fuji's Military Profession Pack, the game throws the following error:

```
 DEBUG    : tried to put an item (m1911mag) count (1) in a container (legpouch_large) that cannot contain it: pockets unacceptable because item is too long

 FUNCTION : ret_val<bool> item::put_in(const item&, item_pocket::pocket_type)
 FILE     : src/item.cpp
 LINE     : 1053
```

I was able to determine the following:

```
From .data/mods/Fuji_Mil_Prof/prof/spc.json:
   { "item": "legpouch_large", "contents-group": "army_mags_1911" }
```

This is defined in `.data/mods/Fuji_Mil_Prof/prof/itemgroups_prof.json` as:

```
   {
    "type": "item_group",
    "subtype": "collection",
    "id": "army_mags_1911",
    "entries": [
      { "item": "m1911mag", "ammo-item": "45_acp", "charges": 7 },
      { "item": "m1911mag", "ammo-item": "45_acp", "charges": 7 }
    ]
  }
```

This item has a volume of 61ml, a longest side of 132mm, and is flagged as `MAG_COMPACT` in `./data/json/items/magazine/460.json`.

In `./data/json/items/armor/ammo_pouch.json` we find the definition for `legpouch_large`, whose pockets are defined thus:
```
{
        "pocket_type": "CONTAINER",
        "max_contains_volume": "500 ml",
        "max_contains_weight": "2 kg",
        "moves": 40,
        "flag_restriction": [ "MAG_COMPACT" ]
      }
```

At first, I thought the problem was trying to put two mags in one pocket, but the game fails at the first insertion. Additionally, during runtime, I'm able to insert a `m1911mag` into a `legpouch_large` with no issues.

# Steps To Reproduce

1. Create a world with Fuji's Military Profession pack in its mod load.
2. Attempt to load the world.

# Expected behavior

To not see this error.

# Screenshots

![image](https://user-images.githubusercontent.com/13796683/103332477-14a65080-4a38-11eb-8233-7d8ceb843da5.png)

# Versions and configuration

Build 11309.

**Comment by BreadPrince** [comment]
I found that pockets of `legpouch_large` does not have `max_item_length` property.

Thus, `max_item_length` will be set to default value: `std::round( std::cbrt( max_contains_volume ) ) * M_SQRT2` = 113mm.

But the `longest_side` of `m1911mag` is 132mm, that's why this debug msg shows up.

**Comment by ToxiClay** [comment]
> I found that pockets of `legpouch_large` does not have `max_item_length` property.
> 
> Thus, `max_item_length` will be set to default value: `std::round( std::cbrt( max_contains_volume ) ) * M_SQRT2` = 113mm.
> 
> But the `longest_side` of `m1911mag` is 132mm, that's why this debug msg shows up.

Oh, holy shit. Good sleuthing. I wonder why I'm able to insert it in-game?

**Comment by BreadPrince** [comment]
> > I found that pockets of `legpouch_large` does not have `max_item_length` property.
> > Thus, `max_item_length` will be set to default value: `std::round( std::cbrt( max_contains_volume ) ) * M_SQRT2` = 113mm.
> > But the `longest_side` of `m1911mag` is 132mm, that's why this debug msg shows up.
> 
> Oh, holy shit. Good sleuthing. I wonder why I'm able to insert it in-game?

You are using "M1911 10-round magazine" which does not have `max_item_length` too.

Try "M1911 7-round magazine".

**Comment by ToxiClay** [comment]
Yep; the game will not show the 7rd magazine as a valid insertion target for the leg ammo pouch. It'll be an easy fix, whenever I get around to it.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.E-10390.

![изображение](https://user-images.githubusercontent.com/11132525/115100910-19dccc00-9f51-11eb-8fe3-e51a95ff8dd9.png)

https://github.com/CleverRaven/Cataclysm-DDA/blob/0469910665608fda5a5e05b50626206e80b31b66/data/json/items/armor/ammo_pouch.json#L310-L327

`legpouch_large` has `max_item_length` defined as 240mm.
