### ISSUE TITLE
The JSON formatter output contains lines that are longer than 120 characters

### ISSUE THREAD

**Issue by int-ua** [CleverRaven/Cataclysm-DDA#46412]
# Describe the bug

https://github.com/CleverRaven/Cataclysm-DDA/blob/8bced723ffee6265e9ae03900e683c98d961f7c4/gfx/UltimateCataclysm/tile_config.json#L6006

The longest line is 137 characters long
```json
           "//": [ "hdframe_horizontal_unconnected_rotW", "hdframe_horizontal_unconnected_rotS", "hdframe_horizontal_unconnected_rotE" ],
```

# Steps To Reproduce

```sh
$ grep -x '.\{121,\}' gfx/UltimateCataclysm/tile_config.json | wc -l
42
```

Or feed the current `gfx/UltimateCataclysm/tile_config.json` to the https://dev.narc.ro/cataclysm/format.html

# Expected behavior

All lines are shorter than 120 characters.

# Versions and configuration

master code

# Additional context

Tried implementing a linter with the same style in Python, found this difference.

**Comment by kevingranade** [comment]
See also #38007
