### ISSUE TITLE
Draw a [separate] item indicator for items underneath vehicles

### ISSUE THREAD

**Issue by int-ua** [CleverRaven/Cataclysm-DDA#46414]
# Is your feature request related to a problem? Please describe.
Items that are underneath vehicles are invisible if any vehicle part covers them.

# Describe the solution you'd like
Having a [separate] item indicator for tiles with items underneath vehicles.

# Describe alternatives you've considered
Option to draw the same `highlight_item` for both cases: when items are inside vehicle and outside.

# Additional context

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.

**Comment by Zireael07** [comment]
Some of the issues you're closing are genuine QoL requests, why are they closed? The fact that some time passed doesn't make them any less valid.

**Comment by Night-Pryanik** [comment]
Closing as stale doesn't make them less valid either, it's said in stalebot's message.

**Comment by Zireael07** [comment]
How will people (either trying to report or someone wanting to implement) find them in the sheer mass of closed things (most of which are invalid/fixed)?

**Comment by Night-Pryanik** [comment]
If someone wants to implement something, he doesn't need an open issue for that. He just implements, and that's it.
Using open issues with feature/QoL requests as a source of inspiration is fine (in general), but not now, when we had 3200+ open issues, which made using the whole issues system barely usable.

**Comment by Zireael07** [comment]
Some projects have a "salvageable"/"PRs welcome" tag for such things
