### ISSUE TITLE
Sun Mage seems to use ilegal damage type for it's blinding ability

### ISSUE THREAD

**Issue by Svankensen** [CleverRaven/Cataclysm-DDA#46415]
I get this error when meleeing enemies:
 DEBUG    : monster::deal_damage_handle_type: illegal damage type damage_type::NONE

 FUNCTION : virtual void monster::deal_damage_handle_type(const effect_source&, const damage_unit&, bodypart_id, int&, int&)
 FILE     : src/monster.cpp
 LINE     : 1614

It also "reflects on the Kevlar zombie's thic hide", which is something I doubt a flash of light would do, but that's a separate issue.

# Steps To Reproduce

Become sun mage.
Hit zombies in melee until the ability triggers.

 - OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-8544-g0c9c8e7 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP]
]

**Comment by actual-nh** [comment]
@KorGgenT: enchantments/Sun_Mage.json has min_damage and max_damage but no damage type; it is actually supposed to default to PURE, but apparently that isn't working?

**Comment by Svankensen** [comment]
Oh, forgot to mention that the constructs from the forge of wonders have the same problem!

**Comment by KorGgenT** [comment]
@actual-nh you would be correct - there was a change in damage types a while ago and the spell documentation actually never got updated to reflect that. it probably just needs to be updated to "pure"

**Comment by actual-nh** [comment]
> @actual-nh you would be correct - there was a change in damage types a while ago and the spell documentation actually never got updated to reflect that. it probably just needs to be updated to "pure"

Documentation and also magic.cpp, so the default there is no longer NONE?
