### ISSUE TITLE
Receiving reward for "item not in inventory" 

### ISSUE THREAD

**Issue by Exis10ce** [CleverRaven/Cataclysm-DDA#46423]
# Describe the bug

While wielding "meat jerky," I was given a reward of "25 Merchs" by refuge center's broker. The game showed error screen "Tried to remove a item not in inventory." I kept the original item "meat jerky" and the reward of 25 Merchs.

# Steps To Reproduce

1. Craft meat jerky.
2. Wield meat jerky.
3. Talk with broker about bringing in food.
4. Receive reward.
5. Observe error message.

# Expected behavior

Meat jerky, whether in inventory or wielded, should be removed from player in exchange for reward.

# Screenshots

![Capture1](https://user-images.githubusercontent.com/76800066/103392156-84751380-4aea-11eb-93f2-19d02b3358f5.PNG)
![Capture2](https://user-images.githubusercontent.com/76800066/103392160-86d76d80-4aea-11eb-9d7f-a85ae75e1649.PNG)
![Capture3](https://user-images.githubusercontent.com/76800066/103392161-88089a80-4aea-11eb-9b09-2d8a320345d0.PNG)
![Capture4](https://user-images.githubusercontent.com/76800066/103392164-89d25e00-4aea-11eb-9d76-10ad2d4cac48.PNG)
![Capture5](https://user-images.githubusercontent.com/76800066/103392166-8b038b00-4aea-11eb-9166-1c86ad8299f3.PNG)

# Versions and configuration

    - OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-8547-g8bced72 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]

    - Please update your OS version with a more precise version: 10.0.18363 Build 18363

# Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5756354/debug.log)
[Savefile.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5756355/Savefile.zip)

**Comment by actual-nh** [comment]
#46381 may fix this.
