### ISSUE TITLE
crash, after sending NPC farming in the faction camp, during sleep.

### ISSUE THREAD

**Issue by Shadesmar99** [CleverRaven/Cataclysm-DDA#46429]
# Describe the bug

crash, after sending NPC farming in the faction camp, during sleep. The program freezes and can only be terminated with the task manager.

# Steps To Reproduce

1. set up faction camp with one NPC
2. have some seeds in the storage, (i have the seed storage on the same tile as the general storage
3. set up farming field zones 
4. go to sleep

# Expected behavior
no crash while sleeping

# Versions and configuration

 - OS: Win10  10.0 1909
 - Game Version: 0.E-2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

[crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5757969/crash.zip)

**Comment by Ramza13** [comment]
So I have loaded your save with the latest code and taken the following steps. 

1. talking to Simefirmi
2. tell him to come with me
3. tell him i want to assign him to work at this camp
4. set farming priority to 1
5. Sleep

What happens is the NPC taking the job and no crash or infinite loop.  Were you taking different steps to produce this issue or using an older build?

**Comment by Shadesmar99** [comment]
farming priority? i dont even know how to do that... 
 i told Simefirmi to directly farming at the fields with "i: i want to assign you to work at the camp", choosing her and selecting "Farming at the fields".
And then sleeping on the bed (east of the stairs) nearby. i tried some stuff again and it looks like the sleeping location here is of some importance.. i went in the cellar, slept there and no problem.
i slept near the wall near the field at the east (so that i get the messages about Simefirmi's work in the log, because the fields are east of the shelter) and it gets stuck again

**Comment by Ramza13** [comment]
Are you using the latest version?  I still can't reproduce the crash on the latest version but I do see a weird prompt about lighting something that seems glitchy.  And my menu option seem different than yours.  
Here are my choices: 
a: I need you to come with me.
d: Theres something I want you to do.
f: I want to assign you to work at this camp.
This pops up a window where I can only hit return on Simefirmi then i can change priority of tasks.

If you are on the latest version what choices are you making/seeing?

**Comment by int-ua** [comment]
Please comment with more details if you ever experience this issue again and we'll reopen this.
