### ISSUE TITLE
[CR] Magiclysm - Windstrike max spell damage

### ISSUE THREAD

**Issue by keampe** [CleverRaven/Cataclysm-DDA#46424]
# Describe the bug

Windstrike says that the MAX damage is 68, but caps out at 36

# Steps To Reproduce

1. Learn Windstrike
2. Get windstrike up to level 10 (it's maximum)
3. Max damage is 36 instead of 68, max range is 14 instead of 20.

# Expected behavior

68 damage and 20 range.

# Additional context

I suspect there are other spells with the same issue. This is basic JSON work that I'd be totally willing to do but I'm wanting some feedback before settling on a course of action.

Windstrike has a base damage of 24, base range of 4 and goes up by 1.2 damage, 1 range per level with a max level of 10. 

I can think of 4 ways this could be fixed.

1. Leave it as is, change max damage to 36 and max range to 14.
2. Up the max level of spell - spell would have to be level ~ 37 to max at 68 damage and level 16 to max range at 20.
3. Up the damage gain to 4.4 and range gain to 1.6.
4. A combination of 2 and 3. Upping the damage gain to 2.2 and max spell level to 20 would work, for example.

I'm leaning towards choice 4 but any feedback would be much appreciated.

   - Shane

**Comment by actual-nh** [comment]
Ping: @KorGgenT

**Comment by KorGgenT** [comment]
i'd be ok with #4. compare the power of windstrike to magic missile, i believe they're the same tier of spell so should have the same power level.
