### ISSUE TITLE
Plutonium batteries are unobtainable, but not obsoleted

### ISSUE THREAD

**Issue by Salty-Panda** [CleverRaven/Cataclysm-DDA#46431]
# Describe the bug

![image](https://user-images.githubusercontent.com/26396019/103422723-25270a00-4ba3-11eb-950d-43fcbab4661f.png)
Various items clearly state that they are the only applicable power source but the only way to obtain any of them is to use a certain starting profession.

There is a book with the recipe for them, but it doesn't spawn either.

EDIT: Advanced UPS according to the description is fueled with plutonium fuel cells, but actually only accepts heavy plutonium battery, which kinda makes no sense.

# Expected behavior

1) Spawn them in labs, certain facilities, high-tech instances, and military instances
2) Spawn book that teaches you the recipe to craft them (makes no sense if done without the former)
3) Obsolete them, make all equipment that uses them UPS by default
EDIT. 4) Remove/fix Advanced UPS

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-8536-g9c2c35a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Mythical Martial Arts [MMA],
    C.R.I.T Expansion Mod [crt_expansion],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Bionic Professions [package_bionic_professions],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP]
]

**Comment by kevingranade** [comment]
Spawning them is a possibility, but we probably want a re-skin if so.  
Making things that accept plutonium batteries accept UPS instead is a non-starter.
Completing the obsoletion (or moving them to a mod that wants them) is a possibility.

**Comment by emptytriangle** [comment]
if plutonium batteries are going away and the only kind of non-rechargeable battery are disposable alkaline-like cells can we revert #31426 and allow some tools to recharge when stored in a recharging station without removing and swapping batteries?

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
