### ISSUE TITLE
Record and replay command sequences

### ISSUE THREAD

**Issue by ferry-** [CleverRaven/Cataclysm-DDA#46430]
Certain actions like farming are very tedious as they require several keypresses to upturn soil, examine tile, select seed and move, for each tile of farming. I propose the addition of a record and replay system, similar to the one in Dwarf Fortress.

The record mechanism should log actions not keypresses, so the commands would still make sense if the keybindings change after recording. Looking at `input.h`, I'm guessing recording the resulting `item_action_id` from each keypress/touch should accomplish this. This would also make it easy to support all types of input methods.

The playback mechanism could also be a bit smarter than just replaying commands. It could validate that each command leads to the same context when replayed, as it did when it was recorded. So for instance when replaying a seed planting sequence after running out of seeds, the examine command wouldn't open the seed selection dialogue, at which point the replay would be aborted. This would also make it possible to have a "replay loop until error" command.

The command log would be stored in a temporary buffer and only saved through a separate command. This is to minimize the number of commands needed to automate once-off tasks. Saved command logs could work like the Autopickup rules - per save or global.

basic use:
- type `^r` to start recording
- a "Recording" label appears on the status panel
- input character commands to record
- type `^r` again to stop recording
- reposition character or otherwise input other commands
- type `^p` to replay the last log

saving command logs:
- type `^r` to start recording
- a "Recording" label appears on the status panel
- input character commands to record
- type `^r` again to stop recording
- type `^R` - a dialogue box prompting a name for this log appears

replaying saved logs:
- type `^P` - a list of saved logs appears
- optionally select things like "repeat up to N times", "stop on error", or "stop on threat sighted"
- select which log to load, it then begins to replay
- if necessary, enter the "pause" command (default key numpad `5`) to interrupt the playback.

I'll take a stab at implementing this. I'd like some input on the how feasible/sensible the design above is. Besides `input.h/cpp`, any other place I should look into? Thanks.

**Comment by anothersimulacrum** [comment]
Past discussion macros:
https://discourse.cataclysmdda.org/t/macros-in-cdda-recording-inputs/17700/2

**Comment by kevingranade** [comment]
As the above link outlines, we need automation for this kind of thing in the game, not re-implemented by players over and over again.

Specifically concerning your use case, you want to set a farming zone.
Hit Y
Hit a
Hit 7 "Farm: Plot"
Place the zone.
Hit O
