### ISSUE TITLE
Annoing game crashes

### ISSUE THREAD

**Issue by Dyuden** [CleverRaven/Cataclysm-DDA#46438]
Reading/crafting at home and nearby causes crash. I don't think it's problem with save and you can reproduce it. Reinstalling game helps for a while but problem comes back. And also sometimes stupid restarting over and over again let me craft or read sucsessfully. Also craft and reading availible upstairs.
Also I got some errors when launch game before main menu, I'll attach them 

# Steps To Reproduce

1. Take book and read or craft anything at home.
2. Experience crash.

# Expected behavior

Game works properly and let me play freely.

# Screenshots

# Versions and configuration

    
(Game language russian, tried in english same crash)
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-8361-g30e687d [32-bit]
- Graphics Version: Tiles
- Game Language: Системный язык []
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у NPC [no_npc_food]
]

# Additional context

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5758255/save.zip)
[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5758257/config.zip)

Crash: if your problem refers to a crash, please add the following files to the "Additional Context" paragraph:
    - From the /config folder (you can zip them both together):
        - crash.log file.
        - debug.log file.
    - Your save file (zipped)

 V   This are errors at starting screen before main menu V
Error1
  DEBUG    : (json-error)
Json error: <unknown source file>:2:21: Failed to visit member fontblending in JsonObject

{
    "fontblending" :
                    ^
                     false,
    "fontwidth" : 9,
    "fontheight" : 15,

 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : src/json.cpp
 LINE     : 120

Error2 
DEBUG    : (json-error)
Json error: <unknown source file>:4:19: Failed to visit member fontheight in JsonObject

    "fontblending" : false,
    "fontwidth" : 9,
    "fontheight" :
                  ^
                   15,
    "fontsize" : 14,
    "typeface" : "TerminusRus",

 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : src/json.cpp
 LINE     : 120

Error3 
DEBUG    : (json-error)
Json error: <unknown source file>:5:17: Failed to visit member fontsize in JsonObject

    "fontwidth" : 9,
    "fontheight" : 15,
    "fontsize" :
                ^
                 14,
    "typeface" : "TerminusRus",
    "map_fontwidth" : 9,

 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : src/json.cpp
 LINE     : 120

Error4
 DEBUG    : (json-error)
Json error: <unknown source file>:3:18: Failed to visit member fontwidth in JsonObject

{
    "fontblending" : false,
    "fontwidth" :
                 ^
                  9,
    "fontheight" : 15,
    "fontsize" : 14,

 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : src/json.cpp
 LINE     : 120

Error 5
 DEBUG    : (json-error)
Json error: <unknown source file>:8:23: Failed to visit member map_fontheight in JsonObject

    "typeface" : "TerminusRus",
    "map_fontwidth" : 9,
    "map_fontheight" :
                      ^
                       15,
    "map_fontsize" : 14,
    "map_typeface" : "TerminusRus",

 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : src/json.cpp
 LINE     : 120

Error 6
 DEBUG    : (json-error)
Json error: <unknown source file>:9:21: Failed to visit member map_fontsize in JsonObject

    "map_fontwidth" : 9,
    "map_fontheight" : 15,
    "map_fontsize" :
                    ^
                     14,
    "map_typeface" : "TerminusRus",
    "overmap_fontwidth" : 9,

 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : src/json.cpp
 LINE     : 120

Error 7

 DEBUG    : (json-error)
Json error: <unknown source file>:7:22: Failed to visit member map_fontwidth in JsonObject

    "fontsize" : 14,
    "typeface" : "TerminusRus",
    "map_fontwidth" :
                     ^
                      9,
    "map_fontheight" : 15,
    "map_fontsize" : 14,

 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : src/json.cpp
 LINE     : 120

Error 8
 DEBUG    : (json-error)
Json error: <unknown source file>:12:27: Failed to visit member overmap_fontheight in JsonObject

    "map_typeface" : "TerminusRus",
    "overmap_fontwidth" : 9,
    "overmap_fontheight" :
                          ^
                           15,
    "overmap_fontsize" : 14,
    "overmap_typeface" : "TerminusRus"

 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : src/json.cpp
 LINE     : 120

Error 9
 DEBUG    : (json-error)
Json error: <unknown source file>:13:25: Failed to visit member overmap_fontsize in JsonObject

    "overmap_fontwidth" : 9,
    "overmap_fontheight" : 15,
    "overmap_fontsize" :
                        ^
                         14,
    "overmap_typeface" : "TerminusRus"
}

 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : src/json.cpp
 LINE     : 120

Error 10

 DEBUG    : (json-error)
Json error: <unknown source file>:11:26: Failed to visit member overmap_fontwidth in JsonObject

    "map_fontsize" : 14,
    "map_typeface" : "TerminusRus",
    "overmap_fontwidth" :
                         ^
                          9,
    "overmap_fontheight" : 15,
    "overmap_fontsize" : 14,

 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : src/json.cpp
 LINE     : 120

**Comment by Dyuden** [comment]
BTW happy new year everyone

**Comment by Zireael07** [comment]
A crash when reading was recently fixed (as in, today) - did you try updating?

**Comment by Dyuden** [comment]
Just used "update cataclysm" crash while crafting food.

**Comment by Saicchi** [comment]
Loaded in save, tried to craft a recharging station and got the crash.
It seems to be related with auto-eat according to a gdb debug.
![image](https://user-images.githubusercontent.com/47158232/103433414-4998db80-4bcf-11eb-8328-1a13069be643.png)
Might be fixed by #46442

**Comment by Dyuden** [comment]
Hmm it's definetly helps, thank you!
Also errors before main menu caused because I keep config folder from previous installs.
