### ISSUE TITLE
Trojan hidden in latest experimental builds

### ISSUE THREAD

**Issue by NSchultz-professioinal** [CleverRaven/Cataclysm-DDA#46446]
I was downloading the newest experimental build for windows, (#11314), but, for some reason the files weren't extracting. I'd go to the folder where I told them to extract, and only the README and some other text files were present. I tried to download the next newest experimental build (#11313), but got the same issue. That's when my antivirus popped up. Long story short, my antivirus caught a trojan executable in the files, just after they extracted, and deleted them immediately.

EDIT: After further testing, I discovered that my computer detected the trojan files in both the website and github downloads. This only applies to the standard version of the game, not the 64x version.

![Oh_no](https://user-images.githubusercontent.com/73670918/103434429-041be480-4bb6-11eb-9791-3f2c7cd54c2f.PNG)
![Double_oh_no](https://user-images.githubusercontent.com/73670918/103434434-18f87800-4bb6-11eb-884a-64c93dd5a9c8.PNG)
![Triple_oh_no](https://user-images.githubusercontent.com/73670918/103434436-1c8bff00-4bb6-11eb-962f-0c836e69a8ad.PNG)

**Comment by NSchultz-professioinal** [comment]
Note: These experimental builds were downloaded straight from the website (https://cataclysmdda.org/experimental/). I'm going to test it from the github now, and potentially update the post if it's only the website

**Comment by ZhilkinSerg** [comment]
There is no trojan. Antivirus heuristics just sucks.

**Comment by Zireael07** [comment]
Rule of thumb: if the build is new, many AV will flag it. And if the warning says something about heu(ristics), in many cases it's a false positive as Zhilkin says.

**Comment by BrettDong** [comment]
2 out of 69 AVs reported trojan: https://www.virustotal.com/gui/file/977608e8b73d7443ed1cd054f413c4679154ec7bb2ece050ff740ed737962b48/detection

Seems like false positive to me.

**Comment by emptytriangle** [comment]
This has been happening a lot the past month or so with several non-CDDA software packages I used at work and I also saw Windows defender flag the cdda launcher as a virus. Might be something going on around the internet right now. The virus in question here is win32 emotet and the cdda experimental builds are (correct me if I'm wrong) built automatically by Jenkins on Linux, then served from Linux, and I think it's technically impossible for this particular trojan to have infested one of these builds.

**Comment by Qrox** [comment]
[This analysis site](https://www.hybrid-analysis.com/sample/977608e8b73d7443ed1cd054f413c4679154ec7bb2ece050ff740ed737962b48/5fefc417be91ed44941ed4fb) reports that the 32bit executable accesses the `TSUSERENABLED` registry which is remote access related. I'm not sure it really means anything though, it could be that one of the libraries we use does this. @NSchultz-professioinal Maybe you can build the game yourself and see if the AV still reports it as malicious?

**Comment by actual-nh** [comment]
What compressor is used for packaging for Windows? UPX by any chance?

**Comment by ZhilkinSerg** [comment]
> What compressor is used for packaging for Windows? UPX by any chance?

None

**Comment by kevingranade** [comment]
False positive.
