### ISSUE TITLE
Bionic aditional parameters/functions

### ISSUE THREAD

**Issue by Asmitha90** [CleverRaven/Cataclysm-DDA#46459]
# Is your feature request related to a problem? Please describe.

It woud insanly beneficial if you cud add functions like:

"instal if"- set of parameters/rule that coud define requaierments for bionic instalation(other bionics needed/upgrades/traits.etc)
"if instaled"- same as above but woudnt let you instal if any of the conditions is present.

**Comment by Ramza13** [comment]
This could be done easily with #42786 once that is merged.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
