### ISSUE TITLE
(bionic)"weight_capacity_bonus" - Dosent suport negative value

### ISSUE THREAD

**Issue by Asmitha90** [CleverRaven/Cataclysm-DDA#46450]
# Describe the bug
When i try to add negative value to this line it dosent work. 
Documentation says it is posible and if not plz add suport for flat negative value.

# Steps To Reproduce

Add bionic with "weight_capacity_bonus": "-5000 g"

# Expected behavior

Shoud add flat negative value, insted spits error.

# Screenshots

![Bez tytułu](https://user-images.githubusercontent.com/76838648/103438169-73361f00-4c30-11eb-854a-078b3201bfd5.jpg)

**Comment by ZhilkinSerg** [comment]
Yeah, the loading code sets minimum supported value to `0_gram`:

https://github.com/CleverRaven/Cataclysm-DDA/blob/6a600db18e23756b8e07116b89161393e5d5b177/src/bionics.cpp#L274

**Comment by Owlblocks** [comment]
I'll take a look at it. Shouldn't be too hard.

**Comment by Owlblocks** [comment]
> I think these zero values for `weight_capacity_bonus` and surrounding parameters were meant to be default values, not minimum supported values, thus they need to be removed.

@ZhilkinSerg Do you think there are any other parameters that need to be changed(The weight capacity bonus was as easy as changing that 0_gram value you mentioned)? The documentation, as Asmitha90 pointed out, does specify that negative values are allowed for the weight_capacity_bonus, and I would assume that specification means that the others aren't intended to allow negative values, as none of the others I saw explicitly mentioned it.
