### ISSUE TITLE
Bionic instal interface 

### ISSUE THREAD

**Issue by Asmitha90** [CleverRaven/Cataclysm-DDA#46457]
# Describe the bug

Sotry for my bad english.

So im working on bionics and i have a parten bionic that splits into 2 other types (light and heavy wariant). Both H and L variant then can be upgraded in H mk.2 and L mk.2 but to block the ability of instaling base type agin when mk.2 is instaled or if one of the variants is instaled instaled it requaiers  to do some wonky stuff.

# Steps To Reproduce
Code that im using(im new to this so maybe theres a beter way):

 Item code:

{
    "id": "trans_storage_base",
    "copy-from": "bionic_general_npc_usable",
    "type": "BIONIC_ITEM",
    "name": { "str": "Prototype Energy Storage" },
    "looks_like": "bio_int_enhancer",
    "description": "x",
    "price": 380000,
    "weight": "3000 g",
    "difficulty": 1
},
{
    "id": "trans_storage_lightI",
    "copy-from": "bionic_general_npc_usable",
    "type": "BIONIC_ITEM",
    "name": { "str": "trans_storage_lightI" },
    "looks_like": "bio_int_enhancer",
    "description": "x",
    "price": 580000,
    "weight": "2500 g",
    "is_upgrade" : true,
    "difficulty": 1
},
{
    "id": "trans_storage_lightII",
    "copy-from": "bionic_general_npc_usable",
    "type": "BIONIC_ITEM",
    "name": { "str": "trans_storage_lightII" },
    "looks_like": "bio_int_enhancer",
    "description": "x",
    "price": 580000,
    "weight": "1500 g",
    "is_upgrade" : true,
    "difficulty": 1
},
{
    "id": "trans_storage_heavyI",
    "copy-from": "bionic_general_npc_usable",
    "type": "BIONIC_ITEM",
    "name": { "str": "trans_storage_heavyI" },
    "looks_like": "bio_int_enhancer",
    "description": "x",
    "price": 580000,
    "weight": "2500 g",
    "is_upgrade" : true,
    "difficulty": 1
},
{
    "id": "trans_storage_heavyII",
    "copy-from": "bionic_general_npc_usable",
    "type": "BIONIC_ITEM",
    "name": { "str": "trans_storage_heavyII" },
    "looks_like": "bio_int_enhancer",
    "description": "x",
    "price": 580000,
    "weight": "2500 g",
    "is_upgrade" : true,
    "difficulty": 1
}

Bionic code:

{
    "id": "trans_storage_base",
    "type": "bionic",
    "name": { "str": "Prototype Energy Storage" },
    "available_upgrades": [ "trans_storage_lightI", "trans_storage_lightII", "trans_storage_heavyI", "trans_storage_heavyII" ],
    "encumbrance": [ [ "torso", 5 ] ],
    "weight_capacity_bonus": "3000 g",
    "capacity": "75 kJ",
    "description": "x",
    "flags": [ "BIONIC_NPC_USABLE" ]
},
{
    "id": "trans_storage_lightI",
    "type": "bionic",
    "name": { "str": "trans_storage_lightI" },
    "available_upgrades": [ "trans_storage_lightII" ],
    "upgraded_bionic": "trans_storage_base",
    "encumbrance": [ [ "torso", 4 ] ],
    "weight_capacity_bonus": "2500 g",
    "capacity": "30 kJ",
    "description": "x",
    "flags": [ "BIONIC_NPC_USABLE" ]
},
{
    "id": "trans_storage_lightII",
    "type": "bionic",
    "name": { "str": "trans_storage_lightII" },
    "upgraded_bionic": "trans_storage_lightI",
    "encumbrance": [ [ "torso", 3 ] ],
    "weight_capacity_bonus": "1500 g",
    "capacity": "50 kJ",
    "description": "x",
    "flags": [ "BIONIC_NPC_USABLE" ]
},
{
    "id": "trans_storage_heavyI",
    "type": "bionic",
    "name": { "str": "trans_storage_heavyI" },
    "available_upgrades": [ "trans_storage_heavyII" ],
    "upgraded_bionic": "trans_storage_base",
    "encumbrance": [ [ "torso", 7 ] ],
    "weight_capacity_bonus": "5000 g",
    "capacity": "70 kJ",
    "description": "x",
    "flags": [ "BIONIC_NPC_USABLE" ]
},
{
    "id": "trans_storage_heavyII",
    "type": "bionic",
    "name": { "str": "trans_storage_heavyII" },
    "upgraded_bionic": "trans_storage_heavyI",
    "encumbrance": [ [ "torso", 6 ] ],
    "weight_capacity_bonus": "3900 g",
    "capacity": "125 kJ",
    "description": "x",
    "flags": [ "BIONIC_NPC_USABLE" ]
}

# Expected behavior

When instaled shoud say that:
mk.1-superior version instaled
mk.1/mk.2 of the other type- dont know, since no one can help me or dosent know if theres a mututaly exclusive function so this may be a feature that needs to be added like.

# Screenshots

![Bez tytułu1](https://user-images.githubusercontent.com/76838648/103442222-9246a800-4c54-11eb-80d4-a8925cc0fbd3.jpg)

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
