### ISSUE TITLE
Cannot (a)ctivate certain items

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#46468]
# Describe the bug

Attempting to `a`ctivate cattail jelly and antiseptic results in a "This is full of dirt after being on the ground" message, even though the items were contained, and drops a unit of the item on the ground.

# Steps To Reproduce

1. Load attached save.
2. Attempt to activate antiseptic.

# Expected behavior

I expected the game to apply the antiseptic.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 20H2 (build 19042.685)
- Game Version: 0.E-8560-ga3bf351 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded:
    - Dark Days Ahead [dda],
    - No Fungal Monsters [No_Fungi],
    - Disable NPC Needs [no_npc_food],
    - C.R.I.T Expansion Mod [crt_expansion],
    - Alternative Map Key [alt_map_key],
    - No Rail Stations [No_Rail_Stations],
    - Fuji's Military Professions Pack [fuji_mpp],
    - SpeedyDex [speedydex],
    - Stats Through Kills [stats_through_kills],
    - Stats Through Skills [StatsThroughSkills]

# Additional context

[Fort Bidwell.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5759533/Fort.Bidwell.zip)

**Comment by Angustmeta** [comment]
Yeah it seems you can't (a)ctivate antiseptics at all right now. 

![210102 0053 34](https://user-images.githubusercontent.com/46400996/103448127-4c5e0400-4c95-11eb-8cdb-374cbde2d299.png)

**Comment by BrettDong** [comment]
As a temporary workaround, antiseptic can be used in `E`at menu.

**Comment by BrettDong** [comment]
Seems like a bug related to containers. When using antiseptic through `a`ctivate, the player tries to obtain one charge of liquid to his/her inventory and fails. The liquid drops on the ground, becomes dirty so it cannot be used.

**Comment by ToxiClay** [comment]
Do you think it'd be a good idea to walk through the builds and try to find where this behavior was introduced?

**Comment by BrettDong** [comment]
I'm doing bisection right now

**Comment by BrettDong** [comment]
Broken by 18a045f3b230ec0d84f29ff3259bc2f367b3c5df in #46400:
```diff
diff --git a/src/avatar_action.cpp b/src/avatar_action.cpp
index f49ca08460..defb4243d8 100644
--- a/src/avatar_action.cpp
+++ b/src/avatar_action.cpp
@@ -1019,7 +1019,7 @@ void avatar_action::use_item( avatar &you, item_location &loc )
         // Adjustment because in player::wield_contents this amount is refunded.
         you.mod_moves( -loc.obtain_cost( you ) );
     } else {
-        loc = loc.obtain( you );
+        loc = loc.obtain( you, 1 );
         if( !loc ) {
             debugmsg( "Failed to obtain target item" );
             return;
```

**Comment by BrettDong** [comment]
Ping @Ramza13

**Comment by PaulBlay** [comment]
Is the the same problem as turned up with siphoning gasoline? https://github.com/CleverRaven/Cataclysm-DDA/issues/46483 

It's not 'a'pplying, but it seems like an odd coincidence.

**Comment by BrettDong** [comment]
>Is the the same problem as turned up with siphoning gasoline? 

They are not relevant.
