### ISSUE TITLE
Misleading message "there are no damaged parts on this vehicle"

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#46461]
# Describe the bug

When you attempt to (r)epair a vehicle you may be given the message "there are no damaged parts on this vehicle" when what it actually means is "there are no damaged parts on this vehicle that you can repair".

# Steps To Reproduce

1. (e)xamine a damaged vehicle
2. Make sure that the location of the vehicle you are looking at does not have any damage.
3. Make sure that you do not have the required tools / clothing to repair vehicle damage.
4. Attempt to (r)epair

The message "There are no damaged parts on this vehicle" will be displayed in the right panel of the screen.

5. Now go get the tools / clothing you need to repair damage.
6. (e)xamine the vehicle again
7. Attempt to (r)epair

The location of the vehicle you are looking at will switch to one with damage.
Selecting (r)epair again will highlight a damaged vehicle part
Selecting (r)epair or [Enter] will cause you to start repairing the vehicle part.

# Expected behavior

It should switch the location of the vehicle you are looking at to one with damage.
Selecting (r)epair again should highlight a damaged vehicle part [that you cannot repair]
Selecting (r)epair or [Enter] should do nothing - but the right panel of the screen will have highlighted in red why you cannot repair it (lack of skill, part, or tools)

# Versions and configuration

- OS: Windows x64 8.1
- Game Version: 0.E-8531-gea3e6a3 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

**Comment by Svankensen** [comment]
This behaviour is quite desirable. When repairing your deathsmobile after a running session, it is very convenient to just hit R until you cannot repair anything anymore, then check what else, if anything, is damaged in the "most damaged" part of the menu. The message should be changed tho.

**Comment by PaulBlay** [comment]
@Svankensen If you changed the behaviour as I suggested you could do the exact same thing only you hit the 'stop' condition with a |\ roof highlighted and no charges in your Arc Welder instead of a message saying you've finished repairing everything.

**Comment by Svankensen** [comment]
What you describe doesn't consider if there are other parts that can currently be repaired with what you have.

**Comment by PaulBlay** [comment]
> What you describe doesn't consider if there are other parts that can currently be repaired with what you have.

You can get an 'early stop' but only when there is something you can't repair on the location you are currently looking at (hence the reason for step 2 in the 'reproduce this bug' section). You will also get the exact same 'early stop' with your method. Otherwise read from step 5 to 7.

**Comment by PaulBlay** [comment]
Just found out in the latest experimental build that somebody fixed this. So, thanks, nameless coder!
