### ISSUE TITLE
Putting broth from a plastic bottle into a 3L jar has odd results

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#46470]
# Describe the bug

I had several bottles of broth. Putting one of the bottles into a 3L jar gave it the `(fresh)` tag, and prevented me from putting more in. The other bottles all worked, though. I made all the bottles at the same time, so I don't know exactly what happened.

# Steps To Reproduce

1. Load save
2. Observe that the broth in the jar has the `(fresh)` tag.
3. Try to put more broth into it.

# Expected behavior

# Screenshots

![image](https://user-images.githubusercontent.com/13796683/103448159-77c7fb00-4c63-11eb-9346-8d4326dbe988.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 20H2 (build 19042.685)
- Game Version: 0.E-8560-ga3bf351 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded:
    - Dark Days Ahead [dda],
    - No Fungal Monsters [No_Fungi],
    - Disable NPC Needs [no_npc_food],
    - C.R.I.T Expansion Mod [crt_expansion],
    - Alternative Map Key [alt_map_key],
    - No Rail Stations [No_Rail_Stations],
    - Fuji's Military Professions Pack [fuji_mpp],
    - SpeedyDex [speedydex],
    - Stats Through Kills [stats_through_kills],
    - Stats Through Skills [StatsThroughSkills]

# Additional context

[Fort Bidwell.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5759574/Fort.Bidwell.zip)

**Comment by PaulBlay** [comment]
I bet this is another variant on the 'differing component' thing. In a previous issue some clean water with the component 'water COOKED' somehow lost the component information. If the same thing happened to just one of your bottles of broth that broth would no longer be able to combine with the other broth.

P.S. I have said component so many times it has ceased to have any meaning to me.

**Comment by ToxiClay** [comment]
> P.S. I have said component so many times it has ceased to have any meaning to me.

Semantic satiation is a hell of a thing.

**Comment by PaulBlay** [comment]
I had a look at the save file, and am now super confused.

There are exactly six matches for "typeid":"broth" in 40.57.0.map but all of them are in plastic bottles. However when you load it, there are clearly five plastic bottles with broth in them and one 3L jar with broth in it.

**Comment by ToxiClay** [comment]
Wow, that bottom one is a hell of a lot longer. What happened?

**Comment by PaulBlay** [comment]
> Wow, that bottom one is a hell of a lot longer. What happened?

Basically, the top one lost all the components. I wonder if it was sheer co-incidence that it happened at the same time it cooled down from HOT?

I got a bit muddled so the text I pasted above isn't exactly what you'll find in your save file. It's a long-ish story, which I will skip.

It might be worth seeing what happens if you pour more of your plastic bottle HOT broth into 3L jars to see if they also cool down and lose their 'cabbage COOKED, soy sauce' information.

**Comment by anothersimulacrum** [comment]
Linted so you can actually see what's going on.
The components should not need to be saving full items here, like it appears to be.
```
[
  {
    "typeid": "bottle_plastic",
    "bday": 5213804,
    "owner": "your_followers",
    "last_temp_check": 0,
    "relic_data": null,
    "contents": {
      "contents": [
        {
          "pocket_type": 0,
          "contents": [
            {
              "typeid": "broth",
              "charges": 2,
              "bday": 6671236,
              "owner": "your_followers",
              "active": true,
              "last_temp_check": 6671236,
              "specific_energy": 85015176,
              "temperature": 28370556,
              "relic_data": null,
              "contents": {
                "contents": [
                  { "pocket_type": 4, "contents": [  ], "_sealed": false },
                  { "pocket_type": 3, "contents": [  ], "_sealed": false },
                  { "pocket_type": 6, "contents": [  ], "_sealed": false }
                ]
              }
            }
          ],
          "_sealed": false
        },
        { "pocket_type": 4, "contents": [  ], "_sealed": false },
        { "pocket_type": 3, "contents": [  ], "_sealed": false },
        { "pocket_type": 6, "contents": [  ], "_sealed": false }
      ]
    }
  },
  {
    "typeid": "bottle_plastic",
    "owner": "your_followers",
    "last_temp_check": 0,
    "relic_data": null,
    "contents": {
      "contents": [
        {
          "pocket_type": 0,
          "contents": [
            {
              "typeid": "broth",
              "charges": 1,
              "bday": 6670922,
              "owner": "your_followers",
              "active": true,
              "rot": 210465,
              "last_temp_check": 6670922,
              "item_tags": [ "HOT" ],
              "components": [
                {
                  "typeid": "cabbage",
                  "charges": 1,
                  "bday": 6288101,
                  "owner": "your_followers",
                  "active": true,
                  "rot": 310412,
                  "last_temp_check": 6665180,
                  "item_tags": [ "COOKED" ],
                  "specific_energy": 84829968,
                  "temperature": 28323068,
                  "relic_data": null,
                  "contents": {
                    "contents": [
                      { "pocket_type": 4, "contents": [  ], "_sealed": false },
                      { "pocket_type": 3, "contents": [  ], "_sealed": false },
                      { "pocket_type": 6, "contents": [  ], "_sealed": false }
                    ]
                  }
                },
                {
                  "typeid": "soysauce",
                  "charges": 2,
                  "owner": "your_followers",
                  "active": true,
                  "last_temp_check": 6665067,
                  "item_tags": [ "COOKED" ],
                  "specific_energy": 101395152,
                  "temperature": 28337726,
                  "relic_data": null,
                  "contents": {
                    "contents": [
                      { "pocket_type": 4, "contents": [  ], "_sealed": false },
                      { "pocket_type": 3, "contents": [  ], "_sealed": false },
                      { "pocket_type": 6, "contents": [  ], "_sealed": false }
                    ]
                  }
                },
                {
                  "typeid": "water",
                  "charges": 1,
                  "bday": 5742033,
                  "owner": "your_followers",
                  "active": true,
                  "last_temp_check": 6665067,
                  "item_tags": [ "COOKED" ],
                  "specific_energy": 95665416,
                  "temperature": 28458190,
                  "relic_data": null,
                  "contents": {
                    "contents": [
                      { "pocket_type": 4, "contents": [  ], "_sealed": false },
                      { "pocket_type": 3, "contents": [  ], "_sealed": false },
                      { "pocket_type": 6, "contents": [  ], "_sealed": false }
                    ]
                  }
                }
              ],
              "specific_energy": 104298496,
              "temperature": 33314999,
              "relic_data": null,
              "contents": {
                "contents": [
                  { "pocket_type": 4, "contents": [  ], "_sealed": false },
                  { "pocket_type": 3, "contents": [  ], "_sealed": false },
                  { "pocket_type": 6, "contents": [  ], "_sealed": false }
                ]
              }
            }
          ]
        }
      ]
    }
  }
]
```

**Comment by ToxiClay** [comment]
Wow. I am thoroughly confused. I understand on some level why items want to keep their component information around, for nutrition tracking, but...I wonder if it'd be a better idea to discard that information to avoid weird nonsense like this.

**Comment by int-ua** [comment]
Can cooked items just save the resulting sums of the components? Calories, vitamins, quench, what else?

**Comment by PaulBlay** [comment]
I think the bit about loss of component information may be fixed by this PR
https://github.com/CleverRaven/Cataclysm-DDA/pull/46836

**Comment by ToxiClay** [comment]
Yeah, it looks like this might do it!

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
