### ISSUE TITLE
In progress disassembly on a workbench

### ISSUE THREAD

**Issue by Digi1980s** [CleverRaven/Cataclysm-DDA#46482]
In progress disassembly on a workbench vanishes, or can't be continued because you don't know the recipe.

By putting a in progress disassembly of camera on a workbench then working on craft, this camera disappears completely. 

In progress disassembly of leggings on a workbench eventually returns "You don't know the recipe for the leggings and can't continue crafting".

# Steps To Reproduce
1. Make a player with a camera or a pair of leggings.
2. Disassemble this item, and store it in your inventory.
3. Drop the in progress disassembly of item on a workbench.
4. Work on craft.
5. Now the camera has gone, or you stop working because you don't know the recipe.

# Expected behavior
Finishing disassembly, regardless of components drop or not. If you disassembly it directly in the inventory, the result will be normal. 

# Screenshots

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-8640-gf8cbc0c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context
 DEBUG    : invalid recipe id "camera"

 FUNCTION : const T& string_id<T>::obj() const [with T = recipe]
 FILE     : src/recipe_dictionary.cpp
 LINE     : 66

**Comment by PaulBlay** [comment]
Is this the same as https://github.com/CleverRaven/Cataclysm-DDA/issues/46481 ?

**Comment by Digi1980s** [comment]
> Is this the same as #46481 ?

I believe it is the same.
