### ISSUE TITLE
Serious disassembly bug

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#46481]
# Describe the bug

Under certain conditions, items being disassembled can vanish into the aether, taking the item and its components with it.

# Steps To Reproduce

1. Load attached save.
2. Observe that on the table is `in progress disassembly of flashlight (off) (0%)`.
3. `e`xamine the table and select `4 Work on craft`.
4. Marvel as CDDA opens a yawning portal to the abyss and swallows the items whole.
5. Reload the save.
6. Instead, `a`ctivate the in-progress disassembly, and the abyss will not take your items.

# Expected behavior

I expected the game to give me the components no matter what.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 20H2 (build 19042.685)
- Game Version: 0.E-8560-ga3bf351 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded:
    - Dark Days Ahead [dda],
    - No Fungal Monsters [No_Fungi],
    - Disable NPC Needs [no_npc_food],
    - C.R.I.T Expansion Mod [crt_expansion],
    - Alternative Map Key [alt_map_key],
    - No Rail Stations [No_Rail_Stations],
    - Fuji's Military Professions Pack [fuji_mpp],
    - SpeedyDex [speedydex],
    - Stats Through Kills [stats_through_kills],
    - Stats Through Skills [StatsThroughSkills]

# Additional context

What I suspect might be happening is the game is mishandling what "work on craft" does, expecting that it will return a finished crafting product instead of disassembled components.

**Comment by BrettDong** [comment]
> Load attached save.

You missed attaching your save here.

**Comment by ToxiClay** [comment]
Oh, hell. Gimme a sec....

**Comment by ToxiClay** [comment]
[Fort Bidwell.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5760284/Fort.Bidwell.zip)
