### ISSUE TITLE
I drowned while driving my car submerged in the ground

### ISSUE THREAD

**Issue by Salty-Panda** [CleverRaven/Cataclysm-DDA#46488]
# Describe the bug

I parked my car using the remote control: part on the ground, part on the shallow water, and part on the deep water.
Inside the car, when I tried to move from shallow water to deep water (driver seat) I got prompt if I want to dive.
"Yes", I sank like stone, activated the vehicle, drove back on the ground, started drowning, died.

# Steps To Reproduce

Inside the car move onto another tile in a such way that it will take you from shallow to deep water. (possibly the car also has to be partially on the ground tiles)
After activating the controls and driving you still will be considered submerged and can drown, even after moving onto the ground.
(Attached save from just before moving on the deep water)

# Expected behavior

Whatever happens, you can't dive in while walking on boardable/movable vehicle tiles.

# Screenshots

![image](https://user-images.githubusercontent.com/26396019/103460168-6e4a9b80-4d14-11eb-8171-8966eef71f2c.png)
![image](https://user-images.githubusercontent.com/26396019/103460172-773b6d00-4d14-11eb-809f-fde62dba382e.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-8536-g9c2c35a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Mythical Martial Arts [MMA],
    C.R.I.T Expansion Mod [crt_expansion],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Bionic Professions [package_bionic_professions],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP]
]

# Additional context
[my_yellow_submarine.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5760425/my_yellow_submarine.zip)

**Comment by Aivean** [comment]
I believe I checked similar scenario when testing #46040 or #46041.

I think diving inside the partially submerged vehicle makes sense. Think of it in the following way: if the vehicle is not floatation-capable it becomes partially submerged (there is logic that determines the part of the vehicle area that is located on the deep water tiles) and the water gets inside:

<img src="https://user-images.githubusercontent.com/2865203/103467847-258ce580-4d08-11eb-8b4c-de2317e1744d.png" width=300>

The buggy part is that you can't recover from this situation when you drive out. Probably has to do something with incorrect `vehicle::in_water` cache recalculation.

**Comment by Theawesomeboophis** [comment]
> I believe I checked similar scenario when testing #46040 or #46041.
> 
> I think diving inside the partially submerged vehicle makes sense. Think of it in the following way: if the vehicle is not floatation-capable it becomes partially submerged (there is logic that determines the part of the vehicle area that is located on the deep water tiles) and the water gets inside:
> 
> <img alt="" width="300" src="https://user-images.githubusercontent.com/2865203/103467847-258ce580-4d08-11eb-8b4c-de2317e1744d.png">
> 
> The buggy part is that you can't recover from this situation when you drive out. Probably has to do something with incorrect `vehicle::in_water` cache recalculation.

It depends on how long you're submerged, the windows could have cracked from pressure and let an excess amount of water through, causing the character to die later on because there's still possibly water in the car. ( Might be intentional, not sure due to how easily car windows crack in real life, not sure if it's the same in game, most likely a bug though).

**Comment by Fosheze** [comment]
I believe I found a related issue. If you have a boat that is parked partially on shallow water and partially on deep water and you move between the two while standing on the boat it will still ask you if you want to dive into the deep water. If you select yes you will be under water while still standing on your boat. The boat wasn't overloaded and did float when parked solely on deep water. This behavior does not exist when the boat is parked solely on deep water either.

**Comment by Salty-Panda** [comment]
Yes, it's exactly the same bug, boats work the same way as any other vehicle.

**Comment by YukioDjo** [comment]
I made an amphibian and calmly ride and swim, but the bug remained.  + to everyone why do we get a fine from the land if we are in the car?

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-11128.
