### ISSUE TITLE
Repeated text in Advanced Reaper description

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#46484]
# Describe the bug

There is a repeated sentence in the Advanced Reaper description text.

# Steps To Reproduce

1. Look at an advanced reaper installed in a vehicle.

An automatic reaper.  Use the vehicle controls to turn it on or off.  When turned on, it will stop the vehicle unless it has a strong engine.  When on, it will cut down plants and store them in the vehicle's cargo.  It should be placed in front of any plows in the vehicle for efficient operation.  It has internal cargo space for collecting the harvest. When turned on, it will stop the vehicle unless it has a strong engine.  

# Expected behavior

You only need to say   "When turned on, it will stop the vehicle unless it has a strong engine." once.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-8531-gea3e6a3 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

# Additional context

The problem is that the description text includes text that is also given by the EXTRA_DRAG flag

```
  {
    "id": "EXTRA_DRAG",
    "type": "json_flag",
    "context": [ "vehicle_part" ],
    "info": "When turned on, it will stop the vehicle unless it has a strong engine."
  },
```

**Comment by PaulBlay** [comment]
Notices 'Good First Issue' tag. Feels conflicted.  

I'm happy that I managed to get a 'Good'. But this is like my twenty-something-th issue submitted?

**Comment by Zireael07** [comment]
'Good first issue' means it's a good first issue for a new contributor to tackle/fix (someone new to Godot's codebase)

**Comment by actual-nh** [comment]
"Good First Issue" does qualify as, umm, slightly confusing on first sight. (IMO, it can also be described as issues that someone with slightly more experience can do even if they're low on time...)
