### ISSUE TITLE
Specify collection vs distribution in use location (e.g., death drops) of item groups

### ISSUE THREAD

**Issue by actual-nh** [CleverRaven/Cataclysm-DDA#46496]
# Is your feature request related to a problem? Please describe.

To be most usable, item groups should be located in someplace central (i.e., the `itemgroups` directory). However, one problem with this is that one can get a collection when one meant a distribution, and vice-versa. (See #46495 for where I made this error.)

# Describe the solution you'd like
Be able to specify in use of an item group that it should be a collection or a distribution, and give an error if this is not the case.

# Describe alternatives you've considered
Making a collection/distribution behave like the other if needed (instead of an error).

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
