### ISSUE TITLE
Faction names and descriptions impossible (?) to translate

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#4651]
The way how faction names are generated is way too English-centric. It contains many word fragments which often are only meaningful in the English language.

I, as a translator, have no idea how to translate faction names. This is because the way how faction names are generated seem to assume a certain Grammar which is the English one. This system completely falls apart for other languages.

I am aware that factions are more or less on hold right now. But when the time has come that factions are being developed, I strongly suggest to start the name generator from scratch, but this time, with taking other languages into account.

Tested in: 0.9
##

**Comment by BrettDong** [comment]
@illi-kun This issue can be closed.

Now faction names and descriptions have been moved into `data/json/npcs/factions.json` and they are all translated normally.

```
#. ~ Description for The Wasteland Scavengers
#: lang/json/faction_from_json.py
msgid ""
"Autonomous bands or individuals who make their living raiding the ruins of "
"the old-world for gear and provisions."
msgstr "各自为政的个人、团伙，在旧世界的废墟中谋生，搜寻着各种装备和给养。"
```

**Comment by AMurkin** [comment]
`faction::describe()` not using translation for some strings

- `name.c_str()`
- `facgoal_data[goal].name.c_str()`

**Comment by BrettDong** [comment]
Thanks for pointing them out. I'll look into them in the weekend.
