### ISSUE TITLE
Error message on towed vehicle rammed with tower vehicle on sudden brake

### ISSUE THREAD

**Issue by BrettDong** [CleverRaven/Cataclysm-DDA#46517]
# Describe the bug
An error message pops up when towed vehicle and tower vehicle collide with each other violently.

# Steps To Reproduce
<del>0. Apply #46508 to reveal this issue</del>
1. Spawn a heavy duty cargo truck
2. Spawn a Beetle behind
3. Spawn a heavy duty tow cable
4. Link two vehicles with tow cable
5. Drive cargo truck, speed up to 64 km/h, drive for a little while so Beetle also gains the speed
6. Suddenly decrease target speed to -64 km/h
7. Observe cargo truck slows down in a sudden and Beetle collides with cargo truck
8. Debug message pops up

# Expected behaviour
Shouldn't cause an error message.

# Screenshots
<img width="1072" alt="螢幕截圖 2021-01-03 上午9 52 58" src="https://user-images.githubusercontent.com/21075502/103481885-8c170f80-4dab-11eb-9b7a-22268bb977e5.png">

# Versions and configuration
 - OS: macOS 11.1
 - Game Version: <del>`HEAD` in PR #46508</del> latest `master`
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: DDA

# Additional context
None

**Comment by mlangsdorf** [comment]
I think what is happening here is the tow cable is being destroyed (on the towing vehicle) without clearing the towed effect on the towing vehicle.  I'll try to track down the logic soonish.

**Comment by actual-nh** [comment]
Would it be a problem to change, at least in the debug messages but preferably elsewhere, "tower" (vehicle) to "towing"? It is otherwise a tad bit confusing when, for instance, doing a grep (and I am guessing would make any messages to the player - non-debug - harder to translate properly).

**Comment by mlangsdorf** [comment]
That's a sensible change; I'll do it if someone else doesn't in the near future.
