### ISSUE TITLE
Game erroneously indicates usable component

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#46515]
# Describe the bug

Lamp oil recipe indicates that rotten tainted fat is usable, but it is not.

# Steps To Reproduce

1. Load attached save
2. Note 13 `tainted fat (rotten)` 1N.
3. Open `&` menu and look at the lamp oil recipe. Observe that it indicates that the tainted fat is usable.
4. Initiate crafting.
5. Note that the game no longer indicates that the tainted fat is a valid ingredient.

# Expected behavior

I expected consistency in the display.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 20H2 (build 19042.685)
- Game Version: 0.E-8659-g4c521a8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded:
    - Dark Days Ahead [dda],
    - C.R.I.T Expansion Mod [crt_expansion],
    - No Fungal Monsters [No_Fungi],
    - Disable NPC Needs [no_npc_food],
    - Alternative Map Key [alt_map_key],
    - SpeedyDex [speedydex],
    - Stats Through Kills [stats_through_kills],
    - Stats Through Skills [StatsThroughSkills]

# Additional context

This behavior means that the underlying behavior intended to be added by PR #29808 was not actually implemented or later regressed (even though the JSON says it is!), and the problem went unnoticed ever since. The aberrance is likely to be found in `\src\crafting.cpp`, but I'm not able to tease it out.

[Woodcock.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5761595/Woodcock.zip)

**Comment by actual-nh** [comment]
It looks like it would be helpful for whoever fixes this to add a test for it...

**Comment by ToxiClay** [comment]
Hm. I just tested it in `0.E-8852-gf360c7f` and it appears to work now. Or it always did, and I'm just dumb.
