### ISSUE TITLE
Cant play on any world

### ISSUE THREAD

**Issue by RedBloodCat** [CleverRaven/Cataclysm-DDA#46512]
# Describe the bug
Cant play on any of my worlds, tried to make a new world and character but still cant play, also happens when i try to play defense or tutorial. The error is the same for all the worlds. It should be noted that the bug made it so that i couldn't make a character on the new world as it gives me an error before it is in.

# Steps To Reproduce
Load a character

# Expected behavior
Load the character 

# Screenshots
 DEBUG    : Error: Json error: <unknown source file>:17569:31: Additional tiles defined, but 'multitile' is not true.

          "rotates": false,
          "multitile": false,
          "additional_tiles": [
                              ^

            {
              "id": "overlay_wielded_corner",

 FUNCTION : bool main_menu::load_character_tab(bool)
 FILE     : src/main_menu.cpp
 LINE     : 1146

# Versions and configuration
OS: Windows 10
Game Version: 11328
Graphics Version: Tiles
Game Language: English [en]
Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
] Are on all of my world saves, but some of them have other mods also

 # Additional context
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5761373/debug.log)

**Comment by Fris0uman** [comment]
Update your tileset or use one included with the game.

**Comment by anothersimulacrum** [comment]
If you are using a first party tileset, please let me know, and I will re-open this, but those were all updated and only third party tilesets will be having this issue, AFAIK.

**Comment by RedBloodCat** [comment]
To be honest i have no idea, i haven't changed any settings when the bugged appeared. I just redownloaded the launcher and updated the game and lunched it.

**Comment by anothersimulacrum** [comment]
What tileset do you use?

**Comment by RedBloodCat** [comment]
ehhh

**Comment by RedBloodCat** [comment]
found it i think "MSX++DEAD_PEOPLE"

**Comment by anothersimulacrum** [comment]
Yep, that's a third party tileset.
