### ISSUE TITLE
Fatigue leads to freezing to death

### ISSUE THREAD

**Issue by Venera3** [CleverRaven/Cataclysm-DDA#46516]
# Describe the bug

While working on a fix for #45113 I stumbled upon sleepiness automagically causing you to get colder. This is generally manageable in the 0-1000 ( lower bound for Exhausted ) range, topping out at -30 degrees, but when fatigue continues to rise it causes you to get colder than outer space.

# Steps To Reproduce

1.Create a character, noting the warmth value
2. Raise the fatigue with the debug menu and wait a few turns to update the temperature
3. Note inexplicable cooling out

# Expected behavior

Loss of temperature bottoming out at 0K. Being tired not actually causing your limbs to fall off.

# Screenshots

![Fatigue0](https://user-images.githubusercontent.com/72006894/103480869-57b94880-4dd7-11eb-9fde-7aa4e3d796a2.png)
0 Fatigue
![Fatigue1000](https://user-images.githubusercontent.com/72006894/103480872-5b4ccf80-4dd7-11eb-9361-d396d12d4405.png)
1000 Fatigue
![Fatigue10000](https://user-images.githubusercontent.com/72006894/103480873-5daf2980-4dd7-11eb-91bb-7fabb3a6e4ff.png)
10000 Fatigue

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-8634-g91698b261b [32-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
If you can't counteract the cold in a meaningful way this can get you into a death spiral of being cold because of a lack of sleep despite acceptable environmental temp and not being able to sleep to solve it.

**Comment by Mrzjadacz** [comment]
In character.cpp:
`void Character::update_bodytemp()` function has responsible fragment:
```
    // Fatigue
    // ~-900 when exhausted
    const int fatigue_warmth = has_sleep ? 0 : static_cast<int>( std::min( 0.0f,
                               -1.5f * get_fatigue() ) );
```

**Comment by actual-nh** [comment]
> # Expected behavior
> Loss of temperature bottoming out at 0K.

Heh. Rather before that, really - no lower than environmental temperature.

> Being tired not actually causing your limbs to fall off.

Quite.

**Comment by anothersimulacrum** [comment]
This is an easy C++ fix, it just requires clamping the fatigue warmth above between zero and some sensible negative value.

**Comment by actual-nh** [comment]
Any suggestions for a sensible negative value?

**Comment by anothersimulacrum** [comment]
`1.5 * 900 = 1350` I don't know if it's the value it should be, but it's just going off the comment above.

**Comment by BrettDong** [comment]
> const int fatigue_warmth = has_sleep ? 0 : static_cast<int>( clamp( -1.5f * get_fatigue(), 0.0f, -1350.0f ) );

Shouldn't it be
```c++
const int fatigue_warmth = has_sleep ? 0 : static_cast<int>( clamp( -1.5f * get_fatigue(), -1350.0f, 0.0f ) );
```
?

**Comment by anothersimulacrum** [comment]
Probably, yes.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/pc-is-way-too-cold/25730/4

**Comment by Jamuro-g** [comment]
seems someone already fixed this one ...

-34 with 1000 fatique and waited for an hour in case it grew:
![image](https://user-images.githubusercontent.com/76928284/107498626-56c4c500-6b94-11eb-9ae7-3e1f518f8864.png)

**Comment by Venera3** [comment]
One hour doesn't lead to noticeable accumulation of fatigue ( it takes about 12 hours to get up to 200, the lower bound for Tired iirc) so you wouldn't see any effect on the temp. The different temperature is a bit weirder. Could you set it to 10000 and report back, like in the last screenie?

**Comment by Salty-Panda** [comment]
The code responsible for the bug has no changed
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/character.cpp#L6526

**Comment by Jamuro-g** [comment]
> One hour doesn't lead to noticeable accumulation of fatigue ( it takes about 12 hours to get up to 200, the lower bound for Tired iirc) so you wouldn't see any effect on the temp. The different temperature is a bit weirder. Could you set it to 10000 and report back, like in the last screenie?

ah my bad, i thought the last screenshot was at 1k fatique.
set it to 10k and yeah it still happens:
![image](https://user-images.githubusercontent.com/76928284/107536525-28f67500-6bc2-11eb-9e1f-6be34288772e.png)

compiling the clamped version now
