### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by RedBloodCat** [CleverRaven/Cataclysm-DDA#46510]
# Describe the bug
When i lunch the game i get an multiple error message. I can still play as long as i ignore it (aka. press i)

# Steps To Reproduce
Start up the game

# Expected behavior
start up without an error

# Versions and configuration

<!-- Please complete the following information; you can now go to:
    - "Main menu (ESC) > Debug Menu > Info > Generate game report" to generate this report.
    - Please update your OS version with a more precise version.

OS: Windows 10
Game Version: 11328
Graphics Version: Tiles
Game Language: English [en]
Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
]

# Additional context
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5761365/debug.log)

**Comment by BrettDong** [comment]
Superseded by #46512.
