### ISSUE TITLE
Support for grammatical case is missing which makes construction of grammatical correct sentences impossible in languages which use a case system

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#4652]
I have very bad problems translating many strings because of missing grammatical case support. English doesn’t have case, but a lot of Indo-European languages do. Like German. It is not possible to translate many strings into German with the correct case.
Example:
“The %s strikes your %s.”
Let’s fill the placeholders with “zombie” and “leg”:
“The zombie strikes your leg.”
No problem yet. Because in English, you already know the sentence is always going to contain “The” and “your”.

Now in German, we have a problem here. The grammar of the sentence depends on the words which get filled in. Examples:
“Der Zombie schlägt dein Bein.”
“Das Monster schlägt deinen Kopf”
“Die Klingendrohne schlägt deinen Torso.”
And so on. Now it is easy to see that a single format string won’t work for German. German is certainly not the only languages with such problems, other languages have case, too.

Sadly, I don’t have any idea how to fix this; any ideas are welcome. :-)
##

**Comment by kevingranade** [comment]
As far as I know there is no support for this concept in gettext, so we have little to no chance of resolving it.  If someone has an idea for implementing this please reopen.
