### ISSUE TITLE
If zombie grab and pull you over a trap, it will break its logic

### ISSUE THREAD

**Issue by Salty-Panda** [CleverRaven/Cataclysm-DDA#46527]
# Describe the bug

If a zombie drag you over the trap it will mess up the activation/explosion logic

# Steps To Reproduce

I set up a booby trap.
A grappler zombie grabbed me and pulled to himself, OVER THE TRAP - I moved from the tile behind the trap to the one in front of it.
I ran around the trap, then another zombie walked on it.
I got a message that the trap was activated twice
The trap caused no damage, I didn't even get the message that it caused no damage. Just nothing happened.

I tried setting up more traps, but without being dragged over it. The activation happened twice too, but it exploded properly.

Then I also tried stepping on landmines. the double activation happened again, but possibly for different reasons since the message is different.

# Expected behavior

Grab-movement will activate the trap

# Screenshots

![image](https://user-images.githubusercontent.com/26396019/103488793-09746b80-4e10-11eb-97db-7a417ea74785.png)
![image](https://user-images.githubusercontent.com/26396019/103489034-b7cce080-4e11-11eb-949a-0cdc4f32df43.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-8536-g9c2c35a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Mythical Martial Arts [MMA],
    C.R.I.T Expansion Mod [crt_expansion],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Bionic Professions [package_bionic_professions],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP]
]

# Additional content

The location of the explosion isn't set using global coords, cause when I was setting up and disarming a large number of land mines during training device skills, the explosions weren't centered on the tile in the front of me, but often as much as 8 tiles to the left/right.

**Comment by Mrzjadacz** [comment]
![image](https://user-images.githubusercontent.com/26396019/103489026-aaaff180-4e11-11eb-88be-8e96cf3883d7.png)
