### ISSUE TITLE
Storm Elemental Burnback causes an error and does not work in Magiclysm

### ISSUE THREAD

**Issue by Overcloak1** [CleverRaven/Cataclysm-DDA#46535]
Upon Taking the storm elemental ascension, one of the features of said ascension is the storm elemental burnback that damages enemies that attack you in melee. Upon getting attacked in melee after taking the ascension, the game client threw the included error message.

# A clear and concise description of what the bug is.

The storm elemental burn back feature throws the error "invalid spell id "STORM_ELEMENTAL_BURNBACK"

# Steps To Reproduce

1. Take the storm ascension.
2. Get attacked by any hostile creature in melee.
3.  "invalid spell id "STORM_ELEMENTAL_BURNBACK" occurs 

# Expected behavior

The attacking creature should get zapped and no errors should occur.

# Screenshots

![storm_elemental_bug_cdda_magiclysm](https://user-images.githubusercontent.com/76927648/103496096-c99e8b80-4df1-11eb-8d1e-392ef551e153.jpg)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-8687-ged7efb8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP]
]

 -->

**Comment by actual-nh** [comment]
Ping: @KorGgenT

**Comment by ZhilkinSerg** [comment]
Should be `STORM_ELEMENTAL_ZAPBACK`

**Comment by Overcloak1** [comment]
That fixed it, thanks! If anyone is having a similar issue before a fix is rolled out, go into \data\mods\Magiclysm\enchantments\Storm_Elemental.json and change     "hit_me_effect": [ { "id": "STORM_ELEMENTAL_BURNBACK" } ]    to     "hit_me_effect": [ { "id": "STORM_ELEMENTAL_ZAPBACK" } ]        as  per ZhilkinSerg's comment.
