### ISSUE TITLE
Large tree sprites (128x128px) get overlayed on the bottom right tile

### ISSUE THREAD

**Issue by acepleiades** [CleverRaven/Cataclysm-DDA#46534]
# Describe the bug
As seen in the following screenshot, the bottom right tile of the tree sprites, which occupy 9 tiles being 128x128px large, is overlayed.

# Steps To Reproduce

Look at fully grown UltiCa trees

# Expected behavior

The tree sprite should appear on top

# Screenshots
![5](https://user-images.githubusercontent.com/69649956/103494720-c7025d00-4e16-11eb-858f-8c62f8d869e6.png)

# Versions and configuration

Happens in all versions

# Additional context
N/A

**Comment by ZhilkinSerg** [comment]
There is a flower there.

**Comment by Zireael07** [comment]
If the tree sprite is indeed 9x9, the flower shouldn't be visible.

**Comment by acepleiades** [comment]
> There is a flower there.

The shadow should appear over the flower
The tree above also has this issue with tall grass, which is just normal terrain

> If the tree sprite is indeed 9x9, the flower shouldn't be visible.

Both should be visible

**Comment by acepleiades** [comment]
Here's a clearer example, it happens on dirt which is normal terrain
![out~2](https://user-images.githubusercontent.com/69649956/103577170-0f6f5880-4eb3-11eb-8c79-e56d31ea3c7c.png)

This is a confirmed bug

**Comment by esotericist** [comment]
report is misidentifying the issue

terrain tiles should never be oversized, and trees should not be terrain.

the renderer is behaving correctly in this case

**Comment by Aivean** [comment]
The issue stems from the fact that trees are terrain, and currently renderer doesn't distinguish between "tall" terrain, that span into the "furniture" layer, such as trees and walls and "flat" terrain, such as dirt.

So the possible solutions would be:
1. make trees furniture (it's not as insane as it sounds, it's just `furniture` not a very good name for what it represents)
2. render terrain in two passes, first everything "flat", then everything "tall"

**Comment by acepleiades** [comment]
I fixed the issue with this https://github.com/I-am-Erk/CDDA-Tilesets/pull/689
