### ISSUE TITLE
Whitespaces in strings considered harmful

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#4653]
There are some strings which have lots of traling or leading whitespace. This doesn’t seem right to me. I think any leading or trailing spaces should usually be eliminated in the original strings. There may be some exceptions.

An example for this are the strings you see at the right part of the map. It seems those strings must have a constant length with the rest filled with spaces. Well, this sucks. What sucks even more is that launchpad.net automatically adds the same amount of white space as in the original string. It is not possible to disable this behaviour. I asked them. They told me that this whitespace stuff is a bad idea and I should go complain to you instead. :D To see the result of this, try CDDA 0.9 with the German translation (download it from Launchpad).
##

**Comment by illi-kun** [comment]
@VlasovVitaly @Night-Pryanik  is this still an issue?

**Comment by cainiaowu** [comment]
@illi-kun Most speed stats such like `Overburdened        -%s%d%%` still use hardcoded whitespace to align.
searching 3 continuous whitespaces in current .pot results total of 246 line, which means 123 string have problems.

**Comment by illi-kun** [comment]
I mean, is that an issue for translators?

**Comment by cainiaowu** [comment]
Not for Chinese at least as translated strings are always shorter. I can filled the string to same length anyway.

Cant say about other languages.

**Comment by Wuzzy2** [comment]
It's not really an “issue” anymore since we finally don't use that crappy Launchpad anymore. Now it's mostly like an annoyance.
I still think needless whitespace should be eliminated as far as possible, because it is pretty error-prone for translators. So I keep it open.

**Comment by Night-Pryanik** [comment]
@Wuzzy2 If I understand it correctly, you meant something like "`Speed: `"? With space after colon?

**Comment by Wuzzy2** [comment]
Not only this, but in general whitespace should be avoided.
I am not sure if whitespace is used that often anymore but it still a minor issue.

Regarding your example: Strings like “Speed: ” are really bad, not because of the whitespace but because it is an indication that string concatenation is used.
**String concatenation is the mortal sin of internationalization!**
Always use format strings, don't concatenate. In this case, you should use “Speed: %d” (or something like that).

**Comment by kevingranade** [comment]
To clarify, what we would like to do instead of aligning with whitespace
manually is to use methods that accept a (translated) string and a field
width, and output a padded string that will fit in the provided space (note
this might truncate instead of padding).

**Comment by VlasovVitaly** [comment]
We already have all methods for Unicode strings. But ofc they not cover all code.

This issue should be closed. And similar issues must be opened for all particular string(s).

**Comment by illi-kun** [comment]
I agree with @VlasovVitaly, this issue contains general complains but doesn't point out the exact "bad" strings (except 'map' menu but it's mentioned just as an example), it's simply not possible to "fix" this issue because "bad" strings aren't listed.

**Comment by BrettDong** [comment]
@illi-kun This should be closed?
