### ISSUE TITLE
calories store in body are increasing without eating anything.

### ISSUE THREAD

**Issue by vitaminlemonade** [CleverRaven/Cataclysm-DDA#46552]
# Describe the bug
   so the the calories store in the body are increasing without eating anything.

  so the the calories store in the body are increasing for no reason. but the metabolism modifier related mutation will make the hunger work properly.

# Steps To Reproduce
1. create a character and wait for one hour (the cal store in body first spawn are 55000)
2. go to debug menu to see the problem is

# Expected behavior

the calories store in the body are increase without eating any food and metabolism modifier related mutation  . 

# Screenshots

# Versions and configuration
 - OS: Android
    - OS Version: Manufacturer: asus; Model: ASUS_Z01QD; Release: 9; Incremental: 16.0420.2009.39-0; 
- Game Version: a3bf351 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead  [dda],
]

 -->

# Additional context

**Comment by BrettDong** [comment]
Could you please elaborate on how to reproduce the bug? I wrote a mutation with -0.5 metabolism modifier, created 3 new characters, each waited an hour in-game, but my characters only got 6-8 hunger value.

**Comment by vitaminlemonade** [comment]
the problem was the metabolism modifier decrease the number, my test was: in one hour of waiting, i got 6 point increase from 0 and the result are same at 5 tries with out the metabolism modifier (the stat of @ that are tested are 25str 25dex 25int 25per), so with -0.5 i should get 3 increase from 0 at one hour of waiting. but the number are different each time tested, especially  is you set to -0.8 the number of hunger demand will increase to 100 in 30. so maybe try -0.8.

**Comment by BrettDong** [comment]
I set my character with a -0.8 metabolism modifier mutation and waited one hour in-game but the hunger value only increased by 4. Can I have your mutation JSON please?

**Comment by vitaminlemonade** [comment]
what is your hunger value with out any mutation?
here is my mutation:
{
    "type": "mutation",
    "id": "still thinking",
    "name": "still thinking" ,
    "points": 0,
    "description": "nothing.",
    "valid": false,
    "purifiable": false,
    "metabolism_modifier": -0.8
  },

**Comment by BrettDong** [comment]
I tried your JSON and here is the experiment result:

| | 08:00 | 09:00 | Δ |
|---|---|---|---|
| Without mutation | 1 | 13 | +12 |
| With mutation | 1 | 2 | +1 |

**Comment by vitaminlemonade** [comment]
oh i forgot to mention that i reset all demand value before testing, also what i got was 6 increase as my result, especially if set to -0.8, i always get to 100 like withing one hour.

**Comment by BrettDong** [comment]
The current mechanics is that hunger value is set to 100 when stored calories is below the value of healthy calories:
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/character.cpp#L5654

**Comment by vitaminlemonade** [comment]
wait so what does metabolism modifier effect on? cal in the body or hunger value >

**Comment by vitaminlemonade** [comment]
> The current mechanics is that hunger value is set to 100 when stomach is empty and stored calories is below the value of healthy calories:
> https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/character.cpp#L5654

so I test again and i see that the cal stored in @ is increasing without the metabolism modifier mutation, i don't know why but if @ has the metabolism modifier mutation waiting will decrease the cal in the @.

**Comment by BrettDong** [comment]
I don't see the mutation broken if you don't reset player demand values in debug menu.

**Comment by vitaminlemonade** [comment]
> I don't see the mutation broken if you don't reset player demand values in debug menu.

so i tested again, reset the player demand isn't the problem. what weird is that the cal stored in the body with @ that don't have any mutation are increasing for at one hour of wait.

**Comment by BrettDong** [comment]
Current calories mechanics is complicated.

**Comment by vitaminlemonade** [comment]
but you know why does calories store in @ are increase without metabolism modifier related mutation on?

**Comment by actual-nh** [comment]
> True, but do you know why does calories store in @ are increasing while waiting without metabolism modifier related mutation on?

Anything in the stomach/guts?

**Comment by vitaminlemonade** [comment]
> > True, but do you know why does calories store in @ are increasing while waiting without metabolism modifier related mutation on?
> 
> Anything in the stomach/guts?

none, completely none

**Comment by vitaminlemonade** [comment]
> Current calories mechanics is complicated.

I wondering is this issue still tracking?

**Comment by actual-nh** [comment]
That is odd. I doubt that I would have time to investigate it, but perhaps a savefile would help others?

**Comment by anothersimulacrum** [comment]
You start with some food in your guts, so you'll digest that throughout the first day and gain some calories

**Comment by vitaminlemonade** [comment]
> but perhaps a savefile would help others?

you mean picture?

**Comment by BrettDong** [comment]
调试菜单点击重置需求会设定胃中有475毫升待消化食物，卡路里升高是因为食物被缓慢消化。

**Comment by vitaminlemonade** [comment]
> 调试菜单点击重置需求会设定胃中有475毫升待消化食物，卡路里升高是因为食物被缓慢消化。

OK, that might answer my question. Thanks for answering back in translated then.
