### ISSUE TITLE
Add item and recipe for bundles of rebar

### ISSUE THREAD

**Issue by DalenTalas** [CleverRaven/Cataclysm-DDA#46551]
# Is your feature request related to a problem? Please describe.
Shifting rebar one by one is annoying. It is easily bundlable, similar to planks, by use of wire or rope.

# Describe the solution you'd like
A recipe for bundles of rebar, similar to bundling planks.

# Describe alternatives you've considered
Keep bungling around with unbundlable rebar like a real buffoon (betcha can't say that three times fast).

**Comment by onura46** [comment]
Fixed with #46557 (not sure why it's not appearing; also check https://github.com/CleverRaven/Cataclysm-DDA/commit/588e89552ab047ecdeb82797a2763bcf0fcbb658)

**Comment by DalenTalas** [comment]
It's a very old issue of mine that I referenced in the current ticket for bundles of pipe. Feel free to disregard.
