### ISSUE TITLE
Power storage drains gasoline from fuel cell after fully charged 

### ISSUE THREAD

**Issue by AHolmen** [CleverRaven/Cataclysm-DDA#46567]
# Describe the bug
Power storage drains gasoline from fuel cell after fully charged 

# Steps To Reproduce

# Expected behavior
It's to be expected that the fuel ceases to drain as soon as you've got full power...

# Screenshots

# Versions and configuration

# Additional context

**Comment by Qrox** [comment]
Did you have the fuel saving mode turned off? When I set it to 100% it correctly turned off the CBM when bionic power became full.

**Comment by hexagonrecursion** [comment]
Could not reproduce. This might be a UX issue. Is there a point to having a configurable fuel saving mode and to requiring manual activation? The most user friendly version would be to have no configuration knobs: automatically turn the bionic on and off to keep the power topped up.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: f50b6be [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
