### ISSUE TITLE
Game often behaves strangely if a string exceed a certain length

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#4657]
CDDA often behaves strangely when it encounters a string which is too long. There are many such examples. CDDA may:
* simply continue writing the text on the next line on the screen,
* overwrite other parts of the screen where it shouldn’t,
* write text on areas which get not cleared correctly or
* do other weird stuff.

Issue #4655 is related, all the examples therein showed one of the symptoms.

Tested in: 0df165bd23e6d3195eb3ac8abc2a2e49fa642773

**Comment by illi-kun** [comment]
This issue has very generic description. It is not possible to track its status.

Please be more specific in the description of actual instances where text handling is broken.
