### ISSUE TITLE
Android key tooltip is an empty box

### ISSUE THREAD

**Issue by LiangWei88** [CleverRaven/Cataclysm-DDA#46573]
# Describe the bug
I use chinese
When I long touch the key on the bottom left corner, it show tooltip with empty box

# Steps To Reproduce

1. set the game on chinese
2. long press on keys at the bottom left corner to see the key description popup

# Expected behavior

How to show those characters normaly?
If it is just for tooltip, can i set it to english? because it is fine in english

# Screenshots

![微信图片_20210106023353](https://user-images.githubusercontent.com/4264011/103685614-80ecfb00-4fc8-11eb-99de-c403150d1cae.jpg)

# Versions and configuration

- OS: Android
    - OS Version: Manufacturer: Xiaomi; Model: Redmi Note 8 Pro; Release: 10; Incremental: V12.0.4.0.QGGCNXM; 
- Game Version: 0.E-3 [64-bit]
- Graphics Version: Tiles
- Game Language: 中文 (天朝) [zh_CN]
- Mods loaded: [
    浩劫余生 [dda],
    禁用NPC需求 [no_npc_food]
]

**Comment by ZhilkinSerg** [comment]
It is fixed in experimental and next stable version. There are no plans to backport the fix into 0.E.

**Comment by ZhilkinSerg** [comment]
You can use a different font as a workaround (e.g. unifont or ttf version of Terminus font).

**Comment by LiangWei88** [comment]
> You can use a different font as a workaround (e.g. unifont or ttf version of Terminus font).

Thank you
Do I need to build my apk to chang font?
or can I just set font some where in game menu?

**Comment by ZhilkinSerg** [comment]
You can put font file to `data\font` folder and put its name to `config\fonts.json` under app data folder.

**Comment by LiangWei88** [comment]
> You can put font file to `data\font` folder and put its name to `config\fonts.json` under app data folder.

Thank you, I find the game folder in my phone and put font and setting in it.
It works fine.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/characters-crash-when-changing-language/25685/3
