### ISSUE TITLE
"prof_aircraft_mechanic" does not appear in game.

### ISSUE THREAD

**Issue by x7GoSu** [CleverRaven/Cataclysm-DDA#46575]
The proficiency "prof_aircraft_mechanic" does not appear anywhere in the game. There appears to be no way to acquire this.

# Expected behavior

A way to at the very least start the game with the aircraft mechanic proficiency/
    - OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-8687-ged7efb8 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by ZhilkinSerg** [comment]
Yeah, it is not something character can learn during average game timeframe. This proficiency is intended to be used for professions and/or NPCs.

**Comment by x7GoSu** [comment]
So would something like this be acceptable?

  {
    "type": "profession",
    "id": "Aircraft_Mechanic",
    "name": "Aircraft Maintenance technician",
    "description": "You have spent your life repairing and maintaining aircraft.",
    "points": 6,
    "skills": [
      { "level": 2, "name": "gun" },
      { "level": 6, "name": "mechanics" },
      { "level": 1, "name": "melee" },
    ],
	"proficiencies": [ "prof_aircraft_mechanic" ],
    "items": {
      "both": {
        "items": [
          "pants_army",
          "socks",
          "undershirt",
          "boots_combat",
          "wristwatch",
          "gloves_tactical",
          "helmet_army",
          "jacket_army",
          "webbing_belt",
          "chestpouch"
        ],
        "entries": [
          { "group": "charged_two_way_radio" },
          { "group": "goggles_welding" },
          { "item": "ear_plugs", "custom-flags": [ "no_auto_equip" ] },
          { "item": "m17", "ammo-item": "9mm", "container-item": "holster", "charges": 17 },
          { "item": "knife_combat", "container-item": "sheath" }
         { "item": "mirror" },
         { "item": "wrench" }
        ]
      },
      "male": [ "boxer_shorts" ],
      "female": [ "bra", "panties" ]
    }
  },

**Comment by kevingranade** [comment]
Yea sure, you can add that in a mod.

**Comment by Fris0uman** [comment]
Since it would be useless for the player to be a mechanic ( can repair but can't fly the helicopter is useless) it would make more sense to give it to some rare random NPC and/Or to one static NPC that you can recruit through a quest.
