### ISSUE TITLE
Game spawns guns with mismatched ammo

### ISSUE THREAD

**Issue by Mrzjadacz** [CleverRaven/Cataclysm-DDA#46574]
# Describe the bug

Found Glock 22 (15/15 .257 SIG)
This weapon uses a magazine that can load both .40 and .357, but the gun can only shoot .40.
A similar problem could happen with STANAG mags that can accept 300 Blackout.

Possibly caused by the function described in #46548, the function to return item's ammo_type iterates over pockets and returns a collection of matches.

# Steps To Reproduce

Set a very high loot rate and kill hordes till you drop this particualr gun.

# Expected behavior

Gun spawn with matching ammo.

# Screenshots

![image](https://user-images.githubusercontent.com/26396019/103694503-59cc0480-4f9b-11eb-8525-ea200514efaa.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-8729-geba9219 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Mythical Martial Arts [MMA],
    C.R.I.T Expansion Mod [crt_expansion],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Bionic Professions [package_bionic_professions],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP]
]

**Comment by PaulBlay** [comment]
Pretttty sure this is a duplicate.

Hmm, looks like this https://github.com/CleverRaven/Cataclysm-DDA/issues/42254 or this https://github.com/CleverRaven/Cataclysm-DDA/issues/42332 but both are marked closed. I think the last was closed REAL recently, so it may just not be in the build you're playing yet.

**Comment by ZhilkinSerg** [comment]
Test in build 11337 or above.

**Comment by Mrzjadacz** [comment]
Yup, it's duplicate
