### ISSUE TITLE
Unable to "Work on Craft" at workbench

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#46576]
# Describe the bug

After storing an in-progress craft in the inventory, I am unable to then work on it at a workbench.

# Steps To Reproduce

1. Load attached save.
2. Enter `a`ctivation menu and select the in-progress craft, which is on the workbench.
3. Note that the game will ask you to wield it and resume work, implying the work is done in-hand.
4. Observe that the end result does end up in your hand.

# Expected behavior

I expected the game to respect where the craft was before work began when deciding where to work on it and where to place it.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 20H2 (build 19042.685)
- Game Version: 0.E-8740-g618a3be [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded:
    - Dark Days Ahead [dda],
    - C.R.I.T Expansion Mod [crt_expansion],
    - No Fungal Monsters [No_Fungi],
    - Disable NPC Needs [no_npc_food],
    - Alternative Map Key [alt_map_key],
    - SpeedyDex [speedydex],
    - Stats Through Kills [stats_through_kills],
    - Stats Through Skills [StatsThroughSkills]

# Additional context

[Woodcock.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5772773/Woodcock.zip)

**Comment by sdvhunter** [comment]
Bug persists in 0.G.
[Бигль-trimmed1.tar.gz](https://github.com/user-attachments/files/16021554/-trimmed1.tar.gz)
Versions and config:
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version (Win 8.1)
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Stats Through Kills [stats_through_kills],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]
