### ISSUE TITLE
Translation: Format strings are not used consistently

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#4658]
There are some strings which seem to be made in a “glue-them-together” manner. One example are the descriptions for factions (there are other examples as well). Needless to say, it is just a pain in the ass to translate these strings, because it is hard to tell the context. Another problem with this is that it forces a certain grammatical structure and parameter order onto the final text. Such strings came up in the WTF thread.

This problem can be fixed by dumping all “glue texts” and using proper format strings instead.

**Comment by illi-kun** [comment]
This issue is described in very general way and it's not possible to track its state. Please re-open with exact references on bad strings.
