### ISSUE TITLE
Use (unread) for unread books you find for easier pick up

### ISSUE THREAD

**Issue by Lamandus** [CleverRaven/Cataclysm-DDA#46588]
We have, right now a color pallete for books, telling which books are read, too hard, ect.. I would like to have (unread) at the end of the name of a book, so it will be "catched" by the autopickup system. Right now you need to get through every book you see and determine if you need it or not. And books are right now the only thing I need to go through manually (very excessive Autopickuplist). It would be a huge QoL update for me (and maybe others who may have problems with colors) to see at a glance if they have/read the book or not.

**Comment by PatrikLundell** [comment]
There are some books that appear to be hidden intentionally, i.e. when you look at them from afar they are displayed as a fairly common "book", but when you look at them for pickup you find that they aren't actually what they appeared to be (in one case there is a recipe manually written in the standard item, and in the other it's a rogue version of the standard item).

**Comment by Lamandus** [comment]
the unread version of the book (even from far away) will still be in red, while the read version will have another color, so there is no difference if we use red or "(unread)"

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
