### ISSUE TITLE
You can get beer out of a can without unsealing the can (vehicle)

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#46591]
# Describe the bug

You can transfer beer from inside a sealed can into a vehicle tank without unsealing the can.

# Steps To Reproduce

1. Obtain a can of beer (sealed)
2. Find a vehicle with an empty fuel tank.
3. (f)ill the vehicle tank, accidentally selecting your can of beer instead of your jerrycan of gasoline.
4. (e)xamine vehicle and notice that your beer is now sitting in a fuel tank.
5. Try to (s)iphon your beer back.
6. Fail. Because your beer can is still sealed.

 DEBUG    : tried to put an item (european_pilsner, amount 1) in a container (can_drink) that cannot contain it

 FUNCTION : int item::fill_with(const item&, int)
 FILE     : src/item.cpp
 LINE     : 8868

(NOTE: Attempting to add liquid into a sealed container gives an error. This is a different bug - it should either unseal the container or not give the container as a destination for the liquid).

# Expected behavior

You should remember not to fill your car fuel tank with beer. But if you don't, then it should open the can before emptying it.

# Screenshots

![beercycle](https://user-images.githubusercontent.com/54060142/103790875-a9610d80-5039-11eb-91be-8ee3794d5d42.png)

# Versions and configuration

- OS: Windows x64 8.1
- Game Version: 0.E-8729-geba9219 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

# Additional context

It unseals the beer can (but does not refill it) when you get the error message.

**Comment by PaulBlay** [comment]
[EDIT] Update. It looks like it does unseal the can, but only after you leave the vehicle screen. If, after you exit the vehicle screen, you place the opened empty aluminum can on the ground you can siphon the beer back into it.

**Comment by Qrox** [comment]
#46520 fixes the bug where you can't fill a sealed container. After that is merged this can be fixed by using the content change handler in the vehicle tank filling code.
