### ISSUE TITLE
Npc drops laser finger pseudo item when killed

### ISSUE THREAD

**Issue by qpekejdj** [CleverRaven/Cataclysm-DDA#46590]
# Describe the bug

An Npc found in PrepNet Orchard when killed dropped the laser finger pseudo item

# Steps To Reproduce

1.Make new game
2.Find PrepNet Orchard
3.Kill the Npc there

# Expected behavior

expected to drop all items that were on them which the laser finger was not in the trade menu or being worn

# Screenshots

![Screenshot (2)](https://user-images.githubusercontent.com/74380848/103758871-ec85a580-5066-11eb-9408-d322fa0df5e5.png)
![Screenshot (3)](https://user-images.githubusercontent.com/74380848/103758882-f27b8680-5066-11eb-9d4e-8be4337b067f.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-8659-g4c521a8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    C.R.I.T Expansion Mod [crt_expansion],
    Aftershock [aftershock]
]

**Comment by BrettDong** [comment]
Possibly related to #45947.
