### ISSUE TITLE
Dynamic shifting of stats and their bonuses

### ISSUE THREAD

**Issue by Savengrr** [CleverRaven/Cataclysm-DDA#46592]
# Is your feature request related to a problem? Please describe.
After using Magiclysm and some of it's stat enhancing spells I've come up with a thought, Base Health is still based on current Strength given via mutation and any increase from stats from kills/skills. In those cases the health bonus is applied immediately where the other more temporary bonuses are not at all.

# Describe the solution you'd like
Make a hidden Adjusted strength (Or other stat) which slowly trends toward the current by like 0.05 per hour. So if you have 16 strength but have been spending days at a constant dead tired state for a -1 to strength, your base health starts to trend towards a hidden adjusted 15 strength with lowered base health. The opposite should also apply.

# Describe alternatives you've considered
-Make Adjusted stat an average of what it has been over a period of like 5,10, or 30 days
-Make all effects on stats (Positive/Negative, temporary due to clothing or mutation) apply base adjustments if they persist longer than 24 hours (Similar in concept to how DND treats magical enhancements.)

# Additional context
This might be possible to apply to other stats, because usually it would make sense that just because your body mutated to allow for more intelligence/dexterity/strength, there should be an adjusting period to see tangible benefits. The same should be true for enhancing gear, just because the benefit would vanish the second you remove it doesn't mean your body isn't adjusting to this new found power over time.

But I guess this would also bring the problem of separating buffs/debuffs that are meant to apply/dismiss immediately (Ex.Pain) to the gradual changes, maybe certain debuffs/buffs would set the adjusted value directly and have high change modifier so they dissipate quickly.

**Comment by ZhilkinSerg** [comment]
Are you talking about hitpoints? They would be gone eventually.

**Comment by Savengrr** [comment]
Well I guess if the current HP system is being overhauled already then nevermind this idea.

But yeah I mean the hitpoints, they are normally determined by strength and not influenced by de-buffs but can be changed due to increases from mutations, rather instantly at that. Was just wanting to see the change of HP reflect on longer term and temporary effects slowly over time depending on how long the de-buff/buff persisted.

Main examples I expected it to best apply was long periods without sleeping properly spanning days and weeks, wearing enhancement rings from Magiclysm for days/weeks, or as an adjustment period to sudden changes in strength from mutations.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
