### ISSUE TITLE
Most vehicle parts that provide lifting/jacking should only operate when vehicle has an engine running

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#46594]
# Describe the bug

The way 'forklift arm' and similar vehicle parts work is super convenient, and highly unrealistic.

# Steps To Reproduce

1. Obtain two steel frames, welding goggles and an arc welder
2. Start vehicle construction and place a frame
3. Move one space from the frame and place a forklift arm
4. Go back to the original frame and remove it.

You now have a 'vehicle' that provides 6 jacking and 2 lifting quality.

# Expected behavior

Vehicle parts that are understood to require mechanical power provided by an engine should only be useable when that engine is present and running. I guess that isn't all of them, but a 'forklift arm' attached to nothing should definitely do nothing.

# Versions and configuration

- OS: Windows x64 8.1
- Game Version: 0.E-8729-geba9219 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

# Additional context

(Some of) the cranes and such are probably manually operated via pulleys and leverage.

The self-jacking motocycle kickstand is obviously fine.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
