### ISSUE TITLE
Autopickup treats fouling weapons differently than clean ones.

### ISSUE THREAD

**Issue by Lamandus** [CleverRaven/Cataclysm-DDA#46602]
# Describe the bug
I have autopickup switched on for most weapons. I horde them. When I was doing another raid, I came across a fouling HK417. Which wasn't picked up automatically. I didn't know why, so I checked my list, everything was fine, but why didn't it pick up? Because of the fouling symbol which is treatened like a part of the name.

# Steps To Reproduce
1. get a fouling gun
2. have the gun on autopickup (+)
3. check your characters autopickuplist

# Expected behavior
The fouling symbol (and color code for that matter) shouldn't be part of the name.

# Screenshots
![grafik](https://user-images.githubusercontent.com/33199510/103896356-23ed6400-50f2-11eb-8da5-c93c25a708ce.png)
![grafik](https://user-images.githubusercontent.com/33199510/103896378-2c459f00-50f2-11eb-8d2d-79b16a5e96f3.png)
![grafik](https://user-images.githubusercontent.com/33199510/103896529-67e06900-50f2-11eb-8fc9-15accc2f9528.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-8807-gffd58c6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Dark Days of the Dead [classic_zombies],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    meins [mine],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Vanilla Additions [Graphical_Overmap_SDG]
]

# Additional context

**Comment by ZhilkinSerg** [comment]
Add wildcard * as a workaround.

**Comment by Lamandus** [comment]
> 
> 
> Add wildcard * as a workaround.

I wand to pick up all HK* related things, so having *HK* will lead to also pick up shishkebabs... so I need to get my exclude listing also up to snuff.

it is not a big bug. But at least something to point out.

**Comment by ZhilkinSerg** [comment]
> 
> 
> > Add wildcard * as a workaround.
> 
> I wand to pick up all HK* related things, so having _HK_ will lead to also pick up shishkebabs... so I need to get my exclude listing also up to snuff.
> 
> it is not a big bug. But at least something to point out.

Do not use `*HK*` as a filter. You need to use wildcard in the beginning of the string only to ignore color tags.

**Comment by Lamandus** [comment]
no you are confusing me.

**Comment by ZhilkinSerg** [comment]
You had issue filtering `blablablaHKabcd` using `*HK*` as a filter because it grabs things like `HKxyz` too, so use `*HKabcd` filter.

**Comment by Lamandus** [comment]
thanks for the idea, but there are a few HK weapons, I wand everyone. I need to add every individually, which is a bit too much work for me. I will just don't pick fouling weapons then...

**Comment by ZhilkinSerg** [comment]
Yes, you need to add filter for each one of them (unless they all have some shared string you can use for the filter), but it is not because of the current issue.

**Comment by Jamuro-g** [comment]
Are any weapons/items completly colored? 
If not, then it might be possible to use find() on checked item names to cut off all segments inbetween "<color_" and "</color>"
This should allow the autopick up rules to ignore color tags and any special symbols inbetween them

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
