### ISSUE TITLE
Disappearing in progress heavy wooden beam

### ISSUE THREAD

**Issue by TJKing293** [CleverRaven/Cataclysm-DDA#46611]
# Describe the bug

when a in progress heavy wooden beam is dropped on the ground it disappears. Yet it still consumes the resources to make it.

# Steps To Reproduce

1. gather 6 logs, wood axe and wood saw with level 1+ fabrication
2. begin making the heavy wooden beam stop halfway through the process.
3. and then drop the in progress heavy wooden beam.

# Expected behavior

it should be on the ground and should be able to be picked up again..

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-8817-g98e7362 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    No Fungal Monsters [No_Fungi],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills]

# Additional context

**Comment by PaulBlay** [comment]
Worked just fine for me now. A save file might help. Also, what sort of workbench, if any, were you using?

- OS: Windows x64 8.1
- Game Version: 0.E-8821-ged07fdc [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Monsters [Only_Wildlife]
]

**Comment by kevingranade** [comment]
The thing that strikes me is that the in progress wooden beam has a very very high volume. It's very likely that if you dropped it on top of a pile of items that also has significant volume especially if you're near a pile of logs or something that it would exceed the total volume limit for a tile and vanish.
