### ISSUE TITLE
Can't compose MSx tileset with latest compose.py

### ISSUE THREAD

**Issue by Fris0uman** [CleverRaven/Cataclysm-DDA#46618]
# Describe the bug

Some change in #46358 make compose not work for MSX

Before changes:
![image](https://user-images.githubusercontent.com/41293484/104009703-bd2c8100-51ab-11eb-829b-b042ecc9c5fc.png)

After Changes:
![image](https://user-images.githubusercontent.com/41293484/104009725-c87fac80-51ab-11eb-8811-a1991d8491d9.png)

The sprites in the Large.png sheet are all switched around.

# Steps To Reproduce

- Get latest version of compose.py
- Compose MSx using -use--all option ( even without you get the same result)
- Load game
- Look at some large sprite : be suprised that the lamp post is a juggernaut corpse and the pike your weilding a snowy pine tree

# Expected behavior

See first screenshot

# Screenshots

# Versions and configuration

# Additional context

**Comment by actual-nh** [comment]
Ping: @int-ua?

**Comment by int-ua** [comment]
Thank you. Looks like an off-by-one error in the code responsible for filling the last row with empty spaces that turns into an off-by-row issue. This appears only when the number of sprites in a sheet is divisible by sheet width (16). Fixing.
