### ISSUE TITLE
You can build multi-tile tall vehicles and step on your NPC but dropping things on them deal no damage

### ISSUE THREAD

**Issue by Salty-Panda** [CleverRaven/Cataclysm-DDA#46616]
# Describe the bug

Climbed on top of my car and unfolded another vehicle which I climbed upon.
Dropped heavy-duty frame on the air tile under which was my NPC, it dealt no damage, didn't even receive a message like "You hear crash".
Jumped down on the tile under which was my NPC. I got damaged, by my NPC not.
Made a bridge out of my NPCs and walked on them.

# Steps To Reproduce

Build a vehicle with at least two roof tiles.
Deploy grappling hook next to it and climb up.
Unfold a vehicle with a cloth roof, deploy a grappling hook on the other roof tile. 
Climb down and back up on the other roofed tile of the bottom vehicle.
Climb up on the unfolded vehicle.

Optionally, arrange NPCs next to the bottom vehicle, drop things (from the upper vehicle) on them, jump down on them (from the upper vehicle), step on them (from the bottom vehicle).

# Expected behavior

~~Depending on their inclination and Masochist trait NPC yell/moan when I step on them.~~
NPC receive damage when 100kg of steel or 80kg of human fall on their heads.

# Screenshots

Unfold another vehicle on top of the existing one, deploy a grappling hook.
![image](https://user-images.githubusercontent.com/26396019/104002359-425e6880-51a1-11eb-9c8d-edc8766ffb3c.png)
NPC bridge
![image](https://user-images.githubusercontent.com/26396019/104002410-53a77500-51a1-11eb-956a-fc142865d6af.png)

# Versions and configuration

OS: Windows
OS Version: 10.0 2004
Game Version: 0.E-8729-geba9219 [64-bit]
Graphics Version: Tiles
Game Language: English [en]
Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
Aftershock [aftershock],
Blaze Industries [blazeindustries],
Magiclysm [magiclysm],
Graphical Overmap [Graphical_Overmap],
Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
Mythical Martial Arts [MMA],
C.R.I.T Expansion Mod [crt_expansion],
No Fungal Monsters [No_Fungi],
Stats Through Kills [stats_through_kills],
SpeedyDex [speedydex],
Bionic Professions [package_bionic_professions],
Aftershock - UndeadPeople Tileset [AftershockUDP],
Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
Mythical Martial Arts - UndeadPeople Tileset [MMAUDP]
]

**Comment by Mrzjadacz** [comment]
Actually, not sure if multi-tile tall vehicles are a problem.
If not I can edit the issue.

**Comment by ZhilkinSerg** [comment]
Try reproducing it using a terrain.

**Comment by Aivean** [comment]
Roofed vehicle tiles currently set floor cache with all the consequences:
* sun is blocked
* you can stand on the vehicle roof (and cannot fall through it)

I think this part is not a bug.

However, things not falling on the NPC sounds like a bug.

**Comment by Mrzjadacz** [comment]
> I think this part is not a bug.

You mean unfolding vehicle while standing on another roofed vehicle, effectively stacking vehicles?

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
