### ISSUE TITLE
Prices applied incorectly to packaged items

### ISSUE THREAD

**Issue by Mrzjadacz** [CleverRaven/Cataclysm-DDA#46626]
# Describe the bug

I talked to a free merchant near Hub 01
Postapo price of the plastic bag: 0
Postapo price of jerky: 250

In-game price of packaged jerky: 250
In-game price of jerky: 300

# Steps To Reproduce

Talks to a merchant offering some packaged goods

# Expected behavior

Consistent pricing

# Screenshots

![image](https://user-images.githubusercontent.com/26396019/104049135-b837f380-51e4-11eb-902e-b21e90db1a10.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-8795-gc06c926 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Mythical Martial Arts [MMA],
    C.R.I.T Expansion Mod [crt_expansion],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Bionic Professions [package_bionic_professions],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP]
]

# Additional context

Social skill: 6 lvl
Free Merchants's attitude to me: Valued

**Comment by BrettDong** [comment]
Prices in NPC trade are based on item prices defined in JSON, but are also adjusted dynamically in game.
