### ISSUE TITLE
Minimum/Maximum Encumberance on Extra-Dimensional Pockets

### ISSUE THREAD

**Issue by GyprockGypsy** [CleverRaven/Cataclysm-DDA#46629]
When using the new CRIT Expansion, I recently found a new peice of armor with a "Dimensional Pocket". At first I thought this was awesome, even if it only had a limit of 12L making it useless for even putting heavy things into it in first place. As soon as I put single CBM into it though, It took my encumbrance from 25 to 39, at which point I realized the Max Encumbrance listed in the description was 65!!

Upon further inspection, I found that the armor article in question (CRIT Engineering Suit) didn't have a max encumbrance defined, just a basic encumbrance. So I followed what I assumed to be the model for encumbrance at the moment, and set it at 15:30.

I assume what was happening before was that the game was assuming the max encumbrance based off of max weight value, which was 1000kg, but was scaling that based on the amount of used volume.

My proposal is making the encumbrance of items on clothing a calculation for volume v. mass. I'm thinking of using mass as a basic unit, volume as a scalar, and pocket capacity as a ceiling.

If someone wanted to point me in the direction of the CRIT forums/disco, I'd love to help out. I'm no Nostradamus of programming, but I can copy and paste with the best of them!
# Versions and configuration

- OS: Win10 Pro
 - Game Version: current experimental (11346 as of  writing this)
 - Graphics version: I See Undead People!
 - Ingame language: Farts
 - Mods loaded: Aftershock, CRIT, MagiCrazyClysm, Dino

**Comment by GyprockGypsy** [comment]
It may also be easier to create a definition for pockets as allows the programmer to define whether volume and/or weight should be used in the calculating effective encumbrance.  Might also solve any future problems with these types of objects.

**Comment by Mrzjadacz** [comment]
The purpose seems to be the same as #45621

**Comment by Maleclypse** [comment]
Please put a PR together with your suggested fix and tag me in it.  I'll review it and offer any suggestions I think are needed.  I try to help with CRIT as possible.

**Comment by actual-nh** [comment]
Some statistics on current pocket capacities (including factoring in pockets limited to particular items) could be useful. E.g., what's the median encumbrance associated with items having X (total) volume/weight/length capacity.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
