### ISSUE TITLE
Add more crash locations to heli_crash scenario.

### ISSUE THREAD

**Issue by Foxtrot-Uniform42** [CleverRaven/Cataclysm-DDA#46637]
# Is your feature request related to a problem? Please describe.
The helicopter crash scenario has very limited start locations where crash can occur (field or forest for now), and it seems strange, since crash may happen in almost every location. 

# Describe the solution you'd like
Add more starting locations to heli_crash scenario. I propose to add at least sloc_desert_island and sloc_lighthouse_ground locations to the current list.

# Describe alternatives you've considered
Since crashing on islands could be much more difficult, add separate challenge scenario like "Crashing on the island" with 3 more starting points (8 in total).

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
