### ISSUE TITLE
Lighstrip recipe gone breaking the hydroponics mod. 

### ISSUE THREAD

**Issue by Astramentis** [CleverRaven/Cataclysm-DDA#46636]
Describe the bug

Lightstrip recipe is unavailable if crafting menu.

To Reproduce

Unlock all recipes in debug menu.
Search for "lightstrip".
No result.
Versions and configuration(please complete the following information):

OS: Win x64
Game Version: 0.E-7424
Graphics version: Chesthole32

**Comment by LaVeyanFiend** [comment]
The hydroponics mod's json file was removed in May. This issue is invalid.
