### ISSUE TITLE
Game crashes on loading of save.

### ISSUE THREAD

**Issue by JackReport** [CleverRaven/Cataclysm-DDA#46649]
The game crashes on loading on a current save.

# Steps To Reproduce

Load the save

# Versions and configuration

 - OS:Windows 10
 - Game Version: cataclysmdda-0.E-Windows-Tiles-b11314
 - Graphics version: Tiles 
 - Ingame language: English
 - Mods loaded: DDA, Bionic Professions, Aftershock, Blaze industries, CRIT expansion, No Rail station, No Fungal monsters.
 -->

# Additional context

<!-- Add any other context about the problem here.

-[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5791913/save.zip)
-[debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5791914/debug.zip)

**Comment by JackReport** [comment]
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5791920/save.zip)
[debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5791922/debug.zip)

**Comment by BrettDong** [comment]
I can get into the game using latest experimental:
<img width="1072" alt="螢幕截圖 2021-01-09 下午7 02 11" src="https://user-images.githubusercontent.com/21075502/104111189-2e079200-52ad-11eb-8ea4-de48b5160f81.png">

**Comment by JackReport** [comment]
I use a Tileset, but turning it off doesn't work. I am able to start a new character, but unable to load my old save.

**Comment by BrettDong** [comment]
Does it crash if you use the latest experimental version?

**Comment by JackReport** [comment]
I just tried that and it works. Was this a problem for last weeks build?

**Comment by BrettDong** [comment]
> I just tried that and it works. 
Closing as this is solved on latest experimental version.

> Was this a problem for last weeks build?
IDK, probably was.
