### ISSUE TITLE
FOODCO water purifier is OP. Balance suggestion.

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#46643]
# Is your feature request related to a problem? Please describe.

Although it's very handy, the FOODCO kitchen buddy water purifier is overpowered. Specifically, it is far too fast to work.

# Describe the solution you'd like

I would suggest giving the FOODCO kitchen buddy two, internal, containers. One holds only 'water' and one holds only 'clean water'. Water would transfer from the first to the second, at a reasonable rate, as long as there is space in the second. You could use the clean water like you can the water faucet on the kitchen station.

# Describe alternatives you've considered

I suppose you could just reduce the maximum amount of water that can be purified at once, and make it take a while to work.

**Comment by PaulBlay** [comment]
Alternatively, you could hitch it up to containers already in the vehicle and have it process 'water' from the first tank found with non-clean water into the first non-full tank (that either contains some clean water or is completely empty). It would basically be a "Install the FOODCO Kitchen Buddy and leave it to do its thing" solution.

**Comment by Cyprex** [comment]
Note that we also have battery-powered water purifiers which are I believe instant(?) and consume 1 battery charge per unit purified, you could probably get around the limit of 150 with UPS/heavy battery conversion mods?

**Comment by emptytriangle** [comment]
it would be really super cool if the water purifiers weren't instant and instead filled a container over time

**Comment by Fosheze** [comment]
It could be a UV sterilization system. While that still isn't instant, it is quick enough that it could be considered instant for gameplay purposes. The current figures that I am finding are about 10 seconds to sterilize all water within 6 inches of the bulb. The time it takes depends on the intensity of the bulb but considering that tech is a bit more advanced in game, UV bulbs are likely a bit more advanced as well. If you assume that it's a stupidly high intensity (by current standards) bulb directly in the tank then it could easily sterilize the entire tank within seconds. 

Where this could be expanded though it that UV systems only work on clear water and currently the game doesn't differentiate between muddy swamp water and tainted but still clear well water. The swamp water would require a pre-filter where the clear water could be run directly through a UV system.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
