### ISSUE TITLE
M57A1 Techno-Medusa 0 rounds magazine space for 9x18mm

### ISSUE THREAD

**Issue by Karsolan** [CleverRaven/Cataclysm-DDA#46658]
The bug

The M57A1 Techno-Medusa cannot reload 9x18mm ammo of any kind. In the weapon description it is shown to have a capacity of 0 rounds of 9x18mm. All the 9x18mm ammo will show up in green as if compatible but wont be allowed for reloading options menu. 

This bug is repeatable across all generated character i can make by hand and by fixed scenarios. This remains the same with and without gun modifications i apply to the weapon. No crash or debug messages appear  due to this bug. Removing all but the Magiclysm mod does not affect the bug on a new world creation.

 - OS: Windows
 - Game Version: 11353 experimental
 - Graphics version: MSX++UnDeadPeopleEdition
 - Ingame language: English
 - Mods loaded: aftershock, blaze industries, C.R.I.T, Magiclysm, bionic professions package and Crazy cataclysm.
 
[Cdda bug screenshots.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5792419/Cdda.bug.screenshots.zip)

I can be contacted directly at Danflord@gmail.com

**Comment by PaulBlay** [comment]
I guess  M57A1 Techno-Medusa is from Aftershock?

**Comment by actual-nh** [comment]
> I guess M57A1 Techno-Medusa is from Aftershock?

Magiclysm. Ping: @KorGgenT?
