### ISSUE TITLE
Onboard chemistry lab's electrolysis kit charges available mis-reported

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#46659]
# Describe the bug

When using the electrolysis kit (as part of the onboard chemistry lab) the charges available register as 2500 when the actual charges available on the vehicle is over 80,000. 

# Steps To Reproduce

1. Have a vehicle with the following installed - onboard chemistry lab, - a couple of fully charged storage batteries, - a couple of fully charged car batteries
2. Start crafting and select batch production of bleach from salt water.
3. Note that selecting a batch of 10 bleach shows "electrolysis kit (2500) charges" in green, but selecting 11 shows "electrolysis kit 2750" in grey (e.g. insufficient charge).
4. Try to craft anyway. Warning: "You don't have enough charges to complete the bleach. Start crafting anyway?"
5. Still try to craft - completes with no problem.

# Expected behavior

Should sum up charges from all batteries installed on vehicle not (as I think it's doing) take the first battery found.

# Screenshots

![bleach](https://user-images.githubusercontent.com/54060142/104120189-d3ae1600-532c-11eb-8304-de8f91035c36.png)

# Versions and configuration

- OS: Windows x64 8.1
- Game Version: 0.E-8729-geba9219 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

#Additional information

I haven't checked exactly how this occurs. I suspect that if it finds the Storage Battery first then it will show 40,000 charges available.

**Comment by BrettDong** [comment]
Could you attach a save? I tried to reproduce this bug but electrolysis kit is green here in my game:
<img width="1072" alt="螢幕截圖 2021-01-20 上午11 59 09" src="https://user-images.githubusercontent.com/21075502/105208633-e8519180-5b16-11eb-9920-1d7bf81b6ee6.png">

**Comment by PaulBlay** [comment]
Do you still want a save?

**Comment by BrettDong** [comment]
I managed to confirm the bug. UI display is horribly wrong.

https://user-images.githubusercontent.com/21075502/105212382-6021bb00-5b1b-11eb-87f1-efcf656123d6.mov
