### ISSUE TITLE
Wish for update of android experimental.

### ISSUE THREAD

**Issue by Lamandus** [CleverRaven/Cataclysm-DDA#46660]
Hey guys. I got hospitalised with a severe covid pneumonia. I have a permanent need for oxygen and I don't feel too well. But I try to manage. I have my mobile phone with me and it would be very nice if the android builds are working again, that way I can get my mind off this situation... 
I know, that is a very personal request. And can be locked anytime if you find it inappropriate. But I said myself, that it is worth a try.

Let me tell you, COVID is a bitch!

Stay healthy.

**Comment by ZhilkinSerg** [comment]
Android builds are working. Use Playstore version or APK from https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-jenkins-latest-experimental

**Comment by Lamandus** [comment]
But they are old, aren't they? Like the linked one is from early 2020.  I talk about the newest experimental.

**Comment by ZhilkinSerg** [comment]
They are as new as it is possible.

**Comment by Zireael07** [comment]
AFAIK Android builds are automated in the same way desktop builds are? Playstore version *might* lag behind a bit, but the version from releases should be up to date.

**Comment by kevingranade** [comment]
This release has the android builds https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-jenkins-b11350
We're having trouble with getting *every* target completing in every build, but they're all succeeding periodically.

**Comment by Qrox** [comment]
> APK from https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-jenkins-latest-experimental

That link doesn't seem to be pointing to the latest experimental though (the date is 24 Mar 2020).

**Comment by ZhilkinSerg** [comment]
The tag is not being updated, but files there are latest successfully built experimental versions.

**Comment by int-ua** [comment]
Ok, the question looks answered. Get well soon and comment if you are still having problems with getting latest CDDA.
