### ISSUE TITLE
Riding a bicycle make you tired instead of weary.

### ISSUE THREAD

**Issue by EvgenijM86** [CleverRaven/Cataclysm-DDA#46663]
# Describe the bug

I was riding a bicycle for about 1-3 hours from the start of the game and I got Tired status and only Lightly Weary. The bug is that bicycle acts like a sleeping pill, instead of something that physically exhausts you.

# Steps To Reproduce

1. Find a bicycle.
2. Ride for a couple of hours.
3. Notice that by the time you got Tired you have almost no Weary status.

# Expected behavior

By the time you get Tired status you should be Extremely Weary already. I think that riding a bicycle should not make you sleepy at all until Extremely Weary status. And when you reach Extremely Weary it should start adding to your desire to sleep.

# Screenshots
None.

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 20.2; Codename: Nibia; 
- Game Version: 0.E-8888-g4f5916841b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

I was doing a low weight start, with that trait that makes you 35% starving.

**Comment by acbcodetribulations** [comment]
From what I understand activity levels for weariness are its own thing based on levels. It does not scale on load or speed.  Fatigue can scale on load through a chance roll, and while the chance is small it adds up over time. This probably was here before weariness or the change to one second rounds. For anyone interested look at the end of vehicle::consume_fuel.

I can't say it would work well but increasing weariness along with the thirst/fatigue is a start. I don't know how to balance it.
