### ISSUE TITLE
Way for NPC's to study all the books in a spot as a job.

### ISSUE THREAD

**Issue by JackReport** [CleverRaven/Cataclysm-DDA#46679]
# Is your feature request related to a problem? Please describe.

It's annoying when I recruit NPC's and their skills suck, but manually giving a book and telling them to read it per level gets very tedious fast.

# Describe the solution you'd like
A way for NPC's to study large amounts of books, or have a way to chain books together/keep reading

# Describe alternatives you've considered
Instead of just a level by level basis, have them read until they can no longer learn from the book.

**Comment by JackReport** [comment]
NPC's should also keep studying when they wake up as well, most NPC jobs you have to tell them to start every morning.

**Comment by YourCompanionCube** [comment]
having some kind of library zone would be helpful, where NPCs can be assigned to increase a skill, or all their skills, and they will read any books in that zone to do so. maybe also a setting to do that if they don't have another task

**Comment by GGgatherer** [comment]
#39129 :)
I like your idea more, though - it's more automated.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
