### ISSUE TITLE
Failing to break a grab while trying to go up/down stairs takes no time

### ISSUE THREAD

**Issue by jagoly** [CleverRaven/Cataclysm-DDA#46677]
# Describe the bug

As title.

# Steps To Reproduce

Start in an apartment with a low strength character. Lead zombie next to steps. Enjoy 100% grab break chance.

# Expected behavior

Failing to go up/down stairs should take just as much time as failing to move.

# Versions and configuration

Latest Experimental

**Comment by PaulBlay** [comment]
Yes, this is a thing.  Attached a save file where a low strength character is grabbed and standing on a stairwell. Attempting to go up a staircase takes no time if you fail to escape the grab. It takes one minute if you succeed in escaping the grab. I got three or for failed attempts with no time passage and no attacks on the character. By comparison, if you are grabbed in the open then it takes one minute to move a tile horizontally, and one minute for a failed escape from grab attempt.

[TESTGRAB.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5818855/TESTGRAB.zip)

- OS: Windows x64 8.1
- Game Version: 0.E-8914-g8c0034b-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]
