### ISSUE TITLE
Heavy cables cannot carry electricity

### ISSUE THREAD

**Issue by chuizhi** [CleverRaven/Cataclysm-DDA#46676]
In version 11352, the heavy-duty cable can not transmit power, either between two vehicles or from the vehicle to its own CBM.

The above is Baidu translation, the following is the original

重型电缆不能输送电力
版本11352，重型电缆不能输送电力，无论是两个载具之间，还是从载具给自身的CBM供电，都不行。

**Comment by ZhilkinSerg** [comment]
Do you have a savegame?

**Comment by ToxiClay** [comment]
I cannot confirm this finding. My save on build 11352 is properly transmitting power.

Ensure that the vehicle *from which the power is coming* has a fully-charged battery. The game will not cause power to flow from one to another unless this is the case.

**Comment by zeropol** [comment]
Because the name are quite similar, at least in English, are you sure you were not using the "heavy duty **tow** cable" ?

Below, a google translation, I hope in the good language : 
因为名称非常相似（至少在英语中如此），您确定未使用“重型**拖缆**”电缆吗？
