### ISSUE TITLE
In-progress disassembly stuck at 100%

### ISSUE THREAD

**Issue by moxian** [CleverRaven/Cataclysm-DDA#46680]
# Describe the bug

I have an "in progress disassembly of small metal sheet (100%)" that i cannot do anything useful with.

`a`ctivating it says: 
![cataclysm-tiles-20210111-195721](https://user-images.githubusercontent.com/7831163/104231824-693dc880-5447-11eb-94a7-bbf79c4a9827.png)

but no scrap is dropped on the floor, and the disassembly item persists.

# Steps To Reproduce

I'm not sure how i got into this state, but it's possible that i was interrupted right when i was about to finish the task.
Save file attached: [Linville - disassembly 100%.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5798061/Linville.-.disassembly.100.zip) (the assembly is on the table to the North-East)

# Expected behavior

The in-progress disassembly disappears, and (optionally) i get some scrap metal out of it.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-8852-gf360c7f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by PaulBlay** [comment]
I tried the game save, I did get the scrap metal drop but the disassembly item persisted as well.
