### ISSUE TITLE
ncursesw compile error on openSUSE Leap 15.2

### ISSUE THREAD

**Issue by liusen373** [CleverRaven/Cataclysm-DDA#46689]
# Describe the bug

command

`make -j 8 RELEASES=1 PREFIX=/dev/shm`
 
Error log:

```bash
g++  -DBACKTRACE -DLOCALIZE -DPREFIX="/dev/shm" -DDATA_DIR_PREFIX -ffast-math -Og -Werror -Wall -Wextra -Wformat-signedness -Wlogical-op -Wmissing-declarations -Wmissing-noreturn -Wnon-virtual-dtor -Wold-style-cast -Woverloaded-virtual -Wpedantic -Wsuggest-override -Wunused-macros -Wzero-as-null-pointer-constant -Wno-unknown-warning-option -Wredundant-decls  -g  -fsigned-char -std=c++14 -MMD -MP -D_GNU_SOURCE -D_DEFAULT_SOURCE -I/usr/include/ncursesw -c src/ncurses_def.cpp -o obj/ncurses_def.o
src/ncurses_def.cpp:199:20: error: redundant redeclaration of 'catacurses::window catacurses::_nc_stdscr()' in same scope [-Werror=redundant-decls]
 catacurses::window catacurses::stdscr;
                    ^~~~~~~~~~
In file included from /usr/include/ncursesw/curses.h:60:0,
                 from src/ncurses_def.cpp:13:
/usr/include/ncursesw/curses.h:1456:21: note: previous declaration of 'catacurses::window catacurses::_nc_stdscr()'
 #define stdscr      NCURSES_PUBLIC_VAR(stdscr())
                     ^
src/cursesdef.h:92:15: note: in expansion of macro 'stdscr'
 extern window stdscr;
               ^~~~~~
cc1plus: error: unrecognized command line option '-Wno-unknown-warning-option' [-Werror]
cc1plus: all warnings being treated as errors
make: *** [Makefile:856: obj/ncurses_def.o] Error 1
```

# Versions and configuration

- OS:  openSUSE Leap 15.2
- Game:    0.E-3 stable release
- g++ (SUSE Linux) 7.5.0
- ncurses-devel-6.1-lp152.7.67.x86_64

# Additional context

Related code in `/usr/include/ncursesw/curses.h`

```C
/*
 * Public variables.
 *
 * Notes:
 *      a. ESCDELAY was an undocumented feature under AIX curses.
 *         It gives the ESC expire time in milliseconds.
 *      b. ttytype is needed for backward compatibility
 */
#if NCURSES_REENTRANT

NCURSES_WRAPPED_VAR(WINDOW *, curscr);
NCURSES_WRAPPED_VAR(WINDOW *, newscr);
NCURSES_WRAPPED_VAR(WINDOW *, stdscr);
NCURSES_WRAPPED_VAR(char *, ttytype);
NCURSES_WRAPPED_VAR(int, COLORS);
NCURSES_WRAPPED_VAR(int, COLOR_PAIRS);
NCURSES_WRAPPED_VAR(int, COLS);
NCURSES_WRAPPED_VAR(int, ESCDELAY);
NCURSES_WRAPPED_VAR(int, LINES);
NCURSES_WRAPPED_VAR(int, TABSIZE);

#define curscr      NCURSES_PUBLIC_VAR(curscr())
#define newscr      NCURSES_PUBLIC_VAR(newscr())
#define stdscr      NCURSES_PUBLIC_VAR(stdscr())
#define ttytype     NCURSES_PUBLIC_VAR(ttytype())
#define COLORS      NCURSES_PUBLIC_VAR(COLORS())
#define COLOR_PAIRS NCURSES_PUBLIC_VAR(COLOR_PAIRS())
#define COLS        NCURSES_PUBLIC_VAR(COLS())
#define ESCDELAY    NCURSES_PUBLIC_VAR(ESCDELAY())
#define LINES       NCURSES_PUBLIC_VAR(LINES())
#define TABSIZE     NCURSES_PUBLIC_VAR(TABSIZE())

#else

extern NCURSES_EXPORT_VAR(WINDOW *) curscr;
extern NCURSES_EXPORT_VAR(WINDOW *) newscr;
extern NCURSES_EXPORT_VAR(WINDOW *) stdscr;
extern NCURSES_EXPORT_VAR(char) ttytype[];
extern NCURSES_EXPORT_VAR(int) COLORS;
extern NCURSES_EXPORT_VAR(int) COLOR_PAIRS;
extern NCURSES_EXPORT_VAR(int) COLS;
extern NCURSES_EXPORT_VAR(int) ESCDELAY;
extern NCURSES_EXPORT_VAR(int) LINES;
extern NCURSES_EXPORT_VAR(int) TABSIZE;

#endif                                                             
```

By default, `stdscr` is a macro rather than a variable

**Comment by ZhilkinSerg** [comment]
Thia should be handled by NCURSES_NOMACROS

**Comment by liusen373** [comment]
> Thia should be handled by NCURSES_NOMACROS

What should I do to prevent this error ?

**Comment by BrettDong** [comment]
Does `CXXFLAGS=-DNCURSES_REENTRANT=0` help?

**Comment by liusen373** [comment]
> Does `CXXFLAGS=-DNCURSES_REENTRANT=0` help?

I patched `src/ncurses_def.cpp`, then all works fine. However, I know little about programming, i dont know whether it is correct.

```C
--- src/ncurses_def.cpp 2020-12-09 17:13:49.000000000 +0800
+++ src/ncurses_def.cpp.modified    2021-01-07 21:35:09.218508081 +0800
@@ -4,6 +4,9 @@
 // defines that clash with the constants defined in input.h (e.g. KEY_UP).
 #include "input.h"

+//patched by Liu Sen, 2021-01-07
+#define NCURSES_REENTRANT 0
+
 // ncurses can define some functions as macros, but we need those identifiers
 // to be unchanged by the preprocessor, as we use them as function names.
 #define NCURSES_NOMACROS
```

**Comment by BrettDong** [comment]
Seems like `ncurses` library on openSUSE and SUSE Linux is an reentrant-enabled version \[1\] that wraps some global `ncurses` variable to provide reentrancy in multithreading scenarios. But Cataclysm DDA is a single-thread program, so at a first glimpse, disabling reentrancy won't cause any problem here.

\[1\]: https://www.nvidia.com/download/driverResults.aspx/146629/en-us
> Updated nvidia-installer for better compatibility with ncurses when libncurses.so.6 exposes the ncurses reentrant ABI, such as on openSUSE Leap 15 and SUSE Linux Enterprise 15.

**Comment by liusen373** [comment]
> Seems like `ncurses` library on openSUSE and SUSE Linux is a reentrant-enabled version \[1\] that wraps some global `ncurses` variable to provide reentrancy in multithreading scenarios. But Cataclysm DDA is a single-thread program, so at a first glimpse, disabling reentrancy won't cause any problem here.
Seems like `ncurses` library on openSUSE and SUSE Linux is a reentrant-enabled version \[1\] that wraps some global `ncurses` variable to provide reentrancy in multithreading scenarios. But Cataclysm DDA is a single-thread program, so at a first glimpse, disabling reentrancy won't cause any problem here.
>
> \[1\]: https://www.nvidia.com/download/driverResults.aspx/146629/en-us
>> Updated nvidia-installer for better compatibility with ncurses when libncurses.so.6 exposes the ncurses reentrant ABI, such as on openSUSE Leap 15 and SUSE Linux Enterprise 15.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/having-trouble-compiling-on-opensuse-leap-15-2/26170/3
