### ISSUE TITLE
Obsolete obsolete data

### ISSUE THREAD

**Issue by Hirmuolio** [CleverRaven/Cataclysm-DDA#46696]
# Is your feature request related to a problem? Please describe.
There are json files that contain obsolete data for backward compatibility with old saves.
Some of this obsolete data is obsolete. The data is for versions that are not anymore compatible with current version anyways.

Obsolete items are not free. They require upkeep. Changes to how data is stored in json also requires updating the obsolete data to avoid errors.
The obsolete items also appear in the wish item menu.

The same applies to migration data too.

# Describe the solution you'd like
After 0.F is released the experimental doesn't need to be backwards compatible with 0.E or anything before that anymore. So all the obsolete files can be cleared at once.

# Describe alternatives you've considered
Stay backwards compatible with 0.E. Crawl through obsolete files and delete obsolete things that haven't changed since 0.E was released.

# Additional context

Some of these obsolete things have unique use actions in c++. It would be best to remove those too.
Quick look at least "fireweapon_off" and "fireweapon_on" only exist in obsolete items.

**Comment by actual-nh** [comment]
In order to make sure games on _experimental_ versions (between 0.E and 0.F) continue to load, what would appear indicated is a comparison between 0.E and the eventual 0.F, and anything already obsolete in 0.E should be removable in 0.F.

**Comment by jeremyshannon** [comment]
Before removing any more migration data, someone needs to go over the migration code and make sure it's migrating everything, and not leaving old unmigrated data lying around: #45631

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
