### ISSUE TITLE
Travis libbacktrace checksum failures

### ISSUE THREAD

**Issue by actual-nh** [CleverRaven/Cataclysm-DDA#46694]
# Describe the bug

Intermittently, mingw builds on Travis are failing due to an error of `Checksum failed for libbacktrace-i686-w64-mingw32.tar.gz`.

# Steps To Reproduce

See #46666 and #46686 for examples.

# Expected behavior

Checksum passing.

# Additional context

Ping: @Qrox?

**Comment by BrettDong** [comment]
I think it is a problem with Travis server itself, or the network between GitHub and Travis. The checksum error usually disappears after rerun. I downloaded `libbacktrace-i686-w64-mingw32.tar.gz` from Qrox's repo to my computer and the checksum matches.

**Comment by ZhilkinSerg** [comment]
So, I guess it is just failing to download the file till EOF. Is there some integrity check for gzip files?

**Comment by BrettDong** [comment]
How about retry a few more times if checksum doesn't match?

**Comment by actual-nh** [comment]
> So, I guess it is just failing to download the file till EOF. Is there some integrity check for gzip files?

gzip -t
