### ISSUE TITLE
Enchanted Tailor's Kit has no value

### ISSUE THREAD

**Issue by WyrdDarcnyzz** [CleverRaven/Cataclysm-DDA#46699]
# Describe the bug

Enchanted Tailor's Kit has no value in Forge of Wonders. I can get two of them for free.

# Steps To Reproduce

 
1. Go to Forge of Wonders
2. Hope they have one on hand
3. Trade value will show $0.00 

# Expected behavior

I expect these to be fairly expensive. Being a freebie is borken.

# Screenshots

 
<img width="1920" alt="Enchanted Tailor's Kit" src="https://user-images.githubusercontent.com/77361544/104376526-bf177c80-54ea-11eb-8e2e-9824e8ae20ef.png"> -->

Do not take a screenshot of the crashing window. Please provide the crash logs in the "Additional context"

# Versions and configuration

 
    - "Main menu (ESC) > Debug Menu > Info > Generate game report" to generate this report.
    - Please update your OS version with a more precise version.

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-8916-ga40bc17-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Mythical Martial Arts [MMA]
]-->

# Additional context

**Comment by PaulBlay** [comment]
Not sure why this is 'Need confirmation' it's right there in the screenshot.

![tailor](https://user-images.githubusercontent.com/54060142/104689073-cbbdef80-56f9-11eb-81a2-b4a4195ef368.png)

@WyrdDarcnyzz Check the Price and Barter Value. (i)nventory, select, [Enter] Also, how useful is one of these things?

**Comment by WyrdDarcnyzz** [comment]
Price is $0.00, no barter value at all. I imagine it's about as useful as a normal Tailor's Kit, only it slowly produces it's own thread over time. There's another item that just produces the thread by itself, Spider Box, I think. Unfortunately, this Forge of Wonders doesn't have one, otherwise I'd check the price, but I'm pretty sure it has one. Same for the Tailor's Kit, which is fairly high-end crafting equipment. I figure the one that mixes the two should be worth a little more than both items combined.

Still, I've notified KorGgenT, so he's aware of it. I figure he'll get around to it when he does.

**Comment by WyrdDarcnyzz** [comment]
Ah, guess I lied. The Spider Box also has $0.00 price and no barter value. I'm an awful person.

**Comment by WyrdDarcnyzz** [comment]
Ah nuts, this has already been reported months ago. Seems it's already being worked on.
