### ISSUE TITLE
Game stuck on emitting "You stop hauling items"

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#46710]
# Describe the bug

Whenever I press `g` to grab items, my game emits "You stop hauling items," even though I was not hauling items.

# Steps To Reproduce

1. Load attached save. << I'm an idiot and forgot to attach.
2. Press `g`.

# Expected behavior

I expect to not be told I'm hauling items when I'm not.

# Screenshots

![image](https://user-images.githubusercontent.com/13796683/104419740-e3a14200-5546-11eb-82b8-6c48aa24ef86.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 20H2 (build 19042.746)
- Game Version: 0.E-8924-gc4efd9e-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded:
    - Dark Days Ahead [dda],
    - C.R.I.T Expansion Mod [crt_expansion],
    - No Fungal Monsters [No_Fungi],
    - Disable NPC Needs [no_npc_food],
    - Alternative Map Key [alt_map_key],
    - SpeedyDex [speedydex],
    - Stats Through Kills [stats_through_kills],
    - Stats Through Skills [StatsThroughSkills]

# Additional context

I know I am not currently hauling items because of `haul()` in `handle_action.cpp`:

```
static void haul()
{
    Character &player_character = get_player_character();
    map &here = get_map();

    if( player_character.is_hauling() ) {
        player_character.stop_hauling();
    } else {
        if( here.veh_at( player_character.pos() ) ) {
            add_msg( m_info, _( "You cannot haul inside vehicles." ) );
        } else if( here.has_flag( TFLAG_DEEP_WATER, player_character.pos() ) ) {
            add_msg( m_info, _( "You cannot haul while in deep water." ) );
        } else if( !here.can_put_items( player_character.pos() ) ) {
            add_msg( m_info, _( "You cannot haul items here." ) );
        } else if( !here.has_items( player_character.pos() ) ) {
            add_msg( m_info, _( "There are no items to haul here." ) );
        } else {
            player_character.start_hauling();
        }
    }
}
```

Because my game emits "There are no items to haul here," I know that the game is returning `false` for `is_hauling()`.

Also my version string says "dirty," and I don't know why or what that means.

[Woodcock.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5807206/Woodcock.zip)

**Comment by PaulBlay** [comment]
Whoops! On the face of it that looks like something snuck in while Jamuro-g was working on this:

https://github.com/CleverRaven/Cataclysm-DDA/pull/46647

However, my game is working just fine with that change so it must have been an additional change made later.

- OS: Windows x64 8.1
- Game Version: 0.E-8914-g8c0034b-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

> Also my version string says "dirty," and I don't know why or what that means.

Mine too. I would guess it's because I have unauthorized content installed? Like a mod not included in the standard set or (in my case) UnDead People tileset?

**Comment by ToxiClay** [comment]
> Mine too. I would guess it's because I have unauthorized content installed? Like a mod not included in the standard set or (in my case) UnDead People tileset?

No; a clean download from the launcher, with nothing added, shows the -dirty string.

Build 11352 does not show -dirty; builds 11356 and beyond do.

**Comment by ToxiClay** [comment]
The commit in question is `a8eb9be449`, for those coming along behind us.

**Comment by Qrox** [comment]
The `-dirty` string means there are uncommited changes when the game was compiled.

**Comment by BrettDong** [comment]
After build 11352 I made a change to building process to pull latest translations from Transifex when building an experimental version. That's probably why there is a `dirty` flag in version string because translation data are newer than that in git.

**Comment by PaulBlay** [comment]
> However, my game is working just fine with that change so it must have been an additional change made later.

I just now noticed that my game _is_ giving extra, spurious, 'You stop hauling items.' messages. Oops? Not sure how I managed to not notice before.

BTW, the same thing has always happened when you switch to 'run' from 'walk'. You are told you stop hauling items, despite not hauling items beforehand. I think this is probably not so much a bug as a request for enhancement. e.g. When the game is told to stop your character hauling it only needs to note that in the log if you were hauling at the time.

**Comment by ToxiClay** [comment]
> When the game is told to stop your character hauling it only needs to note that in the log if you were hauling at the time.

This already is the case. It's a bug because the game is telling your character to stop hauling when you aren't.
