### ISSUE TITLE
Game crashes when doing stuff in the hub

### ISSUE THREAD

**Issue by Devengel** [CleverRaven/Cataclysm-DDA#46719]
# Describe the bug

i'm trying to raid the hub, killing the folks inside, and the game crashes randomly when using items, firing guns, etc.

# Steps To Reproduce

attack NPCs, do stuff inside the hub

# Versions and configuration

12:32:38.490 :  GAME REPORT:
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-8924-gc4efd9e-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Graphical Overmap [Graphical_Overmap],
    Safe Autodoc [safe_autodoc],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Portable Autodoc [portable_autodoc],
    No Fungal Monsters [No_Fungi]
# Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5807666/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5807667/crash.log)

[Athalia.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5807672/Athalia.zip)

**Comment by PaulBlay** [comment]
IIRC, the Hub uses some unholy technical wizardry to get the Intercom to work and isn't really supposed to be broken into. Not saying the game should crash, but it might be difficult to fix / low priority.

**Comment by Qrox** [comment]
Judging from the crash log, `Creature::is_ranged_attacker` uses the return value of `Creature::as_monster` without checking it is not a `nullptr`. The `Creature` is from the returned list of `Creature::get_visible_creatures` called in `game::is_hostile_within`, and can be an NPC.

**Comment by Devengel** [comment]
> IIRC, the Hub uses some unholy technical wizardry to get the Intercom to work and isn't really supposed to be broken into. Not saying the game should crash, but it might be difficult to fix / low priority.

i rolled to an older version, almost a week old, and i don't have crashes anymore. so i don't think whatever makes it crash is old, and i broke into the hub ages ago. so im pretty sure its something small or extremely new

**Comment by Devengel** [comment]
Deleted my comment about saying it doesnt crash if you switch to an old version(i played a while with that version, i didnt get any crashes so i assumed it safe) turns out its not, it still crashes, pls fix.
