### ISSUE TITLE
Sewing kit charge use display confusing

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#46714]
# Describe the bug

When repairing clothing with a sewing kit (probably tailor kit as well) you are told '(1 per use)' for charges of thread/sinew/whatever. However it actually uses something more like 10 thread per damage state recovered. 

# Steps To Reproduce

1. Have a sewing kit with thread loaded
2. Have a damaged item of clothing.
3. Note how many charges of thread are left.
4. (a)ctivate the sewing kit and repair the clothing.
5. Observe that a bunch more than one thread has been used.

# Expected behavior

It should either say how much thread is actually going to be used, or just not say anything about charge use. 

# Screenshots

![oneperuse](https://user-images.githubusercontent.com/54060142/104425561-bcfbff00-5578-11eb-950f-d95813418b83.png)

# Versions and configuration

- OS: Windows x64 8.1
- Game Version: 0.E-8914-g8c0034b-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

# Additional context

Same problem with battery charge use for the soldering iron when repairing (probably also Arc Welder)

**Comment by PaulBlay** [comment]
Ah, I think I see what it's doing. Each 'repair' is a result of a bunch of failures + one success and it takes a charge for each attempt. I'm not sure how that could be made clearer.

**Comment by Qrox** [comment]
`1 per attempt`?

**Comment by PaulBlay** [comment]
> `1 per attempt`?

Yeah, that would help. Maybe show some more stuff in the message log for each damage status change 'seven attempts, one failure'. Is there a more verbose / less verbose option? I seem to recall one, but I might be confusing CDDA with a different game.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
