### ISSUE TITLE
Show different sprites for sounds from other z-levels

### ISSUE THREAD

**Issue by int-ua** [CleverRaven/Cataclysm-DDA#46739]
# Is your feature request related to a problem? Please describe.
It would be very useful to immediately see if the sound is not on the same level.

# Describe the solution you'd like
It _may_ be easy to modify `cata_tiles::draw_footsteps_frame` to add z-level direction suffix for sounds from other z-levels, like `_above` and `_below`.

# Describe alternatives you've considered

# Additional context
#46646

**Comment by Maleclypse** [comment]
Closed by #46646
