### ISSUE TITLE
Inahlers in fixed spawn location still spawn with 0 charges

### ISSUE THREAD

**Issue by YourCompanionCube** [CleverRaven/Cataclysm-DDA#46738]
# Describe the bug

Military base medical vault has empty inhalers despite https://github.com/CleverRaven/Cataclysm-DDA/pull/44554

# Steps To Reproduce
Start an overrun scenario character, break into medical vault, find empty inhalers

# Expected behavior
Inhalers with 100 charges, as they were never used 

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-8914-g8c0034b-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    No Rail Stations [No_Rail_Stations],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Useful Helicopters [useful_helicopters]
]

# Additional context
I suspect other fixed spawns (and perhaps other items) may be similar
The gas masks in the warehouse may also be an example of this, they used to start loaded and now don't

**Comment by YourCompanionCube** [comment]
P.S. other weirdness like water bottles with only one portion of water, flasks of blood with only 1mL of blood

**Comment by int-ua** [comment]
Containers were intentionally made to contain **variable** amounts of stuff. Do all of them have same numbers (0,1) ?

**Comment by YourCompanionCube** [comment]
yes, every flask of blood i've found (both in the vault and outside of it) had only one charge as did all the water bottles in the warehouse, all 4 inhalers were also empty

**Comment by casswedson** [comment]
Missed these in #44554, will fix them later. https://github.com/CleverRaven/Cataclysm-DDA/blob/9483769064d4cf80d49f7cd4a2d69569aa067f8a/data/json/mapgen/military/mil_base/mil_base_z0.json#L1129
https://github.com/CleverRaven/Cataclysm-DDA/blob/9483769064d4cf80d49f7cd4a2d69569aa067f8a/data/mods/Aftershock/npcs/cyborg_npcs/item_groups_cyborg.json#L219


> 
> 
> Containers were intentionally made to contain **variable** amounts of stuff. Do all of them have same numbers (0,1) ?

A decent portion (maybe 15% not sure on this, there is just a lot of JSON dedicated to item spawn, it's hard to review) of all item spawn are still spawning the same amount or none at all of items/charges, I am looking into this but it takes a bit of time.

**Comment by YourCompanionCube** [comment]
thanks a ton for the work you do
