### ISSUE TITLE
Charge usage of Electric Jackhammer is broken (still / again).

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#46742]
# Describe the bug

When you have a fully charged Electric Jackhammer (optionally with a UPS) the jackhammer will not lose charges (even after the UPS runs out).

# Steps To Reproduce

1. Have a UPS (I used a UPS with battery compartment mod and a car battery)
2. Have an electric jackhammer (I crafted my own)
3. (a)pply jackhammer to a wall or solid rock.
4. Repeat (3) until UPS has no charge.
5. Note that jackhammer has exactly 7000 charges left when the UPS is at zero.
6. (a)pply jackhammer to another wall.
7. Note that the jackhammer still has 7000 charges

If you don't have a UPS it still won't lose charges from the Jackhammer's 7000.

# Expected behavior

Charge should be lost from the 'internal capacity' of the electric jackhammer

# Versions and configuration

- OS: Windows x64 8.1
- Game Version: 0.E-8914-g8c0034b-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

# Additional context

Real life electric jackhammers have a power cord that goes to mains electricity or a portable generator.
See https://healthyhandyman.com/best-electric-jack-hammers/ for instance. That would, IMO, make more sense than an implausibly large internal battery and a UPS of dubious worth (how does the UPS work, anyway? Microwave energy transmission, lots of wires?)

**Comment by PaulBlay** [comment]
![jackhammer](https://user-images.githubusercontent.com/54060142/104604972-d59e0f00-5675-11eb-956b-ce942259b50d.png)

7000 before, and after. Do you need a video capture? Because I could do that.

**Comment by JackReport** [comment]
Also have this issue

**Comment by PaulBlay** [comment]
@JackReport Could you post your game version info? 

@int-ua Is that good enough 'confirmation' now?
