### ISSUE TITLE
Not all languages in the lang/mo directory are available for selection in game settings

### ISSUE THREAD

**Issue by int-ua** [CleverRaven/Cataclysm-DDA#46751]
# Describe the bug

The selection of available languages does not contain some languages that have a respective file in `lang/mo` dir.

# Steps To Reproduce

1. Create a list of folders in `lang/mo` [1]
2. Open game settings, try listing available translations.
3. Open `config/options.json` and find the USE_LANG option Values list [2]

[1] `ar, cs, da, de, el, en, es_AR, es_ES, fr, hu, id, is, it_IT, ja, ko, nb, nl, pl, pt_BR, ru, sr, tr, uk_UA, zh_CN, zh_TW`

[2] `en, de, es_AR, es_ES, fr, hu, ja, ko, pl, pt_BR, ru, zh_CN, zh_TW`

# Expected behavior

All languages are available.

# Screenshots

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.1 LTS; Release: 20.04; Codename: focal;
- Game Version: 0.E-8924-gc4efd9e-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

The game is still translated when selecting System language and having one of the unavailable ones in locale settings even though the language itself is not in the list for selecting manually.

Discovered while trying to confirm #45238

**Comment by ZhilkinSerg** [comment]
Yes, we only allow explicit selection of languages that have sufficiently high number of translated strings.

**Comment by actual-nh** [comment]
I have to wonder if in some cases it would be preferable to show what's available, and fallback to a similar language for the rest. (Does it already work this way for, say, es_AR and es_ES?) Originally, I was thinking of Portuguese and Spanish, which doesn't seem needed right now, but I believe there are some other very-close languages (in Scandinavia, for instance).
