### ISSUE TITLE
Demangle C++ symbols in backtrace

### ISSUE THREAD

**Issue by BrettDong** [CleverRaven/Cataclysm-DDA#46758]
# Is your feature request related to a problem? Please describe.
Stack traces are showing mangled C++ symbols. It would make life a little easier if symbols are demangled.

# Describe the solution you'd like
Show demangled symbol names in stack trace.

# Describe alternatives you've considered
N/A

# Additional context
I ran across this that may be helpful: https://gcc.gnu.org/onlinedocs/libstdc++/libstdc++-html-USERS-4.3/a01696.html

**Comment by Cyprex** [comment]
Do mangled names differ between gcc and clang?

**Comment by Qrox** [comment]
> Do mangled names differ between gcc and clang?

Different compilers may mangle the names differently.
https://en.wikipedia.org/wiki/Name_mangling#How_different_compilers_mangle_the_same_functions

We can start with GCC though, since it's used for the official build which is the most likely version players will be using.

**Comment by BrettDong** [comment]
This has been implemented in #47486, #47517, #47621, #48152 for MinGW, Linux, macOS and BSD systems.
