### ISSUE TITLE
Shoelaces should exist.

### ISSUE THREAD

**Issue by therealsnowmann** [CleverRaven/Cataclysm-DDA#46753]
# Is your feature request related to a problem? Please describe.
Most footwear have laces. Currently laces are non-existent. IRL, if I need some string or lashing, and I have none, I should need only look down at my shoes, and ask myself if it is worth not wearing them, or having them not fit to craft this thing depending on the situation I'm in. Also, if I find more shoes, or kill a zombie with shoes, Being able to take the laces from them could prove very useful should I not want to sacrifice my own, or to lace the shoes I did take them from so I can use them effectively again. I think it would be a nice option for early game, and could affect the approach of many scenarios.

# Describe the solution you'd like

I dont know terribly much about the coding stuff. There might be an easier way, my logic might be flawed, you know better than I do, so please bear with me.

 - Create a new item, "Set of Laces"
 - Create a new tag "Unlaced"
 - Set of laces can be crafted with 2 long strings, and disassembled into 2 long strings with no skill, time, or failure rate, essentially they are the same thing, but it turns 2 items into one, which I think is needed to do the next part.
 - Set of laces has the ability to remove the "Unlaced" tag. It consumes itself in the process.
 - Any footwear with laces can be activated to remove the laces. You get a set of laces. The tag "Unlaced" is then added. 
 - "Unlaced" comes with an encumbrance and movement penalty and the description "This footwear has no laces, they are very loose, and much harder to move in." The penalty for fitted footwear is the same as ones that do not fit, maybe even a little more since even footwear that fits you when unlaced can fall off easily, unfitted footwear stacks penalties, and impacts movement speed moderately bad.
 - Set of laces can spawn in clothing stores, or anywhere clothing or shoes is a focus. Also less frequently at drug stores, dollar stores, etc. Anywhere they would normally be sold. In houses, junk drawers (maybe replace the long strings with sets of laces?) rarely in in dressers and desks.

# Describe alternatives you've considered

1.) A more in depth version of this that I originally wrote. It included things that could happen feasibly with unlaced shoes, like them having a chance to fall off depending on how you are moving, the ability to kick them off quickly since they are so loose, and having them affect combat by losing your footing. It grew from there to essentially examine anything in the game that is tied with any form of string, lashing, or lace to logically find anywhere it can be obtained. It turned into a sort of crafting system "overhaul" of sorts, since untying something is easy in almost any case, but since retying is dependent on the item, the new proficiency system would be applied. A whole new set of "in-between" items and recipes for them are needed where the knowledge is applied separately. First each component would need to exist, and making them would use their respective skills/proficiencies, and then the assembly using its skills/proficiencies. Eg. a character finds a leather baldric, and unties it to get the lashing to assemble a spear. You would still have the pieces to that baldric, prepared completely as components to be retied. It respects the logic that the character doesn't need the skills, proficiencies, or tools to actually make those pieces, just enough skill to be able to tie them back together. The game doesn't currently account for that.  I like this idea, but it is beyond the scope of this suggestion.

2.) A simpler version of this, that only adds long string as an output when cutting up shoes and boots that would have laces, and adding long string as a requirement for crafting footwear where applicable, I dont like this much since IRL, you wouldn't actually HAVE to destroy the shoes to get the string out to use, and it detracts somewhat from its usefulness in an early game scenario since you will need a cutting tool to do it, and destroy a useful item, but it still makes sense you should get some string from shoelaces.

# Additional context

Example scenario. 

Day 60, Surrounded by zombies, hiding in the hallway of a zoo. I escaped the one that was chasing me, and now Im hiding in the maintenance room. Luckily, they have calmed down, and I have time to think. There is a broom in the corner, and I find a knife when searching the desk. Looking at my map I need to plan my escape from this town, and be careful since I dont have much gear for protection, and there really isnt anywhere to run that I will be safe if I get overwhelmed. I have to be smart. A spear would be nice. I can use it to keep my distance and mitigate the amount of damage i take, if I can secure an area, I can move forward at pace, making sure I plan ahead by moving things around so if I end up getting overwhelmed I can backtrack and use the environment against them. Having the ability to keep my distance will really help me a lot. I have the broom, and the knife, but no string. I look down at my sneakers, and sigh.

**Comment by guralub** [comment]
I think we can skip adding a new item and directly give 2 long strings. It's essentially the same. Also, I don't know if it would be possible but maybe just adding the poor fit flag to the item without shoelaces would be better than creating a new state for every shoe that this interaction would apply.

**Comment by calibraptor** [comment]
You can't really effectively wear a pair of shoes without laces typically. Just add string to the potential items you can get when deconstructing them.

**Comment by PaulBlay** [comment]
Long string is like really long. You get them from curtains. I think short strings from shoes are more sensible.

**Comment by ThomasLinkin** [comment]
this is pretty much like how belt were created to fit unfitted clothes onto the character, but with shoes

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
