### ISSUE TITLE
[0.E-3]  ferns nearly indestructible

### ISSUE THREAD

**Issue by busterbogheart** [CleverRaven/Cataclysm-DDA#46769]
Smacking into ferns with a 6 ton hummer stops it dead.  (Equipped with spikes, plating, etc)  Has happened multiple times.

Unless i'm missing something in the lore, this probably shouldn't happen.

Win 7
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

![Untitled-2](https://user-images.githubusercontent.com/19196781/104742371-59103c80-5718-11eb-847c-31991b0d8631.jpg)

**Comment by busterbogheart** [comment]
Smashing the fern allows me to continue through

**Comment by int-ua** [comment]
Cannot reproduce on build 11360, don't have 0.E-3 downloaded.

**Comment by PaulBlay** [comment]
I tested this on 11357. Drove at 40mpg into a fern with my hefty motorcycle, it smashed through with no damage to the vehicle and slowed down to 11mpg.

**Comment by int-ua** [comment]
I've downloaded `0.E-3` and cannot reproduce either. 4x4 car destroyed two ferns in a row easily, without any damage visible. Please try testing more and improve your steps to reproduce.
