### ISSUE TITLE
Combat mech "consumes" your gun if you have an arm broken

### ISSUE THREAD

**Issue by Devengel** [CleverRaven/Cataclysm-DDA#46764]
# Describe the bug

"grunt" combat mech does not use its laser cannon if one of your arms is broken, it will ask you to draw your own guns if you use the [f]ire command, which will make the selected gun disappear

# Steps To Reproduce

spawn combat mech
break one of your arms
give yourself a gun, any will suffice
get inside the mech
try to fire, it will ask you to draw your gun
draw the gun
now the mech uses the gun until you dismount, then the gun will disappear
the cycle repeats until you have both of your arms functional, in which case the mech uses its laser cannon.

# Expected behavior

the mech using its laser cannon

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-8965-gad0e7ae-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Graphical Overmap [Graphical_Overmap],
    Safe Autodoc [safe_autodoc],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Portable Autodoc [portable_autodoc]
]

**Comment by Svankensen** [comment]
Yeah, mechs use some workarounds to reach the desired effects. Their weapons can't be unwielded to prevent you from doing other stuff with them (if you debug spawn one of them and grab it with your normal survivor, you are stuck with it). I suspect that is the cause of this bug. Game generates a ghost weapon, then deletes it? It fails to generate the weapon, so it deletes the one you are wielding?
