### ISSUE TITLE
Magiclysm: Orc Archer not spawning with loaded bow

### ISSUE THREAD

**Issue by Theawesomeboophis** [CleverRaven/Cataclysm-DDA#46779]
# Describe the bug
Orc Archer bows are not spawned with arrows.

# Steps To Reproduce
1. Debug spawn or find orc archer in world.
2. Kill orc archer and loot.
3. Orc archer has no arrows for bow.

# Expected behavior
Orc Archer bows should spawn with arrows.

# Versions and configuration

 - OS: Windows 8.1
 - Game Version: 1.B (tiles)
 - Graphics version: Tiles

 - Mods loaded:  [ "dda", "package_bionic_professions", "BL9_100monres", "secronom", "sierra_madre", "aftershock", "Arcana", "blazeindustries", "crt_expansion", "magiclysm", "PK_REBALANCE", "collectablemod", "adv_gear", "Arts' Guns", "Bootleg_Walkers", "fallout", "Medieval_Mod_Reborn", "DinoMod", "World_on_fire", "Youkai_Disco", "Cata++", "crazy_cataclysm", "my_sweet_cataclysm", "MMA", "vamp_stuff", "vamp_stuff+arcana", "zets_hair_extensions_undead", "Dorf_Life", "adv_gearUDP", "AftershockUDP", "ArcanaUDP", "Arts' GunsUDP", "BL9_100monresUDP", "BlazeIndustriesUDP", "Bootleg_WalkersUDP", "crt_expansionUDP", "Cata++UDP", "CrazyCataclysmUDP", "DinoModUDP", "Dorf_LifeUDP", "Fallout_CDDA_UDP", "MagiclysmUDP", "Medieval_Mod_RebornUDP", "secronom_UDP", "PK_REBALANCE_UDP", "sierra_madreUDP", "vamp_stuff_UDP", "WHALEYHAIR_UDP", "Graphical_Overmap", "Graphical_Overmap_Magiclysm", "My_Sweet_CataclysmUDP", "MMAUDP", "fuji_mpp", "Graphical_Overmap_SDG", "darkskies_alt", "darkskies_altUDP" ]

# Additional context
Looking for suggestions on how to fix, as it was something I noticed while playing.

**Comment by actual-nh** [comment]
Could you check the patch I just put up? The JSON validator isn't giving any errors.

**Comment by Theawesomeboophis** [comment]
I will test it and report back.

**Comment by actual-nh** [comment]
> I will test it and report back.

Well, you may want to wait a sec - I didn't spot that "extends" was already in the JSON, and the JSON formatter doesn't seem to check for duplicate tags. I've just fixed that, I think...

**Comment by Theawesomeboophis** [comment]
I'm busy at the moment, I'll test it in the next hour or so.

**Comment by actual-nh** [comment]
Not a problem at all.

**Comment by casswedson** [comment]
Fixed by #46780

**Comment by Theawesomeboophis** [comment]
Oops I forgot to close this.

**Comment by Theawesomeboophis** [comment]
Thanks, I'm on mobile and I don't know how to delete.
