### ISSUE TITLE
Adding UPS Conversion Mod to E-Ink Tablet makes it unable to play music.

### ISSUE THREAD

**Issue by Churby** [CleverRaven/Cataclysm-DDA#46773]
I added a UPS conversion mod to my E-Ink Tablet with all of my music on it.  Upon attempting to play the music I receive the message: "You turned on the music on your e-ink tablet PC+1 (UPS) (active)*.
The tablet's batteries are dead." despite having charged UPSs available

# Steps To Reproduce

1. Download music onto e-ink tablet PC
2. install a UPS conversion mod
3. have a charged UPS in your inventory or worn
3. activate the tablet and try to play music

# Expected behavior

I expect the music to play and use charge from my worn UPSs

# Versions and configuration

Please complete the following information; you can now go to:
   - OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-8970-g4c41789-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    <color_light_red>Secronom</color> [secronom],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    C.R.I.T Expansion Mod [crt_expansion],
    Engineering essentials [EngineeringEssentials],
    Generator mod [generatormod],
    Magiclysm [magiclysm],
    Magiclysm Revamp and Additions [magicrevamp],
    Nechronica Redux [Nechronica_Redux],
    PKs Rebalancing [PK_REBALANCE],
    Mutant NPCs [mutant_npcs],
    Psychiclysm [psychiclysm],
    Whaleys Collectables [collectablemod],
    Add Rice [rice],
    Advanced Technologies [advtech],
    Armor Up! Survivor Expansion [ArmUpSurvEx],
    Arsenal Breach [arsenal_breach],
    Artyoms' Gun Emporium - Reloaded [Arts' Guns],
    Bens GF recipes [Tolerate_This],
    BioCo Content [bioco],
    Bionic Space Expander [Bionic_Space_Expander],
    Bionics Systems Recipes [bio_recipes],
    Bootleg Walkers [Bootleg_Walkers],
    CBM Equipment [CBM_Arms],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Dried Fruits [dried_fruits],
    Expanded Archery [ExArch],
    Gourmand's Graces [Gourmand'sGraces],
    Gun Cotton [guncotton],
    Homestead Instruments Inc. [homestead],
    Icecoon's Arsenal [ew_pack],
    Large capacity storage CBMs [eps_cbm],
    Locked and Loaded [Locked_and_Loaded],
    Makeshift Items Mod [makeshift],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    Miscellaneous Magiclysm Expansions [demon_spider_a],
    Modern Weapon Pack Expanded [modern_weapon],
    MST Extra [MST_Extra],
    Mythological Replicas [nw_pack],
    Nimian Manufacture Guns [NM_wpns],
    Ricky's Future Armory [futurearmory],
    Rivtech Beam Swords [beamswordmod],
    Flowerpot (uekibati) mod [Uekibati_mod],
    Soy mod [Soy mod],
    The Cool Mod [cool_mod],
    The Glory Of Cereal! [CerealMod],
    Thermal Electric UPS [thermal_ups],
    Wild Living [WildLiving],
    Compatible Add Bandits [GOV_BANDITS],
    Crazy Labs [crazy_labs],
    Draco's Dog Mod [DracoDogMod],
    Draco's Pig Mod [DracoPigMod],
    Jury-Rigged Robots [jury_rigged_robots],
    Modular Turrets with No Blacklist [modular_turrets_no_blacklist],
    Mutant Animals [mutant_animals],
    Mutant Insects [mutant_insects],
    Cataclysm++ [Cata++],
    PRM++ Patch [noctpk],
    Salvaged Robots [Salvaged_Robots],
    World on Fire [World_on_fire],
    Mythical Martial Arts [MMA],
    <color_yellow>Mythical Martial Arts - Mods Extension</color> [MMA_Mods_Extension],
    Alternative Map Key [alt_map_key],
    Even More Mutations [even_more_mutations],
    Food Irradiator [food_irradiator],
    Hydroponics [hydroponics],
    Mining Mod [Mining_Mod],
    More Survivor Notes [more_survivor_notes],
    More Survivor Stuff [more_survivor_stuff],
    NPC Recruitment Options [recruitment_options],
    Tekitou Map Commercial Overhaul [tekitoumap],
    Vampiric Stuff [vamp_stuff],
    Vampiric Stuff + Arcana Mod Extension [vamp_stuff+arcana],
    Wandering Masters [wandering_masters],
    Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
    More Locations [more_locations],
    Zet's Hair - More Locations [zets_hair_ext_more_locations],
    Zet's Hair - PKs Rebalancing [zets_hair_ext_pk_rebalance],
    Dorf Life [Dorf_Life],
    EXTENDED_BUILDINGS [ZSFixed_Extended_Buildings],
    More City Locations [cityside],
    No Rail Stations [No_Rail_Stations],
    Morlock Village [morlock_village],
    Ships From Oa Additional Buildings [Ships],
    Water Towers [water_towers],
    Whaleys TALL Buildings [whaleys_tallbuild],
    Folding Parts pack [deoxymod],
    Blazemod - Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tankmod: Revived [Tankmod_Revived],
    Graphical Overmap [Graphical_Overmap],
    Merchant Mod [Merchant],
    Fuji's Military Profession Pack [fuji_mpp],
    Military Professions Mod [More_Military],
    Safe Autodoc [safe_autodoc],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

Have not had any trouble using UPS conversion mod for my arc welder and soldering iron,

**Comment by Churby** [comment]
Sorry, I had more info filled into the subsections but it looks like the formatting ate it or something.

**Comment by PaulBlay** [comment]
Try editing your original post. You might have some stray comment code around your text (the &lt;-- )

**Comment by PaulBlay** [comment]
Holy heck that's a lot of mods.  Anyway, I just tested this with a much more modest mod selection and I can confirm the bug.

- OS: Windows x64 8.1
- Game Version: 0.E-8914-g8c0034b-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

**Comment by PaulBlay** [comment]
@BrettDong How much confirmation does it need? I already posted that the bug shows up on my game / computer.
