### ISSUE TITLE
There are different kinds of strong mixed alcohol 

### ISSUE THREAD

**Issue by ynemo** [CleverRaven/Cataclysm-DDA#46786]
# Describe the bug

I made Strong Mixed Alchogol from different drinks. And now i cant mix them in one container. I cant Unload one container to another, second container with mixed alcohol are not showing up as target container.  I am sure there is free space in it. 

When i reFill vehicle tank with first mixed alcohol and then try to refill same tank with second, i recive 
![image](https://user-images.githubusercontent.com/24881844/104806594-cb048680-57e9-11eb-84b7-b4b75b48165f.png)

# Expected behavior

Mixed alchogol should mix in one container.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-8972-g8041d14-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]

# Additional context

save file:
[Vansant.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5824050/Vansant.zip)

**Comment by PaulBlay** [comment]
This is probably the same problem as 
https://github.com/CleverRaven/Cataclysm-DDA/issues/44791 (which was fixed specifically for clean water only)
and 
https://github.com/CleverRaven/Cataclysm-DDA/issues/46470 (still open, broth)

Liquids can contain component information, and liquids of different components are not able to be mixed together. Also, the component information is sometimes lost for unknown reasons.

You could probably do the same fix for 'weak mixed alcohol' and 'strong mixed alcohol' as was done for clean water but at some point it might be better to address the root issues.

**Comment by Qrox** [comment]
> the same fix

Water can be fixed that way because any water can be considered to have the same nutrients (that is, none), but differently mixed alcohol may have different nutrients.

**Comment by PaulBlay** [comment]
> differently mixed alcohol may have different nutrients.

True, but in my experience the basic reason for mixing weak and strong alcohol in game is to craft denatured alcohol from it. 

For a more general discussion I have a relevant post here 
https://github.com/CleverRaven/Cataclysm-DDA/issues/46091#issuecomment-748438592

**Comment by Hirmuolio** [comment]
Can the nutrients be set to arbitrary values or are they always tied to the components?

Mixed liquids can't be disassembled so the components don't matter. The nutrients could be just averaged when the liquids are mixed.

**Comment by Qrox** [comment]
Nutrients are calculated from the components if no nutrient override is set. I suppose we can just store the average nutrients without storing the components though.

**Comment by anothersimulacrum** [comment]
That will break conditional naming, though, will it not?

**Comment by Qrox** [comment]
Anything conditional (conditional naming or allergies) can be saved as an id when creating the item. It might need intensive overhaul though.

**Comment by ynemo** [comment]
same problem with other drinks. There are different kinds of  Cabernet Sauvignon and etc

**Comment by RenechCDDA** [comment]
Resolved by #54799
