### ISSUE TITLE
Crush entering Faction Camp

### ISSUE THREAD

**Issue by ynemo** [CleverRaven/Cataclysm-DDA#46794]
Cant come back to my camp, game crush.

One NPC is probably chopping logs, and other one building new part of camp. 

# Screenshots
![image](https://user-images.githubusercontent.com/24881844/104809952-50943080-5802-11eb-97c3-28ccfd3c8c88.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-8972-g8041d14-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]

# Crash.log
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5824242/crash.log)
# Save zip
[Vansant.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5824246/Vansant.zip)

**Comment by PaulBlay** [comment]
@ynemo I downloaded your save. Where is your camp?

**Comment by ynemo** [comment]
just drive forward, camp to the N and little W, called "Pobeda" on map. You should be right next to it.

**Comment by PaulBlay** [comment]
> You should be right next to it.

Haha, OK. Yeah, that crashes alright. 

Good news, bad news. 
Good news, if you teleport NW past the camp you can walk into it from that side.
Bad news, it crashes just past the middle of the camp (as you walk SE).

![crash](https://user-images.githubusercontent.com/54060142/104813906-e67c8b00-5803-11eb-9423-ae863055a9f4.png)

- OS: Windows x64 8.1
- Game Version: 0.E-8914-g8c0034b-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by PaulBlay** [comment]
Whatever is causing the crash is around about where the big red X is on this map.

![crashwhere](https://user-images.githubusercontent.com/54060142/104815568-44fa3700-580d-11eb-905e-1e8c164d2756.png)

It might be possible to delete the right map file so you can keep playing this save.

**Comment by Qrox** [comment]
`process_map_items` calls `colony::get_iterator_from_pointer` which asserts that the colony is non empty so a `SIGABRT` was raised. Checking that the colony is not empty before calling the method should fix the crash. There might be some other bug that caused the colony to be empty when the method is called though.

**Comment by ynemo** [comment]
> Whatever is causing the crash is around about where the big red X is on this map.
> 
> ![crashwhere](https://user-images.githubusercontent.com/54060142/104815568-44fa3700-580d-11eb-905e-1e8c164d2756.png)
> 
> It might be possible to delete the right map file so you can keep playing this save.

i know what is there!!

there is a bugged vehicle.
i dont remember it's name. It's 2 tile vehicle with refrigerator and kitchen unit, it could be found in parks. 

The story is:
A long time ago I found two same 2 tile vehicles and put them together on my bike rack. When i remove one of them, they bagged. I suppose it's because they had same names. One vihicle overides other few times. So in result there is vihicle with lets say 6 kitcken units on one tile and 6 refrigerators on other tile. 

I decided to drop this bugged vehicle in water ;) so it is somewhere around your mark.

**Comment by PaulBlay** [comment]
> i dont remember it's name. 

It's a pity you don't know the name. If you did, it would be easy to search for it in the files.

**Comment by ynemo** [comment]
![Uploading image.png…]()

**Comment by ynemo** [comment]
![image](https://user-images.githubusercontent.com/24881844/104818714-4ee65f00-583a-11eb-9b0f-9ebaba975f96.png)
[Vansant1.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5824839/Vansant1.zip)

I found old save, i stand next to this vehicle

**Comment by ynemo** [comment]
btw, if the vehicle is the problem, should i create new issue about bike racks cause this bug? Or is it better to change lables here?
A friend of mine got the same bug with collided parts when he put two same vehicles on the rack and then remove one of them.

**Comment by PaulBlay** [comment]
> if the vehicle is the problem, should i create new issue about bike racks cause this bug?

You shouldn't be able to put two vehicles on the same bike racks (or two vehicles on different bike racks attached to the same vehicle). That probably should be a separate bug, to avoid confusion.

I will see if I can find the right 'food vendor cart' and delete it from your save. It should be doable.

**Comment by ynemo** [comment]
> I will see if I can find the right 'food vendor cart' and delete it from your save. It should be doable.

would be cool ;)  really, thanks

**Comment by PaulBlay** [comment]
[Vansant.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5824869/Vansant.zip)

Done and tested.

If you make a new issue with the steps to putting two vehicles on the same bike rack (or whatever you did) this one could probably be closed.

**Comment by ynemo** [comment]
cool. all works. Thank you!
I will try to reproduce the bug with two vehicles on bike racks, and make a new post if I succeed
