### ISSUE TITLE
Missing tiles in cone spell aim coverage. Too many tiles in AoE spell coverage

### ISSUE THREAD

**Issue by Salty-Panda** [CleverRaven/Cataclysm-DDA#46792]
# Describe the bug

Spells don't aim at all tiles they should.
Missing tiles in aiming coverage.
Spells with AoE range of e.g. 1.05 are displayed as range 2 but the damage range is 1.

# Steps To Reproduce

Spawn a few spells with cone/AoE range, set them to various levels, try aiming.

# Expected behavior

No missing tiles in aiming
Deals damage to all targets in AoE range

# Screenshots

Jolt, cone, lvl 9
![image](https://user-images.githubusercontent.com/26396019/104809396-3c920400-57ed-11eb-9706-f2ad83bed454.png)
![image](https://user-images.githubusercontent.com/26396019/104809411-53d0f180-57ed-11eb-8fba-0b9af96d674a.png)

Lighting Blast, lvl 5
Deals damage only to the enemy at the target, AoE doesn't work
![image](https://user-images.githubusercontent.com/26396019/104809734-9267ab80-57ef-11eb-95f5-33b7a9f6cbe8.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-8972-g8041d14-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Mythical Martial Arts [MMA],
    C.R.I.T Expansion Mod [crt_expansion],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Bionic Professions [package_bionic_professions],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP]
]

**Comment by Tevervin** [comment]
Can confirm, all cone spells has empty spaces in AoE when aiming diagonaly. Cone of Cold at a first level does not have empty spaces, but 20 it has.
Also Blinding Flash at lvl 5 has 3x3 AoE, but blinds and damages only targeted enemy, at lvl 20 AoE works fine.

**Comment by actual-nh** [comment]
This is essentially a form of shadowcasting problem. `spell_effect_cone_range_override` (in magic_spell_effect.cpp) is scanning through the cone 1 degree at a time, casting a line using Bresenham's algorithm (invoked by `line_to`). I think what may be needed is a bit of 'jitter' of the (defaulting to 0) `t` parameter - you might actually be able to get away with scanning 2-3 degrees apart, if each line was done 3 times with a `t` of 1, 0, -1.

**Comment by actual-nh** [comment]
@Mrzjadacz, you might want to change the title to "Missing tiles in spell aim coverage".

**Comment by actual-nh** [comment]
Ping: @Aivean (as well as @KorGgenT) - do you think what I suggested above would work?

**Comment by Aivean** [comment]
The easiest fix I can envision is to replace `line_to` calls with one additional loop over range:

```cpp
for( units::angle angle = start_angle; angle <= end_angle; angle += 1_degrees ) {
   for( int range = 0; range <= params.range; range++ ) {
        tripoint potential;
        calc_ray_end( angle, range, source, potential );
        targets.emplace( potential );
    }
}
```

This also simplifies the logic quite a bit.

**Comment by actual-nh** [comment]
I can try patching that in sometime soon (1/19/2021 or this weekend, I think), if @Mrzjadacz or someone could do the testing.

**Comment by KorGgenT** [comment]
i'm gonna call this one good; i'm not concerned with extra tiles in the aoe, and the above pr fixed the holes.
