### ISSUE TITLE
Lack of clear warning when repairing can only cause damage (with Sewing Kit, Tailor Kit, etc.) 

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#46803]
# Describe the bug

When using a sewing kit to repair items there are cases where there is no chance of success <s>and you also don't advance your Tailor skill at all</s>.

# Steps To Reproduce

1. Prepare a pile of IFAK pouches 
2. Run them over with a car to damage them
3. Set your character's tailor skill to 5
4. Give tailor a lot of rags, thread and a sewing kit
5. 'repair' IFAK pouches until you get bored. (Note that there is 0.0% success rate per attempt, and 5.0% damage rate per attempt)
<s>6. Check your Tailor skill advancement.
7. Note that there is no advancement.</s>

# Expected behavior

I would like a clear warning that what I'm doing is literally pointless, wasting thread, time and items being 'repaired'.

# Screenshots

![sewingkitrepair](https://user-images.githubusercontent.com/54060142/104819125-5d754c00-5823-11eb-997d-397bdb5ff65a.png)

As you can see I destroyed 30 IFAK pouches (and over 1000 thread).

# Versions and configuration

- OS: Windows x64 8.1
- Game Version: 0.E-8914-g8c0034b-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

# Additional context

Save file from before I started 'repairing' stuff.

[sewingkitrepair.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5824855/sewingkitrepair.zip)

The repair system seems a bit weird to me as a whole. You sew up stuff like 5 or 10 times, removing the stitches each time you mess up, until you finally get it right or throw the whole thing away.

**Comment by int-ua** [comment]
AFAIU, the no-advancement part is intended, so issue is the lack of warning, right?

**Comment by PaulBlay** [comment]
I don't know why you wouldn't improve tailoring by repairing things, but if that discussion has been done then, yeah. A clear warning - even if it is after you first damage the article you are working on - would be both useful and, IMO, realistic. "(You damage the IFAK pouch.) You don't think you are getting anywhere with this."

**Comment by int-ua** [comment]
Confirmed that the described behavior is present by following steps to reproduce Adding `Suggestion / Discussion` label as I'm pretty sure the no-advancement part is intended.

**Comment by int-ua** [comment]
Please update title if you agree. Something like "Lack of warning about the absence of tailoring skill gain on repairing things"

**Comment by PaulBlay** [comment]
OK. I'm dubious about why no advancement is intended, but that's a different argument for somewhere else.
