### ISSUE TITLE
Can not find bicycle wheel by searching for 27 in the [i]nstall menu

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#46800]
# Is your feature request related to a problem? Please describe.
I the vehicle manifest menu (e -> [e]xamine wehicle) a bicycle wheel is displayed as "27"&nbsp;bicycle&nbsp;wheel", but in the [i]nstall menu it is displayed as "bicycle&nbsp;wheel". I wanted to install a bicycle wheel, went into the [i]nstall menu, searched for 27 and was surprised to find nothing.

# Describe the solution you'd like
In both menus the name should be the same. Either "27"&nbsp;bicycle&nbsp;wheel" or "bicycle&nbsp;wheel"

# Describe alternatives you've considered
Leave as is

# Additional context
none

**Comment by PaulBlay** [comment]
There are a bunch of vehicle parts that have a different name when installed (or being installed) than they do when they are laying around on the ground. I don't know if anyone made an official Issue in github about it before but I agree it's not ideal.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
