### ISSUE TITLE
Funnel produces more plastic chunks than it takes to craft

### ISSUE THREAD

**Issue by WatermelonsEverywhere** [CleverRaven/Cataclysm-DDA#46801]
When crafting a funnel, it consumes 3 plastic chunks but if you take this same crafted funnel and cut it apart, you get 10+ plastic chunks, sometimes even twelve, allowing you to replicate plastic chunks infinitely.

# Steps To Reproduce

1. Craft a funnel
2. Take funnel aside and put it on the ground
3. Cut it apart by (B)utchering, recieve more plastic than you started with.

# Expected behavior

For the funnel. upon being cut apart, to drop 3 plastic chunks at a maximum, but often only one or two.

# Screenshots

![image](https://user-images.githubusercontent.com/21104734/104819230-bdeb9580-57f1-11eb-99f3-85b8eaed6d2d.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-8821-ged07fdc [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Graphical Overmap [Graphical_Overmap],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by PaulBlay** [comment]
Tested with 10 funnels, can confirm.

![funnel1](https://user-images.githubusercontent.com/54060142/104819962-52251f00-5829-11eb-9a60-a563bfcc4557.png)

![funnel2](https://user-images.githubusercontent.com/54060142/104819963-56e9d300-5829-11eb-9d67-a91be450f22e.png)

- OS: Windows x64 8.1
- Game Version: 0.E-8914-g8c0034b-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/the-need-confirmation-tag-in-github/25708/12

**Comment by shahezad96** [comment]
![funnel_weight](https://user-images.githubusercontent.com/10199441/106434884-25633f80-6498-11eb-913e-aa0912112520.JPG)

am i right? i already confirmed though!

**Comment by PaulBlay** [comment]
@BrettDong If what shahezad96 says is correct, and I expect so, then maybe this gets JSON and Good First Issue labels?
