### ISSUE TITLE
Make Rakes usable. Cant remove mess from butchering. (shards of chitin, bug legs) 

### ISSUE THREAD

**Issue by ynemo** [CleverRaven/Cataclysm-DDA#46828]
# Is your feature request related to a problem? Please describe.
I made field butchery of centipede at my base, and there are a lot of mess i cant remove with Mop.
![image](https://user-images.githubusercontent.com/24881844/104836983-b811b500-58c2-11eb-9a85-5c8014441309.png)
it's Shards of chitin, shattered bug legs, torn insect organs maybe there are other such objects i cant take. 
# Describe the solution you'd like
I suggest to remove them with Rake (all kind plastic or metal, maybe there is other rakes). 
The mechanic should be similar to using mop.

**Comment by int-ua** [comment]
What exactly is impossible to remove with a mop? IIRC last time I butchered something at my base (quite long time ago) I was able to clear most of such fields with a mop.

**Comment by ynemo** [comment]
> What exactly is impossible to remove with a mop? IIRC last time I butchered something at my base (quite long time ago) I was able to clear most of such fields with a mop.

Ну я же перечислил специально все наименования, которые не смог вычистить шваброй.

**Comment by int-ua** [comment]
It looks like a bug because other fields like these are cleanable. I'll try to take a closer look tomorrow.

**Comment by int-ua** [comment]
It happens because their phase is solid: 
https://github.com/CleverRaven/Cataclysm-DDA/blob/59c9b3eeb5f46ac149d671fdea6d2603b214124c/data/json/field_type.json#L898

And mop only supports cleaning liquids:
https://github.com/CleverRaven/Cataclysm-DDA/blob/59c9b3eeb5f46ac149d671fdea6d2603b214124c/src/iuse.cpp#L5314

But they should be cleanable in my opinion too so I'm labeling this as a bug.

**Comment by int-ua** [comment]
I'd suggest just making the field phase liquid and tuning the name because the solids are represented by the butchery refuse item now.

**Comment by int-ua** [comment]
This can be workarounded / fixed by changing these values to `liquid`: 
https://github.com/CleverRaven/Cataclysm-DDA/blob/59c9b3eeb5f46ac149d671fdea6d2603b214124c/data/json/field_type.json#L912
https://github.com/CleverRaven/Cataclysm-DDA/blob/59c9b3eeb5f46ac149d671fdea6d2603b214124c/data/json/field_type.json#L931

**Comment by Zireael07** [comment]
Things @ynemo listed don't sound like liquids, except maybe bug guts, so the original idea (using rake to "mop up" solid stuff) should still be considered imho (at the very least, it'd give a use to the rake item)

**Comment by int-ua** [comment]
Yes, the names suggest the solid phase. But just making them liquid and tuning the names to be closer to liquid would make UX simpler: you wouldn't need to remember which item to use to clean up these functionally identical fields.

**Comment by int-ua** [comment]
@ynemo The `Good First Issue` tag is used for labeling issues that are easy to fix and still don't have a fix. The removal of that label does not mean that I don't think this isn't a relevant problem that needs fixing, just the fact that I think my suggested fix is enough. I wouldn't mind if your version is implemented though.

**Comment by ynemo** [comment]
Sure moping all mess is more usable way. Using rags probably match spirit of "vanilla" CDDA. 
Any way i now use leather tarps, looks like if you butcher directly on tarp there is no such mess?

**Comment by actual-nh** [comment]
One can turn the chitin into powder for liquid fertilizer, etc, IIRC?

**Comment by int-ua** [comment]
It's not the chitin item, it's just a **field** to reflect a mess from either butchering to splattering with damage that is only cosmetic.

**Comment by actual-nh** [comment]
Thanks! Long-term, having a rake turn appropriate fields into items would be nice. The current situation is definitely an argument for letting a mop clean up the useless junk.

**Comment by Rjtheperson** [comment]
If it's any consolation I had a similar incident when I field dressed a moose in my kitchen and the blood and guts that you can't mop up disappeared after a few days on their own.

**Comment by int-ua** [comment]
#46851 was merged and they will now be cleanable. It did not include the name change though. @ynemo now you decide if you still want this to be opened for the chance that rake will get a use or close because the mess will be cleanable now.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
