### ISSUE TITLE
Zombie sprite displaced from actual position

### ISSUE THREAD

**Issue by DavisBroda** [CleverRaven/Cataclysm-DDA#46834]
# Describe the bug

The zombie's sprite appears to be one tile above the zombie's actual position, as below 

# Steps To Reproduce

1. see a zombie this bug is effecting
2. notice that the attention indicator is one tile lower than the sprite
3. target with ranged weapon, it will target the correct tile one square below the sprite's apparent position

# Expected behaviour

Sprite should appear on the same tile as the zombie's actual position.

# Screenshots

![cdda_displaced_zombie_sprite](https://user-images.githubusercontent.com/15205060/104852658-39b91100-58ca-11eb-825b-a131612b4c8d.PNG)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-9017-gac88c03-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

I am using the Chibi_Ultica tileset. 

I have so far encountered this issue with tough zombies, hazmat zombies, decayed zombies, crawling zombies, and a few other types. But never with Basic zombies, child zombies, or feral humans.

**Comment by int-ua** [comment]
@Fris0uman ping

**Comment by Fris0uman** [comment]
Damn it >< not again. I'll see if I can fix it. But that will be something like the 3rd time I fix that stuff and reintroduce it in the next update

**Comment by int-ua** [comment]
So, is it confirmed then? Is it just a wrong offset?

**Comment by Fris0uman** [comment]
No, I don't know I haven't tested it. In any case if it's actually happening it won't be because of wrong offset, the last time it happened it was because there were at least two sprites with the same id but two different offsets.

**Comment by Myobu1** [comment]
Just chipping in, I have also been experiencing this bug with the Chibi_Ultica tileset.

**Comment by actual-nh** [comment]
> No, I don't know I haven't tested it. In any case if it's actually happening it won't be because of wrong offset, the last time it happened it was because there were at least two sprites with the same id but two different offsets.

I would think this could be automatically checked for, perhaps in one of the Python tools?

**Comment by int-ua** [comment]
What condition would you detect? I didn't look into exact reasons behind this yet.

**Comment by Zireael07** [comment]
duplicate id's for one could be detected.

**Comment by Fris0uman** [comment]
Yeah so basically every monsters that are both in MSX and in Ultica but are not 32x32 in ultica ( like most zombies for exemple) will appear with the MSX sprite but the Ultica offset. I don't know why since Ultica's sprite are set as filler, going through everything manually for every update is going to be a pain.

**Comment by int-ua** [comment]
> duplicate id's for one could be detected.

Well, they are with a new-ish `--obsolete-fillers` option of the `compose.py` (I didn't find time to update `TILESET.md` yet). I'll take a closer look at the situation later.
