### ISSUE TITLE
Suggestion for a new cleaner composed tileset JSON structure

### ISSUE THREAD

**Issue by int-ua** [CleverRaven/Cataclysm-DDA#46835]
# Is your feature request related to a problem? Please describe.
Tile entries can be completely decoupled from tilesheet entries in the tileset configuration JSON. Looks like it should be enough to just pass the correct order of tilesheet files. And since the indexes are global and tile entries can reference them across tilesheets, it may be possible to just pass them as a flat list.

And `tiles-new` name is not descriptive IMHO, I'd get rid of this level too if that's possible **and there is someone willing to rewrite tiles config reader**. Yeah, improbable, I know. But I'm ready to do the `compose.py` part.

# Describe the solution you'd like
Suggested new structure:
```
{
  "tile_info": {
    "height": 32,
    "width": 32
  },
  "sheets": [
    {
      "file": "tiles.png"
    },
    {
      "file": "moretiles.png",
      "sprite_width": 96,
      "sprite_height": 96,
      "sprite_offset_x": -32,
      "sprite_offset_y": -64
    }
  ],
  "tile_entries": [
    {
      "id": "10mm",
      "fg": 1,
      "bg": 632,
      "rotates": false
    },
    {
      "id": ["xxx","yyy"],
      "fg": 1,
      "bg": 234
    }
  ],
  "overlay_ordering": [
    ...
  ]
}
```

# Describe alternatives you've considered

# Additional context
https://discord.com/channels/598523535169945603/598535887801810944/794223490626617425 
(^ copy of the rationale)

> https://discord.com/channels/598523535169945603/598614717799596055/800440942036516885 :
> @esotericist: it's intentional they're all in one namespace so that you can if necessary re-use an id for multiple things

> https://discord.com/channels/598523535169945603/598614717799596055/800454721906147409 :
> @esotericist: that's me explaining why the code is the way it is. that's not me saying it _has_ to be that way. i'm just providing context

Originally this suggestion was written in comments to #46253 then moved into this separate issue.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
