### ISSUE TITLE
`U`nloading a first aid kit box gave me double the contents, while leaving the box intact

### ISSUE THREAD

**Issue by moxian** [CleverRaven/Cataclysm-DDA#46839]
# Describe the bug

I started a new world, evacuee scenario, went to the basement to find the first aid kits.
Found two kits in the bathroom.
Moved one of them with `/` directly to `I`nventory,
`U` -> navigate to First aid kit box -> enter
Now my inventory contains duplicate contents of the box. And the box still contains the contents as well: 

Update: I tried to drop the items to unload the box again, in order to reproduce. I selected all the items from the box, and dropped them. But now the box is empty and has no contents.
But also the OTHER first aid kit box is also empty.
So I managed to unload both of the kits, while having only one in inventory? And that somehow didn't update the `first aid kit box > 8 items` display?..

# Steps To Reproduce

Unknown, this is the first time it happened to me

# Expected behavior

Contents are transferred from the box to inventory, once; not duplicated.

# Screenshots

Inventory:
![cataclysm-tiles-20210117-215050](https://user-images.githubusercontent.com/7831163/104857264-20868380-590f-11eb-8b3d-628ff7e395b1.png)
Game log doesn't mention duplicates: 
![cataclysm-tiles-20210117-220001](https://user-images.githubusercontent.com/7831163/104857303-5c214d80-590f-11eb-9dec-40db3cc3fa56.png)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-8852-gf360c7f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

Savefile: 
[Harrisonville - double first aid kit.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5826898/Harrisonville.-.double.first.aid.kit.zip)

**Comment by anothersimulacrum** [comment]
Working as intended. It's a box containing first aid kit items, you can remove them and not destroy the box.

**Comment by anothersimulacrum** [comment]
Nevermind, I should be more thorough on reading.

**Comment by moxian** [comment]
Update: I tried to drop the items to unload the box again, in order to reproduce. I selected all the items from the box, and dropped them. But now the box is empty and has no contents.
But also the OTHER first aid kit box is also empty.
So I managed to unload both of the kits, while having only one in inventory? And that somehow didn't update the `first aid kit box > 8 items` display?..

**Comment by moxian** [comment]
Managed to reproduce.
- Load the save: [Southaven - unload ground.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5832455/Southaven.-.unload.ground.zip)
- `U` -> select the first aid kit box *on the ground*

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-11021.
