### ISSUE TITLE
AIM can put things into wielded containers but not take them out

### ISSUE THREAD

**Issue by YourCompanionCube** [CleverRaven/Cataclysm-DDA#46832]
# Describe the bug
when wielding a container you can pick things up via AIM but they don't display there to take them back out again

# Steps To Reproduce
grab a bag of some kind, i was using a body bag
set it to the highest priority to make sure items go into it 
put something into your inventory via AIM
see it went into the bag but is not listed in AIM

# Expected behavior
to be able to access all containers on your person in AIM

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-9017-gac88c03-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    No Rail Stations [No_Rail_Stations],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Useful Helicopters [useful_helicopters]
]

**Comment by actual-nh** [comment]
Could you correct the spelling on the issue title so it doesn't look like "welding"? Thanks!
