### ISSUE TITLE
Crash when disassembling dental floss on top of sink

### ISSUE THREAD

**Issue by Cyprex** [CleverRaven/Cataclysm-DDA#46842]
# Describe the bug

Disassembling dental floss in the attached save causes a segmentation fault. I do not believe this has anything to do with it being dental floss in particular and is more of a general weird edge case.

# Steps To Reproduce

1.Load attached save.
2.Pick up everything but the inhaler and dental floss.
3.B to pull up the butchering menu, select disassemble everything once
4.Hit 2 to drop item when it prompts you on what to do with it.
5.Segfault once disassembly completes
Note that step 2 seems to actually be required, I was unable to trigger the crash when I accidently forgot to do this. I haven't experimented with leaving other items on the tile.

# Versions and configuration

00:29:10.041 :  GAME REPORT:
- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 10 (buster); Release: 10; Codename: buster; 
- Game Version: 0.E-8929-gd76553adc1 [64-bit]
- Graphics Version: Curses
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

Note that the world was created on b11350, and I encountered this crash playing on b11360, while the stacktrace below and crash log are from a debug build that might be a handful of commits apart. Game report above lists the version used in stacktrace.

# Additional context

stacktrace with gdb attached:(sorry about the image, it wouldn't let me select text in this specific instance for some odd reason): 
![Screenshot_20210117_234336](https://user-images.githubusercontent.com/35031555/104859371-27b88c00-5925-11eb-90f4-8778ecbcb6c1.png)
Mostly the same as the crash log anyway, not sure if there is much value in posting this.

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5827012/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5827013/debug.log)
[Exprito_crash_upon_disassembly.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5827014/Exprito_crash_upon_disassembly.zip)

**Comment by mqrause** [comment]
Can confirm the crash, though it's still mysterious. Under certain conditions that I don't really understand it puts the disassembly item into the list of activity targets. Once the disassembly finishes, that item ceases to exist, but `Character::complete_disassemble` tries to set it as the next item to disassemble, which causes the crash.

If you pick up all items and then drop the dental floss and inhaler back onto the sink, no crash will happen, so it's maybe somehow related to ownership of the items.
