### ISSUE TITLE
Huge cockroaches are invincible to cars

### ISSUE THREAD

**Issue by moxian** [CleverRaven/Cataclysm-DDA#46846]
# Describe the bug

Rammed the giant cockroach with my car. At 25km/h. Multiple times. The cockroach is still at full hp.

# Steps To Reproduce

Load the save, pass the turn, see the cockroach in front of you still with full hp.

# Expected behavior

Cockroach should die. Same way as other fauna does.
Or if it's "too small" to be rammed into, then.. well.. maybe teleported to behind me?  Or at least I'd like the ineffectiveness of my murder method to be communicated in *some* way.

# Screenshots
![cataclysm-tiles-20210118-061135](https://user-images.githubusercontent.com/7831163/104878728-61ed5200-5954-11eb-9fd2-cf24a3814a7a.png)
![cataclysm-tiles-20210118-061149](https://user-images.githubusercontent.com/7831163/104878765-74678b80-5954-11eb-9b77-49bb5a3659bf.png)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-8852-gf360c7f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

Save: [Harrisonville - cockroach invincible.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5828188/Harrisonville.-.cockroach.invincible.zip)

**Comment by OliveChukar** [comment]
Tested in 0.E-9140-gedd42fc-dirty.  I rammed huge cockroaches with vehicles in both the provided save and a fresh world with core content pack Dark Days Ahead [dda] only. Hitting the roaches at 25km/h or less rarely damaged them but repeated ramming at this speed would eventually kill them. Also tested chipmunks and got the same result. 

Small creatures seem to bounce off of vehicles mostly without taking damage while larger ones do the same bouncing thing but take  damage with every hit.  I think this is intended to represent small creatures going under the vehicle without being hit or something like that.

**Comment by actual-nh** [comment]
> Small creatures seem to bounce off of vehicles mostly without taking damage while larger ones do the same bouncing thing but take damage with every hit. I think this is intended to represent small creatures going under the vehicle without being hit or something like that.

Probably, but that is rather contradicted by them bouncing...

**Comment by actual-nh** [comment]
It should be possible to have a vehicle part that damages even small creatures, but has the downside of much worse off-road capabilities - in other words, have something protruding downward to catch them.  An advanced version of such could be adjustable from inside the vehicle.

**Comment by jeffplata** [comment]
I reporting something similar at reddit. Ducks this time.
https://www.reddit.com/r/cataclysmdda/comments/pqydrb/what_did_you_feed_the_duck/

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
