### ISSUE TITLE
Satiety bar different for different instances of the same item (cranberry juice)

### ISSUE THREAD

**Issue by moxian** [CleverRaven/Cataclysm-DDA#46849]
# Describe the bug

I've found a fridge with multiple cranberry juice bottles. Trying to `E`at them gives the following selection:
![20210118-073755-cataclysm-tiles](https://user-images.githubusercontent.com/7831163/104885609-31abb080-5960-11eb-9508-4a4433488145.png)
Note how the bottle with a single portion of the juice is seemingly much more satiet(?) than those with two. This feels like a bug.

# Steps To Reproduce

Load the save, press E: 
[Harrisonville - satiety.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5828523/Harrisonville.-.satiety.zip)

(though i guess you could spawn in plastic bottles with the same drink with different number of charges?)

# Expected behavior

Same satiety bar on the same [kind of] items.

# Versions and configuration
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-8852-gf360c7f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by PaulBlay** [comment]
There are a bunch of different cranberry juice craft recipes. Some of them must be better than the others.

* Glass jar (sealed) ||\
* 3L Glass jar (sealed) ||
* Medium tin can (sealed) ||\
* Cranberry juice (not sealed) ||||

The 3L Glass Jar one should almost certainly the be same as the other sealed recipes, but I suppose the cranberry juice you drink fresh may have more vitamins etc. because it has not been heat treated. It might also have less water in the mix, I don't know.

**Comment by moxian** [comment]
This one was spawned on the map. All game-start items are the same, and use the calories defined in their `json`, rather than inheriting from ingredients.

You can see from the screenshot that the amount of calories between different instances is the same.
And satiety should be defined, roughly, as a calories/volume ratio.

**Comment by PaulBlay** [comment]
Okay, yes, that is weird and I obviously either have no idea how 'satiety' is defined in game or something is bugged.

I tested unloading all the juice into a single 60L tank which proves that they all have the same component information and flags.

**Comment by Hirmuolio** [comment]
Something to do with stack sizes maybe.
The same milk has different satiety depending on how many units of it are in a container.

The relevant code is here: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/consumption.cpp#L1259

There is some iffy math  there. Values are multiplied by something and in next step they are divided by the same thing. The intermediate values are also rouned before calculating the final result.
