### ISSUE TITLE
Butter Calorie amount

### ISSUE THREAD

**Issue by slimeboy460** [CleverRaven/Cataclysm-DDA#46841]
# Describe the bug

I think the butter in game has incorrect calculations with either the liter per one butter or calorie amount per serving. I would just like someone to make sure my calculations are correct before I do anything to the files.

# Steps To Reproduce

Calculate 0.02 L to grams, that equal 20 grams. 100 grams of butter typically equals 105 calories per serving. 

# Expected behavior

if it was 20 grams then it'd be 20 calories per portion. So we can either increase the amount of liters to 0.1 L so it'd equal it's irl equivalent or we'd have to reduce the amount of calories per serving. If we adjust the liters instead of the reducing the calories then there would be no needed recipe adjustments as it'd be similar to the real life equivalents. 

(why am I doing this, it's just butter)

**Comment by Jamuro-g** [comment]
Sorry but i had some troubles following parts of what you described. Still i took a quick look at the json and here are my results

- the json entry has 500ml as volume. 
- 500ml butter should roughly equate to 477.5g (https://www.howmany.wiki/vw/--500--ml--of--butter--in--gram)
- 1g of butter has 7.17 cal (ty google)
- and we have 32 charges in a butter stick:

7.17*477.5/32 = 106.98 cal

So the calories in relation to the specified volume is pretty much spot on. The butter sticks weight on the other hand realy isn't.
If noone finds an error or objects i can just change it to 500g which should be pretty much spot on and is a commonly sold amount of butter even.

**Comment by slimeboy460** [comment]
Ahhh, gotcha, thank you for explaining it. I'll close this then.
