### ISSUE TITLE
Robot wheels/tracks for your vehicle

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#46857]
# Is your feature request related to a problem? Please describe.

If you're like me, you have a ton of 'omni wheels' and 'small tank treads' that you're probably never going to use for anything.

# Describe the solution you'd like

I think it would be cool if you could use 'omni wheels' and 'small tank treads' as vehicle parts. Omni wheels would work for single tile vehicles. They would be light, but have poor off-road performance. 'small tank treads' would have good off-road performance and be durable, but have a lot of roll drag. Possibly you could also use 'small tank treads' as a crafting part and basically wrap them around 24" wide wheels to make armoured wheels.

# Describe alternatives you've considered

Leave as is.

**Comment by Fosheze** [comment]
I believe that the reason that tank treads weren't mainlined originally from the tank mod when the rest of it was is that the current vehicle system can't accurately model a tracked vehicle. Tracked vehicles handle entirely differently from wheeled vehicles (zero point turning), damaging one track should take out all tracks on the same side, and there was also talk about if the average survivor could realistically drive a tank (this would be a good spot for the new proficiency system though). At the time it was decided to leave out the tank tracks until a better system could be created. The same is true of omni wheels except there you also have the issue of needing to allow sideways movement as well.

It is an excellent idea and it would also be interesting to see more robot parts usable as vehicle parts, however there are a lot of new vehicle mechanics which need to be put in place before I can see it being allowed in mainline.

**Comment by anothersimulacrum** [comment]
These are what the small tracks look like:
![from https://en.wikipedia.org/wiki/Foster-Miller_TALON](https://user-images.githubusercontent.com/42699974/105057602-3ccb1300-5a2a-11eb-82b1-678d17a41549.png)

**Comment by PaulBlay** [comment]
@anothersimulacrum Nice. At that size one set replaces one wheel. The robots sure look bigger than that when they show up, though!

**Comment by actual-nh** [comment]
Hmm... ridable robots for Aftershock? Use the omniwheel to create a Segway imitation?

**Comment by kevingranade** [comment]
The small tracks do not replace single wheels, they aren't designed with the same load as a full sized vehicle wheel any more than a similarly sized set of wheels would be.
The same is the case for the omni wheels, they're robot sized parts, not vehicle sized parts.
