### ISSUE TITLE
Eat or Consume menu , comestibles from containers around player are in top of the list, like there are from inventory

### ISSUE THREAD

**Issue by ynemo** [CleverRaven/Cataclysm-DDA#46856]
# Describe the bug

When you press "E" or use consume submenus (food, drink, medication) you will see in top of the list comestibles from your inventory, but also there is a mess with all comestibles around player, if they are inside any container. 
So you cant split your food like "ok, i want to eat smthing from my inventory only, or smthing N from me. All food around player currently shown at top of the list, in case this food is in container. 

# Steps To Reproduce
Put any food/drink/drug inside container, drop container to your feet, use "E". Try to figure out which food is in inventory, and which one is around player, they are in one list. 

# Expected behavior

There are should be possibility to split comestibles from different directions around player to avoid mess in E menu, even if these comestibles are inside containers.  

# Screenshots

![image](https://user-images.githubusercontent.com/24881844/104924792-fbe1e880-59ae-11eb-98fa-149afcd7d3f5.png)

I am standing next to minifridge and freezer. 
On screenshot you can see some ketchup from fridge, other from freezer, and some food from my inventory all in one list at top of the screen. They should be at the bottom, with corresponding tile name

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-9022-g59c9b3e-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by ynemo** [comment]
It's a misunderstanding, this tread is not "quality of Life" or any other kind of suggestion.
I report a bug, I am sure before implementing new pocket system,  items in "E" menu was arranged as intented.

**Comment by Qrox** [comment]
It is a quality of life bug then.
