### ISSUE TITLE
RC car with EMP grenade onboard vanishes when save file loaded.

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#46852]
# Describe the bug

I had a RC car with an EMP grenade installed in my inventory. On loading I get an error message and the RC car (and EMP grenade) is gone.

 DEBUG    : error: item radio_car cannot fit into pocket while loading: pocket is holding too much weight

 FUNCTION : void item_contents::combine(const item_contents&, bool)
 FILE     : src/item_contents.cpp
 LINE     : 335

# Steps To Reproduce

1. Load save file (see end of report)
2. Observe error message.
3. Check inventory - no RC car.

Additional steps to confirm repeatability

4. spawn in new RC car, ultra-light battery, EMP grenade, radio activation mod
5. (r)eload RC car with battery
6. attach radio activation mod to EMP grenade
7. (a)ctivate RC car and attach bomb
8. Save game and Quit
9. Load game
10. Observe error message
11. Check inventory - no RC car.

# Expected behavior

RC car to not vanish.

# Screenshots

# Versions and configuration

- OS: Windows x64 8.1
- Game Version: 0.E-9000-g8f6b461-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

# Additional context

[Little Rapids.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5829835/Little.Rapids.zip)

<s>I suspect that the mass of the stuff when installed / put together is greater than the mass when they are separate items.</s>
Nope. That doesn't seem to be it.

**Comment by PaulBlay** [comment]
Checking mass conservation.

# Apart 

* ultra-light battery 0.01 kg
* radio activation mod 0.14 kg
* EMP grenade 0.40 kg
* RC car 2.34 kg

# Together (1)

* EMP grenade with radio activation mod 0.40 kg
* rc car with battery 2.35 kg

# Together (2)

* rc car with battery and EMP grenade attached 2.75 kg

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-12701.
