### ISSUE TITLE
Damaged ESAPI ballistic vest can be refurbished without any additional material

### ISSUE THREAD

**Issue by Digi1980s** [CleverRaven/Cataclysm-DDA#46850]
Disassembling a piece of damaged ESAPI ballistic vest sometimes yields UNDAMAGED components, which can be used to make a brand new one.   

# Steps To Reproduce

1. Spawn some zombie soldiers.
2. Kill them all.
3. Disassemble their ESAPI vests.
4. Get intact components from one of them.

# Expected behavior

Get damaged components or fail to get components.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-9017-gac88c03-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by PaulBlay** [comment]
I don't know how to implement it, but it would be reasonable to have the "empty ballistic vest" produced by disassembling the ESAPI ballistic vest to always be at least |\ damage level. One can assume that it would be difficult to damage the ballistic plates to a significant level without also doing some damage to the vest that contains them. 

Unlike the assembled ESAPI ballistic vest, you can actually repair the empty ballistic vest.

**Comment by Xenomorph-III** [comment]
I thought you were just grabbing the intact bits and leaving the rest.

**Comment by PaulBlay** [comment]
> I thought you were just grabbing the intact bits and leaving the rest.

I think the point the @Digi1980s is making is that sometimes 'the intact bits' is everything and 'the rest' is nothing. Which doesn't make much sense if the original is stated to be |\ damaged or worse. I haven't tried reproducing this bug, but it's plausible.

**Comment by int-ua** [comment]
IMHO it's a `Suggestion / Discussion` label, not a `Bug` and the situation is that you combine **multiple** damaged ESAPI into one repaired which is quite realistic, although intermediate steps cannot be made fully realistic with current engine.

**Comment by PaulBlay** [comment]
@in-ua My understanding of the report is that, sometimes, you only need a single damaged ESAPI which is an entirely different thing.

**Comment by int-ua** [comment]
Yeah, guess I wasn't paying attention, looks like you are right.

**Comment by PaulBlay** [comment]
I damaged 10 ESAPI ballistic vests and disassembled them. 2 of them recovered all components necessary to make a new one, 8 lost one or more component.

**Comment by Digi1980s** [comment]
I am so glad that finally someone understands and reproduces it.

**Comment by Cyprex** [comment]
This is simply RNG as far as I can tell, which seems like an acceptable limitation.

**Comment by actual-nh** [comment]
> One can assume that it would be difficult to damage the ballistic plates to a significant level without also doing some damage to the vest that contains them.

The ceramic plates are actually designed to crack to absorb a sufficiently massive impact, so I'm not sure the vest itself would have more than cosmetic damage even if some of the ceramic plates needed replacing. For the other plates, I agree.
