### ISSUE TITLE
Radio signal for 'bomb go boom' should have same range as signal 'RC car turn left'

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#46854]
# Describe the bug

The radio signal to activate grenades and bombs with the 'radio activation mod' is shorter than the radio signal used to control an RC car. Given that the same device (RC controller) sends the signals and you can build both RC car and radio activation mod is is reasonable to assume a similar capability for both.

# Steps To Reproduce

1. Check how far you can control a RC car (From a square next to you, you can drive it up to 66 tiles away)
2. Check how close you have to be to activate a grenade with the radio activation mod (Appears to be 30 tiles)

# Expected behavior

Bomb goes boom.

# Screenshots

# Versions and configuration

- OS: Windows x64 8.1
- Game Version: 0.E-9000-g8f6b461-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

# Additional context

This discrepancy means that Crow II turrets (depending on gun installed) can shoot you to pulp before you are close enough to blow them up. For example in the save file you will be shot if you step one tile to the right. However you need to go 23 tiles to the right in order to be close enough to activate an EMP bomb next to the Crows II turrets.

[Little Rapids.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5830058/Little.Rapids.zip)

**Comment by Night-Pryanik** [comment]
You can operate the RC car behind some obstacle. You don't need to directly see the turret.

**Comment by PaulBlay** [comment]
> You can operate the RC car behind some obstacle. You don't need to directly see the turret.

That only helps if there is a convenient obstacle to use. Well, I suppose maybe you could carry two large boxes around and leapfrog them.
