### ISSUE TITLE
Item duplication when trading

### ISSUE THREAD

**Issue by DalenTalas** [CleverRaven/Cataclysm-DDA#46874]
# Describe the bug

Trading with the NPC for a container AND its contents duplicates the contents.

# Steps To Reproduce

1. Give an NPC follower a container with some items (tried with ammunition).
2. Begin a trade.
3. In the trade screen, select both the container, and its contents.
4. Receive both container with the contents, and another copy of the contents separately.

In the attached save file:
1. Speak to the NPC to the NW of the character.
2. Trade for the .22 ammo AND the pouch it's in.
3. Receive 2 stacks of .22 ammo.
4. The pile of ammo under the char's feet is from previous successful duplications.

# Expected behavior

Barter should not violate the principle of matter / energy conservation.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-9017-gac88c03-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Graphical Overmap [Graphical_Overmap]
]

# Additional info

Save file: [TEST`.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5839912/TEST.zip)

**Comment by int-ua** [comment]
#46873 ?

**Comment by PaulBlay** [comment]
@int-ua The steps to reproduce are similar, but not that similar. 

@DalenTalus Save file? I'm having weird problems with trading right now in my game so it would save time.

**Comment by DalenTalas** [comment]
I attached the save file and updated the recreation instructions in the original post.

Was able to successfully dup ammo at least two times.

**Comment by PaulBlay** [comment]
Just now, or was I blind? (I bet it was the second option).

I'll take a look.  I tried the recreation instructions, but the items I sold kept vanishing from the merchant's inventory. https://github.com/CleverRaven/Cataclysm-DDA/issues/46879 Hopefully I'll have more luck with your file.

**Comment by DalenTalas** [comment]
Just now. :)

**Comment by PaulBlay** [comment]
> Note, I tested this with a follower NPC, not a merchant.

Oh, whoops. I failed reading comprehension.

> However, I seem to remember this happening with merchants as well.

I just tested it, and I can confirm that it does happen with merchants as well.
