### ISSUE TITLE
Add American-180 magazines

### ISSUE THREAD

**Issue by emptytriangle** [CleverRaven/Cataclysm-DDA#46875]
# Describe the problem
The American-180 has several magazines, but only the 165-round steel magazine is available in CDDA.

# Describe the solution you'd like
The American-180 should have the following magazines available:

- 165-round steel magazine (already in-game)
- 165-round polycarbonate magazine
- 177-round steel magazine
- 220-round polycarbonate magazine
- 275-round polycarbonate magazine

# Describe alternatives you've considered
Doing nothing. In New England, Vermont is the only state in which you could reasonably find an American-180. Realistically, if you did find an A180, you would probably find more than one and several magazines in the same location. The previous owner would be an enthusiast/collector 100% of the time.

# Additional context
See http://www.brasscatchers.com/am180/accessor/drumlexan.html for a website at which you can still buy these magazines new today.

**Comment by emptytriangle** [comment]
Also an American-180 should foul more quickly than other firearms (is there a way to do that?)

**Comment by DalenTalas** [comment]
How common are those IRL? Would adding items with minor cosmetic differences be worth the effort?

**Comment by Jamuro-g** [comment]
not a fan of different materials being their own mag ... there is already a lot of clutter
same for the 177 mag, it's not realy a big difference imo
that said maybe the 220 and/or the 275 could be worthwhile as a slighty rarer drop and upgrade

**Comment by emptytriangle** [comment]
> How common are those IRL? Would adding items with minor cosmetic differences be worth the effort or needlessly complicate things?
They aren't very common at all. In fact, there might be only two or three in all of New England.  But where those two or three are, there are certainly multiple magazines. They're a collector's item that you have to go way out of your way to get, and the magazines are comparatively inexpensive. Anyone who would have an American-180 would also have at least one 220 or 275 round magazine (as well as a steel magazine) which they would order almost **immediately** after acquiring the A180.

**Comment by emptytriangle** [comment]
I guess what I would like optimally would be to find an a180 and two magazines in a survivor basement, or in a gun safe, with a very low chance. I would never expect to find an a180 in a gun safe or a survivor basement and not also find more than one magazine

**Comment by DalenTalas** [comment]
So probably the best solution would be to modify the drop table accordingly.

**Comment by talltitanicc** [comment]
Honestly, while I'm unsure if a lot of people use the American 180, but having options is nice, even if it is just for the sake of options.
