### ISSUE TITLE
when trading an item from wielded bag for another item that needs to be wielded, you can drop the item before it gets taken away

### ISSUE THREAD

**Issue by Withcrono** [CleverRaven/Cataclysm-DDA#46873]
When trading an item from a wielded bag for another item that you have to wield, you get prompted to drop your bag, if you do the item inside doesn't get taken away. Only tested with a bag of heroin.

# Steps To Reproduce

1. Have little to no space on your inventory.
2. Wield a bag with an item inside.
3. Trade the item inside the bag for another item.
4. Drop the bag when prompted.

# Expected behavior

The transaction is completed, but you get to keep both of the items.

# Screenshots
![1](https://user-images.githubusercontent.com/77210107/104990009-78e67f80-59fa-11eb-825c-68a7944a11a8.jpg)
![2](https://user-images.githubusercontent.com/77210107/104990018-7d129d00-59fa-11eb-8817-ed45fbb351f2.jpg)
![3](https://user-images.githubusercontent.com/77210107/104990021-7edc6080-59fa-11eb-8598-9a653816221d.jpg)
![4](https://user-images.githubusercontent.com/77210107/104990022-80a62400-59fa-11eb-93a6-20b5974ffeb8.jpg)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-8924-gc4efd9e-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Aftershock [aftershock],
    Crazy Cataclysm [crazy_cataclysm],
    Mythical Martial Arts [MMA],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Bionic Slots [cbm_slots]
]

**Comment by PaulBlay** [comment]
@int-ua  I can confirm this.

[TEST3.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5840099/TEST3.zip)

Save file has a character with a rucksack full of jeans. If you sell the jeans to the merchant and buy shovels and then drop your rucksack when prompted you end up keeping the jeans as well as the shovels you bought.

**Comment by wapcaplet** [comment]
Retested in the new trading UI, and got a reproducible game crash out of it.

![image](https://user-images.githubusercontent.com/238395/141686692-18c98dce-f8b3-4a76-8895-63632244a128.png)

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7534001/crash.log)

**Comment by andrei8l** [comment]
I've fixed the segfault but wasn't able to reproduce the item duplication from the OP
