### ISSUE TITLE
Trading quirks. Can't buy back various items at refugee center

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#46879]
# Describe the bug

Selling items to the refugee center I found that I often can't buy them back (they aren't listed in the trading panel).

# Steps To Reproduce

1. Load save
2. Sell modified UPS, laser rifle, combat knife and gas mask to merchant
3. Try to buy them back.
4. Fail.

Note that they are dropped under his feet and marked with the 'steal' flag.

# Expected behavior

I would expect them to be available to buy back (probably for more than I sold them).

# Screenshots

# Versions and configuration

- OS: Windows x64 8.1
- Game Version: 0.E-9000-g8f6b461-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

# Additional context

When I sold him a military rucksack I could buy that back. Similarly for wristwatch, welding goggles, aspirin and bandages. I don't know what the criteria is for failing to buy back.

[Little Rapids.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5837637/Little.Rapids.zip)

**Comment by andrei8l** [comment]
I can't load your save file in master, but I recreated the scenario and wasn't able to reproduce the bug with the new trade UI (ie. I was able to buy back my items).

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
