### ISSUE TITLE
Frog Mother is impossible to deal with (by non-lategame character)

### ISSUE THREAD

**Issue by moxian** [CleverRaven/Cataclysm-DDA#46888]
# Is your feature request related to a problem? Please describe.

Frog mothers are incredibly strong, and can spawn day 1 in confined places such as basements, instantly ending the run.

- They have 400 hp, 12 bash armor and 40 regen so they can only be taken out by very heavy weaponry (melee is ineffective, handguns are ineffective; I haven't tested, but suppose shotguns are also not very effective, dealing only ~50 damage per turn until they run out of ammo and need to be reloaded?)
- They can leap, grab, and summon grabbing tadpoles on top of the player, making the escape impossible.
- They spawn in basements, so there's no way to notice them from outside their vision range and decide to nope out

# Describe the solution(s) you'd like
Either:
- Heavily nerf her to the point that a day 1 character can deal with her at all (probably with heavy losses, but still)
  - either by killing her (so nerf  regen, armor, health, the amount/frequency of summoned tadpoles)
  - or by escaping (so remove spawning tadpoles on top of the player, make tadpoles much slower, remove their grab; remove mother's leap and (optionally?) grab)
  - (or both)
- Make her only spawn outside in the open, so the player can walk away without aggroing her.

**Comment by wapcaplet** [comment]
Similar discussion occurred on #45222 recently. I encountered one in a basement early-game but was lucky and escaped without being seen. They are supposed to be difficult, but I agree that it’s rude to hit players with them on day 1.

**Comment by actual-nh** [comment]
Minimum spawn time a year or so on?

**Comment by PaulBlay** [comment]
I've never met one in the basement, but yeah that would kill me. You need the right gun (and a powerful one) to even stand a chance and they move surprisingly fast (with the leap and all).

Talking about OP, a Ghargoyle(sp) stole my laser rifle yesterday. Hax.

**Comment by moxian** [comment]
Here's a save where I encountered one in the basement. (The save is shortly after I realized that I'm doomed, but before actually suffering any major losses)
[Southaven - frogmother.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5839942/Southaven.-.frogmother.zip)

It was a very good run, and I even have an M4A1 and a pistol on me!!!! And a car that could get me to safety a bit to the south-west! But i cannot run away.. Nor can I kill her.

**Comment by kevingranade** [comment]
> Heavily nerf her to the point that a day 1 character can deal with her at all 
> Make her only spawn outside in the open

Categorically no, if you see one and can't deal with it, run away.
If you don't see it, get better at running away.
There are also lots of options for obscuring vision to help with running away.
Much like with turrets, this is the kind of enemy peeking is intended for.

I do have two changes related to this I would like to make.
1. Spawn should appear adjacent tot he frogmother.
2. Add a cautious movement mode that does a peek and safe mode check before every step to alert vs this kind of extreme danger.

**Comment by moxian** [comment]
> Categorically no, if you see one and can't deal with it, run away.
> If you don't see it, get better at running away.

In the save above: I went downstairs to the house basement, saw the frogmother two tiles away from me. Can't run away from that.

https://github.com/CleverRaven/Cataclysm-DDA/blob/6f42474defb7b3a24ddb6af014581c613cf1f83a/data/json/monstergroups/misc.json#L162-L174

**Comment by PaulBlay** [comment]
Can you see into basements from the floor above if you have debug -> experimental multiple z-level view enabled?

**Comment by actual-nh** [comment]
> > Categorically no, if you see one and can't deal with it, run away.
> > If you don't see it, get better at running away.
> 
> In the save above: I went downstairs to the house basement, saw the frogmother two tiles away from me. Can't run away from that, (because tadpole spawn on top of me, and because of leap)

kevingranade did say one preferred change would be making the tadpoles spawn right next to the Frog Mother. Not sure re the leap.

> https://github.com/CleverRaven/Cataclysm-DDA/blob/6f42474defb7b3a24ddb6af014581c613cf1f83a/data/json/monstergroups/misc.json#L162-L174

A cost multiplier of 3 does seem a tad bit low.

**Comment by moxian** [comment]
As @kevingranade mentioned on discord, escaping the basement frogmother is not a problem if you know what you're doing.

In the save above - run northeast, back into the house you (or, well, I) have just left, break LoS, and then just run north, away from the frog.

So.. I guess this is WAI, and no nerfs are really needed?

**Comment by jeremyshannon** [comment]
You can also peek down stairs, allowing you to spot things like that before you walk down there, and nope out sooner.

**Comment by BHasselaar** [comment]
Tbh right now I feel like they are more an annoyance than truly a boss monster.

I found one by the swamp while I was on a hunting trip and tadpoles spawned inside my car even though I was about ~30 tiles from the frog so I very much support the mentioned change, but...

Another time there was a basement full of albino penguins and a frog mother. Its only use for me was to grind melee skills since neither the penguins nor I could kill it but they took care of the tadpoles as soon as they spawned.

I would like to see this monster more as threat that you can find on the overworld with its own nest or something that it defends, and be a slow, very damaging tank that regenerates, with tadpoles that can grab and pull you (like with grappler zombies).

**Comment by Wyrdean** [comment]
I can contest to the frog mother being nigh-unkillable.
I unloaded three magazines of 12.3ln using the exodii rifle, dealing 60-70 damage each shot and the frog mother regened to full by the time I reloaded, a barrage like this would have killed a hulk several times over, a skeleton hulk several times over.
