### ISSUE TITLE
Mapgen. Hospital (generated by mission?) in the woods (no road access)

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#46881]
# Describe the bug

Found a hospital in the middle of the woods with no way to get there by car.

# Steps To Reproduce

1. Start new game
2. Debug reveal map
3. Look for hospitals
4. Repeat from 1. until it happens again.

# Expected behavior

Ambulances and cars need to be able to reach hospitals.

# Screenshots

![hospital in woods](https://user-images.githubusercontent.com/54060142/105081474-2654a400-5a8a-11eb-8c54-d86423436c1a.png)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-9000-g8f6b461-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

# Additional context

I guess it could be a super-exclusive private hospital which you only get to be helicopter.

**Comment by Cyprex** [comment]
I've also had this happen to a steel mill, is there a map seed somewhere I should post?

**Comment by DalenTalas** [comment]
Should be present in one of my old saves, if it's still up: [Gladewater.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5718604/Gladewater.zip)

**Comment by moxian** [comment]
Personally, I'd prefer to see it as a feature, not a bug (even though it's most likely not intended)

**Comment by Night-Pryanik** [comment]
Are you _absolutely_ sure this is a hospital and not a _helipad_ which has the same symbol and colors? I'm asking because I myself confused hospital for helipad several days ago.

**Comment by PaulBlay** [comment]
> Are you absolutely sure this is a hospital

Well, it was full of drugs, oxygen tanks and a bunch of autodocs. So, yes.

**Comment by Cyprex** [comment]
Aren't helipads 2x2 compared to Hospitals which are 3x3?

**Comment by Night-Pryanik** [comment]
> Aren't helipads 2x2 compared to Hospitals which are 3x3?

Yeah, you're right.

**Comment by PaulBlay** [comment]
Er, oops. I belatedly realized something that I needed to mention. I 'found' the hospital by getting the 'analyze zombie blood' mission. It's quite possible that the hospital was created (in unexplored area) by that mission. Until today I didn't know that missions can actually do that.

**Comment by Night-Pryanik** [comment]
It's a very important information. Seems like mechanics of overmap special placed for missions bypasses some (all?) of fields in definition, like road connection or requirement to be placed in city radius (as hospital is `city_building`).

**Comment by Cyprex** [comment]
I've had this happen with a steel mill, which I doubt was a mission spawn.
![Screenshot_20210113_210547](https://user-images.githubusercontent.com/35031555/105919690-5fff4f00-6036-11eb-9444-a4eda02cd237.png)
[Exprito.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5876740/Exprito.zip)

**Comment by actual-nh** [comment]
> I've also had this happen to a steel mill, is there a map seed somewhere I should post?

That is a somewhat different case from this one. Hospitals are down as city buildings, so should not be found outside of a city. Steel mills have an explicit requirement for a road (at least as of 11397). (Both are still bugs, of course.)

**Comment by Cyprex** [comment]
The two tiles in the bottom left are steel mill depots, map symbol |

**Comment by kholat** [comment]
I also had a hospital generate like that from the analyze blood mission.

**Comment by eltank** [comment]
This is a problem in 0.F. The "old" 3x3 1-level hospitals no longer spawn, only the 2x3 7-level ones do. The first mission for the Refugee Center doctor force-spawns a 3x3 hospital somewhere random, which could very well be in the middle of a forest or swamp. It must have broken shortly before release because when I was debugging #49106 I didn't notice this problem.

The only known workaround at the moment is to savescum talking to the doctor until you get a reasonable hospital placement.

A quick fix might be to let the mission target the "new" hospitals, since they do have the necessary equipment and shouldn't need to be force-placed.
I will probably work on fixing this soon since it's breaking my current playthrough.

**Comment by eltank** [comment]
Upon further debugging I see that the old hospitals do still spawn, just not all the time. There's a chance to reach the refugee center without any hospitals having been placed in any generated overmaps.
At that point `mission_util::assign_mission_target` calls `find_or_create_om_terrain` which calls the 2nd form of `overmapbuffer::place_special` which calls `overmap::place_specials_pass` with `force=true` and that's how hospitals pop up in forests.

So now I think that in addition to allowing the mission to find the "new" hospitals, it should also use a different call that doesn't force placement. Instead it should generate more overmaps until a hospital (of new or old variety) is found.

**Comment by eltank** [comment]
Good news: I found a simple JSON fix that will make this bug go away (as in, no more randomly placed hospitals). It's simply removing ` "om_special": "hospital"` from `assign_mission_target` in the `MISSION_SCIENCE_REP_1` mission definition in `NPC_old_guard_doctor.json`. This forces the game to generate new overmaps (if necessary) until it finds an actual hospital in a city.

Bad news: 
- the target hospital for the mission could be pretty far away (but you don't actually have to go there to complete the mission, you can also find working centrifuges elsewhere)
- I was going to use ` "om_terrain": "hospital", "om_terrain_match_type": "CONTAINS"` to match both new and old hospitals; unfortunately the omt_ids of the new hospitals look like `urban_35_1_south`, which doesn't contain "hospital" at all

So I'll probably create 2 PRs, once with the simple fix and another one that adds an `overmap_location` parameter to `mission_target_params` (with C++ code to handle it) and a new JSON definition for a "hospital" overmap_location that contains "hospital_2" and "urban_35_8".
