### ISSUE TITLE
Taking food from freezer defrosts it

### ISSUE THREAD

**Issue by Mrzjadacz** [CleverRaven/Cataclysm-DDA#46880]
# Describe the bug

Took frozen food from vehicle freezer. In my inventory, it's not frozen anymore.

# Steps To Reproduce

Put food in a freezer, wait till it freezes.  Grab/move in AIM some food to your inventory.
It's not frozen.

Can't add save, cause Git only allows 10MB.

# Expected behavior

Food stays frozen

# Screenshots

![image](https://user-images.githubusercontent.com/26396019/105077341-aed44400-5a8c-11eb-89ec-70f4286d7deb.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-9024-g785f240-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Mythical Martial Arts [MMA],
    C.R.I.T Expansion Mod [crt_expansion],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Bionic Professions [package_bionic_professions],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP]
]

# Additional context

**Comment by PaulBlay** [comment]
I think this is a known bug. See https://github.com/CleverRaven/Cataclysm-DDA/issues/34316 https://github.com/CleverRaven/Cataclysm-DDA/issues/36401 and possibly https://github.com/CleverRaven/Cataclysm-DDA/issues/39051

**Comment by Ramza13** [comment]
I'm guessing this is the same bug as talked about in this post https://github.com/CleverRaven/Cataclysm-DDA/issues/42658#issuecomment-698291653 .  

That said I tried to reproduce it at some point and had a lot of trouble so another save with it would be awesome.  If your save is too big you can share it via google drive or try compressing it into a 7z which can have crazy compression.

**Comment by Mrzjadacz** [comment]
https://drive.google.com/file/d/11h_Il3Szvc7JowtXp-ZCk5eqj1WdQhaz/view?usp=sharing
38MB, actual size 430 MB

**Comment by Hirmuolio** [comment]
I don't know why, I don't know how, but somehow it seems like the conductivity_term becomes infinite here
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/item.cpp#L9449
At least that is what VS debugger says when I add breakpoint a bit later there.

The bug is somehow tied to time. If you wait few hours and take items out from the freezer the bug does not happen.

**Comment by actual-nh** [comment]
> I don't know why, I don't know how, but somehow it seems like the conductivity_term becomes infinite here
> https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/item.cpp#L9449
> At least that is what VS debugger says when I add breakpoint a bit later there.

What is the value for `insulation` at that point, and what volume are we talking about?

**Comment by Hirmuolio** [comment]
Volume 500

Insulation is "optimized away and not available."

**Comment by Mrzjadacz** [comment]
Not sure if those terms are related to electricity, but roughly before I found the bug, there was an electric exchange between shocker and electric turret on my car.  Probably 100+ attacks
