### ISSUE TITLE
Crafting -- Electric Forge Charge Display Bug

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#46895]
# Describe the bug

When attempting to craft an item requiring over 1,000 charges of a vehicle-mounted electric forge, the item shows as white, but the electric forge requirement shows as red. An item requiring less than 1,000 charges shows properly green.

# Steps To Reproduce

1. Load attached save
2. Enter crafting menu
3. Search for `t:electric forge`
4. Compare the kabuto to the kabuto XL

# Expected behavior

I expected the interface to not show red above 1,000 charges.

# Screenshots

![image](https://user-images.githubusercontent.com/13796683/105156037-54ada000-5ad9-11eb-8f8d-58ebd837c16c.png)
![image](https://user-images.githubusercontent.com/13796683/105156082-60996200-5ad9-11eb-9e64-df4c15255a00.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 20H2 (build 19042.746)
- Game Version: 0.E-9022-g59c9b3e-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded:
    - Dark Days Ahead [dda],
    - C.R.I.T Expansion Mod [crt_expansion],
    - No Fungal Monsters [No_Fungi],
    - Disable NPC Needs [no_npc_food],
    - Alternative Map Key [alt_map_key],
    - SpeedyDex [speedydex],
    - Stats Through Kills [stats_through_kills],
    - Stats Through Skills [StatsThroughSkills]

# Additional context

[Woodcock.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5841393/Woodcock.zip)

**Comment by BrettDong** [comment]
Probably share the same root cause with #46659

**Comment by PaulBlay** [comment]
Same as https://github.com/CleverRaven/Cataclysm-DDA/issues/46265 ?

**Comment by ToxiClay** [comment]
> Same as #46265 ?

Nope; different. That one emitted the message "can't continue crafting"; this doesn't.
