### ISSUE TITLE
Magiclysm insane experience gains

### ISSUE THREAD

**Issue by jiornojiovanni** [CleverRaven/Cataclysm-DDA#46907]
# Describe the bug

Huge experience gains when casting spells. I levelled magic missile to 11 by killing 3 rabbits.

# Steps To Reproduce

1. Learn Spell
2. Cast it
3. You became an expert mage

# Expected behavior

Normal experience gains.

# Screenshots

![immagine](https://user-images.githubusercontent.com/31773561/105230248-5b81f480-5b65-11eb-8fc7-429e96a7bfa6.png)
Magic missile level 12 in the first few hours

# Versions and configuration

 - OS: Windows 10
 - Game Version: [from the main menu, e.g. 0.C-29938-g90f5268437]
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: [
  "dda",
  "no_npc_food",
  "package_bionic_professions",
  "magiclysm",
  "No_Rail_Stations",
  "No_Fungi",
  "StatsThroughSkills",
  "speedydex",
  "MagiclysmUDP",
  "Graphical_Overmap",
  "Graphical_Overmap_Magiclysm",
  "Graphical_Overmap_SDG"
]

# Additional context

[West Bath.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5845096/West.Bath.zip)

**Comment by jiornojiovanni** [comment]
uh weird, i can't also learn anything from normal books

**Comment by anothersimulacrum** [comment]
@KorGgenT

**Comment by KorGgenT** [comment]
caused by #46596
