### ISSUE TITLE
Skills - Book training rate extremely slow (11382+)

### ISSUE THREAD

**Issue by NoddingCrow** [CleverRaven/Cataclysm-DDA#46902]
# Describe the bug

The skill gain from reading books is now extremely slow, with 10+ chapters needed to get _one_ percent increase on a book where previously I'd get 10% or higher per read, same character setup, same books. 
Suspect oversight in [this commit](https://github.com/CleverRaven/Cataclysm-DDA/commit/126fc30ae5a2a3bc5ed400709ec8f267329121ee) not applying a modifier to skill.cpp line 290, essentially giving 1/100 the previous progress.

# Steps To Reproduce

1. Aquire a character and a skill book.
2. Read book.
3. Notice how it still says (0%) of skill progress after reading the chapter.

# Expected behavior

Character gains at least some skill from reading.

# Screenshots

![bookreport](https://user-images.githubusercontent.com/77363578/105201550-ee586a00-5b38-11eb-835a-3fb3fd29ffcd.jpg)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-9061-g4d8f8a4-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Stats Through Kills [stats_through_kills]
]

**Comment by MindlessMax** [comment]
![image](https://user-images.githubusercontent.com/77750299/105223156-43cc5100-5b10-11eb-85d7-5d6fd8c9c8d5.png)

Verified this on a world using only Dark Days Ahead [dda]

New character. Zero Computer skill. Reading Computer Science 101 for an entire day 0% skill gain.

Game Version: 0.E-9061-g4d8f8a4-dirty [64-bit]

**Comment by Inglonias** [comment]
Not gonna lie, I half-thought this was an intentional change.

**Comment by NoddingCrow** [comment]
heh. while I don't disagree with skill books being nerfed a little bit, a 1/100 nerf as a master commit with no discussion is... a little too aggressive for me to consider it intentional. May I change hats to an edible item and Eat it if it turns out this is all part of Kevin's master plan.

**Comment by Necrosian** [comment]
Yeah same here. Was confused when i it took 3 day to get 25% to mechanic 4.

**Comment by OmeleteDuFroMago** [comment]
> 
> 
> Not gonna lie, I half-thought this was an intentional change.

I would cry if that was intentional, i love how book works in this game.

**Comment by Necrosian** [comment]
> 
> 
>  May I change hats to an edible item and Eat it if it turns out this is all part of Kevin's master plan.

Dew it!
