### ISSUE TITLE
Containers disappear when trying to contain parent from inside

### ISSUE THREAD

**Issue by Saicchi** [CleverRaven/Cataclysm-DDA#46904]
# Describe the bug

If you try to insert inside a container the container its inside of, both items disappear with everything inside.

# Steps To Reproduce

1. Spawn two backpacks
2. Wear/Wield one backpack
3. Pickup the other backpack such that its inside the first one
4. Try to insert inside the 2nd backpack the backpack you're wearing/wielding ( the 1st one )
5. Both items vanish with anything else inside it

# Expected behavior

Not being able to put the 2nd backpack inside the 1st backpack.
1st backpack not appearing on the list of available options when inserting into the 2nd backpack.

# Screenshots

![backpack](https://user-images.githubusercontent.com/47158232/105215112-9ff29d80-5b2f-11eb-8ec0-8a55d7c64d27.png)
![backpack_2](https://user-images.githubusercontent.com/47158232/105215087-9832f900-5b2f-11eb-8785-a4af40d03bfe.png)
2nd example
![backpack_3](https://user-images.githubusercontent.com/47158232/105215108-9f5a0700-5b2f-11eb-97ba-679d543ab627.png)

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.E-9017-gac88c03ac0 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]
]

# Additional context

This bug happens with any two backpacks you can put inside eachother, doesn't need to be identical.
For example, a duffel bag and a body bag.

If I were to guess what is wrong, in `inventory_holster_preset::is_shown` it should `return false` if the `item_location` its checking is the bag parent or parent's parent recursively, but currently I don't see that check being done.

**Comment by NoddingCrow** [comment]
Verified 0.E-9022-g59c9b3e-dirty
10/10 bug. At least it clears the weight of the items correctly!

**Comment by Fosheze** [comment]
If all that happens when you violate the laws of physics is your backpack disappearing I'd say you came out pretty good.
