### ISSUE TITLE
Skill Corruption

### ISSUE THREAD

**Issue by Cpl-Jordan** [CleverRaven/Cataclysm-DDA#46916]
# Describe the bug
When I was reading the book "First Aid Kit Instruction Booklet" I noticed that I wasn't gaining any %'s to Health Care. I then checked my skills and for some reason all of my skills %'s where back down to 0%.

# Steps To Reproduce
1. Read "First Aid Instruction Booklet"
2. See that the game gives you 0% to the Health Care Skill

# Expected behavior
I read "First Aid Instruction Booklet" and gain X amount of skill to Health Care. 

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-9068-g1d7609a-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context
Here is my save file: 
[Corrupt_Skill.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5846913/Corrupt_Skill.zip)

**Comment by Cpl-Jordan** [comment]
(I just saw that someone posted a glitch just like this one)

**Comment by XygenSS** [comment]
Duplicate of #46902 
Fix is up at #46908, waiting for merge
