### ISSUE TITLE
Simple alternative steel awl crafting recipe

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#46926]
# Is your feature request related to a problem? Please describe.

A steel sewing awl is one of the harder items to find, and the only current crafting recipe is quite intensive.

# Describe the solution you'd like

How to make an steel awl: 
1. Take a steel screwdriver of appropriate size.
2. File the end to a point.
3. That's it.

# Describe alternatives you've considered

Leave as is

# Additional context

<s>I think the following in tool.json would probably do the trick.</s> I thought the following would work in tool.json, but it overrides the original recipe instead of being an alternate. My json skills are obviously even worse than I thought they were. No, I am not going to submit a PR because trying to get my head around the process literally makes me unwell.

```
  {
    "result": "awl_steel",
    "type": "recipe",
    "activity_level": "LIGHT_EXERCISE",
    "category": "CC_OTHER",
    "subcategory": "CSC_OTHER_TOOLS",
    "skill_used": "fabrication",
    "difficulty": 1,
    "time": "15 m",
    "autolearn": true,
    "qualities": [ { "id": "FILE", "level": 2 } ],
    "proficiencies": [ { "proficiency": "prof_metalworking" } ],
    "components": [ [ [ "screwdriver_set", 1 ] ] ]
  },
```

**Comment by talltitanicc** [comment]
I gotcha fam.
