### ISSUE TITLE
Frozen water in a vehicle tank can still be used in crafting recipes

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#46929]
# Describe the bug

When the water in your vehicle tank has frozen you can still use it to cook or craft things. This shouldn't be possible, because frozen water doesn't pour out of a water faucet.

# Steps To Reproduce

1. Find a RV or luxury RV in winter (Or load [Narnia.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5855013/Narnia.zip) )
2. Make sure there is (frozen) water in a tank, and no other water available (there isn't - I tested removing the tank to make sure).
3. Craft something that uses water. (There is lemonade powder available)

# Expected behavior

The water should be unavailable when it is frozen in a vehicle tank. Ice should need melting on a hotplate before you can craft with it.

# Screenshots

# Versions and configuration

- OS: Windows x64 8.1
- Game Version: 0.E-9024-g785f240-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

# Additional context

I think tanks are supposed to defrost if you run the engine (c.f. https://github.com/CleverRaven/Cataclysm-DDA/pull/27824 ) but 3 hours didn't do anything for me. Having a heated or insulated tank has been suggested as a feature https://github.com/CleverRaven/Cataclysm-DDA/issues/28981 .

**Comment by PatrikLundell** [comment]
I've had crafting with the tanks frozen being blocked for at least some recipes UNLESS I had sufficient liquid water available, in which case the selection of the source of the water allowed me to select the frozen water in the tank. Thus, I could craft a batch of X, but not X+1 based on the amount of liquid water available. This was using 0.E2 stable.

**Comment by PaulBlay** [comment]
@PatrikLundell That's interesting. Either something was 'unfixed' or it is specific to some recipes and not others. So, to be specific, you can certainly craft lemonade from lemonade powder and frozen water in a 60L vehicle tank. I'll attach a save to this comment in a moment.

**Comment by PatrikLundell** [comment]
I looked at the cooking recipes, and yes, it seems they can be made from frozen water, including batch ones. Unfortunately, I don't remember what crafting I did that required access to liquid water (it was several months ago).

**Comment by Fosheze** [comment]
Isn't this kind of a necessary "feature" until we have a way to keep water from freezing in tanks. As it is we have refrigerated tanks but not heated tanks so without being able to use frozen water if you live above ground anywhere you would be screwed when winter comes around no matter how much power you have.

**Comment by PaulBlay** [comment]
@Fosheze
In theory you can keep your tanks melted by running the engine and possibly having a space heater or two. In practise it doesn't work very well. If you have water in a jerry can or other portable container you can melt in with a hotplate. Or a fire. Also the ponds and water pumps outside don't seem to have frozen yet, despite being -14C at 3am. Do rivers and ponds ever freeze over?

**Comment by PatrikLundell** [comment]
Not exactly screwed, as you can store the water in containers that can be heated, or go and get liquid water whenever you need it, but it would be a lot more complicated. Ice emptied out of a container (I think it was a bucket) got dirty, so you probably can't use that.

And I don't think the game supports ice as a terrain effect.

**Comment by PaulBlay** [comment]
> And I don't think the game supports ice as a terrain effect.

Well then, as long as you have wood and a match or a hotplate with some charges you're not going to die of thirst.  Talking of, I'm going to try lighting up braziers outside my RV to see if that helps.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
