### ISSUE TITLE
Skill Gains Reset Upon Loading Character

### ISSUE THREAD

**Issue by b3brodie** [CleverRaven/Cataclysm-DDA#46933]
# Describe the bug

Upon loading a saved character into a world, all skill gains (ie, bashing 25% to 1) are reset to 0%.

# Steps To Reproduce

1. Enter world with character, either pre-existing or newly created.
2. Gain any skill %, such as by hitting a zombie a couple of times.
3. Save and Exit game.
4. Enter world with same character, notice that every skill has been set to 0%.

# Expected behavior

Skill gains should persist upon exiting the game.

# Screenshots

Skill Before Exiting Game:
![Screenshot (12)](https://user-images.githubusercontent.com/70666939/105428317-fc26f180-5c03-11eb-9426-2030459c57fd.png)

Skills upon re-entering game:
![Screenshot (13)](https://user-images.githubusercontent.com/70666939/105428338-0f39c180-5c04-11eb-8ae5-7aab09794d34.png)

# Versions and configuration

OS: Windows 10
Game Version: 0.E-9072-g1bb53ba-dirty
Graphics Verison: UNDEAD_PEOPLE_BASE
Ingame Language: English
Mods Loaded: Bionics Professions and No NPC Needs

# Additional context

**Comment by anothersimulacrum** [comment]
Fixed in df2deed81ea74e9d73b10e1b8e2292d5738aed0f
