### ISSUE TITLE
Distribute food vanishes containers

### ISSUE THREAD

**Issue by MathTauAthogen** [CleverRaven/Cataclysm-DDA#46931]
# Describe the bug

When using the "Distribute Food" button, food within containers seems to take the containers with them when disappearing

# Steps To Reproduce

1. Make a faction camp
2. Make a food zone
3. Place 200L steel drum with clean water in the food zone
4. "Distribute food"
5. Search and fail to find the 200L steel drum anywhere

# Expected behavior

The empty containers go somewhere, if not into the sort zones right where they were found, rather than into the void. IDK if this is a bug, but if not I think it is at least undesirable behavior.

# Versions and configuration

 - OS: Ubuntu 18.04
 - Game Version: O.E-2
 - Graphics version: Tiles
 - Mods loaded: dda

**Comment by MathTauAthogen** [comment]
Maybe they go somewhere and I just can't find them but I at least can't find where they are.

**Comment by RadHazard** [comment]
Once upon a time, there was a feature where containers from distributed food would get scattered around the campfire as litter (this was back when there was only one kind of faction camp).  I'm not sure if that code still even exists, but if it does I suspect that's where the issue lies.

**Comment by PatrikLundell** [comment]
The containers disappear, as far as I've seen. Manually emptying containers onto the ground and then distribute the food does add the calories to the calorie store even when the contents are liquids. This means you can save the containers for other use through extra effort or get them disposed of automatically.
Given that water doesn't contain any calories it doesn't make sense to try to add it to the calorie store, but I certainly understand the frustration of losing a perfectly good drum.

I'd suggest adding a toggle to the Distribute Food settings to allow you to select whether to dispose of containers or just empty them (you'd still have to sort them to move them from the food zone). Early on you tend to want to collect containers, while later they tend to just add clutter.

**Comment by MathTauAthogen** [comment]
I just had food and drinks sorted into a zone that is wholly within the
food zone automatically which is why water got sorted there; I think that
water/anything with 0 calories shouldn't be consumed.

**Comment by PatrikLundell** [comment]
I believe containers now remain, so this report should probably be closed rather than marked as stale.
