### ISSUE TITLE
Roofs sometimes ain't auto-created

### ISSUE THREAD

**Issue by Igryn** [CleverRaven/Cataclysm-DDA#46942]
# Describe the bug

Motel roofs are missing

# Steps To Reproduce

1. Walk up to any motel 
2. Climb the stairs
3. Roofs are missing

# Expected behavior

Motels having roofs that you can stand on

# Screenshots

![motel](https://user-images.githubusercontent.com/51831130/105517778-22ba5a80-5ce0-11eb-9583-a65ae35912f4.jpg)

Do not take a screenshot of the crashing window. Please provide the crash logs in the "Additional context" -->

# Versions and configuration

 - Game Version:  #11388 

 - Mods loaded: mods which are on by default + no railstations

# Additional context

Several other building still don't have proper roofs

**Comment by Igryn** [comment]
Interestingly after i loaded the save, smashed a window in big room on 1 floor an then climbed the stairs again the roof tiles appeared

**Comment by Night-Pryanik** [comment]
Looks like this isn't the issue with the motels, but rather with "auto-create-roof-if-terrain-below-supports-it" mechanics which sometimes doesn't create roofs properly:
![изображение](https://user-images.githubusercontent.com/11132525/105535717-a5efa680-5d08-11eb-8592-9cf188826de3.png)

**Comment by anothersimulacrum** [comment]
We should probably remove that mechanic and require roofs to be explicitly generated now.

**Comment by PaulBlay** [comment]
While I'm looking at that screenshot, what's with the 'suicide gap' in the railing at the top left on the upper floor?

**Comment by Night-Pryanik** [comment]
There are two variants of this motel, and this gap is intended only for the first variant, while second variant simply uses the second floor mapgen.
This is a oversight and must be fixed.

**Comment by Igryn** [comment]
Loading a save seam to do the trick
