### ISSUE TITLE
Ability to clean up heaps of gore

### ISSUE THREAD

**Issue by friendfrog** [CleverRaven/Cataclysm-DDA#46945]
# Is your feature request related to a problem? Please describe.
Whenever monsters end up in my living area dealing with them often leads to big messes, I have a mop for cleaning up blood stains but if zombies are killed in an especially spectacular way they leave behind piles of meat that I can't clean up, they can't be interacted with in any way but when examining the tile they show up as heaps of gore. After verifying on discord and checking reddit, I only managed to find [one](https://www.reddit.com/r/cataclysmdda/comments/j3msii/how_to_get_rid_of_gore_on_tiles/) post about the topic.

# Describe the solution you'd like
Allow the mop to clean up heaps of gore and bloody meat chunks, or implement another tool that is capable of cleaning up these chunks/heaps.

# Describe alternatives you've considered
Dealing with the blood stains all over the floor and the vermin that spawn from it(if that's how it works)

# Additional context
![image](https://user-images.githubusercontent.com/55005591/105528301-ab61d800-5c99-11eb-961e-f1c8640d89ea.png)
my base after an unfortunate run in w/ a shocker

**Comment by Zireael07** [comment]
Dupe/related to #46828
