### ISSUE TITLE
Electric bicycle drains more stamina when electric motor is on

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#46955]
# Describe the bug

When riding an Electric Bicycle, if the electric motor is turned on, stamina is drained when riding, regardless of what speed one rides at.

Conversely, when the electric motor is turned off, and pedal power alone is used, it is possible to ride from 6-19 km/h without significant stamina loss, just like a regular bicycle.

# Steps To Reproduce

1. Spawn an undamaged electric bicycle
2. Control the bicycle, and choose "control individual engines" - ensure the electric motor is turned on
3. Ride the bicycle for a minute at 6 km/h - lose stamina
4. Control individual engines, and turn *off* the electric motor
5. Ride the bicycle up to 19 km/h - no loss of stamina

# Expected behavior

Having the electric motor on should provide power-assist, not power-resist! With both pedal and electric power enabled, I would expect to be able to ride longer, or somewhat faster, than I could do unassisted, at the cost of some battery drain.

Riding with the motor turned off should drain some stamina to power the alternator and charge the battery.

# Screenshots

![image](https://user-images.githubusercontent.com/238395/105566422-7d0be900-5ce9-11eb-8a53-763fea397c3c.png)

Riding at 6 km/h for a distance of about 20 overmap tiles (from this park to the farm and back) was enough to drain all my stamina:

![image](https://user-images.githubusercontent.com/238395/105566479-b6dcef80-5ce9-11eb-9652-d7a49cd3a985.png)

![image](https://user-images.githubusercontent.com/238395/105566474-ac225a80-5ce9-11eb-811f-8eee6563af97.png)

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-9116-g4d828a397c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by emptytriangle** [comment]
You're expected to lose stamina whenever the "foot pedals muscle" is turned on. You're using both the pedals and the electric motor. Do you still lose stamina when you turn off the power from the foot pedals?

**Comment by actual-nh** [comment]
I wonder if the bug is that the stamina loss determination isn't from the "foot pedals muscle" but the combined engine output?
