### ISSUE TITLE
Carpet makes every furniture simple to deconstruct.

### ISSUE THREAD

**Issue by superninjakiwi** [CleverRaven/Cataclysm-DDA#46957]
# Describe the bug

Carpet is simple to deconstruct, so you can select any carpeted square when selecting 'deconstruct simple furniture' from the construction menu. However, other furniture can be on top of the carpet, and when selecting a tile with furniture on it, the furniture is deconstructed, even if it would otherwise require prying and screwdriving to deconstruct. 

# Steps To Reproduce

1. Find a location with carpet, and don't bring tools (I used the Apprentice Wizard start from Magiclysm, which starts you in a basement with green carpet).
2. Find or create a light source so that you can deconstruct something.
3. Select 'Deconstruct Simple Furniture' from the construction menu while next to a non-simple furniture.
4. Select the tile with the furniture on it. The furniture will be deconstructed, no tools necessary.

# Expected behavior

Carpet and other tiles underneath furniture can't be deconstructed with furniture on top of them; deconstruction should only consider the furniture's requirements to deconstruct, and not the requirements of any underlying tiles. 

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-9024-g785f240-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    No Fungal Monsters [No_Fungi],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by BrettDong** [comment]
Confirmed on 0.E-9118 4f8278e1cf. Steps to reproduce:
* Start a new game in EVAC shelter
* Use debug menu to change the furniture of a nearby tile to TV antenna
* In construction menu, _Deconstruct Simple Furniture_ is grey
* Use debug menu to change the terrain of that tile to red carpet
* Open construction menu, _Deconstruct Simple Furniture_ turns white
* Press ENTER to deconstruct
* TV antenna is deconstructed
