### ISSUE TITLE
Crash when loading a vehicle onto bike rack with liquids

### ISSUE THREAD

**Issue by dsmky117** [CleverRaven/Cataclysm-DDA#46959]
# Describe the bug
Loading vehicle B onto vehicle A where vehicle B has a tank with liquids causes a crash when you examine the combined vehicle.

# Steps To Reproduce

1. Make vehicle A and install a bike rack.
2. Make vehicle B and install a 60L tank.
3. Fill vehicle B with liquid (I got the crash with 10L of gasoline and 60L of water).
4. Load vehicle B onto the bike rack on vehicle A.
5. Examine, crash to desktop.

# Expected behavior

No crash.

# Screenshots
![image](https://user-images.githubusercontent.com/19257672/105568729-a2a8ea80-5d09-11eb-9ab7-19177faa28bd.png)

# Versions and configuration
- OS: Windows 10
    - OS Version: 10.0 2004
- Game Version: 0.E-9116-g4d828a3-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context
In the zip is a very basic setup to reproduce the crash on experimental 11390. Load up the save, examine vehicle A and load the bike rack. Examine the vehicle again to get the crash.
[crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5859666/crash.zip)

**Comment by actual-nh** [comment]
Ping: @Jamuro-g?

**Comment by PaulBlay** [comment]
IIRC, there were some changes recently to fix a problem with fuel levels not being displayed correctly when a vehicle is loaded on a bike rack. I wonder if that is related.
