### ISSUE TITLE
Crafting simple stuff isn't training Survival/Fabrication

### ISSUE THREAD

**Issue by Stephen2** [CleverRaven/Cataclysm-DDA#46952]
# Describe the bug

Started new game:
 - Evacuee
 - Naked and Afraid
 - Stats all 4
 - Traits: Light Step, Melee Weapon Training, Night Vision, Quick, Robust Genetics
 - No skills

Craft Makeshift sling, and Fishing hook.  Neither Survival nor Fabrication are getting trained. 

# Expected behavior

Just a few days ago, this was working.  Tried to narrow down recent commits/changes but failed to find it.

# Versions and configuration
```
- OS: Fedora
    - OS Version: 32
- Game Version: 0.E-9121-gc15327e62c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]
```
built from Git hash: 4d828a397c

**Comment by Stephen2** [comment]
A clever player noticed that if you craft 1 at a time, we get no skill improvement.  But batch crafting gives expected levels of fast skill improvement.

**Comment by wapcaplet** [comment]
Confirmed in 0.E-9116-g4d828a397c

**Comment by actual-nh** [comment]
> A clever player noticed that if you craft 1 at a time, we get no skill improvement. But batch crafting gives expected levels of fast skill improvement.

Roundoff?

**Comment by wapcaplet** [comment]
When crafting only 1 fishing hook, I see that my focus does not decrease, no matter how many fishing hooks I craft, and I get no skill experience at all from them.

When crafting a batch of 2 fishing hooks, my focus drops from 100 to 83, while fabrication skill progress goes from 0% to 18%. Crafting 2 more fishing hooks drops focus from 83 to 71, and skill progress goes from 18% to 33%.

So it does look like some kind of rounding error, preventing any focus depletion, and thus any skill gain.

**Comment by BrettDong** [comment]
`base_practice` is rounded to 0 at https://github.com/CleverRaven/Cataclysm-DDA/pull/46596/files#diff-9459f71c123a6ab8652dd59412904defe2b9bef6b326d1da4b7e7671949ddd64R888:
```c++
        const double actual_craft_time = base_time_to_craft( making, batch_size );
        const double nominal_craft_time = making.time_to_craft_moves( *this,
                                          recipe_time_flag::ignore_proficiencies );
        const double adjusted_craft_time = ( actual_craft_time + nominal_craft_time ) / 2.0;
        // Normalize experience gain to crafting time, giving a bonus for longer crafting
        const double batch_mult = batch_size + ( adjusted_craft_time / 30000.0 );
        // This is called after every 5% crafting progress, so divide by 20
        const int base_practice = ( making.difficulty * 15 + 10 ) * ( batch_mult / 20.0 ) * multiplier;
        const int skill_cap = static_cast<int>( making.difficulty * 1.25 );
        practice( making.skill_used, base_practice, skill_cap, true );
```

**Comment by Stephen2** [comment]
I'm playing with this mod:
```
        const int final_practice = std::max( base_practice, 1 );
        practice( making.skill_used, final_practice, skill_cap, true );
```
seems ok, but I have no idea what I'm doing

**Comment by actual-nh** [comment]
> `base_practice` is rounded to 0 at https://github.com/CleverRaven/Cataclysm-DDA/pull/46596/files#diff-9459f71c123a6ab8652dd59412904defe2b9bef6b326d1da4b7e7671949ddd64R888:
> 
> ```c++
>         // This is called after every 5% crafting progress, so divide by 20
>         const int base_practice = ( making.difficulty * 15 + 10 ) * ( batch_mult / 20.0 ) * multiplier;
> ```

Fractions of practice need to be accumulated (until they make a whole number or reach the end of crafting; will need to make sure get at least 1 practice in the latter case), looks like. (If I have time, I'll try to create a test for this.)

**Comment by actual-nh** [comment]
BTW - Ping: @kevingranade?

**Comment by kevingranade** [comment]
The one fishhook use case should be super easy to add to the crafting tests from #46596

**Comment by actual-nh** [comment]
@kevingranade: Sorry, I wasn't clear; I was inquiring of you about fixing the original problem. A short-term fix is to wrap `( making.difficulty * 15 + 10 ) * ( batch_mult / 20.0 ) * multiplier` in roll_remainder, but that is going to result in quite a bit of variability. Preferable would be adding the prior iteration's remainder to this iteration's remainder, and only using roll_remainder for the last 5%.

**Comment by kevingranade** [comment]
Yep just dropping a note that a regression test should be easy to add if anyone decided to look into it.  I've since done so myself and simplified skill gain rate from crafting at the same time.
