### ISSUE TITLE
Furniture rotation is incorrect when there are multiple furniture items adjacent to each other

### ISSUE THREAD

**Issue by int-ua** [CleverRaven/Cataclysm-DDA#46966]
# Describe the bug

Furniture with rotations face wrong way when there are multiple adjacent pieces.

# Steps To Reproduce

Put multiple chairs next to a multitile table.
Put multiple fridges next to a wall.

# Expected behavior

All chairs face the table, all fridges face away from the wall.

# Screenshots

![chairs](https://user-images.githubusercontent.com/69649956/103141439-19cf6c80-46d3-11eb-8258-bb1c084c84bd.png)

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu;
- Game Version: 0.E-9111-gd1e702b [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

https://github.com/I-am-Erk/CDDA-Tilesets/issues/375

The rotation is determined by `cata_tiles::get_tile_values_with_ter` at https://github.com/CleverRaven/Cataclysm-DDA/blob/1c164600d12cf2ffb03a623c0ed119ed6187f02c/src/cata_tiles.cpp#L3703

**Comment by acepleiades** [comment]
I want to work on spriting furniture rotations but this bug makes it so leaving them as they are would be preferable...

**Comment by actual-nh** [comment]
What happens with the fridges?

**Comment by int-ua** [comment]
![2021-01-24-101629_1920x1080_scrot](https://user-images.githubusercontent.com/1585431/105624863-95851c00-5e2d-11eb-9975-f438b267379f.png)
It's fine with north-south walls though for some reason.

**Comment by int-ua** [comment]
![2021-01-24-103100_1920x1080_scrot](https://user-images.githubusercontent.com/1585431/105625089-6d96b800-5e2f-11eb-8957-4e5d81e4b567.png)
No, not fine

**Comment by actual-nh** [comment]
Umm... I don't use tiles because simplified graphics often don't make much sense to me. What way are the fridges turned in the above?

**Comment by int-ua** [comment]
Left side of the corridor, from top to bottom, the doors of fridges are facing:
* down
* up
* to the right

on the right side:
* down
* up
* to the left

And I'd expect the all to face away from the wall, so on the left side they all should face to the right and on the right side to the left.

There is definitely a code somewhere that tries to rotate chair sprites depending on adjacency to tables, try placing a table in a clear room away from walls and placing a chair next to it on 4 sides.

**Comment by actual-nh** [comment]
Ah. (Or at least some chairs; not a deck chair?) I see; those have ALIGN_WORKBENCH, and a table is considered a workbench; the code is in `cata_tiles::get_tile_values_with_ter`. Hrm. (Do chairs align with long tables if there's a gap between chairs, BTW?) I have to wonder if it is actually correctly going through that function.

**Comment by int-ua** [comment]
> Ah. (Or at least some chairs; not a deck chair?) I see; those have ALIGN_WORKBENCH, and a table is considered a workbench; the code is in `cata_tiles::get_tile_values_with_ter`. 

Yeah, I've even seen that but forgot that it's there

> Hrm. (Do chairs align with long tables if there's a gap between chairs, BTW?)

I wouldn't like to spend time figuring that out until this behavior that I consider broken is fixed by someone :)

> I have to wonder if it is actually correctly going through that function.

I doubt that it is, of course :)

**Comment by actual-nh** [comment]
Ping: @mlangsdorf
