### ISSUE TITLE
Add safe to drink water as a side product of boiling eggs

### ISSUE THREAD

**Issue by Igryn** [CleverRaven/Cataclysm-DDA#46972]
# Is your feature request related to a problem? Please describe.
Boiling eggs counsumes the water used to boil them

# Describe the solution you'd like
Adding safe to drink water as a side product of boiling eggs

# Describe alternatives you've considered
Leaving it as is

**Comment by mark-ik** [comment]
The water you boil eggs in stinks like eggs though, right? Is that water really clean? I wouldn't drink that.

**Comment by PaulBlay** [comment]
> The water you boil eggs in stinks like eggs though, right? Is that water really clean? I wouldn't drink that

I wonder if eggs smell worse in America than in the UK. Probably. I hear they do weird things to eggs over there. https://www.huffingtonpost.co.uk/entry/english-eggs-vs-american-eggs_n_5403941

Seriously, though, the standard 'boil the water' to clean it method that is used just makes it safe(ish) to drink. Water from the typical swamp or forest pond isn't going to smell or taste any better than water that's had eggs boiled in it. Even American eggs.

**Comment by Igryn** [comment]
> The water you boil eggs in stinks like eggs though, right? Is that water really clean? I wouldn't drink that.

Depends on was the egg clean or dirty on the outside. But in any case it would be safe too drink. Most water you have access in survival situatioun woul stink anyway if you boil it. especialy if stagnant from pond

Is people deam it undrinkable let it produce just regular water so it dont waste it? but you could slit just boil the regular water you get out of it.

**Comment by actual-nh** [comment]
From [here](https://github.com/CleverRaven/Cataclysm-DDA/pull/45680#discussion_r563200785):
> Yeah this would go back into that issue put up by kevingranade talking about water purity. Personally, I think it's good as it is until we do a full revamp of determining how clean water is.

This was about whether you needed clean water for making bread (it depends on the recipe - does it use yeast - and what exactly is meant by water cleanliness).

**Comment by Igryn** [comment]
Regardless of organoleptic properties water is boiled and thus safe to drink, the same way pond water is safe to drink after boiling

**Comment by actual-nh** [comment]
> If anything its even safer because you need to keep it boiling for some time in irder to cook eggs, while just bringing it to boil and stoping on it may leave more surviving pathogens

True; likely more water lost, incidentally - you probably won't wind up with the same amount of water (as you put in) as a byproduct.

**Comment by Igryn** [comment]
> > If anything its even safer because you need to keep it boiling for some time in irder to cook eggs, while just bringing it to boil and stoping on it may leave more surviving pathogens
> 
> True; likely more water lost, incidentally - you probably won't wind up with the same amount of water (as you put in) as a byproduct.

Yeah some loss maybe, but dont think its enough to really think about it. From personal experience i always have most of water still liquid after boiling eggs

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
