### ISSUE TITLE
The effect of bodytemp_modifiers does not match the doc description

### ISSUE THREAD

**Issue by zwa73** [CleverRaven/Cataclysm-DDA#46999]
我发现 bodytemp_modifiers 的效果和doc里的说明相反
如果我设置bodytemp_modifiers = [ -100000, 100000 ];
我的人物会过热
如果是 [ 100000, -100000 ]则不会
这是个bug么？
---Google Translate---
I found that the effect of bodytemp_modifiers is opposite to the description in the doc
If I set bodytemp_modifiers = [-100000, 100000 ];
My character will overheat
If it is [100000, -100000] then not
Is this a bug?

The version is cataclysmdda-0.E-Windows_x64-Tiles-b11399

**Comment by wapcaplet** [comment]
See #52940 for additional info

**Comment by ZhilkinSerg** [comment]
I do not see any inconsistencies between doc and the code.

First value in pair is used when character is overheated and second value in pair is used when character is not overheated:

https://github.com/CleverRaven/Cataclysm-DDA/blob/050e934d5bbf3af11f51ff9a81134a257743ae12/src/mutation_data.cpp#L359-L363

https://github.com/CleverRaven/Cataclysm-DDA/blob/050e934d5bbf3af11f51ff9a81134a257743ae12/src/character.cpp#L7912-L7919

Exactly the same as described in the doc:

https://github.com/CleverRaven/Cataclysm-DDA/blob/050e934d5bbf3af11f51ff9a81134a257743ae12/doc/JSON_INFO.md#L1984

**Comment by zwa73** [comment]
> I do not see any inconsistencies between doc and the code.
> 
> First value in pair is used when character is overheated and second value in pair is used when character is not overheated:
> 
> https://github.com/CleverRaven/Cataclysm-DDA/blob/050e934d5bbf3af11f51ff9a81134a257743ae12/src/mutation_data.cpp#L359-L363
> 
> https://github.com/CleverRaven/Cataclysm-DDA/blob/050e934d5bbf3af11f51ff9a81134a257743ae12/src/character.cpp#L7912-L7919
> 
> Exactly the same as described in the doc:
> 
> https://github.com/CleverRaven/Cataclysm-DDA/blob/050e934d5bbf3af11f51ff9a81134a257743ae12/doc/JSON_INFO.md#L1984
> 
> These bonuses are used like that in the code - I am also not seeing issue here:
> 
> https://github.com/CleverRaven/Cataclysm-DDA/blob/050e934d5bbf3af11f51ff9a81134a257743ae12/src/character_body.cpp#L336-L341


"overheated" 是代表了体温高于正常水平么？如果是，我确定我没错，也许你可以在游戏里按我说的设置[-1000,+1000]与[+1000,-1000]试试
---------google translate-------------
Does "overheated" mean that the body temperature is higher than normal?  If it is, I’m sure I’m right, maybe you can try to set 
[-1000,+1000] (I think is a good effect)  or
[+1000,-1000] (I think is a bad effect)
in the game as I said

 // Difference between high and low is the "safe" heat - one we only apply if it's beneficial 
 const int mutation_heat_bonus = mutation_heat_high - mutation_heat_low; 

I see that the value generated by bodytemp_modifier_traits is only used here
and that function parameters is a const true and false

so mutation_heat_bonus is a fixed value or constant？

if i set to [500,1000] then  mutation_heat_bonus is always (1000-500) ==500?

so "overheated" not a trigger ,just a meaningless parameter?

**Comment by zwa73** [comment]
It seems that github search can’t find everything?  I did not download the code, maybe I did not search all the references
