### ISSUE TITLE
Clipping wings of domesticated birds (goose, chicken, duck, turkey)

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#46994]
# Is your feature request related to a problem? Please describe.

Real life domesticated birds (and at least some CDDA ones) will happily fly over fences to escape their pens. 

# Describe the solution you'd like

A traditional method of preventing farm birds escaping is to use scissors to cut the primary feathers from the tip of one wing (not both). This does no harm to the bird except to its dignity and ability to fly. The person doing the clipping might get pecked or scratched, though. In real life primaries moult and regrow between once every six months to two years - but I think we can ignore that. I would suggest adding 'clip wing feathers' to the actions available on a pet carrier or livestock carrier when it is occupied by a chicken, duck, goose or turkey. Tame, and wild, birds with clipped wings would no longer be able to fly.

# Describe alternatives you've considered

Yes, tame birds can be individually tied down by a rope or trapped inside a building with a roof. Free range eggs taste better, though.

# Additional context

**Comment by actual-nh** [comment]
This actually isn't needed for a lot of chicken breeds, provided you keep them fed - they only fly to get away from a predator, and aren't very good at it. (And clipping only one wing can cause the bird injury if it does try to fly, from what I've read.)

Biology moment: Note that breast meat in chickens is white meat - for instance, it doesn't have myoglobin, which stores a bit of oxygen in muscles that have much endurance. It's focusing on short bursts of strength. (Technically, this is fast glycolytic muscle.) Darker meat in chickens is from the legs - they run around a lot, and do need endurance for those muscles.

**Comment by PaulBlay** [comment]
> This actually isn't needed for a lot of chicken breeds, provided you keep them fed - they only fly to get away from a predator, 
> and aren't very good at it.

It depends on the chicken's personality as much as the breed, IMO. It's always the same one that escapes, until it gets clipped. The ones that don't are left alone. Some chickens prefer to roost up trees given the chance.

> (And clipping only one wing can cause the bird injury if it does try to fly, from what I've read.)

Eh, the first result that came up was from PETA so I'm dubious about that one. There is some controversy, but most sites seem a lot more reasonable about it.

**Comment by actual-nh** [comment]
> > This actually isn't needed for a lot of chicken breeds, provided you keep them fed - they only fly to get away from a predator,
> > and aren't very good at it.
> 
> It depends on the chicken's personality as much as the breed, IMO. It's always the same one that escapes, until it gets clipped. The ones that don't are left alone. Some chickens prefer to roost up trees given the chance.

OK. The game really needs a way to say "this monster has this capability but is reluctant to use it", though. It'd also be nice for a brighter feral (with a gun).

> > (And clipping only one wing can cause the bird injury if it does try to fly, from what I've read.)
> 
> Eh, the first result that came up was from PETA so I'm dubious about that one. There is some controversy, but most sites seem a lot more reasonable about it.

Pet chicken sites were the ones I was looking at saying that.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/what-do-turkeys-eat/25801/5

**Comment by Zireael07** [comment]
Sorta related to #48008

**Comment by Zireael07** [comment]
This would fix #62929 which is almost certainly the birds flying off
