### ISSUE TITLE
Stat through kills stat increase doesn't affect success rate when installing bionics

### ISSUE THREAD

**Issue by Foxtrot-Uniform42** [CleverRaven/Cataclysm-DDA#46991]
# Describe the bug
When you increase INT stat with "Stat through kills", it not improves bionic installation success rate.

# Steps To Reproduce
1. Check installation rate w/o increased INT stat from STK mod
2. Check installation rate with increased INT stat from STK mod
3. In debug menu stat remains unchanged.

# Expected behavior
Increasing intelligence with Stat through kills mod should affect all activities with increased stat (e.g. increase bionic installation success rate)

# Screenshots
![Capture](https://user-images.githubusercontent.com/46412513/105625544-cbd19400-5e4b-11eb-9f96-90f8f499d1eb.JPG)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.E-9141-gdc59dbd-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    Bionic Professions [package_bionic_professions],
    C.R.I.T Expansion Mod [crt_expansion],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    Fuji's Military Profession Pack [fuji_mpp],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills],
    No Zombie Revivification [No_Revive_zombies]
]

**Comment by PaulBlay** [comment]
Interesting. I presume 'stats_through_skills' has the same flaw?
