### ISSUE TITLE
Character does not use firewood source to keep fire going

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#47008]
# Describe the bug

When using a firewood source with a nearby fire, after the fire is lit, the character does not use the firewood source to keep the fire going.

# Steps To Reproduce

1. Get a brazier, or find a fireplace or oven
2. Use the construction menu to mark a firewood source next to it
3. Get 2 planks and put them on the firewood source
4. Light a fire in the brazier - 1 plank is used to start it
5. Wait a couple hours - the fire goes out, with 1 plank still unused in the firewood pile

Using splintered wood is a quicker way to reproduce the issue, since those burn out much faster.

# Expected behavior

Expected avatar to add wood to the fire when necessary to keep it burning.

# Screenshots

Here, one plank has burnt away to ash while another unburnt plank remains on the firewood pile:

![image](https://user-images.githubusercontent.com/238395/105647891-caad6080-5e65-11eb-85a5-98ea1dbb5af4.png)

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-9182-g85a23edc64 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

Confirmed by several users on dev Discord

**Comment by Djinn247** [comment]
Confirmed for me.

# Steps To Reproduce


1. Made basecamp wood stove.
2. Put firewood source and dropped charcoal on top of it.
3. I am standing with basecamp wood stove on south, and firewood source directly north east. It is night time.
4. Light fire in stove.
5. Start crafting without moving.
6. Fire goes out.

# Screenshots

![unknown](https://user-images.githubusercontent.com/42262104/105648034-58b33680-5eba-11eb-8027-a938aa827942.png)



# Versions and configuration


- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-9181-g308bec1-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Mythical Martial Arts [MMA],
    Graphical Overmap [Graphical_Overmap],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by xthorgoldx** [comment]
Discovered an interesting interaction: firewood spots will be used if the player is _manually_ setting a fire in a furniture object with the FIRE_CONTAINER tag (braziers, fireplaces, etc) that has no fuel, then the player will draw fuel from the nearest firewood source. This only works for lighting the fire, though.

**Comment by NyarlathotepZERO** [comment]
I have had a similar issue as above.

fire container:wood stove
fuel source: splintered wood [this is placed in a single tile which has a 'splintered wood' custom zone and also a 'firewood source' zone placed on it]

This is using an old save, so not sure if this could be causing the issue. The last time I played this save was Build #11384 and the zones were placed after updating to  Build #11402.

**Comment by Trioct** [comment]
Just chipping in. Pretty sure it's
```cpp
// void player_activity::do_turn( player &p ), player_activity.cpp
if( *this && type->will_refuel_fires() && !no_fire ) {
    no_fire = !try_fuel_fire( *this, p );
}
```
And considering that with these being every reference I could find to no_fire
```
> grep -rn 'no_fire' src
src/player_activity.h:76:        bool no_fire = true;
src/player_activity.cpp:216:    if( *this && type->will_refuel_fires() && !no_fire ) {
src/player_activity.cpp:217:        no_fire = !try_fuel_fire( *this, p );
```
I'm pretty sure the inside of the if statement to drop planks on a fire is dead code atm since no_fire seems to always be true.
So I think it was introduced in #46596.

**Comment by DalenTalas** [comment]
I am once again noticing this issue. Please reopen.

- OS: Windows
    - OS Version: 10.0.19043.2006 (21H1)
- Game Version: bf9ca7c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Dark Days of the Dead [classic_zombies]
]
