### ISSUE TITLE
Picking up items is too slow

### ISSUE THREAD

**Issue by zwa73** [CleverRaven/Cataclysm-DDA#47007]
500*dragon_bklack_scale 足以让我的游戏卡住5分钟以上
在 b11388  或者更早的版本就没这种问题
---Google Translate---
500*dragon_bklack_scale is enough to make my game stuck for more than 5 minutes
There is no such problem in b11388 or earlier versions

The version is cataclysmdda-0.E-Windows_x64-Tiles-b11399

**Comment by BrettDong** [comment]
我捡500个黑龙只卡了不到两秒钟，你方便发个存档让我调试吗？

Picking up 500 dragon black scales only took me less than 2 seconds in real life. Could you please post a save file?

**Comment by zwa73** [comment]
> 我捡500个黑龙只卡了不到两秒钟，你方便发个存档让我调试吗？
> 
> Picking up 500 dragon black scales only took me less than 2 seconds in real life. Could you please post a save file?

我发现了,我身上带了200个玻璃罐和加仑壶
我把这些丢了就可以以正常速度捡起 dragon_bklack_scale
---Google Translate---
I found out, I took 200 glass jars and gallon jugs with me
I lose these and can pick up dragon_bklack_scale at normal speed

**Comment by BrettDong** [comment]
<img width="972" alt="螢幕截圖 2021-01-24 下午10 32 18" src="https://user-images.githubusercontent.com/21075502/105661197-d9fad100-5e9a-11eb-84d9-b926e22b2700.png">

**Comment by BrettDong** [comment]
你方便把发生卡死的存档压缩成zip发上来吗？

**Comment by zwa73** [comment]
> 你方便把发生卡死的存档压缩成zip发上来吗？

可能纯粹是我物品太多？我上面那个描述可能不太准确
[zwa732.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5867525/zwa732.zip)

**Comment by Aivean** [comment]
`item::weight` is also a bottleneck in fire processing.  Probably some caching is warranted there.

Also, from the cursory look at `item_pocket::can_contain`, relatively expensive `weight()` and `volume()` methods are called twice.

**Comment by Cenness** [comment]
Any updates on this?
Here is my save, it takes minutes of real time to pick up more than 4 items, ~20 seconds for any single item. And 6 seconds from pressing [i] to inventory window pop up.
[thousands.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6393257/thousands.zip)

Game info:
- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-10395-g4525b4f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Wuxia rings [wuxia_rings],
    Graphical Overmap [Graphical_Overmap],
    No Fungal Monsters [No_Fungi],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]]

**Comment by actual-nh** [comment]
Problems similar to this inspired #47986 - at least have the objects (bone skewers) that were slowing things down (#47983) be useful!

**Comment by Cenness** [comment]
That's good. But there are other ways to get a lot of items, albeit not that fast. In my save there are zero skewers.

**Comment by zwa73** [comment]
我觉得在背包里有更多物品(特别是 mutant_bug_hydrogen_sacs 或者 dragon_black_scale 等需要每个分别储存的)的时候捡起物品所耗费的时间会更长
我确定问题不仅仅是https://github.com/CleverRaven/Cataclysm-DDA/issues/48937 
我看到我的 debug_backpack 的描述文本已经长达几十万
而且这其中大多是重复的 mutant_bug_hydrogen_sacs 等物品的文本
以此来看,我猜测是在捡起物品时做了大量重复的文本处理或类似操作导致了我的问题
------------ google translate ------------------
I think it will take longer to pick up items when there are more items in the backpack (especially mutant_bug_hydrogen_sacs or dragon_black_scale that need to be stored separately)
I'm sure the problem is not just https://github.com/CleverRaven/Cataclysm-DDA/issues/48937
I see that the description text of my debug_backpack has reached hundreds of thousands
And most of these are repeated texts of mutant_bug_hydrogen_sacs and other items
From this point of view, I guess that a lot of repeated text processing or similar operations when picking up items caused my problem.
![304Q6U9KM}X1P29X NTCMRB](https://user-images.githubusercontent.com/10141750/143587856-5250f6d2-34cf-42d3-99e1-570e8c086c9a.png)
![XLT}LLH_ XL$EZC%UFDOIS8](https://user-images.githubusercontent.com/10141750/143588052-6d14d555-62d9-458b-8191-a10597bccb3b.png)
It took me more than 10 minutes to pick up these mutant_bug_hydrogen_sacs
