### ISSUE TITLE
Group keybindings by type

### ISSUE THREAD

**Issue by Proxiehunter** [CleverRaven/Cataclysm-DDA#47038]
Description
As the title says group the various keybindings by what happens when you press the key. For example "Craft, Recraft, Disassemble, etc" grouped under the heading Crafting, "wield, throw, fire, toggle attack mode, etc." grouped under the heading Weapons, "bionics, mutations, re-layer clothing, sleep, etc." grouped under the heading Player and so on.

What does this proposal attempt to solve or improve?
Scrolling through what nearly every key on your keyboard does in game can be a long and tedious task when you don't know or have temporarily forgotten what key you need to press to do what you're attempting. A post [here](https://www.reddit.com/r/cataclysmdda/comments/l55331/keybind_cheat_sheet_so_many_controls/) on reddit of someone's hand made cheat sheet made me realize how much easier using the keybinding menu would be if the keybinds were grouped into categories like that.

This would be a _huge_ help to beginning players as well as those of us who take a break and then return and lets face it I'm sure even those who've been playing from day one sometimes need to check the key for a task they rarely do but suddenly feel the need to do this playthrough.

I think it would be a deceptively big quality of life improvement for such a small thing.

Which (other) solutions should be considered?
I suppose just not doing it would be the main possibility. I think the main time sink for this particular proposal would be deciding what heading to put each key under.

**Comment by ZhilkinSerg** [comment]
There is a search in keybindings window.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
