### ISSUE TITLE
A rifle with insufficient UPS charges cannot use non-UPS fire modes

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#47037]
# Describe the bug

If I have a weapon that requires UPS charges to fire, I am unable to use alternative fire modes (an underbarrel M320, for example) because I cannot invoke the weapon's `f`ire interface.

# Steps To Reproduce

1. Ensure your character has Launchers 2.
2. Spawn an XM34 EMP projector.
2. Spawn an M320, and some 40x46 grenades.
3. Attach the M320 and load it.
4. Attempt to `f`ire the weapon, with the intention of using the launcher.

# Expected behavior

I expected to be able to use the M320 even if the gun itself can't fire.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 20H2 (build 19042.746)
- Game Version: 0.E-9186-gd2f3109-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded:
    - Dark Days Ahead [dda],
    - C.R.I.T Expansion Mod [crt_expansion],
    - No Fungal Monsters [No_Fungi],
    - Disable NPC Needs [no_npc_food],
    - Alternative Map Key [alt_map_key],
    - SpeedyDex [speedydex],
    - Stats Through Kills [stats_through_kills],
    - Stats Through Skills [StatsThroughSkills],
    - No Rail Stations [No_Rail_Stations]

**Comment by PaulBlay** [comment]
This is a similar issue to https://github.com/CleverRaven/Cataclysm-DDA/issues/30137

**Comment by ToxiClay** [comment]
> This is a little like #30137 .
> 
> Quick question, if you have UPS charge available then can you fire the non-UPS attachment on its own without using any charge?

Yes, I can fire the grenade launcher without consuming UPS charges.

However, testing that exposed another issue: reloading the launcher does not emit a message saying that I've done so.
