### ISSUE TITLE
Can’t throw clothes if already wearing another item of the same kind

### ISSUE THREAD

**Issue by utechenko-v** [CleverRaven/Cataclysm-DDA#47044]
# Describe the bug
Character can't throw item, e.g. hip flask, if wearing same kind of item, e.g. another hip flask. Message displayed on attempt to throw item: “You are not wearing that item”.

# Steps To Reproduce
1. Get two wearable items, e.g. 2 hip flasks or 2 wrist watches
2. Wear one of items
3. Wield other item
4. Throw wielded item (by throw hotkey, or via inventory - item - menu - throw)

Actual result: Message displayed on attempt to throw item: “You are not wearing that item”. Game is not switched to throw targeting mode
Note: after dropping item which was on a character, it is possible to throw wielded item.

# Expected behavior
Game should be switched to throw targeting mode on "throw" command. 
User should be able to throw item regardless of character wearing another item of the same kind or not.

# Screenshots
N/A

# Versions and configuration
Platform : Windows_x64
Graphics : Tiles
Build number : #11388
Build version: 0.E-9111-gd1e702b
Major version: 0.E
Mods loaded: default mods (IIRC: dark days ahead, disable NPC needs, bionic professions)

# Additional context
N/A

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/cant-throw-clothes-if-already-wearing-another-item-of-the-same-kind/25782/3
