### ISSUE TITLE
New "excluding words in recipes filter" works only for names

### ISSUE THREAD

**Issue by ynemo** [CleverRaven/Cataclysm-DDA#47051]
# Is your feature request related to a problem? Please describe.
New "excluding words in recipes filter" works only for names

# Describe the solution you'd like
I wish it works for components and all other filter types. 
For instance, i want to see what can be done with sugar, but not with sugar beet. Or i would like to see what can be crafter without anvil.

**Comment by ZhilkinSerg** [comment]
> Or i would like to see what can be crafter without anvil.

How does it help?

**Comment by Qrox** [comment]
> How does it help?

It can be useful when you don't have an anvil but want to see what can be crafted with the tools you currently have, I suppose.

**Comment by actual-nh** [comment]
Longer-term, a more general filter of "ignore what I can't do without more tools than are in my camp/owned by my faction" would be useful.

**Comment by ZhilkinSerg** [comment]
> > How does it help?
> 
> It can be useful when you don't have an anvil but want to see what can be crafted with the tools you currently have, I suppose.

Generic "things I can craft" filter would probably be better for that.

**Comment by xthorgoldx** [comment]
Another example of use: targeted proficiencies. Let's say I'm trying to get my "Principles of Leatherworking" proficiency up; in order to level it faster (?) and minimize loss rate, I want to see ONLY recipes that have Principles of Leatherworking and not those that have Leatherworking proper.

**Comment by actual-nh** [comment]
> Another example of use: targeted proficiencies. Let's say I'm trying to get my "Principles of Leatherworking" proficiency up; in order to level it faster (?) and minimize loss rate, I want to see ONLY recipes that have Principles of Leatherworking and not those that have Leatherworking proper.

Hmm... "Filter: Recipes I can learn from", perhaps with specified maximum loss rate?

**Comment by actual-nh** [comment]
For a more-generalized "-" on @Mrzjadacz's nice filter, how would you specify that components/skills/proficiencies - instead of names - were to be excluded? Or are you thinking of it being a negation for any of those?

**Comment by Mrzjadacz** [comment]
> filter of "ignore what I can't do without more tools than are in my camp/owned by my faction"

> Generic "things I can craft" filter would probably be better for that.

Things you can and can't craft have different colors so I don't understand what more would you want 

@anyone interested in more excluding

Making exclude filters is easy, it took more to figure out the code and add description
```cpp
            case search_type::name:
                return lcmatch( r->result_name(), txt );

            case search_type::exclude_name:
                return !lcmatch( r->result_name(), txt );
```

**Comment by ynemo** [comment]
btw, is it possible to add markers start string and end string? I don't know how to name it properly.  
some examples:
c:"corn" will search for recipes with component limited to corn (4 digits), no cornmeal and etc 
c:"corn  will include cornmeal, but exclude raw corn (if we had raw corn)

**Comment by Mrzjadacz** [comment]
> c:"corn will include cornmeal, but exclude raw corn (if we had raw corn)

Use `corn, -raw corn` instead
It would be possible but I doubt anybody would want to do it anytime soon

**Comment by ynemo** [comment]
> > c:"corn will include cornmeal, but exclude raw corn (if we had raw corn)
> 
> Use `corn, -raw corn` instead
> It would be possible but I doubt anybody would want to do it anytime soon

this what this issue about, i cant limit components filter. Only names of recipes can be filtered exclusively.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
