### ISSUE TITLE
Suggestions for improved messages an behavior re. some locked doors, crowbars and lockpicks

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#47069]
# Is your feature request related to a problem? Please describe.

When you try and fail to open a closed metal door the game does not recognize if you have a crowbar on you. If you use 'o'pen it does not recognize it as a door. There are some other quirks regarding opening closed doors which I've addressed while I'm here.

# Describe the solution you'd like

1. If you use 'o'pen next to a locked metal door and there is nothing else adjacent that could be opened you could give a message like: "The closed (metal) door is locked." rather than "There is nothing that can be opened nearby."

2. If you use 'e'xamine next to a locked metal door and you are carrying a crowbar you could give a message like: "The closed metal door is locked.  If only you had something to pick its lock with... You realize the closed metal door is too strong to open with your crowbar." At present it does not give any indication that you remember you have a crowbar in your hands.

3. If you 'a'pply your crowbar while next to a locked metal door and pick "1. Pry crate, window or door" you will be told "There is nothing to pry nearby." It would be better if it gave a message like "You realize the closed metal door is too strong to open with your crowbar."

4. If you use 'e'xamine next to a locked door (that could theoretically be pried open) and you have both a tool with prying quality and a improvised lockpick the game often ignores the lockpick and only tries the tool with prying. Even if you are very good with a lockpick and the tool with prying has no chance of success. I'm not sure exactly how this case should be dealt with, but if would be good if you would either try both in turn or the game would pick the one most likely to succeed. 

# Describe alternatives you've considered
Leave as is. 

# Additional context
There are probably other 'door like' terrain other than the closed metal door that should also be considered as a potential target for crowbars. Like the metal security door next to card readers.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
