### ISSUE TITLE
upper limit of attack.strength_damage in mutation seems to be only 20?

### ISSUE THREAD

**Issue by zwa73** [CleverRaven/Cataclysm-DDA#47078]
# Is your feature request related to a problem? Please describe.
我发现mutation中的attacks.strength_damage的力量加成上限似乎只有20？
我设置 strength 至100所造成的的伤害也不会高于20 strength 造成的伤害
我认为它应该与普通攻击一样没有上限
---google translate---
I found that the upper limit of attack.strength_damage in mutation seems to be only 20?
I set the strength to 100 and the damage caused will not be higher than the damage caused by 20 strength
I think it should have no upper limit like normal attacks

**Comment by actual-nh** [comment]
What do you mean by "in mutation"?

**Comment by BrettDong** [comment]
> What do you mean by "in mutation"?

OP means strength damage in mutation attack.

**Comment by BrettDong** [comment]
上限值是15：
```c++
                damage_instance dam = mut_atk.base_damage;
                damage_instance scaled = mut_atk.strength_damage;
                scaled.mult_damage( std::min<float>( 15.0f, get_str() ), true );
                dam.add( scaled );
```
https://github.com/CleverRaven/Cataclysm-DDA/blob/854f10d0c1df776ffc58bc81914675643511374c/src/melee.cpp#L2154

**Comment by PaulBlay** [comment]
I think OP has a point. Ranged combat with big guns already has the clear advantage of being safe(ish) from retaliation. If your ridiculously muscled hulking character hits something with a fist the size of a cantaloupe you'd want to get something for your mutagen gulping effort.

**Comment by anothersimulacrum** [comment]
If it makes sense as a real result of that scenario, it should happen. If it's arbitrary effort to make doing that route match with other routes, it should not.

**Comment by PaulBlay** [comment]
@anothersimulacrum

"Mo' strength, mo' damage" is pretty logical. The major limitations being things like armour penetration and that, arguably, applying more strength without limit would end up damaging your own limbs if the muscles, ligaments, joints and bones are not also suitably reinforced. Strength 15 is big, but it is not beyond a starting character who dumps all points into that stat with a single point pool. So, 15 is probably "professional athlete strong" but not "bionic / mutant strong".

Was there any reasoning given for the 15 limit in the first place, or was THAT an arbitrary game balance decision?

**Comment by zwa73** [comment]
实际上几个 hard_code attacks 的效果就好像没有上限，比如藤蔓攻击

In fact, the effects of several hard_code attacks seem to have no upper limit, such as vine attacks

**Comment by emptytriangle** [comment]
I was wondering about this. It does not seem like enabling the hydraulic muscles CBM causes my sledgehammer attacks to do more damage.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/whats-happening-in-your-randomly-generated-apocalypse-part-2/14511/2684

**Comment by zantanzuken** [comment]
it seems as though specifically blunt attacks (with strength) are capped in damage, where other damage types may not be, but also may not scale from strength.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
