### ISSUE TITLE
Cant use crucible to collect water from a source 

### ISSUE THREAD

**Issue by NyarlathotepZERO** [CleverRaven/Cataclysm-DDA#47075]
# Describe the bug

Cannot use crucible as a container to collect water from a water source

# Steps To Reproduce

1. wield crucible
2. stand next to water source
3. use 'e' on water source and choose 'pour into a container' option

# Expected behavior

I would expect it to fill as with any other device with a similar containing quality (eg:clay pot)

# Screenshots

none

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-9223-ga149ceb-dirty
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: dda

# Additional context

none

**Comment by OliveChukar** [comment]
Checked in version 0.E-9285-g0ec6948-dirty both the crucible and clay crucible lack any ability to hold anything. Do not know if this is intended.  A crucible is generally a cup/bowl like thing used for melting materials that need to get very hot. It would be possible to carry water or other liquids in one like any other container without a lid however if it had been used to melt anything toxic putting food or water in it could be a bad idea.

**Comment by NyarlathotepZERO** [comment]
A crucible that had been used for melting metal would more than likely have a layer of glasslike flux covering the surface. This 'glaze' would make it above average in quality as a vessel for transportation of water. 

As for its toxicity, I would not hesitate to say that there are countless other activities that would be more hazardous to a player's health in comparison to the transportation of water in a crucible, especially when you also consider that the crucible has a 'food cooking' quality of 1.
