### ISSUE TITLE
Large wallet is not larger than wallet

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#47085]
# Describe the bug

The large wallet has exactly the same numerical capacity in terms of volume and mass as the wallet. They both can hold exactly 210 Merch.

# Steps To Reproduce

1. Load save ( [Narnia.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5888074/Narnia.zip)  )
2. Wield the wallet
3. Pick up 233 Merchs
4. Examine the wallet in your 'i'nventory by pressing [ENTER] or [RETURN] (⏎)
5. 'i'nsert the merch into your wallet.
6. Note that you have 210 Merchs in your wallet.
7. 'U'nload the Merchs from your wallet
8. Repeat steps 2 to 5 with your large wallet
9. Note that you have 210 Merchs in your large wallet.

# Expected behavior

I would expect the large wallet to be larger than the not-large wallet

# Screenshots

![wallets](https://user-images.githubusercontent.com/54060142/106154373-7103a980-6177-11eb-9e72-02ae7c556ebb.png)

# Versions and configuration

- OS: Windows x64 8.1
- Game Version: 0.E-9155-g1319073-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

# Additional context

While you're looking at wallets, the Travel wallet's description is incorrect. It states ... "used to carry items such as currency, identification documents, laminated cards, and other small items". The fact is that it can not be used to carry currency (merch, dollars, flatcoin, or hub gold coin).

**Comment by Saicchi** [comment]
A large wallet is just the regular wallet with a description and material changes with an extra flag. Its missing the pockets redefinition ( see travel wallet for example of pockets ).
```json
{
    "id": "wallet_large",
    "type": "GENERIC",
    "copy-from": "wallet",
    "name": { "str": "large wallet" },
    "description": "A flat case used to carry items such as currency, identification documents, laminated cards, and other small items.",
    "material": [ "leather" ],
    "extend": { "flags": [ "FANCY" ] }
}
```
