### ISSUE TITLE
Magiclysm: Monstrous races produce animal type butchery products

### ISSUE THREAD

**Issue by Sirbab** [CleverRaven/Cataclysm-DDA#47081]
# Describe the bug

When butchered, Orcs, lizards, ogres etc all produce raw meat, and raw leather.  I'm not sure this is a bug, or even an oversight as this may be intended behavior. 

# Steps To Reproduce

1: Find and enter an orc encampment.
2: Kill orc
3: Butcher
4: Notice the results. 
(or just look in harvest.json i guess)

# Expected behavior

Given the trend we have with other semi sapient humanoids giving demi-human meat and stomachs, it stands to reason that the monstrous races would provide demi-human harvests.

# Screenshots
![image](https://user-images.githubusercontent.com/1490991/106107865-74664900-6115-11eb-8386-cb7697bd200e.png)

# Versions and configuration

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5885669/debug.log)

 - OS: Windows 10 64 bit
 - Game Version: 0.E-9182-g85a23ed-dirty
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: 
![image](https://user-images.githubusercontent.com/1490991/106108294-0a9a6f00-6116-11eb-92d7-13cbfa56f126.png)

# Additional context

None

**Comment by emptytriangle** [comment]
I think it's intentional because they are not mutated, they're natural. And eating orcs is somewhat common in fantasy, they're like giant pigs or boars so should be good eating. Some/all of them may need to get the cannibalism penalty though. Eating an ogre or lizardman is probably mentally disturbing

**Comment by actual-nh** [comment]
Do goblins give demihuman harvests (about to go back to grading)?

**Comment by Sirbab** [comment]
> 
> 
> Do goblins give demihuman harvests (about to go back to grading)?

Goblins have the demihuman harvest group.

**Comment by Maleclypse** [comment]
All monstrous races should be using the demihuman harvests. Unless they are particularly bizarre and have acid for blood or something else extreme.
