### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by bunnybananza** [CleverRaven/Cataclysm-DDA#47094]
# Describe the bug

The game crashes whenever I try to load the save. I crashed after using the auto-travel function and now cannot load saves without the game crashing before loading in. Fresh install didn't help.

# Steps To Reproduce

Whenever loading the save

# Expected behavior

I thought the game would just load normally

# Screenshots

# Versions and configuration

Dark Days Ahead, BlazeIndustries, CRT_Expansion, Graphical_Overmap, speedydex, StatsThroughSkills

# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5890946/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5890951/debug.log)
[save file](https://drive.google.com/file/d/1WTnrtfJxyGdbExAI6jlhDddRNBdyOnzj/view?usp=sharing)

**Comment by Ramza13** [comment]
Can you attach the save file?

**Comment by bunnybananza** [comment]
I've attached the save file. It was too large and I couldn't figure out how to share it but I think I got it figured out.

**Comment by Ramza13** [comment]
> 
> 
> I've attached the save file. It was too large and I couldn't figure out how to share it but I think I got it figured out.

So I think you need to change the permissions or something, it says I don't have access.

**Comment by bunnybananza** [comment]
I fixed the link and you should be able to download it now.

**Comment by Ramza13** [comment]
Ok so I've posted a fix for the crash.  That said I have no idea how you got into this situation.  I don't think there should be any side effects after the activity is canceled but if you see any weird behavior or figure out how you caused this after the fix is merged it would be good to know.

**Comment by bunnybananza** [comment]
Okay, I'm not quite sure how to apply the fix.

**Comment by actual-nh** [comment]
> Okay, I'm not quite sure how to apply the fix.

It would probably be easiest for you to wait until the fix is in ("merged") the main game version, then download the new version, unless you're willing and able to compile the game locally.

**Comment by bunnybananza** [comment]
What would I have to do?

**Comment by actual-nh** [comment]
Take a look at the [doc/COMPILING](https://github.com/CleverRaven/Cataclysm-DDA/tree/master/doc/COMPILING) directory. It depends on what your OS is, among other things.

**Comment by int-ua** [comment]
Please include conditions required for the segfault in the title.

**Comment by Trioct** [comment]
I ran your save file through the fix because where's the fun in waiting.
[tar.xz](https://drive.google.com/file/d/1-wcdy38WKJxOQIiQ9vorZhfde-2TTV1X/view?usp=sharing), 17MB. Probably need winrar or something
or
[zip](https://drive.google.com/file/d/1mI2Ee-FGuEjZUq7zPstSAc0pTT5q64C7/view?usp=sharing), 47MB. They're both the same after decompression
Hopefully that'll work until the fix is merged. Otherwise you'll have to wait maybe a couple days, and that can be a real drag sometimes.

**Comment by bunnybananza** [comment]
Hey, what do you know? It works, you're a legend! Everyone else here is legendary too. All this code stuff is way beyond my repertoire of knowledge, so I appreciate y'all making the magic happen somehow. Thank you everyone.
