### ISSUE TITLE
Character untethers to moving vehicle

### ISSUE THREAD

**Issue by DericHuynh** [CleverRaven/Cataclysm-DDA#47093]
# Describe the bug

My player was moving with the vehicle when a fish appears above him.
The vehicle moves into the fish and untethers the player from the vehicle.
The player is floating in the middle of the lake/ocean, I can [wait] and time passes. He doesn't fall into the lake.
When I try to move, it throws an error, after which the player starts drowning.
After which during the writing of this report, I try and teleport onto the canoe,
it throws another error saying that the player (Arceus is the player) is already there.
After which trying to continue on, the player starts drowning AGAIN, even though he's on the canoe.

# Steps To Reproduce

1. Load save
2. Spawn a longear sunfish above/adjacent to the player
3. press wait (timestep)
4. Repeat steps 2-3 until player is kicked off
5. Try to move, error occurs
6. Teleport onto boat, error occurs
7. Continue driving around, notice that the player is drowning.

# Expected behavior

Character stays on the vehicle.

# Screenshots

Video:
https://user-images.githubusercontent.com/54043695/106222837-8b507e00-619d-11eb-91e5-11c988894bc9.mp4

1. My character randomly stopped moving with the vehicle, whenever I press [wait] time continues on and the player is just floating there.
![Floating](https://user-images.githubusercontent.com/54043695/106213718-859d6d00-618a-11eb-8541-5bfc2f018da9.png)

2. When I try to move, I get this error. 
![error](https://user-images.githubusercontent.com/54043695/106213714-833b1300-618a-11eb-8e6b-8f1a25502475.png)

3. After the error, the player falls into the water and starts drowning.
![Sink](https://user-images.githubusercontent.com/54043695/106214438-03ae4380-618c-11eb-9f37-0ca42c1c0b8d.png)

4. I go into debug menu and teleport onto the canoe. It throws another error.
![Error2](https://user-images.githubusercontent.com/54043695/106215126-7c61cf80-618d-11eb-809a-a10f11ea69b1.png)

5. I continue on canoeing, but I notice my character is drowning, even though he is on the canoe, moving with it.
![Problem2](https://user-images.githubusercontent.com/54043695/106215255-c2b72e80-618d-11eb-9fdb-840edc0a5efd.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-9280-g9dde4db-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills]
]

# Additional context

Debug Log
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5891173/debug.log)

Save File
[Valier.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5891174/Valier.zip)

**Comment by DericHuynh** [comment]
I figured out how to reproduce it, and added a video showcasing the problem.

**Comment by PatrikLundell** [comment]
I wouldn't be surprised if a part of the problem is the same as the one where a companion tasked for work through a camp bulletin board remains tied to the vehicle it was in when tasked to perform the job after returning.

In both cases the affected character left a vehicle in a way the code didn't anticipate and didn't have the vehicle connection severed even though the code detected that it was incorrect (vehicle not found).

**Comment by PaulBlay** [comment]
Oh, I know another (much milder) repeatable bug that has the "passenger (whoever) is already there" debug message.
https://github.com/CleverRaven/Cataclysm-DDA/issues/34454

**Comment by GGgatherer** [comment]
Happened to me multiple times too (in January - can't tell exact build), always with floating craft. Couldn't repro though so didn't make a thread.

**Comment by OliveChukar** [comment]
The part of the issue that creates error messages seems like a separate thing from the drowning.  The drowning part looks like #46488.

**Comment by DericHuynh** [comment]
> 
> 
> The part of the issue that creates error messages seems like a separate thing from the drowning. The drowning part looks like #46488.

I think they might be different, it depends on whether or not teleporting updates the player, in terms of their reactions to the environment.

**Comment by DericHuynh** [comment]
> 
> 
> Happened to me multiple times too (in January - can't tell exact build), always with floating craft. Couldn't repro though so didn't make a thread.



> 
> 
> Happened to me multiple times too (in January - can't tell exact build), always with floating craft. Couldn't repro though so didn't make a thread.

Yeah, it's not so common to be easy to reproduce, but it's common enough to piss me off. Almost all of my wizard vacation runs were subject to this.

**Comment by Sirbab** [comment]
I think i found a reproduction of this not related to boats.  Though it may be more ramp shenanigans.
Drive a car while heavily overloaded (carrying a golem corpse for instance), and drive back and forth over a bridge ramp until you're knocked over while going over the ramp tile, this uncouples you from the vehicle as it teleports up the ramp.  I can provide a reproducible save of this, or make a separate issue if it's deemed unrelated.
