### ISSUE TITLE
Healthcare skill will not increase under any circumstance

### ISSUE THREAD

**Issue by BuddySmiles** [CleverRaven/Cataclysm-DDA#47096]
# Describe the bug
Healthcare is stuck at 0% regardless of anything I do, even skill books are bugged

I noticed it was at 0%, read Big Book of First Aid, and it produces a very large negative number.

# Steps To Reproduce
I have no idea, really.

# Expected behavior

My healthcare skill would increase :)

# Screenshots

https://i.imgur.com/VKZjbI9.jpg

# Versions and configuration

# Additional context

Not sure how to provide my save

> 
> 
> What happens if you debug edit your Healthcare skill to 1? Can you increase it by reading / practice after that or is it still bugged up?

I should've mentioned that this was the first thing I did. It has no effect as far as I could tell. I spammed bandages on limbs to see if it'd go up again, as well as reading the book again, same issue.

**Comment by BrettDong** [comment]
Which version are you playing?

**Comment by BrettDong** [comment]
Could you please attach a save file?

**Comment by BuddySmiles** [comment]
> 
> 
> Could you please attach a save file?

I'm new here, I'm not sure how

**Comment by BrettDong** [comment]
You can compress your save folder to a zip file and drag it to comment box here.

**Comment by BuddySmiles** [comment]
> 
> 
> Which version are you playing?

It says on title screen 0.E-9280-g9dde4db-dirty

**Comment by BuddySmiles** [comment]
> 
> 
> You can compress your save folder to a zip file and drag it to comment box here.


[Jackson Junction.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5891157/Jackson.Junction.zip)

**Comment by PaulBlay** [comment]
Looks like it may be related to https://github.com/CleverRaven/Cataclysm-DDA/issues/47047 ?

**Comment by BrettDong** [comment]
> Looks like it may be related to #47047 ?

I guess so.

**Comment by PaulBlay** [comment]
What happens if you debug edit your Healthcare skill to 1? Can you increase it by reading / practice after that or is it still bugged up?

**Comment by BrettDong** [comment]
`_exercise` in this save file is already overflowed. I am curious where could cause a overflow.

**Comment by PaulBlay** [comment]
[#TGVtbXk=.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5895759/TGVtbXk.zip)

Fixed file for @BuddySmiles Extract and place in your save file - overwrite old version. There were a few other bugged skills as well.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/healthcare-skill-will-not-progress-under-any-circumstance/25822/4

**Comment by BrettDong** [comment]
When was this save created? Was the character created in an older version of the game, or was it created new in the version you were playing?

**Comment by BuddySmiles** [comment]
I believe it was created on 11412, and its possible I updated the save, I'm not sure if I'm being truly honest. Usually I update saves I've just started because there's never been any issues. This is a first, lol.

Someone else in the thread I posted on Discourse with the same bug mentioned they edited the exercise values and it happened again-- which makes sense, but so far I have not noticed it happening again yet, but I've only checked a couple of times. Maybe if I catch it fast enough I'll know what I did to cause it.

**Comment by ferociousdork** [comment]
This happens because of an interaction between the focus loss from #47006 and periodic focus-draining effects (such as albinism's sunburn penalty). When `focus_pool` is < 1000, the `mod_focus( -1 )` from sunburn makes `focus_pool` go negative (mod_focus doesn't check if the end result is >= 0). Then the next `practice` call takes a sqrt of the negative focus_pool (character.cpp line 2365), resulting in a very large negative number (probably NaN cast to int). This very large negative number is then used to train the skill, causing the observed effects.
