### ISSUE TITLE
Can't clean gun when mending.

### ISSUE THREAD

**Issue by greatjailb8** [CleverRaven/Cataclysm-DDA#47095]
# I can't clean my guns and I only get other messages.

When I press m to mend I get a message saying "Toggle which fault?" and "1 Set: Blackpowder fouling", "2 Set: Spent casing in chamber", "3 Mend: Fouling".
# Steps To Reproduce

1. Shoot hundreds of rounds, or accurize some firearms then do the first thing.
2. Try to mend.
# Expected behavior

I expected to be able to clean my gun since that's what can be done irl.

# Screenshots

![Screenshot (14)](https://user-images.githubusercontent.com/74266779/106221713-fe082c00-6192-11eb-8a57-22a4c1569e46.png)
![Screenshot (15)](https://user-images.githubusercontent.com/74266779/106221727-03fe0d00-6193-11eb-8772-29119d7dea9e.png)
![Screenshot (16)](https://user-images.githubusercontent.com/74266779/106221741-09f3ee00-6193-11eb-8965-d360bd1163a4.png)

# Versions and configuration

OS: Windows 10
Game Version: 0.E-9233-ga149ceb-dirty
Graphics version: Tileset -> Ultica
Ingame language: English
Mods loaded: Dinomod
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5891092/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5891093/crash.log)
[Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5891099/Save.zip)

# Additional context

**Comment by XygenSS** [comment]
Pretty sure those are debug actions that you get from having debug hammerspace mutation.

**Comment by greatjailb8** [comment]
> Pretty sure those are debug actions that you get from having debug hammerspace mutation.

Ah I see. My mistake. Should I just delete this post?
