### ISSUE TITLE
Certain Firearms have no Sprites and/or sounds.

### ISSUE THREAD

**Issue by greatjailb8** [CleverRaven/Cataclysm-DDA#47097]
# Describe the bug
Some rifles have no sprites and/or sounds for several months to years now.

The AKM has sound but only some Armalite-variant rifle sprite.
The AK-47 has the same sprite as before but no firing or reloading sound.
The AR-10 has the same sprite as well but no firing or reloading sound.
The H&K G3 has a firing sound but an Armalite sprite instead of a G3 sprite.

# Steps To Reproduce

1. Use debug menu to spawn the rifles.
2. Try and fire, unload and reload magazine.

# Expected behavior

The rifles should look and sound like their real life counterparts.

# Screenshots

![Screenshot (17)](https://user-images.githubusercontent.com/74266779/106223182-ca7ad100-6195-11eb-98bf-441beabd4f68.png)
![Screenshot (18)](https://user-images.githubusercontent.com/74266779/106223195-cf3f8500-6195-11eb-9294-dee2d13508bd.png)
![Screenshot (19)](https://user-images.githubusercontent.com/74266779/106223206-d6669300-6195-11eb-97ed-7d41003e1c0b.png)
![Screenshot (20)](https://user-images.githubusercontent.com/74266779/106223215-d9fa1a00-6195-11eb-9129-f7b5a40755de.png)

# Versions and configuration

OS: Windows 10
Game Version: 0.E-9233-ga149ceb-dirty
Graphics version: Tileset -> Ultica
Ingame language: English
Mods loaded: Dinomod
# Additional context

**Comment by greatjailb8** [comment]
There's also no sprite for the player holding the M60 either.

**Comment by anothersimulacrum** [comment]
CC @int-ua @acepleiades

**Comment by int-ua** [comment]
Sprites missing in Ultica are tracked at https://github.com/I-am-Erk/CDDA-Tilesets/issues but there are a lot of missing sprites at the moment, I don't really see a point in creating separate issues for a lot of them. It's easy to contribute new sprites, BTW. In most cases for items you can just submit a PNG image of the appropriate size to Discord or to a folder withing a Pull Request on GitHub. Please ask the soundpack author if it's possible to add a distinct sound. Closing for now, will reopen on more replies that suggest reopening.
