### ISSUE TITLE
Performance drop after planting mini-nuke

### ISSUE THREAD

**Issue by Foxtrot-Uniform42** [CleverRaven/Cataclysm-DDA#47107]
# Describe the bug
When character places active mini-nuke, game starts to freeze.

# Steps To Reproduce
1. Have a mini-nuke in your inventory
2. (A)ctivate it
3. Drop it

# Expected behavior
No freezes between turns

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.E-9233-ga149ceb-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    Bionic Professions [package_bionic_professions],
    C.R.I.T Expansion Mod [crt_expansion],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    Fuji's Military Profession Pack [fuji_mpp],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills],
    No Zombie Revivification [No_Revive_zombies]
]

# Additional context
Can't reproduce it in a new world, will attach a save.
[Килер.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5894292/default.zip)

Notes: Don't know if it matters, that mini-nuke in my inventory was repaired with soldering iron.

**Comment by anothersimulacrum** [comment]
Looks like the NPCs get scared:
![image](https://user-images.githubusercontent.com/42699974/106300687-a8239a80-620b-11eb-9a15-7be8931047b6.png)

It took a little while before the performance drop hit, but it was significant once it came in.

**Comment by BrettDong** [comment]
Why `memset` is taking so much time?

**Comment by anothersimulacrum** [comment]
I am not sure.

**Comment by BrettDong** [comment]
<img width="988" alt="螢幕截圖 2021-01-29 下午1 13 05" src="https://user-images.githubusercontent.com/21075502/106311818-ba193380-6233-11eb-8496-aacbb0f01b63.png">
Mac Instruments profiling result: 
[mininuke.trace.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5895511/mininuke.trace.zip)
