### ISSUE TITLE
Animated sprites do not play while the game is still

### ISSUE THREAD

**Issue by acepleiades** [CleverRaven/Cataclysm-DDA#47104]
# Describe the bug

Animated tiles do not play when the game is still

# Steps To Reproduce

1. Be using a tileset that has animated tiles (such as BrownLikeBears);
2. Look at an animated sprite (in BrownLikeBears, computer consoles are animated. Spawn them through Debug Menu > Map > Map Editor > fu(r)niture);
3. The animated sprite will not cycle through animations while the game is still. If you move the mouse around, the animation cycles. There are some situations in which the animation will cycle, such as rain.

# Expected behavior

The animated sprite should be constantly cycling animations.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-9280-g9dde4db-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi]
]

# Additional context

**Comment by int-ua** [comment]
If this is ever changed please make it optional to animate them when nothing happens. I enjoy the lack of coil whine when nothing happens.

**Comment by Fris0uman** [comment]
So as it's probably the result of this https://github.com/CleverRaven/Cataclysm-DDA/pull/46655 I guess it might not be as much a bug as the previous constant animation was problematic.
Is there a way to get the animation back without the performance hit?

**Comment by wapcaplet** [comment]
This affects the sidebar minimap too - the location of hostile enemies is displayed as colored dots that pulsate, but the pulsating only occurs when passing time or moving the mouse, making monster locations difficult to see while waiting.

**Comment by BrettDong** [comment]
Should add redraw command somewhere if there is animated sprites or minimap

**Comment by actual-nh** [comment]
Ideally, redraw times should be adjustable when nothing else is happening - pulses lasting 10 seconds or something would, IMO, be fine for the minimap. That would include turning it off altogether, as int-ua (and others) prefer.

**Comment by Fris0uman** [comment]
https://user-images.githubusercontent.com/41293484/115950112-9fc0c000-a4d9-11eb-8751-13b09a87a3bf.mp4

#48415 has brought back both minimap and tileset animation

**Comment by actual-nh** [comment]
Should this issue be closed and another one opened for the CPU load issue? I don't use tiles, so it doesn't particularly matter to me personally, but it does to others - @int-ua? @souricelle? @ANickelN?

**Comment by BrettDong** [comment]
I think I didn't actually solve this issue but just hid it again.

**Comment by Fris0uman** [comment]
Maybe there's some improvement to pick up from BN implementation of iddle animation https://github.com/cataclysmbnteam/Cataclysm-BN/pull/510

**Comment by Night-Pryanik** [comment]
Animated sprites play normally on 0.F-12416, so I'm closing the issue.
