### ISSUE TITLE
Magiclysm: Wizard's vactation start fails to generate a location

### ISSUE THREAD

**Issue by Sirbab** [CleverRaven/Cataclysm-DDA#47102]
# Describe the bug
If one picks wizard vacation as a profession, the game fails to generate a valid location, and thus fails to make the character with the error provided below.

# Steps To Reproduce
Step 1: Make a world with DDA, No npc needs, and Magiclysm
Step 2: Make the a character with the profession wizard's vacation.
Step 3: attempt to finalize character, receive error.

# Expected behavior
I expect to not get a error when generating a character with a profession repeatedly.  As for why, uh, pretty sure this is non-ideal behavior for the mod.

# Screenshots

![image](https://user-images.githubusercontent.com/1490991/106231882-b26c7700-61c0-11eb-8e46-d0d48fdb061f.png)
# Versions and configuration
 - OS: Windows 10 64 bit
 - Game Version: 0.E-9182-g85a23ed-dirty
 - Graphics version: Tiles
 - Ingame language: English
- I'm afraid i cannot generate a game report as i am unable to enter the game.
 - Mods Loaded: DDA, No NPC Needs, Magiclysm

# Additional context

[Ruralia_copy_copy_copy_copy_copy.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5891630/Ruralia_copy_copy_copy_copy_copy.zip)

**Comment by actual-nh** [comment]
This may be fixed by #47071, which was just merged.

**Comment by Venera3** [comment]
I could not reproduce it on Build 11414 (0.E-9280-g9dde4db-dirty), either with the save provided or with a default world.

**Comment by Sirbab** [comment]
After updating my game version, i was able to generate a world successfully.  Closing issue, thank you for helping looking into this.
