### ISSUE TITLE
Chitin Armor uses missing Chitinworking proficiency

### ISSUE THREAD

**Issue by morthein** [CleverRaven/Cataclysm-DDA#47110]
# Describe the bug

I've made both the Chitin arms and now the Chitin gauntlets and neither one gave me any progress towards Chitinworking proficiency.

# Steps To Reproduce

1. Make a Chitin armor item (I choose both the arms and gloves)
2. View your proficiencies and note there no progress towards Chitinworking

# Expected behavior

Like leatherworking, there may be different tiers, and Chitinworking maybe hidden under one of those? But, it's not quite clear and makes mass producing chitin armor for a gang almost impossible since it seems to never give any skill in it.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-9285-g0ec6948-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Alternative Map Key [alt_map_key],
    Cataclysm++ [Cata++],
    Crazy Cataclysm [crazy_cataclysm],
    No Rail Stations [No_Rail_Stations],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Cataclysm++ - UndeadPeople Tileset [Cata++UDP],
    Crazy Cataclysm - UndeadPeople Tileset [CrazyCataclysmUDP],
    Graphical Overmap [Graphical_Overmap],
    MSX Black Military Cars [UDP_BlackMilitaryCars],
    No Fungal Monsters [No_Fungi],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

**Comment by anothersimulacrum** [comment]
The red means it has a prerequisite proficiency (principles of leatherworking) that you must learn before learning it.
This could certainly use clarification.
![image](https://user-images.githubusercontent.com/42699974/106310257-1ec69500-6218-11eb-98f7-bb6f0e2b24c8.png)

**Comment by LaVeyanFiend** [comment]
> The red means it has a prerequisite proficiency (principles of leatherworking) that you must learn before learning it.
> This could certainly use clarification.
> ![image](https://user-images.githubusercontent.com/42699974/106310257-1ec69500-6218-11eb-98f7-bb6f0e2b24c8.png)

It requires the second level of Leatherworking, according to the json. It probably wasn't updated when Principles of Leatherworking was introduced.

**Comment by morthein** [comment]
I suspected chitinworking was hidden somewhere, but i guess i've never not had the leatherworking maxed by the time I made chitin, but this time I jumped into it and noticed it just wasn't appearing, but looking back at my game what you say is correct, I have the 'principles of' maxed, not the 2nd tier 'leatherworking'.

**Comment by EvgenijM86** [comment]
It is stupid that you cannot learn the chittinworking proficiency by just crafting chitin gear, because most of the chitin gear does not train 2nd level of leatherworking proficiency.

**Comment by eltank** [comment]
This issue was fixed by #47158, which made chitinworking proficency depend on "principles of leatherworking". Crafting chitin gear now trains principles of leatherworking first if you don't have it, then trains chitinworking (though you really should train p.o.l. by itself before attempting chitin crafting if you don't want to waste a lot of time and material).

@actual-nh I propose closing this issue.
