### ISSUE TITLE
Allow ordering things across level

### ISSUE THREAD

**Issue by linonetwo** [CleverRaven/Cataclysm-DDA#47119]
# Is your feature request related to a problem? Please describe.

As described in https://github.com/CleverRaven/Cataclysm-DDA/discussions/47084

I hope I can "O" things into second floor of the building, and If I can O from 1th to 4th floor that would be great.

# Describe the solution you'd like
Allow area list to get areas in vertical direction.

# Describe alternatives you've considered
Didn't read much about C++, maybe someone can point out?

# Additional context
Nowadays, multiple floor buildings are common, this feature will make it easier to live in tall house.

**Comment by BrettDong** [comment]
Loot menu is at https://github.com/CleverRaven/Cataclysm-DDA/blob/0ec694873a12d05d92ebbf8a45da0876cb874cfe/src/handle_action.cpp#L1113

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
