### ISSUE TITLE
Test Files Fail to Build

### ISSUE THREAD

**Issue by grawprog** [CleverRaven/Cataclysm-DDA#47118]
# Describe the bug

Test files fail to build both during initial build and direct build.

# Screenshots

Error and previous line on initial build:

../cataclysm.a -ffast-math -Og -Werror -Wall -Wextra -Wformat-signedness -Wlogical-op -Wmissing-declarations -Wmissing-noreturn -Wnon-virtual-dtor -Wold-style-cast -Woverloaded-virtual -Wpedantic -Wsuggest-override -Wunused-macros -Wzero-as-null-pointer-constant -Wno-unknown-warning-option -Wredundant-decls -g -fsigned-char -std=c++14 -MMD -MP -I/usr/include/SDL2 -D_REENTRANT -I../src -Wno-unused-variable -Wno-sign-compare -Wno-unknown-pragmas -Wno-parentheses -MMD -MP -Wall -Wextra -Wno-unused-macros -lSDL2 -lSDL2_ttf -lSDL2_image -rdynamic -lpthread -L.
make[1]: Leaving directory '/home/graw/Data/Games/cdda-E.3/cddagraw/tests'

Error trying to build test files directly:

./tests/catch/catch.hpp:14173:56: required from here
/usr/include/c++/7/ext/new_allocator.h:136:4: error: invalid use of incomplete type ‘class Catch::TestCase’

{ ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../tests/test_main.cpp:6:0:
../tests/catch/catch.hpp:12224:11: note: forward declaration of ‘class Catch::TestCase’
class TestCase;
^~~~~~~~

# Versions and configuration

 - OS: KDE Neon (Ubuntu 18.04)
Cataclysm DDA version 0.E-9307-g1ccae0270e
[main] C locale set to en_CA.UTF-8
 [main] C++ locale set to en_CA.UTF-8
SDL version used during compile is 2.0.8
SDL version used during linking and in runtime is 2.0.8
opendir [lang/mo/] failed with "No such file or directory".
Number of render drivers on your system: 3
Render driver: 0/opengl
Render driver: 1/opengles2
Render driver: 2/software
[options] C locale set to en_CA.UTF-8
[options] C++ locale set to en_CA.UTF-8
Active renderer: 2/software
USE_COLOR_MODULATED_TEXTURES is set to 0

clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
Target: x86_64-pc-linux-gnu
Thread model: posix

**Comment by actual-nh** [comment]
Compiler and version?

**Comment by grawprog** [comment]
> Compiler and version?

Updated initial comment with compiler.

**Comment by BrettDong** [comment]
Could you post the full log of initial build?

**Comment by grawprog** [comment]
> Could you post the full log of initial build?

Yeah I can. I'm not sure where to find this though.

**Comment by anothersimulacrum** [comment]
Run `make clean` and `ccache --clear`, then you can try re-compiling and capture the log then.

**Comment by grawprog** [comment]
Ok. So just the log from the terminal as it builds?

**Comment by anothersimulacrum** [comment]
Yep.

**Comment by BrettDong** [comment]
`class Catch::TestCase` is defined in line 4808 so I have no idea why compiler thinks it's an incomplete type.

**Comment by grawprog** [comment]
Build log from a clean rebuild after running make --clean and ccache --clear. Finished with 1 again on tests directory.

[build_log.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/5897486/build_log.txt)

**Comment by BrettDong** [comment]
I don't see failing in the log. `tests/cata_test` should be there.

**Comment by grawprog** [comment]
It's there now. Sorry...i'm not sure. It took longer to build this time after the make clean and ccache clear but the test_cata exists now. I don't know why it wasn't there before.
