### ISSUE TITLE
Segmentation fault crash while reading a book

### ISSUE THREAD

**Issue by Apxangel1** [CleverRaven/Cataclysm-DDA#47126]
# Describe the bug

Reading any book, or disassembling signal receiver from tile on the right causes segmentation fault, game crash.
In some other cases before, moving, waiting or crafting the "signal receiver"
# Steps To Reproduce

1. Load given world and character
2. Try to read any book available or disassemble signal receiver

# Expected behavior

Reading a book until finished or interrupted.

# Screenshots

# Versions and configuration

 - OS: Windows 7
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-3 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [

    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5898493/config.zip)
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5898494/save.zip)

Might be similar to #46397 (might be not)
Character ate nothing but junk food, fruits ect. found in lab, therefore it isn't supposed to be affected by "toxins" from bad meat or something.

**Comment by BrettDong** [comment]
I didn't reproduce the crash on experimental version. (b8b74c3d869383dcd33c5ea3cb4a3160b97e5d7c)

**Comment by PaulBlay** [comment]
So, it's time to say good by to 0.E-3 and all its bugs, and say hello to latest experimental version and all its bugs.

I also tested it and didn't get a crash.

Game Version: 0.E-9155-g1319073-dirty [64-bit]

**Comment by Apxangel1** [comment]
**After updating to "(11417 a day ago) - latest available build" original crash error was not reproduce-able.**
But upon loading character i got this error 
![image](https://user-images.githubusercontent.com/32877852/106367840-428bf700-634e-11eb-89d0-70bc50b58a3d.png)
for what i assume, all "same kind"containers on the map.
guess im playing experimental now :D
