### ISSUE TITLE
Bleed acid zeds should produce sulfuric acid instead of tainted blood. 

### ISSUE THREAD

**Issue by ynemo** [CleverRaven/Cataclysm-DDA#47124]
I butcher bleed "bilious soldier zombie", and harvested 22L Tainted Blood. But when I draw blood from the same zombie using blood draw kit I harvest sulfuric acid. I was hoping butchering bleed function was added to help players to avoid making macros to harvest liquids from dead bodies.
Also, weight of bled corpses do not change at all, and i still can use blood draw kit on bled corpse. 

# Expected behavior

I suppose acid zeds should produce acid when i bleed them.

**Comment by PaulBlay** [comment]
> Also, weight of bled corpses do not change at all, and i still can use blood draw kit on bled corpse.

The blood draw kit only takes a tiny amount of blood so that is not unreasonable.

**Comment by ynemo** [comment]
same  with acidic ants

**Comment by Salty-Panda** [comment]
Not sure if those acidic zombies have acid instead of blood or rather some sort of acidic pus or blisters. Or just sack of acid in the body.
Same with ants.
Instead of bleeding maybe add body_part type acid sacks, that can be crafted into acid/sulfuric acid?

Also obtaining acid from zombies in meaningful amounts would clash with one of the basic rules of the game:
 - zombies are so plentiful, their corpses shouldn't provide anything too good.
 For comparison, a car battery provides two? units of sulfuric acid.
 
 Maybe it would be more reasonable to have zombies contain some `weak acid`?

**Comment by actual-nh** [comment]
Three thoughts:

- I'm not sure why it'd be sulfuric vs other acids (hydrochloric makes more sense to me, being already in the body in significant quantities).
- The blood draw kit and butchery bleeding should be consistent with each other overall, although I can see the argument that the former might draw a more pure version than the latter (which could be mixed with other body fluids). In other words, bleed out a liquid from which acid can be purified. (BTW, I trust the blood draw kit only works once to draw acidic blood?)
- Are acid zombies so common, especially in comparison to car batteries?

**Comment by ynemo** [comment]
> * (BTW, I trust the blood draw kit only works once to draw acidic blood?)

i put it on macro and harvested 20L from single body.
Only drawback, need to repair blood draw kit sometimes, i made another macro for this.

**Comment by actual-nh** [comment]
> > * (BTW, I trust the blood draw kit only works once to draw acidic blood?)
> 
> i put it on macro and harvested 20L from single body.
> Only drawback, need to repair blood draw kit sometimes, i made another macro for this.

Umm... if it's drawing sulfuric acid concentrated enough to be useful off the bat, even assuming a glass syringe (much less common in healthcare settings than plastic), the plunger and/or connection to the needle - both of which, outside of chemistry labs, will be (cheap) plastic - is/are definitely going to be leaking after you get .1 L, and definitely not functional after drawing .25 L. They're designed to handle biohazards (by being disposable!), not chemical hazards.

**Comment by PaulBlay** [comment]
actual-nh does have a good point. The blood drawing kit does get damaged (relatively) quickly, but it is easy to repair. I don't think there is any realistic way to repair a syringe damaged by concentrated acid to the point of leaking.

On the subject of collecting acid blood when butchering, I think a more vital question is how do you butcher a corpse full of concentrated acid without risking severe damage to your butchering tool and yourself? Some of these corpses fire acid half a dozen tiles when you shoot holes in them but you can casually hack them apart at point blank range with your butchers knife without ending covered from head to toe in acid blood.

**Comment by ynemo** [comment]
> On the subject of collecting acid blood when butchering, I think a more vital question is how do you butcher a corpse full of concentrated acid without risking severe damage to your butchering tool and yourself? Some of these corpses fire acid half a dozen tiles when you shoot holes in them but you can casually hack them apart at point blank range with your butchers knife without ending covered from head to toe in acid blood.

there is butchering action named "bleed", it is currently implemented in game. I suppose i tie legs of zed to a rope and hang out it on a butchering rack or a tree. Then "blood" or "acid" is collected to the container under the corpse, maybe i need a funnel, maybe not.

**Comment by PaulBlay** [comment]
> there is butchering action named "bleed", it is currently implemented in game.

Currently implemented, or currently unimplemented?

**Comment by ynemo** [comment]
> Currently implemented, or currently unimplemented?
implemented, it produces blood. I wish it produces some kind of acid.

**Comment by actual-nh** [comment]
> actual-nh does have a good point. The blood drawing kit does get damaged (relatively) quickly, but it is easy to repair. I don't think there is any realistic way to repair a syringe damaged by concentrated acid to the point of leaking.

If you're very lucky and it's glass, replace the needle (including the plastic bit by which it mounts to the syringe) and plunger (and hope they haven't left too much crud that you haven't been able to clean out). I'm not sure whether that should be considered repair or disassemble for usable part to use in a new syringe.

> On the subject of collecting acid blood when butchering, I think a more vital question is how do you butcher a corpse full of concentrated acid without risking severe damage to your butchering tool and yourself? Some of these corpses fire acid half a dozen tiles when you shoot holes in them but you can casually hack them apart at point blank range with your butchers knife without ending covered from head to toe in acid blood.

Good point! It may admittedly only be pressurized while the zombie is still functional, but chopping into them should still result in potentially-damaging blood all over the place.

**Comment by PaulBlay** [comment]
Going back to what @Salty-Panda said

> zombies are so plentiful, their corpses shouldn't provide anything too good.

But also bearing in mind another guideline

> Realism trumps gameplay

You could combine the two for this case by making it possible to fill a 3L glass jar with zombie blood acid, but said zombie blood acid should be full of disgusting and weird zombie goop instead of being pure hydrochloric or sulphuric acid. To the point that Goo only knows what would happen if you tried to make a car battery out of it. Having zombie acid blood being conveniently usable 'as is' would be a tad unlikely as they aren't evolving for our convenience. Quite the opposite.

**Comment by SariusSkelrets** [comment]
It could be some kind of acidic blood (tainted acid) that would need processing, reducing the total amount.

 The acidic zombie’s description alludes to «fluid in its veins» so the acid is mixed with blood and maybe other things so it wouldn’t be usable right now and be reduced to appropriate amounts after the processing

**Comment by PabloJSV** [comment]
There are different kinds of acids that could be compatible with the change @ynemo is proposing. It could be an interesting addition as a rare drop or making it extractable using a syringe.

**Comment by actual-nh** [comment]
Will work on after 0.F is out, I think.

**Comment by anothersimulacrum** [comment]
@actual-nh Do you want me to assign you to this? I can.

**Comment by actual-nh** [comment]
> @actual-nh Do you want me to assign you to this? I can.

@anothersimulacrum: Good thought; please do.

**Comment by actual-nh** [comment]
Also to-fix (from #48971):
> Also, there should be a limit units within a corpse which allowed blood draw kit to draw. I've draw a few gallon blood from this poor zombie... More, a corpse had blood drawn should lose its weight. Not sure about butchery>skinning did the similar thing but it should also be like this.

**Comment by robotic-gamer** [comment]
shouldn't acid zombies give hydrochloric acid, not sulfuric acid since that is what is in stomach acid and is also a stronger acid then sulfuric acid?

**Comment by actual-nh** [comment]
I had the same question; now that I'm on the Discord, I'll see about checking on that.

**Comment by actual-nh** [comment]
Bleeding acid zombies almost certainly came well after their creation - and they're specified as yellow (or the fluid as being yellow). More reasonable would be some mix of acids + tainted blood that you'd need to purify, compensated for by being able to actually bleed them... provided you avoid getting splashed!

**Comment by ynemo** [comment]
may i close this Issue? Looks like it is resolved

**Comment by Night-Pryanik** [comment]
Closing as resolved.
