### ISSUE TITLE
Error Report when trying to boil water from vehicle tank using kitchen unit

### ISSUE THREAD

**Issue by leonhart18** [CleverRaven/Cataclysm-DDA#47128]
Error show up when batch boiling 50 units of water from a 60l tank in my vehicle using the installed rv kitchen unit.

Trying to boil my 60l of dirty water in a tank on my rv using the kitchen unit installed on the vehivle to fill an empty 60l tank with clean water connected to a faucet on the same tile as my kitchen unit. 

DEBUG : ERROR: item_contents::only_item called with 10 items contained

FUNCTION : const item& item_contents::only_item() const
FILE : src/item_contents.cpp
LINE : 980

# Steps To Reproduce

have 2 60l tank on vehicle, one empty, one with dirty water. open craft menu, hit batch, select clean water x50, the error also seems to occur with batch crafting.

I expected clean water to craft with no errors? it works and the water boils properly but its relatively time consuming to sit through multiple error messages when trying to fill a few tanks by boiling over and over.

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-9285-g0ec6948-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Stats Through Skills [StatsThroughSkills],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    SpeedyDex [speedydex],
    Clean CBMs [clean_cbm],
    Manual Bionic Installation [manualbionicinstall]
]

[Outdoor Lyfe.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5898781/Outdoor.Lyfe.zip)

**Comment by PaulBlay** [comment]
Is this the error? Because you didn't include it in your report.

 DEBUG    : ERROR: item_contents::only_item called with 10 items contained

 FUNCTION : const item& item_contents::only_item() const
 FILE     : src/item_contents.cpp
 LINE     : 980

So, yeah, I did get an error message but the actual water boiling to make clean water worked. It looks like you have mods that I don't, so I got some extra error messages when I loaded the game.

- OS: Windows x64 8.1
- Game Version: 0.E-9155-g1319073-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Stats Through Skills [StatsThroughSkills],
    No name () [],
    SpeedyDex [speedydex],
    No name () [],
    No name () []
]

**Comment by leonhart18** [comment]
your right, im my efforts to write all this up i forgot to paste the error report. apologies, i pasted it in an edit to correct.

**Comment by int-ua** [comment]
#41888
#42867

**Comment by misterprimus** [comment]
Now getting this when trying to craft clean water using purifier.
```
DEBUG    : ERROR: item_contents::only_item called with 0 items contained
 FUNCTION : const item& item_contents::only_item() const
 FILE     : src/item_contents.cpp
 LINE     : 1400
 VERSION  : 842769c
```
[Framingham.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9825578/Framingham.zip)
