### ISSUE TITLE
Cordless drill does not use charges when installing 60L tank in vehicle

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#47122]
# Describe the bug

Installing a tank in a vehicle requires a drill, however if you use an electric drill it does not use any charges.

# Steps To Reproduce

1. Load save ( [Narnia.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5897804/Narnia.zip) ) (or spawn 60L tank, vehicle, and other required tools)
2. Check charge level in cordless drill (it's 1200 for save)
2. 'e'xamine vehicle
3. Install 60L tank
4. Confirm charge level is unchanged.

# Expected behavior

If you're required to have drill you can presume that it will be used, and if you use an electric drill it should lose some charge.

# Screenshots

# Versions and configuration

- OS: Windows x64 8.1
- Game Version: 0.E-9155-g1319073-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

# Additional context

Note that if you unload the battery from the cordless drill you can still install the 60L tank with it.

**Comment by OliveChukar** [comment]
Tested in version 0.E-9285-g0ec6948-dirty with Dark Days Ahead [dda] only.  Used a cordless drill to install fuel tanks 2L, 10L, 20L, 60L, none consumed any battery charge. Tested all types of medium battery with same result. Tested using the drill to put a tap into a maple tree and this also did not use any charge. 

Tested crafting a 460 Rowland casing and it did use charge from the drill.
