### ISSUE TITLE
Apparent infinite time bug while repairing vehicles while missing glasses

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#47138]
# Describe the bug

When attempting to repair my car when I don't have access to an item with `glare protection 2`, the game appears to enter an infinite loop where it attempts to repair an extra-light frame, fails due to not meeting the requirements (not having the glasses), but keeps trying and failing and failing....until manually interrupted.

# Steps To Reproduce

1. Load attached save
2. Initiate vehicle repair through the `O` zone interaction menu.
3. Wait.

# Expected behavior

I expected the game to simply fail out entirely.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 20H2 (build 19042.746)
- Game Version: 0.E-9186-gd2f3109-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded:
    - Dark Days Ahead [dda],
    - C.R.I.T Expansion Mod [crt_expansion],
    - No Fungal Monsters [No_Fungi],
    - Disable NPC Needs [no_npc_food],
    - Alternative Map Key [alt_map_key],
    - SpeedyDex [speedydex],
    - Stats Through Kills [stats_through_kills],
    - Stats Through Skills [StatsThroughSkills],
    - No Rail Stations [No_Rail_Stations]

# Additional context

The glasses are available in the cargo space on the racked motorbike.

[Woodcock.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5899410/Woodcock.zip)

**Comment by PatrikLundell** [comment]
A guess is that the initial check finds the glasses in the cargo space and thus proceeds, but a later check doesn't consider that location a valid tool source (like the bug where charges for an oxytorch was found when starting the job, but not when it came time to deduct them after the job).

**Comment by ToxiClay** [comment]
As an additional issue, I noted that once I picked up the glasses, the Repair command would eventually start failing with "The required items are not available. x13", but manually invoking the repair interface proceeded just fine; the materials are in fact available.

**Comment by irwiss** [comment]
Can't reproduce on fd463d4
