### ISSUE TITLE
Harvesting spider webs for thread

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#47139]
# Is your feature request related to a problem? Please describe.

I run out of of thread quite often, and while you can always disassemble rags that is a rather time consuming process for not much thread. CDDA is full of areas with huge spider webs, and that seems like a ready source of silk.

# Describe the solution you'd like

'e'xamine a tile with spiderwebs on it and the right tools to harvest thread. Technically this is silk thread that is really very strong and stretchy.

# Describe alternatives you've considered

Leave as is.

# Additional context

Making (ugly) silk thread from spider webs is a real thing that real people do. Imagine how much easier it would be to get a sensible amount if the spider is the size of a large dog, or a horse.
https://www.instructables.com/How-to-make-Spider-Silk-Thread/

**Comment by actual-nh** [comment]
IIRC, in a web there are two types of silk in use: structural and sticky. The structural thread is stronger but less sticky. (Ping: @Venera3?)

**Comment by PaulBlay** [comment]
> IIRC, in a web there are two types of silk in use: structural and sticky. 

That's quite correct. Although, I imagine that you could make the sticky silk non-sticky either through chemical treatment or talcum powder.

**Comment by PaulBlay** [comment]
Actually, 'macrosized' glue drops could conceivably be collected as an alternative to superglue. Spider silk glue is (depending on variety) water proof, super strong and long lasting. Getting it into a suitable container might be hard, though. Perhaps you could tease it off with needles.

**Comment by Venera3** [comment]
I can't say I haven't thought about it, for whenever I get to their lairs proper. I think smashing webs could yield the structural strands as  a short rope equivalent, and a slow, fiddly examine action with precision cutting could be used to harvest the sticky strands proper (I'm assuming here that they are about fishing line-thick, so that enough can hold a moose but still concievably be invisible). That could yield a sticky fuzzball with a rot timer standing in for the glue solidifying, that you could refine into either the glue component or into thread.

**Comment by actual-nh** [comment]
The structural strands, or at least some of them, may also need to be pretty small to avoid being visible.

**Comment by PaulBlay** [comment]
Spider glue doesn't solidify in humid conditions. It remains sticky for a very long time. Inside houses they end up non-sticky just because they get covered in dust (and/or dry out). In game it's might be easier to go direct to 'duct tape' than separating glue out. The tricky bit would be finding something that doesn't (much) stick to spider glue for the non-sticky side of the tape. I have no idea how you'd do that - although I also have no idea how 'super glue + rag = duct tape'.

**Comment by actual-nh** [comment]
I need to look up how spiders avoid sticking to their own webs. I'm pretty sure it isn't just not stepping on the sticky strands (but I could be wrong).

**Comment by PaulBlay** [comment]
Spoiler alert: Nobody knows, although they suspect it's just not stepping on the sticky threads.

**Comment by Sirbab** [comment]
Could the abdomen be harvested for the precursor glands that create the silk?

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
