### ISSUE TITLE
Uncanny Dodge Trait Stamina Cost Far Too High

### ISSUE THREAD

**Issue by b3brodie** [CleverRaven/Cataclysm-DDA#47133]
# Describe the bug

The biotek attunement from Magiclysm grants the uncanny dodge trait.  The primary issues with this trait is that it has an incredibly large stamina cost in comparison with the cbm cost and it cannot be turned off. 
 
According to character.cpp uncanny dodge either costs 2400 stamina or 75 kj if used separately.  With the default stamina being 10,000 and max bionic power being about 2,000 kj (while not given by default, this is far easier to obtain compared to the biotek attunement and most characters will reach this if they survive long enough), this means that characters can uncanny dodge 4 times with the trait or 26 times with the cbm, discounting resource regeneration.  Taking into account resource regeneration makes these numbers even further apart, as in my experience bionic power can proportionately recharge quicker in contrast with stamina.

Even beyond the amount of times uncanny dodge can trigger, stamina is a more important resource compared to bionic power at the levels that are used by this ability, especially for characters in melee.  With just 4 uncanny dodges the character's attack speed and ability to run away are crippled along with every other downside of having almost 0% stamina.  In my experience, the uncanny dodge trait is an incredible nerf for melee characters rather than being beneficial.

Furthermore, unlike the CBM version the trait / mutation cannot be turned off.  Even with a cost rebalance this prevents it from being able to be strategically turned on / off for difficult enemies that it would be useful for rather than being wasted on basic zombies.

# Steps To Reproduce

1. Obtain uncanny dodge trait (I obtained via the Magiclysm Biotek attunement but it may be available elsewhere)
2. Stand next to enemy
3. Uncanny dodge consumes about 1/4 of stamina 

# Expected behavior

While the cbm and trait do not have to be exactly equal in utility / power, at minimum the trait should be within a general range of the cbm and possess the ability to turn it on and off.

# Versions and configuration

OS: Windows 10
Game Version: 0.E-9229-g6902525-dirty
Graphics: Tiles
Language- English
Mods loaded: Magiclysm

# Additional context

**Comment by anothersimulacrum** [comment]
CC: @KorGgenT

**Comment by KorGgenT** [comment]
you've convinced me. should be as simple as just changing the number to, say, 300.
