### ISSUE TITLE
I can attempt to put a bone into an EMP cannon.

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#47136]
# Describe the bug

My survivor believes she can try to put a bone in an EMP cannon. The game disagrees.

# Steps To Reproduce

1. Load attached save.
2. `g`et the tainted bones from 1W.
3. ????

# Expected behavior

I suppose I expected her to *not* try to bone the cannon.

# Screenshots

```
 DEBUG    : tried to put an item (bone_tainted, amount 1) in a container (emp_gun) that cannot contain it

 FUNCTION : int item::fill_with(const item&, int, bool, bool)
 FILE     : src/item.cpp
 LINE     : 8923
```

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 20H2 (build 19042.746)
- Game Version: 0.E-9186-gd2f3109-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded:
    - Dark Days Ahead [dda],
    - C.R.I.T Expansion Mod [crt_expansion],
    - No Fungal Monsters [No_Fungi],
    - Disable NPC Needs [no_npc_food],
    - Alternative Map Key [alt_map_key],
    - SpeedyDex [speedydex],
    - Stats Through Kills [stats_through_kills],
    - Stats Through Skills [StatsThroughSkills],
    - No Rail Stations [No_Rail_Stations]

# Additional context

[Woodcock.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5899315/Woodcock.zip)

**Comment by PaulBlay** [comment]
While you're looking at EMP cannon, note that you can attempt to 'r'eload EMP cannon, laser rifle and other UPS powered guns. When you do so you get the message

You don't have any NULL to reload your [GUN]
https://github.com/CleverRaven/Cataclysm-DDA/issues/46186

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-11086.
