### ISSUE TITLE
Missing subway signs translation

### ISSUE THREAD

**Issue by akirashirosawa** [CleverRaven/Cataclysm-DDA#47142]
# Describe the bug
This JSON string are not extracted to translate: `"signs": { "M": { "signage": "Subway Map: <city> stop" } }`, from file `data/json/mapgen_palettes/subway.json`. In script `lang/extract_json_strings.py`, type `palette` included to `ignorable`.
Therefore, the two signs related to the palettes `subway` and `subway_underground` not extracted to translate.
# Steps To Reproduce
Switch the language from English to another and visit a metro.
# Expected behavior
The message on the sign must be translated.
# Screenshots
<img width="380" alt="1" src="https://user-images.githubusercontent.com/38557723/106382812-1c5c6a80-63d3-11eb-9411-c54766be260d.png">

# Versions and configuration
Current Master a17d18f13628f741d149f264257f02b01e0e13c9
# Additional context
I don't know how best to solve this issue. Don't want to exclude `palette` from `ignorable` and  handle all objects of this type, because of two strings (actually one, since they are the same). Is it possible to somehow get the text of signs from the `palette` and add it to the `mapgen` object (the strings from which is already being extracted)? Or it could be to handle `subway.json` file in an exceptional order, if provided by the script.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/text-not-available-for-translation/10779/32

**Comment by anothersimulacrum** [comment]
I don't think it's a very big deal to handle all palette type objects, because this is a bit of a hard to notice error, and that future-proofs us.
However, if we want to avoid that, we can probably stick the text of this sign in a snippet, and just reference that snippet for the sign text.
