### ISSUE TITLE
Friendly baby monsters disappear when they grow up

### ISSUE THREAD

**Issue by LyleSY** [CleverRaven/Cataclysm-DDA#47145]
# Describe the bug

DinoMod includes tameable baby dinos that cannot be tamed when they are adults. The intention is that you can therefore have huge and dangerous dino pets, in the same way that people have pet elephants and tigers today if you put in the time and effort. However, Discord user Elizzyble reports that the baby dinos just disappear instead of growing up into adult dinos with the "friendly" tag, I'm betting because they lack the same "catfood" or whatever tag to enable it.

# Steps To Reproduce

1. Debug spawn a velociraptor egg
2. Debug time ahead a week or two. 
3. Give the baby raptor catfood.
4. Debug time ahead a month.
5. Bye bye pet raptor

# Expected behavior

Adult spawns with the "friendly" tag

# Versions and configuration

Mods loaded: DinoMod

# Additional context

Second test from same player here https://discord.com/channels/598523535169945603/598523535169945607/783899516863774720 Can't find the first report

**Comment by actual-nh** [comment]
@Ramza13 - would #42786 be able to help with this?

**Comment by Ramza13** [comment]
At present nope, there don't exist the right combination of effects and conditions to achieve that.  It might be possible to add them without great effort but it feels like overkill.  I'm not knowledgeable about tamed monsters but would think you'd just need to find why this works for some animals and not others and fix the gap.  

Having said that monsters do store variables so it might be possible to add a more sophisticated version of this where you have to increase how much they like you over time before taming them.  That would still require adding some new dialog effect/conditions but would be a task better suited to effect_on_conditions.  And a way to possibly use the having a conversation with monster feature it includes.

**Comment by LyleSY** [comment]
@Venera3 did some testing to see if this issue happens with the new Dermatik system introduced in #46448 and no, those work as expected. Those have the LARVA tag, not the cattle fodder or bird seed tags, so may be handled differently

**Comment by actual-nh** [comment]
I've looked over the code, and I can't see how LARVA would make a difference. I suspect it's that their maturation is hardcoded in monattack.cpp as `mattack::dermatik_growth`, which uses `poly` - I suspect that (without being told to do otherwise) preserves relationships and/or the tameable-via-food flag.

**Comment by Venera3** [comment]
According to the docs, LARVA only handles if they gib or not, but MONSTER.md can be a bit obtuse. The other difference I can think of is that they get their friendliness set wt their spawn in the hardcoded effect, and I don't know how dogfood etc works under the hood.

**Comment by actual-nh** [comment]
BTW, if they don't have an applicable *FOOD tag, how does one make them friendly?

**Comment by Venera3** [comment]
On emergence out of you they have a flat 1-in-3 chance of popping out friendly. It's a bit weird, but it works for now (I have an alternative in mind for whenever mutations catch my fancy).

**Comment by actual-nh** [comment]
I think I just spotted a bug in the dermatik attack code:
```
    if( !foe->has_trait( trait_PARAIMMUNE ) || !foe->has_trait( trait_ACIDBLOOD ) ) {
        foe->add_effect( effect_dermatik, 1_turns, targeted, true );
        get_event_bus().send<event_type::dermatik_eggs_injected>( foe->getID() );
    }
```
Shouldn't that be a `&&`, not a `||`?

**Comment by actual-nh** [comment]
A couple of things:

- @Venera3: Should I put in a PR for that? Can do if you can do the testing.
- Chicks tamed with birdfood growing up into birds seem to be still tame, including ones without the flag as adults - see #47974.

**Comment by Venera3** [comment]
>     Should I put in a PR for that? Can do if you can do the testing.

Thanks, that would be nice! This week will be a bit better, devtime-wise.

**Comment by actual-nh** [comment]
> > ```
> > Should I put in a PR for that? Can do if you can do the testing.
> > ```
> 
> Thanks, that would be nice! This week will be a bit better, devtime-wise.

Assuming this weekend is included in "this week", I think I can manage it.

**Comment by LyleSY** [comment]
Working on something else I noticed that one of the newer dinos is missing a juvenile version. That would definitely cause this issue. I'll fix once we're out of content freeze

**Comment by LyleSY** [comment]
I've been working on more testing on this and now I see different behavior. Now I just have friendly baby hatchlings forever, even after debugging a couple of years to pass.

**Comment by actual-nh** [comment]
Are the juveniles of the species in question tameable with food?

**Comment by LyleSY** [comment]
Just replicated this with a baby chick with DinoMod disabled. Yes, many are but not all. I couldn't get any to grow up.

**Comment by LyleSY** [comment]
And replicated with a baby chick without the FRIENDLY tag.

**Comment by LyleSY** [comment]
I tried the same method suggested by mlangsdorf here https://github.com/CleverRaven/Cataclysm-DDA/pull/37283 and same result, still with DinoMod disabled, just working with one FRIENDLY chick and one normal. Neither upgrade into an adult chicken

**Comment by actual-nh** [comment]
That looks like something going wrong with the grow_up code. Is zombie evolution still working right? (Currently compiling to check into #50390.)

**Comment by LyleSY** [comment]
Oh yeah, zombies are working beautifully, same process applied to a bunch of vanilla zombies:
<img width="568" alt="Screen Shot 2021-08-01 at 9 57 01 PM" src="https://user-images.githubusercontent.com/26608431/127794562-9dd686a0-04e7-403c-a270-e6a8fb7b57e1.png">

**Comment by actual-nh** [comment]
You may want to either change the title of this issue, or create another one.

**Comment by LyleSY** [comment]
Done, thanks. Keeping this alive in case the new one is fixed and this one pops up again
