### ISSUE TITLE
Found a running Quad Bike that doesn't consume fuel, does not create electric charge, and does not create exhaust smoke.

### ISSUE THREAD

**Issue by Quintovir** [CleverRaven/Cataclysm-DDA#47141]
# Describe the bug

An unmodified Quad Bike can be heard running but it doesn't consume fuel, it does not create electric charge through its alternator, it doesn't create exhaust smoke, and it cannot be shut off (controls were found at full health). I found the vehicle's battery empty. #45844 might be related.

# Steps To Reproduce

1. Load the game.
2. Examine the Quad Bike.
3. Walk around to make sure there are no nearby vehicles that are running.
4. Walk around to double check that the Quad Bike is the source of the running engine noise.
5. Try to turn off the Quad Bike's engine.

# Expected behavior

The Quad Bike's running engine should be consuming gasoline, produce electric charge, create exhaust smoke, and be capable of being turned off.

# Screenshots

N/A

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 20.2.1; Codename: Nibia; 
- Game Version: 0.E-9278-g0c167aed8a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]

# Additional context

Save file: 

[Champlin.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5899557/Champlin.zip)

**Comment by Quintovir** [comment]
After some testing I reverted back to the save file I've uploaded and after loading the game I found the engine to not be running. Should I close the issue?

**Comment by PaulBlay** [comment]
Wait a while to see if someone else spots the same thing while playing?
