### ISSUE TITLE
lockpicking proficiency increase even after stopping action using ( . ) key

### ISSUE THREAD

**Issue by shahezad96** [CleverRaven/Cataclysm-DDA#47168]
lockpicking proficiency increase even after stopping action using ( . ) key
its too easy to increase lockpicking this way

# Steps To Reproduce
1. get some lockpicking tool
2. find a locked door
3. start lockpicking door
4. stop ( using . key ) before you finish lockpicking
5. lockpicking proficiency increased even though it shouldn't

# Expected behavior
lockpicking proficiency should not increased if we stop ( . ) before finishing

**Comment by Salty-Panda** [comment]
You DID spend some time lockpicking, so it's fair to increase proficiency ( unless it's some static increase, not a time based ).
The problem would be rather with game not saving your progress while picking a lock.

Although it's way easier to just put proficiency increase at the point when you success with lockpicking.
