### ISSUE TITLE
Some items have a cutting quality but no butchering quality

### ISSUE THREAD

**Issue by Fosheze** [CleverRaven/Cataclysm-DDA#47176]
# Is your feature request related to a problem? Please describe.
While I was digging through items for a different issue I found a few items which had a cutting quality but no butchering quality. A person "could" butcher a corpse with all of them so they should be given a butchering quality.

# Describe the solution you'd like
Assign a butchering quality to the following items.
| Item  |
| ------------- |
| pair of scissors |
| X-Acto knife |
| shears |
| scalpel |
| boxcutter knife |
| simple knife spear |
| knife spear |

# Describe alternatives you've considered
-Remove butchering quality entirely and just expand cutting quality to take it's place.

# Additional context
Suggested qualities when compared to existing items.
| Item | Butchering Quality | Based On |
| ------------- | ------------- | ------------- |
| pair of scissors | 3 | Couldn't find a good existing equivalent but I figured it couldn't be worse than a honey scraper (3), could probably be higher, this really depends on the quality of the scissors as they can vary drastically from scissors which break at the sight of cardstock to scissors which could probably take off a finger at the joint without issue |
| X-Acto knife | 7 | Slightly worse than a paring knife (10) due to it's smaller size but is still a small sharp blade, should also be slightly worse than scalpel, this puts it at the same level as a multi-tool |
| shears | 3 | Couldn't find a good existing equivalent but I figured it couldn't be worse than a honey scraper (3), could probably be higher |
| scalpel | 8 | Slightly worse than a paring knife (10) due to it's smaller size but is still a small sharp blade, this puts it at the same level as a swiss army knife |
| boxcutter knife | 8 | Same level as swiss army knife, roughly same blade sharpness as X-Acto knife but has a larger blade and a grip more suited for large cuts, smaller blade than swiss army knife but much sharper |
| simple knife spear | -42 | Same level as makeshift glaive |
| knife spear | -28 | Same level as glaive |

**Comment by ZaricaDemoni** [comment]
I would like to add, on the opposite scale, you are required to have cutting to butcher, but some items don't have this while they do have negative butchery quality. Example is the glass shiv.

**Comment by Fosheze** [comment]
> I would like to add, on the opposite scale, you are required to have cutting to butcher, but some items don't have this while they do have negative butchery quality. Example is the glass shiv.

I had deliberately left those out initially because of my proposal in a different issue of removing the cutting requirement from butchering and simply make it so that anything with a butchering quality of below zero couldn't be used for actual butchering, only dismembering. However I just went and checked the requirements for dismembering and it uses the same requirements as field dressing which does require cut 1 and surface 2. So as it is all butchering items without a cutting value are completely useless. See code below.

https://github.com/CleverRaven/Cataclysm-DDA/blob/8041d14b7dc4b2a0dcad347113155741ce271800/data/json/butchery_requirements.json#L1-L112
https://github.com/CleverRaven/Cataclysm-DDA/blob/8041d14b7dc4b2a0dcad347113155741ce271800/data/json/requirements/butchery.json#L34-L38

The problem is that some items with a negative butchering value (grip hook, snow shovel, trowel, shovel, etc.) definitely should not have a proper cutting value but could still be capable of dismembering a corpse. So ultimately the dismember requirements should be changed to allow anything with any butchering value to be able to dismember a corpse. I'm not sure if that should be a separate issue or not.

**Comment by ZaricaDemoni** [comment]
I agree with this, and think this is definitely a separate issue to work on, I was just bringing it to the attention as it always felt odd seeing items with a negative, but being unusable in any form. Shovels are a good source of zombie decapitation in reality.
