### ISSUE TITLE
From 100 to 1 focus

### ISSUE THREAD

**Issue by Bertlot** [CleverRaven/Cataclysm-DDA#47172]
I was crafting a electric forge when, in 5 in-game minutes, my focus went from 100 to 1. (also happened when i finished reading a magiclysm spell scroll, but doesn't happen with a book from the base game.)

Steps taken:

1-wake up with 100 focus;
2-started crafting;
3-instantly went from 100 focus to 1 focus.

Expected behavior:

-The focus should've went from 100 to aproximately 50 over the course of hour(s)

Version and configurations:

 - OS: Windows 10 64 bit
 - Game Version: 0.E-9318-g7f32dfb-dirty
 - Graphics version: UNDEAD_PEOPLE (NEW VERSION)
 - Ingame language: English
 - Mods loaded: [e.g.dda, boats, hacktheplanet, StatsThroughSkills]

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5903906/debug.log)

**Comment by PaulBlay** [comment]
Possibly related to https://github.com/CleverRaven/Cataclysm-DDA/issues/47006
