### ISSUE TITLE
Bike racks in certain configurations display phantom names

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#47179]
# Describe the bug

When attempting to unload a racked vehicle in a certain configuration, the game shows two copies of the vehicle's name.

# Steps To Reproduce

1. Load attached save.
2. `e`xamine 1NE and choose to unload vehicle.

# Expected behavior

I suppose I only expected one vehicle to display.

# Screenshots

![image](https://user-images.githubusercontent.com/13796683/106539996-1054d380-64cd-11eb-8fcf-2dda51563732.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 20H2 (build 19042.746)
- Game Version: 0.E-9186-gd2f3109-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded:
    - Dark Days Ahead [dda],
    - C.R.I.T Expansion Mod [crt_expansion],
    - No Fungal Monsters [No_Fungi],
    - Disable NPC Needs [no_npc_food],
    - Alternative Map Key [alt_map_key],
    - SpeedyDex [speedydex],
    - Stats Through Kills [stats_through_kills],
    - Stats Through Skills [StatsThroughSkills],
    - No Rail Stations [No_Rail_Stations]

# Additional context

The bike racks are in the positions marked by arrows. I am standing in the position marked by X. What may be happening is the game is mirroring the name of the racked vehicle to the other set of bike racks for reasons unknown to man or God because both sets are contiguous.

```
 |===|
 |   |
 |   |
 |   |
>|   |
>|   |
>|===|
X^^^^
```

**Comment by Jamuro-g** [comment]
The reason is beause they overlap in the corner-tile.
Which means it finds the racked vehicle itself and then when it checks the 2nd rack line it thinks that there is a single tile wide vehicle in the corner piece.
