### ISSUE TITLE
Why not disassemble floor trunk?

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#47187]
# Is your feature request related to a problem? Please describe.

I dislike floor trunks because I generally need the volume of a full trunk (or cargo space - until they get nerfed) more than I need to be able to walk over them quickly. So I have left over floor trunks that I have no use for.

# Describe the solution you'd like

Allow use of wrench and hacksaw to disassemble floor trunk into its components.

# Describe alternatives you've considered

Leave as is.

# Additional context

**Comment by PaulBlay** [comment]
Floor trunk weighs 18kg, sheet metal weighs 6kg, door hinge weighs 0.6kg. 

So there are three choices (as I see it).
1. Deconstruction gives you 2 sheet metal, not 3 (required for construction)
PRO: Doesn't break mass/energy conservation.
CON: Lose a sheet metal.
2. Deconstruction gives you 3 sheet metal.
PRO: Don't lose 4.8kg of mass.
CON: Breaks laws of mass/energy conservation ... by 1.2kg
3. Deconstruction gives you 3 sheet metal, and the weight of 'floor trunk' is increased to 19.2kg
PRO: Simple.
CON: ... People might not like floor trunks retroactively becoming heavier. Some stuff might vanish from old saves because contents of containers may increase in total weight beyond that the pocket is allowed to contain.

I've gone with option 2 in the following.

```
json\recipes\recipe_deconstruction.json

  {
    "result": "cargo_aisle",
    "type": "uncraft",
    "activity_level": "MODERATE_EXERCISE",
    "skill_used":  "fabrication",
    "difficulty": 2,
    "time": "15 m",
    "qualities": [ { "id": "SAW_M", "level": 1 } , { "id": "WRENCH", "level": 1 } ],
    "components": [ [ [ "sheet_metal", 3 ] ], [ [ "hinge", 2 ] ] ]
  }
```

Note: Could also require the use of a hammer (for flattening things) but as this is just a disassembly I think they might just be left bent.
>    "qualities": [ { "id": "SAW_M", "level": 1 } , { "id": "WRENCH", "level": 1 } ,{ "id": "HAMMER", "level": 2 }]

**Comment by anothersimulacrum** [comment]
For anyone who is going to open a PR, go with option 3 - we should have correct migration or handling for items being too heavy to fit in pockets after migration.

**Comment by actual-nh** [comment]
How about 2 sheet_metal and whatever is needed to make up the difference in sheet_metal_small? The former two for the top and bottom; the sheet_metal_small for the sides.

**Comment by PaulBlay** [comment]
@actual-nh 

> How about 2 sheet_metal and whatever is needed to make up the difference in sheet_metal_small? 

Yeah, that was one of the first things I considered but it wouldn't work at all well. sheet_metal_small actually should be called sheet_metal_tiny. You'd need a ton of them to make up the difference (well 19). That would also break realism because who would take most of a sheet metal and cut it up into 19 pieces while disassembling something?

**Comment by actual-nh** [comment]
> Yeah, that was one of the first things I considered but it wouldn't work at all well. sheet_metal_small actually should be called sheet_metal_tiny. You'd need a ton of them to make up the difference (well 19). That would also break realism because who would take most of a sheet metal and cut it up into 19 pieces while disassembling something?

Why would it be (entirely) while disassembling? The recipe to create it requires a saw capable of cutting metal, so evidently its construction requires some taking apart of the full-size metal sheets.

(There is the oddity that the cargo_aisle item is stated to be made of not only steel, but plastic. Error needing correcting?)

**Comment by PaulBlay** [comment]
> Why would it be (entirely) while disassembling?

Eh, you're technically correct (which everyone knows is the best kind of correct) but the difference between cutting up a single piece of left over metal into 19 pieces, and cutting up, say, four pieces of left over metal into 19 pieces isn't really significant. In both cases there's the niggling sense of 'why the heck would anyone bother to do that?'.

I suspect the original weight of the floor trunk (18kg) is simply because someone thought "three sheet metal = 3 x 6kg" and forgot about the door hinges anyway.

On a more general note, I think more construction recipes should have byproducts of scrap metal, lumps of steel, chunks of steel and similar. For example, when you craft a tourniquet you use an entire 51 inch long (apparently) stout branch or 3 foot long (maybe) copper tubing. In reality, you only use like 12 inches of that while the rest is discarded.
