### ISSUE TITLE
"Passenger already here" error

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#47180]
# Describe the bug

Boarding a bike in certain configurations leads to an error message.

# Steps To Reproduce

1. Load attached save.
2. Proceed 2W to the saddle.

# Expected behavior

I expected to not see this error.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 20H2 (build 19042.746)
- Game Version: 0.E-9186-gd2f3109-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded:
    - Dark Days Ahead [dda],
    - C.R.I.T Expansion Mod [crt_expansion],
    - No Fungal Monsters [No_Fungi],
    - Disable NPC Needs [no_npc_food],
    - Alternative Map Key [alt_map_key],
    - SpeedyDex [speedydex],
    - Stats Through Kills [stats_through_kills],
    - Stats Through Skills [StatsThroughSkills],
    - No Rail Stations [No_Rail_Stations]

# Additional context

```
 DEBUG    : map::board_vehicle: passenger (Alex) is already there

 FUNCTION : void map::board_vehicle(const tripoint&, Character*)
 FILE     : src/map.cpp
 LINE     : 998
```
[Woodcock.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5908152/Woodcock.zip)

**Comment by actual-nh** [comment]
Possibly related/same - #34454?

**Comment by ToxiClay** [comment]
> Possibly related/same - #34454?

Kiiinda, except this bike is unracked and merely adjacent to racks.

**Comment by Jamuro-g** [comment]
> > Possibly related/same - #34454?
> 
> Kiiinda, except this bike is unracked and merely adjacent to racks.

was the vehicle previously racked?
i have experienced the same error while testing bike racks ... most likley the racking/unracking process doesn't clear the passenger flag.
