### ISSUE TITLE
Fuse does not fill plastic bag to max volume

### ISSUE THREAD

**Issue by Djinn247** [CleverRaven/Cataclysm-DDA#47182]
# Describe the bug
I am trying to put my 1000 fuses in a plastic bag -or part of them-
i am confused that the plastic bag ends up only holding 16 fuses, and pocket says it is 0.03L filled out of 6L
I got these fuses from starting NPC who had a lot of molotovs and pipe bombs and fuses in plastic bags.
interestingly, i remember he had multiple plastic bags, each holding 16 fuses

# Steps To Reproduce

1. Select plastic bag and attempt to insert fuses

# Expected behavior
Bag volume be filled as much as possible

# Screenshots
![image](https://cdn.discordapp.com/attachments/598523535169945607/806029198653259776/unknown.png)
![image](https://cdn.discordapp.com/attachments/598523535169945607/806030858389028884/unknown.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-9338-gf1a1af3-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Mythical Martial Arts [MMA],
    Graphical Overmap [Graphical_Overmap],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context
Save File:
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5908903/save.zip)

**Comment by esotericist** [comment]
source of issue:
the plastic bag is in a pocket that is at weight capacity

at this time, the item description interface does not convey capacity restrictions due to containing pockets' capacity

**Comment by PaulBlay** [comment]
Basically, this https://github.com/CleverRaven/Cataclysm-DDA/issues/47070

As esotericist mentions, improving the UI to show what is going on is one possible solution. I suggested that containers should be auto-wielded or placed on the ground before items are inserted into them on the basis that you don't put notes into your wallet while it is still in your trouser pocket.

**Comment by esotericist** [comment]
good catch, I missed that issue.

closing this as a duplicate, and further discussion on UX solutions can happen in the existing issue.
