### ISSUE TITLE
Reversible still recipe results in super long disassembly time

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#47199]
# Is your feature request related to a problem? Please describe.

It takes 200m (three hours 20 minutes) to make a still, which is fine. However the recipe is 'reversible' which apparently means that disassembling it takes exactly as long. This seems unrealistic as it appears to literally be just a hose in a pot. 

# Describe the solution you'd like

Could you override just the time for disassembly? There may be other 'reversible recipe' items that should be easier to disassemble than put together.

# Describe alternatives you've considered

* Have an explicit disassembly recipe in recipe_deconstruction.json
* Change "still" recipe to be more realistic the current recipe is arguably quite suspect
https://diyprojects.com/make-still-diy/

# Additional context

I don't know exactly how it works when there are multiple possible components for a recipe and then you disassemble them. Can you have multiple possible components in deconstruction recipes and pick those that were actually used when you made it?

**Comment by anothersimulacrum** [comment]
The way to override a reversible recipe is to create an explicit disassembly recipe.
When disassembling an item using a reversible recipe, it will give back the components used to make it (the game keeps track of these).

**Comment by PaulBlay** [comment]
It seems I wasn't as clear as I should have been (in my defence, I was posting way too early in the morning).

> The way to override a reversible recipe is to create an explicit disassembly recipe.

Yeah, there's no way to just change one part (like the time) then.

> When disassembling an item using a reversible recipe, it will give back the components used to make it (the game keeps track of these).

So it's a "choose your poison" kind of thing. Either it takes 200 minutes to disassemble your still, or you risk transmuting your 'pot' into a 'copper pot'. You can't have an explicit disassembly recipe with optional components and have the game pick the right one.

**Comment by Sohex** [comment]
A thermometer really isn't necessary, nor is duct tape, though an added flour paste would make sense. I think I'm going to take a look at that, it would also make sense to be able to make different styles of still like a pot still vs a reflux still for different levels of distilling.
