### ISSUE TITLE
(Magiclysm) Golems bleed mechanical fluids

### ISSUE THREAD

**Issue by SariusSkelrets** [CleverRaven/Cataclysm-DDA#47208]
# Describe the bug

#46603 added a bleeding for robots. Apparently, golems are considered robots by the game

# Steps To Reproduce

1: spawn a golem
2: hurt the golem
3: slip on the fresh mechanical fluid it leaked

# Expected behavior

Golems are magical constructs and thus don’t need mechanical fluids

# Versions and configuration

 - OS: Windows 10 
 - Game Version: 0.E-9280g9dde4db-dirty [32-bit]
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: dda, no_npc_food, package_bionic_professions, magiclysm

**Comment by anothersimulacrum** [comment]
CC @KorGgenT

**Comment by PaulBlay** [comment]
Can you disable golems with EMP blasts?

**Comment by SariusSkelrets** [comment]
> Can you disable golems with EMP blasts?

I tested it and no you can’t

**Comment by Sirbab** [comment]
Well, you can hack them with aftershock amusingly.
![image](https://user-images.githubusercontent.com/1490991/106849103-2060e480-6680-11eb-863d-3ba8bf5625fe.png)

**Comment by Night-Pryanik** [comment]
I guess they just need to be added to different species other than ROBOT, with other type of bleeding or no bleeding at all.
