### ISSUE TITLE
Pipes and tubing should have longest_side set to avoid confusion

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#47202]
Was  **Copper tubing numbers are weird**

# Describe the bug

Copper tubing is described as being 3 inches long, 0.5L volume and weighing 0.35kg. At least one of those numbers has to be wrong. (Spoiler alert: Two numbers are wrong).

# Steps To Reproduce

1. Look at copper tubing in game.

# Expected behavior

I would suggest setting the length of pipes and copper tubing to 1m (or 3 feet, if you insist) and adjusting the other numbers to match. Crafting recipes and drops will need to be checked for consistency.

A typical water pipe might be 3/4 inch diameter (larger and smaller ones exist). If the volume is 0.5L that If we take 0.5L as approximately correct, and 3/4 inch diameter that gives 69 inches long (5 3/4 feet) which is not unreasonable. and (according to some quick calculations) 1.7kg

One common source of copper tubing in game is smashing sinks. In real life each sink has two pipes (usually but not always copper) for a total of between 1 and 6 feet of tubing (depending on whether the water is piped from the floor or through the wall). In CDDA you sometimes get one (5 3/4 feet by new metric). 

# Additional context

The amount of copper you get for disassembling it would need to be updated.

**Comment by Salty-Panda** [comment]
Probably just game treats it as a cube, because nobody set longest_side to it.

**Comment by PaulBlay** [comment]
Huh, yeah, that checks out. 500mL works out as 3.13 inches x 3.13 x 3.13

If 500mL is the value that is correct, then that works out at 69 inches long for 3/4 inch diameter.

**Comment by Fosheze** [comment]
I dropped this link in the still recipe issue but I figured it could be handy for whoever takes this on too.
[Wikipedia page on copper tubing sizes](https://en.wikipedia.org/wiki/Copper_tubing#:~:text=In%20the%20plumbing%20trade%20the,and%20108%20mm%20outside%20diameters.)

**Comment by actual-nh** [comment]
Instead of treating things as a cube by default, it would probably give slightly better results by treating things as a sphere by default (the longest side being the diameter).

**Comment by PaulBlay** [comment]
> Instead of treating things as a cube by default, it would probably give slightly better results by treating things as a sphere by default

Really? As far as I can tell that just makes everything worse. 
1. More complicated.
2. Makes 'longest side' smaller than it was with the cube. Thus, very slightly, exacerbating the general problem that for any random object that does not have 'longest_side' set the description will show a Length that is unrealistically short.

If you take a set of all possible shapes then the sphere is, by definition, the one that gives the smallest possible calculated 'longest_side'. Thus, every real value of 'longest_side' _except for spheres_ will be too short. 

If you're going to change the very arbitrary calculated longest_side then, IMO, it would be slightly better to consider the object to be a block with sides in the ratio 3 x 2 x 1. Highly encouraging people to add longest_side for all inflexible objects would be much better, though.

**Comment by actual-nh** [comment]
It would make the longest side larger than with a cube. Any sphere with the same diameter as a cube's side takes up less volume than the cube - it fits _inside_ the cube; therefore, a sphere has to have a longer diameter than the cube's side in order to take up the same volume.

It isn't a sphere that has the smallest longest side (diameter) for a given volume. It's a cube.

**Comment by PaulBlay** [comment]
Oops, yeah, in my head I confusing the calculated 'longest_side' with the longest line that can be fitted inside the object (the 'space diagonal'). For the cube side a that is 
a * 3 ^ -3 or approximately 1.44 a
