### ISSUE TITLE
 Game fails at loading character generation "additional tiles defined, but 'multitile' is not true.

### ISSUE THREAD

**Issue by hrabnaz** [CleverRaven/Cataclysm-DDA#47204]
Game fails at loading character generation "additional tiles defined, but 'multitile' is not true.

The game fails to proceed to character creation, tested with various mods and then without. Its possible to start by turning off tilesets, so far no tileset tested worked.

# Steps To Reproduce

Make a new world
Try to make a new character.
Crashes to main menu
turn of tilesets
Works

# Expected behavior

Character creation starts
Game works with tilesets turned on.

# Screenshots
![Screenshot_19](https://user-images.githubusercontent.com/51446390/106759424-09e06c00-6633-11eb-8ca5-a52924f9766d.png)

Do not take a screenshot of the crashing window. Please provide the crash logs in the "Additional context" -->

# Versions and configuration

<!-- Please complete the following information; you can now go to:
    - "Main menu (ESC) > Debug Menu > Info > Generate game report" to generate this report.
    - Please update your OS version with a more precise version.

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-9353-g6f0e582-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: Systemsprache []
- Mods loaded: [
    Dark Days Ahead [dda],
    NPC-Bedürfnisse deaktivieren [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]

# Additional context

<!-- Add any other context about the problem here.

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5919001/debug.log)

**Comment by anothersimulacrum** [comment]
Please fill out versions and configuration. For this in particular, it's important to know what tileset you are using.

**Comment by ZhilkinSerg** [comment]
You are using incompatible third party tileset. Use compatible game and tileset versions.
