### ISSUE TITLE
Vehicle mounted weapons can not be used

### ISSUE THREAD

**Issue by chuizhi** [CleverRaven/Cataclysm-DDA#47224]
Starting from version 11429, vehicle mounted weapons can not be used, whether set to manual or automatic. When set to automatic, it will never fire. When set to manual, it will display "cannot aim turret: all turrets are offline or in automatic aiming mode"
The above text is the result of Baidu translation
====================
从版本11429开始,车载武器无法使用,无论设置成手动还是自动.设置成自动永远不会射击,设置成手动,手动瞄准时显示"无法瞄准炮塔:所有炮塔均已离线或处于自动瞄准模式".

**Comment by Jamuro-g** [comment]
please upload your save.

i tried reproducing the issue with debug spawned humvees in version 11431 & 11429 but the turret works fine

**Comment by chuizhi** [comment]
> please upload your save.
> 
> i tried reproducing the issue with debug spawned humvees in version 11431 & 11429 but the turret works fine

I'm using xm34 EMP transmitter with battery. The battery is fully charged
How to upload save? Mine is 1.37gb
The above text is the result of Baidu translation
===========
我用的是XM34 EMP发射器,用电池的.电池电量充足.
怎么上传save?我的有1.37GB
![360截图20210204180709318](https://user-images.githubusercontent.com/59391871/106888355-68841380-6721-11eb-8117-9dccc7f45424.jpg)

**Comment by chuizhi** [comment]
> please upload your save.
> 
> i tried reproducing the issue with debug spawned humvees in version 11431 & 11429 but the turret works fine

My God? I finally tried to figure out what the problem was.
The problem is with the xm34 EMP.
Through debugging, we can see that version 11427 has only one xm34emp, which is # 1098, while version 11431 has two, which are # 1115 and # 1116.
After the version upgrade, my xm34emp installed in the car has become # 1115, and only # 1116 can be used normally.
The above content is translated by Baidu.
天哪！我终于试出来问题出在哪里了。
问题出在XM34 EMP上。
通过调试可以看到，版本11427的XM34EMP只有一个，是#1098，而版本11431则有两个，分别是：#1115和#1116。
版本升级后，我的安装在车上的XM34EMP变成了#1115，而只有#1116才能正常使用。

**Comment by BrettDong** [comment]
版本11432我只看到一个XM34 EMP发射器：
<img width="752" alt="螢幕截圖 2021-02-04 上午11 08 26" src="https://user-images.githubusercontent.com/21075502/106920653-4ff00b00-66d9-11eb-8add-7467c66170fa.png">
你在11431里看到的两个XM34 EMP有什么区别？

**Comment by chuizhi** [comment]
> 版本11432我只看到一个XM34 EMP发射器：
> <img alt="螢幕截圖 2021-02-04 上午11 08 26" width="752" src="https://user-images.githubusercontent.com/21075502/106920653-4ff00b00-66d9-11eb-8add-7467c66170fa.png">
> 你在11431里看到的两个XM34 EMP有什么区别？
能看到图片吧？上边那个XM34 EMP projector 就是。应该是汉化组还没翻译的。下边一个XM34 EMP发射器，是正常的。
但是昨天玩的过程中，过了一会，又不能发射了，拆开又成了XM34 EMP projector，我还不清楚是不是上边一个表示坏了，今天继续试。
这两个物品，在描述是也是完全不同的。应该不是MOD的问题，因为同样的存档，版本11427玩是正常的。但是版本11427小地图有BUG。
=================
Can you see the picture? The xm34 EMP projector above is. It should be that the Sinicization group hasn't translated yet. The next xm34 EMP transmitter is normal.
But in the process of playing yesterday, after a while, it couldn't be launched again. It was disassembled and became xm34 EMP projector again. I don't know if one of the above said that it was broken. Continue to try today.
The descriptions of these two items are also completely different. It should not be a mod problem, because the same archive, version 11427 play is normal. But 11427 maps have bugs。

![360截图20210205101741554](https://user-images.githubusercontent.com/59391871/106980608-75454d80-679b-11eb-98f9-816abb1a02d1.jpg)
![360截图20210205101802170](https://user-images.githubusercontent.com/59391871/106980615-770f1100-679b-11eb-8b81-0d82f09f38da.jpg)


![360截图20210205101351760](https://user-images.githubusercontent.com/59391871/106980312-e46e7200-679a-11eb-8244-ab6a8f52142b.jpg)

**Comment by John-Candlebury** [comment]
The aftershock migrated version needs magazines, so afaik, it can no longer run from vehicle power.

Can you spawn the item named "power cartridge", reload the mounted XM34  and test if it works correctly?

**Comment by chuizhi** [comment]
> The aftershock migrated version needs magazines, so afaik, it can no longer run from vehicle power.
> 
> Can you spawn the item named "power cartridge", reload the mounted XM34 and test if it works correctly?

After the test, it's like this: I put on a new xm34 EMP, which can work normally.
However, once I read the file and re-enter the game, it immediately becomes xm34 EMP that needs magazine.
However, if I directly debug an xm34 EMP that needs a magazine, it can't be directly installed on the car yet!!! It should be a new thing, so it's too late for the author to write the mod of vehicle weapon.
The largest magazine is only 1500, only a few shots.
I'd like to change my weapon and find that the A7 laser gun is the same.
I decided to drive home, plant land and build a house at home, and then try to contact the mod author of vehicle borne weapons, and come out after solving the problem.
===========
经过试验，现在是这样的：我换上一个新的XM34 EMP，可以正常运行。
但是，一旦我读档，重新进入游戏，马上就变成了需要弹匣的XM34 EMP。
但是，如果我直接调试出来一个需要弹匣的XM34 EMP，还不能直接安装到车上！！！应该是新出的玩意，所以车载武器MOD作者来不及写。
最大的弹匣也只有1500，只能打几下。
我想换个武器，发现A7激光枪也这样。
我决定开车回家，在家里种地盖房子，然后去试着联系车载武器MOD作者，等解决完问题再出来。

**Comment by chuizhi** [comment]
> 版本11432我只看到一个XM34 EMP发射器：
> <img alt="螢幕截圖 2021-02-04 上午11 08 26" width="752" src="https://user-images.githubusercontent.com/21075502/106920653-4ff00b00-66d9-11eb-8add-7467c66170fa.png">
> 你在11431里看到的两个XM34 EMP有什么区别？

所有的激光武器，一旦安装到车人，然后重新读档，就会变成需要弹匣的。看来我要一直开着游戏不关机了？
我回家盖房子种地去。等问题解决了再出来浪。请问你知道车载武器的作者如何联系吗？

**Comment by Glasswalker78** [comment]
I can confirm this behavior.
 See attached file. V29 laserpistol on turret with turret control unit can be found in the middle row back of the vehicle, A7 Laser rifle and turret controll unit for installation are in the characters inventory.
Prior to Build 11428 everything worked normal, now the two can't be used in a turret anymore. Wondering what happened I deinstalled the rifle only to see that I can't even reinstall it anymore in my vehicle because of an empty magazine. Don't know if that is intended behavior or not. The M249 installed over the driver's seat works fine. 

[San Patricio.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5931575/San.Patricio.zip)

**Comment by chuizhi** [comment]
> I can confirm this behavior.
> See attached file. V29 laserpistol on turret with turret control unit can be found in the middle row back of the vehicle, A7 Laser rifle and turret controll unit for installation are in the characters inventory.
> Prior to Build 11428 everything worked normal, now the two can't be used in a turret anymore. Wondering what happened I deinstalled the rifle only to see that I can't even reinstall it anymore in my vehicle because of an empty magazine. Don't know if that is intended behavior or not. The M249 installed over the driver's seat works fine.
> 
> [San Patricio.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5931575/San.Patricio.zip)

The solution is to copy version 11427's aftershock mod. It's a problem caused by aftershock mod update.
But note that when you copy it, you have to dismantle the weapon on the vehicle first, then debug it out and reinstall it.
Don't read in zombie dinosaurs.
The above is the result of Baidu translation, the following is the original.
解决的方法是复制版本11427的Aftershock MOD。是Aftershock MOD更新导致的问题。
但是要注意，你复制过来，还要先拆了车上的武器，然后调试一把出来，重新安装上。
千万不要在丧尸恐龙堆里读档。

**Comment by John-Candlebury** [comment]
Ah, I'm one of the mod authors.

The weapons requiring magazines to fire, even when mounted on a vehicle, is intended.
However, not being able to mount the weapons in your car is a bug. I'll try to fix this on the weekend.
