### ISSUE TITLE
invalid MONSTER_FACTION id "otter"

### ISSUE THREAD

**Issue by akirashirosawa** [CleverRaven/Cataclysm-DDA#47221]
# Describe the bug
`ERROR : src/generic_factory.h:467 [int_id<T> generic_factory<monfaction>::convert(const string_id<T> &, const int_id<T> &, const bool) const [T = monfaction]] invalid MONSTER_FACTION id "otter"`
# Steps To Reproduce
Load save

# Expected behavior
No error

# Versions and configuration
Current Master commit 658162c43b4be0113dababc5624bf30ef005d6ed
# Additional context
Most likely related to PR #47152. Solution:
>Removed some superflous factions ( "carp", "salmon", "cop_zombie", "otter" )

And I didn't see any kind of migration code to load previous saves (not sure if it is possible).

**Comment by BrettDong** [comment]
Another one:
```
 DEBUG    : invalid MONSTER_FACTION id "cop_zombie"

 FUNCTION : int_id<T> generic_factory<monfaction>::convert(const string_id<T> &, const int_id<T> &, const bool) const [T = monfaction]
 FILE     : src/generic_factory.h
 LINE     : 467
```
<img width="1072" alt="螢幕截圖 2021-02-04 上午10 54 06" src="https://user-images.githubusercontent.com/21075502/106918591-53829280-66d7-11eb-81fa-fe158f3a5d98.png">

**Comment by actual-nh** [comment]
Blast. Is there a migration capability for monster factions? Also - ping @Venera3; sorry I didn't think about this...

**Comment by Venera3** [comment]
Yeah, if one *isn't* an idiot like yours truly he would have added JSON entries he removed to the obsolete file to be deprecated down the line. Apologies, I'll have the fix up in a few hours. (This might also lead to some slight infighting between cop and normal zombies, so use it to your advantage while it lasts)

**Comment by Venera3** [comment]
[obsolete.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5927913/obsolete.zip)

While that merges, you can extract the changed file into \data\json to fix it.
