### ISSUE TITLE
Indefinite Hang when asking Mr. Lapin NPC about other people to meet

### ISSUE THREAD

**Issue by Sirbab** [CleverRaven/Cataclysm-DDA#47220]
# Describe the bug
When asking Mr. Lapin about people to meet, he asks you to check up on a family of farmers. If one accepts, presumably the game attempts to spawn that location, and appears to never recover.

# Steps To Reproduce
1: Load attached save
2: Ask about news about the outside world
3: Ask if there are other people to meet
4: accept
5: Infinite hang?  I waited about a minute on a strong computer and was just left with a spinning cursor.

I'm honestly not sure if this is a singular issue with my save, and i'm unaware how i would reliably create a new world and test this unfortunately.  If someone knows how, i welcome them to try it.

# Expected behavior
I would expect that the game is able to succinctly generate the location without essentially freezing.  This seems like obviously non-ideal behavior.

# Screenshots

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-9318-g7f32dfb-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Modular Turrets Remake [modular_turrets_remake],
    Civilian Salvaged Robots [civilian_salvaged_robots],
    Automations [robot_automation],
    Gun Cotton [guncotton],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    More Survivor Stuff [more_survivor_stuff],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    sees-player icon, retrodays [sees_player_retro],
    Bens GF recipes [Tolerate_This],
    Useful Helicopters [useful_helicopters]
]

# Additional context
[Spring Garden.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5923504/Spring.Garden.zip)
Crash log does not generate, so it is not applicable sadly.
I'm aware I'm using a number of unsupported mods, but i would be surprised if they were responsible for the freeze.  If i knew a better way to find this npc, i'd gladly test with a vanilla world.
[debug.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/5923537/debug.txt)
I wonder if this is at all related to #42457

**Comment by actual-nh** [comment]
Most likely trying to generate Isherwood Farms; see, e.g., #47225, although I can't find anything in the debug log (might have been buffered, though).

**Comment by Sirbab** [comment]
Was able to finally spawn this after several minutes of patience.  It was indeed the isherwoods.  Given there is another issue regarding this, i'm going to close this one.
