### ISSUE TITLE
Add a graphic to the vehicle display page detailing installation "slots"

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#47223]
# Is your feature request related to a problem? Please describe.

When attempting to install a part onto a vehicle, it's not always immediately obvious when and why you can or cannot install the part. For example, a vehicle tile with [`frame` and `large storage battery`] cannot have a 60L tank bolted to it, but a tile with [`frame` and `welding rig`] can. The game internally knows what parts occupy what "slots"; it would be nice if that were exposed somehow to the player.

# Describe the solution you'd like

What suggests itself first to me is for a graphic to be placed somewhere in the empty space on the left panel, below the vehicle schematic.

**Comment by Fosheze** [comment]
Would it be possible to simply rename and replace the vehicle part categories with the slot the parts fit in? That could make this just a tedious but simple JSON edit.

**Comment by ToxiClay** [comment]
> Would it be possible to simply rename and replace the vehicle part categories with the slot the parts fit in? That could make this just a tedious but simple JSON edit.

That sounds like it'd also require C++, because you're reorganizing the visual display. Unless the C++ draws the categories based on the JSON? I haven't touched vehicle code *at all,* so I don't know how it works.

**Comment by Fosheze** [comment]
> > Would it be possible to simply rename and replace the vehicle part categories with the slot the parts fit in? That could make this just a tedious but simple JSON edit.
> 
> That sounds like it'd also require C++, because you're reorganizing the visual display. Unless the C++ draws the categories based on the JSON? I haven't touched vehicle code _at all,_ so I don't know how it works.

I'm definitely not an expert either but I have been browsing through the changes from last time the categories were changed in #44848 and it looks like the vehicle part categories can be modified just by editing [vp_categories.json](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/vehicleparts/vp_categories.json). There were C++ changes in that PR but it looks like they only changed how the game loads the categories; none of the categories seem to be hardcoded in C++ themselves with the possible exception of "all" and "filter".

**Comment by actual-nh** [comment]
Reminder: Be sure to remember to do any migration (old to new part categories) needed for prior saves!

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
