### ISSUE TITLE
Phantom fuel in vehicle

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#47243]
# Describe the bug

If an engine runs out of fuel, save/quitting and reloading generates 250mL of fuel from the ether.

# Steps To Reproduce

1. Load attached save.
2. Examine the power grid, and observe 0.3L of motor oil.
3. Turn on the engine, and pass time until it dies.
4. Examine the vehicle again, and observe 0.0L.
5. Save and quit.
6. Reload save.
7. Examine the power grid, and observe (once again) 0.3L of motor oil.

# Expected behavior

I expected to not see 250mL of fuel, and perhaps for the fuel entry to clear itself from the vehicle after emptying, rather than showing 0.0.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 20H2 (build 19042.746)
- Game Version: 0.E-9353-g6f0e582-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded:
    - Dark Days Ahead [dda],
    - C.R.I.T Expansion Mod [crt_expansion],
    - No Fungal Monsters [No_Fungi],
    - Disable NPC Needs [no_npc_food],
    - Alternative Map Key [alt_map_key],
    - SpeedyDex [speedydex],
    - Stats Through Kills [stats_through_kills],
    - Stats Through Skills [StatsThroughSkills],
    - No Rail Stations [No_Rail_Stations]

# Additional context

[Woodcock.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5933959/Woodcock.zip)

**Comment by PaulBlay** [comment]
Isn't this basically the same one you submitted earlier?

https://github.com/CleverRaven/Cataclysm-DDA/issues/46755

**Comment by ToxiClay** [comment]
> Isn't this basically the same one you submitted earlier?
> 
> #46755

....yes it is. I *forgot* that I had submitted that one. 🤦‍♂️
