### ISSUE TITLE
Allow pocket selection when inserting items into clothing

### ISSUE THREAD

**Issue by xthorgoldx** [CleverRaven/Cataclysm-DDA#47248]
# Is your feature request related to a problem? Please describe.
Currently, there are two ways an item can be placed in an article of clothing. The first is automatic distribution from item pickup and unloading; items are placed into the smallest available pocket on the survivor's person, determined by pocket size and autopickup pocket settings (priority, whitelists, etc). The second is manual (i)nsertion; when objects are manually inserted into a clothing item, they will _ignore_ autopickup settings and instead go into the first available pocket (Pocket 1, Pocket 2, etc).

This causes frustration when trying to organize items within the player inventory, especially if a clothing item has pockets with very different properties. Take the survivor harness: Pocket 1 is a "sling" pocket that can fit darn near anything short of a spear (8L, 47in) and three other "regular" pockets (1.5L, 7in). Say I want to move a STANAG magazine from my backpack to my harness - if Pocket 1 is empty, the magazine will go in there, preventing me from holstering my rifle/sword/axe later on. What's more, it's impossible to NOT use that pocket - in order to make the magazine go into a smaller pocket, I have to holster something in Pocket 1, or drop the magazine to the ground and pick it back up again (to make it subject to autopickup rules), or otherwise juggle my inventory.

Alternatively, take hiking backpack, which has 6 pockets: one main compartment, three smaller compartments, and two sheaths. If I try to place a hunting knife into my hiking backpack, it will go into the main compartment (Pocket 1), instead of going into one of the sheath pockets (admittedly in this case, the problem can be avoided by (a)ctivating the pack to sheath a weapon). This wastes space, and will lead to confusion on why I can't pick up anything despite having so much empty volume.

# Describe the solution you'd like
When inserting an object into an article of clothing that has multiple pockets, provide a prompt to select which pocket the item should go into.  In addition, to assist in storage troubleshooting, provide an explanation of why certain pockets can't be selected,rather than excluding them entirely: "Too Big" or "Too Heavy" or "Can't be stored in a sheath".

# Describe alternatives you've considered
* Have manual insertion obey autopickup pocket settings to determine which pocket in which to place the item - possible and probably good as a toggleable option. However, if the player may need the ability to override autopickup rules when inserting objects, so having pocket selection by default would be more useful in the general case.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
