### ISSUE TITLE
Radios with the UPS conversion mod installed lose the ability to scan for stations

### ISSUE THREAD

**Issue by Quintovir** [CleverRaven/Cataclysm-DDA#47265]
# Describe the bug

Radios with the UPS conversion mod installed lose the ability to scan for stations.

# Steps To Reproduce

1. Turn on a radio with a UPS conversion mod installed.
2. Activate the turned on radio.
3. Notice that the radio has been switched off.
4. Turn on a radio with a charged removable battery inserted.
5. Activate the turned on radio.
6. Notice that you are prompted to either scan for stations or turn off the radio.

# Expected behavior

Radios with UPS conversion mods installed should allow you to scan for stations.

# Screenshots

N/A

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 20.2.1; Codename: Nibia; 
- Game Version: 0.E-9434-g1e8a075abd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]

# Additional context

Save game with a radio with a charged battery inserted, a radio with a UPS conversion mod installed, and charged UPS' in the inventory.

[Champlin.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5937211/Champlin.zip)

**Comment by PaulBlay** [comment]
Possibly this is related to https://github.com/CleverRaven/Cataclysm-DDA/issues/46773 ?
