### ISSUE TITLE
The recently added mission from the new island prison crashes the game at success

### ISSUE THREAD

**Issue by Termineitor244** [CleverRaven/Cataclysm-DDA#47282]
# Describe the bug

#46726 introduced several things, one of which is a new mission from the leader of the new, prisoner faction, but when you try to complete it, the game crashes. 

~~That, and the mission itself has a mistake, it asks you for a Military Id, but the safe from where you are supposed to retrieve it only has an Industrial Id, maybe this is intentional, I don't know, but then it should be at least clearer what is it that you need to find.~~ Edit: My mistake, the Military ID is in "The Chief"'s safe, I was looking into "The Warden"'s safe...

# Steps To Reproduce

1. Make a player start in the island prison, second variant
2. Teleport to the leader of the prisoners
3. Accept the mission, grant yourself an Industrial Id, try to complete it, nothing happens, do the same with a Military Id, the game crashes
OR
1. Load the game from the save below
2. Try to complete the mission
3.  The game crashes 

# Expected behavior

That the game doesn't crash when you complete a mission.
~~That, and to see the npc request items that are actually where they are sending you to find them, or that at least they recognize they didn't wanted what you found.~~

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-9442-ge9e4d33-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: Español (España) [es_ES]
- Mods loaded: [
    Dark Days Ahead [dda],
    Desactivar necesidades de los PNJ [no_npc_food],
    Profesiones Biónicas [package_bionic_professions],
    SpeedyDex [speedydex],
    Estadísticas a través de las muertes [stats_through_kills]
]

# Additional context

Logs:
[logs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5937976/logs.zip)
Save folder:
[Arbuckle.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5937977/Arbuckle.zip)

As a side note, I would like to mention that the rewards are basically worthless, they should at least let you commerce with them or contract them as mercenaries, or, well, something, it's a pretty difficult mission and the leader can get the best stuff in the whole island if you give him the ID. And, if you don't give him the ID, those things can be yours, and you can easily take all of their food, I demand a better reward for this mission, at the very least give me a gun, or a set of armor taken from one of the dead guards... But again, I would prefer a little of respect from the prisoners.

Edit: I forgot to mention, but this bug doesn't happens when you just meet the leader for the first time with already a Military Id and just give it to him, I hope that helps to search for the problem

Edit 2: Grammar

**Comment by Termineitor244** [comment]
Something not entirely related to the bug report: Is safecraking, even with devices 20, and stethoscope, and the safecraking proficiency, supposed to spend several hours of in game time? Cause that happened to me when I tried to retrieve the contents from the safe in the prison, I gave up after several hours and just smashed the thing with a mace.

**Comment by actual-nh** [comment]
Ping: @Night-Pryanik

**Comment by BrettDong** [comment]
Did not crash in my own save after spawned a military ID card through debug menu and completed the mission, but reproduced crash from the save provided by OP.

**Comment by BrettDong** [comment]
The game stuck in an infinite loop when the NPC wants to reward the player a can of beans.

**Comment by BrettDong** [comment]
<img width="391" alt="螢幕截圖 2021-02-06 下午10 23 04" src="https://user-images.githubusercontent.com/21075502/107135575-e2570100-68c9-11eb-802a-e82b001bdaf9.png">

**Comment by Termineitor244** [comment]
> 
> 
> Did not crash in my own save after spawned a military ID card through debug menu and completed the mission, but reproduced freeze from the save provided by OP.

Huh, weird, It happened to me in my first try, and then again in my second (The save that I provided is the second), but at least the bug could be reproduced from my save

**Comment by actual-nh** [comment]
@Termineitor244: You might want to make another issue for the other, well, issues you're having with the mission - be sure to put in something like `ping @Night-Pryanik` when/if you do so.

**Comment by Termineitor244** [comment]
@actual-nh, thanks, I will do it, I found out the other issues when proving the rewards for the mission, so I just added them to my report, but it is true that they should be separated so they can be solved or discarded as appropriate.
And @BrettDong, thanks for the quick fix! (Even if it is a band-aid fix)

**Comment by actual-nh** [comment]
> And @BrettDong, thanks for the quick fix! (Even if it is a band-aid fix)

Actually, it's something that could happen with any mission, as far as I can tell, so it's good to get it fixed now - it isn't a band-aid fix in that regard!

**Comment by Termineitor244** [comment]
> 
> 
> > And @BrettDong, thanks for the quick fix! (Even if it is a band-aid fix)
> 
> Actually, it's something that could happen with any mission, as far as I can tell, so it's good to get it fixed now - it isn't a band-aid fix in that regard!

It isn't? I thought it was... -Reads again the PR details...- Ohhhhh, so the "deeper problem" was fixed too, that's good!

**Comment by Termineitor244** [comment]
Hmmmm I was preparing to report again the issue with the IDs... But testing it, I saw that I mistook "The Warden" with "The Chief", and both characters have safes... I opened the safe from "The Chief" and that indeed had the Military ID card that was needed, so I will cross that from the list
