### ISSUE TITLE
Sidebar options menu doesn't have enough space for all options

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#47285]
# Describe the bug

With addition of new sidebar blocks, sidebar options menu doesn't have enough space to display them. They still can be displayed, it just looks ugly.

# Steps To Reproduce

Start the game (happening on b11440 but probably started when weariness blocks were added), press "{", check left panel.

# Expected behavior

Either the menu should be higher, or options list should allow scrolling (which it kinda does but it's ugly and unclear atm).

# Screenshots
Here, overmap block is selected. Look where it is.
![cataclysm-tiles_2021_02_07_00_36_40_899](https://user-images.githubusercontent.com/56833396/107135263-ca17ce00-692b-11eb-8879-d890b506ca4a.png)

And here, weariness block is selected. It isn't even displayed but if you press "down" again, the list will scroll and it will be at the bottom (over the menu borders, like "overmap" was in previous screenshot).
![cataclysm-tiles_2021_02_07_00_36_38_726](https://user-images.githubusercontent.com/56833396/107135268-cf751880-692b-11eb-887e-9682d124043f.png)

# Versions and configuration

- OS: Windows 7x64
- Game Version: 0.E-9439-g1e8a075-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills],
    Bionic Professions [package_bionic_professions],
    Ultica cursor replacement [ultest],
    Hauling space revived [hspace]
]

**Comment by actual-nh** [comment]
Ping: @anothersimulacrum, perhaps @AlexMooney?
