### ISSUE TITLE
Spells using bionic power display cost in bp instead of (kilo)joules

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#47289]
# Describe the bug

Spell cost is displayed in "bionic power" instead of kJ. Thankfully it also displays current bp so you can infer those are actually one and the same. Still, I think it's the only place left in the game where bionic power is still counted in bps instead of kJs.

# Steps To Reproduce

Learn Laze, look at its cost.

# Expected behavior

My understanding is power should be measured in kJ everywhere in the game, so it must be measured in kJ here too.

# Screenshots

![cataclysm-tiles_2021_02_07_10_44_36_302](https://user-images.githubusercontent.com/56833396/107135992-0c440e00-6932-11eb-9421-a5263899d553.png)

# Versions and configuration

- OS: Windows 7x64
- Game Version: 0.E-9439-g1e8a075-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills],
    Bionic Professions [package_bionic_professions],
    Ultica cursor replacement [ultest],
    Hauling space revived [hspace]
]

**Comment by actual-nh** [comment]
Ping: @KorGgenT

**Comment by enkeyz** [comment]
Would like to work on this.
