### ISSUE TITLE
Missing move cost for inserting items into pockets

### ISSUE THREAD

**Issue by garnetgw** [CleverRaven/Cataclysm-DDA#47298]
# Describe the bug

Items can be inserted into pockets instantly (0 move cost). This works for any item in your inventory or that are on the same tile as you, and also applies to unwielding items that can opt to be placed in a pocket (i.e. knife into sheath). 

Taking items out of pockets incurs regular expected move cost.

# Steps To Reproduce

1. Equip a container.
2. Stand within pickup range of an item, or have it in a separate container.
3. Select (i)nsert on the empty container, insert an item.
4. Observe move counter displaying 0.

5. Bonus: Stand next to hostile mob(s) and shuffle items back and forth between containers with impunity.

# Expected behavior

Survivor does not toki wo tomare to manage their inventory

# Screenshots

Here's me shuffling 8 knives from a backpack into 8 sheaths after being grabbed by a zombie.

![image](https://user-images.githubusercontent.com/58456510/107138950-a1142080-68cc-11eb-92b1-6c6d06b8aea3.png)

![image](https://user-images.githubusercontent.com/58456510/107138967-b9843b00-68cc-11eb-8c95-6bf464ae4903.png)

![image](https://user-images.githubusercontent.com/58456510/107138996-d91b6380-68cc-11eb-88be-5f59f14ce791.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-9443-g4eb4e8f-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by PaulBlay** [comment]
@KorGgenT  Can confirm

[Narnia.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5938775/Narnia.zip)

Save file has Ten dollar bills (60) loose in inventory, and Ten dollar bills (60) in a leather wallet.

Time 1:49:12 PM
Drop Ten dollar bills (60) loose in inventory
Time 1:51:11 PM
Pick up Ten dollar bills (60) loose on ground
Time 1:52:00 PM
Drop Ten dollar bills (60) loose in inventory
Move two north
Time 1:54:00 PM 
Insert Ten dollar bills (60) from leather wallet into wallet
Time 1:54:00 PM 
Insert Ten dollar bills (60) from wallet into leather wallet
Time 1:54:00 PM 

- OS: Windows x64 8.1
- Game Version: 0.E-9451-g2fb49d3-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]
