### ISSUE TITLE
Sporadic "teleumbrella" error in NPC test

### ISSUE THREAD

**Issue by BrettDong** [CleverRaven/Cataclysm-DDA#47296]
# Describe the bug
Sometimes `npc-movement` test fails to start with the error saying cannot put telescope umbrella into inventory:
<img width="857" alt="螢幕截圖 2021-02-04 上午10 26 59" src="https://user-images.githubusercontent.com/21075502/107137930-ee998900-68de-11eb-91c4-18dc1f1065f8.png">

# Steps To Reproduce
Repeatedly run `npc-movement` test.

# Expected behavior
Should not occur such an error.

# Versions and configuration
4eb4e8ff768e89fb9cc09f804b268fcedc85499c

**Comment by actual-nh** [comment]
Does it need to be compacted first?

**Comment by mqrause** [comment]
The issue is (most likely) an item added by a starting trait (albino in this case) to a character without the necessary storage space.
