### ISSUE TITLE
Game crash when towing vehicle over a bridge

### ISSUE THREAD

**Issue by xd3ltax22** [CleverRaven/Cataclysm-DDA#47293]
# Describe the bug

Towing a vehicle with another vehicle, (a military cargo truck towing a humvee). The first crash happened on the down side on the bridge, so coming off the bridge, the second time after i repeated it it was on the upside, so going on to the bridge. Total game crash to desktop with error message to check the crash log

# Steps To Reproduce

1. Get two vehicles( no idea if it matters what kind.)
2. Connected them with a heavy duty cable (mine just so happened to be damaged {l.})
3. Tow the vehicles across a bridge. 

# Expected behavior

The game crashes. i don't know why at all.

# Screenshots

Do not take a screenshot of the crashing window. Please provide the crash logs in the "Additional context" -->

# Versions and configuration

 - OS: Win 10
 - Game Version: Experimental v. 11429 
 - Graphics version: Tiles 1.B
 - Ingame language: English
 - Mods loaded:
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5938285/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5938291/debug.log)

 -->

# Additional context

**Comment by BrettDong** [comment]
Can confirm on 4eb4e8ff768e89fb9cc09f804b268fcedc85499c.
Minimal reproducible save: 
[Towing.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5938312/Towing.zip)

Crash on https://github.com/CleverRaven/Cataclysm-DDA/blob/4eb4e8ff768e89fb9cc09f804b268fcedc85499c/src/map.cpp#L672

where `veh.tow_data.get_towed()` returns `nullptr`.
