### ISSUE TITLE
Crash to desktop. Invalid field types id "65537". Unknown intensity level 65543 for field type .

### ISSUE THREAD

**Issue by Quintovir** [CleverRaven/Cataclysm-DDA#47308]
# Describe the bug

My game has crashed several times and shown the debug messages:
Invalid field types id "65537"
NEW Invalid field types id "458759"
Unknown intensity level 65543 for field type .
NEW Unknown intensity level 196615 for field type .

I've noticed that all the crashes happened as I drove near forests at night.

# Steps To Reproduce

I've loaded the game and drove through the same path but the game wouldn't crash.
1. Drive near forests at night.
2. Hope the game crashes.

# Expected behavior

Driving at night near forests should not cause crash to desktops.

# Screenshots

N/A

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 20.2.1; Codename: Nibia; 
- Game Version: 0.E-9461-g0638fba7a9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]

# Additional context

Save game, debug.log, crash.log.
[Champlin.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5939479/Champlin.zip)
NEW
[Champlin.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5939742/Champlin.zip)

**Comment by actual-nh** [comment]
#47303 might help with this.
