### ISSUE TITLE
Descending from the heavens onto Deep Water makes you Jesus, and trains athletics.

### ISSUE THREAD

**Issue by superninjakiwi** [CleverRaven/Cataclysm-DDA#47305]
# Describe the bug

When climbing down from a higher Z level onto water that you would sink into, you don't actually sink. Instead, you can stand on the water until you move. You can do tasks such as reading which take a long time while standing on water, which trains your athletics since you're technically swimming.

# Steps To Reproduce

1. Spawn in an evac shelter
2. Use the map editor to create a Deep Water tile next to the shelter.
3. Climb to the roof, and then climb down a level onto the Deep Water tile.
4. Spawn a book, and read it.
5. Find that you do not sink. As a bonus, you are training Athletics the entire time you're there.

# Expected behavior

I shouldn't be able to climb down onto water and stay on top of it if I can't swim. 

# Screenshots

https://i.gyazo.com/398a34a1a0b0622f3476fb30a7a5f359.png
# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-9184-g7238324-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    No Fungal Monsters [No_Fungi],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Disable NPC Needs [no_npc_food]
]

# Additional context

A similar issue occurs with teleport pads (and other teleports, such as magiclysm's phase door), which allows players to stand on top of whatever tile they want, for however long they want, including not only deep water tiles, but also air tiles. 

Reading books while swimming could potentially be a separate balance issue; if you strip down to nothing and just float there while reading, you have no chance of drowning or draining stamina, and you train athletics at the same time. I don't know for absolute certain that it's an issue though; assuming you can keep the book dry (and I haven't seen any wet book mechanics yet), you could theoretically just float on your back and read.

**Comment by PaulBlay** [comment]
See also levitating bandits. https://github.com/CleverRaven/Cataclysm-DDA/issues/46876

**Comment by UmbralReaper** [comment]
If you get thrown through an open wall by, say, a zombie brute, you also stand on the air. You fall if you try to move any tiles, but can stand for as long as you want.

**Comment by wapcaplet** [comment]
Confirmed in 0.E-9532-g57d594e - Climbing down from the roof onto deep water does not cause me to "dive into" the deep water, so I can stay there reading a book and learning swimming. I do get wet, but I don't sink, despite wearing clothes and a backpack.

Moving out of the deep water then back into it, I have to dive in, and sink.

![image](https://user-images.githubusercontent.com/238395/107300997-cd987b80-6a37-11eb-8793-ca920ff68467.png)

**Comment by actual-nh** [comment]
> A similar issue occurs with teleport pads (and other teleports, such as magiclysm's phase door), which allows players to stand on top of whatever tile they want, for however long they want, including not only deep water tiles, but also air tiles.

Such without an "unsafe teleport" flag should really only put you over air or deep water if you're already over such in the original location, BTW.
