### ISSUE TITLE
Dragging furniture only works once, is let go of and message that it was destroyed shows up

### ISSUE THREAD

**Issue by ricardo2097** [CleverRaven/Cataclysm-DDA#47304]
# Describe the bug
Dragging furniture only works once, is let go off and message that it was destroyed shows up. After 11444, likely related with 
"Fix grabded furniture/vehicle destruction feature and tests for same" https://github.com/CleverRaven/Cataclysm-DDA/commit/a5db697aedf59a38635bba1f26e9b1df6676952d

# Steps To Reproduce

1. Grab a bench and drag it/push it
3. Bench is let go of (need to grab again) and message saying it was destroyed shows up

# Expected behavior

# Screenshots

# Versions and configuration

No mods, build 11444

# Additional context

**Comment by actual-nh** [comment]
Ping: @kevingranade?

**Comment by NoahGoldFox** [comment]
Is anybody working on fixing this?

**Comment by ricardo2097** [comment]
Disclaimer: I have no idea what I'm doing
I tried reverting the change in @@ -1356,7 +1356,7 @@ void map::furn_set( const tripoint &p, const furn_id &new_furniture )
back to         player_character.grab_point == p && !new_t.is_movable() ) {
and seems to be as before. Can drag furniture around without dropping it.
