### ISSUE TITLE
[Faction Camp] NPC can do another mission while already currently doing one

### ISSUE THREAD

**Issue by Saicchi** [CleverRaven/Cataclysm-DDA#47319]
# Describe the bug

Using the same NPC to do another faction camp mission while they are currently already doing one, will make the first mission unable to be completed.

# Steps To Reproduce

( Using save below )
1. Use any NPC to `Upgrade camp northeast bed`
2. While the mission is active, use the same NPC to `Upgrade camp northeast brazier`
3. Recall NPC when she is done with the brazier mission
4. Check the shack on the east, camp brazier is there but no bed.
5. Bed mission no longer in the bulletin board.

# Expected behavior

NPC that was used for `mission A` not being able to be used again in `mission B` until recalled from `mission A`.

# Screenshots
None

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.E-9419-g5146b8f10d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]
]

# Additional context

[Debuggia.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5940405/Debuggia.zip)

**Comment by UmbralReaper** [comment]
If you do this on the very first mission, the only way to get the option back is by abandoning and re-entering, which causes problems as in #47332.

**Comment by Saicchi** [comment]
After a few tests I found out that you can only select the same NPC if its assigned to the faction camp as a worker.
If they are following you the issue does not occur.
