### ISSUE TITLE
Duplicating anything with armor

### ISSUE THREAD

**Issue by KIDO13** [CleverRaven/Cataclysm-DDA#47326]
Duplicating armor by using the sort armor tab. Actually I can duplicate any items as well because any item in the bag gets duplicated as well. 

1. Wield an item.
2. Using the sort armor tab, equip any armor.
3. Get a drop wielded item message, and press Esc.
4. Get a error message, press space.

 I expected to equip the item without having to unwield wielded item, I mean like why do you even have to unwield your wielded item when you can just equip the armor without hindrances 

 - OS: Windows 7
 - Game Version: [0.E-9355-g203e8c9-dirty [64-bit]]
 - Graphics version: [Tiles]
 - Ingame language: [System Language]
 - Mods loaded: [    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Mythical Martial Arts [MMA],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP],
    My Sweet Cataclysm [my_sweet_cataclysm],
    My Sweet Cataclysm - UndeadPeople Tileset [My_Sweet_CataclysmUDP],
    Magiclysm [magiclysm],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    C.R.I.T Expansion Mod [crt_expansion],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Useful Helicopters [useful_helicopters],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Manual Bionic Installation [manualbionicinstall],
    Portable Autodoc [portable_autodoc],
    Fuji's Military Profession Pack [fuji_mpp],
    Clean CBMs [clean_cbm],
    Alternative Map Key [alt_map_key]]

**Comment by Sirbab** [comment]
Hey mate, you need to actually fill this out, not just write a title.  Also you made two of these.

**Comment by KIDO13** [comment]
yes i made a mistake

**Comment by KIDO13** [comment]
im new to making bug reports sorry

**Comment by PaulBlay** [comment]
> Duplicating armor by using the sort armor tab. 

There's a sort armor tab? *... hunts around ...* Hmm, 'Re-layer armor / clothing dialog box'. +

I never knew that was there.
