### ISSUE TITLE
Some gun mods cannot be installed despite the weapon being unloaded.

### ISSUE THREAD

**Issue by Quintovir** [CleverRaven/Cataclysm-DDA#47320]
# Describe the bug
The following gun mods cannot be installed despite meeting installation requirements and having an unloaded weapon capable of having them:
drop-in auto sear
firearm waterproofing
lightning link
match trigger

#47200 might be related.

# Steps To Reproduce

1. Wield an unloaded AR-15.
2. Try installing one of the gun mods mentioned above.

# Expected behavior

Gun mods should be allowed to be installed if you meet all requirements, including the weapon being unloaded.

# Screenshots

![1](https://user-images.githubusercontent.com/28264543/107163702-aaef5f80-6970-11eb-8826-6c437e668d6c.png)

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 20.2.1; Codename: Nibia; 
- Game Version: 0.E-9461-g0638fba7a9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]

# Additional context

N/A

**Comment by actual-nh** [comment]
Ping: @ToxiClay?

**Comment by ToxiClay** [comment]
...Oh goddammit. One second. I *might* know what happened. Give me just a minute to check.

**Comment by ToxiClay** [comment]
Removing the check on
```
&& ammo_remaining() > 0 || magazine_current()
```

causes the game to (improperly) return that message for all mods of type "mechanism" or "magazine."
