### ISSUE TITLE
Popup when clothing destroyed, such that items fall to the ground

### ISSUE THREAD

**Issue by Lazasar** [CleverRaven/Cataclysm-DDA#47334]
It is quite frustrating when the message that items tumble to the ground due to a backpack being destroyed gets lost in combat spam, and one doesn't notice till long after and there is no way to figure out where that incredibly rare item you just looted is.

Having an option in the settings that would create a modal pop-up (like "Are you sure") popup would be amazing.

**Comment by RadHazard** [comment]
As a less-intrusive alternative, what about a "____ destroyed!" indicator similar to the current damage indicators that pop up over your character?  Could apply to any clothing item, since generally I care when any of my gear breaks, not just the bags

**Comment by Lazasar** [comment]
Right, and it goes right past me. Especially when you are being hit by 3 zeds. I think inventory hitting the ground needs something much more obvious , at least for me.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
