### ISSUE TITLE
Wayfarer but for ranged weapons

### ISSUE THREAD

**Issue by tornikeo** [CleverRaven/Cataclysm-DDA#47337]
# Is your feature request related to a problem? Please describe.
It would be nice to have a defect that prevents survivor from using ranged weapons of every kind. Including guns, bows and throwing grenades. Playing as wayfaring churl is FUN. Really, it really forces you to think twice before engaging enemies and possibly ripping your precious (non-repairable, mind you) clothes. 

However.

The moment I get my hands on a gun with at least 15+ ammunition, the game ends for me. Why? Because I can wander around for a bit to find a group of soldiers and bleed them to death and obtain their gear. Then I get a rifle with a range of 60 tiles and so I can safely take out the mil-spec lights of a military outpost! If careful with moon phase, I also take out all the turrets and get the end-game load-out basically for no risk.

# Describe the solution you'd like
Please add a 3-4 point negative trait that prevents survivor from using ranged weapons. Bashing heads with M16 is still OK. A description can be "You accidentally shot and killed your loved one through a stack of books with a rifle in an attempt to to [gain popularity on YouTube](https://www.bbc.com/news/world-us-canada-43410816#:~:text=A%20US%20woman%20has%20been,his%20chest%20would%20shield%20him.) . This traumatic experience left you with a lifelong fear of bullets and rifles.". 

# Describe alternatives you've considered
Make all high-tier (non-civilian) guns have a [Judge-Dredd-esque](https://judgedredd.fandom.com/wiki/Lawgiver#Security_Features) security feature that bars the survivor from using it unless the survivor has an appropriate profession.

# Additional context
None.

**Comment by Jamuro-g** [comment]
not a fan of a trait that entirely blocks gun usage. imo it would pretty much mean that we have to ensure that everycurrent mob and future mob can be killed in melee.

Maybe a heavy morale penalty would suffice?
something like "- X Had to resort to using a cowards weapon."

**Comment by tornikeo** [comment]
Hey  @Jamuro-g, I've looked through the [design-doc](https://cataclysmdda.org/design-doc/#game-stages-and-timeline) for cataclysm, and nowhere does it mention that a survivor should be able to kill anything. I'm much more interested in a world where you always have to avoid at least something. I mean, the game is much more fun and engaging when I'm afraid for my life and have to run. [Some players](https://www.reddit.com/r/cataclysmdda/comments/ifovfi/wayfarer_has_made_this_game_interesting_for_me/) also like wayfarer trait like me, because it makes game challenging again. 
I think adding that trait would make my challenge run much more interesting.

**Comment by tornikeo** [comment]
@ZhilkinSerg Any pointers on how I could implement this would be much appreciated. Where are these traits even stored?

**Comment by Maleclypse** [comment]
>  Any pointers on how I could implement this would be much appreciated. Where are these traits even stored?

Starting traits are mutations in mutations.json that have the member "starting_trait": true.

**Comment by tornikeo** [comment]
Ok, got that down. Where is the "you refuse to take control of this vehicle" message just like a wayfarer does when pressing "^"? I could probably do the same for the "f" key.

**Comment by kevingranade** [comment]
Frankly I'd prefer to convert wayfarer into a conduct and remove it's point cost anyway. Then we simply detect violations instead of enforcing them.  Narratively it doesn't make sense to render a player *incapable* of driving or using ranged weapons.
