### ISSUE TITLE
Aftershock Cryo grenade does not explode once pin is pulled

### ISSUE THREAD

**Issue by Daved27hundred** [CleverRaven/Cataclysm-DDA#47346]
# Describe the bug

Cryo Grenade from the Aftershock mod does not explode once pin is pulled, simply remains "active" without any countdown

# Steps To Reproduce

1. Find or craft a cryo grenade
2. activate the grenade to pull the pin
3. grenade never explodes

# Expected behavior

Like most grenades, the cryo grenade should start a countdown before it explodes, giving you time to throw it.

# Screenshots

![image](https://user-images.githubusercontent.com/56202842/107289207-a8edd500-6a32-11eb-9770-3f988b394db2.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-9526-g599c1ea-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    No Rail Stations [No_Rail_Stations]
]

# Additional context

N/A

**Comment by Salty-Panda** [comment]
Did you activate it from inventory or while holding it?
If the former, does the problem still happens if you activate while wielding?

**Comment by Abstract-Note** [comment]
problem is in line 41 of grenades.json
      "target": "grenade_cryo",
needs to be:
      "target": "grenade_cryo_act",
also, the active version of the grenade weighs twice as much for no particular reason
