### ISSUE TITLE
[Magiclysm] Aura of protection doesn't spawn the aura

### ISSUE THREAD

**Issue by KorGgenT** [CleverRaven/Cataclysm-DDA#47355]
# Describe the bug

# Steps To Reproduce
try to cast the spell, it doesn't spawn anything.

# Expected behavior
spawning auras.

how to fix: make it have damage = 1
# Screenshots
![image](https://user-images.githubusercontent.com/30208401/107308279-59b99b80-6a56-11eb-9e2d-7bfe71754153.png)

# Versions and configuration

# Additional context

**Comment by actual-nh** [comment]
Since damage for the spawn effect is the number of things spawned?

**Comment by UmbralReaper** [comment]
Works as of `0.E-9442-ge9e4d33-dirty [64-bit]`. It still says `spawns 0 auras of protection`, but it spawns one anyway.

**Comment by KorGgenT** [comment]
huh. then i suppose the bug is the graphical part.

**Comment by Maleclypse** [comment]
I've removed the JSON label as I don't believe this can be fixed in JSON.

**Comment by KorGgenT** [comment]
sure it can. change the min and max damage to 1.

**Comment by actual-nh** [comment]
I believe Maleclypse is responding to your "the bug is the graphical part".
