### ISSUE TITLE
Mission takes too long to find a suitable location

### ISSUE THREAD

**Issue by Termineitor244** [CleverRaven/Cataclysm-DDA#47366]
# Describe the bug

When accepting the mission to go kill a Zombie (Horde) Master (From the generic missions of the generic npcs, after the "Kill the Jaberwock" and "Kill 100 Zombies" ones) the game takes a little more than 30 seconds to search for the place to put the Zombie Master, but the chosen place is not so far away to justify that time.

# Steps To Reproduce

1. Load the save attached to the report
2. Speak to the nearby npc
3. Accept the mission
4. See the massive slowdown (30 or so seconds in my computer)

# Expected behavior

To not see a slowdown so long that made me thought my game died? Specially if the location actually found is not **so** far away (It's always the same motel in the city to the north, I mean, it's not "close" but I do not expect the game to take 30 seconds to find something in that distance).

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-9532-g57d594e-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: Español (España) [es_ES]
- Mods loaded: [
    Dark Days Ahead [dda],
    Desactivar necesidades de los PNJ [no_npc_food],
    Profesiones Biónicas [package_bionic_professions],
    Estadísticas a través de las muertes [stats_through_kills],
    SpeedyDex [speedydex]
]

# Additional context

I found out 2 other bugs in this save, with this same npc, I will do 2 more reports about the others, but I will just use the same save (So no need to download it again to test the other issues).

Edit: Forgot the save 
[Spartanburg.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5949681/Spartanburg.zip)

**Comment by Venera3** [comment]
This mission is one of the few remaining ones that use hardcode instead of the modern mission infrastructure ( mission_start.cpp, Ln 89+ ). The reason for the hang was that it first searched the whole map for an office tower, and then took the (first) fallback option. It probably didn't get moved out of hardcode because it also needs to spawn a small horde for him to mingle in and/or sets the quest-giver to follow you.
