### ISSUE TITLE
Make free-standing plutonium generator usable

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#47370]
# Is your feature request related to a problem? Please describe.

One quite common encounter is the police road-block with two riot platforms, a couple of cars, a military searchlight and a plutonium generator. I think it would be cool if you could hookup the generator to vehicles to recharge batteries installed in them and power onboard equipment. This would be especially useful in Winter when solar panels don't provide much power. 

# Describe the solution you'd like

1. Obtain a heavy duty cable
2. (a)ctivate it and connect one end to a plutonium generator
3. (a)ctivate it and connect the other end to your vehicle
4. (Optional) Fire up the generator using your computing and applied science skills
5. (Optional) Experience a nuclear melt down at point blank range or
6. Enjoy your source of electrical power for the next decade or so.

# Describe alternatives you've considered

Leave as is.

# Additional context

I do not suggest that you should be able to learn the craft recipe for a plutonium generator by disassembling it.  However as they are (in theory) portable, possibly there should be some method of using a tool with lifting to place it into the cargo space of an adjacent HGV.

**Comment by PaulBlay** [comment]
Hah, I thought it would be controversial. I will point out that the "realism trumps gameplay" should apply not just for things that make gameplay harder. (You can see this with the large ammo drops from robots and turrets. They arguably damage game balance by making guns easier to supply). Those plutonium generators (probably RTG https://en.wikipedia.org/wiki/MHW-RTG ) are there to keep two riot platforms and one military search light supplied with power indefinitely. As well as boil coffee for policemen keep their cars warm. In real life 120kg of RTG can provide 470 watts power basically forever and are super reliable. This is 1970's tech.

**Comment by SariusSkelrets** [comment]
This a good idea but there’s still some points to clarify as the weight. How strong do you need to be to haul this back to home? Could you plug it in your electric car? How much power it provides?

But overall, the idea is interesting and i would like to haul that generator back home

(When NPC looting is  i can already see them killing each other for basically infinite energy)

**Comment by PaulBlay** [comment]
> This a good idea but there’s still some points to clarify as the weight. 

That isn't clear. But you can assume it would be 120kg at least. Could be as much as 400kg at a guess.

> How strong do you need to be to haul this back to home? 

Stronk. Too stronk. I can carry my dog upstairs (he's 28kg). Put it on wheels at least.

> Could you plug it in your electric car? 

On a permanent basis? Nuclear reactor powered cars were removed from the game as unrealistic (In CDDA you basically have modern tech + schizo tech. Nuclear powered cars is schizo tech). However on examining the numbers I think it's only more unrealistic than solar panels because a) People won't stand for radioactive material in their car (although RTG are super safe) and b) Plutonium is ridiculously expensive. You could certainly recharge your batteries from it.

> How much power it provides?

A standard solar panel in CDDA weighs 14kg and provides 50W. A RTG (as three of which were used in Voyager 1) weighs 38kg and provides 148W. This is literally 1970's tech so you would expect an improvement in heat energy conversion to power. In 1977 2400 W of heat generated converted into 140W. Modern technology has not achieved better than 10% so the maximum for similar weight / design would be 240W

**Comment by anothersimulacrum** [comment]
#46748

**Comment by l29ah** [comment]
There is (or was) a way to convert a fridge furniture to a vehicle-mountable one in Aftershock at least. I think the same way could be utilized to attach the generator to a vehicle. The power output may be adjusted based on game time to reflect plutonium decay.

**Comment by Maleclypse** [comment]
Closed by #59479
