### ISSUE TITLE
Add planks to travel rooftops

### ISSUE THREAD

**Issue by mawhingo** [CleverRaven/Cataclysm-DDA#47385]
Give the ability to construct a way to cross rooftop to rooftop without having to jump.  Like adding a plank across the gap or two.
So a player can live on rooftops and scavenge the city below.  

Ideally with Z levels active and a massive city it would give new game-play on urban living

**Comment by actual-nh** [comment]
Wires fixed to buildings with shuttle thingys (there's a rope variety, but I suspect wires would be preferable) to get back and forth? (And a negative trait of Acrophobia... as I have.)

**Comment by Salty-Panda** [comment]
You can put a plank over a deep pit ( which, basing on tile dimension is less than meter in diameter ).
Crossing a entire tile or even more than one would place a lot of stres on very flat thing like a plank.

You can construct folding bridge, deploy it over gap ( or before and push over it ), cross it, drag on the roof and fold back in.

**Comment by Fosheze** [comment]
> You can put a plank over a deep pit ( which, basing on tile dimension is less than meter in diameter ).
> Crossing a entire tile or even more than one would place a lot of stres on very flat thing like a plank.
> 
> You can construct folding bridge, deploy it over gap ( or before and push over it ), cross it, drag on the roof and fold back in.

I haven't tried it before but I believe you can already do that with a folding vehicle unless the mechanics have changed to not allow folding vehicles larger than 1 tile.

**Comment by Salty-Panda** [comment]
> I haven't tried it before but I believe you can already do that with a folding vehicle unless the mechanics have changed to not allow folding vehicles larger than 1 tile.

That's what I wrote. And folding multi-tile vehicles works fine, that's required to make that bridge

**Comment by Fosheze** [comment]
> > I haven't tried it before but I believe you can already do that with a folding vehicle unless the mechanics have changed to not allow folding vehicles larger than 1 tile.
> 
> That's what I wrote. And folding multi-tile vehicles works fine, that's required to make that bridge foldable

Ah sorry. I read that as adding a special folding bridge item.

**Comment by mawhingo** [comment]
Great that works, thanks for that :)
