### ISSUE TITLE
Crashes from layering menu

### ISSUE THREAD

**Issue by adamkad1** [CleverRaven/Cataclysm-DDA#47388]
# Describe the bug
Trying to ESC from a equip menu in layering menu crashes game. Might apply to some other submenus too

# Steps To Reproduce
1-go to layering memu (default + i think)
2-press e to equip armor from inventory
3-press ESC
4-game commits yeet

# Expected behavior

the game quits the submenu instead of crashing

# Game info
Tested in dda only world
Ver 1.B build 11450

**Comment by BrettDong** [comment]
Could you attach a save? I tried in 034ac1589c but the game does not crash for me.

**Comment by actual-nh** [comment]
#47394 - possibly confirmed.
