### ISSUE TITLE
Add "filthy" flag to spawned water, remove "clean water"

### ISSUE THREAD

**Issue by Fosheze** [CleverRaven/Cataclysm-DDA#47380]
# Is your feature request related to a problem? Please describe.
During the whole dirty fuel problem I realized that flags could be added to liquids. Rather than having 2 separate items for water it would make sense to just have all water spawn with the "filthy" flag and remove that flag when you clean it. This would also open the door to easily adding other flags such as "muddy" swamp and puddle water so that people can no longer boil their pasta in swamp muck. This would be similar to the switch from having bloodied rags spawning to having rags with the "filthy" flag spawning at the random combat sites. 

# Describe the solution you'd like
Have water spawn with the "filthy" flag. Remove clean water as an item. Change the effects from drinking dirty water so that they look for the flag instead.

# Describe alternatives you've considered
-Spawn all water as normal water and simply add a "clean" flag to cleaned water.
-Not doing any of this because it's probably way to heinously complex for what little benefit it would have.

# Additional context
As stated above I'm sure water is linked into a lot of areas in the game so I don't imagine that this would be an easy change. I'm also not sure how well the crafting system interacts with the flag system. I know there have been issues before with certain crafts/actions deleting flags. The flags would also need to be displayed in the crafting screen somehow so the player knows that they aren't re-boiling their already clean water.

**Comment by ZhilkinSerg** [comment]
See #72

**Comment by RadHazard** [comment]
Before this goes in, the crafting interface will need to be updated to handle items with identical IDs but different flags/qualities better.  At the moment, the only way to ensure crafting uses the right item is to manually put what you want to use in your inventory and dump the other items.

**Comment by Fosheze** [comment]
> See #72

Thank you for the link. I was wondering why no one had thought of this before. Turns out they had I'm just 8 years late.

**Comment by actual-nh** [comment]
> Thank you for the link. I was wondering why no one had thought of this before. Turns out they had I'm just 8 years late.

Well, it hasn't been fixed yet...

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
