### ISSUE TITLE
Flying enemies never path downwards, don't attack when boxed in

### ISSUE THREAD

**Issue by Venera3** [CleverRaven/Cataclysm-DDA#47381]
# Describe the bug

Even with experimental Z-levels on, flying mobs above the player won't path down to chase/attack even when they have vision on them. In addition, flying monsters that are "boxed in" on their own Z-level but are otherwise unimpeded won't ever attack from above. 

# Steps To Reproduce

1. Download the provided folder ( save file with the setup and a debug terrain) and open the save with Z-level vision turned on
2. Each tar roof around the character corresponds to a wasp above, with different configurations of the surrounding terrain
3. Note lack of attacks on the left column, contrast with attacks on the lower two of the right column
4. Stand on the upmost tar tiles, note that the wasps two levels  above have vision on the character, but still don't come closer

# Expected behavior

Flying monsters being unbothered by the terrain on their level, and them showing a bit more engagement in chasing their dinner down.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-9535-g1ffe34c-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

The extra terrain is tangential and was me testing an unrelated thing, but I didn't want to rebuild the whole structure again.
Configuration of the wasp cells, from the left upper corner:
- Wasp boxed in, on Z+2,
- Wasp with a single pathable tile next to it, Z+2
- Wasp boxed in on Z+1, debug air below
- Wasp with a pathable tile on Z+1, debug air
- Wasp boxed in on Z+1, open air below
- Wasp with a pathable tile on Z+1, open air below

[ZLEVEL.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5953901/ZLEVEL.zip)

**Comment by actual-nh** [comment]
pathfinding.cpp does not appear to handle flying monsters/NPCs in terms of moving between Z-levels - it only has going up and down if the terrain allows (in both `vertical_move_destination` and `route`). The only difference is that flying monsters can ignore (most?) terrain costs.

**Comment by Venera3** [comment]
It just not being supported yet was my first hunch, but I know for a fact that turkeys can flee up to Z+1, so there must be some code in there handling that.

**Comment by actual-nh** [comment]
> It just not being supported yet was my first hunch, but I know for a fact that turkeys can flee up to Z+1, so there must be some code in there handling that.

Huh. I will have to take a closer look - probably Thursday, unfortunately (lab tomorrow + grading to do that I'm admittedly procrastinating on...).

**Comment by Venera3** [comment]
All good, this is mostly just me setting up a reproduction save for whenever someone takes a look at cross-Z level interactions, which I don't think will happen in the near future (unless it also messes with normal pathing, but I didn't notice that).
