### ISSUE TITLE
Sort armor for NPC: Impossible to equip something from the player's inventory

### ISSUE THREAD

**Issue by Termineitor244** [CleverRaven/Cataclysm-DDA#47397]
# Describe the bug
When you sort armor for an NPC, and press "e" (currently crashed) or "E" to "Equip armor from inventory", you are not prompted with the option to equip anything from your inventory. 
Another issue has already been filled for the crash that happens when you do equip her with something from the ground (#47394)

# Steps To Reproduce

1. Load the attached save
2. Sort armor for the NPC
3. Press "e" or "E"
4. See no option to equip the armor from your inventory (As is the name of the function)
5. Cry

# Expected behavior

To be able to equip something to the NPC that is in your inventory (I did not see if you are able to do it with something from the NPC's inventory, but still).

# Screenshots

Inventory:
![imagen](https://user-images.githubusercontent.com/53200489/107450909-d78bae80-6b0b-11eb-9d87-b5272a0e9e5b.png)
Menu to equip from inventory to the NPC:
![imagen](https://user-images.githubusercontent.com/53200489/107450982-fab65e00-6b0b-11eb-9acf-cd7205af0e89.png)
Menu to equip from inventory to the player:
![imagen](https://user-images.githubusercontent.com/53200489/107451049-1d487700-6b0c-11eb-8ef8-0831c4fe4e26.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-9532-g57d594e-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: Español (España) [es_ES]
- Mods loaded: [
    Dark Days Ahead [dda],
    Desactivar necesidades de los PNJ [no_npc_food],
    Profesiones Biónicas [package_bionic_professions],
    Estadísticas a través de las muertes [stats_through_kills],
    SpeedyDex [speedydex]
]
# Additional context

Sixth report in three days.
Edit:
Save:
[Spartanburg.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5955299/Spartanburg.zip)

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
