### ISSUE TITLE
Crash when exiting "Equip armor from inventory" (Sort armor) +1 other related crash

### ISSUE THREAD

**Issue by Termineitor244** [CleverRaven/Cataclysm-DDA#47394]
# Describe the bug

If you sort armor for yourself or an NPC, and you press "e" to "Equip armor from inventory" and then exit the menu, the game crashes and gives you a segmentation fault, its worth noting that this crash does not occurs when you use "E" (Equip armor from inventory at this position).

# Steps To Reproduce

That the game doesn't crash.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-9532-g57d594e-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: Español (España) [es_ES]
- Mods loaded: [
    Dark Days Ahead [dda],
    Desactivar necesidades de los PNJ [no_npc_food],
    Profesiones Biónicas [package_bionic_professions],
    Estadísticas a través de las muertes [stats_through_kills],
    SpeedyDex [speedydex]
]

# Additional context

Save:
[Spartanburg.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5955165/Spartanburg.zip) (4 bugs/crashes already found with this world/save, +1 from a failed attempt, I'm on fire)
Logs:
[log files.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5955190/log.files.zip)

Edit: The crash continues... 
New report:
In the same save as provided above:
The game crashes with "E" too if you try to equip the NPC with anything (I tried with a gun and some clothes that I dropped to where she is), that I cannot even try to equip her with something from my inventory should be a bug too, preparing another report... (In other news, this other report will be my sixth in just 3 days!)

**Comment by actual-nh** [comment]
#47388 - same/related?

**Comment by BrettDong** [comment]
I am unable to reproduce the crash when equipping NPC with armours. I loaded the save and equipped the NPC the guns on the ground and it works fine.

**Comment by Termineitor244** [comment]
Weird, In my machine it crashes perfectly fine.
![imagen](https://user-images.githubusercontent.com/53200489/107453273-4834ca00-6b10-11eb-9d2d-f6b098117c51.png)
This is with the mayus "E", I'm pretty sure

**Comment by adamkad1** [comment]
> I am unable to reproduce the crash when equipping NPC with armours. I loaded the save and equipped the NPC the guns on the ground and it works fine.

Thats because yer supposed to not equip the npc to crash

**Comment by Termineitor244** [comment]
> 
> 
> > I am unable to reproduce the crash when equipping NPC with armours. I loaded the save and equipped the NPC the guns on the ground and it works fine.
> 
> Thats because it happens when you dont equip . If you equip something, no error happens

Aghhhhh no? I have the following issues:
1._ When using the sort armor function, and pressing "e" (lowercase), the game crashes after exiting the prompted menu.
2._ When using the sort armor function **in the NPC**, and pressing "E", if I try to equip something to the NPC, the game crashes too, but if I exit the menu without doing anything, no crash happens
BUT! I just found out that if I previously equip the NPC with a Bra (via chat), and then try to equip something with sort armor, the game **does not crash!**
