### ISSUE TITLE
Isherwood Family Dairy Farm has Zombie Cows

### ISSUE THREAD

**Issue by CptCodpiece** [CleverRaven/Cataclysm-DDA#47393]
The Isherwood Family dairy farm can spawn all zombified cows in the dairy cow pens. 

It's pretty unlikely for Eddie Isherwood to be spending time tending to zombified cows that will murderhobo him. Add to it that the zombified cows can be safely put down by throwing rocks at them from the outside (Zombie Cows won't break fences. Not sure about the evolution variant.) and that the Isherwoods seem to have lots of crossbows, I don't think it's very likely that zombified cows would take over the dairy cow pens. At least they'd recognize there's a problem and not allow a total takeover.  

#Steps to reproduce the behavior:

Create a new world and debug in the Isherwood overmap special until you get a zombie cow variant.

# Expected behavior

The Isherwood Family to not be raising undead battle cattle and to be raising regular dairy cows. I expect this to happen because people like to not have a zombie cow horn in their butt. If a zombie cow were to die and raise overnight and kill all the other cows, at the very least the offending undead cow would have been put down and the rest of the dairy cows would be butchered. Or failing that, the eventual other resulting undead cows would be shot from the safety of the fences.

# Screenshots

![image](https://i.imgur.com/yAgipwN.png)

# Versions and configuration

 - OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-9533-g8cad4da-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

The splotches and tainted fats were from dismembering cows. I didn't think to take a picture of proof until partway through.

**Comment by actual-nh** [comment]
This will be particularly problematic when/if #47395 goes in.
