### ISSUE TITLE
Manual labor makes you sleepy

### ISSUE THREAD

**Issue by RadHazard** [CleverRaven/Cataclysm-DDA#47391]
# Describe the bug
Certain manual labor tasks like mining with a pickaxe or chopping logs make the player sleepy.  This is most likely leftover behavior meant to simulate weariness from before actual weariness was implemented.

# Steps To Reproduce
1. Debug in a chainsaw
2. Spend half a day chopping up a bunch of logs
3. Observe that you're really sleepy even though it's only noon.

# Expected behavior
Manual labor makes you extremely weary but isn't so boring that it makes you want to fall asleep

# Versions and configuration
- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.2 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-9545-g034ac1589c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context
The relevant code is in `activity_handlers.cpp`.  Numerous activities call `p->mod_fatigue()` which increases sleepiness rather than weariness.  Gaining weariness is handled automatically by activity levels so most of these calls can probably just be removed entirely.  Calls to `mod_thirst()` and `mod_stored_nutr()` should similarly be audited as well.

**Comment by anothersimulacrum** [comment]
Yeah, it'd probably be appropriate to remove all those direct stat modifiers.

**Comment by s7eamy** [comment]
hey, i'm quite new, but i'd like to attempt to solve this issue, can i? also, does 
> Calls to mod_thirst() and mod_stored_nutr() should similarly be audited as well.
mean that  mod_thirst() and mod_stored_nutr() should be removed too?

**Comment by anothersimulacrum** [comment]
Yep, go ahead. I'd say remove them, we have other systems to deal with it.

**Comment by actual-nh** [comment]
For `pickaxe_finish`, should mod_pain be removed as well? I'm thinking only have it for those without `trait_STOCKY_TROGLO`, to keep their advantage in digging through rock.

Note that the various modifiers in `spellcasting_finish` (and `blood_magic` right above it) should not be removed (probably not at all, and definitely not without further discussion).
