### ISSUE TITLE
Add e-books for your e-ink PCs (and optionally laptops)

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#47402]
# Is your feature request related to a problem? Please describe.

The recipes you occasionally find in SD cards and science SD cards are an interesting idea, but confusingly implemented. I'm never quite sure how to use them and there are so few found (in my experience) that I've never felt the need to work it out. I suggest that entire e-books should be (sometimes) found on SD cards and possibly USB drives.

# Describe the solution you'd like

e-ink PCs and optionally laptops can have both e-books and individual recipes stored on them. e-ink PCs and optionally laptops can be left running (just turn on like flashlights) and you will automatically be able to use any recipes in them as long as they are nearby and you meet the other crafting requirements. You should also be able to improve skills by reading e-books in the same way you can by reading paper books. Crafting/reading would be interrupted if the battery runs flat while you are using them, with an appropriate warning message.

e-book drops (inside SD-cards / USB drives) would need to be considered. Probably not all books would have e-book equivalents, possibly there should be some e-books that do not have paper book equivalents.

# Describe alternatives you've considered

Leave as is.

# Additional context

e-book usage would be both realistic (whisper it, but I think e-ink PCs are secretly Kindles) and would be much easier to transport than dozens of paper and hardbacks.

**Comment by PatrikLundell** [comment]
Getting companions to read books on a computer may be a tricky complication (which should not be taken to mean the suggestion is bad).

**Comment by PaulBlay** [comment]
Good point. I haven't made much use of companions (yet) so that didn't occur to me. How do you get them to read physical books? Just throw one in their inventory and give them an order?

**Comment by PatrikLundell** [comment]
I've done it that way, but I believe you can point them at a book in the vicinity. However, a computer may have multiple books in it, so you'd need a way to select which one you want (for yourself or a companion). Also, a single computer should only be usable by a single character (but logically you should be able to copy everything to multiple computers, although that's not supported currently).

My experience from 0.E2 stable was that using companions is an efficient way to train if you've got the books for it. Set each companion to master one field and then have them teach you about twice per day per companion, while you also read (other) books on your own. You also need the companions trained up to perform various camp tasks, as they have minimum requirements, and some get better results with better trained companions (e.g. foraging, and I think the fighting/patrolling tasks give them better chance of surviving the better trained they are).

**Comment by PaulBlay** [comment]
> Also, a single computer should only be usable by a single character

Hmm, are other tools currently 'single character locked'? Like if you have one hacksaw, can you only assign one companion to cutting up cars? Not that I'm disagreeing with you, just wondering if it's a more general issue.

**Comment by PatrikLundell** [comment]
Companions should go and pick up the tools they need for a job, and so they should be limited to be used by a single character. However, since that seemed flaky (in particular returning the tools afterwards), I've equipped each companions with the set of tools needed. Base camp construction is capable of using welders out of the resource store, though, but in that case the companion is teleported away and the task is performed in that abstract elsewhere space, not in the physical camp.

**Comment by PaulBlay** [comment]
Well, my first suggestion would be that e-ink PCs and laptops should be treated as a special case of container where the contents (e-books and software) are only viewable when they are turned on. You can presumably point to a book in a bag, so you could equivalently point to an e-book in an e-ink PC. You would probably require the character to have the e-ink PC / Laptop in their inventory, wielded or possibly also allow the alternative of being on a table-surface adjacent to the character.

Copying between e-ink PCs and laptops of recipes, music and e-books seems like a good idea. Although that does raise the spectre of some or many books being protected from being copied. There are programs lurking on the Internet that apparently remove digital right management from ebooks, so I guess said programs could be a possible 'drop' on a SD card, science SD card or USB Drive.

Also, we should probably be finding a bunch of random crap on Laptops / e-ink PCs you find (if they are not password protected / locked or if you can break the protection).

All this sort of stuff would require various levels of computing skill to carry out and would, conveniently, provide a much needed avenue to train your computing skill.

**Comment by Saicchi** [comment]
I was already working on this around two months ago, its mostly done, but I need `ACT_READ` to be refactored into an `activity_actor` to progress; #46304 which I'm certain won't be merged until 0.F.
