### ISSUE TITLE
Why not working Laptops?

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#47401]
# Is your feature request related to a problem? Please describe.

As is well known, every single laptop you find is broken. Despite this, the crafting recipes for Turret control unit and Coilgun require a laptop as a tool.

# Describe the solution you'd like

Some or all laptops should be functional. At a basic level they would just function as a heavier e-ink PC that uses more battery charge to run. Later you might give them additional functionality via USB drive programs and / or SD card content. For example hacking security card locks, controlling robots etc. Laptops, with speciality hardware additions, could also replace some unique quest items (like the mind-ripper tool).

# Describe alternatives you've considered

Require an e-ink PC instead of Laptop in the above recipes because every laptop computer is broken.

# Additional context

**Comment by Salty-Panda** [comment]
Laptops work on experimental.

**Comment by PaulBlay** [comment]
> Laptops work on experimental.

They do? They didn't last I checked on experimental - but that was a while back. Lol.

> Controlling robots was moved from vanilla to Aftershock.

Ditto.

> Hacking uses separate item/CBM.

It does now, yes. The electrohack. Has a crafting recipe with a rather ridiculously low skill requirement of computing 1, electronics 4. I think it would be more realistic if it was a peripheral that needed to be attached to a Laptop for a sensible amount of processing power and ease of programming. USB drives sometimes drop with HackPro (reading google results) formerly required for Control Laptop crafting. 

Anyway, closing this because I was working off my memory before everything changed.

**Comment by Zireael07** [comment]
> Has a crafting recipe with a rather ridiculously low skill requirement of computing 1, electronics 4. I think it would be more realistic if it was a peripheral that needed to be attached to a Laptop for a sensible amount of processing power and ease of programming. USB drives sometimes drop with HackPro (reading google results) formerly required for Control Laptop crafting.

IMHO worth doing.
