### ISSUE TITLE
Low effort electrohack rethink

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#47407]
# Is your feature request related to a problem? Please describe.

The electrohack device can be crafted with computing skill 1 and electronics skill 4. This seems far too low. I also think it would need more processing power than you can get from one processing board probably ripped out of a car's security system.

Computing 1 is roughly "Can use Google, may be able to download mp3 files from the Internet (when it existed) without getting viruses". Electronics 4 is a bit rougher to define, but it's what you need to make thermal socks that don't catch fire or a radio controlled boom switch for a grenade.

# Describe the solution you'd like

I would suggest that the electrohack should be considered as a computer peripheral - requiring a laptop computer or possibly e-ink PC running hackPro to use. Simply use as before, but when you (a)ctivate the electrohack it checks for laptop (lit screen) and hackPro nearby.

I would also suggest that there could be an auto-learn crafting recipe for hackPro at computing skill 5 (so you don't entirely rely on USB drive dropping with hackPro installed).

# Describe alternatives you've considered

Just increase skill requirements a bit.

# Additional context

When you craft hackPro you would need a laptop (or possibly e-ink PC) and the resulting software should be contained in said computer.

**Comment by actual-nh** [comment]
What about the fingerhack?

**Comment by PaulBlay** [comment]
> What about the fingerhack?

I'd leave it alone. You can't craft it from bits, and bionics is on the 'schizo tech' side of things anyway.
