### ISSUE TITLE
有新鲜度的液体，新鲜度不同不能倒一个容器里

### ISSUE THREAD

**Issue by chuizhi** [CleverRaven/Cataclysm-DDA#47408]
Version 11454, exotic bug, or setting? The freshness of the liquid is different. It can not be poured into a container.
For example, after milking one cow, the second one can't be milked. The newly milked milk can't be put in the previous milk container.
But if it freezes in the refrigerator for a while, it will do.
There's also blood.
=========================
版本11454，奇葩的BUG，或者是设定？有新鲜度的液体，新鲜度不同不能倒一个容器里。
比如牛奶，挤完一头牛，再挤第二头，不行，新挤出的牛奶不能放在之前装牛奶的容器里。
但是如果在冰箱里冻一会就可以了。
同样的还有血液。

**Comment by Fosheze** [comment]
This is likely related to #47148, #46786, and #46470.

**Comment by chuizhi** [comment]
> This is likely related to #47148, #46786, and #46470.

thank you
