### ISSUE TITLE
Metabolic Rehydration does not work

### ISSUE THREAD

**Issue by coon58** [CleverRaven/Cataclysm-DDA#47400]
# Describe the bug

Thirst still goes up, dispite having the mutation "Metabolic Rehydration"

# Steps To Reproduce

Just wait and see the thirst go up.

# Expected behavior

Thirst wont go up with "Metabolic Rehydration", since the mutation normaly removes the thirst requirement.

# Screenshots
![thirst2](https://user-images.githubusercontent.com/41000583/107479424-5d930e00-6b7b-11eb-9ad5-8f0edac2cada.PNG)
![thirst1](https://user-images.githubusercontent.com/41000583/107479446-67b50c80-6b7b-11eb-8eba-ad29129fabe9.PNG)

# Versions and configuration

 - OS: Windows 10.0 2004
 - Game Version: 0.E-9545-g034ac15-dirty [64-bit]
 - Graphics version: Tiles
 - Ingame language: English [en]
 - Mods loaded: Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]

# Additional context

**Comment by ZhilkinSerg** [comment]
`NO_THIRST` flag is missing in `NO_THIRST` mutation definition.
