### ISSUE TITLE
Kel-Tec KSG & KSG-25 Shotguns - Sight Dispersion = 500?

### ISSUE THREAD

**Issue by MobiusOblidus** [CleverRaven/Cataclysm-DDA#47414]
# Describe the bug

The Kel-Tec KSG and Kel-Tec KSG-25 shotguns both have an extremely high base Sight Dispersion stat of '500'.

# Steps To Reproduce

1. Use Debug to spawn a Kel-Tec KSG or Kel-Tec KSG-25 shotgun
2. Inspect the spawned gun, see the Sight Dispersion stat of '500'

# Expected behavior

Most ranged firearms have a Sight Dispersion of around 30 with Iron Sights.

# Screenshots

![Kel-Tec KSG - 500 Sight Dispersion](https://user-images.githubusercontent.com/76887621/107571104-57844800-6be2-11eb-9ae0-b7991779c116.png)
![Kel-Tec KSG-25 - 500 Sight Dispersion](https://user-images.githubusercontent.com/76887621/107571106-594e0b80-6be2-11eb-8eab-be95b161d7a9.png)

# Versions and configuration

- OS: Windows
    - OS Version: Windows 10.0 2004
- Game Version: 0.E-9555-gfe798ae-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language [UK English]
- Mods loaded: [
    Dark Days Ahead [dda],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
]

# Additional context

N/A

**Comment by LaVeyanFiend** [comment]
The KSGs only have a Picatinny rail on top unless you add a sight on top, which is the intended method of use. The sight dispersion is intended.
![image](https://user-images.githubusercontent.com/51099123/107571818-699dc080-6bb9-11eb-8dfa-b2f8b4189e6a.png)

**Comment by Salty-Panda** [comment]
Adding any sight lets you easily reduce it to 40 or less which is more than enough for a shotgun.

**Comment by MobiusOblidus** [comment]
It's good that adding a sight mod can easily reduce the Sight Dispersion of the KSG & KSG-25 - but that still requires skills, materials, & time.

The player needs Fabrication 2 and Marksmanship 3 to crafty an Iron Sight.
They then need Marksmanship 1 and Shotguns 2 to attach an Iron Sight mod to a KSG.
It then takes about 6 minutes in game to attach the Iron Sights if you have the requisite skills - not great if you find a KSG when in imminent danger.

The base Sight Dispersion being 500 still feels extremely high.

As a comparison, all Pipe firearms in the base game, as well as all Flintlock firearms have a base Sight Dispersion of 30.

Is it imagined that every one of these has an in-built Iron Sight? 

Having fired several flintlock weapons in real life, I can attest that this is absolutely not the case (Blackpowder-Bandits-4-Lyf!). Some have a 'pip' foresight, which makes true aiming quite difficult, but few ever also had rearsights. 

So if the KSGs Sight Dispersion is intended, why is it more than 16 times worse than all Pipe & Flintlock firearms - which probably shouldn't automatically have Iron Sights?

Even the M134 Minigun in game has a Sight Dispersion of 30 - apparently denoting Iron Sights. Many M134s do not have Iron Sights attached unless they are crew operated, and even then many of them still don't. Ones attached to vehicle exteriors and fired automatedly would be very unlikely to have attached sights.

![Special_forces_gatling_gun-1](https://user-images.githubusercontent.com/76887621/107684312-8cec6c80-6c9a-11eb-89bb-7a33fe4c915e.jpg)

**Comment by Quintovir** [comment]
"Optics ready" guns AKA "guns sold without any sights/optics" and bolt action rifles that are found at gun shops and similar locations where these guns would be sold as brand new should be very unlikely to have an optic installed on them (maybe the odd display sample might have an optic installed on it).

Some guns that can be found as "Optics ready" would be:
Remington 700 .30-06
Savage 111F
AR-15 (it seems to me that optics ready ones outsell ones with iron sights/backup iron sights)
AR-10 (it seems to me that optics ready ones outsell ones with iron sights/backup iron sights)
Weatherby Mark V
Winchester Model 70
Remington 700 .270 Win
FN P90 (It's only sold to LE & military so you shouldn't find them in gun stores. It looks like they don't come with factory iron sights. The FN PS90 is the civilian version and it does come with iron sights)
https://fnamerica.com/products/rifles/fn-p90/
https://fnamerica.com/products/rifles/fn-ps90-standard/
Barrett M107A1 (Can be found at a gun store. It does come with iron sights. If found in a gun store it should almost always be found without an optic.)
Serbu BFG-50 (Can be found at a gun store. It's "optics ready". If found in a gun store it should almost always be found without an optic.)

I think that at a minimum any "Optics ready" gun should have at least if not better dispersion than any bow (crossbows?) with no sights installed.

If the above guns are found in the wild or places where they would be sold as used (pawn shops? Can you even find guns in CDDA's pawn shops?), they should almost always have some kind of iron sights/backup iron sights and/or optic installed. The guns listed above that are found in gun safes might be slightly more likely to be found without any backup iron sights and/or optic.
