### ISSUE TITLE
A Magiclym skill-book to allow NPC to level spellcraft

### ISSUE THREAD

**Issue by Salty-Panda** [CleverRaven/Cataclysm-DDA#47417]
# Is your feature request related to a problem? Please describe.
There is no book that levels spellcraft and isn't a spellbook or a scroll.
There are recipes that could use NPC help ( dragon crafts, so looong ) but they can't help because have no spellcraft and they can't level it.

# Describe the solution you'd like
A few books that offer no spells, just magical theory so NPC can read them

# Describe alternatives you've considered
NPC can read scrolls and learn spellcraft, but no spell.s

**Comment by Maleclypse** [comment]
So if I were making this book I would make it with insanely long training times so that it would not make sense for players to read it as it would be faster to learn spells that level spellcraft.

**Comment by Salty-Panda** [comment]
Not sure what you mean?
You can start reading Translocation with 0 spellcraft and it can bring you to 10 spellcraft easily.
Spells seem to be a superior option even with the same learning rate since such a book would not give any spell.

**Comment by Maleclypse** [comment]
I'm saying that I would make it a punishing read for the PC but something you could totally send an NPC off to do for a day.

**Comment by actual-nh** [comment]
Linked pull request is 0.F String Freeze.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
