### ISSUE TITLE
Skill training overflow

### ISSUE THREAD

**Issue by Jninja1** [CleverRaven/Cataclysm-DDA#47413]
After I got back from a raid I tried to read First Responders Handbook. When I began to read it, the progress was at roughly -60,000

# Steps To Reproduce

Unfortunately, I am unsure of what caused the issue. After I got home from a lab raid I put my loot up and began to read. My focus was close to 20.  

# Expected behavior

I expected a dialogue box to pop up that stated "Healthcare 5-> 6 40%". Instead I got, "Healthcare 5-> 6 -60000%". I expected the former because that has always been how skill training behaves.

# Screenshots

# Versions and configuration

[Laketown - Copy.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5960578/Laketown.-.Copy.zip)

**Comment by BrettDong** [comment]
Probably have been fixed by #47191.
