### ISSUE TITLE
Clay walls don't make roofs.

### ISSUE THREAD

**Issue by chuizhi** [CleverRaven/Cataclysm-DDA#47427]
I make clay bricks from animal manure and soil in the game, and then build a house with clay bricks.
Finally, the exterior walls were finished (Figure 1), and I began to add metal roofs to the house.
And then found - closed doors and windows, the house is also bright!
Use a ladder to climb up and have a look. The space where windows and doors are installed will automatically generate a roof on the second floor. Clay walls don't. (as shown in Figure 2)
It seems to be the same reason that the metal wall warehouse in the big map building "apple garden" is the same.
This bug is too bad. I spent a summer and a spring in the game making clay bricks and building a house. As a result, the roof of the house is leaking?
The above is Baidu translated into English, the following is the original Chinese
我在游戏用动物的粪便和泥土做成粘土砖，然后用粘土砖盖房子。

终于，外墙完成了（如图1），我开始给房子加上金属屋顶。
![1](https://user-images.githubusercontent.com/59391871/107657984-a99b9b00-6cc0-11eb-8c84-c924d835b17e.jpg)

然后发现——关上门窗屋里也亮堂堂的！
用梯子爬上去一看，安装窗户和门的那一格，会在二楼自动生成屋顶。而粘土墙则不会。（如图2）
![2](https://user-images.githubusercontent.com/59391871/107658017-b1f3d600-6cc0-11eb-841c-da8396f89e87.jpg)

好像是同样的原因，大地图建筑“苹果园”里的金属墙仓库也是这样。
这个BUG太糟糕了，我在游戏里花了一个夏天+一个春天做粘土砖，建房子，结果房子顶是漏的？

**Comment by Rjtheperson** [comment]
I had a similar issue with wooden walls and one of the developers told me to save and quit, then load the game again. I don't know if it will work for your clay walls but it is worth trying.

**Comment by chuizhi** [comment]
> I had a similar issue with wooden walls and one of the developers told me to save and quit, then load the game again. This worked for me. I don't know if it will work for your clay walls but it is worth trying.

Thank you! But I tried and still couldn't. Ready to debug the roof. Because it's been covered for a long time, it's impossible to push it over and start over.

**Comment by actual-nh** [comment]
> > I had a similar issue with wooden walls and one of the developers told me to save and quit, then load the game again. This worked for me. I don't know if it will work for your clay walls but it is worth trying.
> 
> Thank you! But I tried and still couldn't. Ready to debug the roof. Because it's been covered for a long time, it's impossible to push it over and start over.

Covered for a long time? (@BrettDong: There may be a linguistic issue here; could you help, as you've done before?)

**Comment by chuizhi** [comment]
> > > I had a similar issue with wooden walls and one of the developers told me to save and quit, then load the game again. This worked for me. I don't know if it will work for your clay walls but it is worth trying.
> > 
> > 
> > Thank you! But I tried and still couldn't. Ready to debug the roof. Because it's been covered for a long time, it's impossible to push it over and start over.
> 
> Covered for a long time? (@BrettDong: There may be a linguistic issue here; could you help, as you've done before?)

I have spent three years (91 days a season) in this archive. From the next summer, I began to make clay bricks from the dung of cattle and the soil I dug out to strengthen the base, and then built a new house.
The time to build a house in the game is one summer and one spring (in autumn and winter, I drive out to search for supplies).
In reality, this archive has been playing since the summer vacation of 2020.
My home
![360截图20210212225352197](https://user-images.githubusercontent.com/59391871/107783537-57707d80-6d85-11eb-8cf9-45f4cced9967.jpg)
我这一个存档，游戏里已经度过3年了（91天一季）。我从第二年夏天开始用饲养的牛的粪便，和我加固基地挖出的泥土制作粘土砖，然后修建一座新的房子。
建房子的时间在游戏里是一个夏天一个春天（秋天和冬天我开车出去搜刮物资）。
现实中这个存档大概是从2020年暑假开始玩到现在的。

**Comment by aerrant** [comment]
There's certainly a bug: roof generation isn't handled during terrain construction (see [`complete_construction()`](https://github.com/CleverRaven/Cataclysm-DDA/blob/cbcfab179d4e7e7f715e21d44816d1bee1132868/src/construction.cpp#L1073), so the roofs are only ever generated during the map load (see [`map::add_roofs()`](https://github.com/CleverRaven/Cataclysm-DDA/blob/cbcfab179d4e7e7f715e21d44816d1bee1132868/src/map.cpp#L7375) method). The fix is obvious, I believe.

If you've been paying attention, you may wonder why the roofs weren't regenerated already. This is because the stable 0.E branch has had another bug that is already fixed: the z-levels support switch is read from the options even though z-levels are no longer optional and the option is removed from the menu (see `0.E` [`game::setup()`](https://github.com/CleverRaven/Cataclysm-DDA/blob/cb02195d9fb5ba71f35a105be4104c3d8883065c/src/game.cpp#L623) and `master` [`game::setup()`](https://github.com/CleverRaven/Cataclysm-DDA/blob/cbcfab179d4e7e7f715e21d44816d1bee1132868/src/game.cpp#L608)).

Will do a PR shortly.

@chuizhi This is a software error: hopefully it'll be fixed with the `0.F` release.

**Comment by chuizhi** [comment]
> There's certainly a bug: roof generation isn't handled during terrain construction (see [`complete_construction()`](https://github.com/CleverRaven/Cataclysm-DDA/blob/cbcfab179d4e7e7f715e21d44816d1bee1132868/src/construction.cpp#L1073), so the roofs are only ever generated during the map load (see [`map::add_roofs()`](https://github.com/CleverRaven/Cataclysm-DDA/blob/cbcfab179d4e7e7f715e21d44816d1bee1132868/src/map.cpp#L7375) method). The fix is obvious, I believe.
> 
> If you've been paying attention, you may wonder why the roofs weren't regenerated already. This is because the stable 0.E branch has had another bug that is already fixed: the z-levels support switch is read from the options even though z-levels are no longer optional and the option is removed from the menu (see `0.E` [`game::setup()`](https://github.com/CleverRaven/Cataclysm-DDA/blob/cb02195d9fb5ba71f35a105be4104c3d8883065c/src/game.cpp#L623) and `master` [`game::setup()`](https://github.com/CleverRaven/Cataclysm-DDA/blob/cbcfab179d4e7e7f715e21d44816d1bee1132868/src/game.cpp#L608)).
> 
> Will do a PR shortly.
> 
> @chuizhi This is a software error: hopefully it'll be fixed with the `0.F` release.

The main reason is that this bug is very uncertain. Strengthening concrete walls has always been a problem. With wooden walls, the apple orchard had a roof. I don't know which version has no roof. In the survivor camp built by my NPC, the buildings with the same wooden walls are roofed. All in all, it's chaotic.
主要是这个BUG出现的非常不确定。加强混凝土墙一直没问题。木墙的话，苹果园里的本来有屋顶，不知道哪个版本变得没有屋顶了。而我的NPC建造的幸存者营地里，同样木墙的建筑，又是带屋顶的。总之，就是很混乱。
