### ISSUE TITLE
Caching not working on Travis

### ISSUE THREAD

**Issue by actual-nh** [CleverRaven/Cataclysm-DDA#47429]
# Describe the bug

On (at least recent) Travis builds, the ccache files are not downloading (even those without what appear to be indicators of date/whatever).

# Steps To Reproduce

See #47379, #47374, and #47273 for examples.

# Expected behavior

Able to download cached files, and at least some of them helping.

# Versions and configuration

Travis build.

# Additional context

Ping: @kevingranade, @jbytheway (and possibly @BrettDong)?

Examples from #47379:

```
Setting up build cache
$ export CASHER_DIR=${TRAVIS_HOME}/.casher
0.26s$ Installing caching utilities
0.00s1.66sattempting to download cache archive
fetching PR.47379/cache--linux-xenial-8a0d359a9465ad7c31e3aaa4b1867188f63ce18c48e81ad2113861ebbc2995de--compiler-clang.tgz
fetching PR.47379/cache-linux-xenial-8a0d359a9465ad7c31e3aaa4b1867188f63ce18c48e81ad2113861ebbc2995de--compiler-clang.tgz
fetching PR.47379/cache--compiler-clang.tgz
fetching master/cache--linux-xenial-8a0d359a9465ad7c31e3aaa4b1867188f63ce18c48e81ad2113861ebbc2995de--compiler-clang.tgz
fetching master/cache-linux-xenial-8a0d359a9465ad7c31e3aaa4b1867188f63ce18c48e81ad2113861ebbc2995de--compiler-clang.tgz
fetching master/cache--compiler-clang.tgz
could not download cache
```
and
```
Setting up build cache
$ export CASHER_DIR=${TRAVIS_HOME}/.casher
0.15s$ Installing caching utilities
0.01s2.98sattempting to download cache archive
fetching PR.47379/cache--osx-xcode10.2-0788f710b748e94f3815674fa2127c81997f6ca1bab46e576b33a2f8f16d2bff--compiler-clang.tgz
fetching PR.47379/cache-osx-xcode10.2-0788f710b748e94f3815674fa2127c81997f6ca1bab46e576b33a2f8f16d2bff--compiler-clang.tgz
fetching PR.47379/cache--compiler-clang.tgz
fetching master/cache--osx-xcode10.2-0788f710b748e94f3815674fa2127c81997f6ca1bab46e576b33a2f8f16d2bff--compiler-clang.tgz
fetching master/cache-osx-xcode10.2-0788f710b748e94f3815674fa2127c81997f6ca1bab46e576b33a2f8f16d2bff--compiler-clang.tgz
fetching master/cache--compiler-clang.tgz
could not download cache
```

**Comment by actual-nh** [comment]
Ping: @kevingranade, @jbytheway?

**Comment by BrettDong** [comment]
Is it network error or the file does not exist?

**Comment by actual-nh** [comment]
> Is it network error or the file does not exist?

I don't know. Where is it trying to download it from?

**Comment by actual-nh** [comment]
It is unfortunately necessary to open/whatever the "Setting up build cache" section to see all this, BTW. It would be nice if Travis would show it in red or something when it doesn't work.

**Comment by ZhilkinSerg** [comment]
This is probably something that we do not have much control over - we are just using cache functionality Travis provides. https://travis-ci.org/github/CleverRaven/Cataclysm-DDA/caches shows we are using quite a lot of disk space (355305.8MB) - maybe we should just purge everything and see if it helps.

![image](https://user-images.githubusercontent.com/16213433/107692276-9c30e180-6cbd-11eb-899a-ca43bb29fb0f.png)

Also it could possibly be related to their migration from `.org` to `.com` domain. Did you check if anything is already filed here - https://github.com/travis-ci/travis-ci/issues?

**Comment by actual-nh** [comment]
No issues found at <https://github.com/travis-ci/travis-ci/issues>.

**Comment by actual-nh** [comment]
I'm seeing a lot of errors due to Travis builds getting cancelled, then a lot of new Travis builds going. Flushed cache and "kicked" the tests?

**Comment by BrettDong** [comment]
I just manually re-run recently cancelled builds.

**Comment by actual-nh** [comment]
As of less than 7 minutes ago, #47426 still having this error on Android build.

**Comment by ZhilkinSerg** [comment]
No new caches appeared after cache cleanup, so I guess it is something on Travis side.

**Comment by ZhilkinSerg** [comment]
https://travis-ci.community/t/travis-failed-to-upload-cache/11162
https://travis-ci.community/t/repeatable-failed-to-upload-workspace-error/11108

**Comment by kevingranade** [comment]
Spot-checked a few daily master builds, they seem to be failing to upload new cache archives, reporting the same error message as the issues @ZhilkinSerg linked.

**Comment by actual-nh** [comment]
> Spot-checked a few daily master builds, they seem to be failing to upload new cache archives, reporting the same error message as the issues @ZhilkinSerg linked.

Ditto for PR builds:
```
changes detected, packing new archive
uploading PR.47273/cache--linux-xenial-8a0d359a9465ad7c31e3aaa4b1867188f63ce18c48e81ad2113861ebbc2995de--compiler-clang.tgz
failed to upload cache
```

**Comment by ZhilkinSerg** [comment]
Now in Github Actions too - e.g. https://github.com/CleverRaven/Cataclysm-DDA/pull/47468/checks?check_run_id=1892398099:

```
Post job cleanup.
/bin/tar --posix --use-compress-program zstd -T0 -cf cache.tzst -P -C /home/runner/work/Cataclysm-DDA/Cataclysm-DDA --files-from manifest.txt
Warning: Cache service responded with 400 during upload chunk.
/home/runner/work/_actions/actions/cache/v2/dist/save/index.js:3305
                        throw new Error(`Cache upload failed because file read failed with ${error.message}`);
                        ^

Error: Cache upload failed because file read failed with ESPIPE: invalid seek, read
    at ReadStream.<anonymous> (/home/runner/work/_actions/actions/cache/v2/dist/save/index.js:3305:31)
    at ReadStream.emit (events.js:210:5)
    at internal/fs/streams.js:167:12
    at FSReqCallback.wrapper [as oncomplete] (fs.js:470:5)
```

**Comment by ZhilkinSerg** [comment]
Caches started to appear on https://travis-ci.org/github/CleverRaven/Cataclysm-DDA/caches:

![изображение](https://user-images.githubusercontent.com/16213433/107877454-a3ced100-6edd-11eb-9de5-c76d1394f580.png)

**Comment by actual-nh** [comment]
Appears to be working now (checked #47484 for the build [13 hours ago](https://travis-ci.org/github/CleverRaven/Cataclysm-DDA/builds/758871091); closing issue.
