### ISSUE TITLE
Exoskeleton descriptions do not reflect their change in encumberance when activated

### ISSUE THREAD

**Issue by Sirbab** [CleverRaven/Cataclysm-DDA#47439]
# Describe the bug
Power armor, and perhaps other similar items does not appear to reflect the encumberance relief that activating gives.  For example, when the heavy exoskeleton is off, it has universal 60 encumberance, but when activated once can see the encumberances drop significantly to 20, or 25 on the torso.  However the item description does not reflect this.  

# Steps To Reproduce
1: Spawn a heavy combat exoskeleton and ups.
2: Observe encumberance in item description and the @ menu.
3: Activate the armor, wait a turn or two, then check the @ menu and item description, notice that @ has changed, but desc has not.

# Expected behavior
I expect that one should be able to see an appreciable difference between when the armor is off or on.  As it stands, looking in the inventory as one is trained to do via items like the pba mask which shows the contrast on vs off.

# Screenshots
![image](https://user-images.githubusercontent.com/1490991/107724142-26bf1400-6cb1-11eb-8399-91775a8cca89.png)
![image](https://user-images.githubusercontent.com/1490991/107724150-2b83c800-6cb1-11eb-8cfd-f49dc78eb6b7.png)
Screenshots are taken during the same turn
![image](https://user-images.githubusercontent.com/1490991/107724239-6685fb80-6cb1-11eb-8416-7a3afb5f72ed.png)
Above is the PBA mask format

# Versions and configuration
- OS: Windows 10 64 bit
    - OS Version: 10.0 2004
- Game Version: 0.E-9555-gfe798ae-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Modular Turrets Remake [modular_turrets_remake],
    Civilian Salvaged Robots [civilian_salvaged_robots],
    Automations [robot_automation],
    Gun Cotton [guncotton],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    More Survivor Stuff [more_survivor_stuff],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    sees-player icon, retrodays [sees_player_retro],
    Bens GF recipes [Tolerate_This],
    Useful Helicopters [useful_helicopters]
]

# Additional context
As an addendum, wapcaplet in discord mentioned the fact that changes in the @ menu don't occur immediately is likely a bug in of itself, but i wasn't able to find an open issue via a cursory search.

**Comment by AMurkin** [comment]
Should be closed?
