### ISSUE TITLE
Two Magiclysm achievements incorrectly gained after 1 day's survival

### ISSUE THREAD

**Issue by LaVeyanFiend** [CleverRaven/Cataclysm-DDA#47442]
# Describe the bug

While doing an island prison run with Prisoner profession & no spells learnt, I unlocked "Cast a Spell" and "Spell Level 5" at the same time as "The first day of the rest of their unlives."

# Steps To Reproduce

1. Survive 1 day.
2. Go to sleep.
3. Unlock the two Magiclysm achievements along with the usual 1 day survival.

# Expected behavior

To not gain these from surviving a day.

# Screenshots

![image](https://user-images.githubusercontent.com/51099123/107734242-eff5f780-6cca-11eb-968d-e4b89dcc3492.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-9570-gb09447e-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    Fuji's Military Profession Pack [fuji_mpp],
    Disable NPC Needs [no_npc_food],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex]
]

# Additional context

**Comment by RadHazard** [comment]
I've had the same thing happen in a run of mine before too, except for mine the game thought it was a level 52 spell.  I Alt-F4'd my game after it happened the first time since I thought it was something I did with debug mode accidentally, but it happened again later to the same character at a different spot and time.

**Comment by superninjakiwi** [comment]
I made this save right after it happened to me. Opening the .sav file, it looks like even though I don't actually know any spells, I my spell level for rocket_punch might be 5? That might help narrow down the cause. I hadn't even left the first room, or done anything of consequence, so I'm still not sure what actually causes it. It could be related to how high the character's INT is; I used freeform and started with 20 Int, and the player_levels_spell part of the save seems to contain a lot of references to the character's INT, along with rocket_punch
[NewMunnsville.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6016307/NewMunnsville.zip)
.

**Comment by RadHazard** [comment]
Duplicate/related to #47425?

**Comment by superninjakiwi** [comment]
It might be related, but I don't think it's a duplicate. This bug involves spell levels being given to someone who hasn't actually learned any spells.

**Comment by actual-nh** [comment]
> It might be related, but I don't think it's a duplicate. This bug involves spell levels being given to someone who hasn't actually learned any spells.

The issue title may need changing, then - @LaVeyanFiend?

**Comment by SilverTemper** [comment]
I gained the spell level-up achieve immediately upon spotting two golems if that's helpful.

**Comment by superninjakiwi** [comment]
I can confirm that spotting a Stone Golem seems to reliably grant 'Cast a Spell' and 'Spell level 5' achievements.
