### ISSUE TITLE
Passive enchantments with SPEED modifier do not affect player speed

### ISSUE THREAD

**Issue by olanti-p** [CleverRaven/Cataclysm-DDA#47450]
# Describe the bug
Passive enchantments that affect speed (`enchant_vals::SPEED`) do not actually affect avatar's speed, only speed display.

# Steps To Reproduce
1. Obtain an artifact with passive enchantment that severely reduces speed (win debug spawn lottery or just edit a save)
2. Activate the passive enchantment (e.g. wield the item if needed)
3. Notice that 'speed' indicator in the sidebar dropped as expected
4. Walk around. Notice that the movement takes ~1 turn/tile, both with and without the artifact

# Expected behavior
Character needs a few turns to move across a tile, like when in pain or overburdened.

# Versions and configuration
Build 11459 (aka cbcfab179d4e7e7f715e21d44816d1bee1132868)

# Additional context
I'm pretty sure `Creature::speed_bonus` gets reset at the beginning of each turn, and new moves are assigned based on this new value instead of whatever was calculated by the `Character::enchantment_cache`.

**Comment by OliveChukar** [comment]
Tested in 0.E-9634-gda7c0c6 with core content pack dda only. Spawned artifacts with debug until got one that showed reduced speed on @ screen when wielded then walked a measured distance with and without the artifact. Time to move was the same displayed speed did not effect results of real movement.
Do not know if artifacts like this can spawn naturally without mods but if they can this issue exists in base game not just magiclysm.

I do not know how to force natural artifact spawns or how to save edit them both of these things could help with further testing.
