### ISSUE TITLE
Simplify Character template to include player selections instead of raw data

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#47462]
# Is your feature request related to a problem? Please describe.

Character templates are a raw serialization of the avatar, and are unversioned. This causes changes to avatar internal data to potentially break player templates from one version to another, with no migration path.

# Describe the solution you'd like

Templates should instead capture the player's inputs at the time of character creation. To quote @anothersimulacrum's [comment](https://github.com/CleverRaven/Cataclysm-DDA/issues/46995#issuecomment-766459097):

> The only data that needs to be saved is that which can be selected through character creation: scenario, profession, stats, skills, traits, gender, name, height, age, blood type, and starting location selection.
> Start with a default character, then apply all those, and we're back to the character we made.

Templates should also be versioned, such that when options are added, changed, or removed from the character creation screen, it is (at least in theory) possible for the game to detect and migrate player templates from one version to another.

# Describe alternatives you've considered

There are two main functions to rewrite, both in `src/newcharacter.cpp`:

- avatar::save_template
- avatar::load_template

Plan of action:

- Save and load a version number in the template
- Add some info to both save and load, and add tests for it
- Save/load/test iteration until all character-creation options work

The template should be a mandatory part of the character-generation pipeline, generated for every character that is created, and then applied at the end of chargen, just before the new character spawns in the world. In other words, the template should be the messenger carrying all customizations, and no customizations will work without going through the template (and being properly implemented on both ends).

# Additional context

Recently this occurred when the stored calories changing by a factor of 1000, resulting in new characters started from old templates to begin the game "Skeletal" and "Starving": #46995

This can be reproduced as follows:

- Create a new character, and customize them as you like
- On the last page of character creation, press `!` to save a template
- Open `templates/your-character.template`, and change the `stored_calories` value from `55000000` to `55000`
- Start a new character from your saved template

**Comment by actual-nh** [comment]
Perhaps a (thresholding) patch for #46995 for 0.F to keep compatibility, followed by this after 0.F?

**Comment by hexagonrecursion** [comment]
Sounds fun. I'll give this a try

**Comment by hexagonrecursion** [comment]
Question: what should we do about the feature that allows the player to turn arbitrary characters into templates (main menu -> world -> character to template)? This currently preserves all kinds of information beyond what can normally be configured in the character generation menu: status effects, pain, focus, mutations (current rather then the ones you started with), bionics, XP, clothing etc. This feature is useful for experimenting, debugging and just having "non-canonical" adventures. Granted: the feature is not perfect: current and max HP is reset to 60 (#51128).

**Comment by hexagonrecursion** [comment]
The more I think about this the less this sounds like the right approach:
1. We would loose the feature I mentioned above
2. We should already have code to migrate real characters. It does not sound difficult to apply the same code to templates as well

@wapcaplet Are there benefits to your suggested approach that I am overlooking?

**Comment by wapcaplet** [comment]
@hexagonrecursion I had not considered the "character to template" feature, having not really used it myself. Losing that would definitely be one of the drawbacks of the approach I suggested.

I'll admit I have not thought deeply about the practical advantages of my proposal, aside from making version-migrations potentially easier. There may be other benefits to moving toward a more parameterized process for character generation - saving the character "recipe", so to speak, rather than the "baked" final result like we do now - but those benefits are mostly speculation or theoretical.

@anothersimulacrum Thoughts?

**Comment by anothersimulacrum** [comment]
It feels very wrong and bug prone to me to me to save characters as templates. 
I know, however that you are doing some things in the way of dynamically recalculating character generation data, instead of storing it, which I would think clashes with this approach.

It feels wrong, but if you think it is for the best, I have no objections.

**Comment by hexagonrecursion** [comment]
Here is something I have not considered: using baked characters as templates like we do now causes them to de-sync from the profession, scenario and hobby definitions: when a hobby is updated old templates continue getting the old benefits (eg "locked" traits) and don't get new benefits. This might also apply to the effects of some traits and the list of recipes you learn from the start. Things get worse when the original world of the template and the new world have a different set of mods leading to issues like #50687

**Comment by hexagonrecursion** [comment]
Original motivation for the character to template feature: #33716

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
