### ISSUE TITLE
mp3 player batteries are dead

### ISSUE THREAD

**Issue by DavisBroda** [CleverRaven/Cataclysm-DDA#47478]
When attempting to activate an mp3 player that contains a charged battery, it will always respond with "The device's batteries are dead" rather than turning on. 

# Steps To Reproduce

1. Get mp3 player
2. load with battery that contains charges
3. attempt to turn on mp3 player
4. observe the "The device's batteries are dead" message, and that the mp3 player remains turned off

# Expected behavior

1 battery charge consumed, and mp3 player turns into the on state

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-9634-gda7c0c6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

Attempting to turn on still consumes 1 charge of battery even though it doesn't work. Have tested with full disposable light batteries, light batteries, and light batteries (high-capacity) with no change in behavior. have only observed this for mp3 player. Some other battery powered devices (flashlight for instance) continue to work as expected.

**Comment by actual-nh** [comment]
Ping: @Jamuro-g
