### ISSUE TITLE
Sawing barred windows produces the wrong material

### ISSUE THREAD

**Issue by RadHazard** [CleverRaven/Cataclysm-DDA#47470]
# Describe the bug
I was looking for rebar to add some bars to my house's windows when I remembered the nearby town had a bunch of barred windows.  I used my trusty hacksaw to cut the bars away, but to my surprise they dropped pipes and not rebar.  Sadly, pipes are not actually usable for building my own window bars.

There's also some other weird behavior surrounding barred windows:
 - Barred windows can have curtains, but you can't weld bars onto windows that have curtains, and likewise barred windows with curtains can't be sawed without tearing the curtains off first.
 - If you saw barred windows without curtains, the glass magically disappears.

# Steps To Reproduce
1. Find any window and tear the curtains off
2. Spawn a welder, 8 rebar, 6 small metal plates, a multitool, welding goggles, and a hacksaw
3. Add bars to the window with the construction menu
4. Activate the hacksaw to saw the bars back off of the window 
5. Observe that the window glass has vanished and the rebar you welded onto the window has magically become pipes.

# Expected behavior
Sawing bars off of a window produces the same material that window bars are made of.  Welding bars onto a window then cutting them back off with a saw doesn't cause the glass to magically disappear (either it's left intact or it breaks into shards, but it should definitely not vanish entirely).  Windows with curtains can be given bars, and barred windows with curtains can have the bars sawed off.

# Versions and configuration
- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.2 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-9578-gcbcfab179d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Maleclypse** [comment]
activity_handlers.cpp line 3577 is the start of where pipes are spawned from hacksawing windows. It would be an easy fix but are we willing to say that the cut rebar is long enough to still count as rebar?
```    } else if( ter == t_window_bars_alarm ) {
        here.ter_set( pos, t_window_alarm );
        here.spawn_item( p->pos(), itype_pipe, 6 );
    } else if( ter == t_window_bars ) {
        here.ter_set( pos, t_window_empty );
        here.spawn_item( p->pos(), itype_pipe, 6 );```

**Comment by RadHazard** [comment]
I'd assume you could get back some quantity of usable rebar even if it's not the full amount used to build it, but that's just my opinion.  Either way, it definitely shouldn't be dropping pipes
