### ISSUE TITLE
Segmentation Fault on attempting to read a book that I can't wield

### ISSUE THREAD

**Issue by superninjakiwi** [CleverRaven/Cataclysm-DDA#47487]
# Describe the bug

I have two broken arms, and cannot wield anything. There is a book on the ground that I do not have the ability to pick up, because my inventory is full and I can't wield it. However, when trying to (R)ead it, I'm able to select the book, because my hands are empty. This leads to a segfault.

# Steps To Reproduce

1. Be incompetent; break both your arms.
2. Find a book.
3. Strip down to nothing.
4. Attempt to read the book. 

# Expected behavior

If I can't pick up the book, don't let me read it (and crash).

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-9557-g57383f7-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    No Fungal Monsters [No_Fungi],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

There seem to be more problems related to having two broken arms; for instance, when I tried to turn off a flashlight that I couldn't pick up, it errored as it couldn't add the item to my inventory (though it didn't crash), and the flashlight disappeared. In addition, I managed to get an autodoc to splint my arms... or at least *say* that it splinted both my arms. Only my right arm got a splint, and further interaction with the autodoc didn't help my left arm.

**Comment by actual-nh** [comment]
Previous save files, logs, etc?

**Comment by superninjakiwi** [comment]
Here's a world file that should show the problem. Just load it up, and (R)ead the book on the ground (Outdoor Adventures)
[Munnsville.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5976999/Munnsville.zip)
