### ISSUE TITLE
Use ImgBot to reduce size of tilesheet files prior to releasing new stable version

### ISSUE THREAD

**Issue by int-ua** [CleverRaven/Cataclysm-DDA#47494]
# Is your feature request related to a problem? Please describe.
@UmbralReaper discovered that ImgBot is able to losslessly reduce PNG sizes significantly and so far we didn't find a way to match it with our workflows.

# Describe the solution you'd like
Use ImgBot to optimize `gfx/*/*.png` images after merging latest versions of tilesets right before releasing new stable version.

# Describe alternatives you've considered

# Additional context
https://github.com/I-am-Erk/CDDA-Tilesets/pull/521
https://github.com/UmbralReaper/UltimateCataclysm/pull/1/files
https://discord.com/channels/598523535169945603/598614717799596055/810071093024522250

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
