### ISSUE TITLE
No documentation for 'burn_data', many entries in materials.json have weird values

### ISSUE THREAD

**Issue by Salty-Panda** [CleverRaven/Cataclysm-DDA#47498]
# Is your feature request related to a problem? Please describe.

No documentation for `"burn_data"`, many entries in materials.json have weird values.
There is no baseline, no info about default values.
Gutskin has the same stats as human flesh, fur the same as fruit matter.

# Describe the solution you'd like

Explanation of values in the documentation.

# Describe alternatives you've considered

None

**Comment by wapcaplet** [comment]
Tracing through the git history, I see this was added way back in #17035 

There is a related (also undocumented) field `burn_products` added in #23600

**Comment by Salty-Panda** [comment]
What I learned from the code:
The relevant function is `item::simulate_burn()`
There are three fire intensities. The "contained" fire ( not sure, inside stove maybe? ) is counted as intensity 3.
Array objects are read depending on fire intensity `return _burn_data[ std::min( intensity, _burn_data.size() ) - 1 ]`.
Upon a quick inspection, fire intensity is often in the range 1-3, so the first value might be underused.

Burn data is an array that needs? three objects.
`{ "fuel": <int>, "smoke": <int>, "burn": <int>,  volume_per_turn: <int ml> }` or `{ "immune": true }`
If the object is in the form of `{ "immune": true }` the entire item using this material is assumed to be completely fire-resistant.
If you only want it to be resistant against small fires, you need to specify "burn" : 0 ( then, going by logic fuel and smoke should be set to 0 too )

Fuel is how much the item fuels the fire per turn. Can be negative ( see liquid materials )
Smoke is how much smoke is generated per turn
Burn states how much of an item is burnt per turn
volume_per_turn is an optional parameter, defaults to `1 L`. Multiplies the previous values.
If the item has more than one material things are divided by the number of materials.

Item has <int>`burnt` property.
It's increased by `function `Returns x + x_in_y( x-int(x), 1 )` called with argument ( 1 )`

There are special cases for liquids and corpses.

If `burnt` >= item_volume/250ml * 3 then item is destroyed.

**Comment by actual-nh** [comment]
> volume_per_turn is an optional parameter, defaults to 1 L. Multiplies the previous values.

Is there a relationship between this and `burnt` and/or the item's volume?

> function Returns x + x_in_y( x-int(x), 1 ) called with float returned by item::simulate_burn()

Is this a harder-to-read version of `rnd_remainder` (IIRC regarding the latter's name)?

> Array objects are read depending on fire intensity return _burn_data[ std::min( intensity, _burn_data.size() ) - 1 ]
Upon a quick inspection, fire intensity is often in the range 1-3, so the first value ( which is 0 ) might be underused.

😕  intensity of 1, minus 1, gives you 0.

**Comment by Salty-Panda** [comment]
> Is there a relationship between this and `burnt` and/or the item's volume?
Bigger things burn for longer 


> Is this a harder-to-read version of `rnd_remainder` (IIRC regarding the latter's name)?
I don't remember

> 😕 ? Intensity of 1, minus 1, gives you 0.
Intensity  returned array index
1             1
2             2
3             2

**Comment by Fris0uman** [comment]
closed in #65409
