### ISSUE TITLE
Crash at Regional dump 

### ISSUE THREAD

**Issue by Sple61** [CleverRaven/Cataclysm-DDA#47497]
When you come to the regional dump, the game crashes  
IN debug.log issues 
WARNING : opendir [/storage/emulated/0/Android/data/com.cleverraven.cataclysmdda.experimental/files/mods/] failed with "No such file or directory".
WARNING : opendir [/storage/emulated/0/Android/data/com.cleverraven.cataclysmdda.experimental/files/save/Малкольм/mods] failed with "No such file or directory".
What to do?

**Comment by wapcaplet** [comment]
Can you provide your game version number and platform? You can copy it to the clipboard easily from the game with `ESC > Debug Menu > Info... > Generate game report`. If you can attach a .zip of your save game, that would be helpful as well.

I cannot reproduce the issue in experimental 0.E-9603-g42468f6cab on Linux.

**Comment by Sple61** [comment]
> Можете ли вы указать номер версии вашей игры и платформу? Вы можете легко скопировать его в буфер обмена из игры с помощью `ESC > Debug Menu > Info... > Generate game report`. Если вы можете прикрепить .zip-файл с сохранением игры, это тоже будет полезно.
> 
> Я не могу воспроизвести сбой в экспериментальном 0.E-9603-g42468f6cab в Linux.

- OS: Android
    - OS Version: Manufacturer: Xiaomi; Model: Redmi 7A; Release: 10; Incremental: V12.0.1.0.QCMRUXM; 
- Game Version: cbcfab1 [32-bit]
- Graphics Version: Tiles
- Game Language: Русский [ru]
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у NPC [no_npc_food],
    Бионические профессии [package_bionic_professions],
    Расширение К.Р.И.Т. [crt_expansion],
    Магиклизм [magiclysm],
    Темные Дни Мертвых [classic_zombies],
    Характеристики за убийства [stats_through_kills]
]
version latest experimental for android
Progress https://drive.google.com/file/d/1-ePGmmLUBe-Aft3Rom5_OHUnWSU0BJig/view?usp=drivesdk

**Comment by PaulBlay** [comment]
> Progress https://drive.google.com/file/d/1-ePGmmLUBe-Aft3Rom5_OHUnWSU0BJig/view?usp=drivesdk

Is that the save file? I requested access to test it.

**Comment by BrettDong** [comment]
I heard another player reporting crash around regional dump in Android version build 11451, although I haven't managed to reproduce the crash by myself yet.

**Comment by BrettDong** [comment]
[游猎国度.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5979633/default.zip)

Here is a save provided by another player. Load character "艾丽塔" and head for the regional dump to the northwest. I don't get a crash, but after I recompile with ASan and UBSan, it triggers an out-of-bound access error:
<img width="857" alt="螢幕截圖 2021-02-15 上午12 27 05" src="https://user-images.githubusercontent.com/21075502/107908641-88d37f80-6f24-11eb-8f63-7bc4fa4986c0.png">

My guess is that NPC at the border of the reality bubble causes out-of-bound access to some arrays and corrupted memory.

**Comment by BrettDong** [comment]
Stack trace:
```
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  * frame #0: 0x000000010dbecfe0 libclang_rt.asan_osx_dynamic.dylib`__asan::AsanDie() + 40
    frame #1: 0x000000010dc01d58 libclang_rt.asan_osx_dynamic.dylib`__sanitizer::Die() + 192
    frame #2: 0x000000010dc134a0 libclang_rt.asan_osx_dynamic.dylib`__ubsan_handle_dynamic_type_cache_miss_abort + 76
    frame #3: 0x0000000100c806d0 cataclysm-tiles`std::__1::basic_ostream<char, std::__1::char_traits<char> >::flush() + 1200
    frame #4: 0x0000000100c7ff10 cataclysm-tiles`std::__1::basic_ostream<char, std::__1::char_traits<char> >::sentry::sentry(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) + 820
    frame #5: 0x0000000100e36f20 cataclysm-tiles`std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) + 232
    frame #6: 0x00000001011cf508 cataclysm-tiles`std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::operator<<<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 76
    frame #7: 0x0000000101be8e1c cataclysm-tiles`log_crash(char const*, char const*) + 1788
    frame #8: 0x0000000101be8288 cataclysm-tiles`signal_handler(int) + 120
    frame #9: 0x000000019b61dc44 libsystem_platform.dylib`_sigtramp + 56
    frame #10: 0x000000019b5d5c24 libsystem_pthread.dylib`pthread_kill + 292
    frame #11: 0x000000019b51d864 libsystem_c.dylib`abort + 104
    frame #12: 0x000000010dc023b4 libclang_rt.asan_osx_dynamic.dylib`__sanitizer::Abort() + 68
    frame #13: 0x000000010dc01d6c libclang_rt.asan_osx_dynamic.dylib`__sanitizer::Die() + 212
    frame #14: 0x000000010dc10f58 libclang_rt.asan_osx_dynamic.dylib`__ubsan_handle_out_of_bounds_abort + 64
    frame #15: 0x00000001030f3834 cataclysm-tiles`map::light_transparency(tripoint const&) const + 620
    frame #16: 0x00000001030f4bac cataclysm-tiles`map::is_transparent(tripoint const&) const + 132
    frame #17: 0x000000010343bf9c cataclysm-tiles`std::__1::__function::__func<map::sees(tripoint const&, tripoint const&, int, int&) const::$_69, std::__1::allocator<map::sees(tripoint const&, tripoint const&, int, int&) const::$_69>, bool (point const&)>::operator()(point const&) + 604
    frame #18: 0x000000010312d8d8 cataclysm-tiles`bresenham(point const&, point const&, int, std::__1::function<bool (point const&)> const&) + 1448
    frame #19: 0x00000001033c2c08 cataclysm-tiles`map::sees(tripoint const&, tripoint const&, int, int&) const + 1920
    frame #20: 0x00000001033c23b8 cataclysm-tiles`map::sees(tripoint const&, tripoint const&, int) const + 376
    frame #21: 0x0000000101bf2ee4 cataclysm-tiles`Creature::sees(tripoint const&, bool, int) const + 1756
    frame #22: 0x0000000101676c58 cataclysm-tiles`Character::sees(tripoint const&, bool, int) const + 508
    frame #23: 0x00000001041a4bf0 cataclysm-tiles`npc::assess_danger() + 8000
    frame #24: 0x00000001041aedd0 cataclysm-tiles`npc::regen_ai_cache() + 3736
    frame #25: 0x00000001041b0a64 cataclysm-tiles`npc::move() + 860
    frame #26: 0x0000000102251de4 cataclysm-tiles`game::monmove() + 10868
    frame #27: 0x0000000102241f10 cataclysm-tiles`game::do_turn() + 10004
    frame #28: 0x00000001032e4084 cataclysm-tiles`main + 9920
    frame #29: 0x000000019b5f1f34 libdyld.dylib`start + 4
```

**Comment by Sple61** [comment]
> > Прогресс https://drive.google.com/file/d/1-ePGmmLUBe-Aft3Rom5_OHUnWSU0BJig/view?usp=drivesdk
> 
> Это файл сохранения? Я запросил доступ, чтобы проверить это.

access is open

**Comment by BrettDong** [comment]
Both this save and the save I attached previously have a group of thug NPCs in the regional dump and I suspect that is the cause.
