### ISSUE TITLE
Problem with unloading UPS 

### ISSUE THREAD

**Issue by lmaolollmao** [CleverRaven/Cataclysm-DDA#47502]
# I can unload a UPS and get a "battery"

You shouldn't be able to do that.

# Steps To Reproduce

1. Spawn in a UPS
2. Unload it

# Expected behavior

I expect not being able to take out the electricity out of the UPS.

# Screenshots

![lol](https://user-images.githubusercontent.com/50447956/107884851-6aa35a80-6ef7-11eb-8080-5ebca20b8485.PNG)
![lol2](https://user-images.githubusercontent.com/50447956/107884853-6bd48780-6ef7-11eb-85f9-457769e00733.PNG)
![lol3](https://user-images.githubusercontent.com/50447956/107884882-89095600-6ef7-11eb-96a7-a34d8f5e8854.PNG)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-9640-g62c4484 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    No Fungal Monsters [No_Fungi],
    Disable NPC Needs [no_npc_food],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

 -->
Here is also the save file
https://drive.google.com/file/d/1Pa40FiEjbXeO9GGZcLH_jTx9DeyIpdMn/view?usp=sharing

**Comment by PaulBlay** [comment]
Does that only happen with spawned in UPS?

**Comment by Jamuro-g** [comment]
i couldn't reproduce it on a vanilla world. That said, it does happen in the provided save.
Seems to be a mod issue (i am guessing aftershock)

**Comment by Hirmuolio** [comment]
The vanilla UPS does not say that it is un-unloadable.

Vanilla description:
> This is a unified power supply, or UPS.  It is a device developed jointly by military and scientific interests for use in combat and the field.  The UPS is designed to power bionics, armor and some guns, but drains batteries quickly.

It is also not loaded with free floating battery but instead uses battery magazines. So this seems like mod problem.
