### ISSUE TITLE
Pipes are too short

### ISSUE THREAD

**Issue by Inguinal** [CleverRaven/Cataclysm-DDA#47514]
The pipe item is currently 3 in. long, way too short for most of its applications in crafting. Leads to some silly things like banging a 3 in. pipe into a 23 in. long makeshift crowbar.

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-9634-gda7c0c6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Crazy Cataclysm [crazy_cataclysm],
    Disable NPC Needs [no_npc_food],
    Mythical Martial Arts [MMA]
]

**Comment by PaulBlay** [comment]
See https://github.com/CleverRaven/Cataclysm-DDA/issues/47202
