### ISSUE TITLE
[Magiclysm] Spellcraft seems to be leveling far too slowly.

### ISSUE THREAD

**Issue by Zeilos** [CleverRaven/Cataclysm-DDA#47515]
# Describe the bug
Currently it seems you only gain a small amount of spellcraft experience when you finish studying. I just finished testing and studying Translocate Self for 20 days straight to spell level 25(max) only brings spellcraft up to level 3 and some change. This was done with focus consistently between 80 and 100. Currently your focus from studying only drops when you finish studying and it always seems to drop to 1 instantly when it does. I remember a bug report somewhere about focus drop but couldn't find it. This may be related. At current, once you finish mastering the spell you can no longer learn from it meaning you can't raise spellcraft any further from it. I have found this issue to persist across all spells.

# Steps To Reproduce
Start a new world with Magiclysm.
Study Geospatial Systems: The Lie of Linearity(Translocate Self) to max.
This should raise spellcraft to 1 or so after the first level or two and a bit over 3 by max level.

# Expected behavior

To my knowledge Translocate Self is the most difficult spell and should bring spellcraft up to 16 ideally given enough time. Spending 20 days of studying to get to level 3 doesn't seem right to me. 24 hours of studying any normal book with good focus should bring a character up at least from level 2 of a skill to 3, usually well over that.

# Versions and configuration
 - OS: Windows 10 Home Version 10.0.19041
 - Game Version: 0.E-9654-g1e40b42 and prior versions
 - Graphics version: Tiles
 - Ingame language: English
 
 - Mods loaded: 
  Dark Days Ahead [dda]
  Disable NPC Needs [no_npc_food]
  Bionic Professions [package_bionic_professions]
  Aftershock [aftershock]
  C.R.I.T Expansion Mod [crt_expansion]
  Blaze Industries [blazeindustries]
  Magiclysm [magiclysm]

**Comment by actual-nh** [comment]
Ping: @KorGgenT? Was it occurring in builds prior to 11382 (when #46596 merged)?

**Comment by Zeilos** [comment]
I don't think so. I should clarify that I mean the last few weeks is as I've noticed it.

**Comment by actual-nh** [comment]
Ping: @kevingranade?

**Comment by Karthas077** [comment]
In the process of maxing my Fox's Cunning (Difficulty 5 spell), I noticed that 1 hour increments tended to be the sweet spot for Spellcraft progress from 5 to 6. A single full-day "Study until next level" only netted me around 6-8% progress, but every 1 hour session got me 3-4% each.

Clearly something wonky is going on though because I shouldn't get drastically different results from using "Study for 1 hour" 8 times compared to "Study for 8 hours".

**Comment by Karthas077** [comment]
Just took a looksie, It looks like `amount = std::min( amount, focus_drain_cap );` is dropping all of the spellcraft XP down to a much lower value based on whatever Focus was at the time that the study session finished.

**Comment by KorGgenT** [comment]
i'm pretty sure there's a bug hidden in the recent focus skilling up change, and i'd like to get it fixed for stable.

**Comment by anothersimulacrum** [comment]
I can no longer reproduce this. I have discovered a related integer overflow bug that would set focus to very high values after long periods of training (but after the skill had already been practiced), and I have a fix for that.

**Comment by MarlossCDDA** [comment]
Oh, I think I was looking at the same issue as @anothersimulacrum. There's a bug where studying for more than about 90 minutes only trains your spellcraft as much as training for 90 minutes would, I mention it in the PR description on https://github.com/CleverRaven/Cataclysm-DDA/pull/48020.

**Comment by MarlossCDDA** [comment]
oops, guess @Karthas077 already found it

**Comment by actual-nh** [comment]
Is something like #47186 needed for studying magic?

**Comment by MarlossCDDA** [comment]
Yes, definitely - I'm thinking I'll do that in the next week or so, but feel free to beat me to it.

**Comment by actual-nh** [comment]
Given the number of headaches Kevin had with #47186, I'm not sure if I'm up to it.

**Comment by MarlossCDDA** [comment]
@actual-nh yeah it was pretty rough 48021
