### ISSUE TITLE
damaged minireactor installation 

### ISSUE THREAD

**Issue by VeryTired8462** [CleverRaven/Cataclysm-DDA#47516]
# it wont give the option to install the minireactor 

1. uninstall a damaged minireactor from an atomic vehicle
2. enter the install tab of a vehicle
3. if the 'minireactor' name isnt highlighted, despite having all the things needed, that is the problem
it doesn't allow you to install the reactor, despite having everything you need (ive foud out it works for a completely undamaged minireactor, but not for a damaged reactor.

this is what is wrong, im not a coder, so dont expect me to always know what you are talking about, and im new to github to forgive me if i mess something up

<!-- Add any other context about the problem here.

**Comment by Fosheze** [comment]
I actually ran into this last night. If you are having the same issue I did try unloading the minireactor first then it should let you install it. It's probably not the fact that it is damaged but the fact that it has contents. The same issue exists with a lot of crafting recipes that use tools. If those tools are loaded then they don't show up as usable components.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-6029.

![изображение](https://user-images.githubusercontent.com/11132525/153710520-d08fc37f-f82c-4e33-9ed1-4ef76f452b58.png)

![изображение](https://user-images.githubusercontent.com/11132525/153710511-54f870d1-a9e6-47df-988d-552f3eb81596.png)
