### ISSUE TITLE
[R]eading a book owned by an NPC is considered stealing if seen

### ISSUE THREAD

**Issue by NyarlathotepZERO** [CleverRaven/Cataclysm-DDA#47522]
# Describe the bug

A book owned by an NPC that has the 'R' command used on it results in an act of stealing. 

# Steps To Reproduce

1. Have an NPC stand next to a book he owns.
2. Stand within view of the NPC and use the 'R' command to read the book.
3. The resulting dialogue from the NPC is that you have attempted to steal the book.

# Expected behavior

I would expect that the 'picking up this item will be considered stealing' dialogue box would display prior to my char going ahead and stealing the book.

This dialogue box would display if you were to try picking up the book in any other way.

# Screenshots

not required

# Versions and configuration

Platform     : Windows_x64
Graphics     : Tiles
Build number : #11466
Build version: 0.E-9652-g1e40b42
Major version: 0.E

# Additional context

not required

**Comment by PaulBlay** [comment]
Possibly the result of someone fixing this https://github.com/CleverRaven/Cataclysm-DDA/issues/37181 ?

**Comment by NyarlathotepZERO** [comment]
> Possibly the result of someone fixing this #37181 ?
> 
> I could have sworn I saw someone suggest in an issue that you should be able to read books in the refugee center without being considered to be stealing them, but I can't find it.

I did do a search but did not get any results. Perhaps my syntax was different though.

**Comment by GGgatherer** [comment]
It's different universe in which copyright laws are taken to the highest levels of absurd.

**Comment by Melodeiro** [comment]
When you read books with R which is not in your inventory, you are picking them up by hands, IIRC. Thats why it triggers NPCs. Maybe a dialogue skill check to convince NPC to give that book temporary to you would do the trick, and also sounds immersive
