### ISSUE TITLE
Placing a plank over a pit duplicates the plank

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#47520]
# Describe the bug

When `e`xamining a deep pit with a plank nearby or in the inventory, there is an option to "Place a plank over the pit?" Answering `Y`es will bridge the pit, but will not actually consume the plank. So it is then possible to `e`xamine the bridged pit and get a plank back, resulting in a duplicate.

The action is also free (takes 0 time).

# Steps To Reproduce

1. Dig a deep pit
2. Get 1 plank and wield it
3. `e`xamine the deep pit, and answer `Y`es to "Place a plank over the pit?" - wielded plank remains in the hands
4. `e`xamine the plank over the pit, and answer `Y`es to "Remove cover?" - plank is placed on the ground at the character's feet
5. Repeat as many times as you want to get free lumber

# Expected behavior

It should use up 1 plank to place a plank over the pit.

It should also use some time to place the plank over the pit, and to remove it afterwards, 1 second at least.

# Screenshots

Free pit planks! Get your pit planks here! All 20 of these planks are clones of 1 plank, and it took 0 time to get them:

![image](https://user-images.githubusercontent.com/238395/107893012-e3012000-6ee5-11eb-8bfd-426bed5e6b4c.png)

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-9603-g42468f6cab-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by PaulBlay** [comment]
@wapcaplet While making things take the right time is a good thing to do, does that PR also stop planks from being duplicated?

If not, it doesn't actually close this issue.

**Comment by wapcaplet** [comment]
> @wapcaplet While making things take the right time is a good thing to do, does that PR also stop planks from being duplicated?
> 
> If not, it doesn't actually close this issue.

In fact it does prevent planks from being duplicated, but I have no idea why.
