### ISSUE TITLE
Player can pick conflicting traits when creating a character using professions.

### ISSUE THREAD

**Issue by Saicchi** [CleverRaven/Cataclysm-DDA#47544]
# Describe the bug

When creating a character choosing the profession does not reset the traits, allowing player to pick conflicting traits.

# Steps To Reproduce

1. Go to the create custom character screen, pick `Evacuee` scenario.
2. Go to traits and pick `Animal Discord`
3. Go to profession and pick the `Zoo Keeper` profession which gives `Animal Empathy`
4. Go to description or create the character and notice how the character has both traits which cancel each other.

# Expected behavior

`Animal Discord` would be deselected when picking the `Zoo Keeper` profession which has a conflicting trait with it.

# Screenshots

![Screenshot_20210215_223456](https://user-images.githubusercontent.com/47158232/108007996-0c04dc00-6fde-11eb-93a9-7ff88146c28c.png)

![Screenshot_20210215_223528](https://user-images.githubusercontent.com/47158232/108008028-1e7f1580-6fde-11eb-88b7-018b5f8a171c.png)

![Screenshot_20210215_223704](https://user-images.githubusercontent.com/47158232/108008122-571eef00-6fde-11eb-983c-037dbc04c8d7.png)

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.E-9653-g91cd2bdee2-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]
]

# Additional context

Also works with `Death Row Convict` profession `Killer Drive` and `Psychopath`

**Comment by Jamuro-g** [comment]
can confirm 
it looks like picking a profession doesn't check already existing trait picks.

**Comment by A3Digital** [comment]
For the expected behavior, do you mean to say that ```Animal Discord``` will be deselected as opposed to ```Animal Empathy``` being deselected?

**Comment by Saicchi** [comment]
Yes. Thanks for pointing that out.
