### ISSUE TITLE
Version strings for tilesets and soundpacks

### ISSUE THREAD

**Issue by int-ua** [CleverRaven/Cataclysm-DDA#47551]
# Is your feature request related to a problem? Please describe.
Seeing versions (presumably being dates of release) in the configuration menu may prompt user checking updates.

# Describe the solution you'd like
Adding new value to `tileset.txt`, `VERSION: 2021-02-15` for example.

# Describe alternatives you've considered
Including version in the name, less neat and not mandatory for authors.

# Additional context
https://github.com/CleverRaven/Cataclysm-DDA/blob/bb90c18564a6c7d38622c4a00fb76f3e1f10736d/src/options.cpp#L882

**Comment by ZhilkinSerg** [comment]
Also switch tilesets to use json instead of txt.

**Comment by int-ua** [comment]
> Also switch tilesets to use json instead of txt.

Comments will have to be moved to a separate `README.md` but that's fine, check https://github.com/CDDA-Tilesets/UltimateCataclysm for an example

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
