### ISSUE TITLE
Royal Jelly Does Not Cure Fungal Infection

### ISSUE THREAD

**Issue by tornikeo** [CleverRaven/Cataclysm-DDA#47555]
# Describe the bug

Royal Jelly is described as [cure-all](http://cddawiki.chezzo.com/cdda_wiki/index.php?title=Royal_jelly) medication. However, It does not cure fungal infection.

# Steps To Reproduce

1. Start in fungal infection scenario.
2. Find or wish royal jelly.
3. Consume and see that fungal infection does not go away.

# Expected behavior

Jelly should cure fungal infection. Otherwise, all we have to do is update our wiki about it.

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.1 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-9666-gecae002 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Crazy Cataclysm [crazy_cataclysm]
]

# Additional context

None.

**Comment by Fris0uman** [comment]
Wiki is out of date, Royale jelly is just bitter honey. This is working as intended.
