### ISSUE TITLE
Combat exoskeleton name is not changing when it has contents (thought, that items was vanished initially)

### ISSUE THREAD

**Issue by Melodeiro** [CleverRaven/Cataclysm-DDA#47568]
# Describe the bug

I think this was caused by trying to pick up multiple "big" items, which can be held only by hands. Before the bug i saw multiple dialogs to do something with item in your hands (drop or put in inventory, and inventory option was disabled, because i just picked that item to the hands, because inventory is full). Then i was attacked during proccess of picking up next item, and everything, except item in my hands was just vanished.

The item in hands was also a power armor, so maybe game has tried to put something in its inventory (you can store items in container if they are in your hands as well). The very frustrating bug (because i lost a lot of valuable items), but i really not sure how to reproduce it for 100%

The fact, that immediately after killing that enemy i was able to pick up other items and had a lot of space in my inventory tells, that items vanished directly from my inventory

# Steps To Reproduce

Put a lot of items to the vechile storage
Equip multiple containers
Pick up everything with , key
Get to the point when the game offering you to drop items from your hand to pickup another
Agree to drop the item
Get attacked by enemy during that proccess
Answer "yes" to prevent inventory management, to a warning of being attacked
Everything (or most items) except item from your hands is vanished

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.E-9679-gf9fcf55 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    XEAS [XEAS],
    Mining Mod [Mining_Mod],
    More Survivor Stuff [more_survivor_stuff],
    Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
    Manual Bionic Installation [manualbionicinstall],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    <color_light_blue>BL9-100%-monster-resilience-version</color> [BL9_100monres],
    <color_red>Sierra Madre</color> [sierra_madre],
    Generator mod [generatormod],
    Make bows great again [bow_opness],
    Advanced Gear Goats Edition [adv_gear],
    Advanced Technologies [advtech],
    Adurnsyl's Assorted Arms and Armour [AAA],
    Armor Up! Survivor Expansion [ArmUpSurvEx],
    Arsenal Breach [arsenal_breach],
    Beta National Guard Camp [national_guard_camp_alt],
    No Fungal Monsters [No_Fungi],
    Military Professions Mod [More_Military],
    Sly's Beauteous Beastly Bugfix [sly_beastfix],
    Disable NPC Needs [no_npc_food],
    Bionic Slots [cbm_slots],
    Graphical Overmap [Graphical_Overmap],
    Portable Autodoc [portable_autodoc],
    Safe Autodoc [safe_autodoc],
    Safe Portable Autodoc [safe_portable_autodoc]
]

**Comment by Melodeiro** [comment]
Oh lol, just found all items, they was in that power armor inventory. So the problem is UI not saying, that power armor has contents 
![image](https://user-images.githubusercontent.com/2702567/108200265-4336d280-712f-11eb-9c62-c0f2b0399266.png)
So it just lacks "> XX items" in its name

**Comment by RadHazard** [comment]
It's not just the combat exoskeleton that does this.  I've noticed toolboxes also lack a "> XX items" label despite containing items, and I assume there's probably more

**Comment by Jamuro-g** [comment]
> It's not just the combat exoskeleton that does this. I've noticed toolboxes also lack a "> XX items" label despite containing items, and I assume there's probably more

i am pretty sure for toolboxes (and ordinary tools) that is intentional. But if not i can take a look

**Comment by RadHazard** [comment]
> > It's not just the combat exoskeleton that does this. I've noticed toolboxes also lack a "> XX items" label despite containing items, and I assume there's probably more
> 
> Yeah good catch, they were marked as tools. gonna add that to my fix

Ah, sounds like leftover behavior from when they used to be magic do-everything tools instead of containers.  In that case, I don't think there's going to be more bugged containers after all.  I certainly can't think of any off the top of my head, anyway.
