### ISSUE TITLE
Enable "invocation" of spells (and other mechanisms?) in mapgen

### ISSUE THREAD

**Issue by actual-nh** [CleverRaven/Cataclysm-DDA#47564]
# Is your feature request related to a problem? Please describe.

In contemplating various map transformations to emphasize differences between Magiclysm and vanilla CDDA - see #46057, specifically [this comment](https://github.com/CleverRaven/Cataclysm-DDA/discussions/46057#discussioncomment-310276) - it became evident that there were a very logical set of transformations already mostly encoded that very well fit the effects of mages going nuts: spells. But there does not appear to be any mechanism to invoke a spell's effects during mapgen. (There are map transformations that spells cause, but not the other way around.) One instance would be creating lines of wreckage/burnt terrain/whatever from spells with a "line" shape.

# Describe the solution you'd like

During appropriate stages (probably after item creation but before any monster placement) of mapgen - not necessarily mapgen with precisely specified houses or whatever, but _also_ something like a forest or field - enable the invocation of spells in semi-randomized locations (and directions, where appropriate, such as a line-shape spell). Note that, since spells are not necessarily Magiclysm magic, this could also be useful for more variety in, say, the leftovers from a battle or the positioning of both short-term and long-term (e.g., "vent") fields.

# Describe alternatives you've considered

Expansion of the use of some of the existing hardcoded mapgen transformations, preferably with more control (e.g., specifying portal effects). For instance, generating fields with effects on the already-generated map (by which I mean down to details like items). This somewhat goes against the preference to move away from these transformations, and at least some parts of these (field generation, most notably) could just as well be done via spells.

# Additional context

Ping: @KorGgenT, possibly @anothersimulacrum, @superninjakiwi, @Venera3?

My current ability to program much is rather limited. I can read over what people are doing and comment with very little expenditure of time (to be immodest, I read at over 1,000 words per minute and type at professional secretarial speeds); getting programs to work is much more finicky and time-consuming. I might be able to do some of the above, but it may be a while before I can do so (e.g., between semesters). (I also have some other areas to work on in CDDA, of course!)

**Comment by actual-nh** [comment]
Possible that #48137 will "fix" this one.

**Comment by Zireael07** [comment]
Do the recent EOC systems cover this? I believe so?
