### ISSUE TITLE
JSON relative/proportional flags for ammo don't work

### ISSUE THREAD

**Issue by souricelle** [CleverRaven/Cataclysm-DDA#47565]
# Describe the bug

Shotgun ammo types (slug, 00, bp, scrap, reloaded, etc) all have the same recoil, range, and dispersion, except slugs which all have a flat 100. This is because they have JSON entries like:

    "proportional": { "damage": { "damage_type": "bullet", "amount": 0.1 }, "recoil": 0.4, "loudness": 0.6 },
or
    "proportional": { "price": 0.7, "damage": { "damage_type": "bullet", "amount": 0.9 }, "dispersion": 1.1 },

Further investigation revealed that this was an issue with the proportional/relative flags and affects all ammunition and possibly other items, not just shotguns. Price and damage modifiers are applied, but nothing else.

# Steps To Reproduce

Look at the different types of shotgun shell (or any other ammunition that has child objects that apply proportional/relative stats from parents) and note that only modifications to price and damage are being applied. 

# Expected behavior

Items should be properly applying relative/proportional stats so that black powder/reloads are less accurate than factory-built and variant ammunition should actually have varying stats.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-9666-gecae002 [32-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Stats Through Skills [StatsThroughSkills],
    Aftershock [aftershock],
    Aftershock - UndeadPeople Tileset [AftershockUDP]
]

(I happened to be running aftershock when I tested this but this is not an Aftershock issue)

**Comment by ZhilkinSerg** [comment]
Yeah, `damage` in `islot_ammo::load` uses `assign` function for data loading (which supports `relative` and `proportional`), while `range`, `dispersion` and such are using `optional` function which does not support `relative` or `proportional`.

**Comment by Qrox** [comment]
Caused by #39899. Changing `optional` back to `assign` may fix the issue, but there might be some reason it was changed that way? Pinging @KorGgenT.

**Comment by KorGgenT** [comment]
yeah definitely, i'd like us to move to optional and mandatory rather than assign as they're parts of generic_factory.
