### ISSUE TITLE
Error: Tried To Put Too Many Charges Of Ammo In Item

### ISSUE THREAD

**Issue by Cpl-Jordan** [CleverRaven/Cataclysm-DDA#47578]
# Describe the bug
When you re-enter a house you already have gone though and the items have reloaded into the game the game seems to want to put more "charges" into Candles, Butane Lighters, Matchbooks, Markers, and Inhalers making them then have max charge.

# Steps To Reproduce
1. Walk to any building that will spawn (Candles, Butane Lighters, Matchbooks, and Inhalers)
2. Don't take any of the items and walk far away and then come back and a error should pop up.
3. Look for the (Candles, Butane Lighters, Matchbooks, and Inhalers) and they should have max charges.

If that doesn't work try step 1 and after that quit to main menu and reload the game. After that the game should load the world and you should see the error pop-ups and proceed to step 3.

# Expected behavior
Being able to go back to base and not having the butane fairy fill all my lighters back up.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-9727-gfc5b702 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context
Here is the debug log as well as the save: [Debug_log&Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6000065/Debug_log.Save.zip)

**Comment by Trioct** [comment]
I had issue with this too. Probably from #47436. @KorGgenT

**Comment by Digi1980s** [comment]
Same here.

**Comment by actual-nh** [comment]
Possibly, when deciding whether to move charges to ammo, as well as checking for an item having a magazine pocket type check `!type->can_have_charges()`?

**Comment by KorGgenT** [comment]
drat. if my pr is the cause, i suppose the easiest thing to do is check the version number

**Comment by aerrant** [comment]
@KorGgenT It is, actually. To reproduce this, you'll just have to start a fixed scenario, then save and load. Cheers :)

**Comment by wapcaplet** [comment]
Confirmed in 0.E-9737-g511ddcb179

1. Start a new game in vanilla (I used the "Survivor" scenario)
2. Save and quit
3. Load again

A few examples of the errors:

```
DEBUG    : error: item butane cannot fit into pocket while loading: tried to put too many charges of ammo in item
DEBUG    : error: item extinguishing_agent cannot fit into pocket while loading: tried to put too many charges of ammo in item
DEBUG    : error: item graphite cannot fit into pocket while loading: tried to put too many charges of ammo in item
```

All appear to come from the same part of `item_contents::combine`:

```
FUNCTION : void item_contents::combine(const item_contents &, const bool)
FILE     : src/item_contents.cpp
LINE     : 335
```

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-9737-g511ddcb179 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]
