### ISSUE TITLE
Program crash when '+' removing last backpack pocket item containing items

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#47571]
# Describe the bug & # Steps To Reproduce

So I was looting, and didn't have enough space.  So I put on some extra backpacks for more volume, as one does.  Got to a car I found, started taking the pockets off with the '+' menu, directly unequipping them.  I also took off some pants at this time as well, iirc.  When I took off the last backpack, the program immediately crashed to desktop.

Items were in these backpacks, and kept getting shifted to the remaining ones until the last.  I'm pretty sure with the last backpack, that the remaining pockets couldn't carry enough stuff.

I was also wielding a weapon.  (Baseball bat)  I'm not sure if it matters, but I was inside a vehicle that had nearby containers.  I'm not sure if that influences the logic of where things should be dropped.

# Expected behavior

Stuff would just go to the floor without a program fault.

# Versions and configuration

Version 0.E-9702-gdc41673 (tiles)
Build 11469
Windows 10

# Additional context
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5996760/crash.log)
[mods.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/5996775/mods.txt)

**Comment by wapcaplet** [comment]
Confirmed in 0.E-9727-gfc5b70245d

**Comment by wapcaplet** [comment]
Looks to be the same or similar to #44494 and #44499.
