### ISSUE TITLE
Candles extinguished moving up/down stairs

### ISSUE THREAD

**Issue by Tyranork** [CleverRaven/Cataclysm-DDA#47577]
issue: candles are extinguished when traveling up or down stairs with them.

**Comment by wapcaplet** [comment]
Can you provide your game version number?

I could not reproduce this in 0.E-9727-gfc5b70245d. With a lit candle, I can go up and down stairs and ladders without it going out.

**Comment by Jamuro-g** [comment]
tested in build 11476 and couldn't reproduce the issue.

**Comment by OliveChukar** [comment]
Tested in 0.E stable 10478 unable to reproduce. Tested apartment tower stairs and horse barn ladder.

**Comment by anothersimulacrum** [comment]
3 failures to reproduce - if someone can reproduce it, please provide steps and ping me and I (or someone else) will open it.

**Comment by Tyranork** [comment]
I have to be honest I didn't record which version, I've updated since then
and not had this issue, must have been something wrong on my end.

-DEC
