### ISSUE TITLE
Improve Spoilage view in advanced inventory mode

### ISSUE THREAD

**Issue by RadHazard** [CleverRaven/Cataclysm-DDA#47575]
# Is your feature request related to a problem? Please describe.
Advanced Inventory mode has a sort-by-spoilage option, but it's sorely lacking in visible data compared to the Eat menu.  At the moment, it doesn't show any information at all other than the order in which your items will spoil.

# Describe the solution you'd like
When sorting by spoilage, at the bare minimum I'd like to see columns for freshness and time-to-spoil (the latter only if you have enough food handling skill to actually see it, of course).

Some way to filter out non-perishable items would also be a nice-to-have.  The remainder of the columns from the Eat menu would also be nice, but may be better suited for different sorting modes (e.g. sorting by calories or satiety).

# Describe alternatives you've considered
Making the Eat menu show this info for non-edible items, but that's probably not the best solution.

# Additional context
Lots of data (but only for edible items):
![image](https://user-images.githubusercontent.com/6283552/108293894-b6bafd00-718c-11eb-82d2-74f387bf08c6.png)

Not so much data:
![image](https://user-images.githubusercontent.com/6283552/108293624-a0ad3c80-718c-11eb-9c41-273909941d54.png)

The lack of item coloring for items in containers in Advanced Inventory mode is also painful, but that's fixed by #47426 so I didn't mention it here

**Comment by int-ua** [comment]
I don't understand, are a lot of players just miss Advanced Inventory somehow?

**Comment by RadHazard** [comment]
D'oh, that one's on me.  I do use advanced inventory for a lot of stuff but I didn't think to check for a spoilage view for whatever reason.

Looking at the view, I still think it falls short of my needs -- it doesn't seem to actually _display_ how long each item has left until spoiling even though it does sort by it, which is the main benefit of the table on the Eat screen.  I use it as more of a quick overview of "how long do I have to do something with this food" rather than "what do I eat first?"  It seems like a simple enough addition, though.  Just need to add another column for time remaining when sorting by spoilage (assuming that's easy?).

I can edit this issue to reflect that or create a new one, whichever makes more sense

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
