### ISSUE TITLE
NPCs who eat out of camp stores complain about hunger and the larder being empty even when it's not

### ISSUE THREAD

**Issue by RadHazard** [CleverRaven/Cataclysm-DDA#47596]
# Describe the bug
If you use faction camps to feed NPCs, they will eventually enter a state of being perpetually hungry.  They do still consume calories from the camp and don't seem to be in danger of starving or losing weight, but they remain forever hungry.   They also refuse to train you because of hunger and will randomly complain that the faction camp store is empty, even though it isn't.

# Steps To Reproduce
1. Recruit an NPC
2. Build a faction camp
3. Stock the camp with millions of calories of food
4. Edit the NPC's needs so that they are hungry and have less than 52250 stored kcal (the number at which they start eating from the camp larder)
5. Observe the NPC suffer from hunger pangs despite being well-fed, and also inexplicably complain about an empty camp larder immediately after eating from it

# Expected behavior
NPCs that are fed from faction camp stores behave as if they were fed with ordinary food and don't complain about phantom hunger pangs

# Screenshots
NPC alternating between complaining about the larder being empty and eating from the (very much not empty) larder
![image](https://user-images.githubusercontent.com/6283552/108460348-5d2bfe80-7270-11eb-8aa6-9c914854ca24.png)

The actual needs value of the NPCs immediately after they just ate from the camp stores, in my main save.
![image](https://user-images.githubusercontent.com/6283552/108461401-8ea5c980-7272-11eb-8cde-df9ed489b6e6.png)

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.2 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-9702-gdc4167363d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context
~~Something else weird is going on with NPCs deciding to eat from camps.  While trying to reproduce this bug, I had a problem where my debug NPCs failed to even attempt to eat from the camp larder.  They would just sit around complaining about hunger for a few days.  Eventually something happened that caused them to start eating from the camp stores, at which point this issue was reproducible.~~

Figured out the cause of this -- NPCs only eat from camps when their stored calories are below 52250.  Waiting long enough for them to drop below this or manually editing their stored calorie numbers will immediately cause them to start eating from camps

**Comment by RadHazard** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/511ddcb179ae948d9366c4954ec79bc96118457e/src/npcmove.cpp#L3817-L3827

This seems to be the relevant code.  I think I can see why NPCs are complaining about the empty larder:  `camp_kcals` can end up zero if the NPC is simply not hungry enough to want to eat food, which incorrectly triggers the "not enough food!" complaint.  

Why they continue to be perpetually hungry despite having a healthy number of calories is a different question.  I originally assumed the camp was simply not filling their stomachs, but I believe that's what `mod_hunger()` does, so that doesn't seem to be the cause.

**Comment by actual-nh** [comment]
> This seems to be the relevant code. I think I can see why NPCs are complaining about the empty larder: `camp_kcals` can end up zero if the NPC is simply not hungry enough to want to eat food, which incorrectly triggers the "not enough food!" complaint.

Not quite not hungry enough - not low enough on stored calories.
 
> Why they continue to be perpetually hungry despite having a healthy number of calories is a different question. I originally assumed the camp was simply not filling their stomachs, but I believe that's what `mod_hunger()` does, so that doesn't seem to be the cause.

They are at 300 hunger immediately after eating?

**Comment by RadHazard** [comment]
> Not quite not hungry enough - not low enough on stored calories.

Right, yeah, that's what I meant.  Suppose I should be more precise given the two different concepts are both at play here.

>They are at 300 hunger immediately after eating?

That's correct.  In that screenshot I posted, I had just returned to my camp after an away mission with my NPCs, and that image was taken after I got the "thanks for the food" messages.  You can also see their stored calories are right at the limit, so I know they definitely ate something.

**Comment by actual-nh** [comment]
Huh. If they had positive hunger but it was below 300, I could understand that - hunger and kcals are not quite equivalent. But 300 is the hunger maximum.

**Comment by actual-nh** [comment]
You may wish to make a separate issue regarding the hunger, after your PR is in.
