### ISSUE TITLE
Bug with the levitation. Magiclysm.

### ISSUE THREAD

**Issue by DesLandysh** [CleverRaven/Cataclysm-DDA#47598]
Confirmed.

### **Describe the bug**
I've just tried to repeat levitation (series of movement in the air), and it works again. I already wrote in discord channel, now this is an issue.

### **Steps To Reproduce**
1) +2 Z-lvl Wizard Tower (on that floor there is closed room with plastic golems).
2) It doesn't matter whether you on a side of tower or not, it must have enough range able to translate you into an air (empty space tile).
3) Cast Phase Door spell.
4) For your unfortunate, you have a chance to appear in the air.
5) Repeat the spell, and you have a chance to move in the air far from walkable tiles.

### **Expected behavior**
It's expected that the Phase Door spell not to translate you into the air

### **Versions and configuration & debug.log**
08:53:41.792 ERROR SDL : (error message will follow backtrace)
  #0
    (dbghelp: @0x6a8056[cataclysm-tiles.exe+0x2a8056]), 
    (libbacktrace: Z21debug_write_backtraceRSo+0x56@0x6a8056),
    (libbacktrace: 0x6a8056    [unknown src]:0    [unknown func]),
  #1
    (dbghelp: @0x6a8af6[cataclysm-tiles.exe+0x2a8af6]), 
    (libbacktrace: Z8DebugLog10DebugLevel10DebugClass+0x2f6@0x6a8af6),
    (libbacktrace: 0x6a8af6    [unknown src]:0    [unknown func]),
  #2
    (dbghelp: @0x1013d91[cataclysm-tiles.exe+0xc13d91]), 
    (libbacktrace: Z12printErrorIfbPKc.part.11+0x21@0x1013d91),
    (libbacktrace: 0x1013d91    [unknown src]:0    [unknown func]),
  #3
    (dbghelp: @0x101e1f9[cataclysm-tiles.exe+0xc1e1f9]), 
    (libbacktrace: Z15save_screenshotRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x149@0x101e1f9),
    (libbacktrace: 0x101e1f9    [unknown src]:0    [unknown func]),
  #4
    (dbghelp: @0x6c82a5[cataclysm-tiles.exe+0x2c82a5]), 
    (libbacktrace: ZN10debug_menu5debugEv+0x5815@0x6c82a5),
    (libbacktrace: 0x6c82a5    [unknown src]:0    [unknown func]),
  #5
    (dbghelp: @0x83e197[cataclysm-tiles.exe+0x43e197]), 
    (libbacktrace: ZN4game13handle_actionEv+0xe87@0x83e197),
    (libbacktrace: 0x83e197    [unknown src]:0    [unknown func]),
  #6
    (dbghelp: @0x7ea907[cataclysm-tiles.exe+0x3ea907]), 
    (libbacktrace: ZN4game7do_turnEv+0xdb7@0x7ea907),
    (libbacktrace: 0x7ea907    [unknown src]:0    [unknown func]),
  #7
    (dbghelp: IMG_LoadWEBP_RW+0x7c6049@0x1b3fc49[cataclysm-tiles.exe+0x173fc49]), 
    (libbacktrace: main+0x1239@0x1b3fc49),
    (libbacktrace: 0x1b3fc49    [unknown src]:0    [unknown func]),
  #8
    (dbghelp: @0x4013ed[cataclysm-tiles.exe+0x13ed]), 
    (libbacktrace: _tmainCRTStartup+0x23d@0x4013ed),
    (libbacktrace: 0x4013ed    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crtexe.c:336    __tmainCRTStartup),
  #9
    (dbghelp: @0x4014fb[cataclysm-tiles.exe+0x14fb]), 
    (libbacktrace: WinMainCRTStartup+0x1b@0x4014fb),
    (libbacktrace: 0x4014fb    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crtexe.c:186    WinMainCRTStartup),
  #10
    (dbghelp: BaseThreadInitThunk+0x14@0x7ffaa8847c24[KERNEL32.DLL+0x17c24]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #11
    (dbghelp: RtlUserThreadStart+0x21@0x7ffaa91ed721[ntdll.dll+0x6d721]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
Backtrace emission took 0 seconds.
(continued from above) ERROR : src/sdl_wrappers.cpp:26: save_screenshot: cannot save screenshot file: ./save/Боттом/screenshots/[Р­С„С‚РѕРЅ РљР°СЂСЂРё]__05-53-41_RTZ 2 (зима).png: Couldn't open ./save/Боттом/screenshots/[Р­С„С‚РѕРЅ РљР°СЂСЂРё]__05-53-41_RTZ 2 (зима).png
09:01:35.077 :  GAME REPORT:
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-9737-g511ddcb [64-bit]
- Graphics Version: Tiles
- Game Language: Системный язык []
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у NPC [no_npc_food],
    Бионические профессии [package_bionic_professions],
    Магиклизм [magiclysm],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    MSX Indicators: REMIX [UDP_REMIX_INDICATORS],
    Графическая карта [Graphical_Overmap],
    Графическая карта - Маглицизм [Graphical_Overmap_Magiclysm]
]

### **Screenshots**
On the screenshot there position after casting the spell for the 2nd time, the 1st one it translocate character to closest tile of empty space after walkable tile.
![cdda levitation](https://user-images.githubusercontent.com/60898828/108464949-1f3fd200-7292-11eb-9b1e-07dc1ebe6eca.png)

**Comment by GGgatherer** [comment]
I think the bug is not phase door transporting the character onto open air, it's the character not falling to his death after transporting.

**Comment by superninjakiwi** [comment]
#47305 and issues that mention it are probably somewhat related. Teleportation should either not teleport you onto air, or should trigger the ledge trap while moving you. Same thing with deep water; either you don't teleport there, or it should check if you should sink.

**Comment by actual-nh** [comment]
Ping: @KorGgenT?

**Comment by DesLandysh** [comment]
> #47305 and issues that mention it are probably somewhat related. Teleportation should either not teleport you onto air, or should trigger the ledge trap while moving you. Same thing with deep water; either you don't teleport there, or it should check if you should sink.

Confirmed. They are related
Phase door spell works on deep water too. Same levitation over deep water and during holding NumPad5... until you move to another tile.
If you sink as a stone, and and cast Phase door spell, you're still have hmm 'underwater flag' even if already on a grass tile until you move to another tile.

after the first cast.
![cdda levitation2](https://user-images.githubusercontent.com/60898828/108522453-e6c5e580-72dd-11eb-8575-097420d61cd5.png)
after the second cast. Still on the deep water tile.
![cdda levitation3](https://user-images.githubusercontent.com/60898828/108522458-e7f71280-72dd-11eb-8f10-0b771fbf7272.png)

**Comment by actual-nh** [comment]
The underwater flag being set until moving might be related to #46488, although there it's not moving with respect to the vehicle, not the terrain.

**Comment by Maleclypse** [comment]
GuardianDll — Today at 11:01 AM
#47598 can be closed now, there was a pr that fixed it already
