### ISSUE TITLE
Dropping stolen items and picking them up again changes their owner

### ISSUE THREAD

**Issue by Saicchi** [CleverRaven/Cataclysm-DDA#47592]
# Describe the bug

Dropping an item you stole from an npc, then dropping the item yourself, makes the item yours.

# Steps To Reproduce

1. Pick up a stolen item
2. Drop it
3. Pick up the item again
4. Notice how item is now yours and the NPC won't ask about it anymore

# Expected behavior

Dropping an item stolen from the NPC doesn't make you the owner of it.

# Screenshots
None

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.E-9652-g1e40b428c6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]
]

# Additional context

This can be easily abused using the fact that when an NPC asks you to drop the item you stole, the items are dropped on top of you, as such you can continuously steal the item and have it being dropped until you can move somewhere the NPC won't see, after that you can use the bug described above to get the item.

**Comment by OliveChukar** [comment]
Tested in 0.E-9739-g44d04c5 with core content pack dda only. Was able to reproduce. The lost stolen flag only seemed to happen if item is picked up and dropped out of NPC view. When I was testing a crash happened I will try to attach the crash file.
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6011997/crash.log)

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-6029.  Picked up a bread knife owned by prisoners. NPC who noticed that told me to drop it. I dropped it under myself. The knife didn't change its owner and still belongs to prisoners.
![изображение](https://user-images.githubusercontent.com/11132525/153707634-5c564f3e-c927-47aa-9a0a-72cfa3baa2d6.png)
![изображение](https://user-images.githubusercontent.com/11132525/153707685-c6a2bd79-d426-4c78-aed0-51b21aa07af9.png)
![изображение](https://user-images.githubusercontent.com/11132525/153707710-ac71e441-1c1c-49ff-9751-64ee2c409a22.png)

**Comment by Saicchi** [comment]
Haven't checked in the most recent version but bug still happens in `0.F-5670-g1bba9b703b`.

One thing I haven't mentioned in my post ( I'll update it ) and OliveChukar figured out is that **the item must be dropped and picked up outside the NPC view**.

**Comment by Night-Pryanik** [comment]
Well, I tested your case too. Here's the results.

There's two NPCs in a completely dark room.
![изображение](https://user-images.githubusercontent.com/11132525/153720781-52381fde-86eb-4acf-8cca-3511c967e63f.png)

I want to take one of the frying pans NE of me. Frying pans are owned by prisoners.
![изображение](https://user-images.githubusercontent.com/11132525/153720840-f61dc15d-ce19-4c12-957a-a514c61d417e.png)

I'm stealing it under their noses. Game warns me that this would be considered as stealing.
![изображение](https://user-images.githubusercontent.com/11132525/153720891-29206d59-f3a5-459d-acfe-999675e9c5e6.png)

I stole it, and the pan in mine, as I'm its owner now.
![изображение](https://user-images.githubusercontent.com/11132525/153720929-02dc6d66-0927-4ee7-b8d8-6afeb2cf20cf.png)

Prisoners don't tell me to drop the pan.
![изображение](https://user-images.githubusercontent.com/11132525/153721007-ba5d0073-13f2-44df-b78c-f191756c3610.png)

I find this behaviour (changing owner if no one notices the theft) working as intended.
