### ISSUE TITLE
Attempted a recipe with no available components & (almost) infinite consume missing components

### ISSUE THREAD

**Issue by TandemE** [CleverRaven/Cataclysm-DDA#47591]
# Describe the bug

Trying to craft some food the first day, I received an error: **Attempted a recipe with no available components!**, even though I had them. Couldn't craft clean water or fried eggs, but to my surprise, roasted acorns worked. Tried crafting cattle fodder, as it requires almost nothing, same error

I tried dropping the hide bag and cudgel from my hands (thinking maybe I couldn't pick up the stock pot for boiling). This allowed me to start crafting the fried eggs, but then I received the prompt: **Consume missing components and continue crafting?** (vegetable cooking oil). Saying "Yes" advances the crafting by a minuscule amount. and brings up the prompt again. Hitting "Y" a lot actually completes the craft, and the "missing components" are only consumed once in the end.

# Steps To Reproduce

Unfortunately, I couldn't reproduce the issue quickly with a fresh character, but here is the save file right where it happens (the world has one character only).

[Arcanea.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6006548/Arcanea.zip)

Try these steps with and without wearing the hide bag, as the issue changes.
1. Try crafting "cooked wild vegetables", "cattle fodder", "clean water" or "fried eggs"  -> One of the above described strange behaviours happens
2. Try crafting "roasted acorns", "crude wooden arrow" (and possibly many others) -> no issue at all

# Expected behavior

I would expect crafting to work, given the materials and tools are available.

# Screenshots

# Versions and configuration

- OS: Windows 10 Pro Education (version 20H2, build 19042.804, Experience Pack 120.2212.551.0)
    - (by game report: OS Version: 10.0 2009)
- Game Version: 0.E-9737-g511ddcb [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Packaging [Packaging],
    Mining Mod [Mining_Mod],
    More City Locations [cityside],
    No Rail Stations [No_Rail_Stations],
    Stats Through Skills [StatsThroughSkills],
    Arcana and Magic Items [Arcana],
    Arcana - UndeadPeople Tileset [ArcanaUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mining Mod - UndeadPeople Tileset [Mining_ModUDP],
    More Locations [more_locations],
    More Locations - UndeadPeople Tileset [more_locationsUDP],
    MSX Indicators: Xotto [UDP_XOTTO_INDICATORS],
    Alternative Map Key [alt_map_key],
    More Survivor Stuff [more_survivor_stuff]
]

# Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6006541/debug.log)

I also found a related open issue (a year old), with the same error message, but then it was specific to batch crafting: https://github.com/CleverRaven/Cataclysm-DDA/issues/37239

**Comment by PatrikLundell** [comment]
It sounds like you're subjected to intended behavior with the fried eggs, but with an unintended frequency. If you fail crafting, some resources may be lost in the failure and you're then prompted to answer whether you want to continue or not. Losing resources that way can eventually result in you running out of the resource so you can't continue. However, I don't know what would cause a simple fried eggs recipe to fail repeatedly (somehow getting negative crafting skill, or something like that?).

**Comment by TandemE** [comment]
> If you fail crafting, some resources may be lost in the failure and you're then prompted to answer whether you want to continue or not. Losing resources that way can eventually result in you running out of the resource so you can't continue.

Strangely it does not consume any resources, only when the craft is actually completed. E.g. when crafting fried eggs, even after being promoted countless times to use 2 cooking oil, I still had 398 left of the initial 400. 

Also, wearing the hide bag prevents crafting it completely, as I receive the "Attempted a recipe with no available components!" message.

**Comment by TandemE** [comment]
I've investigated a little bit and created a more accurate bug report: https://github.com/CleverRaven/Cataclysm-DDA/issues/47842
