### ISSUE TITLE
Vehicles on Experimental have windshield and quarterpanel issues.

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#47603]
# Describe the bug

The appearance for vehicles no longer use the old symbols for vehicles parts, specifically `"` for windshields and lines for quarter-panels, and so on. Instead, they are replaced by `T` symbols.

# Steps To Reproduce

1. Spawn a vehicle on a fresh save of 0.E-3 with the debug menu.
2. Observe appearance.
3. Spawn the same vehicle on a fresh save of the newest experimental.
4. Observe appearance.

# Expected behavior

The vehicles should look the same between game versions. At the very least I would expect some consistency with ASCII, that is, retaining their old symbols.

# Screenshots

Freshly spawned vehicle on 0.E3: 
![cdda_0 E_veh](https://user-images.githubusercontent.com/25373560/108488385-323fba00-7305-11eb-91f8-f1e531d5e689.png)

The same vehicle freshly spawned on Experimental Build 11477:
![cdda_0 F_veh](https://user-images.githubusercontent.com/25373560/108488497-53a0a600-7305-11eb-891c-b88d33b3f559.png)

# Versions and configuration

 - OS:Fedora 33
 - Game Version: 0.E-3/Experimental Build 11477
 - Graphics version: Tiles
 - Ingame language:English
 - Mods loaded for 0.E-3: [dda, no_npc_needs]
 - Mods loaded for Experimental Build 11477: [dda, no_npc_needs, bionic_professions]
 - 
# Additional context

**Comment by Fosheze** [comment]
I believe that this is intended behavior from #42477. The different symbols are mean to be used by tilesets to represent different directional versions of the same tile but I can see how it would look wrong in curses. I don't think that there's any way to make them look like they did besides maybe changing the symbol the chiral parts use.

**Comment by actual-nh** [comment]
>I don't think that there's any way to make them look like they did besides maybe changing the symbol the chiral parts use.

That would be nice. As it is, what character is used where makes very little sense (T on one side but not on the other, for instance).

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-11125.
