### ISSUE TITLE
Could not put &item into &pocket_item > # items, aborting. message confusion 

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#47608]
It was confusing to me that you couldn't fully fill non-rigid containing pockets without wielding the item.  Sometimes not even at all, with the pillowcase.  At first I thought there was a bug, as how can a 15L pillowcase not hold a 1L pillow, or a plastic bag not hold more than two dozen seeds, but then I finally figured out that my bags and pillowcases were in a tiny pocket in my pants, and everything now made sense.

# Describe the solution you'd like
It would be nice if the log mentioned that the container could only be filled further when wielded, and outside of a pocket itself that it is full.  A message such as:
Could not put &item into &pocket_item > # items due to confined space, aborting.
would be quite nice, I think.

# Describe alternatives you've considered
Well, I haven't really considered any, as I spent an hour or so trying to understand the 'bug' before I found out I just didn't have the information myself.  Maybe an option to move the nested pocket to a pocket that has more volume, or to be wielded, or be dropped to the floor and filled?  All of those involve significantly more contextual checks, and seem harder to implement.

I suppose if you want to make it easier to implement, possibly throw a message into the log when a higher pocket it not found to have enough volume.  I mean, that fail state is already checked for, so why not let the player know?  It would make the log a bit messier though.
Eg, turn what it is now into:
&Pocket_container too small to continue filling nested container, aborting.
Could not put &item into &pocket_item > # items, aborting.

# Additional context
I really like the idea that we can't overfill nested pockets, great job on the programmers who implemented the checks.

**Comment by Fosheze** [comment]
Duplicate of #47070.

**Comment by chrispikula** [comment]
Ah, thanks, I'll close this then as a duplicate.
