### ISSUE TITLE
Started outside prison during prison break.

### ISSUE THREAD

**Issue by OliveChukar** [CleverRaven/Cataclysm-DDA#47611]
# Describe the bug
Started a run with the prison break start.  Character started outside prison making the start less challenging then intended.

# Steps To Reproduce
Do not know exactly how to reproduce. This bug seems to happen randomly with starts like prison break and lab escape.

I guess you could keep restarting new runs in new worlds until it happens.

# Expected behavior
Challenge starts put character where they say they will.

# Screenshots

# Versions and configuration

# Additional context
I have seen past reports of this issue on the forums and reddit but could not find a report here. Sorry if this is a duplicate report.

[save prison.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6012101/save.prison.zip)

**Comment by OliveChukar** [comment]
Game info got eaten by template. 


OS: Windows
     OS Version: 10.0 2004
 Game Version: 0.E-9739-g44d04c5 [64-bit]
 Graphics Version: Tiles
 Game Language: System language [english]
 Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by PatrikLundell** [comment]
The template is quite good at hiding info if you fail to remove all the comments (has caught me more than once, hiding all the contents). You can edit the first post to correct that, rather than make a new post, but it took some searching to find how to edit the first post.
