### ISSUE TITLE
Cannot 'i'nsert items from inner container into outer container

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#47625]
# Describe the bug

If container 2 is inside container 1 and there are items in container 2, they are excluded from 'i'nsert menu of container 1. Even if there's enough space/weight for them.

# Steps To Reproduce

1. Make a character with a backpack, wallet and a cash card
2. insert cash card into wallet
3. insert wallet into rucksack
4. select rucksack, 'i'nsert
5. see there is no cash card in the list

# Expected behavior

The game allowing me to put my goddamn cash cards into my rucksack from wallets without making me wield them or move them to other worn containers.

# Versions and configuration

- OS: Windows 7x64
- Game Version: 0.E-9679-gf9fcf55 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills],
    Bionic Professions [package_bionic_professions]
]
Yes, it is b11468 but I couldn't see anything in changelog about this issue.

**Comment by wapcaplet** [comment]
Confirmed in 0.E-9739-g44d04c5c27
