### ISSUE TITLE
Reenactors descriptions no longer align with profession names for female characters

### ISSUE THREAD

**Issue by Dansiman** [CleverRaven/Cataclysm-DDA#47632]
# Describe the bug

Introduced in commit 4c699c8. Historical/Ahistorical Reenactor were refactored to simplify the code by changing the profession name by gender, rather than changing the assigned equipment. While this did resolve an inconsistency in the proficiencies between the two classes, it introduced a new inconsistency, in that the description referring to "the end of the world made traditional gender roles obsolete" is now, for female characters, on the profession that does in fact follow traditional gender roles.

# Steps To Reproduce

1. Create a new character.
2. Make them female.
3. Select the Historical Reenactor profession
4. Notice that the description is the one appropriate for the **A**historical Reenactor profession.

# Expected behavior

The profession description about gender roles is displayed when selecting the class named Ahistorical Reenactor, regardless of your character's gender.

# Additional context

Note: I omitted some of the standard fields from this bug report, because I was able to spot the bug just from reviewing the commit.

**Comment by wapcaplet** [comment]
Confirmed in 0.E-9775-gc020c68eff. As a female character, the "Historical Reenactor" role includes the "traditional gender roles obsolete" description, though the starting proficiencies and equipment (Spinning, Knitting, and sewing supplies) are in fact consistent with traditional gender roles. Functionally, everything appears to be correct; it is only the descriptions that are wrong for female characters.
