### ISSUE TITLE
Terminal doesn't resize when changing terminal width in options (TILES build)

### ISSUE THREAD

**Issue by tristanstraub** [CleverRaven/Cataclysm-DDA#47636]
When changing "Terminal width" (or height) in options, after saving, the terminal rendering does not change scale.

# Steps To Reproduce

1. Build with "make -j4 TILES=1 SOUND=1 RELEASE=1 USE_HOME_DIR=1" on fedora 30.
2. Run ./cataclysm-launcher
3. Select "Settings -> Options -> Graphics -> Terminal width". Change value from 240 to 120.
4. Press ESC, then answer "Yes" to save changes.

# Expected behavior

Rendering scale should change so that font appears scaled.

# Versions and configuration

Commit SHA: 681e80c5bb66b186ffe8b5a95f209e93b4d561ca
OS: Fedora 30
Graphics version: Tiles
Ingame language: English
Option "Fullscreen": Windowed borderless
 
# Apparent fix:

In "sdltiles.cpp", comment out "SDL_GetWindowSize( window.get(), &w, &h );" on line 1375 in function resize_term.
This appears to reenable scaling after terminal width is changed.

**Comment by Qrox** [comment]
I think the `SDL_GetWindowSize` call is there to get the actual resized window size if the `SDL_SetWindowSize` call does not fully respect the supplied size (when the size exceeds the screen size, for example). So it should only skip the `SDL_SetWindowSize` and `SDL_GetWindowSize` calls in fullscreen mode. `toggle_fullscreen_window` also automatically changes the terminal size to fit the full screen when changing from windowed to fullscreen, so there needs to be an option that toggles auto/manual terminal size in fullscreen.

**Comment by jnaviamtc** [comment]
This is also the case on MacOS. 
The only way to get it to work is in Fullscreen mode. However in Fullscreen you cannot leave the Cataclysm window, as in you can't tab out to other applications.

**Comment by dkristoffersson** [comment]
I'm experiencing an issue like this with current experimental linux-tiles-sounds builds. I run cdda from a Linux container on a chromebook. I can change other options, but when I try to change terminal width or height, the game reverts to the prior values after restart.

**Comment by Zireael07** [comment]
I believe this is still an issue on Linux
