### ISSUE TITLE
Disable sound while not playing

### ISSUE THREAD

**Issue by schauveau** [CleverRaven/Cataclysm-DDA#47644]
I am using Linux and I often leave CDDA open in another desktop when I not playing. My soundpack (Chesthole) has several ambient sounds (heartbeat, wind, rain, ...) and I occasionally notice that CDDA has been producing them for hours at a very low volume. By experience, I can tell you that a subliminal heartbeat is not the best way to relax. 

So my proposal is to disable all sounds when the game window is not visible (or loses the focus). If I am not mistaken, something like that is already implemented while sleeping. 

Alternatively, the game could disable the sounds after a certain period of inactivity.

**Comment by actual-nh** [comment]
I am curious. Under what circumstances does it play an ambient heartbeat? When no other sound applies?

**Comment by schauveau** [comment]
In the Chesthole soundpack, the heartbeat indicates low stamina. The volume goes up as the stamina goes down. IMHO, this is a very cool feature. No more stupid death for me because I forgot to stop running.

**Comment by Fosheze** [comment]
>  By experience, I can tell you that a subliminal heartbeat is not the best way to relax.

This is something straight out of Poe's "The Tell-Tale Heart".

I've experienced this as well though. As I don't imagine this will be a high priority issue I did find a way to kind of do this just through linux it's self if you feel like doing a bit of bash coding. I found this bit of code that is setup to mute Spotify but you should be able to edit it to work with the CDDA process fairly easily.

https://askubuntu.com/questions/180612/script-to-mute-an-application

**Comment by schauveau** [comment]
I agree that this is not high priority. The idea of using another program to mute CDDA is interesting but there is also the problem of deciding automatically when the sound must be turned off and on. I would rather have a clean solution in CDDA than a half-baked external hack.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
