### ISSUE TITLE
Processing of errors off by 1 line in at least some cases

### ISSUE THREAD

**Issue by actual-nh** [CleverRaven/Cataclysm-DDA#47641]
# Describe the bug

~~Check2~~Catch2 has been set up to give information about what tests were failed. This mechanism is off by one line in at least two commits:

- [ab4ba67c](https://github.com/CleverRaven/Cataclysm-DDA/pull/47273/commits/ab4ba67cc56a3f2519851c81ba512fe0378a75e8)
- [45b1139](https://github.com/CleverRaven/Cataclysm-DDA/pull/47273/commits/45b1139c5b1f942b390796268de61d8139316465)

In both cases, the test failure is from the function on the line above (76 and 92 for the 45b1139 commit, for instance) where the "Check failure on line ##" (and other parts of the error message) indicate. In other words, the failure is for `CHECK( !info.have_weary_decrease() );`, as can be seen in the build+test logs returning "false" as the expansion.

I had initially thought this was a problem with problem matching, but upon further inspection of the logs, unless github's listing of the lines for the commit is off by 1, ~~Check2~~Catch2 seems to be the problem. For the second of the above, for instance, [see](https://github.com/CleverRaven/Cataclysm-DDA/pull/47273/checks?check_run_id=1884066815).

# Steps To Reproduce

Has already happened twice; I suspect examination of other build logs vs commits may indicate more.

# Expected behavior

Line stated in "Check failure in line ##" and similar would be the correct line.

# Additional context

Ping: @Qrox, possibly @jbytheway and @BrettDong?

**Comment by BrettDong** [comment]
Is line number correct in the log?

**Comment by actual-nh** [comment]
As it turns out, no. So either github's display of the line numbers is off by 1, or check2's display is off by 1. I am currently in the middle of compiling another branch, so am unable to switch to that branch (the same thing is happening with the most recent commit) to check whether the line numbers in the files match.

**Comment by actual-nh** [comment]
I just took a look at my copy of local test results (see [this comment](https://github.com/CleverRaven/Cataclysm-DDA/pull/47273#issuecomment-782721315) for the file), and compared it with [this commit](https://github.com/CleverRaven/Cataclysm-DDA/pull/47273). The local ones are not off by 1 (they are for 76 and 92, which are the line numbers displayed by github).

**Comment by jbytheway** [comment]
When you say check2, do you mean Catch2?

**Comment by actual-nh** [comment]
> When you say check2, do you mean Catch2?

Oh. Yes, sorry!

**Comment by actual-nh** [comment]
(Something I just spotted that I will need to put in another issue/PR - clean-pch does not remove tests/pch/tests-pch.hpp.pch.)

**Comment by BrettDong** [comment]
Is it because outdated PCH?

**Comment by actual-nh** [comment]
Isn't it recompiled on Github and Travis builds? The distribution doesn't have the .pch version for the main pch directory, the tests/pch directory, or the tests/catch directory. (I discovered the above by that my local compiler - clang++ - errored out with the old tests/pch/tests-pch.hpp.pch.)

**Comment by actual-nh** [comment]
From [the raw file](https://raw.githubusercontent.com/actual-nh/Cataclysm-DDA/45b1139c5b1f942b390796268de61d8139316465/tests/weary_test.cpp) of weary_test.cpp in my repository, 76 is indeed the correct line number (copied off, put into a file, and checked) for the first failed test.

**Comment by actual-nh** [comment]
The only things I can see different in the cata_test invocation on my local machine:

- No `--use-colour yes` locally... but it is defaulting to using color.
- No use of parallel.

**Comment by Qrox** [comment]
I remeber there were cases where json errors were reported on the wrong line because the "changed files" tab displays the diff from the base branch, where as the CI builds by merging the PR branch into the master branch, but I'm not sure if that's the case here.

**Comment by actual-nh** [comment]
At least for the github ones, it would help if the github-action format (which isn't used on Travis) would format the line itself so that it could be inserted into the error-matcher's output - e.g., `CHECK( !info.have_weary_decrease() );`.
