### ISSUE TITLE
Closing a door twice locks it and gives incorrect messages

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#47658]
# Describe the bug

When `c`losing a lockable door such as a `bar door` in a prison, then `c`losing it again, the door becomes locked, but the message only says `You close the closed bar door.`

# Steps To Reproduce

1. Start an island prison scenario
2. Find an open `bar door`
3. Close the door
4. Close the door again

# Expected behavior

Closing an already-closed door should not be possible, since it is already closed. A message like "You cannot close the closed bar door" should be displayed, like it is for other doors.

Alternatively, if closing a door a second time is going to cause an irreversible change in state (locking the door), then the player should be prompted for this, and the message should clearly indicate that is what happened.

# Screenshots

Closing a `bar door` multiple times, leading it to being locked:

![image](https://user-images.githubusercontent.com/238395/108649570-dac35a80-747a-11eb-8f48-c9aa668b5da4.png)

Unlike bar doors, a `wood door` can only be closed once:

![image](https://user-images.githubusercontent.com/238395/108649704-1a8a4200-747b-11eb-861b-25cbbd2d3ca8.png)

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-9775-gc020c68eff [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

I can reproduce this door locking behavior in 0.E-3, so it has been like this for a long time. However, opening and closing doors did not show any messages at all until #46421 so I guess was merely a silent source of confusion before that.

**Comment by Saicchi** [comment]
I believe this happens with the closed bar door due to having "close": "t_door_bar_locked", which transforms the door into the locked version when closed. 
A part of the closed bar door description says  `The locking mechanism doesn't appear to be engaged.`, so it might be intentional that the player can close it again to lock it, but the message is still wrong. 
It should at least warn the player that it's going to lock the door.

**Comment by wapcaplet** [comment]
> I believe this happens with the closed bar door due to having `"close": "t_door_bar_locked"` in its furniture definition

Indeed, this line is the culprit, thanks!

This behavior appears to have been in the game not just since 0.E, but since 2013 and possibly longer. PR #3428 converted it to JSON.
