### ISSUE TITLE
Island Prison B scenario no drops from guaranteed drop safes

### ISSUE THREAD

**Issue by Saicchi** [CleverRaven/Cataclysm-DDA#47660]
# Describe the bug

Island Prison B safes did not drop ID cards

# Steps To Reproduce

1. Create a world with less than 1.0x item spawn rate ( ideally 0.01x to increase chance of issue happening ).
2. Open any of the two safes ( they are in the warden room or the Chief room ).
3. ID Card does not spawn from the safe.

# Expected behavior

ID Card would spawn independently of the item spawn rate, since its critical to finish the mission given by the Leader of the Bandits.

# Screenshots

None

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.E-9775-gc020c68eff [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

Using a world with 10.0x item spawn rate instead gave me 10 ID cards.
Maybe it could have a flag or some other way to guarantee the spawn of at least one card.

**Comment by Night-Pryanik** [comment]
That's very strange, as chance to spawn the Id is set to 100%.

**Comment by Saicchi** [comment]
I'm not too familiar with the code for map generation but I found this in `src/mapgen.cpp:1449`
```c++
const int c = chance.get();
// 100% chance = exactly 1 item, otherwise scale by item spawn rate.
const float spawn_rate = get_option<float>( "ITEM_SPAWNRATE" );
int spawn_count = ( c == 100 ) ? 1 : roll_remainder( c * spawn_rate / 100.0f );
 ```
Since the chance is 100% it should spawn exactly one, but when I opened the safe in the Chiefs room in a world with 10x loot spawn I got this.
![image](https://user-images.githubusercontent.com/47158232/108684200-5c45d780-74d1-11eb-9fd1-87f1c4fb4e39.png)
And in the Warden room
![image](https://user-images.githubusercontent.com/47158232/108684328-8ac3b280-74d1-11eb-81aa-895ad3678014.png)

**Comment by wapcaplet** [comment]
Confirmed in 0.E-9804-gbc7931f5a0
