### ISSUE TITLE
Hidden Recipe user interface improvements.

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#47677]
# Is your feature request related to a problem? Please describe.
When I'm hiding recipes, sometimes I'll hide one I didn't mean to, and worse, I won't remember it's name as I make a one by off error.  It's frustrating then going through 3 or 4 pages of unsorted hidden stuff trying to figure out which one I didn't mean to hide.

# Describe the solution you'd like
It would be nice to be able to search through our just hidden recipes, or, barring that, having the last few hidden recipes near the top of the hidden tab list.

Given the plethora of google results for using h:yes or h:no to search for stuff, maybe re-enable that usage?  Most of the links don't say that it no longer works, after all, and it doesn't throw a warning to the log when you attempt to use it.

# Describe alternatives you've considered
Save file editing with a python script.  I mean, sometimes I seriously thing that'd be faster than going line-by-line.
# Additional context
#32901 - Removed the ability to search for hidden recipes.
#32611 - Similar issue, but closed due to the former.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
