### ISSUE TITLE
Increase nursebot assistance range

### ISSUE THREAD

**Issue by Fosheze** [CleverRaven/Cataclysm-DDA#47674]
# Is your feature request related to a problem? Please describe.
As it is getting a nursebot to assist in CBM installation is a bit of an annoying dance trying to get the nursebot in just the right location to get the bonus. Realistically if there was a surgery about to take place in it's vicinity it would just move over to help with it.

# Describe the solution you'd like
Make "ASSIST" have a range of 3 tiles or so.

# Describe alternatives you've considered
-Making the nursebot stand next to the autodoc whenever the player is on the couch. (probably more work than it's worth)

# Additional context
I'm not a C++ expert but looking at the assist code, it looks like the nursebot should already be moving towards the player. I couldn't even begin to guess why that isn't happening but as I said above it shouldn't even need to be adjacent to the player to provide assistance gameplay wise. It should just be assumed that if the player is within a few tiles of the bot, visible, and wearing a doctors badge then the bot will be assisting with the surgery. If we did that then all of the player tracking code in there could probably just be ripped out entirely.
https://github.com/CleverRaven/Cataclysm-DDA/blob/5cc608ccea74ba783c2f1569fafdbc2b9caf0021/src/monattack.cpp#L2951-L2989

**Comment by Fris0uman** [comment]
Snippet of code you shared suggest the bot is already searching in a 6 tile radius to give the bonus and doesn't need to be adjacent. And 6 tile radius, I think, is bigger than the autodoc room the nursebot spawns in.

**Comment by Fosheze** [comment]
> Snippet of code you shared suggest the bot is already searching in a 6 tile radius to give the bonus and doesn't need to be adjacent. And 6 tile radius, I think, is bigger than the autodoc room the nursebot spawns in.

I wasn't sure if that was the attack having a range or making the nurse bot move adjacent to a target in range. In either case that is not the effect seen in game. In game I have always had to do a fun song and dance with the nurse bot to get any sort of bonus and it never seems to work unless it is adjacent to me or the autodoc. Like I said above it should be working but I couldn't even begin to guess why it isn't. My best bet is that the assist "attack" just isn't triggering in the first place for some reason.

I should have probably posted this as a bug report rather than a feature request but I wasn't sure if what is happening right now was intended behavior or not.

**Comment by actual-nh** [comment]
Side note: If the player has an MD and is using their own badge, the name used should be theirs.

**Comment by Fosheze** [comment]
> Side note: If the player has an MD and is using their own badge, the name used should be theirs. (~Some chance - 50%, probably - for a female name if random would also be nice.~ Just use a last name.)

The first part would need some a bit of coding but the second one should be very easy. Just change `Name::generate( target->male ) ) );` to `Name::generate( target->family ) ) );`.

**Comment by Fris0uman** [comment]
So the fact that the nurse bot knows some names is a nice flavour thing but it's a bit dubious because with all infrastructures being down there's no database to access to retreive people's name.

For the effect I don't know, special attacks trigger every fixed amount of turn if the monster is trying to attack. So maybe when they're not hostile it's a bit more random. But it's very likely that the " fun song and dance" you did were useless and the only thing that was important was waitintg long enough around the nursebot for the thing to trigger.

**Comment by actual-nh** [comment]
> So the fact that the nurse bot knows some names is a nice flavour thing but it's a bit dubious because with all infrastructures being down there's no database to access to retreive people's name.

Query a chip in the badge, or scan it and read the name.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
