### ISSUE TITLE
Shivering Mechanics

### ISSUE THREAD

**Issue by morthein** [CleverRaven/Cataclysm-DDA#47671]
# Is your feature request related to a problem? Please describe.
Currently, if you're cold and attempt to go to bed, you will not fall asleep due to shivering even though you may have a blanket on the same place you're attempting to sleep in.

# Describe the solution you'd like
It would be divine if the game could assume you are "wearing" the blanket for the warmth bonuses in the case of sleeping. Otherwise, you have to actually wear the blanket, just to go to sleep. (Note: The blanket DOES apply it's warmth while your asleep, "You use your blanket to keep warm" so I wonder why can't it apply that while attempting to sleep.

# Describe alternatives you've considered
The blanket could simply add warmth to your body for being on the same space as it *and* attempting to sleep. I suppose it could add warmth to you even when spending time there and not sleeping. Or maybe apply the "you use your blanket to keep warm" effect could just apply while in the same place as a blanket.

# Additional context
It's not like wearing the blanket and then taking it off is the worst thing in the world, but attempting to sleep then shivering awake, then having to wear the blanket your sleeping with, then sleep, then wake up and take off the blanket, then drop it, is just repetitive.

**Comment by souricelle** [comment]
Can confirm, this basically makes innawoods starts impossible as there's no way to get a blanket early and the game won't let you sleep even in an improvised shelter with a fire going at midday.

**Comment by NetSysFire** [comment]
This also bypasses "Survivor sleep now" and "You collapse due to lack of sleep", allowing insane sleep deprivation to be possible.

**Comment by Fris0uman** [comment]
So actually `You use your blanket to keep warm` does not do anything
Code starts here: 

https://github.com/CleverRaven/Cataclysm-DDA/blob/74abea8db3dd071c52dbf04b9baf71a28301f902/src/character.cpp#L8222

```cpp
  std::string item_name = is_snuggling();
    if( item_name == "many" ) {
        if( one_in( 15 ) ) {
            add_msg_if_player( _( "You nestle into your pile of clothes for warmth." ) );
        } else {
            add_msg_if_player( _( "You use your pile of clothes for warmth." ) );
        }
    } else if( item_name != "nothing" ) {
        if( one_in( 15 ) ) {
            add_msg_if_player( _( "You snuggle your %s to keep warm." ), item_name );
        } else {
            add_msg_if_player( _( "You use your %s to keep warm." ), item_name );
        }
    }
    ```

and `is_snuggling()` just get the name of the item or items that could be used to keep warm, but as far as I can tell no warmth bonus is awarded there. Unless I'm missing something we're missing a piece of code  so that the sleeping on blanket or cloth shoud give some warmth. OR the message should be removed becasue it's lying.

**Comment by Night-Pryanik** [comment]
Can't confirm on latest experimental as of 15 November 2024.

Made my character feel `very cold!`
![изображение](https://github.com/user-attachments/assets/06654d1d-adfd-4540-a50f-f38e5a17a0a1)

Made my character try to fall asleep, he used the blanket lying on the floor to get warm
![изображение](https://github.com/user-attachments/assets/cce1893f-3f36-407d-9e0e-53bbdadac4a5)
