### ISSUE TITLE
Cannot inject prophylactic antivenom pills

### ISSUE THREAD

**Issue by homebass** [CleverRaven/Cataclysm-DDA#47670]
# Describe the bug

Attempting to use those handy antivenom pills doesn't work, even when you have a syringe in your inventory.  Consume and use menus just yell "You need a syringe to consume that!" at you.

# Steps To Reproduce

1. Spawn antivenom pills.
2. Spawn syringe.
3. Notice that you cannot use the pills.

# Expected behavior

You should be able to inject the antivenom pills if you have a syringe in your inventory.

# Screenshots

None.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-9778-gddb9e36 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

Strange bug, doesn't seem to affect heroin or morphine. I remember being able to inject them like a week ago, I think? So it was probably a recent change that broke it.

**Comment by actual-nh** [comment]
Pills? Via syringe?

**Comment by RadHazard** [comment]
> Pills? Via syringe?

I think this is just a naming issue (unfortunate that we're in string freeze...).  Based on the description, they're not actually pills -- they're described as vials of liquid.
