### ISSUE TITLE
dome lights use more power than aisle lights, but provide less light

### ISSUE THREAD

**Issue by misterprimus** [CleverRaven/Cataclysm-DDA#47689]
# Describe the bug

dome lights use more power than aisle lights, but provide less light

# Steps To Reproduce

1. Spawn a car.
2. Install aisle lights.
3. Turn on dome lights, check how much power is left (how much time remains at this usage level).
4. Repeat step 3, but with aisle lights instead of dome lights.
5. Dome lights result in less power remaining, but provide less light!

# Expected behavior

Light sources should consistently use more power the more light it provides, not the other way around.

# Versions and configuration

 - OS: Win10x64
 - Game Version: 0.E-9804-gbc7931f
 - Graphics version: Tiles
 - Ingame language: Eng
 - Mods loaded: No NPC needs

# Additional context

Not sure if this is being handled by some sort of general power consumption audit or if it belongs there.

**Comment by PaulBlay** [comment]
Are 'dome lights' just included for free with the dashboard and / or vehicle controls? 

(Incidentally, I've always called them 'interior lights')

**Comment by misterprimus** [comment]
> Are 'dome lights' just included for free with the dashboard and / or vehicle controls?
> 
> (Incidentally, I've always called them 'interior lights')

Yes.

**Comment by actual-nh** [comment]
> (Incidentally, I've always called them 'interior lights')

To me, that would also include other lights such as from doors (or aisles, for that matter).

**Comment by l29ah** [comment]
Dupe of https://github.com/CleverRaven/Cataclysm-DDA/issues/37229

**Comment by Night-Pryanik** [comment]
Closing as it's working as intended: dashboard's dome lights is a secondary feature, it shouldn't provide very much light; dashboard's higher power consumption than that of aisle lights is justified.
