### ISSUE TITLE
Melee damage test re heavy flashlight keeps failing for unrelated PRs

### ISSUE THREAD

**Issue by actual-nh** [CleverRaven/Cataclysm-DDA#47687]
# Describe the bug

Likely due to miscommunication regarding #47638 and whether it was ready in terms of fixing that part, the heavy flashlight melee damage test keeps failing (see #47686, #47685, and #47683 for examples).

# Steps To Reproduce

Run the test.

# Expected behavior

Test does not fail for completely unrelated PRs.

# Versions and configuration

N/A

# Additional context

Ping: @wapcaplet, @kevingranade, @Lamandus.

**Comment by actual-nh** [comment]
I can attempt to do a patch once I am a bit more functional (just got home from work); anyone who wants to do it before then is welcome.

**Comment by wapcaplet** [comment]
I'll get this one. Thanks for raising it.

**Comment by wapcaplet** [comment]
lol nevermind

**Comment by Lamandus** [comment]
oh damn, I really missed that point. really sorry!
