### ISSUE TITLE
Unable to disassemble ammo (Generic Guns Mod)

### ISSUE THREAD

**Issue by Nerdy314159265** [CleverRaven/Cataclysm-DDA#47693]
# Describe the bug

I am unable to disassemble most ammo. I believe any ammo that is not craftable (at least by my char idk about other) is unable to be disassembled.

Examples:
rifle ammo, ball -> cannot be disassembled
rifle ammo, ball (reloaded) -> can be disassembled

buckshot grenade cartridge -> can be disassembled
HEDP/teargas grenade cartridge -> cannot be disassembled

# Steps To Reproduce

1. Give player ammo and kinetic bullet puller
2. Attempt to disassemble extra rifle ammo
3. Fails to disassemble rifle ammo

# Expected behavior

I'd expect that I could disassemble rifle and other ammo like the rest to gain extra materials for different ammo types.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-9545-g034ac15-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Generic Guns [generic_guns]

# Additional context

**Comment by Rokmonkey** [comment]
I noted the same.  I think it means there is no recipe for disassembling?
This could be my first contribution if someone might be able to point me to where the proper JSON is or should be.  I have looked through a dozen so far to find out where the disassemble recipe is on other ammunition is but could not find it to use as an example.

**Comment by Nerdy314159265** [comment]
> I think it means there is no recipe for disassembling?

I think so too. If I knew more about JSONs then I'd try my hand at adding them.

**Comment by Nerdy314159265** [comment]
@Rokmonkey I just found the JSONs are for disassembly. There is an uncraft folder in the JSON directory that contains disassembly information.

**Comment by Rokmonkey** [comment]
I have solved it.  I just need to figure out the process yet for a pull request.  The recipes just weren't there for it.
