### ISSUE TITLE
Ability to filter the Wear Item menu by layer

### ISSUE THREAD

**Issue by Djinn247** [CleverRaven/Cataclysm-DDA#47697]
# Is your feature request related to a problem? Please describe.
As a hoarder and relatively new player it is difficult to choose what to equip on each layer for maximum effect and no encumbrance penalties from having multiple items on the same part and layer.
The only current way is either examining every item and making a mental or external list, or equpping all items at the same time then removing layer-conflicting items.

# Describe the solution you'd like
Be able to filter the Wear Item menu for items in a specific layer through the [/] Filter similar to the View Nearby Items menu where it filters by search options.
e.g. writing "L:waist" in the Wear Item menu will only show items of the "waist" layer
The only problem i can see that i do not know how to fix is: how to relay that information to the player of this new feature if implemented. The View Near Items menu has a box where the instructions are written and the crafting menu has a pop-up UI element with the instructions in it.

# Describe alternatives you've considered
adding a new column of the layer.
I do not prefer this alternative because the wear menu is already stuffed with columns and numbers and it is not as useful visually and will only clutter smaller screens. Better to have it through the filter menu.

# Additional context
![image](https://user-images.githubusercontent.com/42262104/108809938-fd5c8d00-75ba-11eb-8375-850b4c2bb4e9.png)

As a hoarder, even having the list shortened using the "Sort Armor" menu and then "Equip armor from inventory at this position" does not help much when there is so much variaty of unique items.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
