### ISSUE TITLE
Cornmeal crafting recipes should probably require dehydrated corn kernels.

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#47705]
# Is your feature request related to a problem? Please describe.

There are three crafting recipes for cornmeal, all of them can use fresh corn as the material component. I think this would produce a disgusting looking mush not floury cornmeal.

# Describe the solution you'd like

Require the corn to be dehydrated before being ground into cornmeal. This would require a new, intermediate, item for dehydrated corn kernels.

# Describe alternatives you've considered

Although popcorn kernels are somewhat different to sweetcorn kernels it would be reasonable to lump them all together for CDDA as there is only one corn that can be grown in fields at present. So you could just change the crafting recipe for "popcorn kernels" to allow you to use "corn" as well as (or instead of) "raw popcorn kernels".

# Additional context

I guess you could also make the disgusting looking corn mush first then dehydrate it later?

**Comment by Fosheze** [comment]
This definitely makes sense from a logic standpoint and I agree that it should be done but gameplay wise it would be a pain to have to manually dry all of your corn in a dehydrator before loading it into the mill. You could probably dry it on a smoking rack too but that is still quite a bit of work compared to IRL.

A lot of times IRL corn is just dried by just leaving it on the stalk to dry on it's own. Doing that is a whole lot cheaper and easier than harvesting it wet then loading it into a drier. Corn can sit dried on the stalk for months just fine, even through winter. The only thing that really ruins it is excessive moisture or wind knocking it off the stalk. It only takes leaving it on the stalk for an extra 2-4 weeks for it to dry enough for processing depending on the exact type of corn. I'm not sure what the growing time of corn in game is but it is possible that the survivor should be getting dried corn off of the stalk already. If not it would be interesting if we could add a further growth stage after mature for corn which would be it turning into dried corn.

**Comment by PaulBlay** [comment]
I don't think you can handwave 'it's dry when you pick it off' as a solution unless you go to a lot of trouble re-working the whole vegetable/fruit/grain harvest system (which arguably would be nice, but is a very big job). 

Having harvested corn-on-the cob become dry corn-on-the-cob if it is left laying around for a couple of weeks or so outside in summer is probably doable. You could have 'vegetable drying rack' furniture that would work similarly to the smoking rack but doesn't require fuel. It would need some C++ editing to ensure that you either get 'dehydrated vegetables' or 'rotten vegetables' depending on temperature and if it's rained on or something. Salted and sun-dried meat is also a thing that could be looked into.
