### ISSUE TITLE
Permanent ignore list for advanced inventory

### ISSUE THREAD

**Issue by adamaxis** [CleverRaven/Cataclysm-DDA#47712]
# Is your feature request related to a problem? Please describe.
There is no way to permanent ignore items on the advanced inventory management system. You can do this with recipes and other systems, but not items.

# Describe the solution you'd like
A permanent ignore list with an interface similar or identical to the auto-pickup one. Ignored items either wouldn't show up on advanced inventory management in any capacity, or would show up as 'Ignored item'.

# Describe alternatives you've considered
Whatever solution would allow players to manage ignored items.

# Additional context
None

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
