### ISSUE TITLE
Driving a Vehicle Cause's Player Character to Get Exhausted Even with Gas/electric

### ISSUE THREAD

**Issue by likowski1** [CleverRaven/Cataclysm-DDA#47728]
#Bug Description
Something i Noticed was i was getting Exhausted from Driving Vehicle's Around. This is a Pretty bad one.

# Steps To Reproduce

1.Find/Make a Working Vehicle with Gas/Electric
2.Make sure you have No Exhaustion
3.Drive around for a bit.
4.Check Your Effect's you should have some form of Exhaustion

# Expected behavior

 I Expect that it has to do with it think that The Player is Walking when driving a vehicle.

# Versions and configuration

 - OS:Windows 10  
 - Game Version:0.E-8446-ga4d28d9
 - Graphics version: [Tiles]
 - Ingame language: English
 - Mods loaded:![image](https://user-images.githubusercontent.com/79609231/109074767-c91dc500-76bd-11eb-89f2-ee7c184c6613.png)

# Additional context

I feel i easy way to fix it is to disable Exhaustion then Driving. but i aint a programmer, maybe tie Exhaustion Instead to Stamina Instead of Movement

Edit:i am Using the Launcher

**Comment by ZhilkinSerg** [comment]
Savegame?

**Comment by wapcaplet** [comment]
I could not reproduce this issue in 0.E-8446-ga4d28d9, nor in 0.E-9845-g99a90ed8. I tested using a Hybrid Car at speeds up to 30 mph, but saw no effect on stamina regardless of whether I had the gasoline engine, electric motor, or both enabled.

**Comment by Nerdy314159265** [comment]
I may have seen this in 0.E-9545-g034ac15-dirty
I believe it was intermittent and I assumed it was caused by something else going on while I was driving.

I agree that OP should post a savegame showing the issue.

**Comment by likowski1** [comment]
how do i add one? it isnt letting me put the folder in for it. i only have 1 save

**Comment by likowski1** [comment]
i dont know how to Transfer Save's.

**Comment by likowski1** [comment]
After Testing it on my Own time i have Discovered i may be slightly retarded. Sorry for wasteing yall's time.
