### ISSUE TITLE
Jump or Dive movement option

### ISSUE THREAD

**Issue by Nerdy314159265** [CleverRaven/Cataclysm-DDA#47724]
# Is your feature request related to a problem? Please describe.
In some situations it would be useful to be able to jump or dive across several tiles quickly to get out of the way of something, such as when setting off an explosive nearby.

# Describe the solution you'd like
An option added to movement to allow your character to jump or dive several tiles (depending on stats?) at the cost of stamina,
and probably putting your character into a knocked down state.

# Describe alternatives you've considered
I don't know of an alternative that could duplicate this feature

# Additional context
My specific situation was that I was disarming landmines. When you do, you get a warning that you set it off and you can move one space before the explosion. I was thinking it would be a good idea to allow you to dive out of the way so that there is a chance in a situation like that to get out of range of the explosion.

I think this feature would also be useful for people doing rooftop exploration because they might be able to use this to cross gaps in a hurry with the risk that they'll fall.

This could have interesting interactions with stats, mutations and bionics to vary the length, stamina requirements, and how well the jump is landed. For example, someone could have a mutation that gives them jumping spider legs or some other crazy mutation that would allow them to jump large distances to get within melee range quickly for an attack. It could even go full crazy and allow for the addition of items and mutations that convert default movement to jumping i.e. Kangaroo legs or Pogo stick.

**Comment by SariusSkelrets** [comment]
I think the dive option could work as a move-fast-one-tile-away thing that downs you as a result and can't be used while downed

The jump, however, is more complicated. How far the jump? How would run-up would work? 

According to wikipedia, the world record is nearly 9 meters with run-up but that's a world record and they weren't wearing armor and backpack or killig zombies all day long before the jump

But the capacity to skip one or two tiles would add a new and interesting dimension to roof travel

**Comment by Nerdy314159265** [comment]
Jump distance could be based on real world data to some degree. For example, you could start with the world record of 9m match that with a character that has stats comparable to what you would attribute to the record holder, then give them a 9m jump at peak 0 encumbrance, extremely low carry weight, completely fresh and full stamina.

Then other real world values can form other data points to use for realistic results. Maybe next value could be World Record standing long jump as a version where they didn't move the previous round and have no momentum. Then it could be interpolated between those values based on their previous move speed and direction.

Other values that could help might be military training standards that might have information on jumping performance that could be used for pack load.

Those would probably be the more realistic approaches. It might be possible to create a BaseJump stat that is reasonable and do something like 
<a href="https://www.codecogs.com/eqnedit.php?latex=MaxJump=BaseJump&space;*&space;(\frac{BaseSpeed}{PreviousMoveCost})^{cos(\theta&space;)}&space;*&space;\frac{MaxWeight-CarryWeight}{MaxWeight}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?MaxJump=BaseJump&space;*&space;(\frac{BaseSpeed}{PreviousMoveCost})^{cos(\theta&space;)}&space;*&space;\frac{MaxWeight-CarryWeight}{MaxWeight}" title="MaxJump=BaseJump * (\frac{BaseSpeed}{PreviousMoveCost})^{cos(\theta )} * \frac{MaxWeight-CarryWeight}{MaxWeight}" /></a>
Where θ is the angle between the last move and the current jump direction, set it to 90 degrees or pi/2 when they didn't move the previous turn. (Would probably have to use some shortcut to make this more efficient to calculate and easier to select location to jump to)

Forgive me if any of my terminology is wrong or the formula is a bit weird, I'm not 100% familiar with the way Speed and Move Cost is calculated. I'm also unsure how to incorporate encumbrance more than the effect it'd have on MoveCost.

**Comment by chrispikula** [comment]
You can already jump between nearby roofs so maybe an extension of that?

This was sort of brought up in #42401
It was suggested to continue the discussion in #28564 but that bit is borderline stale, again.

**Comment by Nerdy314159265** [comment]
If jumping between roofs works like I think it does (a contextual interact option with the edge of the roof) then I think it would be better to wrap that into this then try and extend that system out.

**Comment by anothersimulacrum** [comment]
Why are you looking at world record jumps? There is plenty of data for less exceptional jumps, start there.

**Comment by Salty-Panda** [comment]
Dive to the side is a maneuver that could be used in "self-defense with a pistol against melee attacker".
Throw yourself to the ground to get a bit distance, draw a gun, and shoot. Could save some moves, but it's risky.

**Comment by actual-nh** [comment]
> Why are you looking at world record jumps? There is plenty of data for less exceptional jumps, start there.

True - how much is there for the average 25-year-old (as opposed to athletes), though? The two most-usable data-points regarding stats that we have are 8 (average) and 14 (world-class athlete); world-record should be just barely within the possibilities for the second. I suppose studies on before-and-after training programs would be a possibility (the "before").

**Comment by actual-nh** [comment]
> [![](https://camo.githubusercontent.com/9de1434d4168b7df7e54b5f33749879ad10412a6ce06ea753dbd78f0a369eab8/68747470733a2f2f6c617465782e636f6465636f67732e636f6d2f6769662e6c617465783f4d61784a756d703d426173654a756d702673706163653b2a2673706163653b285c667261637b4261736553706565647d7b50726576696f75734d6f7665436f73747d295e7b636f73285c74686574612673706163653b297d2673706163653b2a2673706163653b5c667261637b4d61785765696768742d43617272795765696768747d7b4d61785765696768747d)](https://www.codecogs.com/eqnedit.php?latex=MaxJump=BaseJump&space;*&space;(\frac{BaseSpeed}{PreviousMoveCost})^{cos(\theta&space;)}&space;*&space;\frac{MaxWeight-CarryWeight}{MaxWeight})

BTW, this is unreadable on dark mode (my eyes are intermittently overly sensitive to too-bright screens); try turning the background to white instead of transparent.

**Comment by Nerdy314159265** [comment]
@actual-nh 
<a href="https://www.codecogs.com/eqnedit.php?latex=\bg_black&space;MaxJump=BaseJump&space;*&space;(\frac{BaseSpeed}{PreviousMoveCost})^{cos(\theta&space;)}&space;*&space;\frac{MaxWeight-CarryWeight}{MaxWeight}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\bg_black&space;MaxJump=BaseJump&space;*&space;(\frac{BaseSpeed}{PreviousMoveCost})^{cos(\theta&space;)}&space;*&space;\frac{MaxWeight-CarryWeight}{MaxWeight}" title="MaxJump=BaseJump * (\frac{BaseSpeed}{PreviousMoveCost})^{cos(\theta )} * \frac{MaxWeight-CarryWeight}{MaxWeight}" /></a>
This better?

**Comment by actual-nh** [comment]
Hrm. Unfortunately, that is getting a broken image link.

**Comment by Nerdy314159265** [comment]
@actual-nh Last attempt; I don't want to keep bumping this just to fix an image of a half baked formula (that I already realized needs a fix)
<a href="https://www.codecogs.com/eqnedit.php?latex=\bg_white&space;MaxJump=BaseJump&space;*&space;(\frac{BaseSpeed}{PreviousMoveCost})^{cos(\theta&space;)}&space;*&space;\frac{MaxWeight-CarryWeight}{MaxWeight}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\bg_white&space;MaxJump=BaseJump&space;*&space;(\frac{BaseSpeed}{PreviousMoveCost})^{cos(\theta&space;)}&space;*&space;\frac{MaxWeight-CarryWeight}{MaxWeight}" title="MaxJump=BaseJump * (\frac{BaseSpeed}{PreviousMoveCost})^{cos(\theta )} * \frac{MaxWeight-CarryWeight}{MaxWeight}" /></a>

**Comment by Malorn-Deslor** [comment]
We have a athletics skill now, sounds like the sort of thing that should be tied to athletics skills.

**Comment by actual-nh** [comment]
> We have a athletics skill now, sounds like the sort of thing that should be tied to athletics skills.

That would expand it beyond swimming, IIRC, which would be nice.

**Comment by Night-Pryanik** [comment]
No discussion in half a year, closing.

**Comment by Nerdy314159265** [comment]
> No discussion in half a year, closing.

I'm not sure what discussion is supposed to happen while waiting for contributors to the project to weigh in with opinions.

I still feel that the ability to jump, dive, or leap is important. There are many enemies with leaping abilities it seems to make sense for the player to have some as well.

**Comment by Night-Pryanik** [comment]
Closing the issue doesn't necessarily mean that it's unimportant or we don't want the feature mentioned in it. If someone wants to implement the feature, they are welcome, they doesn't need an open issue for this.

We have almost two thousands open issues, among them are tons of suggestion-type. Such issues without discussion for a long time only make it harder to navigate and should be closed.

**Comment by Nerdy314159265** [comment]
Apologies. You guys obviously have a system different than other devs that I've seen.
A lot will frequently consider closed issues to be thrown away or done.
