### ISSUE TITLE
Look at Sky/Map merge

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#47738]
# Is your feature request related to a problem? Please describe.
It's nice to be able to look at the sky!  I bound it to 'ctrl-w' (weather) just so I could, and I noticed that it used the world map.  Neato!  I could lower levels and see building, etc.

However, when I used the map key, 'm', and decided to look up, I didn't see the weather at lvl 10.  (I was on the ground.)

# Describe the solution you'd like
An option to make the 'sky' a hotkey in the overmap display would be really cool.  It could auto-jump your sight 10 levels, or the max, and would the toggle clouds on.

# Describe alternatives you've considered
N/A

# Additional context
Couldn't find much.

**Comment by LeahLuong** [comment]
Acting funny but I don't know why.

'Scuse me while I kiss this guy.

**Comment by Night-Pryanik** [comment]
This is already implemented as of February 12, 2022. Open `m`ap, then press `w` to toggle weather (visible on level 10).
