### ISSUE TITLE
Hostile Forgeborn

### ISSUE THREAD

**Issue by souricelle** [CleverRaven/Cataclysm-DDA#47735]
# Describe the bug

I was playing Magiclysm and approached a Forge of Wonders. A Forge Born immediately went hostile on me despite the fact that I hadn't attacked anything in the area. It approached me and attacked my accompanying NPC (the one that is at the Wizard's Vacation start by default)

# Steps To Reproduce

1. Make a Magiclysm character
2. Visit a Forge of Wonders
3. Get wrecked by super powerful magic enemies that apparently aren't meant to be hostile.

# Expected behavior

I am told these enemies are supposed to be neutral.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-9804-gbc7931f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Stats Through Kills [stats_through_kills],
    No Fungal Monsters [No_Fungi]
]

# Additional context

I was also attacked by the cyber mastiffs at the PrepNet Orchard in Aftershock, this may not be a mod issue.

**Comment by Maleclypse** [comment]
Once monsters go hostile they tend to stay that way for inordinate amounts of time only rarely if ever going back to neutral.  Monster hostility can also persist through save scumming.   So if either of those creatures were attacked by a zombie it can result in this scenario.  If you start a new world and teleport to either of those locations you will likely find that they don't attack you on sight.

**Comment by actual-nh** [comment]
That they stay hostile that long, and indiscriminately (e.g., attack by a zombie = hostile to everything), is something that does need fixing in the current system - while some parts of (short-term) anger should be shared across (potential) opponents, not all of it should be, particularly long-term.
