### ISSUE TITLE
Item charges can get refilled between sessions

### ISSUE THREAD

**Issue by Trioct** [CleverRaven/Cataclysm-DDA#47739]
# Describe the bug

Some items in the player inventory with charges get refilled the first time they're saved and loaded.

# Steps To Reproduce

0. Start a world with 10x spawn rates or something
1. Go into a kitchen and grab some partially filled matchbooks and lighters
2. Save and load
3. Have full matchbooks and lighters
4. (Optional) Spend a charge on one of the items
5. (Optional) Save and load, charge doesn't get refilled this time

Charges not in your inventory aren't affected between save and loads I don't think

# Expected behavior

Charges remain untouched between sessions

# Screenshots

Initial collection of items:
![1](https://user-images.githubusercontent.com/4079502/109217560-9e924180-777b-11eb-8195-3c9433018037.png)
Save and load:
![2](https://user-images.githubusercontent.com/4079502/109217564-9e924180-777b-11eb-93c1-c03422085cdd.png)
Burn something then save and load after the first save and load:
![3](https://user-images.githubusercontent.com/4079502/109217557-9df9ab00-777b-11eb-9c20-b0900f040bbe.png)

# Versions and configuration

- OS: Linux
    - OS Version: Gentoo 5.11.0-zen2
- Game Version: 0.E-9855-gfa9b27e30e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional Context

I suspect #47613 only partially fixed the behavior in #47578
Also sorry those images are gargantuan

**Comment by wapcaplet** [comment]
Confirmed in 0.E-9855-gfa9b27e30e. Candle, matchbook, permanent marker, and small fire extinguisher were refilled on save/load, but batteries were not:

![image](https://user-images.githubusercontent.com/238395/109247500-466e3600-77a1-11eb-8f18-3f641545ffc2.png)

**Comment by wapcaplet** [comment]
This also affects items stored in vehicle cargo, per #48064.
