### ISSUE TITLE
Getting extend and delete to work with pocket_data

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#47749]
# Is your feature request related to a problem? Please describe.
I'm trying to make a way to make a generic lid for certain pockets, without having to worry about if those parent items will change volume in the future.

IIRC, holster size may have shrunk some time in the past?  This made a few mods need [TARDIS] tags.

Effectively, I'd like to add:

`
"delete": { "pocket_data": [ { "open_container": true } ] },
"extend": {
	"pocket_data": [
		{
			"open_container": false,
			"sealed_data": { "spoil_multiplier": 0.5 }
		}
	]
`
to bowl_pewter, glass_bowl, and ceramic_bowl.  bowl_plastic doesn't need it.
(Side note, _that naming schema_.)

I can't see it really being a bad thing to have the ability to do such from a modders perspective, as it'd help reduce the need to check to see if the parent item's pocket has changed.

If one could get this to work, you'd have the nice side effect of allowing a copy-from gun to have more bullet capacity that would require less programing maintenance going forward.  If the original gun changes, the copy changes in turn!  :-)

However, there are two major problems with this idea.
The first is that I don't know how you'd choose a specific pocket when an item has multiple pockets.
The second is that when I looked at extend_qualities_from_json, which is what performs the "extend" bit, it looked like it only dealt with one dimensional data, not two dimensional data like the pocket stuff.

# Describe the solution you'd like
For it to work as I'd like, one could call a pocket (maybe by number starting from 1 or 0?), and then change the relative values.  Then use something similar to the above code.

# Describe alternatives you've considered
Well, I'm not sure what is an option, given the implicit requirement to not explode the scope.

# Additional context
Of interesting note, there is no warning or error messages that pop up from non-functional use of delete/extend/proportional or relative.  Hell, I tried using proportional and relative on "open_container": false, trying -1, 0, true, -false, etc.  Variable type miss-matches were ignored.
The below _should_ throw some sort of error.  To be fair, it has probably zero in-game consequences.
`[{
    "copy-from": "bowl_pewter",
    "id": "bowl_pewter_extension_rod",
    "type": "GENERIC",
    "category": "container",
    "name": { "str": "blah", "str_pl": "bleh" },
    "description": "blurgh",
    "symbol": "⨆",
    "color": "blue",
    "extend": { "pocket_data: 0": [ { "open_container": false, "sealed_data": { "spoil_multiplier": 2 } } ] },
    "delete": { "pocket_data": [ { "open_container": true } ] },
    "relative": {
      "pocket_data: 0": [ { "max_contains_volume": 355, "sealed_data": { "spoil_multiplier": -0.1 }, "open_container": -1.0 } ],
      "pocket_type: 0": [ { "max_contains_volume": 177, "sealed_data": { "spoil_multiplier": -0.5 }, "open_container": true } ],
      "pocket_data": [ { "max_contains_volume": 234} ]
    },
    "proportional": {
      "weight": "150 g",
      "pocket_type: 0": [ { "max_contains_volume": 351, "sealed_data": { "spoil_multiplier": -0.3 }, "open_container": -1.0 } ],
      "open_pocket_data_0": [ { "max_contains_volume": 253, "sealed_data": { "spoil_multiplier": -0.4 }, "open_container": true } ]
    }
}]`

**Comment by ZhilkinSerg** [comment]
`pocket_data` is a complex object - it should not have support for `extend`, `delete`, `relative` or `proportional`.

**Comment by chrispikula** [comment]
Then something else, maybe?

Thinking about it with a morning head, a pocket_override function call maybe?  Normal operation would be to change every pocket that an item contains.

The pocket data in json files is copy-pasted time and time again everywhere it's used, with only slight changes.  There is no connectivity between those pockets.  This seems smelly.  Understandable, but still.

If, say, far off in the future, there was the decision to change the state of how pockets are done, it would be horrible for the modding community as those copies would need to be updated, which leads to a significant amount of abandoned work to never be used again.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
