### ISSUE TITLE
No prompt for walking in dangerous tile when pushing a furniture/vehicle

### ISSUE THREAD

**Issue by zeropol** [CleverRaven/Cataclysm-DDA#47746]
# Describe the bug

There is no prompt for walking in dangerous tile when pushing a furniture/vehicle.
It only happen when we drag a furniture/vehicle in front of us, not behind us.

Examples I saw : walking into a ledge with a furniture, walking on the secretion of pupating zombie with a shopping cart.

# Steps To Reproduce
1. Grab a furniture.
2. Push the furniture past a ledge ( the grab/drag don't break ).
3. Try to push it once more in the same direction.
4. Fall the ledge without the message "Really step into ledge?"

# Expected behavior
Having the prompt for walking in a dangerous tile even when dragging a furniture.

# Screenshots
![Animated gif](https://cdn.discordapp.com/attachments/613424936928804895/814730228546797588/cdda_drag_and_messages.gif)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-9815-ge819fbb [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Useful Helicopters [useful_helicopters]
]

# Additional context
- It is a minor problem yet can lead to death.
- As we see in the GIF, I was able to move the furniture when it was 1 z-lvl below, hence my test to push it further away.

**Comment by wapcaplet** [comment]
Confirmed in 0.E-9857-gf777f179d0c; pushing a shopping cart off a roof, I can walk off and hurt myself with no prompt:

![image](https://user-images.githubusercontent.com/238395/109371549-b4c6fd00-7862-11eb-8724-f1176f6f0450.png)
