### ISSUE TITLE
Currency Stacks/Denominations

### ISSUE THREAD

**Issue by Grubleafeater** [CleverRaven/Cataclysm-DDA#47740]
# Is your feature request related to a problem? Please describe.
There's some wonkiness around merchant inventories, particularly with currencies(Merch, FlatCoin, Hub Coins). After asking around, people said it wasn't likely to be fixed soon.

# Describe the solution you'd like
So my proposed solution--Reduce the amount of currency items in merchant inventories without reducing the actual amount of currency in their inventory. To that end, I propose a simple solution. Adding items that get unpacked into multiple currency items, along with a way to craft them.

Specifically, I propose that merchants be given items that are 10 times as costly as the normal currencies they carry and which can be crafted from/uncraft to 10 of their respective currency. Then, the normal currency be pared to no more than 10 currency, plus one of these cash-stacks for every 10 this would knock off.

For Merch, I recommend that this be called 'Clipped Merch'--a money clip with 10 merch in it. For FlatCoin and HubCoin, i suggest that they be either 'handfuls' or 'pouches'.

# Additional context

![](https://cdn.discordapp.com/attachments/598523535169945607/814622203345240074/unknown.png)

**Comment by Cenness** [comment]
What we really need is a working stacking in the barter UI. If I'm not mistaken ammo already shows as stacks and not as individual cartridges, so a stopgap solution would be to convert all currency to ammo.

Honestly, I can't imagine gameplay reasons why it is not showing item list in the same way as in our inventory.
I mean, there is no need to choose fourth, sixth and seventh instances of a frag grenades if you want to purchase 3 of them. And there is already code for condition aware stacking in the game.

**Comment by Grubleafeater** [comment]
> What we really need is a working stacking in the barter UI. If I'm not mistaken only ammo shows as stacks and not as individual cartridges, so a stopgap solution would be to convert all currency to ammo.
> 
> Honestly, I can't imagine gameplay reasons why it is not showing item list in the same way as in our inventory.
> I mean, there is no need to choose fourth, sixth and seventh instances of frag grenades if you want to purchase 3 of them. And there is already code for condition aware stacking in the game.
> 
> Edit: different denominations are cool, but it is a partial solution to a much broader problem. And it brings other questions - for example, should merchants provide separate money change services, or would it happen automatically? Should player deal with situation when he only has high value items and wants to buy one bottle of water by buying other things just so he doesn't throw out hundreds of dollars-equivalents?

This is why I suggested stacks over denominations as the stopgap.

Ammo currency would also possibly work.

**Comment by anothersimulacrum** [comment]
Ammo currency should not be considered, it's a hack, not a solution.

**Comment by Cenness** [comment]
> 
> 
> Ammo currency should not be considered, it's a hack, not a solution.

Yeah, I would too prefer to have "$n of something", where something could be anything. But that hack is shockingly effective - whoosh and suddenly you have not multiple screens worth of items, but _one line_.

Slight derail: I think current ammo handling hides performance problems with item pickup/drop - it's quite faster with ammo. I don't know why, but the method of ammo handling is that much more effective than method used for other things. Maybe because game pick ups in batches of one or two, maybe there other reasons .

**Comment by anothersimulacrum** [comment]
What I think happens there is that ammo is one item that has multiple charges, whereas other items are individual single items. So when you drop it, you only need to pay the obtain cost for it once, whereas with other items you need to pay the obtain cost for each item to drop it.

**Comment by actual-nh** [comment]
> Slight derail: I think current ammo handling hides performance problems with item pickup/drop - it's quite faster with ammo. I don't know why, but the method of ammo handling is that much more efficient than method used for other things. Maybe because game pick ups nonammo things in batches of one or two, maybe there other reasons.

Faster in-game, or faster real-time?

**Comment by Cenness** [comment]
Real time. Compare picking up hundreds of plastic forks in mil. base kitchen to picking up thousands 5.56 from a turret.

**Comment by kevingranade** [comment]
Currency stacks now without being count-by-charge.
![Screenshot from 2022-01-01 15-42-18](https://user-images.githubusercontent.com/860276/147862437-60548edd-ae5d-4127-97d9-997e80990b1b.png)
