### ISSUE TITLE
Multi-butcher products disappear during tidy up action if already in destination zone

### ISSUE THREAD

**Issue by jagoly** [CleverRaven/Cataclysm-DDA#47747]
# Describe the bug

When the player or an NPC finishes the multi butcher activity, they switch to the tidy up activity. If the tile where they were working is an unsorted zone (meaning products shouldn't need to be moved), then all butchery products disappear into the void.

# Steps To Reproduce

- load attached save
- npc is already assigned to activity
- wait a few hours
- at end of activity, be sad and hungry

# Expected behavior

End up with lots of pig meat. Why is the "tidy up" even needed?

# Versions and configuration

git master
save: [butcher-fail.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6048609/butcher-fail.zip)

# Additional context

Does not occur if you disable or move the unsorted loot zone. 

Most likely related to https://github.com/CleverRaven/Cataclysm-DDA/issues/39858

**Comment by wapcaplet** [comment]
Possible duplicate of #47737

**Comment by LetterShapedGlyphs** [comment]
Reasonably certain this was fixed by #56276 stopping the tidy action from firing, as it was triggering some double moves and then only removing once. (and if the location it was moved to happened to be the same as the removal location deleting the item)
