### ISSUE TITLE
Magiclysm Goblin Slinger rocks phase through vehicles

### ISSUE THREAD

**Issue by Relyksboa** [CleverRaven/Cataclysm-DDA#47753]
# Describe the bug
Goblin Slingers sling attack phases through vehicles, when they should collide.

# Steps To Reproduce

1. get in a vehicle
2. spawn a goblin slinger
3. get hit by extra dimensional rocks that phase through your car

# Expected behavior

the rock should hit the car and bounce off. 

# Screenshots

# Versions and configuration
Version:

# Additional context

**Comment by actual-nh** [comment]
Related to not having `"ammo_effects": [ "NO_PENETRATE_OBSTACLES" ]`?

**Comment by Relyksboa** [comment]
This also happens with the caustic soldier zombie.
