### ISSUE TITLE
Can't cast any Component Spell, 'not enough energy', despite full mana bar

### ISSUE THREAD

**Issue by Ungen11** [CleverRaven/Cataclysm-DDA#47755]
# Describe the bug

My save cannot cast any component spells, at all. My character learned Shardspray, an Earthshaper component spell, and is currently on a Military Helipad. He had scrap metal he got from smashing a nearby car, which is the component. He tried to cast Shardspray to attack a turret from around a corner without exposing himself, only to discover that he 'doesn't have enough energy', despite his mana being currently at 1153. Shardspray only uses 100 mana to cast, so in theory he could cast Shardspray 11 times (given enough components, obv), so why can't he? Debugging in other component spells reveals that in my save, all component spells share this same issue - even if you have every single component, you just don't 'have enough energy'.

# Steps To Reproduce

1. Run the save provided at the bottom of the issue, likely on the same version and build
2. Smash nearby vehicles and lockers to obtain scrap metal for the spell
3. Open the spellcasting menu
4. Attempt to cast Shardspray (or debug in another component spell and try to cast it after obtaining the oponents)
5. Discover that you 'don't have enough energy'

# Expected behavior

Any component spell should work properly since well, they're spells, they're supposed to be useful, that's why you invested monster evolution time in learning them. Emphasis on Shardspray, since I knew I was going to face turrets and needed an AOE in order to hit them safely, that's why I learned it. Now I have no way to hit them, forcing me to trust on not accidentally walking into their range.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1607
- Game Version: 0.E-9855-gfa9b27e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

# Additional context

I've provided the problem save, compressed into a .zip, for testing purposes.

[shardsprayandpray.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6052478/shardsprayandpray.zip)

Try not to die. /s

**Comment by casswedson** [comment]
I am able to cast shardspray when the component items are in my inventory.

![spray this](https://user-images.githubusercontent.com/58050969/109360239-d7eab000-7854-11eb-94ec-8259b92178d8.png)
When the items are around me I get this.

![image](https://user-images.githubusercontent.com/58050969/109360339-08324e80-7855-11eb-8834-973ecfeda2ff.png)

We have a UI issue here, that's probably as much as I can help here.

**Comment by wapcaplet** [comment]
Confirmed in 0.E-9855-gfa9b27e30e. Mana-powered spells including Caustic Aura, Flamebreath, Feral Form, Freezing Touch, Nova Flare, and Shardspray, as well as health-powered spells like Decaying Boneclub indicate "Not Enough Energy" when components are missing.

**Comment by wapcaplet** [comment]
I will have a fix incoming for this shortly.
