### ISSUE TITLE
Feature Request: XS clothing

### ISSUE THREAD

**Issue by skylord-a52** [CleverRaven/Cataclysm-DDA#47762]
# Is your feature request related to a problem? Please describe.
Currently playing on a character with the Tiny mutation. A lot of pre-generated clothing doesn't fit, which is fine. **However, a good deal of the clothing that my character herself can make would not fit.** If she made herself her own mittens, for example, they would be too big no matter what. This doesn't make sense! If I was making my own clothes, I would make them fit me, rather than some mythical average human, and it's frustrating having a significant amount of clothing and armor locked from my access.

# Describe the solution you'd like
**Recipes for XS items for every item that has an XL version -- ideally for every recipe that doesn't fit abnormally small mutated anatomy and that cannot be downsized.** These would mostly be copies of the original item, but weigh slightly less, require slightly less materials, and have slightly lower volume. Even just direct copies with no changes other than fit would be a great first step, and I'm considering making a PR with those available.

# Describe alternatives you've considered
**Making items made by the player automatically fit their anatomy, just like items made by the player are automatically a good fit.** This has the advantage of not cluttering up the crafting menu with duplicate recipes, but it doesn't allow for changes in weight, volume, cost, etc., and it would also likely require changes to the actual code instead of just the json.

**Going through and reinvestigating which items can or can't fit mutated anatomy, and which items can or can't be refitted.** For example, while I can _maybe_ accept that a bandana could possibly be too large if you had like... a _really_ small face, it seems really strange to me that you can't downsize/refit it -- just fold the edges over and sew them up, or even trim the bandana with a pair of scissors. I'm sure this isn't the only item like this. In general it seems to be that the decision whether an item could be upsized/downsized/refitted was made more with abnormally large anatomy in mind, rather than abnormally small.

**Comment by Maleclypse** [comment]
Don’t make a fork. Make a PR. Do what I did to expand XL clothing. You could probably straight copy my PR and then edit in XS recipes and items right after the XL. Or are you saying that there is no code support for XS items? In which case still make a PR. I’ll happily review it.

**Comment by skylord-a52** [comment]
> 
> 
> Don’t make a fork. Make a PR. Do what I did to expand XL clothing. You could probably straight copy my PR and then edit in XS recipes and items right after the XL. Or are you saying that there is no code support for XS items? In which case still make a PR. I’ll happily review it.

Pull request, yes, sorry. Or a fork, then a PR. I don't use Github much. 😄

**Comment by UmbralReaper** [comment]
@Maleclypse I don't believe there is support for XS items. A quick search for XS reveals only the weight mutation. And if there was support how would they be specified? A tag like `OVERSIZE`?

**Comment by Termineitor244** [comment]
From #24672
> New mechanic: Undersizing

> Being a mouse is tuff stuff, and your clothes are too big to fit you comfortably, resulting in doubled encumbrance if you have the Tiny or Unassuming mutations. However, there's a solution: undersize them! You can refit clothes that already fit you to undersize them if you're very small, which makes them fit you normally again and gives them an (undersize) tag in their name.

I have never actually played with the mouse mutation, but this should already be in the game, now, regarding direct crafting of said clothing (without needing to refit them) maybe only with clothing impossible to refit?
