### ISSUE TITLE
Modifying a shoulder strap with a tailoring kit causes a seg fault

### ISSUE THREAD

**Issue by kholat** [CleverRaven/Cataclysm-DDA#47760]
Modifying a shoulder strap with a tailoring kit causes a seg fault.

# Steps To Reproduce

1. Spawn a Shoulder strap and a tailors kit and make sure the kit has some thread
2. activate the kit and press Modify
3. select the shoulder strap
4. boom

# Expected behavior

Triggers the "this item cant be modified" exception or something instead of crashing the game.

# Screenshots

trivial

# Versions and configuration

 - OS: win10 64bit
 - Game Version: 0.E-9845-g99a90ed
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: happens in vanilla too

# Additional context

N/A

**Comment by wapcaplet** [comment]
Confirmed in 0.E-9855-gfa9b27e30e

![image](https://user-images.githubusercontent.com/238395/109367454-5e05f700-7853-11eb-82eb-45cb93364a4d.png)

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6053279/crash.log)
