### ISSUE TITLE
Rocks don't always group

### ISSUE THREAD

**Issue by nornagon** [CleverRaven/Cataclysm-DDA#47769]
# Describe the bug

Sometimes rocks don't group together in the inventory.

# Steps To Reproduce

Pick up a bunch of rocks off the ground.

# Expected behavior

Since all the rocks are identical (right?), they should group together and say "rock (n)".

# Screenshots

![four lines saying rock (1) followed by one line saying rock (4)](https://user-images.githubusercontent.com/172800/109375642-25761580-7873-11eb-9f1a-6f22cc0d47e1.png)

# Versions and configuration

Game Version: 0.E-9399-gb4ab3df

**Comment by anothersimulacrum** [comment]
Can you turn on debug mode (separate keybind from the debug menu), and show the iteminfo of each rock?

**Comment by nornagon** [comment]
Hm, unfortunately when I dropped the rocks they grouped correctly again.

Perhaps the rocks were in separate containers... closing this until I can repro again.
