### ISSUE TITLE
Mutant animals drop normal organs

### ISSUE THREAD

**Issue by souricelle** [CleverRaven/Cataclysm-DDA#47773]
Mutant animals and humanoids such as the cerbearus, the dambreaker, experimental mutant etc are butchered for mutant meat and fat but drop normal, non-toxic organs. Mutant arthropods like the razorclaws and whale wasps drop mutated organs as expected.

# Steps To Reproduce

1) Spawn a mutant monster or humanoid and kill them
2) Full butcher it
3) Note the normal organs

# Expected behavior

These creatures are probably intended to drop mutated organs.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-9855-gfa9b27e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

This also affects creatures in Magiclysm like the owlbear.

**Comment by Baby-Che-Cell** [comment]
Razor claws, and wasps don't have mutated organs in their harvest table, you may be in the stable version still.

**Comment by leemuar** [comment]
Where can I find the harvest table (what they give on harvesting)?

**Comment by anothersimulacrum** [comment]
`data/json/harvest.json` @leemuar

**Comment by leemuar** [comment]
@souricelle I need some more info from you: what monster should have mutant organs?

As far as I can see there is no mutant kidney, mutant brain, mutant liver and etc currently in the game. Razorclaws don't have any organs currently and wasps have "mutant bug organs" that are specific to insects

To fix the issue we probably should add new mutant organs and then change the harvest table accordingly

**Comment by anothersimulacrum** [comment]
I'd say that any of the harvest entries giving mutant meat should also give mutant organs.
So probably `mutant_*` and `bird_large`. `arachnid*` also, but that appears to already have mutant bug organs.

**Comment by NetSysFire** [comment]
![image](https://user-images.githubusercontent.com/59517351/150688223-3b6f1f2e-b382-40ae-8fd2-35a652716e14.png)

Example of butchering a Cerbearus. The dambreaker also drops the correct things, but the experimental mutant does only drop a human stomach and no organs, which might be intended.
This issue might be ready for closing.
