### ISSUE TITLE
Activating partially-full endless flask causes an error and creates a None object

### ISSUE THREAD

**Issue by RadHazard** [CleverRaven/Cataclysm-DDA#47770]
# Describe the bug
If you activate an Endless Flask that isn't empty, the game tries to fill it with whisky but fails with a "pocket can't fit item" error.  A ghostly None item is added to the flask that can't be dropped or removed from your inventory

# Steps To Reproduce
1. Spawn an endless flask
2. Fill the flask with something (or activate it)
3. Wait for the flask to charge, then try to activate it while it's already full
4. See error and an "endless flask > 2 items" in your inventory
5. Try to empty the flask, notice it still has a None inside it

# Expected behavior
The endless flask either can't be activated while partially full or only tries to refill itself with as much whisky as will fit

# Versions and configuration
- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.2 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-9855-gfa9b27e30e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by RenechCDDA** [comment]
Resolved by #66571
