### ISSUE TITLE
Game crashing constantly after closing it without a notice.

### ISSUE THREAD

**Issue by Dencakun** [CleverRaven/Cataclysm-DDA#47799]
# Describe the bug

After suddenly closing the game my savefile is now constantly crashing via segmentation default, apparently it's looking for an item that is missing.

# Steps To Reproduce

Load  the savefile.

# Expected behavior

Gameplay without a crash.

# Screenshots

![imagen](https://user-images.githubusercontent.com/37341068/109426313-67ae6c80-79c3-11eb-98dd-e6a5f9198112.png)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-9857-gf77f179 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Mythical Martial Arts [MMA]

# Additional context

I added the save file and the logs.

https://mega.nz/file/lWgwjJRL#v7aaqyim6lTXQGcD9MvSM1gIYAVtTZEImbj8XNCSEPw

**Comment by actual-nh** [comment]
What happens if you press the space bar?

**Comment by wapcaplet** [comment]
Was this save game created through normal use of the "Save and exit" command, or did you kill the game with Alt+F4 or something like that?

**Comment by Dencakun** [comment]
> 
> 
> What happens if you press the space bar?

It continues to the game, it shows the segmentation default error and it crashes the game, doesn't let do any input whatsoever.



> 
> 
> Was this save game created through normal use of auto-save, or the "Save and exit" command, or did you kill the game with Alt+F4 or something like that?

I killled with the game with Alt+F4 after selecting the "let's abandon this camp" option by mistake.
