### ISSUE TITLE
Zero-weight and volume items appear, crash on interacting with them

### ISSUE THREAD

**Issue by apollovy** [CleverRaven/Cataclysm-DDA#47795]
# Describe the bug
Zero-weight and volume items appear, crash on interacting with them

# Steps To Reproduce
0. Load save "Тристан Элизондо"
1. "\\"-haul the corpse under the feet
2. "y"-move 1 tile NW
3. "n"-move 1 tile SE
4. "/"-open adv. inv. mgmt
5. Observe some items of 0.00 weight and volume
6. Try to "Enter" one of them to put in your inventory
7. Crash

# Expected behavior
1. No zero-weight/volume items
2. No crash

# Screenshots
![zero-weight-and-volume-items](https://user-images.githubusercontent.com/1671727/109421761-bb33b100-79e9-11eb-9d14-113372582520.png)

# Versions and configuration
CDDA 0.E-3
MacOS Big Sur 11.2.1 (20D74) / iOS 14.4
Mods: dda, no_npc_needs

# Additional context
Those items were owned by that corpse that is under the feet, while it NPC was still alive. It's also strange that those items are marked with red "!" sign, though they are seen as "faction-less" in props.
[Bovard.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6056927/Bovard.zip)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6056928/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6056929/debug.log)
[iOS sentry issue](https://sentry.io/share/issue/468742c6e1d248aaa683caab84b44281/)

**Comment by Jamuro-g** [comment]
fix is in the works ... it happens when you try to move stolen items. i ll make sure to test my solution with your save too.
