### ISSUE TITLE
My custom mutation doesnt work in Magiclysm

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#47806]
Custom mutation maded by armor doesnt work in Magiclysm

I made a custom mutation, that works perfect, when you install it directly to character
in some reason, using cloth that create this mutation on character, it gives you string in status window, but gives you 0 of modifiers that this mutation has. Moving the order of parts changes nothing.

Mutation
```json
{
"type": "mutation",
"id": "BURNSPEED",
"name": { "str": "Burning speed" },
"points": 1,
"description": "TESTTESTTEST",
"types": [ "METABOLISM" ],
"metabolism_modifier": 400.0,
"stamina_regen_modifier": 20.0,
"thirst_modifier": 400.0,
"speed_modifier": 6
},
```
enchantment
```json
{
"id": "ench_burnspeed",
"type": "enchantment",
"has": "WORN",
"condition": "ALWAYS",
"mutations": [ "BURNSPEED", "M_SKIN2" ]
},
```
armor
```json
{
"id": "drive_aura",
"type": "ARMOR",
"category": "armor",
"name": "Drive",
"description": "Is it possible to dart aside and avoid a cannon ball? Is it possible to grab an arrow in flight with one hand?",
"weight": "1 g",
"volume": "1 ml",
"symbol": "o",
"color": "white",
"flags": [ "PERSONAL", "SEMITANGIBLE", "ONLY_ONE", "TRADER_AVOID", "NO_TAKEOFF", "NONCONDUCTIVE" ],
"relic_data": { "passive_effects": [ { "id": "ench_burnspeed" } ] }
},
```
spell
```json
{
"id": "overclocker_drive",
"type": "SPELL",
"name": "Drive",
"description": "The powers of the mana flow into the mage, heightening his speed to supernatural levels. A blur is he amongst his enemies, felling the enemies with blows too swift to see.",
"valid_targets": [ "none" ],
"flags": [ "SOMATIC", "NO_LEGS", "MUST_HAVE_CLASS_TO_LEARN" ],
"effect": "spawn_item",
"shape": "blast",
"effect_str": "drive_aura",
"min_damage": 1,
"max_damage": 1,
"min_duration": 1000,
"max_duration": 40000,
"duration_increment": 1000,
"spell_class": "OVERCLOCKER",
"difficulty": 10,
"max_level": 40,
"base_casting_time": 300,
"base_energy_cost": 900,
"energy_source": "MANA"
},
```

Have no idea why is it happened, know just that problem is in cloth, not in the spell or mutation. KorGgenT says the problem can be in `on_mutate()`

# Screenshots
There is character stats after wearing cloth
![image](https://user-images.githubusercontent.com/67688115/109439103-4c784700-7a2d-11eb-9ab2-ce5cdf3d532b.png)

And here is his stats if i give this mutation directly to character
![image](https://user-images.githubusercontent.com/67688115/109439160-847f8a00-7a2d-11eb-9836-fa22a3aef081.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-9768-gf5e0e6c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills]
    ]

**Comment by anothersimulacrum** [comment]
CC @KorGgenT

**Comment by actual-nh** [comment]
KorGenT had already discussed this with the poster, BTW - problem may not be in JSON (`on_mutate()`).

**Comment by actual-nh** [comment]
I am not finding `on_mutate()` in the code. Could you double-check that's what KorGgenT said?

**Comment by GuardianDll** [comment]
`ok, there must be a bug somewhere related to on_mutate() then`

**Comment by KorGgenT** [comment]
> I am not finding `on_mutate()` in the code. Could you double-check that's what KorGgenT said?

it's Character::on_mutation_gain(), line 11689 in character.cpp

**Comment by actual-nh** [comment]
> it's Character::on_mutation_gain(), line 11689 in character.cpp

Hrm. If it's `recalculate_enchantment_cache` that's ultimately the problem, the code involved is beyond my (current) level of C++. You know it's the cloth - you debug-spawned the cloth and didn't get any effect actually happening?

**Comment by GuardianDll** [comment]
yep, i also test it as normal cloth, without spell, and it still doesnt work
also i found another bug, that, as i think, related to this bug: when i cast my spell, that create slow down effect, it doesnt work with NPC - like this one with cloth. Thats why at first i thought it was my mistake, but i cant find any solution of this
![image](https://user-images.githubusercontent.com/67688115/109729323-fdaae880-7bb7-11eb-884b-7fb594e7e247.png)
it works with another enemies - monsters got this slow down effect, but not NPC

**Comment by KorGgenT** [comment]
so i haven't had the time yet to inspect this, but i did say it might be related to that function. so it might just be the function isn't called properly when wearing the clothing item, or the enchantment cache doesn't update the mutation, or something of that nature.

**Comment by actual-nh** [comment]
In order to add a mutation, magic_enchantment.cpp is doing `mutation.emplace`. However, when mutation.cpp calls `mutation.emplace`, it also calls `cached_mutations.push_back`, `mutation_effect`, and then (after adding all the mutations it's been given at a time) `recalc_sight_limits` and `calc_encumbrance` (and makes sure stamina is not over stamina_max).

**Comment by GuardianDll** [comment]
cause it works right now :derpy:
