### ISSUE TITLE
Activating a hose to siphon fuel gives a debug message

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#47803]
# Describe the bug

When using the `a`ctivate function of a rubber hose near a vehicle with *any* empty tank gives a debug message, `naively asked for first content item and will get a nullptr`

# Steps To Reproduce

1. Get a vehicle having an empty tank installed
2. Get a rubber hose
3. Stand next to the vehicle and `a`ctivate the rubber hose

# Expected behavior

No error

# Screenshots

Full error message:

```
 DEBUG    : naively asked for first content item and will get a nullptr

 FUNCTION : const item &item_contents::legacy_front() const
 FILE     : src/item_contents.cpp
 LINE     : 1144
```

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-9865-g0c24435c6b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

**Comment by anothersimulacrum** [comment]
```diff
diff --git a/src/veh_interact.cpp b/src/veh_interact.cpp
index 1fe20e5eb9..7a5de4f1d0 100644
--- a/src/veh_interact.cpp
+++ b/src/veh_interact.cpp
@@ -2908,7 +2908,8 @@ void act_vehicle_siphon( vehicle *veh )
     std::vector<itype_id> fuels;
     bool has_liquid = false;
     for( const vpart_reference &vp : veh->get_any_parts( VPFLAG_FLUIDTANK ) ) {
-        if( vp.part().get_base().contents.legacy_front().made_of( phase_id::LIQUID ) ) {
+        const item_contents &tank = vp.part().get_base().contents;
+        if( !tank.empty() && tank.legacy_front().made_of( phase_id::LIQUID ) ) {
             has_liquid = true;
             break;
         }
```
Probably fixes it.
