### ISSUE TITLE
Cart Handle vehicle part doesnt appear to function properly

### ISSUE THREAD

**Issue by kholat** [CleverRaven/Cataclysm-DDA#47807]
# Describe the bug

You cannot push or "drive" with a cart handle, which I assume you should be able to from the description:
"A metal handle, a creature with hands could use it to push a vehicle."; you are a creature with hands.

# Steps To Reproduce

Make a frame and weld a cart handle next to it. Try to examine it and harness yourself to it, it says no animal nearby to harness.

# Expected behavior

You should be able to use it somehow to "drive" the cart.

# Screenshots

N/A

# Versions and configuration

 - OS: win10
 - Game Version: 0.E-9845-g99a90ed
 - Graphics version: Tiles
 - Ingame language: english
 - Mods loaded: none

# Additional context

There also exists a flag "HARNESS_human" inside vehicle parts json which is only used on this vehicle part and nowhere else in the code, also there is a food cart vehicle (like for hotdogs I assume?) that has this part so I assume its not meant to be for horse pulling and that job is for the yoke and harness vehicle part.

**Comment by PatrikLundell** [comment]
You can grab a food cart and use that grip to push or pull the vehicle. However, you can do that regardless of whether the vehicle has a handle or not (at least in 0.E2 stable, but I don't think the food cart has a handle in that version: the hand pushed vehicles my character has built don't have any handles anyway).

If I was to guess, the HARNESS_human flag would allow you to get a companion or NPC to pull/push the vehicle, assuming there's code to arrange for it (like a companion command to grab the vehicle).
