### ISSUE TITLE
Segmentation Fault on Load

### ISSUE THREAD

**Issue by bouchacha** [CleverRaven/Cataclysm-DDA#47808]
# Describe the bug
Game crashes upon loading and cites a segmentation fault

# Steps To Reproduce
1. Load game
2. Watch it crash

# Expected behavior
Game shouldn't crash

# Versions and configuration
VERSION: 0.E-9859-g661c627

# Additional context
See attached

[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6058578/config.zip)
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6058579/save.zip)

**Comment by wapcaplet** [comment]
Loading the attached save in 0.E-9866-gf163b8e210 gives "Failed to find item_location owner with character_id 1" and "item_location lost its target item during a save/load cycle" errors as #47799 

Was this save created with a normal quicksave/autosave or "Save and exit" operation, or was it a residual savegame after interrupting the game with Alt+F4?

**Comment by bouchacha** [comment]
I'll have you know, good sir, that accusing me of savescumming by dirty alt-f4 upon my character's death is a grave insult to my reputation.

(I admit that's totally what happened)
