### ISSUE TITLE
Preset sort zones

### ISSUE THREAD

**Issue by Grubleafeater** [CleverRaven/Cataclysm-DDA#47800]
# Is your feature request related to a problem? Please describe.
It's pretty annoying setting up sorting zones over and over.

# Describe the solution you'd like

I'd like to be able to set up preset sorting zones, then load 'em and position them... for example, i could set the filter "c:Guns,c:Ammo,c:Food,c:Books,c:Chem,m:Titanium" to get 90% of the valuables out of a area and into my cargo. But since each cargo space needs its own sorting zone, it would be 20 times faster to be able to select a preset each time rather than type that filter out.

**Comment by kholat** [comment]
I know this is probably going to get mocked but I used to use an AHK script for this because I am incapable of coding in c++; and yes it saves a lot of time in my opinion. If you, or anyone else, wants it, I can give it away no problem.

Having a mainline feature for this would be great ofc.

**Comment by actual-nh** [comment]
AHK?

**Comment by anothersimulacrum** [comment]
AutoHotKey.

**Comment by Salty-Panda** [comment]
That's actually more complicated than you suggest.
You want to assign an unknown amount of zones to an unknown amount of cargo parts of an unknown capacity?

It's fairly easy to hardcode a specific set of zones matching a very specific car, but that's hardly useful.

**Comment by Grubleafeater** [comment]
> That's actually more complicated than you suggest.
> You want to assign an unknown amount of zones to an unknown amount of cargo parts of an unknown capacity?
> 
> It's fairly easy to hardcode a specific set of zones matching a very specific car, but that's hardly useful.



> > That's actually more complicated than you suggest.
> > You want to assign an unknown amount of zones to an unknown amount of cargo parts of an unknown capacity?
> 
> The OP seems to be asking for the ability to set up zones once, then copy them as needed.

This exactly. I suppose being able to directly copy zones would also work, but it's less elegant.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
