### ISSUE TITLE
Segmentation fault while donning a leather duster

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#47817]
# Describe the bug
Tried to wear a leather duster, the game crashed.

# Steps To Reproduce
unknown. Tried to reproduce this from the save but could not. Is the game still not recording the keypresses since last save?

# Expected behavior
no crash

# Versions and configuration
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6064705/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6064708/debug.log)
hippo@hippo-camp:~$ The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 0.E-9855-gfa9b27e
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

    ./cataclysm-tiles(debug_write_backtrace(std::ostream&)+0x49) [0xc1ce95]
    ./cataclysm-tiles() [0xc0509c]
    ./cataclysm-tiles() [0xc0521e]
    /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f89b8bdd210]
    ./cataclysm-tiles(item::item(item const&)+0x33) [0xdf2331]
    ./cataclysm-tiles(player::wear(item_location, bool)+0x4a) [0x1240c08]
    ./cataclysm-tiles(player::sort_armor()+0x15c2) [0xa9f00a]
    ./cataclysm-tiles(game::handle_action()+0x3693) [0xd5ffbd]
    ./cataclysm-tiles(game::do_turn()+0x4e9) [0xd0da77]
    ./cataclysm-tiles(main+0x139c) [0x93124e]
    /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f89b8bbe0b3]
    ./cataclysm-tiles(_start+0x29) [0x9ffa49]

    Attempting to repeat stack trace using debug symbols…
    debug_write_backtrace(std::ostream&)
    ??:?
    log_crash
    crash.cpp:?
    signal_handler
    crash.cpp:?
    ??
    ??:0
    item::item(item const&)
    ??:?
    player::wear(item_location, bool)
    ??:?
    player::sort_armor()
    ??:?
    game::handle_action()
    ??:?
    game::do_turn()
    ??:?
    main
    ??:?
    __libc_start_main
    /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:342
    _start
    ??:?
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6064707/crash.log)
[Uploading debug.log…]()

**Comment by actual-nh** [comment]
Savefile?

**Comment by matt32106** [comment]
Tried to reproduce this from the save but could not. Is the game still not recording the keypresses since last save?
