### ISSUE TITLE
Scrap of meat when butchering fish

### ISSUE THREAD

**Issue by Lamandus** [CleverRaven/Cataclysm-DDA#47811]
Hey guys, what do you think, should we consider changing scrap of meat for fish butchering to scrap of fish? since it is strange that you can make normal meat products out of the scraps but not with the fish filets itself.

**Comment by hexagonrecursion** [comment]
Confirmed. When butchering salmon I gen fillets of fish and scraps of meat
- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 17b9ea1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by NetSysFire** [comment]
This would mean fish scraps need to be added as an item and to the butchery lists and it needs to be investigated where they can be used, as in adding them to any fitting recipes. This should be pretty easy.
