### ISSUE TITLE
Damage to vehicle caused by mob attacks spreads but ignores shock absorbers

### ISSUE THREAD

**Issue by Salty-Panda** [CleverRaven/Cataclysm-DDA#47820]
# Describe the bug

Experienced a few zombie attacks on my car, the damage spreads to other tiles somehow
Checked the code, "SHOCK_ABSORBER" flag is only checked in `vehicle::damage_all` which as far as I can understand is only triggered during collisions ( `*map::move_vehicle` and `map::vehicle_vehicle_collision` ), not monster attacks

# Steps To Reproduce

Have a zombie smack your car with and without shock absorbers on internal parts
Check if they make any difference

# Expected behavior

Not counting extreme cases damage from zombie smashing exterior tiles should not spread
If something like that happens, damage should be reduced properly by shock absorbers

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-9867-gadceb7b [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Mythical Martial Arts [MMA],
    C.R.I.T Expansion Mod [crt_expansion],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Bionic Professions [package_bionic_professions],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP]
]

**Comment by irwiss** [comment]
Skimming code on df589a5e4ffc5d8912b9031928b6f0b5b8be761e monster bash doesn't seem to spread damage, but just to make sure;

I made a 3x3 vehicle with heavy-duty frames, 8 surrounding tiles had hard plating + heavy-duty quarterpanels, inner tile had heavy-duty frame, aisle, shock absorber, motorcycle headlight (for low hp part, it has 8 durability).
Spawned 16 zombie brutes around the car, spammed `.` until they smashed through one of the quarterpanels, center tile had 0 damage.

Unless there's more specific scenario this is likely invalid
