### ISSUE TITLE
[Bug - 0.9-1303-gfe6e883, Windows console] Wacky scent debug messages

### ISSUE THREAD

**Issue by Ishindri** [CleverRaven/Cataclysm-DDA#4782]
Playing the experimental from about two days ago, I went down in a lab and it's completely barren.  No items at all.  Furthermore, I'm getting 'Wacky scent at [coordinates]' debug messages, and a lot of them.

Save exhibiting the issue is here: https://dl.dropboxusercontent.com/u/7857015/save.zip

I don't know if it's pertinent or not, but this character and world were started on the 0.9 RC, ported to stable, then ported to the experimental.

**Comment by mugling** [comment]
Not recently reported in `master` therefore closing due to age and lack of confirmation
