### ISSUE TITLE
We can install foldable seat on the same tile as other seats

### ISSUE THREAD

**Issue by Zeropol** [CleverRaven/Cataclysm-DDA#47824]
# Describe the bug

On vehicles, the foldable seat can be installed even if an other seat is present on the same tile.

# Steps To Reproduce
1. Install a foldable seat.
2. List installable parts : all seats are available for installation. They install without error.

# Expected behavior
Inability to have multiple seats on the same tile, because it is impossible to have multiple characters on the same tile.

# Screenshots
![unnecessary screenshot](https://cdn.discordapp.com/attachments/613424936928804895/816178179697016872/unknown.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-9859-g661c627 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Useful Helicopters [useful_helicopters]
]

# Additional context
Sorry if this is the intended behavior.

**Comment by PatrikLundell** [comment]
Different kinds of seats usually block installation on top of each other because they're all containers, and you can't install two containers on any tile.

The foldable seat doesn't seem to have any storage capacity (and it seems appropriate that it shouldn't), and thus inadvertently bypasses the standard multi install blocking mechanism.

**Comment by Hirmuolio** [comment]
The normal way to block installing things together is the `"location"`. Two vehicle parts with same `"location"` can't be installed on same tile.

Changing this line from "anywhere" to "center" will probably fix this https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/vehicleparts/seats.json#L175

**Comment by Jamuro-g** [comment]
setting it to center does screw with the foldable wheelchair ... might be worthwhile to check for that
