### ISSUE TITLE
Datura can cause negative focus

### ISSUE THREAD

**Issue by LordPancitoFresco** [CleverRaven/Cataclysm-DDA#47829]
# Describe the bug

I eat a single seed of datura on the morning of day 2 which got my focus to 0, i started crafting short cordage ropes and random stuff and at some point it got into negative numbers. 

# Steps To Reproduce

I have no idea
- Eat 1 single seed of datura
- Wait for focus to naturally reach 0 then start crafting
- if second step dont work then activate and set a nail trap repeatedly until it goes below 0
- if none of these work im sorry, i didnt think there was something wrong with focus going negative until someone told me so on discord 

# Expected behavior

Not going bellow 0?

# Screenshots

![Screenshot_20210302_092627_com cleverraven cataclysmdda experimental](https://user-images.githubusercontent.com/64502015/109658066-f8608600-7b44-11eb-913e-ab8b84889fcb.jpg)

# Versions and configuration

- OS: Android
    - OS Version: Manufacturer: HUAWEI; Model: MRD-LX3; Release: 9; Incremental: 9.1.0.308C771; 
- Game Version: ed07fdc [32-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Arcana - UndeadPeople Tileset [ArcanaUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    DinoMod - UndeadPeople Tileset [DinoModUDP],
    MSX Black Military Cars [UDP_BlackMilitaryCars],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP],
    Disable NPC Needs [no_npc_food],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

My save has the Arcana mod and the graphics mods that come with the undeadpeople tileset but i genuinely doubt they have something to do in this. I would add my save on this report but i dont know how to on mobile and i my laptop broke months ago 

I used a spell of magiclysm and i lost experience on said spell which i assume is related to this bug and you can see on the screenshot. 

Sorry if i cant provide a way to reproduce it but i genuinely have no idea how i did it, because when i saw i had negative focus i didn't think lf it as a bug. I just though "well im not eating datura ever again" and just kept playing, but when i casted a magiclysm spell and i actually lost experience from that spell i knew something was wrong.

**Comment by Jamuro-g** [comment]
that bug got fixed roughly around the end of january.
tested with the current version and focus doesn't drop below 0.

**Comment by LordPancitoFresco** [comment]
Well, im playing on the google play experimental version lf the game, and it says so in the report so maybe the fix is to implement the fix on this version too pls

**Comment by LordPancitoFresco** [comment]
Just checked and yeah google play version is outdated as shit. Nevermind then, i guess i will have to manually download the game, or i think i might as well just go back to stable becaise i hate having to manually update.
