### ISSUE TITLE
A way to prevent with long attack times?

### ISSUE THREAD

**Issue by Paperbell** [CleverRaven/Cataclysm-DDA#47832]
I occasionally (w)ield containers as an unarmed character going into a place with a lot of enemies. I eventually mess up and attack while I have the bag, which is now very heavy, so the lost time results in me being basically stunned for a while.

I want some way to warn the player if their attack time will be extremely long. For example, you can get "Attacking with golf bag (39 items) will take a long time, are you sure you want to use it?".

Maybe attack time can be capped and attacks that try to go past this cap end up with penalties due to poor form. Rather than swinging a swag bag like a flail and throwing out your back, you would feebly push with it.

**Comment by BrettDong** [comment]
Implemented in #47835.
