### ISSUE TITLE
[Faction Camp]Giving NPC order to "show me what needs to be done at the camp." crashes the game

### ISSUE THREAD

**Issue by UnFurryCualquiera** [CleverRaven/Cataclysm-DDA#47838]
# Describe the bug
[Faction Camp]Game crashes when re-entering camp after abandoning 

(via "show me what needs to be done at the camp."), 
# Steps To Reproduce

1. Start a camp d -> i
2. Abandon Camp d -> j
3. Ask the NPC to "show me what needs to be done at the camp." d -> k

# Describe the bug

[Faction Camp]Game crashes when re-entering camp after abandoning 

# Expected behavior

The npc giving the list of thing needed to be done in the camp 

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-9867-gadceb7b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    sees-player icon, retrodays [sees_player_retro],
    Graphical Overmap [Graphical_Overmap],
    No Rail Stations [No_Rail_Stations],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    Alternative Map Key [alt_map_key],
    Stats Through Skills [StatsThroughSkills],
    No Fungal Monsters [No_Fungi]
]

# Additional context
[crash+debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6071259/crash%2Bdebug.zip)
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6071260/save.zip)

**Comment by hexagonrecursion** [comment]
Confirmed
```
CRASH LOG FILE: ./config/crash.log
VERSION: 0.F-2000-g1f102d36db
TYPE: St16invalid_argument
MESSAGE: stoi
STACK TRACE:

    ./sanitize-undefined,addresscataclysm-tiles() [0x3042d01]
    ./sanitize-undefined,addresscataclysm-tiles(debug_write_backtrace(std::ostream&)+0x13a) [0x3f8cb3a]
    ./sanitize-undefined,addresscataclysm-tiles() [0x3edfcc3]
    ./sanitize-undefined,addresscataclysm-tiles() [0x3edf951]
    /lib64/libstdc++.so.6(+0xaa08c) [0x721a4a46408c]
    /lib64/libstdc++.so.6(+0xaa0f7) [0x721a4a4640f7]
    /lib64/libstdc++.so.6(+0xaa3a9) [0x721a4a4643a9]
    /lib64/libstdc++.so.6(std::__throw_invalid_argument(char const*)+0x41) [0x721a4a45b34e]
    ./sanitize-undefined,addresscataclysm-tiles(int __gnu_cxx::__stoa<long, int, char, int>(long (*)(char const*, char**, int), char const*, char const*, unsigned long*, int)+0x281) [0x30feef1]
    ./sanitize-undefined,addresscataclysm-tiles(std::__cxx11::stoi(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long*, int)+0x32) [0x30fec62]
    ./sanitize-undefined,addresscataclysm-tiles(basecamp::parse_expansion(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, coords::coord_point<tripoint, (coords::origin)1, (coords::scale)2> const&)+0x185) [0x361fc25]
    ./sanitize-undefined,addresscataclysm-tiles(basecamp::define_camp(coords::coord_point<tripoint, (coords::origin)1, (coords::scale)2> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x350) [0x36212f0]
    ./sanitize-undefined,addresscataclysm-tiles() [0x43612f4]
    ./sanitize-undefined,addresscataclysm-tiles(talk_function::basecamp_mission(npc&)+0x2ae) [0x4361fee]
    ./sanitize-undefined,addresscataclysm-tiles() [0x5fd2f83]
    ./sanitize-undefined,addresscataclysm-tiles() [0x5fd2dad]
    ./sanitize-undefined,addresscataclysm-tiles() [0x5fd2d4d]
    ./sanitize-undefined,addresscataclysm-tiles() [0x5fd2be2]
    ./sanitize-undefined,addresscataclysm-tiles(std::function<void (dialogue const&)>::operator()(dialogue const&) const+0x6d) [0x599c7ed]
    ./sanitize-undefined,addresscataclysm-tiles(talk_effect_fun_t::operator()(dialogue const&) const+0x33) [0x599c763]

```

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 0.F-2000-g1f102d36db [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    sees-player icon, retrodays [sees_player_retro],
    Graphical Overmap [Graphical_Overmap],
    No Rail Stations [No_Rail_Stations],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    Alternative Map Key [alt_map_key],
    Stats Through Skills [StatsThroughSkills],
    No Fungal Monsters [No_Fungi]
]

**Comment by hexagonrecursion** [comment]
Possible duplicate: #45731
