### ISSUE TITLE
Slipping on mechanical fluid should have it's own message

### ISSUE THREAD

**Issue by jagoly** [CleverRaven/Cataclysm-DDA#47847]
# Is your feature request related to a problem? Please describe.
I'd just finished clearing out a mil outpost and was looting it. I kept getting the message "You're knocked to the floor!". My first thought was there was some hidden zombie bio op doing something to me, but no. Then I thought that I was getting radiation weakness from somewhere, again no.

In the end I did a search through the code to find places that the downed effect gets applied, and it turns out that https://github.com/CleverRaven/Cataclysm-DDA/pull/46603 also allows the player to slip over on grease.

# Describe the solution you'd like
Just print out a message before applying the effect. Something as simple as "You slip on the mechanical fluid!".

# Describe alternatives you've considered
Doing a PR for this. Decided against because of string freeze.

**Comment by Night-Pryanik** [comment]
No longer an issue after #47851.
