### ISSUE TITLE
Uncraftable fried eggs when ingredients are in hide bag

### ISSUE THREAD

**Issue by TandemElephant** [CleverRaven/Cataclysm-DDA#47842]
# Describe the bug

Attempting to craft fried eggs when contained in a hide bag results in two errors, depending on whether the hide bag is worn or not. No issue is present when ingredients are unloaded from the bag.

# Steps To Reproduce

1. Make a player with the following items & skills:
    * hide bag
    * eggs + animal cooking oil 
    * frying pan (cooking equipment)
    * planks + lighter (tools for lighting fire)
    * food handling 2
2. Light a fire.
3. Wear hide bag, make sure all the ingredients are in it.
4. Try crafting fried eggs, it is interrupted by an error message: Attempted a recipe with no available components!
5. Drop hide bag with the ingredients still in it.
6. Try crafting fried eggs, a strange prompt appears as if you were wielding the in-progress craft beforehand (screenshot 1). 
    * Options 1 and 2 result in a prompt for missing ingredients (screenshot 2). Saying yes brings up the prompt again. Continuously pressing 'Y' eventually completes the craft, and only consumes the ingredients once.
    * Options 3 and 4 result in simply dropping the in-progress fried eggs (0%). Activating it results in the same behaviour as for options 1 and 2.

# Expected behavior

Normal crafting of fried eggs.

# Screenshots

![strange_prompt](https://user-images.githubusercontent.com/47660135/109726051-54adbf00-7bb2-11eb-99a6-9b16e0de0bae.png)

![continuous_prompt](https://user-images.githubusercontent.com/47660135/109726088-63947180-7bb2-11eb-96d3-b7d3decd0841.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-9867-gadceb7b [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Packaging [Packaging],
    Mining Mod [Mining_Mod],
    More City Locations [cityside],
    No Rail Stations [No_Rail_Stations],
    Stats Through Skills [StatsThroughSkills],
    Arcana and Magic Items [Arcana],
    Arcana - UndeadPeople Tileset [ArcanaUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mining Mod - UndeadPeople Tileset [Mining_ModUDP],
    More Locations [more_locations],
    More Locations - UndeadPeople Tileset [more_locationsUDP],
    MSX Indicators: Xotto [UDP_XOTTO_INDICATORS],
    Alternative Map Key [alt_map_key],
    More Survivor Stuff [more_survivor_stuff]
]

# Additional context

**Comment by RenechCDDA** [comment]
Still valid! It's skipping checking the contents because the hide bag is itself a comestible, which means it's count by charges.

https://github.com/CleverRaven/Cataclysm-DDA/blob/05fe4bd44cdc39347ff09582ebf91c32db704ba2/src/item.cpp#L11884-L11885

Should be resolved by #60885
