### ISSUE TITLE
Pots and coffee mugs cannot be directly filled as container from water pump

### ISSUE THREAD

**Issue by yourlocalchef** [CleverRaven/Cataclysm-DDA#47858]
# Describe the bug

Stated in title. When I wanted to fill a mug or pot with water directly from the faucet these were not listed as container options.

# Steps To Reproduce

Spawn coffee mugs and pots (not tested but try other household cooking items)
Go to water pump and attempt to fill container

# Expected behavior

While I understand they aren't containers with lids and cannot be stored, I should be forced to wield them when they have water contained
# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-9887-gfa86903 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

**Comment by PatrikLundell** [comment]
I assume they work the same as buckets. To fill a bucket you have to wield it. Once filled you can put it down, but then only pick it up by wielding it.

**Comment by akirashirosawa** [comment]
Containers without a lid, such as a mug, must be held in hands, as water will spill in the backpack. This is not a bug, this is a feature :)

**Comment by Qrox** [comment]
We can definitely list them in container selection with a message explaning that they need to be wielded.
