### ISSUE TITLE
Rename "Nails" to "Fasteners"

### ISSUE THREAD

**Issue by Fosheze** [CleverRaven/Cataclysm-DDA#47889]
# Is your feature request related to a problem? Please describe.
For some reason bolts and screws were never invented in the Cataclysm Universe. It would make sense to have them for many crafting recipes where using nails wouldn't make any sense.

# Describe the solution you'd like
Simply rename nails to fasteners then change the description to match. Then "fasteners" could be added to various crafting recipes. For example, many of the items that currently require welding could have alternates that required drilling and fasteners. Fasteners could also be used on vehicles in place of welding for many tasks. Screw driving could be an alternative to hammering for many tasks. You could basically just sprinkle a few "fasteners" into many recipes and construction tasks.

# Describe alternatives you've considered
Adding separate bolt and screw items. - I could see this getting needlessly complex for no real gain. After all if there are nails, bolts, and screws then why aren't there threaded rod, rivets, nuts, washers, snap rings, concrete anchors, pins, u-bolts, eye bolts, etc. Yes you can conceivably harvest "fasteners" from something that would realistically be using a bolt and then use that "fastener" to nail a something together but I don't thing that would be immersion breaking enough to be worth the effort of adding every individual fastener as a different item. Many of them are also interchangeable in that you can use screws or nuts and bolts for most of the things that you can use nails for.

# Additional context
This does seem a little petty but it's also not that big of a change and it is something that has always bothered me a bit.

**Comment by kevingranade** [comment]
The bolt acting like a nail problem isn't so bad, the problem is mass harvesting or even crafting nails and then turning around and using them as bolts, which very much doesn't work.
If we start using metal fasteners instead of welding everything (and we should), we absolutely will want to maintain a difference between nails and bolts.
Possibly something similar to what you're saying could happen, "wood fasteners" vs "metal fasteners".

"Misc fasteners that work by embedding themselves in wood, such as nails and wood screws"

**Comment by Fosheze** [comment]
> The bolt acting like a nail problem isn't so bad, the problem is mass harvesting or even crafting nails and then turning around and using them as bolts, which very much doesn't work.
> If we start using metal fasteners instead of welding everything (and we should), we absolutely will want to maintain a difference between nails and bolts.
> Possibly something similar to what you're saying could happen, "wood fasteners" vs "metal fasteners".
> 
> "Misc fasteners that work by embedding themselves in wood, such as nails and wood screws"

I can definitely see your point there. You don't want somebody pulling a bunch of screws out of cell phones and then using them to bolt a wheel hub on. However I would be skeptical about using material classifications. When we're talking about wood screws  or sheet metal screws that tells you what you "should" use those fasteners on. However a post-apocalyptic survivor is going to care more about what they "can" use those fasteners for. It's the apocalypse, nobody is going to judge you for screwing that hunk of sheet metal to your deathmobile with drywall screws. I think a better way to differentiate them would be the following.

Simple Fasteners - Anything a blacksmith could easily make by hand
Examples: Nails, Pins, simple hand made rivets
Used in: furniture, basic construction, simple hand made crafts

Fine Fasteners - Very precise and/or very small fasteners 
Examples: Spring clips, small machine screws, fine pins
Used in: Most Electronics, power tools, firearms, CBMs (Aftershock)

Light Fasteners - All of your standard everyday off the shelf fasteners that aren't already in the simple fasteners category
Examples: wood screws, self tapping metal screws, small bolts, most machine screws
Used in: Anywhere simple fasteners could also be used, appliances, larger electronics, light weight vehicle components

Heavy Fasteners - High strength or large fasteners.
Examples: Any larger bolt (10mm+), concrete anchors, timber screws/bolts, large threaded studs
Used in: Machinery, heavy/critical vehicle components,  any sort of heavy duty construction

**Comment by Malorn-Deslor** [comment]
I think four different types of fastener might be going a little too far... but I agree with the core concept of more options for metalwork.

On the other hand, it may not really be very much fun to track bolts, etc. It works fairly well to assume that a wheel has the bolts required to attach it included with the wheel. The only real place where bolts would be helpful would be metal construction methods...

And honestly, making nails is fairly easy, making bolts with fine threading which matches properly is just... well, extremely difficult (read nearly impossible) to do without a machine shop. Welding, on the other hand, is actually quite easy, assuming you have the proper equipment to do it. I think any bolt system should be used as an alternative option, not one which replaces welding as an option.

In theory, some sort of new heavy attachment method such as heavy fasteners might be useful, but only if there were enough use cases. Right now there isn't much use for concrete anchors, etc.

Also, if we are going this far into fasteners... can we talk about pegs? Wooden peg construction is the golden standard of furniture making, and yet we can only use nails... 

Of course, one could rightfully say this would make woodworking too simple, if time consuming. But if we are aiming for proper balance and not pure realism here, then let's not go crazy the other direction with adding tons of fastener options.



> 
> 
> The bolt acting like a nail problem isn't so bad, the problem is mass harvesting or even crafting nails and then turning around and using them as bolts, which very much doesn't work.
> If we start using metal fasteners instead of welding everything (and we should), we absolutely will want to maintain a difference between nails and bolts.
> Possibly something similar to what you're saying could happen, "wood fasteners" vs "metal fasteners".
> 
> "Misc fasteners that work by embedding themselves in wood, such as nails and wood screws"

I think a wood vs metal distinction might be very reasonable. In such a case would we want to all metal fasteners to be used for wood? I'm trying to think of a fastener type that can work on metal (other than welding, obviously), which would not work on wood.

**Comment by Maddremor** [comment]
I think it makes more sense to create a "fastener" requirement group that can be filled with screws, bolts, or even dowels than it does to make the current nails generic.

**Comment by Fosheze** [comment]
> I think it makes more sense to create a "fastener" requirement group that can be filled with screws, bolts, or even dowels than it does to make the current nails generic.

In my second comment I basically have just that. Nails are more or less in a group all to themselves in the "simple fasteners" group. There are only a few other things in that group which are very similar in make. After all a nail is just a metal pin with one end sharpened and if you hammer a nail through something thin and then bend the end over you then have a simple rivet. All three are just metal rods of very slightly different make.

**Comment by Fosheze** [comment]
>Also, if we are going this far into fasteners... can we talk about pegs? Wooden peg construction is the golden standard of furniture making, and yet we can only use nails...

>Of course, one could rightfully say this would make woodworking too simple, if time consuming. But if we are aiming for proper balance and not pure realism here, then let's not go crazy the other direction with adding tons of fastener options.

While I do agree that should be an option, my dad does furniture restoration IRL so I can tell you that wooden pegs definitely aren't the gold standard in woodworking due to the ease but rather the durability. You have to remember that you are adding several other steps over just hammering in a nail. To use pegs/plugs you also need either drilling of chiseling (depending on the peg/plug) along with an adhesive and either clamping or nails to hold the whole thing until the adhesive sets. You can do dovetail joints without glue however getting everything cut just perfectly so that is stays together (with hand tools remember) requires requires far more craftsmanship than even most woodworkers IRL have. Even just using dowels requires a greater degree of craftsmanship than using nails because you need to make sure everything will line up while it's still apart rather than just lining it up and driving a nail in right away. Having to add all of those steps would add significantly more work to carpentry projects in game. It would be convenient for high skill in-a-woods characters but for a normal character it would just be far more effort than it is worth.

>And honestly, making nails is fairly easy, making bolts with fine threading which matches properly is just... well, extremely difficult (read nearly impossible) to do without a machine shop. Welding, on the other hand, is actually quite easy, assuming you have the proper equipment to do it. I think any bolt system should be used as an alternative option, not one which replaces welding as an option.

I agree that hand making bolts would not be a practical option however it isn't impossible. Getting the threads right just requires a set of taps (which would need to be added). Ideally you would use a lathe to turn down a metal rod to thread with the tap however blacksmiths have been making relatively precise round rods for far longer than the lathe has existed. That is also why nails were separated out with simple fasteners. In my mind the simple fasteners would just use the exact same crafting recipe that nails currently use.

>On the other hand, it may not really be very much fun to track bolts, etc. It works fairly well to assume that a wheel has the bolts required to attach it included with the wheel. The only real place where bolts would be helpful would be metal construction methods...

I agree 100%. For something like bolting a tire on you would assume that the lug nuts were included with the wheel hub because those are basically a set. Where the fastener items would come in is for something like bolting your engine in. Seeing as how the survivor would have to be hand making an engine mount and every engine has a different way that it attaches, it wouldn't be reasonable to assume that the engine just happened to come with the proper fasteners to bolt onto the cobbled together engine mount. At the same time the engine can't just be welded in place. The same would be true of doors, trunks, seats, seatbelts, controls, alternators, or anything else that couldn't just be welded in place and had a custom made attachment point. For those items which are welded, fasteners should be an alternative in most cases. Just off the top of my head I can't think of anything that _"needs"_ to be welded on. Even body panels _"can"_ be bolted together.

>I think a wood vs metal distinction might be very reasonable. In such a case would we want to ensure metal fasteners can be used for wood? I'm trying to think of a fastener type that can work on metal (other than welding, obviously), which would not work on wood.

This kind of illustrates my point on not using material classifications though. You can use most metal fasteners on wood and you "can" use a lot of wood fasteners on metal. I do hardware repair for warehouse equipment and I can not count the number of times where some maintenance guy on site has stripped out the proper machine screw so they decide to just ram a wood screw into the fine pitch threaded aluminum hole to hold things together. It makes me rip my hair out because I have to try and fix it afterwards but in a survival scenario something like that does work. Having fasteners classified by material is something we do IRL because that's what those fasteners "should" be used for. But if you're like those maintenance guys or our survivor and have no shame then you can use them for whatever you want as long as they will take the load.

>I think four different types of fastener might be going a little too far... but I agree with the core concept of more options for metalwork.

My reasoning behind each of the 4 categories is as follows.
Simple fasteners - These need to be separate because these are the only ones which are feasible to make by hand.

Fine fasteners- These are separated because these are far too small or light weight to use for most practical purposes. At the same time there are some small or light weight tasks which wouldn't be able to accommodate a standard size fastener. Think the screws holding your cell phone together or the screws holding your computer together. These would most likely be found in electronics stores.

Light fasteners - This is the standard fastener category for most light duty work. All of the other categories were separated from this category. For most tasks this is what will be used with simple fasteners being an alternative for woodworking. These are separate from simple fasteners because nails don't work for most metal working tasks no matter how hard you try. These are what you would find in bulk in a hardware store along side simple fasteners.

Heavy Fasteners - These are the fasteners you use when a light fastener isn't enough. These would be used for tasks such as bolting an engine in your car, attaching a boom crane, bolting on a wheel hub, or attaching rams. These are what you use when  there is a large amount of force that needs to be absorbed by the fastener and where their bulk won't be an issue. These would be found in garages and on construction sites.

Each of these has their own specific niche and any attempt I make to pair it down any more leads to strange scenarios such as using screws from a cell phone to hold your seat belt in or using the machine screws from a microwave to hold the rams on your car. Originally simple fasteners were lumped in with light fasteners to reduce the number of categories but I decided that they needed to be separate just so their crafting recipe still made sense.

**Comment by kevingranade** [comment]
> nobody is going to judge you for screwing that hunk of sheet metal to your deathmobile with drywall screws

Wood screws being used on wood isn't a matter of societal conventions, wood screws simply don't work properly on metal and machine screws simply don't work on wood.  Can you jam them in the opposing type of hole? Absolutely. Is it going to actually hold things on as expected? Not at all. In cataclysm, our approach is "Either disallow things that don't work well, or add the nuance necessary to make them work, but not well".  As such, using wood screws (or duct tape) to assemble vehicle parts should be disallowed unless those parts have a reasonable chance of failing as a result.  I'm really spectacularly not interested in implementing that, so we're left with disallowing it, which I don't see any meaningful impact from one way or the other.

I understand why you want to abstract these differences away, but I don't agree that it's reasonable to do so.  As a result, and combined with the issues you bring up, we're likely to end up with a half dozen to a dozen different fastener types at the end of the day.

**Comment by actual-nh** [comment]
> I understand why you want to abstract these differences away, but I don't agree that it's reasonable to do so. As a result, and combined with the issues you bring up, we're likely to end up with a half dozen to a dozen different fastener types at the end of the day.

Potentially including velcro held on with superglue - something close to that actually has been shown to be enough to hold vehicle parts on! (I say "close to" because the velcro was molded into the plastic vehicle parts in question, so how much heat superglue can take would be a factor.)

**Comment by Fosheze** [comment]
> > nobody is going to judge you for screwing that hunk of sheet metal to your deathmobile with drywall screws
> 
> Wood screws being used on wood isn't a matter of societal conventions, wood screws simply don't work properly on metal and machine screws simply don't work on wood. Can you jam them in the opposing type of hole? Absolutely. Is it going to actually hold things on as expected? Not at all. In cataclysm, our approach is "Either disallow things that don't work well, or add the nuance necessary to make them work, but not well". As such, using wood screws (or duct tape) to assemble vehicle parts should be disallowed unless those parts have a reasonable chance of failing as a result. I'm really spectacularly not interested in implementing that, so we're left with disallowing it, which I don't see any meaningful impact from one way or the other.

You are correct that it isn't solely societal convention however most of the issues involved in using the wrong fasteners mainly just make any sort of future work on the part a complete pain. Considering that preventative maintenance isn't a thing that currently exists or seems like it will ever exist in game (routine oil changes don't really add anything to the game)  and repairs are just done with a generic process depending on the material, this doesn't seem like it would be a factor in game. You absolutely can use a machine screw or bolt and a nut to fasten wood together. Fastening sheet metal with woodscrews has been a mainstay of broke teenagers "fixing" rust holes in their cars for years. As I had stated in an earlier comment, I routinely see people IRL shove woodscrews into metal threaded holes to make their stuff work when they lose the proper fastener and it does exactly that. Assuming that part never needed to be worked on again then odds that fastener would hold perfectly fine for the life of the part. A lot of times the wrong fastener holds better and is much harder to remove than the proper fastener would have been. The problem only comes in when I have to work on it later and wind up having to drill out and retap the hole.  It's actually frequently easier to get something working the wrong way than to get it working the right way. This can be easily demonstrated by any maintenance person having ample stories of only discovering duct tape and chewing gum fixes performed by a some rando after that fix had been working for years. Those fixes are always tremendous fun to re-fix but most of the time if they worked to begin with then they will continue to work as long as no one touches it.

>I understand why you want to abstract these differences away, but I don't agree that it's reasonable to do so. As a result, and combined with the issues you bring up, we're likely to end up with a half dozen to a dozen different fastener types at the end of the day.

The issues of adding fastener types still exists with material qualifiers. For example, what about plastic? Plastic pieces can be fastened together with course thread self taping fasteners like wood or it can have pretapped holes for machine screws like metal. Using material qualifiers is also going to lead to people wondering "Why can't I bolt my table legs on in game like they are on my table IRL?" or "Why can I take the screws out of my microwave and use them to bolt a door onto my car?". You would still need to classify them by strength as well and there would still be edge cases where the material classifications wouldn't make sense. Just classifying the fasteners by strength to begin with and abstracting the material portion as just the survivor doing their best Mad Max impression would lead to fewer edge cases and confusion.

Ultimately either way would work. I just feel that using material classifiers would lead to far more gamey strangeness than using strength classifiers.

**Comment by Malorn-Deslor** [comment]
> While I do agree that should be an option, my dad does furniture restoration IRL so I can tell you that wooden pegs definitely aren't the gold standard in woodworking due to the ease but rather the durability. You have to remember that you are adding several other steps over just hammering in a nail. To use pegs/plugs you also need either drilling of chiseling (depending on the peg/plug) along with an adhesive and either clamping or nails to hold the whole thing until the adhesive sets. You can do dovetail joints without glue however getting everything cut just perfectly so that is stays together (with hand tools remember) requires requires far more craftsmanship than even most woodworkers IRL have. Even just using dowels requires a greater degree of craftsmanship than using nails because you need to make sure everything will line up while it's still apart rather than just lining it up and driving a nail in right away. Having to add all of those steps would add significantly more work to carpentry projects in game. It would be convenient for high skill in-a-woods characters but for a normal character it would just be far more effort than it is worth.

I certainly agree it's not something that is easy. As you say, it's a gold standard due to durability, not ease. Though I will say... it's easier to do when you don't care about the looks, speaking from personal experience. But I certainly am not arguing they are 'easier' in any way than running a nail in. But nor do I agree that rough-use pegs are actually that difficult to realistically use.

::::::

That said, I need to agree with Fosheze above, that it is entirely possible to use the 'wrong' thing a lot and have it end up working.

**Comment by Fosheze** [comment]
>I certainly agree it's not something that is easy. As you say, it's a gold standard due to durability, not ease. Though I will say... it's easier to do when you don't care about the looks, speaking from personal experience. But I certainly am not arguing they are 'easier' in any way than running a nail in. But nor do I agree that rough-use pegs are actually that difficult to realistically use.

That's an excellent point on the difficulty if you don't care about looks. However you would still be adding adhesive, drilling, and some sort of clamping requirements. Of course for in-a-woods players that is probably easier to do than making nails. As it is there isn't a primitive drilling implement however it wouldn't be difficult to add a bow drill to the game. For the adhesive all you would need is bone glue. Clamping would be a little more tricky but just tying the pieces together with a length of cordage rope until the glue sets would probably work as a stand in for a proper clamp.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
