### ISSUE TITLE
Bug: Item Multiplication when moving "amount"

### ISSUE THREAD

**Issue by AcidAntOnAMinefield** [CleverRaven/Cataclysm-DDA#47884]
# Describe the bug
Moving items using (m) in the / menu causes the game to multiply the items in question on occasion

# Steps To Reproduce

1. Create a test world
2. Spawn any item that has “multiples” under ( ) in front of the name (ammo, some foods, some drugs, cotton sheet and other spare parts that work the same way)
3. place them on the floor anywhere (or inside a vehicle cargo space, or a cupboard, locker, etc) and open the “/” menu.
4. use “m” to move an amount of the item from one space to another, as long as the amount is less than than the current total available. (for example 100 aspirin, (m)ove 50)
5. End result will be Aspirin(100) on one side, Aspirin(50) on the other.

# Expected behavior
The amount that was moved should be deducted from the original pile.

# Screenshots
[https://cdn.discordapp.com/attachments/708349639371259907/817411011355082782/unknown.png](url)

[https://cdn.discordapp.com/attachments/708349639371259907/817411175561822228/unknown.png](url)

[https://cdn.discordapp.com/attachments/708349639371259907/817411350942449664/unknown.png](url)

# Versions and configuration

 OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-9933-gfd076b9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    No Monsters [Only_Wildlife]
]

# Additional context
Previously reported here: https://discourse.cataclysmdda.org/t/bug-moving-items-using-m-causes-the-game-to-multiply-the-items-in-some-cases/26032

Reported on github per request.

**Comment by Jamuro-g** [comment]
i think i have a solution (this was caused by my stolen items pr) ... need to do some more testing to make sure though
