### ISSUE TITLE
Halligan Bar no longer fits in Fire Axe pocket

### ISSUE THREAD

**Issue by Djinn247** [CleverRaven/Cataclysm-DDA#47886]
# Describe the bug
After commit 5172bb5 the item Halligan Bar which used to fit inside a Fire Axe, no longer does so.

# Steps To Reproduce
1. Start game with build older than 11505
2. Insert Halligan Bar into Fire Axe
3. Update game
4. Observe error on load that Halligan Bar does not fit in pocket: "too long" error.

# Expected behavior
Halligan Bar was expected to fit into Fire Axe same way firefighters wield them.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-9945-g5960368 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Mythical Martial Arts [MMA],
    Graphical Overmap [Graphical_Overmap],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by actual-nh** [comment]
@Lamandus: The max item length in the fire axe "pocket" needs adjusting.

**Comment by Lamandus** [comment]
> 
> 
> @Lamandus: The max item length in the fire axe "pocket" needs adjusting.

ah yeah, on it.

**Comment by wapcaplet** [comment]
Fixed by #47902 and confirmed in 0.E-10120
