### ISSUE TITLE
rubber gloves have absurdly high bash protection

### ISSUE THREAD

**Issue by nornagon** [CleverRaven/Cataclysm-DDA#47900]
# Describe the bug

Rubber gloves have a bash protection value of 15. This is higher than almost any other gloves in the game. For example, armored gauntlets have a bash protection of 12. Bone armor gauntlets have a bash protection of 8. Fire gauntlets have a bash protection of 6.

It makes no sense that rubber gloves should be twice as effective as bone armor gauntlets at protecting against blunt impacts. Probably the value should be closer to 2–3?

It looks like this comes from the bash resist value of the rubber material, which is 5. It should perhaps be lower... Either that, or the `material_thickness` of rubber gloves should be lower.

# Versions and configuration

Checked at build 11511 (5960368)

**Comment by nornagon** [comment]
Supporting evidence:

Rubber gloves:
![image](https://user-images.githubusercontent.com/172800/110198585-71dbcb00-7e08-11eb-8eb6-f888318875b8.png)

Bone gauntlets:
![image](https://user-images.githubusercontent.com/172800/110198595-8a4be580-7e08-11eb-9e57-e05e6e84bdb8.png)

**Comment by actual-nh** [comment]
The current gloves have a `material_thickness` of 3. Thick rubber gloves for dishwashing appear to be about 15 "mils" thick (google "[rubber gloves thickness dishwashing](https://www.google.com/search?q=rubber+gloves+thickness+dishwashing&ei=kAxFYPvWIKqJ5wKMq7yADA&start=20&sa=N&ved=2ahUKEwj73uHX2Z7vAhWqxFkKHYwVD8A4ChDw0wN6BQgEELUB&biw=1434&bih=746)"). Mils are 0.001" (see [this site](https://www.grainger.com/know-how/safety/ppe-in-the-workplace/hand-protection/kh-choosing-the-right-disposable-glove-394-qt#:~:text=Glove%20material%20thickness%20is%20usually,flexibility%20and%20sense%20of%20touch.) - also has some further possibly-useful info, BTW). From this, looks like reasonable-thickness gloves should be ~0.35 mm thick (and probably should have a lower encumbrance - work gloves have a thickness of 2 and an encumbrance of 20).

I note that there is some confusion on various sites about 15 mils vs 15 mm. 15 mm is over half an inch thick, so I somewhat doubt that's the thickness of any very common set of gloves...

**Comment by nornagon** [comment]
I wonder if the thickness is there to up the acid protection value? if so we might also want to tweak the acid protection up so we retain that.

**Comment by actual-nh** [comment]
> I wonder if the thickness is there to up the acid protection value? if so we might also want to tweak the acid protection up so we retain that.

Currently, item.cpp says (in item::acid_resist):
```
        // Not sure why cut and bash get an armor thickness bonus but acid doesn't,
        // but such is the way of the code.
```
The only thing it's currently reduced by in acid_resist is not having environmental_protection 10+:
```
    if( env < 10 ) {
        // Low env protection means it doesn't prevent acid seeping in.
        resist *= env / 10.0f;
    }
```
Which is a bit odd with coverage 100%, but I suppose environmental protection is abstract enough for this to make some sort of sense...

**Comment by actual-nh** [comment]
OK, PR created. The bash protection will now be 1.75 (not sure offhand if that rounds in use) with thickness 0.35 and encumbrance 4. Also altered the volume to 250 mL (matching, among others, wool and work gloves).

**Comment by nornagon** [comment]
We might want to do rubber boots too: https://github.com/CleverRaven/Cataclysm-DDA/blob/8bde748470e32b9ff61a287804bca09b142c3d2e/data/json/items/armor/boots.json#L472
