### ISSUE TITLE
Some items don't get sorted, using normal zones overlaped by custom ones.

### ISSUE THREAD

**Issue by Lamandus** [CleverRaven/Cataclysm-DDA#47904]
# Describe the bug
On some of my last runs (also on that one) I have problems of sorting food items and seed. On one point it just stops working correctly and I can't tell why.

# Steps To Reproduce
1. Open my save.
2. try to sort with "O"
3. see that he won't sort the seed on the ground and the food as well (not the table)

# Expected behavior
Sorting also the rest of my items (Food and seeds (on standing tile)

# Screenshots

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-9945-g5960368 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    meins [mine],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    Fewer Farms [Fewer_Farms],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context
[Landsberg am Lech.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6095143/Landsberg.am.Lech.zip)

my save.

**Comment by Djinn247** [comment]
after disabling the custom loot zone "FiIlthy" which was on top of the seeds zone, it worked

**Comment by Lamandus** [comment]
> 
> 
> after disabling the custom loot zone "FiIlthy" which was on top of the seeds zone, it worked

ok, so another zone ontop others is a "AND" and not "OR"

**Comment by Djinn247** [comment]
it should be OR, i do not know why they are conflicting. it could be due to a mod.

**Comment by Lamandus** [comment]
nah the mods don't adress anything about the zones. Someone with some "knowledge of the zones" may look into that as well.

**Comment by Djinn247** [comment]
does "Nonperishable Overhaul" affect seeds?

**Comment by Lamandus** [comment]
it does, some of them, none of the ones you see tho.

I restarted the save without mods (just DDA) and it still doesn't work. So that's not it.
