### ISSUE TITLE
Stationary demon forges are inoperable because of charge loading bug. 

### ISSUE THREAD

**Issue by TheMrMomo** [CleverRaven/Cataclysm-DDA#47910]
# Describe the bug

The demon forges in forge of wonders don't work and can't be reloaded. 

# Steps To Reproduce

1. Go to the Forge of Wonders and try to craft anything. 
2. Opening the crafting menu will display the bug. 
3. You can't use the forges since they don't have any charges. 

# Expected behavior

The alumentum needs to be placed into the forge correctly for it to work. 

# Screenshots
This is the error message: 

 DEBUG    : tried to put an item (alumentum) count (0) in a container (demon_forge) that cannot contain it: pocket unacceptable because item is not the correct ammo type

 FUNCTION : ret_val<bool> item::put_in(const item&, item_pocket::pocket_type, bool)
 FILE     : src/item.cpp
 LINE     : 1115

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-9859-g661c627 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm]
]

 -->

# Additional context

**Comment by actual-nh** [comment]
Ping: @KorGgenT?

**Comment by Evrze** [comment]
It was a straightforward bugfix, the demon forge furniture version was trying to accept alumentum but the ammo restrictions for its magazine/fuel was charcoal.

No longer do you have to craft your own demon forge that takes insane amounts of demon chitin plates to make your ingots and weapons or be locked out of it.
