### ISSUE TITLE
Magiclysm:No Tainted Blood; Can't Fuel CBM with Kit-Drawn Blood 

### ISSUE THREAD

**Issue by Grubleafeater** [CleverRaven/Cataclysm-DDA#47924]
# Describe the bug

Butchering zombies doesn't give tainted blood; zombies can't be bled because they 'have no blood'; using blood draw kits gives blood specific to the monster that cannot be used as fuel, including own.

# Steps To Reproduce

Kill zombie. Butcher zombie. Note lack of 'bleed' option. Obtain blood draw kit and install blood generator CBM. Use kit on self and on zombie. Note that 'eat' actually has you drink the blood.

# Expected behavior

Should be able to obtain Tainted Blood to fuel CBM with. Should be able to fuel CBM with my own blood.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-9887-gfa86903 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Aftershock [aftershock],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi]
]

**Comment by Fris0uman** [comment]
Can't reproduce on latest master.

Load world, spawn butchering kit, kill zombies, trie to bleed it > 
![image](https://user-images.githubusercontent.com/41293484/110241628-1289d200-7f52-11eb-85a1-599d4e1c8cc4.png)


- OS: Windows
    - OS Version: 10.0 2004
- Game Version: Please install `git` to generate VERSION [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi]
]

**Comment by Fris0uman** [comment]
However there is some sort of bug or at least unlcear UI from using blood draw kit 
![image](https://user-images.githubusercontent.com/41293484/110241744-aa87bb80-7f52-11eb-94b7-821a489c14ad.png)

because it gives me some [monster name] blood that shows up aas fuel in the consumption menu, but is going to end up being eaten instead.

**Comment by Grubleafeater** [comment]
Updated and it's still happening, so I don't know why it's happening.

**Comment by Grubleafeater** [comment]
[South Gastonia_copy_copy_copy.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6097690/South.Gastonia_copy_copy_copy.zip)

For outside testing.

**Comment by Grubleafeater** [comment]
Weird; I can't do it to animals either, but if I order a NPC to butcher, they'll harvest blood anyway.

**Comment by wapcaplet** [comment]
Confirmed in 0.E-9956-gf6f104a441 in a new game with Aftershock, Magiclysm, Blaze Industries, and No Fungal Monsters added. Spawned a zombie, killed it, and tried to `B`utcher, but it has no blood:

![image](https://user-images.githubusercontent.com/238395/110257552-a4e2a380-7f5b-11eb-9424-8acc4f2aece1.png)

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-9956-gf6f104a441 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Aftershock [aftershock],
    No Fungal Monsters [No_Fungi],
    Blaze Industries [blazeindustries]
]

**Comment by Maleclypse** [comment]
Is aftershock messing with blood harvests?  (I feel like I should call for a Daywalker after that sentence)

**Comment by Mom-Bun** [comment]
I have no earthly idea how aftershock is causing this honestly...

**Comment by anothersimulacrum** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/58d6d54fe588daa974a57e922f7f7810f794a831/data/mods/Aftershock/items/afs_harvest.json

**Comment by Mom-Bun** [comment]
> https://github.com/CleverRaven/Cataclysm-DDA/blob/58d6d54fe588daa974a57e922f7f7810f794a831/data/mods/Aftershock/items/afs_harvest.json

Ah makes sense
Most titanium stuff is going to get scrapped for aftershock tier 1 scrap instead; so this might be due to get cut out maybe
