### ISSUE TITLE
Missing and/or confusing mapgen monster spawn documentation

### ISSUE THREAD

**Issue by Venera3** [CleverRaven/Cataclysm-DDA#47942]
# Describe the bug

There are a lot of redundant ways to spawn monsters when making a map, and the documentation does a pretty bad job of listing them and their respective use cases. In addition, some important variables are either completely undocumented or their use and function is hard to glean from their documentation.

To whit, there's:
- Explicit placement using grid coordinates either with specific monster IDs or using monster groups that use very similar syntax and *require* `density` (itself an unhelpfully documented variable)
- Object placement using a symbol, either with a specific monster ID or a monster group (again, annoyingly similar and not explicitly documented syntax), ~~that is not affected by~~ the latter requiring `density`
- Placement in the `overmap_terrain` entry of a map special, that requires `mondensity` (is it the same as `density`? You tell me!)
- Monster group placement of a `population` in a `radius` (both undocumented, neither mapping to anything intuitive) around an overmap special, this one lets you affect the surrounding overmaps and as such would be a very powerful tool to help differentiate "mini-biomes" around setpieces if it was used more prevalently.

# Steps To Reproduce

1. Try to go off-script and not just copy existing maps when doing your cool mapgen
2. Get ERRORed back to the stone age
3. Enjoy the puzzle of fiddling with the fields/numbers/syntax until you please the mapgen gods 

# Expected behavior

Documentation explaining the tools of mapgen in a way that allows one to use them to their full extent without resorting to too much trial and error - yes, mapgen.md mentions that `mondensity` affects the density of mobs, overmap.md helpfully adds that it's summed with the value of surrounding tiles to affect the density of mob spawns, but they're both silent on *how* and *why* it should be used.

**Comment by jbytheway** [comment]
I totally agree that documentation should be better. I don't really know much about monster placement in particular; I've just tried to improve the code without changing existing behaviour.

When it comes to the possibility of improving the syntax, mapgen is one of those areas where it's hard to know how important it is to maintain backwards compatibility for third party mods. If we were going to make breaking changes, then just after a stable release is probably the best time to do so.

**Comment by Venera3** [comment]
I think having redundant ways to do a thing isn't inherently bad, but if the differences aren't clear than it becomes very unwieldy. I'll whip up some comparison screenshots to illustrate the weird differences later today.

**Comment by Venera3** [comment]
I'll keep a catalogue of peculiarities here as I discover them, if this gets comprehensive enough it can serve as a starting point:

- Both `monsters` and `place_monsters` accept monster groups, but they have to be declared by `monster:` and as such are influenced by density even though the array starts complaining if you define it in there.
- `monster` and `place_monster` accept `group:`, in this case all spawns spawn one entry from the mongroup regardless of density
- `radius` seems to be a random range of submaps (ie increasing it by 2 results in one OMT larger radius), doesn't accept more than one monster group and is influenced by the other monster populations. The population value continues to be a bit of a mystery, as is the question if it's influenced by the densities of the OMTs

**Comment by actual-nh** [comment]
As per #48161, an additional oddity being requiring `"chance": 100` even if there's only one group spawning.
