### ISSUE TITLE
Using the firearm repair kit to cut metal uses the battery

### ISSUE THREAD

**Issue by SilverTemper** [CleverRaven/Cataclysm-DDA#47941]
# Describe the bug

Using the firearm repair kit to cut metal uses the battery.  Considering the reason the kit can cut metal is that it contains a hacksaw, there's no reason for the battery to be depleted.

# Steps To Reproduce

1. Use the firearm repair kit to cut metal
2. ???
3. Debt

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 7
- Game Version: 0.E-9945-g5960368 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    MST Extra [MST_Extra],
    Space Heater [space_heater],
    Alternative Map Key [alt_map_key],
    Mining Mod [Mining_Mod],
    Mythical Martial Arts [MMA],
    NPC Recruitment Options [recruitment_options],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    No Fungal Monsters [No_Fungi],
    Faster Stamina Regen [stamina_regen_buff],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Queju Motor [queju_motor],
    Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mining Mod - UndeadPeople Tileset [Mining_ModUDP],
    MST Extra - UndeadPeople Tileset [MST_ExtraUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP],
    Useful Helicopters [useful_helicopters]
]

**Comment by wapcaplet** [comment]
Thanks for reporting. This looks the same as an older issue #30137
