### ISSUE TITLE
Unable to take off with helicopter from wizards retreat

### ISSUE THREAD

**Issue by ProvoGo** [CleverRaven/Cataclysm-DDA#47947]
# Describe the bug

Unable to take off with a 2-seater helicopter from a wizards retreat tower after landing on it.

# Steps To Reproduce

1. Get a 2-seater helicopter.
2. Land on a wizards retreat tower.
3. Unable to take off again

# Expected behavior

If i'm able to land without problems i should also be able to take off again.

# Screenshots

![Heli won't go up](https://user-images.githubusercontent.com/36768970/110373351-b1e0bf00-804f-11eb-97d4-f4ad413822c3.PNG)

Normal game heli i landed on the tower

![Heli won't go up 2](https://user-images.githubusercontent.com/36768970/110373617-fa987800-804f-11eb-80ab-72123af84544.PNG)

Heli i debug spawned on the roof

# Versions and configuration

 - OS: Windows 7
 - Game Version: 0.E-9956-gf6f104a
 - Graphics version: Tiles
 - Ingame language: English

 ** Mods loaded ** 
 
 - Core content packs: Dark Days Ahead [dda]   -   Bionic Professions [package_bionic_professions]  
    Magiclysm [magiclysm]   -   Aftershock [aftershock]

 - Graphical mods:  Magiclysm - UndeadPeople Tileset [MagiclysmUDP]   -   Aftershock - UndeadPeople Tileset [AftershockUDP]

 - Rebalancing mod: Disable NPC Needs [no_npc_food]   -   Useful Helicopters [useful_helicopters]
   Stats Through Kills [stats_through_kills]

 

# Additional context

**Comment by Termineitor244** [comment]
This could be the same problem that was solved in #48126 for the lighthouses, so maybe a similar solution could help here too

**Comment by hexagonrecursion** [comment]
Confirmed 
- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: cb86201 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]
]

**Comment by Night-Pryanik** [comment]
Can't confirm on latest experimental as of 15 November 2024.
