### ISSUE TITLE
[Magiclysm] Biotek u-dodge activates without any (obvious)triggers

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#47945]
# Describe the bug

Well, it does. In some circumstances, that is.

# Steps To Reproduce

In attached save, lower speed to 6-12 km/h and proceed up the bridge. You will eventually (usually in less than 20 turns) get dismounted from the vehicle via automatic UD proc(even if UD CBM is disabled, that's why my bet is on biotek being the culprit) while there is literally nothing around you, leading to the "tried to unboard not-found vehicle" debug message and all the fun of hoping that your vehicle does not decide to powerslide from the bridge into the water.

# Expected behavior

UD only working when you actually need to dodge, not just because the attunement decides to do it for the lulz.

# Versions and configuration

- OS: Windows 7x64
- Game Version: 0.E-9955-g425255a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills],
    Bionic Professions [package_bionic_professions],
    Ye olde Aftershock vehicle parts [afs_veh_goodies]
]

# Additional context

[save](https://drive.google.com/file/d/1VzrvV8ilDtkuJiuDhztpa3Gd1qreKdt1/view?usp=sharing)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6102135/debug.log)

The thing is, it doesn't happen just anywhere. First time it started happening in amigara horrors cave - *before* summoning them, even before I got to the final -6th level. I think it started either on -3 or on -4. It did not stop after dealing with horrors but it did stop at level -2 and up to 0. It never happened on level 0, as long as I can say. But enter the very first bridge after getting the attunement and not 10 turns after, bam, suddenly my ass is on the driveway and my scouter is running away from me.

ping: @KorGgenT

**Comment by actual-nh** [comment]
When in this sequence of events did you get the attunement? Prior to the cave?

**Comment by GGgatherer** [comment]
Yes, I got the attunement then noticed a mine nearby. Went into it, and at level -3 or -4 uncalled-for activations began. *Before* I even entered the final level.

**Comment by GGgatherer** [comment]
Upd:  I've caught the bastard with a debug, and it seems the problem isn't with magiclysm specifically or even UD. Looks more like z-levels to me.

What's going on:
`23:26:52.281 ERROR GAME : UD call from mattack::stretch_attack, monster name: huge dragonfly naiad`

It's always stretch attacks. Checking game state shows all 3 DFNs are on z-level 0, one is near my character on the XY plane. The thing is, my char is walking on the bridge(so, z-level 1), 3 or 4 tiles from the edge of it. BTW, `z->sees( *target )` is always `true`. Somehow.

The thing is, the fact that I'm not seeing anything in-game except standard UD (in-game)log message means that this check
~~~~
    for( auto &pnt : here.find_clear_path( z->pos(), target->pos() ) ) {
        if( here.impassable( pnt ) ) {
            target->add_msg_player_or_npc( _( "The %1$s thrusts its arm at you, but bounces off the %2$s." ),
                                           _( "The %1$s thrusts its arm at <npcname>, but bounces off the %2$s." ),
                                           z->name(), here.obstacle_name( pnt ) );
            return true;
        }
    }
~~~~
results in path being considered traversable. Maybe it should also check actual length of the path, and/or if it is traversable in more or less straight line?

And while we're at it, what is that:
~~~~
if( dodge_check( z, target ) || get_player_character().uncanny_dodge() ) {
        target->add_msg_player_or_npc( msg_type, _( "You evade the stretched arm and it sails past you!" ),
                                       _( "<npcname> evades the stretched arm!" ) );
~~~~
We first check that *player_character* have UD, then add a message to the target which can possibly *not* be a player character?

**Comment by actual-nh** [comment]
I would actually split it into two: one (this one renamed) about being hit despite no accessible path, one about the likely UD problem.

**Comment by GGgatherer** [comment]
Separated.
