### ISSUE TITLE
Air filtration CBM doesn't help against toxic gas

### ISSUE THREAD

**Issue by ChewedGum** [CleverRaven/Cataclysm-DDA#47957]
# Describe the bug

After installing Air Filter CBM despite it's description it does not filter toxins from, for example, bloated boomer. It does however help with smokes created by fires.

# Steps To Reproduce

1. Make a player with "Air Filtration System CBM".
2. Spawn bloated boomer.
3. Hug him before he explodes into a toxic cloud.
4. Get poisoned.

# Expected behavior

Steps 1 to 3 from above, but don't get poisoned on step 4.
Because CBM description clearly states "it will try to prevent toxins if they enter windpipe".

# Screenshots

# Versions and configuration

 - OS: Windows 10.
 - Game Version: 0.E-9956-gf6f104a
 - Graphics version: Undead
 - Ingame language: English.
 - Mods loaded: 
 -->Disable NPC needs.

**Comment by lifearoundfreaks** [comment]
From [cddawiki](https://cddawiki.chezzo.com/cdda_wiki/index.php?title=Air_Filtration_System):

> If your environment protection of mouth is lower than 5, this bionics will add additional two points of environment protection up to total of 5.
> Two additional points of protection is only minor protection. Don't assume it will fully protect you.

I'm guessing that it is supposed to work like that. So you should either ask for it to be buffed or request a more detailed bionic function description.

**Comment by actual-nh** [comment]
> From [cddawiki](https://cddawiki.chezzo.com/cdda_wiki/index.php?title=Air_Filtration_System):
> 
> > If your environment protection of mouth is lower than 5, this bionics will add additional two points of environment protection up to total of 5.
> > Two additional points of protection is only minor protection. Don't assume it will fully protect you.
> 
> I'm guessing that it is supposed to work like that. So you should either ask for it to be buffed or request a more detailed bionic function description.

Or, IIRC, more fine-tuning of how environmental protection works (e.g., enabling partial protection).

**Comment by ChewedGum** [comment]
> From [cddawiki](https://cddawiki.chezzo.com/cdda_wiki/index.php?title=Air_Filtration_System):
> 
> > If your environment protection of mouth is lower than 5, this bionics will add additional two points of environment protection up to total of 5.
> > Two additional points of protection is only minor protection. Don't assume it will fully protect you.
> 
> I'm guessing that it is supposed to work like that. So you should either ask for it to be buffed or request a more detailed bionic function description.

Thanks i guess but the thing is it says IN THE GAME that "it will try to remove toxins". If by "trying" it means "does absolutely nothing" then that's some misleading description i would dare to say.

**Comment by wapcaplet** [comment]
I have no opinion on whether the CBM should be changed, but for context and history I wanted to reference #32939 which gave it better environmental protection in response to #30012. The current protection of 7 is equivalent to wearing a filter mask.

**Comment by actual-nh** [comment]
Stating in the description that it is equal in protection to a filter mask would seem advisable as a PR (going in after 0.F, however).
