### ISSUE TITLE
Earthshaper becomes Technomancer by installing Crystallized Mana Nose CBM

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#47965]
# Describe the bug

When a character has the Earthshaper trait (and is locked out of the Technomancer class), they can become a Technomancer simply by installing the Crystallized Mana Nose CBM.

# Steps To Reproduce

1. Learn an Earthshaper spell, and accept the prompt to become locked out of Technomancer class
2. Get a Crystallized Mana Nose CBM and some anesthetic
3. Find or map-edit in an Autodoc and couch
4. Use the autodoc to install the CBM, and accept the prompt to lose the Earthshaper trait

# Expected behavior

Converting from Earthshaper to Technomancer should not be possible.

If the character has the Earthshaper class already, they should not be able to attempt a Technomancer CBM installation at all.

# Screenshots

Prompt warns that Earthshaper trait will be removed, but no mention that Technomancer will be forced upon them:

![image](https://user-images.githubusercontent.com/238395/110557079-1148d880-80fd-11eb-885b-fa290a81ac8f.png)

Message log shows Earthshaper spells being forgotten, and class changing:

![image](https://user-images.githubusercontent.com/238395/110556948-c9c24c80-80fc-11eb-846b-b5c6a832af8a.png)

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-9956-gf6f104a441-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]
]

# Additional context

Found by Ungen on Discord

**Comment by anothersimulacrum** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/47822 probably does what this wants.

**Comment by Maleclypse** [comment]
Can this be closed or does someone need to make some changes using json from #47822 to finalize this?

**Comment by wapcaplet** [comment]
Stil reproducible. Changing "canceled_mutations" to "mutation_conflicts" for the CBM, per the linked PR, does prevent installing the Nose CBM:

![image](https://user-images.githubusercontent.com/238395/147479242-8e8b2eb7-191d-4d2d-a597-6c38a54035ff.png)


- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-4600-gb5228cfae9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]
]
