### ISSUE TITLE
[Documentation] pre_special not documented

### ISSUE THREAD

**Issue by OromisElf** [CleverRaven/Cataclysm-DDA#47961]
# Describe the bug

"pre_special" is not documented in json_info. I saw it used in construction.json and just now wondered what the possible specials were.

**Comment by jtgibson01** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/5cc608ccea74ba783c2f1569fafdbc2b9caf0021/src/construction.cpp#L1618-L1629

https://github.com/CleverRaven/Cataclysm-DDA/blob/5cc608ccea74ba783c2f1569fafdbc2b9caf0021/src/construction.cpp#L106-L114

    "pre_special": "check_empty" //Tile is empty
    "pre_special": "check_support" //Must have at least two solid walls/obstructions nearby to support the tile
    "pre_special": "check_deconstruction" //The furniture (or tile, if no furniture) in the target tile must have a "deconstruct" entry
    "pre_special": "check_empty_up_OK" //Tile is empty and is below the maximum possible elevation (can build up here)
    "pre_special": "check_up_OK" //Tile is below the maximum possible elevation (can build up here)
    "pre_special": "check_down_OK" //Tile is above the lowest possible elevation (can dig down here)
    "pre_special": "check_no_trap" //There is no trap object in this tile
    "pre_special": "check_ramp_low" //Both this and the next level above can be built up one additional Z level
    "pre_special": "check_ramp_high" //There is a complete downramp on the next higher level, and both this and next level above can be built up one additional Z level

https://github.com/CleverRaven/Cataclysm-DDA/blob/5cc608ccea74ba783c2f1569fafdbc2b9caf0021/src/construction.cpp#L1166-L1182

Unless the game wants to maintain a solid sky layer without allowing construction in it, those ramp pre-specials actually seem to have incorrect behaviour; a ramp only needs to check if it's OK to build up from the current tripoint, not the next one up.  The ramps just affect the current level and the next level up, so theoretically it should be perfectly OK to build on that Z level even if it's the highest map level.  I'd be impressed if any player will ever build a tower high enough to run into this behaviour, though.
