### ISSUE TITLE
Modable surrounded start

### ISSUE THREAD

**Issue by LyleSY** [CleverRaven/Cataclysm-DDA#47971]
# Is your feature request related to a problem? Please describe.
Surrounded start is a great feature but it can get old. Allowing it to pull from a modable spawn list would be super fun

# Describe the solution you'd like
A JSON list of surrounded start options that players can pick from at game start that can be modded

# Describe alternatives you've considered
Just add stuff to the vanilla zombie list that surrounded start pulls from

**Comment by ZhilkinSerg** [comment]
Do you mean monster list?

**Comment by actual-nh** [comment]
This will be quite needed for Aftershock's further development, I would think.
