### ISSUE TITLE
long range projectiles cause bled is way too often.

### ISSUE THREAD

**Issue by vipches** [CleverRaven/Cataclysm-DDA#47979]
So, I know the projectile from long range weapon can cause bled for now, but somehow it just dosn't feel right,

such as, the stone should not has that much power to cause you bled to dead, it just dosn't feel right, stone a suppost to be a blunt projectile, even it can cause bled it shouldn't as efficiency as than bullets,

also, I just got shot by the riot turret, and getting bled too, why? wasn't the riot turret suppost to useing non-lethal bullet in order to prevent killing people?

projectile stystem are completely mass up right now, we gonna need to add some new stystem in order to differentiate the type for the projectiles, I just can't stop getting bleed out in a god damn secs.

I don't mean disrespect, but If we wanna make the game more realistic, We can at least acting like it.

**Comment by PatrikLundell** [comment]
If you read the description of the riot turret, you'll see that it was SUPPOSED to be non lethal, but...

The main way to prevent bleeding from getting shot at is to keep away from things that fire bullets at you (or using other methods to prevent them from firing at you). The secondary method is to wear armor with bullet protection and hope you're not shot at the body parts that are less well protected, while making sure you carry means to staunch bleeding in case hope wasn't enough.

**Comment by vipches** [comment]
I was talking about how the game suppost to getting realistic as it should be, not about how the game play does, That's not the point, you know, I know you all wanna make this game looking more realistic like real life, but the truth is, it's really has nothing to do with it, not at all, in the real life, you won't getting bleed out just because some people threw a rocks at you, even it kills you, it still not getting too many blood loss.

**Comment by GGgatherer** [comment]
> in the real life, you won't getting bleed out just because some people threw a rocks at you

Depends on amount, mass and speed of those rocks. Especially if you don't have ways to stop bleeding - the game is already skirting the edges of realism in that case by allowing you to just hold wound with your fingers for measly several seconds thus making them stop bleeding.

> If you read the description of the riot turret, you'll see that it was SUPPOSED to be non lethal, but...

Statistically non-lethal: as long as official percentage of lethal cases are under set threshold (and don't you worry, citizen, our scientists worked hard *\*cough\*through dozens of test subjects\*cough\** to establish those numbers), you can truthfully say it is technically non-lethal.

**Comment by actual-nh** [comment]
> > in the real life, you won't getting bleed out just because some people threw a rocks at you
> 
> Depends on amount, mass and speed of those rocks. Especially if you don't have ways to stop bleeding - the game is already skirting the edges of realism in that case by allowing you to just hold wound with your fingers for measly several seconds thus making them stop bleeding.

Blunt objects that do cause bleeding actually tend to be rather worse than non-blunt ones doing so - try internal bleeding...  Making them cause bleeding more, but not internal bleeding, seems to me a reasonable compromise.

**Comment by Fosheze** [comment]
> > > in the real life, you won't getting bleed out just because some people threw a rocks at you
> > 
> > 
> > Depends on amount, mass and speed of those rocks. Especially if you don't have ways to stop bleeding - the game is already skirting the edges of realism in that case by allowing you to just hold wound with your fingers for measly several seconds thus making them stop bleeding.
> 
> Blunt objects that do cause bleeding actually tend to be rather worse than non-blunt ones doing so - try internal bleeding... Making them cause bleeding more, but not internal bleeding, seems to me a reasonable compromise.

There's also the fact wounds dealt by dull objects don't heal nearly as well as a nice clean cut. There's a reason that the BSA teaches people that a dull knife is a dangerous knife. A nice sharp cut seals up incredibly quickly where a dull torn wound can take forever to heal and even then often leaves a scar. Non-uniform wounds are also much more difficult to properly dress.

**Comment by vipches** [comment]
Alright, so, what we gonna do about this? Does it need to getting changed or stay that way?

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
