### ISSUE TITLE
NPCs at a faction camp can spend all day stuck inside a single room yelling at each other to move

### ISSUE THREAD

**Issue by Sinanzee** [CleverRaven/Cataclysm-DDA#47976]
NPCs will spend all day stuck inside a single room yelling at each other to move as shown in the photo below. This behavior is ongoing at all times of the day whenever these npcs are not doing other jobs. This causes basic work, consumption, or sleep around the faction base (or otherwise within earshot) to be impossible for the player without earplugs due to constant interruptions/notifications on hearing someone else saying something.

Cause: This is of course conjecture and is based purely on my own assumptions. I am totally willing to upload a save file if someone can direct me to the preferred procedure for doing so. Either way, this behavior began as soon as a large number of NPCs were assigned to a faction camp all at once at a time when I only had two beds at the faction camp in question (At the time I didn't quite understand faction camps). Curiously, they all seem assigned to the same BED, not just the same room. This behavior will persist no matter how I try to 'reset' them. I've attempted ordering them to follow me then assigning them back to the camp, which resumes this behavior as soon as I do so. I've attempted saying to them I want to split up, having them leave, then persuading them to be my npc again and assigning them back to this camp with the exact same behavior resuming. I've assigned zones not to investigate noise, altered their npc behavior to not close doors, and have done everything listed in the comments of the following reddit post to fix this issue all to no avail. 

https://www.reddit.com/r/cataclysmdda/comments/m04d30/possible_bug_after_assigning_faction_workers_to/

Oddly enough it does not seem to affect new npcs assigned to the faction camp as those npcs will pick different beds and function as intended. This would suggest a potential fix for me specifically whereby I abandon all the npcs that are bugging out and just get new ones, but doing so would mean abandoning work I put into leveling their skills up and is a gameplay decision I would make purely for the sake of circumventing unintended npc behavior. Also improving the game by filing a bug report is far preferable to quietly fixing the game for myself and then moving on.

![glitch 2](https://user-images.githubusercontent.com/30304267/110723032-64945700-81e1-11eb-8115-8f139135ebf0.PNG)

![glitch](https://user-images.githubusercontent.com/30304267/110721602-de771100-81de-11eb-881e-6acc1e99fa64.PNG)

![glitch 3](https://user-images.githubusercontent.com/30304267/110724742-5dbb1380-81e4-11eb-9fe5-d4d08abdbcf6.PNG)

Solutions: I have very limited coding experience and as such these proposals are based purely on my own intuitions as to what's going on, and are not valued in terms of how much effort they would take or what the easiest workaround would be. Please take my suggestions with an enormous amount of salt. That being said, it seems to me the easiest way to fix this behavior would be one of the following, which I previously mentioned in the above reddit post:

1) A system by which the player manually reassigns workers to whichever room they want, although the potential value of coding this when it's a pure aesthetic choice with no mechanical value is dubious. However, this option might have more value as npcs increase in complexity/uniqueness. Imagining a future in which npcs decorate the rooms they choose to live in on a faction camp would definitely incentivize me assigning the pretty rooms closer to mine or w.e. Yet as of now, it seems like it would be a fair amount of work without a lot of mechanical value.

2) That being said, an 'unseen' fix that would require no player input could be that reassigning workers to a faction camp or telling them to work on it has them automatically run a check whereby they 'repick' which bed is theirs at the moment of their reassignment. Though this would pose a challenge in players having to hunt down their preferred npc whenever they need to talk to them as they would ostensibly be changing rooms whenever the player drafts one of them to go into town on a raid or something.

It seems to me most of the issue comes from NPCs being very rigid in terms of which room is theirs, and the fact that once set there doesn't seem to be a way for them to change or reassign which room is theirs. Or even just the fact that once rooms are set NPCs never repick which room is theirs and never run checks on whether or not their room in particular is at capacity or has too many people assigned to it.

**Comment by PatrikLundell** [comment]
Based on the description alone (I've never assigned my companions to the faction camp except temporarily by mistake), I would suggest some logic that reevaluates bed assignments when new beds are built and when companions are reassigned to the camp. This is basically a variation of alternative 2.

Basically, when a bed is built all beds in the camp are examined to rearrange the assignments such that the load is spread evenly (keeping current assignments when possible). If the game keeps track of bed assignments for companions that are not assigned to the camp currently (but not dead), those assignments should have a lower priority than assignments to companions present, and thus be the ones most likely to be shifted around. This should also result in the absent companion assignments being smeared out over the ones present when multiple assignments are necessary.
When a companion is (re)assigned to the camp it's assigned to a bed with the least load, with a preference for the bed previously used.

**Comment by MarlossCDDA** [comment]
CDDA takes place in Massachusetts, right? Current behavior seems pretty realistic to me.

**Comment by BrettDong** [comment]
To upload the save, you can compress the folder into a zip archive and drag it to GitHub comment box.

**Comment by Sinanzee** [comment]
The Archived file is 28.3 MB and it looks like github only allows uploading for files up to 10MB large. Either way, here's a link to the file through google. If another format is required I'll be happy to upload it in any way that is preferable. 
https://drive.google.com/file/d/1_JWaCaNcgLT28GgUEJ5h4kWw21b09BDP/view?usp=sharing

**Comment by anothersimulacrum** [comment]
Fixed in https://github.com/CleverRaven/Cataclysm-DDA/pull/51448
If this is incorrect, comment here and I can reopen it.
