### ISSUE TITLE
Flammable arrows dupe on use

### ISSUE THREAD

**Issue by souricelle** [CleverRaven/Cataclysm-DDA#47982]
# Describe the bug

You can't activate a flammable arrow to light it without picking it up. When you do, you drop the arrow and a flaming arrow appears in your hand. The original arrow is not deleted so you get an extra flammable arrow every time you do this.

# Steps To Reproduce

1) Make a character and give them a lighter and a flammable arrow.
2) Activate the flammable arrow.
3) You now have both a flammable arrow and a burning arrow.

# Expected behavior

The flammable arrow should go away and be replaced by the burning arrow.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-9855-gfa9b27e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
]

**Comment by souricelle** [comment]
Possibly related to the issue holding up this PR: https://github.com/CleverRaven/Cataclysm-DDA/pull/45941

**Comment by wapcaplet** [comment]
Confirmed in 0.E-10008-ged4b3c1b04
