### ISSUE TITLE
Monster's stretch_attack can hit through z-levels and around(through?) several tiles of walkable terrain

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#47980]
# Describe the bug

If you're at z-level N, and there's a monster nearby (XY-wise) at z-level N-1, that monster can attack you with stretch_attack even if there is no straight(ish) line of attack.

# Steps To Reproduce

load the [save](https://drive.google.com/file/d/1VzrvV8ilDtkuJiuDhztpa3Gd1qreKdt1/view?usp=sharing), walk around or slightly to the east, see uncanny dodge proc because of `huge dragonfly naiad` attacking you from below despite there being 3 or 4 tiles of a bridge its attack have to go around. More info here https://github.com/CleverRaven/Cataclysm-DDA/issues/47945#issuecomment-795712539

# Expected behavior

either find_clear_path should only work at same z-level, or there should be another function find_clear_and_somewhat_straightish_path for the purposes of deciding if stretch_attack can hit. Also, the length of the path should be a limiting factor: there's a check of straight (sqrt(x2+y2+z2)) distance here
~~~~
    if( distance < 2 || distance > 3 || !z->sees( *target ) ) {
        return false;
    }
~~~~
but the "straight" path is either calculated straight through the bridge pavement or is way longer than that.

# Versions and configuration

    OS: Windows 7x64
    Game Version: 0.E-9955-g425255a [64-bit]
    Graphics Version: Tiles
    Game Language: English [en]
    Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills],
    Bionic Professions [package_bionic_professions],
    Ye olde Aftershock vehicle parts [afs_veh_goodies]
    ]

# Additional context

`stretch_bite` and `longswipe` use almost the same code, probably should be checked too.

**Comment by Venera3** [comment]
In case somebody tackles the targeting, I can offer the biggest rocket emoji if these all could get moved over to the generic monster special attack system.

**Comment by actual-nh** [comment]
@GGgatherer: Did you have fov_3d on?

**Comment by GGgatherer** [comment]
3dfov off, no debug mode

**Comment by actual-nh** [comment]
> 3dfov off, no debug mode

Odd, since it does check `sees`. We are currently discussing this in #48245.

**Comment by actual-nh** [comment]
At the time, was your character able to identify it as a huge dragonfly nymph, or is that from debugging?

**Comment by GGgatherer** [comment]
Debugging (as in recompiled with added debug messages). In game log there were only standard UD "time slows down and you evade" messages.

**Comment by actual-nh** [comment]
Is this build #11556 or later?

**Comment by GGgatherer** [comment]
11552. 11556 isn't even visible to CDDA launcher at the moment.
