### ISSUE TITLE
Too many bone skewers from bones, cumbersome to deal with.

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#47983]
# Is your feature request related to a problem? Please describe.

We get way to many bone skewers from bones.  A single bone, .25L, .23kg, 6cm makes 22 Bone Skewers, .22kG, .56L, with 10 grams lost?  I just killed a skeletal zombie, and got ~300 bones, I think.  I can guess, because after I cut up everything in the pile, I ended up with 6587 bone skewers.

Every google image I look at for bone skewer shows something that might be only 3 or 4 skewers, max, from a single thigh bone.

More importantly, I don't like getting 6k+ bone skewers when I cut up a stack of items, and end up with overfilled squares because of too many items.

Yeah, each bone skewer counts as it's own item.  This can cause slowdowns when crafting, accessing inventory, general lag, due to the shear quantity of them.  They also don't burn, so there's really no easy way to get rid of them.  No recipe takes more than 20, and that one takes 120 minutes to accomplish.

Say, you want to bury them in a pit, to get rid of them?  Great.  Remember, since they are all individual items, to pick up a tile's worth (4096) will take over an hour.  100 move actions to pick up each skewer, yay!  Also, more than an hour to drop as well, given pocket access times.
Dragging them on the floor will also take significant time, in the real world.  5 seconds per tile, and about 25 minutes in game.

Never mind, when you fill in a pit that has them inside the pit, they get moved out of the pit.  Great.  Awesome.

Getting a vehicle to drive over them just to get rid of them seems kind of like a horrible solution to a horrible problem, and also requires a vehicle.

# Describe the solution you'd like
I'd like to be able to get rid of them, _somehow_.
Even bone broth would be acceptable, as each bone broth would use up ~220 of them.  Bone meal would be fine too.  These run into the toxins or parasites issue, though, if they don't come from an animal.

Looking into it, there's a meal_bone_tainted, that leads into meal_bone_any.  Grinding them up into tainted bone meal wouldn't be the worst thing, I think?  meal_bone_any isn't used in too many places, and that kinda pushes the issue back, but it's a step forward.

A way for them to stack would be nice as well.  I accidentally 'B' -> Cut up Everything a stack of garbage near my crafting area, not realizing that there were bones in it.  The lag for crafting and even moving is noticeable.

# Describe alternatives you've considered
Save file editing, a custom recipe mod that just makes them go poof into the ether.

Burning them away with large enough fires would be what I'd prefer, however I don't think they should be able to burn on their own, as bones don't.

Maybe a recipe that allows them to be crafted into 'scrap bone', that can be used as a replacement for regular bone in places where you don't need the physical properties of the bone item?  Chems?

Could they be made to decay, perhaps?  Bone doesn't last forever in the real world, especially when broken into 10gram, 3cm long pieces.  Now, given, they do last a long while, but in the favor of removing thousands and thousands of useless items from the game, they could go away a little faster.

# Additional context
Version:
0.E-10003-g48f45e8 (tiles)
Build 11519

**Comment by Fosheze** [comment]
>Burning them away with large enough fires would be what I'd prefer, however I don't think they should be able to burn on their own, as bones don't.

They do burn they just don't have a fuel value so they can't keep a fire going on their own. My goto for stuff I want to get rid of is to dump a gallon of some sort of fuel (gas, diesel, JP8, Oil, etc.) on the ground then to stack a bunch of whatever I want to get rid of on the square and light it up. One gallon of fuel is enough to more than burn up basically anything that burns.

>Maybe a recipe that allows them to be crafted into 'scrap bone', that can be used as a replacement for regular bone in places where you don't need the physical properties of the bone item? Chems?

As it is bone skewers are the "scrap bone" item. There isn't anything smaller to turn them into. They could use some additional uses though like you said. I could see them being added as an alternative ingredient for bonemeal.

**Comment by Zireael07** [comment]
> I could see them being added as an alternative ingredient for bonemeal.

:+1:

**Comment by chrispikula** [comment]
> They do burn they just don't have a fuel value so they can't keep a fire going on their own. My goto for stuff I want to get rid of is to dump a gallon of some sort of fuel (gas, diesel, JP8, Oil, etc.) on the ground then to stack a bunch of whatever I want to get rid of on the square and light it up. One gallon of fuel is enough to more than burn up basically anything that burns.

In that case, maybe they aren't burnable enough?  There are always thousands left when I drag some of them into a pile with corpse refuse and other scrap, and set that alight.  Is it checking to see if it can burn a single item at a each tick, and since there are _so many_ of them, almost none go away?  I haven't looked at the burning code.

**Comment by Fosheze** [comment]
> > They do burn they just don't have a fuel value so they can't keep a fire going on their own. My goto for stuff I want to get rid of is to dump a gallon of some sort of fuel (gas, diesel, JP8, Oil, etc.) on the ground then to stack a bunch of whatever I want to get rid of on the square and light it up. One gallon of fuel is enough to more than burn up basically anything that burns.
> 
> In that case, maybe they aren't burnable enough? There are always thousands left when I drag some of them into a pile with corpse refuse and other scrap, and set that alight. Is it checking to see if it can burn a single item at a each tick, and since there are _so many_ of them, almost none go away? I haven't looked at the burning code.

Everything with the bone material shares the same burnability (see below code). I'm not entirely sure how the fire code works myself but it was redone fairly recently and I've found that most things don't burn as well as they did. Corpses and associated clothing in particular barely seem to burn at all now. Being able to fuel braziers with corpses was kind of ridiculous anyways. If you want anything to burn up now you really need to use a decent amount of liquid fuel or a nice big wood fire. From what I have seen elsewhere everything in the pile should burn at once. While bone burns, it really doesn't burn well.

It does look like the charcoal kiln only looks for the bone material rather than the bone item, so if you wanted you could shovel them all into a charcoal kiln and get useful charcoal out of the whole venture.

https://github.com/CleverRaven/Cataclysm-DDA/blob/5a0df98b8ffa4b747d275c74769e74cb9547bfbd/data/json/materials.json#L158-L186

**Comment by chrispikula** [comment]
> It does look like the charcoal kiln only looks for the bone material rather than the bone item, so if you wanted you could shovel them all into a charcoal kiln and get useful charcoal out of the whole venture.

That was suggested to me on discord as well, I didn't know, (before), that charcoal kiln's were considered a higher level of burning.  That is a work around, which is nice, but still leaves with the problem of it taking multiple in-game hours to move these things around.  C'est la vie.

**Comment by Fosheze** [comment]
> > It does look like the charcoal kiln only looks for the bone material rather than the bone item, so if you wanted you could shovel them all into a charcoal kiln and get useful charcoal out of the whole venture.
> 
> That was suggested to me on discord as well, I didn't know, (before), that charcoal kiln's were considered a higher level of burning. That is a work around, which is nice, but still leaves with the problem of it taking multiple in-game hours to move these things around. C'est la vie.

Yeah hauling a lot of items like that is a pain. That's what I keep body bags around for. Fill the body bag with the items you want to move and then you only have a few items to move instead of thousands.

**Comment by chrispikula** [comment]
> > > It does look like the charcoal kiln only looks for the bone material rather than the bone item, so if you wanted you could shovel them all into a charcoal kiln and get useful charcoal out of the whole venture.
> > 
> > 
> > That was suggested to me on discord as well, I didn't know, (before), that charcoal kiln's were considered a higher level of burning. That is a work around, which is nice, but still leaves with the problem of it taking multiple in-game hours to move these things around. C'est la vie.
> 
> Yeah hauling a lot of items like that is a pain. That's what I keep body bags around for. Fill the body bag with the items you want to move and then you only have a few items to move instead of thousands.

Exactly.  It takes an insert action to put each bone skewer into the pocket.  And a remove action if you want to take them out of the pocket, and not just get rid of your container.  A significantly long time in total.

**Comment by actual-nh** [comment]
The basic problem is that the recipe is producing too many of them:

- Long bones that are long enough to produce a reasonable skewer make up ~42% of the human skeleton (see [this free article](https://www.researchgate.net/publication/227604939_Bone_Weight_New_Reference_Values_Based_on_a_Modern_Portuguese_Identified_Skeletal_Collection) - the 6 cm figure above is from the standard guess at length, not the real length needed (unless you really want to burn your hands using it as a skewer...).
- The type needed to be made into a skewer is compact bone, which makes up about 80% of the (adult human) skeleton. (Lots and lots of sources - just google "compact bone" and "percentage".) So at most 0.42*0.8 -> 33.6% of the skeleton's mass could be used.
- According to [this master's thesis](https://digitalcommons.calpoly.edu/cgi/viewcontent.cgi?article=1348&context=theses), compact bone has a density of 1.86 g per cubic cm. Trabecular (spongy) bone density ranges from 0.2-0.6 gram per cubic cm; will use 0.6 given soft tissue (marrow) between trabeculae at roughly 1 g per cubic cm.
- Long bones themselves are not, by any means, entirely made of compact bone, the type you could get a skewer from. The limiting factor would be the percentage compact bone in the shaft (diaphysis) - which has the least compact bone (only the outer layer). From [this free article](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0166095) and others (including personal observation - teaching Anatomy & Physiology), roughly 60% of the bone's length is diaphysis. (The ends - epiphyses (possibly not the right plural) - might be usable to extend the length of the skewer, but it would be more difficult than simply cutting off the ends then splitting the shaft; it's an autolearned recipe with no difficulty.) Not taking into account that the ends are wider, nor that less of them are compact bone (see below), that limits it to .336 * 0.6 -> ~20%.
- Of long bone diaphysis in hum+ size animals, [this table](https://link.springer.com/article/10.1007/s00435-021-00516-6/tables/1) is indicating ~64% of the area that's compact bone is about the maximum likely to be seen (cow femurs). 0.64*1.86 + 0.36*0.6 = ~1.19 + ~0.22 = 1.41 g per cubic cm as overall density, meaning 1.41/1.86 -> ~76% of the shaft is cortical bone by weight. 0.2 * 0.76 -> ~15%.

So, at the very most, ~15% of that bone should be convertable into bone skewers. .23 kg of sturdy bone -> ~0.035 kg of skewers (plus the rest in some variety of scraps), which would be exactly that - averaging 3-4 skewers.

**Comment by actual-nh** [comment]
Regarding the remainder of the bone - 0.046 kg of bone meal is one reasonable byproduct (spongy bone).

**Comment by chrispikula** [comment]
> 
> 
> Regarding the remainder of the bone - 0.046 kg of bone meal is one reasonable byproduct (spongy bone).

Since bone meal is fairly time and  labour intensive to make directly, would this mean that we should also change the amount of time to make skewers and to cut up bones?

**Comment by actual-nh** [comment]
> > Regarding the remainder of the bone - 0.046 kg of bone meal is one reasonable byproduct (spongy bone).
> 
> Since bone meal is fairly time and labour intensive to make directly, would this mean that we should also change the amount of time to make skewers and to cut up bones?

That really depends on what we're talking about in terms of bone meal. Bone meal with a lot of marrow mixed in, or just bone meal. About 20% of the mass of bones, at least of the non-marrow part, is spongy bone, which will very easily be crunched into bone meal.

**Comment by chrispikula** [comment]
I'm currently trying to find where it's actually defined how many bone_skewers you get from cutting up bones, and I can't actually find it?
There's a recipe for a bone skewer, that makes a single one from a single sturdy bone.  It's in the recipe menu.  

The only other place I can find is that bone becomes skewers is the property, under the bone material:
"salvaged_into": "skewer_bone",
which doesn't seem to have any ability to result in multiple products, or fractional output.

**Comment by actual-nh** [comment]
I was looking around myself. (The recipe should probably be fixed to generate 4 bone skewers - not that it's currently very clear how to do that - plus leftovers.)

salvaged_into, from materials.cpp, indeed does not seem capable of being more than one thing. I am thinking that the best solution would be something like "bone_scraps", with a weight of something like 67 g. You could do most things you could do with bone_sturdy, but not make skewers or other things requiring a significant length of bone. Due to string freeze, this would have to go into 0.F-dev, not the master branch.

Regarding cleaning crude bone meal from bone marrow - boiling it then filtering should do, and get you bone broth as a side product. Very little crunching would be needed to get you bone meal from that - it'd be more of a task keeping the bone from getting too small to filter out.

So, in 0.F-dev, the added stuff would be:

- bone_scraps (67 g per scrap - that's taking out the bone skewers and the crude_bone_meal - and 2 per bone used in the recipe, or 3 gotten by just busting up bones);
- crude_bone_meal (46 g per bone_sturdy) - coarse bone meal plus bone marrow.

**Comment by Fosheze** [comment]
>I'm currently trying to find where it's actually defined how many bone_skewers you get from cutting up bones, and I can't actually find it?
There's a recipe for a bone skewer, that makes a single one from a single sturdy bone. It's in the recipe menu.

>The only other place I can find is that bone becomes skewers is the property, under the bone material:
"salvaged_into": "skewer_bone",

I believe that salvaged into just uses the scrapped items mass to determine the quantity.

>If we do introduce fewer bone skewers, it also doesn't get rid of the issue of the large number of ones that exist already.

As far as the ones that you have, your current PR is probably fine because the recipes that you added them to won't change even if a different scrap product is added later. Bone needles and other solely bone items could be added to those recipes as well as far as that goes.

Also I agree with actual-nh here. A new byproduct item is really the only way to go here. Skewers will just need to stay in for release.

**Comment by GGgatherer** [comment]
Maybe they should be made stackable? non-stackable items make sense if the game need to track the state of each and every item, which doesn't seem necessary in this case. Moving a stack is a single action so no hours wasted moving them one by one.
