### ISSUE TITLE
Please add more debug setting in the game option, so people can setting game play on it own.

### ISSUE THREAD

**Issue by vipches** [CleverRaven/Cataclysm-DDA#47999]
First, thanks for the hard work on this game so far, it’s feeling very good since year 2008 till now, I understand so far we are trying to make this game looks just like real life, so you can make game harder and challenging, but, as you guys know, not all the DDA players like the game features on the new version,

for example, some people do not like the game are too reality, just crafting are new item to spend about 3 days in order to build a full armors for themselves, or spend like 10 days or even more to build a little log house with the size 9X9 just like a small tent, they want to make the game more amusement, so they can just save some time for some fun,

I mean, not anybody like the game force to fit them into the new game features, And I think that’s the problem for cause so many players quit this wounderful game, it’s really shame, you know,

So, I want to make a suggest, I’m not asking too much, I just wanna the game option can have more debug setting on the menu,
such as you can change a construct speed ,farm speed, the CBMs slots, the weariness switch, stamina switch, and the revive swtich, I mean, we alright have a setting to change the skill learn speed, so why not take one step further, in order to makeing more better game play changer, so people can choose between reality and game play on they own,

you just can’t force the players to play the rules that you has been creation any more, so how about make a change, so you can let the players play the rules on they own, just like the Rimworld, for example.

And I really wish the developer can reference this suggest, so we can make anybody happy, no more quarrel and complain,

for the better future, long live for Cataclysm DDA.

**Comment by mlangsdorf** [comment]
We're not going to add these options to the debug menu. The debug menu is not for customizing the game to your liking; it's for debugging the game.

We might accept a patchset to make some of these options changeable through mods or the normal options menu. There is a cost in debug time and effort to have more options, so whether a patchset to add more configuration options would be accepted would depend on how well the patch is written. 

Alternately, Kevin may decide that the skill learning speed option is a bad idea and remove it.

**Comment by vipches** [comment]
> We're not going to add these options to the debug menu. The debug menu is not for customizing the game to your liking; it's for debugging the game.
> 
> We might accept a patchset to make some of these options changeable through mods or the normal options menu. There is a cost in debug time and effort to have more options, so whether a patchset to add more configuration options would be accepted would depend on how well the patch is written.
> 
> Alternately, Kevin may decide that the skill learning speed option is a bad idea and remove it.

Having you way, sir, have good day

**Comment by kevingranade** [comment]
As Mark says, that's not what the debug menu is for.

A lot of the things you mention are moddable, and a lot more could be. Adjustable scaling factors to most of the game's functionality are going to be acceptable to add but personally I have no interest in adding that sort of thing.

Mods are the interface to expose that sort of thing to players. If an individual player wants to write a tiny mod that adjusts just one of those factors they can easily do so, it's just a small text document.

As for your rationale of attempting to prevent arguments, you should know that's a hopeless endeavor and is not a good reason to make changes. If anything doing so sends a signal that all people have to do is make enough noise to get me to make changes and that's not the case.
