### ISSUE TITLE
Food containers are found full but not sealed

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#47992]
# Describe the bug

Many food and drink items in sealable containers spawn full, but not sealed.

Comestibles include, but are not limited to:
- pickled meat
- pickled veggies
- dark cola
- mineral water
- sauerkraut
- chocolate drink
- pickled fish
- stout
- maple syrup

# Steps To Reproduce

1. Find a house
2. Look for food and drink in completely full containers

# Expected behavior

Any sealable container (jar, bottle, jug, or can) that is completely full of food or drink should be `(sealed)`, because who opens their pickled meats and cola without eating or drinking any?

# Screenshots

Here is a glass jar of pickled veggies, completely full, but indicated as an "open pocket":

![image](https://user-images.githubusercontent.com/238395/110871754-30c23b80-828c-11eb-942c-a2c5e3abe0ad.png)

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-10008-ged4b3c1b04 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

A few foods afflicted by this bug were fixed in #47841, #47623, and #47548 by adding `"sealed": true` to the item JSON.

**Comment by wapcaplet** [comment]
From [doc/ITEM_SPAWN.md](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/ITEM_SPAWN.md):

> `sealed`: If true, a container will be sealed when the item spawns. Default is `true`

So the "sealed" field should not even be needed for these items. Yet there are strange inconsistencies in what items have defined in their JSON, and what actually occurs in game.

I ran around and looted some sample items from fridges. All these foods are in *sealable* containers that spawned *full*:

![image](https://user-images.githubusercontent.com/238395/111017527-6856e380-8371-11eb-8a45-beee9b627fe2.png)

Yet in the JSON for these items, we have:

- `syrup` maple syrup - in `bottle_glass`, sealed undefined (default `true`)
- `veggy_pickled` pickled veggies - in `jar_glass_sealed`, sealed undefined (default `true`)
- `peanutbutter` peanut butter - in `jar_glass_sealed`, sealed undefined (default `true`)
- `sauerkraut` sauerkraut - in `jar_glass_sealed`, sealed undefined (default `true`)
- `water_clean` clean water - in `bottle_plastic`, sealed undefined (default `true`)
- `honey_bottled` forest honey - in `bottle_plastic`, sealed `false`
- `sports_drink` sports drink - in `bottle_plastic`, sealed undefined (default `true`)

Although `sauerkraut` and `peanutbutter` are both in `jar_glass_sealed` and should default to "sealed" being `true`, only the `peanutbutter` actually spawns in a sealed state.

Similarly, though `water_clean` and `sports_drink` are defined with a `bottle_plastic` container, and default to "sealed" being `true`, only the `clean_water` actually spawns sealed.

Worse, I have seen some containers with "sealed" explicitly set to `false` (such as ketchup and mustard) that actually spawn in a sealed condition when they are full.

Surely there is a logical explanation for this madness, but I have not yet discovered it. I would welcome any insight others might provide.

**Comment by actual-nh** [comment]
You may be interested in #46359 (and possibly #46970).

**Comment by Maleclypse** [comment]
I found this `{ "group": "ketchup_sealed_rng", "prob": 10 },` in the itemgroup dining.  which might explain the weird sealed:true/false behaviour.

**Comment by Fosheze** [comment]
> I found this `{ "group": "ketchup_sealed_rng", "prob": 10 },` in the itemgroup dining. which might explain the weird sealed:true/false behaviour.

If I'm understanding this correctly the problem is that when a container randomly rolls it's contents quantity and happens to spawn full rather than being a specifically spawned full container then it will not be sealed. This seems like a bit of a hack but if that is the case then you could change the randomized spawning to only allow spawning an item at a maximum of one unit below full and then add a separate chance to specifically spawn the full container.
