### ISSUE TITLE
Spay/neuter tamed animals

### ISSUE THREAD

**Issue by tsulh** [CleverRaven/Cataclysm-DDA#48008]
# Is your feature request related to a problem? Please describe.
It is frustrating that it is possible to install bionics on self, but not possible to spay/neuter tamed animals. Killing extra animals breaks the atmosphere, especially when playing with Animal Empathy trait.

# Describe the solution you'd like
When interacting with a tamed animal, I'd like a new option to be added. The option would say smth like "Spay/neuter ANIMAL_NAME", and the activity would require a scalpel as a tool and painkillers as consumable. On interaction with a neutered animal, this option would say "This animal is spayed/neutered".

# Describe alternatives you've considered
Currently available alternative solution is to kill extra animals (e.g., by sending them to attack dangerous monsters). However, this breaks the atmosphere, because the character might not want to send offspring of their pets to gruesome death.

# Additional context
I think that this feature is needed (and makes sense) only for non-egg-laying animals.

**Comment by Rivet-the-Zombie** [comment]
>I think that this feature is needed (and makes sense) only for non-egg-laying animals.

[Birds can be neutered too.](https://en.wikipedia.org/wiki/Capon)

**Comment by actual-nh** [comment]
> > I think that this feature is needed (and makes sense) only for non-egg-laying animals.
> 
> [Birds can be neutered too.](https://en.wikipedia.org/wiki/Capon)

True, although if the game were to be realistic about this it's the supply of fertile females that's the primary limiting factor, unless you neuter _all_ the males (and keep the females away from non-tame males).

**Comment by tsulh** [comment]
I tried to implement this based on how other `monexamine` interactions work, but `‘class monster’ has no member named ‘set_flag’`, and I did not manage to find a way to change the flag of the monster class. Variables `monster.reproduces` and `monster.baby_timer` are private, so can't change them either. :disappointed:

**Comment by tsulh** [comment]
Any opinions on what's better: to make  `monster.reproduces `and `monster.baby_timer ` public or to introduce flag edition to the monster class? Maybe other possible solutions?

**Comment by actual-nh** [comment]
By `set_flag`, you are meaning to add the `NO_BREED` flag?

**Comment by tsulh** [comment]
> By `set_flag`, you are meaning to add the `NO_BREED` flag?

yes, I'd like to set it to 'true'

**Comment by actual-nh** [comment]
Monster flags are in the monster type, which I suspect would be why you can't edit them for a specific monster. Why would you need `monster.baby_timer` to be public if `monster.reproduces` were public?

**Comment by tsulh** [comment]
> Why would you need `monster.baby_timer` to be public if `monster.reproduces` were public?

To show a message `"PET_NAME is spay/neutered"` if `monster.reproduces` is false and `monster.baby_timer` exists (or not zero), to differentiate between spayed/neutered tamed monsters and those that can't reproduce by default.

**Comment by actual-nh** [comment]
> > Why would you need `monster.baby_timer` to be public if `monster.reproduces` were public?
> 
> To show a message `"PET_NAME is spayed/neutered"` if `monster.reproduces` is false and `monster.baby_timer` exists (or not zero), to differentiate between spayed/neutered tamed monsters and those that can't reproduce by default.

Ah. That doesn't mean baby_timer needs to be public, just that a "readonly" function to check it needs to be public - it isn't being altered.

**Comment by anothersimulacrum** [comment]
You could also store monster flags on monsters, and has_flag would return something like `type->has_flag( flag ) || flag_data.count( flag )`.

(And a set flag function would be added, modifying `flag_data`).

**Comment by actual-nh** [comment]
> You could also store monster flags on monsters, and has_flag would return something like `type->has_flag( flag ) || flag_data.count( flag )`.
> 
> (And a set flag function would be added, modifying `flag_data`).

True; could be useful also for - as an example - taming only-when-young critters, although I'm unclear on exactly how that's working/not working (in other words, if the critter is tame as a baby, pass along the tameable-with-food flag to the adult monster, and possibly that it's already tame).

**Comment by tsulh** [comment]
I went with the public variable solution and got an error that I don't understand. I think that I'd need to set up proper debugging with variable tracking to figure this one out, and I won't have time for this anytime soon. So I'll commit what I wrote so far and link it here, maybe someone else would want to continue.

> You could also store monster flags on monsters
OK, maybe first I'll try creating a NEUTERED flag for the monster class and use it instead.

The confusing error from the "public variables" solution:
```
In file included from src/debug.h:5,
                 from src/coordinates.h:14,
                 from src/character.h:29,
                 from src/activity_actor_definitions.h:13,
                 from src/monexamine.cpp:12:
src/string_formatter.h: In instantiation of ‘RT cata::convert(RT*, const cata::string_formatter&, T&&, ...) [with RT = int; T = cata::optional<time_point>&]’:
src/string_formatter.h:252:31:   required from ‘RT cata::string_formatter::get_nth_arg_as(unsigned int, T&&, Args&& ...) const [with RT = int; unsigned int current_index = 1; T = cata::optional<time_point>&; Args = {}]’
src/string_formatter.h:250:108:   required from ‘RT cata::string_formatter::get_nth_arg_as(unsigned int, T&&, Args&& ...) const [with RT = int; unsigned int current_index = 0; T = std::__cxx11::basic_string<char>&; Args = {cata::optional<time_point>&}]’
src/string_formatter.h:347:31:   required from ‘void cata::string_formatter::parse(Args&& ...) [with Args = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, cata::optional<time_point>&}]’
src/string_formatter.h:409:9:   required from ‘std::__cxx11::string string_format(std::__cxx11::string, Args&& ...) [with Args = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, cata::optional<time_point>&}; std::__cxx11::string = std::__cxx11::basic_string<char>]’
src/string_formatter.h:418:25:   required from ‘std::__cxx11::string string_format(const char*, Args&& ...) [with Args = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, cata::optional<time_point>&}; std::__cxx11::string = std::__cxx11::basic_string<char>]’
src/ui.h:224:43:   required from ‘void uilist::addentry(int, bool, K&&, const char*, Args&& ...) [with K = char; Args = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, cata::optional<time_point>&}]’
src/monexamine.cpp:150:121:   required from here
src/string_formatter.h:151:41: error: static assertion failed: Unsupported argument type
     static_assert( std::is_pointer<typename std::decay<T>::type>::value ||
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                    is_numeric<T>::value || is_string<T>::value || is_char<T>::value ||
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                    std::is_enum<typename std::decay<T>::type>::value ||
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                    is_cstring<T>::value || is_translation<T>::value, "Unsupported argument type" );
                    ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
src/string_formatter.h: In instantiation of ‘RT cata::convert(RT*, const cata::string_formatter&, T&&, ...) [with RT = long long int; T = cata::optional<time_point>&]’:
src/string_formatter.h:252:31:   required from ‘RT cata::string_formatter::get_nth_arg_as(unsigned int, T&&, Args&& ...) const [with RT = long long int; unsigned int current_index = 1; T = cata::optional<time_point>&; Args = {}]’
src/string_formatter.h:250:108:   required from ‘RT cata::string_formatter::get_nth_arg_as(unsigned int, T&&, Args&& ...) const [with RT = long long int; unsigned int current_index = 0; T = std::__cxx11::basic_string<char>&; Args = {cata::optional<time_point>&}]’
src/string_formatter.h:284:75:   required from ‘void cata::string_formatter::read_conversion(int, Args&& ...) [with Args = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, cata::optional<time_point>&}]’
src/string_formatter.h:355:17:   required from ‘void cata::string_formatter::parse(Args&& ...) [with Args = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, cata::optional<time_point>&}]’
src/string_formatter.h:409:9:   required from ‘std::__cxx11::string string_format(std::__cxx11::string, Args&& ...) [with Args = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, cata::optional<time_point>&}; std::__cxx11::string = std::__cxx11::basic_string<char>]’
src/string_formatter.h:418:25:   required from ‘std::__cxx11::string string_format(const char*, Args&& ...) [with Args = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, cata::optional<time_point>&}; std::__cxx11::string = std::__cxx11::basic_string<char>]’
src/ui.h:224:43:   required from ‘void uilist::addentry(int, bool, K&&, const char*, Args&& ...) [with K = char; Args = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, cata::optional<time_point>&}]’
src/monexamine.cpp:150:121:   required from here
src/string_formatter.h:151:41: error: static assertion failed: Unsupported argument type
src/string_formatter.h: In instantiation of ‘RT cata::convert(RT*, const cata::string_formatter&, T&&, ...) [with RT = long long unsigned int; T = cata::optional<time_point>&]’:
src/string_formatter.h:252:31:   required from ‘RT cata::string_formatter::get_nth_arg_as(unsigned int, T&&, Args&& ...) const [with RT = long long unsigned int; unsigned int current_index = 1; T = cata::optional<time_point>&; Args = {}]’
src/string_formatter.h:250:108:   required from ‘RT cata::string_formatter::get_nth_arg_as(unsigned int, T&&, Args&& ...) const [with RT = long long unsigned int; unsigned int current_index = 0; T = std::__cxx11::basic_string<char>&; Args = {cata::optional<time_point>&}]’
src/string_formatter.h:291:75:   required from ‘void cata::string_formatter::read_conversion(int, Args&& ...) [with Args = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, cata::optional<time_point>&}]’
src/string_formatter.h:355:17:   required from ‘void cata::string_formatter::parse(Args&& ...) [with Args = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, cata::optional<time_point>&}]’
src/string_formatter.h:409:9:   required from ‘std::__cxx11::string string_format(std::__cxx11::string, Args&& ...) [with Args = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, cata::optional<time_point>&}; std::__cxx11::string = std::__cxx11::basic_string<char>]’
src/string_formatter.h:418:25:   required from ‘std::__cxx11::string string_format(const char*, Args&& ...) [with Args = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, cata::optional<time_point>&}; std::__cxx11::string = std::__cxx11::basic_string<char>]’
src/ui.h:224:43:   required from ‘void uilist::addentry(int, bool, K&&, const char*, Args&& ...) [with K = char; Args = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, cata::optional<time_point>&}]’
src/monexamine.cpp:150:121:   required from here
src/string_formatter.h:151:41: error: static assertion failed: Unsupported argument type
src/string_formatter.h: In instantiation of ‘RT cata::convert(RT*, const cata::string_formatter&, T&&, ...) [with RT = double; T = cata::optional<time_point>&]’:
src/string_formatter.h:252:31:   required from ‘RT cata::string_formatter::get_nth_arg_as(unsigned int, T&&, Args&& ...) const [with RT = double; unsigned int current_index = 1; T = cata::optional<time_point>&; Args = {}]’
src/string_formatter.h:250:108:   required from ‘RT cata::string_formatter::get_nth_arg_as(unsigned int, T&&, Args&& ...) const [with RT = double; unsigned int current_index = 0; T = std::__cxx11::basic_string<char>&; Args = {cata::optional<time_point>&}]’
src/string_formatter.h:301:75:   required from ‘void cata::string_formatter::read_conversion(int, Args&& ...) [with Args = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, cata::optional<time_point>&}]’
src/string_formatter.h:355:17:   required from ‘void cata::string_formatter::parse(Args&& ...) [with Args = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, cata::optional<time_point>&}]’
src/string_formatter.h:409:9:   required from ‘std::__cxx11::string string_format(std::__cxx11::string, Args&& ...) [with Args = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, cata::optional<time_point>&}; std::__cxx11::string = std::__cxx11::basic_string<char>]’
src/string_formatter.h:418:25:   required from ‘std::__cxx11::string string_format(const char*, Args&& ...) [with Args = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, cata::optional<time_point>&}; std::__cxx11::string = std::__cxx11::basic_string<char>]’
src/ui.h:224:43:   required from ‘void uilist::addentry(int, bool, K&&, const char*, Args&& ...) [with K = char; Args = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, cata::optional<time_point>&}]’
src/monexamine.cpp:150:121:   required from here
src/string_formatter.h:151:41: error: static assertion failed: Unsupported argument type
src/string_formatter.h: In instantiation of ‘RT cata::convert(RT*, const cata::string_formatter&, T&&, ...) [with RT = void*; T = cata::optional<time_point>&]’:
src/string_formatter.h:252:31:   required from ‘RT cata::string_formatter::get_nth_arg_as(unsigned int, T&&, Args&& ...) const [with RT = void*; unsigned int current_index = 1; T = cata::optional<time_point>&; Args = {}]’
src/string_formatter.h:250:108:   required from ‘RT cata::string_formatter::get_nth_arg_as(unsigned int, T&&, Args&& ...) const [with RT = void*; unsigned int current_index = 0; T = std::__cxx11::basic_string<char>&; Args = {cata::optional<time_point>&}]’
src/string_formatter.h:304:75:   required from ‘void cata::string_formatter::read_conversion(int, Args&& ...) [with Args = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, cata::optional<time_point>&}]’
src/string_formatter.h:355:17:   required from ‘void cata::string_formatter::parse(Args&& ...) [with Args = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, cata::optional<time_point>&}]’
src/string_formatter.h:409:9:   required from ‘std::__cxx11::string string_format(std::__cxx11::string, Args&& ...) [with Args = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, cata::optional<time_point>&}; std::__cxx11::string = std::__cxx11::basic_string<char>]’
src/string_formatter.h:418:25:   required from ‘std::__cxx11::string string_format(const char*, Args&& ...) [with Args = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, cata::optional<time_point>&}; std::__cxx11::string = std::__cxx11::basic_string<char>]’
src/ui.h:224:43:   required from ‘void uilist::addentry(int, bool, K&&, const char*, Args&& ...) [with K = char; Args = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, cata::optional<time_point>&}]’
src/monexamine.cpp:150:121:   required from here
src/string_formatter.h:151:41: error: static assertion failed: Unsupported argument type
src/string_formatter.h: In instantiation of ‘RT cata::convert(RT*, const cata::string_formatter&, T&&, ...) [with RT = const char*; T = cata::optional<time_point>&]’:
src/string_formatter.h:252:31:   required from ‘RT cata::string_formatter::get_nth_arg_as(unsigned int, T&&, Args&& ...) const [with RT = const char*; unsigned int current_index = 1; T = cata::optional<time_point>&; Args = {}]’
src/string_formatter.h:250:108:   required from ‘RT cata::string_formatter::get_nth_arg_as(unsigned int, T&&, Args&& ...) const [with RT = const char*; unsigned int current_index = 0; T = std::__cxx11::basic_string<char>&; Args = {cata::optional<time_point>&}]’
src/string_formatter.h:307:75:   required from ‘void cata::string_formatter::read_conversion(int, Args&& ...) [with Args = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, cata::optional<time_point>&}]’
src/string_formatter.h:355:17:   required from ‘void cata::string_formatter::parse(Args&& ...) [with Args = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, cata::optional<time_point>&}]’
src/string_formatter.h:409:9:   required from ‘std::__cxx11::string string_format(std::__cxx11::string, Args&& ...) [with Args = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, cata::optional<time_point>&}; std::__cxx11::string = std::__cxx11::basic_string<char>]’
src/string_formatter.h:418:25:   required from ‘std::__cxx11::string string_format(const char*, Args&& ...) [with Args = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, cata::optional<time_point>&}; std::__cxx11::string = std::__cxx11::basic_string<char>]’
src/ui.h:224:43:   required from ‘void uilist::addentry(int, bool, K&&, const char*, Args&& ...) [with K = char; Args = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, cata::optional<time_point>&}]’
src/monexamine.cpp:150:121:   required from here
src/string_formatter.h:151:41: error: static assertion failed: Unsupported argument type
cc1plus: error: unrecognized command line option ‘-Wno-unknown-warning-option’ [-Werror]
cc1plus: all warnings being treated as errors
make: *** [Makefile:962: obj/tiles/monexamine.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by tsulh** [comment]
Progress report in pictures, at least it compiled! I'll fix the weird thing on the last screenshot + add requirement for a needle, painkillers and 50 thread-like items later.

Plz share ideas on required tools and consumables, I'm not sure yet how much painkillers are suitable for this. Maybe 5 weak or 2 medium or 1 strong (if there are indeed 3 grades of painkillers, I need to check the code).

![image](https://user-images.githubusercontent.com/6495727/111565032-6478f600-87a3-11eb-9e14-d50741967691.png)

![image](https://user-images.githubusercontent.com/6495727/111565137-8c685980-87a3-11eb-9cc6-1586b19ea605.png)

![image](https://user-images.githubusercontent.com/6495727/111565190-a3a74700-87a3-11eb-9849-ad12735a8204.png)

![image](https://user-images.githubusercontent.com/6495727/111565248-b7eb4400-87a3-11eb-83dc-6d50b6ae0052.png)

![image](https://user-images.githubusercontent.com/6495727/111565327-cfc2c800-87a3-11eb-8bd8-1202643ba1d6.png)

![image](https://user-images.githubusercontent.com/6495727/111565444-0993ce80-87a4-11eb-9fc8-73c180b954d4.png)

**Comment by tsulh** [comment]
The next level of complexity would be a chance to cause the pet damage proportionally to (10 - player.medicine_skill).

**Comment by tsulh** [comment]
Hmm, it seems that the word "neuter" applies o an animal of any sex (https://dictionary.cambridge.org/dictionary/english/neutering).
I'm not a native speaker though, but should probably trust the dictionary... If someone knows how this procedure is properly called in US, to maintain the regional atmosphere, the input is very welcome.

**Comment by actual-nh** [comment]
> Hmm, it seems that the word "neuter" applies to an animal of any sex (https://dictionary.cambridge.org/dictionary/english/neutering).
> I'm not a native speaker though, but should probably trust the dictionary... If someone knows how this procedure is properly called in US, to maintain the regional atmosphere, the input is very welcome.

Typically in the US, "spay" is used for female animals, and "neuter" for male ones. Is monster gender actually assigned anyplace other than in the try_reproduce() method (which doesn't seem to keep track of it for the next potential reproductive round...)? (And are all bovines, etc considered to be milkable, despite that there should be at least one bull?)

**Comment by tsulh** [comment]
> Typically in the US, "spay" is used for female animals, and "neuter" for male ones. 
That's sad, it would be nice to just use one word. Why wiki then says that assigning "neuter" to males is a mistake? Maybe it is a mistake and it should not be promoted in cdda... :eyes:

> Is monster gender actually assigned anyplace other than in the try_reproduce() method (which doesn't seem to keep track of it for the next potential reproductive round...)? (And are all bovines, etc considered to be milkable, despite that there should be at least one bull?)
No, and here is a nice answer from reddit: "Animal reproduction in cdda happens when an animal lives long enough and commits mitosis." ( https://www.reddit.com/r/cataclysmdda/comments/d7ipt2/how_does_animal_reproduction_work/ )

I don't even want this changed because animals committing mitosis is too hilarious. I won't get upset if someone else updates it, but I can't take this crime on myself. :sweat_smile:

**Comment by tsulh** [comment]
(I don't know about the milkable status)

**Comment by actual-nh** [comment]
>Why wiki then says that assigning "neuter" to males is a mistake?

I don't see that in the wikipedia article. "Neutering" would be OK to use for either, technically. "Fixing" is another term, although colloquial, that could be used for either... and perhaps is more appropriate if they are reproducing by mitosis!

**Comment by tsulh** [comment]
> > Why wiki then says that assigning "neuter" to males is a mistake?
> 
> I don't see that in the wikipedia article. "Neutering" would be OK to use for either, technically. "Fixing" is another term, although colloquial, that could be used for either... and perhaps is more appropriate if they are reproducing by mitosis!

Well, I meant that assigning it only to males is a mistake:
> Neutering, from the Latin neuter ('of neither sex'), is the removal of an animal's reproductive organ, either all of it or a considerably large part. "Neutering" is often used incorrectly to refer only to male animals, but the term actually applies to both sexes. The male-specific term is castration, while spaying is usually reserved for female animals.

**Comment by tsulh** [comment]
> > > Why would you need `monster.baby_timer` to be public if `monster.reproduces` were public?
> > 
> > 
> > To show a message `"PET_NAME is spayed/neutered"` if `monster.reproduces` is false and `monster.baby_timer` exists (or not zero), to differentiate between spayed/neutered tamed monsters and those that can't reproduce by default.
> 
> Ah. That doesn't mean baby_timer needs to be public, just that a "readonly" function to check it needs to be public - it isn't being altered.

TIL private variables can be changed via functions, so that's what I did (since this is the style of the existing code there).

**Comment by anothersimulacrum** [comment]
I say go with neuter, we don't present (or track) any sort of gender information for people to be confused by anyways.

**Comment by tsulh** [comment]
I added a fork commit for now: https://github.com/CleverRaven/Cataclysm-DDA/commit/adab9b371813b6a662efad0f712e18f981f950e4
I'll make a pull request after I complete the tools+materials requirements, and maybe also add the pet damage risk that depends on the player's medical skill.

For now, I'll play with the code above and see if it works as intended. I plan to neuter a few dogs, keep them away from the non-neutered ones, and check whether the neutered ones indeed don't reproduce.

**Comment by tsulh** [comment]
I have a few brown chicks in the game (hatchlings of geese and/or turkeys), and they don't have the neutering option on interaction. I wonder if it appears when they grow up...

**Comment by tsulh** [comment]
Testing in progress: split my dogs into 2 groups: non-neutered (5 dogs, stay outdoors) and neutered (7 dogs, moved to the hall of the nearby refugee center.

Are puppies of pet dogs born wild or tamed? How far from their parents can they spawn?
