### ISSUE TITLE
Moving corpses cause duplication

### ISSUE THREAD

**Issue by OliveChukar** [CleverRaven/Cataclysm-DDA#48001]
# Describe the bug
Moving unpulped corpses with from a vehicle to the ground with advanced inventory causes the corpses that are ready to revive to do so but also puts the corpse that you were moving on the ground under the revived creature. 

# Steps To Reproduce
Kill several creatures that can revive.
Put them in vehicle storage.
Wait until enough time has passed for revival.
Use advanced inventory to move the corpses to the ground. 
Kill the revived creatures.
See that you have more corpses then you started with.

# Expected behavior

Corpses that revive should remove the corpse item. 

# Screenshots

# Versions and configuration
 OS: Windows
    OS Version: 10.0 2004
 Game Version: 0.E-10010-gd821da4 [64-bit]
 Graphics Version: Tiles
 Game Language: System language [english]
 Mods loaded: [
    Dark Days Ahead [dda]
# Additional context
[save corpse dupe.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6131336/save.corpse.dupe.zip)

**Comment by OliveChukar** [comment]
Tested more in version 0.E stable. Put corpses in furniture waited for them to be ready to revive then moved them in and out of the furniture with advanced inventory. When the zombie revived as I was moving it I got a message asking if I wanted to stop moving items. I answered yes and the dupe bug happened. I also tested having corpses revive when I was hauling them along the ground and they did not dupe. 

It seems that the problem happens when a corpse revives as you are moving it with advanced inventory and you choose to stop in the middle of the move action.

**Comment by actual-nh** [comment]
Do the duplicated corpses revive (and, if so, when)?

**Comment by OliveChukar** [comment]
The dupe corpse is unchanged. If you keep moving it around the floor it will repeatedly revive and dupe. I was able to create 5 corpses form 1 in less then 10 in game minutes. Each revived monster corpse was shown in yellow so I think they would also revive if I waited.

**Comment by anothersimulacrum** [comment]
Confirmed on fb7f80eb048a52f5c357508d5f1f3f0edb94dcb5
