### ISSUE TITLE
Weary Transition keep getting increase and decrease repetitively while resting.

### ISSUE THREAD

**Issue by vipches** [CleverRaven/Cataclysm-DDA#48009]
I have this problem on the new version, I spend like about 2 days in order to recovering my weariness fully,

However, there's something wrong about the weary transition, because it keep getting repetitively increase and decrease over and over,

I tried spend about half day in order to recovering fully my weariness at the fresh level, and weary transition just simply won't going any further, it stuck like ||| between ||/ and |||/ over and over and some time it's decrease even more, like || or something,

I have no idea what's going on, I spend whole day waiting it fill up, and it just can't do so, my activity are stay at the none level, and the weird thing is, this situation only happening when my weariness is at the Fresh level, anything else work normally.

**Comment by actual-nh** [comment]
This sort of thing is what #47653 is trying to reduce. (Tip: In the meantime, make sure your stomach and gut have some stuff in them.)

**Comment by anothersimulacrum** [comment]
`intake` is not reducing to 0, for whatever reason. I'd need a save to really be able to say much more.

**Comment by actual-nh** [comment]
Given that it's being multiplied by 0.95 each hour - not having something subtracted from it - and added to by anything coming out of the guts, I would be surprised if it did go to 0, actually. But - @vipches, a save would indeed be nice.

**Comment by anothersimulacrum** [comment]
It's being subtracted by either 5% of itself or bmr, whichever is larger. BMR is for 24 hours, so when it gets closer to 0, it'll have added 30 minutes of calorie loss, and lost 72 minutes worth. That should let it hit 0.

**Comment by actual-nh** [comment]
> It's having either 5% of itself or bmr, whichever is larger, subtracted. BMR is for 24 hours, so when it gets closer to 0, it'll have added 30 minutes of calorie loss, and lost 72 minutes worth. That should let it hit 0.

You seem to be thinking of `weary.tracker` - this is what's (currently) happening to `weary.intake` that decreases it (at character.cpp line 5706):
```
    if( weary.tick_counter >= 12 ) {
        weary.intake *= 1 - recovery_mult;
        weary.tick_counter = 0;
    }
```
One of the odder aspects of this is that increasing recovery_mult makes `weary.tracker` go down faster, but also makes `weary.intake` - which opposes the effects of `weary.tracker` - go down faster.

**Comment by anothersimulacrum** [comment]
The code's here:
https://github.com/CleverRaven/Cataclysm-DDA/blob/d821da4ea4c3ed722033a662e3e653bd2139545c/src/character.cpp#L5690-L5704

`recovery_mult = 0.05`

**Comment by anothersimulacrum** [comment]
Oh, my bad, I did indeed mean tracker.

**Comment by anothersimulacrum** [comment]
Maybe there's some odd interaction with negative weariness? I realized that `Character::weariness()` can return a negative value, and it's probably worth halting that at 0.

**Comment by actual-nh** [comment]
Ping: @vipches: Save file (and ideally debug log)?

**Comment by vipches** [comment]
Sorry, I alright restart the game, it's,gone.

**Comment by vipches** [comment]
And, it's happening, this time I'll took my save file at this issue, I hope you can found where the problem is.
[Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6147922/Save.zip)
By the way, because I'm chinese, I hope you wont have any problem with chinese language.

**Comment by anothersimulacrum** [comment]
Won't be a problem.
I can reproduce it, looking into it.

**Comment by anothersimulacrum** [comment]
This is probably generally reproducible by having a high `tracker` (> thresh), and an `intake` higher than that. Weariness increases as you burn calories, then decreases every 30 minutes (as tracker increases and decreases). If you wait for a while, you'll burn down `tracker` and start to recover.

**Comment by actual-nh** [comment]
Should I check vs #47653, or should you since you've been able to reproduce it (I've been working on monster factions + test errors so haven't tried yet)?

**Comment by actual-nh** [comment]
@vipches: #47653 has been merged; could you check this in an experimental build for 11567 or later? It may not fix it entirely, but it should help.
