### ISSUE TITLE
Boats partially grounded force me to go underwater to get to the driver's seat.

### ISSUE THREAD

**Issue by Eavath** [CleverRaven/Cataclysm-DDA#48011]
# Describe the bug
Any time I get in my boat after grounding it, all boat tiles on deep water tiles essentially are intangible, making me go for a swim.

# Steps To Reproduce

1. Get any boat long enough to span from dry land to deep water
2. Park boat with even just 1 frame touching dry land.
3. Any part of the boat in deep water forces you to go underwater. Boat is still driveable.
4. Park boat immediately fully in water, able to traverse boat above water.

# Expected behavior

I should be able to park my long boat partially on land to help with loading of loot. I shouldn't have to drench myself to leave land.

# Screenshots

Screen capture of problem. Also replicated with a 1x4 metal canoe as well as a 3x3 amphibious vehicle: https://imgur.com/a/T3xqv63

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-9887-gfa86903 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Eav's Mutations [eav_mut]
]

 - OS: Windows 10
 - Game Version: 0.E-9887-gfa86903
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: [See Above]
 -->

# Additional context

**Comment by Fosheze** [comment]
From what I have seen it doesn't even need to be dry land. This works just between shallow water and deep water as well.

**Comment by Salty-Panda** [comment]
Sounds exactly like ##46488

**Comment by actual-nh** [comment]
Also see #48612.

**Comment by actual-nh** [comment]
> Sounds exactly like ##46488

This seems a bit different - it can be recovered from, for one thing.

**Comment by Salty-Panda** [comment]
The one I made was the same I think. I could walk back from deep water to shallow water to "get back on the ground".
Although the pics I linked shows how I instead took control of vehicle and _drove_ back which resulted in my staying "diving" despite leaving deep water tiles

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-11128.
