### ISSUE TITLE
Non-hardcoded map extras can't be debug spawned

### ISSUE THREAD

**Issue by Venera3** [CleverRaven/Cataclysm-DDA#48034]
# Describe the bug

Map extras defined only in JSON can't be spawned from the map section of the debug menu, making testing them more annoying than it needs to be.

# Steps To Reproduce

1. Look for JSON-defined map extras (prisoner transport, dermatik/wasp nests) in the "Spawn map extra" option
2. Find none

# Expected behavior

Being able to spawn stuff for testing.

# Additional context

I thought I opened this already when I did the big dermanest, but apparently I forgot.

**Comment by ZhilkinSerg** [comment]
Yeah, debug menu for map extras was added before map extras were unhardcoded and it still operates on functions.

std::unordered_map<std::string, map_extra_pointer> FM = MapExtras::all_functions();

**Comment by actual-nh** [comment]
> Yeah, debug menu for map extras was added before map extras were unhardcoded and it still operates on functions.
> 
> std::unordered_map<std::string, map_extra_pointer> FM = MapExtras::all_functions();

So either have them in a separate debug menu or stick fake functions for them in (that call the code that uses the JSON map extra in question)?

**Comment by ZhilkinSerg** [comment]
It should just be using list of map extra ids.
