### ISSUE TITLE
[0.9] Increase pathfinding cost for Zombies in regards to cars.

### ISSUE THREAD

**Issue by Lap** [CleverRaven/Cataclysm-DDA#4803]
Zombies are regularly rampaging against empty cars instead of moving one or two spaces around. Not only does this not makes sense even for limited zombie intelligence, it is also a huge pain as Zombies will unnecessarily trash vehicle parts.

I don't know if you are using astar, but I think the relative cost of paths through cars should be increased so that zombies will only attack cars if there really is no better way anywhere close.

**Comment by mugling** [comment]
Duplicates #2169
