### ISSUE TITLE
Bike Shop doesn't generate a roof

### ISSUE THREAD

**Issue by superninjakiwi** [CleverRaven/Cataclysm-DDA#48041]
# Describe the bug

The bike shop doesn't have a roof. I've come across the issue a few times before, but never realized exactly what the problem was, because I always died before bothering to investigate why I couldn't climb up the downspout. I think it's happened every time I've come across a bike shop, and I believe that it only happens to the bike shop.

# Steps To Reproduce

1. Find a bike shop
2. Climb a nearby building to the second story/roof
3. Find that the bike shop has no roof.

# Expected behavior

The bike shop should have a roof, like everything else.

# Screenshots

https://i.gyazo.com/939e2e0fa8c6a288032287c2b7f9af16.png

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-9945-g5960368 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Mythical Martial Arts [MMA],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    No Fungal Monsters [No_Fungi],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

I think that at least one version of the bike shop spawns with stairs, and if you climb them, you immediately fall back down a level. Owch.

**Comment by Night-Pryanik** [comment]
Can't confirm on latest experimental as of 2nd of April. Debug-spawned `s_bike_shop_1` (the variation from the OP), and it has correctly spawned a roof.
![изображение](https://user-images.githubusercontent.com/11132525/113383640-68a53600-9395-11eb-9bfd-84eadba87694.png)

**Comment by Night-Pryanik** [comment]
Probably the same reason as in #46942?

**Comment by l29ah** [comment]
Got hit with it today. Save file: 
[2021.04.25.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6395126/2021.04.25.zip)

**Comment by RenechCDDA** [comment]
Resolved by #51729
