### ISSUE TITLE
Decreasing key presses for (t)hrowing.

### ISSUE THREAD

**Issue by MeltingIsTired** [CleverRaven/Cataclysm-DDA#48055]
# Is your feature request related to a problem? Please describe.
Throwing objects takes more time/key presses than necessary. When a player presses **t**, an item menu opens, defaulting to the first listed item in one's inventory, rather than their wielded item. From there, the player makes a manual selection of the item to be thrown. However, if one chooses an item aside from whatever is being currently held, the player is prompted to wield the object they intend to throw. Yet preparing for this by simply equipping the item beforehand is insufficient. They still have to select it in the item menu every single time they want to throw it. All of this before the actual menu for aiming appears. The way it works now is a simple downgrade in convenience compared to guns or bows.

# Describe the solution you'd like
Remove the item selection screen for throwing. Proceed to the aiming menu directly by pressing **t**, using the item currently wielded. If the character is empty-handed, display the message _"You can't throw a handful of air!"_

# Describe alternatives you've considered
1: Have the item menu pop up exclusively when attempting to throw whilst empty-handed
2: If the item menu is to be kept in its current position, have it default to selecting the wielded item first.

**Comment by WilliamtheCardboardBox** [comment]
Considering most throwing weapons are stacks, this seems really reasonable. I always hated training Throwing up or trying to lob stuff at monsters from my inventory. It was very clunky.

**Comment by superninjakiwi** [comment]
> display the message "You can't throw a handful of air!"

A message containing the slang phrase "throwing fists" might provide a bit of opportunity for humor, if anyone wants that instead.

**Comment by snipercup** [comment]
A good solution would be to allow the user to select an item if their hands are empty and otherwise just throw what's in their hands. On the other hand, a lot of checks can be skipped if you only allow the wielded item to be thrown.
