### ISSUE TITLE
Listener zombie sprite displaced

### ISSUE THREAD

**Issue by DavisBroda** [CleverRaven/Cataclysm-DDA#48053]
Listener zombie sprite appears one tile higher than it actually is

# Steps To Reproduce

find listener zombie, and look at sprite

# Expected behavior

sprite appears on tile zombie occupies

# Screenshots

![listener_zombie_displaced](https://user-images.githubusercontent.com/15205060/111095443-d76c3d80-8513-11eb-8432-c671f0ac23e5.PNG)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-10027-g45f883c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

using tileset Chibi_Ultica

potentially related to earlier issue #46834

**Comment by actual-nh** [comment]
Ping: @int-ua, @Fris0uman?

**Comment by Fris0uman** [comment]
Yep, I'll try to fix it at some point today. The short term fix is easy but long term I think it will require some tweaks of the compose.py script and/or me being more carefull when I add monster to MSX that have non 32*32 sprites in Ultica.

**Comment by actual-nh** [comment]
How is MSX related?

**Comment by Fris0uman** [comment]
Chibi Ultica is build from Ultica and MSX, if you go to https://github.com/I-am-Erk/CDDA-Tilesets/tree/master/gfx/Chibi_Ultica you'll see that ChibiUltica is just symbolic links towards Ultica and MSX.

**Comment by actual-nh** [comment]
Oh, yes; I have no problem remembering that Chibi Ultica is built out of two others, nor (as one might guess) that one of them is Ultica, but remembering from which other tileset it's built is another matter...
