### ISSUE TITLE
Lab Lag

### ISSUE THREAD

**Issue by souricelle** [CleverRaven/Cataclysm-DDA#48062]
# Describe the bug

Labs in some locations get very laggy due to the large amount of stuff happening on Z levels other than the player's. Contributing factors appear to include an overlapping anthill, the rift finale with the phase suit (the rifts pump out tons of monsters even if the player isn't around and the Hounds spread purple fog all over the place), or having a research center up above. The problem feels somewhat unique to labs due to the large number of enemies, the vertical layout, and the kinds of enemies that show up.

This isn't a huge problem when you're going down into a lab from the surface usually, especially in the case of a research center, but a lab start often relies on sleeping a few nights down there and reading plenty of books to get yourself to a point where you can escape, whereas a player approaching a research center from the outside probably isn't going to be sleeping or reading books there until they've cleaned up a lot of the enemies.

Suggestions off the top of my head would be to limit research center basements to 1 floor lab designs, to stop lab scenario starts from putting the player under a research center, to reduce the purple fog from Hounds of Tindalos, to make the phase suit/rift lab finale not one you can start in, or to make ants invade labs less often.

# Steps To Reproduce

1) Make a new character in a lab start scenario.
2) Try reading a book. Many times it'll be fine, but depending on your finale and what's on the upper Z levels, you might experience serious slowdown.

# Expected behavior

The game should run at a normal speed.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-10010-gd821da4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]
# Additional context

Here's an example save. This one doesn't have Hounds in the basement or ants, but it does have a research center up top. Try reading a book and note the slowdown - it is often much worse but this demonstrates the issue.

[Moulton Heights.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6143697/Moulton.Heights.zip)

**Comment by anothersimulacrum** [comment]
Fairly normal monster AI slowness
![image](https://user-images.githubusercontent.com/42699974/111205636-ae37c580-8584-11eb-9d23-c96066b9db3e.png)

**Comment by Fosheze** [comment]
> Fairly normal monster AI slowness
> ![image](https://user-images.githubusercontent.com/42699974/111205636-ae37c580-8584-11eb-9d23-c96066b9db3e.png)

Won't this be resolved by #36832 whenever that gets implemented? Basically if the monsters sit around long enough with no stimuli then they just go dormant.
