### ISSUE TITLE
Lighters and Candles Refilling in Vehicle Containers.  

### ISSUE THREAD

**Issue by Cpl-Jordan** [CleverRaven/Cataclysm-DDA#48064]
# Describe the bug
Lighters (Butane) and candles from my experience seem to refill max in vehicle containers once. Then it wont happen to those lighters or candles again.

# Steps To Reproduce
1.) Find a used lighter.
2.) Find a vehicle with any storage compartments.
3.) Walk away from the vehicle and past time by waiting.
4.) Come back and the lighter should now have refilled to max.

(This might not be 100% accurate on how to reproduce but I know from just playing the game that used lighters/candles I store in my car end up refilling to max uses when I put them in storage and I walk away from my car to kill more zombies or looting)

# Expected behavior
Storing Candles and lighters in my car shouldn't refill my candles and lighters.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-10055-gb7e1cd5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by MarlossCDDA** [comment]
I can't repro by going to sleep or leaving + coming back to the reality bubble, but I can repro via:
- Spawn car
- Spawn lighter and candle, use them up so they aren't at 100, drop them in the trunk
- `S` to save and quit
- Reload
- They're back at 100
- Use the same lighter and candle again so they aren't at 100, drop in trunk
- Save and quit, reload
- They are NOT back at 100 this time

Also confirmed that it only works in a vehicle, not with items you dropped on the ground.

**Comment by wapcaplet** [comment]
Maybe same issue as #47739
