### ISSUE TITLE
Signal Flares do not stay Lit

### ISSUE THREAD

**Issue by Boredone** [CleverRaven/Cataclysm-DDA#48074]
# Describe the bug
When using a Flare Gun, the Signal Flares from the flaregun makes a Flare when it lands/hits.
In my messing around, said flare has 0 `Flare Pyrotechnic` loaded, meaning it automatically goes out after a few seconds.

# Steps To Reproduce

1. Spawn/Find loaded Flaregun
2. Shoot it anywhere.
3. Wait a few seconds
Optional:    Look at the flare with X or some other method and see it's empty of Pyrotechnic.
4. Watch it go out, with the message `You have lost the item you were using to start the fire.'

# Expected behavior

The flare the flaregun shoots should last longer then a few seconds. Can't even load in another flare before it goes out.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-10055-gb7e1cd5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

Discovered another bug testing this out related to it interrupted actions. Plan to toss up an issue report of that as well soon.

**Comment by hexagonrecursion** [comment]
Confirmed
- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: cb86201 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]
