### ISSUE TITLE
Bird mutagens and serums doesn't give bird wings mutation.

### ISSUE THREAD

**Issue by ifffrt** [CleverRaven/Cataclysm-DDA#48080]
# Describe the bug
You cannot get bird wings mutation from bird mutagens and serums. Normal mutagens works fine.

# Steps To Reproduce

1. Give yourself 100 bird serums.
2. Give yourself wings stub mutation as a head start.
3. Inject all 100 bird serums into yourself. 
4. Fail to get bird wings mutation.
5. Try again with normal mutagens. Succeed on first try.

# Expected behavior

That bird wings mutation can be triggered with bird mutagens.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version [Windows 8.1 Pro build 9600]
- Game Version: 0.E-10070-gbcd4c6c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key],
    Graphical Overmap [Graphical_Overmap],
    sees-player icon, retrodays [sees_player_retro],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    Mythical Martial Arts [MMA],
    More Survivor Stuff [more_survivor_stuff],
    Fuji's Military Profession Pack [fuji_mpp],
    Mutation Changes [Mutation_Changes],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    No Fungal Monsters [No_Fungi],
    Magiclysm [magiclysm],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Zombie Cop Drop [Zombie_Cop_Drop]
]

# Additional context

**Comment by Salty-Panda** [comment]
In JSON it appears to be declared properly.
Could you check it without mod `Mutation Changes [Mutation_Changes]`?

**Comment by ifffrt** [comment]
It worked. It seems the mutation changes mod changed the category of the Bird Wings mutation to chimera which was why I couldn't trigger it with bird mutagens.
