### ISSUE TITLE
Incorrect Magiclysm Spellcasting Achievement Popup

### ISSUE THREAD

**Issue by souricelle** [CleverRaven/Cataclysm-DDA#48084]
# Describe the bug

I got an achievement for casting a spell when no spell was cast. My character does not know any magic.

# Steps To Reproduce

Unknown, I got the achievement when I was sleeping as a malfunctioning cyborg. A lot of my bad bionics were going off. I heard of an issue where someone was getting the achievement when something else cast a spell.

# Expected behavior

You should not get an achievement for something you didn't do.

# Screenshots

![error](https://user-images.githubusercontent.com/67675144/111375542-9c752180-865b-11eb-850d-eb289ebe9003.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-10010-gd821da4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Stats Through Skills [StatsThroughSkills],
    No Fungal Monsters [No_Fungi]
]

# Additional context

[The relevant save immediately after it happened](https://github.com/CleverRaven/Cataclysm-DDA/files/6152053/Yeagertown.zip)

**Comment by Maleclypse** [comment]
Monsters added because the only cause I've found for this so far is when a monster inside the reality bubble casts a spell.

**Comment by actual-nh** [comment]
Ping: @KorGgenT?

**Comment by Termineitor244** [comment]
Maybe related: In my own game I got this achievement after _learning_ my first spell, not when casting said spell

**Comment by anothersimulacrum** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/issues/47425 and https://github.com/CleverRaven/Cataclysm-DDA/issues/47442

**Comment by superninjakiwi** [comment]
> Maybe related: In my own game I got this achievement after _learning_ my first spell, not when casting said spell

That is actually most likely because the Rune spells are currently set to the maximum level of 2, and you learn them whenever becoming a member of a particular class; it's probably a slightly different bug than what's causing the achievement popup after sleeping or other mundane activities.
