### ISSUE TITLE
Interruptable/Resumable Digging

### ISSUE THREAD

**Issue by jorganmir** [CleverRaven/Cataclysm-DDA#48105]
Changes to exhaustion and stamina usage make the digging stick mostly useless, as digging does not hold onto progress when interrupted. A digging stick takes far too long to possibly dig a hole, because one cannot resume digging after interrupting it, due to becoming weary and exhausted too soon.

**Comment by MomoiroShinobinomono** [comment]
Aye, just got attacked by a wild goose at 92% after ~7 hours of digging. All the work is wasted for nothing.
Though on a bright side a digging stick is ok for tilling.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
