### ISSUE TITLE
compose.py with --use-all uses tile entries from filler sheets for non-filler sprites under certain conditions

### ISSUE THREAD

**Issue by int-ua** [CleverRaven/Cataclysm-DDA#48103]
# Describe the bug

This may require forcing all filler sheets being worked on after finishing non-fillers and creating tile entries for unused non-filler sprites. Suggestions for alternative approaches are welcome.

# Steps To Reproduce

Minimal tileset that shows this issue when composed with `--use-all`:
[test_tileset.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6159913/test_tileset.zip)

```sh
$ venv/bin/python compose.py --use-all .../test_tileset/
$ python3 -m json.tool .../test_tileset/tile_config.json
```

# Expected behavior

Filler tile entry ignored.

# Screenshots

# Versions and configuration

master branch

# Additional context

This was the reason behind #48053 and #46834 and I'll try to think what can be done. 

Update: and #48157

**Comment by actual-nh** [comment]
>forcing all filler sheets being worked on after finishing non-fillers

So that everything is known about the non-fillers by the time the program gets to the fillers?

>creating tile entries for unused non-filler sprites

I am having problems understanding how this would be related; if they're unused, then why would substituting filler for them be a problem?

**Comment by int-ua** [comment]
> > forcing all filler sheets being worked on after finishing non-fillers
> 
> So that everything is known about the non-fillers by the time the program gets to the fillers?

So that with `--use-all` non-fillers become used and thus fillers are ignored properly.

> > creating tile entries for unused non-filler sprites
> 
> I am having problems understanding how this would be related; if they're unused, then why would substituting filler for them be a problem?

A bit repetitive, but still: `--use-all` is for not having to define tile entries for all sprites, so they should be used by the time fillers are checked.

**Comment by actual-nh** [comment]
Ok. So they aren't literally unused, they're more like un-named-by-json (so a default id from the filename gets used). Hrm... but I'm looking at the code, and it should already be doing it in the order you said... so the problem seems to be that it isn't replacing the fillers that it already has with the unused tiles by filename. Hrm. Wait:
```python3
       for unused_png in unused:
            unused_num = self.pngname_to_pngnum[unused_png]
            sheet_min_index = 0
            for sheet_max_index in tiles_new_dict:
                if sheet_min_index < unused_num <= sheet_max_index:
                    tiles_new_dict[sheet_max_index]['tiles'].append(
                        {'id': unused_png.split('.png')[0],
                         'fg': unused_num})
                    break
                sheet_min_index = sheet_max_index
```
Umm... this is just going to put it into _that sheet's_ dict for the correspondence. How would this override a filler sheet's entries? Am I misunderstanding something?

**Comment by int-ua** [comment]
Filler sheet entries are worked on before this code is executed and they reference the ID of the filename, try composing the test tileset in the first comment.

Also I'm rewriting the code slowly, right now it's
```py
    def handle_unreferenced_sprites(self) -> list:
        '''
        Either warn about unused sprites or return the list
        '''
        if self.use_all:
            return self.unreferenced_pngnames

        for pngname in self.unreferenced_pngnames:
            if pngname in self.processed_ids:
                print(f'Error: {pngname}.png not used when {pngname} ID '
                      'is mentioned in a tile entry')
                self.error_logged = True
            else:
                print(
                    f'Warning: sprite filename {pngname} was not used '
                    f'in any {self.output_conf_file} entries')
        return []
```

```py
        # get sprites that need tile entries generated
        unused = self.handle_unreferenced_sprites()

        # the list must be empty without use_all
        for unused_png in unused:
            unused_num = self.pngname_to_pngnum[unused_png]
            sheet_min_index = 0
            for sheet_max_index in tiles_new_dict:
                if sheet_min_index < unused_num <= sheet_max_index:
                    tiles_new_dict[sheet_max_index]['tiles'].append(
                        {'id': unused_png.split('.png')[0],
                         'fg': unused_num})
                    break
                sheet_min_index = sheet_max_index
```
