### ISSUE TITLE
(Magiclysm) Repeatable 1000+ focus from reading scroll

### ISSUE THREAD

**Issue by souricelle** [CleverRaven/Cataclysm-DDA#48110]
# Describe the bug

While reading a scroll of Eagle's Sight, my focus jumped up to the 1700s.

# Steps To Reproduce

1) Load the attached save
2) Read the scroll of eagle's sight
3) When you gain a level, your XP gained will be added to your current focus

# Expected behavior

Obviously that shouldn't be happening. I imagine it's trying to pull focus for xp gain rate and accidentally adding XP to focus.

# Screenshots

![bug](https://user-images.githubusercontent.com/67675144/111598281-4e137000-878c-11eb-9450-dc34994cf485.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-10010-gd821da4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Stats Through Skills [StatsThroughSkills],
    No Fungal Monsters [No_Fungi]
]

# Additional context

[Yeagertown.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6162573/Yeagertown.zip)

**Comment by MarlossCDDA** [comment]
I think this should have been fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/48021 - can you still reproduce on the latest build?

**Comment by anothersimulacrum** [comment]
If that didn't fix it, https://github.com/CleverRaven/Cataclysm-DDA/pull/48022 definitely should have.

**Comment by souricelle** [comment]
> I think this should have been fixed by #48021 - can you still reproduce on the latest build?

No longer seems to be happening, closing the issue now.
