### ISSUE TITLE
Favorited Ammo, and non favorite ammo of the same type cannot both be loaded into the same magazine/gun

### ISSUE THREAD

**Issue by Mallowdust** [CleverRaven/Cataclysm-DDA#48120]
# Describe the bug
If you try to load a gun or magazine with ammunition that has the favorite asterisk and that does not have the favorite asterisk it will not allow you to do so. I tried this with 9mm on a handgun and with 223, on a rifle and the results where the same. I presume this issue affects other calibers as well

It seems that having bullets with with a favorite asterisk and without it classify them as separate bullets and incompatible to be loaded into the same magazine unless all the bullets are of either category (favorited or not favorited)

# Steps To Reproduce

<!-- Steps to reproduce the behavior:
1. Make a player with a gun, magazine, and some ammo.
2. Have either the magazine or gun itself partially loaded with favorited ammo or non favorited ammo.
3. Then try to fill up the gun or magazine with ammo that is not of the same favorite category that is already loaded. (either with " * " or without one)

# Expected behavior

Ideally you are able to put favorited 9mm ammo with non favorited 9mm ammo, into your 9mm compatible gun rather than having to make sure all the ammo you are loading into your gun is favorited or non-favorited.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-10088-g74e26ac [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by pjf** [comment]
Can reproduce in #49292 with trying to mix favourite and non-favourite liquids as well.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-11128.
![изображение](https://user-images.githubusercontent.com/11132525/188936617-318899c7-2fb1-4014-b285-35e334033255.png)
