### ISSUE TITLE
Cant make a new game (system not responding)

### ISSUE THREAD

**Issue by BerryZone** [CleverRaven/Cataclysm-DDA#48130]
# Describe the bug
I tried to make a new game with a custom char as usual, the assets and mods loaded, and right after that the game brings me back to the main menu without showing a error alert or the character creation panel. Preset, random character and "play now" options do the same thing. This didnt happen to me before, and the best part is i dont know the source of the issue.

# Steps To Reproduce
I have no idea.

# Expected behavior
I expected for the character panel to show up (in the case of custom or preset char), and to get thrown right into the game (in the case of random char and "play now" option).

# Screenshots
N/A.

# Versions and configuration
(sadly i cant access the game menu in any way, so i gotta improvise)

OS: Windows 10
Game Version: 0.E-10070-gbcd4c6c
Graphics version: ChestHole16
Ingame language: English
Mods loaded: dda, graphical overmap, cityside, MMA, more survivor stuff, alt map key, generic guns, crit expansion, aftershock, classic zombies, fuji military pack, mutation changes, speedydex, stats through kill, stats through skills
Additional context

# Additional context
N/A.

**Comment by Zireael07** [comment]
Try removing mods one by one to see which one is the culprit...

**Comment by BerryZone** [comment]
> Try removing mods one by one to see which one is the culprit...

Quick update: my game is now frozen and not responding. Think im gonna need to make a new directory.

**Comment by BrettDong** [comment]
Does a fresh new world with no mods other than core content have the same problem?

**Comment by BerryZone** [comment]
> Does a fresh new world with no mods other than core content have the same problem?
No the game works just fine with only core content, think its about the other mods.

**Comment by BerryZone** [comment]
actually yeah, turns out some of the mods were outdated for my build. Also found a neat modpack that should take care of that, sorry for the false alarm. But for some reason my 1st game directory is frozen and not responding, gonna make a seperate issue report for it.
