### ISSUE TITLE
Always crashing when trying to load my game

### ISSUE THREAD

**Issue by Paperbell** [CleverRaven/Cataclysm-DDA#48134]
# Describe the bug
The entire game crashes when I try to load my most recent run after alt-f4.

# Steps To Reproduce

1. Extract the attached world zip to a saves folder
2. Run "Maxwell Conn" in that world
3. The game immediately crashes

# Expected behavior

The game shouldn't crash.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-10111-g5ca62e7 (tiles)
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: dda, Disable NPC needs, bionic professions
 
# Additional context
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6172505/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6172506/debug.log)
[vanila2zip.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6172472/vanila2zip.zip)

I don't know if this has anything to do with it, but before alt-f4'ing to my last autosave, I had talked with the marloss npc and got a marloss berry. I was also repairing a cleansuit while said autosave happened.
Edit: I was also getting a lot of errors of "lost target in save cycle" beforehand, but without any crashes.

**Comment by tsulh** [comment]
I confirm that it crashes after showing errors like this and a few more:

```
 DEBUG    : Failed to find item_location owner with character_id 1

 FUNCTION : bool item_location::impl::item_on_person::ensure_who_unpacked() const
 FILE     : src/item_location.cpp
 LINE     : 290


 DEBUG    : item_location lost its target item during a save/load cycle

 FUNCTION : void item_location::impl::ensure_unpacked() const
 FILE     : src/item_location.cpp
 LINE     : 114


 DEBUG    : parent location does not point to valid item

 FUNCTION : void item_location::deserialize(JsonIn&)
 FILE     : src/item_location.cpp
 LINE     : 782
```

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 10 (buster); Release: 10; Codename: buster; 
- Game Version: 0.E-10118-g4338567d94-dirty [64-bit]
- Graphics Version: Tiles

**Comment by EvgenijM86** [comment]
It seems the save/load errors are dependent on what was generated in the world. I.e. you can start the game and it will save/load perfectly, but if you drive around for a while you might encounter those errors. Although in my case it does not lead to crash (yet).

**Comment by wapcaplet** [comment]
Similar errors reported on discord. User Hedemod reported the "Failed to find item_location owner" error after a normal save and load cycle (*not* using Alt-F4), followed by other errors (possibly unrelated). In this case, the game did not crash afterward.

```
DEBUG    : Failed to find item_location owner with character_id 1

 FUNCTION : bool item_location::impl::item_on_person::ensure_who_unpacked() const
 FILE     : src/item_location.cpp
 LINE     : 290
```

Screenshot of some following errors:

![image](https://user-images.githubusercontent.com/238395/111908163-cd6ba280-8a1d-11eb-9e86-bd0cda4007c5.png)

![image](https://user-images.githubusercontent.com/238395/111908177-da889180-8a1d-11eb-9d37-1609248c9a29.png)

**Comment by EvgenijM86** [comment]
In my case it happens when it tries to read the following lines from save file:

`"targets": [ { "idx": 0, "type": "in_container", "parent": { "idx": 7, "type": "in_container", "parent": { "type": "character", "character": 1, "idx": 15 } } } ]`

The in_container part fails here:

```
    } else if( type == "in_container" ) {
        item_location parent;
        obj.read( "parent", parent );
        if( !parent.ptr->valid() ) {    <---------- here!
            debugmsg( "parent location does not point to valid item" );
            ptr.reset( new impl::item_on_map( map_cursor( pos ), idx ) ); // drop on ground
            return;
        }
```

**Comment by EvgenijM86** [comment]
And it tries to drop the item at these coordinates:
"placement": [ -2147483648, -2147483648, -2147483648 ]

Are those coordinates normal?

**Comment by EvgenijM86** [comment]
And the whole things happens inside some "backlog" entry:

`"backlog": [ { "type": "ACT_EAT_MENU", "actor": null, "moves_left": 21474836, "index": -1, "position": -2147483648, "coords": [  ], "coord_set": [  ], "name": "", "targets": [ { "idx": 0, "type": "in_container", "parent": { "idx": 7, "type": "in_container", "parent": { "type": "character", "character": 1, "idx": 15 } } } ], "placement": [ -2147483648, -2147483648, -2147483648 ], "values": [ 0, 1 ], "str_values": [ "" ], "auto_resume": false, "monsters": [  ] }, { "type": "ACT_EAT_MENU", "actor": null, "moves_left": 21474836, "index": -1, "position": -2147483648, "coords": [  ], "coord_set": [  ], "name": "", "targets": [ { "idx": 0, "type": "in_container", "parent": { "idx": 7, "type": "in_container", "parent": { "type": "character", "character": 1, "idx": 15 } } } ], "placement": [ -2147483648, -2147483648, -2147483648 ], "values": [ 0, 1 ], "str_values": [ "" ], "auto_resume": false, "monsters": [  ] } ]`

**Comment by Zireael07** [comment]
All those 21474836(48) look suspicious - it's exactly the max value that fits in an int32, so something is definitely up...

**Comment by EvgenijM86** [comment]
And if you try to save right away after loading with errors then it would also display errors during the save (ensure_unpacked error). More specifically it fails to save "backlog", whatever that means.

```
void Character::store( JsonOut &json ) const
...
    // crafting etc
    json.member( "destination_activity", destination_activity );
    json.member( "activity", activity );
    json.member( "stashed_outbounds_activity", stashed_outbounds_activity );
    json.member( "stashed_outbounds_backlog", stashed_outbounds_backlog );
    json.member( "backlog", backlog );   <----- here
    json.member( "activity_vehicle_part_index", activity_vehicle_part_index ); // NPC activity
```

**Comment by EvgenijM86** [comment]
Here is my save file when I first encountered a save/load error.

[Men of Culture.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6178054/Men.of.Culture.zip)

**Comment by actual-nh** [comment]
Could you compare some saves and see if the "backlog" entry is changing - growing longer, for instance?

**Comment by EvgenijM86** [comment]
When starting the game in the same scenario and saving it on next turn the backlog have zero entries, according to debugger. And empty backglog is not saved in .sav file. So, in my case it have increased from 0 to 2 entries.

**Comment by actual-nh** [comment]
This is a backlog of some variety of actions; I'm wondering if it isn't being properly taken care of and thus keeps getting longer and longer (it can't do it, so it pushes it to the back of a backlog).

I think the position numbers, move numbers, etc are probably from trying to read info regarding a nonexistent/not-indexed-the-same character.

**Comment by EvgenijM86** [comment]
I tried loading my save, pressing num_5 once to pass 1 turn, and:
1) The save error that I encountered previously did not happen. Strange.
2) Here is how the entries changed: https://www.diffchecker.com/IGAi4HUm

**Comment by Paperbell** [comment]
> And the whole things happens inside some "backlog" entry:
> 
> `"backlog": [ { "type": "ACT_EAT_MENU", "actor": null, "moves_left": 21474836, "index": -1, "position": -2147483648, "coords": [ ], "coord_set": [ ], "name": "", "targets": [ { "idx": 0, "type": "in_container", "parent": { "idx": 7, "type": "in_container", "parent": { "type": "character", "character": 1, "idx": 15 } } } ], "placement": [ -2147483648, -2147483648, -2147483648 ], "values": [ 0, 1 ], "str_values": [ "" ], "auto_resume": false, "monsters": [ ] }, { "type": "ACT_EAT_MENU", "actor": null, "moves_left": 21474836, "index": -1, "position": -2147483648, "coords": [ ], "coord_set": [ ], "name": "", "targets": [ { "idx": 0, "type": "in_container", "parent": { "idx": 7, "type": "in_container", "parent": { "type": "character", "character": 1, "idx": 15 } } } ], "placement": [ -2147483648, -2147483648, -2147483648 ], "values": [ 0, 1 ], "str_values": [ "" ], "auto_resume": false, "monsters": [ ] } ]`

I went to my game's SAV file and found something very similar:

`"activity": { "type": "ACT_REPAIR_ITEM", "actor": null, "moves_left": 636, "index": -6, "position": -2147483648, "coords": [  ], "coord_set": [  ], "name": "", "targets": [ { "type": "character", "character": 1, "idx": 68 }, { "idx": 33, "type": "in_container", "parent": { "type": "character", "character": 1, "idx": 130 } } ], "placement": [ -2147483648, -2147483648, -2147483648 ], "values": [ 1 ], "str_values": [ "repair_metal" ], "auto_resume": false, "monsters": [  ] }`

I deleted the entry entirely and it works now.

**Comment by actual-nh** [comment]
> `"activity": { "type": "ACT_REPAIR_ITEM", "actor": null, "moves_left": 636, "index": -6, "position": -2147483648, "coords": [ ], "coord_set": [ ], "name": "", "targets": [ { "type": "character", "character": 1, "idx": 68 }, { "idx": 33, "type": "in_container", "parent": { "type": "character", "character": 1, "idx": 130 } } ], "placement": [ -2147483648, -2147483648, -2147483648 ], "values": [ 1 ], "str_values": [ "repair_metal" ], "auto_resume": false, "monsters": [ ] }`
> 
> I deleted the entry entirely and it works now.

You were in the middle of repairing a cleansuit when the autosave happened, and I note "ACT_REPAIR_ITEM". What stage is the cleansuit repair after removing this?

**Comment by anothersimulacrum** [comment]
There's an invalid tripoint value somewhere, and I am fairly sure it is that triplet posted above.

**Comment by Paperbell** [comment]
> You were in the middle of repairing a cleansuit when the autosave happened, and I note "ACT_REPAIR_ITEM". What stage is the cleansuit repair after removing this?

I just wasn't repairing anything anymore. It's like I stopped without a message, though my cleansuit and soldering iron are still there.

**Comment by Ataman** [comment]
Friend of mine had the same issue on build 11552. Crash on load, identical error messages.
The issue was also resolved by replacing the activity with ACT_NULL inside the save file.

The original activity that caused the crash was as follows:
```json
"activity": {
    "type": "ACT_INSERT_ITEM",
    "actor": {
      "actor_type": "ACT_INSERT_ITEM",
      "actor_data": {
        "holster": {
          "idx": 0,
          "type": "in_container",
          "parent": {
            "type": "character",
            "character": 1,
            "idx": 41
          }
        },
        "items": [
          [
            {
              "idx": 0,
              "type": "in_container",
              "parent": {
                "type": "character",
                "character": 1,
                "idx": 18
              }
            },
            1
          ],
          [
            {
              "idx": 4,
              "type": "in_container",
              "parent": {
                "type": "character",
                "character": 1,
                "idx": 23
              }
            },
            1
          ],
          [
            {
              "idx": 3,
              "type": "in_container",
              "parent": {
                "type": "character",
                "character": 1,
                "idx": 23
              }
            },
            12
          ]
        ],
        "handler": [
          {
            "idx": 0,
            "type": "in_container",
            "parent": {
              "type": "character",
              "character": 1,
              "idx": 41
            }
          },
          {
            "type": "character",
            "character": 1,
            "idx": 23
          }
        ],
        "all_pockets_rigid": false
      }
    }
```
