### ISSUE TITLE
An error when a game update increases a volume of a contained item such that it exceeds the container space

### ISSUE THREAD

**Issue by tsulh** [CleverRaven/Cataclysm-DDA#48141]
# Describe the bug

When loading the game, an error appears on the screen:

```
 DEBUG    : error: item coffee_syrup cannot fit into pocket while loading: item too big

 FUNCTION : void item_contents::combine(const item_contents&, bool)
 FILE     : src/item_contents.cpp
 LINE     : 335
```

I had to press spacebar 3-4 times before the game loaded, but the error message haven't changed (maybe I had several instances of the same error). Then the game appeared to be loaded and functioning normally. 

The error does not appear with commit 15bebba6c4 and appears with commit 9b14c88cf6. The bug is still present with the latest commit 4338567d94.

After I saved, quit and reloaded the game, the error has not appeared anymore.

# Steps To Reproduce

1. Load the attached save with a game version at commit 9b14c88cf6 or later.

# Expected behavior

When an update changes volume of items held in containers or inventories, this does not cause an error message. Instead, either the number of the item charges is reduced to fit the new volume or the container/inventory is able to hold more than it is supposed to if the contents are already inside.

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 10 (buster); Release: 10; Codename: buster; 
- Game Version: 0.E-10118-g4338567d94-dirty [64-bit] and 0.E-10118-9b14c88cf6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6174499/debug.log)
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6174521/save.zip)

**Comment by UmbralReaper** [comment]
This is not a bug; this is intended behaviour. The alternatives (reducing the quantity of an item and temporarily increasing the size of a container) would not only be much harder to implement but be, in many ways, undesirable.

**Comment by tsulh** [comment]
> This is not a bug; this is intended behaviour. The alternatives (reducing the quantity of an item and temporarily increasing the size of a container) would not only be much harder to implement but be, in many ways, undesirable.

OK! What happens to the items currently, are they removed from the game?

**Comment by UmbralReaper** [comment]
They should be dropped on the ground, next to where their container was. If they were nested inside another container, it may also be inside that.

**Comment by tsulh** [comment]
> They should be dropped on the ground, next to where their container was. If they were nested inside another container, it may also be inside that.

So liquids are intended to be "lost", since they're no-pickup?

**Comment by UmbralReaper** [comment]
> So liquids are intended to be "lost", since they're no-pickup?

Well this is actually kind of a special case. It is very rare for liquids to have their volume changed, as most current changes involve `longest_side`. I agree there could be a better alternative for liquid handling, but I doubt it would ever happen as it would be too much work for too little gain.

**Comment by tsulh** [comment]
I agree that this is not very relevant. Rarely losing some liquid at game version change seems to be a very low priority issue... should I close this issue then? Or is it still an open issue because of the potentially lost liquid?

**Comment by UmbralReaper** [comment]
Close it; The issue won't ever be dealt with, and if you don't close it stale bot will.
