### ISSUE TITLE
Unexpected behaviour while tearing the curtains off an open window

### ISSUE THREAD

**Issue by Teacher-Tim** [CleverRaven/Cataclysm-DDA#48149]
# Describe the bug

Crowbarring a window open and then attempting to tear down the curtains from it gives the correct items, but replaces the window tile with a "nothing" tile. Removing curtains from a window that was opened by hand functions as expected. Removing curtains from a window that was crowbarred open, but then closed, functions as expected too.

# Steps To Reproduce

1. Spawn in an evac shelter (any building works, but the shelter start makes it easy to reproduce).
2. Give yourself a crowbar.
3. Go outside and crowbar a window open.
4. Tear down the curtains, either from the inside or from the outside.

# Expected behavior

Working normally.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-10114-gd55d4a1 [64-bit]
- Graphics Version: Tiles
- Game Language: English
- Mods loaded:
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]

**Comment by ama0** [comment]
Same happens when just removing curtains from an open window
