### ISSUE TITLE
Skeletal brute displaced

### ISSUE THREAD

**Issue by DavisBroda** [CleverRaven/Cataclysm-DDA#48157]
# Describe the bug

skeleton brute appears to be be tile higher than it actually is

# Steps To Reproduce

see skeletal brute while using Chibi_Ultica tileset

# Expected behavior

skeletal brute appears in the tile it actually occupies

# Screenshots

![skeleton_brute_displaced](https://user-images.githubusercontent.com/15205060/111893334-6a0b5180-89d8-11eb-9b96-81df24c65cf3.PNG)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-10114-gd55d4a1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

similar to #48053

likely a result of Chibi_Ultica taking some assets from both Ultica and MSX tilesets

pinging @Fris0uman, as he seems to be the one that deals with this sort of error

**Comment by Fris0uman** [comment]
Yep same problem again, int-ua is working on a permanent solution so hoepfully it's the last time we fix one of those. I'll try to fix it today.
