### ISSUE TITLE
Issue with bike rack

### ISSUE THREAD

**Issue by bramblepicker** [CleverRaven/Cataclysm-DDA#48154]
# Describe the bug

Uninstalling bike rack with bicycle mounted leaves bicycle attached to vehicle, can't be unmounted even if you reinstall the bike racks. The vehicle acts as though the bicycle is part of the overall vehicle and needs increased jacking skill to disassemble bicycle from vehicle. Using ^ on bike seat starts vehicle's motor.

# Steps To Reproduce

1. Install bike rack on side of vehicle (RV in this case)
2. Mount bicycle onto vehicle
3. Uninstall bike rack with bicycle still mounted
4. Try to unmount bicycle
5. Reinstall bike rack onto adjacent tiles on vehicle
6. Try to unmount the bicycle
7. Try to drive the bicycle ("Turn on the engine")
8. Try to disassemble bicycle (note jacking quality needed - 6 in my case)

# Expected behavior

I expected the bicycle to automatically become unmounted when the bike racks were uninstalled. I also expected to be able to unmount the bicycle once the bike racks were reinstalled.

# Screenshots

![2021-03-20-160109_1920x1080_scrot](https://user-images.githubusercontent.com/81046539/111884490-54763780-8998-11eb-8341-025a1e268da8.png)

# Versions and configuration

 - OS: Manjaro 21.0 Ornara
 - Game Version: 0.E-9804-gbc7931f
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: None

**Comment by lcy03406** [comment]
Is this a way to install unlimited number of engines?

**Comment by actual-nh** [comment]
Ping: @Jamuro-g?

**Comment by Jamuro-g** [comment]
I am a bit caught up in stuff atm (rl issues) and don't have time to take a good look. 
From what i can recall, i don't think there is code that handles removal of racks yet (only the destruction of bike racks is handled)

I ll be able to take a closer look in a few days

**Comment by Zlorthishen** [comment]
> 
> 
> I am a bit caught up in stuff atm (rl issues) and don't have time to take a good look at the code.
> From what i can recall, i don't think there is code that handles removal of racks yet (only the destruction of bike racks is handled)
> 
> I ll be able to take a closer look in a few days

I've also had transient issues with bike racks, specifically having problems attaching a 3x1 bike to a 5x bike rack. The bike doesn't always want to latch onto the bike rack. I haven't caught it with a screenshot but I'd thought I'd add my two cents. Thank you.

**Comment by actual-nh** [comment]
Ping: @mlangsdorf?
