### ISSUE TITLE
Planted wild vegetable returns error

### ISSUE THREAD

**Issue by jorganmir** [CleverRaven/Cataclysm-DDA#48160]
# Describe the bug

Trying to interact with newly planted wild vegetables is returning an error report, and disappears the wild vegetable.
This does'nt seem to affect other crops.

# Steps To Reproduce

1. Plant wild vegetables
2. Try to interact with the newly planted plant

# Expected behavior

Should return normal messages about fertilizer or lack thereof, and not destroy the young crop.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-10114-gd55d4a1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    No Fungal Monsters [No_Fungi],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

 -->

# Additional context
(continued from above) ERROR : src/iexamine.cpp:2556 [void iexamine::aggie_plant(player&, const tripoint&)] Missing seed for plant at (69, 70, 0)
02:48:21.436 ERROR : src/iexamine.cpp:2556 [void iexamine::aggie_plant(player&, const tripoint&)] Missing seed for plant at (69, 69, 0)
02:48:22.300 ERROR : src/iexamine.cpp:2556 [void iexamine::aggie_plant(player&, const tripoint&)] Missing seed for plant at (68, 70, 0)
02:48:23.067 ERROR : src/iexamine.cpp:2556 [void iexamine::aggie_plant(player&, const tripoint&)] Missing seed for plant at (68, 69, 0)
02:48:24.516 ERROR : src/iexamine.cpp:2556 [void iexamine::aggie_plant(player&, const tripoint&)] Missing seed for plant at (70, 61, 0)
02:48:48.358 ERROR : src/map.cpp:1448 [std::__cxx11::string map::furnname(const tripoint&)] Missing seed for plant at (69, 61, 0)

**Comment by jorganmir** [comment]
Okay, upon further playing around and research, it appears that the issue comes from using seeds in stockpiles. Seeds from your own inventory are fine, if you carry the seeds on your person, but if the seeds are grabbed from a seed stockpile, then it gives an error, presumably because of making a seedless crop.

**Comment by hexagonrecursion** [comment]
@jorganmir Could you please clarify what yo mean by "stockpile"? Do you mean a "Loot: seeds" zone?

**Comment by jorganmir** [comment]
> @jorganmir Could you please clarify what yo mean by "stockpile"? Do you mean a "Loot: seeds" zone?

Yes, sorry. However, I haven't experienced this bug since.

**Comment by hexagonrecursion** [comment]
Could not reproduce
1. Create a loot: seeds zone
2. Dump 10 wild vegetable stems in it
3. Create a farm: plot zone configured to plant wild vegetables
4. Do zone activities
5. Press e near the planted wild vegetables
6. See the expected message about missing fertilizer

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 86ff040 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]
