### ISSUE TITLE
[Magiclysm] Totem of Calling (Attracts summoned creatures)

### ISSUE THREAD

**Issue by Termineitor244** [CleverRaven/Cataclysm-DDA#48177]
# Is your feature request related to a problem? Please describe.
The summoned monsters are hard to use because you cannot give them orders, take for example a zombie, given the casting time you should be summoning it before entering a battle, but you must guide it to the enemies or it could end up hunting a rabbit.

# Describe the solution you'd like
A new, classless spell, let's call it "Totem of Calling" or whatever, with a decent range (increased by level) that just makes the allied summoned creatures feel attracted to the location you select as the spell's objective (for a set amount of time until the "totem" disappears), that way you can make your summons before a battle and make them start fighting without having to actually get close yourself, or, if you are being followed, you can make your summon go in a different direction that yourself and stay there, to attract the enemies to it and give you time to escape.

Edit: The actual spell could look something like this:

```
id": "calling_totem",
    "type": "SPELL",
    "name": "Totem of Calling",
    "description": "This spell generates a magical totem that constantly calls your summoned creatures, attracting them to that location until it disappears or a new totem is conjured.",
    "valid_targets": [ "ground" ],
    "flags": [ "LOUD", "SOMATIC", "VERBAL", "NO_LEGS", "NO_PROJECTILE" ],
    "effect": "summon",
    "effect_str": "calling",
    "shape": "blast",
    "base_casting_time": 100,
    "base_energy_cost": 10,
    "energy_source": "MANA",
    "difficulty": 2,
    "max_level": 20,
    "min_damage": 1,
    "max_damage": 1,
    "min_range": 15,
    "max_range": 35,
    "range_increment": 1.0,
    "min_duration": 500,
    "max_duration": 1500,
    "duration_increment": 50,
  }
```

The problem is with the "calling" part, since, as far as I know, attracting a creature would need some changes in `monster::plan()` that I don't know how to do, that and specify that a given creature is summoned (and because of that, affected by this spell) so you do not end up calling all the zombies in the city. Given the work in #48155 this spell could use something similar, but again, this is outside of my capabilities.

# Describe alternatives you've considered
To guide them with basic commands? Or maybe to make one Calling spell for every class with summons, and only attract the monsters summoned by that class, but that would be more difficult.

# Additional context
I think that the concept of guiding your summoned creatures, one way or another, should be implemented in the game to help with the usefulness of summoned creatures, since it will open a whole new world of possibilities and stories in the game.

This will also help to give more life to the druid and animist classes.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
