### ISSUE TITLE
Hardware rendering of text is very slow

### ISSUE THREAD

**Issue by DarkDaskin** [CleverRaven/Cataclysm-DDA#48179]
# Describe the bug

Recent experimental builds have very low frame rates when a lot of text is shown on the screen. Most notable slowdown is on the overmap, which is completely filled with characters.

With the default `direct3d` renderer, redrawing the overmap takes around 2 seconds, which results in slow scrolling and text input. `opengl` renderer performs the same way, while with `direct3d11` overmap redraws in about 1 second. `software` does not introduce any noticeable redraw delay.

In the latest stable build (0.E-3) all renderers work without noticeable delay.

# Steps To Reproduce

1. Load any game and open the overmap.
2. Hold the arrow keys or try to add a new note and enter a lot of text.

# Expected behavior

All renderers work equally fast just as in stable build.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-10055-gb7e1cd5 [64-bit]
- Graphics Version: Tiles
- Game Language: Системный язык []
- Mods loaded: [
    Тёмные Дни Впереди [dda]
]

# Additional context

I have AMD Radeon RX 580 with driver version 27.20.1034.6.

**Comment by GGgatherer** [comment]
Never had this problem but I'm on nvidia. Try updating to latest experimental, maybe? And what about English language, does it lag too?

**Comment by DarkDaskin** [comment]
In tiles mode I get 15 FPS in experimental and 19 FPS in stable. In ASCII mode I get 4 FPS in experimental and 8 FPS in stable. That is for main game screen, I can't open debug menu while browsing overmap.

Switching to English makes no difference.

There were some changes in the engine related to font handling. After I updated the game (last played around a year ago), I got errors about configuration JSON parsing, that is the time I deleted my configs, got a new font and performance problems.

**Comment by DarkDaskin** [comment]
Switching to built-in Intel graphics makes it even worse, down form 25 FPS to 18. The numbers are different this time because I made game window smaller as built-in graphics does not support full resolution of my display. Numbers in previous comment are for playing full screen, which is 3440x1440.

**Comment by BrettDong** [comment]
This is probably a Windows specific issue. I get solid 60 FPS in full screen (2560x1600) in both tileset and ASCII mode on macOS with M1, regardless of the choice of renderer being software, OpenGL or Metal.

**Comment by ZhilkinSerg** [comment]
> 
> 
> This is probably a Windows specific issue. I get solid 60 FPS in full screen (2560x1600) in both tileset and ASCII mode on macOS with M1, regardless of the choice of renderer being software, OpenGL or Metal.

Did you compile by yourself? Which SDL version did you use?

**Comment by BrettDong** [comment]
> Did you compile by yourself? Which SDL version did you use?

May I try updating SDL libraries on Jenkins build server and see if it helps?

**Comment by ZhilkinSerg** [comment]
> 
> 
> > Did you compile by yourself? Which SDL version did you use?
> 
> Yes, self-compiled by `make TILES=1 RELEASE=1`, SDL library version 2.0.14.

There is batch rendering on more recent SDL versions which could help (`SDL_HINT_RENDER_BATCHING`) while precompiled Windows versions do not have it - they still use SDL 2.0.5.

**Comment by ZhilkinSerg** [comment]
Try this binary in your game folder (make savegame backup first) - [Cataclysm-vcpkg-static-Release-x64-0.E-10144-g68ae0abd0a-dirty.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6184378/Cataclysm-vcpkg-static-Release-x64-0.E-10144-g68ae0abd0a-dirty.zip) and see if it is running any faster. Especially with using this new option enabled:

![image](https://user-images.githubusercontent.com/16213433/112037329-ad89cb00-8b52-11eb-914c-bb27a109b857.png)

**Comment by DarkDaskin** [comment]
I was running official builds. Tried to compile it myself and it ran a lot faster (as fast as @ZhilkinSerg build, 33 FPS in benchmark), disabling render batching made it slower, but not as slow as official build. Now I get few FPS on the overmap, but it still feels somewhat slower than stable.

**Comment by DarkDaskin** [comment]
Installed a FPS monitor, so here are specific numbers on the overmap: 

- Stable (official): 18 FPS
- Experimental (official): 2 FPS
- Custom: 6 FPS

**Comment by DarkDaskin** [comment]
Compiled `0.E-branch` against the same libs (SDL is `2.0.14#3` from vcpkg) and got 30 FPS on the overmap.

**Comment by ZhilkinSerg** [comment]
Profile both builds and see what's eating CPU.

**Comment by DarkDaskin** [comment]
I have performed `git bisect` and found that the problem is caused by addition of https://github.com/CleverRaven/Cataclysm-DDA/blob/894002bd18a9be3d38442913f4db79391916a15e/src/sdltiles.cpp#L604-L607

Apparently this should _Fix overmap UI not redrawing correctly after slight resizing_  (#46768), but is missing a check and needlessly invalidates whole screen multiple times every frame. Even though that issue is minor, I was able to reproduce it with the lines removed, so I will spend a bit more time and try to make a PR with a proper fix.
