### ISSUE TITLE
Shakes effect will not go away after kicking heroin addiction

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#48171]
# Describe the bug

After the addiction to heroin goes away, the "Shakes" effect remains, seemingly permanently.

# Steps To Reproduce

1. Start a new character as "Heroin addict"
2. Find a safe place, debug-spawn in some food and water, and wait 3-4 days until the addiction is gone
3. Keep waiting for some days - "Shakes" effect remains

# Expected behavior

After getting rid of the addiction, the "Shakes" effect should go away as well.

# Screenshots

Shakes effect, giving -1 STR and -4 DEX:

![image](https://user-images.githubusercontent.com/238395/111917243-98267b00-8a44-11eb-8d7e-5dc32a597664.png)

There are no messages in the log about ongoing effects, but my stats remain debuffed indefinitely.

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-10120-g3a8df30748 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

Reported by discord user "i will bring up 1984", confirmed by me.

Save game with permanent "Shakes", about 2 days after kicking the addiction:
[PermanentShakes.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6178113/PermanentShakes.zip)

**Edit** By turning on debug mode, I see that the "Shakes" duration is set to 2 weeks and 5 days:

![image](https://user-images.githubusercontent.com/238395/111917703-1126d200-8a47-11eb-8272-87b0a32fa044.png)

so it appears that the effect has accumulated during the time I was in withdrawal from addiction, and still needs to play out for another few weeks before it will go away on its own.

**Comment by anothersimulacrum** [comment]
The duration was capped in  - #51250
