### ISSUE TITLE
Looking at drugs in advanced inventory makes you take them

### ISSUE THREAD

**Issue by OromisElf** [CleverRaven/Cataclysm-DDA#48183]
# Describe the bug

When you open the details of a drug (e), that's inside of our inventory, through the advanced inventory screen, hitting enter to close the details window takes the drug instead.

# Steps To Reproduce

1. have a drug in your inventory (like codeine)
2. open the advanced inventory with your Inventory (I) on one side and wherever on the other side (tested with All (A))
3. open the details of the drug with e
4. hit enter to close the details window

# Expected behavior

Just close the details screen or at least put the drug where the other advanced inventory screen is pointing to.

# Versions and configuration

(mods shouldn't matter but if they do hit me up I can provide links to all of them)

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-10111-g5ca62e7 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Battle Maid Redux [battle_maid],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Advanced Gear Goats Edition [adv_gear],
    Resource Crops for Advanced Gear [resource_cropsAdvGear],
    Armor Up! Survivor Expansion [ArmUpSurvEx],
    Pixel's Various Fuckery [Pix's Shit],
    DinoMod [DinoMod],
    Hydroponics [hydroponics],
    machine [machine],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Mythical Martial Arts [MMA],
    Tankmod: Revived [Tankmod_Revived],
    Necromancy [necromancy],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    Plant Crops [resource_crops_plants],
    Portable Autodoc [portable_autodoc],
    Resource Crops [resource_crops],
    Resource Crops for Magiclysm [resource_cropsMagic],
    Safe Portable Autodoc [safe_portable_autodoc],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Resource Crops for Aftershock [resource_cropsAfter],
    Advanced Gear - UndeadPeople Tileset [adv_gearUDP],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Armor Up! Survivor Expansion - UndeadPeople Tileset [ArmUpSurvExUDP],
    Battle Maid Redux - UndeadPeople Tileset [battle_maidUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    DinoMod - UndeadPeople Tileset [DinoModUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    My Sweet Cataclysm - UndeadPeople Tileset [My_Sweet_CataclysmUDP],
    Tankmod: Revived - UndeadPeople Tileset [Tankmod_RevivedUDP],
    Bootleg Walkers [Bootleg_Walkers],
    Bootleg Walkers - UndeadPeople Tileset [Bootleg_WalkersUDP]
]

**Comment by wapcaplet** [comment]
When using `e` to examine an item in the advanced inventory screen, the action menu is also displayed, with `a`ctivate highlighted. Pressing Enter in this menu chooses the one you have highlighted. If you want to exit this menu without doing anything, using Escape is more appropriate. I don't know of any context in game where pressing Enter means "cancel".

**Comment by OromisElf** [comment]
I completely didn't notice that menu :D
But concerning the "I don't know where enter closes something"; nowhere I was just under the impression the description window is one of those "press any key" deal (which it seems to be for items on the ground)

**Comment by Night-Pryanik** [comment]
Not a bug.
