### ISSUE TITLE
[Magiclysm] "task is too simple to train spellcraft" log spam while reading spellbooks

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#48182]
# Describe the bug

When leveling up spells, if this process cannot raise your spellcraft level you get bombed by *exactly the the same* messages which aren't collapsed into "\<message\> x N" for some reason. Or sometimes they are but it is only x2 and sometimes x3, never higher than that.

# Steps To Reproduce

spawn scroll of haste, set your spellcraft to 11, start reading the scroll

# Expected behavior

Collapse same messages.

# Screenshots

![cataclysm-tiles_2021_03_22_22_14_10_939](https://user-images.githubusercontent.com/56833396/112013701-d3b46880-8b5c-11eb-8b13-7edb8d504b5e.png)

# Versions and configuration

- OS: Windows 7
- Game Version: 0.E-10134-g9b256f6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills],
    Bionic Professions [package_bionic_professions],
    Ye olde Aftershock vehicle parts [afs_veh_goodies]
]

**Comment by MarlossCDDA** [comment]
Looks like a side effect of https://github.com/CleverRaven/Cataclysm-DDA/pull/48021.

**Comment by GGgatherer** [comment]
Now I have a question: how the hell "message cooldown" parameter is supposed to work? It says it's a period (in game turns) that similar messages aren't shown.
What I assumed:
- messages go into queue
- if they are the same, they are bunched into a pile with nX 
- if we get another message during the "cooldown period", we will see pile of previous messages of whatever size it was at the time new message got in, plus the new message, and the cycle restarts.
- when the period ends we get the bunch anyway, and the cycle restarts (even if messages are the same, we get to see them all, just bunched in different size piles)

Instead, if I set the cd to quite a high number (>500 or about so, but even that is not nearly enough to be longer that reading time), it does not show *any* "task is too simple" messages at all. Yes, none at all. And when I start lowering it, messages begin to appear but there's way less of them then at my default value of 8. What's the logic behind it, if there's any?

**Comment by actual-nh** [comment]
Ping: @KorGgenT?

**Comment by GGgatherer** [comment]
Looks like it's fixed? Can't repro with cooldown of 100 in 15dd993.

**Comment by actual-nh** [comment]
Does the high-number thing (no messages at all with 500+ cooldown) still happen?
