### ISSUE TITLE
Meaning-distorting translation errors into Russian (no main)(experemental)

### ISSUE THREAD

**Issue by mrshockost** [CleverRaven/Cataclysm-DDA#48196]
_I noticed a crooked translation in the tips of the day_
I am sad for the Russian translation

**Comment by ZhilkinSerg** [comment]
Translation are handled via Transifex - https://www.transifex.com/cataclysm-dda-translators/cataclysm-dda/. Please make amendments there.

See https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/TRANSLATING.md for more details.

**Comment by CountAlex** [comment]
@mrshockost If you can give me a screenshot, I will fix it right away.
