### ISSUE TITLE
Science Lab Tower turrets don't despawn when opening the shutters with a Science ID Card

### ISSUE THREAD

**Issue by SolidMilk19** [CleverRaven/Cataclysm-DDA#48198]
# Describe the bug

When you open the shutters to a Science Lab Tower with a Science ID Card (hacking it probably also does the same thing but I didn't try that out), the two Riot Control Platforms behind the door will be right there to greet you with open arms and a couple of bullets to the face.

# Steps To Reproduce

1. Find an Office Tower and pray to whatever entity you believe in that there's a Science Lab Tower in there. Find the entrance and bring a Science ID Card. Alternatively, just load the provided save file.
2. Swipe your card at the (hopefully intact) card reader.
3. Open the door and get shot in the chest, then limp away injured and confused. Getting mauled by the horde you didn't clear out in anticipation of sweet, sweet loot is optional but highly encouraged.

# Expected behavior

The turrets should despawn like they do when you open a regular Science Lab with an ID card. The danger of getting shot should be the price you pay for skipping the card reader and breaking in by force.

# Screenshots

![01](https://user-images.githubusercontent.com/68878873/112199310-52b5a980-8c0e-11eb-87a2-42a1203d4c11.PNG)
![02](https://user-images.githubusercontent.com/68878873/112199354-5f3a0200-8c0e-11eb-9704-7e14199f985d.PNG)

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-10134-g9b256f6
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: dda, no_npc_food, package_bionic_professions
 

# Additional context

Save File: [Three Springs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6192005/Three.Springs.zip)

**Comment by OliveChukar** [comment]
Tested on 0.E-10188-gd02fc13 with Dark Days Ahead [dda] only no mods. Had the same result as report.Opened door with card and was shot by riot turrets. Standard labs would have the turrets despawn when card is used to unlock the entrance door. Standard lab turrets do not despawn when the doors are unlocked with an electrohack and the lab tower is the same.

 Possibly unrelated but I spawned a heavy exoskeleton suit and helmet for the test I was still stunned by the turrets shots but did not lose hp. The exoskeleton mostly makes you indestructible so being stunned by something intended for use on unprotected humans seems odd.

**Comment by actual-nh** [comment]
> Possibly unrelated but I spawned a heavy exoskeleton suit and helmet for the test I was still stunned by the turrets shots but did not lose hp. The exoskeleton mostly makes you indestructible so being stunned by something intended for use on unprotected humans seems odd.

It depends on how much physical impact the munitions are designed to have. Riot control ammo tends to be big on knocking people back/down while trying to avoid too much impact on any one spot. Having the helmet slammed against your head, even if not penetrated, could quite reasonably stun (although one could argue bracing against the exoskeleton should limit such).

**Comment by OliveChukar** [comment]
I think the exoskeleton is intended to be something like power armor in the fallout games.The helmet is connected to the body and it is probably rigid enough to stop most blunt impacts from affecting the user. However it is probably not worth adding a special armor quality just so a few types of rare super heavy armor can resist attacks from a rare type of robot.

**Comment by actual-nh** [comment]
@BrettDong: Confirmed as a bug, I think.

**Comment by anothersimulacrum** [comment]
Are those the less-than-lethal turrets? They may need the `ID_CARD_DESPAWN` flag.
