### ISSUE TITLE
JSONize + rework (mod-used) shock absorber CBM

### ISSUE THREAD

**Issue by actual-nh** [CleverRaven/Cataclysm-DDA#48199]
# Is your feature request related to a problem? Please describe.
This is in response to @Fris0uman's request in #48186.

The shock absorber CBM needs JSONizing if it is to continue being used in mods... and also reworking heavily to be more realistic than the current description. (For instance, no decrease in stored calories, if fat was replaced, or strength/dexterity if muscle, etc was?)

# Describe the solution you'd like
I can see a few possibilities:
- Make it a boost to the Subdermal Carbon Filament (and characters without that would get it instead), making it impact armor - stiffening in response to impact. (This would mean it should also give a bit of a boost vs bullets, BTW.) Admittedly, the Carbon armor does have the realism problem that your skin would still get damaged, so it shouldn't be reducing damage to zilch.
- I suppose it could just maybe be some sort of foam padding inserted between your skin and hypodermis, possibly with impact armor characteristics, although it would not be switchable, would give some continuous encumbrance, and like the above wouldn't be able to stop all damage. 
- Given that both of the mods using it (Aftershock and Dark-Skies-Above) have weird tech available of various sorts, it could be something that used power (force field?) to slow down impacts or something like that.

# Describe alternatives you've considered
It getting removed entirely?

If mod maintainers really like how it's currently described, the rework could be limited to JSONizing it.

**Comment by Mom-Bun** [comment]
Pretty sure the fact that both aftershock and Dark Skies Above use it is due to just well, legacy code and it being CBMs

I'll defer to Candlebury and Maleclypse if we should keep the shock absorber CBM in aftershock however.

**Comment by actual-nh** [comment]
> Pretty sure the fact that both aftershock and Dark Skies Above use it is due to just well, legacy code and it being CBMs
> 
> I'll defer to Candlebury and Maleclypse if we should keep the shock absorber CBM in aftershock however.

Understand. Oh - Ping: @Night-Pryanik - you had objected to removing it from vanilla. I'd like to hear from you on this.

**Comment by kevingranade** [comment]
It seems likely that even if Aftershock or DSA wants something *like* this, it's not going to actually be shock absorbers or padding popping out of the user's body, which is neat as that might sound is incredibly far out on the "can't possibly work" scale of things.

**Comment by Mom-Bun** [comment]
> It seems likely that even if Aftershock or DSA wants something _like_ this, it's not going to actually be shock absorbers or padding popping out of the user's body, which is neat as that might sound is incredibly far out on the "can't possibly work" scale of things.

Replacing your legging with springs and pillows sounds incredibly silly, I talked with maleclypse and we figured we'd use feather fall spell for it, and flavor it as a gravity chute, so yeah you are right.

**Comment by actual-nh** [comment]
> It seems likely that even if Aftershock or DSA wants something _like_ this, it's not going to actually be shock absorbers or padding popping out of the user's body, which is neat as that might sound is incredibly far out on the "can't possibly work" scale of things.

Anyone know a clockpunk/steampunk game where this could fit?

**Comment by Night-Pryanik** [comment]
I objected because I don't like content being removed rather than reworked, especially if this content doesn't interfere with something or interrupt something or get in the way for anyone for so long, especially if this content was merged by project leader himself.

**Comment by EvgenijM86** [comment]
Shock Absorber CBM can be a combination of 2 things: brain implant that will automatically control your muscles to rotate your body in mid air to land on your legs, and modified legs that are more suited for jumping and landing.

Removing end game content is not a good development direction, because cdda already lacks in end game content.

**Comment by actual-nh** [comment]
> Shock Absorber CBM can be a combination of 2 things: brain implant that will automatically control your muscles to rotate your body in mid air to land on your legs, and modified legs that are more suited for jumping and landing.

Another reasonable alternative.

> Removing end game content is not a good development direction, because cdda already lacks in end game content.

Point.

**Comment by Mom-Bun** [comment]
> Shock Absorber CBM can be a combination of 2 things: brain implant that will automatically control your muscles to rotate your body in mid air to land on your legs, and modified legs that are more suited for jumping and landing.
> 
> Removing end game content is not a good development direction, because cdda already lacks in end game content.

The project is open source; if you feel end game is lacking end game content, there is nothing stopping you from [forking and setting up your workflow](https://github.com/CleverRaven/Cataclysm-DDA/wiki/Guide-to-setup-git-locally) and [contributing some](https://github.com/CleverRaven/Cataclysm-DDA/wiki/Guide-to-adding-new-content-to-CDDA-for-first-time-contributors) except yourself, patience, and the ability to work in a team.

**Comment by EvgenijM86** [comment]
> > Shock Absorber CBM can be a combination of 2 things: brain implant that will automatically control your muscles to rotate your body in mid air to land on your legs, and modified legs that are more suited for jumping and landing.
> > Removing end game content is not a good development direction, because cdda already lacks in end game content.
> 
> The project is open source; if you feel that the game is lacking end game content, there is nothing stopping you from [forking and setting up your workflow](https://github.com/CleverRaven/Cataclysm-DDA/wiki/Guide-to-setup-git-locally) and [contributing some](https://github.com/CleverRaven/Cataclysm-DDA/wiki/Guide-to-adding-new-content-to-CDDA-for-first-time-contributors) except yourself, patience, and the ability to work in a team.

I did exactly that - my local copy of CDDA has this and some other stuff reverted.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
