### ISSUE TITLE
Finger Lighter bionic cannot be used to fire charcoal kiln, smoking rack and molotov cocktail

### ISSUE THREAD

**Issue by gogo1704** [CleverRaven/Cataclysm-DDA#48193]
# Describe the bug

I'm unable to fire filled rock charcoal kiln, smoking rack and Molotov cocktail with Finger Lighter bionic.

# Steps To Reproduce
All test were made with "Bionic Prepper" profession and Bionic Power: 250kJ/250kJ 

Charcoal Kiln:
1. Construction -> "Build Charcoal Kiln"
2. Fill it with Logs
3. Pressing "Examine" key ("e") and selecting the kiln opens the pickup menu

Smoking Rack:
1. Construction -> "Build Smoking Rack"
2. Examine the rack and Reload with charcoal...
3. Examine the rack and Insert food for smoking...
4. Examining and selecting "Light up and some food" option shows a message: "This smoking rack is ready to be fired, but you have no fire source.".

Molotov cocktail:
1. Take Molotov cocktail into inventory
2. Activate ("a") the Molotov cocktail ("Light rag")
3. Message says: "You need a source of fire!"

# Expected behavior

Charcoal Kiln:
Instead of pickup menu it should show a confirmation box to fire the kiln.

Smoking Rack:
It should show a confirmation box to fire the smoking rack.

Molotov cocktail:
It should light the Molotov cocktail.

_I believe "Finger Lighter" bionic should be able to do those things because it's possible while having normal Lighter in inventory._

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.E-2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

**Comment by Ramza13** [comment]
It's possible that #47694 will fix this as it should make the bionic more like a standard fire starting tool.
