### ISSUE TITLE
Can't use smartphone to check the time.

### ISSUE THREAD

**Issue by vipches** [CleverRaven/Cataclysm-DDA#48204]
Pc version: 11541

Unable to check the time with smartphone.

Screenshot:
![QQ图片20210324173848](https://user-images.githubusercontent.com/6611199/112288606-79d0b180-8cc8-11eb-8865-cf9d5152cb69.png)
![QQ图片20210324173859](https://user-images.githubusercontent.com/6611199/112288612-7b9a7500-8cc8-11eb-98e0-c0ba904f81f5.png)

save file:
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6196535/save.zip)

**Comment by ZhilkinSerg** [comment]
Are you using any mods?
