### ISSUE TITLE
Rail Laser Sight mod does not change stats of the gun.

### ISSUE THREAD

**Issue by EvgenijM86** [CleverRaven/Cataclysm-DDA#48200]
# Describe the bug

Rail Laser Sight mod does not change stats of the gun, other than weight.

# Steps To Reproduce

1. Make a player with a gun, magazine, some ammo and give him Rail Laser Sight gun mod.
2. Try to install Rail Laser Sight gun mod.
3. The before/after screen that show changes will list no changes other than weight increase.

# Expected behavior

Some stats become better.

# Screenshots

![Rail Laser Sight](https://user-images.githubusercontent.com/430076/112214845-952fb400-8c17-11eb-83f0-821ba233e5e7.png)

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 20.2.1; Codename: Nibia; 
- Game Version: 0.E-10173-gb991a1bab2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

I have tried it with 3 different guns: M4A1, AR-10, AK-74M and result is the same.

**Comment by Hirmuolio** [comment]
Guns by default have sight dispersion of 30 without any weapon mods installed.

So if the sight has dispersion of 30 or higher then they will not do anything. Rail laser sight has sight dispersion of 30.

The aim speed from the rail laser may still apply. That value is not visible ingame and the base value for weapons hardcoded somewhere in c++.

AFAIK the only exception to this is if the gun has some mod with ´"DISABLE_SIGHTS"´ flag. That one causes the gun base sight dispersion to increase.

**Comment by EvgenijM86** [comment]
I see. So it's not a bug.

**Comment by l29ah** [comment]
I have installed rail laser sight, and the `Precise Aim` of my `M4 carbine` is still `317 moves` on todays master, just like with the base weapon. I couldn't verify if the actual amount of time being spent is different, as it seems like it gets rounded to seconds in `Check game state` debug menu knob.
