### ISSUE TITLE
Fur doesn't give warmth to arms and legs

### ISSUE THREAD

**Issue by KittyTac** [CleverRaven/Cataclysm-DDA#48213]
# Describe the bug

Fur mutations do not give warms to arms and legs.

# Steps To Reproduce

1. Make a character,
2. Debug in a fur mutation.
3. Wait a turn.
4. Press @ and look at warmth.

# Expected behavior

It warms the entire body.

# Screenshots

 
![image](https://user-images.githubusercontent.com/52408044/112433134-667b2000-8d74-11eb-95ed-d1989cc192ca.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-10097-ga6ea001 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Kittymod [kittymod],
    Tankmod: Revived [Tankmod_Revived],
    Tankmod: Revived - UndeadPeople Tileset [Tankmod_RevivedUDP]
]

# Additional context

Kittymod is my mod that I'm making, it doesn't change anything related to mutations so no way it's affecting this.

**Comment by ZhilkinSerg** [comment]
What's the state of your character limbs? Are they damaged?

**Comment by KittyTac** [comment]
> What's the state of your character limbs? Are they damaged?

Undamaged.

**Comment by OliveChukar** [comment]
Tried to reproduce on 0.E-10188-gd02fc13 with Dark Days Ahead [dda] and no mods. Following the steps in the report fur mutations gave the same warmth to all parts. I made sure to drop all clothing for the test and try several different mutations.

Need either more detail about how to make the problem happen or a copy of the save.

**Comment by hexagonrecursion** [comment]
Could not reproduce.

![fur](https://user-images.githubusercontent.com/52621858/129193414-ca54e129-5d98-46b0-99a4-0615b4d29a90.png)


I can not find a mutation called "fur" is this something added by kittymod, Tankmod_Revived or Tankmod_RevivedUDP?

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: cb86201 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by actual-nh** [comment]
> I can not find a mutation called "fur" is this something added by kittymod, Tankmod_Revived or Tankmod_RevivedUDP?

The "fur" mutations were what were mentioned, I think - either that, or "Furry" (id "FUR") is what was meant. But checking "Shaggy Fur" should be sufficient.
