### ISSUE TITLE
Game is slower on builds above build 11537 

### ISSUE THREAD

**Issue by DillonSimeone** [CleverRaven/Cataclysm-DDA#48223]
# Describe the bug
Eating dried fruits, sleeping and crafting among other actions in the game now seems to take longer to render to the screen. 

It appears that everything now takes one second in real life per action/updates... For example, eating dried fruit takes 20 seconds, but will now take one second to finish in real life while previously it went by in a blink.

Crafting updates each five minutes, and appears to also takes one second in real life each update.

Sleeping updates each 30 minutes, same problem as above.

I've tried other render settings, as noted below:

Render batching is enabled. Direct3d is default render. Testing by eating the same dried fruit, which takes 20 seconds.

Opengl... Slower.
Opengel2... No change from default.
Software... Laggy? Slower.
Direct3d11... No change from default.

# Steps To Reproduce

1. Make a player
2. Spawn in dried foods, crafting materials
3. Eat stuff. Craft stuff. Time the time it takes for the game to become responsive again between updates.

# Expected behavior

Sleeping, eating and crafting to pass by faster in real time, because that was how it was in build 11537.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-10188-gd02fc13 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Crazy Cataclysm [crazy_cataclysm],
    Mining Mod [Mining_Mod],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Mythical Martial Arts [MMA],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Kills [stats_through_kills]
]

# Additional context

[Uncas.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6209241/Uncas.zip) If you want to use my save, load up McDonald, he's standing on a pile of foods that you can use to test this out.

**Comment by ZhilkinSerg** [comment]
Both versions looks to work at the same speed for me in your save.

Please send your `config` folder.

**Comment by DillonSimeone** [comment]
[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6211108/config.zip) Here you go. 

Odd. I filed this bug report only after hearing that several other players on the discord was noticing the same slowdowns. You can see anothersimulacrum replying to players that mentioned slowdowns in the discord here: https://discord.com/channels/598523535169945603/598523535169945607/824848082582634527

Maybe this is related to our CPUs? I'm not sure what theirs are, but mine is an AMD 3600xt cpu on stock settings.

**Comment by DillonSimeone** [comment]
Dragged my config folder out of my game, then loaded the save up... Still seemed to be lagging between each actions/updates. Odd. 

I rolled back to 11537, and can say for 100% sure that it's running much faster while eating the dried fruits off the ground, crafting and sleeping. On 11543, when I eat, I can see 5%, then 55%, then 100%, and finally, control is given back to me. On 11537, I only see 5% flashing before the fruit is consumed completely.

**Comment by DillonSimeone** [comment]
Build11537 recording: https://www.youtube.com/watch?v=AA6UUJ0hYO8
Build 11543 recording: https://www.youtube.com/watch?v=KkqS15h8tl4

Now that I have them side by side... They look the same! Maybe rolling back to 11537 then forward again to 11543 fixed the mystery lag. >.> Need inputs from the other affected players, pinging them to add to this.

**Comment by RDru** [comment]
It's way slower on my save:
[11537_test.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6211593/11537_test.zip)

1. Load the save on 11537 and eat ketchup (it's in inventory so it will be first on eating menu).
2. Update the game to 11543 and repeat.

I have old i5 (but overclocked) and it takes less than 1s on 11537 (it's not instant but still fast).
On 11543 it takes almost 3s. It feels really slow.

**Comment by wapcaplet** [comment]
Reported on Reddit as well: https://www.reddit.com/r/cataclysmdda/comments/mdopud/latest_experimental_11543_noticeable_game_lag/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

**Comment by DillonSimeone** [comment]
WHOA. I just updated to 11544 from 11543, and it's way slower! Moving even across an empty map is much more sluggish than before. Bad enough that I'm rolling back to 11543 now. Tempted to go all the way back to 11537, but those updates... >.<

https://www.youtube.com/watch?v=YKTlMa-g3uw

You can see the lag getting really nasty when I go south a bit closer to my camp.

**Comment by DillonSimeone** [comment]
Someone pointed out that my videos was set to private. Fixed the settings, they're unlisted videos now. You should be able to view them now.

**Comment by Cpl-Jordan** [comment]
I was about to make a post and saw that this one was already open. Build 11544 is much slower compared to 11537. Moving your character is much more slower. Driving seems to show it much better then walking. What does show it the best is using the SHIFT+E to show the eat menu. For me it takes up to 15-25 seconds for the menu to open up and between eating portions of food it takes another 15-25 seconds. Ill send my save over of my current world that has this problem. If you use my save try and open the quick eat menu he is already in his (Food Horded) kitchen.

Save: [Chemult.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6214880/Chemult.zip)

**Comment by Tommy-os** [comment]
I can confirm this issue makes the game unplayable for me if I update to latest experimental due to the massive slowdown.

My current info dump:

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-10088-g74e26ac [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by actual-nh** [comment]
@Night-Pryanik: This would appear to be confirmed (I noticed you doing labeling).

**Comment by actual-nh** [comment]
> Both versions looks to work at the same speed for me in your save.

(From ZhilkinSerg) Then I have to wonder if it's the SDL "update" on the build machine.

**Comment by actual-nh** [comment]
@ZhilkinSerg: From your message on the SIGILL issue, has the SDL "update" (I place in quotes because I am dubious about it being any improvement, to say the least) been undone on the build machine?

**Comment by ZhilkinSerg** [comment]
Yeah - you can check SDL versions used in `debug.log` after starting app.

**Comment by actual-nh** [comment]
> Yeah - you can check SDL versions used in `debug.log` after starting app.

Hopefully useful for others (I use curses on a Mac); thanks!

**Comment by DillonSimeone** [comment]
> 
> 
> Yeah - you can check SDL versions used in `debug.log` after starting app.

I see... Now that the SDL is rolled back, which you mentioned in #48307, I've updated to build 11552 and don't see any FPS issues now.

Should this issue be closed?
