### ISSUE TITLE
Invisible worms

### ISSUE THREAD

**Issue by OliveChukar** [CleverRaven/Cataclysm-DDA#48237]
Burrowing creatures that are stuck on ground they cannot burrow into are not visible.

# Steps To Reproduce

Option 1
Use provided save.
Walk east/right.
Run into unseen and immobile graboid.

Option 2
Spawn a vehicle with a cargo are separate from the driver seat.
Drive over dirt.
Spawn burrowing creatures in the cargo area.
Drive onto a road.
The creatures should be stuck but not visible.

Option 3
Drive a vehicle on dirt toward a road.
When you are a few tiles from the road spawn several burrowing creatures in the dirt next to the road.
Ram the creatures.
Some of the creatures should be pushed onto the road and become stuck.
Notice that the creatures are still hidden.

# Expected behavior

I think that burrowing creatures not being visible represents them being hidden because they are underground.
If a burrowing creature ends up on a surface that it cannot burrow into it should be visible.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-10210-geedb52d [64-bit]
- Graphics Version: Tiles
- Game Language: System language [english]
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context
[save giant worm.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6215816/save.giant.worm.zip)

**Comment by actual-nh** [comment]
Just in case, can you check if turning fov_3d on (or off) makes any difference? (It shouldn't.)

**Comment by OliveChukar** [comment]
Tried 3d fov. No difference. You did mean the option in the debug section of the main menu?

**Comment by actual-nh** [comment]
> Tried 3d fov. No difference. You did mean the option in the debug section of the main menu?

Yes. (See #42845 and #48202.)

**Comment by actual-nh** [comment]
It appears that the problem is in Creature::sees():
```
} else if( ( wanted_range > 1 && critter.digging() ) ||
```
It needs a check vs `here.has_flag( TFLAG_DIGGABLE, critter.pos() )`. If someone else can test it (@iffrt? @OliveChukar?), I can try a PR adding that as a check.

**Comment by OliveChukar** [comment]
I have never tested a PR.  If you can explain it I will try.

**Comment by actual-nh** [comment]
> I have never tested a PR. If you can explain it I will try.

Well, you would need to be able to compile CDDA (namely the version you'd be downloading from my fork), in this case, possibly unfortunately - see doc/COMPILING for more on this. (If this were a JSON change, it'd be a lot easier to test - just get the replacement JSON files.) Then you'd follow the "Steps to Reproduce" above.

If that isn't possible, and ifffrt isn't available for this, I can check it sometime using your save, but it will take me a bit longer.

**Comment by actual-nh** [comment]
@OliveChukar: OK, I was finally able to test it; the patch appears to work fine. When I started the game, the graboid was already visible (along with some other worm types), and going one tile to the right resulted in safe mode going on.
