### ISSUE TITLE
Cannot reload a battery in multi cooker

### ISSUE THREAD

**Issue by RDru** [CleverRaven/Cataclysm-DDA#48238]
# Describe the bug

 DEBUG    : Tried to reload liquid container with non-liquid.

 FUNCTION : bool item::reload(Character&, item_location, int)
 FILE     : src/item.cpp
 LINE     : 8444

# Steps To Reproduce

Try to reload a multi cooker (with battery or without, doesn't matter).

# Expected behavior

A battery is inserted/replaced in multi cooker.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-10203-gcf500cf [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills]
    Alternative Map Key [alt_map_key]
]

**Comment by Maleclypse** [comment]
I don't recall if this was fixed or not but I think this might be the issue?  
```  {
    "id": "multi_cooker_filled",
    "type": "TOOL",
    "copy-from": "multi_cooker",
    "name": { "str": "multi cooker - cooking" },
    "description": "A professional-grade multi-cooker, with a battery slot for camping trips or tailgating.  There is a dish in it.",
    "delete": { "qualities": [ [ "CONTAIN", 1 ] ] }
  },```
  `Copy-from` at one time didn't copy pockets.  Making this note for someone who has a better understanding of copy-from than myself.
