### ISSUE TITLE
Languange does not change

### ISSUE THREAD

**Issue by happyman1997** [CleverRaven/Cataclysm-DDA#48235]
Applies to all languanges except for japan/china
![bug1](https://user-images.githubusercontent.com/81465252/112716383-23958580-8ef7-11eb-8d55-6c46c467ceb3.png)
OS: Windows
OS Version: 10.0 2004
game version:  11548 64bit

**Comment by ZhilkinSerg** [comment]
Please fill in issue template properly.

**Comment by actual-nh** [comment]
> Please fill in issue template properly.

In particular, what version and OS?

**Comment by ZhilkinSerg** [comment]
At a bare minimum - because I cannot reproduce the issue on latest `master` on whatever Windows version I have installed.

**Comment by BrettDong** [comment]
![image](https://user-images.githubusercontent.com/21075502/112728814-73784a80-8eff-11eb-8a94-533b33cc45fc.png)
No problem on build 11545 on Windows 10

**Comment by happyman1997** [comment]
> > Please fill in issue template properly.
> 
> In particular, what version and OS?

done

**Comment by ZhilkinSerg** [comment]
Did you delete lang folder from game folder?

**Comment by happyman1997** [comment]
> Did you delete lang folder from game folder?

no

**Comment by BrettDong** [comment]
Could you upload `config/debug.log`? You can just drag and drop it to the GitHub comment box here.

**Comment by BrettDong** [comment]
And what is your Windows region, language, and locale setting?

**Comment by ZhilkinSerg** [comment]
Could be related to https://github.com/CleverRaven/Cataclysm-DDA/issues/48255

**Comment by happyman1997** [comment]
> Could be related to #48255

yes! i just changed scaling from 2x to 1x and its all in russian now. but if i revert on 2x its still english

**Comment by happyman1997** [comment]
> Could you upload `config/debug.log`? You can just drag and drop it to the GitHub comment box here.

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6217983/debug.log)
russia, russian, russian

**Comment by BrettDong** [comment]
Discussion continued in #48255.
