### ISSUE TITLE
[Magiclysm] Bug with endless flask containing other liquids.

### ISSUE THREAD

**Issue by b0urgeoisie** [CleverRaven/Cataclysm-DDA#48233]
# Describe the bug

I had clean water in an endless flask and (a)ctivated it. An error occurred because it tried to put whiskey in the flask and couldn't mix it with clean water.

# Steps To Reproduce

Spawn an endless flask.
Put a liquid other than whiskey in it.
(a)ctivate it.

# Expected behavior

I guess I would expect some sort of fail safe built in, which would display a message if the flask can't be filled with whiskey.

# Screenshots

![image](https://user-images.githubusercontent.com/52261571/112710296-54919e00-8e96-11eb-81ff-d20bfb41e936.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-10134-g9b256f6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by GGgatherer** [comment]
Instead of how it is working at the moment, this flask should refill whatever liquid is currently in it, with whiskey as default (when it is empty).
