### ISSUE TITLE
Bows don't shoot

### ISSUE THREAD

**Issue by GuilhermeMohr** [CleverRaven/Cataclysm-DDA#48266]
# Describe the bug

I try to shoot with a bow but this message apears: Your "name of the bow" isn't loaded

# Steps to reproduse bug:
1. Chose the hunter profession.
2. Equip the bow.
3. Try to shoot.

# Expected behavior

I just expected that I can shoot

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-10233-g678cf6a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Generic Guns [generic_guns],
    Alternative Map Key [alt_map_key],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

 - OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
 - Game Version: [from the main menu, e.g. 0.C-29938-g90f5268437]
 - Graphics version: [Tiles or Terminal]
 - Ingame language: [Arabic or Bulgarian or Chinese (Simplified) or Chinese (Traditional) or Dutch or Esperanto or French or German or Italian (Italy) or Japanese or Korean or Polish or Portuguese (Brazil) or Russian or Serbian or Spanish (Argentina) or Spanish (Spain) or Turkish]
 - Mods loaded: [e.g.dda, boats, hacktheplanet, StatsThroughSkills]
 -->

# Additional context

No crash report

**Comment by actual-nh** [comment]
Bows generally require arrows?

**Comment by RDru** [comment]
You probably don't have enough strength to shoot the bow.

**Comment by Saicchi** [comment]
Can not reproduce in `0.E-10134-g9b256f63cd [64-bit]`.
1. Created a character with 9 strength and the hunter profession.
2. Equiped the modern recurve bow
3. Fired an arrow with success.
