### ISSUE TITLE
Vehicle repair gets stuck by internal processing in the vicinity of many items

### ISSUE THREAD

**Issue by sumpfralle** [CleverRaven/Cataclysm-DDA#48269]
# Describe the bug

Repairing a vehicle is interrupted multiple times by a (non-responsive UI) period.
In case of the installation of a windshield (30 minutes in game), three of these interruptions happen.
In case of my (rather slow) computer, the non-responsive periods last more than 200 seconds each.

Moving the car three overmap tiles away from the base (and thus from the storage of many items) resolves the issue (no delay).
Maybe some kind of periodic state check for items (food?) causes the interruptions.

An strace log (see attached) reveals, that no syscalls are emitted during these periods. Thus they are probably exclusively used for internal processing of the game state (no UI).

# Steps To Reproduce

1. load the attached save game
2. install an reinforced windshield in the front left tile of the vehicle
3. wait for 10 minutes (real time) until completion

# Expected behavior

The operation should take only a few seconds.

# Screenshots

 - OS: Debian testing
 - Game Version: 0.E-7920-ge62c502
 - Graphics version: tiles
 - Ingame language: English
 - Mods loaded: default

# Additional context

* save game: [car-repair-stuck-periods.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6222483/car-repair-stuck-periods.zip)
* strace log (with relative timestamps): [strace-stuck-periods.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/6222480/strace-stuck-periods.txt)
    * see the lines 11633, 13831 and 22300: no system calls are emitted by the cdda process for around 200 seconds - probably there are just internal calculations happening during these periods

**Comment by mqrause** [comment]
![grafik](https://user-images.githubusercontent.com/38702195/112884970-72e2de00-90d0-11eb-8ea5-84be5d707da1.png)

Uh, each one of those seems to create a completely new crafting inventory, since `can_do_activity_there` starts with invalidating the cached crafting inventory. It's possible multiple NPCs go through that loop, too.

**Comment by actual-nh** [comment]
IIRC, there was a lightweight crafting inventory mechanism created specifically for that?

**Comment by sumpfralle** [comment]
> It's possible multiple NPCs go through that loop, too.

Yes, four NPCs may walk around this camp, too. Probably I did not notice these huge delays before, since the NPCs were working on remote missions. Thus your educated guess seems to match my experience with this issue.

btw: I am surprised, that such delays (for me: minutes) are not causing noticable pains on more modern hardware, too. I do not consider myself to be such a great hoarder :)

The non-responsive UI also happens during other activities, like:
* sorting out loot
* repairing cloth
* (and probably many more)
