### ISSUE TITLE
Shooter's earmuffs activation deletes the item

### ISSUE THREAD

**Issue by RDru** [CleverRaven/Cataclysm-DDA#48261]
# Describe the bug

Activating shooter's earmuffs deletes it or makes it invisible(?) without any message.

# Steps To Reproduce

1. Spawn Shooter's earmuffs and light battery.
2. Load the battery into shooter's earmuffs .
3. Activate shooter's earmuffs. 

# Expected behavior

Shooter's earmuffs work and are not deleted.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-10214-ga70b7d0 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by actual-nh** [comment]
I suspect there was an assumption made that you would be wearing them when you activated them.

**Comment by RDru** [comment]
> 
> 
> I suspect there was an assumption made that you would be wearing them when you activated them.

Wearing them deletes them also on activation.

**Comment by zeropol** [comment]
I don't know why but if we remove this line : 
https://github.com/CleverRaven/Cataclysm-DDA/blob/a8cf0e32895f1e082146f82c66d80be24e9fcada/data/json/items/tool_armor.json#L2694
then the earmuffs can transform.

( Why ? )

But,
when no battery, they show up not "greyed out" in the item activation menu, ( on activation it still says batteries are dead. )

**Comment by actual-nh** [comment]
Ping: @Salty-Panda?

**Comment by Salty-Panda** [comment]
Caused by #47887
Only occurs because of fix #47870
Possible short term solution: setting `charges per use: 1` in target item ( I guess it's earmuff_shooter_on or close )
