### ISSUE TITLE
Bleeding a corpse of acidic zombie results in tainted blood

### ISSUE THREAD

**Issue by RDru** [CleverRaven/Cataclysm-DDA#48267]
# Describe the bug

Bleeding a corpse of acidic zombies results in normal tainted blood instead of acid.

# Steps To Reproduce

1. Bleed a corpse of acidic zombie.
2. Check the resulted liquid.

# Expected behavior

The resulted liquid should be acid.
Using blood draw kit correctly results in sulfuric acid.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-10214-ga70b7d0 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

I also tried to bleed giant acidic ant and this action hangs the game. I have waited like 5min before killing the game.

**Comment by actual-nh** [comment]
The acidic zombie thing is known, and I'm planning on working on it after 0.F is out (#47124); the acidic ant, IIRC, is not, so you might want to focus on that one - especially given the freeze.
