### ISSUE TITLE
Massgrave special does not create a massgrave

### ISSUE THREAD

**Issue by Tommy-os** [CleverRaven/Cataclysm-DDA#48279]
# Describe the bug

Overmap special massgrave does not spawn any massgrave tiles anymore. Only zombies spawn in an open field.

# Steps To Reproduce

1. Turn on autonotes
2. Explore map until it notes down a mass grave on map
3. See only zombies and no mass grave at location

# Expected behavior

Finding a mass grave (like those in a FEMA camp) at the location, instead of a flat open field. It used to spawn a big grave previously.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-10088-g74e26ac [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

**Comment by jbytheway** [comment]
I'll see what I can do.

**Comment by jbytheway** [comment]
I looked into this.  As far as I can tell, terrain specification works just fine without being put into an array.  This may be a result of the changes I made in #48498.  So I think there's no need for an additional check.
