### ISSUE TITLE
Petrified eye mine finale Dark Wyrm spawning distance and faction problems

### ISSUE THREAD

**Issue by Tommy-os** [CleverRaven/Cataclysm-DDA#48288]
# Describe the bug

Once Dark Wyrms start spawning (by using the petrified eye pedestal), they will spawn directly next to the player in large groups. Similarly to how flesh raptors used to spawn on player, I'm assuming this is unintended or an oversight.

Second issue, is that these Dark Wyrms will then consider each other as valid targets for attacks. Meaning that even though this is a certain death scenario by having such lethal monsters spawn right next to a player, all the player has to do is run one tile away and the Dark Wyrms will start killing eachother instead of the player.

# Steps To Reproduce

1. Activate petrified eye pedestal in mine (E)
2. Walk a few steps for Dark Wyrms to spawn out of thin air directly next to player.
3. Run one tile away from Dark Wyrms and watch them kill eachother.

# Expected behavior

Dark Wyrms spawning further away from player/replacing nearby walls and chasing the player, instead of appearing out of air next to player.

Dark Wyrms not killing their own, instead only attacking the player.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-10088-g74e26ac [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

There's a separate issue already opened about the pedestal itself not triggering when petrified eye is picked up https://github.com/CleverRaven/Cataclysm-DDA/issues/13310

**Comment by actual-nh** [comment]
#48077 can be updated to fix the "attacking each other" problem, but I have to say I'm reluctant to advocate such until the "spawning too close" problem is fixed...

**Comment by actual-nh** [comment]
KorGgenT's fixes in #43350 may be of interest.

**Comment by actual-nh** [comment]
<https://github.com/CleverRaven/Cataclysm-DDA/blame/1fdfd68e4fac97d0be9e4b560f7b15019c4ba616/src/iexamine.cpp> indicates the original code there was more like place_critter_within (in its current version) than what's currently in use, place_critter_around. The latter tries to place the critters as close as possible; the former just tries to place them within the given range. (Admittedly, a radius of 2 is not very large...)

Also: Is it quite intended that both iexamine.cpp and timed_event.cpp seem to be doing monster placement (or am I misreading the code)?

Ping: @i2amroy, @BevapDin, possibly @jbytheway?

**Comment by jbytheway** [comment]
I don't know anything about this feature, but my reading of the old code agrees with you: it spawns 1d4 wyrms within 2 tiles of the player, not around the pedestal.  From @Tommy-os saying "large groups", it sounds like it might be spawning more wyrms now?  That might also be an issue.

**Comment by actual-nh** [comment]
According to [a wiki article from 0.C](http://cddawiki.chezzo.com/cdda_wiki/index.php?title=Guide:_Mine#Dark_Pedestal), it's supposed to be 1d4 wyrms spawning off-screen in waves, with each wave having a  1 in 25 chance of being the last. KA101 wrote most of the article - [most recent edit by KA101](http://cddawiki.chezzo.com/cdda_wiki/index.php?title=Guide:_Mine&oldid=4478#Dark_Pedestal) - and OK'd the Dark Pedestal material (see wiki page history).

**Comment by Night-Pryanik** [comment]
I don't get to the wyrms mine stuff yet, but I'll try to look into it.

**Comment by actual-nh** [comment]
> I don't know anything about this feature, but my reading of the old code agrees with you: it spawns 1d4 wyrms within 2 tiles of the player, not around the pedestal.

Actually, it randomizes the position between 0 and MAPSIZE_X|Y and rejects it if it's 2 tiles or less to the player - or at least seems to be the intent; there's a && that should be a || - which confirms the wiki's version:
```cpp
 for( int i = 0; i < num_wyrms; i++ ) {
        int tries = 0;
        tripoint monp = examp;
        do {
            monp.x = rng( 0, MAPSIZE_X );
            monp.y = rng( 0, MAPSIZE_Y );
            tries++;
        } while( tries < 10 && !g->is_empty( monp ) &&
                 rl_dist( p.pos(), monp ) <= 2 );
        if( tries < 10 ) {
            g->m.ter_set( monp, t_rock_floor );
            g->summon_mon( mon_dark_wyrm, monp );
        }
    }
```

**Comment by Night-Pryanik** [comment]
Article from the wiki seems to contain actual information. On latest experimental as of 04 of April the game indeed spawns 1-4 wyrms within radius of 2 tiles around the player, and it will be adding more and more wyrms every minute until 4% chance triggers the stop.

What could be done:
- radius increased to 5 or 10 tiles so player has some place to maneuver;
- delay between waves increased to, say, 2 minutes so player has some time to deal with the previous wave;
- change wyrms' spawn point from player to pedestal (or to the surrounding walls) so player could run away from them if needed.

**Comment by actual-nh** [comment]
> What could be done:
> * radius increased to 5 or 10 tiles so player has some place to maneuver;

Using place_critter_within instead of place_critter_around?

> * delay between waves increased to, say, 2 minutes so player has some time to deal with the previous wave;

That one could work well combined with either of the others.

> * change wyrms' spawn point from player to pedestal (or to the surrounding walls) so player could run away from them if needed.

This is also a definite possibility, although a bit more complicated because:

- The timed event would have to be able to figure out where to spawn them from, unless you're meaning going on spawning them in that "room" (how does one pass information to a timed event?).
- Which walls would one use? First ones encountered by going N/S/E/W, or what?

**Comment by Night-Pryanik** [comment]
> Using place_critter_within instead of place_critter_around?

`place_critter_within` uses random points in a radius, `place_critter_around` uses closest available points to the center. `place_critter_within` looks like more appropriate, but honestly they don't differ too much in this context.

> you're meaning going on spawning them in that "room"

Yes, I meant that. 

>how does one pass information to a timed event?

A room with a pedestal should have separate id so we could use its coordinates to spawn wyrms.

But I just want to say this will shift the balance of whole encounter. Now it's spawning wyrms in player's vicinity, even if he ran away from the pedestal, until he get away to the ground level. And he has to fight the wyrms all the way up. If we make wyrms' spawn point anchored only to the pedestal room, player will have a much easier way to deal with the monsters. I just don't get why wyrms are spawned next to the player out of nowhere.
On the other hand, if we go the "walls" variant, we could simply spawn wyrms in player's global position and spawn wyrms out of the walls, which might look better IMO.

> Which walls would one use? First ones encountered by going N/S/E/W, or what?
Random, I guess. This shouldn't really matter.

**Comment by actual-nh** [comment]
> > Using place_critter_within instead of place_critter_around?
> `place_critter_within` uses random points in a radius, `place_critter_around` uses closest available points to the center. `place_critter_within` looks like more appropriate, but honestly they don't differ too much in this context.

With a radius of 2, not much, true.

> But I just want to say this will shift the balance of whole encounter. Now it's spawning wyrms in player's vicinity, even if he ran away from the pedestal, until he get away to the ground level. And he has to fight the wyrms all the way up. If we make wyrms' spawn point anchored only to the pedestal room, player will have a much easier way to deal with the monsters. I just don't get why wyrms are spawned next to the player out of nowhere.
> On the other hand, if we go the "walls" variant, we could simply spawn wyrms in player's global position and spawn wyrms out of the walls, which might look better IMO.

Agreed. Spawn further away from the player - ideally from the walls or at least just outside of the player's vision range - but still "follow" the player's position until they get out of the mine. (This seems to be the original code's intent and what the wiki is describing.)

> > Which walls would one use? First ones encountered by going N/S/E/W, or what?
> Random, I guess. This shouldn't really matter.

OK.

**Comment by jbytheway** [comment]
Some random trivia: In the Infinity Engine (used for Baldur's Gate and similar games) there's a specific function that can be used for scripted events which spawns something just outside of player vision.  So that's some evidence that adding support for something like that would probably be useful and reasonable for our scripted stuff too.
