### ISSUE TITLE
Item endochitin was loaded with charges, but can not have any!

### ISSUE THREAD

**Issue by Tommy-os** [CleverRaven/Cataclysm-DDA#48281]
# Describe the bug

 DEBUG    : Item endochitin was loaded with charges, but can not have any!

 FUNCTION : void item::io(Archive&) [with Archive = io::JsonObjectInputArchive]
 FILE     : src/savegame_json.cpp
 LINE     : 2567

# Steps To Reproduce

Unknown, randomly pops up. Usually after loading a save game. The item in error varies.

# Expected behavior

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-10088-g74e26ac [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

Had other similar errors previously, again seemingly randomly after loading a savegame.

 DEBUG    : Item mre_meatball_box was loaded with charges, but can not have any!

 FUNCTION : void item::io(Archive&) [with Archive = io::JsonObjectInputArchive]
 FILE     : src/savegame_json.cpp
 LINE     : 2567

 DEBUG    : Item mre_bbqbeef_box was loaded with charges, but can not have any!

 FUNCTION : void item::io(Archive&) [with Archive = io::JsonObjectInputArchive]
 FILE     : src/savegame_json.cpp
 LINE     : 2567

**Comment by BrettDong** [comment]
Could you upload a save that's causing this problem for you?

**Comment by Tommy-os** [comment]
@BrettDong

> Could you upload a save that's causing this problem for you?

I've managed to reproduce this error in the following savegame: https://ufile.io/eamzd40v

Follow these steps:
1. Load the savegame
2. Open metal doors out of the lab
3. Get on the bike that's parked inside the lab
4. Drive the bike out of the lab
5. Drive on the road to forest south, do not take detour to military helipad
6. After entering the forest on the road the error will appear

![error](https://user-images.githubusercontent.com/81636323/113279638-a5185980-92e3-11eb-99cd-20307c6e68ce.png)

Map screenshot to show where the error occurs.

**Comment by DillonSimeone** [comment]
I've seen this bug around in my game too. They come from big bugs, like ants. Butcher them, and a bunch of endochitins will drop. Save and quit, then load back in and you'll very likely get this error.
