### ISSUE TITLE
Make giant worms, graboids and half worms automatically visible inside cars.

### ISSUE THREAD

**Issue by ifffrt** [CleverRaven/Cataclysm-DDA#48299]
# Is your feature request related to a problem? Please describe.
Just got a run ended by wasting all of my mana shooting at the ground next to my car because I assumed that giant worms and half worms can't hide when they are boarding cars.

# Describe the solution you'd like
Giant worms and half worms and graboids shouldn't be able to hide inside cars, at least with how they are described in the wiki. A half-worm is supposedly a human-sized monster that weighs 81.5 kg. So something that's about the size of this person 
![Jamal-Shere-1024x1024](https://user-images.githubusercontent.com/74819253/113200257-4aa2dd00-9292-11eb-9c9a-2d066dbc7eb8.jpg)

shouldn't be able to hide itself inside the space underneath your average car seat.
![fd86273c6908b2af77e0766b4d5574dd](https://user-images.githubusercontent.com/74819253/113222633-a2047580-92b1-11eb-8ff7-90994b60b717.jpg)

# Describe alternatives you've considered
I've wracked my brain on how giant worms and half worms can somehow hide underneath car seat, but the more I think about it the less that makes sense.

**Comment by OliveChukar** [comment]
I think this is a variation of  #48237. The problem seems to be that burrowing creatures are only made visible when adjacent to the player representing the creature emerging to attack.  No one considered that there would be situations that would trap them above ground making them visible at distance. 

Probably not relevant to this situation but when you think of the size of a worm vs human you need to remember that worms are basically cylinders of meat and therefore more compact then humans. So they probably could fit in smaller spaces then you imagine.

**Comment by ifffrt** [comment]
> 
> Probably not relevant to this situation but when you think of the size of a worm vs human you need to remember that worms are basically cylinders of meat and therefore more compact then humans. So they probably could fit in smaller spaces then you imagine.

Yeah I have thought of that, but even with that taken into account, the size of a seat still (probably) barely covers more than 2/3 of that man in the picture's torso length wise, and width-wise he would barely fit. A worm would probably spill out into somewhere that's immediately visible to players anyway, so I didn't mention that.

**Comment by actual-nh** [comment]
The PR I've linked _should_ fix this problem, provided that your vehicle is on undiggable terrain (e.g., a road, IIRC). I can undo the "will close this issue" if you check it out, @ifffrt, and it doesn't work.

**Comment by ifffrt** [comment]
Would that still leave the graboid invisible if it's stuck in a car though? I don't think that would fix the real issue, which is that graboids can hide itself inside the cramped narrow space under a seat (and inside cargo spaces where there aren't any space where they can hide) even though they are massive monstrosities that shouldn't be able to.

**Comment by actual-nh** [comment]
> Would that still leave the graboid invisible if it's stuck in a car though? I don't think that would fix the real issue, which is that graboids can hide itself inside the cramped narrow space under a seat (and inside cargo spaces where there aren't any space where they can hide) even though they are massive monstrosities that shouldn't be able to.

I don't think that's quite what's happening, although your logic is perfectly valid. (Just in case I'm wrong, I've removed this issue from those closed by the PR.) I think they aren't in the vehicle in the first place, but coming up from underneath, conceptually - the vehicle code is rather weird on things like that (note that stuff can fall through to the ground if it's too much for the seats to contain?).

The code essentially said "if you're more than 1 tile away from a digging monster, you can't see it, no matter what". The PR adds a check for whether the local terrain actually would allow the monster to dig.

**Comment by ifffrt** [comment]
I actually think that the giant worm is in the vehicle. The way I could tell that is because when the giant worm show up inside my car, I could drive at 102 miles per hours and it would still stay inside my car. Which means it must be boarding the car and not simply on the ground (and burrowing up through the car somehow without harming the car itself). And when I drive onto asphalt, the worm still shows up in my car. But now it is stuck in the same place in the car and can't change seat. Probably because of the code that forbids it from entering non-diggable terrain (just a shot in the dark because I actually can't read C++ code at all and can only contribute by testing).

**Comment by actual-nh** [comment]
Huh. Ping: @mlangsdorf?

**Comment by Zireael07** [comment]
@ifffrt: Could you provide a save for testing/debugging so that the devs can check if that's indeed the case?

**Comment by ifffrt** [comment]
[savefile.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6255228/savefile.zip)

Also just discovered that when the worm is inside the car, it can't do anything to you period. Even on dirt ground.

**Comment by anothersimulacrum** [comment]
Worms, graboids, and half worms are visible in cars as of 0.E-10713-g65d31be62e
