### ISSUE TITLE
"MESSAGE: SIGILL: Illegal instruction" ... On a window 10 OS. 

### ISSUE THREAD

**Issue by DillonSimeone** [CleverRaven/Cataclysm-DDA#48307]
# Describe the bug

A linux user on the C:DDA discord, several people, strongly suggested filing this bug report. He said that it was very strange that a sigill error would occur for me since I'm playing on window 10, and have a modern CPU, an AMD 3600xt cpu.

> "...
> I have 0 idea about windows however on linux sigill means literally illegal cpu instruction.
> which implies that binary is compiled for a cpu of a newer generation than yours, generally.
> ..."

I was fighting a mother frog on build 11537, doing science to see if monsters have a finite blood pool without looking at the game files.

After awhile of this abuse, the SIGILL error occured and crashed the game. The crash.log is attached to this report below.

# Steps To Reproduce

Not sure.

1. New world, player with a cutting weapon and 8 melee + cut. (And armor to withstand monster attacks, maybe)
2. Spawn in a mother frog.
3. Abuse mother frog without killing it.
4. ???
5. Sigill crash!

# Expected behavior

The mother frog either flopping over as a bloodless corpse, or me losing interest in the mother frog. No sigill crash.

# Screenshots
![image](https://user-images.githubusercontent.com/21962421/113300972-594dbc00-92b3-11eb-9cfa-8ff075071b00.png)

![image](https://user-images.githubusercontent.com/21962421/113301148-8d28e180-92b3-11eb-85b2-eb189d1f93c3.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-10134-g9b256f6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    <color_light_red>Secronom</color> [secronom],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Crazy Cataclysm [crazy_cataclysm],
    Mining Mod [Mining_Mod],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Mythical Martial Arts [MMA],
    Dorf Life [Dorf_Life],
    Advanced Gear - UndeadPeople Tileset [adv_gearUDP],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Arcana - UndeadPeople Tileset [ArcanaUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Crazy Cataclysm - UndeadPeople Tileset [CrazyCataclysmUDP],
    DinoMod - UndeadPeople Tileset [DinoModUDP],
    Dorf Life - UndeadPeople Tileset [Dorf_LifeUDP],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mining Mod - UndeadPeople Tileset [Mining_ModUDP],
    My Sweet Cataclysm - UndeadPeople Tileset [My_Sweet_CataclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP],
    Secronom - UndeadPeople Tileset [secronom_UDP],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Useful Helicopters [useful_helicopters]
]

# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6243849/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6243850/debug.log)

My save is not attached because it's a little over 80Mb right now.  If you still want it anyway, let me know and I'll upload the file to a some sort of file sharing server for you along with my oversized mod folder.

**Comment by BrettDong** [comment]
Does build 11552 crash for you?

**Comment by DillonSimeone** [comment]
I still haven't been able to cause this to happen again on 11537... Went back to the mother frog and attacked it brutally as I did when this error occurred then wandered away after running out of stamina. 

The mother frog spawns little frog babies and use them to attack the player with, maybe that's related to the crash: baby frogs spawning on top of other monsters and/or the player, causing the game to freak out.

**Comment by ZhilkinSerg** [comment]
> No. I still haven't updated beyond 11537 due to the SDL updates (possibly) killing the FPS.
Everything is back already.

**Comment by DillonSimeone** [comment]
I still haven't managed to cause the Sigill error to occur again. I've long since updated to 11552. 

Shrug, maybe a random electron from space managed to strike my CPU just right to throw that error.
