### ISSUE TITLE
Taped windows don't reduce scent dispersion as much as a regular closed window

### ISSUE THREAD

**Issue by SnowyFlare** [CleverRaven/Cataclysm-DDA#48300]
# Describe the bug

Taped Windows don't reduce scent dispersion.

# Steps To Reproduce

Be next to a taped up window, your scent cloud will travel through it as if it was an open window.

# Expected behavior

Being the same object, the latter simply having duct tape applied to it, It should reduce your scent cloud at the same level as a normal closed window.

# Screenshots

![Screenshot (59)](https://user-images.githubusercontent.com/81720283/113234474-529d5580-926f-11eb-9ae2-6accd81282ca.png)

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-10255-g6b8dd00
 - Graphics version: Tiles

# Additional context

The taped up windows, along with stained glass windows, lack the "REDUCE_SCENT" flag in terrain-windows.json.

**Comment by Zireael07** [comment]
AFAIK intentional - the taped window is an open window that's been taped shut, not a closed window with tape on top.

**Comment by souricelle** [comment]
> AFAIK intentional - the taped window is an open window that's been taped shut, not a closed window with tape on top.

That isn't so. You can tape a regular glass window shut and then remove the tape from it just fine without breaking the window or anything. You cannot tape up a broken window. The tape is supposed to be blocking light and air flow and it isn't - seems like an easy JSON fix.

**Comment by Zireael07** [comment]
agree with the above, nitpick: I meant the window is open as in "not closed", not as in "no glass/broken"
