### ISSUE TITLE
Remove references to an inexistent "INSTALL" file 

### ISSUE THREAD

**Issue by Termineitor244** [CleverRaven/Cataclysm-DDA#48318]
# Describe the bug

Trying to compile the game, I decided to use visual studio, but upon starting the app  and selecting the game folder... I find an error? Something related to Cmake lists, I read the error message and it says at the end to "See INSTALL file for details and more info" so I received a great surprise when I searched for that file and found nothing at all... After some search in the repository I think this "INSTALL" file (and the messages relating to it) was added and removed in #11970 (In 2015...), with its contents put in COMPILING-CMAKE.md

# Steps To Reproduce

I don't know, tell a noob to compile the game and see that error message? Or just go to CMakeLists.txt and search for "INSTALL file", then search in the repository for an "INSTALL" file.

# Expected behavior

To see error messages directing me to files that exist and are related to the problem at hand.

# Screenshots

![error](https://user-images.githubusercontent.com/53200489/113386375-5dc3b480-9347-11eb-83dc-551b318f9140.png)

# Versions and configuration

A build from the past week.

# Additional context

If you have never used any of these programs, compiling cdda can be way too difficult, but I guess if one has experience it should be pretty easy to discern what to do... Well, if I discover how to make this work I could write a guide for dummies in compiling cdda in Visual Studio.

Edit: I coudnt compile with Visual Studio and VCPCK, but after trying with MSYS2 I succeeded without a single problem.

**Comment by ZhilkinSerg** [comment]
Visual Studio guide (using `vcpkg`) is here - https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/COMPILING/COMPILING-VS-VCPKG.md. Please add one for CMake.

**Comment by Termineitor244** [comment]
> 
> 
> Visual Studio guide (using `vcpkg`) is here - https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/COMPILING/COMPILING-VS-VCPKG.md. Please add one for CMake.

??? That is the guide I'm using... Or is that directed to someone else?

**Comment by ZhilkinSerg** [comment]
You are not following the guide then - it tells you:

![image](https://user-images.githubusercontent.com/16213433/113388233-82934880-9396-11eb-96c5-0a749b861874.png)

You have opened folder instead (that's valid, but only if you want to build using `CMake` and we have not tested or provided instruction for building using `CMake` on WIndows in Visual Studio).

**Comment by Termineitor244** [comment]
Ohhhhh, that will help, I have not reached that part yet (I was opening visual studio to check if the program was installed correctly, so when asked for a project folder, I naturally select the main folder, then I received the error notice, but I'm still doing the installation and configuration).

**Comment by actual-nh** [comment]
So where is the error message mentioning an `INSTALL` file originating from?

**Comment by ZhilkinSerg** [comment]
> 
> 
> So where is the error message mentioning an `INSTALL` file originating from?

CMake files:

![image](https://user-images.githubusercontent.com/16213433/113429965-03c3fd00-93e2-11eb-94e2-885ce771a630.png)

**Comment by actual-nh** [comment]
Thank you, I will see about a PR for altering those as appropriate ("doc/COMPILING", "doc/COMPILING/COMPILING-CMAKE.md", or "doc/COMPILING/COMPILING.md"?).
