### ISSUE TITLE
Office Tower Only Having One Floor

### ISSUE THREAD

**Issue by Cpl-Jordan** [CleverRaven/Cataclysm-DDA#48311]
# Describe the bug
Office Tower location (With the gray square background on the map and has a courtyard) only has one floor.

# Steps To Reproduce
1.) Spawn in a new world
2.) Find a Office Tower
3.) See if it has a second floor. (They might have floors above but there is a chance of them spawning without any floors)

# Expected behavior
Having a office tower be a office tower with many floors.

# Screenshots
Map:
![OfficeTower1](https://user-images.githubusercontent.com/77216510/113323683-3be51600-92e4-11eb-9326-de7307f4747a.png)
![OfficeTower2](https://user-images.githubusercontent.com/77216510/113323700-41426080-92e4-11eb-8f2b-2892322205ad.png)

In Game:
![Officetower3](https://user-images.githubusercontent.com/77216510/113326291-78fed780-92e7-11eb-935b-eba57f1c1873.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-10239-gdc8bba6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
