### ISSUE TITLE
Crafting with items that use charges

### ISSUE THREAD

**Issue by b0urgeoisie** [CleverRaven/Cataclysm-DDA#48324]
# Describe the bug

The game will not recognize items with existing charges as viable for meeting crafting criteria for "components". An example would be a craft that requires soldering iron. If the soldering iron has a battery in it, it won't work. You need to unload the battery.

This becomes an issue with items that can't be reduced to an "ammo-free" state like lighters or candles. Batteries work fine.

# Steps To Reproduce

Load soldering iron and associated charge.
Load the battery into the soldering iron.
Try to craft something that uses "soldering iron" as a requirement for a component. (welding component kit)

Load candle.
Try to craft jack o' lantern.
Be wildly disappointed.

# Expected behavior

Would expect the recipe to accept these items.

# Screenshots

![image](https://user-images.githubusercontent.com/52261571/113425256-90010080-939f-11eb-8da3-0fe1daa55697.png)
![image](https://user-images.githubusercontent.com/52261571/113425295-9db68600-939f-11eb-9171-3bce3c0c31b8.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-10235-gec881d7 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by b0urgeoisie** [comment]
MAYBE a 0/100 candle would work but I don't know how to create that item.

**Comment by RenechCDDA** [comment]
Resolved at some point or another, as of https://github.com/CleverRaven/Cataclysm-DDA/commit/c94dc0387513d5bba49eb7d74b2b51a7a4d8c4a0

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/6ebf855e-675f-46a5-8970-404ed472745f)

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/81d7fabb-4178-4a11-8b4a-bf1dd7387f56)

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/715d9d7c-e839-4dad-bf29-fdddf28f8660)
