### ISSUE TITLE
Spells with blast shapes sometimes have impossible blind spots at certain angles.

### ISSUE THREAD

**Issue by ifffrt** [CleverRaven/Cataclysm-DDA#48320]
# Describe the bug

Spells with blast shapes such as Jolt and Windblast can have blind spots that shouldn't exist. Jolt level 10 in particular has a blind spot that basically prevents you from hitting anything in a straight line angled at a 45 degree angle to your north-east and south-west. All the other directions doesn't have this blind spot. This issue is also present with Windstrike, but it seems higher the range a spell has, the less the blind spots appear.

# Steps To Reproduce

1. Give yourself Jolt level 10.
2. Try to aim at anything in a line angled 45 degree at your north-east and south-west.
3. Fail.

# Expected behavior

We shouldn't have an issue hitting things only at those particular angles.

# Screenshots

![New Bitmap Image (5)](https://user-images.githubusercontent.com/74819253/113411693-b004e400-93e0-11eb-9bb5-0b72da967aad.png)
![New Bitmap Image (3)](https://user-images.githubusercontent.com/74819253/113411697-b1cea780-93e0-11eb-87fa-f7ed223799bd.png)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-10239-gdc8bba6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key],
    Graphical Overmap [Graphical_Overmap],
    sees-player icon, retrodays [sees_player_retro],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    Mythical Martial Arts [MMA],
    More Survivor Stuff [more_survivor_stuff],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    No Fungal Monsters [No_Fungi],
]

# Additional context

**Comment by actual-nh** [comment]
See #46792 (including a possible fix that I've never gotten around to trying).
