### ISSUE TITLE
[Mods] CRIT helmets disappear upon turning on and off attached flashlight.

### ISSUE THREAD

**Issue by ifffrt** [CleverRaven/Cataclysm-DDA#48321]
# Describe the bug

When you turn on and off the flashlight of the CRIT helmet, it disappears from your inventory.

# Steps To Reproduce

1. Give yourself a CRIT helmet.
2. Turn on the flashlight of the CRIT helmet.
3. Turn off the flashlight of the CRIT helmet.
4. See it disappear.

# Expected behavior

The CRIT helmet shouldn't disappear into thin air.

# Screenshots

# Versions and configuration

    OS: Windows
        OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
    Game Version: 0.E-10239-gdc8bba6 [64-bit]
    Graphics Version: Tiles
    Game Language: English [en]
    Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key],
    Graphical Overmap [Graphical_Overmap],
    sees-player icon, retrodays [sees_player_retro],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    Mythical Martial Arts [MMA],
    More Survivor Stuff [more_survivor_stuff],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    No Fungal Monsters [No_Fungi],
    ]

# Additional context

**Comment by actual-nh** [comment]
Looks like the underlying problem is probably the same as for #48261, just for a different item.

**Comment by Salty-Panda** [comment]
> Looks like the underlying problem is probably the same as for #48261, just for a different item.

Yup
The solution is the same as in #48278
