### ISSUE TITLE
Recipe for makeshift ear plugs

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#48368]
# Describe the solution you'd like
A recipe to build makeshift ear plugs from a candle (i.e. wax)

**Comment by Entity-y** [comment]
How would this work, by carving the candle with a knife or by dripping hot wax onto something like a cotton ball?

**Comment by matt32106** [comment]
1/ Warming wax and shaping it with your fingers would be enough I think (I remember doing that during lit-by-candles RPG sessions :)). So one of the requirement could be a fire source + anything that contain wax. 
2/ Carving wax would work too.
3/ Plasticine would need nothing else (not sure it is an item yet...).
4/ Clay could also be used (maybe with a source of water nearby?)

**Comment by TealcOneill** [comment]
I think Occulti's commit completes this issue.
