### ISSUE TITLE
"proportional" doesn't work with armor parameters ("warmth" etc)

### ISSUE THREAD

**Issue by Salty-Panda** [CleverRaven/Cataclysm-DDA#48364]
# Describe the bug

Items that use copy_from and proportional, doesn't have certain values changed.
Most armor using acidchitin: legguard_acidchitin, boots_acidchitin....
and boots_western

Didn't check if "relative" works.

# Steps To Reproduce

Compare values in code/game

# Expected behavior

"proportional" properly changes those values, possibly documentation entry/test which values can't be used

# Screenshots

![image](https://user-images.githubusercontent.com/26396019/113515494-191d6080-9575-11eb-8bf2-4b693dd91081.png)
![image](https://user-images.githubusercontent.com/26396019/113515502-30f4e480-9575-11eb-9a5b-0e3d05cbe528.png)

# Versions and configuration

- Game Version: 0.E-10239-gdc8bba6 [64-bit]

**Comment by wapcaplet** [comment]
Confirmed in 0.E-10282-gf22beb8074. "pair of boots" and "western boots" have the same encumbrance, and "chitinous boots" and "biosilicified chitin boots" have the same encumbrance and warmth, despite the fact that "western boots" and "biosilicified chitin boots" have a "proportional" increase to those fields defined in the JSON.

**Comment by actual-nh** [comment]
An armor variant on #47565?

**Comment by Salty-Panda** [comment]
> An armor variant on #47565?

Possibly, I compared to #47567 and both "encumbrance" and "warmth" use optional, not assign.
Also encumbrance can appear in various forms due to multiple ways to declare armor parameters.

**Comment by Salty-Panda** [comment]
The simple solution is to change `optional` to `assign`, but @KorGgenT said in https://github.com/CleverRaven/Cataclysm-DDA/issues/47565#issuecomment-780794021 he would like to move from `assign` to `optional`.
Assign seems to be the only place where `proportional` and `relative` are handled.

**Comment by ZhilkinSerg** [comment]
Change it to assign for 0.F then revert everything in 
#43144

**Comment by LeahLuong** [comment]
@ZhilkinSerg Is your comment above still relevant??

This may have been resolved by #54801. If so, please close.

**Comment by RenechCDDA** [comment]
Per above comment, was resolved and has a test for it. Resolved.
