### ISSUE TITLE
[0.9-116-glaf62d1] Infinite Thread Bug

### ISSUE THREAD

**Issue by Killer-of-Lawyers** [CleverRaven/Cataclysm-DDA#4837]
As seen here: http://smf.cataclysmdda.com/index.php?topic=4512.0

6 inch string can be made indefinitely with no resource input.  Having sinew or plant fiber close enough to craft with seems to also satisfy the requirement for thread.  When asked what to use to make the 6 inch string with, if you select thread it will craft the string, but not use any of the plant fiber or sinew.  It is possible to get in an infinite crafting loop with this bug, with the player stuck crafting string until they finally die from dehydration.

I haven't seen any updates relating to this, so I thought I'd go ahead and put it here where it's easier to see.  Hopefully I didn't fuck anything up by doing this, just trying to help!

**Comment by mugling** [comment]
Resolved some time ago
