### ISSUE TITLE
Circular Saw disappears upon activation

### ISSUE THREAD

**Issue by Caelum-Updates** [CleverRaven/Cataclysm-DDA#48374]
# Description
Circular saws will disappear once turned on even when wielded, stored in inventory or placed in the environment. 

# Steps To Reproduce

1. Get a circular saw with charges.
2. Activate to turn on.
3. Circular saw disappears.

# Expected behavior

Circular saw turns on and spawns in [Circular saw (On)]

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-10282-gf22beb8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Generic Guns [generic_guns],
    Alternative Map Key [alt_map_key],
    Graphical Overmap [Graphical_Overmap]
]

# Additional context

Reproducible by other users.

**Comment by Salty-Panda** [comment]
Another cases of wrong "charges_per_use", I'll fix it soon
