### ISSUE TITLE
Add "weight_limit" to heavy duty tow cable (breaking tows)

### ISSUE THREAD

**Issue by TheGoatGod** [CleverRaven/Cataclysm-DDA#48372]
# Describe the solution you'd like
adding
"weight_limit": "2 tonne" for example
if it hits 2 tonne, the cable breaks and turns into `"broken_hd_tow_cable"` on each vehicle

# Describe alternatives you've considered
make `"broken_hd_tow_cable"` spawn between the vehicles (be nice if it was random, on the vehicle and/or on the tiles between the vehicles)

# Additional context
if this happens ill add the broken variant for vehicle parts and generic 

# Testing

after testing it seem indestructible but I cant get it to brake

**Comment by TheGoatGod** [comment]
second thoughts, how this would be implemented as above would only allow tows to break if you attached it to a vehicle that's too heavy. this is fine, but to make allowance for breaking during driving would be different and atm thinking of how to make this work easily

**Comment by PatrikLundell** [comment]
The weight isn't really the issue in reality (when it comes to getting it to move: the inertia is a significant issue when getting it to stop...), but rather the force exerted on the cable. The situation is similar to that of whether an engine is capable of moving a vehicle or not. A heavy vehicle on wheels with low roll resistance on a good quality road may well be towed with ease (assuming the tower pulls the cable gently), while a much lighter frame with no working wheels lying in the middle of a plowed field may be impossible to drag along.

While having borderline cases break while you're towing would be interesting, I'm not sure the coding effort involved is worth it (it may, if it's "just" a matter of using existing vehicle code). The easiest (and probably most common) case would be for the cable to break when you try to get the whole ensemble into motion.

The obvious answer to a tow cable that's not strong enough is to add more cables, as you can probably add one per facing vehicle tile, but I'm not sure it would work in practice, as there's always going to be one cable that gets taught before the others.

**Comment by TheGoatGod** [comment]
tbh i just want to add a broken_hd_tow for when they brake and im not sure how it would be done, but yeah it would be alot of work for one thing, actually i think i can add breaks into via the vehicle parts, but im not sure it would work how i would like

**Comment by Salty-Panda** [comment]
Pretty sure the current tow takes drag into account, as the bug with extra drag from handbrake during towing proved.
Did you test it for various tensions?
Road vs field, bike vs truck

**Comment by TheGoatGod** [comment]
im testing it furrily now, my basic testing was for spawning and testing the items worked. ill add my results to the main post.

**Comment by TheGoatGod** [comment]
after careful thinking I don't see the need I can do what i want and it all works rare to see broken tows
