### ISSUE TITLE
The staff hold on hand should can cast spell by press [f] instead of [A]

### ISSUE THREAD

**Issue by MikuMiddo** [CleverRaven/Cataclysm-DDA#48387]
# Is your feature request related to a problem? Please describe.
It's not a  bug,but a suggestion for better usage of staff.
When using a staff like Magic Missile,you shold continuely pressing the [A] and the [f],it's quite terrible when do it for 20~30 times,So why don't make the staff use like a gun,press [f] to aim and press [f] to cast the spell;

# Describe the solution you'd like
When holding a staff,It can cast spell by just press [f] instead of [A]

# Describe alternatives you've considered
Can add a FLAG to the things that can press [f] to cast spell,when a thing with this FLAG holding on hand,[f] can make this thing to cast spell;

**Comment by actual-nh** [comment]
Reasonable. (By "case" you mean "cast"?)

**Comment by MikuMiddo** [comment]
> Reasonable. (By "case" you mean "cast"?) Ping: @KorGgenT?

Ahh my fault.Wrong spell

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
