### ISSUE TITLE
Stimulant Module Effect Descriptions

### ISSUE THREAD

**Issue by Caelum-Updates** [CleverRaven/Cataclysm-DDA#48388]
# Description
Stimulant modules (ex. RA10K Stimulant Modules) have very vague descriptions and no hints about their effects. Considering that these are military standard chemical implants, there will probably be a label of effects on it at the very least.

# Describe the solution you'd like
Update item description with something similar to "Effects: Increases physical abilities at the cost of mental faculties."

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
