### ISSUE TITLE
Barley crops are too productive

### ISSUE THREAD

**Issue by langp11** [CleverRaven/Cataclysm-DDA#48397]
# Describe the bug
Compared to other cereal crops, barley produces about 5 times more than I would expect.

# Steps To Reproduce
Grow various crops, measure the weight of barley, wheat etc.
Be astonished.

# Expected behavior
I don't expect all crops to be the same, but I do expect them to be close, allowing for growth times.

Using 91 day seasons and growing several thousand tiles of each to smooth out the variations, I calculated (a) kg/tile, and (b) cal/day/tile (to allow for the different growth times). We get:
Barley, 3.3 / **126**
Buckwheat, 1.5 / 42 (only 86 tiles so a less robust value)
Corn, 0.6 / 5
Oats, 0.3 / 22
Wheat, 0.8 / 17

Observations:
Oats are less productive per square, their shorter growth time makes them a bit more productive than wheat, fitting its reputation as a favourite crop for survivors.
Corn is not very productive on these measures but it's quite a different plant, producing the cob as well as the seed, so that could be fine.

Comparing this to the USDA Crop Production 2020 Summary (Jan 2021), using the national averages (because it doesn't have New England detail), we get bushels per acre.
Barley 77.5
Corn 172 (which probably includes the cob, so we might have to give up on finding good relative values for corn)
Oats 65.1
Wheat 49.7 (50.9 for winter wheat, 48.6 for spring wheat)

Bushels convert to kg at a different rate for each crop (the wikipedia page has values and source references) we get kg per acre:
Barley 1,687
Oats 945
Wheat 1,353

This confirms the expectation that barley should be a lot closer to wheat than it is. 

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-8729-geba9219 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock]
]

# Additional context

These yields don't seem to be in json files or I would be making a PR.

The attached spreadsheet has the source yields and calculations in case I've made some glaring error.
[Crop_Yields.xlsx](https://github.com/CleverRaven/Cataclysm-DDA/files/6268285/Crop_Yields.xlsx)

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
