### ISSUE TITLE
Hammer's and Wrench's no longer fit into toolboxes.

### ISSUE THREAD

**Issue by O1OOO1O** [CleverRaven/Cataclysm-DDA#48395]
After updating from experimental build 11561 to 11566 and restarting from a saved game, the hammer and wrench were ejected from the toolbox in my character's inventory.  Attempting to use the insert command after picking them up, they were no longer available as a choice to insert.

# Steps To Reproduce
load a toolbox with a hammer, wrench and other items on build 11561 and save the game. Update to 11566 and load the saved game, and see message about them getting ejected.

# Expected behavior
A hammer and wrench should be able to fit in a toolbox as they had previously when there is ample room for them.

**Comment by O1OOO1O** [comment]
As of 11567  a Rubber Hose and Screwdriver set also no longer can fit in a toolbox. The amount of items that can actually fit in a toolbox now has been drastically reduced, to the point of making a toolbox not particularly a viable item.

**Comment by ANickelN** [comment]
I will fix this, the toolbox does not have proper length defined.
