### ISSUE TITLE
Elite zombie bio-operator disarm attack destroys items

### ISSUE THREAD

**Issue by Psiclops** [CleverRaven/Cataclysm-DDA#48403]
# When the elite zombie bio-operator "grabs your weapon and throws it to the ground", often the item is completely gone.

# Steps To Reproduce

# Expected behavior

By the text that happens, the item should be found on the ground nearby, but often is not.

In 3 tests, 2 out of 3 disarming moves by the elite.... cause the item to disappear.
Once was a gun, once was a melee weapon, the correctly functioning time was an identical melee weapon that did not disappear.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-10212-gb725af3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm]
]

**Comment by Psiclops** [comment]
Thinking back, its possible this is happening near walls, as I was in the new one level "lab" all the times it has happened.

**Comment by Zireael07** [comment]
Hm, maybe it's trying to put the item in the wall or something weird like that?

**Comment by ZhilkinSerg** [comment]
Yeah - there is no check for free space:

https://github.com/CleverRaven/Cataclysm-DDA/blob/89a9480e68cc63c8d7877dba665b9c48658ed6d6/src/monattack.cpp#L5374-L5376

**Comment by actual-nh** [comment]
Suggestion: If there isn't any free space at the randomly-selected point, put it in the square of the zombie bio-operator.

**Comment by RenechCDDA** [comment]
No monster uses this attack anymore but mattack::bio_op_disarm is still in the code and docs, so still (vaguely) relevant.
