### ISSUE TITLE
Add a kitchen timer to the game

### ISSUE THREAD

**Issue by O1OOO1O** [CleverRaven/Cataclysm-DDA#48402]
A kitchen timer is a typical old-style wind-up timer that lets you select anywhere from 30 seconds to 60 minutes before it rings excessively for a while. 

Does not require electricity/battery.
Set, it. throw it and wait for the noise distraction to do its job.
https://comicbook.com/tv-shows/news/the-walking-dead-1019-one-more-aaron-gabriel-season-5-callback-enid-timer/

Disassembling would yield plastic chunks, a spring, and a bell (if bells are a thing) and/or scrap metal

**Comment by O1OOO1O** [comment]
Springs are described as "A large, heavy-duty spring. Expands with significant force when compressed." A kitchen timer would not have a spring of this quality within it, but a "small spring" item does not appear to exist.

**Comment by Entity-y** [comment]
Perhaps we could use it with a bundle of dynamite to make a Fallout New Vegas time bomb.
![image](https://user-images.githubusercontent.com/50155659/113908670-ccb86780-97a4-11eb-9a36-36d379713f45.png)

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
