### ISSUE TITLE
Add Ceramic Shards as a OR component to the Pebble recipe.

### ISSUE THREAD

**Issue by O1OOO1O** [CleverRaven/Cataclysm-DDA#48400]
They're basically sharp jagged variations of rock. They can become more useful if they are added to the existing pebble recipe, which already requires a hammer. I imagine you are breaking the shards up into smaller more manageable pieces without the sharp edges.

**Comment by Zireael07** [comment]
Shards are sharp while pebbles are round... so a no-go from my pov.

**Comment by O1OOO1O** [comment]
As I stated in the OP the idea is that you are using the hammer to break off off the sharp edges.  Do you think rocks and flint, the existing recipe, wouldn't have sharp edges on them also, or produce sharp edge when first broken? (ones that then get broken off further via the hammer tool requirement)

**Comment by actual-nh** [comment]
I suggest taking a look at #47211.
