### ISSUE TITLE
Spice up your night visits to town with Solar Motion Street/Security Lights

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#48413]
# Describe the solution you'd like
I think it would be FUN (as in df) to have motion triggered lights. This could be used for street lightning ("smart cities") or as security features in houses/pools. 
A % of those lights that are solar based would probably still work and would be a great addition to your ninja-ish night trip downtown.

Examples: https://cleanenergysummit.org/best-solar-street-lights/
https://cleanenergysummit.org/best-solar-motion-security-lights/

**Comment by ZhilkinSerg** [comment]
Is it a thing in New England?

**Comment by Entity-y** [comment]
I could see this fitting in nicely whenever the game gets a proper power grid. Solar houses or houses with backup natural gas generators would almost certainly have smart lights equipped. Even something as small as a solar lawn light around flower beds or driveways would be a nice touch.

**Comment by matt32106** [comment]
> Is it a thing in New England?

Idk but it is getting relatively commonplace in western europe so I guess New England must have it too.

**Comment by matt32106** [comment]
> whenever the game gets a proper power grid.

I was talking about self-powered solar lights i.e. not needing a power grid. I have added some example gear in my first post.
