### ISSUE TITLE
Bicycles become permanently stuck if handbrake is used while on ramp.

### ISSUE THREAD

**Issue by ifffrt** [CleverRaven/Cataclysm-DDA#48419]
# Describe the bug

Bicycles can become permanently stuck if you use the handbrake while it's standing on a ramp.

# Steps To Reproduce

1. Find a house with a ramp, recommending the technomancer house in magiclysm since it provides both a large ramp and usually a bicycle.
2. Drive it up the ramp. When the bicycle has cleared the ramp, immediately press the handbrake button.
3. The bicycle is now for all intents and purposes permanently broken. You can grab it with "G" and take it off the ramp, but if you try to actually steer it or change speed the game would stop you immediately with a message saying "You can't turn the vehicle while on a ramp" (see attached save file).

# Expected behavior

This shouldn't happen. 

# Screenshots

![New Bitmap Image (3)](https://user-images.githubusercontent.com/74819253/113940634-f666a280-9827-11eb-8981-1daaba4fa7bd.jpg)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-10342-g8286e1d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key],
    Graphical Overmap [Graphical_Overmap],
    sees-player icon, retrodays [sees_player_retro],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    Mythical Martial Arts [MMA],
    More Survivor Stuff [more_survivor_stuff],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    No Fungal Monsters [No_Fungi]
]

# Additional context

[savefile.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6274756/savefile.zip)

**Comment by actual-nh** [comment]
Appears to be another version of #48148. Ping: @mlangsdorf?

**Comment by ifffrt** [comment]
Saving and reloading fixed it! Should have tried that sooner.
