### ISSUE TITLE
Better error log for "Duplicate entries in the professions array "

### ISSUE THREAD

**Issue by linonetwo** [CleverRaven/Cataclysm-DDA#48411]
# Is your feature request related to a problem? Please describe.
I got Duplicate entries in the professions array after install tons of mods from Kenan's mod pack.

 DEBUG    : Duplicate entries in the professions array.

 FUNCTION : void scenario::check_definition() const
 FILE     : src/scenario.cpp
 LINE     : 188

# Describe the solution you'd like
Hope I can get clear message about which id is duplicate, so I can fix it or issue Kenan,

# Describe alternatives you've considered
Maybe just don't Error out, just ignore this error silently, since we are not able to fix it?

**Comment by ZhilkinSerg** [comment]
Adding output of offending profession id on that line is trivial.

**Comment by linonetwo** [comment]
thanks for encourage, I will take time to try this.
