### ISSUE TITLE
Broken arms taekwondo fix

### ISSUE THREAD

**Issue by aragonasx** [CleverRaven/Cataclysm-DDA#48410]
# Is your feature request related to a problem? Please describe.
Taekwondo is a martial art which uses kicks for attacks and etc, and if you have both broken arms currently you deal no damage to any monster like only 2 damage, even though you have no negative stat penalties and etc, beside arm encumberance but that shouldn't be important to that martial art.

# Describe the solution you'd like
The fix would be that damage shouldn't be affected on taekwondo if you have both broken arms, since you use kicks to attack.

# Describe alternatives you've considered
At bare minimum the damage should be increased on taekwondo if both arms are broken cause dealing 2 damage with 16 strength is absurd.

# Additional context
When I had my arms broken, I splinted them and recovered myself from pain to not have any stat penalties (my arms are still broken) and when I hit something it only does 2 damage, which doesn't make any sense.

**Comment by robotic-gamer** [comment]
I think it would sense to add kicking to "force unarmed" too since its also mainly kicks and with both broken arms it would give some way to defend yourself even without Taekwondo.

**Comment by OliveChukar** [comment]
Tested on 0.E-10347-gf914621 [64-bit]. Broke both arms and fought a zombie with taekwondo with 8 strength 0unarmed and 0melee damage was always 1 or 2. With 20 strength 20unarmed and 20melee damage was 3 to 7. With 20 strength 20unarmed and 20melee and healthy arms damage was over consistently over 20.  

The description of the fighting style says that taekwondo uses the arms for defense and attacks with the legs so it seems that broken arms should result in the player not dealing much less damage but taking more.

**Comment by aragonasx** [comment]
Exactly

**Comment by actual-nh** [comment]
I suggest that the player should also be missing more - your balance is going to get thrown off by splints, among other things.
