### ISSUE TITLE
Need a single key to to clear pocket auto pickup settings

### ISSUE THREAD

**Issue by gcaliber** [CleverRaven/Cataclysm-DDA#48417]
There is nothing that tells you that to remove whitelist/blacklist items from a pocket you have to select them again. Even after figuring this out, if you have a lot of these and want to clear them from an item it is very tedious.

There should be a single key that clears all the pocket settings, probably with an "are you sure" confirmation.

At the very least this screen needs to tell you to select an item again to remove it.

**Comment by ANickelN** [comment]
This would be a nice QoL feature for those that tend to dive deeper into the pocket settings.

**Comment by matshou** [comment]
@ANickelN If you like to tinker with pocket settings you will love https://github.com/CleverRaven/Cataclysm-DDA/pull/54812
