### ISSUE TITLE
visible secret cabin roof

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#48424]
# Describe the bug

the secret cult cabin in the woods has a normal cabin roof on the overmap making its location obvious

# Steps To Reproduce

1)find secret cabin
2)observe roof is visible

# Expected behavior

the cabin roof of the cult cabin being marked as open air

# Versions and configuration

cataclysmdda-0.E-Windows_x64-Tiles-11492

 - Mods loaded: [e.g.dda, boats, hacktheplanet, StatsThroughSkills]
-disable npc needs
-bionic professions
-Simple_additions
-alternative Map Key
-C.R.I.T Expansion Mod
-Blaze Industries
-Stats Through Skills
-Bionic Slots

**Comment by Venera3** [comment]
I changed the whole thing over to show as a normal cabin on the overmap when rebalancing  the overmap specials in general. Apart from two exceptions there are no "hidden" specials anymore, not that half the players didn't abuse the land use code mode to reveal them anyway.

**Comment by actual-nh** [comment]
> Apart from two exceptions there are no "hidden" specials anymore

What are the exceptions, BTW?

**Comment by Venera3** [comment]
||The central lab's manhole and lab vents.|| Everything else is obfuscated at most - bandit versions of garages/cabins show up as normal ones, for example.
