### ISSUE TITLE
universal awareness of npc

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#48435]
# Describe the bug

npc names are indicated on the overmap even if the tile is unexplored

# Steps To Reproduce

on the overmap scroll over unexplored tiles likely to contain npcs (based on the road layout) until you find one

# Expected behavior

npcs being less visible
-you straight up shouldn't see npcs if the tile is unexplored
-you should really only see npcs if you have talked to them
-or visibly seen them (in the case of bandits)
# Screenshots

![image](https://user-images.githubusercontent.com/78816055/114082160-6fdbb080-987b-11eb-8d61-87b4dd9336fe.png)

# Versions and configuration

 - OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-10281-ge365124 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Simple_additions [simple_additions],
    Alternative Map Key [alt_map_key],
    C.R.I.T Expansion Mod [crt_expansion],
    Blaze Industries [blazeindustries],
    Stats Through Skills [StatsThroughSkills],
    Bionic Slots [cbm_slots]
]

**Comment by Entity-y** [comment]
I like how zombie hordes are displayed on the map, you can't see them unless you've had view of them. Maybe something similar could work out for NPCs.

**Comment by RenechCDDA** [comment]
Resolved by #50190

Specific relevant code:
https://github.com/CleverRaven/Cataclysm-DDA/blob/9afa65ce6bbaf3bb96f12cb0ce9046d096c04667/src/sdltiles.cpp#L1037-L1040
