### ISSUE TITLE
Pumps at airports have wrong fuel

### ISSUE THREAD

**Issue by YourCompanionCube** [CleverRaven/Cataclysm-DDA#48434]
# Describe the bug
Pumps at airports have diesel and gasoline and no avgas

# Steps To Reproduce
Find an airport, 'e'xamine pumps

# Expected behavior
Pumps on runway to have fuels appropriate to aircraft like avgas and JP8 

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-10342-g8286e1d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    No Rail Stations [No_Rail_Stations],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Useful Helicopters [useful_helicopters]
]

# Additional context
100L drums of avgas do spawn in the hangars just fine

We don't have things like Jet A-1 or kerosene in game so avgas (and possibly JP-8, or maybe diesel) should be at airports

**Comment by YourCompanionCube** [comment]
Closed by https://github.com/CleverRaven/Cataclysm-DDA/pull/48458

**Comment by Night-Pryanik** [comment]
The PR isn't merged yet.

**Comment by anothersimulacrum** [comment]
The PR has been merged since then.

**Comment by Night-Pryanik** [comment]
Well, it was merged if 0.F-dev, so in master the bug is still present.
