### ISSUE TITLE
Weapon Balance

### ISSUE THREAD

**Issue by souricelle** [CleverRaven/Cataclysm-DDA#48432]
# Is your feature request related to a problem? Please describe.

Among the 3 melee weapon types, there's a pretty broad (if not universal) consensus that blunt weapons are strongly advantaged over cut. There are fewer complaints about stab weapons, but swords and especially medium to small swords have been left out in the cold by the armor changes from a while back, while simple blunt weapons like the cudgel are incredibly good at shutting enemies down and easily killing them.

The problem as I see it mainly comes down to two factors:

1) Enemy armor stops many cut weapons and natural attacks cold, regardless of skill. The argument could be made that cut is intended for unarmored enemies, but blunt weapons are just as good at killing those, so why bother? A nodachi or a zweihander can overcome this gap but your options are very limited.

2) The special attacks on blunt weapons proc way too often and easily, and can shut even boss-level monsters down. Because blunt weapons get through armor very easily, you see things like characters with 3 melee skill stunlocking juggernauts with a cudgel they made on day 1.

# Describe the solution you'd like

The first issue could potentially be solved by adjusting the armor penetration cutting weapons get from high Cut skill. I'm not sure this would apply to cut-based mutations like Fangs or Claws, but if it did this could make cut generally a more viable lategame contender. As far as I know this armor-piercing ability was not adjusted when enemy armor values were recalculated, but if it was I don't think enough was done to help it scale. The skill-based bonuses suggest a paradigm where blunt weapons are better for unskilled people and cut for well-trained fighters, and this would play into that nicely.

The second issue could come down to making the bash specials (sweep, precise strike, brutal strike, etc) need to deal more than a certain percentage of the target's current HP to proc, or to have a worse chance of proccing if they didn't. This would make large blunt weapons like sledgehammers retain their stopping power, but cudgels and shillelaghs etc would be less effective against durable enemies unless they'd been worn down already. 

None of this of course means that everything needs to be equal, or that bashing weapons shouldn't be the superior choice for armored enemies, I just think things are a little too far in bash's favor in all circumstances and players are being discouraged from tactically diversifying.

# Describe alternatives you've considered

Not doing anything, waiting for some other combat overhaul IE vitals, cherrypicking things like the cudgel and removing their specials.

**Comment by ThomasLinkin** [comment]
not a contributor, but i figure your second issue's solution will be hard to do, since it night make this a complete overhaul in weapon system and i think that's bit too much work to be done. right now we are in 0.F release process, so to say that your idea is wrong isnt correct. more like not the right time. maybe you can bring this up again after the release of 0.F ?

**Comment by souricelle** [comment]
We're not holding back on considering or adding changes at this time, plenty of extensive work is being done on the game.

**Comment by actual-nh** [comment]
I can understand ThomasLinkin's confusion - there is also a 0.F-dev branch that PRs that, for one reason or another, can't go into the master branch, are going into. This is so that other development work doesn't stop. (It's not an ideal system - switching something meant for master into 0.F-dev can be tricky, and distinguishing what should go where can have miscommunications - but it does help.)

**Comment by RDru** [comment]
I don't think the game needs super balance. If all weapons are equal then what's the point of different weapons. Also the game follows realism and in-real you cannot simply cut metal plates or kevlar armor - you need to find other means to penetrate it. And lastly having different enemies of different difficulties is healthy for gameplay. That's my point of view.

**Comment by actual-nh** [comment]
> I don't think the game needs super balance. If all weapons are equal then what's the point of different weapons.

I don't think souricelle is asking for all of them being the same - just that different ones have uses in different situations, which is perfectly realistic (something for dealing with multiple "normal" zombies and something for dealing with one fiend should be different items).

> Also the game follows realism and in-real you cannot simply cut metal plates or kevlar armor - you need to find other means to penetrate it.

Kevlar alone is susceptible to cutting attacks, actually (and even more so to stabbing attacks); note that people behind the deli counter slicing things are (supposed to be) using chainmail gloves.

> And lastly having different enemies of different difficulties is healthy for gameplay. That's my point of view.

I'm not sure how this would make enemies less-differing in difficulty, particularly for a survivor with some weapon skills - or weapons, including potentially different ammo types - but not all of them.

**Comment by ThomasLinkin** [comment]
> I don't think the game needs super balance. If all weapons are equal then what's the point of different weapons. Also the game follows realism and in-real you cannot simply cut metal plates or kevlar armor - you need to find other means to penetrate it. And lastly having different enemies of different difficulties is healthy for gameplay. That's my point of view.

his idea was to buff cut weapon and debuff blunt, or find a way to balance these since blunt weapons are OP while cut aren't.

**Comment by kevingranade** [comment]
The rationale is terminally flawed. Despite claiming otherwise, the rationale as presented is, "cutting weapons need to be better to force them to have a niche".
