### ISSUE TITLE
A 9" sheet of glass weighs 68.89 lbs....

### ISSUE THREAD

**Issue by O1OOO1O** [CleverRaven/Cataclysm-DDA#48447]
# Describe the bug

A sheet of glass described as being 9" long weighs 68.89 lbs. 
How large and thick is a sheet of glass supposed to represent given most uses of them is for making windows/skylights?
This is not realistic.

# Steps To Reproduce
View a sheet of glass in your inventory.

# Expected behavior
Glass sheets should conform to more realistic dimensions and weight.
Here are some weight examples:
https://www.optimumcut.com/cms/glass-weight-technical-data-creation-glazing-specifications-optimumcut-1d-v3/

If you had a rather large 5 ft by 5 ft window area (25 square feet) at 1/8th inch thick you'd get a weight of 40.5 lbs.
Note that 1/8" inches are in fact larger than the average thickness of residential window glass pane, which is 3/32nd, (so 25% less material, thus in reality about 30.375 lbs.) A 5x5 foot window is also extremely large for a window but I'm not sure how tile dimensions are interpreted but even a smaller window size than that could still handle a human-sized person climbing through it.

Then there is the matter of the longest side mention on the glass sheet. 9" is definitely not right for the weight. Either many much lighter-weight glass sheets need to be used in making a large window or the length is too short for what is intended to be represented.

# Screenshots
![glass](https://user-images.githubusercontent.com/82064797/114215634-70338480-992b-11eb-9075-3acdc418d130.jpg)

# Versions and configuration
12:00:30.159 :  GAME REPORT:
- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-10361-gfa0b7d6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Desert Region [desertpack],
    Disable NPC Needs [no_npc_food],
    Generic Guns [generic_guns],
    Alternative Map Key [alt_map_key],
    Graphical Overmap [Graphical_Overmap],
    Bionic Slots [cbm_slots],
    Fuji's Military Profession Pack [fuji_mpp],
    Stats Through Skills [StatsThroughSkills],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    Gun Cotton [guncotton],
    Useful Helicopters [useful_helicopters],
    Mining Mod [Mining_Mod]
]

# Additional context
https://www.optimumcut.com/cms/glass-weight-technical-data-creation-glazing-specifications-optimumcut-1d-v3/
https://www.google.com/search?client=firefox-b-1-d&q=average+thickness+of+residential+window+glass

**Comment by ANickelN** [comment]
I can fix the length in an upcoming PR, what should the weight be cut down to in your opinion considering a 3/32 residential panel that is around 3 feet by 4 feet?

**Comment by O1OOO1O** [comment]
going by the chart I referenced a 3x4 ft (12 square foot) sheet of 3/32 thick glass should be 14.58 lbs.

**Comment by O1OOO1O** [comment]
![npcneeds](https://user-images.githubusercontent.com/82064797/114276066-a6840900-99ea-11eb-8125-908ecc3ea7da.jpg)
If they still require sleep then the description should be changed to "Make NPC's not require food or water"

**Comment by ANickelN** [comment]
You can close this issue, it was fixed by #48449
