### ISSUE TITLE
Item Action Menu "start fire quickly" problems

### ISSUE THREAD

**Issue by RDru** [CleverRaven/Cataclysm-DDA#48443]
# Describe the bug

Item Action Menu (default %) 
1. Menu sometimes uses different key under defined 'f' key (see screenshot). Sometimes there is dangerous action there.
2. Start fire quickly sometimes is not available (it's greyed out) despite having a lighter or other fire sources in inventory. 
3. In the sun the default item with lens is used, like telescope, but sometimes there is not enough light to start fire quickly and it takes a long time. I propose removing lens using from this menu and increasing the time to start a fire through lenses since in real it usually takes more than few seconds.

# Steps To Reproduce

1. Save included. No idea how to reproduce.
2. Load it, press % and check what's under f key.

# Expected behavior

1. On defined key should always be action that the key defines. Other actions should not overwrite it.
2. Same as 1.
3. Either it's always fast or other item is used or there is no action to use.

# Screenshots

![1](https://user-images.githubusercontent.com/26722636/114189611-acc2a880-994a-11eb-8b7a-215f8ea43ef2.png)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-10361-gfa0b7d6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    Alternative Map Key [alt_map_key]
]

# Additional context

[11572_test.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6286197/11572_test.zip)

**Comment by OliveChukar** [comment]
Tested on 0.E-10383-gad91f6a [64-bit] with Dark Days Ahead [dda] only no mods. Was not able to replicate with a fresh save.  With provided save the interface was as shown in the picture. I was able to get the interface back to normal by dropping most of the items that the character was carrying.

I think the starting fire with lenses thing is a separate issue.

**Comment by int-ua** [comment]
Please comment if you are still experiencing this issue and we'll reopen it.
