### ISSUE TITLE
Incompatible mutations are possible to obtain together

### ISSUE THREAD

**Issue by Dhanvanthri** [CleverRaven/Cataclysm-DDA#48441]
# Describe the bug

There are some threshold traits, notably Unassuming, that don't prevent conflicting traits (like freakishly huge) from rolling. 
Other examples include: 
Eater of the dead and Herbivore/Ruminant etc, 
Metabolic Rehydration (it says not purifiable) getting overwritten by high thirst etc

# Steps To Reproduce

Make a new character, cross the diminutive threshold and get all the relevant mutations, then spam ursine mutagen.

# Expected behavior

As Freakishly huge gets cancelled by Unassuming, so should Unassuming be cancelled by freakishly huge/prevent freakishly huge from rolling (since it's a post threshold mutation)

# Versions and configuration

 - OS: Debian Buster
 - Game Version: 0.E 10282-gf22beb8
 - Graphics version: Tiles
 - Ingame language: English
  - Mods loaded: Blazemod, Crit expansion, Fuji Military professions, Bionic Professions, Alt Map Key, Disable NPC Needs
 
# Additional context

I think that in addition to the cancel flags that mutations have relative to each other, that there should be an excludes/precludes tag, specifically for thresholds, that prevent conflicting mutations from rolling.

**Comment by Dhanvanthri** [comment]
This is also true for near sighted and scout, and also interacts badly with bionics. 

Ex, near sighted doesn't cancel scout

Also I just tested that although telescopic eyes will fix all your maluses on installation, it's possible to still mutate near sightedness once it's installed.

**Comment by Salty-Panda** [comment]
Probably #47117 doesn't cover all combinations

**Comment by actual-nh** [comment]
> Probably fixed by #47117, it's merged do 0F dev

The bionics part may well have been. I doubt it on the mutation-mutation interactions.

**Comment by Dhanvanthri** [comment]
I could work on this if someone would point me in the right direction, I searched through all the files in src with the "mutation" keyword in the file name, and I couldn't find any references to any of the categories (was looking for diminutive/mouse/chaos/chimera), I did see lots of matches for "cancel" but I wasn't able to figure what they did without context.

I think the correct solution is just to make mutations that are non-purifiable preclude mutations that cancel them.

**Comment by actual-nh** [comment]
> I could work on this if someone would point me in the right direction, I searched through all the files in src with the "mutation" keyword in the file name,

"src" or "data/json/mutations"?

> and I couldn't find any references to any of the categories (was looking for diminutive/mouse/chaos/chimera), I did see lots of matches for "cancel" but I wasn't able to figure what they did without context.

"cancel" doesn't point at categories - it points at specific mutations that are removed (as opposed to replaced by a further development of something, IIRC).

> I think the correct solution is just to make mutations that are non-purifiable preclude mutations that cancel them.

Sounds reasonable.

> I notice that all the non-purifiable mutations are gated behind thresholds. So if the threshold mutations themselves are hardcoded to exclude each other, this rule would encompass that condition as well whilst fixing my original problem.

Is that true for things that can be starting traits?

> In the specific case of freakishly large and unassuming however, the problem is just that freakishly large doesn't cancel unassuming, although unassuming cancels freakishly large. Wherever this condition is recorded is the file that I presumably need to edit.

Probably data/json/mutations/mutations.json.

**Comment by Dhanvanthri** [comment]
> > I could work on this if someone would point me in the right direction, I searched through all the files in src with the "mutation" keyword in the file name,
> 
> "src" or "data/json/mutations"?
>  I looked at src, but I'll look at /data/json/mutations and figure it out. Ty!
> > and I couldn't find any references to any of the categories (was looking for diminutive/mouse/chaos/chimera), I did see lots of matches for "cancel" but I wasn't able to figure what they did without context.
> 
> "cancel" doesn't point at categories - it points at specific mutations that are removed (as opposed to replaced by a further development of something, IIRC).
> 
> > I think the correct solution is just to make mutations that are non-purifiable preclude mutations that cancel them.
> 
> Sounds reasonable.
> 
> > I notice that all the non-purifiable mutations are gated behind thresholds. So if the threshold mutations themselves are hardcoded to exclude each other, this rule would encompass that condition as well whilst fixing my original problem.
> 
> Is that true for things that can be starting traits?
> This isn't true for starting traits, but I think the same rule can be applied to them for the same reason. In my mind, the non-purifiable tag represents those innate attributes of the genetic structure that can't be changed any more. Like once you get deadened, you're nerves are no longer capable of working like the once did. You can't mutate back the sensation of pain.
> > In the specific case of freakishly large and unassuming however, the problem is just that freakishly large doesn't cancel unassuming, although unassuming cancels freakishly large. Wherever this condition is recorded is the file that I presumably need to edit.
> 
> Probably data/json/mutations/mutations.json.

Thanks for these, I will take a look at the json file, and then report back!

**Comment by Dhanvanthri** [comment]
This isn't true for traits, but I think the same rule should be applied. Imo, the non-purifiable tag represents genetic changes that your body can no longer reverse. You can't get a sensation of pain back once you've become deadened.

I will take a look at the json file you've mentioned and see what I can do. 

Thanks a lot for your help!

**Comment by Dhanvanthri** [comment]
Do the new mutation type systems solve this problem? Since all these mutations are now under the bucket of Size?
