### ISSUE TITLE
Small vacuum oven has unrealistic weight

### ISSUE THREAD

**Issue by SolsticeTheTechMarine** [CleverRaven/Cataclysm-DDA#48456]
# Describe the bug
I found a small vacuum oven on a dead scientists overmap feature. I think that the weight is a little ridiculous. 
![image](https://user-images.githubusercontent.com/38237593/114259782-427b2980-9985-11eb-8784-bf4c928ecb4b.png)

# Expected behavior

Doing some research, I found that a modern 0.9 cubic foot vacuum oven would weigh far less than what is represented in game. Weights vary among units, but they seem to be around 120 to 130 pounds.

I gathered three examples from various shopping websites:
https://www.amazon.com/Across-International-AT09p7-110-Vacuum-Heating/dp/B07L8NDHJG
![image](https://user-images.githubusercontent.com/38237593/114259963-ab16d600-9986-11eb-82ee-f64e3ae26b1c.png)
**120.0 Pounds**
https://www.ebay.com/itm/US-Shipping-Commercial-0-9Cu-ft-Vacuum-Drying-Oven-Table-Top-New-Drying-Oven-/202736273547
![image](https://user-images.githubusercontent.com/38237593/114259977-c71a7780-9986-11eb-9d66-af3931b2f2a4.png)
**128.0 Pounds**
https://www.ebay.com/itm/282535766688?chn=ps&norover=1&mkevt=1&mkrid=711-117182-37290-0&mkcid=2&itemid=282535766688&targetid=1068323860470&device=c&mktype=pla&googleloc=9032466&poi=&campaignid=11758020206&mkgroupid=111348621262&rlsatarget=pla-1068323860470&abcId=9300462&merchantid=101757415
![image](https://user-images.githubusercontent.com/38237593/114260068-71929a80-9987-11eb-86db-49e77dfd09f2.png)
**120.0 Pounds**

# Version Info
Version: 0.E-10188-gd02fc13 (tiles)
Build: 11543

**Comment by actual-nh** [comment]
That's with the vacuum pump?

**Comment by SolsticeTheTechMarine** [comment]
I realized after looking a little closer at the in game item, that most of the weight was due to a large storage battery.
