### ISSUE TITLE
Seg fault when using filter to search for specific items to clean

### ISSUE THREAD

**Issue by O1OOO1O** [CleverRaven/Cataclysm-DDA#48457]
# Describe the bug
Get a seg fault error and crash when I activate a washing kit near a very large pile of filthy items. I use filter to find a select a pair of binoculars, I then change the filter to select 'pads' to find elbow and knee pads to wash, but after hitting return to change the filter the game crashes with a seg fault error.

# Steps To Reproduce
Load the save
Active the nearby washing kit and filter 'bin' to find the binoculars and select them to be added to the wash items.
Change the filter to 'pads' and hit return, get seg fault.
# Expected behavior
The ability to change your filter and it remembers your prior selections as you add additional items based on new filter searches.

# Screenshots
![segfault_washing](https://user-images.githubusercontent.com/82064797/114260395-26ce4e00-999a-11eb-8ece-a6c7ffddffeb.jpg)

# Versions and configuration
12:00:30.159 :  GAME REPORT:
- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-10361-gfa0b7d6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Desert Region [desertpack],
    Disable NPC Needs [no_npc_food],
    Generic Guns [generic_guns],
    Alternative Map Key [alt_map_key],
    Graphical Overmap [Graphical_Overmap],
    Bionic Slots [cbm_slots],
    Fuji's Military Profession Pack [fuji_mpp],
    Stats Through Skills [StatsThroughSkills],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    Gun Cotton [guncotton],
    Useful Helicopters [useful_helicopters],
    Mining Mod [Mining_Mod]
]

# Additional context
[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6289332/config.zip)
[Portage Lakes.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6289334/Portage.Lakes.zip)

**Comment by OliveChukar** [comment]
Tested on 0.E-10383-gad91f6a [64-bit] with Dark Days Ahead [dda] only no mods. I did not use the included save. I spawned in many creatures then killed them then activated a washing kit. Filtered items and selected them then changed the filter and selected more. After several changes of the filter the game crashed.

**Comment by RoyBerube** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/5594c87b21cc9465991507cac0828d71fa2426e0/src/inventory_ui.cpp#L2510

This is where the problem comes from.  The `inventory_entry` gets used as a reference by the variable `to_use`, but `inventory_entry ` gets expunged after applying a filter. So `to_use` ends up pointing to some invalid locations and causes the nullptr crash.

**Comment by RoyBerube** [comment]
Am finishing up a fix for this. Should have it submitted today after doing some more testing.
