### ISSUE TITLE
issues with barred windows

### ISSUE THREAD

**Issue by jagoly** [CleverRaven/Cataclysm-DDA#48453]
# Describe the bug

There are a number of issues with barred windows and their variants. The issues centre around the fact that the base tile, t_window_bars, has glass, as opposed to being just a frame.
 - other variants when smashed turn into this tile, when they do glass shards are dropped
 - but t_window_bars still has glass, only the alarm or curtains has disappeared 
 - t_window_bars name "window frame with metal bars" implies it is just a frame 

# Steps To Reproduce

Smash an alarmed window, see that it creates glass shards, but then see that the glass is still there in the window.

# Expected behavior

- A new terrain, t_window_bars_noglass, should be added to match other window types
- t_window_bars should have "frame" removed from its name
- t_window_bars as well as alarm/curtains/domestic variants should be changed to bash into noglass variant

# Versions and configuration

Latest git.

**Comment by actual-nh** [comment]
May be fixed by #48408 (for 0.F-dev, unfortunately).
