### ISSUE TITLE
[S]mashing fences completely turns dirt tiles into rock floors.  

### ISSUE THREAD

**Issue by Cpl-Jordan** [CleverRaven/Cataclysm-DDA#48452]
# Describe the bug
[S]mashing any fence completely in the game causes the dirt tiles, asphalt, ect. where they where build on into rock floors.

# Steps To Reproduce
1.) Find Fence
2.) [S]mash fence completely
3.) See the ground where the fence was built on turn to rock floor.

# Expected behavior
Smashing fences should retain the ground from it was built on.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-10361-gfa0b7d6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context
Just a question is there a way to turn a rock floor into dirt without having to use the debug mode?

**Comment by robotic-gamer** [comment]
-I casually tested it in my game (cataclysmdda-0.E-Windows_x64-Tiles-11560)
and it left dirt
-is there something under where you smashed like a basement or something?
-I have observed that sometimes if there is something other then a wall like solid rock under it, it can revert to some sort of roof

**Comment by Cpl-Jordan** [comment]
> -I casually tested it in my game (cataclysmdda-0.E-Windows_x64-Tiles-11560)
> and it left dirt
> -is there something under where you smashed like a basement or something?
> -I have observed that sometimes if there is something other then a wall like solid rock under it, it can revert to some sort of roof

I tested smashing some farm fencing with nothing underground and it caused the dirt tiles to turn to rock floors. I could be wrong but I think you are running on a previous version of the experimental build.

**Comment by robotic-gamer** [comment]
-my version I'm running was from 2021-04-03 12:42, (about 6 days ago).
good the most recent version I could (cataclysmdda-0.E-Windows_x64-Tiles-11572)
[-from:](http://dev.narc.ro/cataclysm/jenkins-latest/Windows_x64/Tiles/)
and I encountered the bug making then smashing fence posts.
It appears this is a new bug that occurred in the last 12ish releases.

**Comment by Night-Pryanik** [comment]
The fences is a _terrain_, so there's could not be anything _underneath_ them in game terms. Fences turning into a rock floor on smashing looks like a bug, though, as it should turn into `t_null`.

This issue is possible duplicate of #27316.

**Comment by actual-nh** [comment]
It's actually worse than #27316 - it isn't that it's a hardwired map extra causing problems, it's something that's fully JSONized having problems. Specifying what "t_null" should actually _be_ on a map seems to be a more general problem.

**Comment by robotic-gamer** [comment]
by underneath I meant by z-level
-awhile back before planters you could have dirt on roofs by building walls directly underneath (by z-level) then building then mining a wall on the roof
-similarly building then mining out a wall overtop (by z-level) an empty space would result in dirt being replaced by flat roof
