### ISSUE TITLE
Torch disappears upon activation

### ISSUE THREAD

**Issue by Tommy-os** [CleverRaven/Cataclysm-DDA#48464]
# Describe the bug

Activating a torch (lighting in on fire) will produce a "You light the torch." message but the torch itself will disappear.

# Steps To Reproduce

1. Craft a torch
2. Activate the torch
3. Torch is now gone

# Expected behavior

Torch becoming a lit torch, not disappearing.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-10361-gfa0b7d6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    No Fungal Monsters [No_Fungi]
]

# Additional context

It appears to be a missing magazine and ammotype for the torch item, similar to how a candle has wax as ammo.

**Comment by actual-nh** [comment]
And/or a problem as with #48361, etc, if there are distinct not-on-fire and on-fire items; currently too groggy to check...

**Comment by Salty-Panda** [comment]
I recall there was another use-action, specifically for setting things on fire, used in currently obsoleted flaming weapons (shishkebab?)

**Comment by Salty-Panda** [comment]
Yup, it uses transform
a) add charges_per_use, easy solution
b) change it to use fireweapon_on/fireweapon_off - imo probably better solution, more suited because it handles extinguish etc

**Comment by actual-nh** [comment]
@Salty-Panda: Have you had a chance to work on this?

**Comment by Salty-Panda** [comment]
Was busy at work, will fix today/tomorrow
