### ISSUE TITLE
reconstituted milk makes less than you started with

### ISSUE THREAD

**Issue by YourCompanionCube** [CleverRaven/Cataclysm-DDA#48468]
# Describe the bug
crafting reconstituted milk from condensed milk results in fewer portions than is required to craft it

# Steps To Reproduce
look at the recipe 

# Expected behavior
that adding water to condensed milk would make more portions

# Screenshots
![image](https://user-images.githubusercontent.com/26364270/114278627-b60d4d00-99fe-11eb-9e30-eeb146eb4225.png)
![image](https://user-images.githubusercontent.com/26364270/114278631-bad20100-99fe-11eb-8ec7-6232fec858a3.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-10342-g8286e1d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    No Rail Stations [No_Rail_Stations],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Useful Helicopters [useful_helicopters],
    Gun Cotton [guncotton]
]

# Additional context
Some recipes also use condensed milk and reconstituted milk as if they were the same (using the same number of portions)

**Comment by GGgatherer** [comment]
I can't quite see what is wrong here. It all depends on portion sizes for rec.milk and cond.milk. Portions for different items can be of different sizes. Are they for those two?
If the end result had different mass or caloric value than the sum of its parts, that would be an obvious bug.

**Comment by YourCompanionCube** [comment]
the main issue being that i can craft less with the something i've *added* material to and that you should logically get more servings (but less calories per serving) by diluting it with water

**Comment by YourCompanionCube** [comment]
the actual issue is a can make more of a given recipe (the requires some form of milk) if i don't add water, which makes no sense

**Comment by PatrikLundell** [comment]
I agree that logically each condensed milk portion ought to result in a reconstituted milk portion, possibly with some calorie loss (although that ought to happen in the condensing step only). I can see a potential portion loss in the step where the water is removed from the milk to produce condensed milk, but not in the reverse step.
It doesn't make sense if the portions of the different stages would be of different "sizes" (obviously the condensed stage would be physically smaller, given that the water has been removed, but it ought to be the rough equivalent of the "size" of the other stages in terms of nutrients.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
