### ISSUE TITLE
Infection system is broken

### ISSUE THREAD

**Issue by AcidAntOnAMinefield** [CleverRaven/Cataclysm-DDA#48461]
# Describe the bug
Infection makes you go "tired" within 30-50 mins after getting it, Dead tired within 1 hour, exhausted within 2h. 

# Steps To Reproduce

1. Create a default test world with a flat hour start
2. Create a character with default stats and start an "Infected Scenario"
3. Debug yourself some sort of watch so you can see the time, then watch as you are essentially told you cant do anything within the first 30-50 minutes of the game.

# Expected behavior
The severity of the symptoms should increase much later than just 30 minutes after getting an infection - 4-6 hours would be a more realistic time - depending on whether antibiotics were taken or the wound was treated.

# Screenshots
None, this is easy to replicate.

# Versions and configuration
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-10361-gfa0b7d6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    No Ants [No_Anthills]
]

# Additional context

Infections do not work like the way it works in-game currently.
An Infected **wound** IRL wouldn't render you completely wasted within 30 mins to 2h of getting it, at most you'd have an itch to start with, and a fever would develop after **several** (not just 2) hours of it being left untreated. Should notice that the game refers to it as "an infected **bite wound**".  
An "internal infection" (respiratory or cardiovascular infections) would take several hours for the symptoms to manifest, and more for those symptoms to cause you to actually become bed-ridden as you are not immediately going to experience symptoms the moment it begins to develop, and 30 minutes is a very short time span for an infection to fully settle in, regardless of which body part is infected.

**Comment by ZhilkinSerg** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/projects/14

**Comment by Venera3** [comment]
See #47041 for the discussion of the current effect and the comments on #46947 for my rough plans regarding it in the mid-term as well.

**Comment by kevingranade** [comment]
Redundant with other issues as mentioned.
