### ISSUE TITLE
Fire damage with minimal fuel/intensity is too powerful

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#48466]
# Describe the bug

-lighting something on fire like a single piece of thread then lure a zombie on it which does large amounts of damage

# Steps To Reproduce

-set thread on fire
-lure zombie on it
-observe large amounts of damage

# Expected behavior

-fire immediately lit should not really do much damage

Do not take a screenshot of the crashing window. Please provide the crash logs in the "Additional context" -->

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-10281-ge365124 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Simple_additions [simple_additions],
    Alternative Map Key [alt_map_key],
    C.R.I.T Expansion Mod [crt_expansion],
    Blaze Industries [blazeindustries],
    Stats Through Skills [StatsThroughSkills],
    Bionic Slots [cbm_slots]
]

# Additional context

the easiest solution I can think of is a tier of fire below small fire that does little/no damage when stand on

edit: forgot reproduce step

**Comment by actual-nh** [comment]
You might try a title of something like "Fire damage with minimal fuel/intensity is too powerful".

**Comment by robotic-gamer** [comment]
done, thanks for advice on the title

**Comment by actual-nh** [comment]
Ping: @Aivean? Any thoughts?

**Comment by morthein** [comment]
Fire does need to be reviewed for sure. The damage is strange, when an NPC or even yourself runs through fire you slowly burn to death. When an enemy runs through it, they either die immediately or occasionally are able to just walk through it.  I would think they should begin taking fire damage like you (except those special zombies like the firemen, or the smoldering ones). Maybe if the zombies took burning damage instead of instant death, that could lead to scaling the damage based on the fire size, as mentioned.

**Comment by kevingranade** [comment]
My plan for years has been to break the fire field into two components, a "small fire" field that results from application of a firestarter that only consumes fuel on it's own tile, and a "large fire" field that both consumes fuel and spreads and causes damage as per the current fire fields.
In other words increase the dynamic range of fire fields and extend the time between starting a fire and the fire being a significant threat unless meaningful accelerant is used.
