### ISSUE TITLE
Pillows within pillowcases do not improve sleeping comfort

### ISSUE THREAD

**Issue by ferociousdork** [CleverRaven/Cataclysm-DDA#48463]
# Describe the bug

Pillows within pillowcases (more generally, any item with the SLEEP_AID flag contained within an item with the SLEEP_AID_CONTAINER flag) do not improve sleeping comfort.

# Steps To Reproduce

1. Spawn pillow and pillowcase.
2. Insert pillow into pillowcase.
3. Drop pillowcase on current tile.
4. Go to sleep.
5. No message about using an item for comfort.

# Expected behavior

There should be a message about using an item for comfort, e.g. "You use your pillowcase > pillow for comfort."

# Versions and configuration

- OS: Windows
    - OS Version: 6.1 7601
- Game Version: 0.E-10367-g47c9250-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

The code in [character.cpp:7010](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/character.cpp#L7010) checks `contents.size()`, which seems to count pockets, not items. Changing this to `contents.num_item_stacks()` seems to work (the comfort message appeared in-game), but I'm not familiar enough with the codebase to tell if this should be the proper check.

There's a duplicate of this check in [character.cpp:6953](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/character.cpp#L6953) that should also be changed.

**Comment by actual-nh** [comment]
Ping: @anothersimulacrum?

**Comment by AdamChirnside** [comment]
Can someone with contributor status mark this as confirmed? 
Pillows indeed do not appear to work while inside a pillowcase

**Comment by actual-nh** [comment]
> Can someone with contributor status mark this as confirmed?

Triage permissions, actually.

**Comment by AdamChirnside** [comment]
This issue can be closed; I had linked the wrong issue in my PR
