### ISSUE TITLE
Magiclysm Feature Request: Drop/stow weapon while attempting to cast spells that requires hands, then (toggleable) reequip weapon.

### ISSUE THREAD

**Issue by DillonSimeone** [CleverRaven/Cataclysm-DDA#48475]
# Is your feature request related to a problem? Please describe.
I'm always annoyed when I have to drop my weapon to cast spells such as piercing bolt to pop bloated zombies before they get too close. It wears out my fingers and keyboard!

# Describe the solution you'd like

It'd be great if a setting was added for that, auto drop/stow weapon while attempting to cast spells, and another option for reequipping those weapons. While either or both is enabled, the movement cost of either/both action is added to the spell cast time. 

Maybe something similar to toggleable fuel saving mode for bionics. 

(d) toggle drop weapon while attempting to use hands to cast
(s) toggle stow weapon while attempting to use hands to cast (Worthwhile if you have high blade, and a sheath for your blade, etc)
(r) toggle reequipping weapon afterward

![image](https://user-images.githubusercontent.com/21962421/114291103-7fa0f380-9a39-11eb-8361-550dff439eb2.png)

**Alternative idea**: Once you reach a level of mastery with a spell, you no longer need to move your fingers around. And maybe no longer need to chant phases, you just will the spell into existence. 

Halfway to mastery, no hands requirements. Mastery, no speech requirement. 

# Describe alternatives you've considered
Going unarmed always, using spell-focus weapons, or only using spells that doesn't require hands.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
