### ISSUE TITLE
M17 spawns with 10 round magazine

### ISSUE THREAD

**Issue by carmakazi** [CleverRaven/Cataclysm-DDA#48486]
# Is your feature request related to a problem? Please describe.
Despite being a primarily military spawn, the M17 pistol (and presumably the M18, as it references the code of the M17) appears to spawn in world with a reduced capacity 10-round magazine for restricted civilian use, rather than the full-capacity 17-round magazine that is standard.  This does not appear to apply to M17s given as character starting equipment, as the magazines/ammo are curated by the loadout.

# Describe the solution you'd like
Return the default magazine to the 17-round version.  I believe it is as simple as putting it first in the list of compatible magazines.  In fact, this issue likely came about when the 10-round magazine was added to the game, and it was logically put before the 17-rounder to follow ascending order.

# Describe alternatives you've considered
-Removing the 10 round magazine as an item altogether, though I do not think that is necessary and would cause more problems anyway.
-Make the default magazine the 21-round extended magazine.  From the limited pictures of it in military service, the extended mag seems to be a fairly common sight.  It might make the M17 a more interesting sidearm, but I don't think that's the direction to go either.

**Comment by davidfawcett** [comment]
PR: https://github.com/CleverRaven/Cataclysm-DDA/pull/49764
