### ISSUE TITLE
Overmap location descriptions idea.

### ISSUE THREAD

**Issue by RockCaster23** [CleverRaven/Cataclysm-DDA#48490]
(sorry for my poor English, isn't my mother language)
I've been playing CDDA a long time, and i think this feature should be at least considered. It can be useful when it comes to explore the world, and know your surrandings withou the fear of being eat. For example, when you press "e" in a overmap tile, an small Window appear, giving you some idea of what you will encounter if you went there. Like, if you inspect a hospital, the text will say that the place has been overrun by the undead, but it also has useful resources and first aid supplies.
 Or if you inspect mine. It say that is just a normal mine, but the player character feel that there's something wrong there, giving the player the hint that is not good idea went without proper preparation.

This is my first suggestion from any kind of game in github, sorry if i put some errors in the text but like i said, English isn't my mother language. Thank You anyway and have a nice day/afternoon/night.

**Comment by ANickelN** [comment]
Would be cool to have some text describing the location, probably only should appear AFTER you've been there for some buildings however...  Any text is better than none, and it would give some community members a creative outlet in the form of writing instead of coding!  📖

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
