### ISSUE TITLE
Zombie blood drawn by blood draw kits is safe to cosume. 

### ISSUE THREAD

**Issue by DillonSimeone** [CleverRaven/Cataclysm-DDA#48493]
# Describe the bug

Zombie blood turned out to be an excellent source of calories. There's no toxins in the blood too... And the blood isn't rotten! It's easy to balance out the health debuff by just eating some plants off the ground. 

Despite the item description saying that you'll be poisoned if you drink the blood, you don't get poisoned.

# Steps To Reproduce

1. New world, new powerful survivor
2. Spawn in a zombie, punch zombie into a fresh corpse
3. Spawn in blood kit, draw blood from zombie corpse
4. Consume blood
5. Repeat

# Expected behavior

It should be a **really** bad idea to drink zombie blood! 

# Screenshots

![image](https://user-images.githubusercontent.com/21962421/114381365-e3addf80-9b3f-11eb-86cc-ccbefd6d5202.png)

![image](https://user-images.githubusercontent.com/21962421/114381444-fb856380-9b3f-11eb-899f-9cee5460bff5.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-10321-g4e706d9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock]
]

# Additional context

**Comment by OliveChukar** [comment]
Tested on 0.E-10395-g4525b4f [64-bit] with Dark Days Ahead [dda] only no mods. I ate used blood draw kits on a zombie and a tough zombie when I ate the blood and did blood analysis with an autodoc I had no negative affects. I tried the same thing with a zombie soldier and a zombie scientist and got hemolytic parasites. I think the parasites were caused by the blood being raw.

**Comment by SenpaiSlime** [comment]
Tested it in unmodded X64 b15 and got both poisoned and food poisoning

**Comment by hexagonrecursion** [comment]
Confirmed. No poison or food poisoning from drinking zombie cop bood

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 17b9ea1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]
