### ISSUE TITLE
Don't tie hunger to calories

### ISSUE THREAD

**Issue by souricelle** [CleverRaven/Cataclysm-DDA#48492]
# Is your feature request related to a problem? Please describe.
People cannot seem to get their heads around the idea of hungry/very hungry. The discord and reddit are routinely full of players who are convinced that they're starving to death because the game is telling them they're **Very Hungry** in bright colored letters on their screen, when in fact they're simply losing a bit of weight. Slipping toward underweight is commonly seen as some kind of horrible catastrophe and not a harmless part of the normal flow of gameplay. They get frustrated when they eat a huge meal and half an hour later they're Very Hungry again, and they're right to say that this isn't exactly realistic.

# Describe the solution you'd like
Simply have the game tell you that you're hungry if your stomach has been empty for a while, and then have it tell you that you're very hungry if it's been empty for a day or so, with no respect to your BMI. You will be famished if you go for a couple days without eating. IRL, calorie deficit _does_ somewhat affect hunger, but overweight people can be very hungry and underweight people can fast without feeling like they're going to die. Players already have a calorie surplus/deficit indicator in their body weight. There's no need to have an additional flashing warning that you're losing weight when you can already see that you're underweight.

Everyone needs to eat regularly regardless of their body fat, and everyone will feel ill effects (such as the Jittery trait) from avoiding food even if they could stand to go on a diet. Currently an obese person can just feel mildly hungry while fasting for a month straight, which makes zero sense. After a day or two, anyone who wasn't intentionally fasting (and even then sometimes) would be desperate for food regardless of their body weight. If dieting was that easy IRL, obesity wouldn't be such a hot topic.

We could still leave in the message box indicators (despite having something in your stomach, you feel like you haven't eaten in days) etc, but I think even those are unnecessary, especially given that we have bathroom scales to weigh ourselves and track our weight with. Body weight is its own indicator and the current hunger system is too omniscient and specific. IRL I have no idea if I'm operating at a calorie deficit or surplus, I just know I want to eat twice a day and snack in between or I'll feel crummy.

# Describe alternatives you've considered

Implementing a comprehensive blood sugar system, doing nothing.

**Comment by actual-nh** [comment]
> underweight people can fast without feeling like they're going to die

Definitely true (by the BMI definition of "underweight"). Perhaps, once some fixes are done on the weariness "intake" stat, hunger/low blood sugar messages can - if your stomach doesn't have anything in it - show up when that's less than half of the weariness "tracker" stat? (In other words, if you're getting weary partially due to lack of calories absorbed recently.)

**Comment by souricelle** [comment]
That sounds great, but we may be outsmarting ourselves by not just reverting hunger in the meantime to be about how our tummies feel. I guess it depends on how long #48409 will take.

**Comment by actual-nh** [comment]
> That sounds great, but we may be outsmarting ourselves by not just reverting hunger in the meantime to be about how our tummies feel. I guess it depends on how long #48409 will take.

Point. Most of it will definitely be after 0.F; the question is whether a temporary change of hunger would be acceptable for 0.F, or too much of a change at the last minute. @anothersimulacrum - any thoughts?

**Comment by morthein** [comment]
You could probably add an additional fork in hunger (<-- dad jokes!) to make it so even if your calories don't dictate that you are hungry, your weight can override it. Lots of overweight people eat more than enough calories but still feel hungry, making obesity (likewise the opposite, anorexia) very dangerous to those that don't count calories (either not enough or too much).

**Comment by kevingranade** [comment]
The existing system is based on how hunger works as we understand it, any suggestions for improving it need to be based on making it better reflect reality.
