### ISSUE TITLE
The Zombie kicks you

### ISSUE THREAD

**Issue by Mare-expectantem** [CleverRaven/Cataclysm-DDA#48496]
# Describe the bug

The message "the zombie kicks your (Limb) for (XX) damage..." is currently being displayed by non zombie enemies

# Steps To Reproduce

1. Make a player fight against an enemy that can kick. (In my case it was a Super Soldier Ant)
2. Fight
3. Look for the "The Zombie kicks you..." messsage in the sidebar.

# Expected behavior

It should read "The [Enemy] kicks you... 

# Screenshots

**If applicable**, add screenshots to help explain your problem.

![Untitled](https://user-images.githubusercontent.com/82387450/114400794-9d3d9c80-9ba2-11eb-8739-db6287c78948.PNG)

# Versions and configuration
Please complete the following information; you can now go to:
    - "Main menu (ESC) > Debug Menu > Info > Generate game report" to generate this report.
    - Please update your OS version with a more precise version.

- OS: Windows 10 Home
    - OS Version: 10.0 2009          || 20H2
- Game Version: 0.E-10377-g3860b0e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Graphical Overmap [Graphical_Overmap],
    Arcana and Magic Items [Arcana]

# Additional context

A redditor commented that the lines 5199 to 5210 of monattack.cpp were responsible for this
.

**Comment by Mare-expectantem** [comment]
I want to add, that a bunch of stuff is being cut off, I don't know wether this is by design, but I'll copy the stuff I can't see to here
![Untitled](https://user-images.githubusercontent.com/82387450/114400794-9d3d9c80-9ba2-11eb-8739-db6287c78948.PNG)

# Versions and configuration

<!-- Please complete the following information; you can now go to:
    - "Main menu (ESC) > Debug Menu > Info > Generate game report" to generate this report.
    - Please update your OS version with a more precise version.

- OS: Windows 10 Home
    - OS Version: 10.0 2009          || 20H2
- Game Version: 0.E-10377-g3860b0e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Graphical Overmap [Graphical_Overmap],
    Arcana and Magic Items [Arcana]

# Additional context

A redditor commented that the lines 5199 to 5210 of monattack.cpp were responsible for this.

**Comment by Mare-expectantem** [comment]
<!-- Please complete the following information; you can now go to:
    - "Main menu (ESC) > Debug Menu > Info > Generate game report" to generate this report.
    - Please update your OS version with a more precise version.

- OS: Windows 10 Home
    - OS Version: 10.0 2009          || 20H2
- Game Version: 0.E-10377-g3860b0e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Graphical Overmap [Graphical_Overmap],
    Arcana and Magic Items [Arcana]

# Additional context

A redditor commented that the lines 5199 to 5210 of monattack.cpp were responsible for this.

**Comment by actual-nh** [comment]
Cut off, or line-wrapping?

**Comment by Mare-expectantem** [comment]
Where's the diffrence?

**Comment by actual-nh** [comment]
> Where's the difference? The Stuff just ends and I can't seem to scroll

Are you meaning the text messages, or some part of the graphics (I don't use tiles)?

**Comment by Mare-expectantem** [comment]
I was referring to the post I made.

**Comment by actual-nh** [comment]
> I was referring to the post I made, It acts as if nothing were below it, but I wrote stuff into the "Version and Configuration" and "Additional Context" sections

Remove the `<!--` comment starters.

**Comment by Mare-expectantem** [comment]
Thanks, that worked.

**Comment by JumiDeluxe** [comment]
I can confirm. It is caused by hardcoded "The zombie kicks your [...]" in the `mattack::bio_op_takedown`.

![zombie-kick-bug-1](https://user-images.githubusercontent.com/47438768/127265320-f9c8be89-d22d-47e9-9e59-257dfb6ee29d.png)

I fixed it by replacing hardcoded "zombie" with monster name value. I can make a PR with the change.
