### ISSUE TITLE
Error log when tamed pets attack eachother across z levels

### ISSUE THREAD

**Issue by LordPancitoFresco** [CleverRaven/Cataclysm-DDA#48508]
# Describe the bug

This happened to me when riding a dino from dinomod but it might apply to other riddeable pets. 

Dinos from dinomod attack eachother when tamed even if they are of the same type and were friendly before taming. I tamed 2 different dinos from different types and tied them on the basement of my starting shelter. When i tried to get them out dino1 would not follow me, i left dino1 standing on the stairs without being tied when i gave up on getting him to follow me out. I mounted dino2 that did follow me up outside of the basement and when i tried to move forward and in the process move over the same tile that that dino1 in the basement was standing 1 z level down. I got a an error log saying that dino1 below had tried to attack dino2 the one i was riding. I dont know what is wrong to make the log pop but it does every time that i ride over the stairs if the dino from below is there on same tile but below. 

# Steps To Reproduce

1- Have 2 tamed dinos, you need to be able to ride one. They will attack eachother. 
2 - Make one dino to follow you down the stairs into a basement(or spawn it there) and leave it on the stairs untied. 
3 - Go back up and mount the other dino, then walk on the stairs that are over where you left the other dino below, they will attack eachother and the error log will pop. 
4 - If the log doesn't pop then maybe the dino below moved off the stairs, dismount and go down to see where he moved to. Push/change place with it until it is back on the stairs and repeat step 3.

# Versions and configuration

- OS: Android
    - OS Version: Manufacturer: HUAWEI; Model: MRD-LX3; Release: 9; Incremental: 9.1.0.308C771; 
- Game Version: fa0b7d6 [32-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    DinoMod [DinoMod],
    Disable NPC Needs [no_npc_food]
]

# Additional context 

Before reporting this i created a test world with only dinomod to check if it would be reproduceable, it was pretty easy and i assume that the biggest bug here is that dinos that are tamed by you attack eachother.

Sadly i cant/don't know how to provide a save with it ready to reproduce because i am on mobile and the only options i see are for adding screenshots, though i doubt that it would be helpful to get a screenshot from the error log.
Idk maybe im just dumb

**Comment by actual-nh** [comment]
What species of dinos? Multiple different ones?

> Idk maybe im just dumb

I don't think so; cell phones are limited. I've added OS: Android above, even though I don't think it's to do with the OS, to see if someone can help with that part.

**Comment by LordPancitoFresco** [comment]
![Screenshot_20210413_055924_com cleverraven cataclysmdda experimental](https://user-images.githubusercontent.com/64502015/114561559-088b7b00-9c44-11eb-9b57-66120716891f.jpg)

**Comment by actual-nh** [comment]
Edmontia and Torosaurus indeed shouldn't be attacking each other; they're in the same faction (herbivore_dino), and it isn't one (like "mutant") that attacks each other. I suspect the code for hostility may be checking, seeing friendly, and assuming it should attack anything not in the player faction.

Regarding z-levels - you don't have the experimental 3D field of view option turned on, correct?

**Comment by LordPancitoFresco** [comment]
I dont have 3D field on no. Also this happens with any dino you tame, i have tamed 3 ankylosaurs i found on my save before the current one. I found them together and as soon as i tamed the second one they started attacking eachother.

**Comment by actual-nh** [comment]
Were they attacking the untamed one also, and was it attacking them?

**Comment by LordPancitoFresco** [comment]
They attacked only eachother, they weren't hostile to neutral dinos but as soon as i tamed another dino they start fighting.

**Comment by LyleSY** [comment]
CV reached out to me in other channels suggesting that the ATTACKMON flag might be causing this. Reasonable guess? I see 31 hits when I search for that in dinosaur.json

**Comment by actual-nh** [comment]
> CV reached out to me in other channels suggesting that the ATTACKMON flag might be causing this. Reasonable guess? I see 31 hits when I search for that in dinosaur.json

I think so - they're trying to move someplace, there's another monster in the way, and under those circumstances ATTACKMON causes them to attack the monster in the way.

**Comment by LordPancitoFresco** [comment]
They may attack eachother even if they are just side by side on a field, it's so blatant that i just assumed that someone else had already made an issue about it and if i made this one was just because of the error log

Here is a screenshot of the save i played before my current one where the dinos i tamed and named started hitting eachother right after i tamed them
![Screenshot_20210401_220540_com cleverraven cataclysmdda experimental](https://user-images.githubusercontent.com/64502015/114979085-a2c80a80-9e60-11eb-994a-405d73e63576.jpg)

**Comment by LyleSY** [comment]
I think #48077 fixed this by removing ATTACKMON. I can't replicate it in testing anymore 
<img width="1161" alt="Screen Shot 2021-07-08 at 6 30 57 PM" src="https://user-images.githubusercontent.com/26608431/124998757-f474d100-e01a-11eb-9345-4ed814809097.png">
