### ISSUE TITLE
Zombies always prioritize attacking player in melee range

### ISSUE THREAD

**Issue by Saicchi** [CleverRaven/Cataclysm-DDA#48500]
# Describe the bug
Zombies always attack the player, no matter which targets it attacked first, or where the player is, prioritizing the player over even NPCs. 

# Steps To Reproduce

1. Spawn any zombie monster.
2. Summon / spawn friendly monsters to fight the zombie.
3. Circle around the zombie, checking the message log and noticing how the zombie always target you if you are in melee range.

# Expected behavior

Zombies attack first available target, not just you.

# Screenshots

Zombie attacks me no matter the position
![132258](https://user-images.githubusercontent.com/47158232/114428658-d837d400-9b92-11eb-94de-9cd16a707567.png)
Zombie attacks me no matter the position
![132316](https://user-images.githubusercontent.com/47158232/114428660-d837d400-9b92-11eb-9ea3-4ec73204de24.png)
Always attacks the same target
![132355](https://user-images.githubusercontent.com/47158232/114428666-d9690100-9b92-11eb-921b-8dd24cdfc48d.png)
Zombie attacks me no matter the position
![132413](https://user-images.githubusercontent.com/47158232/114428667-da019780-9b92-11eb-9cfe-ade2a22650d6.png)
Always attacks the same target.
![132427](https://user-images.githubusercontent.com/47158232/114428670-da019780-9b92-11eb-9129-0802c2f76425.png)

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.E-10379-g0f86226edf [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]
]

# Additional context

Does not seem to happen with other non-zombie monsters.
The weird monster I used for testing is called `debug monster`.

**Comment by morthein** [comment]
This is a problem, I agree. It's been around for a long, long time too.  If your NPC friend is engaging with a zombie and you move in, the zombie will target you and attack, no matter what.  I feel like that should happen sometimes, but not every time. 
What to do then?

A threat system - maybe the best choice, but the most work and bugs.  And likely not before the next stable patch is released.

A simple engage lock unless the npc moves out of melee distance (or moves further than you, which would then make them lock on you?) - simple, easy, maybe?

Either way, I agree it feels wonky at best in it's current state, only because it happens constantly and is kind of annoying.

**Comment by SenpaiSlime** [comment]
Can also confirm from experience, zombies are very eager to target you over anyone else if in melee range

**Comment by Xindage** [comment]
That's one of the reasons for me to not help the npcs to fight in meele range, i aways use some ranged weapon to attack from at least 1 tile distance.

The logic behind the zombies should be like this:
First target to be seen gain priority, if this target move a calculation should start, if both player and the first target is at same distance still priority the first target, else start targeting the player or any other enemy of is closer.
During meele combat with multiple enemyes the zombie must run gain a status effect to help him choose who he should attack, the first target must run aways a higher chance. lets start an example.

target A (player) target B (migo) target C (Friendly NPC) (of course a zombie cannot survive aa such abuse but let suppose that's a tank variant)
Zombie engaged at target A (100%) chance of attacking it, B comes from behind a little after and start attacking (5% of chance of being targeted by the zombie) [A has 95% B has 5%] each turn doing a attack on zombie increase this by 5% up to max of 10%, next turn it'll be [A has 90% B has 10%] and this keep going until C join me to help kill the zombie:
[A has 85% B has 10% C has 5%] > [A has 80% B has 10% C has 10%] no matter how much enemys comes to decrease the chance the main will be aways in priority: Attacks from all sides (8 on total) [Main has 20% all others 10%]

Sounds cool on paper but i dont think it's viable on game (there's already much calculations going on, imagine using this on labs, rip framerate) there should be an easy solution... (simple targeting goes true when much enemys are on fight?)

**Comment by SenpaiSlime** [comment]
> 
> 
> That's one of the reasons for me to not help the npcs to fight in meele range, i aways use some ranged weapon to attack from at least 1 tile distance.
> 
> The logic behind the zombies should be like this:
> First target to be seen gain priority, if this target move a calculation should start, if both player and the first target is at same distance still priority the first target, else start targeting the player or any other enemy that is closer.
> During meele combat with multiple enemyes the zombie must run a status effect to help him choose who he should attack, the first target must run aways a higher chance. lets start an example.
> 
> target A (player) target B (migo) target C (Friendly NPC) (of course a zombie cannot survive aa such abuse but let suppose that's a tank variant)
> Zombie engaged at target A (100%) chance of attacking it, B comes from behind a little after and start attacking (5% of chance of being targeted by the zombie) [A has 95% B has 5%] each turn doing a attack on zombie increase this by 5% up to max of 10%, next turn it'll be [A has 90% B has 10%] and this keep going until C join me to help kill the zombie:
> [A has 85% B has 10% C has 5%] > [A has 80% B has 10% C has 10%] no matter how much enemys comes to decrease the chance the main will be aways in priority: Attacks from all sides (8 on total) [Main has 20% all others 10%]
> 
> Sounds cool on paper but i dont think it's viable on game (there's already much calculations going on, imagine using this on labs, rip framerate) there should be an easy solution... (simple targeting goes true when multiple creatures are infighting?)

I mean personally id think zombies, or any enemy without the prioritizes targets tag, would just attack the first thing they can reach, and intelligent enemies would choose targets with the highest damage potential, making it a variable/status thing would probably have a zombie changing its mind occasionally, which dosent match their grabbing behaviour very well, maybe whenever the target they were fighting leaves melee range, they run the check again to see if someone is closer and then target that one instead?
