### ISSUE TITLE
Density of gas turbine items is insanely high

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#48512]
# Describe the bug

Iron - 7.87 g/cm3
Densest element on periodic table, osmium - 22.6 g/cm3
1350 hp gas turbine engine - ‭25.111 g/cm3
1900 hp gas turbine engine - 25.111 g/cm3
‭6000 hp gas turbine engine - 33.305 g/cm3

# Steps To Reproduce

1. Calculate density of engines using simple division

# Expected behavior

Larger volume or lower weight for engines.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-10361-gfa0b7d6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    No Fungal Monsters [No_Fungi]
]

# Additional context

**Comment by actual-nh** [comment]
Verified (and yes, I did multiply L by 1000 to get ml, which is the same as cubic centimeters).
