### ISSUE TITLE
Couldnt craft on top of stairs

### ISSUE THREAD

**Issue by Pooshmeu** [CleverRaven/Cataclysm-DDA#48517]
I couldn't simply board up a window, even with all the materials under my foot.

A clear and concise description of what the bug is. -->

I'm pretty sure I couldn't craft because there was a stair under my foot, the crafting page detected the nails because the nails were in my inventory, but It didn't detected the planks because I can't have 4 planks in my inventory, I tried to put the planks all over the place, I had to get out of the house and construct on the outside which almost had me dead, the construction window could only detect the planks when I wasn't on the stairs tile(when I was on the tile that is used to change z-level). 

1-place character on top of a z-level changing tile, (maybe only house stairs, and the stairs led to a basement)
2-windows was exactly on the 1N tile, window was already cleaned, and ready to be crafted.
3- crafting window can only detect materials in your inventory.

Expected behavior

Planks were all over the place, in my vision and I still couln't detect it.

- "Main menu (ESC) > Debug Menu > Info > Generate game report" to generate this report.
  Sorry, this character is long deleted.

 - OS: w10.
 -game version: experimental version from about 2 weeks ago
 - Graphics version: Tiles version, UDP
 - Ingame language: English
 - Mods loaded: A lot of mods but supposedly, none messed with construction recipes.

Additional context

**Comment by zeropol** [comment]
I reproduced this bug on :

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-10472-g245065a1ef-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

- player on top of stairs going down, ressources on stairs going down : **not working**
- player on downstairs, ressources on upstairs : **not working**
- player on downstairs, ressources on "flat" tile : **not working**

- player on upstairs, ressources on upstairs : ok
- player on upstairs, ressources on downstairs : ok
- player on upstairs, ressources on flat tile : ok

- player on flat tile, ressources on downstairs : ok
- player on flat tile, ressources on upstairs : ok
- player on flat tile, ressources on flat tile : ok

The problem only show up when the player stands on stairs going down.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-6398.
Disposition:
To the north of me (on stairs leading down) is a pool cue.
To the NE of me is a broom.
To the east of me are pointy sticks.
To the south of me is a pit.
I'm standing on a stairs leading down.
![изображение](https://user-images.githubusercontent.com/11132525/155750255-fe1e5e1d-f08f-4765-a507-f3e365b972c9.png)

Pointy sticks are correctly recognized in Construction menu
![изображение](https://user-images.githubusercontent.com/11132525/155750602-0100e8e4-fd21-4eb4-a954-9e46ec240da5.png)

Successfully built spike pit
![изображение](https://user-images.githubusercontent.com/11132525/155750734-90892a60-d545-45c8-a304-5b127dfcde3c.png)

Both broom and pool cue are correctly recognized by Crafting menu
![изображение](https://user-images.githubusercontent.com/11132525/155751025-046828fa-8f1e-41f6-a747-f1ef055779e9.png)

Successfully crafted pointy stick from a pool cue
![изображение](https://user-images.githubusercontent.com/11132525/155751221-c4eb7834-8c31-427a-ade5-8212af20087e.png)
