### ISSUE TITLE
Intricate cufflinks missing fancy tag

### ISSUE THREAD

**Issue by Tommy-os** [CleverRaven/Cataclysm-DDA#48510]
# Describe the bug

Intricate cufflinks are missing the fancy tag.

Their description:
`An expensive pair of silver cufflinks, stylized with detailed overlays of gold gears and fractal patterns.  You can wear it if you like, but it won't provide any effects.
"price": 7000,`

Compared to the less expensive garnet and gold cufflinks which do have a fancy tag:
`A pair of cufflinks with inset garnets.
"price": 3500,`

# Steps To Reproduce

1. Compare different cufflinks

# Expected behavior

Intricate cufflinks made out of silver and gold to have a fancy tag.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-10361-gfa0b7d6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    No Fungal Monsters [No_Fungi]
]

# Additional context

**Comment by leemuar** [comment]
Well, turns out a lot of cufflinks are not actually fancy (diamond_gold_cufflinks is not but garnet_gold_cufflinks is fance ). 
Should we make all cufflinks with gems fancy or just change only intricate one?

**Comment by Zireael07** [comment]
IMHO all cufflinks with gems should be fancy

**Comment by leemuar** [comment]
Here you go, @Tommy-os 
Survive with style!
