### ISSUE TITLE
Gloves are messing up punch speed

### ISSUE THREAD

**Issue by souricelle** [CleverRaven/Cataclysm-DDA#48526]
# Describe the bug

Many items that cover your hands have an attack speed value. If you attack while wearing one of these items, they're potentially slowing your attacks down very badly. An easy example of this is the Field Combat Exoskeleton, which has an attack speed of 700. So picking up an empty suit of power armor and walloping someone with it is costing the same amount of moves as punching someone while wearing it, whether it's powered or not.

Wielded weapons are unaffected by this bug.

# Steps To Reproduce

1. Equip and power a suit of power armor
2. Punch something
3. Take 7+ seconds to do so despite being able to stab with a knife at the normal speed

# Expected behavior

Gloves should not be affecting attack speed whatsoever, except for their hand encumbrance.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-10114-gd55d4a1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by Salty-Panda** [comment]
Can confirm, happened to me with RM13 combat armor and Taekwondo

**Comment by Salty-Panda** [comment]
Caused by #41209
