### ISSUE TITLE
western holster has too little storage volume 

### ISSUE THREAD

**Issue by Aeiouuu01234** [CleverRaven/Cataclysm-DDA#48532]
# Describe the bug

in comparison with a normal holster, the western holster has less than half of storage volume and cannot be used to holster most of the handguns in the game      

# Steps To Reproduce

check teh stats

# Expected behavior

mabey update the stats based on the standard holster

# Screenshots

![west holster](https://user-images.githubusercontent.com/52901609/114811662-21934980-9d74-11eb-92e2-5123f5dd5861.png)

Do not take a screenshot of the crashing window. Please provide the crash logs in the "Additional context" -->

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-10383-gad91f6a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

**Comment by Antrocon** [comment]
can confirm. 400ml max volume doesn't make sense for western holster
in-game volume & lenght for s&w model 10: 402ml / 252mm.
in-game volume & lenght for s&w 619: 608ml / 278mm
in-game volume & lenght for colt SAA: 324ml / 208mm

RL lenght for s&w 10 (4" barrel): 237mm 
RL lenght for s&w 619 (4" barrel): 240mm 
RL length for colt SAA (4" 3/4 barrel; shortest): 260mm

from western holster description i can assume it represents cowboy-style holster one might see in western movies and expect revolvers like colt SAA to fit in perfectly. 
from RL dimension values i can assume colt SAA, s&w 10, s&w 619 are roughly same size, so we should expect those to fit into same "western holster", along with majority of regular-sized revolvers we have in game.
the in-game dimension values for those revolvers do look off, but i'm not sure if it worth to audit&correct dimensions of all revolvers and won't change OP issue: colt SAA in-game (supposed to fit into WH) is _way less_ volume than in RL or other revolvers have _way too much_ volume than in RL.
given that, it seems bumping up western holster max volume to something more reasonable would be appropriate.


refs:
https://en.wikipedia.org/wiki/Smith_%26_Wesson_Model_619_%26_620
https://weaponsystems.net/system/626-Smith+%26+Wesson+Model+10+Military+%26+Police
https://en.wikipedia.org/wiki/Colt_Single_Action_Army
https://www.kirkpatrickleather.com/product/idaho-john-rig-model-idj-2/
