### ISSUE TITLE
Chitin armor set tooling consistency

### ISSUE THREAD

**Issue by Caelum-Updates** [CleverRaven/Cataclysm-DDA#48544]
# Is your feature request related to a problem? Please describe.
Chitin armor does not have consistent tooling requirements.

# Describe the solution you'd like
Adjust/revise tooling requirements for chitin items for consistency

# Additional context
![image](https://user-images.githubusercontent.com/78391880/114988415-e48c9b80-9ec8-11eb-9941-e74406b46ab0.png)
![image](https://user-images.githubusercontent.com/78391880/114988472-f3734e00-9ec8-11eb-915b-ba2bc5f94a80.png)
![image](https://user-images.githubusercontent.com/78391880/114988518-fff7a680-9ec8-11eb-960d-7b453d2af905.png)
![image](https://user-images.githubusercontent.com/78391880/114988558-09810e80-9ec9-11eb-9043-be6c50d927cd.png)
![image](https://user-images.githubusercontent.com/78391880/114988674-2b7a9100-9ec9-11eb-9d65-f719ef58791f.png)

**Comment by hexagonrecursion** [comment]
Can reproduce
- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 17b9ea1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]
