### ISSUE TITLE
Camp followers fabrication level increases the same amount, regardless the amount of stuff crafted.

### ISSUE THREAD

**Issue by nathanbigbob** [CleverRaven/Cataclysm-DDA#48542]
# Describe the bug
I'm trying to level a camp follower with 0 fabrication. I told him to make 1 pointy sticks and his fabrication leveled by about        1-2%. Then I told him to make 20 pointy sticks, and his fab leveled by 1-2%. 
I don't think is intended

# Steps To Reproduce

1. Make a camp and assign a low fab follower
2. Order them to make a large amount of pointy sticks, and a low amount of pointy sticks.
3. See how much they level with each order

# Expected behavior

He should level more according to amount crafted.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-10389-g4a67b7c
 - Graphics version: NeoDays
 - Mods loaded: StatsThroughSkills, SpeedyDex

**Comment by actual-nh** [comment]
You say "20" twice above. I'm guessing one or the other numbers is supposed to be different?

**Comment by nathanbigbob** [comment]
Oh boy, that is stupid. Yes, I meant 1 stick for the first sentence.

**Comment by hexagonrecursion** [comment]
The XP **does** depend on the amount you craft:
1 pointy stick: survival +7%
300 pointy sticks: fabrication +25%, survival +8%, mechanics +3%

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 7e2826a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]
