### ISSUE TITLE
Cutting up a large LCD screen yields too many resources

### ISSUE THREAD

**Issue by Bulletfang** [CleverRaven/Cataclysm-DDA#48568]
# Describe the bug
Cutting up a large LCD screen yields roughly 260 plastic chunks.

# Steps To Reproduce
1. Make a player with a cutting tool and a large LCD screen.
2. Cut the screen apart via the butchering menu.
3. See that it yields an absurd amount of plastic chunks.

# Expected behavior
Balanced amount of resources is harvested from the item.

# Screenshots
![Capture1](https://user-images.githubusercontent.com/45204409/115134781-815b5000-a013-11eb-97d8-35954b73bf5f.JPG)

![Capture2](https://user-images.githubusercontent.com/45204409/115134784-86b89a80-a013-11eb-85b6-d6c3cadce49e.JPG)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-10395-g4525b4f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context

No additional context,

**Comment by Zireael07** [comment]
This and #55704 are two manifestations of a general problem with the way yield for cutting is implemented
