### ISSUE TITLE
Dropping items while smoking results in self-ignition

### ISSUE THREAD

**Issue by Salty-Panda** [CleverRaven/Cataclysm-DDA#48562]
# Describe the bug

I was smoking, decided to drop my items, most clothes in order to swap to a different set of armor.
I guess that during procedure my character silently also dropped lit joint inside one of the dropped items, which set dropped items and me on fire

# Steps To Reproduce

1. Lit cigar
2. Start dropping worn items
3. Burn baby, burn

# Expected behavior

1. Lit cigar
2. Start dropping worn items
3. Warning or extinguish lit items while dropping their containers

# Screenshots

![image](https://user-images.githubusercontent.com/26396019/115122768-f7cb6400-9fb9-11eb-9a42-33ccbc5c776f.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-10383-gad91f6a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Mythical Martial Arts [MMA],
    C.R.I.T Expansion Mod [crt_expansion],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Bionic Professions [package_bionic_professions],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP]
]

**Comment by OliveChukar** [comment]
Tested on 0.E-10395-g4525b4f [64-bit] with Dark Days Ahead [dda] only no mods. Killed several zombies picked up a lighter cigarettes and pants from one. Started smoking a cigarette then checked my inventory and it was shown as being in my backpack.  I inserted the lit cigarette into the pants waited a few seconds then dropped them and they instantly caught fire when dropped. I also tried the putting the a lit cigarette in pants but not dropping them and there was no fire.
