### ISSUE TITLE
SegFault on savegame load of new game.

### ISSUE THREAD

**Issue by danielkwinsor** [CleverRaven/Cataclysm-DDA#48563]
# Describe the bug

SegFault on game load.  Reproducible.

# Steps To Reproduce

Start new game.
Save and reload (repeat if needed, take no other actions)

# Expected behavior

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-10395-g4525b4f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Alternative Map Key [alt_map_key]
]

# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6329926/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6329927/debug.log)

[Barahona - 0CrashesForReporting.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6330472/Barahona.-.0CrashesForReporting.zip)

**Comment by BrettDong** [comment]
Tried but unable to reproduce the crash on self-compiled 24c0489c764b38f5c6430e514e755b9d5a21c521 on macOS

**Comment by dustan1** [comment]
Thought this was like a different bug I had with saves/load, but I also couldn't reproduce this crash with 0.E-10395-g4525b4f on windows (downloaded with the launcher). I don't have the "data/sound/damalsksoundpack-0.2/music/Dreaming with Great Old One (Arkham Radio Podcast).mp3" file in my installation though.
