### ISSUE TITLE
Crash when inserting items into container

### ISSUE THREAD

**Issue by Salty-Panda** [CleverRaven/Cataclysm-DDA#48573]
# Describe the bug

When inserting items from the ground into a wielded container, if you attempt to insert an item loaded with its ammo, ammo inside the item, and the ammo as separate stack game crashes.

# Steps To Reproduce

Replicated a few times, this is the smallest crashing sample
Didn't tried with other configurations (not wielded item, not from the ground, magazine and ammo)

Wield cardboard box
Insert
Select from the ground tailor kit loaded with thread, thread inside it and a separate stack of the thread

# Expected behavior

No crash

# Screenshots

![image](https://user-images.githubusercontent.com/26396019/115149302-b8f1e880-a063-11eb-9b51-89269e12c40b.png)
Note weird indent for the lower stack of the thread (placed under other thread and not tailor kit)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-10383-gad91f6a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Mythical Martial Arts [MMA],
    C.R.I.T Expansion Mod [crt_expansion],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Bionic Professions [package_bionic_professions],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP]
]

**Comment by RoyBerube** [comment]
I can make the crash happen by inserting the tailor's kit and selecting its ammo thread as well. Extra thread is unnecessary, and the container receiving the items does not have to be wielded.

It is a nullptr crash, caused by trying to move the ammo thread twice.
