### ISSUE TITLE
Switching martial arts allows for stacking multiple bonuses

### ISSUE THREAD

**Issue by Salty-Panda** [CleverRaven/Cataclysm-DDA#48577]
# Describe the bug

All martial arts effects end at the end of a turn
Martial art penalties are only applied if the martial art is active
By switching martial art at the beginning of the turn you can apply bonuses from more than one martial art

# Steps To Reproduce

Have Current speed >= 2 * Base Move Cost
Trigger new turn (run till the clock tick to a new second)
Change style
You have two bonuses

If you change from Ninjutsu to another one, you keep +50% dmg from Sneak Attack but you won't get a penalty Lost Surprise.
If you change during combat you can manipulate various block/attack/hit bonuses from Muay Thai etc.

# Expected behavior

Effects gained from MA disappear when changing to another MA.

# Screenshots

![image](https://user-images.githubusercontent.com/26396019/115160142-f6bc3480-a096-11eb-8b45-7e784a29b038.png)
Here we have +2 acuracy, + 50% dmg, +33% bash dmg till the end of the turn, but we still can trigger attack benefitting from those, it allows for very strong hit & run

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-10383-gad91f6a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Mythical Martial Arts [MMA],
    C.R.I.T Expansion Mod [crt_expansion],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Bionic Professions [package_bionic_professions],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP]
]

**Comment by hexagonrecursion** [comment]
Confirmed:
1. Mutate insect wings, quick and road runner; wear moccasins (speed 110, base move cost 53)
2. Set martial art to ninjutsu
3. Skip turns until a zombie is right next to you
4. Set martial art to no style
5. Attack
6. Open the @ menu and look at the buffs. You have "sneak attack" and you don't have "lost surprise"

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: f50b6be [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]
