### ISSUE TITLE
[Magiclysm] Flesh Pouch spawned wielded, unable to drop it

### ISSUE THREAD

**Issue by Salty-Panda** [CleverRaven/Cataclysm-DDA#48574]
# Describe the bug

Wanted to pick up a plank, casted Flesh Pouch a few times, got success twice.
Unable to drop it, but I think I dropped the one that spawned as clothing.

# Steps To Reproduce

Cast Flesh Pouch 
It will spawn as a wielded item
You don't even see it in the drop menu, when trying to wield another item, unable to drop it.

# Expected behavior

Can be dropped

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-10383-gad91f6a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Mythical Martial Arts [MMA],
    C.R.I.T Expansion Mod [crt_expansion],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Bionic Professions [package_bionic_professions],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP]
]

**Comment by actual-nh** [comment]
Being unable to drop it is quite reasonable; unable to wield something else would be a bug, AFAIK.

**Comment by Light-Wave** [comment]
Flesh pouch has the "NO_UNWIELD" tag which is supposed to prevent you from getting rid of it.
I think the idea is that the pouch is part of your body.
If you managed to drop it, then that would probably be a bug.
When I was messing around with it a while ago, I found I could move it between being equipped as armor, and being wielded in my hands.

**Comment by hexagonrecursion** [comment]
The item description is:
https://github.com/CleverRaven/Cataclysm-DDA/blob/d008f2e224c1d228d698dad562e51259c2514bea/data/mods/Magiclysm/items/ethereal_items.json#L264
With #51019 fixed there is no bug here. This should be closed.
