### ISSUE TITLE
Add "say/speak a sentence" command to [Shift+C]hat menu

### ISSUE THREAD

**Issue by jtgibson01** [CleverRaven/Cataclysm-DDA#48579]
# Is your feature request related to a problem? Please describe.

Currently, the only way for the player to speak is by talking directly to an NPC or by yelling a sentence out loud, using [Shift+C].  There is no way to talk to yourself, mutter things, or do other roleplaying in a normal voice.

# Describe the solution you'd like

I would like an additional menu option added to Shift+C giving the ability for the player to speak in a normal voice, to say an arbitrary user-specified sentence out loud.

This has three benefits:

1. It's fun for roleplaying, especially a Mad Max style of character who no longer has any friends and must content himself or herself with her own company.

2. It actually serves as a poor-man's notebook.  The player can say something, then check the message log to remember what they said.  If you go about describing your day to day activities using the speech command, it can serve as a memory aid when you come back to the character after an absence.

3. For future consideration, speaking in a calm, confident, and level voice would help placate animals.  Currently, you may yell at animals, and this does already have a gameplay effect on their fear and anger.  It makes sense that doing the opposite -- projecting resolution and a lack of fear -- would make aggressive animals hesitant to harm you and make peaceful animals more likely to trust you.

I just recently resurrected the old Roguelike Classes mod with my own special spin, and I'm having a world of fun playing as a fighter who is discovering modern technology, especially all of the "slain metal whales".  I'm sotto-vocing using the 'yell' command, but it seems odd at times to be yelling about a land whale that yet breathes, but its hide is too thick to slay, so I must regrettably leave it to suffer.

I would prefer for the speak command to be implemented without gameplay features rather than delayed for the gameplay feature to be included, thanks to its immediate benefit and simplicity.  The placating feature would be a major feature that would come later, perhaps as a separate issue.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.

**Comment by octalmage** [comment]
I've been looking for this myself. I wonder if there's a mod that does this.
