### ISSUE TITLE
Cryptic error message when missing symbol in type:terrain

### ISSUE THREAD

**Issue by jtgibson01** [CleverRaven/Cataclysm-DDA#48578]
**Version:** 0.E-9355-g203e8c9 #11430, still present in experimental build #11581

**Issue:**
In JSON modding, when creating a patch of a tile (copy-from object with type terrain) that is missing a ``symbol`` member, the game will refuse to load the content, citing the error message "Expected string or array" and pointing directly to the opening brace of the object.

    13:00:39.220 ERROR : src/main_menu.cpp:1146 [bool main_menu::load_character_tab(bool)] Error: Json error: mods/JTMisc/override_fruitharvest.json:28:2: Expected string or array
    {
     ^
      "id":"t_tree_chestnut","type":"terrain","copy-from":"t_tree_chestnut","harvest_by_season":[{"seasons":["autumn"],"entries":[{"drop":"chestnut","base_num":[5,12],"scale_num":[2.5,12]}]}]}
     ,{"id":"t_tree_beech","type":"terrain","copy-from":"t

**Cause:**
The line producing the error message is this:
https://github.com/CleverRaven/Cataclysm-DDA/blob/b991a1bab26d0fb8a6f9068ab4e9c9639ab76e26/src/mapdata.cpp#L392

which appears in the function
https://github.com/CleverRaven/Cataclysm-DDA/blob/b991a1bab26d0fb8a6f9068ab4e9c9639ab76e26/src/mapdata.cpp#L372-L394

and which is in turn called (among other places) when the game attempts to load the symbol via the function
https://github.com/CleverRaven/Cataclysm-DDA/blob/b991a1bab26d0fb8a6f9068ab4e9c9639ab76e26/src/mapdata.cpp#L421-L437
[snip]

**Solution:**
Since the 'key' parameter is already provided on line 392, the error message should be improved to include the member that is expected, such as ``"A string or array for mandatory member %s could not be found; must provide a '%s' member in JSON"``.

The message does disappear when the missing symbol is added to the corresponding object(s).  This also reveals that colours are mandatory, even though they are defined in the object being copied from, which creates yet another content loader failure... and so on.

**Alternative Solution:**
The content loader should be clever enough to recognise that an object that has a copy-from member is copying from an existing object, and should double-check the original object to determine whether it has the missing member instead of parachuting and aborting the loading process.  Especially, the need to redefine redundant data in patched objects creates a point of failure where mods will have to ensure that their duplicated data reflects the original copy -- i.e., whether the copied data is a deliberate override or merely identical-to-master and included due to the lazy loader.

**Best Practices/Notes:**
Missing symbols (and colours) for flora should not cause a strict loader failure at all, but should instead dispatch a warning and fall back to a default based on the first letter of the name parameter and/or a default '#'.  A missing ``color`` should default to light_gray.  A missing ``name`` should default to the ``id``. Much of the difficulty of patching/JSON modding these days is fighting the strict expectation of missing JSON keys when they could easily have lax fallbacks and default values, and assigned correct values later during the polishing phase. =)

**Related issues:**
Examining the function above, it erroneously claims that symbols must be one character long even while it includes special behaviour for loading the value "LINE_XOXO" or "LINE_OXOX".  The error message should probably be updated to reflect that it can accept those values, as well (I had no idea!), e.g., ``"Symbol must be \"LINE_XOXO\", \"LINE_OXOX\", or a single Unicode character"``.

``"Incorrect number of entries"`` is also highly cryptic without referencing what exactly is going on, but I don't understand enough about the intention of that code (array overflow?) to give a better message.

**Comment by GuardianDll** [comment]
Can confirm it, spend almost few hours trying to understand whats wrong with inheritance when Snup send me this
after adding the `symbol` node (and `color`, because they cant be separated) the bug dissapeared

**Comment by jbytheway** [comment]
Could one of you please provide an example of a complete JSON object reproducing the problem?

**Comment by GuardianDll** [comment]
```json

  {
    "type": "terrain",
    "id": "t_elevator_no_roof",
    "roof": "t_null",
    "flags": [ "TRANSPARENT", "FLAT" ],
    "copy-from": "t_elevator"
  },
  ```
  here i have a terrain, that make a copy of `t_elevator` without a roof, which cause the error
  ```DEBUG    : Error: Json error: data/json/mapgen/aircraft carrier/0t_.json:65:3: Expected string or array

    "flags": [ "TRANSPARENT", "FLAT" ],
	"copy-from": "t_elevator"
  }
  ^
   ,
  {
    "copy-from": "t_elevator_control",


 FUNCTION : bool main_menu::load_character_tab(bool)
 FILE     : src/main_menu.cpp
 LINE     : 1069
 VERSION  : 51814ea
```
but if you add `symbol` (and a `color`, cause they bonded), and it would look like this:
```json
  {
    "type": "terrain",
    "id": "t_elevator_no_roof",
    "roof": "t_null",
    "symbol": ".",
    "color": "dark_gray",
    "flags": [ "TRANSPARENT", "FLAT" ],
    "copy-from": "t_elevator"
  },
  ```
  it works totally fine
