### ISSUE TITLE
[DinoMod] juvenile sauropods confusing description

### ISSUE THREAD

**Issue by LyleSY** [CleverRaven/Cataclysm-DDA#48584]
# Describe the bug

DinoMod juvenile sauropods have the same generic desciption as other juvenile dinos, except they are larger than the max cap in the game. Multiple players have reported being surprised at how deadly mobs of them are. Most players now are using Ultica, which gives them generic dino art that doesn't help either.

# Steps To Reproduce

You can just look at the JSON, here is a good example from juvenile Apatosaurus: 

`    "description": "A small four-legged plant-eating dinosaur juvenile with huge shiny eyes, it could be from a number of different species.",
`

# Expected behavior

    "description": "A huge four-legged plant-eating juvenile sauropod with a long neck and tail, it could be from a number of different species.",

# Versions and configuration

 - OS: Mac OS 11
 - Game Version: most recent experimental
 - Graphics version: Tiles 
 - Ingame language: English
 - Mods loaded: DinoMod

# Additional context

I think Torres reported this first in Discord, but a bunch of people have pointed it out

**Comment by LyleSY** [comment]
Thanks to @actual-nh for the poke to properly report this

**Comment by actual-nh** [comment]
The linked PR has been merged (albeit unfortunately into 0.F-dev), which should have closed this issue.
