### ISSUE TITLE
Light Gloves Subtract Warmth

### ISSUE THREAD

**Issue by SibilantScream** [CleverRaven/Cataclysm-DDA#48587]
Wearing light gloves over w\ leather gloves subtracts from warmth.
Light Gloves + Medical Gloves = 10
Leather + Light = 10
Light + Leather + Medical = -4
Light + Leather = -4

Platform     : Windows_x64
Graphics     : Tiles
Build number : #11574
Build version: 0.E-10377-g3860b0e
Major version: 0.E

**Comment by SariusSkelrets** [comment]
What’s the issue? Are they supposed to keep you warm? 

What is the expected behavior?  What do you suggest to solve this issue?

**Comment by Salty-Panda** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/issues/45482#issuecomment-729541747

Is this the case?

**Comment by SibilantScream** [comment]
I only have these gloves on the hands layer so I don't think I'm losing any pocket related bonuses.


> What’s the issue? Are they supposed to keep you warm?
> 
> What is the expected behavior? What do you suggest to solve this issue?

I expect adding light gloves to add not subtract warmth.

correct:
Leather + Light = 10
in the original post to:
Leather + Light = -4

**Comment by hexagonrecursion** [comment]
Could not reproduce
- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: f50b6be [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]
