### ISSUE TITLE
Incorrect text on proficiency failure rate.

### ISSUE THREAD

**Issue by danielkwinsor** [CleverRaven/Cataclysm-DDA#48597]
# Describe the bug

Text says this is 1.0x _more_ likely to fail.  it should say _as_ likely, or similar verbage.

<img width="565" alt="Screenshot 2021-04-20 203555" src="https://user-images.githubusercontent.com/2822992/115493223-3199a600-a218-11eb-8aa5-ff9f05bd33b7.png">

# Steps To Reproduce

View item without prof

# Expected behavior

# Screenshots

# Versions and configuration

# Additional context

**Comment by hexagonrecursion** [comment]
Confirmed

![1x](https://user-images.githubusercontent.com/52621858/129782907-33b52c96-0fcd-4f56-aa16-04cf4d7fcf43.png)


- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 31ef3ba [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by actual-nh** [comment]
I know @anothersimulacrum had worked on this before, with a wider vision of revamping.

**Comment by anothersimulacrum** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/46082 - which needs revivification.
