### ISSUE TITLE
Tell the user when they load a bad (crashing) save

### ISSUE THREAD

**Issue by ethankaminski** [CleverRaven/Cataclysm-DDA#486]
Sometimes, when save compatibility is broken, the game will simply segfault. It would be better, IMO, to realize that the save is completely broken, and alert the user to this fact. Possibly with the option to delete the save folder, as well.

**Comment by tivec** [comment]
Ran into this bug while searching for "segfault" in the issues list. It's quite old, and as far as I know, the builds are backwards compatible now?
