### ISSUE TITLE
Bug: Campgrounds with cars don't spawn with road connections.

### ISSUE THREAD

**Issue by stubkan** [CleverRaven/Cataclysm-DDA#48602]
# Describe the bug

Campgrounds that have cars dont spawn with road connections.

# Steps To Reproduce

1. Choose wilderness start, campground spawn / Find campground
2. Odds are you will spawn surrounded by trees, miles from any road.
3. Cars that spawn in the campground with a high chance of being drivable cannot be taken out because of tree obstructions and no road path.

# Expected behavior

Since campgrounds spawn with a high percentage of drivable cars, and have facilities on par with state parks, rest stops, etc and a path, they are supposed to be connected to roads. And not surrounded by impassible forest.

This is only for the 2x2 campgrounds which spawn with mostly drivable vehicles and facilities.  The 1x1 campgrounds have no vehicles or facilities, so it makes sense for those to be off grid.

# Screenshots

![campgrounds fubar](https://user-images.githubusercontent.com/34361592/115565960-bf759f80-a2b1-11eb-8052-956582a71565.png)

![image](https://user-images.githubusercontent.com/34361592/115566270-0499d180-a2b2-11eb-8682-36f2a0765e52.png)

Do not take a screenshot of the crashing window. Please provide the crash logs in the "Additional context" -->

# Versions and configuration

0.E
No Mods

# Additional context

I think this is a result of increased city spacing and size.

**Comment by PatrikLundell** [comment]
"Latest" is not a valid version number. It relies on any investigators to correlate the bug report time stamp (taking time zone madness into account) against the release of various versions, plus the assumption that you've actually verified that no new version has appeared between your download and the filing of the report.
You've also neglected to list the rest of the configuration info, in particular the list of mods, which could potentially influence the world generation. Although I don't think the OS used has an impact in this case, leaving out things that "obviously" have no impact can turn out to be incorrect surprisingly often.

**Comment by actual-nh** [comment]
No mods, or default mods?

**Comment by stubkan** [comment]
> No mods, or default mods?

Default. 

Don't worry about this too much, I made a pr to c++ code and fixed this issue.  I think this is a long standing issue, mlangsdorf said nothing connects to a road if a city is not present so I made a patch for that, and it fixed that.
