### ISSUE TITLE
Плавание в воде на месте водителя

### ISSUE THREAD

**Issue by YukioDjo** [CleverRaven/Cataclysm-DDA#48600]
Если автомобиль находится одновременно на земле, воде, глубокой воде - то персонаж перемещаясь по автомобилю наступая на клетку с глубокой водой начинает плыть/тонуть. Тогда если сесть за руль (он тоже должен находиться на клетке с глубокой водой) персонаж едет и плавает/тонет одновременно. Если при этом выехать с воду на сушу - будете дальше плыть/тонуть пока не прекратите находится за рулём.
Это на эксперметальной версии андроида из Гугл магазина. Есть подробнее видео, но сюда не смог прикрепить пишите на почту mrdomaya@gmail.com если нужно видео.

**Comment by XygenSS** [comment]
Google Translate says:

If the car is simultaneously on the ground, water, deep water - then the character moving around the car, stepping on a cell with deep water, starts to swim / sink. Then if you sit behind the wheel (he must also be on a cage with deep water), the character drives and swims / drowns at the same time. If at the same time you leave the water on land, you will continue to swim / sink until you stop being behind the wheel.
This is on the expert version of the android from the Google store. There is a video in more detail, but I could not attach it here, write to mrdomaya@gmail.com if you need a video.

**Comment by Fris0uman** [comment]
Duplicates of https://github.com/CleverRaven/Cataclysm-DDA/issues/46488 , also please follow the template and post in english.
