### ISSUE TITLE
NPC should reload empty magazines in their inventory

### ISSUE THREAD

**Issue by Salty-Panda** [CleverRaven/Cataclysm-DDA#48613]
# Describe the bug

Gave NPC gun, spare magazines, ammo
NPC prioritizes reloading with full mags I have them, but once they are empty, they are simply ignored

# Steps To Reproduce

1. Give NPC gun, spare magazines, ammo
2. Have them shoot things
3. Wait till they use up all filled mags
4. Observe they just reload wielded gun with ammo and do nothing with empty mags

# Expected behavior

If not doing anything, they should reload empty mags in their possession with matching ammo in their inventory

# Screenshots

![image](https://user-images.githubusercontent.com/26396019/115684546-bd661c00-a357-11eb-8890-200d2569f432.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-10383-gad91f6a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Mythical Martial Arts [MMA],
    C.R.I.T Expansion Mod [crt_expansion],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Bionic Professions [package_bionic_professions],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP]
]

**Comment by hexagonrecursion** [comment]
Confirmed: NPCs reload wielded guns it they have nonempty magazines, but they don't reload the magazines if the have the ammo

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 8051d7d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by I-am-Erk** [comment]
So, I'm thinking the way to get NPCs to reload magazines is to let them soft-cheat on the time it takes to reload magazines. Rather than calculating hte number of moves to refill magazines and seeing if that's an optimal choice, we instead could just have them automatically gradually refill magazines in their inventory "in the background". Something like this:


1. every 1 minute, call mag_refill()
2. Mag_refill checks if not in combat. Return if in combat.
3. If not in combat, assemble a list of magazines in inventory for which you have ammunition and a gun, inversely weighted by time it would take to fill them
4. Randomly select a magazine from the list and fill it.

**Comment by I-am-Erk** [comment]
So it looks like we have code for this and I'm not sure why it is not firing:
https://github.com/I-am-Erk/Cataclysm-DDA/blob/e8f77ab4c9ed02ab697a9bd618f3ed45549d7d85/src/npcmove.cpp#L1966C1-L1970C6

this appears to be the code for getting NPCs to identify reloadable magazines in inventory and have them reload them automatically. It could be refined but it doesn't seem to be running at all, which is weird.
