### ISSUE TITLE
Crafting recipes don't show up in custom basecamp expansion

### ISSUE THREAD

**Issue by krulunio** [CleverRaven/Cataclysm-DDA#48616]
# Describe the bug
I'm working on more basecamp locations and basecamp expansions. I tried to add some crafting recipes for one of my custom expansion, but recipes don't show up in expansion's tab.

# Steps To Reproduce
1. Create basecamp (in center of `Mansion_Road_Alt`)
2. Expand basecamp with custom expansion (`mansion_t1` - swimming pool)
3. Crafting recipes don't show up

# Expected behavior
Crafting recipes should be visible.

# Versions and configuration
 - OS: Windows 10
 - Game Version: 0.E-10395-g4525b4f
 - Mods loaded: my basecamp locations and expansions

# Additional context
I saw #34535 and skimmed trough some code, so I tried changing `"building_type"` to `NONE`, `ANY`, `ALL` and `BASE`, nothing happend.
[Here](https://github.com/CleverRaven/Cataclysm-DDA/files/6357129/mo_camps.zip) is my mod.

**Comment by krulunio** [comment]
I found workaround: you need to add:
- `"blueprint_provides": "reseeding"` for `"building_type": "FARM"`
- `"blueprint_provides": "kitchen"` for `"building_type": "COOK"`
- `"blueprint_provides": "blacksmith"` for `"building_type": "SMITH"`
Still, it needs proper fix, by moving stuff from source code to JSON.

**Comment by PatrikLundell** [comment]
Basically all of the code of the base camp file would need a rewrite. It's a mess of comparisons of string literals, concatenations, and parsing, with display strings used as tokens (an example is that the making of tinder can be ordered from both the kitchen expansion and the base [with the current modular base camp], but the string used to identify the job is the same in both cases, causing it not to be able to determine which building the job comes from).

**Comment by RenechCDDA** [comment]
Per krulunio's comment this is an issue with the mod's json, and was at the time of posting as well.
