### ISSUE TITLE
Active grenades thrown at tiles on fire just dissappear without detonating

### ISSUE THREAD

**Issue by Torres84f** [CleverRaven/Cataclysm-DDA#48625]
# Describe the bug

If you throw an active grenade at a tile that's on fire you'll lose the grenade, it won't detonate.

# Steps To Reproduce

1. Throw molotov at tile
2. Throw active grenade at tile
3. It will become a burnt grenade first turn then it'll break into metal scrap like in the pic

# Expected behavior

# Screenshots
![1](https://user-images.githubusercontent.com/15707408/115848660-01baf000-a41c-11eb-936d-2f68be9f7c0a.jpg)
![2](https://user-images.githubusercontent.com/15707408/115848670-04b5e080-a41c-11eb-99fc-0fc7b9e0a460.jpg)

# Versions and configuration

GAME REPORT:
- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-10389-g4a67b7c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries [blazeindustries],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod [crt_expansion],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Magiclysm [magiclysm],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    DinoMod [DinoMod],
    DinoMod - UndeadPeople Tileset [DinoModUDP],
    Alternative Map Key [alt_map_key],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm]

# Additional context

**Comment by Salty-Panda** [comment]
Not sure what grenades are made of (in game), but maybe adding some explosive as material would help

**Comment by Alex-Folts** [comment]
I assume that in most modern hand-grenades inside hexogen, which is stable enough to not trigger from fire or heat. It would melt, boil and burn but wont explode, you need detonator to triger it, similar situation with c4.

**Comment by actual-nh** [comment]
Does this happen with improvised/homemade/etc varieties of grenades/bombs? (I don't know about modern incendiary grenades - anyone know how fire-stable those are?)

**Comment by Hirmuolio** [comment]
Grenades have the main explosive and a detonator explosive.

The main explosive is stable and probably wouldn't blow up in fire.  
The detonator explosive is much more volatile. It will most likely blow up in fire. And when it blows up it will cause the main explosive to also blow up.

I think making all grenades blow up in fires would be good.

**Comment by SenpaiSlime** [comment]
just checked this out, standard military grenades will not detonate, but incendiary grenades and makeshift grenades will. Not sure if its actually intentional given other grenades and rockets still work

**Comment by hexagonrecursion** [comment]
Confirmed: grenades do disappear

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: bea0650 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]
