### ISSUE TITLE
Make followers crouch with us while staying in cars.

### ISSUE THREAD

**Issue by ifffrt** [CleverRaven/Cataclysm-DDA#48626]
# Is your feature request related to a problem? Please describe.
Imagine you and your follower are going along a road when you spot a military blockade with a mean-looking M2HB turret. You crouch, confident that this will be enough to fool the turret, and drive past it. But half way towards the blockade, your follower's head explode!

# Describe the solution you'd like
Dumbass follower NPC should have crouched with you when you did.

# Describe alternatives you've considered
That NPCs should also crouch when you are both _outside_ vehicles as well, maybe when you are both within 10 tiles range. This way both the NPC and you will muffle the sound of your feet.

# Additional context

**Comment by Salty-Panda** [comment]
Wasn't there option to have them act sneaky?

**Comment by actual-nh** [comment]
> Wasn't there option to have them act sneaky?

Triggering that when you crouch would be nice.

**Comment by ifffrt** [comment]
> 
> 
> Wasn't there option to have them act sneaky?

How do you turn that on?

**Comment by Salty-Panda** [comment]
Sorry, mistaken with "Stay quiet"

**Comment by actual-nh** [comment]
> Sorry, mistaken with "Stay quiet"

Are you referring to `allow_complain` or `use_silent`? The latter could be expanded.

**Comment by Salty-Panda** [comment]
Yes, but I have no idea how to make NPC crouch, not sure if they can even change movement mode in the first place.
