### ISSUE TITLE
Keffiyeh only covers the mouth despite description and common sense saying otherwise

### ISSUE THREAD

**Issue by O1OOO1O** [CleverRaven/Cataclysm-DDA#48630]
# Describe the bug
The Keffiyeh shows as only covering the mouth but read the description and look at some on google images...
![keffiyeh](https://user-images.githubusercontent.com/82064797/115943144-db28a380-a473-11eb-8893-09c0a57a7c7f.jpg)

# Steps To Reproduce
Examine a Keffiyeh

# Expected behavior
Keffiyeh should default to covering the head and have an activate action that allows it to be modified to cover the head and the mouth.

-------
Experimental Build 11581

**Comment by ferociousdork** [comment]
Keffiyeh has the `HOOD` flag, which does work to keep your head warm:
https://github.com/CleverRaven/Cataclysm-DDA/blob/30306f9be7f00a60cf54b6319f39d980c8eac92c/src/character.cpp#L11047-L11050

**Comment by actual-nh** [comment]
Is it currently possible to have full coverage on one body part (e.g., mouth) but only partial coverage on other parts (e.g., head)?

**Comment by ferociousdork** [comment]
It looks that way, through the `armor_portion_data` field. For example:
https://github.com/CleverRaven/Cataclysm-DDA/blob/30306f9be7f00a60cf54b6319f39d980c8eac92c/data/json/items/armor/coats.json#L194-L215

**Comment by O1OOO1O** [comment]
While having a hod is better than what  I first thought, I still believe that it should primarily be a head covering item with the mouth component toggleable and the default behavior to not covering the mouth.

**Comment by ferociousdork** [comment]
In that case an option could be to make it fully cover the head and change the `HOOD` flag to `COLLAR` (which works the same way as `HOOD` does, but applies to the mouth).

**Comment by cheekygoblin** [comment]
FYI, the commit to fix this based on the decisions and conversations had here was quashed because someone faefux disagreed with the solution. I don't know what the correct course of action is for this, but this issue surely still exists. 

https://github.com/dissociativity/Cataclysm-DDA/commit/7ed10a735a1d923b5cc96260380bca8f4b7fa381
https://github.com/CleverRaven/Cataclysm-DDA/pull/50144
