### ISSUE TITLE
Jenkins/Build Bot Broken

### ISSUE THREAD

**Issue by brosseaualex** [CleverRaven/Cataclysm-DDA#48642]
# Describe the bug

No builds have been generated for more than a week.

CataclysmDDA Launcher is unable to pull changelogs because the Build system for CDDA seems to be offline

# Steps To Reproduce

No builds available for more than a week.

# Expected behavior

Automated builds being done.

# Screenshots

# Versions and configuration

# Additional context

**Comment by actual-nh** [comment]
Ping: @narc0tiq?

**Comment by DemolitionDerby** [comment]
Issue has already been reported a few times on the Launcher Github page;

https://github.com/remyroy/CDDA-Game-Launcher/issues/551

**Comment by narc0tiq** [comment]
I haven't been able to get in touch with the hosting provider. I'll keep
trying, but it might not be a bad idea to find an alternative, if someone's
willing to work on it.

**Comment by actual-nh** [comment]
> I haven't been able to get in touch with the hosting provider. I'll keep trying, but it might not be a bad idea to find an alternative, if someone's willing to work on it.

I doubt I'll be able to, but for others - what specifications need to be available (and at what price range) from a hosting provider?

**Comment by BrettDong** [comment]
An alternative could be building experimental versions on GitHub Action and directly releases the distribution zip on GitHub. It's free of charge.

**Comment by Inglonias** [comment]
This issue is no longer valid - experimental releases have been using Github actions for some time now.
