### ISSUE TITLE
Can't remove items from an overburdened NPC

### ISSUE THREAD

**Issue by O1OOO1O** [CleverRaven/Cataclysm-DDA#48648]
# Describe the bug
I have an NPC who is overburdened. I wanted to take items away from them in order to remove that condition via the trade interface, but despite only offering to take items away and giving nothing I get the message that the NPC 'can't carry all that'

# Steps To Reproduce
Have a low STR NPC (to make it easier to overburden them) tell them to use enough equipable items that they become overburdened.  Talk with them and open the trade interface and attempt to take items away so as to lighten their load.

# Expected behavior
If the final weight result after the trade is done is less than than the starting weight, the trade should be allowed even if the NPC is overburdened. 

# Screenshots

![cantremoveitemsfromnpc](https://user-images.githubusercontent.com/82064797/116000996-0ddbb480-a5b8-11eb-9003-75e7b5bafb55.jpg)

(Arminda Nicholas STR is 4)

Build 11581

**Comment by O1OOO1O** [comment]
If I remove enough items that the weight goes back to positive values I am able to remove the undesired items with the rest. I then can hand back the items I removed that I originally did not want to remove if they are equipable items valid for the "I want you to use this" interaction.

**Comment by AngularFruit** [comment]
I had the same issue and was able to resolve it the same way, by getting their weight back in the green.

**Comment by RenechCDDA** [comment]
Resolved as of c94dc03
