### ISSUE TITLE
Boat rental generated inbetween a river and a lake

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#48655]
# Describe the bug
![screenshot-rental](https://user-images.githubusercontent.com/31852/116011461-c9cacd00-a614-11eb-9d60-5efa8ef5f284.png)

# Steps To Reproduce

# Expected behavior

# Screenshots

# Versions and configuration
https://github.com/CleverRaven/Cataclysm-DDA/issues/37784 is ANNOYING

# Additional context

**Comment by Night-Pryanik** [comment]
You have to rent a boat to get to the boat rental? Seems legit.

**Comment by l29ah** [comment]
![screenshot-rental](https://user-images.githubusercontent.com/31852/117483804-bd6c3b80-af55-11eb-8947-566dcec17a04.png)

**Comment by sethsimon** [comment]
Confirmed on version 0.F-785-gb47a3c0325-dirty. I had to reveal about a dozen overmaps to find one. Note that there aren't any lakes nearby in this case.

![boat_rental](https://user-images.githubusercontent.com/16765166/126052148-8516c902-3118-4b46-9e59-84f7c6f8aa1a.png)

River generation is wonky in some cases. Some related issues are #46844, #36630, and #38036.

**Comment by LovamKicsiGazsii** [comment]
Boat rentals no longer generate in the middle of rivers thanks to #56123.  Riverside dwellings do, however, but that'll (hopefully) be fixed in #58439.
