### ISSUE TITLE
Deconstructing Furniture should be available for open windows

### ISSUE THREAD

**Issue by moll** [CleverRaven/Cataclysm-DDA#48657]
Hey,

Thanks for maintaining Cataclysm!

It took me a while to realize that the "Deconstruct Furniture" command is only available for closed windows. I think it should be available regardless of the window state, as it would be rather unintuitive and confusing otherwise. That's the case with `t_window_no_curtains_open` at least.

I tracked it down to  [terrain-windows.json](https://github.com/CleverRaven/Cataclysm-DDA/blob/e6ad91695da3fda6584da17688434c2d17b7f5e4/data/json/furniture_and_terrain/terrain-windows.json) and suspect it's because the open-variants of windows lack their respective `deconstruct` properties. I'm not familiar with the codebase to incorporate the change outright for the chance that open-closing works somehow specially, but if it doesn't, I can go ahead and do the change. Or if someone with commit-rights already has an editor open, they'd probably be quicker than me. :)

I first stumbled upon the issue in the latest stable version 0.E, but looking at the master branch's [terrain-windows.json](https://github.com/CleverRaven/Cataclysm-DDA/blob/e6ad91695da3fda6584da17688434c2d17b7f5e4/data/json/furniture_and_terrain/terrain-windows.json) as of right now, it still seems to be the case.

Thanks and cheers

**Comment by RoyBerube** [comment]
The id for this window in terrain-windows.json is "t_window_open"

It looks like there is missing deconstruction info for a number of windows.

**Comment by actual-nh** [comment]
> The id for this window in terrain-windows.json is "t_window_open"
> 
> It looks like there is missing deconstruction info for a number of windows.

Yes. The most efficient way to cure a lot of the missing window info problems seems to be using "copy-from"...

**Comment by leemuar** [comment]
> The most efficient way to cure a lot of the missing window info problems seems to be using "copy-from"...

As I can see [here](https://github.com/CleverRaven/Cataclysm-DDA/blob/b991a1bab26d0fb8a6f9068ab4e9c9639ab76e26/doc/JSON_INHERITANCE.md#support) TERRAIN type objects do not support JSON inheritance. Is the doc outdated or we should add inheritance for terrain type too to resolve this issue using "copy-from"?

**Comment by actual-nh** [comment]
> > The most efficient way to cure a lot of the missing window info problems seems to be using "copy-from"...
> 
> As I can see [here](https://github.com/CleverRaven/Cataclysm-DDA/blob/b991a1bab26d0fb8a6f9068ab4e9c9639ab76e26/doc/JSON_INHERITANCE.md#support) TERRAIN type objects do not support JSON inheritance. Is the doc outdated or we should add inheritance for terrain type too to resolve this issue using "copy-from"?

The documentation needs to be fixed; do a search for copy-from in furniture_and_terrain.

**Comment by actual-nh** [comment]
PR created to deal with documentation issue.

**Comment by RoyBerube** [comment]
Doing the reverse of the construction from construction.json seems like a logical way to go. For example, deconstructing t_window_taped will yield some duct tape and revert to a t_window. 
https://github.com/CleverRaven/Cataclysm-DDA/blob/245065a1ef36d4b27a1719e1a2db424e3c942012/data/json/construction.json#L429-L440

I should be able to get it done over the next few days and will do a PR if it plays ok.

**Comment by actual-nh** [comment]
I would not allow getting all of the duct tape (or other adhesives back), BTW, but otherwise sounds good.

**Comment by RoyBerube** [comment]
> 
> 
> I would not allow getting all of the duct tape (or other adhesives back), BTW, but otherwise sounds good.

That is the plan. For 50 duct tape I'm thinking a random range of 25 to 40.

**Comment by Tairesh** [comment]
Now you can deconstruct alarm windows and even alarm windows with metal bars in 20 minutes with only a hammer and a screwdriver.
