### ISSUE TITLE
[Magiclysm] Make Lizardmen similar in mechanics to Hub01 

### ISSUE THREAD

**Issue by Jan-Blasiak** [CleverRaven/Cataclysm-DDA#48665]
Swamp Lizardmen feel very underdeveloped, they seem to be a tribal society, with shamans, warriors, scouts etc. but the only possible interaction you can have with them is to shoot them on sight, then loot the cave for dragon scales and one or two items.

What I would love instead, would be to have an interaction with them similar to Hub01 where you can trade, and undertake some quests for them which would help them fortify their cave, gather food, build nursery scavenge some human technology to help them prepare and preserve food and generally thrive in the absence of humans, and once enough quests are accomplished they would allow player to enter the lower levels of their caverns and meet the dying Black Dragon who would have some personal quests for player with considerably greater rewards, risks and consequences.

**Comment by Jan-Blasiak** [comment]
I'm on mobile, I don't know how to tag the idea properly.

**Comment by actual-nh** [comment]
You can't, unless you have "triage" permissions. Ping: @KorGgenT?

**Comment by actual-nh** [comment]
I think the Forge of Wonders is probably a bit more intended to have some similarities to Hub01, but more interactions with the various "monster" races than combat would certainly be nice.

**Comment by Jan-Blasiak** [comment]
> I think the Forge of Wonders is probably a bit more intended to have some similarities to Hub01, but more interactions with the various "monster" races than combat would certainly be nice.

Absolutely. There are other mods which "add races" (Blaze/Aftershock I think?) but they are similarly just another group of simple monsters with no other interaction to them than to be something which baits shotgun slugs or tries to jump under the 30 ton murdertruck (sorry mr squid).

**Comment by actual-nh** [comment]
Aftershock definitely does, as does Dark Days Above.

**Comment by actual-nh** [comment]
I think part of this is that they are added as monster types - not as new NPCs.

**Comment by Jan-Blasiak** [comment]
Is there a way for me to help create or expand such story/interaction elements?

I really like my idea and I would love to help making it real, similarly to my FOW idea.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
