### ISSUE TITLE
[Magiclysm]Balance Demon Spiders

### ISSUE THREAD

**Issue by Jan-Blasiak** [CleverRaven/Cataclysm-DDA#48664]
Demon spiders are unquestionably one of the hardest enemies you can find in Magiclysm. They have insanely high armor, ability to start fires, regeneration, and in case of the Queen - ability to lob spells spawning chaff enemies who interrupt attacks.

In addition, Magiclysm Demon Spiders are very common, their lairs can be found easily, practically in every other forest, making Magiclysm a boring spider hunt. They don't even have the loot which would even partially justify the risks the common, or even uncommon survivor has to undertake to get to it.

I propose few steps:
1. Nerf Demon Spider armor. Currently the only reliable way to damage even regular Demon Spiders is magic. Most of the guns are useless against them, and they can't be approached in melee due to their fire magic being so incredibly lethal.

2. Nerf the spider queen. The spider queen seems like something that was added as a joke and never fixed, regular .50 cal ammunition has a high chance of bouncing, queen can practically instantly nullify the damage dealt with regeneration, her spider chaff attack IS a game over due to how aiming/casting works, and she can set player on fire causing instant death spiral by pain, destroying equipment, and interrupting attacks.

3. Add a fire resistance potion made of Demon Spider Chitin. Demon Spiders are fire elementals, and fighting them without SOME way to offset the best type of damage in the game is infuriating.

4. Either buff the loot spawning in the Spider Lair, or nerf the Spider Lair defense. The only reason to go there currently is bragging rights, since usually what you get out of a murderfest that is assault on spider lair is two magic sticks, a sappy scroll and some Chitin if you bother to harvest it for a mediocre set of armor.

**Comment by Jan-Blasiak** [comment]
I'm on mobile, I don't know how to tag the idea properly.

**Comment by actual-nh** [comment]
Ping: @KorGgenT?

**Comment by Salty-Panda** [comment]
I killed the queen thrice.

The first time attempted to do it in medium-range using tourist table and .50 machine gun, I was seriously harmed, had to evacuate.
Later I burnt the forest, drove my vehicle, lured the queen out, and killed her using the vehicle's belt-fed grenade launcher. I took 10-20 shots, I don't recall.
The second and third time I neared the entrance, killed some spiderlings, luring the bigger enemies out. Then I kept a distance of 40-60 tiles and sniped demon spiders and the queen using .50 ammo. It took roughly 50-60 ammo (I used some reloaded ones).
In the first attempt, the loot was destroyed by explosion, but I have to note that with Stats-Through-Kills mod I got a lot of XP from the queen.
The enemies were unable to conduct any attacks and only slowly walked to my position, slow enough to allow me to easily keep the distance.

I believe the current difficulty to be appropriate and encouraging the player to find out alternative engagement methods.
I must agree though that more loot/new thematic loot would be reasonable. If possible placed in an explosion-proof chest.

**Comment by actual-nh** [comment]
Demon chitin does have uses other than armor, actually, but it does seem like too-little reward. And the frequency of Spider Lairs could be cut down a bit.

**Comment by Salty-Panda** [comment]
Once 0.F hits and when I will be done with some of my other PRs I will probably have the urge to add some more magical stuff.
Both Spider Queen and Triffid Queen will probably be used as a source of essences

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
