### ISSUE TITLE
[Magiclysm] Add magic-altered zombies

### ISSUE THREAD

**Issue by Jan-Blasiak** [CleverRaven/Cataclysm-DDA#48667]
As the title says, Magiclysm adds a whole new mechanic to the game: Macic, which isn't showing in the very core part of the game: Zombies.

We have Golems, Dragons, Goblins, Owlbears, Demon Spiers etc. but there are NO MAGIC ZOMBIES WHATSOEVER anywhere in the game. No zombiefied Mages who pepper player with ice bolts and blast outwards a kinetic explosion when player tries to engage them in melee, no zombie Druids who raise skeleton chickens from the trash cans or call in a flock of zombie birds onto the player, no zombie alchemists who, when they see the player: throw buffing potions at the zombies around them, no zombie paladins who shiled-bash player through the concrete wall, no zombie Stormashapers who call long range inaccurate bolts of lightning at the player.

I reeeeeeeeeeeeeeeeeeeeally feel like there is a tiny little bit someone forgot to add to the zombie apocalypse.

(Just please no zombie fireballs, there will be no cities afterwards)

**Comment by SariusSkelrets** [comment]
I don’t think regular zombies have the ability to do something as complex than casting a spell

Feral mages could work, a rare variant of the regular feral with random spells and casting abilities 

As magically altered zombies like one filled to the brim with mana crystals that sometimes unleash an unaimed blast of pure-type lightning and one that with demon chitin, similar to the kevlar zombie

Or zombie owlbears, goblins, trolls, ect

**Comment by Salty-Panda** [comment]
Normal zombies wouldn't be able to cast a spell since it's a rather difficult activity and they can't even operate a gun.

Feral mages could be justifiable, but there is a problem with balance. Magic always targets the torso and guarantees a hit, effectively making it about 5 times as strong when used against NPC/players. Also, almost all magic ignores nearly all conventional armor, further increasing this disproportion.

**Comment by actual-nh** [comment]
> zombie owlbears, goblins, trolls, ect

There are a couple (see Magiclysm/monsters/zombified_monsters.json), but I agree they could use expansions.

> Normal zombies wouldn't be able to cast a spell since it's a rather difficult activity and they can't even operate a gun.

How about the more "instinctive" spells, as you were discussing with #48651? (Or the "Crystallized Mana Nose Replacement" bionic, assuming someone would actually get this?) Another possibility (also for feral humans) is out-of-control spellcasting - see #46057 for some discussion of this.

Long-term, a further evolution of the more-sapient zombie types (e.g., Lab Zombie Scientists - in 0.F-dev with #47996 - Zombie Masters, Zombie Necromancers, etc) could be magical.

**Comment by Salty-Panda** [comment]
As I see it, it issues is to add "spellcasting enemies". 
I don't think we currently have code support for non-player spellcasting (WIP by KorgGenT). So basically Magiclysm would have to add a lot of special attacks to monsters? Not sure if they can be declared json-only.

**Comment by actual-nh** [comment]
> As I see it, the issue is to add "spellcasting enemies".
> I don't think we currently have code support for non-player spellcasting (WIP by KorgGenT). So basically Magiclysm would have to add a lot of special attacks to monsters? Not sure if they can be declared json-only.

Take a look at mon_demon_spider in monsters/demon_spider.json:
```
"special_attacks": [ { "type": "spell", "spell_data": { "id": "burning_hands", "min_level": 4 }, "cooldown": 20 } ],
```

> I think that we could make some generic effects:
> 
> * wild mana explosion with a varying range, centered on caster
> * short range cone spell with fluctuating damage/range/AoE in different elemental flovors
> * projectile spell with small range
> 
> As I understand from the discussion, that would fit mages not being able to control themselves and having strong tendencies to explode

Also a good thought.

**Comment by RenechCDDA** [comment]
2 year-old feature request with no takers. Closing as per the last close wave, "we can not support issues asking for arbitrary content additions in the repo, there are too many issues."

That doesn't mean it can't be added, just that the issue can't sit around stale forever.
