### ISSUE TITLE
Display non-conventional damage and resistances, passive relic effects on items

### ISSUE THREAD

**Issue by Salty-Panda** [CleverRaven/Cataclysm-DDA#48674]
# Is your feature request related to a problem? Please describe.

Magiclysm, AFS, probably some vanilla items too have damage/resistance against elements such as biological, electric, pure etc.
The Player has no way to know those values without checking in the repo.

Same with various passive stat boosts, speed modifiers, mana regen. Although this might be a problem since some items are supposed to be "unknown", maybe some new Flag?

# Describe the solution you'd like

Display those values if exist.

# Describe alternatives you've considered

Require some skill check (electronic/fabrication, in Magiclysm replaced with spellcraft?) to show them. The problem is we don't distinguish in any way what category those items belong too. So this approach makes little sense.

**Comment by RenechCDDA** [comment]
Protection display resolved by #64386

Enchantments still are not player facing
