### ISSUE TITLE
Increase durability of Magiclysm item by using stronger materials

### ISSUE THREAD

**Issue by Salty-Panda** [CleverRaven/Cataclysm-DDA#48676]
# Is your feature request related to a problem? Please describe.

Boots of Haste are made of Leather and Plastic, their durability is dramatically low.
Bracers are made of Leather and Steel, still somewhat lacking.
Dimensional Toolbelt uses just Leather iirc.

# Describe the solution you'd like

Make new leather-like material, replace steel with mithril/orichalcum for the more exotic items.

# Describe alternatives you've considered

New flag/code check for relic property that would artificially increase durability.

# Additional context

I'm planning to do it in unpredictable future

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
