### ISSUE TITLE
Disassembing wielded stuff doesn't update the carried weight after it's finished

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#48681]
# Describe the bug

# Steps To Reproduce

1. Wield a storage battery.
2. Disassemble it (noticing how long and awkward this is by the way).
3. You still have 200kg of shit and can't walk even though all the results are dropped.

# Expected behavior

# Screenshots

# Versions and configuration
todays master

# Additional context
[2021.04.25.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6386966/2021.04.25.zip)

**Comment by OliveChukar** [comment]
Tested on 0.E-10395-g4525b4f [64-bit] with Dark Days Ahead [dda] only no mods. Wielded a storage battery and disassembled it when finished weight in inventory did not decrease and I was unable to move but dropping a single item caused inventory weight to update and fixed the problem. I also tested with a v6 engine and a v8 engine both were heavy enough to knock the character down during disassembly but when I finished the weight left the inventory as it should.
