### ISSUE TITLE
Filling container changes amount of materials required for modification

### ISSUE THREAD

**Issue by Saicchi** [CleverRaven/Cataclysm-DDA#48686]
# Describe the bug

Filling a container with items change the amount of materials required to modify it.

# Steps To Reproduce

1. Spawn a backpack, 45 rocks and a tailor's kit.
2. Wear the empty backpack.
3. Try to modify the backpack and take note of the requirement values.
4. Put the 45 rocks inside the backpack.
5. Try to modify the backpack and notice how the requirement values increased.

# Expected behavior

Values stay the same not matter how filled the backpack is.

# Screenshots

Empty Backpack
![234927](https://user-images.githubusercontent.com/47158232/116339182-5dd29b00-a7b3-11eb-9662-31a478489aae.png)

Filled Backpack
![234946](https://user-images.githubusercontent.com/47158232/116339185-5e6b3180-a7b3-11eb-85aa-92ec47ffeba3.png)

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.E-10379-g0f86226edf [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]
]

# Additional context

**This issue extends to any container that can be modified, including armour.**

After looking around a bit the formula for calculating how many items are necessary:
`const int items_needed = mod.volume() / 750_ml + 1;` : `src/iuse_actor.cpp:4307`
`const int thread_needed = mod.volume() / 125_ml + 10;` : `src/iuse_actor.cpp:4323`

I think the problem is that they are using `item::volume` instead of `item::base_volume`.

Repairing items doesn't seem to suffer from this bug, and it uses `item::base_volume` when calculating the amount required.

```cpp
const int items_needed =
    std::max < int > ( 1, just_check ?
        std::ceil( fix.base_volume() / 250 _ml * cost_scaling ) :
        roll_remainder( fix.base_volume() / 250 _ml * cost_scaling ) );
```
`src/iuse_actor.cpp:2637`

**Comment by leemuar** [comment]
It looks like an easy change to make: just replace one function call to another.
Is there any risk it could break some other things? fi some item that was increased in size (like armor with additional kevlar plates inserted)

**Comment by Saicchi** [comment]
Only case I can think of is modifying a container A inside a backpack B, such that after you're done, A doesn't fit B anymore. But I think the game already handles those cases by dropping A.

**Comment by actual-nh** [comment]
> Only case I can think of is modifying a container A inside a backpack B, such that after you're done, A doesn't fit inside B anymore. But I think the game already handles those cases by dropping A.

It would be reasonable to require taking out container A in order to do modifications (and, for that matter, requiring emptying a container to do anything to it other than _maybe_ repairs). Just fixing what you spotted will be a good step, however.

**Comment by leemuar** [comment]
I can easily fix this, but I need some time to figure out how to compile from the source to test it. I've never done it before, and sending a PR without proper testing would be a bad idea

**Comment by actual-nh** [comment]
For Linux, the instructions in the doc subdirectory are reasonably complete, as far as I'm aware (CONTRIBUTING.md is actually under .github if using the Github/web interface).

**Comment by leemuar** [comment]
Should work fine now! I've tested it - and it works as expected
