### ISSUE TITLE
Volume exceeds capacity while making cookies

### ISSUE THREAD

**Issue by DakkaSight** [CleverRaven/Cataclysm-DDA#48695]
Making a cookie, selected ingredients of Flour, Maple Syrup, Clean Water and an Orange.

 DEBUG    : volume exceeds capacity (5230ml > 4500ml)

 FUNCTION : float item_contents::relative_encumbrance() const
 FILE     : src/item_contents.cpp
 LINE     : 1499

# Steps To Reproduce

Select Cookie recipe
Select Flour as the first ingredient
Select Maple Syrup as the 2nd ingredient
Select Clean Water as the 3rd ingredient
Select an orange as the 4th ingredient - error immediately appears.

# Expected behavior

I should get a tasty cookie!

# Screenshots
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6396219/debug.log)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-10395-g4525b4f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

 - OS: Windows 10
 - Game Version: 0.E-10395-g4525b4f
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: default
 -->

# Additional context

None, game doesn't crash - recipe fails and resources are lost.

**Comment by actual-nh** [comment]
What (container) were you trying to make it in?

**Comment by DakkaSight** [comment]
I was using a Charcoal Cooker

**Comment by RoyBerube** [comment]
I'm unable to reproduce this on the latest master build. 

From the debug.log provided it is failing when trying to put an item into the player's inventory, but nothing should be going into the player's inventory. The cookies don't use a cook tool other than a heat source - oversight maybe - and are placed on the counter when finished. 

With the charcoal cooker in inventory and suspending the craft, the in progress cookie is placed on the counter. 

A single batch of 4 cookies takes up .05L so those can't account for the volume. It is a mystery.
