### ISSUE TITLE
(F)ire Command for Melee Weapons

### ISSUE THREAD

**Issue by SibilantScream** [CleverRaven/Cataclysm-DDA#48698]
As is if you want to attack while having 0 vision tiles you risk moving & losing move points\position, if we could fire melee weapons like reach attack or guns we have better options.
Another point is this creatures at different Z-levels can't be targeted with melee weapons, where realistically you should be able to even if less accurately. This accuracy penalty can also be accounted for when attacking blindly at 0 tile vision.

**Comment by KittyTac** [comment]
Perhaps like in Dwarf Fortress? Ctrl+<direction> = force attack in a direction. Would be more... intuitive I guess than firing a quarterstaff.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
