### ISSUE TITLE
Crash on using NPC sort armor menu to equip clothing to NPCs

### ISSUE THREAD

**Issue by Caiggas** [CleverRaven/Cataclysm-DDA#48691]
# Describe the bug

When you try to equip armor/clothing onto an NPC using the sort armor menu the game crashes. I have tested this with both an AEP suit and a sheet. I have attached a screenshot.

# Steps To Reproduce

1. Drop clothing/armor underneath or next to an NPC.
2. Interact with the NPC.
3. Select "sort armor".
4. Use Shift+E to equip items from the NPCs location.
5. Select an item with the enter key.
6. Game will now crash.

# Expected behavior

I expected the item menu to close and the NPC to be wearing the item.

# Screenshots

Added Screenshot

# Versions and configuration

 - OS: Windows 10 20H2
 - Game Version: 0.E-10214-ga70b7d0
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: dda, no_npc_food, package_bionic (This is cut off, it is the Bionic Professions mod.), alt_map_key

# Additional context

Equipping items through dialogue with the NPC works fine.

Crash: 
[Logs and Screenshot.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6393487/Logs.and.Screenshot.zip)

Save File:
Save file is too big. 33 mB. Not sure how to correct this. Is there somewhere else I can upload it?

**Comment by Salty-Panda** [comment]
Did you compress your save?
You should be able to reduce it to 7-10% or original size

**Comment by Caiggas** [comment]
> Did you compress your save?
> You should be able to reduce it to 7-10% of original size

Yeah, that is the compressed size. I can see if I can figure out what map chunks are not near me and delete them. That ought to reduce the size.

**Comment by actual-nh** [comment]
Google Docs?

**Comment by Caiggas** [comment]
https://drive.google.com/file/d/1sp5yzUG-RvcY31NFwply0DbtiZpvhVpk/view?usp=sharing

Here is a google drive link to the save file. Sorry for the long wait.
