### ISSUE TITLE
Extend VS compiling tutorial by explanation of usage of flags

### ISSUE THREAD

**Issue by Salty-Panda** [CleverRaven/Cataclysm-DDA#48702]
# Is your feature request related to a problem? Please describe.

Wanted to compile the game for regular playing, had to ask for help on Discord

# Describe the solution you'd like

Include in the tutorial how/where to use flags like USE_HOME_DIR, what can be configured for compiling (sounds, localization, cores)

# Describe alternatives you've considered

Changing it myself but I'm clueless about VS and c++ compiling in general, blindly followed the tutorial

# Additional context
Is the default `<MultiProcessorCompilation>true</MultiProcessorCompilation>` all I need or can I squeeze faster compiling with some option?

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
