### ISSUE TITLE
Problems with small screen phones

### ISSUE THREAD

**Issue by 2659848223** [CleverRaven/Cataclysm-DDA#48701]
When I play on the first generation of my iPhone se, the content of the game is not comprehensive, such as missing menu list and missing buttons. It's obviously different from my iPad, but my iPad is too heavy, so I don't want to play on it. I hope developers can fix this bug as soon as possible, so as to give us a better game experience.
![4A8C1494-23EB-4D9F-AC14-78DEAD5123E5](https://user-images.githubusercontent.com/83422402/116605594-2e15c580-a962-11eb-8c77-7a76a8ca4282.png)

**Comment by actual-nh** [comment]
You're running iOS, I am guessing?

**Comment by 2659848223** [comment]
Yes.so,are you in the same situation as me?

**Comment by actual-nh** [comment]
No, I'm on a Mac. The iOS port (<https://github.com/apollovy/Cataclysm-DDA-iOS>) may be where the problem is - on the other hand, it may be something like #48700. Can you try switching to English and seeing if stuff fits on the screen then?

**Comment by 2659848223** [comment]
Ok, I will try.

**Comment by 2659848223** [comment]
I tried but failed. although I like the game very much, it seems that I can only look forward to the subsequent update.
![13AEAFEF-F015-4814-8496-6E25C6432B9D](https://user-images.githubusercontent.com/83422402/116629550-0e8f9480-a984-11eb-97dd-9f519724e8ea.png)

**Comment by actual-nh** [comment]
Actually, I suggest putting in an issue over at <https://github.com/apollovy/Cataclysm-DDA-iOS> - that is in the process of being incorporated into this repository, but it isn't as yet.
