### ISSUE TITLE
Harmonising the game with different terminal color schemes

### ISSUE THREAD

**Issue by MaximilianC** [CleverRaven/Cataclysm-DDA#4870]
I spend most of my time in the terminal within vim/the shell/irssi, so naturally I use a custom color scheme (in my case the popular Solarized scheme - http://ethanschoonover.com/solarized) to avoid eyestrain. Unfortunately, Solarized mixes up the bright (bold) colors, so every time I switch to Catacylsm-DDA (I run all my applications in tmux), I have to change the color scheme of my terminal (iTerm2). This is annoying because I usually play in short periods by quickly switching over from vim.

Is there a possibility to realloc the 8 upper/bright color slots easily to some matching colors in the whole 256 color space? My reasoning is that everybody who is running the game within the terminal probably uses it for other tasks as well and won't use the standard ANSI colors.

**Comment by illi-kun** [comment]
I guess #11865 implements core functionality for color management. Feel free to reopen the issue if it's not enough.
