### ISSUE TITLE
Crafting recipe search UI does not show up for some languages when using tiny game window

### ISSUE THREAD

**Issue by olanti-p** [CleverRaven/Cataclysm-DDA#48700]
# Describe the bug
Crafting recipe search UI does not show up for some languages when using tiny game window

# Steps To Reproduce
1. Set language to English, set game window to the minimum (80x24)
2. Enter crafting menu
3. Hit `/`. Search window pops up
4. Get back to settings, choose Russian
5. Enter crafting menu
6. Hit `/`. Nothing happens.
7. Drag bottom border of the game window down. When window height reaches 26, the search UI shows up.

On step 6, you can still blindly type something and press `Enter`, and the search will work, so it's likely a display bug.

# Screenshots
80x26, English
![image](https://user-images.githubusercontent.com/60584843/116589677-8ed2dd00-a925-11eb-9937-aa76cfeefe73.png)

80x26, Russian
![image](https://user-images.githubusercontent.com/60584843/116589465-58955d80-a925-11eb-8279-7633ef476159.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-10395-g4525b4f [64-bit] (aka build 11581)
- Graphics Version: Tiles
- Game Language: Русский [ru]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by Qrox** [comment]
My guess is that due to the longer russian text, the search UI becomes higher than the game window, which causes window creation to fail. Limiting the search window height to the game window height in `string_input_popup::create_window` may fix this problem.
