### ISSUE TITLE
Fragile items (e.g glass bottles) don't shatter when thrown

### ISSUE THREAD

**Issue by KittyTac** [CleverRaven/Cataclysm-DDA#48707]
# Describe the bug

See title. If you throw them it shows a message about it shattering but the item stays.

# Steps To Reproduce

1. Debug in a glass bottle or the like.
2. Throw it.
3. See that despite there being a message about the bottle shattering, the bottle is not destroyed.

# Expected behavior

The object is destroyed and becomes a pile of glass shards.

# Screenshots

Not necessary.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-10389-g4a67b7c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Kittymod [kittymod],
    Tankmod: Revived [Tankmod_Revived],
    Tankmod: Revived - UndeadPeople Tileset [Tankmod_RevivedUDP]
]

# Additional context
Kittymod is my personal mod, it doesn't alter any of those items or their materials, shouldn't affect this.

**Comment by zeropol** [comment]
I can confirm this  (tried glass bottle, glass pipe, glass flask, glass jar, glass shiv).

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-10472-g245065a1ef [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]
