### ISSUE TITLE
[Magiclysm] Allow Translocator Gates to be disassembled.

### ISSUE THREAD

**Issue by Jan-Blasiak** [CleverRaven/Cataclysm-DDA#48715]
Since teleporters are an extremely, and I mean EXTREMELY rare resource - allow players to disassemble Translocator Gates to get a teleporter, or make Translocator Gates require some other kind of special item to craft that isn't a teleporter if item scarcity works as intended.

I've played for IRL three months, from IG early spring to the begining of winter, but despite making multiple lab raids, clearing two cites and finding one working Translocator Gate, I wasn't able to find a teleporter to place one in my own base.

**Comment by actual-nh** [comment]
Either that (which appears reasonable) or make it possible/easier to move a Translocator Gate?

**Comment by connorpmartin** [comment]
you could maybe make them deployable in a similar manner to butchering racks?

**Comment by Maddremor** [comment]
First of all, you can get a teleporter by disarming and disassembling a teleporter trap which are fairly common in procgen labs.

Secondly, my impression of the gates is that they are not meant to be easily movable, but to act as a link between high value locations. If you can disassemble and reassemble them at will, you could just make a gate wherever you made camp for the night or at the roadside by your parked deathmobile.

**Comment by Salty-Panda** [comment]
Why highly magical item relies on hightech item in the first place?

**Comment by Maddremor** [comment]
> 
> 
> Why highly magical item relies on hightech item in the first place?

I can't speak for KorGgenT, but I assume it to be a combination of it being thematically adjacent, a semi rare resource, and there were no better candidates at hand.

**Comment by PudgyElderGod** [comment]
> If you can disassemble and reassemble them at will, you could just make a gate wherever you made camp for the night or at the roadside by your parked deathmobile.

I don't see much of an issue with this. If you've found the Geospatial Systems book, can break into a lap and thief a teleporter, and can reliably secure a location with your death mobile... Why shouldn't you be able to set up and relocate safe bases of operations with a recall system?

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
