### ISSUE TITLE
Change Morphine's description to state that it is a natural drug

### ISSUE THREAD

**Issue by devoured-by-incandescence** [CleverRaven/Cataclysm-DDA#48710]
# Is your feature request related to a problem? Please describe.

Morphine's description in-game states that it's a semi-synthetic opioid. This is false. Morphine is a naturally occurring drug. Semi-synthetics require synthetization from a natural drug, as opposed to naturally occurring drugs, which only need extraction, and total synthetic drugs, which are synthesized, typically, from other synthetic bases. 

# Describe the solution you'd like

Morphine's description should state that it is a natural opioid. "A very strong naturally occuring narcotic used to treat intense pain..." 

# Describe alternatives you've considered

Outright remove the part of the description that states that it is a semi-synthetic narcotic without replacement, simply referring to it as "A very strong narcotic..."

# Additional context

While heroin is a semi-synthetic opioid and tramadol is a synthetic opioid, morphine is most definitely naturally present in opium as the majority of its alkaloid content. While morphine does need to be chemically extracted from the opium rubber before use, synthetization methods of morphine are currently far too expensive to pursue on industrial scale, and likely always will be, according to experts in the field. Besides that, synthetically produced morphine is totally synthetic, not semi-synthetic. Virtually all morphine in use in the medical industry, the black market drug trade, and any other contexts it might be found in is natural morphine, extracted from opium rubber, though opium straw extractions are also common. This isn't the biggest deal, of course, but it is inaccurate.

https://en.wikipedia.org/wiki/Morphine#Production
https://en.wikipedia.org/wiki/Morphine#Chemical_synthesis

**Comment by ZhilkinSerg** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/9034

**Comment by actual-nh** [comment]
"A very strong, naturally-occurring narcotic used to treat intense pain" would be better IMO. This will need to go into 0.F-dev, or wait until after 0.F comes out (which marking it with "0.F String Freeze" will enable doing).

**Comment by LohTek** [comment]
> WHAT ARE SYNTHETIC OPIOIDS? 
> 
> Synthetic opioids are substances that are synthesized in a laboratory and that act on the same targets in the brain as natural opioids (e.g., morphine and codeine) to produce analgesic (pain relief) effects. In contrast, natural opioids are naturally occurring substances extracted from the seed pod of certain varieties of poppy plants. Some synthetic opioids, such as fentanyl and methadone, have been approved for medical use.

According to the DOJ's own classification of synthetic drugs.
