### ISSUE TITLE
Crashing in Cataclysm Dark Days Ahead

### ISSUE THREAD

**Issue by Sandew7** [CleverRaven/Cataclysm-DDA#48711]
# Describe the bug
When I tried to open Cataclysm on my MacBook Pro, it immediately crashed while displaying an error message. 
It just displayed a black window along with the error message. 

# Steps To Reproduce

1. Open applications folder in 'Finder'
2. Click on Cataclysm
3. An error message saying that the game has crashed is displayed.

# Expected behavior

I expected the game to open so that I can play it.
This is because, it always worked properly when I played it on my windows pc

# Screenshots

 

# Versions and configuration

OS: macOS 10.13.6
Game Version: 0.E-10395-g4525b4f
Graphics Version: Tiles
Ingame language: English
Mods Loaded: None

# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6406398/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6406399/debug.log)

**Comment by Inglonias** [comment]
It might be worth moving your config folder out of the cataclysm folder so it generates a new one (don't delete it if you've made changes). I'm seeing some issues with the fonts.json file in the debug log, which suggests some sort of config problem.

**Comment by Sandew7** [comment]
Thanks, it worked

**Comment by Sandew7** [comment]
I thought the fix worked but it turns out that it is still crashing every few minutes
Any further instructions?

**Comment by Sandew7** [comment]
I've realised that the crashing is due to a different problem so I am creating a new issue.
