### ISSUE TITLE
Edible as-is sealed food (canned jarred etc) gets sorted in perishible order.

### ISSUE THREAD

**Issue by Anaglyphic** [CleverRaven/Cataclysm-DDA#48732]
Again, sorry if dupe, I did do a search but a generic terms like "sealed" food "canned food" etc. in a database of 1.6k entries leads to lots of hits. I did scan pretty diligently after my last faceplant over playing permanently crouching. :rofl: 

As long as you're awake and paying attention and playing at a computer, you might not notice or care about this one. You get used to it. Playing on a portable with limited screen space, playing when you're distracted and tabbing between apps, etc. You'll see you're hungry, pull up consume, and eat things in the order of spoilage - even though it wasn't going to spoil, it was at the top, so nom nom nom. I'm frowning now? _Oh that was dog food._ But I had fresh lasagne that's only got 2 days left right here!

# Describe the bug

As title. Sealed foods that can be consumed as-is without preparation gets sorted on the consume list by age/perishable date as if the container was open, creating an inference that you opened it and it's spoiling. It shows a product's unpackaged shelf life and spoils in timeframe, which is grossly incorrect!

# Steps To Reproduce

Have any canned jarred etc foods that are immediately edible if opened in your inventory or nearby; soups, peanut butter, tuna fish, hell even wet cat food... and invoke consume menu. Instead of being darker tinted cyan of nonperishable-even-once-opened foods and drinks, they at the top, and sorted within in the same bright cyan colour as fresh fruit or already cooked meals made from the crafting menu.

# Expected behaviour

Sealed but immediately edible foods that are edible should change the "spoils in" to indefinite, and the unpackaging routine changes that to the shelf life value. This way the canned-but-immediately-edible stuff is moved to the bottom of the you-can-eat-it-now consumables list, and not sorted in amongst opened packages and prepped foods

# Screenshots

![Screenshot at 2021-05-02 05-12-22](https://user-images.githubusercontent.com/19985100/116808099-0743c480-ab05-11eb-8f86-b130a7ef6cf8.png)

# Versions and configuration

linux vanilla 5.12 and any of the later Epsilon builds where the new food container system exists, this particular one is 0.E-10395-g4525b4f (last Narc autobuild, 4/15) w/ dda & no_npc_food

# Additional context

probably unnecessary.

**Comment by actual-nh** [comment]
Well, I don't think that there's an actual issue previously for this, although there is a PR to fix it (albeit currently in draft) - #46866.

**Comment by strategineer** [comment]
This is resolved by  #54020 i think

**Comment by Brambor** [comment]
Agreed. @Anaglyphic can reopen if there is something left to do.
