### ISSUE TITLE
Crashing In Cataclydm DDA

### ISSUE THREAD

**Issue by Sandew7** [CleverRaven/Cataclysm-DDA#48731]
# Describe the bug

The game crashes approximately 15-30 mins after I open the application on my macOS.

# Steps To Reproduce

1. Click on Cataclysm application in the Applications folder in the Finder application
2. Click on 'Open' when a window is displayed showing the message: '"Cataclysm" is an application downloaded from the internet. Are you sure you want to open it?'.
3. Press the Spacebar when this error message is displayed: 
![Screen Shot 2021-05-02 at 08 47 22](https://user-images.githubusercontent.com/83463350/116800949-28b3a900-ab23-11eb-820f-a129caa8b1ab.png)
4. 

4. Click on Load 
5. Select the save to be loaded
6. Press Spacebar when the error messages whose screenshots are available in the Screenshots.
7. Play until the game crashes

# Expected behavior

I except the game to be played the way it is supposed to without crashing.

# Screenshots

   ![Screen Shot 2021-05-02 at 08 51 34](https://user-images.githubusercontent.com/83463350/116801002-9e1f7980-ab23-11eb-9322-fab8eb82952c.png)
![Screen Shot 2021-05-02 at 08 52 13](https://user-images.githubusercontent.com/83463350/116801015-b394a380-ab23-11eb-950f-7458e5773bd8.png)
![Screen Shot 2021-05-02 at 08 55 28](https://user-images.githubusercontent.com/83463350/116801079-2867dd80-ab24-11eb-9e32-5f22a27f4404.png)
![Screen Shot 2021-05-02 at 08 55 55](https://user-images.githubusercontent.com/83463350/116801088-37e72680-ab24-11eb-8a41-ed77a5a093fe.png)
![Screen Shot 2021-05-02 at 08 56 19](https://user-images.githubusercontent.com/83463350/116801101-459cac00-ab24-11eb-9f6e-fee03604f674.png)
![Screen Shot 2021-05-02 at 08 56 46](https://user-images.githubusercontent.com/83463350/116801117-61a04d80-ab24-11eb-8b52-b20f81487f48.png)
![Screen Shot 2021-05-02 at 08 57 27](https://user-images.githubusercontent.com/83463350/116801121-6d8c0f80-ab24-11eb-9e18-60ccd2ca839a.png)
![Screen Shot 2021-05-02 at 08 57 47](https://user-images.githubusercontent.com/83463350/116801127-7977d180-ab24-11eb-86b7-6f21a7fb5243.png)
![Screen Shot 2021-05-02 at 08 58 09](https://user-images.githubusercontent.com/83463350/116801133-8694c080-ab24-11eb-8d18-ecbccf21c81a.png)
![Screen Shot 2021-05-02 at 08 58 25](https://user-images.githubusercontent.com/83463350/116801141-914f5580-ab24-11eb-8fe7-c92090d654b4.png)
![Screen Shot 2021-05-02 at 08 58 41](https://user-images.githubusercontent.com/83463350/116801144-99a79080-ab24-11eb-96f4-a4a7dac94fb4.png)
![Screen Shot 2021-05-02 at 08 58 53](https://user-images.githubusercontent.com/83463350/116801148-a0360800-ab24-11eb-95b2-d7a6e651bfbd.png)
![Screen Shot 2021-05-02 at 08 59 12](https://user-images.githubusercontent.com/83463350/116801156-ac21ca00-ab24-11eb-8e9b-1e91370c8b63.png)

# Versions and configuration

- OS: MacOs
    - OS Version: Name: Mac OS X; Version: 10.13.6; Build: 17G14019; 
- Game Version: 0.E-10395-g4525b4f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Icecoon's Arsenal [ew_pack],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    MST Extra [MST_Extra],
    Graphical Overmap [Graphical_Overmap],
    Classes and Scenarios Mod [more_classes_scenarios],
    No Filthy Clothing [no_filthy_clothing],
    Simplified Nutrition [novitamins],
    Stats Through Skills [StatsThroughSkills],
    Folding Parts pack [deoxymod]
]

# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6410778/crash.log)
(The debug log file did not appear after the crash)
Save file: [Stormsville.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6410783/Stormsville.zip)

**Comment by ZhilkinSerg** [comment]
You have some tileset installed twice. Also it looks like you are using some mods which are incompatible with your game version. Try removing duplicate tileset and starting a game without any third party mods.

**Comment by Sandew7** [comment]
It works, thanks
