### ISSUE TITLE
Cdda Bug

### ISSUE THREAD

**Issue by GreatRegret** [CleverRaven/Cataclysm-DDA#48730]
# Describe the bug
When I shoot any gun that i have it automatically treats it as i have been aiming and thus resulting in less moves to fire the precise shots

# Expected behavior

I expected to happen is that I would have to press 5 or . to aim so that there would be a better chance to get a good hit.
I expected this to happen because this is what happened when I first played the game.

# Screenshots 
![image](https://user-images.githubusercontent.com/83526735/116802028-15640600-ab42-11eb-9ba4-7a26752369b6.png)

# Versions and configuration

# Additional context
This is happening for a 2 weeks now and it doesnt show a bug popup

**Comment by Anaglyphic** [comment]
Hi.

As someone that's gotten bitten by things like this, I walked around for an embarrassing amount of time perma-crouched, so let me try CDDA 101, _"is it plugged in and turned on?"_

What I mean is, if it's looking like that, like it's taking a ton o turn to "pre-aim" ? Chances are that's what you did, you set the default firing mode to something other than immediate.

Easy enough to verify, equip a ranged weapon and press **f** then **s** and see which firing mode is set as **(active)** first.

![Screenshot at 2021-05-02 21-34-32](https://user-images.githubusercontent.com/19985100/116834941-508c2680-ab8e-11eb-8d74-1569ff29ae29.png)
