### ISSUE TITLE
Zombie animal bugs

### ISSUE THREAD

**Issue by LyleSY** [CleverRaven/Cataclysm-DDA#48743]
# Describe the bug

Vormithrax noticed a few issues with #41844 and #41317 . The upgrade lists had the Kevlar hulk bug. I already have a PR in for that. There is a bear with "moose" in the name. Most interestingly, boneplate wolves have zero attack dice, so the SMASH attack fails to do anything and they only use special attacks, making them way less difficult than intended.

# Steps To Reproduce

1. Start very late, say 28 months in
2. Wander around in the woods, observe all the boneplate wolves
3. Fight them and win with a day one character

# Expected behavior

More monster diversity, Thorny moose shambler spawns with the right name. Boneplate wolves are dangerous, though not as bad as skeletal juggernauts

# Versions and configuration

Latest experimental, no mods

# Additional context

Thanks to Vorm for catching all this, I normally don't survive long enough to see it

**Comment by LyleSY** [comment]
Ah, #48733 has been merged, that bit is fixed

**Comment by actual-nh** [comment]
mon_zoose_thorny - will need to wait until after 0.F given string freeze. For mon_dog_skeleton_brute, what would be the appropriate fix for:
```
"relative": { "melee_dice": -1, "melee_dice_sides": 2, "melee_cut": 6 },
```
Remove the negative sign, or remove the adjustment to melee_dice altogether?

**Comment by LyleSY** [comment]
I think just removing the negative sign will do it

**Comment by LyleSY** [comment]
I've sliced the fixes into two separate PRs if the mergers want to wait on the moose fix.
