### ISSUE TITLE
Fire does not spread in Burning Building start

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#48747]
# Describe the bug

When choosing the "Burning Building" start, there is no real danger from the fire in the building because the initially generated fire tiles do not spread.

# Steps To Reproduce
1. Create a new character in the Burning Building scenario
2. Kill all monsters with the debug menu so you can appreciate the bug without interruption.
3. Wait around for a while for the building to collapse. It doesn't do that. The fire tiles do not spread.
4. Use a lighter to start a small fire somewhere. All existing fire in the area starts to behave as expected.

# Expected behavior

I want to see the building burn down!

# Screenshots

I have been waiting for four hours for this building to burn down.
![image](https://user-images.githubusercontent.com/2125926/117008983-46b31200-acb9-11eb-8aba-71946d62d61a.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-10395-g4525b4f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Monsters [Only_Wildlife]
]

# Additional context

N/A

**Comment by ZhilkinSerg** [comment]
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/37378

**Comment by Inglonias** [comment]
Right, but that issue was closed as fixed.

**Comment by ZhilkinSerg** [comment]
Cannot reproduce on Android with version d55d4a1 [64-bit]

**Comment by ZhilkinSerg** [comment]
Possibly reproduced with https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-jenkins-b11572 on Android 64 bit

**Comment by Inglonias** [comment]
Odd. This occurs on my laptop, but not on my desktop. Let me try my laptop again.

**Comment by Inglonias** [comment]
Closing this issue as CNR. This issue is occurring on my laptop, but not on my desktop, leading me to believe the issue lies there and not with the game's code. Weird. I'll try reinstalling the game on my laptop.

**Comment by Zireael07** [comment]
What is different with the laptop? Different OS? Different bitness?

**Comment by Inglonias** [comment]
Different hardware, obviously, but the same OS and game versions. Very strange. I can work around this issue by saving/loading the game, which is relatively fast considering that the game had only just started when this is relevant
