### ISSUE TITLE
Проблема 

### ISSUE THREAD

**Issue by BlackRainbow69** [CleverRaven/Cataclysm-DDA#48741]
DEBUG    : (json-error)
Json error: <unknown source file>:2:21: Invalid or misplaced field name "fontblending" in JSON data

{
    "fontblending" :
                    ^
                     false,
    "fontwidth" : 9,
    "fontheight" : 15,

 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : src/json.cpp
 LINE     : 122
 DEBUG    : (json-error)
Json error: <unknown source file>:4:19: Invalid or misplaced field name "fontheight" in JSON data

    "fontblending" : false,
    "fontwidth" : 9,
    "fontheight" :
                  ^
                   15,
    "fontsize" : 14,
    "typeface" : "TerminusRus",

 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : src/json.cpp
 LINE     : 122
 DEBUG    : (json-error)
Json error: <unknown source file>:5:17: Invalid or misplaced field name "fontsize" in JSON data

    "fontwidth" : 9,
    "fontheight" : 15,
    "fontsize" :
                ^
                 14,
    "typeface" : "TerminusRus",
    "map_fontwidth" : 9,

 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : src/json.cpp
 LINE     : 122
 DEBUG    : (json-error)
Json error: <unknown source file>:3:18: Invalid or misplaced field name "fontwidth" in JSON data

{
    "fontblending" : false,
    "fontwidth" :
                 ^
                  9,
    "fontheight" : 15,
    "fontsize" : 14,

 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : src/json.cpp
 LINE     : 122
 DEBUG    : (json-error)
Json error: <unknown source file>:8:23: Invalid or misplaced field name "map_fontheight" in JSON data

    "typeface" : "TerminusRus",
    "map_fontwidth" : 9,
    "map_fontheight" :
                      ^
                       15,
    "map_fontsize" : 14,
    "map_typeface" : "TerminusRus",

 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : src/json.cpp
 LINE     : 122
 DEBUG    : (json-error)
Json error: <unknown source file>:9:21: Invalid or misplaced field name "map_fontsize" in JSON data

    "map_fontwidth" : 9,
    "map_fontheight" : 15,
    "map_fontsize" :
                    ^
                     14,
    "map_typeface" : "TerminusRus",
    "overmap_fontwidth" : 9,

 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : src/json.cpp
 LINE     : 122

 DEBUG    : (json-error)
Json error: <unknown source file>:7:22: Invalid or misplaced field name "map_fontwidth" in JSON data

    "fontsize" : 14,
    "typeface" : "TerminusRus",
    "map_fontwidth" :
                     ^
                      9,
    "map_fontheight" : 15,
    "map_fontsize" : 14,

 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : src/json.cpp
 LINE     : 122
 DEBUG    : (json-error)
Json error: <unknown source file>:12:27: Invalid or misplaced field name "overmap_fontheight" in JSON data

    "map_typeface" : "TerminusRus",
    "overmap_fontwidth" : 9,
    "overmap_fontheight" :
                          ^
                           15,
    "overmap_fontsize" : 14,
    "overmap_typeface" : "TerminusRus"

 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : src/json.cpp
 LINE     : 122
 DEBUG    : (json-error)
Json error: <unknown source file>:13:25: Invalid or misplaced field name "overmap_fontsize" in JSON data

    "overmap_fontwidth" : 9,
    "overmap_fontheight" : 15,
    "overmap_fontsize" :
                        ^
                         14,
    "overmap_typeface" : "TerminusRus"
}

 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : src/json.cpp
 LINE     : 122
 DEBUG    : (json-error)
Json error: <unknown source file>:11:26: Invalid or misplaced field name "overmap_fontwidth" in JSON data

    "map_fontsize" : 14,
    "map_typeface" : "TerminusRus",
    "overmap_fontwidth" :
                         ^
                          9,
    "overmap_fontheight" : 15,
    "overmap_fontsize" : 14,

 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : src/json.cpp
 LINE     : 122

**Comment by Salty-Panda** [comment]
I have same error, I think it's caused by outdated Undead People tileset, but it doesn't bother me so never investigated

**Comment by BlackRainbow69** [comment]
Проблема в том, что у меня нет тайлов Undead

**Comment by Salty-Panda** [comment]
Post game version information, according to instruction in Issue template

**Comment by BlackRainbow69** [comment]
Игра будет нормально функциоровать если не решить проблему?

**Comment by ZhilkinSerg** [comment]
Delete `fonts.json` from `config` folder.

**Comment by BlackRainbow69** [comment]
Удаление fonts.json из config помогло
