### ISSUE TITLE
Allow different night vision color

### ISSUE THREAD

**Issue by linonetwo** [CleverRaven/Cataclysm-DDA#48753]
# Is your feature request related to a problem? Please describe.

Night vision makes the whole screen green, which color is somehow bad for eyes after long staring at it.

![Screen Shot 2021-05-05 at 19 34 49](https://user-images.githubusercontent.com/3746270/117135018-fa5ef380-add8-11eb-91a8-305187ab213c.png)

# Describe the solution you'd like

Maybe allow reduce the green scale, in the option. Just like how we adjust color of maps in the memory.

Look at previous PR about night vision, seems it need change of C++
https://github.com/CleverRaven/Cataclysm-DDA/pull/13715/files

# Describe alternatives you've considered

Or allow turn off the green scale when we have night vision.

# Additional context

My eyes now feels everything is red.

**Comment by Night-Pryanik** [comment]
> Or allow turn off the green scale when we have night vision.

We have an option to turn night vision filter off in #53170. Would this suffice?

**Comment by linonetwo** [comment]
Sure! Similar to #53167 this is ok to close.
