### ISSUE TITLE
can't set ammo null in XM34 EMP projector as it is not an ammo when trading with NPC

### ISSUE THREAD

**Issue by Hirmuolio** [CleverRaven/Cataclysm-DDA#48771]
# Describe the bug

If you try to trade with an NPC while wielding XM34 EMP projector you will get this error message:

```
 DEBUG    : can't set ammo null in XM34 EMP projector as it is not an ammo

 FUNCTION : item& item::ammo_set(const itype_id&, int)
 FILE     : src/item.cpp
 LINE     : 549

```

SInce XM34 EMP projector doesn't have ammo type for itself the game tries to load null ammo into it.

This happens in `Character::gun_value` on this line https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/ranged.cpp#L1824

Also on this line the game seems to think that XM34 EMP projector is a magazine. Which is a bit weird. https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/ranged.cpp#L1812

The same probably happens with all electric powered weapons.

# Steps To Reproduce

1. Have XM34 EMP projector it in inventory/wield it
3. Trade with NPC

# Expected behavior

No error

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-10395-g4525b4f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Dark Days of the Dead [classic_zombies],
    No Monsters [Only_Wildlife]
]

# Additional context

**Comment by hexagonrecursion** [comment]
Could not reproduce
- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 17b9ea1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]
