### ISSUE TITLE
Allow size flags for mutations

### ISSUE THREAD

**Issue by Stadler76** [CleverRaven/Cataclysm-DDA#48774]
# Is your feature request related to a problem? Please describe.
In the magiclysm-mod the black dragon mutation uses its own version for the sizes `LARGE`, `LARGE_OK`, `HUGE`, `HUGE_OK`, but the character/player height value isn't updated.

# Describe the solution you'd like
Allow the mutation-/trait-flags:
- `SMALL2`
- `SMALL_OK`
- `SMALL`
- `LARGE`
- `LARGE_OK`
- `HUGE`
- `HUGE_OK`

Should be farily easy to implement (I hope) by (untested so far):
```cpp
void Character::recalculate_size()
{
    if( has_trait( trait_SMALL2 ) || has_trait_flag( json_flag_SMALL2 ) ||
        has_trait( trait_SMALL_OK ) || has_trait_flag( json_flag_SMALL_OK ) ) {
        size_class = creature_size::tiny;
    } else if( has_trait( trait_SMALL ) || has_trait_flag( json_flag_SMALL ) ) {
        size_class = creature_size::small;
    } else if( has_trait( trait_LARGE ) || has_trait_flag( json_flag_LARGE ) ||
        has_trait( trait_LARGE_OK ) || has_trait_flag( json_flag_LARGE_OK ) ) {
        size_class = creature_size::large;
    } else if( has_trait( trait_HUGE ) || has_trait_flag( json_flag_HUGE ) ||
        has_trait( trait_HUGE_OK ) || has_trait_flag( json_flag_HUGE_OK ) ) {
        size_class = creature_size::huge;
    } else {
        size_class = creature_size::medium;
    }
}
```
in `mutation.cpp` and by adding the corresponding `json_character_flag`s to `character.cpp`.

It's untested, since I didn't yet find the time to setup a dev-environment.

**Comment by ZhilkinSerg** [comment]
Better yet replace `has_trait_flag` check with `has_trait_flag` check for size-related mutations, so it won't be attached to mutations ids.

**Comment by Stadler76** [comment]
Here's the diff: [20210511_0305_mutation-size-flags.diff.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/6455792/20210511_0305_mutation-size-flags.diff.txt)
