### ISSUE TITLE
Cigarette packs fit more than their initial full amount.

### ISSUE THREAD

**Issue by O1OOO1O** [CleverRaven/Cataclysm-DDA#48780]
# Describe the bug
Cigarette packs fit more than their initial full amount.
# Steps To Reproduce
Have lots of cigarette packs with variable amounts of cigarettes in the. 
Have a few full packs with the standard max 20 amount. 
Unload all packs that are not full.
Verify you have empty packs in your inventory and a load of loose cigarettes.
Select a full pack containing 20 cigarettes in it, select insert and target the loose cigarettes, you van fit one more in to have 21.

# Expected behavior
Standard max cigarettes in a pack is 20.

Also it would be really nice if Empty cigarette packs were called 'cigarette pack (empty)' or somthing right now they are just called 'pack' which can be confusing.

# Versions and configuration
build 11581

**Comment by Zeropol** [comment]
Confirmed in `0.E-10474-g1ae66c97a0-dirty [64-bit]` that we can insert 21 cigs in a pack.
![image](https://user-images.githubusercontent.com/28099824/117396234-d3e4a980-aef9-11eb-9df9-d3cd076c279d.png)

**Comment by O1OOO1O** [comment]
I also noticed that  the packs do not showup in the reload menu, but I didn't include that because I wasn't sure if they were supposed to or not, or if that's just meant to represent ammo containers & weapons.

**Comment by Anaglyphic** [comment]
Hi. To be fair, in these apocryphal times, maybe it's OK you squeezed _one more_ in the box than it normally holds? _No?_ Well, the obvious choices are shrink  _box_cigarette_'s capacity, or increase a  _cig_'s volume; Example below is the former, the smallest whole-number reduction that allows only 20: 

(base) [anaglyphic@shakes cataclysm-dda-0.E-10519-g272a1d4244]$ git diff -U2
```
diff --git a/data/json/items/containers.json b/data/json/items/containers.json
index ecc421bd78..25590b9f52 100644
--- a/data/json/items/containers.json
+++ b/data/json/items/containers.json
@@ -451,5 +451,5 @@
     "symbol": ")",
     "color": "white",
-    "pocket_data": [ { "pocket_type": "CONTAINER", "rigid": true, "max_contains_volume": "90 ml", "max_contains_weight": "3 kg" } ]
+    "pocket_data": [ { "pocket_type": "CONTAINER", "rigid": true, "max_contains_volume": "87 ml", "max_contains_weight": "3 kg" } ]
   },
   {
```
(_this will also limit joints, handrolled cigarettes, etc. at 20... candycigarette are bery borken though, listed at length 1in / 25mm, weigh 18g, contain 130 calories, and expire in 180 days? Uhh... sure why not? In reality candy cigarettes are slightly smaller than a regular cigarette, 30-40 calories, weigh a couple grams, they'll last 100 years, the taste being as gross as ones made yesterday. Much like those chalky valentine's day message hearts._)

**Comment by gabu0** [comment]
If you're a non-smoker or never worked in retail you won't know this but cigarette packs contain a lot of empty space to appear larger. Marlboro is notorious for this especially, so it makes sense that you can fit one more cigarette into a 20-pack.

**Comment by Maleclypse** [comment]
Cigarette packs can contain 21 cigarettes.  It just takes some doing.
