### ISSUE TITLE
allow blindfolds to be made from makeshift bandages

### ISSUE THREAD

**Issue by shadowsapex** [CleverRaven/Cataclysm-DDA#48787]
# Is your feature request related to a problem? Please describe.
without duct tape the quickest way to make a blindfold from scratch is 45 minutes for a bandana? like what it's just a blindfold

# Describe the solution you'd like
I don't see how there could be any difference between wrapping bandages around your eyes and wrapping makeshift bandages around your eyes. judging from the recipe the only difference between the two is bandages are adhesive and medicated so maybe bandages shouldn't be in the recipe in the first place in favor of makeshift bandages

# Describe alternatives you've considered
none

# Additional context
thanks

**Comment by KittyTac** [comment]
Also just rags and string maybe (tying rags around your eyes).
