### ISSUE TITLE
There should be an 1-z-level deep soil layer

### ISSUE THREAD

**Issue by KittyTac** [CleverRaven/Cataclysm-DDA#48792]
# Is your feature request related to a problem? Please describe.
This always kind of struck me as odd that you can't dig "under" the soil in-game, only deep pits. From what I have read (there seems to be little information on this, or I am looking in the wrong places), the soil layer in New England is several-meters-thick.

# Describe the solution you'd like
Add a single level of "solid soil" underground before you hit rock. You could reach it with the "dig staircase" construction or by digging down in a deep pit, Note that the latter will create a slope without supports that you'd have to reinforce to prevent a cave-in. Then you could dig through the soil tiles with just digging 2, creating tunnels.

Speaking of cave-ins, they should occassionally occur in dirt tunnels, with a larger chance the more time passes. A cave-in will create rubble (possibly a new type) on a tile, heavily damage anything on the tile, and possibly increase the chances of further cave-ins. You could prevent this by adding supports with the construction menu (planks or stout branches or rebar, possibly nails also),

# Describe alternatives you've considered
Not adding this I guess.

# Additional context
[Soil depth map](https://agupubs.onlinelibrary.wiley.com/cms/asset/727a055b-0fc1-4202-b410-610ee67cd3e5/jame20243-fig-0014-m.jpg)

**Comment by ZhilkinSerg** [comment]
One z-level is already several meters high.

**Comment by KittyTac** [comment]
> One z-level is already several meters high.

Yes and according to the map the soil in New England (unless I completely fail geography) in most places around... 5 meters? Should be enough for one level.

**Comment by Igryn** [comment]
Nice idea, it would also make dug-out shelters more of a viable option.
![guns](https://user-images.githubusercontent.com/51831130/117554696-e679f280-b061-11eb-9b96-67ac6220ad59.jpg)

**Comment by Headjack** [comment]
There's an issue where destroying/deconstructing most wall tiles leaves behind either a solid stone floor or a concrete floor(which itself is mined away into a solid stone floor). This makes it impossible to put down shallow pits and then rebuild any other wall. Would this change address this?

**Comment by Inglonias** [comment]
Fixed by #49658
