### ISSUE TITLE
Lighting a torch from an open fire destroys the torch

### ISSUE THREAD

**Issue by KittyTac** [CleverRaven/Cataclysm-DDA#48791]
# Describe the bug

If you light a torch from a brazier or the like then the torch disappears.

# Steps To Reproduce

1. Light a fire in a brazier.
2. Make sure you have no lighter/matches in your inventory.
3. Spawn in a torch.
4. Try to light the torch from the fire.

# Expected behavior

You don't accidentally throw the torch into the fire.

# Screenshots

Not needed.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-10389-g4a67b7c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Kittymod [kittymod],
    Tankmod: Revived [Tankmod_Revived],
    Tankmod: Revived - UndeadPeople Tileset [Tankmod_RevivedUDP]
]
Kittymod is my personal mod, doesn't alter torches so it shouldn't affect this.

# Additional context

Maybe also fire drills should be allowed to light torches.

**Comment by Salty-Panda** [comment]
![image](https://user-images.githubusercontent.com/26396019/117533231-fb1ba380-afeb-11eb-82d3-aac207af1a07.png)
Torch be lit safely by using `a`ctivation.
I assume you threw it into the brazier.

Version: b7b8f77a87333682516f092feee4d3dcf5d211a8 03.05.2021

**Comment by KittyTac** [comment]
> ![image](https://user-images.githubusercontent.com/26396019/117533231-fb1ba380-afeb-11eb-82d3-aac207af1a07.png)
> Torch can be lit safely by using `a`ctivation.
> I assume you threw it into the brazier.
> 
> Version: [b7b8f77](https://github.com/CleverRaven/Cataclysm-DDA/commit/b7b8f77a87333682516f092feee4d3dcf5d211a8) 03.05.2021

Are you sure you don't have a lighter on you?
