### ISSUE TITLE
ASCII for vehicles is bugged

### ISSUE THREAD

**Issue by Miloch** [CleverRaven/Cataclysm-DDA#48799]
ASCII art for vehicles in game is displaying capital letters for parts that were something totally different before.  Doors are now what used to be corner pieces which point in different directions.
-Doors are replaced with corners MOST of the time.
-Boards, windshields, and some quarter panels are replaced with capital letters.

A link to the forums.  At least one other person reported this issue.
https://discourse.cataclysmdda.org/t/ascii-vehicle-are-displaying-capital-letters/24809/9

# Steps To Reproduce

1. Start a game.
2. Look at a vehicle.

# Expected behavior

# Screenshots

![CDDA-Vehicle](https://user-images.githubusercontent.com/4497993/117552545-9c692080-b011-11eb-9bc5-305f816f10a8.PNG)
![CDDA-VehicleA](https://user-images.githubusercontent.com/4497993/117552550-9ffca780-b011-11eb-80ec-f911abf60773.PNG)

Do not take a screenshot of the crashing window. Please provide the crash logs in the "Additional context" -->

# Versions and configuration

- OS: Windows 10
    - OS Version: 10.0 2004
- Game Version: 07c58d9 [64-bit]
- Graphics Version: Terminal
- Game Language: English
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]
]

# Additional context

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/ascii-vehicle-are-displaying-capital-letters/24809/10
