### ISSUE TITLE
NPC's ignores "No NPC pickup" Zones completely

### ISSUE THREAD

**Issue by Vasil-Dimitrov** [CleverRaven/Cataclysm-DDA#48800]
# Describe the bug
Right after completing the quest "Find Inhaler" the NPC went in the nearby pile and took all books them being under "No NPC pickup" zone.

This issue could be connected with [#21290](https://github.com/CleverRaven/Cataclysm-DDA/issues/21290) although I am not sure since there only the fuel pickup is mentioned.

**EDIT 1:**
After retrieving the items and placing them on the floor then auto sorting the NPC picks some of them up again. This isn't a one time thing only after finishing a quest.

**EDIT 2:**
This isn't only limited to books. NPC seems to completely ignore the zone and picks up items like books and wearable clothes until there's no more free weight or volume left in their inventory (mine is even at -8.4 kg right now). This possibly extends to other items than books and wearables but this is what I've observed so far.

**EDIT 3:**
Can no longer retrieve my items from NPC via trading since no matter how many items I request to take the NPC still stays with a negative carry weight in the inventory and the trade cannot be accomplished. I have attached a screenshot of this as well.

# Steps To Reproduce

1. Have quest "Find Inhaler"
2. Place books close to the NPC with the above mentioned quest
3. Cover books with "No NPC pickup" zone
3. Talk to NPC and finish quest
4. Ask to be taught a skill as compensation
5. After finishing NPC will have went and stolen all books

# Expected behavior

# Screenshots
**Log screenshot:**
![image](https://user-images.githubusercontent.com/26870349/117552419-ce9b7200-b053-11eb-8093-2d70a9f0c66d.png)

**All books were on the area corresponding to the "7" key move and now it's empty:**
![image](https://user-images.githubusercontent.com/26870349/117552431-e07d1500-b053-11eb-9693-0a8a775e40ae.png)

**"No NPC pickup" zone on both ends of priority - active and covering all items:** 
![image](https://user-images.githubusercontent.com/26870349/117552438-f2f74e80-b053-11eb-974f-c2f5f169a7c4.png)
![image](https://user-images.githubusercontent.com/26870349/117552441-f7bc0280-b053-11eb-8d6c-54544e7ab6ea.png)

**All books appear in the NPC's inventory:**
![image](https://user-images.githubusercontent.com/26870349/117552479-3f428e80-b054-11eb-8915-cf5b10f34acf.png)

**EDIT 3 SCREENSHOT showing retrieval of items is no longer possible:**
![image](https://user-images.githubusercontent.com/26870349/117553292-6bacd980-b059-11eb-9554-9967c88383d2.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 07c58d9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Tiles: [UndeadPeopleTileset](https://github.com/SomeDeadGuy/UndeadPeopleTileset) latest master as of 2021-05-08 (last commit f6852a2)
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Mythical Martial Arts [MMA],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    No Fungal Monsters [No_Fungi],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

**Comment by Vasil-Dimitrov** [comment]
Additional: After retrieving the items and placing them on the floor then auto sorting the NPC picks some of them up again. This isn't a one time thing only after finishing a quest.

**Comment by Vasil-Dimitrov** [comment]
After force closing the game hoping the final NPC item pickup didn't save I got a ton of errors on start up so I checked the logs and I noticed errors were also logged before I force closed the game while trying to trade my items back so I am uploading my logs as well, hopefully this gives enough description to ease the work of whomever decides to look at this case.

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6446573/debug.log)

**Comment by I-am-Erk** [comment]
Duplicates #21290
