### ISSUE TITLE
minor typo in top level menu help text

### ISSUE THREAD

**Issue by aaevan** [CleverRaven/Cataclysm-DDA#48803]
# Describe the bug

In the starting menu under Help, section "Hunger, thirst and sleep", in the last sentence of the second paragraph, replace "then" with "than".

"Thirst will kill you faster then hunger" --> "Thirst will kill you faster than hunger"

# Steps To Reproduce

From the top level menu of cataclysm-tiles, select the [Help] menu option, then press 'd' for "Hunger, thirst and sleep". Look at the last sentence of the second paragraph.

# Expected behavior
N/A

# Screenshots
N/A

# Versions and configuration

linux 64 release cataclysmdda-0.E

# Additional context

I wasn't sure where to look in the vast file tree to fix this so I opened an issue instead.

**Comment by ToxiClay** [comment]
Contributors do their best now, and are preparing. Please watch warmly until it is ready.

Also, the file you want is `\data\help\texts.json` for future reference. I recommend installing Notepad++; its "find in files" feature is tremendously helpful.

**Comment by aaevan** [comment]
Okay, great! Thanks for the info!

**Comment by anothersimulacrum** [comment]
Didn't get closed by #48807 for some reason.
