### ISSUE TITLE
[Magiclysm] Will-o-wisps and Animated Blades are almost useless against feral humans' godlike rock throwing ability, especially if up against a pack of feral humans at once.

### ISSUE THREAD

**Issue by ifffrt** [CleverRaven/Cataclysm-DDA#48810]
# Describe the bug

Feral humans are just way too gosh-darn accurate with their rocks. A group of 3 Will-o-wisps can be dispatched with within 10 turns by a group of about 3-5 feral humans, which is a common occurrence inside parks. A group of 2 Animated Blades can be dispatched with even more easily, which makes them almost useless in such situations if you have no way to dealing with the feral humans individually.

Related to https://github.com/CleverRaven/Cataclysm-DDA/issues/42531.
# Steps To Reproduce

1. Go to a park where a lot of ferals are spawned.
2. Cast Ignus Fatuus and Animated Blade.
3. Watch your conjured monsters all get slaughtered.

# Expected behavior

Animated Blades and Will-o-wisps should not be so easy to hit with rocks (and bullets). And they should also not be so vulnerable to rock throwing damage. 

# Screenshots

# Versions and configuration

    OS: Windows
        OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
    Game Version: 0.E-10342-g8286e1d [64-bit]
    Graphics Version: Tiles
    Game Language: English [en]
    Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key],
    Graphical Overmap [Graphical_Overmap],
    sees-player icon, retrodays [sees_player_retro],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    Mythical Martial Arts [MMA],
    More Survivor Stuff [more_survivor_stuff],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    No Fungal Monsters [No_Fungi]
    ]

# Additional context

**Comment by ifffrt** [comment]
From the JSON the Animated Blade only has 2 armor for cut, bash and bullet damage. And Will-o-wisps have none. I propose giving buffing those numbers, since Animated Blades are supposed to be longswords made of steels, and Will-o-wisps are balls of vapor so should at least be much more resistant to bullets than they are now.

**Comment by Paperbell** [comment]
I feel like feral human rocks are harder to dodge than they should be. If will-o-wisps with 9 dodge and HARDTOSHOOT can't dodge the rocks, you might as well see them as a bullet with less damage. They should be something you can at least occasionally dodge if you are lucky.

I looked in ranged.cpp and found that there were only 2 mentions of projectile speed, one for throwing by the player, which set speed to 10 + throwing skill, and another for guns which set speed to 1000. The feral humans monstergun is a gun, so it fires projectiles moving at the same speed as an actual gun.

I tested with a dodge skill of ~1000, which would allow me to sometimes dodge gun bullets, and the rocks still hit me. Maybe there could be a way to set speed of a projectile in json?
![rockdebug](https://user-images.githubusercontent.com/66850460/117579702-afcfc680-b0b9-11eb-9078-b387c3916cb5.png)

**Comment by ifffrt** [comment]
> 
> 
> There is a ready PR (#48596) which should resolve the ferals' throwing issues.

There's still the HP issue with the Animated Blades and Will-o-wisps. Currently they still feel a tad unrealistic.

Just as a side note, how do you update the game from Github Action? Do you just unzip the file and then drag and drop? Would that reset Graphical Overmap?

**Comment by anothersimulacrum** [comment]
> > There is a ready PR (#48596) which should resolve the ferals' throwing issues.
> 
> There's still the HP (Edit: By HP I meant armor) issue with the Animated Blades and Will-o-wisps. Currently they still feel a tad unrealistic.
> 
> Just as a side note, how do you update the game from Github Action? Do you just unzip the file and then drag and drop? Would that reset Graphical Overmap?

@ifffrt Download and unzip the new release, then copy over your `save/` and `config/` directories to the newly unzipped release.
