### ISSUE TITLE
Same tile ids with different tile size in tile_config.json cause problems with rendering

### ISSUE THREAD

**Issue by olanti-p** [CleverRaven/Cataclysm-DDA#48819]
# Describe the bug
Same tile ids with different tile size in tile_config.json cause problems with rendering.
As an example, ChestHole16 tileset which defines trees first as 16x16 tiles, then again as 32x40 tiles.

# Steps To Reproduce
1. Switch to ChestHole16
2. Enter a forest

![image](https://user-images.githubusercontent.com/60584843/117685848-fb1fcd00-b1be-11eb-85fd-28a8e33b166f.png)

# Expected behavior
The game either produces debug message on load, or overwrites such tiles in consistent manner.

In case of ChestHole16, one of the options of how trees should look is:
![image](https://user-images.githubusercontent.com/60584843/117686491-9749d400-b1bf-11eb-83f6-022c6f7de061.png)
This screenshot was done after I removed 16x16 `t_tree_maple*` definitions from `gfx/ChestHole16Tileset/tile_config.json`. 

# Versions and configuration
272a1d4 (Experimental build 18)

**Comment by olanti-p** [comment]
> I've had this problem a lot with Chibi Ultica and a little bit initially with MSX

As this is a recurring problem (and one that may be affecting other tilesets in this repo right now), some kind of automated solution could be useful (edited in in "Expected behavior").

**Comment by Fris0uman** [comment]
right so chosing the biggest prite by default and maybe reporting an error could be nice. No idea how feasable it is though.

**Comment by olanti-p** [comment]
This may have same root cause as #45563, as sprites with same ID no longer get overwritten after #44917:
https://github.com/CleverRaven/Cataclysm-DDA/pull/44917/files#diff-c8561880131eb6314d85f58032f9063284bcfc226b75b3b5df585dcaa219605cL238-R257

**Comment by Fris0uman** [comment]
#51080 Probably fixed this

**Comment by anothersimulacrum** [comment]
Will close until a report there is an issue.
