### ISSUE TITLE
Add tire armor

### ISSUE THREAD

**Issue by Igryn** [CleverRaven/Cataclysm-DDA#48820]
# Describe the solution you'd like
Add suit of armor made out of tires, similarly to scparsuit made of bike and/or car tires.

# Additional context
As it is a staple of postapocalyptic genre it would feel appropriate. As it is nor possible to disassemble tires for the moment it could produce scrapmetal or metal chunks as a sideproduct, also it would be posible to justify using thinner rubber comprising the pressurised chamber as string of rubber tiyng it al together
![76c0cff70371a7392180192b01ac52b8](https://user-images.githubusercontent.com/51831130/117708006-f3b8ed80-b1d7-11eb-9b0b-67a87c996d3a.jpg)
![o85r77fvdar41](https://user-images.githubusercontent.com/51831130/117708009-f4ea1a80-b1d7-11eb-8bc9-5bfe77081f7c.jpg)

**Comment by RoyBerube** [comment]
Good idea. And is probably doable entirely in json.

**Comment by Igryn** [comment]
> A new material `vulcanized rubber`, to be used in tires.
> Would be somewhat better scrap armor I guess, sort of interesting idea

Tires just use **plastic** as a material, we could weather change tires to **vulcanised rubber** also or just use **plastic** as a material in new armor

**Comment by Aiden-Koorsen** [comment]
Can't you just maybe be able to break down tires and then get a certain material to make it out off and then just have another material to wind it together?
