### ISSUE TITLE
Allow soapy water to be used to clean wounds

### ISSUE THREAD

**Issue by Igryn** [CleverRaven/Cataclysm-DDA#48826]
# Is your feature request related to a problem? Please describe.
Only way to treat wound is cutterising which is not ideal, also propper healing does require disinfecting even if it doesnt have deep wounds, at the moment cleaning yourself for proper healing only involves rubbing antiseptics, it also would emulate maintaining hygiene without adding it as a mechanic and a obligatory chore as you would only do it when damaged.

# Describe the solution you'd like
Ability to use soapy water as less effective antiseptic

# Describe alternatives you've considered
Drink soapy water

# Additional context
Historically soap drastically improved survival rates in hospitals when staff started to use it on equipment and patients

**Comment by robotic-gamer** [comment]
In general there are a lot of things that could be used as antiseptics that currently aren't. a relevant discussion on this #48418

**Comment by Inglonias** [comment]
I suggested this long ago with #25558 and didn't really get anywhere then.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
