### ISSUE TITLE
Inside of closed vehicle should not be accessible to zombies

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#48822]
# Is your feature request related to a problem? Please describe.
Zombies can enter a perfectly closed vehicle as soon as it is not in a strict NS/EW direction. 

# Describe the solution you'd like
Zombies shoud not be able to enter closed vehicles just because of the orientation of the vehicle. Check if moving to a vehicle square is legit should be done by checking if the move is possible with a "examine vehicle" type of view (ie NS), not with the map view.

# Describe alternatives you've considered
None

**Comment by Igryn** [comment]
Ah yes, this again. I propose making diagonal vehicle walls impassable at all, thik how such diagonal wall would work in minecraft, any fps game or real life for that matter. Of all that i have seen this causes the least amount of side effects.
![guns](https://user-images.githubusercontent.com/51831130/117732454-984b2780-b1f8-11eb-92fe-fb07094183fa.jpg)

**Comment by matt32106** [comment]
hola a mi&go! :)

**Comment by matt32106** [comment]
This would need to be true only to vehicles because it would break some labs if this was enforced everywhere.

**Comment by Igryn** [comment]
I think only applying it to vehicles is the way to go, that way it won't be needed to revise most of buildings mapgen.

**Comment by GGgatherer** [comment]
That would only band-aid the problem with hitchhikers. There would still be at least visibility issue - for example, turrets can shoot you while you're in "closed" vehicle.

**Comment by Salty-Panda** [comment]
This subject was talked upon many times.
Issue is duplicate and PR fixing it (a third iteration of the fix) was made by mlangsdorf and awaits next experimentals: #42462
