### ISSUE TITLE
cooked meat has 10 times too much B12

### ISSUE THREAD

**Issue by danielkwinsor** [CleverRaven/Cataclysm-DDA#48828]
# Describe the bug
1 piece of cooked meat has 778%  this is expected to be 77.8% or so, based on rough estimations from USDA.  2.4 micrograms needed per day, 100grams meat has ~.6 micrograms

# Steps To Reproduce

# Expected behavior

# Screenshots

# Versions and configuration

# Additional context

**Comment by danielkwinsor** [comment]
Also, 100 grams of meat has 6% iron, and 1 cooked meat is 3x 100 grams.
Vitamin C should also be ~0.
I feel like probably all of the stats could use a double check.

**Comment by Jasper-Hawks** [comment]
Mutant meat also has a Vitamin B of 389. Though I do not know if mutation affects the amount of Vitamin B12 in meat.

**Comment by merrygin** [comment]
I suspect the former contributor just made mutant varieties at 50% of the normal, so the wrong value got dragged on. Made a PR to fix this just now. 
Its a bigger issue though what values to use, since reallife meats have very varying vitamin values. I used pork as default in the PR now.
