### ISSUE TITLE
Seg fault

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#48821]
# Describe the bug
Seg fault
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 0.E-10395-g4525b4f
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

    ./cataclysm-tiles(debug_write_backtrace(std::ostream&)+0x49) [0xc365b3]
    ./cataclysm-tiles() [0xc1e7b8]
    ./cataclysm-tiles() [0xc1e93a]
    /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7fd24967c210]
    ./cataclysm-tiles(Character::find_firestarter_with_charges(int) const+0xb0) [0xb51f7a]
    ./cataclysm-tiles(Character::has_fire(int) const+0x50) [0xb52aca]
    ./cataclysm-tiles(Character::has_charges(string_id<itype> const&, int, std::function<bool (item const&)> const&) const+0x9c) [0xb52bf8]
    ./cataclysm-tiles(Character::use_charges_if_avail(string_id<itype> const&, int)+0x4f) [0xb7fbe3]
    ./cataclysm-tiles(iuse_transform::use(player&, item&, bool, tripoint const&) const+0x202) [0xef0354]
    ./cataclysm-tiles(use_function::call(player&, item&, bool, tripoint const&) const+0x25) [0xe947c9]
    ./cataclysm-tiles(itype::invoke(player&, item&, tripoint const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const+0x10e) [0xe92d2e]
    ./cataclysm-tiles(Character::invoke_item(item*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, tripoint const&, int)+0x1c8) [0xb8031c]
    ./cataclysm-tiles(avatar::invoke_item(item*, tripoint const&, int)+0x8b) [0xacb39f]
    ./cataclysm-tiles(player::use(item_location, int)+0x3cb) [0x125d607]
    ./cataclysm-tiles(avatar_action::use_item(avatar&, item_location&)+0x38d) [0xadaf7e]
    ./cataclysm-tiles(avatar_action::use_item(avatar&)+0x2f) [0xadb015]
    ./cataclysm-tiles(game::handle_action()+0x2c9c) [0xd78f1e]
    ./cataclysm-tiles(game::do_turn()+0x4e9) [0xd27179]
    ./cataclysm-tiles(main+0x1336) [0x93c05c]
    /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7fd24965d0b3]

    Attempting to repeat stack trace using debug symbols…
    debug_write_backtrace(std::ostream&)
    ??:?
    log_crash
    crash.cpp:?
    signal_handler
    crash.cpp:?
    ??
    ??:0
    Character::find_firestarter_with_charges(int) const
    ??:?
    Character::has_fire(int) const
    ??:?
    Character::has_charges(string_id<itype> const&, int, std::function<bool (item const&)> const&) const
    ??:?
    Character::use_charges_if_avail(string_id<itype> const&, int)
    ??:?
    iuse_transform::use(player&, item&, bool, tripoint const&) const
    ??:?
    use_function::call(player&, item&, bool, tripoint const&) const
    ??:?
    itype::invoke(player&, item&, tripoint const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const
    ??:?
    Character::invoke_item(item*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, tripoint const&, int)
    ??:?
    avatar::invoke_item(item*, tripoint const&, int)
    ??:?
    player::use(item_location, int)
    ??:?
    avatar_action::use_item(avatar&, item_location&)
    ??:?
    avatar_action::use_item(avatar&)
    ??:?
    game::handle_action()
    ??:?
    game::do_turn()
    ??:?
    main
    ??:?
    __libc_start_main
    /build/glibc-YbNSs7/glibc-2.31/csu/../csu/libc-start.c:342

# Steps To Reproduce
Unknown

# Expected behavior
No seg fault

# Screenshots
No

# Versions and configuration
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6454889/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6454890/debug.log)

**Comment by RoyBerube** [comment]
It would help us to know the item being activated and the types of firestarters available.

**Comment by matt32106** [comment]
Sorry, I don't know. When I tried to do more or less the same thing, the crash did not happen again. This is why I think keystrokes should be saved alongside the savegame (with the seed used for the rng)  so that this kind of bug can be reproduced in 100%  of cases. I made this feature request a long time ago but it was dismissed at the time.
