### ISSUE TITLE
Possible balance issue with Fused Dragonflies

### ISSUE THREAD

**Issue by GreatLurdo** [CleverRaven/Cataclysm-DDA#48838]
# Describe the bug

The **fused dragonflies** monster currently has 1100 HP, making it fatally dangerous (learned it the hard way when it trashed my car and checked in the CDDA Item Browser, see screenshot).
I don't know if this is intentional, but perhaps it was just a typo. Otherwise, it became one of the most fearful monsters in the game, even compared to hulks.
In fact the huge/giant dragonflies have only 50 HP, and the monster description claims it is the amalgamation of two of them (even taking into account the binding energy...).

# Steps To Reproduce

1. Go to a swamp and find a **fused dragonflies** monster.
2. Have fun.

# Expected behavior

Don't know. Perhaps 110 HP?

# Screenshots
![imagen](https://user-images.githubusercontent.com/66877699/117863570-33450f80-b294-11eb-9c19-7993f7e11921.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-10395-g4525b4f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

[I'm not really sure this is a bug]
[I'm not really sure this is the correct place to mention this]

**Comment by GreatLurdo** [comment]
I'm aware this should be easy to do. Unfortunately, even as I try to help by reporting this, I'm not sure of how to do it. I will be glad to if I knew where the Jsons are and how to do a PR. Truly sorry.

**Comment by Saicchi** [comment]
In their original implementation in #44203, `mon_dragonfly_mega` was using `copy_from` with proportional 20x the HP and 0.25x the speed of a giant dragonfly. It seems they were changed to fixed values and it's name became `fused dragonflies`, keeping the increased HP but not reducing the speed.

**Comment by GreatLurdo** [comment]
Just a couple of comments: 
1) I've been playing experimental for a long time, although I recognize I'm no expert in the game. That being said, hulks have 480 HP and, in terms of monsters, from what I see the only ones that get close to 1000 HP are (magiclysm) dragons and dinosaurs from the corresponding mod. Even as I understand you have done this for challenge purposes, merging two 50 HP dragonflies into one 1100 HP monster kind of takes me out of the game. Perhaps you should change the drescription to dozens of dragonflies fused?
2) I've encountered fused dragonflies **a lot**. In my last 3 games, y found one over a lake, a month or two from start, fatally dangerous, dead (me). Then second game on a swamp, and the third game I tried to smashed with my car (1100HP, car destroyed, fatally dangerous). There were 2 of them. What I mean is that for being an uber monster, perhaps it is bad luck, but it seems too common.

**Comment by SariusSkelrets** [comment]
> I'm aware this should be easy to do. Unfortunately, even as I try to help by reporting this, I'm not sure of how to do it. I will be glad to if I knew where the Jsons are and how to do a PR. Truly sorry.

In the game’s file, you go in data, then you open the Json file. If you can open a txt document, you can edit Json

**Comment by GreatLurdo** [comment]
> 
> 
> > I'm aware this should be easy to do. Unfortunately, even as I try to help by reporting this, I'm not sure of how to do it. I will be glad to if I knew where the Jsons are and how to do a PR. Truly sorry.
> 
> In the game’s file, you go in data, then you open the Json file. If you can open a txt document, you can edit Json

Many thanks for the information. I will try it (then what should I do with the modified Json?)
Also, it seems that the creator of the monster have a view on the matter different from my own. I'm not sure of the policy here, and don't want to step on anybody.

**Comment by Venera3** [comment]
They spawn from around month five naturally and grow up from giant dragonflies on a 40-day timer, making the earliest encouter a month or two ingame. They can also be outpaced on even ground by walking in the opposite direction, or drawn into other mobs to distract them. Them swimming quickly is a bit of an oversight, so that flag could be removed.

Hulks are in a *bad* place in the current balance, being way too squishy for when they appear and not being able to outkill a survivor unless they get a lucky throw into a concrete wall or something like that, so they are a bit of a bad reference. Given the state of the game at the moment it helps to think of monster hp in terms of "can I shoot it to death with an M4 before it kills me?", which is eminently true for both (fused dragonflies take about a mag of 5,56 ignoring bleeding, and are slow enough to let you plink them down on the way).

**Comment by GreatLurdo** [comment]
I see your, point. In fact, if this is going to be changed, I will leave it for some one more senior in game balance issues than me. 

However, and even accepting all your points about balance, it still strikes me as weird that such a huge monster (and I say that because I understand that HP level is related to things like destroying you van in a collision) is described as just 2 giant dragonflies. I will suggest just a modification of  the description so that a character is not deceived and ends up thinking that, as you crush a giant/huge dragonfly with your car, you can do the same with two (and get the middle finger).

**Comment by GreatLurdo** [comment]
> 
> 
> In their original implementation in #44203, `mon_dragonfly_mega` was using `copy_from` with proportional 20x the HP and 0.25x the speed of a giant dragonfly. It seems they were changed to fixed values and it's name became `fused dragonflies`, keeping the increased HP but not reducing the speed.
> This change happend in #44779 if you want to give it a read.

Sorry did not see this. Thank you for the info. And to Venera3 for the inter**fun**esting contribution.
Cound be than in crazy CDDA world, dragonflies mate by the dozens?

**Comment by Venera3** [comment]
The thought was dragonflies that stuck together didn't need to stay flying so they could bulk up, but I agree their chonkiness isn't emphasised by their description properly. I'll keep this in mind for whenever I swing back around to them in the future.

**Comment by BaumgeistOne** [comment]
A huge enemy with more than double the health of a hulk I can deal with. Small Enemies multiplying too.

Huge enemies which multiply I do not like at all. I am in Autumn, day 48, and the rivers are full of these. Often a whole swarm of them approaches while I am just trying to use the street along the river.

Worst of all, when I do enough damage to them, they retreat, often over the water, and thus stay alive for more multiplying.

I've started using the debug menu to kill them off, because frankly those enemies are getting ridiculous.

**Comment by Venera3** [comment]
That's a separate issue (they don't multiply, as such). There has been some work going on with how monster groups are set up, and I've gotten a few reporst of the rivers teeming with naiads - those growing up lines up with your timeline there. I'll try to look into in the near future.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
