### ISSUE TITLE
Dazed by razorclaw scream while having Deaf mutation

### ISSUE THREAD

**Issue by OldFriendEr** [CleverRaven/Cataclysm-DDA#48835]
# Describe the bug

I'm a plant mutant, with a deaf mutation, was shooting some razorclaws 9 away and got dazed by the scream. ("The scream dazes you!")

# Steps To Reproduce

1. Debug a Deaf trait,
2. Spawn some Razorclaws and ~make them scream~ wait for them to scream

# Expected behavior

Expect a deaf character to be immune to scream based attacks. Or just modify the message so its more about a shockwave than the sound. I think “dazed by the shockwave” would spark less confusion

# Screenshots

![Untitled](https://user-images.githubusercontent.com/17822510/117859825-2aeed380-b298-11eb-8a86-e6eff52e8a60.png)

# Versions and configuration

 OS: Windows 10
 Game Version: 07c58d9 (experimental build 11582)
 Graphics version: Tiles 
 Ingame language: English
Mods loaded: dda, no_npc_food, package_bionic_professions

# Additional context

**Comment by Saicchi** [comment]
In `Character::is_immune_effect` I think it's missing `has_flag( json_flag_DEAF )`. Since the `DEAF` trait already gives the `DEAF` flag.
```c++
} else if( eff == effect_deaf ) {
        return worn_with_flag( flag_DEAF ) || worn_with_flag( flag_PARTIAL_DEAF ) ||
               has_flag( json_flag_IMMUNE_HEARING_DAMAGE ) ||
               is_wearing( itype_rm13_armor_on );
}
```

**Comment by OldFriendEr** [comment]
just pulled the source and tested the issue again, without any modifications and then with your suggestion. Everything worked as you have suggested, making a PR
