### ISSUE TITLE
Deconstrucion of privacy fence yields door hinges

### ISSUE THREAD

**Issue by GreatLurdo** [CleverRaven/Cataclysm-DDA#48837]
# Describe the bug

Deconstructing a privacy fence yields 2 door hinges, even if none is required to build it.

# Steps To Reproduce

1. Construct a privacy fence (no door hinges are used)
2. Deconstruct it (you get 2 door hinges)

# Expected behavior

The **privacy fence gate** should yield 2 hinges (as they are used for its construction), but not the **privacy fence**. 

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-10395-g4525b4f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

**Comment by Saicchi** [comment]
Can confirm.
Privacy Fence Components: `[ [ [ "pointy_stick", 2 ], [ "spear_wood", 2 ] ], [ [ "2x4", 8 ] ], [ [ "nail", 20 ] ] ]`
Deconstruction Components: `[ { "item": "2x4", "count": 10 }, { "item": "nail", "charges": 20 }, { "item": "hinge", "count": [ 1, 2 ] } ]`
