### ISSUE TITLE
Large Talons mutation should allow fingerless gloves

### ISSUE THREAD

**Issue by KittyTac** [CleverRaven/Cataclysm-DDA#48832]
# Is your feature request related to a problem? Please describe.
This is a followup to my "leg guards and knee pads should allow tails" issue (which got implemented). Logically, talons on fingers should fit though the finger holes.

# Describe the solution you'd like
Add `"allowed_items": [ "ALLOWS_TALONS" ]` to `TALONS` and `"flags": [ "ALLOWS_TALONS" ]` to `gloves_fingerless`, `gloves_fingerless_mod`, `gloves_survivor_fingerless`, and `gauntlets_larmor`.

# Describe alternatives you've considered
None.

# Additional context
Not necessary.

**Comment by ActualDio** [comment]
Should it also let you use "gauntlets_larmor"? The description says "Heavy fingerless leather gloves.  Very flexible and comfortable." so Im wondering if its appropriate

**Comment by ActualDio** [comment]
Should "gloves_wraps" be included in there? Its supposed to just be fabric wrapped around your hand, the tallons shouldt interfere with that.
