### ISSUE TITLE
Crash when filtering in pickup menu

### ISSUE THREAD

**Issue by andrei8l** [CleverRaven/Cataclysm-DDA#48858]
Filtering the pickup menu for an item that does not exist crashes the game

# Steps To Reproduce

1. Open pickup menu (default key `g`)
2. Filter for an item that does not exist (ex: `blorg`) (default key `\`)
3. crash

# Expected behavior

No crash

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.E-10536-g3d0463f8bd [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context
[asan.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6474011/asan.log)
It might not crash without ASan/UBsan

Quick and dirty patch:
```diff
diff --git a/src/pickup.cpp b/src/pickup.cpp
index f283ceb1cc..9f5103d405 100644
--- a/src/pickup.cpp
+++ b/src/pickup.cpp
@@ -679,9 +679,8 @@ void Pickup::pick_up( const tripoint &p, int min, from_where get_items_from )
         const std::string all_pickup_chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ:;";
 
         ui.on_redraw( [&]( const ui_adaptor & ) {
-            const item &selected_item = *stacked_here[matches[selected]].front();
-
-            if( selected >= 0 && selected <= static_cast<int>( stacked_here.size() ) - 1 ) {
+            if( !matches.empty() && selected >= 0 && selected <= static_cast<int>( stacked_here.size() ) - 1 ) {
+                const item &selected_item = *stacked_here[matches[selected]].front();
                 std::vector<iteminfo> vThisItem;
                 selected_item.info( true, vThisItem );
 
@@ -690,17 +689,15 @@ void Pickup::pick_up( const tripoint &p, int min, from_where get_items_from )
                 dummy.without_border = true;
 
                 draw_item_info( w_item_info, dummy );
+                // print info window title: < item name >
+                mvwprintw( w_item_info, point( 2, 0 ), "< " );
+                trim_and_print( w_item_info, point( 4, 0 ), pickupW - 8, selected_item.color_in_inventory(),
+                                selected_item.display_name() );
+                wprintw( w_item_info, " >" );
             } else {
                 werase( w_item_info );
-                wnoutrefresh( w_item_info );
             }
             draw_custom_border( w_item_info, 0 );
-
-            // print info window title: < item name >
-            mvwprintw( w_item_info, point( 2, 0 ), "< " );
-            trim_and_print( w_item_info, point( 4, 0 ), pickupW - 8, selected_item.color_in_inventory(),
-                            selected_item.display_name() );
-            wprintw( w_item_info, " >" );
             wnoutrefresh( w_item_info );
 
             const std::string pickup_chars = ctxt.get_available_single_char_hotkeys( all_pickup_chars );
```
(i.e. check that the list has items before dereferencing)

**Comment by Saicchi** [comment]
Can't reproduce on `0.E-10474-g1ae66c97a0 [64-bit]`.
Opening the pickup menu and searching for an item that does not exist in the pile or in the game returns a popup saying `Your filter returned no results.`, without crashing.

**Comment by andrei8l** [comment]
You need to build with ASan (`-fsanitize=address` or `-fsanitize=address,undefined`). I can't reproduce it reliably with the official builds either. Either way you can see the oversight in the code...

**Comment by Svatopluk1** [comment]
I've tested andrei8l's patch on top of the latest master. With the patch, I correctly get "Your filter returned no results" without crashing (without it, the game always crashes for me in the same situation).

Could you turn the above patch into a pull request?

**Comment by andrei8l** [comment]
Invalidated by https://github.com/CleverRaven/Cataclysm-DDA/pull/51033; closing.
