### ISSUE TITLE
Can't reload Hub 01 dazzle rifle with UPS

### ISSUE THREAD

**Issue by SariusSkelrets** [CleverRaven/Cataclysm-DDA#48851]
# Describe the bug
You can't reload the dazzle rifle with UPS, even if the description says it uses UPS charges

# Steps To Reproduce

1.  Accept iron safari mission from Hub 01
2. reload the UPS with the heavy battery
3. Try and fall to reload the rifle with the UPS

# Expected behavior

Being able to reload the rifle with the apparently intended ammo

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-9280-g9dde4db-dirty [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: 
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]

# Additional context

the game tells me that "don't have any    to reload the weapon"

**Comment by John-Candlebury** [comment]
You dont need to load the UPS into the rifle, you should be able to just fire with the UPS in your inventory.

**Comment by SariusSkelrets** [comment]
It works, but I expected the power source to be in the gun, not unplugged and in your backpack.

The gun's name includes the word empty, implying that you need to load it first
