### ISSUE TITLE
Krav Maga weaponry (Is a tanto a Krav weapon?)

### ISSUE THREAD

**Issue by 6maboc** [CleverRaven/Cataclysm-DDA#48854]
# Is your feature request related to a problem? Please describe.
As it currently stands, the tanto is not a valid Krav Maga weapon in default. Magiclysm also currently considers the Tanto+1 and Tanto+2 to be valid weapons.

# Describe the solution you'd like
This can probably be remedied with a simple .json edit. However, I suspect that the valid weapons list may need additional changes (or not).

# Describe alternatives you've considered
A more elegant solution (to me) would be to be enable white/blacklisting weapon groups through their flags, but I'm not sure if this is worth the effort to implement.

# Additional context
Krav Maga, as it is currently implemented, seems to accept: batons/tonfas, knives, handguns, and rifles.
This could easily be a PR, but I wanted to ask around if there were any other potential irregularities in the weapons lists for other martial arts or Krav Maga itself.

**Comment by ZhilkinSerg** [comment]
#33602
