### ISSUE TITLE
(Lettuce) vegetable sandwich has more calories than meat sandwich

### ISSUE THREAD

**Issue by GreatLurdo** [CleverRaven/Cataclysm-DDA#48862]
# Describe the bug

Crafting a vegetable sandwich (proved several ingredients), creates a sandwich with more calories than a meat sandwich (same).

# Steps To Reproduce

1. Get some vegetables (tested lettuce, sauerkraut and several other vegetable ingredients)
2. Get some meat (tested canned chicken, smoked meat, canned tuna and others)
3. Cook some flatbread
4. Make a vegetable sandwich. You get a sandwich with 900+ calories.
5. Make a meat sandwich. You get a sandwich with 600+ calories.

# Expected behavior

On equality of bread it should be: calories(chicken) > calories(lettuce) (depending on size, I guess, but see additional context).

# Screenshots
CDDA Lettuce vs Canned Chicken calories heavyweight championship (spoiler, letucce wins)
![imagen](https://user-images.githubusercontent.com/66877699/118190920-1b13f280-b444-11eb-9202-7649a971c662.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-10395-g4525b4f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

I thought at first that a lot of lettuces were used to craft the sandwich vs small amounts of meat, but the ingredients were:
1 lettuce = 4 cal vs 1 canned chicken = 400 cal
It is also possible I'm missing something obvious here.

**Comment by Saicchi** [comment]
The calories are divided between the charges. The meat sandwich recipe has two charges, with each charge having half the total calorie.

**Comment by GreatLurdo** [comment]
> 
> The calories are divided between the charges. The meat sandwich recipe has two charges, with each charge having half the total calorie.

Clearly, I was indeed missing something obvious here :) Sorry for the loss of time.
