### ISSUE TITLE
contents.has_pocket_type( item_pocket::pocket_type::MAGAZINE_WELL ) always returns true for guns

### ISSUE THREAD

**Issue by Hirmuolio** [CleverRaven/Cataclysm-DDA#48860]
# Describe the bug

`contents.has_pocket_type( item_pocket::pocket_type::MAGAZINE_WELL )` always returns true for guns

# Steps To Reproduce

Call `contents.has_pocket_type( item_pocket::pocket_type::MAGAZINE_WELL )` on gun that takes no ammo or magazines (UPS powered guns).

For example:
* Spawn fun that does not take ammo or magazines (UPS powered guns like "A7 laser rifle")
* Look at it in your inventory. The option to reload is enabled.

The reload option is enabled because  `item::is_reloadable()` returns true.
`item::is_reloadable()` returns true because `contents.has_pocket_type( item_pocket::pocket_type::MAGAZINE_WELL )` returns true. ( `is_magazine()` also returns true but for same reason).
The guns has no magazine wells or any other places where ammo could go so it can never be reloaded so `item::is_reloadable()` should return false.

# Expected behavior

Guns with no magazine wells should not be handled as if they had magazine wells.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-10395-g4525b4f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Dark Days of the Dead [classic_zombies],
    No Monsters [Only_Wildlife]
]

# Additional context

**Comment by mqrause** [comment]
`Item_factory::check_and_create_magazine_pockets` will assign a `MAGAZINE` pocket to any gun that doesn't define any pockets. This will cause `item::is_magazine` to be true, which should be the real cause of the issue you have. `item_contents::has_pocket_type` does correctly return false for `MAGAZINE_WELL` on the laser rifle.

**Comment by Hirmuolio** [comment]
Seems like some sort of workaround for some odd old styled magazines/guns/tools.

The only error that seems to come from removing that part is from "feral_human_thrown_rock" which has clip size but no magazine definition.

I don't know what the magazine part is for so I'll not touch it.

The tool part is probably for tools that contain battery charges without batteries.

It also seems like it would interact with the old magazine system instead of the new magazine pocket system in some way.
