### ISSUE TITLE
Tile-to-tile movement latency on new builds

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#48878]
On the new build infrastructure for CDDA, there is a slight, but perceptible increase in tile-to-tile move latency. This is most noticeable when holding down a movement key.

# Steps To Reproduce

Simply hold down a movement key in the old build, then the new build.

# Expected behavior

No latency difference.

# Versions and configuration

Old build: 0.E-10395-g4525b4f

New build: b4db094

# Additional context

Old Build:
https://user-images.githubusercontent.com/13796683/118339404-c9707400-b4e6-11eb-8ddc-f80ac120706b.mp4

New Build:
https://user-images.githubusercontent.com/13796683/118339420-d2614580-b4e6-11eb-9ea3-91accf45bc8d.mp4

**Comment by Saicchi** [comment]
Maybe the build flags changed with the github builds.

**Comment by ZhilkinSerg** [comment]
There is SDL version bumped in GHA builds which could've affect performance. Can you please test performance of different renderers and new batch rendering option?

**Comment by ToxiClay** [comment]
I can try downloading the latest GHA build, but I'm unable to build my own from source; whenever I try to build, I get even horribly worse latencies.

**Comment by isloat** [comment]
This happens in menus/options as well. It seems worst for 2-3 minutes after opening the program, and abates after that initial time period. Hold up or down while in menus and you'll see the problem immediately.

GIF of the above: https://gyazo.com/57bcde0f75f156ecf13696225f529986

**Comment by ZhilkinSerg** [comment]
What's your graphical settings?

**Comment by isloat** [comment]
> What's your graphical settings?

Whatever is the default -- which looks like windowed borderless, direct3D renderer, render batching allowed. I played around with changing stuff around and it looks like changing my renderer from direct3D to direct3D11 seems to have fixed the issue (after a restart of the program).
