### ISSUE TITLE
Unit test failure in 0.F-rc1 (roll_remainder_distribution)

### ISSUE THREAD

**Issue by reinerh** [CleverRaven/Cataclysm-DDA#48875]
# Describe the bug

While building cdda `experimental-15` (rc1) I noticed a unit test failure with a specific seed.

# Steps To Reproduce

Run tests with the following command:
```
$ ./tests/cata_test --min-duration 0.2 --rng-seed 1621001079 "~[slow] ~[.]"
```

# Expected behavior

All tests are passing

# Screenshots

```
$ ./tests/cata_test --min-duration 0.2 --rng-seed 1621001079 "~[slow] ~[.]"

16:50:46.132 INFO : Randomness seeded to: 1621001079
16:50:46.139 WARNING : opendir [./test_user_dir/sound/] failed with "No such file or directory".
16:50:46.139 WARNING : opendir [./test_user_dir/gfx/] failed with "No such file or directory".
16:50:46.140 INFO : [options] C locale set to C
16:50:46.140 INFO : [options] C++ locale set to C
16:50:46.151 WARNING : opendir [./test_user_dir/mods/] failed with "No such file or directory".
16:50:48.232 WARNING : opendir [./test_user_dir/save/Test World 1052061/mods] failed with "No such file or directory".
16:50:53.355 INFO : Starting the actual test at Fri May 14 16:50:53 2021
Filters: ~[slow] ~[.]
0.300 s: soldier zombie
0.300 s: effective vs actual damage per second
0.640 s: smoker zombie
0.641 s: effective vs actual damage per second
0.512 s: survivor zombie
0.513 s: effective vs actual damage per second
0.377 s: soldier zombie
0.378 s: accuracy increases success
0.644 s: smoker zombie
0.644 s: accuracy increases success
0.513 s: survivor zombie
0.514 s: accuracy increases success
0.260 s: acid_field_expiry_on_map
0.233 s: time to level
0.233 s: focus
0.564 s: tripoint_hash_distribution
0.253 s: line_to_boundaries
1.192 s: mx_minefield real spawn
0.328 s: map_bounds_checking
0.486 s: attacking on open ground
0.593 s: monster_attack
0.246 s: attack_up_stairs 2d
0.356 s: monster_attack
0.313 s: attack_up_stairs 3d
0.422 s: monster_attack
0.454 s: monster_speed_square
0.431 s: monster_speed_trig
0.854 s: reachability_horizontal
0.857 s: reachability_horizontal
0.858 s: reachability_horizontal
0.885 s: reachability_horizontal
0.869 s: reachability_horizontal
0.868 s: reachability_horizontal
0.869 s: reachability_horizontal
0.871 s: reachability_horizontal
0.858 s: reachability_vertical
0.865 s: reachability_vertical
0.858 s: reachability_vertical
0.857 s: reachability_vertical
0.860 s: reachability_vertical
0.858 s: reachability_vertical
0.860 s: reachability_vertical
0.866 s: reachability_vertical

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cata_test is a Catch v2.13.0 host application.
Run with -? for options

Randomness seeded to: 1621001079

-------------------------------------------------------------------------------
roll_remainder_distribution
-------------------------------------------------------------------------------
../tests/rng_test.cpp:22
...............................................................................

../tests/rng_test.cpp:19: FAILED:
  CHECK( stats.test_threshold( target_range ) )
with expansion:
  false
with messages:
  Goal: -1.75
  Result: -1.89344
  Samples: 122


16:51:20.921 WARNING : opendir [./test_user_dir/memorial/] failed with "No such file or directory".0.386 s:      When: the avatar runs the required distance
0.386 s:     Given: a new game
0.386 s: achievement_marathon
0.386 s: movement
0.386 s: achievements_tracker
0.312 s: hunger
0.235 s: string_ids_intern_test
0.271 s: test_player_vs_zombie_javelin_iron_athlete
0.286 s: basic_throwing_sanity_tests
0.341 s: test_player_kills_zombie_with_rock_basestats
0.356 s: player_kills_zombie_before_reach
0.469 s: unseal_and_spill
0.306 s: Heavy tasks - Digging Pits 12 hours
0.306 s: weary_assorted_tasks
0.516 s: Heavy tasks
0.517 s: weary_recovery
1.118 s: 1 day vehicle work
1.118 s: weary_recovery
0.914 s: Waiting 24 hours
0.914 s: weary_24h_tasks
0.716 s: Digging 24 hours
0.717 s: weary_24h_tasks
1.966 s: weather realism
===============================================================================
test cases:     653 |     652 passed | 1 failed
assertions: 3652236 | 3652235 passed | 1 failed
```

# Additional context

The failure has been found on a Debian build server. [build log](https://buildd.debian.org/status/fetch.php?pkg=cataclysm-dda&arch=s390x&ver=0.F%7Erc1-1&stamp=1621001157&raw=0)

**Comment by actual-nh** [comment]
Also happens (if the same seed is used) on Mac 10.12.6, Apple LLVM version 8.1.0 (clang-802.0.42), 0.E-10708-gfc3689cd6b.

**Comment by BrettDong** [comment]
The roll remainder algorithm and the testing statistics algorithm both look good to me. Tracing reveals that among 122 calls to `x_in_y(0.25, 1.0)`, 13 returned `true` and 109 returned `false`. I guess it's the linear congruential generator (`std::minstd_rand0`) that fails.

**Comment by actual-nh** [comment]
>  I guess it's the linear congruential generator that fails, under this specific seed and the constants `std::minstd_rand0` chose.

Could std::minstd_rand be used instead? This shouldn't increase computational load any, it's just a slightly better set of constants.

**Comment by BrettDong** [comment]
It's surprising that `std::mt19937` is even faster than the linear congruential generator `std::minstd_rand0`:

(time to generate 1,000,000 random integers)
| Generator | `-O0` | `-O2` |
|---|---|---|
| `std::minstd_rand0` | 34,382 us | 12,416 us |
| `std::mt19937` | 24,806 us | 8,905 us |

Test program:
```cpp
#include <iostream>
#include <random>
#include <chrono>
using namespace std;

int main()
{
    int x = 0;
    
    std::minstd_rand0 lcg(std::chrono::high_resolution_clock::now().time_since_epoch().count());
    auto t1 = std::chrono::high_resolution_clock::now();
    for(int i = 0; i < 1000*1000; i++) x ^= lcg();
    auto t2 = std::chrono::high_resolution_clock::now();
    cout << std::chrono::duration_cast<std::chrono::microseconds>(t2 - t1).count() << "us" << endl;

    std::mt19937 mt(std::chrono::high_resolution_clock::now().time_since_epoch().count());
    auto t3 = std::chrono::high_resolution_clock::now();
    for(int i = 0; i < 1000*1000; i++) x ^= mt();
    auto t4 = std::chrono::high_resolution_clock::now();
    cout << std::chrono::duration_cast<std::chrono::microseconds>(t4 - t3).count() << "us" << endl;

    return x;
}
```

**Comment by jbytheway** [comment]
Kevin was averse to std::mt19937 because of performance concerns, but if you have evidence it's not a problem then we can probably switch.

The disadvantages of std::mt19937 are that it uses more memory and is slower to initialize. Those might matter for is, but I wouldn't expect so.

However, I don't think this test failure is actually a sign that the rng is bad; I suspect this is just an unlucky seed.

**Comment by actual-nh** [comment]
> However, I don't think this test failure is actually a sign that the rng is bad; I suspect this is just an unlucky seed.

There's a lot higher likelihood of a bad/unlucky seed from a RNG that has a lower period, etc in the first place.

**Comment by actual-nh** [comment]
> It's surprising that std::mt19937 is even faster than the linear congruential generator std::minstd_rand0:

The MT was originally written specifically to avoid multiplication/division (including modulus) and to be better in pipelined architectures - something even more important now than it was when it was written.

**Comment by BrettDong** [comment]
However I just ran the same benchmark on a x86 server whose CPU model is Intel Xeon E5-2680 v4 and got the opposite result:

| CPU | `mt19937` | `minstd_rand0` |
|---|---|---|
| Apple M1 | 8,905 us | 12,416 us |
| Intel Xeon E5-2680 v4 | 7,007 us | 5,138 us |

**Comment by BrettDong** [comment]
And the benchmark reverses again on Intel Core i7-8650U:

| `mt19937` | `minstd_rand0` |
|---|---|
| 5,645 us | 7,749 us |

`mt19937` is still faster than `minstd_rand0`, by around 30%.

**Comment by anothersimulacrum** [comment]
On a `Intel i7-9700K`:

| Compiler      | `minstd_rand0` | `mt19937` |
|---------------|----------------|-----------|
| `g++ -O0`     | 20515us        | 20905us   |
| `clang++ -O0` | 41897us        | 10126us   |
| `g++ -O2`     | 7162us         | 10376us   |
| `clang++ -O2` | 17829us        | 10774us   |

On a `Intel i3-2330M`:
| Compiler      | `minstd_rand0` | `mt19937` |
|---------------|----------------|-----------|
| `g++ -O0`     | 25426us        | 28194us   |
| `clang++ -O0` | 31241us        | 20901us   |
| `g++ -O2`     | 7667us         | 10255us   |
| `clang++ -O2` | 7449us           | 6764us      |

Looks like gcc likes minstd_rand0 more, and that appears to be what we use for our release builds.

**Comment by anothersimulacrum** [comment]
And just for fun, on an `ARM Cortex-A72`:
| Compiler      | `minstd_rand0` | `mt19937` |
|---------------|----------------|-----------|
| `g++ -O0`     | 46129us        | 54931us   |
| `clang++ -O0` | 75755us        | 62160us   |
| `g++ -O2`     | 16033us         | 8413us   |
| `clang++ -O2` | 13393us           | 8465us      |

**Comment by kevingranade** [comment]
Thanks for the report, but one bad run of the RNG is not grounds to switch RNG backends.  What we have is one seed that produces out-of-tolerances RNG behavior in one test, out of who the hell knows how many seeds, what we do not have is any indication that:
1. this is an observable problem in the game.
2. that switching to MT will fix either any observable problem or the theoretical problem surfaced by the tests
3. improve anything else about the game that we can actually detect.

As you can see, MT and minstd_rand0 are a toss-up for performance, and the proportion of time we spend generating random numbers is hard to even measure it's so small.
Nevertheless, I prefer to use as simple a RNG as is feasible, so unless something serious crops up, we're sticking with minstd_rand0.
