### ISSUE TITLE
"aisle with lights" has to go

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#48873]
We already have an aisle and aisle lights as separate parts, and there's no reason for the opaque part/item that one can't disassemble or selectively purge from the vehicle.

**Comment by Maleclypse** [comment]
So are you saying that aisle lights can’t be removed from a vehicle?

**Comment by Salty-Panda** [comment]
If I understand them right, they refer to the fact that we have redundancy in those three vehicle parts:
aisle - boardable
aisle with lights crafted from aisle and light strip - boardable, light
aisle light - crafted from flashlight - can be put on non-obstacle tiles
