### ISSUE TITLE
Security Camera System does not work at night even with flood lights 

### ISSUE THREAD

**Issue by toweroglass** [CleverRaven/Cataclysm-DDA#48889]
# Describe the bug

In a contained vehicle at night you cannot see outside the vehicle when you have a camera system, even when you provide light.

# Steps To Reproduce

1. spawned a cube van
2. installed camera display, security camera and floodlight
3. turned on display, closed van and confirmed could see outside.
4. changed the time to 1 am.
5. turned on flood light and closed cube van.
6. cannot see outside.

# Expected behavior

you should be able to use a camera system at night if you provide a source of physical light.`

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: b4db094 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Alternative Map Key [alt_map_key],
    Crazy Cataclysm [crazy_cataclysm],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Crazy Cataclysm - UndeadPeople Tileset [CrazyCataclysmUDP],
    Graphical Overmap [Graphical_Overmap],
    MSX Black Military Cars [UDP_BlackMilitaryCars],
    sees-player icon, retrodays [sees_player_retro],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

# Additional context

**Comment by Saicchi** [comment]
Can't replicate on `0.E-10474-g1ae66c97a0 [64-bit]`
The security camera must be installed on the border of the vehicle, otherwise the board will block its view.

**Comment by toweroglass** [comment]
I believe I've got the camera installed correctly. it works during the day time. That's why I included the step.

**Comment by toweroglass** [comment]
nope. different idiot mistake. i put the floodlight behind the camera so the camera blocked the light. i'll close this now.
