### ISSUE TITLE
Manhole cover can be opened with hammer, but description says it needs crowbar

### ISSUE THREAD

**Issue by MarlossCDDA** [CleverRaven/Cataclysm-DDA#48884]
# Describe the bug

Manhole covers have the following description: "A heavy iron disc that typically covers a ladder into the sewers. Lifting it from the manhole is impossible without a crowbar." But in fact, at least for the manholes next to mines, you can lift them by `a`pplying a hammer on them.

# Steps To Reproduce
- Find a mine
- Find its manhole
- `a`pply a hammer to open the cover
- Look at your new manhole cover object, see that you're supposed to need a crowbar

# Expected behavior
I think probably you should need prying 2, but if it's intended that you can use something like a hammer with prying 1 then the description should be updated.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2009
- Game Version: b4db094 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    sees-player icon, retrodays [sees_player_retro],
    Alternative Map Key [alt_map_key],
    Stats Through Kills [stats_through_kills]
]

**Comment by ToxiClay** [comment]
Data point: the makeshift crowbar has prying 1 and its description states that it can lift manhole covers. A more nuanced patch will be needed than simply changing manholes to prying 2.

**Comment by Night-Pryanik** [comment]
> give the makeshift crowbar Pry 2.

Makeshift crowbars were deliberately nerfed to have prying 1 (#36435) as they ain't sturdy enough.

In my opinion we don't need to change any values (manholes prying requirement, makeshift crowbar prying ability). What we really need here is slightly change the description so it wouldn't explicitly state that you need a crowbar, but any tool with prying ability.

**Comment by ToxiClay** [comment]
>What we really need here is slightly change the description so it wouldn't explicitly state that you need a crowbar, but any tool with prying ability.

This would leave the Makeshift Crowbar able to pry manhole covers, though, despite being ductile enough to be hammered with a rock. Is that as intended?

**Comment by Night-Pryanik** [comment]
I think makeshift crowbar is sturdy enough to lift manhole covers (and pry out nails).

**Comment by deadcutlass2** [comment]
Perhaps a change to the makeshift crowbar, that it  can be damaged when prying..

**Comment by SenpaiSlime** [comment]
The makeshift crowbar is literally a stone bent pipe, there is no way it could pry properly. However I/we could totally update the manhole to say you need a strong prying tool to open it up, alternatively we introduce a pry level of 3 specific to something as heavy as a manhole cover and update existing tools that are proper crowbars to use it, assuming that doesn't exist yet.

**Comment by Night-Pryanik** [comment]
Description was changed some time ago and no longer mentions crowbar.
