### ISSUE TITLE
CBM energy storage is capped at 2100kj

### ISSUE THREAD

**Issue by lcy03406** [CleverRaven/Cataclysm-DDA#48881]
# Describe the bug

While installing power storage CBM, if the player's max energy is 2100kj, you cannot install more storage CBMs and get the message "Max power capacity already reached." 
2100kj is not too large, and not very meaningful. The reason is 2100kj + 100kj > 2147483647J

# Steps To Reproduce

1. Have the player and 22 power storage CBMs
2. Go to a hospital and install 21 power storage CBMs
2. Try to open the installing menu again.
3. See the power storage CBM is forbiden by "Max power capacity already reached."

# Expected behavior

The player should be able to install more storage CBMs. If there must be a cap, it should be some meaningful value, balanced by some gameplay reason and not the max int32.

# Screenshots

![image](https://user-images.githubusercontent.com/3512151/118350614-47d22200-b58a-11eb-9386-4ac3eecaf68e.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 07c58d9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    DinoMod [DinoMod],
    Mythical Martial Arts [MMA],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Fuji's Military Profession Pack [fuji_mpp],
    Stats Through Skills [StatsThroughSkills],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Bionic Slots [cbm_slots]
]

# Additional context

None.

**Comment by Fris0uman** [comment]
See discussion in https://github.com/CleverRaven/Cataclysm-DDA/issues/34422

**Comment by lcy03406** [comment]
@Fris0uman I see. I read #34422 and related links.  But what's the team's opinon about the energy cap? 

@kevingranade wrote "The fact that you can just keep installing power modules is a bug, it is absolutely not intended that you can get more than 2,000 bionic power". If we all agreed on this, the cap should be 2,000,000J, not 2147483647J.

I don't think 2000KJ is a reasonable cap, but if you think so, it's fine. Anything is better than 2147483647J hard cap.

**Comment by anothersimulacrum** [comment]
Decreasing the cap to 2 MJ is a reasonable change, but I don't think we need an issue for it.
