### ISSUE TITLE
Zombie won't step on walkway to reach the player

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#48883]
# Describe the bug

# Steps To Reproduce

# Expected behavior

# Screenshots
![screenshot-walkway](https://user-images.githubusercontent.com/31852/118358134-fcf5e180-b56c-11eb-88ad-0ffab3d9c1c9.png)

# Versions and configuration
- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.E-10550-gb4db09430a-dirty [64-bit]
- Graphics Version: Curses
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

# Additional context

[2021.05.10.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6486145/2021.05.10.zip)

**Comment by PatrikLundell** [comment]
You probably need to update the post to make sure your info isn't hidden by the comments that tend to hide the info if you're not very careful.

**Comment by l29ah** [comment]
No idea what you are talking about.

**Comment by Zireael07** [comment]
He likely means the comments built into the bug report template - it's easy to insert content within them, so people won't see what you wrote.

**Comment by l29ah** [comment]
Ah, thanks. Nah, i just didn't write anything.

**Comment by actual-nh** [comment]
> Ah, thanks. Nah, i just didn't write anything.

Well, please provide more information if you want anything done about it (other than the bug report being closed).

**Comment by l29ah** [comment]
Still an issue on todays master.
