### ISSUE TITLE
Remembered vehicle location is displayed at the ground level instead of the proper one

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#48897]
# Describe the bug

I have my remembered foldable cart accompanying me in my lab shopping spree, but it's shown on map on the ground level instead of however deep it is atm.

# Steps To Reproduce

Load the game and check the map.

# Expected behavior

# Screenshots

# Versions and configuration
- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.E-10552-g227b45b9e3-dirty [64-bit]
- Graphics Version: Curses
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

# Additional context
[2021.05.10.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6489308/2021.05.10.zip)

**Comment by OliveChukar** [comment]
Tested on 0.E-10395-g4525b4f with Dark Days Ahead [dda] and no mods. Tested on a fresh world spawned a vehicle in a lab at level -8  and another on top of a radio tower at level 6 both location notes appeared on level 0 on the map.
