### ISSUE TITLE
Wind not being properly stored or restored

### ISSUE THREAD

**Issue by danielkwinsor** [CleverRaven/Cataclysm-DDA#48906]
# Describe the bug
Direction and speed of the wind can vary between save / load cycle.  

# Steps To Reproduce

1. Start game, observe wind direction, Save and Quit (or debug quit to main menu)
2. Start second game, perform same actions.
3. Load first save, observe wind direction has changed.

This problem also exists when you have many historical savegames copy pasted and load them up later only to find they all have the exact same direction and speed, but not what was saved.

# Expected behavior

# Screenshots

# Versions and configuration

# Additional context

**Comment by ZhilkinSerg** [comment]
There is `weather` object that is serialized to master save in `game::serialize_master`. I've checked three random savegames and they have different numbers in weather object:

```
  "weather": { "lightning": false, "weather_id": "clear", "next_weather": 5257800, "temperature": 57, "winddirection": 247, "windspeed": 6 }
}
```

```
  "weather": { "lightning": false, "weather_id": "clear", "next_weather": 5213100, "temperature": 43, "winddirection": 315, "windspeed": 3 }
```

```
  "weather": { "lightning": false, "weather_id": "sunny", "next_weather": 13149578, "temperature": 59, "winddirection": 180, "windspeed": 2, "snow_level": 17.954794 }
```

Maybe this object is not deserialized properly in `game::unserialize_master` (or `weather_manager::unserialize_all`), though I am not seeing any obvious issue there. Another chance is that weather is somehow reset after it was deserialized from savegame.

**Comment by RelMayers** [comment]
did some testing, 
with 2 save and reloads weather didnt change.
![obraz_2021-05-18_234930](https://user-images.githubusercontent.com/74023387/118727824-b1c12480-b833-11eb-88ca-c902387039c2.png)

**Comment by danielkwinsor** [comment]
<img width="533" alt="1" src="https://user-images.githubusercontent.com/2822992/119082484-11920980-b9b3-11eb-8dfd-dca81a17f237.png">
<img width="521" alt="2" src="https://user-images.githubusercontent.com/2822992/119082489-122aa000-b9b3-11eb-8225-3aaecba5f06b.png">

**Comment by danielkwinsor** [comment]
Between pic 1 and pic 2, this game saved, time passed in alternate game, restored this game.

**Comment by danielkwinsor** [comment]
Here is another way to reproduce: Start new world / game.  Copy paste the save on disk.  On the copy, advance time.

**Comment by ZhilkinSerg** [comment]
That was introduced in #28143 probably.
