### ISSUE TITLE
Cash management ideas

### ISSUE THREAD

**Issue by Psiclops** [CleverRaven/Cataclysm-DDA#48903]
A soft objective of my current character is to collect over a million dollars by killing zombies and taking their wallets.
Unloading enough wallets to have thousands of twenty dollar bills leads to storage issues, so I have some ideas about managing the cash in a way that does not involve burning it or throwing it on the ground.

1. The complete lack of one hundred dollar bills is not realistic. Benjamins are actually quite commonly carried by many people, and are even offered as options for withdrawal at many types of ATM machines, including at banks and casinos. Adding hundreds, even if they are rare, would add to realism. Related to item 2, perhaps ATMs would allow withdrawal of 20's or 100's if you wanted the currency form. (there could be some kind of limit on the amount they had, some would be empty already.)

2.  Many RL current ATM machines offer the ability to deposit cash. I would love the  CDDA ATM's to allow the deposit of cash to credit on cash cards. This alone would be enough to fix most of my other issues about managing cash.

3. Allow bundling of different bill types, perhaps using thread or paper to make physical management of large amounts of cash more feasible. Currently in the game is the item "bundle of money" which has no specific value, but it could be "bound stack of 20's" which requires quantity 100 twenty dollar bills, 1 unit of duct tape and some paper as a recipe with 2 minutes of time, Obviously allow disassembly to reverse the binding back to individual bills. This reduces the consumption of "item space limit" by 100x. A stack of 20's would have the combined volume and weight of 100 bills plus some amount for the wrapped paper, but be a single item.

4.As it stands, there is some kind of hard limit on the quantity of items in a specific container. Even a vehicle cargo space will get overwhelmed with enough paper twenties, despite being nowhere near the volume limits, and will not allow additional items to be placed there. I tried stuffing the bills into a hiking backpack, and placing the backpack in a cargo space and it will cause game crashes randomly if you try to manipulate the backpack, if there are enough bills in there. We are talking about many 1000's of bills. 

5. Ease of use, allow auto-pickup settings to pull specific items out of wallets without (U)nloading them or picking them up and (O)pening them. I currently only keep twenties and cash cards and throw the rest of the garbage away. 

6. Add an achievement related to the acquisition of this useless wealth, just for fun.

Thanks!

**Comment by PatrikLundell** [comment]
2. Deposit ATMs would get full over time.

**Comment by Psiclops** [comment]
When you have over 1000 individual bills in your inventory, using a (w)ield action starts to take a VERY long time to show the dialogue. Up to 20-30 seconds between pressing "w" and seeing the choice menu pop up. Probably the engine is parsing each bill individually to determine if it is wieldable or something. 

Similarly if you are in a vehicle near a cargo container with 10000 bills nearby, it feels like the game is hung before the menu pops up.

**Comment by PatrikLundell** [comment]
Yes, the game doesn't handle large numbers of non stacking items well (try shattered glass, for instance, or pieces of fabric), so it's a general problem. There are some band aids in the form of bundling for some kinds of items, but those are generally a work around.

**Comment by Psiclops** [comment]
The way that ammunition is dealt with does not cause these lag problems. Perhaps using that method for more items would help.

**Comment by PatrikLundell** [comment]
Ammunition is stackable, which is why it doesn't cause problems. I assume there is some reason most things aren't, but I don't know what they might be (things that aren't identical, such as food with different expiration time, or the same unperishable dish made out of different ingredients make sense, as they aren't actually identical, just similar).

**Comment by Psiclops** [comment]
Similar to #48937

**Comment by Nerdy314159265** [comment]
A related is I've been storing all the money I've collected in a plastic bag and it's nowhere near full, however, it frequently bugs out and doesn't want me to add any more to it.

**Comment by PatrikLundell** [comment]
A plastic bag isn't rigid, and so would demand additional space from the container it is stored in when you're trying to stash more money into it, in case it's stored within something, which might be the cause of Nerdy Pi's issue. I'm using a briefcase, which is rigid.

**Comment by Nerdy314159265** [comment]
> A plastic bag isn't rigid, and so would demand additional space from the container it is stored in when you're trying to stash more money into it, in case it's stored within something, which might be the cause of Nerdy Pi's issue. I'm using a briefcase, which is rigid.

That could be it if the length value increases as well. If that is the issue then it'd be useful to have some more clear indications of that. The container system is not 100% there yet IMO and still has some clunkiness to work out.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
