### ISSUE TITLE
CDDA cannot save an existing character/world or make a new one

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#48915]
# Describe the bug

Exactly as described in the title. Whenever I load my character, I get the following error:

> Failed to write last world info to "./config/lastworld.json": opening file failed

I'm able to skip past this by pressing enter, and otherwise, the game plays as normal until it saves, whether manually or automatically, at which point, it gives similar errors for the following files:

./save/Newland/#QXJj.sav
./save/Newland/#QXJj.mm
./save/Newland/#QXJj.log

While I am able to get past these errors by pressing enter again, exiting the game and reloading the save again confirms not only that this error persists, but that my attempt to save my progress has failed, as everything reverts back to where it was when I first discovered the problem. This renders the game practically unplayable.

In addition, when trying to create a new world, once I finish with the settings and finalize it, I don't get any error messages, but I also do not see the new world appearing in either the world menu or the new game menu.

# Steps To Reproduce

Described above.

# Expected behavior

I expect to be able to save and reload any progress made going forward, with no errors preventing me from doing so, and I expect to be able to create and play in a new world.

# Screenshots

# Versions and configuration

Windows 8.1
Version 0.E-3 Stable
Tiles
English
Mod list:
no_npc_food
aftershock
crt_expansion
magiclysm
XEAS
Medieval_stuff
DinoMod
hydroponics
MMA
blazemod
NM_wpns
jury_rigged_robots
No_Fungi
fuji_mpp
Speedydex
stats_through_kills
StatsThroughSkills
magiclysm_no_class_limit

# Additional context

I don't know if any of this will help to narrow down what the problem is or what I can do about it, but here goes...

The only thing I have changed recently is having updated the launcher. After doing so, I was able to reload and eventually save my game without issue, but the next time I tried to reload it, the error described above began to occur. I don't know exactly when the inability to create new worlds began, but I only discovered that problem after discovering the saving/reloading problem.

I also happened to notice that opening the launcher no longer causes Windows to automatically prompt me for administrator permission before it can run. When trying to open as an administrator anyway, Windows prompts me for administrator permission, and once I grant it, the launcher fails to open, instead displaying a command prompt window and giving me the following error message:

> Windows cannot find 'pythonw.exe'. Make sure you typed the name correctly, and then try again.

After clicking "okay," both the error message and the command prompt window close, and the launcher fails to open.

Otherwise, when I do open the launcher, and try to revert back to an earlier stable version, the launcher crashes, giving the following message:

> CDDA Game Launcher version: 1.5.3
> OS: Windows-8.1-6.3.9600-SP0 (64-bit)
> Type: <class 'PermissionError'>
> Value: [WinError 5] Access is denied: 'C:\\Program Files (x86)\\CDDA Game Launcher\\cdda\\cdda\\cdda\\cdda\\cdda\\cdda\\cdda\\cdda\\cdda\\cdda\\cdda\\cdda\\previous_version'
> Traceback:
> File "C:\Program Files (x86)\CDDA Game Launcher\cddagl\ui\views\main.py", line 2078, in completed_test
> 
> self.clear_previous_dir()
> File "C:\Program Files (x86)\CDDA Game Launcher\cddagl\ui\views\main.py", line 2132, in clear_previous_dir
> self.backup_current_game()
> File "C:\Program Files (x86)\CDDA Game Launcher\cddagl\ui\views\main.py", line 2183, in backup_current_game
> os.makedirs(backup_dir)
> File "os.py", line 225, in makedirs

**Comment by ZhilkinSerg** [comment]
You have installed launcher and game to a location you don't have permissions to write to. Do not use read-only folder (e.g `Program Files`), create a folder accessible to your user (e.g. `C:\Games\`) instead and put your launcher and game there.

**Comment by AmarinReyny** [comment]
> You have installed launcher and game to a location you don't have permissions to write to. Do not use read-only folder (e.g `Program Files`), create a folder accessible to your user (e.g. `C:\Games\`) instead and put your launcher and game there.

It's in the same place it's always been in, and the error is only just now happening. Still, I'll try this... hopefully, it'll work.

**Comment by Zireael07** [comment]
If you only now get the errors, and you haven't changed UAC or other security settings, then most likely your hdd is slowly dying - time to backup stuff!!!

**Comment by AmarinReyny** [comment]
> If you only now get the errors, and you haven't changed UAC or other security settings, then most likely your hdd is slowly dying - time to backup stuff!!!

Thanks for the warning. I'll see what I can do about it, but given my extremely limited budget, I'm not sure what that'll entail...

**Comment by Anaglyphic** [comment]
hi.

Shot in the dark here, but WTH is with that ridiculous path?! cdda 12 times or whatever? Is that an error of the launcher or the actual path, and if so, aren't paths limited? What filesystem is the C drive, ntfs or fat32?

**Comment by AmarinReyny** [comment]
> hi.
> 
> Shot in the dark here, but WTH is with that ridiculous path?! cdda 12 times or whatever? Is that an error of the launcher or the actual path, and if so, aren't paths limited? What filesystem is the C drive, ntfs or fat32?

Those are all from when I first installed the launcher, and was initially trying to get it working. I kind of had trouble with it, and while I had said trouble, it kept making new folders. I have no idea why.
 
> edit: hit tab-tab-space too fast. The obvious choice is stop using the 3rd party launcher - does it work fine without it? Since it's not part of cdda anyway and you might want to ask on creator's github. Besides, just curious, why even bother to use a 3rd party launcher if you're running 0.E stable? Curious on that but not really relevant I guess.

I use it because that's what I'm used to. My friend who first introduced me to CDDA told me to use it, so that's what I did.

Either way, what ZhilkinSerg suggested seems to have worked, so the issue is resolved. Thank you.
