### ISSUE TITLE
Add modifiers to crafted items.

### ISSUE THREAD

**Issue by AskaHope** [CleverRaven/Cataclysm-DDA#48916]
# Is your feature request related to a problem? Please describe.
I just saw a guide on proficiencies on Reddit and after reading some comments, I had an idea about item modifiers.

# Describe the solution you'd like
What about allowing players to craft whatever they want but instead of several skill failure checks, we add a modifier to the crafted item, just like in Rimworld?

Modifiers ranging from terrible to masterwork that affect weapon and armor attributes, lowering/increasing their efficiency and durability as the player skills increases.

I see here an opportunity to improve game progress balance-wise with this system, especially during mid-game. Focusing proficiencies in a more time consuming feature and adding weapon/armor quality to the equation is better IMHO than just dropping crafting success chances to the ground as any individual with above average intelligence, no experience and a detailed manual is able to craft at least a mediocre sword on his/her first attempt. We humans are extremely efficient at following step-by-step instructions and hardly fail when we do.

# Describe alternatives you've considered
Not suggesting.

# Additional context
I think it's a good idea.

**Comment by AskaHope** [comment]
A skilled blacksmith would definitely end the job faster but if I spend 4 days to craft a sword, I at least expect something out of it.

**Comment by RelMayers** [comment]
Did you thought of any alternatives or just skipped that step?
Also crafting mechanics are in my opinon in good spot right now.

**Comment by SariusSkelrets** [comment]
It will work if the pre-cataclysm items get similar modifiers

I expect most if not all tools in commercial buildings to be well-made so they’ll get good modifiers. Some tools in a house might be sightly damaged by years of use

Tools made by the player will have modifiers based on skill, proficiency and materials. The first batches won’t be as good than the regular quality you can find in store

The only thing I don’t want is an individual able to make better tools by hand with scrap than the pre-cataclysm mechanized production using quality materials

**Comment by AskaHope** [comment]
> Did you thought of any alternatives or just skipped that step?
I actually did, but ended up thinking it's not a good alternative to this game, decided to just leave the main idea open ended and up to the devs interpretation as I'm not experienced in game balancing. I leave it up to the devs if they want to give it a shot
> Also crafting mechanics are in my opinon in good spot right now.
I agree. I'm glad with the introduction of proficiencies but I think the current algorithm is unrewarding and unrealistic. Even a complete idiot would be able to turn a bunch of leather patches into some sort of pouch given enough time and resources, even if said pouch would break at the slightest turbulence.

The higher failure chances could scale with item difficulty, that would make a lot more sense as raw skill is no longer enough. That way early game characters wouldn't be forced to grind from minute one to get average equipment, they can choose to craft low quality items with good utility/modifiers in the mid game and upgrade them as the game progresses.

The only fault I see in this system is that players can construct/deconstruct the same items several times to buff their quality. Maybe disabling deconstruction in most metallurgy items and add an option to "improve" them in a crafting table (provided you have tools and raw materials) might be a solution.

**Comment by AskaHope** [comment]
> The only thing I don’t want is an individual able to make better tools by hand with scrap than the pre-cataclysm mechanized production using quality materials

Capping the item qualities to materials available is actually a great idea! I can see the possibility of adding machines in a factory that could be used to achieve masterwork quality in certain items (provided you have proficiency in industrial machinery), but that's a very ambitious idea.

**Comment by SariusSkelrets** [comment]
I guess the factories would need to be added first

The idea of machines in factories that can be used to make the best tools possible is a good one.

 Currently, tools in factories have a quality of ‘’work well enough so nobody complains but improving the design would make them much costly to produce’’ 

Some high-grade tools might be found in stores, expensive and rare but someway better than the cheaper versions. Their rarity is simply caused by the low-cost tools the average citizen uses

This system, along with the factories, would allow people to experience this unique combination of looting and crafting. Loot the high-grade materials, secure the factory and craft tools without the profit margin before enjoying your lighter, more confortable and sturdy tools

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
