### ISSUE TITLE
FeRq: possible aim enhancements? (discussion/notes)

### ISSUE THREAD

**Issue by Anaglyphic** [CleverRaven/Cataclysm-DDA#48928]
Just to put this here since someone will refer back to it - aka _me_. And I know actual-nh will read it, god bless em.
I know this isn't my personal notebook, I do want others to comment and suggest.
//////

Story - apologies if you're bored reading it, it's unimportant I promise you can skip it.

I prefer to play sneak maps, 16-size cities no-spacing to build interconnected megacities with roving hordes and severe respawn, 4.0-5.5x? You get high-density zeds, you frequently end up with  _hundreds_ on-screen at any given location. like ~26 deep chasing a eyebot kind of thing, or they'll level a whole building trying to get a noisy turret with every tile a corpse. It can get crazy dense, but to me it's fun*, and discharging a firearm is suicidal, even with 4-figures of ammo, especially the louder ones, 308s 30-06s and 50s even suppressed will pull everything in the bubble to you, and since even 100-rd drum mags need swapping eventually, nevermind 5-shot bolt action? Dead. Firing near-silent weapons can be tricky, too. You need to plan, even walking. I'd never just hold KP_9 to walk _sort-of NE_ with autopathing on. You round a corner without peeking and that can easily lead to watching your final moments.

_(_ **"There's so many ways, to play, C:DDA !"** _should be the slogan.)_

And in this everything-needs-to-be-planned world of low encumbrance and no slip-ups? 
_Didn't say easy to implement, just come-to-mind_ aim enhancements I've wanted:
```
* protected terrain - stop shooting my car and through my house windows! Don't wreck my stuff!
* threat assessment - give priority to things that move fast or have ranged weapons too.
* circle thresholds - at XX tiles precision snipe, at YY careful bursts, at ZZ? immediate full-auto!
* combat monitor    - aim indicator or projectile path alt color/blink, ie. enemies > ammo, etc.
* targeted area     - if manual pick or cycle-to target, start next f nearest to that fallen enemy.
* zone cover        - you mark region(s) and anytime an enemy enters, auto-engage f and target.
* noise map         - show soundmap circles for both the weapon discharge and the target strike.
* discriminator     - skip non-hostiles.
```
That last one is from #48649

_* Yes it becomes unplayable eventually and you die, not sure it's even possible to survive more than a month without hiding the whole time. But it's ~~different~~ fun._

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
