### ISSUE TITLE
Electric motor disassembly and destruction drop inconsistent amounts of bearings

### ISSUE THREAD

**Issue by SSpook** [CleverRaven/Cataclysm-DDA#48926]
# Describe the bug
Disassembling electric motors yields less bearings than destroying an installed motor.
Large electric motor disassembly yields 40 bearings, destruction on a vehicle yields around 1800.
Electric motor disassembly yields 10 bearings,, destruction around 500.

# Steps To Reproduce
1. Find an electric motor or a large electric motor.
2. Check disassembly results.
3. Install the motor on a vehicle.
4. Destroy the motor in your preferred way.
5. Count the bearings.

# Expected behavior
I'd expect a careful disassembler to find all the bearings when taking the motor apart and/or electric motors to not form bearings when beaten.

# Versions and configuration

 - Game Version: 0.E-10395-g4525b4f
 - Mods loaded: dda

# Additional context
-Enhanced and super electric motors can't be disassembled but drop ~1300 and ~2200 bearings.

**Comment by OliveChukar** [comment]
Tested on 0.E-10395-g4525b4f with Dark Days Ahead [dda] and no mods.  Tested in game and replicated the issue.

I looked in json/vehicleparts/motor.json and found that the "breaks_into" value for bearings is much larger then the number of bearings given by disassembly in json/recipes/recipe_deconstruction.json.
