### ISSUE TITLE
[Blazemod] Wiring vehicle part floats on water

### ISSUE THREAD

**Issue by SSpook** [CleverRaven/Cataclysm-DDA#48927]
# Describe the bug

Installing wiring on a vehicle makes it float on water.

# Steps To Reproduce

1. Find a bicycle.
2. Find 3 or more wire and install them on the bike..
3. Ride the bike into a river.

# Expected behavior
Expected metal wire to not float or act like a boat hull.

# Versions and configuration

    Game Version: 0.E-10395-g4525b4f
    Mods loaded: dda, Blaze Industries

# Additional context
There is no indication on the vehicle examine menu that the vehicle can float.

**Comment by Zeilos** [comment]
I have tested on the present version and can confirm that bikes float on deep water, though slowly with 2+ wiring sections along the side. Interestingly it doesn't have a sealed hull height. Dropping the wiring to 1 sank the bike. I've also checked the wiring's json and it doesn't use any boat code at a glance. Could this just be a vehicle density issue with water?

**Comment by Night-Pryanik** [comment]
Blazemod is no longer supported.
