### ISSUE TITLE
Purifying chemical imbalance while experiencing a chill locks the survivor out of the comfortable state.

### ISSUE THREAD

**Issue by sharkfinsouperman** [CleverRaven/Cataclysm-DDA#48923]
# Describe the bug

If you purify away chemical imbalance while experiencing a false chilled state, it stays that way unless you reach the warm state or higher, or anything lower than chilled, without entering the comfortable state.

This may apply to a hot flash as well.

# Steps To Reproduce

Gain the chemical imbalance mutation, wait for either a hot flash or a chill and remove the mutation using a purifier. I'll assume this will also work through debugging, because I undid the bug by debugging the mutation in again and waited for the chill to end. This restored the survivor to the comfortable state and normal behaviour is restored.

# Expected behavior

It is expected the effect of the chemical imbalance would vanish once the mutation that caused it was gone.

# Versions and configuration

Win7, 0.E-3, base game with no mods

**Comment by OliveChukar** [comment]
Tested on 0.E-10395-g4525b4f with Dark Days Ahead [dda] and no mods. 

Was not able to make the issue happen. Debuged in a character with chemical imbalance waited for both false hot and cold conditions then removed mutation with debug conditions ended with time as they should. Tried removing the mutation with purifier and the character returned to comfortable after a short time.

**Comment by actual-nh** [comment]
Is #37439 still present (not the eyes part, the original issue)?

**Comment by OliveChukar** [comment]
That issue did not happen when I was testing.

**Comment by sharkfinsouperman** [comment]
@OliveChukar Did you use the trait, or was it the mutation? There may be a difference how each are handled because the trait cannot be purified, so it might be bypassing the function with the bug, or the buggy routine within the function.

In my case, the mutation was gained and removed using a mutagen and purifier, and later debugged in as a mutation, allowed to cycle out of the chills, and then debugged out again.

**Comment by OliveChukar** [comment]
I tested with a copy of 0.E that I downloaded on April 1 2020 and was able to replicate the issue. I tested it the same way I tested in experimental so if the problem still exists in experimental I should have seen it.

**Comment by sharkfinsouperman** [comment]
Thanks, so it is an issue in 0.E but resolved itself at some point since. I'll close the issue since it no longer affects game play.
