### ISSUE TITLE
Cant change language if 2x scalling

### ISSUE THREAD

**Issue by happyman1997** [CleverRaven/Cataclysm-DDA#48945]
When 2x scalling, game cant change language - only english
Ways to reproduce: Set scalling on 2x - try to set for example russian language
![cda1](https://user-images.githubusercontent.com/81465252/118913470-372afe80-b932-11eb-88ff-aa638a8e6da3.png)

**Comment by actual-nh** [comment]
Please give the version (and other) information the template asks for - for one thing, IIRC there was a fix of that issue a bit back, and you may have a version from before that.

**Comment by happyman1997** [comment]
> Please give the version (and other) information the template asks for - for one thing, IIRC there was a fix of that issue a bit back, and you may have a version from before that.

Newest version, last build without this problem was 11581

**Comment by actual-nh** [comment]
Ping: @BrettDong, @ZhilkinSerg?

**Comment by BrettDong** [comment]
A potential solution: revert to SDL 2.0.12 in GHA build process.

**Comment by BrettDong** [comment]
Unfortunately there is only SDL 2.0.14 in MXE package repository: 
* https://pkg.mxe.cc/pkg/
* https://pkg.mxe.cc/repos/apt/pool/main/m/mxe-i686-w64-mingw32.shared-sdl2/

**Comment by happyman1997** [comment]
@BrettDong Well, is there any fixin`?

**Comment by andrei8l** [comment]
Calling `set_language()` before `get_options().save()` (called by `init_term_size_and_scaling_factor()` if scaling factor is used) works around the issue in mingw. There must be an overflow somewhere but it's not apparent at a glance and there's no ASan for (cross) mingw.

**Comment by BrettDong** [comment]
I'm still unable to reproduce the issue on MSVC with SDL 2.0.14.
![scaling](https://user-images.githubusercontent.com/21075502/120647459-360add00-c4ad-11eb-88d0-a38023d02737.png)
Can't help debug and find out where the bug is.

**Comment by andrei8l** [comment]
I think this is a caching issue rather than an overflow. `options_manager::save()` calls `_()` and `options_manager::serialize()` calls `translation::translated()` a couple of times all of which initialize/access the translation cache too early if scaling factor is set. So I do think the best option is to properly initialize the translation cache by calling `set_language()` (or at least `bindtextdomain`, `bind_textdomain_codeset`, and `textdomain`) before `catacurses::init_interface()`.

**Comment by ZhilkinSerg** [comment]
I am still wondering why did it start to happen only after we bumped SDL2 version up?

**Comment by andrei8l** [comment]
That does strongly indicate there's some UB somewhere, but I'm a little too dumb to figure it out
