### ISSUE TITLE
Stone Fireplace (and other constructions) require too high digging quality

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#48948]
# Describe the bug

Stone Fireplace requires digging quality 2, despite being just a carefully arranged pile of rocks. A charcoal kiln requires only digging quality 1 and is also made only of pure stone. Same with a rock forge.

There seems to be more constructions which require digging 2 for seemingly no reason. Stone wall and dry stone wall both require digging quality 2, despite neither having any logical need for such in construction.

# Steps To Reproduce

1. Examine and compare various rock based construction quality requirements

# Expected behavior

Requiring no digging quality or at most 1. There's no digging involved in these constructions.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: cae2be1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    No Fungal Monsters [No_Fungi],
    No Monsters [Only_Wildlife]
]

# Additional context

**Comment by Zireael07** [comment]
Most stone fire pits I can find on the net DO require digging: https://homebnc.com/best-diy-firepit-ideas/#:~:text=One%20of%20the%20simplest%20ways,enough%20to%20not%20fall%20inside.

**Comment by Tommy-os** [comment]
These are not pits to my understanding, but free standing stones arranged by hand in a stable manner without any mortar. Neither do they require a shallow pit for construction, as a "fire ring" requires.
