### ISSUE TITLE
Flinknapping failure rate too high

### ISSUE THREAD

**Issue by TheLyca0n** [CleverRaven/Cataclysm-DDA#48956]
The failure rate for flintknapping without proficiency has made failure too high for naked wildness challenge. Making the stone chopper to progress has become next to impossible without dying of thirst due to the length of the grind/number of flint needed

I suggest either removing the basic/advanced flintknapping requirement for the chopper (as it is literally just a split open rock neanderthals made) or decreasing the diffuclty.

**Comment by actual-nh** [comment]
See #47211 and possibly #48925 for further discussion on this.

**Comment by Evrze** [comment]
There was a change that inverted the normal rates tied to the proficiency multiplier, it shifting things exponentially harder than they should be.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
