### ISSUE TITLE
No recipe to make yarn

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#48959]
# Describe the bug
I was making a Magiclysm yarn and realized that the only yarn the survivor can make is grass yarn and there are no cotton or wool recipes. I'd fix this in what I'm working on but it feels like scope creep so I'm making a note here for someone to fix it.  That person may be me.  It could literally almost mirror the grass yarn recipe.

# Steps To Reproduce

# Expected behavior

# Screenshots

# Versions and configuration

# Additional context

**Comment by Maddremor** [comment]
Sheep ⇒ wool staple ⇒ felt patch ⇒ yarn is a thing, but there might be a more straightforward realistic method.

**Comment by Maleclypse** [comment]
> Sheep ⇒ wool staple ⇒ felt patch ⇒ yarn is a thing, but there might be a more straightforward realistic method.

#48982 Thanks for getting me to look at the felt patch recipe!

**Comment by ActualDio** [comment]
From what I can see that recipe shouldnt exist. Clumping is done on already woven wool so you couldnt just put a clump of wool fibers straight from a sheep to get a felt patch. I suggest as well as adding a yarn recipe, also requiring that felt patch recipe to require a loom to function and increase its crafting time.
