### ISSUE TITLE
Using an electric firestarter does not expend a charge

### ISSUE THREAD

**Issue by DalenTalas** [CleverRaven/Cataclysm-DDA#48955]
# Describe the bug

Using an electric firestarter does not expend a charge.

# Steps To Reproduce

1. Obtain an electric firestarter.
2. Load with a fully-charged light battery.
3. Attempt to light a fire.

# Expected behavior

Earlier versions of the code did expend a charge from the firestarter's battery when using it.

# Versions and configuration

# Additional context

OS: Windows
OS Version: 10.0 2004
Game Version: 12fcd38 [64-bit]
Graphics Version: Tiles
Game Language: System language []
Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
Aftershock [aftershock]
]

**Comment by OliveChukar** [comment]
Tested on cdda-windows-tiles-x64-2021-06-05-0832 with Dark Days Ahead [dda] only no mods.  Tried all compatible battery types and none consumed charges on use.  Also tried battery compartment mod with car battery and it did not consume charge.
When I tried the battery compartment mod with car battery I got      ERROR : src/item_contents.cpp:1499 [float item_contents::relative_encumbrance() const] volume exceeds capacity (6753ml > 1200ml)    this is probably unrelated to the original issue.

**Comment by DalenTalas** [comment]
Haven't gotten to trying to recreate the issue in another save yet. Just noting similar symptoms listed in #47887.

**Comment by DalenTalas** [comment]
Possible similar symptoms in #47887.

**Comment by DalenTalas** [comment]
Looks like this has been resolved in later versions.
