### ISSUE TITLE
Make raw sausage use stomach as casing and/or add synthetic casing and crafting

### ISSUE THREAD

**Issue by Warfoniusz** [CleverRaven/Cataclysm-DDA#48953]
Wasteland sausage crafting requires stomach as a casing while regular sausage doesn't. It would be good to either make both use it/not use it and add some sort of synthetic casing with crafting to make it more realistic.

**Comment by DalenTalas** [comment]
As per the Wiki, "Generally, smoke and water can not pass through the casing, so plastic is used for non-smoked products where high yields are expected." https://en.wikipedia.org/wiki/Sausage_casing#Plastic_casings

An option may be an alternate crafting recipe for sausage casings, using plastic bags and the appropriate plastic handling proficiency,

**Comment by merrygin** [comment]
I just took a brief look into the receipes and sausage casings are already alternatively made with plastic bags. 
So this would actually just be about replacing the stomach with casings for the wasteland sausage and add casings as requirement for all other sausage types (I think I only saw them for bratwurst and homemade hotdogs). Also, the receipe for casings should be adapted to use EITHER stomach OR plastic bags - atm the need both.

**Comment by merrygin** [comment]
Made a PR for all sausages to require casings now, also casings would need stomachs OR plastic bags now. No added synthetic casing though, i figured this was an easy and ok solution for the distinction for now. Could possibly add some more varient materials for the casings in the future though, i think.
