### ISSUE TITLE
[My Sweet Cataclysm] Can't continue crafting in-progress caramel ointment

### ISSUE THREAD

**Issue by clownhonko** [CleverRaven/Cataclysm-DDA#48957]
# Describe the bug

Activating an in-progress caramel ointment does not allow you to continue the craft. In the "Use item" menu, "Work on craft" is displayed next to the in progress caramel ointment, but, when activated, the only thing that happens is that I receive a message with the text "Your biology is not compatible with that healing item.". There doesn't appear to be any way to continue the craft.

# Steps To Reproduce

1. Create world with the My Sweet Cataclysm mod activated
2. Create character (My character was default except for: Scenario: The Sweet Life, Food Handling: level 2
3. Begin and interrupt the crafting of caramel ointment (In my case, interruption came from crafting failure and missing ingredients)
4. Activate in progress caramel ointment.

# Expected behavior

I expect activating the in progress caramel ointment to continue crafting the item.

# Screenshots

(doesn't seem necessary)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 418b45d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    My Sweet Cataclysm [my_sweet_cataclysm]
]

# Additional context

**Comment by Fris0uman** [comment]
Seems related to https://github.com/CleverRaven/Cataclysm-DDA/issues/41699

**Comment by Fris0uman** [comment]
Can confirm the bug is happening in lastest version
