### ISSUE TITLE
Corpse search 

### ISSUE THREAD

**Issue by comdv** [CleverRaven/Cataclysm-DDA#48965]
# Problem
Probably a lot of people are annoyed or confused by the modern system of death and search zombies.
More precisely, there is no search - all the things that are on the zombie just scatter and fall down next to the body.
The reanimation of zombies creates a rather funny situation when a zombie soldier loses all his armor, but standing up again has the same armor and appearance as before.
Moreover - such a problem leads to interesting situations, such as mass ramming of a crowd of zombies, and the subsequent “cursory” search of the place through the “V”, with the display of everything that fell out.

# Solution
I have a suggestion on how this could be fixed, but I don’t know how hard it is to implement.
I think all of the above written (and unwritten) problems could be solved by adding a “Corpse Search” mechanic that could work similarly to “butchering”.
_How does butchering work?_
After death, we can interact with the corpse in order to dismember it. We see a modal window that offers us a choice of several options for carving - the possibility of doing this depends on the tools we have and a suitable environment (a flat surface, or special racks), and depending on the survival skills we get different items, depending on the corpse we have carved.
The body, in this case, is the carrier of meat, bones, and organs.

**MAIN IDEA**
In the same way, you can also redo the search of the corpse. Now about the flow itself.
The player kills the zombie and sees only the corpse. To see the things that fell out of the zombie, the player must go to the corpse and search it. When searching a corpse (the mechanics of activating something or cutting up a corpse), the player will see a window with a choice of how detailed the search will be - a pocket search, a top coat search, and a detailed search. You can think about this in more detail, it’s not that important right now.
Each of these types of searches has its own spaw_item_group which will be tied to the type of corpse (zombie, in our case).
Pockets search will show only those things that can be in pockets - some small amount of things, gum, cigarettes, cell phones, and stuff like that.
A search of the top layer of clothing will remove the zombie’s outer clothing like jackets, pants, backpacks, and other things.
And a detailed search completely undresses the corpse, taking off all his clothes.
After the detailed search can we change the type of the corpse? So, if the zombie soldier was not mutated into something scarier (such as a kevlar hulk), after the search he can become a normal zombie (or a special naked zombie, which can not be searched again).
Essentially, generating items after a zombie’s death works about the same way - we have item_groups that are tied to a creature and they give us a random set of items when it dies.
I propose to move this issuing of items from the moment of death to the moment of the interaction of the player with the corpse.
Well, and separate how detailed this search can be.
It is also possible to implement the possibility of auto-search of corpses (for example, a surface search of corpses - we do not need to remove the clothes from each zombie?). 

**What might that affect?**
Well, first of all, it will change the priorities of the game itself.
You will probably not waste precious time searching the corpses of ordinary people but will concentrate your forces on searching the “right” zombies. Searching will take time, so now the items dropped out of zombies can not be picked up immediately after their death, it will take time (even the ability to unclip the machine gun from a lying corpse also takes time).
Moreover - search can bring frustration to morale, and also for the search can create a skill, or bind the search speed to any of the existing skills. Perhaps it will increase the chance of finding things, but it can just reduce the time required to search. Maybe add more options for certain kinds of corpses - find hidden pockets, search backpacks, removing weapons (if any) - a lot of options, and most importantly, that zombies will stop throwing all items on the floor when dying.
There will no longer be a situation where there are hundreds of abandoned items in the city, and somewhere wandering zombie soldiers who no longer have on their past outfits.

It is necessary to take into account the damage of corpses - the corpse on which will pass a tank or a heavy machine will be hopelessly damaged, and should be processed this case and when searching the player will find damaged items (can you add minus to morale, for the search of damaged corpses? the sight of brains on the ground, severed arms or ripped belly can shock unprepared person)

# Alternatives
You can consider alternatives with the implementation of this mechanics - bush search works about the same way I suggest: 
1. We approach the bush
2. Press [e]xamine 
3. Confirm action
4. The character spends some time searching
5. Gets some item (or several) 

It's worth noting that the number of loot, if I'm not mistaken, is tied to the skill "Survival". The number of loot may depend on the skills, in the future you can enter some items that would also improve the search for items (or search corpses) - scanners, bionics (sensitive fingers or something like that). 

Also the creation of duplicate corpses without clothes can be solved in more elegant ways than just creating copies of zombies, with less armor and a different description (remove the military zombie mention of his ammunition and clothes, and so on). 
By the way, it seems that for most non-evolved zombies, one type of corpse would do - a naked zombie, or something like that. For mutated and structurally different ones (acid, hulk, and others), you'd have to describe each one.
The question remains open with the bodies of NPCs - how the items will be there, because the NPC already has things that are on him (and they are on it until death) 

An alternative to my approach would be the idea of giving all creatures (who can wear things and clothes) a system similar to the NPC, where we immediately see what the creature is carrying. However, this doesn't solve the problem of all things just scattering to the ground when they die. We should keep the items on the corpse.

# Additional context
I can prepare some mock-ups of what the user-flow might look like when searching corpses - messages with the choice of search type (surface, detailed, and so on), approximate loot, and naked zombies

**Comment by SuddenEyePuncture** [comment]
I hope it would be possible to enable "autosearch" feature, so you wouldn't have to manualy click on bodies, similar to autopulp, autoharvest and autopickup. It would be even better, if you could make a list of mobs you always want to search and assign a type of search to each one of them. Also it would be really nice to pickup things from autopickup list immediately after search.

**Comment by Inglonias** [comment]
A simpler solution, though a little less precise, would be to have reviving zombies take as much stuff as possible from the tile they were on when they revive. The biggest issue there would ne determining which stuff belongs to who when zombies die.

Another possibility would be to make nonpulped corpses into containers that contain all their stuff.

**Comment by DalenTalas** [comment]
> Another possibility would be to make nonpulped corpses into containers that contain all their stuff.

What's to stop clever players from using zeds as containers a-la S.T.A.L.K.E.R., then? Sure, IRL has examples of stuff being smuggled inside stiffs, and this is a post-apoc simulation with *all* sorts of morally questionable possibilities, but...

**Comment by Night-Pryanik** [comment]
I think this is resolved by #58651.
