### ISSUE TITLE
Ak47 reconversion 

### ISSUE THREAD

**Issue by Max-programming-novice** [CleverRaven/Cataclysm-DDA#48978]
My idea is add opportunity to upgrade one mode semi-auto Ak47 into selective fire (semi-auto or full auto) Ak47.

As i know, in real life, semi auto Ak47, after some actions can be reconverted into full auto one, so... Lets add such opportunity to the game (since it has Ar15 full auto reconversion).

Mhm... The way how to make this: just copy Ar15 reconversion, change some things at the Code, add one recipe and voalia full auto Ak47 , that is a bit unwieldy than Akm, is done... 

Just copy and rework drop-in-auto sear of Ar platform (drop in auto seal...)

Sorry.. If i made some mistakes with issue form.

**Comment by faefux** [comment]
Hi @Max-programming-novice. Do you have any good resources of people doing this IRL and specifically ones that show it explicitly to be similar to the current drop-in-auto sear system?

**Comment by Max-programming-novice** [comment]
Ok... So...
As i know civilian versions of full auto rifles hasn't automatic release
system (if they were manufactured as semi auto guns), or if they were
reconverted from full auto to semi-auto this system were blocked...
Knowing that most USA ak47 were manufactured by American companies...
I guess that they was manufactured without auto release...
So as not gun expert, i looked at Ak blueprint and video so... I guess that
they havent auto release (so... https://youtu.be/jHpnhSzovR0).

And it is possible, because Brandon Herrera "unbroke" this Ak...
https://youtu.be/n16Uk8BuALw

https://youtu.be/n16Uk8BuALw

ср, 26 мая 2021 г., 04:37 faefux ***@***.***>:

**Comment by Max-programming-novice** [comment]
> Hi @Max-programming-novice. Do you have any good resources of people doing this IRL and specifically ones that show it explicitly to be similar to the current drop-in-auto sear system?

Ok... So... 
As i know civilian versions of full auto rifles hasn't automatic release system (if they were manufactured as semi auto guns), or if they were reconverted from full auto to semi-auto this system were blocked...
Knowing that most USA ak47 were manufactured by American companies...
I guess that they was manufactured without auto release... 
So as not gun expert, i looked at Ak blueprint and video so... I guess that they havent auto release (so... https://youtu.be/jHpnhSzovR0). 

And it is possible, because Brandon Herrera "unbroke" this Ak... https://youtu.be/n16Uk8BuALw 

https://youtu.be/n16Uk8BuALw

**Comment by faefux** [comment]
Cool, thanks @Max-programming-novice I can try to see the videos and make an approximating recipe. I checked out how the autosear works and as below, it looks like it could _potentially_ be an easy change. :)
`  {
    "id": "dias",
    "type": "GUNMOD",
    "name": { "str": "drop-in auto sear" },
    "description": "This is a vaguely 'U' shaped piece of metal with a vaguely 'T' shaped flapper on a pin.  Once tucked into an AR-15's lower receiver, the rifle will become selective fire-capable.  The handcrafted-sear surface isn't as good as actual full-auto parts, so precision and reliability suffer slightly.",
    "weight": "113 g",
    "volume": "250 ml",
    "integral_volume": "0 ml",
    "integral_weight": "0 g",
    "price": 65000,
    "price_postapoc": 500,
    "material": [ "steel" ],
    "symbol": ":",
    "color": "red",
    "location": "mechanism",
    "mod_targets": [ "ar15", "ar15_retool_300blk", "ar_pistol", "oa93" ],
    "//": "Install time short since it drops in, hinging open the AR being all the 'skill' necessary. Precision drop marginal since it'd change how semi and FA trigger pulls feel.",
    "install_time": "5 m",
    "dispersion_modifier": 10,
    "//durability_modifier": -1,
    "mode_modifier": [ [ "AUTO", "auto", 4 ] ],
    "min_skills": [ [ "rifle", 2 ] ]
  },
`

**Comment by Max-programming-novice** [comment]
I guess yes...
But
1 Be careful
2 Use VPN to watch this...
3 If cops will arrest you, then you don't know me


сб, 29 мая 2021 г., 23:00 faefux ***@***.***>:

**Comment by Max-programming-novice** [comment]
Damn

пт, 2 июл. 2021 г., 16:52 stale[bot] ***@***.***>:
