### ISSUE TITLE
Game crashes when killing monster without "material"

### ISSUE THREAD

**Issue by Saicchi** [CleverRaven/Cataclysm-DDA#48988]
# Describe the bug
Game crashes when spawning monster body without materials.

# Steps To Reproduce

1. Pick any monster with a `NORMAL` death function
2. Remove their `"material"` array.
3. Spawn and kill said monster
4. Game crashes

# Expected behavior

Game does not crash.

# Screenshots
None

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.E-10474-g1ae66c97a0 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]
]

# Additional context

Most likely due to: `src/item.cpp:6895`
```c++
float item::get_freeze_point() const
{
    if( is_comestible() ) {
        return get_comestible()->freeze_point;
    }
    return made_of_types()[0]->freeze_point();
}
```
`made_of_types()[0]` does not exist.

From the stack trace:

```
??:0
item::get_freeze_point() const
??:?
item::set_item_temperature(float)
??:?
item::process_temperature_rot(float, tripoint const&, player*, temperature_flag, float)
??:?
item::process_internal(player*, tripoint const&, float, temperature_flag, float)
??:?
map::add_item(tripoint const&, item)
??:?
 map::add_item_or_charges(tripoint const&, item, bool)::{lambda(tripoint const&)#3}::operator()(tripoint const&) const
map.cpp:?
map::add_item_or_charges(tripoint const&, item, bool)
??:?
make_mon_corpse(monster&, int)
??:?
mdeath::normal(monster&)
??:?
monster::die(Creature*)
...
```

**Comment by ZhilkinSerg** [comment]
material array should be made mandatory or include some default value when it is empty.

**Comment by SariusSkelrets** [comment]
The only monsters without material in game have the MELT death function so they don’t create corpses

When a monster without material leaves a corpse, the game can’t understand which matter must be used. Is the corpse made of stone, steel, flesh, ect.

A default material for monsters without one should work. I thought of an ‘’unrecognizable mass’’ described as useless and hard to describe that could be butchered for useless unrecognizable chunks
