### ISSUE TITLE
Disassembling Some CBMs in Aftershock does not give the expected Aftershock scrap components

### ISSUE THREAD

**Issue by VoidForge** [CleverRaven/Cataclysm-DDA#48986]
# Describe the bug
According to [the item browser](http://cdda-trunk.chezzo.com/bio_power_storage/disassemble), disassembling Power Storage CBM in Aftershock should produce a bunch of scraps, instead of the standard electronic materials in vanilla. Apparently this is not the case now, and disassembly always gives the vanilla components.

# Steps To Reproduce
1. Start a new world with Aftershock enabled.
2. Open the debug menu and spawn a Power Storage CBM.
3. Disassemble it and find that it gives no funny materials which can be used to craft railguns and lasers.

# Expected behavior
Components obtained by disassembling Power Storage CBM (and other CBMs that exist in vanilla and can be disassembled, namely Power Storage CBM Mk II) should be from `recipe/bionic_recipes.json`, not from the boring vanilla recipe.

# Screenshots

![image](https://user-images.githubusercontent.com/21039812/119215480-7e66ea00-bb00-11eb-9945-9071b7d24f4b.png)

# Versions and configuration

 - OS: Windows 10
 - Game Version: 3c13759 (build 2021-05-21-1508) and 07c58d9
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: dda, aftershock

# Additional context
This bug may also exist for other items that can be crafted in vanilla with different recipes.

**Comment by VoidForge** [comment]
Cranial Flashlight, Internal Unified Power System, and Water Extraction Unit CBM also have this problem.

**Comment by hexagonrecursion** [comment]
Confirmed. Power storage gives: solder, power converters, amplifier circuits, a light battery and a burnt out bionic

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: f50b6be [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock]
]
