### ISSUE TITLE
Dehydrated vegetable recipe should ask the player to pick which vegetable to dehydrate

### ISSUE THREAD

**Issue by Warfoniusz** [CleverRaven/Cataclysm-DDA#48994]
The recipe for dehydrated vegetables doesn't ask the player what he wants to dehydrate, so it randomly chooses everything that fits the recipe. It should ask you which vegetables you want to use in the recipe.

**Comment by natsirt721** [comment]
Could not reproduce on 0.E-10606. Spawned a food dehydrator, gas cooker, 3 zucchini and 3 burdock. Interestingly enough there are two recipes for dehydrated veg, with the only difference being slightly higher rated calorie output and reduced crafting time if you have a fire source nearby. Tried both of them with zucchini and burdock in my inventory and it asked me which components I wanted and consumed them as expected. 

Is it possible that you did a batch craft where there was only enough of one type of veg to meet the recipe? e.g. you have 1 burdock and 3 zucchini, if you do a batch of 3 it isn't going to ask for materials.
