### ISSUE TITLE
Monsters guaranteed spawning from "rot_spawn"

### ISSUE THREAD

**Issue by Saicchi** [CleverRaven/Cataclysm-DDA#49001]
# Describe the bug

Monsters have 100% chance of spawning from `rot_spawn`.

# Steps To Reproduce

1. Make a box monsters can't go through with any size.
1. Spawn any amount of **unfertilized** chicken eggs you want, the higher the better, inside the box.
3. Advance time until all eggs show up as rotten
4. Wait a couple turns
5. All unfertilized eggs turn into chickens even though they have a `"rot_spawn_chance": 0`.

# Expected behavior

No chickens should spawn.

# Screenshots
None

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.E-10474-g1ae66c97a0 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]
]

# Additional context

`rot_spawn_chance` isn't used anywhere in the code except for loading. It was removed in this PR #48116

**Comment by Venera3** [comment]
It might be worth a try to check if turning the inheritance around (unfertilized eggs as a base item without any rot spawn info and chicken egg as a copy-from) is enough to band-aid fix it. The fact *every* egg hatches is also a bit concerning, if I had to guess there might be some overwriting or undocumented scaling going on.

**Comment by Saicchi** [comment]
There was a check, it was removed ( accidentally I believe ) when the carrion spawn rate was removed.
`const int chance = static_cast<int>( comest->rot_spawn_chance * get_option<float>( "CARRION_SPAWNRATE" ) );`

**Comment by actual-nh** [comment]
Ping: @MarlossCDDA?

**Comment by MarlossCDDA** [comment]
Hm, yep, that's my fault - should have looked at the actual rot_spawn_chances in the code before assuming they were all 100. Should be able to send a PR fixing it today.
