### ISSUE TITLE
UPS-powered energy weapons error

### ISSUE THREAD

**Issue by AdamChirnside** [CleverRaven/Cataclysm-DDA#49004]
# Describe the bug

When trying to use any UPS-powered weapon, an error is thrown:

>  DEBUG    : can't set ammo null in A7 laser rifle as it is not an ammo
> 
>  FUNCTION : item& item::ammo_set(const itype_id&, int)
>  FILE     : src/item.cpp
>  LINE     : 549

# Steps To Reproduce

1. Make a player with an A7 laser rifle (UPS)
2. Equip it
3. Get near monsters

# Expected behavior

No error message

# Screenshots

N/A

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 9488256 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Disable NPC Needs [no_npc_food],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Alternative Map Key [alt_map_key],
    Cataclysm++ [Cata++],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Graphical Overmap Cataclysm++ [Graphical_Overmap_SDG_Cata++],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Cataclysm++ - UndeadPeople Tileset [Cata++UDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    No Fungal Monsters [No_Fungi],
    Blaze Industries [blazeindustries],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex]
]

# Additional Context

This seems to be a problem with nested container code

**Comment by actual-nh** [comment]
Confirmed - see #45041. #48771 is likely related.

**Comment by AdamChirnside** [comment]
It seems like these weapons simply need to have the USES_BIONIC_POWER flag to fix this. Testing it now

**Comment by AdamChirnside** [comment]
This seems to have been fixed
