### ISSUE TITLE
Can't throw blind while peeking upstairs/downstairs

### ISSUE THREAD

**Issue by Zeropol** [CleverRaven/Cataclysm-DDA#49009]
# Describe the bug

We can't throw blind after peeking upstairs/downstairs.

# Steps To Reproduce
1. Move on a stairs tile.
2. Peek up or down.
3. See you can't throw.
4. Open the keybinding menu while peeking up/down and see there is no entry for blind throw.

# Expected behavior
Ability to blind throw like when we peek on the same z-level.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-10605-gb533bda05d-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context
In `peek()`, if there is a z-level move, the function `look_around()` is called without argument, the last one ( peeking ) default to false. After this, the code don't check if the player tried to throw an item, and return.
https://github.com/CleverRaven/Cataclysm-DDA/blob/b533bda05dda5094f46a561bf297c271f30e1e52/src/game.cpp#L6101

Sorry if my wording is poor.

**Comment by Saicchi** [comment]
Can confirm on `0.E-10474-g1ae66c97a0`
In the `game::peek` function in `src/game.cpp:6103`. When the player is looking at other z-levels it uses the `game::look_around` function without the `peeking` parameter being set to true.
```c++
if( p->z != 0 ) {
        const tripoint old_pos = u.pos();
        vertical_move( p->z, false, true );

        if( old_pos != u.pos() ) {
        look_around();
        vertical_move( p->z * -1, false, true );
        }
        return;
}
```
Passing the parameter to the function should work to fix it, but I have not done any testing on the effects it would cause.
