### ISSUE TITLE
Falling is voluntary.

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#49017]
# Describe the bug

If you climb up to a house rooftop with a reach weapon, and go to the edge, you can attack down if Z-levels are enabled.  If monsters below you destroy the structure you are above, you can continually tab-attack them, even when you have no roof under you anymore.

# Steps To Reproduce

Have a reach weapon.  
Climb a downspout.  
Go to edge of a roof.
Have a few hundred enemies that destroy things at ground level.
Hold Tab.

# Expected behavior

Falling.
Barring that, maniacal laughter after consuming an energy source larger than my head.

# Screenshots

I only remembered that this happens while reading the levitating bandits bug(s).

# Versions and configuration

Win 10
2021-05-20-2005
Tiles
English
Various mods, but this seems game-engine related.

# Additional context

N/A

**Comment by actual-nh** [comment]
This has been a problem for a while - see #47951.
