### ISSUE TITLE
Reptiles (including dinosaurs) should not have GOODHEARING

### ISSUE THREAD

**Issue by actual-nh** [CleverRaven/Cataclysm-DDA#49011]
According to <https://www.nature.com/articles/d41586-019-03170-7>, which accords with what I know of the subject, reptiles - including dinosaurs - should probably not have GOODHEARING, at least in comparison with mammals. This primarily affects DinoMod, although mon_gator is also affected. 

# Steps To Reproduce

N/A.

# Expected behavior

Logical replacements - when desired - are adding KEENNOSE or increasing vision_day and/or vision_night. (Vision boosts are more suitable for flying dinosaurs, for instance.)

# Additional context

I'll do a PR for this soon - wanted to get feedback, mainly on replacements and when they're desirable. BTW, how the middle ear bones help is mainly by leverage - they take the short-distance but more-powerful fluctuations at the eardrum and convert them to longer-distance but less-powerful fluctuations at the much-smaller oval membrane, which leads to the cochlea in the inner ear. (I say "mainly" because a couple of muscles there can help against overly-loud noises... if the reflex happens in time!) The article is a bit confusing regarding the "ectotympanic" bone - in humans, it's fused with the rest of the skull; the third middle ear bone in humans is the stapes.

Ping: @LyleSY, @ephemeralstoryteller, @damien, possibly @Venera3?

**Comment by LyleSY** [comment]
Thanks, didn't see that.

Really it depends what GOODHEARING is intended to model. I think we (I maybe?) only gave it to some of the raptor family because they had good hearing for a dinosaur, but not for like a bat or owl. See this for example https://www.discovermagazine.com/planet-earth/nocturnal-dinosaurs-night-vision-and-superb-hearing-in-a-small-theropod

I have no big feelings either way from a gameplay perspective. We're not doing  a ton with raptors other than the dino exhibit but maybe we should.

**Comment by actual-nh** [comment]
(BTW, good to "see" you around, @anothersimulacrum!) I've tried to take a further look at this, but so far all the journal articles I've been able to locate are behind paywalls (sigh...). I was trying just directly from the Discover article, however, and I'm going to try taking a look at what cites those this weekend or week.

**Comment by LyleSY** [comment]
Yeah, I get 16 hits when I search for GOODHEARING on the dinosaur monster file. That's definitely too much. If there should be any, it should probably just be night hunters https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/mods/DinoMod/monsters/dinosaur.json

**Comment by actual-nh** [comment]
I had been taking a look at some articles on this. There are several groupings:
- Archaeopteryx (and, to a lesser extent, its closer relatives) seems to have likely had hearing abilities about at the bottom end of the range for modern birds (similar to the emu) - rather far from the really good hearers among the birds (owls, etc).  Pterosaurs, OTOH, seem to have more been using their ears for balance during flight, from what areas are largest; they probably didn't hear better than a crocodile, which isn't very good.
- Mammalian ancestors (and related) - therapsids - likely did have good hearing starting pretty far back, although probably not the ground-hugging or burrowing ones - they likely were using their hearing to sense ground vibrations (which also indicates specialization for lower frequencies).
- The sauropods, hadrosaurs, and I suspect other really big ones were likely pretty deaf to high-range frequencies.
- Mosasaurus and other aquatic ones didn't have good hearing, interestingly - probably partially due to jaw adaptations. It was likely better for underwater than air, but that's uncertain. 
- Non-avian theropods are uncertain; some of them may have had decent hearing.
- Night-hunting critters having had good hearing is quite reasonable; among lizards, the ones with the best hearing are geckos - which are the only night-hunting (modern-day) lizards.
