### ISSUE TITLE
Book learning while skill disabled prevents future learning.

### ISSUE THREAD

**Issue by Psiclops** [CleverRaven/Cataclysm-DDA#49021]
Disabled vehicle skill to prevent focus loss while driving. Reading a book about vehicle skill should ignore this, but instead it says "You learn a little about vehicles! (-1342090%)
"You learn a little about vehicles! (-1342083%)

Upon re-enabling the skill and trying to read the book again it continues to show negative increase and will not improve vehicle skill.

Considerable amounts of additional driving with the skill re-enabled also does not result in any vehicle skill improvements. Skill remains at 3(0%) after a hour of ingame driving around.

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: b6c4ce5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm]
]

**Comment by Saicchi** [comment]
This doesn't seem to be an issue about books.
It's more of an issue with negative skill experience. I've seen it quite a few times before but I haven't seen an open issue now do I know how to replicate it.

**Comment by Night-Pryanik** [comment]
Can't confirm on latest experimental as of 12 November 2024. 

Disabling a skill and reading a book about that skill shows correct numbers in message log.
![изображение](https://github.com/user-attachments/assets/04c7129a-6e80-444d-8140-762fe0658f52)
