### ISSUE TITLE
Feature Request: Expansion of Old Guard faction

### ISSUE THREAD

**Issue by faefux** [CleverRaven/Cataclysm-DDA#49034]
# Is your feature request related to a problem? Please describe.
I always feel that the Old Guard would have a larger presence in the area due to being remnants of the state and military which has banded together. USA traditionally has a very decentralized military with a large fleet bases all over the country in the name of the National Guard as well as over the rest of the world/continent and a very militarized police force.  It stands to reason they could potentially still be a strong force, even if highly dis-unified. The problem being that power block aside of 5 mission from the representative is lacking. 

# Describe the solution you'd like
The solution as i see it is to create an Old Guard space. Ideally how I would like it to work is to do a mission for the representative which will lead to a more Established Old Guard position on the overmap in the form of a re-occupied military structure.  I've personally been looking at the helicopter pad map but would love to here others feedback on it.

As an aside I also think it could be a place where one could learn to fly helicopters as there is nobody else in game that teaches it. Although I am not sure the current teaching mechanics are suited for teaching such a complex skill in the respects that it will simply be taught to fast.

# Describe alternatives you've considered
I was first considering adding more old guard NPC's in to the FMC building but A this building can be a strain on CPU with all the NPC's and B. the FMC just accepting the extra bodies in there already crowded building does not seem to fit with the current social landscape there.
Currently to me the beginning PR will look like this: 
1. Old Guard representative tells (not asks. You are a marshal now. In there employ.) you to go and clear our a helicopter map
2. Destroy the 4 turrets and collected a piece of data from a terminal on a new variation of current helipad map 
3. Return to Representative (that guy really needs a name) for to finish. On mission complete OG owned soldiers, safe turrets and military vehicles are spawned on the helipad map.
4. Representative tells you the base has been designated as a Forward Operation Base and orders you to return with a package of FMCNotes. (An opportunity for players to play the 'bad guy' and cut and run at the expense of a faction turning against them)

# Additional context
That it is, it is just a rough idea and an early version of the helipad map converted as a Forward Operating Base so far. I think it would be a good vehicle for expanding the players understanding of the world around them as well as a branch for end-game high risk quests and and faction conflict both internal and external.
And here is a mock-up in mapgen of the helimap slightly extended and how I think it could look in the first iteration of the Guard moving in. The plan would be for the base to become more pieced together and formidable over time... As long as nothing bad happens to it.. ;) I'd appreciate alternative ideas for how the map should look.
![image](https://user-images.githubusercontent.com/49350286/119621921-94c1be00-bdfe-11eb-9f9b-7eee379636ea.png)
![image](https://user-images.githubusercontent.com/49350286/119622292-ef5b1a00-bdfe-11eb-9d67-48487535c147.png)

**Comment by SariusSkelrets** [comment]
If you want the old guard to give a mission about killing people while including a moral dilemma, the Isherwood familly look like a valid target for them

They’re no bandits but will shoot on sight anything related to the old guard and will reject players wearing marshall badges. They’re innocent people just trying to survive that hate the old guard. 

It forces the player to choose between the factions: who will you help? An innocent family, or the remain of the american military?

**Comment by PatrikLundell** [comment]
@SariusSkelrets 
No, it isn't a moral dilemma for those that don't meta game. If you don't meta game (or just haven't encountered Isherwood, like myself) before you encounter the old guard and perform their quests you encounter another set of bandits that, according to your description, shoots at you on sight. My character has encountered other bandits that shoot on sight, and I've just ignored them as I don't really care to take the risks involved in engaging them (not quite true, as I've led zombies to them when trying to clear out the neighborhood in one case), but wouldn't think twice about eliminating them if given a good reason for doing so. It only becomes a moral dilemma if you have a reason to believe they just want to be left alone but aren't bandits or otherwise an expanding threat, and to set up such a situation you'd have to provide the player with info that informs the player of it, as I'm fairly sure the military won't tell you.

If, on the other hand, you encounter Isherwood first, they'd have to provide a really compelling reason for the player to attack the military rather than just not perform an extermination quest given (and a meta gamer can easily do that by just not following the quest chain beyond the quest prior to that one, while one who doesn't may either be rejected by the military [which is reasonably OK], or essentially get ambushed by the game as they're attacked by the formerly friendly force in what essentially is an ambush created by the game [which is a disgustingly horrible {and common} plot device even in games that don't frown upon reloading saves]).

**Comment by SariusSkelrets** [comment]
The Isherwood only rejects the player if they wear a marshall badge and won’t attack unless provoked 

AFAIK they won’t ask you to attack the old guard, it’s just that the guard is in the kill_on_sight section of the Isherwood faction

If the old guard asks you to get rid of this family, they might force you to choose between them and the family if and only you’re spotted interacting with the Isherwood or refuse the mission

The Isherwood rewards includes a small building made for you, a horse and the possibility to recruit some NPCs. It’s quite useful

If the old guard decides to kill you, it won’t materialize soldiers out of thin air. The only time it should happens is for mission targets and summoning abilities 
They would pass the message to their existing forces

**Comment by PatrikLundell** [comment]
Unless the old guard informs the player that the Isherwoodians are hostile to them, and the Isherwoodians refuse to have anything to do with the PC if wearing the badge without telling the PC why, the non meta gaming player won't know what's happening (although it's better than just being shot at out of the blue, of course).

I'm fine with "being forced to chose" if it includes the option of cutting them both off without getting into an active war against either of them (I have no sympathy for assholes who demand that either you're with them and participate in their wars/hate campaigns [e.g. against former partners], or you're the enemy and should similarly be targeted).

Unless horses are overhauled they're essentially useless, as they were too weak to carry a weakish normal (non mutated) armored human when I tried. However, I guess that if the quests are sufficiently easy to perform that you can do them before getting a vehicle (or a horse), a horse might have a little value for some time (and can be turned into food, if nothing else). New companions, however, may be useful, while a building may be less so, as I assume it can't be turned into a base camp, but, again, it depends on how early you encounter them. 

If the establishment of a new old guard base involves gradually building up of the base through quests, turning down a quest in the middle of the now built up base won't require the teleporting of soldiers to screw you over completely if it's automatically turned into war, as you'd be surrounded by the soldiers that have been moved in as a result of the base being built up, as I assume you'd conduct this conversation with the quest giver inside the base (a way out of that might be if the quest giver would contact you over radio for that quest).

**Comment by faefux** [comment]
@SariusSkelrets @PatrikLundell 
Re Isherwoods: I was thinking that the big conflict to begin with could may be the Lab faction, it was previously Government property and they were researching the blob, etc. I'm not sure what that conflict would look like but the stages are pretty large. I cannot really see a decent scenario where the family and guard have an issue that resorts to sending the player on a murder-mission. 
Not that i'm against anyone else writing it, it is just perhaps behind my ability to write a compelling story of a conflict between the Isherwood and Guard. Maybe if we want interaction between the two the play could be asked to mediate between the two factions who have little trust between each other for a mcguffin; artifact, a member of either sides prisoner or corpse or some-such. (maybe the guy who got captured by the migo could have been captured now by the guard, a little joke about his bad luck) We only have one mission where you Use your words instead of your steel and this could be a good reason for that.

**Comment by actual-nh** [comment]
Old Guard to Lab: "We funded you, and you turned around and wrecked the world!"
Lab to Old Guard: "You were the ones pushing for more and more, and backing up the higher-ups who were doing the same (and making money on the side) while turning a blind eye to their crimes."
Isherwoods: "You're all to blame; screw all of you." (With the exception of Melchior at the Lab, who can't exactly be blamed for what ?his? creators did, I think they've got it right...)

**Comment by faefux** [comment]
> Old Guard to Lab: "We funded you, and you turned around and wrecked the world!"
> Lab to Old Guard: "You were the ones pushing for more and more, and backing up the higher-ups who were doing the same (and making money on the side) while turning a blind eye to their crimes."
> Isherwoods: "You're all to blame; screw all of you." (With the exception of Melchior at the Lab, who can't exactly be blamed for what ?his? creators did, I think they've got it right...)
Right. I feel like there is more room for other factions who believe the same as the Isherwoods too, as it would be a comon opinion even before the act that everyone is considerably more rash and hot headed after <the_cataclysm>.  Long term I think it'd be great to see more and more micro-factions.

**Comment by faefux** [comment]
> You're not in the employ of someone if that someone doesn't pay you some kind of salary. It's more of an honorary title like being knighted, which doesn't actually provide any real benefits, nor any real obligations. At best you're a somewhat trusted free agent (which is probably the best status for a player character anyway, as you don't actually want the PC to be under the direct command of others [unless you can somehow set up a slave scenario you're trying to escape from, but that shouldn't be the case here]).

I am thinking, tell me if it's to much, but after a certain point with factions (say, 4 or 5 missions and especially for the military) they will start to think more negatively of you if you do not assist them in there requests when asked. It seems like a good trade off to me.

> Another cue I'd take from the Tacoma farm implementation is to use a "unique" fairly large location for it to ensure it can be expanded in the way you envision. This may well "start" with a helicopter base or a military bunker and then gradually grow with additional facilities.

I was thinking the same too. Currently the map will be 4x3 and have a bunch of fields around it before spawning in the forest probably. I think that will be enough for now at least. :)

>  i.e. have the Representative send you to clear out a place on behalf of someone higher up that's recently established contact with him, then have the old guard gradually establish themselves in these facilities, with the boss of that location taking over in giving you quests (although it wouldn't rule out the appearance of some new quest from the Representative at a later time). This seems to be in line with what's suggested.

It's pretty difficult to write a mission around actually going to clear an area out and cannot really be done very organically, I think the best we can do currently is set one monster as a target and put it after a bunch of others. For this I have created unique turrets that are functionally identical to others but drop a mcguffin and another mcguffin dropped by a zombie in the building.

**Comment by PatrikLundell** [comment]
I find it quite reasonable that the old guard may cut you off if you don't perform their missions within a reasonable time, although it's probably difficult to determine what a "reasonable time" is, as you may start the quest chain as a reasonably fresh character who's just managed to perform the Representative quests, or someone who's well established with high quality gear and vehicles.

Well, placing a monster or bandit (with its associated horde members) at the target location and then target that monster counts as clearing an area in my book (I meant clearing it out of opposition, not clearing the ground of trees and shrubs).

I can certainly see that various factions that previously worked together start to blame each other when things go pear shaped. I don't think those who hate technology (or whatever) would, generally, be clear headed enough to consider Melchior free of blame, regardless of the extent to which it actually was involved. If nothing else, I suspect they'd see it as the spawn of evil (with or without religion attached).
Given that both the military and the lab faction seems to have been completely unhinged and probably would have had any dissenters turned into test subjects, any reason to be found from those factions would probably come from people who very cautiously start to steer things into a less extreme direction once the iron fist(s) has crumbled (which, I admit, would allow for an immediate call for execution of the traitors who don't unquestionably and immediately perform requested quests, but I still don't think that would result in good game play).

**Comment by leemuar** [comment]
I like the idea. I suggest to use a more "complex" building for the main base of Old Guard. A prison or some military base might be better. imho helipad is too small for it.

**Comment by PatrikLundell** [comment]
The starting configuration isn't actually that important in there is an expansion that adds new structures to the base. I haven't looked at how the Tacoma farm goes about its expansion, but it adds new buildings and associated people to an existing set of starting buildings, and I assume the same ought to be possible here.

One thing I forgot to comment on earlier is that I think it's important for the location to have a road leading to it. This is both for the convenience of the player and for the expansion of the base itself, as I would expect it to mainly use land vehicles beyond a possible establishment of a presence, as, logically, running everything using helicopters would consume an enormous amount of fuel, which is a resource that ought to be in limited supply (diesel is limited as well, but ground vehicles generally use less [although tanks aren't exactly noted for their fuel economy, I expect even them to use less fuel than a military helo], and it can be produced with post apocalyptic technology [assuming the old guard hasn't captured oil wells and refineries and managed to keep them running, somewhere off the map]).

**Comment by faefux** [comment]
Just my thinking on some maters:
> although it's probably difficult to determine what a "reasonable time" is, as you may start the quest chain as a reasonably fresh character who's just managed to perform the Representative quests, or someone who's well established with high quality gear and vehicles.
Very good point. I think at least to begin with it would be good to give times that were very permissive as long as you don't spend weeks off doing other things as well as very clear how long the window of opportunity is for the thing. Such as "We need this done in the next four weeks." (for the sake of argument), a time long devise some sort of real plan if under-powered for whatever it is. I also considered a vehicle could actually be a quest reward from the Old Guard. a humvee that's pretty undamaged with decent amounts of ammo or something. Preferably I'd like to leave this all until they're actually in the game though. I think to begin with it should just be basic mobs in the map who say hi, etc. as i'd like to get the beginngs up before getting bogged down in trying to develop characters and write dialogue for them.

> 
> Well, placing a monster or bandit (with its associated horde members) at the target location and then target that monster counts as clearing an area in my book (I meant clearing it out of opposition, not clearing the ground of trees and shrubs).

The problem is that you can only target a single monster in a mission, for example if you have 3 mobs targeted in the mission then any one of those mobs killed will result in the mission being complete, in this scenario for example if you destroy one turret it would leave 6 more to rip up any new NPC's spawned there.  I am not certain if it is a bug or working as intended but I suspect the latter.

**Comment by faefux** [comment]
> The starting configuration isn't actually that important in there is an expansion that adds new structures to the base. I haven't looked at how the Tacoma farm goes about its expansion, but it adds new buildings and associated people to an existing set of starting buildings, and I assume the same ought to be possible here.
> 
> One thing I forgot to comment on earlier is that I think it's important for the location to have a road leading to it. This is both for the convenience of the player and for the expansion of the base itself, as I would expect it to mainly use land vehicles beyond a possible establishment of a presence, as, logically, running everything using helicopters would consume an enormous amount of fuel, which is a resource that ought to be in limited supply (diesel is limited as well, but ground vehicles generally use less [although tanks aren't exactly noted for their fuel economy, I expect even them to use less fuel than a military helo], and it can be produced with post apocalyptic technology [assuming the old guard hasn't captured oil wells and refineries and managed to keep them running, somewhere off the map]).

All good insights and I will consider all this certainly! I was actually considering around putting some more spawns for JP8 fuel and others in the game with many of the at least early missions for the base being centered around logistics and supply. I am assuming they come with food, weapons and bullets and more medical supplies than most but would need help from a local deputy like our player character to aid in collecting things like diesel for the humvees, tanks and generators, regular helicopter fuel and the JP8 stuff.
