### ISSUE TITLE
Idea: give long weapons reach aka spears are cool [$5]

### ISSUE THREAD

**Issue by NaturesWitness** [CleverRaven/Cataclysm-DDA#4903]
It's always struck me as odd that we don't have melee weapons that can hit more than one square away.  In a lot of other roguelikes, weapons like spears and polearms give you the ability to hit enemies from a few squares away.  Is there any chance we could add this kind of function to Cata?

**Comment by happypandaface** [comment]
if you have a rifle with a bayonet, and you press 'f' and select a monster you could both shoot or stab, it could just ask you which one you wanted to do in a window like when you activate a knife or when it asks you if you really want to sleep.
