### ISSUE TITLE
Feature request: Straw (and similar) pillows

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#49031]
There are currently two type of pillows: The ones filled with downs and the ones filled with cotton.

It would be great if there are pillows which can be filled with straw and other similar fillings. As stated in the [wikipedia article about pillows](https://en.wikipedia.org/wiki/Pillow#Construction_and_parts), one of the possible fillings is straw. [Apparently you can also stuff buckwheat in pillows](https://en.wikipedia.org/wiki/Buckwheat#Upholstery_filling).

I am doing a wilderness run (rural mapgen and city size set to 0) and downs/cotton are very hard to find but straw and withered plants are not. A possible recipe would be a few rags, straw/withered plants/pine boughs and a bit of thread/plant fiber/sinews/... to sew it shut.

It is of course not as comfortable as a "real" pillow but better than nothing. A simple makeshift pillow would also be way easier to make in bulk for e.g your followers.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/living-off-the-land-rural-only/26691/1
