### ISSUE TITLE
Feature Request: Items longer than pocket maximum length allowable with chance of dropping

### ISSUE THREAD

**Issue by TobalJackson** [CleverRaven/Cataclysm-DDA#49032]
The current pocket system imposes a maximum length of objects allowed inside a pocket which makes sense for most cases where you want/need the pocket/container to be securely closed. However in a situation where I'd like to carry something that's just *slightly* over the maximum length allowed (say 2-3 inches), I feel as if I should be able to with a very small chance of something going wrong (like the item falling out).

Therefore, I'd propose the following change:
* Allow items longer than the pocket length into the pocket with a chance that it could fall out
* make the chance dependent upon how much longer the item is than the maximum length

For example, if I wanted to put something like a crowbar into a backpack (I don't have the exact numbers) but say the crowbar is 23" and the backpack's maximum is 20", then the crowbar would have a ((23 - 20)/20) / 2 == 7.5% chance of falling out every N turns.

* A future enhancement may even to be to tie the chance on the activity being performed:
* walking == x / 4
* running == x
* standing still == x / 20
* attacking == x * 1.5
* being attacked == x * 2

My rationale for the percentage being divided by two is the idea that an upright object (that has its mass evenly distributed along its length) with 50% of its length protruding from the top of a backpack storing it is essentially balanced at its midpoint, and ready to tip the containing object over and then fall out, so something like 50% chance to fall out. More concretely, a 40" object in a container that can hold 20" objects is 100% over length, so ((40 - 20) / 20) / 2 == 50% chance to fall out base. 

I think the activity-level modifications as indicated above could be tweaked or adjusted to balance usability or risk vs reward, or even implemented later than the initial implementation since completely disallowing an object that is 1" over max length feels too restrictive at the moment.

**Comment by Saicchi** [comment]
How would this work for open containers, like pots and frying pans, and for pockets that can contain liquids, like water bottles or body bags? 
Would liquid spill if I put a scalpel ( 10 ml with 13 cm length ) inside a steel bottle with alcohol ( holds 750 ml with maximum item length of 12.7 cm )? 

Also your mesurements are in inches, but how would they work in metric units?

**Comment by TobalJackson** [comment]
I was planning on excluding anything that can be sealed (or water-tight, I forget which; essentially things made for liquid) initially. I haven't looked at the code for this game in a while, and also haven't actually looked at the pocket code at all yet. if there's a way to apply this to a large swath of most common use case, I'd try implementing that first, and work on edge case scenarios or broad-yet-unconventional (like wanting to use a water bottle as a chopstick holder) cases.

As for the metric/imperial question, I'd only be considering the ratio of `(item length - pocket length) / pocket length` and which dispenses with the units.

Also, I didn't think you could mix objects and liquids in a container, but I could be wrong. I'm planning on taking a concerted look at this this weekend after I've played a bit more with the current experimental and gotten a better grasp of things I might wanna change.

**Comment by ZhilkinSerg** [comment]
> Also your mesurements are in inches, but how would they work in metric units?

Ratios are the same whichever system you use.

**Comment by Saicchi** [comment]
> Ratios are the same whichever system you use.

I assumed the `20` used as divisor was a constant number, not the `pocket length`.

**Comment by SariusSkelrets** [comment]
There’s a problem in the formula:

If the crowbar only sticks out by one centimeter and is the only thing sticking out, it shouldn’t fall no matter what happens

The formula needs a buffer where the object can stick out but won’t fall

**Comment by TobalJackson** [comment]
I'd definitely assumed the formula would need to be tweaked pending play testing, however after speaking with a few others as well as taking into account the point raised by @SariusSkelrets , I'm thinking of the following:

* Up to X% of the item can be sticking out of the container with no chance of dropping (say 5, 10, 15% or similar small amount). * Instead, the (slightly) protruding object will add penalty encumbrance, much like wearing extra pieces of equipment on the same layer.  This will encapsulate the idea that objects over length limit will get in the way and generally make using/wearing the containing container harder.
* Only after this lower limit on protrusion length will dropping the item become possible, and even then, the chance will be much greater when performing strenuous activity (walking < running < getting attacked < attacking)

I have still yet to open the code and take a look at what needs to be changed to make this happen, but I'm planning on doing that this weekend. Thank you for your feedback and consideration of this change.

**Comment by chrispikula** [comment]
How do you envision this working with nested pockets?

**Comment by andrei8l** [comment]
If your item is sticking out, then its container must not be closed off completely. That puts all contained items at risk of falling out, depending on their size, weight, or the container's aperture type and fastening strength, orientation, item stacking inside the container, etc... You'd have to consider all these factors (and provide mitigation possibilities) or else you're trading one abstraction for another and frustrating the player with random spills hidden in the typical log spam.

Or you can find a rope and stick the item in the rope since [we have that option now](https://github.com/CleverRaven/Cataclysm-DDA/pull/45916).

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
