### ISSUE TITLE
(Dark Days of the Dead) Even if the mi-go are blacklisted, you can try to start as a captive

### ISSUE THREAD

**Issue by SariusSkelrets** [CleverRaven/Cataclysm-DDA#49056]
# Describe the bug

Mods: Even if DDoD blacklists all alien species and locations, you can choose the mi-go captive scenario.

Doing that prevents the game from starting as it failed to find a valid location

# Steps To Reproduce

1. Create a world with Dark Days of the Dead
2. Choose the mi-go captive scenario and start the game
3. See the message that indicates that the game failed to start

# Expected behavior

You can't be kidnapped by aliens that doesn't exist so the option isn't available with the mod

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-9280-g9dde4db-dirty [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: 
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Dark Days of the Dead [classic_zombies]

**Comment by actual-nh** [comment]
See <https://github.com/CleverRaven/Cataclysm-DDA/blob/0.F-dev/data/mods/aftershock_exoplanet/setting_blacklists/scenario_blacklist.json> for scenario blacklists - not sure if they work currently in master (as opposed to 0.F-dev), however.

**Comment by actual-nh** [comment]
Ping: @I-am-Erk, BTW?

**Comment by I-am-Erk** [comment]
Yep that shouldn't happen.
