### ISSUE TITLE
Option to set the top speed when autodriving

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#49058]
# Is your feature request related to a problem? Please describe.
Even if you have driving skill at 10, the autodrive still colides with obstacles, cars, trees close to the side of the road...
When I speak of autodrive, I mean shit-W shift-W while in map mode (on an azerty kbrd).

# Describe the solution you'd like
An option or conf file that enables you to set the autodrive speed as a % of the vehicle max speed or as a speed limit. If I could I would probably autodrive at 6 or 12 mph in order to save fuel as well as giving me time to stop in case there is an obstacle.

**Comment by RoyBerube** [comment]
The development string freeze makes it hard to do for now.  The player will need some new text and I can't find any appropriate current text that can be reused for this.

The idea is good. It would be even better to fix the autodrive pathing to avoid running into things; it is not trivial.

**Comment by anothersimulacrum** [comment]
Autodrive has since learned to drive https://github.com/CleverRaven/Cataclysm-DDA/pull/49772
