### ISSUE TITLE
Dropping an Item Crashes the game

### ISSUE THREAD

**Issue by SummGai** [CleverRaven/Cataclysm-DDA#49050]
When I drop things the bug crashes

# Steps To Reproduce

<!-- Steps to reproduce the behavior:
Drop something

# Expected behavior

I wanted to drop something without the game crashing to desktop

# Versions and configuration

<!-- Please complete the following information; you can now go to:
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: d1797d9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Engineering essentials [EngineeringEssentials],
    MST Extra [MST_Extra],
    Packaging [Packaging],
    More Survivor Stuff [more_survivor_stuff],
    Mythical Martial Arts [MMA],
    Caches [P_Caches],
    Tankmod: Revived [Tankmod_Revived],
    Clean CBMs [clean_cbm],
    Disable NPC Needs [no_npc_food],
    Faster Stamina Regen [stamina_regen_buff],
    Fuji's Military Profession Pack [fuji_mpp],
    Mutation Changes [Mutation_Changes],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    Portable Autodoc [portable_autodoc],
    Safe Portable Autodoc [safe_portable_autodoc],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    MST Extra - UndeadPeople Tileset [MST_ExtraUDP],
    Mutation Changes - UndeadPeople Tileset [Mutation_ChangesUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP],
    Tankmod: Revived - UndeadPeople Tileset [Tankmod_RevivedUDP],
    Arcana and Magic Items [Arcana],
    Arcana - UndeadPeople Tileset [ArcanaUDP],
    Cataclysm++ [Cata++],
    Cataclysm++ - UndeadPeople Tileset [Cata++UDP],
    DinoMod [DinoMod],
    DinoMod - UndeadPeople Tileset [DinoModUDP],
    Magiclysm [magiclysm],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    My Sweet Cataclysm [my_sweet_cataclysm],
    My Sweet Cataclysm - UndeadPeople Tileset [My_Sweet_CataclysmUDP]
]

# Additional context
any item dropped period crashes the game regardless of what, how, where, or why.

<!-- Add any other context about the problem here.
config+debug
https://mega.nz/file/yBYw3JwD#yRJ_GGIH1aaktIU7aS3pwxvjFvn_UGRBWIAo5LEXjy8
save
https://mega.nz/file/bdASyZAb#iwJ7do8N9pqRzN3iA1fOI2KRHiOg7py3Fz66nxEqOAQ

**Comment by SummGai** [comment]
https://mega.nz/file/bdASyZAb#iwJ7do8N9pqRzN3iA1fOI2KRHiOg7py3Fz66nxEqOAQ
save

https://mega.nz/file/yBYw3JwD#yRJ_GGIH1aaktIU7aS3pwxvjFvn_UGRBWIAo5LEXjy8
debug+config

**Comment by SummGai** [comment]
[Uploading crach files.zip…]()

**Comment by actual-nh** [comment]
> I had the same issue in 2021-05-28-1029 build. The issue was resolved by reverting back to at least 2021-05-24-0603. Other intervening versions might also be without issue but I didn't test them.

OS? (@SummGai, version and OS?) And dropping what/when? Anything/anytime?

**Comment by chrispikula** [comment]
I had the issue when dropping cash cards, as well.
windows 10 build 2021-05-28-1029.

**Comment by OldFriendEr** [comment]
Dropped a book and also a crashed on windows 10 build 2021-05-28-1029

**Comment by Daimiou** [comment]
This crash started happening to me on the 2021-05-23-0814 build.

Running somewhat heavily modded build, game was running without issues for a while (17+ days in game) and then suddenly started crashing when I tried disassembling my car (then tested by just dropping a random item with the same result). Cannot confirm if it was right after updating to 0814 or just started randomly for whatever reason since it's been a while and I do not remember.

**Comment by Taichi22** [comment]
Happened when dropping a first aid kit on windows 10 2021-05-28-1029 build. Didn't happen when dropping plank, so maybe it's something to do with nested items? Unsure.

**Comment by actual-nh** [comment]
Has anyone seen this on a non-Windows OS, or should I attract the attention of Windows-knowledgeable folks with an OS: Windows tag?

**Comment by FeelsBadMatey** [comment]
Pull request already opened, but-
Happened when dropping a "file" item as a Career Politician. Windows 10, 2021-05-28-1807.
