### ISSUE TITLE
Can't take photo of NPC

### ISSUE THREAD

**Issue by Tairesh** [CleverRaven/Cataclysm-DDA#49064]
# Describe the bug
Every time you trying to use a camera on NPC you got a selfie or a photo of the floor.

# Steps To Reproduce
1. Start scenario "Evacuee" with profession "Photojournalist" on default settings or just spawn NPC and professional camera through debug menu.
2. Activate the camera and select tile with NPC
3. Check the message in the log that says "You took a selfie" and a photo in the camera's memory is the photo of you or "You took a photo of the floor" and a photo is the photo of the floor. As I see it becomes a selfie when NPC is in less than 3 tiles apart from you and a photo of the floor if it in more than 3 tiles.

# Expected behavior
Photos of tile with yourself should be selfies, photos of tiles with NPC should be photos of that NPC. if you with NPC are close enough it should be a selfie with NPC, it works with monsters.

# Screenshots
![image](https://user-images.githubusercontent.com/1105196/120061628-892cfc00-c077-11eb-8947-e4267002ea96.png)

# Versions and configuration

 - OS: Linux Mint 20
 - Game Version: 0.E-10361-gfa0b7d6
 - Graphics version: Tiles
 - Ingame language: English/Russian
 - Mods loaded: [ "dda" ]

# Additional context
As I hear it's a very old bug. There is my save with a photojournalist and NPC around: [empty.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6564174/empty.zip)

**Comment by Tairesh** [comment]
As I can see in code, camera doesn't know about NPC, it checks only player and monsters on the way:
https://github.com/CleverRaven/Cataclysm-DDA/blob/9e12cf51f4cea5818894b012d6a1b3ea902d5fa5/src/iuse.cpp#L7500-L7502

**Comment by ZhilkinSerg** [comment]
> 
> 
> As I can see in code, camera doesn't know about NPC, it checks only player and monsters on the way:
> 
> https://github.com/CleverRaven/Cataclysm-DDA/blob/9e12cf51f4cea5818894b012d6a1b3ea902d5fa5/src/iuse.cpp#L7500-L7502

```
Creature -> Character  -> player -> npc
                               |
                               \--> avatar
```

**Comment by Tairesh** [comment]
> Creature -> Character  -> player -> npc
>                                |
>                                \--> avatar

Oh, I see they are the `<player>` too. I found that in function `photo_def_for_camera_point` in similar code it checks for `<avatar>` not `<player>`, probably it's the place where it skips NPCs.
https://github.com/CleverRaven/Cataclysm-DDA/blob/9e12cf51f4cea5818894b012d6a1b3ea902d5fa5/src/iuse.cpp#L7077-L7078

**Comment by Salty-Panda** [comment]
I can confirm the issue, for experimental somewhere between Feature Freeze and String Freeze.
