### ISSUE TITLE
FeRq / What can be done about sight distance and visible details? (completely game-changing)

### ISSUE THREAD

**Issue by Anaglyphic** [CleverRaven/Cataclysm-DDA#49076]
So my bike got gakked by some zeds when I was sleeping. Engine and both wheels are intact but the battery is \*draining\* and I'm mechanics 0 not the required 3 to repair it, nevermind I don't yet have a torch or welder. I know at stores with parking lots there's a good chance for bikes. I find one. 

I'm walking up to snag this motorcycle's battery, _which I spotted from **25 tiles away** across the parking lot_, and could see it had some charge and was undamaged... even though anyone who's _seen_ a motorcycle knows most are under the seat or behind a side panel and not visible even standing next to the bike.

As I approach, I look up and see, through a partially obscured window two buildings away, a tiny slice of visibility through said window onto a row of bookshelves, 36-38 tiles away, which I can tell from, again, _**36-38 tiles away**_, contains books I haven't read, and crazier than that, I can _see through_ those books and shelves to the other side of the book shelf, and it's readily apparent there's a book I've already read at least once and two I haven't. You see that semicolon down next to the terminal at almost the edge of the vision circle in the lower right? I can spot a coffee maker in the shadows on the counter, across the entire freaking bookstore, **_49 tiles_** distant from my vantage point. Mmmm I want a coffee.

I know changing this could change the whole feel of cdda, but for a game of discovery? 
**A lot is auto-discovered for us.**

Because it's not just the reality bubble, it's how the game is structured.

Hmm. Fixing the battery. There's a bunch of dead zeds in the parking lot. I wonder if any of them have any mechanics-related literature on them? _(Presses **V**, hits **/**, types in **c:book**, )_ Yep. 29 tiles away, 42 tiles away, oh and look, I must have just missed a Xenu's Fan Club meeting because 4 zeds are carrying Dianetics and are in serious violation of their billion-year contracts to help humanity.

I guess the first question is: Would changing this be considered so "drastic" that it should be a mod?

Thanks for reading.
![Screenshot at 2021-05-29 14-58-07](https://user-images.githubusercontent.com/19985100/120085920-4b959680-c0aa-11eb-94d8-03211d258339.png)

**Comment by ZhilkinSerg** [comment]
Slightly related - https://github.com/CleverRaven/Cataclysm-DDA/issues/35023

**Comment by Salty-Panda** [comment]
Not exactly duplicate, but https://github.com/CleverRaven/Cataclysm-DDA/issues/31957#issuecomment-506989693

Also I recall a discussion about rendering vehicle roofs and only allowing player to inspect vehicle's interior from inside/next to it

**Comment by Anaglyphic** [comment]
There's all kinds of ways to implement it, although if I were doing it right now I'd probably shoehorn in an invisible opaque field "line_of_sight" way, or a terrain modifier way where invisible walls encircle you and are deleted and recreated every step; either way I envision it so that the fog of war is much tighter, and if you know terrain or furniture memory you'll still see the darkened but "unseen" for all objects on the memory map older than a threshold, different than the map itself.

Still, any form of this will drastically change the gameplay, so different in fact the "old way" will seem like cheating.
That's why I was concerned with opinion re: should it be a mod or does it sound like a welcome addition?

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
