### ISSUE TITLE
Error with scenario blacklist in DSA

### ISSUE THREAD

**Issue by actual-nh** [CleverRaven/Cataclysm-DDA#49089]
The following bug is showing up in CI, apparently in 0.F-dev.
```
Check failure on line 3 in data/mods/Dark-Skies-Above/blacklists/scenario_blacklist.json

GitHub Actions
/ GCC 9, Ubuntu, Curses, LTO
data/mods/Dark-Skies-Above/blacklists/scenario_blacklist.json#L3
Attempted to load scenario blacklist with an existing scenario blacklist

[
  {
    "type": "SCENARIO_BLACKLIST",
                                 ^
```
<s>I  have no idea why it's showing up at the moment.</s> EDIT: Looks like it would have shown up earlier but other things going wrong preempted it.

# Steps To Reproduce

See:
- <https://github.com/CleverRaven/Cataclysm-DDA/pull/49087/commits/ccb2e7b600edd100dc2a1ba9e0a9d3225805106e>, although technically targeted currently at master it's actually from the 0.F-dev branch (see #49087).
- <https://github.com/CleverRaven/Cataclysm-DDA/pull/49069/checks?check_run_id=2702853795>, at the end (see #49069).

**Comment by jbytheway** [comment]
Would be fixed by #49097.
