### ISSUE TITLE
"lethal force" security robots do not spawn with ammo

### ISSUE THREAD

**Issue by connorpmartin** [CleverRaven/Cataclysm-DDA#49088]
# Describe the bug

Security robots summoned via the bionic vault "lethal force" failure do not have ammunition.
Also true for at least some "lethal force" failures on finales: I checked the resonance cascade finale.

# Steps To Reproduce

Go to a bionic vault, fail to unlock the vault and summon security robots.

# Expected behavior

judicious application of .223, dead survivor

# Screenshots

![image](https://user-images.githubusercontent.com/55263157/120116897-6e7e8400-c158-11eb-98cc-5a071f42913a.png)
![image](https://user-images.githubusercontent.com/55263157/120117017-185e1080-c159-11eb-9b3b-47e30f9f03d6.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-10134-g9b256f6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key],
    Beta National Guard Camp [national_guard_camp_alt],
    No Rail Stations [No_Rail_Stations]
]

**Comment by mft-dev** [comment]
Can confirm. Failed twice on a bionic vault hack. Both times the secubot was hostile, but did not fight back when shot at. Did not drop any ammo upon death.

**Comment by OliveChukar** [comment]
Tested on cdda-windows-tiles-x64-2021-06-05-0832 with Dark Days Ahead [dda] only no mods.  Failed bionic vault hacks until m16 bot spawned.  It was unable to shoot me and when killed had no magazine drop.  The same bots were in the lab finale and they did have ammo bots spawned with debug also had ammo.

**Comment by RenechCDDA** [comment]
Still an issue as of https://github.com/CleverRaven/Cataclysm-DDA/commit/c94dc0387513d5bba49eb7d74b2b51a7a4d8c4a0

https://github.com/CleverRaven/Cataclysm-DDA/blob/9afa65ce6bbaf3bb96f12cb0ce9046d096c04667/src/computer_session.cpp#L1509-L1519

Probably needs to use spawn_monsters()
