### ISSUE TITLE
Crash when debug killing all monsters

### ISSUE THREAD

**Issue by Theawesomeboophis** [CleverRaven/Cataclysm-DDA#49092]
# Describe the bug

I was debug testing some monsters, and once I was done, I tried using the kill all monsters debug command, which crashed my game.

# Steps To Reproduce

1.  Spawn into game.
2. Debug spawn in monsters.
3.  Kill All Monsters using debug.
4.  Crash. 

# Expected behavior
 Debug command should not crash game.

# Versions and configuration

 - OS: [ Windows 8.1 ]
 - Game Version: [ 7bd9849 (tiles) ]
 - Graphics version: [ Tiles ]
 - Ingame language: [English]

**Comment by Saicchi** [comment]
Does this happen only on one specific world or in any world you create?

**Comment by Theawesomeboophis** [comment]
> Does this happen only on one specific world or in any world you create? If the former, please share with us the save where the error occurs.
> Also having the `crash.log` file would be nice.

I'll test on another world and report back.

**Comment by Theawesomeboophis** [comment]
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6566865/crash.log)

**Comment by Saicchi** [comment]
It might also be a problem with mods.
From the debug menu ( you need to bind a key to it, press `?` while in-game ), go to `i Info` then `r Generate game report`, it will give you a pretty list of game version and loaded mods.

**Comment by Theawesomeboophis** [comment]
It's not, retested with new world, problem went away. I'll test again to make sure it was just that world, it may have just temporarily disappeared.

**Comment by Theawesomeboophis** [comment]
Retested again, no crash. It seems it was just that world. ( I created two new worlds with same mods and repeated process, both times the game did not crash).

**Comment by Theawesomeboophis** [comment]
I'm gonna close this, as it seems fixed, I'll reopen if the bug appears again, but so far seems to have fixed itself.
