### ISSUE TITLE
respirator does nothing

### ISSUE THREAD

**Issue by connorpmartin** [CleverRaven/Cataclysm-DDA#49095]
# Describe the bug

The respirator CBM does not prevent the player from drowning.

# Steps To Reproduce

Install respirator CBM
Jump in a lake, drown

# Expected behavior

The player can breathe underwater.

# Screenshots

![image](https://user-images.githubusercontent.com/55263157/120124290-c087cf80-c181-11eb-8fc5-f1e1996cd4ba.png)

# Versions and configuration

OS: Windows
OS Version: 10.0 1909
Game Version: 0.E-10134-g9b256f6 [64-bit]
Graphics Version: Tiles
Game Language: System language []
Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
Bionic Professions [package_bionic_professions],
Aftershock [aftershock],
Arcana and Magic Items [Arcana],
Blaze Industries [blazeindustries],
Alternative Map Key [alt_map_key],
Beta National Guard Camp [national_guard_camp_alt],
No Rail Stations [No_Rail_Stations]
]

**Comment by natsirt721** [comment]
Looks like you're out of power, does the respirator consume power when active?

**Comment by connorpmartin** [comment]
Hm, it says it does in the tooltip, but maybe the issue is just that it doesn't display power draw on the bionics menu.
The display on the menu is a simple on/off toggle like Integrated toolset.

**Comment by Salty-Panda** [comment]
I can confirm that the Respirator consumes a lot of power when you don't have full Stamina which includes drowning. Not sure if it's listed anywhere though.

**Comment by Saicchi** [comment]
Can't replicate in `0.E-10474-g1ae66c97a0`.
The respirator consumes 25kJ to save the player from drowning. And when the player is out of energy, they start drowning.

**Comment by actual-nh** [comment]
It would appear to be an interface issue, then, of not telling the player what exactly is happening.

**Comment by natsirt721** [comment]
Seeing as how the respirator doesn't always consume power while active, I don't think it is appropriate to give it a power cost on the bionics UI. The best choice in this case might be change the log statement from the default "You're drowning!" to something that acknowledges that you do have an active respirator but informs you that it is unpowered.

**Comment by connorpmartin** [comment]
There's also a "x mj act" notation that gets used for bionics like probability travel, which turn on normally and occasionally act for larger draws of power. Maybe that notation would be good for the respirator?

**Comment by natsirt721** [comment]
The act notation is for when you toggle the bionic on for the first time (or so says the documentation). While it would present better to the user it smells like a hack to get that to work mechanically (ie NOT drawing the activation power when the user activates, instead when the trigger occurs). Perhaps making the respirator passive would be more in-line with its intended usage?

**Comment by actual-nh** [comment]
Ping: @Ramza13 - any thoughts?

**Comment by Salty-Panda** [comment]
We had te same problem with Repair Nanobots and decided to only display
actual cost while working. We could copy that solution.

**Comment by Tharn** [comment]
Yep, it says "No power is consumed if there is nothing to heal." Append something similar to the Respirator description and display power use for drowning/stamina regen please. I remember it using a lot of power, which is definitely something that should be mentioned.
