### ISSUE TITLE
Climbing while grabbed

### ISSUE THREAD

**Issue by connorpmartin** [CleverRaven/Cataclysm-DDA#49090]
# Describe the bug

Climbing onto a fence or similar object away from a grabbing zombie effectively allows the player to move while grabbed.

# Steps To Reproduce

Get grabbed next to a climbable object.
Climb the object successfully despite being grabbed

# Expected behavior

Player attempts to break grab instead of climbing: if grab break fails, climb is cancelled.

# Screenshots
Before: player grabbed by zombie security guard.
![image](https://user-images.githubusercontent.com/55263157/120118052-835e1600-c15e-11eb-8be1-f327f8585c8d.png)
After: player still grabbed, but has successfully moved away from the guard.
![image](https://user-images.githubusercontent.com/55263157/120118059-97097c80-c15e-11eb-9fa0-1a1ba16fcef1.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-10134-g9b256f6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key],
    Beta National Guard Camp [national_guard_camp_alt],
    No Rail Stations [No_Rail_Stations]
]

**Comment by Saicchi** [comment]
Can confirm on `0.E-10474-g1ae66c97a0 [64-bit]`

**Comment by OliveChukar** [comment]
Tested on cdda-windows-tiles-x64-2021-06-05-0832 with Dark Days Ahead [dda] only no mods.  I tested climbing up stairs when grabbed by a zombie wrestler and climbing up a downspout when grabbed by a standard zombie both times I got a message saying that I tried to break out of the grab but failed.  It seems like climbing up things is treated as a normal move and can only be done if you break any grabs however if you succeed at breaking the grab the character will move without any message.

**Comment by Saicchi** [comment]
Climbing a fence is not the same as going up/down stairs or downspouts.

**Comment by anothersimulacrum** [comment]
Confirmed on 0.E-10713-g65d31be62e

**Comment by NetSysFire** [comment]
The relevant part of the code should be:

https://github.com/CleverRaven/Cataclysm-DDA/blob/9d4315055517236355cefead31190f64086c84ee/src/iexamine.cpp#L1313-L1341

It looks like this would be easy enough for a new contributor to add a check if the player is being grabbed.
