### ISSUE TITLE
Radio-controlled, motorized garage door/winch/rope-pully systems

### ISSUE THREAD

**Issue by CoffinC** [CleverRaven/Cataclysm-DDA#49094]
# Is your feature request related to a problem? Please describe.
Mechanical Winches/Rope-Pully systems cannot be motorized. We can add motors to doors and to window covers, how about to these systems, and radio receivers?

# Describe the solution you'd like

1. Motorized Mechanical Winch/Motorized Rope-Pulley system, requires a battery (and perhaps a vehicle version to attach to base electrical vehicles), signal receiver, tunes to a color as already implemented. 

2. Radio-receiving motorization mod like battery/UPS mods that attach to existing mechanical winches/rope-pulleys. Activated like the RC-car remote already does via color, or a new 'remote activation button' AKA a garage door opener like you keep in your car.

# Describe alternatives you've considered
Any other way I can remote-open my garage doors or other winch/pulley uses!

# Additional context
Fire stations have two winch doors (3 if you count the side door but that's not the focus)! The simple pleasure of remote-controlling them from outside would be stellarrrrrr.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
