### ISSUE TITLE
Enjoying junk food while unable to taste from common cold

### ISSUE THREAD

**Issue by HenryAhnburger** [CleverRaven/Cataclysm-DDA#49113]
# Describe the bug

If you have the sweet tooth trait and you get the common cold, you still get the "Mmm, junk food" message and morale bonus when you eat junk food, even though "you can't taste much of anything with this cold"

# Steps To Reproduce

1. spawn with the sweet tooth trait
2. contract the common cold
3. eat some junk food to trigger sweet tooth

# Expected behavior

You shouldn't enjoy junk food that you can't taste

# Screenshots

# Versions and configuration

 - OS: windows 7
 - Game Version: the 0.f release candidate from the reddit sticky
 - Graphics version: tiles
 - Ingame language: english
 - Mods loaded: dda, no npc needs, bionic professions, graphical overmap

# Additional context

**Comment by actual-nh** [comment]
You can still taste sweet (it's your sense of smell that's knocked out), but I agree it should at least be reduced.

**Comment by HenryAhnburger** [comment]
> 
> 
> You can still taste sweet (it's your sense of smell that's knocked out), but I agree it should at least be reduced.

it triggers on non-sweet junk food as well (pork sticks for example)

**Comment by NetSysFire** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/cecb4775bde77fd4637f08ab1f17478040eca1eb/src/consumption.cpp#L1025-L1032

It appears there is apparently no effect at all?

**Comment by Night-Pryanik** [comment]
There are actually lots of messages describing good/bad taste of food based on traits (for example, honey for ursines or raw meat for predators) which doesn't take common cold or flu into account.

> It appears there is apparently no effect at all?

The effect is applied in `Character::fun_for` function.
