### ISSUE TITLE
crash when multidropping items 

### ISSUE THREAD

**Issue by gloryblackjack** [CleverRaven/Cataclysm-DDA#49110]
# Describe the bug

When I multidrop any items the game crashes. 

# Steps To Reproduce

1. Spawn into the game.
2. Press D (multidrop) and select a direction
3. select more than one item via the right arrow key
4. press enter
5. crash

# Expected behavior
multi dropping should not crash the game

# Versions and configuration

- OS: [ Windows 10 ]
- Game Version: [ 099e4a5 (tiles) ]
- Graphics version: [ Tiles ]
- Ingame language: [English]

**Comment by actual-nh** [comment]
@gloryblackjack: A fix was put in on the next version (#49055); try updating.
