### ISSUE TITLE
using an effective emitter on a makeshift rail rifle makes the ammo essentially infinite

### ISSUE THREAD

**Issue by toweroglass** [CleverRaven/Cataclysm-DDA#49115]
# Describe the bug

I placed am effective emitter mod on a makeshift rail rifle and now it doesn't consume ammo. I removed the mod and it correctly consumes one rebar rail when fired.

# Steps To Reproduce

# Expected behavior

I would expect it to reduce the amount of UPS energy used, not the ammo.

# Screenshots

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 9e12cf5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Alternative Map Key [alt_map_key],
    Crazy Cataclysm [crazy_cataclysm],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Crazy Cataclysm - UndeadPeople Tileset [CrazyCataclysmUDP],
    Graphical Overmap [Graphical_Overmap],
    MSX Black Military Cars [UDP_BlackMilitaryCars],
    sees-player icon, retrodays [sees_player_retro],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

# Additional context

**Comment by actual-nh** [comment]
Version? I think those are no longer around in the game.

**Comment by toweroglass** [comment]
> Version? I think those are no longer around in the game.

added version info. these are no longer in the base game, but they are in Aftershock.

**Comment by Mom-Bun** [comment]
I'll look into testing this to confirm it, but I'm suspecting its an issue of how the emitter works possibly.
