### ISSUE TITLE
I don't wanna eat my cellphone

### ISSUE THREAD

**Issue by Tairesh** [CleverRaven/Cataclysm-DDA#49126]
# Describe the bug
When you eat the `hide bag (fresh)` you also eat all items inside the bag (or they are just disappearing)

# Steps To Reproduce
1. Spawn or craft a hide bag
2. Put some things inside it
3. Eat the hide bag
4. Things disappeared

# Expected behavior
Non-edible things inside the edible container should not be consumed.

# Screenshots
![image](https://user-images.githubusercontent.com/1105196/120297882-f8f2ef00-c2e2-11eb-9816-ff9f02990c55.png)
![image](https://user-images.githubusercontent.com/1105196/120297961-0d36ec00-c2e3-11eb-9b5f-6b5cecf9710a.png)

# Versions and configuration
 - OS: Linux Mint 20
 - Game Version: fe42098
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: [ "dda" ]

# Additional context
I have seen this bug about a year ago when the "pockets" system was added but didn't think it's still there.

**Comment by anothersimulacrum** [comment]
This has a pretty simple solution: `spill_contents` the item when it is eaten, or (this is probably better) prevent eating items with contents.
