### ISSUE TITLE
Feature request: Wattle fences

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#49138]
There is [wattle](https://en.wikipedia.org/wiki/Wattle_(construction)), which is already used in wattle-and-daub walls in-game. It would be magnificent if wattle fences could be added. They would be an alternative to chickenwire fences, it can prevent small and maybe even medium-sized creatures from crossing. It will probably keep medium-sized creatures out, such as deer, but they can still tear it down when enraged since the wattle fence is not very sturdy. They may be good for anything farming-related so that your fields do not get trampled. And they will reliably keep small livestock such as chickens in.

The construction itself can probably be done in two steps:

1. Building a fence post
2. Putting the actual wattle in place

However, it may be possible to have an alternative for step 2: wattle panels, which should look like this:

![](https://upload.wikimedia.org/wikipedia/commons/c/c5/Wattle_hurdle.JPG)
This could also be used for walls and other things.

Just to add the feature, it can be crafted with heavy sticks, like the wattle-and-daub wall.
On the other hand, the whole system may need adjustments since stout branches may be too thick to be woven. Wattle fences may actually work fine with stout branches, since the woven texture does not need to be as dense:

![](https://upload.wikimedia.org/wikipedia/commons/c/ce/Zagroda_z_Ro%C5%BCnowic_%28Rozenberg%2C_1858%29.JPG)

Twigs may be just the right size. Splintered wood will be too inflexible and inconsistent in size to be woven and stout branches are, as already mentioned, too thick.
One advantage of wattle fences are that they only need wood. Constructing everything related to wattle may make use of the basketweaving proficiency if it is still in use.

I discussed this with some users in the IRC channel. @DeeUnderscore @faefux

**Comment by DeeUnderscore** [comment]
I think after #49156 this can now be closed?

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/living-off-the-land-rural-only/26691/1
