### ISSUE TITLE
Drug deal mapgen again spawns hundred drug items in every zipper bag

### ISSUE THREAD

**Issue by Salty-Panda** [CleverRaven/Cataclysm-DDA#49136]
# Describe the bug

There was a bug with drug deal mapgen spawning 100 heroin/other drug in every placed zipper bag. It was fixed but now it happens again.

Found in regular gameplay, tested on a fresh world with debug spawn.

EDIT. The PR #48327 that fixes it was only merged to 0F.dev branch?

# Steps To Reproduce

Start new world without any mods
Spawn mapgen drug_deal

# Expected behavior

Fewer drugs per zipper bag

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 418b45d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by Night-Pryanik** [comment]
@Salty-Panda could you please retest it on latest experimental?

**Comment by Night-Pryanik** [comment]
Can't reproduce on 0.F-2745.
![изображение](https://user-images.githubusercontent.com/11132525/133920202-e0a1ada3-d1d0-460d-a049-ac54cac776ac.png)
