### ISSUE TITLE
The program that my Visual Studio build exits immediately just after start

### ISSUE THREAD

**Issue by martinrhan** [CleverRaven/Cataclysm-DDA#49157]
# Describe the bug
I am using Visual Studio 2019, followed step-by-step to https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/COMPILING/COMPILING-VS-VCPKG.md
There was no error thrown, but the program exits just after start.
Here is the output log:
```
'Cataclysm-vcpkg-static-Debug-x64.exe' (Win32): Loaded 'C:\Users\Martin\source\repos\Cataclysm-DDA\Cataclysm-vcpkg-static-Debug-x64.exe'. Symbols loaded.
'Cataclysm-vcpkg-static-Debug-x64.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. 
'Cataclysm-vcpkg-static-Debug-x64.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. 
'Cataclysm-vcpkg-static-Debug-x64.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. 
'Cataclysm-vcpkg-static-Debug-x64.exe' (Win32): Loaded 'C:\Windows\System32\imm32.dll'. 
'Cataclysm-vcpkg-static-Debug-x64.exe' (Win32): Loaded 'C:\Windows\System32\user32.dll'. 
'Cataclysm-vcpkg-static-Debug-x64.exe' (Win32): Loaded 'C:\Windows\System32\winmm.dll'. 
'Cataclysm-vcpkg-static-Debug-x64.exe' (Win32): Loaded 'C:\Windows\System32\win32u.dll'. 
'Cataclysm-vcpkg-static-Debug-x64.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. 
'Cataclysm-vcpkg-static-Debug-x64.exe' (Win32): Loaded 'C:\Windows\System32\gdi32.dll'. 
'Cataclysm-vcpkg-static-Debug-x64.exe' (Win32): Loaded 'C:\Windows\System32\gdi32full.dll'. 
'Cataclysm-vcpkg-static-Debug-x64.exe' (Win32): Loaded 'C:\Windows\System32\msvcp_win.dll'. 
'Cataclysm-vcpkg-static-Debug-x64.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. 
'Cataclysm-vcpkg-static-Debug-x64.exe' (Win32): Loaded 'C:\Windows\System32\advapi32.dll'. 
'Cataclysm-vcpkg-static-Debug-x64.exe' (Win32): Loaded 'C:\Windows\System32\sechost.dll'. 
'Cataclysm-vcpkg-static-Debug-x64.exe' (Win32): Loaded 'C:\Windows\System32\version.dll'. 
'Cataclysm-vcpkg-static-Debug-x64.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. 
'Cataclysm-vcpkg-static-Debug-x64.exe' (Win32): Loaded 'C:\Windows\System32\shell32.dll'. 
'Cataclysm-vcpkg-static-Debug-x64.exe' (Win32): Loaded 'C:\Windows\System32\ole32.dll'. 
'Cataclysm-vcpkg-static-Debug-x64.exe' (Win32): Loaded 'C:\Windows\System32\combase.dll'. 
'Cataclysm-vcpkg-static-Debug-x64.exe' (Win32): Loaded 'C:\Windows\System32\oleaut32.dll'. 
'Cataclysm-vcpkg-static-Debug-x64.exe' (Win32): Loaded 'C:\Windows\System32\setupapi.dll'. 
'Cataclysm-vcpkg-static-Debug-x64.exe' (Win32): Loaded 'C:\Windows\System32\cfgmgr32.dll'. 
'Cataclysm-vcpkg-static-Debug-x64.exe' (Win32): Loaded 'C:\Windows\System32\bcrypt.dll'. 
'Cataclysm-vcpkg-static-Debug-x64.exe' (Win32): Loaded 'C:\Windows\System32\kernel.appcore.dll'. 
The thread 0x26f8 has exited with code 1 (0x1).
The thread 0xea8 has exited with code 1 (0x1).
The thread 0x2f8c has exited with code 1 (0x1).
The program '[9656] Cataclysm-vcpkg-static-Debug-x64.exe' has exited with code 1 (0x1).
```

# Steps To Reproduce
Everything I did was just following https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/COMPILING/COMPILING-VS-VCPKG.md. No code was edited.
Then hit the "Local Windows Debuger" Button.

# Expected behavior
It should run without automatic exit

# Versions and configuration
N/A

# Additional context
Not sure what do I need to provide, please ask me for any needed information.

**Comment by martinrhan** [comment]
![屏幕截图 2021-06-03 175700](https://user-images.githubusercontent.com/53336429/120626324-21224f80-c495-11eb-84f1-bca493e5248e.jpg)
Just got the cause.

**Comment by martinrhan** [comment]
Just found this.
![屏幕截图 2021-06-03 175700](https://user-images.githubusercontent.com/53336429/120627939-beca4e80-c496-11eb-862d-0a81a6e16e75.jpg)

**Comment by martinrhan** [comment]
Just found this
![屏幕截图 2021-06-03 175700](https://user-images.githubusercontent.com/53336429/120628226-00f39000-c497-11eb-9a35-d449bde65b44.jpg)

**Comment by BrettDong** [comment]
Did you set the working directory in debug settings?

**Comment by ZhilkinSerg** [comment]
See https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/COMPILING/COMPILING-VS-VCPKG.md#debugging:

![image](https://user-images.githubusercontent.com/16213433/120650850-d7cb0380-c486-11eb-9529-fad2e8ddf81b.png)

**Comment by martinrhan** [comment]
> See https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/COMPILING/COMPILING-VS-VCPKG.md#debugging:
> 
> ![image](https://user-images.githubusercontent.com/16213433/120650850-d7cb0380-c486-11eb-9529-fad2e8ddf81b.png)

sorry I didn't see carefully
