### ISSUE TITLE
Wrong text for resuming an in progress disassembly

### ISSUE THREAD

**Issue by danielkwinsor** [CleverRaven/Cataclysm-DDA#49169]
# Describe the bug

Says Get Content

# Steps To Reproduce

Interrupt disassembly
Activate with item nearby

# Expected behavior

Resume or Continue or similar to whatever text is for in-progress crafting

# Screenshots
<img width="929" alt="Screenshot 2021-06-03 192733" src="https://user-images.githubusercontent.com/2822992/120736997-233edb00-c4a2-11eb-9ed9-4d3d7b6d34c0.png">

**Comment by Psiclops** [comment]
Technically, when you disassemble anything, you are trying to get its "contents" or base materials. I doubt there is a different string for each item that is being disassembled.

**Comment by danielkwinsor** [comment]
OK, if the consensus is that this is desired, then anyone can unilaterally close this, np.
