### ISSUE TITLE
'Follower' animals do not add weight to vehicle when on trunks/aisles/etc

### ISSUE THREAD

**Issue by RenechCDDA** [CleverRaven/Cataclysm-DDA#49172]
# Describe the bug

My bike weighed 218kg with me on it.  A cow boarded my bike's "trunk". The bike still weighed 218kg with the entire adult cow riding it.

# Steps To Reproduce

Spawn a domesticated animal
Feed it
Move onto vehicle that they can move onto as well
Compare weights

# Expected behavior

The vehicle's weight should increase by the animal's weight and handling characteristics should change accordingly.

# Screenshots

![cdda1](https://user-images.githubusercontent.com/84619419/120793004-56b25180-c504-11eb-81aa-d939fbde0716.png)
![cdda2](https://user-images.githubusercontent.com/84619419/120793016-5c0f9c00-c504-11eb-8277-a341e33e6c5e.png)

# Versions and configuration

- OS: Windows 10
    - OS Version: 10.0 1809
- Game Version: fe42098 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded: [
    Dark Days Ahead [dda],
    Graphical Overmap [Graphical_Overmap]
]

# Additional context

-Not just cows, debug tested with some dogs too
-Friendly NPCs correctly add weight, just animals don't
-Animal compartments properly add weight when the animal is stored
-I can't seem to make animals follow me after putting them in and taking them out of an animal compartment, even with re-feeding/dog whistle. Not sure if this is a separate bug or I'm doing something wrong. Haven't used them much.

**Comment by Saicchi** [comment]
Can confirm on `0.E-10700-g0f965c0184`.
Not just friendly monsters. All monsters don't add weight to the vehicle, whether they be friendly / pets or not.

**Comment by leemuar** [comment]
Cow on bike, ahaha, that's cool :)

**Comment by SurFlurer** [comment]
A quick fix:
```
diff --git a/src/vehicle.cpp b/src/vehicle.cpp
index 489960b3..570e1435 100644
--- a/src/vehicle.cpp
+++ b/src/vehicle.cpp
@@ -7585,7 +7585,10 @@ void vehicle::calc_mass_center( bool use_precalc ) const
             // Sometimes flag is wrongly set, don't crash!
             m_part += p != nullptr ? p->get_weight() : 0_gram;
         }
-
+        if( vp.has_feature( VPFLAG_BOARDABLE ) ) {
+            const monster* z = get_monster( i );
+            m_part += z != nullptr ? z->get_weight() : 0_gram;
+        }
         if( use_precalc ) {
             xf += vp.part().precalc[0].x * m_part;
             yf += vp.part().precalc[0].y * m_part;
```
I think it also needs a test unit.
