### ISSUE TITLE
Amoebic Molds and Slimes lead to exponential Slime production

### ISSUE THREAD

**Issue by Founded1992** [CleverRaven/Cataclysm-DDA#49186]
Amoebic Molds,  Slimes, and Small Slimes in close proximity result in exponential slime spawns, causing game lag and numerous error warnings.

# Steps To Reproduce
1. Spawn an Amoebic Mold, a Slime, and a Small Slime in close proximity.
2. Wait several in-game hours.

Spawning the monsters in an enclosed area helps speed up the process.

# Expected behavior

I would expect the slimes to remain in the numbers they originate at.

# Screenshots

[https://imgur.com/hHPwVWA](url)

# Versions and configuration

 - OS: Windows 10
 - Game Version: d3b1ed2 (latest experimental as of this report)
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: dda, no_npc_food, package_bionic_professions 

# Additional context

The bug seems to occur only when a combination of the three entities are present. The image includes three rooms with each set of two of the above entities: small slime and amoebic mold, slime and amoebic mold, and small slime and slime from left to right. All monsters were spawned at the same time, and the bottom room was filled before 12 hours had passed.

I have not tested to see whether any other combination of three of the above entities produce these effects.

This was discovered on an older, modded experimental during a research facility lab escape. During the run, numerous errors regarding enemies occupying the same space and zombies being unable to move in spaces occupied by slimes occurred. It was replicated on an unmodded version, and then the newest version.

I was unable to find any open issues that described this bug. Possibly related to #46733.

**Comment by Theawesomeboophis** [comment]
Slimes are supposed to multiply, but I'm pretty sure it's not supposed to be enough to cause lag. And amoebic molds spawn slimes, which then multiply, it's an intended feature of amoebic mold, I believe this is a problem with how the game handles a large quantity of enemies in one place or something.

**Comment by xerenogan** [comment]
I can confirm this. About 15 minutes ago I had a run come to an end because of this. Spent two in-game days fighting the never ending tide of slime. Finally spawned a clairvoyance artifact and found that every single unobstructed on the lab basement level I was on (with the exception of the dwindling safe areas was filled with slimes. I tried fixing it with debug by using the kill all monsters option a few times, and that killed most of them, with the exception of a still large section of medium sized slimes. All attempts at using the kill command from that point on had the opposite effect, and duplicated them by about 25%. I don't know why this is, but if I had to guess, it might have something to do with all the slime globs on the ground. So, basically, not even the kill all command can stop them from growing beyond all hope of control.

**Comment by Theawesomeboophis** [comment]
> I can confirm this. About 15 minutes ago I had a run come to an end because of this. Spent two in-game days fighting the never ending tide of slime. Finally spawned a clairvoyance artifact and found that every single unobstructed tile in the lab basement level I was on (with the exception of the dwindling safe areas was filled with slimes. I tried fixing it with debug by using the kill all monsters option a few times, and that killed most of them, with the exception of a still large section of medium sized slimes. All attempts at using the kill command from that point on had the opposite effect, and duplicated them by about 25%. I don't know why this is, but if I had to guess, it might have something to do with all the slime globs on the ground. So, basically, not even the kill all command can stop them from growing beyond all hope of control.

So it's a problem with the amount of slimes produced?

**Comment by xerenogan** [comment]
Maybe, I'm going to see if I can recreate my specific circumstances. It seems that they merge into big slimes and rapidly duplicate faster than it is possible to deal with, and at some point, even the kill all command stops working. Either way, their is something very wrong here. That was a good run, and I would hate to have another run end like that.

**Comment by Theawesomeboophis** [comment]
> Maybe, I'm going to see if I can recreate my specific circumstances. It seems that they merge into big slimes and rapidly duplicate faster than it is possible to deal with, and at some point, even the kill all command stops working. Either way, their is something very wrong here. That was a good run, and I would hate to have another run end like that.

It seems we might have to lower the amount of slimes produced, but I could be wrong, maybe this is an actual bug and not a problem with json values.

**Comment by xerenogan** [comment]
> It seems we might have to lower the amount of slimes produced, but I could be wrong, maybe this is an actual bug and not a problem with json values.

Maybe. Where are those values? I'll do some testing to see if I can figure it out.

**Comment by Theawesomeboophis** [comment]
> > It seems we might have to lower the amount of slimes produced, but I could be wrong, maybe this is an actual bug and not a problem with json values.
> 
> Maybe. Where are those values? I'll do some testing to see if I can figure it out.

I'm not sure where the actual values are contained, I'm guessing somewhere in the data/json folder though.

**Comment by xerenogan** [comment]
Alright then. I'll do some poking around.

**Comment by Theawesomeboophis** [comment]
It should be in monster special attacks, from what i've read in json for slimes.

**Comment by Founded1992** [comment]
> 
> 
> Slimes are supposed to multiply, but I'm pretty sure it's not supposed to be enough to cause lag. And amoebic molds spawn slimes, which then multiply, it's an intended feature of amoebic mold, I believe this is a problem with how the game handles a large quantity of enemies in one place or something. ( It could be that the amount of slimes spawned needs to be tuned down, I'm not really sure).



> 
> It seems we might have to lower the amount of slimes produced, but I could be wrong, maybe this is an actual bug and not a problem with json values.

I should emphasize the point that the issue with slimes is that their growth is exponential, and that it impedes gameplay through the introduction of lag and numerous errors related to overproduction.

As an example, I've dropped a debug character into a vanilla research facility on the most recent experimental version with no additional mods added. I waited in the same location for the duration of a day.

The following images are graphic, and not for the faint of heart:

![image](https://user-images.githubusercontent.com/24758773/120896951-a82c1080-c5d8-11eb-8e3c-3aaed48a5881.png)
![image](https://user-images.githubusercontent.com/24758773/120896954-acf0c480-c5d8-11eb-86bc-57cc10041757.png)

Note that slime generation in the minimap composite abruptly ends at the reality bubble.

This is a problem for laboratory escapes because the reality bubble extends beyond the z-level of your current position, and you're not in a position to address the growing slime presence until long after it has begun to deteriorate to a veritable grey goo.

I am of the opinion that this is a bit more than a JSON modification, as the exponential growth would render variable modifications either ineffective in removing overproduction or overly nullifying replication in the first place.

**Comment by Theawesomeboophis** [comment]
Wow, that is a lot more slimes than I was expecting.

**Comment by xerenogan** [comment]
Yep, that's what I've found as well. It seems the presence of other monsters is not needed. They eventually hit a critical mass and from there it's game over in so many ways.
![slimebs](https://user-images.githubusercontent.com/75096026/120897299-5cd32b80-c5f3-11eb-9dbe-6fb757e10b10.png)

**Comment by Theawesomeboophis** [comment]
Not even a super-mutant bionic god with lvl 100 in all combat skills can kill that many.

**Comment by xerenogan** [comment]
Yep, that's what I've seen as well. I've been messing around with it and it seems that the presence of other monsters is not required. They eventually hit a critical mass, and then it's game over from there.
![slimebs](https://user-images.githubusercontent.com/75096026/120897357-ba677800-c5f3-11eb-8b17-41a9048598ed.png)

**Comment by Theawesomeboophis** [comment]
I'm not really the person for this, I don't really do anything outside of json, I hope someone else knows how to fix this.

**Comment by Founded1992** [comment]
I would be hesitant to say that this replication is independent of external monsters. My original issue submission included a test where two slimes were held separately from an amoebic mold. I also note the existence of an amoebic mold in your image, within the open autodoc room toward the south.

Are you running the game on a linux OS? The issues document suggests confirming the bug's existence across different platforms would be helpful.

**Comment by xerenogan** [comment]
Yes, I am on Linux. That Amoebic mold was from a test to see if they would grow out of control in different conditions using those cells down below. They seemed to grow out of control fastest in that water room. I just opened all the doors and let them spread to get the screenshot.

**Comment by xerenogan** [comment]
I'll do another without any other monsters to confirm. One moment.

**Comment by xerenogan** [comment]
Interesting, you seem to be correct. They spread far far more prodigiously in the presence of an amoebic mold. Hmm, code-wise the amoebic mold is almost identical to a big slime with the same special attack, even mass. The only big difference is the death effect which just has it melt away to nothing. Looking at the FORMBLOB attack itself in monattack.cpp, it seems to mostly just transfer speed to other slimes and transfer speed if high enough. I assume the number being fed into it is the chance to use the attack, so amoebic molds look to have a much lower chance of spawning slimes. I'm not sure why they are causing this problem.

**Comment by xerenogan** [comment]
The mold seems to absorb the slimes despite itself being a friendly and also technically a slime.

**Comment by xerenogan** [comment]
I'm trying to narrow down what changed. I just tried a build from 16 days ago and it was fine, no super duplication. So something in the last few weeks broke it. I'll be back when I narrow down the build.

**Comment by xerenogan** [comment]
Somewhere between build 1757 and 1836 on June 1 is when this bug was introduced. Now I just need to narrow it down to the specific commit.

**Comment by xerenogan** [comment]
Found it! The problem is caused by "Fix crash when killing monsters without "material" #49125".
The FORMBLOB special attack does a check to see differentiate slimes from non-slimes by their material type and if it is something like "flesh" it absorbs it and makes another slime. #49125 makes it so that if a monster has no material type, it is default flesh, which is what is causing this problem.

**Comment by xerenogan** [comment]
The fix is to add a material field with something like "slime". One moment. If this works, I'll have a pull request to fix this shortly.
