### ISSUE TITLE
Nested inventory + trading with NPC = counting items twice

### ISSUE THREAD

**Issue by big-smitty** [CleverRaven/Cataclysm-DDA#49209]
# Description

 When trading with an NPC, you can sell a container and it's contents, then sell its contents, doubling the expected gain.

# Steps To Reproduce
1. Trade with an NPC
2. Sell a container:
![bug1](https://user-images.githubusercontent.com/85451361/120948943-3945d900-c6f8-11eb-8df6-009f22541c10.PNG)
3. Sell the contents of the container, note the difference in credit, and the expected price of selling:
![bug2](https://user-images.githubusercontent.com/85451361/120949005-55e21100-c6f8-11eb-9844-1ff3e6ae158f.PNG)

# Expected behavior

Selling the container implies selling the contents, so you shouldn't be able to select the subcontents of a container if you are selling the container.
eg.
Selling a bottle of water -> you shouldn't be able to sell the water as well.
so the water would auto-select on selecting the bottle.

# Versions and configuration
- OS: Win 10
- Version: experimental 38074ba, released 05/25/21@1559
- Graphics: Tiles
- Language: en-us
- Mods: Aftershock, stats through kills, Magiclysm

**Comment by natsirt721** [comment]
This works the other way around too - you can dupe items by buying the item and the container that it is in.

**Comment by RoyBerube** [comment]
PR #48580 addressed this kind of problem by disallowing a duplicate selection when in a container. The same approach should work here.
