### ISSUE TITLE
Auto-highlight (and center on the screen when appropriate) enemies that trigger safe mode.

### ISSUE THREAD

**Issue by ifffrt** [CleverRaven/Cataclysm-DDA#49213]
# Is your feature request related to a problem? Please describe.
Safe mode can sometimes be a pain to deal with when I'm trying to maneuver around a group of enemy, because this can typically lead to situations where the warning popups for a group of enemy in one direction repetitiously come up so often that I zone out and ignore those warnings, which then leads me to fail to notice the warning for another enemy coming from another direction and get blindsided. This can also happen if I have special blacklist settings for particularly dangerous enemies, because typically when they are most needed I would have been too busy dealing with other lesser enemies and their safemode spam, and so those special blacklist settings might as well not exist. All of this have made safe mode much less useful than it should be in my playing experience.

# Describe the solution you'd like
The game should highlight the particular enemy that triggered the safemode with a reticule, along with a trail leading back to the player (like the one used in aiming) to give an easy indication of direction. If an enemy is so far away that you can't see it on screen, the game should also automatically pan the screen to make the enemy in the distance visible.

# Describe alternatives you've considered

# Additional context
The inclusion of this feature would also help a lot with mitigating the headache of navigating around flying enemies on different z-levels when experimental 3D vision is enabled (which I brought up in this issue https://github.com/CleverRaven/Cataclysm-DDA/issues/48322), because right now you can't see them on screen at all, and the player character can in fact be less able to see through different z-levels than enemies can.

**Comment by natsirt721** [comment]
Honestly, just adding the direction to the log text would be nice. 
* "You've spotted a mi-go to the east!"
* 'yeah I know that's the one I'm aiming at' 
* .... 
* .... 
* "You've spotted a mi-go to the south-west!" 
* 'oh f*** ok'

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
