### ISSUE TITLE
FeRq: Screenshots in a neutral tile-free format?

### ISSUE THREAD

**Issue by Anaglyphic** [CleverRaven/Cataclysm-DDA#49214]
This came up in trying to help someone who uses UltiCa, I have not spent more than 10 seconds using it, mostly when trying builds from someone else where it's the default, like the jenkins autobuilds, before I immediately go change it.

I would expect everyone has a favourite; and there's officially what, 9 +2 variants? And another ~3 not part of base game in common use? I would guess most people set and stay. When they upgrade they either keep their config, or immediately change it to their favourite, perhaps even from the main menu, never even loading the default once.

So my feature request is this - sure, dump the .png screen buffer, but also, save the underlying row/column data of what the tiles represent, so that a helper app of some sort, maybe code on the debug menu, maybe an external shell script python perl lua something, little helper app, could change the screenshot we see into a format we're familiar with.

Would this have any usefulness for anyone besides me?

_(I'll going to try to use UltiCa more since it's the default, but as more people try the iso projection tileset with z-level enabled, and that's even more alien than UltiCa.)_

**Comment by actual-nh** [comment]
> Would this have any usefulness for anyone besides me?

I was just discussing something closely related to this with @Fris0uman over on the discord, namely helping people figure out what's what in the different tilesets (_plus the curses version_) to help people figure out what someone else's screenshot is (it also may help someone select a good tileset - or the curses version - for them, and could be helpful for development of, say, new combined tilesets - I wouldn't mind seeing something that did ASCII for things other than monsters, but used as-realistic-as-possible icons for monsters, for instance.)

**Comment by ZhilkinSerg** [comment]
No need to invent a wheel - we already have savegame functionality. You load provided savegame and see everything in your preferred tileset.

**Comment by esotericist** [comment]
save games can be huge. like, implausible-to-share huge, even for people who haven't been running their game for real-life-years.

so i think something in between has merit abstractly, but i suspect it will tend to be brittle, and will still be a lot of a hassle for a given user to work with. plus the complexity on the game end to try to extract that information meaningfully so it can be reconstructed later.

**Comment by Anaglyphic** [comment]
I initially used ascii simply because it's just what makes sense, hopefully that's not a self-diagnosis. Although I have gotten used to the SDL asciitiles because of the scalability without having to change the font parameters and quit/restart... and even retrodays a little bit, which I've now made my default. It's like the perfect match to the mostly-textual data, it's clear a lot of thought went into it by a like-minded person - for most of the tiles, anyway.

But ultimate or hoders or msxotto/deadpeople, as I said, it's a different game to me. Again, hopefully that's not self-diagnosis. It took me an EMBARRASSING amount of time to figure out that symbol on the bottom of a killed enemy in ultimatecataclysm was a warning triangle, basically telling you to gib them. It's only a couple pixels unless I'm on zoom 4 or 5, because even the font scale <-> tiles doesn't align. _(I am also a huge fan of the isometric Fallouts 1/2/BoS so I want to love hitbutton, but it's just so damn foreign.)_

Huge saves? Ehh, well, even a mid/late-game with 100+ submap sectors fully explored, so many millions of adjustments since the mapgen ran, etc. it's still only a hanful megabytes once compressed, yea? ~180M of world data compresses down to ~8M with bzip2. _(my biggest world so far I worry about backing up)_. I mean compared to a modern 3d game save that's dozens / hundreds of megs, cdda saves are essentially free. Locally. Even cell phones (can) have terabytes now. But yea you do have a point.
\- \- \-
Hmm, so without reinventing the wheel, would it be worth the effort to section off a bit of that savegame map code so can we have it modular, and callable independently? Maybe even a convenient "take screenshot for bug tracker" debug menu item?

Further, are there any open image format standard that supports layers? I mean a GIF is so much smaller than a PNG but, well, it's a damn GIF, and GIF supports layers so that saving every tileset installed in one GIF would probably be the same size as a truecolor PNG, but again, it's a damn GIF. But you get my point. What about the user's default tileset in the main PNG and then as a metadata tag, the ascii representation so we could load said PNG with cdda and generate it in whatever tileset we wanted? 

Sorry just thinking out loud...

**Comment by esotericist** [comment]
we routine have players who can't attach their saves to issues because even compressed it comes out to a few hundred megabytes.

the rest of what you say is what i referred to in my last comment: brittle, a hassle to use, and technically expensive to implement.
