### ISSUE TITLE
When I create a roof, it doesn't show up on the z level above.

### ISSUE THREAD

**Issue by mawhingo** [CleverRaven/Cataclysm-DDA#49210]
# Describe the bug

I decided to live in one room of a building.  To make more room I smashed through one wall to make the room larger by using  the room beyond it.  The roof caves in.  No problem, I build a roof where-ever it collapsed.  However when I climb to the top of the building the roof has a hole showing open air. I cannot build a floor over open air.  My newly built roof doesn't extend to the the z level above.  So I cannot use the level above me as it has holes in it.

I tried building a roof with experimental z - levels on, and that didn't help.

<!-- Steps to reproduce the behavior:

- Smash through a wall with a jackhammer.
- The roof above will collapse
- construct a roof where the collapsed roof is.
- Climb to the level above, there is a hole where there should be a roof.
- Cant construct a floor over the hole because it is open air.
- You can build a skyline window over the open hole.  However that means you cannot use that level above because you cannot travel over the skyline.

# Expected behavior

You should be able to construct a roof and have it show up on the above level as a 'floor' and be able to travel normally over that 'floor'

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-10395-g4525b4f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    No Fungal Monsters [No_Fungi],
    Disable NPC Needs [no_npc_food],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    More Survivor Stuff [more_survivor_stuff],
    Stats Through Skills [StatsThroughSkills],
    Mining Mod [Mining_Mod],
    Useful Helicopters [useful_helicopters],
    Blaze Industries [blazeindustries]

**Comment by actual-nh** [comment]
Could you upload a savefile, and also fill in the rest of the bug report template (most particularly version, although OS might matter also)?

**Comment by Anaglyphic** [comment]
Yes correct of course it doesn't the "roof" would be over where you're standing, not above that.

You're thinking too much like a 3d gamer, and enabling z levels is just going to enforce that belief. it's not a 3d world.

Hmm. Let me explain a different way. 

If you made a stair_up and then tried to go up that stair_up, without already having been to the z level +1 from your current location and making a stair_down, you'd falli immediately to your previous floor and probably get hurt. 

You'll still need a "floor" on this z, even though there's a "roof" on the z -1 below. Does that makes z-sense?

**Comment by mawhingo** [comment]
I'm sorry, I thought I added the game report.

[Jim_base_world_001.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6605559/Jim_base_world_001.zip)
 ##


- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-10395-g4525b4f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    No Fungal Monsters [No_Fungi],
    Disable NPC Needs [no_npc_food],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    More Survivor Stuff [more_survivor_stuff],
    Stats Through Skills [StatsThroughSkills],
    Mining Mod [Mining_Mod],
    Useful Helicopters [useful_helicopters],
    Blaze Industries [blazeindustries]
]

**Comment by mawhingo** [comment]
thanks Anaglyphic that makes sense.  It's a bit of a head bender.

**Comment by Anaglyphic** [comment]
yea so I get what you mean now...

You jackhammer'd the brick wall... you get sky... you walk over to the stairs in the NW, and there's your hole in the floor/root, but, it won't let you do an open air build; you can build a wooden or pebble or even concrete floor if you drag the mixer up here, but nope not over those fallen bits.

Sorry it just doesn't exist yet. There's no repairing that damage legitimately I don't think. I could be wrong, I'm no expert. 

I would tell you to use the debug menu and put the floor back, but if you're going to do that? Then just remove the wall with debug instead of the jackhammer and not have to fix anything afterwards. Then re-enable achievements and pretend you know about the debug menu, because it's a very slippery slope.

**Comment by mawhingo** [comment]
Thanks, I think I will just debug it then.  And then pretend debug doesn't exist.

**Comment by Tairesh** [comment]
it is very confusing that the "Build the roof" action actually builds the floor.

**Comment by KittyTac** [comment]
Honestly I think a roof on z0 should automatically create a "linked" floor on z1. That would make more sense, that's how it works IRL and it would be more convenient gameplay-wise.
