### ISSUE TITLE
Lifting vehicle part can't use to remove vehicle part

### ISSUE THREAD

**Issue by WindAndNothing** [CleverRaven/Cataclysm-DDA#49212]
# Describe the bug
lifting arm can't be used, but strength can used to remove vehicle part.

# Steps To Reproduce

1.I have telescopic crane and forklift arm in fig.1.
2.Can't remove the engine with the lifting request in fig.2

# Expected behavior
Vehicle part can be removed with telescopic crane or forklift arm.

# Screenshots

![image](https://user-images.githubusercontent.com/45221786/121017976-79788a80-c7d0-11eb-89b1-2ac2961bcd81.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 099e4a5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    Alternative Map Key [alt_map_key],
    Dark Skies Above [darkskies],
    Fuji's Military Profession Pack [fuji_mpp],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

**Comment by Tamiore** [comment]
Do you have line of sight/effect from the crane to both you and the part you are trying to take out?

**Comment by Maleclypse** [comment]
> Do you have uninterpreted line of sight/effect from the crane to both you and the part you are trying to take out?

If it's still occurring after you check the above comment please attach a zipped save file for reproduction of the bug.

**Comment by WindAndNothing** [comment]
> > Do you have uninterpreted line of sight/effect from the crane to both you and the part you are trying to take out?
> 
> If it's still occurring after you check the above comment please attach a zipped save file for reproduction of the bug.

I tried it. It's really sight line problem. Thanks.

**Comment by Anaglyphic** [comment]
Hi.

The code in veh_interact.cpp states:
`vehicle_selector( player_character.pos(), 2, true, *veh ).max_quality( qual_JACK `

You're 3 tiles away, not 2. Can you move 1 closer and try again?

**Comment by natsirt721** [comment]
Looks like OP acknowledged that a lack of LoS was the problem, I believe this can be closed.
