### ISSUE TITLE
Generated Vehicles have damage in weird places.

### ISSUE THREAD

**Issue by big-smitty** [CleverRaven/Cataclysm-DDA#49226]
# Is your feature request related to a problem? Please describe.
When encountering vehicles that aren't entirely trashed, they seem to have minor damage over the entire vehicle. That doesn't really make any sense. Shouldn't most cars be in decent condition? It's not like every car ended up crashing. Even if they did crash, the damage should be localized to the crash area (front of car/ right passenger door & wheel/ etc.). They shouldn't be lightly damaged over the entire vehicle. What circumstances lead to a car being damaged like that?

Also, how am I finding cars with a destroyed engine and front wheel assembly, but the windshield is intact? That ain't realistic.

# Describe the solution you'd like
Car generation should be slightly tweaked. Certain areas of some cars should generate free of damage, while other parts might be entirely destroyed. Basically, the generation should be more realistic.

# Describe alternatives you've considered
On vehicle generation, flag the vehicle as "crashed" or "not crashed". 
- If it's not crashed, reduce the damage over the entire vehicle. 
- Otherwise, pick a part(s) of the vehicle to simulate a crash on. Destroy that tile to a certain degree, then the ones around it. The damage should be localized to the crash site.

# Context
Stuff like this on one tile (the windshield is intact but the frame supporting it is destroyed?)
![image](https://user-images.githubusercontent.com/85451361/121130384-34118880-c7e3-11eb-93bd-c66b35277507.png)

Every tile of this car- and most others- has damaged parts, seemingly at random. There could be more thought behind the damage generation.

**Comment by KittyTac** [comment]
Originally it was due to acid rain but the lore has changed. This would make more sense.

**Comment by natsirt721** [comment]
One approach might be to subject the vehicle to collisions with a selection mobs, terrain, and other vehicles. Although I think the current collision code is pretty poor, and relies on the game map so it won't be plug-n-play.

**Comment by actual-nh** [comment]
See #49105, BTW.

**Comment by actual-nh** [comment]
Regarding vehicles damaged in the course of the Cataclysm itself, faefux at <https://github.com/CleverRaven/Cataclysm-DDA/pull/49105#issuecomment-861126423> pointed out something:
> Despite being out of scope I'd like to add that we likely are not only looking at your normal car crash in some/many instances but the after effects of, well reality failing down on its head for a minute there. I think we can justify exceptionally strange crash configurations in the context of <the_cataclysm> happening.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
