### ISSUE TITLE
Using a splint on an NPC will splint the limb, but return the splint to you

### ISSUE THREAD

**Issue by big-smitty** [CleverRaven/Cataclysm-DDA#49227]
# Describe the bug
When you use a splint on an NPC to heal a broken wound, the wound is marked as 'broken but set with a splint', but you retain the splint in your inventory

# Steps To Reproduce
1. Have an NPC with a broken limb
2. Use a splint on them
3. View duped item in your inventory

# Expected behavior
- The splint should leave your inventory since it is on an NPC. 
- It should probably retain the "Your Followers" faction, but stay in the NPCs inventory since it is with them and not you.

# Screenshots
The wound is set and healing:
![image](https://user-images.githubusercontent.com/85451361/121132446-fd893d00-c7e5-11eb-9139-2c25008ece93.png)
But I retain the || arm splint:
![image](https://user-images.githubusercontent.com/85451361/121132553-227db000-c7e6-11eb-8dbf-f2a8349bdfc4.png)

# Versions and configuration
- OS: Win 10
- Version: experimental 38074ba, released 05/25/21@1559
- Graphics: Tiles
- Language: en-us
- Mods: Aftershock, stats through kills, Magiclysm

**Comment by OliveChukar** [comment]
Tested on (cdda-windows-tiles-x64-2021-06-20-0737) with no mods core content pack only.  Got a NPC with a broken arm and leg.  Used an arm splint and a leg splint on NPC by walking into it and pressing (i) and the splint items were still in my inventory.  Checking the NPC showed that its limbs were splinted and it was wearing the splints so the items were duplicated.
