### ISSUE TITLE
Debug error happens when switching to saves without mod.

### ISSUE THREAD

**Issue by Xindage** [CleverRaven/Cataclysm-DDA#49223]
# Describe the bug
It's a little complex to explain but the issue is when loading a save without mod already having loaded a other save with a mod before, led to some debug errors when loading the new save. (in this case not loading aftershock)

# Steps To Reproduce
1. Have 1 world save whit aftershock.
2. Load this save.
3. Save and quit this world.
4. Load a new world without aftershock mod.
5. Notice some debugs errors while you load the game again.

# Expected behavior
No errors.

# Versions and configuration
- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.2 LTS; Release: 20.04; Codename: focal; 
- Game Version: 39074ba [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded on first save: [    Dark Days Ahead [dda],    Disable NPC Needs [no_npc_food],    Bionic Professions [package_bionic_professions],    Aftershock [aftershock]]
- Mods loaded on second save: [    Dark Days Ahead [dda],    Disable NPC Needs [no_npc_food],    Bionic Professions [package_bionic_professions]]

# Additional context
i think the engine wont unload data that's on memory after quitting from a world, and them keep the mod loaded in memory while loading a new game without this information.
[debug.log.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6612595/debug.log.zip)

**Comment by actual-nh** [comment]
I am confused. Why would you anticipate _not_ getting errors if a game was created using a mod, then attempted to be restored without that mod (as in, what happens to all the stuff from that mod)?

**Comment by Xindage** [comment]
no i wont restored any save,i loaded a save with the mod them i quited it, i wont exited the engine just the world, them i loaded OTHER save that dont contain that mod and errors happened, i'll cut part of the debug to show you.

21:09:23.358 WARNING : opendir [./save/Batesland (Normal)/mods] failed with "No such file or directory".
21:09:39.500 INFO : Loaded tileset: UltimateCataclysm
21:10:13.108 WARNING : opendir [./save/debug solder/mods] failed with "No such file or directory".
21:10:13.572 ERROR : src/item_factory.cpp:716 [void Item_factory::finalize_item_blacklist()] Replacement item for migration emp_gun does not exist

It's indeed different saves. i hope this explain it better.

**Comment by actual-nh** [comment]
Ah! I believe this is a known problem (essentially, things are being referenced by an internally-generated id number that could change with different mods in use), but I'm not completely sure offhand.

**Comment by anothersimulacrum** [comment]
It's actually a different thing, we're failing to clear all the data we should.

**Comment by PatrikLundell** [comment]
I've had that problem with 0.E2 stable. I quit my "normal" world, generated a new one with one or both of the "over time" stat gain mods added, saved and quit that world, and reloaded the normal one, only to find my character now having gained inflated stats. That went away after quitting the game completely and loading the save.

**Comment by Xindage** [comment]
i've tested that again myself with stable ellison 3 on a windows 10 machine and the same glitch from above happened i created a new character on a world with stats by skill on, i give him 3 points on all skill and base skill of 8, some of their stats was raise at the start of the game, so i closed the world and i started a new world whitout the stats by skill using the last character from before, and the result was a buffed stats character like if the mod was on, even if it's off.

![stats on while off](https://user-images.githubusercontent.com/6380147/121202914-0e6c9980-c84c-11eb-88c0-eed823dfa45e.png)

so even after closing a world whit a mod enabled it'll be still enabled after changing worlds if you do not completely close the game.

**Comment by Vollch** [comment]
You don't even need a save or character for this to happen. Just empty world is enough:
1) Create world "A" with default mods + Aftershock
2) Create world "B" with only defaults mod
3) Start creating character in world "A" - enter chargen, and after loading data immediately return to main screen, without finishing
4) Try to create character in world "B" - and here's bunch of errors: `Replacement item for migration emp_gun does not exist`, `Invalid migration target: afs_xm34`, etc.

**Comment by GoLoT** [comment]
Linking related issue #50287 for reference.
