### ISSUE TITLE
A7 laser rifle not working with a UPS

### ISSUE THREAD

**Issue by Ste-Mich** [CleverRaven/Cataclysm-DDA#49237]
# Describe the bug

With Aftershock enabled there are two A7 rifles. One of these does not work.
On reload it will tell you: "You need a compatible magazine to reload the A7 laser rifle!".
When trying to shoot: "Your A7 laser rifle is empty!".
In debug menu you will find two A7 rifles, the 3.00L one is not functioning.
The 3.18L one works fine.

There is a similar issue, that might help: #49004

# Steps To Reproduce

1. Make a world with Aftershock enabled.
2. Make a player with an A7 rifle and a UPS.
3. You will find two different A7 rifles. One works, one does not. 
4. Unfortunately I'am not sure which one is from Aftershock.

# Expected behavior

The A7 rifle shoots.

# Versions and configuration

 - OS: Windows 10
 - Game Version: c821798 [64-bit]
 - Graphics version: Tiles - MSX Undead People
 - Ingame language: default (english)
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by Ste-Mich** [comment]
Totally forgot to add: #49004
It might help with this issue.

**Comment by Mom-Bun** [comment]
Intended, energy weapons in Aftershock use magazines now instead of UPS now with #47131

You can find the new magazines in formless ruins.
