### ISSUE TITLE
Using sealed yeast culture made with glass jar still yields glass flask

### ISSUE THREAD

**Issue by Little-119** [CleverRaven/Cataclysm-DDA#49235]
# Describe the bug

The growth of yeast can reshape glass, converting glass jars to glass flasks

# Steps To Reproduce

1. Craft sealed yeast culture using glass jar
2. Wait 2 hours
3. Use sealed yeast culture
4. Observe the product: a glass flask filled with yeast

# Expected behavior

To receive a glass jar in this situation

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 876e779 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    No Rail Stations [No_Rail_Stations]
]

# Additional context

**Comment by Night-Pryanik** [comment]
Can't confirm on latest experimental as of 10 November 2024.
Crafted sealed yeast culture, waited for 9 hours, activated it, got a sealed glass jar with yeast inside.
![изображение](https://github.com/user-attachments/assets/a710b63c-5153-4033-af64-a267d564500a)
