### ISSUE TITLE
"Insert into-" button in inventory

### ISSUE THREAD

**Issue by big-smitty** [CleverRaven/Cataclysm-DDA#49242]
# Is your feature request related to a problem? Please describe.
Micromanaging nested containers is pretty frustrating. One quality of life addition that seems easy-ish to implement would be an option when viewing an item to "insert into" some other container.

# Describe the solution you'd like
When viewing an item, you should be able to insert it into another container from that menu.  
The current procedure is to exit out of the item menu, find the container, then (i)nsert the item. Its tedious.

# Additional context
This menu specifically: (include an option to insert this box of duct tape into another container, eg. a backpack)
![image](https://user-images.githubusercontent.com/85451361/121396155-f0646f00-c907-11eb-9c39-be617aab8a33.png)

**Comment by AveaCallister** [comment]
I initially thought the insert command implied inserting the currently viewed item into another item.
Just like how Disassemble, Wield, Open Throw are all actions done to the viewed item itself.
I propose we have "fill" and "insert" commands.

You can "insert" the viewed item into another item.
You can "fill" the viewed item with another item.

This is a linguistic pet peeve. 💯

**Comment by scorpion451** [comment]
Extending the "container" mode of the advanced item window to work for non-liquid container items would also go a long way to easing the frustration of working with the pocket system- just let me manually look at what's in a given box or bag in a proper interface, and add and remove stuff from it.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
