### ISSUE TITLE
Knit scarf requires the same tool level twice.

### ISSUE THREAD

**Issue by Xindage** [CleverRaven/Cataclysm-DDA#49244]
# Describe the bug
It's pretty simple both the long and the normal Knit Scarf requires a tool of 1 knitting quality, but it's required twice for some reason.

# Expected behavior
Requires the tool just once

# Screenshots
![image](https://user-images.githubusercontent.com/6380147/121438956-50d0cc00-c95b-11eb-98f6-d4b67d0d509a.png)

# Versions and configuration
- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.2 LTS; Release: 20.04; Codename: focal; 
- Game Version: 39074ba [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [    Dark Days Ahead [dda],    Disable NPC Needs [no_npc_food],    Bionic Professions [package_bionic_professions],    Aftershock [aftershock]]

**Comment by Saicchi** [comment]
The `tailoring_wool_knitting` requirement groups adds yarn and `KNIT` level 1 quality.
Removing `"qualities": [ { "id": "KNIT", "level": 1 } ],` from both `knit_scarf` and `long_knit_scarf` recipes in `data/json/recipes/armor/head.json` should be enough to fix it.

**Comment by Delta5861** [comment]
I believe that you need two knitting needles to knit anything IRL, so I don't think this is a bug.

**Comment by Saicchi** [comment]
The description for knitting needles say `A pair of stout wooden needles with round ends used to turn thread and yarn into cloth.`. So that should not be a problem.

**Comment by Delta5861** [comment]
Ah yes, I see. Nevermind then.
