### ISSUE TITLE
Idea: Achievements based on buying and selling to vendors and getting certain conversational variables.

### ISSUE THREAD

**Issue by faefux** [CleverRaven/Cataclysm-DDA#49254]
# Is your feature request related to a problem? Please describe.
No problems but with the new achievements system I had an idea.

# Describe the solution you'd like
The idea is to be able to have achievements such as 'Sell X of Y to Z' for example, 'Arms Dealer: You sold over 50 guns to any trader' or 'Free Merchant: You traded over 9000 worth of goods to the free merchants (either from the broker or the trader). I think we could get a few fun achivements this way. '

Another idea would be to have certain achievements gained when you get a certain variable from an NPC interaction. For example maybe on becoming a Marshal for the Old Guard the quest giver assigns you a regular jsonized conversation variable which the achievements code check before giving you the achievement 'Marshal', but preferably with a better name than that.

Anyways, I hope that this is readable, I think it would be a nice way for people to add various Achievements through JSON.  Just my two sense.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
