### ISSUE TITLE
Folding Gun Stock Should Reduce Some Lengths 

### ISSUE THREAD

**Issue by Comzav36** [CleverRaven/Cataclysm-DDA#49262]
# Is your feature request related to a problem? Please describe.
Folding Gun Stock Not Reduce Gun Lengths.
But It Should.

# Describe the solution you'd like
Folding Gun Stock Should Reduce Some Length. 

# Additional context
Cut Down Gun Barrel Does Decrease Length.
So Why Not Folding Stock.
Nomally Stock Is About 13.5 inch (34 Cm.) For AR Maybe Different On Another Firearm Type.

**Comment by actual-nh** [comment]
I seem to recall this being more complicated than it looked from prior examination of length being affected by modifications, but I may well be wrong.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-11712.
![изображение](https://user-images.githubusercontent.com/11132525/193310604-4cacd684-3f5d-4a51-8e3e-acaa41bad3e5.png)
![изображение](https://user-images.githubusercontent.com/11132525/193310615-caffc8b9-40b9-4e6f-b4a3-03418217dc55.png)
