### ISSUE TITLE
Pressuring bleeding wounds is too effective at high lvls of first aid

### ISSUE THREAD

**Issue by SuddenEyePuncture** [CleverRaven/Cataclysm-DDA#49269]
# Is your feature request related to a problem? Please describe.
At high first aid levels (4+) pressuring a bleeding wound stops heavy bleeding in under 30 seconds, making tourinquets, bandages, etc. almost useless. I don't think any doctor can close an arterial bleeding so fast with bare hands.

# Describe the solution you'd like
Pressuring a wound should be similar to tourinquets. It does't close a wound but makes it bleed less. High first aid levels should make bleeding reduction more effective, but any serious bleeding shouldn't magically go away.

Players should use bandages or hemostatic powder to stop bleeding, instead of standing for a minute waiting for it to go away. Pressuring a wound should be used as a last resort if you have no other options. Probably it should be possible to pressure bleeding while walking, although less effective, since players would still have to bandage themselves.

In my opinion this change would make players to use blood-stopping aid more, especially at high levels of first aid.

# Describe alternatives you've considered
Leave it as it is. Bleeding is mostly a problem for new characters, so it may be harder to pass early game alive. Real in game situations usually leave you with multiples bleedings and pressuring is not much of a help here, unless your first aid skill is high.

**Comment by Zireael07** [comment]
Counterpoint: https://en.wikipedia.org/wiki/Clint_Malarchuk#:~:text=Malarchuk%20is%20known%20for%20surviving,causing%20immediate%20massive%20blood%20loss.

This guy's athletics trainer, a former US Army combat medic, pinched the artery shut long enough for doctors to arrive (which I estimate took more than a minute).

That said, we could make pressuring a wound work less or not at all when moving around...?

**Comment by SuddenEyePuncture** [comment]
> Counterpoint: https://en.wikipedia.org/wiki/Clint_Malarchuk#:~:text=Malarchuk%20is%20known%20for%20surviving,causing%20immediate%20massive%20blood%20loss.
> 
> This guy's athletics trainer, a former US Army combat medic, pinched the artery shut long enough for doctors to arrive (which I estimate took more than a minute).
> 
> That said, we could make pressuring a wound work less or not at all when moving around...?

Your example confirmes my point. Trainer could hold the bleeding, but he didn't make it stop completely. Doctors still had to apply treatment to stop the bleeding.

In game you can hold an arterial bleeding for a minute and it will stop completely without any bandages.

**Comment by Venera3** [comment]
For small wounds ("diffuse" bleeding) putting pressure on it with or without a bandage allows for a clot to form and can stop most of the bleeding provided the clot isn't disturbed. Large wounds, that include a few blood vessels, especially if one of them is an artery shouldn't stop bleeding unless you cut off blood flow (by applying a tourniquet or pelvic sling, or putting pressure in the appropriate area- *not* on the wound itself) and patching/ligating the offending artery - or in a worst-case scenario amputation of the limb.

So, as it stands ingame bandages, hands and hemostatic powder are all massively overpowered meaning the one realistic option for life-threatening haemorrhages (tourniquets) don't see any use. How I'd redo it would be to add a hard ceiling to which bleed intensity bandages/manual compression can actually stop, and for anything above that bandages would do nothing and compression would apply a worse and tiring tourniquet effect - the duration stays the same but the flow rate is capped. Higher skill levels should allow for advanced treatment, same as NPC surgeons - that stuff will need to happen in some form for the infection overhaul as well, and amputations need a lot of limb stuff that will probably happen in the next cycle.

**Comment by actual-nh** [comment]
Side comment from RL personal (post-surgical) experience - before assuming that "diffuse" bleeding will respond to pressure, check to make sure the person isn't on anticoagulants...

**Comment by actual-nh** [comment]
Ping: @I-am-Erk?

**Comment by RAldrich** [comment]
Addressed by #61726 if anyone wants to mark this as resolved.
