### ISSUE TITLE
Introduce logic to detect or autocorrect duplicate tools

### ISSUE THREAD

**Issue by danielkwinsor** [CleverRaven/Cataclysm-DDA#49266]
# Is your feature request related to a problem? Please describe.
Recipes sometimes require duplicate tools for an unknown reason, probably inheritance.  Besides being glaring, it makes it difficult to decipher if the tools required are really intended or not.  (for this second part consider all the [bio]chitinous armor sequence of recipes, and the screenshots)

# Describe the solution you'd like
I want recipes autocorrected, rather than just linted

# Describe alternatives you've considered
Manual auditing

# Additional context
See #49244 

<img width="912" alt="Screenshot 2021-06-11 211714" src="https://user-images.githubusercontent.com/2822992/121764678-9677cb00-cafa-11eb-952a-baf597621acb.png">
<img width="936" alt="Screenshot 2021-06-11 211802" src="https://user-images.githubusercontent.com/2822992/121764679-97106180-cafa-11eb-9f4f-8c34c2ad6ad9.png">

**Comment by leemuar** [comment]
probably relates to #49244

**Comment by anothersimulacrum** [comment]
Added in https://github.com/CleverRaven/Cataclysm-DDA/issues/51086
