### ISSUE TITLE
Feature request: spell effect to leap

### ISSUE THREAD

**Issue by KittyTac** [CleverRaven/Cataclysm-DDA#49267]
# Is your feature request related to a problem? Please describe.
I have always wanted a spell equivalent of the leaping special ability some monsters have.

# Describe the solution you'd like
Add a new spell effect: `leap`. It would function like a targeted, short-ranged teleport but it wouldn't allow the user to go through walls or any creatures larger than small in size. This would allow: a balanced targeted "teleport" for Magiclysm (instead of random) and for vanilla it would allow, say, feline mutants to actually pounce at prey like a cougar (with a new mutation with the "spell" attached, like Attack Barbs does).

# Describe alternatives you've considered
Not adding this.

# Additional context
N/A.

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
