### ISSUE TITLE
Making A Gravel Floor And Deconstructing it Makes Infinite Rocks 

### ISSUE THREAD

**Issue by Ferride** [CleverRaven/Cataclysm-DDA#49263]
When you create a gravel floor, it only requires 100 pebbles. However, when you deconstruct it as furniture, it creates near a thousand pebbles and a few rocks, allowing you to clone rocks and pebbles.

1. Create a gravel floor
2. Deconstruct it
3. Rinse and repeat

I expected to get less pebbles than I put in, as I can't think of any logical reason for getting more pebbles.

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 25abf78 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by I-am-Erk** [comment]
Sounds like both of them need adjusting; rocks are a bit large to find in gravel, so it should just be pebbles, and the construction cost should be much higher.

**Comment by chrispikula** [comment]
So, I just noticed that the smoking rack also gives extra rocks, when constructing and simple-deconstructing it.

**Comment by robotic-gamer** [comment]
gravel floor seems to be poorly implemented as other issues with it:
- it can be smashed easily (str12 with quarterstaff)
- it prevents furniture moved over it
I mentioned these issues (including the construction/deconstruction cost mismatch) in #48426
