### ISSUE TITLE
The game crashes when i try to drop items

### ISSUE THREAD

**Issue by Smilijags** [CleverRaven/Cataclysm-DDA#49273]
![Captura de Tela (55)](https://user-images.githubusercontent.com/85803973/121786152-7a286c80-cb94-11eb-903c-2a505d50d438.png)

# Describe the bug

When i use DROP or MULTIDROP the game crashes

it's a crash

# Steps To Reproduce

# Expected behavior

# Screenshots

# Sorry if i had did it something wrong
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6642729/save.zip)

**Comment by Zireael07** [comment]
You haven't given the version you're on, so assuming this is a duplicate of #49050, try any build after deb7618

**Comment by Smilijags** [comment]
> You haven't given the version you're on, so assuming this is a duplicate of #49050, try any build after [deb7618](https://github.com/CleverRaven/Cataclysm-DDA/commit/deb761881fc4979db1e87f79289990bfb28f571a)

well i put there but don't apear

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 099e4a5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    C.R.I.T Expansion Mod [crt_expansion],
    Graphical Overmap [Graphical_Overmap],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player icon, retrodays [sees_player_retro]
]

**Comment by Theawesomeboophis** [comment]
> > You haven't given the version you're on, so assuming this is a duplicate of #49050, try any build after [deb7618](https://github.com/CleverRaven/Cataclysm-DDA/commit/deb761881fc4979db1e87f79289990bfb28f571a)
> 
> well i put there but don't apear
> 
> * OS: Windows
>   
>   * OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
> * Game Version: [099e4a5](https://github.com/CleverRaven/Cataclysm-DDA/commit/099e4a53685d070f6c452c7f3a521e78a4ca7439) [64-bit]
> * Graphics Version: Tiles
> * Game Language: English [en]
> * Mods loaded: [
>   Dark Days Ahead [dda],
>   Disable NPC Needs [no_npc_food],
>   Bionic Professions [package_bionic_professions],
>   C.R.I.T Expansion Mod [crt_expansion],
>   Graphical Overmap [Graphical_Overmap],
>   sees-player icon, HitButton_iso [sees_player_hitbutton],
>   sees-player icon, retrodays [sees_player_retro]
>   ]

Please update to current version, as this has been fixed, if problem persists after update, report back, as there is a chance it may have returned.

**Comment by PatrikLundell** [comment]
A very common reason things you write in the bug description doesn't appear is that the template uses comments that are very easy to miss to remove (or, at least, remove correctly/completely), resulting in the info you wrote being hidden inside the comments.

**Comment by actual-nh** [comment]
No news is good news in this case, I think.
