### ISSUE TITLE
Bat is short

### ISSUE THREAD

**Issue by big-smitty** [CleverRaven/Cataclysm-DDA#49272]
# Describe the bug
The titanium bat is short
4 inches bat

# Steps To Reproduce
1. See Titanium bat
2.  It is short

# Expected behavior
Bats are long. Make bat longer

# Screenshots
![image](https://user-images.githubusercontent.com/85451361/121785817-daa5b280-cb70-11eb-8796-f6e99e33838b.png)

# Versions and configuration

- OS: Win 10
- Version: experimental 38074ba, released 05/25/21@1559
- Graphics: Tiles
- Language: en-us
- Mods: Aftershock, stats through kills, Magiclysm

# Additional Context
Long bat
![image](https://user-images.githubusercontent.com/85451361/121785862-2b1d1000-cb71-11eb-9415-4dda0c7da488.png)

**Comment by Theawesomeboophis** [comment]
How long, on average, is a regular titanium bat IRL?

**Comment by big-smitty** [comment]
![image](https://user-images.githubusercontent.com/85451361/121785958-d201ac00-cb71-11eb-9497-016a66ce3611.png)

**Comment by Theawesomeboophis** [comment]
I looked it up, titanium bats in real life are about 32-34 inches, slightly shorter than a wooden bat according to a website selling them.
Website Here: https://www.justbats.com/product/2021-mizuno-titanium--10-fastpitch-softball-bat--f21titanium/33676/.

**Comment by Theawesomeboophis** [comment]
Would that make it a polearm, I'm not sure what is and isn't a polearm, but 32 inches seems large for game standards?

**Comment by Salty-Panda** [comment]
Already fixed #49045
