### ISSUE TITLE
Heating up puddles

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#49275]
# Describe the bug

I heated up a puddle.  This is odd.

# Steps To Reproduce

Spill some water.
Heat it up.

# Expected behavior

Not being able to heat up a liquid you can't pick up.

# Alternatives

I guess we press the hot kettle into the ground to heat up the liquid?

# Screenshots

![image](https://user-images.githubusercontent.com/22281606/121788350-d5a12d00-cb89-11eb-9bf8-53bc6dbee551.png)

# Versions and configuration

Windows, tiles, 2021-06-12-0631
# Additional context

**Comment by Saicchi** [comment]
Can confirm on `0.E-10700-g0f965c0184`, tested with a hotplate, not only water it extends to any liquid the player can heat up.
