### ISSUE TITLE
Randomizing New Scenario/Character repeatedly results in 'Could not find bodypart' error

### ISSUE THREAD

**Issue by EchoingZen** [CleverRaven/Cataclysm-DDA#49282]
# Describe the bug
When you create a new game using the Random Character option, repeatedly rerolling everything ('^') will cause a 'Could not find bodypart' error.

Here is the bug that appears:
```
 DEBUG    : Could not find bodypart hand_l in Refugio Monroe's body

 FUNCTION : bodypart* Creature::get_part(const bodypart_id&)
 FILE     : src/creature.cpp
 LINE     : 1703
```
('Refugio Monroe' is the randomly generated name)

# Steps To Reproduce

1. From the main menu, select New Game
2. Select Random Character
3. If needed, create a new world. (Default mods I had loaded were 'dda', 'no_npc_food', and 'package_bionic_professions')
4. When previewing the random character, repeatedly press (or hold) the '^' key to randomize everything.
5. After sometime, you should get this error. It seems really random, as it took anywhere from 5 seconds to 4 minutes to get it to occur. (Most likely, it some specific scenario/profession combo, wish I knew more to help figure it out)

# Expected behavior

Randomizing everything should not crash the game, and just randomize scenario/profession

# Screenshots
N/A

# Versions and configuration

 - OS: Windows 10
 - Game Version: 4637dd8
 - Graphics version: Tiles
 - Ingame language: System Language (English)
 - Mods loaded: 'dda', 'no_npc_food', and 'package_bionic_professions'

# Additional context
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6643347/debug.log)
No crash.log was generated

**Comment by ZhilkinSerg** [comment]
DEBUG    : Could not find bodypart hand_l in Roberta Jung's body

 FUNCTION : bodypart *Creature::get_part(const bodypart_id &)
 FILE     : /home/runner/work/Cataclysm-DDA/Cataclysm-DDA/android/app/jni/src/../../../../src/creature.cpp
 LINE     : 1703

**Comment by ZhilkinSerg** [comment]
I guess `set_body();` should be called before adding any traits.
