### ISSUE TITLE
Two by fours reference should be removed. (string freeze block?)

### ISSUE THREAD

**Issue by Xindage** [CleverRaven/Cataclysm-DDA#49281]
# Is your feature request related to a problem? Please describe.
Yes, it's a slight a problem: Two by four was replaced by planks in game but the name of this item is always present around.

# Describe the solution you'd like
Replace 2b4 names by plank, it's very simple i think, but i suppose that string freeze will prevent this from happening.

# Describe alternatives you've considered
fix at least the search menu text from crafting menu.

# Additional context
![image](https://user-images.githubusercontent.com/6380147/121796354-b8527a00-cbee-11eb-9d04-66b7fb4f7d42.png)
![image](https://user-images.githubusercontent.com/6380147/121796377-e33cce00-cbee-11eb-920c-62c76fc85d6a.png)
![image](https://user-images.githubusercontent.com/6380147/121796399-09626e00-cbef-11eb-87c5-dc311064c610.png)

**Comment by BrettDong** [comment]
IIRC this has been dealt with in #47709.

**Comment by Xindage** [comment]
oh sorry i'll close this so.
