### ISSUE TITLE
Nighttime OM visibility with night vision

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#49280]
# Describe the bug

If you climb a silo/radio tower/any other high building during the day, you get consistent results only depending on your equipment (binoculars, etc).
If you try doing it at nighttime, then, first of all, you have to have a source of night vision. This is fine. 
Which is *not* fine is even if you have NV, actually getting a map solely depends on... cloud coverage at your location. If it is cloudy *at your OMT*, you will see nothing at all. If it is not, you get same view distance as in daytime. If your OMT is unclouded then you get full daytime vision even if there are clouds over other tiles.

# Steps To Reproduce

get some means of achieving NV(goggles, mutation, cbm, whatever)
find a silo/radio tower
save
debug clear weather on your tile, check map reveal radius
reload
debug cloudy weather on your tile, note that your character can't see shit

# Expected behavior

Either it should follow daylight rules, as in no reliance on weather, OR it should actually check weather over all tiles that would be revealed in case of perfect conditions and hide ones with bad enough conditions (based on weather, light level, and distance).
Also, nighttime map reveal radius should probably be reduced compared to daytime even if you do have NV?

# Versions and configuration
- OS: Windows 7x64
- Game Version: a76f7e8 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills],
    Bionic Professions [package_bionic_professions]
]

**Comment by Psiclops** [comment]
Night vision is not the same as day vision, and the revealed radius should be much smaller, especially if binoculars are involved. Adding telescope or binoculars should have zero impact with technology granted night vision at night. Perhaps magical or biological night vision could work slightly differently.

**Comment by actual-nh** [comment]
> Night vision is not the same as day vision, and the revealed radius should be much smaller, especially if binoculars are involved. Adding telescope or binoculars should have zero impact with technology granted night vision at night. Perhaps magical or biological night vision could work slightly differently.

Telescopes (and thus, to a lesser degree, binoculars) gather light from a wider visual surface and thus effectively intensify what light is present at the smaller eyepiece. IR vision would likely not be helped by such, however, unless specifically designed to.

**Comment by GGgatherer** [comment]
Well, question of reveal radius aside, the fact that you can't see anything on the map if exactly one OM tile, the one you're standing on, is clouded, doesn't make sense. After all, you're looking at other tiles, not the one you're on.

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
