### ISSUE TITLE
MacOS version not reading save files in Application Support

### ISSUE THREAD

**Issue by linonetwo** [CleverRaven/Cataclysm-DDA#49297]
# Describe the bug

This release https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2021-06-14-0542

Don't read things in `Library/Application Support/Cataclysm`

My last tried version is b11572, which is using things and mods in `/Users/linonetwo/Library/Application Support/Cataclysm/{mods,save}`

# Steps To Reproduce

Things should be store in `/Library/Application Support/Cataclysm`, so when install new version, things won't get overwrote.

# Screenshots

<img width="1109" alt="Screen Shot 2021-06-14 at 20 55 35" src="https://user-images.githubusercontent.com/3746270/121895553-f2d52780-cd52-11eb-9351-bff03fae868c.png">

# Versions and configuration

 - OS: MacOS 11.4
 - Game Version:  2021-06-14-0542
 - Graphics version: [Tiles]
 - Ingame language: All
 - Mods loaded: not loading mods in `Library/Application Support/Cataclysm/mods`

# Additional context

**Comment by linonetwo** [comment]
@BrettDong Said it is related to `USE_HOME_DIR`, but I don't know where to modify.

**Comment by pehamm** [comment]
Can verify that when installing the precompiled experimental releases, the app wrapper will leave the savegames inside the wrapper, which leads to the savefiles becoming overwritten when installing the new versions, as macOS does not offter an option to merge both wrappers and overwrite the old versions, only complete replacement.

@BrettDong is there a way to set USE_HOME_DIR for the macOS build created by Github actions? Most non-technical users will probably pull their builds from there and have a high risk to inadvertently overwrite their saves while updating.
