### ISSUE TITLE
Cannot mix favourite and non-favourite liquids of the same type

### ISSUE THREAD

**Issue by pjf** [CleverRaven/Cataclysm-DDA#49292]
# Describe the bug

Reloading my canteen with clean water claims that it works, but does nothing.

# Steps To Reproduce

1. Load the [attached save](https://github.com/CleverRaven/Cataclysm-DDA/files/6645323/CantCombineLiquidsSave.zip)
2. Note the plastic canteen (right) holds two units of clean water, and I have a 2.5L caffeine in inventory with 3 units of clean water.
2. `r`eload, `plastic canteeen > clean water (cold) * (right)`
3. Observe the message "You refill the plastic canteen..."
4. Observe that no water has moved between any container.

# Expected behavior

Refilling the canteen transfers liquid, or gives a reason why it cannot.

# Versions and configuration

```
- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 16.04.5 LTS; Release: 16.04; Codename: xenial; 
- Game Version: 0.E-10773-g280c9fd44a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Alternative Map Key [alt_map_key],
    Bionic Slots [cbm_slots]
]
```

Game version is a76f7e8ef80def9607589352c84815dbf2678d66 with undeadpeople tileset applied.

# Additional context

- Possibly related to #44931?

**Comment by pjf** [comment]
Minor experimenting shows this might be the game refusing to mix favourited clean water with unfavourited clean water.

**Comment by pjf** [comment]
I can reproduce this with other types of favourite/non-favourite liquid combinations (eg: cat-tail jelly), and have updated the description accordingly.

**Comment by anothersimulacrum** [comment]
Same as https://github.com/CleverRaven/Cataclysm-DDA/issues/48120 ?

**Comment by pjf** [comment]
> Same as #48120 ?

Oh, almost certainly! Thank you for spotting that!

Should I go closing this ticket as a duplicate?

**Comment by anothersimulacrum** [comment]
Probably best to have only one issue open for it.

**Comment by pjf** [comment]
Thank you! Closing as duplicate of #48120
