### ISSUE TITLE
Make respirator CBM compatible with NPC

### ISSUE THREAD

**Issue by Aerotinge** [CleverRaven/Cataclysm-DDA#49307]
# Is your feature request related to a problem? Please describe.
NPC, like player, is able to come with asthma trait. Though they could use inhaler, a respirator should help them once and all.
But currently respirator CBM is incompatible with NPC, UI says "CBM not compatible with patient"

# Describe the solution you'd like
Make it compatible with NPC and make sure they do active it if there's bionic power left in their power storage.

# Describe alternatives you've considered
Or simply make it a passive effect to suppress asthma attack, since his/her respiratory system was augmented.

# Additional context

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
