### ISSUE TITLE
MIUI12.5 breaks CDDA, what can we do?

### ISSUE THREAD

**Issue by linonetwo** [CleverRaven/Cataclysm-DDA#49304]
# Describe the bug

After upgrading to MIUI12.5 (Android 11), CDDA's virtual joystick not working anymore, and fast access on the bottom is not working anymore, too.

I tried other games like MiniDayZ2, it works fine, so there must be something wrong in the Android shell of CDDA.

# Steps To Reproduce

1. Download CDDA 64 bit latest experimental in an Android MIUI 12.5 machine.
2. Try to swipe the virtual joystick
3. There's no way to bring up joystick

# Expected behavior

The touch should be working.

# Versions and configuration

 - OS: Android11 MIUI12.5.3
 - Game Version: Experimental build 2021-06-14-1544
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: vanilla

# Additional context

The old b11572 is not working too, so I think this Android shell is using some API that is not working in the latest Android?

**Comment by ZhilkinSerg** [comment]
Try disabling any accessibilty features that might be enabled on your device.

**Comment by BrettDong** [comment]
Duplicate of #48632.

**Comment by linonetwo** [comment]
Thank you. Solved by disabling FooViewer advanced permission in the Accessibility, which can perform automatically click.

Seems the discussion about the solution on the Android Shell side is in https://github.com/CleverRaven/Cataclysm-DDA/issues/45876 , so closing this.
