### ISSUE TITLE
Selecting Large Building/Mall (Food Court) location results in crash

### ISSUE THREAD

**Issue by EchoingZen** [CleverRaven/Cataclysm-DDA#49308]
# Describe the bug

Selecting Large Building/Mall (Food Court) location during character creation results in the following crash:
```
DEBUG    : Bad add_spawn(mon_zombie_fat, 1, -16, 8)

FUNCTION : void map::add_spawn(const mtype_id&, int, const tripoint&, bool, int, int, const string&, const spawn_data&) const
FILE     : src/mapgen.cpp
LINE     : 5353
```

# Steps To Reproduce

1. Create a Custom Character
2. Select Large Building for the scenario
3. On the character preview screen where you name the character, hit "/" to select the "Mall (Food Court)" location
4. The program should give the crash

# Expected behavior

You should start in the Mall (Food Court) location without it crashing

# Screenshots

# Versions and configuration
 - OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
 - Game Version: 9a81a10
 - Graphics version: Tiles
 - Ingame language: System Setting (English)
 - Mods loaded: 'dda', 'no_npc_food', 'package_bionic_professions'

# Additional context

**Comment by venum4k** [comment]
Just tested it myself, same error happened 7 times with different coordinates, continuing past the errors didn't result in a crash though. 
```

 DEBUG    : Bad add_spawn(mon_zombie, 1, -7, 22)

 FUNCTION : void map::add_spawn(const mtype_id&, int, const tripoint&, bool, int, int, const string&, const spawn_data&) const
 FILE     : src/mapgen.cpp
 LINE     : 5353

```
This was on 817307e

I tried once more on 9a81a10 and encountered the same error again, 4 times with no crash.
The game seems to work fine after the messages.

**Comment by EchoingZen** [comment]
Question in the meantime, is there any adverse side effects from starting with Mall (Food Court)?  Are these error putting mobs in invalid spots?  Just not generating them?  I'm one of those folks who wants to play the game "as intended".

**Comment by NetSysFire** [comment]
Can not reproduce this anymore, I did get some errors which appear related to #53830 though. No crash.

```
 DEBUG    : loading non-main map at (-140,654,0) which overlaps with main map (abs_sub = (-143,651,0)) is not supported

 FUNCTION : void map::load(const tripoint_abs_sm&, bool, bool)
 FILE     : src/map.cpp
 LINE     : 6699
 VERSION  : 0.F
```

**Comment by Night-Pryanik** [comment]
Can't confirm crash either, though I do have errors like @NetSysFire described.
