### ISSUE TITLE
Make mutations scale character sprites (e.g. Tiny, Large, and Huge)

### ISSUE THREAD

**Issue by Olaroll** [CleverRaven/Cataclysm-DDA#49315]
# Is your feature request related to a problem? Please describe.
When playing with a tileset, there's not much intuitive player feedback for the Tiny, Large, and Huge mutations. Having your player sprite change size would make the mutations feel more impactful and immersive.

The same goes for NPCs you might find in the wild. I think it would be pretty intimidating to encounter an NPC that looks visibly bigger than the rest.

# Describe the solution you'd like
Allow mutations to scale sprites, for both players and NPCs. The change doesn't have to be very big, just enough to be noticeable.

And just for clarity, what I mean is scaling all layers of the character sprite. This includes mutations, clothing, and wielded items. That way, nothing gets misaligned.

There should also be a way for tilesets to opt-in or opt-out of this feature, because not all would look good with it.

# Describe alternatives you've considered
Not changing anything.

# Additional context
I don't actually know just how much work this would take. If it's a lot, then this suggestion is probably not worth tackling.

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
