### ISSUE TITLE
No experimental build since 2021-05-28?! [Solved]

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#49329]
Is something wrong with the experimental build link? https://cataclysmdda.org/experimental/ The last version I can see there is 2021-05-28-1807.

**Comment by BrettDong** [comment]
Latest experimental builds are available for download at https://github.com/CleverRaven/Cataclysm-DDA/releases . 

Kevin tried to make the website update the link automatically but hasn't got it working.
