### ISSUE TITLE
Recipes do not recognize tools powered by UPS using UPS CBM

### ISSUE THREAD

**Issue by bobface11** [CleverRaven/Cataclysm-DDA#49321]
# Describe the bug

The power provided from Internal Unified Power Supply CBM does not count for tools using UPS in recipes.

# Steps To Reproduce

1. Spawn in a tool that needs batteries and convert its power supply to UPS.
2. Install UPS CBM to character and make sure it's turned on and has enough charges for a recipe requiring the tool.
3. Go to crafting menu and search for recipe. Option greyed out because tool doesn't have enough charges.

# Expected behavior

As long as bionic power has enough charges, recipe should use bionic power to power tool to craft item.

# Screenshots

![image](https://user-images.githubusercontent.com/6170954/122153266-d94de180-ce1f-11eb-965e-52241d57d1bf.png)
![image](https://user-images.githubusercontent.com/6170954/122153307-eb2f8480-ce1f-11eb-809c-af220769a8a7.png)
![image](https://user-images.githubusercontent.com/6170954/122153329-f84c7380-ce1f-11eb-9cf6-a6ee31f3be32.png)

# Versions and configuration

 - OS: Windows 10
 - Game Version: df08e8d
 - Graphics version: Tiles x64
 - Ingame language: English
 - Mods loaded: Aftershock, CRIT, Blaze Industries, StatsThroughSkills, TankMod Revived
 -->

# Additional context

UPS CBM does not work, but spawning in the UPS item works, and it takes charges from bionic power.

**Comment by Hirmuolio** [comment]
#48608 should fix this.
