### ISSUE TITLE
Magiclysm - need passive Attunement Force Mage ability 

### ISSUE THREAD

**Issue by Altogolik** [CleverRaven/Cataclysm-DDA#49326]
# Is your feature request related to a problem? Please describe.
For a long time, the last passive property of the magician is not added to the game, I am very waiting for it. Add it finally, Please. 
# Describe the solution you'd like
 Forceful: Melee damage x2  Passive feature 
# Additional context
![изображение](https://user-images.githubusercontent.com/48449647/122207366-bae0f800-ceaa-11eb-8023-90de57ffa5c8.png)

**Comment by Maleclypse** [comment]
It won't be added until 0.F drops as we are in string freeze.

**Comment by KorGgenT** [comment]
this is a duplicate of the overall issue with the attunement list #45011
