### ISSUE TITLE
ench_effects in relic_data is not saved

### ISSUE THREAD

**Issue by MarsM0nd** [CleverRaven/Cataclysm-DDA#49334]
# Describe the bug

An item that does have some relic data containing ench_effects receive the effect when spawned, but when they are saved, that information is not saved, and such lost upon loading

# Steps To Reproduce

1. Spawn in an item with relic_data containing ench_effects
2. Notice ench_effects work without problems
3. Save and load the game
4. Notice ench_effects are gone

# Expected behavior

I expected ench_effects to not work at all, or them to be saved and loaded, so an item stays consitent

# Screenshots

# Versions and configuration

# Additional context

Cata++'s ACS-74 stealth cloak is the affected item that caused this issue to be found.

**Comment by ZhilkinSerg** [comment]
Do you have an example not from a third-party mod?

**Comment by MarsM0nd** [comment]
As far as i can tell, no json in the repository uses ench_effect in relic_data, only for an enchantment that may be later used in relic_data. It's rarely used in general, so i did just text search for ench_effect and checked. I figured the issue is rather inconsistency in the code, rather than a broken mod in the repository.
