### ISSUE TITLE
Wind seems to not exist, and when it does it makes wind turbines generate more than they say they should

### ISSUE THREAD

**Issue by Nictron** [CleverRaven/Cataclysm-DDA#49332]
Wind (and wind turbines) not working correctly in current experimentals

# Steps To Reproduce

1. Make new world in latest experimental
2. Make vehicle, attach some wind/large wind turbines
3. Notice that it is not generating any power
4. Use debug mode to force wind to blow
5. Notice that that seems to be generating possibly too much power, now? (a vehicle with 2 large and 2 regular wind turbines on the roof of a building was generating 1200w power with a 10mph wind which seems... a lot? Given large turbines say they only generate about 30w)

It seems like wind turbines, rather than generating up to an expected value, are generating that value PER MPH of wind speed... when there is any wind, which it appears there isn't any by default?

# Expected behavior

Wind should generally exist without having to be kicked into action via debugging.

I'm not sure if wind turbines are generating more than expected, or if their description is just misleading; it's been a while since I played before this, so I am not sure whether 'expected behaviour' is wind turbines having a vastly lower output than this, or if they just need their description updating.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 47a2b01 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills]
]

# Additional context

I tried reverting back a few versions; someone on Reddit reported that 2021-06-14-0542 worked for them, but I created a new world then and wind was still not working for me, so I am not sure which version has caused this. Wind did work in the previous stable build, however.

**Comment by RenechCDDA** [comment]
Can't say that I've seen this problem despite using a wind turbine. Were you testing inside or by a building? (Your post seems to suggest you may have been).

Buildings block wind. You'll need open air or otherwise to be a good distance away from buildings for it to register wind.

**Comment by Nictron** [comment]
> Can't say that I've seen this problem despite using a wind turbine. Were you testing inside or by a building? (Your post seems to suggest you may have been).
> 
> Buildings block wind. You'll need open air or otherwise to be a good distance away from buildings for it to register wind.


First time I built it, it was near a building. Then I built on the roof (which I don't think counts as near? But I'm not sure there) 

Just as a test, though, I decided to stick a super simple turbine vehicle out in the middle of nowhere, and...
![capture_086_17062021_172138](https://user-images.githubusercontent.com/17142047/122436341-a7a85800-cf90-11eb-9ef6-eff46b445c74.png)

![capture_087_17062021_172141](https://user-images.githubusercontent.com/17142047/122436354-aa0ab200-cf90-11eb-9930-1bf7c02bab97.png)

**Comment by jumjummju** [comment]
I'm having the same issue, and also when checking the sidebar where you can set it to show wind it always shows "Calm" for me, even at the top of radio towers (which are supposed to, and I know indeed used to have fairly high winds basically constantly). I even passed time and after two weeks there was just 0 wind anywhere unless I forced it.

**Comment by Nictron** [comment]
> I'm having the same issue, and also when checking the sidebar where you can set it to show wind it always shows "Calm" for me, even at the top of radio towers (which are supposed to, and I know indeed used to have fairly high winds basically constantly). I even passed time and after two weeks there was just 0 wind anywhere unless I forced it.

Yeah, same on the wind showing permanently as Calm, always 'blowing' south. In one game I tried debugging in that  CBM that gives you an exact weather reading and it said wind was 0.0mph; not sure if there's a debug command that tells you the exact wind like that a bit more easily, but if there was I missed it.

**Comment by OldFriendEr** [comment]
Can confirm, there is no wind nor on the roof nor in the fields for the entire week. Got a cbm that tells the wind speed, the direction is from the north, but the speed is always 0m/s

**Comment by Tamiore** [comment]
"No wind" issue still seems to be present as of Game Version: d0fb1f3

On a side note, the wind seems to be work fine if you change it via debug menu. So the issue seems to be with whatever function is supposed to change wind naturally.

**Comment by actual-nh** [comment]
<https://github.com/CleverRaven/Cataclysm-DDA/commit/0a130e43935302e42568b2156a3e11dfad10e2c6> pointed out by @ralreegorganon on discord - thanks very much: `The eagle-eyed viewer will note that in the change, it stopped pulling the wind direction and weather off of the weather object, so now it never actually takes the real weather and assigns it to the variables (winddirection vs w.winddirection).`

**Comment by actual-nh** [comment]
Ping: @ZhilkinSerg?

**Comment by ZhilkinSerg** [comment]
Probably this:

![image](https://user-images.githubusercontent.com/16213433/126853252-c4821afc-b2ff-4365-a54c-0c5619d9419c.png)

**Comment by ZhilkinSerg** [comment]
Seems to be working (weather change is sped 10000 times):

https://user-images.githubusercontent.com/16213433/126853601-70d12435-caa7-4893-b7b1-99439ffcaa08.mp4
