### ISSUE TITLE
Feature request: Triffid fertilizer

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#49337]
Vaguely related to #49302.

I discussed this in our IRC channel a bit. There is currently, apart from using the debug menu and herding triffid queens (which is a bit risky), no way to grow trees. There are certain reasons why the player wants to grow trees:
- Making an orchard
- Because they look nice
- Sustainable source of certain materials

The solution could be triffid fertilizer, which harnesses the triffids power to grow trees and other vegetation in a very short time.
One could harvest oil or organs from triffid queens to craft this special fertilizer, which can be used to grow a tree in a short time.

The potential problems arising here are balance issues. Being able to grow a lot of trees in a short time may break the gameplay a bit, especially when one is abusing them as organic replacements of reinforced concrete walls. I thought of the following things to balance it out:
- Make the material harvested from triffid queens rare and/or diluted since it is a very special substance and hard to harvest.
- The tree will not grow instantaneously but rather in a week or even a month. The reasoning could either be the diluted material or because it does not come from a live triffid.

But how do we even grow trees? Where do we get the saplings from?
As far as I know most trees produce some kind of fruit. Oaks produce acorns, fruit trees produce, well, fruit but there are a few which do not produce anything relevant, like willow and birch trees. You can not easily create saplings from bark. Maple trees have a very similar problem.
In reality, they all produce little seeds. Birch seeds for example look like this:
![](https://upload.wikimedia.org/wikipedia/commons/8/80/European_Birch_Seeds.JPG)

It would be impractical if the player would get 500 of those every time they harvest a tree, so there should be an extra action for harvesting those seeds in the right season.

Someone in the IRC channel also suggested grafting, but I do not know much about it.

**Comment by krulunio** [comment]
> But how do we even grow trees? Where do we get the saplings from?

How about cutting off branch from living tree instead of using seeds? It works IRL, it should work with alien fertilizer.

**Comment by Mom-Bun** [comment]
Trees take so long to grow, it is impractical to do this, and anyway, this isn't really necessary, you could just walk 2 overmap tiles in a forest and find hundreds of trees, they aren't exactly in rare supply

**Comment by Zireael07** [comment]
It's less about trees imho (it could be used for plants, too, I imagine) and more about giving the player a good reason to fight triffid/mycus.

**Comment by PatrikLundell** [comment]
If this magic substance is capable of growing mature trees in an incredibly short time, it's probably capable of making a cut branch sprout roots and mature into a tree as well, as suggested by krulunio, and it also has the advantage of not requiring a specific (seeding) season, although it still shouldn't work while the ground is frozen.

I agree such a substance should be in rather limited supply of e.g. 10 doses per queen. You'd also need to introduce branch objects for each type of tree in the game (plus the code required to actually make this magic work).

As Zireal07 noted, it would provide a reason to fight triffids. If the magic fertilizer was in limited supply, I probably wouldn't use it on other plants, even though the option to plant useful shrubs where you want them would be nice (but I'd still probably not use it, as those plants can be farmed currently).

**Comment by natsirt721** [comment]
I do like the idea of incentivizing combating triffids to get powerful agricultural components. However, I can't really advocate for using that to grow trees. The timescale just doesn't work out without it. Imagine not knowing about triffid fertilizer and you go to plant some trees. Those are going to take at least a decade to be anything more than a 'young tree' level of tree-ness, and currently those can't bear fruit or be useful. IDK, I like the concept but I don't think it works out this way.

**Comment by NetSysFire** [comment]
The time to grow a tree without it is way too long, I agree.

Ignoring that for the moment, here are some ideas to actually get saplings from branches and planting them:

1. Apply/use (`%`) a knife or something similar near a tree to cut off a branch/twig.
2. The resulting item will probably have a short time before it dries out/rots.
3. It needs to grow roots before it can planted. Making an item similar to a tanning leather hide which needs time before it is done, one could craft something out of the twig, a bottle, a bit of water and maybe a bit of string to hold it in place? https://en.wikipedia.org/wiki/Cut_flowers#Longevity may apply here, so a knife may be required, too.
4. When the item is done and it sprouted roots inside the bottle, it should be planted inside a shallow pit.
5. The fertilizer could be applied now.

I just had an idea to get more mature trees easier, LMOE shelters (or labs or similar) may contain "tree kits", which is basically a barely mature tree in a big case which is keeping it alive/in stasis. It is ready to plant and would produce a grown tree. The problem here is that there are not any tree growing mechanics. This is just a random idea.

The reason why the player may want to grow trees is farming. Especially fruit and juniper trees may be worth growing.

**Comment by PatrikLundell** [comment]
The time scale for growing trees without "magic" is too long to be practical in the game, and thus there's little to no reason to spend effort on implementing it, and I don't see LMOE shelters containing "tree kits" as that's not something that exists in the real world. They've already planted useful trees outside the shelters for that purpose.

With "magic", I think it ought to be possible to skip the root growing preparation and just plunk down the sapling/branch (which should be fresh) in a shallow pit in the unfrozen ground together with some "magic" fertilizer and be done. The real world root growth stimulation is taken care of by the fertilizer.

**Comment by robotic-gamer** [comment]
actually a simpler solution would be to allow digging up a tree with the help of a steel boom. the planting it in a pit. this appears to be possible since:
- a tree weighs about 14.385 tons
- a steel boom can lift 20 tons
- with enough digging you can separate the tree from the ground
- any root damage sustained can be treated with fertilizer and water (making the remaining roots job easier)
however impractical I like the idea of being able to add trees close to base since it removes the permanentness of cutting down trees, and makes the composition of trees surrounding your base irrelevant in the very late game. balancewise it would largely be just a convenience if the capability occurs after you are well equipped enough to travel unlimited distances since you could just get the tree resources over that large distance instead.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/poll-should-fruit-spawns-in-forests-be-nerfed/27538/11

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
