### ISSUE TITLE
Dropping item causes game to crash

### ISSUE THREAD

**Issue by UndeadMoose** [CleverRaven/Cataclysm-DDA#49348]
# Describe the bug

Starting up a game and then attempting to drop an item crashes the game

# Steps To Reproduce

1. Start up a game
2. Try and drop an item

# Expected behavior

Dropping an item shouldn't crash the game

# Versions and configuration

 - OS: Kubuntu 21.04
 - Game Version: 099e4a5 [64-bit]
 - Graphics version: Tiles
 - Ingame language: English

# Additional context

When the game crashes no crash log is generated.

**Comment by BrettDong** [comment]
Probably a duplicate of #49050. Have you tried the latest experimental build?

**Comment by UndeadMoose** [comment]
Yeah I tried the latest build it still happens

**Comment by anothersimulacrum** [comment]
And you're downloading that build from here https://github.com/CleverRaven/Cataclysm-DDA/releases ?

**Comment by UndeadMoose** [comment]
Yup that seems to work now. I was downloading the latest build from here https://cataclysmdda.org/experimental/
