### ISSUE TITLE
Bashable terrain with FLAT flag always receives collision from vehicle frames

### ISSUE THREAD

**Issue by pjf** [CleverRaven/Cataclysm-DDA#49346]
# Describe the bug

The `farm_dairy` and `farm_dairy_2` maps have lines of `t_splitrail_fencegate_c` and `t_gate_metal_c` gates respectively at the end of roads, and sometimes even with vehicles spawning behind them. However these gates act as a line of individual gates, and do not allow vehicle access, even when all are open.

# Steps To Reproduce

1. Explore or debug until you find a `farm_dairy` or `farm_dairy_2` map.
2. Look at the gates that connect it to the road

# Expected behavior

Vehicle-accessible sections of dairy farms have multi-tile gates with pully systems, so vehicles can pass.

# Extra notes

- @jtgibson01 has tracked this down to #49173, which adds bash data for split-rail fences, which causes them to participate in collisions.

# Versions and configuration

- Version: af4b28f40907e9807b3916f76deb62fe6ec8c673 (cdda-experimental-2021-06-17-2045)

**Comment by Maleclypse** [comment]
#49153 fixed this but it may not be fixed if the new PR that adds another mirror to the cube van goes through.

**Comment by Maleclypse** [comment]
I've added the Tiles label as I think this could be resolved by tileset makers creating a multitile option that shows them as one single gate.

**Comment by pjf** [comment]
> Edit: They do allow vehicles to pass if they are all open and the line of them is wide enough to allow passage. I agree with you that it looks weird on tilesets though.

They *do*? Hmm, I wonder why I ended up hitting the gate. Do all connected gates need to be open, or just enough to allow passage?

> I've added the Tiles label as I think this could be resolved by tileset makers creating a multitile option that shows them as one single gate.

Since gate tile has to be opened individually by hand, would it still look weird if some are open and some are not?

Many thanks!

**Comment by Maleclypse** [comment]
Just enough to allow passage but the fix to make the gate wide enough for the cube van is literally days old so your game may not have it.  Also I believe right after I increased the gate size someone increased the van size by adding a second mirror so there is literally only a few hours of build where you can get through the gate I'm betting.

**Comment by pjf** [comment]
As an update, I absolutely cannot figure out how the van is supposed to drive through the gate.

In [this save](https://github.com/CleverRaven/Cataclysm-DDA/files/6721674/CantDriveThroughGate.zip) the van (the mirrors on which I've removed) will impact with the gates, rather than drive through them.

**Comment by jtgibson01** [comment]
I loaded your save in an older 0.E Experimental build from March (0.E-10003-g48f45e8) and, after getting through the massive slew of bugs from loading a newer save in an older version, it works fine to drive through the fence.  So something may have changed in the vehicle code between March 10th and now that results in this problem.

**Comment by jtgibson01** [comment]
Propose renaming this issue to "Bashable terrain with FLAT flag always receives collision from vehicle frames".  That'll take a code level fix.

Hard to say whether #49173's added bash data should be reverted or whether the bug should be fixed, but this might be a blocker for 0.F. =)

**Comment by pjf** [comment]
@jtgibson01 : Oh my, this is some top-tier sleuthing! Renaming issue as proposed

**Comment by pjf** [comment]
@jtgibson01 : I can see that #49173 has added bash to both open and closed split-rail fences.

Having only *closed* split-rail fences bashable feels like a reasonable compromise if it works. That means one can still drive through an open gate, will still collide with a closed gate, and can still destroy gates as long as they're closed first.

**Comment by actual-nh** [comment]
Ping: @Tairesh?

**Comment by Tairesh** [comment]
I made this gate bashable in #49173 because most of other doors are bashable even in open state. Didn't think about vehicles with more than 1 tile width. I sure if it's a blocker for 0.F it should be temporary removed, but I think there should be some changes in vehicle code, maybe new flag for these "wide" gates, making them just indestructible seems like temporary workaround to me.

**Comment by Night-Pryanik** [comment]
Can't confirm on latest experimental as of 06 November 2024.
