### ISSUE TITLE
Mods' folders name convention

### ISSUE THREAD

**Issue by Tairesh** [CleverRaven/Cataclysm-DDA#49359]
# Is your feature request related to a problem? Please describe.
I'm always frustrated when seeing mods inside the `data/mods` folder. There are at least five different name styles.

# Describe the solution you'd like
All mods' folders should be named in same style, CamelCase, snake_case, SCREAMING_SNAKE_CASE, Sort_Of_This_Case, or even Sort-Of-That-Case.

# Describe alternatives you've considered
Leave it as is, It has no practical sense.

# Additional context
![image](https://user-images.githubusercontent.com/1105196/122595295-aacf4100-d081-11eb-93c5-dd6eeaa55570.png)
Five styles in a row!
![image](https://user-images.githubusercontent.com/1105196/122595743-52e50a00-d082-11eb-83b9-7ba52ac32f4d.png)
Why? Just why?

**Comment by Maddremor** [comment]
I personally think that the folder should have the same name as the mod ID, but that's just my personal taste.

**Comment by ZhilkinSerg** [comment]
It does not affect anything at all, so there is no sense to bother with rename.

**Comment by Saicchi** [comment]
I don't really care about the style as long as there is no space between in the folder name, but if I were to choose I'd prefer using lowercase snake_case.

**Comment by actual-nh** [comment]
> It does not affect anything at all, so there is no sense to bother with rename.

It does create a mild headache for scripts manipulating mod names, such as selecting mods for testing (@jbytheway?).

**Comment by jbytheway** [comment]
So long as there are no spaces, it's not a big problem for scripts.

I'm with @Maddremor - the folder names should match the IDs. That mismatch has caused me problems. But we shouldn't change the IDs; that would break everyone's saves.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
