### ISSUE TITLE
Judo belts are ridiculously hard to repair/reinforce

### ISSUE THREAD

**Issue by SariusSkelrets** [CleverRaven/Cataclysm-DDA#49354]
# Describe the bug

At tailoring 8, repairing a half-destroyed judo belt is more likely to damage than to repair it. Reinforcing an intact judo belt at that level is impossible

# Steps To Reproduce

1. Spawn a characther with 8 tailoring wearing a judo belt
2. Spawn a zombie so the belt can be damaged
3. Spawn a sewing kit and rags to repair it
4. Look at the odds 
5. Spawn an undamaged judo belt
6. Try to reinforce it

# Expected behavior

At this tailoring level, you can repair armor, backpacks and boots without a chance to fail. I expect a belt to work in the same way

# Screenshots

![judo belt hard](https://user-images.githubusercontent.com/68650913/122570917-3614ec00-d01a-11eb-8e53-e884ad60345f.png)
![judo belt hard 2](https://user-images.githubusercontent.com/68650913/122570949-3b723680-d01a-11eb-81f5-35052ba4f0f6.png)
![judo belt hard 3](https://user-images.githubusercontent.com/68650913/122570952-3c0acd00-d01a-11eb-935e-486011dde367.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-9280-g9dde4db-dirty [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

learning all the proficiencies didn't changed the odds at all

**Comment by anothersimulacrum** [comment]
Needs a `repairs_like`, because it has no recipe. It expect you to have tailoring 10.
