### ISSUE TITLE
Cant read with Atomic Nightlight

### ISSUE THREAD

**Issue by rizkiv1** [CleverRaven/Cataclysm-DDA#49367]
# Describe the bug
Cant Read books with atomic nightlight on vehicle

# Steps To Reproduce

1. Install atomic reading light
2. turn it on from vehicle menu
3. move to tile where installed part is, still cant read books

# Expected behavior
Can read books

# Screenshots

# Versions and configuration

OS: Windows 10
Game Version: f75db2f (based on CDDA Launcher)

# Additional context

**Comment by Maleclypse** [comment]
"A very dim light, self-powered by an atomic decay reaction that never stops. When turned on, it illuminates a single square inside the vehicle that isn't suitable for crafting."  Is the description of the vehicle part.  I assume that crafting and reading use the same level of light?

**Comment by rizkiv1** [comment]
seems yes, based on in game comparing between atomic readlight in inventory and atomic nightlight

**Comment by Zireael07** [comment]
I can't find the other issue right now, but IIRC it was already reported and closed as 'by design'
