### ISSUE TITLE
Breaking up recipe_food.json into more managable chunks

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#49374]
# Is your feature request related to a problem? Please describe.

recipe_food.json is nearly 7500 lines long, and covers everything from drinks to salad to cake to condiments to preserves.
This makes it an intimidating thing to patch.  Say you want to add batching or non-hydrokinesis requirements to some recipes, it feels that you leave a job unfinished when you only touch a few in the file, and leave the rest broken.

# Describe the solution you'd like

We already have ...\json\recipes\food\ &foo.json, so reducing recipe_food.json into it's bare amount of ungroupable recipes.

This will help with adding batching to a large number of recipes without batching, by grouping similar things better.

# Describe alternatives you've considered

I'd like to hear suggestions and ideas.

# Additional context

Of note, I'd like to not get hit with the string freeze with any PR's this directly contributes to.  Any changes as to text would ideally be part of a future discussion.

**Comment by Saicchi** [comment]
You could separate them by their subcategory.
| Subcategory | Recipes |
| :-- | :---: |
| CSC_FOOD_BREAD | 20 |
| CSC_FOOD_DRINKS | 74 |
| CSC_FOOD_OTHER | 69 |
| CSC_FOOD_VEGGI | 92 |
| CSC_FOOD_MEAT | 87 |

There are also a bunch of recipes which don't have a subcategory, and recipes like salt which should probably be using applied science instead of cooking.

**Comment by Maleclypse** [comment]
@mlangsdorf I wanted to get your opinion on this as it would be significant churn but might be valuable given the size of the file and the fact that many of the other food files exist already and so for example we have breads in both the bread file and the generic food file.

**Comment by chrispikula** [comment]
@Saicchi 
> You could separate them by their subcategory.

I think it comes down to granularity.  More than 30 recipes in a single file is quite a bit of work when one wants to make a change, and make sure it's consistent.

eg; make simple mixed liquids all have the same sort of batching, or that all boiling recipes provide water as a byproduct.  Neither of which is currently the case.

Would a file structure of the sort work with people?:

File name.json | Contents
------------ | -------------
Breads_Junk_Food | Cakes, Doughnuts, cookies, etc
Breads_Simple | Wastebread, bread, sandwiches
Breads_Pasta | Anything with noodles
Drinks_Alcoholic | Mixed Alcoholic Drinks
Drinks_Cooked | Any drinks that require heat sources to make
Soups | Woods Soup, Fish Soup, Ketchup Soup, etc
Condiments | Ketchup, Various spices, Mayo, etc
... | ...

Ideally keeping the number of recipes per file below 25 or so.

This does making finding specific recipes a little harder, but until we get a simple method to go back and forth between a spreadsheet and a bunch of little files, we can't have the best of both worlds.  And writing such a python script would take a solid week for me, at least.  No fun, and it'd be kind of brittle too.  There's always notepad++ (or your editor of choice) search within files in folder as a stopgap.

**Comment by natsirt721** [comment]
Instead of filename prefixes just use directories. That's what they're for after all.
```
recipes/food/
recipes/food/breads/
recipes/food/breads/bread.json
recipes/food/breads/pastries.json
recipes/food/pasta.json
recipes/food/drinks/
recipes/food/drinks/alcoholic_mixed.json
recipes/food/drinks/juices.json
recipes/food/drinks/hot_drinks.json

**Comment by atealein** [comment]
I would like to help out with this as I am digging in the food recipes as is right now, fixing and rebalancing some things. I am a bit worried that it will mess up some ongoing PRs and there isn't really a clear structure to how the final goal should look like. I the recommendation to use directory structure is still valid, I can open a draft PR and use this WIP structure? 

```
recipes/food/
recipes/food/unsorted.json
recipes/food/dishes/
recipes/food/dishes/bread.json
recipes/food/dishes/deserts.json
recipes/food/dishes/meat.json
recipes/food/dishes/pasta.json
recipes/food/dishes/soups.json
recipes/food/dishes/snacks.json
recipes/food/dishes/vegetarian.json
recipes/food/drinks/
recipes/food/drinks/alcoholic.json
recipes/food/drinks/cold_or_frozen_drinks.json
recipes/food/drinks/general.json
recipes/food/drinks/hot_drinks.json 
recipes/food/ingredients/
recipes/food/ingredients/batter.json
recipes/food/ingredients/dairy.json  
recipes/food/ingredients/fermenting.json
recipes/food/ingredients/nuts.json
recipes/food/ingredients/raw.json
recipes/food/preserved/
recipes/food/preserved/canned.json
recipes/food/preserved/dried.json
recipes/food/preserved/pickled.json
recipes/food/preserved/salted.json

```
