### ISSUE TITLE
Autoforage set to "bushes" also forages trees

### ISSUE THREAD

**Issue by kholat** [CleverRaven/Cataclysm-DDA#49376]
# Describe the bug

Set autoforage to only bushes, walk around a forest in the summer and things like peaches, apricots, cherries etc are also foraged.

# Steps To Reproduce

Set autoforage to only bushes, walk around a forest in the summer and things like peaches, apricots, cherries etc are also foraged.

# Expected behavior

It should not work on trees if selected for bushes only.

# Screenshots

N/A

# Versions and configuration

 - OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
 - Game Version: 989bcb8 (tiles)
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: Secronom, magiclysm

# Additional context

N/A

**Comment by OliveChukar** [comment]
Tested on  (cdda-windows-tiles-x64-2021-06-20-0737) with core content pack DDA only.  Setting autoforage to trees harvested all trees that could be harvested and not bushes.  Setting it to bushes had it harvest bushes and fruit trees but not willow or pine trees.

**Comment by chrispikula** [comment]
Long term, do we want to add another option to autoforage, ie, between bushes and trees, have 'edibles'?

I'm guessing what happened here is that fruit trees were added to the bush autoforage as they always give food.  Whereas when you think for foraging trees you think of getting non-food items.

**Comment by natsirt721** [comment]
I'd change the categories to 'edibles' and 'non-edibles'. That seems more in-line with the expected usecases. You either want food but not materials, materials but not food, or both food and materials. The source (tree vs bush) shouldn't really matter.

**Comment by chrispikula** [comment]
I don't know if you can know if a bush has edibles or not before it's foraged.  Berry bushes, yes, but regular ones?

Also, adding text will get this bap'd by the string freeze.

**Comment by natsirt721** [comment]
Thats a good point, I was considering the generic bush to be 'non-edible' but thats clearly not the case as they give both.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-5881. If this is still an issue, ping me and I'll reopen.
