### ISSUE TITLE
CTD when using blood draw kit on acid zombie corpse.

### ISSUE THREAD

**Issue by Solusphere** [CleverRaven/Cataclysm-DDA#49389]
# Describe the bug

When attempting to use a blood draw kit on an acid zombie corpse, the game immediately closes with no error message displayed. Other zombie types and using it on yourself work as expected.

# Steps To Reproduce

1: Use a blood draw kit on an acid zombie corpse
2: Game crashes.

# Expected behavior

Using a blood draw kit on an acid zombie should not result in a crash.

# Screenshots

Not applicable.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: f963525 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi]
]

# Additional context

[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6683870/config.zip)

**Comment by Maleclypse** [comment]
#45929 I believe this is at least a baseline for when it worked last.

**Comment by anothersimulacrum** [comment]
It's because the acid it's trying to extract has no materials, and no freezing point as such (and in trying to find it, we crash!).
This is a regression introduced in https://github.com/CleverRaven/Cataclysm-DDA/pull/48972

Should anything really be allowed to have no materials?

**Comment by Hirmuolio** [comment]
It seems like acid isn't even temperature tracked item. It is classified as ammo (only food and corpses have temperature).

Just removing this line should be enough to fix it for now https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/iuse.cpp#L4771

Probably should do something about adding temperature to chemicals.
