### ISSUE TITLE
Trenchcoat has wrong armor values

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#49385]
# Describe the bug
Trenchcoat has old armor values
Compare to Duster which is basically just longer version

# Steps To Reproduce
spawn trenchcoat
spawn duster
compare them

# Expected behavior
armor values should match

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: f963525 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA],
    Stats Through Kills [stats_through_kills]
]

# Additional context

**Comment by Dacendeth** [comment]
Yep it has material thickness 2 when it should have .3.
