### ISSUE TITLE
Bug-No zombies  spawning at light industry map location

### ISSUE THREAD

**Issue by Azazoth** [CleverRaven/Cataclysm-DDA#49382]
# Is your feature request related to a problem? Please describe.
Light indstry location have no zombies spawning  and considering huge loot it offer-crafting books,lot of tools and even good clothes  (leather jackets and bags on sofas) and opearational cube truck sometimes its unbalanced.

# Describe the solution you'd like
Zombies should appear or loot should be much lesser

# Describe alternatives you've considered
as above

Proof

just updated to  new version and teleported on light industry location after spawning
https://prnt.sc/162yluw
no zombies in sight -and lot of good high level books (sicp,history of firefighting,electronic cirucuit theory,plastic and polymers,fermenting culture,advanced chemistry,mechanical mastery)
https://prnt.sc/162zjab

 tools-(crowbar,jackhammer,arc welder,acetilne torch...) 
https://prnt.sc/162zrds
https://prnt.sc/162zwmk

rain coat and messenger bag..
https://prnt.sc/16301vr

also pretty full fridge
https://prnt.sc/162zcyb
along   with full vendors if you have cash
https://prnt.sc/16305d0

.this time no cube van...but you see the problem

this problem persist for a time now its not new..i avoid lootign this locaion as its too powerfull with no danger

**Comment by actual-nh** [comment]
Ping: @Extension-Driver?

**Comment by OliveChukar** [comment]
On (cdda-windows-tiles-x64-2021-06-20-0737) I started a next summer run and teleported to a light industry location.  There were no creatures.  There was a working cube multiple jackhammers and a toolbox.  It did seem to be a no risk high reward place.

**Comment by Extension-Driver** [comment]
Yes, I'm still working on the Light Industry location. My plan as per @Venera3 's Duscord suggestions is to add some tough zombies, rust zombies and feral humans to the normal Light Industry.

Also, 70% chance of spawning is way too high for the van. THe high chance to spawn should be reserved for a scenario-only version of the Light Industry.

**Comment by eltank** [comment]
Opened a PR to add some standard zombies there as an interim fix.

**Comment by Extension-Driver** [comment]
Great! I have been working on a scenario-only version of the Light Industry myself. I hope to have it ready soon.
