### ISSUE TITLE
Driving might be leveling too fast

### ISSUE THREAD

**Issue by AlbertTheTerrible** [CleverRaven/Cataclysm-DDA#49388]
# Is your feature request related to a problem? Please describe.
I think driving feels like an underwhelming skill because it levels too fast.  Right now it just feels like a mild inconvenience, when driving should be/feel like a dangerous choice, if you have no experience. I don't remember ever having the need to even read a book about driving because of this.

The kinks and quirks of low level driving are fun and well thought out, but some people might not even know they exist because you can easily get to driving lvl +4 easily by spending a few minutes driving in a straight line by accident.

# Describe the solution you'd like
Slow down the leveling of the driving skill a LOT, specifically the early levels. I don't think the later ( 4+) levels matter as much, but i'm not too sure on that part.

# Describe alternatives you've considered
None

# Additional context
This is just my opinion. I think the skill itself is well thought out, it's just that you barely see a point in investing points in it early or take time to read something about it because you level it so easily and thus bypass it's biggest hurdle.

**Comment by Qrox** [comment]
Related: #49018.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
