### ISSUE TITLE
You can befriend hallucinatory NPCs and bring their stuff into reality

### ISSUE THREAD

**Issue by SariusSkelrets** [CleverRaven/Cataclysm-DDA#49387]
# Describe the bug

NPCs created by hallucinations can be talked to then befriended and picked clean of their inventory before they disappear

# Steps To Reproduce

1. Spawn a flaming eye then give you debug invincibility and high social skill
2. Wait until a NPC is created by the hallucinations
3. Use Shift+v to locate them and walk into them to talk 
4. Befriend them before taking all their stuff
5. Wait for them to disappear, leaving behind their material goods

# Expected behavior

Not being able to reach the point where you can create matter from your mind with your social skill by hallucinating

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-9280-g9dde4db-dirty [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

Unrelated issue: Shift+v allows you to see hallucinations while blind

**Comment by Fris0uman** [comment]
What menu do you go through to get their stuff?

**Comment by chrispikula** [comment]
@Fris0uman 
Once they are a follower, they will trade everything away for free.

**Comment by Fris0uman** [comment]
Do you have a save with an hallucination NPC in it that you could share?

**Comment by SariusSkelrets** [comment]
[Hallucination NPC.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6686913/Hallucination.NPC.zip)

The NPC is already befriended. I also confirmed the hallucination status by reverting the save and killed the flaming eye to prevent being interrupted while waiting for the NPC to disappear
