### ISSUE TITLE
Fast travel

### ISSUE THREAD

**Issue by eltank** [CleverRaven/Cataclysm-DDA#49416]
# Is your feature request related to a problem? Please describe.
Players that settle down in a base often need to drive repeatedly to and from far-away locations, either for questing/trading or for looting interesting locations (e.g. labs). Traveling to a new location for the first time can be fun because you have to find a good path and deal with various perils and obstacles on the way. However subsequent trips are usually either boring (repetitive key presses) or annoying (having to constantly avoid wrecked cars and boulders). I think some automation would be helpful here and the current auto-drive feature doesn't cut it (very poor obstacle avoidance, can't drive off-road and can't follow custom paths).

# Describe the solution you'd like
I'm planning to implement path recording and replay for vehicles. I suppose I could make it work without a vehicle too, but traveling long distances without a vehicle doesn't make much sense to me and auto-walk kind-of works for that already.

Phase 1. Minimum Viable Product
- [ ] Add "Record path" to vehicle driving menu. Record position, heading and speed at each game turn. Stop driving also stops recording
- [ ] Add "Replay path" to vehicle driving menu, replay a previously recorded route. Requires starting from the same starting position. Can be interrupted
- [ ] Serialize recorded paths to JSON
- [ ] Optimize the path representation for memory and disk space
- [ ] Load on demand (only if keeping all paths in memory is unacceptable, else defer this to Phase 2)

Phase 2. Independent Incremental Improvements
- [ ] Collision detection (avoid hitting dynamic obstacles, e.g. animals)
- [ ] Resume recording (after stopping to take care of something)
- [ ] Resume playback
- [ ] Frame skipping (avoid rendering every step of the way to reduce IRL time)
- [ ] Support for multiple paths starting in the same spot. Add "Rename path" and "Travel to"
- [ ] Auto-generate reverse paths. Add "Return to origin"
- [ ] Hop onto a recorded route from any position
- [ ] Route manager (like Zone manager) for viewing, renaming, deleting, tweaking recorded routes
- [ ] Override recorded speed
- [ ] Support mounts (horses, mechs)
- [ ] In-game help text describing the feature

(roughly sorted in the order I'd choose to work on them, based on personal interest and expected difficulty)

# Describe alternatives you've considered
Instant fast-travel (teleport player and vehicle to destination + advance time). Very easy to implement but there's no way that would be approved, right?
"Fast-travel by teleportation is pretty much off the table. if we do it, it’ll just be continuously auto-moving, possibly skipping some redraws to speed things up." -- Kevin Granade 2015

Improving the auto-drive system to avoid obstacles, to be able to path off-road, and to support waypoints. Seems viable in theory but I don't think I have the skill to pull it off.

Recording only speed+heading. I think I need position as a sanity check, though maybe not every turn.

# Additional context
I wonder if others would find this useful. Comments and suggestions are welcome.

If this is the sort of thing that will not be allowed into the game I'd like to know that as well, to avoid wasting time/effort.

This will probably take weeks or months to do and I probably won't do everything in Phase 2. If someone wants to take on any of that work they are welcome to.

Open questions:
- Has this been suggested/attempted before? I tried a few searches but didn't find anything on github. I did find some stuff on discord but very old. [\[1\]](https://discourse.cataclysmdda.org/t/auto-travel-option/8821) [\[2\]](https://discourse.cataclysmdda.org/t/uh-fast-travel/9453)

- How much extra memory usage is acceptable?

- Am I missing anything in the MVP?

**Comment by Saicchi** [comment]
How would you handle random events like hordes or the vehicle skidding in a replay? Stop the replay and ask the player to handle the situation?

**Comment by eltank** [comment]
> How would you handle random events like hordes or the vehicle skidding in a replay? Stop the replay and ask the player to handle the situation?

With Phase 1 functionality the replay will stop if the vehicle goes off-course or is unable to maintain the recorded speed, which will happen if the vehicle hits anything, skids due to low driving skill, or runs out of fuel. If you see you're about to crash you can also interrupt with the skip-turn key. No way to resume, so you have to drive the rest of the way yourself, or go back to the starting point if it's closer and try again.

In Phase 2 either safe mode or collision detection should kick in before you hit anything. The player can either stop and deal with the problem or drive around it, then resume. Existing auto-drive code will be used to try to get back on track, which may fail.

**Comment by PatrikLundell** [comment]
Note that unless your vehicle is completely symmetrical around the pivot point, a return path won't be identical unless you drive the whole distance in reverse gear. Thus, generation of a return path isn't trivial if you've got some tight spots along the path.
In fact, I suspect return paths won't be identical because of accelerations/deceleration probably not being identical.

My "standard" obstacle driving issue is bridges with vehicles forming an obstacle course where you have to move very precisely to get past without the swiveling causing the vehicle to swivel into either the railing or a blocking vehicle (often requiring a 30 degree angle movement so that you can move a tile sideways [eventually] while still having the vehicle oriented straight).

**Comment by Saicchi** [comment]
It might be easier to improve the auto-driving feature that already exists. Though I don't know much about AI driving.

**Comment by robotic-gamer** [comment]
some alternate solutions
- if being able to swap into npc followers becomes a thing, you'd just need to order them to travel were you want then swap to them.
- if alternate dimensions becomes a thing you could use it to travel faster like the nether in minecraft. or there could be a really "empty" dimension ideal for travelling long distances.
- being able to make aircraft could solve long distance travel
- making highways that are largely straight and wide would help in long distance travel

**Comment by eltank** [comment]
> Note that unless your vehicle is completely symmetrical around the pivot point, a return path won't be identical unless you drive the whole distance in reverse gear. Thus, generation of a return path isn't trivial if you've got some tight spots along the path.
> In fact, I suspect return paths won't be identical because of accelerations/deceleration probably not being identical.

Right, that's why it's further down the list in Phase 2. Driving in reverse could work but is unrealistic (you wouldn't / couldn't actually do that IRL) so I prefer to find an algorithm that generates a forward-driving route back to the starting point. If the vehicle is not perfectly symmetrical and the route involves "tight spots" then the auto-generated route may cause collisions, which is why collision detection is higher up in the list.

> It might be easier to improve the auto-driving feature that already exists.
It might be easy for someone other than me. If such a person is willing to do the work then by all means they should go for it.

**Comment by actual-nh** [comment]
I'm considering converting this to a discussion. Thoughts?

**Comment by eltank** [comment]
> I'm considering converting this to a discussion. Thoughts?

I just need a place to collect feedback and report progress. If it's customary to put feature discussions in Discussions these days, then by all means feel free to move it there.
