### ISSUE TITLE
Instant Coffee Mix Has No Nutrition

### ISSUE THREAD

**Issue by ERRORCODE509** [CleverRaven/Cataclysm-DDA#49412]
# Describe the bug
Instant coffee mix (such as that from MREs) has no nutrition, resulting in coffee crafted using it also having no nutrition.

# Steps To Reproduce

1. Find or spawn some instant coffee mix
2. Notice that it has no calories
3. Craft coffee using it
4. Notice that the coffee also has no calories

# Expected behavior

The instant coffee mix should have calories, resulting in coffee crafted using it also having calories.

# Screenshots

![image](https://user-images.githubusercontent.com/75010328/123017567-af497180-d381-11eb-8d1a-634c72e43426.png)

![image](https://user-images.githubusercontent.com/75010328/123017630-d43de480-d381-11eb-9bf4-b0e4ddca82f9.png)

![image](https://user-images.githubusercontent.com/75010328/123017767-1f57f780-d382-11eb-8a97-30129b847973.png)

# Versions and configuration

Version 2021-6-22-0605, present in current GitHub repo at _Cataclysm-DDA\data\json\items\comestibles\other.json_ starting at line 856 and ending line 870. (Pictured above)

**Comment by ERRORCODE509** [comment]
Fix is to include _"calories": X,_ (with X being the appropriate number of calories) between lines 868 and 869. Would make a PR myself if I understood how.

**Comment by ERRORCODE509** [comment]
Should probably also have _"flags": [ NUTRIENT_OVERRIDE ],_ between lines 869 and 870.

**Comment by I-am-Erk** [comment]
100g of instant coffee mix contains 2 calories. That is lower than we are able to represent in game, since you'd only be using around 5 g in a cup of coffee, about 0.1 kcal. This behaviour is intended. I suspect you are thinking of something else?

**Comment by ERRORCODE509** [comment]
My bad, since the description made it sound like it included sugar it threw me off. Didn't think to actually google it.
