### ISSUE TITLE
Overclocker Attunement speed mutation?

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#49418]
# Is your feature request related to a problem? Please describe.
I was looking through the attunements and when I read Soul Afterburner I realized I was expecting something similar in Overclocker but didn't find one.  Increasing speed is exactly what Overclocking implies to me

# Describe the solution you'd like
Overclocker Attunement giving a toggle mutation that increases speed (maybe +30%) but constantly generates heat and consumes some sort of power (calories, mana, bionic power).

Generating heat is a double edged sword, great in labs/winter but dangerous in summer/mi-go tower

Bionic power as the source seems particularly interesting as it forces a shifting equilibrium between bionic power and mana (and this attunement excludes Biotek making the balance more meaningful) while also giving you a way to burn off excess power if you overcharge by accident.

# Describe alternatives you've considered
not giving Overclocker a speed boost ability

using calories/mana as the power source

# Additional context
for those unfamiliar with Magiclysm, current bionic power directly reduces your max mana which is used to cast spells.  for an 8,8,8,8 character max mana (baseline) is 1000

This would probably fill the ["haste variant with drawback"](https://app.thebrain.com/brains/55fdc5fe-c744-4c3b-bff5-bffa37424c89/thoughts/01ff27e4-876d-48c6-a386-70d863f13952/notes) in the mind-map

This also gives a lot of dials to make sure it's valuable but still balanced

**Comment by GuardianDll** [comment]
Soon will be in one of my prs, but not before first three will be merged to game

**Comment by Xpyder** [comment]
suggestion related to #45011
