### ISSUE TITLE
Should plastic mold be swapped for lump of clay?

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#49422]
# Is your feature request related to a problem? Please describe.
There have been a number of discussions about plastic molds over the last year or so.

the TL:DR is that they don't make sense where used currently (would need to be only for 1 specific item and then only for batches), are only available in 1 book, are not autolearned, are a massive artificial bottleneck, and any attempts to make the recipe more wide spread have been consistently reverted.

# Describe the solution you'd like
I think plastic mold should just be directly swapped for lump of clay as a tool, then those audited for anything that doesn't make sense.  But I wanted to open the floor to see if this is the general consensus or if we think a different approach should be used

I'll see if I can do a scan of where it's used at some point and post the results

# Describe alternatives you've considered
reworking the batch crafting system so where plastics are used allow an optional plastic mold (created specifically for that item) to allow for a better time savings

# Additional context
#47867
#32883
#47826
#46948
https://discourse.cataclysmdda.org/t/should-plastic-mold-recipe-be-in-more-books/25310
#45293
#45514
#45498

**Comment by Maleclypse** [comment]
Plastic mold has already been replaced in the 0.F -dev branch.  Once stable releases you should see the difference in the new experimentals.

**Comment by Xpyder** [comment]
Yey! do you have a pr or issue number I can put here for posterity after I close this?

**Comment by Maleclypse** [comment]
#47880 this will make significant changes to the plastic mold.

**Comment by Xpyder** [comment]
With the move to vacuum molds this becomes largely unnecessary
