### ISSUE TITLE
I find the names / descriptions for the Mana Traits (sensitivity, efficiency, regen) confusing Tags: suggestion, magiclysm

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#49424]
# Is your feature request related to a problem? Please describe.
The names / descriptions for the Mana Traits (sensitivity, efficiency, regen) are confusing

Sensitivity and Efficiency have almost identical descriptions and sound like they do the same thing

based purely on name this is what I'd expect:
- Sensitivity be the flat bonus and only affect max mana, not regen
- Efficiency to reduce the mana cost of spells but be more affected by impedance like gloves
- Regen to be a mana regen multiplier

# Describe the solution you'd like
better descriptions
some discussion on whether the names are mismatched to their bonuses
 
# Describe alternatives you've considered
leaving it as is

# Additional context

**Comment by exuvo** [comment]
I found some info on what they do at https://cddawiki.chezzo.com/cdda_wiki/index.php?title=Magiclysm_:_How_to_be_a_great_magus in section Mana 101 .

>Mana Sensitivity: Multiply your mana
>Mana Efficiency: Flat increase in mana
>Mana Regeneration: Increase mana regeneration speed

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
