### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by licaon-kter** [CleverRaven/Cataclysm-DDA#49435]
...since now at least the Android version is built here and it's no longer a side project elsewhere.

One obstacle, if the devs want it F-Droid in the first place :slightly_smiling_face: , is the `deps.zip` thing, we'd need to script all those to be built too.

**Comment by licaon-kter** [comment]
> Cataclysm is licensed under the Creative Commons Attribution-ShareAlike 3.0 Unported License. To view a copy of this license, visit http://creativecommons.org/licenses/by-sa/3.0/ or send a letter to Creative Commons, 444 Castro Street, Suite 900, Mountain View, California, 94041, USA.

Oh, wa- looking at https://spdx.org/licenses/ it appears that's not actually FOSS :( :(

nvm then

**Comment by anothersimulacrum** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/issues/18095

**Comment by reinerh** [comment]
Hm, that's weird. CC-BY-SA-3.0 is considered DFSG-free by Debian. (https://wiki.debian.org/DFSGLicenses)

**Comment by licaon-kter** [comment]
@eighthave thoughts?

**Comment by actual-nh** [comment]
> > Cataclysm is licensed under the Creative Commons Attribution-ShareAlike 3.0 Unported License. To view a copy of this license, visit http://creativecommons.org/licenses/by-sa/3.0/ or send a letter to Creative Commons, 444 Castro Street, Suite 900, Mountain View, California, 94041, USA.
> 
> Oh, wa- looking at https://spdx.org/licenses/ it appears that's not actually FOSS :( :(
> 
> nvm then

That listing seems to exclude public domain?!?

**Comment by licaon-kter** [comment]
@actual-nh does it matter in this case?

**Comment by eighthave** [comment]
@actual-nh first "public domain" isn't a license, it means copyright no longer applies.  Unfortunately, in most of the world copyright is automatic and by default.  That means to put something into the public domain, you have to make a license which does that.  That's what CC0 is.

You'll have to ask FSF or OSI why that particular CC license is not considered free.
