### ISSUE TITLE
Feature request: syringe sterilization and infection

### ISSUE THREAD

**Issue by Aerotinge** [CleverRaven/Cataclysm-DDA#49432]
# Is your feature request related to a problem? Please describe.
Syringes in game are prone to reuse again and again, which are unsafe.
We already have autoclaves and pouches(much useless in most of time), so I come up an idea to make injection more realistic.

# Describe the solution you'd like
**1. Make syringes spawn with flags, like mushroom did.**

| Flag | used                                                                                           | contam_tetanus       | contam_infection | packed| sterilized | unopened |
|------|------------------------------------------------------------------------------------------------|----------------------|------------------|------------|----------|----------|
| Desc | An used syringe. Even in post-cataclysm days, you'd better sterilized it first before a shot. | <The same as "used"> | <The same as "used">|An used syringe. Wrapped in a autoclave pouch and waiting for sterilization.|An used syringe. It has been sterilized in an autoclave, should much lower the possibility of infection, but not 100% safety guaranteed.|A brand-new syringe, with tip cap unopened. This pre-cataclysm medical supplies ensure the safety of the patient.|

- `used`: an "used" type spawn while a syringe "a"pplied, in most of time. also spawn for loots/mapgen(hospital, dispensary, etc.).
- `contam_tetanus`: an "contam_tetanus" type spawn while a syringe "a"pplied, if the character has tetanus. also spawn for loots/mapgen(dispensary, house, mobile meth labs, etc.).
- `contam_infection`: an "contam_infection" type spawn while a syringe "a"pplied, if the character has infection. also spawn for loots/mapgen(dispensary, house, mobile meth labs, etc.).
- `packed`: "a"pply an autoclave pouch to contain a empty used/contan_* type syringe, turning it into "packed" type. disable item from being usable(not "a"ppliable)
- `sterilized`: put a "packed" type syringe into a autoclave/mounted autoclave and start sterilizaion for 20 minutes(1800 charges).
- `unopened`: Only spawn for loots/mapgen(rare)

**2. Change the way injecting drugs are used.**

Instead of "E"at an injection medicine(`NO_INGEST`), now they are loaded into a syringe and being ready to "a"pply.

- Any empty syringe exclude of "packed" type can be "a"pplied to choose what to fill into this syringe. (some items with `NO_INGEST` flag, e.g. `iv_mutagen_*`, `inj_*`, etc.)
- Once loaded, the drug inside cannot be "U"nloaded.
- On applying, a `contam_tetanus`/`contam_infection` type syringe and make the patient ill after couple of hours, with a rather small chance(around 1/32, for both game-balance and realistic).
- After a loaded syringe was "a"pplied, it stayed or turned into a `used`/`contam_tetanus`/`contam_infection` type syringe base on its previous status and the status of the patient. 

**3. Change the way autoclave working.**

This feature also need some autoclave enhancement, make it accept more item than packed CBM.

# Describe alternatives you've considered

# Additional context

**Comment by Venera3** [comment]
Sterility levels will be useful for a lot more than iv drugs, so I'd like a more generic framework for it - potentially as a series of flags ( `FILTHY, UNSAFE, CLEANED, STERILIZED, UNOPENED`) that could be applied to any item, with healthcare-related actions changing the items into their appropriately-flagged variants. 

I have plans for wound care/wound infections in the short-to-mid term, after I successfully badgered anothersimalcrum into helping with the codey bits, we'll see if something like that makes it in in the first pass.

**Comment by Aerotinge** [comment]
Not sure about what other than iv drugs or bandages could make use of sterility level but generic framework is nice anyway.
Just make sure there's no item like "blood soaked rag(Cleaned)"
(Why `rag_bloody` is still a thing in game!?)

**Comment by Vendidurt** [comment]
Perhaps the same effect could be applied by soaking a syringe in denatured alcohol? Practically forcing mutating characters to get autoclave access does not seem like a fun idea.

**Comment by Aerotinge** [comment]
I can't see what difficulty are mutating guys finding an autoclave. But if so, an alternative method could be used, based on Sterility levels by Venera3.
A `CLEANED` syringe could be obtained by boiling it in a pot or soaking in denatured alcohol or ethanol(250ml) for 20 minutes, like you said.
It lower the possibility of getting infection but not totally safe.
While a `STERILIZED` one requires an autoclave, which is undoubted.

Playing mutating is far more easier than cbm currently. Find a cbm/autoclave/pouch? Nah.
No first aid skill training required, no anesthetics that are difficult to make.
All you need is a drink or a shot, even a bad mutation is !FUN! in most of time, not screwing up a character's body like cbm.
I come up with this comment is wanted to somehow balance this situation.

**Comment by PatrikLundell** [comment]
Well, mutations is the "wild" option, while using CBMs is the "technological" one. From that perspective, I believe it would make sense to require less technology to mutate (although I think you still need specific books to get across thresholds, or get ready made threshold crossing mutagens from essentially the same kind of places where you'd get those books).

**Comment by Venera3** [comment]
In addition to resterilizing, most places you'd find packed syringes you'd expect to find them a few dozen at a time, at least until gametime looting becomes a thing.

**Comment by actual-nh** [comment]
@Venera3, can I assign this to you?

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
