### ISSUE TITLE
Lower str of high stained glass window, so it could be smashed

### ISSUE THREAD

**Issue by Aerotinge** [CleverRaven/Cataclysm-DDA#49440]
# Describe the bug

`t_window_stained_green`/`t_window_stained_red`/`t_window_stained_blue` has an insane "str_min": 100, which is the same value of concrete terrain.
Even a .50 rifle can't break it, holy glasses!

# Steps To Reproduce

1. Find a Cathedral
2. Smash the ultra-holy-reinforced glass as a zombie did
3. Damn my hand hurts

# Expected behavior

Use the same value with Double glazed glass window(`t_double_pane_glass`) and most of glasses window.
```
"bash": {
      "str_min": 3,
      "str_max": 6,
...
```

More, add `glass_tinted` as its ingredient.
```
...
      "items": [ { "item": "glass_shard", "count": [ 34, 50 ] }, "item": "glass_tinted", "count": [ 8, 17 ] } ]
```

A broken stained glass symbolizes post-cataclysm era, smash it.

# Screenshots

![圖片](https://user-images.githubusercontent.com/6275647/123362770-c8316d00-d5a3-11eb-8f2d-44e2fcc8c100.png)

# Versions and configuration

 - OS Version: 10.0 2009
 - Game Version: 17c44e4
 - Graphics Version: Tiles
 - Ingame language: English
 - Mods loaded: [
"dda",
"no_npc_food",
"cbm_slots",
"sees_player_retro"
]

# Additional context

**Comment by Salty-Panda** [comment]
Those windows are half-metal actually, with small glass pieces fit in. Maybe it should rather break into a weaker version of window bars?

**Comment by I-am-Erk** [comment]
It's probably very slightly stronger than glass, but not strong. Str_min 5 and max 8 or something would probably do it.
