### ISSUE TITLE
Windows with metal grate and curtains seems to be lacking some tags resulting in odd behavior

### ISSUE THREAD

**Issue by ErrorUsernameNotFound** [CleverRaven/Cataclysm-DDA#49444]
# Describe the bug
A window with just a metal grate is transparent. When curtains are added the window becomes opaque regardless if the curtains are open or closed. 
The curtains can also be closed and opened from outside.

# Steps To Reproduce

1. Board up a window
2. Reinforce boarded window
3. Armor Reinforced window
4. Build metal grate over the window
5. Repeat the previous step to add the curtains

# Expected behavior
I would expect a window with grate and curtains to be transparent when the curtains are opened. 
Also the curtains should probable only be accessible from the outside when the window does not have a glass pane.

# Screenshots
![image](https://user-images.githubusercontent.com/53142838/123422255-3aaf4680-d5be-11eb-8070-c8df01f7df10.png)
Light is blocked as expected when the curtain is closed.

![image](https://user-images.githubusercontent.com/53142838/123422463-86fa8680-d5be-11eb-8d3d-703d920f5990.png)
Light is still blocked even when the curtains are opened

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 4a3fa7c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    Graphical Overmap [Graphical_Overmap],
    SpeedyDex [speedydex]
]

# Additional context
It seems that the tags  "TRANSPARENT" and "OPENCLOSE_INSIDE" are missing in "t_metal_grate_window_with_curtain_open" in terrain-windows.json.

**Comment by Anaglyphic** [comment]
Uhm, how did you get that one? What I mean is, is that you editing a map, or is that something one of the mapgen scripts did on it's own, something you found in-game as is? Because that's 609, and that's by intent I'm pretty sure. Use 612: Window metal grate w closed curtains, and this one behaves like you'd expect.
