### ISSUE TITLE
Exhaust and productive alternators for non-running faulty motors

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#49446]
[Game info log.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/6717626/Game.info.log.txt)
# Describe the bug

If you start a vehicle that has two motors, say, an electric and a faulty diesel motor, and only one of the engines starts, you still get exhaust.

Also, on further inspection, it seems that the alternator for the diesel motor runs the alternator on idle.  Without using diesel.  At least, until you start moving, in which case it starts using some, and, upon stopping, uses 0.0% per hour.

# Steps To Reproduce

Find a vehicle in way of your battle bus that has a faulty motor, batteries, and some fuel.  Maybe a muffler too.  Put a small electric engine in it to move it out of the way.  Drive forward, see the muffler produce exhaust, see the batteries get charged.

# Expected behavior

An engine that doesn't start shouldn't run.  No infinite power via petroleum catalyst.

# Screenshots

![image](https://user-images.githubusercontent.com/22281606/123451598-e3e44580-d59a-11eb-8c73-37de5f00e000.png)

![image](https://user-images.githubusercontent.com/22281606/123452123-56552580-d59b-11eb-8d23-88cdde3da9b6.png)

# Versions and configuration

Windows 10, tiles, 6-24-2044
Several mods, but I don't think any touch the relevant parts, that is, the engines.  (Checked via file-searching for the relevant part IDs of the engines.)

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
