### ISSUE TITLE
Feature Request: Autodriving Off-Road

### ISSUE THREAD

**Issue by Theawesomeboophis** [CleverRaven/Cataclysm-DDA#49449]
Currently, Autodriving is only available when on roads, it would be great to autodrive on trails or in the woods, as exploring the forest is one of my favorite activities in-game.

**Comment by actual-nh** [comment]
Also see #49416.

**Comment by Theawesomeboophis** [comment]
Thanks.

**Comment by RoyBerube** [comment]
Autodriving is trickier to do pathfinding compared to being on foot. The way that turning is handled is a problem. On foot, characters can just change direction with no problems and can easily follow a predetermined path. In a vehicle, the way that turning and speed changes are implemented in autodrive makes it hard to predict the exact turning path. Couple that with the vehicle taking up more than one square and it becomes really tricky.

IMO autodrive would need a major rework to enable offroad driving.

**Comment by actual-nh** [comment]
I believe @eltank is working on this.

**Comment by eltank** [comment]
That's right. Autodrive is getting a major rework, tracked in #49455, and off-road navigation is something I'm working on right now.
