### ISSUE TITLE
XL Pot Helmet Lacks The Qualities Of A Canning Pot

### ISSUE THREAD

**Issue by ERRORCODE509** [CleverRaven/Cataclysm-DDA#49457]
# Describe the bug
The XL pot helmet lacks the qualities of a canning pot used to craft it. The normal pot helmet requires a pot to craft, but it retains the qualities of a pot, unlike the XL version.
# Steps To Reproduce

1. Spawn a normal and XL pot helmet
2. Compare them
3. See that the XL version lacks the qualities of a canning pot

# Expected behavior
The XL pot helmet would be expected to have the qualities of a canning pot, similar to how a normal pot helmet has the qualities of a pot.
# Screenshots
![image](https://user-images.githubusercontent.com/75010328/123501230-3dc72880-d5f8-11eb-8e1a-906ea227c757.png)

# Versions and configuration
 - OS: Windows 10
 - Game Version: a0a4318

**Comment by actual-nh** [comment]
Really, it should depend on how much different one had to make it (if you had to put in holes for horns, say...), but that's likely being a bit too picky....

**Comment by occulti** [comment]
Confirmed in 2021-07-24-1012 - disassembling XL port helmet gives working canning pot so reasonable to assume it will still work when made into a helmet like the standard size version

![pot helmets](https://user-images.githubusercontent.com/87604321/126872143-b7b75213-1d42-43fb-a98f-840eb19ed67a.PNG)
