### ISSUE TITLE
NPC claims to eat frozen food via "use this item", but doesn't

### ISSUE THREAD

**Issue by pjf** [CleverRaven/Cataclysm-DDA#49450]
# Describe the bug

With NPC needs enabled, my companion will say "Thanks, that hits the spot" when hungry and offered frozen food, but the food is not eaten or removed from the player's inventory.

# Steps To Reproduce

1. Load the [attached save](https://github.com/CleverRaven/Cataclysm-DDA/files/6719061/npc_why_u_no_eat.zip).
2. `C`hat, `t`alk, "`[d]` There's something I want you to do", "`[c]` I want you to use this item", Select jerky from inventory.
3. NPC says "Thanks, that hits the spot"
4. Note that we still have the same amount of jerky as before.

# Expected behavior

NPCs eating food removes it from the player's inventory, or an appropriate message is given if they decline to eat.

# Versions and configuration

- 64afab68a517ee9da7ef24a68656bec1e7e3fab4 with UndeadPeople tileset applied.

**Comment by pjf** [comment]
**Update:** It appears this is happening because the jerky is frozen. Defrosting the food causes it to actually be eaten.

The misleading message when food was not consumed ("Thanks, that hits the spot") still remains.

**Comment by Salty-Panda** [comment]
I suggest adding in `Character::can_consume_as_is` checks for flags FROZEN and EDIBLE_FROZEN
