### ISSUE TITLE
[Bug] Scopes are used to light a fire when trying to put them on guns

### ISSUE THREAD

**Issue by CyberVonCyberus** [CleverRaven/Cataclysm-DDA#49464]
# Describe the bug

When trying to attach a scope to a rifle while out in the sunlight you will be interrupted and the message log will show "You have lost the item you were using to start the fire" after multiple attempts I tired again indoor with the curtains closed and I succeeded. It seems that when activating a scope while exposed to sunlight it will try to both use it to light a fire and attach it to the gun at once.

# Steps To Reproduce

1. Player is outside during a sunny day.
2. Try to activate a scope and attach it to a gun.
3. During the process of attaching the gunmod you will receive a message in your log saying "You have lost the item you were using to start the fire.

# Expected behavior

Player activates the scope, selects the gun he wants to put it on and after a few seconds the scope is attached to the gun in the form of a gunmod.

# Screenshots

![image](https://user-images.githubusercontent.com/86529974/123520917-475d9880-d6ab-11eb-8ec1-38896620389a.png)

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-3
 - Graphics version: UNDEAD_PEOPLE (NEW VERSION)
 - Ingame language: English
 - Mods loaded: StatsThroughSkills, StatsThroughKills, Disable NPC Needs, Aftershock, Magiclysm, DinoMod, Alternative Map Key

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-5881.

![изображение](https://user-images.githubusercontent.com/11132525/152780695-c511bd97-dd8a-40d8-a4d6-9e386411b800.png)
