### ISSUE TITLE
[Magiclysm] Blood Power Generator CBM not working

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#49478]
# Describe the bug
Blood Power Generator CBM can't be fueled

# Steps To Reproduce
start a world with Magiclysm enabled
spawn :
 - a Blood Power Generator CBM
 - a Power Storage II CBM
 - an NPC
 - a Butchering Kit
 - a Large Water Skin
give yourself the 'install bionics' debug mutation, and install the CBMs
debug kill all nearby NPCs
bring the stuff over to the body, Butcher -> Bleed -> Waterskin

Now that you have a waterskin with fresh blood, try to fill the CBM
I've tried Activating, Eating, powering the CBM with blood in my inventory, and setting auto-on (expected the activate and auto-on to prompt me to refill if it's empty)

# Expected behavior
- a Refill option on the CBM menu for cbm's that have tanks to allow me to refill them directly
- an Auto-Refill prompt when trying to turn activate a CBM that doesn't have enough left in tank (if you have some in your inventory)
- an Auto-Refill prompt when a power generator CBM tries to turn on (like from the autostart) but doesn't have enough fuel (if you have some in your inventory)
- possibly a prompt when trying to consum(e) something that's both comestible, and a usable ammo for a CBM

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: a0a4318 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA],
    Stats Through Kills [stats_through_kills]
]

# Additional context

related to #45040 but I'm not convinced charges are the actual problem
I've tried the following without success:
 - Increasing the volume of the Blood Power Generator CBM Tank by 100x
 - Making the blood non-comestible
 - Adding missing properties from gasoline with changes to match blood

Thing's I've noticed:
 - I've had inconsistent results with changes in the mod's materials.json for blood not overriding the default materials.json blood
 - There's some artificial blocks in the bionic fuel checks that explicitly refuse to acknowledge comestible materials for no reason other than that they're comestible [specifically in `Character::can_fuel_bionic_with`] (which is an incorrect approach)
 - I would have expected the activation code to (if a bionic is empty) call the bionic's own refill command rather than trying to metamind the refill for all bionics itself.  If it's an efficiency thing when consum(e)ing then there should probably be a map where the Keys are 'what installed bionics say they can consume' and the values are the bionics that say they can accept that fuel, or better yet a refill command in the bionics menu so the player can directly fill what they want rather than the player needing to risk "Eat"ing stuff like gasoline

**Comment by Fris0uman** [comment]
See https://github.com/CleverRaven/Cataclysm-DDA/pull/49352
