### ISSUE TITLE
Add makeshift/metalplate ESAPI vest

### ISSUE THREAD

**Issue by Igryn** [CleverRaven/Cataclysm-DDA#49477]
# Is your feature request related to a problem? Please describe.
You cannot easily modify ESAPI vest in a crude manner

# Describe the solution you'd like
Ability to load an empty ESAPI vest with regular metal plates to make kind of simple and light but not so protective scrappy apocalyptic vest. Not good against projectiles with stats simlar to scrap cuirass

# Describe alternatives you've considered
Make empty vest less protective, as description says its only synthetic fabric

# Additional context
Just thought it would fit the game. Mostly just a scrap cuirass alternative if you dont have the skill but have means to shape some large metal plates in to approriate shape of plate holder compartment. Like by sawing off exces material or bending it in shape with pliers, and just put whatever fits in the compartment 
![74535280-old-metal-sheet-roof-texture-pattern-of-old-metal-sheet-metal-sheet-texture-rusty-metal-sheet-textur](https://user-images.githubusercontent.com/51831130/123556849-40f81b00-d796-11eb-9bec-e8a62a722eeb.jpg)

**Comment by Igryn** [comment]
![2-2523_stuart_highway_mileage_sign](https://user-images.githubusercontent.com/51831130/123641929-70a53280-d82b-11eb-92ab-5b9cee7d3b04.jpg)

**Comment by Aerotinge** [comment]
We had modularvest removed in #36920 and now add back a makeshift one. 
Is this making any progress on that?

**Comment by thesharkdude** [comment]
I'll try my hand at this one.
