### ISSUE TITLE
[Bug] Dogs acquired via "Find Lost Dog" missions can't be interacted with like other dogs

### ISSUE THREAD

**Issue by UriyaBA** [CleverRaven/Cataclysm-DDA#49474]
# Describe the bug
Dogs acquired via ["Find Lost Dog" missions](http://cddawiki.chezzo.com/cdda_wiki/index.php?title=Missions#Find_Lost_Dog) can't be played with, tied down, ridden etc.

# Steps To Reproduce
1. Make a player.
2. Find / make an NPC that gives the player the quest ["Find Lost Dog"](http://cddawiki.chezzo.com/cdda_wiki/index.php?title=Missions#Find_Lost_Dog).
3. Find the dog and return to the NPC.
4. Complete the quest.
5. Examine the dog.

# Expected behavior
I expected the normal "What to do with your dog?" menu to pop up.

# Screenshots
The menu I expected to pop up:
![](https://cdn.discordapp.com/attachments/642349261320880128/858718822916030504/unknown.png)

The menu that popped up:
![image](https://user-images.githubusercontent.com/44501176/123549226-b6e98b80-d770-11eb-8721-0829ce90f40a.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: a5c3b7f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6721784/save.zip)

**Comment by Venera3** [comment]
This happens with creatures that get spawned friendly (specifically friendliness -1) - for example debug-spawned friendlies and friendly dermatik larvae.
