### ISSUE TITLE
Can no longer use Battery System CBM to consume charge

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#49509]
# Describe the bug

Two days ago, I could use the Battery System CBM to consume batteries.  Now, I am no longer able to do so.

# Steps To Reproduce

Have the battery system CBM installed
Try to consume charge.
Take the time to consume the charge.
No charge is added, battery is not drained.

# Expected behavior

Charge would be added to the internal battery.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: e58a9fd [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6743691/debug.log)

Mods: yes, per log, but none touch the actions of "bio_batteries" or "Battery System"

# Additional context

Looking at recent accepted PR's, #49499 maybe?

**Comment by Nierfenhimer** [comment]
Can confirm here. Cannot use Shift-E or inspect-Eat to consume charge. When attempting to consume battery charge, the time to consume the charge will pass, but nothing will happen. As of last exp build, it would only result in "Never mind.". The same seems to be happening for Ethanol Burner and trying to consume that. May be farther-reaching with other power-producing CBMs that use consumption.

**Comment by Maleclypse** [comment]
Is it just battery eating cbm that’s not working or is the gasoline cbm also not working?

**Comment by Maleclypse** [comment]
Gasoline cbm does work though.

**Comment by KorGgenT** [comment]
![image](https://user-images.githubusercontent.com/30208401/124172116-6ecfaf00-da77-11eb-9dee-09b0dc23f22b.png)
i cannot confirm that the ethanol burner does not work.

**Comment by actual-nh** [comment]
Excellent! There's unfortunately still the blood_tainted thing, admittedly.

**Comment by Nierfenhimer** [comment]
> ![image](https://user-images.githubusercontent.com/30208401/124172116-6ecfaf00-da77-11eb-9dee-09b0dc23f22b.png)
> i cannot confirm that the ethanol burner does not work.

Yeah, eth and gas seem to be fine. I must have been tired. Disregard ^^ It's just batteries. Thanks~
