### ISSUE TITLE
Zombies drop barrels on occasion

### ISSUE THREAD

**Issue by nuget102** [CleverRaven/Cataclysm-DDA#49510]
# Describe the bug

On occasion it appears that zombies will occasionally drop a barrel of whiskey. During clearing a Bastion Fortress I had a single zombie drop a barrel of "Single Malt Whiskey" while this is hilarious and I now have whiskey for a lifetime, I don't believe this is intended.

# Steps To Reproduce

1. Make a player capable of killing Zombies en masse
2. Cull a bunch of zombies
3. Possibility of them dropping a barrel. (odds seem to be about 1 in 3000

# Expected behavior

I would expect zombies to drop a bottle of whiskey, not a barrel.

# Versions and configuration

   - OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.2 LTS; Release: 20.04; Codename: focal; 
- Game Version: 9b5b534 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Crazy Cataclysm [crazy_cataclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm]
]

 - OS: [Ubuntu 20.04]
 - Game Version: [9b5b534]
 - Graphics version: [Tiles]
 - Ingame language: [English]
 - Mods loaded: [Dark Days Ahead [dda], Disable NPC Needs [no_npc_food], Bionic Professions [package_bionic_professions], Magiclysm [magiclysm], Crazy Cataclysm [crazy_cataclysm], Graphical Overmap [Graphical_Overmap], Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm]

**Comment by actual-nh** [comment]
A bit more detail, such as version (and OS) and perhaps a save-file, would be appreciated.

**Comment by nuget102** [comment]
> A bit more detail, such as version (and OS) and perhaps a save-file, would be appreciated.

**Comment by nuget102** [comment]
> A bit more detail, such as version (and OS) and perhaps a save-file, would be appreciated.

I have fixed the initial post and it now shows all the information. Here is the save file: 
However I have been unable to reproduce the issue and I can't seem to get my save file to upload.

**Comment by SariusSkelrets** [comment]
After looking at the code I found nothing about a barrel of whiskey 

Are you sure the zombie corpse didn’t just landed on a whiskey barrel?

An easy way to test it would be spawning then killing hundreds or thousands of reenactors to see their loot

**Comment by Founded1992** [comment]
I went ahead and created a world with the mods referenced in the issue report, teleported to an empty field, spawned a 100-size group of Ravenous Reenactors on myself, debug-killed them all, and 'V'iewed items dropped. I repeated this process three more times, and in each case no barrels were dropped by the Reenactors.

I also looked at two Bastion Forts and noted that the Reenactors there dropped similar items to the ones spawned with debug commands, but that there existed food items spawned in the Bastion Fort alongside.

Therefore, it is my impression that a barrel that was generated from the Bastion Fort is the culprit. An examination of Bastion Fort loot tables would help confirm this.

Tests were done using the most recent experimental as of this post: Windows Tiles x64 version 5861984, with the mods posted in the initial issue post.

**Comment by PatrikLundell** [comment]
I've encountered a surprise drop of a barrel of some kind of booze when looking through the loot from killed zombies back in 0.E2 stable. I don't believe the zombie was some special kind, although it was quite some time ago, but I think it was in the open, not inside a building. I believe I've seen one or two other cases of zombies dropping very large objects of some other kinds as well in that version, so it might be some issue in drop generation that can very rarely add items that presumably aren't in the drop tables.

**Comment by Founded1992** [comment]
I've made a more rigorous assessment, repeating the previous procedure several more times in the middle of an ocean so as not to contaminate the items viewed with errant debris. Attached is the total sum of viewed items after several thousand zombie souls cried out and were silenced:

![MoreRigorous](https://user-images.githubusercontent.com/24758773/124084618-0bf10000-da04-11eb-8de8-bc1eaf896c30.png)

The rarest drop within these lists are the faulty versions of +1 muskets and rifles exclusive to the class, both of which seem to be modifiers for other class drops. If there does exist a very rare drop for a barrel of booze for this particular monster, either the drop is of exceedingly high rarity or my luck in viewing that drop is exceedingly terrible.

In any case, a review similar to the one done by SariusSkelrets would be most appropriate for determining this matter in fact. Whether there exist other monster groups with larger drops similar to booze barrels remains to be seen.

This was done using a new world with the same mods and specifications as used in the attempt in my previous post within this issue.

**Comment by LyleSY** [comment]
Digging into this some, I see they do have a special drop group: "zombie_reenactor_drops" defined in https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/monsterdrops/misc.json

...but nothing I see there should do this. Hopefully this helps some.

**Comment by actual-nh** [comment]
The only barrel I've been able to find in anything related to the fort is the one with gunpowder.

**Comment by anothersimulacrum** [comment]
Anything that can drop `single_malt_whiskey`, included in the `liquor_and_spirits` itemgroup (included in the `alcohol_bottled_canned`, `bowling_alcohol`, and `drugdealer` itemgroups), can potentially drop a barrel of `single_malt_whiskey`, because it's default container is `wooden_barrel`.

**Comment by Founded1992** [comment]
Having a look at code, the Bastion Fortress spawns GROUP_FORT monsters rather than exclusively placing Ravenous Reenactors.
GROUP_FORT is a monster group which contains mon_zombie and mon_zombie_child in addition to mon_zombie_reenactor, at a lower frequency.
From mon_zombie, we get the default_zombie_death_drops item-group, which includes the default_zombie_items item-group, which includes the default_zombie_items_bags item-group, which includes the alcohol_bottled_canned item-group, which includes the liquor_and_spirits item-group, which finally includes single_malt_whiskey.

This allows for a barrel of single-malt whiskey to be found from fighting monsters in the Bastion Fortress, and corroborates with PatrikLundell's statement regarding having found barrels in regular play.

anothersimulacrum's analysis was vital in establishing this possibility, as I'm nowhere near fluent enough with the code to be able to tangle the beast that is Cataclysm DDA. As such, I recommend someone more experienced confirm this analysis to assure that I haven't made an amateur error in analysis.

**Comment by nuget102** [comment]
> Anything that can drop `single_malt_whiskey`, included in the `liquor_and_spirits` itemgroup (included in the `alcohol_bottled_canned`, `bowling_alcohol`, and `drugdealer` itemgroups), can potentially drop a barrel of `single_malt_whiskey`, because it's default container is `wooden_barrel`.

Okay following this, I looked through the zombies that were present at the Bastion Fort. There were Ravenous Reenactors, normal Zombies, Grappler Zombies, and Tough Zombies. I spawned over 3,000 normal Zombies and managed to get a single barrel drop. My best guess is that I was mistaken and a normal zombie dropped the barrel, and NOT a Ravenous Reenactor.

**Comment by actual-nh** [comment]
@nuget102: If you could change the title of the PR?

**Comment by nuget102** [comment]
> @nuget102: If you could change the title of the PR?

Done, I've also updated the instructions on reproducing. Based on my testing, it seems to be incredibly rare (about 1 in 3000)
