### ISSUE TITLE
Dexterity and perception are overvalued for vehicle handling instead of driving skill

### ISSUE THREAD

**Issue by CivilisationDDA** [CleverRaven/Cataclysm-DDA#49529]
# Describe the bug
I have no serious coding experience but my reading of the following piece of code from `vehicle_move.cpp` is that while the intention(I assume) is for dexterity, perception and driving skill to contribute equally to vehicle handling, the fact that base character stats are Dex:8, Per:8 and driving skill:0 means that Dex & Per are more valued.

https://github.com/CleverRaven/Cataclysm-DDA/blob/68b8751a108922c102319261628bb80478b67af8/src/vehicle_move.cpp#L1381-L1387

# Expected behavior

I would expect driving skill to have greater weighting in the vehicle handling formula than dexterity and perception.

# Additional context

As I said in the beginning I have zero C++ experience, I was just looking at the code as part of #49018

**Comment by alph4numb3r** [comment]
If I'm not reading the parentheses wrong, then dex and per get divided by 10 before getting added to the driving skill, making driving skill 10× as impactful.

**Comment by CivilisationDDA** [comment]
Yes I musread the brackets. Closing.
