### ISSUE TITLE
Wrong gloves

### ISSUE THREAD

**Issue by Shibimon** [CleverRaven/Cataclysm-DDA#49523]
# Describe the bug
Crafting "fingerless survivor gloves" currently requires a "light survivor gloves" instead of a "survivor gloves".
Fingerless survivor gloves have approximately half the base armor stats of normal survivor gloves, and light survivor gloves have a half of that (or 1/4 of normal survivor gloves).
This produces a weird behavior where cutting the fingertips of a light survivor gloves (by crafting them into a fingerless survivor gloves) doubles most armors and resistances of the base item and seems that this was intended to be crafted with common survivor gloves halving stats instead.

# Steps To Reproduce
1 Craft a fingerless survivor gloves.
2 Marvel at how your light survivor gloves are now twice as strong by the miracles of the apocalypse.

# Expected behavior
1 Crafting a fingerless survivor gloves from a survivor gloves cutting the fingertips and reducing its stats a bit to get less encumbrance.

# Screenshots
![imagen](https://user-images.githubusercontent.com/43771067/124256563-d4687d80-db01-11eb-8788-bfa1dc0121f9.png)

# Versions and configuration
48d1c4f (tiles) 4 days ago as per launcher info.

**Comment by Night-Pryanik** [comment]
Fixed by #49527.
