### ISSUE TITLE
Generated wrecked furniture in looted grocery store spawns a lot of nails

### ISSUE THREAD

**Issue by Deiskos** [CleverRaven/Cataclysm-DDA#49522]
# Describe the bug

Generated wrecked furniture in looted grocery store spawns a lot of nails. Screenshots from when I was reproducing it in latest experimental show 800, but I got 1200 of them spawn in slightly older experimental I'm playing in right now. Manually smashing furniture produces a normal amount of nails. 

# Steps To Reproduce

0. Find or spawn a looted variant of grocery store
1. Find a wrecked furniture such as a bookshelf or a table
2. Nails

# Expected behavior

A normal amount of nails to spawn.

# Screenshots

Generated wrecked furniture
![image](https://user-images.githubusercontent.com/11491788/124255351-a6645700-db5c-11eb-8de6-c4c07e72eba8.png)

Manually smashed furniture
![image](https://user-images.githubusercontent.com/11491788/124256259-ad3f9980-db5d-11eb-8085-ffb1671eee6a.png)

1200 nails spawn (in experimental 41b5fad )
![image](https://user-images.githubusercontent.com/11491788/124257142-a6fded00-db5e-11eb-8112-b3e031c9f71b.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 68b8751 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

n/a

**Comment by Procyonae** [comment]
Can confirm it spawns 100 times the amount of nails and 200 times the amount of copper wire compared to the bash drop rate, will look to make a fix
