### ISSUE TITLE
Hand broken and can't apply splint.

### ISSUE THREAD

**Issue by Rathner** [CleverRaven/Cataclysm-DDA#49539]
# Describe the bug
You can break your hand (Confirmed.) through cold air. It can't be healed back.

You can break your hand and possibly feet. The Arm/Leg splints do not give the option to apply them. It also appears to not heal on its own. This gives a debuff that can not be removed.

# Steps To Reproduce

Freeze your hands until they break or use other methods to cause substantial damage to the hands directly. (Unconfirmed if its just cold.)

# Expected behavior

Either hands/feet can not be broken or add splints specifically for hands or feet.

# Screenshots
 N/A 

# Version and mods
 e8a4794 (tiles)
 DDA, Disable needs, mining mod, bionic professions, sees-playericon hitbuttoniso, Alternative map key.

# Game Report
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: e8a4794 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Mining Mod [Mining_Mod],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    Alternative Map Key [alt_map_key]
    ]

# Additional context
Unsure how exactly one hand froze and the other did not. I'll be adding in splints as a remedy to this issue unless its believed that they should not be added and rather this is a unintended feature. (Hand/Foot breakage is alerted and healed the exact same way when hand/foot splints are added.)

**Comment by Fris0uman** [comment]
Can you post the save where you managed to break your hands?

**Comment by Fris0uman** [comment]
Waited all night naked in the snow, broke every limb but no problem with hands and feets
![image](https://user-images.githubusercontent.com/41293484/124361937-48a23e80-dc32-11eb-943d-fc0dc094dae4.png)

**Comment by Fris0uman** [comment]
So apparently messed up CBM removal might be a way to get that issue. I haven't tested it yet

**Comment by Fris0uman** [comment]
Nop can't reproduce it that way either, and the code for that uses  `apply_damage()` which only damage main parts so I still don't know how it happens U_U
