### ISSUE TITLE
Monsters appear before my eyes

### ISSUE THREAD

**Issue by kydsh** [CleverRaven/Cataclysm-DDA#49530]
they just appear in front of my eyes when I walk, just now a situation has arisen: a mycus appeared in front of the house, I set them on fire and finished off the survivors, after a couple of actions it repeated three more times, one of which they broke into my house and infected me, before that I walked through the fields and zombies appeared in front of my nose

# Steps To Reproduce

1. wait
2. get mycus and zombies

# Expected behavior

I expect them to appear beyond my perception

# Screenshots

no screenshots, then just spawn

version: 9894f03

**Comment by Qrox** [comment]
Not sure about the mycus, but some zombies can't be seen in low light unless they are right next to you.

**Comment by kydsh** [comment]
> Not sure about the mycus, but some zombies can't be seen in low light unless they are right next to you.

that was usual zombies and it was sunny so probably not
