### ISSUE TITLE
Furniture is missing in LMOE shelters

### ISSUE THREAD

**Issue by LaVeyanFiend** [CleverRaven/Cataclysm-DDA#49547]
# Describe the bug

Beds, wooden tables, bookshelves, and display racks aren't appearing in LMOE shelters.

# Steps To Reproduce

1. Pick the LMOE Shelter option for Safe Place scenario.
2. Walk around downstairs.
3. See no beds or display racks.

# Expected behavior

Not leaving stuff on & sleeping on the floor.

# Screenshots

![image](https://user-images.githubusercontent.com/51099123/124366683-72059f00-dc1f-11eb-8210-94bc90cce30d.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0f172bb [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    Fuji's Military Profession Pack [fuji_mpp],
    Disable NPC Needs [no_npc_food],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

Also tested with:

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0f172bb [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

I checked regular houses & saw no issue of missing furniture.

**Comment by eltank** [comment]
I can reproduce this on 90178082 

![missing_furn](https://user-images.githubusercontent.com/8000047/124367316-00bbf100-dc0b-11eb-92d2-9bdbc652d935.png)

**Comment by eltank** [comment]
I investigated this a bit. Neither the [mapgen lmoe.json](https://github.com/CleverRaven/Cataclysm-DDA/commits/master/data/json/mapgen/lmoe.json) nor the [mapgen_palettes lmoe.json](https://github.com/CleverRaven/Cataclysm-DDA/commits/master/data/json/mapgen_palettes/lmoe.json) have changed recently. I'm suspecting a problem with the mapgen code itself.

I tried editing the `empty_bunker_items` palette and removing everything but the books. The furniture came back (without items) except for the bookshelves that were supposed to hold the books. It seems that when the items are spawned the furniture is erased.
![missing2](https://user-images.githubusercontent.com/8000047/124367983-467bb800-dc11-11eb-85a3-735b061b102a.png)

**Comment by eltank** [comment]
I found the culprit, it is indeed a change to the mapgen code: a1e1dd207485c009db670c9a8706cbc31b0307ea
When I revert that commit, the problem goes away. I will create a PR with the reversion.

![fixed](https://user-images.githubusercontent.com/8000047/124368230-ff42f680-dc13-11eb-8fc7-cc1d58717db6.png)

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/mansions-bathrooms-bugged/26597/2

**Comment by eltank** [comment]
As reported on discord, this bug also affects mansion bathrooms (as well as kitchens). I checked to see if #49551 fixes that and it does -- but it doesn't look like anyone is willing to merge it.

**Comment by jbytheway** [comment]
I'm going to try to find a proper fix today, but no idea how tricky it will be, so don't hold out too much hope.

**Comment by jbytheway** [comment]
Turns out it was a very simple fix.  PRed in #49594.
