### ISSUE TITLE
Abandoned start may spawn you in building adjacent to hospital.

### ISSUE THREAD

**Issue by nuget102** [CleverRaven/Cataclysm-DDA#49549]
# Describe the bug
On occasion when you are choosing a scenario to play that normally starts you in a building you will instead spawn in a adjacent building. I have confirmed this occurs in the "Abandoned" scenario (hospital start) and it is not uncommon. May also occur in Prison Start

# Steps To Reproduce

Simply make a character selecting the "Abandoned" start repeatedly until bug occurs.

# Expected behavior
I assume you should be starting inside the hospital, rather than in a building next door or across the street.

# Versions and configuration

game version is current 0.F stable version as of July 3rd, 2021.

 - OS: Ubuntu 20.04
 - Mods loaded: [e.g.dda, Disable NPC Needs, Bionic Professions.]

**Comment by robotic-gamer** [comment]
I had similar thing happen in lmoe start, and escaped start (aftershock). It seems it occasionally just puts you somewhere in the reality bubble that is under a roof.

**Comment by teackot** [comment]
Similar with "Large Building -> Hospital" start. 

> Simply make a character selecting the "Abandoned" start repeatedly until bug occurs.

Well... for me it is: start repeatedly until bug **doesn't** occur. I tried to spawn in a hospital not less than 10 times, still unsuccessful

**Comment by robotic-gamer** [comment]
are you using the same world without resetting it? in theory given the same conditions the game will spawn you in the same place.

**Comment by teackot** [comment]
Always the different spawn place. Good news: eventually I've spawned inside the hospital
