### ISSUE TITLE
Monsters can see through z-level cover (needs confirmation)

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#49556]
# Describe the bug

I'm about 98% sure monsters ignore z-level cover like roofs

# Steps To Reproduce

start a game
go to town
climb a roof
wait for zeds to get close
sneak to other side of roof, and to various positions
note that zeds follow you around the house even though they shouldn't be able to see you through the roof/floor

# Expected behavior
At a minimum, if a on/in the same building, zeds can't magically see up through roofs

Ideally both
 - you should be able to crouch/prone on a roof to expand z-level cover
 - and z-level cover should block player vision too (like going prone on a roof should virtually eliminate your ability to see the ground

In addition to not magically and immediately aggroing all zeds within 2-3 block radius through walls, 
This would allow for tactics like hiding on a roof, waiting still for a little bit (for the sound aggro to dissipate), then tossing a rock at an adjacent building and sneaking to the other side to try and shake a horde

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 197868f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    Stats Through Kills [stats_through_kills]
]

# Additional context

I know prone isn't in the game currently (because we didn't have a real use for it) but with z-level cover there might be a place for it (esp now that it could be on a menu rather than taking a full keybind for itself)

**Comment by anothersimulacrum** [comment]
I'm pretty sure they smell you through the roof. Try the same thing with the debug no smell mutation - it's made them not follow me under rooves when I checked.

**Comment by GGgatherer** [comment]
I just checked, the scent does not propagate between z-levels.
But another thing to consider is sound. Are you crouching while moving? Try debugging your character with Tiny mutation, then check again.

**Comment by OliDM** [comment]
I also feel like zombies become hunting dogs or something similar, I have had instances where I go loot a basement or a magiclysm mage tower and by the time I come back to the ground level its filled with 10+ zombies, they do not come down to chase me they appear to be just waiting for me to show up.

**Comment by misterprimus** [comment]
Also wondering why scent is so strong among all of the zombies. Sure, some zombies, like zombie dogs, should have good scent detection, but why would a human zombie have such excellent sense of smell if humans in general have a very poor sense of smell?

**Comment by GGgatherer** [comment]
Because blob magic.

**Comment by Xpyder** [comment]
Given the testing done by @hexagonrecursion I'm going to close this is as "working as intended".

While I agree with @misterprimus  the extent of the tracking by scent abilities of non-specialized zombies does seem high, that would be a separate issue (and one I'm not presently confident enough in to open a bug ticket for at this time)
