### ISSUE TITLE
Furniture and items missing from basements

### ISSUE THREAD

**Issue by eltank** [CleverRaven/Cataclysm-DDA#49555]
# Describe the bug

Related to #49547, but different. Some house basements are missing not just furniture but also the items that are supposed to be on top of the furniture and even some surrounding walls. I suspect something's gone wrong with the nested chunk placement.

# Steps To Reproduce

Create a new game world, debug super clairvoyance, teleport into a city and check out house basements. They are more empty than they're supposed to be.

# Expected behavior

The basement seen below is half-empty. If I reload a save from before visiting the place using the 0.F binary and go there again the basement is full.

# Screenshots

at 90178082:
![halfempty](https://user-images.githubusercontent.com/8000047/124369510-4388c380-dc21-11eb-95fe-961b82a79847.png)

in 0.F
![full](https://user-images.githubusercontent.com/8000047/124369511-44b9f080-dc21-11eb-80df-43b89509e23b.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 90178082 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

**Comment by anothersimulacrum** [comment]
Looks like nested chunks are not placing.

**Comment by curstwist** [comment]
Nested basement chunks don't always spawn, they have a chance. So if this happened to an area that you visited,  then ended game without saving, it could be normal mapgen behavior since nests are not determined until they enter the reality bubble.

**Comment by eltank** [comment]
Yeah, I think it was just a coincidence. I tried several more times to reproduce the issue but couldn't. Closing.
