### ISSUE TITLE
Someone forgot to rename all instances of Schizoprenic trait to Kaluptic Psychosis in game.

### ISSUE THREAD

**Issue by MomoiroShinobinomono** [CleverRaven/Cataclysm-DDA#49552]
# Describe the bug

In-game FAQ still calls Kaluptic Psychosis as Schizophrenia.
Same problem can be encountered while using English, Russian, Deutch, Español (Argentina), Español (España), Français, Italiano, probably Korean, Norsk and Polski localizations.
Japanese and both variants of Chinese seem to have hieroglyphs that are used in the word Psychosis but I'm not sure about them.
Português (Brasil) doesn't even let the player to open the FAQ section possibly due to some typo in game code.

# Steps To Reproduce

1. Make a new character.
2. Press enter.
3. Prezz 0.
4. Press 4.
5. Look at the fourth Q+A pair.

# Expected behavior

In-game FAQ is supposed to say "You have the Kaluptic Psychosis trait, which might make the game seem buggy.".

# Versions and configuration

- OS: Windows 7 Professional SP1.
- Game version: stable 0.F for Windows, or as it is oficially called, cdda-windows-tiles-x64-2021-07-03-0512
- Mods loaded: Disable NPC needs, Bionic Professions, Blaze Industries, Magiclysm, Mythical Martial Arts, SpeedyDex.

**Comment by aoae23** [comment]
Was going to do this but someone beat me to it. This issue should be resolved now.

**Comment by Cyrano7** [comment]
Closed via https://github.com/CleverRaven/Cataclysm-DDA/commit/6d729594d41b69e34b1bc34da79eff50f3664779

**Comment by MomoiroShinobinomono** [comment]
> Closed via [6d72959](https://github.com/CleverRaven/Cataclysm-DDA/commit/6d729594d41b69e34b1bc34da79eff50f3664779)

Now I don't want to look stupid or ungrateful but why would you close this issue if only a small fraction of the described problem got fixed?
Or do you want me to fill the issue list with an individual appeals for each language represented in the game?
And how about the fact that for a players that speak Português (Brasil) the in-game FAQ is inaccessible?
Thanks.

**Comment by anothersimulacrum** [comment]
It is up to the translators to fix the issue, they will begin to do that now that the incorrect strings have been fixed. Having an issue for it will not be helpful, because there is nothing that can be done here about it any more.

If you could file a separate issue about the FAQ being inaccessible for certain languages, it would be appreciated.

**Comment by MomoiroShinobinomono** [comment]
> If you could file a separate issue about the FAQ being inaccessible for certain languages, it would be appreciated.

Done.

**Comment by anothersimulacrum** [comment]
Thank you!
