### ISSUE TITLE
Can't Play game, getting this error no matter what. 

### ISSUE THREAD

**Issue by RynhardGrey1** [CleverRaven/Cataclysm-DDA#49569]
# Describe the bug

< I receive the following message every time I try to play the game, load an old save or try to create a new game or world.

DEBUG    : Error: Json error: data/json/items/comestibles/veggy_dishes.json:27:15: duplicate entry in json object

    "spoils_in": "5 days",
    "description": "A roasted root from a cattail plant.  Its fibrous outer core is charred black, you can remove it and chew on the dry inside.",
    "milling":
              ^
               { "into": "flour", "conversion_rate": 7.5 },
    "fun": -1,
    "delete": { "flags": [ "RAW" ] },

 FUNCTION : bool main_menu::load_character_tab(bool)
 FILE     : src/main_menu.cpp
 LINE     : 1149
>

# Steps To Reproduce

# Screenshots

# Versions and configuration

# Additional context

**Comment by BrettDong** [comment]
You didn’t mention which version you are playing.

**Comment by RynhardGrey1** [comment]
Oh so sorry about that, it's the latest build of the launcher, 2021-07-04-1015.

**Comment by RynhardGrey1** [comment]
Oh so sorry about that, it's the latest build of the launcher, 2021-07-04-1015.

**Comment by BrettDong** [comment]
Why did you close the issue? Is the problem solved?

**Comment by Qrox** [comment]
Clicked the wrong button I guess. Anyway, this is already fixed by #49562.

**Comment by RynhardGrey1** [comment]
I'm guessing I pressed the wrong button, sorry I'm new, but yes, it has been resolved thanks a lot guys and thanks for all your hard work
