### ISSUE TITLE
Some sealed milk jugs spoil despite description suggesting they should not spoil

### ISSUE THREAD

**Issue by dustan1** [CleverRaven/Cataclysm-DDA#49563]
# Describe the bug

I found a sealed milk jug in a basement refrigerator which slowly went from fresh to old over a day. While it is expected that milk spoils over time, the description should make this more clear.

# Steps To Reproduce

Find a sealed jug of milk, and check if it spoils. Not all milk jugs seem to spoil though, some are "sealed" while others are "sealed fresh".

# Expected behavior

I expect all milk jugs to act the same, or at least for milk that does spoil/does not spoil to be labelled differently.

# Versions and configuration

 - OS: Windows 10
 - Game Version: bc28921 [64-bit]
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: [dda, no_npc_food, package_bionic_professions, Only_Wildlife]

# Additional context

If this is just a wording issue in the jug description, removal of "Some may be factory sealed to preserve content from rot until opened". If the different types of milk is intended, it should probably be "shelf-stable milk" instead.

[Spoiling Milk.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6759461/Spoiling.Milk.zip)
[Stable Milk.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6759462/Stable.Milk.zip)

**Comment by Qrox** [comment]
Plastic bottles and gallon jugs have a spoil multiplier of 0.5, meaning their content will spoil at half of the usual rate.

> just a wording issue in the jug description

This seems to be the case. Maybe change it to "Some may be factory sealed to improve shelf life", or something to that effect.
