### ISSUE TITLE
A flashing ! symbol to identification the corpse which it can get revive.

### ISSUE THREAD

**Issue by vipches** [CleverRaven/Cataclysm-DDA#49567]
I have this idea because I was a original acsii player, I don't really play tilesets for this game,

I saw a lot of tilesets has a special icon such like yellow ! in order to identification the corpse which it can revive, to tell you needs to be smash,

so is possible the original game can have this stystem too? 

I have a lot problem to finding which zombies are not completely dead yet, and it's even worst after a bunch group of zombies has been taking down, because you had to finding them by useing search key many times.

that's really inconvenience, because there's always some zombies getting revived if we don't looking careful enough.

**Comment by Fris0uman** [comment]
How would that work in ascii? Changing the background color of the corpse?

**Comment by vipches** [comment]
we can try add a twinkling yellow ! on the dead body, just like when you useing the map.

**Comment by Vendidurt** [comment]
I would hate to have to rely on the Shift-V to see whethera corpse is pulped or just bruised.

**Comment by vipches** [comment]
> I would hate to have to rely on the Shift-V to see whether a corpse is pulped or just bruised.

We all do, that's why I'm asking to add a key to swiching, so once it's active, you can see all the ! flashing icon on the corpses, as long as it can getting revive and not getting smash yet, 

and you can always turn off as you want, so you wont worry about flashing icon is on the whole screen to making game even lagger.

**Comment by Fris0uman** [comment]
In ascii it can't be an icon though, if we do flashing `!` it will just replace the corpse symbol

**Comment by vipches** [comment]
> In ascii it can't be an icon though, if we do flashing `!` it will just replace the corpse symbol

it will be just fine, after all you can swich to turn it on and off, we just make it work just like flashing icon on the world map menu.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
