### ISSUE TITLE
Compile error: exception specification of explicitly defaulted move assignment operator does not match the calculated one

### ISSUE THREAD

**Issue by pjf** [CleverRaven/Cataclysm-DDA#49566]
# Describe the bug

Compiling with clang 8.0 on Ubuntu 16.04 gives the following compile error:

```
src/player_activity.h:90:26: error: exception specification of explicitly defaulted move assignment operator does not match the calculated one
        player_activity &operator=( player_activity && ) noexcept = default;
```

# Steps To Reproduce

- Check out `origin/master` on Ubuntu 16.04
- `make -j8 RELEASE=1 TILES=1 CLANG=1 ASTYLE=0 USE_HOME_DIR=1 SOUND=1 LINTJSON=0 NOOPT=0 RUNTESTS=0`

# Expected behavior

Compiles happily without errors.

# Versions and configuration

- Version: 1d04305e40235b6f6b7bde809f36cbb5749cad78

# Other notes

I suspect this is some sort of STL shenanigans like we saw in #48482.

**Comment by ZhilkinSerg** [comment]
Try adding `list_is_noexcept`, i.e.:

`player_activity &operator=( player_activity && ) noexcept ( list_is_noexcept ) = default;`

**Comment by pjf** [comment]
@ZhilkinSerg : That works, thank you!

Pull request opened with changes.
