### ISSUE TITLE
Apple orchard buildings have no roof

### ISSUE THREAD

**Issue by molkero** [CleverRaven/Cataclysm-DDA#49575]
# Describe the bug

Orchard processing and orchard stall buildings have no roof.

# Steps To Reproduce

1. Visit the apple orchard.

# Expected behavior

Buildings come with a roof.

# Screenshots

![Screenshot_2021-07-04_18-16-15](https://user-images.githubusercontent.com/49575273/124390751-a3e93500-dcf5-11eb-8067-578a2797c609.png)

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 21.0.7; Codename: Ornara; 
- Game Version: 0.F-328-g66163721b9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Bionic Slots [cbm_slots]
]

# Additional context

**Comment by Procyonae** [comment]
I'll get on it and spice the location up a tad while I'm at it ^^

**Comment by Igryn** [comment]
It is an issue with automatic roof generation, reloading a save helps.

**Comment by anothersimulacrum** [comment]
It's an issue with it not having a roof, which automatic roof generation is band-aid for.
