### ISSUE TITLE
[Magiclysm] Orc village is named orc_village

### ISSUE THREAD

**Issue by molkero** [CleverRaven/Cataclysm-DDA#49576]
# Describe the bug

Orc village is named orc_village on the map.

# Steps To Reproduce

1. Find orc village.
2. Look at map. (Or location on sidebar.)

# Expected behavior

Locations would be named in the same way.

# Screenshots

![Screenshot_2021-07-04_18-44-15](https://user-images.githubusercontent.com/49575273/124391485-81591b00-dcf9-11eb-951a-008eb6eca20c.png)

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 21.0.7; Codename: Ornara; 
- Game Version: 0.F-328-g66163721b9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Bionic Slots [cbm_slots]
]

# Additional context

**Comment by Theawesomeboophis** [comment]
I was waiting until freezes were over to fix this, thanks for reminding me, this is a mistake on my end.
