### ISSUE TITLE
0.F (tiles) does not launch on macOS

### ISSUE THREAD

**Issue by dixius99** [CleverRaven/Cataclysm-DDA#49570]
# Describe the bug

Double-clicking on the Mac app does not launch the game. The app icon bounces a few times, and then nothing. If I "Show Package Contents" and then double-click on the `cataclysm-tiles` binary, Terminal opens and tells me:

```
dyld: Library not loaded: /usr/local/opt/sdl2_ttf/lib/libSDL2_ttf-2.0.0.dylib
  Referenced from: /Applications/Cataclysm.app/Contents/Resources/cataclysm-tiles
  Reason: image not found
```

I can see that this dylib is in the app, but the binary isn't looking for it there.

Installing `sdl2_ttf` via brew allows the app to launch.

~~(though I'm getting error messages related to `json.cpp`, but I'll report on that separately...~~

(Removing my comment about `json.cpp`, since this was due to a mistake I made installing 0.F. Basically, if I install 0.F without first uninstalling 0.E, it leaves files in ~/Library/Application Support/Cataclysm that cause error messages. Uninstalling 0.E, deleting that folder, and then installing 0.F fixes the `json.cpp` issues I was seeing.)

# Steps To Reproduce

1. Double click on Cataclysm.app

# Expected behavior

The game loads.

# Versions and configuration

- OS: MacOs
    - OS Version: Name: macOS; Version: 11.4; Build: 20F71; 
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No name () []
]

**Comment by actual-nh** [comment]
Same behavior on 10.12.6.

**Comment by actual-nh** [comment]
After `export DYLD_LIBRARY_PATH=.`, symlinking libSDL2_mixer-2.0.0.dylib to libSDL2_mixer.dylib and libSDL2-2.0.0.dylib to libSDL2.dylib gets over it not finding those two... but it then gives:
```
dyld: Library not loaded: /usr/local/opt/libvorbis/lib/libvorbisfile.3.dylib
  Referenced from: /Users/administrator/Desktop/CDDA_old/Cataclysm-tiles.app/Contents/Resources/./cataclysm-tiles
  Reason: image not found
Abort trap: 6
```

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/mac-0-f-not-launching/26618/2

**Comment by andwaal** [comment]
A workaround is to install with homebrew. Install with --HEAD to get last version.

**Comment by Th3Kh3d1v3** [comment]
The workaround with homebrew works but I also have this issue when doing the normal download and install.

**Comment by Rathlord** [comment]
Downloading with homebrew did *not* work for me with --HEAD on MacOS 11.4. I get the same behavior as if I download the latest experimental. The game itself launches but there is no ASCII at all on the home screen- so it's just a single line and the highlight for the current cursor placement.

**Comment by actual-nh** [comment]
Different issue - see #50149.

**Comment by ashtiboy** [comment]
ok it seems you guys are not putting all the needed frameworks that need to be put into the apps resource file that has to be in the app folder when a build compile cycle is completed! it looks  like most of the needed depended frameworks and libraries  are either been removed or not been properly compiled! make sure that all framework depended framework files are the apps resource file! if there's a error that a needed framework is not there! then recompile it until all the needed frameworks are actually in the games resource folder when the games code needs to run with are actually in the game resource file on mac os x! mac os x needs all framework dependent files in the fully compiled game resources folder! make sure all the needed frameworks they need have been properly compiled in the game resource file or it's not going to work! mac os x can't run a game if the needed frameworks files are not available in the app resource folder!  like theres alot of framework library files are missing in the mac os x 0.F build that where needed for sound also there are important needed framework  game engine core files that were in 0.E are missing!  the files needed to run the sound and new stuff for mac on 0.F are not been complied eather the 0.F CDDA build is just a big mess of missing frameworks that seem to have been deleted somehow during a pull and even the new needed frameworks that are needed in the new 0.F build for sound also seem to be missing this is why most if not all the post sable E.0 sable releases don't work!

**Comment by actual-nh** [comment]
The problem is that different test builds are taking place on different machines (whether github or personal), many of which happen to already have the libraries in question (due to version of OS, being a developer's machine, or whatever), so it's rather hard to tell what needs including.

**Comment by ashtiboy** [comment]
well how to make sure there's a proper build to to test the build for each missing framework then if you try to run it and it give a crash error then add the new framework that it says it needs until it works! also we cant sorport anything older past mac os x 10.12.0 at the minimum without breaking everything! if you don't have a mac that can sorport mac os x 10.12.0 or newer than either get a new mac that can support it or get a new pc! it is highly recommend that no one tries to run 0.F or combile 0.F on mac os x older than 10.12.0 bescue that's just too old for both ways of compatibility at this point and its starting to break everything i got mac os x 10.13.6 and it ran E.0 just fine but something F*** the 0.F build up when they were making a pull requests  that tried to fix crashes on mac os x version older then mac os x 10.12.0 is when things started to not work!
