### ISSUE TITLE
Hunting Lodge won't generate on start

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#49580]
# Describe the bug
Using Safe Place I can't succesfully get the hunting lodge to generate, first reported by LSF and confirmed by me.

# Steps To Reproduce
Get latest experimental 
Create a safe place start and choose Hunting Lodge variant
Fail to generate

# Expected behavior
Game starts normally.

# Screenshots

# Versions and configuration

# Additional context

**Comment by Maleclypse** [comment]
@Venera3  You know this space much better than I do.

**Comment by Venera3** [comment]
The start location points at the terrain `lodge_ground`, but the special uses `lodge_ground1`, changing it allows it to spawn.
