### ISSUE TITLE
Dropping everything with "," crashes the game

### ISSUE THREAD

**Issue by hansonry** [CleverRaven/Cataclysm-DDA#49588]
# Describe the bug

On my character when I try to drop everything in my inventory using "d" -> "," causes a crash to occur

# Steps To Reproduce

1. Load My save
2. Press "d" for drop
3. Press "," for select all

# Expected behavior
I would expect all items to be selected for dropping and for the game to not crash.

# Screenshots

None

# Versions and configuration

 - OS: Linux Mint 20.1
 - Game Version: commit 1ddd145bc69c9a776812b2639314206a1d70808c
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: None
 - g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

# Additional context
[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6760752/config.zip)
[Chaires.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6760754/Chaires.zip)

**Comment by hansonry** [comment]
I am suspect of the vegetable oil or something related to it:
```
(gdb) p *iter
$22 = (inventory_entry &) @0x555592ffd310: {locations = std::vector of length 1, capacity 1 = {{static nowhere = {static nowhere = <same as static member of an already seen type>, 
        ptr = std::shared_ptr<item_location::impl> (use count 1, weak count 0) = {get() = 0x55555a52adf0}}, ptr = std::shared_ptr<item_location::impl> (use count 6, weak count 0) = {get() = 0x55555dddf260}}}, chosen_count = 240, 
  custom_invlet = -2147483648, cached_name = "vegetable cooking oil", highlight_as_parent = false, highlight_as_child = false, custom_category = 0x55558e94d940, enabled = true, _indent = true}
(gdb) n
1228	            iter = entries.erase( iter );
(gdb) p * iter
$23 = (inventory_entry &) @0x555592ffd310: {locations = std::vector of length 1, capacity 1 = {{static nowhere = {static nowhere = <same as static member of an already seen type>, 
        ptr = std::shared_ptr<item_location::impl> (use count 1, weak count 0) = {get() = 0x55555a52adf0}}, ptr = std::shared_ptr<item_location::impl> (use count 6, weak count 0) = {get() = 0x55555dddf260}}}, chosen_count = 240, 
  custom_invlet = -2147483648, cached_name = "vegetable cooking oil", highlight_as_parent = false, highlight_as_child = false, custom_category = 0x55558e94d940, enabled = true, _indent = true}
selection_column::on_change (this=0x55555dda6730, entry=...) at src/inventory_ui.cpp:1230
1230	        entries_unfiltered.clear();
(gdb) p *iter
$24 = (inventory_entry &) @0x555592ffd310: {locations = std::vector of length 1, capacity 1 = {{static nowhere = {static nowhere = <same as static member of an already seen type>, 
        ptr = std::shared_ptr<item_location::impl> (use count 1, weak count 0) = {get() = 0x55555a52adf0}}, ptr = std::shared_ptr<item_location::impl> (use count 458758, weak count 458756) = {get() = 0x555592f70c50}}}, 
  chosen_count = 240, custom_invlet = -2147483648, cached_name = "\000\000\000\000\000\000\000\000\020\240?ZUU\000\000g oil", highlight_as_parent = false, highlight_as_child = false, custom_category = 0x55558e94d940, enabled = true, 
  _indent = true}

```

**Comment by hansonry** [comment]
Maybe not directly related to the vegetable oil. If I drop one item, it don't crash, if I pick the item back up, it does crash.

**Comment by anothersimulacrum** [comment]
I don't get a crash. I am going to recompile with UBsan and Asan, as I suspect that could change things.

**Comment by HarleyLorenzo** [comment]
I can confirm this, it just happened to me. I'm trying to reproduce the bug so I can find exactly what's causing it, but I got a crash just now by dropping all on a fresh save.

**Comment by anothersimulacrum** [comment]
I cannot reproduce with UBsan and Asan either, on the provided save.

**Comment by HarleyLorenzo** [comment]
> I cannot reproduce with UBsan and Asan either, on the provided save.

I am having a hard time reproducing it on my end with my own save. I reloaded the autosave and did everything in pretty much the exact way the first time, including having the same inventory (I'm 99% sure I did anyway) and it didn't work. There might be something _really fun_ happening in the background here, maybe, so I'm gonna keep playing and saving before anytime I use the drop all hoping I can catch it then.

**Comment by hansonry** [comment]
Well, I am going to pass out for tonight. Tomorrow I will get my gcc version in case that is causing it. (I'm on my cell right now)

**Comment by hansonry** [comment]
My g++ version is as follows:
g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

@anothersimulacrum What is your compiler/version? Maybe I can get it and give it a try.

**Comment by hansonry** [comment]
I dug a little deeper. This deletes the vegetable oil from the list. It seems to work ok: https://github.com/CleverRaven/Cataclysm-DDA/blame/master/src/inventory_ui.cpp#L1228


It seems like this: https://github.com/CleverRaven/Cataclysm-DDA/blame/master/src/inventory_ui.cpp#L878 is where things go a little strange. After this line of code runs, the `entries.end()` changes to something else. While the `iter` remains the same.

**Comment by anothersimulacrum** [comment]
> My g++ version is as follows:
> g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
> 
> @anothersimulacrum What is your compiler/version? Maybe I can get it and give it a try.

I was using
```
clang version 12.0.0
Target: x86_64-pc-linux-gnu
Thread model: posix
```

**Comment by hansonry** [comment]
> clang version 12.0.0

Linux Mint is making it unnecessarily hard to get llvm installed. I might pass on this. I was hoping it was just going to be a newer version of g++ :) Thanks anyway.

**Comment by anothersimulacrum** [comment]
I can try with a newer version of g++ (11.1.0), but I haven't had Asan and UBsan work too well with g++ in the past.

**Comment by hansonry** [comment]
My  C++ is not very strong. Is it possible the iterator is invalidating it self based on what `prepare_paging()` is doing and clang just takes a more conservative approach?

I found this random thing by googling: https://www.geeksforgeeks.org/iterator-invalidation-cpp/
