### ISSUE TITLE
Overmap missing tiles with various graphics packs

### ISSUE THREAD

**Issue by venum4k** [CleverRaven/Cataclysm-DDA#49584]
# Describe the bug

For the majority of texture packs, tiles such as roads have missing sprites on the map screen.

# Steps To Reproduce

Pick a graphics pack without a complete set of tiles for the new map renderer and look at the world map.

# Expected behavior

All tiles missing a sprite fallback to ASCII

# Screenshots

MSXotto+
![image](https://user-images.githubusercontent.com/1928247/124399359-c2115e00-dd12-11eb-9f7d-ff036aa898dc.png)
ASCIITiles
![image](https://user-images.githubusercontent.com/1928247/124400219-c3de2000-dd18-11eb-9779-a0a62ec0ef44.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 1ddd145 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Aftershock [aftershock],
    DinoMod [DinoMod],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Mythical Martial Arts [MMA],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    DinoMod - UndeadPeople Tileset [DinoModUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    My Sweet Cataclysm - UndeadPeople Tileset [My_Sweet_CataclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP]
]

# Additional context

I have tested it on completely vanilla worlds and the problem persists so the pile of mods from my main save's report probably isn't too important.

**Comment by Fris0uman** [comment]
MSX got updated there https://github.com/CleverRaven/Cataclysm-DDA/pull/49583
The bigger issue is that a lot of tiles don't have fallbacks and it's unclear to predict which ones I think

**Comment by ZhilkinSerg** [comment]
Tileset authors should fill in missing overmap terrain sprites eventually. Also there would be an option to toggle overmap tiles soon. I am not sure about fallback - it is generally tricky, but could work for linear terrains like roads.

**Comment by venum4k** [comment]
MSX was just the first example. Retrodays+, Neodays, ASCIITiles, BrownLikeBears, ChestHole16, Cuteclysm, Hoder's, UDP (I know it's unofficial) and HitButton iso (also seems to have issues beyond just this problem) seem to have missing tiles in the overmap.

**Comment by ZhilkinSerg** [comment]
That's right - it is a brand new feature and only a few tilesets were updated for it as of now.

**Comment by venum4k** [comment]
I understand the problem, I made this issue because of the amount of people coming into channels on the discord asking why their map was broken.

**Comment by Fris0uman** [comment]
No but there's an issue with fallbacks because ASCIITILE is missing stuff and it should just work in an ideal world.

**Comment by venum4k** [comment]
![image](https://user-images.githubusercontent.com/1928247/124400113-08b58700-dd18-11eb-92e4-ea322b147713.png)
Here's the image you asked for

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/updated-game-map-looks-very-different/26596/6

**Comment by eltank** [comment]
Anyone who builds the game from source can simply edit overmap_ui.cpp:1142 (the draw function) to "if( true )" to force the overmap to be render with ASCII as before. Everyone else should wait for PR #49586 to be merged and picked up in an experimental release, then toggle the option from the in-game menu.
