### ISSUE TITLE
Car Crash scenario cannot be used

### ISSUE THREAD

**Issue by LaVeyanFiend** [CleverRaven/Cataclysm-DDA#49608]
# Describe the bug

It is not possible to use the Car Crash scenario, due to inability to find location.

# Steps To Reproduce

1. Choose Car Crash scenario.
2.  Attempt to spawn in.
3. Game will never find a valid location.

# Expected behavior

Ability to use the scenario

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 1f0b625 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

I used standard city size & spacing.

**Comment by ZhilkinSerg** [comment]
```
  {
    "type": "start_location",
    "id": "sloc_road",
    "name": "Road",
    "terrain": [
      { "om_terrain": "road_straight", "om_terrain_match_type": "PREFIX" },
      { "om_terrain": "road_curved", "om_terrain_match_type": "PREFIX" },
      { "om_terrain": "road_end", "om_terrain_match_type": "PREFIX" }
    ]
  }
```
