### ISSUE TITLE
Re-implementation of optional disabling starting NPCs

### ISSUE THREAD

**Issue by FeelsBadMatey** [CleverRaven/Cataclysm-DDA#49614]
# Is your feature request related to a problem? Please describe.
Not having easy access to disabling starter NPCs in scenarios (e.g. burning building) was a feature before, but it's been removed between now and 2018.

# Describe the solution you'd like
Re-implementation of the toggle would be much appreciated.

# Describe alternatives you've considered
Avoiding the scenarios with starting NPCs forever.

# Additional context
Unsure of why the feature was removed. Found this, though: #25793

**Comment by Night-Pryanik** [comment]
You can always add a `LONE_START` flag to the scenario you want to play, and this will remove the starting NPC in it.

**Comment by ZhilkinSerg** [comment]
> Unsure of why the feature was removed.

The feature was not removed - it is now controlled with `LONE_START` scenario flag. No need to have it in options menu.

**Comment by FeelsBadMatey** [comment]
True. Apolocheese.

**Comment by FeelsBadMatey** [comment]
Quite embarrassingly, I'm having difficulty editing the scenarios json by hand, and... there's no better place to ask for help than here, right?

**Comment by Broken27** [comment]
> Quite embarrassingly, I'm having difficulty editing the scenarios json by hand, and... there's no better place to ask for help than here, right?

Open Scenarios.json with notepad++ or a similar program, search for the scenario you want, add LONE_START to the flag list of the scenario you want to modify.

For example, if we wanted to modify the default Evacuee scenario, we would go from this:

![Screenshot - 06_07_2021 , 18_19_56](https://user-images.githubusercontent.com/67008253/124634728-f60d9000-de86-11eb-9d4b-ed293775b369.jpg)

To this:

![Screenshot - 06_07_2021 , 18_20_41](https://user-images.githubusercontent.com/67008253/124634750-fd349e00-de86-11eb-87fe-f924d4259245.jpg)

**Comment by FeelsBadMatey** [comment]
> > Quite embarrassingly, I'm having difficulty editing the scenarios json by hand, and... there's no better place to ask for help than here, right?
> Open data/Json/Scenarios.json with notepad++ or a similar program, search for the scenario you want, add LONE_START to the flag list of the scenario you want to modify.


Done to little effect. I'm going to leave this open and continue to just play missed.

**Comment by FeelsBadMatey** [comment]
Using notepad++ it was easy peasy, thanks.
