### ISSUE TITLE
Vacuum oven has transdimensional battery that weighs 10x that of the oven itself

### ISSUE THREAD

**Issue by pjf** [CleverRaven/Cataclysm-DDA#49618]
# Describe the bug

Vacuum ovens from #37946 weigh 40.86kg and occupy 27 litres of space, but take large storage batteries, which weigh 400kg and occupy 50 litres of space!

This does not seem consistent with the known laws of physics or lab equipment design.

# Steps To Reproduce

1. Spawn a vacuum oven
2. Spawn a large storage battery
3. Look at their weights and sizes
4. Reload the vacuum oven with the battery, just to be sure you're not imagining things.

# Expected behavior

The vacuum oven takes a battery which is smaller than itself. Does it really need 80MJ (~22kWhrs)? Most other tools take medium or large batteries.

# Versions and configuration

- 1f0b625fec9c9712e7dff303462bcd9c1112e770

**Comment by ActualDio** [comment]
From what Ive seen these types of things work at around 1kW of power for 24L volume (Im assuming 27 isnt the inside volume) so you have an hourly energy cost of around 3.6MJ if Im not mistaken

**Comment by Qrox** [comment]
If it needs that much electricity it might be better to make it a vehicle part.

**Comment by actual-nh** [comment]
It does also depend on how much you're heating it up, of course; not sure how much of an impact that would have.

**Comment by Night-Pryanik** [comment]
As of 05 November 2024, vacuum oven no longer accepts batteries, it connects to power grid.
