### ISSUE TITLE
Inappropriate monsters spawned at freshwater research station, weird behavior

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#49625]
1. Find a freshwater research station
2. Enter it, descend using the ladder
3. For some reason, there are sewer rats in the depths of the lake, outside of the actual station. Also sewergators and penguins, but this might not be a bug since they can actually dive deep.

My research is inconclusive, it seems that rats only have a limited ability to actually dive. According to wikipedia [they can swim up pipes to get into toilets](https://en.wikipedia.org/wiki/Rat#As_pests), but why would they be diving in the depths of a lake?

If you are at e.g Z level -3 in the freshwater research station, teleport outside so you are standing on the bulkhead. For some reason, you can submerge into it (`>`), which should not be possible.
I know there are no fluid dynamics and one can not dive to change Z levels, but this seems weird.

**Comment by anothersimulacrum** [comment]
@Venera3 I know you've looked at monsters spawns in these sort of areas recently, do you have any insight?

**Comment by Venera3** [comment]
Ah, my newest nemesis `GROUP_SEWER`. #48772 will fix errant sewer mobs on z-1

**Comment by NetSysFire** [comment]
Not reproducible anymore in master.
