### ISSUE TITLE
Text gets truncated in the debug monster spawn menu

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#49627]
Go into the monster spawning section of the debug menu, choose a monster with a long description, e.g a pigeon. The description gets truncated. It should be split in multiple lines instead, also because it improves the readability.

**Comment by Valares** [comment]
**Can't reproduce**.

Tested this in 0.E-3 stable on Windows 7 64-Bit version, no mods.

Please follow the [template](https://github.com/CleverRaven/Cataclysm-DDA/issues/new?assignees=&labels=&template=bug_report.md) when reporting a bug and provide **_all_** information (version, operating system, mods loaded).

**Comment by NetSysFire** [comment]
This is the latest stable (0.F-1, I assumed this is the default) on Arch Linux (which should not matter too much). This is the default world selection, so the cataclysm dda mod is loaded together with bionic professions and disable npc needs.

![image](https://user-images.githubusercontent.com/59517351/124679714-40adfd00-dec5-11eb-9e76-719c5817ef7e.png)

**Comment by DeeUnderscore** [comment]
Looks like this has started happening somewhere between 0.E and 0.F. I have 0.E-10400-g0469910665, which wraps text on that screen, and 0.F, which doesn't. 

![0.E](https://user-images.githubusercontent.com/156239/124681433-d0a17600-dec8-11eb-9b8d-f3210546a305.png)
![0.F](https://user-images.githubusercontent.com/156239/124681436-d1d2a300-dec8-11eb-9f0d-c0795b1f8724.png)

Both of these are on Ubuntu Linux, in the same save.

**Comment by NetSysFire** [comment]
The spawn monster menu has changed and there are no longer monster descriptions, so either this is another bug or it is intended and this issue can be closed
