### ISSUE TITLE
"Bordered" scenario causes game to die

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#49620]
# Describe the bug

Attempting to create a game world using the Bordered challenge causes the game to die while finalizing the world setup.

# Steps To Reproduce

1. Pull latest experimental
2. Create a world with the default mod load
3. Set the Challenge - Bordered scenario
4. Confirm character creation

# Expected behavior

Expected: the game not to die.

# Screenshots

No screenshots possible.

# Versions and configuration

```
- OS: Windows
    - OS Version: 10.0 21H1 19043.1052
- Game Version: d98fcf0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]
```

**Comment by ToxiClay** [comment]
@Night-Pryanik Bordered is your baby; any program flow insight you can offer?

**Comment by Night-Pryanik** [comment]
No idea. It worked without issues back when I was implementing it. Will check it out later today.

**Comment by Night-Pryanik** [comment]
Tested right now on latest experimental (0.F-358). I successfully started a new game with this scenario:

![изображение](https://user-images.githubusercontent.com/11132525/124603703-42eb6980-de7b-11eb-9ae7-04df0f5f073e.png)

What's in your debug.log? What are the settings for your world?

**Comment by Broken27** [comment]
I can confirm that it crashes for me as well.

**Comment by anothersimulacrum** [comment]
"Assertion `can_place_special( special, p, dir, must_be_unexplored )' failed."
https://github.com/CleverRaven/Cataclysm-DDA/blob/0db0077907fda534553c5790f75b9e2a02b52e66/src/overmap.cpp#L4073

**Comment by anothersimulacrum** [comment]
```
p special_id
$2 = (const overmap_special_id &) @0x7fffffffa0a0: {_version = 562, _cid = 338, _id = {_id = 18777,
    _string_id = 0x60600500a998 "world"}}
```

**Comment by Night-Pryanik** [comment]
That's weird. I successfully started a new scenario on my self-compiled version (3 times on three different brand-new worlds), but the game indeed crashes when I try to start the scenario on downloaded version.

**Comment by actual-nh** [comment]
Different optimization settings?

**Comment by anothersimulacrum** [comment]
@ZhilkinSerg @Night-Pryanik Were you both compiling with VS when you failed to reproduce it? I believe VS turns off asserts (It defines `NDEBUG`).

**Comment by Night-Pryanik** [comment]
Yes, I compiled with VS.

**Comment by ZhilkinSerg** [comment]
Nothing is wrong with #48514 per se, but there is a bug introduced in https://github.com/CleverRaven/Cataclysm-DDA/commit/87d79bd086e657b957b5e540dc3db54ac10904fd - `overmap::place_special_forced` puts `false` to `force` parameter of `overmap::place_special`, so assertion in the latter fails:

https://github.com/CleverRaven/Cataclysm-DDA/blob/76612800d24a1b06fe49b7dcd93f94247ed75beb/src/overmap.cpp#L1903-L1908

https://github.com/CleverRaven/Cataclysm-DDA/blob/061b97fbd291be7880b762b8f99938268cec25c9/src/overmap.cpp#L4066-L4074

It is also strange that asserts are enabled in cross-compiled release builds and aren't in VS release build - maybe we need to fix that too for consistency.

**Comment by ToxiClay** [comment]
> ZhilkinSerg made the linked commit at the tail end of 2019, and it does what it's supposed to

> Pryanik opened the PR to add the "Bordered" scenario in mid-April of 2021, which explodes due to ZS' commit

If this doesn't sum up software development in a nutshell, I don't know what does.

**Comment by ToxiClay** [comment]
Bah. I'd need a debugger to figure out what's happening here. There are several places within `can_place_special` where the assertion can fail, but none of them seem to have to do with the `force` variable. :/

**Comment by anothersimulacrum** [comment]
> It is also strange that asserts are enabled in cross-compiled release builds and aren't in VS release build - maybe we need to fix that too for consistency.

Yes, we should have VS builds stop defining NDEBUG, it's been problematic in the past too.

**Comment by Night-Pryanik** [comment]
In any case, there should be some error message, the game shouldn't close without a single word.
