### ISSUE TITLE
Better error message when trying to dig a pit when there is already one

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#49624]
This is a very minor bug.

1. Dig a pit (2x, since it progresses from shallow to deep)
2. Dig a pit again, you will get the "You can't dig a pit in this location.  Ensure it is clear diggable ground with no items or obstacles." error.
3. You should get an error message like "The pit can not be any deeper"

See:
https://github.com/CleverRaven/Cataclysm-DDA/blob/5f90cfb7afbc91aee18528a608874e7fac932cee/src/iuse.cpp#L2824-L2828

**Comment by PracticalMetal** [comment]
Hi, I would like to work on this, can you suggest me ways to get started?

**Comment by anothersimulacrum** [comment]
The [C++ code](https://github.com/CleverRaven/Cataclysm-DDA/wiki/New-Contributors-Guide-C-Code) section of the guide can probably provided some helpful pointers.

The change needed here is simply changing the check as such
```diff
-if( !can_dig_here ) {
+if( here_is_pit ) {
+    p->add_msg( _( "There's already a pit here!" ) )
      return cata::nullopt;
+else if( !can_dig_here ) {
      p->add_msg_if_player( 
          _( "You can't dig a pit in this location.  Ensure it is clear diggable ground with no items or obstacles." ) ); 
+    return cata::nullopt;
 }
 ```
Of course, replacing the `here_is_pit` with a check that the terrain at that position is a pit.

**Comment by PracticalMetal** [comment]
So, we just have to change the error message right?

**Comment by anothersimulacrum** [comment]
You need to check if there's already a pit there, and add a new error message if so.

**Comment by PracticalMetal** [comment]
Thanks for your reply, I am working on it.

**Comment by PracticalMetal** [comment]
Hi, I think I have applied the fix but I want to check if it works or not, can you please suggest me how to test this build and also how I can reproduce the issue?

**Comment by PracticalMetal** [comment]
#49813

**Comment by actual-nh** [comment]
This can be reopened if the fix didn't work; thanks for it!
