### ISSUE TITLE
Missing debug mutations

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#49623]
Since 0.E, the carrying/inventory stashing mechanics have changed, but there are no new debug mutations for it, which would allow you to carry an infinite amount of long objects.
I had problems picking up a halligan bar while wearing nothing and having all debug mutations except the bionic-related ones active.

One can also still get weary and there is no debug mutation to not get weary.
Just spawn e.g an entrenching tool and dig pits until you are weary enough.

**Comment by SariusSkelrets** [comment]
There’s the debug pocket universe item that allows you to store effectively infinite items

To become weary, a spell would work better than a mutation. Spells just need the ability to cause weariness

**Comment by anothersimulacrum** [comment]
As SariusSkelrets said, there's an item for infinite carrying capacity. A debug function to modify the activity tracker would be appropriate, but it's not worth keeping an issue open about suggested debug functions.
