### ISSUE TITLE
Worldgen error when the starting location is the compartmentalized version of the Evac Shelter.

### ISSUE THREAD

**Issue by Grnkchi** [CleverRaven/Cataclysm-DDA#49633]
When attempting to generate a world after creating a character, if the chosen or randomly selected variant of the Evac Shelter is Compartmentalized, the player is sent to the main menu with the following error message:

Unable to generate valid starting location Shelter - Compartmentalized [sloc_shelter_b] in a radius of 3 overmaps. Please report this failure.

Steps To Reproduce:

1. Create a World and go through character creation with the Evacuee Scenario.
2. When finished, select Shelter - Compartmentalized as the starting location.
3. Receive error message.

Expected Behavior:

The successful generation of the world and the start of a new game.

Versions and Configuration:

 - OS: Windows 10
 - Game Version: 0.F; Version in Main Menu: bc28921
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: Sierra Madre; More Locations; Dorf Life; Morlock Village; Ships From OA Additional Buildings (None of my other mods should affect worldgen.)

**Comment by Venera3** [comment]
Could you upload your world file from your save folder and the out-of-repo mod files you use? On a vanilla game I don't have any problem generating one.

**Comment by hexagonrecursion** [comment]
Could not reproduce
- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 31ef3ba [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by Night-Pryanik** [comment]
Duplicate of #35376.
