### ISSUE TITLE
Character creation quality of life

### ISSUE THREAD

**Issue by CrunchyDuck** [CleverRaven/Cataclysm-DDA#49632]
# Is your feature request related to a problem? Please describe.
As the entry point for a new player, character creation could allow better control over randomization.

Changing scenario will wipe any existing profession/stat/trait/skill selection. When trying to create a character or track down a bug, this can be extremely frustrating, and particularly for stats/traits/skills seems needless.
There is no way to randomize only stats/traits/skills.
The option to randomize scenario/profession (*) in their given tabs is not displayed on screen.

# Describe the solution you'd like
- Attempt to preserve profession/stats/traits/skills when changing scenario.
- Allow the ability to randomize only stats/traits/skills from their respective tabs.
- Display "randomize" bind similarly to the "sort" bind.

**Comment by ZhilkinSerg** [comment]
Related - #37869
