### ISSUE TITLE
Beam Scatterer range error

### ISSUE THREAD

**Issue by AdamChirnside** [CleverRaven/Cataclysm-DDA#49634]
# Describe the bug

When attached to an Av22, the Beam Scatterer causes an error that makes the gun functionally unable to shoot anything other than the player's tile.

# Steps To Reproduce

1. Have an Av22 with a Beam Scatterer attachment.
2. Try to aim and move the cursor off the player.

# Expected behavior

# Screenshots

N/A

# Versions and configuration

- OS: Windows 10
    - OS Version: 10.0 2009
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Disable NPC Needs [no_npc_food],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Alternative Map Key [alt_map_key],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    No Rail Stations [No_Rail_Stations],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Graphical Overmap Vanilla Additions [Graphical_Overmap_SDG]
]

# Additional context

 DEBUG    : Exceeded allowed range!

 FUNCTION : bool target_ui::set_cursor_pos(const tripoint&)
 FILE     : src/ranged.cpp
 LINE     : 2335

**Comment by anothersimulacrum** [comment]
@Maleclypse @Mom-Bun @John-Candlebury
