### ISSUE TITLE
misc raw chemical production

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#49649]
# Is your feature request related to a problem? Please describe.
- currently no way to produce acetone, phenol, or sulfur and ammonia
- tainted and mutant meat is largely left to rot currently
- tainted bones have little use
- lack of a good early game source of acid
- current way to get potassium hydroxide is overcomplicated
- no use for excess casings

# Describe the solution you'd like
- acetone can be produced by dry distilling calcium acetate. so effectively distilling acetic acid (or vinegar) with limestone as a needed "tool"

- salicylic acid, the active ingredient in willow bark breaks down into phenol when heated. thus phenol can be made by first extracting salicylic acid from willow bark, then distilling off the phenol with heat

- when meat rots it emits ammonia and hydrogen sulfide. the ammonia can be collected by bubbling the gas through water, while the hydrogen sulfide can be captured and converted to sulfur be bubbling the remaining gas through bleach.

- sulfur can also be produced from sulfuric acid when carefully combined with hydrogen produced by using a reactive metal (aluminum, magnesium etc)

- hard burning of tainted bone meal should be able convert it to quicklime by burning off the phosphate and anything organic

- quicklime can be converted to limestone by reacting with water and CO2 in the air

- combustion of PVC plastic releases HCl which turns to hydrochloric acid when mixed with water

- lye powder from wood ash is largely potassium hydroxide. therefore wood ash can be used with water to make potassium hydroxide.

- brass from casings can be distilled to separate the copper and zinc (brass is 2 parts copper, 1 part zinc)

# Describe alternatives you've considered
- fermenting a certain bacteria can produce acetone
- coal distillation can give phenol and ammonia
- sulfur can be produced by capturing hydrogen sulfide from rotting vegetation
- distillation of acid zombie stomach contents to get hydrochloric acid
# Additional context
- acetone and phenol could be used early game as a disinfectant. acetone can also be used as an inhalant drug (think sniffing glue)
- it may be necessary to replace the ammonia water frequently to prevent hydrogen sulfide build up.
- then it may be necessary to distill to the ammonia water to concentrate and purify the ammonia

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
