### ISSUE TITLE
[Bug] Cataclysm ++ crashes on loading save or starting new game.

### ISSUE THREAD

**Issue by JackReport** [CleverRaven/Cataclysm-DDA#49643]
Windows 10
What version were you playing: 1f0b625 (tiles)
Version string : 2021-07-05-1542
Load up Cataclysm ++ with current build, try to make a new world with the mod and load it.

Error before crash:

16:00:19.526 ERROR : src/main_menu.cpp:1149 [bool main_menu::load_character_tab(bool)] Error: Json error: data/mods/nocts_cata_mod_BN/Monsters/c_monsters.json:325:100: invalid monster flag: "BLEED"

    "special_attacks": [ [ "GRAB", 10 ], [ "BIO_OP_TAKEDOWN", 30 ], [ "LUNGE", 20 ] ],
    "death_drops": "mon_zombie_bio_knife_death_drops",
    "flags": [ "SEES", "HEARS", "SMELLS", "POISON", "NO_BREATHE", "FILTHY", "PATH_AVOID_DANGER_1", "
                                                                                                   ^
                                                                                                    BLEED" ],
    "delete": { "upgrades": { "half_life": 28, "into": "mon_zombie_bio_knife" } }
  },

16:00:29.744 : Log shutdown.

**Comment by JackReport** [comment]
If further information is required, let me know, will submit as well.

**Comment by actual-nh** [comment]
That's the version for C:BN, not C:DDA - "data/mods/nocts_cata_mod_BN".

**Comment by anothersimulacrum** [comment]
Download https://github.com/Noctifer-de-Mortem/nocts_cata_mod , and copy over the folder with `DDA` at the end to your mods folder.
If you need further assistance, let us know, but I'm going to close this issue because it's an issue with a third party mod we can't do anything about.

**Comment by JackReport** [comment]
> That's the version for C:BN, not C:DDA - "data/mods/nocts_cata_mod_BN".

Interesting, I had only used the launcher to install cataclysm ++. However thanks for the info.

**Comment by JackReport** [comment]
> Download https://github.com/Noctifer-de-Mortem/nocts_cata_mod , and copy over the folder with `DDA` at the end to your mods folder.
> If you need further assistance, let us know, but I'm going to close this issue because it's an issue with a third party mod we can't do anything about.

I just done a fresh manual install, and still got the same error oddly enough, It was running fine before I had updated to a newer version of cdda, but this was a 2-4 days ago. Should I submit an issue to nocts_cata_mod?

**Comment by anothersimulacrum** [comment]
I am not sure. Are you sure you copied over the DDA folder and not the BN one? Try deleting the BN folder, it may be somewhere problematic.

**Comment by JackReport** [comment]
> I am not sure. Are you sure you copied over the DDA folder and not the BN one? Try deleting the BN folder, it may be somewhere problematic.

Deleting the BN one fixed it, although I think there was a duplicate from the launcher that was installing both mods somehow.
Thanks for your help!
