### ISSUE TITLE
we need a lesser sludge trail

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#49644]
# Is your feature request related to a problem? Please describe.
Sludge trails are a feature from giant slugs that I borrowed from pupating zombies. Unfortunately, the sludge trail from pupating zombies is just overboard given their frequency.

# Describe the solution you'd like
We need a "small_sludge_trail" feature that dispenses sludge, but only about once every other tile or so, and only one sludge tile - not a 3x3 area. Apply it to all the pupating zombie types.

# Describe alternatives you've considered
We could use a shorter-lived sludge field as well or instead.
Alternatively the zombie could occasionally barf out a 5x5 sludge spatter around itself every few minutes.

# Additional context
Now that we have more pupating zombies we need this even more.

**Comment by actual-nh** [comment]
A continuous (thus deterministic for testing) but single-tile trail with a shorter-lived sludge field could work.
