### ISSUE TITLE
gypsum

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#49646]
# Is your feature request related to a problem? Please describe.
the lack of a good pseudo renewable source of sulfuric acid or sulfur
# Describe the solution you'd like
introduce gypsum (CaSO4) as a raw material for making sulfuric acid

# Describe alternatives you've considered
sulfur production by forcing gases containing hydrogen sulfide through bleach to produce sulfur. these gases can be made by rotting vegetation.

# Additional context
- gypsum is a major component of drywall so it would be a fairly common drop by smashing generic walls
- gypsum is also a common type of stone so mining could feasibly produce it like it does with limestone
- to convert gypsum to sulfuric acid you only need to mix with a strong acid

**Comment by Mom-Bun** [comment]
Do you have an actual suggestion of how to harvest the gypsum from the drywall? instead of just smashing it, we need more detail for this suggestion

**Comment by robotic-gamer** [comment]
I was thinking short term adding it as something you can get from smashing was the easiest way. that and burning is how you can currently get stuff from walls. maybe long term there should be a deconstruct wall construction task?

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
