### ISSUE TITLE
crude disinfectant

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#49651]
# Is your feature request related to a problem? Please describe.
there are a lot more things that could be used to treat bites then are currently available

# Describe the solution you'd like
add a "crude disinfectant" type with a 60-80% chance to treat bites
substances that could be used directly include:
- vinegar
- vodka, whiskey other "strong drinking alcohol"

substances that need watering down first:
- acetic acid
- acetone
- bleach
- oxidizer powder
- phenol

# Additional context
- in game there seems to be a noticeable treatment gap between cauterizing (50%) and current disinfectants (95%).
- cattail jelly is the only thing currently filling the gap but it is not always an option if you lack the starting skills or are simply away from where cattails spawn

**Comment by logros13** [comment]
There is already makeshift disinfectant craftable from ethanol or denatured alcohol (which can in turn be crafted from any alcoholic beverage). 

http://cdda-trunk.chezzo.com/disinfectant_makeshift/craft

**Comment by robotic-gamer** [comment]
the problem is early game distillation equipment is not available. thus this is not an option until you have a chemistry set. while in real life people have used vodka straight from the bottle to clean wounds.

**Comment by actual-nh** [comment]
Could you instead add any additional information to #48418? It's still open for discussion.
