### ISSUE TITLE
misc complex chemistry

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#49657]
# Is your feature request related to a problem? Please describe.
- lack of a way to make antibiotics
- the lack of renewable stimulant production beyond caffeine pills
- lack of a way to renewably make improvised gasoline
- the lack of a renewable source of cinnamon

# Describe the solution you'd like
- produce sulfa drug antibiotics from:
ammonia, phenol, acetic acid, hydrochloric acid, sulfuric acid and lye

- amphetamine based stimulant pills from:
phenol, (zinc or aluminum), glycerol, formic acid, and ammonia

-a makeshift gasoline made from mesitylene/psudocumene mix plus a bit of ether.
note mesitylene/psudocumene mix can be made by distilling acetone with sulfuric acid similar to turning ethanol into ether

-a cinnamon powder knockoff can be made by mixing cinnamaldehyde with flour
ethanol---silver------>acetaldehyde
charcoal+oxygen ---->carbon monoxide
phenol+(zinc+aluminium)---->benzene
benzene +carbon monoxide--->benzaldehyde
benzaldehyde + acetaldehyde + lye powder (5 units)---->cinnamaldehyde
net:
ethanol + charcoal + phenol+ (zinc + aluminum)+lye powder + flour--silver->cinnamon

# Describe alternatives you've considered
- growing bacteriophages
- adrenal gland extract
- extending normal gasoline with something like ethanol
 
# Additional context
- given the nature of sulfanilamide it would be a narrow-spectrum antibiotic
- more detailed process:
phenol+(zinc or aluminum )->benzene
glycerol + formic acid->allyl alcohol
allyl alcohol + hydrochloric acid-> allyl chloride
benzene + allyl chloride + ammonia -> amphetamine
- mesitylene and psudocumene are benzene with 3 methyl groups similar to toluene's 1 methyl group.
the ether is to compensate for the problems with trying to run an engine on pure toluene.
- cinnamaldehyde is responsible for cinnamon powders taste

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
