### ISSUE TITLE
Português (Brasil) localization's code obstructs the interface and denies access to information.

### ISSUE THREAD

**Issue by MomoiroShinobinomono** [CleverRaven/Cataclysm-DDA#49650]
# Describe the bug

Português (Brasil)'s localization's **"View help"** section of an in-game **"Actions"** menu contains pieces of code visible to a player.
Said errors also prevent player from accesing such submenus with information as: 
1. **"Description of map symbols"**.
2. **"Description of gun types"**.
3. **"FAQ (contains spoilers!)"**.

Additionally, the **"Radioactivity and mutation"** subsection is displayed incorrectly but, unlike previous examples, it is accesible.

_As I know nothing about a discussed language, all the names of the subsections are written in this issue as they are presented through the default localization._ 

# Steps To Reproduce
1. Change localization to Português (Brasil).
2. Make a new character.
3. Press enter.
4. Prezz 0.
5. Try to access **"Description of map symbols", "Description of gun types", "FAQ (contains spoilers!)"** and **"Radioactivity and mutation"** subsections by pressing _2, 3, 4_ buttons or _i_ button respectively.

# Expected behavior

Game's interface's supposed to look clean with no code spilling out on it.
All the menus that are supposed to be accessible, should be.

# Screenshots

![screenshot](https://user-images.githubusercontent.com/86895942/124669924-e6f50500-debb-11eb-91e3-fcbd7418fad5.png)

# Versions and configuration

 - OS: Windows 7 Professional SP1
 - Game Version: 6419e56
 - Mods loaded: [dda, no_npc_food, Bionic Professions]

**Comment by Qrox** [comment]
As far as I know `&lt;` and `&gt;` are not supported by the game, so this might be a error due to translation.

**Comment by BrettDong** [comment]
This is a translation error:

```po
#: lang/json/help_from_json.py
msgid "<2>: Description of map symbols"
msgstr "&lt;2&gt;: Descrição dos símbolos do mapa"
```

**Comment by Night-Pryanik** [comment]
Translation was fixed some time in the past.
