### ISSUE TITLE
cordite based smokeless gunpowder

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#49664]
# Is your feature request related to a problem? Please describe.
lack of ability to manufacture gunpowder
# Describe the solution you'd like
cordite can be made from:
2 guncotton
1 glycerol
1 sulfuric acid
1 nitric acid
4 tallow
1 acetone

# Describe alternatives you've considered
basing the gunpowder recipe off something other then cordite
# Additional context
- cordite is 65% guncotton, 30% nitroglycerine and 5% petroleum jelly, with some acetone used as a solvent in manufacturing
- guncotton can be made from rags, water, sulfuric acid and nitric acid.
- nitroglycerine can be made from glycerol, sulfuric acid and nitric acid
- petroleum jelly can be substituted with tallow due to there physical and chemical similarities
- lastly acetone can be made by dry distilling acetic acid and limestone

**Comment by actual-nh** [comment]
@robotic-gamer: There's been some discussion over on Discord about this previously - see <https://discord.com/channels/598523535169945603/598523535169945607/848661762185232465> for instance. More generally, please take a look at <https://github.com/CleverRaven/Cataclysm-DDA/wiki/Frequently-Made-Suggestions> (not sure if any you're making are on there, but you've made quite a few!).

**Comment by actual-nh** [comment]
Oh. And perhaps combine, for instance, all the posts related to gunpowder (or smokeless gunpowder - another one was dealing with guncotton also) together? Thanks!

**Comment by robotic-gamer** [comment]
duly noted. I added guncotton to alternates in the alternate blackpowder recipes suggestion. thank you for your feedback I was unaware of the frequently made suggestions page. fortunately it seems it was just this idea that overlaps with it. easiest way to add negatives to crafting would be for a failure mode that results in an explosion. I'll just close this in the meantime so it isn't cluttering things up needlessly.
