### ISSUE TITLE
craftable light batteries

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#49669]
# Is your feature request related to a problem? Please describe.
lack of a way to make rechargeable batteries

# Describe the solution you'd like
craftable silver zinc batteries that can be used as the basis to make craftable light batteries

# Describe alternatives you've considered
makeshift non-rechargeable batteries based on steel, some other metal and salt water

# Additional context
- silver zinc batteries are second to lithium ion batteries in terms of charge density
- the needed components would be zinc, silver, potassium hydroxide, and some sort of casing material

**Comment by Mom-Bun** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/issues/30202#issuecomment-489173061 

It is not intended for you to be able to craft batteries, as they are non-renewable and a survivor has the inability to craft them, and if you require power and cannot scavenge normal batteries, you'd have to make lead batteries.

**Comment by robotic-gamer** [comment]
I see, I did not consider it was for balance reasons, my thinking was that it is just like making disposable batteries.

**Comment by anothersimulacrum** [comment]
The disposable battery recipe is possibly incorrect.
