### ISSUE TITLE
makeshift batteries

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#49670]
# Is your feature request related to a problem? Please describe.
an alternative to the hand-crank
# Describe the solution you'd like
- you can make a crude battery from any two corrodible metals and an electrolyte
- with proper tools (metalworking equipment) you can make a non-rechargeable makeshift battery
- components: scrap metal, other metal (scrap copper, aluminum can etc.), salt water, paper, (super) glue.

# Additional context
- for balance I would give it a charge half of a normal rechargeable battery
- this would  be more suitable for inawood characters then a hand crank to run electronics

**Comment by Qrox** [comment]
The voltage, capacity, and resistance of a battery all depend on the electrode and electrolyte material, so I imagine a makeshift battery like you describe here is only useful for simple applications such as lighting LEDs or fire starting.

**Comment by Zireael07** [comment]
IIRC we used to have a salt water+scrap recipe for a battery and it was removed for being too unrealistic (giving a normal battery as a result).

**Comment by robotic-gamer** [comment]
the easiest solution to represent the use for only simple applications would be to reduce the charge to 25% a normal rechargeable batteries charge (so about 25 for a light battery).

**Comment by Night-Pryanik** [comment]
Should this be fixed by #54287?

**Comment by Inglonias** [comment]
This has been fixed by #54287
