### ISSUE TITLE
early game craftable helmets

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#49674]
# Is your feature request related to a problem? Please describe.
lack of craftable helmets early game
# Describe the solution you'd like
two possibilities
- an arming cap which is the helmet equivalent of a gambeson
- a wooden helmet made by craving out a log

**Comment by I-am-Erk** [comment]
my guy, please slow down on the flurry of issue posts. I appreciate your enthusiasm but this is excessive. Check out the "search" feature as I think some of these have been discussed before, and pace yourself by writing up some more detail into the posts please.

**Comment by robotic-gamer** [comment]
my bad, I just accumulated a bunch of ideas and was waiting for the freeze to end. would it help if I closed and repost a bunch of these latter at a slow pace? I'll consult the search feature now (sorry for not thinking of it beforehand)

**Comment by anothersimulacrum** [comment]
I think you could probably condense an awful lot of your issues into single ones - e.g. the chemistry ones could be one issue.

**Comment by robotic-gamer** [comment]
thanks for the feedback. I'll try to do that now. my thought process was to keep things independent so they could be judged independently.
