### ISSUE TITLE
Auto Sort zones bug

### ISSUE THREAD

**Issue by Atsumari** [CleverRaven/Cataclysm-DDA#49675]
Auto sort zones get pulled by camp.

When you make a camp a z level directly above the area you have all your zones on it pulls all of your zones up a level

1. Build loot zones in the bottom of a building(I used Evac Shelter).
2. Then build a camp 1 z level above said zones.
3. All of your zones get pulled up on z level leaving your sorted base zoneless.

I expected to have multiple loot zones or even have camp specific ones.

OS: Windows
   OS Version: 10.0 2004
   Game Version: 6419e56 [64-bit]
   Graphics Version: Tiles
   Game Language: System language [English]
    Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Monsters [No_Fungi],
    Blaze Industries [blazeindustries]
]

**Comment by hexagonrecursion** [comment]
Confirmed.
* To reproduce:
  1. Create the following zones in the evac shelter basement:
     * Basecamp: Food
     * Basecamp: Storage
     * Loot: Ammo
  2. Create a camp above
* I could not reproduce this issue in a world that already has other camps

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 8051d7d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by RenechCDDA** [comment]
No longer able to reproduce as of https://github.com/CleverRaven/Cataclysm-DDA/commit/c94dc0387513d5bba49eb7d74b2b51a7a4d8c4a0
