### ISSUE TITLE
breaking up large rocks

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#49673]
# Is your feature request related to a problem? Please describe.
lack of use for large rocks early game
# Describe the solution you'd like
a recipe that uses the fact that large rocks can be broken down by quickly heating then cooling it water so that the thermal shock causes it to shatter

# Describe alternatives you've considered
just break it up with a hammer?
# Additional context
this idea is based on the fire-setting mining technique which was used in mining before explosives became available.

**Comment by actual-nh** [comment]
And the need for the shattered pieces?

**Comment by robotic-gamer** [comment]
the shattered pieces is that they would just be rocks. the purpose of the recipe is to give a pre-pickaxe way to get rocks from the large rocks from digging pits.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
