### ISSUE TITLE
Possible new starting traits related to pets and wildlife.

### ISSUE THREAD

**Issue by Xindage** [CleverRaven/Cataclysm-DDA#49676]
# Is your feature request related to a problem? Please describe.
Not related to a problem but it can be something interesting to have in game. Two new mutation to have interactions with animals in general.

# Describe the solution you'd like.
Note: I'm not good with names
Positive trait: Like of animals. -2 (You love animals, there's nothing better than seeing them playing around in this world, unfortunately you cant keep them all with you.)

Seeing a wild passive/neutral/friendly animals give you a morale boost that can last for a hour, wont stack if you see multiples, but it can restart the duration of the buff. +5 for a hour.
Interacting with wild animals for example giving food for them gave you a long lasting morale buff of +8 for 12 hours, even if that animal is not domestically. (I don't think the game allows that yet.)
Playing with a pet gives a better morale than it normally give, since you really like it compared to the others.
If you pet dies that'll drop you morale a lot -35 for a day and can stack multiple times.
Trying to kill wild animals are harder to you.
== Having this trait wont allow you to get psychopath, hate animals and terrifying (goes well with animal empathy)

Negative trait: Hate animals. +2 (You hate animals, since your childhood you couldn't put up with the incessant barking of your neighbor's dog, and now with the apocalypse happening, nothing will stop you from taking out all your fury on them.)

Seeing any kind of animals but zombies variants nearby you makes you angry. -12 for a hour.
Killing any kind of animals including zombies variants give you a good feeling until there's no one alive near you. (Piece and quiet) +6 for 6 hours, it wont stack and remove the debuff from seeing a live animal.
Fighting against zombie animals are normal (regardless if you care for fighting or not). 
You cant have pets or interact with any living animal.
== Having this trait wont allow you to get animal empathy, like animals and pacifist. (goes well with killer drive)

""  That can give a different approach for who like farming and same for who don't like and being not able to interact with animals in late game can be a very negative trait.

# Describe alternatives you've considered
Change animal empathy to something like this, still having a counterpart to it.

# Additional context
We have to revise some mutations that can obtain them and what should cancel who and vice versa.
And I'm up to change this topic if you guys find if something is unbalanced or think if something is missing.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
