### ISSUE TITLE
Add additional pine products and uses for them

### ISSUE THREAD

**Issue by ERRORCODE509** [CleverRaven/Cataclysm-DDA#49689]
# Is your feature request related to a problem? Please describe.
Pine trees (and pine products) are underrepresented in Cataclysm. Just pine cones and pine boughs? Come on, they're supposed to have resin and sap too! And there are way more uses for pine than you may first think.

# Describe the solution you'd like
Adding the following:
- Pine bark
- Boiled pine bark
- Fried pine bark
- Roasted pine bark
- Ability to consume the previous 4 entries
- Pine resin
- Ability to harvest pine resin (normally done by damaging tree, waiting a few days for it to repair the damage with pine resin, then harvesting the excess)
- Ability to consume pine resin like gum (and possibly include its anti-bacterial and joint pain relief properties)
- Ability to craft glue using pine resin
- Pine sap
- Ability to craft glue using pine sap
- Ability to use pine sap for fire-starting
- Ability to chew pine sap for relief from cold symptoms
- Ability to use pine sap as an antiseptic, anti-inflammatory, and astringent
- Add turpentine
- Ability to craft turpentine using pine sap

Possibly adding the following (placed in a separate category as they may be useless at the moment):
- Ability to use pine sap for waterproofing
- Ability to use pine resin for making fiberglass

Additional things to add (thanks to robotic-gamer):
- Ability to use turpentine as an antiseptic
- Ability to add turpentine to ethanol to make camphine, which is a lamp fuel
- Use turpentine for the treatment of intestinal parasites
- Ability to make camphor by mixing turpentine, acetic acid, strong acid, water, and oxidizer powder
- Use turpentine as a cheap way to extend gasoline by at least 30%
- Ability to use turpentine as flamethrower fuel
- Ability to combine with ethanol/methanol to create makeshift gasoline

# Describe alternatives you've considered
- Not suggesting anything, resulting in me not living up to my title as the Pine Nut Prophet.
- Adding whatever from this list that I can to TGCNP.

# Additional context
There **_IS_** a difference between sap and resin, as stated here: [http://www.differencebetween.net/science/nature/difference-between-sap-and-resin/#:~:text=Summary%3A,the%20outer%20cells%20of%20trees.](http://www.differencebetween.net/science/nature/difference-between-sap-and-resin/#:~:text=Summary%3A,the%20outer%20cells%20of%20trees.)

Sources:
- [https://findanyanswer.com/what-happens-if-you-eat-pine-sap](https://findanyanswer.com/what-happens-if-you-eat-pine-sap)
- [https://www.quora.com/What-are-the-uses-of-Pine-Resin-gathered-from-pine-trees](https://www.quora.com/What-are-the-uses-of-Pine-Resin-gathered-from-pine-trees)
- [https://www.gardeningknowhow.com/ornamental/trees/pine/pine-tree-sap-information.htm#:~:text=Pine%20tree%20sap%20is%20used,removal%20is%20not%20always%20easy.](https://www.gardeningknowhow.com/ornamental/trees/pine/pine-tree-sap-information.htm#:~:text=Pine%20tree%20sap%20is%20used,removal%20is%20not%20always%20easy.)

**Comment by robotic-gamer** [comment]
some uses for turpentine:
- antiseptic
- combined with ethanol to make camphine, a lamp fuel
- treatment for intestinal parasites
- raw material to make camphor ie
turpentine+acetic acid+strong acid+water +oxidizer powder-->camphor
- a cheap way to extend gasoline (by at least 30%)

not certain on this but since turpentine combustion properties are between gasoline and diesel
- flamethrower fuel
- combined with ethanol/methanol to make makeshift gasoline

**Comment by ERRORCODE509** [comment]
Good to know, I didn't research turpentine at all and just focused on pine sap and resin.

**Comment by ifffrt** [comment]
Good post. Never knew you could chew pine resin. Immediately went up my rooftop garden where I stored my pine resin and chewed it for science. 8/10 not sure if would do it again but my mouth smells nice.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
