### ISSUE TITLE
Swage blocks should be removed.

### ISSUE THREAD

**Issue by Atsumari** [CleverRaven/Cataclysm-DDA#49682]
Summary

Balance

Purpose of change

Swage block is useless unless you request it for batch crafting(Which might be more work than that's worth)

Describe the solution

Remove the requirement when crafting items.

Describe alternatives you've considered

You could change the swageblock to a hot cut and it would make way more sense.

Testing

None

Additional context

I'm a blacksmith in real life and only use swages when I'm making A LOT of an item. It's used for producing large amounts of things, but isn't necessary.

https://www.youtube.com/watch?v=ZBfkmPt-WYw&ab_channel=Torbj%C3%B6rn%C3%85hman

This video shows the process: The blacksmith shown uses something known as a "hotcut" and a "header" at the end of the video. These are NOT required but makes cutting the nail and putting on the head of the nail MUCH easier.

**Comment by Gaunah** [comment]
Heads up to #49691 which got recently merged.

**Comment by actual-nh** [comment]
Fixed by #49691.
