### ISSUE TITLE
"Good Memory" and "Forgetful" traits are crippled by an optionality of Skill Rust

### ISSUE THREAD

**Issue by MomoiroShinobinomono** [CleverRaven/Cataclysm-DDA#49696]
# Is your feature request related to a problem?

I'm always frustrated when I cannot take "**Good memory**" trait as it is takes 3 whole points. 
My problem with it is that I never play with skill erosion and never did I see anyone doing it either.
To spend 3 points on a crippled trait half the functions of which I'm never going to access seems unreasonable, as Skill Rust is an **_optional_** addition to the gameplay that is even set at the Debug subsection of the Options menu.
Moreover, it looks especially unreasonable considering the fact the "**Good Memory**" and "**Forgetful**" traits are **_always_** there when you create a new character.

# Describe the solution

### Split the functions of the "**Good memory**" trait:
1. Take out a _slower erosion rate of skills_ part from the "**Good Memory**" trait and make it into its own trait which is only accesible in the character creation menu if the player has turned on Skill Rust in the Options.
 - It could be renamed as "**Mnemonist**" or left as is.
2. Merge the part about being able to remember more terrain from "Good Memory" trait with the "Scout" trait and up the price of "Scout" to **2** points. 

### Split the functions of the "**Forgetful**" trait:
1. Take out a _faster erosion rate of skills_ part from the "**Forgetful**" trait and make it into its own trait which is only accesible in the character creation menu if the player has turned on Skill Rust in the Options.
 - It could be renamed as "**Dementia**" or left as is.
2. Merge the part about being able to remember less terrain from "**Forgetful**" trait with the "**Topographagnosia**" trait and up the price of "**Topographagnosia**" to **-2** points.

**1**'s are going to ensure that the players who want to give their characters less or more memory map capacity will not be limited by an **_optional_** Skill Rust and also slightly tidy the Traits section of the character creation menu, while **2**'s will add more roleplay value to already existing traits.

Thanks.

**Comment by actual-nh** [comment]
The map memory system may be reworked before too long - see #47253.

**Comment by MomoiroShinobinomono** [comment]
I've got an additional idea about a memory map system, it would be really nice if players could designate 1 or 2 or couple more overmap squares as their "base" which will prevent a memory map of said squares from being forgotten.
Most complaints I saw in regards to the current system were exactly that characters easily forget layout of places they tend to spend weeks or even months at.
Which is understandably both jarring and unreasonable.
It could be called "**Mental note**".

**Comment by anothersimulacrum** [comment]
The PR linked above will make that irrelevant.

**Comment by MomoiroShinobinomono** [comment]
Good.
The only thing that is still bothering me is the fact that my issue is not only about map memory.
Sorry, maybe I structured it so it's unreadable.
An idea to hide Skill Rust dependant traits from traits list when Skill Rust is disabled is still a good suggestion in my opinion.
Should I open a separate issue for that?

**Comment by actual-nh** [comment]
> Should I open a separate issue for that?

If the PR doesn't remove the traits completely, probably yes.

**Comment by kevingranade** [comment]
The map memory related traits are almost certainly going away, and not coming back unless it's with some kind of mechanism to prevent forgetting "very frequently visited areas".
