### ISSUE TITLE
bed sheet to patchwork sheets unrealistic

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#49694]
# Describe the bug
Turning* a bed sheet into patchwork sheets takes 30+ hours

Currently you cut it into rags (which is instant) and then have to stitch it back together which takes 6 hours per 1L (4 patchwork sheet)

*Realistically you don't need to cut it into smaller sheets just to sew it back together.  You would just use it as is meaning you're repurposing it not actually disassembling it

# Steps To Reproduce

summon sheet
summon watch
note day and time
cut sheet to rags
make patchwork sheets
note new time

# Expected behavior

process should be Sheet -> patchwork sheets (instant) -> rags (instant)
Process should NOT be instant in reverse obvs.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 1f0b625 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    Stats Through Kills [stats_through_kills]
]

# Additional context

I'm not sure how to change the results of cutting something up.  If someone can point me to the right place I can do a PR for it.

**Comment by Xpyder** [comment]
While we COULD make a Sheet -> patchwork sheets recipe, I think it's better to change the cutting -> patchwork sheets and patchwork sheets -> rags

Based on the assumption we're trying to move away from rags as the default cotton clothing piece as indicated by the Tailoring Rework project (which I forget the link for)

**Comment by Xpyder** [comment]
Oh hey look, it's a palindrome!

**Comment by Night-Pryanik** [comment]
Fixed by #50207.
