### ISSUE TITLE
Can't load game

### ISSUE THREAD

**Issue by RynhardGrey1** [CleverRaven/Cataclysm-DDA#49698]
# Describe the bug

<! Can't load game or create new game on version 8b2485a, receiving the following message:

 DEBUG    : Error: Json error: data/json/overmap/overmap_terrain/overmap_terrain_faction_base.json:207:5: missing required field "type" in object: {
    "id": "faction_base_mansion_e1",
    "name": "mansion base entrance",
    "sym": "M",
    "color": "white",
    "flags": [ "SOURCE_PEOPLE", "NO_ROTATE" ]
  },

    "color": "white",
    "flags": [ "SOURCE_PEOPLE", "NO_ROTATE" ]
  },
    ^
  {
    "type": "overmap_terrain",
    "id": "faction_base_mansion_e2",

 FUNCTION : bool main_menu::load_character_tab(bool)
 FILE     : src/main_menu.cpp
 LINE     : 1149
 VERSION  : 8b2485a
-->

# Steps To Reproduce

< !-- Steps to reproduce the behavior:
1. loading save game.
2. Creating new game/new world
 -->

# Versions and configuration

< 

 - OS: Windows 10
 - Game Version: 8b2485a
 - Graphics version: Tiles undeadpeople
 - Ingame language: English 
 - Mods loaded: StatsThroughSkills, Fuji Millitary profession pack, Disable NPC Needs, Bionic professions
 -->

**Comment by ZhilkinSerg** [comment]
Fixed in https://github.com/CleverRaven/Cataclysm-DDA/pull/49692
