### ISSUE TITLE
Loot placement in Lumbermills is broken

### ISSUE THREAD

**Issue by ThatIdiotMonro** [CleverRaven/Cataclysm-DDA#49697]
# Describe the bug

Items are being spawned in windows, on the winch mechanisms, all sorts of (well, those two) unreachable places.

# Steps To Reproduce

1. Go to Lumbermill
2. Observe magic windows

# Expected behavior

Loot to be on the floor or in crates/benches etc

# Screenshots

![Lumber 1](https://user-images.githubusercontent.com/87063960/124724764-2fd0ac00-df04-11eb-9613-3e130b32ea3f.png)
![Lumber 2](https://user-images.githubusercontent.com/87063960/124724796-352df680-df04-11eb-9607-22d8f185cd7f.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 03192ba [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Stats Through Kills [stats_through_kills],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi]
]

# Additional context

The truck was completely intact, though, so that was nice...

**Comment by robotic-gamer** [comment]
there is a small chance it could be item overflow out of the crates due to the game trying to spawn more than the max volume for a crate.

**Comment by Inglonias** [comment]
Probably a side-effect of high item spawn rate. We can probably close this one.
