### ISSUE TITLE
Combat messages can be confusing / inaccurate, particularly with scratching

### ISSUE THREAD

**Issue by arockperson** [CleverRaven/Cataclysm-DDA#49709]
# Is your feature request related to a problem? Please describe.
There are a couple messages that I still am not 100% sure on what they are supposed to mean. I THINK I have the hang of them now, but they are way too confusing IMO.

1. "The zombie tries to claw at you, but fails to."
2. "The zombie hits your arm / leg / head." (when it actually hits your hand / foot / eye / mouth)
3. "The zombie hits your torso."

# Describe the solution you'd like
1. "The zombie claws at your (bodypart), but fails to penetrate armor." ("The %1$s claws at your %2$s, but fails to penetrate armor.")

This line in particular bugs me the most. Saying it "fails to" claw at you makes it sound like it misses or you dodge, whereas I'm pretty sure this is the message for when it doesn't deal any damage due to your armor. That is, the zombie actually DOES succeed in clawing at you, but fails to do damage, so the message is inaccurate.

The bodypart would be useful to know as well, since this message has to do with your armor (I think?)

edit: looking in the files, I think this claw message is the only one that's like this.  "The %1$s tries to impale your torso, but fails to penetrate your armor!" for impaling, and "The %1$s bites your %2$s, but fails to penetrate armor!" for biting. It should be consistent with the others. 
2. "The zombie hits your right hand / hits your right foot, etc."

I know there are times where it refers to zombies hitting your hand/foot/eye whatever (with biting I think), but I feel if a zombie hits your hand/foot/eye/whatever, you always want to know. Yeah, they share the same HP pool, but it's very useful for the player to know if it's their hand armor that's getting them killed, or their arm armor.

In short, it should ALWAYS say where you are hit; I don't see any reason to not be specific.

3. "The zombie punches / whacks / whatever it is supposed to be your torso."

This one is a bit more involved, but I think the combat message should reflect the damage type you receive. Just saying you are "hit" could mean almost anything. For example, feral humans could have messages that reflect the weapons they are using. "The feral human bludgeons your torso with their baseball bat" "The feral human chops your torso with their fire axe". The messages could even be as concise as replacing hit with bludgeon or slice or whatever, which would still make things more clear.

# Describe alternatives you've considered
Leave the messages as is, of course.

Also, the combat messages in general are kind of lackluster, so a total rework could be nice, but these are just a few things that have been confusing to me.

**Comment by Zireael07** [comment]
1. is wrong. "it fails to" refers to "penetrate armor", not "clawing"

**Comment by anothersimulacrum** [comment]
> "The zombie tries to claw at you, but fails to."

https://github.com/CleverRaven/Cataclysm-DDA/blob/83bdbb7589b5eb31ff9d3e29c9be5a413a05e894/data/json/monster_special_attacks/monster_attacks.json#L39

**Comment by arockperson** [comment]
I understand that's the intention, but it's very unclear IMO. Look, let's say you claw a brick wall (I won't judge). I wouldn't say you "tried to claw at the wall, but failed to", instead I would say you "clawed at the brick wall, but didn't scratch it", you know?

**Comment by Venera3** [comment]
Giving the ferals their own damage/miss/hit snippets and appropriate damage is simply the question of adding a custom special attacks - a simple JSON change, same as changing the existing messages. The attacks can already print the targeted body part *for attacks that manage to hit*, some are just not set up for that. Both are a good first contribution, for anybody adding labels.

**Comment by anothersimulacrum** [comment]
Should be fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/49715 and https://github.com/CleverRaven/Cataclysm-DDA/pull/49790
