### ISSUE TITLE
cold resistance cream

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#49707]
# Describe the bug

In aftershock the cold resistance cream has a few issues:
- there is no way to take it off
- it seems to be permanent
- it causes wet mood debuff if you go swimming with only it on

# Steps To Reproduce

use the cold resistance cream

# Expected behavior

- able to take off and lose the item
- it not to be permanent
- it to not cause wet mood debuff

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 1f0b625 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Simple_additions [simple_additions],
    C.R.I.T Expansion Mod [crt_expansion],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    Stats Through Skills [StatsThroughSkills],
    Bionic Slots [cbm_slots]
]

**Comment by Maleclypse** [comment]
Needs a duration on the spell.

**Comment by Maleclypse** [comment]
I was wrong.  Everything on the cold resistance cream is correct.   The problem was that the ethereal item was being placed inside the landfall kit so it was effectively debugged in without any duration.  I'm fine with it retaining water and causing a wet mood debuff.
