### ISSUE TITLE
Ninjutsu martial art does incorrect damage due to multiplicative calculation

### ISSUE THREAD

**Issue by ShiftyGuy** [CleverRaven/Cataclysm-DDA#49701]
# Describe the bug

The "Loss of Surprise" effect with Ninjutsu reduces all melee damage by 50%, this is supposed to cancel out the constant buff you have from the Ninjutsu effect "Sneak Attack" (which increases all melee damage by 50%).

**These effects are multiplicative, not additive** . Therefore all damage is being reduced further than intended apart from the initial attack.

How it is supposed to work: - (100 base damage * (1.5-0.5) = 100 damage
How it is working: - ((100 base damage *1.5) *0.5) = 75 damage

# Steps To Reproduce

1. Equip Ninjutsu martial art with a compatible weapon
2. Attack a monster and check your average damage (not including the "Sneak Attack" attacks)
3. Test your average damage without Ninjutsu 
4. Compare numbers, damage is ~75% of the normal damage when using Ninjutsu 

# Expected behavior

Based on the description it seems like the "Loss of Surprise" effect is supposed to just counteract the constant bonus from "Sneak Attack", therefore the damage should be the same, not ~25% less.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Fuji's Military Profession Pack [fuji_mpp]
]

# Proposed Fix

Fix:

Change this segment in martialarts.json to the following:
{
        "id": "buff_ninjutsu_onattack",
        "name": "Loss of Surprise",
        "description": "You intentions are known!  It will take you a few moments to sneak attack again.\n\n-50% all damage.\nLast 3 turns.",
        "unarmed_allowed": true,
        "melee_allowed": true,
        "buff_duration": 3,
        "mult_bonuses": [
          { "stat": "damage", "type": "bash", "scale": 0.67 },
          { "stat": "damage", "type": "cut", "scale": 0.67 },
          { "stat": "damage", "type": "stab", "scale": 0.67 }
        ]
      }

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue

**Comment by ShiftyGuy** [comment]
Tested the fix I posted in my current game and seems to work fine, only issue is that the 0.67 multiplier I posed does not return the damage to exactly 100% (100.5% to be exact)). Maybe just add more significant figures to the number posted to get it closer? Either way i'm happy with "scale": 0.67.

**Comment by Patil2099** [comment]
I would love to work on this issue.

**Comment by himanshu007-creator** [comment]
@Patil2099  thanks for the PR but I had claimed this issue earlier. Nevermind, but next time do consider to read the above messages.
Thanks🎉
