### ISSUE TITLE
Graphical Overmap Causes Map Notes Text To Disappear

### ISSUE THREAD

**Issue by SquareMan** [CleverRaven/Cataclysm-DDA#49708]
# Describe the bug

Enabling the graphical overmap option causes the text of a map note not to appear when hovering over the note. Reading the note requires opening the Notes List with `L`

# Steps To Reproduce

1. Enable Graphical Overmap
2. Create a note anywhere on the map.
3. Hover over that map tile.

# Expected behavior

The text of the note will be displayed in the upper-left corner.

# Screenshots

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.F-461-g83bdbb7589 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

**Comment by actual-nh** [comment]
Thanks; this is a known bug that's being worked on, but good idea to put up an issue for it.

**Comment by KorGgenT** [comment]
Fixed by 
#50190
