### ISSUE TITLE
only one power storage cbm of mk I and II each can be installed

### ISSUE THREAD

**Issue by fluorineacid** [CleverRaven/Cataclysm-DDA#49727]
# Describe the bug

I can only install one of each power storage cbm (mk I and II). it says "CBM is already installed."

# Steps To Reproduce

1. Make a character and acquire 2 power storage cbm, or start with a character that already has it and acquire one.
2. Try to install two of the same power storage cbm.
3. You can't.

# Expected behavior

One should be able to install power storage cbm more than one. I guess this happened after #47777.

# Screenshots

![bug01](https://user-images.githubusercontent.com/1030728/124852335-210af780-dfdf-11eb-898d-4163ba2273f3.png)
![bug02](https://user-images.githubusercontent.com/1030728/124852338-223c2480-dfdf-11eb-99dd-b751b1ef9384.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 1b2fd7b [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

**Comment by actual-nh** [comment]
Ping: @Ramza13?

**Comment by anothersimulacrum** [comment]
This is an easy fix, I'm just trying to track down how to keep coloring them green in the menu, and that's harder:
```diff
diff --git a/src/bionics.cpp b/src/bionics.cpp
index 1187c9cd1b..10de31657d 100644
--- a/src/bionics.cpp
+++ b/src/bionics.cpp
@@ -2340,7 +2340,7 @@ ret_val<bool> Character::is_installable( const item_location &loc, const bool by
         return ret_val<bool>::make_failure( msg );
     } else if( it->has_fault( fault_id( "fault_bionic_salvaged" ) ) ) {
         return ret_val<bool>::make_failure( _( "CBM already deployed.  Please reset to factory state." ) );
-    } else if( has_bionic( bid ) ) {
+    } else if( has_bionic( bid ) && !bid->dupes_allowed ) {
         return ret_val<bool>::make_failure( _( "CBM is already installed." ) );
     } else if( !can_install_cbm_on_bp( get_occupied_bodyparts( bid ) ) ) {
         return ret_val<bool>::make_failure( _( "CBM not compatible with patient's body." ) );
```
