### ISSUE TITLE
Electronics control unit contains unbalanced solder amounts

### ISSUE THREAD

**Issue by pjf** [CleverRaven/Cataclysm-DDA#49725]
# Describe the bug

Electronics control units contain 120 solder, which seems to be a *lot* more than similar electronics (eg: 40 solder for an electric motor).

This means that electronics control units are both extremely expensive to make, but also provide oversized solder bounties when disassembled.

# Steps To Reproduce

1. Spawn an electronics control unit
2. Examine the unit to see 120 solder on disassembly.

# Expected behavior

Electronics control units have similar solder costs to other items.

I'm happy to do a PR for this (down to say 40 solder?), but wanted to check if we actually intend for electronics control units to be so solderful first.

# Versions and configuration

- dc17463eaf4e915696884c36a87cd372789d0778

**Comment by Night-Pryanik** [comment]
I'm not sure where did I take that 120 solder requirement when I was adding ECU, but I think it's pretty safe to reduce the amount if it seems like too much.
