### ISSUE TITLE
Add sheet metal walls

### ISSUE THREAD

**Issue by Igryn** [CleverRaven/Cataclysm-DDA#49735]
# Is your feature request related to a problem? Please describe.
Add walls made out of thin sheets of coregated and/or flat sheets of metal secured on a carcass 

![61YHoNqkfiL _AC_SL1000_](https://user-images.githubusercontent.com/51831130/124899132-7e577680-dfe8-11eb-8870-6fa7cd125241.jpg)

# A clear and concise description of what the problem is. 
Currently metal walls in mapgen are super this and strong solid, which is not suitable for an simple structures like sheds and garages you encounter in game, like at apple orchards. 

# Describe the solution you'd like
Add thin metal walls and include them in mapgen where suitable

# Describe alternatives you've considered
Replace such overkill metal walls with wood or drywall

# Additional context
Crashed plains and boats especially grind my gears in that regards as they are supposed to be at least somewhat light
Aluminum panel walls for pasenger plains crashes would also be nice

**Comment by TealcOneill** [comment]
This has been finished already.
