### ISSUE TITLE
Bird food crafting should not transform random seeds into superfood (NUTRIENT_OVERRIDE)

### ISSUE THREAD

**Issue by RenechCDDA** [CleverRaven/Cataclysm-DDA#49748]
# Describe the bug
Bird food applies NUTRIENT_OVERRIDE, which means that whatever ingredients you put into the crafting recipe the same nutrition pops out. Crafting 1 "foo seeds" into 1 bird food increases calorific value by 10-20x. 

Also it has 5 enjoyability. I've eaten sunflower seeds and let me tell you, slapping a "bird food" label on them would not make them better than sugared donut holes (4 enjoyability).

# Steps To Reproduce
-Grab some random seeds from somewhere, around 20-30 calories
-Craft bird food
-Look at bird food. 400 calories. Wow!

# Expected behavior
I am still eating the same seeds

# Screenshots

# Versions and configuration
335ab2a

# Additional context
NUTRIENT_OVERRIDE is apparently required to pass some of the automated tests (c309868591c960561e6870abe8b65a221c6f8807). Which for some reason check eating using bird food? I am not familiar with the automated testing schema and that's why I'm posting it as an issue instead of a simple PR.

If the automated test issue can be resolved or worked around, then simply removing NUTRIENT_OVERRIDE should allow existing bird food spawns (e.g. in zoos/farms) to retain their expected calorie density and 'value' while not causing undue changes in the ability to craft bird food for taming.

(Sorry, Reddit!)

**Comment by actual-nh** [comment]
Actually, NUTRIENT_OVERRIDE is why the tests didn't pick this up IIRC - they would otherwise complain about the massive caloric difference.

**Comment by RenechCDDA** [comment]
Oh this is embarrassing. Apparently I should have looked for the tests, they were neither difficult to find nor was the related one difficult to understand. I actually did not know that bird food was normally inedible by characters!

It stands to reason then that in terms of faction camps, they simply shouldn't be allowed as a food source. That is something I might be able to change, will have to look into it. 

That is my understanding of the test starting in line 196 of char_edible_rating_test.cpp. Is there a separate test that may cause problems if the recipe itself is adjusted, such as by removing the NUTRIENT_OVERRIDE flag?

**Comment by actual-nh** [comment]
NUTRIENT_OVERRIDE appears to be required because most of the possible seed components have 0 calories. That doesn't mean that the components of the recipe don't need adjusting - the average unit of seeds is 1 gram (or less?) in weight, and it's getting transformed into 60 g of birdfood, unless I'm misinterpreting the recipes completely.
