### ISSUE TITLE
Feature request: Morale bonus from pets

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#49756]
In real life, pets are beneficial to mental health and overall mood. Who doesn't like petting a cat/dog/horse/whatever?

I propose adding a minor morale bonus when around pets or friendly domestic animals. There should be also actions to interact with it, like petting it.
I also found [this post](https://www.reddit.com/r/cataclysmdda/comments/nvk378/pocket_rat/) on the r/CataclysmDDA subreddit.

There are potential edge cases here though. Some people do not like dogs and prefer cats, some may even have an allergy to them. So being near them could even, in the worst case, trigger an asthma attack. This could be realized using traits perhaps.

Some people may also be scared of dogs, so it could be a morale penalty. This could be applied in a very broad sense though. Fighting spiders or cockroaches is certainly not for everyone for example, but this should be a separate thing and is not very relevant here. Although mutations making you less human could maybe make you like bugs and other things most humans do not find cute.

If the domestic animal is a baby, the morale boost should be even bigger. Having a [teeny kitten around you](https://commons.wikimedia.org/wiki/File:1-month-old_kittens_20.jpg) is bound to lighten up your mood. Right? Right??

I actually wanted to open a discussion instead of an issue but it seems like discussions are for collaborators only :/
This is more of an idea so it would be more appropriate to just post a discussion in the idea category there.

**Comment by anothersimulacrum** [comment]
![image](https://user-images.githubusercontent.com/42699974/125006284-97751d00-e012-11eb-852e-d6cb9298677b.png)
![image](https://user-images.githubusercontent.com/42699974/125006292-9e039480-e012-11eb-91c3-d9af916ce18d.png)

**Comment by Saicchi** [comment]
This issue is asking for two things: Playing with pets which is already a feature in game, and a **morale bonus for being near pets**.

**Comment by Maleclypse** [comment]
So if you’re out walking with your pet you have a continuous bonus?  I think this would need to be offset with a significant morale debuff if the pet dies in your sight. Which unfortunately would make someone who raises packs of dogs to fight zombies on his behalf not a valid play style.  Not sure it is currently but we can’t differentiate between friendly animals that are pets and animals that are tools currently.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
