### ISSUE TITLE
Shotgun Arm doesn't produce a hull when fired.

### ISSUE THREAD

**Issue by Orange01gaming** [CleverRaven/Cataclysm-DDA#49767]
# Describe the bug

<Shotgun Arm doesn't produce a hull when fired.>

# Steps To Reproduce

< Steps to reproduce the behavior:
1. Install shotgun arm, and power CBMs
2. Turn on shotgun arm cbm
3. Load 
4 with shotgun shell.
5. Fire
6. No hull produced. >

# Expected behavior

< Hull to be produced like when gun is fired >

# Versions and configuration

< - OS: Windows
    - OS Version: 10.0 2009
- Game Version: 5f90cfb [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Slots [cbm_slots]
]
>

**Comment by Maleclypse** [comment]
I will try to test later but I thought the hull stayed in the arm like a single barrel shotgun until you go to reload.

**Comment by natsirt721** [comment]
Can confirm, the `bio_shotgun`'s associated item `bio_shotgun_gun` has the `RELOAD_EJECT` flag. Assuming everything is working as intended with that flag, then the observed behavior appears to be expected.

**Comment by Orange01gaming** [comment]
Oh I see it now after reloading, or using U to unload it.
