### ISSUE TITLE
Outline for Increasing Difficulty Over Time - Dynamic systems and a progessively more dangerous world

### ISSUE THREAD

**Issue by GlyphGryph** [CleverRaven/Cataclysm-DDA#4977]
**Zombie Replacement/Advancement**
Right now, all special zombies that spawn on the map spawn at the start of the game. The game should have all zombies spawn as regular zombies and, over time, we would like these zombies to be replaced by special zombies in larger numbers, until a certain density of special types is reached, depending on conditions.

I'd recommend a system to "mark" zombies upon being spawned with a time and type to change to, and if they are encountered after that time they get replaced.

**Conditional Zombie Replacement and Zone Zombie Replacement**
We could also add additional zombie types later in the game, such as those mentioned here: http://smf.cataclysmdda.com/index.php?topic=4077.0
These monsters should only spawn under certain limited conditions. Which zombies and the frequency they appear should be tied to specific cities and area of cities, rather than the generalized building system we have now. So you may run across a city that has made a LOT of spitter zombies, or one that's just crawling in Brutes. The zombies in the thread above should only appear in specific "zones" (but in high numbers in those zones), and only after a certain amount of time has passed.

**Zombie Mobs** 
Here's the big one - we want "mobs" to form, a sort of overmap group (a visible one, like the old NPCs) that moves around on the overmap "picking up" and "dropping off" zombies as it goes, moving a few squares a day. Whenever one of those "mobs" moves into a players range (or the player moves into the mobs range) it should spawn the entirety of the zombie contents. When the zombies de-spawn they are added back to the Mob, which doesn't move until the player has left it's range or the last monster has died (at which point it is destroyed)

**Zombie Immune Response**
When a player kills many zombies in an area, this will trigger an "immune response" in the Netherum colony. Zombie mobs may spawn from off map, already containing many zombies, and should be programmed to move to the place where the zombie massacre occured (before resuming normal roaming behaviour). This response can only be triggered every so often, and there should be a delay before the mob appears (where it is assumed the forces are gathering off-map and coming from very far away).

**Faction Expansion**
Monstrous Factions (Triffid Colonies, Fungal Blooms, Ant Colonies, Beehives) should be able to grow over time, and 'take over' nearby areas. There should also be a way to prune them back, if such a way doesn't exist.

**Faction Multiplication**
Monstrous factions should be able to form "Mobs" that are given a location on the map and work their way towards it at which point they create a new source for that faction. Some of these mobs should be single creatures, while others may be more than that.
See http://smf.cataclysmdda.com/index.php?topic=2113.msg26507#msg26507 for details about factions and the means they'd use for multiplication. Triffids use "seed bearers" that create new Hearts, the Mycus uses infected organisms of various types, while Bee and Ant colonies will create "swarms" to start new faction areas. There should be one or more "special monsters" in each of these mobs. If killed, the Mob is disbanded, does not finish going to it's location, and it's members should soon die off.

**Comment by kevingranade** [comment]
Several major parts of this are implemented or in progress.  I'm closing it for now as an omnibus issue, feel free to resurrect individual pieces of it as separate issues.
