### ISSUE TITLE
Gasoline Fuel Cell CBM no longer working

### ISSUE THREAD

**Issue by AdamChirnside** [CleverRaven/Cataclysm-DDA#49789]
# Describe the bug

After updating, an already-installed Gasoline Fuel Cell CBM seems to no longer take new fuel. I am unable to 'E'at gasoline to fill up the fuel storage.

# Steps To Reproduce

1. Create character with Gasoline Fuel Cell CBM installed
2. Have less than maximum gasoline fuel stored
3. Try to 'E'at gasoline

# Expected behavior

As was previously possible: able to consume Gasoline to refuel the CBM

# Screenshots

![](https://cdn.discordapp.com/attachments/642349261320880128/863190089470050314/unknown.png)

![](https://cdn.discordapp.com/attachments/642349261320880128/863190175005147136/unknown.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: ef8144d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Disable NPC Needs [no_npc_food],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Alternative Map Key [alt_map_key],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    No Rail Stations [No_Rail_Stations]
]

# Additional context

N/A

**Comment by GoLoT** [comment]
Related to #48750?

I haven't tried it yet but it looks like a new menu was added exclusively for refueling.

**Comment by actual-nh** [comment]
Perhaps feedback of "use the X menu to refuel your CBM"?

**Comment by ZhilkinSerg** [comment]
Do not eat gasoline - use refuel menu from bionics menu.

**Comment by actual-nh** [comment]
I suggest that there is a bug - inadequate feedback (about a change in the game). @AdamChirnside, could you correct the issue (including the title) accordingly?

**Comment by ZhilkinSerg** [comment]
We can probably call refuel menu when consume function is called if some bionic can be refueled with item to be consumed.

**Comment by Robik81** [comment]
On related issue, Battery System is bugged too.

- can't eat batteries in Eat menu (batteries are grayed out)
- can't Refuel in Bionics menu ("You have no fuel to consume", despite having several batteries in the inventory)
- can't switch CMB from OFF to ON state (is it necessary? it writes "Your Battery system does not have enough fuel to start." to the console anyway)

Alternatively I have no idea how this CBM works, which is possible, first time any of my characters got it (Bionic Game Master start).

**Comment by GoLoT** [comment]
> * can't switch CMB from OFF to ON state (is it necessary? it writes "Your Battery system does not have enough fuel to start." to the console anyway)
> 
> Alternatively I have no idea how this CBM works, which is possible, first time any of my characters got it (Bionic Game Master start).

It works by draining the stored fuel (battery power) and turning it into bionic power. If you don't have any battery power stored it can't be activated. So the issue here is that there is no way to refuel that specific CBM through any of the menus, I guess.

**Comment by actual-nh** [comment]
> > Alternatively I have no idea how this CBM works, which is possible, first time any of my characters got it (Bionic Game Master start).
> 
> It works by draining the stored fuel (battery power) and turning it into bionic power. If you don't have any battery power stored it can't be activated. So the issue here is that there is no way to refuel that specific CBM through any of the menus, I guess.

If so, I suggest opening up a new issue for this part.
