### ISSUE TITLE
Recipe Dictionary CTD

### ISSUE THREAD

**Issue by AdamChirnside** [CleverRaven/Cataclysm-DDA#49793]
# Describe the bug

When trying to open the interact menu (default keybind '%'), game crashes

# Steps To Reproduce

1. Load provided save
2. Press %

# Expected behavior

Context menu for various inventory item interactions

# Screenshots

N/A

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: ef8144d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Disable NPC Needs [no_npc_food],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Alternative Map Key [alt_map_key],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    No Rail Stations [No_Rail_Stations]
]

# Additional context

 DEBUG    : invalid recipe id ""

 FUNCTION : const T& string_id<T>::obj() const [with T = recipe]
 FILE     : src/recipe_dictionary.cpp
 LINE     : 65
 VERSION  : ef8144d

[My savefile](https://www.dropbox.com/s/jqjpkdmv6srv7ns/Olex.7z?dl=0)

**Comment by GoLoT** [comment]
I can't test the savegame. Windows Defender is throwing a false positive and removing the file:

![image](https://user-images.githubusercontent.com/1606943/125148300-91299280-e131-11eb-83c1-c326cedfa6fe.png)

Does it happen only on that specific save?

**Comment by ZhilkinSerg** [comment]
This is caused by one of installed bionics:

```
{
			"id": "bio_carbon",
			"invlet": 97,
			"powered": false,
			"charge": 0,
			"ammo_loaded": "null",
			"ammo_count": 0,
			"bionic_tags": [],
			"safe_fuel_threshold": 1.000000
		}, {
			"id": "bio_targeting",
			"invlet": 98,
			"powered": false,
			"charge": 0,
			"ammo_loaded": "null",
			"ammo_count": 0,
			"bionic_tags": [],
			"safe_fuel_threshold": 1.000000
		}, {
			"id": "bio_climate",
			"invlet": 99,
			"powered": false,
			"charge": 1,
			"ammo_loaded": "null",
			"ammo_count": 0,
			"bionic_tags": [],
			"safe_fuel_threshold": 1.000000
		}, {
			"id": "bio_ups",
			"invlet": 100,
			"powered": false,
			"charge": 0,
			"ammo_loaded": "null",
			"ammo_count": 0,
			"bionic_tags": [],
			"safe_fuel_threshold": 1.000000
		}, {
			"id": "bio_eye_optic",
			"invlet": 101,
			"powered": false,
			"charge": 0,
			"ammo_loaded": "null",
			"ammo_count": 0,
			"bionic_tags": [],
			"safe_fuel_threshold": 1.000000
		}, {
			"id": "bio_uncanny_dodge",
			"invlet": 103,
			"powered": false,
			"charge": 1,
			"ammo_loaded": "null",
			"ammo_count": 0,
			"bionic_tags": [],
			"safe_fuel_threshold": 1.000000
		}, {
			"id": "bio_night_vision",
			"invlet": 104,
			"powered": false,
			"charge": 1,
			"ammo_loaded": "null",
			"ammo_count": 0,
			"bionic_tags": [],
			"safe_fuel_threshold": 1.000000
		}, {
			"id": "bio_fuel_cell_gasoline",
			"invlet": 105,
			"powered": false,
			"charge": 1,
			"ammo_loaded": "null",
			"ammo_count": 0,
			"bionic_tags": [],
			"auto_start_threshold": 0.750000,
			"safe_fuel_threshold": 1.000000
		}, {
			"id": "bio_weight",
			"invlet": 102,
			"powered": false,
			"charge": 0,
			"ammo_loaded": "null",
			"ammo_count": 0,
			"bionic_tags": [],
			"safe_fuel_threshold": 1.000000
		}, {
			"id": "bio_blood_filter",
			"invlet": 106,
			"powered": false,
			"charge": 0,
			"ammo_loaded": "null",
			"ammo_count": 0,
			"bionic_tags": [],
			"safe_fuel_threshold": 1.000000
		}, {
			"id": "bio_memory",
			"invlet": 107,
			"powered": true,
			"charge": 1,
			"ammo_loaded": "null",
			"ammo_count": 0,
			"bionic_tags": [],
			"safe_fuel_threshold": 1.000000
		}, {
			"id": "bio_str_enhancer",
			"invlet": 108,
			"powered": false,
			"charge": 0,
			"ammo_loaded": "null",
			"ammo_count": 0,
			"bionic_tags": [],
			"safe_fuel_threshold": 1.000000
		}, {
			"id": "bio_purifier",
			"invlet": 109,
			"powered": false,
			"charge": 0,
			"ammo_loaded": "null",
			"ammo_count": 0,
			"bionic_tags": [],
			"safe_fuel_threshold": 1.000000
		}
```

**Comment by GoLoT** [comment]
Adding to the analysis:

Bionics are being assigned a default fake item with empty id. When creating a list of fake items it loops through all bionics and tries to find the matching fake item by id. Since "" (empty) is not a valid itemid it fails.

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/character.cpp#L2269

**Comment by actual-nh** [comment]
Ping: @Ramza13?

**Comment by GoLoT** [comment]
Changed:

```
std::vector<item> Character::get_pseudo_items() const
{
    std::vector<item> result;
    for( const bionic &bio : *my_bionics ) {
        const bionic_data &bid = bio.info();
        if( bid.fake_item && !bid.fake_item.str().empty() && ( !bid.activated || bio.powered ) ) {
            result.emplace_back( item( bid.fake_item ) );
        }
    }
    return result;
}
```

![image](https://user-images.githubusercontent.com/1606943/125149032-c08ece00-e136-11eb-93ae-f3564650c8e5.png)

I'll leave you to decide the best approach. I think making it an optional should be cleaner.

**Comment by ZhilkinSerg** [comment]
Yeah, the approach is fine plus we should make `fake_item` field `cata:optional` instead of a `string`.
