### ISSUE TITLE
Compile error: "functions that differ only in their return type cannot be overloaded"

### ISSUE THREAD

**Issue by pjf** [CleverRaven/Cataclysm-DDA#49803]
### Describe the bug

When compiling with clang 10 under Ubuntu 20.04:

```
src/panels.cpp:1015:29: error: functions that differ only in their return type cannot be overloaded
std::string activity_level::activity_level_str( float level )
~~~~~~~~~~~                 ^
src/panels.h:21:19: note: previous declaration is here
const std::string activity_level_str( float level );
      ~~~~~~~~~~~ ^
```

### Steps To Reproduce

1. `git checkout 25cf01e5a50470a2ac2a1b4a20e4582077476b2c` (current `origin/master`)
2. `make -j8 RELEASE=1 TILES=1 CLANG=1 ASTYLE=0 USE_HOME_DIR=1 SOUND=1 LINTJSON=0 NOOPT=0 RUNTESTS=0`
3. :boom: 

### Expected behavior

Compiles with clang 10

### Versions and configuration

- Ubuntu 20.04
- Clang 10
- 25cf01e5a50470a2ac2a1b4a20e4582077476b2c

### Additional context

Reverting #49026 resolves this error, and causes the game to compile normally.

Also I'm using the new bug report form and it's great!

**Comment by actual-nh** [comment]
A check of the CI for #49026 confirms the bug.
