### ISSUE TITLE
zombie necro-boomer revives itself

### ISSUE THREAD

**Issue by GadekMaciej** [CleverRaven/Cataclysm-DDA#49816]
# bug
zombie necro-boomer seems to revive itself over and over, no matter how many times i kill it. They are literally invincible. I don't know if its all of them, I just met 1 so far inside cathedral basement.

# Steps To Reproduce

1. find/spawn necro-boomer
2. kill him
3. watch him happily come back to life everytime

# Expected behavior

I expected necro boomer to die, revive other creatures/zombies and stay dead. I don't know how this would work with a 2 necro-boomers, because I can't tell if they should revive "themselves" when one of them dies in range of other dead body.

![cdda_bug_necroboomer](https://user-images.githubusercontent.com/64140639/125167469-05e7e580-e1a1-11eb-97bc-09545bbbae77.png)

# Versions and configuration
running on build : 2021-07-09-2342 

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: c1159c2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by Broken27** [comment]
@KorGgenT you probably want to take a look at this one, it's almost certainly caused by #49439

**Comment by pjf** [comment]
Just arrived to report this as well. At first I thought the necro-boomer was completing its cast on the same tick as it died and this was somehow a race condition, but no... I've killed it plenty and it keeps reviving itself.
