### ISSUE TITLE
hidden unexplained crafting menu

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#49829]
### Describe the bug

There is a menu in crafting I got to. I don't know what it's for and I don't know how was I supposed to know how to get there.

### Steps To Reproduce

To get to the menu:
1. Probably regular character that played a bit and has some materials for fabrication recipes.
2. Open crafting menu.
3. Search "p:fab" (search for recipes using fabrication as primary skill).
4. Press the left arrow twice.

### Expected behavior

Explanation on what the menu is once I get there. How are the crafting recipes sorted?

Explanation on how to get to that menu e.g. "folders"/"cards" that are at the top that switch by pressing tab or arrows like everywhere else.

### Screenshots

![Screenshot_2](https://user-images.githubusercontent.com/13402666/125178089-b675d980-e1e1-11eb-864a-8106f5cf46af.png)

### Versions and configuration

- OS: Windows 10
- Game Version: 19c4b2f
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: dda, no_npc_food, package_bionic_proffessions

**Comment by ToxiClay** [comment]
Can you upload your save? I can't reproduce your issue.

Searching `p:fab` pulls up a list of all recipes I have the components to make, sorted by required skill level, descending.

Pushing left once changes the sorting in a way I can't currently discern.

Pushing left again, though, brings me back to the original sort method, so pushing the button twice does not bring me to something I don't understand.

**Comment by ZhilkinSerg** [comment]
Left and Right arrows cycle through sub-tabs in selected crafting tab. When displaying Searched tab there are no sub-tabs, so this action should just be disabled.

**Comment by Brambor** [comment]
[Middle Earth.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6796652/Middle.Earth.zip) that's my save. I hope it contains Legolas, I have no time right now :(
