### ISSUE TITLE
Add option to reopen to/remember last crafting menu page

### ISSUE THREAD

**Issue by justn6** [CleverRaven/Cataclysm-DDA#49839]
# Is your feature request related to a problem? Please describe.
No issue, only a request

# Describe the solution you'd like
Entering the crafting menu with & / Shift+7 always brings you to the [*] tab on the favorites page.
Would be nice to have a toggle in options that enables the menu to remember which tab/page you where on last.

**Example:**
- Enter crafting menu
- Go to weapons tab, then other page
- Hit escape to exit crafting menu because you are missing a material
- Find material
- Go back into crafting menu
- Menu should still be on same tab/page you previously browsed to

# Describe alternatives you've considered
The favorites and recent are good alternatives already in the game for quickly getting back to a certain recipe, but this would be a big QoL

# Additional context
N/A

**Comment by ZhilkinSerg** [comment]
There is already recraft last recipe command.

**Comment by justn6** [comment]
If you dont have light, or are missing something, the recraft command does not help you get back to the last menu

**Comment by leemuar** [comment]
Generally I think it's a nice feature to have. There is nothing wrong in opening last viewed page and recipe

**Comment by leemuar** [comment]
@dseguin contributed the code in pull/52685, we can use it to implement this feature

**Comment by leemuar** [comment]
After implementing the most basic approach - "always open the last crafted recipe" - I've started doubting. This behaviour might be undesirable for people who want Favorite tab to always open first (current behaviour).

One way to solve it might be to add a new option menu to toggle it on and off. But honestly this task is too complicated for my current programming skills.

But then I've looked to "Recent" tab mentioned in alternatives section. Looks like it does exactly that: the first recipe in the list is the last one crafted. So in current built it is enough to press "&" and "arrow right" to get the desired result. In just 2 buttons. @justn6, do you really want it to be just 1 button?
