### ISSUE TITLE
Killing things doesn't count as killing, but violence counts as violence.

### ISSUE THREAD

**Issue by somepersondunno** [CleverRaven/Cataclysm-DDA#49837]
### Describe the bug

You can kill something, but your kill count won't increase, and you won't get the associated conducts/achievements. Note that I fail Non-Violence but I don't get any achievements.

### Steps To Reproduce

1. Find a monster/creature.
2. Kill it.
3. Have your violence acknowledged but fail to be acknowledged for _killing_ the monster.

### Expected behavior

I expected to be rewarded for my violence.

### Screenshots

![log](https://user-images.githubusercontent.com/70115628/125180916-819f5d80-e1b4-11eb-8306-131af6ef2e35.PNG)
![log2](https://user-images.githubusercontent.com/70115628/125180923-89f79880-e1b4-11eb-8c20-77b77ea093c9.PNG)
![log3](https://user-images.githubusercontent.com/70115628/125180936-b3b0bf80-e1b4-11eb-9190-ad1a6925f96b.PNG)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: aa126fe [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi]
]

**Comment by justn6** [comment]
I tried stats through kills for the first time and though the mod broke this feature, but after disabling all mods and retrying with vanilla settings I also reproduced it.

**Comment by UNOwenWasMe** [comment]
I'm no programmer, but I might have a hunch:
Recently, I think 2-3 days ago or so, there was a change in the death function of monsters, and all mods had to update because of it too. It might have something to do with the fact that the change in that function doesn't properly call the one that registers the kill?

**Comment by anothersimulacrum** [comment]
The kill event is still sent.

**Comment by anothersimulacrum** [comment]
Removing this causes it to work - because the `set_killer` above 
https://github.com/CleverRaven/Cataclysm-DDA/blob/159413daa279694aeaf7885edde67f496d61d473/src/monster.cpp#L2348

**Comment by anothersimulacrum** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/159413daa279694aeaf7885edde67f496d61d473/src/creature.cpp#L2440-L2445

`nullptr` should not be the argument here.
