### ISSUE TITLE
Stealing from "no faction"

### ISSUE THREAD

**Issue by logros13** [CleverRaven/Cataclysm-DDA#49840]
### Describe the bug

When trying to retrieve my equipment from a dead ex-follower who ran away after suddenly no longer being in my faction (https://github.com/CleverRaven/Cataclysm-DDA/issues/36386#issuecomment-877738130) i got a warning that doing so would be stealing from "no faction".

### Steps To Reproduce

1. try to loot a dead "no faction" faction npc (possibly only those created by the above bug?).

### Expected behavior

Picking up items from dead factionless npcs should not be considered stealing.

### Versions and configuration

- OS: Windows 10
- Game Version: aa126fe [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    No Rail Stations [No_Rail_Stations],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex]
]

**Comment by hexagonrecursion** [comment]
@wapcaplet Thank you for processing all the issues I tried to reproduce. I am glad to see my work paying off.
