### ISSUE TITLE
Uncraft recipes inherit new vacuum mold tool requirements

### ISSUE THREAD

**Issue by GoLoT** [CleverRaven/Cataclysm-DDA#49841]
### Describe the bug

When trying to disassemble items with recipes that use the new vacuum mold, the requirement is inherited by the uncraft recipe and prevents you from disassembling the item unless you have a charged mold nearby.

### Steps To Reproduce

1. Get a car battery.
2. Try to disassemble the battery without a vacuum mold nearby.
3. See how the game prevents disassembling the battery.

### Expected behavior

Disassembling shouldn't require molds since you are just taking stuff apart.

### Screenshots

![image](https://user-images.githubusercontent.com/1606943/125185991-155e4180-e228-11eb-8547-acb6261e1e15.png)
![image](https://user-images.githubusercontent.com/1606943/125185997-23ac5d80-e228-11eb-8067-89ac9613de1b.png)

### Versions and configuration

- OS: Windows 10
- Game Version: c1159c2
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: DDA, Disable NPC needs

**Comment by Maleclypse** [comment]
Also shouldn’t yield polycarbonate sheets.

**Comment by actual-nh** [comment]
As a more general solution, perhaps a list of "unless overridden, these tools are only needed for crafting, not uncrafting" - precision tools would be other cases. Possibly ditto for yield, provided there is a scrap item to substitute?

**Comment by RenechCDDA** [comment]
Resolved nowadays by setting a specific uncraft recipe. The items listed here (car battery and the since-renamed retractable telescope) have done this.

If you encounter more items with this issue, please open a new issue.
