### ISSUE TITLE
Unable to complete "Visit the Isherwood's"

### ISSUE THREAD

**Issue by Starshard0** [CleverRaven/Cataclysm-DDA#49869]
### Describe the bug

I took the mission from Mr. Lapin, but the mission will not complete, even when standing directly on the map tile the mission points to. This may be related to taking his other mission at the same time.

### Steps To Reproduce

1. Accept the "Visit the Isherwood's" mission from Mr. Lapin
2. Accept the "Timber!" mission from Mr. Lapin.
2. Travel to the Isherwood farm
3. Nothing happens

### Expected behavior

I expected that the mission would complete itself, much like finding the refugee center.

### Screenshots

![image](https://user-images.githubusercontent.com/87286227/125214481-05bd1800-e27d-11eb-9e1b-1d80ef4f95d2.png)

### Versions and configuration

- OS: Windows 10
- Game Version: bc28291
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: dda, no_npc_food, package_bionic_professions

**Comment by Starshard0** [comment]
I'm not familiar with the debug menu, but would it be possible to use it to complete this mission so I can finish the other? I would like to avoid side effects if at all possible.

**Comment by hexagonrecursion** [comment]
Fixed by #50494

**Comment by actual-nh** [comment]
Please update.
