### ISSUE TITLE
 found 3 bugs in the Mobile version of the game

### ISSUE THREAD

**Issue by SoggyLemon** [CleverRaven/Cataclysm-DDA#49862]
### Describe the bug

These bugs were all found in the experimental mobile version of the game, 1: The virtual keyboard for mobile doesnt pop up, 2: Players sometimes become naked when they get hit, and 3rd, the whole square around a character become dark as if they in a very dark area even though there in a lit area.

### Steps To Reproduce

Happens randomly

### Expected behavior

.

### Screenshots

Idk how to send screenshots in github since im on mobile but i can email it to you if u want.

### Versions and configuration

- OS: Fire os, amazon tablet
- Game Version: bc28921
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: None

### Additional context

No mods were added, all this was in vanilla gameplay

**Comment by actual-nh** [comment]
Could you fill in the Version/Configuration information, particularly OS version and game version?

**Comment by SoggyLemon** [comment]
Ok

**Comment by SoggyLemon** [comment]
.

**Comment by SoggyLemon** [comment]
Mm idk how but the problems resolved themselves however, the person turns naked when hit is still there, although this is only a visual bug so its not that bad, so imma just close this thread, hope the devs continue making this game better (:
