### ISSUE TITLE
wasp larva butchering

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#49867]
### Describe the bug

wasp larva is giving human body parts when butchered

### Steps To Reproduce

butcher a wasp larva

### Expected behavior

wasp larva to give insect body parts

### Screenshots

![image](https://user-images.githubusercontent.com/78816055/125213929-6f8bf080-e282-11eb-977b-abb4e1055967.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 1f0b625 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Simple_additions [simple_additions],
    C.R.I.T Expansion Mod [crt_expansion],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    Stats Through Skills [StatsThroughSkills],
    Bionic Slots [cbm_slots]
]

**Comment by casswedson** [comment]
Fixed by #49878
