### ISSUE TITLE
Smashing a downstair generates a floor instead of a void.

### ISSUE THREAD

**Issue by Broken27** [CleverRaven/Cataclysm-DDA#49870]
### Describe the bug

If you smash the upper portion of an staircase, it will leave behind a solid floor instead of an empty space.

### Steps To Reproduce

1: Smash any wooden staircase upper part

2: Confirm it magically leaves a solid floor behind 

### Expected behavior

if you break the steps of an staircase that doesn't magically seal off the space.

### Screenshots

![Screenshot - 12_07_2021 , 03_39_05](https://user-images.githubusercontent.com/67008253/125218460-57889100-e2c3-11eb-9e28-6623562cbbeb.jpg)
![Screenshot - 12_07_2021 , 03_38_05](https://user-images.githubusercontent.com/67008253/125218471-5b1c1800-e2c3-11eb-9b94-8c15d788d262.jpg)

### Versions and configuration

- OS: Windows 10
- Game Version: [0.E-6b9918a] (A couple weeks older than 0.F)
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: None

### Additional context

I wanted to see if you could smash a downstair to generate an empty space where i could drop a ladder (For cases when zombies smash the upstairs below).

**Comment by UmbralReaper** [comment]
I managed to reproduce this in `0.F`
