### ISSUE TITLE
cataclysm-tiles "lags" when run natively under Wayland

### ISSUE THREAD

**Issue by MalteT** [CleverRaven/Cataclysm-DDA#49886]
### Describe the bug

When the game is run natively under Wayland, it looks like some kind of lag is happening. The window content is updated only after another keypress/resize/etc event happened.

(Might just be a bug in SDL)

### Steps To Reproduce

1. Run the game under wayland, not XWayland. (I used `SDL_VIDEODRIVER=wayland cataclysm-tiles`)
2. Press the right arrow key in the main menu
3. Press the left arrow key in the main menu and observe the selection moving to the right

### Expected behavior

Direct input feedback, the window updates according to the given input as it does under X11.

### Screenshots

(Tried to take a screenshot of the off-center main menu after a window resize, but didn't manage to do it. The screenshot always looks correct)

### Versions and configuration

- OS: nixos-unstable, sway 1.6
- Game Version: 0.F
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: []

**Comment by ZhilkinSerg** [comment]
Try compiling it with a different version of SDL. We observed perfomance regressions on more recent SDL versions on Windows. Could be true for Linux too.

**Comment by MalteT** [comment]
I'll try that! In the meantime, I found this SDL issue which sounds related: https://github.com/libsdl-org/SDL/issues/4326

**Comment by MalteT** [comment]
Oh and I should probably clarify: I'm almost certain, that this is not a performance issue. The window is updated on every input event. It's just, that it looks like the game is always one input event behind. But this problem is independent from timings.

**Comment by MalteT** [comment]
Compiled the master-branch, same problem. [nixpkgs uses the latest SDL2 version](https://github.com/NixOS/nixpkgs/blob/586a9e6bffb1b4e0e444bf4013169d8f415f2987/pkgs/development/libraries/SDL2/default.nix#L28). What other version should I try?

If someone could confirm that they are running the game natively on Wayland (not XWayland), I could start looking into other directions. I'm also willing to add further proof/descriptions in other forms, but I'll try to describe the situation with some pseudocode:

```
fn loop() {
  wait_for_event();
  switch_buffer();
  handle_event_and_update_second_buffer();
}
```

While it should be more like:

```
fn loop() {
  wait_for_event();
  handle_event_and_update_second_buffer();
  switch_buffer();
}
```

This might as well be caused by Sway/wlroots or someone else in the pipeline, but it feels like someone is updating to lazily.

Hope that helps. If there's additional info/help I can deliver, ask away!

**Comment by Faalagorn** [comment]
> Compiled the master-branch, same problem. [nixpkgs uses the latest SDL2 version](https://github.com/NixOS/nixpkgs/blob/586a9e6bffb1b4e0e444bf4013169d8f415f2987/pkgs/development/libraries/SDL2/default.nix#L28). What other version should I try?
> 
> If someone could confirm that they are running the game natively on Wayland (not XWayland)

Just to add, this can be relatively easily checked by running xorg-xeyes. If the eyes are moving when the mouse is over the game window, it's running on XWayland, if not, it's native Wayland one.

**Comment by Adriankhl** [comment]
I also encountered this problem. (SDL version: 2.0.14-1.8)

`SDL_VIDEODRIVER=wayland cataclysm-tiles` behaves weirdly with "lag".


`SDL_VIDEODRIVER=x11 cataclysm-tiles` works.

**Comment by andrei8l** [comment]
```diff
diff --git a/src/sdltiles.cpp b/src/sdltiles.cpp
index d7a68d65d0..eef7bef83e 100644
--- a/src/sdltiles.cpp
+++ b/src/sdltiles.cpp
@@ -545,11 +545,11 @@ void refresh_display()
     // Select default target (the window), copy rendered buffer
     // there, present it, select the buffer as target again.
     SetRenderTarget( renderer, nullptr );
+    RenderClear( renderer );
 #if defined(__ANDROID__)
     SDL_Rect dstrect = get_android_render_rect( TERMINAL_WIDTH * fontwidth,
                        TERMINAL_HEIGHT * fontheight );
     SetRenderDrawColor( renderer, 0, 0, 0, 255 );
-    RenderClear( renderer );
     RenderCopy( renderer, display_buffer, NULL, &dstrect );
 #else
     RenderCopy( renderer, display_buffer, nullptr, nullptr );
```

**Comment by MalteT** [comment]
@andrei8l's solution works almost perfectly. It's still missing a redraw on resize, at least with my setup (Sway). But the above patch makes the game playable on native wayland.

@andrei8l are you planning on submitting a PR? Did you already?

**Comment by ZhilkinSerg** [comment]
Nice catch!

**Comment by Faalagorn** [comment]
It works for me with this patch too, just (unrelated to this patch), having the game set to fullscreen or borderless makes the game not launching with `error -1: Tried to set invalid xdg-surface geometry`. Thanks!

**Comment by Adriankhl** [comment]
@Faalagorn Are you using sway and and the latest sdl 2.0.16? Then, you should patch the sdl in your distro with this: https://github.com/libsdl-org/SDL/pull/4629

**Comment by Adriankhl** [comment]
@MalteT I am stilling having the same problem after applying the patch to 0.F, which version are you using?

**Comment by Faalagorn** [comment]
> @MalteT I am stilling having the same problem after applying the patch to 0.F, which version are you using?

Not @MalteT but for me it worked for me on the latest master, here's my PKGBUILD for Arch I used https://gist.github.com/Faalagorn/e6d6440cd768d32c8a571023fa08769a

```
[faalagorn@faalagorn-pc ~]$ pacman -Q cataclysm-dda-git
cataclysm-dda-git cdda.experimental.2021.08.14.1744.r0.gbadd5e3393-1
```

**Comment by MalteT** [comment]
@Adriankhl, I'm on master (9d7ed7d6d918942cf1eedffb40477a3b3b33bf76 to be precise). I'm not sure about the SDL version. I'm on nixos-unstable and would assume that I'm using the latest SDL.

**Comment by Faalagorn** [comment]
One more issue I have on Wayland is that it doesn't detect my second monitor giving me an option only for my primary one and blank, but maybe it's something on my side. It runs well otherwise.

**Comment by andrei8l** [comment]
> It's still missing a redraw on resize, at least with my setup (Sway).

Resizing works fine for me on mutter.
> are you planning on submitting a PR?

Feel free to open a PR with a proper patch yourself, for example
<details>
<summary>possibly good patch</summary>

```diff
diff --git a/src/sdltiles.cpp b/src/sdltiles.cpp
index 7f930e8c9c..e802865e80 100644
--- a/src/sdltiles.cpp
+++ b/src/sdltiles.cpp
@@ -545,11 +545,10 @@ void refresh_display()
     // Select default target (the window), copy rendered buffer
     // there, present it, select the buffer as target again.
     SetRenderTarget( renderer, nullptr );
+    ClearScreen();
 #if defined(__ANDROID__)
     SDL_Rect dstrect = get_android_render_rect( TERMINAL_WIDTH * fontwidth,
                        TERMINAL_HEIGHT * fontheight );
-    SetRenderDrawColor( renderer, 0, 0, 0, 255 );
-    RenderClear( renderer );
     RenderCopy( renderer, display_buffer, NULL, &dstrect );
 #else
     RenderCopy( renderer, display_buffer, nullptr, nullptr );
```
</details>

Make sure you test on Android though! There's also an input issue for slow CPUs that you could address; let me know if you need ideas.

> P.S. There's also an issue where cursor being bigger than usual

Upstream issue. At the moment there's no common way to get cursor size (and probably there never will be).
> One more issue I have on Wayland is that it doesn't detect my second monitor giving me an option only for my primary one and blank, but maybe it's something on my side.

This will most likely never work on Wayland since it doesn't allow clients to position themselves. On mutter, the window opens on the same display as the (primary) cursor.

**Comment by Faalagorn** [comment]
> Feel free to open a PR with a proper patch yourself, for example
> possibly good patch
> 
> ```diff
> diff --git a/src/sdltiles.cpp b/src/sdltiles.cpp
> index 7f930e8c9c..e802865e80 100644
> --- a/src/sdltiles.cpp
> +++ b/src/sdltiles.cpp
> @@ -545,11 +545,10 @@ void refresh_display()
>      // Select default target (the window), copy rendered buffer
>      // there, present it, select the buffer as target again.
>      SetRenderTarget( renderer, nullptr );
> +    ClearScreen();
>  #if defined(__ANDROID__)
>      SDL_Rect dstrect = get_android_render_rect( TERMINAL_WIDTH * fontwidth,
>                         TERMINAL_HEIGHT * fontheight );
> -    SetRenderDrawColor( renderer, 0, 0, 0, 255 );
> -    RenderClear( renderer );
>      RenderCopy( renderer, display_buffer, NULL, &dstrect );
>  #else
>      RenderCopy( renderer, display_buffer, nullptr, nullptr );
> ```
> 
> Make sure you test on Android though! There's also an input issue for slow CPUs that you could address; let me know if you need ideas.

Thanks for the new patch, I'm gonna test it and probably continue to use it for playing on Wayland natively, but not sure I'll be up for testing and making a proper PR, so if someone's up for the task, feel free to go! Good point about Android though. 

> > P.S. There's also an issue where cursor being bigger than usual
> 
> Upstream issue. At the moment there's no common way to get cursor size (and probably there never will be).

That's interesting, why is it larger than in other SDL games I played? Or maybe they don't use a system cursor :thinking:  

> > One more issue I have on Wayland is that it doesn't detect my second monitor giving me an option only for my primary one and blank, but maybe it's something on my side.
> 
> This will most likely never work on Wayland since it doesn't allow clients to position themselves. On mutter, the window opens on the same display as the (primary) cursor.

That's interesting as well, why there's an empty string though? Is it because I have two monitors in the first place? I might test it with one disabled.

**Comment by MalteT** [comment]
> Feel free to open a PR with a proper patch yourself, for example

I'd be interested in opening a PR in the upcoming week, I'll do some Android testing aswell, would be a first though, so I might have some additional questions. :)

**Comment by Faalagorn** [comment]
> > Feel free to open a PR with a proper patch yourself, for example
> 
> I'd be interested in opening a PR in the upcoming week, I'll do some Android testing aswell, would be a first though, so I might have some additional questions. :)

Well, I tested your new patch and it continues to work fine on my system, so it's good to go here so far. :)
