### ISSUE TITLE
Cannot complete half-built wooden staircase

### ISSUE THREAD

**Issue by zer0Entropy** [CleverRaven/Cataclysm-DDA#49881]
### Describe the bug

My current character finds himself wanting to build a staircase leading up inside of a restaurant (long story...)

He proceeded to disassemble furniture in the restaurant to accumulate enough crafting materials.  After doing so, I went into the Construction menu (*), selected "Build Wooden Staircase", and BAM -- a half-built wooden stairs is there, as expected.

However, the game will not let me complete the staircase!  It shows all the skills, tools, and components in green, confirming I have enough of all of them (I do).  But when it asks me, "Construct where?", the half-built wooden staircase I previously built is not one of the highlighted squares, and when I try to select that tile anyways, it tells me "You cannot build there!"

![Screenshot-Construction Menu](https://user-images.githubusercontent.com/20136649/125253479-12faf680-e2bf-11eb-938a-9e40363df915.png)

![Screenshot-Confirm Direction](https://user-images.githubusercontent.com/20136649/125253499-1a220480-e2bf-11eb-93ed-21ccc23fd305.png)

![Screenshot-Cannot Build](https://user-images.githubusercontent.com/20136649/125253514-1db58b80-e2bf-11eb-98e9-c849bc3a97d9.png)

### Steps To Reproduce

1.  Complete stage 1 of "Build Wooden Staircase" from the Construction Menu.
2.  Attempt to complete stage 2 of "Build Wooden Staircase".
3.  Be unable to select the half-built wooden staircase when prompted for a construction location.

### Expected behavior

I expected to be able to complete stage 2 of "Build Wooden Staircase" and thereby upgrade the half-built wooden staircase to a full-fledged, usable wooden staircase.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 21.04; Release: 21.04; Codename: hirsute; 
- Game Version: ab86019 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Graphical Overmap [Graphical_Overmap]
]

**Comment by zer0Entropy** [comment]
It just occurred to me that including a save file might be helpful to anyone trying to figure out why this is happening.
[algernop.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/6810188/algernop.tar.gz)

**Comment by Valares** [comment]
Can't reproduce, following your `Steps To Reproduce` in a new world, I can build a wooden staircase without problems.

Based on your screenshots it looks like you're trying to build the staircase inside a building. Unless you have knocked down (a part of) the roof, there's still a floor above you, so it can't build the stairs (as they would lead nowhere).
If that's the case, I'd say it's working as intended. Either build them under a free tile or free up the tile above it.

**Comment by zer0Entropy** [comment]
Valares, thank you for taking the time to look into this and respond.

After posting this issue and thinking about it for awhile, I was beginning to suspect something like that myself.  I would like to humbly suggest: it would be really nice, as a usability feature, if I got an in-game message explicitly telling me that when I attempt to build a staircase in a location where it cannot be completed.

(In a more perfect world, I'd dive straight into the source code and make that change myself; however, at this stage in its development, the CataclysmDDA codebase is...daunting, to a newcomer such as myself.)

Thanks again for responding.
