### ISSUE TITLE
Android x64 0.F says it's experimental

### ISSUE THREAD

**Issue by PLUUZ** [CleverRaven/Cataclysm-DDA#49885]
### Describe the bug

The 0.F release version for android says its an experimental build in the app name, and when launched has a experimental version code underneath the CDDA title.  experimental build disclaimer remains in the credits.

I haven't used android cdda in a while i suspect this is just some convention i'm unfamiliar with but i will open the issue just in case.

### Steps To Reproduce

1. Go to the release frank page at https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/0.F
2. Download https://github.com/CleverRaven/Cataclysm-DDA/releases/download/0.F/cdda-android-x64-2021-07-03-0512.apk
3. install app into phone
4. c.f. the name of the app, the version code, and the experimental build disclaimer

### Expected behavior

0.F would be in the version code, app would not say experimental, no disclaimer would be inside the app.

### Screenshots

![android](https://user-images.githubusercontent.com/30785198/125299581-ce9c4480-e318-11eb-99b4-27967caeb7f5.png)

### Versions and configuration

- OS: android 10
- Game Version: bc28921 (expected 0.F)
- Graphics version: tiles

**Comment by RenechCDDA** [comment]
As we have since released 0.G, if this wasn't already resolved I feel confident saying it never will be.
