### ISSUE TITLE
Crash to Desktop after accepting fisherman mission

### ISSUE THREAD

**Issue by AdamChirnside** [CleverRaven/Cataclysm-DDA#49896]
### Describe the bug

After accepting the quest to help the fisherman bring back his family, and then navigating around the overmap screen game crashes to desktop.

### Steps To Reproduce

1. Load attached save
2. Accept quest to find the fisherman's family
3. Open 'm'ap
4. Move cursor towards and onto mission objective

### Expected behavior

No crash

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 4abcc6f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Disable NPC Needs [no_npc_food],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Alternative Map Key [alt_map_key],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

[My savefile](https://www.dropbox.com/s/jqjpkdmv6srv7ns/Olex.7z?dl=0)

**Comment by pehamm** [comment]
Cannot replicate. Can you paste the crash.log? It should be in the config folder.

**Comment by AdamChirnside** [comment]
> Cannot replicate. Can you paste the crash.log? It should be in the config folder.

Unfortunately, no such file exists for me. I have just updated the steps to reproduce however.
Going to try reproducing on the latest release as well.

**Comment by AdamChirnside** [comment]
Still getting the same crash on 2f313ab

**Comment by anothersimulacrum** [comment]
I'm going to close this as fixed, then. If someone still has it, please comment here to reopen it.
