### ISSUE TITLE
Magiclysm speed ring glitch

### ISSUE THREAD

**Issue by Torres84f** [CleverRaven/Cataclysm-DDA#49891]
### Describe the bug

Speed rings are grossly overpowered, they should add +10 speed yet they add something like +1300

### Steps To Reproduce

1.- Spawn +10 speed ring
2.- Wear it and see your speed reach 1400+
3.- Spawn a 2nd +10 speed ring
4.- Wear that one too and watch as you become The Flash with 3000+ speed

### Expected behavior

Speed rings shouldn't be **that** unbalanced 

### Versions and configuration

18:28:17.596 :  GAME REPORT:
- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 4abcc6f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Graphical Overmap [Graphical_Overmap],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    DinoMod [DinoMod],
    Crazy Cataclysm [crazy_cataclysm],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Crazy Cataclysm - UndeadPeople Tileset [CrazyCataclysmUDP],
    DinoMod - UndeadPeople Tileset [DinoModUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    My Sweet Cataclysm - UndeadPeople Tileset [My_Sweet_CataclysmUDP],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by actual-nh** [comment]
Ping: @KorGgenT?

**Comment by GGgatherer** [comment]
Can confirm. Behold this glory:

![](https://aws1.discourse-cdn.com/standard11/uploads/cataclysmdda/original/2X/a/aa9d67309a6e6d4ac09245e46b9ba27e50764a9e.png)

That's with +7 speed ring.
I think it broke somewhere after 2021-07-03-0750.

**Comment by actual-nh** [comment]
Another person noticed (see above).
