### ISSUE TITLE
Typo in magiclysm druid spells JSON

### ISSUE THREAD

**Issue by AdamChirnside** [CleverRaven/Cataclysm-DDA#49902]
### Describe the bug

```
 DEBUG    : Error: Json error: data/mods/Magiclysm/Spells/druid.json:402:3: tried to start object, but found '}', not '{'

    "effect_str": "mon_wolf"
  },
  }
  ^

    "id": "druid_natures_commune",
    "type": "SPELL",


 FUNCTION : bool main_menu::load_character_tab(bool)
 FILE     : src/main_menu.cpp
 LINE     : 1144
 VERSION  : 00b2a14

```

### Steps To Reproduce

Try to open game with Magiclysm loaded

### Expected behavior

Normal load

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 00b2a14 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Disable NPC Needs [no_npc_food],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Alternative Map Key [alt_map_key],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

Changing the } to { fixes the issue

**Comment by actual-nh** [comment]
Fixed - 3 hours ago! - by #49897, but thank you.
