### ISSUE TITLE
Battery System CBM not working properly

### ISSUE THREAD

**Issue by Robik81** [CleverRaven/Cataclysm-DDA#49905]
### Describe the bug

You can't 'eat' batteries to store battery power and subsequently you can't activate CBM to reload from stored battery power, because you have none.

### Steps To Reproduce

1. start with Bionic Game Master to have CBM
2. spawn some batteries to your inventory
3. try to 'E'at batteries - they are grayed out
4. try to use 'R'efuel in Bionics menu, you get "You have no fuel to consume" popup.

### Expected behavior

You should be able to either consume batteries by eating or by refuelling to store battery power.

### Versions and configuration

- OS: Windows
    - OS Version: 7
- Game Version: 4abcc6f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Commented about it in #49789. Was told CBM works by reloading from 'stored battery power', which is gained by eating batteries. Never used this CBM before, so despite trying my best with bug description and expected behavior, it might be unintentionaly wrong.

Probably related to #48750

**Comment by actual-nh** [comment]
Ping: @Fris0uman?

**Comment by PositiveVibesVR** [comment]
I can confirm that I am also having the same issue on the latest build (2021-07-13-0115)

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/battery-system-cbm-possible-bug/26722/3

**Comment by Nabo92** [comment]
> This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:
> 
> https://discourse.cataclysmdda.org/t/battery-system-cbm-possible-bug/26722/3

OP here, having the same issue. No way to consume batteries or open the refuelling menu.
