### ISSUE TITLE
Shotgun/other weapons reload time independent of retrieve time of pocket that ammo resides in.

### ISSUE THREAD

**Issue by GadekMaciej** [CleverRaven/Cataclysm-DDA#49911]
### Describe the bug

Shotgun reload movement cost is the same, no matter if my ammo is on the bottom of hiking backpack, ~~on the pavement~~, or in my shotgun ammo bandolier (which should have considerable faster "draw" speed than previous items). The same is true for reloading glock 17 with its apropriate magazines.

### Steps To Reproduce

1.Spawn in some containers with pockets, ammo satchel, shotgun waist bandolier, duffle bag ect;
2.spawn gun and additional ammo;
3.place ammo in diferent pockets (with different retrieve times);
4.hit r for reload;
5.no matter which pocket ammo resides, reload times remain the same. (notice how reload times are different for ammo on the ground, from my testing the numbers seems to be not-final and work well when ur "naked", not so well when ur under multiple effects, I might be wrong on that detail tho.
![image](https://user-images.githubusercontent.com/64140639/125470548-4b8a5c81-f5f9-4b3a-a691-c5b586e8a762.png)

### Expected behavior

grabbing ammo from pockets closer to hand(with faster retrieve speed), should be considered when reloading a weapon.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 4663683 [64-bit]
- Graphics Version: Tiles (UDP)
- Game Language: System language [English]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

The same is true for glock,
![image](https://user-images.githubusercontent.com/64140639/125470866-1c13db22-8623-4f54-afd6-172c8afe4146.png)

**Comment by anothersimulacrum** [comment]
It's either a display bug or a bug with obtaining ammo, yes.

**Comment by GadekMaciej** [comment]
I'm not an expert but from my limited knowledge and experience function **Character::item_reload_cost** doesn't consider pocket in which ammo resides

**Comment by pjf** [comment]
Can confirm. I've seen this with sling staffs and stone bags, and with STANAG magazines and leg pouches.
