### ISSUE TITLE
Generic Guns Show Up When Turned Off

### ISSUE THREAD

**Issue by TheMurderUnicorn** [CleverRaven/Cataclysm-DDA#49920]
### Describe the bug

While the option for generic guns is disabled, generic guns still appear in the game.

### Steps To Reproduce

Enable gun brand names
Run around until you accrue firearms
See that some generic guns are appearing

### Expected behavior

I expect that when I enable gun brand names I only get guns with brand names.

### Screenshots

Here you'll see the AR-15 which is a brand name, whereas the shotgun is generic.  I also have an M4 in my inventory and many guns in my base that all use brand names, so I know I have them enabled.
![image](https://user-images.githubusercontent.com/41651793/125532329-44f7082e-1478-4f1c-98d4-29fbc5e22d1c.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: aa126fe [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Caches [P_Caches],
    No Fungal Monsters [No_Fungi]
]

### Additional context

I was fine with this new feature when I thought I could disable it.  But forcing generic guns into my game is actually terrible.  This feature should not impact those that choose to play without it.

Additionally, I believe generic guns should be disabled by default -- yes, I'm glad we have it for people who want more abstracted guns.  But I also believe that you will turn off people who want real gun names.  Maybe I'm in the minority but I hate when games have abstracted guns when they could have real gun names, and I suspect I'm not the only person.

Also because it's a feature that revolves entirely around preference, I would encourage you to poll the community online and see what the majority prefer.  Normally I never suggest getting feedback from the community because communities are wrong all the time and often terrible, but given that this is just preference it makes sense to go with a majority.

Again, not trying to crap on whoever made the change, but one it should not impact me if I choose to disable it (which it currently does, hence the issue) and two I don't believe it should be default because I believe people who use this will not be the majority.

**Comment by anothersimulacrum** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/issues/49573

**Comment by TheMurderUnicorn** [comment]
So do I close this or leave it open?  I see the other one hasn't been confirmed, I doubt my posting about it helps anyone else confirm it other than by me saying I've also had this issue.

Mine differs from the other because this gun was generated long after I had disabled the generic guns, so it was not a gun that failed to convert, it was generated this way.

**Comment by anothersimulacrum** [comment]
Sorry for the extremely brief response. It's better to not have two issues open for the same bug, yeah.
