### ISSUE TITLE
Claire Isherwood gives excessive opiates

### ISSUE THREAD

**Issue by pjf** [CleverRaven/Cataclysm-DDA#49926]
### Describe the bug

When completing the quest "Gather 50 dandelions" for Claire Isherwood, she gave me a glass jar of "poppy painkiller" as a reward.

Except the jar contains 200 doses. That seems like a *lot*.

Making that much painkiller by hand would require 40 poppy buds. I get that Claire likes dandelions, but I get the impression she values them a little too highly for this to be the reward.

### Steps To Reproduce

1. Find Claire Isherwood on the Isherwood farm
2. Complete the "Gather 50 dandelions" quest
3. You now have more opiates than you could ever need

### Expected behavior

Claire gives you drugs, just not quite so many drugs.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: cdda-experimental-2021-07-13-2317, with some local patches
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Slots [cbm_slots]
]

### Additional context

I haven't checked the data files, so I don't know if Claire's rewards are static or random.

**Comment by I-am-Erk** [comment]
@curstwist

**Comment by GoLoT** [comment]
She is trying to hook you and since she is the only dealer around, I'm sure she got the model business right. Free samples always have a catch.
