### ISSUE TITLE
Prep net cyber mastiffs attach player when the prepnet man is attacked by monsters

### ISSUE THREAD

**Issue by Sanek12382** [CleverRaven/Cataclysm-DDA#49937]
### Describe the bug

in my case a couguar started attacking him  and when i approached to try and helped i realized that the cyber masstifs are hostile

### Steps To Reproduce

1. have a prep net person with cyber mastiffs(in my case at a prep net orhard)
2. have a monster acttach and hurt him(in my case a cougar lept over the fence
3. run?
4. PS the apple orchard building dont seem to have a roof(if you try to climb a labber in the storage one it will warn and theyn youll fall down, step ladder says there is nowhere you can get up to and so does the drain pipe on the building)
[Uploading Mizpah.zip…]()

[Uploading Mizpah.zip…]()

### Expected behavior

dogs woudnt get mad at me

### Versions and configuration

- OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
- Game Version: [from the main menu, e.g. 0.C-29938-g90f5268437]
- Graphics version: [Tiles or Terminal]
- Ingame language: [Arabic or Bulgarian or Chinese (Simplified) or Chinese (Traditional) or Dutch or Esperanto or French or German or Italian (Italy) or Japanese or Korean or Polish or Portuguese (Brazil) or Russian or Serbian or Spanish (Argentina) or Spanish (Spain) or Turkish]
- Mods loaded: [e.g.dda, boats, hacktheplanet, StatsThroughSkills]

**Comment by Sanek12382** [comment]
for whatever reason my save doesnt want to load in here ill send it to the email in MOTD

**Comment by actual-nh** [comment]
Before you do that, what version are you running? If it's anything much prior to 0.F, that can be fixed by upgrading to version 0.F.

**Comment by Sanek12382** [comment]
![image](https://user-images.githubusercontent.com/58268711/125697504-bf3368cf-bec6-4c5b-ae57-af6a5b4d03ef.png)

**Comment by Maleclypse** [comment]
I think this is unfortunately part of our monster hostile code. There’s a PR that I thought had been merged which replaces the barbed wire with more appropriate walls that should help to prevent this in the future.

**Comment by actual-nh** [comment]
I am puzzled on this one. The cyber-mastiffs are of the PrepNet faction - which is neutral toward humans (including the player) - and do not have ATTACKMON. They should not be attacking anything they're neutral toward.

**Comment by hexagonrecursion** [comment]
Clarification: cyber-mastiffs *do not* become hostile when a cougar attacks a prepnet NPC. cyber-mastiffs *do* become hostile when the cougar attacks them directly.
- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: bc1f60e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Aftershock: Exoplanet [aftershock_exoplanet]
]

**Comment by NetSysFire** [comment]
Closing in favor of #54752.
