### ISSUE TITLE
Can't put a condom inside a travel wallet.

### ISSUE THREAD

**Issue by Saicchi** [CleverRaven/Cataclysm-DDA#49932]
### Describe the bug

Can't put a condom inside a travel wallet.

### Steps To Reproduce

1. Spawn and Wield a Travel Wallet
2. Spawn a condom
3. Try to put condom inside travel wallet
4. Fail

### Expected behavior

Condom can be put inside travel wallet.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.F-705-g4663683f2d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]
]

### Additional context

Unlike the other wallets, `condom` is not in the `item_restriction` list of the travel wallet pocket.

**Comment by hjk321** [comment]
I can only imagine what the gameplay scenario was that led you to discover this.

**Comment by Saicchi** [comment]
> I can only imagine what the gameplay scenario was that led you to discover this.

I was confirmed this bug https://discourse.cataclysmdda.org/t/bug-3-75-liter-condom-inside-wallet/26670
