### ISSUE TITLE
Liquid poured into toilets can't be taken out again if the liquid is not water. 

### ISSUE THREAD

**Issue by ifffrt** [CleverRaven/Cataclysm-DDA#49935]
### Describe the bug

Sometimes I try butchering corpses on top of toilets and bathtubs to try to collect as much blood from the corpses as I can for recipes that need them (like the Twisted Restoration potion from Magiclysm or Mana Infused Dust). But this only really works on bathtubs, as any liquid that isn't regular water (not even clean water or salt water) cannot be taken out again when poured inside toilets. It's even impossible to mop up the liquid, rendering the toilet useless.

### Steps To Reproduce

1. Pour water into an empty toilet.
2. Interact with it with "E". It will let you pour it onto the floor. Do it.
3. Pour blood or diesel or any other liquid into the empty toilet.
4. Try interact with the toilet again. It will only bring up the pickup-item menu and not the one that lets you pour the liquid out.

### Expected behavior

That toilets should let you pour every types of liquid out, not just basic water.

(But the volume that the toilet can contain should be capped at "Volume of standing tank"+"Maximum volume of toilet bowl before the liquid flows down the trapway pipe (the u-shaped pipe)". Because as of now the toilet has a max capacity of 1000 liters, 5 times that of a bathtub, and could theoretically be used to harvest all of a black dragon's blood that would normally be wasted if this bug was fixed.)

### Versions and configuration

    OS: Windows
        OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version [Windows 8.1 Pro build 9600]
    Game Version: 0.E-7667-g6bc3296 [64-bit]
    Graphics Version: Tiles
    Game Language: English [en]
    Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key],
    Graphical Overmap [Graphical_Overmap],
    sees-player icon, retrodays [sees_player_retro],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    Mythical Martial Arts [MMA],
    More Survivor Stuff [more_survivor_stuff],
    Fuji's Military Profession Pack [fuji_mpp],
    Mutation Changes [Mutation_Changes],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
    ]

**Comment by actual-nh** [comment]
This would appear to be due to toilet handling via what is described as a "kluge" in inventory.cpp (form_from_map).

**Comment by Night-Pryanik** [comment]
Resolved by #58486.
