### ISSUE TITLE
Error in Russian localization

### ISSUE THREAD

**Issue by Xomikadze** [CleverRaven/Cataclysm-DDA#49943]
### Describe the bug

Part of the ammunition that has a cartridge separator in the form of the letter "x". Separated by different letters. In one case it is the Russian "x" in the other English "x". Probably it is necessary to decide which letter to use for all such cases, Russian or English.

### Steps To Reproduce

1) enter the game
2) select the interface which mode Russian
3) Enter debug mode
4) Try to find such items using the search.

### Expected behavior

All ammunition drops out in the list and you do not need to change the letter to search.

### Screenshots

first English "x", second Russian "х"
![image](https://user-images.githubusercontent.com/68762218/125693028-94649e97-465b-4019-bee6-46ff10846d91.png)
![image](https://user-images.githubusercontent.com/68762218/125693049-bc9cb1a1-461b-4cd0-9b50-329da76914e4.png)

### Versions and configuration

- OS: Windows 10
- Game Version: 5fec688
- Graphics version: Tiles
- Ingame language: Russian

**Comment by Xomikadze** [comment]
Forgot to mention. There is a search through the crafting interface, then the same difficulties arise.

**Comment by ZhilkinSerg** [comment]
Translations are handled on Transifex - see https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/TRANSLATING.md

**Comment by Xomikadze** [comment]
@ZhilkinSerg it turns out about problems with translation you need to write to another resource (subforum)? How to deal with this task?

**Comment by leemuar** [comment]
Just register on Transifex , find the wrong string and fix it right there

> 
> @ZhilkinSerg it turns out about problems with translation you need to write to another resource (subforum)? How to deal with this task?

**Comment by Xomikadze** [comment]
@leemuar Oh, nice. I was looking at the page that ZhilkinSerg threw off. The only thing there is a few versions. I don't quite understand which one needs to be edited. It is also written that everything is 100% translated, but I know that in the latest version there are not translated items. Therefore, I have even more questions about which specific version I need to fix.

**Comment by leemuar** [comment]
master. Тебе нужно выбирать для перевода master.

То что написано "100% переведено" - это нормально. Это лишь означает, что не осталось не переведенных строк. Но это не означает, что нельзя уже переведенную строку исправить. Заходишь в master, ищешь поиском интересующие тебя строки - и вводишь там в поле справа исправленный перевод

> 
> 
> @leemuar Oh, nice. I was looking at the page that ZhilkinSerg threw off. The only thing there is a few versions. I don't quite understand which one needs to be edited. It is also written that everything is 100% translated, but I know that in the latest version there are not translated items. Therefore, I have even more questions about which specific version I need to fix.

**Comment by leemuar** [comment]
Я за то чтобы использовать русскую "х"

**Comment by Xomikadze** [comment]
@leemuar если ты не против давай обсудим это в дискорде. У меня всё равно остались вопросы.

**Comment by Night-Pryanik** [comment]
Closing the issue as this matter better discuss elsewhere.
