### ISSUE TITLE
Pocket Comparison is backwards

### ISSUE THREAD

**Issue by YourCompanionCube** [CleverRaven/Cataclysm-DDA#49944]
### Describe the bug

When comparing one container to another the bigger pocket is shown as worse

### Steps To Reproduce

Compare with 'I' two bags with different total volume, length, and weight capacities 

### Expected behavior

That the bag that can hold more, larger, heavier stuff is considered better

### Screenshots

High volume rucksack (left) vs golf bag (right)
![image](https://user-images.githubusercontent.com/26364270/125697567-f6d34343-3808-412b-9f12-13f0c8c682c3.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Gun Cotton [guncotton],
    Graphical Overmap [Graphical_Overmap],
    Stats Through Skills [StatsThroughSkills],
    Useful Helicopters [useful_helicopters],
    SpeedyDex [speedydex]
]

**Comment by WelpThatWorked** [comment]
Appears Fixed?

![image](https://user-images.githubusercontent.com/9769385/130130074-2b704e52-2677-46eb-bd3c-ec3e1b573d79.png)
![image](https://user-images.githubusercontent.com/9769385/130130103-1d4b2c48-46d3-46e2-9b80-dc91c48e0f9f.png)

**Comment by YourCompanionCube** [comment]
Confirmed on latest experimental debug world, don't know who fixed it but it's cool that it's fixed

![image](https://user-images.githubusercontent.com/26364270/131198588-0f7116ca-e8e9-4986-9854-26e65d8cf119.png)

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 308d1d2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
