### ISSUE TITLE
Postapoc prices need audit

### ISSUE THREAD

**Issue by leemuar** [CleverRaven/Cataclysm-DDA#49956]
### Describe the bug

Im trading with a free merchant in HUB01, suddenly he sells all CBMs for just 10$. This is extremely low. I've visited this merchant on 0.E-2, CBMs were VERY expensive

Also this merchant buys weapons for decreased value. M4A1 was $2000+, now he only buys it for like 60$

### Steps To Reproduce

I really don't know how to reproduce it

Here is the save file for 0.F stable
[Хатто.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6821527/default.zip)

Here is save file for 0.E-2 I used to migrate to 0.F:
[0.E-2.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6821523/0.E-2.zip)

### Expected behavior

Prices should be higher

### Screenshots

![image](https://user-images.githubusercontent.com/5869791/125753269-3da8f370-c210-4020-a764-e04121909970.png)

![image](https://user-images.githubusercontent.com/5869791/125753564-30992f94-87eb-4bbf-9de6-ce000de4d055.png)

![image](https://user-images.githubusercontent.com/5869791/125755370-487b4614-1831-4c52-b83c-2153608a135a.png)

### Versions and configuration

- OS: Windows 10 x64
    - OS Version: 10.0 1909
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]

### Additional context

Im playing save exported from 0.E-2 stable. I've visited this trader in 0.E-2. Maybe it is important.

**Comment by anothersimulacrum** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/POSTAPOC_PRICE_GUIDE.md#how-to-give-items-a-sensible-postapoc_price-value

**Comment by leemuar** [comment]
> 
> 
> https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/POSTAPOC_PRICE_GUIDE.md#how-to-give-items-a-sensible-postapoc_price-value


Are you trying to say these new prices are new norm in 0.F?

**Comment by anothersimulacrum** [comment]
Pricing guidelines exist now, that did not in 0.E, yes.

**Comment by leemuar** [comment]
> 
> 
> Pricing guidelines exist now, that did not in 0.E, yes.

But I don't understand how it affects price drops. I've checked json for the price:

![image](https://user-images.githubusercontent.com/5869791/125846327-f3d03593-8eba-48db-9601-40a15f6cab9f.png)

Integrated Toolset price in json is 800000. In my save file it's been sold for 10$. I believe it is not because prices were changed in data files.

**Comment by anothersimulacrum** [comment]
That is probably because it inherit's a price_postapoc from `bionic_general_npc_usable`.

**Comment by leemuar** [comment]
> 
> 
> That is probably because it inherits a price_postapoc from `bionic_general_npc_usable`.

Yeah, you are right! bionic_general has price_postapoc 1000, which is exactly 10$. Thanks for pointing it out.

I think prices need audit because buying any CBMs for just 10$ looks kinda game-breaking

**Comment by anothersimulacrum** [comment]
I agree that the CBM prices could definitely use with a look-over, instead of all inheriting.

**Comment by Maleclypse** [comment]
My personal suggestion for this writing it here til I can edit the guide. Is for CBMs and other ultra tech to have significantly higher prices than the guide listed max of $20. These items are only being sold by people who know what they are snd what to do with them. We could then create a new item called techno-doodad that is sold by non tech savvy traders and it has to be traded in to someone who can decipher what it does and they randomly give back some other item or if the player can decipher what it is it could turn into a random item. I think this could all be done in json currently.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
