### ISSUE TITLE
Slowdown from debug message

### ISSUE THREAD

**Issue by Hirmuolio** [CleverRaven/Cataclysm-DDA#49966]
### Describe the bug

Game speed is approximately halved when player has active mp3 player.
The cause is debug message here: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/effect.cpp#L841

* The `to_string( duration )` in the debug message is evaluated even when debug mode is off.
* The `to_string` is very slow if translation files are not present.

### Steps To Reproduce

Run CDDA on windows.
Wait and see how fast the game is
Turn on mp3 player.
Wait and see how slow the game is.

Add translation files.
Wait again with mp3 player on and see how fast the game is.

### Expected behavior

* The `to_string( duration )` in debug message should not be evaluated when debug mode is off.
* `to_string` should not be very slow if translation files are not present.

### Screenshots

Without english translation files:
![debug](https://user-images.githubusercontent.com/22011552/125828421-8e105b4f-a2f8-43fe-ad4d-1ba29e8bcf62.png)

With english translation files:
![debug2](https://user-images.githubusercontent.com/22011552/125828642-3080f3fc-5278-46cc-b453-26e2200fe514.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.C-62935-gcc0bdb2976 [64-bit] (built from recent experimentals)
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Dark Days of the Dead [classic_zombies]
]

### Additional context

According to discord comments #31673 should have prevented things in debug messages being evaluated when not in debug mode.
#38892 is related to the language files affecting performance.

**Comment by anothersimulacrum** [comment]
273a5b1e9caf4e1bad11ac93247b95b517a63a5a changed `add_msg_debug` from a macro to a template function.

Possibly making those template functions constexpr would help? I am not too familiar with how that all works.

**Comment by actual-nh** [comment]
I suggest replacing `to_string` with `to_string_writeable` in the specific instance (taking a duration); that doesn't go through translation (unless string_format does).

**Comment by Qrox** [comment]
> 273a5b1 changed add_msg_debug from a macro to a template function.

I suppose we can reinstate the macro by renaming the template and redirecting to it if debug mode is on.

**Comment by actual-nh** [comment]
Ping: @jbytheway, in regard to making add_msg_debug not interpret arguments unless debug_mode is indeed set.
