### ISSUE TITLE
Current experimental builds are missing a lot of localized strings

### ISSUE THREAD

**Issue by leemuar** [CleverRaven/Cataclysm-DDA#49963]
### Describe the bug

Originally reported in #49943 

@Xomikadze noted that experimental builds are missing LOTS of localized strings. Not the new ones, but strings that were translated in 0.F stable.

### Steps To Reproduce

Download f40b5330 experimental
Switch to Russian language
Open Debug - Spawn menu
Scroll down te list of items and note there are translated and untranslated strings
f.i. try to search for "stick"

### Expected behavior

Everything is translated

### Screenshots

![image](https://user-images.githubusercontent.com/5869791/125799425-c4f0daa9-c4da-4a60-8f5b-50c627bf6e28.png)

![image](https://user-images.githubusercontent.com/5869791/125801014-0ceb06ab-2327-4d69-9600-b35cde20dae3.png)

### Versions and configuration

cdda-windows-tiles-x64-2021-07-15-0526

### Additional context

0.F stable has all strings translated

**Comment by Qrox** [comment]
These strings can be found on Transifex but are somehow missing from the `.po` file. Ping @BrettDong.

**Comment by BrettDong** [comment]
Will do the next translation synchronisation in the weekend.

**Comment by Qrox** [comment]
According to the commit history, `ru.po` hasn't been updated sicne d7fc0b50e601537751ee84b056d071000f5ba090.
