### ISSUE TITLE
Farms generate with harvestable plants no matter what

### ISSUE THREAD

**Issue by Marrim** [CleverRaven/Cataclysm-DDA#49975]
### Describe the bug

1) Farms always generate with a field full of corn, oats or wheat, even after the first year.
2) Plants that generated during the first year but were not harvested, do not die during winter and can be harvested at the player's leisure.
This creates an almost infinite supply of easy food.

### Steps To Reproduce

Choose "The Next Summer" scenario and start on a farm. Note that the farm is sown with mature corn plants.
Alternatively, start on a farm in late fall and wait into the winter--the plants survive.

### Expected behavior

In the winter all crops should wilt.
Even before winter a lot of them would be eaten by birds and wild animals. Nobody is looking after them.
Farms generated during the second and subsequent years should not have crops. Nobody is sowing.

### Versions and configuration

Stable 0.F, Ubuntu 18.04.

**Comment by Xomikadze** [comment]
I disagree. Crops that no one has harvested can still germinate in the spring. Because their fruits usually contain seeds. And if no one has collected them, then they will fall to the ground and can germinate. I think that the majority will die, because these are cultures used to serving people, but still some will remain. I think 20% will remain after the first year, everything else will die and will not germinate again. And it's hard for me to imagine what will happen after 2 years.

**Comment by actual-nh** [comment]
Seeds may not sprout from some sterile hybrids.

**Comment by Marrim** [comment]
I propose, at least as a first approximate solution, to use the same logic as with vending machines (that generate with proportionally less contents if found late in the game).

**Comment by hexagonrecursion** [comment]
Confirmed: I spawned on a farm in "The Next Summer" scenario and it was about 50% full of corn

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: bea0650 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by abatyiev** [comment]
There are multiple farms full of corn (in winter!) with quickly maturing plants (maturing -> harvestable) in "Sheltered" scenario.
