### ISSUE TITLE
unharvestable poppies

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#49970]
### Describe the bug

In Dark Skies Above the poppies can not be harvested

### Steps To Reproduce

use the mod, try to interact with the poppies

### Expected behavior

able to harvest poppies

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 1f0b625 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Simple_additions [simple_additions],
    Dark Skies Above [darkskies],
    Stats Through Skills [StatsThroughSkills],
    Bionic Slots [cbm_slots]
]

### Additional context

adding this line to the poppies file in the mod fixes it` 
   "examine_action": "flower_poppy",`

**Comment by hexagonrecursion** [comment]
confirmed
- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 8051d7d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Dark Skies Above [darkskies]
]

**Comment by anothersimulacrum** [comment]
Is this intentional @ephemeralstoryteller ?

**Comment by ephemeralstoryteller** [comment]
Very strange that it never seems to ping me for these.

Unintentional, though it seems that `copy-from` doesn't inherit examine_actions?

Should be fixed by #51519.
