### ISSUE TITLE
Bullets do not inherit the material of the sleeve which is a part of them

### ISSUE THREAD

**Issue by Xomikadze** [CleverRaven/Cataclysm-DDA#49981]
# Is your feature request related to a problem? Please describe.
For example, for bullet 22lr, the material is indicated manually on the cartridge and it is displayed correctly in the game. But in 9x18 brass is not indicated in the materials and therefore only what is indicated is displayed, namely steel and gunpowder, although the sleeve is made of brass.

# Describe the solution you'd like
А function that allows you to associate materials for a bullet based on its components.

# Describe alternatives you've considered

# Additional context
![image](https://user-images.githubusercontent.com/68762218/125977993-6817592e-d492-4c39-ac90-73020102476f.png)
![image](https://user-images.githubusercontent.com/68762218/125978106-6253a1b4-7eae-4037-8b33-60a42c010569.png)
![image](https://user-images.githubusercontent.com/68762218/125978170-154b5385-5569-4c29-86b1-fcc89689db88.png)

**Comment by actual-nh** [comment]
In other words, until the bullet is actually fired (at which point it won't have the gunpowder or the brass), the entire bullet object contains steel, brass, and gunpowder?

**Comment by Xomikadze** [comment]
![Cartridge_cross_section svg](https://user-images.githubusercontent.com/68762218/125999672-0444067e-82c9-4781-a505-d75df7846f85.png)
The patron is a collection of all points from the diagram.
1 - bullet (steel)
3 - gunpowder
2, 4 - sleeve (brass)
5 - capsules (I think its material can be neglected at this moment)
So now, in order to indicate the material of the entire patron , you need to do it manually in json. Although we already have an indication of the connection with the sleeve and what it consists of. I want this to happen automatically.
I apologize if I do not understand what I write. English is not my native language.
