### ISSUE TITLE
Guns with detachable magazines cannot be reloaded with loose ammo

### ISSUE THREAD

**Issue by LaVeyanFiend** [CleverRaven/Cataclysm-DDA#49989]
### Describe the bug

Guns with detachable magazines refuse to be reloaded with loose ammo, requiring you to swap magazines or take out its magazine, reload the magazine, then put it back in.

### Steps To Reproduce

1. Spawn in a NATO assault rifle, a spare magazine, and loose 5.56.
2. Shoot once.
3. Attempt to reload with loose ammo, game refuses but spends the time anyways.
4. Attempt to reload using spare magazine, works.

### Expected behavior

Game simulates time spend to take out magazine, reload it, and reinsert without manually doing all steps.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 9658f3d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    Stats Through Kills [stats_through_kills]
]

### Additional context

Guns with internal magazines don't have this issue.

**Comment by LohTek** [comment]
In terms of a real AR15, SCAR, etc. It really isn't possible to reload the weapon without removing the magazine because the spring mechanism pops a round up into the bolt carrier ready to push it forward into the barrel, I am sure that you could reload it through the ejector port if you have very small fingers, and 30 minutes or so to fight with the magazine spring/bolt carrier but that really isn't feasible or recommended for the weapon.

![3d-animation-shows-how-an-ar-15-semi-automatic-rifle-works-1503677249_resize_md](https://user-images.githubusercontent.com/7308109/126037286-5287e254-61d4-4e2f-921c-5a747313d607.jpg)

**Comment by LohTek** [comment]
Actually upon review of reloading an AR/SCAR magazine it is completely and totally impossible to reload it through the ejection port. You must slide the bullet backward through the feed side of the front of the magazine, attempting to jam ammo into the ejection port would only cause damage to the magazine.

![opplanet-how-to-how-to-load-magazine-ar](https://user-images.githubusercontent.com/7308109/126037520-c93f791e-e04b-4883-8d84-79edfeea66e1.jpg)

**Comment by LohTek** [comment]
Rifles without detachable magazines use a tube style of ammunition feeder, which consists of an ammo tube, and a spring rod which looks like this under the barrel of the rifle:

![RifleTube](https://user-images.githubusercontent.com/7308109/126037750-6777a4c2-6edc-42fb-b84c-6652310a2c54.jpg)

This allows you to remove the spring rod and put more ammunition into it, this is mostly found on older rim fire rifles as it would be very dangerous to load a center fire rifle in this way; the ammunition could go off while being loaded.

![image002](https://user-images.githubusercontent.com/7308109/126037849-a8ca00ef-cae7-4f78-90b3-e5364163a918.jpg)

**Comment by Cenness** [comment]
Also you can't reload if there is no same XX rounds magazine in inventory

1. Spawn in a NATO assault rifle, a spare 60 rounds magazine, and loose 5.56.
2. Shoot once
3. Attempt to reload, rifle now has 60 mag
4. Attempt to reload again, game refuses
4. Spawn spare 60 rounds mag, attempt to reload, game shows only 60 rounds mags and loose ammo

Save - [West Puente Valley.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6841881/West.Puente.Valley.zip)
