### ISSUE TITLE
Seemingly random items keep lagging when I scroll over them and I can't even begin to figure out why

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#49987]
### Describe the bug

Well, as the title says, seemingly random items cause varying degrees of lag when I scroll over them, such as when I'm trying to pick them up or when I try to spawn them in. So far, the affected items I know of are cargo pants, glove liners, hiking backpacks, holsters, leather gloves, light gloves, boots, and hiking boots. Of these, the gloves seem to produce the most lag, while the cargo pants seem to produce the least.

### Steps To Reproduce

(See additional context, because this might be difficult/impossible for others to reproduce)

1. Find the items listed above
2. Try to pick them up

OR

Try to spawn in the items listed above

### Expected behavior

I expected that I would be able to scroll over the aforementioned items with no noticeable or significant difference in lag compared to other items.

### Versions and configuration

- OS: Windows
    - OS Version: Windows 8.1 Pro
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    XEAS [XEAS],
    Bootleg Walkers [Bootleg_Walkers],
    Gun Cotton [guncotton],
    DinoMod [DinoMod],
    PKs Rebalancing [PK_REBALANCE],
    Youkai Enemies [Youkai_Disco],
    Mining Mod [Mining_Mod],
    Mole Mutation [dig_a_tunna],
    More Survivor Stuff [more_survivor_stuff],
    Mythical Martial Arts [MMA],
    More City Locations [cityside],
    No Rail Stations [No_Rail_Stations],
    Compatible Nimian Manufacture Guns [NM_wpns],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    Magiclysm No Class Limit [magiclysm_no_class_limit],
    Mutation Changes [Mutation_Changes],
    Portable Autodoc [portable_autodoc],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Useful Helicopters [useful_helicopters],
    Arcana and Magic Items [Arcana],
    return_the_nut [return_the_nut],
    Hydroponics [hydroponics],
    Cooler Versatility [coolervers]

### Additional context

So... This time, I already tried to figure out if it was caused by mods, first by creating a new world with no mods loaded, then by creating new worlds with different mods loaded in order to see if any one of them was the cause.

In none of these new worlds did this problem occur. Not only that, but copying all of the settings of the world I'm currently playing in into another new world didn't result in the same problem occurring.

As such, I suspect that something must have happened since world/character creation to make these particular items laggy. However, I have no idea what that could possibly be, and I don't recall everything I've done so far since character creation.

**Comment by Inglonias** [comment]
A save file along with some idea of which items are causing the issue would be hugely helpful in diagnosing this issue.

**Comment by AmarinReyny** [comment]
> A save file along with some idea of which items are causing the issue would be hugely helpful in diagnosing this issue.

I'll upload it, then. Question, though: will people need to actually play through my save in order to figure out what's wrong, or will the file itself be enough? I just want to know if I need to upload the save file itself, or my entire CDDA folder, given the extensive modifications I've been working on to get things working the way I want them to (especially with older mods and obsoleted content I'd like to keep using from 0.E, but to a lesser extent making things easier for me (don't judge me too much, okay?)). Also, for some reason, Google Drive doesn't like map files, so is there another place I should upload to instead?

**Comment by actual-nh** [comment]
Well, given that there are often errors if you try restarting a game without all the mods that were used originally, the entire folder would probably be best. Try compressing (zipping, since you're on Windows) it and see if Google Drive is happier taking that.

**Comment by anothersimulacrum** [comment]
Copy your mods folder into your save directory, then upload your save directory.

**Comment by AmarinReyny** [comment]
> Copy your mods folder into your save directory, then upload your save directory. The game can read mods from mods folders in saves.

Eh... by the time I saw your reply, the 7z and rar folders (I decided to use both in case one didn't work for whatever reason) were one minute away from finishing their upload to Google Drive. That, and some of the files I've edited didn't come from mods.

That said, [here](https://drive.google.com/drive/folders/1G6gfGG6t-7YLo3AxtyjdMOnjMR9XQiK8?usp=sharing) it is. My apologies in advance for the error messages you're bound to get upon playtesting. For me, I press i three times to get to the main menu, then 34 times after loading the save (Newland/Arc, by the way).

**Comment by anothersimulacrum** [comment]
That ignoring of error messages is very probably why the game lags when you scroll over the items.

**Comment by AmarinReyny** [comment]
> That ignoring of error messages is very probably why the game lags when you scroll over the items.

I don't ignore them, I just don't want to have to wade through them all individually every single time I load my save. I've actually looked over them in the debug log, and I can't find anything about the laggy items in the debug messages. In addition, as stated before, this didn't happen when creating new worlds, regardless of mods used (or not used). As such, while I do plan on figuring out how to address the error messages when my health enables me to, I highly doubt that they have anything to do with this particular problem.

**Comment by anothersimulacrum** [comment]
What are the debug messages?
In saying you ignore them, I only intended to say you use the 'i'gnore function to make those messages not show up.

**Comment by AmarinReyny** [comment]
> What are the debug messages?
Too many to list. Between opening the game itself and the resumption of play in the save, there are 13,625 lines of text in the debug log, and I have yet to read through every individual message... Still, I searched for the items in question, and none of them showed up.

> In saying you ignore them, I only intended to say you use the 'i'gnore function to make those messages not show up.
Ah, sorry. I keep forgetting that's what the "i" stands for.
