### ISSUE TITLE
Deconstructing Chainlink Fences (built with pipes) yields pipe fittings

### ISSUE THREAD

**Issue by definitelynotklip** [CleverRaven/Cataclysm-DDA#49994]
### Describe the bug

Chainlink fences can be found naturally generated with many buildings, so it is okay to assume those are industrial-made fences built with pipe fittings. However, it is possible to construct them as well (through the [`*`] Construction menu). Doing so requires nothing but pipes and wires.

If you then [`s`]mash the fences you built, they will yield pipe fittings which then cannot be [`B`]utchered, [`(`] Disassembled or otherwise crafted into regular pipes, resulting in a loss of material.

### Steps To Reproduce

1. Get 6 pipes
2. Start building a Chainlink Fence ([`*`] Construction menu).
3. After the first stage is complete, grab a tool or a weapon and [`s`]mash the fence you made.
4. The fence may drop some pipes, however it will also drop a pipe fitting resulting in pipe loss.

### Expected behavior

The constructed fences should be dropping 6 (or less) pipes, no pipe fittings. Fences can drop pipe fittings if a recipe to deconstruct them into regular pipes is introduced.

### Versions and configuration

- OS: Windows 10 Pro, Version 1909
- Game Version: 0.F-7b88ade (Experimental, July 15th)
- Graphics version: Tiles
- Ingame language: System language [English]
- Mods loaded: dda, cbm_slots, OG_Drugs, speedydex, stats_through_kills, StatsThroughSkills, stamina_regen_buff.

**Comment by anothersimulacrum** [comment]
The construction recipe should require pipe fittings.

**Comment by definitelynotklip** [comment]
> The construction recipe should require pipe fittings.

This is also a good alternative to my proposed solution.

**Comment by casswedson** [comment]
Fixed by #50003
