### ISSUE TITLE
0.F stable Humvee has jerry can with diesel, but runs on JP8

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#50008]
### Describe the bug

As the title says, the fuel used and spare fuel carried didn't match.

### Steps To Reproduce

This is my first JP8 car examined...

### Expected behavior

If spare fuel is carried, it should match the fuel the vehicle uses.

### Versions and configuration

-- OS: Windows
    - OS Version: 10.0 2004
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap]
]

### Additional context

I expect the introduction of JP8 and conversion of vehicles to use it didn't (fully?) consider spare fuel carried, i.e. the loot tables weren't updated.

(As an aside, this new bug report format is a HUGE improvement over the old one!)

**Comment by anothersimulacrum** [comment]
These should be something other than `fuel_diesel`.
https://github.com/CleverRaven/Cataclysm-DDA/blob/b47a3c0325bb9c26c39b0215354a8532cc2e154f/data/json/vehicles/military.json#L452
https://github.com/CleverRaven/Cataclysm-DDA/blob/b47a3c0325bb9c26c39b0215354a8532cc2e154f/data/json/vehicles/military.json#L537
https://github.com/CleverRaven/Cataclysm-DDA/blob/b47a3c0325bb9c26c39b0215354a8532cc2e154f/data/json/vehicles/military.json#L614
