### ISSUE TITLE
Attempting to bulk deconstruct copper wire after you previously worked on it causes it to instantly finish and crash the game when picked up

### ISSUE THREAD

**Issue by Alexalmighty502** [CleverRaven/Cataclysm-DDA#50014]
### Describe the bug

See Title

### Steps To Reproduce

1. Get more than 1 copper wire.
2. Attempt to deconstruct it.
3. Cancel the task halfway through.
4. Resume deconstructing it.
5. Notice that it finishes instantly even if you are attempting to deconstruct 1000 of them.
6. Notice that there is only a single piece of copper.
7. Attempt to pick up the copper.
8. The game will instantly crash.

### Expected behavior

To resume deconstructing it normally and to pick up the result without crashing.

### Screenshots

N/A

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 20H2
- Game Version: b47a3c0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    No Freeze [no_freeze],
    DinoMod [DinoMod],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    Crazy Cataclysm [crazy_cataclysm],
    Crazy Cataclysm - UndeadPeople Tileset [CrazyCataclysmUDP],
    DinoMod - UndeadPeople Tileset [DinoModUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts [MMA],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Animatronic Monsters - UndeadPeople Tileset [AnimatronicsUDP],
    C.R.I.T Expansion Mod [crt_expansion]
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6835485/debug.log)
Oddly even though the game crashes nothing is written to the crash file (it was last edited in 2020) so it is omitted

**Comment by WelpThatWorked** [comment]
I'm not getting the crash on my end, but I've figured out that the number of wires being disassembled isn't saved anywhere in the disassembly item, so when resuming the moves_left gets set to something low enough to appear instant, and it gives you a copper item with zero charges.
