### ISSUE TITLE
items generating items

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#50011]
# Is your feature request related to a problem? Please describe.
there is a fair few situations were an item destruction/removal generating new items would be a good idea.

# Describe the solution you'd like
when an item gets "removed" it generates some new items
common ways it gets removed:
- eaten (fruits--> seeds)
- rots completely (corpse --> skeleton/bones)
- used in crafting (fruit for fruit wine generating seeds)
- destroyed due to damage, (weapons--> scrap metal and splintered wood), (large rock -->rocks)
- crafting like were you craft an "in progress" thing like bread that auto turns to bread when done (liquids could need to be activated to give items)

# Describe alternatives you've considered
- conditional byproducts
- more than one byproduct possible

# Additional context
- there should probably be a flag that suppresses item generation like crafting seeds from fruit

**Comment by ZhilkinSerg** [comment]
Byproducts for recipes already exist - search for "byproducts".

Items that change over time already exist - search for "delayed_transform".

**Comment by actual-nh** [comment]
> crafting like were you craft an "in progress" thing like bread that auto turns to bread when done (liquids could need to be activated to give items)

The first is under consideration. What do you mean by the second (re liquids)?

**Comment by robotic-gamer** [comment]
by byproducts I meant the ability for multiple different byproducts and the ability for the byproducts to be conditional on the ingredients like seeds from the fruit used etc.

requiring activation so you can tell the game were to put the liquids. that or the game just prompts you out of the blue for what to do. or you reserve a container in advance.
