### ISSUE TITLE
massive debug log

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#50017]
### Describe the bug

my debug.log file in config is about 30GB, while debug.log.prev is about 21GB

### Steps To Reproduce

no idea

### Expected behavior

there really should be a cap for log files

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 1f0b625 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Simple_additions [simple_additions],
    C.R.I.T Expansion Mod [crt_expansion],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    Stats Through Skills [StatsThroughSkills],
    Bionic Slots [cbm_slots]
]

### Additional context

only error I am encountering is about it not understanding the overmap tiles
I deleted the log files then started playing again for 10 seconds. attached is the debug.log
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6835621/debug.log)
It seems that an error is occurring constantly. it causes no in game affect. the only observed affect is the ballooning debug.log file size.

**Comment by anothersimulacrum** [comment]
I've been doing some development which involved me setting overmap terrain with no mapgen defined for it (and me ignoring the problem out of laziness), and I can confirm this issue.

**Comment by actual-nh** [comment]
What's the best way to avoid triggering this? My main drive has less than 45 GB free as it is.

**Comment by robotic-gamer** [comment]
it seems to happen slow enough that keeping an eye on the debug.log file size and deleting it when it becomes a problem is a viable solution for the time being. 
the fact that I am the first to mention it may mean its just a problem with my version.
you only have this problem if you encounter an error that looks like:

 DEBUG    : invalid overmap terrain id "ot_forest"

 FUNCTION : int_id<T> generic_factory<T>::convert(const string_id<T>&, const int_id<T>&, bool) const [with T = oter_t]
 FILE     : src/generic_factory.h
 LINE     : 468
 VERSION  : 1f0b625

**Comment by robotic-gamer** [comment]
just tested a better solution that seems to work. Just create a an empty debug.log file in config and deny everyone permission to edit it. that way the game is blocked from writing to the debug.log.

**Comment by actual-nh** [comment]
> just tested a better solution that seems to work. Just create a an empty debug.log file in config and deny everyone permission to edit it. that way the game is blocked from writing to the debug.log.

Point; that will work unless you actually want (some of) the debug.log file output. (I need to check into debug message/log filtering - IIRC there was something like that?)
