### ISSUE TITLE
Gracken should be less cowardly

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#50022]
### Describe the bug

In 0.F stable dead humans found when walking around tend to be recently risen rather than lying around on their dropped belongings. Gracken, for whatever reason, tend to hang out among those bodies, which worked reasonably well in 0.E2 stable when the dead humans remained dead. Now, when they reanimate, I see the hordes of newly risen chase the Gracken all over the place, rather than it keeping them down.

### Steps To Reproduce

Find a Gracken "guarding" its field of death. See the weird chase when the newly risen chase their guardian.

### Expected behavior

Gracken should probably keep whacking "their" bodies back into immobility as soon as they rise, while still being peaceful/fearful towards more competent opponents (such as new survivors).

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap]
]

**Comment by Xaleth** [comment]
Confirmed in 0.F stable, zeds are indeed hostile towards grackens

**Comment by actual-nh** [comment]
The question is not so much them being hostile toward grackens, as gracken possibly needing to be a bit braver... with the oddity that they already have morale of 100... ah. But aggression of 0. Perhaps give them aggression, say, 5 and an anger_trigger of PLAYER_WEAK (which is actually more like HOSTILE_WEAK)?

**Comment by Vendidurt** [comment]
I hope this change doesnt interfere with an upcoming challenge i have in mind - Gracken Refuge Habitat. Please dont make them attack the player.
