### ISSUE TITLE
Asking companion to read book displays books according to PC skills, not companion skills

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#50020]
### Describe the bug

You can ask a companion to read a book, and the UI correctly lists the books within reach of the companion (rather than the PC). However, the books are displayed according to the skills possessed by the PC rather than the companion, which makes it harder than it should be to select an appropriate book.

### Steps To Reproduce

Get a companion and a bunch of skill training books. Ask the companion to read a book, and see that the display is based on the PC's current skills, rather than the companion's.

### Expected behavior

The selection shows the current skill level of the companion, the companion's reading time, and whether the companion is capable of reading and learning from the books.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap]
]

### Additional context

I'd expect the screen has hard coded the PC as the subject rather than being fed the character to be used as the subject.

**Comment by MarlossCDDA** [comment]
Could you clarify what about the display is based on the PC? Since https://github.com/CleverRaven/Cataclysm-DDA/pull/48662 was merged, everything except the colors of the books ought to be based on the reader's skills - is there something other than the colors that you think is wrong?

**Comment by PatrikLundell** [comment]
Re-checking the display, the only info except the names of the books is the colors of them, and the colors are based on the PC's skills. The selection of which books are present in the list is correct.

The rest of the info visible on the display when the player selects a book to read is absent (adding it would be an enhancement, but not a bug correction). I mentally carried over the image that reading time, current/max skill, etc. was present, but it isn't.

Thus, in short: It's the color, only.

**Comment by MarlossCDDA** [comment]
Ah, looks like you're running a version of experimental from 16 hours before my PR got merged - if you update CDDA you should see some better behavior :)

**Comment by PatrikLundell** [comment]
I'm not running experimental, but 0.F stable. I didn't think to state that as I was more or less required to generate the "Versions and configuration" info. I'll try to remember to state that explicitly in the future, to make it easier for to see that than using the number alone. Happy to hear it has been improved, and sorry for the confusion.

**Comment by actual-nh** [comment]
#48662 noted as 0.F backport candidate.
