### ISSUE TITLE
Radio Car Box can't be disasembled.

### ISSUE THREAD

**Issue by skoormit** [CleverRaven/Cataclysm-DDA#50025]
### Describe the bug

I found a radio car box.
I have it in my inventory.
The item description says "...Disassemble to unpack and enjoy."
But when I (e)xamine the item, the (D)isassemble option is grayed out.
If I try to (D)isassemble anyway, the message log says "You cannot disassemble this."

### Steps To Reproduce

Try to disassemble a radio car box.

### Expected behavior

I expected that I could disassemble the radio car box to acquire the contents, like with a First Aid Kit Box.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 2fe7328 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by PatrikLundell** [comment]
The radio car box I found in 0.F stable has a car, control, and 3 batteries in the box. The text in that version says "An RC car, with radio-control and batteries included! Unpack and enjoy."
Unpack, not disassemble. i.e. it uses the (new) container system, like the first aid kit now does.

It seems your version is 9 days older than 0.F stable, if the game version link is to be believed. I would have expected the first aid kit to be converted to a container well before your version.

**Comment by skoormit** [comment]
I have found several First Aid Kit Box items in this version. They all work fine--like you said, they are just normal containers.
This Radio Car Box does not act like a container. It does not show a capacity or list any contents or any pockets.

It is true that I had not yet updated to stable. I have done so now, but the problem persists. Granted, that could be because the item had already been created.

**Comment by Qrox** [comment]
The obsolete `radio_car_box` item mentions disassembling in its description, while `rc_car_box` (the current radio car box) mentions unpacking. We should add a migration entry for `radio_car_box` to `rc_car_box` instead (and perhaps add radio car to it when migrating).

**Comment by Night-Pryanik** [comment]
I can't find `radio_car_box` in game files anymore as of 0.F-5881, so I think it's safe to close the issue.
