### ISSUE TITLE
Unknown error with large quiver leaves save critically compromised

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#50029]
### Describe the bug

In the attached game file, the character is wearing, among other things, a large quiver (data ID `quiver_large`) with 17 simple metal arrows in it. Doing *anything* with this quiver results in a highly-unstable condition where the game will continue to run until it is saved, either manually or automatically. This triggers a hard crash; not hard enough to throw up the segfault dialog, but too hard to leave anything in the `.log` files.

When I say "anything," I mean "anything" -- even using the debug menu to delete the item sets up the crash.

I suspect there's some particular data value or something associated with that quiver.

This bug was resolvable by manually removing the `large_quiver` from the .SAV file and ignoring the resulting deserialization error.

This save file belongs to `6apa6ax` on the development Discord; if further details are required, please coordinate with them.

### Steps To Reproduce

1. Load attached save.
2. Do anything at all with the large quiver the character is wearing.
3. Attempt to save.
4. Profitn't.

### Expected behavior

I expected no crash upon saving after manipulating the quiver.

### Versions and configuration

Testing performed on the following environment:

- OS: Windows
    - OS Version: 21H1 (Build 19043.1110)
- Game Version: 21ca15e [64-bit] (`2021-07-18-1457`)
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded:
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]

### Additional context

[Ivydale.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6836482/Ivydale.zip)

**Comment by mqrause** [comment]
Not sure what exactly it is, but the `item_location` of the arrows seems to be messed up (`container->get_item()` in `item_location::impl::item_in_container::calc_index()` returns a nullpointer). Dropping the arrows and picking them up again fixes that.

Looking at the history there's "you unload your composite bow", so maybe it's coming from that?

**Comment by ToxiClay** [comment]
> Not sure what exactly it is, but the `item_location` of the arrows seems to be messed up (`container->get_item()` in `item_location::impl::item_in_container::calc_index()` returns a nullpointer). Dropping the arrows and picking them up again fixes that.
> 
> Looking at the history there's "you unload your composite bow", so maybe it's coming from that?

How in the world did you track that down?

**Comment by mqrause** [comment]
I loaded it up with debugger and then went through the callstack on the crash.

**Comment by satheon49** [comment]
I tested the original save with and without #50525 and it no longer crashed with the PR changes. So this issue can probably be closed.

**Comment by ToxiClay** [comment]
Closing due to fix implemented in #50525.
