### ISSUE TITLE
Cannot reload underslung shotgun and other attached guns.

### ISSUE THREAD

**Issue by shacknetisp** [CleverRaven/Cataclysm-DDA#50031]
### Describe the bug

When using an underbarrel shotgun, the option to reload the parent gun with shotgun ammunition appears but it does not reload, instead displaying the message e.g. `Can't reload the NATO assault rifle+1`.

This also affects the 14-round tube shotgun (you can only load one of the magazines) and the Masterkey.

It is possible to reload the underslung shotgun before it is attached every time, then unattach when it needs to be reloaded again, but this is quite tedious; and this doesn't work for the 14-round tube shotgun anyway since its second magazine is built in.

### Steps To Reproduce

Make a player with a NATO assault rifle and install an underslung shotgun. Give yourself 00 shot. Try to reload the gun with it. The error will be displayed instead of reloading.

### Expected behavior

Attached guns should be reloadable.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.2 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-790-ga17ccb1888 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

May be related to #49989

**Comment by actual-nh** [comment]
Or to #50157.
