### ISSUE TITLE
Streamline the repair interface to show repair/improvement/damage chance during item selection

### ISSUE THREAD

**Issue by DalenTalas** [CleverRaven/Cataclysm-DDA#50048]
# Is your feature request related to a problem? Please describe.
When attempting item repairs, the item to be repaired needs to be selected (by hitting Enter) in order to see the repair / improvement chance. From there, you need several key presses to get back to the selection menu if the odds are not in your favor. This is frustrating when trying to find an item to tailor/fabricate on with decent chances of success. More frustrating when there's a pile of raggedy clothes/armor nearby.

# Describe the solution you'd like
Rework the repair interface. In my vision of things, the selection panel you get after (a)ctivating the repair tool:
- MUST display the percentage chance of repair / improvement / failure next to each item.
- MUST use dashes to indicate an item that cannot currently be repaired (no material, etc.). EDIT: using NONE as in the example below is actually much better. So the previous should be read as "MUST indicate that an item currently cannot be repaired".
- SHOULD, if possible, indicate the type of material used in the repair and the quantity  available.
 
I posit that something similar to the (E)at menu should work very well here.

# Describe alternatives you've considered
This will likely be a big interface redesign, and the current one does serve its purpose with reasonable effectiveness.

**Comment by WelpThatWorked** [comment]
Something like this?
![image](https://user-images.githubusercontent.com/9769385/127089320-434222fc-da0c-4b3b-8ff0-5e7d62aa8211.png)
I haven't figured out the dashes part or how to get it to display in a single column, so that it isn't so wide.

**Comment by DalenTalas** [comment]
Perfect!

I'm assuming exceptionally high damage chances (above 10%, if actually possible) are highlighted in red? Maybe consider highlighting success chances in a similar way (light / dark green). Although I have doubts whether that would clutter the interface or not.

**Comment by WelpThatWorked** [comment]
I experimented with a few different things for color, but I'm not entirely set on one scheme yet. When I tried coloring based on if it was in a certain range, I felt unsure it was sending the right message, though I might just have been using the wrong percentage thresholds. What you see in the screenshot is "yellow if damage chance is greater than improve chance", though maybe I should make both numbers yellow in that case?

**Comment by anothersimulacrum** [comment]
Success and damage both red if there is no chance to repair, damage yellow if it's greater than repair, repair light green if there is no chance of damage?

**Comment by WelpThatWorked** [comment]
The only thing I'm worried about is that, even if the chance to improve is 0, you can still "practice" the action (to improve the relevant skill?) and I worry using red might make some players think they can't do anything with the object. Maybe success yellow if zero, damage yellow if greater than success, both light green if damage zero and success greater than zero?
