### ISSUE TITLE
Make bundling flexible

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#50047]
# Is your feature request related to a problem? Please describe.
It's a pain to collect (long) stout branches, because with the "new" inventory system you can only carry them in the hand (unless you happen to have gotten hold of a golf bag or a suitable vehicle, which you probably haven't if you're looking for low tech branches). You can tie them up in a bundle, but that's really only reasonable when you find a forest patch where a lot of them are gathered within a single tile so you can drag them together before bundling them up, since a bundle requires a fixed number of items.

# Describe the solution you'd like
Modify the bundling recipe logic to bundle up to the maximum number of the item. That way you can grab the first branch, make a two branch bundle when you encounter the second one, disassemble and reassemble into a 3 branch bundle when you encounter the third one, etc.
This would also alleviate the current problem that bundles have to be kept sufficiently small to actually be created early on, but with you (potentially) ending up with a pile of bundles later on.

# Describe alternatives you've considered
Allowing for bundling of similar, but not identical, items, such as bills of differing denominations, or mixing long and regular stout branches.

Reimplement bundles as spontaneously constructed/deconstructed containers with restrictions on what items can be placed in them.

# Additional context
This might be tricky to implement, as the crafting system doesn't seem to support variable number of items, optional items, or even collection of different items from the same group (such as making something including eggs to take your two chicken eggs and 3 goose eggs).
Thus, this seemingly simple suggestion might actually require fairly substantial modifications of the crafting system.
Also note that bundle items would have to keep track of what they're bundling, as they can't have fixed deconstruction recipes.

**Comment by DalenTalas** [comment]
Alternate idea.

Make rope containers able to accept multiple items.

Make wrappers (a)ctivateable to turn into "package" / "bundle" item that tracks its original contents as components, and can then be (a)ctivated or disassembled into its components and a wrapper.

Algorithm would be something like this (though me not being familiar with how disassembly is handled, this is like Not How It Works):

on (a)ctivation of wrapper:
     new package created
     package placed into player's inventory
     wrapper's contents copied into package's composition
     wrapper's total weight and volume copied into package's weight and volume
     wrapper and its contents deleted from player's inventory

**Comment by mqrause** [comment]
An easy solution would be to make a low tech container item that can hold sticks (and maybe other similarly formed items). Then you can wield that container and fill it with sticks you find.

**Comment by AccountAlias** [comment]
Alternatively, since that isn't currently implemented, you can `\` haul multiple items on the same time as you

**Comment by PatrikLundell** [comment]
Yes, it's possible to haul stuff across limited distances, but when roaming through the forests hunting for branches it's not really practical.
