### ISSUE TITLE
Navigatin overmap with mouse always centers cursor 1 tile left of the point you select

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#50059]
### Describe the bug

Mouse-clicking a point on the overmap always moves to a point 1 tile to the left/west. Happens both in tiles and ascii overmap.

### Steps To Reproduce

Start a game, open overmap, try clicking somewhere, see it focus on the wrong tile.

### Expected behavior

OM focusing on the tile which was clicked.

### Versions and configuration

- OS: Windows 7
- Game Version: 3c14227 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills],
    Bionic Professions [package_bionic_professions]
]

### Additional context

![cataclysm-tiles_2021_07_19_18_27_51_411](https://user-images.githubusercontent.com/56833396/126154159-3fe6b121-7c8a-43f0-bc7f-cdfa0087b467.png)

**Comment by molkero** [comment]
One tile north for me when windowed, if I maximize the window it changes to one tile west.

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 21.1.0; Codename: Pahvo; 
- Game Version: 0.F-852-g9dc329cd03 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Bionic Slots [cbm_slots]
]

**Comment by ToxiClay** [comment]
Cannot confirm behavior on any of 21ca15e or 3c14227 or 9dc329c.

Clicking a tile on the overmap focuses directly on the clicked tile, as expected.

Can you try pulling a clean copy of the game and trying again?

**Comment by GGgatherer** [comment]
Nope, still happening in db097c5. Same thing, 1 tile to the left (or a cursor to the right): clicking on character's @ shifts view 1 tile left, clicking 1 tile to the right of @ doesn't result in any changes.

**Comment by ToxiClay** [comment]
Uhhhh. I can't confirm this on db097c5 either. It acts as expected.

**Comment by GGgatherer** [comment]
Updated to latest experimental 7fae1b5, fiddled with OM tilesets. It gets even worse.
Clicks to the side now go about 2x as long as they should be, i.e. you click 3 tiles to the right, you go 6 tiles to the right instead. It pretty much does not depend on the tileset as far as I can tell. Maybe the multiplier is slightly different, can't say.
In-place clicks work slightly different depending on different OMtilesets. In some they work fine. In others, graphical representation of current tile seem to be misaligned with its actual position on screen - so they can intersect in top-right corner  (ultica), top-left corner (asciitiles), or not at all  (in Retrodays case, the "safe place" is actually in the SE corner of the tile adjacent to the NW).

**Comment by olanti-p** [comment]
Possible fix: https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1101/commits/3ac5fe16075b3916c191b077254a8ddceb343599
