### ISSUE TITLE
Unable to add bleach to bleach tank

### ISSUE THREAD

**Issue by AdamChirnside** [CleverRaven/Cataclysm-DDA#50078]
### Describe the bug

DEBUG    : tried to put an item (bleach, amount 1) in a container (metal_tank) that cannot contain it

 FUNCTION : int item::fill_with(const item&, int, bool, bool, bool)
 FILE     : src/item.cpp
 LINE     : 9274
 VERSION  : 7e05d34

### Steps To Reproduce

1. Find bleach in the wild (e.g. looting a house)
2. Make bleach using electrolysis method
3. Try to get them into the same container, especially any vehicle tank

### Expected behavior

Ability to supplement looted bleach with fabricated

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 7e05d34 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Disable NPC Needs [no_npc_food],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Alternative Map Key [alt_map_key],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    No Rail Stations [No_Rail_Stations]
]

**Comment by actual-nh** [comment]
This has come up before with water; I had thought at least _some_ of that was fixed... sigh.

**Comment by ToxiClay** [comment]
Oh, this old chestnut again.

**Comment by Resok** [comment]
I was able to fix this locally by simply adding "NUTRIENT_OVERRIDE" to the bleach item flags in JSON (similar to water_clean).

After looking at the data in the save game this is caused by bleach having components stored, which differentiates it as a different object than other bleach from houses, etc. which do not have components.
