### ISSUE TITLE
America needs lobster

### ISSUE THREAD

**Issue by LyleSY** [CleverRaven/Cataclysm-DDA#50077]
# Is your feature request related to a problem? Please describe.
Although lobster is a defined monster and recipes for it exist in the game, it spawns very rarely if at all. This is the most unrealistic thing about modern CDDA content

# Describe the solution you'd like
Code to allow lobsters and less important fish to spawn in filled aquariums that have their preferred water type

# Describe alternatives you've considered
Hacky terrain kluges like at the zoo

# Additional context
Lobsters are delicious. Inspired by #49533

**Comment by Zireael07** [comment]
Closed by #56121 ?

**Comment by LyleSY** [comment]
I don't think it's closed because it's still impossible to spawn a lobster or fish in a filled aquarium, but that definitely helped
