### ISSUE TITLE
Spellcasting doesn't draw targets with disabled tiles

### ISSUE THREAD

**Issue by Vollch** [CleverRaven/Cataclysm-DDA#50082]
### Describe the bug

Spellcasting doesn't draw targets with disabled tiles. With single target spells it hides targeted mobs, showing trace to it. With blast spell it shows trace to center of blast but not affected area. Pure aoe spells shows nothing at all. (Screenshots below)
I suspect it caused by this(https://github.com/CleverRaven/Cataclysm-DDA/commit/789c7a468973a01d8960be4566c78193228c772a#r53658510) change, but don't have have building environment to check and confirm it.

### Steps To Reproduce

1. Disable tiles
2. Create world with Magiclysm
3. Start as Shock Officer (Or some other character with AOE spell)
4. Try to cast Windstrike or Jolt
5. Affected area rendered as empty terrain. No highlighting to see bounds; if there's any monsters in affected area - they're rendered invisible.

### Expected behavior

I expect to see where i'm shooting

### Screenshots

![image](https://user-images.githubusercontent.com/544763/126328543-c2831320-fc5e-47af-9865-359703bc2454.png)
![image](https://user-images.githubusercontent.com/544763/126328619-51ceb871-b0e1-4975-a9c9-5ca9bd6c4a3a.png)
ASCII vs Tiles, targeting same zombie with Windstrike.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: a27f801 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm]
]

**Comment by hexagonrecursion** [comment]
The area of effect can be seen in the dark (e.g. at night):
![see](https://user-images.githubusercontent.com/52621858/128663188-4cf29a9c-f235-4a82-b51a-207430bec9f9.png)
but can not be seen when it's brightly lit:
![no-see](https://user-images.githubusercontent.com/52621858/128663186-2c265654-30c4-4e27-9854-75b6e374840d.png)

**Comment by actual-nh** [comment]
Ping: @KorGgenT?

**Comment by A-Powerful-Mage** [comment]
This remains a problem. Please fix this.
