### ISSUE TITLE
Applying sewing to "clean" leather gloves with "not clean" enough raw material: You don't have enough leather patches to do that. Have: 16, need: 1

### ISSUE THREAD

**Issue by hal2100** [CleverRaven/Cataclysm-DDA#50094]
### Describe the bug

Applying a sewing kit to bad fitting "clean" leather gloves with "not clean" enough raw material: You don't have enough leather patches to do that. Have: 16, need: 1

### Steps To Reproduce

1. Have enough filthy leather patches in inventory, but no clean
2. Have clean leather gloves in inventory
3. Apply sewing kit to gloves

### Expected behavior

I expect the game to tell me that I have no clean raw materials available, only filthy.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by actual-nh** [comment]
Note to whoever fixes it: Please use positional parameters (e.g., without any bugfix for the above, `_( "You don't have enough %1$s to do that.  Have: %2$d, need: %3$d" )`. This makes it much easier on the translators (that way, they can rearrange the parameters to fit the language's ordering for such things).

**Comment by Night-Pryanik** [comment]
Resolved by #69776.
