### ISSUE TITLE
CRIT EM vest disappears after turning on

### ISSUE THREAD

**Issue by stasalcatraz** [CleverRaven/Cataclysm-DDA#50095]
### Describe the bug

Lost CRIT EM vest after turning it on

### Steps To Reproduce

1. Start a game as CRIT Spec Ops by helicopter crush scenario.
2. Turn a CRIT EM vest on.
3. Item disappears.

### Expected behavior

CRIT EM vest (off) turns into CRIT EM vest (on)

### Versions and configuration

- OS: Ubuntu 20.04
- Game Version: 0.F Experimental b69f40
- Graphics version: Tiles
- Ingame language: tested at Russian, English
- Mods loaded: "dda",  "no_npc_food",  "package_bionic_professions",  "blazeindustries",  "magiclysm",  "crt_expansion",  "alt_map_key",  "MMA",  "No_Rail_Stations",  "Graphical_Overmap",  "fuji_mpp",  "speedydex",  "StatsThroughSkills"

**Comment by actual-nh** [comment]
Ping: @Salty-Panda, IIRC?

**Comment by Salty-Panda** [comment]
Probably the known bug, will check/fix later today
