### ISSUE TITLE
Exodii Quadrupeds shoot fire at neutral avatars

### ISSUE THREAD

**Issue by gisaku33** [CleverRaven/Cataclysm-DDA#50103]
### Describe the bug

When approaching Exodii quadrupeds they will repeatedly shoot fire at you without warning or becoming hostile, and without any message in the log.

### Steps To Reproduce

1. Approach Exodii quadruped without attacking
2. Be lit on fire, see no log

### Expected behavior

Not being lit on fire without warning

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 7d23809 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA],
    Stats Through Kills [stats_through_kills],
    Useful Helicopters [useful_helicopters],
    SpeedyDex [speedydex],
    Aftershock [aftershock]
]

### Additional context

@I-am-Erk asked for a ping

**Comment by I-am-Erk** [comment]
Probably they should just not have a flamethrower, blasphemous though that sounds

**Comment by logros13** [comment]
not only fire, their gun too. i tried to run up to one wanting to check out the "friendly new trader faction" and it promptly blew my head off... -.-

It was fighting zombies at the time if that is relevant but i never got between them so i don't think it could be crossfire.

**Comment by GoLoT** [comment]
AFAIK monsters become hostile against any other factions when attacked or provoked. Assuming the exodii are monsters and not NPCs, a zombie attacking them should turn them hostile even to you. Same as wild life ignoring you until a zombie decides to poke that moose over there and suddenly your day 2 character is pushing up daisies.

If they showed up as neutral/ignoring/whatever and still attacked you, then it's a bug.

**Comment by actual-nh** [comment]
They turn hostile against any faction they aren't NEUTRAL or FRIENDLY to; exodii monsters are BY_MOOD to humans. (Guaranteed attack, and prioritization at that, is HATE, which exodii monsters have vs zombie, fungus, triffid, and mi-go.)

**Comment by I-am-Erk** [comment]
The quadrupeds are a scout unit, if you get too close to them they will attack. I believe it's in their description.

**Comment by logros13** [comment]
"This enormous quadrupedal robot seems to be cobbled together from parts, most of them unfamiliar to you. It moves with a heavy, oddly graceful gait, its footsteps leaving shallow craters behind. It bristles with an arsenal of weaponry, but doesn't seem in a particular rush to target you."

@I-am-Erk It says that they are armed but "doesn't seem in a particular rush to target you." If anything reinforced my belief that it was non-hostile.

**Comment by I-am-Erk** [comment]
Fair enough. I had an older draft that made it clearer they were risky bizness, I must have taken it out for some reason. I will fix that along with the flamethrower.

**Comment by Marrim** [comment]
It seemed like by design to me. Non-hostile but if you get too close to the supplies, you get roasted.
They're automated sentries after all, aren't they?
