### ISSUE TITLE
UI:Improve zone management by indicating location of existing zones when in the zone management menu

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#50110]
# Is your feature request related to a problem? Please describe.
When I want to sort things I typically want to place zones side by side with no overlap. However, It's a bit tricky as you have to remember where the existing zones are when defining the location of a new one. While you can browse the list of existing zones and get an indication where they are, you still have to remember all of the relevant ones, and potentially count tiles when trying to cover an area in side by side zones.

# Describe the solution you'd like
Indicate where existing zones are by outlines similar to the one you get when defining a new zone/browsing an existing one, but with a different color, and possibly a third color to indicate overlapping tiles.

# Describe alternatives you've considered
- A toggle to allow you to show zones permanently (in addition to showing them only while managing zones).
- Different colors and/or line patterns depending on the zone type, but that probably just gets messy and confusing.

# Additional context
The current system works, so it's not broken (and sort zones as such are very useful, as is the auto sorting command).

**Comment by Qrox** [comment]
Showing each zone with a differently colored rectangle would be nice, but that needs to bypass the current tile-based drawing logic (or, with some hack, utilize the connection of tiles, similar to how blood and so on are drawn).

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
