### ISSUE TITLE
Game unable to load any glyphs.

### ISSUE THREAD

**Issue by l3lb0t** [CleverRaven/Cataclysm-DDA#50115]
### Describe the bug

Upon booting a github clone version, none of the glyphs loading, meaning there is no text displayed anywhere in the game.

### Steps To Reproduce

1. Clone the game off of github using MYSY2
2. Boot the game from the MYSY2 console

### Expected behavior

I expected glyphs to be loaded, as that's what happens in other versions of the game I have installed (10.C and 10.E).

### Screenshots

![image_2021-07-21_174709](https://user-images.githubusercontent.com/77447558/126527350-23b8e2e8-3204-4751-9909-58d2d73e56aa.png)
![image](https://user-images.githubusercontent.com/77447558/126527429-7a8660fc-b042-4ee2-b379-7b0bd552c487.png)

### Versions and configuration

- OS: Windows 10
- Game Version: Unknown. Presumably 0.F-2021-07-21-1542
- Graphics version: Tiles (edited)
- Ingame language: English (United Kingdom)
- Mods loaded: Unknown.

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6857550/debug.log)

**Comment by actual-nh** [comment]
Curses (non-tiles) generally doesn't work on Windows, and isn't supported. (A few people have managed to get it to run with considerable work, but not reliably AFAIK.)

**Comment by l3lb0t** [comment]
> Curses (non-tiles) generally doesn't work on Windows, and isn't supported. (A few people have managed to get it to run with considerable work, but not reliably AFAIK.) EDIT: Or is the "Graphics version: Terminal" incorrect above?

I'm not entirely sure. How would I check?

**Comment by anothersimulacrum** [comment]
Your screenshot has tiles, you are almost certainly using SDL.

**Comment by actual-nh** [comment]
> Your screenshot has tiles, you are almost certainly using SDL/Tiles, not Curses.

Oops. Good point.

**Comment by actual-nh** [comment]
Ping: @I-am-Erk?

**Comment by actual-nh** [comment]
What db_path are you using? Did you follow the directions in doc/COMPILING/COMPILING-MSYS.md?

**Comment by I-am-Erk** [comment]
I am having the same problem, yes. I haven't solved it yet, although I also don't seem to be able to solve it building 0.F so I'm not sure what is happening.

**Comment by l3lb0t** [comment]
> What db_path are you using? Did you follow the directions in doc/COMPILING/COMPILING-MSYS.md?

I did follow the directions, as far as I know. I'm using the path  /C/Cataclysm-DDA

**Comment by jani-laakso** [comment]
Possible workaround described here: [https://github.com/CleverRaven/Cataclysm-DDA/issues/50149](url)

**Comment by l3lb0t** [comment]
> Possible workaround described here: [https://github.com/CleverRaven/Cataclysm-DDA/issues/50149](url) (although this is for MacOS, but in short, try modifying your fonts.json file)

The link doesn't seem to be working, how are you supposed to modify the file?
