### ISSUE TITLE
Implementing summer coats for Fur mutations

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#50119]
I saw this suggestion in an issue and I was thinking I could do this kind of thing now through effects on condition.   My thought process would be to set Fur traits to have an alternate trait based on the time of year it is.    The alternate trait would be the summer coat which would be less warm but also provide less benefits.   I am writing this up but don't know for sure when I'll have time to implement, the further I get into this feature discussion.

[] Post-threshold fur mutations that allow shedding in the summer -- Fur is extremely punishing to have right now due to the excessive warmth it provides. That's a fine downside for a pre-threshold mutation, but it would help make post-threshold more attractive to lessen the downsides after crossing the threshold (similar to how Inconveniently Large becomes Large for post-thresh Ursine mutants). A summer coat would provide less warmth and equally less protection, though it would still be warmer than no fur at all.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
