### ISSUE TITLE
Mounted laser weapons in turrets cannot fire in either Auto or Manual mode.

### ISSUE THREAD

**Issue by naitchal** [CleverRaven/Cataclysm-DDA#50122]
### Describe the bug

Laser weapons mounted in turrets do not appear to be working, either in automatic or manual mode.

Tried with both A7 rifle and pistol.

These turrets worked in experiment build 2021-7-20-1917, but do not appear to work after this build.

### Steps To Reproduce

1. Spawn Vehicle
2. Install turret mount if not present
4. Ensure vehicle has power storage
5. Mount laser weapon in turret
6. Attempt to aim turret

### Expected behavior

Turret should allow user to aim and fire at targets when installed and the vehicle has power, or fire in automatic mode if a controller is present.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 90539ba [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    Bionic Professions [package_bionic_professions],
    sees-player icon, HitButton_iso [sees_player_hitbutton]
]

### Additional context

The mounted weapon doesn't seem to believe it is in a valid state to fire, this could be a problem with recognizing power can be drawn from the vehicle battery.

**Comment by RDru** [comment]
I can confirm.
Probably caused by #48608
