### ISSUE TITLE
Feature Request: Add "old" guns back to experimental

### ISSUE THREAD

**Issue by NotDucc** [CleverRaven/Cataclysm-DDA#50135]
# Is your feature request related to a problem? Please describe.
The new changes to guns in experimental makes all 5.56 rifles exactly the same and even removed some rifles from the game. This is despite that they were pretty accurately portrayed, as they all took into account the different weight, length, volume, accuracy, and effectiveness of each rifle. An example being the M4A1 versus the M27 IAR, which both now have the same exact stats and were made into being the same exact "NATO Assault Rifle". However, the M27 IAR was a rifle made to replace the M4A1 (and M249) in real life. It has higher effective range, maximum range, and bullet velocity when compared to the M4A1, as well as being heavier, longer, and more durable. Before the change was made, this was reflected upon in-game in the best way it could be done. It jammed less often, was heavier, had a longer length, dealt more damage, and was more accurate/had less recoil than the M4A1 but at the cost of needing more strength to fire in full auto due to the added weight and power.

As mentioned earlier, it isn't just those two rifles suffering the problem of being inaccurately portrayed. Even the "new variants" of 5.56 rifles are all the exact same other than having different firing modes, which is completely wrong. A SIG 552 (Now the "NATO Assault Rifle with Burst) is much shorter and lightweight than an M16 (Now the "NATO Burst Rifle"), to add in another example on the new inaccuracy created by the change.

# Describe the solution you'd like
I recommend reversing the changes made by re-merging the previously used code for guns. It worked before, I don't see why these rifles needed removed or changed to be less accurate to their real-life equivalents.

# Describe alternatives you've considered
If the previous stats were removed because they were "too similar" to each other, make them more unique. Though length, volume, weight, and dispersion were pretty accurate in-game and I considered those qualities to be unique enough, I'm sure other differences could be made. Examples would be using larger amounts of ammo being used in full-auto if it has a higher rate of fire or better range if it has good range for that type of rifle.

# Additional context
Some sources of information about the guns mentioned:

https://en.wikipedia.org/wiki/M4_carbine
https://en.wikipedia.org/wiki/M27_Infantry_Automatic_Rifle
https://en.wikipedia.org/wiki/M16_rifle#M16A4
https://en.wikipedia.org/wiki/SIG_SG_550

**Comment by I-am-Erk** [comment]
The change includes a lot of guns that are in fact pretty similar to each other, so just "revert it" isn't a good request. It happens I've been looking into this over my lunch break, so I'll give you an example:

NATO assault rifle currently includes the following guns
-m16a3
-m4a1
-remington acr
-HK416 A5
-M27 IAR
-FN SCAR-L
-M38 DMR
-MK 18 CQBR

Based on dimensions alone, there are a few here that belong together and a few that don't. Conveniently these also fall into similar groups.
-m16a3 is way longer than the others and should be its own entry.
-mk18 cqbr is much shorter than the others, as is HK416. These are similar in size and weight and should get their own entry.
-M38, m27, SCAR-L, and ACR are all similar both in length and weight and in age and purpose. They should be a single entry with variants.
-m4a1 is not as long as the bigguns and not as short as the smalluns, it should be its own entry.

If you want to do this for other varianted guns that are over-condensed, that would be helpful. I've been allowing roughly 10% variance in size and weight to be counted as 'the same' for our purposes.

**Comment by NotDucc** [comment]
> 
> 
> The change includes a lot of guns that are in fact pretty similar to each other, so just "revert it" isn't a good request. It happens I've been looking into this over my lunch break, so I'll give you an example:
> 
> NATO assault rifle currently includes the following guns
> -m16a3
> -m4a1
> -remington acr
> -HK416 A5
> -M27 IAR
> -FN SCAR-L
> -M38 DMR
> -MK 18 CQBR
> 
> Based on dimensions alone, there are a few here that belong together and a few that don't. Conveniently these also fall into similar groups. Bear in mind that things like "comes with an included folding stock" or similar are already represented, an m38 comes with different attachments than an m27.
> -m16a3 is way longer than the others and should be its own entry.
> -mk18 cqbr is much shorter than the others, as is HK416. These are similar in size and weight and should get their own entry.
> -M38, m27, SCAR-L, and ACR are all similar both in length and weight and in age and purpose. They should be a single entry with variants.
> -m4a1 is not as long as the bigguns and not as short as the smalluns, it should be its own entry.
> 
> If you want to do this for other varianted guns that are over-condensed, that would be helpful. I've been allowing roughly 10% variance in size and weight to be counted as 'the same' for our purposes.

As of right now, none of the "NATO guns" that are supposed to be represented by "branding" being turned on is accurate. All 3 have the same dimensions, weight, length, damage... everything. If this list is planning on getting simplified, I think it could be agreed that those numbers need to change to match the branded gun it represents at the very least so that they stay accurate to the real-life counterpart.

**Comment by I-am-Erk** [comment]
yes, that is exactly what I just said. However, there are a great many guns covered by the variant change that really are just variants of each other, we're not going to revert the whole change. For example, many of the pistols that have been condensed really are not meaningfully different in any stats we can feasibly measure. So, if you want to see some guns that are overly condensed broken up into groups again, you need to do what I just did above and find those guns and specify why they need to be separate. I've done it for NATO assault rifle, you're welcome to identify similar cases.

**Comment by NotDucc** [comment]
I did so already for 2 cases, unless you mean something else:

> As mentioned earlier, it isn't just those two rifles suffering the problem of being inaccurately portrayed. Even the "new variants" of 5.56 rifles are all the exact same other than having different firing modes, which is completely wrong. A SIG 552 (Now the "NATO Assault Rifle with Burst) is much shorter and lightweight than an M16 (Now the "NATO Burst Rifle"), to add in another example on the new inaccuracy created by the change.

A SIG 552 has a length of 28.7 inches (and as is stated in-game, this is labeled as the new "Nato Assault Rifle with burst"), weight of 7.1 lb (guessing while loaded). An M16A4 (Now the "NATO Burst Rifle") has a length of 39.5 inches, weight of 7.5 lb when loaded. These are weapons that remain in experimental, but were both changed (alongside the M4A1, the "NATO Assault Rifle") to all have a length of 29 inches and weight of 7.73 lb. Recoil and Dispersion also remain the same, thought that is admittedly hard to judge. However, this still makes both rifles wrong if you were to turn on branding and was what I was referring to in my last comment.

**Comment by I-am-Erk** [comment]
Right, my point is, you should generate a list of the rifles in a given group eg NATO burst rifle, and do what i did - make a clearly legible recommendation for how to split them apart. Doing it in prose form is hard to read and presumably incomplete, depending on what other rifles are currently considered variants NATO burst rifle. Ideally include the length and weight stats in your list.

That said, the SIG 552 and m16a4 are not currently considered variants of each other. Mostly what they need is their length and weight stats added back after being incorrectly removed... and those names are not good, I have a whole separate issue for that but it's not directly related to this.

**Comment by NotDucc** [comment]
Alright, got it, I'll come up with a list to group them all into

**Comment by I-am-Erk** [comment]
see also #50137

**Comment by NotDucc** [comment]
> 
> 
> see also #50137

Already said it on that issue, but I'll say it here as well; I'd be cool with guns getting simplified like this rather than the incredibly broad way they are done now. Plus, it would allow for more accurate stats due to them being broken up in a much tidier way if this is done. Going to still come up with a list to help with that when I get the time later today

**Comment by I-am-Erk** [comment]
@anothersimulacrum generated a list of the old gun weight and length values for re-adding as well.

**Comment by anothersimulacrum** [comment]
See https://github.com/CleverRaven/Cataclysm-DDA/pull/50142
