### ISSUE TITLE
OVERSIZED armor and Tiny mutants

### ISSUE THREAD

**Issue by Stretop** [CleverRaven/Cataclysm-DDA#50139]
# Is your feature request related to a problem? Please describe.
In the current experimental version, when player character gets both Tiny mutation and mutations that preclude usage of "human" clothing on some bodypart (the ones that have "restricts_gear" property) - he can very well end up with no options for usable gear for said bodypart whatsoever. Why it is so? Because of the current implementation of the OVERSIZE flag that forbids downsizing items even if those at the same time have VARSIZE flag.

# Describe the solution you'd like
Refactor OVERSIZE flag functionality so that it allows such "mutant-friendly" equipment to be downsized for Tiny characters.

# Describe alternatives you've considered
Dispose with the OVERSIZE flag (and XL gear variants) entirely and explicitly separate size and "mutant-friendliness" (by VARSIZE and some new flag, say "MUTANT_ADAPTABLE") of any piece of equipment (this also goes for craftable weapons, by the way), so that it can be up-sized, down-sized and "mutanized" separately as needed (if requisite flags are present). Also provide an option during craft preparation (along with choosing variants of materials and tools used) to craft the thing already up/downsized/mutanized.

# Additional context
So, to accomodate all characters in regards to craftable equipment we have to provide items along two axes:
1) Large-Small
2) Human-Mutated
Since those two axes are _independent_ (as we can potentially have Tiny Humanlikes, Huge Humanlikes, Tiny Mutants and Huge Mutants) - flags intended to address those should likewise be independent.

**Comment by kevingranade** [comment]
The other option is that the small and tiny mutations are severely underdeveloped in general, and unless someone is excit

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
