### ISSUE TITLE
UI:Zone management, add mixed content container zone as new container sub zone

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#50148]
# Is your feature request related to a problem? Please describe.
With 0.F stable, wallets and first aid kit type items end up in the container zone when sorted, which comes as a bit of a surprise (but it's a lot better than if they'd get buried in the Others zone).

# Describe the solution you'd like
Add a new Mixed Container zone type for containers (and, ideally, any kind of non empty items that aren't containers with "pure" contents, such as e.g. the cargo pants with stuff still in their pockets). This zone would serve as a "things to sort out manually" zone.
The "simple" implementation would have it as a sub type of the container zone, in a manner similar to how perishable food is a sub type zone of the food zone. A more complex implementation would have it take any items that aren't empty and which are not simply a container with it's contents (like as a box of pasta). Thus, the un-emptied cargo pants would end up here, together with wallets, first aid kits, and non empty backpacks.

# Describe alternatives you've considered
The current implementation works, until your container zone grows to cover many tiles, at which time it gets unwiedly.

# Additional context
-

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
