### ISSUE TITLE
Cannot compile on macOS

### ISSUE THREAD

**Issue by pehamm** [CleverRaven/Cataclysm-DDA#50141]
### Describe the bug

Pulling the current master (as of 6d52144) and trying to build it with `make NATIVE=osx LOCALIZE=0 CLANG=1 RELEASE=1 TILES=1 SOUND=0 OSX_MIN=10.14` fails with the following messges:

`// NOLINT(cata-header-guard)

#define VERSION "0.F-1000-g6d521443d9"
astyle -V: Artistic Style Version 3.1
no astyle regressions
find data gfx -name "*.json" -print0 | grep -v -z -F -f json_blacklist | \
	  xargs -P 0 -0 -L 1 tools/format/json_formatter.cgi
grep: invalid option -- z
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
xargs: max. processes must be >0
make: *** [style-json] Error 1`

It worked last week without a hitch. Could be connected to #50098, not sure.

### Steps To Reproduce

1. Checkout current master from github on a macOS system
2. run make, I used `make NATIVE=osx LOCALIZE=0 CLANG=1 RELEASE=1 TILES=1 SOUND=0 OSX_MIN=10.14`

### Expected behavior

Compilation should work without issues.

### Versions and configuration

macOS version 10.14.6

**Comment by BrettDong** [comment]
Temporary workaround: append `LINTJSON=0` to your `make` parameters.

**Comment by BrettDong** [comment]
I remember I solved this by installing GNU command line utilities.

**Comment by pehamm** [comment]
Yeah, looks like macOS is shipping a 15-year old xargs version, the current FreeBSD variant is supporting the `-P 0` option. Not sure if there is a way to check inside the Makefile which xargs version is used, breaking macOS compiles to save 15 seconds for a lint check seems unreasonable, but just checking for Darwin removes the time savings for mac users who have newer versions.
