### ISSUE TITLE
Previously towed vehicle has high cruise speed when controlled directly

### ISSUE THREAD

**Issue by Qrox** [CleverRaven/Cataclysm-DDA#50153]
### Describe the bug

Normally when you start a vehicle that has stopped previously the cruise speed is set to 0, However if the vehicle was previously towed and stopped on its own, and then controlled directly, the cruise speed can be as high as 100 km/h despite being towed at a slow speed. If you don't notice and try to accelerate thinking that the cruise speed is 0, some nasty surprise awaits you.

### Steps To Reproduce

1. Tow a vehicle.
2. Control the towed vehicle.
3. Notice the cruise speed.
4. Pretend that you didn't notice the cruise speed and try to accelerate.
5. Crash into whatever is ahead of you at high speed.

### Expected behavior

The cruise speed is set to 0 whenever a vehicle is stopped.

### Versions and configuration

f0170fea37d442fcab33e6303e10c9594a8cab7a

### Additional context

Alternatively, add a "crappy cruise control software" fault that spawns in some vehicles, and add newspaper snippets mentioning the recall of these models by car companies.

**Comment by RenechCDDA** [comment]
Resolved by #64188
