### ISSUE TITLE
Unwielding an item with assigned inventory letter causes the inventory letter to be reset

### ISSUE THREAD

**Issue by Qrox** [CleverRaven/Cataclysm-DDA#50154]
### Describe the bug

Unwielding an item with assigned (yellow) inventory letter causes the inventory letter to be reset

### Steps To Reproduce

1. Wear a spear strap with a spear
2. Assign an inventory letter to the spear
3. Wield the spear
4. Unwield the spear
5. See that the assigned inventory letter is reset

### Expected behavior

The spear keeps its inventory letter.

### Versions and configuration

f0170fea37d442fcab33e6303e10c9594a8cab7a

### Additional context

Probably caused by #49925, since when the wielded item is added to the inventory, the original wielded item is not removed, which causes the newly added item to lose its inventory letter.

**Comment by Shibimon** [comment]
I noticed this same issue with my guns and wielded storage, having updated the game recently (newest version available) from the one i was using befor from 5 days ago where it was working fine.
Weilding again the same weapon manually seems to show again the correct yellow shortcut letter in the gun but is a hassle cause this bug makes the letters useless still.
I noticed too when this happens seems to assign random white letters to my weapon magazines.

**Comment by actual-nh** [comment]
Ping: @exuvo?

**Comment by exuvo** [comment]
Oh i have not been using any straps for my current game so have not noticed this. I'll try to fix it.

**Comment by exuvo** [comment]
oh what a mess this is.

Ex assign B to wielded item. Then assign A to the item while in pocket (normal inventory). If you do it in the opposite order , inventory first then wielded, the pocket letter assignment is lost.
So it is A in inventory at start. Wield it and it stays A. Unwield and it is now B, wield again still B, unwield back to A.

Wear the item from pocket and assign letter C. Whatever letter it had assigned just before your new assignment is now gone from the rotation.
Ex it was A before new assignment. Unwear and it is now B.
Back and forth between pocket and wear it stays B.
Wield and pocket back and forth it swaps between B and C.

So it seems like removing from wield and wear to pocket uses their own letter assignments. But swapping between wield and worn keeps whatever letter it had.

**Comment by Shibimon** [comment]
I found a "workarround", dropping to the floor the item that was being held when welding another and then grabbing it again don't break the letters and even better, don't assign a bunch of white letters to random tools and magazines.

**Comment by exuvo** [comment]
Checkout the linked commit, it should fix this but i might have missed some testcase.
