### ISSUE TITLE
Make caltrops have a chance to give the player tetanus

### ISSUE THREAD

**Issue by Saicchi** [CleverRaven/Cataclysm-DDA#50167]
# Is your feature request related to a problem? Please describe.
Caltrops does not have a chance to give the player Tetanus

# Describe the solution you'd like
Caltrops being able to give the player Tetanus.

# Describe alternatives you've considered
None

# Additional context
Beartraps, nailboard trap, pit spikes, and glass pit all can give player tetanus, so it seems weird that caltrops and glass caltrops can not.

The respective functions are in `src/trapfunc.cpp`

**Comment by ZhilkinSerg** [comment]
Jsonize this.

**Comment by Venera3** [comment]
Glass shards? Really? I have some plans for tetanus down the line, so the having a look at the hardcoded parts is on the agenda. Probably as a low chance on all stab damage sources, progressing into a separate local infection from the generic one.
