### ISSUE TITLE
mac os ox build for 0.F is missing libSDL2mixer-2.0.0 dylib file and wont start

### ISSUE THREAD

**Issue by ashtiboy** [CleverRaven/Cataclysm-DDA#50198]
### Describe the bug

mac os ox build for 0.F is missing libSDL2 mixer-2.0.0 dylib file and won't run! bescue there's only half of the libsdl2 mixer files needed for normal function in the games core resource folder! i can't run the game without the other half of the sdl2 mixer files that not in the game files! it looks like someone forgot one needed file for the mac os x 0.F build of CDDA to work!

### Steps To Reproduce

trying to start up the game
then it crashes

### Expected behavior

the main menu should pop up

### Versions and configuration

mac os x 10.13.6

### Additional context

Dyld Error Message:
  Library not loaded: /usr/local/opt/sdl2_mixer/lib/libSDL2_mixer-2.0.0.dylib
  Referenced from: /Applications/Cataclysm 7.app/Contents/Resources/./cataclysm-tiles
  Reason: image not found

**Comment by ashtiboy** [comment]
so anyway we can just put in the latest version of the sdl2 mixer 2.0 other files since its open source now by the way! maybie we should download like libSDL2 mixer-2.0.4 dylib or something like that! sense it's the one file that's available from the sdl main website right now!

**Comment by actual-nh** [comment]
One can fix some of these by making a symlink of the name it wants to what's currently shipped, but one eventually does get to things that can't fix. See #49570 (not marking this as a duplicate because it's focusing on things other than Mac versions).

**Comment by ashtiboy** [comment]
also don't complete  0.F to support any mac os x version that's older than 10.12.0 bescue that's just not going to work! bescue  mac os x pre 10.12.0 frameworks are just not compatible with arm or newer mac os x versions past 11.0.0 bescue it's just to old and outdated and incomplete! also no more 32 bit support on mac os x at all! new mac os x builds need to run in a pure 64 bit compile kernel os or its not going to work on mac os x 10.15.0 and newer!

**Comment by actual-nh** [comment]
See #49595 for a bit on that.

**Comment by ashtiboy** [comment]
anyway i'm giong to try the july 27 build to see if it works or not!

**Comment by ashtiboy** [comment]
nope still broken! the pull didn't get approved and there still missing frameworks! and guess what it's the same issue I had said before there's missing frameworks that need to be put in a pull that makes the computer to be able to run the game on a mac bescue IT needs to be in the game application resource folder on the mac afters its built with the needed frameworks on the developer mac! then once its built with the farmworks successfully! then you upload the build for others to use! the developer must make the build with the needed frameworks into it first!  then when all the needed farmworks are actually been checked to make sure all of them are in the game app resource folder after being built after you bug test the thing! so you know it can works on other macs ! mac os x uses the frameworks in the application program resource folder! not from the system files framework folder you used to build it!  if the frameworks are if they not in the application resource data folder before being uploaded  then thing won't work thus no runnable game! that's how it works on mac os x! you just build it and make sure the application program resources folder has everything needed you built has all the needed frameworks in the finished application folder SUCCESSFULLY  before you try to even try to think about uploading a mac os x stable! i'm getting sick and tired of someone not doing a basic framework check list of what's needed! before its experimental build is uploaded for testing!  that should be done before anything else for the mac os x version of the game! it's the first thing that should be done before anything else!

**Comment by ashtiboy** [comment]
you guys better bundle the needed frameworks with the game application resource folder because if you don't !IT WON"T F*** WORK! that its what the new pull is for i can't use a apple program without the need library  frameworks if it ain't in the game program itself you know!  it has to come with the game when its been downloaded from the internet! it's like running a game without its needed data files but worse! it won't even get to even boot before the game gets to even logs its own error!  if it can't even like even set itself up before it crashes! bescue the mac os x is like: dude you don't got my framework data files in my app! i'm not going to touch that before you get my frameworks in my app resource folder you noob!

**Comment by actual-nh** [comment]
Marked PR to fix as priority; I understand you're frustrated, but please try to be a bit more polite.

**Comment by kevingranade** [comment]
No thanks, someone can re-open the issue if it's valid, but we don't keep around ranty stuff like this.
