### ISSUE TITLE
Shelves and other storage furniture types do not allow freezing temperatures to effect food

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#50199]
### Describe the bug

Hello again.

So, I've been definitely-not-just-debugging-into-existence a nice, fortified stronghold for my main survivor's fledgling post-apocalyptic utopia, and one of the features of this totally-built-the-hard-way stronghold was a giant, laboriously-grafted room that just so happens to be coincidentally, conveniently made of terrain that can't be crafted by survivors neatly arranged into the exact shape I wanted it to be in, why are you asking, which I then filled with rows of warehouse shelves, along with a stationary vehicle designed with parts I modded in for myself that can near-instantly drop the temperatures in the whole room to below freezing.

A while after putting some of the food I intended to store on one of the shelves, however, I happened to notice that none of what I had put there was freezing. Hell, it wasn't even cold. Since I'm _preeetty_ sure that's not how it's supposed to work, I then made a new world without any extra mods, save for the one I made myself to add in vehicle parts, to test this further. Starting in an LMOE shelter, I debugged in some warehouse shelves, as well as a dresser just to see how that would work, and some bottles of water, and constructed a vehicle not unlike the one my main survivor wanted to use to freeze food and such. I put some water into the warehouse shelf, some into a utility shelf that came with the shelter, some into a standing tank that also came with the shelter, and some into a dresser. I also dumped some water onto the floor, and put the rest of the water bottles down somewhere else on the floor. After cranking on the mega-AC and giving the test survivor the debug mutations that would allow her to survive this test, I had her wait for an hour, and then looked at the water. Only the water on the floor (both in and out of the bottles) managed to freeze, or even change temperature at all, while the water in the shelves, dresser, and standing tank were completely unchanged.

### Steps To Reproduce

1. Find or debug in some storage furniture and comestibles
2. Put the comestibles in said storage furniture
3. Subject the comestibles and the furniture they're in to constant exposure to maxed-out levels of all four types of cold air fields for several hours
4. See that the comestibles in the storage furniture is not frozen
5. Lament your lack of an absurdly giant freezer

### Expected behavior

I expected the comestibles to eventually freeze while stored away in furniture surrounded by temperatures that make the South Pole look like Florida in comparison.

### Versions and configuration

- OS: Windows 8.1 Pro
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Cooler Versatility [coolervers]

### Additional context

[Here is a google drive folder including both the save folder for the world I used to test this, and the mod I made for the vehicle parts.](https://drive.google.com/drive/folders/1ye3LQvHbvwg41wwkBVhNwCUNXzNphw3E?usp=sharing)

So you're aware, there are two characters in the same world. I thought I just exited out without saving for the first one (Dullia), which is why I made another one (Lovella). I did slightly less testing with Dullia anyway. Also, between Dullia and Lovella, I ended up removing some files from the mod folder, since I was never able to get what I was working on in those files to function properly anyway, and I have no idea of how to change that. If you try to load Dullia for some reason, you might get a couple of extra error messages.

**Comment by anothersimulacrum** [comment]
Probably these should have the `PERMEABLE` flag.

**Comment by AmarinReyny** [comment]
> Probably these should have the `PERMEABLE` flag.

I just tried this with the warehouse shelves, just to see if it would work, and it did! I'll get to editing the rest of the storage furniture data on my own end, once I lay down for a while to recover enough spinal strength to sit again.

Also, I know the whole dev team is really, *really* busy with, well, everything, so... if you want me to, I'll upload the file when I'm done with it, so you don't have to edit it yourselves? Granted, it might have some other edits to it which I've forgotten making in the past... hm... well, it's up to you, I guess.

Thank you!

**Comment by mythosmod** [comment]
@AmarinReyny Good morning! I was just going through older issues and wanted to check if you are still intending to look at this one? No problem if not, I am happy to take this one on if this is the case.

**Comment by AmarinReyny** [comment]
> @AmarinReyny Good morning! I was just going through older issues and wanted to check if you are still intending to look at this one? No problem if not, I am happy to take this one on if this is the case.

What do you mean?

**Comment by RenechCDDA** [comment]
No longer an issue as of https://github.com/CleverRaven/Cataclysm-DDA/commit/c94dc0387513d5bba49eb7d74b2b51a7a4d8c4a0

PERMEABLE does not function as previously stated, either it never did or was changed. Common storage furnitures (including the mentioned warehouse shelves) are allowing their contents to freeze without any specific flags.
