### ISSUE TITLE
Make dump file or invisible log file

### ISSUE THREAD

**Issue by web-hijacker** [CleverRaven/Cataclysm-DDA#502]
My game crashed several times (Cataclysm-DDA 0.4). As far as I played with debug mode OFF, I don't have anything to send to prove this :)

At the same time, debug mode ON is annoying -- often I need to press anykey to proceed with the messages in debug console. 

Having some debug file being written in the background seems to be a good idea.
##

**Comment by sparr** [comment]
does the now-existing debug.log file fulfill this request?
