### ISSUE TITLE
PR Validator and PR template don't match

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#50208]
### Describe the bug

the PR template says to do it like this:

#### Summary
Category "Balance"

The PR validator doesn't like this and throws arcane errors that can only be divined by a master wizard of the regex variety.

### Steps To Reproduce

Make a pr
Note that the validator hates you

### Expected behavior

Following the template should validate correctly

### Versions and configuration
n/a

**Comment by Xpyder** [comment]
I'm indifferent as to whether it's the template or the validator that gets changed, I just want to stop getting yelled at by the gatekeeper

**Comment by Qrox** [comment]
From the comments below `Category "Balance"`:

```
<!-- This section should consist of exactly one line, edit the one above.
Category must be one of these: Features, Content, Interface, Mods, Balance, Bugfixes, Performance, Infrastructure, Build, I18N. Or replace the whole line with just the word None for no changelog entry.
```

What it means is that you replace `Category` with one of the category values and put a summary of the changes into the quotes. For example `Bugfixes "Fix foo and bar"`. It's definitely not asking you to use a category value as the brief description.

We can make it more clear in the PR template, and instead of asking people to change the PR summary to match a regex, ask them to refer to the PR template instead.

**Comment by Xpyder** [comment]
Maybe the inclusion of your example might make it more clear?  I'll have to check next time I'm doing a PR

**Comment by Xpyder** [comment]
don't merge this just yet, I need to do some more testing

**Comment by actual-nh** [comment]
> We can make it more clear in the PR template, and instead of asking people to change the PR summary to match a regex, ask them to refer to the PR template instead.

The regex was helpful to me when I was first figuring it out, but I agree that putting a reference to the PR template, with an example included, should be first.

**Comment by anothersimulacrum** [comment]
IIRC We can't put a valid summary line in the PR template, or the validator will see that and use it.

**Comment by Xpyder** [comment]
can we put one inside the comment tag where we describe it?

**Comment by anothersimulacrum** [comment]
That's still in the PR template.

**Comment by Xpyder** [comment]
hmm... what about putting the/an example in the error message the PR Validator gives back?

**Comment by anothersimulacrum** [comment]
That'd go here
https://github.com/CleverRaven/pr-validator/blob/160a007b08976855c37b38d78e6156b8fab4d2b0/src/main.ts#L13
