### ISSUE TITLE
[0.F stable] Companion pathfinding confused by sludge trails

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#50206]
### Describe the bug

Moving zig-zag to avoid a somewhat decayed sludge caused the companion to cease to follow the PC until the PC moved to a position where the sludge didn't confuse the companion.

### Steps To Reproduce

1. Have a companion follow the PC at two steps no matter what. don't investigate sounds (don't know what's relevant, but that's what was used).
2. Find a sludge trail of the type "*.***", where * is sludge and . is a sludge free tile.
2. Moved straight down towards the sludge trail from the north towards the center tile in the string above.
3. Side step the sludge into the free space via a diagonal movement and then back to the center downward line with another diagonal movement.
4. Watch in confusion as the companion moves to the tile above the center sludge trail tile (where the PC was two steps ago), then back north, back south, back north... until the PC move around the mess to give the companion a sludge free path to follow.

### Expected behavior

The companion should follow the PC in the footsteps if shortcuts are blocked off by sludge (like when the PC dodges normal bad terrain, such as boulders).

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

By the time I decided to write a bug report the trail had already dissipated, so I can't provide a save, unfortunately.

The sludge trail was generated by the new pupating zombie.

The default setting of having diagonal movement cost more than orthogonal ones hasn't been touched, so two diagonal movements should be more expensive than a straight (sludge free) line.

I've had other cases of sludge confusion where the companion walks off in a different direction when the PC navigates through the sludge mess until the PC moves around to give the companion a path it can understand.

**Comment by PatrikLundell** [comment]
[Auburn Hills.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6873502/Auburn.Hills.zip)

The save above manages to recreate the issue with an acid trail. Moving the PC south, the companion keeps moving back and forth in the N/S direction just below the trail, which continues if the PC turns around and moves northwards again.

A guess as to the cause: The path finding makes a path that would go through the trail, finds that the trail blocks it when reaching the trail, then moves back one step, finds a "new" path that's the same as the old one, moves one step, find the path blocked, ...
The re-pathing logic would need to take into account that it has already run into trouble and analyze tiles for non static blocks as well as static ones new retrying (basically: treat sludge/acid/... as impassable terrain so as to not make a path through it unless there is no other path available).

**Comment by Xomikadze** [comment]
I had similar situations but with windows. If there are 2 windows in the wall, one of which is closed and the other is open. Then if you go along the wall to these windows and the satellite will lag behind a little, and you will enter the house through the window. Then the satellite will try to enter the closed window and will naturally not be able to do this until you open it. Although there is an open window in the next cell.

**Comment by PatrikLundell** [comment]
I've had issues with the companion sometimes not being able to follow through a window, while doing so without problem at other times. However, I haven't looked at that more closely, since it's only been annoying, not resulting in the death of the companion. It may, however, well be related, as Xomikadze indicates.
