### ISSUE TITLE
NPC in the team not eat from the camp

### ISSUE THREAD

**Issue by linonetwo** [CleverRaven/Cataclysm-DDA#50211]
### Describe the bug

NPC used to eat food source in the camp, but they are not, so they keep saying hungry in the camp.

### Steps To Reproduce

Basically same as https://github.com/CleverRaven/Cataclysm-DDA/issues/47663  and https://github.com/CleverRaven/Cataclysm-DDA/pull/47720

### Expected behavior

NPC in the camp and in the team don't say hungry if there is food in the camp.

### Versions and configuration

- OS: Android & MacOS
- Game Version: https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2021-07-25-0740
- Graphics version: [Tiles]
- Ingame language: [Arabic or Bulgarian or Chinese (Simplified) or Chinese (Traditional) or Dutch or Esperanto or French or German or Italian (Italy) or Japanese or Korean or Polish or Portuguese (Brazil) or Russian or Serbian or Spanish (Argentina) or Spanish (Spain) or Turkish]
- Mods loaded: [dda, and Kenan mod pack]

**Comment by hexagonrecursion** [comment]
NPCs do eat from the camp. Is there a chance you are not doing this right?
1. Create a world without the npc_no_food mod
2. Get a follower
3. Create a camp
4. Create basecamp: food and basecamp: storage zones
5. Bulletin board -> Assign Workers -> assign the NPC to the camp
6. Drop a meat pie into the basecamp: food zone
7. Bulletin board -> Distribute Food
8. Debug edit the NPC needs such that stored kcal + gut kcal + stinach kcal < 52000
9. Wait. This may take a couple of hours (in game time)
10. See a message indicating that the NPC ate

NPC also eat food when they *return* from a mission

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: bc1f60e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions]
]

**Comment by linonetwo** [comment]
Can't reproduce from my side in latest experimental...
