### ISSUE TITLE
New alien idea for Aftershock:Floaters

### ISSUE THREAD

**Issue by Ali-Anomma** [CleverRaven/Cataclysm-DDA#50218]
# Is your feature request related to a problem? Please describe.
Aftershock,despite being a total converison mod and have own planet,lacks alien fauna.

# Describe the solution you'd like
Adding floaters.This flying creatures have lighter than air gas,and moves like zeppelin,can make photosyntehesis,creates and guards floater trees.

Floaters body shaped like a large horizontal wheel which its edges are not flat(by not flat,i mean that face that touches the ground,other edge is more flat), its top is covered by cloroplasts,which allows them to photosyntehesis.

Its body covered by several mouth like holes,which: 

- exchanges air,sugar(as food) ethanol(spits it to burn its enemies)

- creating little vines for planting or connecting to floater trees

- inhaling and exhaling powerfully so floaters can move in air

Floaters also have three stomachs,which:

1.  First stomach is normal stomach which digests sugar.

2. Second stomach is storing methane,ligher than air gas which allows to floaters float in air.

3. Third stomach is storage space for caught or finished chemicals,which every role uses it for different chemicals.

Floaters relies photosyntehesis,burning sugar and (literally burning) ethanol for live. But since water dense in clouds, CO2 and O2 more on surface,sunlight more on above clouds,and trees which can serve as storage for chemicals can easily hunted;they serve different roles.

Roles have same anatomy and DNA despite they will have seperate monsters for roles in game;only differences is what they do,where to work and what fills their third stomaches,the roles are:

- Breathers,collects CO2 from air,can be uncommonly(because it flies on 0-20 meter) seen in game.Fills their stomach with CO2.

- Defenders,most commonly found enemy,protects floater trees and burns with ethanol creatures that came too close to floater tree,but otherwise,it ignores player.Fills their stomach with ethanol.

- Drinkers,collects water from clouds or fogs,cant seen on game beacause of this,fills their stomach with water.

- Solars,flies above clouds or flies to cloudless areas to get sunlight,then take water and CO2 to photosyntehesis,produces sugar.Fills their stomach with sugar.

Because of transporting chemicals beween heights,floaters need floater trees;not just tramsports chemicals,also for various reasons:

- It transports and stores chemicals to floaters(gives water and co2 to solars,ethanol to defensers and sugar to all floaters)

- Save energy for floaters,instead of using mouths for staying on air(they are falling down because of their weight,but thanks to their second stomachs,it happens very slowly and floaters can regain their altidute with using their mouths)since floaters need constantly spend energy to float,floaters produce vines from their mouth and ties themselfs to tree,so even they dont spend any energy,they dont fall to ground.

- Ferment ethanol from sugar,while ethanol dont used by body directly,floaters (literally) burns ethanol for surviving from cold.

- Provide nutritents which cant be avaible from photosyntehesis.

Floaters "plant" trees with creating vine from their mouths,as the end of vine touch to ground,it produces anchor roots,which set them in place.After that,it produces nutrition roots which sucks minerals from ground. If one bloater dies,it produces compsing roots and gets corpses nutritents.Also if it barely balancing,it produces new branches which bends to ground and become side tree,support for floater tree.

While floater trees sounds like plant it is more likely to coral,which is animal (also floater tree goes to sky without any branches,branch like structures either tied floaters or side trees.) and connection between floaters and trees is jellyfishes and corals.See the additional context below.

Of course we dont need to all info for game,i just explained so it is not purely fictional,instead it can be realistic. In game,players all need to learn:

Floaters are flying creatures which guards floater trees and side trees,can attack with fire and when butchered,it gives ethanol,sugar and a leather when tanned it becomes nomex like fireproof material.

# Describe alternatives you've considered
Wait me to add floater code.

# Additional context
Jellyfish life cycle:
![jellyfish-lifecycle-blue](https://user-images.githubusercontent.com/59798817/126908069-be7f1830-11ea-4c9d-b184-6dad00b6b37a.jpg)

**Comment by Maleclypse** [comment]
I really like this `Floaters "plant" trees with creating vine from their mouths,as the end of vine touch to ground,it produces anchor roots,which set them in place.After that,it produces nutrition roots which sucks minerals from ground.` because mi-go resin works similar to this and ||mi-go|| are the devolved version of the previously intelligent alien species on Salus IV

**Comment by LyleSY** [comment]
Seems good to me. Do you want to give a PR a try?

**Comment by Ali-Anomma** [comment]
> Seems good to me. Do you want to give a PR a try?

very soon

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
