### ISSUE TITLE
[0.F stable] Pick UI doesn't color code food in containers

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#50210]
### Describe the bug

Items in the 'g'et menu are color coded according to its freshness (and, I think, the PC's tolerance for it), but only provided they're not stored in containers which are uniformly using a grey color.

It can be noted, however, that the items still have textual modifiers, such as e.g. "(fresh)" regardless of whether they're in containers or not. Thus, this is a border case between bug and enhancement, and thus not a high priority issue.

### Steps To Reproduce

1. Try to pick up food items of various levels of freshness and varying whether they're in containers or not.
2. Observe the lack of color coding for food in containers.

### Expected behavior

The same color coding would be applied regardless of whether the food is in a container or not.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

As noted, I'm unsure whether to label this as a bug or an enhancement. "Feature request" sounds like more ambitious than enhancement, though...

**Comment by ZhilkinSerg** [comment]
If you are talking about changes from #47426 - this is a post-0.F change and it is not a bugfix, so there is little sense to backport it to 0.F.

**Comment by PatrikLundell** [comment]
Yes, it does seem this is the same issue. It's hard to keep track of changes in a "new" release when those changes were made a quarter before the release was actually made.

**Comment by ZhilkinSerg** [comment]
> Yes, it does seem this is the same issue. It's hard to keep track of changes in a "new" release when those changes were made a quarter before the release was actually made.

Try https://github.com/CleverRaven/Cataclysm-DDA/compare/0.F-branch...0.F-dev or https://github.com/CleverRaven/Cataclysm-DDA/issues/42658#issuecomment-667835289
