### ISSUE TITLE
Random start gives trait that are not starting traits

### ISSUE THREAD

**Issue by Fris0uman** [CleverRaven/Cataclysm-DDA#50224]
### Describe the bug

Start `Play now!` random start with Magiclysm mod, start with Demon Skin which is not available at character creation.

Additionally the Starting NPC in this screenshot is loaded with Manatouched mutations and I'm not sure it's supposed to happen since those are not starting mutations either.

Got this bug with Magiclysm but I'm not sure it's Magiclysm specific since Demon skin seems set up properly to not be a starting trait on the json side.

### Steps To Reproduce

1. Start `Play now!` random start with Magiclysm mod enabled
2. Get mutation like Demon Skin that's not a starting trait
[Nice.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6874580/Nice.zip)

### Expected behavior

Not getting non starting trati even wit random start

### Screenshots

![image](https://user-images.githubusercontent.com/41293484/126913855-4fa14169-1fcd-4e2e-9ec5-559d5a0821a2.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: Please install `git` to generate VERSION [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]
]

**Comment by Broken27** [comment]
I can confirm this, i got Demon Skin in a random character last week. (Although i didn't knew it was a bug).
