### ISSUE TITLE
[0.F stable] QoL: Let Safe Mode suppress warnings about seeing enemies you are aiming at

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#50239]
# Is your feature request related to a problem? Please describe.
It's annoying to have your aiming at an enemy be interrupted by a question whether you want to stop aiming at it because you can see it.

# Describe the solution you'd like
Let the safe mode check whether the enemy it wants to warn you about is one you're targeting. If you target it, you presumably are aware of its presence.
Note that you still need to be warned when the enemy starts to hurt you.

# Describe alternatives you've considered
Just live with it. It isn't more than annoying, after all.

Add a further suppression check to block the annoying sequences of a warning about the enemy you're targeting, immediately followed by a generic warning against monsters. While aiming at an enemy (as opposed to an unseen position), you presumably did look at the situation before you started to aim, so you really should be interrupted only if something suddenly appears close.

There is (or was) a bug where you can get stuck in aiming for hours, but getting hurt would get you out of the situation when this rare bug strikes (it might still be fatal, of course).

# Additional context
-

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
