### ISSUE TITLE
Sound system for musical instrument

### ISSUE THREAD

**Issue by olegikoligik** [CleverRaven/Cataclysm-DDA#50237]
**What is problem:**
I try to add music to any musical instrument, but every second (every move) the music starts over and the previous one does not turn off. As a result, they are layered on top of each other.

**Solution:**
Music is not layered, and played one by one.

**Alternatives:**
Radio sound system is suitable for solving this problem. I ran a test with radio_inaudible_chatter_ * sounds and it works as it should, without overlapping.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
