### ISSUE TITLE
Make Boxing martial art available through pickable traits

### ISSUE THREAD

**Issue by jumjummju** [CleverRaven/Cataclysm-DDA#50232]
# Is your feature request related to a problem? Please describe.
There is currently no way to start with Boxing unless you specifically choose one of a few professions that start with it (Pugilist, Boxer, etc.) which limits roleplaying ability somewhat, and boxing isn't particularly more complex or stronger than other unarmed styles to warrant being exclusive.

# Describe the solution you'd like
Either make the Pugilist trait choosable from the trait list normally (probably unnecessary bloat in a trait list that's already bloated) or add it to Martial Arts Training or Self-Defense Classes as an option.

# Describe alternatives you've considered
Changing my RP character who's an EMT that boxes in her free time into a Muay Thai practitioner instead.

# Additional context
This seems like a fairly easy change to make (unless traits are hardcoded in which case whelp), I just have absolutely no idea what I'm doing with editing traits or even where they are in the files.

**Comment by anothersimulacrum** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/8bf16a41edb66df389573c4ff0416a8e76585e52/data/json/mutations/mutations.json#L763
