### ISSUE TITLE
Replace flamethrower with thermobaric weapons

### ISSUE THREAD

**Issue by eJ0opb** [CleverRaven/Cataclysm-DDA#50248]
# Is your feature request related to a problem? Please describe.
Flamethrowers haven't been used by the US military since 1978.  They have been replaced with [thermobaric weapons](https://en.wikipedia.org/wiki/Thermobaric_weapon).

# Describe the solution you'd like
Replace flamethrowers with weapons currently used by the US military, such as the [SMAW-NE](https://en.wikipedia.org/wiki/Mk_153_Shoulder-Launched_Multipurpose_Assault_Weapon).

# Describe alternatives you've considered
* Pretend flamethrowers as depicted in popular culture are still being used by the US military in this timeline
* Make flamethrowers represent commercial flamethrowers and change stats/loot/spawns accordingly

# Additional context
Don't blame me for taking away the toys; the US DOD unilaterally decided on this in 1978.

**Comment by RenechCDDA** [comment]
AFAIK, the M202 FLASH (used by Talon UGVs ingame) is a thermobaric weapon, and likely the only man-portable weapon that would qualify.

I'm not sure that replacing flamethrowers would necessarily be appropriate though, they're already somewhat rare spawns in military outposts/FEMA camps, and the FLASH just doesn't occupy quite the same role in a zombie scenario. 

I think the government could, pretty quickly, dust off some old equipment and concepts to reintroduce proper flamethrowers since they would be more appropriate than incendiary rockets. We already do have mass graves and other examples of the government's ad-hoc response.

**Comment by DalenTalas** [comment]
The military tends to keep their old stuff in reserve, even if it's obsolete. Just in case. Breaking out the flamethrowers from storage in case of a zombie apocalypse seems like an acceptable break from reality to me.

Furthermore, as The Wiki tells us, they are also in use for civilian applications like agriculture and forestry. And it's not unexpected that enterprising survivors could put one together.

My proposal:
- Keep the flamethrowers.
- Consider adding them as rare drops in civilian locations (farms, forestry areas of some sort).
- Add thermobaric weapons for extra !!!fun!!!

**Comment by eJ0opb** [comment]
> I'm not sure that replacing flamethrowers would necessarily be appropriate though, they're already somewhat rare spawns in military outposts/FEMA camps, and the FLASH just doesn't occupy quite the same role in a zombie scenario.

Maybe they're rare spawns, but they're not rare loot.  Visit any FEMA camp or military base and you're pretty much guaranteed to come across a few flamethrowers by killing burner zombies.
 
> I think the government could, pretty quickly, dust off some old equipment and concepts to reintroduce proper flamethrowers since they would be more appropriate than incendiary rockets. We already do have mass graves and other examples of the government's ad-hoc response.

> The military tends to keep their old stuff in reserve, even if it's obsolete. Just in case. Breaking out the flamethrowers from storage in case of a zombie apocalypse seems like an acceptable break from reality to me.

Considering that the primary role of flamethrowers was to flush out bunkers, which is not really an issue with zombies, and there are plenty of other effective weapons, including thermobaric weapons, in the current arsenal, I have doubts that the US military would reintroduce a weapon that weighs 45 pounds empty, only has a few seconds of burn time, and hasn't been serviced and or trained on for over 40 years.

> Furthermore, as The Wiki tells us, they are also in use for civilian applications like agriculture and forestry. And it's not unexpected that enterprising survivors could put one together.

Sure.  I guess I don't really mean "make flamethrowers not exist" since they do exist, but currently in game they're common military loot and seem to represent a film depiction of a Vietnam War era weapon.  Probably they should be made to represent a real life commercial flame thrower e.g. the [X18 flamethrower](https://throwflame.com/) and their loot and spawn be adjusted according to their real life distribution as alluded to in "alternatives".

**Comment by Broken27** [comment]
>Maybe they're rare spawns, but they're not rare loot. Visit any FEMA camp or military base and you're pretty much guaranteed to come across a few flamethrowers by killing burner zombies.

From the description of the burner zombie:

_"When bullets weren't enough to stop the end of the world, the military tried fire instead. Their failure is made manifest in this gas-masked husk, its black suit torn and ripped. Its flamethrower, dangling limply at its side, is attached to a tank of napalm strapped onto its back, which trickles its contents onto the ground."_

This is very much the military turning to desperate measures, like hastily taking flamethrowers out of storage or making new ones.

Removing flamethrowers from Burner zombies and giving them thermobaric weapons doesn't make sense, thermobaric weapons aren't good against zombie hordes, and burner zombies are specifically a late anti-zombie unit.

**Comment by eJ0opb** [comment]
> This is very much the military turning to desperate measures, like hastily taking flamethrowers out of storage or making new ones.

But why?  Effective weapons that soldiers have been trained on are plentiful at the start of the game, which is already after the point when the military has fallen apart.
 
> Removing flamethrowers from Burner zombies and giving them thermobaric weapons doesn't make sense, thermobaric weapons aren't good against zombie hordes, and burner zombies are specifically a late anti-zombie unit.

Actually, I would say that means burner zombies in their current state don't make sense, since they are not late game units (they occur in the first week), and by the time late game units occur the US military as we know it has long ceased to exist.  Their current in-game description doesn't negate the fact that reintroducing flamethrowers simply doesn't make much sense.  And on what basis do you say modern thermobaric weapons aren't effective against zombie hordes compared to a Vietnam-era flamethrowers?

**Comment by Broken27** [comment]
>Actually, I would say that means burner zombies in their current state don't make sense, since they are not late game units (they occur in the first week), and by the time late game units occur the US military as we know it has long ceased to exist. Their current in-game description doesn't negate the fact that reintroducing flamethrowers simply doesn't make much sense. And on what basis do you say modern thermobaric weapons aren't effective against zombie hordes compared to a Vietnam-era flamethrowers?

This is pretty obvious - Rockets are anti-tank or antibunker weapons, they are good against big, hard to kill targets. They aren't good to kill large numbers of enemies, they would run out of ammo fast.

Meanwhile flamethrowers are truly excellent clearing hordes.

**Comment by RenechCDDA** [comment]
To be a bit more specific than the above post.... outside of the explosive effect thermobaric weapons are mostly useful in *constrained* spaces, where the fire reaction literally sucks all the oxygen out of the air. Soldiers don't tend to wear or be equipped with closed-cycle respirators, which means that asphyxiation soon follows. Even for "misses" and near-hits. (Obviously against the unbreathing zombies this quality leaves something to be desired....)

Flamethrowers generally use a long-burning or gelling fuel which can stick, spread to things, and can create a conflagration. A self-spreading conflagration would be more effective against a hypothetical zombie horde than an explosive of the same mass/volume.

**Comment by eJ0opb** [comment]
> This is pretty obvious - Rockets are anti-tank or antibunker weapons, they are good against big, hard to kill targets. They aren't good to kill large numbers of enemies, they would run out of ammo fast.

Flamethrowers are also antibunker weapons.  That run out of ammo fast.  That are really heavy.  They suffer from the same disadvantages and suboptimalities of launchers, and additionally have much shorter range.
 
> Late in the cataclysm timeline, before the game starts. Not late in the game proper.

Early in the game (and therefore before the game starts) there aren't any zombies that can't be killed easily with 5.56 NATO.  Which is ubiquitous and can be carried in relatively large quantities.

> To be a bit more specific than the above post.... outside of the explosive effect thermobaric weapons are mostly useful in _constrained_ spaces, where the fire reaction literally sucks all the oxygen out of the air.
 
> Flamethrowers generally use a long-burning or gelling fuel which can stick, spread to things, and can create a conflagration. A self-spreading conflagration would be more effective against a hypothetical zombie horde than an explosive of the same mass/volume.

We can armchair quarterback the Suboptimality of the Application of Hand-Launched Thermobaric Weapons Against Large Numbers of Zombies versus The Unreasonable Effectiveness of Flamethrowers Against Zombie Hordes all day long and never reach an agreement, but the main problem with flamethrowers is logistics.  Flamethrowers were obsolete long before the cataclysm, and there is no reason to believe they would be readily available.  Considering how difficult it was to ramp up production and distribution of masks during the real world pandemic, it seems really implausible that the military could or would acquire and distribute so many flamethrowers in the events leading up to the cataclysm.  Fire-based desperate measures look more like Molotov cocktails and setting fire to large areas by readily available means - not mass production and distribution of obsolete flamethrowers.

**Comment by kevingranade** [comment]
Your argument against flamethrowers is reasonable, feel free to drop spawns of them and/or rationalize them as outlined in https://github.com/CleverRaven/Cataclysm-DDA/issues/50248#issuecomment-887198647

Your argument *for* more thermobaric weapon spawns are pretty much nil. They exist, they're absurdly rare, that's pretty much where they should be.

**Comment by eJ0opb** [comment]
> Your argument against flamethrowers is reasonable, feel free to drop spawns of them and/or rationalize them as outlined in [#50248 (comment)](https://github.com/CleverRaven/Cataclysm-DDA/issues/50248#issuecomment-887198647)
> 
> Your argument _for_ more thermobaric weapon spawns are pretty much nil. They exist, they're absurdly rare, that's pretty much where they should be.

Fair enough; my original intended point (expressed poorly) was that the US military has replaced flamethrowers with thermobaric weapons (in their role, not necessarily in numbers), not that every in-game flamethrower should be replaced with a launcher and thermobaric rockets.  What I realized in this discussion is that thermobaric weapons are actually a red herring - the real problem is burner zombies.  They shouldn't exist in their current form.  I don't buy the idea that the military keeps all these flamethrowers around, ready to go - keeping stuff lying around is not without cost (space, security, maintenance, staff time doing inventory checks, moving them even deeper into the warehouse, etc.), and 40 years is a long time to keep something that isn't used in any role, not even as a threat.  I also don't buy the idea that any production whatsoever happened when the workforce would already have been mostly dead, panicking, gone crazy, or turned into zombies.

Controlled burn/prescribed fire is a thing in New England, but I doubt they are using military flamethrowers instead of [driptorches](https://en.wikipedia.org/wiki/Driptorch).  Either way, I'm guessing the vast majority of New Englanders have never come across one.

So I guess, the updated ask is
* Turn burner zombies into foresters instead of soldiers, give them driptorches instead of flamethrowers, and put them in the appropriate setting with appropriate rarity
* Make flamethrowers a rare item found in some museums (always unloaded, probably non-functioning?).
* Maybe make a commercial variant that rarely spawns in basements (hobbyists) or on farms?  Though I'm guessing these fall into "abusrdly rare, statistically nil" territory
* No change w.r.t. thermobaric weapons

Is it more appropriate to edit this issue or write a new one?

**Comment by robotic-gamer** [comment]
potentially a bad idea but what is stopping people from combining a flamethrower with a chemical thrower to make a more general purpose tool?
potential uses:
- applying herbicide around bases to remove vegetation
- burning the now dead and more flammable vegetation (flamethrower)
- applying insecticide around bases
- applying fungicide to mold ridden building
- spray painting in a quick manner

**Comment by LyleSY** [comment]
Does #59354 close this?
