### ISSUE TITLE
.50 caliber rifle behaving strangely, causing crashes

### ISSUE THREAD

**Issue by Nictron** [CleverRaven/Cataclysm-DDA#50261]
### Describe the bug

The .50 caliber rifle made by taking a browning and repurposing it as a single-shot weapon is behaving strangely and causing crashes in the current experimental.

After firing a shot of .50 BMG M33 Ball, the rifle still reads as loaded, but attempting to fire this phantom bullet causes the game to hang, then crash with no error message. The gun has to be manually unloaded then reloaded between each shot to prevent this effect.

Note: Despite crashing, I do not seem to have a crash.log file to upload, sorry.

### Steps To Reproduce

1.  Make a .50 Caliber Rifle, load it with ammo of choice (I've only tested this with the aforementioned .50 BMG M33 balls, might work with others)

2. Fire  the single round in the chamber

3. Check the gun, see that it is still somehow loaded despite having fired

4. Attempt to fire the  phantom bullet. (Game did not crash when I didn't have extra rounds on hand, but did produce an error message about an  unexpected ammo shortage)

### Expected behavior

Expected the gun to have no round in the chamber after firing, or at  least to not crash the game.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 8bf16a4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills]
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6887829/debug.log)

[Experimental Magic Land.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6887854/Experimental.Magic.Land.zip)

Archimond is the character experiencing this, please ignore my terrible naming sense and absurd stats.

**Comment by hexagonrecursion** [comment]
I am unable to open the attached save file - the world does not show up in the list. It looks like several essential files are missing.

**Comment by hexagonrecursion** [comment]
Can not reproduce.
- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: bc1f60e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills]
]
