### ISSUE TITLE
Allow mods to change person/town/region name lists

### ISSUE THREAD

**Issue by Cyrano7** [CleverRaven/Cataclysm-DDA#50263]
# Is your feature request related to a problem? Please describe.
We now have more setting changing mods that would benefit from names/flavor that can't be put on the vanilla lists.
Example: Aftershock replacing the name lists with more scifi/cyberpunk sounding names or references.
Example2: Dinomod adding some Jurassic Park references to their list for flavor.

# Describe the solution you'd like
Mods can include list of names. The mod lists can overwrite or add to the vanilla lists.

# Additional context
Essentially a reopening of this https://github.com/CleverRaven/Cataclysm-DDA/issues/33076

**Comment by kevingranade** [comment]
Pleased don't open already-closed issues unless, as it says, you are planning on working on it.  If you are, say so.
We have almost two THOUSAND open issues, we do not have the bandwidth to keep "it would be nice if somebody did x" issues around.
