### ISSUE TITLE
Joint should not be a military drop

### ISSUE THREAD

**Issue by eJ0opb** [CleverRaven/Cataclysm-DDA#50267]
### Describe the bug

Zombie soldiers frequently drop joints.  This should be unlikely, as cannabis remains illegal by US federal law, and there shouldn't be so many soldiers willing to risk their honorable discharge over weed.

### Steps To Reproduce

1. Visit a military base
2. Kill zombie soldiers
3. Observe how much weed there is on base

### Expected behavior

Definitely no weed on base.  Almost no weed from soldier corpses.

### Versions and configuration

- OS: [Debian 10]
- Game Version: [0.F bc28921]
- Graphics version: [Terminal]
- Ingame language: [English (US)]
- Mods loaded: [dda, no_npc_food, package_bionic_professions]

### Additional context

`mon_zombie_soldier_death_drops` includes `misc_smoking` which includes `joint`.

**Comment by actual-nh** [comment]
Given that they do drug testing, yes.
