### ISSUE TITLE
Combining like foodstuffs

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#50276]
# Is your feature request related to a problem? Please describe.
It'd be nice to merge or combine things that have slightly different ingredients.  Found animal cooking oil combining with self-made animal cooking oil should be possible.

# Describe the solution you'd like
I'd like to be able to get a notification asking if you'd really like to do this, and after it's done it takes the worse of the two items spoil times as the new spoil time for the whole.  Weighted average calorie & nutrition variables.  

So if you've got a 15.4 L of found cooking oil that spoils in 10 days, and you have 1 L of cooking oil made from human fat, spoils in a month, your new results will be 16.4 L of cooking oil with nasty stuff in it, spoiling in 10 days.

Also, if you add 1 cup of day from expiry oil to a nearly full 200L drum, don't be surprised when the whole thing goes rancid tomorrow.

# Describe alternatives you've considered
Having 20 different containers of cooking oil in my base.

# Additional context
I'm sure there's a bunch of other foodstuffs that this could also apply to, other than just the cooking oils, yeah?
Mustard, ketchup, mayonnaise, vinegar, etc.

Maybe even some of the chemicals too?

**Comment by RenechCDDA** [comment]
Per the last close wave, "we can not support issues asking for arbitrary content additions in the repo, there are too many issues."

That doesn't mean it can't be added, just that the issue can't sit around stale forever.
