### ISSUE TITLE
More versions of "transform" in item_actions

### ISSUE THREAD

**Issue by Basher6079** [CleverRaven/Cataclysm-DDA#50277]
# Is your feature request related to a problem? Please describe.
I've been trying to recreate the Service Weapon from Control, which has multiple forms it can switch between. Unfortunately, even though multiple transform actions can be placed on an item, only the first command is recognized by the game. This means I have to transform in a loop, switching types sequentially until I reach the one I want. Additionally, any other multi-form items would have to use a system like this.

# Describe the solution you'd like
Adding additional transform commands, like transform_a, transform_b, etc. with identical functionality but different ids should allow multi-transformation items. This should also cause no issues form existing transforming items, just add more options for future content.

# Describe alternatives you've considered
A better solution would be if the game could accept multiple transform actions on a single item, but I think that would be far harder. I have also tried substituting actions like fireweapon_on for transform, but non-transform commands are far more restricted.

# Additional context
Current Example:
    "use_action": [
      {
		"type": "transform",
		"menu_text": "Switch to spin",
		"target": "service_weapon_spin",
		"msg": "The Service Weapon reconstructs itself into a round array of plates."
      }
    ]

Proposed Example:
    "use_action": [
      {
		"type": "transform",
		"menu_text": "Switch to spin",
		"target": "service_weapon_spin",
		"msg": "The Service Weapon reconstructs itself into a round array of plates."
      },
      {
        "type": "transform_a",
        "menu_text": "Switch to shatter",
        "target": "service_weapon_shatter",
        "msg": "The Service Weapon reconstructs itself into a cloud of solid blocks."
      },
      {
        "type": "transform_b",
        "menu_text": "Switch to pierce",
        "target": "service_weapon_pierce",
        "msg": "The Service Weapon reconstructs itself into an empty barrel supported by thin long pyramids."
      },
      {
        "type": "transform_c",
        "menu_text": "Switch to charge",
        "target": "service_weapon_charge",
        "msg": "The Service Weapon reconstructs itself into a heavy triangular barrel."
      }
    ]

In the current game, switching from the first type to charge takes four transformations. With this change, it could be done in one.

**Comment by actual-nh** [comment]
It would be nice if the current bug regarding use of charges according to the transformed-into item was fixed alongside this; @Salty-Panda?

**Comment by Basher6079** [comment]
I know that if you transform into an item that can't hold as many charges as the original has, all charges are lost. However, if the new item can hold the current charges, charges are kept.

Example 1: Form 1 has 7/8 charges, Form 2 can hold 50, after transformation Form 2 has 7/50 charges.

Example 2: Form 2 has 37/50 charges, Form 3 can hold 20 charges, after transformation Form 3 has 0/20 charges.

**Comment by Salty-Panda** [comment]
A nice fix for the bug would be to move `charges-per-use` inside `use_action` object.
It would also allow for making items with multiple abilities of varying costs, e.g. ring that can cast more than one spell with varying costs.

**Comment by Hirmuolio** [comment]
Smartphone can turn into two different items when it is activated. 
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/items/tool/electronics.json#L514

Not sure how hardcoded the options are.

**Comment by Salty-Panda** [comment]
AFAIK that only works because only one option is json-only.

**Comment by new02DAY** [comment]
Would duplicating the [iuse_transform](https://github.com/CleverRaven/Cataclysm-DDA/search?q=iuse_transform) function and creating a new `iuse_transform_a`, etc. work?

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
