### ISSUE TITLE
Using a tailoring kit to permanently remove pockets from gear

### ISSUE THREAD

**Issue by Marrim** [CleverRaven/Cataclysm-DDA#50274]
# Is your feature request related to a problem? Please describe.
Gear like the leather armor, swat armor, armored jacket etc often has a few small pockets that provide minor storage space but end up adding encumbrance for the whole armor when used. Some players may want to avoid using them.

# Describe the solution you'd like
Removing pockets feels like a sensible option for customizing your clothing, so I propose to make this doable via the tailoring kit. The item would become slightly lighter, but not necessarily less encumbering (would just have the encumbrance of the gear in question when completely empty). It does need some sanity checks, e.g. "removing" the main storage space of a rucksack or a holster is nonsensical--perhaps exclude all items in the "storage" subcategory?

# Describe alternatives you've considered
1) Pocket settings already let you blacklist everything from a pocket but the game will still occasionally put stuff in it (allegedly when there's no other room for the item, but I'm not sure), and its volume is still counted when displaying total available volume.
2) Implement complete disabling of pockets in the pocket settings menu, so they don't count when calculating available space on the inventory / multidrop / pick up screens and perform for all purposes as if they were not there.
3) Implement a new type of survivor suit completely without pockets. This would solve things for me personally, but I would like to hear opinions on a more in-depth solution.
4) Option to remove pockets via other items (cutting tool or sewing kit).

# Additional context
None

**Comment by GuGuyCDDA** [comment]
I would love to have the option to ADD pockets to existing clothes to add storage.
for example, we could add loops to backpacks to hold crowbars or entrenching tools, or small hatchets, for the cost of encumberment and very slow draw speed.

**Comment by Brambor** [comment]
I didn't know about blacklisting pockets, I wonder where that's mentioned, I will look into that. But I have the same issue. Armour being more encumbering because I don't know how can I forbid using it's pockets.

**Comment by BHasselaar** [comment]
Rather than blacklisting every single thing from all armour pockets you could set the priority to something like -20 (default being 0) in the same auto-pickup options menu

**Comment by Broken27** [comment]
Yeah, the workaround a lot of people use for this is using the _whitelist_ not the blacklist - If you whitelist an item, the pocket won't accept anything else, so just whitelist something huge than won't fit in the pocket and the pocket will not take any items.

**Comment by chrispikula** [comment]
The biggest issue with the negative priority bit is that it'll still fill up.  Whitelists are the way to do it, if but cumbersome and hodgepodge.

**Comment by KittyTac** [comment]
> 
> 
> I would love to have the option to ADD pockets to existing clothes to add storage.
> for example, we could add loops to backpacks to hold crowbars or entrenching tools, or small hatchets, for the cost of encumberment and very slow draw speed.

Yep! This would be complex to implement but very fun. I'd like more options for customizing gear in general.

**Comment by Marrim** [comment]
Yeah, when I said blacklisting pockets I didn't mean painstakingly blacklisting every item. Sorry for the confusion. You use whitelist of course.
However, like I said, it's not an ideal solution: disabled pockets still count in calculating total volume, which leads to incorrect figures. And I'm pretty sure sometimes items still get put in.

_Adding_ pockets is beyond the scope of this suggestion.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
