### ISSUE TITLE
Colloidal Silver supplements

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#50282]
# Is your feature request related to a problem? Please describe.
Have you ever felt blue?  What about feeling like making yourself blue?  Colloidal Silver can cure what ails you!

# Describe the solution you'd like
We already have homeopathic pills, why not their older, more expensive cousin?  Take some pills, get permanent Argyria, which gets worse the more you take.

A temporary mood boost, inversely proportional to intelligence.  Stacking Argyria condition, maybe removable with a high-end CBM?  Uncommon pain and fatigue hits, very rare torso damage, and very rare stuns(seizures) should be the symptoms at the worst level.  Reduced antibiotic effectiveness as well.

# Describe alternatives you've considered
Not including the shames of our forefathers.

# Additional context
It'd be neat to have a challenge scenario, or 'rider' option like this that reduces the effectiveness of antibiotics.  I don't think we've got anything close this, have we?

**Comment by actual-nh** [comment]
You forgot skin cancer...

**Comment by Broken27** [comment]
>A temporary mood boost, inversely proportional to intelligence. 

This isn't really good mechanics. Believing in quackery isn't really related to intelligence.

**Comment by chrispikula** [comment]
> This isn't really good mechanics. Believing in quackery isn't really related to intelligence.

Fair, so make it statless, s.t. anyone who's willingly takes it believes it'll work?

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
