### ISSUE TITLE
No available scenarios after exiting Aftershock Total Conversion world and starting another world.

### ISSUE THREAD

**Issue by freijie** [CleverRaven/Cataclysm-DDA#50287]
### Describe the bug

After creating aftershock total conversion world, then exiting to main menu and making a new world, scenarios tab for new character will be empty.

### Steps To Reproduce

1. Crate a world with Aftershock Total Conversion
2. Start in this world
3. Exit to main menu
4. Start new game in non-total conversion world
5. Your scenarios tab will be empty

### Expected behavior

Scenarios should be reset to current world mods.

### Versions and configuration

- OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
- Game Version: 2b9d8f5
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: aftershock total conversion on/off

**Comment by hexagonrecursion** [comment]
I can not find a mod named "Aftershock Total Conversion", but I can reproduce the same effect with "Aftershock: Exoplanet"

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 113660b [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Aftershock: Exoplanet [aftershock_exoplanet]
]

**Comment by actual-nh** [comment]
Looks like the scenario blacklist (or whitelist?) doesn't get cleared properly when a mod gets unloaded?

**Comment by John-Candlebury** [comment]
Yes it looks like the whitelist isnt being cleared properly, Dark Skies Above has the same issue,
