### ISSUE TITLE
Vehicles reset body temperature to 0, even without any sort of AC system

### ISSUE THREAD

**Issue by KittyTac** [CleverRaven/Cataclysm-DDA#50297]
### Describe the bug

Inside vehicles your body temperature is always 0 (comfortable), no matter the clothing or the weather outside.

### Steps To Reproduce

1. Make a character of a profession that starts with a vehicle.
2. Enter the vehicle.
3. Walk around a bit, perhaps take control of it.
4. Press @ to check temperature.

### Expected behavior

For all vehicles (even custom-built carts) to not have a magical AC system that takes no power or anything.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: f40b533 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Kittymod [kittymod],
    Tankmod: Revived [Tankmod_Revived],
    Tankmod: Revived - UndeadPeople Tileset [Tankmod_RevivedUDP],
    No Fungal Monsters [No_Fungi]
]

**Comment by ZeWoll** [comment]
Can confirm, after waiting for 50 seconds sitting around inside a semi-truck, temperature changes to 0, my hands show 13 warmth, wearing work gloves.
I'm using the default mods and latest game version.

**Comment by RoyBerube** [comment]
Character::in_climate_control() in character.cpp is where it is happening. It just checks if the vehicle has power available and the doors are closed. The engine does not need to be running.

Adding a check for a running engine should be enough to fix this.
