### ISSUE TITLE
Various guns don't work properly

### ISSUE THREAD

**Issue by ZeWoll** [CleverRaven/Cataclysm-DDA#50299]
### Describe the bug

When shooting with the following guns: 
**S&W 619, S&W 500, S&W 629, S&W Model 10, shotgun revolver, 10mm/ .40 revolver, pipe rifle**
Inventory shows that no ammo has been used, the gun cannot be reloaded either and when unloading the gun, only the unused bullets appear, no casing fall on the floor.
Game has crashed a couple of times while testing which guns don't work properly.
Also, when trying to aim the gun after all the bullets have been used, the following error appears:

 DEBUG    : Exceeded allowed range!

 FUNCTION : bool target_ui::set_cursor_pos(const tripoint&)
 FILE     : src/ranged.cpp
 LINE     : 2442
 VERSION  : 2b9d8f5

### Steps To Reproduce

1. Spawn a S&W 619 or any other gun from the list
2. Wield and shoot at anything
3. Check inventory and gun still has all the bullets despite having used 1 bullet

### Expected behavior

Guns should show remaining ammo, we should be able to reload them properly, without the need to unload them each time and we shouldn't be able to aim without ammo in the gun.

### Screenshots

![image](https://user-images.githubusercontent.com/88143686/127487220-1cd46fc7-8ccc-4195-9c67-172526e11342.png)
Inventory before shooting
![image](https://user-images.githubusercontent.com/88143686/127487295-d0c48bd1-98a6-41dc-8420-1c4f2dd9486e.png)
NPC is alerted by the shot
![image](https://user-images.githubusercontent.com/88143686/127487326-c3478e2b-b462-4557-bfab-6b354ff16bec.png)
Gun is still full

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 2b9d8f5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by actual-nh** [comment]
@AdamChirnside has had this error also, in #50311.
