### ISSUE TITLE
Sunrise happens at 3AM

### ISSUE THREAD

**Issue by Marrim** [CleverRaven/Cataclysm-DDA#50298]
### Describe the bug

Observing sunrises as early as 02:45 in the summer, by 03:00 everything's already brightly lit.
Happens consistently (assuming the weather is clear) on fresh game start (Spring 61) and in my current game (Summer 22), both times at 3 AM.

### Steps To Reproduce

Start the game at 6 AM, observe it's already bright as midday.
During the first night, select "Wait till daylight", observe the proposed time of wait.
Wait till about 03:00. The sun rises.
If this does not reproduce for other people, I'll attach a save.

### Expected behavior

Expecting the sun to start rising at 5-6 AM or so.

### Screenshots

![morning1](https://user-images.githubusercontent.com/11006744/127472373-ac8dacb2-9b6a-4976-b748-ca30f22075f3.png)
![morning2a](https://user-images.githubusercontent.com/11006744/127472386-35938bae-81ca-4ad8-be78-0426648eb1c0.png)
![morning2b](https://user-images.githubusercontent.com/11006744/127472398-c261d74e-4a99-44ae-8879-6d88738dd5fc.png)

### Versions and configuration

Ubuntu 18.04
Game Version: 0.F experimental f1b6e7d
Terminal.
Default mods + StatsThroughKills.

**Comment by GuardianDll** [comment]
Ive just checked, and yes, in Boston (Massachusetts, New England) the dawn starts on 5 am, so its okay to make same time in the game(if there is no some mistake in my fast google search)

**Comment by definitelynotklip** [comment]
Potentially fixed in #50068.
