### ISSUE TITLE
'Crossdresser' & 'Cosplayer' traits

### ISSUE THREAD

**Issue by big-smitty** [CleverRaven/Cataclysm-DDA#50290]
# Is your feature request related to a problem? Please describe.
Right now catalysm is at 9.5/10. Adding these traits would really push it 11

# Describe the solution you'd like
Crossdressers should get a moral buff when wearing items for the other gender. Males would get it from wearing heels, gowns, dresses, panties, skirts, bras, etc. Females would get it from wearing a tuxedo or a tie something. Idk you could probably get away with using a cowBOY hat or some kind of rugged jeans. Maybe for using a haircut kit or wearing a wig? 

Cosplayers would get a moral buff from wearing cosplay things like cat ears or other cosplay garb that is already in-game

# Describe alternatives you've considered
There are none. Myself and probably thousands of others refuse to play c:dda unless their character gets the happies from looking like a sexy anime cat-girl drag queen

# Additional context
For reference. This c:dda fanart is exactly what i'm envisioning is the future of catalysm. Catgirl survivors for miles
![image](https://user-images.githubusercontent.com/85451361/127406333-cf0e1f92-823b-4be0-9a8c-eea1e4754704.png)

**Comment by anothersimulacrum** [comment]
Yeah, we would have to annotate clothing as belonging to a gender, and I do not think we should do that.

**Comment by kevingranade** [comment]
Big nope, I'm also not a fan of trivializing people's lifestyle choices to just be a morale buff.
