### ISSUE TITLE
some one f****ed all the other expermantal builds there's only andriod x32 builds now! who let that pull that made the automatic experimental builder do only andriod 32x?

### ISSUE THREAD

**Issue by ashtiboy** [CleverRaven/Cataclysm-DDA#50308]
### Describe the bug

there's only android x32 on the latest expamant builds on the main website experimental builder! this has just  happened yesterday!
 devs if you say there other builds! but i counterpoint the argument in a funny joke i saw on the internet that would summarize the issue! when i say the meme: there's only soup but it's CCDA androids 32x builds instead! it goes like this: me: i can't find the builds! devs: there on the main website. me: there's only android builds! devs: but there's should be more than that! look at the auto build page! me: i am at the main auto builds page, there's only anodiods builds!    devs: what? me: there's only android builds!: devs: why are there only android builds! me: i don't know it all started yesterday!
devs: them make your own builds! me: i don't know how if there's no proper frameworks! if the auto builder can't do it then its f****ed! devs: oh f**** what happened! 

that's the how the discussion would go for the most part! i don't know how the mac os x framework build bug fix pull didn't get through! but the android auto build exclusive pull did somehow! and now almost all the builds that are not x32 android build are now f*****ED! 

### Steps To Reproduce

don't know how

### Expected behavior

there should be experimental builds for windows linux and mac os x and others!

### Versions and configuration

mac os x 10.13.6 (not that it matters at this ponit)

### Additional context

can't make a log if there's no experimental build to use! and i don't knida know how to do a build on my computer if theres no upto date files that a can make a build with anyway! BESCUER THERE'S NO FRAMEWORK for windows linux or mac os x that's useful anymore! even for the main experimental auto builder too since yesterday!

**Comment by ashtiboy** [comment]
hey i'm serious! check the auto builder web page! there's only 32 bit android builds on there! i couldn't find all the other builds! im VERY SERIOUS! there's no other builds other than 32 bit android builds! i have checkd myself ther no other build like at all! and it happens just yesterday form the build date!

**Comment by anothersimulacrum** [comment]
Calm down.
It looks like something on GitHub's end.
This is the last build that ran:
![image](https://user-images.githubusercontent.com/42699974/127562410-fa6c99a8-9cb6-4514-b86f-2c4491507325.png)
All the other builds since are:
![image](https://user-images.githubusercontent.com/42699974/127562595-a8c85f05-05e0-42d4-890a-c0c2dd564e36.png)
And there's one running right now:
![image](https://user-images.githubusercontent.com/42699974/127562532-ac7abf31-c787-464c-8385-a11852580fdc.png)

**Comment by ashtiboy** [comment]
oh okay thats what happened! way can't it build the other ones at the same time!

**Comment by ashtiboy** [comment]
it's still looks like someone F**** up the auto builder with one of the pulls that happened yesterday!

**Comment by ashtiboy** [comment]
so how did gethub get on the friz this time?

**Comment by ashtiboy** [comment]
well i'm going to close this issue now its just github on the frizz
