### ISSUE TITLE
Character templates don't show proficiencies at character creation

### ISSUE THREAD

**Issue by Broken27** [CleverRaven/Cataclysm-DDA#50301]
### Describe the bug

When you make a template of a character, it doesn't save any proficiencies said character has.

### Steps To Reproduce

1: Start a new character, debug yourself all proficiencies, save.

2: Make a template of the character.

3: Start a new game with the template, confirm the character creation screen doesn't show proficiencies

### Expected behavior

Templates should exactly copy the original.

### Screenshots

![127561007-cd94c95d-d7a3-4535-8161-9ab23a094b5f](https://user-images.githubusercontent.com/67008253/127577324-c982b855-66cd-495e-adcb-b6f3242ef526.jpg)

### Versions and configuration

- OS: Windors 10
- Game Version: 0.F-2b9d8f5 (2021-07-27 build).
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: only dda.

**Comment by Broken27** [comment]
Edit: Ok, i was a bit too hasty with my report - The template *does* actually save proficiencies, it just happens that they won't appear in the character creation screen:

![Screenshot - 29_07_2021 , 22_25_57](https://user-images.githubusercontent.com/67008253/127561007-cd94c95d-d7a3-4535-8161-9ab23a094b5f.jpg)

But when the game starts, the proficiencies are actually there.

So it's just a minor interface error.

**Comment by actual-nh** [comment]
@AccountAlias, would you like to take a look at this?

**Comment by AccountAlias** [comment]
I'll take a look when I get some free time :)

**Comment by AccountAlias** [comment]
fix included under #50262 to prevent merge conflicts
![image](https://user-images.githubusercontent.com/85119255/127582028-a370f550-46ce-42df-89ae-21ba0d43f66d.png)
