### ISSUE TITLE
Composite crossbow description doesn't match materials

### ISSUE THREAD

**Issue by Fireiy** [CleverRaven/Cataclysm-DDA#50315]
### Describe the bug

Composite crossbow describes itself as "A modern moderately powerful hunting crossbow with fiberglass limbs."

### Steps To Reproduce

Spawn a composite crossbow.
View description.

### Expected behavior

The description should match the materials it's actually made out of.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by actual-nh** [comment]
Specifically, it should have materials of "steel" and "plastic", not "wood" and "bone".

**Comment by Fireiy** [comment]
That would also require the crafting recipe to be updated to be more in-line with the compound greatbow. I believe that the description should actually be changed to match the materials rather than the other way around, as it represents a medieval style crossbow with the limbs made out of composite materials rather than solely out of wood or metal. The current description would be more fitting for a modern crossbow.

**Comment by actual-nh** [comment]
You are correct. Perhaps "A traditionally-constructed crossbow made from wood, bone, and sinew"?

**Comment by Fireiy** [comment]
Copying the description of the composite bow does seem good, they are just the same materials used differently after all.

**Comment by actual-nh** [comment]
Actually, the composite bow says horn, but seems to likewise be made from wood, bone, and sinew according to both its materials and its recipe.
