### ISSUE TITLE
Wooden split rail gates offer too much coverage

### ISSUE THREAD

**Issue by big-smitty** [CleverRaven/Cataclysm-DDA#50318]
# Problem Description
You should be able to see through 'Wooden split rail gate's.

# Describe the solution you'd like
Wooden split rail gates should have a coverage of maybe 40% and should be see-through-able.

# Describe alternatives you've considered
Rename Wooden split rail gates to Wooden privacy gate.

# Additional context
My character not being able to see through the wooden split rail gate:
![image](https://user-images.githubusercontent.com/85451361/127620763-dc7674fc-7a57-48cb-9f9d-c6192b3e3ab1.png)

The Google image search result of "wooden split rail gate" showing they are clearly not full coverage:
![image](https://user-images.githubusercontent.com/85451361/127620495-e9d025a6-281a-4307-8790-443e5a858c3a.png)

**Comment by hexagonrecursion** [comment]
The game has both t_splitrail_fencegate_c and t_privacy_fencegate_c. One is see-through, the other is not. Both have the same name: 
https://github.com/CleverRaven/Cataclysm-DDA/blob/ab9621dd20b699f24e20845bf7ff0eb62c84cd77/data/json/furniture_and_terrain/terrain-fences-gates.json#L959-L960
https://github.com/CleverRaven/Cataclysm-DDA/blob/ab9621dd20b699f24e20845bf7ff0eb62c84cd77/data/json/furniture_and_terrain/terrain-fences-gates.json#L748-L749
