### ISSUE TITLE
NPC movement dialogue effects

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#50310]
# Is your feature request related to a problem? Please describe.
Our ability to command and control NPCs through dialogue is getting really profound, but there is one huge gap still preventing a lot of quest lines: we have no way to move an NPC around the map.

# Describe the solution you'd like
We could use a few dialogue effects for this.

EDIT: See my comment for a much simpler way to do this after some sober thought.

## Targeting
First, we need a way to figure out where to put the NPC. I suggest we implement at least one, maybe all of the following:
- unique waypoints that can be placed in mapgen (especially update_mapgen), as zones or fields or something. You'd give the waypoint an `id` when placing it. The NPC would select the nearest waypoint of that ID when given a command related to it. If it helps, perhaps we should also consider making it possible to explicitly link a waypoint to a specific NPC when generating it. so for example in Dino Dave's NPC placement we'd add:
```
        { "class": "refugee_beggar2", "x": 55, "y": 2, "track_waypoint": [ "dave_fort" ] },
```
if waypoint `dave_fort` was not defined in the same map special we'd throw an error. The idea here is that with this we could avoid having to search for that waypoint, its tripoint location would cache with Dave when he spawns.
If we want an NPC to go to a waypoint in an entirely different overmap, we probably should ask the player to specify the name of the overmap, to expedite searching. I'd look at how update_mapgen does it and copy that.

- It should also be an option to move an NPC using x-y-z coordinates measured relative to their present location. I care for this option less, though. 
- Similarly we should be able to specify x-y coordinates in another overmap like how we specify mission targets.

## The commands
1. Probably the simplest to code: `clone` and `delete`. Copy the current NPC, their inventory, dialogue variables, effects, etc exactly as is, but put them in a new location. This would be one command. `delete` would be a separate one, removing the npc in question. We might also want a `delete_clone` option. This would be good for easy long distance travel: when you finish Dana Nunez' quest to get her to Tacoma ranch, we can just `clone` her there, and when you talk to her in Tacoma, `delete_clone` would remove the version of her in the old refugee center.
2. For shorter travel, we could use `walk_to`. I would suggest we have two versions of this, `force=true` and `force=false`. With `force`, if the NPC leaves the reality bubble, next time they load, they will be in their `walk_to` location, regardless of pathfinding. This would be the default. `force=false` means they'd save their current location when you leave and continue trying to path to destination when you return, probably.
3. For longer travel, we may want a special form of `walk_to` that does overmap pathing. I don't know enough about this to offer design solutions and I think it should wait.

# Additional context
I am sure we could find other uses for waypoints like this, such as using them in monster patrol paths as a shorthand, and also for npc patrol pathing and things.

**Comment by actual-nh** [comment]
@curstwist, @jbytheway: Any thoughts on how to best specify waypoints for NPCs?

**Comment by jbytheway** [comment]
If we reuse an existing structure for waypoints then I think zones are the obvious choice. Or they could just be a new thing entirely.

I'm not a fan of the idea of cloning NPCs. We can't have two NPCs with the same id existing at the same time. I'd say for long distance travel we have three options (two of which you already suggested)

1. NPC walks to edge of reality bubble, and then teleports to destination.
2. NPC remains where they are, but once the player moves far enough away that they are outside the reality bubble, they teleport to the destination.
3. As case 1, but we somehow model the overmap movement of the NPC (I believe there's already code for this)

**Comment by I-am-Erk** [comment]
So, some thoughts with time between writing this and now:
1. We already have a teleport function. I think we can skip `clone` and `delete` and instead just use our existing teleport function as an effect rather than a spell/debug command
2. The waypoint system I outlined here would be great but is probably too much. It would be very helpful to add it later, but for a first pass we could instead have the following:
```
"walk_to": { "x": x, "y": y, "overmap_id": "om_id", "force": true }
```
where overmap_id is optional - we assume the current overmap otherwise. x-y coordinates are based on absolute overmap locations. "force" is as above.

plus the complementary:
```
"walk_to: "home"
``` 
which would take the NPC back to the place they spawned. We might also allow:
```
"walk_to": { "x": x, "y": y, "set_home": true }
```
which would walk an NPC to a new location and treat that location as home from now on.

**Comment by I-am-Erk** [comment]
I need to test out the new functionality, I suspect this is closed though. I'll reopen if there's something I still wish.
