### ISSUE TITLE
Disassembly sometimes requires tools that should only be used in assembly

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#50313]
### Describe the bug

If you disassemble any item that use the new vacuum molding quality they require you to have a vacuum mold and then it gives you polycarbonate sheets.   Which is not how this should work.   I'm thinking there could be an easy fix here by going to crafting.cpp going to line 2071 
```
for( const auto &opts : dis.get_tools() ) {
        const bool found = std::any_of( opts.begin(), opts.end(),
        [&]( const tool_comp & tool ) {
            return ( tool.count <= 0 && inv.has_tools( tool.type, 1 ) ) ||
                   ( tool.count  > 0 && inv.has_charges( tool.type, tool.count ) );
        } );

        if( !found ) {
            const tool_comp &tool_required = opts.front();
            if( tool_required.count <= 0 ) {
```
I was thinking you'd drop an if statement in here to return zero if it's the vacuum mold or has some No_disassembly flag.  But I'm less sure of that now.

### Steps To Reproduce

Try and disassemble any item that uses molding.

### Expected behavior

That the spent components used to hand craft single use molds don't magically reform whole and unused when you crack open an electric carving knife.

### Versions and configuration

- OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
- Game Version: [from the main menu, e.g. 0.C-29938-g90f5268437]
- Graphics version: [Tiles or Terminal]
- Ingame language: [Arabic or Bulgarian or Chinese (Simplified) or Chinese (Traditional) or Dutch or Esperanto or French or German or Italian (Italy) or Japanese or Korean or Polish or Portuguese (Brazil) or Russian or Serbian or Spanish (Argentina) or Spanish (Spain) or Turkish]
- Mods loaded: [e.g.dda, boats, hacktheplanet, StatsThroughSkills]

**Comment by Zireael07** [comment]
Note that this is a generic problem with the crafting system that the vacuum molds exposed, but I'm 99% there's a report of that for another item, too.
