### ISSUE TITLE
Craft time disparity: bone broth

### ISSUE THREAD

**Issue by DalenTalas** [CleverRaven/Cataclysm-DDA#50324]
### Describe the bug

Crafting a 3L jar of bone broth takes about an hour. Crafting the same amount (12 units) of bone broth without a jar takes about 3 hours.

### Steps To Reproduce

1. Get a pile of bones, some water, cooking implements, and a 3L jar.
2. Check cooking times for canned broth and loose broth.

### Expected behavior

Crafting canned broth should take slightly longer instead, to account for the canning process.

### Versions and configuration

- OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
- Game Version: [from the main menu, e.g. 0.C-29938-g90f5268437]
- Graphics version: [Tiles or Terminal]
- Ingame language: [Arabic or Bulgarian or Chinese (Simplified) or Chinese (Traditional) or Dutch or Esperanto or French or German or Italian (Italy) or Japanese or Korean or Polish or Portuguese (Brazil) or Russian or Serbian or Spanish (Argentina) or Spanish (Spain) or Turkish]
- Mods loaded: [e.g.dda, boats, hacktheplanet, StatsThroughSkills]

### Additional context

The question is whether to increase cooking time on canned broth, or decrease cooking time on "loose" broth.

**Comment by Saicchi** [comment]
Since cooking proficiencies are going to be added, decreasing the cooking time should be fine.
