### ISSUE TITLE
Can't load 2nd clip on 14-round tube shotgun

### ISSUE THREAD

**Issue by pontim** [CleverRaven/Cataclysm-DDA#50329]
### Describe the bug

Can't switch to 2nd magazine to reload

### Steps To Reproduce

fully load first magazine, aim and switch with (o). It says "Can't reload the 14-round tube shotgun." Doesn't seem to be any way to load it

### Expected behavior

I expected to switch the the 2nd magazine and reload

### Screenshots

![image](https://user-images.githubusercontent.com/5273559/127685386-0d6da8be-c568-497c-8f2c-9fa4ad21193c.png)

### Versions and configuration

- OS: Windows 10
- Game Version: f1c4129
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: Stats through kills, Bionic Professions, Disable NPC Needs, Dark Days Ahead

**Comment by Menschheit** [comment]
Should be fixed by #50281
