### ISSUE TITLE
Associated hotkey to a item gets lost after being wielded

### ISSUE THREAD

**Issue by OneThousandResets** [CleverRaven/Cataclysm-DDA#50323]
### Describe the bug

Self explanatory.

### Steps To Reproduce

If you use (i) Inventory -> (=) reassign to give a letter to an item, (w) wield the item, and put it away (w) back into a storage, the letter assigned gets lost.

### Expected behavior

The assigned key should stick.

### Versions and configuration

Windows 10
Version 64x-tiles  15dd993
mods used: statsThroughkills, speedydex, bionic slots,

**Comment by OneThousandResets** [comment]
Just now saw this issue being discussed in merge request #50173.
Godspeed.

**Comment by actual-nh** [comment]
Duplicate of #50154.

**Comment by exuvo** [comment]
Feel free to test the patches i have in that merge request. Might speed the approval up if more people have tested that my patch does not break anything else.
