### ISSUE TITLE
Attempt to look at recipe for candle or jack o' lantern crashes the game

### ISSUE THREAD

**Issue by LaVeyanFiend** [CleverRaven/Cataclysm-DDA#50335]
### Describe the bug

You cannot craft or even look at the recipe for candles or jack o' lanterns.

### Steps To Reproduce

1. Debug give all recipes.
2. Attempt to look at the recipe for candle or jack o' lantern.
3. Game crashes before you can see it.

### Expected behavior

No crash

### Screenshots

N/A

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: b781a0e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by mqrause** [comment]
#50334 just got merged.
