### ISSUE TITLE
Build Bookshelf (*)

### ISSUE THREAD

**Issue by big-smitty** [CleverRaven/Cataclysm-DDA#50338]
# Is your feature request related to a problem? Please describe.
You can't build a bookshelf from the construction menu (*). I would like to.

# Describe alternatives you've considered
Making it from the craft menu, then placing it. This is a worse option.

**Comment by anothersimulacrum** [comment]
![image](https://user-images.githubusercontent.com/42699974/127716458-9a46cb81-3dcd-4952-a0f6-a4d79b899c74.png)

**Comment by big-smitty** [comment]
@anothersimulacrum I'm an idiot. I searched for "Bookshelf" and not "Bookcase". Should I delete this issue?

**Comment by anothersimulacrum** [comment]
No big deal. I'll close it.
