### ISSUE TITLE
Game crashes when trying to choose candle or jack o'lantern in crafting menu.

### ISSUE THREAD

**Issue by ZulDjinn** [CleverRaven/Cataclysm-DDA#50332]
### Describe the bug

Game crashes when trying to choose candle or jack o'lantern in crafting menu. Perhaps some other recipes can also cause the game to crash.

### Steps To Reproduce

1. Open crafting menu.
2. Find candle or jack o'lantern recipe and try to choose.

### Expected behavior

Successfully craft this items.

### Versions and configuration

- OS: Windows 7
- Game Version: fc6d52f [64-bit]
- Graphics Version: Tiles
- Game Language: System Language
- Mods loaded: [dda]

**Comment by actual-nh** [comment]
What do you mean by "crash"? Crash to desktop, or an error message popping up (that you can go on despite), or what?

**Comment by Zeropol** [comment]
I can confirm for both the candle and jack o'lanternc ( other lanterns are fine ) 
CTD, debug.log don't contains info about the crash.

Only in the crafting menu, we are still able to interact ( spawn, grab, light ) the candle.

**Comment by ZhilkinSerg** [comment]
![image](https://user-images.githubusercontent.com/16213433/127696441-16cea3dc-cdf9-4bf1-b8cd-9837963a0af4.png)
