### ISSUE TITLE
Tabbing from Profession to Hobbies tab with negative point total causes accumulation of negative points

### ISSUE THREAD

**Issue by BriscoLargg** [CleverRaven/Cataclysm-DDA#50337]
### Describe the bug

Tabbing from Profession to Hobbies tab with negative point total causes accumulation of negative points

### Steps To Reproduce

1. Create a new custom character
2. Give them the Park Ranger profession so they have -1 points
3. Tab to Hobbies tab - Park Ranger points have been subtracted again to -10 total
4. Repeat by backtabbing to Professions and back to Hobbies

### Expected behavior

Negative points are applied to total selected attributes and do not accumulate.

### Screenshots

![image](https://user-images.githubusercontent.com/55927101/127708420-252077fa-a282-420e-928e-1ae3a71b4112.png)

### Versions and configuration

- OS: Windows 11 dev channel
- Game Version: 2021-07-30-1907 - 78074C6
- Graphics version: Tiles
- Ingame language: - English
- Mods loaded: DDA, Disable NPC Needs, Bionic Professions

**Comment by Istoprocent** [comment]
I can confirm that. Got -5 points each time I tabbed from professions to hobbies (including the initial tab). Any hope for a quick fix?

**Comment by actual-nh** [comment]
Ping: @AccountAlias?

**Comment by AccountAlias** [comment]
whoops, bad copy-pasta is bad. Fix has been PR'd, thanks for the heads up!
