### ISSUE TITLE
Hobbies give unexpected amount of XP(past level 1)

### ISSUE THREAD

**Issue by LaVeyanFiend** [CleverRaven/Cataclysm-DDA#50340]
### Describe the bug

Hobbies only gives the XP required to level up from whatever is specified for the level granted from the previous level, when it should do that + all XP from the previous levels.

Ex. Lvl 1 hobby grants 10k experience/ lvl 2 hobby 40k/ lvl 3 90k, which is the XP to go from 0-1/1-2/2-3 respectively. This means a level 2/3 hobby gets you to 1.75 skill and 2.44 skill if you only pick that one.

### Steps To Reproduce

1. Make a hobby that gives skill XP beyond level 1.
2. Pick said hobby.
3. Get below expected XP.

### Expected behavior

Defining a hobby as a level beyond 1 gives the XP to level to exactly that.
(10k/50k/140k/300k for a level 1/2/3/4 hobby)

### Screenshots

N/A

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 78074c6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Yes I know about the intended diminishing returns from picking multiple hobbies, this applies if you just pick one.

Increasing the XP curve would preserve the diminishing returns meaning something if you pick overlapping hobbies.

**Comment by actual-nh** [comment]
Ping: @I-am-Erk?
