### ISSUE TITLE
Compound Crossbow and Heavy Crossbow should have better performance

### ISSUE THREAD

**Issue by Fireiy** [CleverRaven/Cataclysm-DDA#50352]
# Is your feature request related to a problem? Please describe.
One thing I've found strange is that compound crossbows have almost the same damage numbers as the compound hunting bow while having over twice the Joules in energy. Similarly, the heavy crossbow has comparable velocity to the compound hunting bow but has significantly less damage. I believe that this problem arises from how the damage calculation for archery only takes into account momentum, while ignoring contact area and kinetic energy aside from how they affect momentum. The smaller crossbow bolts as a result suffer in their damage calculations, largely ignoring their increased penetration capabilities.

The below stats are taken from data/json/items/ranged/archery.json and ranged/crossbows.json
|Weapon|Draw Weight|Draw Length|Projectile Mass|Kinetic Energy|Momentum|Base Damage|
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
|Compound Hunting Bow|60lbs|17in|30g / 463 grain|100J / 73.58 ft-lbs|0.55 slugs|10|
|Heavy Crossbow|800lbs|N/A|30g / 463 grain|~55.44J /40.89 ft-lbs|0.41 slugs|6|
|Compound Crossbow|175lbs|17in|20g / 300 grain|197J / 147.58 ft-lbs|0.636 slugs|13|

Unfortunately the data of the heavy crossbow in the json is incomplete so I've had to reverse calculate kinetic energy manually and do not know the draw length. It also provides slug values for a theoretical 0.5kg/7716 grain bolt that is not in the game and is ludicrously large. However in the videos linked below I have gotten the following stats.

|Weapon|Draw Weight|Draw Length|Projectile Mass|Kinetic Energy|Momentum|Velocity|Base Damage|
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
|Compound Bow|70bs|28.5in|27g / 416 grain|85J / 62.75 ft-lbs|0.48 slugs|260.6FPS|8|
|Windlass Arbalest|1000lbs|N/A|96g / 1482 grain|110J /73.8 ft-lbs|0.99 slugs|157.0FPS|23.3|
|Compound Crossbow|185lbs|15.75in|31g / 478 grain|183J / 135.0 ft-lbs|0.76 slugs|356.5FPS|16.4|

# Describe the solution you'd like
While I believe the current numbers match reality fine with all other bows and crossbows, the higher velocity crossbows suffer in comparison to the bows. I believe that the best way to simulate the increased kinetic energy that the compound has is to give it a base penetration stat in order to simulate how it can penetrate stronger armors, instead of increasing its base damage outright. I don't suggest that this should be applied to other crossbows however, as those line up fairly well with expected real life performance.

Meanwhile for the heavy crossbow I believe that new special bolts made specifically for the heavy crossbow should be added, a lighter one with 1.0 slug values and possibly a heavier one with 2.0 slug values and incredibly reduced ranges for the 0.5kg bolt, but also negative armor penetration values. This will allow it to more accurately replicate its real life capabilities of a incredibly slow but powerful projectile weapon, despite the slower velocity. This would give it a base damage of 23.6 and 53.6 respectively, allowing it to deal a decent amount of damage to moderately armored enemies, while hopefully only doing minor damage to the more heavily armored enemies. The noise it makes when firing should also be increased though still significantly quieter than even a suppressed 9mm pistol.

# Describe alternatives you've considered
Increasing the base damage of the compound and heavy crossbow by 3-4 points, increasing their overall capability.
Add a compound hunting crossbow with correspondingly higher stats instead.

# Additional context
This video measures the velocity and kinetic energy of several bows and crossbows including a 70lb compound bow and a 185lb compound bow, with a table at the time stamp provided near the end of the video. Unfortunately it doesn't feature the windlass crossbow.
https://youtu.be/bqqnYOYF7Po?t=498

This video measures the velocity and kinetic energy of a recreated 1000lb windlass crossbow firing a 96g / 1480 grain bolt.
https://youtu.be/kHnZo6ELEV0?t=483

And as a simple visual demonstration here's a video of various reproduction and modern bows and crossbows tested against reproduction butted and riveted mail armor, but no windlass crossbow here. The compound crossbow punches straight through both of the armors burying the full 21in down to the fletching, while the compound bow only penetrates the riveted mail armor for a decent 4.5in flesh wound and fails to penetrate the butted mail.
https://www.youtube.com/watch?v=eYsr81y0Aeo

This video only demonstrates medieval crossbows, but shows their inability to penetrate against breastplates and even a fairly shoddy reproduction of lamellar armor, although they do inflict moderate damage to the two armors. On the other hand a gambeson fares significantly worse against bodkin arrows, with the windlass scoring a deeply penetrating hit and the lighter crossbows inflicting flesh wounds.
https://www.youtube.com/watch?v=XMT6hjwY8NQ

**Comment by actual-nh** [comment]
A number of damage calculations I've seen for fragments settle on something like mass * (velocity ** 1.5), which is between kinetic energy and momentum.

**Comment by anothersimulacrum** [comment]
`**` meaning exponentiation?

**Comment by Fireiy** [comment]
That could work, though I'm unsure about the numbers that gets me.
For the heavy crossbow that gets a slug value of 0.54 for 10 base damage, the same damage as the current medium weight compound hunting bow.
For the compound crossbow that gets a slug value of 2.46 for 67 base damage, almost as much as the .300 winchester magnum.
And for comparison the compound hunting bow gets a slug value of 1.30 for 33 base damage, in between the .44 magnum and the .45 ACP JHP.

And of course these will also get multiplied by the ammo they're using, from 0.5 with small game ammo up to 1.5 and 1.75 with broadhead and carbon fiber ammunition. While applying it to only crossbows might work, it doesn't really simulate the armor penetration aspect well, instead simply buffing them massively against everything. Suggestions for how to convert these numbers to a armor penetration stat for the crossbows themselves would be welcome.

As an aside, I made a mistake by describing crossbow bolts as having a smaller contact area compared to arrows. While that is true with modern crossbow bolts, that is reversed for medieval ones. I also found out that those often had wooden fletching instead of feathers, though that might be better for a separate PR to update their recipes.

**Comment by kevingranade** [comment]
I've seen no credible sources arguing that arrow penetration is dependent on kenetic energy, and many credible arguments that it is directly dependent on momentum.
I also haven't seen a credible outline of how to calculate armor penetration, if you have one I'd love to take a look.
The larger projectiles would increase launch efficiency and therefore momentum and therefore damage output.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
