### ISSUE TITLE
Sludge Crawlers outregenerate being on fire

### ISSUE THREAD

**Issue by pehamm** [CleverRaven/Cataclysm-DDA#50358]
### Describe the bug

Not sure if this is a bug, but I am fighting a sludge crawler that is standing in a fire from a molotov for a bunch of turns and keeps its health in the green area. For good measure, I unloaded a full 5.56 magazine into it and it is still feeling fine, only panicking from the fire, HP still at 4 bars flat.

I saw that their regen function was changed as part of #49439, so I wanted to throw this out in case something broke there, as it was my understanding that the way to fight them is with fire.

### Steps To Reproduce

1. Load attached save
2. Admire the regen ability of the common crawler

### Expected behavior

Sludge crawler HP should sink slowly in fire, not stagnate at a high level. Their intended weakness seems to be fire, given how they are afraid of it, but it looks like their fear is utterly unfounded.

### Screenshots

![Screen Shot 2021-07-31 at 4 27 05 PM](https://user-images.githubusercontent.com/76401419/127743337-f43d9d43-2b8c-45b6-8d91-f26ab8877dc4.png)

### Versions and configuration

- OS: MacOs
    - OS Version: Name: Mac OS X; Version: 10.14.6; Build: 18G6020; 
- Game Version: 0.F-1137-g15dd9934ab [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[Groton.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6911326/Groton.zip)

**Comment by actual-nh** [comment]
Ping: @KorGgenT?

**Comment by pehamm** [comment]
Ooops, I was looking at the previous line, the regen has been like this for quite some time. Seeing the more recent responses on the frog mother which is also almost unkillable and much much more dangerous than the crawler, I will assume this is intended.
