### ISSUE TITLE
Dragging broken overloaded bike causes error collisions

### ISSUE THREAD

**Issue by EvaShark** [CleverRaven/Cataclysm-DDA#50354]
### Describe the bug

Grabbing and dragging a bike with no functional wheels that has a heavy load (4 solar panels) prints to the action log that "The bicycle collides with errors in movement code." but does not crash or throw the usual exception.

### Steps To Reproduce

Spawn a disabled bike, place 4 solar panels in its basket, attempt to Grab and drag the bike.

### Expected behavior

Either allow or disallow the bike to move, without throwing errors.

### Screenshots

![image](https://user-images.githubusercontent.com/13387397/127734964-a4465486-6c35-43a7-a608-a5773e91b560.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context
Tested, error does not occur with "like new" bikes

**Comment by Qrox** [comment]
#23000

**Comment by Night-Pryanik** [comment]
Closing as duplicate.
