### ISSUE TITLE
Cathedrals have walls of dirt

### ISSUE THREAD

**Issue by Hatfish** [CleverRaven/Cataclysm-DDA#50364]
### Describe the bug

While churches generate with the proper rock walls, cathedrals instead generate with walls of solid earth.  While earthen-walled places of worship are not unheard of in the wider world, they are very unheard of in New England.

### Steps To Reproduce

1.  Create a world.
2. Find a cathedral.
3. Note the walls are solid earth instead of stone.

### Expected behavior

Cathedrals would have stone walls.

### Screenshots

Cathedral with dirt walls.
![image](https://user-images.githubusercontent.com/8237862/127748262-196c27b3-bf14-4ff6-8ed7-dc38895c9407.png)

Another cathedral with dirt walls.
![image](https://user-images.githubusercontent.com/8237862/127748435-4cf87e52-292e-4276-b56a-f3157b8d98ed.png)

Church with the expected rock walls.
![image](https://user-images.githubusercontent.com/8237862/127748387-dd823b11-cc45-482f-a461-30163c7f1a86.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: a287fad [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations],
    sees-player icon, retrodays [sees_player_retro],
    No Fungal Monsters [No_Fungi],
    Bionic Slots [cbm_slots],
    Blaze Industries [blazeindustries]
]

### Additional context

I noticed that some cathedrals spawn without roofs, and some spawn with a mixture of dirt and flat roof.  That's a whole other issue though.

**Comment by occulti** [comment]
Looking to fix with pull request #50174 as part of change to stained glass windows in cathedrals

**Comment by hexagonrecursion** [comment]
This appears to have been fixed. Should this be closed?

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: c850e91 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by Night-Pryanik** [comment]
Ok, closing until reconfirmed.
