### ISSUE TITLE
Too much material recovery from cutting kevlar armor

### ISSUE THREAD

**Issue by BHasselaar** [CleverRaven/Cataclysm-DDA#50362]
# Is your feature request related to a problem? Please describe.
Layered kevlar panels are very sought after because they can be used to make some the best suits of armor in the game, requiring up to 48 panels a piece.
The skinning of kevlar zombies gives you a steady supply, given you manage to kill them and then sew the sheets into panels, each requiring 4 hours of crafting without the proficiency and with no batch savings.

All this work is trivialized by simply cutting a swat armor, sometimes dropped by swat zombies, and instantly getting 97 layered kevlar pannels, equivalent to 1552 (!) kevlar sheets or almost 3 kevlar zombies skinned and sewn together.
Kevlar vests suffer the same problem, spawning on swat and cop zombies and being cut into 35 layered pannels, because there is no disassemble recipe defined and their weight defines the amount and tpe of material harvested.

# Describe the solution you'd like
A couple options here I can see: 
1. I can see a possibilty of giving these items a `NO_SALVAGE` flag, similar to the kevlar dog harness, but this wouldn't solve much.
2. Define a disassemble recipe for them to give kevlar sheets, a mix of panels and sheets, or a reduced number of panels.

I'd like some help to discuss other ways to tackle the subject.

# Describe alternatives you've considered
Ignore and continue with unbalanced crafting materials recovery.

# Additional context
None.

**Comment by hexagonrecursion** [comment]
I can reproduce this
1. Set all skills to 0
2. Wish for: 
   * SWAT armor
   * pair of scissors
3. Activate the scissors -> Cut up an item -> SWAT armor
4. Get 91 layered kevlar panels

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: eec1398 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by Zireael07** [comment]
Likely to be fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/50463

**Comment by anothersimulacrum** [comment]
If this was not fixed in #50463, let me know and I can reopen it.
