### ISSUE TITLE
Most canning, pickling and vacuum sealing recipes have their calories calculated as if their ingredients are raw and not cooked while crafting

### ISSUE THREAD

**Issue by Post-Apocalypse-Potatoes** [CleverRaven/Cataclysm-DDA#50369]
### Describe the bug

After cooking canned vegetables using raw potatoes the calories of the canned vegetables were 121 and if the ingredients were consider cooked it should be 162. After this I tested on a debug world ,
using potatoes for vegetable components,
raw lung for the offal components,
fish fillet,
chuncks of meat,
normal mushroom for mushroom components, 
blackberries (because they are a raw fruit) for fruit components, 
sugar,
salt for the broths 
and flour for the mushroom soup,
 that every canning, pickling (both including using 3L and 0.5L jars) and vacuum sealing, asides from canned meat, pickled meat, meat soup, woods meat soup and vacuum packed salted meat slices, don't cook their ingredients as a part of the recipes. Also pickled offal lacks a 3L jar vesion even though there is such a version for canned offal.

Here is a list for all affected recipes.
Canned and pickled: veggy, fish, offal, fruit
Fruit jam and kompot (the 0.5l jar recipe for kompot also doesn't create a sealed glass jar so the food is not preserved)
Canned soups: broth, vegetable, mushroom, fish

I also forgot to test canning in tin cans so after I post this I will be doing that.

I did the testing on canning with tin cans. Just as the previous recipes only the recipes with chunks of meat works as expected but I did find out that for some recipes that include a choice of either chunks of meat or something else, such as those for wet cat food, when I do use meat the recipe does not have this problem but when I do use fillet of fish it does not work properly and in the item description of the food in the fields for it's ingredients it will display cooked meat for foods that has used meat as a components but in the case of the wet cat food it displayed fillet of fish instead of cooked fish.
Also canning recipes using chunks of meat and other raw ingredient, such as canned woods meat soup, would calculate as if the meat is the only raw ingredient that was cooked but not the other ones (in the test I did it was mushrooms) and just like the cat food recipe it will show cooked meat as a component but just mushroom for the mushroom component (in case it matters the other components are listed as broth, mesium tin can and scrap of metal).

### Steps To Reproduce

1. Debug in the tools (canning pot, a source of heat for cooking such as a hotplate and a vacuum sealer)
2. Debug in the ingredients that you wish to use
3. Craft the recipes
4. Calculate the calories that the recipes should have if they were using raw components and using cooked components
5. Compare the calculated results with the results in game

### Expected behavior

I expect that these recipes should be cooking their ingredients as a part of them as that alredy happens for regular meat recipes and the process for sealing and sterilising the sealed jar should also be enough tho cook the food in it.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 61be774 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by actual-nh** [comment]
Would pickling actually involve cooking the meat? See <https://www.cooksinfo.com/pickled-pork>, for instance.

**Comment by Post-Apocalypse-Potatoes** [comment]
> Would pickling actually involve cooking the meat? See https://www.cooksinfo.com/pickled-pork, for instance.
In game it does cook only chunks of meat and no other components. As for if pickling should cook the ingredients the in game recipes use a source of heat as tool that if it uses charges (such as a hotplate) the amount of charges is equivalent as that of the charges in the similar canning recipes (as an example in game pickling meat in a .5L gar needs 20 charges of a hotplate which is the same amount as that of canning meat in a .5L jar). Also in game pickling uses exclusive vinegar while in the site you linked me the non cooked variant of oickled meat uses brine, while the variant that uses vinegar does seem to be pre cooked. Another thing is that pickled meat can be used as an ingredient in a very small amount of recipes, mostly sandwiches and soups. So maybe there should be two different types of recipes for pickling meat: one that uses vinegar and pre cooks the meat, and one that uses brine (so just salt water in game) but does not cook the meat, does not use heat or uses less of it (I don't know if the process of sealing the jar shut needs heat) and can be used as raw meat ingredients in most if not all recipes needing raw meat.

**Comment by Post-Apocalypse-Potatoes** [comment]
I made a test mod in which I added the line
"cooks_like": "fish_cooked"
to the json item for raw fish and it did make canned fish have the proper calories that it should have had if it is cooked while canning. So maybe the problems with the other ones is something to do with such a line. I will continue testing and see if it works with other foods.

**Comment by RenechCDDA** [comment]
Last resolved by #65439 although calorie inheritance has been a sporadic problem since this issue was posted.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/157f5fbc-2536-42cf-80e0-9ead0f1354d4)


If this issue should come up in future searches, recipe::hot_result basically just checks if a hotplate is used anywhere in the recipe. If so, the result is heated up and regains the extra calories. (The other side of the check is removes_raw, which compares the components and result to see if the RAW flag is still around.)
