### ISSUE TITLE
Ridiculously high winds regardless of weather.

### ISSUE THREAD

**Issue by BritishLion** [CleverRaven/Cataclysm-DDA#50375]
### Describe the bug

With the "Dark Days of the Dead" mod enabled winds appear to be extremely high in game regardless of season or temperature.

### Steps To Reproduce

1. Start any new character and step outside.
2. Observe notes on lack of wind resistant clothing and very low perceived temperature in clothing tab.

### Expected behavior

I expected there to be at most moderate wind on a clear day in the middle of summer.

### Screenshots

![Screenshot_4](https://user-images.githubusercontent.com/88254894/127753636-718ab0e8-7fbd-46ee-aecf-1f995a55208a.png)
![Screenshot_1](https://user-images.githubusercontent.com/88254894/127753646-2e43909d-d2da-4c59-bf26-c33f7754b31a.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: be78ee9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Dark Days of the Dead [classic_zombies]
]

### Additional context

This occurs regardless of scenario, character, weather or season.
This only occurs when the "Dark Days of the Dead" mod is installed

**Comment by capSAR273** [comment]
Looks like the base_pressure for the classic_zombies region is set to 815 hPa, which is extremely low, implying very strong hurricane conditions. Maybe this causes a hurricane to exist simply because its that out of the norm? Other mods and the base game keep it to 1015 hPa. I'll test changing the mod's region to 1015 and see if that fixes it.

**Comment by actual-nh** [comment]
Ping: @I-am-Erk?

**Comment by capSAR273** [comment]
Looks like adjusting that base_pressure did the trick, changed it to 1015 for a new world, weather was clear. Made a world with 815 hPa and there is a freezing hurricane when you step outside.

**Comment by PokemanPhill** [comment]
> Looks like adjusting that base_pressure did the trick, changed it to 1015 for a new world, weather was clear. Made a world with 815 hPa and there is a freezing hurricane when you step outside.

How do you go about changing this? It is not showing up in my world generation options.
