### ISSUE TITLE
Overmap pathfinding for amphibious vehicles goes over land and does not avoid forests

### ISSUE THREAD

**Issue by anothersimulacrum** [CleverRaven/Cataclysm-DDA#50378]
### Describe the bug

When attempting to autodrive with an amphibious vehicle, it does not limit routes only to roads, and creates routes through the middle of forests.

### Steps To Reproduce

1. Spawn in a DUKW
2. Attempt to drive to somewhere far away from your current location on the overmap, or separated from you by a large forest
3. Watch as autodrive refuses to route you through a forest.

### Expected behavior

1. Autodrive does not attempt routes which will never be pathable.
2. The rules for whether or not you can drive off road are the same for amphibious and non-amphibious vehicles (except water is allowed for amphibious ones)

### Versions and configuration

- OS: Linux
    - OS Version: Arch, kernel 5.13.5
- Game Version: 0.F-1200-g61be774194 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

### Additional context

![bug](https://user-images.githubusercontent.com/42699974/127754911-e961bbb3-7cff-4154-b468-7920e18cb591.gif)

**Comment by actual-nh** [comment]
Ping: @eltank?
