### ISSUE TITLE
Radiation-proof container item(s)

### ISSUE THREAD

**Issue by AdamChirnside** [CleverRaven/Cataclysm-DDA#50374]
# Is your feature request related to a problem? Please describe.
Some materials are radioactive. It would be useful for an experienced survivor to be able to make a container, lined with Lead for example, to safely contain them. (But otherwise they should emit radiation in their vicinity)

# Describe the solution you'd like
An item or series of container items which could be cobbled together by a player with certain skill thresholds of Fabrication/Applied Science, which safely contain radioactive items.

# Describe alternatives you've considered
Avoiding radioactive items altogether.
Face-tanking the radiation and mitigating its effects with drug items, PPE, etc.

# Additional context
Stalker Anomaly has a Lead Lined Metal Container (LLMC) item which I think is particularly pertinent. The other containers from that game are probably too "Sci-Fi" for base CDDA.

**Comment by actual-nh** [comment]
Whether this will work would depend on exactly how strong (and what type of) radiation we're talking about. If you define "safe" as effects too small to reasonably represent in the game, and the source is of any significant amount of gamma radiation, the amount of lead sufficient is not going to be (portable) container linings - more like walls.

**Comment by chrispikula** [comment]
Would it make sense for the Exodii to have something like that?  Some sort of slightly out of dimension holding space that can only handle a bit of energetic radiation before it 'leaks'?

**Comment by actual-nh** [comment]
@I-am-Erk?

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
