### ISSUE TITLE
Non-heated recipes that could be crafted with frozen components should be enabled if there is an adequate source of heat

### ISSUE THREAD

**Issue by Svatopluk1** [CleverRaven/Cataclysm-DDA#50387]
# Is your feature request related to a problem? Please describe.
Non-heated recipes with frozen ingredients currently show up in the Crafting menu as disabled, same as if the character had no ingredients at all. This makes it so that, even with a ready source of heat, it becomes a UI nightmare to try to figure out what the frozen ingredients could be used for.

**Steps to observe the issue:**

1. Change the season to winter.
2. Change the weather to snowstorm.
3. Spawn an undamaged Luxury RV, and 2 raspberries just outside (will get frozen), a pot, a hammer, and a rag.
4. Stand next to the Luxury RV's built-in Hotplate, with the other components nearby.
5. Try to craft Fruit Juice.

When looking at Fruit Juice, the Crafting Menu simply pretends that you have zero raspberries, despite the availability of frozen raspberries and heat.

**Context and Discussion:**

Why is it a UI nightmare if you can just do a search, filtering for the particular frozen c:component?

Because you could have _multiple_ frozen components in non-heated recipes and all ingredients would show as if you had zero of them. Various types of sausages that use different combinations of meat, fat, tallow, stomach, etc are good examples. Butchery products spoil fast, so having frozen meat/fat/etc around is not a rare occurrence. Then, if you have several such ingredients frozen, all such frozen ingredients will show up as if you had zero of them when you look at a non-heated recipe.

So if you want to know what you can make from your frozen ingredients, it is currently necessary to memorize the entire contents of your freezer, and then _manually check every recipe_ (including disabled ones!) in case it is non-heating but could use a combination of frozen-but-defrostable ingredients.

# Describe the solution you'd like
Non-heated recipes with frozen components should be enabled if there is a sufficient source of heat available, just with a warning about using extra electricity/batteries/heatpacks/time for defrosting the frozen ingredients.

# Describe alternatives you've considered
Currently, some items, like Dehydrated Fruit, can be produced using either a heated or a non-heated recipe (with the heated recipe using more time and battery charges). The same could potentially be done for all non-heated recipes that use a component that might be frozen.

However, this would result in a massive bloat; not just in the backend, but the UI would also be cluttered with many duplicated recipes. The more elegant solution of allowing frozen ingredients in non-heated recipes (with an extra check for the availability of heat, and extra time/power cost for defrosting) on the other hand would *get rid of bloat*, with heated duplicate variants of existing recipes (like Dehydrated Fruit) becoming superfluous once the system can handle frozen and non-frozen ingredients intrinsically.

# Additional context
[The PR that disabled crafting with frozen components](https://github.com/CleverRaven/Cataclysm-DDA/pull/29699).

**Version:**
Custom-built from the latest git master via Arch AUR: cataclysm-dda-git 0.F.2021.08.01-1

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
