### ISSUE TITLE
[0.F stable] Batwing zombie description is extremely misleading

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#50383]
### Describe the bug

The batwing zombie is described as "... The mutation does not suit it well: it moves clumsily, even compared to other zombies." However, "It is much faster than you" in the speed description section tells a very different story.

### Steps To Reproduce

1. Find a batwing zombie. Look at the description when looking at it with 'x'.

### Expected behavior

Modify the description to e. g. "... The mutation does not suit it well: it moves clumsily, even compared to other zombies, but still manages to do so very rapidly."

My interpretation of the description plus the speed is that it is upon you very rapidly, but has a very hard time actually hitting you. However, I haven't been in melee combat with one.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Bug or suggestion? Given that it's easy to read just the description and miss the relative speed, I went for bug.

**Comment by Saicchi** [comment]
While it is as fast as regular zombies ( 70 speed ), the leap ability increases it speed rating, just by having it it's the equivalent of a monster with 120 speed.

**Comment by actual-nh** [comment]
"The mutation does not suit it well: It moves clumsily, even compared to other zombies, but can leap a significant distance"? It does have lower melee skill than a standard zombie.
