### ISSUE TITLE
In the Eating and food Crafting menus, Joy should display as Actual/MaximumPossible, e.g. 6/14

### ISSUE THREAD

**Issue by Svatopluk1** [CleverRaven/Cataclysm-DDA#50386]
# Is your feature request related to a problem? Please describe.
**Context**:
Eating more of the same non-junk food reduces the joy gained from eating more of it. This is a nice mechanic both in terms of gameplay balance and realism.

**Issue:**
When multiple different foods are available and rotting is not a concern (e.g. mid-game with fridges and freezers), the player can afford to try to eat a variety of food in a way that maximizes joy and hence focus gain. This depends on knowing whether the joy gained from a particular food is debuffed due to having recently eaten the same food, which is information that is not readily available.

# Describe the solution you'd like
After having eating one fish sandwich, and considering making/eating another fish sandwich:
- In the Crafting menu, its Enjoyability should display as 12/14
- In the Eat menu, its Joy should display as 12/14

This takes up very little extra space and provides important information when deciding which food to make/eat.

# Describe alternatives you've considered
When the Joy gained from the food item is debuffed due to having recently eating the same thing, this could be indicated using colors instead of numbers. This would trade information for space. However, the space gained from the trade would be very little (2-3 characters), and the information lost could be significant (e.g. 4/14 vs 12/14 would be collapsed). Also "Enjoyability: 12/14", after having eaten one would make more intuitive sense to a new player than a color change.

# Additional context
To observe the issue directly:
- Spawn 3 yogurts and 3 jam sandwiches.
- Eat 2 yogurts.

Now look at the Eat menu: eating a yogurt would provide 11 joy, while eating a jam sandwich would provide only 6. So if you are still hungry, you should eat another yogurt?

With the proposed solution, yogurt would show up as 11/15, and jam sandwich as 6 (or 6/6). So it would be clear that eating a jam sandwich now, and leaving the yogurt for later (when its enjoyability recovers to 15) would maximize joy gain from these items.

**Version:**
Custom-built from the latest git master via Arch AUR **cataclysm-dda-git 0.F.2021.08.01-1**

**Comment by PatrikLundell** [comment]
It seems to be implemented in the eat menu in 0.F stable (tried a corn bread with an enjoyment of 2, after eating it the enjoyment column for cornbread was blank). If it doesn't work in a current experimental, something has probably been broken.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
