### ISSUE TITLE
Recharging Station should not drain power when there is nothing to charge

### ISSUE THREAD

**Issue by Svatopluk1** [CleverRaven/Cataclysm-DDA#50388]
### Describe the bug

The Recharging Station drains batteries regardless of whether it has anything to charge or not.

It is a basic principle of physics that energy cannot simply disappear. If there is nothing for the Recharging Station to charge, where does the electrical energy it uses go? In reality, it would simply stop draining the car batteries when there is nothing to charge.

Note that "not using energy while not doing anything" is not a matter of "how clever the design is", but derives from a fundamental law of physics (which a mundane non-sci-fi battery charger should probably not violate).

### Steps To Reproduce

1. Spawn a Luxury RV
2. Spawn a Recharging Station, install it over the Floor Trunk
3. Make sure there is nothing in the Floor Trunk whose contents the Recharging Station would charge
4. Go to the driver's seat, examine the vehicle to check how the battery level changes (e.g. +200W)
5. Turn on the Recharging Station
6. Immediately check how the battery level changes (e.g. +190W)

Observe that the Recharging Station uses 10W despite not charging anything.

### Expected behavior

The Recharging Station should not use any battery charge while there is nothing to charge.

Ideally, it would drain power at a rate proportional to how much it actually charges batteries in its compartment, with power use dropping to zero when all chargeable batteries in its compartment are fully charged.

It would be reasonable to keep 10W as a cap (maximum power use, corresponding to maximum actual recharging rate).

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.F [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

Custom-built from the latest git master via Arch AUR ( **cataclysm-dda-git 0.F.2021.08.01-1** )

### Additional context

A related but less glaring issue: the Smart Engine Controller should be smart enough to be in a hibernation mode (reduced battery power use) when all engines are completely switched off.

**Comment by Qrox** [comment]
IIRC, the 10 watt that recharging station consumes is simply the standby power, while the batteries are charged with additional power.

**Comment by Menschheit** [comment]
But still, having a chance to charge every turn is weird. Doesn't real rechargers provide stable power?

**Comment by Svatopluk1** [comment]
Putting an uncharged medium battery into a Recharging Station inside a fully charged Luxury RV, and turning the Recharging Station on reduced the vehicle's batteries to 99%, so it seems to be true that batteries are charged with additional power.

Still, 10W is 1/3 the power consumption of a fridge. What is the Recharging Station doing with that amount of power while there is nothing to charge? Where does the energy go?

I expect standby power (perhaps a dim LED button to indicate that it is on) to be negligible, and certainly not within the same order of magnitude as the power consumption of a fridge or a freezer.

**Comment by Qrox** [comment]
> having a chance to charge every turn is weird

I think that's how the code handles fractional charging rate because battery level is stored as an integer.

> standby power

I tried to search the standby power of recharging stations, but they mostly have a higher power (tens of kilowatts) than the recharging station in-game (600 watts), and a standby power ranging from a few watts to a few hundred watts. So yeah, maybe you can make a 600-watt charger that has negligible standby power.

**Comment by PatrikLundell** [comment]
It's true (according to accepted laws of physics) that energy cannot be destroyed, so the answer to the question of where the standby power goes is that it's converted to heat. In fact, all the appliances that are "turned off", but in reality actually are on standby power, consume a rather considerable amount of energy globally.

**Comment by chrispikula** [comment]
Is there any way to make the recharge not 100% efficient at charging batteries?

The other option would be a normal recharger, and an advanced one.  That would match with real-world power supplies, that is, ones that use transistors or IGBT's to shave input voltage off the top into heat, vs a switching power supply that flickers on and off very fast to fill up a capacitance charge pool.  The former have garbage efficiency, but the latter have a restive drain on the capacitor somewhat proportional to the max current output.

**Comment by Qrox** [comment]
> Is there any way to make the recharger not 100% efficient at charging batteries?

`map.cpp:4588`:

```
// Around 85% efficient; a few of the discharges don't actually recharge
if( missing == 0 && !one_in( 7 ) ) {
```

It already has an efficiency of ~85%, and we can jsonize that value if we want different efficiency for different types of chargers.
