### ISSUE TITLE
Advanced Inventory keyboard shortcuts should have state-independent effects

### ISSUE THREAD

**Issue by Svatopluk1** [CleverRaven/Cataclysm-DDA#50392]
# Is your feature request related to a problem? Please describe.
**Context:**
Keyboard shortcuts are designed to save time by quickly producing a predictable effect. Having the effect of a keyboard shortcut depend on things that need to be thought about goes against the idea of a shortcut.

An extreme example to illustrate the principle:
What if CTRL+T opened a new tab in a web browser *if* the current location was near the top of the webpage, but CTRL+T closed the current tab if the current location was more towards the bottom of the webpage. Such cool context-sensitivity! Would this be a good idea?
Absolutely not: if I want to open a new tab, I want a shortcut that opens a new tab reliably and predictably. I don't want to have to spend even a second on having to check whether I am currently more towards the top or the bottom of a page, or having to deal with accidentally closing a tab instead of opening a new tab. That design would lead to completely unnecessary mistakes and frustration.

Predictable, reliable effects are key.

**The issue:**
In Advanced Inventory Management, if you press 8, it *sometimes* switches the current tab to display the what is located in the northern tile.
- Sometimes pressing 8 switches the current tab to display the eastern tile (if the current tab was already set to north, and the other tab was set to east).
- Sometimes pressing 8 switches the current tab to display your inventory! (if the current tab was already set to north, and the other tab was set to your inventory).
- Sometimes pressing 8 switches the current tab to display the contents of your dragged vehicle! (if the current tab was already set to north, and the other tab was set to your vehicle).

This is the same situation as the terrible context-sensitive CTRL+T example above. The same principle applies.

# Describe the solution you'd like
In Advanced Inventory Management, if you press 8, it sets the current tab to north. Always, predictably, reliably.

Why would this be an improvement over the current system?
You could, for example, enter the combo "4 TAB 6 TAB ," and it would *always* move everything from the western tile to the eastern tile. You would not have to double-check which tabs are currently set to which locations because the combo would *always reliably produce the same effect*. "A TAB D TAB ," would move everything into your dragged vehicle, then "D TAB 2 TAB ," would unload it to the southern tile, and so on.
Quick, predictable, with no chance for mistakes; a hallmark of good UI design.

# Describe alternatives you've considered
Currently, there is an option under the Interface submenu, where "open default advanced inventory layout" can be set to True. This results in a situation where you always start with the left tab set to All, and the right tab set to Inventory. One might think that this could be used to produce predictable effects, but this is not true either, because which tab is active after opening Inventory Management depends on which was active when you last closed it!

So even with "open default advanced inventory layout" set to true, if you try the combo "/ A TAB D TAB", it will *sometimes* set one tab to All and the other to your dragged vehicle (when you started with the right tab active), but it will *sometimes* set one tab to Inventory and the other to your dragged vehicle (when you started with the left tab active).

Making sure that with "open default advanced inventory layout" it is always the same tab that starts active (e.g. the left one) would be an improvement, although it would not be as good a system as the one proposed, i.e. using last opened layout but with predictable keyboard effects.

It is only with the proposed solution that you could do the following:
1. Grab a shopping cart to go looting with
2. Enter the combo "/ D TAB A" to set up the advanced inventory management tabs
3. Go somewhere with loot, simply enter the combo "/ ," to put everything around you into the cart
4. Move another few steps, simply enter "/ ," again to put more stuff around you into the cart
5. Go home, simply enter the combo "/ D TAB 6 TAB ," to unload everything from the cart to the east

# Additional context
I expect that a proposal to change a part of the UI will run into the status quo bias. I hope, however, that you will consider the general principle illustrated by the hypothetical CTRL+T example above, and will see how it applies to the Advanced Inventory Management system in terms of the desirability of predictable effects.

**Comment by andrei8l** [comment]
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/45900. Some devs don't want to change this behaviour (autoswap if the current pane is re-selected) because people are used to it, and apparently adding an option for it is just too much.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
