### ISSUE TITLE
autosave exits game

### ISSUE THREAD

**Issue by DavisBroda** [CleverRaven/Cataclysm-DDA#50399]
### Describe the bug

Intermittently autosave will exit the game mid-save, leaving behind a .temp file that makes the game think the character has been duplicated upon reload. 

### Steps To Reproduce

1. wait for autosave
2. game exits

unfortunately issue seems somewhat intermittent, so reproduction not guaranteed.

### Expected behavior

autosave should succeed, and not exit the game

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 37f9b6c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    DinoMod [DinoMod],
    No Fungal Monsters [No_Fungi]
]

### Additional context

unsure if logs are related, as had to restart game to get OS version info. But here they are
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6913189/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6913190/debug.log)

**Comment by DavisBroda** [comment]
Also finding it happens sometimes when I quicksave. 

Also crash log in earlier post appears to be old, so should be disregarded. whatever happened did not update crash.log

**Comment by DavisBroda** [comment]
[#VHJpeGllIFRhZQ==.sav.17192.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/6913267/VHJpeGllIFRhZQ.sav.17192.txt)

Here's the .sav.temp file generated by a failed quicksave (renamed to .txt so it can be uploaded). seems to be about half the size of the correct .sav file and ends abruptly with 

```
 { "typeid": "wristwatch", "bda
```

indicating that something went wrong in the middle of writing the file

**Comment by DavisBroda** [comment]
[DinoDale.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6913275/DinoDale.zip)

included the zip of the save file this happens to

**Comment by ifffrt** [comment]
This also happens to me as well. Have a save file where it always crashes when I try practicing dodging with a sewer rat. Would like for a fix so I can get my dodging up.

**Comment by ifffrt** [comment]
It wasn't just autosave. Quicksave does that as well. And I have narrowed down the culprit in my save: it was me dropping my hiking backpack (filthy) to the floor that's causing the issue. I've tried dropping the backpack to another square, unloading and reloading the backpack, repairing it up a bit so that maybe it won't be the same backpack anymore. Nothing works. It always crashes right after I press esc-8.

**Comment by PatrikLundell** [comment]
A pity. When did you save? I would try to move sufficiently far away from the rat massacre that it won't be inside the reality bubble when saving.
I don't think there would be a difference between autosave and quicksave technically, but disabling autosave allows you to select when to save, thus potentially delay that until out of a corruption causing situation.

**Comment by ifffrt** [comment]
That didn't work either. I tried playing for a bit longer and then dropping the backpack and it still crashed. I finally had to resort to open the save file in notepad++ and switched the position of the hiking backpack and my wielded wristwatch so that I wear the wristwatch and wielded the backpack instead. Now I have no issue.

**Comment by DavisBroda** [comment]
@ifffrt was there anything unusual about the save file that you could think of as the cause? If we could nail down what in the save file causes it, if would probably be useful for whoever attempts to fix this. Or at least let me edit my own save to keep things going if I can find something similar.

**Comment by DavisBroda** [comment]
OK, looked into things a bit more after noticing the comment by @ifffrt, and it seems like thing will fail if I try to quicksave after dropping my character's double rifle case onto the ground. Dropping other containers doesn't seem to be matter, just this one specifically.

**Comment by ifffrt** [comment]
Try editing your save file like I did. Maybe that would fix the problem. Just wield a clothing item (has to be something you can wear. Guns with shoulder straps work too), save it. Then find your double rifle case and the "weapon" field in your .sav file (there's hundreds of mentions of "weapon" in the file but the only one you need is on line 24) and then swap them with cut and paste. Worth a try.

**Comment by DavisBroda** [comment]
@ifffrt While the bug has been fixed in the recent PR, I tried your editing save file fix a few days ago, and it did prevent the crash, so thanks for that.
