### ISSUE TITLE
Problem with disassembly of items

### ISSUE THREAD

**Issue by ZeWoll** [CleverRaven/Cataclysm-DDA#50404]
### Describe the bug

When resuming the disassembly of an item, it finishes instantly, ignoring the remaining progress.

### Steps To Reproduce

1. Start the disassembly of any item
2. Stop the disassembly
3. Resume the disassembly and the item disassembles instantly

### Expected behavior

Items should logically take some time to disassemble.

### Screenshots

![image](https://user-images.githubusercontent.com/88143686/127788947-36658061-0a64-4d10-be76-219f03a92a51.png)
Television is disassembled in less than a second.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 2c152ac [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by Qrox** [comment]
Can confirm on 130a300007051579adf6b60b485f6e87e2513b63. Started disassembling a storage battery, interrupted immediately, and resuming the disassembly immediately finished it.

**Comment by Menschheit** [comment]
May be caused by #50100


![image](https://user-images.githubusercontent.com/28317565/127844170-f0c4132d-8772-4c4e-b026-17e1a815eb3d.png)
