### ISSUE TITLE
grow_up is broken

### ISSUE THREAD

**Issue by LyleSY** [CleverRaven/Cataclysm-DDA#50406]
### Describe the bug

Monsters with grow_up never do. Zombies still evolve as expected. Confirmed with baby chickens

### Steps To Reproduce

1. Spawn a chick somewhere you'll remember
2. Teleport far away
3. Debug a year to pass
4. Teleport back and there's still a chick there, no chicken.

### Expected behavior

Chicken

### Versions and configuration

- OS: Mac
- Game Version: 675499c368
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: None

### Additional context

Discovered trying to fix #47145

**Comment by Venera3** [comment]
I have no problem growing up wasps, dermatiks and chicks on version `g4cc11cc413` (Last PR #50322). I'll try to reproduce on the latest exp.

**Comment by LyleSY** [comment]
Huh, okay. I reproduced on the newest experimental, but then teleported to the next overmap, debugged another year passed, and then teleported back again and THEN chicken. I don't understand why it's different but at least it doesn't seem to be completely broken

**Comment by Venera3** [comment]
I think the "try upgrading/set upgrade timer" function onlx gets run on load, not on spawning from the debug menu.

**Comment by LyleSY** [comment]
Okay, sounds like it just works differently so needs different testing. Closing for now, thanks for helping me chase this down. Future people: if you want to test grow_up functionality, debug the test monster, debug yourself to the next overmap, debug time ahead, and then debug yourself back to the test monster. That appears to work
