### ISSUE TITLE
Wetsuit multiplying neoprene patches on dissassembly

### ISSUE THREAD

**Issue by Nabo92** [CleverRaven/Cataclysm-DDA#50415]
### Describe the bug

Crafting a wetsuit costs 12 neoprene patches, but cutting it up gives 63 patches back

### Steps To Reproduce

1. Spawn or get enough materials to craft a wetsuit (12 neoprene patches + other stuff)
2. Drop wetsuit
3. [B]utcher it (gives 63 neoprene patches back)

### Expected behavior

Expected that disassembling a wetsuit would give me back the 12 patches, not 63.

### Screenshots

![image](https://user-images.githubusercontent.com/37299923/127837005-51936adc-10b8-4d18-baeb-55a83c85fc7c.png)
![image](https://user-images.githubusercontent.com/37299923/127837059-d9222bea-2a86-4053-999b-0f02d303ea55.png)

### Versions and configuration

- OS: Windows 10 Pro
- Game Version: 28c62b9 (experimental)
- Graphics version: Tiles - Chibi_UtiCa
- Ingame language: English
- Mods loaded: basegame + disable npc needs

**Comment by Menschheit** [comment]
The outcome of cut mostly depends on item weight and material(more precise, the corresponding item defined in materials.json) weight, has nothing to do with recipe.

And there is another issue. Materiel items with the same weight will only be added once. So you never get any rag by cutting wetsuit.
