### ISSUE TITLE
Certain traps should be impossible to fail to disarm, or non-damaging even if you fail.

### ISSUE THREAD

**Issue by Aerin-of-the-Toast** [CleverRaven/Cataclysm-DDA#50411]
# Is your feature request related to a problem? Please describe.
Unless the survivor is meant to represent someone with an astounding lack of common sense, there is no real reason why someone who *has already spotted* and is *actively trying to disarm* certain traps should fail. And for some other traps, while failure is possible, there's no reason to stand within the line of fire when attempting to disarm. Obviously, this doesn't apply to something like landmines or other explosives or similar traps.

# Describe the solution you'd like
Ideally there'd be two new flags made for traps (do active traps even use flags?); one that makes it impossible to fail to disarm a trap (let's call this ALWAYS_DISARM) and one that changes the effect of the trap going off if you fail to disarm (perhaps call it FAILURE_SAFE). In most cases the effect would be it still goes off, it just doesn't damage the player.

Examples for traps that should be ALWAYS_DISARM:
All the benign traps or ones you disarm by just picking up (bubblewrap, glass shards, caltrops, nailboard). (I don't know if you actually can fail these or not, I'm just being thorough).
Tripwire (It's just a string at ankle-height, not attached to any mechanism)
Beartrap (Before it's set off I mean. Since "Disarming" it essentially involves just setting the trap off with something not attached to you, an alternative is to make it possible to trigger the trap by dropping an item on its tile. But there's really no reason for someone trying to disarm a bear trap to get their foot stuck in it)

Examples for FAILURE_SAFE traps:
Shotgun trap (The gun doesn't freely rotate, and its nonsensical to try to disarm it while staring down the gun's barrel. Ideally on a fail, the shotgun trap still goes off, it just doesn't hit the player at all.)
Crossbow trap (ditto)

This is not an exhaustive list, and its possible other traps could fall under one of those, like teleport pads, but I'm not exactly certain what those even are exactly.

# Describe alternatives you've considered
For the beartrap in particular, it could be FAILURE_SAFE instead since a failed disarm makes the loud "clank" sound of it activating while a disarm removes it silently.

**Comment by dseguin** [comment]
This is a longstanding issue and it makes sense to address it

**Comment by Night-Pryanik** [comment]
Most of traps mentioned here is addressed by #76638, the only one not touched by that PR is bear trap. I think it's not worth to keep this open.
