### ISSUE TITLE
Let players create custom alarms on mobile phones, and then drop them as a distraction.

### ISSUE THREAD

**Issue by ifffrt** [CleverRaven/Cataclysm-DDA#50414]
# Is your feature request related to a problem? Please describe.
We should give players more MacGyver types of stuff they can use to deal with the zombies. Like creating a 10 second alarm on your phone which you can then drop (or peek and throw, even better) and run away somewhere safe by the corner to lure the zombies away.

# Describe the solution you'd like
Make items with alarm features set their own alarms. Tie that alarm to that specific item so that the alarm can go off even if it's not on you anymore.

# Describe alternatives you've considered

# Additional context
Some items should have louder alarms than others. An alarm watch shouldn't be as loud as an alarm clock, for instance.

**Comment by robotic-gamer** [comment]
In theory smartphones can talk to each other peer to peer. with computer skill you could use this to turn smartphones to be remote activated by a separate smartphone.

**Comment by ifffrt** [comment]
in theory? you mean the functionality has already existed in the code?

**Comment by actual-nh** [comment]
If the character finds a locked iPhone (at least of the versions I've encountered), one can actually still set alarms, BTW. So this would also be a use for such (not sure if locked phones appear in game currently?).

**Comment by robotic-gamer** [comment]
@ifffrt I meant irl. also I think android phones come with timed alarms as well. you could also do this with alarms meant to wake you up in the morning by setting it to just after you drop the phone. so its safe to say smartphones in general can function as time delay noisemakers with the delay being anything you want.

**Comment by Vendidurt** [comment]
Currently the only way i have found to have this effect is to use a radio activation modded noise emitter. You can turn them off and on, even leapfrogging the zombies from one emitter to another. This has saved my life and gotten me past the lab bots in a finale before.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
