### ISSUE TITLE
Disassemble items on a workbench instead of wielding them all the time

### ISSUE THREAD

**Issue by Qrox** [CleverRaven/Cataclysm-DDA#50412]
### Describe the bug

You can put an in-progress craft on a table/workbench and craft without wielding it. However you can't do the same with an in-progress disassembly and have to wield it to disassemble. This is annoying when you try to disassemble a storage battery and be constantly knocked to the ground because supposedly you are holding the 200 kilogram battery pack in hand while cutting wires and removing solder.

### Steps To Reproduce

1. Get storage battery
2. Try disassemble it
3. Be knocked to the ground

### Expected behavior

You put the storage battery nicely on a nearby surface and work from there, unless you are a hulk, in which case you disassemble it in your hands like a normal human would an AA battery.

### Versions and configuration

130a300007051579adf6b60b485f6e87e2513b63

**Comment by Menschheit** [comment]
May be caused by #50100.

![image](https://user-images.githubusercontent.com/28317565/127843998-120edeb6-b31b-45d8-b3ba-4c8c67d80584.png)
