### ISSUE TITLE
Advanced inventory can't be used to move items from player inventory to ground.

### ISSUE THREAD

**Issue by Hirmuolio** [CleverRaven/Cataclysm-DDA#50430]
### Describe the bug

Advanced inventory can't be used to move items from player inventory to ground.

### Steps To Reproduce

1. Have item in inventory.
2. Open advanced inventory
3. Try to move the item to ground
4. Observe that nothing happens

### Expected behavior

The item should move to ground.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.C-63406-g7ff01aa03c [64-bit] (latest experimental)
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by Brambor** [comment]
Can confirm on the latest build.

**Comment by GoLoT** [comment]
It's possible that I introduced this in #50381.
I can't test it right now but https://github.com/CleverRaven/Cataclysm-DDA/pull/50381/files#diff-53bbc0e3a13a878bf2d4266e2ccfec49f658d3664ca4ef9d3f908a0fb0370b9dR1384-R1385 might need to be moved to the top of the else block. If anyone can test it out (I'll have a busy day tomorrow) it'd be helpful.

**Comment by Nabo92** [comment]
Yes, mine is broken too, can't use it inside vehicles as well, same build as OP

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/loading-bag-bicycle-basket-or-cars/26881/2

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/problem-with-advanced-inventory-0-f-1/26954/2
