### ISSUE TITLE
Encumbrance bug with axe ring holster

### ISSUE THREAD

**Issue by ZeWoll** [CleverRaven/Cataclysm-DDA#50440]
### Describe the bug

I'm not 100% sure what exactly happens but basically, the encumbrance of the axe ring holster stays the same even after taking the holstered axe.

I also had another issue but I have not been able to reproduce it yet, I refitted some leather gloves while having them equipped and the encumbrance stayed the same as if it hadn't been refitted.

### Steps To Reproduce

1. Equip axe ring holster without axe in inventory
2. Holster axe in the ring
3. Equip axe
4. Encumbrance of the ring stays the same as if it was still holding the axe

### Expected behavior

Encumbrance should not stay the same after wielding the axe.

### Screenshots

![image](https://user-images.githubusercontent.com/88143686/127921569-245c3f35-faa9-4c04-b4af-e61ccc9d608e.png)
![image](https://user-images.githubusercontent.com/88143686/127921573-621724af-5e60-49c5-a54b-e50a0bc7f45e.png)
Axe is equipped, ring is empty and yet the encumbrance stays the same.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 4edf6ad [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by GoLoT** [comment]
Related to #49978?

Apparently encumbrance is updated at the end of the turn so it displays incorrectly until taking any action. It fixes itself the next turn.

**Comment by ZeWoll** [comment]
> Related to #49978?
> 
> Apparently encumbrance is updated at the end of the turn so it displays incorrectly until taking any action. It fixes itself the next turn.

I see, I suppose we can close this issue then.
