### ISSUE TITLE
Make NPCs able to disassemble items for you

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#50469]
# Is your feature request related to a problem? Please describe.
Given how much junk a survivor can accumulate, and also how much longer it down takes to disassemble clothing after updating to 0.F, I think it's reasonable to add some way to assign NPCs to disassemble items in a given zone.

# Describe the solution you'd like
The above paragraph pretty much describes it.

# Describe alternatives you've considered
Accumulating many days of time spent in-game on disassembling items for their components while a significant portion of my growing nation of followers does absolutely nothing.

**Comment by wapcaplet** [comment]
This was resolved by #50517
