### ISSUE TITLE
Less fumbling with vehicles 

### ISSUE THREAD

**Issue by Cratelord** [CleverRaven/Cataclysm-DDA#50462]
# Is your feature request related to a problem? Please describe.
When turning a moving vehicle, the character has a high chance to fumble with the controls, causing them to turn randomly or not turn at all.  My current character is at vehicles 7, and while driving a pristine motorcycle at 20 MPH, I fumble at least a dozen times. Even as slow as 4 MPH I've fumbled up to 10 times. This seems wildly unrealistic, and it almost makes driving worse than simply walking. 

# Describe the solution you'd like
I think that fumbling should be greatly reduced, and outright stopped at a certain vehicles skill. 

# Describe alternatives you've considered
Bigger vehicles could be locked until you reach a certain level in the vehicles skill, as in real life larger vehicles require training beyond simple driver's education to attain licenses. The vehicles skill could also/instead play a bigger role in how much focus is drained when driving. 

# Additional context
EDIT: It seems that increasing the player's speed via magiclysm items such as a ring of speed cause the fumbling, and driving works as intended without them. This should probably be relabeled to a bug, since I don't think the increased speed is meant to cause fumbling.

**Comment by capSAR273** [comment]
In calculating whether you fumble with a vehicle while operating, the player's dexterity and perception are also taken into account. If these were very low, you could've seen more fumbles than what you would expect with a vehicle skill of 7.

Other variables taken into account are the surface you're driving on, how fast you are going, and if you are currently turning. Were any of these out of the norm when you experienced the fumbling?

**Comment by Cratelord** [comment]
Based on what you said, I should've had even less trouble. I have a perception of 12 and a dexterity of 17. Also, I very rarely go over 20. An hour or so after posting this, I had around 35 fumbles in a row when I was going 4 MPH. I can't think of any reason for my character to fumble.

**Comment by ZhilkinSerg** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/08378ceb55c34f79ece7d492fcad33fb67e94478/src/vehicle.cpp#L4459-L4472

https://github.com/CleverRaven/Cataclysm-DDA/blob/08378ceb55c34f79ece7d492fcad33fb67e94478/src/vehicle_move.cpp#L1353-L1447

**Comment by AmarinReyny** [comment]
I've noticed that every time my character's under the effects of the Haste spell from Magiclysm, she fumbles a lot more when driving. Maybe that has something to do with it?

**Comment by Cratelord** [comment]
That must be what's causing it, as I used both a ring of speed and a belt of haste from magiclysm. I'm not sure why that would cause fumbling though.

**Comment by AmarinReyny** [comment]
> That must be what's causing it, as I used both a ring of speed and a belt of haste from magiclysm. I'm not sure why that would cause fumbling though.

So, I could be completely wrong about this, and given my A. sleep deprivation, B. headache, and C. lack of any working knowledge of how to write C++ code, it's mostly likely that I am completely wrong about this... but, given how driving faster makes it harder to control the vehicle, maybe the script that determines whether or not you fumble with vehicle controls is somehow including the character's own speed in addition to the speed at which the vehicle is moving?

**Comment by actual-nh** [comment]
Could you change the title appropriately - something like "Player Speed boosts increase fumbling with vehicles"?

**Comment by actual-nh** [comment]
The problem appears to be here in pldrive:
```
        float skill = std::min( 10.0f, driver.get_skill_level( skill_driving ) +
                                ( driver.get_dex() + driver.get_per() ) / 10.0f );
        float penalty = rng_float( 0.0f, handling_diff ) - skill;
        int cost;
        if( penalty > 0.0f ) {
            // At 10 penalty (rather hard to get), we're taking 4 turns per turn
            cost = 100 * ( 1.0f + penalty / 2.5f );
        } else {
            // At 10 skill, with a perfect vehicle, we could turn up to 3 times per turn
            cost = std::max( driver.get_speed(), 100 ) * ( 1.0f - ( -penalty / 10.0f ) * 2 / 3 );
        }

        if( penalty > skill || cost > 400 ) {
            driver.add_msg_if_player( m_warning, _( "You fumble with the %s's controls." ), name );
            // Anything from a wasted attempt to 2 turns in the intended direction
            turn_delta *= rng( 0, 2 );
            // Also wastes next turn
            cost = std::max( cost, driver.moves + 100 );
        } else if( one_in( 10 ) ) {
            // Don't warn all the time or it gets spammy
            if( cost >= driver.get_speed() * 2 ) {
                driver.add_msg_if_player( m_warning, _( "It takes you a very long time to steer that vehicle!" ) );
            } else if( cost >= driver.get_speed() * 1.5f ) {
                driver.add_msg_if_player( m_warning, _( "It takes you a long time to steer that vehicle!" ) );
            }
        }
```
If the penalty is negative, then the cost goes up with the player's Speed - which can wind up putting cost over 400, causing fumbling.

**Comment by actual-nh** [comment]
Ping: @mlangsdorf?

**Comment by AmarinReyny** [comment]
> ~Ping: @mlangsdorf? Actually - ping: @eltank, I can actually do a PR for this if you (or others) can do testing (I am pretty unfamiliar with vehicles in-game!), or if you'd like to fix it next time you're working on code in that "area"?~
> 
> I'm doing a PR; currently compiling. I still would greatly appreciate other people to test the result.

I'd be willing to test it, once I'm back on my "gaming" laptop. Question, though... what would testing it involve? Would it be included in a new experimental version, or is there some other way I would get it?

**Comment by actual-nh** [comment]
> > I'm doing a PR; currently compiling. I still would greatly appreciate other people to test the result.
> 
> I'd be willing to test it, once I'm back on my "gaming" "laptop." Question, though... what would testing it involve? Would it be included in a new experimental version, or is there some other way I would get it?

Hrm. Compiling locally, or by someone with the same system as yours - what are you on?

**Comment by AmarinReyny** [comment]
> > > I'm doing a PR; currently compiling. I still would greatly appreciate other people to test the result.
> > 
> > 
> > I'd be willing to test it, once I'm back on my "gaming" "laptop." Question, though... what would testing it involve? Would it be included in a new experimental version, or is there some other way I would get it?
> 
> Hrm. Compiling locally, or by someone with the same system as yours - what are you on?

Windows 8.1 (pro, I think, I'm not sure - still not back at it yet).

**Comment by eltank** [comment]
Let me offer another piece of insight. The higher the driver's speed and driving skill, the more times they can steer in the same turn. However, each steering action becomes progressively more difficult as the delta between the vehicle's current direction and steering direction increases -- see the `aligned` multiplier in `vehicle::handling_difficulty()`.

To avoid this problem when hasted, use the pause action after steering 2-3 times if your turn didn't end (i.e. vehicle didn't move). Or use autodrive (#49455).

As always, uploading a save file helps a lot with debugging specific issues.

**Comment by actual-nh** [comment]
> Windows 8.1 (pro, I think, I'm not sure - still not back at it yet).

Unfortunately, I have a Mac.

**Comment by eltank** [comment]
I was unable to reproduce this. I created a character with 8/17/16/12 stats, level 7 vehicles, level 8 spellcraft, learned level 20 Haste and spawned a pristine motorcycle.
I drove the motorcycle while hasted (400 speed) off-road at 20mph for 2 minutes (the duration of haste), making various turns. I never saw a single message about fumbling.

**Comment by actual-nh** [comment]
I suspect this may have to do with that rings of speed were nerfed a bit back; before then, they were adding something like 1000 speed....

**Comment by AmarinReyny** [comment]
> I suspect this may have to do with that rings of speed were nerfed a bit back; before then, they were adding something like 1000 speed.... @Cratelord, @AmarinReyny, what was the total speed your characters were at with the rings, etc?

I typically use a combination of things, which I've been adding to over time. With the version of my character I had in the last 0.E stable, I usually got her speed into the 600s/700s range. Since updating to 0.F and using combined effects of multiple spells from Magiclysm, Arcana, and other mods, as well as a mod I made myself in order to create a sort of "toned-down" version of Haste, I can get her speed to over 1,000. Also of note is that, in both cases, I was also using the speedydex mod.

**Comment by eltank** [comment]
After adding speedydex and hacking the stats on some gear I was able to get a player speed of 631. I still could not get any fumbling with the motorcycle at 20mph or less. Fumbling starts at 25mph or higher.

With a player speed of 131, I was able to drive at 60mph without fumbling. And then crashed into a tree, because driving at that speed is very unsafe in CDDA.

**Comment by actual-nh** [comment]
Still, one should not be getting fumbling at 25 mph with higher speed but not at 60 mph with lower speed. Could you check #50539 for that? Thanks!

**Comment by AmarinReyny** [comment]
> After adding speedydex and hacking the stats on some gear I was able to get a player speed of 631. I still could not get any fumbling with the motorcycle at 20mph or less. Fumbling starts at 25mph or higher.
> 
> With a player speed of 131, I was able to drive at 60mph without fumbling. And then crashed into a tree, because driving at that speed is very unsafe in CDDA.

So, after seeing that you were trying it with a motorcycle, I decided to do a little more testing, since my character always drives bigger, bulkier vehicles (not fully-featured mobile bases, mind you, but still). I tried having my character drive the Mojocycle from Magiclysm, and she fumbled just from trying to turn it around at 4 mph. Her speed was 1086, due to the combined effects of multiple speed-boosting spells.

**Comment by eltank** [comment]
> Still, one should not be getting fumbling at 25 mph with higher speed but not at 60 mph with lower speed. Could you check #50539 for that? Thanks!

Agreed. In fact one should never fumble when `skill > handling_diff`. I made a suggestion on your PR.
In any case, #50539 will fix this issue for hasted players.
