### ISSUE TITLE
Species tamed achievement

### ISSUE THREAD

**Issue by LyleSY** [CleverRaven/Cataclysm-DDA#50475]
# Is your feature request related to a problem? Please describe.
Killing a species gives achievements, but not making them your loving servants

# Describe the solution you'd like
Statistics that counts how many of each species you make FRIENDLY and related achievements similar to the murdery ones

# Describe alternatives you've considered
Focus more on killing and less on making every monster my bosom companion

# Additional context
"You must always remember
Life can be a challenge
Life can seem impossible
It's never easy, when so much is on the line
But you can make a difference
With courage you can set things right
The gift to dream and make dream real,
Is yours and mine" - Donna Summer

**Comment by actual-nh** [comment]
The c++ things that are - as far as I can tell - definitely needed for this to happen:
- event.h: Add 'character_tames_monster' to event_type; also copy event_spec from 'character_kills_monster' to 'character_tames_monster'.
- event.cpp: Add 'character_tames_monster' to the enum_to_string function; change the static_assert to require 86 event types; add `DEFINE_EVENT_FIELDS( character_tames_monster )`.

@jbytheway, am I leaving anything out on the c++ things? After that would be JSON (scores.json and achievements.json; any others?).

**Comment by LyleSY** [comment]
statistics.json too, I was just fiddling with this for DinoMod

**Comment by jbytheway** [comment]
> @jbytheway, am I leaving anything out on the c++ things? After that would be JSON (scores.json and achievements.json; any others?).

The most important thing is sending the event to the event bus when a creature is tamed. And you also need to add this new type to the enum of types in `event.h`. I think that should be everything. The compiler errors will tell you about anything you miss.

**Comment by LyleSY** [comment]
Along similar lines, inspired by #56665 it would be fun to have achievements for taking pictures of different species too
