### ISSUE TITLE
Inventory volume is miscounted

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#50472]
### Describe the bug

See pic. In advanced and normal inventory, it says 15.81 / 50.00 L used, but much more is used.

### Steps To Reproduce

It happens all the time, so just spawn a character and load them with stuff?

If you cannot reproduce, I will investigate further

### Expected behavior

Right volume counted.

### Screenshots

![CDDA inventory wrong volume countedt](https://user-images.githubusercontent.com/13402666/128194335-e8b0f256-2d7e-47d2-9465-3db5dd11e7fe.png)

### Versions and configuration

- OS: Windows 10
- Game Version: 2021-08-04-0834
- Graphics version: Tiles

**Comment by Brambor** [comment]
> Canning pots are rigid containers, so their pocket volume isn't counted, since you can fill them up anyway when you put them inside your backpack.
> 
> Can't tell you why the jar doesn't fit without a save, though.

I guess the jar doesn't fit into the other jars. Well, it would be better to display the information in a different way. I don't think I'm the only one who is confused. I will try to think of something...

**Comment by mqrause** [comment]
There is definitely a lot to improve in that regard and it's also not possible to have a perfect display taking everything into account with just some numbers since some pockets have specific restrictions. I'm also not sure how AIM does this compared to the normal inventory and pickup/drop menues.

**Comment by chrispikula** [comment]
This also happens if you've got filters for your inventory, it only shows _displayed_ inventory.

Ideally it'd show the max volume of a space available, but given that AIM is talked about being merged into normal inventory, I don't know if it'll get updated.

Also, a canning pot is an 'open_container', so it might only hold things when carried?  
> If true, the contents of this pocket will spill if this item is placed into another item.

**Comment by PatrikLundell** [comment]
Yes, you have to wield a canning pot to put anything into it.

**Comment by Brambor** [comment]
In that case, isn't it a bug? Shouldn't the volume occupied (15.81 in picture) be >= volume of canning pot?

**Comment by mqrause** [comment]
> Also, a canning pot is an 'open_container', so it might only hold things when carried?

While that is true, it's not the point. When a rigid container is in a pocket, it will only occupy its total volume minus the volume of its pocket. Because it wouldn't make any sense to just leave it empty when you pack things like that. Technically all the items you put inside then go into the parent pocket, of course.

**Comment by chrispikula** [comment]
While that's reasonable in reality, in CDDA, I'm trying to think of the best method to load/unload that pot.  If you decided to remove that canning pot from your bag, and things were occupied inside it, you've got a few options.

Do they spill on the ground?  No, this is bad.  The most realistic, given that in game you are removing the pot from the bag as quickly as possible.

Do they go into the container on the ground?  Well yes, but it's not wielded, so no?

Do you remove each item, one at a time from inside the pot, inside the bag, leaving them inside the bag while you remove the pot?  Maybe, but this could end up with a very large remove/insert move cost.  If it's a bunch of small non-stacking things, it might take over ten minutes, given that move costs for some pockets start over 200.  If you are wielding something or have hand encumbrance this can unintentionally skyrocket.  I'd be kinda opposed, as I would sometimes end up losing a couple hours if I forgot to drop something.

Do you tell the player 'you can't remove that object while holding something' or 'there is no space to remove said item'?  This isn't intuitive, nor would the code look sane without a paragraph or two of comments, so... I dunno?

**Comment by mqrause** [comment]
This is moving away from the actual issue here (how available space is displayed) and probably belongs more in #40163.

**Comment by Brambor** [comment]
What about showing the range of volumes one can put in their inventory?

Ex: You have 40L of free space. You can fit items with volume ranging from 0L to 2.8L. Lengths from 0cm to 140 cm.

Maybe not in AIM but a sort of a popup (hotkey in AIM and elsewhere) for summarization so that you don't have to go through pockets to figure this out?

**Comment by Brambor** [comment]
Oh, and list of pockets with space! Yas, that's it, right?
