### ISSUE TITLE
Child zombies do not have fungalize_into specified

### ISSUE THREAD

**Issue by dgobi** [CleverRaven/Cataclysm-DDA#50485]
### Describe the bug

In https://github.com/CleverRaven/Cataclysm-DDA/pull/48479 it appears that there was an error, and `zombify_into` was used instead of `fungalize_into`, meaning child zombies can't currently fungalize.

### Steps To Reproduce

Look at json/monsters/zed_children.json

### Expected behavior

`fungalize_into` specified

### Screenshots

![image](https://user-images.githubusercontent.com/12568319/128246925-0996f723-6622-4edf-b90d-1b27eeecd3b5.png)

### Versions and configuration

Current experimental as of writing.

**Comment by Patil2099** [comment]
I would love to take this up

**Comment by actual-nh** [comment]
> I would love to take this up

Please see <https://github.com/CleverRaven/Cataclysm-DDA/wiki/Guide-to-adding-new-content-to-CDDA-for-first-time-contributors>, and thank you!

**Comment by khudson13** [comment]
I've just had a look and everything appears to be correct now. All the zombie children have their fungalize_into settings correctly set. I think this issue can be closed.
