### ISSUE TITLE
collectible marking

### ISSUE THREAD

**Issue by vipches** [CleverRaven/Cataclysm-DDA#50496]
Can we make a system that can marking some items on game such as ammunitions?

I have hard time to finding the ammo because I dosn't take a gun with me, becausea ammunitions only change color as green or red when you have the same type magazines or guns on you bag,

If we can makeing a stystem to marking those item, we can save a lot of time in order to finding them, I have noticed there was a styestem called "favorite" in order to marking the item that you like, I try it on the ammunitions, and it dosn't work well, mabye on the few new versions of the game?

**Comment by Hirmuolio** [comment]
You can use autopickup to automatically poick up any item when you pass over them.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
