### ISSUE TITLE
Multiplying condoms

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#50498]
### Describe the bug

I move stuff around in my base when I notice my condoms have multiplied again. I started with one condom, discovering what a fabulous item it is, I marked it favourite right away. Then, as time went on, I had two, then 3 or 4, now 4 multiplied into 6.

### Steps To Reproduce

I still don't know, I have marked condom item as favourite and they _seem to_ multiply sometimes when I am moving items (not the condoms though.)

More investigation needed, maybe somebody had similar <strike>issue</strike> blessing?

### Expected behavior

Condoms shouldn't multiply.

### Versions and configuration

- OS: Windows 10
- Game Version: from the main menu: c850e91; 2021-08-05-1036; I have had this issue for some time (2 weeks?) and update regularly
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: basic

**Comment by BHasselaar** [comment]
Check if there are any items in your character/global auto-pickup options, please.

**Comment by Brambor** [comment]
> Check if there are any items in your character/global auto-pickup options, please.

There are two: `*arrow` and (turned off most of the time) `wood ash`, both global.
However, I am 100% positive (true 100%) that I haven't picked up condoms accidentally. I pay quite a bit of attention to what am I picking up.

**Comment by PatrikLundell** [comment]
I'm not sure, but I have a feeling I've found a condom in a wallet, in which case you don't see it as you pick up the wallet itself, but only when you go through its contents.

**Comment by Brambor** [comment]
> I'm not sure, but I have a feeling I've found a condom in a wallet, in which case you don't see it as you pick up the wallet itself, but only when you go through its contents.

Yes, that could be it. If wallets contain condoms, that's my source of them...

**Comment by hexagonrecursion** [comment]
Verified: zombies do sometimes drop wallets with condoms in them

**Comment by actual-nh** [comment]
Closing issue, then.
