### ISSUE TITLE
Recolor the blackjack oak tree.

### ISSUE THREAD

**Issue by vipches** [CleverRaven/Cataclysm-DDA#50495]
I'm living in wild on this game for a while, and I have a little problem about this tree, 

I been wounder if other tree has the same problem, because this blackjack oak has different color, it's brown color as the same as harvested tree, it make little diffuculty to differentiate between harvested one and this one, and when it's harvested, it will became green color instead of brown,

so can we change it color just like other trees do? how about we make all harvested tree share the same brown color instead of something else? please?

I already change blackjack oak to brown into yellow, and change the harvested one into brown, I hope we don't have to change it again.

**Comment by int-ua** [comment]
What tileset are you using if any?

**Comment by vipches** [comment]
> What tileset are you using if any?

No titesets, I'm acsii player.

**Comment by int-ua** [comment]
Please make a PR with your changes, the easiest way is to edit the file directly at GitHub, it will guide you through making a new PR: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/furniture_and_terrain/terrain-flora.json

The edit button is in the bottom right part on this screenshot 
![screenshot](https://user-images.githubusercontent.com/1585431/128465700-89e366c4-106f-4c6c-9385-8283e4d69e8d.png)

**Comment by vipches** [comment]
> Please make a PR with your changes, the easiest way is to edit the file directly on GitHub, it will guide you through making a new PR: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/furniture_and_terrain/terrain-flora.json
> 
> The edit button is in the bottom right part on this screenshot
> ![screenshot](https://user-images.githubusercontent.com/1585431/128465700-89e366c4-106f-4c6c-9385-8283e4d69e8d.png)

I have complete the edit for this PR, waiting for permission.

**Comment by int-ua** [comment]
What permission?

**Comment by vipches** [comment]
> What permission?

Eh... I mean please accept the edit I have create please.

**Comment by int-ua** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pulls/vipches

Looks like you didn't create a PR, use this link

https://github.com/CleverRaven/Cataclysm-DDA/compare/master...vipches:patch-1?expand=1

**Comment by TealcOneill** [comment]
PR #50646 fixed this issue.
