### ISSUE TITLE
Zombie sight range is underestimated during dusk

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#50497]
### Describe the bug

For every enemy I can see the game tells me whether or not it can see my current location. The issue is: sometimes the game tells be that the enemy can not see me even though it can.

### Steps To Reproduce

1. Set time to year 0, season 0, day 61, hour 20
2. Mutate debug deodorizer, debug silent walk and debug clairvoyance super
3. Spawn a fat zombie
4. The game reports that the fat zombie can see me from 5 tiles away but can not see me from 6 tiles away
5. Kill the fat zombie
6. Spawn a fat zombie 39 tiles to the south
7. Move one tile east and one tile  west (i.e. perpendicular to the direction to the zombie) a couple of times. This is necessary. I don't understand why, but if I stand still the zombie does not see me.
8. Observe the zombie purposefully walking toward you

### Expected behavior

Either the zombie should not be able to know where I am or the sight range prediction should correctly telly me that the zombie can see me.

### Screenshots

none

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 013c199 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by connorpmartin** [comment]
have you tried checking scent w/ debug?

**Comment by Saicchi** [comment]
#43479 related?

**Comment by hexagonrecursion** [comment]
@ConnorMartin See 2) I have disabled scent via debug deodorizer.

**Comment by actual-nh** [comment]
Specifically dusk? Monsters have vision_day and vision_night; this might be due to different parts of the game using different intermediate values for vision ranges.

**Comment by hexagonrecursion** [comment]
@actual-nh yes dusk. I tried dawn too, but so far was unable to produce the same effect.

**Comment by actual-nh** [comment]
And at step 8, the game is reporting that the fat zombie can't see you?

**Comment by hexagonrecursion** [comment]
yes

**Comment by actual-nh** [comment]
Another finding - #51185.
