### ISSUE TITLE
[0.F stable] Vehicle generated on same tile as tree

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#50505]
### Describe the bug

I found a camp ground with a nice car, when returning to repair it, I realized a tree was growing on one of the car's tiles...

### Steps To Reproduce

1. Keep generating worlds and check the camping grounds in them?

### Expected behavior

Whichever is generated first of the tree and the vehicle should block the other from being generated: The Cataclysm was a month ago, not 30 years!

### Screenshots

![Screenshot (7)](https://user-images.githubusercontent.com/22739822/128408242-96eec135-4717-45e0-985b-00a4eed89943.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

I've found cars generated on top of lamp posts, but in those cases the lamp posts have been smashed into pieces under the vehicles.

**Comment by int-ua** [comment]
I've seen a vehicle generated over a deployed tourist table at camping grounds. It was not broken.

**Comment by PatrikLundell** [comment]
Just found the same thing as int-ua did:
![Screenshot (8)](https://user-images.githubusercontent.com/22739822/128418599-348da698-cc5b-489e-b600-5176daf3ffc8.png)

**Comment by actual-nh** [comment]
Ping: @Fris0uman, @mlangsdorf?

**Comment by BrettDong** [comment]
![image](https://user-images.githubusercontent.com/21075502/128434724-fa847f6f-b21e-498e-9269-2897711dbb31.jpeg)

**Comment by PatrikLundell** [comment]
Looking at the code that places vehicles (map::add_vehicle_to_map) shows that it should "collide" with any impassable object on the any vehicle tile and smash the object. I've debug spawned vehicles on top of trees and boulders, and in all of my attempts the trees and boulders were smashed, while the vehicles were damaged (they were specified to spawn undamaged, so the damage should be from the "collisions").
It can be noted, however, that young trees, shrubs, and small boulders are not impassable and are not affected by this code, so spawning a vehicle on top of a young tree results in a collision when driving the vehicle away, while a small boulder isn't a problem unless it collides with the wheels. Fortunately, shrubs are no longer made out of reinforced concrete, so vehicles can now drive through them with limited damage, even if spawned on top of them.

So, what causes the tree/vehicle spawning if the code checks for it? My guess is that there may be situations where the tree somehow is spawned after the vehicle has been spawned. I tried debug spawning a vehicle and then edit the terrain under of one of its tiles to become a pine tree, which essentially replicated the situation in this PR. Obviously, using debug functions doesn't say that much about real functionality, as debug functions may well bypass normal checks in order to allow the generation of "impossible" situations.
I don't know if the order in which sections of JSON "items" are defined matters, but if it does, it looks like moving the "rows" section of the first "object" in data/json/mapgen/campground.json to the top would cause vehicles to crash down on top of the map rather than the map spawning below vehicles (and furniture, items, etc.) suspended in limbo. However, I don't know how to test this (change the definition to ensure a collision by e.g. remove the alternatives to trees in the palette, somehow ensure a camping ground is spawned, teleport there (I assume that's reasonably easy), verify lots of trees as spawned in vehicles, kill CDDA, change the JSON order, redo the steps above, verify the vehicles in the camping ground are now probably smashed to pieced by the trees they've landed on, restore the palette (and that would be it, as I don't think it's worthwhile to keep generating the situation until a vehicle tree collision happens, as they seem to be fairly rare)).

**Comment by PatrikLundell** [comment]
I've managed to debug the generation of "campground_2a_west" by using the debug menu to spawn it, and have hacked the map to generate "t_region_tree" instead of ground cover and a chance of trees (to increase the chance of vehicles and trees spawning in the same location).

Debugging shows that the vehicle is indeed checked against the impassability of "t_region_tree", but consider it to be passable because it has a movement cost of 1, and thus is passable. This means the vehicle is placed on top of unresolved terrain where pseudo terrain has not yet been resolved into "actual" terrain. It would probably be possible to resolve the situation for "t_region_tree" by setting it to be impassable, but that isn't a proper solution as pseudo terrain might resolve into both passable and impassable tiles (young trees mixed with mature ones, for instance, and I think the ground covers may have tree in them as well).
A proper solution would probably require that the terrain is resolved into actual terrain before things are placed on top of it.
