### ISSUE TITLE
Making summon allies as guards

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#50506]
Right now summon an animal using spell spawn them as "friendy", which is fine, when they are spawned inside the crowd, but its absolutely useless when there is no enemies - they just walk around the territory and do nothing to protect the caster

What about adding new flag to spell, that spawn creature with same AI as dog? it will make summoning creatures before the fight more reliable than now

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
