### ISSUE TITLE
Feature Idea: Cross Contamination

### ISSUE THREAD

**Issue by Theawesomeboophis** [CleverRaven/Cataclysm-DDA#50510]
I don't know if this is already in the game, but IRL, storing rotten food next to fresh food contaminates it, which would make food preservation more of a necessity than it is currently, as well as make farming builds (slightly) more useful.

**Comment by actual-nh** [comment]
It doesn't contaminate it (unless it's attracting/hatching flies or something), but it can accelerate ripening of fruits/vegetables (including causing them to go overripe).

**Comment by Theawesomeboophis** [comment]
Also with things like meat, doesn't salmonella begin to form ( or whatever correct terminology is)?

**Comment by Theawesomeboophis** [comment]
https://resources.centralrestaurant.com/cross-contamination-food-safety-101/
This is what I'm referring to.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
