### ISSUE TITLE
Nudist Conduct Works Strange In Current Implementation

### ISSUE THREAD

**Issue by Theawesomeboophis** [CleverRaven/Cataclysm-DDA#50527]
The way the nudist conduct works in current implementation is strange to me. What I mean is that currently, starting on a profession with clothes does not disqualify you for nudist conduct, but if you put for example kneepads on on top of your starting gear you lose the conduct. The ideal scenario would be that you lose it upon loading when starting with clothes, as you can't really be a nudist while wearing full metal armor.

**Comment by SariusSkelrets** [comment]
I think you doesn’t lose it at start so you can start as anything else than naked and afraid

Following conducts is up to the player. If they want to be nudists, they’ll simply remove their clothes right after spawning. 

Removing the conduct at spawn would force players attempting it to start in the naked and afraid camp, preventing them from starting their game anywhere else

**Comment by Theawesomeboophis** [comment]
That makes sense, thanks for explaining the reasoning.
