### ISSUE TITLE
Player move cost higher than intended

### ISSUE THREAD

**Issue by GadekMaciej** [CleverRaven/Cataclysm-DDA#50524]
### Describe the bug

build 2021-08-05-1036 works perfectly fine for me, but in build 2021-08-06-0631 player move cost is higher than it used to be, that is probably unintended. This can be due to #47561. I haven't checked it myself but that is my first thought.

### Steps To Reproduce

1. get both builds (from description).
2. start new game
3. press '@' to check character sheet

### Expected behavior

move cost remains the same as always, around 115 points

### Screenshots

Before: (build 2021-08-05-1036)
![image](https://user-images.githubusercontent.com/64140639/128514066-7be5d4f6-2400-4cba-b23d-7e580c463999.png)
now: (build 2021-08-06-0631)
![image](https://user-images.githubusercontent.com/64140639/128514501-e620eee5-2457-4109-aed6-558549f40ca5.png)

### Versions and configuration

- OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
- Game Version: [from the main menu, e.g. 0.C-29938-g90f5268437]
- Graphics version: [Tiles or Terminal]
- Ingame language: [Arabic or Bulgarian or Chinese (Simplified) or Chinese (Traditional) or Dutch or Esperanto or French or German or Italian (Italy) or Japanese or Korean or Polish or Portuguese (Brazil) or Russian or Serbian or Spanish (Argentina) or Spanish (Spain) or Turkish]
- Mods loaded: [e.g.dda, boats, hacktheplanet, StatsThroughSkills]

**Comment by actual-nh** [comment]
Ping: @KorGgenT?

**Comment by KorGgenT** [comment]
i'll look into this ASAP.
