### ISSUE TITLE
regression: player movement costs went up dramatically

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#50526]
### Describe the bug

The player used to be slightly faster then most zombies by default: 100 speed (not counting pain etc.), 100 base move cost (not counting encumbrance etc.). Now the player is slower then the zombies: 100 speed, 167 base move cost. The regression was introduced in the 2021-08-06-0539 release https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2021-08-06-0539

### Steps To Reproduce

1. Create a new world with default settings
2. Create a character:
    * Evacuee
    * Survivor
    * no hobbies/traits/skills
    * stats: 8/8/8/8
3. Walk a space
4. See that the move cost is 167

### Expected behavior

The move cost should be 102 (100 + 2 for encumbrance)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 6a49389 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

The following version is unaffected:
- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: c850e91 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by anothersimulacrum** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/issues/50524

**Comment by KorGgenT** [comment]
closing this one as a duplicate. i'll look into the issue, and we'll use the other to track it
