### ISSUE TITLE
Fishing spears can only be stored inside golf bags

### ISSUE THREAD

**Issue by ZeWoll** [CleverRaven/Cataclysm-DDA#50523]
### Describe the bug

Fishing spears can only be stored in golf bags. I thought the spear strap could hold fishing spears too.
Since golf bags don't seem craftable, and there seem to be no alternatives, is this a mistake or intentional?

### Steps To Reproduce

1. Try to store fishing spears
2. They can only be stored inside golf bags

### Expected behavior

It would make sense to have some alternative to carry fishing spears.

### Screenshots

![image](https://user-images.githubusercontent.com/88143686/128510885-39af1061-a860-4534-b8b9-8381e7f2a86c.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 1a5362d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by satheon49** [comment]
I can confirm this. Fishing spears are missing the SHEATH_SPEAR flag. Since even fishing rods have this flag this is probably a bug.
