### ISSUE TITLE
"PET_WONT_FOLLOW" is bugged

### ISSUE THREAD

**Issue by LyleSY** [CleverRaven/Cataclysm-DDA#50532]
### Describe the bug

Monsters with PET_WONT_FOLLOW flag follow exactly like they don't

### Steps To Reproduce

1. spawn a cow
2. spawn cattlefodder, activate it and give it to the cow
3. move and watch it follow you

### Expected behavior

cow does not follow

### Screenshots

happy cow
<img width="993" alt="Screen Shot 2021-08-06 at 2 12 53 PM" src="https://user-images.githubusercontent.com/26608431/128554463-c0c4ae33-6d77-465d-b61b-a65d0f747056.png">

cow follows
<img width="1269" alt="Screen Shot 2021-08-06 at 2 13 29 PM" src="https://user-images.githubusercontent.com/26608431/128554506-5488172d-2db4-4606-b631-9e613c8fba35.png">

### Versions and configuration

- OS: Mac
- Game Version: ab9621dd20
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: None

### Additional context

Thanks to @actual-nh for letting me know I'm not crazy. Refreshing!

**Comment by actual-nh** [comment]
The only place that PET_WONT_FOLLOW is checked is in monmove.cpp in monster::plan():
```
    // If we can see the player, move toward them or flee, simpleminded animals are too dumb to follow the player.
    if( friendly == 0 && seen_levels.test( player_character.pos().z + OVERMAP_DEPTH ) &&
        sees( player_character ) && !has_flag( MF_PET_WONT_FOLLOW ) ) {
```
Note that, in this instance, the check for `friendly == 0` will exclude actual pets...

**Comment by PatrikLundell** [comment]
Cows, horses, and sheep sometimes follow and sometimes won't, in my experience (both 0.E2 stable and 0.F stable). They seem to sometimes hit some kind of invisible lines they won't cross, for whatever reason.

**Comment by anothersimulacrum** [comment]
Probably when they see other monsters.

**Comment by PatrikLundell** [comment]
No, unless those monsters are non hostile ones (such as squirrels, although I've gotten a safe mode warning about a squirrel once...). I know they won't follow when predators or hostile creatures are seen.

**Comment by anothersimulacrum** [comment]
They won't follow when non-tamed cows are seen - go to a dairy farm, and you'll see none of the cows follow you until all the cows are tame.

**Comment by actual-nh** [comment]
That correlates. Since they can't target the player directly while friendly, if there's something else, they'll target that instead.

**Comment by eltank** [comment]
I have a simple fix for this, which is moving the PET_WONT_FOLLOW check in `monmove.cpp` to the correct place (L636 at the time of writing). But fixing that would make it impossible to move cows around (which should definitely be possible) except via an extremely tedious sequence of swap-place operations.

So the plan is to fix this while adding a new feature to the game: leashing animals. Examine a friendly animal with a short rope in inventory, select option to leash (animal gains effect "leashed"), replacing the option to tie down. Examine a friendly leashed animal and you can:
- tie them down (as before)
- unleash
- lead
The last option gives them a new effect ("led" or "led_by_leash") which makes them follow the player regardless of PET_WONT_FOLLOW and even if they can't see you. If you go too far they lose the effect. Or you can interact with them again to stop leading them. You can leave the leash on when done or if you're short on ropes you can unleash them.
I'll work on this, but it'll take some time.

**Comment by PatrikLundell** [comment]
I really like eltank's approach.

I assume "go too far" means too far away from the animal, such as when running or passing over obstacles the animal can't navigate, as opposed to traveling further than some arbitrary distance.
It can be noted that this would make ponies useful, as you'd be able to use them as (rather weak) pack mules, since you can't ride them unless basically naked (or being rather small).

I don't really think it's needed, but just in case I'll point out that the functionality needs to be tested up and down stairs (regardless of whether if the animals are supposed to follow or fail to navigate stairs), including the unaligned weirdo ones in e.g. subway stations, and ramps, as well as when the leading character climbs obstacles the animals can't pass over/on top of.
