### ISSUE TITLE
Game doesn't open at all on OSX Catalina, previous fix did not fix issue.

### ISSUE THREAD

**Issue by Essnato** [CleverRaven/Cataclysm-DDA#50542]
### Describe the bug

The game does not open on OSX, it closes instantly after attempting to open, no error message is given, tested on latest experimental and latest stable (0.F).

### Steps To Reproduce

Open the game on a system running OSX Catalina, 2 different versions were used to see if updating the OS would fix the issue, it made no difference.

### Expected behavior

The game is supposed to open?

### Versions and configuration

- OS: OSX Catalina
- Game Version: [O.F stable and Cataclysm-DDA experimental build 2021-08-06-0539]
- Graphics version: Tiles
- Ingame language: N/A
- Mods loaded: N/A, game did not open to the point where activating or deactivating mods was an option

### Additional context

This problem did not happen a few months ago, which was the last time I tried to play this game.

**Comment by ZhilkinSerg** [comment]
Did you try compiling the game yourself with Homebrew?

**Comment by Essnato** [comment]
I did but it didnt work due to ISP related issues, i tried for a long time.

**Comment by BrettDong** [comment]
Please check if https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2021-08-08-0155 works.

**Comment by Essnato** [comment]
it worked, however my game opened without any text visible at all, a
workaround was just to change some config files and it works 'for now'
