### ISSUE TITLE
drop mac builds support until devs can learn to do framework bundling  because devs refuse to do frameworks bindles and its brkeing all mac builds in F.0 bescue not meeting mac basic requirements for a working build bescue missing frameworks not bundled with program on builds is a issue that breaks mac programes

### ISSUE THREAD

**Issue by ashtiboy** [CleverRaven/Cataclysm-DDA#50541]
# okay devs it seems that if you keep refuseing to bundle your needed frameworks on your mac builds! then theres no other option anymore then to drop mac support  completely until your can get your mac frameworks file S*** put back to together! i'm sick of reporting the same issue of the same exact error that is the core issue causing  the mac builds to not work! but i can't just keep reporting the same thing over and over and over to get ONE gosh dang fix to get the game to run!  you devs just won't bundle the frameworks WITCH YOU NEED TO DO FOR IT TO WORK AT F**** AT ALL! if you can't do a bsic core mac program app requirement then stop making mac builds until you know what frameworks you need to have it run on a mac that's not like made before 2009! until you bundle the needed frameworks with the game data files on the mac build then you can't make mac programs PERIOD!

**Comment by actual-nh** [comment]
@ashtiboy: The more you rant, the more discouraged I get from checking into the problem.
