### ISSUE TITLE
Rotten food should make container (filthy)

### ISSUE THREAD

**Issue by Vendidurt** [CleverRaven/Cataclysm-DDA#50552]
# Is your feature request related to a problem? Please describe.
No, it is no problem, but after milk rots to oblivion my character has no compunction against storing clean water, etc. and consuming it straight from the jug.

# Describe the solution you'd like
A cleaning task required to use the jug for foodsafe purposes, and if it is not respected, roll chance to vomit, add nausea, lower morale, etc.
The (filthy) label refers to zombie-infested clothing and has no connection that I am aware of to the food system. Some other label would be easier to differentiate, but also let the player know that they should do something first before eating out of it.

# Describe alternatives you've considered
Ignoring this whole idea since clean containers probably wouldnt be any less accessible afterward, and bleach bottles would still be relatively safe to just rinse anyway.

# Additional context
I had a picture of a jug of bad milk but that probably is unnecessary.

Edit: small grammar fixes

**Comment by ERRORCODE509** [comment]
Jokes on you, I store my food in a pile on the floor.

**Comment by Vendidurt** [comment]
But not your water or precious, precious jam.

**Comment by ERRORCODE509** [comment]
You got me, I store those in a bathtub.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
