### ISSUE TITLE
Unrealistic effects duration

### ISSUE THREAD

**Issue by Menschheit** [CleverRaven/Cataclysm-DDA#50554]
### Describe the bug

The duration stacks additively and can be extremely long like this:
![image](https://user-images.githubusercontent.com/28317565/128600976-b6472e27-bf4a-49f2-bb33-313c6fe1796e.png)
My save shows the left duration is 1696410 ( turns I assume).
It is because the opiate withdrawal keeps adding new shakes effect and the duration gets longer and longer which is very unrealistic

### Steps To Reproduce

Start as a heroin addict and enjoy the weeks long shakes even after the withdrawal wears off.

### Expected behavior

Many of the effects in game like shakes should not even stack. They get refreshed if the new effect is longer than the existing one.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: fc6d52f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by Saicchi** [comment]
It seems the shakes effect is not capped. I suggest capping it to 60 minutes with subsequent applications while the player already has the effect being only 30% effective.
```json
{
    "type": "effect_type",
    "id": "shakes",
    "name": [ "Shakes" ],
    "desc": [ "Your hands just won't stop shaking." ],
    "miss_messages": [ [ "You tremble", 4 ] ],
    "base_mods": { "str_mod": [ -1 ], "dex_mod": [ -4 ] },
    "max_duration": 3600,
    "dur_add_perc": 30
 }
  ```

**Comment by anothersimulacrum** [comment]
The duration was capped in  - #51250
