### ISSUE TITLE
Birds have difficulty chasing player up bridge ramps

### ISSUE THREAD

**Issue by Vendidurt** [CleverRaven/Cataclysm-DDA#50553]
### Describe the bug

I irritated some geese the other day by walking down a bridge ramp and stepping too close to them, and they gave chase. I walked back up the ramp and the geese flew up to match me, getting magically stopped by the open-air side of the ramp. Coincidentally, while I was investigating this, a zombie came up the ramp with no difficulty and I was surprised to find the **Hostile** geese and the zombie ignored one another.

### Steps To Reproduce

1. Get some geese near a bridge ramp.
2. Fire nailgun at geese.
3. Escape up the ramp.
4. Stare in confusion.

### Expected behavior

1. That birds are not defeated by ramps.
2. That murder birds also look at zombies with the same contempt they show me.

### Screenshots

![IMG_20210803_185533](https://user-images.githubusercontent.com/86169163/128599795-5193cec6-6a5a-420e-941f-1594da8f9c5a.jpg)

### Versions and configuration

- OS: [Windows 10]
- Game Version: [9a81a10]
- Graphics version: [Tiles or Terminal]
- Ingame language: English, US
- Mods loaded: Sees-player icon, Retrodays
Note: my version is prior to .F

**Comment by actual-nh** [comment]
Did you have the "experimental 3d vision" (or whatever it's called) option enabled? (Geese and zombies not attacking one another is a consequence of the current somewhat-crude monster faction implementation. Ideally, the geese if angry enough might attack the zombies, and then vice-versa, but currently that isn't really possible - either the zombies would be attacking geese all the time, or zombies would never attack the geese even if attacked.)

**Comment by Vendidurt** [comment]
> Did you have the "experimental 3d vision" (or whatever it's called) option enabled? ....

3d FOV is False.
 I think the ramp tile that puts the creature/car down a Z-level is trying to shove the geese into the z-level below, which is impossible, so it does not let the birds proceed forward. Maybe since they are not currently standing on the "highest" part of the ramp which is probably necessary for the "second highest" part to function.

I appreciate how zombies wont chase smaller creatures, as it made it way too easy to undermine their behavior that way.

**Comment by actual-nh** [comment]
> > Did you have the "experimental 3d vision" (or whatever it's called) option enabled? ....
> 
> 3d FOV is False.

That may be part of the problem.

> I appreciate how zombies wont chase smaller creatures, as it made it way too easy to undermine their behavior that way.

Good! The in-game logic is that smaller creatures won't become zombies after dying, so why would zombies bother attacking them?

**Comment by Vendidurt** [comment]
I will check again with 3d FOV a bit later today.

It would be fun to see Zihuahuas trying to murder me.

**Comment by Vendidurt** [comment]
Tested again with 3d FOV and that option is irrelevant. In testing one goose ran up the ramp and 2 others flew up as soon as i changed Z level, the one who walked has no problem biting me but the others are stranded, helpless.
![IMG_20210807_170420](https://user-images.githubusercontent.com/86169163/128616657-90d1e9a3-addf-4532-ab37-9b9be8e23eb3.jpg)

**Comment by actual-nh** [comment]
@Venera3, you've previously mentioned Z-level pathing problems?
