### ISSUE TITLE
Bridge spawn incomplete into another bridge

### ISSUE THREAD

**Issue by BriscoLargg** [CleverRaven/Cataclysm-DDA#50569]
### Describe the bug

Please see attached images
![image](https://user-images.githubusercontent.com/55927101/128608486-4a603ef9-bba8-4ce2-a46e-f1f50af11463.png)
![image](https://user-images.githubusercontent.com/55927101/128608564-daac3637-1b84-4372-8fd2-a941f095d6cc.png)

### Steps To Reproduce

Save: 
[Wickenburg.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6949479/Wickenburg.zip)

### Expected behavior

Bridges should not be incomplete and perpendicular to each other on the same Z-level

### Versions and configuration

- OS: Windows 11 dev channel
- Game Version: f9aaa92 
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: DDA, Bionic Professions, NPC Needs

**Comment by mqrause** [comment]
This looks like a case of #22133, a bridge as a connection to a mapgen special.
