### ISSUE TITLE
Reload and fire unloading when not loaded

### ISSUE THREAD

**Issue by AlexMooney** [CleverRaven/Cataclysm-DDA#50571]
### Describe the bug

If you bring up the `f`ire menu with a `RELOAD_AND_SHOOT` weapon equipped and then `esc` out of it, you lose several seconds unloading the weapon that you haven't loaded yet.

### Steps To Reproduce

1. Spawn a slingshot
2. Bring up the `f`ire menu
3. Immediately `esc` out of the menu
4. Several seconds pass as you unload the weapon that you didn't load yet

### Expected behavior

I expect to be able to hit `esc` to bail out for free, unless I've `r`eloaded the weapon or I've begun to aim.

### Versions and configuration
- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.2 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-1395-gbcb8e7f596 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

### Additional context

I've tested that the unload code is hitting this message:
https://github.com/CleverRaven/Cataclysm-DDA/blob/bcb8e7f596513f0a72d064c1c4f0fd1bed0461fe/src/activity_actor.cpp#L2655
but I haven't traced the code any more than that.

As a side note, the aiming times don't take into account the time to load the weapon, but the first time you steady your aim (`.`), it takes seconds to load the ammo that weren't advertised to the player.

**Comment by WelpThatWorked** [comment]
The weapon is loaded when you bring up the fire menu. This appears intentional, and is not a bug.

**Comment by AlexMooney** [comment]
Then time should pass when you hit `f` instead of when you hit `esc` or `.`.

**Comment by AlexMooney** [comment]
- When you bring up the `f` menu, no time elapses.
- If you bring up the menu and then hit esc, you unload the weapon and several seconds pass.
- If you bring up the menu and then stabilize you aim `.`, then several seconds pass.  _After doing this, escaping from the menu is instantaneous._

**Comment by AlexMooney** [comment]
>  When you open the fire menu with a reload and shoot weapon, the weapon immediately loads, and consumes the time needed to do so.
This doesn't happen.  No time goes by when you _open_ the menu.

> When you close the menu, it cannot leave the weapon in the loaded state, so it unloads the weapon, consuming the time needed to do so.
When you close the menu, no time is consumed if you steadied your aim with `.`.

> Where is the problem?
What seems to be happening is that you pay no moves to load, and you pay moves to unload when you begin aiming or when you exit the menu, whichever comes first.
