### ISSUE TITLE
wrong weight for small_turbine_engine? 0.F Stable

### ISSUE THREAD

**Issue by wanray** [CleverRaven/Cataclysm-DDA#50573]
### Describe the bug

![Скриншот 07-08-2021 223744](https://user-images.githubusercontent.com/41958381/128612358-15abf91b-68b2-4f8d-b3e9-d08c35c28c57.jpg)

### Steps To Reproduce

see cdda\data\json\items\vehicle\engine.json

### Expected behavior

.

### Screenshots

![Скриншот 07-08-2021 223744](https://user-images.githubusercontent.com/41958381/128612396-9fb7ce41-0aec-4ff7-9195-b47c5344fdb6.jpg)

### Versions and configuration

0.F Stable

**Comment by actual-nh** [comment]
There is a comment present about the lighter weight of the medium gas turbine. The largest one's lower weight is odd.

**Comment by Night-Pryanik** [comment]
Nothing is wrong with weights here. IDs of items could be literally anything.
