### ISSUE TITLE
Health feedback messages on wake-up are not triggering

### ISSUE THREAD

**Issue by Rogal-Dorn** [CleverRaven/Cataclysm-DDA#50570]
### Describe the bug

The feedback messages from health_msgs.json are not printing to the log when the character wakes up.

### Steps To Reproduce

1. Make a character
2. Debug health and health mod to an extreme value
3. Debug sleep deprivation to a high value
4. Sleep and wake-up

### Expected behavior

A snippet from health_msgs.json is printed to give feedback on the hidden health stat

### Screenshots

![image](https://user-images.githubusercontent.com/52333807/128610189-15449a32-3691-41ea-b649-28e44f9649f4.png)

### Versions and configuration

- OS: Windows 10
- Game Version: 0c328f5
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: disable npc needs, graphical overmap, bionic slots, speedydex, stats through kills

### Additional context

I have a suspicion this is related to #40069 but I do not know how that code works.

**Comment by kevingranade** [comment]
Thanks for the clear reproduction instructions.

**Comment by Night-Pryanik** [comment]
Fixed by #50791.
