### ISSUE TITLE
Wasps are immune to frag grenade damage

### ISSUE THREAD

**Issue by dleepernoinc** [CleverRaven/Cataclysm-DDA#50582]
### Describe the bug

I Found a military base and lots of goodies, and wanted to test some out. I drove by a wasp nest and slowed to open my door at 4 mph, activated and tossed a grenade (the nice military kind just called "grenade") right at the foot of a wasp, it took no damage despite many hits. Baffled, I got even closer and tried again, no joy. I wasn't sure if this was intended, so i posted on reddit, and Venera3 asked me to open the issue here.
TLDR: Wasps are immune to grenades, this seems unintended?
![Capture](https://user-images.githubusercontent.com/26723081/128616853-81cfd80c-58ab-437f-ad9c-8297bc27faf9.PNG)

### Steps To Reproduce

1: Spawn in some grenades
2: Find/spawn some wasps/wasp hive
3: Die to wasps because your grenades, they do nathinggg.

### Expected behavior

I believe grenades should harm wasps.

### Screenshots

I didnt capture the screen, but i did capture the log stating what was happening.

![Capture](https://user-images.githubusercontent.com/26723081/128616872-cab31fa4-04da-432e-8e2e-6fcd29b0a2da.PNG)

### Versions and configuration

- OS: Windows 10
- Game Version: 0.F
- Graphics version:: Tiles
- Ingame language: English
- Mods loaded: StatsThroughSkills

### Additional context

I was in a car, if that matters, but I would imagine it shouldnt.

**Comment by actual-nh** [comment]
Ping: @Venera3?

**Comment by hexagonrecursion** [comment]
Can not reproduce in experimental

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: eec1398 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by hexagonrecursion** [comment]
Can not reproduce in 0.F.
- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by hexagonrecursion** [comment]
The screenshot above could not possibly be from the same version of 0.F I'm testing: mine only has huge wasps, giant wasps and whale wasps
![wasp](https://user-images.githubusercontent.com/52621858/128623733-c6d12f9c-c9cf-4036-a83b-cd4b79caa75d.png)
![damage](https://user-images.githubusercontent.com/52621858/128623735-c309a651-cc7e-4cb0-a3a8-9973e3b58277.png)

**Comment by Venera3** [comment]
I'll be able to test it to be safe in a few days. Grenade fragmentation is pretty deep, and they do cut damage near as I can tell so there shouldn't be anything too wonky going on. Still, better safe than sorr

**Comment by Venera3** [comment]
They aren't *immune*, but the different variants consistently take different damage from fragments. 
![Waspnade](https://user-images.githubusercontent.com/72006894/128755737-b7a37404-57b9-412e-ac80-dea59aff5fd6.png)

I have the impression that it's scaled based on size (which feels weird, since it should influence hit chances not damage done on hit), but I won't be able to do some proper testing on it for a few days, in case somebody else wants to go on a dive in the meantime.

**Comment by actual-nh** [comment]
It is scaled based on size; see #49993.
