### ISSUE TITLE
Crash after NPC loses the book they are reading

### ISSUE THREAD

**Issue by Qrox** [CleverRaven/Cataclysm-DDA#50586]
### Describe the bug

Game crashes when an NPC is reading a book and the book is removed.

### Steps To Reproduce

1. Ask an NPC to read a book
   ![image](https://user-images.githubusercontent.com/11890223/128652575-1dfec688-9e71-4311-bbab-a60d33165d8a.png)
   ![image](https://user-images.githubusercontent.com/11890223/128652579-2dd32cfb-3500-49f2-b725-a2d72a24af7d.png)
   ![image](https://user-images.githubusercontent.com/11890223/128652614-8ad37e58-4bd1-4776-995c-444ca2367b3b.png)
2. Trade away the book
   ![image](https://user-images.githubusercontent.com/11890223/128652575-1dfec688-9e71-4311-bbab-a60d33165d8a.png)
   ![image](https://user-images.githubusercontent.com/11890223/128652622-bb375cef-6f9d-4f5d-9cf5-1bd43b5dfa22.png)
3. Wait for a while
4. Game crashes

### Expected behavior

The NPC stops reading instead of crashing the game.

### Versions and configuration

1d6189f3c9b3afd45622f4833e52decae0d0a43f

### Additional context

It crashes in `read_activity_actor::npc_read` when dereferencing the removed book. I tried to fix it by testing the `book` item location, but it didn't work. The stored `safe_reference` in `item_location` did not expire, but pointed to an invalid item. `safe_reference` is supposed to expire once the item is removed, so I'm clueless why this happens.

**Comment by Saicchi** [comment]
This crash also happens on the same place when you debug delete all items from an npc while they are reading a book.

**Comment by Menschheit** [comment]
Didn't dig in much into item_location class and shared_ptr, but what does "pointed to an invalid item" mean? I can reproduce the crash and `book.get_item()` just returns a nullptr, isn't it expected? What is the return value supposed to be?

**Comment by Saicchi** [comment]
An `item *`, `nullptr` means there is no item found at that item location.

**Comment by Qrox** [comment]
> book.get_item() just returns a nullptr

In my case, it returns a non-null pointer, but deferencing it results in a crash. I'm building with MinGW-w64, in case it's related.
