### ISSUE TITLE
Composite bow (light) missing crafting recipe

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#50589]
### Is your feature request related to a problem? Please describe.
Both heavy and light versions of composite bow exist in the game, but only composite bow (heavy) can be crafted by the player.

### Describe the solution you'd like
Add crafting recipe for composite bow (light).

### Describe alternatives you've considered
Add the ability to loosen/tighten limbs of composite bow similar to the compound hunting bow.

### Additional context
Game version: cdda-android-x32-2021-08-07-0649.apk

**Comment by RenechCDDA** [comment]
This is a feature request, not a bug. Anyone reading this is more than welcome to add it, but we can't let these issues sit around unloved forever.
