### ISSUE TITLE
Fonts are missing on mac version

### ISSUE THREAD

**Issue by Essnato** [CleverRaven/Cataclysm-DDA#50580]
### Describe the bug

I downloaded the latest version to see if the bug for macs had been fixed and the game did in fact open however all text was completely missing, I managed to navigate through the invisible menus far enough to start a game, which is where I saw that the tiles (that had a sprite) were all still there and functional, but there was also no text on there as well. I also checked inside the game files and turns out the fonts folder was completely empty, even though this was a fresh download.

### Steps To Reproduce

Open the game with OSX.

### Expected behavior

There should be text in an ASCII game

### Versions and configuration

- OS: OSX Catalina
- Game Version: Cataclysm-DDA experimental build 2021-08-07-2139
- Graphics version: Tiles
- Ingame language: N/A
- Mods loaded: N/A

**Comment by actual-nh** [comment]
See #50149, which may also help with some workarounds.

**Comment by Essnato** [comment]
I've tried using homebrew before, doesn't work at all on my device for some reason, so something else please.

**Comment by BrettDong** [comment]
Try editing `config/fonts.json` and remove references to Terminus font.

**Comment by Essnato** [comment]
temporary fix seems to have worked thank you

**Comment by BrettDong** [comment]
Fixed in #50609.
