### ISSUE TITLE
Game Literally Unplayable

### ISSUE THREAD

**Issue by Fireiy** [CleverRaven/Cataclysm-DDA#50590]
### Describe the bug

There is no way to load into a world.

### Steps To Reproduce

(Optional) Make a world
Attempt to load a character or make a new one
Get error message and booted back to the main menu

### Expected behavior

Game should probably not be literally unplayable.

### Versions and configuration

- OS: Windows 10
- Game Version: 4fc4b31
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: dda, no_npc_food, package_bionic_professions

### Additional context

 DEBUG    : Error: Json error: data/json/items/tool/science.json:1385:74: invalid sub effect syntax: { "message": "You have a slight feeling of being watched." },

          "condition": { "not": { "one_in_chance": 3 } },
          "effect": [
            { "message": "You have a slight feeling of being watched." },
                                                                         ^
            { "u_adjust_var": "migo_interest", "type": "migo_interest", "context": "interest", "adjustment": 1 }
          ]
        },

 FUNCTION : bool main_menu::load_character_tab(bool)
 FILE     : src/main_menu.cpp
 LINE     : 1144
 VERSION  : 4fc4b31

**Comment by 778wd** [comment]
If anyone wanna play immediately the latest version without waiting for another build, just go to every file that it throws up an error in notepad++, then find+replace "message" with "u_message".
