### ISSUE TITLE
Manually assigned inventory letters are often lost

### ISSUE THREAD

**Issue by Zeropol** [CleverRaven/Cataclysm-DDA#50591]
### Describe the bug

Manually assigned inventory letters (invlets) often get lost, in particular when un-wielding or wielding an item.
It was not true for all of the invlets I've tested, see *Additional context*

### Steps To Reproduce

1. Assign a letter to an item
2. Wield the item - The invlet *may* be lost
3. Un-wield the item - The invlet *may* be lost
4. Drop the item
5. Pickup the item. - The invlet is back

### Expected behavior

Invlet consistency

### Screenshots

![a gif](https://cdn.discordapp.com/attachments/823936842814586880/873859764071829542/cdda_assigned_letter_lost_when_wield.gif)

In this example, the invlet was lost when unwielding the item.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-1326-g3750f4cfca-dirty [64-bit] (PR 50468 build)
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    DinoMod [DinoMod],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

This bug did not happened ( for me ) when wielding/unwielding bow (z) with bow sling (Z), or spear (a) with spear strap (A), nor when bow (z) is worn when unwielded.

The invlets go back when the item is dropped then picked up again.

The bug happened to me with tailor kit (t), mp3 player (m), atomic reading light (f), S&W 619 (s).

Duplicate of (closed) #50154

**Comment by hexagonrecursion** [comment]
This is 0.F. The fix was only applied to the master branch.

**Comment by actual-nh** [comment]
Bugfix is already down as a backport candidate.
