### ISSUE TITLE
Should the difficulty of repairing runner packs be reduced?

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#50604]
# Is your feature request related to a problem? Please describe.
Even with a tailor's kit repairing a slightly damaged runner pack required tailoring 7 before success chance = damage chance. The failure rate goes up if the pack is more damaged. This seems excessive considering that crafting a *survivor* runner pack (technically not the same item, but close enough. right?) *from scratch* only requires tailoring 4

![pack](https://user-images.githubusercontent.com/52621858/128635822-1ceb07e3-bc22-4090-a17e-265909e8e58a.png)

# Describe the solution you'd like
Reduce the difficulty of repairing runner packs

# Describe alternatives you've considered
Keep as is

# Additional context

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: eec1398 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by Saicchi** [comment]
Can confirm on `0.F-1344-gc850e911f9`.
So the way the repair difficulty works:
If the item has a recipe ( or multiple ) on how to craft it, it takes the lowest difficulty of those recipes and uses it as the repair difficulty. If it doesn't, then if the item definition has a `repairs_like` field, it uses that item as a guide on how to repair it. **If both fail it sets the difficulty to 10.**, another example of an item like this is the `doctor's badge`.

So to fix this, you'd either need to create a recipe for the runner pack or add a `repairs_like` to its item definition in `data/json/items/armor/storage.json`
