### ISSUE TITLE
Consuming contained food owned by someone else is safe

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#50617]
### Describe the bug

You can safely consume someone else's food by opening Consume menu and selecting the food in question.

### Steps To Reproduce

1. Make sure food is contained (for example, yogurt in a plastic cup) and owned by someone else.
2. Open Consume menu (`E` by default).
3. Eat owned food without any repercussions.

### Expected behavior

The same mechanics as for trying to pickup owned items.

### Screenshots

![изображение](https://user-images.githubusercontent.com/11132525/128644203-872095bc-92ba-40ee-82ea-e2bd63ec9685.png)

![изображение](https://user-images.githubusercontent.com/11132525/128644213-328762f5-21a2-4438-ba9b-caec36b6bade.png)

![изображение](https://user-images.githubusercontent.com/11132525/128644223-a218bb19-c4e8-47d8-a50e-1881cb8615d4.png)

### Versions and configuration

- OS: Windows 10
- Game Version: 0.F-1425
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: default only

### Additional context
None.

**Comment by NetSysFire** [comment]
I can reproduce this and looking at the code, it actually appears to check the ownership, but maybe it does so incorrectly which might be why it does not query? It might be a good first issue but I am not sure about the exact cause of this bug.

https://github.com/CleverRaven/Cataclysm-DDA/blob/cecb4775bde77fd4637f08ab1f17478040eca1eb/src/consumption.cpp#L1786-L1789

**Comment by LeahLuong** [comment]
You don't even need a straw to drink up their milkshake!
