### ISSUE TITLE
Dragging items into an NPC annihilates the NPC

### ISSUE THREAD

**Issue by big-smitty** [CleverRaven/Cataclysm-DDA#50629]
### Describe the bug

If you are dragging a furniture item but you are blocked by an NPC, then (s)wap spaces with them, your sprite will be on top of theirs and they are uninteractable.

### Steps To Reproduce

Swap places while grabbing like in the pic
![image](https://user-images.githubusercontent.com/85451361/128688692-77cad11d-e590-4e8d-a18b-750c0006b3da.png)

### Expected behavior

block swapping, or displace npc to a vacant square

### Versions and configuration

- OS: win 10
- Game Version: 0.f
- Graphics version: [Tiles 
- Ingame language: en
- Mods loaded: aftershock

**Comment by hexagonrecursion** [comment]
I can confirm that the NPC becomes hidden. Moving off of the tile makes the NPC reappear.
1. The NPC can not be seen in the [;] mode
2. The NPC can not be seen in the [V] mode
3. I *can* talk to the NPC via the [C] menu


- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: bc1f60e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

> displace npc to a vacant square

I believe this is not always possible. Consider:
![example](https://user-images.githubusercontent.com/52621858/128801092-edc3174f-8c7c-44ea-b6ab-c553bffc1456.png)

**Comment by GoLoT** [comment]
> I believe this is not always possible. Consider:
> ![example](https://user-images.githubusercontent.com/52621858/128801092-edc3174f-8c7c-44ea-b6ab-c553bffc1456.png)

In any case the furniture will leave an empty tile after moving so moving the NPC to the last position of the grabbed furniture should work for those corner cases.

Unless you are dragging a multi-tile vehicle. But since those are not on the same layer as furniture it's likely that the NPCs won't break if they are placed on a non-walkable vehicle tile. It will be ugly but not as bad as them breaking completely.
