### ISSUE TITLE
Basecamp saltworks is missing its cooking recipes

### ISSUE THREAD

**Issue by Secret-Cisco** [CleverRaven/Cataclysm-DDA#50623]
### Describe the bug

The basecamp saltworks expansion has no available cooking recipes even when fully completed

### Steps To Reproduce

1. Mutate debug hammerspace
2. rapidly build base and saltworks (I tried evac shelter and field with same results)
3. no recipes

### Expected behavior

I expected there to be a recipe to craft salt from salt water. The JSONs for the saltworks and basecamp recipe_groups indicate that you should be able to craft salt and salt fish.

### Versions and configuration

- OS: Windows 10
- Game Version: 7a64f7e, the latest listed experimental release
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: all default

### Additional context

Copying the recipe line for crafting "salt_from_salt_water" from the saltworks recipe group into the kitchen 1 recipe groups successfully added salt crafting to the game from the central building and canteen. ALSO, The sealab basecamp has the recipe group from the saltworks as it's supposed to.

**Comment by RenechCDDA** [comment]
Those are both from saltworks_recipes_1, as you confirmed. I am also missing those when I test.

I poked it for a while, and I found out that.... for **some** reason, "saltworks_recipes_1" will only work if the providing expansion also provides "kitchen". For example, making a canteen stove that *only* provides "saltworks_recipes_1" does nothing. Making a canteen stove that *only" provides "kitchen" does nothing. But if it provides *both*, then you get the actual two recipes in "saltworks_recipes_1".

Honestly I don't know why that is. I re-reviewed the post 0.F faction camp changes, as those are the likely culprits. But I don't see anything that could cause it.

**Comment by RenechCDDA** [comment]
Okay, learn something new everyday. From the documentation:  
<html>
<body>


"kitchen" | after this upgrade mission is complete, recipe groups with "building_type": "COOK" will become visible.
-- | --



</body>
</html>

saltworks_recipes_1 indeed has the "COOK" type, so that's why it's hidden. Some quick testing says that simply adding a "blueprint_provides: kitchen" entry to the saltworks should resolve this without any knock-on effects (e.g. making food recipes available in other camp sections before they should be available).

And just in case I'm missing something.... the relevant C++ code which handles revealing these recipes: https://github.com/CleverRaven/Cataclysm-DDA/blob/8fa3885150aa2338d5a3a48bc8d7911ce4a6f684/src/faction_camp.cpp#L1074-L1084

**Comment by Secret-Cisco** [comment]
Huh, that's interesting, I didn't think to try that adding a kitchen. I saw messing around with it and couldn't get an old saltworks with no tab in the bulletin board anymore to work for some reason, but a brand new saltworks but with addition kitchen 1 recipes.

I was scrambling the code pretty bad so it's possible I missed a change though

**Comment by Secret-Cisco** [comment]
> Huh, that's interesting, I didn't think to try that adding a kitchen. I saw messing around with it and couldn't get an old saltworks with no tab in the bulletin board anymore to work for some reason, but a brand new saltworks but with addition kitchen 1 recipes.
> 
> I was scrambling the code pretty bad so it's possible I missed a change though

I tried just adding `{ "id": "kitchen" }` to the saltpan building in a completely fresh install and now it seems to be working exactly as it ought to!
![image](https://user-images.githubusercontent.com/77130566/128661467-9d65b9fc-559e-494e-b582-f55d10e60deb.png)

**Comment by Secret-Cisco** [comment]
I tried importing my old testing save into the fresh install and it had me still with one wholly non-functioning saltworks and one that also had basic kitchen recipes so it seems the fix/change isn't retroactive to old saltworks for whatever reason.

**Comment by RenechCDDA** [comment]
Yeah, during testing I learned that unlocked recipes seem to be locked into the save and are not recalculated. Unfortunately that's not something that can so easily be fixed. I'll probably put in a PR for this issue tomorrow. Faction camps not recalculating their recipes is something that would need a completely different one.

**Comment by Secret-Cisco** [comment]
In the course of testing this problem I discovered another problem, the brewery part of the saltworks also doesn't work! Thankfully that *seems* to have a simple solution which I reported and described here https://github.com/CleverRaven/Cataclysm-DDA/issues/50625 already.
