### ISSUE TITLE
Faction camp liquid recipe results should be stored in containers

### ISSUE THREAD

**Issue by Secret-Cisco** [CleverRaven/Cataclysm-DDA#50627]
# Is your feature request related to a problem? Please describe.
Basecamp recipes that create a liquid product get dumped into a dirty puddle in the storage zone.

# Describe the solution you'd like
Liquids created get stored in available containers

# Describe alternatives you've considered
They could be handed to the player upon recalling the NPC to store them like a normal recipe?

# Additional context
![image](https://user-images.githubusercontent.com/77130566/128665048-31e79710-bf1a-47d0-9670-ff9d98ec9c88.png)

**Comment by hexagonrecursion** [comment]
Confirmed: crafting Kompot spilled it on the ground
- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 7fec2ef [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by Secret-Cisco** [comment]
Seems that Maleclypse figured out the solution for this problem https://github.com/CleverRaven/Cataclysm-DDA/pull/50664#issuecomment-896486187 

Basically the camp needs to have liquid recipes that come contained like with canning.

**Comment by AmarinReyny** [comment]
Maybe another possibility would be to add another zone type for liquid-containing furniture? Granted, just giving it to the player like a normal recipe would probably be a lot less complicated...

**Comment by Secret-Cisco** [comment]
> Maybe another possibility would be to add another zone type for liquid-containing furniture? Granted, just giving it to the player like a normal recipe would probably be a lot less complicated...

The current solution (that I should get around to actually finishing) right now is a seperate NPC version of recipes that includes and fills a specific container. It's less than ideal because it locks you into a single choice of container but a lot better than a unusable puddle.

**Comment by Secret-Cisco** [comment]
> Maybe another possibility would be to add another zone type for liquid-containing furniture? Granted, just giving it to the player like a normal recipe would probably be a lot less complicated...

Being able to store the recipe results inside a furniture keg/tank would be pretty dang useful, you could potentially fill up the fermentation vat in one go instead of one container at a time. Plus then the kegs would have an actual use instead of basically just taking up space really.

**Comment by Secret-Cisco** [comment]
I'm leaving some notes here because I was working on a solution to this but gave up on it because it was too frustrating and I got tired of it. Perhaps they can be of some use to somebody else in the future?

1. Different liquids portions have different volumes, e.g. a glass bottle stores 3 water but 12 burdock wine must.
2. Different liquids portions have different weights and containers can only handle so much weight, the glass bottle can only store 12 burdock wine must despite only being 0.43 L / 0.75 L full because that maxes out its weight capacity at 6.61 lbs.
3. The number of portions of liquid a recipe produces is not always readily apparent while reading the JSON.
4. Some liquids display as a number of _charges_ rather than _portions_ in game, but still use portions in the JSON, e.g. denatured alcohol and methanol. One portion being 250 charges I believe?

**Comment by Secret-Cisco** [comment]
> Maybe another possibility would be to add another zone type for liquid-containing furniture? Granted, just giving it to the player like a normal recipe would probably be a lot less complicated...

Actually, I just tested it and if there happens to be a keg or bathtub where they place the loose liquid it will count as being stored in the furniture. So you can currently force it by temporarily restricting camp storage to just the keg you want.

**Comment by AmarinReyny** [comment]
> > Maybe another possibility would be to add another zone type for liquid-containing furniture? Granted, just giving it to the player like a normal recipe would probably be a lot less complicated...
> 
> Actually, I just tested it and if there happens to be a keg or bathtub where they place the loose liquid it will count as being stored in the furniture. So you can currently force it by temporarily restricting camp storage to just the keg you want.

That's very good to know! I'll have to experiment with optimal base layouts to see how best to utilize this fact. Thank you!

**Comment by Maleclypse** [comment]
@bombasticSlacks Would this be something you could tie into some of your zones work?  No stress if not.

**Comment by bombasticSlacks** [comment]
I'm not a base camp expert but I imagine this will get hit when someone does #53298 I'm not sure if it will be me however.

**Comment by RenechCDDA** [comment]
Still an issue as of https://github.com/CleverRaven/Cataclysm-DDA/commit/c94dc0387513d5bba49eb7d74b2b51a7a4d8c4a0
