### ISSUE TITLE
Bugged Movement

### ISSUE THREAD

**Issue by M1nze** [CleverRaven/Cataclysm-DDA#50631]
### Describe the bug

If i cycle to the movemode "Run", than walk 1 Tile and press the "cycle movemode" button again, I move at a speed of about 1550. If I move with this speed one tile zombies move about 15 tiles at once and I have no chance to run away. If I cycle further, than I get back to normal speed.

### Steps To Reproduce

1. Bind a key to the "cycle move mode" in the options menu.
2. Cycle with that key to run mode.
3. Walk 1-2 tiles.
4. Press that key again to get to crouch mode.
5. Every tile you walk now will take about 15-20 turns.

### Expected behavior

If I toggle from run to crouchmode the next moves should happen at a speed of 200 not at 1550.

### Screenshots

![Screenshot 2021-08-09 135951](https://user-images.githubusercontent.com/88654425/128702948-a3a85f9b-7777-438d-b831-efe77dafc6f0.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 9d7ed7d [64-bit]
- Graphics Version: Tiles
- Game Language: Deutsch [de]
- Mods loaded: [
    Dark Days Ahead [dda],
    NPC-Bedürfnisse deaktivieren [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by Fris0uman** [comment]
Because by pressing one more time you get prone and not crouched

**Comment by Fjolset** [comment]
I was confused about this aswell once I started cycling between the movement options. Most tilesets haven't added an icon for proning yet, so it can be a bit confusing. You are in fact just crawling. Should say aswell in the Message Log.

**Comment by actual-nh** [comment]
> I was confused about this aswell once I started cycling between the movement options. Most tilesets haven't added an icon for proning yet, so it can be a bit confusing. You are in fact just crawling. Should say aswell in the Message Log.

What icon is used? Crouched?

**Comment by Fjolset** [comment]
> > I was confused about this aswell once I started cycling between the movement options. Most tilesets haven't added an icon for proning yet, so it can be a bit confusing. You are in fact just crawling. Should say aswell in the Message Log.
> 
> What icon is used? Crouched?

I'm using UltiCa tileset and no icon seems to be used for proning at the moment. The only indiciators that you are crawling/proning that I know of, is your moement speed, player icon is blue on the minimap and the message logs.
