### ISSUE TITLE
[Ultica] Add a prone stance indicator

### ISSUE THREAD

**Issue by DalenTalas** [CleverRaven/Cataclysm-DDA#50638]
# Is your feature request related to a problem? Please describe.
Prone stance is missing an indicator near the character sprite. This had me scratching my head on why does my character move so slow, after accidentally switching to prone.

# Describe the solution you'd like
An indicator similar to run / crouch stances.

# Describe alternatives you've considered
Posting this directly on the Ultica git. But, this info may be useful for other players / developers.

**Comment by actual-nh** [comment]
Inquired on the dev discord's #graphics-and-sound channel.

**Comment by ZhilkinSerg** [comment]
There is nothing to do in the main repo - it is already supported code-wise and just needs a sprite.

**Comment by actual-nh** [comment]
Added to Ultica (although the exact form may change from the initial version) - <https://github.com/I-am-Erk/CDDA-Tilesets/pull/817>.
