### ISSUE TITLE
Infinite walking loop instead of automatic wood chopping 0.F

### ISSUE THREAD

**Issue by eptz** [CleverRaven/Cataclysm-DDA#50648]
### Describe the bug

I pressed chop my wood into planks action and now my character has been walking back and forth for the last 3 in-game hours with no way of stoping him. When I press anything I get a "program not responding" message.

### Steps To Reproduce

Press chop my wood into planks action. Except it used to work just fine. I really have no idea.

### Expected behavior

Ability to stop his action. Maybe it should be impossible to autosave during something like that, And in general him not doing whatever he is doing

### Versions and configuration

- OS: Windows 10
- Game Version: 0.F
- Graphics version: Undeadpeople
- Ingame language: english
- Mods loaded: dda; crt_axpansion; MMA; UDP_Old_Floor; UPD_BlackMilitaryCars

### Additional context

I  really wish I could just send you my save file but it weights 1/5 of a GB. This stuff is happening inside the spawn shelter so maybe you can tell me how to send just the files necessary.
I am sorry if my incompetence causes you any trouble. 

Edit:
So here is my save file: https://mega.nz/folder/Wt4GGA5R#AvWr5iixvT2X2JqCathrkQ
I think it should work but this is my first time uploading anything to MEGA so tell me if I did something wrong way or something is missing for the save file to work properly.
Also if someone would be so kind and upload this file back but fixed I would be grateful. I hope I am not asking for too much.

**Comment by eptz** [comment]
> Haven't managed to reproduce this - does this this still happen to you on latest? (Might be doing something wrong, I don't really play the game)

I haven't really played since posting this. Did you not get the loop on the save file I attached?
It should pop you into the game in the middle of the loop, unless I uploaded something wrong.

**Comment by Farseer2** [comment]
No, it just worked - guess someone solved this already

**Comment by eptz** [comment]
> No, it just worked - guess someone solved this already

So I just updated my game to the latest experimental and the bug is still there.
I think it either has to do with my configuration or there is more to save files than I uploaded.

**Comment by eptz** [comment]
I updated the game to the latest experimental and checked if it works now, and it does, thank you.
