### ISSUE TITLE
Player stays prone after waking up from sleep

### ISSUE THREAD

**Issue by StStep** [CleverRaven/Cataclysm-DDA#50644]
### Describe the bug

The player automatically lies down, going prone, when sleeping. When the player wakes up from sleep they are still prone; it doesn't matter if the wake up naturally or are interrupted. I believe the intention is to have the player automatically stand up after sleeping.

### Steps To Reproduce

For interrupted sleep:
1. Make an evacuee character
2. Sleep
3. Wakeup due to tossing and turning and you are still prone

For natural wakeup:
1. Make an evacuee character
2. Spawn blindfold, ear plugs, fur sleeping bag, and 3 poppy cough syrup
3. Place the sleeping bag on the ground
4. Drink a bunch of poppy cough syrup (like 12 doses)
5. Put in ear plugs and blindfold
6. Sleep and wake up naturally
7. There is no indicator the character stood up and if you walk you will see the ~500 move speed 

### Expected behavior

I assume standing up after sleep is the expected behavior.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: d213995 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap]
]

**Comment by actual-nh** [comment]
It is apparently when sleep is interrupted, IIRC?

**Comment by StStep** [comment]
I could see that, I can't remember if it's only happened when I was interrupted, but if you sleep as an evacuee you are definitely interrupted by not being able to sleep. I'll amend the issue.

**Comment by ERRORCODE509** [comment]
Doesn't just happen when interrupted, happens normally too.

**Comment by StStep** [comment]
Yeah, it looks like any kind of sleep. I'll update it again

**Comment by chrispikula** [comment]
Does it also happen to NPC's?
