### ISSUE TITLE
Give slings the ability to throw hand explosives like grenades, etc

### ISSUE THREAD

**Issue by Secret-Cisco** [CleverRaven/Cataclysm-DDA#50643]
# Is your feature request related to a problem? Please describe.
Slings have been used in modern history to extend the range of hand grenades and Molotov cocktails but can't be used that way in the game. It would also be cool and useful.

# Describe the solution you'd like
Let slings and staff slings load/fire ordinary thrown explosives like grenades.

# Describe alternatives you've considered
Instead of launching ordinary grenades, perhaps you could have a simple recipe that converts them for sling ammo usage. For example: tying a string to the pin to activate it upon release, or making/replacing the molotov ignition source with something more stable like a fuse or matches like some real ones have.
# Additional context
Big fan of slings

**Comment by occulti** [comment]
I think this would need to be specialist ammo similar to the rope grenade in the below: https://www.google.co.uk/books/edition/Improvised_Munitions_Handbook_Learn_How/wVw1DwAAQBAJ?hl=en&gbpv=1&dq=Tie+a+4+to+6+foot+(a+meter)+length+of+cord+to+the+grenade&pg=PA65&printsec=frontcover

![Rope Grenade](https://user-images.githubusercontent.com/87604321/128880132-86052bc9-7a48-4203-a889-8e1b75b3970e.PNG)

My approach to this would be to create a new sling grenades and molotov cocktails (possibly called sling-ready or fused grenade\molotov) that can be assembled using the grenade and a fuse - this can be activated as standard with a lighter and turned into a long fused active version of the grenade in question ready to be thrown.

Then it would just be a case of changing the sling and staff sling to accept the sling-ready items as valid ammo.

**Comment by Secret-Cisco** [comment]
Oh, thanks for the actual reference material! It's interesting to see that they replaced the safety pin with a length of fuse, I hadn't thought of that.

I thought the alternate would probably be both easier to code (ammo *version* of grenades) and made more logical sense, but I thought I'd propose using normal grenades first as it seemed simpler for UX reasons.

And your pull request looks very cool 👍 I'll be honest, I held off on trying to make this my self in part because after looking at the JSON I couldn't quite figure out how to make slings fire more than one kind of ammo.

You seem to have a handle on things but let me know if I could help in any way.
