### ISSUE TITLE
Picking up frozen water shows smash prompt with the tool's container

### ISSUE THREAD

**Issue by StStep** [CleverRaven/Cataclysm-DDA#50645]
### Describe the bug

When the player goes to pickup ice, a prompt appears asking the player if they want to smash the ice to pick it up. Rather than showing the tool being used, it suggests you are smashing the ice with the container the tool is in.

### Steps To Reproduce

1. Make an evacuee character
2. Debug Change the season to winter
3. Debug spawn water and drop it on the ground (just the water not the bottle)
4. Debug spawn a hammer and put it in a container
5. Wait for the water to freeze, and then go to pick it up

### Expected behavior

I expect the text to just show the tool being used. This can be confusing to players. 

### Screenshots

See this clip from a let's play where they encounter it this issue: https://www.youtube.com/watch?v=YB8ZRwcX0Vk&t=1400s

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: d213995 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by hexagonrecursion** [comment]
Confirmed
Hammer inside a worn backpack
![hammer1](https://user-images.githubusercontent.com/52621858/128805207-8464904b-5886-42ac-b270-c5b462d87ef4.png)
Hammer inside tool belt inside backpack
![hammer2](https://user-images.githubusercontent.com/52621858/128805209-417ca21d-3d95-42e7-9091-44dc85ffd623.png)
- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: bc1f60e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by StStep** [comment]
I haven't verified it yet, but according to the description, I think PR #53501 has resolved this.

**Comment by hexagonrecursion** [comment]
This is not fully fixed. I still get this message "Do you want to crush up water (dirty) (frozen) (2) with your backpack > messenger bag > 1 item" if I put a hammer in a messenger bag, put the bag inside a backpack and wear the backpack.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: f8734ab [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Night-Pryanik** [comment]
Can't confirm on latest experimental as of 03 November 2024.
I put a hammer in a messenger bag, put the bag inside the backpack, and wore the backpack.
![изображение](https://github.com/user-attachments/assets/51972d99-07c6-41e8-ab7b-350cda9a005f)

![изображение](https://github.com/user-attachments/assets/0720ccd5-d6d7-4b0e-a7b9-567d8754e293)
