### ISSUE TITLE
Hills & Mountains

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#50651]
# Is your feature request related to a problem? Please describe.
You climb a radio tower, find binoculars and enjoy the view. Then you realize: "There are no mountains, this must be a simulation."

The only place where Z-levels are considered seems to be man-made buildings - be it high buildings, deep labs, or bridges elevated by 1 level.

# Describe the solution you'd like
I would like hills & mountains. Initially, it doesn't seem that hard. If we place current buildings (towns) on flat ground. At least in nature, we make some hills avatar can walk up and hike. Even mountains where ropes and carabines (new item!) could be used.

The thing to consider is the field of view - you should be able to see up a hill (you know...).

# Describe alternatives you've considered
Flat, unrealistic, more boring worlds.

Sometimes in nature, you can find hills, just like you find forests (that's not yet implemented, right?).

# Additional context
Tunnels for cars?

I'm a passionate climber. Willing to utilize my knowledge and research, if climbing would be implemented. But let's keep this to simple walkable & drivable hills.

**Comment by ZhilkinSerg** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/issues/47563

**Comment by JonathanLochridge** [comment]
I see a few possible implementations depending on what the status and direction other map gen changes are headed.

1. Add a set of hill objects to the overmap specials list. Or potentially make it a bit fancier with a modular system like nested mapgen. starting with just single z-height hills would be simpler. An easier aspect that could be done once it was started would be to make variants of some more  existing overmap specials which are sensible to place on hills. Which come included with one. The lmoe shelter already has an included small hill. but we could have more.

2. Add some sort of generator to the world gen. something for linear mountains could probably be made fairly simply as an inverse of the ravine functions.
But with different attached maps. Although, a simple form might be a bit meh looking? If made simply enough. And hopefully documented well. Then, it might not be super hard for people to 
3. An Overhaul that allows shifting existing map gen to other z-level:
a blob based generator(Maybe cellular automata or a variant of the lake code?) could be used to designate regions as being shifted. Then the tiles at the edge could be given transition tiles.
Some issues are whether to make z-levels partially relative? Or require some code to automatically adjust ground based terrain to adjust to the hill curvature.
This would give large scale gentle hills. I think the Wishlist linked to above. Has some ideas that relate to that sort of an approach. 
This also would require a new set of road tile variants to handle the transitions. and hopefully some other hill-edge variants of existing terrain? As making all hill transitions be empty plains could look a little weird.

I could probably do 60% of 1. But I sort of feel like if there are any aspirations towards 3. that most work there might end up being wasted. It should be able to coexist with 2. Both 2. and 3. are significantly out of my skill level. 
I have other tasks I want to work on in the short term but I could see working on this in a week at the soonest. Most likely a couple weeks to a month though. I would appreciate seeing some more discussion before I actually start on doing something though.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
