### ISSUE TITLE
"Find Lost Dog" mission failure - NPC dialog still for active mission.

### ISSUE THREAD

**Issue by cdxdir** [CleverRaven/Cataclysm-DDA#50662]
### Describe the bug

During "Find Lost Dog" mission, dog died before I could reach the chunk (zombies spawned inside barricaded house with dog).
NPC that gave the mission still asks for the dog.

### Steps To Reproduce

1. Get "Find Lost Dog" mission from starter NPC
2. Go towards chunk with mission dog.
3. Dog dies to monsters
4. Talk to mission NPC.

### Expected behavior

NPC dialog should be for "mission failure" and not "mission active".

### Screenshots

![image](https://user-images.githubusercontent.com/25249937/128946897-98427226-631c-40a0-8150-3e29c445531c.png)
![image](https://user-images.githubusercontent.com/25249937/128946939-400eff46-5c0c-4284-8fff-1a9ab9f0a4d7.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Character has "Truth Teller" negative trait. Not sure if related.

**Comment by cdxdir** [comment]
I can provide the save if unable to reproduce.

**Comment by hexagonrecursion** [comment]
Confirmed

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 7fec2ef [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]
