### ISSUE TITLE
Character creation: selecting same hobby and trait removes too many points

### ISSUE THREAD

**Issue by STMauserrio** [CleverRaven/Cataclysm-DDA#50665]
### Describe the bug

In character creation menu If you select Shaolin Adept **Trait** and then Shaolin Adept **Hobby**, you lose the points you used for Shaolin Adept **Trait** because the game is supposed to keep the Trait enabled, but it got automatically disabled when you enable the hobby (that's the bug). So when you try to undo it, disabling the hobby because the trait is already disabled, you end up with less points than the beginning.
I don't know if it applies to all hobbies, I only tried with _Shaolin adept_.

I also found a way to undo the bug: Change Point pool to any other pool, go back to the Traits and disable Shaolin Adept Trait.
When you change the pool, the Shaolin Adept trait appears as enabled.

### Steps To Reproduce

1. Create a new character template
2. Select _Shaolin Adept_ **trait**
3. Select _Shaolin Adept_ **hobby**
4. (The _Shaolin Adept_ **trait** gets deselected automatically by the game but you don't recover the points)
5. Deselect _Shaolin Adept_ **hobby**
6. You end up with less points than the beginning. In this case, you start with 8 points and end up with 6. That's the bug.

To undo the bug:
7. Once you have already done the above steps:
8. Change Point pool
9. Disable _Shaolin Adept_ **trait** 

### Expected behavior

I expected any of these:

- I expected to recover the points from _Shaolin Adept_ **trait** after I did step 3. 
- Or the cost of the **Hobby** be reduced by the cost of the **trait** (Former costs 4, latter 2, so the new hobby cost would be the substraction: 4 - 2 = 2)
- Or even the trait to stay enabled but that doesn't really make sense because, objectively and in total, the hobby cost would be the **hobby** (4) + the **trait** (2) = 6 points.

### Versions and configuration

- OS:  Windows 10
- Game Version: ed2f630
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: Default mods upon world creation

**Comment by hexagonrecursion** [comment]
I see two possibly related bugs:

# Cost inconsistency
Action | Point pool state after the action
-|-
1 Select the Shaolin Adept hobby | **6+0-2**

Action | Point pool state after the action
-|-
1 Select the Shaolin Adept trait | 6-2+2
2 Select the Shaolin Adept hobby | **6-2-2**
Undoing: |
3 Deselect the Shaolin Adept hobby | 6-2+2
4 Deselect the Shaolin Adept trait | 6+0+2

# Permanent point loss
Action | Point pool state after the action
-|-
1 Select the Shaolin Adept trait | 6-2+2
2 Select the Shaolin Adept hobby | 6-2-2
3 Notice that the trait is now deselected |
4 Select the Shaolin Adept trait again | 6-4-2
5 Deselect the Shaolin Adept hobby | 6-4+2
6 Now both the trait and the hobby are deselected and 4 points from the trait pool are gone |

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 7fec2ef [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]
