### ISSUE TITLE
Adjust time for shelling nuts

### ISSUE THREAD

**Issue by plattfish** [CleverRaven/Cataclysm-DDA#50668]
# Is your feature request related to a problem? Please describe.
I feel like shelling (i.e. deconstructing) nuts takes too long. 5-10 minutes for a handful of nuts (abstracted as a single hazelnut, chestnut, etc.) seems  like overkill. 

# Describe the solution you'd like
Adjust the time for shelling nuts downwards to maybe 1-2 minutes per "handful" of nuts. Maybe 3 minutes for walnuts, since they are trickier than some other nuts. Just throwing these numbers out there, any decrease from 5-10 minutes would help!

# Describe alternatives you've considered
Perhaps giving a deconstruction time bonus for batch-deconstructing nuts. But I think batch deconstruction is its own big project, so I think the above is more reasonable in the meantime.

# Additional context
No mockups for this, just a simple recipe timing change. 

NOTE: I think there are a couple of open pull requests for nut adjustments, so the above request may have already been dealt with, and is just pending merging! https://github.com/ERRORCODE509/crack_the_nut

**Comment by plattfish** [comment]
Okay, fair point. Maybe the calories per serving need to be tweaked then? Taking almonds for example -> 5 minutes to shell "1" almond (240 grams of almonds) for 125 kcal. Looking here: https://www.fatsecret.com/calories-nutrition/usda/almonds?portionid=59771&portionamount=250 there are almost 1500 kcal in 250 grams of almonds. For 250 grams of walnuts, it's 1600 kcal vs the 125 in game. 

It just feels a bit unbalanced right now, in terms of time in vs. kcal out. Then again, maybe this should be saved for a broader look at recipe times, if that is on the agenda? Just an inconsistency I noticed!

**Comment by ZhilkinSerg** [comment]
Shelled almonds: 125 kcal is for one 30 gram serving in CDDA. That site reports 173 kcal for 30 gram.
Shelled walnuts: 144 kcal for one 30 gram serving in CDDA. That site reports 196 kcal for 30 gram.
Shelled pistachos: 126 kcal for one 30 gram serving in CDDA. That site reports 160 kcal for 30 gram.

While there is a difference it is not tenfold.

**Comment by plattfish** [comment]
Hmm, those numbers definitely make more sense. 30 grams of almonds is about 20 individual almonds, and I guess I could see that taking about 5 minutes to deshell.

Maybe this is just a bigger issue about not being able to bulk disassemble, since individually disassembling 10+ nuts can get annoying.

I'll go ahead and close this issue, I feel like there is less inconsistency here than it originally appeared.
