### ISSUE TITLE
Aftershock cold resistance cream doesn't go away

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#50676]
### Describe the bug

On the development discord, someone implied that their cold resistance cream aura never went away after they put it on.
cold_res_cream
cream_prot_cold

The cold_res_cream is found up to a count of 3 in afs_escape_pod_suppliesII

### Steps To Reproduce

Put on the cream / aura
Wait 2+ hours.

### Expected behavior

That it'd go away post being put on.

### Versions and configuration

N/A

### Additional context

I looked at the JSON, and was wondering if it would be better if the item was turned instead a tube of cream, and then 'activated' to turn into a wearable item with the NO_TAKEOFF flag.  Then have it wear off with a delayed_transform and transform_age into nothingness?  Rather than a spell effect duration that reportedly doesn't work?

Or maybe something else that creates the spell effect should be found in afs_escape_pod_suppliesII ?

**Comment by Maleclypse** [comment]
Duplicate of #49707 fixed by same fix.
