### ISSUE TITLE
Bundles of fabrics cannot be disassembled

### ISSUE THREAD

**Issue by Fireiy** [CleverRaven/Cataclysm-DDA#50674]
### Describe the bug

When you attempt to disassemble a bundle of felt, rags or leather, you get a in progress disassembly at -21474% progress instead. This bug does not occur with the other bundle items. Cutting them up however still works.

### Steps To Reproduce

Spawn in a bundle of felt, rags or leather.
Attempt to disassemble them.
Be unable to.

### Expected behavior

Bundles of fabric should be able to be disassembled.

### Screenshots

![Screenshot 2021-08-11 052055](https://user-images.githubusercontent.com/18078627/129028391-121c40f9-3805-4ca4-a180-a5ed6500c647.png)

### Versions and configuration

- OS: Windows 10
- Game Version: 5b0c218
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: dda, no_npc_food, package_bionic_professions

**Comment by Marrim** [comment]
Can confirm. Noticed after updating to 7fec2ef.
Terminal, Ubuntu 18.04.
Modset: Default + StatsThroughKills.

**Comment by ferociousdork** [comment]
This is a bug in #50479. All items that have zero deconstruction time are affected.

When `moves_total` is 0, a division by zero happens here, causing `craft.item_counter` to become `INT_MIN` after casts:
https://github.com/CleverRaven/Cataclysm-DDA/blob/5b0c21832ab74c439dd1e66897d80767e28c0ecb/src/activity_actor.cpp#L4120
