### ISSUE TITLE
Activatable paper

### ISSUE THREAD

**Issue by TealcOneill** [CleverRaven/Cataclysm-DDA#50671]
### Describe the bug

I found in a clothing store locker a hundred pieces of paper with the (active) tag, including the yellow color.

### Steps To Reproduce

1. Find a clothing store.
2. Search for janitor's closet.
3. You might find the same thing.

### Expected behavior

Paper should not be activatable.

### Screenshots

![activepaper](https://user-images.githubusercontent.com/45678006/128985601-ff429c25-a9fb-4617-b704-102012ecbcb2.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: d17ef5b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by ferociousdork** [comment]
Is this on a fresh save, or one that's more than a week or two old? Paper was recently changes from comestible to ammo, and comestibles are active to process rot. So if it's an old save, it could just be an item that was already generated in your world.

**Comment by TealcOneill** [comment]
If there's a way to check the date I can tell you exactly but I believe it's right around a week old. That does make sense though.

**Comment by ferociousdork** [comment]
You can just check the creation date of your save file, or you can open the save file, search for `game_version` and post that version string here.

**Comment by TealcOneill** [comment]
I kind of forgot about this. I couldn't find the actual time and I haven't found anymore since then so I'm going to close the issue. I'll reopen it if I find anymore activated paper in the new world I've created.
