### ISSUE TITLE
I can assign followes to missions at the Tacoma Commune even if they are far away

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#50688]
### Describe the bug

If a follower is assigned to a camp it is possible to send her on a mission at the Tacoma Commune. Sometimes doing so causes the follower to completely vanish - the mission to recover him is missing 

### Steps To Reproduce

1. Load the attached save [eat.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6970773/eat.zip)
2. Talk to the foreman
3. Assign Concetta Corona to menial labor
4. See that there is no mission to "recover ally"

### Expected behavior

It should not be possible to assign a follower to a mission unless she is at the Tacoma Commune

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 7fec2ef [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by Catalyst2114** [comment]
A jank work around to this is to go into the debug mode, control the npc you sent on the mission, and then edit the mission to be completed then you'll get your npc back.

**Comment by Eb-** [comment]
Related https://github.com/CleverRaven/Cataclysm-DDA/issues/81944
