### ISSUE TITLE
Bulk dissassembly passively interrupted on second item

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#50686]
### Describe the bug

Currently when one tries to 'Dissassemble Everything Once' when ontop of a pile of stuff, you only disassemble the first item, then you stop after wielding or putting the second item onto the counter at 0% complete.

### Steps To Reproduce

Make a character, spawn a multitool, stand over a pile of items then 'B'utcher them to Dissassemble Everything Once'.
This also happens when you try it recursively.

### Expected behavior

To take apart the whole pile of items that it's possible to take apart without writing a keyboard macro.

### Screenshots

![image](https://user-images.githubusercontent.com/22281606/129082162-d04dbe3a-1094-472e-bd03-6c0e20494f50.png)

### Versions and configuration

No Mods, base game.
-----------------------------------------
12:21:12.315 : Starting log.
12:21:12.315 INFO : Cataclysm DDA version d213995
12:21:12.315 INFO : [main] C locale set to C
12:21:12.315 INFO : [main] C++ locale set to C
12:21:12.315 INFO : SDL version used during compile is 2.0.14
12:21:12.315 INFO : SDL version used during linking and in runtime is 2.0.14
12:21:12.528 INFO : Number of render drivers on your system: 5
12:21:12.528 INFO : Render driver: 0/direct3d
12:21:12.528 INFO : Render driver: 1/direct3d11
12:21:12.528 INFO : Render driver: 2/opengl
12:21:12.528 INFO : Render driver: 3/opengles2
12:21:12.528 INFO : Render driver: 4/software
12:21:12.533 INFO : [options] C locale set to C
12:21:12.533 INFO : [options] C++ locale set to C
12:21:12.533 INFO : Setting language to: 'en'
12:21:12.533 INFO : Language is set to: 'en'
12:21:12.533 INFO : [translations] C locale set to English_Canada.1252
12:21:12.533 INFO : [translations] C++ locale set to C
12:21:12.785 INFO : Active renderer: 0/direct3d
12:21:13.020 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
12:21:13.224 INFO : Setting language to: 'en'
12:21:13.224 INFO : Language is set to: 'en'
12:21:13.224 INFO : [translations] C locale set to English_Canada.1252
12:21:13.224 INFO : [translations] C++ locale set to C
12:21:20.281 WARNING : opendir [./save/Hargis/mods] failed with "No such file or directory".
12:21:48.680 INFO : Loaded tileset: UNDEAD_PEOPLE_BASE
12:21:57.957 ERROR SDL : src/sdlsound.cpp:583: Failed to play sound effect: Tried to play a chunk with a bad frame

**Comment by ferociousdork** [comment]
This is another bug in #50479. When multiple items are disassembled, `Character::complete_disassemble` assigns the next target; but the new code calls `cancel_activity` unconditionally afterwards, cancelling the activity for subsequent disassemblies:
https://github.com/CleverRaven/Cataclysm-DDA/blob/216401f5c94bb318af4de90322bf72c4856baa6c/src/activity_actor.cpp#L4125-L4128
