### ISSUE TITLE
Can not assign a follower to a mission at Tacoma Commune unless the follower is set to guard

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#50682]
### Describe the bug

When I try to assign followers to a mission at Tacoma Commune I get "You don't have any companions to send out" even though I do have a follower NPC that is not currently on a mission.

### Steps To Reproduce

1. Load the attached save file [save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6970153/save.zip)
2. Talk to the foreman
3. Select the "Assign Ally to Menial Labor'

### Expected behavior

I should be able to assign the follower to a mission

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 7fec2ef [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Workaround: talk to the follower -> There is something I want you to do -> Guard this position.

This works but is completely unintuitive and undiscoverable -> most players will never figure this out.

**Comment by Eb-** [comment]
Related: https://github.com/CleverRaven/Cataclysm-DDA/issues/81944
