### ISSUE TITLE
CTD when bringing up the @ menu

### ISSUE THREAD

**Issue by eltank** [CleverRaven/Cataclysm-DDA#50700]
### Describe the bug

Game crash

### Steps To Reproduce

(maybe needed) Enable skill rust (Vanilla) in Options
Load the attached save
Press `@`
Observe crash

### Expected behavior

No crash

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: cb862016 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6973004/save.zip)
Nothing useful in debug.log

**Comment by eltank** [comment]
Reported by `CuddleStruggle` on discord

**Comment by anothersimulacrum** [comment]
DBZ in `SkillLevel::exercise` because some of the skills have negative levels.
