### ISSUE TITLE
Rethink the terrain DOOR flag

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#50707]
# Is your feature request related to a problem? Please describe.
The terrain flag DOOR is poorly named and its semantics are unclear. This causes bugs such as https://github.com/CleverRaven/Cataclysm-DDA/pull/46505.

I have found several instances of the above bug that are still unfixed:
https://github.com/CleverRaven/Cataclysm-DDA/blob/b991a1bab26d0fb8a6f9068ab4e9c9639ab76e26/data/mods/More_Locations/secret_doors/secret_door_terrain.json#L54-L60
https://github.com/CleverRaven/Cataclysm-DDA/blob/b991a1bab26d0fb8a6f9068ab4e9c9639ab76e26/data/mods/More_Locations/secret_doors/secret_door_terrain.json#L104-L110
https://github.com/CleverRaven/Cataclysm-DDA/blob/b991a1bab26d0fb8a6f9068ab4e9c9639ab76e26/data/mods/More_Locations/secret_doors/secret_door_terrain.json#L153-L159
https://github.com/CleverRaven/Cataclysm-DDA/blob/b991a1bab26d0fb8a6f9068ab4e9c9639ab76e26/data/mods/More_Locations/secret_doors/secret_door_terrain.json#L202-L208

[This is what the documentation currently says about the flag](https://github.com/CleverRaven/Cataclysm-DDA/blob/f398549c7c9fa5ebbad200c255cabba852f85bf0/doc/JSON_FLAGS.md):
> DOOR Can be opened (used for NPC path-finding).

The flag is currently used in several seemingly unrelated places:
https://github.com/CleverRaven/Cataclysm-DDA/blob/0f8bd786da742b2e57def98e795a3a76921a30ac/src/start_location.cpp#L373
https://github.com/CleverRaven/Cataclysm-DDA/blob/0f8bd786da742b2e57def98e795a3a76921a30ac/src/npcmove.cpp#L2332
https://github.com/CleverRaven/Cataclysm-DDA/blob/0f8bd786da742b2e57def98e795a3a76921a30ac/src/mapgen.cpp#L3481
https://github.com/CleverRaven/Cataclysm-DDA/blob/0f8bd786da742b2e57def98e795a3a76921a30ac/src/mapgen.cpp#L3729
https://github.com/CleverRaven/Cataclysm-DDA/blob/0f8bd786da742b2e57def98e795a3a76921a30ac/src/mapgen.cpp#L3821
https://github.com/CleverRaven/Cataclysm-DDA/blob/0f8bd786da742b2e57def98e795a3a76921a30ac/src/mapgen.cpp#L3846
https://github.com/CleverRaven/Cataclysm-DDA/blob/0f8bd786da742b2e57def98e795a3a76921a30ac/src/mapgen.cpp#L3956
https://github.com/CleverRaven/Cataclysm-DDA/blob/0f8bd786da742b2e57def98e795a3a76921a30ac/src/mapgen.cpp#L4021
https://github.com/CleverRaven/Cataclysm-DDA/blob/0f8bd786da742b2e57def98e795a3a76921a30ac/src/cata_tiles.cpp#L3909

# Describe the solution you'd like

The flag should probably be split into several better named flags.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
