### ISSUE TITLE
Friendly turkeys fly over a fence, they stay at Z+1 and stop following you (can't see you?)

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#50715]
### Describe the bug

Friendly turkeys fly over a fence, they stay at Z+1 and stop following you (can't see you?)

### Steps To Reproduce

1. Load save.
2. Climb over a fence.
3. Observe fewer turkeys are following you.
4. Climb onto shelter roof by north steplader.
5. Observe turkeys are in the air.

### Expected behavior

Turkeys can see you down there and will follow you down there.

### Screenshots

![friendly turkeys fly over the fence](https://user-images.githubusercontent.com/13402666/129216700-9acf42b8-e4b2-422a-a7de-d4012748a074.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0f8bd78 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

I cannot look up and have to climb on the roof to see they indeed are in the distance stuck flying over a fence.

**Comment by Brambor** [comment]
Turkeys stay afloat for an entire day without going down. Doesn't really make sense and I will slowly loose my turkeys :(

**Comment by actual-nh** [comment]
Do you have 3d/Z-level vision on? They should be able to see you and vice/versa if you turn it on (as well as other monsters the same way!).

**Comment by Brambor** [comment]
> Do you have 3d/Z-level vision on? They should be able to see you and vice/versa if you turn it on (as well as other monsters the same way!).

I hadn't. It defaults to false. However, this is not obvious to regular players, that they should turn it on when their turkeys seemingly disappear.

![image](https://user-images.githubusercontent.com/13402666/129232861-98db2a8f-8a43-4f97-8617-fef65d18dbc6.png)

**Comment by Brambor** [comment]
Even with 3D vision, the turkey doesn't want to go down and keeps flying. Still, it is a huge improvement for getting the birds back. But I don't know how to get the turkey down...

**Comment by actual-nh** [comment]
Probably monster Z-level pathing problems. Have you tried climbing over the fence again to see if it follows you then?

**Comment by Brambor** [comment]
> Probably monster Z-level pathing problems. Have you tried climbing over the fence again to see if it follows you then?

I haven't, but will, thx for tip.

**Comment by Brambor** [comment]
> Probably monster Z-level pathing problems. Have you tried climbing over the fence again to see if it follows you then?

I did now, They didn't follow down, since I now have 3D vision enabled. But I could easily see them now, thanks for that.

I think they fly for too long. I would go along a road, see turkeys in the forest and they often are flying...

**Comment by actual-nh** [comment]
For the fence ones, if you can reach them by climbing, you should be able to leash them now (#50890). Currently, the "FLIES" flag is, well, binary - either a critter has it or it doesn't. Ideally, monsters that should be flying all the time would be specifically marked, and the rest would be on a structure or the ground if they didn't have a reason to fly.

**Comment by Brambor** [comment]
I see that I forgot to attach a save file. Sigh...
Or I wanted to but the 3d was brought up so quickly that I thought it was not needed anymore.
Silly me.

**Comment by Brambor** [comment]
#68213 (or some earlier PR) fixed this.
It is now also easy enough to get friendly turkeys down from the roof with a leash.

Spawned a chain link fence and went over it, turkey following me. `The turkey flies over the chain link fence.` And I can still see it.
