### ISSUE TITLE
Save saves as .zip

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#50711]
# Is your feature request related to a problem? Please describe.
Save has 82.1 MB on disk. `.zip` of that save has 10.0 MB. Maybe we could add an option to save saves as .zip? Bigger loading times (barely), but smaller save sizes.

# Describe the solution you'd like
Add in-game option in settings to save files as `.zip`. Maybe no option, just make it default.

Make the game able to load folders and zips. For backward compatibility & it's a free feature.

Maybe even add an option to "save as" .zip, so when the game is loaded from a folder, the folder is deleted and replaced by .zip on saving. - This is to save space for those, who already have games in folders. They might not even notice, but their saves will suddenly take 9x less space!

A nice side effect is that players don't have to zip saves before posting to GitHub, because they are already zipped!

# Describe alternatives you've considered
Needlessly big saves.

# Additional context
[Factorio](https://www.factorio.com/) has .zipped saves, so it's probably the way to go!

**Comment by actual-nh** [comment]
.zip format is generally not as portable as one might think. Gzip is among the possibilities being examined; see #44218.

**Comment by ERRORCODE509** [comment]
Issue I see with this is that it would make editing saves unnecessarily difficult, as it must be unzipped, edited, then redipped.

**Comment by Zireael07** [comment]
@ERRORCODE509: Most users do not need editing saves ;)

**Comment by ERRORCODE509** [comment]
True, though I'm mostly just referring to editing the mod list for a world mid-game.

**Comment by Leland** [comment]
See historic issues #10784, #19192, #14307, #24916.

**Comment by Brambor** [comment]
Ok, I see, I read the issues linked so I'm closing this too :/

**Comment by Brambor** [comment]
I don't know where else to put it so:
zipped files would increase the speed of CDDA Launcher update, as it moves the save files. It can be told not to do so, however, after last time it broke on experimental and I had to manually edit the save, I like to keep the option on.

**Comment by Maddremor** [comment]
@Brambor I think https://github.com/CleverRaven/Cataclysm-DDA/wiki/Command-Line-Parameters would help with your actual problem.
