### ISSUE TITLE
Upon lighting a fire on a brazier, my practical and theoretical understanding of survival became godly. (85 on both)

### ISSUE THREAD

**Issue by Obeycap** [CleverRaven/Cataclysm-DDA#50713]
### Describe the bug

Title.

When I lit my brazier to cook some coyote meat, my survival shot up, both in practial and theoretical terms, to 85 each. The most perplexing part of all this is that, as far as I know, I was not using the survival skill at the time in which it shot up.

### Steps To Reproduce

I have absolutely no idea. I had lit the brazier multiple times before, to boil water on 60L tanks from the evac shelter roof. I hauled some planks from the benches up to the brazier, lit it up, but this time, immediatly after lighting it up I got 85 survival. I wasn't doing any survival work, I started with 0 survival, I might have gotten some of it off hand from one of the crafts, but looking back at it, that really doesn't seem likely.

Hopefully my save is of some use figuring this out though. (Additional Context.)

### Expected behavior

Not what happened. The action I took was not a survival skill action, nor something that normally grants experience.

### Screenshots

![](https://cdn.discordapp.com/attachments/699896059555610717/875377123500634172/unknown.png)

![](https://cdn.discordapp.com/attachments/699896059555610717/875377333425545286/unknown.png)

### Versions and configuration

- OS: Windows 10
- Game Version:  0f8bd78, 2021-08-12-0754 release
- Graphics version: Tiles
- Ingame language: EN
-Mods: magyclism, aftershock, bionic professions, blaze industries, Fuji's military, graphical overmap, disable npc needs.

### Additional context

Here's my save.
[Hitchland.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6976019/Hitchland.zip)

**Comment by Obeycap** [comment]
could be possible. This is the experience value at the time I checked.

![](https://cdn.discordapp.com/attachments/598523535169945607/875379493680848936/unknown.png)

and I almost forgot, version 0f8bd78, 2021-08-12-0754 release.

**Comment by actual-nh** [comment]
Do you have skill rust turned on?

**Comment by actual-nh** [comment]
Ping: @anothersimulacrum, @eltank, @I-am-Erk?

**Comment by Obeycap** [comment]
> Do you have skill rust turned on? (I am assuming so, given practical/theoretical split.)

It's off, because it's off by default, but it might be working despite the debug setting because of the theoretical skill update?

**Comment by I-am-Erk** [comment]
The theoretical skill split is separate from the rust setting anyway

**Comment by eltank** [comment]
I can see where the overflow is happening in `SkillLevel::rust`

First we have:
`float rust_slowdown = std::max( static_cast<float>( std::sqrt( _rustAccumulator / level_exp ) ), 0.04f );`
When _rustAccumulator is 0, this becomes 0.04.

Then `int rust_amount = level_multiplier * 16 / rust_slowdown`
This evaluates to 4,000,000 at level 0 or 144,000,000 at level 5.

Then if rust_resist > 0 this gets multiplied by about 100 which makes it > 2^31 (INT_MAX) if level is >= 2.

The overflow in that last multiplication is my fault and I can fix it by using floating point arithmetic, but I'm a bit suspicious about the rust_slowdown/rust_amount formula. Should it really be evaluating to level_multiplier * 16 / 0.04 (or level_multiplier * 400) when rustAccumulator is 0?

**Comment by eltank** [comment]
But I think I see how people end up with >100% practice.
`_exercise = ( 100 * 100 * level_multiplier ) - 1;`
is using the level_multiplier for the current level, not the lower level it's about to drop to.
Should be changed to:
`_exercise = ( 100 * 100 * _level * _level ) - 1;`

**Comment by eltank** [comment]
As a quick fix we could change the while loop in `SkillLevel::train`
`while( _exercise >= xp_to_level )`
to an `if` so that you can only gain 1 level in a single `train()` call and also reset `_exercise` to 0.

**Comment by actual-nh** [comment]
> > Do you have skill rust turned on? (I am assuming so, given practical/theoretical split.)
> 
> It's off, because it's off by default, but it might be working despite the debug setting because of the theoretical skill update?

Or because isRusting isn't preventing rusting - see #50718.

**Comment by eltank** [comment]
I have a PR to hopefully fix both.
