### ISSUE TITLE
Allow keybinding customization in the drop menu

### ISSUE THREAD

**Issue by OneThousandResets** [CleverRaven/Cataclysm-DDA#50729]
As of the latest experimental, the keybind to SELECT an item in the multidrop menu as been changed from RIGHT to ".". Muscle memory is giving me some trouble. There is no in game option to change those myself.

Previously:
![Capture2](https://user-images.githubusercontent.com/86806985/129271804-3fe828af-46c5-4eef-a6ca-47ddd86dcd3f.PNG)

Latest experimental:
![Capture](https://user-images.githubusercontent.com/86806985/129271595-378d2938-4cb1-401e-96cd-913f991b3749.PNG)

build type: windows-tiles-x64
build number: 2021-08-12-0754
commit sha: 0f8bd786da742b2e57def98e795a3a76921a30ac
commit url: https://github.com/CleverRaven/Cataclysm-DDA/commit/0f8bd786da742b2e57def98e795a3a76921a30ac

It would be also nice to be able to reassign the keys in the aiming menu.

Kudos. Godspeed.

**Comment by eltank** [comment]
This feature already exists.
Press `?` in the multidrop menu to change the key bindings.

https://user-images.githubusercontent.com/8000047/129301167-3fe25bd7-a1f7-41e7-906f-248bded3214e.mp4

**Comment by eltank** [comment]
Oh and `?` works during aiming and many other contexts to change the key bindings for each specific interface.

**Comment by OneThousandResets** [comment]
Thanks for your help eltank. I went the longest time unaware of said feature.

I close the issue.
