### ISSUE TITLE
Character creation recipes stay if skill in increased to max then decreased

### ISSUE THREAD

**Issue by paroid01** [CleverRaven/Cataclysm-DDA#50730]
### Describe the bug

During character creation, if you set a skill to a particular level, then reduce the skill, the recipes that would have been learned by having the skill at that level are kept instead of removed.

I believe this is a side effect of the new skill knowledge/practical system introduced in #50176

### Steps To Reproduce

Enter character creation to make a new custom character.

Increase skills to some high level in the skill screen and then decrease back to a level that allows game to start.

Notice that the knowledge level of the skill remains as high as they were increased to in character select, and recipes are learned.

### Expected behavior

Recipes and highest skill level known should probably only be set on exiting of character creation after point allocation is finalized.

### Screenshots

![image](https://user-images.githubusercontent.com/46875613/129280643-dc9fb58b-05bf-43ae-a4f1-d272c6641aad.png)

![image](https://user-images.githubusercontent.com/46875613/129280667-aebd3062-025b-4417-b602-ebf7c1f623b3.png)

![image](https://user-images.githubusercontent.com/46875613/129280720-9945adc7-582e-4b52-9549-004ff1dfd916.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0f8bd78 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

I didn't test if selecting a hobby that gives experience to a skill and then unselecting the hobby was causing a similar bug, but I suspect fixing this will fix that if it was also an issue.

**Comment by eltank** [comment]
When decreasing a skill level in the chargen menu, the theoretical level doesn't change. So after starting the game you'd also get a large boost to leveling up that skill due to skill rust.

Alright, I'll fix this too.

**Comment by eltank** [comment]
"I didn't test if selecting a hobby that gives experience to a skill and then unselecting the hobby was causing a similar bug"

It doesn't. Hobbies give skill xp instead of levels and that's applied at the end.
Changing professions also doesn't trigger the bug.
