### ISSUE TITLE
Character Info Panel can't display all skills with knowledge levels

### ISSUE THREAD

**Issue by paroid01** [CleverRaven/Cataclysm-DDA#50731]
### Describe the bug

Have a bunch of skills with a high knowledge but low practical and you can't see the level of your skills in the character information window.

Related to new skill rust change I think #50176

### Steps To Reproduce

Debug mode assign all your skills to 10 then all to 0 and open the character info panel.

### Expected behavior

Either need a more concise way of displaying the practical/knowledge skills on one line or that panel needs to sub scroll.

### Screenshots

![image](https://user-images.githubusercontent.com/46875613/129281071-db395fa7-1360-4014-becd-b375634dba4c.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0f8bd78 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by I-am-Erk** [comment]
I believe that window is scrollable. However the UI needs improvement regardless.

**Comment by paroid01** [comment]
While I can move my active selection to different skills, the rendering of the window doesn't change. Here is a screenshot of me selecting throwing skill and a screenshot of me moving down to select applied science.

![image](https://user-images.githubusercontent.com/46875613/129283174-92b8b84c-939c-4d49-8c2d-e9206730772c.png)

![image](https://user-images.githubusercontent.com/46875613/129283186-34e75400-903c-442c-b886-d8622ffa1327.png)

**Comment by I-am-Erk** [comment]
Fair enough, that definitely needs fixin

**Comment by eltank** [comment]
See #50734 for a fix
