### ISSUE TITLE
0.F.exe file not reacting

### ISSUE THREAD

**Issue by Chaos8ringer** [CleverRaven/Cataclysm-DDA#50745]
### Describe the bug

The problem is that the .exe files do not react. There is no popup, no windows defender warning, no antivirus warning. 

I have attempted the following to try and fix this problem:
-Unpack the game in C:\Programs\CDDA TEST\
-Run as administrator
-Grab a version from the CDDA community discord with a pregenerated config, template, etc. based on the assumption that there is a problem with the generation part of the .exe
-checked drive space (+40 gb)
-tried on both SSD and HDD
-Tried compatibility mode with windows 8 and 7
-redownloaded the newest stable 0.E version, unpacked it in a new folder and ran it, which successfully generated files, a world, a character and allowed me to play.
-while writing this bug report, i tried running the game from INSIDE the zipfile. After a brief extraction, the game actually started up, and after closing it implemented the config, template, and all other first-startup-generated files into the zip. I have not attempted to generate a world or a character. I am using WINRAR, in case this is important.
-ran a registry cleaner and fixer (CCleaner, and SFC & DISM over CMD)
-I have no idea what's going on or how to fix this. 

### Steps To Reproduce

I sadly do not how to reproduce this problem.

### Expected behavior

I expected the game to run as it usually did.

### Versions and configuration

Running the newest Windows 10 update.
i have tried the current 0.F stable as of the time of writing, and versions:
cdda-windows-tiles-x64-2021-08-13-0925
cdda-windows-tiles-x64-2021-07-03-0512
cdda-windows-tiles-x64-2021-08-12-0754

I cannot give the ingame mentioned versions for these since i cannot reach the main menu

**Comment by Chaos8ringer** [comment]
i tried unpacking the game from the .zip file in which the new config files were generated and it appears to work now. The version is ecc6a8f.
I could successfully generate a world and character. I will try out and the game and check in with the changelog to see if it is indeed the new version i am playing and nothing strange happened.

**Comment by ZhilkinSerg** [comment]
Try running the game from a folder you have write access to - e.g. create folder `C:\Games\cdda` under your account and unpack game there.

**Comment by Chaos8ringer** [comment]
tried that: C:\Games\cdda\

Sadly no result. Starting the game in the .ZIP, having it generate the config inside the .ZIP and unpacking it, however, works. So i theoretically "fixed" the problem with a workaround.

**Comment by ZhilkinSerg** [comment]
You are missing write permissions to your folder - probably creating your folder and/or unpacking under admin account, then running game w/o admin account.

**Comment by Chaos8ringer** [comment]
that would be weird, i just tried the same thing with the newest stable 0.E version which i just downloaded and it worked like a charm, it is only the 0.F version that causes these problems. Was there a large change in the backend that warrants write permission issues?

**Comment by ZhilkinSerg** [comment]
Permissions issue is on your end. When you say it works fine when you run the game from inside the archive - what really happened is winrar unpacked zip to some temporary folder, started executable and then put everything from that temporary folder (including config folder and its contents) back to archive after you closed the game. That means cdda works fine overall and you probably just lack permissions to create files in a folder you put nee version to.

**Comment by Chaos8ringer** [comment]
okay, thank you for the insight, i'll try to figure out why only 0.F has permission issues :D

**Comment by Chaos8ringer** [comment]
Just did, admin and system has full control, user has write & execute.

**Comment by Zireael07** [comment]
Did you unpack 0.E to the exact same folder you tried to unpack 0.F into?

**Comment by Chaos8ringer** [comment]
just tried that too, first unpacked a new 0.E, which started and generated config files, then deleted it and extracted 0.F, which once again did not react.

**Comment by actual-nh** [comment]
Did the permissions change _after_ unpacking?

**Comment by Night-Pryanik** [comment]
@Chaos8ringer is this still an issue?

**Comment by Night-Pryanik** [comment]
Closing as stale and unconfirmed.
