### ISSUE TITLE
Drug Deal Overriding Road Terrain

### ISSUE THREAD

**Issue by EmpressWynnter** [CleverRaven/Cataclysm-DDA#50747]
### Describe the bug

I have noticed that when a drug deal occurs in the middle of a road, the tile is not generated with road terrain, and instead spawns with grass and some rock terrain. 

### Steps To Reproduce

1. Generate a world with the same mods and game version as below.
2. Wander around until you find a road tile with a drug deal (unless there is a way to generate them via debug).

### Expected behavior

The corpses, blood, and items should spawn on top of a normal, or mostly normal road tile, rather than a field variant. One wouldn't expect these drug dealers to have done so much damage with pistols and other firearms as to completely remove all asphalt terrain from an area. 

### Screenshots

![durgdl](https://user-images.githubusercontent.com/86111552/129372280-1f8415d0-0dad-4ea7-ac8e-a2de3231359d.png)

### Versions and configuration

- OS: Windows 10
- Game Version: bcb8e7f
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: dda, no_npc_food, package_bionic_professions, Graphical_overmap, extra_mut_scens, crt_expansion, blazeindustries, cbm_slots

**Comment by Night-Pryanik** [comment]
This should've been fixed in #50697. Could you please update to latest experimental and check if this still an issue?

**Comment by hexagonrecursion** [comment]
I can confirm that this was fixed. a7bfe77 is affected, but 8dcc284 is not.
