### ISSUE TITLE
DinoMod: #50722 made zombified Dinos incredibly tedious to kill / too strong

### ISSUE THREAD

**Issue by Celepito** [CleverRaven/Cataclysm-DDA#50749]
# Is your feature request related to a problem? Please describe.
Okay, so in my current run I am already quite advanced before #50722 got implemented. Actually managing to kill them isnt that big a problem for my character, cause they cant even hit me. While I work on my 3rd Flail Fiend, with its 39.600 HP or 66.000 HP, it does leave me wondering how in hell is one supposed to deal with these things in any way that isnt running away. With a basic .50 cal and only Normal hits, you will need 300+ hits to kill this one, going by the lower estimate. (Depends on how  ` "proportional": { "hp": X ` is applied, either "times X" or "+( X times 10 )%", and with just the basic damage of .50 BMG M33 Ball, and fully ignoring any armour.) And overall, I am just kinda baffled at what the intended plan of action is here.

# Describe the solution you'd like
I can live with an explanation on how to deal with them, but I think either another numbers balance change is in order, or the spawn rate needs to be severely reduced. And I am not just talking on a #50746 kind of level. 

One could also implement some kind of %-based damage. That would probably fit with bleeding, I feel like.

Feel free to yell at me though, if I missed any obvious way to deal with them or if I got my math wrong somewhere.

# Describe alternatives you've considered
Asking on the discord for ways to deal with these, which promptly ended with me here.

# Additional context
My character is rather strong at this point, and I am using multiple different mods that make him even stronger, so I dont even want to know how this looks for people not using these mods. (I am talking StatsthroughSkills, Arcana, Magiclysm and a personal mod that adds some rather strong items. And the character is a post threshold mutant.)

**Comment by LyleSY** [comment]
Agreed, this seems fine for sizes in line with the base game, but gets crazy projecting out linear rules into multi-ton creatures. I'm working on a fix
