### ISSUE TITLE
check ammo inventory before using items, even if no consumed

### ISSUE THREAD

**Issue by kwl01skz** [CleverRaven/Cataclysm-DDA#50752]
### Describe the bug

Now, the game assumes that each time we use an item that can hold ammo, we consume ammo. 
This error is reflected in the following aspects:

in {Item Action Menu}(%):
Use [misc repair kit] to [chop down a tree], we consume duct tape (5).
in {Apply or use Item}(a):
Empty [misc repair kit] cannot use, although I just want to cut trees.
[Fire repair kit] the same as above.

in any where:
We cannot Apply a weapon to remove module when it is not filled with ammo.
Bow cannot be filled with ammo, so the module of bow is almost non removable.
 [compound hunting bows] cannot be active for [Looseen Limbs].

### Steps To Reproduce

Debug a [misc repair kit].
 {Item Action Menu}(%) - [misc repair kit] - [chop down a tree].
-->consume duct tape (5).
Unload the [misc repair kit].
{Apply or use Item}(a).
-->cannot use it.

Debug a [compound hunting bow].
{Apply or use Item}(a).
[compound hunting bow].
Loosen Limbs.
-->It seems to work, but this is because there is ammunition in the debugging item.
Fire.
-->Now it doesn't work, and there's no normal way to make it work.

### Expected behavior

When using multi-functional items, it is allowed not to consume ammo.

### Screenshots

Use [misc repair kit] to [chop down a tree], we consume duct tape (5).

![image](https://user-images.githubusercontent.com/1281487/129394116-91e0c4f1-0352-4a2d-a515-02bd2f5503f4.png)

in {Apply or use Item}(a):
Empty [Fire repair kit] cannot use.
![image](https://user-images.githubusercontent.com/1281487/129393956-de42c8e1-e180-4c07-a6e4-11977da5892a.png)

Remove module when it is not filled with ammo.

![image](https://user-images.githubusercontent.com/1281487/129428576-bc6a423e-7a12-4712-9bbf-98525b28cc27.png)

### Versions and configuration

- OS: [Windows 10]
- Game Version: [0.F-8bd78]
- Graphics version: [Tiles]
- Ingame language: [Chinese (Simplified)]
- Mods loaded: [dda]

### Additional context

https://github.com/CleverRaven/Cataclysm-DDA/blob/4814255da0b72a5ede1360e5058c32d5b3a22b90/src/character.cpp#L8887-L8896

https://github.com/CleverRaven/Cataclysm-DDA/blob/ecc6a8f461ac31b48221875b42fba003465af781/src/game_inventory.cpp#L1119-L1124

**Comment by chrispikula** [comment]
I'll confirm it, and I'm pretty sure that this is a long-standing bug?  It's got to be a duplicate at this point.

**Comment by kwl01skz** [comment]
Interesting. I am quite sure that the remove weapon module (especially the bow module) can work at that time.

**Comment by kwl01skz** [comment]
#50319 seems to have solved the problem

**Comment by kwl01skz** [comment]
#50319  is merged, but the problem has not been completely solved.

Now using [Fire repair kit] still needs to consume batteries,

Although no consumption (- 0) is displayed before use, it actually consumes (- 100)

**Comment by nullinsky** [comment]
Can confirm that Misc Repair kits still use duct tape on actions like plank-cutting when loaded.
