### ISSUE TITLE
Looking on photos on laptop deletes all

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#50753]
### Describe the bug

If you've got multiple photos on a laptop or e-ink pc, if you look at them, you look at all of them rather than one at a time.

### Steps To Reproduce

Scan SD cards till you get a bunch of photo's, then look at them.

### Expected behavior

Only 'using up' a single photo at a time.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: ecc6a8f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]

**Comment by Saicchi** [comment]
Can confirm on `0.F-1687-gbadd5e3393`.
It seems to be the intended behaviour to prevent the player from getting the morale bonus multiple times from looking at the same photos over and over again.

**Comment by chrispikula** [comment]
Okay, that makes sense.  Still seems to be a bit much, but at least there's a rational behind this.  Closing.
