### ISSUE TITLE
Vehicle part installation uses practical, not theoretical knowledge

### ISSUE THREAD

**Issue by KittyTac** [CleverRaven/Cataclysm-DDA#50775]
### Describe the bug

Unlike everything else, and unlike what has been stated by Kevin, there is a case where theoretical knowledge affects what you can do: vehicle modification. You can read a mechanics book to level 3 and while your skill level for the purposes of crafting will be 3, for the purposes of part installation it will be 2. This can bottleneck the player at higher skill levels.

### Steps To Reproduce

1. Spawn in a mechanics book,
2. Read it.
3. Look at the crafting menu, see you are able to craft things that require mech skill because it uses theoretical.
4. Try to install a part that requires skill over 0, see that you can't.

### Expected behavior

The skill requirements are consistent with this:
![image](https://user-images.githubusercontent.com/52408044/129446422-37493e25-255a-4414-adaa-a076b2ed0562.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 28bf497 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Kittymod [kittymod],
    Tankmod: Revived [Tankmod_Revived],
    Tankmod: Revived - UndeadPeople Tileset [Tankmod_RevivedUDP],
    No Fungal Monsters [No_Fungi]
]

**Comment by actual-nh** [comment]
Ping: @I-am-Erk?

**Comment by DalenTalas** [comment]
Same with camp construction.

**Comment by Metallumere** [comment]
Would fixing this be as simple as changing this line?
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/veh_interact.cpp#L320

player_character.get_skill_level --> player_character.get_knowledge_level

**Comment by I-am-Erk** [comment]
It's probably roughly that simple. I tried to track them all down but there are many calls to skill level.

**Comment by hexagonrecursion** [comment]
Confirmed: at mechanics skill 0 and mechanics knowledge 1 I could not remove a seat belt

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: f50b6be [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]
