### ISSUE TITLE
Compile warning with SDL 2.0.16

### ISSUE THREAD

**Issue by BrettDong** [CleverRaven/Cataclysm-DDA#50771]
### Describe the bug

Commit https://github.com/libsdl-org/SDL/commit/c8b4edf3d0b8903cabf8ae1bc71c310d880160e1 (https://github.com/libsdl-org/SDL/pull/4552) in upstream SDL2 causes a compile warning in our build process:

```
In file included from src/debug.cpp:80:
In file included from /opt/homebrew/include/SDL2/SDL.h:41:
/opt/homebrew/include/SDL2/SDL_events.h:640:65: error: use of old-style cast [-Werror,-Wold-style-cast]
SDL_COMPILE_TIME_ASSERT(SDL_Event, sizeof(SDL_Event) == sizeof(((SDL_Event *)NULL)->padding));
                                                                ^            ~~~~
/opt/homebrew/include/SDL2/SDL_stdinc.h:347:54: note: expanded from macro 'SDL_COMPILE_TIME_ASSERT'
       typedef int SDL_compile_time_assert_ ## name[(x) * 2 - 1]
                                                     ^
1 error generated.
make: *** [obj/tiles/debug.o] Error 1
make: *** Waiting for unfinished jobs....
```

### Steps To Reproduce

Upgrade SDL2 library to 2.0.16 and `make TILES=1 RELEASE=1`.

### Expected behavior

Expect our code compiles.

### Versions and configuration

- OS: macOS 11.5.1
- Game Version: ecc6a8f461ac31b48221875b42fba003465af781
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: DDA
- Compiler: AppleClang 12.0.5
- Package Manager: Homebrew

### Additional context

Potential solutions:
* Applying the following patch suppresses the warning:
```diff
diff --git a/src/crash.cpp b/src/crash.cpp
index 55a79f2143..09e757fa6c 100644
--- a/src/crash.cpp
+++ b/src/crash.cpp
@@ -18,7 +18,10 @@
 #   if defined(_MSC_VER) && defined(USE_VCPKG)
 #       include <SDL2/SDL.h>
 #   else
+#pragma GCC diagnostic push
+#pragma GCC diagnostic ignored "-Wold-style-cast"
 #       include <SDL.h>
+#pragma GCC diagnostic pop
 #   endif
 #endif
 
diff --git a/src/debug.cpp b/src/debug.cpp
index cb572723c6..abf810f736 100644
--- a/src/debug.cpp
+++ b/src/debug.cpp
@@ -77,7 +77,10 @@
 #   if defined(_MSC_VER) && defined(USE_VCPKG)
 #       include <SDL2/SDL.h>
 #   else
+#pragma GCC diagnostic push
+#pragma GCC diagnostic ignored "-Wold-style-cast"
 #       include <SDL.h>
+#pragma GCC diagnostic pop
 #   endif
 #endif // TILES
 
diff --git a/src/loading_ui.cpp b/src/loading_ui.cpp
index b1eae6eccd..1037f712e1 100644
--- a/src/loading_ui.cpp
+++ b/src/loading_ui.cpp
@@ -15,7 +15,10 @@
 #   if defined(_MSC_VER) && defined(USE_VCPKG)
 #       include <SDL2/SDL.h>
 #   else
+#pragma GCC diagnostic push
+#pragma GCC diagnostic ignored "-Wold-style-cast"
 #       include <SDL.h>
+#pragma GCC diagnostic pop
 #   endif
 #endif // TILES
 
diff --git a/src/player_hardcoded_effects.cpp b/src/player_hardcoded_effects.cpp
index 74503e1e5b..85ba55d2f0 100644
--- a/src/player_hardcoded_effects.cpp
+++ b/src/player_hardcoded_effects.cpp
@@ -42,7 +42,10 @@
 #   if defined(_MSC_VER) && defined(USE_VCPKG)
 #       include <SDL2/SDL.h>
 #   else
+#pragma GCC diagnostic push
+#pragma GCC diagnostic ignored "-Wold-style-cast"
 #       include <SDL.h>
+#pragma GCC diagnostic pop
 #   endif
 #endif // TILES
 
diff --git a/src/sdl_wrappers.h b/src/sdl_wrappers.h
index b1f82bed87..f1486c31e1 100644
--- a/src/sdl_wrappers.h
+++ b/src/sdl_wrappers.h
@@ -8,9 +8,12 @@
 #   include <SDL2/SDL_image.h>
 #   include <SDL2/SDL_ttf.h>
 #else
+#pragma GCC diagnostic push
+#pragma GCC diagnostic ignored "-Wold-style-cast"
 #   include <SDL.h>
 #   include <SDL_image.h>
 #   include <SDL_ttf.h>
+#pragma GCC diagnostic pop
 #endif
 // IWYU pragma: end_exports
 
```

* Submit a patch to upstream to fix the compile warning.

**Comment by BrettDong** [comment]
Consequently Mac build workflows will fail because Homebrew package manager just updated SDL to 2.0.16.

**Comment by jbytheway** [comment]
Ideally, the SDL headers should be treated as system headers, which would cause warnings in them to be suppressed.

This can be done by using `-isystem` rather than `-I` on the command line.

I guess that might be tricky to achieve if we're getting our include dirs via pkg-config.

**Comment by actual-nh** [comment]
> I guess that might be tricky to achieve if we're getting our include dirs via pkg-config.

Provided pkg-config isn't including CDDA internal headers in its listing of include directories, I'm not sure why.

**Comment by kevingranade** [comment]
Depending on availability of the flag we might be able to grab the output of `pkg-config --cflags-only-I sdl2` and do a replacement of -I, which is gross and error prone, but it might be better than marking up a bunch of code.

**Comment by kevingranade** [comment]
Though on second look getting it right across all the places that SDL headers get referenced might be messier than annotating the code, IDK about cmake, but in Makefile it's pretty gross.

**Comment by jbytheway** [comment]
If we're going to go with the suppressions approach, it might be worth making all the other `cpp` files include their SDL headers through `sdl_wrappers.h` (or maybe a new header that just includes `SDL.h`) so the nastiness is contained.

**Comment by kevingranade** [comment]
Yea that was crossing my mind too, need to see if that messes anything up.

**Comment by kevingranade** [comment]
It looks like the only reason to keep them separate is that sdl_wrappers.h pulls in sdl_image.h and sdl_ttf.h in addition to SDL.h
That's not super compelling, so I think I'll inline them and see if it breaks anything at least.
