### ISSUE TITLE
e or E doesn't 'examine' on d (multidrop) screen

### ISSUE THREAD

**Issue by zarkone** [CleverRaven/Cataclysm-DDA#50774]
### Describe the bug

e or E doesn't 'examine' on d (drop) screen. Even though `?` help legend shows `e` and `E` as an option to examine. 

### Steps To Reproduce

1. hit `d` to open multidrop menu
2. hit `e` or `E` on any item

### Expected behavior

Expected examine window to be opened, like on inventory screen

### Screenshots

![1628939561-14-08-21_13:12:41](https://user-images.githubusercontent.com/1899654/129444508-e0b7cdd3-fea9-4f95-b29c-1b8400661525.png)

### Versions and configuration

- OS: Nixos pre21.11
- Game Version: 0.F-5b0c218 https://github.com/CleverRaven/Cataclysm-DDA/commit/5b0c21832ab74c439dd1e66897d80767e28c0ecb
- Graphics version: Terminal
- Ingame language: English
- Mods loaded: dda, i.e. default

**Comment by Svatopluk1** [comment]
Experiencing the same bug.

There seems to be a more general issue with the keybindings in the drop menu: for me, the ? help legend shows ". or 5" to "mark/unmark selected item" (the default I think), but only "." works; "5" does not. Clearing and then re-adding "5" to "mark/unmark selected item" does not help either ("5" is recognised as a key in the legend menu, but has no effect in the drop menu).

**Comment by Beetlecat** [comment]
Possibly un/related; Do you use numpad arrow keys? Do these function in the multidrop screen either? I'm unable to navigate or drop using movement arrows or center '5' key.

**Comment by Saicchi** [comment]
Can confirm on latest experimental.
