### ISSUE TITLE
Never gain any progress on crafting items 

### ISSUE THREAD

**Issue by Menschheit** [CleverRaven/Cataclysm-DDA#50787]
### Describe the bug

With the new practice/knowledge system the only reliable way to gain practice level is to craft things( train first aid by using bandages? Or practice computer by hacking terminals? They are just punishing and provide only tiny exp).

Now the problem comes: there are no recipes using firstaid with 0 difficulty, and the player can not gain any progress crafting item with difficulty > 0 (and therefore can not gain any exp).

in `set_next_failure_point`:
`const int failure_point_delta = crafter.crafting_success_roll( get_making() ) * percent;`

in `crafter.crafting_success_roll`:
`if( secondary_difficulty > 0 ) {`
`        skill_dice = get_skill_level( making.skill_used ) * 3 + secondary_dice;`
`    } else {`
`        skill_dice = get_skill_level( making.skill_used ) * 4;`
`    }`

If I understood the codes correctly, 0 dice means the roll can only be 0 (Yeah I don't have a die!), thus the return value is 0 if the difficulty roll > 0, thus the failure delta will be always 0.

PS: Now it is really painful to practice computer and social... Or there is a way to practice skills which I don't know?

### Steps To Reproduce

1. Make a player with 0 firstaid skill.
2. Read a book boosting knowledge level.
3. The player can never gain any progress crafting items using firstaid skill.
4. The player must spam using bandage to gain firstaid exp.

### Expected behavior

The player with 0 skill should have a chance to craft items with difficulty > 0. 

### Versions and configuration

Current Master e816cb754606b874fbfc11735a7779e36851746c, vanilla game no mods.

**Comment by Saicchi** [comment]
Applying makeshift bandages and other health items gives health care experience, after applying 6~12 of them you should get a level in health care.

**Comment by Scorch-Mechanic** [comment]
Krytor#6219 and Wyrdean#7746 on the dev discord asked for help with similar problems regarding crafting a makeshift welder and pipe cleaners, respectively. 

I just replicated this bug with pipecleaners (mechanics 1) and makeshift stethoscopes (fabrication 1). I encountered a similar problem myself trying to make superglue on my current active play character as well. There's simply nothing like blowing through 999 duct tape without seeing even 2% progress.

Save file attached, my test character is the one clearly named as such.
[manual_backup3.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7025212/manual_backup3.zip)


- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 1f0d81e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    No Fungal Monsters [No_Fungi],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

**Comment by eltank** [comment]
I don't think that failing to craft a recipe that requires a skill above your current practical level is a bug. You need to increase your practical level first.
The best way to do that is through Practice Recipes (#51007).
If the skill you want to raise doesn't have any practice recipes you can either write a JSON PR like #51518 or make some suggestions by opening a new Issue.

**Comment by anothersimulacrum** [comment]
I think the scenario outlined by scorch-mechanic is erroneous enough to be a bug.

**Comment by eltank** [comment]
Ok, I loaded the save and it does seem odd that crafting always fails at 0%. I would expect the craft to be able to make some non-zero progress even if you are 1 skill level below the recipe difficulty. Let me poke around a bit and see why that's happening.

**Comment by eltank** [comment]
Ah, this is simply because of how the crafting formula works. You roll a number of dice computed from your skill level, with a number of sides computed from your INT, against a recipe dice roll which uses a number of 8-sided dice based on recipe difficulty.
0 practical skill means you roll 0 dice, which results in immediate failure. This only works when crafting 0-difficulty recipes because the opposing roll is also 0 dice.

So in order to fix this bug we should either change the crafting success formula or change the crafting UI to not allow crafting when you have no chance to succeed.

BTW, if you have an NPC helper that does give you some skill dice (equivalent to half of a skill point), which will allow you to succeed at crafting a level 1 recipe with 0 skill.
![image](https://user-images.githubusercontent.com/8000047/133011805-5192e2af-2b86-40ee-85b4-28d547c74142.png)

**Comment by eltank** [comment]
Another thing we could do, which would be helpful beyond this particular issue, is to display the estimated failure chance (i.e. the chance of failing at least once before completing the craft) in the crafting UI, like we do for CBM installation. In this case it would be 100%, which would tip you off that it's not a good idea to attempt it.

**Comment by captainego** [comment]
Another option is to switch from using 0 indexed skill (and difficulty) levels to using 1 indexed skill (and difficulty) levels.

This change would allow a character with skill level 0 to craft a skill level 1 recipe the same chance that a character with skill level 1 has to craft a skill level 2 recipe before this change.

This does change the dice ratio as you go up levels (as it did previously, just 1 step earlier) as shown in the tables below:

Before |   |   |   |  
-- | -- | -- | -- | --
Skill Level | Recipe Level | Skill Based Dice | Difficulty Base Dice | Dice Ratio
0 | 0 | 0 | 0 | N/A
0 | 1 | 0 | 4 | 0
0 | 2 | 0 | 8 | 0
1 | 1 | 4 | 4 | 1
1 | 2 | 4 | 8 | 0.5
1 | 3 | 4 | 12 | 0.333333
2 | 2 | 8 | 8 | 1
2 | 3 | 8 | 12 | 0.666667
2 | 4 | 8 | 16 | 0.5

After |   |   |   |  
-- | -- | -- | -- | --
Skill Level | Recipe Level | Skill Based Dice | Difficulty Base Dice | Dice Ratio
0 | 0 | 4 | 4 | 1
0 | 1 | 4 | 8 | 0.5
0 | 2 | 4 | 12 | 0.333333
1 | 1 | 8 | 8 | 1
1 | 2 | 8 | 12 | 0.666667
1 | 3 | 8 | 16 | 0.5
2 | 2 | 12 | 12 | 1
2 | 3 | 12 | 16 | 0.75
2 | 4 | 12 | 20 | 0.6
