### ISSUE TITLE
Sheltered Survivor lacks inventory space for starter items.

### ISSUE THREAD

**Issue by TealcOneill** [CleverRaven/Cataclysm-DDA#50799]
### Describe the bug

The sheltered survivor profession currently always generates the below bug report when created. This is due to a lack of volume in any of their clothing for the bottle. I would suggest either a small backpack or the fanny pack be added to the profession so that this bug doesn't happen.

### Steps To Reproduce

Create a player using the Sheltered scenario and the Sheltered Survivor profession.

### Expected behavior

I expect that a profession doesn't lose some of their starting items.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

### Additional context

 DEBUG    : ERROR: Could not put plastic bottle (sealed) > clean water (bottle_plastic) into inventory.  Check if the profession (sheltered_survivor) has enough space.

 FUNCTION : Character::migrate_items_to_storage(bool)::<lambda(const item*, item*)>
 FILE     : src/character.cpp
 LINE     : 10949

**Comment by hexagonrecursion** [comment]
Could not reproduce
- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 17b9ea1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by TealcOneill** [comment]
#48420 fixes this issue but it has not yet been merged with the stable branch.
