### ISSUE TITLE
Damaged book scanned into e-ink tablet PC shows as damaged in stored book menu.

### ISSUE THREAD

**Issue by Scorch-Mechanic** [CleverRaven/Cataclysm-DDA#50798]
### Describe the bug

As title. A book I had accidentally damaged (hit a zombie with it) that I later scanned into my e-ink tablet PC shows visually as damaged in the "read a stored book" menu of the e-ink tablet PC.

### Steps To Reproduce

1. Acquire a damaged book.
2. Scan it into the memory of an e-ink tablet PC
3. Activate the device and choose the "read a stored book" menu item.
4. See that the stored book shows up just as damaged as the book you scanned.

### Expected behavior

I expect that there would be no durability bar in the stored book menu. Because the contents of the book have been digitally scanned (OCR'd?) and stored. They should have no health, or be pristine. Or similar.

### Screenshots

Test character, with two damaged books in inventory:
![image](https://user-images.githubusercontent.com/5760760/129465790-6a00ab6f-8a20-469b-a50f-616d3f7f86e3.png)

----

And inside the e-ink tablet PC memory.
![image](https://user-images.githubusercontent.com/5760760/129465805-06803578-894d-4f30-b001-ea30c5859739.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: f56f7c2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    No Fungal Monsters [No_Fungi],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

**Comment by actual-nh** [comment]
If it were damaged after you scanned it, then certainly. Before? You'll have problems with the text.

**Comment by Scorch-Mechanic** [comment]
> If it were damaged after you scanned it, then certainly. Before? You'll have problems with the text.

This is a game mechanic? I've never heard of this before. If this is so, then I suppose this issue can be closed as working as intended. 

Either way, damaging the scanned book does not affect the "durability" of the scanned book (I just tested it).

**Comment by Saicchi** [comment]
I didn't know damaged books affected reading either so I never tested that...

**Comment by actual-nh** [comment]
Correction (sorry!): You _should_ have problems with the text; whether or not it actually happens I don't know.

**Comment by Saicchi** [comment]
Anyway whether it happens or not, if you had trouble reading the damage book before, it won't be any better after you digitalize it into the eBook. If reading a damage book does have a penalty then an option to replace it with a book in better condition should be added.

**Comment by Scorch-Mechanic** [comment]
Setting aside whether or not damaged books are supposed to be harder to use and may or may not actually work that way, it appears that this is not a bug and is working as intended. Closing.
