### ISSUE TITLE
Dino Mod - Have eggs percholate into other egg recipes

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#50795]
# Is your feature request related to a problem? Please describe.
It'd be nice if dino eggs could be used in recipes like powdered eggs.  

# Describe the solution you'd like
A way to extend recipe ingredient lists.  If there's two mods that add creatures with, say, eggs, have a way that powdered eggs recipes could be extended with both without over-writing each-other.

I tried to figure out how to do this myself, but couldn't figure it out.  

Maybe an [egg] category like there is a [water] category?

# Describe alternatives you've considered
Dino-mod replicates the powdered egg recipe and funnels things in that way.

# Additional context
N/A

**Comment by LyleSY** [comment]
I believe this was fixed by #42583
