### ISSUE TITLE
Broken Pockets

### ISSUE THREAD

**Issue by RockNShoulders** [CleverRaven/Cataclysm-DDA#50802]
### Describe the bug

When placing items into pockets/inventory, the game does not properly determine if the items can actually go in the pocket. It will refuse to auto-place items into empty, non-whitelisted pockets unless manually (i)nserted. It will also refuse to place items into any pocket when one pocket is full. Eventually it will run out of space and will not have "room" for more items, even if pockets are empty and available.

### Steps To Reproduce

1. Get a survivor belt and drop everything else.
2. Whitelist a few items and pick them at the same time. Preferably more than 3.
3. The game will have you wield at least one of them.
4. Manually insert it into the belt.
5. Keep inserting items while checking the (v) menu for whitelist/blacklist and where each item is in the pockets.

### Expected behavior

Able to insert items as normal until all pockets are full. Respects the whitelist.

### Screenshots

![Untitled](https://user-images.githubusercontent.com/88957626/129467790-7fedffeb-b5c1-4a21-80c6-5e2704ccfbfd.jpg)

### Versions and configuration

- OS: Win 10
- Game Version: 2021-08-14-2036
- Graphics version: Tiles
- Ingame language: English

### Additional context

I've made another report about pockets here: https://github.com/CleverRaven/Cataclysm-DDA/issues/50801

**Comment by Svatopluk1** [comment]
> It will also refuse to place items into any pocket when one pocket is full. Eventually it will run out of space and will not have "room" for more items, even if pockets are empty and available.

Are you absolutely sure that the items you are trying to pick up match the restrictions of the pocket? Note that some pockets have a *minimum item volume* defined, some have *maximum item length*, some accept only certain types of items, etc. And so even an empty pocket may not be able to hold the item you are trying to pick up.

The reason I ask is because

>2. Whitelist a few items and pick them at the same time.

when trying to reproduce it very much matters what items you are trying to fit into what pockets.

**Comment by RockNShoulders** [comment]
I've posted a video of me reproducing the problem in the other ticket. https://github.com/CleverRaven/Cataclysm-DDA/issues/50801

Here it is again: https://youtu.be/2mn6lPshbiA

Summary: Items picked up that satisfy the pocket requirements are not automatically placed regardless of priority of the pocket and have to be manually inserted.

**Comment by RockNShoulders** [comment]
Based on comments from the other bug report, this is actually working as intended. The issue was coming from the items not fitting into a sheath or being clip-on.
