### ISSUE TITLE
Character does not exit prone mode after triggering insomnia

### ISSUE THREAD

**Issue by DalenTalas** [CleverRaven/Cataclysm-DDA#50809]
### Describe the bug

Noticed greatly reduced character speed after insomnia triggers. Noticed log message for character going prone prior to falling asleep. Noticed no such message on resumption of activities. Fixable by switching movement mode back to walking.

No such effect seems to occur if the "Keep trying to fall asleep?" prompt does not trigger.

Note, this may be restricted to sleeping in a vehicle bed.

### Steps To Reproduce

1. Create an Insomniac character.
2. Attempt sleeping until "Keep trying to fall asleep?" prompt triggers.
3. "Stop trying to fall asleep and get up" and observe the movement speed. Switch back to walking.
4. Repeat step 2 until the character falls asleep. The "Keep trying..." prompt MUST trigger, and be dismissed in  favor of keeping trying to sleep. Observe movement speed on waking up.

### Expected behavior

While remaining prone after waking up / tossing and turning is realistic, the action prompt "...and get up" suggests the character has returned to vertical.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 7835cc2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations]
]

**Comment by StStep** [comment]
Yeah, I've seen this too when waking up before my alarm clock. I penned the PR that fixed some of the scenarios such as manually interrupting sleep, sleeping properly, and selection the prompt to cancel,  but something must have fell through.

**Comment by DalenTalas** [comment]
Looks like this issue was resolved in one of the latest versions.
