### ISSUE TITLE
Numpad navigation in inventory screens is ignored

### ISSUE THREAD

**Issue by RoyBerube** [CleverRaven/Cataclysm-DDA#50819]
### Describe the bug

Tested in Windows. Other OS may behave differetly.

Numpad navigation in inventory screens is not handled correctly, even with the interface option for "Use key code input mode" set to keycode.

Numpad keys return same number code as keyboard keys.

### Steps To Reproduce

1. Shift-d to open multidrop screen.
2. Attempt to navigate the menus with numpad.
3. Numpad inputs are treated the same as keyboard number keys. No navigation is possible.

### Expected behavior

Numpad navigation should be possible in inventory screens.

I did find a way to get it working but am not confident that it is a correct fix:

In inventory_selector::inventory_selector()
change    , ctxt( "INVENTORY", keyboard_mode::keychar ) to  , ctxt( "INVENTORY", keyboard_mode::keycode )
https://github.com/RoyBerube/Cataclysm-DDA/blob/ae7e5b9d962ba9d6e7926e6d8f509ac44d198b5d/src/inventory_ui.cpp#L1980
and  set "Use key code input mode" to keycode.

For reference:
https://wiki.libsdl.org/SDLKeycodeLookup

### Versions and configuration

- OS: [Windows 10]
- Game Version: [0.F latest experimental]
- Graphics version: [Tiles and Terminal]
- Ingame language: [English]
- Mods loaded: [dda]

**Comment by anothersimulacrum** [comment]
It might because it is overlapping with selecting a number of items (e.g 5 out of 7 rags).

**Comment by hexagonrecursion** [comment]
Confirmed
- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 17b9ea1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]
