### ISSUE TITLE
Eating food when many options are available is very slow

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#50813]
### Describe the bug

When you open the eating menu, such as when you chose to consume only drinks or only food from a large selection, a large amount of lag is experienced when you have many items available for consumption.

The work around is to pick up the food, move out of the range of fridges or freezers on your basemobile, and then consume the food.  This happens, real time, much quicker.

This issue is fairly old as well, at least from Epsilon.  I remember thinking about it when #48223 came up, but while also being lag, it doesn't appear to be the same cause.

### Steps To Reproduce

Have your entire food stockpile around you, have over ten pages of food available to be chosen from.  
Eat one.  
Watch as you see 5%, 11%, 16% ... progress for eating an item that takes 30 seconds to eat.
~~Wonder if you can eat more slowly than real-time.~~

### Expected behavior

It to be near as quick as when you eat it by itself, save for a screen redraw near the end.

### Versions and configuration

-----------------------------------------
11:01:54.864 : Starting log.
11:01:54.864 INFO : Cataclysm DDA version ecc6a8f
11:01:54.872 INFO : [main] C locale set to C
11:01:54.872 INFO : [main] C++ locale set to C
11:01:54.872 INFO : SDL version used during compile is 2.0.14
11:01:54.872 INFO : SDL version used during linking and in runtime is 2.0.14
11:01:55.183 INFO : Number of render drivers on your system: 5
11:01:55.183 INFO : Render driver: 0/direct3d
11:01:55.183 INFO : Render driver: 1/direct3d11
11:01:55.183 INFO : Render driver: 2/opengl
11:01:55.183 INFO : Render driver: 3/opengles2
11:01:55.183 INFO : Render driver: 4/software
11:01:55.188 INFO : [options] C locale set to C
11:01:55.188 INFO : [options] C++ locale set to C
11:01:55.188 INFO : Setting language to: 'en'
11:01:55.188 INFO : Language is set to: 'en'
11:01:55.188 INFO : [translations] C locale set to English_Canada.1252
11:01:55.188 INFO : [translations] C++ locale set to C
11:01:55.449 INFO : Active renderer: 0/direct3d
11:01:55.813 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
11:01:56.055 INFO : Setting language to: 'en'
11:01:56.055 INFO : Language is set to: 'en'
11:01:56.055 INFO : [translations] C locale set to English_Canada.1252
11:01:56.055 INFO : [translations] C++ locale set to C
Base game, no mods.

### Additional context

I _think_ what's happening is that it's either re-drawing, or re-calculating the 'time left' of all of the foods you had in that menu.  Add in fridge and freezer math, as well as having some items in packaging, ie, pockets, and it becomes quite slow.

**Comment by mqrause** [comment]
Are there NPCs and/or zones nearby?

**Comment by anothersimulacrum** [comment]
Would it be possible for you to provide a save? It would ease profiling.

**Comment by chrispikula** [comment]
> Are there NPCs and/or zones nearby?
There were none nearby, and several zones were adjacent.  None are in the attached save.

Here's a mockup I made.  0.00 spawn, 10.0 item spawn.
Let's consider yogurt, as it has a consume time of 50 seconds in game.

Eating one of the yogurts at the tile you start on takes ~3 seconds.  
Eating one of the yogurts after picking one up and moving 4 tiles north takes a fraction of a second.

[Avernum - Copy (2)_copy.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6988639/Avernum.-.Copy.2._copy.zip)

**Comment by VincentRoyceMorgan** [comment]
Probably because the game has to refresh the entire list, all pages included, every single time you consume an item. On a slower machine it's not much more than just a performance problem. Although I have noticed that in recent versions it takes way less items in a list to start experiencing slowdowns.
If you're like me and you have about 10 pages of food/drinks/drugs each placed on adjacent tiles and then open the general consume menu is an easy way to slow down lunch to a crawl. Using the "Consume Item Menu" keybind alleviates things a little bit, but nothing beats just doing the described workaround.
Taking things out of their packaging or combining liquids in as little containers as possible to reduce the amount of entries  also helps. (Having 1 entry of 10 chocolate bars instead of 10 entries of 1 chocolate bar just because they're all in separate paper wrappers). The recent changes to MREs make them very prone to slowing things down, both in the consume menu and the multidrop menu.

**Comment by mqrause** [comment]
Yeah, this is the delay from (re-)building the consume menu. Seems pretty expensive to reset filter and cursor position.

![grafik](https://user-images.githubusercontent.com/38702195/129491436-18fee854-2f71-47eb-8f5b-017dd0f8c9d8.png)

**Comment by chrispikula** [comment]
Now, that makes sense, but why would I see the / - / | \ - / hourglass spin at the top when I eat near my stockpile, and not when I don't?
Is it rebuilding it each each 'tick'?  
Why not just rebuild it once at the very end of consumption?

**Comment by mqrause** [comment]
No, it's just being rebuilt once at the end. I didn't see any noticeable slowdown during the eating itself, considering it took only ~1s on my system and 75% of that is rebuilding the menu. It does show the last tick of the spinning hourglass during that time, which might increase the impression of that being slow?

**Comment by mqrause** [comment]
Related to #35292 btw. Not exactly the same, since this one here is about reopening the menu after an activity finished, but a fix for #35292 maybe also mostly fixes this.
