### ISSUE TITLE
"copy-from" bug for activity levels in recipes contained within subdirectories of json\recipes

### ISSUE THREAD

**Issue by Pseudogeist** [CleverRaven/Cataclysm-DDA#50827]
### Describe the bug

While looking through the JSON with an eye to setting all knitting activity levels to NO_EXERCISE I discovered that there was something amiss. "pair of XL wool gloves" copies from "pair of wool gloves" but doesn't copy the activity level and instead sets it to 'Moderate'.
Edit: Only applies to recipes located in sub-directories of recipes. Line 215 in recipe.cpp is setting "MODERATE_EXERCISE" as a fallback. I'm yet to test mod recipes, perhaps there's no need. Either way, I've not been able to find a cause as to why only these recipes are failing. Perhaps somebody more familiar with the code can figure it out. I'll have another look tomorrow with fresh eyes.

### Steps To Reproduce

Compare JSON entries for stated items with in-game crafting menu.

### Expected behavior

Good question. Maybe copy-from should likely copy all stated parameters as-is from the parent without any guessing or upscaling, which I suppose might be what's happening here. Possibly the default is MODERATE_EXERCISE and NO_EXERCISE isn't being retrieved. I don't know.

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 7a64f7e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by Pseudogeist** [comment]
JSON digging revealed a to-do for solar backpacks to use copy-from for their deconstruction, referencing #24702 . It seems this is still a problem as the deconstruction using copy-from is the crown_golden_survivor which doesn't return anything when deconstructed as you can see when viewing the recipe. This is a separate issue. I've checked pretty thoroughly and it seems #24702 is exclusive to deconstruction recipes while #50827 **only applies to recipes located in sub-directories of recipes**. It also goes a long way to explaining why the large water wheel is more strenuous to craft if you use power tools. Explanation: They're not meant to, it's this bug.

**Comment by RenechCDDA** [comment]
Checked the gloves, the water wheels, some other nests. Seems to be resolved as of https://github.com/CleverRaven/Cataclysm-DDA/commit/c94dc0387513d5bba49eb7d74b2b51a7a4d8c4a0
