### ISSUE TITLE
disable_activity_actor is declared in src/activity_actor.h

### ISSUE THREAD

**Issue by Saicchi** [CleverRaven/Cataclysm-DDA#50826]
### Describe the bug

`disable_activity_actor` is declared in `src/activity_actor.h` instead of `src/activity_actor_definitions.h`

### Steps To Reproduce

1. Go to https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/activity_actor.h
2. See that `disable_activity_actor` is declared there.

### Expected behavior

`disable_activity_actor` is declared in https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/activity_actor_definitions.h

### Screenshots

None

### Versions and configuration

N/A

### Additional context

Move `disable_activity_actor` to `src/activity_actor_definitions.h`, remove any headers or declarations used only for that class ( possibilly only `point.h` )  and make sure it compiles and works properly in-game.

It was declared there because #44670 was created before the move to `src/activity_actor_definitions.h` happened.

**Comment by actual-nh** [comment]
I suspect a contributing factor is that one might look at the name and think it was something acting on an activity_actor, not an activity disabling something.

**Comment by anothersimulacrum** [comment]
It is just that the PR adding the actor predates moving the actors to a new header.
