### ISSUE TITLE
Spear straps need leather to repair even when not made of leather

### ISSUE THREAD

**Issue by angryisosceles** [CleverRaven/Cataclysm-DDA#50822]
### Describe the bug

I have a spear strap that I made without using leather, but both the description and the materials tag suggest that it is made of leather. Furthermore, it requires leather to repair.

### Steps To Reproduce

- Make a spear strap without using leather
- Look at the description of the item
- Attempt to repair it

### Expected behavior

Ideally, the spear strap would count as being made out of cotton whenever it is made using only cotton. Alternately, it could be impossible to craft without leather.

### Screenshots

![spearStrap](https://user-images.githubusercontent.com/51832925/129496390-8580c53b-a323-44d5-9f5b-ed60b7c726ac.PNG)

### Versions and configuration

- OS: Windows x64
- Game Version: 9a10b0c
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: None

**Comment by hexagonrecursion** [comment]
Confirmed
- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 17b9ea1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by Night-Pryanik** [comment]
Fixed by #67371.
