### ISSUE TITLE
Small Wheels: a suggestion for improving CDDA's small vehicle mobility options

### ISSUE THREAD

**Issue by Gavinfoxx** [CleverRaven/Cataclysm-DDA#50837]
Small Wheels: a suggestion for improving CDDA's small vehicle mobility options

CDDA has an interesting, nuanced vehicle creation system that, in the small scale, has some extreme limitations. The realm of 'personal mobility devices' is quite varied, and that realm is also extremely viable for fitting the 'find/make/modify useful stuff in a post apocalyptic context' core gameplay loop.

As the game currently exists, small (one square and below) wheeled mobility options for players are limited to unicycles (and shopping carts) with the vehicle system and three types of roller skates (old school, inline, and in-shoe) in the clothing system.

Focusing on the 'skater' options, they are currently balanced by increasing your speed on roads, decreasing it off-road, not generally being usable with exotic foot mutations, and being likely to trip and fall in combat scenarios.  This is somewhat oversimplified, because what about these sorts of options:

https://www.powerslide.com/inline/off-road/
And note how they have a frame set designed for custom fabrication -- check the accessories tab!

Or how about these:

http://www.inlineskates.com/Skorpion-Multi-Terrain-Outdoor-Roller-Skates/122479P,default,pd.html
https://www.amazon.com/Skorpion-skates-Multi-Terrain-130mm-wheels/dp/B001B41TF4

Or even, for mutants with odd feet, something like these to combine with the above?

https://www.cavallo-inc.com/
and that is only one brand of that product type!

But let's back up to another issue: ‘Skater’.

The game desperately needs a wider variety of things for Skater to apply to. The game already has skateparks -- so where are the skateboards as alternative small manually powered vehicles to unicycles?

I would consider the earliest reasonable short-term implementation of a skateboard to be simply a vehicle version of both types of skates, as a thing you mount provided you aren't wearing roller blades, not a thing you wear, that intrinsically works with all foot types.  You could even have speed vs stability options that mirror the different skate options.  Of course, it would have to be something you can fall off of, both in normal exiting vehicle situations and ones analogous to the rollerskate fall triggers, maybe with Skater providing a large bonus to prevent those. It'd also make a decent melee weapon, and should be modifiable to clip onto a harness or sling or similar. Maybe even it should have mounting points so you can put a light or a large shotgun or mine device on the front if you need to clear your path?

The only mod I found which added skateboards was this ancient thing: https://discourse.cataclysmdda.org/t/skateboard/9661

Of course, this also ignores the existence of off-road and large wheel skateboards, from traditional unpowered off road skateboards to something like the bmw streetcarver, which due to being raised and the large wheels, works alright offroad.

Now, what about those two wheel standing scooters, and those very very tiny foldable commuter's bikes, of many different varieties?  While the game has foldable bikes, these are full-sized, three-squares type foldable bikes, not any of the several types that are trying to go for ‘smallest foldable commuter bike’ ranking, the type which can plausibly be strapped to you or your backpack without too much encumbrance when folded!  What about motorized (either electric or gas powered) standing scooters, skateboards, tiny foldable bikes, side-by-side-wheeled self-balancing electric standing scooters, Segways, and the many Segway ripoffs out there? Many of these work fine off-road, and several (mostly the gas powered ones that can run on ethanol) would work fine in a post apocalyptic setting. Take the Motoboard or the gas powered skateboards from SkaterX!

Essentially, you would likely need a keyword-based system, allowing you to categorize different designs by questions like:

-how much speed bonus does it give in flat terrain, if you power it?
-what is the max speed, if engine-based?
-can you combine your strength with engine assist?
-is it a thing you wear or mount?
-do you have to strap yourself into it?
-does it require you to balance?
-how unstable is it or how hard to balance?
-is it electric or gas powered?
-if powered, iis it auto stabilizing?
-do you sit or stand on it?
-does it need you to stay in motion for stability?
-does it have handlebars?
-does it have breaks or require skill to break?
-does it have a seat?
-how many wheels does it have?
-does it also give a speed bonus offroad, and if so, how much?
-does it have a legally mandated speed limiter which you can remove if you know how?
-is it loud or silent when on?
-does it fold up, and into what size device for carrying?
-does it have a strap for your foot, preventing you from kicking with that foot while mounted?
-Can you use it with oddly shaped feet, as is?
-Can you modify it to work with your oddly shaped feet?
-Can you do stunts and jumps with it (ie, parkour type tricks), especially without needing a ramp to get some air?
-Can you fight while mounted on it, and if so, what penalties does it give you, either in melee, dodging, or as a firing platform?
-Can you crouch on it?
-Can you safely take a foot or hand (or two) off of it?
-Is it worth hitching a small two wheel cargo/luggage trailer to this device?
-What slots does it have for what sorts of modifications?
-Is it a thing that you walk behind or in front of to hold things, in order to steer it (red wagon, shopping cart), or can you steer it while mounted on ot and benefitting from its speed bonuses?
-How big of an engine, if any, can you modify this thing to have, and with what bonuses?

Due to all of this, I think it is reasonable that there be a personal mobility device skill that improves your capabilities with these sorts of things, and Skater should remove some of the limits of the capabilities of that skill, and maybe give morale bonuses while peacefully skating.

Next, if this is being done, I think the Wayfarer trait could do with a bit of tweaking, notably making it actually prevent you from riding in a forbidden vehicle, giving you massive morale penalties if you somehow end up in a moving vehicle via circumstance, and splitting into several traits (via add-ons) with specific restrictions:
-Worn personal vehicles only (roller-skates, snowfoot mini skis, ice skates, snowshoes, etc)
-Self-powered, non motorized vehicles only
-Only silent motors below a very small size allowed
-Unenclosed, very small (one square) vehicles only
-No vehicles or personal mobility devices at all

**Comment by Pseudogeist** [comment]
Actually, there's quite a bit of content you don't seem to be aware of: Wheelies (shoes with retractable wheels? Kids were into them a while back), wheelchairs and hand rims (muscle engine vehicle part for wheelchairs), RC car wheels (steering capable, provides enough wheels to single tiled vehicles). iirc I once made a functioning single tile sailboard, and that would have been over a year ago... It probably couldn't turn as I was using casters.  Skateboards could be done with the current flags I assume by adding a part that requires a plank or two, has [MOUNTABLE] and whatever is appropriate to make it a muscle engine / vehicle controls.

It seems a lot of these questions should really be handled by the frameworks we have in place. Some are already taken care of (e.g. [MOUNTABLE] again) or should be resolved by parts flags. I'm not sure if foot cranks are prevented by foot mutations, but if they are, then it'll be by a tag. Perhaps that's what you mean by a keyword system? Questions like "Is it wearable / mountable" and "do stand / sit" are _already_ dealt with. If it's something you wear, then it's a worn item, and wouldn't be a vehicle. If you mount it, it's probably a creature (see horses / mechsuits, also cows / dogs / etc if you're small enough) or a vehicle. If you sit on or stand on it then it's a vehicle, and the vehicle parts would cover the specifics of all that. The vehicle framework is pretty robust these days and should be capable of addressing things like "can you attach 'x' to it" based solely on what parts comprise the vehicle. 

Regarding Wayfarer: personally, I dislike the trait, and the traits system as a whole is a little dissatisfying. I suspect few people use wayfarer as it hampers hauling loot and moving to and from your base. Innawoods style players would probably find it a no-brainer. Those in the middle would be people who don't set up permanent or temporary bases I guess. I doubt variations would see much use at all and only serve as bloat, which traits really don't need.

You should take a look at the JSONs if you're interested in seeing more of this kind of content and see about implementing it yourself! I think a skateboard and associated parts should be more than doable with the current tools, and if not, then a focused feature request is likely to get you what you need to make it happen. :)

**Comment by Gavinfoxx** [comment]
I mentioned the three types of roller skates -- one of those was wheelies.

And yes I am using tag/flag/keywords as synonyms; I wasn't sure of the internally used term for the variable in the code.

**Comment by Pseudogeist** [comment]
Ah, in-shoe, right? I don't know how I didn't draw the connection, it's pretty obvious with hindsight. I do hope you'll take a look at the JSONs - they're designed to be easy to modify so they're a great way to get in to developing content. It sounds like you have a lot of great ideas and are thinking pretty deeply on them, so even if you don't have the time to spend on developing you'll at least gain a deeper understanding of how your ideas could take shape. [This guide](https://github.com/CleverRaven/Cataclysm-DDA/wiki/Guide-to-adding-new-content-to-CDDA-for-first-time-contributors) is really helpful introduction and a very quick read.

**Comment by Gavinfoxx** [comment]
Ah, I'm not a coder.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
