### ISSUE TITLE
Increase car turret magazines for semi auto weapon

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#50832]
# Problem
I want to use a semi auto weapon on my car - it has lower dps, but has way more accuracy and lesser ammo consumption for use than m240/m249, but the limitation of magazine make it enough slow to work (it requires lot of time to reload it, what can be dangerour when you are in the center of city). 50 and 100 round magasines are pretty rare and still not so good as 500 round of m240/m249
Also there exist m249s - m249 version with semi auto mode only, but its too rare to find
# Solution
My options is:
1. Add ammo belts to `item_restriction` for a few guns (i found few videos with belted ar-15 so at least for this line it must be possible).
2. Add recipe to conversate m240 and m249 to semi auto mode - i found a patent on google that describe trigger modification for m240 that allow to use it in semi auto and full auto mode without any problem. 
3. Both of them

I can make it by myself, but i wanted to ckeck is it possible to merge this to the game? And how i can make it? (as a recipe, that require special item, or it possible to make by yourself, does ammo belt on ar-15 must require something like ammo box, or which guns can be allowed to use ammo belts etc)

# Additional context
Belt fed ar-15
https://youtu.be/BFrhWFTgdsg
Patent for m240 trigger modification
https://patents.google.com/patent/US8087343B2/en

**Comment by kevingranade** [comment]
No and sort of.
Building a belt-feed mechanism for an ar-15 is well past what we expect a survivor to be able to do.
A new fire control group is a lot more reasonable, it just needs appropriate tools and proficiencies.
