### ISSUE TITLE
Possible enforced skill rust and skill level disparity.

### ISSUE THREAD

**Issue by VincentRoyceMorgan** [CleverRaven/Cataclysm-DDA#50844]
### Describe the bug

Despite having skill rust turned off, skills appear to be marked eligible for rust and do, in fact, decrease over time. At the same time, in my case specifically, skills that have been increased by reading books appear to not update properly when viewed in character statistics.

### Steps To Reproduce

1. Be on the latest versions of experimental.
2. Be on a world with skill rust disabled.
3. Wait for skills to be marked eligible for skill rust.
4. Read a book which won't prevent skills from becoming marked.
5. Book-increased skills won't update in the character stats screen.

### Expected behavior

Worlds that have skill rust turned off shouldn't enforce skill rust. Skills shouldn't be even visually marked as eligible, even if they don't decrease when skill rust is set to off.

### Screenshots

![rusty](https://user-images.githubusercontent.com/86779303/129670918-ffa3c9f8-2f80-450f-82ec-a75abc12e96a.png)
![slightlyrusty](https://user-images.githubusercontent.com/86779303/129670922-8518cc6b-ed98-4873-be44-31a0160c59bd.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 8ffaff4 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Graphical Overmap [Graphical_Overmap],
    No Fungal Monsters [No_Fungi],
    Safe Portable Autodoc [safe_portable_autodoc]
]

### Additional context

It is possible that this issue will arise only for already existing saves that have gotten updated to the new versions of experimental. If needed I could upload my save, except I'd have to trim it up first because it's jut that large.

**Comment by Xpyder** [comment]
I thought the skills not raising through reading is because reading is increasing your "theoretical" knowledge of a skill not your practical knowledge (these were recently separated in experimental but the display for them is lacking atm).

Also I'm not positive on the relationship between these, I'm guessing theoretical affects recipes known and how fast your practical experience advances?

**Comment by Xpyder** [comment]
come to think of it it's reasonable that the split might also have broken the "no skill rust" module too.  Especially if say theory doesn't rust but practical does
