### ISSUE TITLE
Size changing containers in containers can lead to error or invalid pockets

### ISSUE THREAD

**Issue by StStep** [CleverRaven/Cataclysm-DDA#50843]
### Describe the bug

Basically what was happening with #50512 but with resizing containers. I saw this when filling a condom in my inventory with water, but it probably happens with other containers that can change size. It sometimes throws an error or will just let you have a pocket with too much in it.

The error seems to occur when the newly filled condom is too big for all the combined pockets in the container. If you have spare room in other pockets it, it doesn't error out but drops on a future inventory update. Before the update occurs you can see the pocket is overfilled. So it easiest to create the error using an item with only a single pocket.

### Steps To Reproduce

1. Make a player with a condom and another container and a liquid to fill the condom with
2. Place the condom in the container and place enough other things to fill that container
3. Pour a liquid into the condom
4. Either get an error or check pocket the condom is in to see it's oversized.

### Expected behavior

I expect to be prevented from filling the condom or for the condom to be forced to be removed in the case of the error.
![too-much-milk](https://user-images.githubusercontent.com/2823857/129647630-8a5dedf6-ae20-4a65-86d3-82e14ac6a35d.PNG)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-1657-g0a85313753 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by hexagonrecursion** [comment]
Confirmed

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 17b9ea1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by Xpyder** [comment]
Not sure if related but there's also a bug where sometimes I can't insert into a stored container unless I wield it first, even if it goes back into the same pocket afterwards so there may be a bug in how it assesses available space for layered containers
