### ISSUE TITLE
Foldable furniture inside of tents

### ISSUE THREAD

**Issue by Entity-y** [CleverRaven/Cataclysm-DDA#50849]
# Is your feature request related to a problem? Please describe.
Folding tables and chairs are currently unable to be placed inside of a tent. 

Large tents are spacious and lackluster without the luxury of a table and chair.

Having a collapsible stove to cook food on and warm up next to while being protected from the elements inside of a tent would make the nomadic lifestyle much more appealing. 

# Describe the solution you'd like
•Allow folding tables and chairs to be placed inside of a tent.

•Implement a foldable stove to be used inside of a tent.

![palatka_kub_bereg_5_2048x](https://user-images.githubusercontent.com/50155659/129716271-535758f1-4314-4549-ad2a-4409ab731b14.jpg)

# Describe alternatives you've considered
Having folding tables and chairs work similar to a roll mat, which can be placed inside of a tent without issue.

**Comment by Pseudogeist** [comment]
Going to hazard a guess that this is because canvas floor isn't terrain it's furniture. *sigh* If the hobo stove can't be set up inside a tent that's not very good. You might want to spawn one and see.

**Comment by Night-Pryanik** [comment]
Duplicate of #26638, which was closed as stalled.

**Comment by chrispikula** [comment]
I think a moderate solution would be to create a new tent that has foldable terrain or a hobo stove inside it.  Craft a new tent item with a folded tent, collapsible table and hobostove.  Then on deployment/retrieval, have it lay out the items inside, and be able to be taken down like the normal tent.

**Comment by Entity-y** [comment]
> Going to hazard a guess that this is because canvas floor isn't terrain it's furniture. _sigh_ If the hobo stove can't be set up inside a tent that's not very good. You might want to spawn one and see.

That's right, furniture cannot be placed on furniture, that's the message it gives if you try.

The hobo stove uses tinder and it's only use is to cook and heat up food, doesn't compare to a collapsible wood stove which could emit real heat.

**Comment by Entity-y** [comment]
> I think a moderate solution would be to create a new tent that has foldable terrain or a hobo stove inside it. Craft a new tent item with a folded tent, collapsible table and hobostove. Then on deployment/retrieval, have it lay out the items inside, and be able to be taken down like the normal tent.

It wouldn't make much sense to have a rolled up tent with a table, chair, and stove packed up into it, the volumes would be all wrong. A better solution would be to turn the string of code that allows the roll mat to be placed into a FLAG to be applied to other furniture.

**Comment by chrispikula** [comment]
Eh, I was thinking of it being a tent-kit, maybe in a box or somesuch.  Not unreasonable for a tent that large.

**Comment by Entity-y** [comment]
One alternative solution that might work would be to implement a new tent that doesn't have a canvas floor, this would allow for furniture placement.

**Comment by Pseudogeist** [comment]
I think the best solution would be to have more furniture layers, in this case a floor layer. This would resolve all the carpet issues, and perhaps could be used for roof tiles too. I think we'd have the tools to end all of the utter nonsense surrounding roofing at least. Of course, this will add another layer of complexity to JSONs and require another pass over all existing terrains. This is very non-trivial, though, and shouldn't be knocked out without a plan... As a stopgap I like @Entity-y 's solution the best. I'll take a look.

**Comment by MomoiroShinobinomono** [comment]
Want to have a good chuckle?
You can cut grass through the tent floor tiles.

**Comment by MomoiroShinobinomono** [comment]
In all seriuosness tho, my take on that problem is it would be nice to make tents stay unfolded even when their individual parts are damaged or missing.
As, you know, slighly puching tent floor shouldn't collapse the whole structure and fold it automatically like it does currently.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
