### ISSUE TITLE
Select option in Multidrop behavior inconsistent when applied to mouse vs keyboard

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#50859]
### Describe the bug

Select option in multidrop selects items when applied to mouse, but does nothing when applied to keyboard

This functionality seems to be moved into "Mark selected item" but I'm unclear on what the value is in having a separate "Select" option that only works for the mouse (but allows keyboard bindings that do nothing.  Or more accurately I suspect this was overlooked and they should be merged (though I'm not sure where to do this in the code)

Possibly originated in #50214 (and subsequently related to #50840)

### Steps To Reproduce

open the (d)rop menu
go to keybindings
assign a keyboard shortcut to Select
note that it seems to do nothing

### Expected behavior

I expected:
the keybind to have parity between mouse and keyboard

possibly either by merging it into the new option, disabling the ability to bind keyboard to it, or removing it from this menu if it's a global shortcut, or renaming it to make it clear it only works for cursor selections

### Screenshots

![image](https://user-images.githubusercontent.com/12039454/129818960-be9ee173-dda7-42e9-bb7c-21f4fedfe33a.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: bea0650 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills]
]

**Comment by Xpyder** [comment]
also it would be nice to be able to restore all keybinds (for a single window) to current defaults

**Comment by ZhilkinSerg** [comment]
Inventory menu is used not only for multidrop context, but for regular inventory as well - `SELECT` command there (assigned to left mouse button) is used, well, for selecting inventory entries and opening corresponding item context menu. This is a behavior from rather long time before linked tickets.

**Comment by Qrox** [comment]
It's probably because the input code only returns the mouse position when a mouse button is clicked.
