### ISSUE TITLE
Turned slightly left while 140 km/h, car crashed into trees immediately.

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#50850]
### Describe the bug

Not quite a bug, but worth discussion. Probably will end with simple "closed".

I'm driving my precious car down a road 140 km/h. I see a car, turn the steering wheel slightly (I think) to find myself in a tree.

### Steps To Reproduce

1. Drive 140 km/h on road.
2. Turn to a side slightly.
3. Observe that you went off the road.

### Expected behavior

Can dodge a single car that's far away on a straight road even when driving 140 km/h, like you would in real life.

### Screenshots

![Aftermath](https://user-images.githubusercontent.com/13402666/129763708-562f3d23-c734-4b00-a27b-e0ebc57de979.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 31ef3ba [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by Brambor** [comment]
Btw, I think the car rotated while crashing into trees & that's why the backlights are to the left on the picture?

**Comment by ZhilkinSerg** [comment]
What was your skill level?

**Comment by Brambor** [comment]
> What was your skill level?

It was 2 (51%). Also, my speed was at 84 Due to pain and heat. Full stats after the crash (from another bug report):
![image](https://user-images.githubusercontent.com/13402666/129766933-a1270d5e-d804-4128-b205-55fc05a97734.png)

Since with health care 1, you apply an average bandage to average quality. I would think that an avatar who drove some car for a while (driving skill 2) would know not to crash into a tree when steering on a straight road.

I'm not necessarily saying the reflexes were slow or anything (not enough moves), maybe the car should have been seen sooner. Maybe an option for slight steering is missing.

Would an avatar with average driving skill be able to drive a 500 km/h car on a big circle? Because real people can do that and they don't need high driving skills.

**Comment by Zireael07** [comment]
At low skill levels, you have a lot of skids. That's likely what sent you into the tree

**Comment by Brambor** [comment]
> At low skill levels, you have a lot of skids. That's likely what sent you into the tree

OK, but it shouldn't happen, it wouldn't happen in reality... Do skids show up in a log?

**Comment by Malkeus** [comment]
I think it used too, can't recall seeing that message recently. I would have written off your scenario as a consequence of driving to fast with skill to low. The chance of losing control goes up with speed and is most likely to hit after making a steering adjustment, in my experience. Keep it below 80 til you get up to 4 or so.

**Comment by Maleclypse** [comment]
> > At low skill levels, you have a lot of skids. That's likely what sent you into the tree
> 
> OK, but it shouldn't happen since it wouldn't happen in reality... Do skids show up in a log?

At a low level it's the equivalent of you being a teenager who over corrects their car and sends it screaming into a ditch, flipping it multiple times.

**Comment by Pseudogeist** [comment]
What classifies as 'low skill' is really pretty arbitrary. The underlying systems aren't quite there yet, but yes, a skill of 2 _sounds_ like your average driver when compared to other skills. However, most drivers wouldn't approach a car inert in the middle of the road at 140km/h, perhaps? The counterpoint being that they would also see it much sooner than a player sees the obstacle. We could do with more input opportunities at higher skill levels rather than more input at opportunity points, although this will slow down RL vehicle operation time (which is one of the benefits to driving). Perhaps autodrive negates that point.

**Comment by Brambor** [comment]
> However, most drivers wouldn't approach a car inert in the middle of the road at 140km/h, perhaps? The counterpoint being that they would also see it much sooner than a player sees the obstacle.

As I said, on a straight road, you should be able to see the first obstacle (standing car) from far away. IRL drivers can see marks such as [triangles](https://www.google.com/search?q=road+triangle&tbm=isch&ved=2ahUKEwjnnty39bryAhXS6aQKHYYtDaEQ2-cCegQIABAA&oq=road+triangle&gs_lcp=CgNpbWcQAzIECAAQEzIECAAQEzIECAAQEzIECAAQEzIICAAQBxAeEBMyCAgAEAcQHhATMggIABAHEB4QEzIICAAQBxAeEBMyCAgAEAcQHhATMggIABAHEB4QEzoFCAAQgAQ6BAgAEEM6BggAEAcQHlCBN1iaQGDgQWgAcAB4AYABvQKIAeEGkgEHMi4zLjAuMZgBAKABAaoBC2d3cy13aXotaW1nwAEB&sclient=img&ei=XSsdYaf8LNLTkwWG27SICg&bih=937&biw=1920) from far away. OK it is reflective, but there is no way to get something reflective in CDDA, is there?

I get that CDDA is a game and the reality bubble is essential in making it playable in real-time though... I don't see a solution right now :/

Maybe we could do not circular but conical view for fast speeds? A nice side effect is that, isn't it how it works approaching the speed of light? Things able to affect you would be in that cone.

**Comment by Xpyder** [comment]
1. I agree that you should either be able to avoid the car or have better feedback if a skid or other pebcak error occurred so you can learn for next character
2. realistically you'd slow down to improve maneuverability when avoiding a stopped car irl (remember this is different from weaving cars going similar speeds on the freeway, this is like dodging a mattress lying in the middle of the road)
3. I too would say lvl 2 in a skill should be equivalent to someone who's been driving for a while, not a teenager who's brand new
4. in the event of a skid or some similar malfunction it would be nice if it took into account your speed and gave you a chance to react like you would in combat, as this scenario is similarly lethal.

**Comment by Xpyder** [comment]
re: 5.
I wonder if there could be a calculation where if your skill is above a certain level it defaults to turning a maximum of whatever the "save" turn adjustment would be and only yank the wheel if you don't pause a moment in between adjustments

**Comment by Brambor** [comment]
> 5. It might be better for turning to be by smaller degrees if you're going faster.  At high speeds you would be giving a slight adjustment of maybe 5 degrees not trying to yank the wheel 45 degrees

I like 5, my go on 5:
When you drive at a certain speed (maybe 80 km/h? should be settable), you enter _fast & fine_ driving mode. In F&F you turn by half amount of degrees per keypress. But only in half the moves so the player is able to "yank" the wheel even at those speeds. Additionally:

1. Doesn't have to be half, or maybe set different degrees for different speeds.
2. Message "Going over 80 km/h,  5° fine turning enabled." - If intuitive enough, can be removed later.
3. Ability to list speed to degrees turned in a menu. It would look like this:

"Turning by D degrees at speed abs(V)"
- D | V
- 0 km/h | 30°
- 32 km/h | 22° 30'
- 60 km/h | 15°
- ...
- 400 km/h | 3 °

The player would add and remove lines in ascending order. Simpler than autopickup.

But then, when I'm reading this. Real highways are made for a system I'm sketching out. In CDDA every road turn is 45°, so realistically, while good for dogging things on road, it's useless for driving on an empty road. So I'm sceptical about the ratio of programmers work to players enjoyment.

But still, combined with a longer vision range it is necessary for dogging, I think.

**Comment by Pseudogeist** [comment]
> 
> 
>     1. I agree that you should either be able to avoid the car or have better feedback if a skid or other pebkac error occurred so you can learn for next character
> 
>     2. realistically you'd slow down to improve maneuverability when avoiding a stopped car irl not just turn (remember this is different from weaving cars going similar speeds on the freeway, this is like dodging a mattress lying in the middle of the road)
> 
>     3. I too would say lvl 2 in a skill should be equivalent to someone who's been driving for a while, not a teenager who's brand new
> 
>     4. In the event of a skid or some similar malfunction it would be nice if it took into account your speed and gave you a chance to react like you would in combat, as this scenario is similarly lethal.
> 
>     5. It might be better for turning to be by smaller degrees if you're going faster.  At high speeds you would be giving a slight adjustment of maybe 5 degrees not trying to yank the wheel 45 degrees

Ah, point 5 reminds me of headlight input. Perhaps a key to initiate a precision maneuvering which brings up a (can't think of the right word for the 'x'), changing colour based on how difficult the correction will be. Perhaps the pause command can then, instead of passing 100 moves, pass only enough for the vehicle to move one tile. Perhaps correction difficulty could be factored based on number and severity of corrections in the past few hundred moves, alongside the sharpness of the current correction?

**Comment by Xpyder** [comment]
these are all decent ideas but require the player to predict exactly when the mechanic will become a problem, which they have no way of knowing. (you might not know you need to enable "precision maneuvering" at your speed until you've already spun out)

I think that at or above skill level 2/3 it should default to a safe turning radius for your current speed and pass maybe 1/4 the number of turns that would normally pass (maybe require skill 4+ if factoring in inclement weather).  That way if you try to turn and it's not turning enough, your default reaction is to slow down to give yourself more time to turn?

**Comment by Xpyder** [comment]
I think there's value in allowing the character to perform unsafe actions, I just think for driving we need to better balance "I meant to do that and it bit me in the tush" vs "That's not what I asked you to do, so why did you kill me for it"

**Comment by Xpyder** [comment]
> at or above skill level 2 or 3 it should default to a safe turning radius

to clarify here I'm not saying it has to be a hard jump, it's probably better if it's an "estimate safe speed" that gets more accurate as your skill increases and less accurate during hazardous conditions, though I get that's probably a fair bit of work

**Comment by Pseudogeist** [comment]
> 
> to clarify here I'm not saying it has to be a hard jump, it's probably better if it's an "estimate safe speed" that gets more accurate as your skill increases and less accurate during hazardous conditions, though I get that's probably a fair bit of work

I don't really think we have to hand-hold too much here. Like with real driving it comes down to experience. Thinking about it, in- game the only time I ever seriously got up to those speeds was a year or two ago when I came across a black dragon from Magiclysm raining death on me from above. The other times were testing it out to see how it handled and going 'nah, this is unworkable'. Without longer, straighter roads or a serious need to GTFO there's no reason to be driving that fast, it's suicide. 140km/h is highway speeds, not twisty country roads. I like the idea of getting around an obstacle if you have enough time, but I wouldn't want to see someone snaking between two obstacles within spitting distance at 140km/h without spinning out unless they had excellent vehicle skill.

Regarding an estimated safe speed, it's pretty trivial I think. You would call the function calculating the chance of losing control, give the result a style and obfuscate it in some way, then display it. I'd rather not see that, personally, maybe if it was obfuscated based on traits and called something like "confidence". Regarding hazardous conditions, I haven't looked much at the code, but I'm pretty sure there's already some stuff in there regarding that. I think it may even include some scaling panic-type malus when confronted with danger. If not, that would be pretty cool. I _really_ like the idea of fumbling the keys/ wires with a horde banging on the windows, which I'm pretty sure isn't a thing yet...

**Comment by Zireael07** [comment]
Another candidate for a 'salvageable'/'QoL' label imho.
