### ISSUE TITLE
[Magiclysm] Potion starter containments

### ISSUE THREAD

**Issue by AdamChirnside** [CleverRaven/Cataclysm-DDA#50856]
### Describe the bug

Unable to combine potion starter created using whiskey, with potion starter created using rum, etc.

### Steps To Reproduce

1. Craft potion starter using some alcohol base
2. Craft more potion starter using some OTHER alcohol base
3. Attempt to put them both into the same container

### Expected behavior

Potion starter probably shouldn't care about the nutrition values of the base alcohol

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 31ef3ba [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi]
]

### Additional context

 DEBUG    : tried to put an item (potion_starter, amount 1) in a container (jerrycan) that cannot contain it

 FUNCTION : int item::fill_with(const item&, int, bool, bool, bool)
 FILE     : src/item.cpp
 LINE     : 9460
 VERSION  : 31ef3ba

**Comment by actual-nh** [comment]
Possibly a flag on recipes that should result in something ignoring the exact details of what you started with - something building on OVERRIDE_NUTRITION?

**Comment by AdamChirnside** [comment]
Soapy Water is another good candidate for this proposed new flag

**Comment by RenechCDDA** [comment]
Potion starts now have NUTRIENT_OVERRIDE and should stack regardless of component items, owing to their inheritance from `mixed_alcohol_strong`
