### ISSUE TITLE
keyboard select in Multi-drop was recently broken

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#50857]
### Describe the bug

in the multidrop screen you can only select with the mouse.  I've tried setting a keyboard key (space in my case since Esc is how I exit the menu anyways) but it ignores the key.

This bug was introduced within the past 2 weeks though not sure exactly when.

### Steps To Reproduce

Create a player
pick up lots of stuff
try to multi(d)rop without using the mouse
note that you can move the selector but can't actually choose anything

### Expected behavior

I expect that I can actually choose items to drop using the keyboard, and that the game respects the keybinding I set for this.

### Versions and configuration

(currently away from computer so don't have version info atm, can add later if others are having trouble reproducing)

**Comment by ZhilkinSerg** [comment]
See https://github.com/CleverRaven/Cataclysm-DDA/pull/50840.

**Comment by Xpyder** [comment]
Yep, that looks like it probably covers this.
I'll test tonight and close if that solves this
(and for posterity I did search but for drop specifically which is probably why it didn't show up)

**Comment by Xpyder** [comment]
ok, I figured out the confusion "Select" chooses items when applied to the mouse, but not when applied to the keyboard:

![image](https://user-images.githubusercontent.com/12039454/129818647-22914931-25fb-47e1-aa97-6e1ff990b670.png)

**Comment by Xpyder** [comment]
actually I think it's different enough from my initial surmisation to deserve a separate PR
