### ISSUE TITLE
numpad keybindings don't work in (d)rop item menu

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#50860]
### Describe the bug

the numeric keypad movement buttons (4 8 6 2) don't work in the multidrop menu despite showing in the keybindings menu.

This issue affects both numlock off and numlock on

### Steps To Reproduce

open (d)rop items menu
check keybindings
try to use arrow keys (as shown in keybindings) to verify those work
try to use numpad keys (as shown in keybindings), note those don't work

### Expected behavior

the settings to either be clearly bound locally (i.e. not show the numpad bindings) 
or to respect the global keybindings

### Screenshots

![image](https://user-images.githubusercontent.com/12039454/129820255-1b98cddf-187c-459e-9e9d-769fe345b65c.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: bea0650 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills]
]

**Comment by Malkeus** [comment]
Confirmed. I thought this was an Android thing. Started noticing it after updating a couple days back.

**Comment by Entity-y** [comment]
Good to see I'm not the only one with this issue

**Comment by Malkeus** [comment]
It shows in Android as suddenly not being able to mark stuff with a flick. But it also let me move around the drop menu freely instead of only being able to change columns to the left. Is it a bug or a 'feature'? All I know is I had to set my mark items key to ç bc every regular key gets mapped to an item eventually. Thumbs down.

**Comment by Qrox** [comment]
Number keys are handled as item count input in the drop menu, so they don't work when bound to other actions.

**Comment by Pseudogeist** [comment]
> 
> 
> Number keys are handled as item count input in the drop menu, so they don't work when bound to other actions.

The issue is that item count input circumvents the keybindings menu, which among other things conflicts with player expctations. This could be addressed with an `input item count dialogue' key and `number key item count input toggle` key. With better names, mind you.

**Comment by Qrox** [comment]
Yeah, a separate keybind that lets you input and select a given amount sounds better than the current system where you secretly input a number as if it were a password.

**Comment by Xpyder** [comment]
I didn't even know you could enter numbers on that screen

**Comment by Xpyder** [comment]
> This could be addressed with an `input item count dialogue` key and `number key item count input toggle` key. With better names, mind you.

My expectation would be that it matches the behavior in the Advanced Inventory Screen, one could probably steal keybinding names from that as well

**Comment by Qrox** [comment]
Maybe we can use `,` and `0` for partial selection to match the current `.` and `5` for full selection (on qwerty keyboard, at least). Other inventory menus still use number keys for hotkeys though, so this won't solve the original issue.

**Comment by RoyBerube** [comment]
Same as issue #50819. It would be easy to change the inventory window from using keychar to using keycode instead. Then the numpad keys would provide a different key code than the keyboard number keys. I've tested it and seems like a good start.

A nasty side effect of that however is when you change the input option to keycode to get it to work, the ? screen poorly handles wrapping of the now longer action key list. Since the output is absolute per line, it cannot handle lines that wrap.

**Comment by Qrox** [comment]
The inventory hotkeys need to be reworked to accept keys with shift modifiers in keycode mode. There's also the problem of what to do with assigned hotkeys when switching between keychar to keycode, which is why I haven't migrated inventory menus to use keycode yet.
