### ISSUE TITLE
Custom alarms (Not for sound bombing)

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#50869]
# Is your feature request related to a problem? Please describe.
As the game grows and advances it's becoming valuable to have reminders of certain times of days, or of certain periods of time.  Like reminders to eat or a 2 hour timer to interrupt a crafting project

# Describe the solution you'd like
Similar to the alarm you set before you go to bed, I'd like to be able to  set:
 - an alarm based on time of day
 - an alarm based on time passed
 - a 'silent' vibrating alarm (so if it goes off while I'm sneaking it doesn't snitch on me)
 - the ability to cancel specific upcoming alarms

ideally by activating an item with an alarm clock
possibly with each item having it's own alarm
eventually with each item maybe supporting up to 3-5 alarms

# Describe alternatives you've considered
none atm

# Additional context
About half of this seems like it's already in the game, if you set a sleep alarm then get up early the alarm still goes off.  But idk  if the code currently accommodates multiple alarms or just one (even just one would be fine as a starting point)

**Comment by Xpyder** [comment]
Note that this is different from the "Wait until" feature because it allows you to fill the time with an activity other than resting

**Comment by anothersimulacrum** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/29519

**Comment by Xpyder** [comment]
Hmm, I wonder if I've been muscle memorying right past it.  I'll check when I get home

**Comment by ifffrt** [comment]
Maybe this is already resolved, but I would still want the ability to get my alarms to be more customizable, like showing custom messages, the ability to add multiple alarms, and being able to set my alarms to more granular times of day (and times passed). Maybe in another opened issue.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
