### ISSUE TITLE
[0.F stable] Zero starting cash in Defense Mode

### ISSUE THREAD

**Issue by asamn** [CleverRaven/Cataclysm-DDA#50871]
### Describe the bug

Defense mode always starts with zero cash, no matter what value was entered for initial cash during the setup.

### Steps To Reproduce

Start defense mode in Special > Defense from the starting screen
Enter any amount for initial cash during defense mode setup  
Start defense mode and notice that you are broke 

### Expected behavior

Expected that you start with the amount of cash you entered 

### Screenshots

![defenseset](https://user-images.githubusercontent.com/43041738/129943709-4064a0d7-893b-4128-8087-9e4b9d03aeb0.png)
![defense](https://user-images.githubusercontent.com/43041738/129943710-0c13d14b-bb2c-42e8-960a-4c2c0a32e20a.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by ERRORCODE509** [comment]
Honestly, I'm surprised that defense mode functions at all. I don't think it's had much work done in quite a long time. I'd do it myself if I knew how, because I think it's a neat concept.

**Comment by actual-nh** [comment]
Ping: @ZhilkinSerg?

**Comment by ZhilkinSerg** [comment]
`cash` data member in `player` class shadows `cash` data member from `Character` class and that causes that strange behavior.

Can be fixed with removing `cash` data member from `player` class:
![image](https://user-images.githubusercontent.com/16213433/130129757-ef1faa2a-7881-4b15-b03b-1d2a1d151467.png)

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-5858.
![изображение](https://user-images.githubusercontent.com/11132525/152647893-ad59a5d2-76d5-423b-9b26-98922903c12a.png)
