### ISSUE TITLE
Camera Picture string parsing error

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#50886]
### Describe the bug

When you take a photo of multiple subjects, you get an error.

19:10:33.983 ERROR : src/iuse.cpp:6095 [int get_quality_from_string(const string&)] Error parsing photo quality: Stray characters after integer in '0,mon_goose_canadian,0,mon_mirelurk,0,'
19:10:38.558 ERROR : src/iuse.cpp:6095 [int get_quality_from_string(const string&)] Error parsing photo quality: Stray characters after integer in '0,'
19:11:38.767 ERROR : src/iuse.cpp:6095 [int get_quality_from_string(const string&)] Error parsing photo quality: Stray characters after integer in '0,mon_mirelurk,5,'

### Steps To Reproduce

I used a professional camera and took a photo at close range.
Does not appear to be an issue with dead creatures.

### Expected behavior

For it to parse the string properly

### Versions and configuration

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7011072/debug.log)

**Comment by hexagonrecursion** [comment]
Confirmed by taking a photo of 9 zombie cops

 DEBUG    : Error parsing photo quality: Stray characters after integer in '5,'

 FUNCTION : int get_quality_from_string(const string&)
 FILE     : src/iuse.cpp
 LINE     : 6095
 VERSION  : bfda921

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: bfda921 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]
