### ISSUE TITLE
Vehicle tank water transfer infinite loop

### ISSUE THREAD

**Issue by AdamChirnside** [CleverRaven/Cataclysm-DDA#50899]
### Describe the bug

When trying to top up a 60L vehicle water tank from a smaller tank, the game loops forever (no water seems to be transferred). See attached save file for vehicle configuration

### Steps To Reproduce

1. Make a vehicle with multiple liquid tanks of different sizes
2. Have some clean water in each tank, but leave space in the larger tank
3. Try to transfer water from smaller tank into larger tank (using 'e'xamine faucet, fill a container with water, fill available tank)

### Expected behavior

Ability to transfer water between vehicle tanks

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 7e2826a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi]
]

### Additional context

[My save file](https://github.com/CleverRaven/Cataclysm-DDA/files/7015510/Pickett.zip)

**Comment by Menschheit** [comment]
Well you are not choosing a specific tank by using faucet. It is actually very logical in real life that you keep filling the same tank from where you siphon water, the task will never end and nothing changes.

I had a glance at the code, there is no way to exclude one specific vehical part(the target) from the draining sources during liquid transfer. Since the `parts` member is private, someone needs to write a new member function in the `vehicle` class.

**Comment by hexagonrecursion** [comment]
Confirmed using the attached save file

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: bfda921 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi]
]
