### ISSUE TITLE
0.F-1 bug - advanced inventory (AIM) does not allow carried items to be moved

### ISSUE THREAD

**Issue by chaohedgehogs** [CleverRaven/Cataclysm-DDA#50897]
### Describe the bug

Carried items can't be placed on a floor tile/furniture using AIM. When interacting with items in the inventory, pressing enter or shift+m does not do anything, pressing m brings up quantity selection, but pressing enter at this point closes said popup without doing anything. 

Moving items between two tiles, moving items from a tile into the inventory, and using "," to move all items from inventory to a tile still work normally. Drop menu works. Bug affects multiple newly created worlds, occurs both when wielding and unarmed.

### Steps To Reproduce

1. Make new world/character.
2. Open AIM when adjacent to tile/furniture containing items.
3. Pick up items without issue.
4. Attempt to move said items back to tile (no response).

### Expected behavior

Carried items should be able to be moved onto a tile.

### Screenshots

![cdda 0 f-1 bug](https://user-images.githubusercontent.com/46550455/130069594-c79c8006-d6fd-4c49-9d83-6e3715ecdf29.png)

### Versions and configuration

- OS: Windows 7
- Game Version: 0.F-1
- Graphics version: Tiles [MSXotto+]
- Ingame language: English
- Mods loaded: dda, no_npc_food, package_bionic_professions, No_Fungi

### Additional context

[Bugtown.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7014381/Bugtown.zip)

**Comment by ZhilkinSerg** [comment]
Try to reproduce it on latest experimental version.

**Comment by chaohedgehogs** [comment]
Bug doesn't occur on latest experimental (0626) or 0.F stable (0512), so it's specific to 0.F-1.

**Comment by DK451TFX** [comment]
Confirmed

- OS: Windows
    - OS Version: Windows 7 SP1
- Game Version: 0.F-1 [64-bit]
- Graphics Version: Tiles
- Game Language: System [ru]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Dark Days of the Dead [classic_zombies]
]

**Comment by helicomatic** [comment]
This is the commit that fixed this issue, didn't make it into 0.F-1
https://github.com/CleverRaven/Cataclysm-DDA/pull/50452

**Comment by ZhilkinSerg** [comment]
Fixed in `0.F-2`
