### ISSUE TITLE
Gun Mending currently doesnt work

### ISSUE THREAD

**Issue by estebandellasilva** [CleverRaven/Cataclysm-DDA#50896]
### Describe the bug

When trying to mend a gun - you can choose to clean or clean and lubricate.
Afterwards the time ticks down - then an error pops. No ressource except time is wasted, but gun still needs cleaning.

### Steps To Reproduce

1. Make a character with a gun. 
2. Aquire gun cleaing supplies. 
3. Mend the gun.
4. Get Error Message 

### Expected behavior

I expected my gun would be clean after mending.

### Versions and configuration

- OS: [Windows 10]
- Game Version: [0.F_7e2826a] (current lasted experimental)
- Graphics version: [tiles]
- Ingame language: [English]
- Mods loaded: [ StatsThroughSkills,StatsThroughkills, no fungal]

**Comment by Menschheit** [comment]
Possibly caused by #50736
This line was not copied into character.cpp 
![image](https://user-images.githubusercontent.com/28317565/130094102-382fbf4e-dce9-426f-a297-bcf321ecd4e1.png)
![image](https://user-images.githubusercontent.com/28317565/130095365-43b7fce6-12da-4ca2-b764-8719a2f7e7b5.png)

**Comment by actual-nh** [comment]
Ping: @KorGgenT?

**Comment by Stretop** [comment]
Seem to affect CBM mending ("Reset to factory state") as well:
 DEBUG    : invalid arguments to ACT_MEND_ITEM

 FUNCTION : void activity_handlers::mend_item_finish(player_activity*, player*)
 FILE     : src/activity_handlers.cpp
 LINE     : 2647
 VERSION  : c015a60
