### ISSUE TITLE
Sound support for spells

### ISSUE THREAD

**Issue by Ryan7251** [CleverRaven/Cataclysm-DDA#50898]
# Is your feature request related to a problem? Please describe.
Currently, there is no sound support for spells in Magiclysm. After unsuccessfully trying to add sound support through json, we have realized that the sound support is something that needs to be coded in sounds.cpp.

# Describe the solution you'd like
I know this is a lot to ask but if someone could make the code needed for spells to be able to make sounds we could get a sound pack for magiclysm going :) 

# Additional context
Here is aceplejades PR to show some of his work https://github.com/CleverRaven/Cataclysm-DDA/pull/50888 but till code is added sadly we are stuck.

**Comment by Ramza13** [comment]
Ok so its kinda awkward but it can be done with json at present.  The idea would be to have the spell call a second spell that uses effect_on_conditions which can make sound effects.  Take a look at the way lightning is handled as its creating a sound here at the top https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/effect_on_condition.json

**Comment by acepleiades** [comment]
> Ok so its kinda awkward but it can be done with json at present. The idea would be to have the spell call a second spell that uses effect_on_conditions which can make sound effects. Take a look at the way lightning is handled as its creating a sound here at the top https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/effect_on_condition.json

So it appears that
` { "sound_effect": "thunder_far", "outdoor_event": true, "id": "environment" }`

Allows me to add a sound in the soundpack side by writing
```
        "type": "sound_effect",
        "id": "environment",
        "variant": "thunder_far",
        etc.
```

Which makes me guess "sound_effect" relates to "variant" in the soundpack side and "id" is the same in both cases. That is interesting and good to know.
However, I still don't understand where I need to insert
` { "sound_effect": "x", "id": "spell" }`

I'd be willing to add it to every spell if you would please show me an example!

**Comment by Ramza13** [comment]
Yea its confusing and a lot bigger than you were thinking as its kinda a workaround but heres how it would go.  Assume spell base is the spell I want to add a sound effect to.  I'm guessing some of the fields I have here are optional and you could make it smaller.  Note:  I don't have sound effects working when I build it myself so while this prints the test message and therefore should work let me know if it doesn't as that would be a bug.
```
  {
    "type": "SPELL",
    "id": "base",
    "name": { "str": "Base" },
    "description": "Base.",
    "valid_targets": [ "ground" ],
    "extra_effects": [ { "id": "sound_effect", "hit_self": true } ],
    "max_level": 1,
    "base_casting_time": 3,
    "shape": "blast",
    "effect": "summon",
    "effect_str": "mon_zombie_gasbag_impaler"
  },
  {
    "type": "SPELL",
    "id": "sound_effect",
    "name": { "str": "sound_effect" },
    "description": "sound_effect.",
    "valid_targets": [ "self" ],
    "max_level": 1,
    "shape": "blast",
    "effect": "effect_on_condition",
    "effect_str": "EOC_sound_effect"
  },
  {
    "type": "effect_on_condition",
    "id": "EOC_sound_effect",
    "effect": [
      { "sound_effect": "thunder_far", "id": "environment" },
      {"npc_message":"Test"}
    ]
  }
```

**Comment by Ryan7251** [comment]
@Ramza13 ok so i'm new to this would all the changes be done in the magiclysm spell json file like say i wanted to add a sound to point flare would it be the base spell with just everything you posted added because i did try that it sadly did not work i even got the test npc_message just no sound anyone have any idea what i did wrong?

**Comment by Ramza13** [comment]
It actually doesn't matter what file you put it in it should work.  

I just looked at the demo code and I think I figured out why it's not working.  I think there is a bug with using sound effects that might be causing a problem when done by spells.  I'll submit a fix and link it to this issue.

**Comment by Ryan7251** [comment]
> 
> 
> It actually doesn't matter what file you put it in it should work.
> 
> I just looked at the demo code and I think I figured out why it's not working. I think there is a bug with using sound effects that might be causing a problem when done by spells. I'll submit a fix and link it to this issue.

Good news everyone! it works......kind of it does in deed make sound now issue is my little brain is having issues understanding how to add diffident sounds. like to test it i tried to use Otopack's 9mm_1 sound file it did not seem to work (to be clear i will be using my own sounds i make/find for free when i start for real i won't steal otopacks sounds) this was more to see if i can get other sounds to work. but sadly no sound if i switch thunder_far anyone have any ideas?

**Comment by Ramza13** [comment]
My guess is the confusing id system for sounds is tripping you up but its just a guess.  If you post the code you are trying I will see if I can figure out whats happening.

**Comment by Ryan7251** [comment]
> 
> 
> My guess is the confusing id system for sounds is tripping you up but its just a guess. If you post the code you are trying I will see if I can figure out whats happening.

I just fixed it what i had to do is make a new sound effect in environment json for the 9mm_1 sound file and then i placed the 9mm_1 ogg sound file with all the rest of the ambience and weather sound files told the joson to grab it from there and it worked!

**Comment by Ryan7251** [comment]
will oddly the workaround works but only if useing sounds that are with the otopack but if i try to add a new sound it's a no go....

**Comment by Ryan7251** [comment]
Got it to make sound but seems like it is on loop like even if i just move the sound loops may have to see about waiting till some kind soul adds the support needed for spells after all.

**Comment by Ryan7251** [comment]
> 
> 
> My guess is the confusing id system for sounds is tripping you up but its just a guess. If you post the code you are trying I will see if I can figure out whats happening.

got the sound to work however due to it counting as environment it is just looping over and over do you maybe have a idea or are we back to hoping someone codes in support for spell sounds?

**Comment by Ramza13** [comment]
Can you post the code you are using?  It shouldn't be an infinite loop that sounds like a bug.

**Comment by Ryan7251** [comment]
> 
> 
> Can you post the code you are using? It shouldn't be an infinite loop that sounds like a bug.

sure thing
`[
    {
    "type": "sound_effect",
    "id" : "environment",
    "volume" : 100,
    "files" : [
        "kelvinist_sounds/point_flare.ogg"
    ]
  }
]`
kelvinist json was changed with your work around with sound effect being point_flare other then that i have no other code.
folders are in the following order
![Capture](https://user-images.githubusercontent.com/22566295/130290836-b0241f68-503b-4102-a84d-384b52fb587f.PNG)
with the json code being in the Magicsounds folder.

**Comment by Ryan7251** [comment]
> 
> 
> Can you post the code you are using? It shouldn't be an infinite loop that sounds like a bug.

got a update turns out i needed to use a variant i was thinking variants were used to control when a sound is played passed of a trigger like how thunder_far is a variant so would only play when the game made thunder and it was far away.

**Comment by acepleiades** [comment]
I guess this issue could be closed then? Now it's just a matter of doing this for every spell I suppose.
