### ISSUE TITLE
Refrigerators are spawning instead of fences inside labs

### ISSUE THREAD

**Issue by andreicv9** [CleverRaven/Cataclysm-DDA#50893]
### Describe the bug
Fences are being replaced by refrigerators.

### Steps To Reproduce

1. Spawn inside a lab
2. Find room that contains wire fences. 
3. Proceed to witness the rise of our new cooling overlords.

### Expected behavior

Refrigeratos should not replace fences.

### Screenshots

![image](https://user-images.githubusercontent.com/64739806/130021107-7f184441-3534-40eb-bcfe-a56ec46f28b2.png)
![image](https://user-images.githubusercontent.com/64739806/130021198-1a771671-c5ad-4455-98fc-8fa80b3d58ab.png)

### Versions and configuration

- OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
- Game Version: [from the main menu, e.g. 0.C-29938-g90f5268437]
- Graphics version: [Tiles or Terminal]
- Ingame language: [Arabic or Bulgarian or Chinese (Simplified) or Chinese (Traditional) or Dutch or Esperanto or French or German or Italian (Italy) or Japanese or Korean or Polish or Portuguese (Brazil) or Russian or Serbian or Spanish (Argentina) or Spanish (Spain) or Turkish]
- Mods loaded: [e.g.dda, boats, hacktheplanet, StatsThroughSkills]

**Comment by KanterDev** [comment]
![image](https://user-images.githubusercontent.com/89065534/130022585-c8b091db-278c-48d1-8b88-ecc80216ee39.png)

Can confirm, looks like it's refrigerators on top of fences.

**Comment by stelscarrot** [comment]
Got it on 957defc, 4 days old build

![image](https://user-images.githubusercontent.com/88937756/133021242-cec8ec15-7951-4582-8dd2-9a80f621d3fd.png)
