### ISSUE TITLE
Activating bionics cools overheated character for one turn

### ISSUE THREAD

**Issue by pehamm** [CleverRaven/Cataclysm-DDA#50900]
### Describe the bug

In my current save, I noticed that with my temperature just above the level where heat penalties start to reduce my strength by one, activating any of my bionics removes the penalty. The character info screen shows a smaller slowdown, and the inventory screen shows a higher max carrying capacity as well. Doing any other action including waiting afterwards brings the penalty back to 1.

This happened during dusk, and waiting for a few minutes would reduce the exterior temperature to give back the stat point either way, so this seems to be a small temperature effect whenever bionics are activated.

### Steps To Reproduce

1. Load attached save
2. If strength is lowered to 10 due to heat, activate any bionic and observe strength go back to 11.
3. Wait a turn or do any action to again reduce strength to 10.
4. Repeat as wished.

### Expected behavior

Activating bionics should not cool me down.

### Versions and configuration

- OS: MacOs
    - OS Version: Name: Mac OS X; Version: 10.14.6; Build: 18G6020; 
- Game Version: 0.F-1516-ged2f630d83 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Cannot upload the savefile to github (It tells me "is not included in the list"), so I put it on Dropbox:
https://www.dropbox.com/s/bpystzqiqcmo05t/Fishers.zip?dl=0

**Comment by hexagonrecursion** [comment]
Confirmed using the attached save file by turning the taste modulator on and off

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: bfda921 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]
