### ISSUE TITLE
[0.F stable] Claire Isherwood's cat quest is sort of broken

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#50903]
### Describe the bug

Claire's quest asks you to bring her a cat, and a quest marker is placed by a cabin. However, the cats are spawned outside of the cabin, and all cats I've found in this version flee at a very long range from my character (no animal discord, nor affinity, so the attitude should be default), and you can't chase them down, as they're too fast (as they should be).
Thus, the only chance to catch a cat is to corner it, and you can't corner these cats (it would have been possible if at least one of them had been spawned inside).
I got "lucky" and saw another cat inside a building at a completely different location, managed to corner it, bribe it with food, and capture it. However, Claire doesn't recognize the quest as fulfilled when the monster is brought to her.
If I understand the JSON file correctly, she requires a "mon_cat", while the cat I caught is a shorthair cat, which ought to be one of the mon_cat_x variants.

### Steps To Reproduce

- Bring Claire a cat that isn't of the base type.
- See that she doesn't recognize the quest as fulfilled either with the cat in the cage or on the floor.

### Expected behavior

- Either the quest should be specific to make sure the correct kind of cat is specified, or it should, somehow, be modified to accept any cat (so the player understands what's expected).
- Spawn at least one of the cats inside the target building to give players a chance to actually follow the quest indication, rather than be left to find a work around when they find it isn't possible to perform the quest in the indicated way.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

I assume the problem stems from modifications to cat behavior at some point in time, and that they previously behaved approximately like dogs in terms of human interaction.

**Comment by Night-Pryanik** [comment]
Resolved by #61675.
