### ISSUE TITLE
Accuracy of vehicle turrets has plummeted recently so that they can't hit any target 95% of the time. 

### ISSUE THREAD

**Issue by Dano-416** [CleverRaven/Cataclysm-DDA#50907]
### Describe the bug

After one of the recent updates to the experimental branch, vehicle turrets can't seem to hit **anything** anymore. Shots just spray all over the place. It makes vehicle-mounted weapons pretty much useless. Note that I first encountered the issue in a Magiclysm run, but I have also tested it in regular vanilla Cataclysm, and the problem persists there as well. I also tested with manual aiming as well as automatic targeting, and neither targeting mode makes any difference either.

### Steps To Reproduce

1. Get in a vehicle that has a mounted and loaded machine gun turret.
2. Go find some zombies or other creatures to murder.
3. Try to shoot them with the mounted machine gun. You will almost certainly miss, regardless of target size or range.
4. Try again, and again, and again, until you are persuaded that something is broken here.

### Expected behavior

I expect my mounted guns to hit targets at reasonable range far more often than not. Mounted turrets were never dependent on the character's marksmanship or rifles skill, nor does using a mounted turret affect or improve those skills. My understanding is that this is still supposed to be the case. Otherwise, mounted turrets are useless, and turrets capable of targeting and firing automatically are doubly useless.

### Versions and configuration

- OS: Windows 10 x64
- Game Version: e055bd1 (tiles), experimental build 2021-08-18-0858
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: None

**Comment by Xpyder** [comment]
> Mounted turrets were never dependent on the character's marksmanship or rifles skill, ... Otherwise, mounted turrets are useless

I'm not saying something isn't broken, but manually firing a turret seems like it should be affected by the player's marksmanship skill (though I agree automatic turrets probably shouldn't)

**Comment by Dano-416** [comment]
> I'm not saying something isn't broken, but manually firing a turret seems like it should be affected by the player's marksmanship skill (though I agree automatic turrets probably shouldn't)

I don't necessarily disagree with that, actually, in terms of manual aiming. I don't generally bother building a turret control unit for automated targeting, but I did when this issue emerged, to see if an AI-controlled turret could do better than my character could (which I figured would/could mean that it was a skills problem for my character), and it didn't make a damn bit of difference when AI targeting was turned on. 

Given that I stripped the parts to build that control unit off of military helipad turrets that are still eminently competent and murdering a character once they're in range (I tested that, too), an automated vehicle turret should have the same level of accuracy as a sentry turret, at the very least.

**Comment by hexagonrecursion** [comment]
Confirmed. M240 installed on Humvee is surprisingly inaccurate

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 86ff040 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by Ramza13** [comment]
Mikenyes on discord tracked it down to this PR #50634

**Comment by anothersimulacrum** [comment]
Fixed in #50967
