### ISSUE TITLE
Disable automatic drinking for alcohol

### ISSUE THREAD

**Issue by Igryn** [CleverRaven/Cataclysm-DDA#50906]
# Is your feature request related to a problem? Please describe.
From time to time i forget to set up an ignore zone for alcohol in my zones settings and player character gets very drunk while performing any activity, faster than i can react.

# Describe the solution you'd like
Ban alcohol from autodrinking

# Describe alternatives you've considered
Exclude alcohol from drinks category and move it to some other

# Additional context
As fun as it is it is also kind of annoying after a while

**Comment by actual-nh** [comment]
Perhaps do this automatically - unless the character has an alcohol addiction?

**Comment by Xpyder** [comment]
I would say Alcohol probably belongs in the Drugs category not the Drinks category in general.  Given that Hard alcohol should actually dehydrate you, the opposite of what other drinks do

**Comment by Scorch-Mechanic** [comment]
Is this really the fault of the zone system? It seems to me that if you don't want to auto-drink alcohol, you shouldn't put alcohol in an auto-drink zone. I personally have my auto drink and auto eat zones set up separately from my main food and drink storage zones, and take care to only place recently cooked foods and beverages I want to auto-drink there.

**Comment by Xpyder** [comment]
> if you don't want to auto-drink alcohol, you shouldn't put alcohol in an auto-drink zone

My understanding was they set up the Auto Sort: Drinks and Auto Sort: Food to the same square as Auto Eat/Drink, as one should so they don't have to manually sort individual food items.
