### ISSUE TITLE
Early Mechanics balance is off with the new split between Theoretical / Practical skill

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#50911]
### Describe the bug

Mechanics 0 used to be locked behind books, presumably because you would need a reference manual to do maintenance starting out

Books now train theoretical skill, but even attempting something like removing a mirror or seatbelt requires the practical skill

### Steps To Reproduce

create a character with mechanics 0
wish for a copy of Under The Hood
Read your way up to mechanics 3
note you effectively have no way to raise your practical mechanics

### Expected behavior

I would expect that with theoretical knowledge I could attempt a mechanics install/removal/repair
and practical skill would affect success vs damaging the part

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: c015a60 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills]
]

### Additional context

some recipes that use the Mechanics skill as primary could also help and might be an easier early solution

**Comment by Entity-y** [comment]
Guess the new meta is sealing and opening crates to get to level 1.

**Comment by Xpyder** [comment]
g2k you can do that.  I was desperately searching for a wrench and jack so I could practice changing tires.  A lot.

**Comment by actual-nh** [comment]
Ping: @I-am-Erk?

**Comment by I-am-Erk** [comment]
Being able to attempt to remove and install things is supposed to be knowledge based, not practical, which is the primar bug here.

It would be nice to have some more practical skill role in here, probably in the time it takes you to do the thing, but on a basic level this is just a spot where I missed an inappropriate call to get_skill that needs to be get_knowledge.

**Comment by Svatopluk1** [comment]
This looks like the same problem as in #50775.

**Comment by I-am-Erk** [comment]
yes it is
