### ISSUE TITLE
Make translation context in Transifex more reliable

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#50916]
Right now the translation context is pretty messy and enforse to find context by yourself, which make translation enough complicate

I see few ways to improve it:
1. Make "Occurrences" more readable, showing more reliable information - at least mod name and correct file name, something like `[Magyclism] lang/json/magyclism/spells/attunement/Forse_Mage.py:` instead of `lang/json/SPELL_from_json.py:`

 2. Make the whole context more understandable without search - maybe showing another text from same file or at least raw json. Like
```
Spell X - NNN
Description of Spell X - translated version of Description of Spell X
Message of spell X - translated version of Message of spell X
```

3. Show another dependencies of this file - if Spell X create Item X, knowing that fact can help users to not make a few names for same thing

4. Show the commented `"//":` information - even if it's simple TODO, it can help to understang the hidden meaning of text

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
