### ISSUE TITLE
Mining destroys connected downstair

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#50918]
### Describe the bug

If you start on the ground level, dig a downstair, go down and mine sideways, the downstair you dug becomes a ledge as does the ground above the tile you dug.

### Steps To Reproduce

1. stand on grass
1. dig a downstair
2. go down
3. mine sideways
4. try going up the stairs
5. you get "You may be unable to return back down these stairs. Continue up?"
6. say yes
7. you trigger a ledge and fall down one story
8. get out of the hole in the ground
9. Find that some tiles on the surface turned into ledges. This always affects the stair you stood on and the tile you mined. Sometimes this also affects other surrounding tiles (falling down those ledges places you inside solid blocks).

### Expected behavior

I expected to be able to mine without destroying the surface above me. How am I supposed to create a staircase that is several z levels deep?

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 86ff040 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Possibly related: https://github.com/CleverRaven/Cataclysm-DDA/issues/50599

**Comment by a-chancey** [comment]
Ran into this the other day and assumed I did something wrong while trying to dig into a hazardous waste sarcophagus. Wound up debug teleporting out to find just an open hole where my downstair was. I assumed digging my next space caused a collapse of the ground above me which maybe chain collapsed the stairs

afterwards, I grabbed my grappling hook and climbed back down the hole, and I was entirely unable to climb out. Pressing < attempted to climb back up only gave me the same “you won’t be able to climb, attempt anyways?” Prompt, and (e)xamining the space only gave the prompt to take down the hook. I had to debug teleport out again. 

I’ll have to find what version, it was an experimental from about three days ago, running on Windows 10

**Comment by jim-huynh** [comment]
@hexagonrecursion This should be mostly resolved now.  There should only be a 1-2% chance that the stairwell gets destroyed now, rather than the seemingly 100% chance previously.  Tunneling will always have a risk of collapse due to how collapse is calculated, but it should be much lower than previously, assuming you're only digging single wide tunnels.

**Comment by hexagonrecursion** [comment]
This was mostly fixed. Thanks.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: cfc00fa [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
