### ISSUE TITLE
-21M xp on skill means no way to progress

### ISSUE THREAD

**Issue by MagratGarlick** [CleverRaven/Cataclysm-DDA#50921]
### Describe the bug

Some calculations in SkillLevel::train is probably causing an integer overflow. 

Dont have a pinpoint cause, but a character created after Aug 15 (#50703, last possibly related patch I can find; I believe https://github.com/CleverRaven/Cataclysm-DDA/commit/7d2cd66aea1869cb8eb7861f58d33680c91393c1 is already in effect) is not gaining any fabrication on level 3 despite 20 buckets made so I dug into the save file. 

`"fabrication": { "level": 3, "exercise": -2147292544, "istraining": true, "lastpracticed": 833841, "knowledgeLevel": 3, "knowledgeExperience": -2147292544, "rustaccumlator": 0 }` is what I found. 

It's likely not restricted to crafting too, because while I had not noticed, my Melee and Cutting are both having -21M exercise & knowledgeExps as well. 

This issue is also experienced by others and reported in reddit: 
https://www.reddit.com/r/cataclysmdda/comments/p7f26z/my_progress_to_tailoring_3_is_roughly_23_million/
https://www.reddit.com/r/cataclysmdda/comments/p7f26z/my_progress_to_tailoring_3_is_roughly_23_million/h9n95s4?utm_source=share&utm_medium=web2x&context=3

Can provide save on request, but isn't sure it'll help since the trigger point is likely long in the past.

@I-am-Erk @eltank 

### Steps To Reproduce

Don't know...see above.

### Expected behavior

Not having arbitrary large negative experience. 

### Versions and configuration

- OS: Win10
- Game Version: 7e2826a
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: Vanilla

### Additional context

I'll attempt to see if I can get a reliable way to replicate this, but not putting my hope up

**Comment by I-am-Erk** [comment]
besides tracking down the overflow we should also have some sanity checks that ensure your experience is not negative and set it to zero if itis.

**Comment by Xpyder** [comment]
> set it to zero if it is

Does it go to 0 when you level up a skill?  if not is there a way to determine the floor for your current skill level?  that might be better than setting it to 0 as the autocorrect

**Comment by eltank** [comment]
Time for another band-aid fix: #50929
This should get people's save file un-borked and prevent xp from going negative as well as give us more debugging info (we still don't know how it's happening).

**Comment by eltank** [comment]
> > set it to zero if it is
> 
> Does it go to 0 when you level up a skill? if not is there a way to determine the floor for your current skill level? that might be better than setting it to 0 as the autocorrect

Yes, 0 is the baseline when you've just gained a level.
