### ISSUE TITLE
When a wielded item with magazine/ammo gets destroyed, it will not drop the magazine/ammo

### ISSUE THREAD

**Issue by Valares** [CleverRaven/Cataclysm-DDA#50925]
### Describe the bug

If a wielded item that contains a magazine, ammo or with a modification takes enough damage to get destroyed, it vanishes with the magazine/ammo/mod.

### Steps To Reproduce

1. Spawn in a cellphone with a fitting battery or a gun with fitting ammo/magazine.
2. Reload the item with the fitting battery/magazine/ammo.
3. Try [s]mashing it against a surface until it breaks.
4. Neither the ground nor the inventory bear the battery/magazine/ammo.

### Expected behavior

Given that in other circumstances - like shooting at the item in question - it does drop the content, as well as containers like backpacks do the same with their content, I'd expect the same from these items and under these conditions (consistency).

Ideally, content of all kind would take at least some damage when the container is destroyed, but it might be a bit extreme to just make it vanish.

### Versions and configuration

- OS: Windows 7 64-Bit
- Game Version: 5857e10 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

For a long time it actually dropped the content and mods of a weapon/tool.
I was able to track the change back to version 2021-07-23-0253 (first version that behaves like this), or namely the pull request #50138.

**Comment by Zeropol** [comment]
Indeed sometimes it is not that relevant : Say my M4A1 suffer critical damage, the magazine may be usable again ( not the sturdiest thing in a weapon system, but ).

Other times it ( actual behavior, if I trust you, and I am ) the magazine/content is destroyed yet it still is relevant. If I smash my smartphone on a rock, I won't expect to recover the battery.

To go forward, if a bullet hit my backpack, I won't expect all of the content to be magically exempt from damage.

As you said : 
>Ideally, content of all kind would take at least some damage when the container is destroyed, but it might be a bit extreme to just make it vanish.

I have no better insight than flaging a pocket/magazine as "exernal" or "inernal" for damage pruposes.

**Comment by mqrause** [comment]
If anyone wants to fix this: `Character::handle_melee_wear` in `melee.cpp` calls `item::spill_contents`. That checks if the item is a container before spilling, so magazines get ignored. Note though: `item_contents::spill_contents` then spills all pocket types anyway, not just container pockets.

**Comment by Valares** [comment]
> If I smash my smartphone on a rock, I won't expect to recover the battery.

Smartphones in the game are considered UPS, so you will not get any battery/accumulator back (nor did you get them before that change). This is fine, hence my bug report does not consider smartphones in any way.

As for the rest of your post, I'm not sure if I understand what this has to do with this bug report... unless you intepret my bug report as a suggestion, which it is not.

---

> If anyone wants to fix this: [...]
Given that you're the autor of the linked pull request and you called it a "fix" yourself, am I assuming correctly that this was an oversight and not an intended change?
I wanted to make sure this is actually a bug before pushing a fix for it.

**Comment by Xpyder** [comment]
> am I assuming correctly that this was an oversight and not an intended change

While your underlying assumption here is incorrect
(afaik there was not any change that brought this behavior about, and it's not technically an oversight since mags and ammo are treated differently than storage packs [who's ability to hold items only evolved relatively recently] making it a new feature request)

I do agree that it seems like a reasonable and intuitive feature request that would bring parity to the behavior when storage containers are damaged (crates being the exception)

**Comment by Xpyder** [comment]
In other words:

No it's not a bug, it's a missing feature that mirrors another feature recently added

Yes it is a good suggestion, thank you for posting it

**Comment by mqrause** [comment]
> Given that you're the autor of the linked pull request and you called it a "fix" yourself, am I assuming correctly that this was an oversight and not an intended change?
> I wanted to make sure this is actually a bug before pushing a fix for it.

Yeah, it's an oversight. It was meant to be an infrastructure change only, not a change in behavior. As such I consider restoring the previous behavior a valid fix. (There's always the possibility the core devs disagree with that, though.)
But as always, there's multiple ways to solve an issue, so a more complex solution would be good, too.

**Comment by Valares** [comment]
> Yeah, it's an oversight. It was meant to be an infrastructure change only, not a change in behavior.

Alright, good to know that I interpreted that correctly, thank you.
Also, looks like someone managed to pull a fix before I had the chance to get mine off. We will get to fine-tune the balance later...

---

> While your underlying assumption here is incorrect
> (afaik there was not any change that brought this behavior about, [...])

@Xpyder: I mean, I've explicitely stated in my report that this behavior changed in version 2021-07-23-0253, in a pull request that from my point of view was clearly intended to tidy up pocket handling and not shift balance around.

Please never state that someone's assumption or statement is incorrect if you don't know it either, given that in this case you are incorrect.

**Comment by mqrause** [comment]
I think this should have been closed by #50970?

**Comment by Valares** [comment]
> I think this should have been closed by [merged pull request]?

It should have, no idea why it wasn't.

**Comment by mqrause** [comment]
Because of the double `##`, it seems.
