### ISSUE TITLE
Autosave triggered mid crafting cause save error on load

### ISSUE THREAD

**Issue by MagratGarlick** [CleverRaven/Cataclysm-DDA#50922]
### Describe the bug

If an autosave is somehow triggered mid-crafting (I'm not sure if this's the "scheduled" autosave; think some message popped up before the saving but I didn't pay attention), the generated save file then contains an "activity_override" key in json which isn't properly handled on Load and cause a panic: `Invalid or misplaced field name "activity_override" in JSON data`

### Steps To Reproduce

1. Trigger Autosave while crafting
2. Load the save
3. Watch error popup
4. Ignore the error to resume loading and watch your craft progress to the end

**Edit**: Easier way to reproduce - Save-and-quite immediately after finish a crafting. Reload the save. This should trigger it right there.

### Expected behavior

Not getting the error message?

### Versions and configuration

    OS: Win10
    Game Version: 7e2826a
    Graphics version: Tiles
    Ingame language: English
    Mods loaded: Vanilla

**Comment by RDru** [comment]
Yes, saving just after crafting something and then loading causes the bug.
You can remove the content of "backlog" to fix the save, so it looks like that `"backlog": [  ]`

**Comment by NetSysFire** [comment]
Sounds like the thing that happened in https://github.com/CleverRaven/Cataclysm-DDA/issues/54208#issuecomment-1008674074

**Comment by LeahLuong** [comment]
Similar but not the same. This issue seems more benign in that its not causing game-breaking seg faults that require save editing. OP's "Edit:" offers an easy way to confirm if this is still an issue following #54323.

**Comment by mqrause** [comment]
I can't reproduce it. Neither with save after finishing a craft nor with autosave during crafting. No idea if it would have anything to do with #54323.

**Comment by LeahLuong** [comment]
This issue should prob be closed. Not only has it likely been fixed, stalebot was going to mark it & we've received no similar reports since. OP can still pipe up if they have something more to add.
