### ISSUE TITLE
Food preparation - allow skill and tool cooking time improvement.

### ISSUE THREAD

**Issue by freijie** [CleverRaven/Cataclysm-DDA#50935]
# Is your feature request related to a problem? Please describe.
Food preparation batch time does not represent real world cooking methods of making a lot of food quickly.
# Describe the solution you'd like
Change preparation mechanics as such:
Each recipe has

1. Preparation time for ingredients that require manual labor

This time can be improved by:

- Food preparation skill*proficiency
- Group craft(major, linear benefits from more cooks)
- Tools specific to recipe, e.g. food processor, food preparation kits that include now-unused kitchen junk and other variety of tools.

2. Cooking time for ingredients
Improved by: 

- If heat source is involved, heat source should have intencity, that determines max volume that could be processed at a time(e.g. you cant really boil 60L of water on hexamine stove, but its easy to do with open fire)
- Higher volume of cooking container to contain more portions of food, directly takes volume of ingredients to calculate how many portions you could make at once

For stage 2, there could be additions:
Using multiple heat sources at once, limit depending on skill and proficiency
Using multiple containers at once, limit depending on skill and proficiency
Each additional person helping with cooking adds 1 to limit of usable heat sources and containers.

With proposed method:

-  Food preparation could fully benefit from difference between fixed base with powerful tools vs road kitchen set vs portable tools.
-  It would allow getting help from NPCs in realistic way, scaling with helpers and kitchen size and allowing you to prepare large batches of food if you have a lot of NPCs, which could be essential for basecamp.

# Describe alternatives you've considered

Allow passive cooking stage like with fermenting, allowing you to switch to other work. After considering issues involved - e.g. it should check heat source constantly, check player presence nearby to make it somewhat realistic, I assume its it even more difficult to implement. However it could be implemented alongside with proposed mechanics.

# Additional context
tbd

**Comment by Xpyder** [comment]
I agree there's value here, though I'm curious to see how we're able to manifest these.

maybe certain tools could offer bonuses to batch cooking
maybe crafts (not just for cooking) could get a "recipe" section where we can declare the different stages of work, whether they benefit from batching, whether they require player interaction, and whether they're time sensitive (like overcooking bread is bad, over-fermenting vinegar/moonshine  or overcooking charcoal isn't a big deal [so far as I know])

Depending on how complicated it gets there might even be a place for adding an alarm clock requirement to certain recipes that goes off when certain stages finish and it needs interaction.

 maybe something like:
```
// Cook Pasta Recipe stuff
    "crafting_stages": [
        [
            "description": "Prep work"
            "duration": "5m"
            "requires_player": true
            "pausable": true
            "time_sensitive": false
            "batch_time_savings": "0%"
            "success": {"stage": "Boiling pasta"}
        ],[
            "description": "Boiling pasta"
            "duration": "10m"
            "tool": ["nearby_fire","hotplate"]
            "requires_player": false
            "auto_next_stage": false
            "pausable": false
            "time_sensitive": true
            "batch_time_savings": "95%"
            "batch_tool": [
                [ ["containing"],["boiling"] ]
            ]
            "success": {"item": "pasta_cooked"}
            "failed": {"item": "pasta_burned"}
        ]
    ]
```

Such that the amount you can batch is limited by the size of your "boiling+containing" tool and it requires a nearby fire or hotplate

obvs these categories would nee to be worked out and I'm sure I got some of they very wrong, but just food for thought

**Comment by MagratGarlick** [comment]
Smoking came to my mind - there are already two ways to smoke in-game where one needs your full attention and the other is prep-and-forget. Would be nice to have eg. pressure cookers etc to brew stew the same way smoking do.

**Comment by Zireael07** [comment]
Prep-and-forget implementation would also work for other things that have to e.g. cure, e.g. https://github.com/CleverRaven/Cataclysm-DDA/pull/50937

**Comment by RoyBerube** [comment]
The multi-cooker can already do the set-and-forget type of cooking. Begin by 'a'ctivating it and it will behave differently than normal cooking.

The drawback is that it needs separate code from normal cooking. Last time I checked, its power consumption was way out of line depending on if cooking was through activation or not.

**Comment by freijie** [comment]
For prep-and-forget i imagine following implementation:

- Upon starting passive stage of cooking, player gets 'cooking id #### remaining time #####' marked akin to other status effects, checking distance from object with every movement. (could be bugged out with remotely controlled kitchen on vehicle, but should save CPU cycles for checks? unless there is another usable method already implemented like with jumper cables).
- If player gets too far from dish in preparation, another timer starts. It checks dish info for how much attention it requires, and sets time accordingly. If player didnt return back to dish before timer ends, dish stops cooking and is transformed into object described in dish recipe (e.g. ruined bread)
- Potentially, dish could have two stages - one is for not checking in the middle, and other is for not returning to dish by the timer end - resulting in overcooked(- to Joy, slight penalty to Calories ) or charred(1/3 of calories, -joy, -health, -quench) dish depending on how late you are, described in recipe json.

For recipe side, as a rough draft - example for cake:
```
  {
    "type": "recipe",
    "activity_level": "LIGHT_EXERCISE",
    "result": "cake2",
    "category": "CC_FOOD",
    "subcategory": "CSC_FOOD_BREAD",
    "skill_used": "cooking",
    "difficulty": 6,
    "book_learn": [ [ "cookbook_daintydishes", 6 ], [ "baking_book", 2 ], [ "sweets_book", 3 ] ],
    "qualities": [ { "id": "COOK", "level": 3 } ],
    "tools": [ [ [ "surface_heat", 15, "LIST" ] ] ], 
    "charges": 12,
    "components": [
      [ [ "flour", 4 ] ],
      [ [ "salt", 12 ] ],
      [ [ "sugar", 24 ], [ "artificial_sweetener", 24 ] ],
      [ [ "chocolate", 3 ] ],
      [ [ "any_butter_or_oil", 2, "LIST" ] ],
      [ [ "powder_eggs", 2 ], [ "eggs_bird", 2, "LIST" ], [ "egg_reptile", 2 ] ],
      [ [ "water", 6 ], [ "water_clean", 6 ] ]
    ]
\\Tools that improve speed of preparation, optional
\\number is % for time reduction of preparation stage for each tool
"prep_tool": [ [ "baking_kit", 10 ], [ "pastry_kit", 30 ],  [ "food_processor", 10 ]
\\proficiencies used for preparation stage speed up
"prep_proficiencies": [
      { "proficiency": "adv_baking" },
      { "proficiency": "pastry" },
     ], 
\\Minimal preparation time with proficiencies learned
\\prep tools reduce it further
"prep_time": 15
\\increases speed of prep stage with more people helping, max helpers,  % of time that could be saved by max helpers.
\\possible future option, advanced cooking furniture like automated processor could count as an assistant rather than tool
\\each helper increases time reduction by 60/3%
"prep_assist": 3, 60 
\\can leave preparation halfway, true or false
"prep_interrupt": false
\\object that you get when you interrupt the dish, can be used to make generic dish later
"prep_interrupt_result":failed_sweet_dough
 \\name of dish during passive cooking stage
"prep_success": {"stage": "baking_cake"}
\\proficiencies used for cooking stage
"cook_proficiencies": [
      { "proficiency": "adv_baking" },
   ], 
\\time to cook dish with proficiencies learned
"cook_time":45
\\player has to be near cooked food to check up on it, time (seconds there) between check ups, rolls a failure upon each missed checkup
"cook_player_attention": true, 300
\\by the end of cooking stage, checks of player is present, if not present for more than 20% of total cook time when it finishes baking, you get failed dish instead
\\if you miss the time by 20%, you get overcooked dish instead,
\\lack of proficiency may roll that too, optionally
\\additionally maybe define custom overcooked stages names
\\some advanced automated tools may omit this requirement
"cook_time_sensitive": yes
\\tools that are used for batch cooking
"cooking_tools": [ ["baking, 2"] ]
\\optional. can use multiple cooking tools at once to finish one portion of the recipe? how many tools are usable at once, base cooking time is divided by this number
"cooking_split_tools": yes, 2
\\optional. how much energy it consumes in comparison to  water of the same volume, where 100 = intensity required to boil water. determines power usage of heat source
"cooking_intensity": 40
```

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
