### ISSUE TITLE
Automatically wield smokables

### ISSUE THREAD

**Issue by Entity-y** [CleverRaven/Cataclysm-DDA#50936]
# Is your feature request related to a problem? Please describe.
Lit smokables remain inside of the inventory. This to me just seems like I'm burning a hole inside of my pocket. 

# Describe the solution you'd like
Automatically wield the lit smokables if hands are free.

# Describe alternatives you've considered
Treat lit and unlit smokables like a wearable piece of mouth clothing that when equipped could free up hands for other things.

# Additional context
There is a sprite for smoking a cig when it's wielded but I would have never of noticed if not for just trying it out.

**Comment by Entity-y** [comment]
Currently if I'm wielding an unlit cigarette and light it, the lit cigarette spawns inside of my inventory rather than in my hands.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
