### ISSUE TITLE
The current way the game has you get down from a roof is incredibly unintuitive. New players miss it regularly.

### ISSUE THREAD

**Issue by RandDenner** [CleverRaven/Cataclysm-DDA#50940]
I find it extremely unintuitive that I can simply push the “ascend” key to go up on a drainpipe, but the “descend” key along the edge, even adjacent to the drainpipe square, does nothing.
If you’re over a drainpipe top graphic, it should work more like stairs.
I died once when first starting to play the game because I couldn’t figure out to “examine” the empty air spaces to climb down. And that’s a very odd use of the examine command, I believe the only one where you functionally examine empty space. And it’s also kind of dumb to have to do it to jump down. And it pops up a selection box to choose between climb and jump down every time as well? Cumbersome and unintuitive.

Here's my thoughts on an improved system.
(I believe all of this could also apply to ladders in some situations. I don't know if ropes are implemented for climbing as yet, though.)

**Climbing down:**

1) if you are orthogonally adjacent to a drainpipe square and push the "descend" key, you should just climb down the drainpipe, ignoring the possibility of climbing down any other nearby edges. This makes it simpler for the player, since if they maneuvered to the square adjacent to the drainpipe there are few to no cases where they were not doing so in an interest of climbing down it.
Also, if you are diagonally adjacent to a drainpipe square, but **not** adjacent to any other edge square, it should act in exactly the same way.

2) if you are adjacent to an edge **_and_** diagonally adjacent to a drainpipe and push the "descend" key, a selection box asking to choose between "climb down nearby drainpipe" and "climb down" could pop up. If there is more than one choice of non-drainpipe square, a yellow square selection box should appear asking the player to choose the square to climb down, omitting the drainpipe from the selectable squares (kind of how examining the squares now has you select one of the squares that are highlighted.)
If there is only one possible square for selection, once the player has confirmed they wish to climb down, it should just do it .

3) if you use the “descend” key command at an edge **without** a drainpipe adjacent in any way, it should jump directly to the part in (2) above where it asks you if you want to climb down, then prompt you to select a space if there is more than one choice.
Again, if there is only one possible square for selection, once the player has confirmed they wish to climb down, it should just do it .

5) attempting to move off the edge without pressing the descend command key should indicate that the player wishes to jump.
They should get a selection box with the choices "jump down" and "jump off roof", and if there is a nearby roof, the second option should change to "jump across".
The player does not need to select a square option because the attempted move selected the target square/direction already.
However, it has been suggested that the option to "climb down" should **_also_** be offered in this circumstance as well, since players may not know of the usage of the "descend" key in this circumstance, or just wish to use an initially simpler method of choosing the target square by movement.

Anyway, all that would make it simpler for everyone and more intuitive for new players. In Discord and Forum posts about this, several players mentioned that they had this issue as well.

![image](https://user-images.githubusercontent.com/73523034/130303761-cbf5cdb4-f5b7-4909-951b-ef7e95263ee2.png)

I would code it, but I don’t know how…

**Comment by MagratGarlick** [comment]
+1 on this one. A makeshift solution would be just make the downpipe (ie. the tile you're supposed to `e` with) more visible & examineable - IIRC its already currently showing in a highlighted white different from all other random dots?

**Comment by chrispikula** [comment]
Also, if you have a grappling hook in your inventory, you _need_ to use it to descend.  There's a pop up asking if you'd like to use it, and if you choose not to, you stay on the roof.

**Comment by kwl01skz** [comment]
In addition, when we climb up an area with a grappling hook, we can't disassemble the grappling hook on the upper layer, but only on the lower layer. In fact, it should be the opposite, or it should be allowed to be disassembled in two cases.

**Comment by leemuar** [comment]
oh wow, I didn't know we can do that :)

**Comment by LeahLuong** [comment]
#54555 closed #54561 & prob should have closed this issue, too. Also, not sure kwl01skz's comment was implemented in the PR:

> In addition, when we climb up an area with a grappling hook, we can't disassemble the grappling hook on the upper layer, but only on the lower layer. In fact, it should be the opposite, or it should be allowed to be disassembled in two cases.

Testing in 0.F-3, I was able to recover the hook from ground level but not the Z-lvl above. Throwing the hook up I was able to safely ascend & descend multiple times. Standing on the upper lvl w/ the hook in my inv, examining the ledge prompted me to use the hook to climb down & this happened:

![Screenshot_20220127-134450](https://user-images.githubusercontent.com/91638992/151470183-20487d2c-6546-4a85-9fa9-d0da25dad7c4.png)

Is this intended behavior??

**Comment by Venera3** [comment]
Why would you test an experimental change in stable? In a fresh experimental having and choosing to use the grapple (you can decide to not use it and try your luck otherwise) bypasses the slipdown chance calc, so it won't happen. Recovering the hook from upstairs and going down with `>` would certainly be nice to have, but they were out of the scope of that PR.

**Comment by LeahLuong** [comment]
@Venera3 I was unable to tell from the PR if bypassing slippage was changed. If it weren't, my testing would've found a current issue I'd have filed a report. As you can prob tell from the screenshot, I did employ the hook & subsequently fell.

I suppose this issue should be left open, then.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
