### ISSUE TITLE
Error while trying to mend a faulty engine, action is not completed

### ISSUE THREAD

**Issue by NancokPS2** [CleverRaven/Cataclysm-DDA#50942]
### Describe the bug

When trying to mend an automotive filter using a normal (non makeshift) automotive filter part, the game gives an on-screen error and causes nothing to happen, the filter is not consumed
The error appears AFTER the specified time for mending (5 minutes of work)

### Steps To Reproduce

1. Attempt to mend an engine with the required part nearby
2. Select the only option in the list that pops up "Replace expired fuel filter"
3. Wait for the process to complete
4. Get a screen wide error (log in additional info below)

### Expected behavior

The filter is consumed and the engine looses the faulty suffix

### Versions and configuration

- OS: Windows 10
- Game Version: 2ead586 
- Graphics version: tiles
- Ingame language: English
- Mods loaded:   "dda",  "no_npc_food",  "aftershock",  "alt_map_key",  "StatsThroughSkills",  "stats_through_kills",  "crt_expansion",  "Cata++",  "Mining_Mod",  "speedydex",  "No_Fungi",  "blazeindustries",  "MMA",  package_bionic_professions",  "No_Rail_Stations",  "Mutation_Changes",  "useful_helicopters",  "extra_mut_scens"

### Additional context

DEBUG    : invalid arguments to ACT_MEND_ITEM

 FUNCTION : void activity_handlers::mend_item_finish(player_activity*, player*)
 FILE     : src/activity_handlers.cpp
 LINE     : 2647
 VERSION  : 2ead586

**Comment by freijie** [comment]
Exactly the same happens when I tried to mend faulty CBMs.

Mods loaded: dda, np_npc_food, package_bionic_professions, aftershock, aftershock_exoplanet, blazeindustries, MMA, No_Rail_Stations, Graphical_Overmap, No_Fungi, speedydex, stats_through_kills, StatsThroughSkills

**Comment by RoyBerube** [comment]
I did not test this exact problem, but is probably fixed by merged PR #50957.

**Comment by NancokPS2** [comment]
Gonna be honest, i'm going to forget about this issue again and let it go stale, so i'll just close it and open another if the issue persists since the PR seems to adress these issues
