### ISSUE TITLE
integer overflow in train() when training archery/marksmanship.

### ISSUE THREAD

**Issue by Tamiore** [CleverRaven/Cataclysm-DDA#50941]
### Describe the bug

When I try shooting a bow with these skill values:
![image](https://user-images.githubusercontent.com/61312205/130304619-38d5fdaf-18ce-4134-b442-32a8866e2ff5.png)

I get these errors (one error for archery, one for marksmanship):

`DEBUG    : integer overflow in train() amount=155 catchup_modifier=2.04167 knowledge_modifier=1.275 level_gap=1 catchup_amount=1.#INF knowledge_amount=1.#INF scaling=1 _exercise=-2147483648`

`FUNCTION : void SkillLevel::train(int, float, float, bool)`
`FILE     : src/skill.cpp`
`LINE     : 250`
`VERSION  : 1f0d81e`

+

` DEBUG    : integer overflow in train() amount=153 catchup_modifier=2.04167 knowledge_modifier=1.275 level_gap=1 catchup_amount=1.#INF knowledge_amount=1.#INF scaling=1 _exercise=-2147483648`

` FUNCTION : void SkillLevel::train(int, float, float, bool)`
` FILE     : src/skill.cpp`
` LINE     : 250`
` VERSION  : 1f0d81e`

And __no skill training occurs__.

### Steps To Reproduce

1. Shoot at bow at something.
2. Get an error message.

### Expected behavior

Skills should train, errors should not occur.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 1f0d81e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Hope [no_hope],
    Rural-Only Mapgen [ruralbiome]
]

### Additional context

This only happens with archery+marksmanship. Melee skills train fine under the same circumstances. 
Does not matter if I shoot at an empty space or at an actual mob.

**Comment by BrettDong** [comment]
Could you please upload the save?

**Comment by Tamiore** [comment]
> Could you please upload the save?

[Burnwillows Creek.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7024589/Burnwillows.Creek.zip)

**Comment by eltank** [comment]
Thanks, @Tamiore! That debug message was exactly what I was hoping someone would send in. This should help us narrow down the cause. The code I added earlier today just makes it so that when the bug is triggered you won't get stuck with a ridiculous negative xp value.

**Comment by Tamiore** [comment]
Is there a way to manually reset your skill to "safe default" (via debug mane or something)?
Resetting it to 0 would be better than this situation...

**Comment by MagratGarlick** [comment]
that was fast, sweet!

**Comment by eltank** [comment]
> Is there a way to manually completely reset your skill to "safe default" (via debug menu or something)?
> Resetting it to 0 would be better than this situation...

You can, by editing your save file. But I'm hopeful that we can get this bug squashed by tomorrow.

**Comment by Tamiore** [comment]
> You can, by editing your save file. But I'm hopeful that we can get this bug squashed by tomorrow.

Ok, sounds good. I'll wait a bit. Good hunting o7

**Comment by MagratGarlick** [comment]
From a glance it would seem the cause could be _knowledgeExperience gained before _exercise for reasons, then exercise() / knowledgeExperience() flew out from window?

**Comment by eltank** [comment]
I got it, it's division by 0 in `skill.cpp` L222. It uses the non-raw value for `knowledgeExperience` which is rounded to the nearest %, which is 0 in this case.
But even if it did use the raw value, 0 knowledge xp is still possible. So the formula needs to be changed (still thinking about what to change it to).

**Comment by Tamiore** [comment]
> From a glance it would seem the cause could be _knowledgeExperience gained before _exercise for reasons, then exercise() / knowledgeExperience() flew out from window?

Can it be that releasing the arrow triggers _knowledgeExperience gain while arrow hitting the target (or just hitting _something_) triggers _exercise?

**Comment by eltank** [comment]
Oh, actually 0 is not possible due to the condition (_knowledgeExperience > _exercise). So the bug is really just computing with rounded values instead of raw. That's easy to fix.

**Comment by eltank** [comment]
Alright, I used your save file to confirm the fix and I'll have a PR up shortly.

**Comment by eltank** [comment]
So in general, the way this bug was triggered was by having a little bit of xp progression on a skill, while still showing up as 0%, then having your practical xp fall below the theoretical xp (via rust, which happens at midnight). Then the next time you practice that skill you either get a huge boost or a huge negative due to the division by 0.
Normally integer division by 0 crashes the game, but this was floating point, which generates "floating point infinity", which when added back to an integer causes overflow.

**Comment by MagratGarlick** [comment]
I think skill rust is probably not the only cause as the world I experienced this had skill rust turned off (and recent enough that that setting is respected) - but this one should fix it nevertheless whatever the cause. 

Thank you!

**Comment by actual-nh** [comment]
> I think skill rust is probably not the only cause as the world I experienced this had skill rust turned off (and recent enough that that setting is respected) - but this one should fix it nevertheless whatever the cause.

I think it was having read a little bit so your theoretical xp went slightly above your practical.
