### ISSUE TITLE
Combat Engineer missing reasonable proficiencies

### ISSUE THREAD

**Issue by YourCompanionCube** [CleverRaven/Cataclysm-DDA#50955]
### Describe the bug

Combat Engineer only has basic gunsmithing

### Steps To Reproduce

Look in the character creator

### Expected behavior

Based on the description of the combat engineer profession it should start with proficiencies relating to spotting, setting, and disarming traps as well as perhaps some construction related ones like welding 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: bd2ce6b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Gun Cotton [guncotton],
    Stats Through Skills [StatsThroughSkills],
    Useful Helicopters [useful_helicopters],
    SpeedyDex [speedydex]
]

**Comment by RandDenner** [comment]
This is a legitimate complaint.
Along with construction and maintenance, combat engineering specialists also handle mines and such.
