### ISSUE TITLE
mission_arrow_up and mission_arrow_down not displayed in tile overmap

### ISSUE THREAD

**Issue by Fris0uman** [CleverRaven/Cataclysm-DDA#50962]
### Describe the bug

mission_arrow_up and mission_arrow_down are not displayed in tile overmap and use the uknown sprite even in tilesets that have a sprite set up for it like Retrodays.

The id used in retrodays appears to be the correct one and yet it's not displayer in game.

### Steps To Reproduce

1. Get a Mission
2. Move on overmap to the mission
3. Move one layer up or down
4. Get the unknwon sprite instead of the arrow

### Expected behavior

arrow up and down showing up properly

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: Please install `git` to generate VERSION [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]
]

**Comment by olanti-p** [comment]
Possible fix: https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1101/commits/e577404b62a1d61b9c987a3f2a5c2373ffcb379f
