### ISSUE TITLE
Moving lots of stuff with Advanced Inventory doesn't interrupt quickly enough when attacked

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#50979]
### Describe the bug

When mass moving items from one container to another, you can get hit multiple times by a single zombie before you have even the opportunity to stop and respond

You should have the opportunity to see a zombie coming and stop.
Even if you were to claim "you were distracted" as soon as they hit you it should interrupt, you would not stand there and let them keep whacking you just so you can finish moving a pile of leather patches

### Steps To Reproduce

spawn a tile full of leather patches
spawn zombies at varying ranges
try moving all the leather patches
note that it doesn't give you the opportunity to interrupt when it should

### Expected behavior

if there's no zombie within 25 tiles when I start moving items, I would expect to be able to stop moving stuff and prepare for combat when a zombie is within close range (2-5 tiles), not let it attack me multiple times before I bother doing something about it.

### Screenshots

![image](https://user-images.githubusercontent.com/12039454/130345257-e2c6749a-616e-4c95-ada2-7e87ff22ab0b.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 73374dd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills]
]

**Comment by Xpyder** [comment]
another example without the blindness debuff:
![image](https://user-images.githubusercontent.com/12039454/130345517-69603c5b-2267-4306-9b13-ce68bf7721aa.png)

**Comment by StStep** [comment]
I found this happens too when unloading containers with a lot of items

**Comment by anothersimulacrum** [comment]
Can this be reproduced after https://github.com/CleverRaven/Cataclysm-DDA/pull/51041?

**Comment by hexagonrecursion** [comment]
I can reproduce this in 119e2fe, but not in f7e3308. This bug appears to have been fixed by #54672. @wapcaplet, IMHO This bug should be closed.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 119e2fe [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: f7e3308 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
