### ISSUE TITLE
Error about "skill_points" when starting a new game with a preset character

### ISSUE THREAD

**Issue by eltank** [CleverRaven/Cataclysm-DDA#50976]
### Describe the bug

Character templates created before #50772 are now giving JSON errors when trying to start a new game with that preset.

### Steps To Reproduce

1. Build at bf3398f27a4bd8b26b97a9f87254068db8bbf2bc (the commit before #50772 was merged)
2. Create a new world, then create a custom character
3. Before finishing character generation, press `!` to save the character as a preset
4. Build at 5343061b497a2fa3a9d733b2cc2772dacf7d70a9
5. Try to start a new game with the preset character
6. Errors

### Expected behavior

I don't know what the backwards-compatibility policy is for preset character json files, but I would expect to not get errors.

### Screenshots

![image](https://user-images.githubusercontent.com/8000047/130343845-a0518fc8-65e0-426e-b436-35bdb6fd0070.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 5343061b [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7026641/debug.log)

The errors can be skipped, can't tell if anything bad happens.
Saving a new preset over the old one makes the errors go away.

**Comment by hexagonrecursion** [comment]
I know how to fix this. I'll get right on it.
