### ISSUE TITLE
Magiclysm parkour effect

### ISSUE THREAD

**Issue by Juafr** [CleverRaven/Cataclysm-DDA#50981]
### Describe the bug

Wearing items like the freerunner's boots, should give you the parkour proficiency, but it doesn't. It gives this error when trying to wear them.

 DEBUG    : invalid trait id "PARKOUR"

 FUNCTION : const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]
 FILE     : src/generic_factory.h
 LINE     : 442
 VERSION  : 8051d7d

### Steps To Reproduce

1- Spawn the freerunner's boots.
2- Wear them.
3- Ignore the error. 
4- Walk over a counter.
5- Check the movements used.

### Expected behavior

Wearing the boots should give you the parkour proficiency making it so the moving cost to walk over a counter and the like is the same as walking over flat terrain.

### Versions and configuration

- OS: Windows 10 Home
    - OS Version: 20H2
    - Windows Compilation 19042.1165
- Game Version: 8051d7d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm]
]

### Additional context

I think the problem is the changes in traits, the boots are described to give the mutation PARKOUR, but now Parkour is a proficiency.
in enchanted_boots.json:

"relic_data": {
      "passive_effects": [
        { "has": "WORN", "condition": "ALWAYS", "mutations": [ "PARKOUR" ], "values": [ { "value": "MOVE_COST", "add": -5 } ] }

All the items that give parkour and similar should be bugged the same way.

**Comment by actual-nh** [comment]
Ping: @KorGgenT?

**Comment by anothersimulacrum** [comment]
Fixed in https://github.com/CleverRaven/Cataclysm-DDA/pull/51488
