### ISSUE TITLE
[0.F stable] Preplanted farm fields remain plowed after harvest, but player planted ones do not

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#50982]
### Describe the bug

Farm fields are now mostly planted with corn, but there are unplanted prepared tiles in the rows. Plant something with a reasonably short growing time in such tiles and wait for the corn to be ripe for harvest. Harvest both the corn and the PC planted tiles, and not that there are now gaps in the rows of furrowed ground where the PC planted crops grew.

### Steps To Reproduce

The description is basically a reproduction recipe...

### Expected behavior

Harvesting should behave in a consistent manner, i.e. either all furrowed tiles should revert, or none should, with the former presumably being the intended result.

### Screenshots

![Screenshot (9)](https://user-images.githubusercontent.com/22739822/130348430-7f59685e-f883-4a8e-aeaa-253bfcaf0889.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

The issue isn't restricted to corn, but can be seen at any pre planted areas, such as community farm areas.

Looking closely at the screen, I can see that the pre planted tiles have a furrowed background, while the player planted ones do not. I suspect the issue arose when farms changed from being furrowed ground with harvested crops lying on top of it to planted fields. In that transition, the planted tiles should probably have had their furrowing removed, while the unplanted ones should keep it (or, if that's too hard to implement, not being furrowed, although that would increase the difficulty of first year farming).

**Comment by anothersimulacrum** [comment]
It is as you said - when a player manually farms, the plowing is removed when a seed is planted. Here, it was not removed when the farms were converted from being empty to planted.
