### ISSUE TITLE
Freshwater Research Station - problems with autogenerated roof and ladder hole

### ISSUE THREAD

**Issue by RandDenner** [CleverRaven/Cataclysm-DDA#50998]
### Describe the bug

Since there is no roof level defined for the freshwater research station, one is apparently auto generated.
Since the main floor has a down ladder, a hole is auto-generated above it, even though it's a ladder down.
The player can use the ascend command, and it's treated as climbing, with a prompt for climb direction.
This is odd, since the player can't just climb any old edges. The auto-generated hole is being treated as a climbable ledge (confirmed in screenshot, below when (x)amined).
However, if the player attempts to climb down the hole, it always results in a severe fall, since the game disallows usage of the ladder from the lower level, and the player falls two levels to the base (where the up-ladder is).

### Steps To Reproduce

Just go to one and try it yourself.
It works exactly as I've described above.

### Expected behavior

Really, auto-generated roofs should not auto-generate holes over down-ladders.

Additionally, this particular template "freshwater_research_station.json" could have a defined roof level added to the template in the meantime.

Actually, even though the auto-generation needs to be fixed either way, it would be best to make a defined roof in the .json, adding in a ladder top with a "t_grate" surround, and a number of greeblies like an antenna, satellite dish, and cell antenna ("f_TV_antenna", "f_small_satelitte_dish", "f_cellphone_booster") at the three corners for verisimilitude.

(I believe I've seen this same problem in other situations involving a step-ladder in a bike shop from 0.F. I still have the save, so I'll go and look.)

### Screenshots

Surface level:
![image](https://user-images.githubusercontent.com/73523034/130365473-67129753-a904-49ab-96f9-6b14e575e6be.png)

When pressing ascend key:
![image](https://user-images.githubusercontent.com/73523034/130365653-0f34ceb0-eec4-4d15-a468-93d81f522795.png)

Autogenerated roof:
![image](https://user-images.githubusercontent.com/73523034/130365493-9b1d36e8-5209-487d-a678-3b8c552d596a.png)

(x)amining roof hole from above:
![image](https://user-images.githubusercontent.com/73523034/130365594-65e37571-a26d-4240-8ed4-0fd16897b626.png)

(e)xamine hole:
![image](https://user-images.githubusercontent.com/73523034/130365770-f218efa4-5b1f-4384-b174-c4d12990e711.png)

Select "climb down":
![image](https://user-images.githubusercontent.com/73523034/130365694-0d7f079a-67dd-45e7-a209-2c32f28aa576.png)

### Versions and configuration

- OS: Windows 10
- Game Version: 0.F-1
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: none, 100% default worldgen

**Comment by hexagonrecursion** [comment]
Confirmed: there is a hole in the roof

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 8051d7d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by RandDenner** [comment]
@actual-nh, please remove "needs confirmation tag" re: above post
