### ISSUE TITLE
Error during world loading/generating

### ISSUE THREAD

**Issue by CalmTechie** [CleverRaven/Cataclysm-DDA#50994]
### Describe the bug

Error being thrown after choosing world generation parameters and starting generation. (right after list of loading files/modes appears)

### Steps To Reproduce

1. Clear all game data and reinstall game package
2. Start creating new world leaving all parameters default
3. Wait a couple of seconds while world is generating
4. Errors being thrown (example in screenshot) with various 'itype' fields: 'gloves_fingerless', 'gloves_bag', ect.

### Expected behavior

World generated. Character creation screen.

### Screenshots

![2021-08-22-182206_1435x298_scrot](https://user-images.githubusercontent.com/38151004/130361635-d5e14fd4-d67f-458c-92c7-7688dfdd5a7a.png)

### Versions and configuration

- OS: Arch Linux x86_64
- Game Version: 0.F (package version 0.F.1-1, from arch community repository)
- Graphics version: terminal
- Ingame language: English
- Mods loaded: tried with bare game without mods, but default bionic mod changes nothing

### Additional context

Game package updated couple of days ago, but previous version was 0.F as well. Initially, I had a created world from the previous version of the package.

**Comment by RandDenner** [comment]
Tested as steps to reproduce, 0.F-1 Windows tiles 64 bit version. Could not reproduce in that OS & version.

Must need a specific test using Arch Linux x86_64, package version 0.F.1-1, from arch community repository.
I cannot do this at this time as I don't have that distro (or any Linux) installed.

**Comment by ZhilkinSerg** [comment]
They refer to an invalid commit hash for 0.F-1. That tag was updated since it was originally created.

**Comment by hexagonrecursion** [comment]
Was probably fixed by af757339fb9541cb0cdff87d8a9b49679e424121.

**Y u mov tag?** This is what happens when you move tags

**Comment by ZhilkinSerg** [comment]
Tag is on the commit it should be on.
