### ISSUE TITLE
Allow character being NPC,  when playing other character in the same world

### ISSUE THREAD

**Issue by linonetwo** [CleverRaven/Cataclysm-DDA#50990]
# Is your feature request related to a problem? Please describe.

In Magicalism you can't be some magic class at the same time. And in reality, it is hard to be both a top computer scientist and a medical/mechanical expert.

- But in CDDA, a player tends to let his character have every ability, because there is only him.
- And ask NPC to learn and practice is not as straightforward and satisfy as ask player-controlled character to learn and practice

# Describe the solution you'd like

If you create two characters in the same world, when you play one character, you can see the other character being NPC in the world, and can get into your car to travel around.

When facing a problem, you can switch to a different character to learn&practice skills, and use their different skill to solve different in-game problems.
This I think, may give this game more tactic when building a character, and being more realistic. And I think this will encourage player to experience as much game content as possible, while not using over power mods or cheating. 

# Describe alternatives you've considered

Allow "attach" to a NPC, give direct control to it.

# Additional context

We some players are talking about how to maintain a satisfying experience as game playing duration is extended.

**Comment by Zireael07** [comment]
IIRC something very similar has been proposed (something like having a fleet of your previous NPCs...?)

**Comment by Entity-y** [comment]
This would be the best addition as it's a much better alternative to dying and completely losing hours of progress(or having to close the game). The game would end when everyone in your faction is dead. There could also be opportunities to reanimate freshly dead characters via magic, medicine or technology to continue playing as them once again.

Character files would need to be updated simultaneously to prevent a temporal paradox between saves, perhaps merge character saves to a single world save. Starting the game as a particular character would continue where they as a NPC left off. 

The perfect solution would be to allow changing characters in real time, without having to return to the main menu and generating the world in between swapping characters. The colony sim game Rimworld is a good example of how this could all work out.

**Comment by Brambor** [comment]
Hive mind!

**Comment by eltank** [comment]
While not exactly what you wanted, you might be interested in #51450.

**Comment by linonetwo** [comment]
Continue the discussion at https://github.com/CleverRaven/Cataclysm-DDA/issues/51632 , as eltank is the active developer for this and has a comprehensive design of a new mechanism.
