### ISSUE TITLE
Practice Activity

### ISSUE THREAD

**Issue by StStep** [CleverRaven/Cataclysm-DDA#50999]
# Is your feature request related to a problem? Please describe.
While the new rust mechanic which splits practical and theoretical knowledge has potential, I think it's a bit too tedious and gamey to have to level up some practical skills now. For example, mechanics, the best way to be able to work on your car is to just remove and install a simple part, like a tire or battery, repeatedly until you have the level you want. This requires a lot of tapping of keys to do and feels weird from a verisimilitude level. Previously, you could spend a couple of days reading, which while taking a lot of in-game time, is efficient use of player time. With the crafting focused skills with a low barrier to entry, this is less of an issue because the player could just batch craft 100 makeshift bandages. It's relatively player time efficient, but it is still lacking a bit in verisimilitude. Additionally, with the split of books, the question of when to use books vs when not has gotten more confusing. Why bother reading a mechanics book if you can't use your knowledge skill anyway? Having a knowledge skill higher than your practical skill helps the practical raise faster, but is it worth the time to read up to knowledge skill one and then craft up to practical skill one? Why not just craft up both skills at the same time, is it that much slower?

# Describe the solution you'd like
I would like to do the following:

- Make activities the primary way to gain skill
    - Create a new practice activity
    - Will replace nonsensical actions such as replacing inserting batteries
    - Will be real world time efficient for player
    - Give players a clear method to reach that one craft they can't do yet
- Create a more clear way for the player to efficiently use books
    - Books should make learning easier
    - Allow incorporating books into practice, which I'm calling guided practice, to give them a clear benefit to the player
- Maintain gates on player skills based on items and time
    - I like requiring the player to find books or certain tools to be able to progress their skill
    - Have tiers of tools and books, which kind of already exist
    - Player shouldn't be able to just hide, and practice their skills up to max

So to the player, the following activities will exist:

- Reading Activity - gain theoretical skill, requires book of appropriate tier
    - Do this when you don't have access to the proper tools or materials
- Practice Activity (New) - gain practical skill, requires tools of appropriate tier and might consume spare parts
    - Do this if you don't have a book, basically experimentation
- Guided practice (New) - Requires both a book and tools and might consume spare parts
    - Best way to learn, use if you have a book and materials

The player could still batch craft a 100 makeshift bandages or battery swap to gain levels, but players, especially new ones, will now have a clear way to raise their practical skills. 

# Describe alternatives you've considered

N/A

# Additional context

## Skill Implementations and Gating

I don't consider myself well versed in how to use all the skills, especially social and computers which I haven't ever really used, so here are some of my ideas of how practice might be gated based on tools or resources.

As far as the tiers themselves, I’m also open to ideas. We should also try to unify nomenclature around novice, beginner, expert, etc. I don’t want to make tiers too complicated, and I want them to fit nicely into how books are organized without conflating ‘book tier’ and ‘practice tier’

Books are kind of sorted like the following (taking mechanics as an example):

- 0-1: Popular Mechanics, easy reading
- 0-3: Under the Hood, basic reference
- 3-6: Mechanical Mastery, advanced reference
- 4-8: Internal Combustion Engine, highly technical

Required tool qualities are cumulative, and should roughly line up with what you need to perform recipes or actions of that tier.

Other requirements would be like having a vehicle you can work on for mechanics, people around for social, or a laptop and encrypted SD cards for computers. I think we should also use tool charges and spare parts for the high up tiers of non-craft skills and then for all tiers of craft skills. For example, you use up metal sheets and welding charges for practicing mechanics at high tiers, and cotton clothing patches for practicing tailoring at lower tiers, and then zippers or kevlar for higher tier tailoring practicing. Basically, I’m trying to balance skills that require a lot of different tools, like mechanics, with skills that require less tools but a lot of materials, like tailoring.

## Mechanics Example

Tier | End Level Range | Req. Book | Min Req. Tool Qualities | Other Req.
-- | -- | -- | -- | --
Tier 0 | 1 |   | Bolt Turning 1, screw driving 1 | Vehicle
Tier 1 | 2-3 | Under the Hood | Wheel Fastening 1 and Jacking 3 (or str) | Vehicle with engine
Tier 2 | 4-5 | Mechanical Mastery | Bolt Turning 2, Welding 1, glare protection 2, metal sawing 1 | Vehicle with working engine, uses welding charges
Tier 3 | 6 | Mechanical Mastery | Welding 2, metal cutting 2 | uses welding charges, uses up sheet metal
Tier 4 | 7 | Internal Combustion Engine |   |  

## Combat Skills

Some combat skills, like throwing and archery seem like they would be easy to practice with since targets already exist in the game. But I feel like you shouldn’t be able to practice too much combat skills without actual opponents, and unlike other skills, combat isn’t normally the boring part of the game, so I think it would be okay to only be able to practice up to like tier 2 without an opponent. I think this would be a good opportunity for adding a sparring activity that you could do with NPCs. Alternatively, we could let the player construct weird equipment, like those spinning martial arts wooden things, boxing bags, or skeet throwers.

## Proficiencies

I’m honestly not sure how to fit proficiencies in, since they are leveled alongside but separately from skills. Maybe you could flavor practicing, like practicing with leather vs zippers for leather working proficiency vs closure proficiency? This might be fine being handled by batch crafting.

**Comment by StStep** [comment]
Linking older practice feature that I didn't see before writing this: #28283

**Comment by StStep** [comment]
After reading through the other issue, I think that one works better with proficiencies, and the craft menu seems like nice place to put this kind of thing. My proposal inherently focuses on skills by themselves and not applications of those skills. Like I was proposing just having practice mechanics, but with the other one you could have practice welding, practice on car electronics, practice removing/taking out components, to cover the overlap mechanics has with fabrication, electronics, or just mechanics by itself.

The one thing I think it's missing is taking into account practical and knowledge skills being separate, and focusing on books, since that feature wasn't implemented yet.

In any case, I think the new knowledge mechanics means implementing some kind of practice feature is much more in demand now.

**Comment by kevingranade** [comment]
Redundant with #28283
