### ISSUE TITLE
"folded inflatable boat" very different from inflatable boat

### ISSUE THREAD

**Issue by angryisosceles** [CleverRaven/Cataclysm-DDA#51005]
### Describe the bug

An inflatable boat weighs 20 pounds. A "folded inflatable boat", the item you get from folding an inflatable boat, weighs 72 pounds. Additionally, you need a hand pump to inflate an inflatable boat, but not a folded inflatable boat.

### Steps To Reproduce

Get an inflatable boat
Inflate it
Fold it
Inflate it again (you won't need a hand pump)

### Expected behavior

I expected that folding an inflatable boat would give an inflatable boat (the item used to create it) back. Alternately, a folded inflatable boat should weigh less.

### Versions and configuration

- OS: Windows 10
- Game Version: e055bd1
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: default

**Comment by hexagonrecursion** [comment]
Confirmed
- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 8051d7d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by hexagonrecursion** [comment]
Related: https://github.com/CleverRaven/Cataclysm-DDA/issues/46752
