### ISSUE TITLE
IFAK pouch always has description as empty, even when it isn't

### ISSUE THREAD

**Issue by RandDenner** [CleverRaven/Cataclysm-DDA#51000]
### Describe the bug

IFAK pouch description assumes it's empty, even when full.

### Steps To Reproduce

Look at a full, unopened IFAK pouch.

### Expected behavior

The description shouldn't assume past tenses and states.

### Screenshots
"used to contain"? It still does (look at the bottom)
![image](https://user-images.githubusercontent.com/73523034/130367218-38d14c98-2057-4122-a090-8a429a1352cf.png)

### Versions and configuration

- OS: Windows 10
- Game Version: 0.F-1
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: none

**Comment by RandDenner** [comment]
Checked the descriptions in containers.json in both 0.F-1 and the latest experimental. They match.
There are three of these used/past tense errors:
1) survival kit box
![image](https://user-images.githubusercontent.com/73523034/130370287-af5912f9-c16f-4e03-a9aa-c7b2ae1a1ef4.png)
2) first aid kit box
![image](https://user-images.githubusercontent.com/73523034/130370301-4e4902e1-37b0-4422-9bb2-77adff568969.png)
3) IFAK pouch
![image](https://user-images.githubusercontent.com/73523034/130370332-21060680-e266-42d7-a350-990c895c6aa6.png)

4) this RC car box may also need an adjustment for the description, since the box may have previously been unpacked and enjoyed...
![image](https://user-images.githubusercontent.com/73523034/130370428-6219a7f5-a97d-436f-af72-0230c046c623.png)

**Comment by kitsaws** [comment]
New here!
May I pick this up?

**Comment by RandDenner** [comment]
I make no claim on it. Go ahead if you want to run with it. I'm working on something else, anyway.

**Comment by kitsaws** [comment]
![bag_body_bag](https://user-images.githubusercontent.com/85405400/130557095-a666b9ea-7ee9-4421-b4f2-0070e1c5030d.png)
What about this item?

**Comment by RandDenner** [comment]
I believe it means that it IS used to hold a dead body, not that it held one.
Perhaps "They are used to store a dead body." is clearer?

**Comment by kitsaws** [comment]
Ok. 
And which variant of English is used in the descriptions, **American** or **British**? I see the spellings are mostly American.

**Comment by RandDenner** [comment]
It's set in American New England, so that would be the clear preference.

**Comment by RandDenner** [comment]
@kitsaws , I see you've made a commit.
![image](https://user-images.githubusercontent.com/73523034/130562002-e0d7d78d-709e-4e8f-a467-ba9c464c582c.png)
But saying it **_contains_** something is as bad as saying it **_used_** to.
Because they may be empty or repurposed.
"...designed to hold..." is probably a better phrase.

Also, what about the RC car box. Same issue, basically.
"This is a box for..." at the beginning basically fixes it.

**Comment by kitsaws** [comment]
Oh, changing.
Also, there are other minor grammatical changes possible. Should I include these?
![Editing Cataclysm-DDA containers json at containers-grammar-fix · kitsaws Cataclysm-DDA (2)](https://user-images.githubusercontent.com/85405400/130562836-7f6f40a2-0b4b-41ea-b880-d7b4e62a41da.png)

**Comment by kitsaws** [comment]
The large_survival_kit_box and thermos have the same issue.

**Comment by RandDenner** [comment]
I looked over what you propose.
I think line 991 is better the old way with the delusions comment, and in North America, we never put a dash between the numbers and the unit (2.5 liter, never 2.5-liter), but other than that, I think it's all good.
I'll look at your new commit when you make it.

**Comment by kitsaws** [comment]
@RandDenner 

> 
> 
> I looked over what you propose.
> I think line 991 is better the old way with the delusions comment, and in North America, we never put a dash between the numbers and the metric unit (2.5 liter, never 2.5-liter, but strangely I have seen 50-gallon...), but other than that, I think it's all good.
> I'll look at your new commit when you make it.

I don't think this is a North American issue.

- This is a bottle which may hold 2.5 liters of liquid.
- This is a 2.5-liter bottle.

Did you see the difference?
Anyway, I have removed the hypens.
