### ISSUE TITLE
Why do IFAKs contain water purification tablets but no pain relievers or antiseptic?

### ISSUE THREAD

**Issue by RandDenner** [CleverRaven/Cataclysm-DDA#51006]
### Describe the bug

The title says it all

### Steps To Reproduce

Look at one. Or look below. I just grabbed this from one in an army warehouse in 0.F-1

### Expected behavior

Bandages are nice, but pain relievers would be critical after the wounds are bandaged. Antiseptic isn't critical, but what kit doesn't have some antiseptic solution or powder?

Water treatment tablets _**aren't**_ emergency first aid...

### Screenshots

![image](https://user-images.githubusercontent.com/73523034/130370924-d17719f7-50fe-4803-929d-fffe6a844639.png)

### Versions and configuration

Win10, Tiles, 0.F-1, English, no mods.

**Comment by hexagonrecursion** [comment]
Confirmed
- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 8051d7d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by DalenTalas** [comment]
The purpose of an IFAK is to quickly stop bleeding / stabilize trauma in a combat situation, where more thorough treatment is often impossible. This serves to keep the soldier alive until they are transferred to a secure area for more thorough treatment. In the meantime, the soldier is either already unconscious from pain, or can suck it up for the duration.

Refer here for the contents of a typical IFAK https://www.military.com/equipment/individual-first-aid-kit-ifak

Suggested alternative: No change, or remove water treatment tablets altogether.

**Comment by DalenTalas** [comment]
So, add powdered antiseptic? From my experience, the IFAK in the game is already well-stuffed.

**Comment by RandDenner** [comment]
Yeah, I'd add a bottle of antiseptic powder (ID: bfipowder).
Matches expectations of anyone familiar with the IRL kits better.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
