### ISSUE TITLE
Runtime Error Inserting Items

### ISSUE THREAD

**Issue by RockNShoulders** [CleverRaven/Cataclysm-DDA#51001]
### Describe the bug

Posting on behalf on someone else:

Runtime errors occurs when trying to insert a stack (19) of boiled bandages inside of a toolbelt.

### Steps To Reproduce

1. Get a toolbelt.
2. Set category whitelist to ammo for all toolbelt pockets.
3. Insert small bottle (with antiseptic in the bottle) inside the toolbelt's first pocket,
4. Manually insert bandages into the toolbelt.
5. Runtime error occurs.

### Expected behavior

No runtime error.

### Screenshots

![unknown](https://user-images.githubusercontent.com/88957626/130367423-a94e4de6-d8a1-490b-84dd-09b0da7d3e0b.png)
![unknown](https://user-images.githubusercontent.com/88957626/130367443-31dab89e-4fb2-4ef6-99dc-f3ae2880067c.png)
![unknown](https://user-images.githubusercontent.com/88957626/130367448-1368a084-e68b-4fa5-8bdc-5565e4423f9c.png)

### Versions and configuration

- OS: Windows
- Game Version: bc28921
- Graphics version: Tiles
- Ingame language: English

### Additional context

NA

**Comment by actual-nh** [comment]
#47856 might be related.

**Comment by mqrause** [comment]
It's an issue coming from the category whitelist. The issue was fixed with #49318 which got backported into Frank-1, so it shouldn't happen anymore with the lastest stable release.

**Comment by RockNShoulders** [comment]
> 
> 
> It's an issue coming from the category whitelist. The issue was fixed with #49318 which got backported into Frank-1, so it shouldn't happen anymore with the lastest stable release.
> Edit: definitely doesn't happen on [8051d7d](https://github.com/CleverRaven/Cataclysm-DDA/commit/8051d7d8ca05fd1b2ace9ca695f6ef04c476fcf7).

I'll communicate this to other person and close the issue then. Appreciate you looking into it.
