### ISSUE TITLE
Use JSON Schema to define JSON format

### ISSUE THREAD

**Issue by linonetwo** [CleverRaven/Cataclysm-DDA#51012]
# Is your feature request related to a problem? Please describe.

We don't have a portable (that can port to different language) description about what JSON format we accept, it is mostly embedded in the C++ code. And doc about JSON is sometimes incomplete.

And even use C++ to write 3rd party tool, we can't directly use a C++ SDK to speed up the JSON loading part development. Which is the most time-consuming part of tools about CDDA.

# Describe the solution you'd like

Use JSON Schema to define the JSON that CDDA accepts, other 3rd party tools can generate code from JSON schema using https://transform.tools/json-schema-to-protobuf this kind of tools.

# Describe alternatives you've considered

Or maintain SDK for different languages, but this can also be autogenerated if we have JSON Schema.

# Additional context

I'm creating a map editor for CDDA, but adapting its JSON is a hard job, and later maintain it to keep update with experimental is human resource consuming.

**Comment by ZhilkinSerg** [comment]
See https://github.com/CleverRaven/Cataclysm-DDA/issues/42986, https://github.com/CleverRaven/Cataclysm-DDA/pull/34735, https://github.com/CleverRaven/Cataclysm-DDA/issues/10965

**Comment by linonetwo** [comment]
Okay, maybe generate JSONSchema from C++ code later, generate from an internal struct.
