### ISSUE TITLE
Error on loading saved world after today's update 

### ISSUE THREAD

**Issue by Hoppywhite** [CleverRaven/Cataclysm-DDA#51017]
### Describe the bug

 DEBUG    : invalid overmap special id "FakeSpecial_s_lot"

 FUNCTION : const T &generic_factory<overmap_special>::obj(const string_id<T> &) const [T = overmap_special]
 FILE     : /var/lib/jenkins/workspace/Cataclysm-Android/android/app/jni/src/../../../../src/generic_factory.h
 LINE     : 436
 VERSION  : 0.F-1

______________________________________________________________________________________________

 DEBUG    : invalid overmap special id "Mass Grave"

 FUNCTION : const T &generic_factory<overmap_special>::obj(const string_id<T> &) const [T = overmap_special]
 FILE     : /var/lib/jenkins/workspace/Cataclysm-Android/android/app/jni/src/../../../../src/generic_factory.h
 LINE     : 436
 VERSION  : 0.F-1

### Steps To Reproduce

Load saved game

### Expected behavior

No errors

### Versions and configuration

- OS: Android 11 on Samsung S5e
- Game Version: latest stable
- Graphics version: default tiles
- Ingame language: English 
- Mods loaded: DDA, StatsThroughSkills,

**Comment by ZhilkinSerg** [comment]
Just ignore these errors and continue playing.

**Comment by MagratGarlick** [comment]
`Tried to use an invalid beta talker. `

`Unable to find and assign mission target lab_res_8_NW`. 

It'd look like something's wrong w/ migration which should warrant a fix by itself, _and_ now I'm getting spontaneous "Remain in place, unauthorized person. Security has been activated" message, _and_ the game is crazy slow: moving one step takes one second IRL time (comes with one Remain in place message)

**Comment by schealex** [comment]
same problem here:

![image](https://user-images.githubusercontent.com/3441348/130455150-86de0289-4d08-4c9a-83b7-26fbed934ccf.png)

**Comment by RandDenner** [comment]
Procedure for deleting unnecessary queued_effect_on_conditions (all beginning with lab_ or bot_) from saves fixes the issue as far as messages and other related weirdness (gas clouds) goes.

It's in a single line in your world save directory, in the file ending in .sav.
Make sure you get the whole of each entry, beginning with a { all the way to the },<space> at the end.

Deleting the entire "queued_effect_on_conditions" line will likely work as well, but I cannot confirm that it win not mess something up in your save unrelated to this issue. Most saves have no queued effects, but some might.

**Comment by Hoppywhite** [comment]
> Just ignore these errors and continue playing.

thanks for the quick response

**Comment by Hoppywhite** [comment]
thank you

**Comment by ZhilkinSerg** [comment]
> 
> 
> `Tried to use an invalid beta talker. `
> 
> `Unable to find and assign mission target lab_res_8_NW`.
> 
> It'd look like something's wrong w/ migration which should warrant a fix by itself, _and_ now I'm getting spontaneous "Remain in place, unauthorized person. Security has been activated" message, _and_ the game is crazy slow: **moving one step takes one second IRL time** (comes with one Remain in place message)
> 
> I thought the lab drone message was fixed in #50920, hrm.
> 
> @ZhilkinSerg : save-and-reload as suggested in [#50977 (comment)](https://github.com/CleverRaven/Cataclysm-DDA/issues/50977#issuecomment-903286699) does nothing to stop either the message or slowness.
> 
> build: `51520f6`. Guess I'm reverting back to `73374d` for now.

Issues you are referring to are completely unrelated to current issue. That ticket #50977 is not closed yet and was only partially fixed in #51002
