### ISSUE TITLE
Found something odd with relative stats of bandages, adhesive bandages, and gauze

### ISSUE THREAD

**Issue by RandDenner** [CleverRaven/Cataclysm-DDA#51013]
### Describe the bug

Bandages in 0.F-1 and the latest experimental have this data in the med.json file (combined here for clarity):
![image](https://user-images.githubusercontent.com/73523034/130393901-7dfb627a-0119-4772-a46b-624a503051a9.png)
Note how adhesive bandages only have a charges stat (10), bandages have a charges stat (3) _AND_ a stack size stat (9), and gauze has neither.

What happens is, since adhesive bandages have a charges stat of 10, when there is a stack of 10 of them, that's when the volume, price, and barter value (price_postapoc) reach the values set in the .json file. Weight from the .json is simply multiplied by the raw number, though (40g each x 10 is 400g or 0.40kg).
These are the in-game stats as a result:
(Note that my character's medical stat is set to 20, so the two lines for "actual effect" values in the info panel are maxed out. Ignore those lines.)
![image](https://user-images.githubusercontent.com/73523034/130394356-8db1ea08-a3cc-4d44-a7a2-cf4ca1ce5753.png)
10 of them are $6 to purchase and $2 to sell. Which is more or less reasonable considering they neither bandage or stop bleeding very well (bandage of 1, bleed of 4).

Since gauze has neither a charges stat or a stack size, it's just straight-up multiplication for 10 of them:
![image](https://user-images.githubusercontent.com/73523034/130394564-d7fee12f-8ca9-4c36-b787-85d6ca2de224.png)
$35 and $20 respectively. Yeah, you can make adhesive bandages and splints using them, but that price is pretty shockingly high when you consider the bandage value of 4 (equal to bandages) and the bleed value of 5 (1 better than adhesive bandages, and 2 better than cotton balls, but 1/3 that of bandages). Also a stack of 10 is 2000mL (2L) of volume and weighs 900g (about 2 pounds!). That's very bulky and heavy!

Where it gets strange is with regular old bandages. Remember they have a charges stat (3) _AND_ a stack size stat (9). The charges seems to do nothing, but the stack size acts like the charges stat does for adhesive bandages. When you have 9 bandages is when the volume and the prices match those set in the med.json:
![image](https://user-images.githubusercontent.com/73523034/130394907-b85b88a1-878d-4be2-8939-c7c7f348a79d.png)
So, 9 of them only take up 250mL, weigh 630g (about 1.4 pounds), and only cost $6 to buy and sell for $2. They bandage as well as gauze (bandage 4) but are three times better at stopping bleeding (bleed 15). They take up an 1/8th of the volume, weigh 2/3ds as much and cost about 1/6th to buy.

Frankly, these values are all not meshing well. 9 bandages and 10 adhesive bandages cost the same, but adhesive bandages are 4 times **_worse_** than bandages in every way (except for being about 2/3ds the volume and weight).
Then you have gauze, which can make splints, but are way too much volume and are ridiculously expensive in comparison to the other two. They're as good as bandages for bandaging, but way worse at stopping bleeding, so why is the price so high?

Frankly, all these values look like they were added by different people at different versions and none of it meshes well any more.

And what _**does**_ the charges entry in bandages _**do**_ anymore that isn't overridden by the stack size?

Lastly, "_**consume time**_" ???
Wat?
Who's **_eating_** them?
Seriously though, they all have a "NO_INGEST" flag (along with a bunch of other supplies like medical tape and cotton balls and such). The info panel should probably not display that "consume time" stat for items with that flag. They already show the correct time to use them lower down in the healing effects section.

### Steps To Reproduce

This is all from the json file data and game info panels. You can double check them yourselves.

### Expected behavior

I would expect that the relative stats would make sense when compared, but when you look at all three together, you see that no matter how you compare any two of them, the third is way off.

Also, the bleeding effect of gauze and adhesive bandages is only one point different, gauze being 5 and adhesive bandages being 4 (bandages is 15 and hemostatic powder is 20) but calling the one _small_ and the other _minuscule_ in the infopanel obscures the difference, which is actually pretty insignificant. Both are almost equally bad at stopping bleeding. Cotton balls alone are a bleed value of 3.

As a suggestion:
Bleed values of 1 to 7 should be "poor" - cotton balls (3), adhesive bandages (4), and gauze (5)
values of 8 to 13 should be "average" - makeshift/homemade bandages (10)
values of 14 to 18 should be "good" - medical bandages (15)
19 and up should be "excellent" - hemostatic powder (20) and, strangely, topical cocaine cream (also 20 ?)
(Is a cocaine cream _really_ that good at treating bleeding?)
The maximum level seems to be "outstanding" (not sure what number range that represents), but no matter what a medical wizard you are, should things with little inherent ability to stop bleeding _really_ be able to reach that level? Maybe clamp the max value to triple the base or something.

This needs a rebalance, and a bugfix for the info panels, and maybe the bandages having both charges and stack size needs revisiting as to whether these are both useful stats together.

### Versions and configuration

Win10, tiles, English, v0.F-1 and/or latest experimental (checked both), default settings & no mods

**Comment by RandDenner** [comment]
> Consume time means application time.
These have a defined application time. Look in the info panel under Healing effects: "Moves to Use"

**Comment by Maleclypse** [comment]
> > Consume time means application time.
> 
> These have a defined application time. Look in the info panel under Healing effects: "Moves to Use"

Oh yeah I remember MurderUnicorn recently mentioned on one of his videos that all the healing items had both a consume time and a moves to use time and it wasn't always clear which was the amount of time your character would actually take to use said item.

**Comment by RandDenner** [comment]
Okay, so I've been giving this a lot of thought, and I have a start.
1) uses aren't necessarily individual pieces. Like 1 gauze isn't necessarily a whole roll, and neither is one adhesive bandage a single bandage, since they come in various sizes and you may use one big one or a bunch of small ones to do the same job. One bandage is more or less one bandage, I think, though.
2) starting with some basics, $2 barter value for 10 applications of adhesive bandages is a decent base. Bandages are 4x as good, so should be 4x more ($8). Gauze isn't as good in all ways, but is still pretty useful, so say 70% of bandages or so. Call it $6.

### Adhesive bandages 20 cents each application, bandages (medical grade) $1 each, and an application of gauze for 80 cents sounds about right to me.

**Comment by RandDenner** [comment]
Oh, and this is a factor as well:
![image](https://user-images.githubusercontent.com/73523034/130551553-4e90636c-3ff3-4a8d-bc9e-c875f3a6fe2c.png)
5 gauze making 10 adhesive bandages may need to be changed slightly.
Plus:
![image](https://user-images.githubusercontent.com/73523034/130551699-64bc63fa-dd79-40a2-b094-9060fd19ab78.png)
and
![image](https://user-images.githubusercontent.com/73523034/130551740-cf5ff653-ac57-4296-9f15-6dde8e9419b5.png)
but that seems like about the right amount of gauze, given my estimation of a 10cm x 100cm strip being an application.

**Comment by chrispikula** [comment]
I _think_ the idea with medical gauze is that since once you open the package, it no longer remains sterile.  So if it has multiple uses, those future uses shouldn't be considered sterile.  

There's opportunity here to make a paper package for it, activatable into a transform of multiple single application gauzes, but have them have an transform timer upon spawn into a cotton sheet after some time to represent no longer being sterile.

**Comment by RenechCDDA** [comment]
All bandages are now defined as single items - no stack sizes, no charges.
