### ISSUE TITLE
Safe mode lets me get too close to a wolf

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#51018]
### Describe the bug

Initially a wolf is "Ignoring". While the wolf is in this state safe mode **and fast travel** do not consider it a threat resulting in me walking until I'm 5 tiles away from it. At that point the wolf switches to "Tracking" and safe mode stops me, but it is too late: even if I immediately start walking in the opposite direction sometimes the wolf switches to "Hostile" and catches up to me.

### Steps To Reproduce

1. Spawn a wolf
2. Turn safe mode on
3. Walk towards the wolf until safe mode stops you
4. Try to walk away - sometimes the wolf becomes hostile and eats you

### Expected behavior

Expected safe mode to be safe

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 8051d7d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

I think at least one other canine monster is affected, but I don't remember which one.

**Comment by Night-Pryanik** [comment]
> Expected safe mode to be safe

That's too vague. 
What do you expect? To safe mode saying "don't come close to the wolf"?

**Comment by hexagonrecursion** [comment]
I expected the safe mode to warn me about the wolf as soon as I saw it the same way it warns me about a moose for example.

**Comment by Little-119** [comment]
If you'd like, you can customize what sets off safe mode with the safe mode manager.

For this, you can add `*wolf` with 'attitude' set to `Any` to the safe mode manager rules

**Comment by NetSysFire** [comment]
I think the issue is that some monsters become hostile if you get close. Safemode does not know about this. It would get annoying if you got warned about every wasp or wolf minding its own business in the forest while you are just driving past.

This might be a wontfix.

**Comment by hexagonrecursion** [comment]
> while you are just driving past.

Isn't safe mode ignored while driving?

> It would get annoying if you got warned about every wasp or wolf

It is more annoying to die because safe mode + hold move key or auto move resulted in me finding myself in an unsurvivable situation.

> If you'd like, you can customize what sets off safe mode with the safe mode manager.

Customization is nice, but I would prefer safe mode and auto move to be safe by default.

> I think the issue is that some monsters become hostile if you get close

Idea: add a fourth monster state: "about to get angry". For the purposes of monster behavior it should be the same is "tracking", but safe mode and auto move should treat it as "hostile". Instead of jumping straight to "hostile" monsters should go through the new state for long enough to give the player an opportunity to retreat,

**Comment by LeahLuong** [comment]
I believe there's a setting toggling whether safe mode is active while driving.

I have to agree w/ hex here: some monsters shouldn't be able to skirt safe mode as they currently can. IRL, most people wouldn't walk up to a wild wolf they can plainly see, only stopping when it's a couple of paces away growling @ them. Those same people would be even more wary of dog-sized wasps. Safe mode needs some way of recognizing these types of threats before they go hostile as a default. As it stands, some1 who's killed by it might think safe mode malfunctioned or was temporarily deactivated & end up dying to it again. Many players prob don't know about the safe mode manager & of those who do, an even smaller set would think to change their settings after experiencing this sort of setback, or even know how.
