### ISSUE TITLE
Cooked mutant organs recipe and item issues

### ISSUE THREAD

**Issue by ERRORCODE509** [CleverRaven/Cataclysm-DDA#51016]
### Describe the bug

Mutant lungs, livers, kidneys, and brains can be "cooked" without any tools or requirements, and the cooked version of each is still considered to be raw.

### Steps To Reproduce

1. Create a character with food handling 1
2. Search any of the aforementioned recipes in the crafting menu
3. See that they don't require tools to craft and are still considered raw

### Expected behavior

That cooked mutant organs require normal cooking requirements and be considered cooked rather than raw.

### Screenshots

![image](https://user-images.githubusercontent.com/75010328/130400155-89939099-2dd6-41a7-9db8-4a99c5df0907.png)
![image](https://user-images.githubusercontent.com/75010328/130400239-f5be4d53-a6d3-45ff-8749-3135a258ebdb.png)
![image](https://user-images.githubusercontent.com/75010328/130400277-246ce7e4-f53f-47d5-b257-ce1d0c19c546.png)
![image](https://user-images.githubusercontent.com/75010328/130400312-6f083cfc-cd16-4691-8028-384c98e7df15.png)

### Versions and configuration

- OS: Windows 10
- Game Version: bea0650
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: 
[
  "dda",
  "no_npc_food",
  "package_bionic_professions",
  "aftershock",
  "blazeindustries",
  "crt_expansion",
  "magiclysm",
  "no_hope",
  "consume_the_nut",
  "convert_the_nut",
  "crack_the_nut",
  "crudeimprovised",
  "dihydrogen_monoxide",
  "fungi_nuke",
  "lube_the_nut",
  "MST_Extra",
  "Packaging",
  "pineapple_pizza",
  "return_the_nut",
  "survive_the_nut",
  "TGCNP",
  "more_survivor_stuff",
  "the_inquisitor",
  "crazy_cataclysm",
  "Mining_Mod",
  "extra_mut_scens",
  "MMA",
  "simple_additions",
  "Deconstruction_plus",
  "No_Fungi",
  "clean_cbm",
  "fuji_mpp",
  "magiclysm_no_class_limit",
  "manualbionicinstall",
  "portable_autodoc",
  "safe_autodoc",
  "safe_portable_autodoc",
  "speedydex",
  "stats_through_kills",
  "StatsThroughSkills"
]

### Additional context

Have verified that the recipe issue is still present in the current master branch, haven't checked the issue with the cooked organs being considered raw, however. Recipe issue seems to be caused by the use of `"copy-from"`, which correct me if I'm wrong, only works for items and not recipes.

**Comment by Venera3** [comment]
There's a reason I hate crafting stuff. I did test them for the PR, and I'm certain it complained about my fire going out but I'll take a look at it later today.
