### ISSUE TITLE
Can not interrupt dropping 100 rags

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#51022]
### Describe the bug

It current;y takes over 9 in-game minutes to drop 100 rags out of the inventory. While dropping the game says "dropping. press . or 5 to interrupt" but pressing . or 5 does nothing.

### Steps To Reproduce

1. Wear a watch
1. Wear a leather backpack
2. Put 100 rags into it
3. Drop the rags
4. Try pressing . 5 and numpad 5 while dropping

### Expected behavior

I expected dropping to be interrupted

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 8051d7d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

* If you are attacked while dropping the game does prompt to stop dropping and this works
* Related: https://github.com/CleverRaven/Cataclysm-DDA/issues/48937

**Comment by RandDenner** [comment]
Confirmed in experimental 8051d7d.
Also, dropping 200 plastic bags takes 8 minutes 58 seconds, while picking up only took 2 minutes 45 seconds.
That's not right.
Also, picking up was not only faster in game-time, but much faster in realtime as well.
