### ISSUE TITLE
Autodrive overmap pathing

### ISSUE THREAD

**Issue by MagratGarlick** [CleverRaven/Cataclysm-DDA#51020]
### Describe the bug

Not convinced this's the best way to drive...
![image](https://user-images.githubusercontent.com/3895319/130441656-dc4a2800-efdb-4a38-83ef-6105473073fa.png)

### Steps To Reproduce

1. Open map
2. Find a location(x1, y1) that's below you(x, y) and to the side, and also have some obstacles between (x, y1) and (x1, y1) ie: if you draw a horizontal line from destination and a vertical line from starting location, there are some forest tiles between the theoretical turning point and your destination (the horizontal line you draw)
3. Watch autopath attempts to get down to the same Y level, then curve back on X movement to avoid forest tiles

### Expected behavior

Stick to the road might be a better idea? Or the path of least resistance, or just..shortest path?

### Versions and configuration

- Game Version: 2eb4ed3

### Additional context

The new autodrive feature _is_ **awesome**, which is why I'm actually using it going from A to B on every chance, despite the fact that driving manually would save me quite a few in-game minutes time (due to autodrive reluctant to go higher than 19km/h and quite often insist on driving at walking speed), so natually #IWantMore! 

Additional info: Car, 100% offroad performance when this occurred. Load rocks onto the car to reduce its offroad performance might help to force it to stick to the road but thats a heretics solution, right?

**Comment by MagratGarlick** [comment]
(tagging @eltank pretty please)

**Comment by MagratGarlick** [comment]
sorry, it'd seem the commit right after my version already fixed this - closing

**Comment by eltank** [comment]
Yes, should be fixed by #50835.
