### ISSUE TITLE
Pickup dialog does not respect partial quantities

### ISSUE THREAD

**Issue by DalenTalas** [CleverRaven/Cataclysm-DDA#51023]
### Describe the bug

When picking up several items out of a very large stack, occasionally the dialog does not respect the quantity specified and picks up the whole stack.

Un-selecting the target item and re-selecting it after specifying a quantity will avoid this issue.

### Steps To Reproduce

1. Obtain 200 plastic bags.
2. Pick up 2 of them.
3. Observe character's inventory get stuffed with bags beyond specified quantity.
4. Repeat 1 and 2. Before confirming pickup, un-select the bags and re-select them specifying the quality.
5. Observe pickup happen as intended.

### Expected behavior

Quantities specified during pickup should be respected.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: e3199c8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations]
]

**Comment by RandDenner** [comment]
This sounds a lot like you are selecting the item first (making it have a +) then typing the number.

You can type the number before selecting an item, or even highlighting a line. You can even move up and down on the list before selecting the item and it will work correctly. The next item you select (by pushing right cursor) will have the number selected, and will show # instead of + as the selection indicator.

I just tested on 0.F-1 and cannot reproduce what you saw while using the "type the number before selecting the item" method that I just described.

(Checked this with plastic bags and found that picking up 200 of them only takes 4 minutes, while dropping them takes 9 minutes. That's weird and probably wrong.)

**Comment by RandDenner** [comment]
Just checked with experimental 8051d7d. Pickup behavior is working correctly with respect to number.

However...
Drop time for 200 bags remains a few seconds less than 9 minutes, but pickup time is now only 2minutes 45 seconds or so.
I am doing more specific testing to see if this is a difference in the versions.
I DO notice that 0.F-1 takes much longer to load a save, slowing noticeably at 3 points, where experimental loads at least 5x faster.
This is on the same SSD. 
Testing with the exact same duplicated save on both versions should work.

**Comment by DalenTalas** [comment]
No, I am using this exactly as you describe. Typing a number, selecting a line.

Maybe is has to do with a specific number? Will check later.

**Comment by RandDenner** [comment]
You have a quite old experimental version.
Perhaps try downloading a newer one and test in that?
I have the latest experimental and 0.F-1 running side by side. (Experimental uses the launcher, while 0.F-1 is gust run from a desktop shortcut.)

**Comment by hexagonrecursion** [comment]
> (Checked this with plastic bags and found that picking up 200 of them only takes 4 minutes, while dropping them takes 9 minutes. That's weird and probably wrong.)

This is a known bug https://github.com/CleverRaven/Cataclysm-DDA/issues/48937

**Comment by hexagonrecursion** [comment]
Confirmed

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: e3199c8 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by hexagonrecursion** [comment]
Confirmed
- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 51520f6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by hexagonrecursion** [comment]
Unfortunately I can't find a reliable way to trigger this making troubleshooting difficult

**Comment by RoyBerube** [comment]
It could be the result of unintentional muscle memory. 'E'xamining with just one valid location nearby automatically opens the dialog box for that location. But without realizing it you might press a direction button on the numpad. Then when you press '2' and right arrow to pick up 2, you might get 42 by mistake.

**Comment by RandDenner** [comment]
I believe in the default setup, only the cursor keys work, not the keypad directions.

**Comment by mqrause** [comment]
Is this still a thing with the new menu?
