### ISSUE TITLE
Cannot open MRE after today's update

### ISSUE THREAD

**Issue by Hoppywhite** [CleverRaven/Cataclysm-DDA#51029]
### Describe the bug

MRE was simple to open and heat before my software updated today. Now I can't find a way to open the MRE without turning it into plastic chunks. Please help.

### Steps To Reproduce

Activate MRE.

### Expected behavior

Drop contents of MRE.

### Versions and configuration

- OS: Android 11 on Samsung S5e
- Game Version: current stable
- Graphics version: default tiles
- Ingame language: English
- Mods loaded: dda, StatsThroughSkills

**Comment by ZhilkinSerg** [comment]
MREs are containers - [U]nload them

**Comment by Hoppywhite** [comment]
> MREs are containers - [U]nload them

thank you!

**Comment by Hoppywhite** [comment]
Issue reopened because MRE do not appear in the (U)nload menu

It is no possible to open an MRE pack

**Comment by Hoppywhite** [comment]
In the (a)use item menu the "Get Content" option gives "You cannot dissemble this"

**Comment by Qrox** [comment]
I also had this problem with MREs from an old save. I no longer have that save but I think it's because the old MRE items are obsoleted instead of migrated to the new MRE package. (See `json/items/obsolete.json`). I think you can specify the content to add when migrating an item but I'm not sure if it supports nested containers.

**Comment by Hoppywhite** [comment]
> I also had this problem with MREs from an old save. I no longer have that save but I think it's because the old MRE items are obsoleted instead of migrated to the new MRE package. (See `json/items/obsolete.json`). I think you can specify the content to add when migrating an item but I'm not sure if it supports nested containers.

Thanks for the feedback

**Comment by hexagonrecursion** [comment]
Confirmed. I created a save with MREs in 0.F https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/0.F and loaded it in 0.F-1 https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/0.F-1 could not open MREs after that.

The most likely culprit is #48827. The same change also caused #50932

**Comment by ZhilkinSerg** [comment]
It was spawned before the update.

**Comment by RandDenner** [comment]
Noticed that the "no hope" mod generated old-style MREs and IFAKs due to old IDs present in mapgen json files.
