### ISSUE TITLE
Controlling dogs with a whistle needs some improvements

### ISSUE THREAD

**Issue by RandDenner** [CleverRaven/Cataclysm-DDA#51032]
So, controlling dogs with a whistle needs some work.
Want an exercise in frustration?
Get one dog and put him in passive mode, pick up 2 more dogs and they start in aggressive mode.
Now blow the whistle. It's a toggle, so all dogs that hear it change to the other state of whichever they're in. You wanted them all passive or all aggressive, but it's not possible unless you lead the odd one(s) way away and change their state without the rest hearing.

### Easy fix:
Blowing a whistle opens a selection "set to aggressive", "set to passive". Affects all animals that hear it.

### Better but more complicated fix:
What are the things you want animals to do?
1) stick close and don't fight. (also acts as a come back and follow me closely command)
2) stay close and only attack things that are close. (5 squares from player is plenty)
3) attack the nearest threat at any range.
4) stay here and guard this spot. (only attack aggressives that close within 5 squares of the spot where the whistle was blown)
5) go home. (this requires a home spot be set with a zone, I would think)
6) guard a large home area. (as per the settlement/zones stuff already in the game)

**Comment by RandDenner** [comment]
Also suggested: using your voice
1) talking to the dogs like they're an NPC
2) yelling group commands if you don't have a whistle

**Comment by PLUUZ** [comment]
To order dogs around so precisely  would require extensive training and/or greater levels of sentience than dogs have currently achieved, I think. (Dog owners can correct me).

#50890 this code adds walking a dog or other pet with a leash, but it isn't clear to me that it actually restricts the dogs movement beyond 2 tile distance from the player; it seems that the player automatically drops the leash if the dog rushes off to attack something.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
