### ISSUE TITLE
Fungal Patch with Fungi Disabled

### ISSUE THREAD

**Issue by StStep** [CleverRaven/Cataclysm-DDA#51042]
### Describe the bug

I'm was playing my game with the fungi blacklist mod and found a fungal patch. It was about 20 by 20 squares of fungal beds and was in a random area near a road. It just had some of the fungal bushes on it. There was no landmark on the overworld map for them.

### Steps To Reproduce

I spawned a character to try and find another example (because I died from nether spawns in the original save) and couldn't find any. I'm not sure how to find another example.

### Expected behavior

I don't expect fungal patches when the no fungi blacklist mod is is on

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 51520f6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi]
]

**Comment by StStep** [comment]
It's possible the fire attracted them? I was doing a lot of waiting for it to burn up? I tried recreating by forcing fungal patches to spawn in a no fungi world by spawning the bloated fungal zombies and killing them. But nothing happened other than normal fungi stuff.

**Comment by Venera3** [comment]
One of the portals spawns a patch of fungus before starting spewing the usual nether nasties.

**Comment by eltank** [comment]
The fungal bed is hardcoded in C++ as a possible outcome for a portal map-special and it's not easy to change that.
But as long as you're not getting fungal monsters or spores popping up, the mod is doing what it's intended to do.

**Comment by StStep** [comment]
Okay, cool that makes sense. I was mostly just very confused. I'll close this issue then.
