### ISSUE TITLE
Disassembling a leather jacket is ridiculously taking too long

### ISSUE THREAD

**Issue by jeffplata** [CleverRaven/Cataclysm-DDA#51049]
### Describe the bug

Disassembling a leather jacket takes a very long 7 in-game hours for harvesting 18 leather patches, 30 threads, and 1 long plastic zipper. IRL that would be done in 20 minutes tops 30 with the proper tool.

### Steps To Reproduce

1. Have a leather jacket around nearby or in-person for disassembling with ( key
2. The leather jacket will be listed to take 7 hours to complete disassembly

### Expected behavior

The time to disassemble the leather jacket should be considerably shorter.

### Versions and configuration

Version: experimental

**Comment by actual-nh** [comment]
It would be very nice if someone could locate some RL info on how long it takes to do stuff with leather - the current times seem to be either rather too long or rather too short.

**Comment by Ryan7251** [comment]
yeah seems a little long but i don't know how leather works...

**Comment by Entity-y** [comment]
It's probably taking so long because the recipe is turning part of the jacket into thread. Cutting the jacket to salvage the leather would likely take seconds.

**Comment by jeffplata** [comment]
> 
> 
> It's probably taking so long because the recipe is turning part of the jacket into thread. Cutting the jacket to salvage the leather would likely take seconds.

Probably. Would it be possible to disregard the threads when disassembling the leather jacket? There are better sources for threads, I believe. Those would be the cotton based shirts etc. It would be nice and faster if leather jackets and the likes be the source of primarily leather patches, but not threads.

**Comment by Entity-y** [comment]
Maybe change the deconstruct recipe to drop rags instead of thread and shorten the time a couple hours

**Comment by hexagonrecursion** [comment]
Confirmed. Cutting up a leather jacket takes 3 seconds but only gives you leather patches. Disassembling a leather jacket takes 7 hours.
- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 2970a2f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by anothersimulacrum** [comment]
Needs an explicit uncraft recipe.
