### ISSUE TITLE
Installing and uninstalling gun mods seems to be reversed

### ISSUE THREAD

**Issue by Aeiouuu01234** [CleverRaven/Cataclysm-DDA#51057]
### Describe the bug

when trying to install a mod in a gun the requirements where that the gun needed to be at least 1 charge, which contradicts previous versions that make you discharge the gun before any modifications.

Makes things difficult when trying to modify a weapon with no ammo and makes the bow modifications imposible to install 

### Steps To Reproduce

Get a bow or a gun
discharge it
try to install a weapon mod
prompt says you need at least 1 charge 

### Expected behavior

it made sense when you have to discharge a gun before modifying it or cleaning, so i hope it gets resolved

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: f1e2e5a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Crazy Cataclysm [crazy_cataclysm],
    Mythical Martial Arts [MMA]
]

**Comment by anothersimulacrum** [comment]
Fixed in https://github.com/CleverRaven/Cataclysm-DDA/pull/50319
