### ISSUE TITLE
Crafting Components not Visible

### ISSUE THREAD

**Issue by FindusCrispyPancakes** [CleverRaven/Cataclysm-DDA#51058]
### Describe the bug

When attempting to craft 'tinder', and you have the following components to choose from: plank, splintered wood and paper, once you are prompted to select which component you would like to use, the selection box doesn't display the names of the components.
![Components missing](https://user-images.githubusercontent.com/89490508/130699716-2b15e01b-b589-45c8-a5e4-d31f848241d6.png)

### Steps To Reproduce

1. Start a game using build 2021-08-24-1245 f1e2e5a
2. Have plank, splintered wood and paper in your inventory
3. Attempt to craft 'tinder'
4. You will see the components are not showing up like they used to.

### Expected behavior

I expected to see the list of available components I can choose from.

### Screenshots

![Components missing](https://user-images.githubusercontent.com/89490508/130699979-6bf8bd6d-6fc3-46c4-a3d2-05f0f5815c7c.png)

### Versions and configuration

- OS: Windows 10
- Game Version: 0.F 2021-08-24-1245 f1e2e5a
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: DDA, Disable NPC Needs, Bionic Professions

**Comment by actual-nh** [comment]
I believe #51055 is intended to fix this.

**Comment by anothersimulacrum** [comment]
Fixed in #51055
