### ISSUE TITLE
Weird Lab bug starting in 2021-08-21-2314.

### ISSUE THREAD

**Issue by Lee-Adamson** [CleverRaven/Cataclysm-DDA#51059]
### Describe the bug

The game loads alright, but as soon as I move, I get 
18:52:06.285 ERROR : src/npctalk.cpp:1362 [talker* dialogue::actor(bool) const] Tried to use an invalid beta talker.
 several times, as well as 
18:54:45.816 ERROR : src/mission_util.cpp:251 [cata::optional<coords::coord_point<tripoint, (coords::origin)1, (coords::scale)2> > find_or_create_om_terrain(const tripoint_abs_omt&, const mission_target_params&)] Unable to find and assign mission target lab_2x2_cargo_NE.
 (also get one for lab_2x2_cargo_NW, and some others, can send debug log if needed).

This goes on until I (i)gnore the messages.  At this point, the game spawns some concrete floors nearby, and spams these debug messages to the log while saying "Remain in place, unauthorized person. Security has been activated" 32 times per turn, with a great deal of lag.

Bug persists in current experimental at the time of this writing, 2021-08-24-1245.

### Steps To Reproduce

Update from cdda-linux-tiles-x64-2021-08-21-2146 to cdda-linux-tiles-x64-2021-08-21-2314.  Please ping me on Discord @Lee if you'd like a copy of my save game and/or debug logs, as I don't appear to be able to attach them here.

### Expected behavior

No weird lab spam and spawns.

### Versions and configuration

x86 Linux, Devuan Ceres

**Comment by actual-nh** [comment]
See #50977.

**Comment by RenechCDDA** [comment]
Duplicate, closing.
