### ISSUE TITLE
Can't cut long cordage ropes into short cordage ropes quickly (2 hours disassembly)

### ISSUE THREAD

**Issue by PLUUZ** [CleverRaven/Cataclysm-DDA#51052]
### Describe the bug

 long cordage ropes, disassembly takes 2 hours, whether it was made from cordage pieces or short cordage ropes, yielding whatever craft components the character originally used.There is no way to simply use a cutting tool to cut the long rope into short ropes in a matter of minutes

### Steps To Reproduce

Get a long cordage rope. Attempt to cut or disassemble it and note the time required.

### Expected behavior

Expect that when you want short cordage ropes, you could just cut a long cordage rope into pieces in a few minutes.

### Versions and configuration

- OS: Mac 10.11.6 (I know this isn't supposed to work anymore, but it does again for some reason)
- Game Version: F-1
- Graphics version: (edit: curses!) 
- Ingame language: English

**Comment by Zireael07** [comment]
That's because you're carefully disassembling it, not cutting it up.

**Comment by hexagonrecursion** [comment]
Confirmed: the game does not offer to cut up the long cordage rope. The [B]utcher menu only offers to disassemble the rope. Activating scissors to cut the rope up says "you have nothing to cut up"
- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 2970a2f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]
