### ISSUE TITLE
Json error while loading

### ISSUE THREAD

**Issue by Menschheit** [CleverRaven/Cataclysm-DDA#51065]
### Describe the bug

The field `activity_override` is not loaded.

### Steps To Reproduce

Load the game (with craft activity in backlog).

### Expected behavior

No error.

### Screenshots

![image](https://user-images.githubusercontent.com/28317565/130773769-a1f5fad5-b152-4ce3-80fe-02a6cf450f3e.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 2970a2f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

### Additional context

![image](https://user-images.githubusercontent.com/28317565/130773544-aed23449-f082-426d-a6c9-c51766764982.png)
in #50756

**Comment by ZhilkinSerg** [comment]
Please attach affected save game.

**Comment by Menschheit** [comment]
Save file:
[upload.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7046729/upload.zip)

**Comment by Menschheit** [comment]
Fixed by #51186
