### ISSUE TITLE
Can not drop frozen liquids

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#51069]
### Describe the bug

If you spill water on the ground and it freezes it it possible to pick it up by crushing it. This places it into your inventory (e.g. backpack). When open the [d]rop menu and try to select it - you can't.

### Steps To Reproduce

1. Spill water on the ground
2. Wait for it to freeze
3. Pick it up
4. [d]rop
5. Try selecting the frozen water - noting happens

### Expected behavior

It should be possible to drop the water

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 2970a2f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Originally reported here: #48806
Dropping via the item description UI does work

**Comment by Shados** [comment]
It looks like it is possible to drop it, but only via the advanced inventory management screen.
