### ISSUE TITLE
SD cards containing smartphone applications

### ISSUE THREAD

**Issue by Entity-y** [CleverRaven/Cataclysm-DDA#51064]
# Is your feature request related to a problem? Please describe.
Currently SD cards can contain pictures, songs, and recipes. While this was good for it's time, since then, we've had the addition of smartphones. This opens up the possibility of having applications that function as if you activated a specific tool.

# Describe the solution you'd like
These applications would add a new action to the smartphone and use varying amounts of power consumption to the phone's battery with each passing turn, making the smartphone an enjoyable yet balanced tool that would be rewarding for investing time into and also make SD cards highly sought after.

SD cards could have a chance of containing smartphone applications like:
- the newly added eBook reader and eBook scanner features
- random eBooks
- noise maker
- night light
- vibrator
- instruments
- video games
- board games
- maybe even a dog whistle

Encrypted SD cards could contain hacked applications like:
- RC car controller 
- vehicle controller 
- robot controller
- AI assistants that can train skills and proficiencies

# Describe alternatives you've considered
SD cards should also allow for transferring of applications, books, and the other stuff that they usually contain between devices. Prompting to copy, cut, or delete applications from a device when activating an empty SD card.

**Comment by Entity-y** [comment]
It might be best to have this feature exclusive to smartphones as some of the applications wouldn't make sense on a tablet or laptop. 

Could be a copy paste of the SD card, expanded upon with new applications, and renamed to micro SD card.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
