### ISSUE TITLE
Repeating tool requirements

### ISSUE THREAD

**Issue by TealcOneill** [CleverRaven/Cataclysm-DDA#51060]
### Describe the bug

A lot of tailoring recipes now list some required tools repeatedly. Particularly in the fur and leather working sections of armor/clothing. 
You do still only need 1 of that tool to fulfill the requirements though.

### Steps To Reproduce

Search through the Armor section of the crafting menu and you will/should see this.

### Expected behavior

I would expect that crafting only says it requires one of each tool, not multiples.

### Screenshots

![furboots](https://user-images.githubusercontent.com/45678006/130703949-9e1f3333-e9e6-4e0a-8ac4-424d285a59e6.png)
![heavysurvivorboots](https://user-images.githubusercontent.com/45678006/130703950-646e71b3-c6e2-4458-b885-9886a96cbd47.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: f1e2e5a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by Brambor** [comment]
Wow, I thought you need multiple tools, didn't think that would be a bug. I guess you never know!
