### ISSUE TITLE
Alcohol withdrawal effects are too intense

### ISSUE THREAD

**Issue by Little-119** [CleverRaven/Cataclysm-DDA#51063]
### Describe the bug

The effects of alcohol withdrawal are far too intense, which seems to be the product of a bug

Whenever the player starts experiencing alcohol withdrawal:

- the message log is spammed with messages
- the player will quickly accumulate turns of the 'shakes' effect. In a test, my character accumulated 21,309 turns (almost 6 hours) worth of the effect while waiting for 30 minutes
- The player character's morale will very quickly (within 5 minutes) drop to between -170 and -200

Going into withdrawal is extremely difficult to avoid; the player is given no warning before it happens.
Without extremely careful management, the player character will experience shakes 24/7

The drop to about -200 morale seems unintentional, as every message about the player 'needing a drink' appears to reduce morale by 3

### Steps To Reproduce

1. Make character with alcohol addiction
2. Wait for some hours
3. Observe results that occur in that time

### Expected behavior

Shakes should be temporary, only lasting for a few turns, not be practically permanent

The message log should not be spammed with messages. Though maybe it serves to give the feeling of addiction to the player

Alcohol cravings should be occasional as the messages said, one should not get the message 'You could use a drink' about every 10 turns.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: f1e2e5a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]

### Additional context

This might apply to other addictions. I haven't tested them.

**Comment by Little-119** [comment]
After reading the wiki page for addictions and testing some more, this seems like it mostly applies at high-intensity addictions. Starting addictions are apparently always at the apparent maximum intensity of 20.

Still, this means if you start with an alcohol addiction you'll accumulate a ridiculous amount of turns of shakes, and sating your addiction is not really a viable playstyle

**Comment by anothersimulacrum** [comment]
Is this still problematic after #51250?

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
