### ISSUE TITLE
JMAPGEN_SETMAP_BASH wont destroy furniture/impassable terrain

### ISSUE THREAD

**Issue by John-Candlebury** [CleverRaven/Cataclysm-DDA#51074]
### Describe the bug

JMAPGEN_SETMAP_BASH used in a few buildings to partially destroy them in a dynamic manner, will no longer damage impassable terrains or furniture, with only floor type terrain ever being affected.

### Steps To Reproduce

1. Spawn a collapsed tower basement and notice that the map walls are intact, with no partially destroyed terrains or rubble from terrain destruction.
2. Spawn a collapsed tower basement in a 0.F or a pre 0.F experimental and notice that the place is much more damaged.

### Expected behavior

Everything in the map is detroyed equitatively.

### Screenshots

Here is a the basement of the collapsed tower with all the walls and rock rubble intact, which doesnt allow you to reach the final room (lower right) from the elevator entry (upper right).

![image](https://user-images.githubusercontent.com/5290912/130816858-b17a2ef8-d5f9-4b2f-b7a8-76f1fb830ef2.png)

### Versions and configuration

- OS: Windows 10 
- Game Version:  0.f-1906-g51520f6245

- Mods loaded: dda

**Comment by Venera3** [comment]
Can confirm, the microlab firebreak variant spawning evolved mutants has the same problem.

**Comment by Night-Pryanik** [comment]
Looks like the issue was resolved some time in the past, as now locations with `bash` stuff are bashed like they should

![изображение](https://user-images.githubusercontent.com/11132525/196178401-8eef53bf-ec1f-4149-b850-9af44a137b4c.png)
