### ISSUE TITLE
Custard doesn't accept frozen ingredient

### ISSUE THREAD

**Issue by jorganmir** [CleverRaven/Cataclysm-DDA#51089]
### Describe the bug

When trying to make frozen custard, one cannot use frozen ingredients, such as frozen blueberries. Heating the blueberries alleviates this, but seeing as blueberries don't need to be cooked to be put into frozen foods, this seems to be an oversight or bug.

### Steps To Reproduce

1. get ingredients for custard
2. Get berries
3. freeze the berries
4. 4. observe crafting menu
5. heat up berries
6. observe crafting menu

### Expected behavior

Able to cook custard with frozen berries

### Versions and configuration

- OS: [ Windows 10 ]
- Game Version: 8051d7d (tiles)
- Graphics version: [Terminal]
- Ingame language: [English]
- Mods loaded: [e.g.dda, disableNPCneeds, Bionic Professions, graphical overmap, ]

**Comment by RoyBerube** [comment]
Adding the flag "EDIBLE_FROZEN" to the item allows it to be used in a cooking recipe. The small fruits being used in this recipe should really be edible frozen - I eat them like this all the time.
