### ISSUE TITLE
NPC Inventory / Loot Management

### ISSUE THREAD

**Issue by schealex** [CleverRaven/Cataclysm-DDA#51093]
# Is your feature request related to a problem? Please describe.
I really love to play with NPCs in CDDA but the way they handle loot is soooo tedious. Currently after my NPCs loot 100+ items one needs to manually take those items / or their containers off them and sort it away.

# Describe the solution you'd like
1) It would be great to have an option with the NPC menu to have them store / sort loot they don't use (wear / wield / meds?) in loot zones (or optionally just drop everything on the ground)
2) Maybe completly seperate but it would also be great if they where able to "upgrade" their gear. AFAIK they are already aware of some stuff e.g. if you give them a weapon that is worse than the one they are currently wielding they will refuse. Why not make some numbers be configurable via NPC menu (max. encumberence per bodypart / minimum dodge / prefer defensive values etc.) and have them upgrade their gear from the stuff they loot automatically

# Describe alternatives you've considered
The only alternative is the current way of doing it manually

I really think this would greatly improve the usability of NPCs in every playthrough.

**Comment by anothersimulacrum** [comment]
See #51120
