### ISSUE TITLE
About vitamin system

### ISSUE THREAD

**Issue by game2202018** [CleverRaven/Cataclysm-DDA#51094]
We are players which really like your game, and we find the vitamin system is no longer available after some tests and check CDDA browser. So we decide to check github to find out what is happening. After watched your discussion in #50273, we do believed that you think too compliacted for this system. The purpose of this system is force player to find various kinds of food, including meat, vegetable, fruit and so on. Only thing you need to do, is try to make a system look like enough "realism", and the player will try to fix it to reality by imagination. Like meat（VB, IRON）, vegetable（VA）, fruit(VC), that is enough for player. The symptom do not need too complicated, just show some influence or debuff（lower stat etc.） and player will do something, only thing you need to do is make the symptom enough "realism". But the calcium need to be fixed, because there are no too many way to get calcium in game, now you have to drink 4 milk per day to ensure your calcium is enough. We suggest that you can improve calcium of other food, so milk will not be the only way to get calcium. Hope CDDA will be funner in the future.

**Comment by kevingranade** [comment]
This has been addressed many times. The goal of dda is to present the challenges one would actually encounter in this scenario, not make up new ones, so if satisfying your vitamin requirements are trivial IRL, then they will be trivial or nonexistent in the game.

**Comment by game2202018** [comment]
Actually, we totally understand what you want to, and we do believe it is good for us too. We only suggest that present a simple vitamin symptoms first, and then you can fixed the symptoms and threhold value by new version, instead of delete most of the deficiency. But we totally understand your decision, if you want to make this by one time, that is great too. We will add the deficiency into vitamin.json to simulate this condition before you fix this problem, thanks for all of your hard working and this game is great and important for us.
