### ISSUE TITLE
Can no longer drop items in Advanced inventory management

### ISSUE THREAD

**Issue by cupnooodle** [CleverRaven/Cataclysm-DDA#51095]
### Describe the bug

Pressing <Enter> to drop an item no longer works, however you can still press <Enter> to pickup

### Steps To Reproduce

1. Press / to open advanced inventory management
2. Press <Enter> to attempt to drop any item 

### Expected behavior

Item should drop to respective square

### Versions and configuration

- OS: Windows 10
- Game Version: 0.F-1
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: Vanilla

**Comment by ZhilkinSerg** [comment]
Fixed in `0.F-2`
