### ISSUE TITLE
Refactor and reduce the size of Character class (character.h / character.cpp)

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#51106]
# Is your feature request related to a problem? Please describe.

The Character class defined in `src/character.cpp` is bloated with code that may be more appropriate in a separate class, file, or namespace.

# Describe the solution you'd like

Make `character.cpp` no longer the largest file in the `src` directory.

I expect the most logical way to accomplish this is to first identify functions that don't have a good excuse to be Character member functions - those that are not closely related to operating on a Character instance, or which are loosely coupled enough to be factored out into a different class or namespace.

Small bites at a time, over several PRs, is probably the way to go.

# Describe alternatives you've considered

I spent some time skimming through what we have, and making note of some potential candidates for refactoring or removal.

Armor:
- [x] get_armor_cut_base
- [x] get_all_armor_type
- [x] get_armor_bash_base
- [x] get_armor_bullet_base

Combat:
- [x] absorb_hit
- [x] armor_absorb
- [ ] deal_damage
- [ ] impact
- [ ] knock_back_to

Item interaction:
- [ ] invoke_item
- [ ] dispose_item
- [ ] item_store_cost
- [ ] item_retrieve_cost
- [ ] item_wear_cost

Others:
- [ ] base_comfort_value (~170 lines)
- [ ] siphon
- [ ] pour_into
- [ ] toolmod_add
- [ ] mend_item
- [ ] handle_contents_changed
- [ ] crush_frozen_liquid
- [ ] get_targetable_creatures
- [ ] check_mount_will_move
- [ ] check_mount_is_spooked
- [ ] get_book_reader
- [ ] get_book_mastery
- [ ] can_use_floor_warmth
- [ ] floor_bedding_warmth
- [ ] sleep_spot

More to move to `display` namespace (similar to  #50972):
- [x] encumb_color (no namespace)
- [ ] Character::body_window (many internals)
- [x] Character::limb_color
- [ ] Character::symbol_color
- [x] Character::bodytemp_color
- [ ] Character::short_description_parts
- [ ] Character::extended_description
- [ ] Character::print_health

Move out of `character.h` and `character.cpp` (moved to `contents_change_handler.h|cpp`)
- [x] `contents_change_handler` class and function definitions

Moved to `character_guns.cpp`:
- [x] get_ammo
- [x] find_ammo
- [x] find_ammo_helper
- [x] has_gun_for_ammo
- [x] has_magazine_for_ammo
- [x] gunmod_installation_odds
- [x] gunmod_add
- [x] gunmod_remove

Moved to `character_attire.cpp`:
- [x] change_side
- [x] layer_item (static)
- [x] is_wearing_power_armor
- [x] is_wearing_active_power_armor
- [x] item_encumb
- [x] wearing_something_on
- [x] is_wearing_shoes
- [x] is_worn_item_visible
- [x] get_visible_worn_items
- [x] is_wearing_helmet
- [x] head_cloth_encumbrance
- [x] armwear_factor
- [x] footwear_factor
- [x] shoe_type_count

Traps and snares (moved to `character_escape.cpp`):
- [x] try_remove_downed
- [x] try_remove_bear_trap
- [x] try_remove_lightsnare
- [x] try_remove_heavysnare
- [x] try_remove_crushed
- [x] try_remove_grab
- [x] try_remove_webs
- [x] try_remove_impeding_effect

Bionic and fuel (moved to `bionics.cpp`):
- [x] get_remote_fueled_bionic
- [x] can_fuel_bionic_with
- [x] get_bionic_fueld_with
- [x] get_most_efficient_bionic
- [x] get_fueled_bionics
- [x] get_fuel_available
- [x] get_fuel_capacity
- [x] get_total_fuel_capacity
- [x] update_fuel_storage

Morale (moved to `character_morale.cpp`):
- [x] update_morale
- [x] hoarder_morale_penalty
- [x] apply_persistent_morale
- [x] get_morale_level
- [x] add_morale
- [x] has_morale
- [x] rem_morale
- [x] clear_morale
- [x] has_morale_to_read
- [x] check_and_recover_morale

Body stuff (moved to `character_body.cpp`):
- [x] update_body_wetness
- [x] update_body
- [x] update_stomach
- [x] update_bodytemp
- [x] update_frostbite
- [x] body_window

Ammo and reloading (moved to `character_ammo.cpp`):
- [x] rate_action_unload
- [x] rate_action_reload
- [x] select_ammo
- [x] list_ammo
- [x] ammo_count_for
- [x] find_reloadables
- [x] can_reload

Proficiencies (moved to `character_proficiency.cpp`):
- [x] has_proficiency
- [x] has_proficiency
- [x] has_prof_prereqs
- [x] add_proficiency
- [x] lose_proficiency
- [x] display_proficiencies
- [x] practice_proficiency
- [x] proficiency_training_needed
- [x] known_proficiencies
- [x] learning_proficiencies
- [x] get_proficiency_bonus
- [x] set_proficiency_practice

Modifier and score stuff (moved to `charcter_modifier.cpp`):
- [x] melee_thrown_move_modifier_hands
- [x] melee_thrown_move_modifier_torso
- [x] melee_stamina_cost_modifier
- [x] reloading_move_modifier
- [x] thrown_dex_modifier
- [x] stamina_recovery_breathing_modifier
- [x] limb_speed_movecost_modifier
- [x] limb_balance_movecost_modifier
- [x] limb_run_cost_modifier
- [x] swim_modifier
- [x] melee_attack_roll_modifier
- [x] reloading_move_modifier
- [x] aim_speed_skill_modifier
- [x] aim_speed_dex_modifier
- [x] aim_speed_modifier
- [x] ranged_dispersion_modifier_hands
- [x] ranged_dispersion_modifier_vision
- [x] manipulator_score
- [x] blocking_score
- [x] lifting_score
- [x] swim_score
- [x] vision_score
- [x] breathing_score
- [x] balance_score
- [x] movement_speed_score

There may be good reasons for a lot of the above functions to exist in the Character class; this list is just ones that look kind of suspicious to me.

# Additional context

Opening this issue mainly to stimulate discussion and collaboration, as this is a huge undertaking, and I have no illusions of completing it alone.

**Comment by wapcaplet** [comment]
Note, a lot of the Character class implementation is defined in other files (`bionics.cpp`, `consumption.cpp`, `crafting.cpp`, `melee.cpp`, `martialarts.cpp`, `mutation.cpp`, `suffer.cpp` and a few others). I don't know the relative value of reducing the size of the `Character` class itself versus just reducing the `character.cpp` file by moving some of the definitions to other files.

**Comment by actual-nh** [comment]
Given that various editors (including for mergers to resolve merge conflicts, IIRC) are having fits editing character.cpp, I would think the most important thing is moving out of the file - if possible, into another class at the same time. If one can't edit the file, it's difficult to make progress on anything else.

**Comment by wapcaplet** [comment]
> I would think the most important thing is moving stuff out of the file - if possible, into another class at the same time.

Simply moving definitions from one `.cpp` to another (or even a new `.cpp`) is much easier than the conceptual change to another class, so I'm inclined to begin with some straight moves of related functions to new files (or sometimes existing ones). I've started this with #51270

**Comment by Saicchi** [comment]
These functions could probably go into `src/proficiency.cpp`. Saving around ~90 lines.

```
Character::has_proficiency
Character::has_proficiency
Character::has_prof_prereqs
Character::add_proficiency
Character::lose_proficiency
Character::display_proficiencies
Character::practice_proficiency
Character::proficiency_training_needed
Character::known_proficiencies
Character::learning_proficiencies
Character::get_proficiency_bonus
Character::set_proficiency_practice
```

**Comment by wapcaplet** [comment]
With the 6 PRs so far submitted (3 merged and 3 draft/pending), the total size of `character.cpp` (413K) will be about 30K less than `src/game.cpp` (442K), though it will still have more lines than `game.cpp` (11,762 vs. 11,693). I would love to shrink `character.cpp` down to less than 10K lines before calling this issue completed, but I'd probably settle for 11K at this point, since I'm pretty tired of looking at it `o_O`

**Comment by wapcaplet** [comment]
When #51369 is merged, `character.cpp` will be only 378KB in size, and 10,710 lines. No longer the largest file by any measure. I'm sticking a fork in this and closing it.
