### ISSUE TITLE
Hair growth over time

### ISSUE THREAD

**Issue by Entity-y** [CleverRaven/Cataclysm-DDA#51112]
# Is your feature request related to a problem? Please describe.
Hair at the moment is static, years can go by and the hair will stay the same length.

# Describe the solution you'd like
Make hair length dynamic but keep color static. Starting from bald, have hair grow and switch to the next length every couple of months. This would give hair trimmers a real purpose over just a mood buff. The use of hair trimmers would allow the choice of how short the player would like to trim their hair.

This could also be extended to work with facial hair. Players go from clean shaven face to a full grown beard over a years time, using trimmers would allow for stylizing facial hair if they have a full face of it. A full beard can be trimmed to any style. Goatees can be trimmed to mustaches or chin straps.

# Describe alternatives you've considered
Applying this code to work on NPCs, the problem with this is they don't have the intelligence to cut their own hair.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
