### ISSUE TITLE
More dialogue system integration into spellcasting

### ISSUE THREAD

**Issue by Light-Wave** [CleverRaven/Cataclysm-DDA#51125]
# Is your feature request related to a problem? Please describe.
As the dialogue system grows more powerful (such as by #50305) it becomes more appealing to use it more in spellcasting. Specifically the ability to use dialogue condition to check whether or not a spell can be cast. This could enable us to make more interesting and unique spell mechanics without hard coding the functionality in C++

# Describe the solution you'd like
Run a group of EoCs in the following scenarios. Modds can expand these groups to hook into the system. The spell themselves can also list additional EoCs to run at these instances.
- For each spell when the spellbook is opened
- For a spell when it is selected in the spellbook
- When trying to cast at a location
- For each target when trying to cast
- When trying to cast, after targets have been looped through
- When trying to target a location, after looping over each target
- After casting
- after casting, looping over each target

New Command: spell_fail, behaves differently depending on in which of the above states it is used.
- If used when the spellbook is opened, it will cause the spell to be hidden.
- If used when selected, it will cause the spell to be uncastable, as if you didn't have enough mana. A string can be passed along that will be printed explaining why the spell can not be cast.
- If used when trying to target a location, either before, after or during the looping over targets, it will cause the spell to not be cast, as if it had an invalid target. A string can be printed to explain why.
- After casting, it will cause the spell to fizzle, as if you had failed due to too high encumbrance or too low focus. A string can be printed to explain why nothing happened.
- After casting looping over each target, it will cause the spell to have no effect on that target but otherwise continue to resolve. A string can be printed to explain why nothing happened.

Let the EoC access and use information about the following things
- The spell's ID
- The level of the spell
- The Exp of the spell
- The mana cost of the spell
- The spell's casting time
- The spell's flags
- The spell's school
- The mod the spell is from
- If you have a written source of the spell in your inventory

Let EoC's modify the following values
- The level of the spell
- The Exp of the spell
- The mana cost of the spell
- The spell's casting time

When looping over targets, treat the target as the NPC you are talking to for the purposes of effects and conditions. When targeting a point, pretend there is an NPC there for the purposes of many effects and conditions.

# Describe alternatives you've considered
- Move mutation and bionic activation to spells, and only display them if you have the mutation / bionic that enables them? 

# Additional context
Some ideas:
A spell with multiple applications. Say that wen you learn Move Earth, you also learn a bunch of sub-spells, such as create stone wall, crate stone table, create stone chair, etc. When you open your spellbook these all spells have their exp set to the highest exp any of them have. This causes them to behave as if they were one spell that can be cast in multiple ways.
A mod that makes it so that you have to carry a written source of the spell you wanna cast with you in a spellbook. This might allow you to organize your spells a bit better, and not have your spell list cluttered up with spells you're not gonna use
A spell that only affects targets without the flying tag
A spell that requires 3 friendly creatures to be in the area of effect in order to cast it
Global modifiers to mana cost and spell casting time
Effects that makes the target immune to spells with a certain tag. For example, a worn anti-magic field might cause most spells to be unable to affect you.
An effect that boosts the damage of all spells you cast with a 'cold' tag
A spell that can only be cast outside under a full moon
A spell that requires a nearby tree to work

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
