### ISSUE TITLE
[0.F stable] Impossible to "eat" batteries when the bionic power is full, but the battery system isn't.

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#51126]
### Describe the bug

As the title says. If the bionic power is full, you can't replenish the battery storage by "eating" batteries. Expending a single charge allows you to load up on power again.

### Steps To Reproduce

1. Have a character with a battery system CMB and some bionic power storage.
2. Ensure the bionic power is completely filled, but the battery system isn't.
3. Try to "eat" batteries.
4. See that nothing happens. The battery system power pool isn't replenished.
5. Expend at least one bionic power charge (e.g. by enabling some active bionic for a turn).
6. Try to "eat" batteries again.
7. See that the battery system power pool is replenished.

### Expected behavior

The power pool should be replenishable whenever it's not full.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

It's not possible to try this on a recent experimental as the save crashes on the next action after loading, so I won't bother supplying a save that won't be used.

The bionic system is being reworked, but I don't think bionics are supposed to be removed, so the issue may still be relevant.

There have been some work to address issues where at least one charge of "ammo" has been required to perform tasks unrelated to ammo. This may or may not be related to those issues, and thus, may or may not have been fixed.

**Comment by hexagonrecursion** [comment]
> the save crashes

Please upload your save file as a separate bug report to allow us to debug the crash

**Comment by hexagonrecursion** [comment]
Experimental is not affected: [E]ating was replaced by refueling through the bionic menu and that works fine

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 9ccd509 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap]
]

**Comment by hexagonrecursion** [comment]
Confirmed: the batteries are enabled in the [E]at menu, [E]ating them takes time, **but** charges are not removed from the battery and not added to the battery system

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 0.F-1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by PatrikLundell** [comment]
There is a separate bug report for the crash issue, so that's already taken care of.

Since it has been confirmed the issue is fixed in experimental I close this issue.
