### ISSUE TITLE
The "no hope" mod generates old-style obsoleted an non-interactive MREs and IFAKs due to old IDs present in the mod's versions of mapgen json files.

### ISSUE THREAD

**Issue by RandDenner** [CleverRaven/Cataclysm-DDA#51139]
### Describe the bug

The listed contents of some files (mil_base_z0.json in particular) in the No Hope mod use old obsoleted IDs and are otherwise missing newer item information. This leads to inoperable IFAKs, along with a few other items having potential issues.

In **mil_base_z0.json** alone:
Not updated:
"ifak" -> "full_ifak"
"inhaler -> "charged_inhaler"
"1st_aid" -> "full_1st_aid"
"aep_suit" -> "hazmat_suit"

Not sure why the old MREs are not working correctly. Maybe the other errors caused them to glitch. It's not 100% reproducible for me.

Other potential issues are with items "glowstick" & "handflare" lacking ammo values, 

As well as the "forklift", "welding_cart" & "engine_crane" vehicles lacking  status info.

Last, it still references old weapon IDs which cause occasional errors:
"nato_assault_rifle" -> "m4_carbine"
"nato_assault_rifle" -> "m27_assault_rifle"

since there are 122 or so mapgen files in the mod, I expect there are other similar issues in some of them as well.

### Steps To Reproduce

Start a game using the "No Hope" mod, and the "Overrun" scenario.
You'll start in an military warehouse where you can find most of the affected items except the guns.

A few items/vehicles will be nearby in the automotive workshop and armory

### Expected behavior

Correct, functional items.

### Versions and configuration

Win10, tiles, 0.F-1, only one required mod as listed, since it's the problem.

**Comment by RandDenner** [comment]
So I'm just going to update the affected file and make a PR from this.

**Comment by casswedson** [comment]
Fixed by #51150

**Comment by RandDenner** [comment]
Yeah. I made that PR.
