### ISSUE TITLE
Hallucinatory skill increase messages are outdated

### ISSUE THREAD

**Issue by Little-119** [CleverRaven/Cataclysm-DDA#51130]
### Describe the bug

Hallucinated skill increase messages are outdated, simply saying "You increase [skill] to level [number]" instead of "Your [practical/theoretical] skill in [skill] has increased to [number]!" making them less convincing. The messages for real skill increases were changed in #50176 and the hallucinatory messages were not updated to match

### Steps To Reproduce

1. Play a character with Kaluptic Psychosis, or who is otherwise sufficiently prone to hallucinating
2. Wait for a fake skill level up message
3. Increase your real skills
4. Observe that they do not match

### Expected behavior

For hallucinated skill increase messages to look like real ones

### Screenshots

Real skill increase
![image](https://user-images.githubusercontent.com/4680835/131174425-06bf3449-fc27-4e2a-b61c-170358e23035.png)

Fake skill increases
![image](https://user-images.githubusercontent.com/4680835/131174469-31e1001d-7df5-49f9-9395-463cc2e5124e.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 308d1d2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    No Fungal Monsters [No_Fungi],
    No Rail Stations [No_Rail_Stations]
]

**Comment by Theawesomeboophis** [comment]
I usually play kaluptic psychosis characters and it is hilarious when the game tells me something like " You increase shooting to level 7" followed by " Just Kidding". Hallucinations just make the game much more terrifying/fun in my opinion, like when you go into a bathroom and see a zombie hulk only for it to be a figment of your imagination and vanish into thin air.
