### ISSUE TITLE
Pool balls should be usable as rock ammo

### ISSUE THREAD

**Issue by actually-reb** [CleverRaven/Cataclysm-DDA#51149]
Despite pool balls being described as "essentially a rock", I cannot fire them from a sling while exclaiming "8-ball, corner zombie!" I'm not sure how the damage of a pool ball would compare to a rock.

**Comment by Wyrdean** [comment]
Compare the weights, and extrapolate from there I'd say. Subtract a bit for being made out of plastic; although they tend to be rather hefty.

**Comment by Pseudogeist** [comment]
> 
> 
> Despite pool balls being described as "essentially a rock", I cannot fire them from a sling while exclaiming "8-ball, corner zombie!" I'm not sure how the damage of a pool ball would compare to a rock.

<p>They used to be, I'm not sure when that changed.</p> Weird, I could have sworn they were, but I can't see any sign of it in the repo. Maybe that was pre-DDA?


> 
> 
> Compare the weights, and extrapolate from there I'd say. Subtract a bit for being made out of plastic; although they tend to be rather hefty.

Plastics come in many forms. Pool balls are made of bakelite, which I'm pretty sure would perform as good as a rock, if not better. I'm not sure how the aerodynamics would compare, but I would imagine favorably. It all depends what a 'rock' is.

**Comment by Night-Pryanik** [comment]
Can't confirm on latest experimental as of 01 November 2024.
![изображение](https://github.com/user-attachments/assets/9d6b1be0-2940-4bd4-862c-4834a323adcb)
