### ISSUE TITLE
Option to hide Switch Gender feature from character screen

### ISSUE THREAD

**Issue by mourningsun** [CleverRaven/Cataclysm-DDA#51146]
### Is your feature request related to a problem? Please describe.
As someone who never going to use this feature, I think there should be an option to hide it.

### Describe the solution you'd like
An option to hide Switch Gender from character screen.

### Describe alternatives you've considered
Fully customisable character screen.

**Comment by ZhilkinSerg** [comment]
There are plenty of options players are not using - we are not hiding them.

**Comment by mourningsun** [comment]
There are a lot of features that you can switch off when customising sidebar. Like I always switch off } hint. But in character screen there is a lot of useless information that you can't hide, and that is my primary issue.

**Comment by Rivet-the-Zombie** [comment]
> in character screen there is a lot of useless information that you can't hide, and that is my primary issue.

Yet this has only become an issue just now. Curious.

**Comment by mourningsun** [comment]
> > in character screen there is a lot of useless information that you can't hide, and that is my primary issue.
> 
> Yet this has only become an issue just now. Curious.
You got me Sherlock.

Anyway. There is already an option to change your profession (and soon your name). Do we need to clutter ui with all those tool tips as well or just the gender one?

**Comment by mourningsun** [comment]
> > > in character screen there is a lot of useless information that you can't hide, and that is my primary issue.
> > 
> > 
> > Yet this has only become an issue just now. Curious.

 You got me Sherlock.
Anyway. There is already an option to change your profession (and soon your name). Do we need to clutter ui with all those tool tips as well or just the gender one?

**Comment by ZhilkinSerg** [comment]
> There are a lot of features that you can switch off when customising sidebar. Like I always switch off } hint. But in character screen there is a lot of useless information that you can't hide, and that is my primary issue.

Yes, please go work on unifying UI and make it customizable. @-menu is not winning to fit everything in 80*24/25.

**Comment by Night-Pryanik** [comment]
I suppose the theme of customizing the @-menu and letting the players turn on and off specific elements is worth discussing. Not only this particular "change gender" hint, but most, if not all, elements of this menu.

**Comment by mourningsun** [comment]
> > There are a lot of features that you can switch off when customising sidebar. Like I always switch off } hint. But in character screen there is a lot of useless information that you can't hide, and that is my primary issue.
> 
> Yes, please go work on unifying UI and make it customizable. @-menu is not winning to fit everything in 80*24/25.

I dont have a PC. Is there a way to compile game on android?

**Comment by ZhilkinSerg** [comment]
You only need text editor to write code and git client to upload code to the repo. Compiling on mobile is possible, but would be pretty slow on most mobile devices. Anyway Github CI can compile the game for you - would be faster in any case.

**Comment by mourningsun** [comment]
> You only need text editor to write code and git client to upload code to the repo. Compiling on mobile is possible, but would be pretty slow on most mobile devices. Anyway Github CI can compile the game for you - would be faster in any case.

I'll look into that. Thanks!

**Comment by mourningsun** [comment]
By the way, in case someone else would like to work on it, should I open another issue and reword it without mentioning Gender Switcher (since this is a taboo topic apparently) or will this one be reopened eventually?

**Comment by Night-Pryanik** [comment]
Please open a new issue.
