### ISSUE TITLE
keep gender politics out of the game dev

### ISSUE THREAD

**Issue by MooseyHey** [CleverRaven/Cataclysm-DDA#51159]
the ability to change sex and gender are a divisive political issue and not something everyone agrees with. We are here to play a game, not to be subjected to the devs political opinions in this regard.

Please remove the option to change gender midgame. You know this is something not everyone agrees with, and it is very disappointing to see encroachment of personal politics into the development of CDDA.

**Comment by Saicchi** [comment]
The change is small enough that you can remove it and update the game with the latest version without any problems.
Read this if you want to know how to compile the game: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/COMPILING/COMPILING.md
If you have any question about compiling or contributing feel free to come to the developer's discord and ask in #dev-help

**Comment by Gollum-of-Prague** [comment]
I  agree with the OP's general point here (minus mentally ill part - that was unnecessary). I think the way it was implemented was questionable and it also revealed the shortcomings of the UI, which is why an option to hide it would've been a good compromise. However, to my surprise, the original [issue](https://github.com/CleverRaven/Cataclysm-DDA/issues/51146) I posted was immediately closed and my account was banned soon after just for mentioning this feature. This is an example  of how letting your personal politics affect your judgement can lead to abuse of power and the atmosphere of fear and hostility it creates goes against the open nature of this project.
![Screenshot_2021-08-31-07-23-39](https://user-images.githubusercontent.com/89833413/131462289-df6fb01c-f010-4b0f-99aa-95f51d441b18.png)

**Comment by ZhilkinSerg** [comment]
You can think whatever you want. Thing is PR was created by someone and then it was merged by project owner. That's the end of it.

**Comment by Gollum-of-Prague** [comment]
> You can think whatever you want. Thing is PR was created by someone and then it was merged by project owner. That's the end of it.

Why was my account banned then?

**Comment by ZhilkinSerg** [comment]
> 
> 
> > You can think whatever you want. Thing is PR was created by someone and then it was merged by project owner. That's the end of it.
> 
> That doesn't explain why my account was banned.

This is probably because I was not providing obvious explanation. You can have one if you want - your account was banned by project owner because they do not want you to participate in their project.

**Comment by Gollum-of-Prague** [comment]
> > > You can think whatever you want. Thing is PR was created by someone and then it was merged by project owner. That's the end of it.
> > 
> > 
> > That doesn't explain why my account was banned.
> 
> This is probably because I was not providing obvious explanation. You can have one if you want - your account was banned by project owner because they do not want you to participate in their project.

If that's the case I would like to hear his reasoning if he stands by this decicion.

**Comment by ZhilkinSerg** [comment]
Yeah, you would like, but they don't have to provide you one.

**Comment by Gollum-of-Prague** [comment]
What do you think the reason was?

**Comment by Saicchi** [comment]
If the project owner does not want your contribution there is nothing anyone can do about it. Arguing here is pointless. Avoid hotly-debated topics if you're just a new member of the community.

**Comment by Gollum-of-Prague** [comment]
I understand. Will this account also be banned? I was planning to participate, but now I'm not sure anymore.

**Comment by ZhilkinSerg** [comment]
> 
> 
> What do you think the reason was?

I've already told you the reason: "they do not want you to participate in their project"

**Comment by Gollum-of-Prague** [comment]
> > What do you think the reason was?
> 
> I've already told you the reason: "they do not want you to participate in their project"

I typed the instead of their. My english sucks when I'm stressed.

The question would be "What do you think their reason was?"

If you were on my place how would you phrase that issue to avoid getting in trouble.

**Comment by Gollum-of-Prague** [comment]
Forget it. I am done with this. I'll just dissapear.

**Comment by ZhilkinSerg** [comment]
There is no issue to discuss for the start.

**Comment by ChainsawGarden** [comment]
@ghost there are probably two forks of the game now, BrightNights and my fork. Feel free to contribute to either.. though, I don't know whether or not BrightNights merged this change.

**Comment by ZhilkinSerg** [comment]
There are like 3K forks - https://github.com/CleverRaven/Cataclysm-DDA/network/members.
