### ISSUE TITLE
Crash on resize in options

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#51162]
### Describe the bug

Crash when expanding window drastically when scrolling options -> Interface.

### Steps To Reproduce

1. Play in windowed mode, make the window small.
2. Go into options -> Interface and scroll down until the menu starts scrolling.
3. Expand the CDDA game window drastically.
4. Observe crash (Segmentation fault)

### Expected behavior

No crash.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-2082-g74951016d3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

I think it might have crashed because of the scrolling thing. The number of items in the list or position might have not be updated properly, so we access vector[i], where i > vector.size().

But who knows?

**Comment by hexagonrecursion** [comment]
Please post the contents of config/crash.log

**Comment by Brambor** [comment]
> Please post the contents of config/crash.log

I... don't have that. When I play with the Game Launcher, it hangs for a bit. When I play with compiled binary on MSYS on Windows, it says "Segmentation Fault"

**Comment by hexagonrecursion** [comment]
I did try reproducing this. In the process of doing so I found two other bugs (#51189 #51191) but neither matches your description.

* If you know how to start cataclysm in a debugger or how to open a crash dump in a debugger, you could try doing that and then posting a backtrace
* If gcc or clang build is supported on windows, you could try building with sanitizers

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.

**Comment by Brambor** [comment]
I can no longer reproduce this. The menu went through some changes, so it makes sense.
