### ISSUE TITLE
Stimulants

### ISSUE THREAD

**Issue by estebandellasilva** [CleverRaven/Cataclysm-DDA#51166]
# Is your feature request related to a problem? Please describe.
My current Character iss sick with the Common Cold, so i was drinking bee balm tea.
It appears that bee balm tea iss a Stimulant, which i had no way of knowing. (it is not mentioned in the description)
With caffeinated chewing gum you get the information that it is an Upper. (If Upper iss the correct cause)
With food you dont get that information.

# Describe the solution you'd like
Provide the Information if the food provides you with Stimulants.

# Describe alternatives you've considered
Mentioning in the description that a food has Stimulants

**Comment by hexagonrecursion** [comment]
Confirmed

![4](https://user-images.githubusercontent.com/52621858/147977457-cf179861-294d-462e-947e-bdd9c8a3c398.png)
![9](https://user-images.githubusercontent.com/52621858/147977473-d635d7e0-bd38-4795-a128-a47738cb6361.png)

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: eacb7d9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by hexagonrecursion** [comment]
This has been fixed

![image](https://user-images.githubusercontent.com/52621858/183577509-dd01aca2-fa1b-4e7a-8d28-9da2245b6fb9.png)

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: df06cbf [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
