### ISSUE TITLE
Slight issue with high skill overlapping skill name text

### ISSUE THREAD

**Issue by RandDenner** [CleverRaven/Cataclysm-DDA#51179]
### Describe the bug

Not enough space was given for the lines in the character generation interface, so there's overlaps.

### Steps To Reproduce

Make character with a skill of 10 or higher. Piercing weapons line always has overlaps due to length.

### Expected behavior

Proper spacing

### Screenshots

![image](https://user-images.githubusercontent.com/73523034/131233240-f13ef5b1-0e4c-4d71-a235-6de3968a3239.png)

### Versions and configuration

Win 10 tiles, any current version
English

**Comment by actual-nh** [comment]
I've tagged this with Translation because that's likely to cause even more problems with languages in which the skill names are longer than in English, and/or a cut-off version of the names is more ambiguous than English.
