### ISSUE TITLE
Item disassembly zone bugs

### ISSUE THREAD

**Issue by Pseudogeist** [CleverRaven/Cataclysm-DDA#51170]
### Describe the bug

Regarding #50517 :

1. In-progress items are finished instantly by player / NPC.
2. Moving a currently worked on in-progress item to another tile causes the NPC to pick it back up and drop it in a random spot, unless the item is placed back in to the disassembly zone. I've not been able to identify a pattern.
3. In-progress items started by the player are not valid for NPC disassembly. The inverse is fine.
4. Results are added back to the disassembly pile, meaning any results will be disassembled if possible. This should probably be an option on the zone. Possible appropriate settings: current behaviour, dump to nearest unsorted loot pile, sort results, or leave results on the crafting spot (PC behaviour).
5. Player / NPC will only use a table / workbench if they are already standing next to one when they appropriate the item for disassembly. This behaviour might be best as optional toggles, too, but I'm not entirely sold on it: current behaviour, find closest, find closest best, use only surfaces in area. This kind of control probably has limited use... But for large or overlapping areas, or during renovation, I can see them being significant, perhaps.
6. Typo: An NPC working on disassembly, when talking to them about their current activity, say `"I'm currently disassemble things."` This should be `"I'm currently disassembling things."`

### Steps To Reproduce

All should be pretty obvious.

### Expected behavior

Already covered / obvious.

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 7495101 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

### Additional context

That's all I've found so far. Nice start though, @Menschheit ! It's good to see some work on making NPCs helpful, as opposed to the burden / downright liability they currently are. At least they don't spawn with active mininukes anymore I guess. I was very much looking forward to seeing @davidpwbrown 's NPC workbench come to fruition but this addition definitely goes some way towards scratching that itch.

**Comment by Menschheit** [comment]
Thanks for your feed back.
1. Trying to fix in next PR
2. I think out of the zone means the item should not be processed anymore? It is hard to track all the items taking off the zone.
3. Hmm, if an item is processed by 1 character, I don't want it to be taken by other ppl, need to know if the activity is interrupted.
4. I have no idea for this one... So what if there is no loot zone available? Or the disassembly zone is too big so that we can't find a "no disassembly" tile? Also it is hard to track recursiv disassemble.
5. Trying to fix in next PR: Find best workbench.
6. FIx in next PR.

I will try to fix 1,5,6 in the next PR, but after that I don't have much time for coding, have 3 exams next month : (

**Comment by Pseudogeist** [comment]
Nice! Good luck with your exams!

Regarding point 3, after a little thought, this looks like a bug stemming from the item disassembly activity handler that only surfaced now that NPCs have the potential to work on them. 

Regarding point 4, the issue where there is no space outside the zone should be pretty rare, so it can probably default to dumping the results wherever. If you've managed to cover an entire area with item disassembly zones I imagine you want everything disassembled there anyway. If there is no loot zone available, again, this is something the player should be ensuring so we can probably leave results wherever they currently are.

As player item disassembly (without a zone) drops results wherever the 'in progress' item is when it is completed I think this should be default behaviour for zones, too. I expected the item disassembly activity handler would deal with this? Hmm.

Kudos on the quick fixes! :)
