### ISSUE TITLE
Can't detect items in construction menu when on top of stairs

### ISSUE THREAD

**Issue by Pooshmeu** [CleverRaven/Cataclysm-DDA#51187]
### Describe the bug

when on top of stairs the construction menu does not detect items that are on the ground near the player

### Steps To Reproduce

1-stay on top of a "t_wood_stairs_down"(json id) terrain
2- spawn 100 planks
3- open construction menu
4-check for "board up wood door"
5-move out of "t_wood_stairs_down"
6-repeat "steps 3" and "4"

### Expected behavior

construction menu should detect planks near the player, or any other material

### Screenshots

![Sem título](https://user-images.githubusercontent.com/82523535/131237373-5f02fd76-046e-4444-bcce-0686a15dddff.png)
![Sem título2](https://user-images.githubusercontent.com/82523535/131237375-fadf2ab8-c5d5-4573-aa7f-b2ddaea7fea3.png)
![Sem título3](https://user-images.githubusercontent.com/82523535/131237376-3b36ca60-bea8-44b5-99bc-cb6551d5a97d.png)

### Versions and configuration

-w10
-build number: 2021-08-17-2240
-tiles version
-english language

**Comment by actual-nh** [comment]
There was an earlier report of this IIRC.

**Comment by Vendidurt** [comment]
Might be related- you also cannot open/close windows/curtains when standing on staircases going up. This causes a minor issue sometimes in mansions.
