### ISSUE TITLE
UPS Conversion Mod not working with Internal Unified Power System when trying to cook

### ISSUE THREAD

**Issue by AkdoolTheSlimy** [CleverRaven/Cataclysm-DDA#51190]
### Describe the bug

I applied a ups mod to a mess kit, hoping that I could cook with it without needing a fire or batteries. I have the Internal Unified Power System cbm and a ton of power to draw from. I can use it with a ups in my inventory to cook things like meat, but I cannot use my cbm to do so, even though it is active when I try. I assume this is an oversight; I can still heat up food with it, for example, and it uses my internal power supply. So it has only half functionality, and I still need batteries/fire to cook. I don’t know how many other items have this issue.

### Steps To Reproduce

1. Install the Internal Unified Power System CBM, with a power supply and power storage.
2. Find a mess kit. Apply a UPS Conversion Mod to it.
3. Activate the Internal Unified Power System in the bionics menu while you have power. (P)
4. Attempt to cook something that requires a mess kit. Make sure you have all other ingredients. It will be grayed out and not acknowledge that you have the mess kit and sufficient power.
5. Grab a UPS. Reload it with a battery that holds sufficient power. Keep it in your inventory.
6. Attempt to cook something that requires a mess kit again. This time, it should recognize that you have the mess kit and sufficient power.

### Expected behavior

I expected that I could use my internal power supply to heat things up using the modified mess kit.

### Versions and configuration

- OS: iOS
    - OS Version: Name: <unknown>; Version: <unknown>; Build: <unknown>; 
- Game Version: 0.F [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key]
]

**Comment by Hirmuolio** [comment]
This is in stable 0.F?

#48608 fixed it in experimentals.

**Comment by AkdoolTheSlimy** [comment]
Wait, really? That’s odd. Since I’m on an iPad port, maybe that’s why, or at least related. 

Here’s the app page.
https://apps.apple.com/us/app/cataclysm-roguelike-rpg-0-f/id1577366679

Under versions, it says it’s 0.F, and was updated to 0.F-1 about a week ago. I’m new and don’t know the specifics about which version’s which. How would I know if this is the stable version?

**Comment by AkdoolTheSlimy** [comment]
Alright, well no point in reporting bugs unless you’re on the PC, it seems. I’ll close. Have a nice day.
