### ISSUE TITLE
A large amount of CPU time is spent on unnecessary copying of string literals

### ISSUE THREAD

**Issue by Putnam3145** [CleverRaven/Cataclysm-DDA#51195]
# Is your feature request related to a problem? Please describe.
I did a quick profile of sleeping overnight in a basement under a city, which I noticed takes much longer than doing so in e.g. an LMOE shelter in the wilderness. I found that a lot of the slowdown was due to heap allocation--a lot of which was due to a [single line](https://github.com/CleverRaven/Cataclysm-DDA/blob/7f73bd02fafe5a77df10c225e79fca1b8099b78c/src/item.cpp#L10805), which was copying the string literal every time due to [`has_fault_flag`](https://github.com/CleverRaven/Cataclysm-DDA/blob/7f73bd02fafe5a77df10c225e79fca1b8099b78c/src/item.cpp#L5824) taking a `const std::string&` as an argument. "BLACKPOWDER_FOULING_DAMAGE" is not an `std::string`, so it has to be copied into a new one, and then free'd at the end of the function, every single time. Overall, this _one line_ accounted for 2% of the CPU time--not large, but not negligible. Something like 8.5% of the CPU time was spent in checks similar to this, copying and freeing strings repeatedly in functions that, for the most part, take literals.

# Describe the solution you'd like
Ideally, [`std::string_view`](https://en.cppreference.com/w/cpp/string/basic_string_view) would be used, but that's C++17 and, yeah, my attempts to migrate to that have *not* gone well--at the very least I should get more familiar with the codebase, haha. 

# Describe alternatives you've considered
It may be possible to replace all the `const std::string &`s for simple read-only check functions such as this with `const char *`, which also does no copying but has obvious potential safety issues. Naturally, it's also possible to just do nothing about it--this is a microoptimization, and while I _have_ profiled it and found that it _does_ matter to an extent, it's also rather onerous partially due to the sheer quantity of actual `const std::string&` arguments there are in the codebase--well over 1000.

# Additional context
Tested on stable, but specific code I was looking at is identical in latest experimental.

It should also be noted that much of this can likely be chalked up to simple quantity, too--[`item_pocket::is_type`](https://github.com/CleverRaven/Cataclysm-DDA/blob/85414d7ee8e2c0d3df109355fb114e260a9db378/src/item_pocket.cpp#L1470) is using up ~3% of the CPU time, despite not actually doing _anything_ wrong (that I can see), just because it's being called a whole lot. The effect is amplified greatly due to the sheer amount of checks being done.

...I would've started a discussion on this instead of an issue, but I can't actually start new discussions, which is probably reasonable, haha, it's not like I've ever even interacted with this github before, I just got into the game last week and really, really enjoy optimization.

**Comment by ZhilkinSerg** [comment]
Yep, we are waiting to migrate to C++17 (in 5 or so years) and we will be using `string_view` - in the meanwhile let's try not to use C-strings in C++ when not necessary.

`const std::string &` is pretty cheap, but when you call function that uses it with string literal - temporary string object is created. You can try to use `static const std::string flag_BLACKPOWDER_FOULING_DAMAGE ( "BLACKPOWDER_FOULING_DAMAGE" );` instead of literal string and profile again to compare if performance increases.
