### ISSUE TITLE
Cataclysm++ Radiogenic Goggles Permanent Lit Up

### ISSUE THREAD

**Issue by VaneFox** [CleverRaven/Cataclysm-DDA#51203]
### Describe the bug

A permanent irremovable lit up effect is applied to the player for as long as the radiogenic goggles are in your inventory, the only fix is to not have them.

### Steps To Reproduce

1. Have Pair of Radiogenic Goggles

### Expected behavior

Permanent Lit Up

### Screenshots

![cataclysm-tiles_2021-08-30_00-32-36](https://user-images.githubusercontent.com/67852696/131254126-a2c4b1e6-bf4b-4626-bff6-6d783184d50c.png)
![cataclysm-tiles_2021-08-30_00-33-02](https://user-images.githubusercontent.com/67852696/131254129-0adbed23-cfd1-4e6e-a753-7042ac33a2b4.png)
![cataclysm-tiles_2021-08-30_00-33-15](https://user-images.githubusercontent.com/67852696/131254130-23a43b08-82bf-4df2-aa81-7c89a6b69043.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 610c4de [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    <color_light_green>Real Dark Skies</color> [realdarkskies],
    <color_light_red>Secronom</color> [secronom],
    <color_light_red>Secronom+ Lore Expansion</color> [secronom_lore_expansion],
    <color_red>Sierra Madre</color> [sierra_madre],
    Aftershock [aftershock],
    Battle Maid Redux [battle_maid],
    Bionic Professions [package_bionic_professions],
    C.R.I.T Expansion Mod [crt_expansion],
    Engineering essentials [EngineeringEssentials],
    Make bows great again [bow_opness],
    Nechronica Redux [Nechronica_Redux],
    PKs Rebalancing [PK_REBALANCE],
    Pneumatic fun [pneumo_fun],
    Steampunk Mod [steampunk_arcanum],
    Whaleys Collectables [collectablemod],
    Add Rice [rice],
    Adurnsyl's Assorted Arms and Armour [AAA],
    Advanced Gear Goats Edition [adv_gear],
    Advanced Technologies [advtech],
    Armor Up! Survivor Expansion [ArmUpSurvEx],
    Arsenal Breach [arsenal_breach],
    Artyoms' Gun Emporium - Reloaded [Arts' Guns],
    BioCo Content [bioco],
    Bionic Space Expander [Bionic_Space_Expander],
    Bionics Systems Recipes [bio_recipes],
    CBM Equipment [CBM_Arms],
    Culinary Days Ahead [culinary_days_ahead],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Dried Fruits [dried_fruits],
    Expanded Archery [ExArch],
    Fallout New England [fallout],
    Gourmand's Graces [Gourmand'sGraces],
    Homestead Instruments Inc. [homestead],
    Icecoon's Arsenal [ew_pack],
    Large capacity storage CBMs [eps_cbm],
    Locked and Loaded [Locked_and_Loaded],
    Makeshift Items Mod [makeshift],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    MOD to grow tea leaves [More tea leaf],
    Modern Weapon Pack Expanded [modern_weapon],
    MST Extra [MST_Extra],
    Mythological Replicas [nw_pack],
    Pixel's Various Fuckery [Pix's Shit],
    Project APEX [apex],
    Ricky's Future Armory [futurearmory],
    The Cool Mod [cool_mod],
    The Glory Of Cereal! [CerealMod],
    The Vermilion Mod [VermilionMod],
    Thermal Electric UPS [thermal_ups],
    Wild Living [WildLiving],
    Compatible Add Bandits [GOV_BANDITS],
    Crazy Labs [crazy_labs],
    Youkai Enemies [Youkai_Disco],
    <color_light_blue>Lighter Weariness</color> [light_weariness],
    Cataclysm++ [Cata++],
    CDDA Variety Pack [ks_variety_pack],
    Even More Mutations [even_more_mutations],
    Extra Mutated Scenarios [extra_mut_scens],
    Food Irradiator [food_irradiator],
    machine [machine],
    Mining Mod [Mining_Mod],
    More Survivor Stuff [more_survivor_stuff],
    Mutant NPCs [mutant_npcs_new],
    Tekitou Map Commercial Overhaul [tekitoumap],
    Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
    Zet's Hair - PKs Rebalancing [zets_hair_ext_pk_rebalance],
    Dorf Life [Dorf_Life],
    Oa's Early Game Mutations mod [oa_early_game_mutations_mod],
    Ships From Oa Additional Buildings [Ships],
    Water Towers [water_towers],
    Whaleys TALL Buildings [whaleys_tallbuild],
    Blazemod - Vehicle Additions Pack [blazemod],
    Cars to Wrecks [cars_to_wrecks],
    Roadheader and other mining vehicles [Heavy miners],
    Tankmod: Revived [Tankmod_Revived],
    Amplified @'s Features [amplified_players_features],
    Graphical Overmap [Graphical_Overmap],
    ProjectKawaii [ProjectKawaii],
    Sarcophagi Access [sarcophagi_access],
    Whaleys Hair Mod (UDP Tweaks) [WHALEYHAIR_UDP],
    Fuji's Military Profession Pack [fuji_mpp],
    Military Professions Mod [More_Military],
    Mutation Changes [Mutation_Changes],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    ZSFIXED_C:DDA Extra Professions & Gears [ZSFIXED_cddaxp],
    Real Dark Skies Above faction rebalance [realdarkskies_faction_balance]
]

**Comment by Night-Pryanik** [comment]
This is a third-party mod issue. We don't fix such issues. Please ask a mod author/maintainer to fix it.
