### ISSUE TITLE
Eat until full

### ISSUE THREAD

**Issue by schealex** [CleverRaven/Cataclysm-DDA#51209]
# Is your feature request related to a problem? Please describe.
I think we should add a hotkey in the consume menu to consume the currently selected item until player character is FULL.

# Describe the solution you'd like
Instead of having to press the key for consuming over and over if you are eating stuff like butter it would be a press of a button to either consume the whole stack if thats not enough to feel FULL or until FULL.

# Describe alternatives you've considered
keeping it the way it is.

# Additional context
N/A

**Comment by PatrikLundell** [comment]
I'm trying to avoid Full, but rather aim for Satisfied plus as close to Full as I can get, unless I want to reserve space to top up with some water at the end.

Also note that some food is quite hydrating, so you don't want to overdo neither the hydration nor the dehydration part of the feeding spectrum.

**Comment by mqrause** [comment]
An option could be to make the eat menu multiselect. I'm not sure how the eating activity handles stacks, but if it's handled properly, that would do pretty much what.

**Comment by Brambor** [comment]
I wouldn't like to press a hotkey to then select from a multi menu if my selection will always be the same.

I think it's better to set desired "keep eating until X" in the options, probably bring up a menu with a hotkey to customize the consumption menu.

There you would select until what you want to eat by pressing the hotkey. I would prefer the default to be satisfied over FULL. But we can put there all the options, including "", "hungry", "very hungry"... Somebody could find that useful.

Then do the same for drinking.

When that customization (option) menu is finished, being able to not show columns would be nice as well. Simple turn on / off.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.

**Comment by schealex** [comment]
@Night-Pryanik i still think this would be a gread QOL addition, so do some others. Is it the right thing to just close it?

**Comment by Night-Pryanik** [comment]
Closing it doesn't mean we don't want it or don't need it. Keeping open issues like this just clutter the issue list. If someone wants to implement this feature, he doesn't need open issue for that.

**Comment by Zireael07** [comment]
Again, I wonder how someone wishing to implement this is supposed to find this in a sea of closed issues (most of them invalid/fixed)

**Comment by Night-Pryanik** [comment]
Why someone needs to search for this (or any other feature) in the first place? I think it's a very rare case when someone purposefully lurks through open issues in search for an inspiration.

**Comment by Brambor** [comment]
> Again, I wonder how someone wishing to implement this is supposed to find this in a sea of closed issues (most of them invalid/fixed)

If this, and many other issues weren't closed, then:
How should one find it in the see of open issues?

**Comment by schealex** [comment]
> > Again, I wonder how someone wishing to implement this is supposed to find this in a sea of closed issues (most of them invalid/fixed)
> 
> If this, and many other issues weren't closed, then: How should one find it in the see of open issues?

That's what labels are for. 

I agree that in a big repository like this the amount of open stuff can get overwhelming but I think y'all do a great job categorizing them.

Myself for example is looking through open issues to check if there is something I would like to work on. I would never check closed issues to check if some are "actually still open"

**Comment by Night-Pryanik** [comment]
We need two big categories for issues: "Bugs" and "Ideas/suggestions". The latter could contain all these tons of "good to have" issues. But since we have only one big "Issues" category for all kind of stuff, having lots of open non-bug issues I personally see as detrimental to project management.

**Comment by PatrikLundell** [comment]
I agree a big pile of mixed suggestions and bugs is messy, but it's definitely unfair to just close everything that's been sitting idle for a while, in particular if that sitting is due to release freezes, and then just reject suggestions because they're the same as something that was closed earlier.
There's really a need to distinguish between just closed due to inactivity and closed because something has been rejected.

**Comment by schealex** [comment]
> We need two big categories for issues: "Bugs" and "Ideas/suggestions". The latter could contain all these tons of "good to have" issues. But since we have only one big "Issues" category for all kind of stuff, having lots of open non-bug issues I personally see as detrimental to project management.

Again that's exactly what labels are for on github. Check the labels on this issue. There is the enhancement / feature label. And you can filter the issues based on the labels: https://github.com/CleverRaven/Cataclysm-DDA/labels/%3CEnhancement%20%2F%20Feature%3E

**Comment by Zireael07** [comment]
> Myself for example is looking through open issues to check if there is something I would like to work on. I would never check closed issues to check if some are "actually still open"

My thoughts exactly.

**Comment by Brambor** [comment]
Maybe something like:

CDDA tags for closed issues: unsolved / partially solved / solved / ...?

description of tags: track the status of issues more precisely, since 2022-12-23

But I would move this discussion to Discord. To some #meta channel.
