### ISSUE TITLE
Crash when the character template name include a 2-byte code.

### ISSUE THREAD

**Issue by Ezsk** [CleverRaven/Cataclysm-DDA#51204]
### Describe the bug

If the language used is set to Japanese or other 2-byte codes, an error occurs when trying to save the Last Character.template during character creation. This is because the template file name is automatically named to "前回のキャラクター設定.template" when language used is set to Japanese.

The character template will fail to save and the file name "前回のキャラクター設定.template.1016.temp" will remain in templates folder.

If you have a previously created character template that contains 2-byte codes, the game will crash immediately upon startup.

### Steps To Reproduce

1. Set 2byte-code language in Interface option such as Japanese.
2. Make new character
3. Failed to save Last Characters template file. 

### Expected behavior

The template should be able to saved correctly even if 2-byte codes in the template name.

### Screenshots

![error](https://user-images.githubusercontent.com/17972439/131255015-29390eef-ba4a-49c0-8846-520464141783.png)

### Versions and configuration

OS: Windows10
Game version:2470543 (This occurs in versions after 2021-08-27-2258 or so.)
Ingame language:Japanese

**Comment by ZhilkinSerg** [comment]
Is it a thing in stable 0.F?

**Comment by Ezsk** [comment]
No, this occurs in the experimental version.
Probably since the version of 2021-08-27-2258 or nearly.

**Comment by ZhilkinSerg** [comment]
Must be https://github.com/CleverRaven/Cataclysm-DDA/pull/50624

**Comment by Ezsk** [comment]
Ah, that's it. If making changes to the file system, perhaps a test for 2-byte codes should be added.

**Comment by Ezsk** [comment]
The attached file is Last Character template which was created by Stable 0.F1 with Japanese settings. I think it can be used for test.
[Sample_2byteCode_template.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7072976/Sample_2byteCode_template.zip)

**Comment by BrettDong** [comment]
This is a Windows specific issue, so our existing testing process on Linux and macOS won't be able to discover the problem.

<img width="1072" src="https://user-images.githubusercontent.com/21075502/131272595-09880781-f2d5-4065-9d9b-dd6f226dacfc.png">

**Comment by Ezsk** [comment]
I have confirmed the template files are generated correctly in the last experimental version. Thank you so much!
