### ISSUE TITLE
Faction camp followers should be able to radio the player character

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#51206]
# Is your feature request related to a problem? Please describe.
Not really. I just think that enabling followers to radio the player would help to liven things up a bit, and expand NPC functionality.

# Describe the solution you'd like
If a an NPC and the player character both have a two-way radio, NPCs would be able to call the player in the same way the player can call the NPC. Obviously, this shouldn't be a frequent occurrence, since games where NPCs can randomly contact the player on their own have demonstrated all-too-well how annoying this can get, so getting a random call maybe once every ten days or so (with a check to make sure the player character isn't within face-to-face speaking distance at the time) on average with a decently-sized faction camp would probably be the maximum frequency by default (though maybe an option to adjust frequency would also help).

Situations in which an NPC calls the player might include wandering hordes coming too close to where the NPC is (and when the player character is over a certain distance away), or maybe if an NPC is on a risky faction camp mission, they might be able to call for assistance, which could make them appear in a random location somewhat close to the faction camp along with some zombies chasing them, or something else they need help with. With multiple followers, maybe you could even then call another follower in order to send them as backup instead.

Maybe this functionality could also be expanded to include nearby factions that are friendly with the player's faction, and give random missions every now and then.

Iunno, this is just an idea for something I think would help to break up some of the tedium that comes with having a relatively secure base and a lot of followers with nothing to do.

# Describe alternatives you've considered
Just keeping this suggestion to myself and quietly hoping someone else thinks of something similar, I guess?

# Additional context
Not really anything to add, here.

**Comment by PatrikLundell** [comment]
As long as the calls are relevant, i.e. not "just called to check up on you", but rather emergency calls, or, if setting allow, reports that tasks are done (so no orders can be given). These things would require new functionality for companions, though.

It's also worth considering if these radios should be smarter, i.e. being able to be set on vibration (to avoid incidents when sneaking), and having a caller memory (so you can call back after dispatching the opponent currently trying to rip out your throat). I have no idea if walkie-talkies have gained any smarts since the dawn of time (or at least transistors), though.

**Comment by AmarinReyny** [comment]
> As long as the calls are relevant, i.e. not "just called to check up on you", but rather emergency calls, or, if setting allow, reports that tasks are done (so no orders can be given). These things would require new functionality for companions, though.

Of course. Like I said above, measures should be taken to ensure that it doesn't get annoying. And, yeah, I kind of figured that this wouldn't happen for a long time, if it happens at all. I just think it's a good idea to have in mind for the game's future.

> It's also worth considering if these radios should be smarter, i.e. being able to be set on vibration (to avoid incidents when sneaking), and having a caller memory (so you can call back after dispatching the opponent currently trying to rip out your throat). I have no idea if walkie-talkies have gained any smarts since the dawn of time (or at least transistors), though.

Also very good ideas.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
