### ISSUE TITLE
Disassembling E-ink tablet all the Ebooks spill out

### ISSUE THREAD

**Issue by Menschheit** [CleverRaven/Cataclysm-DDA#51218]
### Describe the bug

Ebooks become real books if E-ink is disassembled. :laughing:

### Steps To Reproduce

1. Scan books into e-ink
2. Disassemble e-ink
3. Get books back

### Expected behavior

Don't spill Ebooks.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 7495101 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by Saicchi** [comment]
Can confirm on `0.F-2195-gfda3f04eb5`.
