### ISSUE TITLE
Shocker zombie has unrealistic view through Z-levels

### ISSUE THREAD

**Issue by Entity-y** [CleverRaven/Cataclysm-DDA#51217]
### Describe the bug

Shocker zombie is up against the wall on ground level and seemingly has x-ray vision to me on the second floor of an augmentation clinic.

### Steps To Reproduce

1. Start scenario CHALLENGE - Abnormal Augmentations ( started as a Bionic Pseudovamp )
2. Walk around the clinic and be shocked from impossible angles

### Expected behavior

Electricity shouldn't be able to pass through layers of glass like that, or through the concrete wall the zombie is next to, or the concrete floors separating the levels. The zombie sees my character as if it were hovering on the second floor in front of the window. The closer you are to the building the less of a view there should be of the next level up, when the zombie is directly next to the wall it should have absolutely no view of the second floor.

### Screenshots

![image](https://user-images.githubusercontent.com/50155659/131266600-3b22bd72-11d4-42c3-91f5-7a357ebe4fa6.png)
![image](https://user-images.githubusercontent.com/50155659/131266710-abaec679-f387-49e7-9ef8-13884e21ae15.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 84eef84 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    <color_light_red>Secronom</color> [secronom],
    <color_light_red>Secronom+ Lore Expansion</color> [secronom_lore_expansion],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Secronom - UndeadPeople Tileset [secronom_UDP]
]

**Comment by hexagonrecursion** [comment]
I am sorry. I have used the debug menu to fill the entire first floor with shocker zombies and still could not reproduce the issue. Do you have a save file where the issue can be replicated?

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: eacb7d9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock]
]
