### ISSUE TITLE
Typos, lack of plural forms and other errors in game texts

### ISSUE THREAD

**Issue by CountAlex** [CleverRaven/Cataclysm-DDA#51229]
### Describe the bug

Somewhat regular issue of not adding plural from to a word that can't be changed to plural by simply adding "s" in the end.
This time:
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/monsters/insect_spider.json#L2083
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/monsters/insect_spider.json#L2099
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/monsters/insect_spider.json#L2139
Also same problem:
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/items/gunmod/conversions.json#L27

Double use of same word:
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/crafting.cpp#L2532

Grammar error:
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/snippets/lab.json#L20

The "1" is extra?
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/iexamine.cpp#L592

### Steps To Reproduce

Find more that a single mantis. See how they are "2 great mantiss" instead of "2 great mantises".

### Expected behavior

Proper plural form for mantises.

### Versions and configuration

After #49170.

### Additional context

Maybe it could be useful to add a check to tests that catches such words in JSON that end with "s" and so might require a plural form.

**Comment by Qrox** [comment]
> The "1" is extra?

The two percentage symbols become a single one after formatting, resulting in `Exchange Cash for eCash (1% fee)`, so it's not wrong.

**Comment by Qrox** [comment]
> Maybe it could be useful to add a check to tests that catches such words in JSON that end with "s" and so might require a plural form.

I wrote a check like that and have been using it to find incorrect plurals. However due to the complexity of plurals it reports false negatives more often than not. I guess I can hide it behind a command line flag and create a PR when I have the time.

**Comment by CountAlex** [comment]
> 
> 
> > The "1" is extra?
> 
> The two percentage symbols become a single one after formatting, resulting in `Exchange Cash for eCash (1% fee)`, so it's not wrong.

I see, but resulting text was a bit confusing and looked like it has extra "1" in the front of  the parentesis part and no "%"symbol.



> 
> 
> > Maybe it could be useful to add a check to tests that catches such words in JSON that end with "s" and so might require a plural form.
> 
> I wrote a check like that and have been using it to find incorrect plurals. However due to the complexity of plurals it reports false positives more often than not. I guess I can hide it behind a command line flag and create a PR when I have the time.

Yeah, I thought that would be a little complicated. However, it could still cover simple cases such as no plural form for something ending with "s".
