### ISSUE TITLE
[0.F-0] Towed vehicles rear end the tower when stopping, and start out set at silly speed

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#51228]
### Describe the bug

Two bugs that may well be related.
When towing a vehicle, the towed vehicle rear ends the tower as often as not when stopping, even if the speed is reduced gradually, or never having been above minimum.

When taking control of a formerly towed vehicle it tends to start out with a silly speed set, such as a value in the hundreds, rather than the expected 0.

### Steps To Reproduce

1. Connect a towing vehicle to a towed vehicle.
2. Drive straight ahead at minimum speed.
3. Stop after towing the vehicle for at least some distance.
4. Either get rear ended or try again until you do.
5. Enter the towed vehicle and start it. Check the speed it's set to reach: it's typically not zero.

### Expected behavior

When speed is reduced gradually, the towed vehicle should roll to a stop before reaching the towed vehicle on any surface (one could argue that grass would be rougher than furrowed earth, but the towed vehicle should stop in time even on a road).

The target speed for a towed vehicle should be reset to zero when the pulling force ceases (i.e. when the cable slackens).

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

I've tried to increase the tower vehicles speed from 0 to minimum when the towee approaches to within two tiles to give the towee additional room to stop, but that does not help: the code probably doesn't model a slack cable not propagating any force. This is OK as long as the towee stops in time.

My last towing resulted in the rear ending vehicle hitting and damaging the tow cable part of the tower...

There are also wild swerving and strange catch ups of the towed vehicle (typically causing any wing mirrors on the towed vehicle to be lost by the end of the trip), but these are minor issues: it's impressing towing works at all.

**Comment by Maleclypse** [comment]
This is only considered a bug if you are experiencing this when slowing down in increments of five mph or less.

**Comment by PatrikLundell** [comment]
As mentioned, I've experienced it when never even increasing speed beyond minimum, and I've never slowed down faster than one step per tick (nor have I accelerated faster). The towing vehicles haven't been dragsters, and the speed increments seem to be about 6 km/h, which is a fair bit less than 5 mph.
