### ISSUE TITLE
NPCs do not close vehicle doors ever

### ISSUE THREAD

**Issue by jeffplata** [CleverRaven/Cataclysm-DDA#51234]
### Describe the bug

When entering or exiting vehicles with PC, NPCs do not close open doors. This is potentially dangerous as monsters could easily enter the vehicle through open doors.

### Steps To Reproduce

Take a mission to take NPC somewhere.
He starts following you.
He/She enters and exits vehicles as you do.
They leave doors open all the time

### Expected behavior

NPCs should close doors when entering/exiting vehicles.

### Screenshots

![image](https://user-images.githubusercontent.com/29348635/131325022-8df452f0-2090-47b3-ba77-c35f66eb922a.png)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: f29d9a0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by RenechCDDA** [comment]
Have you asked them to close doors? I believe that by default they will not, but that is one of the things you can ask them to do.

(It is possible this is a regression introduced since I last updated, but vehicle doors *were* being closed properly as of 0.F-1)

**Comment by jeffplata** [comment]
"Any leads on where the camp might be?" That's all he cares for now.

**Comment by RenechCDDA** [comment]
Sounds like you're currently in a quest, specifically `MISSION_REACH_FEMA_CAMP`. NPCs that are following you for a quest are not actually followers as I understand it, so they're either engaging in default orders or completely ignoring them.

I would say that the behavior of following NPCs (and NPCs by default, probably) *should* be to close doors behind them though.

**Comment by jeffplata** [comment]
Aside from the door, he also charges to monsters like a maniac, and there's no talking him out of it. All he cares about is the goddamn mission.

**Comment by PatrikLundell** [comment]
When I had one companion, ordering the closing of doors worked fine, but with two following you it gets a mess where they close doors in the face of each other, so I reverted the behavior back to the default. Whenever I have one or more companions with me I move around such that I can close the doors that need closing.

But, yes, it's strange that NPCs completely single minded on a mission still recklessly charges any enemies they see rather than trying to stick to the mission, and possible be alive at the end of it.

**Comment by Night-Pryanik** [comment]
Allied NPC do close doors after them when ordered to do this in 0.F-12004. So I'd close this issue.
