### ISSUE TITLE
Why are you making me create new issue to answer?

### ISSUE THREAD

**Issue by akirashirosawa** [CleverRaven/Cataclysm-DDA#51236]
### Describe the bug

@Fris0uman
>It's not, biological sex is not simulated in game only gender. So the gender option just changes how you refer to yourself which does not require any physical change.

Check out your video at #51079. The video clearly shows how the character's appearance changes. Does your appearance change in reality, does your face change when you begin to consider yourself a different gender in your head?

https://user-images.githubusercontent.com/41293484/130859505-59835e3d-4c13-413f-9786-23a0de0066d0.mp4

Do you realize that most developers and gamers believe that gender is dependent on biological sex in real life?

The game changes the appearance of the character depending on gender. Appearance is a biological trait. So you're lying that this is just how the character thinks he is. Otherwise, why does the face change in a second?

The game changes items, the character's underwear depending on gender at the beginning of the game, assuming that women's panties are comfortable for the vagina, and men's panties are for the penis? Or do you think that women's and men's underwear are different just like that, for no real reason?

Do you understand that people choosing a man or a woman at the beginning of the game think that they are choosing REALLY a man or a woman?

Why do you want to break their opinion of the knee by taking advantage of your privilege as a moderator?

### Steps To Reproduce

Why are you making me create new issue to answer?
You cannot communicate on equal terms and abuse the privilege of a moderator?
Are you the same contributor as me or are you something better?

### Expected behavior

Let me answer, w/o creating new issues.

### Versions and configuration

#51079

**Comment by Fris0uman** [comment]
Feel free to use a tileset that uses the same sprite for every gender, now please stop spamming useless issues.

**Comment by akirashirosawa** [comment]
It's okay to use tilesets and sound packs with different looks and different voices for different genders, if you think, that gender is related to biological sex, and therefore related to appearance and voice. And also with the underwear that the character is wearing.

I only point out that there are details in the game that indirectly indicate that gender is associated with biological characteristics. And that you can't just change it in one second.

If gender is only what a person thinks of himself, and not the real sex, then why does the set of clothes change depending on gender when creating a character? Clothes are not worn on thoughts from the head, but on a biological body.

Most people thought that by choosing gender, they also determined biological sex. It's more important than gender for roleplaying, isn't it? Why can't you play as a real woman and not as a man who thinks she is a woman?

**Comment by Fris0uman** [comment]
Why didn't you complain when the ability to change the appearance of vehicle parts was added months ago??

**Comment by jiornojiovanni** [comment]
Do you know this is the game where you can mutate into a squid and other animals right? Realism is only a tool, not an end. 

This is literally an option that allow you to change a sprite with like 10 pixels of difference, i can't even tell the difference between the two option. If this is enough for you to be unplayeable, this might not be the game for you.

**Comment by Zireael07** [comment]
I have to admit I'm confused. In another issue you @Fris0uman said 
> So the gender option just changes how you refer to yourself which does not require any physical change.

... but the sprite changes, so I am just confused... A sprite changing is a fairly physical change imho....

**Comment by akirashirosawa** [comment]
> Why didn't you complain when the ability to change the appearance of vehicle parts was added months ago?

Because the appearance of machine parts is more in line with reality with this change.

I'm not complaining that that both men and women can choose any hairstyle for themselves, for example, and there is no division into female and male hairstyles in the game. Because it’s quite real. Everyone has their own tastes.

But gender depends on biological characteristics, not just taste (for the majority of people).

**Comment by Fris0uman** [comment]
Please the sprite is purely cosmetic, In Retrodays the option gives you a ponytail, do you think this is intrinsically linked with biological sex and can only be achieved through hormonal treatment and extensive surgery?
As discussed at length in the original PR already bioloigical sex is not tracked in dda, and gender only affects your sprite and the way NPCs adresses you.

**Comment by Zireael07** [comment]
Oh, I don't play with retrodays, thanks for the clarification ;)

In that case, to prevent any more discussions popping up, maybe add the "sprites are purely cosmetic" part to either @-menu or the README? Because I can **bet** there's gonna be more people confused by the sprite changing in response to this option...

**Comment by akirashirosawa** [comment]
> Do you know this is the game where you can mutate into a squid and other animals right? Realism is only a tool, not an end.
> 
> This is literally an option that allow you to change a sprite with like 10 pixels of difference, i can't even tell the difference between the two option. If this is enough for you to be unplayeable, this might not be the game for you.

Let's do a sex reassignment mutation? I don't mind. For example, in Dark Souls there was a coffin that changed its sex. And it was realistic, or rather it was in the logic of that universe.

You are trying to make the game not for everyone and that is bad. To play the game you don't need to share certain views on gender, I think so. Why impose on others that it is enough just to imagine that you are a woman to become a woman? Mutation or magic is in the logic of the game, not in ideology.

**Comment by jiornojiovanni** [comment]
> 
> 
> > Do you know this is the game where you can mutate into a squid and other animals right? Realism is only a tool, not an end.
> > This is literally an option that allow you to change a sprite with like 10 pixels of difference, i can't even tell the difference between the two option. If this is enough for you to be unplayeable, this might not be the game for you.
> 
> Let's do a sex reassignment mutation? I don't mind. For example, in Dark Souls there was a coffin that changed its sex. And it was realistic, or rather it was in the logic of that universe.
> 
> You are trying to make the game not for everyone and that is bad. To play the game you don't need to share certain views on gender, I think so. Why impose on others that it is enough just to imagine that you are a woman to become a woman? Mutation or magic is in the logic of the game, not in ideology.

Everyone has opinion that might contrast with this game. It's impossible to cater to everyone, especially when we are talking about something so small that you can just ignore it, instead of going nuts. Nobody is forcing you to accept a "political" ideology.


Is this game against antivax people by having a flu vaccine? Should we cater to them by removing it? I don't think so.

**Comment by akirashirosawa** [comment]
> Please the sprite is purely cosmetic, In Retrodays the option gives you a ponytail, do you think this is intrinsically linked with biological sex and can only be achieved through hormonal treatment and extensive surgery?
> As discussed at length in the original PR already bioloigical sex is not tracked in dda, and gender only affects your sprite and the way NPCs adresses you.

Please answer exactly: How do you feel about yourself depends on your biological sex? How NPCs adresses you depends on your biological sex? I believe the answer to both of these questions is yes. Then why produce entities?

Why separate one from the other? If you belong to minorities that were not born in their own body, then what prevents them from choosing the real sex/gender they want at the beginning of the game?

Then why can't you change the age at the push of a button? Or weight? I don’t consider myself fat, let me enter the weight from the keyboard. These are all cheats and should be on the cheat menu.

**Comment by akirashirosawa** [comment]
> Everyone has opinion that might contrast with this game. It's impossible to cater to everyone, especially when we are talking about something so small that you can just ignore it, instead of going nuts. Nobody is forcing you to accept a "political" ideology.

Look at the original PR. What a heated discussion. And judging by the emoticons under the original post - opinions were divided approximately equally.

As I wrote earlier - the game does not look into your underpants. You can choose any character at the beginning of the game. And he will have the appearance, voice and clothes of the chosen gender, biological sex.

You can think of it as just gender or biological sex. The game does not impose this on you. Until the PR clearly showed that all your roleplay is all nonsense and you are not playing for a real woman, but for a sexless person in fact, who only considers himself as woman and can change his mind 100 times a day.

What settings should I choose to play a biological woman if I want to? Previously, the game allowed me to do it. Now there is no.

**Comment by jiornojiovanni** [comment]
Literally nothing changed, really. If you think you are playing as a biological woman that's it, nobody is telling you otherwise, as it's just not represented.

It's a choice of design that you can only find on GitHub, as nothing in the game suggest it. 

View it as a character editor, many game have one. It just allow to change one particular feature of your character (i hope they also add other customization).
