### ISSUE TITLE
inability to understand gender 

### ISSUE THREAD

**Issue by akirashirosawa** [CleverRaven/Cataclysm-DDA#51233]
### Describe the bug

Breaking the link of the gender with the biological sex #51079.

The reality given to us in sensations connects gender and sex with a direct link. Attempts to break this tie are follow by your ideology. So either the gender directly follows from the sex, and it is not possible to change it at the request of the left heel. Or it doesn't exist - it's a fantasy out of your head.

Why did you decide to produce your fantasies, dictated by your ideology, into an open source game?

Why did you decide to impose your political ideological views on the fact that the gender is not related to sex to everyone?

The fact that you closed the discussion, forbade expressing other opinions does not make you fascists?

This is a very fascist statement: There are my views and the wrong ones. "your inability to understand gender" - this statement is one of those. Why is your ideological understanding of gender the only correct one? Because your ideology is fascist, which does not allow other views?

And most importantly, you ignored the opinion of other developers who invested their time and energy in the project, rejecting their opinions, closing the discussion, appropriating the results of their work in order to promote your fascist ideology.

Some people, users, developers and gamers believe that gender directly follows from sex and it is not correct to call a biological man a woman. Thus, it is not possible to change the genus without changing the biological sex. 

There are brainwashed people who have studied gender studies and studied 52 genders. And it's normal for them to have a cinnamon patty or sausage bun as a gender. Or is it normal for a weightlifter man who calls himself a woman to compete with biological women, putting them in a losing position. Their position is ideological and has nothing to do with reality.

Why did you reject the opinion of the first people who take their data from the world of sensations and began to promote the opinion of the second, whose opinion is dictated by their fascist ideology?

I have no problem with people who consider themselves a pancake as a gender.  But I see the problem in the fact that you gave a shit on the face of half, if not most of the developers who put their efforts into this project, closed the discussion in order to advance their ideological views.

### Steps To Reproduce

1. Launch the game

### Expected behavior

The player can choose the gender at the start of the game. Someone is free to perceive this sex as directly related to the biological sex, someone is not, depending on the views of the player. The ability to change sex while playing directly dictates that gender is not associated with biological sex.

I see no reason to impose your ideological views directly. A person can always decide for himself whether gender is associated with biological sex or not, choosing it at the beginning of the game.

Therefore, I suggest roll back the request #51079. At least arrange a vote on it, and not arrange fascism and the imposition of the "correct" understanding of gender.

### Versions and configuration

Latest version with PR #51079

### Additional context

Instead of making the project convenient for people of all views, you started to impose yours. What's next? Will you ban all those who disagree? By stealing their time and energy that they put into a common project, appropriating them for themselves and expelling those who disagree with your fascist dictatorship?

**Comment by jiornojiovanni** [comment]
wow, thanks for this shitpost. I really enjoyed reading your delirious post

**Comment by akirashirosawa** [comment]
> wow, thanks for this shitpost. I really enjoyed reading your delirious post

Thank you for your reasoned opinion and respect for the opinions of others. I have never seen so many arguments. You are definitely not a bearer of the fascist ideology.

**Comment by Fris0uman** [comment]
github issue are not meant for ranting, please take that somewhere else. The gender swap option is a small QOL addition it does not need that much effort fighting against it.
