### ISSUE TITLE
ATM takes all money in a stack but only turns one into ecash 

### ISSUE THREAD

**Issue by Entity-y** [CleverRaven/Cataclysm-DDA#51230]
### Describe the bug

When exchanging all paper bills and coins in an ATM #51090, the whole stack of money #51077 gets taken but only actually converts one in the stack, wasting the remainder of the stack of money.

### Steps To Reproduce

1. Spawn a stack of bills or coins
2. Deposit all into ATM and notice that only one was converted

### Expected behavior

The whole stack of money should be counted and added into the cash card instead of just one. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 4b793ad [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by Entity-y** [comment]
@eltank while the ATM technically works, I'd have to input every dollar individually from a stack for it to register. 

This could be a consequence of money being altered to now use charges after the ATM PR.

**Comment by eltank** [comment]
Thanks for letting me know, this is easy to fix.
