### ISSUE TITLE
Stop block conversation

### ISSUE THREAD

**Issue by akirashirosawa** [CleverRaven/Cataclysm-DDA#51235]
### Describe the bug

@Fris0uman 
> github issue are not meant for ranting

Github is a place for conversation, for discussion. Or not?
Why are you blocking any discussion regarding the changes about gender (PR #51079)?

@Fris0uman 
> The gender swap option is a small QOL

This breaks the essence of the game based on realism. In real life, you cannot change gender in 1 second (assuming, gender related with biological sex). If it's a cheat, put it in the cheat/debug menu.

### Steps To Reproduce

Try to open a issue related with PR #51079

### Expected behavior

Open discussion, and not close any issue and blocking any discussion, because your understanding of gender is the only correct one.

If it's only small QOL as you say, not ideology - let's put it in the debug menu?

### Versions and configuration

with PR #51079

### Additional context

Stop running away from open discussion. How about debug menu?

**Comment by Fris0uman** [comment]
Please no spam

**Comment by Fris0uman** [comment]
>  (assuming, gender related with biological sex)

It's not, biological sex is not simulated in game only gender. So the gender option just changes how you refer to yourself which does not require any physical change.
