### ISSUE TITLE
Power armor helmets (on) Missing item definition

### ISSUE THREAD

**Issue by Fris0uman** [CleverRaven/Cataclysm-DDA#51245]
### Describe the bug

Every power helmet on throws error whe nscrolling over in debug menu.
I suppose that you get the error too if you find it in game but I found the error while testing sprites

``` 
DEBUG    : Missing item definition: power_armor_helmet_basic_on

 FUNCTION : find_template
 FILE     : D:\Game\CataclysmCODE\Cataclysm-DDA\src\item_factory.cpp
 LINE     : 1650
 VERSION  : Please install `git` to generate VERSION
```

### Steps To Reproduce

Open debug menu spawn list
Go to any power armor helmet on
Get error

### Expected behavior

No error when getting to the helemets. I guess some json is missing.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: Please install `git` to generate VERSION [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]
]

**Comment by Hirmuolio** [comment]
Same as #49894

**Comment by Fris0uman** [comment]
closing as a duplicate of #49894
