### ISSUE TITLE
Balance: DURABLE_MELEE is removed from i_staff and q_staff but cudgel

### ISSUE THREAD

**Issue by CKRainbow** [CleverRaven/Cataclysm-DDA#51251]
# Is your feature request related to a problem? Please describe.
Quarterstaff is no longer a durable weapon for it needs little treatment, but cudgel is a even simplier weapon, I think DURABLE_WEAPON should be removed for it.

# Describe the solution you'd like
remove DURABLE_WEAPON for cudgel. And we need durable improved staff/cudgel weapon which needs more treatment

**Comment by Maleclypse** [comment]
Closed by #52048
