### ISSUE TITLE
Further issues with Strict Humanitarian

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#51256]
### Describe the bug

Multiple enemies that should fall under the lens of Strict Humanitarian do not: Experimental and Evolved Mutants (Mutant Humanoid flesh/fat/etc is cannibal-only) and Gozu, which drop human meat only despite being essentially minotaurs. 

### Steps To Reproduce

Attempt to butcher a gozu or experimental mutant as a Strict Humanitarian and be unable to consume their products without massive morale decrease.

### Expected behavior

Anything that isn't literally a human should be fine for a strict humanitarian, that's the point of the trait. Experimental Mutants and Gozu are clearly not human, even if they are similar to humans.
However, it may be intentional? Gozus drop both human and cow meat, is it intended the part covered in socks and shorts is literally human but their head is edible?

### Screenshots

![gozu](https://user-images.githubusercontent.com/56016372/131463325-1bdf2bfd-6702-4851-a024-33affd0ff278.PNG)

### Versions and configuration

Cataclysm DDA version bc1d00c

**Comment by RandDenner** [comment]
Perhaps it's their presumed sentience that's the actual problem for a strict humanitarian, not just a strict adherence to human/non-human or not quite human.

**Comment by anoobindisguise** [comment]
> Perhaps it's their presumed sentience that's the actual problem for a strict humanitarian, not just a strict adherence to human/non-human or not quite human.

Currently you are able to eat Grackens, Blank Bodies, Twisted Bodies and Human Snails. It appears to be a sort of "well if a human ate a gnome/elf/vulcan/ferengi/etc it's *technically* not cannibalism even if they're sentient" deal. But there are a lot of missing entries, all the mutants (experimental/evolved/chud/troglobite/cyclopean/etc) as well as aforementioned Gozu, plus Amigara Horrors, are all "demihumans" that yield meat only Cannibals can eat.

**Comment by Maleclypse** [comment]
Part oversight and part when I was newer on the project I was more afraid of overstepping.  Whereas now I'm more likely to assume that any change I make will be argued against if people think I'm wrong.  Anyway please correct this :)

**Comment by anoobindisguise** [comment]
Am I expected to do this commit myself? Just curious, I guess I can get on it if needed.

**Comment by eltank** [comment]
The description of Strict Humanitarian says: "You're convinced that these things that look vaguely human from elsewhere are definitely not people.  Therefore it's okay to eat them, right?"
So nether creatures are fine to eat but anything evolved/mutated from a human shouldn't be.
