### ISSUE TITLE
Bicycle Movement bug

### ISSUE THREAD

**Issue by Rocwarg** [CleverRaven/Cataclysm-DDA#51260]
### Describe the bug

Certain bicycles generated in the world refuse to be dragged with the 'Grab Something Nearby' command.  This applies when the bike is initially generated.

### Steps To Reproduce

1. Use the grab command on a world generated bicycle.
2. Try to move the bicycle in any direction
3. Bicycle will not move and print the appropriate message

### Expected behavior

I expect the bicycle to be dragged along with my player character to make moving it through tight corners easier.

### Screenshots

![cddabikeerror](https://user-images.githubusercontent.com/69776947/131506376-9c9834cf-12b1-4b38-97db-0b5c0019a048.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Crazy Cataclysm [crazy_cataclysm],
    Mythical Martial Arts [MMA],
    Fuji's Military Profession Pack [fuji_mpp]
]

**Comment by RandDenner** [comment]
I found that, too.
![image](https://user-images.githubusercontent.com/73523034/131553016-677b1f04-ed1f-4e34-a7cb-7ce48b880ffb.png)

But I also found that there is always one direction they can be moved.
If it fails at one end, try the other.
I've always found that it will work, and then the issue stops for both ends, if you go back to the other.

Additionally, as you see in that screenshot, I teleported some distance away without ending the grab, but it stuck and prevented me from going up stairs.
That could probably also happen with other kinds of in-game instant movement, like artifact teleportation, or maybe something from Magiclysm (there's teleport magic there, right?).

**Comment by StStep** [comment]
I'd like to add you can reproduce this using wooden frames and wagon wheels pretty easily. As soon as I added wheels to a wooden wagon I was making, I got the "collides with errors in movement code" when trying to drag it, so i thinks it's something with the wheels.

**Comment by PatrikLundell** [comment]
Yes, that happens a lot with motorcycles and scooters as well. Just try grabbing the other end, as mentioned (only a work around, of course: you should be able to grab and drag it as long as there isn't actually something it collides with).

**Comment by RoyBerube** [comment]
I've noticed that shopping carts don't ever exhibit the bug.

Once you find a bugged vehicle and manage to get it moving by pulling in another direction, the bug goes away. Afterwards it can be grabbed in any direction without problems.

**Comment by RoyBerube** [comment]
Have a working fix for this. Just want to do some more testing to make sure it has no unexpected side effects.
