### ISSUE TITLE
Not really a glitch but there's salt water for the Moose in the Zoo

### ISSUE THREAD

**Issue by OmeleteDuFroMago** [CleverRaven/Cataclysm-DDA#51265]
### Describe the bug

I don't think it makes much sense for it to be salt water. And sorry if this is not the place for this, i wanted to give feedback so i assume here.

### Steps To Reproduce

Just try press E on the shalow water

### Expected behavior

It is salt water

### Screenshots

![Screenshot_5](https://user-images.githubusercontent.com/26847612/131555779-bc12fc52-c77f-4688-84c0-f64cbb309739.png)

### Versions and configuration

- OS: Windows
    - OS windows 10
- Game Version: 0447a46 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Monsters [No_Fungi]
]

**Comment by RandDenner** [comment]
Confirmed.

It's coded as follows in the mapgen:
![image](https://user-images.githubusercontent.com/73523034/131559760-078de1c0-d342-4582-95c6-8bc8f7d915c3.png)

I can fix it easily, unless OP wishes to themselves.

**Comment by OmeleteDuFroMago** [comment]
> 
> 
> Confirmed.
> 
> It's coded as follows in the mapgen:
> ![image](https://user-images.githubusercontent.com/73523034/131559760-078de1c0-d342-4582-95c6-8bc8f7d915c3.png)
> 
> Most water in the zoo is coded as salt water, it seems. The otter pond shown in OP's pic is 3 squares "W" (fresh water) and 6 squares "s" (salt water). How does that work? Lol.
> 
> I can fix it easily, unless OP wishes to themselves.

Oh i'm not very good at codes and stuff, you can do it no problem.

**Comment by RandDenner** [comment]
All right. This will be my next project in the next day or two.

**Comment by ps-19** [comment]
Hi @RandDenner i have a question that, instead of salt water their should be fresh water?

**Comment by RandDenner** [comment]
@ps-19
I assume that it should mostly be fresh water, depending on the animals.
However, since some locations are partly salt water and partly fresh water, which is of course impossible in the real world, that some of the water coded as salt water is supposed to be **_deep_** water of one sort or another.

**Comment by ps-19** [comment]
@RandDenner 
Can i submit a PR with changing
"s": "t_swater_sh" to "s": deep water. 
I am asking because you want to work upon it or i might be wrong.

**Comment by RandDenner** [comment]
@ps-19
If you would like to make the PR to fix this, then please go ahead.

I have some advice for you, though.

As per your question "**But what is name of deep water like salt water is "t_swater_sh**"?":

If you search in all the game's json files for `t_water_sh` and/or `t_swater_sh` using either the "search in files" function of Notepad++ or the Everything app (which I highly recommend on Win10), you will see that their root definition file is `Cataclysm-DDA\data\json\furniture_and_terrain\terrain-liquids.json`.
Looking in that file will give you the IDs for other liquid terrain, including deep water (salt or fresh).

The only water that needs adjusting is in BOTH versions of `zoo_1_1`.
I believe that the "s" coded terrain should be shallow fresh water, while "W" coded terrain should be deep fresh water.

As a small issue, I believe the two characters in the pic below should be swapped (in both versions of this sub-map).
![image](https://user-images.githubusercontent.com/73523034/132240948-bd7f8e86-2326-4b14-8583-7a0032ea28cb.png)

And there's another issue. Some of the water terrain is coded as "FISHABLE". These pools, in a zoo for the use of the animals, should definitely NOT be. And it currently IS using those fishable terrain types, so they'll need to be changed.
There are two outdoor pool definitions in the terrain file (shallow and deep). I would change the coding to those types.

This should fix all issues. If you like, you can ping me to check your changes and I can help with any issues that come up.

Good luck, and have fun.
