### ISSUE TITLE
Off road bicycle wheels made using incorrect rims?

### ISSUE THREAD

**Issue by RandDenner** [CleverRaven/Cataclysm-DDA#51264]
### Describe the bug

The 27" off-road bicycle wheels are using the wide steel rim that wide vehicle wheels are also using, and not the bicycle rim.

### Steps To Reproduce

Just spawn them and look at the item info panel.

### Expected behavior

That bicycles don't use huge car tire rims.

### Screenshots

Wide steel rim and bicycle rim:
![image](https://user-images.githubusercontent.com/73523034/131558530-99f94361-e0d3-491b-8aaf-b6cc9a77af95.png)

### Versions and configuration

Win10 64, experimental tiles 2021-08-31-920 (0447a46), no mods

**Comment by RandDenner** [comment]
Ping: @occulti, this is your PR. Was this intended?

**Comment by RandDenner** [comment]
Oh, also the lengths are too small.
24" is 610mm
27" is 686mm

**Comment by RandDenner** [comment]
Also, volume is off.
Using the formula for a cylinder and a spreadsheet, I find that the volumes are pretty low, too.
Bicycle rim (27", 30mm wide) = 11L, motorcycle (20", 50mm wide) = 10L, medium steel (17", 19mm wide) = 28L, wide steel (24", 23mm wide) = 68L. (That 68L isn't a typo. Those are huge.)

**Comment by actual-nh** [comment]
Sounds like the motorcycle would be a better bet for matching, if off-road bike wheels are indeed wider in the rim (IIRC, they are).

**Comment by occulti** [comment]
@RandDenner Not intentional but an oversight - the intention was for off-road bicycle wheels to use the bicycle rim but I must have copy-pasted and not changed.

Thank you for the calculations too - the originals were just best guesses based on the dimensions and volume of the wheels themselves but these are much more accurate, will look to adjust now.

**Comment by RandDenner** [comment]
> Sounds like the motorcycle would be a better bet for matching, if off-road bike wheels are indeed wider in the rim (IIRC, they are).

Not so much wider that bicycle rims don't still basically make sense.
narrower ones use around 20 mm, wider ones are about 30mm, which I used for calculations.
Both are a lot narrower than motorcycle rims, but also a greater diameter (27" as opposed to motorcycle 20").
