### ISSUE TITLE
pathing error

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#51288]
### Describe the bug

I got a bug whilst auto-driving a car just before driving around a land post.

### Steps To Reproduce

Not sure, but I was auto-driving in a car through here

![image](https://user-images.githubusercontent.com/13402666/131684514-65a36461-99f9-4223-8cc9-b65135cc0d6b.png)

It seems to have happened just before the arrow when driving up. The game autosaved just after, so I don't have the save to reproduce.

### Expected behavior

No bug

### Screenshots

![image](https://user-images.githubusercontent.com/13402666/131684064-11d8bae2-aa64-4b23-9e6c-206611398464.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: c11072c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

<details><summary>debug.log</summary>

13:06:45.551 : Starting log.
13:06:45.551 INFO : Cataclysm DDA version c11072c
13:06:45.565 INFO : [main] C locale set to C
13:06:45.565 INFO : [main] C++ locale set to C
13:06:45.565 INFO : SDL version used during compile is 2.0.14
13:06:45.565 INFO : SDL version used during linking and in runtime is 2.0.14
13:06:45.640 WARNING : opendir [./sound/] failed with "No such process".
13:06:45.649 INFO : Number of render drivers on your system: 5
13:06:45.649 INFO : Render driver: 0/direct3d
13:06:45.649 INFO : Render driver: 1/direct3d11
13:06:45.649 INFO : Render driver: 2/opengl
13:06:45.649 INFO : Render driver: 3/opengles2
13:06:45.649 INFO : Render driver: 4/software
13:06:45.657 INFO : [options] C locale set to C
13:06:45.657 INFO : [options] C++ locale set to C
13:06:45.657 INFO : Setting language to: 'en'
13:06:45.657 INFO : Language is set to: 'en'
13:06:45.657 INFO : [translations] C locale set to English_United Kingdom.1252
13:06:45.657 INFO : [translations] C++ locale set to C
13:06:45.925 INFO : Active renderer: 0/direct3d
13:06:46.865 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
13:06:46.903 INFO : Setting language to: 'en'
13:06:46.903 INFO : Language is set to: 'en'
13:06:46.903 INFO : [translations] C locale set to English_United Kingdom.1252
13:06:46.903 INFO : [translations] C++ locale set to C
13:06:47.228 WARNING : opendir [./mods/] failed with "No such process".
13:10:02.762 WARNING : opendir [./save/Middle Earth/mods] failed with "No such process".
13:10:11.596 INFO : Loaded tileset: UltimateCataclysm
15:11:06.135 ERROR : src/item.cpp:9475 [int item::fill_with(const item&, int, bool, bool, bool)] tried to put an item (charcoal, amount 1) in a container (hsurvivor_suit) that cannot contain it
15:53:07.354 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:44.879 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.961 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.962 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.962 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.962 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.962 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.962 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:54:45.962 ERROR : src/map_memory.cpp:255 [const mm_submap& map_memory::get_submap(const tripoint&) const] Called map_memory with an 
15:55:19.222 :  GAME REPORT:
- OS: Windows
    - OS Version: 10.0 2009
- Game Version: c11072c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

15:58:02.253 : Log shutdown.
</details>

**Comment by actual-nh** [comment]
Ping: @eltank?

**Comment by eltank** [comment]
Looks like a map memory bug, I can't tell you much else. The map memory object was queried while its cache was empty, but as to how that happened I have no idea.

**Comment by Brambor** [comment]
I think it has something to do with pressing 5 (cancelling the auto-drive), but take it as a hunch. I'm not sure whether I pressed it before or after the bug.
