### ISSUE TITLE
Segfault crash when attempting to aim gun at Melded Task Force

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#51291]
### Describe the bug

I attempt to fight the Melded Task Force enemy, naturally with a gun because it is very scary. Whenever I am in range of the task force and attempt to aim my m27 assault rifle with 'f' the game locks up and crashes.

### Steps To Reproduce

1. Fight melded task force.
2. Aim gun at task force.
3. Game crashes?

### Expected behavior

I expect to die because it's actually secretly immune to bullets and I don't know it yet instead of crashing.

### Versions and configuration

ver bc1d00c. 

### Additional context

The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 0.E-3
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

  #0
    (dbghelp: @0x620ab6[cataclysm-tiles.exe+0x220ab6]), 
    (libbacktrace: Z21debug_write_backtraceRSo+0x56@0x620ab6),
    (libbacktrace: 0x620ab6    [unknown src]:0    [unknown func]),
  #1
    (dbghelp: @0x605bbf[cataclysm-tiles.exe+0x205bbf]), 
    (libbacktrace: log_crash+0x4af@0x605bbf),
    (libbacktrace: 0x605bbf    [unknown src]:0    [unknown func]),
  #2
    (dbghelp: @0x606892[cataclysm-tiles.exe+0x206892]), 
    (libbacktrace: signal_handler+0x32@0x606892),
    (libbacktrace: 0x606892    [unknown src]:0    [unknown func]),
  #3
    (dbghelp: SMPEG_error+0x4b034@0x10521e0[cataclysm-tiles.exe+0xc521e0]), 
    (libbacktrace: gnu_exception_handler+0x70@0x10521e0),
    (libbacktrace: 0x10521e0    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crt_handler.c:223    _gnu_exception_handler),
  #4
    (dbghelp: _C_specific_handler+0x98@0x7ffee40c7ff8[msvcrt.dll+0x27ff8]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #5
    (dbghelp: _chkstk+0x11f@0x7ffee58d217f[ntdll.dll+0xa217f]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #6
    (dbghelp: RtlRaiseException+0x434@0x7ffee5881454[ntdll.dll+0x51454]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #7
    (dbghelp: KiUserExceptionDispatcher+0x2e@0x7ffee58d0cae[ntdll.dll+0xa0cae]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #8
    (dbghelp: @0x6ccbf4[cataclysm-tiles.exe+0x2ccbf4]), 
    (libbacktrace: ZNK5field10find_fieldERK6int_idI10field_typeE+0x4@0x6ccbf4),
    (libbacktrace: 0x6ccbf4    [unknown src]:0    [unknown func]),
  #9
    (dbghelp: @0x9a1b98[cataclysm-tiles.exe+0x5a1b98]), 
    (libbacktrace: ZNK3map19get_field_intensityERK8tripointRK6int_idI10field_typeE+0x18@0x9a1b98),
    (libbacktrace: 0x9a1b98    [unknown src]:0    [unknown func]),
  #10
    (dbghelp: @0x9ebf0f[cataclysm-tiles.exe+0x5ebf0f]), 
    (libbacktrace: ZN3map15propagate_fieldERK8tripointRK6int_idI10field_typeEii+0x35f@0x9ebf0f),
    (libbacktrace: 0x9ebf0f    [unknown src]:0    [unknown func]),
  #11
    (dbghelp: @0x9ec853[cataclysm-tiles.exe+0x5ec853]), 
    (libbacktrace: ZN3map10emit_fieldERK8tripointRK9string_idI4emitEf+0xe3@0x9ec853),
    (libbacktrace: 0x9ec853    [unknown src]:0    [unknown func]),
  #12
    (dbghelp: @0x8ea72d[cataclysm-tiles.exe+0x4ea72d]), 
    (libbacktrace: ZNK10emit_actor3useER6playerR4itembRK8tripoint+0x5d@0x8ea72d),
    (libbacktrace: 0x8ea72d    [unknown src]:0    [unknown func]),
  #13
    (dbghelp: @0x8175b6[cataclysm-tiles.exe+0x4175b6]), 
    (libbacktrace: ZN4item7on_dropERK8tripointR3map+0x86@0x8175b6),
    (libbacktrace: 0x8175b6    [unknown src]:0    [unknown func]),
  #14
    (dbghelp: @0x9a4209[cataclysm-tiles.exe+0x5a4209]), 
    (libbacktrace: ZN3map19add_item_or_chargesERK8tripoint4itemb+0x5f9@0x9a4209),
    (libbacktrace: 0x9a4209    [unknown src]:0    [unknown func]),
  #15
    (dbghelp: @0x9a4bf5[cataclysm-tiles.exe+0x5a4bf5]), 
    (libbacktrace: ZN3map11spawn_itemsERK8tripointRKSt6vectorI4itemSaIS4_EE+0x135@0x9a4bf5),
    (libbacktrace: 0x9a4bf5    [unknown src]:0    [unknown func]),
  #16
    (dbghelp: @0x9a5631[cataclysm-tiles.exe+0x5a5631]), 
    (libbacktrace: ZN3map10bash_itemsERK8tripointR11bash_params+0x2b1@0x9a5631),
    (libbacktrace: 0x9a5631    [unknown src]:0    [unknown func]),
  #17
    (dbghelp: @0x9c2263[cataclysm-tiles.exe+0x5c2263]), 
    (libbacktrace: ZN3map4bashERK8tripointibbbPK7vehicle+0x103@0x9c2263),
    (libbacktrace: 0x9c2263    [unknown src]:0    [unknown func]),
  #18
    (dbghelp: @0x9c36df[cataclysm-tiles.exe+0x5c36df]), 
    (libbacktrace: ZN3map7destroyERK8tripointb+0x4f@0x9c36df),
    (libbacktrace: 0x9c36df    [unknown src]:0    [unknown func]),
  #19
    (dbghelp: @0x9cefbc[cataclysm-tiles.exe+0x5cefbc]), 
    (libbacktrace: ZN9MapExtrasL9mx_craterER3mapRK8tripoint+0xfc@0x9cefbc),
    (libbacktrace: 0x9cefbc    [unknown src]:0    [unknown func]),
  #20
    (dbghelp: @0x9e515a[cataclysm-tiles.exe+0x5e515a]), 
    (libbacktrace: ZN9MapExtras14apply_functionERK9string_idI9map_extraER3mapRK8tripoint+0x6da@0x9e515a),
    (libbacktrace: 0x9e515a    [unknown src]:0    [unknown func]),
  #21
    (dbghelp: @0x9e5493[cataclysm-tiles.exe+0x5e5493]), 
    (libbacktrace: ZN9MapExtras14apply_functionERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEER3mapRK8tripoint+0x43@0x9e5493),
    (libbacktrace: 0x9e5493    [unknown src]:0    [unknown func]),
  #22
    (dbghelp: @0xa40189[cataclysm-tiles.exe+0x640189]), 
    (libbacktrace: ZN3map8generateERK8tripointRK10time_point+0x1239@0xa40189),
    (libbacktrace: 0xa40189    [unknown src]:0    [unknown func]),
  #23
    (dbghelp: @0x9ac4cc[cataclysm-tiles.exe+0x5ac4cc]), 
    (libbacktrace: ZN3map5loadnERK8tripointb+0x62c@0x9ac4cc),
    (libbacktrace: 0x9ac4cc    [unknown src]:0    [unknown func]),
  #24
    (dbghelp: @0x9babad[cataclysm-tiles.exe+0x5babad]), 
    (libbacktrace: ZN3map4loadERK8tripointb+0xdd@0x9babad),
    (libbacktrace: 0x9babad    [unknown src]:0    [unknown func]),
  #25
    (dbghelp: @0x722cbb[cataclysm-tiles.exe+0x322cbb]), 
    (libbacktrace: ZN4game10start_gameEv+0x1cb@0x722cbb),
    (libbacktrace: 0x722cbb    [unknown src]:0    [unknown func]),
  #26
    (dbghelp: @0x98eca6[cataclysm-tiles.exe+0x58eca6]), 
    (libbacktrace: ZN9main_menu17new_character_tabEv+0x1d66@0x98eca6),
    (libbacktrace: 0x98eca6    [unknown src]:0    [unknown func]),
  #27
    (dbghelp: @0x993b9a[cataclysm-tiles.exe+0x593b9a]), 
    (libbacktrace: ZN9main_menu14opening_screenEv+0x87a@0x993b9a),
    (libbacktrace: 0x993b9a    [unknown src]:0    [unknown func]),
  #28
    (dbghelp: IMG_LoadWEBP_RW+0x67ac1b@0x17bec6b[cataclysm-tiles.exe+0x13bec6b]), 
    (libbacktrace: main+0x151b@0x17bec6b),
    (libbacktrace: 0x17bec6b    [unknown src]:0    [unknown func]),
  #29
    (dbghelp: @0x4013ed[cataclysm-tiles.exe+0x13ed]), 
    (libbacktrace: _tmainCRTStartup+0x23d@0x4013ed),
    (libbacktrace: 0x4013ed    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crtexe.c:336    __tmainCRTStartup),
  #30
    (dbghelp: @0x4014fb[cataclysm-tiles.exe+0x14fb]), 
    (libbacktrace: WinMainCRTStartup+0x1b@0x4014fb),
    (libbacktrace: 0x4014fb    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crtexe.c:186    WinMainCRTStartup),
  #31
    (dbghelp: BaseThreadInitThunk+0x14@0x7ffee4ad7034[KERNEL32.DLL+0x17034]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #32
    (dbghelp: RtlUserThreadStart+0x21@0x7ffee5882651[ntdll.dll+0x52651]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),

**Comment by anoobindisguise** [comment]
Confirmed same error in latest experimental.

**Comment by Venera3** [comment]
The only thing I can think of that they do differently to other mobs is I purposefully put their volume *just* below the HUGE category and gave them HARDTOSHOOT to protect them from grenades a bit. It might be that fusing with a zombie friend puts them above the limit but interacts weirdly with the aiming code. I spent a lot of time shooting them with different guns in testing, so it's extra weird.

**Comment by anoobindisguise** [comment]
I also got this error when attempting to melee it:
![invalid size class](https://user-images.githubusercontent.com/56016372/131718819-6f295947-3f27-4231-81a1-d60549841a31.PNG)

**Comment by anoobindisguise** [comment]
The game also crashes with the same segfault error when I attempt to x-look over them. Looks like the crash occurs whenever I attempt to get its description, the gun just automatically gets that crash because 'f' aim automatically targets it.

**Comment by actual-nh** [comment]
Descriptions are autogenerated with regard to monster size...
