### ISSUE TITLE
tie & Remove leash have the same keybinding

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#51290]
### Describe the bug

Wanna tie them, but I Remove leashes from them instead.
Also, push and lead by leash have the same keybinding.

### Steps To Reproduce

Tie turkey, examine them.

### Expected behavior

When I press [t] I will now what will happen. Also, every keybinding listed at most once.

### Screenshots

![image](https://user-images.githubusercontent.com/13402666/131707435-dc8e8be5-01da-4c8e-8302-d8f61fe18862.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: c11072c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by PatrikLundell** [comment]
Change one of each pair to upper case?

**Comment by anothersimulacrum** [comment]
The `p` argument here needs to be something else
https://github.com/CleverRaven/Cataclysm-DDA/blob/717e695188fedda09991589847042de90ae3c522/src/monexamine.cpp#L583-L589

and the `t` argument here
https://github.com/CleverRaven/Cataclysm-DDA/blob/717e695188fedda09991589847042de90ae3c522/src/monexamine.cpp#L615
