### ISSUE TITLE
Endless flask's whiskey unusable for anything but drinking

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#51300]
### Describe the bug

Even once poured from the flask, the whiskey from the endless flask can't be used to craft mixed drinks or for other purposes.

### Steps To Reproduce

Have an endless flask, find that it provides something useless for all the purposes you'd put whiskey to other than drinking it straight.

### Expected behavior

I'd expect that something called whiskey be able to be used for all the purposes to which you could normally put it. I want it to be like that because at the moment it requires googling the issue to discover that it's not a bug, and that's not great design.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    No Rail Stations [No_Rail_Stations],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

Having googled the issue, I can see that this invisible failure is because of "balance", but if you want it for balance purposes, better to have the flask provide some other, magical liqueur, rather than calling it the same as an item that actually has purposes in game.

**Comment by Brambor** [comment]
Or if it must be whiskey, leave in the description that it is "such a rare and special kind it cannot be used for crafting".
