### ISSUE TITLE
Blood Power Generator CBM charges differently from container or vehicle.

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#51301]
### Describe the bug

If I have 10 units of blood in a jug, I can add it to the CBM, and I get 10 units of charge, leaving me with an empty jug. If I have 10 units of blood in a vehicle's tank I can siphon it to add to the CBM, and I get 10 units of charge and am left with 9 units of blood in the vehicle. 

### Steps To Reproduce

Have blood in a vehicle's tank, siphon it, see a mismatch between charge and remaining amount.

### Expected behavior

I'd expect it to work like it does from a regular container, because that's how conservation of mass works.

### Screenshots

![image](https://user-images.githubusercontent.com/6834262/131761834-2ac56be2-0b9a-45bc-8304-395ad9b0c2d1.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    No Rail Stations [No_Rail_Stations],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by hexagonrecursion** [comment]
> And now this generator isn't working at all

@Shootnik01 please report this as a separate issue instead of hijacking an existing thread - this makes it easier to keep track of troubleshooting and debugging efforts. Thank you.

This bug should be closed because it is no longer possible to refuels the CBM from a vehicle tank.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: eacb7d9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]
]

**Comment by Shootnik01** [comment]
> ]

It's already fixed, thank you:)
