### ISSUE TITLE
Winded infected characters never regain stamina after a point

### ISSUE THREAD

**Issue by Pooshmeu** [CleverRaven/Cataclysm-DDA#51316]
### Describe the bug

If you get "winded" (0 stamina) in an infected character, it never regains stamina, even if you are in ideal circumstances (comfortable temperature, basic needs reset on debug menu, high morale, no pain)

However, as soon as you set stamina to something above a certain margin, character stamina can recover.

### Steps To Reproduce

1-create the standard character, "infected" scenario.
2-teleport to a basement, run untill "winded" effects kicks in
3-maybe repeat a few times, there'll come to a point when the bug will start to happen.
4-when you start having this problem, make your character winded again
5-go to debug>reset all player needs>set pain to 0>put comfortable clothes>set morale to something high
6-wait for a very long time, character will never regain staminal, it may eventually regain stamina, but if you repeat it'll stay without stamina again for days

### Expected behavior

even if someone is infected, it doesn't mean that you are out of breath 24/7, if any player gets infected and for some reason has to run and get out of breath, the character will stay out of breath for as long as the character is infected(which means days to come), this can be a death sentence.

Player could even get this effect by carrying too much weight for example, or even butchering, since these activities spend stamina.

### Screenshots

no need

### Versions and configuration

-W10
-tiles
-build number: 2021-08-17-2240
-language: english
-only "dda" in modlist

### Additional context

I was talking to venera and told me this is actually intentional

in an infection, you should actually be wasted, weak, thirst as hell, and all of that, exhausted, and in dire need of antibiotics

but lets say I'm recovering from the infection, a wasp, lots of slimes, or something dangerous goes after me, all I can do is run to a basement on the other side of the street, my character will be barely able to do that, but that'll be an awesome feat, I'll run out of breath, escape from the zombies, sleep for 8 hours and wake up still out of breath?

this doesn't make sense at all, if a dodgy zombie gets inside my basement, I run out of breath killing it, sleep for 8 hours, only to wake up and die for a zombie child because even after sleeping for 8 hours I'm still out of breath.

If I was only able to get inside a pharmacy/doctor office after some time infected, which is a very hard thing to do, I'll never be able to leave the pharmacy/office, because even if I wait 2 hours inside it getting some rest, I'll still be out of breath.

Instead of cancelling stamina regenration altogether, a more appropriate thing to do in case of infections is to make the stamina consumption bigger, and a slightly lower stamina regeneration.

there's currently a lot more things to do for infection if this feels too much like a "nerf" to infection, 
  -it could also reduce perception (currently it doesn't)
  -it could cause pain from time to time
  -could make the player occasionally cough, 
  -it should make the player less hungry (this is realistic) making food consumption a pain in the ass (a message may appear just to make sure the player doesn't stop eating, "you are infected, you need to rest, drink fluids, and eat well. Antibiotics help you fight the infection")

  -a very cool thing, would be that the infected limb loses some HP after some time infected, when the player eventually goes trough the infection, the limb is not 100% fine like it currently is.

all of this is possible with .json only changes, reducing morale would also be more fitting (who wants to study or craft if you have a fever) but I'm not sure if this can be achieved with json only changes, and also, coughing if it's the torso that is infected, but maybe this too is not possible with json changes

**Comment by actual-nh** [comment]
Ping: @Venera3?

**Comment by Venera3** [comment]
As I said, the effect does what it intends to do within the confines of the current infection framework. Raising stamina consumption of actions isn't an doable with JSON to the best of my knowledge, and with how deep the stamina pool is it would be of little consequence. Also, a survivor in septic shock not being able to beat a zombie to death is more realistic than the alternative.

See  #48461 for some discussion.

**Comment by actual-nh** [comment]
> See #48461 for some discussion.

Thank you, I'll keep that handy.
