### ISSUE TITLE
No way to place non-human corpses in json mapgen

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#51311]
# Is your feature request related to a problem? Please describe.
Basically, the title. `corpse` item is human corpse.

# Describe the solution you'd like
Create an object with a parameter for type of creature whose corpse it is. Something like this:

```
{ "type": "corpse", "creature_type": "mon_dog" }
```

# Describe alternatives you've considered
None.

# Additional context
None.

**Comment by Venera3** [comment]
Dynamic (pseudo)items for corpses would also be useful for harvet lists - I have mutant meat chunks as a stand-in for dermatik larvae in the incubator lists, for example.

**Comment by Night-Pryanik** [comment]
Resolved by #53782.
