### ISSUE TITLE
Examine (e, E) keybindings don't work in Multidrop interface (d, D)

### ISSUE THREAD

**Issue by TripleSixPeasant** [CleverRaven/Cataclysm-DDA#51322]
### Describe the bug

Examine (e, E) keybindings have no effect when in Multidrop interface (d, D).

There is a similar issue here: https://github.com/CleverRaven/Cataclysm-DDA/issues/50860, but I believe this is defferent because, as explained above, numbers are used to specify the amount to be dropped. Examine keys however don't have overlapping functionality in this interface as far as I can tell. 

### Steps To Reproduce

1. Open Multidrop UI (d)
2. Navigate to any item
3. Press E or e to see no effect

### Expected behavior

I expect to see the item's detailed description, like in Advanced Inventory Interface for example.

### Versions and configuration

- OS: MacOs
    - OS Version: Name: macOS; Version: 11.5.2; Build: 20G95; 
- Game Version: 0.F-2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    C.R.I.T Expansion Mod [crt_expansion],
    DinoMod [DinoMod],
    Generic Guns [generic_guns],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by ZeroInternalReflection** [comment]
Looking at inventory_ui.cpp in 0.F-2, it does not actually have the code for examining in inventory_drop_selector (or inventory_compare_selector), which would explain why it's not working. 

Both should work the way you expect in the latest experimental thanks to #50793 (based upon a very similar issue #50774 ).  However, it looks like this change was not included in 0.F-2.

**Comment by TripleSixPeasant** [comment]
Ah, that's why it didn't come up in search - I was only searching open issues. All good then, sorry about creating a duplicate.
