### ISSUE TITLE
A fresh enchanted tailor's kit won't reload with thread

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#51329]
### Describe the bug

Despite being loaded with something called "thread" when purchased, the enchanted tailor's kit won't reload with thread from elsewhere, not even from a spider box which is described as being included with the enchanted tailor's kit. You have to use up the initial "thread" before you can reload it normally.

### Steps To Reproduce

Buy an enchanted tailor's kit. Have thread, try to reload. Use up existing "thread", successful reload.

### Expected behavior

I'd expect to be able to reload the enchanted tailor's kit immediately.

### Screenshots

![image](https://user-images.githubusercontent.com/6834262/131955124-ee0de86c-28f4-45ba-b8f1-dd9f28cca1d2.png)
![image](https://user-images.githubusercontent.com/6834262/131955457-8981d55c-47d3-4227-b6bf-880084659a75.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    No Rail Stations [No_Rail_Stations],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by RandDenner** [comment]
So I took a look at the json files for the regular games' tailor's kit and the ones in this mod, and I don't see any data or formatting problems.
The only thing I can think may be an issue is in this image
![image](https://user-images.githubusercontent.com/73523034/132109660-37ea0e0f-cd13-46a7-8852-69b75e372d86.png)
I wonder if the regeneration is bugging out the reloading function until the item is empty of "ammo" (which is what thread literally is counted as by the game).
An easy test would be to remove this relic_data line and see if the thread can be reloaded and expected.

**Comment by GuardianDll** [comment]
in this case it will lost his ability to regenerate threads
the issue is somewhere in the code i guess

**Comment by Night-Pryanik** [comment]
Can't confirm on latest experimental as of 01 November 2024.
