### ISSUE TITLE
Refueling gasoline fuel cell CBM directly from a gas tank doesn't work correctly

### ISSUE THREAD

**Issue by The-Numbers** [CleverRaven/Cataclysm-DDA#51334]
### Describe the bug

When attempting to siphon gas directly from a car to fill a bionic, it tells you that it "that doesn't look edible" because you can no longer consume gas to fuel the CBM.

### Steps To Reproduce

1. Install a power storage cbm and a gasoline fuel cell CBM
2. get a tool with the siphoning quality and a vehicle with a filled gas tank.
3. (s)iphon the gas tank
4. fuel bionic with it
5. receive response"that doesn't look edible"

### Expected behavior

I expect it to refuel my CBM, but instead it tries to consume the gas.

### Versions and configuration

Windows 10
game version 91a3fc
tiles
english
mods loaded: disable npc needs, bionic professions, blaze industries, crit expansion mod, magicysm, no fungal monsters, stats through skills.

**Comment by hexagonrecursion** [comment]
I could not reproduce this issue. What I did:
1. Install a gasoline fuel CBM and a Power Storage Mk II
1. Debug wish for a rubber hose
2. [a]ctivate
3. Select the rubber hose
4. I get a menu that only offers me to:
    * Pour into a container
    * Fill available tank
    * Pour on the ground

    Non of this 3 options show the gasoline fuel CBM as a possible destination

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: eacb7d9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
