### ISSUE TITLE
Safecracking fails silently with Enhanced Hearing CBM installed and turned off

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#51336]
### Describe the bug

If you don't have a way to listen to a safe, you spin the dial. If you do, you try to crack the safe. If you have the Enhanced Hearing CBM turned off it says that you try to crack the safe, but it stops immediately without explaining why.

### Steps To Reproduce

Have enhanced hearing, make sure it's off, try to crack safe.

### Expected behavior

I would expect one of: 

1. If the CBM is off, give the "no tool" result of spinning the dial.
2. Automatically turn on the CBM when you try to crack the safe.
3. Tell the player that they need to turn on their Enhanced Hearing CBM to try to crack the safe.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    No Rail Stations [No_Rail_Stations],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Saicchi** [comment]
Can't replicate on `0.F-2271-gb92e5a073a`, but keep in mind that this issue game version is `0.F-1`.

https://github.com/CleverRaven/Cataclysm-DDA/blob/bc28921102f05a092c103dd2af265439a9934d61/src/iexamine.cpp#L1509-L1510

https://github.com/CleverRaven/Cataclysm-DDA/blob/bc28921102f05a092c103dd2af265439a9934d61/src/activity_handlers.cpp#L3023-L3034

https://github.com/CleverRaven/Cataclysm-DDA/blob/bc28921102f05a092c103dd2af265439a9934d61/data/json/bionics.json#L357-L366

On `iexamine::safe` the code checks to see if the player has the `IMMUNE_HEARING_DAMAGE` to start safe cracking, but on `activity_handlers::cracking_do_turn` it checks for the active flag `SUPER_HEARING`, which is only present if the bionic is active.

On experimental this is fixed.

https://github.com/CleverRaven/Cataclysm-DDA/blob/f064b186128348feefdfa909dbf40347546dd5b3/src/iexamine.cpp#L1519-L1521

**Comment by MrHrulgin** [comment]
I checked the fixed error reports to see if it had been resolved and didn't see it, so I guess it was resolved without a bug report being submitted. Thank you for checking.
