### ISSUE TITLE
Hub 01 Free merchants attack Hub 01 drones

### ISSUE THREAD

**Issue by Zeropol** [CleverRaven/Cataclysm-DDA#51335]
### Describe the bug

The Free merchants that spawn in the Hub 01 attack the Hub 01 drones introduced by #51161.

### Steps To Reproduce

1. Do the first hub01 missions
2. ( maybe unrelated ) start the "radio mission" with the mercenary that just spawned inside the building.
4. See the drone is hostile. 
5. Move to the Free merchants that also just spawned in the backyard.
6. See the Free merchants fight the drone

### Expected behavior

The Free merchants understand the drone is not dangerous,
or,
the drone is not hostile to them and the player.

### Screenshots

![image](https://user-images.githubusercontent.com/28099824/132028614-985cc316-c5e8-42da-9a63-70828698a945.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-2219-g5aff6c266b [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA],
    No Rail Stations [No_Rail_Stations],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex]
]

### Additional context

Despite I had not attacked the drone ( nor rammed with car ), it was also hostile on me but did not attacked me.

I noticed the drone was hostile only when I started the "radio mission" with the mercenary that spawn inside the hub 01 buiding so I don't know if it was hostile before or not.

And may be related or not : when the merchands and the drone spawned, I heard "Crashs" from "North West and below"

**Comment by pehamm** [comment]
Is this related to the Hub being set to hostile? When looking at the factions display (#), it always shows the hub relation as “Archenemy”, even when on the best relations, probably to ensure they attack you of you ever dare to break in.

**Comment by Maleclypse** [comment]
@John-Candlebury is this still happening or should I close this?

**Comment by Zeropol** [comment]
I think it is closed by #53686 by I have not tested

**Comment by AdamChirnside** [comment]
This is fixed
