### ISSUE TITLE
Overfull warning when adding blood to CBM

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#51351]
### Describe the bug

If you eat until full, and then "eat" blood to add it to a CBM, you get the warning that you're full and shouldn't eat any more, despite it not going to your stomach.

### Steps To Reproduce

Be full. Try to add blood to CBM. See error.

### Expected behavior

I'd expect that if you are sending material somewhere other than your stomach, you won't get the warning that your stomach is too full.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    No Rail Stations [No_Rail_Stations],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by hexagonrecursion** [comment]
This should be closed - CBMs are now refueled via the [p] bionics menu instead of the [E]at menu

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: eacb7d9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]
]
