### ISSUE TITLE
Use of sprites in the description of items and creatures

### ISSUE THREAD

**Issue by Entity-y** [CleverRaven/Cataclysm-DDA#51357]
# Is your feature request related to a problem? Please describe.
The descriptions are great, it's what gives this game depth and character, but there is only so much room for a written description in the examine window. Pictures are worth a thousand words and as this game evolves we should go beyond ASCII art to represent the finer details.
# Describe the solution you'd like
Adding a new section to the description that displays a larger more detailed sprite for weapons and monsters. Like with the ASCII art in item and monster descriptions we would have a section for .png files. This would allow for a hand drawn sprite, a render, or a real world picture to represent firearms, animals, monsters, and other items.
# Describe alternatives you've considered
Having an even closer zoom level in game that uses these larger more detailed sprites.
# Additional context
![Screenshot 2021-09-04 025519](https://user-images.githubusercontent.com/50155659/132086101-89a8ed00-4dd2-4604-a1d7-ef49c7465b18.png)
![Untitled](https://user-images.githubusercontent.com/50155659/132086427-5c87acaa-7c43-4a06-98df-57fa1bfa889c.png)

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
