### ISSUE TITLE
All characters always start with overweight

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#51366]
### Describe the bug

No matter if it's a random or customized characters, they always start with overweight.

Looking through the debug menu showed that new character has stored value of 55010 kCal. Debug-changing stored kCal value to strictly 55000 fixes the bug and gives the character normal weight. I'm not sure where these excessive 10 kCal came from.

### Steps To Reproduce

Start a game with random or customized character, look at the @-menu.

### Expected behavior

New characters have normal weight, unless they have XS or XXL traits.

### Versions and configuration

Windows 10, tiles, 0.F-2247.

**Comment by ps-19** [comment]
hi @kevingranade i am new to this repository, i would love to work upon any issue.

**Comment by Saicchi** [comment]
Is this really an issue? I thought the intention was to give the player a few extra calories to live with. As far as I know being overweight is not a detriment to the player.

**Comment by Night-Pryanik** [comment]
55000 stored kcal means normal weight. I suppose the game doesn't update some function related to bmi or calories when the game starts because when I tried to resolved this issue by myself and changed `healthy_calories ` to 45000, 40000, 35000, the result was still overweight, even with 35000 stored kcal.

**Comment by aoae23** [comment]
> hi @\kevingranade i am new to this repository, i would love to work upon any issue.

@ps-19 please check out this link to learn how to start contributing: https://github.com/CleverRaven/Cataclysm-DDA/wiki/Guide-to-adding-new-content-to-CDDA-for-first-time-contributors

**Comment by actual-nh** [comment]
> Is this really an issue? I thought the intention was to give the player a few extra calories to live with. As far as I know being overweight is not a detriment to the player.

That in and of itself qualifies as a bug in terms of realism...

**Comment by Skrassh** [comment]
Looking into this it seems that the overweight part clears up within 10 minutes (in game time) of starting. My uneducated guess as to whats happening is that we start the player off with calories in their stomach, which turns in to small amounts of calories that push us over the 55k stored kcal. 

So is this actually an issue that needs any kind of fix?

**Comment by Night-Pryanik** [comment]
Yes. If weight is turning to normal in 10 minutes in any case, as you say, why wait said 10 minutes? This makes absolutely no sense.

**Comment by matshou** [comment]
> My uneducated guess as to whats happening is that we start the player off with calories in their stomach, which turns in to small amounts of calories that push us over the 55k stored kcal.

Your *uneducated* guess seems to be correct:
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/stomach.cpp#L304-L312
