### ISSUE TITLE
Sweets cookbook doesn't spawn in game

### ISSUE THREAD

**Issue by Secret-Cisco** [CleverRaven/Cataclysm-DDA#51384]
# Is your feature request related to a problem? Please describe.
The `"sweets_book"` _Sweets for your Sweet Child_ doesn't spawn anywhere in the game because it's not in an item group.

# Describe the solution you'd like
Add it to the relevant book groups.

# Describe alternatives you've considered
Remove the book?

# Additional context
https://github.com/CleverRaven/Cataclysm-DDA/blob/cb9d2614ad6994edc0d9e816f5bcdb5998f29706/data/json/items/book/cooking.json#L460

https://github.com/CleverRaven/Cataclysm-DDA/search?q=%22sweets_book%22&type=code

**Comment by Brambor** [comment]
There could be some kind of check if every item is obtainable - as a drop, spawn, recipe or deconstruction.
