### ISSUE TITLE
Door locks

### ISSUE THREAD

**Issue by Entity-y** [CleverRaven/Cataclysm-DDA#51383]
# Is your feature request related to a problem? Please describe.
Even though most doors should be capable of being locked, the player is unable to lock doors.
# Describe the solution you'd like
From inside of a room, the closed door is able to be locked by closing once again, similar to a curtain on a window. Unless the player built the door and has a theoretical key, preexisting doors that are typically locked in the game would need to be picked or pried into once again from the outside.

Using the small lock and key, a player could add a lock onto a door (or anything really) via the construction menu. This would allow for getting that theoretical key for a preexisting locked door by swapping out the locks, and a method of locking any furniture container.

The doors of a vehicle should be capable of being locked as well. This too could use the small lock and key or with an electronic lock to control remotely. Child safety locks could be added to doors to prevent being opened from the inside, also able to be controlled remotely.

This would mean vehicles could have an extra layer of security and when bypassed by prying might end up tripping the security alarm, giving careful lockpicking an edge for once. Slim jims or a makeshift wire variant could be added to unlock the vehicle doors with a lesser chance at tripping the alarm.

# Describe alternatives you've considered
Giving a key to all preexisting locked doors once bypassed, ideally we would have spare house/car keys occasionally appearing around a house or on the occupants for nearby doors and vehicles.

More prevalent home security systems that's actually connected to a power grid, should the house happen to have solar power or a backup generator. The security system should be an actual object attached to a wall that can be hacked or have the batteries ripped out of just moments before the alarm goes off. Maybe a programmable code could be entered into the system to toggle armed/disarmed status.

**Comment by Numbuh474** [comment]
I'm working on a patch for the vehicle side of this.

Current behavior is that having an installed door motor enables the locking feature.

I feel like it would also make sense to have certain doors, like the ones seen on most cars, be inherently lockable. Others, for example military vehicle doors, should not be inherently lockable as they typically aren't IRL but they should still be modifiable. Any thoughts on this?

**Comment by Zireael07** [comment]
IIRC this has been recently fixed?

**Comment by Numbuh474** [comment]
If you're referring to #48902 that is still pending review/merge.
