### ISSUE TITLE
Hoader Trait takes into consideration improper containers

### ISSUE THREAD

**Issue by Pooshmeu** [CleverRaven/Cataclysm-DDA#51392]
### Describe the bug

Hoarder trait takes into consideration, impossible to fill containers, like a sheath with a combat knife, an ammo leg pouch with already 2 STANAG 30 rounds magazines, semi empty plastic canteens, etc.

Those are containers that, ocasionally, can never be 100% volume filled.

Hoarder right now is more of a nuisance than a gameplay element, because you are constantly trying to squeeze items in and out of containers, this should be fine, but the amount of time you spend searching for little items soon gets old (you are constantly having to scroll, exhaustively, trough your items to decide how you are going to fill every 0,01L remaining pockets).

While the player should deal with the traits he chose, it should blend into the gameplay instead of being a nuisance, if it's a hoarder, he should just grab a few rags or empty bottles, and roll with it, gets close to 100% volume, and roll with it, the only way to do this is with a small volume tolerance, as not to force to player to exhaustively search little items.

### Steps To Reproduce

No need

### Expected behavior

No need

### Screenshots

No need

### Versions and configuration

-W10
-tiles
-build number: 2021-08-17-2240
-language: english
-a lot of mods

### Additional context

I guess an implementation of the following is appropriate:
   -for pockets that can only have one item like sheathes, exclude such pockets entirely from the formula
   -allow a small tolerance before the trait starts to eat morale

**Comment by Gooseheaded** [comment]
How about changing the Hoarder trait so that instead of asking the player to be at 100% encumbrance, we lower the percentage down to, say, 95%?

That should give players _just enough freedom_ so they never have to look for infinite tiny objects, while still maintaining the fantasy of "being pretty much full pretty much all of the time."

**Comment by strategineer** [comment]
This issue seems to have been fixed by #51864, this can be closed.
