### ISSUE TITLE
Significant lag after updating past c11072c

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#51390]
### Describe the bug

On about the 31st of August I had intended to update from version c11072c but after experiencing significant lag I held off assuming it would be a temporary issue. However it has still persisted, and makes the game much less enjoyable. It is present everywhere, not just in game - loading saves, both new and old, is much slower, and the game gets especially held up on "mapgen weights". Tabbing to large crafting menu sections such as Armor takes about five seconds when it took one previously. Booting up the game takes longer as well. In game, there is noticeable input lag and passing time while crafting is significantly slower as well. Essentially, everything about cata runs slower. I have tried changing my renderers from direct3d with no luck.

### Steps To Reproduce

Compare version c11072c to current experimental. I'll attach a save file as well in case it is needed. Play it on c11072c, then try loading in current experimental and hopefully notice much longer load time and significant input lag.
Alternatively - upgrade 1 version at a time from c11072c and attempt to pinpoint where the slowdown begins.

### Expected behavior

Even if my computer was bad it wouldn't explain how cata was running fine until it wasn't. I feel like something somewhere broke and deoptimized the game, and while I can't prove it happens outside of my own computer I'd like to at least see if anyone else experiences this and if there's any way to resolve this.

### Screenshots

[Cantwell.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7111311/Cantwell.zip)

### Versions and configuration

Experimental version c11072c is what I'm currently on due to lagging issues, it seems to have begun some point beyond that.

**Comment by BrettDong** [comment]
What’s your operating system, and did you download from GitHub or compiled yourself?

**Comment by anoobindisguise** [comment]
Running on windows 10 and running the version from the launcher.

**Comment by anoobindisguise** [comment]
OK, I changed over to 313fa33, the end up updates for the following day, and once again lag is present there. I'm in the middle of nowhere and confirmed with debug that there are only 4 giant aphids nearby and nothing else and sleeping is noticeably slow, normally the loading wheel spins extremely fast but it takes about a second to complete a revolution, compared to 5-10 per second on c11072c. So my issues started due to a change made between those versions most likely.

**Comment by BrettDong** [comment]
Are you playing with tiles or ASCII, if tiles, which tileset are you using?

**Comment by anoobindisguise** [comment]
Tiles and it is present on both chibi ultica and msx+, I guess I didn't test the others.

**Comment by anoobindisguise** [comment]
OK. I'm going to close this, my game was in x86 32bit mode. For whatever reason, possibly my clumsiness, the launcher was set to that setting. I tried downloading manually a 64bit version and it worked fine, then tried updating with 64bit in the launcher - fine. Sorry for false positive.
