### ISSUE TITLE
Glass walls still have 90% coverage

### ISSUE THREAD

**Issue by ISuckM8** [CleverRaven/Cataclysm-DDA#51400]
### Describe the bug

Glass walls, the ones that can be found at normal houses at least, have 90% coverage. This is higher than a window's coverage. It doesn't make any sense, glass doors have 0% coverage though.

### Steps To Reproduce

Just press X and aim at a glass wall, or crouch next to it.

### Expected behavior

It should have 0% coverage, just like the glass door.

### Versions and configuration

1fa1d84

### Additional context

If it's a frosted wall, can we change the name to "Frosted Glass Wall" to clear confusion?

**Comment by Vendidurt** [comment]
Since it presumably does not reach the floor, it should have some level of coverage.

**Comment by occulti** [comment]
Can confirm in 4d92cc6 (tiles)

![Glass Wall](https://user-images.githubusercontent.com/87604321/132955390-5ff85128-734d-4140-ae66-b2fc1cbfbba3.png)

Glass walls are used in a lot of mapgen to represent large windows (bakery, fast food restaurant, gym and a load of houses to name a few) so taking the below image as a reference I would say coverage of 25-30% with the wall along the bottom, will look to alter to this.

![CFKF2F](https://user-images.githubusercontent.com/87604321/132955455-83024e1c-c75d-45e7-9adb-b33696d7a64a.jpg)
