### ISSUE TITLE
Circular dependency in aftershock

### ISSUE THREAD

**Issue by Theawesomeboophis** [CleverRaven/Cataclysm-DDA#51403]
### Describe the bug

 DEBUG    : (json-error)
Json error: data/mods/Aftershock/items/obsolete.json:340:3: JSON contains circular dependency, this object is discarded

    "looks_like": "depowered_helmet"
  },
  {
  ^

    "id": "afs_survivor_belt",
    "copy-from": "survivor_belt",

 FUNCTION : void DynamicDataLoader::load_deferred(DynamicDataLoader::deferred_json&)
 FILE     : src/init.cpp
 LINE     : 181
 VERSION  : 0138041
I get this skippable error while loading aftershock and thought I should report it.

### Steps To Reproduce

1. Make World With Aftershock
2. Create new game in world
3. Skip with I.

### Expected behavior

The circular dependency to not exist.

### Versions and configuration

OS: Windows 8.1
Version: Current experimental as of writing
Graphics: Tiles

**Comment by Theawesomeboophis** [comment]
I am also getting an error about fusion being a nonexistent ammo type
 DEBUG    : Tried to get invalid ammunition: fusion

 FUNCTION : const T& string_id<T>::obj() const [with T = ammunition_type]
 FILE     : src/ammo.cpp
 LINE     : 53
 VERSION  : 0138041
Don't know if this is from aftershock or something else though.

**Comment by Mom-Bun** [comment]
The first error is easily fixable, just need to prune out our obsoletion list

second one is...

Can we please have your mod list? Because we don't use "fusion" we use "hydrogen" for the plasma guns

**Comment by Theawesomeboophis** [comment]
Ok, I will submit that error to Kenan, thank you.

**Comment by anothersimulacrum** [comment]
Fixed in https://github.com/CleverRaven/Cataclysm-DDA/pull/51483?

**Comment by Theawesomeboophis** [comment]
It has been fixed, thanks for reminding me to close this.
