### ISSUE TITLE
OVERSIZE & UNDERSIZE crafting options

### ISSUE THREAD

**Issue by Drew4484** [CleverRaven/Cataclysm-DDA#51405]
# Is your feature request related to a problem? Please describe.
Currently there is a very limited number of options for oversize and undersize crafts. However in most cases, the item being created is being made from scratch, meaning that the crafter could make it of an appropriate size for a large or small character at the cost of more or less resources.

# Describe the solution you'd like
An option when crafting to select an item's size. This would be applicable to most clothing and armor, and would require a determined conversion factor in required materials for XL/XS.

# Describe alternatives you've considered
Manually adding OVERSIZE and UNDERSIZE versions of all items that don't have an existing piece of armor or clothing as a core component (i.e. chainmail suit requires a regular sized chainmail vest or equivalent amount of chainmail sheet.)

Making OVERSIZE/UNDERSIZE a clothing mod like the existing linings and paddings. Not practical for things that can't be repaired with the tailoring kit, also it doesn't make sense to sew together a jacket then go back to remove or add half again the material to make it the right size.

# Additional context
This could also be applied to things like melee weapons, that adds a whole extra set of problems with balance of those weapons.

It might also be useful as a framework to support clothing for survivors with more than the usual number of limbs.

**Comment by UmbralReaper** [comment]
Relevant: #47762
