### ISSUE TITLE
Tutorial Uses Default Mod List, Should Force Vanilla

### ISSUE THREAD

**Issue by TheMurderUnicorn** [CleverRaven/Cataclysm-DDA#51413]
### Describe the bug

Trying to boot up the tutorial loads your default mod list.  If you have broken mods in your default mod list, this breaks the tutorial's ability to load.  Updating the default mod list does not fix this problem, you actually have to delete the tutorial world AND update your default mod list before attempting to load the tutorial.  This will not be obvious to new players who jump into the game, may possibly use broken mods, and then find themselves locked out of the tutorial.

### Steps To Reproduce

1. Have a default mod list
2. Load Tutorial
3. Observe that it attempts to load your default mod list
4. Update default mod list in the world creation menu
5. Reload tutorial (by using the special options -> tutorial)
6. Observe that it tries to load your original mod list (because the tutorial world was already generated as soon as you tried to load it the first time)
7. The only way to fix this is to delete the world that is generated from the World-menu AND update your default mod list to not include broken mods, something that is not obvious to a new player.  This will generate the tutorial world again with your new default mod list.

### Expected behavior

I believe that the tutorial should force vanilla only.  There will inevitably be players who set up a world, save defaults with broken mods, and then try the tutorial, which will then not load.  I know this is a bit niche but it's an issue.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0138041 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Caches [P_Caches],
    Oa's Additional Buildings mod [oa_additional_buildings_mod],
    No Fungal Monsters [No_Fungi],
    StatsThoughSkills IV [StatsThroughSkillsFour]
]

### Additional context

I'm not sure if there's support at the moment for forcing vanilla or not.  The only solution I can think of is to force use only DDA when starting the tutorial.  I can't think of a way to illustrate to new players that they will need to delete the TUTORIAL world from their world-menu and fix their default mods to solve the tutorial loading issue.

**Comment by Night-Pryanik** [comment]
One part of this issue comes from saving and loading the tutorial world. We probably should disallow saving tutorial world altogether.
