### ISSUE TITLE
Make Computer (practice) recipies Dark craftable

### ISSUE THREAD

**Issue by LilimDiam** [CleverRaven/Cataclysm-DDA#51412]
# Is your feature request related to a problem? Please describe.
Currently you cannot practice computer recipe in the dark, which doesn't really make much sense considering that you are doing it on a phone or computer screen.

# Describe the solution you'd like
All computer practice recipes to have "Craftable in the dark? Easy".

# Describe alternatives you've considered
Doing nothing and continuing to learn hacking in a brightly lit room.

# Additional context
![image](https://user-images.githubusercontent.com/90160875/132144644-49b44fb3-2f6d-42a2-a175-932a601c4fb0.png)

**Comment by Qrox** [comment]
There should be a separate flag that says the crafting recipe provides light itself, because currently the dark craftable flag also makes the recipe craftable when blind.

**Comment by LilimDiam** [comment]
> There should be a separate flag that says the crafting recipe provides light itself, because currently the dark craftable flag also makes the recipe craftable when blind.

I don't think it's necessarily worth the effort it would take, and blindness isn't really a common issue when you're at your home base

**Comment by Qrox** [comment]
The player is not restricted to practicing hacking at home base though, however unlikely that may be. It would be hilarious if a boomered player can wait the blinding effect to wear off by pracitcing hack.

**Comment by wapcaplet** [comment]
See #51207 for some challenges resolving this
