### ISSUE TITLE
Allow each different save files to choose different default tilesets for themselves (or default to the global default tileset).

### ISSUE THREAD

**Issue by ifffrt** [CleverRaven/Cataclysm-DDA#51423]
# Is your feature request related to a problem? Please describe.
Cataclysm is a game that can offer drastically different experiences in tone and game-feel depending on what kind of mod you chose to enable. For example, a basic, DDA-only game will differ a lot from an Aftershock enabled one, a Magiclysm one, a No Hope one, or a Dark Days of the Dead one. Sometimes I want to switch from one game with a particular tone to another with a vastly different tone, but the game won't switch to the right tileset by itself so I'd have to manually navigate the GFX menu and do the switch myself, which personally ruins the experience for me.

# Describe the solution you'd like
In the world creation menu, there could be an option to choose your preferred tileset that would only apply to the world that you are currently making, so that when you switch between save files, it would automatically load that tileset for you, instead of using only one default tileset. The game should of course give you the option to default to whatever tileset that the game is using as the global default.

# Describe alternatives you've considered

# Additional context

**Comment by ZhilkinSerg** [comment]
Tileset is not a world option.

**Comment by Qrox** [comment]
It can be made one though. Also, I think the auto-save option is also worth being made a world option. I want my playthrough save to auto-save, but not my debugging save because I might need to revert to the original state and the last thing I want is accidentally saving.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
