### ISSUE TITLE
Earthships - passive constructions of upcycled and natural materials

### ISSUE THREAD

**Issue by Zireael07** [CleverRaven/Cataclysm-DDA#51427]
# Is your feature request related to a problem? Please describe.
Tires are only useful for vehicles. Similarly bottles and cans aren't very useful.

# Describe the solution you'd like
We already have tire armor, which is a recent addition, but I was just made aware of 'earthships'. These use tires and soil for exterior walls, and bottles or cans for interior walls.

# Describe alternatives you've considered
?? not adding I guess ??

# Additional context

[Wikipedia](https://en.wikipedia.org/wiki/Earthship)

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
