### ISSUE TITLE
Followers allow infinite social skill practice

### ISSUE THREAD

**Issue by pehamm** [CleverRaven/Cataclysm-DDA#51429]
### Describe the bug

If a follower is asked to teach, social skill is practiced BEFORE the persuasion check is performed. Unlike actual teaching by NPCs, this is immediately repeatable ad nauseam to quickly gain levels in social by just asking for training and immediately declining.

### Steps To Reproduce

1. Talk to a follower who has not taught you anything recently, and tell them you need them to do something ('d')
2. Ask them to teach you something ('a'), then decline the persuasion check ('b').
3. Repeat the  previous step a few times (you can quickly hammer 'a' and 'b') to observe how focus sinks and the character slowly gets social levels.

### Expected behavior

Social skill should be gained when persuasion checks are actually performed.

### Versions and configuration

- OS: MacOs
    - OS Version:  Name: Mac OS X; Version: 10.14.6; Build: 18G6020; 
- Game Version: 45996c5 [64-bit]
- Graphics Version: Curses
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by eltank** [comment]
Confirmed and will be fixed shortly.
