### ISSUE TITLE
Obsolete things that are not fully obsoleted.

### ISSUE THREAD

**Issue by Hirmuolio** [CleverRaven/Cataclysm-DDA#51430]
### Describe the bug

There are things that are obsoleted. But they are still used either in the base game or in a mod.

They need to be properly obsoleted so that they can be removed.

List of things:

Items:
* solar_panel_v3 (quantum solar panel). Used in some recipes and in aftershock.
* spidery_legs_big in some uncraft recipes
* rock_pot in some recipe

Terrain. Mostly in looks-like but some of these are in full use..
* t_machinery_heavy
* t_machinery_old
* t_machinery_electronic
* t_plut_generator
* t_console_broken
* t_machinery_light
* t_console

The obsolete terrain "triffid_grove", "triffid_roots", "triffid_finale", "mine_entrance" still have their JSON maps. (not familiar with how obsolete maps work).

### Steps To Reproduce

Use some program to search for these things in game data (notepad++ search in files).

### Expected behavior

Obsoleted things are not used anywhere.

### Versions and configuration

Latest master.

**Comment by Maleclypse** [comment]
Does the solar_panel_v3 (quantum solar panel) have an entry in Aftershock or just make use of vanilla having the obsoleted entry?

**Comment by Hirmuolio** [comment]
Aftershock has its own quantum solar panel. 

But I am not sure how well it works. Base game has migration from quantum solar panel to upgraded solar panel. And this passes to Aftershock.
So if the player somehow gets their hand on quantum solar panel, saves and reloads the game they will have just an upgraded solar panel left.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
