### ISSUE TITLE
It is possible to shoot enemies through reinforced glass

### ISSUE THREAD

**Issue by Alphyn-gunner** [CleverRaven/Cataclysm-DDA#51432]
### Describe the bug

Reinforced glass doesn't prevent characters from shooting ranged weapons through it. It doesn't stop bullets and doesn't break when shot through. I'm pretty sure it works for monsters too. I think I was shot at through some reinforced glass by a feral security guard.

### Steps To Reproduce

1. Have a gun and an enemy.
2. Spawn some reinforced glass between you. 
3. Try shooting the enemy.

### Expected behavior

You can't shoot the enemy.

### Screenshots

![2021-09-06 17_17_18-Cataclysm_ Dark Days Ahead - b67e505](https://user-images.githubusercontent.com/34932866/132231610-1233f938-459b-4ab1-a70a-fdcd475bc363.png)

### Versions and configuration

- OS: Windows
    - OS Version: Windows 7 64-bit
- Game Version: b67e505 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: 
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Graphical Overmap [Graphical_Overmap],
    No Fungal Monsters [No_Fungi]

### Additional context

I noticed it while exploring the recently added lab. I'm not 100% sure, It might be one of the old labs I haven't seen yet.

**Comment by Alphyn-gunner** [comment]
![2021-09-06 17_32_53-Cataclysm_ Dark Days Ahead - b67e505](https://user-images.githubusercontent.com/34932866/132232709-861a2690-45ee-4f8c-afdd-ed3277b33299.png)
You can't throw items through the glass, however.

**Comment by anothersimulacrum** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/issues/33374
