### ISSUE TITLE
Ultica - make player character sprite bigger

### ISSUE THREAD

**Issue by Igryn** [CleverRaven/Cataclysm-DDA#51436]
# Is your feature request related to a problem? Please describe.
While its already more than 1 whole squre in size, it still is hard to see your character clearly

# Describe the solution you'd like
Make character sprite atleast 1.5 squares tall if not more

# Describe alternatives you've considered
Make it wider or add an outline to make it stand out more

# Additional context
While i like the tileset a lot of stuff is hard to see due to being very small, items included 
Should probably make all humanoid enemies to match the height if approved

**Comment by Xaleth** [comment]
You can press "z" or "Z" to make the tiles smaller/bigger

**Comment by ZhilkinSerg** [comment]
You better create issue in tileset repo.

**Comment by actual-nh** [comment]
> You better create issue in tileset repo.

As in https://github.com/I-am-Erk/CDDA-Tilesets, yes.

**Comment by acepleiades** [comment]
![characters](https://user-images.githubusercontent.com/69649956/132547199-e5ae989c-8a09-4b01-b0d7-25da5c89f0f9.png)
What's so hard to see about it? Are you sure you're just not used to it?

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
