### ISSUE TITLE
Pocket Priority

### ISSUE THREAD

**Issue by Dzlan** [CleverRaven/Cataclysm-DDA#51445]
# Is your feature request related to a problem? Please describe.
Currently, managing where items go when picked up is almost void. (I may be missing something though)

# Describe the solution you'd like
A simple interface very similar to the clothing layers interface. However, in this interface we list all our pockets/clothes. We can press s to select an item and move it up and down the list. This will determine which pockets are filled first.
It's simple and quick enough for a player to organize before a looting run, for example.

# Describe alternatives you've considered
Leave as is.

# Additional context
(+) Clothing layers screen summaries it well.

**Comment by Terrorforge** [comment]
There actually is already a system for determining where items go. Select the container you want and press v to go to the pocket autopickup manager. This allows you to not only set a priority for each pocket, but also white- or blacklist specific items or entire categories of item.

However, I think your suggested interface is much cleaner and easier to use. If nothing else, it would make clear which of your items even have pockets, which isn't always obvious right now.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
