### ISSUE TITLE
Warning prompt when a container within a container will be dropped due to grown size

### ISSUE THREAD

**Issue by atealein** [CleverRaven/Cataclysm-DDA#51457]
# Is your feature request related to a problem? Please describe.
With current system of pockets and containers contained in other containers, it happens often that when something is placed in the nested container (where there is space for it) it makes the container grows too large in size to be nested in the outside one.. so it is dropped out of inventory. There is a small message in the log that something was dropped and if there is a lot happening it is easy to miss. It is especially inconvenient when it happens to tools that are containers when recharging them - for example refilling your tailor's kit with thread will drop it and you might not notice until a crucial moment later when you actually need to use it. 

# Describe the solution you'd like
I think a warning prompt similar to the one that appears when you try to wield an item but are already wielding one can help the warn the player with a better notice and let them choose what they wants to do. It will require a check to be done (maybe it already is?) and trigger the prompt before dropping the nested container. The promt can be something like

"You are trying to fit X into Y which would make it too large for its current location in Z. What would you like to do?"
A. Store in inventory (see note below)
B. Wield item
C. Drop item
D. Wear item (where applicable)

A. is still a valid option, since current behavior doesn't seem to check if the item that is dropped out of it's pocket, could have been fitted somewhere else in the inventory. I've had situations where an item would drop and then I would pick it up and it would be placed easily in a different pocket. (I guess this might be considered maybe a bug?)

# Describe alternatives you've considered
Additional to the general prompt, there can be an additional check if the new size container will fit anywhere else in the inventory? If it does - move it, and don't prompt the player.

**Comment by mqrause** [comment]
I believe it's currently not possible anymore to fill a nested container more than the parent container allows by normal means. The exception is activatable items that change size, as described in #55742 and (in the opposite direction, but works both ways) #58808. Activating items is a whole other can of worms and the problem is better described in those issues, so I think this one can be closed.
