### ISSUE TITLE
Churches.json map definitions are too wide

### ISSUE THREAD

**Issue by RandDenner** [CleverRaven/Cataclysm-DDA#51454]
### Describe the bug

In both the base game and the version in DinoMod, the map definition files are 25 wide instead of 24. This throws off the on-screen map a tiny bit and accounts for some weirdness I noticed when I did PR #51224, but didn't alert me to the problem.
Oops. Well, I'm fixing it now.

### Steps To Reproduce

Look at the json file.
Count the width. It's 25, not 24.

### Expected behavior

Correct map generation without overrun.

### Screenshots

![image](https://user-images.githubusercontent.com/73523034/132381986-6c6ef941-a5ad-4bea-bfd0-118a43d4dda3.png)

### Versions and configuration

Win10 tiles x64, all versions

### Additional context

PR #51431 may end up fixing it.

**Comment by anothersimulacrum** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/51431

**Comment by RandDenner** [comment]
Okay, good. Saves me the time.
But I notice the fix in #51431 is not (yet) correct, as the PR is removing the trailing and not leading extra column.
So I'll see what happens with the PR and fix it as necessary.
Also, DinoMod `churches.json` has the same issue, so that'll need to be updated either way.

**Comment by RandDenner** [comment]
Okay, this was fixed and merged.
Now it only needs to be rotated, but that's a separate PR.
