### ISSUE TITLE
Minor Radioactivity/Radioactivity trait is unnecessarily detrimental and forbids players from making bases

### ISSUE THREAD

**Issue by NancokPS2** [CleverRaven/Cataclysm-DDA#51463]
# Is your feature request related to a problem? Please describe.
This trait builds up radiation near the player and keeps stacking it in nearby tiles, this is as harmful as it sounds.
Radiation is a permanent thing, it cannot be cleaned nor mitigated since it just keeps stacking and becoming more intense over time until even a cleansuit can't do anything to protect the player from radiation.
In as little as 3 days, a base becomes too irradiated to live in with just Minor Radioactivity, with a clean suit you may be able to live for a week but that's about it. The point appears to be that you can combine it with Radiogenic, the issue is that the radiogenic buff is very minor (it only comes into play while resting over hours and it's not like there's a time limit on the game for you to rush rests) and ONLY removes damage, not the weakness caused by radiation. EVEN if you want to use radiogenic, the time required to build up radioactivity is just too long if you're just playing in a nomadic style.
What this means is that for having a base or spending more than 3 days in any place, the player has to suffer the trade off of loosing 2 in all stats and 9% of speed until they bot move out AND take pills to reduce radiation, without mentioning that the player will keep getting mutations akin to some other high impact mutations like Genetically Unstable (which can also be obtained with this).
It just feels illogically restrictive and punishing, specially when compared to other mutations.

# Describe the solution you'd like
There are various ways i think this could be adressed.
- Put a cap on radiation stacking from this mutations: Essentially make it so you can't just turn your base into mini-Chernobyil over time, so the rads that pile up on tiles cannot get so high that it becomes impossible to manage.
- Reduce the Weakness penalties: just like mutations akin to Strong Stomach reduce penalties from food poisoning, i think it stands to reason that this mutation should also reduce the penalty at least by half.
- Make it so a character with high coverage clothing cannot irradiate tiles: basically contain the radiation generated, i imagine that Minor Radioactivity would generate something akin to Alpha or Beta radiation so it wouldn't just penetrate all clothing. At the moment using a full cleansuit protects you from the radiation you leave on your wake, but does nothing to keep it from escaping your person.

# Describe alternatives you've considered
The solutions above could be moved to Radiogenic, altho it would make the time gape between getting this and Radiogenic extremely punishing, and cross your fingers that you don't get Radioactive before that.

# Additional context
Worth mentioning that this is a signature mutation from the Slime tree, which already has a fair amount of negative mutations like high food and water requirements as well as permanent pain form wearing clothes and other minor negatives.

**Comment by Zireael07** [comment]
The minor version definitely should have a cap imho.
High coverage, e.g. cleansuit, should definitely stop you emitting radiation in any case.

**Comment by NancokPS2** [comment]
I figured that capping radiation was kinda hard to code and would make Jsonifying mutations an even harder thing than it already is
This is why i mentioned the reduction of the weakness side effects, they could tweak weakness from radiation to not scale past a certain amount (as in, even if you have accumulated 9 trillion rads, the effects stopped increasing at 5000 rads) this means that no one has to mess with the radiation itself and only the weakness effect has to be fucked with
Also, no player without radiogenic/reduction to weakness effects would survive that long anyway so it isn't something most players would ever experience
It's just that there's nothing that can be done as long as radiation keeps stacking infinitely, even letting players survive with a cleansuit would seem fucky when they take it off and instantly die

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
