### ISSUE TITLE
Craftable smart purifier and smart mutagens

### ISSUE THREAD

**Issue by Entity-y** [CleverRaven/Cataclysm-DDA#51480]
# Is your feature request related to a problem? Please describe.
Science should be able to prevail through the complications that are negative mutations.

# Describe the solution you'd like
With a maxed out applied science skill and perhaps a rare recipe, players would have access to crafting their own smart purifier to select which mutation to remove. 

Conversely players could craft smart mutagens which allows for selecting mutations within a branch, and smart serums for some of the better mutations. 

These smart mutagens and recipes could be added to lab finales.

**Comment by Vendidurt** [comment]
I thoroughly, wholeheartedly, agree.

**Comment by Termineitor244** [comment]
The idea about smart mutagens is a good one, but about recipes... When the smart purifier was implemented in #45612, there were no plans to make it craftable, and I think if you make a recipe for it, it would trivialize mutations, but I don't know what is the current stance in the subject. Maybe a downgraded version would be acceptable? (One that purifies more random mutations but still allows for your one targeted to be removed).

**Comment by andrei8l** [comment]
Craftable smart purifier was removed from Aftershook [too](https://github.com/CleverRaven/Cataclysm-DDA/pull/46296#pullrequestreview-558847722) so it's highly unlikely it'll be added to CDDA, at least in its current form. Also, its "smartness" might come from super-advanced delivery compounds rather than the purifier itself, so it shouldn't be craftable by the survivor even if "science can prevail".

**Comment by actual-nh** [comment]
Mutagens with more tendencies to mutate particular parts of the body, for instance, are likely a possibility, including via recipes. Truly "smart" ones... I rather doubt it. Similarly, purifier that is more-targeted **to a part of the body** _might_ be a possibility, but I suspect a less likely one.

**Comment by Entity-y** [comment]
With the use of an electron microscope the player could study how the mutagen alters the DNA, then taking this found data and use it with something like [CRISPR](https://www.newscientist.com/definition/what-is-crispr/) would allow for precise restructuring of DNA. Pre-Cata scientists would have had the time and resources to test the smart mutagens out on subjects before settling on the perfect gene editing recipe.

**Comment by actual-nh** [comment]
> With the use of an electron microscope the player could study how the mutagen alters the DNA, then taking this found data and using it with something like [CRISPR](https://www.newscientist.com/definition/what-is-crispr/) would allow for precise restructuring of DNA. Pre-Cata scientists would have had the time and resources to test the smart mutagens out on subjects before settling on the perfect gene editing recipe.

Except that they failed, because it turned out to be rather more complicated than that. "mutagen" is perhaps a misnomer - it is by no means entirely (or even mostly) DNA alterations.

**Comment by Entity-y** [comment]
Unless mutagens are some kind of magical potion, realistically they would need to alter the DNA of the host to have any sort of bodily change.

**Comment by chrispikula** [comment]
> 
> 
> Unless mutagens are some kind of magical potion, realistically they would need to alter the DNA of the host to have any sort of bodily change.

Given that the 'mutations' don't come in gradually, but are very much binary, ie, you have them or not, the idea that any sort of purely cellular mechanism is what gives them to you is wrong.

It takes humans a dozen years to gain 4 feet in height, and a day or two after quaffing some mutagen I've got an extra couple feet of height and now have leaves growing out of my skin.

**Comment by Entity-y** [comment]
> Given that the 'mutations' don't come in gradually, but are very much binary, ie, you have them or not, the idea that any sort of purely cellular mechanism is what gives them to you is wrong.
> 
> It takes humans a dozen years to gain 4 feet in height, and a day or two after quaffing some mutagen I've got an extra couple feet of height and now have leaves growing out of my skin.

Then maybe mutations should be reworked to change the body over time instead of instantaneously.

**Comment by Termineitor244** [comment]
> 
> Then maybe mutations should be reworked to change the body over time instead of instantaneously.

That's the plan, Re: #28277

**Comment by Night-Pryanik** [comment]
Closing as stalled, since stalebot can't do this by itself.
