### ISSUE TITLE
Wearable cigarettes

### ISSUE THREAD

**Issue by Entity-y** [CleverRaven/Cataclysm-DDA#51481]
# Is your feature request related to a problem? Please describe.
As mentioned in #50936, wielded cigarettes and other smokes are transfered to the inventory once lit.

# Describe the solution you'd like

Prevent lit cigarettes from starting inside of the inventory.

Make cigarettes and other smokes wearable and occupy the mouth, adding mouth encumbrance and the ability to have animated smoking sprites with free hands.

Worn cigarettes and cigars could provide the fancy flag. 

Additionally, cigarette holders could be added which provides the very fancy flag when worn.

# Additional context
See https://github.com/I-am-Erk/CDDA-Tilesets/pull/907 for a mockup.

**Comment by PatrikLundell** [comment]
I definitely disagree that smokes makes you fancy: that's a rather 1950-ish marketing thing (along the lines of radium enriched products from even earlier). Today it just shows you're stupid (or giving in to peer pressure from a stupid peer environment).

Sure, in the cataclysm you might not care about catching lung cancer in 20 years, but smoke still stinks, which zombies can detect, lungs are still irritated which can result in coughs zombies can hear, and the lung capacity is still impaired, which might affect your ability to run away from those sniffing and listening zombies.

**Comment by Entity-y** [comment]
That's subjective, and it's interesting that you mention the 1950s because that was easily considered the fanciest era. Smoking complimented that dapper look and literally everyone smoke, the consensus back then was that smoking is a cool and attractive thing to do.

All I'm saying is that stylish characters should benefit from smoking.
