### ISSUE TITLE
Krav Maga doesn't work with Generic Guns

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#51484]
### Describe the bug

Using the Generic Guns mod, Krav Maga doesn't detect the generic version of a gun as an appropriate weapon for the martial art.

### Steps To Reproduce

Use Generic Guns, use Krav Maga, see it not detect it as appropriate.

### Expected behavior

I'd expect that if the branded version would work, so would the generic.

### Screenshots

![image](https://user-images.githubusercontent.com/6834262/132618295-22861ab0-cc18-42c8-afaa-c1579409953a.png)
![image](https://user-images.githubusercontent.com/6834262/132618329-c8f7d27d-f5a3-4ad1-8e85-de254c93d6c3.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    No Rail Stations [No_Rail_Stations],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    No Fungal Monsters [No_Fungi],
    Generic Guns [generic_guns]
]

**Comment by Termineitor244** [comment]
This should be an easy fix, and with #45612 merged this kind of things should happen less as soon as someone goes around adding the JSON flags for weapon categories (Is someone doing it already or is it still in the air?)

**Comment by Termineitor244** [comment]
I think this was resolved in #51785, I gave a read to some files of the mod and they use copy-from from several weapons used in Krav Maga, so they are automatically added too (Benefits of using weapon categories showing themselves!), I spawned a character with the mod and tried some weapons and they are indeed compatible with the martial art.

**Comment by Termineitor244** [comment]
@Maleclypse unless someone else seems to experience this problem, I think this issue can be closed as fixed.

**Comment by Night-Pryanik** [comment]
Closing as fixed.
