### ISSUE TITLE
Show/hide contents functionality in menus removes items from it that are not on the character

### ISSUE THREAD

**Issue by mqrause** [CleverRaven/Cataclysm-DDA#51490]
### Describe the bug

Using that functionality in menus that use items from the map or a vehicle instead of only from character removes all items not on the character from the menu.

### Steps To Reproduce

1. Make player, spawn some food and throw it on the ground.
2. Open the `E`at menu.
3. Try to show/hide contents.
4. The food on the ground disappears from the menu.

### Expected behavior

Show the same items as before.

### Versions and configuration

Introduced in #50491.
https://github.com/CleverRaven/Cataclysm-DDA/blob/d43b990e7cb4296368136bd1d39482943053cfb0/src/inventory_ui.cpp#L2164-L2173

**Comment by ZeroInternalReflection** [comment]
For the show/hide to work correctly, I get the impression it is in fact necessary to refresh the list of items.  So we need to know what the list of items _was_, and that's currently all handled outside of inventory_selector.  Would it make sense to encapsulate the process of adding items (e.g. only having the one public function add_items()) and have it accept a list of flags ("CHAR_INV", "VEH_INV", etc.) for what needs to be added.  Those flags could then be saved in inventory_selector, and when the time comes to refresh the list (this is not the only place where clear_items(), add_items() shows up), inventory_selector can just call that again with the current flags.

It's probably not as simple as I'm currently imagining, but it seems like it would be handy.

**Comment by RoyBerube** [comment]
Looking into it. The hide/show functionality makes no sense in the 'E'at menu - this is not intended behavior.

**Comment by mqrause** [comment]
This affects all `inventory_selector` menus. I first stumbled upon this in my pickup menu PR #51033 and just used `E`at as an easy to reproduce example.
