### ISSUE TITLE
Fibrous stalks don't stack correctly for butchering

### ISSUE THREAD

**Issue by atealein** [CleverRaven/Cataclysm-DDA#51509]
### Describe the bug

Fibrous stalks are alternative way to get plant fiber as 1 takes 30 minutes to disassemble into 80. However, currently there is something wrong with the stacking of this item and it triggers a different butchering menu, where you don't see the complete stack available for butchering at the location, neither do you get the option to start disassembling a number of them in a row. Instead the menu only shows only 1 fiber stalk available for disassembly, this always trigger a confirmation dialogue if you really want to disassemble this.. which means if you need to disassemble several in a row - a lot of unnecessary menu browsing and clicking.

### Steps To Reproduce

1. Get X fibrous stalks where X > 1
2. Put them in a pile on the ground and try to butcher them

### Expected behavior

I would expect to see a butchering menu that has the option to "butcher all" or "disassemble all once" and when triggered to proceed through the items disassembling them in order.

### Screenshots

![Screenshot from 2021-09-10 21-04-10](https://user-images.githubusercontent.com/25322782/132905437-b299e0a4-995c-489d-8bbf-ef0c4b5ceb92.png)
How the current menu appears, regardless of the stack of fibrous stalks being butchered below.

![Screenshot from 2021-09-10 21-28-53](https://user-images.githubusercontent.com/25322782/132907206-1fa46306-81eb-422c-8a79-c6a6fecc2344.png)
It asks for confirmation every single time.

### Versions and configuration

- OS RHE Linux 8.4 
- Game version 20bf2de
- Terminal (curses installation, no tiles)
- English language

**Comment by ferociousdork** [comment]
This seems to be due to comestibles having charges, and disassembly not taking this into account (comestible uncraft recipes are pretty rare). The same thing can be observed when trying to disassemble a stack of garlic bulbs.

The butchering dialog seems to be completely unaware of items with charges, disassembly itself has some custom code for ammo only, and Character::complete_disassemble can handle charges, but only in combination with the UNCRAFT_SINGLE_CHARGE flag (none of the comestible uncraft recipes have this at the moment).

**Comment by atealein** [comment]
Okay, I am trying to dig my way around the code to figure out how to fix this. 
1. Why is fiber stalk comestible? It's category is spare parts and it isn't edible in any way, there are no food-like recipes that use it directly, only way to use it currently is through disassembly to plant fibers
![Screenshot from 2021-10-10 14-16-39](https://user-images.githubusercontent.com/25322782/136695284-ceeb025c-f909-4550-b793-1c14cdf9eeb8.png)
2. You are correct that a bunch of other comestibles can use this as well - almost all the raw harvestable nuts and the garlic bulb for one have this issue. But the items that are able to be disassembled to their components aren't the comestible part itself, so maybe switching their type won't have dramatic consequences? Or would it? (it is a question, as far as I can see the raw nuts are not consumable, garlic bulb however has a rot timer, would that conflict with a change of its type somehow?) 
3. I am trying to dig through the code to figure out where the disassemble menu/options/functions start and where the butcher one does. The dialogue through the B-menu leads to this confirmation request, which mentions disassemble
![Screenshot from 2021-10-10 14-29-02](https://user-images.githubusercontent.com/25322782/136695721-736e65c6-9aa4-49f4-ad26-1054d61729c2.png)
Did you mean "UNCRAFT_BY_QUANTITY" in your message @ferociousdork and not "UNCRAFT_SINGLE_CHARGE" ? 
I think I traced the option you were talking about in crafting.cpp
![Screenshot from 2021-10-10 14-36-04](https://user-images.githubusercontent.com/25322782/136695970-5445133d-99d0-4921-adb8-301a73b615de.png)
 
I guess simply removing the ``` obj.is_ammo() ``` is going to be too simple to actually generalize the use of this function (and the comments suggest it should be expanded to more than ammo). 

I noticed that small_metal_sheet has type of "ammo" and ammo_type of "components" so I will tried to apply this for stick_fiber (fiber stalks's ID) since it isn't actually a comestible right now in any way ( it has -100 joy, -20 health, no other comestible modifiers). It worked to trigger the correct disassemble menu (or at least the one I was trying to trigger) but now they also have this "(active)" tag behind the item name, which I have no clue how or why it appeared there.

The question for the real comestibles still apply - would it break something if the type of some of them is "ammo"? What other way could there be to allow for the proper disassembly of non-ammo items that have charges?

**Comment by ferociousdork** [comment]
> Why is fiber stalk comestible? It's category is spare parts and it isn't edible in any way, there are no food-like recipes that use it directly, only way to use it currently is through disassembly to plant fibers

It doesn't appear to be very useful for fibrous stalks. I suppose its type could be changed, but in general it would cause problems.

> You are correct that a bunch of other comestibles can use this as well - almost all the raw harvestable nuts and the garlic bulb for one have this issue. But the items that are able to be disassembled to their components aren't the comestible part itself, so maybe switching their type won't have dramatic consequences? Or would it? (it is a question, as far as I can see the raw nuts are not consumable, garlic bulb however has a rot timer, would that conflict with a change of its type somehow?)

It would, only comestibles process rot. This is also the reason why they are active (if you change the category you see the "(active)" tag on existing items).

I think it would be best to proper handle items with charges. If you want to implement this, there are a few places that would need changes, to apply to not just ammo but to all items with charges:

https://github.com/CleverRaven/Cataclysm-DDA/blob/de98d1d2754abadd636efa164e2aaa7be486128b/src/crafting.cpp#L2192-L2194

https://github.com/CleverRaven/Cataclysm-DDA/blob/de98d1d2754abadd636efa164e2aaa7be486128b/src/crafting.cpp#L2295

https://github.com/CleverRaven/Cataclysm-DDA/blob/de98d1d2754abadd636efa164e2aaa7be486128b/src/crafting.cpp#L2489-L2495

And here check if the stack size including charges is > 1:
https://github.com/CleverRaven/Cataclysm-DDA/blob/de98d1d2754abadd636efa164e2aaa7be486128b/src/game.cpp#L8235

**Comment by atealein** [comment]
Thanks a lot! I am not good with the C++ part and what I tried on my own indeed resulted in the items getting the (active) tag :D and me not having any clue how to turn it off. 

I guess in the first two cases that you selected removing the check of .is_ammo() would make it more general but not sure what the change in the third one should be. I'll play around and I'll try to implement this and test it.

**Comment by ferociousdork** [comment]
For the third something like:
```
if( dis_item.count_by_charges() ) {
    if( dis.has_flag( flag_UNCRAFT_SINGLE_CHARGE ) ) {
        // Counted-by-charge items that can be disassembled individually
        // have their component count multiplied by the number of charges.
        compcount *= std::min(dis_item.charges, dis.create_result().charges);
    } else {
        compcount *= activity.position;
    }
}
```
