### ISSUE TITLE
Filtering in crafting menu changed logic and doesn't follow the description (between stable and experimental)

### ISSUE THREAD

**Issue by atealein** [CleverRaven/Cataclysm-DDA#51515]
### Describe the bug

This is a bug found in the experimental, screenshot below shows the difference with stable where it works properly.

In crafting menu the description lists the options for filtering by skills used in crafting as:
p: - for primary skill used for crafting
s: - as any skill used for crafting (here also the example is with s:cooking where cooking is no longer the skill name, now it is food handling)

However in experimental, s: no longer filters for any skill, it only filters by secondary skills used in the recipes. This is very clearly shown for trying to use the filter to find recipes using food handling skill - s:food - in stable this option would show all recipes having food handling as primary or secondary skill, while in experimental it lists the only recipes where it is used as secondary.

### Steps To Reproduce

1. Open crafting menu
2. Filter s:food

### Expected behavior

Either change the description of the filtering options or make it so s: works again for any skill used, not just secondary ones.

### Screenshots

![unknown](https://user-images.githubusercontent.com/25322782/132929181-1fd031cd-1dfc-4292-a228-410a558ab758.png)
this is how it looks in stable (screenshot by esotericist)
![Screenshot from 2021-09-11 01-57-26](https://user-images.githubusercontent.com/25322782/132929194-f6dd9bb0-f8dc-4f25-97cb-3b18fd876383.png)
this is how it looks in experimental

### Versions and configuration

OS RHE Linux 8.4
Game version 20bf2de
Terminal (curses installation, no tiles)
English language

**Comment by eltank** [comment]
Confirmed and will send a fix PR soon.
