### ISSUE TITLE
Multiunit liquid foods force you to dump instead of equip the container

### ISSUE THREAD

**Issue by Machminotaur** [CleverRaven/Cataclysm-DDA#51513]
### Describe the bug

Eating a food with multiple units from a backpack will force you to dump the remainder on the ground instead of give you some option to equip the can or set it down if you have no other available liquid containers.

### Steps To Reproduce

Spawn some meat soup into your backpack, without any other liquid containers.
Eat soup.
Watch as you're forced to spill the rest of the soup on the ground like a toddler because you don't have an empty plastic bottle.

### Expected behavior

You should be given an option to equip soup can in hand, as you... had to hold it to eat it. Or maybe you ate it out of the can on the ground like a dog bowl.

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0421556 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
