### ISSUE TITLE
Game crashes when walking next to laboratory card reader.

### ISSUE THREAD

**Issue by daetzu** [CleverRaven/Cataclysm-DDA#51525]
### Describe the bug

Game crashes when standing in any tile adjacent to a laboratory card reader.

### Steps To Reproduce

1.Make a character
2.Teleport to laboratory
3.Go to any tile adjacent to a card reader.

### Expected behavior

Game not crashing.

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: Xiaomi; Model: Redmi Note 8; Release: 11; Incremental: 9650; 
- Game Version: 4d92cc6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7148042/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7148043/debug.log)
[Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7148066/Save.zip)

I have a custom ROM installed, ArrowOS v.11 with Ryzen kernel, I've tried multiple ROMs and kernels just in case the issue was the phone but this isn't the case.
I've also tried multiple different worlds and versions to no avail, however this bug is not present in the latest stable version so it must've been introduced in one of the experimentals, I don't know which though.
I can't test this on the PC version because I currently don't have a PC.

**Comment by ferociousdork** [comment]
It crashes when examining the card reader. Seems to have been caused by #47948 which changes `can_examine` to use `examine_func` unconditionally:
https://github.com/CleverRaven/Cataclysm-DDA/blob/21435d22a0b237746c8ba120cc6d702faf4b05a7/src/mapdata.cpp#L498-L501

However, card readers use `examine_action` (#46734), and that branch doesn't initialize `examine_func`, hence the segfault:
https://github.com/CleverRaven/Cataclysm-DDA/blob/21435d22a0b237746c8ba120cc6d702faf4b05a7/src/mapdata.cpp#L1298-L1306

**Comment by actual-nh** [comment]
Ping: @MarlossCDDA, @anothersimulacrum?

**Comment by MarlossCDDA** [comment]
Hmm, I was worried my PR would break something with card readers but it worked fine when I tested it. Maybe a difference in how things get initialized on PC vs Android? I can send out an attempted fix but I don't know if I'll be able to repro the crash.

**Comment by anothersimulacrum** [comment]
Plobably it is invoking UB, so if you can compile with a sanitizer you can get it anywhere
