### ISSUE TITLE
Corn Cobs and eating

### ISSUE THREAD

**Issue by morthein** [CleverRaven/Cataclysm-DDA#51533]
### Describe the bug

When you have a stack of corn cobs and eat one, it eats the whole stack.

### Steps To Reproduce

1. make a stack (or harvest) some corn to receive corn cobs
2. attempt to eat once, while holding them all
3. notice you devour the entire pile and only get the calories from one (or so it seems)

### Expected behavior

Normal eating, one at a time.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 4d92cc6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Alternative Map Key [alt_map_key],
    Crazy Cataclysm [crazy_cataclysm],
    Dorf Life [Dorf_Life],
    No Rail Stations [No_Rail_Stations],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Crazy Cataclysm - UndeadPeople Tileset [CrazyCataclysmUDP],
    Dorf Life - UndeadPeople Tileset [Dorf_LifeUDP],
    Graphical Overmap [Graphical_Overmap],
    No Fungal Monsters [No_Fungi],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    Manual Bionic Installation [manualbionicinstall],
    Safe Portable Autodoc [safe_portable_autodoc],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by estebandellasilva** [comment]
dublicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/50002
