### ISSUE TITLE
Getting infected aways told as "Deep Bite"

### ISSUE THREAD

**Issue by Xindage** [CleverRaven/Cataclysm-DDA#51560]
### Describe the bug

If you get damaged while wearing filthy clothes it's registered in console that you was bite deeply even if the source of the damage is not a zombie or any enemy. "The bite wound feels really deep."

### Steps To Reproduce

1. Wear filthy clothing.
2. Walk into the exposed conduit.
3. Get bite wound on the body. (without being bitten)

### Expected behavior

Getting a nasty wound (early infection maybe?) without it being told as bite because the damage source was not a bite to start with it.

### Screenshots

![image](https://user-images.githubusercontent.com/6380147/133002388-65733ef6-556d-41a3-a306-fcfa5371958d.png)
![image](https://user-images.githubusercontent.com/6380147/133002404-9cc7a8d1-d7b9-4640-a3cb-79fa5ca036bf.png)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.2 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock]
]

### Additional context

This is noting so important so can be safely ignored if you guys want.

**Comment by Venera3** [comment]
Turning the `apply_message` of the effect into something a bit more generic is a one-line change, so this can get "Good First Issue" as well.

**Comment by anothersimulacrum** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/920a0886a3c907b43add51cb74fe0c11d52dd9e9/data/json/effects.json#L968-L971

**Comment by radekrudak** [comment]
So can i have this i as my first issue ?

**Comment by Night-Pryanik** [comment]
@radekrudak yes, of course, you are welcome.

**Comment by Night-Pryanik** [comment]
No one is rushing you. Take any time you need.

**Comment by radekrudak** [comment]
Ok is three place i can ask questions like "Where can i conduit to get hurt and test if i fixed this bug" ?

**Comment by Venera3** [comment]
For short questions like that the dev Discord is usually the easiest. For this, you can activate the debug menu (you need to assign a key to it first) -> Player -> Edit Player/NPC -> Select your char -> Add Effect -> infected, non-1 duration should show your changed message.

**Comment by radekrudak** [comment]
@Venera3  Ok is there place for more complicated problems like now i have problems with even compiling it and reasons seem vary depending on with variables i set.

**Comment by kevingranade** [comment]
Fixed by #52145
