### ISSUE TITLE
Error on profession selection (Tourist?)

### ISSUE THREAD

**Issue by StStep** [CleverRaven/Cataclysm-DDA#51565]
### Describe the bug

Error on profession selection, after scrolling down to tourist:

```
 DEBUG    : requested mission with uid 2 does not exist

 FUNCTION : static mission* mission::find(int)
 FILE     : src/mission.cpp
 LINE     : 88
 VERSION  : 5cb6295
```

### Steps To Reproduce

1. Go to create a new character
2. On the profession page and scroll down to tourist (it also works if you just scroll up instead)

### Expected behavior

No error

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 5cb6295 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by ProfoundDarkness** [comment]
I could NOT reproduce this on linux (debug) nor windows (release), cdda version 0.F-2601-g77f8f60808.

Is this something you can replicate consistently?  I *may* be on a newer version meaning it *could* be fixed already, can you replicate this after upgrading?  ...once a new version is available.

I don't know enough about the missions/character selection to try and dig further from the given error message.

**Comment by StStep** [comment]
I updated to latest version and couldn't reproduce, while I did repeatability on my previous version. I'm going to throw this out as a fluke.
