### ISSUE TITLE
Error on Practicing Computers on Vehicle Table

### ISSUE THREAD

**Issue by StStep** [CleverRaven/Cataclysm-DDA#51567]
### Describe the bug

If you perform a computer practice recipe while next to a vehicle table, it will throw the following error. This doesn't happen next to standard tables or when not near any tables.
```
 DEBUG    : Item 'in progress computer (beginner) (0%)' with zero volume

 FUNCTION : int item::charges_per_volume(const volume&) const
 FILE     : src/item.cpp
 LINE     : 959
 VERSION  : 5cb6295
```

### Steps To Reproduce

1. Make new character will computer skill 0
2. Spawn Computer World, a laptop, a medium battery and a luxury RF
3. Reload the laptop and attempt to practice the recipe next to the table in it

### Expected behavior

No error.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 5cb6295 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by ProfoundDarkness** [comment]
Cataclysm version 0.F-2601-g77f8f60808 (debug for more info) on linux x64 (Ubuntu 20.04) replications steps DID result in error.  Log attached.
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7156575/debug.log)

I don't know if it matters but it also happened in release.
