### ISSUE TITLE
Overmap Issues (default, zoom, not updating)

### ISSUE THREAD

**Issue by StStep** [CleverRaven/Cataclysm-DDA#51564]
### Describe the bug

Three big things, maybe related:
* Can no longer zoom on overmap. I verified keys are bound and am using a tileset (Ultica)
* Overmap tile set doesn't automatically update after changing like the normal tileset does
    * You can force the overmap tileset to be loaded by changing the standard tileset
* The default overmap tileset is RetroDays. While I like retrodays, I think it should be Ultica?  

### Steps To Reproduce

1. Make a new character, view overmap (See default?)
2. Switch overmap tileset, see how it doesnt' change
3. Try to zoom in and out on overmap tileset with one that should zoom (ultica)

### Expected behavior

Should be able to zoom and tileset should update after selecting and saving options.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 5cb6295 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by actual-nh** [comment]
Ping: @KorGgenT?

**Comment by YourCompanionCube** [comment]
can confirm, came to report the same thing

**Comment by chance-m** [comment]
Can confirm as well. Have not updated to the most recent version just yet.
