### ISSUE TITLE
Spoiler Secret Entrance is clearly visible on Overmap

### ISSUE THREAD

**Issue by StStep** [CleverRaven/Cataclysm-DDA#51568]
### Describe the bug

The secret lab entrance that is just a manhole in the forest is clearly visible on the overmap of several tilesets due to how they display it as it's ASCII symbol (Green F). In ASCII mode (and other tilesets with trees as Green F's such as NeoDays) its not obvious that the tile is special, but on others you see a Forest listed as F in the middle of otherwise rendered tiles. While it's not obviously a secret lab entrance, it will lead players there unintentionally.

### Steps To Reproduce

1. Make a new character and reveal overmap and look for F (might need to move over a block or two before you get one with it)

### Expected behavior

That it shouldn't be so obvious from the overmap that the forest is "special"

### Screenshots

MSXotto+
![Secret Entrance (MSXotto+)](https://user-images.githubusercontent.com/2823857/133006743-f8f60aa6-ccca-412e-a715-fcb3901e835d.PNG)
RetroDays
![Secret Entrance RetroDays](https://user-images.githubusercontent.com/2823857/133006744-64273cfb-dc9f-46f5-9c17-8bdf85489a34.PNG)
Ultica
![Secret Entrance](https://user-images.githubusercontent.com/2823857/133006745-a60eadaf-e296-4f5f-b59b-760026303e08.PNG)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 5cb6295 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by actual-nh** [comment]
@Fris0uman: Would you like to add something to fix this to your current PR #51550?

**Comment by Venera3** [comment]
A *touch* less obvious, but it also doesn't have the appropriate land use code so it's easy to scan forests in that mode and find it.

**Comment by Qrox** [comment]
So, if I make a base camp nearby and order my companion to chop down trees on a "fake" forest tile, will the tile be revealed as fake or will it be turned into ground tile and make the entrance disappear, assuming that the submap was not generated before?

**Comment by ProfoundDarkness** [comment]
I don't use graphical overmap (prefer consistency with sidebar) so I know almost nothing about it.  I read an issue or PR that implied overmap tiles have a looks-like tag in json... couldn't this get that tag set to forest?  Assuming they always spawn in forest anyway...
