### ISSUE TITLE
Is possible to we have new custon panels and an option for the log list.

### ISSUE THREAD

**Issue by Xindage** [CleverRaven/Cataclysm-DDA#51563]
# Is your feature request related to a problem? Please describe.
I'm a user who like of the having a good amount of lines on the log but this said panel is who suffer from being most eaten by the map panel, so i wanted if it's possible to we have these changes to the status bar.

# Describe the solution you'd like
First an compact Compass: Its alternative version of Compass (come disabled by default in all status bars), instead of using a lot of lines it just use the first 3 lines and doesn't show the monsters list, any veteran player already know what each Z color means, this allow we having the core feature of the compass while making it eat less of the Status Bar.
Bigger Log: About having a big log list i wanted if we can have a option that set a minimum amount of lines for the log in the Status bar, Since map can be resized by the panels present it can be resized to fit a bigger log list for who want more than just 2 lines of log.
this feature should be in the option>interface> and appear just after the entry 33 Minimum log entries Default 1, min: 1 max: (i don't really know, it may depends in each player resolutions)

# Describe alternatives you've considered
Having an alternative log that can accommodate more lines by default.

# Additional context
![image](https://user-images.githubusercontent.com/6380147/133005117-0d59b817-63cf-4202-86cc-472210a43876.png)

**Comment by actual-nh** [comment]
Ping: @wapcaplet - your thoughts?

**Comment by wapcaplet** [comment]
It would be fairly easy to add a "Compact Compass" that you could toggle in the sidebar. I don't think there is any need for adding another setting to Options / Interface, it can simply be a sidebar panel you can toggle on and off.

Meanwhile, if you want to have greater control over your own sidebar's use of space, you might try using the relatively new "Custom" sidebar panel, and modding your own layout with JSON. See #44683 for where the feature was introduced, and read [doc/SIDEBAR_MOD.md](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/SIDEBAR_MOD.md) for docs on how to use it. The builtin sidebar layouts are often filled with wasted space that you have no control over; this new Custom layout lets you arrange (almost) everything the way you want.
