### ISSUE TITLE
warnings on load with no hope

### ISSUE THREAD

**Issue by dissociativity** [CleverRaven/Cataclysm-DDA#51579]
### Describe the bug

`13:34:39.935 ERROR : src/item_group.cpp:269 [virtual void Single_item_creator::check_consistency() const] item group id tripod is unknown (in item_group id tripod)
13:35:15.811 ERROR : src/item_group.cpp:239 [virtual Item_spawn_data::ItemList Single_item_creator::create(const time_point&, Item_spawn_data::RecursionList&, spawn_flags) const] unknown item spawn list tripod
13:35:16.672 ERROR : src/mapgen.cpp:1025 [void mapgen_value<Id>::id_source::check(const string&, const mapgen_parameters&) const [with Id = string_id<itype>; std::__cxx11::string = std::__cxx11::basic_string<char>]] mapgen 'mapgen house_21' uses invalid entry 'toolbox' in weighted list
13:35:17.067 ERROR : src/mapgen.cpp:1025 [void mapgen_value<Id>::id_source::check(const string&, const mapgen_parameters&) const [with Id = string_id<itype>; std::__cxx11::string = std::__cxx11::basic_string<char>]] mapgen 'mapgen p_resort_0nw' uses invalid entry 'toolbox' in weighted list
13:35:17.067 ERROR : src/mapgen.cpp:1025 [void mapgen_value<Id>::id_source::check(const string&, const mapgen_parameters&) const [with Id = string_id<itype>; std::__cxx11::string = std::__cxx11::basic_string<char>]] mapgen 'mapgen p_resort_0nw' uses invalid entry 'toolbox' in weighted list
13:35:17.905 ERROR : src/monstergenerator.cpp:1240 [void MonsterGenerator::check_monster_definitions() const] monster mon_laserturret has unknown revert_to_itype: bot_laserturret
13:35:17.925 ERROR : src/monstergenerator.cpp:1240 [void MonsterGenerator::check_monster_definitions() const] monster mon_tripod has unknown revert_to_itype: bot_tripod
13:35:17.925 ERROR : src/monstergenerator.cpp:1240 [void MonsterGenerator::check_monster_definitions() const] monster mon_tankbot has unknown revert_to_itype: bot_tankbot
13:35:17.925 ERROR : src/monstergenerator.cpp:1240 [void MonsterGenerator::check_monster_definitions() const] monster mon_chickenbot has unknown revert_to_itype: bot_chickenbot`

### Steps To Reproduce

load game with world with no hope mod, game loads fine if ignored

### Expected behavior

don't have these warnings

### Versions and configuration

latest build as of 2:20PM GMT10+ 13/09/2021 Windows 32 bit tiles.

**Comment by Night-Pryanik** [comment]
Caused by #51309.
