### ISSUE TITLE
Can't siphon fuel from a vehicle with a "hole" inside

### ISSUE THREAD

**Issue by utechenko-v** [CleverRaven/Cataclysm-DDA#51582]
### Describe the bug

I got error - error in activity data: "could not find source vehicle for liquid transfer" on attempt to siphon fuel from a specific vehichle - APC with JP8 fuel. Character can successfully siphon fuel from other cars.
APC is partially deconstructed, maybe it matters. I'll attach a savegame archive.

### Steps To Reproduce
:warning: **note : see updated STR in comments below** (Sep-25)

1. Load attached savegame
2. Check that character has a rubber hose and a plastic bottle to siphon JP8 fuel
3. Interact with APC vehicle and try to siphone JP8 fuel (from any tank ,10L or 200L)

Actual result:
debug message with error displayed. No fuel siphoned.
```
DEBUG    : error in activity data: "could not find source vehicle for liquid transfer"

 FUNCTION : void activity_handlers::fill_liquid_do_turn(player_activity*, Character*)
 FILE     : src/activity_handlers.cpp
 LINE     : 1573
 VERSION  : abff338
```

### Expected behavior

Character with a rubber hose and a plastic bottle should be able to siphon JP8 fuel from that particular APC.

### Versions and configuration

- OS: Windows 10
- build type: windows-tiles-x64
- build number: 2021-09-07-1822 (experimental)
- commit sha: abff33888297d49c333d5fd33427f6797aa00139

### Additional context

attached fiels: savegame and debug.log
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7152540/debug.log)
[save-cannot_siphone_fuel_from_APC.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7152542/save-cannot_siphone_fuel_from_APC.zip)

**Comment by ProfoundDarkness** [comment]
With the provided save I DID get the error message.  I've included that log.  There are some other errors from loading an older save on current version - at least that's when I've encountered them in my regular gameplay.
I attempted to siphon from two different locations (physically and in vehicle tank selection) so there are two copies of the error near the end of the log.
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7156934/debug.log)

HOWEVER
While waiting for the save to download/decompress I created a new character and spawned in an APC (apc) and WAS able to siphon from that just fine.  That is no error, so this really does seem somewhat specific.  In fact spawning a vehicle in on the given save also allows siphoning, just the vehicle the character is standing next to on save load that is broken.

**Comment by utechenko-v** [comment]
I have an older save of the same game, in an older game version. 
(build number: 2021-09-01-0513, commit sha: c11072c6ea85ec83fa08fa2a69b694745548436c)
In that save no spare parts were removed from that particular APC yet, and a character can siphon a fuel without any problems. So probably APC was "corrupted" by removing parts - I've removed a lot of parts from it (or there is a small probability that APC was "corrupted" by moving save from one game version to another, or some other action).
I can try to start from an older save and repeat the disssemble actions on the APC, if it makes any sense (though I don't remember exact order of parts removal).

**Comment by utechenko-v** [comment]
I've tried similar disassemble actions for APC from older save, and for regular car, and now I have updated STR:
1. Find car or APC with non-empty tank 
2. Get tools for parts removal: hacksaw, wrench etc.
3. remove all car parts in 2x2 square to make a "hole" inside the car (e.g. trunk and back seats), leave outer cells intact (doors, quarterpanels, trunk door) - see image:
![зображення](https://user-images.githubusercontent.com/16246933/134771521-b12c4144-c060-4ae1-83e5-e6fec2272747.png)
4. Stand inside car's inner "hole" 
5. Try to siphon fuel with rubber hose into some container
Result: DEBUG    : error in activity data: "could not find source vehicle for liquid transfer"

**Comment by kapacek** [comment]
Confirmed on 0.F-2. I drove the car like a prick and it is now severely damaged, but it is still going. Just some parts missing.

**Comment by hexagonrecursion** [comment]
I could not reproduce this issue by following the second version of the steps to reproduce in a fresh save.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: eacb7d9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by pjf** [comment]
I can reproduce in my current run with a game generated wreck. Siphoning from other vehicles (including wrecks) has been fine.

**To reproduce**

Load the attached save, try to siphon from the RV wreck the survivor is standing next to.

**Attached save:**

- [CannotSiphon.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7858665/CannotSiphon.zip)

**Backtrace:**

```
10:39:30.325 ERROR : (error message will follow backtrace)
    ./cataclysm-tiles(debug_write_backtrace(std::ostream&)+0x24) [0x11a7ade]
    ./cataclysm-tiles(DebugLog(DebugLevel, DebugClass)+0x294) [0x11a6fff]
    ./cataclysm-tiles(realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0xa0) [0x11a68bd]
    ./cataclysm-tiles(void realDebugmsg<char const*>(char const*, char const*, char const*, char const*, char const*&&)+0x5f) [0xeebf2b]
    ./cataclysm-tiles(activity_handlers::fill_liquid_do_turn(player_activity*, Character*)+0xfc0) [0xed2b70]
    ./cataclysm-tiles(activity_type::call_do_turn(player_activity*, Character*) const+0x67) [0xf15e1f]
    ./cataclysm-tiles(player_activity::do_turn(Character&)+0x334) [0x1ad74ce]
    ./cataclysm-tiles(do_turn()+0x81b) [0x121e9b7]
    ./cataclysm-tiles(main+0xeca) [0x1654f62]
    /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f12a86d70b3]
    ./cataclysm-tiles(_start+0x2e) [0xe6803e]

    Attempting to repeat stack trace using debug symbols…
    debug_write_backtrace(std::ostream&)
    ??:?
    DebugLog(DebugLevel, DebugClass)
    ??:?
    realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    ??:?
    void realDebugmsg<char const*>(char const*, char const*, char const*, char const*, char const*&&)
    ??:?
    activity_handlers::fill_liquid_do_turn(player_activity*, Character*)
    ??:?
    activity_type::call_do_turn(player_activity*, Character*) const
    ??:?
    player_activity::do_turn(Character&)
    ??:?
    do_turn()
    ??:?
    main
    ??:?
    __libc_start_main
    /build/glibc-YYA7BZ/glibc-2.31/csu/../csu/libc-start.c:342
    _start
    ??:?
Backtrace emission took 1 seconds.
(continued from above) ERROR : src/activity_handlers.cpp:1541 [void activity_handlers::fill_liquid_do_turn(player_activity *, Character *)] error in activity data: "could not find source vehicle for liquid transfer"
```

**Version info:**

Version: 600018f31109fe9adce80a6f388bee0cb6d1ae62 (`cdda-experimental-2022-01-12-2215`) with minor local JSON patches applied that do not involve vehicles.

```
- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-5219-g2028c4cd45 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Alternative Map Key [alt_map_key],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    No Hope [no_hope],
    Bionic Slots [cbm_slots]
]
```
