### ISSUE TITLE
Martial Arts buffs no longer stack

### ISSUE THREAD

**Issue by Hymore246** [CleverRaven/Cataclysm-DDA#51591]
### Describe the bug

Martial Arts buffs can be applied to the player but can never grown beyond a stack of "1". I am pretty sure this is being caused by #51374 which probably undid part of #31733 by accident.

### Steps To Reproduce

1. Use the debug menu to give yourself Toad Kung Fu.
2. Move around a lot.
3. Open the Status menu and notice how Iron Skin Dissipation always remains at 1 stack regardless of how much movement was done.

### Expected behavior

Buffs should stack up to their given maximum when they are applied to the player while already under their effects.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 9154058 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Mythical Martial Arts [MMA]
]

**Comment by actual-nh** [comment]
Ping: @Venera3?

**Comment by Venera3** [comment]
On a fresh master I have intensity 6 `buff_toad_onmove` (debug intensity readouts moved to the @ menu, fwiw).

**Comment by Hymore246** [comment]
#51592 has merged but I still can't get any MA buffs to stack. Falling Leaf remains at one stack after multiple attacks and Iron Skin Dissipation stays at one stack regardless of movement.

**Comment by Venera3** [comment]
Just to confirm, you're checking the intensities in debug mode? The values aren't visible by default in the @ menu for some reason, but I haven't changed `show_intensity` in any way..

**Comment by Hymore246** [comment]
I was not using the debug mode. The values should be visible on the @ menu. If they are not showing up for another reason then that is a big issue since players shouldn't have to use the debug menu to know if a buff is stacking.

**Comment by Venera3** [comment]
They also didn't show up in 0.F, so it might be that the default for showing intensity changed somewhere along the line. I'll be able to look into ot in a few hours.

**Comment by Venera3** [comment]
#42461 changed the effect header to use `show_intensity` and set the default to false, then added true as the true default on JSON load. Since MA buffs use a weird mishmash of effect code they inherit the original false definition, and can't accept `show_intensity` as a field since they aren't proper effects. Shouldn't be too hard to fix, all things considered.
