### ISSUE TITLE
oats, oatmeal and cooked oatmeal calorie bug means haggis disobeys thermodynamic laws

### ISSUE THREAD

**Issue by PLUUZ** [CleverRaven/Cataclysm-DDA#51606]
### Describe the bug

Someone please double check this, but it I tried making a haggis from 16 oatmeals, 4 piece of kidney, and a stomach.  The result was a single bomb of food with 3072 calories that i have to consume all at once - one portion. I think this is because the recipe for oats and oatmeal_cooked are a bit out of whack (10 cal of oatmeal turns into 175 cal of oatmeal_cooked) , and oats used in recipes cooks_like oatmeal_cooked.

### Steps To Reproduce

Take the above ingredients and produce a haggis.

### Expected behavior

I expected the haggis to be less calories becuase of the ingredients, according to JSONs in the github these are the caloric values of the  ingredients:

stomach - 60cal x 1 = 60
kidney - 54 cal x 4 = 216
oatmeal 10 cal x 16 = 160
expected total = 436

### Versions and configuration

osx 10.11.6
version F-1
curses

### Additional context

Looking at the jsons on the github, i think the problem is the cooked oatmeal, and some other strange things about oats.

Oats  x 1  = 323 cals

the oatmeal recipe uses 2x oats (646 cals) to produce 16 charges of oatmeal at 10 cals each.
16 x 10 = 160 calories.  Ok so we lost like a 500  calories just crushing the oat grains. I doubt that is accurate.

But anyway besides that, then to produce cooked oatmeal from oats, **we need only 1 charge of oatmeal, which is just 10 calories, but it produces a portion of cooked oatmeal that's 175 calories.**  I know cooking releases nutrients and all that, but not by a  factor of 17.5! 

re: the haggis i notice that oatmeal has a cooks_like tag of oatmeal_cooked, it is benefitting from this oatmeal bug.  

now we're getting 
stomach - 60cal x 1 = 60
kidney - 54 cal x 4 = 216
oatmeal > oatmeal_cooked - 175 cal x 16 = 2800
 
=   3076 cals, which is what the haggis is!

**Comment by Kribylet** [comment]
I did produce a sweet piece of scottish jet fuel using raw livers the other day on 0F-1:

![image](https://user-images.githubusercontent.com/8685696/133313973-0eb99482-e6ee-4658-8240-b3815dc1bb38.png)

Bot I didnae really question eet
