### ISSUE TITLE
Can not disassemble broken tank drone

### ISSUE THREAD

**Issue by stasalcatraz** [CleverRaven/Cataclysm-DDA#51644]
### Describe the bug

When i'm trying to disassemble subject, i've got the message "The broken tank drone is too large and/or heavy to work on.  You may want to use a workbench or a smaller batch size". Even if it's on the workbench.

### Steps To Reproduce

1. Find a broken tank drone.
2. Take it on a workbench.
3. Try to disassemble.

### Expected behavior

I expect to finish disassembling process

### Versions and configuration

- OS: Ubuntu 20.04
- Game Version: Cataclysm-DDA experimental build 2021-09-15-0541
- Graphics version: Tiles
- Ingame language: Russian
- Mods loaded: 
  "dda",
  "no_npc_food",
  "package_bionic_professions",
  "blazeindustries",
  "magiclysm",
  "crt_expansion",
  "crazy_cataclysm",
  "MMA",
  "No_Rail_Stations",
  "fuji_mpp",
  "speedydex",
  "StatsThroughSkills",
  "aftershock",
  "extra_mut_scens"

**Comment by wapcaplet** [comment]
Confirmed. The broken tank drone weighs over 1200 kg, but I can work around #53671 by designating a zone for "Disassembly Work" and putting the tank drone there.

![image](https://user-images.githubusercontent.com/238395/147097892-fd945169-e199-4213-8fa8-9e711d78cfb3.png)

When I begin disassembly using z`O`ne activities, `D`isassemble items, I get the "You may want to use a workbench" messaging:

![image](https://user-images.githubusercontent.com/238395/147097656-08c639d8-6887-4f5f-be9f-59f2ab150f1d.png)

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-4532-g630da649b6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Aftershock: Exoplanet [aftershock_exoplanet]
]

**Comment by Sukul22** [comment]
I am also having issues, i have found several posts saying to butcher it, but it says you cannot dissasemble anything here. The broken tank drone item does not list any method or tool requirements to dissasemble, nor any possible drops for doing so. I found the item in a supersoldier bunker. It is currently a one ton paperweight. I seem to remember a post suggesting it be moved solely to aftershock, which I am not running. Could this also be a reason? It might be appearing because of Cata++

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Cataclysm++ [Cata++],
    Crazy Cataclysm [crazy_cataclysm],
    Mining Mod [Mining_Mod],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Mythical Martial Arts [MMA],
    Caches [P_Caches],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

**Comment by Night-Pryanik** [comment]
The message now is `The <item to disassemble> is too large and/or heavy to work on.  You may want to use a workbench or a lifting tool.` This should hint the player that he needs a lifting tool powerful enough to lift weight of an item. Having `rope and tackle hoist` in the vicinity, for example, allowed me to successfully disassemble the broken tank drone.

The only thing that could be done here is an update to message, like `You may want to use a workbench or a lifting tool powerful enough to lift the weight of <item to disassemble>`.
