### ISSUE TITLE
[RetroDays] Harvested alder trees do not change their sprite

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#51642]
### Describe the bug

If you harvest the bark off e.g a blackjack oak, the tree sprite will change appropriately. The same is not true for the RetroDays tileset when you harvest an alder tree. It displays properly in UltiCa.

### Steps To Reproduce

1. Find an alder tree
2. Harvest it
3. Observe there is no change
4. Find a blackjack oak
5. Harvest it
6. Observe there is a change
7. Optionally compare RetroDays with UltiCa for this purpose

### Expected behavior

The alder tree should look like it is dead to show it has been harvested, just like e.g the blackjack oak.

### Screenshots

UltiCa (displays it properly):
![image](https://user-images.githubusercontent.com/59517351/133441242-efccff89-fb63-4590-9d7d-07df8cc61a11.png)

RetroDays:
![image](https://user-images.githubusercontent.com/59517351/133441443-42f3f37f-8152-464b-8677-86aaf9a007dd.png)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.F [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

Built from 920a088

**Comment by actual-nh** [comment]
I suggest submitting an issue (as in, a request for someone to draw a harvested version) to the tileset repo (<https://github.com/I-am-Erk/CDDA-Tilesets/issues>).

**Comment by NetSysFire** [comment]
It has the very same shape as a blackjack oak or hickory tree (both of them and the maple and hazelnut trees share the sprite). It would perfectly suffice to just copy the harvested blackjack oak/hickory tree/etc sprite to the alder one. I personally do not see the need to have a unique sprite for that in this scenario since the retrodays tileset is designed to be simple anyways.

I am not familiar with editing a tileset, would creating an issue in the mentioned repo still make sense in this case?

**Comment by actual-nh** [comment]
Just adding "looks_like": "ID_OF_HARVESTED_ONE_WITH_SPRITE" (substituting appropriately) to the JSON of the harvested version should work, then.

**Comment by NetSysFire** [comment]
Closing this one because I moved it to the tileset repo where it is more appropriate.
