### ISSUE TITLE
Zombies doesn't attack giant lady bugs

### ISSUE THREAD

**Issue by Titinator** [CleverRaven/Cataclysm-DDA#51653]
### Describe the bug

Zombies doesn't attack giant lady bugs, the lady bugs however do attack the zombies.

The problem seems to only affect these two, as zombies can fight Giant ants and mi-gos can fight with the lady bugs.

### Steps To Reproduce

1. Spawn a giant lady bug
2. Spawn any zombie
3. The zombie will wander or attack the player while the lady bug attack it.

### Expected behavior

I would expect the zombies and the lady bug to fight because the zombies fight all the other giant bugs.

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: HUAWEI; Model: HUAWEI VNS-L23; Release: 7.0; Incremental: C605B362; 
- Game Version: cdc6843 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    No Fungal Growth [no_fungal_growth],
    Stats Through Kills [stats_through_kills]
]

**Comment by actual-nh** [comment]
Sigh... thank you, working on.
