### ISSUE TITLE
Aluminium and tin cans should have the boiling quality again

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#51660]
### Describe the bug

In 0.F, aluminium and tin cans lost the boiling quality. This should be restored. The only reason we (it was discussed in the IRC channel and the forums) can imagine why you could not use it as an improvised pot is that it does not have any handles and can not be removed from the heat source safely without gloves or a tool.
But glass jars do have the same problem and still have the boiling quality.

### Steps To Reproduce

1. Start or just be somewhere far away from the city
2. Try to get water somewhere
3. You need to boil the water unless you want to throw up every 5 minutes
4. If you have to survive on foraging and natural resources for a while, the only thing you can use to boil is a clay pot, for which you need to level fabrication and survival.
5. This takes long and even if you find a can along a trail or in the bushes, you can not use it to fight off dehydration
6. Especially gathering clay will drain your clean water reserves, if there are any

### Expected behavior

Tin cans should be able to be used for boiling again. I am not too sure about aluminium cans, but it appears they are both suitable. Even in real life.
See https://backpackinglight.com/forums/topic/55915/

Alternatively, a recipe for a can pot may be added, as seen above. The boiling quality should be removed from the glass jar, too. A 3L glass jar may be big enough already, so it may be exempt.

### Versions and configuration

0.F

### Additional context

Discussed here: https://discourse.cataclysmdda.org/t/living-off-the-land-rural-only/26691/14

Suggestion made by me to add a recipe: https://discourse.cataclysmdda.org/t/living-off-the-land-rural-only/26691/27

**Comment by Zireael07** [comment]
Is this still relevant after https://github.com/CleverRaven/Cataclysm-DDA/pull/51075?

**Comment by NetSysFire** [comment]
Yes, since this is about *crafting* clean water. But the physics method mentioned may work.

**Comment by ZhilkinSerg** [comment]
Should be related https://github.com/CleverRaven/Cataclysm-DDA/pull/41332

**Comment by NetSysFire** [comment]
Yes, this looks very relevant. You can not boil water with closed tins.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/living-off-the-land-rural-only/26691/32
