### ISSUE TITLE
No sorting zone for currency or maps

### ISSUE THREAD

**Issue by YourCompanionCube** [CleverRaven/Cataclysm-DDA#51670]
# Is your feature request related to a problem? Please describe.
As new item categories have been introduced there haven't been subsequent sorting options added for them meaning that these items get left behind even if you have every category set up (aside from manually setting a long custom filter for all the items)

# Describe the solution you'd like
For there to be a sorting zone for each of the new categories as they are added

# Describe alternatives you've considered
Having and "overflow" category for any items that aren't in any categories that have been set up within a sorting zone, both of these would actually be good to have imo

**Comment by PatrikLundell** [comment]
I've noted that maps don't seem to belong to any category, so I manually put them into a bookshelf with "just for fun" books.

**Comment by YourCompanionCube** [comment]
closed by https://github.com/CleverRaven/Cataclysm-DDA/pull/51691
