### ISSUE TITLE
Segmentation fault and crash when attempting to reinforce duffel bag.

### ISSUE THREAD

**Issue by redcrate** [CleverRaven/Cataclysm-DDA#51674]
### Describe the bug

I was going through repairing/reinforcing my clothes and eventually found that attempting to do so on my duffel bag caused the game to seg fault and crash.

### Steps To Reproduce

Load attached Save
Activate sewing kit in inventory
Select worn duffel bag
Choose to repeat until reinforced
Wait about 2 seconds...
Seg Fault

### Expected behavior

I expect nothing, but hope for the game to not seg fault.

### Screenshots

Just before the crash.
![image](https://user-images.githubusercontent.com/85591702/133821135-740e91f6-5fe9-48e2-9d6b-0189a57fe68d.png)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.3 LTS; Release: 20.04; Codename: focal; 
- Game Version: 8d47fe3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Since it is seg faulting i don't think it can create a crash log file as there is none in the config folder.
I have uploaded the save folder and debug.log in a zip.
[crash_debug_and_save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7187112/crash_debug_and_save.zip)

**Comment by redcrate** [comment]
While playing with this bug some more I noticed that sometimes the crash doesn't trigger if the character runs out of patchwork clothing parts and in the save i only had 3 readily available, you can cut up more nearby thogh and it does trigger if there's enough stock.

**Comment by eltank** [comment]
Tried a few times using the same game version, didn't get a crash (on Windows, using an MSYS build). I either run out of cotton parts or if I cut up more I get a reinforced duffel bag.

**Comment by eltank** [comment]
What are your tileset settings looking like (main and overmap)?

**Comment by redcrate** [comment]
> What are your tileset settings looking like (main and overmap)?

![image](https://user-images.githubusercontent.com/85591702/133872601-5a18fd60-b802-4ee7-a8a9-21121d6d7224.png)

**Comment by redcrate** [comment]
still looking for the core dump to analyze further closer, but here is part of the kernel log from the various times i've crashed it

`Sep 17 06:27:14 blackbox kernel: [34698.105437] traps: cataclysm-tiles[7160] general protection fault ip:55dfd32e8767 sp:7ffe351b0900 error:0 in cataclysm-tiles[55dfd2c00000+12fe000]
Sep 17 09:17:01 blackbox kernel: [44885.188506] traps: cataclysm-tiles[13616] general protection fault ip:558487ce8767 sp:7ffff1d78560 error:0 in cataclysm-tiles[558487600000+12fe000]
Sep 17 10:04:56 blackbox kernel: [47760.539329] traps: cataclysm-tiles[17125] general protection fault ip:55e527ae881b sp:7ffed44ff670 error:0 in cataclysm-tiles[55e527400000+12fe000]
Sep 17 11:04:02 blackbox kernel: [51305.921360] traps: cataclysm-tiles[17940] general protection fault ip:55e93eae881b sp:7ffcdc200050 error:0 in cataclysm-tiles[55e93e400000+12fe000]
Sep 17 11:05:36 blackbox kernel: [51400.174194] traps: cataclysm-tiles[18043] general protection fault ip:55f732ae881b sp:7ffcc5481e00 error:0 in cataclysm-tiles[55f732400000+12fe000]
Sep 17 11:09:51 blackbox kernel: [51655.458120] traps: cataclysm-tiles[18114] general protection fault ip:5560bb6e881b sp:7fff69d681d0 error:0 in cataclysm-tiles[5560bb000000+12fe000]
Sep 17 11:26:03 blackbox kernel: [52626.822872] traps: cataclysm-tiles[18169] general protection fault ip:5606fa0e881b sp:7ffdac296820 error:0 in cataclysm-tiles[5606f9a00000+12fe000]
Sep 17 11:27:26 blackbox kernel: [52710.335611] traps: cataclysm-tiles[18361] general protection fault ip:55a7c8ce881b sp:7ffcc77c0bd0 error:0 in cataclysm-tiles[55a7c8600000+12fe000]
Sep 17 11:58:34 blackbox kernel: [54578.288276] traps: cataclysm-tiles[18901] general protection fault ip:5571502e8767 sp:7ffe3ae21e30 error:0 in cataclysm-tiles[55714fc00000+12fe000]
Sep 17 12:02:34 blackbox kernel: [54818.066326] traps: cataclysm-tiles[18971] general protection fault ip:565214ee76fb sp:7ffd2aeccb30 error:0 in cataclysm-tiles[565214800000+12fc000]
Sep 17 12:19:14 blackbox kernel: [55818.026409] traps: cataclysm-tiles[19335] general protection fault ip:559bf26e76fb sp:7ffde8a53770 error:0 in cataclysm-tiles[559bf2000000+12fc000]
Sep 17 23:39:09 blackbox kernel: [  484.247520] traps: cataclysm-tiles[2733] general protection fault ip:5612d5ce76fb sp:7fff2ab0eac0 error:0 in cataclysm-tiles[5612d5600000+12fc000]
`

**Comment by redcrate** [comment]
> What are your tileset settings looking like (main and overmap)?

Since you've mentioned the tileset, i've changed the tile-set setting dramatically and that did not mitigate the crash.

**Comment by redcrate** [comment]
As an update, it does not appear to be specific to any article of clothing specifically, but the process of reinforcing them. Repairing completes without a crash, however, reinforcing produces the crash.

**Comment by redcrate** [comment]
I have meticulously downloaded build after build to test and determine when my crash problem came into existence. Builds prior to 401cc441715b1e034345141360b0f9e6fe661ea3 seem to work fine. Though the commit for that build seems innocuous. #51650. Builds prior to this commit work fine without crashing for me.

**Comment by Sumguy62** [comment]
Can confirm the same crash on OSX with version 0.F-2737-g0efe692cae when attempting to reinforce a chest rig.

**Comment by anothersimulacrum** [comment]
I can reproduce it with UBsan, without it simply tells me that I do not have enough materials to repair it more than once.
```
src/item_location.cpp:738:17: runtime error: member call on address 0x6040012c4f10 which does not point to an object of type 'item_location::impl'
0x6040012c4f10: note: object has invalid vptr
```

**Comment by redcrate** [comment]
> I can reproduce it with UBsan, without it simply tells me that I do not have enough materials to repair it more than once.

Sorry, when I made the save I only had a few patchwork clothing parts available, but you can cut up more nearby.

**Comment by anothersimulacrum** [comment]
That is fine - what I am saying is that the crash is due to udefined behaviour, and so that will be why some people are not able to reproduce it. Even with the materials, I expect I would not get the crash.

**Comment by svenstaro** [comment]
I believe I found a fairly easy fix. Can you guys help me test?
