### ISSUE TITLE
Examining "e" workbench/table/etc does not bring up the craft/recraft/etc small window.

### ISSUE THREAD

**Issue by Quintovir** [CleverRaven/Cataclysm-DDA#51684]
### Describe the bug

Whein I examine working surfaces (workbench, table, etc) the window below does not show up:
![3d4db62d2f19652738988184db718934587a9598](https://user-images.githubusercontent.com/28264543/133870530-48629289-5700-4ec0-9c4e-6e9a1a186c7f.png)
and nothing happens.

### Steps To Reproduce

1. Examine "e" a working surface (workbench, table, etc).
2. Nothing happens.

### Expected behavior

The working surfaces (workbench, table, etc) crafting menu should show up when I examine them.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 21.1.2; Codename: Pahvo; 
- Game Version: 0.F-2729-g6b325a91eb-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    No Hope [no_hope],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    No Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

Save file.
[Wolfe City.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7189107/Wolfe.City.zip)

**Comment by Quintovir** [comment]
[The No Hope mod seems to be breaking the function according to Valase](https://discourse.cataclysmdda.org/t/resuming-item-being-crafted-on-a-table-workbench/27057/9?u=quintovir)

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/resuming-item-being-crafted-on-a-table-workbench/27057/10

**Comment by Night-Pryanik** [comment]
Working as intended in No Hope.
