### ISSUE TITLE
Vehicle welding rig requires welder?

### ISSUE THREAD

**Issue by YourCompanionCube** [CleverRaven/Cataclysm-DDA#51692]
### Describe the bug

Not so much a bug as a weird balance thing, why does the vehicle welding rig require a welder to craft (though sensibly not to mount)

### Steps To Reproduce

Look at the recipe

### Expected behavior

That crafting a welding rig wouldn't require me to make *another* welder besides the one i used to make the component kit

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 89a5de5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Gun Cotton [guncotton],
    Stats Through Skills [StatsThroughSkills],
    Useful Helicopters Experimental [useful_helicopters],
    SpeedyDex [speedydex]
]

### Additional context

i would imagine you would make a vehicle welding rig by basically just setting up a rack for the welder and altering the power connections to go to the vehicle's power instead of a battery, which shouldn't require any welding though a soldering iron might make sense

**Comment by atealein** [comment]
The welder in the welding rig of a vehicle relies on the power of the vehicle once assembled and installed. Thus it is without power (in fact it needs to be without installed battery to be used in the crafting recipe for the welding rig) and you need a different item to combine it all in one module and then install to the power source. 

I don't see it as a bug and you can use different tools for this - including the acetylene torch which cannot be used for the construction of the rig itself.

**Comment by YourCompanionCube** [comment]
ok i understand why you would need a seperate tool for power, what i don't understand is why a welder is required *at all*

**Comment by atealein** [comment]
Almost all vehicle parts installation (few exceptions for batteries and wheels and others) require welding in something. The welding rig as a part is not built directly onto the vehicle, you can make it somewhere else, transport it, then install on one vehicle, uninstall and move to another. This isn't a small correction that a soldering iron can fix - which is for more small scale and detailed work.

**Comment by YourCompanionCube** [comment]
i still don't get how you need a welder when you make the part but not when you install it

especially when i can't find any logical reason why the welder would need welding to function when you're starting with a functional welder and then bolting (literally installed with a wrench) it onto the vehicle, it should just be a welder on a rack that you wire into your vehicle's wiring harness

the reason i think that you *might* need a soldering iron when crafting it is that you have to convert from battery power to cable power from the vehicle, but that's arguably already taken care of in the "welding component kit" step

**Comment by chrispikula** [comment]
When you make a welder, you are also making the frame, and the housing for the welder, none of which you want to be free or loose.  Grounding, cable holding, lower chance of scattering in a bump or crash, etc.

This would be an example of a vehicle welding rig  (Ours is probably not near as good looking.): 

https://scontent.fyqr2-1.fna.fbcdn.net/v/t1.6435-9/s960x960/164330861_256016522843138_6135718869493087906_n.jpg?_nc_cat=103&ccb=1-5&_nc_sid=843cd7&_nc_ohc=fISdkhhCeQgAX-w1ybS&_nc_ht=scontent.fyqr2-1.fna&oh=aab0b34383961077502ae4457c88ce5f&oe=616A23CE

As you can see, it's frame would require some welding work to make.

**Comment by YourCompanionCube** [comment]
that looks like every shop welder i've ever had, nothing special to mounting it to a vehicle and i see nothing in that picture that would require additional welding from what a normal welder comes from the factory with

the main reason that i made this is it's ridiculous from a gameplay perspective (on top of not making a ton of logical sense) where if i want to create a vehicle rig from scratch i have to make *3* makeshift welders, one of which i just... throw away afterwards

**Comment by YourCompanionCube** [comment]
> When you make a welder
for the record, you're not making a welder from scratch, this is just the mounting solution for an existing welder to a vehicle and the ability for it to hook into the power supply there

**Comment by PatrikLundell** [comment]
If it's any consolation, there are situations in which you'd want a portable welding capability, such as any companion base camp work requiring welding, and it doesn't make much sense to try to use a vehicle mounted welder to mount stuff onto another vehicle (even though the system might allow it, if you park your vehicle close enough, and that makes sense with the single tile welding "vehicles" you can find in the game).

**Comment by YourCompanionCube** [comment]
i'd much rather have to make a new solution to a new problem than find a problem of an accidental "solution"
