### ISSUE TITLE
Allow mutation tiles to be affected by skin tone

### ISSUE THREAD

**Issue by KittyTac** [CleverRaven/Cataclysm-DDA#51690]
# Is your feature request related to a problem? Please describe.
In a lot of detailed tilesets, like Ultica, there are problems with tiles for mutations (such as elf ears) or even eye colors clashing with dark or light skin colors, preventing the addition of those tiles.

# Describe the solution you'd like
Allow mutations to optionally set their tiles to be triggered by skin tone (and additionally hair color too, for things like animal ears). And perhaps by other mutations too, for things like snout.

# Describe alternatives you've considered
Making a system where the tiles have some sort of placeholder color which can be filled in according to skin tone. But this way is easier and more flexible, even if it results in more tiles needing to be made.

# Additional context
An example would be "overlay_female_mutation_ELFA_EARS_SKIN_DARK".

**Comment by Cactoideae** [comment]
Isn't this already a thing with some other tilesets? I remember in UDP the default Chitin Plate looks black, but if you also have Pale Skin it becomes white instead, while still looking like chitin.

**Comment by KittyTac** [comment]
> 
> 
> Isn't this already a thing with some other tilesets? I remember in UDP the default Chitin Plate looks black, but if you also have Pale Skin it becomes white instead, while still looking like chitin.

I think it's just semitransparent.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
