### ISSUE TITLE
Add descriptions to construction recipes.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#517]
The construction recipes are rather inscrutable and non-intuitive to interact with.  Adding a description field to each construction recipe that is displayed in the construction menu would go a long way toward clearing this up.
##

**Comment by Xpyder** [comment]
If you tell me what tag to add I'd be up for adding placeholder tags for the items to make it easier for other people to edit.  They already have one called "Description" but that seems to just be the name.

(I'm assuming you're talking about \data\json\construction.json if it's in a different file let me know)

**Comment by Night-Pryanik** [comment]
Should be closed after #20519?
