### ISSUE TITLE
Going to sleep with Repair Nanobots active triggers shut-off warning

### ISSUE THREAD

**Issue by Kribylet** [CleverRaven/Cataclysm-DDA#51717]
### Describe the bug

When you go to sleep with repair nanobots active the game suggests turning them off to conserve power. AFAIK the nanobots draw no idle power since #45985, so this is probably an oversight.

### Steps To Reproduce

1. Have repair nanobots installed and active
2. Go to sleep
3. Be prompted suggesting that nanobots be shut off.

### Expected behavior

No warning.

### Versions and configuration

OS: Linux Mint 20.2
Game Version: 0F-1
Graphics Version: Tiles
Ingame language: English
Mods: dda, no_npc_food, package_bionic_professions

**Comment by hexagonrecursion** [comment]
Confirmed.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: eacb7d9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by LeahLuong** [comment]
Reflex Photophore (on) also triggers that warning but the player has no direct control over the mutation.
