### ISSUE TITLE
win32 / vcpkg build: font glyphs not rendering

### ISSUE THREAD

**Issue by nornagon** [CleverRaven/Cataclysm-DDA#51736]
### Describe the bug

When building on Windows 10 with Visual Studio 2019 and the vcpkg build, no glyphs are rendered:

![image](https://user-images.githubusercontent.com/172800/133951881-c04b9d2d-e0f0-4e2b-819e-500537093d8a.png)

### Steps To Reproduce

1. Build a Release/x64 build on Windows 10 with Visual Studio 2019 and vcpkg using the instructions at https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/COMPILING/COMPILING-VS-VCPKG.md
2. Run the exe from within Visual Studio

### Expected behavior

Text should render

### Versions and configuration

built at 8ba81b4abbd3ce3e9be94b1440ed80f24befdb9d

**Comment by anothersimulacrum** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/issues/50149#issuecomment-920210863
