### ISSUE TITLE
You are completely unable to fight in melee at all with a broken leg

### ISSUE THREAD

**Issue by jumjummju** [CleverRaven/Cataclysm-DDA#51735]
### Describe the bug

If you break a leg, you immediately fall over into prone whenever you try to walk or stand back up. While in this state, you are given an error: "You cannot fight while on the ground" that prevents you from attacking no matter what. No matter what I tried to do (moving after falling over, standing back up and immediately attacking, passing turns) I was unable to attack whatsoever. Going prone manually, without broken legs, does _NOT_ cause this issue.

### Steps To Reproduce

1. Spawn a character in, debug spawn in a test dummy or zombie.
2. Debug damage your leg to broken.
3. Observe you are entirely unable to attack, even in a debuffed state, leaving you 100% helpless unless you have a firearm.

### Expected behavior

Obviously, fighting while prone should be difficult, especially if you're also dealing with a broken leg. But if a zombie (or in my case, a mutant coyote) is pouncing on you while you're lying there, you should still be able to feebly fight back in desperation rather than just lying there like a lemon. I'm not sure if there necessarily needs to be any special debuffs for this beyond the normal fight debuffs for having a broken leg, the pain from it breaking, and being prone. So, to clarify, I obviously don't think you should be able to fight unimpeded, and naturally you shouldn't be able to chase anything down (though this is already handled by prone's massive movecost) or dodge, but you should still be able to swipe your combat knife or flail somewhat ineffectually with a longsword if an enemy is actively dogpiling you.

### Screenshots

![image](https://user-images.githubusercontent.com/75549031/133951657-750161cc-ab94-4b27-baa0-73955b851a2a.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 09095af [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by sharkfinsouperman** [comment]
Would a wearable crutch item be an additional solution to making it possible to fight while prone?

If so, I can also see an additional speed increase over hobbling around with splinted limbs and a possible proficiency for survivors who've become accustomed to using them being part of the implementation.
