### ISSUE TITLE
A pill being "frozen" should not affect the character's ability to consume it.

### ISSUE THREAD

**Issue by redcrate** [CleverRaven/Cataclysm-DDA#51740]
# Is your feature request related to a problem? Please describe.
Pills that are frozen can not be consumed.

# Describe the solution you'd like
In real life, a pill being frozen does not affect my ability to consume it. I have consumed many a frozen pill left in my vehicle during the dead of winter. Therefore, consuming frozen pills in game should be an option.

I do agree that things like a frozen protein bar would not be consumable just as the ones I've allowed to freeze in my car could not be consumed by me until they have thawed enough that I can bite off a chunk, a pill does not have this limitation.

# Describe alternatives you've considered
Make "frozen" pills consumable. Perhaps their effect will take longer to kick in since it will take a bit longer for them to be warmed up in the stomach and available to be digested.

# Additional context
N/A

**Comment by TealcOneill** [comment]
#51678 should be merged fairly soon and fixes this exact issue.

**Comment by redcrate** [comment]
fixed by #51678
