### ISSUE TITLE
Martial Arts error on character creation

### ISSUE THREAD

**Issue by Pynter** [CleverRaven/Cataclysm-DDA#51766]
### Describe the bug

Creating a new character makes the game throw an error and quits back to main menu.

I manually fixed it by reverting the change done by [this pull](https://github.com/CleverRaven/Cataclysm-DDA/pull/51662).

### Steps To Reproduce

1. Download as of writing latest version.
2. Try to create a new character.

### Expected behavior

Game goes to character creation.

### Versions and configuration

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7202739/debug.log)

**Comment by ISuckM8** [comment]
Made a PR to fix this, hopefully it'll get merged soon.
