### ISSUE TITLE
Ubuntu 20.04 & 21.04 libncursesw.so.5

### ISSUE THREAD

**Issue by silentiumNoxe** [CleverRaven/Cataclysm-DDA#51775]
### Describe the bug

Can't open application until 0.E version
Returned error - error while loading shared libraries: libncursesw.so.5: cannot open shared object file: No such file or directory

0.D can be started in Ubuntu 20.04

### Steps To Reproduce

starting game

### Expected behavior

game start

### Screenshots

no needed

### Versions and configuration

Ubuntu 20.04
Stable 0.F-2

**Comment by ZhilkinSerg** [comment]
Did you try installing `libncursesw`?

**Comment by silentiumNoxe** [comment]
> Did you try installing `libncursesw`?

Yes, it is not resolve the problem

**Comment by silentiumNoxe** [comment]
~/app/cataclysmdda-0.F$ whereis libncursesw.so.5
libncursesw.so: /usr/lib/x86_64-linux-gnu/libncursesw.so.6

**Comment by silentiumNoxe** [comment]
I think that need to compile a source in the newest linux version

**Comment by Maleclypse** [comment]
Is this still an issue?

**Comment by silentiumNoxe** [comment]
yes

**Comment by NetSysFire** [comment]
This is also reproducible on Arch Linux since we have `libncursesw.so.6.3` and all the experimental builds link against `libncursesw.so.5`, forcing me to compile it myself instead.

**Comment by ZhilkinSerg** [comment]
> > Did you try installing `libncursesw`?
> 
> Yes, it is not resolve the problem

What if you install version 5?

**Comment by silentiumNoxe** [comment]
> > > Did you try installing `libncursesw`?
> > 
> > 
> > Yes, it is not resolve the problem
> 
> What if you install version 5?

this is not Imposible

**Comment by tbukfrc** [comment]
> `~/app/cataclysmdda-0.F$ whereis libncursesw.so.5` `libncursesw.so: /usr/lib/x86_64-linux-gnu/libncursesw.so.6`
> 
> `sudo apt-get install libncurses5` `Reading package lists... Done Building dependency tree... Done Reading state information... Done libncurses5 is already the newest version (6.2+20201114-2build1). 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`

You need to install `libncursesw5` instead of `libncurses5`
