### ISSUE TITLE
Many artifacts are broken

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#51777]
### Describe the bug

The current state of artifacts is lacking, and there are many examples of artifacts that just don't work.
I've dived into a number of mines and while my sample size is probably not sufficient I've experienced multiple bugs.
The "heal self" artifact doesn't work. When I use it I get the "you feel healed" message but can confirm with Self-Aware that it doesn't heal me at all; I get a "the shot reflects off your torso!" message and it occasionally damages my gear. The "HURTALL" activation effect gives me an "invalid damage type" error and then fails to do any damage to anything.

In addition, artifacts currently feel very incomplete. There are currently no clothing/armor artifacts and haven't been for a good while, only activate-only ones. Further the stat changes of activate-only artifacts are relatively pointless since they require the artifact to be wielded actively to take effect - this largely limits their use to +Speed effects for crafting, +Strength effects for installing heavy vehicle parts, and +Intelligence effects for installing CBMs and talking to people. The passive effects don't fit for an activatable item, especially the attack speed modifiers. Perhaps instead they could apply while in your pockets (overpowered if you had enough?) or while mounted to a rare talisman which would limit your artifact effects to 2 instead of infinite. Also, the old artifact recharge types seem to be gone, currently I've only found 1 charge/hour variants. That griping probably belongs in a separate issue but it is heavily related to the current affair of artifacts (they were changed and then left unfinished) so I believe it belongs here too.

### Steps To Reproduce

1. Spawn artifacts with debug.
2. Observe the broken.

### Expected behavior

All artifact effects should "work", a healing artifact should heal me and a hurting artifact should hurt enemies. Artifacts should have the variation and coolness of their original selves. 

### Screenshots

![artifact](https://user-images.githubusercontent.com/56016372/134248283-a718ad77-eac7-4971-bc60-a4acfc3ddc93.PNG)

### Versions and configuration

Windows 10, latest experimental.

**Comment by Machminotaur** [comment]
I can confirm I've had the same deflection/invalid bugs. I've also had an artifact that buffed my speed dramatically, twice, leaving me holding an instance of the buff if my hands were free.

**Comment by atealein** [comment]
I can confirm the uselessness of passive effects. Right now all artifacts/relics that I've seen spawned in the game that have passive effects require "WIELD" and "ALWAYS" (to be wielded to get the passive effects), which basically makes the ones that lower your attack speeds (i think OP mentioned this too) pointless - you would want to wield your actual weapon to do that.

**Comment by anoobindisguise** [comment]
a lot has changed since this happened. closing
