### ISSUE TITLE
Statsthroughkills is broken

### ISSUE THREAD

**Issue by mrrobustno** [CleverRaven/Cataclysm-DDA#51786]
### Describe the bug

Each kill generates a large amount of xp that makes it impossible to use the mod to level up skills.

### Steps To Reproduce

1. Create a new world with statsthroughkills mod included.
2. Generate character.
3. Kill a mob.
4. Hit the ) key, and check the kills section for XP gained.

### Expected behavior

I expected the mod to work like normal, when it didn't on this latest experimental. 

### Screenshots

![Screenshot (153)](https://user-images.githubusercontent.com/91169556/134274254-468a42a6-4e2a-488b-ba35-ba8857c3b29e.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 99dc03c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Extra Mutated Scenarios [extra_mut_scens],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

### Additional context

***Edit*** Loading the latest stable and using statsthroughkills works as intended.

**Comment by Entity-y** [comment]
Started a new game on the latest experimental with statsthroughkills and couldn't replicate issue.


![image](https://user-images.githubusercontent.com/50155659/134295324-2aa3bc84-d97b-45c8-be47-8f394b478963.png)

**Comment by ferociousdork** [comment]
Confirmed, `kill_xp` and `spent_upgrade_points` aren't initialized to zero properly in #51687, so all bets are off. I just got these values on a new character:
`"kill_xp": 22074, "spent_upgrade_points": -670002136`.

**Comment by actual-nh** [comment]
Ping: @eltank?

**Comment by eltank** [comment]
Sorry about that, I suspect the reason I didn't spot this during testing (and also why it's not broken for everyone) is because those fields were getting 0-initialized on my system but it's actually undefined behavior.
Thanks for fixing it, @ferociousdork!
