### ISSUE TITLE
Maple Sugar Should Not Need Lye / Make Maple Sugar Its Own Recipe

### ISSUE THREAD

**Issue by CptCodpiece** [CleverRaven/Cataclysm-DDA#51780]
# Is your feature request related to a problem? Please describe.
Currently the sugar recipe will take maple syrup as a component and demand that you use lye in it to give you regular sugar. 
It'd make more sense to just make granulated maple sugar by boiling it down with heat and leave out the lye and complicated chemistry stuff.

# Describe the solution you'd like
Just include a boil recipe for maple syrup -> sugar that uses the current sugar cooking code. Strip out the lye line and you're good. (It requires a good amount of coercing to stir, so probably give it a moderate exercise activity?)

If anyone can suggest a time where you couldn't just interchange maple sugar for regular granulated cane sugar, let me know.

# Describe alternatives you've considered
Just making a separate maple sugar item with its own separate maple sugar recipe. But it seems to just promote item bloat, when you have a perfectly good regular sugar item in the game as it is.  I don't think a survivor would really be so fussy as to not use maple sugar in place of cane sugar for any given recipe. 

# Additional context
Personal experience over a stove has it at somewhere just shy of 30 minutes cook time, but I cook while chatting, so I always go over. You can probably keep it at the current 24 minutes cooking time with no changes. There's also countless YT videos on it it, so I'd assume it to be a pretty low-skill recipe. More than cook 0, but probably no more than 2. Definitely not a cook 4 though.

**Comment by anothersimulacrum** [comment]
Fixed in https://github.com/CleverRaven/Cataclysm-DDA/pull/51789
