### ISSUE TITLE
Activating an RC car from item view does not work

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#51807]
### Describe the bug

When an RC car is in the inventory, viewing the item with `Enter` then selecting `a`ctivate from the item action menu gives a message popup "You don't have any items with registered uses". However, using the main `a`ctivate ("Use item") menu, selecting the RC car works as expected (although the "Action" column shows `...` where there should be an action like "Turn on car").

### Steps To Reproduce

1. Get a radio car box, unpack it, and install batteries in the RC car and RC control
2. Go to `i`nventory screen, select RC car, press Enter
3. Select "activate" from the item detail screen, press Enter

### Expected behavior

I should be able to activate the RC car from the item detail screen, the same as activating it in my inventory.

### Screenshots

RC car, selecting "activate":

![image](https://user-images.githubusercontent.com/238395/134420133-def5a424-8fd0-4906-b14a-f9dffbf326ae.png)

Says "You don't have any items with registered uses"

![image](https://user-images.githubusercontent.com/238395/134420186-755848e3-ee35-488f-9238-457cb97f15e4.png)

But the main `a`ctivate screen shows the RC car (though its action shows "...")

![image](https://user-images.githubusercontent.com/238395/134420958-43e7e9e5-60d0-404f-96e9-164322a22bdd.png)

Pressing Enter on the RC car gives the action prompts to "Turn on" or "Put a bomb to car" as expected:

![image](https://user-images.githubusercontent.com/238395/134421059-455bf723-5459-450b-8038-0fb28373979d.png)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-2852-g99dc03c98e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Generic Guns [generic_guns],
    Mythical Martial Arts [MMA],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi]
]

**Comment by l29ah** [comment]
I'll try bisecting this.

**Comment by l29ah** [comment]
1ec8c90fed6cf43aa9cb169aa32ca25a3fdb3829 is the first bad commit

**Comment by RoyBerube** [comment]
Am looking into it. Items with pockets are getting activated incorrectly. My bad.
