### ISSUE TITLE
Crash without crash report during sleep on Win64

### ISSUE THREAD

**Issue by utechenko-v** [CleverRaven/Cataclysm-DDA#51812]
### Describe the bug

Game crashed during character's sleep, and it keeps crashing if I use savegame made before going to sleep. There is no crash report or any errors logged.

### Steps To Reproduce

1. Load savegame on Win64 tiles game
2. Sleep for 4 hours (or more)

After that, game crashes - process just got closed.
(sometimes there is no crash, but typically game crashes)

### Expected behavior

There should be no crash.

### Versions and configuration

- OS: Windows 10
- build type: windows-tiles-x64
- build number: 2021-09-22-0438
- commit sha: 423e7b8bfe4d8f016d63ba388e1379ced6970c24
- Graphics version: [Tiles]
- Ingame language: [Ukrainian - partial translation]
- Mods loaded: dda, disable NPC needs

### Additional context

savegame
[save_sleep_crashes_Win64_sometimes.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7214392/save_sleep_crashes_Win64_sometimes.zip)

**Comment by BrettDong** [comment]
```
VERSION: 0.F-2881-ge1e5c9edf2
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

    0   cataclysm-tiles                     0x0000000104c55b90 debug_write_backtrace(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) + 72
    1   cataclysm-tiles                     0x0000000104c2b7a4 log_crash(char const*, char const*) + 580
    2   cataclysm-tiles                     0x00000001059d287c signal_handler(int) (.cold.1) + 32
    3   cataclysm-tiles                     0x0000000104c2b46c crash_terminate_handler() + 0
    4   libsystem_platform.dylib            0x000000019cb36c44 _sigtramp + 56
    5   cataclysm-tiles                     0x0000000104abbdc0 Character::process_effects() + 1036
    6   cataclysm-tiles                     0x0000000104c2c638 Creature::process_turn() + 64
    7   cataclysm-tiles                     0x0000000104a96c18 Character::process_turn() + 360
    8   cataclysm-tiles                     0x0000000104cb7fac do_turn() + 6800
    9   cataclysm-tiles                     0x000000010514f640 main + 3572
    10  libdyld.dylib                       0x000000019cb09430 start + 4
```
