### ISSUE TITLE
Combat stances for guns

### ISSUE THREAD

**Issue by scavtoons** [CleverRaven/Cataclysm-DDA#51813]
# Is your feature request related to a problem? Please describe.
No, it's more like an addition

# Describe the solution you'd like

The basic idea is pretty clear, make an addition to the martial art menu for combat stances and add features that let them interact with gun recoil, accuracy, penetration and critical rate, working along with the enemy coverage system. This feature idea Inspired by modern FPS sims were weapon inertia affects your aim time and accuracy.

# Describe alternatives you've considered
Make combat stances as close to normal martials arts as possible, but with the difference that techniques use bullets from your current gun.

# Additional context
As i haven't reversed engineered game code yet, theoretically what would be needed to is to expand the martial arts code along with the aiming code, that lets us include additional properties to a .json martials art entry. So we can give bonuses to recoil, accuracy, critical and armor penetration of a shot action, either as a bonus of the combat stance or a technique of it. Also modify the technique code so techniques can be activated depending on the aim mode selected (current, aimed, careful, precise) and current fire mode, and for the aiming part of the game to be able to take this new information into account. 

Also code that lets us check for weapon attachments and total weight for buffs and technique activation. And probably even code that lets us check for holsters and weapons in them for features like a quickdraw.

Pretty much, martial arts techniques trigger when hitting an enemy, and combat stances techniques should be triggered when shooting. 

With no more information to add here are some examples of a combat stance:

**Combat pace:** You get a grip of your gun and ready it up aiming forwards, moving slower but methodically so your accuracy is not compromised when stopping and turning, helping you shoot faster and precisely when encountering an enemy.

**Buffs:**

-Slow pace: You walk firmly but slowly so your aim is not compromised. Requires Marksmanship 1. Effects: Time to aim penalty when moving is lowered depending on dexterity and marksmanship skill, speed is reduced by 25%, deactivated when running.

-Raised gun: You raise your gun a keep it up no matter what, your arms will begin to hurt after a while.
Requires Marksmanship 1. Effects: Accuracy bonus based on marksmanship level and strength. Stamina drains faster depending on strength and weight of the gun, high levels of strength with a lighter weapon should make this effect barely noticeable, deactivated when running.

-Lowered gun: You lower your gun to run and move more comfortably. Requires marksmanship 0. Activated when running and moving. Effects: You lose all bonuses all debuffs from combat pace duration 1 turn.

-Broken stance: You were suddenly hit and lost your aim. Activated when the player is hit.Effects: You lose all bonuses all debuffs from combat pace duration 1 turn.

**Techniques:**

Quick recovery. Requires marksmanship 4. Activated when using Current aim and broken stance is active.Effects: Raised gun bonuses are reactivated, uses stamina and cannot be used when stamina is low, like a counter. _"You quickly recover your aim and shoot zombie in the head for 69 damage"_

Target acquisition: Requires marksmanship 4. Activated when using Careful aim in single fire. Accuracy and time to aim bonus when attacking a different target than the last one. (Meant to be use with low recoil weapons and when enemies are getting close) "You quickly switch your aim to the next enemy without losing your stance"

Concentrated Fire: Requires marksmanship 2. Activated when using Precise aim. Bonus to crit chance when hitting the same enemy consecutively. _"You concentrate after your last hit to get a better next shot"_

Spray and pray: Requires marksmanship 1, Activated when using aimed shot, when raised guns is active while using full auto or burst mode. Bonus to time to aim.

**Weapons:** Basically all guns except for mounted ones.

**Hitman stance:** You acquire a modest estance with your weapon so you can move freely but does not provide many advantages to conventional marksmanship.

**Buffs:**

Sureshot: You're ready to quickly strike your victim once the close the gap between each other.Requires Marksmanship 1. Effect: 50% bonus accuracy to current aim shots when the enemy is 4 tiles or less away from you.

Quick Hands: You tune your reflexes to quickly aim your gun. Requieres marksmanship 0. You get a bonus to accuracy based on Dexterity.

Hitman determination: You're in a ready position to make a quick and precise strike with your gun. Requires marksmanship 4. Effects: Improved chance of hitting enemy weak points. 5% Critical chance to current aim shots. Duration 3 turn. Stacks 3 times.

Assassin step: You move graciously with your gun as if it was an accessory, and you're ready to strike at any time. Requires Marksmanship 2. Activated on move.Effects: Time to aim penalty when moving is lowered depending on dexterity, strength, weapon weight and marksmanship skill .

**Techniques:**

Point Blank: Requieres marksmanship 1. Activated when using Current aim. Bonus to penetration and critical based on dexterity, only when enemy is one tile away from you. _"You point your gun directly against zombie torso and shot for 40 damage"_

Pop shots: Requieres marksmanship 3. Activated when using Aimed shot and the enemy is 4 tiles or less away from you. Bonus to time to aim when shooting the same target multiple times.

Dropshot: Requires marksmanship 2. Activated when using Careful shot and the enemy is 4 tiles or less away from you. Knockdowns the enemy for 2 turns.

Grace shot: Requires marksmanship 4. Activated when using precise aim. When you critical shoot an enemy and it doesn't die, the next shot gets maximum time to aim bonus and a critical bonus based on accuracy.

**Weapons:** Handguns, Submachine Guns and light shotguns & rifles.

This 2 examples are a pretty good starting point of what i've thought, techniques could also be activated with any kind of aimed shot. some other examples include a combat stance that lets characters with certain traits use heavy weapons with some conditions, and a sniper/machine gunner stance that relies on being prone or behind cover for shooting.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
