### ISSUE TITLE
Move furniture through Z-levels

### ISSUE THREAD

**Issue by Entity-y** [CleverRaven/Cataclysm-DDA#51826]
# Is your feature request related to a problem? Please describe.
The only way to move furniture, like a wood stove for example, between Z-levels is to disassemble and reassemble. That is if your mechanics skill is high enough to put it back together.

# Describe the solution you'd like
Implement a hand truck to attach furniture to, reducing strain while also allowing for transitioning between Z-levels.

# Describe alternatives you've considered
Foldable hand truck.

Requiring straps to attach furniture, could be found in the back of trucks or inside garages.

# Additional context
![image](https://user-images.githubusercontent.com/50155659/134495250-b8693920-f88a-495c-bb18-5a70a3d54f5c.png)
![image](https://user-images.githubusercontent.com/50155659/134495418-9f4ce262-b30e-4fd6-a9e8-6e872608da5e.png)

**Comment by Saicchi** [comment]
Would that work with any furniture or only ones with a specific flag?

**Comment by Entity-y** [comment]
I'd say just the furniture that can be pulled by hand if strength is high enough like couches, refrigerators and bookshelves. Cupboards on the other hand are bolted down and can't be moved, I'm sure there is more furniture like this, which reasonably would not be able to be moved with a hand truck.

**Comment by Ochrad** [comment]
The piece of furniture could be pushed off the ledge, haven't tried to drop it on another object though.
