### ISSUE TITLE
Sleeping seems to have been broken into recovering fatigue far slower

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#51839]
### Describe the bug

This is an odd issue because I have little hard and fast evidence for this and it might not be totally easy to replicate but I want to put it here in case others can corroborate this issue and perhaps identify it better.
The act of sleeping seems to be recovering my character from tiredness far, far less. I've played a lot of characters with every addiction hobby and while the "You feel tired..." messages have certainly made me need to sleep more, only just on this most recent character (started on latest experimental 947f8d7) were those withdrawl symptoms actually making me tired faster than I could sleep, I watched my sleepiness tick from tired to very tired _while_ asleep. While the addictions have worn off by now I'm noticing that I'm spending far more time than is normal asleep, it takes upwards of 12 hours to reduce my tiredness by a stage. I am not iron deficient or seemingly under the effects of anything else that would make me extremely tired.

### Steps To Reproduce

1. Create a new character
2. Observe sleeping issues?

### Expected behavior

IDK what the expected behavior here is but I would ideally want sleep to return to its intended form before it got broken, assuming it did in fact get broken and I'm not just insane. All I can say is that it wasn't like this a week ago. I don't know if there's something broken on my character or what but it feels really abnormal.

### Versions and configuration

latest experimental 947f8d7 as of writing

### Additional context

[Furnace Woods.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7224221/Furnace.Woods.zip)
Attached save file. Don't mind my shitty scrublord character and world settings lol.

**Comment by Kribylet** [comment]
Just curious, if you try using melatonin tablets do you get any messages like (para-phrasimg here)"You feel like you've recovered some of your lost sleep"?

**Comment by anoobindisguise** [comment]
> Just curious, if you try using melatonin tablets do you get any messages like (para-phrasimg here)"You feel like you've recovered some of your lost sleep"?

Consuming melatonin tablets produced no effect. will continue to see if effect persists.

**Comment by anoobindisguise** [comment]
I've done more testing with a watch. Going to sleep the exact moment I become Tired, I sleep for 10 hours and wake up, but don't get the "You feel well rested" message. Sleeping on a couch with a blanket and pillow with a blindfold on. I can then do activities for about 10 hours before becoming Tired, then I sleep 10 hours again and wake up not well-rested, this cycle stayed consistent for several days. That's 50% of my time being spent asleep, that can't be normal. I do not have the Sleepy mutation.

**Comment by anoobindisguise** [comment]
I've been doing some testing. As early back as version 4774b42 the issue is not present. Upgrading to fb48f34 the issue is present. Will try to narrow down the cause between those two points.

**Comment by anoobindisguise** [comment]
Confirmed present with 6ee1821. Fatigue is increasing while asleep, confirmed with debug

**Comment by anoobindisguise** [comment]
OK! I can say with certainty that something in experimental build 2021-09-24-0055 broke sleeping. The issue is NOT present in the previous experimental build, 2021-09-23-2236. Therefore something in that update caused the issue.

**Comment by KurzedMetal** [comment]
I got this issue too, also playing 2021-09-24-0055

Created a new world, played 6 days, the first few char seemed fine, on ~4th and 5th day I noticed he was getting tired early in the afternoon. On 6th day, my char woke up at 5:00 AM and it's already getting Tired at 6:00 AM

Something is giga broken.

**Comment by Kribylet** [comment]
Also seeing this issue on my test character for haggis on latest build. The first night the character is sleepy by evening, went to sleep without alarm. The second night sleepy by 5 pm, slept without alarm, the next "night" sleepy by 2 pm.

**Comment by FinWeirdoh** [comment]
I have the same issue. My character just slept 12 hours and is tired again right away. No sleepy trait but still my character sleeps nearly half a day everyday to keep tiredness away. I`m playing on 2021-09-25-1354 experimental build.

**Comment by atealein** [comment]
I can confirm this as well. On a character that used to be able to run for days on atomic coffee only before catching sleep when the Sleep Deprived status started to show up, now I have to spend half my days sleeping and still tired.

**Comment by wapcaplet** [comment]
Confirmed with a new basic character; set up a cot to sleep on, spawn a good supply of food and water, and wait each day:

- Day 2: awoke 11am, tired at 8pm, slept 10 hours
- Day 3: awoke 6am, tired at 5pm, slept 11 hours
- Day 4: awoke 4am, tired at 1pm, slept 10 hours
- Day 5: awoke 11pm, tired at 9am, slept 10 hours

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-2988-gab32a1296a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
