### ISSUE TITLE
Add a color hint for vehicle tiles

### ISSUE THREAD

**Issue by Kribylet** [CleverRaven/Cataclysm-DDA#51841]
# Is your feature request related to a problem? Please describe.
-

# Describe the solution you'd like
I think it'd be a neat idea to include a color "hint" associated with a vehicle. I imagine something like an integer interpreted hexadecimally as RGB, ie. 0xFFF_FFF_FF style colors. Tilesets could then use this color hint to dye vehicle tiles. Perhaps an opt-in/opt-out could be implemented in parallel with a toggle like USES_DYE or IGNORES_DYE as a property of the tiles themselves, for things like wing mirrors, vehicle coolers etc. The idea would be to have a bunch of pre-set sensible vehicle colors that would be applied to randomly generated vehicles, and to let players apply a color to vehicles they steal/create.

Edit: To be super clear, I picture tileset designers creating neutrally colored tiles for vehicles as defaults so that the game can then apply a color shift to the neutral tiles according to the hint. Not infinite work for tileset creators, but might require some care to avoid certain tiles looking goofy.

# Describe alternatives you've considered
Giving dye-values to each vehicle frame instead, but that would require a bit more memory and work for players/generic vehicle designers. Maybe frames could have an optional dye hint that if left alone just defaults to the overall vehicle dye.

# Additional context
Mostly I keep thinking of this whenever I hear people prefer the UDP vehicles over the Ultica tileset vehicle colors.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
