### ISSUE TITLE
'invalid overmap special id "FakeSpecial_s_bike_shop_1"' on save load and while moving around

### ISSUE THREAD

**Issue by ProfoundDarkness** [CleverRaven/Cataclysm-DDA#51856]
### Describe the bug

Updated master this morning and compiled.
On save load got a few of this log snippet:
ERROR : src/generic_factory.h:445 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = overmap_special]] invalid overmap special id "FakeSpecial_s_bike_shop_1"

Also periodically while moving about.

### Steps To Reproduce

1. Have a save from a day or so ago.  8ba81b4abbd3ce3e9be94b1440ed80f24befdb9d or older.  Needs the overmap special mentioned above.
2. Load the save on c5b0b8431ce2442e203452714d23bf29d72569d5 or newer.
3. Observe error message, assuming the overmap special had been generated for you in previous save.

### Expected behavior

Not getting that error message...

### Versions and configuration

- OS: Ubuntu 20.04
- Tiles version
- Version: Cataclysm DDA version 0.F-2777-gc5b0b8431c or newer
- Basic mods (dda, no_npc_food, reduced fungal growth)

### Additional context

The error is persistent, if I save and then load... *guessing* something missing related to migration?

To put some bounds on this...
Current Head: 75de0318b8a6396834a9e5bc242de957354b81e5
My previous head (maybe): 8c55e1b6c90d5e4f99c5db2a1a9048034ab878ee

I didn't think it would take very long but had a lot of interruptions, anyway this was the result of the bisect:

c5b0b8431ce2442e203452714d23bf29d72569d5 is the first bad commit

I've generated a save (involved overmap editing) on commit 8ba81b4abbd3ce3e9be94b1440ed80f24befdb9d then moved to commit c5b0b8431ce2442e203452714d23bf29d72569d5, loaded save, got the error.
[DBG_BikeShop.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7228384/DBG_BikeShop.zip)

Was kind of hoping I might understand what was wrong but nope...  Hopefully I've provided enough to make some sense of this and thus a fix (or maybe a save edit to purge the errors).

The error popping up while moving around/fighting is... a nuisance.  I'm not fond of ignore further as I'm more likely to miss other errors.

**Comment by Termineitor244** [comment]
This was introduced after #51729, the ID of the building was changed, so a migration was needed for the old ID in maps from before this change, it happens to me too (Confirmed).

**Comment by ProfoundDarkness** [comment]
Thinking I might explore how a migration could work...  I generated a new world on the current master and force generated both bike shop overmap specials (one with \_1, one without that).  As expected, no error on loading save (after saving and quitting).  Inspecting the save however shows a complete lack of "fakespecial\_.\*?bike" in the map files.  On the other hand there IS now specials simply called "s\_bike\_shop\_1" so the whole FakeSpecial\_ bit is gone.

As a test I used grepwin on my save, text search and replace all "special":"FakeSpecial\_s\_bike\_shop\_1" with "special":"s\_bike\_shop\_1".  No errors on my old save load.  I then located a bike shop, I hadn't visited one yet so that might matter.  Visiting via debug - long range teleport... it looks proper, from exploring the ones in my test world/save.  As a bonus I finally figured out how to read more of the map data in json form.

How to turn this into a migration though... ?  Item migration seems well documented with plenty of examples, this would be an overmap special migration so <shrug>.  I suppose those who know how can do the migration by hand as I did, I'd advise when doing anything like that to have a backup, as I did.

Still technically a bug due to missing migration but at least for myself personally it's apparently fixed, assuming I did that correctly.

**Comment by wapcaplet** [comment]
Here is another saved game created in 0.F-3 that reproduces this error along with the Military Outpost, Military Bunker, and several others.

[MilitaryOutpost0F3.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7695627/MilitaryOutpost0F3.zip)
