### ISSUE TITLE
Rain and Weather seems to work well for the first few days, before breaking into just sunny, cloudy, or clear

### ISSUE THREAD

**Issue by Paprika-H** [CleverRaven/Cataclysm-DDA#51861]
### Describe the bug

For the first week of a new world, it seems that weather like rain works fine and dandy, but after that period, you can go months without seeing rain. 

### Steps To Reproduce

1. Make a new world. (Doesn't seem to be effected by the starting season)
2. Wait for rain.
3. Run the game for a few months, and notice the weather, or lack thereof. 
Yes, I know this is a long timescale, but this is an issue about weather, which is on a long timescale. 

### Expected behavior

I would expect that we'd see a lot more weather like rain and snow, but it just does not seem to happen one bit. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: e6a647a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

### Additional context

I think it's related to this PR #34515. 
I've also seen other people complain about this, but you may have to hunt them down for their game versions.

**Comment by ZhilkinSerg** [comment]
You start a game in spring and expect to see snow in a few months? Did you try starting in winter? Do you see snow weather then?

> you can go months without seeing rain
But you still see it, right?

Did you try weather test in debug menu? (it outputs to `weather.output` in game folder)?

![image](https://user-images.githubusercontent.com/16213433/134762382-2b2580e7-c26a-451d-8d0c-b759036de14f.png)

**Comment by Paprika-H** [comment]
> You start a game in spring and expect to see snow in a few months? Did you try starting in winter? Do you see snow weather then?
> 
> > you can go months without seeing rain
> 
> But you still see it, right?
> 
> Did you try weather test in debug menu? (it outputs to `weather.output` in game folder)?
> 
> ![image](https://user-images.githubusercontent.com/16213433/134762382-2b2580e7-c26a-451d-8d0c-b759036de14f.png)

I started a game in winter, saw snow for the first time ever in game. And no, I don't see it even after months. I will check the test weather thing though, that's very helpful! Thank you
