### ISSUE TITLE
Weapon Categories

### ISSUE THREAD

**Issue by Termineitor244** [CleverRaven/Cataclysm-DDA#51867]
# Is your feature request related to a problem? Please describe.
Weapon categories are an useful concept made possible by #50212, every time there is a new implemented weapon, one needs to manually insert it in the weapon lists of the many martial arts there are, but with the categories, one would just need to add a category, and the martial arts would update themselves accordingly. This issue is mainly to organize the PRs I will be doing to make the martial arts actually use the feature.

# Weapon Categories guidelines:
1._ It should be re-usable by different martial arts if possible.
2._ It should include similar items.
3._ No weapon should remain in a weapon list, if the martial art has a theme, it can have categories for its weapons.

# List of weapon categories added until now:
| Weapon Category  | Martial Arts | Includes |
| ------------- | ------------- | ------------- |
| AUTOMATIC_RIFLES | Krav Maga  | All kind of automatic rifles  |
| AUTOMATIC_PISTOLS | Krav Maga  | All kind of automatic pistols  |
| KNIVES | Krav Maga, Ninjutsu, Eskrima, Silat  | All kind of knives  |
| BATONS | Krav Maga, Eskrima, Silat  | Batons, tonfas and weapons of similar shape  |
| MEDIUM_SWORDS  | Ninjutsu  | Swords of 81cm - 100cm length  |
| LONG_SWORDS | Ninjutsu  | Swords of 101cm length or more  |
| SHORT_SWORDS | Ninjutsu  | Swords of 80cm length or less  |
| QUARTERSTAVES | Ninjutsu, Silat, Bōjutsu  | Quarterstaves and similar weapons  |
| BLADED_FARMING | Ninjutsu, Eskrima, Silat  | Bladed farming tools and the machetes  |
| CLAWS | Ninjutsu, Eskrima, Bionic Combatives, Aikido, Judo  | Bionic and Tiger claws  |
| SHIVS  | Eskrima, Krav Maga  | Tiny, stabbing weapons like a glass shiv or monster's stings  |
| HOOKING_WEAPONRY | Fior Di Battaglia  | Long enough weapons with something to make a "Hook"  |
| POLEARMS  | Silat, Sōjutsu  | Polearms in general, including spears and the like  |
| FENCING_WEAPONRY  | Fencing  | The Foil, Épée, Sabre, and similar weapons like several batons  |
| BIONIC_WEAPONRY  | Bionic Combatives  | All kind of bionic installed weapons  |
| CONSTRUCTED_SWORDS  | Medieval Swordsmanship, Barbaran Montante  | All kind of custom build (generic) swords, like the nord  |
| MEDIEVAL_SWORDS | Medieval Swordsmanship  | All kind of medieval european build/themed swords  |
| JAPANESE_SWORDS  | Niten Ichi-Ryu  | All kind of Japanese specific swords (The katana and its variations)  |
| BIONIC_SWORDS  | Niten Ichi-Ryu  | All kind of bionic installed swords (?)  |
| FLAILS  | Barbaran Montante  | A mace with the a loose end attached by a string or chain ("war flail", "peasant flail")  |
| MACES  | Barbaran Montante  | A stick with a heavy, usually metal, ball on the end ("mace", "trench mace", "morningstar")  |
| GREAT_SWORDS  | Barbaran Montante  | Large and heavy swords with a cutting edge ("longsword", "zweihänder", "nodachi")  |
| GREAT_HAMMERS  | Barbaran Montante  | Two-handed hammers that aren't polearms ("sledge hammer", "heavy sledge hammer", "war hammer") |
| GREAT_AXES  | Barbaran Montante  | two-handed axes that aren't polearms ("battle axe", "fire axe") |

# Additional context
List of martial arts and their respective PRs:
Krav Maga: #51785 and #52615
Ninjutsu: #51868
Eskrima: #51918
Silat: #51972
Sōjutsu: #52579
Fior Di Battaglia:  #52671
Fencing: #52786 and #52839
Karate: Already done by Hymore246 in #52305
Bionic Combatives: #52885
Medieval Swordsmanship: Done by @catdach in #53449
Niten Ichi-Ryu: Done by @catdach in #53695
Barbaran Montante: Done by @catdach in #54758
Bōjutsu: Done at MA creation by @SantosValourion and reviewers in #50010, finished in #57008
Aikido and Judo: #57008

**_Extension of this project into the MMA mod:_**
#56105 by @catdach 

**_Related:_**
Display martial arts weapons by category: #52638 by @dseguin 
Allows translation of weapon categories: #52639 by @Saicchi 
Required weapon categories for buffs & techniques: #52788 by @dseguin 
Partial update of the MMA and Magiclysm mods for compatibility with already added categories: #55756 by @trip-flip 
And following fix of that update: #56082 by @TheShadowFerret 
Specific techniques for weapon categories: #56116 by @bombasticSlacks

**Comment by AcidAntOnAMinefield** [comment]
Would it be possible to have an unarmed category, as well as have them display for unarmed martial arts (such as Zui Quan)? 
Currently the only way to find out (that I know of) which weapons are considered "unarmed" is through the crafting menu, through filtering by description, which can take a long time before you are allowed to do anything else. The MAs that allow unarmed weapons have no list of which equipment is compatible with them, which is strange considering all other MAs have had some sort of "list" for a long time.

**Comment by Termineitor244** [comment]
> 
> 
> Would it be possible to have an unarmed category, as well as have them display for unarmed martial arts (such as Zui Quan)? Currently the only way to find out (that I know of) which weapons are considered "unarmed" is through the crafting menu, through filtering by description, which can take a long time before you are allowed to do anything else. The MAs that allow unarmed weapons have no list of which equipment is compatible with them, which is strange considering all other MAs have had some sort of "list" for a long time.

You can use this [link](https://nornagon.github.io/cdda-guide/#/json_flag/UNARMED_WEAPON) to see the current unarmed weapons (The weapons with the "UNARMED_WEAPON" flag), they only are the knuckles and the cestus, "none" is for no wielding, and the handcuffs are only there to allow you to use unarmed techniques after the robo police capture you.

It would be nice to have them displayed in the item menu, but they use a different code that weapons, if I add a weapon category, to say, Dragon Kung Fu, I would need to add `"melee_allowed": true,` to the style and techniques, and a style like Karate and Krav Maga, which use different techniques depending if you use a weapon or not, would use weapon techniques with the knuckles items...

One way to do what you want would be to just display the weapons with the flag in the martial art menu, like the weapon categories now, but a better idea that I just had...

To add an option for techniques and buffs of a style to work or not depending of the weapon category used by the current weapon, so, for example, you can have a unique technique that only triggers while using shorts swords, and a buff to critical chance while using knives, **all in the same style**.

I will open a new issue for this idea, this way, it would allow more diverse martial styles and to make a "Knuckles" category or something.

This will require C++ so lets hope someone likes the idea and helps implementing it.

**Comment by Maleclypse** [comment]
Are any more left to do on this?

**Comment by Termineitor244** [comment]
> Are any more left to do on this?

Weapon styles remaining are only 3, Barbaran, Medieval and Niten Ichi-Ryu, apart from those I want to turn the unarmed weapons into proper weapons, using the new restriction by categories to implement it, but I have been doing other things so I left it on the back burner for now.

After these styles I want to start with the MMA styles, so there is that.

**Comment by catdach** [comment]
@Termineitor244 if haven't already, you might want to take a look at #54313 and #41209, arguably anything that you can wear on your hands in now an unarmed weapon now, I think? (I'm not really sure how it all works at this point) #53939 may also be relevant. Depending on how it works, it may be unnecessary to deal with unarmed with weapon categories at all. Also, welcome back! 🥳

**Comment by Termineitor244** [comment]
Its what I have seen, I need to give it some tests (Maybe after the bug with unarmed wearable weapons is resolved) but I hope it works fine and is just some touch ups for any remaining weapon in the styles (No more style weapons! Only categories!). The new unarmed mechanics looks pretty great in paper, I can't wait to change my character into an unarmed master haha.
