### ISSUE TITLE
Hickory trees are not considered as valid target to "e"xamine when digging for roots.

### ISSUE THREAD

**Issue by Tamiore** [CleverRaven/Cataclysm-DDA#51889]
### Describe the bug

When trying to dig up some hickory roots, hickory trees are not considered as valid target to e"xamine.
You can still "overwrite" in by disabling "examine auto select" and forcing your charter to e"xamine a hickory tree (despite it not showing as a valid target to examine).

### Steps To Reproduce

Grab something with digging, try to "e"xamine a lone hickory tree with no nuts on it (with "examine auto select" enabled).

### Expected behavior

Hickory trees should be a valid thing to "e"xamine.

### Screenshots

![hickory](https://user-images.githubusercontent.com/61312205/134800212-649cf756-6b28-4e08-8afe-9848eccb87b6.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 9ec6ae1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Hope [no_hope],
    Rural-Only Mapgen [ruralbiome],
    Bionic Slots [cbm_slots]
]

### Additional context

This happened to me during winter, not 100% sure if season matters a lot.

**Comment by atealein** [comment]
Are these "hickory trees" or "dead hickory trees" ?

**Comment by Tamiore** [comment]
> 
> 
> Are these "hickory trees" or "dead hickory trees" ?
hickory trees

**Comment by MarlossCDDA** [comment]
Probably my fault, should be able to get a fix PR out today.
