### ISSUE TITLE
Autonote manager marks things you can not see yet

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#51883]
### Describe the bug

If you roam the map, there is a good chance, especially with low perception, that the autonote manager will mark extras for you which you can not see yet.

### Steps To Reproduce

1. Roam the map with autonote manager enabled
2. Frequently open the map (this is important)
3. Encounter an extra which the autonote manager marks before you can even see it

### Expected behavior

The autonote manager should not mark things that you can not see on the overmap. Alternatively, do not mark any map extras which you can not see. If you e.g explore at night, you can still be warned of dangers before you can even see them.

### Screenshots

![image](https://user-images.githubusercontent.com/59517351/134786484-abe052f2-65aa-4b37-9d95-e478621dd1f6.png)

See the top right. My character can not see to this spot in the map but the autonote manager marked it.

### Versions and configuration

experimental

**Comment by atealein** [comment]
I can add something extra to that - if you end up waking in the subways for long time, outside of the area where you would have gone on the surface - the autonotes will mark things on the surface layer for the areas where you haven't been yet.
