### ISSUE TITLE
Warn player when attacking with a slow item

### ISSUE THREAD

**Issue by brassmaster2357** [CleverRaven/Cataclysm-DDA#51894]
# Problem
I just lost a character by accidentally attacking with a mattress that  I was bringing back to the evac shelter to make a bed there.

# Suggestion
I would definitely appreciate a sort of feature that warns the player when they're about to attack with something with a very high move cost (something around 400 or more, or double/triple their speed) with some sort of dialogue message, maybe like this:
┍─────────────────────────────────────────────────────────┐
┃Your current weapon (_weapon here_) has a high move cost (_cost here_)! Confirm attack? (Y/N) ┃
┃_______________________________________________________________________________(Y)es (N)o________┃ 

I'm fine if something like this isn't added. There also might already be a feature like this that I haven't seen, so if that's the case, make sure to tell me where/how to use it! Thanks in advance.

**Comment by kwl01skz** [comment]
I'm not sure how to, but I'm sure I triggered this warning.

**Comment by anothersimulacrum** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/36704

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
