### ISSUE TITLE
Use SD cards to back up E-ink books

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#51905]
# Is your feature request related to a problem? Please describe.
I've been making extensive use of the book scanning feature of the E-ink reader, but two times now I've ended up taking an unintended dip in a river, lost access to my library, and found myself annoyed that there's no way to transfer or back up the files, something which would be easy to do in real life.

# Describe the solution you'd like
Allow E-ink readers to write a backup of all currently contained books to an SD card, and allow other E-ink readers to load in books from that card.

# Describe alternatives you've considered
Direct transfer between tablets and/or the ability to salvage the memory of a broken tablet, but this seems like the cleaner solution.
Could also just accept that this is the price you pay for getting to carry an entire library in your backpack, but it feels really weird that you're completely unable to do backups or transfer files. This system also allows you to create copies of your library for other purposes, e.g. handing them out to the entire party for use with the new ability to take control of NPCs.

**Comment by atealein** [comment]
I opened a similar issue a bit back: https://github.com/CleverRaven/Cataclysm-DDA/issues/51640

**Comment by Terrorforge** [comment]
> I opened a similar issue a bit back: #51640
Ah, then this one is unnecessary. I'll just close it.
