### ISSUE TITLE
Weakpoints: Monster Defenses

### ISSUE THREAD

**Issue by Joshua-Chin** [CleverRaven/Cataclysm-DDA#51915]
# Goal

Monster should be able to defend their weak points. For example, a zombie bio-operator might raise its hands to protect its eyes, or a turtle might retract it head into its shell.

The purpose of this discussion is to determine a formula and set of variables for determining a monster's weak point defenses. This formula should include the weapon type (e.g. spear, sledge hammer, sword).

# Proposals

## Formulas

The monsters defenses operate on individual weak points, modifying their base hit chance. Currently, the base hit chance is simply equal to the `coverage`. In this proposal, the monsters defenses should output a multiplier in the range `[0, 1]` that will be applied to the base `coverage`. (Note that the defensive multiplier should be applied *before* skill based reweighing)

```
base_hit_chance = f(defenses) * coverage
```

In terms of possible values of `f`, I can think of two classes: constant and gating. 

### Constant
```
base_hit_chance = coverage_mult * coverage
```

A constant function `f` would return a constant `C` in the range `[0, 1]`. The benefits of this approach is simplicity and interpretability. This works well for unavoidable defenses, such as ranged attacks against a turtle hiding its shell.

### Gating

```
base_hit_chance = erf((skill - difficulty) / c) * coverage
```

A gating function returns the probability of a normally distributed roll centered on `skill` exceeds `difficulty`. The `skill` parameter is the attacker's effective skill, and the `difficulty` is weak point provided value. The standard deviation of the roll is a fixed constant. This approach works well for defenses that can be mitigated through skill, like a melee attack against a zombie bio-operator trying to protect its head.

## Weapon Classes
The formula should allow contributors to specify independent values for different types of weapons. I suggest the following 4 mutually exclusive classes, based on damage types:

- Melee Stab: weapons like spears and polearms
- Melee Cut: weapons like swords and knives
- Melee Bash: weapons like clubs and hammers
- Ranged: projectiles and thrown items

For convenience, we would also support a `Melee` and `All` fields as shorthand.

**Comment by PatrikLundell** [comment]
My understanding of the zombie lore is that zombies do not have any sense of self preservation, and so wouldn't engage in any protective behavior. The exception is when the character that later became zombiefied was so highly trained that behaviors became reflexes (such as for the bio operator zombie). Ferals ought to be allowed more of a defensive capability (although still a deficient one), while mutated animals presumably would retain animal intelligence and roughly the same behavior.

Also note that zombie wrestlers typically result from zombie evolution rather than the zombiefication of a showman who engaged in "wrestling", and so wouldn't have any trained reflexes to rely on.

**Comment by Joshua-Chin** [comment]
You're right that most zombies will have minimal defensive capabilities. In the examples, I replaced zombie wrestlers with zombie bio-operators. For now, I'd prefer to focus on determining the actual formula. Once that's decided, it'll be easier to discuss the actual values.

**Comment by Joshua-Chin** [comment]
@I-am-Erk Please take a look when you have a chance. This should let contributors specify a weak point's `difficulty`, or an equivalent parameter. Thanks!

**Comment by I-am-Erk** [comment]
I don't have much to add to this, it looks about right. There might be some value to also permitting weapons to be split into `point` (melee_stab and ranged) or `broad` (melee_slashing and melee_blunt)
