### ISSUE TITLE
Some items silently defined twice within the same mod

### ISSUE THREAD

**Issue by anothersimulacrum** [CleverRaven/Cataclysm-DDA#51926]
### Describe the bug

The game silently lets duplicate item definitions exist within the same mod, leading to potential confusion when updating an item does not update the stats as the item is later overwritten.

### Steps To Reproduce

Here are two examples. There may be more.
https://github.com/CleverRaven/Cataclysm-DDA/blob/2245d732366b065552373ad9282b340051cc650e/data/mods/Aftershock/items/inactiverobot.json#L26-L27
https://github.com/CleverRaven/Cataclysm-DDA/blob/2245d732366b065552373ad9282b340051cc650e/data/mods/Aftershock/items/inactiverobot.json#L76-L78

https://github.com/CleverRaven/Cataclysm-DDA/blob/2245d732366b065552373ad9282b340051cc650e/data/mods/CRT_EXPANSION/items/crt_armor.json#L138-L140
https://github.com/CleverRaven/Cataclysm-DDA/blob/2245d732366b065552373ad9282b340051cc650e/data/mods/CRT_EXPANSION/items/crt_clothes.json#L88-L90

### Expected behavior

The game complains when an item is defined twice within the same mod.

### Versions and configuration

https://github.com/CleverRaven/Cataclysm-DDA/commit/2245d732366b065552373ad9282b340051cc650e

**Comment by PatrikLundell** [comment]
I would go one step further and have the game complain whenever any JSON definition is defined twice, not just items.

**Comment by anothersimulacrum** [comment]
Yeah, items are just the thing I was writing the tool that accidentally found these was looking at.
