### ISSUE TITLE
Automatic testing fails automatically. Weakpoints or the testing of it is buggy.

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#51925]
### Describe the bug

PR #51902 fails due to errors in master or tests thereof.

(~[slow] ~[.])=> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
(~[slow] ~[.])=> cata_test is a Catch v2.13.7 host application.
(~[slow] ~[.])=> Run with -? for options
(~[slow] ~[.])=> 
(~[slow] ~[.])=> Randomness seeded to: 1632743887
(~[slow] ~[.])=> 
(~[slow] ~[.])=> -------------------------------------------------------------------------------
(~[slow] ~[.])=> monster_weakpoint
(~[slow] ~[.])=> -------------------------------------------------------------------------------
(~[slow] ~[.])=> ../tests/weakpoint_test.cpp:66
(~[slow] ~[.])=> ...............................................................................
(~[slow] ~[.])=> 
(~[slow] ~[.])=> ../tests/weakpoint_test.cpp:81: FAILED:
(~[slow] ~[.])=>   CHECK( wr2.PercHits( "the knee" ) == Approx( 0.25f ).epsilon( 0.20f ) )
(~[slow] ~[.])=> with expansion:
Error: (~[slow] ~[.])=>   0.301f == Approx( 0.25 )

### Steps To Reproduce

Make a PR.
Keep trying until testing RNGs fails.

### Expected behavior

Automatic testing should be squeaky clean.

### Versions and configuration

Whatever was in master at the time the automatic tests were run.

**Comment by Joshua-Chin** [comment]
This failure seems to be within expectation. Each test case roughly has a 0.03% flake rate. There are 3 tests cases and 8 runs per pull request, leading to a ~0.71% flake rate per pull request run. Given 100 runs, there's a ~50% chance of a failure (0.71 failures in expectation). This is a similar flake rate as other randomized tests, like the ranged weapons balance test.

**Comment by PatrikLundell** [comment]
So how are victims of it expected to deal with it?

Past experience indicates that any PR that doesn't succeed in running the gauntlet of "flake tests" of a hundred different tests are completely ignored until the victim somehow triggers retests again and again (there seemed to be about a 90% failure rate in the December-January period).

**Comment by Joshua-Chin** [comment]
Closing this issues because the weak point implementation and test are working as expected. If you want to discuss tests for inherently random functions, consider opening a separate issue.
