### ISSUE TITLE
Automated testing fails on mutable lab specials placement

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#51923]
### Describe the bug

PR #51920 fails due to unrelated tests. Looks like either there's a bug in the logic for mutable lab part placement or the tests for it are faulty.

(~[slow] ~[.])=> 11:19:59.846 INFO : Randomness seeded to: 1632741002
(~[slow] ~[.])=> 11:19:59.846 INFO : Treating result as failure due to error logged during tests.
(~[slow] ~[.])=> test exited with code 1
([slow] ~crafting_skill_gain)=> 
([slow] ~crafting_skill_gain)=> 11:10:02.509 INFO : Randomness seeded to: 1632741002
([slow] ~crafting_skill_gain)=> 11:10:02.510 WARNING : opendir [test_user_dir_2/sound/] failed with "No such file or directory".
([slow] ~crafting_skill_gain)=> 11:10:02.514 WARNING : opendir [test_user_dir_2/gfx/] failed with "No such file or directory".
([slow] ~crafting_skill_gain)=> 11:10:02.516 WARNING : opendir [test_user_dir_2/gfx/] failed with "No such file or directory".
([slow] ~crafting_skill_gain)=> 11:10:02.518 INFO : [options] C locale set to C
([slow] ~crafting_skill_gain)=> 11:10:02.518 INFO : [options] C++ locale set to C
([slow] ~crafting_skill_gain)=> 11:10:02.567 WARNING : opendir [test_user_dir_2/mods/] failed with "No such file or directory".
([slow] ~crafting_skill_gain)=> 11:10:21.802 WARNING : opendir [test_user_dir_2/save/Test World 13119/mods] failed with "No such file or directory".
([slow] ~crafting_skill_gain)=> 11:12:33.742 INFO : Starting the actual test at Mon Sep 27 11:12:33 2021
([slow] ~crafting_skill_gain)=> Filters: [slow] ~crafting_skill_gain
([slow] ~crafting_skill_gain)=> 3.512 s: grenade_lethality
([slow] ~crafting_skill_gain)=> 584.929 s: starting_items
([slow] ~crafting_skill_gain)=> 
([slow] ~crafting_skill_gain)=> 11:22:28.403 ERROR : (error message will follow backtrace)
([slow] ~crafting_skill_gain)=>     /lib/x86_64-linux-gnu/libasan.so.6(+0x45c5e) [0x7f9bddbd6c5e]
([slow] ~crafting_skill_gain)=>     ./tests/cata_test(debug_write_backtrace(std::ostream&)+0x4e1) [0x55e93dcd0d91]
([slow] ~crafting_skill_gain)=>     ./tests/cata_test(DebugLog(DebugLevel, DebugClass)+0x2f2) [0x55e93dcd3c25]
([slow] ~crafting_skill_gain)=>     ./tests/cata_test(realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x3b0) [0x55e93dcd418e]
([slow] ~crafting_skill_gain)=>     ./tests/cata_test(void realDebugmsg<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)+0x274) [0x55e93f532d6e]
([slow] ~crafting_skill_gain)=>     ./tests/cata_test(mutable_overmap_special_data::place(overmap&, coords::coord_point<tripoint, (coords::origin)4, (coords::scale)2> const&) const+0x1ea7) [0x55e93f5666dd]
([slow] ~crafting_skill_gain)=>     ./tests/cata_test(overmap::place_special(overmap_special const&, coords::coord_point<tripoint, (coords::origin)4, (coords::scale)2> const&, om_direction::type, city const&, bool, bool)+0x14a4) [0x55e93f4d5e90]
([slow] ~crafting_skill_gain)=>     ./tests/cata_test(overmap::place_special_attempt(overmap_special_batch&, coords::coord_point<point, (coords::origin)4, (coords::scale)2> const&, int, bool, bool)+0x4c4) [0x55e93f4d9910]
([slow] ~crafting_skill_gain)=>     ./tests/cata_test(overmap::place_specials_pass(overmap_special_batch&, om_special_sectors&, bool, bool)+0x21e) [0x55e93f4d9c66]
([slow] ~crafting_skill_gain)=>     ./tests/cata_test(overmap::place_specials(overmap_special_batch&)+0x177d) [0x55e93f4db539]
([slow] ~crafting_skill_gain)=>     ./tests/cata_test(overmap::generate(overmap const*, overmap const*, overmap const*, overmap const*, overmap_special_batch&)+0x177) [0x55e93f4dbf8d]
([slow] ~crafting_skill_gain)=>     ./tests/cata_test(overmap::open(overmap_special_batch&)+0xb31) [0x55e93f4dcb7b]
([slow] ~crafting_skill_gain)=>     ./tests/cata_test(overmap::populate(overmap_special_batch&)+0xa3) [0x55e93f4dce51]
([slow] ~crafting_skill_gain)=>     ./tests/cata_test(overmapbuffer::create_custom_overmap(coords::coord_point<point, (coords::origin)1, (coords::scale)4> const&, overmap_special_batch&)+0x2ba) [0x55e93f5e6214]
([slow] ~crafting_skill_gain)=>     ./tests/cata_test(overmap::place_specials(overmap_special_batch&)+0x15fe) [0x55e93f4db3ba]
([slow] ~crafting_skill_gain)=>     ./tests/cata_test(overmap::generate(overmap const*, overmap const*, overmap const*, overmap const*, overmap_special_batch&)+0x177) [0x55e93f4dbf8d]
([slow] ~crafting_skill_gain)=>     ./tests/cata_test(overmap::open(overmap_special_batch&)+0xb31) [0x55e93f4dcb7b]
([slow] ~crafting_skill_gain)=>     ./tests/cata_test(overmap::populate(overmap_special_batch&)+0xa3) [0x55e93f4dce51]
([slow] ~crafting_skill_gain)=>     ./tests/cata_test(overmapbuffer::create_custom_overmap(coords::coord_point<point, (coords::origin)1, (coords::scale)4> const&, overmap_special_batch&)+0x2ba) [0x55e93f5e6214]
([slow] ~crafting_skill_gain)=>     ./tests/cata_test(overmap::place_specials(overmap_special_batch&)+0x15fe) [0x55e93f4db3ba]
([slow] ~crafting_skill_gain)=> 
([slow] ~crafting_skill_gain)=>     Attempting to repeat stack trace using debug symbols…
([slow] ~crafting_skill_gain)=>     ??
([slow] ~crafting_skill_gain)=>     ??:0
([slow] ~crafting_skill_gain)=>     debug_write_backtrace(std::ostream&)
([slow] ~crafting_skill_gain)=>     ??:?
([slow] ~crafting_skill_gain)=>     DebugLog(DebugLevel, DebugClass)
([slow] ~crafting_skill_gain)=>     ??:?
([slow] ~crafting_skill_gain)=>     realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
([slow] ~crafting_skill_gain)=>     ??:?
([slow] ~crafting_skill_gain)=>     void realDebugmsg<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)
([slow] ~crafting_skill_gain)=>     ??:?
([slow] ~crafting_skill_gain)=>     mutable_overmap_special_data::place(overmap&, coords::coord_point<tripoint, (coords::origin)4, (coords::scale)2> const&) const
([slow] ~crafting_skill_gain)=>     ??:?
([slow] ~crafting_skill_gain)=>     overmap::place_special(overmap_special const&, coords::coord_point<tripoint, (coords::origin)4, (coords::scale)2> const&, om_direction::type, city const&, bool, bool)
([slow] ~crafting_skill_gain)=>     ??:?
([slow] ~crafting_skill_gain)=>     overmap::place_special_attempt(overmap_special_batch&, coords::coord_point<point, (coords::origin)4, (coords::scale)2> const&, int, bool, bool)
([slow] ~crafting_skill_gain)=>     ??:?
([slow] ~crafting_skill_gain)=>     overmap::place_specials_pass(overmap_special_batch&, om_special_sectors&, bool, bool)
([slow] ~crafting_skill_gain)=>     ??:?
([slow] ~crafting_skill_gain)=>     overmap::place_specials(overmap_special_batch&)
([slow] ~crafting_skill_gain)=>     ??:?
([slow] ~crafting_skill_gain)=>     overmap::generate(overmap const*, overmap const*, overmap const*, overmap const*, overmap_special_batch&)
([slow] ~crafting_skill_gain)=>     ??:?
([slow] ~crafting_skill_gain)=>     overmap::open(overmap_special_batch&)
([slow] ~crafting_skill_gain)=>     ??:?
([slow] ~crafting_skill_gain)=>     overmap::populate(overmap_special_batch&)
([slow] ~crafting_skill_gain)=>     ??:?
([slow] ~crafting_skill_gain)=>     overmapbuffer::create_custom_overmap(coords::coord_point<point, (coords::origin)1, (coords::scale)4> const&, overmap_special_batch&)
([slow] ~crafting_skill_gain)=>     ??:?
([slow] ~crafting_skill_gain)=>     overmap::place_specials(overmap_special_batch&)
([slow] ~crafting_skill_gain)=>     ??:?
([slow] ~crafting_skill_gain)=>     overmap::generate(overmap const*, overmap const*, overmap const*, overmap const*, overmap_special_batch&)
([slow] ~crafting_skill_gain)=>     ??:?
([slow] ~crafting_skill_gain)=>     overmap::open(overmap_special_batch&)
([slow] ~crafting_skill_gain)=>     ??:?
([slow] ~crafting_skill_gain)=>     overmap::populate(overmap_special_batch&)
([slow] ~crafting_skill_gain)=>     ??:?
([slow] ~crafting_skill_gain)=>     overmapbuffer::create_custom_overmap(coords::coord_point<point, (coords::origin)1, (coords::scale)4> const&, overmap_special_batch&)
([slow] ~crafting_skill_gain)=>     ??:?
([slow] ~crafting_skill_gain)=>     overmap::place_specials(overmap_special_batch&)
([slow] ~crafting_skill_gain)=>     ??:?
([slow] ~crafting_skill_gain)=> Backtrace emission took 1 seconds.
([slow] ~crafting_skill_gain)=> (continued from above) ERROR : src/overmap.cpp:1826 [std::vector<coords::coord_point<tripoint, coords::origin::overmap, coords::scale::overmap_terrain> > mutable_overmap_special_data::place(overmap&, const tripoint_om_omt&) const] Spawn of mutable special microlab_mutable had unresolved joins.  Existing terrain at (38,36,-2) was empty_rock; joins were south: hallway_to_hallway and west: hallway_to_hallway

### Steps To Reproduce

Make a PR for anything.
Repeat until test RNGs generate the error.

### Expected behavior

Automated tests shouldn't reject PRs due to unrelated bugs in accepted code and, especially, in tests. If successful passing of automated tests is mandatory for PRs to be looked at, keeping tests completely clean should be the top priority, with tests either fixed immediately when errors are detected, or immediately suspended until fixed.

### Versions and configuration

Whatever was in master at the time the automated tests were run.

**Comment by Maleclypse** [comment]
I think this particular issue has been fixed though we do have some tests failing now but they aren't related to this placement.  Please reopen if I'm mistaken.
