### ISSUE TITLE
Automatic testing fails to move character?

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#51921]
### Describe the bug

Basic Build and Test (GCC 9, Curses, LTO) fails for #51920 (JSON addition only PR). Presumably due to test cases encountering RNGs they can't handle:

(~[slow] ~[.])=> 0.936 s: place_player_can_safely_move_multiple_submaps
(~[slow] ~[.])=> 
(~[slow] ~[.])=> 09:42:35.089 ERROR : (error message will follow backtrace)
(~[slow] ~[.])=>     ./tests/cata_test(debug_write_backtrace(std::ostream&)+0x3e) [0x562ceda085e7]
(~[slow] ~[.])=>     ./tests/cata_test(DebugLog(DebugLevel, DebugClass)+0x1c8) [0x562ceda0997c]
(~[slow] ~[.])=>     ./tests/cata_test(realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x17b) [0x562ceda0b330]
(~[slow] ~[.])=>     ./tests/cata_test(overmap::place_special(overmap_special const&, coords::coord_point<tripoint, (coords::origin)4, (coords::scale)2> const&, om_direction::type, city const&, bool, bool)+0x2636) [0x562ced559680]
(~[slow] ~[.])=>     ./tests/cata_test(overmap::place_special_attempt(overmap_special_batch&, coords::coord_point<point, (coords::origin)4, (coords::scale)2> const&, int, bool, bool)+0x228) [0x562ced55a2e2]
(~[slow] ~[.])=>     ./tests/cata_test(overmap::place_specials_pass(overmap_special_batch&, om_special_sectors&, bool, bool)+0x60) [0x562ced55a39c]
(~[slow] ~[.])=>     ./tests/cata_test(overmap::place_specials(overmap_special_batch&)+0x46b) [0x562ced55a841]
(~[slow] ~[.])=>     ./tests/cata_test(overmap::generate(overmap const*, overmap const*, overmap const*, overmap const*, overmap_special_batch&)+0x156) [0x562ced55b5ee]
(~[slow] ~[.])=>     ./tests/cata_test(overmap::open(overmap_special_batch&)+0x222) [0x562ced55b8c2]
(~[slow] ~[.])=>     ./tests/cata_test(overmap::populate(overmap_special_batch&)+0x24) [0x562ced55b980]
(~[slow] ~[.])=>     ./tests/cata_test(overmap::populate()+0xe1) [0x562ced56038b]
(~[slow] ~[.])=>     ./tests/cata_test(overmapbuffer::get(coords::coord_point<point, (coords::origin)1, (coords::scale)4> const&)+0xb6) [0x562ced5369d4]
(~[slow] ~[.])=>     ./tests/cata_test(overmapbuffer::get_om_global(coords::coord_point<tripoint, (coords::origin)1, (coords::scale)2> const&)+0x94) [0x562ced536e16]
(~[slow] ~[.])=>     ./tests/cata_test(overmapbuffer::check_ot(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ot_match_type, coords::coord_point<tripoint, (coords::origin)1, (coords::scale)2> const&)+0x32) [0x562ced536ed6]
(~[slow] ~[.])=>     ./tests/cata_test(overmapbuffer::is_findable_location(coords::coord_point<tripoint, (coords::origin)1, (coords::scale)2> const&, omt_find_params const&)+0x5e) [0x562ced53a4c8]
(~[slow] ~[.])=>     ./tests/cata_test(overmapbuffer::find_all(coords::coord_point<tripoint, (coords::origin)1, (coords::scale)2> const&, omt_find_params const&)+0x7b) [0x562ced53a5d1]
(~[slow] ~[.])=>     ./tests/cata_test(+0x10830ee) [0x562cedd5c0ee]
(~[slow] ~[.])=>     ./tests/cata_test(Catch::RunContext::invokeActiveTestCase()+0x52) [0x562cedbc21b6]
(~[slow] ~[.])=>     ./tests/cata_test(Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)+0x14a) [0x562cedbd1a64]
(~[slow] ~[.])=>     ./tests/cata_test(Catch::RunContext::runTest(Catch::TestCase const&)+0x15c) [0x562cedbd8d4a]
(~[slow] ~[.])=> 
(~[slow] ~[.])=>     Attempting to repeat stack trace using debug symbols…
(~[slow] ~[.])=>     debug_write_backtrace(std::ostream&)
(~[slow] ~[.])=>     ??:?
(~[slow] ~[.])=>     DebugLog(DebugLevel, DebugClass)
(~[slow] ~[.])=>     ??:?
(~[slow] ~[.])=>     realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
(~[slow] ~[.])=>     ??:?
(~[slow] ~[.])=>     overmap::place_special(overmap_special const&, coords::coord_point<tripoint, (coords::origin)4, (coords::scale)2> const&, om_direction::type, city const&, bool, bool)
(~[slow] ~[.])=>     ??:?
(~[slow] ~[.])=>     overmap::place_special_attempt(overmap_special_batch&, coords::coord_point<point, (coords::origin)4, (coords::scale)2> const&, int, bool, bool)
(~[slow] ~[.])=>     ??:?
(~[slow] ~[.])=>     overmap::place_specials_pass(overmap_special_batch&, om_special_sectors&, bool, bool)
(~[slow] ~[.])=>     ??:?
(~[slow] ~[.])=>     overmap::place_specials(overmap_special_batch&)
(~[slow] ~[.])=>     ??:?
(~[slow] ~[.])=>     overmap::generate(overmap const*, overmap const*, overmap const*, overmap const*, overmap_special_batch&)
(~[slow] ~[.])=>     ??:?
(~[slow] ~[.])=>     overmap::open(overmap_special_batch&)
(~[slow] ~[.])=>     ??:?
(~[slow] ~[.])=>     overmap::populate(overmap_special_batch&)
(~[slow] ~[.])=>     ??:?
(~[slow] ~[.])=>     overmap::populate()
(~[slow] ~[.])=>     ??:?
(~[slow] ~[.])=>     overmapbuffer::get(coords::coord_point<point, (coords::origin)1, (coords::scale)4> const&)
(~[slow] ~[.])=>     ??:?
(~[slow] ~[.])=>     overmapbuffer::get_om_global(coords::coord_point<tripoint, (coords::origin)1, (coords::scale)2> const&)
(~[slow] ~[.])=>     ??:?
(~[slow] ~[.])=>     overmapbuffer::check_ot(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ot_match_type, coords::coord_point<tripoint, (coords::origin)1, (coords::scale)2> const&)
(~[slow] ~[.])=>     ??:?
(~[slow] ~[.])=>     overmapbuffer::is_findable_location(coords::coord_point<tripoint, (coords::origin)1, (coords::scale)2> const&, omt_find_params const&)
(~[slow] ~[.])=>     ??:?
(~[slow] ~[.])=>     overmapbuffer::find_all(coords::coord_point<tripoint, (coords::origin)1, (coords::scale)2> const&, omt_find_params const&)
(~[slow] ~[.])=>     ??:?
(~[slow] ~[.])=>     ____C_A_T_C_H____T_E_S_T____0() [clone .lto_priv.53]
(~[slow] ~[.])=>     <artificial>:?
(~[slow] ~[.])=>     Catch::RunContext::invokeActiveTestCase()
(~[slow] ~[.])=>     ??:?
(~[slow] ~[.])=>     Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)
(~[slow] ~[.])=>     ??:?
(~[slow] ~[.])=>     Catch::RunContext::runTest(Catch::TestCase const&)
(~[slow] ~[.])=>     ??:?
(~[slow] ~[.])=> Backtrace emission took 0 seconds.
(~[slow] ~[.])=> (continued from above) ERROR : src/overmap.cpp:1826 [std::vector<coords::coord_point<tripoint, coords::origin::overmap, coords::scale::overmap_terrain> > mutable_overmap_special_data::place(overmap&, const tripoint_om_omt&) const] Spawn of mutable special microlab_mutable had unresolved joins.  Existing terrain at (152,41,-2) was empty_rock; joins were north: hallway_to_hallway and west: hallway_to_hallway

### Steps To Reproduce

Make a PR.
Trigger compilation/testing until the RNGs cause testing to fail.

### Expected behavior

Tests should be kept in perfect condition or suspended until fixed.

### Versions and configuration

Whatever Master contained at the time the tests failed, less than ½ hours before this bug report was written.

**Comment by PatrikLundell** [comment]
This faulty test also kills #51922.

**Comment by hexagonrecursion** [comment]
I get an error "Error: We are currently unable to download the log. Please try again later" when I try to view the logs for the two PRs you have linked. IMHO this should be closed unless someone has ran into the same issue more recently.

**Comment by hexagonrecursion** [comment]
@wapcaplet I think this should be closed unless someone has ran into the same issue more recently.

**Comment by wapcaplet** [comment]
Agreed.
