### ISSUE TITLE
Allow to start sourdough in other vessels than just a glass jar

### ISSUE THREAD

**Issue by DanielVartanov** [CleverRaven/Cataclysm-DDA#51964]
# Is your feature request related to a problem? Please describe.
I felt it clearly when I was temporarily cut out of towns for the course of the entire winter and had to rely on crafting a lot. With clay canisters, I can do a lot, including molotov's, but I can't start a sourdough? Currently, it allows using only glass jars, which is unreasonably limiting.

# Describe the solution you'd like
Allow clay canister to be used for starting a sourdough, assuming it has a lid. It does not have to be hermetically sealed, after all.

# Describe alternatives you've considered
Assume any vessel can be reasonably sealed with anything at hand. E.g. even a bowl can be reasonably sealed with a thick cloth.

# A question on implementation
It seems to be easy to do, just replace `[ "jar_glass_sealed", 1 ]` with more options, but the biggest problem is the ability to [uncraft a sourdough](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/uncraft/food/sourdough.json). I'd love to implement the feature myself, but how do I deal with uncrafting?

**Comment by Kribylet** [comment]
In 0F I've seen items like the grappling hook list the components it was made out of. I'm not super familiar with the code, but if the crafting process tracks what things are made out of it seems reasonable that you could either look that up during normal disassembly or add a special action to the sourdough item that returns the base item. Since sourdough starters change into different things repeatedly it might take some doing to keep things consistent, though.

**Comment by Maleclypse** [comment]
The problem is that it converts every item into sourdough in a glass jar.  We don't currently have the ability to define multiple possible outcomes from a single recipe.  You'd really want to create new recipes that have a sourdough outcome contained in whatever input container was used.

**Comment by rubenpd** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/issues/51174
this might be related if anyone wants to expand recipes with transforming outcomes

**Comment by DanielVartanov** [comment]
@rubenpd https://github.com/CleverRaven/Cataclysm-DDA/pull/56324 makes the issue you mentioned irrelevant/solved, as well as the issue we are commenting to
