### ISSUE TITLE
Can't compile on MacOS "mixed implicit and static pattern rules"

### ISSUE THREAD

**Issue by Ivan-Shestakov** [CleverRaven/Cataclysm-DDA#51968]
### Describe the bug

When compiling the game from latest sources, getting this error:
Makefile:1193: *** mixed implicit and static pattern rules.  Stop.

### Steps To Reproduce

1. Checkout latest game source on MacOS(11.5.2) with GCC (Homebrew GCC 11.2.0).
2. Attempt to compile using `make -j 8 RELEASE=1 TILES=1 LOCALIZE=0 SOUND=1 CLANG=0 ASTYLE=0 RUNTESTS=0`
3. Error message is displayed instantly:
`Makefile:1193: *** mixed implicit and static pattern rules.  Stop.`

Same command and config worked before Sep-20. 

### Expected behavior

This setup worked fine for several months - I'd update my game almost every gaming session. 

### Versions and configuration

- OS: MacOS BigSur 11.5.2
- Compiler: Homebrew GCC 11.2.0
- Tiles version
- Last working version (for me, found by `git log Makefile`) - ff4db050877c4cdcb9ae2e5b247eb4f70c1d3eb4
 the breaking commit seems to be 81960cdb39686b1c119eaf04d8724a348f547c1d

**Comment by BrettDong** [comment]
Does it help if you add `LINTJSON=0`?

**Comment by Ivan-Shestakov** [comment]
No, the error stays the same

**Comment by BrettDong** [comment]
What's the version of your make program (`make -v`)?

I can't reproduce the error on macOS 11.6.

**Comment by Ivan-Shestakov** [comment]
make -v                                                                                                                                                                          master~/code/Cataclysm-DDA
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0

**Comment by Ivan-Shestakov** [comment]
The problem resolved after installing GNU make 4.3 via `brew install make`, and running the build as `gmake -j 8 RELEASE=1 TILES=1 LOCALIZE=0 SOUND=1 CLANG=0 ASTYLE=0 RUNTESTS=0` - it still took a lot of time to lint all json.
