### ISSUE TITLE
Crash then save corruption??

### ISSUE THREAD

**Issue by LeahLuong** [CleverRaven/Cataclysm-DDA#51977]
### Describe the bug

Booted to desktop during game & getting a crash report when failing to reload. Crash may have happened during auto-save attempt.

### Steps To Reproduce

Unknown steps to reproduce.

### Expected behavior

Game has always reloaded following previous crashes. Current game was a couple of weeks in progress.

### Versions and configuration

 DEBUG    : Error: Json error: storage/emulated/0/Android/data/com.cleverraven.cataclysmdda/files/data/json/mapgen/basecamps/modular_shelter_2/modular_shelter_2_common.json:270:13: missing comma

  {
    "type": "mapgen",
    "method"�          ^
             w
Pυ򇪓핖Ns\ested_mapgen_餢: "fbmc_shelter_��~[D�QFv2m��HZ蘈FꈗVCA̘ZO踑ܸʡ9gڊG୯X#̰Կٔ+e렛柖Ѩޏ΀!      "b #,

 FUNCTION : bool main_menu::load_character_tab(bool)
 FILE     : /var/lib/jenkins/workspace/Cataclysm-Android/android/app/jni/src/../../../../src/main_menu.cpp
 LINE     : 1150
 VERSION  : 0.F-2

### Additional context

IDK how to do these things on my device. HELP!

**Comment by BrettDong** [comment]
Save data is corrupted. Do you have crash report in config/crash.log?

**Comment by LeahLuong** [comment]
I did a search for "crash.log" using my phone's File Manager & nothing came up. I've seen crash logs come up before but not during this incident; I was playing the game & it unceremoniously dropped me out. I posted what I have above after attempting to reload. Digging around the debug.log I may have found the crash.log:

Starting log.
15:19:45.076 INFO : Cataclysm DDA version 0.F-2
15:19:45.078 INFO : [main] C locale set to C
15:19:45.078 INFO : [main] C++ locale set to 
15:19:45.078 INFO : SDL version used during compile is 2.0.12
15:19:45.078 INFO : SDL version used during linking and in runtime is 2.0.12
15:19:45.419 INFO : [options] C locale set to C
15:19:45.419 INFO : [options] C++ locale set to 
15:19:45.419 INFO : Read Android system language: 'en_US'
15:19:45.419 INFO : Setting language to: 'en'
15:19:45.419 INFO : Language is set to: 'en'
15:19:45.421 INFO : Read Android system language: 'en_US'
15:19:46.878 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
15:19:47.156 INFO : Read Android system language: 'en_US'
15:19:47.156 INFO : Setting language to: 'en'
15:19:47.156 INFO : Language is set to: 'en'
15:19:47.161 INFO : Read Android system language: 'en_US'
15:19:48.980 WARNING : opendir [/storage/emulated/0/Android/data/com.cleverraven.cataclysmdda/files/mods/] failed with "No such file or directory".
15:19:49.313 INFO : Read Android system language: 'en_US'
15:19:49.395 INFO : Read Android system language: 'en_US'
15:19:49.398 INFO : Read Android system language: 'en_US'
15:19:49.400 INFO : Read Android system language: 'en_US'
15:20:32.395 ERROR : (error message will follow backtrace)#01: 0xa1825aa4 DebugLog(DebugLevel, DebugClass)
#02: 0xa1825650 realDebugmsg(char const*, char const*, char const*, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)
#03: 0xa162a614 void realDebugmsg<char const*>(char const*, char const*, char const*, char const*, char const*&&)
#04: 0xa1b5bf7c main_menu::load_character_tab(bool)
#05: 0xa1b59bba main_menu::opening_screen()
#06: 0xa1b55390 SDL_main
#07: 0xb38dae2a Java_org_libsdl_app_SDLActivity_nativeRunMain
Backtrace emission took 0 seconds.
(continued from above) ERROR : /var/lib/jenkins/workspace/Cataclysm-Android/android/app/jni/src/../../../../src/main_menu.cpp:1150 [bool main_menu::load_character_tab(bool)] Error: Json error: storage/emulated/0/Android/data/com.cleverraven.cataclysmdda/files/data/json/mapgen/basecamps/modular_shelter_2/modular_shelter_2_common.json:302:4: expected string but got '�'

    "method": "json",
    "nested_mapgen_id": "fbmc_shelter_2_bed_makeshift_south1_wall",
   �
   ^
    @�p8s���z���fx8V����y�ܫ�|v��2 ], &rOws": [
(�EXJ�I|�����   0 "nL"
      �8ѽ���%rw��hO�4�_�Ϣߖ��}v�
15:21:22.436 ERROR : /var/lib/jenkins/workspace/Cataclysm-Android/android/app/jni/src/../../../../src/main_menu.cpp:1150 [bool main_menu::load_character_tab(bool)] Error: Json error: storage/emulated/0/Android/data/com.cleverraven.cataclysmdda/files/data/json/mapgen/basecamps/modular_shelter_2/modular_shelter_2_common.json:302:4: expected string but got '�'

    "method": "json",
    "nested_mapgen_id": "fbmc_shelter_2_bed_makeshift_south1_wall",
   �
   ^
    @�p8s���z���fx8V����y�ܫ�|v��2 ], &rOws": [
(�EXJ�I|�����   0 "nL"
      �8ѽ���%rw��hO�4�_�Ϣߖ��}v�
15:21:32.465 : Log shutdown.

Hope that helps! Is there a way to rollback to a previous save??

**Comment by BrettDong** [comment]
Did you quit the app when it's saving?

> Is there a way to rollback to a previous save?

I don't think so.

**Comment by PatrikLundell** [comment]
I believe the only way to create rollbacks is to manually copy the save folder periodically. It can be noted that these folders can get rather large, so it may become an issue if you have limited amounts of memory (although deleting the rollback before the last one before creating a new one might limit the effect [if you want to be sure to be able to roll back, you need the current save and the previous rollback, so you can't just rely on the current save and the just created rollback copy of it, in case the current save is silently corrupted]).

**Comment by LeahLuong** [comment]
No, I didn't quit the app when it was saving; it may have quit itself.

Are you telling me I have no option but to start over again -- scrapping the last couple of weeks of progress -- & simply hope this doesn't happen again if I want to keep playing this game??

**Comment by PatrikLundell** [comment]
Unfortunately, I think you're screwed. However, the error refers to a file that's not part of the save, but part of the game installation, so I'd try to install the game again from scratch in a new location (or renaming the old installation and use the "sensible" name for the new one) and copy your save folder from the corrupt installation to the new one and start the game and try to load the copied save. If you're really lucky the corruption hit the game installation but not the save.
The save folder should be <CDDA installation>/save/<folder named according to the world's name>, and you'd need to manually create the "save" folder in the new installation as it isn't created until the first world is created.

**Comment by BrettDong** [comment]
Your save data is corrupted, and if you don't have backup, your game is lost.

If the game crashes, it will write stack trace information to `crash.log` in `config` folder. Without `crash.log` we cannot determine what caused the crash.

**Comment by BrettDong** [comment]
If the game crashes, it will write stack trace information to crash.log in config folder. Without crash.log we cannot determine what caused the crash.

**Comment by LeahLuong** [comment]
Renaming sounds like a simpler solution to try before reinstallation. What is the "sensible" name to use & to which folder do I apply it??

Brett, I looked in config & there is no crash.log. I already told you my systemwide search for that term turned up nothing. That's why I turned to debug.log & posted the entry that appeared just prior to the failure-to-reload log. The debug.log spans half of a mB of text stretching back to, I think, world creation & seems to contain every log generated in my playthrough.

**Comment by BrettDong** [comment]
I recommend you to backup your save folder, reinstall the game, and copy your backup back to the new installation.

> Brett, I looked in config & there is no crash.log. I already told you my systemwide search for that term turned up nothing. That's why I turned to debug.log & posted the entry that appeared just prior to the failure-to-reload log. The debug.log spans half of a mB of text stretching back to, I think, world creation & seems to contain every log generated in my playthrough.

Unfortunately `debug.log` you posted does not contain information that can explain why the crash happened.

**Comment by PatrikLundell** [comment]
Renaming wasn't meant to indicate an alternative to re-installation, but rather a step to retain the name you have now, i.e.
Cataclysm-DDA ->Cataclysm-DDA.bugged + installation to Cataclysm-DDA (if Cataclysm-DDA is what you've called it currently).
The folder thus would be the folder into which you've placed CDDA (sorry if I'm overly explicit, but I find that to better than the alternative).

**Comment by LeahLuong** [comment]
It appears I have won the lucky lottery today; reinstallation allowed me to get back into my game. Strangely, simply renaming the original folder was not allowing me to do it. It would offer to update my game & then fail to install. I moved my save & settings out of the original, uninstalled, & then reinstalled. Even following uninstallation the renamed folder was still there. I manually deleted it after successfully reloading. Thanks for the good advice & this issue can now be closed. Do I have to do that or can you??
