### ISSUE TITLE
Experimental build cdda-windows-tiles-x64-2021-09-30-0747.zip seems to be broken

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#51991]
### Describe the bug

The build crashes to desktop when trying to load a save.

### Steps To Reproduce

1. Install the experimental build.
2. Copy a (recent and not-so-recent: tried both) save into the save folder (created if needed)
3. Try to load the save
4. See a list of "mods"
5. See the game disappear without progressing to trying to read the list of things to load that usually appears after the mod list.

I've also created a world with default parameters and a random character within that world. Trying to load that save behaves the same.

### Expected behavior

It would load the save without crashing.

### Versions and configuration

Windows 10.1 (unless the number has increased through auto updates).
Game version as per title.

Can't use the "Generate game report" functionality as the game crashes before this functionality becomes available.

### Additional context

[debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7258548/debug.zip)
No crash log generated.

Edit: The same bug seems to affect build 2021-09-30-0617. Since the Windows versions were missing from a number of builds prior to these, it may well be a Windows specific issue, in which case it might be useful to withdraw the new non working ones as well.

**Comment by mpyn** [comment]
the previous build cdda-windows-tiles-x64-2021-09-30-0617had the same problems

**Comment by BrettDong** [comment]
Alternatively https://github.com/akrieger/Cataclysm-DDA/releases/tag/cdda-experimental-2021-09-30-0020 is playable for those who want to play latest experimental on Windows.

**Comment by PatrikLundell** [comment]
Thanks @BrettDong! That's exactly what I need at the moment!

**Comment by GGgatherer** [comment]
Can confirm, crashes while processing the very first, core [dda] module, even in freshly-created world. No crash log generated, last thing in debug is language setting.

**Comment by BrettDong** [comment]
![Stack Trace](https://user-images.githubusercontent.com/21075502/135449185-1d213f9f-f76c-49ac-bcc9-35e571936658.png)
