### ISSUE TITLE
Some EOC related suggestion

### ISSUE THREAD

**Issue by adorableNYNICG** [CleverRaven/Cataclysm-DDA#51992]
# Is your feature request related to a problem? Please describe.
**1.Please make "deactivate_condition" run with mutation via enchantment.**
EOC.md says that when player gets new bionic/traits(mutation), game checks for "deactivate_condition" of all deactiveted EOC. And  then activate EOC if it's "deactivate_condition" returns false.
But game doesn't check for it if player gets mutation via enchantment.
Could you make this "check" runs on acquisition of mutation via enchantment too?

**2.Please make it possible to talk to monster via "pet_menu"**
There is new feature which allow player to talk with monster. But currently, monster or player needs to cast spell to the opponent in order to talk each other. I think it's bit inconvenient when I want to talk with friendly pet monster. I want to talk to pet via "pet_menu".

# Describe the solution you'd like
**For 1**
Run "deactivate_condition" check on mutation acquisition via enchantment too.

**For 2**
Add new entry to "pet_menu" if monster has "chat_topics" field in it's definition. Upon selecting this new entry, game opens dialog between player and pet monster.

# Describe alternatives you've considered

# Additional context
I can't code. So this suggestion is just a little wish of one of fan. It may pointless to add these feature.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
