### ISSUE TITLE
[Magiclysm] Invisibility effect is never applied

### ISSUE THREAD

**Issue by DigitalLibrarian** [CleverRaven/Cataclysm-DDA#51998]
### Describe the bug

When I cast the magiclysm technomancer Invisibility spell, I get confirmation of success in the console, but the effect is never applied to my character.  I have other worlds and other characters and this spell works on them, running the same version of code.  Also one of those working characters is in a world that came from copying the same settings/mods as the upload.

### Steps To Reproduce

1. Load up the only character in my Zombieland save: Chet Garza
2. Cast Invisibility (until success)
3. Confirm that the console indicates that the spell cast successfully
4. Check the character sheet and notice that there is no Invisibility effect
[Zombieland.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7259782/Zombieland.zip)
 

### Expected behavior

Casting Invisibility should apply the effect

### Versions and configuration

Version: cfc8042
Build: 2021-09-15 1905

modlist:

[
  "dda",
  "no_npc_food",
  "no_fungal_growth",
  "package_bionic_professions",
  "BL9_100monres",
  "aftershock",
  "blazeindustries",
  "magiclysm",
  "alt_map_key",
  "crazy_cataclysm",
  "extra_mut_scens",
  "MMA",
  "Graphical_Overmap",
  "Graphical_Overmap_Magiclysm",
  "speedydex",
  "StatsThroughSkills",
  "useful_helicopters"
]

**Comment by Zetsumei45** [comment]
I haven't checked the save but if you have the buff/debuff Safe Shopping from Forge of Wonders it won't let you apply invisibility.

**Comment by DigitalLibrarian** [comment]
That was the case.  For some reason, I had a gigantic duration on that safe shopper effect.  There may be some bug related to how it renews itself if the player spends many days/hours inside the forge of wonders.

**Comment by Divreus** [comment]
Yeah, my Safe Shopping Experience effect has been going on for five weeks now. I think I slept in the building at some point.
