### ISSUE TITLE
xlnomex_socks lacks the OVERSIZE flag

### ISSUE THREAD

**Issue by Lloydles** [CleverRaven/Cataclysm-DDA#51990]
### Describe the bug

XL flame-resistant socks do not fit on mutated feet because they lack the OVERSIZE flag in boots.json.

### Steps To Reproduce

Make a player character, mutate hooves, and spawn in XL flame-resistant socks. You will not be able to put them on, which essentially renders the XL version useless and needlessly expensive.

### Expected behavior

I would generally expect XL clothing and armor to fit mutated body parts.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 716276e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi],
    Manual Bionic Installation [manualbionicinstall],
    Stats Through Kills [stats_through_kills],
    Blaze Industries [blazeindustries],
    Useful Helicopters Experimental [useful_helicopters]
]

**Comment by PatrikLundell** [comment]
XL is for extra large, not for weirdly shaped. It's a common issue with mutated body parts that equipment for those parts no longer fit. What you'd need is the ability to essentially create crafting recipes to create clothing that fits mutated shapes, and I don't think that exists.

Thus, I don't think the item would fit even if the missing flag was there.

**Comment by Lloydles** [comment]
> XL is for extra large, not for weirdly shaped. It's a common issue with mutated body parts that equipment for those parts no longer fit. What you'd need is the ability to essentially create crafting recipes to create clothing that fits mutated shapes, and I don't think that exists.
> 
> Thus, I don't think the item would fit even if the missing flag was there.

I don't see this being a matter of opinion, as every other 'XL' item has the OVERSIZE tag and reads _'large enough to accommodate abnormally large mutated anatomy'_. Nomex socks are simply inconsistent with this.

**Comment by PatrikLundell** [comment]
I agree the flag is missing, so we're not in disagreement regarding that part. However, a number of mutations (like abnormally large) cause the size to change without changing the shape of some body parts. Hooves are not compatible with shoes regardless of size, and muzzles etc. prevent the usage of gear covering that part of the anatomy (again, regardless of size).

**Comment by Sohex** [comment]
Fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/52239 Needs to be closed.
