### ISSUE TITLE
Smart Engine Controller shuts down with single engine

### ISSUE THREAD

**Issue by Nerdy314159265** [CleverRaven/Cataclysm-DDA#52009]
### Describe the bug

I'm unsure if this is more appropriate as a bug or feature request since the issue is borderline a bug via it's text and borderline a feature request since it seems like it might be asking to alter the item to add a feature.

The Smart Engine Controller lists as one of it's uses cases a Stationary Generator. However, in the case of a single engine vehicle it will shut itself down and refuse to function at all.

This feels like a bug, since when the vehicle isn't moving and you aren't in control of it, it functions as a stationary generator. If I'm running a high power operation like an autoclave and I don't have a large amount of battery capacity, then I would expect that if I activated it while not driving and left it to it's devices, it'd work to keep the battery level topped off.

Instead, like I mentioned it shuts itself down.

### Steps To Reproduce

Add a Smart Engine Controller to a single engine vehicle.
Activate it while stationary and without taking control of the vehicle.
Wait
SEC will shut itself off complaining that it is attached to a single engine vehicle and that it's intended for multiple engines.

### Expected behavior

I would expect that as long as you don't take control of the vehicle, that it would work to maintain the battery charge level.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by hexagonrecursion** [comment]
Confirmed

![DeepinScreenshot_select-area_20220104133424](https://user-images.githubusercontent.com/52621858/148046353-a581e656-0098-4277-8585-4e931c944f46.png)

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: eacb7d9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
