### ISSUE TITLE
NPCs stop disassembly work if player character changes Z-level

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#52008]
### Describe the bug

So, I've started to get enough NPCs at my new faction that I can spare a few for non-expansion-related things, and I decided to try out assigning them to jobs around the camp - especially the disassembly work I had suggested adding in a while back (thank you, by the way!). Unfortunately, I soon found out that the NPC immediately "completes" their disassembly work if I change Z-levels, despite not being finished with disassembling the items in the zone.

### Steps To Reproduce

1. Designate a disassembly work zone with loot to disassemble in it
2. Tell an NPC follower to disassemble the items
3. Walk up or down a ramp or set of stairs
4. Look at the message log, and/or return to the previous Z-level, and observe that the NPC supposedly "completed" their task without actually doing so

### Expected behavior

I expect NPCs assigned to do disassembly work will continue doing it regardless of whether or not I'm on the same Z-level.

### Versions and configuration

OS: Windows
OS Version: Windows 8.1 Pro
Game Version: ccf5e15 [64-bit]
Graphics Version: Tiles
Game Language: System language []
Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
Bionic Professions [package_bionic_professions],
Aftershock [aftershock],
Blaze Industries [blazeindustries],
C.R.I.T Expansion Mod [crt_expansion],
Magiclysm [magiclysm],
XEAS [XEAS],
Gun Cotton [guncotton],
DinoMod [DinoMod],
Youkai Enemies [Youkai_Disco],
Mining Mod [Mining_Mod],
Mole Mutation [dig_a_tunna],
More Survivor Stuff [more_survivor_stuff],
Mythical Martial Arts [MMA],
More City Locations [cityside],
No Rail Stations [No_Rail_Stations],
Compatible Nimian Manufacture Guns [NM_wpns],
No Fungal Monsters [No_Fungi],
Fuji's Military Profession Pack [fuji_mpp],
Magiclysm No Class Limit [magiclysm_no_class_limit],
Mutation Changes [Mutation_Changes],
Portable Autodoc [portable_autodoc],
SpeedyDex [speedydex],
Stats Through Kills [stats_through_kills],
Stats Through Skills [StatsThroughSkills],
Useful Helicopters [useful_helicopters],
Arcana and Magic Items [Arcana],
return_the_nut [return_the_nut],
Hydroponics [hydroponics],
Cooler Versatility [coolervers],
Chris K's Knives [ChrisKsKnives],
Custom Spells [Custom_Spells],
Reproduction mod [perverts],
Custom Bionics [custom_bionics],
Magiclysm Runes in Arcana Recipes [Custom_ArcanaRune],
Deconstruction Plus [Deconstruction_plus],
Core Data Changes [core_data_changes],
Arcadia Mapgen [custom_arcadia_mapgen]

**Comment by PatrikLundell** [comment]
Does it "complete" if you move so the companion ends up outside of the reality bubble by moving away horizontally? If so, it may be implemented in a similar fashion to sorting of items.

Also, does it abort or does it finish disassembling the current item, but not continue with the next one?

**Comment by AmarinReyny** [comment]
> Does it "complete" if you move so the companion ends up outside of the reality bubble by moving away horizontally? If so, it may be implemented in a similar fashion to sorting of items.

Just checked, and no, it doesn't.
 
> Also, does it abort or does it finish disassembling the current item, but not continue with the next one?

It doesn't finish disassembling the current item, it just immediately stops the moment my character changes Z-levels.

**Comment by PatrikLundell** [comment]
Thanks for the answers. Now, I can't do anything useful with the information, but I asked the questions in case the info would be of use to those who can, basically to help speed up any investigation that may be happening.

**Comment by GGgatherer** [comment]
Looks like resurface of my old issue #43982, only that one was about NPCs reading books. Was fixed by #46615, maybe this needs the same fix?
