### ISSUE TITLE
Game could not remove file

### ISSUE THREAD

**Issue by SCHIZO8586** [CleverRaven/Cataclysm-DDA#52019]
### Describe the bug

Game could not remove save file. If the world name is in English, then it works fine.

### Steps To Reproduce

1. Create a new world or stay in the old one.
2. Start playing.
3. Die.

### Expected behavior

The game should copy the save file to the new path and delete the old one.

### Screenshots

![unknown](https://user-images.githubusercontent.com/52156243/135610377-bf7a7c38-6556-4ef2-bbfa-991506953643.png)

### Versions and configuration

OS: Linux Mint 20.2
Game version: 76635e3 [64-bit]
Graphics version: Tiles
Ingame language: Russian
Mods loaded: [dda, no_needs_for_NPC, no_fungal_growth]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7266731/debug.log)

**Comment by BrettDong** [comment]
Is your system locale ru.UTF-8?

**Comment by SCHIZO8586** [comment]
> Is your system locale ru.UTF-8?

Yes, it is.

**Comment by kwl01skz** [comment]
This error is not repeated in Chinese.

Maybe there is something wrong with my compilation settings. I can't find the option of Russian.
![image](https://user-images.githubusercontent.com/1281487/135762021-cf45b66f-a21b-4106-966d-442ad58bff0b.png)



- OS: Linux
    - OS Version: Distributor ID: Linuxmint; Description: Linux Mint 20; Release: 20; Codename: ulyana; 
- Game Version: 0.F-3183-g82fd5e73ed [64-bit]
- Graphics Version: Tiles
- Game Language: [zh_CN]
- Mods loaded: [
  [dda],
  [no_npc_food],
  [package_bionic_professions],
  [blazeindustries],
  [crt_expansion],
  [magiclysm],
  [extra_mut_scens],
  [fuji_mpp],
  [MMA]
]

**Comment by SCHIZO8586** [comment]
> Maybe there is something wrong with my compilation settings. I can't find the option of Russian.

Russian -> Русский

**Comment by kwl01skz** [comment]
It happened that I updated Linux mint to 20.2 yesterday.
I tried just now and didn't report an error.

- OS: Linux
    - OS Version: Distributor ID: Linuxmint; Description: Linux Mint 20.2; Release: 20.2; Codename: uma; 
- Game Version: 0.F-3183-g82fd5e73ed [64-bit]
- Graphics Version: Tiles
- Game Language: Русский [ru]
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у NPC [no_npc_food],
    Без роста фунгалоидов [no_fungal_growth]
]

**Comment by morthein** [comment]
My in game language is English and I get this every time. Been happening for awhile.
