### ISSUE TITLE
Segmentation fault when trading with Eddie Isherwood from the Isherwood ranches.

### ISSUE THREAD

**Issue by Quintovir** [CleverRaven/Cataclysm-DDA#52014]
### Describe the bug

When I accept a trade with Eddie Isherwood the game crashes.

### Steps To Reproduce

1. Select Eddie's "3L glass jar (sealed) > milk (fresh)" and "plastic bag > cheese".
2. Select my disposable batteries.
3. Press Enter.
4. Confirm the trade by pressing "Y".

### Expected behavior

The game should not crash when trading with Eddie Isherwood.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 21.1.3; Codename: Pahvo; 
- Game Version: 0.F-3098-g15692c4b21-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    Fuji's Military Profession Pack [fuji_mpp],
    No Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

Save game with crash.log.
[TRADE SEGMENTATION FAULT.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7263220/TRADE.SEGMENTATION.FAULT.zip)

**Comment by ferociousdork** [comment]
Seems to have been caused by #51704. `ip` is copied here instead of captured by reference:
https://github.com/CleverRaven/Cataclysm-DDA/blob/81ae26757a8fe9a2abfa8ce6def25ee7853b268a/src/npctrade.cpp#L86

which causes the pointer here refer to local stack memory:
https://github.com/CleverRaven/Cataclysm-DDA/blob/81ae26757a8fe9a2abfa8ce6def25ee7853b268a/src/npctrade.cpp#L140

**Comment by zakhad** [comment]
I believe i might have been getting the same issue but with trading with hub 0


[crash (1).log](https://github.com/CleverRaven/Cataclysm-DDA/files/7273470/crash.1.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7273471/debug.log)
![image](https://user-images.githubusercontent.com/5264667/135757679-bdee95fe-1622-4a7c-a1f7-8d2de557769f.png)
