### ISSUE TITLE
Teleglow can cause permanent irreversible fungal infections

### ISSUE THREAD

**Issue by jim-huynh** [CleverRaven/Cataclysm-DDA#52040]
### Describe the bug

Teleglow can cause permanent irreversible fungal infections due to antifungals now working over time https://github.com/CleverRaven/Cataclysm-DDA/pull/42388

### Steps To Reproduce

Step into a portal and hope for the 1/10,000 chance that you get the fungal result.

### Expected behavior

This used to be a curable condition when antifungals were instant and removed the fungal infection directly.  Since teleglow is not coded to specifically make you a Mycus, it should still be curable.

```
if( one_in( 10000 ) ) {
        if( !u.has_trait( trait_M_IMMUNE ) ) {
            u.add_effect( effect_fungus, 1_turns, true );
        } else {
            u.add_msg_if_player( m_info, _( "We have many colonists awaiting passage." ) );
        }
        // Set ourselves up for removal
        it.set_duration( 0_turns );
    }
```

The duration should probably be changed to something relatively long, but the permanent flag should be set to false.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-3138-g6457789afd-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots]
]

(This is my own build with very minor bug fixes that don't touch player_hardcoded_effects.cpp)

**Comment by Kribylet** [comment]
What makes you sure that #42388 is to blame? Is there something that makes you sure this case is different from #51939?

> (This is my own build with very minor bug fixes that don't touch player_hardcoded_effects.cpp)

Does your build revert #51827?

**Comment by jim-huynh** [comment]
@Kribylet https://github.com/CleverRaven/Cataclysm-DDA/issues/51939 is caused by a different snippet of code in player_hardcoded_effects.cpp which has basically the same problem - it adds the fungal effect with a 1 turn duration and the permanent flag is set to true.  It should be something like u.add_effect( effect_fungus, 4_hours, false ); <--- time depending on how intense we want it to be on initial infection.

```
static void eff_fun_spores( Character &u, effect &it )
{
    // Equivalent to X in 150000 + health * 100
    const int intense = it.get_intensity();
    if( ( !u.has_trait( trait_M_IMMUNE ) ) && ( one_in( 100 ) &&
            x_in_y( intense, 900 + u.get_healthy() * 0.6 ) ) ) {
        u.add_effect( effect_fungus, 1_turns, true );
    }
}
```

![image](https://user-images.githubusercontent.com/3409545/135719834-d12f9cf8-99d2-4c18-831b-e5c5849f4c40.png)

**Comment by Kribylet** [comment]
> @Kribylet #51939 is caused by a different snippet of code in player_hardcoded_effects.cpp which has basically the same problem - it adds the fungal effect with a 1 turn duration and the permanent flag is set to true. It should be something like u.add_effect( effect_fungus, 4_hours, false ); <--- time depending on how intense we want it to be on initial infection.

If the permanent flag is the issue, why does reverting #51827 also fix the issue?

**Comment by jim-huynh** [comment]
Yeah ok, I see what you're talking about in your PR.
