### ISSUE TITLE
Better refugee center mission

### ISSUE THREAD

**Issue by TealcOneill** [CleverRaven/Cataclysm-DDA#52067]
# Is your feature request related to a problem? Please describe.
The current first refugee center mission is really not great and typically ends up with a bunch of NPCs flooding the room of zombies if the player doesn't jump in the way. I recently did the mission and was totally unable to attack the zombies because I backed up to give myself room and then couldn't fire around the NPCs. Afterwards I also had an issue where all the NPCs stacked up in a hallway and didn't return to their positions.
# Describe the solution you'd like
Instead of the merchant telling you to kill the zombies and then leaving you to your own devices he directs you to talk to the guard in the back bay about the zombie situation. The guard will direct you to gather some reach weapons for the guards to use, along with the materials to build some walls( as in #52068) that you can use reach weapons through. You will also need some kind of explosive to blow open the door to the room. Once you get all the stuff you're told to come back in a day or two once the walls have been put up. You can then talk to the guard to start the fight, and they will position guards around the newly built wall while you can shoot or do whatever. All the other doors to the room should also be locked and or barred until the fight is finished so that if you fail all the zombies don't flood the rest of the center and so the random NPCs don't try and come fight. This to me is a much more logical because who is really going to tell a stranger to go kill all the zombies and then leave them to it. The teamster also shouldn't show up until the first mission is finished, i.e they're out trading at the time.
# Describe alternatives you've considered
Somehow making it to where the NPCs won't attempt to come help when you open the door up.
# Additional context
I don't know how difficult this would be to do and I have other stuff to do so I'm putting it out there for someone else to deal with. 
![refugeecenter1](https://user-images.githubusercontent.com/45678006/135743144-bd210d09-f71b-42ed-970b-6d09b22470b3.png)
This is the configuration for the walls I thought of, with these metal ones being replaced by the ones with slits.
![refugeeproblem](https://user-images.githubusercontent.com/45678006/135743148-38876cd3-3517-4a0f-99bb-0004def99a9a.png)
This happened after I did the refugee mission and the NPCs never returned to their positions afterwards.

**Comment by TealcOneill** [comment]
I-am-Erk and I spent a while chatting about this here(https://discord.com/channels/598523535169945603/598535827169083403/895098034633973780) and we came up with some good thoughts and ideas. I plan to work on some other stuff for a while but in a couple of weeks I'm going to come back to this. If you're interested in working on this or have a thoughts, don't hesitate to @ me here or on discord.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
