### ISSUE TITLE
"Unracking task failed" error after vehicle(s) vanish post unload/reload on bike rack.

### ISSUE THREAD

**Issue by ProfoundDarkness** [CleverRaven/Cataclysm-DDA#52079]
### Describe the bug

This is kind of two part and may be related to #52005.
First part, detaching one of several 'identical' vehicles causes the other 'identical' vehicles to vanish.
Second, if re-attaching the recently detached vehicle then detaching it again this error gets thrown:

`ERROR : src/activity_actor.cpp:1227 [virtual void bikerack_unracking_activity_actor::finish(player_activity&, Character&)] Unracking task failed.  Parent-Vehicle:Electric SUV with Bike Rack; Found parts size:12`

It seems the other vehicles didn't vanish but got merged into one invalid vehicle (3 frames in one slot).

### Steps To Reproduce

[Test_BikeRack.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7274269/Test_BikeRack.zip)
From save:
1. Attach all three vehicles to bike rack. (technically 2 of them side by side is sufficient)
2. Detach one of the vehicles.  Observe there is only one choice with 3 attached.  Observe the others attached vanish.
3. Attach the vehicle.
4. Detach the vehicle (it's name is missing first letter in dialog?).
5. Observe error.

### Expected behavior

That the invalid state by step 4 is prevented... somehow...

There seems to be at least a couple different options to prevent that particular chain of events from resulting in an error.
- A new mechanism which makes identical vehicles perfectly valid. So step 2 would list 3 items and only one of the three would detach.
- Disallow identically named vehicles to be attached... So in step 1 when trying to attach the second Laundry Cart instead of it attaching it would not.  Bonus some feedback to the player letting them know there was already an identically named vehicle attached.  Having not yet poked around the relevant code this one seems easier to pull off.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.3 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-3146-g81ae26757a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth]
]

### Additional context

I seem to recall something like this being known back in 0.E stable... I didn't notice an issue on it in my searching though so likely called something else.

A snippet of the log around the error from a debug build:
[debug-snip.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7274306/debug-snip.zip)

**Comment by redcrate** [comment]
Confirmed carts vanished and appear to have combined into a mutant cart of some kind... received this error:
```
 DEBUG    : Unracking task failed.  Parent-Vehicle:Electric SUV with Bike Rack; Found parts size:27

 FUNCTION : virtual void bikerack_unracking_activity_actor::finish(player_activity&, Character&)
 FILE     : src/activity_actor.cpp
 LINE     : 1228
 VERSION  : d9d6448
```
![image](https://user-images.githubusercontent.com/85591702/135952687-a4f0545f-f47c-4e32-ade2-fa22b922b28f.png)


- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.3 LTS; Release: 20.04; Codename: focal; 
- Game Version: d9d6448 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth]
]

**Comment by hexagonrecursion** [comment]
> ###
> 
> [Test_BikeRack.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7274269/Test_BikeRack.zip) From save:
> 
>     1. Attach all three vehicles to bike rack. (technically 2 of them side by side is sufficient)
> 
>     2. Detach one of the vehicles.  Observe there is only one choice with 3 attached.  Observe the others attached vanish.
> 
>     3. Attach the vehicle.
> 
>     4. Detach the vehicle (it's name is missing first letter in dialog?).
> 
>     5. Observe error.

Confirmed. Thank you for uploading a save file and writing clear steps to reproduce the bug.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: eacb7d9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth]
]
