### ISSUE TITLE
Update 2021-10-03-1727 blanks out all menu text

### ISSUE THREAD

**Issue by DalenTalas** [CleverRaven/Cataclysm-DDA#52082]
### Describe the bug

See screenshot below. I can navigate the menu and even select the options. But no text is visible in any of the menus.

### Steps To Reproduce

Updated to 2021-10-03-1727.
Launched the game.

### Expected behavior

Um... actual game menus should be visible on the screen?

### Versions and configuration

Unable to obtain, as game is not launchable.

### Additional context

Windows 10 Home build 19043.1237 experience 120.2212.3530.0
Tiled graphics via the CDDA Launcher.

**Comment by ZhilkinSerg** [comment]
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/50149

**Comment by DalenTalas** [comment]
Closing as such, then.
