### ISSUE TITLE
Electronic devices that are (on) don't get broken by going in the water

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#52080]
### Describe the bug

(Some?) electronic devices that are in the (on) state do not get destroyed when you dive into deep water. I have confirmed this to be the case for the flashlight and E-ink reader, so presumably other items have the same issue.

Curiously, it doesn't seem to apply to items which say something other than (on). The smartphone and laptop computer, for instance, gain no protection from having their light turned on, unlike the E-ink reader.

### Steps To Reproduce

1. Give yourself a flashlight and/or E-ink reader and some batteries.
2. Step into deep water to confirm that they get Broken.
3. Give yourself another set of items, load them up with batteries and turn them on.
4. Go in the water and confirm that you don't get the prompt and the items are not detroyed.

### Expected behavior

Turning electronics on shouldn't waterproof them. If anything, the opposite would be true.

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0436c6d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Stats Through Skills [StatsThroughSkills],
    Extra Mutated Scenarios [extra_mut_scens],
    Magiclysm [magiclysm]
]

**Comment by Saicchi** [comment]
`flashlight_on` and `eink_tablet_pc_on` are missing the `WATER_BREAK` flag.

**Comment by PatrikLundell** [comment]
CDDA uses the convoluted method of morphing items into a different item when they are turned on/off, so if you happen to miss to add properties to one version when adding them to the other you end up with this kind of odd behavior (an attempt at an explanation for why this kind of weird behavior can happen).

**Comment by leemuar** [comment]
More specifically in this example flag inheritance properties were not used at all. On and Off versions used their own flags instead of inheriting (adding or removing) from the base item

> 
> 
> CDDA uses the convoluted method of morphing items into a different item when they are turned on/off, so if you happen to miss to add properties to one version when adding them to the other you end up with this kind of odd behavior (an attempt at an explanation for why this kind of weird behavior can happen).
