### ISSUE TITLE
Software renderer doesn't work properly under Wayland

### ISSUE THREAD

**Issue by Faalagorn** [CleverRaven/Cataclysm-DDA#52095]
### Describe the bug

Follow up to https://github.com/CleverRaven/Cataclysm-DDA/pull/51053#issuecomment-918256160 – software renderer doesn't work without this hacky solution of rendering it twice.

### Steps To Reproduce

1. Make sure you are running Wayland (e.g. type `echo $XDG_SESSION_TYPE`).
2. Run Cataclysm with Wayland (e.g. type `SDL_VIDEODRIVER=wayland cataclysm-tiles`).
3. If the renderer was not set to software, change to it in options and apply changes.
4. Observe the having issues with input.

### Expected behavior

The game should not have issues with input.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.F-3195-gcbd8876a6a1 [64-bit]
- Graphics Version: Tiles
- Game Language: Polski [pl]
- Mods loaded: [
    Dark Days Ahead [dda],
    Wyłącz potrzeby NPC [no_npc_food]
]

### Additional context

You can use fix from https://github.com/CleverRaven/Cataclysm-DDA/pull/51053#issuecomment-918256160 to get rid of the issue, despite at performance cost.

Unrelated, but software renderer doesn't seem to work on Android for me too, as per my comments in #51053 and on Discord, ideally the option should not appear there or fallback to a different renderer then.

**Comment by Adriankhl** [comment]
I was annoyed by this many weeks ago, and it is sad to see that this is still here. 

There are plenty of wayland-related bug in sdl2 (https://github.com/libsdl-org/SDL/issues?q=is%3Aissue+is%3Aopen+wayland), perhaps someone with good knowledge of sdl2 could figure out whether this problem belongs to CDDA or sdl2 itself.

**Comment by Faalagorn** [comment]
Well, there's a hack in the comment I posted if you want to use software renderer, I guess it _could_ be `if`-ed, but a proper fix would be welcome.

Gladly opengl and opengles work fine in Wayland for me, I used to be an have a problem with cursor, but it seems to be gone now, so I'm glad.

Alternatively, the game could detect running on Wayland and disallow or show a warning (or silently switch to xwayland) when trying to change to software, that at least would alleviate crashes by setting this option for whatever reason… :thinking:

**Comment by Adriankhl** [comment]
Thanks, opengles2 (it is the same as opengles in CDDA right?) works for me! Still have the same problem with opengl, perhaps the problem is from sdl2 side.

I think the sdl2 starts in xwayland by default (https://github.com/libsdl-org/SDL/issues/2710), which I also see this in the "Display" option.

**Comment by Faalagorn** [comment]
I run it with `SDL_VIDEODRIVER=wayland` forced in `.bash_profile` (sway and Arch BTW, but DE and distro shouldn't matter) and #51053 fixed the issues for me, but indeed the default for SDL is Xwayland (which sometimes is sane for proprietary closed source game, as they experience various problems with it forced so I actually have to switch it to `SDL_VIDEODRIVER=wayland` for some Steam games, including Valve's ones, but also things like original Dead Island which is having issues with mouse and keyboard under native Wayland.

**Comment by Adriankhl** [comment]
Great, https://github.com/CleverRaven/Cataclysm-DDA/pull/51053 fixes the `opengl` option :smile:
