### ISSUE TITLE
Excessive error repetition detected - invalid effect type id mabuff:buff_krav_maga_static1

### ISSUE THREAD

**Issue by atealein** [CleverRaven/Cataclysm-DDA#52094]
### Describe the bug

After this morning's update to most recent experimental I got an error about the krav maga (my default style) almost immediately, which I ignored in the future. A bit later I got a much more interesting error about "Excessive error repetition detected" for the same cause that requested to file a bug report. So here it is. 

### Steps To Reproduce

As far as I see, the error happened when my hands got free after crafting an item. ~~I am not sure if it is reproduceable as such.~~ 

I have now managed to reproduce it - every time I try to craft or construct something it happens. "Ignore this message" also doesn't seem to work for the reports of the excessive error repetition as I would choose it and it will still show up in the next craft action I do (even when it is the same craft/construct)

### Expected behavior

No error messages?

### Screenshots

![Screenshot from 2021-10-04 13-25-29](https://user-images.githubusercontent.com/25322782/135844228-1a2b9fbc-443b-4c8a-998c-7dfa505cbe00.png)

### Versions and configuration

- Linux RHLE
- Curses
- Experimental cbd8876

**Comment by Rabidweasel** [comment]
This is presumably related to #52036 changing the name of the Krav Maga buff from buff_krav_maga_static1 to buff_krav_maga_static. I can't reproduce on a fresh save, my best guess is it's some issue from having the martial art active in an old save and then updating?

**Comment by atealein** [comment]
Yeah, I just tested that I get the error regardless if I have weapon in my hands or if I change the style, so it is something else. Do you think it is something that can be fixed manually in the save? Search and replace sort of a thing?

**Comment by atealein** [comment]
> This is presumably related to #52036 changing the name of the Krav Maga buff from buff_krav_maga_static1 to buff_krav_maga_static. I can't reproduce on a fresh save, my best guess is it's some issue from having the martial art active in an old save and then updating?

That was it. Thanks a lot, a quick find and replace in my .sav fixed the issue! I'll close this one too, since it is my-side sort of a problem :D
