### ISSUE TITLE
Cannnot input Japanese.

### ISSUE THREAD

**Issue by shinmuro** [CleverRaven/Cataclysm-DDA#52105]
### Describe the bug

Version: 0.F-2
Cannot input Japanese on Android.

It assumes below SDL lib topics.
[SDL - iOS and Android Japanese Input not showing candidate list](https://discourse.libsdl.org/t/ios-and-android-japanese-input-not-showing-candidate-list/23214)

Please consider change InputType from `TYPE_TEXT_VARIATION_VISIBLE_PASSWORD` to `TYPE_TEXT_VARIATION_NORMAL`
[source](https://github.com/CleverRaven/Cataclysm-DDA/blob/2f54703cafb64f46d3c30e2be0d91b4fd5dd6411/android/app/src/main/java/org/libsdl/app/SDLActivity.java#L2209 )

### Steps To Reproduce

1. Show soft keyboard.
2. It cannnot switch Japanese Input Method. It normally labeled `あ`, inside Left-down corner.

### Expected behavior

When soft keyboard showed, It can see Input Method labeled `あ`, inside Left-down corner.

### Versions and configuration

- OS: Android
- Game Version: 0.F-2
- Ingame Language: Japanese

**Comment by ZhilkinSerg** [comment]
This is something to report in SDL2 repo. The proposed fix causes other bugs, so it was reverted. See https://github.com/libsdl-org/SDL/commit/d4e1c797205822e8da645b148a4d784c29abcd5f

**Comment by shinmuro** [comment]
Thank you for SDL2 information!
