### ISSUE TITLE
Limbs fail to load

### ISSUE THREAD

**Issue by l3lb0t** [CleverRaven/Cataclysm-DDA#52101]
### Describe the bug

Various json files in the json folder fail to load, preventing the game from starting. So does the LARWICK font used on the overmap.

### Steps To Reproduce

1. Clone the most recent version of CDDA onto your computer using the minty compiler
2. Create a world
3. Select create character or play now

### Expected behavior

I expected the game would start, as that's what it has done in the past.

### Screenshots

![image](https://user-images.githubusercontent.com/77447558/135931022-77399378-c0a5-48cc-8650-ca02860203af.png)
![image](https://user-images.githubusercontent.com/77447558/135931036-7e8550ae-ff33-4d1c-9e8e-cacfceac9bf8.png)
![image](https://user-images.githubusercontent.com/77447558/135931047-a2b66623-f7bb-4ad3-ba8a-e1e80172f6ae.png)
![image](https://user-images.githubusercontent.com/77447558/135931057-a60cad72-b294-41f7-b440-3c2ff4654547.png)
![image](https://user-images.githubusercontent.com/77447558/135931064-b25b6491-fa47-44e9-a5d4-4b1325704045.png)
There are many more.

### Versions and configuration

- Windows
- O.F-989-g01e74b623e
- Tiles
- English
- Disable NPC Needs, No Fungal Growth, Bionic Professions, Rural Only Mapgen

**Comment by ZhilkinSerg** [comment]
You are using incompatible game binary and data - e.g. you have unpacked archive with new version (from recent time) over existing installation (from July) and started old game executable. Don't do that. Install updated game to empty location instead and copy user files (saves, configs, mods, etc) there. If you are compiling by yourself - recompile the game.
