### ISSUE TITLE
No option to turn on the floodlight on the vehicle

### ISSUE THREAD

**Issue by mpyn** [CleverRaven/Cataclysm-DDA#52100]
### Describe the bug

No option to turn on the floodlight on the vehicle

<img width="374" alt="cata_floodlight" src="https://user-images.githubusercontent.com/5890610/135929698-f2714f1b-e080-4d67-a732-88e86cd3b098.png">

### Steps To Reproduce

Spawn any vehicle with floodlight e.g. work light (oa_work_light) and try to turn on floodlight

### Expected behavior

There should be an option to turn on the floodlight on the vehicle

### Versions and configuration

OS: Windows 10
Game version: cbd8876 [64-bit]
Graphics version: Tiles
Ingame language: English
Mods loaded: [dda, no_needs_for_NPC, no_fungal_growth]

**Comment by atealein** [comment]
Overhead lights is the floodlights of the vehicle, not sure why the name is different but that switch will turn them on.

**Comment by mpyn** [comment]
> Overhead lights is the floodlights of the vehicle, not sure why the name is different but that switch will turn them on.

Thank you, I understand. Previously there was a separate option for the floodlight.
