### ISSUE TITLE
Torso modifiers for encumbrance shows wrong rolls

### ISSUE THREAD

**Issue by Chupachabra** [CleverRaven/Cataclysm-DDA#52109]
### Describe the bug

Modifiers for torso encumbrance shows incorrect rolls on "player info" screen. Only affect on what is worn on the feet.

![Снимок экрана (66)](https://user-images.githubusercontent.com/73247933/136003088-22915b4b-664b-47ad-8a21-c781c9f3d69b.png)

### Steps To Reproduce

1. Equip few bags with stuff
2. Remove encumbrance from feet
3. Behold no modiier rolls on torso encumbrance

### Expected behavior

Why can't you just be normal?

### Versions and configuration

OS: Windows 10
Game version: 2f54703 [64-bit]
Graphics Version: Tiles
Game Language: English/Russian
Mods loaded: None

**Comment by wapcaplet** [comment]
See also #52418
