### ISSUE TITLE
QOL: Disassemble menu, permit searching by yield

### ISSUE THREAD

**Issue by bididox** [CleverRaven/Cataclysm-DDA#52117]
# Is your feature request related to a problem? Please describe.
The disassemble interface permits searching only by item name, such as truck alternator, dashboard and down-filled blanket. It would be helpful to permit searching by item components (e.g. solder, felt patch, power converter) so that when a recipe calls for some component you quickly and easily know where to get it from.

# Describe the solution you'd like
Similar to recipes, where you hit the '/' key and can add a prefix to look-up by component required to craft (c:plank), or tool required to craft (p:tailoring), in the disassemble menu include a prefix to look-up by yield (y:solder).

# Describe alternatives you've considered
N/A

# Additional context
Currently you need to carefully scan the whole list. I attach my mock-up of how it can possibly look like.
![Untitled](https://user-images.githubusercontent.com/91974071/136065238-b2e4beb6-bc35-48ab-ac78-c9eb2598cdc8.png)

Thank you very much team CDDA for giving us so much over the years.

**Comment by dseguin** [comment]
There's a `d:` flag for sorting by disassembled components. Is this what you're looking for?
![disassemble](https://user-images.githubusercontent.com/12537966/136103409-dc92338e-431c-4b89-a364-0a1d186c4564.png)

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
