### ISSUE TITLE
Storage improvements

### ISSUE THREAD

**Issue by GodPhase777** [CleverRaven/Cataclysm-DDA#52116]
It would be far easier to have some more diverse storage, like upgrading backpacks with fabric to increase weight handling, volume, and length. Possibly make it so each upgrade has its drawbacks against other parts of storage, so you can't upgrade length without somehow messing with volume or other important aspects of the bag.

Possibly add some wall storage devices that can be installed on preexisting boards, this would have the benefit of better durability and less weight at the cost of lower storage size than stow boards.

You could also add roof storage, like those crappy bungee cables and some other methods as well.

**Comment by GodPhase777** [comment]
I'm saying to be able to sow new things onto those, to upgrade them
like sowing a pocket on a pocketless shirt, or increasing the width of a molle pack to hold a longer object.

**Comment by Zireael07** [comment]
@GodPhase777 In that case, dupe of https://github.com/CleverRaven/Cataclysm-DDA/issues/44866

**Comment by GodPhase777** [comment]
Not just that? a few other things i suggest too

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
