### ISSUE TITLE
Allow installing ladders to vehicles

### ISSUE THREAD

**Issue by bididox** [CleverRaven/Cataclysm-DDA#52119]
# Is your feature request related to a problem? Please describe.
N/A

# Describe the solution you'd like
From the roof of the vehicle our characters have a better view of their surroundings. Similar to how they can climb radio towers to discover more map, or the roof of houses with a stepladder. This way, paired with binoculars or a telescope, they can scout from a safe distance.

The component can be a step ladder, installed with nails and hammer protruding on the outside perimeter of the vehicle (like wing mirrors).

The current interface to install vehicle parts. Imagine there was a ladder in that list.
![24](https://user-images.githubusercontent.com/91974071/136072560-15524dea-6304-4f8e-8af1-c8dec71f9ad4.png)

# Describe alternatives you've considered
Carry a stepladder.
Deploy it next to a vehicle's roof, climb it up, climb it down, pack the ladder.
Move the vehicle to a new position.
Repeat.

# Additional context
Ladder on the back of an RV
![th](https://user-images.githubusercontent.com/91974071/136071435-308bc606-79d1-4bff-bd4c-08d1b10cdd67.jpeg)

Guy with binoculars on a car's roof.
![gettyimages-200343666-002-2048x2048](https://user-images.githubusercontent.com/91974071/136071436-da4a14ac-014c-4cd6-8f27-51ddef491605.jpg)

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
