### ISSUE TITLE
Blacklisting / Marking a vehicle so NPCs won't disassemble it

### ISSUE THREAD

**Issue by atealein** [CleverRaven/Cataclysm-DDA#52123]
# Is your feature request related to a problem? Please describe.
I can install a vehicle welding rig or a boom crane on a frame to be used in a faction camp. However they have to be in proximity of the vehicles to be disassembled and if placed in the center of the vehicle disassembly zone (so they can cover a better radius) they get disassembled alongside the other vehicles.

# Describe the solution you'd like
I want to be able to tag a vehicle in a way so it is blacklisted from disassembly. Or alternatively, white listed to show that I want them to disassemble exactly that vehicle.

# Describe alternatives you've considered
Customizing the disassembly zone into 4-5 smaller ones so the tool-vehicles are not in them.
# Additional context
I only assume that the NPCs benefit from the tools available to them like this, but am actually not 100% sure they use them.

**Comment by PatrikLundell** [comment]
Good suggestion. 

I know they use lifting vehicles for disassembly in 0.F-0 (I'd managed to get hold of 4 such single tile vehicles). The way I've used them was to paint disassembly zones over the vehicle to be disassembled and then remove the zone afterwards (for each and very vehicle). If the vehicle has wing mirrors I've painted a single tile wide strip from one mirror to the other (so the lifting vehicles could be placed next to the vehicle elsewhere). It can also be noted that you don't need a faction camp to use this (the faction camp garage has a "Chop Shop" functionality I've never used).

These vehicles have an action radius of 3 tiles, which means you can have a fixed arrangement for vehicles with a width of up to 6 tiles wide, spaced 7 tiles apart in rows. However, wing mirrors, again, get in the way, so if you want to deal with those you need to move the lifting vehicles out of the way before driving them into the zone. It can be noted that there's one vehicle that you need a very exact arrangement to get at the engine (at a 45 degree angle to get LoS to it, unless you remove the walls first).

For the garage I'd like to see an abstract ceiling mounted system that would cover the whole building (at a construction cost). That's a different solution to a slightly different problem, though.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
