### ISSUE TITLE
_More_ realistic animal breeding

### ISSUE THREAD

**Issue by atealein** [CleverRaven/Cataclysm-DDA#52122]
# Is your feature request related to a problem? Please describe.
Currently, different tameable or wild animals (non-mutant, non-monsters) have a very simplified breeding system where all animals are considered to reproduce asexually, all adult animals have a pregnancy timer and at the end of it they have 50% chance to give birth to one young animal, and in either case the timer is reset and started again.

# Describe the solution you'd like
I think there are few steps that can turn the system to be a bit more realistic and provide some challenge for anyone that wants to RP the Isherwood family farms in his own version of the cataclysm :) 

The proposed changes are for mammals and birds only, insects and fish work in different scale/system in game and in real world so we are ignoring them here.

- [ ] Add explicitly male version of all (or most tameable at least) animals that will be affected by this. Bull, ram, hog, etc. Make the male version more hostile or aggressive by default to provide some extra challenge for the player _(because who doesn't want to be chased by an angry bull through the corn fields in a world full of other more interesting monsters)_. And obvious jokes aside, it is clear that rams and bulls won't be available for milking purposes. _expected mostly json changes_
- [ ] Change the way that young animals grow up - they will change to either the male or female adult animal (50% chance for each) _expected mostly json changes_
- [ ] Herds spawn when a location enters the reality bubble for first time will have a pair of male and female animals, and if the herd is larger than 2 in number, the extra animals will be females or young ones. (different family structure can be developed later on if anyone has interest to continue developing this, but as first estimation this is the more average ruminant herd)
- [ ] Females will start their pregnancy timer when they get a trigger from a male animal of the same type (the trigger can be proximity, line of sight or the two animals being loaded at the same time in the reality bubble, not sure what is available in the code as functions right now that we can recycle for this)
- [ ] Different animals will have litters of different sizes, but at the end of the pregnancy timer there will be always a birth. (Single females won't have pregnancy timer active by default, so acquiring a "meeting" of a pair will require a bit of work that deserves a reward). _expected mostly json changes_
- [ ] In case of bird species, all eggs laid by females will be unfertilized by default unless there is a male present within the trigger condition and won't hatch chicks.
- [ ] Add a stronger and nastier Z-version of the male animals for some extra cream on the top. _expected mostly json changes_

# Describe alternatives you've considered
Playing farm simulator somewhere without zombies around, but it feels too boring.

# Additional context
I know this is not one of the most requested features, but due to the major difficulties of obtaining fresh bacon in the game, it is the one that I feel strongly for. I know generally where to make some of the required changes in the json files, but I don't have good background with C++ so I would appreciate guidance or directions to files where certain functionalities can be found or functions that can be recycled from other parts of the code to be used for this. 

# Files that can be affected:
data/json/monsters/bird.json
data/json/monsters/mammal.json
src/monstergenerator.cpp
src/monster.cpp <--- try_reproduce() and .reproduces function and arguments

# Documentation that mentions "reproduction" flags or functions or objects
doc/JSON_FLAGS.md
doc/MONSTERS.md

**Comment by LyleSY** [comment]
This is something I've wanted for DinoMod for a long time. A lot of this is already possible in JSON, though we'll need a MALE and/or FEMALE flag and some code to make them work. I'm happy to do some of the JSON work on this if/when those get implemented. Farm animals and moose seem like priorities to me

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
