### ISSUE TITLE
Every choice in "You struggle to continue. Keep trying?" prompt results in taking a break.

### ISSUE THREAD

**Issue by Divreus** [CleverRaven/Cataclysm-DDA#52130]
### Describe the bug

In addition, the choices aren't exactly clear about what they're supposed to do.

### Steps To Reproduce

Go fight some zombies and get all tired out.
Try to pulp some corpses while in this state.
Pick any option when prompted to take a break.
Regardless of your choice, you will start catching your breath until your stamina is full or a zombie wanders close enough to interrupt you.

### Expected behavior

The choices between resting before continuing, continuing while winded, and stopping the action should function properly, and preferably be more labeled.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 2f54703 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Night-Pryanik** [comment]
Fixed by #56180.
