### ISSUE TITLE
Yrax Trifacet cannot be dazzled, scrambled, or deactivated

### ISSUE THREAD

**Issue by CayoDaves** [CleverRaven/Cataclysm-DDA#52142]
### Describe the bug

when performing the iron safari mission, you are tasked with deactivating a Yrax Trifacet robot. However when shooting it with a dazzle rifle or hitting it with a scramble grenade, there is no effect applied - it will continue to shoot, engage, and run away from the player as if nothing happened. When cornered, even after being hit with a scramble grenade, the robot cannot be interacted with.

### Steps To Reproduce

spawn a player with a dazzle rifle and scrable grenades
spawn a Yrax trifacet
shoot or hit the yrax with a dazzle rifle or scramble grenade
try to interact with the yrax to deactivate it

### Expected behavior

expected behavior is for the robot to be dazzled with the dazzle rifle and unable to engage the player. with the scramble grenade expectation is that it will be temporarily friendly, and both should allow the player to approach and deactivate the robot

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 594fd67 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills]
]

### Additional context

This is happening because the creature does not have the ELECTRONIC flag. when applying the ELECTRONIC flag to the .json file, the robot behaves as intended.

**Comment by jim-huynh** [comment]
It's in Creature.cpp, line 790.

The bot probably still should have the electronic flag added though, or some commentary added to state that it's intentional that you cannot scramble the bot in the json for future reference.

**Comment by Maleclypse** [comment]
@John-Candlebury Is this still occurring/intended?

**Comment by John-Candlebury** [comment]
Yeah it should get the "ELECTRONIC" flag.
