### ISSUE TITLE
Bash / pierse melee damage drops to minimum for no reason

### ISSUE THREAD

**Issue by Farmabear** [CleverRaven/Cataclysm-DDA#52159]
### Describe the bug

i have a character with 10 str and combat knife for no reason damage reduced to 1 and 2-3 when crits 

there were moments when i was hitting scientist zed with knife for 16-30 damage and after recieving any hit it drops to 1 

### Steps To Reproduce

1. Just start hitting zeds from save scientist or crawling zombie recive 1 damge with combat knife or even unharmed with barehanded broken cyborg

### Expected behavior

Damage has no unexplained drawdown

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: cbd8876 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

### Additional context

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7305107/save.zip)

**Comment by hexagonrecursion** [comment]
~I am sorry, but I am unable to open your save file archive - it appears to be corrupted.~ I have figured it out - you have uploaded a .rar file with a .zip extension. Please use the .zip format in the future: .rar has [legal complications](https://en.wikipedia.org/wiki/RAR_(file_format)#Creating_RAR_files).

I can not reproduce your bug. I get ~15 dmg on a quick strike and ~30 on a crit.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: eacb7d9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

**Comment by hexagonrecursion** [comment]
One possibility is that your arms got too damaged to be able to hold the combat knife. If your HP is too low on both arms, you can't wield a knife (or many other items). You simply drop the knife on the floor and your damage drops with it.

In this scenario you get the following chat messages:
* "You are too damaged or encumbered to fight effectively"
* "Your combat knife tumbles to the concrete floor"
