### ISSUE TITLE
Necroboomer leaves a revivable corpse on death

### ISSUE THREAD

**Issue by Abexis** [CleverRaven/Cataclysm-DDA#52157]
![Screenshot_20211007-005037_Cataclysm DDA (experimental)](https://user-images.githubusercontent.com/37454559/136347011-67806a32-26fe-4096-b39b-ee776174993a.jpg)
### Describe the bug

When a necroboomer dies, it explodes while simultaneously leaving a revivable corpse. 

This means that when two necroboomers are in close proximity, they can revive each other on death (as well as every other zed in the area) on a loop.

### Steps To Reproduce

1. Spawn Necroboomer
2. Kill said necroboomer 
3. Observe necroboomer's revivable corpse

### Expected behavior

All existing "boomers" (boomers, gasoline zombies, snotlings, etc) do not leave corpses upon death. 

The necroboomer is unique in that it both explodes while also leaving a revivable corpse upon death. I believe this to be an oversight. 

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-G973U; Release: 11; Incremental: G973USQS5GUF1; 
- Game Version: 8c55e1b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations]
]

**Comment by Maleclypse** [comment]
@kevingranade I've pulled up the discord conversation about this and there are so many threads ongoing in that area that I can't tell if you were responding that yes Necroboomers should leave a revivable corpse or that no they shouldn't.

**Comment by KorGgenT** [comment]
woop! i must have missed this ping. no, they should not be revivable
