### ISSUE TITLE
Depiction of children in game

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#52151]
# Is your feature request related to a problem? Please describe.
We now have the ability to have talking monsters, which is the feature I wanted to get before adding children to the game. However, there are some minor potential problems depicting children in a game like this: many areas have laws against depiction of violence against them, so the open-world nature of the game would cause problems with distribution. Plus it's really distasteful, which IMO is a more important issue, despite seeming small: I am already tired of the number of "hurr hurr I made a cannibal meal" posts, and adding children is likely to bring a whole new bunch out of the wordwork. On the other hand, it's very immersion breaking to have invulnerable children floating around after you drop a mininuke on the refugee center.

# Describe the solution you'd like

Adding children in general should be done by depicting them using monster, not character code. We can make monsters that talk now, and this way will use less processor power. Children aren't going to be using any of the NPC code - spawning randomly, doing goal based AI behaviour, etc - so it's not necessary to use the NPC framework for them and really just makes it needlessly complicated. Note that any child old enough to fight zombies and do construction work should be depicted as an NPC and, like Aleesha and Gunny in the refugee center, just mention in conversation that they are young.

## Preventing unnecessary kid gore

This can be done through JSON almost entirely (maybe even entirely), but it might be nice to do it in code for simplicity.

I propose that children be made invulnerable and totally unkillable. They should "despawn" - go invisible and intangible and cease reacting to anything at all - when any hostile is spotted. This could be accompanied by a comment like "little billy scurries out of sight" if we want to explain what happened to the player. When hostiles are out of sight, the child should respawn in its previous location.

Children should also have the option to be linked to a particular NPC death, so if the linked NPC dies we may hide that child permanently. This would keep children from reappearing alone if you wipe out a faction.

While most or all of this can be done with JSON and effects, it would be great if we could have a simple field for it like `"is_child": true` covering the invulnerability and disappear/reappear effects, to reduce JSON line bloat. The 'disappear for good if NPC killed' part is probably best managed through EOCs on that NPC's death.

Of note, if we go the `"is_child": true` route we could also perhaps make children fully ignored by the AI, to avoid somehow using them as bait. We could also make it difficult for the player to target them with attacks, potentially.

## Addressing common questions below

- children should not be random spawns. There's no point to that. The only reason to add them is for story building, and having them pop up randomly in an evac center wouldn't connect them to any story. Most concerns about adding children are therefore easily addressed by being judicious about where and how they're added to the map.
- Nothing stops us from hiding a child from the game and later depicting them returned as a zombie. If you wipe out the Free Merchants, or send the Hells Raiders to do it, then you *should* return to find the children also dead and returned as zombies. It's only the rather tasteless and possibly problematic-to-distribution element of actively allowing player violence against children that I would like to avoid.

# Describe alternatives you've considered
Invulnerable children - pretty bland and dumb

Dealing with edgy teenaged players that want to kill and eat child NPCs - we could make child bodies nonharvestable, which would help a little.

Not adding children - I really do need them for a fair bit of the story, the other options are more obvious than this (mentioning them but never showing them on screen eg)

# Additional context
Starting to think about the free merchant basement here. It would also be nice to find children in the world on occasion, if used carefully.

Edit to add: The hyperbolic reactions are unnecessary, please. This is a discussion thread, not a PR.

**Comment by Fris0uman** [comment]
So with this solution when Joe Mcdeathlord hit a kid with their machete they'll get a message about the kid hiding and the kid desapears?
Also having kid tied to other NPC means they can't exist as random encounters?

**Comment by leemuar** [comment]
Im relatively new player and it's just my opinion, but: I have an impression about CDDA project as "as realistic and logical as it can be". I've seen a lot of passion and fights in issue comments about certain features being rejected because they were not right for the game principles of logic and realism. And I appreciate that, I think generally it adds a lot to the immersion game provides, the freedom of action.

Unkillable, godlike, magically disappearing kids would be immersion breaking. We have zombie children, but real children can not die, can not be attacked by monsters? Sounds kinda counterintuitive to me. Partly because children are vulnerable, and we care a lot about them exactly because they can damage themselves very easy and we as human raze fear to lose them. Their vulnerability is the biggest reason we care about them.

If I have to choose between keeping that immersion and general idea of "logic and realism" in the game or to have kids around - I will choose not to have kids at all.

**Comment by I-am-Erk** [comment]
@leemuar for my own opinion, it's just kinda gross and tiresome. There are, as I've outlined, some practical considerations but they're not pressing. I know I am far from the only person who considers violence against children to be a rather particular trigger, since it's a lot less abstract than the usual player edgy behaviours.

**Comment by I-am-Erk** [comment]
Aaaand we made it one comment.

**Comment by Squishums** [comment]
> I didn't really read or think about this, but I feel I should give you my opinion

Not reaching the same conclusions as you doesn't mean that people didn't read or think about it. What did you expect from a discussion thread other than opinions?

* If your children are killable, you give player a reason to care about their life, and you open up your narrative design space to include antagonist children. There is room for emergent storytelling here.

* If your children aren't killable, your design space is basically set dressing and a cheap tool for pulling some heartstrings when storylines dictate it. There is no room for emergent storytelling here and they may as well not be represented in the game.

I feel like if your narrative ideas are in conflict with game mechanics (i.e. I want children, but I need to make a bunch of weird unrealistic concessions to get them comfortably into the world), you should reevaluate your narrative ideas. Would you seriously approve a mechanic that needed those kinds of concessions from a new contributor?

**Comment by I-am-Erk** [comment]
> Not reaching the same conclusions as you doesn't mean that people didn't read or think about it

The problem isn't people not reaching the same conclusion as me. It's that there isn't discussion here, just repetition of largely two points with the odd bit of useful feedback. The noise ratio was too high, probably partly because my initial issue post was too specific on a single point and thus didn't invite sufficient alternative discussion, and partly because it got shared with an inaccurate tagline to a much larger and less development-centric audience. Since the discussion isn't providing any of the information I was looking for, I closed it.

Things I was looking for:
- discussion of different ways children can be depicted in game and various available options
- discussion of ways within the code to implement various ideas for depicting children in game.

Things I was not really looking for:
- discussion of whether or not people want children in game at all
- people's general yay/nay opinion of the rough concept of not being able to kill children with no specific thoughts about implementation
