### ISSUE TITLE
Blood from Draw Kit Differs from Butchery

### ISSUE THREAD

**Issue by Owlfren** [CleverRaven/Cataclysm-DDA#52160]
### Describe the bug

When using the blood draw kit to draw blood a corpse it produces a different type of blood than bleeding the corpse does. 

### Steps To Reproduce

1: Use a blood draw kit on a corpse.
2: Bleed a corpse using the butcher menu
3: Compare the blood types

### Expected behavior

For the blood to match given that it is from the same source.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.F-2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    No Fungal Monsters [No_Fungi],
]

**Comment by hexagonrecursion** [comment]
related: #53481

**Comment by hexagonrecursion** [comment]
@wapcaplet confirmed
* mon_cow
    * bleed -> animal blood
    * blood draw kit -> cow blood
    
    ![DeepinScreenshot_select-area_20220121064126](https://user-images.githubusercontent.com/52621858/150461788-4dab2cc8-e521-444e-ae4c-a99324dcc144.png)

* mon_zombie
    * bleed -> tainted blood
    * blood draw kit -> zombie blood

    ![DeepinScreenshot_select-area_20220121064331](https://user-images.githubusercontent.com/52621858/150462000-d59d3bb4-6d3b-4ee8-9686-2e536906c65f.png)

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 62a046c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by LeahLuong** [comment]
By the power of Science! the draw kit is able to more accurately determine the blood's type.
