### ISSUE TITLE
Mutant Organs cook incorrectly

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#52166]
### Describe the bug

Mutant Organs (from bugs) cook like regular meat, inheriting the calories and vitamins (and lack of toxins) of regular meat but still having the "gross mutant meat" -5 morale tag. Though it cannot be cooked on its own like other organs, which itself is also an issue, its strange properties can be observed by making canned or pickled offal. (On an unrelated note there is no 3L variant of pickled offal unlike most other canning and pickling options). Upon being crafted into canned or pickled "offal", the resulting item has the same calories and vitamins of cooked meat (except for being "unappetizing mutant meat") and says it is made of cooked meat, although it occasionally produces results with half the calories. This is likely because it copies from Offal, an obsolete food that copies from regular meat, but I don't know exactly how the cooking system works under the hood.

### Steps To Reproduce

1. Attempt to cook Mutant Organs. Canned, Pickled, Sausage, any works.
2. Observe through the powers of alchemy/Blob Magic the organs are transmuted into mysterious gross but nontoxic ordinary animal meat.

### Expected behavior

Mutant Organs should have their own "cooked" version, and properly translate into various prepared versions. 

### Screenshots

![offal1](https://user-images.githubusercontent.com/56016372/136458958-6c26adfc-7d17-4b2d-95ae-42aa00a79a77.PNG)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: bfe9028 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap],
    Blaze Industries [blazeindustries]
]

**Comment by Owlblocks** [comment]
I just wrote a commit fixing mutant bug organs so they no longer have parasites after being cooked (I decided to write this in here, rather than starting a separate issue, because it's related to @kwl01skz 's fix. :)

**Comment by hexagonrecursion** [comment]
Confirmed. I have butchered a giant ant (id: mon_ant) and got the "mutant organs" item. I then used it to cook "cooked mutant bug organs". The result did not report as toxic.

![DeepinScreenshot_select-area_20220104131406](https://user-images.githubusercontent.com/52621858/148043923-443384d2-4140-426a-a377-33fa802835e8.png)
![DeepinScreenshot_select-area_20220104131612](https://user-images.githubusercontent.com/52621858/148044111-01f3fb77-5cb5-4212-9293-056726ca3c68.png)

**Comment by snipercup** [comment]
Same issue as in #35573. It enherits the NUTRIENT_OVERRIDE flags. The fix should be the same, so adding the 
`"delete": { "flags": [ "NUTRIENT_OVERRIDE" ] },`
property to the cooked mutant bug organs should fix it. Although I wonder if it should copy-from mutant_bug_organs->offal->meat in the first place
