### ISSUE TITLE
'force unarmed' does not apply to 'smash'

### ISSUE THREAD

**Issue by Adomatic** [CleverRaven/Cataclysm-DDA#52175]
### Describe the bug

If you want to fight with something fragile in your hands, you 'force unarmed'.

If you find yourself having to smash something when you have something fragile in your hands, and you 'force unarmed', you should use your feet, elbows, etc to do so rather than, say, the 3 liter bottle of lamp oil you're holding in your hands.

### Steps To Reproduce

Wield something silly
Select 'force unarmed' from the martial arts menu
's'mash something

### Expected behavior

Unarmed damage to the things smashed

### Versions and configuration

Mac 0.F-2

**Comment by LeahLuong** [comment]
I brought a similar issue up in #52001 with regards to Taekwondo. "Good" to see the issue isn't simply isolated to that martial art. Seems the devs might prefer you having to find out about this interaction the hard way and subsequently spend the action points to empty your hands before making unarmed attacks that may or may not include the use of your hands.
