### ISSUE TITLE
fake items versus pseudo items for furniture?

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#52185]
### Describe the bug

Is it a bug, a feature request, or a discussion (which can't be created by outsiders currently)?

Currently the game has both fake items and pseudo items, and they seem to serve the same purpose, even though some of them are defined both ways (and I don't know if both actually work ... at least one from each group does work).

I noticed this when working with base camp expansions, and found that much of the furniture needed for base camp crafting recipes are defined both ways.

### Steps To Reproduce

1. Compare CDDA\data\json\furniture_and_terrain\furniture-tools.json with CDDA\data\json\items\basecamp.json.
2. See that much furniture is defined in both places:
    - f_forge's rock_forge_pseudo vs fake_forge
    - f_anvil's anvil vs no match
    - f_still's still vs no match
    - f_kiln_empty's char_kiln vs fake_char_kiln
    - f_metal_kiln_empty's char_kiln vs fake_char_kiln (2->1 relation for kiln)
    - f_arc_furnace_empty's arcfurnace vs no match
    - f_smoking_rack's pseudo_char_smoker vs fake_char_smoker
    - f_metal_smoking_rack's char_smoker vs fake_char_smoker (note different token for metal smoker)
    - f_forge_rock's rock_forge_pseudo vs fake_forge (2->1 relation for forge)
    - f_clay_kiln's kiln_pseudo vs no match
    - f_arc_furnace's fake_arc_furnace vs no match
    - f_drill_press' fake_drill_press vs no match
    - f_tablesaw's fake_tablesaw vs no match
    - f_mitresaw's fake_mitresaw vs no match
    - f_bandsaw's fake_bandsaw vs no match
    - f_router's fake_router_table vs no match
    - f_planer's fake_planer vs no match
    - f_jointer's fake_jointer vs no match
    - f_hydraulic_press' fake_hydraulic_press vs no match
    - f_heavy_lathe's fake_power_lathe vs no match
    - f_air_compressor's fake_air_compressor vs no match
    - f_manual_tire_changer's fake_tire_changer vs no match
    - f_butcher_rack's butchery_rack_pseudo vs no match
    - f_metal_butcher_rack's butchery_rack_pseudo vs no match (2->0)
    - no match vs fake_fireplace
    - no match vs fake_stove
    - no match vs fake_drop_hammer

### Expected behavior

- No duplication of functionality.
- Consistent naming of functionality (rather than a random mix of no specific indication, pseudo attached to the front or end, and fake attached to the front.

### Versions and configuration

Exists in a recent experimental, but the inconsistency seems to have been present for a long time.
OS is not applicable as it's a matter of the game's own JSON definitions.

### Additional context

Is there a technical reason for the split, or is it a matter of development of parallel features?

It seems as if the furniture-tools.json file is more complete, so if there is no technical reason for the split it looks like everything could move there and basecamp.json could be removed.

It would also be useful to use a common naming scheme for this kind of functionality.

Note that legacy aspects have to be taken into account. Thus, names currently used to produce functionality in existing blueprints would need to remain supported as deprecated names.

**Comment by ProfoundDarkness** [comment]
It's been a while and there are some big gaps in when I was paying attention... As I understand it the fake stuff was added in to allow for the NPCs to do recipes.... it's connected to crafting and how NPCs can't craft on their own as yet... except as part of a faction camp which employs those fake tools as well as special recipes hidden from the player.  Normal (player) crafting has a LOT of complexity hung off of it while recipes using the fake tools have a lot of that complexity dropped.

Again, take that with a big ol' grain of salt.  ... Also #51941 could be an interesting read.
