### ISSUE TITLE
Overhaul vehicle construction; proficiencies and skills used

### ISSUE THREAD

**Issue by ClipClopBoom** [CleverRaven/Cataclysm-DDA#52200]
# Is your feature request related to a problem? Please describe.
Over time the vehicle system has evolved into more of a catch-all for all large constructions, and with the proficiency system some of the skills needed are probably due an overhaul.

# Describe the solution you'd like
A greater skills base for part manipulation dependant on material, as it seems disingenious that a survivor can be an expert at assembling a motor vehicle from scratch but lack the welding proficiencies for a basic metal construction through the crafting system.

For example; if the proficiencies system could be married up to vehicle assembly, then for example repairs could be affected by Principles of Welding, and Installation by Welding. Carpentry could be used for wooden parts, electronics with on-board systems and so on.

# Describe alternatives you've considered
With the proficiencies system and the investment in time and resources to train up a survivor as a competent machinist, it does call into question why mechanics couldn't be used as a proficiency in itself and most vehicle work require fabrication (with mechanics involved with engines and the like). This would likely involve a substantial rewrite and make migration very difficult if not impossible.

# Additional context
I have a lot of ideas around how the vehicle system could be made both more deep but more balanced to move away from the cargo cube/deathmobile style of play, but want to split it across more precise smaller issues as I consider them; I would like to try and contribute to this rather than just come across as demanding, if that is how it might look; Long time player here and really want to chip in and pick C++ back up at the same time.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
