### ISSUE TITLE
Displace NPC followers

### ISSUE THREAD

**Issue by Entity-y** [CleverRaven/Cataclysm-DDA#52215]
# Is your feature request related to a problem? Please describe.
NPCs are always where I need to be, I can talk to them to swap positions or push away but this is unnecessary key presses.

# Describe the solution you'd like
Walking into a friendly following NPC will automatically swap positions, or push them away if player is sprinting, without bringing up the dialog menu.

**Comment by SariusSkelrets** [comment]
It could do the same for friendly creatures, like slimesprings

They’re always in the way

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
