### ISSUE TITLE
Prompt to swap characters before sleeping

### ISSUE THREAD

**Issue by Entity-y** [CleverRaven/Cataclysm-DDA#52246]
# Is your feature request related to a problem? Please describe.
Can't switch to follower when speeding up time because the UI become locked until the avatar finishes the task.

# Describe the solution you'd like
Before starting any activity that passes an extended amount of time ( such as reading, crafting, and sleeping ), ask to swap to an available follower only if one exists and if the follower isn't already engaged in an activity.

# Describe alternatives you've considered
Unlocking certain UI functions like the faction menu, character screen, and debug menu to always be available during tasks.

**Comment by Entity-y** [comment]
Another QoL feature would be to have a notification in the message box when an NPC follower finishes their task.

This would let the player know that they can switch back to that other character if they so choose.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
