### ISSUE TITLE
Adaptive traits / achievement perks

### ISSUE THREAD

**Issue by Entity-y** [CleverRaven/Cataclysm-DDA#52268]
# Is your feature request related to a problem? Please describe.
Traits are static and will never change unless the player mutates.

# Describe the solution you'd like
Making traits adapt to what the character does in game, what they've been through, and what they've accomplished. This could use, and expand upon, the existing achievement system to reward the character with traits by achieving specific milestones.

I'll name a few examples, most of these traits would come and go based on playstyle and circumstances, others are granted by reaching certain milestones.

- Fleet-Footed/ Slow Footed: Determined by dexterity and the amount of time spent running, use it or lose it scenario.
- Strong Knees/ Bad Knees: Carrying heavy loads for long periods of time grants strong knees, crippling leg injuries causes bad knees.
- Indefatigable/ Languorous: Staying active and managing stamina well will reward indefatigable, staying dormant for long periods of time gives the languorous trait.
- Fast, Slow, Poor, Imperceptive Healer: Determined by the amount of blood in the body, calories, and health stat.
- Quick/ Ponderous: Similar to fleet and slow footed, goes by dexterity and time spent running or not running for long periods of time
- Tough/ Flimsy/ Glass Jaw: Tough is influenced similar to the healer traits, flimsy and glass jaw caused by crippling head and torso(instead of outright dying from this characters would become incapacitated for a chance at recovery with the help of NPC).
- Psychopath/ Pacifist: Default starting as a pacifist, after killing so many creatures become a desensitized psychopath.
- Fast Reader/ Slow Reader: Determined by intelligence and from reading or not reading for extended periods of time.
- Weak Scent/ Strong Scent: Bathing or showering would grant weak scent, over days without cleaning this becomes strong scent.
- Addiction Resistant/ Addictive: Determined by persistent drug use or not using drugs at all.
- Substance Tolerance/ Lightweight: Same as addictions.
- Good Memory/ Forgetful: Intelligence determines memory.
- Food Intolerances: Not eating a type of food for extended periods of time makes the body briefly intolerant.
- Accomplished Sleeper/ Insomniac: Sleeping on a set schedule would make falling asleep faster, where as persistently waiting until dead tired would cause insomnia, also heavy stimulant and depressant use would shift these traits.
- Good Hearing/ Poor Hearing: In addition to perception, being exposed to silence or loud noises for a length of time.
- Strong Back/ Bad Back: Strength determines carry weight, exercising or lack of could also influence this.
- Cannibal: Eating a lot of human flesh would grant this trait.
- Light Step/ Clumsy: Dexterity determines movement, could also be influenced by leg hp.
- Stimulant Psychosis: Always happens with heavy stimulant use, unless a tolerance has built up through frequent use.
- Masochist/ Pain Resistant/ Pain Sensitive: Start off being sensitive to pain, after being subjecting to large amounts of pain start building up a resistance, eventually becoming masochistic.
- Less Sleep/ Sleepy: Stimulant and depressant use and staying on a consistent sleep schedule.
- Animal Empathy/ Animal Discord: Have pets and play with them helps understand animal body language and how to act around wild animals, discord would come from killing animals from hunting or by sport.
- Fast Learner/ Slow Learner: Determined by intelligence and use of substances.
- Packmule/ Disorganized:  Determined by perception.
- Hoarder: Be at volume limit for extended periods of time.
- Poison Resistant: Frequent exposure to poisons.
- Infection Resistant: Time spent having an infection.
- Outdoorsman: Time spent being and sleeping outside, setting up camps, exposure to the elements.

# Describe alternatives you've considered
More perks granted through achievements.

Having a system similar to Fallout where leveling up lets you choose new perks.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
