### ISSUE TITLE
Anti-glare compensators not working with acetylene torch

### ISSUE THREAD

**Issue by Torres84f** [CleverRaven/Cataclysm-DDA#52276]
### Describe the bug

The CBM description says that it works as welding goggles and you can work with any welding equipment except for the task of bringing down a shut tight metal door, if you have a working acetylene torch and you try and take said door down a message pops saying you need goggles for that -_-

### Steps To Reproduce

1.- Install said CBM
2.- Try and use the acetylene torch to destroy/unweld a metal door
3.- A message pops up saying you need welding goggles to do that

### Expected behavior

Should work as the description says

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 1d946db [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    DinoMod - UndeadPeople Tileset [DinoModUDP],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Useful Helicopters [useful_helicopters]
]

**Comment by Saicchi** [comment]
Then since the requirements for welding changed.
https://github.com/CleverRaven/Cataclysm-DDA/blob/b8ea90af13e2c3f948997848a292910c3c1f685a/src/iuse.cpp#L4847
Set the required level to `1`
