### ISSUE TITLE
Cannot harvest some harvestable crops

### ISSUE THREAD

**Issue by Kordian459** [CleverRaven/Cataclysm-DDA#52286]
### Describe the bug

Some plants I have sowed are not harvestable even if they appear as such.

As for now I have tested this plants in an "harvestable" status
>dahlia
>carrots
>cucumbers
>chili pepper
>sugar beets
>potatoes
>bee balm

At the moment only potatoes and bee balm look harvestable, even though without the usual prompt "you want to harvest... Yes / No"

The other crops are not interactable: when you [e]xamine them the game says "there is nothing that can be examined nearby"

### Steps To Reproduce

1. seed a plant (eg. chili pepper)
2. fertilize it
3. wait some ingame days till it becomes harvestable
4. try to harvest it by [e]xamining it
5. game will report "there is nothing that can be examined nearby"

### Expected behavior

I expected to be able to harvest plants who figure as harvestable.

### Screenshots

<img width="1920" alt="pepper" src="https://user-images.githubusercontent.com/16650638/137320070-6f1a9d19-facf-419b-9be2-75bea61f29a6.png">

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: b8ea90a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    Mining Mod [Mining_Mod],
    Mythical Martial Arts [MMA],
    No Fungal Monsters [No_Fungi]
]

**Comment by Kordian459** [comment]
Very strange: sometimes if I [e]examine certain plants from one direction (eg. [e]+LEFT ) crops can't be harvested but if I [e]xamine from another direction (like [e]+RIGHT) crops get harvested. Not always working, seems totally random to me.

**Comment by ZulDjinn** [comment]
Tested some versions, the bug appears from this version https://github.com/CleverRaven/Cataclysm-DDA/commit/a0cdf82bf08528b9a8664aecb33622991752d6a6 .Replacing both "aggie_plant" instead of a "harvest_plant" in the furniture-domestic_plants.json file fixed it.
