### ISSUE TITLE
Canned Offal from mutant innards have 0 toxin

### ISSUE THREAD

**Issue by TheDefend** [CleverRaven/Cataclysm-DDA#52287]
### Describe the bug

canning organs and lung from mutants result in 0 toxin

### Steps To Reproduce

Crafting Canned Offal

### Expected behavior

Same amount of toxins from the material used or maybe half of it

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Generic Guns [generic_guns],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Vanilla Additions [Graphical_Overmap_SDG],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Owlfren** [comment]
Canning mutant lungs from a humanoid mutant resulted in 100% toxicity. Given that the output is 2 units and 8 go in, and in this case they have 25% toxins each, output is as expected. Will check a few others later though, just to make sure.

**Comment by Owlfren** [comment]
Mutant liver, kidney, lung and organs have been tested by being spawned and also harvested through butchery. All but organs behave as expected, that one creates a 0% toxin version. I can't see why by just glancing at the JSON but think we can consider the issue confirmed at least.

**Comment by RenechCDDA** [comment]
Resolved as of c94dc03
