### ISSUE TITLE
Allow copy-from to use an array of entries

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#52293]
# Is your feature request related to a problem? Please describe.
`copy-from` is a potent tool for creating object inheritances, saving us a lot of JSON lines and allowign changes to an abstract JSON object to be passed to its inheritors.

Monsters are very complex JSON objects, and growing more complex. Since many of them are combinations of features of each other, it is currently impossible to make a decent JSON inheritance structure that doesn't still require duplicating a fair bit of information.

# Describe the solution you'd like
Allow copy-from to specify an array of parents, loaded in order. For example

```json
"copy-from": [ "mon_zombie_base", "mon_police_armour_template", "mon_electric_template" ]
```
This would first load mon_zombie_base. Then it would update it with the armour values and weakpoints in police_armour_template. Then it would add electric immunity and special attacks from electric zombies.

```json
"copy-from": [ "mon_zombie_fat_base", "mon_police_armour_template", "mon_electric_template" ]
```
This would create a monster identical to the one above, except with some of the core details changed because we started with a fat zombie.

As far as I can tell this should be a fairly simple change.  Kevin says that to prevent recursion, we should prevent anything with multiple inheritances of its own from functioning as a parent. I think that's reasonable, I wouldn't need it for my own purposes and can't see why we would.

1. A first pass would probably just add the rules to add the stats from one and then the next to create the final values using regular copy-from code. 
2. A second pass, it would be nice if `abstract` entries could specify `relative`, `delete`, `extend`, and `proportional` *without a parent*. So, the "mon_police_armour_template" might specify `"relative": { "armor_bash": 6 }`, and whatever parent you called would get its pre-existing bash armour increased, if it had any.
3. Somewhere in here we might want to kill the `cannot assign explicit value the same as default or inherited value` error when doing multiple copies-from, since it isn't very helpful in this context.

Of note, we may need to make sure "looks_like" behaves reasonably. I would expect it to work as though each layer of copy-from was applied after the other. So in the above examples, we'd look for a sprite for `mon_electric_template`, then for `mon_police_armour_template`, then for `mon_zombie_base`.

# Describe alternatives you've considered
I can keep doing it as I'm doing it but it's a lot of JSON, and inheritance is good.

We could consider making multiple copy-froms require `abstract` rather than `id` for the entries, which would reduce the risk of duplicated entries throwing an error.

We could define "templates" as a separate thing, so there is a base `copy-from` of a single type and then a second entry like "copy-templates" that specifies an array of `template` objects to include. that may be easier to accomplish 2 above, IDK.

# Additional context
This would be very powerful. We could specify things like monster equipment or attacks in individual templates and glue 'em together to create new things. 

This is definitely a gateway to designing a framework where monsters could mutate procedurally by applying new templates to themselves, which would be awesome. You want that, right? we all want that. coooode thiiiiis.

This would also be helpful in recipes, allowing us to make two nearly identical recipes with slightly different tools and times, eg. for using a different toolset to be done quicker, but still requiring the same basic ingredients and knowledge.

**Comment by jbytheway** [comment]
On an implementation level, this is probably not going to be as easy as you might think. I suspect it would require some major surgery to the way we load data.

The thing is, copy-from doesn't copy the JSON data, it copies the C++ object, which has all the values set. So whichever thing you listed last on the list of patent items would just overwrite everything else. We don't keep track of which fields were loaded from JSON and which were defaulted.

**Comment by I-am-Erk** [comment]
> On an implementation level, this is probably not going to be as easy as you might think. I suspect it would require some major surgery to the way we load data.
> 
> The thing is, copy-from doesn't copy the JSON data, it copies the C++ object, which has all the values set. So whichever thing you listed last on the list of patent items would just overwrite everything else. We don't keep track of which fields were loaded from JSON and which were defaulted.

The concept is that the subsequent entries would be abstracts, and for the data structure to make any sense they'd presumably have different portions of the data. So, it's fine if they overwrite it... One section would add things like weight and volume, hp, speed, then the next would add weakpoints and armour, and the next attack data, for example.

**Comment by jbytheway** [comment]
I understand the concept; I'm just saying that's not how it works internally, currently.  Every abstract has every field, regardless of which ones were specified in JSON, and they would all get copied.  Changing that will be complicated.

I think a better approach might be to define a new thing, lets call it a template, which is a collection of JSON fields rather than a complete object.  And applying a template is mostly equivalent to just inserting those JSON fields into the object using the template, with the exception that any particular field is ignored if a later template or the object itself defines a field of the same name.

**Comment by I-am-Erk** [comment]
We've had some better ideas for how to do this since I wrote this
