### ISSUE TITLE
Graphical overmap - Tiles with extras show differently than tiles without extras

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#52290]
### Describe the bug

Any map tile with map extras has a ? on it, at least with RetroDays overmap tiles.

### Steps To Reproduce

1. Turn on Graphical Overmap.
2. Select your favorite tileset
3. Look around until you find some map extras
4. Open the map and turn off map notes.

### Expected behavior

I expect tiles with extras to be notated the same way as tiles without extras.

### Screenshots

![image](https://user-images.githubusercontent.com/2125926/137357537-f3ab1b54-8ecf-436e-ab44-aa4093e4018a.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 95019f2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations]
]

**Comment by olanti-p** [comment]
This is a matter of waiting for tilesets to catch up with https://github.com/CleverRaven/Cataclysm-DDA/pull/51664, or implementing something akin to `looks_like` support for map extras.

Neither UltiCa nor RetroDays have sprites for map extras yet; the question marks seen in this issue are "missing tile" indicators.
