### ISSUE TITLE
Crash to desktop if you start too many games

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#52300]
### Describe the bug

If you repeatedly start a character and then die, the game will eventually crash to desktop while creating the world. This typically only occurs if you start multiple characters, one after the other, without quitting out of the game at any point. This crash is intermittent - I have seen it occur in as few as two runs, and as many as 6 to 8, but it does eventually occur unless you quit out of the game before starting a new run.

### Steps To Reproduce

1. Press "Play Now" on the main menu to create a character quickly.
2. Kill your character.
3. Repeat this process until the game crashes with a segfault. This usually occurs on the screen that says "Please wait while we build your world", but I have also seen it occur as a world is resetting because the last character in it has died.

It seems that if the character actually does stuff before they commit suicide, this occurs more quickly.

### Expected behavior

I expect the game to not crash if I'm bad at it. That's just a little silly.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 95019f2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7354977/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7354978/debug.log)

**Comment by AcidAntOnAMinefield** [comment]
I need to add to this that upon dying and starting with a new character - whether the game crashes or not - it seems like the game "removes" selected mods from the World settings. Specifically it removes custom made "no triffids" and "no zombie animals" mods I put together based off of other existing blacklisted mods (essentially copy-pasted the code and changed the relevant entries to reflect the things I want to see blacklisted.)

**Comment by Inglonias** [comment]
In game version 1384c38 [64-bit], this is now occurring after two games, without fail.

**Comment by wapcaplet** [comment]
I could not reproduce this, trying various scenarios:

- "Play Now!", QYY, repeat
- "Random Character", QYY, repeat
- "Play Now!", QYY, then Preset Character / Last Character

Each time, I left the world intact. I tried leaving one or two saved characters alive in the same world, as well as none (using QYY on the last character in the world, then starting another character in the same world). No crashes occurred.

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-4108-gfa916867f5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Inglonias** [comment]
Further testing reveals that I don't know the meaning of "without fail".

It seems the best way to reproduce this crash on my end is to actually try to play, last a few hours, and then make another preset character with the same settings.

To prove I am not lying, here is a crash log from last time this happened.

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7622597/crash.log)
[Last Character.template.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/7622600/Last.Character.template.txt)

**Comment by Maleclypse** [comment]
```22:38:11.597 WARNING : opendir [./save/Stanwood/mods] failed with "The system cannot find the path specified.".
22:38:20.847 INFO : Loaded tileset: Chibi_Ultica``

This is where my attempt to preset with the last character failed.

**Comment by Inglonias** [comment]
I haven't seen any crashes in the last two or three days of heavy play. If nobody else has seen this crash for a while, I'll close this issue.

**Comment by Inglonias** [comment]
Closing this issue. If this is still happening, leave a comment and I'll re-open it.

**Comment by mqrause** [comment]
It's still happening, but it's also the same issue as #53103, so it's not really a problem if it stays closed.

To reproduce:
1. `play now (fixed scenario)` (just `play now` probably works, too)
2. move to the next overmap
3. die
4. `play now (fixed scenario)`
5. crash

**Comment by Inglonias** [comment]
Unable to reproduce in version 9da956a

**Comment by mqrause** [comment]
I was using version dcda8fd with the steps above.

**Comment by Inglonias** [comment]
I'll re-open the issue out of an abundance of caution, though I am not seeing this crash myself.

**Comment by Inglonias** [comment]
Yeah, I know. I used the debug menu's teleport overmap function. Did you just walk the whole way?

**Comment by mqrause** [comment]
Ah, right, if you teleport, you still have to move a step afterwards (and possibly before?).

**Comment by Inglonias** [comment]
I tried again on version 9da956a. Still no luck reproducing the crash.

Another thing that doesn't help matters is that I reinstalled the game because I swapped from remyroy's launcher to qrrk's Catapult launcher. I can't think of any other reason why you would still be experiencing this crash and I would not.

My advice would be to create a fresh install of the game in another directory and try to reproduce the crash there. Even if it does not continue to occur, we still have yet to discover its root cause.

**Comment by BrettDong** [comment]
If you compile the game with Address Sanitizer and Undefined Behaviour Sanitizer, I expect you can 100% reproduce the crash.

**Comment by mqrause** [comment]
I literally downloaded the then most recent version and used it for nothing else than testing this. Just tested it again with `play now` and it actually doesn't work with that. It's still 100% with `play now (fixed scenario)`, though.

**Comment by mqrause** [comment]
From the sounds of it, undefined behavior might be the keyword here.
