### ISSUE TITLE
Let players set a default martial art

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#52313]
# Is your feature request related to a problem? Please describe.
Getting the most out of your martial arts is kind of a pain. Any time you switch to an off-style weapon, you have to manually change your style or lose all your MA benefits, even if you have an appropriate style - which is particularly galling because every character has Brawling, a decent style that works with every weapon.

In addition to being mechanically annoying, it just feels weird. As if you'd forget how to break a grab while holding a knife because you didn't flip on the "Krav Maga" switch in your brain.

# Describe the solution you'd like
Give players the ability to set a 'Default' style that will be used if they're wielding a weapon that doesn't work with their primary style. Set it to 'Brawling' by default.

I would also like to suggest the ability to set a primary armed style and a primary unarmed style. This would be helpful for unarmed specialists who want to have a backup armed style and still have access to Brawling for random other weapons. Doubt that's a lot of people, but I'm one of them. Mainly adding this because it seems like it would be pretty easy to tack on if you're already doing the other stuff.

# Describe alternatives you've considered

- Just replace No Style with Brawling. This would solve the majority of the problem for the majority of players. But some players would prefer to have a style appropriate to their backup weapon, or want to use no style at all. Since I don't think it would be _much_ more work than simply hardcoding it to Brawling, letting the player choose seems correct.
- A system that detects which weapon you're wielding and automatically selects the most appropriate martial art you know. Don't like this one because it would require a lot of both backend and UI work, especially because it would have to have some sort of manual priority system to resolve conflicts anyway. It would also be complicated and prone to error, for marginal upside.
- Letting the player set which martial art to use with each weapon individually. This would actually be a really neat feature, especially if implemented in addition to my main suggestion. But it would again be a lot of work, and a basic two-tier priority system would solve 98% of the problem.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
