### ISSUE TITLE
Moving a non-pulped zombie corpse from a container to an open space, and then interrupting it, duplicates the corpse.

### ISSUE THREAD

**Issue by zachary-kaelan** [CleverRaven/Cataclysm-DDA#52320]
### Describe the bug

Moving the corpse causes it to instantly resurrect on the spot you moved it to, if you stop the action, and then puts a duplicate corpse underneath it. 

### Steps To Reproduce

1. Have a non-pulped zombie corpse in a space where it cannot resurrect.
2. Wait until the corpse is ready to resurrect.
3. Using advanced inventory, move it to an open space.
4. The corpse will instantly resurrect, prompting you to stop interacting with inventory.
5. Select "Yes".
6. The corpse will be moved and resurrected at the same time, creating a duplicate.

### Expected behavior

I expect the corpse to resurrect without creating a duplicate.

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.F-2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    Mining Mod [Mining_Mod],
    More Survivor Stuff [more_survivor_stuff],
    Bionic Slots [cbm_slots],
    Stats Through Skills [StatsThroughSkills],
    Mythical Martial Arts [MMA]
]

**Comment by hexagonrecursion** [comment]
I could not reproduce this bug. I used a zombie dog corpse. Using AIM to move it from a large tactical backpack to a tile nearby results in one resurrected dog and no extra corpses.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 9473cf6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
