### ISSUE TITLE
Power armor can't be (a)ctivated from the inventory menu

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#52348]
### Describe the bug

Power armors can't be turned on by selecting them in the inventory and pressing 'a' to activate. Doing this gives the message "You don't have any items with registered uses" and then an "Execute which action?" menu with greyed-out options, as if you had activated an empty container. It still activates as expected if you press 'a' from the standard play mode to bring up the 'activate' menu and select it from there.

I think this happens to any item that has both pockets and an activation feature, because something similar happened with a piece of CRIT gear when I was testing it, but I currently can't think of any items like that in vanilla except for power armor. Presumably this has something to do with recent improvements to containers accidentally overriding the (a)ctivate function on containers that are also supposed to have other functions.

### Steps To Reproduce

1. Spawn in Field Combat Exoskeleton, UPS and Heavy battery.
2. Wear armor, pick up and reload UPS.
3. Go into the (i)nventory, select the exoskeleton and attempt to (a)ctivate it and note that you get the message about registered uses insted of turning the armor on.
5. Exit out of the menus
6. Open the (a)ctivate menu and select the armor. Note that it turns on.

### Expected behavior

Choosing 'activate' from the inventory menu should turn the power armor on.

Maybe there should be some sort of option to open the "activate something in this container" function instead, since you might still want to do that, but it has to be possible to activate the armor's own functions through the inventory menu.

### Screenshots

![image](https://user-images.githubusercontent.com/5107449/137730610-e4d184b9-10c5-493f-a234-dac164bde7f8.png)
![image](https://user-images.githubusercontent.com/5107449/137730634-5ea171fb-9553-4181-8cef-3866cb1edc0e.png)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: c9d5870 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by HalfRetro** [comment]
same thing happens with blood draw kit
