### ISSUE TITLE
Recipes in "Good" AAA Guide Not Showing Up

### ISSUE THREAD

**Issue by LeahLuong** [CleverRaven/Cataclysm-DDA#52354]
### Describe the bug

There are several recipes (4, I think) titled "Stuff THE MAN doesn't want you to know about" which appear in the book's description but do not show up in the crafting menu. RDX is another recipe from this book with the same problem. Saltpeter may have this problem because none of the 3 entries I have in my crafting menu references the book. Other recipes like the bootleg explosives do refer to AAA Guide in my crafting menu. The commonality amongst the 3 problem recipes I mentioned is that their names appear in brown text in the book's description, although only the 1st "Stuff . . . " recipe is brown, the others are grey. I believe white text means memorized & grey means not, but I'm not sure what brown text signifies.

Perhaps the "Stuff . . . " recipes refer to things that were removed from previous versions of the game, like the control laptop. If so, wouldn't it be better to remove them from the AAA Guide description to avoid confusion?? What else could THE MAN be trying to hide from us??

### Steps To Reproduce

Get that book and look.

### Expected behavior

I expected that Annual Anarchist Anonymous level would increase, because all other skills can increase in level.

### Versions and configuration

Android 0.F-2 Tiles English vanilla

**Comment by estebandellasilva** [comment]
Liverlicous recipes for kids or whats it called haved recipe names that dont match the recipes which they represent
This is proably intended

**Comment by RenechCDDA** [comment]
> That still doesn't explain the RDX & saltpeter recipes. AAA names those, they are components in other recipes, & yet I lack any RDX recipe on searching & none of my 3 saltpeter recipes refer to AAA whereas the bootleg explosive recipes do.

RDX shows up just fine once you have the required skill level. Keep in mind that the (disguised) AAA guide requires *10* applied science to learn it, as opposed to 8 from chemical reference - classified.

Similarly, saltpeter requires 7 as opposed to 4 otherwise, etc.

Your character is simply not skilled enough to learn them from the (disguised) AAA guide.


> Falsely naming recipes seems simply terrible from pretty much any perspective. Is your in-game character really just assembling things a book tells them to w/out knowing the end goal?? We as players of the game should have some inkling of what these recipes are; the crafting menu is overwhelming enough as it is w/out hiding stuff. This seems like shoddy gameplay design at best or malevolence on the part of the devs at worst.

Please don't assume things like "malevolence". What seems like a good idea one day can have unintended impacts, like the extremely unintuitive recipe listing you're mentioning.

**Comment by jharg42** [comment]
Brown text recipes are ones you don't meet the skill requirements to unlock yet.  As mentioned above, the requirement can vary by book for the same recipe, and I believe that recipes are always unlocked from books based on your level in the primary skill of the recipe, completely independent of what skill the book trains when you read it, or how much you've read the book (beyond the initial "read" required to see what's in it).

I'm not sure if 0.F-2 differs from current experimental on the recipes in that particular book, but the 3 "hidden" recipes I see currently are for napalm, gelled gasoline, and flamethrower fuel, with napalm almost certainly being the one that appears brown for you, as I'm seeing 7 applied science needed to use the napalm recipe out of this book, while the other two only need skill 2 to use.

The recipe naming is certainly obtuse for players, but it sounds like the underlying mechanics are still working properly.

**Comment by LeahLuong** [comment]
Thanks for filling me in about the brown-text recipes. I don't assume the worst when it comes to this game's devs because I know the game is free & it's worked on by people who really care about its direction. That said, I do think this part of the game could be improved.

When a recipe is above your char's skill level, they can still attempt it & learn something from it. I have several of these on my WEAPONS/MODS list; they appear in yellow text to warn you they are likely to fail. Having brown-text recipes on top of yellow-text ones seems extraneous. Are brown-text recipes really so arcane the char can't even attempt them?? I get that AAA Guide is probably not as clearly written as chemical reference but it might be better to represent this in-game by having a higher failure rate when attempting recipes referencing the lower-quality text.

Brown-text recipes add another possibility for confusion and remove options for char advancement. I'd like to see them done away with and have yellow-text recipes altered as per my suggestion above in order to replace them.

Also, I believe my comments regarding the "Stuff . . . " recipes still stand; it's silly the char would know what these recipes do when the player does not.
