### ISSUE TITLE
Find Source of Robot mission error

### ISSUE THREAD

**Issue by jeffplata** [CleverRaven/Cataclysm-DDA#52373]
### Describe the bug

After accepting the Find Source of Robots mission from the refugee center, the error message provided below occurs. The mission is recorded for action but there are no coordinates making it a technically failed mission.

EDIT: Retried/reloaded several times, always error.

 ```
DEBUG    : Unable to find and assign mission target exodii_base_x0y3z0.

 FUNCTION : cata::optional<coords::coord_point<tripoint, coords::origin::abs, coords::scale::overmap_terrain> > find_or_create_om_terrain(const tripoint_abs_omt&, const mission_target_params&)
 FILE     : src/mission_util.cpp
 LINE     : 251
 VERSION  : 7afb487
```
![image](https://user-images.githubusercontent.com/29348635/138125504-ac772d1e-cb11-47d2-9363-07503721cd74.png)

### Steps To Reproduce

1. From the attached save, complete the Find Informant mission. 
2. Go to the Representative
3. Ask for another mission; he will give you the Find Source of Robots mission
4. Accept ("Ok, I'll do it.")
5. Error

### Expected behavior

Mission should be logged for action with coordinates

### Screenshots

![image](https://user-images.githubusercontent.com/29348635/138126071-58483d4f-794c-4c95-abbd-dc7fbca4f02c.png)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 7afb487 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Hope [no_hope]
]

**Comment by hexagonrecursion** [comment]
Possibly fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/55400
