### ISSUE TITLE
Peeking up/down stairs is having weird effects

### ISSUE THREAD

**Issue by FrozenTearCDDA** [CleverRaven/Cataclysm-DDA#52379]
### Describe the bug

I have noticed in the experimental version cdda-windows-tiles-x64-2021-10-08-1504 that peeking was not showing the area it was supposed to show, adjacent to the stairs tile, but a random location nearby. It happened both when peeking up or down. I thought it might be a mod's fault, but I tested it without any and the problem still happens. Upadting the game to cdda-windows-tiles-x64-2021-10-17-2032 also did not solve that issue.

### Steps To Reproduce

Save is right next to the stairs, just peek up.

### Expected behavior

I expected to see the tiles seen in screenshot #3, but saw the tiles as in #2.

### Screenshots

Before climbing stairs: 
![stairsbug01](https://user-images.githubusercontent.com/15993955/138191812-7b7a1bd7-1089-4df5-ab1e-6ce8785b2256.png)

Using peeking to look up: 
![stairsbug02](https://user-images.githubusercontent.com/15993955/138191818-41ad4b00-6983-47a0-9d1b-a033598d6a51.png)

Actually climbing the stairs: 
![stairsbug03](https://user-images.githubusercontent.com/15993955/138191825-53633a9a-6d4c-4dbd-95c6-42e3028509af.png)

Save file: [Elk Plain.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7385162/Elk.Plain.zip)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 5c41748 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by FrozenTearCDDA** [comment]
> What's the location? Peeking up/down non-aligned stairs shows you the tile directly above/below you. The only non-aligned stairs left are in old labs, lab basements and subway stations, otherwise something's broken with mapgen.

I think the location might be the problem then, as I played more, this was not happening at regular houses and other city locations, but it happened to a previous character in abandoned mines, maybe older locations have it more often.

**Comment by epsimpson** [comment]
> What's the location? Peeking up/down non-aligned stairs shows you the tile directly above/below you. The only non-aligned stairs left are in old labs, lab basements and subway stations, otherwise something's broken with mapgen.

I have one in a city house, my NPC got stranded downstairs because of it, map generated after you made that comment.  Is it worth a new issue?  I can generate a save file in that location if it's of interest.

**Comment by wapcaplet** [comment]
See also #49162
