### ISSUE TITLE
Heated vehicle tanks to keep liquids from freezing.

### ISSUE THREAD

**Issue by zachary-kaelan** [CleverRaven/Cataclysm-DDA#52387]
I'm always frustrated when fluids in my vehicle freeze, and the only way to defreeze them is to uninstall the tank, use the hotplate, install _another_ tank in its place, then empty the original tank into the vehicle. And it will just freeze again later.

There is already a refrigerated tank, so why not a heated tank? It could either keep the liquid hot at all times, or just keep the liquid from freezing. I noticed that the hotplate only heated it up to cold, "because that's how I like it", so if there are liquids that are preferable hot, the tank could either set the temperature based on what's inside of it, or be split into a "heated tank" and an "antifreeze tank".

I've considered keeping the car heated, but that's 700W for every vehicle transporting freezable liquids and will make the character too warm while inside if not in the right clothes.

**Comment by zachary-kaelan** [comment]
@jim-huynh Ah so literally any engine or motor. I don't know if an electric motor keeping stuff from freezing is realistic, especially since it doesn't appear to drain any battery when the vehicle is still, but it's good to know.

The alternative I've found and will be using is building an underground kitchen, because I realized that things don't freeze down there unless in a freezer.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
