### ISSUE TITLE
Re-accessing Scenario tab resets selected scenario

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#52384]
### Describe the bug

In Vormithrax's latest-but-one CDDA video, he demonstrates a bug during character creation wherein re-accessing the scenario-select tab after reaching the summary screen resets the selected scenario to Evacuee, which has the knock-on effect of ruining your build and obligating you to re-create it.

### Steps To Reproduce

1. Begin creating a new character.
2. Reach the summary screen before loading in.
3. Return to the Scenario tab.

### Expected behavior

Scenario expected to remain as selected.

### Screenshots

Begin watching Vormithrax's video from [this timecode](https://youtu.be/wuHLQ2TKdbQ?t=60). Visual evidence of the bug is at 2:55.

### Versions and configuration

Version string in the video shows as 8256058, which would appear to correspond to PR 52232 and therefore `cdda-experimental-2021-10-11-0810`.

### Additional context

The source of the error can only be `newcharacter.cpp`, but even after staring at it for a while, I can't work out what could be causing it.

**Comment by ToxiClay** [comment]
I specifically searched and didn't manage to spot this. Damn it.

**Comment by Night-Pryanik** [comment]
Resolved by #52413.
