### ISSUE TITLE
OH GOD IT WON'T STOP: invalid effect type id mabuff:buff_krav_maga_static1

### ISSUE THREAD

**Issue by Nameless-Survivor** [CleverRaven/Cataclysm-DDA#52412]
### Describe the bug

This error pops up at game loading and during game after a small period of time passes (EX: dragging items, crafting, sleeping, waiting, etc). Option to (I)gnore does not seem to function. Changing active martial art to Judo does not prevent error. 

DEBUG    : Excessive error repetition detected.  Please file a bug report at https://github.com/CleverRaven/Cataclysm-DDA/issues
            invalid effect type id mabuff:buff_krav_maga_static1

 FUNCTION : const T& string_id<T>::obj() const [with T = effect_type]
 FILE     : src/effect.cpp
 LINE     : 75
 VERSION  : 20aaf46

Here are some of the most recent lines from the debug log.

[ Previous repeated 37 times ]
11:09:01.737 ERROR : src/effect.cpp:75 [const T& string_id<T>::obj() const [with T = effect_type]] invalid effect type id mabuff:buff_krav_maga_static1
11:09:01.850 ERROR : src/effect.cpp:75 [const T& string_id<T>::obj() const [with T = effect_type]] invalid effect type id mabuff:buff_krav_maga_static1
[ Previous repeated 199 times ]
11:09:02.440 ERROR : src/effect.cpp:75 [const T& string_id<T>::obj() const [with T = effect_type]] invalid effect type id mabuff:buff_krav_maga_static1
11:09:02.580 ERROR : src/effect.cpp:75 [const T& string_id<T>::obj() const [with T = effect_type]] invalid effect type id mabuff:buff_krav_maga_static1
[ Previous repeated 24 times ]
11:09:02.709 ERROR : src/effect.cpp:75 [const T& string_id<T>::obj() const [with T = effect_type]] invalid effect type id mabuff:buff_krav_maga_static1
11:09:02.851 ERROR : src/effect.cpp:75 [const T& string_id<T>::obj() const [with T = effect_type]] invalid effect type id mabuff:buff_krav_maga_static1
[ Previous repeated 50 times ]
11:09:02.978 ERROR : src/effect.cpp:75 [const T& string_id<T>::obj() const [with T = effect_type]] invalid effect type id mabuff:buff_krav_maga_static1
11:09:03.121 ERROR : src/effect.cpp:75 [const T& string_id<T>::obj() const [with T = effect_type]] invalid effect type id mabuff:buff_krav_maga_static1
[ Previous repeated 5 times ]
11:09:03.140 ERROR : src/effect.cpp:75 [const T& string_id<T>::obj() const [with T = effect_type]] invalid effect type id mabuff:buff_krav_maga_static1
11:09:03.281 ERROR : src/effect.cpp:75 [const T& string_id<T>::obj() const [with T = effect_type]] invalid effect type id mabuff:buff_krav_maga_static1
[ Previous repeated 5 times ]
11:09:03.300 ERROR : src/effect.cpp:75 [const T& string_id<T>::obj() const [with T = effect_type]] invalid effect type id mabuff:buff_krav_maga_static1
11:09:03.442 ERROR : src/effect.cpp:75 [const T& string_id<T>::obj() const [with T = effect_type]] invalid effect type id mabuff:buff_krav_maga_static1
[ Previous repeated 12 times ]
11:09:03.510 ERROR : src/effect.cpp:75 [const T& string_id<T>::obj() const [with T = effect_type]] invalid effect type id mabuff:buff_krav_maga_static1
11:09:03.958 ERROR : src/effect.cpp:75 [const T& string_id<T>::obj() const [with T = effect_type]] invalid effect type id mabuff:buff_krav_maga_static1
[ Previous repeated 5 times ]
11:09:03.977 ERROR : src/effect.cpp:75 [const T& string_id<T>::obj() const [with T = effect_type]] invalid effect type id mabuff:buff_krav_maga_static1
11:09:05.658 ERROR : src/effect.cpp:75 [const T& string_id<T>::obj() const [with T = effect_type]] invalid effect type id mabuff:buff_krav_maga_static1
[ Previous repeated 1444 times ]

### Steps To Reproduce

Cause any time period to pass longer than a single action. EX: Craft, sleep, eat, drag items on the ground.

### Expected behavior

Not have constant errors, and presumably whatever the Krav Maga buff is supposed to be doing.

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 20aaf46 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills]
]

**Comment by hexagonrecursion** [comment]
I could not reproduce this bug.

I loaded a save file provided here https://github.com/CleverRaven/Cataclysm-DDA/issues/52385#issue-1032417346 (a duplicate of this issue) https://github.com/CleverRaven/Cataclysm-DDA/files/7375690/Benjamin.zip and waited for several hours. Unless the missing mods are masking the issue, I think this was fixed.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: e49949d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Slots [cbm_slots],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    No Rail Stations [No_Rail_Stations],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    No name () [],
    No name () []
]

09:11:23.1000 ERROR : src/mod_manager.cpp:33 [const T& string_id<T>::obj() const [with T = MOD_INFORMATION]] Invalid mod AftershockUDP requested
09:11:25.516 ERROR : src/mod_manager.cpp:33 [const T& string_id<T>::obj() const [with T = MOD_INFORMATION]] Invalid mod AftershockUDP requested
09:11:26.732 ERROR : src/mod_manager.cpp:33 [const T& string_id<T>::obj() const [with T = MOD_INFORMATION]] Invalid mod MagiclysmUDP requested
09:11:27.189 ERROR : src/mod_manager.cpp:33 [const T& string_id<T>::obj() const [with T = MOD_INFORMATION]] Invalid mod MagiclysmUDP requested
