### ISSUE TITLE
Items get randomly dropped from inventory while moving items into/out of inventory/switching containers

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#52422]
### Describe the bug

When picking up items, dropping items, or changing which containers items are in, random items will drop from my character's inventory. This problem causes my character to leave loot behind when I intend for her to bring it with her, and even causes her to lose important tools, even when said tools are favorited.

### Steps To Reproduce

1. Have a character with a storage container/article of clothing with storage for their inventory
2. Pick up/drop items, or change the containers items are in, until you see random items from your inventory suddenly on the ground with no explanation

### Expected behavior

I expect items to remain in my character's inventory when there is nothing that would reasonably cause them to fall from her inventory.

### Versions and configuration

09:23:00.012 :  GAME REPORT:
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version (actually windows 8.1 Pro, but the game report doesn't seem to be able to figure that out)
- Game Version: 95019f2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    XEAS [XEAS],
    Gun Cotton [guncotton],
    DinoMod [DinoMod],
    Youkai Enemies [Youkai_Disco],
    Mining Mod [Mining_Mod],
    Mole Mutation [dig_a_tunna],
    More Survivor Stuff [more_survivor_stuff],
    Mythical Martial Arts [MMA],
    More City Locations [cityside],
    No Rail Stations [No_Rail_Stations],
    Compatible Nimian Manufacture Guns [NM_wpns],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    Magiclysm No Class Limit [magiclysm_no_class_limit],
    Mutation Changes [Mutation_Changes],
    Portable Autodoc [portable_autodoc],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Useful Helicopters [useful_helicopters],
    Arcana and Magic Items [Arcana],
    return_the_nut [return_the_nut],
    Hydroponics [hydroponics],
    Cooler Versatility [coolervers],
    Chris K's Knives [ChrisKsKnives],
    Custom Spells [Custom_Spells],
    Reproduction mod [perverts],
    Custom Bionics [custom_bionics],
    Magiclysm Runes in Arcana Recipes [Custom_ArcanaRune],
    Deconstruction Plus [Deconstruction_plus],
    Core Data Changes [core_data_changes],
    Arcadia Mapgen [custom_arcadia_mapgen]
]

### Additional context

Before anyone asks, this happens regardless of how damaged the container for the items happens to be.

**Comment by wapcaplet** [comment]
I definitely had something like this happen to me. I had a favorite condom (don't judge) filled with electronic gadgets, and I think it fell out of my backpack onto the ground when I reloaded one of the gadgets (inside the inner bag) with a fresh battery.

**Comment by hexagonrecursion** [comment]
I have a save where this bug can be reliably reproduced. In that save I am wearing a hiking backpack (and nothing else - in the interest of purity of the experiment). Inside the backpack is just one item: a short rope. Under my feet is an M4 carbine. When I try to pick the carbine up my backpack becomes empty and I can see a "short rope > M4 carbine" under my feet.

[tmp.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7827751/tmp.zip)

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 4d22129 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by Lord-Helmchen** [comment]
what, apart from learning c++, can I do to help here ? I lost about 5 painstakingly assembled IFAK-pouches with assorted medical equipment in three days and am becoming really frustrated.
to make things worse, either the item drop is not announced in the message log, or it takes me longer than the log buffer to notice the pouch is gone, but either way I can't seem to find them again :-/

**Comment by wapcaplet** [comment]
> I have a save where this bug can be reliably reproduced. In that save I am wearing a hiking backpack (and nothing else - in the interest of purity of the experiment). Inside the backpack is just one item: a short rope. Under my feet is an M4 carbine. When I try to pick the carbine up my backpack becomes empty and I can see a "short rope > M4 carbine" under my feet.

Many thanks for finding a reliable reproduction case. Your save works for me to reproduce the bug repeatedly.

I think what's happening (in this particular scenario) is when you pick up the M4, the short rope in your backpack is deemed the "best pocket" to store the M4 in, for whatever reason. Then, when `item_pocket::overflow()` is called to enforce pocket capacities, this section throws causes the rope (now containing the M4) to be silently dropped to the ground:

https://github.com/CleverRaven/Cataclysm-DDA/blob/8a25ad4f33bc884ad25b3719272558dc1d2f20b7/src/item_pocket.cpp#L1513-L1522

The solution is at least two-fold:

- Add a message here, warning the player when items drop to the ground because of this
- Investigate why a short rope is considered the best place to put an M4 - is this a weird edge case, or a more general problem with containers-within-containers that happen to overflow?

The first part is easy, and I'll go ahead and make a PR for it to get the ball rolling:

![image](https://user-images.githubusercontent.com/238395/148845039-bef5c9eb-c96c-44d1-a24f-150dc401895d.png)

**Comment by Terrorforge** [comment]
I know some changes were made to the best_pocket rules in #53162 that seem to have cause containers-in-containers to get fileld when they previously wouldn't, but the original report predates that change..

**Comment by hexagonrecursion** [comment]
> * Investigate why a short rope is considered the best place to put an M4 - is this a weird edge case, or a more general problem with containers-within-containers that happen to overflow?

This is still not fixed. The bug should be reopened

**Comment by AmarinReyny** [comment]
> > * Investigate why a short rope is considered the best place to put an M4 - is this a weird edge case, or a more general problem with containers-within-containers that happen to overflow?
> 
> This is still not fixed. The bug should be reopened

Also, there's the fact that the problem I'm experiencing occurs when doing things like emptying wallets and putting animals in pet carriers, and usually, the items that are being dropped aren't even the containers having things being put into/taken out of therm.

**Comment by wapcaplet** [comment]
> > > * Investigate why a short rope is considered the best place to put an M4 - is this a weird edge case, or a more general problem with containers-within-containers that happen to overflow?
> > 
> > 
> > This is still not fixed. The bug should be reopened
> 
> Also, there's the fact that the problem I'm experiencing occurs when doing things like emptying wallets and putting animals in pet carriers, and usually, the items that are being dropped aren't even the containers having things being put into/taken out of therm.

Can you provide steps to reproduce the use case(s) you have experienced? I am pretty sure the new message will handle those cases too, but I can only test them if they are reproducible.

**Comment by AmarinReyny** [comment]
> Can you provide steps to reproduce the use case(s) you have experienced? I am pretty sure the new message will handle those cases too, but I can only test them if they are reproducible.

1. Pick up a bunch of wallets dropped by zombies.
2. Empty all of them

There will sometimes be wallets that drop to the floor. So far, the wallets that have dropped to the floor have been ones that have not been emptied yet, in my experience.

As for the pet carriers:

1. Have at least two pet carriers in your inventory, with one occupied and one not occupied
2. Use the non-occupied pet carrier to pick up an animal

The occupied pet carrier has a pretty big chance of dropping to the floor, for me - around 50%, as mentioned before.

Also, side note, I have experienced something somewhat similar to the rope bug others seem to be experiencing. While it hasn't led to anything being dropped, I have noticed that a lot of smaller items, upon being picked up, have a tendency to go into belts I've picked up from zombie drops. Not only that, but attempting to unload the items from the belts has a significant chance of putting the items back into the same belt they're being unloaded from.

**Comment by Zireael07** [comment]
> We know now that it's a general problem with containers, and we have a message in the log when it occurs - do you propose we keep this issue open until all possible edge cases with randomly dropped items are sorted out and fixed?

Unless there is an open issue about "randomly dropping items", yes, this should be reopened imho.

**Comment by wapcaplet** [comment]
The phrase "randomly dropping items" is a misnomer; the items are not dropped randomly, but for specific reasons (being too big or heavy to fit in their container. Before #54268 these drops occurred silently; now you should be seeing log messages about them.

I'm ok with reopening this, but I would like to avoid the possibility of conflating a bunch of different things in the same issue, as well as the possibility of having an issue with no clear definition of "done". So I need to ask, what do you *expect* to happen in these cases?

You can't hold onto the item in the container where it is; it either needs to be dropped, or you need to move some things around in your inventory (and/or drop something else) to make room for it to stay where it is. Would you rather be prompted to wield it? Or to be prevented from doing whatever action that led to the item being dropped? I am not clear on what you want to happen, aside from being informed by log messages when something is dropped.

**Comment by AmarinReyny** [comment]
I can confirm that the larger container that had everything in it had the capacity for everything that I expected to be/remain in it at every stage, before and after capturing animals, before and after unloading wallets, and so on. I've experienced this problem regardless of how full the larger container was or was not.

One thing I will say, though, is that, with the wallets, I do tend to go a bit rapid-fire on the keys when emptying them - I'll even drop other containers from the inventory just to cut down on how tedious it would otherwise be to repeatedly press the same buttons over and over and over again. I also experience a bit of lag in my game. Do you think that it might be a result of something not registering properly due to the number of keys pressed in a short period of time during lag?

**Comment by wapcaplet** [comment]
I should also clarify, you are *still* seeing items mysteriously and silently drop to the ground, even after the messaging fix in #54268 ? There could surely be other places in the code where items drop, so if it's still occurring silently, that is definitely a problem.

**Comment by I-am-Erk** [comment]
@hexagonrecursion since you requested this be reopened, can you clarify then how you know it is not fixed?

**Comment by mqrause** [comment]
> I know some changes were made to the best_pocket rules in #53162 that seem to have cause containers-in-containers to get fileld when they previously wouldn't, but the original report predates that change..

I believe both of the checks added there should be ignored for contained pockets.

https://github.com/CleverRaven/Cataclysm-DDA/blob/2057907bb8dd952c3523b9ec141ddff8685fda93/src/item_pocket.cpp#L325-L333

They depend on the parent pocket or rather the topmost pocket of a worn item anyway.

**Comment by hexagonrecursion** [comment]
> @hexagonrecursion and @Zireael07 since you requested this be reopened, can you clarify then how you know it is not fixed?

> So I need to ask, what do you _expect_ to happen in these cases?

In the case I described above I expect the pocket overflow to not occur in the first place - M4 should be put in a pocket it can fit when I pick it up.

**Comment by hexagonrecursion** [comment]
> @hexagonrecursion and @Zireael07 since you requested this be reopened, can you clarify then how you know it is not fixed?

When I try the below steps I now get the message "Your short rope > M4 carbine falls to the ground". This should not happen - M4 should not be put in that pocket in the first place.

> I have a save where this bug can be reliably reproduced. In that save I am wearing a hiking backpack (and nothing else - in the interest of purity of the experiment). Inside the backpack is just one item: a short rope. Under my feet is an M4 carbine. When I try to pick the carbine up my backpack becomes empty and I can see a "short rope > M4 carbine" under my feet.
> 
> [tmp.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7827751/tmp.zip)

**Comment by wapcaplet** [comment]
I would suggest reporting a separate issue for "Better pockets should be chosen when picking up items", because it has very little to do with "items get randomly dropped". This is what I meant by not conflating multiple issues into one.

**Comment by mqrause** [comment]
> I would suggest reporting a separate issue for "Better pockets should be chosen when picking up items", because it has very little to do with "items get randomly dropped". This is what I meant by not conflating multiple issues into one.

In my opinion that's a questionable way to read this issue (and issues in general). "Items get randomly dropped" is a vague issue simply by using the word "randomly", so it has to do with anything that addresses that. The issue of chosing the wrong pockets is as much part of that as is the issue of messaging about it happening. Splitting up the issue once different parts have been identified is definitely valid, but arbitrarily deciding which part it is about without that is not.

**Comment by I-am-Erk** [comment]
This issue is much more specific than just "items get randomly dropped". If we allowed every issue post to remain open for every possible vague interpretation of the subject line, we would never close issues. This specific issue appears to be done, and a new issue to discuss algorithms for pocket sorting is fine.
