### ISSUE TITLE
Crash when I died

### ISSUE THREAD

**Issue by RowanRam** [CleverRaven/Cataclysm-DDA#52448]
### Describe the bug

My game some how crashed a bit after I died. I do not know if this is my sound pack or tile set or something else

### Steps To Reproduce

The crash happed after I pressed yes on the "continue to watch your death" screen.

### Expected behavior

The way that I died in-game was not specific because I was just killed by wasps.

### Versions and configuration

- OS: Windows 10
- Branch: Experimental
- Build: 10d50a8
- Platform: Windows x64
- Tile set: Ultica
- Soundpack: Basic

### Additional context

The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 10d50a8
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

  #0
    (dbghelp: @0x7ff7a8424b89[cataclysm-tiles.exe+0x1d4b89]), 
    (libbacktrace: register_frame_ctor+0x7ff666f0eb39@0x7ff7a8424b89),
    (libbacktrace: 0x7ff7a8424b89    [unknown src]:0    [unknown func]),
  #1
    (dbghelp: @0x7ff7a840e4b1[cataclysm-tiles.exe+0x1be4b1]), 
    (libbacktrace: register_frame_ctor+0x7ff666ef8461@0x7ff7a840e4b1),
    (libbacktrace: 0x7ff7a840e4b1    [unknown src]:0    [unknown func]),
  #2
    (dbghelp: @0x7ff7a840e6df[cataclysm-tiles.exe+0x1be6df]), 
    (libbacktrace: register_frame_ctor+0x7ff666ef868f@0x7ff7a840e6df),
    (libbacktrace: 0x7ff7a840e6df    [unknown src]:0    [unknown func]),
  #3
    (dbghelp: @0x7ff7a8c5e752[cataclysm-tiles.exe+0xa0e752]), 
    (libbacktrace: register_frame_ctor+0x7ff667748702@0x7ff7a8c5e752),
    (libbacktrace: 0x7ff7a8c5e752    [unknown src]:0    [unknown func]),
  #4
    (dbghelp: _C_specific_handler+0x98@0x7ff971907ff8[msvcrt.dll+0x27ff8]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #5
    (dbghelp: _chkstk+0x11f@0x7ff971cd20cf[ntdll.dll+0xa20cf]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #6
    (dbghelp: RtlRaiseException+0x434@0x7ff971c81454[ntdll.dll+0x51454]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #7
    (dbghelp: KiUserExceptionDispatcher+0x2e@0x7ff971cd0bfe[ntdll.dll+0xa0bfe]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),

**Comment by hexagonrecursion** [comment]
In my humble opinion this bug should be closed. Unfortunately there is not enough information for useful troubleshooting. Even if we did find and fix a big that could have caused this we could not conclusively link this issue to it.
