### ISSUE TITLE
Folding bicycle transformation magic (recipe needs to be updated)

### ISSUE THREAD

**Issue by estebandellasilva** [CleverRaven/Cataclysm-DDA#52487]
### Describe the bug

Crafting a folding bike needs 

2 Steel frames, saddle, vehicle controls, foot pedal, 2 bicycle wheels and can also be disassembled into this.

The unfolded bike consists of

3 extra light frames, light wheel mount, foot pedal, wire basket, light wheel mount steerable, 2 bicycle wheels and bicycle horns (currently not craftable or i dont have the recipe)

That also means if your unfold you bike it turns from steel -> into aluminum. 

### Steps To Reproduce

make a folding bike and compare the parts it consists of folded and unfolded

### Expected behavior

Update the recepie to match the end result.

### Screenshots

![image](https://user-images.githubusercontent.com/89189872/139050115-352a7f9a-3271-4759-a4e6-a823aab7045c.png)
![image](https://user-images.githubusercontent.com/89189872/139051378-39869339-c9c8-4968-ad30-b4aefd2b225b.png)
![image](https://user-images.githubusercontent.com/89189872/139051439-0f0fbb7b-fd72-4e88-8a50-553114c9930b.png)
![image](https://user-images.githubusercontent.com/89189872/139051535-49ad7b1c-a3af-455c-a452-360808012924.png)

### Versions and configuration

OS: Windows
OS Version: 10.0 1909
Game Version: 209bf26 [64-bit]
Graphics Version: Tiles
Game Language: English [en]
Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
No Fungal Growth [no_fungal_growth],
Bionic Professions [package_bionic_professions],
SpeedyDex [speedydex],
Stats Through Kills [stats_through_kills],
Stats Through Skills [StatsThroughSkills]
]

**Comment by Inglonias** [comment]
If it were up to me, the recipe for the folding bicycle would be removed entirely and it would be treated as just another vehicle. The folding bicycle was created before foldable vehicles in general were merged into the mainline game, so the recipe itself is obsolete.

**Comment by Inglonias** [comment]
I think with the merging of #52596, this issue can be closed.
