### ISSUE TITLE
Extremely long portal storm

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#52491]
### Describe the bug

I was on a normal Spring 61 start, and on the evening of Spring 70, my first portal storm began. I do not recall getting any of the message usually associated with portal storms, e.g. about the sun winking out, at any point. I just started seeing question marks popping up all around me and saw that the weather had changed to Portal Storm. At that point I begin to crouch in my Humvee to hide from any monsters, and tried reading and crafting until the storm passed. By the time I had to turn the game off, it was early morning of Spring 79 and the storm was still raging.

However, when I started the game again this evening, I waited for a few hours, got a bunch of the "The sun is winking out" messages, and then the portal storm passed.

It's possible I just got really weird RNG, but given that I didn't get the messages and saw no monsters, I think something broke. My suspicion is that the portal storm didn't start properly for some reason, which caused it to be unable to end properly, but this was resolved on save-load. That's just speculation, though.

### Steps To Reproduce

I don't know how to reproduce this bug, except to play the game and see if it happens to you. I've provided my save file, but as I said, the issue was resolved on load.

### Expected behavior

Portal storms should not last for over a week, at least not this early in the game. Even if this was just bad RNG, there should be hard limits in place that prevent such an early storm from lasting more than say 48h at the very most, and not come closer than a few days apart.

### Screenshots

![image](https://user-images.githubusercontent.com/5107449/139111729-bdaa0a77-d176-415c-a515-e14f6da9cf65.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: bdf59dd [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Extra Mutated Scenarios [extra_mut_scens],
    Fuji's Military Profession Pack [fuji_mpp]
]

### Additional context

[French Vanilla.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7428029/French.Vanilla.zip)

**Comment by hexagonrecursion** [comment]
Hello. I got hit by something similar: #54133 - I used the debug menu to start a portal storm in one world and it affected all the worlds lasting until I quit to desktop and reloaded. Were you, per chance, experimenting with portal storms in a debugging world too?

**Comment by Terrorforge** [comment]
No, I wasn't.

But like you, I did close the game before it resolved. I don't recall if I tried just saving and loading.
