### ISSUE TITLE
Stack trace on Windows (MinGW) is incorrect

### ISSUE THREAD

**Issue by BrettDong** [CleverRaven/Cataclysm-DDA#52503]
### Describe the bug

After I upgraded MinGW build compiler to GCC 11.2, the stack trace generated in crash reports does not seem to be correct. For example, see `crash.log` in #52448 and #52329.

I thought it is because @Qrox's `libbacktrace` build in https://github.com/Qrox/libbacktrace/releases/tag/2020-01-03 is not compatible with the new compiler, so I tried to build `libbacktrace` targeting MinGW GCC 11 along with MXE toolchain (https://github.com/BrettDong/MXE-GCC/commit/b97f72e3043d113c780aab56c7c11d2c5ceaeb26). However the game compiled from this new `libbacktrace` library still exhibits incorrect stack trace problem (see my screenshot below).

### Steps To Reproduce

1. Download Windows (MinGW) experimental releases from [GitHub](https://github.com/CleverRaven/Cataclysm-DDA/releases)
2. Force a game crash in debug menu
3. Open `config/crash.log` to view the stack trace

### Expected behavior

Expect to see first two frames to be `debug_write_backtrace()` and `log_crash()`, and debug menu somewhere at the bottom.

### Screenshots

<img width="1005" src="https://user-images.githubusercontent.com/21075502/139258543-07bf2d81-874a-4502-9f72-7d479dfd2c0d.png">

### Versions and configuration

- OS: Windows 7
- Game Version: 9b861e4cc57a0c4072a0f6607722e3b82996858b

**Comment by Qrox** [comment]
Both have the same problem.
