### ISSUE TITLE
Ambient sound stacking

### ISSUE THREAD

**Issue by HalfRetro** [CleverRaven/Cataclysm-DDA#52515]
### Describe the bug

Issue with all sound packs with ambient sounds.
Ambient sounds such as Indoor, outdoor, and/or underground sounds are stacking when prompted, and stay toggled on whether I'm indoors or out. Max stack I discovered so far is 2 ambient sound loops.
**_Also the options menu for adjusting ambient sound levels is not making any affect to the ambience volume._** 
The only way to untoggle, e.g., indoor.ogg and daytime.ogg, is by going underground, 
(_or waiting for nighttime.ogg, which ends up stacking with indoors.ogg anyway_) 
but upon resurfacing the underground.ogg continues to play with daytime.ogg
(_underground.ogg doesn't seem to stack with indoors.ogg when using a mineshaft elevator to transfer between the two environments_) 
until entering an indoor environment tile, then they both toggle off and it plays indoors ambient sound, until going back outdoors and it all repeats again. 
Upon further testing, entering underground does not cause a stack with any above ground ambience, only upon exiting underground into outdoors, it stacks with the outdoor ambience.

### Steps To Reproduce

1. Load in character that is indoors during daytime
2. prompt indoors.ogg by walking around indoors
3. step outside and prompt daytime.ogg to start playing causing a sound stack of the both
4. enter an underground area such as a sewer or mineshaft, through a manhole, to prompt underground.ogg and untoggle the previous stack
5. exit underground, back through manhole, causing another sound stack with underground.ogg and daytime.ogg 
6. step into indoors environment tile, while underground.ogg and daytime.ogg are stacking, and toggle them both off when prompting indoors.ogg

### Expected behavior

I expect every time I step into a new environment such as outdoors to indoors, that the ambient sound changes to the corresponding environment and untoggles the previous ambient sound loop. Only one ambient sound loop should be active per environment.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 44f0416 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    <color_light_blue>BL9-100%-monster-resilience-version</color> [BL9_100monres],
    <color_light_red>Secronom</color> [secronom],
    <color_light_red>Secronom+ Lore Expansion</color> [secronom_lore_expansion],
    <color_red>Sierra Madre</color> [sierra_madre],
    Arcana and Magic Items [Arcana],
    Battle Maid Redux [battle_maid],
    C.R.I.T Expansion Mod [crt_expansion],
    Engineering essentials [EngineeringEssentials],
    Magiclysm [magiclysm],
    Magiclysm Revamp and Additions [magicrevamp],
    Make bows great again [bow_opness],
    More Survivors Stories [More_Survivors_Stories],
    Nechronica Redux [Nechronica_Redux],
    Pneumatic fun [pneumo_fun],
    Wandering Masters [wandering_masters],
    XEAS [XEAS],
    Add Rice [rice],
    Adurnsyl's Assorted Arms and Armour [AAA],
    Advanced Gear Goats Edition [adv_gear],
    Advanced Technologies [advtech],
    Armor Up! Survivor Expansion [ArmUpSurvEx],
    Arsenal Breach [arsenal_breach],
    Artyoms' Gun Emporium - Reloaded [Arts' Guns],
    Aftershock [aftershock],
    BioCo Content [bioco],
    Bionic Space Expander [Bionic_Space_Expander],
    Bionics Systems Recipes [bio_recipes],
    Bootleg Walkers [Bootleg_Walkers],
    CBM Equipment [CBM_Arms],
    Climate Defying Farming [climate_defying_farming],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    Expanded Archery [ExArch],
    Fallout New England [fallout],
    Flowerpot (uekibati) mod [Uekibati_mod],
    Garden Pots [growable-pots],
    Gourmand's Graces [Gourmand'sGraces],
    Gun Cotton [guncotton],
    Homestead Instruments Inc. [homestead],
    Icecoon's Arsenal [ew_pack],
    Large capacity storage CBMs [eps_cbm],
    Locked and Loaded [Locked_and_Loaded],
    Makeshift Items Mod [makeshift],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    Miscellaneous Magiclysm Expansions [demon_spider_a],
    MOD to grow tea leaves [More tea leaf],
    Modern Weapon Pack Expanded [modern_weapon],
    MST Extra [MST_Extra],
    Mythological Replicas [nw_pack],
    Nimian Manufacture Guns [NM_wpns],
    Project APEX [apex],
    Ricky's Future Armory [futurearmory],
    Rivtech Beam Swords [beamswordmod],
    The Cool Mod [cool_mod],
    The Glory Of Cereal! [CerealMod],
    Thermal Electric UPS [thermal_ups],
    Wild Living [WildLiving],
    Bug's life [Bug's life],
    Crazy Labs [crazy_labs],
    Draco's Dog Mod [DracoDogMod],
    Draco's Pig Mod [DracoPigMod],
    Jury-Rigged Robots [jury_rigged_robots],
    Modular Turrets with No Blacklist [modular_turrets_no_blacklist],
    Mutant Animals [mutant_animals],
    Mutant Insects [mutant_insects],
    Salvaged Robots [Salvaged_Robots],
    Youkai Enemies [Youkai_Disco],
    <color_light_blue>Lighter Weariness</color> [light_weariness],
    Cataclysm++ [Cata++],
    CDDA Variety Pack [ks_variety_pack],
    Hydroponics [hydroponics],
    machine [machine],
    More Survivor Notes [more_survivor_notes],
    More Survivor Stuff [more_survivor_stuff],
    Mutant NPCs [mutant_npcs_new],
    Ninja_Mod [Ninja],
    Rummaging [Rummaging],
    Vampiric Stuff [vamp_stuff],
    Vampiric Stuff + Arcana Mod Extension [vamp_stuff+arcana],
    Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
    More Locations [more_locations],
    Zet's Hair - More Locations [zets_hair_ext_more_locations],
    PKs Rebalancing [PK_REBALANCE],
    Zet's Hair - PKs Rebalancing [zets_hair_ext_pk_rebalance],
    Dorf Life [Dorf_Life],
    Morlock Village [morlock_village],
    Oa's Early Game Mutations mod [oa_early_game_mutations_mod],
    Ships From Oa Additional Buildings [Ships],
    Water Towers [water_towers],
    Whaleys TALL Buildings [whaleys_tallbuild],
    Tankmod: Revived [Tankmod_Revived],
    Necromancy [necromancy],
    Abrahms Recipes 1 [AbrahmsRecipes1],
    Merchant Mod [Merchant],
    Whaleys Hair Mod (UDP Tweaks) [WHALEYHAIR_UDP],
    Graphical Overmap [Graphical_Overmap],
    No name () [],
    No name () [],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    No name () [],
    No name () [],
    No name () [],
    No bs enemies [No_Cata++BS]
]

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/0-f-frank-release-is-here/26581/25
