### ISSUE TITLE
Thessalonian Bronze can't be repaired with welder

### ISSUE THREAD

**Issue by bombasticSlacks** [CleverRaven/Cataclysm-DDA#52521]
### Describe the bug

Cataphract armor can only be repaired with a sewing kit it seems that the welder and using bronze isn't an option.

### Steps To Reproduce

spawn cataphract leggings
look at the item and see repair options

### Expected behavior

You should be able to repair it with bronze.

### Screenshots

![image](https://user-images.githubusercontent.com/4514073/139361300-3ae52a51-1c4e-4d75-ad78-25bcbaf833a4.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 7dce252 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by I-am-Erk** [comment]
It's scale armour, welding it would be weird. Is it still using bronze as a component?

**Comment by bombasticSlacks** [comment]
It uses the custom bronze but there is currently no way to repair it with bronze. You can only use a sewing kit and leather.

**Comment by I-am-Erk** [comment]
Not requiring bronze is an oversight. Really, actually, it should require bronze lamellae, not just scrap, but I don't know how to require that if it's even possible.
