### ISSUE TITLE
A Necropolis is free of radiation

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#52523]
### Describe the bug

Despite being basically a Fallout reference and including many irradiated monsters, there is no radiation.

### Steps To Reproduce

1. Find a necropolis.
2. Go to a crater.
3. Enable radiation display.
4. There is exactly 0 radiation everywhere.

### Expected behavior

At least craters should be irradiated. Maybe also the sewers?

### Versions and configuration

- experimental

**Comment by Traple** [comment]
I want to add to this with some screenshots of being next to a crater (This is using the current experimental build):

![Next to crater](https://user-images.githubusercontent.com/5754894/159980797-f60caae8-46a0-47fe-aca0-97b45bba4c59.JPG)

This is the rad view:
![Rad view](https://user-images.githubusercontent.com/5754894/159980807-b0d19f77-16c3-4c84-b0b3-5835ea5ce35a.JPG)

If someone would be able to fix this, that would be great! Craters not giving off radiation is not fun!

**Comment by NetSysFire** [comment]
#55204, this was intentional.

**Comment by NetSysFire** [comment]
Closing because the necropolis has been removed since 2 years or so.
