### ISSUE TITLE
Turrets need to be IR based.

### ISSUE THREAD

**Issue by Chroniclerope** [CleverRaven/Cataclysm-DDA#52535]
# Is your feature request related to a problem? Please describe.
Current turret detection systems are too weak and perpetuate the problem of players being able to easily kill them for ammo.

# Describe the solution you'd like
Turrets in game should be based off turrets in real life, using FLIR and infared torches to identify targets during any time or weather conditions, rather than the visual based systems it seems to have currently.  This will solve the issue of a player being able to wait until nightfall and get within range to kill the turret with lower caliber fire arms, or even rush it down and melee it.
# Describe alternatives you've considered
Turrets could also use LiDAR to have an assured aquisition range in the game, but should also be feasible to jam or blind with the correct tools and player knowledge.
# Additional context
http://www.army-guide.com/eng/product4914.html For the real life example, here is the Super Aegis II, which mounts a selection of weapons but uses 12.7mm machine gun as a standard.  I am aware that it is not the CROWS, but it serves as a better example of what an AI guided turret is capable of.

**Comment by LeahLuong** [comment]
Yes, let's fix the problem of turrets giving too juicy rewards by making them deadlier.

**Comment by jim-huynh** [comment]
What would the proposed detection range be?  I think turrets have gone through multiple passes to balance out their deadliness with the ability for players to not 'randomly' die at 36 or 40 tiles.  This range is especially important for the 50 caliber turret where it's likely a 1-hit kill.

**Comment by l29ah** [comment]
No IR detection would save a turret from being smashed with a survivor crouched behind the wheel of a random car.

**Comment by estebandellasilva** [comment]
Also would raise  the question of you could use fire to trick the turrent?

**Comment by DavidAGi** [comment]
Yeah, i like the idear of IR. If you use it tho, hiding behind things shoud be a Realistic. 
Also, you coud add Plastic shelds, not for Combat but to cover Form the IR detection. 

But i think laider woud be more likely, in this case the turrets have to also shoot at, every large moving (humanoid) Objekt, without an ID badge. 
Or the turret shoots at everything, destroying granades (without detonation) within flight.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
