### ISSUE TITLE
Mutant lungs can be harvested from giant bugs.

### ISSUE THREAD

**Issue by Cynthius** [CleverRaven/Cataclysm-DDA#52534]
### Describe the bug

Butchered giant insects drop mutant lungs, while in real life insects have no such organs.

### Steps To Reproduce

1. Kill a giant insect (in my case, it was a Wasp Guard)
2. Use Full Butchery on its corpse
3. Examine the remains for mutant lungs

### Expected behavior

Lungs not being harvested from insects.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0ad2fdd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

I realize that this may be justified by lore, given how mutation works in-universe and the fact that insect respiratory systems cannot support creatures the size of Cataclysm's giant mutants in real life. Or that the "lungs" are simply an abstraction of respiratory systems in general, though if that's the case, I'm not sure it should be kept that way considering how actual lungs might have very different nutritional values and edibility compared to giant insect tracheae. I couldn't find any reference to this lung peculiarity in any previous issues though, so I'm filing this just in case it's a genuine oversight.

**Comment by estebandellasilva** [comment]
not sure but i read somewhere that insects breath through their skin -> if they would only grow bigger they would suffocate - which means if you didnt find the insect dead it would have some kind of lung to breath, but i may be wrong

-> There were bigger insects in history, but appearently the air had more oxygen at that time

**Comment by TealcOneill** [comment]
I think the blob would make them better at absorbing oxygen the way they currently do and not mutate lungs into every single species of bugs to make up for it.

**Comment by Scorch-Mechanic** [comment]
Mutated insects in game have "endochitin" which is some sort of handwavy version of a rigid internal support structure (y'know, instead of "bones"). I suppose it could be in the spirit of things for mutant insects to mutate some kind of "lungs".

**Comment by LeahLuong** [comment]
It's kinda like how giant cockroaches can give live birth & lay eggs. They wouldn't be "mutant" wasps unless they had extra organs, right?? QED.

**Comment by TealcOneill** [comment]
> Mutated insects in game have "endochitin" which is some sort of handwavy version of a rigid internal support structure (y'know, instead of "bones"). I suppose it could be in the spirit of things for mutant insects to mutate some kind of "lungs".

Man am I dumb, I knew the meaning of exo and endo but somehow thought the endochitin was just the name for the stuff attaching the exoskeleton to the body. Not that it was actually some kind of psuedo-endoskeleton. I think that kind of thing would be fine as long as it had a different name than just mutant lungs since that is confusing.

**Comment by Cynthius** [comment]
I figure it's probably more in-line with established lore if the blob made adjustments to their existing respiratory system than to spontaneously evolve mammal/lizard-like lungs. Doesn't mean they can't have lungs of their own, but I'd expect them to be a little different from the lungs of creatures that normally have them, a different item at the very least. Whether we wanna stick with the spiracle-tracheae system and modify it to believably function, or give them pseudo-lungs instead both seem fine to me, I just don't expect whatever they do end up with to be 1:1 analogous with other creatures. Are there any non-insect mobs that use "mutant" parts?

**Comment by Scorch-Mechanic** [comment]
All "mutated" creatures drop mutant meat, fat, and organs. Whether it's a spideer or a wyrd spider. The various mutant meats even have a variety of (ha!) "flavor text" that change depending on chance and what kind of mutant you salvaged them from. For example:
```
        "id": "mutant_bug_lung_1",
        "text": "You're pretty sure this is lung tissue.  It looks like a lung from a larger mammal, like a dog, but instead of a few distinct lobes, it has dozens of lobes arranged in sheets.  Strange spindles and gnarled tumescences dot the surface."
      },
      {
        "id": "mutant_bug_lung_2",
        "text": "You're pretty sure this is lung tissue.  It has a vaguely wing-like shape, with a series of nodules around what would be the trailing edge of the 'wing'.  A cluster of quills in each corner of the organ held it to the bug's carapace like clasps."
```
Are the two possible descriptions for mutant lungs sourced from mutated insects and mutated arachnids.

**Comment by Cynthius** [comment]
Hmm... What threw me off was the fact that it's explicitly labelled as a "lung", and even our survivor can somehow identify it as lung tissue just from looks, which feels a bit too concretely "normal" than I'd expect for a mutated insect respiratory system. Comes off less like "alien lung" and more like "lung that's turned alien", if you know what I mean.

Is it only the flavor text that changes between variants? It still seems odd to me that insect "lungs" would have the same stats and values as mammal ones, even if they're both mutated.

**Comment by Stone94** [comment]
I'd just rationalize the giant bugs mutating lungs as a means to deal with the issues caused by their growth in size. Their original respiratory system wouldn't be able to provide enough oxygen to their cells because they would be too far apart (according to some quora answers). most arthropods breath through muscular sphincters  in their body called spiracles which force air through tracheae, and some arachnids use both trachea and book lungs which are similar to lungs, so in order for the giant bugs to get enough oxygen it would make sense for them to undergo some respiratory evolution.

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3926130/ evolution in air breathing. **(covers many kingdoms)**
https://pubmed.ncbi.nlm.nih.gov/26820263/ respiration in spiders.
https://www.quora.com/If-insects-were-as-big-as-dogs-would-humans-still-be-able-to-dominate-Earth **while the topic is different, the reasons why it isn't supports my rationalization**

**Comment by Maleclypse** [comment]
Stone's answer is the correct one.   There was a discord discussion about this when the mutant lung organs were added to insects.
