### ISSUE TITLE
Crafting menu practice leaves "in progress" items.

### ISSUE THREAD

**Issue by Cynthius** [CleverRaven/Cataclysm-DDA#52532]
### Describe the bug

When using the practice feature in the crafting menu, I'm left with "in progress" items representing the practice itself lying on the ground.

### Steps To Reproduce

1. Start a Practice
2. Abort it partway through (or when prompted because of proficiency gain, which also causes this)
3. Check the ground below you for the physical manifestation of your unfulfilled commitment.

### Expected behavior

I expected training sessions to not leave a physical object, at the very least not an "in progress" craft with no weight or size, but a concrete physical location.

### Screenshots

![Screenshot 2021-10-29 141709](https://user-images.githubusercontent.com/15305144/139483318-e9e43878-4b20-498b-8018-d4092bc6ae45.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0ad2fdd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Xpyder** [comment]
My expectation would be that if the practice consumes items (like with carpentry) it would leave behind a practice item with a reverse percent (to indicate how much use it has left, and when it hits 0 it turns into scraps), and if it doesn't consume any materials for it to not leave behind an item.

arguably the direction of the % of the practice item is arbitrary and probably doesn't actually need to be changed (though a clearer naming might be valuable).

Which just leaves the "practice that doesn't consume materials" case.  My guess would be that for now it generates and uses a dummy item, but it should delete that dummy item when practice is over/cancelled (or make it invisible and flag it for cleanup by the garbage collector [or equivalent] )

**Comment by LeahLuong** [comment]
But don't you want your world populated by physical manifestations of your unfulfilled commitments, just like real life??

**Comment by Cynthius** [comment]
> 
> 
> My expectation would be that if the practice consumes items (like with carpentry) it would leave behind a practice item with a reverse percent (to indicate how much use it has left, and when it hits 0 it turns into scraps), and if it doesn't consume any materials for it to not leave behind an item.
> 
> arguably the direction of the % of the practice item is arbitrary and probably doesn't actually need to be changed (though a clearer naming might be valuable).
> 
> Which just leaves the "practice that doesn't consume materials" case. My guess would be that for now it generates and uses a dummy item, but it should delete that dummy item when practice is over/cancelled (or make it invisible and flag it for cleanup by the garbage collector [or equivalent] )

Many of the Practices don't consume any items, at least at low levels. I should also point out that you earn exp while working on the Practice, not just each time you complete one, so there's not much reason to have a "resume" option, at least for the ones I've tried. If a practice does consume items though, I can see why we'd want an "in-progress" version. The best solution is probably to just have the dummy item deleted or not created in the first place for Practices with no item cost.

**Comment by Inglonias** [comment]
@I-am-Erk Apologies for the ping, but can we close this issue? There's a merged PR covering it.

**Comment by Fris0uman** [comment]
We probably still want practice that consume components to be resumable through in progress item so I'm closing this as solved, feel free to reopen an issue if there's still something wrong specifically about in progress items of practice recipe that consume components
