### ISSUE TITLE
Batch crafting long cordage pieces results in an error > Attempting to craft heavy or big things while hand is occupied (by straw basket) results in an error

### ISSUE THREAD

**Issue by RosaEscura** [CleverRaven/Cataclysm-DDA#52542]
### Describe the bug

Tried to batch craft long cordage pieces and got a weird error.

### Steps To Reproduce

1. Batch craft long cordage piece or activate already existing batch craft of them
2. Get error message and craft never starts or finishes

### Expected behavior

No error message appears and craft completes

### Screenshots

![image](https://user-images.githubusercontent.com/38073849/139523504-3345e2ba-abf3-4a51-8044-106388d9a9ba.png)
![image](https://user-images.githubusercontent.com/38073849/139524088-b3b7d9ce-43b4-4313-99bb-54068680be50.png)

### Versions and configuration

- Win 10
- Version bc28921
- Tiles
- English
- Only default mods: Dark Days Ahead
[Aspen Hills.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7445996/Aspen.Hills.zip)

**Comment by Tamiore** [comment]
Can't reproduce on de98d1d

![batch_cordage](https://user-images.githubusercontent.com/61312205/140098700-ac210fef-6532-4299-98e2-6b9250295e5f.png)

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: de98d1d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    No Hope [no_hope],
    Rural-Only Mapgen [ruralbiome]
]

**Comment by RosaEscura** [comment]
I revisited my save and figured this out. I had a straw basket occupying one hand which prevented me from doing this batch craft. It normally prints out a message "Something you are wearing hinders the use of both hands" when you try to pick up an item that requires both hands (like the batch craft of long cordage pieces) but instead it bugs out and prints that error for some reason.
If someone can figure out why that happens and fix it that'd be great.

**Comment by Night-Pryanik** [comment]
Can't confirm on latest experimental as of 01 November 2024.
