### ISSUE TITLE
Introduce furniture clearing tokens

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#52544]
# Is your feature request related to a problem? Please describe.

Note: Issue edited after discussion in comments.

There is currently no way to clear terrain of "vegetation" (flowers, bushes, trees, boulders, etc.) in (base camp) construction recipes, leading to those remaining inside constructed walls/floors. The game can also place vehicles such that trees exist inside of them.

# Describe the solution you'd like

The introduction of a tile named e.g. "f_clear_furniture" that could be used in construction recipes to have the indicated tile cleared of furniture layer definitions. There is currently a null furniture tile "f_null" that does nothing when specified which can have some uses, but there's no way to remove things that are already there.

My use case would be to clear a construction site of obstructions before starting construction so the vegetation (etc.) doesn't remain stuck in the construction constructed later, but there's also a potential use case for removing preexisting furniture in buildings to free up floor space or simply rearranging the furniture to fit a modified design.

# Describe alternatives you've considered

A much (?) more complicated but also more complete alternative would be to introduce some kind of logic that was capable of detecting these unwanted features and add the work required to remove them to the construction recipes on the fly. If that kind of logic was introduced, it ought to also include removal of of existing "terrain" (such as walls) into consideration.

# Additional context

As far as I understand, there are now two layers of "terrain" in CDDA:
- A terrain layer, using tiles named "t_<whatever the terrain is>" containing natural terrain and constructions such as walls and floor/roof combos.
- A furniture layer containing flowers, bushes, trees, bounders (of varying sizes), as well as ash and constructed things such as furniture, fireplaces, constructed kilns, etc.

It's currently possible to replace the furniture layer with something else using construction recipes (such as ash), but not clear it (and covering the construction site in ash look rather ugly). 

An example of a constructed building with a fair bit of "vegetation" remaining inside of it.
![Screenshot (37)](https://user-images.githubusercontent.com/22739822/139528241-243bf191-5e37-4749-9201-6a5a053badd4.png)

**Comment by ZhilkinSerg** [comment]
There are only two layers available currently - terrain and furniture.

**Comment by PatrikLundell** [comment]
How can furniture appear on top of boulders, if that's the case?

**Comment by Zireael07** [comment]
I believe 0.E didn't have that simplification yet - furniture used to be a weird its own thing.

**Comment by ZhilkinSerg** [comment]
> How can furniture appear on top of boulders, if that's the case (I've encountered that with 0.E2 stable)?

If boulder is terrain, furniture can be put on top of it.

**Comment by PatrikLundell** [comment]
if boulders were terrain they should have been replaced when the terrain was changed to t_dirt, and they seem to be named "f_boulder_small", "f_boulder_medium", and "f_boulder_large" based on a search for "boulder" in data/json.

**Comment by ZhilkinSerg** [comment]
If they are furniture then no other furniture can be placed on the same tile.

**Comment by PatrikLundell** [comment]
That's not what I saw, but Zireal07's suggestion that things may have changed since could explain it.

**Comment by ZhilkinSerg** [comment]
Map tiles can contain multiple items and field types, but it is not possible to place more than one of each (terrain, furniture, trap) on the same tile.

https://github.com/CleverRaven/Cataclysm-DDA/blob/de98d1d2754abadd636efa164e2aaa7be486128b/src/submap.h#L53-L63

**Comment by PatrikLundell** [comment]
After butting my head against the issue, I believe I've found that the cause of my issues is that the usage of a palette together with "rows" causes "f_null" in the palette to be treated as a no-op, while specifying "f_null" as "terrain" in an object set ("point", "line", and "square") causes it to replace vegetation and boulders (I haven't tested against "real" furniture, but assume it will work there as well).

Thus, it seems it's possible to work around the current issue, but a proper solution would be to let processing of "rows"/palettes make a distinction between not assigning any furniture to a palette character and explicitly assigning "f_null" to it. The former case ought to be a no-op, while the latter ought to be a clearing of the furniture from the tile.

**Comment by PatrikLundell** [comment]
Closed this issue in favor of bug report #52747
