### ISSUE TITLE
Allow zones in different Z-levels to continue existing

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#52549]
# Is your feature request related to a problem? Please describe.
So, it seems that, if I make a zone in one Z-level, then my character goes to a different Z-level, the zones become un-loaded. They no longer display in the Zones manager, and from what I can tell, they no longer matter for any intents or purposes until my character re-enters the Z-level in which they were placed. This means that I can't auto-sort loot between Z-levels, and NPCs can't do the same; I also suspect that it has something to do with a [bug I had previously encountered](https://github.com/CleverRaven/Cataclysm-DDA/issues/52008#issue-1012536921) in which NPCs would immediately stop disassembly work if my character changed Z-levels.

# Describe the solution you'd like
I'd like for zones in different Z-levels to continue existing and be able to matter for auto-sorting and NPC jobs.

# Describe alternatives you've considered
Never allowing myself to have a base that exists on more than one Z-level.

**Comment by PatrikLundell** [comment]
The work around I've used is to have my character drag all the stuff that should change Z levels up/down stairs and then sort it once it's on the target Z level. It's not particularly useful to have things neatly sorted on one level and then have the workshops on a different level where the things can't be seen, though.

**Comment by AmarinReyny** [comment]
> The work around I've used is to have my character drag all the stuff that should change Z levels up/down stairs and then sort it once it's on the target Z level. It's not particularly useful to have things neatly sorted on one level and then have the workshops on a different level where the things can't be seen, though.

Yeah, but that doesn't really help when I want NPCs to do the sorting for me, or for when I want NPCs to do other things when I'm not on the same Z-level as the stuff I want them to do. It's kind of hard to RP as someone trying to establish a new society in the post-apocalyptic world when my character is the only one doing anything in said society, you know?

Also, I use basements and such for things I don't really have enough room for on the surface, such as washing machines for all the zombie laundry I want to salvage usable materials from, freezers to store all the food I accumulate, expanded storage for all the extra stuff that won't fit into the storage space in the expansion workshops (because I don't want to waste an expansion on something that can't produce anything), safe places for all my rescued animals to run around in instead of being stuck in carriers, expanded living areas for all the NPCs I rescue but don't have any jobs for, and so on.

**Comment by PatrikLundell** [comment]
True, but it's the best work around I've come up with given the current system. Once I've actually hauled the stuff up/down the stairs I can then use the "normal" sorting orders to get things into their proper places (but still have to remain on that level while the work is done, as things stand now: read a book or participate in the sorting [with the attendant risk of collisions and premature aborting of the job]).
The problem there is to define a custom target zone that contains all the stuff I want at the top/bottom of the stairs (I should probably save such a custom zone definition for use both in new games and when hauling stuff out of places such as labs). Once companions have move stuff there I can then have the PC drag it up/down.

Things are slowly moving towards increasing Z level competence, so this (good) suggestion is probably going to be implemented eventually.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
