### ISSUE TITLE
Allow swapping wielded item to holster

### ISSUE THREAD

**Issue by Delta5861** [CleverRaven/Cataclysm-DDA#52557]
# Is your feature request related to a problem? Please describe.
Scenario - you are wielding a shillelagh, and wearing a back holster containing a FN SCAR-H. Note that both items are valid (individually) for the back holster. You want to switch weapons from the shillelagh to the rifle, so you 'a'pply the holster, select Draw <weapon>, and are then prompted to drop the shillelagh as you don't have room for it in your inventory despite wearing a back holster. 

# Describe the solution you'd like
Allow the player to 'switch' weapons without having to drop their current weapon, then pick it up and holster it (given they would have room for it in their inventory when wielding the new weapon).

# Describe alternatives you've considered
Leave it as-is.

# Additional context
This would mostly be for convenience, saving some extra key-presses.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
