### ISSUE TITLE
Can't gut tazer hack for parts

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#52562]
### Describe the bug

Description says "A broken tazer hack, with its propellers still and tazer inert.  Could be gutted for parts.", but you can't.

### Steps To Reproduce

Load the game, press `(`, see there's no broken tazer hack.

### Expected behavior

No inconsistency.

### Versions and configuration

16:09:31.191 :  GAME REPORT:
- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.F-3656-gde98d1d275-dirty [64-bit]
- Graphics Version: Curses
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

[2021.10.21.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7448883/2021.10.21.zip)

**Comment by l29ah** [comment]
Same for `broken green maintenance security drone`.

**Comment by RoyBerube** [comment]
Looks like recipes for these are missing in `recipe_deconstruction.json`
