### ISSUE TITLE
All morale modifiers disappeared, except for 'took antidepressant'.

### ISSUE THREAD

**Issue by epsimpson** [CleverRaven/Cataclysm-DDA#52563]
### Describe the bug

Had negative morale effects "Saw something that hurts to remember", a nightmare effect and an accidental food.  Had several positive effects including playing with pet, hot meal, and some foods.  Total morale -21.  Took an antidepressant.  Morale became -5.  Trained social skills by crafting 'social (beginner)'.

When my social skill increased, or maybe when the craft was complete, I got an error "player_morale::took_prozac is inconsistent"  (sorry, I didn't copy that actual debug message).

After continuing past the debug message (space bar), I checked morale ('v'), and all morale modifiers, positive and negative, were gone.  

Checked status effects ('@'), and all status effects, except for 'Happy', 'Took Antidepressant', and 'bandaged (poor)' were gone (heat, pain, stimulant from drinking Lotus Tea), but that could have been natural.  According to my log I turned on my vehicle cooler a couple hours earlier, and I drank 4 lotus teas over an hour before my social skill level increased, so perhaps that was enough time for that to happen naturally.

Did it also remove the effects of eating toxic foods  (I'd had some splitting headaches before reading the labels on some of my cracklings)?  Were there mutagenic or other effects unknown to me (I've had dreams), caused by handling plutonium (oops) or trying out the objects I got from Amigara Horrers (one of them did give me the message 'attract attention', and another one whose negative side effects I've never seen that I wield a lot)?

I have no save file that reproduces the status wipe, but I later attempted to use a makeshift bandage, and saw the same kind of "took_prozac is inconsistent" debug message, and I have a save file that reproduces that one.  Hopefully what caused the later debug message also cleared my morale flags.

### Steps To Reproduce

For the debug message:
1. Open included save file.
2. Apply a makeshift bandage (type 'a' 'b' hotkeys)

For the original effect (I don't know if this will work or how to try it)
1. Create a player with optimist trait and an antidepressant pill.
2. Give player the morale effects "Saw something that hurts to remember" for -40 morale, and a nightmare effect for -2 morale, total penalty -42.
3. Give player some positive morale effects (hot meal, play with pet, a couple of good foods, etc), total boost about +20, producing net morale about -21.
3. Take antidepressant.
4. Craft 'social (beginner)'

### Expected behavior

If a negative effect goes away (e.g. times out), it won't take positive effects with it.  All effects don't just disappear at once.

Debug message free.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.3 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-3654-g150bb486b9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Negative morale effects "Saw something that hurts to remember", and the nightmares, were caused by playing during a portal storm.  Fought (melee) 2 creature types, once an Impossible Shape (1 shows up on my kills) and twice something else that doesn't show up in my kills.  The 'something else' has a classic DND name - Ghasts maybe?  They appeared to pass into or through me, and I had the 'Tired' status afterwords.

The debug message I got (the reproducible one) was:

 DEBUG    : player_morale::took_prozac is inconsistent.

 FUNCTION : bool player_morale::consistent_with(const player_morale&) const
 FILE     : src/morale.cpp
 LINE     : 811
 VERSION  : 0.F-3654-g150bb486b

[AlexProzacBug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7449015/AlexProzacBug.zip)
9

**Comment by l29ah** [comment]
Reproduces for me on a fresh game on todays master; load the save and do anything: the morale status will get wiped, and you get the message.
https://tinystash.undef.im/il/5XVG2zUsBUwuWk8GY7ne1FiLpxDgzX8nHEHaXss1dMaDpUxgSarfSfRacd75S9UREPqS3ECEUHR7TTo3HiNynyPr.zip

**Comment by misterprimus** [comment]
I still get it in `ee6be48`

```
 DEBUG    : player_morale::took_prozac is inconsistent.

 FUNCTION : bool player_morale::consistent_with(const player_morale&) const
 FILE     : src/morale.cpp
 LINE     : 845
 VERSION  : ee6be48
```
