### ISSUE TITLE
Improved vehicle optics

### ISSUE THREAD

**Issue by Drew4484** [CleverRaven/Cataclysm-DDA#52574]
# Is your feature request related to a problem? Please describe.
The current camera implementation uses low power security cameras with poor optics. With the availability of high quality sensors from CROWS and other robots, a survivor could potentially integrate those into their vehicles.

# Describe the solution you'd like
The existing monster flag "MECH_RECON_VISION" currently offers night vision, IR, and increased overmap view distance. If a version of that same flag could be added for vehicle parts, a new item could be added to take advantage of the capability.

# Describe alternatives you've considered
More floodlights.

# Additional context
I can add the vehicle part, but I'm not sure where to start with the C++ portion of adding a new flag.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
