### ISSUE TITLE
"Bad Rumors" NPC Mission

### ISSUE THREAD

**Issue by LeahLuong** [CleverRaven/Cataclysm-DDA#52585]
### Describe the bug

I completed this NPC's 1st 2 missions -- kill the Jabberwock & kill 100 Z's -- & am now getting some strange behavior. I had sent the NPC to work on the ranch carpentry job while completing the 2nd mission. Upon recovering the ally, they acknowledged completion of the 2nd mission & mention hearing some bad rumors about a dense throng of Z's w/ some sort of leader. Accepting this mission leads to a seeming freeze on the dialogue screen & the game subsequently pooping out. No crash.log is generated & there seems to be no relevant debug.log entry.

The NPC has an "Asked to Train" effect but I believe this is from granting the reward for the 2nd mission; I thought I should mention it because it does tell you that seeing it is a bug. Also, the NPC has red-text dialogue options upon initially presenting the new mission; I believe they are to intimidate the NPC into putting away their weapon or fleeing the area. I found these options strange considering the NPC is an ally. The options seemingly had very low success rates (7% & 0%, respectively) despite my char's lvl 6 Social.

This freeze has happened 3 times now & effectively prevents me from progressing this NPC's mission chain. I can reject the mission in order to access all of the NPC's other functions but choosing chitchat & asking if there's anything I can do for them results in presentation of the mission (w/ red-text dialogue options) & the subsequent freeze. Do I need to clear the "Asked to Train" effect?? What else could be the matter??

### Steps To Reproduce

Unknown steps to reproduce. I've given what details seem relevant above & am open to inquiry.

### Expected behavior

I expected that ally level would increase, because all other skills can increase in level.

### Versions and configuration

Android 0.F-2 Tiles English vanilla

**Comment by LeahLuong** [comment]
A separate but possibly related issue is I wasn't able to collect payment for the NPC's carpentry work. It told me they'd made over $1000 but they didn't have any Merch in their invo, none was dropped on the ground, & I didn't have any. I tried buying the $1000 farm plot & was told I didn't have enough money.

**Comment by hexagonrecursion** [comment]
> This freeze has happened 3 times now

Hello. It sounds like you have a save file where this freeze can be reliably reproduced. Please upload it. Sorry, but I do not know how to export the save file on android. You should ask on reddit https://www.reddit.com/r/cataclysmdda

**Comment by LeahLuong** [comment]
Sorry, that file no longer exists. Even if it did, it was too large to upload here. I started a new game when the latest stable hit & haven't crossed this error yet but I'll keep an eye out.

**Comment by LeahLuong** [comment]
I finally found another NPC w/ this mission chain. They were w/ me for the completion of both of their missions (kill Jabberwock & then 100 Z's) so I don't think Tacoma carpentry has anything to do w/ it.

In the link provided below, you need to speak to Latosha in order to complete her 2nd mission. I chose to be rewarded w/ Marksmanship training. Following that, she will produce her red-text options. Choose the white 1. Accepting her 3rd mission causes my system to hang & then the game poops out to the home screen; no crash.log. YMMV.

Don't ask me about the tied-up horse in my humvee.

https://drive.google.com/file/d/19qfPJdaZVsCNmDnb5iWIRmZLmt2S7g0Z/view?usp=drivesdk

**Comment by MNG-cataclysm** [comment]
I tested this on build windows-tiles-sounds-x64 2022-10-08-0525, and this error did not appear.
