### ISSUE TITLE
Rainy weather missing sprites

### ISSUE THREAD

**Issue by ektoplazm** [CleverRaven/Cataclysm-DDA#52582]
### Describe the bug

There are no sprites for rain, only sound. Sidebar still shows the weather correctly, rain drop sound plays out ok, "wet" status effect applies to the character. Tested on Ultica, chibi-ultica, brown like bears and neodays. Encountered it on my old character, replicated with debug-spawning drizzle, rain and thunderstorm on a fresh character. 

### Steps To Reproduce

1. Debug rain in
2. Status changes in sidebar, sounds comes in
3. There are no sprites or effect from raining

### Expected behavior

I bless the rains down in ~~Africa~~ New England

### Screenshots

Not that useful but here you are
![image](https://user-images.githubusercontent.com/60448096/139662536-b5c8dd47-e347-4d39-9a8d-f2537745a2b4.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 946ed1d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by ZhilkinSerg** [comment]
It could've been a duplicate of #45385, but I can see rain sprites were already added in all mentioned tilesets, so just make sure animations and rain animation are enabled:

![image](https://user-images.githubusercontent.com/16213433/139703598-e270ada8-7e91-4c0f-9c23-a31c216787c0.png)

**Comment by ektoplazm** [comment]
That was it, thanks.
