### ISSUE TITLE
Recipes descriptions for items in containers need to show stats for contents, not container.

### ISSUE THREAD

**Issue by epsimpson** [CleverRaven/Cataclysm-DDA#52588]
I just read a book that has canned and pickled foods, and all the descriptions give details of the container they are placed in, not the contents actually being cooked and preserved.  There is a "D[e]scribe" keybinding at the bottom of each recipe page, but hitting 'e' just produces the exact same container description already shown by the recipe.  Right now we have to actually craft the recipe to find out what sort of per-portion nutrient and enjoyability scores we will be producing.

I think the contents are generally more important than the container for crafting, so the contents should be what is displayed in the crafting screen (unless the container is empty after crafting, in which case the container is the item of interest).  The 'D[e]scribe' window could continue to display the container itself as it does now - you are describing what you see when you look at the sealed container you have crafted.

I was thinking about why the 'D[e]scribe' window would show the exact same information as the recipe itself, and realized that maybe it is intended for use by handheld devices.  If a reason does exist for both descriptions to be the same, then maybe the best solution would still be to provide the contents description for recipes, but to also add a nested "contained in" field to item contents descriptions in general, thereby making the need for a separate container description less critical. (e.g. Contained in a sealed 0.50L glass jar, in a tool belt, in a large tactical backpack, in a vehicle "foldable cart", 1 NE of your location.)

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
