### ISSUE TITLE
PR template could be improved

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#52591]
### Describe the bug

The comment under the Summary section is ambiguous in a way that causes many contributors to get the format wrong.

### Steps To Reproduce

1. Look at PRs submitted.
2. Note that it isn't unusual for new contributors to get the Summary line wrong.

### Expected behavior

A comment that guides contributors towards entries in the correct format.

Suggested changed wording:
The word "Category" above must be replaced with exactly one of the following words (in exactly that form): ..., or None. The comment should describe the nature of the PR (used to generate a change log), but should be removed in case of the None alternative.
Examples:
- Content "Adds the FUBAR faction"
- Balance "Reduces the spawning rate of foos in the bar facility"
- Bugfixes "Removes crash condition when a bar is merged with a foo"
- None

All of the above can be improved upon, of course.

### Screenshots

N/A

### Versions and configuration

N/A

### Additional context

The current format is a vast improvement over the previous one, but it's not perfect.

**Comment by wapcaplet** [comment]
I agree this section is confusing and difficult to get right. One difficulty I recall from when I cleaned up this template (#39909) is that we cannot include a literally correct summary line as an example.
