### ISSUE TITLE
Android port of C:DDA Error. 'SDL Error'

### ISSUE THREAD

**Issue by Helpfulcockroaches** [CleverRaven/Cataclysm-DDA#52597]
### Describe the bug

Opened the first time, black screen

Opened the second time, "Z" loading screen shows for a loooong time. 

After a long time of loading screen, installation begins.

After installation, the usual setup will prompt and ask if I want to enable Software Rendering, Force Fullscreen, Trap Back Button.

Tried twice, first one with just Trap Back Button enabled. Error.

The second time, Trap Back Button and Software Rendering enabled. Error

The error is;

SDL error

An error occured while trying to start the application.
Please try again and/or reinstall

Error:dlopen failed: empty/missing DT_HASH in
"libintl-lite.so" (built with --hash-style=gnu?)

### Steps To Reproduce

1. Install on an Android phone version 5.1.1 (or even older)
2. Open the game, it's blackscreen then restart the app. Open again, if there's the Z loading screen then just wait.
3. After installation, don't enable anything else than the Trap Back Button.

### Expected behavior

Expect black screen, and error.

Because you're using an old phone, which I saw on another issue that android 4 below has no support on latest C:DDA android builds.

### Screenshots

![Screenshot_2021-11-02-19-55-32](https://user-images.githubusercontent.com/93592945/139855124-e8ad12c2-0277-4c9a-abe3-1208fd5d293a.png)

### Versions and configuration

Phone: Galaxy Samsung On7
Android version 5.1.1
1.5 gb RAM

Game version: Latest stable build on the Playstore
(The experimental version of C:DDA isn't showing on the playstore of this old phone)

### Additional context

I installed the other C:DDA, ported by Michael Davis.
Game version 0.4.9, and it worked on the phone without any problem.

At this point I just assumed that the C:DDA newest builds doesn't support older versions of Android. Which is fine, I'm stuck with this old phone till I get my android 8.0 phone fixed.

**Comment by LeahLuong** [comment]
I'm able to play on my 5yo Android phone. I DL'd the latest stable from cataclysmdda.org & use trap, fullscreen, & no software rendering.

**Comment by ZhilkinSerg** [comment]
We have moved from using that third party translation library, so this error does not exist in current experimental version - either use it or wait until next stable version to hit Playstore.

**Comment by Helpfulcockroaches** [comment]
Downloaded the latest experimental version of C:DDA, and yeah it did worked!
Thanks for the info guys, I can finally play C:DDA again
I really should've looked this error days ago. Saved me some time
