### ISSUE TITLE
Solar Backpack Lacks "Integrated Cable"

### ISSUE THREAD

**Issue by LeahLuong** [CleverRaven/Cataclysm-DDA#52598]
### Describe the bug

Item description leads you to believe you won't need a jumper cable to interface w/ your CBM. You do.

On a side note, power availability on the CBM management screen is not always visible. My char has several power sources but I can only see the 1st 2 digits of power accessible from my gas cell; the rest fall off the right side of my screen due to the small terminal space on my phone. I can't even tell if my Cable Charger has a separate reservoir like my other power systems or if it feeds directly into the basic storage. UI for small terminal size is also a big issue in the vehicle construction menu because the various buttons that are supposed to scroll around do not function for the most part.

### Steps To Reproduce

1. Read solar backpack's item description.
2. Try using the solar backpack & Cable Charger w/out a jumper cable.
3. Make demands for truth in advertising.

### Expected behavior

I expected that solar backpack level would increase, because all other skills can increase in level.

### Versions and configuration

Android 0.F-2 Tiles English vanilla

**Comment by zachary-kaelan** [comment]
How are you playing it on your phone?

**Comment by LeahLuong** [comment]
I mainly use my thumbs. The virtual joystick & hotkey bar arguably make the game easier to play than it would be with a real keyboard, UI visibility issues notwithstanding.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/rework-solar-backpack-to-make-it-charge-smartphones-not-only-cbms/28227/1
