### ISSUE TITLE
No ink in any black writing pens.

### ISSUE THREAD

**Issue by Scorch-Mechanic** [CleverRaven/Cataclysm-DDA#52594]
### Describe the bug

I've been to three mine entrances so far in this save and in every single one I've found dozens of black ink writing pens, nice ones, that are all empty. Not the thick permanent markers, I mean `pen`, as in `This is a fine pen, of much better quality than a disposable model.  `

### Steps To Reproduce

1. Go to a mine entrance.
2. Rifle through some desks.
3. Fail to find a single black ink writing pen with even a drop of ink in it.

### Expected behavior

Writing pens should have ink.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 946ed1d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

**Comment by Termineitor244** [comment]
Done, the problem was with charges in the item groups where the pen could spawn.
