### ISSUE TITLE
Eyeglasses missing on start

### ISSUE THREAD

**Issue by Zenithir** [CleverRaven/Cataclysm-DDA#52601]
### Describe the bug

in 0.F-2 starting with wilderness and farsight as a lost submissive I start with the outfit, matches, but lack the glasses.

### Steps To Reproduce

1) Make a player with wilderness and farsight as a lost submissive
2) Check inventory and worn gear

### Expected behavior

I expected to have the glasses that go with farsight

### Versions and configuration

0.F-2 Windows Tiles

**Comment by ZhilkinSerg** [comment]
No issue here - that profession is not expected to have any items related to traits:

https://github.com/CleverRaven/Cataclysm-DDA/blob/ddc285a7e0218f341c2e4c77025143a68cc0f5c3/doc/JSON_INFO.md#L1253

https://github.com/CleverRaven/Cataclysm-DDA/blob/0fac7c74eb200dc20fc5411b908426fc1ef1347b/data/json/professions.json#L2305-L2315
