### ISSUE TITLE
Zweihander has no reach attack

### ISSUE THREAD

**Issue by rubenpd** [CleverRaven/Cataclysm-DDA#52613]
Zweihander has no reach attack despite being just as long or longer than most spears, here's a list of some spears and their lenght, plus the zweihander lenght:

1) zweihander is 180cm long, has no reach attack
2) simple knife spear/knife spear is 130cm long, has reach attack
3) wooden/forked spear is 150cm long, has reach attack 
4) steel/copper/stone spear is 180cm long, has reach attack
5) pipe spear is 184cm long, has reach attack

**Comment by Terrorforge** [comment]
I support this change. 

Now, there is a counterargument that raw length isn't everything. As a relatively light thrusting weapon, it's possible and effective to grasp a spear very near the end and lance it out to its full length, whereas heavier cutting weapons such as greatswords both require a more centered grip and doesn't have full cutting power at the very end of the blade. But the zweihander is still significantly longer than the shortest reach weapons, and oh would you [look at that](https://www.wiktenauer.com/images/thumb/1/13/Di_Grassi_21.jpg/400px-Di_Grassi_21.jpg), it can do that same lancing thing spears do.

Also, from a purely mechanical standpoint, this would differentiate it from the nodachi, justifying it's more cumbersome length.

**Comment by rubenpd** [comment]
given a 50cm hypotetical handle for the zweihander it should still have 130cm (knife spear total lenght) worth of blade to hit with

**Comment by SirPendrak** [comment]
You could do some ranged attacs with thrusts from zweihander, but cuts with the tip of the blade are not very effective. Optimal cuts are made at center of percussion, which is usually about 3/4 or 4/5 of the blade lenght. This, minus handle lenght, and reach cuts from this sword become questionable again by the game scale. I wonder if it would be possible to give different damage stats only for reach attacks (stabs in this case). 
And giving zweihander reach atttacks would make it OP balancewise

**Comment by Terrorforge** [comment]
This post got me thinking about something like that. Specifically I thought you could implement it by giving players the option to activate the weapon to switch between zweihander (cutting) and zweihander (thrusting)

But consensus was that this was too finicky to do manually, and we should implement a smart system where weapons have different attack profiles, and you automatically select the most appropriate one based on skills and proficiencies. Perhaps a ranged thrust could be implemented as part of that

But that requires quite a bit of infrastructure, so for now I think just giving it reach is the only reasonable way to represent those attacks.

I also really don't think it would be OP. It has similar techniques to polearms like the halberd and Lucerne hammer and is about as annoying to carry, but it deals less damage. Without the "Polearm" tag it would deal more damage to adjacent enemies than some of them, but still less on the actual reach attacks. I don't see what part of that is worryingly strong.

**Comment by kevingranade** [comment]
feel free to implement a feature to make the zweihander deal reduced damage with a reach attack and then give it that reach attack.
