### ISSUE TITLE
Parkour and skating as athletics profiencies

### ISSUE THREAD

**Issue by Termineitor244** [CleverRaven/Cataclysm-DDA#52618]
# Is your feature request related to a problem? Please describe.
Its currently impossible to become good at parkour or skating after world generation, skating is considered a trait, and parkour, while a proficiency, its impossible to train.

# Describe the solution you'd like
To have both as proficiencies of athletics, and being able to train them when:

**Parkour:**
- Traveling trough rough terrain (Base move cost higher than normal).
- Climbing roofs and fences.
- Doing a dedicated practice recipe (Like practicing running from one place to another while climbing and evading obstacles).

**Skating:**
- Using items with the "REQUIRES_BALANCE" (Rollerskates, rollerblades and heelys).
- Doing a dedicated practice recipe (Like doing some acrobatics with some kind of skate).

All of these actions could (and should) also train your levels of athletics.

# Describe alternatives you've considered
To leave them as it is.

# Additional context
This could be made in conjunction with the long awaited swimming proficiency.

Your athletics skill could give some basic bonuses to battling in skates and doing some parkour, if it isn't doing it already.

**Comment by Termineitor244** [comment]
Related: #49191

**Comment by Maleclypse** [comment]
Partially addressed in  #53205
