### ISSUE TITLE
Sauerkraut fermentation not providing sealed jars

### ISSUE THREAD

**Issue by Zhid13** [CleverRaven/Cataclysm-DDA#52622]
### Describe the bug

As title said. The sauerkraut fermentation creates unsealed jars which spoil instead of sealed ones as code and message displayed would suggest.

### Steps To Reproduce

1. Craft the "fermenting sauerkraut jar" recipe.
2. Wait for it to ferment.
3. Activate the item to recieve sauerkraut jar
4. Jar is not sealed and will spoil

### Expected behavior

I expected the item activation to yield a sealed jar of sauerkraut. 

### Versions and configuration

OS: Windows 10
Game version: 0ad2fdd
Modlist: DDA, no_npc_food, speedydex, stats_throughSkills, stats_through_kills
Language: English

**Comment by RoyBerube** [comment]
It fails to seal a fermenting sauerkraut jar spawned from the debug menu as well. Spawned the item, advanced time 4 days, activated it, and the jar is not sealed.

**Comment by RoyBerube** [comment]
Found why. PR #51527 changed the volume of some items. Sauerkraut changed from 250 ml to 240 ml. 2 charges fit into a 500ml jar.

Problem is that sealing a container will fail if the remaining space is greater than zero. I see 2 ways to fix this: 
1. Revert the item volumes to fill the jar with no unused space.
2. Change  item::seal() to be a little more forgiving in determining when to seal a container. I'm thinking if it is 90-95% full that should be enough to allow it to seal.

**Comment by Zhid13** [comment]
You can actually activate the jar to finish fermentation in only 9 hours, as the object description says. And I think the first solution is the most useful. I don't know why the item size would get changed to such a close number, specially since most containers that I know of already have capacities that are multiples of 250ml.
