### ISSUE TITLE
Moving in progress practice craft items with 0 volume errors

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#52625]
### Describe the bug

 DEBUG    : Item 'in progress melee (beginner) (32%)' with zero volume

 FUNCTION : int item::charges_per_volume(const volume&) const
 FILE     : src/item.cpp
 LINE     : 976
 VERSION  : 0ad2fdd

### Steps To Reproduce

1. interrupt a practice craft
2. move resulting item into various tile/vehicle containers using advanced inventory management

### Expected behavior

No error, ideally no item remains from practice craft.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0ad2fdd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by LeahLuong** [comment]
This issue seems related to #52532 if not a duplicate.

**Comment by irwiss** [comment]
Fixed by #57625
