### ISSUE TITLE
Include "ESC" on various shortcut bar presets for Android build

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#52630]
# Is your feature request related to a problem? Please describe.
The shortcuts tab on the Android build makes the game much more manageable, cutting down time spent pulling up the keyboard when in fullscreen mode (which itself is tricky without the option for a small, virtual "open keyboard" button - a useful addition).

The shortcut tab options are preset and unchangeable on many actions, and only half of the actions and menus include the "ESC" key on this tab. 

# Describe the solution you'd like
Add the "ESC" key to these other actions and menus to drastically cut down on time spent manually pulling up the keyboard. These include the following. 

 **Actions with the "e" examine key like:**
- Table workbench (before actual crafting menu),
- Smoking racks,
- Items on the ground

**Menus including:**
- Main Menu,
- Keybindings menu,
- Actions menu, 
- "O" Sort menu
- "A" use item actions (shovel, knife, marker, etc)
--------------------------------
Also, "e" should be added to easily examine items on many menus such as:
- "E" Eat menu,
- "R" Read menu.
- "i" Inventory,
- "I" compare inventory,
- etc. ("e" is useful most everywhere)

# Describe alternatives you've considered
- Add a screen gesture for the "ESC" key.
- Make tapping outside in game menus default to "ESC" and inside the menus default to "Enter" (Would be nice for the menus)
- Throw away my phone

# Additional context
When the game is set to force fullscreen mode, the back button is totally hidden and trying to pull up the keyboard invariantly registers as movement (likely varies with device) An "open keyboard" virtual button like is found in many other games would be super handy.

Also, The force fullscreen option is only available on first start up. That should really be configurable in options.

**Comment by ZhilkinSerg** [comment]
Double tap works as Escape key.

**Comment by LeahLuong** [comment]
You didn't post a version #. Latest stable usually does provide "e" for many menus. Have you disabled contextual hotkeys in settings??

Not sure of your Android's make but mine has a hardwired "Back" button that opens the virtual keyboard.

Also, I agree that force fullscreen shouldn't be an option requiring reinstallation to change.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
