### ISSUE TITLE
Spider Nest special fails to generate spiders/webs

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#52646]
### Describe the bug

Spider Nest overmap special fails to generate when it appears over larger structures, like a farm field or light industry. It generates correctly over single map tile city houses.

Autonote stills labels it on the map tile, but there are no webs or spiders.

### Steps To Reproduce

1. enable autonotes
2. look around map for large structures
3. notice that spider nests over them don't generate spiders or webs

### Expected behavior

Webs and spiders.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0ad2fdd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Venera3** [comment]
Spider nests still use a hardcoded map extra (wasp houses as well) that could stand to be moved over to JSON mapgen. If nobody picks it up I hope to get around to some spider-themed stuff later this cycle.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-12004.

Spider nest map extra over farm field
![изображение](https://user-images.githubusercontent.com/11132525/196336848-dcab0e6f-2613-485a-bbd2-13764ca3ac5c.png)
