### ISSUE TITLE
Refugee center scout exodii mission assignment error

### ISSUE THREAD

**Issue by Tommy-os** [CleverRaven/Cataclysm-DDA#52643]
### Describe the bug

 DEBUG    : Unable to find and assign mission target exodii_base_x0y3z0.

 FUNCTION : cata::optional<coords::coord_point<tripoint, coords::origin::abs, coords::scale::overmap_terrain> > find_or_create_om_terrain(const tripoint_abs_omt&, const mission_target_params&)
 FILE     : src/mission_util.cpp
 LINE     : 251
 VERSION  : 0ad2fdd

### Steps To Reproduce

1. Find refugee center
2. Do quests for old guard until they mention robots
3. Get above error when accepting said mission

### Expected behavior

No error.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0ad2fdd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

I've scouted a fair bit in every direction around the refugee center, maybe it failed to generate the base?

**Comment by kholat** [comment]
I got the same.

**Comment by NiktoNekto** [comment]
I got the same too.

**Comment by I-am-Erk** [comment]
I believe this was solved in 53000, let me know if I am wrong.
