### ISSUE TITLE
Tried to drain something without any liquid

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#52647]
### Describe the bug

 DEBUG    : Tried to drain something without any liquid: <color_c_magenta>|.</color> steel drum (200L) (draining) amount: 30 ammo: 0

 FUNCTION : int vehicle::drain(int, int)
 FILE     : src/vehicle.cpp
 LINE     : 3369
 VERSION  : 0ad2fdd

### Steps To Reproduce

1. find a vehicle with a draining (damaged) tank
2. siphon tank with rubber hose into a tank on the same vehicle
3. if the tank drains during the siphoning, error is produced

### Expected behavior

No error due to siphoning.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0ad2fdd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by LeahLuong** [comment]
I wasn't getting an error message but I was having what may be a related issue: wasn't able to fuel my gas cell CBM when siphoning from a draining tank.

**Comment by hexagonrecursion** [comment]
I am sorry, but I could not reproduce this bug. If you can reproduce this bug reliably, please post more information about how to reproduce it.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: eacb7d9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
