### ISSUE TITLE
Bugs with unpacking items in inventory 

### ISSUE THREAD

**Issue by RDru** [CleverRaven/Cataclysm-DDA#52644]
### Describe the bug

Unpacking items in advanced inventory can drop them or put them into other container. This is happening a lot with MREs.

### Steps To Reproduce

1. You need MREs so make a world with "Bionic Professions" mod. 
2. Start "Overrun" scenario in military warehouse. Pick character that already have some items like backpack or spawn and wear those items.
3. Pick up some MREs.
4. Open advanced inventory.
5. Keep opening each MRE and each item in MRE by pressing 'e' on item and then 'U'nloading it.

Some items will fall on the ground, some will be put into other container.
For example unpacking a chocolate bar from a paper wrapper can result in that chocolate bar going into another paper wrapper that already has a chocolate bar.

### Expected behavior

Assuming that volume of container with items is always at least the same or bigger than the items inside, unpacking whole container should drop that container if there is no space in inventory and not the items.
Unpacking should never result in putting unpacked items into another container.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 130797e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Extra Mutated Scenarios [extra_mut_scens]
]

### Additional context

Unpacking works fine from the ground.

**Comment by Scorch-Mechanic** [comment]
@Maleclypse Not a bug, and should be closed.

"Unloading" containers has always attempted to put the unloaded items into other available containers on your person, like backpacks. If RDu wishes to drop the contents of containers entirely onto a table or floor somewhere, they should use either the drop hotkeys to drop individual items or bind a key to "unload container" and use that hotkey to empty all items out of the container(s) of their choosing onto the tile of their choosing.
