### ISSUE TITLE
Execute player activities in the middle of dialogue.

### ISSUE THREAD

**Issue by adorableNYNICG** [CleverRaven/Cataclysm-DDA#52654]
# Is your feature request related to a problem? Please describe.
I've tried around with "talk_topic" json and dialogue effects and found that I can't assign player activities to character and execute it in the middle of dialogue.
When I assign player activities to character, it's always being executed after dialogue ends.
In my opinion, being able to execute player activities while dialogue goes on adds some flexibility to flavor of "player to NPC communication". (NPC includes talkable item and monster)

e.g.
-Here is one NPC named A. A has two talk_topic, "TOPIC_BBB" and "TOPIC_CCC".
-In "TOPIC_BBB", A greets to player and asks if player wants some conversation. Player has two choice for response, talk for 5 minutes or decline A's offer and end dialogue.
If player choose to talk, player does 5 minutes activity and then dialogue moves to "TOPIC_CCC".
-In "TOPIC_CCC", A asks if player needs more conversation, or some quiz. Player has three response, talk for another 5 minutes, play some quiz for 10 minutes or end conversation and end dialogue.
This time, if player choose to talk for more or play quiz, player does 5 or 10 minutes activity and then dialogue moves to "TOPIC_CCC" itself.
-With this NPC(A) and topic(BBB,CCC), player can interact with NPC in more "living" form. Player can choose to chat or quiz freely, and time passes accordingly to player's choice. 
(Currently, similar thing to this example can be done by setting activity duration using "variable_object". But in this method, interaction between player and NPC is less "living". That's because we can assign only one activity and it's executed after dialogue.)
# Describe the solution you'd like
Please make it possible to execute player activities while dialogue goes on.

**Case 1: Assign player activity in "response effect".**
Here is example, "TOPIC_AAA" and "TOPIC_BBB".
TOPIC_AAA has one response, it assign one player activity to character(player) and lead dialogue to TOPIC_BBB.
Upon selecting this response, game will do...
1.Assign player activity to character.
2.Close dialogue before it moves to next topic.(participants of dialogue and id of next topic will be saved. also dialogue opponent's "relative position to player" will be saved if opponent is actual NPC or talkable monster.)
3-1.Execute assigned player activity on character.(while execution, dialogue opponent : NPC or talkable monster won't take any action including move)
3-2.If something gets wrong while activity,(e.g. hostile creature appeared, player or NPC gets damage by some reason) query to player whether to continue activity(and dialogue which follow it). If player chooses to quit, end activity and dialogue. Saved information(participant, topic id and relative position) will discarded.
3-3.After activity ends, game checks specific position from player for existence of dialogue opponent. Position is based on saved information "opponent's relative position to player". If there is no accident, this check will pass. But if some case occurs(e.g. player or opponent's position has changed forcefully by teleglow teleportation, sudden disappearance of opponent), game tells player what happened and ends dialogue. Saved information(participant, topic id and relative position) will discarded.
4.Reopen dialogue between saved participants and set it's current topic to saved one.(in this case, topic will be TOPIC_BBB) Saved information(participant, topic id and relative position) will discarded.
5.Dialogue goes on...

**Case 2: Assign player activity in "speaker_effect".**
Here is same example,"TOPIC_AAA" and "TOPIC_BBB". I'll describe about TOPIC_BBB this time.
TOPIC_BBB has one "speaker_effect", it assign one player activity to character(player). Response is ordinal one, it ends dialogue.
When dialogue moved to TOPIC_BBB from TOPIC_AAA, game will do...
1.Display "dynamic line" and "response" in normal way.
2.Assign player activity to character.
3.Close dialogue before allow player to choose response.(participants of dialogue and id of current topic will be saved. also dialogue opponent's "relative position to player" will be saved if opponent is actual NPC or talkable monster.)
4-1.Execute assigned player activity on character.(while execution, dialogue opponent : NPC or talkable monster won't take any action including move)
4-2.If something gets wrong while activity,(e.g. hostile creature appeared, player or NPC gets damage by some reason) query to player whether to continue activity(and dialogue which follow it). If player chooses to quit, end activity and dialogue. Saved information(participant, topic id and relative position) will discarded.
4-3.After activity ends, game checks specific position from player for existence of dialogue opponent. Position is based on saved information "opponent's relative position to player". If there is no accident, this check will pass. But if some case occurs(e.g. player or opponent's position has changed forcefully by teleglow teleportation, sudden disappearance of opponent), game tells player what happened and ends dialogue. Saved information(participant, topic id and relative position) will discarded.
5.Reopen dialogue between saved participants and set it's current topic to saved one.(in this case, topic will be TOPIC_BBB)(player activity won't assigned again upon reopen of dialogue) Saved information(participant, topic id and relative position) will discarded.
6.Dialogue goes on...

# Describe alternatives you've considered
none.

# Additional context
none.

**Comment by PatrikLundell** [comment]
Any such system would have to be able to handle interruptions, such as e.g. the appearance of zombies (without the participants calmly continuing to talk about the weather while being eaten alive), or something suddenly killing the NPC.
You also don't this to drag on to the extent that the PC gets hurt from it, at least not without any way to get out of it (hunger/thirst/sleep deprivation/delayed poisoning kicking in, etc.), as well as handling more bizarre cases such as teleglow teleportation cutting the conversation short.

**Comment by adorableNYNICG** [comment]
Uh... ok. Let me suggest ideas about interruption.(may insufficient to be idea though... and also it may hard to read...)

**First situation : hostile creature appears, player gets hurt by some reason, player's condition goes bad(hunger, thirst etc...) while activity.**
For this case, I think same function can be used as normal activity interruption. If situation goes bad, query player whether to stop activity. (and dialogue)

**Second situation : dialogue opponent(actual NPC or talkable monster) gets hurt by attack or some bad effect while activity.**
I think it needs whole new function to this case... This function watches opponent whle activity is benig executed. And when opponent gets hurt, it query player whether to stop activity. (and dialogue) 

**Third situation : sudden death of dialogue opponent(actual NPC or talkable monster), player or opponent's position changed forcefully by teleglow teleportation or some sort while activity.**
-To react this, I want to add information to be saved at "step 2 of case 1" and "step 3 of case 2" of "describe the solution you'd like" section. I wrote that "participant of dialogue" and "id of next/current topic" will be saved upon close of dialogue. In addition to this, I want to save dialogue opponent's "relative position to player"(if opponent is NPC or talkable monster, not the talkable item). When dialog closes, game checks player and opponent's coordinate, and then caluculate opponent's relative position to player in coordinate form(X, Y, Z). Then save it.
-After player activity ends, game checks specific position using saved coordinate information. Checks if there is matchng NPC or talkable monster to saved information "participant of dialogue". If thing goes without problem, there should be matching NPC exists in place. And dialogue will reopened. But if something wrong(NPC's sudden death = NPC disappered, NPC or player's position has changed by teleglow teleportation) happens, there is no matching NPC exists in there. In this case, game tells player what happened(NPC is dead!, NPC has disappered! etc...) and stop conversation.(game doesn't reopen dialogue)

I would have to say about saved informaton (participant, topic id, coordinates) as well. These information will discarded upon inerruption of activity(and dialogue which following this activity) and reopen of dialogue.

**Comment by wapcaplet** [comment]
> To react this, I want to add information to be saved

As the creator of this issue, you can edit the issue description - use the "..." icon in the upper-right corner and choose "Edit" to rephrase or clarify.

The example you gave was spending 5 or 10 minutes taking a quiz, but I am not aware of any such quiz activity in the game now. Can you give another example of an existing activity (like crafting, repairing, or disassembling) that you might want to do in the middle of a conversation? I am having trouble thinking of practical applications for such a feature.

**Comment by PatrikLundell** [comment]
A couple of "sort of this" cases in the game now would be "spending time with Alonso" and get on the job training from Jenny Forcette (both in the refugee center) where you could potentially continue the conversation after the activity, as well as all training sessions you can get as payment or for payment. You also have the general chat (which is quite similar to a quiz session) and training session activities with companions. Thus, there are cases where such a functionality could be used, although I don't find improvements to any of them to be critical (nice, but not critical).

**Comment by adorableNYNICG** [comment]
Yes, these examples which PatrikLundell said is good example. If I have to give an example from already existing contents in game, I would say same thing...
But, sorry... To be honest, I didn't have any example activity from existing contents... The activity I wanted to be executed was custom activity which can be added easily with .json only. This actvity does nothing, just passes time like "waiting". But I could set arbitrary exercise level and arbitrary message displayed in top of screen while activity. So I thought I can add more flavor to my MOD's NPC (also to the mainline NPC if some changes in .json will be done) if I can execute these custom activity in middle of conversation. 

eg. talking to NPC:A --> choose to chat for 5 min --> 5 min of low exercise level activity named "chatting..." will be executed --> choose to quiz for 10 min --> 10 min of low exercise level activity named "answering quiz..." will be executed --> choose to dance with A for 5 min --> 5 min of medium exercise level activity named "dancing with partner..." will be executed... 
You can choose as many activities as you want to do with A, time passes accordingly, each activity does only pass of time but has different name and exercise level.

This feature won't do much on current game itself, but I thought adding way to make NPC conversation more "living" is good idea...


> 
> As the creator of this issue, you can edit the issue description - use the "..." icon in the upper-right corner and choose "Edit" to rephrase or clarify.

Ok, I'll try later when I have additional time to spare. But sorry if I make things more complicated...

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
