### ISSUE TITLE
Examine Menu no longer offers Option to pick items up

### ISSUE THREAD

**Issue by estebandellasilva** [CleverRaven/Cataclysm-DDA#52655]
### Describe the bug

Unable to examine any items on the ground. Unable to interact with containers In this case stow boards or cargo spaces.
Examine Menu only shows vehicle option and remember and forget position.

### Steps To Reproduce

Start game
Find items on ground or in a locker
press e

### Expected behavior

E menu would offer option to pick up items

### Screenshots

![image](https://user-images.githubusercontent.com/89189872/140541893-f958067a-24f7-47df-a712-c10920cb1992.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: c74af52 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by dvolk** [comment]
It was removed in #51033, but IMO it shouldn't have been. It was useful to be able to quickly pick up from a single tile, especially when neighboring tiles had lots of items.

**Comment by Night-Pryanik** [comment]
You can use dedicated `g` hotkey to pickup items from a single tile.

**Comment by dvolk** [comment]
> You can use dedicated `g` hotkey to pickup items from a single tile.

'g' lists items on all adjacent tiles. The problem is that that can be difficult to browse when you have a lot of items nearby.
