### ISSUE TITLE
Move martial arts to the 'skills' tab

### ISSUE THREAD

**Issue by AskaHope** [CleverRaven/Cataclysm-DDA#52667]
# Is your feature request related to a problem? Please describe.

Currently there's no way to get information on the perks and buffs that a martial art may have until after character creation, this can be really frustrating if you were intending to create a character with a certain build in mind just to be reminded after all the time you've spent that Aikido scales with Dexterity and not Perception.

# Describe the solution you'd like

![idea](https://user-images.githubusercontent.com/43182704/140594728-1d177fc4-048f-4d91-83ed-5f4897023089.png)

There! with martial arts available in the 'skills' tab, players can easily acess them and build their characters without 'alt tabs' to check the wiki or waiting until the last second to see if they did it right.

Adittionally, martial arts can be balanced more easily like that, at least I would rather pay one extra point on character creation for a buff or two on my favorite martial art.

# Describe alternatives you've considered

I honestly don't see why this shouldn't be a thing, there's tons of free spaces on the UIs of this game. this may be a small step but is definetively a good QoL improvment.

# Additional context

None

**Comment by molkero** [comment]
Stats screen is also looking pretty empty, could be easier to show which stat affects which martial art
![Screenshot_2021-11-06_15-41-12](https://user-images.githubusercontent.com/49575273/140612167-bf1f9e79-cae8-4922-8781-0608f4c7c46c.png)

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
