### ISSUE TITLE
Enable/restore directional filtering to "Pick up Nearby Item(s)" action.

### ISSUE THREAD

**Issue by ProfoundDarkness** [CleverRaven/Cataclysm-DDA#52663]
# Is your feature request related to a problem? Please describe.
With the changes made from #51033 I'm finding myself **very** frustrated with not being able to select what direction to pick items up from.  (This is pickup, for me bound to 'g'.)

# Describe the solution you'd like
Some method of quickly filtering what to pickup by relative location of the character.

# Describe alternatives you've considered
Reverting the mentioned PR... this is far less than ideal though since there are a lot of changes I like in the mentioned PR.

# Additional context
Previously I'd hit g (pickup) then a direction and only be shown items in the direction I pressed.  Now I am presented with all the items around my character.  Problematic since I have tightly packed zones at my current base meaning it now takes me MUCH longer or I have to type a filter for an item I'm looking for where I didn't before.  It's not possible to stand on all furniture...

To be clear I don't hate the whole PR.  While I was using the mentioned PR I liked the changes to 'e'xamine (actually made me grin since it's bugged me for a while to have 'e'xamine ask if I want to pick things up).  I find the ability to pull items from all around handy in some situations (mostly while looting).  Also the ability to pull items directly out of containers on the ground seems invaluable... Pretty sure that's a VERY old and now fulfilled request.

What shape a solution takes...?  There seems to be a few variations on a couple of themes that comes to mind...
- Somewhat simple revert in that 'g'rab asks for a direction and after pressing a direction be shown only the items on the indicated tile but with the nice new interface.
- Variation on the above.  When prompted for a direction have a new key which indicates all directions, all other direction keys function as above.
- Alternative to above, instead of a new key have the '5' position (at feet) include all the other directions too.  So we get direction if picked or if at feet picked show everything.  The interface currently shows 'at feet' items first.
- Add a new hotkey/action, one 'action' behaves as it does now (show all).  The other 'action' behaves as it used to in that it prompts for a direction then displays the new interface with just the direction picked out.
- A new key from within the pickup menu which when pressed prompts for a direction and then when a direction is pressed redraw the interface with just the one direction's contents displayed.  This seems potentially fraught with complication however.

For now I've personally reverted the PR since my character got back to base with a broken arm so won't be going out much for a while and not being able to pick a direction to filter with was driving me a bit nuts...

**Comment by RelMayers** [comment]
It's harder now to pickup items when having them sorted into nearby tiles...

**Comment by catdach** [comment]
This was of course previously tied to `e`xamine
I'm honestly not sure why it was removed from `e`xamine to begin with. Even if the menu was 

> unfit for the pocket system
> and also a general pain.

The first point seems to have more to do with the menu itself, and not it's connection to `e`xamine. The second point is a matter of opinion.

From a player perspective it has suddenly become much more difficult to do something as simple as pickup an item because of #51033

Also if a new menu was created, why didn't it simply replace what was tied to `e`xamine?

I'm really not sure what #51033 did other than remove functionality

**Comment by Tommy-os** [comment]
What I used directional examine for, since the PR author asked:

1. quickly accessing a specific item storage in a vehicle that I knew had items I want
2. looting a specific zombie/drawer/fridge when surrounded by multiple other item stacks
3. interaction with huge stockpiles of items on neighboring shelves in my base

Now I instead have to stand directly on top of tiles I want to interact with, as it has become a choice between wasting time from perspective of game (moving onto tiles) or wasting my personal time (scrolling through pages of items to find the tile I want).

**Comment by ProfoundDarkness** [comment]
huh... since 0.E I've used 'g'rab instead of examine in those cases...

**Comment by Tommy-os** [comment]
'g'rab is used to pull furniture, I doubt the interaction with movable furniture pieces that store items will be the one you have in mind.

**Comment by ProfoundDarkness** [comment]
oh... ok... I use 'G'rab to pull furniture and 'g'rab to pickup items...

**Comment by Tommy-os** [comment]
Yes same here, calling it grab is what confused me since we're talking items here.

**Comment by catdach** [comment]
Personally, I use 'e' to pickup items the majority of the time, otherwise I use the '/' advanced inventory screen. I use 'G'rab to move furniture. I have never used 'g'rab

**Comment by catdach** [comment]
I not sure how difficult it would be coding wise but, if item pickup being tied the 'e'xamine is something that some people like and some people don't then is it feasible to make a togglable option in the settings or something?

**Comment by RelMayers** [comment]
Removing ability to grab items from single tile is bad. Player had ability to pick up from all tiles around him thru advanced Inventory before... Now there is no option for player, also more time is spent on looking for items

**Comment by Night-Pryanik** [comment]
Picking up items through the examine menu caused numerous bugs in the past, that's why it was removed. It isn't going to be restored, at least in the old way.
Dedicated hotkey for picking up items from specific tile, like it was done previously, could be restored, though.

**Comment by catdach** [comment]
> picking up items through the examine menu caused numerous bugs in the past

I was unaware of that. In that case, removing it from the examine menu makes a lot of sense! 
So long as directional pickup is restored, I'll be happy. (even if it is tied to 'g'rab, I can just rebind the hotkey to 'e' if I want)

**Comment by Aphegis** [comment]
Everyone already knows this, but I'm explaining the problem in case someone played it differently (something I'm noticing after reading some comments, some players used 'g', some 'e').

This is an exaggerated situation (common if you have a small base with many items close together, even after managing 'Y' zone (shift + y).

Previously, I would press 'V' (shift + v), so I could scan the area in a few seconds and see if I found something good, then press 'e' + arrow keys to select the item's position.

Currently you don't have the option to select tiles specifically, so when you press 'g' with too many items around you, it becomes confusing and inefficient. 

_Character surrounded by items_
![cataclysm-tiles_2021_11_06_11_48_43_022](https://user-images.githubusercontent.com/34956440/140614040-70eb8e4e-d430-4967-8877-1186758ac3d7.jpg)

_Current 'g' interface_
![cataclysm-tiles_2021_11_06_11_48_47_000](https://user-images.githubusercontent.com/34956440/140614041-b6510f1a-64ae-4073-98f4-8f1e25b9c6f5.jpg)

Obviously devs are already aware of this, but i must say, highly controversial change, specially given the fact that current 'g' does not 100% substitutes the previous 'e'.

**Comment by ProfoundDarkness** [comment]
I would like to add, for those that don't know... g **used to** do the same thing as e when it came to pickup.  If I wanted to pick something up from a desk I'd have to e then direction then g... vs g then direction even on interactive tile.  That was actually one of the reasons I stopped using 'e' to pick things up is the extra button press IF the tile I wanted to 'g'et things from happened to be interactive in some way.

About the only time I personally used 'e' was if I was planning to interact somehow with something be it lighting a fire in a brazier or to craft something at a desk or look over a vehicle...  I can't remember off hand a complete enumeration of my 'e' usage but it was never to pick things up.  At least not since 0.D or 0.E.

**Comment by AskaHope** [comment]
This change is especially awkward in the Android version

**Comment by ProfoundDarkness** [comment]
I noticed #52683 got merged, I pulled the latest master and did a rebuild to test it.

I only briefly tested it but I've got a big grin on my face... directional pickup has returned for when you want to 'g'et items.  There's also a new hotkey (unbound by default) to pickup everything around (like 'g'et was the last couple days).  Not sure where I'll slot this yet.  All the features of the newer get interface seem present including picking up items from containers that are on the ground :) .

Also if anyone is unfamiliar... as with the newer 'd'rop interface you need to bind "Mark a selected amount of selected item" to a key, for me it's on '.' (I don't know if that's default).  If you've used AIM you've probably gotten used to this a bit.

I feel I should mention since it came up a couple times in discord... Once you are in the pickup interface (after you hit 'g' and pick a direction) you can use 'e' or 'E' on a highlighted item to get the details about the item.  This works on a wide variety of item management screens such as 'i'nventory, compare (=), 'd'rop, 'D'irectional drop, and AIM.  Also when picking what to 'E'at.

I'm closing this issue as resolved, thanks much.
