### ISSUE TITLE
Allow more type of effects for ammo effects

### ISSUE THREAD

**Issue by Termineitor244** [CleverRaven/Cataclysm-DDA#52679]
# Is your feature request related to a problem? Please describe.
I want to do poisoned arrows, where, for example, you soak your arrows in the concentrated venom of a bee and then fire it to an enemy to debilitate it, but arrows use ammo_effect(s) to decide what special effects they do, and the poisons are categorized as effect_type, so I'm incapable of doing this with only JSON.

# Describe the solution you'd like
To be able to call effects from effect_type when firing ammo, similar to when monsters use special attacks, this would enable not only more types of arrows for the player, but even new enemies with ranged attacks meant to debilitate you (Without using the spell system).

# Describe alternatives you've considered
To resign myself to not be able to soak in poison my arrows.

# Additional context

**Comment by Maleclypse** [comment]
Aftershock and Magiclysm have run into similar issues.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
