### ISSUE TITLE
Putting handflare into bowl_plastic causes error and destroys flare

### ISSUE THREAD

**Issue by Chadtholomew** [CleverRaven/Cataclysm-DDA#52672]
### Describe the bug

I tried to put some flares into a tupperware container and it caused an error and consumed the flare. I am attaching a screenshot of the error. This happens every time i try and in a new world. 

### Steps To Reproduce

1. select plastic tupperware
2. reload it with flare (300/300 flare pyrotechnic)
3. error
4. the exact same behavior happens with jar_glass_sealed so it's probably an issue with the flare.

### Expected behavior

I expected that the tupperware would hold the flare and keep it waterproof

### Screenshots

![DeepinScreenshot_select-area_20211106010844](https://user-images.githubusercontent.com/57277165/140600017-1bd0d4b4-fa3d-46c3-b735-38c939f8ce97.png)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 21.1.6; Codename: Pahvo; 
- Game Version: 0208449 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Blaze Industries [blazeindustries]
]

**Comment by Hirmuolio** [comment]
This was fixed yesterday. Grab latest version.

**Comment by Chadtholomew** [comment]
> This was fixed yesterday. Grab latest version.

Thanks
