### ISSUE TITLE
Incorrect calories of boiled fiddlestick heads

### ISSUE THREAD

**Issue by danielkwinsor** [CleverRaven/Cataclysm-DDA#52676]
### Describe the bug

Calories and RDA of boiled fiddlestick heads may vary between multiples of 0, 2, or 3 when batch boiling fiddlesticks with mixed status.

### Steps To Reproduce

Gather fiddlesticks.
Wait, and maybe save/load cycle.
gather more.
Batch boil.

If you see calories as 0, eating them really does give 0 calories.  Save and load, you may then see a multiple of 2/3.

### Expected behavior

18 calories

### Screenshots

<img width="766" alt="Screenshot 2021-11-06 110250" src="https://user-images.githubusercontent.com/2822992/140619446-2d658492-4f2b-4d8a-90f7-2da269982f2c.png">
<img width="773" alt="Screenshot 2021-11-06 110306" src="https://user-images.githubusercontent.com/2822992/140619447-7f9f4930-ab84-44cd-9dae-77684b97ccc5.png">

### Versions and configuration

0.F-2

**Comment by chemicalhorse** [comment]
appears to be same issue as #52628

**Comment by hexagonrecursion** [comment]
I can reproduce this bug

![DeepinScreenshot_select-area_20220104235624](https://user-images.githubusercontent.com/52621858/148123008-d61bee6c-0b36-4ac7-a36c-b78ba5e8f57d.png)


- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: e7cd5fb [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by Sirbab** [comment]
Just encountered this.  It works for feeding faction camps though weirdly.
![image](https://user-images.githubusercontent.com/1490991/149285759-90827d8f-3a29-4068-8ce2-331444494c1f.png)
![image](https://user-images.githubusercontent.com/1490991/149285772-8839c8f7-b8b0-41e6-80a9-c432d6c97111.png)
