### ISSUE TITLE
Allow washing machines and dishwashers to be controlled from the electronics control unit menu

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#52678]
# Is your feature request related to a problem? Please describe.
I'm not sure how many other people can relate to this, but I'm really into the whole "roleplaying the building of a new civilization from the ashes of the old one" thing, and part of that - for me, anyway - involves industry, part of _that_ involves producing things en masse, which involves securing far more materials than the average lone wolf-type survivor would need, and for me, many of those materials come from the zombie laundry I accumulate, and have to wash before having it disassembled. As such, my character uses washing machines a _lot_, to the point where using them all to clean as much zombie laundry as possible causes these fingers I use to type with to hurt pretty quickly. As such, it would be helpful to have an option to toggle washing machines and the like from the electronics control unit, in the same way that doors and curtains can be.

# Describe the solution you'd like
I'd like to be able to activate washing machines (and dishwashers, just to not leave them out), either individually or all at once, from the electronics control unit interface. As for detergent, maybe there could be a special vehicle part that auto-loads it, or maybe activating washing machines from the electronics control unit would just require a tank with sufficient soapy water or something.

# Describe alternatives you've considered
1. Somehow making it possible to execute specific interactions with vehicle parts and similar things as a zone activity.
2. Giving up on roleplaying someone for whom industrial-scale production is an interest.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
