### ISSUE TITLE
Shopping carts can't be dragged through slopes 

### ISSUE THREAD

**Issue by SariusSkelrets** [CleverRaven/Cataclysm-DDA#52681]
### Describe the bug

When grabbing a shopping cart, the player will automatically ungrab the cart after walking up a slope, thus preventing players to pass bridges with their shopping carts

### Steps To Reproduce

teleport to a bridge
spawn a shopping cart
grab it before walking on the bridge
notice how you can't get the cart to change z-level

### Expected behavior

the cart can be pushed up or down a slope

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 1d946db [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    [WIP] Mythos Mod - No Zombies [Mythos]
]

**Comment by PatrikLundell** [comment]
Have you tried both pushing and dragging (in an attempt to find a work around, not to claim the problem doesn't exist)?

**Comment by SariusSkelrets** [comment]
Pushing them up a slope will make them change z-level but you'll then need to ungrab, walk on the bridge, then grag it again. Same for pushing them down one

**Comment by RoyBerube** [comment]
The problem occurs in game::walk_move(). Z levels are not processed properly for anything being moved by a grab - instead the grab is lost.

**Comment by RoyBerube** [comment]
I've got a fix mostly working for dragging and pushing of vehicles and furniture over ramps. A few kinks still to work out.
