### ISSUE TITLE
Crafting search filter won't show up

### ISSUE THREAD

**Issue by Maryionet** [CleverRaven/Cataclysm-DDA#52688]
### Describe the bug

The crafting search filter ui won't show up when i try to click the (f) button i can still search things do

### Steps To Reproduce

1 go to crafting by (&)
2 click (f) for search filter

### Expected behavior

It should show the search filter ui when i click (f)

### Screenshots

![Screenshot_2021-11-07-22-01-25-89_6fe8938556442e3d4f710ab4f9a16601](https://user-images.githubusercontent.com/68288642/140648248-e840f682-2f92-49df-9bd5-2c1226a303c5.jpg)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: realme; Model: RMX3241; Release: 11; Incremental: 1620697410778; 
- Game Version: 3b51b62 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by dseguin** [comment]
Your screen doesn't display enough rows, so the filter window is technically spawning off-screen. You can try reducing your font size and font height a little bit to display more rows:
![font_size](https://user-images.githubusercontent.com/12537966/140657432-8c48b753-7cd7-4fd1-b4c8-6fd3eeaa0189.png)

A more proper solution would involve setting the window's origin based on the number of rows.

**Comment by Maryionet** [comment]
@dseguin i tried your solution but the filter still won't show but from my testing it appears that the search filter does show on older versions.
and i'm not sure if this is related to the issue but when i start the game this white square appears and i don't see this on older versions were the filter appears.
![Screenshot_2021-11-08-11-56-20-99_6fe8938556442e3d4f710ab4f9a16601](https://user-images.githubusercontent.com/68288642/140682274-7cbf2919-2292-4e52-a4fa-e97aee038fe7.jpg)

**Comment by hexagonrecursion** [comment]
Possibly related: https://github.com/CleverRaven/Cataclysm-DDA/issues/48700

**Comment by Maryionet** [comment]
> Possibly related: #48700

It is related in that the search filter ui failed show but i checked and i tried his method of increasing the terminal height to 26 and it works.
![Screenshot_2022-01-06-13-05-13-22_6fe8938556442e3d4f710ab4f9a16601](https://user-images.githubusercontent.com/68288642/148331818-bb1cc6a3-28a5-4ad9-90cc-07abc06634e2.jpg)
