### ISSUE TITLE
Pickup Menu - Hide Unhide only works correctly if there is less than one full page of items

### ISSUE THREAD

**Issue by estebandellasilva** [CleverRaven/Cataclysm-DDA#52689]
### Describe the bug

With the change to the Pickup Menu, you are now able to open wallets for example -> this show the items which are inside it.
But this doesnt work if you see more than one page - then you have to open the wallet close the menu and open it again otherwise the menu will not update.

### Steps To Reproduce

Get a stack of items with some closed wallets inside - stack must exceed one page 
open wallets in the pickup menu
close pickup menu 
open pickup menu
Now you are able to see content of wallet

get only 1 closed wallet with nothing else
open pickup menu
open wallet 
see content of wallet

### Expected behavior

Pickup menu should update items as is does if the stack is smaller than one page.

### Screenshots

works with one page
![image](https://user-images.githubusercontent.com/89189872/140649631-c8dc6674-7396-46eb-aa29-9800a62f7dee.png)
![image](https://user-images.githubusercontent.com/89189872/140649645-ae576554-4090-4c6a-b658-198b66f4f423.png)
does not work with mulitple pages
![image](https://user-images.githubusercontent.com/89189872/140649676-a73287de-e305-49fa-82f8-6e80d8407c80.png)
![image](https://user-images.githubusercontent.com/89189872/140649691-0f59cb56-c700-4ad1-8b74-d5d4bed1885d.png)
close and open now it works
![image](https://user-images.githubusercontent.com/89189872/140649711-80d3b157-3519-4a8c-8475-847b953e6b04.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 3b51b62 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by andrei8l** [comment]
This happens whenever the column height doesn't change. https://github.com/CleverRaven/Cataclysm-DDA/pull/52659 should fix it.
