### ISSUE TITLE
Pickup Menu - Hidden still show items if items has mulitple layers (bags inside bags - see MREs)

### ISSUE THREAD

**Issue by estebandellasilva** [CleverRaven/Cataclysm-DDA#52699]
### Describe the bug

In the Pickup Menu Items that are hidden inside a container dont get shown - but if there are items unhidden inside an hidden item they still get shown
i dont think the statuts of the container containted in the hidden item matters

### Steps To Reproduce

Get an mre
try to pick it up and look at it in the pickup menu
See content of the hidden containers

### Expected behavior

Hidden Should apply to the content of a container thats inside a container that was hidden

### Screenshots

![image](https://user-images.githubusercontent.com/89189872/140664491-9870a22e-94a4-47c7-8454-ed6f45f5a0b7.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 7b95439 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by estebandellasilva** [comment]
After some testing it appears that hidden iss properly applied if you unhide and then hide - but for lootet stuff it is only applied to the first layer -> you have to unhide and hide manually for it to function properly

**Comment by Zhid13** [comment]
I knew I wasn't going mad writing my own report on this issue and then seeing it dissapear when I was taking screenshots. So far I've tested with an IFAK pouch not showing any of the singular bandages and gauze in it, nor showing them in the `E` menu. However the pills I have that are themselves inside plastic bottles in my IFAK pouch did show up until I "refreshed" it's hidden contents status. I haven't done any testing further and believe it should be looked into if you can still see problems in items that were already spawned in the world such as MREs and IFAKS.

**Comment by ToxiClay** [comment]
I think, personally, the relevant MRE PR #48827 should be reverted in its entirety. It's a nightmare to interact with and doesn't make sense: MREs are printed with the name of the entree on the package. "MRE Package" is not an accurate reflection of how they appear in real life.

I'm not skilled enough with Git to work out how to do it without snapping things in half, though.

**Comment by esotericist** [comment]
> I think, personally, the relevant MRE PR #48827 should be reverted in its entirety. It's a nightmare to interact with and doesn't make sense: MREs are printed with the name of the entree on the package. "MRE Package" is not an accurate reflection of how they appear in real life.

that (and the other attendant issues) can be addressed without reverting the mechanism.

one of the advantages of the nested MREs is highly valuable to me: the ability to open the outer package, and eat *some of the contents*, while leaving others still sealed so they'll stay good for later.

we don't need to discard that benefit while trying to get back readability and convenience.

**Comment by ToxiClay** [comment]
> one of the advantages of the nested MREs is highly valuable to me: the ability to open the outer package, and eat _some of the contents_, while leaving others still sealed so they'll stay good for later.

Can we escape that by simply setting each individual content to have an indefinite shelf life? Then we can do whatever we like.
