### ISSUE TITLE
Still an absurd number of zombies in parks

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#52698]
### Describe the bug

Despite #49086 , there are still a VERY large number of zombies spawning in parks.

### Steps To Reproduce

1. Find a park.
2. Look at all those zambos.

### Expected behavior

Maybe ten to fifteen zombies in a park.

### Screenshots
The screenshot below was taken on a world with a spawn rate of 1.0, and no dynamic spawns.
![image](https://user-images.githubusercontent.com/2125926/140660924-f73428d3-571c-4ffa-928e-26d3d0dc68e2.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 7b95439 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations]
]

**Comment by Inglonias** [comment]
I want to clarify that this is not the case in EVERY park I see, but many of them still have a lot of monsters for no apparent reason.

**Comment by RoyBerube** [comment]
I tried teleporting around a freshly generated map and found no massive spawns. Tried about 30 locations. If anything, I noticed too few spawns in the parks.

This looks like it will be a hard bug to isolate.

**Comment by Inglonias** [comment]
Not necessarily. If we mathematically audit the json files, we should be good. I suspect the issue here is less "too many spawns" and more "too much variance"

**Comment by Inglonias** [comment]
As an example, the [very first park](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/mapgen/park.json#L2) defined in park mapgen has a 1 in 60 chance for the monster group GROUP_PARK_PLAYGROUND to spawn. There are **FIVE HUNDRED AND FORTY FOUR CHANCES TO HIT THAT GROUP.** Granted, the most likely outcome of that group is "nothing", but that is... still frightening.
