### ISSUE TITLE
Add a linux installer.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#527]
As a preamble to packaging, add an install target to the Makefile.

See http://stackoverflow.com/questions/528399/what-should-linux-unix-make-install-consist-of for some basics.

**Comment by tvm1** [comment]
I will give it a shot.

**Comment by tvm1** [comment]
Well, after lengthy investigation I can say, that the make install works as it is.

1) make PREFIX=/usr/local USE_HOME_DIR=1
2) make install PREFIX=/usr/local
3) profit

It should be just probably made obvious in COMPILING that if the user wants to install CDDA in /usr/local that he needs to use PREFIX during make/install and also that the USE_HOME_DIR needs to be enabled.

This issue can be probably closed.
