### ISSUE TITLE
Divide No Hope into some submods

### ISSUE THREAD

**Issue by waveyl** [CleverRaven/Cataclysm-DDA#52707]
# Is your feature request related to a problem? Please describe.
Some players like low spawn rate but dislike Extra Bandits or Cars to Wrecks, and others do the opposite.

# Describe the solution you'd like
Divide No Hope into some submods so players can choose what to enable and what to disable.

**Comment by Night-Pryanik** [comment]
I'm afraid that's not gonna happen. Small submods or variations don't fit our guidelines for having mods in main repository.
