### ISSUE TITLE
`use_default_colors();` -> transparency for ncurses interface

### ISSUE THREAD

**Issue by normen** [CleverRaven/Cataclysm-DDA#52702]
# Is your feature request related to a problem? Please describe.
Currently the ncurses interface doesn't allow for transparent background colors in compatible terminals and doesn't pick up on the configured colors.

# Describe the solution you'd like
In a local version I added the `use_default_colors();` command at the end of the `catacurses::init_interface()` function in `ncurses_def.cpp` which seemed to yield the desired result.

# Describe alternatives you've considered
I could send a PR but it seems overkill for one line?

# Additional context
Heres a screenshot of my local version with transparent background:
<img width="1436" alt="Bildschirmfoto 2021-11-08 um 00 54 49" src="https://user-images.githubusercontent.com/3270528/140666730-eb5e5e36-591f-49f3-8978-a50f877bbe05.png">

**Comment by ZhilkinSerg** [comment]
> I could send a PR but it seems overkill for one line?

If you would not send a PR - it won't be ever resolved.

**Comment by normen** [comment]
> If you would not send a PR - it won't be ever resolved.

Okay, I'll pack it up one of these days. Unless anyone knows of possible issues with this change.

**Comment by Zireael07** [comment]
PR has been sent, but closed?

**Comment by ZhilkinSerg** [comment]
It is a draft and not finished.
