### ISSUE TITLE
Mod support for monster subgroups from #52323

### ISSUE THREAD

**Issue by LyleSY** [CleverRaven/Cataclysm-DDA#52714]
# Is your feature request related to a problem? Please describe.
Monster spawn sub groups do not spawn from mods

# Describe the solution you'd like
They do

# Describe alternatives you've considered
Leave DinoMod with redundant spawn groups

# Additional context
Discovered working on #52701

**Comment by dseguin** [comment]
Didn't realize it doesn't work for mods. Sorry about that, I'll get that fixed soon.

**Comment by LyleSY** [comment]
My bad, thanks for figuring this out!
