### ISSUE TITLE
Smoking racks (f_smoking_rack) cannot be activated when fully loaded with food, can now only have 375 charges of charcoal.

### ISSUE THREAD

**Issue by ProfoundDarkness** [CleverRaven/Cataclysm-DDA#52711]
### Describe the bug

Smoking racks (f_smoking_rack) currently has more volume for food to smoke than capacity for fuel resulting in being unable to light up the smoking rack when fully loaded with both food and fuel.

Formerly this constructed item could be loaded up with 2000 units of charcoal.  It still allows up to 40L of food to be loaded.  This results in needing 125 units of fuel MORE than can possibly be loaded in order to activate it when fully loaded with food.

### Steps To Reproduce

(optional) wish for a lighter...  Not required.
1. Construct a smoking rack (mutation hammer space helps with this, or editing the map to place the furniture f_smoking_rack).
2. Wish for a bunch of charcoal (2000 units for ex).
3. Wish for 40L of food (80 blueberries works here).
4. If using hammer space mutation, remove it here.
5. Examine the smoking rack - Fill it with the maximum amount of food (80 blueberries).
6. Examine the smoking rack - Reload with the maximum amount of charcoal (375 is all that's allowed).
7. Examine the smoking rack - Observe that the light up option requires an additional, impossible, 125 units of charcoal to proceed.

### Expected behavior

The simplest seems to either the change the amount of charcoal fuel that can be loaded to match or exceed the 40L possible  food that can be loaded (revert, at least in part) or to change the maximum possible food loaded to match or be below the maximum fuel that can be loaded.

### Screenshots

![cdda-er-smoking_rack](https://user-images.githubusercontent.com/13865432/140769235-741d49a3-82d5-45ed-9638-4b03d29a9798.png)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.3 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-3763-g74156e1745 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth]
]

### Additional context

I personally would prefer having a large capacity (need not be 2000) for the constructed version but either route that involves not having to carefully load the smoker up with a valid amount of food for the fuel I'm allowed to deposit is desired.

I've included a save with the smoker setup like in the shown in the picture (basically at the end of replication steps).
[Test_Smokers.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7498114/Test_Smokers.zip)

according to a bisect 290dd1a23702bf7dd0d23e338db6728e6f5b7096 is notable...  Changing the psuedo item of the smoker from "pseudo_char_smoker" to "char_smoker" ... which explains the 375 charcoal limit.  Also changing f_smoking_rack_active in a similar way.  Right... the pseudo_char_smoker got obsoleted.

**Comment by PatrikLundell** [comment]
It looks like I failed to account for the capacity. I checked the capacity of a number of items, but failed to check all of them.
I'll investigate and return either here or your commit. To clarify: a change of capacity was not intended.
