### ISSUE TITLE
Attempting to spawn an overmap special crashes the game

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#52719]
### Describe the bug

Opening the Overmap Editor and attempting to spawn a special (a military base, for example) causes the game to crash.

### Steps To Reproduce

1. Create a new game
2. Open the Overmap Editor
3. Attempt to place a map special

### Expected behavior

I expected no crash.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 3b51b62 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

The game never generates a debug or a crash file.

**Comment by wapcaplet** [comment]
I was not able to reproduce this. Spawned a house, lab, and a mil_base with no problem.

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-3781-g 3df2f1de5e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by ToxiClay** [comment]
Weird. I used the Catapult launcher to download build 3b51b62, `cdda-experimental-2021-11-07-1130`, specifically the MSVC build, and crashed consistently. Reproduction evidence:

https://user-images.githubusercontent.com/13796683/141088324-217f791c-aac1-4bf8-a23c-901d12ee8789.mp4

**Comment by ToxiClay** [comment]
Trying the non-MSVC build crashes as well, but a tiny bit more gracefully:

![image](https://user-images.githubusercontent.com/13796683/141089915-38169964-0713-4115-91dc-44e663f2cde7.png)

```
The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 3b51b62
TYPE: Signal
MESSAGE: SIGABRT: Abnormal termination
STACK TRACE:

  #0
    (dbghelp: @0x7ff67d30623f[cataclysm-tiles.exe+0x1d623f]), 
    (libbacktrace: register_frame_ctor+0x7ff53bdd41af@0x7ff67d30623f),
    (libbacktrace: 0x7ff67d30623f    [unknown src]:0    [unknown func]),
  #1
    (dbghelp: @0x7ff67d2efd21[cataclysm-tiles.exe+0x1bfd21]), 
    (libbacktrace: register_frame_ctor+0x7ff53bdbdc91@0x7ff67d2efd21),
    (libbacktrace: 0x7ff67d2efd21    [unknown src]:0    [unknown func]),
  #2
    (dbghelp: @0x7ff67d2eff4f[cataclysm-tiles.exe+0x1bff4f]), 
    (libbacktrace: register_frame_ctor+0x7ff53bdbdebf@0x7ff67d2eff4f),
    (libbacktrace: 0x7ff67d2eff4f    [unknown src]:0    [unknown func]),
  #3
    (dbghelp: raise+0x21b@0x7ffc72eaadfb[msvcrt.dll+0x2adfb]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #4
    (dbghelp: abort+0x1b@0x7ffc72eaf1fb[msvcrt.dll+0x2f1fb]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #5
    (dbghelp: @0x7ff67d8648af[cataclysm-tiles.exe+0x7348af]), 
    (libbacktrace: register_frame_ctor+0x7ff53c33281f@0x7ff67d8648af),
    (libbacktrace: 0x7ff67d8648af    [unknown src]:0    [unknown func]),
  #6
    (dbghelp: @0x7ff67d86b15e[cataclysm-tiles.exe+0x73b15e]), 
    (libbacktrace: register_frame_ctor+0x7ff53c3390ce@0x7ff67d86b15e),
    (libbacktrace: 0x7ff67d86b15e    [unknown src]:0    [unknown func]),
  #7
    (dbghelp: @0x7ff67d9f4139[cataclysm-tiles.exe+0x8c4139]), 
    (libbacktrace: register_frame_ctor+0x7ff53c4c20a9@0x7ff67d9f4139),
    (libbacktrace: 0x7ff67d9f4139    [unknown src]:0    [unknown func]),
  #8
    (dbghelp: @0x7ff67d86eefb[cataclysm-tiles.exe+0x73eefb]), 
    (libbacktrace: register_frame_ctor+0x7ff53c33ce6b@0x7ff67d86eefb),
    (libbacktrace: 0x7ff67d86eefb    [unknown src]:0    [unknown func]),
  #9
    (dbghelp: @0x7ff67d86ff01[cataclysm-tiles.exe+0x73ff01]), 
    (libbacktrace: register_frame_ctor+0x7ff53c33de71@0x7ff67d86ff01),
    (libbacktrace: 0x7ff67d86ff01    [unknown src]:0    [unknown func]),
  #10
    (dbghelp: @0x7ff67d326144[cataclysm-tiles.exe+0x1f6144]), 
    (libbacktrace: register_frame_ctor+0x7ff53bdf40b4@0x7ff67d326144),
    (libbacktrace: 0x7ff67d326144    [unknown src]:0    [unknown func]),
  #11
    (dbghelp: @0x7ff67d4275cc[cataclysm-tiles.exe+0x2f75cc]), 
    (libbacktrace: register_frame_ctor+0x7ff53bef553c@0x7ff67d4275cc),
    (libbacktrace: 0x7ff67d4275cc    [unknown src]:0    [unknown func]),
  #12
    (dbghelp: @0x7ff67d4297ca[cataclysm-tiles.exe+0x2f97ca]), 
    (libbacktrace: register_frame_ctor+0x7ff53bef773a@0x7ff67d4297ca),
    (libbacktrace: 0x7ff67d4297ca    [unknown src]:0    [unknown func]),
  #13
    (dbghelp: @0x7ff67d334860[cataclysm-tiles.exe+0x204860]), 
    (libbacktrace: register_frame_ctor+0x7ff53be027d0@0x7ff67d334860),
    (libbacktrace: 0x7ff67d334860    [unknown src]:0    [unknown func]),
  #14
    (dbghelp: @0x7ff67e4cecf7[cataclysm-tiles.exe+0x139ecf7]), 
    (libbacktrace: register_frame_ctor+0x7ff53cf9cc67@0x7ff67e4cecf7),
    (libbacktrace: 0x7ff67e4cecf7    [unknown src]:0    [unknown func]),
  #15
    (dbghelp: @0x7ff67d1313c1[cataclysm-tiles.exe+0x13c1]), 
    (libbacktrace: register_frame_ctor+0x7ff53bbff331@0x7ff67d1313c1),
    (libbacktrace: 0x7ff67d1313c1    [unknown src]:0    [unknown func]),
  #16
    (dbghelp: @0x7ff67d1314d6[cataclysm-tiles.exe+0x14d6]), 
    (libbacktrace: register_frame_ctor+0x7ff53bbff446@0x7ff67d1314d6),
    (libbacktrace: 0x7ff67d1314d6    [unknown src]:0    [unknown func]),
  #17
    (dbghelp: BaseThreadInitThunk+0x14@0x7ffc712c7034[KERNEL32.DLL+0x17034]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #18
    (dbghelp: RtlUserThreadStart+0x21@0x7ffc731e2651[ntdll.dll+0x52651]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
```

**Comment by Night-Pryanik** [comment]
@ToxiClay did you try to spawn special in a world without mods (or default mods only)? Did you try to spawn special NOT on your character's position?

**Comment by Night-Pryanik** [comment]
I can confirm crash.

**Comment by Photoloss** [comment]
Can confirm on Windows 10, new world default mods and similar cryptic message and trace log to ToxiClay above.

However, I noticed this does not happen for _all_ map specials, and those which do can still be spawned in the regular map (debug->m->M->O) but not the Overmap editor. The "quiverfull" house crashes for me and a lot of "interesting" specials do so I suspect it might be tied to orientation, adjacency or some other tile metadata not categorically required by all specials.

Here's a crash log from a few days ago:

The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 3b51b62
TYPE: Signal
MESSAGE: SIGABRT: Abnormal termination
STACK TRACE:

  #0
    (dbghelp: @0x7ff6deca623f[cataclysm-tiles.exe+0x1d623f]), 
    (libbacktrace: register_frame_ctor+0x7ff59d7741af@0x7ff6deca623f),
    (libbacktrace: 0x7ff6deca623f    [unknown src]:0    [unknown func]),
  #1
    (dbghelp: @0x7ff6dec8fd21[cataclysm-tiles.exe+0x1bfd21]), 
    (libbacktrace: register_frame_ctor+0x7ff59d75dc91@0x7ff6dec8fd21),
    (libbacktrace: 0x7ff6dec8fd21    [unknown src]:0    [unknown func]),
  #2
    (dbghelp: @0x7ff6dec8ff4f[cataclysm-tiles.exe+0x1bff4f]), 
    (libbacktrace: register_frame_ctor+0x7ff59d75debf@0x7ff6dec8ff4f),
    (libbacktrace: 0x7ff6dec8ff4f    [unknown src]:0    [unknown func]),
  #3
    (dbghelp: raise+0x21b@0x7ffaffccadfb[msvcrt.dll+0x2adfb]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #4
    (dbghelp: abort+0x1b@0x7ffaffccf1fb[msvcrt.dll+0x2f1fb]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #5
    (dbghelp: @0x7ff6df2048af[cataclysm-tiles.exe+0x7348af]), 
    (libbacktrace: register_frame_ctor+0x7ff59dcd281f@0x7ff6df2048af),
    (libbacktrace: 0x7ff6df2048af    [unknown src]:0    [unknown func]),
  #6
    (dbghelp: @0x7ff6df20b15e[cataclysm-tiles.exe+0x73b15e]), 
    (libbacktrace: register_frame_ctor+0x7ff59dcd90ce@0x7ff6df20b15e),
    (libbacktrace: 0x7ff6df20b15e    [unknown src]:0    [unknown func]),
  #7
    (dbghelp: @0x7ff6df394139[cataclysm-tiles.exe+0x8c4139]), 
    (libbacktrace: register_frame_ctor+0x7ff59de620a9@0x7ff6df394139),
    (libbacktrace: 0x7ff6df394139    [unknown src]:0    [unknown func]),
  #8
    (dbghelp: @0x7ff6df20eefb[cataclysm-tiles.exe+0x73eefb]), 
    (libbacktrace: register_frame_ctor+0x7ff59dcdce6b@0x7ff6df20eefb),
    (libbacktrace: 0x7ff6df20eefb    [unknown src]:0    [unknown func]),
  #9
    (dbghelp: @0x7ff6df20ff01[cataclysm-tiles.exe+0x73ff01]), 
    (libbacktrace: register_frame_ctor+0x7ff59dcdde71@0x7ff6df20ff01),
    (libbacktrace: 0x7ff6df20ff01    [unknown src]:0    [unknown func]),
  #10
    (dbghelp: @0x7ff6decc6144[cataclysm-tiles.exe+0x1f6144]), 
    (libbacktrace: register_frame_ctor+0x7ff59d7940b4@0x7ff6decc6144),
    (libbacktrace: 0x7ff6decc6144    [unknown src]:0    [unknown func]),
  #11
    (dbghelp: @0x7ff6dedc75cc[cataclysm-tiles.exe+0x2f75cc]), 
    (libbacktrace: register_frame_ctor+0x7ff59d89553c@0x7ff6dedc75cc),
    (libbacktrace: 0x7ff6dedc75cc    [unknown src]:0    [unknown func]),
  #12
    (dbghelp: @0x7ff6dedc97ca[cataclysm-tiles.exe+0x2f97ca]), 
    (libbacktrace: register_frame_ctor+0x7ff59d89773a@0x7ff6dedc97ca),
    (libbacktrace: 0x7ff6dedc97ca    [unknown src]:0    [unknown func]),
  #13
    (dbghelp: @0x7ff6decd4860[cataclysm-tiles.exe+0x204860]), 
    (libbacktrace: register_frame_ctor+0x7ff59d7a27d0@0x7ff6decd4860),
    (libbacktrace: 0x7ff6decd4860    [unknown src]:0    [unknown func]),
  #14
    (dbghelp: @0x7ff6dfe6ecf7[cataclysm-tiles.exe+0x139ecf7]), 
    (libbacktrace: register_frame_ctor+0x7ff59e93cc67@0x7ff6dfe6ecf7),
    (libbacktrace: 0x7ff6dfe6ecf7    [unknown src]:0    [unknown func]),
  #15
    (dbghelp: @0x7ff6dead13c1[cataclysm-tiles.exe+0x13c1]), 
    (libbacktrace: register_frame_ctor+0x7ff59d59f331@0x7ff6dead13c1),
    (libbacktrace: 0x7ff6dead13c1    [unknown src]:0    [unknown func]),
  #16
    (dbghelp: @0x7ff6dead14d6[cataclysm-tiles.exe+0x14d6]), 
    (libbacktrace: register_frame_ctor+0x7ff59d59f446@0x7ff6dead14d6),
    (libbacktrace: 0x7ff6dead14d6    [unknown src]:0    [unknown func]),
  #17
    (dbghelp: BaseThreadInitThunk+0x14@0x7ffaff667034[KERNEL32.DLL+0x17034]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #18
    (dbghelp: RtlUserThreadStart+0x21@0x7ffb00302651[ntdll.dll+0x52651]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
