### ISSUE TITLE
Game crashes when attempting to create a new character in a world where one died

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#52720]
### Describe the bug

If a character dies in a world, attempting to create a new character in that world causes the game to crash when it finalizes the world.

### Steps To Reproduce

1. Start a character
2. Die
3. Create a new character in the same world
4. ???

### Expected behavior

I suppose I expected the game to not implode when creating a new character.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 3b51b62 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by LeahLuong** [comment]
This issue looks very similar to 1 posted just a little earlier: #52715. May also be related to #52300 or #52329. It's helpful if you do searches for these things before creating duplicate issues which clutter the board.

**Comment by wapcaplet** [comment]
Looks most similar to #52300 since both mention crash after the previous character *not* dying. Closing as a duplicate.
