### ISSUE TITLE
Stoppable Force Collides w/ "Movable" Object

### ISSUE THREAD

**Issue by LeahLuong** [CleverRaven/Cataclysm-DDA#52728]
### Describe the bug

I was driving @ 30mph by full moonlight in my vehicle when I bumped into an airdrop crate. My vehicle was brought to a dead halt & severe damage resulted: the colliding shredder almost shattered & proceeded to fall off, 6 of the front quarterpanels were XX'd, a frame was XX'd, both reinforced headlights were XX'd, an enhanced electric motor was XX'd, a mounted autoclave was XX'd, a smart engine controller was XX'd, & varying levels of damage were dealt to practically every tile of the vehicle. The vehicle was basically fully repaired prior to collision; I think there was a dented rear quarterpanel from sideswiping a Z earlier. The autoclave & engine controller were both sitting on shock absorbers & external components were covered in steel or hard plating. I had to spend 2 in-game days repairing & rebuilding to get back to snuff & was still lacking the electric motor & autoclave.

The crate was seemingly undamaged. Crates can be moved or destroyed by hand so this seems like a ridiculous outcome. I had a similar, prior experience w/ a sandbag barricade: low-speed collision resulting in the shredder falling off & damage propagating throughout the vehicle. I'm not sure if this is some sort of crazy kickback from the shredder or if this issue is related to #48394 but I think vehicle collision mechanics could use a second look. Wooden crates should not be able to nearly destroy a slow-moving, metal deathmobile, nor should single-thick sandbag walls.

On a side note, there may be something wrong w/ the coding for smart engine controller. Repairing the vehicle did not offer to replace the XX'd component despite having a spare processor board on hand. Another time, the controller was dented & I had to pull it out of the vehicle before being able to solder it back to full.

### Steps To Reproduce

1. Drive around @ low speeds in a seemingly solid vehicle, made of metal.
2. Bump into seemingly flimsy things like wooden crates or sandbags.

### Expected behavior

I expected that deathmobile level would increase, because all other skills can increase in level.

### Versions and configuration

Android 0.F-2 Tiles English vanilla

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
