### ISSUE TITLE
Problem defrosting frozen food

### ISSUE THREAD

**Issue by lurkinglikeamofo** [CleverRaven/Cataclysm-DDA#52735]
### Describe the bug

I can't defrost frozen food or packaged liquids with a cooking utensil anymore.

### Steps To Reproduce

1. migo camp start 
2. teleport away
3. spawn in your items necessary (brazier, lighter, cast iron frying pan, planks and food)
4. maybe spawn in a dino suit and winter boots/gloves to survive the cold while you wait for the food to freeze
4. wait for food to freeze, light up your brazier and then try to heat it up/defrost by activating your cooking utensil next to a lit fire

### Expected behavior

It should say "you don't have any items with registered uses" upon activating your fry pan. I used a cast iron fry pan, a copper pot and a canning pot all with the same result. 

### Screenshots

![Untitled](https://user-images.githubusercontent.com/93702587/141043396-b99898d7-a6a5-40c5-a091-63681570a5ce.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 3a0bbea [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Maybe this is as intended but when i asked on the discord nobody could help and one suggested i make a bug report. I'm not sure if you could replicate it on any other start then a mi-go camp start as that's the only one i tried. Also, i updated to 3df2f1d from 3a0bbea to check if it was my version and it wasn't.

**Comment by RoyBerube** [comment]
PR #52708 addressed this problem. I just tested a frying pan by a fire and is behaving properly on activation.
