### ISSUE TITLE
Add uniforms/outfits that can be easily configured and changed into

### ISSUE THREAD

**Issue by ccaviness** [CleverRaven/Cataclysm-DDA#52730]
# Is your feature request related to a problem? Please describe.
I think it would be very useful to have configurable uniforms/outfits with the ability to easily change into them. I find myself frequently removing various armor and other clothing when, for example, spending time outside in the summer crafting or working on vehicles, and then often forgetting to put all the same piece back on before entering a dangerous scenario.

# Describe the solution you'd like
I'd like to have a configurable set of outfits. Maybe shorts/shoes/t-shirt for safe summer work, armor/mask/helmet/gloves/etc. for raiding, maybe a winter raiding outfit, and so on. Then, I could swap into the work clothes so I don't overheat trying to change the engine on my vehicle while wearing plate mail.

# Describe alternatives you've considered
I have considered no alternatives.

# Additional context
An initial implementation that's just a collecting of exact items would be good, but I can imagine a more complex setup where you could say "use any long pants".

**Comment by l29ah** [comment]
Yeah would be nice to have a simple way to wear/take off all the hand armor due to its impact on crafting speed.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
