### ISSUE TITLE
Washing items with nearby filthy items prevents input of quantity to wash

### ISSUE THREAD

**Issue by kholat** [CleverRaven/Cataclysm-DDA#52737]
### Describe the bug

so if you try to wash something, as expected you get the first picture.
However, each nearby filthy item gets assigned a number from 0 to 9, meaning you can no longer select the quantity of an item to wash (say we want 3 out of 10 game watches). 
If you press the number 3, it will select the appropriate item instead of 3 of the currently selected item, which is seen in the second pic (I want 3 game watches, but "3" is assigned to "boxer shorts" meaning I have to do either ALL game watches or 0, which are not wanted outcomes because for instance I might be lacking detergent or dont want to waste time washing all of them).

### Steps To Reproduce

1. Have 11 different filthy items. Have higher quantity of 1 item.
2. Have washing kit or equivalent with washing agent.
3. Activate the kit and try to select some quantity to be washed, notice you cant do it.

### Expected behavior

Perhaps not assign numbers to nearby items? Not sure how this should be fixed.

### Screenshots

![cataclysm-tiles_2021-11-10_09-46-43](https://user-images.githubusercontent.com/33296847/141081083-35ebe2e1-8e2f-4061-95ee-47a5af6f16d0.png)
![cataclysm-tiles_2021-11-10_09-49-31](https://user-images.githubusercontent.com/33296847/141081128-8fd99acd-9c77-491a-b9ff-72eda96d4bf2.png)

### Versions and configuration

- OS: win 10
- Game version: 60d9697 (tiles) 
- Mods: NoHope, BlazeIndustries, Magiclysm, Disable NPC Needs

### Additional context

N/A

**Comment by kholat** [comment]
For some reason the first pic is not embedded idk why, just github things, you have to click the link.

**Comment by mqrause** [comment]
> 
> 
> For some reason the first pic is not embedded idk why, just github things, you have to click the link.

It's missing the closing `)`. Or rather it got moved behind the second image.

**Comment by kholat** [comment]
> > For some reason the first pic is not embedded idk why, just github things, you have to click the link.
> 
> It's missing the closing `)`. Or rather it got moved behind the second image.

Oh thanks! fixed
