### ISSUE TITLE
"Walkable actions", being able to move during some actions

### ISSUE THREAD

**Issue by Fonso0** [CleverRaven/Cataclysm-DDA#52740]
# Is your feature request related to a problem? Please describe.
Do some actions really need my character to stay still? 
Like wielding a weapon from a pocket in the clothes you wear, I think one can move their legs while doing that.

# Describe the solution you'd like
My idea is to make possible to your character to move while doing some "walkable action" X.

# Describe alternatives you've considered
I think it might work like this:
- you tell your character to do a "walkable action" X that costs 420 action points;
- now your character starts doing X and is at 0%, to complete the action he/she must spend the 420 ap only on moving (on flat terrain) or waiting;
- he/she moves horizontally or vertically 3 times for a cost of 300 ap, X is at 71% and needs only 120 ap to finish;
- he/she waits 1 time for a cost of 100 ap, X is at 95% and needs only 20 ap to finish;
- he/she waits (not move) 1 more time for a cost of just 20 ap (100 ap if we moved), because X only needed 20 ap to finish.

# Additional context
And this is all.
English is not my native language, so if you've read anything weird I'm sorry.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
