### ISSUE TITLE
Hobbies can exceed trait limit if selected last

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#52746]
### Describe the bug

You are normally only allowed 12 points of positive and 12 points of negative traits, but if you select your traits first and then go back and select a hobby that gives you traits, those will be added on top. If you do it the other way around, the hobby traits do count towards your max.

### Steps To Reproduce

1. Start new game
2. Select 12 points of positive and/or negative traits
3. Select hobbies that bring you over the the trait total, in such a way that the end result is still +/-0.
4. Start the game to verify the game considers this stat spread valid.

### Expected behavior

I don't think Hobby traits should count towards your max at all. And many of them don't, because they don't select traits that are already in the trait list.

However, the least I would expect is that whether hobby traits do or don't let you go over the max, it shouldn't matter _when_ you select the hobby.

### Screenshots

![image](https://user-images.githubusercontent.com/5107449/141167299-f634fd10-5d33-47f9-a79e-45e225d0ca3f.png)
I have 15 points of negative traits here due to selecting the "Butchering" hobby after already having selected 12 points of negative traits

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 6db9695 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Extra Mutated Scenarios [extra_mut_scens],
    Fuji's Military Profession Pack [fuji_mpp]
]

**Comment by hexagonrecursion** [comment]
Confirmed: You can't take the genetic downward spiral trait if you have sleeping pill dependence, but you can take sleeping pill dependence even if you already have genetic 
downward spiral resulting in -14/-12

Traits we get from professions and scenarios do not count toward the cap, but we forgot to also exclude backgrounds (previously known as hobbies).
https://github.com/CleverRaven/Cataclysm-DDA/blob/c7004d1567e9b0c717ddc722c6a95f8abe720eb2/src/newcharacter.cpp#L1248-L1267

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 9473cf6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by I-am-Erk** [comment]
I don't know if it's worth fixing this, as the trait cap is a feature we would like to phase out in the long run.

**Comment by Terrorforge** [comment]
Trait limit was removed, this no longer matters.
