### ISSUE TITLE
Makeshift insecticide grenades never stop spewing insecticide smoke

### ISSUE THREAD

**Issue by Scorch-Mechanic** [CleverRaven/Cataclysm-DDA#52753]
### Describe the bug

Makeshift insecticidal grenades never stop emitting insecticidal smoke. The non-makeshift variant seems to stop correctly, but the home-made kind constructed out of bleach, superglue, and insecticide powder does not. 

### Steps To Reproduce

1. Acquire a makeshift insecticidal grenade. Crafted or debug spawned both work for this. 
2. Wield, pull pin, throw.
3. Wait however long you want to wait. I waited more than 24 hours and the first test grenade is still going.
4. Carry one in your backpack and explore a wasp nest, I guess? Wear a gas mask. Become Bugdeath, Killer of Bugs Dead.

### Expected behavior

Makeshift insecticidal grenades should stop smoking after a few seconds, like their factory-made cousins.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 6db9695 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

I include my test world save. You can find some perpetually smoking makeshift insecticidal grenades on the ground, and even fixings to craft more if you like. 
[Fanny's Knob_home_of_wasp_murderer.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7517643/Fanny.s.Knob_home_of_wasp_murderer.zip)

**Comment by Hirmuolio** [comment]
Seems like it just copies from wrong item.

`"copy-from": "gasbomb"` instead of `"copy-from": "gasbomb_act"`.
