### ISSUE TITLE
Constantly interrupted during autodrive at night with a dialogue window telling me that I heard my combustion engine starting

### ISSUE THREAD

**Issue by Scorch-Mechanic** [CleverRaven/Cataclysm-DDA#52752]
### Describe the bug

Autodriving to a destination at night is being constantly interrupted by a dialogue window informing me that I have just heard my 4.5L V8 gasoline engine starting, presumably caused by my smart controller turning it on. Every time this window appears I am given the option to cancel autodrive, continue anyways, or ignore all further interruptions. This behavior is unwanted.

### Steps To Reproduce

1. Make it nighttime.
2. Create a hybrid vehicle, give it fuel and battery power, and set the battery charge level and smart controller so that while driving, the engine will have to turn on. OR load the attached save.
3. Autodrive to a location. My destination in the attached save is the milk farm to the southeast.
4. Have the game pause repeatedly to tell you every time the combustion engine turns on when the battery threshold is reached.

### Expected behavior

Not to have autodrive paused repeatedly. I presumably know that my engine will turn on and off according to my smart controller's programming. Previously the only notification would be a message in the log and perhaps some vrooms or whatever. 

### Screenshots

![Screenshot 2021-11-10 18 48 11](https://user-images.githubusercontent.com/5760760/141230064-37463556-740b-4614-88e9-459f50dde234.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 6db9695 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

### Additional context
EDIT: looks like the save I attached didn't upload properly? This should fix it.
[Shady Knob_autodrive_annoyance.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7522248/Shady.Knob_autodrive_annoyance.zip)

**Comment by LeahLuong** [comment]
Is "autodrive" a new experimental thing?? I tried to use the simple autopilot thingy you can craft in stable but it doesn't seem to have that option.

**Comment by Scorch-Mechanic** [comment]
Autodrive is triggered from the map view by selecting a destination with `W` and confirming it with the same key. However,  experimental got a new version of it a few months ago that makes it so that even driving large vehicles through narrow and complicated streets, it does not crash you into things. 
Here is a demonstration of the new system:
https://youtu.be/tyNoqQRC_u0?t=195
