### ISSUE TITLE
Prone movement speed is far too slow.

### ISSUE THREAD

**Issue by jumjummju** [CleverRaven/Cataclysm-DDA#52756]
# Is your feature request related to a problem? Please describe.
Currently, moving a tile while prone takes 15x as many moves as walking a tile does, making prone movement speed roughly 15 seconds per meter-ish travelled. This is obscenely slow if we assume the character is trying to army crawl.

# Describe the solution you'd like
I decided to test how fast I could army crawl on my living room floor at 2 in the morning because my priorities are out of whack and I have discovered something: I am out of shape. Also, my knees hurt.

More relevant to the discussion, while I didn't have a stopwatch on hand, I found even my out-of-shape self could army crawl around at fairly close to walking speed, or maybe a bit slower, but nowhere near 1/15th the speed. It was, however, exhausting. I also tried crawling around without using my legs, to simulate a survivor who's crawling due to broken legs, and it was a fair bit more exhausting and about half as fast, and still managed to hurt my knees.

**The point is:** If I had to ballpark a more proper cost, it would be a 50% BMC penalty when prone, so that an average, unencumbered survivor would take 150 moves to travel one tile while prone. **BUT** there should be a stamina cost to travelling like this, perhaps a bit below the cost of running. The BMC penalty of x15 might be more accurate if the survivor has a broken arm or two, however, since it's about as slow as I'd imagine wriggling around would be. And maybe broken legs could double the BMC as well, if it doesn't already.

# Describe alternatives you've considered
I'm currently ignoring other methods of moving around while prone, such as rolling around or... I don't know, doing the worm and hoping to impress the undead with your style. To get around the stamina issue, one alternative is to have two "prone" modes, and have the current, very slow one be called "lurk" or something while the other acts as "running while prone" and moves as fast/drains stamina like I suggested, but this is probably a bit excessive since prone isn't used too often anyway and a slower "lurk" can be emulated by just pausing a few turns every tile.

# Additional context
Naturally my IRL tests only involved someone completely unencumbered, so I'm not entirely sure how much a loaded backpack or armor would get in the way, but judging by how soldiers in boot camp might train by army crawling with gear on, I don't think it'd get in the way that vastly much more than it already does for, say, running. Maybe wielding something would also slow it down, but I didn't really want to crawl around on my floor at 2 in the morning while also carrying my sword. People would think I'm weird!

**Comment by ZhilkinSerg** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/38b23292bd5531111be956325c2fe0fb22d85997/data/json/move_modes.json#L70

**Comment by jumjummju** [comment]
> https://github.com/CleverRaven/Cataclysm-DDA/blob/38b23292bd5531111be956325c2fe0fb22d85997/data/json/move_modes.json#L70

Strange, is that supposed to mean prone movement is 1/5th the speed of walking? Cuz I tested it in game and it took 1500 moves to move one tile instead of 500 (and imo the cost should be closer to 150/200 instead)

**Comment by Stephen2** [comment]
I dropped a joint on myself, which burned my legs up, which made me fall prone
![image](https://user-images.githubusercontent.com/4276422/141655445-a197f9bd-a277-4956-a56b-880aa3078802.png)

I think ~100,000 moves is too many, and thought of this thread, maybe there's some relationship between @jumjummju seeing larger numbers than expected, and this

**Comment by ZhilkinSerg** [comment]
You have both of character legs broken.

**Comment by Stephen2** [comment]
Oh for sure, my guy is screwed, but 100,000 moves? lol that's...  maybe it's right :shrug: it just seemed off by x100 than reasonable

Also, the figure may cut off and go to a 7th digit, can't tell

**Comment by jumjummju** [comment]
Not just broken legs but your arms are also *almost* broken too *and* you're in severe pain so at that point you're basically just writhing around the floor on fire. 100k  is extremely excessive but at the point you're at it'd probably be more accurate to just make you immobile. 

As I touched on the post though, if a character has two broken legs but is otherwise uninjured and their arms still work, the movement cost *should* probably be around 300 to 400 IMO. But that would be before pain or arm damage factors in. All 4 limbs broken? Probably immobile.

**Comment by Stephen2** [comment]
Right, agreed. But the more I think about it, the more I'm certain that 100,000 moves means something is wrong with the maths - as you showed it is already too high when in good shape, and I showed it scales to crazyness if you have negative effects.

**Comment by kevingranade** [comment]
To clarify, I tested locally and I'm seeing 15X move cost when prone without any broken limbs, so it does seem like there's something wrong.

**Comment by Stephen2** [comment]
Thanks @kevingranade :partying_face:
