### ISSUE TITLE
Impossible to heat clean water with tools that can boil water

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#52763]
### Describe the bug

That's really troublesome in cold weather as your clean water reserves freeze, and you can't reheat it, only produce more with your coffeemaker/charcoal smoker/etc, given you have a `water` source. Maybe add a recipe making water from clean water?

### Steps To Reproduce

`a`ctivate a charcoal smoker, note it doesn't offer to heat anything.

### Expected behavior

Being able to thaw liquids with tools that allow making `clean water (hot)` from `water (frozen)`.

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.F-3785-ge79ee6a008-dirty [64-bit]
- Graphics Version: Curses
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by NetSysFire** [comment]
Basically a duplicate of #52394

**Comment by RoyBerube** [comment]
Charcoal smoker does not have any use action. This may be an oversight, because it can be used for cooking.

Tools with the use action "HOTPLATE" will allow heating up and thawing of food.  The charcoal smoker does not have that flag.
