### ISSUE TITLE
Peeking From Behind Cover When Crouched

### ISSUE THREAD

**Issue by ChrispyChris** [CleverRaven/Cataclysm-DDA#52764]
# Is your feature request related to a problem? Please describe.
I've been playing around more with stealth and thought it would be nice to have a "peek over cover" option for things like sofas, pool tables, or other items of cover. Rather than standing up and possibly exposing yourself to the zombie's line of sight, peeking would help with this.

# Describe the solution you'd like
Allow the peek option to peek above cover you're behind.

# Describe alternatives you've considered
N/A

# Additional context
I don't think this is the most important thing ever, I just figured I would put in a feature request to bring it up and see where it goes from there :).

**Comment by Owlfren** [comment]
You can already do this, I just tried it in the latest experimental, so I'm not sure what you're suggesting be added? Shift+x then point in the direction of the cover, peeking over it without leaving the safety of your current location.
Is this just a case of you missing that feature or am I misunderstanding the issue?

**Comment by ChrispyChris** [comment]
Ahh shoot @Owlfren you are correct. The cover I was trying behind was more than one space so it was showing odd. I apologize for this. Closing thread.

Thanks!

**Comment by Owlfren** [comment]
Always happy to help! And trust me, I've made worse blunders recently myself so I know the feeling intimately. 😆
