### ISSUE TITLE
New military healing item, MSX32.

### ISSUE THREAD

**Issue by ISuckM8** [CleverRaven/Cataclysm-DDA#52761]
# Is your feature request related to a problem? Please describe.

No.

# Describe the solution you'd like.

A new item called "MSX32", AKA the "Military Stimpak". How it works: You use it on a limb (and ONLY one limb) to slightly heal the limb (half a bar max), stop bleeding, and reduce your pain levels a bit. The downside is that it increases your thirst, hunger, and tiredness. It will only spawn in labs, and rarely on military personnel. It could only be used one time, then you'll have to throw it away.

# Describe alternatives you've considered

Balance the RX12 jet injector.

# Additional context

**Comment by Saicchi** [comment]
You meant this addition as a mod or in the main game? If it's in the main game can you give an example of its real life counterpart that gives visible regeneration like that?

**Comment by ISuckM8** [comment]
> You meant this addition as a mod or in the main game? If it's in the main game can you give an example of its real life counterpart that gives visible regeneration like that?

XStat is the closest one.

**Comment by estebandellasilva** [comment]
> > You meant this addition as a mod or in the main game? If it's in the main game can you give an example of its real life counterpart that gives visible regeneration like that?
> 
> XStat is the closest one.

But that one only stops bleeding or am i wrong

**Comment by ISuckM8** [comment]
> > > You meant this addition as a mod or in the main game? If it's in the main game can you give an example of its real life counterpart that gives visible regeneration like that?
> > 
> > 
> > XStat is the closest one.
> 
> But that one only stops bleeding or am i wrong

Well then, make it so it only stops bleeding and helps a lot with healing (Bandages help)
