### ISSUE TITLE
Gun straps don't hang from torso

### ISSUE THREAD

**Issue by bombasticSlacks** [CleverRaven/Cataclysm-DDA#52779]
### Describe the bug

After the sublocation changes #52468 gun slings are now not conflicting with other strapped items.

This seems to be because the original code for shoulder strap mod is hard coded and sublocations don't have similar hard coding. 

With this said what is the best way to fix this should the hard coded shoulder strap be moved away from?

Should shoulder strap be removed as a gun mod and changed to a clothing item with a pocket that just takes a gun and hangs off your back?

Since the sub locations are in I was planning to add a new front sling for weapons should I also just add a back sling?

### Steps To Reproduce

1. start as survivor
2. spawn a gun
3. add a shoulder strap 
4. wear it
5. see your backpack and gun aren't conflicting 

### Expected behavior

Your backpack and sling should conflict this seems to be a code limitation however. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 610e7d5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Photoloss** [comment]
From a realism standpoint the strap should remain attached to the gun, and the same might apply to certain spear, bow and shield strapping systems as well. In gameplay terms what really matters is the time taken to wield and stow the gun, which should not exceed the second or so it takes to drape a strap over your shoulder. We have non-rigid pockets so it can easily have a base 0 encumbrance while empty as a temporary fix.

**Comment by PatrikLundell** [comment]
Yes, the straps are attached to the items in reality, and should remain so in the game. The proper solution ought to be to modify the code to handle strap-on items "properly", which might include changes to the strap definitions so they would have to specify where they are strapped (which might get messy with weirdly shaped critters).
