### ISSUE TITLE
Staves, greatswords etc. not capable of reach attacks

### ISSUE THREAD

**Issue by Photoloss** [CleverRaven/Cataclysm-DDA#52771]
### Describe the bug

There are a variety of items which logically should be capable of making effective reach attacks but currently aren't. This includes the quarterstaff variants (quarterstaff, ironshod, powered, L-stick) and the "long stick" they are made from, the zweihänder, some variants of nodachi, and a general review of the "battle axe". This list is not complete, there might be other items to which similar considerations apply.

### Steps To Reproduce

Review of in-game item lengths and historical references.

### Expected behavior

First of all the staves. Both in-game and historically these are roughly man-height, similar to many spears (but not pikes, the "long reach attack" weapons). They are also easy to hold on one end, and deliver significantly lethal force on the other when swung as a bashing weapon. The "SPEAR" flag is more contentious, the base staff has no sharp point or other means of inflicting comparable damage in a thrust, but does have some physical stopping power. The powered quarterstaff will not wound either, but definitely will inflict its full shock effect. All of them are thin enough to fit through fences as they basically are slightly thicker spear shafts without the head. The staff sling potentially warrants exclusion as its attachments might make it unsuitable for fully extended melee strikes. A perfect example of a long weapon which definitely should not receive the ability to perform reach attacks is the lajatang: it has large, cumbersome and excessively dangerous blades on _both_ ends forcing the user to grip it near the centre to mitigate the risk of self harm.

Next the zweihänder. Historically also man height, at least if we want a meaningful distinction from the longsword to warrant other gameplay differences. This one is explicitly designed to be held on one end, bringing the full length to bear against the enemy. Unlike the staff its offensive capability at that distance might depend on the target, but the mostly unarmoured flesh of a zombie horde would be easy to cut even with the tip. The properly sharpened version is also very lethal in the thrust, but might hit the limit of what will fit through typical wire fences without scraping so the "SPEAR" flag is not a given. Since reach attacks would be a massive buff to an already powerful endgame weapon I will also note that when wielded at the hilt even a large sword does not really have the momentum to warrant the "Brutal Strike" knockback effect against a non-complying target (fear of the lethal cut would be effective against a sane human, which zombies and ferals definitely are not). Additionally the "Wide Strike" technique seems very unrealistic as-is, instead a skilled swordsman would only really slice additional targets if they miss or glance off the first one. Unlike most polearms the blade can be sharpened pretty far down and still used with halfswording in close quarters, so from a realism standpoint I can't think of a way of balancing this one properly without adding entirely new gameplay mechanics (blade sharpness - the long and heavy blade is under far more strain than its smaller cousins, and would dull quickly hitting hard targets unlike the hammers and spikes on polearms)

Now the nodachi. As-is it basically is just a slightly larger katana which definitely does not warrant reach attacks, nor either version of the "Wide Strike" technique if two-handed sidearms like the longsword don't also get it by default (I am against this, for the record). However the in-game stats are very close to the low end of nodachi parameters. The [2+m long](https://en.wikipedia.org/wiki/%C5%8Cdachi) "horse cutting" versions would both meaningfully differentiate it from the katana (no Rapid Strike on that one!) and warrant reach attacks. The blade is thin and pointed thus suitable for lethal thrusts, however with the curvature and extreme length it would require very high skill and precision to actually thread it through a chicken-wire fence, or even just perpendicular to iron bars, and still strike the target.

Finally the "battle axe", and this might warrant a separate issue but stood out in the context of length. Simply put I have no idea what historical weapon this is referencing. At 1m it seems quite short for a "[dane axe](https://www.youtube.com/watch?v=55Sb93pz1Xk)" and that design wouldn't have the mass to warrant "Brutal Strike" either, although "Wide Strike" cutting through multiple targets makes slightly more sense with a two-handed axe. There are plenty of other designs including some polearms not yet featured separately, but it isn't tagged as explicitly two-handed and most one-handed combat axes were significantly smaller so I would like some clarification as to what "a huge axe designed for warfare" is intended to represent.

### Versions and configuration

Current master branch source code

### Additional context

Some of this should probably go in a "discussion" or "feature request" post instead but "cannot bash zombie with man-height pole of wood while keeping my distance" is illogical enough to warrant bug-like status in my opinion.

**Comment by anoobindisguise** [comment]
Battleaxe definitely shouldn't get a reach attack so that it doesn't invade the halberd's space imo. Clarifying that it is not actually just a random videogame axe would be cool because most axes are pretty tiny, much smaller than the fireaxe in game.

**Comment by Photoloss** [comment]
> Battleaxe definitely shouldn't get a reach attack so that it doesn't invade the halberd's space imo. Clarifying that it is not actually just a random videogame axe would be cool because most axes are pretty tiny, much smaller than the fireaxe in game.

From a gameplay perspective I agree, I don't think we have another high-quality "slow but powerful" cutting weapon if the greatswords get changed (and those basically are fancy polearms). I included it because the creator's intent is not clear to me and the dane axe is the closest historical match I know. If this one becomes the dane axe and one-handed axes are added as well then the distinction would be that the dane axe does not suffer the "polearm" malus against adjacent enemies and is slightly faster, but cannot make piercing or bashing attacks at all and would chip, dull or even break much more easily. Later complex polearms have several reinforcements, the dane axe is "just" a thin sheet of metal stuck on a pole. Without shields I don't see a fundamental reason to have both one- and two-handed battle axes though.

**Comment by catdach** [comment]
> blade sharpness

Sounds kinda like fouling for guns. If you were to add sharpness, that might be a good starting point to reference.

I agree that the zweihänder is long enough and, in general, effective enough at a distance to warrant reach attacks.

>  I will also note that when wielded at the hilt even a large sword does not really have the momentum to warrant the "Brutal Strike" knockback effect against a non-complying target

Maybe not the longsword, but the zweihänder? In my opinion, the zweihänder is probably the weapon that warrants "Brutal Strike" the most! It would at least have similar swinging force to the fire axe (which also has "Brutal Strike"). [for reference](https://youtu.be/knNoib52PBw?t=281). 

Unless you mean that it shouldn't have "Brutal Strike" **in combination** with reach attacks. Hitting a "Brutal Strike" from a tile away would be a bit ridiculous.

>  (fear of the lethal cut would be effective against a sane human, which zombies and ferals definitely are not).

(not sure what _fear_ has to do with it. They are being knocked back by the force of the blow, not from shock and awe)

> "Wide Strike" technique seems very unrealistic as-is, instead a skilled swordsman would only really slice additional targets if they miss or glance off the first one.

I mostly agree with this, but it feels like a difference in circumstances. fighting a horde of zombies isn't quite the same as fighting a group of medieval combatants. I can't really think of a circumstance IRL where a swordsman would even consider trying to hit more than one target. Most of the time, targets wouldn't be close enough together anyway. But zombies? Zombies will stand shoulder to shoulder trying to swarm you (to my knowledge most swordsmen didn't have to deal with being swarmed). I don't see why you couldn't cleave through the limbs of at least 2 unarmored zombies. It may not be a normal technique for a swordsman, but modern problems require modern solutions.

**Comment by Photoloss** [comment]
> Maybe not the longsword, but the zweihänder? In my opinion, the zweihänder is probably the weapon that warrants "Brutal Strike" the most! It would at least have similar swinging force to the fire axe (which also has "Brutal Strike"). [for reference](https://youtu.be/knNoib52PBw?t=281).

That reasoning applies to pretty much every single polearm with any amount of metal at the head. If that is the bar we set then I agree, but I imagine physically forcing back something like a tough or brute requires a little more effort. I suppose as a "crit only" technique it can stay from a conceptual standpoint, but in my mind it is one of the things we can reasonably cut first if necessary for gameplay balance purposes. Way behind Wide Strike mind you.

> (not sure what _fear_ has to do with it. They are being knocked back by the force of the blow, not from shock and awe)

Fear probably would be the more effective deterrent against sane living humans. They have a self-preservation instinct so they will hesitate to approach a giant swinging blade. To my understanding that is how the Montante variant functions against multiple opponents, you basically perform the real-life equivalent of "spin2win" making sure the sword is cutting in their direction often enough they cannot close the distance in the first place without also getting hit in the process.

> I mostly agree with this, but it feels like a difference in circumstances. fighting a horde of zombies isn't quite the same as fighting a group of medieval combatants. I can't really think of a circumstance IRL where a swordsman would even consider trying to hit more than one target. Most of the time, targets wouldn't be close enough together anyway. But zombies? Zombies will stand shoulder to shoulder trying to swarm you (to my knowledge most swordsmen didn't have to deal with being swarmed). I don't see why you couldn't cleave through the limbs of at least 2 unarmored zombies. It may not be a normal technique for a swordsman, but modern problems require modern solutions.

Yeah a limb hit or glancing hit would work. Thing is, not all zombies are unarmoured, some are just innately more resilient, and a fair number of opponents don't have traditional humanoid limbs to begin with. I am not sure how much granularity the system allows but especially from the perspective of an unskilled or novice user reach attacks seem more natural to me than knockback or AoE if something has to give.

Ideally the armed martial arts would then pick up the slack with a "strike adjacent target for reduced damage" "miss/glancing blow recovery" technique or being able to hit another target if you kill the first one. The murder stroke as a stun/down/knockback also makes much more sense there, so in the end you would still be able to perform all these actions with a greatsword but with more progression requirements.

Another thing which comes to mind, mostly as a stopgap for blade sharpness, is to remove the "STURDY" flag. Yes it is a metal bar, but it very obviously is not engineered to be _more_ sturdy beyond the basic resilience of the material. Contrast that with an H-beam, a rounded tube or the langets on a wooden polearm shaft which are explicitly designed to increase structural strength. (Your average metal table leg is not spring-tempered of course, so please do not read this as demanding the flag on the "pipe" item!)

And just to be clear I am deliberately arguing in favour of these nerfs not because they seem the most logical to me but to brainstorm options if gameplay balance demands nerfs in exchange for the addition of reach attacks.

**Comment by catdach** [comment]
> That reasoning applies to pretty much every single polearm with any amount of metal at the head.

You've got me there.

> I am not sure how much granularity the system allows but especially from the perspective of an unskilled or novice user reach attacks seem more natural to me than knockback or AoE if something has to give.

My person interpretation of wide strike is less of a skillful utilization of momentum and more akin to unintentionally swinging clean through a weak point (joint, gap in armor, quantum nether stomach, slime everything, etc.) and hitting the enemy next to them (hence the crit requirement). 

> And just to be clear I am deliberately arguing in favour of these nerfs not because they seem the most logical to me but to brainstorm options if gameplay balance demands nerfs in exchange for the addition of reach attacks.

That's fair, something probably has to be exchanged for the sake of balance. Getting rid of brutal strike and removing STURDY seem like the most reasonable options to me. Wide strike seems like it's one of the unique features of the zweihänder(and other large cutting weapons); without it, I don't think I would ever use it over something like the katana, which is faster and can fit in a scabbard that doesn't conflict with a backpack. Another is that it kind of just turns into a worse version of the steel spear now that it would have reach, taking away wide strike would exacerbate the problem. (Or maybe it would be a better version of the steel spear? it's hard to tell). My point is that it becomes too similar to the already existing reach weapons in the game, so there wouldn't be much reason to use it.

**Comment by Photoloss** [comment]
> My person interpretation of wide strike is less of a skillful utilization of momentum and more akin to unintentionally swinging clean through a weak point (joint, gap in armor, quantum nether stomach, slime everything, etc.) and hitting the enemy next to them

Yeah that ain't gonna happen with proper edge alignment past the first impact. Not with a novice anyway. Again on glancing or killing blows or misses it is much easier to justify.

> Another is that it kind of just turns into a worse version of the steel spear now that it would have reach, taking away wide strike would exacerbate the problem. (Or maybe it would be a better version of the steel spear? it's hard to tell). My point is that it becomes too similar to the already existing reach weapons in the game, so there wouldn't be much reason to use it.

Umm, have you looked up the glaive, naginata or war scythe recently? The greatswords stand out by *not* suffering the polearm malus at the cost of being conductive, having very low bashing damage and being much more difficult to craft. Not sure how loss of the STURDY flag compares to being mostly made out of wood, once implemented the swords should probably dull slightly faster which would then compound the lack of bashing damage.

**Comment by catdach** [comment]
> Umm, have you looked up the glaive, naginata or war scythe recently?

Actually...no I haven't... 

Ok, now it is abundantly clear to me that I've been wrong about this. My apologies. I completely forgot that so many other polearms had wide strike. That being the case, removing wide strike would probably be fine.

I hope I wasn't being too unpleasant about the whole thing, I will make an effort to be better informed in the future.

As a side note, a system for blades becoming dull is probably a no go until quality of life for maintaining equipment is improved (based on what happened to this old PR  #49898). Until then, the weapon becoming generally damaged more quickly seems to be the suggested substitute.

**Comment by Photoloss** [comment]
> I hope I wasn't being too unpleasant about the whole thing

Not at all! I don't know all this stuff by heart either, I'm just quick at looking it up.
