### ISSUE TITLE
leg guards have 0% coverage

### ISSUE THREAD

**Issue by isnaka** [CleverRaven/Cataclysm-DDA#52784]
### Describe the bug

as stated above

### Steps To Reproduce

1. acquire any leg guards
2. observe 0% coverage

### Expected behavior

leg guards to have some coverage 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 610e7d5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    No Rail Stations [No_Rail_Stations],
    Bionic Slots [cbm_slots]
]

**Comment by wapcaplet** [comment]
Confirmed

![image](https://user-images.githubusercontent.com/238395/141598058-11c6e812-d4cb-49d8-bf9d-6f376e5ac5b2.png)

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-3826-g610e7d5502 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Generic Guns [generic_guns],
    Mythical Martial Arts [MMA],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi]
]

**Comment by catdach** [comment]
it seems like this is also a problem for the hard arm guards
