### ISSUE TITLE
Hacksaw window w/ metal grate replaces w/ boarded window; open curtains on grate stop LoS

### ISSUE THREAD

**Issue by Setokaiva** [CleverRaven/Cataclysm-DDA#52782]
### Describe the bug

**Location:** Mine entrance

Interacting with a _window with metal grate_ tile, with the curtains removed. Used _hacksaw_ to cut it, which turned it into a _reinforced boarded-up window_ tile.

Metal grate window with curtains blocked vision even when curtains were open, but when curtains were removed it did NOT. The sheet curtains are acting like the grate is a solid metal vision-blocking wall.

### Steps To Reproduce

1. Obtain _hacksaw_ and visit a _mine entrance_ location
2. Use _hacksaw_ on _window with metal grate_ (with curtains removed)
3. Metal grate disappears and replaces with vision-blocking reinforced boarded window (wooden)

### Expected behavior

I expected the metal grate to be removed and leave an open window frame (wooden). The grate behaved as it should with curtains removed, i.e. I could see through it, so there was no reason to assume there'd be reinforced boards 'under' it.

### Screenshots

![Bug (hacksaw metal grate window)](https://user-images.githubusercontent.com/7769589/141534904-3752b553-69fd-4e92-b094-7791455d3b42.jpg)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 74156e1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Aftershock: Exoplanet [aftershock_exoplanet],
    Stats Through Kills [stats_through_kills]
]

**Comment by Lamberthassel** [comment]
The windows at the mine entrance are `t_metal_grate_window_with_curtain` which means (according to the construction menu) that these are plain windows with glass, curtain, boarded with 2x4s, reinforced with more 2x4s, and finally boarded with pipes and metal sheets.
So, if we want to keep the metal grate window transparent we need to change the way of constructing it cause the current way (https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/construction.json#L4071) looks completely wrong (adding pipes and metal sheets to the boarded reinforced and obviously non-transparent window can't make it transparent).
