### ISSUE TITLE
Error when mutating into spider / getting arachnid mutation

### ISSUE THREAD

**Issue by Spacer-1970** [CleverRaven/Cataclysm-DDA#52792]
### Describe the bug

When you get the arachnid mutation, whether through spider serums or the debug menu, you get an error saying that there is "no valid mood_face found for: THRESH_SPIDER" and whenever your mood changes you get the same "THRESH_SPIDER" error and if you continue to use spider serums after the error the game crashes.

### Steps To Reproduce

1.Take spider serums or use the 'mutate' option in the debug menu and get the arachnid mutation

2.Continue to take spider serums after the error to cause a crash.

### Expected behavior

I expected to get the arachnid mutation without getting any error and to not get the same error whenever my character's mood changes.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 38b2329 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Roach [No_Roach]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7531448/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7531449/debug.log)

**Comment by Headjack** [comment]
theres supposed to be a bug

**Comment by anoobindisguise** [comment]
I have also gotten some sort of error and a bugged facial expression when my morale was in the negative 400s from Every Drug Addiction. Similar I think.
