### ISSUE TITLE
"g" does not unseal (sealed) containers

### ISSUE THREAD

**Issue by rubenpd** [CleverRaven/Cataclysm-DDA#52798]
### Describe the bug

i just happened to loot some MREs and after picking up some items inside i noticed the bags were still sealed

### Steps To Reproduce

1 find (sealed) MRE bag
2 pick up some food item without the container
3 observe the MRE bags

### Expected behavior

i expected MRE bags to not be sealed anymore after picking up items inside

### Screenshots

https://cdn.discordapp.com/attachments/598523535169945607/909042270228054026/unknown.png

### Versions and configuration

Windows 10
version 9afd76b
build 2021-11-13-0710

**Comment by I-am-Erk** [comment]
Does this still happen?

**Comment by andrei8l** [comment]
/confirmed

still happens
