### ISSUE TITLE
`=` menu no longer highlights items sharing a layer resulting in encumbrance penalty

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#52800]
### Describe the bug

`=` menu no longer highlights items sharing a layer resulting in encumbrance penalty

### Steps To Reproduce

Wear multiple things on the same layer on the same body part, see the nonzero + stuff in encumbrance in `@` but no yellow on the items in `=`.

### Expected behavior

Highlight.

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.F-3826-g610e7d5502-dirty [64-bit]
- Graphics Version: Curses
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by l29ah** [comment]
8999c0f6107469f5bdc30500c9d0f03cfa0c69f7 is the first bad commit

**Comment by bombasticSlacks** [comment]
What items? It seems to be working for me
![image](https://user-images.githubusercontent.com/4514073/141661297-afa4234b-b8cf-4b82-b578-8e0cb9354697.png)

**Comment by l29ah** [comment]
![screenshot-items](https://user-images.githubusercontent.com/31852/141661424-508867d2-6b67-4584-a773-b0b5f8943b63.png)

**Comment by bombasticSlacks** [comment]
okay head, hand and feet coverage is broken I'll work on a fix
