### ISSUE TITLE
Best way to split dissections between cbms and specimens

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#52804]
# Is your feature request related to a problem? Please describe.
I need the specimen dissection itemgroups that don't have cbms in them to not spawn burnt out bionics on failure.  

# Describe the solution you'd like
I'd like a simple jsonized method for dissection failures to be changed.  

# Describe alternatives you've considered
I'd settle for a hardcoded hotfix that was expandable with a cargo culters knowledge base.

# Additional context
```
static void butcher_cbm_item( const itype_id &what, const tripoint &pos,
                              const time_point &age, const int roll, const std::vector<flag_id> &flags,
                              const std::vector<fault_id> &faults )
{
    if( roll < 0 ) {
        return;
    }
    map &here = get_map();
    if( item::find_type( what )->bionic ) {
        item cbm( check_butcher_cbm( roll ) ? what : itype_burnt_out_bionic, age );
        for( const flag_id &flg : flags ) {
            cbm.set_flag( flg );
        }
        for( const fault_id &flt : faults ) {
            cbm.faults.emplace( flt );
        }
        add_msg( m_good, _( "You discover a %s!" ), cbm.tname() );
        here.add_item( pos, cbm );
    } else if( check_butcher_cbm( roll ) ) {
        item something( what, age );
        for( const flag_id &flg : flags ) {
            something.set_flag( flg );
        }
        for( const fault_id &flt : faults ) {
            something.faults.emplace( flt );
        }
        add_msg( m_good, _( "You discover a %s!" ), something.tname() );
        here.add_item( pos, something );
    } else {
        add_msg( m_bad, _( "You discover only damaged organs." ) );
    }
}
```

**Comment by dseguin** [comment]
It looks like this issue stems from using `"bionic_group"` as the type for sample drops:

https://github.com/CleverRaven/Cataclysm-DDA/blob/765af02555ee5722e34b2559eaa1b2796759bb6c/data/json/harvest.json#L795-L799

It turns out that there's some special handling for "bionic_group" that skips the special "sample" stuff. Have you tried using just `"bionic"` as the drop type instead?

**Comment by Maleclypse** [comment]
Weird I changed it to `bionic` and tested it about 5 times and only got damaged organs and bovine samples.  I guess I didn't use a large enough test pool?

**Comment by dseguin** [comment]
There's some remaining issues, like flavor text when field dressing corpses. I can add `"mutagen"` and `"mutagen_group"` types for samples in this case, but I guess it makes sense to try and jsonify this altogether.

**Comment by Amoebka** [comment]
It's also worth noting that the "roll" argument the linked function uses comes from elsewhere, and it uses electronics skill in addition to first aid. Success rates for dissecting animals obviously shouldn't be influenced by it.
