### ISSUE TITLE
Impossible to choose not to catch breath during firing a slingshot

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#52801]
### Describe the bug

The choice is ignored.

### Steps To Reproduce

Load the attached game, `f`ire, `a`im, `m`aybe later (or any other option), see that it decided to rest, `The zombie is dangerously close! Stop catching breath? (Case Sensitive)`.

### Expected behavior

Aiming and shooting regardless of the lack of stamina.

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.F-3826-g610e7d5502-dirty [64-bit]
- Graphics Version: Curses
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[2021.11.10.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7532653/2021.11.10.zip)

**Comment by Termineitor244** [comment]
This also happens when firing a bow.
