### ISSUE TITLE
Hallucinatory ZOMBIECOW can move car 

### ISSUE THREAD

**Issue by The-eternal-Fay** [CleverRaven/Cataclysm-DDA#52808]
### Describe the bug

I got seen bye a flaming eye an it made me hallucinate I ignored this an needed fuel so I found a car an started to take apart its fuel tank an which a zombie cow came an moved said car into me an hurt me 👎 hope this helps 

### Steps To Reproduce

Get flamed eyed wait at car til zombie cow comes an it moved it 

### Expected behavior

Will move said car an hurt 

### Screenshots

I have a video but thats it 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 38b2329 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

### Additional context

https://user-images.githubusercontent.com/94274132/141667602-fe2b09b5-ddcb-410e-a4e2-a84af903db04.mp4

**Comment by AskaHope** [comment]
Unique bug

**Comment by wapcaplet** [comment]
There have been many bugs over the years with hallucinations being a little too real. I found some already-fixed issues that may shed light on a solution for this one:

#14763 Hallucinations destroying items
#19970 Vehicle crashing into hallucination

I expect we need to add an `is_hallucination()` check on creatures pushing vehicles, whever in the code that may be occurring.

**Comment by tempestnano** [comment]
It seems that if I hallucinate while crafting for a few hours, eventually one will spawn that will wreck my base. I think on average it takes about four hours, but that may just be that it takes that long to hallucinate something big enough to damage infrastructure.

**Comment by waffel183** [comment]
I just had a similar experience, I had alcohol withdrawal and was hallucinating a lot, zombies in the air, random NPC's spawning and disappearing etc.... I decided to talk to one NPC and it threatened me to drop my weapon, I did and it threatened to kill me  (ofc it was an illusion so I went on with looting). Walked a few turns later back into his sight radius and it started to shoot me??? Again, it was an illusion so I thought I was hallucinating my injuries as well, and I died...

**Comment by pjf** [comment]
Can confirm this still exists as of `cdda-experimental-2021-12-21-2042`, with a hallucinatory necrowolf spider throwing my car into a lake while I was still in it.

**Comment by hexagonrecursion** [comment]
@tempestnano 

> It seems that if I hallucinate while crafting for a few hours, eventually one will spawn that will wreck my base.

This is off-topic in this thread. If you are still able to reproduce the bug, please [open a separate issue](https://github.com/CleverRaven/Cataclysm-DDA/issues/new/choose). This makes it easier for us to keep track of our troubleshooting efforts. Thank you.

> I believe my hallucinations have managed to spawn "alien grass" that persists after the hallucination ended.

I am by no means an expert on how hallucinations work, but a quick [search
](https://github.com/CleverRaven/Cataclysm-DDA/search?q=t_grass_alien&type=) suggests that alien grass is caused by portal storms and *not* by hallucinations. If you have more to say on the topic, please [open a separate issue](https://github.com/CleverRaven/Cataclysm-DDA/issues/new/choose). 


> I just had a similar experience, I had alcohol withdrawal and was hallucinating a lot, zombies in the air, random NPC's spawning and disappearing etc.... I decided to talk to one NPC and it threatened me to drop my weapon, I did and it threatened to kill me (ofc it was an illusion so I went on with looting). Walked a few turns later back into his sight radius and it started to shoot me??? Again, it was an illusion so I thought I was hallucinating my injuries as well, and I died...

This is off-topic in this thread. If you are still able to reproduce the bug that causes hallucinatory NPCs to deal damage to the player please continue the discussion at https://github.com/CleverRaven/Cataclysm-DDA/issues/53510
