### ISSUE TITLE
Trade Menu Double Keybind - Switching Between buying and selling not possible without rebind + unable to specify number of items if npc has dropped items below him

### ISSUE THREAD

**Issue by estebandellasilva** [CleverRaven/Cataclysm-DDA#52816]
### Describe the bug

With the new trade Menu i was unable to switch columns with the tab key - looking at the keybind TAB was assigned to next column (found no use for this) and switch lists.

After rebinding switch lists it was working properly

Second bug

if the npc has items dropped below him you cannot use the number keys to specifiy a number because they are assigned to some items on the floor - you need to filter for the item you want to take a number of then you are able to specify the number

### Steps To Reproduce

Find NPC - i used the guy from the refugee center
Trade
try to switch lists
rebind switch lists key

find npc with items below him
trade
go to item with a amount - type in a number - see it jump to the item on the ground assigned the number
filter the items you want
now you can type in the number (havent checked if this works if the items iss on the floor)

### Expected behavior

Press  tab to switch lists

type number in to pick up a certain amount

### Screenshots

![image](https://user-images.githubusercontent.com/89189872/141684765-1eaf0880-c6ca-446a-aa40-4a195275582a.png)
Those shouldnt be there

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 564d632 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by andrei8l** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/52796 should fix the second bug.

Not sure how to approach the first one. I didn't realize `TAB` already had a role in default keybindings but it's the key for switching panes in both the AIM and the old `trading_window` so I think we should keep it for consistency. Which key did you use, or do you have any suggestion?

**Comment by estebandellasilva** [comment]
i used "s", but i dont think it is the most useful one in this case because it is not something which is used in most menus other menus, which could lead to more confusion
