### ISSUE TITLE
More Autodrive controls and options

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#52814]
# Is your feature request related to a problem? Please describe.
The new autodrive feature can flawlessly navigate through dense obstacles, however it will always prefer to path through roads. Often times, I would prefer to path straight to my target without having roads as the preferred route. In such case I have to path the route in smaller segments to carefully sidestep a city fully of zombies that always attracts the pathfinding algorithm.

Then there's situations where I have cleared a path through a forest tile, but the pathfinder does not recognize it as a valid path even though it's as clear as any road. There's also places where I would like the pathfinder to never path through, such as radioactive craters as it irradiates my character despite there being ample room to go around it.

# Describe the solution you'd like
I would like a new map tile toggle, similar to how we can mark tiles as explored on the map. It would flag tiles on the map for the pathfinder to ignore/take into account when finding a route so we can designate dangerous places as off limits to paths and let the pathfinder know of shortcuts that were manually cleared by the player.

In addition, I would like an option to ignore preferred terrain for the pathfinder, so it always paths the shortest possible route without routing through the nearest roads.

# Describe alternatives you've considered
A waypoint system where player can designate highly preferred map tiles for pathfinding.

# Additional context
Sometimes the pathfinder refuses to start, even when I'm on an empty parking lot. I suspect this is because it's not recognized as empty like a road or field is.

**Comment by Terrorforge** [comment]
I agree that this is a problem, but just for context I want to add that it doesn't _always_ go for the roads. It seems to be based on... fuel efficiency, I guess? Because vehicles with high enough offroad values will in fact just path straight across open fields.

**Comment by Inglonias** [comment]
We can already mark map notes as dangerous via the notes list (Press `L` while on the map screen), though marking other tiles as high priority could be an interesting addition. Not sure if I would ever need that personally though.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
