### ISSUE TITLE
Animation behavior

### ISSUE THREAD

**Issue by vetall812** [CleverRaven/Cataclysm-DDA#52834]
### Describe the bug

Maybe it is not a bug and intended, but should be documented.

Animation sprites displayed in order if their weights are equals or above 8.
If weights are below, some sprites can be skipped till summary weight is above 8.

### Steps To Reproduce

      { "weight": 8, "sprite": "0" }, //- displayed fine
      { "weight": 8, "sprite": "1" }, //- displayed fine
      { "weight": 2, "sprite": "2" }, //- displayed (but may be skipped)
      { "weight": 2, "sprite": "3" }, //- skipped (weights 2+2 less than 8)
      { "weight": 2, "sprite": "4" }, //- skipped (2+2+2 < 8)
      { "weight": 2, "sprite": "5" }, //- skipped (2+2+2+2 = 8)
      { "weight": 4, "sprite": "6" }, //- displayed (but again - may be skipped for no reason)
      { "weight": 4, "sprite": "7" }  //- skipped (4+4 = 8)

### Expected behavior

May be it is ok. But sometimes CDDA skip frames that should be shown.

### Screenshots

This is behavior with 8 sprites all of them have weight = 2
https://user-images.githubusercontent.com/6676374/141761095-4ddfd413-fefa-413c-b8a6-8353327546dd.mp4

### Versions and configuration

OS: Windows 10 x64
Game version: 5eb505a (tiles) 2021-11-14-2100
Ingame language: English
Mods: default

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
