### ISSUE TITLE
Character reports seeing vehicle collisions outside of one's field of view

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#52832]
### Describe the bug

`The Wreckage's frame collides with Wreckage's V6 engine.`

### Steps To Reproduce

Load the attached save file and `.`wait a minute.

### Expected behavior

No strange collisions when i'm chilling in a toilet.

### Screenshots

![screenshot-toilet-collision](https://user-images.githubusercontent.com/31852/141732711-43b367e8-118e-4956-afd4-49f486dca473.png)

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.F-3857-g5eb505ae9a-dirty [64-bit]
- Graphics Version: Curses
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[2021.11.10.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7536337/2021.11.10.zip)

**Comment by wapcaplet** [comment]
This message is printed by the `add_msg` function, which does not check whether the player character can see it happening.

https://github.com/CleverRaven/Cataclysm-DDA/blob/050e934d5bbf3af11f51ff9a81134a257743ae12/src/map.cpp#L707

One solution would be to use `add_msg_if_player_sees` instead.

There are quite a lot of other instances of `add_msg` in this file that probably should be changed as well - the notifications about washing machine, dishwasher, and autoclave cycles in `process_vehicle_items` for example, or "Something has crawled out of the ..." in `rotten_item_spawn`.
