### ISSUE TITLE
Terrain generation removed the return path in this mine. 

### ISSUE THREAD

**Issue by Profit0004** [CleverRaven/Cataclysm-DDA#52830]
### Describe the bug

The terrain was generated in such a way there is no possible way after descending a mining elevator to return as the controls were not spawned. 

### Steps To Reproduce

I assume just go to enough mines and eventually you will find one. 

### Expected behavior

Be able to climb back up?

### Screenshots

![image](https://user-images.githubusercontent.com/15096894/141714072-7d77c2dc-9dac-4c83-8fd4-6e98393f905b.png)

### Versions and configuration

cdda-windows-tiles-x64-msvc-2021-10-13-1557
aftershock and blaze industries mods active.

**Comment by Night-Pryanik** [comment]
Duplicate of #52517.
