### ISSUE TITLE
Mounds of dirt become flat roof terrain when smashed

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#52836]
### Describe the bug

So, I accidentally pressed the wrong buttons, and smashed a mound of dirt instead of what I was intending to smash, and lo and behold, the mound of dirt turned into a flat roof.

### Steps To Reproduce

1. Find a mound of dirt
2. Smash it
3. See a flat roof where the mound of dirt used to be

### Expected behavior

I expect mounds of dirt to not turn into flat roofs when smashed, at the very least (I'm also wondering why they're smashable at all).

### Versions and configuration

OS: Windows
OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version (actually windows 8.1 Pro, but the game report doesn't seem to be able to figure that out)
Game Version: 95019f2 [64-bit]
Graphics Version: Tiles
Game Language: System language []
Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
Bionic Professions [package_bionic_professions],
Aftershock [aftershock],
Blaze Industries [blazeindustries],
C.R.I.T Expansion Mod [crt_expansion],
Magiclysm [magiclysm],
XEAS [XEAS],
Gun Cotton [guncotton],
DinoMod [DinoMod],
Youkai Enemies [Youkai_Disco],
Mining Mod [Mining_Mod],
Mole Mutation [dig_a_tunna],
More Survivor Stuff [more_survivor_stuff],
Mythical Martial Arts [MMA],
More City Locations [cityside],
No Rail Stations [No_Rail_Stations],
Compatible Nimian Manufacture Guns [NM_wpns],
No Fungal Monsters [No_Fungi],
Fuji's Military Profession Pack [fuji_mpp],
Magiclysm No Class Limit [magiclysm_no_class_limit],
Mutation Changes [Mutation_Changes],
Portable Autodoc [portable_autodoc],
SpeedyDex [speedydex],
Stats Through Kills [stats_through_kills],
Stats Through Skills [StatsThroughSkills],
Useful Helicopters [useful_helicopters],
Arcana and Magic Items [Arcana],
return_the_nut [return_the_nut],
Hydroponics [hydroponics],
Cooler Versatility [coolervers],
Chris K's Knives [ChrisKsKnives],
Custom Spells [Custom_Spells],
Reproduction mod [perverts],
Custom Bionics [custom_bionics],
Magiclysm Runes in Arcana Recipes [Custom_ArcanaRune],
Deconstruction Plus [Deconstruction_plus],
Core Data Changes [core_data_changes],
Arcadia Mapgen [custom_arcadia_mapgen]
]

**Comment by ProfoundDarkness** [comment]
I had trouble replicating this on 2969200dd6 (mxe compile win64) with the following mods:
[
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Mythical Martial Arts [MMA],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

I created the mound of dirt with a shovel in one case.
In another case I used map editor to create two different variants of mound of dirt.
In neither case did smashing change the mound.

**Comment by wapcaplet** [comment]
I also could not reproduce this; smashing a mound of dirt with 25 STR and a heavy sledgehammer had no effect.

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-3988-g943e476770 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by AmarinReyny** [comment]
> I also could not reproduce this; smashing a mound of dirt with 25 STR and a heavy sledgehammer had no effect.
> 
> * OS: Linux
>   
>   * OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal;
> * Game Version: 0.F-3988-g943e476770 [64-bit]
> * Graphics Version: Tiles
> * Game Language: System language []
> * Mods loaded: [
>   Dark Days Ahead [dda],
>   Disable NPC Needs [no_npc_food],
>   No Fungal Growth [no_fungal_growth],
>   Bionic Professions [package_bionic_professions]
>   ]

Huh... weird. I wonder why I'm having this bug, then?

**Comment by wapcaplet** [comment]
> Huh... weird. I wonder why I'm having this bug, then?

My guess would be one of the mods you are using. A lot of them are third party and may introduce strange behavior, or may not be compatible with the experimental version you are running.

Do you see the same results in a world with fewer mods or no mods?

**Comment by hexagonrecursion** [comment]
@AmarinReyny, could you please upload you mods folder?

**Comment by AmarinReyny** [comment]
> @AmarinReyny, could you please upload you mods folder?

https://drive.google.com/drive/folders/1F12tOx7w69R6oFdAaM56Ii3HbLaMvU2I?usp=sharing

**Comment by hexagonrecursion** [comment]
Loading errors:
* Custommod Shoulder Guns is corrupted: modinfo.json and recipes.json are empty
* You have two copies of FujiStruct: Fuji_Structures and Fuji_Structures-master
Luckily neither of the two mods is in the above list.

**Comment by AmarinReyny** [comment]
> Loading errors:
> 
> * Custommod Shoulder Guns is corrupted: modinfo.json and recipes.json are empty
> * You have two copies of FujiStruct: Fuji_Structures and Fuji_Structures-master
>   Luckily neither of the two mods is in the above list.

Yeah, the Shoulder Guns mod is a WIP that I started working on a week or two ago, and then stopped due to worsening symptoms IRL. It's not actually corrupted, it just doesn't have anything workable in it yet.

**Comment by hexagonrecursion** [comment]
I have recreated your exact setup (game version and mods) and I still can not reproduce the bug: when I smash a mound of dirt it leaves a dirt floor behind. Please test: can you still reproduce it?

I did get a bunch of errors suggesting you are using old versions of mods or mods that have not been updated to keep up with the version of the game you are playing. Those errors are for *good* reasons. You should expect all kinds of broken stuff to happen because of issues on your end rather then game bugs.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 95019f2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    XEAS [XEAS],
    Gun Cotton [guncotton],
    DinoMod [DinoMod],
    Youkai Enemies [Youkai_Disco],
    Mining Mod [Mining_Mod],
    Mole Mutation [dig_a_tunna],
    More Survivor Stuff [more_survivor_stuff],
    Mythical Martial Arts [MMA],
    More City Locations [cityside],
    No Rail Stations [No_Rail_Stations],
    Compatible Nimian Manufacture Guns [NM_wpns],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    Magiclysm No Class Limit [magiclysm_no_class_limit],
    Mutation Changes [Mutation_Changes],
    Portable Autodoc [portable_autodoc],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Useful Helicopters [useful_helicopters],
    Arcana and Magic Items [Arcana],
    return_the_nut [return_the_nut],
    Hydroponics [hydroponics],
    Cooler Versatility [coolervers],
    Chris K's Knives [ChrisKsKnives],
    Custom Spells [Custom_Spells],
    Reproduction mod [perverts],
    Custom Bionics [custom_bionics],
    Magiclysm Runes in Arcana Recipes [Custom_ArcanaRune],
    Deconstruction Plus [Deconstruction_plus],
    Core Data Changes [core_data_changes],
    Arcadia Mapgen [custom_arcadia_mapgen]
]

**Comment by AmarinReyny** [comment]
> I have recreated your exact setup (game version and mods) and I still can not reproduce the bug: when I smash a mound of dirt it leaves a dirt floor behind. Please test: can you still reproduce it?

Yep.

> I did get a bunch of errors suggesting you are using old versions of mods or mods that have not been updated to keep up with the version of the game you are playing. Those errors are for _good_ reasons. You should expect all kinds of broken stuff to happen because of issues on your end rather then game bugs.


Hm... would that broken stuff include stuff that isn't actually changed by any one mod? I tried searching through the mods folder through Notepad++ for anything that changes mounds of dirt, and I found nothing that would produce this particular problem.

**Comment by hexagonrecursion** [comment]
> > Please test: can you still reproduce it?
> 
> Yep.

This might be specific to a world. Could you please upload your world too? Also: please try reproducing this issue in a freshly generated world.

**Comment by AmarinReyny** [comment]
> > > Please test: can you still reproduce it?
> > 
> > 
> > Yep.
> 
> This might be specific to a world. Could you please upload your world too? Also: please try reproducing this issue in a freshly generated world.

Okay, so testing it in a freshly-generated world with all of the same mods does not produce the same results; smashing mounds of dirt produces just regular dirt.

When you say upload the world, do you mean the whole folder for it?

**Comment by hexagonrecursion** [comment]
I am not sure what else I can do to help.

**Comment by NetSysFire** [comment]
I can verify this does not affect vanilla. I got a heavy sledge hammer and when i smash mounds of dirt i get dirt.

**Comment by AmarinReyny** [comment]
Ah, well... I guess my save is just messed up, then. Wouldn't be the first problem I've had that couldn't be reproduced in new worlds.
