### ISSUE TITLE
Arm encumbrance effects are not shown in character menu

### ISSUE THREAD

**Issue by avianArsonist** [CleverRaven/Cataclysm-DDA#52846]
### Describe the bug

The character menu (in experimental) states that arm encumbrance should affect melee stamina cost and ranged weapon accuracy; 
however, the numbers shown remain at x1.00 melee and +0 ranged dispersion, even with >50 encumbrance.

### Steps To Reproduce

1. Start as a Survivor in the evac shelter.
2. Look at the values affected by arm encumbrance in the @ menu.
3. Put on two emergency jackets.
4. Look at the values again.

### Expected behavior

Melee stamina cost and ranged weapon dispersion should be shown to increase when encumbrance increases.

### Screenshots

![image](https://user-images.githubusercontent.com/91783002/141895109-3259c037-df91-4f7e-bd77-f705772a7848.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 050e934 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key]
]

### Additional context

I haven't tested if the values shown in the character menu are reflective of the actual values in combat.

**Comment by Inglonias** [comment]
Likely related to #52418

**Comment by Terrorforge** [comment]
Maybe, but it's worth noting that the torso and and legs don't list dodge penalty either, and that's definitely in effect.

**Comment by OneThousandResets** [comment]
Please fix encumbrance. Torso is still affected by footwear and unaffected by torso gear.

Also, somebody knows if it is just visual or is it really broken? It does feel broken on my end. Never before I was able to fight melee wearing two emergency jackets. 

Godspeed.

**Comment by avianArsonist** [comment]
I'm pretty sure torso encumbrance is equal to foot encumbrance, both in the character screen and in combat. If it helps, my workaround has been to bring my footwear encumbrance up to whatever my torso encumbrance should be
