### ISSUE TITLE
Russian Layout not work

### ISSUE THREAD

**Issue by ZSHADOWWOLF** [CleverRaven/Cataclysm-DDA#52852]
### Describe the bug

Cyrillic alphabet does not work correctly in Debug mode. When you enter letters or words, the necessary items, mutations, or the map editor does not give an answer, as it was before. Temporarily solved by changing the language from Russian to English and back, but before re-entering the game

### Steps To Reproduce

1. Set Russian Lang
2. Open Debug mod, like items,mutations, or what?
3. Try to find any thing in Russia - Get Empty
4. Set Language to English save, and change again to Russia, save
5. Now lets try again
6. All works, Profit

### Expected behavior

Work as before

### Screenshots

![Current Screenshot 2021 11 16 - 23 34 56 76](https://user-images.githubusercontent.com/12477741/142061613-38e9be39-0912-4cc4-9931-a706ca049188.png)
![Current Screenshot 2021 11 16 - 23 35 11 21](https://user-images.githubusercontent.com/12477741/142061617-4f67cdbd-650f-4337-a566-81a655a395b2.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 9b60b4c [64-bit]
- Graphics Version: Tiles
- Game Language: Системный язык []
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Бионические профессии [package_bionic_professions]
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7549682/debug.log)

**Comment by BrettDong** [comment]
I have no problem searching item names. The game language is set to Russian prior to launching the game and I don't need to switch language between English and Russian to get the working filtering menu.
![image](https://user-images.githubusercontent.com/21075502/166144339-944fdd7b-50ac-43cc-8c93-cc5c27180416.png)

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-12091.
