### ISSUE TITLE
[Magiclysm] - Mojocycle Summon On Vehicles

### ISSUE THREAD

**Issue by Doge-of-Venice** [CleverRaven/Cataclysm-DDA#52864]
### Describe the bug

When you summon a Mojocycle on top of a vehicle it seems to trigger the vehicle crash code and creates a wreck where the vehicle was before now including the Mojocycle as well. The wreck is unable to be accessed after it is created and will disapear once the duration of the Mojocycle has elapsed. It looks like a previous issue [48344](https://github.com/CleverRaven/Cataclysm-DDA/issues/48344) may have connected reasons for these effects.

### Steps To Reproduce

1) Cast Summon Mojocycle so that the Mojocycle will overlap onto a vehicle. (I have tried it on an Armored Personnel Carrier and a Minivan with the same results).
2) Wreck will be created joining both the mojocycle and the vehicle.

### Expected behavior

What was discussed is the expected result would be that the spell fails instead of creating the wreck.

### Screenshots

https://imgur.com/Hb0tLK0

### Versions and configuration

OS: Windows
Game Version: de98d1d2754abadd636efa164e2aaa7be486128b
Graphical: Ultica
Language: English
Mods: Blaze Industries, Graphical Overmap, Magiclysm, Graphical Overmap Magiclym, Stat Through Skills, Dark Days Ahead, Disable NPC Needs, No Fungal Growth

**Comment by Night-Pryanik** [comment]
As of 0.F-8778 you can't cast spawn mojocycle on tile with a vehicle.
