### ISSUE TITLE
shotgun beanbag unfireable, range is 0

### ISSUE THREAD

**Issue by catdach** [CleverRaven/Cataclysm-DDA#52881]
### Describe the bug

Shotgun beanbags cannot be fired or aimed, likely because the range for the ammo is set to zero. Could have something to do with #52583 

### Steps To Reproduce

1. load a shotgun with "shotgun beanbag" ammo
2. try to aim shotgun at anything

### Expected behavior

Aim reticle moves to target.

### Screenshots

![image](https://user-images.githubusercontent.com/93795131/142452547-a16cffe3-718e-4e07-9865-b188f5578ecc.png)

![image](https://user-images.githubusercontent.com/93795131/142452926-d8966e01-d02f-4fbc-897c-511166cc4c0e.png)

![image](https://user-images.githubusercontent.com/93795131/142453383-a8e16afe-fe15-431d-b1b0-ec9c623f49a0.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 5ec5e24 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Magiclysm [magiclysm],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    C.R.I.T Expansion Mod [crt_expansion]
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7564293/debug.log)

**Comment by CosmicHitman** [comment]
Do you have a suggested range value? I saw a possible source saying about 20m for a beanbag round is the maximum, but I do not know how meters convert to tiles in game. I would also note, I know nothing about guns so please correct me if that seems wrong.

**Comment by catdach** [comment]
If we assume that slugs (range 24 in game) have a range of 100m, that would put beanbags at an in game range of 5 which seems about right.

**Comment by CosmicHitman** [comment]
Good idea. I'll do just that.
