### ISSUE TITLE
The current "land mine" recipe does not make sense. Change it and add recipes for improvised land mines or explosive booby traps.

### ISSUE THREAD

**Issue by Scorch-Mechanic** [CleverRaven/Cataclysm-DDA#52907]
# Is your feature request related to a problem? Please describe.
I'm looking at the recipe in-game right now and I can make a "military anti-personnel mine" with just duct tape, scrap metal, nails, and gasoline. Which shouldn't be possible. There's a bunch of components in here that simply can't be used to make a functional landmine like gasoline, diesel, and biodiesel. Furthermore, the recipe lacks the option to use a bunch of explosives that exist in the game and could reasonably be used, like ANFO, composition B, dynamite, or even match head powder. 

# Describe the solution you'd like
Change the military land mine recipe to _require_ high explosives, a military fuze of some kind, and some kind of shrapnel like lead pellets, BBs, nails, or ball bearings. 

Second, add one or more recipes for an "improvised land mine", which allows low explosives (and high explosives) as the primary explosive, shotgun shells as the initiator, and whatever else seems appropriate as container and shrapnel. 

Third, remove the hand grenade as an option for crafting the land mine. We already have the booby trap, which is made with a hand grenade.

# Describe alternatives you've considered
Leaving it as it is, nonsensical and fantastic.

# Additional context
I don't think that gasoline, diesel, or biodiesel can't be used for booby traps of some kind. An improvised trap that erupts in a fireball of gasoline sounds intriguing, fun, and useful.

**Comment by Photoloss** [comment]
> I don't think that gasoline, diesel, or biodiesel can't be used for booby traps of some kind. An improvised trap that erupts in a fireball of gasoline sounds intriguing, fun, and useful.

This would need some more careful design though. Gasoline evaporates quickly but it needs to be exposed to the air once the trap actually triggers. Diesel fuels aren't really volatile enough to be useful in a reactive trap.

Variants which seem plausible include a "molotov on a string" with some very simple primer spark, a diesel-filled trench to manually light into a wall of smoke and fire, a "boiling oil" pouring/drop trap to directly douse a target in diesel (or better yet, napalm), and of course anything with an explosive primer to spread the fuel. It would also be nice to have a deliberate "pouring tank" vehicle component with an integrated toggleable pilot light instead of having to bash a tank and throw the match yourself.

**Comment by Scorch-Mechanic** [comment]
> This would need some more careful design though. Gasoline evaporates quickly but it needs to be exposed to the air once the trap actually triggers. 
Not especially. Those big greasy orange fireballs you see on TV and in movies are usually gasoline fireballs. You can do those just by filling a couple gallon jugs with gasoline and sticking a gunpowder charge between them, as shown on Mythbusters. It's also worth noting that you don't need to take any special steps to make the fuel-air mixture just right, you just have to provide a useful source of fire. Once an adequately mixed ratio of fuel vapor and oxygen is achieved (for example, by flinging a bunch of it around with a smaller explosion) it will blow up on its own so long as it has an ignition source. This is why farmers have to be careful around silos, because disturbing fine flammable dust will cause it to billow up into clouds and potentially achieve the correct ratio of fuel and air to explode.

**Comment by Photoloss** [comment]
> You can do those just by filling a couple gallon jugs with gasoline and sticking a gunpowder charge between them

Yes that is what I meant, the trap needs an explosive primer for that approach to work. If you have access to that chances are you can build a better trap. Or at least fill it with napalm instead of just gasoline.

**Comment by kevingranade** [comment]
Or in the interim  just obsolete the recipe, it's not exactly something that it's a good idea to fiddle with.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
