### ISSUE TITLE
Estimate clothing warmth from existing item stats

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#52905]
# Is your feature request related to a problem? Please describe.
Warmth granted by various clothing pieces is seemingly arbitrarily decided by authors of said pieces, it is not tied to material type, thickness or coverage. Examples are not needed, as all are currently a matter of opinion and not material properties.

# Describe the solution you'd like
Warmth granted by a clothing piece should depend on already existing item properties, instead of being a manually assigned number.

# Describe alternatives you've considered
Defining more properties of materials themselves and working from there.

# Additional context
Cold is never an issue from my player experience, as it is trivial to stay hot - just pile on more clothing layers. Cooling down is extremely limited as the only choices are to strip naked, install a CBM or use a vehicle cooler. There's missing options of using water to cool down, there's already a possibility to cool/freeze food items, it would help alleviate the clothing problem if frozen items or (cold) liquids could be used to cool a character down by pouring it over oneself.

**Comment by Photoloss** [comment]
A manual override for warmth is necessary, the current materials system can't easily handle gaps in the material. Chainmail effectively provides 100% coverage but its heat retention is negligible compared to equal thickness (or even mass) of the same iron/steel arranged into a continuous effectively airtight plate.

The "(a)ctivate water" is something I have been pondering too for a while but haven't gotten round to writing out a feature request. Would douse fires and clean off acid too.
