### ISSUE TITLE
Trap quality

### ISSUE THREAD

**Issue by LyleSY** [CleverRaven/Cataclysm-DDA#52906]
# Is your feature request related to a problem? Please describe.
Traps are kind of handy early game but don't scale

# Describe the solution you'd like
Traps that scale with skill in damage and durability

# Describe alternatives you've considered
Various recipes for each trap type like "low quality", "medium quality" and "high quality" gated behind different skill levels

# Additional context
Inspired by Castlevania Season 3, which has a trap that is remarkably deadly and durable

**Comment by catdach** [comment]
It's hard to tell what exactly you're asking for. Do want more trap _items_? Do you want more ways to make more complex traps with _terrain_? or something else?

Like, the trap items in the game do scale quite a bit, from nail-board traps and tripwire traps and crossbow traps, to shotgun traps and bear traps, to grenade traps and blade traps, to home-made land mines (and military land mines), to teleporter traps (which could arguably be more useful for something so high tech). It's hard to think of more late game traps. Maybe it would be nice to be able to craft those laser traps that you can find in labs? Also you can craft automated gun turrets, which are basically high-end gun traps if you think about it.

I personally haven't seen Castlevania (yet), but it sounds like you want a cool new trap item/construction; In which case great! That is very do-able.

I don't think this is what you're asking for, but something more _terrain_ based would probably be like pit traps where this is no explicit item associated with it but is more a product of creatively interacting with the environment. It could be possible to make something like the Redstone system from Minecraft where you can wire up pressure plates to activate doors and electronics and such, but that would be a **_HUGE_** project that also doesn't really fit well with the ways traps and electronics work right now.

giving traps different levels of quality seems kinda... well to me it seems kinda boring, and its not very clear what the different quality levels would do. If it's just more `damage` then we already sorta have that, just upgrade your crossbow traps to shotgun traps or whatever. `durability` seems like a big can of worms that I personally do **NOT** want to deal with. On top of that, there are already the trap setting proficiencies that presumably already fills this role of becoming better with traps over time.

So yeah, It just not clear what you're asking for that isn't in the game already, more clarification would be a big help.

**Comment by LyleSY** [comment]
Specifically I had pit traps in mind since the current ones do very little damage and break quickly, making them useful in early game but pretty quickly become more trouble than they're worth. Agreed that trap items can be useful into mid game. My thought was to be able to build pit trap (low quality) or pit trap (high quality) etc and then they do less damage and break more easily as they break down. Sure, I'm good with the proficiencies playing a role in this. I'm mainly interested in a way for pit traps to be worth using in mid game and maybe even late game.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
