### ISSUE TITLE
(e)xamine no longer allows to examine items on the ground around player

### ISSUE THREAD

**Issue by Jan-Blasiak** [CleverRaven/Cataclysm-DDA#52901]
### Describe the bug

(e)xamine no longer allows to examine items on the ground

### Steps To Reproduce

Update the game, try to pick up something on the ground

### Expected behavior

(e)xamine working normally

### Versions and configuration

47cbf68 (tiles)

### Additional context

Which glue eater decided to ~~break~~upgrade this feature?

**Comment by Zireael07** [comment]
Being fixed in https://github.com/CleverRaven/Cataclysm-DDA/pull/52873

**Comment by Maleclypse** [comment]
Hi, while you may have meant it jokingly please refrain from insulting people and name calling in this repo.
