### ISSUE TITLE
Subway train console mission doesn't point toward target

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#52914]
### Describe the bug

Both myself and LeahLuong have encountered the problem of receiving the refugee center mission to download data from a subway terminal but being directed to a lab without any subway connection. My case is from 0.F-0, while LeahLuong's is from 0.F-2.
There's a closed bug report, #45973, that's supposed to fix the problem.

### Steps To Reproduce

Start the game and progress to get this mission until it fails...

### Expected behavior

The mission should point to a location actually validly related to the final target

### Versions and configuration

Game version: 0.F-0 and 0.F-2.
OS: Windows 10.1 and Android

### Additional context

Cannot upload the save due to its size (52 MB).

It can be noted that lab target locations typically are incorrect (at least in 0.F-0), although appropriate terminals have been found within the same lab prior to this mission.

Trying to make sense of the code referenced by #45973, I've noted several suspicious things:
- The code searches for "lab_train_depot". However, the game displays "S subway station?" indications both at level -2 and level -4 for hidden labs, and the search function seems to do a 3D search. This means it ought to be able to pick up a subway station at level -2 rather than the intended -4, although it may be that the level -2 ones never have any terminals.
- The code searches for a "real" lab entrance in the vicinity of the "lab_train_depot" it has found, but if that depot is for a hidden lab the entrance it will find will be for a different lab (which might have no connection to any subterranean network at all).
- There's another issue with the logic that finds the closest between a "lab_stairs" and a "hidden_lab_stairs" location in that there may be edge cases where the entrance to an adjacent lab might be closer to a depot than the entrance to the actual target lab.
- The code appears to set the mission target at the surface level, yet all the 0.F-0 targets have been underground, and I think they've been at z-2. This could be because the code I'm looking at (day old experimental) may be different from that of the stable version(s).
- I don't know what kind of entrance is used to connect a research facility to a lab, but that might be another possible case where the entrance search could get the wrong lab.
- There's no handling of the case where no console or lab is found, in which case an uninitialized location is used (and I did get something looking like a similar case for an earlier lab mission where the distance to the target seemed to be based on -2**31. That case was save scummed away).

Edit: Corrected the initial version references above.

**Comment by LeahLuong** [comment]
Correction: I'm playing on 0.F-2, the latest stable, & encountered this issue.

Also, practically any .sav that has progressed to this point in the game will have exceeded the file size which is uploadable to this site. Lyman Easley's missions seem to involve the most travel & this quickly grows past the storage limit here. I can see this being a problem for any issues which tend to crop up in lategame scenarios. Perhaps not the most pressing thing but I thought I should bring it up.

**Comment by MNG-cataclysm** [comment]
PR #61000 overhauled and fixed the mission. 
@kevingranade I would recommend closing this issue.
