### ISSUE TITLE
Unable to harvest certain plants such as chamomiles or sunflowers.

### ISSUE THREAD

**Issue by nullinsky** [CleverRaven/Cataclysm-DDA#52916]
### Describe the bug

After a recent update, unable to harvest some types of plants such as chamomiles or sunflowers.

### Steps To Reproduce

1. Update to latest at 55f4f59.
2. Try to examine a nearby plant.

### Expected behavior

Should let us pick and harvest the plants like normal.

### Screenshots

![cannotharvest](https://user-images.githubusercontent.com/45400571/142726175-1fb86070-30b3-4dde-96e6-9987237d57c7.png)

### Versions and configuration

OS: Windows 10
Game Version: 2021-11-20-1035
Graphics Version: Tiles
Mods:

[
"dda",
"no_npc_food",
"no_fungal_growth",
"package_bionic_professions",
"aftershock",
"blazeindustries",
"DinoMod",
"extra_mut_scens",
"Mining_Mod",
"Rummaging",
"cbm_slots",
"fuji_mpp"
]

**Comment by dseguin** [comment]
It turns out that you can't examine the plant because it's out-of-season. If you examine a sunflower in the summer, you get the option to harvest it:
![harvest_plant](https://user-images.githubusercontent.com/12537966/142736989-ff0f7dc3-dd75-4c9c-a47a-ec9f2df60f65.png)

**Comment by nullinsky** [comment]
Oh, good find there. So it looks to be an auto-examine/sprite issue since there's no notification that the plant is immature.

I tried harvesting the plants in my game around late spring.

**Comment by wapcaplet** [comment]
If you disable the game Option on the Interface tab, "Autoselect if exactly one valid target", you will be able to actually use `e`xamine on a sunflower to see that it cannot be harvested in the current season:

![image](https://user-images.githubusercontent.com/238395/142745077-0903af16-39b3-4034-87a9-15d84345ddb9.png)

And if you examine using `x` ("look around"), cursor over the sunflower, then press `e` ("extended description"), it tells you what season:

![image](https://user-images.githubusercontent.com/238395/142745114-5e8abb2b-529a-49ff-ad06-25529ed92aec.png)

**Comment by nullinsky** [comment]
Thanks for the info, I didn't know it was due to the new autoselect setting. Pretty used to having my 'e' show an input. Please close the issue at your convenience.
