### ISSUE TITLE
101 Important Integrated Circuits book incorrectly marked

### ISSUE THREAD

**Issue by Tommy-os** [CleverRaven/Cataclysm-DDA#52919]
### Describe the bug

The book "101 Important Integrated Circuits" is incorrectly marked (text colored) as a regular "for fun" book when not read, despite providing a practice recipe for the player. I assume this is due to it containing only a practice recipe and not a real crafting recipe.

### Steps To Reproduce

1. find a bookstore with 101 Important Integrated Circuits
2. compare color of unread books to other skillbooks and "for fun" books

### Expected behavior

101 Important Integrated Circuits should have name colored as other skill books.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 738d25d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

There's hundreds of various skill books that a player can collect, these name color markings are important to differentiate between fluff and useful books. Similar to how player already has access to info/lore dumps for every monster and item he sees.

**Comment by Inglonias** [comment]
I can confirm this, though the name of the book hinted at the possibility that it was some kind of skill book. I agree that this needs to be changed.

**Comment by catdach** [comment]
I think the flagging system to differentiate books was implemented before practice recipes and the new experience system was introduced so that's probably why this is the case. I'll try to look into it more

**Comment by wapcaplet** [comment]
As the one who created this book, I agree that its importance should be indicated better. It is intended primarily as a reference manual, but it would be reasonable for the book to give some higher-level electronics skill. A quick survey of existing electronics books and their skill levels:

- Ham Radio Illustrated: 0 - 1
- What's a Transistor?: 0 - 3
- Advanced Electronics: 2 - 5
- Electronic Circuit Theory: 3 - 6

The "101 Important ICs" should fit around level 5 - 7, I would suggest.

**Comment by l29ah** [comment]
I would suggest 5-6 or something like 5-5 just to plug the bug like some mutagen lab stuff does.

**Comment by PatrikLundell** [comment]
Yes, the work around for "recipe only" books has been to set the required skill equal to the level it trans the skill to, so that's probably the short term solution for the incorrectly flagged books (this work around leads to the obvious question from people encountering it for the first time, like I did, why these books were bugged).

The longer term solution would be to check whether the book provides a recipe or trains a skill, rather than just check for skill training (I don't know if there's a need to also do something for proficiency training, or if that's included in the skill part check already).
