### ISSUE TITLE
Stun Guns use ludicrously too much energy

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#52911]
# Is your feature request related to a problem? Please describe.

The power consumption of stun guns is too high. Kevin wanted me to show my work on this so here we are.

"The fatal current" https://academic.oup.com/ptj/article-abstract/46/9/968/4637975?redirectedFrom=PDF describes 10 mA (0.01 amp) as causing "painful to severe shock". Currents above 200mA (0.2 amp) are described as being lethal unless immediate medical attention is given, and even then still possibly life threatening. While less likely to kill instantly than 100-200mA due to the sheer voltage clamping the heart, it will leave severe burns as well. The heart is far more vulnerable and a shock delivered to the heart would be severely more lethal, and require far less energy to kill. 
https://www.scienceabc.com/humans/how-many-volts-amps-kill-you-human.html
This is the most charitable source I could find regarding our ability to not die to charge.

Stun gun companies dramatically overstate their voltages. The max practical voltage for a stungun looks to be about 30-50kV.  Stun guns deliberately have high voltage to decrease amperage (what actually does the shocking) and increase penetration against resistors such as clothing and skin.
https://www.sabrered.com/stun-gun-voltage-maximum
https://www.srselfdefense.com/blog/stun-gun-myths/
https://www.tbotech.com/highest-amperage-stun-gun.htm

A typical stun gun delivers 2-5 mA. This is enough to cause significant pain and muscle spasms, which is what is desired out of a compliance weapon.
https://taserguide.com/how-many-amps-in-a-stun-gun/ (describes 0.1 amp as being lethal)
https://hypertextbook.com/facts/2004/LukeWorkoff.shtml
https://www.thehomesecuritysuperstore.com/collections/high-voltage-stun-guns (lies about its voltage, but gives information about the lethality of amperage and the average amperage of a stun gun.)

So what does this give us? Stun guns use DC. A cataclysm stun gun takes 100kJ to fire. Since V*A=W and we can assume the stun gun is not firing for more than one second, we can approximate it as 100,000W = 30,000V * A, where A is greater than _3 amps_. Given that 0.2 amps is more than enough to kill a human the discharge from such a weapon is not only 15-30x that, but it is literally 1000x as powerful as a typical 3mA stun gun. 

Given its paralysis and super-effectiveness against robots the cata version may be souped up a bit more but it it CLEARLY is not that powerful given what it actually does to the player character. If it were actually that strong it would likely kill you instantly and every tazer hack and skitterbot would individually be as dangerous as a .50 CROWS turret. There are possible explanations for some increased power usage that isn't represented in its actual effect on enemies - the stun gun is described as its current "jumping through the air". This doesn't actually appear to be physically possible, and maybe needs to be changed, but it's also possible it's some sort of techno-magic that the cataverse invented to play with their super powerful batteries.

# Describe the solution you'd like

What's the solution? Obviously lower the power consumption considerably. A 0.03 amp stun gun operating at 30k volts would use only 100j of power. However - batteries can't use anything other than whole kJ, and a 1kJ stun gun would still be pretty powerful because it doesn't miss. I don't know what to do here for the sake of realism/balance. Zombies don't feel pain and they don't breathe (somehow) but an electric shock would still cause damage to them as well as spasms and muscular paralysis. I assume that since they bleed they need a heart to stay "alive". 

https://massgunownership.com/stun-gun-basics.html describes a stun gun as being able to be used "100s of times on a single charge". Supposedly a majority of stun guns IRL use 9v batteries. 
https://sciencing.com/energizer-watthour-battery-specs-7425932.html estimates a 9v battery has about 20kJ stored in it, so an IRL stun gun might be taking about 100j to fire if it has 200 "uses". This lines up with the previous figure. 
Given that cataclysm batteries are much stronger, you would expect far more uses out of a battery. I don't know how to compare a 9v and a "medium" battery but the medium, rechargeable battery would be giving you about 25x the charge of a 9v. I don't think it's very helpful to know that, but the math behind the uses a stun gun provides does at least line up with and confirm what I had to say previously.

Personally I do think that it would make sense that Cata stunguns are more powerful than usual, because they would be amped up (heh) to deal with "rioters". So approximating the current stungun as a 100 mA (0.1 amps) stunner - would give us a very clean 3kJ cost for each "zap" of the stun gun while not needing to change its effects against enemies. This fits on the axis of "just barely technically nonlethal, maybe" just like the riot control turrets. This might still be too much for its total damage output but our characters can also take multiple 9mm rounds and keep going so it does fit.

This would make stun guns a pretty powerful early game weapon that remained powerful later on but then again, stun guns are pretty strong and you can pretty easily kill someone by discharging your gun Palpatine-style since they'd likely be paralyzed from the discharge.

# Describe alternatives you've considered
100 mA is still really really high and probably impossible for the circuitry of a stun gun to handle. But it's not practical to go lower than that due to the way batteries work in cata. 
Alternatively we could massively overhaul how batteries work but I really don't want to do that...

# Additional context

**Comment by kevingranade** [comment]
You have zero information about the power draw of a stun gun here, yes that seems to be hard to track down, but that does not mean you should pile on a bunch of speculation instead.
