### ISSUE TITLE
Impossible to unfreeze antiseptic and cough syrup with a hotplate

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#52938]
### Describe the bug

How am i supposed to survive in winter!?

### Steps To Reproduce

Grab some frozen cough syrup or antiseptic, `a` hotplate, note that there's no option to choose them.

### Expected behavior

Being able to handle them like beverages.

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.F-3954-g228248d3e1-dirty [64-bit]
- Graphics Version: Curses
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

[2021.11.18.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7575780/2021.11.18.zip)

**Comment by PatrikLundell** [comment]
To survive winter until bug fix time you'd have to store them at frost free depth (i.e. in a basement or similar location, possibly one you've dug yourself). I don't know if a thermos can be used to bring these things with you out into the field (once thawed), but it might be worth a try.
