### ISSUE TITLE
NPCs spawned with knee pads keep them inside backpack

### ISSUE THREAD

**Issue by Tommy-os** [CleverRaven/Cataclysm-DDA#52932]
### Describe the bug

So far every randomly spawned NPC that I've seen had knee pads stored inside one of their storage items, instead of wearing them. Telling the to use the item makes them wear their knee pads without any issue.

### Steps To Reproduce

1. find NPC with knee pads and some storage
2. check their inventory

### Expected behavior

NPCs should wear their knee pads instead of storing them.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 738d25d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Photoloss** [comment]
Are they wearing any long coats or other leg-covering armour in the "Outer" layer? If so it could be caused by #52546 invalidating previous assumptions on layering.

**Comment by Tommy-os** [comment]
It's not related to that PR, as my current version is 2 weeks old. I will reopen this if I encounter it in the new version.
