### ISSUE TITLE
Mutated Anatomy Prevents Wearing Flesh Pouch

### ISSUE THREAD

**Issue by OmniscientQ** [CleverRaven/Cataclysm-DDA#52949]
### Describe the bug

The Flesh Pouch summoned by the spell of the same name cannot be worn with mutated anatomy. Since it can't be worn, it defaults to being wielded, and you're not allowed to drop it.

### Steps To Reproduce

1. Mutate yourself with some torso-restricting mutation (My character had the Shell mutation).
2. Cast Flesh Pouch
3. Profit

### Expected behavior

I would expect flesh pouch to work even for huge or small mutants (perhaps with scaling volume based on size). Even if that doesn't work, I'd at least hope the spell would politely inform me that it has failed and not leave me stuck in a laboratory unable to use my hands for 17 minutes.

### Screenshots

![FleshBug](https://user-images.githubusercontent.com/7938543/142780555-19ab09f2-f4fe-4992-b40d-62bf2e247b01.png)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.2 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-3914-gdca8d570af [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Stats Through Skills [StatsThroughSkills],
    Disable NPC Needs [no_npc_food],
    Bionic Slots [cbm_slots]
]

**Comment by LeahLuong** [comment]
I hate it when I'm unable to use my hands for 17 mins because of my Flesh Pouch.

**Comment by Jan-Blasiak** [comment]
test

**Comment by Venera3** [comment]
The easy solution to it is to add `"OVERSIZE"` to the flesh pouch - Good First Issue IMHO.
