### ISSUE TITLE
Pickup menu items are not displayed within their container

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#52947]
### Describe the bug

When picking up items using `g`, items are often not displayed within or anywhere near their container.

### Steps To Reproduce

1. Find a pile of items
2. Use `g` to select items you want to pick up

### Expected behavior

Items in containers should be displayed just under the line for their container.

### Screenshots

Spear strap with halberd - halberd is shown above the spear strap that contains it:

![image](https://user-images.githubusercontent.com/238395/142776299-575caa5e-d127-4e98-a3ea-8ea2764e8dfb.png)

Two-way radio with light battery - battery is 4 lines above, under "glass jar":

![image](https://user-images.githubusercontent.com/238395/142776273-a6c86621-cb5c-4c5d-b18c-57700e115808.png)

Chemistry set with medium battery - battery is 4 lines below, under "glass jar":

![image](https://user-images.githubusercontent.com/238395/142776284-b79dee4c-99f2-4a1b-ad17-42e31f52ffd1.png)

Tailor's kit actually appears correctly, with thread listed under it:

![image](https://user-images.githubusercontent.com/238395/142776314-19c4fd41-7fe5-42c9-b3a4-edfa11d1ebac.png)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-3928-g47cbf6852d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Generic Guns [generic_guns],
    Mythical Martial Arts [MMA],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi]
]

**Comment by mqrause** [comment]
This is likely the case for all `inventory_selector` menus, considering the pickup menu is mostly just a copy of the multidrop menu.

**Comment by Photoloss** [comment]
> This is likely the case for all `inventory_selector` menus, considering the pickup menu is mostly just a copy of the multidrop menu.

Also happens with "insert" on individual containers at the very least.

**Comment by dseguin** [comment]
I noticed that the alphabetic compare includes all the item modifiers in the name (ex: `"<color_c_light_green>|| </color>XL holster"`) when sorting.

See: `inventory_column::prepare_paging`

**Comment by andrei8l** [comment]
The issue with alphabetic sorting is easily solved:
<details>
<summary>patch</summary>

```diff
diff --git a/src/inventory_ui.cpp b/src/inventory_ui.cpp
index b75ee98737..885dff3f50 100644
--- a/src/inventory_ui.cpp
+++ b/src/inventory_ui.cpp
@@ -28,6 +28,7 @@
 #include "point.h"
 #include "ret_val.h"
 #include "sdltiles.h"
+#include "localized_comparator.h"
 #include "string_formatter.h"
 #include "string_input_popup.h"
 #include "trade_ui.h"
@@ -228,7 +229,7 @@ nc_color inventory_entry::get_invlet_color() const
 
 void inventory_entry::update_cache()
 {
-    cached_name = any_item()->tname( 1 );
+    cached_name = any_item()->tname( 1, false );
 }
 
 const item_category *inventory_entry::get_category_ptr() const
@@ -280,7 +281,11 @@ inventory_selector_preset::inventory_selector_preset()
 bool inventory_selector_preset::sort_compare( const inventory_entry &lhs,
         const inventory_entry &rhs ) const
 {
-    return lhs.cached_name.compare( rhs.cached_name ) < 0; // Simple alphabetic order
+    if( lhs.cached_name == rhs.cached_name ) {
+        return localized_compare( lhs.any_item()->tname(), rhs.any_item()->tname() );
+    }
+
+    return localized_compare( lhs.cached_name, rhs.cached_name );
 }
 
 bool inventory_selector_preset::cat_sort_compare( const inventory_entry &lhs,
```
(same sorting logic as in the AIM)
</details>
But I don't think you can sort contained items below their parents in one step since that parent is a moving target too.

**Comment by wapcaplet** [comment]
The inventory keybinding "Toggle inventory view to show item categories" aka `VIEW_CATEGORY_MODE` (bound to semicolon `;` by default in the `i`nventory and `d`rop screens) invokes `inventory_selector::toggle_categorize_contained()`, displaying items as an indented list within their containers.

This works because both the `i`nventory and `d`rop screens sort items into **categories** by default, and does not do nested indentation. The new `g` pickup screen sorts items into **location** groups by default, and all items are indented based on their container depth, although they are not shown in their containers, but instead alphabetized by their name. Unlike its siblings, pressing `;` on the `g` pickup screen does not do anything.

If the `g` pickup screen could support this `;` toggle like the other inventory screens do, and switch between "items grouped by location" and "items nested in their containers", that would also fix this issue. But the current `g` pickup menu is a poor hybrid between both, and is not very usable.

**Comment by andrei8l** [comment]
> The inventory keybinding "Toggle inventory view to show item categories" aka `VIEW_CATEGORY_MODE` (...

`toggle_categorize_contained()` calls this horrendous function `order_by_parent()` to get that sort order. You could use that for the pick selector too, but it doesn't seem to work when there are more than 1 top-level containers (much like my naive commit above)
<details>
<summary>before order_by_parent()</summary>

![before 1item](https://user-images.githubusercontent.com/68240139/142872330-04812965-f1c3-4264-9398-429f7e27f9ac.png)
</details>
<details>
<summary>after oder_by_parent()</summary>

![after 1item](https://user-images.githubusercontent.com/68240139/142872375-c4790658-d2bd-4e37-84bd-089c7aeb130c.png)
</details>
<details>
<summary>after oder_by_parent() w/ 2 top containers</summary>

![after 2items](https://user-images.githubusercontent.com/68240139/142872424-36547158-f16c-4e46-a572-37a3f15c6572.png)
</details>

**Comment by mqrause** [comment]
> This works because both the `i`nventory and `d`rop screens sort items into **categories** by default, and don't do nested indentation for containers. The new `g` pickup screen sorts items into **location** groups by default, and all items are indented based on their container depth, although they are not shown in their containers, but instead alphabetized by their name. Unlike its siblings, pressing `;` on the `g` pickup screen does not do anything.

Oh wow, didn't expect that different behavior simply from adding items from different sources. Then I guess other affected menus would be `a`ctivate, `E`at or `R`ead, except they don't care about containers anyway.
