### ISSUE TITLE
Targeted mutations can grant out-of-category prerequisites

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#52942]
### Describe the bug

When using targeted mutagens and serums, it is possible to gain mutations that aren't part of the relevant category if they're part of the prerequisite chain for a mutation that is.

For example, the Medical category includes the Resilient mutation. It has another medical mutation, Pain Junkie, as a prerequisite, and the intention is obviously that the mutation should progress from the various pain resistance mutations -> Pain Junkie -> Resilient. However, Resilient also has Large, Huge, Extremely Strong and Insanely Strong as possible prerequisites, all of which in turn require Strong/Very Strong. This causes Medical Serum to frequently grant Strong, a mutation that is not in the Medical category.

This is partly intended behavior, as it's convenient that you can simply include e.g. Large without having to manually include every step in the prerequisite chain, but it causes odd behavior with mutations like Resilient that have multiple paths.

### Steps To Reproduce

1. Spawn in a syringe and a bunch of medical serum
2. Take serum repeatedly
3. Pay attention to the mutations you get and note that you get Strong

This won't happen every time, but it happens a lot of the time, so you shouldn't have to repeat the test very many times.

### Expected behavior

Targeted mutagens should grant in-category prerequisites only.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 2969200 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

There's a related bug where Resilient has Pain Junkie as a prerequisite, but not its upgraded version Cenobite, which causes you to sometimes mutate past Pain Junkie, ensuring that the serum trying to mutate Resilient will grant you Strong etc.

But to be clear, this is not a problem with the Medical category specifically, it's a problem with the fundamental mutation mechanics.

**Comment by Terrorforge** [comment]
Another, more harmful example is that ursine mutagen can give you Carnivore, even though the category is specifically set up to let you have the "Apex Predator" without being a true carnivore, because you are a a bear.

**Comment by I-am-Erk** [comment]
Does this happen with the new mutation system?

**Comment by Naadn** [comment]
Yes, This does happened, Whem I useing raptor mutagen, it gave me Phelloderm, Epicuticle, Lightly Furred and Jumbled Skin. So I have to savescum for the correct mutation to appear.
