### ISSUE TITLE
Little gaps between tiles with OpenGL linear filtering

### ISSUE THREAD

**Issue by rumly111** [CleverRaven/Cataclysm-DDA#52962]
### Describe the bug

When I choose opengl or opengles backend, and select linear filtering, I can see strange gaps between tiles. With "nearest" or no filtering there is no issue.

### Steps To Reproduce

1. Options
2. Graphical backend -> OpenGL / OpenGL ES
3. Filtering -> Linear Filtering

### Expected behavior

no gaps between tiles

### Screenshots

![2021-11-22_20-51-51](https://user-images.githubusercontent.com/8035743/142936228-59c89ee8-b008-440b-95ce-7b95bfcf5c97.gif)

### Versions and configuration

 CDDA version: 0.F-2 or latest git, tiles, Debian Linux x86_64 .

**Comment by ZhilkinSerg** [comment]
https://forums.libsdl.org/viewtopic.php?p=38817
https://stackoverflow.com/questions/68522099/black-edges-when-blending-transparent-texture

**Comment by rumly111** [comment]
> https://forums.libsdl.org/viewtopic.php?p=38817 https://stackoverflow.com/questions/68522099/black-edges-when-blending-transparent-texture

so, it's a bug with SDL or the graphic driver? there are no workarounds? then I don't mind tagging it "wontfix"

**Comment by Zireael07** [comment]
This keeps reoccuring - the most recent reports I recall were on Android, though, but I remember one on PC
