### ISSUE TITLE
Nonpurifiable mutations can still be lost by targeted mutagen

### ISSUE THREAD

**Issue by Venera3** [CleverRaven/Cataclysm-DDA#52961]
### Describe the bug

Despite setting `purifiable: false` traits can still be lost by targeted mutagens adding an incompatible trait.

### Steps To Reproduce

1. Mutate a non-purifiable trait with mutation incompatibilities (e.g. Proboscis)
2. Choose an incompatible trait(e.g. Wide Mouth) and debug-add it, note that it removes your supposedly-permanent trait
3. Re-add the non-purifiable trait and apply in enough serums of the target category to gain the incompatible trait

### Expected behavior

Purifiability being checked in targeted mutations as well.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-3890-gda132ebabf-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

At a glance `mutate()` - used for non-targeted mutations - checks for purifiability, `mutate_towards` doesn't.

**Comment by anoobindisguise** [comment]
oh gosh, just realized this means I won't be able to turn Imperceptive Healer into 8 free points by mutating fast healer. that's scary! I like that certain effects that say they're "permanent" like Ectothermic will actually mean that now, irreversible changes are cool. Especially once mutations will stop being instantaneous now.

**Comment by OmniscientQ** [comment]
I can confirm this behavior. My post-Threshold slime mutant had Distributed Neurology, and took some Cephalopod serum. The Distributed Neurology was downgraded to "Smart" then upgraded again to "Very Smart".
