### ISSUE TITLE
MAX_HP in Enhancement does not count towards hp regeneration

### ISSUE THREAD

**Issue by xxxyyyqqq12345** [CleverRaven/Cataclysm-DDA#52966]
### Describe the bug

When using MAX_HP as an enchantment with json, it adds the extra hit points to limbs but the extra hit points are not affected when regenerating. That is the character will not heal all the way to maximum when using such an enchantment.

### Steps To Reproduce

1. Create an new enchantment effect that uses MAX_HP
2. Create something that uses that enchantment ex:

` 
 {
    "id": "bio_super_hp_boost",
    "type": "bionic",
    "name": { "str": "Super HP Booster" },
    "description": "add 9999 max hp to all limbs",
	"enchantments": [
      {
        "condition": "ALWAYS",
        "values": [
		  { "value": "MAX_HP", "add": 9999 }        ]
      }
    ]
  }
`
3. Wait for it to heal (It won't)

### Expected behavior

The max hit points of all limbs increase and heals overtime to the maximum amount

### Versions and configuration

OS: Windows
Game Version: e5992d2 [64-bit]
Graphics Version: Tiles
Game Language: System language []

**Comment by chrispikula** [comment]
/confirmed

I got an artifact that increases my base HP
![image](https://user-images.githubusercontent.com/22281606/183275146-9fa51a11-437f-45d1-91dc-7c026e21b943.png)
 vs
 
![image](https://user-images.githubusercontent.com/22281606/183275152-9ef32315-be17-4a30-ba2a-f23afb9bde52.png)
And I perpetually stay at half HP.
Win 10 tiles, 8f8b8d9
