### ISSUE TITLE
Allow autodrive to be used outside of the map menu

### ISSUE THREAD

**Issue by SariusSkelrets** [CleverRaven/Cataclysm-DDA#52977]
# Is your feature request related to a problem? Please describe.
AutoTravel is nice but can only be used for long distances. There's some situations where short-range autotravel would be useful (such as trying to navigate a wheelchair in a house)

# Describe the solution you'd like
Allowing automove to be used from the look around

# Describe alternatives you've considered
None

# Additional context
Single-tile vehicles can't be turned without moving around in a circle but that's a separate issue

**Comment by Terrorforge** [comment]
That's already a feature. Press shift+T in look around mode.

Admittedly you can only walk to tiles you can see and I've never tried it with a small vehicle, but it is there.

**Comment by ZhilkinSerg** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/29885

**Comment by SariusSkelrets** [comment]
> Admittedly you can only walk to tiles you can see and I've never tried it with a small vehicle, but it is there.

I tried and it doesn't work on vehicles. I'll edit the request's name

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
