### ISSUE TITLE
Indefatigable and Hyperactive do not raise maximum stamina

### ISSUE THREAD

**Issue by alex-p-b** [CleverRaven/Cataclysm-DDA#52980]
### Describe the bug

Indefatigable and Hyperactive do not raise stamina by 25% and 40%, respectively. They instead do not affect maximum stamina whatsoever.

### Steps To Reproduce

1. Using debug mode, record maximum stamina
2. Give yourself Indefatigable and/or Hyperactive
3. Using debug mode, record maximum stamina after receiving aforementioned mutations. Maximum stamina will not have changed.

### Expected behavior

I expected that maximum stamina would have risen after receiving Indefatigable or Hyperactive.

### Versions and configuration

OS: Windows 10
Game version: e5992d2 (tiles)
Graphics version: Tiles
Ingame language: English
Mods loaded: dda, no_npc_food, no_fungal_growth, package_bionic_professions

**Comment by wapcaplet** [comment]
Confirmed. These traits' `max_stamina_modifier` values are supposed to affect `get_cardiofit()` which in turn affects `get_stamina_max()`, but it doesn't seem to matter - characters starting with or without these mutations have the same maximum stamina (8717, with default character template).

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-3988-g943e476770 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by wapcaplet** [comment]
Verified once again with some test cases I'm working on for cardio. The "Languorous" trait does affect maximum stamina but only by a rounding error (8714 versus 8717).
