### ISSUE TITLE
"atomic coffeemaker" cannot be [a]ctivated, but "coffeemaker" can?

### ISSUE THREAD

**Issue by AcidAntOnAMinefield** [CleverRaven/Cataclysm-DDA#52993]
### Describe the bug

I cannot activate an atomic coffee maker to heat up water, even if I go the long way around ([i]nventory > Atomic Coffee Maker > [a]ctivate), what I get is "You can't use a(n) atomic coffee maker there." Doesn't matter if I am near a counter, near a table or any surface. It won't ever work. But I can use a regular coffee maker just fine for anything. 

### Steps To Reproduce

1 - Start a new world in day 1 spring or peak winter. 
2 - Debug in an Atomic Coffee Maker, a Regular Coffeemaker and a Medium Battery of any kind to recharge the coffeemaker. 
3 - Move towards the closets/cupboards that have clean water and rations. 
4 - Try activating the atomic coffee maker, fail at it. 
5 - Try activating the regular coffeemaker only to then not understand why one is able to heat up solids and liquids and the other only works as a crafting tool. 

### Expected behavior

I would expect the atomic coffeemaker to be able to heat up frozen liquids at the very least. 

### Versions and configuration

- OS: Windows
    - OS Version: Windows 7
- Game Version: 330bb58 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    No Monsters [Only_Wildlife]
]

### Additional context

I would probably suggest that both have their volume updated, as the Atomic Coffeemaker has a volume of 1L and weight of 6.10kg, whereas the coffeemaker has a volume of 7L and a weight of 1kg.

**Comment by PatrikLundell** [comment]
#52965 looks like it should address this (while fixing #52394).

**Comment by Maleclypse** [comment]
Closed by #52965
