### ISSUE TITLE
Drag-Selection in inventory menus

### ISSUE THREAD

**Issue by Miner239** [CleverRaven/Cataclysm-DDA#52998]
# Is your feature request related to a problem? Please describe.
The number of keypresses done when picking up stacks of loot gets pretty high when the player is picky and doesn't want to pick up everything, Category Selection and Filters improves the looting experience by allowing the player to see and select only what they want. I think this can be improved further by adding drag-selection. This suggestion is inspired by a similar feature from Rimworld.

# Describe the solution you'd like
When the drag-select toggle is activated, the game remembers the selection state (selected or unselected, how many item selected in stack). Then, the player can move the selection cursor up and down, and the game applies the selection state to the cursor entry. Moving the cursor to an entry that has the same selection state as the first one does not change the selection state. 

# Describe alternatives you've considered
- Add a macro to automatically press down and left at the same time

# Additional context
---

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
