### ISSUE TITLE
M202A1 Flash Cannot be reloaded with a FULL magazine

### ISSUE THREAD

**Issue by estebandellasilva** [CleverRaven/Cataclysm-DDA#53002]
### Describe the bug

Got myself a M202A1 Flash but only recently found a fitting magazine (from a Talon UGV)

If the magazine is full i cannot reload the gun. 
If the magazine is empty i can reload the gun with the magazine, and then reload the magazine inside the gun.
If i take the magazine out and try to put it in again i cannot put it inside and would have to unload the magazine again.

### Steps To Reproduce

Get M202A1 Flash with a Magazine
Unload magazine from gun
Try to reload
Unload magazine
Try to reload the gun

### Expected behavior

If i have a magazine i should be able to reload the gun with a full magazine.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 1384c38 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Scorch-Mechanic** [comment]
I'm pretty sure this is the cause of #52936

**Comment by estebandellasilva** [comment]
Seems likely

**Comment by Photoloss** [comment]
> I'm pretty sure this is the cause of #52936

Can confirm the error I get when the bot attempts to fire implies this. Mentions item length rather than volume though.

**Comment by Hirmuolio** [comment]
After digging the problem seems to be the max length limit of the pocket.

The magazine well pocket is (unnecessarily) defined to be 20 liters.
Since there is no maximum length defned the code defaults to `(volume)^(1/3) * sqrt(2)`. Which in this case after all the rounding is 381 cm.
Empty M74 4-rocket clip is only 8 cm and can be used for reloading. But the loaded clip is 53 cm and doesn't fit in anymore.

**Comment by catdach** [comment]
> The magazine well pocket is (unnecessarily) defined to be 20 liters. 

For some reason every example of a gun with a magazine well defines `20 L` as the maximum volume and `20 kg` as the maximum weight
