### ISSUE TITLE
Slimes Won't Drop Globs

### ISSUE THREAD

**Issue by OmniscientQ** [CleverRaven/Cataclysm-DDA#53001]
### Describe the bug

Slimes that are generated by killing a larger slime will not drop globs once their smallest form is defeated. Only small slimes that were spawned in by themselves will drop a glob.

### Steps To Reproduce

1) Find a slime pit.
2) Do a massacre.
3) Find a pitifully small amount of globs equal to the number of small slimes that were already on the map when you arrived.

### Expected behavior

I recall from older versions that taking on a slime wave yielded vast troves of useful goo. I could even understand if the game somehow only yielded a single glob from any given slime, no matter how many pieces you cut it into before it finally died.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.2 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-3914-gdca8d570af [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Stats Through Skills [StatsThroughSkills],
    Disable NPC Needs [no_npc_food],
    Bionic Slots [cbm_slots]
]

**Comment by anoobindisguise** [comment]
Can confirm, killed a lot of slimes and got a lot of nothing many times myself.
