### ISSUE TITLE
After crafting, food will sometimes include more ingredients than it took to make them, giving them higher calorie contents. 

### ISSUE THREAD

**Issue by Holli-Git** [CleverRaven/Cataclysm-DDA#53006]
### Describe the bug

Food will sometimes have a lot more calories than it should and will list extra amounts of an ingredient. 

### Steps To Reproduce

1. Batch craft some foods
2. Save and quit, under what circumstances I haven't found out yet. 
3. Tada! Your food now has an impossible calorie content. 

### Expected behavior

I expect that food should be subject to the same laws of thermodynamics and not magically gain calories or ingredients 

### Screenshots

![image](https://user-images.githubusercontent.com/78005870/143327513-3b8a9825-366f-4f26-b2ee-bce37283dea2.png)
![image](https://user-images.githubusercontent.com/78005870/143327575-1a224084-25d2-4baf-8e3a-5f501f973f94.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 03f9cc1 [64-bit]
- Graphics Version: Tiles
- Game Language: Nederlands [nl]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

It seems to be infrequent, and mostly related to foods that you've crafted from hand, eg hand made sugar and clean water will sometimes make a lot more dense sweetwater. 
Also seems to be related to the portion sizes of the item, as I've had sweetwater that was made from 71 sugar. (Sadly forgotten to take a screenshot).

**Comment by estebandellasilva** [comment]
THe issue was mentioned several times - if you use an ingrediant which has different calorie values or ages( in your case flours) they dont average correctly the calorie count but instead add it some kinda of way together. If you cook that way the food gets a way higher calorie count

**Comment by OmniscientQ** [comment]
I provided that screenshot of the differing milk values. Even weirder is that when I first crafted them, they had no calories at all. I saved and quit in frustration, went to bed, and when I started up Cataclysm the next day, found those values waiting.

**Comment by gynther** [comment]
Can confirm that it happens for me aswell, but i have found no pattern as of yet.
Also that is some calorie rich s'more

![image](https://user-images.githubusercontent.com/622038/143657202-12bb8859-234a-405a-9146-3e8279fd65eb.png)

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 03f9cc1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

**Comment by Holli-Git** [comment]
Closing this, as I can't recall the last time I've heard or encountered this bug.
