### ISSUE TITLE
No ammo spawning in gun stores

### ISSUE THREAD

**Issue by angstr0m** [CleverRaven/Cataclysm-DDA#53007]
### Describe the bug

There are a lot of weapons and magazines in gun stores. But no ammo. The only exception I encountered being non broken ammo vending machines.

### Steps To Reproduce

1. Create a new world with standard settings.
2. Spawn with a random character, reveal the map and teleport to the nearest non looted gun store.
3. Observe: Lots of guns and magazines, but no ammo outside of rare non broken vending machines.

### Expected behavior

I would expect non looted gun stores to at least have some ammo located in the shelves or lockers.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 1384c38 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by catdach** [comment]
Most gun stores have a locked safe by the magazines or in a back room full of ammo. Are those empty as well? (make sure to 'e'xamine them after you've unlocked them to open them)

**Comment by angstr0m** [comment]
You're right. The safes are full of ammo. Thanks for the help :)!

I must have missed that change in gun stores (didn't play CDDA for some months). Since, to my understanding, this works as intended, I will close the issue. Thanks again :)!
