### ISSUE TITLE
Bionics Menu randomly reopens after using a bionic (finger lighter)

### ISSUE THREAD

**Issue by estebandellasilva** [CleverRaven/Cataclysm-DDA#53003]
### Describe the bug

Lately i go in Firestarting sprees and using the bionic lighter cbm i noticed that the menu behaves a little weird.

If i open the menu and then use the lighter there is a 50% chance that the menu pops up immediatly again.
Its not consistant, but reproduceable for me. Like sometimes it pops up like three times again. Sometimes not even once in 5 uses.

### Steps To Reproduce

Get Finger lighter CBM
Got to Forest and light stuff on fire
Notice that the cbm menu sometimes pops up again and sometimes not

### Expected behavior

Either the menu pops up again but every time or the menu closes after the use of a cbm. Both choices are ok, but please make it consistant

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 1384c38 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

Should you require my save to test please inform me, but unpacked it would be like 270mb so iam unsure if i can upload it, but i can try ( zipped it shows like 30mb)

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-8778. Started about 50 fires with my finger lighter, no random popups appeared. Closing for now, if this still an issue, ping me to reopen.
