### ISSUE TITLE
Better 3D fov symmetry

### ISSUE THREAD

**Issue by GoodDays13** [CleverRaven/Cataclysm-DDA#53013]
# Is your feature request related to a problem? Please describe.
When I'm on top of a building, enemies can see me from below, but when I'm below, I can't see zombies that are on top of buildings. It seems to work in an "if you can see it, it can see you" way, but you can't see up the same way you can see down.

# Describe the solution you'd like
Make it where when you are further away from a ledge you can see less that is close to that ledge below, like a perspective thing, then do the same for seeing enemies above you.

# Describe alternatives you've considered
You could also make it where you can just always see enemies above, or make it where enemies below can't see you when you're on something.

**Comment by GoodDays13** [comment]
And maybe also the ability to crouch or prone so you can see less below and zombies have to be further to see

**Comment by Maleclypse** [comment]
Would this be impacted/fixed by #53351?

**Comment by GoLoT** [comment]
For the first issue (symmetry), yes. There is a bug somewhere that I still need to track down but when it's fixed the visibility should work as described here.

For the crouched/prone part I have an idea that I've been meaning to implement but it will be a different PR. It will also use coverage values on furniture to restrict visibility.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
