### ISSUE TITLE
Hundred-dollar currency bundle looted from bank vault disassmbled into 10 Merch currency straps

### ISSUE THREAD

**Issue by Scorch-Mechanic** [CleverRaven/Cataclysm-DDA#53012]
### Describe the bug

Looted a bank vault of all its contents. Dropped all the currency bundles in front of an ATM and disassembled them all. Ended up with ten Merch currency straps on the floor, somehow. According to HHG, hundred-dollar currency bundles can disassemble into Merch currency straps, and I definitely looted one of those from the bank vault.

### Steps To Reproduce

1. Loot hundred-dollar currency bundles. 
2. Disassemble.
3. Pre-apocalpyse money somehow becomes post-apocalypse money.

### Expected behavior

Merch is a post-apocalypse currency, there should be no way to find it in a bank vault that's not under the control of the refugee center traders. Furthermore, it should be impossible to disassembled a hundred-dollar currency bundle into Merch currency straps, because Merch currency straps should only assemble into a Merch currency bundle. Looks like an oversight to me.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 1384c38 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

**Comment by Amoebka** [comment]
Free merchants use pre-cataclysm dollar bills to "print" their currency, so it's likely intended.

**Comment by Scorch-Mechanic** [comment]
Yes, but the way they convert U.S. money to Merch is by stamping it with a special stamp and signing it. Merch is expressly a post-apocalpse currency, it should be impossible to get it from inside of a bank vault that's been sealed since the start of the apocalypse.
