### ISSUE TITLE
Magiclysm balrog mine special can get the player trapped in rock

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#53023]
### Describe the bug

When you reach the end of the mine and you step into the empty space, you will end up being in solid rock.

### Steps to reproduce

1. Get to the balrog mine, right at the end where the fiery nightmare resides.
2. Step into the empty space.
3. Get stuck.

### Expected behavior

There should be something below the empty space, like lava or even just rocky terrain with a few more skeletons and lava which actually improves environmental story telling.
I would also remove the lava next to the empty space and place it down below instead. Or just make little mounds with rocky floor next to it.

### Screenshots

![image](https://user-images.githubusercontent.com/59517351/143443000-d5a8ff7d-7623-4611-a2d7-2be110735799.png)

### Versions and configuration

- experimental

**Comment by Night-Pryanik** [comment]
How would placing lava on the level beneath help? Lava will burn player to death in any case. 

These empty spaces are supposed to be bottomless. In game terms that means max 10 levels down, falling down in these is a guaranteed death. So the only right decision is NOT stepping on them.

**Comment by Zireael07** [comment]
> So the only right decision is NOT stepping on them.

Is this clearly communicated to the player? Is the player really killed when stepping on them?

**Comment by Night-Pryanik** [comment]
> Is this clearly communicated to the player?

No. I'm not sure how this should be better communicated besides "Really step into ledge?".

> Is the player really killed when stepping on them?

No. But I think they should be.

**Comment by NetSysFire** [comment]
>How would placing lava on the level beneath help? Lava will burn player to death in any case.

Cosmetic reasons. Floating lava will work but I think it would look more pretty if it was below or as a little "mound".

**Comment by NetSysFire** [comment]
>No. I'm not sure how this should be better communicated besides "Really step into ledge?".

In real life, you can look down ledges. So if you see an infinite amount of darkness below, maybe even drop a pebble and do not hear how it hits the ground, you might not want to drop down.
So the empty space tile should have a description like "You can not see the bottom, no matter how hard you try." since it clearly differs from a "normal" drop.

On the other hand, having a bottomless abyss on z-level -4 and then solid rock on z-level 5 makes it inconsistent. Maybe the empty space tile can be used as a sort of substitute for "make all tiles below also open air" and then having an instant death when you reach z-level -11? This does feel like yak shaving though.

**Comment by Night-Pryanik** [comment]
I added 6 levels of open air below the main tunnels. Most players will die from the impact if they jump down.

**Comment by Night-Pryanik** [comment]
> In real life, you can look down ledges.

You can do it ingame too.

>So the empty space tile should have a description like "You can not see the bottom, no matter how hard you try." or "This drop feels really deep..." since it clearly differs from a "normal" drop.

Adding this might be useful, though this might require way too much hassle.

**Comment by NetSysFire** [comment]
Thanks for the incredibly quick fix!

>You can do it ingame too.

That is the experimental 3d-fov, right?

**Comment by Night-Pryanik** [comment]
> That is the experimental 3d-fov, right?

Yeah, exactly.

**Comment by Maleclypse** [comment]
Closed via #53024
