### ISSUE TITLE
Examine nearby terrain, furniture, and items key binding is missing item menu in vehicles.

### ISSUE THREAD

**Issue by morthein** [CleverRaven/Cataclysm-DDA#53040]
### Describe the bug

#52873 caused items in vehicles to no longer register as items to pick up in the menu when using the 'new' key binding (examine nearby terrain, furniture, and items) You have to use the previous key binding (pick up items from one nearby tile) to pick them up.

### Steps to reproduce

1. start a vehicle construction with a box
2. place something in the box
3. make sure you're using the 'new' key binding from #52873 (examine terrain, furniture, and items)
4. try to get items from box, notice you cant without using the other key binding (pick up items from one nearby tile)

### Expected behavior

The old behavior just plainly understood there was items there and added the 'pickup items' to the possibilities of menu selections. 

The game does recognize there are items there and if I use the singular key binding to 'pick up items from one nearby tile' it can pick them up.

It'd be nice if the get items menu selection was added to the 'examine nearby terrain, furniture, and items' when using it in a vehicle. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 04d1bce [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    No Hope [no_hope],
    Alternative Map Key [alt_map_key],
    Crazy Cataclysm [crazy_cataclysm],
    Extra Mutated Scenarios [extra_mut_scens],
    Mining Mod [Mining_Mod],
    No Rail Stations [No_Rail_Stations],
    Cars to Wrecks [cars_to_wrecks],
    Graphical Overmap [Graphical_Overmap],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by wapcaplet** [comment]
Confirmed. Could have sworn I tested this in my PR, but indeed the "g Pick up items" option is not availble using "Examine nearby terrain, furniture, and items" keybinding.

![image](https://user-images.githubusercontent.com/238395/143610135-096e067c-69e6-4b63-b3b3-561d8e6b06be.png)

I will work on a fix.

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-4059-g04d1bcebc5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
