### ISSUE TITLE
101 Important Integrated Circuits cannot be used as a tool for practicing integrated circuits when stored on e-ink tablet

### ISSUE THREAD

**Issue by mmiki2305** [CleverRaven/Cataclysm-DDA#53042]
### Describe the bug

When I store the book on a tablet and get rid of the physical book, I lose access to the tool to practice integrated circuits.

### Steps to reproduce

1. Make a character.
2. Use the debug menu to give them 3 electronics skill, 101 Important Integrated Circuits book, e-ink tablet, and a light battery to power it.
3. Read the book once to get access to the recipe.
4. Check 'Practice' in crafting menu to see that the tool requirement for the book is green.
5. Reload the tablet with the battery and store the book.
6. Drop the book out of crafting range.
7. Check the crafting menu again, the book tool requirement will be red.

### Expected behavior

I would expect to be able to use a digital version of the book in the same way as a physical copy.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 04d1bce [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth]
]

**Comment by VitreousEyes110** [comment]
Bug confirmed in the most recent experimental, reproduced following the steps described above.

Electronics 3 given to character.
![Screenshot (323)](https://user-images.githubusercontent.com/45680256/145903430-fd98f622-c52f-4de5-9f2e-ceb11036c3e5.png)
Items given to character, e-ink tablet has full battery and no stored book.
![Screenshot (321)](https://user-images.githubusercontent.com/45680256/145903422-6ae81c23-f42d-4a71-ba7c-924553f69909.png)
Practice recipe shows the book in green.
![Screenshot (322)](https://user-images.githubusercontent.com/45680256/145903452-1a98b724-a02f-4e02-a306-b0cc9fe96a18.png)

Book stored in the e-ink tablet, and then dropped outside of crafting range.
![Screenshot (324)](https://user-images.githubusercontent.com/45680256/145903611-52bbe4d4-c298-4131-b67a-0fcb9434cd6f.png)
Showing the book is stored in the e-ink tablet, and that it contains the relevant recipe.
![Screenshot (325)](https://user-images.githubusercontent.com/45680256/145903617-474241db-c91d-45cc-b3d0-2fef86f636b9.png)
Practice recipe shows the book in red despite the character's access to it via the e-ink tablet's storage.
![Screenshot (326)](https://user-images.githubusercontent.com/45680256/145903625-b01108c7-229c-4b53-9dc2-23a9579e1ee4.png)

Generated game report:
- OS: Windows
    - OS Version: 10.0 1607
- Game Version: 8b7a449 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by LeahLuong** [comment]
Maybe the book has a little breadboard & baggie of electronic components in its cover to practice w/??

**Comment by VitreousEyes110** [comment]
I doubt that's the case, the item description doesn't mention any components included with the manual and the crafting recipe requires you to have a breadboard and many components alongside the book. I assume that the book is just included as a tool in the practice recipe as an oversight.

> **101 Important Integrated Circuits** This reference manual contains datasheets and pinout diagrams for 101 of the most popular IC chips, including the 555 timer, LM358 op-amp, and LM317 voltage regulator, along with logic chips from the 74xx family, and even the 6502 8-bit processor. If you want to do anything useful with integrated circuits, a reference like this would be indispensable.

No mention of any electronic components coming with the book, just datasheets and pinout diagrams used for reference.

If it is meant to have included components, they should be removable from the book with the pockets system, or maybe detachable via dissassembly resulting in the book and a plastic bag containing the components. But I don't think that's the intention.

**Comment by hexagonrecursion** [comment]
> Maybe the book has a little breadboard & baggie of electronic components in its cover to practice w/??

The recipe already requires a breadboard and a bunch of other stuff.

**Comment by LeahLuong** [comment]
Thanks, hex, but I did get that from Vit's previous comment.
