### ISSUE TITLE
Zero portal storms after thirty days

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#53041]
### Describe the bug

I was under the impression that I should have seen a portal storm by now, but given that I'm trying to prove a negative, I can't really be sure.

### Steps to reproduce

Unknown. For all I know, my save is functioning correctly and I'm just getting lucky.

### Expected behavior

I expected to see portal storms by now

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 1384c38 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

Here is my save file
[Roger.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7609459/Roger.zip)

I'm seeing things in the save file that suggest that portal storms are functioning correctly, but I can't tell for sure. Since I haven't seen a portal storm yet, I can't tell you what their normal behavior SHOULD be. All I know is that what I am seeing is not what I was led to expect from pull requests about portal storms.

**Comment by Inglonias** [comment]
Found this in the save file:
`{ "time": 7818976, "eoc": "EOC_PORTAL_STORM_WARN_OR_CAUSE_RECURRING" }`

Changed time to just before this happens, and sure enough, I do see the message in the log warning me of a portal storm. Looks like I still have another week to go or thereabouts.

Leaving this open in case there's some more behavior that needs checking.

**Comment by Ramza13** [comment]
Did you update versions with this save?  I'll take a look at the save later but it shouldn't take 30 days for one to happen.

**Comment by Inglonias** [comment]
I do update my game as new experimentals come out.

**Comment by Ramza13** [comment]
So if you updated a save on day 30 to a version with portal storms the correct behavior would be for the next portal storm to happen about a week later.  So this might not be a bug.

**Comment by Terrorforge** [comment]
I will say that portal storms seem a little too infrequent. I recently had a game that went to about summer 60, and I only saw... one storm? Maybe two?
