### ISSUE TITLE
Trade Menu - Sorting and Inventory Problems - too many items

### ISSUE THREAD

**Issue by estebandellasilva** [CleverRaven/Cataclysm-DDA#53057]
### Describe the bug

With the change to the new trade window 2 Problems became more apparent.

Frist:  Sorting inventory into categories only works if the items are in the inventory of the character.
This means a soon as you sell more stuff to them and they drop stuff on the ground you, and they restock you need to know what you are looking for as it is becoming harder and harder to find

Second : NPC Restock, which iss intended - but they never consume stuff you sell them which also leads to the problem mentioned above. This could lead to the trader sooner or later be unable to offer his stuff as he could be outside the range of the item he can offfer. ( had this issue with the free traders at the hub because they hunted one of the hubspies and ran away from some of his stuff he could sell me)

### Steps to reproduce

Find a trader (hub, refugee center)
Sell him stuff
wait for him to restock
see that now the inventory gets bigger and if stuff is on the ground its no longer sorted

### Expected behavior

Maybe apply sorting to all of the inventory he is offering?

But as it  stands currently NPC traders get overwhelmed by their items sooner or later.
NPCs need a way to get rid of Items without the Player involvement.

### Screenshots

First Page everything ok
![image](https://user-images.githubusercontent.com/89189872/143678612-5cbe020a-d72c-4f92-a66f-d0ad3c1de79f.png)
Second page no longer sortet after categories
![image](https://user-images.githubusercontent.com/89189872/143678630-17b10934-78d2-4c6f-b08f-7f4fe9dc6ddb.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: b0e629c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by andrei8l** [comment]
It definitely makes sense for a shopkeeper's items to always be categorized, but I'm not so sure about an NPC's or the player's items. What do you think? I think that would need an additional column (for location) that would make this UI a lot more awkward without arbitrary & selectable sorting (like in the AIM).

**Comment by estebandellasilva** [comment]
When trading, what use do i get from the information of the location of the item? Even if i where interessted in stealing the view Menu would probably be easier than the trade window for accessing the information

**Comment by Lord-Helmchen** [comment]
> But as it stands currently NPC traders get overwhelmed by their items sooner or later.
> NPCs need a way to get rid of Items without the Player involvement.
The same conclusion was also mentioned in https://github.com/CleverRaven/Cataclysm-DDA/issues/46766#issuecomment-810642984_

this ist the crux of the matter. especially since the stuff I sell is probably not what I want to buy later.
It could be assumed that , given time, the trader can get rid of things he bought from me (probably at a profit, otherwise why would they buy it in the first place? or if they are a collector, moving it to their personal vault or something).
and as there is no way to remove items on the ground via debug, this can't even be handwaved until it is solved somehow :-(

**Comment by andrei8l** [comment]
Consumption and restocking was fixed in #56720 and follow-ups
Sorting by category was fixed in #62423
