### ISSUE TITLE
Error when getting a mission from the teamster NPC

### ISSUE THREAD

**Issue by mmiki2305** [CleverRaven/Cataclysm-DDA#53058]
### Describe the bug

When trying to get a mission from an NPC I get an error.  I still get the mission 'Check out the farm', but it does not seem to have any coordinates, and there is no mission marker.  I don't think the location actually spawned.

### Steps to reproduce

Teleport to the refugee center, talk to teamster NPC and ask them about whether the caravans have noticed something strange.  In testing I had to do several tries to reproduce this because the NPC sometimes tells you they don't have anything, and other times I get the Isherwood farm which seems to spawn correctly.

### Expected behavior

I expected a mission marker and coordinates.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 688e5d1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

Debug.log trace:

-----------------------------------------
13:12:31.252 : Starting log.
13:12:31.252 INFO : Cataclysm DDA version 688e5d1
13:12:31.253 INFO : [main] C locale set to C
13:12:31.253 INFO : [main] C++ locale set to C
13:12:31.253 INFO : SDL version used during compile is 2.0.14
13:12:31.253 INFO : SDL version used during linking and in runtime is 2.0.14
13:12:31.476 INFO : Number of render drivers on your system: 5
13:12:31.476 INFO : Render driver: 0/direct3d
13:12:31.476 INFO : Render driver: 1/direct3d11
13:12:31.476 INFO : Render driver: 2/opengl
13:12:31.476 INFO : Render driver: 3/opengles2
13:12:31.476 INFO : Render driver: 4/software
13:12:31.479 INFO : [options] C locale set to C
13:12:31.479 INFO : [options] C++ locale set to C
13:12:31.479 INFO : Setting language to: 'en'
13:12:31.479 INFO : [i18n] Scanning core translations from lang/mo/
13:12:31.479 INFO : [i18n] Scanning mod translations from ./mods/
13:12:31.481 WARNING : opendir [./mods/] failed with "No such process".
13:12:31.600 INFO : Active renderer: 0/direct3d
13:12:31.707 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
13:12:31.825 INFO : Setting language to: 'en'
13:12:31.967 WARNING : opendir [./mods/] failed with "No such process".
13:12:38.085 WARNING : opendir [./save/Kentmore Park/mods] failed with "No such process".
13:12:56.212 INFO : Loaded tileset: Chibi_Ultica
13:12:57.406 INFO : Loaded tileset: Chibi_Ultica
13:13:22.424 ERROR : (error message will follow backtrace)
  #0
    (dbghelp: @0x7ff7bebd898f[cataclysm-tiles.exe+0x1d898f]), 
    (libbacktrace: register_frame_ctor+0x7ff67d68154f@0x7ff7bebd898f),
    (libbacktrace: 0x7ff7bebd898f    [unknown src]:0    [unknown func]),
  #1
    (dbghelp: @0x7ff7bebd9752[cataclysm-tiles.exe+0x1d9752]), 
    (libbacktrace: register_frame_ctor+0x7ff67d682312@0x7ff7bebd9752),
    (libbacktrace: 0x7ff7bebd9752    [unknown src]:0    [unknown func]),
  #2
    (dbghelp: @0x7ff7bebda7c4[cataclysm-tiles.exe+0x1da7c4]), 
    (libbacktrace: register_frame_ctor+0x7ff67d683384@0x7ff7bebda7c4),
    (libbacktrace: 0x7ff7bebda7c4    [unknown src]:0    [unknown func]),
  #3
    (dbghelp: @0x7ff7bf746d7d[cataclysm-tiles.exe+0xd46d7d]), 
    (libbacktrace: register_frame_ctor+0x7ff67e1ef93d@0x7ff7bf746d7d),
    (libbacktrace: 0x7ff7bf746d7d    [unknown src]:0    [unknown func]),
  #4
    (dbghelp: @0x7ff7befaffc8[cataclysm-tiles.exe+0x5affc8]), 
    (libbacktrace: register_frame_ctor+0x7ff67da58b88@0x7ff7befaffc8),
    (libbacktrace: 0x7ff7befaffc8    [unknown src]:0    [unknown func]),
  #5
    (dbghelp: @0x7ff7befb0091[cataclysm-tiles.exe+0x5b0091]), 
    (libbacktrace: register_frame_ctor+0x7ff67da58c51@0x7ff7befb0091),
    (libbacktrace: 0x7ff7befb0091    [unknown src]:0    [unknown func]),
  #6
    (dbghelp: @0x7ff7befb015e[cataclysm-tiles.exe+0x5b015e]), 
    (libbacktrace: register_frame_ctor+0x7ff67da58d1e@0x7ff7befb015e),
    (libbacktrace: 0x7ff7befb015e    [unknown src]:0    [unknown func]),
  #7
    (dbghelp: @0x7ff7befaf21d[cataclysm-tiles.exe+0x5af21d]), 
    (libbacktrace: register_frame_ctor+0x7ff67da57ddd@0x7ff7befaf21d),
    (libbacktrace: 0x7ff7befaf21d    [unknown src]:0    [unknown func]),
  #8
    (dbghelp: @0x7ff7bfab198d[cataclysm-tiles.exe+0x10b198d]), 
    (libbacktrace: register_frame_ctor+0x7ff67e55a54d@0x7ff7bfab198d),
    (libbacktrace: 0x7ff7bfab198d    [unknown src]:0    [unknown func]),
  #9
    (dbghelp: @0x7ff7bef8f1db[cataclysm-tiles.exe+0x58f1db]), 
    (libbacktrace: register_frame_ctor+0x7ff67da37d9b@0x7ff7bef8f1db),
    (libbacktrace: 0x7ff7bef8f1db    [unknown src]:0    [unknown func]),
  #10
    (dbghelp: @0x7ff7bf0b4925[cataclysm-tiles.exe+0x6b4925]), 
    (libbacktrace: register_frame_ctor+0x7ff67db5d4e5@0x7ff7bf0b4925),
    (libbacktrace: 0x7ff7bf0b4925    [unknown src]:0    [unknown func]),
  #11
    (dbghelp: @0x7ff7bf0c5e30[cataclysm-tiles.exe+0x6c5e30]), 
    (libbacktrace: register_frame_ctor+0x7ff67db6e9f0@0x7ff7bf0c5e30),
    (libbacktrace: 0x7ff7bf0c5e30    [unknown src]:0    [unknown func]),
  #12
    (dbghelp: @0x7ff7bf0d7ca2[cataclysm-tiles.exe+0x6d7ca2]), 
    (libbacktrace: register_frame_ctor+0x7ff67db80862@0x7ff7bf0d7ca2),
    (libbacktrace: 0x7ff7bf0d7ca2    [unknown src]:0    [unknown func]),
  #13
    (dbghelp: @0x7ff7bf0d7fe8[cataclysm-tiles.exe+0x6d7fe8]), 
    (libbacktrace: register_frame_ctor+0x7ff67db80ba8@0x7ff7bf0d7fe8),
    (libbacktrace: 0x7ff7bf0d7fe8    [unknown src]:0    [unknown func]),
  #14
    (dbghelp: @0x7ff7bf0d9553[cataclysm-tiles.exe+0x6d9553]), 
    (libbacktrace: register_frame_ctor+0x7ff67db82113@0x7ff7bf0d9553),
    (libbacktrace: 0x7ff7bf0d9553    [unknown src]:0    [unknown func]),
  #15
    (dbghelp: @0x7ff7becf6f5a[cataclysm-tiles.exe+0x2f6f5a]), 
    (libbacktrace: register_frame_ctor+0x7ff67d79fb1a@0x7ff7becf6f5a),
    (libbacktrace: 0x7ff7becf6f5a    [unknown src]:0    [unknown func]),
  #16
    (dbghelp: @0x7ff7becfb902[cataclysm-tiles.exe+0x2fb902]), 
    (libbacktrace: register_frame_ctor+0x7ff67d7a44c2@0x7ff7becfb902),
    (libbacktrace: 0x7ff7becfb902    [unknown src]:0    [unknown func]),
  #17
    (dbghelp: @0x7ff7bec06fa9[cataclysm-tiles.exe+0x206fa9]), 
    (libbacktrace: register_frame_ctor+0x7ff67d6afb69@0x7ff7bec06fa9),
    (libbacktrace: 0x7ff7bec06fa9    [unknown src]:0    [unknown func]),
  #18
    (dbghelp: @0x7ff7bfdb5a97[cataclysm-tiles.exe+0x13b5a97]), 
    (libbacktrace: register_frame_ctor+0x7ff67e85e657@0x7ff7bfdb5a97),
    (libbacktrace: 0x7ff7bfdb5a97    [unknown src]:0    [unknown func]),
  #19
    (dbghelp: @0x7ff7bea013c1[cataclysm-tiles.exe+0x13c1]), 
    (libbacktrace: register_frame_ctor+0x7ff67d4a9f81@0x7ff7bea013c1),
    (libbacktrace: 0x7ff7bea013c1    [unknown src]:0    [unknown func]),
  #20
    (dbghelp: @0x7ff7bea014d6[cataclysm-tiles.exe+0x14d6]), 
    (libbacktrace: register_frame_ctor+0x7ff67d4aa096@0x7ff7bea014d6),
    (libbacktrace: 0x7ff7bea014d6    [unknown src]:0    [unknown func]),
  #21
    (dbghelp: BaseThreadInitThunk+0x14@0x7ffec7923034[KERNEL32.DLL+0x13034]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #22
    (dbghelp: RtlUserThreadStart+0x21@0x7ffec9ad1551[ntdll.dll+0x71551]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
Backtrace emission took 0 seconds.
(continued from above) ERROR : src/mission_util.cpp:251 [cata::optional<coords::coord_point<tripoint, coords::origin::abs, coords::scale::overmap_terrain> > find_or_create_om_terrain(const tripoint_abs_omt&, const mission_target_params&)] Unable to find and assign mission target robofac_hq_surface_freemerchant_camp.

**Comment by Venera3** [comment]
Good first issue, the teamster's mission target placements just need the `om_special` field. Basically the same as #53000 , I just didn't notice the other two missions having the same problem when doing that little drive-by fix.

**Comment by Alex-Folts** [comment]
Im facing the same issue.

**Comment by GordanGeeko** [comment]
I just got the same issue with the Teamster mission at the Refugee center.

**Comment by ccaviness** [comment]
Running latest experimental (`0.F-5519-gee4600e1e8`), and just had this when talking to the teamster:
```
 DEBUG    : Unable to find and assign mission target robofac_hq_surface_freemerchant_camp.

 FUNCTION : cata::optional<tripoint_abs_omt> find_or_create_om_terrain(const tripoint_abs_omt &, const mission_target_params &)
 FILE     : src/mission_util.cpp
 LINE     : 251
 VERSION  : 0.F-5519-gee4600e1e8
```

The `Check out the farm` mission is listed, but with no coordinates as a target.

**Comment by hahaha1776** [comment]
same here

**Comment by edusaraiva** [comment]
Having the same issue latest experimental [Cataclysm-DDA experimental build 2022-02-21-2034] 
DEBUG    : Unable to find and assign mission target robofac_hq_surface_freemerchant_camp.

 FUNCTION : find_or_create_om_terrain
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\mission_util.cpp
 LINE     : 251
 VERSION  : a139c2e
