### ISSUE TITLE
Certain ammo pouches have volume capacity 2000000L, wearing two makes available volume go negative.

### ISSUE THREAD

**Issue by d-schlereth** [CleverRaven/Cataclysm-DDA#53061]
### Describe the bug

As of experimental build 2021-11-26-0633 some ammo pouches have a volume capacity of 2000000L. Wearing two of these together results in a negative max volume, which makes picking up items impossible due to lack of space.

Ammo pouches affected, as far as I've found in the `ammo_pouch.json` file:

ammo pouch, quiver, quiver_birchbark, quiver_large, quiver_large_birchbark, tacvest.

All these seem to have the pocket data defined through ammo restriction like for example `"pocket_data": [ { "ammo_restriction": { "arrow": 60, "bolt": 60 }, "moves": 20 } ]`.

### Steps to reproduce

Equip any 2 of the following items together: ammo pouch, quiver, quiver_birchbark, quiver_large, quiver_large_birchbark, tacvest.
Open inventory, the max volume should now display negative, preventing any items from being picked up even if there is room in another pocket available (i.e. backpack or similar).

### Expected behavior

I expect ammo pouches that can hold a set number of a specific ammo type to have no effect on the max inventory volume.

### Screenshots

![ammo_pouches](https://user-images.githubusercontent.com/49560870/143686523-a3604014-3dd0-45a6-8966-5526e5ce9e05.png)

### Versions and configuration

Game version experimental 2021-11-26-0633 and newer tested.

**Comment by Zireael07** [comment]
Related to #53044 (this is more generic of the two)

**Comment by Terrorforge** [comment]
Fwiw, if you go into Settings and enable "Dangerous pickups", it should let you pick up items even though it thinks you're full; your actual ability to put things into containers doesn't seem to be affected.

**Comment by d-schlereth** [comment]
That is actually a fair workaround for the time being, thank you for the tip. The volume display seems to count a lot of small pockets that don't really hold anything useful so the display can be a bit imprecise, did not know about that option yet though.
