### ISSUE TITLE
Canteen faction camp expansion (version 1) does not display most furnishing mission options

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#53065]
### Describe the bug

So, I have a faction camp with a canteen expansion, and despite the fact that it's lacking many of its furnishing options, it seems to be about as done as it's going to get until this problem is fixed. The missions to build furnishings for the pantry and dining hall, as well as the butchery area and the planters, are completely absent from the menu for sending NPCs on missions.

### Steps to reproduce

1. Make a faction camp with a canteen (version 1) expansion
2. Build the expansion up enough that the furnishing options mentioned above should appear
3. Notice that they do not appear

### Expected behavior

I expect to be able to send my NPC followers on missions to furnish the canteen until it is complete, and all recipes are available.

### Screenshots

![Furnishing options missing from canteen](https://user-images.githubusercontent.com/60671985/143690499-cc04b15b-fc0b-4f03-8095-98e239f15492.png)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version [Windows 8.1 Pro]
- Game Version: 95019f2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    XEAS [XEAS],
    Gun Cotton [guncotton],
    DinoMod [DinoMod],
    Youkai Enemies [Youkai_Disco],
    Mining Mod [Mining_Mod],
    Mole Mutation [dig_a_tunna],
    More Survivor Stuff [more_survivor_stuff],
    Mythical Martial Arts [MMA],
    More City Locations [cityside],
    No Rail Stations [No_Rail_Stations],
    Compatible Nimian Manufacture Guns [NM_wpns],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    Magiclysm No Class Limit [magiclysm_no_class_limit],
    Mutation Changes [Mutation_Changes],
    Portable Autodoc [portable_autodoc],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Useful Helicopters [useful_helicopters],
    Arcana and Magic Items [Arcana],
    return_the_nut [return_the_nut],
    Hydroponics [hydroponics],
    Cooler Versatility [coolervers],
    Chris K's Knives [ChrisKsKnives],
    Custom Spells [Custom_Spells],
    Reproduction mod [perverts],
    Custom Bionics [custom_bionics],
    Magiclysm Runes in Arcana Recipes [Custom_ArcanaRune],
    Deconstruction Plus [Deconstruction_plus],
    Core Data Changes [core_data_changes],
    Arcadia Mapgen [custom_arcadia_mapgen],
    Dripbots [dripbots],
    Hard Steel Armor [hardsteel_armor]
]

### Additional context

I looked through my canteen basecamp recipes (which I have not edited) for any sign of anything that would cause this problem, and have found nothing. I already searched through all of the mods I use for anything that might change how the canteen mission recipes work, and the only mod that even mentions basecamps at all in its data is Aftershock, which does not modify the canteen. Also, I have another faction camp set up with the version 2 canteen expansion, and that one doesn't seem to have the same problem.

**Comment by PatrikLundell** [comment]
If I remember correctly, version 1 doesn't enable the construction of planters until something else has been constructed (unlike version 2, where it's available immediately). The other missing recipes are all dependent on other parts having been constructed first, so a guess is that somehow a token hasn't been registered correctly.
It might be useful to have an image of the bugged expansions so it's possible to figure out what has been constructed and what's missing.

**Comment by AmarinReyny** [comment]
> If I remember correctly, version 1 doesn't enable the construction of planters until something else has been constructed (unlike version 2, where it's available immediately). The other missing construction recipes are all dependent on other parts having been constructed first, so a guess is that somehow a token hasn't been registered correctly. It might be useful to have an image of the bugged expansions so it's possible to figure out what has been constructed and what's missing.
> 
> Edit: If you remember, it might be useful to know what your building was made out of. I tried to repeat it by constructing a version 1 canteen out of mi-go resin (because that's the fastest and easiest) and then tried to construct both fireplaces and stoves, and in both cases the option to construct smoking racks appeared next. Building the smoking racks provided the same cooking recipe list as you posted, but with options to continue the construction of the canteen (pantry, smoking rack roof, kitchen counters, well). This was done using whatever was in the master branch a few days ago.

The fireplaces, well, counter/shelves, and smoking rack have been built, and the material used for the building was metal.

I doubt this will influence anything, but I did also smash one of the fireplaces to replace it with a "vehicle" meant to serve as an electric stove, I replaced all the counters with workbenches, I removed one of the workbench tiles to make room for another "vehicle" meant to serve as a freezer, and I replaced all the default shelves with warehouse shelves, after the kitchen furnishings had been finished. However, since that's all after the furnishings were already constructed, I doubt it matters.

**Comment by PatrikLundell** [comment]
Nope, I still can't reproduce it. I built the stuff you listed in a metal building, smashed the left fireplace and deconstructed all counters and shelves (and I agree that removing these shouldn't matter, but it sometimes happen that "this can't affect that" sometimes actually does, so mentioning everything is a good thing).
Vehicles in the way of buildings will cause construction to fail, but not recipes to fail to be listed.
It seems this expansion hasn't been touched for a year (apart from a change I did on fake furniture 20 days ago, and your version is older and that change shouldn't amount to any functional change, and screw up cooking recipes if it did result in a functional change).

My current guess is that either your save or your game installation is damaged in some way, but I don't know how hard it would be to repair the save if that's the case.
I've looked at my old 0.E2 stable save which contains the canteen (at that time only version) in metal, and the file o.0.0 contains the string "fbmk_center" 4 times at line 32 (Notepad++ can search for strings in all the files in a directory structure). The construction of the first canteen part should result in one pair of "fbmk_center" and the second one (required for the counters and shelves) results in one pair of "fbmk_center_2". I don't know why they're duplicated, and currently I'm too lazy to try to find out. These two tokens should be present for the following constructions to be available (some depend on one, and the rest on the other). If there are tokens for parts you haven't constructed, such as e.g. "fbmk_canteen_dining_*" that indicates the save think you have constructed them, which would explain why it doesn't allow you to construct them again.

I'd start with the game, though, by renaming the current game installation, download and install the current experimental (or reinstall the one you've used, if you still have the download) and copy over the save to see if that fixes the problem. If it does, you apparently have an uncle named Robert, and if it doesn't, I'd delete the new installation (unless you want to upgrade, in which case you'd have to re-change any key bindings and other settings you've modified) and rename the old one back to its original name.

**Comment by AmarinReyny** [comment]
> Nope, I still can't reproduce it. I built the stuff you listed in a metal building, smashed the left fireplace and deconstructed all counters and shelves (and I agree that removing these shouldn't matter, but it sometimes happen that "this can't affect that" sometimes actually does, so mentioning everything is a good thing). Vehicles in the way of buildings will cause construction to fail, but not recipes to fail to be listed. It seems this expansion hasn't been touched for a year (apart from a change I did on fake furniture 20 days ago, and your version is older and that change shouldn't amount to any functional change, and screw up cooking recipes if it did result in a functional change).
> 
> My current guess is that either your save or your game installation is damaged in some way, but I don't know how hard it would be to repair the save if that's the case. I've looked at my old 0.E2 stable save which contains the canteen (at that time only version) in metal, and the file o.0.0 contains the string "fbmk_center" 4 times at line 32 (Notepad++ can search for strings in all the files in a directory structure). The construction of the first canteen part should result in one pair of "fbmk_center" and the second one (required for the counters and shelves) results in one pair of "fbmk_center_2". I don't know why they're duplicated, and currently I'm too lazy to try to find out. These two tokens should be present for the following constructions to be available (some depend on one, and the rest on the other). If there are tokens for parts you haven't constructed, such as e.g. "fbmk_canteen_dining_*" that indicates the save think you have constructed them, which would explain why it doesn't allow you to construct them again.
> 
> I'd start with the game, though, by renaming the current game installation, download and install the current experimental (or reinstall the one you've used, if you still have the download) and copy over the save to see if that fixes the problem. If it does, you apparently have an uncle named Robert, and if it doesn't, I'd delete the new installation (unless you want to upgrade, in which case you'd have to re-change any key bindings and other settings you've modified) and rename the old one back to its original name.

Will do, when I have the energy do go through all that. Thank you for the suggestion.

**Comment by hexagonrecursion** [comment]
@AmarinReyny, I recommend you to put more effort into debugging issues on your end before reporting them here:
* Try replicating them in a fresh world
* Try copying the world into an installation recreated from scratch

Given what you told me in #52836 there is a substantial chance for you to experience issues that only affect you and can not be replicated (and therefore can not be debugged) anywhere else. Even issues seemingly unrelated to the changes you have made.

If you want someone else's help debugging an installation of C:DDA that is customized to such a degree, you should ~upload the entire installation~ *upload them all and let god sort them out*.

**Comment by AmarinReyny** [comment]
> @AmarinReyny, I recommend you to put more effort into debugging issues on your end before reporting them here:
> 
> * Try replicating them in a fresh world
> * Try copying the world into an installation recreated from scratch
> 
> Given what you told me in #52836 there is a substantial chance for you to experience issues that only affect you and can not be replicated (and therefore can not be debugged) anywhere else. Even issues seemingly unrelated to the changes you have made.
> 
> If you want someone else's help debugging an installation of C:DDA that is customized to such a degree, you should ~upload the entire installation~ _upload them all and let god sort them out_.

I suppose I should, yeah. I'll get that upload going, but it'll be a while.

**Comment by AmarinReyny** [comment]
> If you want someone else's help debugging an installation of C:DDA that is customized to such a degree, you should ~upload the entire installation~ _upload them all and let god sort them out_.

So, after several hours of uploading, it turns out that most of the files in the folder for the world/save itself were "unreadable" by Google Drive. So... I don't know what to do about that.

**Comment by LeahLuong** [comment]
Have you tried compressing them prior to upload?? I backup my .sav as a .zip on Drive in case something bad happens. Even a large world should compress & upload in mins.

**Comment by AmarinReyny** [comment]
> Have you tried compressing them prior to upload?? I backup my .sav as a .zip on Drive in case something bad happens. Even a large world should compress & upload in mins.

Good idea. I'll try that tomorrow, if I get the chance to. I don't think I'll be able to stay awake long enough to do it tonight, though.

**Comment by AmarinReyny** [comment]
So, uh... here's this:

https://drive.google.com/file/d/1hBJvNbL2auWcZvqYfZDQUksnYP89i4IQ/view?usp=sharing

**Comment by PatrikLundell** [comment]
I believe I've stumbled upon the cause of this when testing some JSON cleanup and running into the same problem and then trying to fault find it: some recipes have exactly the same name in version2 of the canteen, and the weird way in which JSON is handled causes the order in which they're loaded to be essentially random, so sometimes one recipe "wins" and sometimes the other. There aren't any warnings for overloading recipes either.
I'll try to fix this as quickly as possible.
