### ISSUE TITLE
Wire draw machine does not accepts battery mods. 

### ISSUE THREAD

**Issue by buffog** [CleverRaven/Cataclysm-DDA#53068]
### Describe the bug

Wire draw machine does not accepts battery mods. 

Most likely caused by lack of 
    "ammo": [ "battery" ],
line 
in  /data/json/items/tool/workshop.json "wire_draw_machine"

### Steps to reproduce

1. Have a player with empty wire draw machine, any other empty electric tool as control and any battery mod. 
2. Activate battery mod to attempt attaching it. 
3. Observe lack of  wire draw machine in presented options to attach the mod. 

### Expected behavior

Expected wire draw machine to accept battery mods. 

### Versions and configuration

5ec5e24

**Comment by wapcaplet** [comment]
Confirmed. Also, I verified your suspicion, that adding `"ammo"; [ "battery" ]` to the item fixes the problem, and allows battery mods to work with it.


- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-4068-gfdeff510ae [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
