### ISSUE TITLE
Make adv. inventory behave like 2-pane file manager (while opening nested containers)

### ISSUE THREAD

**Issue by rumly111** [CleverRaven/Cataclysm-DDA#53085]
### Is your feature request related to a problem? Please describe.

We can put items into containers now, but it's still a bit troublesome. You need to select the container in the inventory, press `i` etc etc

### Solution you would like.

In the advanced inventory, you select the container, and press a `DIVE_INTO_CONTAINER` button, and the game shows items in that container. And you can put/remove items from inside a container. It's as if you entered into a directory in a file manager like MC or VC :-)

Also if there is a container inside a container etc, you can "dive" deeper.

**Comment by andrei8l** [comment]
The AIM is, sadly, on the chopping block - see https://github.com/CleverRaven/Cataclysm-DDA/issues/50015

**Comment by Je55eah** [comment]
Chopping block or not, this seems like a good idea.
