### ISSUE TITLE
Tamp ground -- should be in construction zone menu

### ISSUE THREAD

**Issue by FaNToMKH** [CleverRaven/Cataclysm-DDA#53088]
### Describe the bug

There is no way for NPC's to tamp ground using tools.

### Steps to reproduce

1.Create a "field mount of dirt" several tiles long.
2.Add a zone construction of "dry stone wall" over those tiles
3.Order NPC's to do construction work.

### Expected behavior

I expected NPC's to start constructing, but they don't.
"dry stone wall" needs "field dirt" and while NPC's are equipped with entrenching tool, they do not recognize the action of "tamp ground" to  convert "field mount of dirt" to "field dirt"

### Versions and configuration

OS : Windows 7 Professional, Service pack 1
Game Version : Experimental fdeff51 (tiles)
Graphics Version : tiles
Ingame Language : English
Mods Loaded: dda, no npc food, package bionic professions, dinomod, statsthroughskills, stats trough kills,

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.

**Comment by andrei8l** [comment]
This was fixed in #57466: add a construction zone with the "Fill Pit" blueprint, which has a variant for mounds of dirt
