### ISSUE TITLE
Need a way to practice health care skill to higher levels

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#53084]
### Is your feature request related to a problem? Please describe.

Manual bandaging is the only workable way to get past `health care` 4, but very tedious IRL.

### Solution you would like.

One or more practice actions fir advancing practical health care skill.

### Describe alternatives you have considered.

Some other way to train health care?
`%` -> apply a bandage 100 times

**Comment by l29ah** [comment]
I also tried copy-pasting, but it seems like my symbol(s) that should signalize the body part that the bandage is applied to is just ignored, probably must delay it for some reason.

**Comment by catdach** [comment]
Not trying to be harsh, but this seems like one of the most wild ideas to solve the current problem of training healthcare past level 4.

**Comment by Venera3** [comment]
See #53048 for some relevant concerns.

**Comment by wapcaplet** [comment]
Is there any other use case for applying 100 bandages, other than simply grinding the skill?

I would rather see more ways or practice recipes to improve first aid proficiency(ies), instead of having ways to save keystrokes just for the sake of skill grinding.

**Comment by Inglonias** [comment]
This seems like a perfect use case for practice recipes.

**Comment by Alex-Folts** [comment]
Could add some mummification activity, when you take any corpse and wrap it in bandages/towels/sheets etc, which will increase said skill... I mean if you going crazy do it with a style.

**Comment by l29ah** [comment]
The linked pull request doesn't provide a way to grind health care past 2 :/

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
