### ISSUE TITLE
Can infinite reload a gun or magazine

### ISSUE THREAD

**Issue by MikuMiddo** [CleverRaven/Cataclysm-DDA#53096]
### Describe the bug

You can reload a gun or magazine nomatter it's full or not,and this reload action will consume time and make the reload noise even when the item is full.Also show a message on the message bar.

### Steps to reproduce

1.get you self a shotgun and some shots.
2.Still (R)eload them after the magazine is full
3.Press R you can see them can be continuly reloaded

### Expected behavior

A full gun or magazine shouldn't be reloaded and also try to reload them won't consume time or make noise,just show a message at the bar "XXX is full!" like before.
they shouldn't show in R menu,It will hard to find the gun that need to be reloaded

### Screenshots

![image](https://user-images.githubusercontent.com/53809752/143802435-eedfc15b-e30b-4a4b-94e5-2a4e4061082e.png)
![image](https://user-images.githubusercontent.com/53809752/143802436-8261cc25-5830-4cdb-b67d-5344df724547.png)
![image](https://user-images.githubusercontent.com/53809752/143802446-bd76531e-cb38-487b-947a-4202afdae630.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0068ddf [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Drew4484** [comment]
I believe this behavior is allowed in case you want to reload with different ammunition types,  but unloading would still allow this.

**Comment by MikuMiddo** [comment]
> 
Other ammunition won't show here see
![image](https://user-images.githubusercontent.com/53809752/143812170-1797e24e-adf8-4ca5-b8fa-6962421a638d.png)
![image](https://user-images.githubusercontent.com/53809752/143812195-56f9c187-96f0-4998-a1c3-96dc6b29f8fb.png)
![image](https://user-images.githubusercontent.com/53809752/143812204-e59db8be-0a6c-49dd-bb79-813bc7bc01ab.png)
Concluding the time consumtion，It is just missing a full magazine check
