### ISSUE TITLE
Segmentation Fault On Load - Save Broken

### ISSUE THREAD

**Issue by InfiniteMonkeys94** [CleverRaven/Cataclysm-DDA#53090]
### Describe the bug

I have a game that I've been playing for a good 10 hours, and it's just started crashing with a segmentation fault whenever I try to load the save. I don't remember what I was doing before saving, but it was nothing unusual. If anyone knows how to fix the save, I'd appreciate it!
[Pandemonium.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7614505/Pandemonium.zip)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7614506/crash.log)

### Steps to reproduce

Try to load the attached save with this version:

build type: windows-tiles-x64
build number: 2021-11-27-1335
commit sha: fdeff510ae1cd6cc4cbb49e7de208b0119179950
commit url: https://github.com/CleverRaven/Cataclysm-DDA/commit/fdeff510ae1cd6cc4cbb49e7de208b0119179950

[Pandemonium.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7614505/Pandemonium.zip)

### Expected behavior

The save should load without crashing.

### Versions and configuration

Windows 10, English, built in mods only.
Version:

build type: windows-tiles-x64
build number: 2021-11-27-1335
commit sha: fdeff510ae1cd6cc4cbb49e7de208b0119179950
commit url: https://github.com/CleverRaven/Cataclysm-DDA/commit/fdeff510ae1cd6cc4cbb49e7de208b0119179950

**Comment by dseguin** [comment]
I tried loading the attached save using the latest master, and it looks like it works fine on my system:
![save_loaded](https://user-images.githubusercontent.com/12537966/143812719-0bb4a014-76fe-47ab-a398-d01a7f96ac01.png)

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.3 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-4074-g0068ddf27e [64-bit]
- Commit: 0068ddf27e5c5010e33e1bc7aec9319dadc33db5
- Graphics Version: Tiles
- Game Language: System language []

**Comment by PatrikLundell** [comment]
I tried loading the save on a Windows 10.1 local compilation of the master version less than a week old, and it was successful.

Given the experience of dseguin and myself, I'd suggest trying to reinstall the game using the latest version. I'd rename the current installation, install the latest one, and copy the save over. If it's successful, I'd then delete the old installation.

**Comment by BrettDong** [comment]
The attached save is loaded successfully without any error with Address Sanitizer and Undefined Behaviour Sanitizer enabled on macOS at d8a51aad1883a5e88e104204f87bc44c661e66cd.

**Comment by InfiniteMonkeys94** [comment]
I just tried to load the save again today on the same version, and it worked. I tried several times yesterday with no luck, so I'm not sure what happened, but the problem is fixed I guess. Maybe I just had to restart my PC? Thanks everyone!
