### ISSUE TITLE
Gum is technically a stimulant

### ISSUE THREAD

**Issue by Wolf401** [CleverRaven/Cataclysm-DDA#53107]
### Describe the bug

so using the candy mod i had an absurd amount of gum, normal gum and so after choosing to eat a bunch of it, which never filled my characters hunger, i thought that was the way to end the 30 gum spider corpses, after walking 3 steps i was prompted that i was to die, appearantly after reloading to see what happened, the gum was considered a stimulant and gave me a heart attack due to overdose, nothing was prompted to warn of this and while yes eating upwards of 1000 pieces of gum in a sitting is gonna kill anyone, its rather strange its effect is a stimulant which causes a heart attack in low enough doses

### Steps to reproduce

1. spawn in any character with the mod
2. kill any gum spider and butcher it preferably the basic one
3. consume copious amounts of gum and check the @ menu for the stimulant effect

### Expected behavior

i expected to get sick off it but for the gum to no longer be capable of rotting and turning into 1-3 more spiders, rather than having a heart attack

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Generic Guns [generic_guns],
    Crazy Cataclysm [crazy_cataclysm],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by catdach** [comment]
Gum contains sugar, which is a stimulant so no bug there. Well, I jut looked up how much sugar it takes to kill a human so if I wasn't on some watchlist for the FBI before I am now.

Lets look at the math of this. How much gum would you have to eat to die instantly? According to the USDA, a stick of gum contains 2g of sugar. From some google searches, a lethal dose of sugar is somewhere around 13.5g of sugar per pound of body weight. The average bodyweight in North America is somewhere around 170-ish pounds. 13.5*170 = 2295. 2295/2 = 1147.5. It would take about 1147.5 sticks of chewing gum to kill you, congratulations!

**Comment by estebandellasilva** [comment]
https://pubmed.ncbi.nlm.nih.gov/11382890/

Chewing gum is a stimulant not because of the sugar (which might help) but because of the chewing action. The lethal dose of sugar would also be wrong in that regard as most publications which talk about the lethal dose of sugar also mention that its nearly impossible to eat that much sugar without throwing up.

Similar Green/Black  Tea iss a stimulant in this game  but not because of the sugar.(i know that they have a similar substance like coffeine).

**Comment by kevingranade** [comment]
So you were playing a mod with weird animated candy creatures and decided to just start eating the hell out of their corpses.

Yea that might have some *ill effects*, maybe don't do that.
