### ISSUE TITLE
Setting a default firing mode breaks "moves to fire" calculation

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#53124]
### Describe the bug

If you set a default firing mode through f -> F, the "moves to fire" listed in the info box become too low. The mode you select (and all slower ones) is set to the same as "immediate", and the others seem to then be calculated based on that incorrect values. This seems to be a visual bug that does not affect the actual speed of firing.

### Steps to reproduce

1. Equip a gun
2. Press f->F and select a default firing mode

### Expected behavior

The "moves to fire" listing should still be accurate when you have a default firing mode.

### Screenshots

![image](https://user-images.githubusercontent.com/5107449/144067725-7b483a2e-2052-4e70-abe7-5d865f50d065.png)
Precise as default

![image](https://user-images.githubusercontent.com/5107449/144067693-9f08eca2-6570-479c-9133-161b28bfd2c3.png)
Regular as default

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: d8a51aa [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Extra Mutated Scenarios [extra_mut_scens]
]

### Additional context

Setting a default firing mode also disables the "immediate" mode that's normally the default, which is annoying.

**Comment by LeahLuong** [comment]
Let me get this straight: you are annoyed that changing the default firing mode changes the default firing mode??

**Comment by Terrorforge** [comment]
> Let me get this straight: you are annoyed that changing the default firing mode changes the default firing mode??

No. I'm annoyed that it makes all firing modes display their speed incorrectly.

If you're referring to my comment under additional context, the answer is still no. If you don't set a default, you have access to four firing modes: immediate, regular, careful and precise. But if you set the default firing mode to anything other than "immediate", you can't access "immediate" at all. That's what annoys me, because I do want to use it sometimes, but as it currently stands I have to go in and change my default to do that.

**Comment by LeahLuong** [comment]
Sorry, it looks like I misunderstood you when you said:

> Setting a default firing mode also disables the "immediate" mode that's normally the default, which is annoying.

On 2nd glance, did I?? What exactly do you mean when you say "default firing mode"?? Also, there's that other time where you said, "change my default." Were you pointing to "firing mode" w/ that statement or some other default. I apologize if I'm splittung hairs here but I'm really curious about your use of language here as it pertains to the game's fairly clear functionality on this point.

**Comment by Terrorforge** [comment]
I get like that too, sometimes. Let me try to explain:

The game has four firing mode; immediate, regular, careful and precise. When you start a new character, the default firing mode is set to "immediate", which is what I meant by "normally the default". So if you press f and then f again, you'll use "immediate". But you can also press f and then a, c or p for regular, careful or precise.

If you press f and then shift-F or s, you can manually set your default firing mode to any of the other three, which is what I meant by "setting a default firing mode" and "changing your default". This means that pressing f and then f again will do regular/careful/precise instead of immediate. Very handy if like me you mostly do precise shots. You can still press a, c or p to do one of the others as before, but there is no hotkey to use the immediate mode. So if you want to use it, you have to press shift-F again and change your default firing mode back to immediate.

(also they're not called firing modes, they're called aiming modes, but at this point it would probably be more confusing to switch terminology)

**Comment by LeahLuong** [comment]
Oooooh, I get it now! When you said:

> But if you set the default firing mode to anything other than "immediate", you can't access "immediate" at all.

You didn't actually mean "at all". Simply that you found it hasslesome to have to revert the default firing mode to its primary setting. Not that you were being locked out of changing your default firing mode after changing it or something else entirely which you may or may not have communicated.

Thanks for clearing that up for me!

I mostly use precise shots too. Isn't it great how doing that requires only 1 keystroke regardless of whether your default primary mode is shifted from its primary setting or not??
