### ISSUE TITLE
Let liquid soap be used to clean clothes

### ISSUE THREAD

**Issue by dnworden** [CleverRaven/Cataclysm-DDA#53125]
### Is your feature request related to a problem? Please describe.

I find it a bit unusual that regular soap can clean clothing when cut into flakes, but liquid soap doesn't seem to be able to be used for anything. I believe that liquid soap should be able to clean clothing too, but probably being a lot worse at it than regular soap since it's shampoo or conditioner rather than all-purpose soap.

### Solution you would like.

I can probably make a change to the code to let liquid soap be used as detergent by giving it the DETERGENT flag, but I am putting a request here because I would like to know what would be a reasonable ratio of soap to liquid soap for cleaning. I was thinking that since both soap flakes and detergent have a count of 20 that I could give liquid soap a count of 5 in addition to the detergent flag to make a box of detergent equivalent to 4 bottles of liquid soap. If the ratio should be something else like 2 or 5, I would appreciate the suggestion.

### Describe alternatives you have considered.

Adding liquid soap to the recipe for soapy water as an alternative to regular soap since I feel that makes sense.

### Additional context

I can write the code myself as soon as I get results on my other PR #52965, which I mistakenly am merging from my fork instead of just a branch. I'd rather not disrupt that at the moment, but after that I can create the code for this one. The main advice I need is how many units of liquid soap should equal one unit of detergent?

**Comment by Inglonias** [comment]
The ratio can be easily altered by changing what volume of soap actually counts as one charge.

**Comment by dnworden** [comment]
@Inglonias yup, I know how to change the ratio, I just was wondering if 1:4 was a good ratio of detergent to liquid soap was fair.

**Comment by pjf** [comment]
With #53161 merged, is this issue now resolved?

**Comment by Night-Pryanik** [comment]
Closed after #53161.
