### ISSUE TITLE
Linux Tiles 0.F-3 Release missing

### ISSUE THREAD

**Issue by sappergr** [CleverRaven/Cataclysm-DDA#53122]
### Describe the bug

The Linux 0.F-3 release Tiles download is missing. Is that intended or an omission? 

### Steps to reproduce

It's not on the releases page

### Expected behavior

It should be available

### Screenshots

![Screenshot_2021-11-30_14-33-01](https://user-images.githubusercontent.com/82756438/144048686-47559bc3-3761-40b4-9052-72c3c96bd0c1.png)

### Versions and configuration

Irrelevant

**Comment by BrettDong** [comment]
We are having some technical issues in building Linux Tiles version.
