### ISSUE TITLE
Stun Gun uses over 4000x too much energy

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#53127]
### Is your feature request related to a problem? Please describe.

I emailed the SABRE personal defense company about the specs of their stun gun, specifically [this extremely powerful one](https://www.sabrered.com/pepper-spray/sabre-multi-range-protection-pack-police-strength-25-burst-pepper-spray-plus-0704). I got some battery and capacity specs from the representative.

> I’ve pulled the information for that particular model and the battery specs are as follows: 3.7 Volts, 210mAh. The battery in this model is comprised of 3 lithium cells so those specs would be per cell.

Using the formula J = V * mAh * 3.6 I get a total capacity of about 8,391.6 J.

> So on these models the power output of the “zap” is measured in microcoulombs and cant be converted and quantified into watts, volts, etc. I can assure you, however, that the output is A LOT. The particular model you’re interested in delivers 2.5 times the needed output to cause unbearable pain. Per my lab manager, you can fire it a few hundred times at 1 second intervals on a full battery. We do recommend the initial charge to be for 12 hours followed by weekly charges lasting 4-5 hours just to make sure your battery stays fully charged.

"A few hundred" is somewhat vague but gives a pretty good idea at least. If we take "a few hundred" to mean a little over 300 that gives a total of about 25j per 1-second "zap" - our in game stun gun physically cannot be firing for more than a second at a time due to turnspeed. 

So since our stun gun uses 100kJ to fire it takes 100,000/25 = 4,000x as much energy as a real-world, extremely-overkill-powerful model. 

### Solution you would like.

We physically cannot make the stun gun accurate under current battery systems. The closest we could come would be 1kJ. Still, 1kJ is only 40x too much energy instead of 4000x, that's two orders of magnitude closer!

This really points to a broader issue with batteries in CDDA. Batteries should probably use a finer scale like bionic power, and power usage is wildly wrong in many places (boiling water is one of the biggest examples). But that's (somewhat) outside of my issue.

### Describe alternatives you have considered.

Cataclysm stun guns don't necessarily need to be the same strength as real life stun guns. It's not unreasonable for security and police forces to deploy a massively-overkill stun gun to be used against "rioters" especially given pain-compliance doesn't work against zombies. So 1-3kJ may actually be somewhat reasonable in the messed up world Cata had become, especially the setting's batteries are so absurdly powerful by comparison. (Also, 1-3kJ is still about "a few hundred uses" off a 500kJ battery so the ratio stays the same!) 

### Additional context

Continuation of issue #52911 with hopefully a higher standard of evidence. I'm making this an issue before I make a PR because I want input on how to proceed.

**Comment by Inglonias** [comment]
I say create a PR for this. If it's accepted, great, but I think this qualifies as enough information to work with.

**Comment by anoobindisguise** [comment]
Will do then, I just wanted to make sure that this wasn't a "yes, but we need more infrastructure to make this change" situation.

**Comment by nullinsky** [comment]
I'm a bit more concerned about balance since with plentiful charges and common ammunition, Stun guns could trivialize most melee threats throughout the game. Maybe specialized, rare, or hard-to-charge batteries?

Zap mechanics could really be looked at since large or tank-sized creatures should shrug them off due to the body mass. But currently, you could just permastun nearly everything to death over a fire. Though this is another issue altogether.

**Comment by Broken27** [comment]
>I'm a bit more concerned about balance since with plentiful charges and common ammunition, Stun guns could trivialize most melee threats throughout the game. Maybe specialized, rare, or hard-to-charge batteries?

The devs said very clearly than they don't care about game balance issues.

**Comment by anoobindisguise** [comment]
My understanding is that it's just a fundamental or how electricity interacts with our muscles - it takes very little charge to get them to expand, contract, or lock up entirely, and therefore even a tiny charge on a stun gun (25j) does that. But against humans the main goal is pain, paralysis-like symptoms take 3-5 seconds to set in. That's a normal stun gun however. If we assume that there's some super-powerful, highly unethical version (1kJ charge) it would have significantly higher effects, such as burns and spasms. The kind of damage a stun gun delivers in Cata is fairly in line with that I think (albeit energy cost is way too high as is) 
10 mA to the heart can kill you. It takes a really surprisingly low amount of electricity to cause damage to the human body. The main issue with stunning, say, a bear, is that the bear has tons of fur and thick skin which insulates it. Big zombies would likely be a similar case.

**Comment by Inglonias** [comment]
I agree. The effects of hitting various things with a stun gun are a natural follow-up task, but this is a separate issue.

**Comment by anothersimulacrum** [comment]
Is this still relevant after https://github.com/CleverRaven/Cataclysm-DDA/pull/53353?
