### ISSUE TITLE
Magus Battle Staff Requires a Nonexistent Tool

### ISSUE THREAD

**Issue by CrowbarZef** [CleverRaven/Cataclysm-DDA#53123]
### Describe the bug

Magiclysm's magus battle staff requires a tool with cutting 2 which does not exist.

### Steps to reproduce

1. Enter game
2. Look at recipe
3. Sadness

### Expected behavior

Being able to craft the Staff

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: fa91686 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    No Fungal Monsters [No_Fungi]
]

**Comment by wapcaplet** [comment]
This has come up in the dev discord a couple times. The "extended toolset" CBM has cutting level 2, and the Magiclysm "artificer's toolkit" has cutting level 5, whatever what means, so it might be intentional for this recipe to require cutting level 2 (though I could very much be wrong).

https://discord.com/channels/598523535169945603/642349261320880128/913132871223496715
https://discord.com/channels/598523535169945603/598523535169945607/878880968574926889

**Comment by Terrorforge** [comment]
> This has come up in the dev discord a couple times. The "extended toolset" CBM has cutting level 2, and the Magiclysm ["artificer's toolkit"](http://cdda-trunk.chezzo.com/artificer_toolkit) has cutting level 5, whatever what means, so it might be intentional for this recipe to require cutting level 2 (though I could very much be wrong).

It is not. The artificer's toolkit is a special perk of the Artificer attunement, a late-game prestige class. It should not be required to craft the magical standard magical weapon of an unrelated class.

**Comment by wapcaplet** [comment]
For reference, #48187 added the item and its recipe.

I agree it’s probably a bug, since no other tools have cutting level 2 except those two exceptions. Even the monomolecular blade only has cutting level 1, so any level higher than that seems nonsensical to me.

**Comment by GoLoT** [comment]
Also the extended toolset is being reworked in #52889 and the cutting 2 quality is most likely going to be removed from it if/when that PR is merged. We can scratch it from the list of available tools.

**Comment by Sofistico** [comment]
Sorry everyone, i was the one who wrote the weapon, it was an oversight by my part
