### ISSUE TITLE
Reload Tileset action crash

### ISSUE THREAD

**Issue by nheve** [CleverRaven/Cataclysm-DDA#53138]
### Describe the bug

Using "Reload Tileset" action through the debug menu (or through previously set hotkey) causes the game to crash immediately. Problem exists only in the experimental version, and isnt present in the current stable version.

Tileset type choice doesnt seem to matter as well, similar with turning on/off the use of tiles for overmap.
Problem isnt also related to the specific world/save file - neither to the specific type of character playing on the world.

### Steps to reproduce

1. Load into the world with your character, using latest experimental version of the game and with any kind of tileset.
2. Run "Reload Tileset" action - through debug menu, or by using previously set hotkey.

### Expected behavior

I would like to be able to use 'Reload Tileset' action in the experimental version, the same way like in stable version - to test any kind of changes previously made to the tileset in the graphics software, without need to reload the whole game repeatedly.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 661b2fd [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[logs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7635997/logs.zip)
[Test World1.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7635998/Test.World1.zip)

**Comment by ZhilkinSerg** [comment]
![изображение](https://user-images.githubusercontent.com/16213433/144290122-8a140a53-ec69-4b7e-b839-56b80d348932.png)
