### ISSUE TITLE
PE070 "Raptor": Proposal cannot be studied to raise your applied science skill

### ISSUE THREAD

**Issue by Scorch-Mechanic** [CleverRaven/Cataclysm-DDA#53146]
### Describe the bug

The skill book says it can raise your applied science skill to 8, but it also requires applied science skill 8 to understand it. Therefore, it cannot be used for this.

### Steps to reproduce

1. Create character with applied science skill of 7 or less. Give them the skill book.
2. See that they cannot read it. 

### Expected behavior

It should be possible for a book that says it can raise your theoretical skill to actually do that.

### Screenshots

![image](https://user-images.githubusercontent.com/5760760/144308196-e33439e3-db12-4245-a3b1-b108e5ae6795.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 661b2fd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

**Comment by PatrikLundell** [comment]
This is sort of intended, as it's a work around in the current crafting system to allow a book to provide recipes without training a skill. Unfortunately, the skill training is currently required for the system to recognize the recipes, so the work around is to require a level that's the same as the one it trains you to.

This issue isn't the first of this kind, and won't be the last one until the system decouples recipes from skill training.

**Comment by wapcaplet** [comment]
With #52964 merged (which correctly distinguishes recipe books as not "Just for fun"), this workaround should no longer be needed.

I tested by removing all three of these fields from the `recipe_raptor` book:

```
"skill": "chemistry",
"required_level": 8,
"max_level": 8,
```

The book still displays its recipes correctly:

![image](https://user-images.githubusercontent.com/238395/144541172-ffd6007d-373b-4f14-a77b-e310642b9824.png)

The "It can be understood by beginners" part seems a little off in this case, but the skill requirements of the recipes themselves have nothing to do with the book's skill level. The recipes are available in my crafting menu once I've met the minimum requirements to understand them.

So it seems like we could remove this workaround from those books now.

**Comment by Max17U** [comment]
> With #52964 merged (which correctly distinguishes recipe books as not "Just for fun"), this workaround should no longer be needed.
> 
> I tested by removing all three of these fields from the `recipe_raptor` book:
> 
> ```
> "skill": "chemistry",
> "required_level": 8,
> "max_level": 8,
> ```
> 
> The book still displays its recipes correctly:
> 
> ![image](https://user-images.githubusercontent.com/238395/144541172-ffd6007d-373b-4f14-a77b-e310642b9824.png)
> 
> The "It can be understood by beginners" part seems a little off in this case, but the skill requirements of the recipes themselves have nothing to do with the book's skill level. The recipes are available in my crafting menu once I've met the minimum requirements to understand them.
> 
> So it seems like we could remove this workaround from those books now. These are all the ones I could find:

So removing these 3 fields, the recipes will still be able to be understood/craft when you'll have the level 8 ( or the relative required level) ? If so, how can someone understand what will be the required level to understand/craft these recipes?

**Comment by PatrikLundell** [comment]
I don't think this differs from other recipes in books. Books on cooking can contain a lot of different recipes with differing skill requirements, for instance, and I believe these recipes can be both below, at, and above the level to which these books train you.
To get the requirements for individual recipes you'd have to go to the crafting system menu.

**Comment by Max17U** [comment]
True, but at least you know the name and the minimum skill needed for some of those recipes. In this case someone (like me to be honest) wouldn't even know where to begin with, unless reading it from a "wiki". Personally i'd remove only the "max_level" field (if possible) and  keep the rest.

**Comment by PatrikLundell** [comment]
I agree it would be better if you could state a minimum level to understand the book as some kind of guide. However, changing the JSON descriptions (i.e. remove the lines indicated) can be done by anyone with a minimum of JSON structures skill (not implying people without that are stupid), while allowing you to state a minimum without a maximum would require a change of the code (which may or may not be easy once the code has been located [and you're able to handle High Level Assembly language, a.k.a. C++]).

**Comment by wapcaplet** [comment]
> So removing these 3 fields, the recipes will still be able to be understood/craft when you'll have the level 8 ( or the relative required level) ? If so, how can someone understand what will be the required level to understand/craft these recipes? (At least in your screenshot there's nothing saying what kind of skill, or what level, is needed to learn the recipes)

Yes, they should be. Recipe skill requirements are completely separate from book skill requirements.

**Comment by Max17U** [comment]
> > So removing these 3 fields, the recipes will still be able to be understood/craft when you'll have the level 8 ( or the relative required level) ?
> 
> Yes, they should be. Recipe skill requirements are completely separate from book skill requirements.



> I agree it would be better if you could state a minimum level to understand the book as some kind of guide. However, changing the JSON descriptions (i.e. remove the lines indicated) can be done by anyone with a minimum of JSON structures skill (not implying people without that are stupid), while allowing you to state a minimum without a maximum would require a change of the code (which may or may not be easy once the code has been located [and you're able to handle High Level Assembly language, a.k.a. C++]).

Something like this would be ok?
![Immagine 2021-12-10 170443](https://user-images.githubusercontent.com/74881393/145604461-2f479e46-3eda-4f8a-8f7e-4e3eb1a12be9.jpg)

**Comment by PatrikLundell** [comment]
That's what I envisioned, yes (but without the mixture of English and Italian, and without the overlay of the text for the recipes at the bottom...).

**Comment by Max17U** [comment]
Omg hahah didn't see that! Yeah, Italian wasn't supposed to be there, my system default language is Italian so it mixed everything up
