### ISSUE TITLE
Add Integrated Multi-Tool CBM

### ISSUE THREAD

**Issue by Photoloss** [CleverRaven/Cataclysm-DDA#53153]
### Is your feature request related to a problem? Please describe.

With #52889 the former "Integrated Toolset CBM" has been slimmed down to a specialised welding and soldering tool. This eliminated the realism concern regarding fully functional power tools, hammer and crowbar hidden away in your forearm, but left a niche for a more "low-power" convenience tool option. Theoretically the power tools could also be brought back separately, with a cost and bulk worthy of their nature.

### Solution you would like.

The key idea is that where the welder provides two very important advanced tool features this new CBM would be more of a convenience feature, providing all the rarely used niche tool qualities which reasonably fit into such a package. As a result a single multi-tool CBM might not provide the absolute highest level of each tool quality, but enough to get most odd jobs done without having to carry around a dozen tools with names no one bothers to remember. The following tool qualities seem feasible to square away in the fingers or forearms:

- "Forearm Tool Blade", essentially the tool version of the Monomolecular Blade CBM: Cutting 1, Butchering (comparable to a pocket knife), Prying 1, Filing 1 (in the flat of the blade), Fine Cutting 1 (X-acto tip on the blade), *maybe* Wood Sawing 1 and Metal Sawing 1 via serrations on the second edge of the blade, one of the survival knives has those.
- A "needle dispenser", essentially a hollow tube embedded in the forearm next to the blade(s): Sewing 1, Knitting 1, Awl 1, Lockpicking 1 and maybe Curved Needle 1 all take up very little volume, and could potentially be performed with the same needle(s).
- Screwdriving 1 and Fine Screw Driving 1: essentially a metal fingernail replacement, or swappable bits in a fingertip replacement. The existing "Swiss Army Knife" multi-tool also has Bolt Turning 1, not sure whether that implies tips/bits or pliers. If the former Fine Bolt Turning 1 is on the table as well.
- Proper scissors and pliers are quite difficult to fit. Something like [this](https://images-na.ssl-images-amazon.com/images/I/517bCdmgOUL.jpg) would fit into a permanently outstretched finger but they really aren't very useful for most things an in-game survivor would want to do with a pair of pliers or scissors.
- I am not entirely sure what the Smoothing quality represents, but a machete-like blade or said blade with a folding panel to double its width might qualify.

Basically if I missed any other tools or some get added in the future which can be performed by an inert piece of metal or plastic no more than 1 cm in diameter and ~10-15 cm long those should be safe for inclusion as well. I deliberately omitted the scalpel as that might require sterility and special care for certain uses, the same goes for most lab equipment. Tools requiring processors or a user interface are not included in this proposal either, although the weather readers, watch etc. could potentially be combined into a "Digital Multi-Analyser CBM" in a similar vein.

There are potential solutions for bulkier tools as well: a telescoping tube with detachable heads could hold a hammer, wrench and crowbar attachment, and the hammer head could also serve as a knapping punch. Unlike commercial hand tools the handle tube would be made out of superalloy or comparable materials to maintain the necessary structural strength. The tube could also hold the needles mentioned above. This CBM would occupy most of a forearm or a decent volume in a leg.

A full-size wood saw or hacksaw would each occupy most of a forearm so those are unlikely to make a return. With the hammer, crowbar and full-size wrench also outsourced this firmly establishes the main "Integrated Multi-Tool CBM" proposal as a quality-of-life convenience item rather than a primary tool, distancing it from both the welder and the old Integrated Toolset version.

### Describe alternatives you have considered.

The various physical components required to implement the full multi-tool capability could also be split into a series of individually less versatile but more thematically appropriate CBMs, which would also place them more in the realm of something "our" Earth's rich technology enthusiasts and budding transhumanists might have been able to pull off using what's basically real-world present day implant technology. A tailor's kit with a thick ring to wrap thread around, the "tool blade" for (pre-zombie) survival enthusiasts, maybe even a "wrench hand" for the gig mechanic who's lost a few fingers too many to OSHA violations.

From a realism standpoint we can definitely build pretty much everything described above and also implant it into *certain* people. We have titanium hip replacements, stents and prosthetic limbs! The main issue is the interface between living skin and exposed implant which can tear and infect easily and thus is avoided by modern medical designs where possible. However permanent catheters, external insulin pumps and similar devices exist so we are learning to deal with small openings.

If all CBMs *must* shift to the Exodii, since their motivation for providing such tools was questioned before: they would provide these because they are able to, specifically as a trade good/service for allies and new recruits who haven't "earned"/cannot already be provided with a full cyborg shell. It is in their best interest to provide the scavengers working with/for them with the best tools to remain alive and functional, and being exclusive exotic technology would also justify a much higher price for these items compared to the handheld tools they can obviously produce instead. I am not too familiar with Exodii lore but the use of such basic CBM tools could also be written as a rite of passage for new recruits or a similar social function rather than a purely practical one.

### Additional context

I mentioned power tools might be brought back, and here is what I had in mind: a full arm replacement like the old arm blaster. Think [Bioshock Big Daddy](https://images.cgames.de/images/gamestar/4/bioshock-der-big-daddy_6145943.jpg) only more functional. A multi-purpose auger with Drilling, Grinding and pickaxe/jackhammer functions, circular sawblade attachments for high-level Wood and Metal Sawing, a hammer plate, prying hook and inlay bits squared away behind the business end to provide Bolt Turning and Wheel Fastening functions as well as high-level Screwdriving and anything else you might want to solve with high RPM high torque action. All the above "lesser" tools would also fit onto the sides of the metal frame, possibly even the welder essentially making this an upscaled version of the old Integrated Toolset CBM with a high cost attached. Don't forget to include some kind of skeletal bracing so this big boy can truly pierce the heavens instead of tearing itself out of your shoulder!

**Comment by anoobindisguise** [comment]
I think the most important thing to keep in mind is that the Exodii are only going to keep what is practical and useful. A CBM that turns your finger into a sewing needle or pocket knife is nice but it's of questionable utility given how easy it is to find the real thing and competes for valuable space that could be used for something else, plus might also be more hassle than it's worth - it's a lot easier to grab a new pair of scissors when yours goes dull than it is to surgically swap them. Though the Exodii are inheriting numerous "consumer-grade" CBMs like the flashlight or firestarter we probably want to avoid it in the future, if possible.

Another important consideration is that fully mechanical bodies and the new limb system may mean that modular body part CBMs like the blaster are no longer such a bad idea. Not for a fleshy human but there's a lot of room for innovation once we introduce the Exodii body replacements.

**Comment by catdach** [comment]
>  A CBM that turns your finger into a sewing needle or pocket knife is nice but it's of questionable utility given how easy it is to find the real thing and competes for valuable space that could be used for something else

Seems like the same could be said for just about any CBM with the utility of an item: soldering iron, arc welder, shotgun, fire starter, knife, file set, lockpick, intravenous needle, etc. "easy to find" can also be a matter of perspective, what seems common to us might not be common to the Exodii. How are they to know what is easy to find on our "brown and green"(for lack of a better term)?

> questionable utility...competes for valuable space

Wait, what? I must be misunderstanding what you mean by utility, because to me a multi tool is perhaps the item with the **most** utility in the **smallest** amount of space possible, seemingly by [definition](https://en.wikipedia.org/wiki/Multi-tool). Also in the case of the multi-tool in this request, we're talking about a single blade, one small sheet of metal, is that really going to take up a lot of space? Even if it extends, I doubt it would take up more space than the equivalent of an ankle sheath on the back of your hand (we don't have to be Wolverine level of extendable blades to be practical). Heck, the multi-tool in game is [0.07 L volume](https://cdda-trunk.chezzo.com/multitool), how much space do we need?

> it's a lot easier to grab a new pair of scissors when yours goes dull than it is to surgically swap them

I think the idea is to sharpen it when it gets dull, not try to replace it. Unless you outright snap the tool somehow, I guess that could be a problem but even then I feel like swaping out a single blade is much less serious than a "surgical replacement" would make it sound. I could be as easy as changing a lightbulb.

**Comment by anoobindisguise** [comment]
All good points. I just figure that it's more about the fact that you could just carry about a multitool rather than get one installed. Super tiny tool, the Exodii can definitely make it work. But they might not find it essential enough to perform a surgery.

**Comment by catdach** [comment]
I guess that's a fair point but from my perspective it's like; if they commonly perform surgery for tools anyways, why would it cause trouble for them to add it? If it's small then that makes it an easy surgery right? Like it just seems like the most practical effort to utility ratio possible, so what's the problem?

**Comment by anoobindisguise** [comment]
Effort to use a screwdriver <<<< effort to hook a screwdriver up to your body. My thinking at least. It's not my PR though, and you are not beholden to my suggestions.

**Comment by Photoloss** [comment]
> I think the most important thing to keep in mind is that the Exodii are only going to keep what is practical and useful.

I already addressed this. The Exodii themselves would not use this and instead have full-size tool arms. But such a small tool is trivial to produce and not particularly difficult to install so they would offer it as an entry-level service. *Some* survivors would definitely take that offer which means they can recoup the cost in trade goods, and that bottom line is what matters in the end.

**Comment by I-am-Erk** [comment]
This is a little bit tangential to your post, but what I would like to see for the integrated toolset - and it could be done similarly for this - is a change to a modular design. You get a "utility arm attachment" CBM, and then you can swap in various tools, fairly quickly (and automatically during a craft or something). However, you have to obtain the individual tool attachments and, for the full effect, may even have to carry around a toolbox with them. You can get multiple attachments, so you might have a welder on your right arm a rotary saw on the left, and two skeletal robot arms with a drill and pneumatic hammer jutting from your back.  However you wouldn't be able to turn your left arm into a drill, rotary saw, welding rig, and pneumatic hammer all at once. 

AFAIK the code framework for a plug-and-play CBM like that actually already exists, though that's just hearsay. If it does, I'd love to see it implemented, and something like this would make sense as a single attachment.

Anyway, in the shortest term, as long as the utility of this was equivalent to a swiss army knife, I see no problem with it at all. Having needles and screwdrivers that pop out of your fingertips is a bionics mainstay.

**Comment by Photoloss** [comment]
> a modular design. You get a "utility arm attachment" CBM, and then you can swap in various tools, fairly quickly (and automatically during a craft or something). However, you have to obtain the individual tool attachments

That sounds pretty close to my drill arm suggestion, except I allowed the convenience of using all attachments "in the same recipe" without distinguishing whether that would in fact mean "at the same time". For example you would saw, then weld, then grind/file, then drill, then bolt scrap metal plates to build a frame or box, compared to the total recipe time swapping tool heads is insignificant. Honestly most uses of the main tools are sequential rather than simultaneous, but you would not be able to use a single arm as both metal tongs and the forging hammer for example despite clearly being suitable for either purpose (and possibly also as an anvil).

I think where your "modular utility arm" idea really matters is weapons. If you're caught with a (narrow) drill on one arm and an angle grinder on the other you are basically unable to wield regular weapons and also have no bionic equivalent ready. However if you keep the auger or saw on one arm you can probably tear several regular zombies to pieces with no effort. Same with auxiliary arms holding a lockpick and a flashlight versus a machete and a laser pistol. Having to lug around a separate hammer head and welding tip just makes it a clunky annoyance with no real benefit over hand tools, blocking weapons *in the moment* presents an engaging gameplay scenario.

**Comment by GoLoT** [comment]
Honestly, I feel this is not a problem with the toolset CBM itself (you can justify pretty much anything in the current setting) but with the lack of a limit when installing CBMs. I think I might start working on properly implementing slots (there are good suggestions out there to make it work, I'll go through those and see what I can come up with) with soft caps and hard caps instead of simply adding a hard cap.

What I think the toolset CBM needs is to be split into multiple different tool CBMs. This will allow players more control on what tools they install and when a proper limit is set, they will have to choose if they want convenience (having some "magic tools" always on them) or room for other (better) CBMs. They will have to choose which tools they will want installed as implants.

I think that's the best compromise so I suggest splitting the CBM into multiple sets of tools, as this will keep people happy while also making it harder to find and install a complete set of tools (You'd have to find all the different CBMs and install them). And then we can control how hard it is to install each of them so we can gate some of them.

**Comment by I-am-Erk** [comment]
It does need to be split, but I don't like requiring a different operations to install a different tool each time. It's not a very practical solution. If you were making a tool arm, you'd just make a mount, and you'd attach the tool you need when you need it.

**Comment by GoLoT** [comment]
If I understand it right, you'd only have one weapon installed at a time. I added support to persist weapons from CBMs to the save file so if we stick to a single tool it can be implemented easily. All we need is a way to assign the specific item (tool) to the CBM fake_weapon member and make sure it inherits the USES_BIONIC_POWER flag. The easiest way I can think of is to add a whitelist/blacklist of item flags to the CBM to control which items can be assigned as fake_weapon. It requires changes in code though.

Then it's a matter of flagging tools that can be installed or maybe creating new tools that only work with the CBM, that are hard to craft/find, and sold by the Exodii. Adding the allow_dupes flag to the CBM would allow multiple tools to be installed, one per CBM, if needed. But maybe it would be better to have a single CBM and create multiple tiers of the attachable tool with different qualities.
