### ISSUE TITLE
modifying worn clothes with tailor's kit doesn't change their encumbrance effects until taking them off and on again

### ISSUE THREAD

**Issue by Slumbrero** [CleverRaven/Cataclysm-DDA#53164]
### Describe the bug

Padded a survivor firehood with kevlar while wearing it. Prior the @-window showed a value of 0.85 to dodge and block rolls due to head encumberance. After padding, which added encumberance to the clothing, it still showed 0.85. Taking the hood off and on again now showed a value of 0.82 on dodge and block rolls.

### Steps to reproduce

1. wear a clothing
2. check @-window for encumberance effect value on according bodypart
3. modify the clothing with a tailor's kit and a modification that adds encumbrance while still wearing it
4. repeat step 2
5. take off said clothing, put it on again
6. repeat step 2

### Expected behavior

While it is possible to modify clothing while wearing it, according changes on encumberance effects should take place immediately after modifying it.

### Versions and configuration

build type: windows-tiles-x64
build number: 2021-12-01-1115

### Additional context

Modifying the warmth of clothing _probably_ won't change the effects of it immediatly either. A simple fix might be the need to take off the clothing in order to modify it or to automatically take it off when modifying it.

**Comment by Slumbrero** [comment]
edit: I did some further investigation - the according encumbrance value itself for the specific bodypart shown in the @-tab doesn't change until the clothing is taken off and on again, the warmth value however changes immediately after modifying.

**Comment by wapcaplet** [comment]
Confirmed. Similar behavior occurs when making a "(poor fit)" item fit properly, thus decreasing its encumbrance.

- Spawn a `|| survivor firehood (poor fit)`, encumbrance 30
- Wear it - both `+` and `@` screens show encumbrance 30 on the head
- Use a sewing kit or tailoring kit to improve the fit

Afterward, the armor layering menu `+` shows the correct encumbrance of 20:

![image](https://user-images.githubusercontent.com/238395/144509133-88c2bb1d-7f8c-4529-970f-7bddc56024d8.png)

But the `@` character menu still shows 30 head encumbrance:

![image](https://user-images.githubusercontent.com/238395/144509066-6054f301-f0b7-4269-8a9d-17d655724f09.png)

This does not refresh until I take it off and put it back on.

Modifying the fitted survivor firehood to pad with Kevlar will increase its encumbrance from 20 to 30:

![image](https://user-images.githubusercontent.com/238395/144509717-cada0129-ffd4-4143-a44f-e2a86cd0daae.png)

The armor layering menu `+` correctly reflects the new encumbrance of 30:

![image](https://user-images.githubusercontent.com/238395/144509807-13def741-e8d8-4aac-bef2-3dc3a0dd9f81.png)

But the `@` screen still shows 20:

![image](https://user-images.githubusercontent.com/238395/144509774-e65a9e56-1f8d-4063-a41b-4ddd31f410ae.png)


- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-4108-gfa916867f5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by ElfLeaderMike** [comment]
Confirmed this is still an issue in the latest experimental.

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 1bba9b7 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock]
]
