### ISSUE TITLE
Add option to turn off "green" from night vision

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#53167]
### Is your feature request related to a problem? Please describe.

So, as an autistic person, bright, garish colors are a problem for me. Upon having my character cast one of the spells from Arcana that temporarily grants night vision, my laptop's screen became covered in a very intense, very painful green color - the pain and nausea caused by me looking at the screen for more than a few seconds at a time was bad enough that I had to make several trips to the bathroom in order to vomit.

### Solution you would like.

I would like to have an option to disable the "green" effect of night vision so I can have my character use it without causing highly disruptive health problems for me IRL.

### Describe alternatives you have considered.

1. Never using night vision at all
2. Removing night vision from the spell via JSON editing so my character can use it, making it less effective in-game in exchange for my health (already done for now)

**Comment by Inglonias** [comment]
As a temporary workaround in the meantime, I suggest installing [F.lux](https://justgetflux.com/). One of its functions is to switch your screen to greyscale, which may help avoid future issues.

What you are asking for here also seems reasonable to me. If at all possible, I would rather that this game not cause real world harm to people.

**Comment by Hirmuolio** [comment]
The map memory can be set to custom RGB in settings. It would probably be best to make the night vision use similar system.

**Comment by PatrikLundell** [comment]
You might try to adjust the brightness and/or color saturation of your monitor while wearing those goggles as an intermediate solution (definitely tedious to change that back and forth in any longer perspective, though).
