### ISSUE TITLE
Negative trait idea (dementia/brain trauma)

### ISSUE THREAD

**Issue by Totaspy** [CleverRaven/Cataclysm-DDA#53181]
### Is your feature request related to a problem? Please describe.

I hate skill rust on certain skills, and rarely use it. But one exception I thought of might be fun for others if not myself.

### Solution you would like.

What about a negative trait called “dementia” or “brain trauma”. Randomly, one of your skills gets dropped by half, or completely reset. You have to occasionally take some kind of medication or neurostimulants to decrease the chances of this happening.

**Comment by SariusSkelrets** [comment]
It is temporary or permanent?

 It will feel impactful as a mood swing or screw you like narcolepsy depending of which skill is targeted 

 but it will feel like a skill-version of genetic downward spiral (forever locking you out of a system) if the reduction is permanent

**Comment by Totaspy** [comment]
> It is temporary or permanent?
> 
> It will feel impactful as a mood swing or screw you like narcolepsy depending of which skill is targeted
> 
> but it will feel like a skill-version of genetic downward spiral (forever locking you out of a system) if the reduction is permanent

Maybe permanent. Hell, the problem is I get a little too OP too quickly. I thought something that could potentially set you back, and undo a portion of your growth/exploration would be beneficial. 

Maybe it could also have a random chance to delete an “explored” portion of your map?

And I understand it might be incredibly detrimental. Which is why I suggested medication to mitigate the affects. People with Alzheimer’s or severe head trauma tend to take “cognition-enhancing medication” to treat the conditions. Perhaps the longer you go without treatment, the greater the chances increase of it happening every day.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
