### ISSUE TITLE
Shorts and cargo shorts have broken max encumbrance value

### ISSUE THREAD

**Issue by kitune1415** [CleverRaven/Cataclysm-DDA#53183]
### Describe the bug

Shorts and cargo shorts have 20+ max encumbrance

### Steps to reproduce

1.Spawn shorts and check max encumbrance.

### Expected behavior

Max encumbrance should be 5 if unfitted.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: ba1f9cf [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]

### Additional context

Looks like max encumbrance doesn't loaded correctly and using default value.

**Comment by Venera3** [comment]
The second part of the coverage data has no explicit encumbrance defintion, so it falls back to 5 + max volume/250 (in ml). Since you can stuff 7 *litres* of stuff in there it gets up. While 30 might be a bit overblown, having 14 beer cans rattling around in your pockets should definitely affect you.

**Comment by Photoloss** [comment]
> having 14 beer cans rattling around in your pockets should definitely affect you.

Can we finally split encumbrance into weight and bulk? 7 litres of empty beer cans tightly fastened to your outer thighs wouldn't really do much, but 7 litres of lead weigh as much as a person. On the flip side a full mail suit weighs a lot and doesn't obstruct your ability to swing a sword or draw a bow much at all, but try that with empty bags slung from your wrists.
