### ISSUE TITLE
Small quality-of-life improvement to laptops: The ability to record books that are right next to the player, rather than be limited to only ones directly in the inventory

### ISSUE THREAD

**Issue by cataclysmsurvivalist** [CleverRaven/Cataclysm-DDA#53207]
### Is your feature request related to a problem? Please describe.

I opted to ignore that because I thought it was just a matter of convenience, but now I found a rare library that was once used by old survivors and it's filled to the fucking brim with books. The knowledge greed in me can't let that crap slide, I really want to register them all. I think that's a pretty big oversight that makes things extremely inconvenient for no particular reason, and while I wouldn't call it a bug per see, I still think it should be included for the next update.

### Solution you would like.

It should be possible for the player to register books while standing right next to them, rather than only the ones in the inventory.

**Comment by Saicchi** [comment]
Kind of a duplicate of #52920?

**Comment by cataclysmsurvivalist** [comment]
> 

I was not aware of that thread, since it's my first time seeing it. If this one is redundant, will it be deleted?

**Comment by Night-Pryanik** [comment]
Duplicate of #52920.
