### ISSUE TITLE
Add some kind of soundproofed variants of terrain/means of soundproofing for player characters

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#53204]
### Is your feature request related to a problem? Please describe.

For someone like myself, who both uses Magiclysm/Arcana and is really into basebuilding, I find that my character's followers rarely get a chance to sleep due to all noise generated by the spells my character casts on herself to keep the rate at which she does literally everything as fast and efficient as possible. I also have found that I've had to reorganize my character's base, after I realized how annoying it is to have an enclosed place for the various pets she's accumulated right next to where she crafts and disassembles everything, since I got constantly interrupted by messages about hearing footsteps from said enclosed space.

For other players, who aren't as much into basebuilding as I am and who see the construction menu more as a way to rig the battlefield against relatively-nearby zombies than as a way to build a more permanent home, I'd imagine that adding soundproofed walls/floors would add some interesting new strategies for surviving - and interesting new challenges as well, especially for walls that were already soundproofed before the Cataclysm.

### Solution you would like.

I would like for there to be a way for terrain such as walls and floors to be soundproofed (probably with a flag of some kind), and, by extension, I would also like for variations of terrain with this soundproofing applied to be added to the game, and made constructible by the player character to at least some extent.

### Describe alternatives you have considered.

Pretending that soundproofing isn't a thing

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
