### ISSUE TITLE
Erroneous usage of salt_seasoning ingredient list in certain recipes 

### ISSUE THREAD

**Issue by FoolsGold45** [CleverRaven/Cataclysm-DDA#53211]
### Describe the bug

Deluxe fried egg recipes are pulling from an ingredient list intended for curing meat, for use as a seasoning. The most obvious issue is that this list includes black gunpowder.

### Steps to reproduce

1. Make a character with all recipes unlocked
2. Check crafting ingredients for deluxe fried eggs, deluxe fried egg sandwich, and wheat-free deluxe fried egg sandwich

### Expected behavior

To not be able to salt my eggs with gunpowder, medical saline solution, etc

### Versions and configuration

Current experimental

**Comment by FoolsGold45** [comment]
#45611 I guess this was done on purpose? Looks like this pr was intended for purely meat Preservation recipes though, the current utilization of this ingredient list for fresh foods such as eggs and hot dogs seems unintended.

**Comment by Alex-Folts** [comment]
I saw recipe also use saltpeter, which is potassium nitrate, which is one of components in clasic recipe for black powder. I think thats wy.

**Comment by Owlfren** [comment]
Gunpowder has been used in drinks and as a seasoning IRL so I'm guessing that's where it is drawn from. That said I'm not sure how common that is these days (other than the whiskey shots).

**Comment by FoolsGold45** [comment]
Regardless, the recipe list that includes black gunpowder is clearly intended for meat preservation. The fried egg recipes should not be utilizing it.
