### ISSUE TITLE
Disassembling a tool with a battery doesn't yield a battery

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#53215]
### Describe the bug

It just vanishes!

### Steps to reproduce

Load the game, disassemble a coffeemaker, look around and figure that the battery is gone.

### Expected behavior

Battery conservation.

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.F-4227-gba1f9cfb84-dirty [64-bit]
- Graphics Version: Curses
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

[2021.12.01.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7655038/2021.12.01.zip)

**Comment by I-am-Erk** [comment]
Coffee makers should probably not have batteries anymore, and instead should draw from your power grid

**Comment by mqrause** [comment]
Does that happen for any kind of pocket or just for magazine wells? Or is this explicitly a battery thing?

**Comment by l29ah** [comment]
Seems working correctly with pockets, checked by disassembling a `makeshift sling`, the behavior is not ideal tho (the stuff ends up on the ground, not in the vehicle tile i'm standing on OR crafting desk i disassembled it on OR inventory OR hands).
