### ISSUE TITLE
Invalid overmap special id "Military Outpost"

### ISSUE THREAD

**Issue by stemps** [CleverRaven/Cataclysm-DDA#53224]
### Describe the bug

Since switching to one of the recent `HEAD` builds I am getting the error message

```Invalid overmap special id "Military Outpost"```

on every game load and sometimes when walking around.

I assume this was introduced by https://github.com/CleverRaven/Cataclysm-DDA/commit/ba1f9cfb848132bdcc4698e9c226a04a9dcee01a#diff-e994ff0fa63b304d0c1d6a1adb13f841f6a3ff0b328c58f34435263d78232aeeL834-R843 and existing savegames don't get migrated correctly.

If someone could point me to a previous commit where similar IDs were already migrated I could make an attempt at creating a fix PR.

### Steps to reproduce

1. Have an older save with a military outpost
2. update to latest HEAD
3. 💥 

### Expected behavior

Existing saves should be migrated to the new ids.

### Versions and configuration

- MacOS (homebrew `--HEAD`)
-  Version: `HEAD is now at 66c53a15e0 Merge pull request #53200 from CleverRaven/update-toc`

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7655747/debug.log)

**Comment by wapcaplet** [comment]
Confirmed. This occurs every time I load my save game.

```
DEBUG    : invalid overmap special id "Military Bunker"

 FUNCTION : const T &generic_factory<overmap_special>::obj(const string_id<T> &) const [T = overmap_special]
 FILE     : src/generic_factory.h
 LINE     : 445
 VERSION  : 0.F-4248-g69966b075b
```

There is a similar error for `FakeSpecial_s_jewelry` and `FakeSpecial_used_bookstore`, and a previous issue #51856 is open for a similar error for `FakeSpecial_s_bike_shop_1`.

My understanding is that these cannot be migrated, and need special handling in the savegame-loading code.

**Comment by wapcaplet** [comment]
Here is a saved game from 0.F-3 that reproduces this error and several related ones.

[MilitaryOutpost0F3.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7695622/MilitaryOutpost0F3.zip)

**Comment by wapcaplet** [comment]
Still occurring with the [MilitaryOutpost0F3.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7695622/MilitaryOutpost0F3.zip) save attached above.

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-4540-g8b32af6577 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]
