### ISSUE TITLE
Intergrated toolset not displaying tool quality 

### ISSUE THREAD

**Issue by DeshawnINHERE** [CleverRaven/Cataclysm-DDA#53230]
### Describe the bug

Intergrated toolset not displaying its tool qualities

### Steps to reproduce

1. Install intergrated toolset CBM
2. Wield the extended multitool
3. Check the extended multitool you're wielding
4. Displays no tool qualities 

### Expected behavior

It should display it's qualities 

### Versions and configuration

Version: c232b41

**Comment by DeshawnINHERE** [comment]
I read on the pull request and this was the last post on the qualities 
[ "WRENCH", 1 ],
[ "WRENCH_FINE", 1 ],
[ "WHEEL_FAST", 1 ],
[ "SCREW", 1 ],
[ "SCREW_FINE", 1 ],
[ "CUT", 1 ],
[ "DRILL", 3 ]

Plus soldering and wielding

**Comment by wapcaplet** [comment]
I cannot reproduce this. Extended toolset displays all the expected qualities:

![image](https://user-images.githubusercontent.com/238395/144757690-d375c7cb-23b7-421e-8ce3-765f943e6946.png)

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-4108-gfa916867f5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by anoobindisguise** [comment]
I listed its functions in the item itself but may have missed this. Does anyone remember if it listed qualities before I started messing with it?

**Comment by wapcaplet** [comment]
@anoobindisguise Your commit 4b639b75 appears to be the initial removal of all qualities; commit 30602783 restored several but then bbb677f2 removed them again, leaving it only with the "HAMMER" and "CROWBAR" use_actions.

**Comment by anoobindisguise** [comment]
Ah I think I see, I left the qualities in the fake tool but not the extended tool. I'll make a PR for that in a bit if no one else does.
