### ISSUE TITLE
Items stored in clip-on storage are not displayed in inventory

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#53236]
### Describe the bug

Items kept in clip-on storage in the backpacks with the new functionality created by #53162 causes those objects to be hidden in the inventory. They are there and can be retrieved by (U)nloading the relevant container, but are otherwise impossible to interact with. Considering that weapons and large tools are likely to end up here, this is a bit of a problem and creates extra keypresses.
### Steps to reproduce

1. Spawn a MOLLE pack
2. Spawn an M4A1 for the MOLLE pack
3. Ensure the M4A1 is stored inside the MOLLE pack
4. The M4A1 is not selectable in the inventory and the MOLLE pack must be unloaded to access it. I cannot wield the gun when it is in this state.

### Expected behavior

I would expect it to be listed among my other inventory items so I can interact with it normally.

### Screenshots

![image](https://user-images.githubusercontent.com/2125926/144763117-6a483953-3f95-42cb-b220-0dac18f26c48.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 33a2804 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations]
]

**Comment by Inglonias** [comment]
Turns out there is a little button in the inventory to fix this. Didn't know that.
![image](https://user-images.githubusercontent.com/2125926/144764393-b4955d4f-c726-433a-9d42-175a42f73e58.png)

If this is intentional behavior, let me know and I'll close the issue.

**Comment by andrei8l** [comment]
This is intentional and you can (un)hide from any inventory window with the keys `<` and `>`. If the `hidden` tag is not clear enough, maybe we can draw it in a different color.

The relevant PRs are [50491](https://github.com/CleverRaven/Cataclysm-DDA/pull/50491), [52602](https://github.com/CleverRaven/Cataclysm-DDA/pull/52602), and [52709](https://github.com/CleverRaven/Cataclysm-DDA/pull/52709). I could maybe add a flag to certain pockets (like this holster on a backpack) to prevent collapsing but I think that would just lead to more confusion.

**Comment by Zireael07** [comment]
Nope, not clear enough, at least in this case.

**Comment by Inglonias** [comment]
I saw that the items were hidden. I just didnt expect it to behave that way.

**Comment by andrei8l** [comment]
Ok, so what is the expected behavior? Currently, the hidden items can be interacted with directly from all menus if their collapsed parent isn't visible; otherwise you have to uncollapse first.

**Comment by Inglonias** [comment]
I didn't expect the items to be hidden in the first place. They aren't typically hidden when placed in other pockets, at least in my experience.

**Comment by bombasticSlacks** [comment]
at least for me starting a fresh save and doing what you recommended the MOLLE pack doesn't default to hidden contents which makes sense since it didn't before adding some pockets. You may have just pressed the hide contents key by mistake during play before putting something into it.

**Comment by Inglonias** [comment]
I'm closing this issue because others are failing to reproduce it, nothing appears to actually be broken, and it only really happened because I didn't fully read the UI in front of me.
