### ISSUE TITLE
Magiclysm - "Cast a spell" achievement obtained while asleep

### ISSUE THREAD

**Issue by ChucklesTheBeard** [CleverRaven/Cataclysm-DDA#53238]
### Describe the bug

The Magiclysm achievement "Cast a spell" was granted while the player was asleep.

### Steps to reproduce

I'm not sure how to reproduce the problem. I've seen it happen while sleeping in a car out in the woods during several games, but I don't know what the trigger is, or if sleeping is a factor beyond letting time pass quickly.

### Expected behavior

"Cast a spell" should presumably only be given when the player actually casts a spell.

### Screenshots

![image](https://user-images.githubusercontent.com/12536545/144763906-d933e7f3-e765-4806-b8b2-6a9aa03dfa52.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 66c53a1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Crazy Cataclysm [crazy_cataclysm],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Mythical Martial Arts [MMA],
    Stats Through Kills [stats_through_kills],
    Military Profession Pack [military_professions]
]

**Comment by wapcaplet** [comment]
A similar issue #48084 was fixed once, but this looks like a reoccurrence, or another way it can happen.

Another similar issue #47425 relates to spell level achievements.

**Comment by mkrutov** [comment]
I also keep receiving this achievement randomly while doing mundane things.

**Comment by Inglonias** [comment]
Was notified of this issue by CodeTriage.

After testing, this achievement is indeed broken. It looks like the achievement isn't named correctly, as its requirements involve getting a spell to level 1, and not actually casting it. I don't know if we have an event for casting a spell, to be honest.

```
  {
    "id": "achievement_max_spell_level_1",
    "type": "achievement",
    "name": "Cast a Spell",
    "description": "The first great milestone to becoming a full-fledged wizard is to cast a spell.  Some mages simply study the spell in the spellbook until they think they understand it as well as they can, but you can't beat practice over theory.",
    "requirements": [ { "event_statistic": "avatar_max_spell_level", "is": ">=", "target": 1 } ]
  }
```
