### ISSUE TITLE
Exodii CBM installation bug

### ISSUE THREAD

**Issue by LilimDiam** [CleverRaven/Cataclysm-DDA#53244]
### Describe the bug

You can skip the unconsciousness period triggered by installing CBM starter pack by Rubik if you ask to help you install CBM without exiting dialogue tree. If you do that, you end up unconscious for the installation time of new CBM, but retain Blind and Deaf effects for their duration.

### Steps to reproduce

1. Ask Rubik to help you become cyborg and supply anesthesia kits.
2. Without exiting dialogue window, ask Rubik to help you install CBM. (Either by having some beforehand or by buying one from them, both are possible without exiting dialogue window.)
3. End up blind and deaf after installation of CBM you asked.

### Expected behavior

Not being able to end up in this situation, probably by making sure you can't ask Rubik for help with CBM installation before you leave the dialogue screen and finalise initial installation.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 307572a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Mythical Martial Arts [MMA],
    No Rail Stations [No_Rail_Stations],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by I-am-Erk** [comment]
I believe this was resolved by removing the blind/deaf effects
