### ISSUE TITLE
Multitiles on Overmap

### ISSUE THREAD

**Issue by nheve** [CleverRaven/Cataclysm-DDA#53240]
### Is your feature request related to a problem? Please describe.

I was trying to add missing textures (in Ultica tileset) to the lake on overmap - and while ive been able to attach single texture to it (both lake_shore and lake_surface) - for some reason i cant really add the autotile/multitile setup to it.
Ive read Ultica's guide on github how to prepare textures for autotiles, and ive prepared the code like in the other autotiles (like for some furnitures or different liquid bodies). But it still didnt work, and resulted in the game showing only single tiles on the overmap.

Then i tried to set up additional tiles like user Acepleiades did for the river, but it isnt possible to do as well. It seems that river has in code (data/json/overmap/special_locations.json) its own ids for multiple direction variants, like: river_ne, river_se, etc - but lake_shore and lake_surface dont have any of similar variants. After checking these options - i would assume that multitiling on overmap, without these additional id terrain variants in code, isnt possible?

### Solution you would like.

I would like to be able to add autotiles/multitiles for the overmap tiles, similar as in a non-overmap tiles.
It seems like the additional terrain variant (direction) ids for some overmap tiles (in my case **lake_shore** and **lake_surface**) should be added to the **special_locations.json** file.
Or maybe some different changes to the code should be made, to open a possibility of creating multitiles on overmap to all tilesets creators.
Third option could be possibility of me making mistake at some point in my setup - and if thats true, i apologize, and would really appreciate pointing the proper solution to fix mentioned mistake. Thank you.

### Describe alternatives you have considered.

1. Adding multitile code (used similarly as for non-overmap tiles) for the lake_surface and lake_shore, following other users code and this guide: https://i-am-erk.github.io/CDDA-Tilesets/how-to/autotiles.html

2. Trying to add different parts of multitiles in a similar way as user acepleiades did in the river.json: https://github.com/I-am-Erk/CDDA-Tilesets/blob/master/gfx/UltimateCataclysm/pngs_normal_32x32/overmap/river/river.json
This option unfortunately isnt possible, because of missing ids (like river_ne, river_se) for the lake_surface and lake_shore.

### Additional context

My graphics tileset setup for adding multitiles to lake_surface and lake_shore (very raw graphics, just for testing of all different corners and directions):
![screen1](https://user-images.githubusercontent.com/83027765/144765623-d7b31592-c8ea-4122-8d94-98e75511e616.png)

My addition to the code in **tile_config.json** file in the Ultica Tileset - for testing the tileset directly in game:
![screen2](https://user-images.githubusercontent.com/83027765/144765624-e91e953d-ed2d-41da-8ecd-5ef161428607.png)

Lines of code from the cdda/data/json/overmap/**special_locations.json** file. As you can see, river has different variants, and lake_shore (as well lake_surface) doesnt have ones:
![screen3](https://user-images.githubusercontent.com/83027765/144765625-1e819d08-62c3-4cd9-b7d7-c11716d5483b.png)

Results of the overmap tiles in game - lake tiles are not autotiled:
![screen4](https://user-images.githubusercontent.com/83027765/144765626-a01079fc-fa11-447a-b252-948e4c2e0171.png)

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
