### ISSUE TITLE
Pickup menu positioning option still in settings menu

### ISSUE THREAD

**Issue by VoleurVolant** [CleverRaven/Cataclysm-DDA#53249]
### Describe the bug

The pickup menu no longer pops up a sidebar-like interface, instead using a centered menu like `R`ead does. I believe that this obsolesces Settings/Options/Interface/41: Pickup Position, as the new panel cannot *be* `left`, `right`, or `overlapping the sidebar`. I would remove that setting, but I'm not comfortable trying to.

### Steps to reproduce

It's in the settings menu on the main screen. Hard to miss.

### Expected behavior

The player should ideally only be asked if they would like to change settings that will result in a change to the game.

### Versions and configuration

Linux Tiles 0.F-4262-g33a28042a9

**Comment by mqrause** [comment]
Yeah the whole old pickup code still needs to be cleaned up.
