### ISSUE TITLE
Crater on top of rooftop creates dirt tile

### ISSUE THREAD

**Issue by DeshawnINHERE** [CleverRaven/Cataclysm-DDA#53241]
### Describe the bug

Confusing looking rooftop had dirt floor which turned out to be a crater which lead to me dying from rad poisoning. 

### Steps to reproduce

1.Find rooftop with crater
2.See the dirt tiles on top of it 

### Expected behavior

for craters to destroy rooftops or not appear on them at all

### Screenshots

![vlcsnap-2021-12-05-23h24m04s688](https://user-images.githubusercontent.com/95584149/144766580-dbcef553-3dc1-4177-80f2-e5f78d3c3263.png)

### Versions and configuration

version: c232b41

**Comment by Lamberthassel** [comment]
I confirm there's a bug here, I've been able to reproduce it.
The dirt floor is being generated here: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/map.cpp#L3514
Not 100% sure but it looks like map_extras are being added in 2D mode.
Removing this line alone seems to fix the issue (see the screenshot below) but it might break something else so I think we need someone more familiar with the codebase (The initial feature was designed quite a long time ago #12502).

![image](https://user-images.githubusercontent.com/28668981/144900349-85ff227d-0514-4ec7-a3ad-cdd037a61053.png)

**Comment by DeshawnINHERE** [comment]
Ah nice to get some conformation. I was afraid that i was mistaken about the crater on the roof being the think that killed me. hopefully removing that line will fix it, but like you said hopefully someone comes and reviews it
