### ISSUE TITLE
Replace skeletal HARDTOSHOOT flagging with appropriate weakpoints

### ISSUE THREAD

**Issue by Photoloss** [CleverRaven/Cataclysm-DDA#53255]
### Is your feature request related to a problem? Please describe.

The "HARDTOSHOOT" flag on these enemies originated in a time when they were literal walking skeletons with a significant fraction of open space in their cross-section. Presumably it has remained since in order to preserve their role as anti-ranged threats despite not making a lick of sense, especially on the skeljug. There are no references to any other supernatural ability justifying the flag either e.g. smoke or shady magic.

### Solution you would like.

We have a dedicated bullet damage/armour type now, and the weakpoint system. Instead of making these zombies harder to hit/aim at make their armour work with appropriate effectiveness. Ideally add location-specific damage multipliers to weakpoints if those don't exist already to represent thinner bone plates (low dmg bonus) versus actual gaps like the eyes (high dmg bonus). We could even have "anti-weakpoints" representing the strongest domed plates where anything short of a 50cal will simply bounce off, if that somehow makes the code easier to handle compared to just setting the strongest armour value as the default.

These changes should not result in a net nerf to the skeletal enemies, they should merely provide a justification for their strengths which is actually reflected in the creature design and lore. Maybe add other compensation such as increased resistance to bleeding, fire, acid and electricity if specific ranged weapons remain a problem.

### Describe alternatives you have considered.

Add flavour text referencing a smokescreen, camouflage pattern or particularly fast erratic twitching to justify these enemies being "hard to shoot" despite being regular fleshy humanoids with natural plate armour on top.

### Additional context

The described "partial weakpoints" and "strongpoints" would also make sense on other enemies and could potentially also be used to represent intelligent ones like mutants or ferals parrying your attacks, with similarly poor results against a 50cal or a poleaxe. The "HARDTOSHOOT" flag still makes sense on nimble insects and possibly things like zombie hollows or predators due to their unnatural body shapes and movements and should not be deprecated entirely.

**Comment by anothersimulacrum** [comment]
Past context https://github.com/CleverRaven/Cataclysm-DDA/pull/47764#issuecomment-810651746

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
