### ISSUE TITLE
Ways to Mask Scent 

### ISSUE THREAD

**Issue by estebandellasilva** [CleverRaven/Cataclysm-DDA#53251]
### Is your feature request related to a problem? Please describe.

The game currently lacks a way to actively mask you scent - except (correct me if iam wrong) Mutations and mufflers (when an engine is running)

One solution i read was to use special soaps that kill bacteria so you gain smell slower
The other solution was to dress that you sweat less and so produce less smell
The last suggestion was to mix/rub in dirt, leaves and stuff into your clothing overpowering your odor.

### Solution you would like.

since there iss currently no hygene directly in the game lets look at option 2 and 3

Dress to produce less smell and mix in stuff you overpower your smell.
The solution would be kinda simple.

Wearing Filthy Clothing should help you mask your smell. Because Zombies dont exactly react to other Zombies.
That way can give players actually a reason that even later in game why they would wear filthy clothing. (nightraiding hurray)
And looking at some hunting tips regarding the ways to reduce your smell profile it would kinda fit. 

### Describe alternatives you have considered.

well maybe the thing with the soap, but i feel this lacks a downside except that you have to find the stuff actually.
It would be a temporary buff, but it this feels a little lacking

**Comment by ZhilkinSerg** [comment]
The code is there - https://github.com/CleverRaven/Cataclysm-DDA/pull/36160, so all you need is to implement some items.

**Comment by Alex-Folts** [comment]
There is hazmat suit, if it is what i think, it is sealed basically isolate you from outside world, this should work. I think it is best what you can.  As for limiting factor, you will need tank with air/oxygen which will limit time you can wear it, also its usually have bright color so better use it at night.

**Comment by LeahLuong** [comment]
I believe smoking can help w/ reducing your scent footprint. There are also various items that generate smoke as well (tear gas, smoke bombs, etc.) that can entirely obliterate your scent trail. I've seen smoker Z's cut a scent trail & I believe there's a CBM that can do it too.

That said, it would be nice to have the additional options mentioned above implemented. Scent is almost always what gets my early, night-raiding survivors in a pickle so having more early options could help a lot. Maybe even something like smearing Z guts on yourself w/ the tradeoffs of easier infection & a hit to morale. Sort of like how wearing filthy items works but worse. Perhaps filthy items should confer a scent reduction . . .

**Comment by PatrikLundell** [comment]
Unless it has been removed as well, one of the few remaining dissection item is a pheromone gland that causes zombies to ignore you for some time. That's not really an early game item, though, as getting it requires some skill and lots of time to cut up zombies.

**Comment by estebandellasilva** [comment]
> Unless it has been removed as well, one of the few remaining dissection item is a pheromone gland that causes zombies to ignore you for some time. That's not really an early game item, though, as getting it requires some skill and lots of time to cut up zombies.

Looking in the Hitchhikers Guide - regarding Pheromones or Zombie implies that the item does not exist

**Comment by estebandellasilva** [comment]
> The code is there - #36160, so all you need is to implement some items.

How would one do so?

**Comment by victorfeight** [comment]
I would agree that wearing a piece of filthy clothing should confer a scent reduction, similar to using the goop action. Implementation could be simple as, 
if wear (any filthy clothing piece) {
      reduce scent (but don't stack on same clothing piece re-equip)
}

Scent reduction should stack on multiple filthy clothing pieces.
Not sure how to implement this as a mod. Even as a mod this would make sense, be thematic and fun, and give a gameplay purpose to filthy clothing other than morale penalties against the players (giving an interesting choice to choose to wear them).

**Comment by Photoloss** [comment]
Not sure how to model it but [corona discharge ozone generators](https://www.amazon.com/Enerzen-Commercial-Industrial-Deodorizer-Sterilizer/dp/B00JAP7388) could be a simple electric solution for long-term indoor use. Easy to maintain, probably easy to build, not particularly convincing for immediate "smoke bomb" use while fleeing from zombies though.

**Comment by estebandellasilva** [comment]
> I would agree that wearing a piece of filthy clothing should confer a scent reduction, similar to using the goop action. Implementation could be simple as, if wear (any filthy clothing piece) { reduce scent (but don't stack on same clothing piece re-equip) }
> 
> Scent reduction should stack on multiple filthy clothing pieces. Not sure how to implement this as a mod. Even as a mod this would make sense, be thematic and fun, and give a gameplay purpose to filthy clothing other than morale penalties against the players (giving an interesting choice to choose to wear them).

While i agree that scent reduction should stack - there should be a maximum you can reduce it, because you still need to have some danger - max 50 -60 % from my opinion

**Comment by JonathanLochridge** [comment]
This seems like it might tie in with #44880 Since, the OP mentions that sweating less would help?
Although, I think that in the short term simply adding some soap that reduces scent radius for x amount of time would be good.

**Comment by martosss** [comment]
There are currently
- shaving kit
- hair trimmer
- towel - dry yourself
- soap and washing kit(although only for zombies
- other?

I feel like all of those should be able to reduce your smell, and they should have some kind of limit of uses, say, 1 per week for the shaving/hair trimming and 1 per 48h for the washing/drying

Additionally, an idea is tht your clothes could get dirty with time and generate more smell. However, if you wash them you'd decrease the smell.
Not to mention there are washing machines and dryers already implemented in the game - you just need to be able to power them and use them.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
