### ISSUE TITLE
Flaming Eyes aren't hostile and their stare doesn't count as an attack

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#53259]
### Describe the bug

Flaming Eyes are neutral rather than hostile, and their very dangerous debuff stare isn't registered as an attack. Consequently, they don't trigger the typical safeguards in e.g. auto-movement and extended actions. This results in situation where, if you encounter an eye while doing any such things, you will often find yourself at the deep end of the teleglow before you even have a chance to react.

As an example, I once died because I parked next to a hunting lodge and started crafting, at which point a flaming eye came around the corner and, from my player's point of view, instantly filled my car with Hounds of Tindalos. More recently, I almost got got because I was autowalking along a road that turned out to have a portal on it, and just casually sauntered up next to a flaming eye.

### Steps to reproduce

1. Spawn flaming eye
2. Attempt to do a long-term action like crafting
3. Notice that you get no prompts about seeing an enemy or being attacked until it's too late

### Expected behavior

The extreme danger posed by flaming eyes is balanced by the fact that they're relatively slow acting and thus easy to avoid, so they should probably count for the various "not getting instantly murdered for no reason" systems.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 3dc1a79 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by Maleclypse** [comment]
@curstwist were you wanting to make the drone's in TLC neutral and their stare attack not be a hostile attack?   Can you piggyback off of however Flaming Eyes do this?

**Comment by curstwist** [comment]
It's a spell attack not a stare attack, but I'll look.
