### ISSUE TITLE
Coelophysis drops

### ISSUE THREAD

**Issue by Hextroyer413** [CleverRaven/Cataclysm-DDA#53262]
### Describe the bug

Coelophysis drop lab equipment

### Steps to reproduce

1. Find Coelophysis
2. Kill Coelophysis
3. Coelophysis drops lab equipment

### Expected behavior

There is no description that would indicate that the dinosaur will drop something on death.

### Screenshots

OS: Windows 10
Game Version: cdda-windows-tiles-x64-2021-11-25-1616
Mods loaded: Dinomod

### Versions and configuration

OS: Windows 10
Game Version: cdda-windows-tiles-x64-2021-11-25-1616
Mods loaded: Dinomod

### Additional context

The monsters json indicates that the Coelophysis data is copied from the Eoraptor which drops lab equipment on death.

**Comment by LyleSY** [comment]
Yep, not intended. Thanks!
