### ISSUE TITLE
Crafting salted meat slices using vacuum-packed bags creates duplicate slices outside of bags

### ISSUE THREAD

**Issue by epsimpson** [CleverRaven/Cataclysm-DDA#53265]
### Describe the bug

Batch crafted 6X salted meat slice, inside a vehicle, using meat in fridge, vacuum-bags in trunk, salt water in vehicle tank, results going onto nearby table.  Found 12 salted meat slices on table sealed in bags (2 slices per bag), AND 12 salted meat slices NOT inside bags (duped meat slices).

### Steps to reproduce

This bug reproduction method places the sealed bags on the table, each containing 2 meat slices, and the duplicated meat slices are placed in inventory (original event placed duplicate meat on table).
1. Load included save file - space through startup DEBUG warnings if DEBUG warnings during crafting are desired - NOTE - DEBUG messages only happen the first time the recipe is crafted during a game session, even if `SPACEBAR` is used.  To confirm DEBUG messages also happen when selecting `plastic bags` in step 5, you must `S`ave and quit, and reload the save file.
2. Open advanced inventory `/` and confirm no salted meat slices on table to SW or in inventory (advanced inventory in save file is set up with those views)
3. Open crafting menu using `&`.
4. Craft `salted meat slice` - you can right arrow to `Recent` recipes.
5. Select `vacuum-packed bags` - CRITICAL STEP - bug doesn't happen when using `plastic bags`.
6. Select either `chunk of meat` or `scrap of meat`
7. Select `salt water` - I haven't tried other options.
8. If no crafting error losing meat, then reopen advanced inventory `/` and find 2 unbagged salted meat slices in inventory and a sealed package of salted meat slice on table to SW.

### Expected behavior

Recipe should produce 2 salted meat slices sealed in a bag.  Unbagged duplicate salted meat slices should not exist.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.3 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-4289-g8dc5caf63f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Batch crafting is not necessary to reproduce the bug, but if batch crafting is used, and a crafting error losing meat happens, then all duplicate meat slices are still produced, while the entire batch of sealed bags is not produced.  Crafting errors, losing meat, during individual crafting attempts eliminates both the sealed bag AND and duplicate meat for that attempt.

There are 2 sets of DEBUG messages occurring, but both appear to be unrelated to this bug since they occur when the bug doesn't.
- A set of `invalid overmap special id "Military Outpost"` and `invalid overmap special id "FakeSpecial_s_jewelry"` messages that occur during file loading (6X or 7X starting with `FakeSpecial_s_jewelry`) AND ALSO during salted meat slice crafting (7X or 8X starting with `Military Outpost`)
  - This DEBUG message may be unrelated to this bug, since the `invalid overmap special id` messages also happen when `plastic bags` is selected for the recipe, in which case the bug does not happen.
- A set of `ERROR: item_contents::only_item called with 0 items contained` messages that occur during several crafting recipes (e.g. "canned meat" in a 3L jar), but do not occur in the final reproduction method for this bug.

[AlexDupeMeatLocal.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7670666/AlexDupeMeatLocal.zip)
.

**Comment by dseguin** [comment]
It looks like this is resolved by #53220
