### ISSUE TITLE
Cooking with jars selects suboptimal jar

### ISSUE THREAD

**Issue by Lord-Helmchen** [CleverRaven/Cataclysm-DDA#53270]
### Describe the bug

Trying to cook a jar of meat soup (and probably similar recipes) selects a filled glass jar from the adjacent space insted of a (visible from here) empty jar one space farther away. this results in e.g. "glass jar > sauerkraut is not empty. Continie anyway?" Prompt isntead of asking which jar to use.

### Steps to reproduce

have recipe for sealed glass jar of soup (Can Sealer Instructions or You Can Can At Home)
prepare ingredients for a soup
have a nonempty (but not completely full?) glass ja close
have an empty glass jar not quite so close
try to cook soup

### Expected behavior

automatically selecting an empty jar or asking which jar to use (similar to other ingredient choices)

### Versions and configuration

version 3dc1a79
build 2021-12-07-0949

**Comment by morthein** [comment]
#52970 is the issue. I found holding the empty ones or standing on the space then crafting seems to use them first. (guessing the code is written for distance from character? seems like it).  Honestly, I dislike the way it stands now, it makes crafting things with containers really frustrating when it wasn't before.

**Comment by LeahLuong** [comment]
I'd like to point out another couple of semi-related issues:

1. Crafting seems to randomly prioritize component use. I really hate it when I'm preparing food & the game chooses to pop the seal on some unspoiling vittles when I already had an open jar or can to draw from in my stores. I usually move the items I intend to use for food prep into my invo but this seems needlessly hasslesome.
2. Sealed items appear in the 'E'at menu organized according to spoilage time regardless of seal or no. It'd be nice to push  sealed items lower down the list to just above items which have infinite shelf life for convenience's sake.

I 2nd that proximity seems like a silly priority when crafting. If it's in crafting range, I'd prefer priority go to perishability or using more common components, perhaps in that order.

**Comment by dseguin** [comment]
Sorry, I didn't realize it would be such a problem. The way the game processes items for crafting makes it very difficult to use specific items before others. I'll try to come up with an acceptable solution.

**Comment by morthein** [comment]
> 

Aw, don't feel bad. It was a good fix!  Just has some quirks :-)

**Comment by Scorch-Mechanic** [comment]
The way it works now there's no way to tell how many _empty_ jars, cans, or plastic/vacuum bags I have left from the crafting menu, and there's no way to get freshly filled and sealed jars off the list without physically moving them out of crafting range. Frankly I never found not being able to use partially full containers to be a problem, but I am actively hindered by and have to do a lot more micromanagement because of the changes wrought by #52970.

I'm not saying it was overall a bad change. I am saying "please make the crafting menu indicate how many of the available containers have stuff in them _prior_ to blindly starting a batch craft with them"

**Comment by Lord-Helmchen** [comment]
> I'd like to point out another couple of semi-related issues:
> 
>     1. Crafting seems to randomly prioritize component use. I really hate it when I'm preparing food & the game chooses to pop the seal on some unspoiling vittles when I already had an open jar or can to draw from in my stores. I usually move the items I intend to use for food prep into my invo but this seems needlessly hasslesome.
> 
>     2. Sealed items appear in the 'E'at menu organized according to spoilage time regardless of seal or no. It'd be nice to push  sealed items lower down the list to just above items which have infinite shelf life for convenience's sake.
> 
> 
> I 2nd that proximity seems like a silly priority when crafting. If it's in crafting range, I'd prefer priority go to perishability or using more common components, perhaps in that order.

I'd agree that, in addition to the selectin of the containers, ingredient selection could be improved, for example by seperating and marking open vs still sealed ingredients in the component selection popup.
