### ISSUE TITLE
Make corpses drop their loot on the ground when pulped/made non-revivable

### ISSUE THREAD

**Issue by Scorch-Mechanic** [CleverRaven/Cataclysm-DDA#53271]
### Is your feature request related to a problem? Please describe.

Corpses keeping their loot instead of dropping it instantly is a pretty nice verisimilitudinous change, but it seriously cramps my looting now. Previous to the change, I was always using the "list all items around player" interface to search for Phat Lewts like ammunition and guns and stuff. Now I can't, and it's made looting zombie bodies a huge pain.

### Solution you would like.

I still think that the idea is great, but it would be really cool and much less hassle if their corpses would spill their loot on the ground when they are no longer able to revive. Pulped, mangled, dismembered, exploded into bits, whatever. When the corpse is smashed, drop their trash. The point of the "corpse pocket" is to have zombies keep their loot when they revive, not be a permanent container that all zombie loot is kept in forever. It would make sense for the "corpse pocket" to go away when the corpse is damaged beyond revification.

### Describe alternatives you have considered.

It would be incredibly good to be able to use the AIM interface to move stuff out of dropped zombie corpses too, but in the meantime a change that just makes a corpse spill their stuff on the ground when I pulp them would ameliorate the immediate problem.

**Comment by I-am-Erk** [comment]
This circumvents something we actually want to develop further, which is that looting bodies should be a non trivial action that takes time. [I am working on a project](https://github.com/CleverRaven/Cataclysm-DDA/projects/47) that includes some solutions to the "this sucks and is annoying" part, mostly [this one](https://github.com/CleverRaven/Cataclysm-DDA/issues/53292) that will allow you to sort out the contents of containers (eg corpses) in a single automated action. The behaviour of items just falling off a corpse was never a desirable one, and I don't think we should backtrack towards it again so much as move forward to better behaviours.

**Comment by kevingranade** [comment]
Pulping is going to mess up those clothes you want to loot pretty badly, you're going to need to loot first, then pulp, and as Erk says, we want to pretty much automate that process so that you're spending in-game time doing it, not your IRL time.
