### ISSUE TITLE
Missing line in the "Dragon Tail" code in Magiclysm

### ISSUE THREAD

**Issue by SpiritFoxs** [CleverRaven/Cataclysm-DDA#53288]
### Describe the bug

This mutation does not even allow knee pads to be worn, which is illogical.
The line is missing:
"allowed_items": ["ALLOWS_TAIL"],

### Steps to reproduce

1. Acquire a mutation;
2. Try to put on knee pads.

### Expected behavior

Knee pads must be worn.

### Versions and configuration

version: 3b435c9 (2021-12-08-1552)

**Comment by NetSysFire** [comment]
I can confirm this happens with Scaled Reptilian Tail and Dragon Tail, but not with any other tail.
