### ISSUE TITLE
Cant reload 40mm pipe launcher while it installed on any gun

### ISSUE THREAD

**Issue by Bark0805** [CleverRaven/Cataclysm-DDA#53281]
### Describe the bug

Cant reload 40mm pipe launcher while it installed on any gun. Only way to fire grenade is to reload launcher before installation. I tested with M4, hk416, also different types of grenades, it didn't work.

### Steps to reproduce

1. Make a player with any gun, 40mm pipe launcher and 40mm grenades
2. Install empty pipe launcher on a gun
3. Try to reload a grenade, notice you cant

### Expected behavior

40mm pipe launch should be reloadable while installed on gun.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by wapcaplet** [comment]
Confirmed. My M4 modded with 40mm pipe launcher gunmod says it accepts 40x46mm M433 HEDP:

![image](https://user-images.githubusercontent.com/238395/145212490-51724a23-4f10-4e03-845e-9afac7185b9b.png)

I have 5 such ammo:

![image](https://user-images.githubusercontent.com/238395/145212669-d08814f7-493d-4a53-aae6-92ff650425c1.png)

However, *after* firing my 1 round from the launcher, I can use `U`nload on the gun, and it still indicates there is a round in the launcher:

![image](https://user-images.githubusercontent.com/238395/145213092-0c08780a-2fe7-4372-a770-0f9ffdc0ed26.png)

This round (that has already been fired) cannot be `r`eloaded, until I manually `U`nload it first. After I do that, then `r`eload prompts me to reload with a grenade:

![image](https://user-images.githubusercontent.com/238395/145213193-6478dd05-8e43-4bf1-b2a2-ec082ec82ccb.png)

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-4294-gdb37efe49b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Terrorforge** [comment]
This sounds like the same problem as #53133, which is set to be fixed by #53102. For now, you have to manually unload the casing after every shot.

**Comment by Bark0805** [comment]
Weird, but i cant unload casing in my case, i didnt even fired once and i still cant reload. May be a difference between stable and experimental versions.
![image](https://user-images.githubusercontent.com/74302625/145226542-4f1253d9-b708-4da2-bb5a-8bb52a14b23a.png)

**Comment by Hirmuolio** [comment]
It is the casing in the mod.
But you can't directly interact with the mod and the gun thinks you want to handle the ammo of the gun.
