### ISSUE TITLE
Making worn clothes dirty over time or after a blood-bath battle.

### ISSUE THREAD

**Issue by morthein** [CleverRaven/Cataclysm-DDA#53282]
### Is your feature request related to a problem? Please describe.

I'm not sure how difficult a request this is, i'm hoping <dirty> is just a simple tag. I'd like to see the clothes you wear become <dirty> after a bloody fight, over time, or if you exert yourself heavily all day. 
As it stands I made an empire out of soap and only really use it to occasionally clean a piece of gear I want from a corpse, or the occasional shave. 
The <dirty> tag has some really bad detrimental effects if you get hit and are wearing dirty clothes (infection, right?) and it would make <squeamish> even more deliciously terrible. 
 

### Solution you would like.

It doesn't have to be overpowered, as it would be annoying to kill one zombie and have to change, but the amount of guts and blood would seem to build up and make your clothes pretty nasty after awhile, eh?  Same with working very hard, sprinting everywhere, or simply not changing over a season. 

The <dirty> from pulping and battle would affect outer layers first, as obvious, and the over-time <dirty> could affect inner layers first (also the same with working yourself weary, all day). 

### Describe alternatives you have considered.

I found wearing something from a corpse (such as a large bag like a duffle bag when you have only jeans) to be a risk vs. reward idea. Infection can spring from dirty items, but yet you want the bag space.  Yet, once you get past the very beginning and find soap everywhere, one washboard later, and you're a living breathing laundromat that is immune to the dirty tag, making it an 'almost' worthless feature. I found this game to always tend to lean on the hard side of gaming and thinking, and I just think dirty items can be used more maliciously than they are. This would give even a veteran survivor cause to pause a long campaign because all their gear is covered in infection-causing zombie guts and your own sweat. 
Nothing kills over powered-ness faster than a good old infection.

### Additional context

Maybe this is just one more gimmick that will annoy everyone, and I wouldn't want that, I just thought perhaps this will lean it on the realism side, force them to use more ranged and perhaps even not-pulp everything, which of course doesn't completely kill the zombie or you'd have to wash yourself. or not..  and take a risk.

**Comment by estebandellasilva** [comment]
I already had a discussion with Erk regarding this issue - the summary was - yes possible but only if something was implemented which would take away the tedium of doing it manually - like zones only for autocleaning your stuff and so on.

https://www.reddit.com/r/cataclysmdda/comments/prxtvj/comment/hdm2cz4/?utm_source=share&utm_medium=web2x&context=3

**Comment by morthein** [comment]
I would think this would put importance on decision making because of the tedium. Pulp and clean or leave and get zombies again. We do have a recipe for a washing machine which would remove the by-hand problem.

**Comment by Alex-Folts** [comment]
I think it would turn into tedious daily task very fast, its like if character supposed to change clothes to pijama every time going sleep(and after wakeup change back) - it make sense, it is realistic, it is what people do, it has it's benefits, but would be tedious and require automation eventually.

**Comment by morthein** [comment]
Perhaps this would be best taken to a separate mod. Not everyone is in love with busywork I suppose.

**Comment by Photoloss** [comment]
My main issue with this is that unequipping your gear is incredibly annoying and tedious even *without* any situational items you carry but do not want to wear all the time. If I could just grab a bar of soap, hop into a river and (a)ctivate it to clean myself that might be fine (still tedious to get to the water source, but eh). If I had to manually unequip, wash and then reequip all my clothes every day or two I would move to Bright Nights in a heartbeat.

**Comment by catdach** [comment]
It might be more reasonable to have a moral buff for wearing "freshly cleaned" clothes, kinda like how there's a moral boost for eating with a table and chair. That way it can encourage and give benefit to those who want to do that sort of thing without being a detriment to those who don't want to do that level of busy work. 

The whole getting filthy over time thing feels like a big nononopleaseno, even in minimal amounts it really just feels annoying. IIRC in Project Zomboid your clothes become filthy over time and did I ever wash my clothes in that game? No, I looted new clothes and wore that instead or I just ignored the fact that my clothes were dirty. It's just not what I play my zombie apocalypse simulator game for. It really takes me out of my power fantasy of a rugged survivor must do whatever it takes to survive. What's the plan for today survivor? "**looting the nearby gun store**, **clearing out the overrun mansion**, **scavenging for food in the forest**, doing my laundry, filing my taxes, vacuuming the living room." I get that it would be more realistic and it can be cool to be **cleaning blood out of your clothes** in your power fantasy to an extent, but I don't want to be bothered with a tax fugitive debuff when every in game week passes ya'know?

Sorry. I went a bit overboard there, I've just felt like I've seen this sort of suggestion going around a lot lately and had to get that out of my system.

It seems that at least some people do enjoy this sort of thing in their game so I think a separate mod for this level of busywork activities would be a good idea.

**Comment by I-am-Erk** [comment]
As Kevin states. The concept of needing to do laundry is fine! The practice of having to track it manually and press keys for it is not.

Personally I favour passive actions that just occur automatically if you spend more than *n* time in the vicinity of supplied laundry zones.
