### ISSUE TITLE
Let devs name pockets

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#53301]
### Is your feature request related to a problem? Please describe.

The new backpack pockets are great, but even as someone who keeps up with development and knows why they're there, I find myself looking at them and getting confused about what they're supposed to represent. This was already a problem when items had many pockets, but it's really obvious now that most backpacks have lots of them.

### Solution you would like.

Let is name pockets in the json, and display the names in the UI. For example, a survivor belt instead of having like 9 "pockets" with dimensions such and such would have one sheath, one belt loop, one holster and 6 pouches. Backpacks would have "tucked between the straps" and "clipped on" etc.

For extra credit, create a standardized library of pockets so you can just add a pre-defined KNIFE_SHEATH_LARGE instead of having to manually match existing dimensions and terminology

**Comment by bombasticSlacks** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/53283

[I'm three steps ahead](https://thumbs.gfycat.com/ConsiderateKindheartedBobwhite-max-1mb.gif)
