### ISSUE TITLE
Stop NPC followers from verbally abusing each other while walking into each others' tiles

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#53300]
### Is your feature request related to a problem? Please describe.

It's immersion-breaking and disruptive (not to mention at least a little triggering, as a person with C-PTSD) for NPCs who are on the same side to start angrily cursing each other out just because they can't figure out how to walk around each other or walk together in an organized manner, and the sound it generates can attract nearby enemies and/or cause false alarms for other followers in the area.

### Solution you would like.

I would like for some way for NPCs to be able to recognize when the person in the tile they're trying to move through is a friend/ally, and have this prevent them from yelling obscenities at each other, and honestly, preferably just not say anything to each other at all but instead just have the person in the tile being moved into just politely make room for their ally.

### Describe alternatives you have considered.

As described above, but instead of having one politely make room for the other without talking, just disable the more abusive comments among friends/allies (maybe make a separate list with the abusive comments for non-friends/allies), and give NPCs the ability to recognize the voices/words of friends/allies not in their sight (which would probably be a good idea for any future NPC AI overhaul anyway), as well as making the "stay quiet" command for followers also apply to asking others to move out of the way so they don't make any extra noise in dangerous situations.

**Comment by morthein** [comment]
"as well as making the "stay quiet" command for followers also apply to asking others to move out of the way so they don't make any extra noise in dangerous situations."

+1 to this. 
I've had a npc die from what I suspected was giving up our location due to his loud command to move while night raiding some bandits in a field. They rushed over (from behind..!) and shot him to death before I could aim and fire.

**Comment by NetSysFire** [comment]
Since this is the Cataclysm, I could understand why some NPCs do use rough language but however, I am not a fan of it either. There should be a mod which removes the really ugly insults.

I am okay with NPCs calling each other "butchery refuse" or "emergency ration" though.

**Comment by AmarinReyny** [comment]
> Since this is the Cataclysm, I could understand why some NPCs do use rough language

I mean, maybe for random strangers, or even casual acquaintances, that would make some sense, but not for friends or allies. Not only that, but it's also pretty disruptive when it occurs, since it can either attract zombies/other enemies, or give other allies around the base a false alarm which they'll feel compelled to investigate, which will then most likely lead to more occurrences of NPCs being in each others' ways, potentially in an infinite loop - again, I also think that making NPCs able to have different reactions depending on what's being said and who's saying it, where applicable, would be a great contribution to a future NPC AI overhaul.

**Comment by NetSysFire** [comment]
True, I was mainly speaking about the content of those insults which I do find too extreme personally.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
