### ISSUE TITLE
Combat and Motorcycle boots are no longer able to be disassembled due to #52889

### ISSUE THREAD

**Issue by a-chancey** [CleverRaven/Cataclysm-DDA#53315]
### Describe the bug

Issue #52889 reworked integrated toolset to integrated welder, removing a large number of tool qualities from it.
Issue #53197 revamped it slightly, adding a handful of qualities back, but not Cutting 2

This has now rendered Combat and Motorcycle Boots impossible to deconstruct, with two side effects:
1. Neither recipe can be learned, as they're only learned through deconstruction.
2. Kevlar Thread has effectively become unobtanium, given the only source available now is a 20% chance for the Exodii merchant to have _at most 6_ of them.

#53059 is going to audit disassembly and materials, but this is a different issue.
More info below.

### Steps to reproduce

1. I acquire a pair of combat or motorcycle boots
2. I attempt to disassemble combat or motorcycle boots
3. I am informed that they cannot be disassembled as the disassembly required Cutting 2

### Expected behavior

1. I acquire a pair of combat or motorcycle boots
2. I attempt to disassemble combat or motorcycle boots
3. I receive the components from disassembly.

### Screenshots

Here is the combat boots recipe from in game:
![2021-12-09 10_35_53-Cataclysm_ Dark Days Ahead - 66c53a1](https://user-images.githubusercontent.com/2692336/145426793-c2d8d267-52ee-4fd1-82d6-74db6d0f14f0.png)

### Versions and configuration

OS: Windows 11
Game version: 0.F-4306-g61fa86a117 built from source
Graphics version: Tiles
in game language: English
Mods: dda, disable npc needs, no fungal growth

### Additional context

after running through the code in debug, it's an issue within src/requirements.cpp, starting around line 1169 with the emplace_back method. When Sewing is replaced with Cut, it's passing (qual_CUT, 1, quality.level). The quality level is the quality of the sewing tool requirement - level 2. 

Combat boots and Motorcycle boots are the only two Sewing 2 items that can be deconstructed - which is why this may have been missed.

Additionally, sewing levels 3 and 4 (sewing and tailor's kits, respectively) are actually unused across all recipes.

**Comment by a-chancey** [comment]
Additional information: 
Kevlar cannot reliably be cut by normal scissors, and it's preferable to use serrated bladed shears or a diamond coated rotary cutting tool (like a dremel), though a razor knife can work in a pinch. Source: https://compositeenvisions.com/blog/how-to-properly-trim-kevlar-cloth-parts/

Proposed solutions in order of personal preference:
1. Add new cutting tools with cutting quality 2. Since Kevlar should be cut with special tools, this would mean adding:
1.a. Kevlar Shears (which are similar to scissors/fabric shears, but serrated). Possibly craftable with a similar recipe to Scissors but with higher skill requirements for the serration. Serrations are made during the forging process using files to make each individual serration. Source: https://www.redlabelabrasives.com/blogs/news/how-to-make-a-serrated-knife
1.a.1. Update Sewing Kit to include scissors as a component and cut 1 quality (who has a sewing kit but no scissors to cut the thread/fabric?)
1.a.2. Update Tailor's kit to include kevlar shears as a component and give them cut 2 quality.
1.b. Rotary Tool. Something similar to a dremel, which would not be *much* more complicated than crafting a soldering iron, but would need a micromotor. I'm not a fan of having replacement parts for the rotary tool. If we don't have drill bit sets for drills, I don't think we should have rotary tool components. Give the tool the following qualities: 
cutting 2
fine cutting 2
drilling 2 or 3
grinding 1
metal sawing 1
wood sawing 1
fine metal sawing 1
filing 2
This would cover the common bits and attachments most rotary tool kits have available.
1.b.1. Possibly a new upgrade or alternative to the Tailor's Kit, an "Armorer's Kit", which would consist of a tailor's kit, soldering iron and a rotary tool. The only issue I have with this is that it would require both thread and battery power to be loaded into it. Perhaps it can be UPS powered or a vehicle mounted tool?
1.b.2. A CBM version of the rotary tool.
1.c - add these to appropriate spawn groups.

---This would also mean we'd want to bump *all* Kevlar requirements to at least Cutting 2 - and we could possibly require the rotary tool for working with layered or rigid Kevlar, as cutting Kevlar other than individual sheets often needs something like a water jet cutting tool.

2. Modify the reverse requirements code to check for a valid list of tool levels. This is out of my wheelhouse with C++, so someone else may need to take that over. This may be a good idea in the future.
2.a. Modify just the sewing quality replacement to limit it to cutting level 1. This is a bad idea, IMO, as Kevlar sheets can't reliably be cut with scissors.

3. Add cutting 2 back to integrated multitool, but this is the worst case bandaid in my opinion.

Any comments are welcome.

**Comment by Photoloss** [comment]
The serrations on kevlar shears seem to be quite fine, but I imagine those would still get in the way of other uses of the "cutting" quality. On the flip side they kinda resemble bread knives, and we have several knives with coarser serrations (mostly for sawing 1, see survival knife or Swiss army knife). Do we have any info on how these more common implements interact with kevlar?

I'll also note most items are not made *entirely* of kevlar so there's also the possibility of cutting it free from the surrounding fabric with lesser tools. This probably needs to be judged per item.

**Comment by a-chancey** [comment]
> The serrations on kevlar shears seem to be quite fine, but I imagine those would still get in the way of other uses of the "cutting" quality. On the flip side they kinda resemble bread knives, and we have several knives with coarser serrations (mostly for sawing 1, see survival knife or Swiss army knife). Do we have any info on how these more common implements interact with kevlar?

Kevlar shears actually have a very fine serration, as pictured [here](https://www.amazon.com/dp/B07HP9NRZ6/). A more coarse serration actually causes the ends of the fibers to tear and fray, which would require sanding to clean up. It's very similar to fiberglass

> I'll also note most items are not made *entirely* of kevlar so there's also the possibility of cutting it free from the surrounding fabric with lesser tools. This probably needs to be judged per item.

You'd still need to trim Kevlar sheets to fit the coverage you need and to fit pieces together, even if you're using scavenged pieces.

**Comment by Photoloss** [comment]
> A more coarse serration actually causes the ends of the fibers to tear and fray, which would require sanding to clean up. It's very similar to fiberglass

Yes, my concern is how those serrations interact with materials *other* than kevlar. Cutting 2 quality implies the blade is universally better for most materials already handled by cutting 1.

> You'd still need to trim Kevlar sheets to fit the coverage you need and to fit pieces together, even if you're using scavenged pieces.

I was only talking about disassembly not crafting with it. Players might want to destroy the bulky clothing and carry the more compact raw materials, allowing that seems reasonable for anything not made entirely out of large sheets of kevlar. So not army helmets or ballistic vests but the boots should be fine.

**Comment by a-chancey** [comment]
>Yes, my concern is how those serrations interact with materials other than kevlar

From what I've been able to find out, it doesn't seem to be that much different than other types of shears, with the added benefit of cleanly slicing the Kevlar fibers. Shear blades have a flat edge, rather than a point, to apply pressure across a wider surface area to get a cleaner break. If the break isn't clean, this can cause individual fibers to pull and shift, compromising the integrity of the weave - one of the biggest selling points of Kevlar. Using them on carbon fiber would dull them rapidly, due to the abrasive nature of carbon fiber itself, which needs its own special blade, but we don't have anything craftable with carbon fiber so it's a moot point.

>I was only talking about disassembly not crafting with it. Players might want to destroy the bulky clothing and carry the more compact raw materials, allowing that seems reasonable for anything not made entirely out of large sheets of kevlar. So not army helmets or ballistic vests but the boots should be fine.

That's what cutting up the items is for. it's destructive but gives the raw materials. This issue here is directly related to the reversibility of these two recipes in question - they are the only two recipes that can be deconstructed using the reverse function that require Sewing 2 as part of the construction - and as such, require cut 2 based on how the replacement function works.

In fact, now I'm thinking over the recipes in question here and thinking it's completely unrealistic to have most clothing recipes be reversible. The combat boot recipe takes 66 Kevlar sheets, and since it's reversible, disassembling them can yield *up to 66 Kevlar sheets*. And all the thread used to sew it together. That's insane, you're going to have to cut thread, not only while sewing (cut to length), but while disassembling (likely with a seam ripper - a specialized tool, which destroys the thread). Additionally, manufacturing the boots just uses 33 Kevlar sheets each without cutting them whatsoever with this logic, so they can be perfectly recovered when disassembling? Shit, a standard Kevlar sheet is 24"x48". Boots aren't just wrapping your foot with Kevlar and slapping on a sole with rubber cement. At the very least, we're going to want to add patchwork Kevlar sheets and Kevlar patches to bring it in line with the other materials. But that's out of the scope of this issue and should be redirected to #53059 

I had considered adding a new quality for Kevlar cutting or shear cutting, instead of making them cutting 2, but I don't know that this would be the best solution. I think I'll just stick with cutting 2 based on my research - they're made to have extreme precise cut force between the shear edge and the serrations, but not something with a *ton* of control like an X-acto, which would be fine cutting. Until we have something else that might need a higher cut quality, this should be a workable solution

**Comment by mkrutov** [comment]
On top of what's described in OP, the only way to cut up Kevlar vest (and other kevlar stuff which can be salvaged) is to use CUT: 2 item.

**Comment by a-chancey** [comment]
> On top of what's described in OP, the only way to cut up Kevlar vest (and other kevlar stuff which can be salvaged) is to use CUT: 2 item.

#53366 is adding a new (and craftable) Cut 2 tool, I’ll get around to adding a rotary power tool later, I threw the shears together and tested in about an hour, just had to wait for linting and tests to run before I submitted this morning.
