### ISSUE TITLE
Allow players to view unarmed damage as though it were a weapon

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#53313]
### Is your feature request related to a problem? Please describe.

I think it would be useful for people doing martial artist and/or unarmed mutant builds, and probably very early-game characters who need to know how much of a priority it is to find an actual weapon, to be able to view stats for unarmed attacks as though they were stats on a weapon, such as the amount of moves it takes to attack, how much damage is dealt per attack, typical damage per second, and so on.

### Solution you would like.

I would like for there to be some sort of interface which would allow players to view the aforementioned stats for their unarmed attacks.

### Describe alternatives you have considered.

Throwing punches with no idea of exactly how effective they will be compared to using a weapon or how different martial arts and/or mutations might influence their effectiveness.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
