### ISSUE TITLE
0.G Stable - Warning: feature freeze impending.

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#53318]
## Update 19 April 2022
We're now on the way to Feature Freeze. There are a few core features we'd like to get in before this hits but not many. I am hoping to switch to Feature Freeze on or near May the 1st. Feature Freeze, for those who haven't done this before, means no new major code features that will need playtesting and debugging can be merged. Bugfixes and balance fixes are still allowed (and sometimes the line is blurry, but the general rule is "nothing big and new"). Content, such as maps and items, is still merged during feature freeze.

So this is the warning: we're aiming for about 2 weeks to close out merging on features. If you have something waiting, get our attention to merge it. If you have something almost ready, finish it up!

## Previous update, 9 Dec 2021
We're going to try a different thing for the 0.G stable process. Previously, the first official stage of stable development has been 'feature freeze', where new major code features are no longer being merged so we can do bugfixes. This stage has become progressively longer each cycle, and can be extremely hard on contributors.

This time around, we're trying it a bit differently. We are going to start very early with what we're calling "project freeze", effective today. Project freeze means, keep developing and contributing as usual, but don't *start* any new big overhauls that will require multiple PRs and phases of testing. If you do start them, just be aware they'll be frozen and won't be merged until Stable is out, which right now will be several months. Anything ongoing is fair game. If you're not sure, feel free to ask a project maintainer here or in discord about it. There is a fuzzy area around things that themselves constitute new projects, but are necessary to balance out or complete an ongoing project that comprises a major 0.G-stable feature. These will be handled on a case-by-case basis, mostly dependent on how likely they are to wind up throwing off the release of stable if they're incomplete.

I will continue to update this post as we clarify the rules around this, and add some more information about the countdown to 0.G Stable. In general, though, just keep doing your thing as you normally would, but now is not the best time to start totally redesigning the way we do monster attacks or something.

#### This does not mean 0.G stable is close!
This is an early stage change! Our goal is to avoid having quite so long of a total feature freeze, by focusing efforts on in-progress features. Stable is likely still several months away, at the time of this writing, given the number of major features in our countdown that have a lot of work left.

#### Notes for project maintainers
- Don't add the project freeze tag willy-nilly, it has to be something that you're sure will set off a snowball of changes that will delay stable.
- Feel free to apply Project Freeze tags to Issues, to indicate they are things that shouldn't be picked up until 0.G, especially if you're the sort of design dev that creates tons of wide-sweeping issues suggesting changes that will fundamentally alter the state of the game or something. Not that any of us are guilty of *that*.

**Comment by Tommy-os** [comment]
Are serums for 0.G?

**Comment by I-am-Erk** [comment]
> Are serums for 0.G?

Nope (T_T) that's a great example of an issue that should be tagged with freeze, creating and balancing serums will take a few passes.

**Comment by Terrorforge** [comment]
Do you mean creating new mutation lines? Because balancing the mutagen/serum crafting is both an ongoing project and something that needs to be finished before the next stable, because it's in quite a bad state atm.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/howd-you-like-to-help-with-0-g-stable-issue-triage-outsourcing-poll/27415/1

**Comment by I-am-Erk** [comment]
> Do you mean creating new mutation lines? Because balancing the existing mutagen/serum crafting is both an ongoing project and something that needs to be finished before the next stable, because it's in quite a bad state atm.

No, they likely mean the supersoldier serum suggestion I made a few days ago (which, in turn, will mean renaming mutagen serums most likely)

**Comment by Maleclypse** [comment]
> Do you mean creating new mutation lines? Because balancing the existing mutagen/serum crafting is both an ongoing project and something that needs to be finished before the next stable, because it's in quite a bad state atm.

I will happily accept help on getting the remaining mutagen sample monsters created and placed in the game before 0.G.
