### ISSUE TITLE
Add strong scent neutralisation to electricity fields

### ISSUE THREAD

**Issue by Photoloss** [CleverRaven/Cataclysm-DDA#53317]
### Is your feature request related to a problem? Please describe.

Electric discharges in air produce ozone, a potent oxidiser which is produced in this way in [commercial deodorisers](https://www.amazon.com/Enerzen-Commercial-Industrial-Deodorizer-Sterilizer/dp/B00JAP7388) and is responsible for that characteristic "lightning smell". Ozone gas itself decomposes fairly quickly even if not consumed in oxidisation reactions. As currently portrayed "fd_electricity" is visible to the naked eye in broad daylight for several seconds which should be enough to obliterate any scent in the affected tile.

### Solution you would like.

Add "scent_neutralization" property to "fd_electricity" at least on par with smoke, albeit noting that ozone does not "mask" the scent but rather outright destroys it. Possibly wait for #53135 to be completed to work with the changes to field intensity.

If someone has the time to build a proper model maybe add ozone gas as its own field effect as we do have some rather persistent discharge sources in incandescent husks and generator traps. Ozone is not *poisonous* in the stricter sense but it [can cause lung damage](https://en.wikipedia.org/wiki/Ozone#Acute_ozone_exposure) in higher concentrations while continuing to oxidise airborne molecules.

### Describe alternatives you have considered.

Tangentially related to #53251 but this is more motivated by real world secondary effects of electric discharges with *potential* relevance to gameplay rather than adding convenient player-controllable means of mitigating scent.

**Comment by GoLoT** [comment]
I'll remove the WIP tag on #53135 as I think the rework is fine as it is. I wanted to add infrastructure for electric resistance / insulation, but I think it goes out of the scope of that PR anyway and it's probably better to playtest those changes on their own and then work on resistances as a different project.

Hopefully it can be fast-tracked (and possibly playtested so nothing breaks in actual runs, as test scenarios don't really paint the whole picture) so it doesn't block your changes for too long.

**Comment by Photoloss** [comment]
> In pure oxygen atmosphere yes, in air it also produces nitrogen oxide, and if im not wrong there is more of it compare to ozone. But NOx also potent oxidizer.

[Here](https://www.york.ac.uk/res/gkg/nox/nox_pap.html)'s something on NOx yield, conclusions are in the range of 10<sup>16</sup> NO molecules per joule. Unfortunately I can't find a comparable source for ozone in a hurry, too much work on the ozone layer (photochemical production via UV light) and lab equipment (focused on concentrations or flow rates) getting in the way. The two processes are related however as both rely on high energy reactions splitting O2 and subsequent collisions of O with N2/O2 respectively. Nitrogen oxides aren't particularly *toxic* either so for gameplay purposes they're mostly just another short-lived gas which directly wrecks your lungs. (Don't read this as me saying they're harmless, but the lung damage will kill you far more quickly and dedicated poison zombie gas has rather limited effects.)

> Should we ask question: since zombies are ex humans, and human have bad sense of scent, should zombie even detect us by scent?
Animals and monsters based on animals are fine, wolf will scent you even with maskings, but human...?

They're Blob-mutated with an "intent" to kill and assimilate otherwise they would not attack us at all, basic sensory enhancements seem perfectly fine in that regard.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
