### ISSUE TITLE
Autosaving during unload activity creates save that crashes the game

### ISSUE THREAD

**Issue by Hirmuolio** [CleverRaven/Cataclysm-DDA#53312]
### Describe the bug

Game throws some errors and then crashes.

Seems like the game autosaved during unload action and can't finish it after loading the save.

The errors:

```
 DEBUG    : Failed to find item_location owner with character_id 1

 FUNCTION : bool item_location::impl::item_on_person::ensure_who_unpacked() const
 FILE     : src/item_location.cpp
 LINE     : 291
 VERSION  : 6de928c
```

```
 DEBUG    : item_location lost its target item during a save/load cycle

 FUNCTION : void item_location::impl::ensure_unpacked() const
 FILE     : src/item_location.cpp
 LINE     : 115
 VERSION  : 6de928c
```

```
 DEBUG    : parent location does not point to valid item

 FUNCTION : void item_location::deserialize(const JsonObject&)
 FILE     : src/item_location.cpp
 LINE     : 785
 VERSION  : 6de928c
```

### Steps to reproduce

1. Set autosave frquency to 10 turns/0 minutes to make it more likely for the autosave to occur.
2. Get something slow to unload (for example full STANAG magazine)
3. Unload the magazine
4. Close game and try to load the save. It is broken.

### Expected behavior

Not autosaving during actions would probably be the best.
Graceful recovery from broken situation would be nice extra.

### Screenshots

![crash](https://user-images.githubusercontent.com/22011552/145379050-b288e0ad-3965-4149-847f-af5e9674c178.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 6de928c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

A broken save: [milbase.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7684165/milbase.zip)

**Comment by LeahLuong** [comment]
This may be what happened to me in #52775. Almost lost my game but was able to find a solution mentioned there in a previous thread. Autosaving does seem slightly problematic @ this point & needs either more checks in place or better error-handling.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/segmentation-fault/27429/3
