### ISSUE TITLE
Make photos show the emotional, physical state of the depicted character

### ISSUE THREAD

**Issue by airportation** [CleverRaven/Cataclysm-DDA#53336]
### Is your feature request related to a problem? Please describe.

As it stands, the appearance part of photos only shows the player's outfit. This is rather boring in and of itself, and makes them rather forgettable unless you go on a safari to snap pics of monsters. I think I've got a way of making photography a lot more flavourful. To the point that a selfie of yourself, in your bunker, after a heavy hauling trip, could actually make you think back on what a day that was.

### Solution you would like.

Instead of just showing the outfit, appearance could also encompass other things:
- the emotional state of the character, drawn from either morale or the effects that come from morale
- their health, like saying "X looks _well fed_ if overweight, _haggard_ at low health, _parched_ if thirsty, _pale_ after blood loss", showing the symptoms of an infection,...
- their health in terms of otherworldly things too, such as fungal infection, slimed,...
- various other effects, like "her eyes are red-rimmed" if you've been smoking marijuana, "he looks tired" if you're fatigued,...

A tiny few of these might look out for mutations/cybernetics too, though that wouldn't be necessary: Do the eyes of a bug mutant still turn red from marijuana? Should the description for freezing hands depict that the finger lighter isn't affected?

### Describe alternatives you have considered.

Make every human on CDDA-Earth canonically have a permanent pokerface.

One user also had the idea that what state of happiness the photo depicts could impact your morale when you look at it. This should be looked into too imo.

### Additional context

Previous discussion and some feature ideas can be found in this thread: https://old.reddit.com/r/Cataclysm_DDA/comments/ra9lu3/idea_for_photos_show_the_emotional_state_of_the/

Here is a crude mockup to show what I am talking about; look at the second line from the bottom. I made this when the idea only included morale, the window would have to be extended or given a scrolling bar for the entire thing to work.
![image](https://user-images.githubusercontent.com/67428677/145543655-e898ea36-ea3f-441e-baa2-17f09db2765c.png)

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
