### ISSUE TITLE
Vehicular childbirth

### ISSUE THREAD

**Issue by VoleurVolant** [CleverRaven/Cataclysm-DDA#53330]
### Describe the bug

Occasionally when moving a vehicle by hand one of the tiles will be left behind / copied. That tile remains in place on the original, but all parts present on that tile of the main vehicle are present on a strange isolated spot as well, which does not move when the original is pushed further. Saving and reloading makes that erroneous tile of parts disappear, but in the meantime it retains at least some traits of the 'true' version - impassibility being one, if present on the original. I have yet to get an appliance or door to be left behind, but if I manage such a thing, I will comment on whether or not power can be drawn from the parent car while at the isolated child tile, and on whether opening and closing a door on one of the two causes it to be opened and closed on the other. 

### Steps to reproduce

Frankly uncertain what exact steps are involved. It just happens sometimes.

### Expected behavior

I would expect the number of parts in a vehicle to remain constant every time that vehicle is moved, and for all tiles of a vehicle to move together.

### Screenshots

![image](https://user-images.githubusercontent.com/94157027/145498192-0fe54935-e0c3-452c-93c6-0cc2ddf1e586.png)

### Versions and configuration

Multiple versions, most recently 0.F-4262-g33a28042a9. Occurs both with and without native mods. No external mods used.

### Additional context

Could potentially be related to an error that stemps#7761 [mentioned](https://discord.com/channels/598523535169945603/642349261320880128/917554274211348500) in the development discord: 
'There's something weird going on with my cart on some levels of the trans coast logistics place. It happens more often in some places than others. When it happens I lose the cart I'm dragging and when I go back I can't grab it anymore. I need to walk off screen and come back and then find the cart a few tiles away from where it should be.
... and sometimes I see "You can't find the grabbed object" messages'

**Comment by GoLoT** [comment]
Linking #53266 for reference (issue related to the additional context).

**Comment by hexagonrecursion** [comment]
I have encountered this bug too.

A reliable way to reproduce this issue:
1. Wish for an electric scooter
2. Move south twice
2. Grab the scooter
3. Move south

Note:
* I have not found a reliable way to reproduce this bug except immediately after spawning a fresh vehicle
* I did encounter this bug in a regular (non-gebug) game too.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 0.F-4465-gef6206f0f7 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
