### ISSUE TITLE
Melded Task Forse won't drop anything.

### ISSUE THREAD

**Issue by Kywi001** [CleverRaven/Cataclysm-DDA#53335]
### Describe the bug

Since the new feature that items are bound to corpse, there's a bug that when a Melded Task Force dies it won't drop it's item as it spawns a Swirling Air instead of it's corpse.

### Steps to reproduce

1. Spawn Melded Task Force. (or do a Transcoast run)
2. Kill said Melded Task Force.

### Expected behavior

When killed, Melded Task Force should spawn a Swirling Air where it died and it's items in said tile.

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: Xiaomi; Model: Redmi 6; Release: 9; Incremental: V11.0.4.0.PCGMIXM; 
- Game Version: 1c847f1 [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Military Profession Pack [military_professions],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Inglonias** [comment]
This seems to have been resolved by #53362

**Comment by wapcaplet** [comment]
Thanks for verifying. Closing issue.
