### ISSUE TITLE
Nail prying quality missing from firearm/gunsmith repair kits. 

### ISSUE THREAD

**Issue by new02DAY** [CleverRaven/Cataclysm-DDA#53356]
### Describe the bug

Nail prying quality is missing from kits that have hammers. And should possibly be removed from makeshift hammer? The description ("This is a crude hammer made from a piece of metal affixed to a stick. It functions adequately as a hammer, but really can't compare to a proper one.") doesn't really fit being able to pry nails.

### Steps to reproduce

1. Spawn items mentioned.
2. Unable to pry nails "You can't use your firearm repair kit to pry up the nails.".
3. Spawn crowbar, can pry nails.

### Expected behavior

Be able to pry nails using kits that contain a hammer.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: c6f4ab5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    Player Mod [Player_Mod],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Max17U** [comment]
So as of now only the "gunsmith repair kit" is missing the quality prying_nail, right?
