### ISSUE TITLE
High Grade Meth Recipe needs too much acetone

### ISSUE THREAD

**Issue by estebandellasilva** [CleverRaven/Cataclysm-DDA#53357]
### Describe the bug

The high grade Meth recipe require 150 units of acetone for 6 units of meth - thats 37,5l of acetone ... seems a bit out of whack if you ask me.

Other recipes use 5(apex) or 1(rubber cement) units of acetone - this why the number for meth feels completely out of context

### Steps to reproduce

Look at the high grade meth recipe

### Expected behavior

Resonable amount of acetone when trying to craft high grade meth

### Screenshots

![image](https://user-images.githubusercontent.com/89189872/145670189-75486a92-a552-488c-83fe-3333ec42e4ee.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: c6f4ab5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by wapcaplet** [comment]
The recipe was added in #50511. The original PR was pretty light on details and did not include any references for their choice of ingredient quantities.

That said, do you have any chemistry references that would refute this, except for "seems a bit out of whack"?

**Comment by estebandellasilva** [comment]
> The recipe was added in #50511. The original PR was pretty light on details and did not include any references for their choice of ingredient quantities, but the author said [they a chemist in real life](https://discourse.cataclysmdda.org/t/realistic-chemistry-recipes/26802).
> 
> Do you have any chemistry references that would refute this, except for "seems a bit out of whack"?

From reading around the internet it seems acetone is used to "wash" the meth - to remove impurities and then minimal amounts are used. from reading around it seems like 1g needs like 10-15ml of acetone - problem ist i cannot find any chemistry reference that exactly lists the amounts only user feedback about it.

**Comment by estebandellasilva** [comment]
To emphasize my point.
you need:
15 non drowsy cough sirup (0,75l/0,72kg)
15 iodine crystal (0,015l/0,525kg)
15 red phosphorous (0,015l/0,027kg)
150 acetone (37,5l/30kg)
3 methanol (0,003l/0,003kg)
5 lye powder (0,005l/0,0105kg)

to get 6 high-grade methamphetamine (0,006l/0,006kg)
If you look at that recipe thats what i mean out of whack the numbers are completely unrealisitic

**Comment by anoobindisguise** [comment]
I think it's likely the author thought acetone was measured in mL like most other chemicals are, it's just weird and is in 0.25L quantities for some silly reason.

**Comment by PatrikLundell** [comment]
A guess would be that the author assumed a "unit" of acetone was the same amount as a "unit" of the chemicals, i.e. 0.001 L rather than 0.25 L, i.e. that 150 ml was the intended amount, which I guess would result in the crude usage of 1 unit, as I don't think fractional units are supported.

However, I'd suggest trying to ask the recipe author.

**Comment by estebandellasilva** [comment]
@Nabo92 can you clarify the numbers? because i dont know what exact recipe you used.

If the does not answer would it be alright to assume that the recipe uses 1 unit of acetone?

**Comment by Nabo92** [comment]
> @Nabo92 can you clarify the numbers? because i dont know what exact recipe you used.
> 
> If he does not answer would it be alright to assume that the recipe uses 1 unit of acetone?

sure, you can fix it. The whole issue was what @PatrikLundell described (also some misconceptions about the code cause I'm a newbie :P)

**Comment by geek819024** [comment]
Can someone please can help me out to cook meth in high grade in"shake in bake method . 

Thanks for your help

**Comment by JRPirks** [comment]
I thought acetone was suppose to evaporate leaving a more pure methamphetamine? Quality over quality.
