### ISSUE TITLE
No way to undress a corpse in AIM

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#53352]
### Describe the bug

This makes looting corpses much more real-time intensive, having to `g`et individual stuff, especially when it's `Too big to pick up!` and you have to `w`ield each item to grab it, say to drop it into your car(t).

### Steps to reproduce

Kill someone, press / next to the corpse, see only the corpse.

### Expected behavior

Being able to dive into the "container".

### Screenshots

![screenshot-too](https://user-images.githubusercontent.com/31852/145660139-78f256e9-daf8-4385-9243-cfd822d7d3a1.png)

### Versions and configuration

Todays master.

**Comment by wapcaplet** [comment]
Similar to #50015 and #52221
