### ISSUE TITLE
Can't disassemble or cut kevlar items unless having a tool with "cut 2". Cut 2 tools don't exist. 

### ISSUE THREAD

**Issue by mkrutov** [CleverRaven/Cataclysm-DDA#53364]
### Describe the bug

Kevlar vest can be salvaged into components only with tool with "CUT" quality of 2. Combat boots can be disassembled only with "CUT" quality of 2. There are no items with CUT quality of 2 in vanilla. Supposedly it meant to be fine cutting instead of cutting.

### Steps to reproduce

1. Be unable to disassemble combat boots or cut kevlar vest.
2. Shut down game, change combat_knife CUT quality to 2.
3. Be able to disassemble combat boots and kevlar vest using new changed combat knife.

### Expected behavior

fine cut is probably what should have been used. 

### Screenshots

![Screenshot_20211211_142848](https://user-images.githubusercontent.com/48674477/145678420-3e7f0734-4dc5-4000-a00e-763833be3028.png)

### Versions and configuration

These are the outputs for the experimental build of commit 00a0caa64d7838379418150e9e3189840853beef

### Additional context

I've tried to find the definition of disassembly/cutting things in json but wasnt' able to, unfortunately.

**Comment by Zireael07** [comment]
Dupe of #53315

**Comment by mkrutov** [comment]
Whoops.
