### ISSUE TITLE
Can't reload grenade in underbarrel launcher mod

### ISSUE THREAD

**Issue by stemps** [CleverRaven/Cataclysm-DDA#53365]
### Describe the bug

When mounting an underbarrel grenade launcher (e.g. M320) to a rifle the grenade cannot be reloaded. It works fine when the mod is removed from the parent rifle, but once the mod is attached to the rifle, the grenades I have on person are not shown in the available ammo when reloading the rifle.

### Steps to reproduce

1. Attach an M320 mod to a rifle
2. Have 40x46mm grenades on person
3. Reload the rifle
4. the grenades are not offered as possible ammo

### Expected behavior

Grenades are shown as available ammo and I can reload the launcher

### Versions and configuration

- OS: MacOs
    - OS Version: Darwin stemps-ubuntu.localdomain 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
- Game Version: 0.F-4272-g40e9432310 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Blaze Industries [blazeindustries]
]

**Comment by wapcaplet** [comment]
Similar or duplicate of #53281

**Comment by wapcaplet** [comment]
This may have been fixed by #53102, can anyone confirm?

**Comment by stemps** [comment]
Confirmed... fixed by #53102
