### ISSUE TITLE
fire from dropped cigarette can destroy car's frame.

### ISSUE THREAD

**Issue by mkrutov** [CleverRaven/Cataclysm-DDA#53393]
### Describe the bug

I've been jittery and dropped my cigarette in unfortunate spot. That destroyed car's quarterpanel and frame in next few turns (car was already slightly damaged).

### Steps to reproduce

1. Drop lit cigarette on tile where there is a vehicle
2. Wait five minutes
3. Observe car parts damaged/destroyed.

### Expected behavior

Fire from cigarette should not be powerful enough to destroy cars.

### Versions and configuration

These are the outputs for the experimental build of commit 00a0caa
Linux

**Comment by NetSysFire** [comment]
Can not reproduce. What exact car was this and where exactly did you drop the cigarette?

![image](https://user-images.githubusercontent.com/59517351/145731433-638c14bf-55d5-44d5-9962-8fe9cf5e967f.png)

**Comment by mkrutov** [comment]
I've reproduced this by dropping a cigarette under frame which contained quarterpanel. It was a car from the frat boy start with some damage already. It is not instanteneous, in test world it took several minutes to damage car to XX from full strength quarterpanel.

**Comment by NetSysFire** [comment]
Nevermind. Spawning a lit cigarette from the debug menu is not actually lit. I just lit one manually and a part of the car exploded.

**Comment by NetSysFire** [comment]
![image](https://user-images.githubusercontent.com/59517351/145731605-9792e565-2047-4b01-8903-ab02ebfcb6c4.png)

Also interestingly enough, the quarterpanel was damaged but not the wheel. The tank is on the same tile and could have exploded, but did not. The grass on that tile is still perfectly fine, too.
