### ISSUE TITLE
Error when trying to continue an in-progress craft that can not be picked up

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#53413]
### Describe the bug

This seems to apply when you wear something that hinders the use of both hands, e.g a straw basket.

### Steps to reproduce

You need special stats for this one:

- Strength 10
- Dexterity 8
- Intelligence 8
- Perception 6

I am not sure which one of it is relevant here. Probably strength, but might also be dex.

1. Wear a straw basket.
2. Try to craft e.g carding paddles. Have the materials on the same tile.
3. Put it down to start working and interrupt the process (`.`). It can also tumble to the ground.
5. Activate the in-progress craft.

```
 DEBUG    : Failed to obtain target item

 FUNCTION : void avatar_action::use_item(avatar&, item_location&)
 FILE     : src/avatar_action.cpp
 LINE     : 1148
 VERSION  : 0.F
```

### Expected behavior

I *think* this happens because you can not pick up the item with one hand. It should not display this error but instead say why it could not let you continue crafting.

It did not error out when I removed the straw basket.

### Versions and configuration

- experimental

**Comment by NetSysFire** [comment]
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7711257/save.zip)

Here is a save for that. Just activate the in-progress carding paddles on the ground. If you put the straw basket down so you are not wearing it anymore and then activate the in-progress item, it works as intended.

**Comment by NetSysFire** [comment]
It might be, but I am not sure since a different part in the code is causing that issue apparently. It looks to be really similar though.

**Comment by hexagonrecursion** [comment]
Same function, same assertion. What is different?
