### ISSUE TITLE
Crash on switching to "Background" menu in character creation

### ISSUE THREAD

**Issue by DamienRoyan** [CleverRaven/Cataclysm-DDA#53415]
### Describe the bug

When creating the character and then switching to the Background tab, the game crashes

### Steps to reproduce

1) Go into character creation
2) Press (Tab) to until you reach the character "Background" tab

Then the game crashes

### Expected behavior

I should be able to continue character creation as how I did with in the previous tabs

### Screenshots

![image](https://user-images.githubusercontent.com/88375697/145807953-4bd9f38f-af58-4169-adb2-50624d3a57f4.png)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 14e0103 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7703464/crash.log)

**Comment by joshuataylor** [comment]
I have the same issue on Linux, with both gcc and clang.

**Comment by NetSysFire** [comment]
I wonder if this is somehow related to #53386.
