### ISSUE TITLE
Excessive "Your shivering prevents you from sleeping" messages.

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#53411]
### Describe the bug

When trying to sleep when you are too cold, there are waaaaaay too many messages. I am talking about about ~1000 per try.

### Steps to reproduce

1. Have a naked character on spring, day 61 at night.
2. Try to sleep in a shallow pit.
3. Witness the excessive messages.

![image](https://user-images.githubusercontent.com/59517351/145762784-ac2ffeeb-71f1-4bb1-af33-a21b0f9bc5f1.png)

### Expected behavior

This should be ratelimited.

### Versions and configuration

- experimental

**Comment by Fris0uman** [comment]
#61708 should make it so you only get a message once per hour at most
