### ISSUE TITLE
"Reload weapons" key loops reloading of antiseptic bottles

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#53418]
### Describe the bug

If you have multiple bottles of antiseptic, pressing the "reload weapons" key will eventually trap you in a loop of trying to reload antiseptic bottles from other antiseptic bottles, even if all the bottles are full.

Depending on conditions, this may take precedence over reloading your actual weapons/magazines. If I'm wielding my M4A1, pressing the key will reload my STANAG magazines, and only after that will I get stuck in the antiseptic loop. But if I'm wearing the M4A1 (w/strap), the antiseptic loop will start before my magazines get reloaded, meaning I have to select them manually through the "reload" or inventory menus.

### Steps to reproduce

1. Give yourself several bottles of antiseptic, an M4A1, some STANAG 30-round magazines and a pile of 5.56
2. Attempt to reload the magazines while wielding and not wielding the M4

### Expected behavior

Hammering "reload weapons" should reload all my weapons regardless of what I'm holding.

### Screenshots

![image](https://user-images.githubusercontent.com/5107449/145815741-25553ef6-2b29-48e4-afc6-72fd68b5749c.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 8b7a449 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by Hirmuolio** [comment]
It should work something like this:
Take a vector of all reloadable items.
Sort the vector to  this order: 

1.  Wielded item
2. Magazines compatible with the wielded item
3. Guns
4. Magazines in reload speed order

Then reload the first item from that list that has ammo available.

The code is here: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/game.cpp#L8629

The  sorting doesn't seem to be working and the wielded item is not the first. (also the last part will include all non-magazines too).

**Comment by Terrorforge** [comment]
Well that last part should ideally be split into magazines for guns and then everything else. In fact, I'm not sure "everything else" should be in there at all. That just seems like an easy way to end up accidentally reloading your headlamp with disposable batteries all the time - and besides, it's the "reload weapons" hotkey, not the "reload everything" hotkey.

But at any rate, the order isn't the big problem right now. The problem is that if you have two or more containers that can be reloaded, and allow you to reload _from_ that container, you get stuck in a loop of reloading one into the other. Or possibly just reloading the one over and over, because like I said it seems to happen even when they're full.

**Comment by Hirmuolio** [comment]
On closer look the sorting seems to be fine and the wielded item gets reloaded first. I'll just massage the sorting a bit so non-gun/magazines are ignored here.
