### ISSUE TITLE
Errors "No mapgen terrain exists for ..." occur when using the specified mods

### ISSUE THREAD

**Issue by SpiritFoxs** [CleverRaven/Cataclysm-DDA#53419]
### Describe the bug

If you use this list of mods, then errors occur:
<img width="960" alt="123" src="https://user-images.githubusercontent.com/44747644/145817286-b8fb15da-931d-49c7-b222-d693ff4ad824.png">
<img width="960" alt="234" src="https://user-images.githubusercontent.com/44747644/145818226-3060c1e7-f55c-4ba4-a780-9ccbeea33288.png">

### Steps to reproduce

1. Create a world with the specified list of mods;
2. Try to create or load a character.

### Expected behavior

There are no such errors

### Versions and configuration

8b7a449 (2021-12-13-0951)

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7704016/debug.log)

**Comment by Night-Pryanik** [comment]
Could you please post screenshot of the error?

**Comment by SpiritFoxs** [comment]
<img width="960" alt="456" src="https://user-images.githubusercontent.com/44747644/145843136-cdca51ab-ea78-4eca-ac55-9037d6ffd5d7.png">

**Comment by SpiritFoxs** [comment]
Each is repeated 3-4 times in a row.

**Comment by Night-Pryanik** [comment]
Could you please try to start the game without any mods so we could be sure that it's not the vanilla bug?

**Comment by SpiritFoxs** [comment]
Here's what it gave me on trying to start ONLY CDDA:
<img width="960" alt="1" src="https://user-images.githubusercontent.com/44747644/145849195-0ee49909-556c-4ec8-93a6-54e1ab0b750e.png">
<img width="960" alt="2" src="https://user-images.githubusercontent.com/44747644/145849198-d545334a-0162-48a4-a166-c98ecc4e0ce3.png">
<img width="960" alt="3" src="https://user-images.githubusercontent.com/44747644/145849202-0fee838a-ffd4-4141-8ca2-d4bacbdcf44d.png">
<img width="960" alt="4" src="https://user-images.githubusercontent.com/44747644/145849205-d37e615a-237b-4b69-bcb2-6b6f47d3b7b7.png">
<img width="960" alt="5" src="https://user-images.githubusercontent.com/44747644/145849208-1dceac79-75af-453b-b322-118a1b95cfd1.png">
<img width="960" alt="6" src="https://user-images.githubusercontent.com/44747644/145849210-7fbcfc9e-94aa-459a-9b8d-b650cada05ff.png">
<img width="960" alt="7" src="https://user-images.githubusercontent.com/44747644/145849212-337e0228-2c15-4ee5-b511-e753a405baea.png">
<img width="960" alt="8" src="https://user-images.githubusercontent.com/44747644/145849215-8f526b04-8d27-4b2c-9fd0-148aac4f6fb6.png">
<img width="960" alt="9" src="https://user-images.githubusercontent.com/44747644/145849218-db1e11c7-4caa-4d80-89c4-957d37daf04a.png">

**Comment by SpiritFoxs** [comment]
I checked for "Chibi_UltiCa" and "UltiCa". The errors are the same.

**Comment by JyeGuru** [comment]
Found this thread when looking for a solution to this same error. After some testing, it seems to be caused by the Graphical Overmap mod. Default settings on latest experimental generate a world fine, but as soon as Graphical Overmap is added it generates the same list of errors in the original post.

Working config (default):
![image](https://user-images.githubusercontent.com/5215014/146034038-7a9c2fbd-4e17-495e-8891-176aa0b5b947.png)

Minimal failing config:
![image](https://user-images.githubusercontent.com/5215014/146033941-69d965d8-4faa-4494-9da4-386c1f0f76df.png)

Also confirmed that removing the Graphical Overmap mod from the OP mod list results in a successful world generation.

**Comment by hexagonrecursion** [comment]
Confirmed.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: cfc00fa [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap]
]

Errors as text for convenience:

```
17:59:18.586 ERROR : src/overmap.cpp:1003 [void overmap_terrains::check_consistency()] No mapgen terrain exists for "farm_lot_wire_turn_uni".
18:00:19.405 ERROR : src/overmap.cpp:1003 [void overmap_terrains::check_consistency()] No mapgen terrain exists for "farm_lot_wire_turn_uni".
18:00:33.568 ERROR : src/overmap.cpp:1003 [void overmap_terrains::check_consistency()] No mapgen terrain exists for "farm_lot_wire_turn_uni".
18:00:33.568 ERROR : src/overmap.cpp:1003 [void overmap_terrains::check_consistency()] No mapgen terrain exists for "farm_lot_wire_turn_uni".
18:00:33.568 ERROR : src/overmap.cpp:1003 [void overmap_terrains::check_consistency()] No mapgen terrain exists for "farm_lot_wire_straight_h_open".
[ Previous repeated 2 times ]
18:00:33.568 ERROR : src/overmap.cpp:1003 [void overmap_terrains::check_consistency()] No mapgen terrain exists for "farm_lot_wire_straight_h_open".
18:00:33.568 ERROR : src/overmap.cpp:1003 [void overmap_terrains::check_consistency()] No mapgen terrain exists for "farm_lot_wire_turn_h_open".
[ Previous repeated 2 times ]
18:00:33.568 ERROR : src/overmap.cpp:1003 [void overmap_terrains::check_consistency()] No mapgen terrain exists for "farm_lot_wire_turn_h_open".
18:00:33.568 ERROR : src/overmap.cpp:1003 [void overmap_terrains::check_consistency()] No mapgen terrain exists for "mansion_c".
[ Previous repeated 2 times ]
18:00:33.568 ERROR : src/overmap.cpp:1003 [void overmap_terrains::check_consistency()] No mapgen terrain exists for "mansion_c".
18:00:33.568 ERROR : src/overmap.cpp:1003 [void overmap_terrains::check_consistency()] No mapgen terrain exists for "mansion_c_up".
[ Previous repeated 2 times ]
18:00:33.568 ERROR : src/overmap.cpp:1003 [void overmap_terrains::check_consistency()] No mapgen terrain exists for "mansion_c_up".
18:00:33.568 ERROR : src/overmap.cpp:1003 [void overmap_terrains::check_consistency()] No mapgen terrain exists for "mansion_c_dn".
[ Previous repeated 2 times ]
18:00:33.568 ERROR : src/overmap.cpp:1003 [void overmap_terrains::check_consistency()] No mapgen terrain exists for "mansion_c_dn".
18:00:33.568 ERROR : src/overmap.cpp:1003 [void overmap_terrains::check_consistency()] No mapgen terrain exists for "mansion_+".
[ Previous repeated 2 times ]
18:00:33.568 ERROR : src/overmap.cpp:1003 [void overmap_terrains::check_consistency()] No mapgen terrain exists for "mansion_+".
18:00:33.568 ERROR : src/overmap.cpp:1003 [void overmap_terrains::check_consistency()] No mapgen terrain exists for "mansion_+_up".
[ Previous repeated 2 times ]
18:00:33.568 ERROR : src/overmap.cpp:1003 [void overmap_terrains::check_consistency()] No mapgen terrain exists for "mansion_+_up".
18:00:33.568 ERROR : src/overmap.cpp:1003 [void overmap_terrains::check_consistency()] No mapgen terrain exists for "mansion_+_dn".
[ Previous repeated 2 times ]
18:00:33.568 ERROR : src/overmap.cpp:1003 [void overmap_terrains::check_consistency()] No mapgen terrain exists for "mansion_+_dn".
18:00:33.568 ERROR : src/overmap.cpp:1003 [void overmap_terrains::check_consistency()] No mapgen terrain exists for "mansion_t".
[ Previous repeated 2 times ]
18:00:33.568 ERROR : src/overmap.cpp:1003 [void overmap_terrains::check_consistency()] No mapgen terrain exists for "mansion_t".
18:00:33.568 ERROR : src/overmap.cpp:1003 [void overmap_terrains::check_consistency()] No mapgen terrain exists for "mansion_t_up".
[ Previous repeated 2 times ]
18:00:33.568 ERROR : src/overmap.cpp:1003 [void overmap_terrains::check_consistency()] No mapgen terrain exists for "mansion_t_up".
18:00:33.568 ERROR : src/overmap.cpp:1003 [void overmap_terrains::check_consistency()] No mapgen terrain exists for "mansion_t_dn".
[ Previous repeated 2 times ]
18:00:33.568 ERROR : src/overmap.cpp:1003 [void overmap_terrains::check_consistency()] No mapgen terrain exists for "mansion_t_dn".
18:00:33.568 ERROR : src/overmap.cpp:1003 [void overmap_terrains::check_consistency()] No mapgen terrain exists for "mansion_entry".
[ Previous repeated 2 times ]
18:00:33.568 ERROR : src/overmap.cpp:1003 [void overmap_terrains::check_consistency()] No mapgen terrain exists for "mansion_entry".
18:00:33.568 ERROR : src/overmap.cpp:1003 [void overmap_terrains::check_consistency()] No mapgen terrain exists for "mansion_entry_up".
[ Previous repeated 2 times ]
18:00:33.568 ERROR : src/overmap.cpp:1003 [void overmap_terrains::check_consistency()] No mapgen terrain exists for "mansion_entry_up".
18:00:33.568 ERROR : src/overmap.cpp:1003 [void overmap_terrains::check_consistency()] No mapgen terrain exists for "mansion_entry_dn".
[ Previous repeated 2 times ]
18:00:33.568 ERROR : src/overmap.cpp:1003 [void overmap_terrains::check_consistency()] No mapgen terrain exists for "mansion_entry_dn".
18:00:33.568 ERROR : src/overmap.cpp:1003 [void overmap_terrains::check_consistency()] No mapgen terrain exists for "mansion_wild".
[ Previous repeated 2 times ]
18:00:33.569 ERROR : src/overmap.cpp:1003 [void overmap_terrains::check_consistency()] No mapgen terrain exists for "mansion_wild".
18:00:33.569 ERROR : src/overmap.cpp:1003 [void overmap_terrains::check_consistency()] No mapgen terrain exists for "mansion_wild_up".
[ Previous repeated 2 times ]
18:00:33.569 ERROR : src/overmap.cpp:1003 [void overmap_terrains::check_consistency()] No mapgen terrain exists for "mansion_wild_up".
18:00:33.569 ERROR : src/overmap.cpp:1003 [void overmap_terrains::check_consistency()] No mapgen terrain exists for "mansion_wild_dn".
[ Previous repeated 2 times ]
18:00:33.569 ERROR : src/overmap.cpp:1003 [void overmap_terrains::check_consistency()] No mapgen terrain exists for "mansion_wild_dn".
```

**Comment by hexagonrecursion** [comment]
This was likely caused by #53117
