### ISSUE TITLE
I can't start the game with the character I created yesterday. 

### ISSUE THREAD

**Issue by HrodebertRex** [CleverRaven/Cataclysm-DDA#53412]
### Describe the bug

Throws  out of the game. After 4 crashes.

### Steps to reproduce

1) I choose to start the world and wait for the download of files(world name :Округ Кнокс).
2) At the end of the download, 4 errors take off. 

Game version 0.F-3
The experimental version and 0.F-2 has the same error. 

### Expected behavior

Normal loading was expected.

### Screenshots

![image](https://user-images.githubusercontent.com/96046979/145779490-57fb168d-3bc4-43a5-a092-f91e81cd4d3b.png)

![image](https://user-images.githubusercontent.com/96046979/145779530-5dc174bf-d4cc-4bf4-96c9-f81a03f2b2b5.png)

![image](https://user-images.githubusercontent.com/96046979/145779559-c6cce4ad-ab10-4141-a297-be2cd4f19e33.png)

![image](https://user-images.githubusercontent.com/96046979/145779692-21bd45f7-e583-4f44-9d9a-d7d55d0c7f50.png)

### Versions and configuration

-Windows 10
-in game language : Russian
-Game version 0.F-3
The experimental version and 0.F-2 has the same error. 

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7702357/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7702358/debug.log)

### Additional context

My world save 
[Округ Кнокc.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7702453/c.zip)
My config
[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7702496/config.zip)

**Comment by Hirmuolio** [comment]
The errors look same as in #53312. So the game most likely autosaved at bad time and now can't resume.

**Comment by BrettDong** [comment]
Fixed in #54323.
