### ISSUE TITLE
Display furniture/terrain description in Look Around mode

### ISSUE THREAD

**Issue by nexusmrsep** [CleverRaven/Cataclysm-DDA#53427]
### Is your feature request related to a problem? Please describe.

You have to `Look Around` and then `'E'xamine` things to see the description of furniture and terrain.
Many descriptions are too well hidden and I'm under impression that some people don't even know they exist.

### Solution you would like.

In most cases there is enough real estate in the `Look Around` mode to fit descriptions of furniture & terrain occupying the tile.
If there are both present furniture's description could be prioritized.

### Describe alternatives you have considered.

If the idea is not feasible then at least the `'e'xamnine` option should be pronounced on the border or at the bottom of the `Look Around` frame.

**Comment by I-am-Erk** [comment]
Yes please, I spend a lot of time adding puns and Easter eggs in those descriptions.
