### ISSUE TITLE
Instead of a improvised lockpick, he tries to use the integrated multitool to open the door

### ISSUE THREAD

**Issue by SpiritFoxs** [CleverRaven/Cataclysm-DDA#53421]
### Describe the bug

After the last update, instead of using a improvised lockpick to open the door (on "e"), for some reason he tries to use the integrated multitool.

### Steps to reproduce

1. Create or load a character;
2. Install CBM: integrated multitool;
3. Create an improvised lockpick;
4. Find a closed door and try to open it on "e".

### Expected behavior

Automatic use of the right tool.

### Screenshots

<img width="960" alt="345" src="https://user-images.githubusercontent.com/44747644/145833104-a9d6e117-36a4-40f9-b4f5-828565048f43.png">
<img width="960" alt="234" src="https://user-images.githubusercontent.com/44747644/145833811-9ecf5a9d-6915-4235-b282-8f423ada2bcd.png">

### Versions and configuration

8b7a449 (2021-12-13-0951)

**Comment by catdach** [comment]
IIRC this also happens when you have any type of crowbar in your inventory. The game seems to prioritize prying open doors rather than picking them.

**Comment by Terrorforge** [comment]
Which is especially annoying when you're carrying a hammer, which cannot pry open doors, but still takes priority over lockpicks
