### ISSUE TITLE
When loading a save from a previous version 'invalid overmap special id'

### ISSUE THREAD

**Issue by SpiritFoxs** [CleverRaven/Cataclysm-DDA#53423]
### Describe the bug

When loading a save from a previous version, it gives several errors.
The world is also from the previous version.
P.S. The errors in the screenshots are repeated 3-4 times.

### Steps to reproduce

1. Create a world and save in the previous version;
2. Update the game;
3. Load the game.

### Expected behavior

The game does not show these errors.

### Screenshots

<img width="960" alt="12" src="https://user-images.githubusercontent.com/44747644/145847921-d93465c1-0c82-411f-a7f5-fa846b9847b5.png">
<img width="960" alt="2" src="https://user-images.githubusercontent.com/44747644/145848030-9e3b0e25-196c-4da7-b112-79849ed042ed.png">
<img width="960" alt="3" src="https://user-images.githubusercontent.com/44747644/145848094-1b68d7c1-34b4-4905-9868-45e8152151e2.png">

### Versions and configuration

8b7a449 (2021-12-13-0951)

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7705223/debug.log)

**Comment by wapcaplet** [comment]
Similar to #53224 and #51856

**Comment by BaumgeistOne** [comment]
"bog" and "basin" - those errors show up in my game too. I updated yesterday.

**Comment by Night-Pryanik** [comment]
These errors can be safely ignored. They only occur in existing saves, in new worlds they won't appear.

**Comment by wapcaplet** [comment]
> These errors can be safely ignored. They only occur in existing saves, in new worlds they won't appear.

If these are like the other issues I linked, they appear every time the game is loaded, and players who migrate their game from 0.F to 0.G experimental will see these errors forever afterward. They can indeed be ignored and seem harmless, but should be fixed before 0.G release.

**Comment by wapcaplet** [comment]
These errors are still occurring when loading the save game I attached above: [BikeShop0F.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7712099/BikeShop0F.zip)

```
Invalid overmap special id "basin"
Invalid overmap special id "bog"
```

(and many others) 

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-4540-g8b32af6577 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]
