### ISSUE TITLE
Can't autopickup from corpse pockets (or other containers)

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#53425]
### Describe the bug

It's always been annoying that you can't autopickup items from inside containers, but it's become a serious problem now that corpses are treated as containers. I loved autopickup as it was, because it saved me the tedious task of painstaking combing over every tile of a zombie massacre for rare but valuable drops like autoclave pouches and ID cards, but that functionality no longer exists.

### Steps to reproduce

Kill a zombie
Attempt to autopickup something it is carrying
Do not pick it up automatically

### Expected behavior

I should be able to autopickup zombie drops somehow, because that's the most important function of that feature. If at all possible, let us autopickup things from inside containers in general, because I'm pretty tired of my inventory filling up with prescription bottles containing one or two pills, and not even being able to sort where those bottles go.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 8b7a449 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by bombasticSlacks** [comment]
this isn't exactly what you want but loot zones sorting does this now #53346

**Comment by KurzedMetal** [comment]
I'm missing the autopickup feature a lot. I use it during my gameplay.
I think autopickup has been broken since #50987

**Comment by Terrorforge** [comment]
Well it's not _broken_, technically. It still works for random items in the world, but it never worked for items inside containers, and since all the zombie loot is now in their corpse containers, you can't autopick it any more.

**Comment by Jan-Blasiak** [comment]
> Well it's not _broken_, technically. It still works for random items in the world, but it never worked for items inside containers, and since all the zombie loot is now in their corpse containers, you can't autopick it any more.

Well, that makes it almost completely useless now.
