### ISSUE TITLE
Rollerblade movement cost on "flat roof" is 280+

### ISSUE THREAD

**Issue by mkrutov** [CleverRaven/Cataclysm-DDA#53434]
### Describe the bug

Moving on flat roof in rollerblades uses same movement cost as on grass or dirt.

### Steps to reproduce

1. Equip rollerblades.
2. get onto roof
3. move around

### Expected behavior

It should be same as asphalt really

### Versions and configuration

These are the outputs for the experimental build of commit 00a0caa
Linux

**Comment by ZhilkinSerg** [comment]
Only terrains with `ROAD` flag are considered good enough for movement cost reduction for items with `ROLLER_INLINE`, `ROLLER_QUAD` or `ROLLER_ONE` flag. Flat roof only has `FLAT` flag.

**Comment by mkrutov** [comment]
Its' weird that flat roof is not considered good enough for rollerblades but house parquet floor is

**Comment by Max17U** [comment]
Is it because the roof could be even made from different materials, like straw? So the check should be done only on the concrete roof i guess. Correct me if i'm wrong

**Comment by matshou** [comment]
Perhaps a good solution would be to create a new terrain flag called `ROUGH` and allow rollerblades to move with full speed on `FLAT` and non `ROUGH` terrain.

**Comment by matshou** [comment]
After reviewing the code the best solution would be to add `ROAD` flag to appropriate roof tiles. 

Currently that flag affects the following things:

- Speed of rollerblades.
- Movability of furniture.
- Likelihood of bashing surfaces.
