### ISSUE TITLE
Some items don't display body locations in sorting menu

### ISSUE THREAD

**Issue by bombasticSlacks** [CleverRaven/Cataclysm-DDA#53459]
### Describe the bug

When wearing certain conflicting items it doesn't give you the list of effected body parts.

### Steps to reproduce

1. start a new game
2. spawn 2 US ballistic vests
3. wear them both
4. open sorting manager

### Expected behavior

The limbs should be displayed

### Screenshots

Current
![image](https://user-images.githubusercontent.com/4514073/146078867-910d3315-1dcb-4bd9-8595-edc11df6a090.png)

What normally shows up:
![image](https://user-images.githubusercontent.com/4514073/146078940-b924887d-5f4a-4bc2-b71f-055b67f440ae.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 40e9432 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

I bet I broke this with sub locations.

**Comment by ZeroInternalReflection** [comment]
I believe this was fixed in #58463.  I can't guarantee there aren't other edge cases hiding out there, but the example of two ballistic vests now correctly flags the torso as being extra encumbered.

**Comment by bombasticSlacks** [comment]
yup I think you are right I'm closing this
