### ISSUE TITLE
Inaccurate description in makeshift crowbar Use item menu

### ISSUE THREAD

**Issue by foul-fortune-feline** [CleverRaven/Cataclysm-DDA#53451]
### Describe the bug

In the (a)ctivate menu, the makeshift crowbar's action description is "Pry crate, windows, door or nails", despite makeshift crowbars no longer being capable of prying open windows. The action description should likely be updated to reflect this change, if it's technically feasible.

### Steps to reproduce

1) Acquire a makeshift crowbar
2) Open the Use item menu (usually by pressing the "a" key)

### Expected behavior

One would expect the action description in the "Use item" menu for "makeshift crowbar" to only include actions it's capable of

### Screenshots

![image](https://user-images.githubusercontent.com/56287293/146064943-bd7ac3e2-00c3-41a3-9343-889557aed1e1.png)

### Versions and configuration

- OS: Pop!_OS 21.04
- Game Version: cdda-experimental-83d3de8
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: dda, package_bionic_professions, no_npc_food, no_fungal_growth, cbm_slots

**Comment by catdach** [comment]
So this is the action description for all tools the prying and nail-prying quality. As far as I know, no windows can currently be opened with level 1 prying witch means the makeshift crowbar, makeshift hammer, regular hammer, and the...firearm repair kit and gunsmith repair kit? items can't pry open windows. It seems misleading to leave it in, but prying open windows is part of the prying quality so it almost feels disingenuous to take it out. How would a new player know that a tool with higher level prying would even be capable of opening windows? It's not like the tools aren't _potentially_ capable of opening windows despite being _functionally_ incapable of doing so. As far as I know there are no tools in the game that change their action description based on tool quality level. What to do hmm... 🤔

**Comment by Max17U** [comment]
In my opinion, if the action is "doable", the description should stay there, even if you know (by reading code or log) that you will fail 100% of the times. The description just tells you what kind of action you can do with the item, not if the action will succeed or not. Maybe in the future there will be a "damaged window" that could be pried with a level 1 prying item.
OR we ( I ) could just add another "action description" for all those tools that aren't able to pry windows. 
By the way are you sure windows can't be pried with a level 1 prying item? Is it a new thing or was always like this? I don't remember being able to pry a window with a makeshift bar on 0.C version, but i could be wrong.

**Comment by JohnC3** [comment]
I remember being able to buy windows open with the makeshift crowbar in 2019. It had a risk of smashing the glass in the window that I don’t think the real crowbar had. 

I don’t really follow the rest of the reasoning either if something will 100% always fail to do something it clearly cannot do that thing. 

Do you mean more that someone who doesn’t know might like think it can do the thing but in reality it can’t?

**Comment by LeahLuong** [comment]
Even real crowbars occasionally break windows.

I have to agree w/ the OP on this 1: this seems like a bug. Using terms like "potentially" or "doable" seems ludicrous when there is a 100% fail rate using the makeshift crowbar. There is no potential to do something w/ a 0% success chance, by definition. There is no doing something that can't be done, by definition.

This seems like an easy fix, even if "level 1 prying" needs its own action description. Perhaps Examining windows from their pryable side should also include some text alluding to their pryability.

**Comment by Max17U** [comment]
> Do you mean more that someone who doesn’t know might like think it can do the thing but in reality it can’t?

Yes, I meant this. Iirc there are games that give you the possibility to make “that specific action” without actually ever giving any results.
Anyway I was more like playing the devil’s advocate, and giving another point of view that could have been the reason why it’s like this. But probably it’s just a bug or a “not updated code” that does not reflect the new mechanics.
