### ISSUE TITLE
Using hammer to pry open door, but showing container

### ISSUE THREAD

**Issue by DamienRoyan** [CleverRaven/Cataclysm-DDA#53469]
### Describe the bug

Instead of saying that I am using my hammer to pry open the door, it says I am using my military rucksack (which contains the hammer) to pry open the door

### Steps to reproduce

1. Acquire hammer and military rucksack
2. Try to pry open a locked door
3. Instead of saying which tool is being used, it will name the military rucksack

### Expected behavior

Instead of "using your military rucksack | |" it should say "using your hammer"

### Screenshots

![image](https://user-images.githubusercontent.com/88375697/146185421-8ac51ea2-eed8-4b82-90e0-e2a744605892.png)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: c145d55 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Extra Mutated Scenarios [extra_mut_scens],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Terrorforge** [comment]
Can confirm, this has happened and continues to happen to me
