### ISSUE TITLE
No afs UPS energy weapons

### ISSUE THREAD

**Issue by Proxima-b** [CleverRaven/Cataclysm-DDA#53463]
### Describe the bug

since the item migration change the ups energy weapons to those which use energy cell, the original UPS weapon cannot be found in the game.

### Steps to reproduce

1. Get A-7 laser rifle
2. It can only use energy cell

### Expected behavior

Make a UPS mods for afs energy weapon so it can use UPS energy again.

### Versions and configuration

latest exprimental

**Comment by Maleclypse** [comment]
Not a bug. Energy weapons are balanced differently in Aftershock and one of those differences is limited ammunition.

**Comment by Proxima-b** [comment]
> Not a bug. Energy weapons are balanced differently in Aftershock and one of those differences is limited ammunition.

However there should be a way to let them use UPS energy w/ modifications just like those tools do, it could be difficult but not impossible.
Using afs energy cells only basically means I can't use those weapons. Because in my 200+ hrs of playthru with aftershock, I have never once seen one of those energy cell, nor did I acquire any recipe for of them.

**Comment by Maleclypse** [comment]
Then they need to spawn more energy cells because I know the other Aftershock authors have said they will never make them UPS moddable.  Also they spawn most frequently  in formless ruins.
