### ISSUE TITLE
Currency Haggling

### ISSUE THREAD

**Issue by AdamChirnside** [CleverRaven/Cataclysm-DDA#53467]
### Describe the bug

When "buying" currency from NPCs, the player's Social skill is checked and the price is adjusted. When "selling" currency, the standard rate is correctly used.

### Steps to reproduce

1. Spawn an NPC and give them any currency item, or go to a trading hub location
2. Trade with them

### Expected behavior

I expect currency items to have a standardized value regardless of who holds them

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 83d3de8 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by dseguin** [comment]
This should be an easy fix, if anyone wants to give it a go:
```diff
diff --git a/src/npctrade.cpp b/src/npctrade.cpp
index 15ef527965..f436943de8 100644
--- a/src/npctrade.cpp
+++ b/src/npctrade.cpp
@@ -152,7 +152,7 @@ int npc_trading::adjusted_price( item const *it, int amount, Character const &bu
                                  Character const &seller )
 {
     double const adjust = npc_trading::net_price_adjustment( buyer, seller );
-    faction const *const fac = buyer.get_faction();
+    faction const *const fac = buyer.is_npc() ? buyer.get_faction() : seller.get_faction();
 
     int price = it->price_no_contents( true );
     if( it->count_by_charges() and amount >= 0 ) {
```
