### ISSUE TITLE
STANAG drum won't go in chest rig despite fitting

### ISSUE THREAD

**Issue by YourCompanionCube** [CleverRaven/Cataclysm-DDA#53472]
### Describe the bug

i'm unable to insert 50 round STANAG drums into a chest rig despite the pockets saying they're large enough in both size and weight

### Steps to reproduce

spawn both items, try to insert magazine (full or empty)

### Expected behavior

that pockets would be able to hold items within their volume/weight/length limits

### Screenshots

Pockets:
![image](https://user-images.githubusercontent.com/26364270/146226289-3533a5a2-3344-470e-958e-a638b667a879.png)

Empty Magazine:
![image](https://user-images.githubusercontent.com/26364270/146226473-9fddc604-f675-4ccf-84ea-54fdfb4d756b.png)

Full Magazine:
![image](https://user-images.githubusercontent.com/26364270/146226539-71678912-e9e7-485c-be03-7b7711e5368b.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 373cf4e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Stats Through Skills [StatsThroughSkills],
    Useful Helicopters Experimental [useful_helicopters],
    SpeedyDex [speedydex],
    Extra Mutated Scenarios [extra_mut_scens],
    No Rail Stations [No_Rail_Stations]
]

**Comment by Hirmuolio** [comment]
Those pockets are restricted to compact magazines.
#53420 should make the restriction visible in the item info.

**Comment by YourCompanionCube** [comment]
cool, it makes some sense to me that these don't fit in normal mag pouches, it was just confusing since the restrictions tab was blank.

i'll close this when that gets merged

**Comment by bombasticSlacks** [comment]
I've set it so that it getting merged will auto close this :)
