### ISSUE TITLE
Random NPC spawn in unsafe locations

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#53477]
### Describe the bug

Example: random NPCs can spawn at a military helipad. As soon as they enter the reality bubble they commit suicide by walking into the line of fire of a turret.

### Steps to reproduce

1. Play the game until a random NPC spawns at a military helipad
2. Approach the helipad until the NPC is in the reality bubble
3. Hear "Hostile detected"
4. See the NPC get shot

### Expected behavior

Do not spawn random NPCs where they will immediately get themselves killed.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: cf9e61e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Setting random NPC spawn time very low should help reproducing this. Ditto editing JSON to boost helipad spawn rate.

**Comment by LeahLuong** [comment]
I kinda like how NPC's can spawn in unsafe places but I wish their AI were better. Getting an NPC out of a jam is good story-building. It's lame if they won't flee or take cover when the odds are against them. The situation you describe sounds hopeless & should prob be ruled out for NPC spawning. Would be cool if you could pull up in your vehicle, cover them from the turret fire, & have them jump in to make a clean getaway.
