### ISSUE TITLE
ascend/descend stairs with shift+up and shift+down

### ISSUE THREAD

**Issue by rumly111** [CleverRaven/Cataclysm-DDA#53480]
### Is your feature request related to a problem? Please describe.

If you move around mostly with your arrow keys, reaching '>' and '<' keys can be bothersome. Just like you can move diagonally with Shift+Left, Control+Left etc, I'd like to move/look/peek up and down with Shift+Up and Shift+Down

### Solution you would like.

I would like it if pressing Shift+UpArrow had the same effect as pressing '<' , also Shift+DownArrow = '>'

### Describe alternatives you have considered.

Maybe it can be achieved by editing keybindings.json ? There is something related to "mod", but I don't really know how it works. Maybe I'd need to switch input method from "keysyms" to "keycodes" in settings? Tell me if you know how this works.

### Additional context

It wasn't such a problem when you couldn't look/peek up and down with "x", but since it's a possibility now and I do it often, I noticed how annoying it is to move my hand from the arrow keys to '>' or '<'

**Comment by wapcaplet** [comment]
I don’t think there is currently a way to add a shift-arrow keybinding, but it might be possible to change that.

The PageUp / PageDown keys should also work for traversing stairs with default key bindings, and are typically near the arrow keys and numeric keypad on full-size US keyboards.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
