### ISSUE TITLE
Items with FIRE flag are not recognized as a source of flame

### ISSUE THREAD

**Issue by lapis413** [CleverRaven/Cataclysm-DDA#53482]
### Describe the bug

When an everburning torch is lit, it's description has the note "This item counts as fire for crafting purposes" but does not appear to fulfill that for any crafting recipes.

### Steps to reproduce

1. Spawn an everburning torch item
2. Activate the torch
3. Check torch's description to confirm it should function as fire
4. Check crafting recipes for anything that requires fire

### Expected behavior

Either for the item to serve as fire, whether in all recipes or only certain ones, or for the entry in the item's description to be removed if it is not intended.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 9b60b4c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by catdach** [comment]
This isn't exclusive to magiclysm, the refillable lighter (lit) has the same problem.

**Comment by Night-Pryanik** [comment]
Fixed by #62129.
