### ISSUE TITLE
[Magiclysm] "Blood" is not being picked up as a crafting item for certain recipes

### ISSUE THREAD

**Issue by lapis413** [CleverRaven/Cataclysm-DDA#53481]
### Describe the bug

The item "blood" seems to not be counted as an item in certain recipes, the only one I've tested is the scroll of acid resistance.

### Steps to reproduce

1. Obtain and read the "Black Dragon:Swamp Ruins" book to gain the scroll of acid resistance recipe
2. Bleed an animal corpse into a container
3. Check recipe to see blood is not recognized

### Expected behavior

Either for the blood to work as a crafting ingredient, or for it to be removed from the recipe if it is not intended to work.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 9b60b4c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by catdach** [comment]
So, there are multiple items named "blood", one being more generic and one being specific to animals. It seems that all the Magiclysm recipes use only the generic blood item.

**Comment by hexagonrecursion** [comment]
Confirmed (used blood from a cow). For reference: the option to bleed a corpse can be found in the [B]utcher menu (I did not know that).

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: cfc00fa [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]
]
