### ISSUE TITLE
Fatal error in the Electromagnetic Leak CBM: value outside supported range

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#53495]
### Describe the bug

See title.

### Steps to reproduce

1. Try to load a save.
2. Fatal error.

```
 DEBUG    : Error: Json error: usr/share/cataclysm-dda/json/bionics.json:1,679:16: value outside supported range

    "type": "bionic",
    "name": { "str": "Electromagnetic Leak" },
    "capacity":
               ^
                "-25 kJ",
    "dupes_allowed": true,
    "description": "A broken implant that sends electromagnetic impulses that reduce other implants capacity to store charge.",


 FUNCTION : bool main_menu::load_character_tab(bool)
 FILE     : src/main_menu.cpp
 LINE     : 1069
 VERSION  : 0.F
```

### Expected behavior

Seems to be introduced by #53165

### Versions and configuration

- experimental, as of 4ac5f7158aefb817e286c7dac95d68e252889e8a

**Comment by GoLoT** [comment]
I can't reproduce it on current experimental. I double checked and there is only one place where capacity is assigned that I can find:
https://github.com/CleverRaven/Cataclysm-DDA/blob/9fe84e0cfcbdeb633585bf597febb821b1de1ad8/src/bionics.cpp#L330

Previously it had a lower limit of 0kJ which caused this error, but the limit it was removed in #53165. The default lower limit should be `units::energy_min` so unless that changed in a specific build I don't see any reason for it to fail. Can someone else confirm that they have this issue?

As a workaround, I suggest changing the "-25 kJ" to 0.

**Comment by NetSysFire** [comment]
I think the reason it failed was because github builds were broken in some way. I just built it again and it magically started to work.
