### ISSUE TITLE
Eating stack of fresh corn cob results in stack of empty cobs

### ISSUE THREAD

**Issue by zamp** [CleverRaven/Cataclysm-DDA#53491]
### Describe the bug

Eating stack of fresh corn cob results in stack of empty cobs.
Player only receives kcal for one cob.

### Steps to reproduce

1. Spawn in 1000 fresh corn cobs
2. Use eat action once on stack of 1000 cobs
3. Note amount of empty cobs.

### Expected behavior

Only a single empty cob is produced per consume or player receives kcal for all consumed cobs.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 83d3de8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by hexagonrecursion** [comment]
Confirmed. Possibly related: eating 1000 corn cobs does not add kCal to stomach contents.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: cfc00fa [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by morthein** [comment]
#50002
