### ISSUE TITLE
"You can't craft this right now" dynamic block

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#53498]
### Is your feature request related to a problem? Please describe.

We are running into consistent problems with people trying to craft endgame recipes with midgame skills, finding it very hard, and not knowing why. I believe the key reason for this is the absolute information overload of the crafting window making it hard for people to parse all the data. That's a hard problem to resolve, but there is a good argument that, when it becomes simply impractical to attempt to craft a thing, we probably don't have to let you try. The number of use cases for it become vanishingly small.

### Solution you would like.

Rather than a hard-block of "you need x proficiencies to attempt this", I recommend we develop a dynamic block based on your chance of failing a crafting attempt, from all causes. Some things that can influence this include
- your current mental state
- pain, fatigue, light levels
- low practical skill but high knowledge granting access to recipe
- lack of proficienices

We can probably do some refactoring in [crafting_success_roll](https://github.com/CleverRaven/Cataclysm-DDA/blob/cfc00fa884fe9d4d623537c83b6b67550c166e32/src/crafting.cpp#L984) to pull the actual modifiers out to another function or set of functions (a good refactor anyway, that is a big function). Then, we could have `calculate_crafting_success` as a separate function drawing on the same modifiers, to calculate how likely the craft is to succeed. We set a low level whereupon we call the craft impossible. I'd have to run the numbers but I would suggest if your chance of success is less than 10%, we should just call it impossible. 

UI wise, a "too high failure rate" recipe should still show in available recipes, maybe highlighted red or brown. When selected, the middle pane of the crafting window should be replaced with an explanatory message, something like:
```
Your chance of crafting this is too low to even attempt it at this time.  You barely know where to start.
Main contributing factors:
- Darkness
- Low morale
- Skill(s) too low: Computers, Electronics
- Missing proficiency "Principles of Open Source Game Design"
Having a knowledgeable assistant or reference book might also help your luck.
```
This area is another one where potentially, refactoring out the different contributors to the success roll might make it easier to identify these. The wording of this message is up for discussion of course.

### Describe alternatives you have considered.

There are several other ways this could be done or a similar thing accomplished.
- a popup on attempted craft, warning you of a high failure rate.
- allow an override key to attempt to craft anyway despite low chance
- more hard barriers to crafting based on lacking key proficiencies

Personally, as someone with a lot of "proficiencies" in real life, I recognize there are points where while I may academically know how a thing is done, at some point it is not really "craftable" in the sense we model, and it may be worthwhile to just block the player from that frustration - but I am open to suggestions. Certainly there is not anything actually *stopping* me from trying to make a high quality dining table from scrap wood without a reference, I have the knowledge to try it, but lack the necessary practical skill and so would fail and waste material exactly as we model it. I also know enough to know my fail rate is very low, which is what this suggestion would model to some degree. The best simulation for that would be to allow a manual override of the blocked crafting, but it's fair to argue that that doesn't necessarily make for good gameplay... attempting to craft said dining table would not be fun for me, or for an avatar of me in a game.

### Additional context

The other advantage of this solution is a general highlight of the things that are contributing to crafting failure that players might not be aware of.

This issue comes up often enough and should be easy enough to fix that I'd like to consider this as a possible G-blocker.

**Comment by Photoloss** [comment]
An override key should definitely exist for weird edge cases. Maybe you happened to loot a cubic metre of alcohol and that 0.5% success chance doesn't seem too bad for raising chemistry since you won't drink it anyway. A full lockout should occur if you won't even gain any skill progress e.g. [this situation](https://youtu.be/II9-jXUWfI0?t=2659).

Note that example doesn't even involve Proficiencies, and probably shouldn't be science 2 in the first place as we can easily measure out quantities of liquids when handling them on their own. In other scenarios the requirements might be justified based on something the average player is not aware of however.

**Comment by I-am-Erk** [comment]
That is more or less what I think as well. "Press `C` to clear this warning and attempt anyway" wouldn't be amiss.

**Comment by GoLoT** [comment]
Relevant issue: #50787

**Comment by I-am-Erk** [comment]
Yes, that's related, although for that one we need to review the success calculation to make sure that 0 skill doesn't mean 0 chance. This would still help.

**Comment by PatrikLundell** [comment]
A hard block requires a very thorough check that you always can practice your way to the level at which you can try the crafting. I think an override is more or less necessary to avoid this situation (while also lessening the restrictions of how well all possible avenues have to be investigated).
The greatest problem with failures is the loss of scarce crafting materials, while a very long time to actually get the job done is less of a problem and also something that's fairly apparent up front.

**Comment by Brambor** [comment]
This issue has been resolved by showing the success chance to the player:
![image](https://github.com/user-attachments/assets/ef477bd3-de6f-4274-a184-c73bbbff7f03)

Which was introduced by #63886.
