### ISSUE TITLE
Missing overmap specials on game load

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#53502]
### Describe the bug

I am getting many missing overmap specials when loading my game.

Errors listed below. I get them many times.
```
 DEBUG    : invalid overmap special id "basin"

 FUNCTION : obj
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\generic_factory.h
 LINE     : 445
 VERSION  : cfc00fa

 DEBUG    : invalid overmap special id "bog"

 FUNCTION : obj
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\generic_factory.h
 LINE     : 445
 VERSION  : cfc00fa

```

### Steps to reproduce

1. Load this save [Alfred.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7730981/Alfred.zip)
2. Observe errors that you can skip through.

### Expected behavior

No missing overmap specials

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: cfc00fa [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Fewer Soldier Extras [Fewer_Soldiers]
]

### Additional context

Related to #53423, probably

**Comment by Night-Pryanik** [comment]
Closing as duplicate.
