### ISSUE TITLE
Increase UPS spawning in gas stations and electronics stores

### ISSUE THREAD

**Issue by foul-fortune-feline** [CleverRaven/Cataclysm-DDA#53509]
### Is your feature request related to a problem? Please describe.

Considering the fact that they are the closest thing to cataclysm's version of a smartphone charger, and are already common in malls as a consumer product, it makes little sense one can't find them in gas stations or electronics stores. In fact, the later has many smartphones on display, which irl typically come with a charger.

### Solution you would like.

Increase the spawning of UPS in electronics stores and gas stations to levels similar to that of malls and superstores.

### Describe alternatives you have considered.

Make smartphones and similar rechargeable devices compatible with a more common/cheaper charger that bionics and military weaponry aren't.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
