### ISSUE TITLE
Human hallucination

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#53503]
### Describe the bug

I see a creature marked as "if you see this, it's a bug" as a hallucination

### Steps to reproduce

1. Make a character that hallucinates (Kaluptic Psychosis)
2. Wait patiently for RNG to show you this bug, I guess

### Expected behavior

The game doesn't ruin my immersion

### Screenshots

![image](https://user-images.githubusercontent.com/2125926/146464948-3a8f4fc1-bff3-4103-9b64-1ec8807e492d.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: cfc00fa [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Fewer Soldier Extras [Fewer_Soldiers]
]

**Comment by Michael1993** [comment]
The simple solution would be to add `"flags": [ "NOT_HALLUCINATION" ]` as line 11 to [`mammal.json`](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/monsters/mammal.json#L10).

This should prevent [this `for` loop in `monstergenerator.cpp`](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/monstergenerator.cpp#L452-L456) to add it as a valid hallucination.
