### ISSUE TITLE
Finish reading certain skill books should give the appropriate principle proficiency 

### ISSUE THREAD

**Issue by bobface11** [CleverRaven/Cataclysm-DDA#53505]
### Is your feature request related to a problem? Please describe.

The description of proficiencies such as "Principles of Metalworking" and "Principles of Welding" points to these proficiencies as having the fundamental understanding of the skill being used. It makes no sense for a character who read a blacksmithing book to increase his fabrication skill to not know how blacksmithing works in theory.

### Solution you would like.

Considering that the purposes of skill books are to provide the basic knowledge for those skills, it would make sense for the character to gain the appropriate principle proficiency after reading a relevant skill book and at the reasonable skill level.

**Comment by I-am-Erk** [comment]
Proficiencies are considered a type of "practical" skill. No amount of reading will grant you one.

I'd be open to a mirror of the knowledge mechanic that temporarily gave you some partial benefits of a reference book if you'd studied a reference book enough, but ultimately you can read about welding all you like, you're still not going to have a feel for it until you put your hands on a welder.

**Comment by bobface11** [comment]
Based on what you said, the description of these basic proficiencies is giving me the impression that they are more theoretical instead of practical, given that the description of "Principle of Metalworking" is "A _basic understanding_ of the properties of metal as a material, and the _concepts_ behind smithing, die casting, and other metalworking techniques.". Perhaps a change in the description is warranted?

Having an appropriate skill book nearby to speed up proficiency learning like a reference book is a pretty good idea. Maybe multiple different skill books can stack the bonus but with diminishing results?

Unrelated, but does having higher skill level influence the speed of learning proficiencies?

**Comment by I-am-Erk** [comment]
Having skill books nearby already does that.

**Comment by bobface11** [comment]
Alright, cool.
