### ISSUE TITLE
You can be shot and killed by hallucination NPCs

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#53510]
### Describe the bug

Hallucinatory NPCs can shoot and kill you.

### Steps to reproduce

1. Make a character with Kaluptic Psychosis
2. Wait for them to hallucinate an NPC with a gun.
3. Make that NPC angry.
4. They shoot you and you get hurt.

Here's a savegame you can use. There is an armed hallucination inside the cabin directly to the east. Make them angry and they can shoot you!
[Alfred.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7731469/Alfred.zip)

### Expected behavior

I would expect hallucinatory NPCs to NOT be able to shoot me.

### Screenshots

![image](https://user-images.githubusercontent.com/2125926/146474663-5fa0e8c2-d513-4ca8-941f-ceef5b2ccbd2.png)
![image](https://user-images.githubusercontent.com/2125926/146474681-e3e596dc-ea55-4752-87aa-a6f3fcc311a8.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: cfc00fa [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Fewer Soldier Extras [Fewer_Soldiers]
]

**Comment by Inglonias** [comment]
![image](https://user-images.githubusercontent.com/2125926/146474946-014ed3e0-ece8-4438-aebf-0bc90ecf4467.png)

**Comment by Inglonias** [comment]
Oddly enough, we have a `pretend_fire()` method [in ranged.cpp](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/ranged.cpp#L710). Either that method is working improperly or is not being called correctly.

**Comment by Michael1993** [comment]
I don't know how to test this but I think the fix _could be_ this: 
```cpp
if ( !source.is_hallucination() ) {
    gun_mode mode = source.get_wielded_item().gun_current_mode();
    source.pretend_fire( source, mode.qty, *mode );
} else {
    source.fire_gun( location );
}
```
in here: [npc_attack.cpp](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/npc_attack.cpp#L400)

This piece of code is immediately followed by a `debugmsg` so seeing if this is indeed the code that gets called instead of the other one should be just loading in the save file and enabling debug messages.

**Comment by Inglonias** [comment]
I'm at work and can't compile anything right now, but the best way to test this would be to do just that, though. Compile the project with that code added in, and run it. See if it works as you expect. If it doesn't, make a test procedure and repeat it in the debugger, though playing Cataclysm through a debugger is like walking while neck deep in quicksand. The game slows down to the point of being damn near unplayable.

**Comment by Inglonias** [comment]
> I don't know how to test this but I think the fix _could be_ this:
> 
> ```c++
> if ( source.is_hallucination() ) {
>     gun_mode mode = source.get_wielded_item().gun_current_mode();
>     source.pretend_fire( source, mode.qty, *mode );
> } else {
>     source.fire_gun( location );
> }
> ```
> 
> in here: [npc_attack.cpp](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/npc_attack.cpp#L400)
> 
> This piece of code is immediately followed by a `debugmsg` so seeing if this is indeed the code that gets called instead of the other one should be just loading in the save file and enabling debug messages (`npcmove.cpp` doesn't have a `debugmsg` call).

Congratulations sir. You were almost 100% correct. The only incorrect thing in your fix was the if statement you provided was inverted. Otherwise, it works great!
