### ISSUE TITLE
Puddles still say you can not pick up spilt liquids when examining items

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#53526]
### Describe the bug

See title. Scooping up water works perfectly, but this is mainly a display bug. Since this happens with non-default settings and does not impact gameplay that much, this is not a terribly important bug.

### Steps to reproduce

1. Find a puddle in the forest or spawn one with the map editor.
2. Examine the puddle.
3. Hit Escape in the "What to do with the water from recess?" dialogue. This requires you to use examine nearby terrain, furniture **and items** (this part is important), so bind it to a key.
![image](https://user-images.githubusercontent.com/59517351/146506887-7dde6d93-e92d-46cf-b0a6-299f80f54760.png)
4. The resulting pickup window says you can not pick up spilt liquids.
![image](https://user-images.githubusercontent.com/59517351/146507069-ac1ad4d7-1756-4445-99e5-9df0eb696725.png)

### Expected behavior

There should be no pickup window for water from recesses. There should also be an error when trying to pour it onto the ground since it basically moves the puddle and makes all the water dirty so you can really not pick it up anymore.

### Versions and configuration

- experimental

**Comment by Night-Pryanik** [comment]
The same with trying to pick up liquids from toilets and all other terrain/furniture with `LIQUIDCONT` flag.
