### ISSUE TITLE
Doctor installs Power Storage CBMs beyond max resulting in negative power 

### ISSUE THREAD

**Issue by Nerdy314159265** [CleverRaven/Cataclysm-DDA#53522]
### Describe the bug

I discovered that you are allowed to have a Doctor install a Power Storage CBM even when you have already hit the max 2100 bionic power.
However, doing this will cause the Bionic power to go into the negatives and make activating anything impossible.

### Steps to reproduce

1. Create player with max Bionic Power
2. Chat with Doctor at farm base
3. Install a Power Storage CBM through the Doctor

### Expected behavior

I'd expect the Power Storage to increase like normal, if the Doctor is allowed to install past the standard max Bionic Power.
If no, then I'd expect the Doctor to do the same checks that autodocs do to prevent installation.

Also, I'd suggest adding a small check that if someone has negative power to set it to maximum.

### Screenshots

![image](https://user-images.githubusercontent.com/6250374/146497770-a4ab46d2-99be-4964-ad8d-1ee20cdd9e3e.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Useful Helicopters [useful_helicopters]
]

**Comment by GoLoT** [comment]
If confirmed: #53165 doesn't have this issue and it should be easy to backport.

**Comment by hexagonrecursion** [comment]
Confirmed

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 0.F-2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by hexagonrecursion** [comment]
@wapcaplet confirmed

**Comment by Night-Pryanik** [comment]
Fixed in #53165.
