### ISSUE TITLE
Doctor will install Bionics he owns for no extra cost

### ISSUE THREAD

**Issue by Nerdy314159265** [CleverRaven/Cataclysm-DDA#53524]
### Describe the bug

Once the Doctor's inventory is full and he starts dropping items on the ground, those items will be available for installation as any other loose item owned by the player would be.

Since the Doctor doesn't see it as "his" for sale, it isn't restricted from installation and requires no extra cost to install.

This opens up the ability to sell the Doctor items you want to install to pay for themselves effectively.

### Steps to reproduce

1. Trade the doctor enough items or large enough items to fill his inventory
2. On the next install, sell bionics that you want to install and he'll drop it on the ground
3. Select that bionic for install for no additional cost
4. Trade him more bionics that you want installed to make up for the installation cost

### Expected behavior

The Doctor should recognize any items not owned by you and should either remove them from the list of possible installs or adjust the price of installation to include the price of the bionic.

### Screenshots

![image](https://user-images.githubusercontent.com/6250374/146502630-50e82883-6064-48e5-b606-a6422dea9dd5.png)

Items on the floor are not owned by the player.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Useful Helicopters [useful_helicopters]
]

**Comment by GoLoT** [comment]
Possible (untested) fix:
```diff
diff --git a/src/game_inventory.cpp b/src/game_inventory.cpp
index 59c3219661..8b3a9e7b9c 100644
--- a/src/game_inventory.cpp
+++ b/src/game_inventory.cpp
@@ -2259,7 +2259,7 @@ class bionic_install_preset: public inventory_selector_preset
         }

         bool is_shown( const item_location &loc ) const override {
-            return loc->is_bionic();
+            return loc->is_bionic() && loc->is_owned_by( you );
         }

         std::string get_denial( const item_location &loc ) const override {
@@ -2347,7 +2347,7 @@ class bionic_install_surgeon_preset : public inventory_selector_preset
         }

         bool is_shown( const item_location &loc ) const override {
-            return loc->is_bionic();
+            return loc->is_bionic() && loc->is_owned_by( you );
         }

         std::string get_denial( const item_location &loc ) const override {

```

**Comment by hexagonrecursion** [comment]
I was unable to reproduce this bug. I am stuck on step 2. When I try to sell the CBMs I get NAME, Doctor doesn't have the appropriate pockets to accept that.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 9473cf6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by hexagonrecursion** [comment]
I can confirm that the bug affects 0.F-2, but does not affect experimental.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 0.F-2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by hexagonrecursion** [comment]
0.F-3 is also affected

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 0.F-3 [64-bit]
- Graphics Version: Curses
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by LeahLuong** [comment]
Weird, I was unable to locate a PR that would've fixed this bug for the latest release.
