### ISSUE TITLE
Easy to merge label

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#53529]
### Is your feature request related to a problem? Please describe.

Are you someone who can merge PRs? Are you overwhelmed by the sheer volume of new PRs that need to be reviewed?

Fear not, as I have developed the perfect™ solution for this: The Easy to merge label.

### Solution you would like.

I'd like to add a new label: "Easy to merge", basically the "Good first issue" equivalent for PRs. There are many contributions which are small fixes or additions, usually in JSON. I think it would make sense to label them as such so the easy stuff can get taken care of faster.

Examples which would be easy to merge:

- Typo/grammar/wording fixes.
- Mapgen fixes (e.g someone fixing a missing wall or something)
- Crafting recipe fixes (e.g adding some sensible byproducts or adjusting some values in a minor way)

### Describe alternatives you have considered.

Maybe naming it "Minor". The classification of that is potentially something to discuss though, since there are lots of easy fixes but not all of them just change 2 lines.

E.g what if someone would go through through an entire file fixing typos and grammar? Is it still minor if the file is over 1000 lines long and the diff is about say 50 lines long?

What if someone adds rain gutters to a roof which was missing them? The diff will also be potentially large yet the change is simple.

**Comment by Inglonias** [comment]
Even simple changes can cause crashes and failures if you don't understand what you're doing. A lesson I learned through personal experience in #30749

**Comment by NetSysFire** [comment]
Yes, but maintainers usually™ know what they are doing and are familiar with some of the internals so they can judge if something is simple enough or not. And people who have the power to actually merge PRs will not merge stuff without checking first.

**Comment by I-am-Erk** [comment]
Label addition still requires a rank in the CleverRaven organization. What has worked really well is to post PRs that have passed tests and are good to go in the "ready to merge" channel on discord, and we can then assess if they're an easy merge or not. Another good way to help triage is to review and approve PRs that touch code you might know, or to playtest a PR and make an approved review if you have done so, regardless of your understanding of the code itself. We don't treat those as an instant approval but as a useful point of data that can facilitate merging

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
