### ISSUE TITLE
Martial Arts tab in Character Creation

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#53534]
### Is your feature request related to a problem? Please describe.

(Note: i may use "fighting styles" and "martial arts" interchangeably.)

I find selecting martial arts to be a bit tedious. This was worse before when they were split between multiple tabs like [Hobbies] and [Traits] and is better now, all being found grouped in the [Backgrounds] tab. However, there are still limitations and (subjectively) issues with the current implementation.

Fighting styles are a great, rather fleshed out mechanic used quite often. Many have been rebalanced or revised lately. More are being proposed and likely added in the future. The [Backgrounds] tab is already quite long. It's worth revisiting how Martial Arts are selected in character creation. The goal being to:

- Make martial arts selection easier
- Allow for greater customization (Who says my character did not learn both Karate and Taekwondo)
- Give easier access to information on fighting style options and techniques.
- Allow for easier integration of fighting style mods

### Solution you would like.

**Add a [Martial Arts] tab to character creation.**
This name could be changed to martial training, fighting styles, etc. Whatever is most fitting.
This could look like -     [Scenario]  [Profession]  [Background]  [Martial Arts]  [Stats]  [Traits]  [Skills]  [Description]

Currently there are 5 groups of fighting styles. These are:
-Martial Arts
-Self-Defense
-Melee Training
-Fencing
-Shaolin Kung Fu

Rather than the [Martial Arts] tab simply having the current groups, a tree system would be preferable. Fighting styles would be chosen individually but still shown under their respective groups. This also would allow for selection of multiple styles from the same group. Showing the martial art groups would make scrolling through and finding the desired style easier.

A left side panel would list the (un-selectable) fighting style groups with their (selectable) indented fighting styles below. A right side panel could be used to display all the buffs and techniques of the currently highlighted Fighting Style. This panel could be switched to for more information on the techniques.

I believe this change would not only ease the process of viewing and selecting martial arts for players (especially those newer to the game) and possibly de-clutter the backgrounds tab some, but would allow for greater integration of new fighting styles in current or new mods (An area where the two panel system of fighting groups and styles, and techniques and buff information would really be helpful).

### Describe alternatives you have considered.

An addition would be to add levels of martial art proficiencies. Current martial arts techniques are gated by melee or unarmed skills. This could be changed to or in addition to the level of the martial art.

You could have Taekwondo [Beginner], [Intermediate], [Advanced], and possibly [Expert] levels which would unlock greater techniques or even increase the effectiveness of techniques and buffs. 

Certain professions or backgrounds could give levels of a martial art, or these could be chosen on the [Martial Arts] page where points could be distributed to different arts similar to the current [Skills] tab.

Known martial arts could be leveled up by practicing them in the [Practice] tab in gameplay. New martial arts can be learned from Books or from NPCs where you will learn practice recipes to gain levels in the Martial art. 

For example.

- Character with no Ninjutsu skills
- Finding a book that can teach Ninjutsu [Expert]
- Practicing Ninjutsu from the crafting menu while book is on you.
- Eventually learning Ninjutsu [Beginner]
- Can keep practicing until you master the art.

This would take a while. Perhaps a solid week devoting 30-60 min a day to learn each level, similar to proficiencies. 
There could be skill rust as well, where the martial art should be practiced at least 30 min a week to keep your current level.

### Additional context

With a quick search, approx 5% of adults have studied a martial art. It may seem unnecessary to dedicate a tab to this function. But this is a zombie-fighting survival game with a heavy focus on combat and I believe many enjoy the aspect of starting a character with fighting styles. They are a wonderful element of combat and there are many possibilities for the mechanic to become even more fleshed out or expanded upon.

Maybe we will see fighting styles that pair particularly well with certain mutation types or CBMs, styles that can be learned from special factions or races, ability to practice and improve techniques specifically.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
