### ISSUE TITLE
Item mods should be able to "modify" pockets without having to re-write them entirely 

### ISSUE THREAD

**Issue by catdach** [CleverRaven/Cataclysm-DDA#53542]
### Is your feature request related to a problem? Please describe.

So I've been trying to find a fix for shotgun speedloaders for over a month now, and I've come to realize that it's not a problem that I can fix without some changes to how JSON data is parsed in the C++ code. Basically, what I need is some way for the "speedloader chute" gun mod to add the line `"allowed_speedloaders": [ "shot_speedloader6", "shot_speedloader8" ]` into the pocket data of whatever shotgun it's attached to. As far as I can tell there isn't a way to access or add to the pocket data of an item with an item mod. In pull request #41917 the "pocket_mods" option was introduced, but despite the name it doesn't seem to allow any edits or additions to existing pocket data (if it does then there isn't any documentation for how to do so). Instead it allows you to _replace_ existing pockets with a new one. So the best I can do with the speedloader chute is add the following:
```
    "pocket_mods": [ 
 {
        "pocket_type": "MAGAZINE",
        "ammo_restriction": { "shot": 8 },
        "allowed_speedloaders": [ "shot_speedloader6", "shot_speedloader8" ] 
 } 
],
```
Which _almost_ works, but there are a few problems. 
1. If the gun is loaded, attaching the chute produces an error (no problem, lots of gunmods require the gun to be unloaded)
2. The change is permanent, so players could just take the chute off and keep the functionality (abit more of a problem)
3. I have to re-write the `"ammo_restriction"` (oh gosh, oh frick, oh no)

Problem 1 and 2 can probably be worked out pretty easily but 3 is a mess. If you don't know why 3 is a problem, that line will set the max ammo of any gun with the chute to 8. The speedloader chute can go on a lot of guns with varying ammo capacities, so changing them all to a capacity of 8 (or any number really) doesn't make sense. The need to define values for the "ammo_restriction" field **at all** is a bit of a mess itself but I've gone off about that at exhausting length already in this issue request #53375 so I'll refrain from doing that here. The bottom line is that It prevents `"pocket_mods"` from solving my problem. For now changing `"ammo_restriction"` from how it's written in the original gun item in _any_ way, will break the game. 

### Solution you would like.

Something similar to `"pocket_mods"` that allows for modification of pocket data having to reiterate all the current pocket data of an item. Something like a `"pocket_extends"`

### Describe alternatives you have considered.

If #53375 could be done then I wouldn't _need_ to be able to modify pocket data for this specific issue, but it would still be a little messy. This IR's solution is preferred as it could be useful for other potential gun mods (maybe interchangeable barrels, magazine expanders, etc.), but I would really like both issues to be resolved.

### Additional context

No shade on #41917, it just doesn't seem to do quite what I need it to. Also we could use some documentation on how exactly `"pocket_mods"` works, I spent a lot of time trying to figure it out on my own through trial and error. Also a more descriptive name than "pocket_mods" might be nice. Otherwise it's great, hahahaha (speedloaders haunt my dreams now 🙃)

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
