### ISSUE TITLE
newly generated "crater" map features are now visibly holes in the ground

### ISSUE THREAD

**Issue by Scorch-Mechanic** [CleverRaven/Cataclysm-DDA#53549]
### Describe the bug

After a conversation in the devcord, someone said we should write this down as a bug report so we don't forget about it.

Craters appear to destroy dirt now. They're empty air, with dirt below. I suppose they're finally living up to their name. I don't drive over craters as a matter of course, ~~but I'd hate to accidentally destroy my car in one.~~ they are solid to drive upon, but not to walk upon. As an experimented I drove a dirtbike onto the center of one and stepped into the ledge. I fell _into_ a solid earth tile, and there was solid dirt all around me, even though it showed as being empty space on the surface level.

EDIT: saving and loading with a bugged crater in the reality bubble appears to have fixed it. 

### Steps to reproduce

1. Find or debug in a newly generated crater. See that it is now more than just radioactive dirt, it is now a radioactive absence of dirt.

### Expected behavior

Craters should go back to their old generation, or perhaps be "shallow pits". 

### Screenshots

![image](https://user-images.githubusercontent.com/5760760/146632508-0457ac15-9aa8-425b-8cf9-3eb005858c69.png)
![image](https://user-images.githubusercontent.com/5760760/146632512-ffff4c2a-49da-4aa2-a7ad-fe94a605d33b.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 2eb98ad [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Could it possibly be related to #53247 ?

**Comment by PatrikLundell** [comment]
For a crater to live up to its name I think it ought to be shallow pits and deep pits.

**Comment by NetSysFire** [comment]
I agree. There is also rubble. I think this might be related to #53247

**Comment by NetSysFire** [comment]
Yeah this is definitely buggy and this should not happen. If I step into a crater and teleport out of it back onto the surface, the open air vanishes and it looks like an ordinary crater from before.

**Comment by NetSysFire** [comment]
@I-am-Erk Could we make this a release blocker? This might be an important bug, especially because you and your vehicles can get trapped.

**Comment by NetSysFire** [comment]
So I just saw https://www.reddit.com/r/cataclysmdda/comments/rthyxk/dont_ignore_craters/ and tested it out. Monsters do not die instantly but they get trapped in solid earth. This also triggers an error:

```
 DEBUG    : tried to put an item (tshirt) count (1) in a container (null) that cannot contain it: pocket with type (CONTAINER) not found

 FUNCTION : ret_val<bool> item::put_in(const item&, item_pocket::pocket_type, bool)
 FILE     : src/item.cpp
 LINE     : 1417
 VERSION  : 0.F
```

**Comment by coyo7e** [comment]
reloading a save in view of these tiles seems to fill them in, at least some of the time.
