### ISSUE TITLE
Corpse deleted instead of resurrecting

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#53547]
### Describe the bug

While trying to reproduce #52320 I have ran into a different bug: dropping a ready-to-resurrect corpse under your feet makes it vanish.

### Steps to reproduce

1. Kill a zombie dog [id: mon_zombie_dog]
2. Wear a large tactical backpack
3. Put the dog corpse in the backpack
4. Debug time forward 10 days
5. [d]rop the corpse under your feet
6. The corpse disappears 

### Expected behavior

I expected to see either a resurrected dog or a corpse.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 9473cf6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Sometimes I can reliably reproduce this issue several times in a row and sometimes I can not reproduce it several times in a row. There may be a variable I do not know about (and do not know how to control) affecting the experiment.

**Comment by LeahLuong** [comment]
Are you familiar w/ the concept of Schrödinger's cat?? I think you may have found his dog . . .

**Comment by AustinBoyd9** [comment]
I have tried to reproduce this issue by starting a fresh game and using the Debug menu to spawn a large tactical backpack, a weapon (steel spear), and a zombie dog. I killed the corpse, put it in my backpack, forwarded 10 days, and dropped it. The dog was alive and attacking. I repeated this process again with the same behavior. 

Configuration:

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by KHeket** [comment]
> I have tried to reproduce this issue by starting a fresh game and using the Debug menu to spawn a large tactical backpack, a weapon (steel spear), and a zombie dog. I killed the corpse, put it in my backpack, forwarded 10 days, and dropped it. The dog was alive and attacking. I repeated this process again with the same behavior.
> 
> Configuration:
> 
> * OS: Windows
>   
>   * OS Version: 10.0 2009
> * Game Version: 0.F-3 [64-bit]
> * Graphics Version: Tiles
> * Game Language: System language []
> * Mods loaded: [
>   Dark Days Ahead [dda],
>   Disable NPC Needs [no_npc_food],
>   Bionic Professions [package_bionic_professions]
>   ]
> 
> This could be related to the no fungal growth mod, as it is the difference between our configurations.

you must drop the dog body undr your feet, not near you, becase I confirmed this bug. Spawn big backpack, killed the dog, take its body, wait for 30 days, then dropped it under my feet - and body dissapeared

Same problem is in https://github.com/CleverRaven/Cataclysm-DDA/issues/61836
