### ISSUE TITLE
Eyebot leads to infinite spawning of bots

### ISSUE THREAD

**Issue by njk2002** [CleverRaven/Cataclysm-DDA#53559]
### Describe the bug

When the player get close to the eyebot, the eyebot will summon a police bot or a riot control bot (in the northwest). 

If the player wears a hazmat suit or a Hub-01 suit that protects him/herself  from electric discharges, and he/she somehow managed to beat the bot at a fairly low cost (hm12 dazzle rifle), then there exists a way to get infinite materials (disassembling those inactive bots).

I think this is somehow related to game balance. 

### Steps to reproduce

1. Be well equipped. (suit, rifle,etc)
2. Spawn or find an eyebot.
3. Wait for the summoned police bot to walk closer.
4. Shoot at it and turn it off.
5. Repeat 3 and 4 for many times.
6. Now you can get many valuable things, such as solar cells. 

### Expected behavior

The number of bots one eyebot can summon should be limited. 

### Screenshots
![cdda](https://user-images.githubusercontent.com/22912139/146645873-55298244-5f15-42df-be3d-c603979c06e9.JPG)

### Versions and configuration

OS: Windows 10
Game Version: experimental build 2021-11-12-0952 (the problem still exists in 2021-12-18-1029)
Graphics version: Tiles
Ingame language: Chinese (turned to English to take a screenshot)
Mods loaded: no_npc_food, no_fungal_growth, package_bionic_professions, blazeindustries, crt_expansion, StatsThroughSkills, speedydex, stats_throgh_kills

**Comment by GoLoT** [comment]
This definitely needs a cooldown or a cap. Or both. At most 3 bots should spawn per eyebot and there should be a long cooldown period, at least 6h, between "emergency calls".
