### ISSUE TITLE
Batch Crafting Errors

### ISSUE THREAD

**Issue by pontim** [CleverRaven/Cataclysm-DDA#53569]
### Describe the bug

When trying to batch craft items (in this example antiseptic soaked cotton balls) I often get the error "Attempted a recipe with no available components" it then returns to the game and nothing was crafted

### Steps to reproduce

1. get several different bottles of antiseptic and cotton balls
2. try to batch craft the max number of antiseptic soaked cotton balls

### Expected behavior

No errors when batch crafting

### Screenshots

![image](https://user-images.githubusercontent.com/5273559/146655718-bb953410-230c-47d7-affb-dbc50774a67b.png)

![image](https://user-images.githubusercontent.com/5273559/146655710-96da3fb8-7cd8-481f-b79d-ae9f6afa0bf9.png)

### Versions and configuration

2021-12-17-2356 windows 10 x64

**Comment by pontim** [comment]
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7739978/save.zip)

**Comment by mkrutov** [comment]
That happens when you craft things and one of the ingridients that you use is either far from you or is visually blocked by something (so x -- X -- i with x being you, X being a shelf, i being ingridient, leads to this behaviour)

**Comment by GoLoT** [comment]
> That happens when you craft things and one of the ingridients that you use is either far from you or is visually blocked by something (so x -- X -- i with x being you, X being a shelf, i being ingridient, leads to this behaviour)

Another common scenario: After closing a car door. The crafting cache isn't refreshed so the crafting menu will still show the recipe as available but fail when trying to retrieve the components/tools.

**Comment by dseguin** [comment]
The issue here was some leftover cruft that I forgot to remove as part of #53157. Some recipe pointers were acting as bools when passed to `Character::crafting_inventory`.

(See https://github.com/CleverRaven/Cataclysm-DDA/pull/53302/commits/3b8bb34e289e8bd86f1dadc58f80f81f0dcddf93)
