### ISSUE TITLE
Atomic smartphone from Aftershock doesn't support calories counting

### ISSUE THREAD

**Issue by mkrutov** [CleverRaven/Cataclysm-DDA#53566]
### Describe the bug

n/a

### Steps to reproduce

1. Get atomic smartphone
2. eat stuff

### Expected behavior

exact Calories displayed instead of "huge/minimal" etc

### Versions and configuration

These are the outputs for the experimental build of commit 9bbe06ec7076ae9b879ab348fc841b905e141639
Linux

Aftershock enabled

**Comment by nexusmrsep** [comment]
Good first issue here.
Just add `"CALORIES_INTAKE_TRACKER"` to the list of permittable actions in `"use_action"` in `tools.json` for the `"afs_atomic_smartphone"`
![image](https://user-images.githubusercontent.com/39925111/146826006-99bbee9f-b6fb-44c2-890a-df855603bc40.png)
