### ISSUE TITLE
Towing Woes

### ISSUE THREAD

**Issue by LeahLuong** [CleverRaven/Cataclysm-DDA#53575]
### Describe the bug

There are a couple of issues I wanted to raise here & I think I can do that best w/ a little story.

I wanted to get some components off of a solar car which happened to be inside an active fungal zone. Knowing it would be foolhardy to spend hours in the area working on the vehicle, I decided to tow it away. I got the car out of there using my humvee & decided to pull off the road a little so I wouldn't endanger future users of the way by leaving an aluminum husk there. Leaving the pavement resulted in a warning that my vehicle was having difficulty towing on the new surface (grass & dirt) but I still had traction. Decelerating seemed to have a much reduced effect on the towee as compared to towing on the road; this resulted in the towee rearending the tower. Following the collision, the towing vehicle seemed unable to brake & the towee seemed to be maintaining slowly reducing acceleration. A few more collisions ensued as I wrestled the 2 vehicles back to the road & was finally able to brake successfully, where the solar car was finally brought to a halt by crashing one more time. @ no point was I driving faster than 30 mph. The last crash caused the front frame of the solar car to fall off, disconnecting the tow cable. I put the cable back in my hummer & went to inspect the damage. As you'd expect, the humvee didn't take much but I noticed there was a tow cable still attached. I went to remOve it, the game crashed, & I received the segmentation fault pasted below.

My guess is that the math governing offroad handling of towing mechanics is somehow tied to variables generated while driving on the road. Perhaps reversing the order of things would shed some light; start towing offroad & then transfer to a better surface. I was unable to crash the solar car to a halt for fear of destroying 1 or both vehicles while towing on the grass because each collision didn't seem to reduce the car's speed by much & the humvee was unable to decelerate very quickly, merely gaining more speed from getting repeatedly rearended; it looked like it was coasting to a halt rather than actively braking, which it was doing, offroad, prior to the 1st collision which also happened offroad. I U-turned to get back on the road & the solar car did some crazy fishtailing. I tried to curtail my velocity slowly once back on the road (1 increment down/tick) but the solar car still managed to break off 2 frames @ the final stop.

Furthermore, there is the issue where disconnection of the tow cable by part failure doesn't result in the other end automatically detaching. I assume the game broke because it wasn't able to find the other end when I went to detach. In actuality, the entire cable, undamaged, was already sitting in my hummer's cargo. The part still attached had taken a tick of damage from the collisions & perhaps this circumvented automatic detachment.

Perhaps damage to the tow cable also played a part in the strange handling following the 1st collision. The tow cable did still seem to be working but prob not as intended. After all, I was able to get both vehicles back to the road but, offroad, each collision seemed to impart more speed to the towed vehicle which would only partially dissipate before the next collision.

I was able to reload my game to a point before I started towing.

### Steps to reproduce

1. Tow a light vehicle using a heavy 1 on a road.
2. Go offroad.
3. ???
4. PROFIT!

### Expected behavior

I expected that heavy duty tow cable level would increase, because all other skills can increase in level.

### Versions and configuration

Android 0.F-3 Tiles English vanilla

### Additional context

VERSION: 0.F-3
Signal SIGSEGV: Segmentation fault
STACK TRACE:
# 3: 0xb4ba5838 art::FaultManager::HandleFault(int, siginfo*, void*)
# 5: 0xa2b540b4 item_pocket::favorite_settings::favorite_settings(item_pocket::favorite_settings const&)
# 6: 0xa2b54030 std::__ndk1::list<item_pocket, std::__ndk1::allocator<item_pocket> >::push_back(item_pocket const&)
# 7: 0xa2b53ff4 std::__ndk1::list<item_pocket, std::__ndk1::allocator<item_pocket> >::list(std::__ndk1::list<item_pocket, std::__ndk1::allocator<item_pocket> > const&)
# 8: 0xa2b1a3c4 item::item(item const&)
# 9: 0xa310de96 vehicle::remove_part(int, RemovePartHandler&)
#10: 0xa3111e42 vehicle::remove_part(int)
#11: 0xa30ede56 veh_interact::complete_vehicle(player&)
#12: 0xa2779e26 activity_handlers::vehicle_finish(player_activity*, player*)
#13: 0xa27a3b46 std::__ndk1::function<void (player_activity*, player*)>::operator()(player_activity*, player*) const
#14: 0xa27a3ba6 activity_type::call_finish(player_activity*, player*) const
#15: 0xa2f8b93e player_activity::do_turn(player&)
#16: 0xa2a20e88 game::process_activity()
#17: 0xa2a1f944 game::do_turn()
#18: 0xa2c8dd80 SDL_main
#19: 0xb3966e2a Java_org_libsdl_app_SDLActivity_nativeRunMain

**Comment by PatrikLundell** [comment]
There is something wrong with the towing logic, as you get rear-ended most of the time when stopping, even if you never traveled faster than the minimum speed (#51228) regardless of whether the surface is road or plain.

You can also get rear-ended while traveling at a constant speed and turning gently as the towed vehicle somehow can convert wildly swinging sideways motions into forward motion.

**Comment by LeahLuong** [comment]
I appreciate your response to the 1st issue but you may not want to close this issue w/out addressing the 2nd concern I raised: part failure leaving behind a buggy end of the cable attached. Had I not noticed it & later saved my game, that part would still be on my vehicle w/out a way to remove it that wouldn't trigger a seg fault. Perhaps not gamebreaking but I can't imagine the solution to this problem being too complicated.

**Comment by hexagonrecursion** [comment]
To reproduce the crash:
1. Attach two vehicles
2. Destroy the frame the heavy duty tow cable is attached to on the towee without destroying the tow cable part itself
3. A tow cable is dropped on the ground where the part you destroyed used to be
4. The other end of the tow cable can still be seen by inspecting the towing vehicle
5. Rem[o]ve
6. Crash (see below for gdb stacktrace)

```c++
Thread 1 "with-debug-symb" received signal SIGSEGV, Segmentation fault.
0x0000000002c9d1b0 in item::item (this=0x7ffd363cee50) at src/item.cpp:470
warning: Source file is more recent than executable.
470	item::item( const item & ) = default;
(gdb) bt
#0  0x0000000002c9d1b0 in item::item (this=0x7ffd363cee50) at src/item.cpp:470
#1  0x000000000381c019 in vehicle::remove_part (this=<optimized out>, 
    this@entry=0x3b037e30, p=<optimized out>, p@entry=-1, handler=...)
    at src/vehicle.cpp:1926
#2  0x00000000038213b7 in vehicle::remove_part (this=0x7ffd363cee50, p=0)
    at src/vehicle.cpp:1810
#3  0x00000000037dc59d in veh_interact::complete_vehicle (you=...)
    at src/veh_interact.cpp:3397
#4  0x00000000025229ec in activity_handlers::vehicle_finish (
    act=act@entry=0x5cdad20, you=0x5cda7c0) at src/activity_handlers.cpp:2117
#5  0x0000000002536c0f in std::__invoke_impl<void, void (*&)(player_activity*, Character*), player_activity*, Character*> (__f=
    @0x5599bf0: 0x2522960 <activity_handlers::vehicle_finish(player_activity*, Character*)>, __args=<optimized out>, __args=<optimized out>)
    at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:61
#6  0x0000000002536bb4 in std::__invoke_r<void, void (*&)(player_activity*, Character*), player_activity*, Character*> (__fn=
    @0x5599bf0: 0x2522960 <activity_handlers::vehicle_finish(player_activity*, Character*)>, __args=<optimized out>, __args=<optimized out>)
    at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:154
#7  0x0000000002536af4 in std::_Function_handler<void (player_activity*, Character*), void (*)(player_activity*, Character*)>::_M_invoke(std::_Any_data const&, player_activity*&&, Character*&&) (__functor=..., __args=<optimized out>, 
    __args=<optimized out>)
    at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:291
#8  0x000000000257a133 in std::function<void (player_activity*, Character*)>::operator()(player_activity*, Character*) const (this=0x5599bf0, 
    __args=__args@entry=0x5cda7c0, __args=__args@entry=0x5cda7c0)
    at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:560
#9  0x00000000025798a9 in activity_type::call_finish (this=<optimized out>, 
    act=0x5cdad20, you=0x5cda7c0) at src/activity_type.cpp:118
#10 0x0000000003524ce7 in player_activity::do_turn (this=0x5cdad20, you=...)
    at src/player_activity.cpp:358
#11 0x00000000029c9837 in do_turn () at src/do_turn.cpp:656
#12 0x0000000002f3dc35 in main (argc=<optimized out>, argv=<optimized out>)
    at src/main.cpp:711
```

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 0.F-4465-gef6206f0f7 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by captainego** [comment]
I have been attempting to reproduce the sub-issue that @hexagonrecursion  described in https://github.com/CleverRaven/Cataclysm-DDA/issues/53575#issuecomment-997806355.  

Steps to attempt reproduction:
Create a new character
Move to a clear area
Spawn a Humvee
Exit the Humvee and move 5 "steps" behind the Humvee
Spawn a Solar Car
Spawn a heavy tow cable
Attach the first end of heavy tow cable to the center rear of the humvee
Attach the second end of the heavy tow cable to the center front of the Solar Car
Modify the character strength to 100
Spawn a Heavy Sledge Hammer
Wield the Heavy Sledge Hammer
Smash the center front tile of the Solar Car (where the heavy tow cable is placed)
OBSERVE:  A message that the heavy-duty tow cable is destroyed appears and the frame object is destroyed
OBSERVE: A damaged heavy-duty tow cable appears on the ground under the tile being smashed
OBSERVE: The center rear tile of the humvee no longer has a heavy-duty tow cable listed as a part

Additonal attempted steps to attempt reproduction:
Create a new character
Move to a clear area
Spawn a Humvee
Exit the Humvee and move 5 "steps" behind the Humvee
Spawn a Solar Car
Modify the character strength to 100
Spawn a Heavy Sledge Hammer
Wield the Heavy Sledge Hammer
Smash the center front tile of the Solar Car until the frame is heavily damaged (I was able to achieve the XX damaged state)
Spawn a heavy tow cable
Attach the first end of heavy tow cable to the center rear of the humvee
Attach the second end of the heavy tow cable to the center front of the Solar Car
Smash the center front tile of the Solar Car (where the heavy tow cable is placed)
OBSERVE:  A message that the heavy-duty tow cable is destroyed appears and the frame object is not further damaged
OBSERVE: A damaged heavy-duty tow cable appears on the ground under the tile being smashed
OBSERVE: The center rear tile of the humvee no longer has a heavy-duty tow cable listed as a part

Based on these tests I believe that this issue has been resolved.

**Comment by I-am-Erk** [comment]
I will mark this as resolved. Please let me or another member of CleverRaven know if this is incorrect, and we can reopen it.
