### ISSUE TITLE
Teach Autodrive to ram/ignore some obstacles

### ISSUE THREAD

**Issue by Nerdy314159265** [CleverRaven/Cataclysm-DDA#53579]
### Is your feature request related to a problem? Please describe.

Later in the game where one has likely used their mechanical skills to create a rolling death machine with rams and armor. It's a tad limiting for Autodrive to be afraid of running into anything.

For example, my current machine can run over light poles with (almost) no damage as well as most zombies as long as they are hit square on with the rams. So if I have Autodrive enabled and I am having it drive me through a city or in the field a stray enemy appears, it'd be nice if it could pulverize the enemy instead of cancelling Autodrive.

### Solution you would like.

It'd be nice for Autodrive to be able to allow for ignoring obstacles that will do no damage to the vehicle with a sliding scale of how much damage is allowable and also for it to be aware of rams so that it can attempt hit square on with them instead of hitting the side of the vehicle.

Default would be avoid all obstacles and progressively get more aggressive according to some settings.

Example:
1. Avoid all obstacles
2. Avoid obstacles that cause damage
3. Avoid obstacles that will heavily damage parts
Can't think of more tiers but I think one option that should be toggle for the higher levels is:
Avoid obstacles that will damage beyond repair or destroy a part.

**Comment by PatrikLundell** [comment]
Disagree. The decision to run into targets should be active decisions. If you want to plow a new path through a town it should be a manual task, although auto drive should then be able to follow the cleared path if it's clear enough (but you should still have to make the decision to run over the zombies manually).

**Comment by Nerdy314159265** [comment]
That's reasonable, I guess in alternatives I should've added something like the ability for autodrive to reroute if a road is completely blocked and a way to resume if it does have to stop.

Those are needed at minimum because it can be a little annoying when a single zombie steps in front of your vehicle in the middle of nowhere when I know I could run it down no problem since it can be a pain to reopen the map, find where I wanted to go again which can take awhile if far away and then restart the run. (still infinitely better than before though I love autodrive now)

**Comment by PatrikLundell** [comment]
I certainly agree that resuming after dealing with an interruption is a useful thing.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
