### ISSUE TITLE
Gas Station buying diesel/gas error

### ISSUE THREAD

**Issue by Kywi001** [CleverRaven/Cataclysm-DDA#53581]
### Describe the bug

You can buy a gas/diesel initially but once you refund even once, it will give you an error and can't buy diesel/gas again.

### Steps to reproduce

1. Go to a gas station
2. issue a refund
3. try to buy diesel/gas

### Expected behavior

should allow me to buy diesel/gas after a refund

### Screenshots

![Screenshot_2021-12-19-13-18-12-724_com cleverraven cataclysmdda experimental](https://user-images.githubusercontent.com/95905384/146665935-e6183e59-ff95-4463-b965-704b5d4c7fdb.jpg)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: Xiaomi; Model: Redmi 6; Release: 9; Incremental: V11.0.4.0.PCGMIXM; 
- Game Version: aa90e92 [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Military Profession Pack [military_professions],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Wearable Artifacts [art_wear]
]

**Comment by dseguin** [comment]
This is a good first issue. One-line fix:
```diff
diff --git a/src/iexamine.cpp b/src/iexamine.cpp
index e07aae309c..d1131a75dc 100644
--- a/src/iexamine.cpp
+++ b/src/iexamine.cpp
@@ -4523,7 +4523,7 @@ void iexamine::pay_gas( Character &you, const tripoint &examp )
         int maximum_liters = std::min( money / pricePerUnit, tankUnits / 1000 );
 
         std::string popupmsg = str_to_illiterate_str( string_format(
-                                   _( "How many liters of %s to buy?  Max: %d L.  (0 to cancel)" ), fuelType, maximum_liters ) );
+                                   _( "How many liters of %s to buy?  Max: %d L.  (0 to cancel)" ), fuelTypeStr, maximum_liters ) );
         int liters = string_input_popup()
                      .title( popupmsg )
                      .width( 20 )
```
