### ISSUE TITLE
Sound/music from soundpack becomes permanently louder after alt-tabbing

### ISSUE THREAD

**Issue by mkrutov** [CleverRaven/Cataclysm-DDA#53593]
### Describe the bug

When game is playing music, and you alt-tab out of it, there is a 2/3 chance of music becoming louder. It is a one-time event which would keep the music at new 66%ish louder state until one:
a) restarts game
b) goes to options & changes loudness. 

Loudness values stay the same, so if I have it at 10 then it stays at 10, and I need to up/down it by 1 to get it back to original state.

### Steps to reproduce

1. Enable soundpack
2. Wait till it starts playing music
3. alt-tab
4. if it doesn't work on first alt tab, wait till music track switches to next one and alt-tab again.

### Expected behavior

No changes to volume on alt tab

### Versions and configuration

These are the outputs for the experimental build of commit 9da956adf361cf7821cacca42af3547b9f4e15f6

Linux, pipewire (I didn't test with pulseaudio, but I'm pretty sure behavior was same when I was using pulseaudio), pure ALSA as well.

### Additional context

This behaviour is not consistent to reproduce, only consistent thing about it is that if volume increases it stays at increased state until one changes volume settings or restarts the game.

It happens however a lot, I feel it is almost 2/3 of alt-tabbing which triggers this behavior.

**Comment by mkrutov** [comment]
It might be related to characters's deafness status, or to plugged earplugs/headphones from mp3 player.

**Comment by hexagonrecursion** [comment]
Please include the relevant information:
1. Which sound pack you are using and where did you get it from
2. The game version and configuration report: Main menu (ESC) > Debug Menu > Info > Generate game report.

**Comment by mkrutov** [comment]
@hexagonrecursion , I don't know how exact sound pack would be related to this. I've reproduced it on otopack.

report of current version on which I also reproduced it is:

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 00a57e1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Blaze Industries [blazeindustries],
    Disable NPC Needs [no_npc_food],
]

distro doesn't matter, same happens on fedora on different hardware.
sound system doesn't matter, pipewire, pulseaudio and alsa exhibit same problem once in a while.

**Comment by hexagonrecursion** [comment]
I am sorry, but I could not reproduce your issue. Could you please upload your config folder? BTW: is there an objective method to measure loudness on Linux?

Soundpack: https://github.com/Fris0uman/CDDA-Soundpacks

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 35 (Thirty Five); Release: 35; Codename: ThirtyFive; 
- Game Version: 524a7db [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by hexagonrecursion** [comment]
I could not reproduce the issue with ottopack (https://discourse.cataclysmdda.org/t/soundpack-otopack/23190) either.

**Comment by mkrutov** [comment]
Okay, so couple more relevant things:

1) I'm using KDE. May be switching between active windows does something differently in different WMs? May be KMix is affecting it somehow? 

2) I'm using HDMI sound on amdgpu.

3) Problem is not noticeable on high sound volume, if I set all volumes in CDDA sound configuration to 10 it becomes much more noticeable.

4) Other SDL applications/games I use don't behave the way I describe. 

>is there an objective method to measure loudness on Linux?

If there is, I don't know of it.

>Could you please upload your config folder
Sure.

**Comment by hexagonrecursion** [comment]
1. I have added kde via `sudo dnf groupinstall kde-desktop-environment`  and tried both plasma (Wayland) and plasma (X11)
2. HDMI; NVIDIA GK107
3. music, sound & ambient: 10/100

I still could not reproduce the issue.

**Comment by mkrutov** [comment]
[config.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/7799131/config.tar.gz)
config- unsure why exactly it didnt' attach previously.

@hexagonrecursion , thanks for your effort. I don't know why it doesn't reproduce for you since its an extremely common occurance for me, both on fedora (little bit different hardware, laptop with bluetooth headphones and some ic97 audio) and on arch.

**Comment by hexagonrecursion** [comment]
A screencast demonstrating the issue might be helpful.

**Comment by mkrutov** [comment]
I haven't been observing this issue in quite some time, it subtly disappeared at some unknown point in time. May be pipewire update fixed something to do with SDL at some point or sometihng? don't know. 

Closing for the time being.
