### ISSUE TITLE
bright at 4AM?

### ISSUE THREAD

**Issue by YourCompanionCube** [CleverRaven/Cataclysm-DDA#53595]
### Describe the bug

The in game watch says it's 4AM but it's as bright as it is at noon

### Steps to reproduce

i have *no idea*

### Expected behavior

that it would be dark

### Screenshots

![image](https://user-images.githubusercontent.com/26364270/146688366-b80c22f8-f469-4525-bb3d-b1d189addbbf.png)
![image](https://user-images.githubusercontent.com/26364270/146688385-83fba41d-31fa-400e-8eb1-849c63fb31b2.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 373cf4e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Stats Through Skills [StatsThroughSkills],
    Useful Helicopters Experimental [useful_helicopters],
    SpeedyDex [speedydex],
    Extra Mutated Scenarios [extra_mut_scens],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

[Save File](https://github.com/CleverRaven/Cataclysm-DDA/files/7741470/Manhasset.Hills.zip)

**Comment by NetSysFire** [comment]
I am fairly sure this is intended. As far as I know "Day 64 of Spring" means basically april and the sun starts rising earlier at this time of the year. However, it seems that this happens even in the deepest of winter when I changed the time via the debug menu.

On the other hand, the sun will set at like 7 PM.

**Comment by Hirmuolio** [comment]
Day 1 of spring is March equinox (approx march 20th).  
Spring day 64 would then be somewhere around May 22nd.
Using this calculator https://gml.noaa.gov/grad/solcalc/azel.html for Boston (approx where game is located) on May 22nd at 4:45 the Sun would be at elevation of 4.11° above horizont.  
So it is bright at that time.

**Comment by YourCompanionCube** [comment]
weird, i've never seen the sun rise that early and i don't live that far from new england. 
you learn something new every day

**Comment by Snaaty** [comment]
Hello,
I've also noticed this phenomenon and it feels a bit inappropriate? In my recent playthrough I could observe everything being quite bright as early as 4:15 AM on the first day, so March 20th. 

Google tells me the sun in Boston (which is approximately the are CDDA takes place, I think?, not a native) rises at 6:48 AM on the 20th of march. Seems like CDDA is over two hours early then? 
![Screenshot (6)](https://user-images.githubusercontent.com/8500479/214061887-a67ccc35-ef7f-4054-a5e0-021eef3f07c6.png)
