### ISSUE TITLE
The hazardous waste sarcophagus should not have zombies inside them

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#53591]
### Describe the bug

There are already only robots in the upper level because of the radiation, so why are there so many ordinary (!) zombies in the lower level?

### Steps to reproduce

1. Teleport into the lower level of a hazardous waste sarcophagus.
2. Have a horde of zombies

### Expected behavior

There are two ways of solving this:

- Adding a few very dangerous creatures down there (maybe something something slime?) because radiation + blob + portal storms do not mix. There should no humans be in there, so maybe add some slime-like blob monster? Or if a foolish technician tried to take shelter in there he died and mutated.
- Add some lore why the zombies are in there. They certainly could not have wandered in. One possibility is to add some secret military snippets saying that there are some heavily infected corpses or they ran out of space in the mass graves or something and they put the corpses in there.

In any case, ordinary zombies do not belong there.

### Versions and configuration

- experimental

### Additional context

On a related note, the hazardous waste sarcophagus currently looks like solid earth, which might need to get fixed.

**Comment by Night-Pryanik** [comment]
I always thought that government just dumped there all "dead" rioters they killed in the first stages of pre-cataclysm riots. Then they all resurrected in zombie form.

**Comment by NetSysFire** [comment]
As of master right now, there are even ferals down there. I would argue they *definitely* do not belong there.
