### ISSUE TITLE
[Magiclysm] Technomancer mana-toolbar spending charges incorrectly

### ISSUE THREAD

**Issue by lapis413** [CleverRaven/Cataclysm-DDA#53607]
### Describe the bug

While using the technomancer mana-toolbar, charges are used in order to pry open windows and doors, even though they should presumably only be used by casting mirror image from it. When out of charges, the toolbar is unable to pry windows or doors.

### Steps to reproduce

1. Spawn a technomancer mana-toolbar, attempt to pry a window or door, see that it doesn't work.
2. Wait long enough for the toolbar to gain 1 charge
3. Pry the window or door again, see it successfully pry but lose 1 charge for doing so.

### Expected behavior

For prying objects open to not spend any charges of the spell in the item.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 9bbe06e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Stats Through Kills [stats_through_kills]
]

**Comment by hexagonrecursion** [comment]
Confirmed: charges drain when prying. After they run out prying fails with a chat message: "Your Technomancer mana-toolbar ran out of charges"

Related:  #30137

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 579f907 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]
]
