### ISSUE TITLE
For Modders resources, please add a modifier for drugs/traits/enchantments that modifies how much stamina is spent on certain actions (fighting, running, etc.)

### ISSUE THREAD

**Issue by cataclysmsurvivalist** [CleverRaven/Cataclysm-DDA#53601]
### Is your feature request related to a problem? Please describe.

In order to diversify mutation types and future branches, this might be a good way to ensure they feel differentiated from each other rather than a plain "max_stamina_modifier' or 'stamina_regen_modifier'.

### Solution you would like.

stamina_cost_running, stamina_cost_attack, stamina_regen_laying, and other conditioners for how stamina is spent and dealt with. And if this is too little, it's not just stamina, but many other factors, like stats or health regen, could be modified this way to give the community better tools when working/modding the game.

**Comment by ZhilkinSerg** [comment]
Are you making up these parameters or do they exist in the code?

**Comment by cataclysmsurvivalist** [comment]
I'm making them up as examples, I mean if they existed already I wouldn't even need to ask them to be added, right?

**Comment by ZhilkinSerg** [comment]
If you are making a feature request you need to be more specific than this. Right now it is not exactly clear which specific goal you are trying to achieve, what you have tried already and what is lacking.

Say, you wanted to add stamina modifier for specific traits for running movement mode. You already knew `effect` can modify stamina, created such effect and tried to assign it through `effect_on_condition`, but found out `effect_on_condition` lack any conditions related to running (or any other movement modes). Then you could request to add some movement mode related conditions.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
