### ISSUE TITLE
Firewood Zone being very unsmart about what it uses

### ISSUE THREAD

**Issue by JyeGuru** [CleverRaven/Cataclysm-DDA#53608]
### Describe the bug

Had a firewood zone that was only planks. Accidentally used `\` to drag some stuff around my base and ended up with other spare parts on the pile. Apparently my character isn't smart enough to use the planks first.

![image](https://user-images.githubusercontent.com/5215014/146710023-3e3e6964-d3e6-47ce-a093-cbb47a35ee08.png)

Parts list (minus the stuff that was burned, now separated):
![image](https://user-images.githubusercontent.com/5215014/146710212-ec56fe44-cb66-45fe-8a88-d2200a99f99c.png)

### Steps to reproduce

1. Have a pile of misc spare parts (see list above) including planks on a Firewood Zone (created via `Y` not via `*` if that matters)
2. Light the fire
3. Craft something that takes a while

### Expected behavior

Character is smart enough to prioritise "fuel" items (planks/sticks/wood panels) over other items (rubber hoses and copper wire)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 40dc4e5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    My Sweet Cataclysm [my_sweet_cataclysm]
]

**Comment by ZhilkinSerg** [comment]
That is what zone is for - all usable items from designated zone are used for specific purpose of the zone. Game doesn't know if you have decided to stoke fire with your rubber hoses or not.

**Comment by Maddremor** [comment]
Using a bunch of trash as fuel is actually really convenient if you ask me. Planks can be used for crafting. Make a bookcase or something as to not accidentally haul over it.

**Comment by PatrikLundell** [comment]
I agree that anything that can burn within a firewood zone should be available to be used as fuel, but not things that can't burn (copper wire, for instance, won't burn unless there's plastic insulation on it).

**Comment by morthein** [comment]
> Using a bunch of trash as fuel is actually really convenient if you ask me.

Perhaps wooden objects should be given higher priority only if they're in the firewood zone. But, keep the idea that *any* flammable item in there can also be used. It's an amazing way to hobo heat your house/food/drinks. Especially when winter hits and everything freezes :(

**Comment by JyeGuru** [comment]
In an ideal world, I'd like to see an interface like the armor layering thing where you can select what should get burned in what order, but I presume that would be a lot of work. I'm not sure there would be a consensus on what order things should be burned in either, if it was to be hard-coded in some way.

Would it be possible to (ab)use the favorite tag to deprioritise things from being burned?

**Comment by PatrikLundell** [comment]
Depending on your situation, planks may be desirable to use for firewood, or kept for construction/crafting. Similarly, logs may be in demand for construction and charcoal making in addition to fuel, so a static priority list probably won't work.

**Comment by morthein** [comment]
> so a static priority list probably won't work.

Yes, I see what you mean.   Hmm.  This might need some good brainstorming.
