### ISSUE TITLE
Fold athletics skill into cardio

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#53619]
### Is your feature request related to a problem? Please describe.

The athletics skill is basically useless right now, consigned only to swimming. In addition, we also have a cardio system, separate from the athletics skill, but serving the same function for stamina when running

### Solution you would like.

Fold these two systems together. Either make the cardio system visible somehow through the athletics skill, or, more likely, remove the athletics skill completely and use cardio for both swimming and running. More visibility on the cardio and stamina system would be nice too.

### Describe alternatives you have considered.

I mean, we don't have to do this, but it would be kind of neat.

**Comment by Inglonias** [comment]
Actually, it would be really cool if we could use the cardio system to have an "effective" athletics skill, similar to how we use encumbrance to have an "effective" dodge skill.

**Comment by Tommy-os** [comment]
Atheltics is already a factor in cardio.

`const int athletics_mod = get_skill_level( skill_swimming ) * 10;
...
int final_cardio_fitness = bmr / 2 + athletics_mod + health_effect + trait_mod + prof_mod +
                               cardio_acc_mod;`

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/character.cpp#L6317

**Comment by nexusmrsep** [comment]
Every skill has two characteristics: it has to be trainable somehow and it must serve a purpose somehow.
Athletics as a skill is problematic in a current form as it conceptually overlaps strength (stat) and cardio (discrete mechanic), but finally cannot decide what it realy is.

So we actually should start from answering the question: what is athletics?
1. If the answer is: muscle mass and muscle strength, then the overlap is more with strength then cardio, and it would affect strength based activities, perhaps introducing a sort of `stats-from-skills` "mod" but for a singular skill and singular stat.
2. If the answer is: muscle fitness for prolonged activity, then it overlaps cardio more then strength, and it might be used by for example reducing stamina cost of actions (example: lets say every tile you run eats flat `20` stamina, but it could be: `20 - athletics`)

Problem with first approach is that as of now the game balance imply static stats, set in stone at character creation. It was already discussed at least few times how many months one would need to spend in the gym to get 1 point of strength in game units. Thus it is doubtful that strength-through-athletics would be approved, although if the skill levels were in a certain ratio to the "power" of 1 point of strength, then who knows? But then what's the point for the skill that has negligible effect?

Problem with the second approach is that cardio system is (I guess) a go-to system to govern stamina from the players perspective (answer to question: what can I do to get my stamina management better). Stamina's influence on game balance and gameplay is governed by 3 factors: stamina pool (max stamina), stamina regen ratio, stamina consumption ratio - if any skill, mechanic, trait, mutation touches one of these - the in game effect is apparent. Cardio's final effect defines max stamina (pool). Theoretically this leaves stamina regen and stamina consumption as possible targets of athletics. But then again: overlap - you already gain cardio/stamina by activity, so why gain athletics/stamina simultaneously - as that would do literally the same?

So in fact there are arguments to remove athletics altogether - lets not forget that it was migrated from the swimming skill.

> Actually, it would be really cool if we could use the cardio system to have an "effective" athletics skill, similar to how we use encumbrance to have an "effective" dodge skill.

They are too far apart - rather, after removing athletics, cardio fitness should be exposed to the player in some form - there is no reason to why is should be hidden - you know if you are capable of running 50 meters or a marathon. If there are concerns about giving exact quantified measurements - give the info in blocks similarly to how weight is described.

**Comment by Photoloss** [comment]
> Cardio's final effect defines max stamina (pool).

Does cardio not affect stamina regen at all? The mutation modifier for "maximum" stamina grants just as much of a regen boost as the actual regen modifier!

And stamina consumption would need more granularity for arms/legs, burst/endurance, strength/speed etc. With the current UI that wouldn't really work with Proficiencies let alone Skills.

**Comment by Terrorforge** [comment]
> Does cardio not affect stamina regen at all? The mutation modifier for "maximum" stamina grants just as much of a regen boost as the actual regen modifier!

It does. According to the original spec, regen is 5 + [Cardio/100]. And anecdotally, my 200cm Fast Metabolism characters (BMR ca. 3.4k) have no problems regenerating stamina even through a gas mask.

**Comment by wapcaplet** [comment]
Cardio and stamina are in a pretty bugged condition right now (see #53603) - the max stamina modifier is definitely broken, and none of the size-related and cardio-related mutations are working correctly with respect to stamina and stamina regen. So you can probably ignore most of the current behavior of those factors.

**Comment by nexusmrsep** [comment]
Thus definitely calling for a dedicated test suite.

**Comment by l29ah** [comment]
Tested the athletics impact on stamina on today's master: it only adds about 0.5% to max stamina pool size per skill level, so much less than one sprinted tile :/
