### ISSUE TITLE
Using candles for welding rod recipe unloads candles into candle wax, doesn't use.

### ISSUE THREAD

**Issue by epsimpson** [CleverRaven/Cataclysm-DDA#53623]
### Describe the bug

I batch fabricated 2 batches of welding rod, choosing to use 2 candles.  I received following messages twice:
You put the candle wax in your inventory.
\- candle wax
You unload your candle.
After finishing my inventory had:
AMMO
Candle wax (72)
Candle wax (87)

The welding rod recipe allows you to use wax as a consumable, but not candle wax, so the resulting wax is useless.

### Steps to reproduce

Fabricate welding rod using a candle.

### Expected behavior

Only as much of a candle as is needed is used for crafting.

I would actually expect candle wax as a recipe ingredient for welding rod (not candles) with candles able to be disassembled into candle wax.

Alternately, if tallow is a realistic option, then tallow would be the recipe ingredient and candles might be disassembled into tallow, because then new candles could be remade using the remains of old ones.

### Screenshots

![Screenshot_unloadCandle](https://user-images.githubusercontent.com/64863108/146806567-a1888221-75a1-4ff4-b5ad-21bcee746cad.png)
![Screenshot_candleWax](https://user-images.githubusercontent.com/64863108/146806606-8774174c-fb01-472f-a34f-66e285f9ec84.png)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.3 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-4495-g40dc4e5d11 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by epsimpson** [comment]
Sorry, to clarify, the fabrication was a success, just produced all that waste candle wax.

**Comment by Alex-Folts** [comment]
I'll look what can be done, there is some issues with candles. 
Basically wax is just one of alternative for binding agents, so yes there suppose to be candle wax itself, not the candle. I think back then you couldnt disassemble candle nor get candle wax out.

**Comment by dseguin** [comment]
> I'll look what can be done, there is some issues with candles. Basically wax is just one of alternative for binding agents, so yes there suppose to be candle wax itself, not the candle. I think back then you couldnt disassemble candle nor get candle wax out.
> 
> edit: you still can't disassemble candle nor get wax from it. and recipe cant use candle wax from candle directly. So i think i'll just remove candle from recipe. Or add uncraft recipe for disassembling candle into candle wax. The idea was to utilize candles somehow as over time they just keep stockpiling.

This is not an issue with the welding rod recipe, it's just a bug that I introduced when adding non-empty containers as crafting ingredients. This will be fixed by #53302.

**Comment by epsimpson** [comment]
I'm still learning to understand github but it looks like this should be fixed.  Unfortunately, as of 0.F-4569-g3acaa917ee this is still happening.

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.3 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-4569-g3acaa917ee [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Alex-Folts** [comment]
You should reopen this issue.
