### ISSUE TITLE
Use actions should be able to override their assigned charge_per_use

### ISSUE THREAD

**Issue by Stone94** [CleverRaven/Cataclysm-DDA#53620]
### Is your feature request related to a problem? Please describe.

Currently, if we have an item that has multiple tool uses, we are limited to a single power draw, for example, if you give the soldering guns use action to the firearm repair kit you are unable to adjust the power cost and a single use would use 100 charges, instead of the charges that would have used had you just used the soldering iron.

### Solution you would like.

I would like to be able to be able to override values in JSON 

` So this is the current way the repair kit handles gun repair, if we were to copy the soldering guns repair action it would use the 100 charges per use and drain very quickly.

    "id": "small_repairkit",
    "type": "TOOL",
    "name": { "str": "firearm repair kit" },
    "charges_per_use": 100, 

    "use_action": [ "GUN_REPAIR", [ "CROWBAR", 0 ], [ "HAMMER", 0 ], [ "HACKSAW", 0 ] ],

`  on the other hand, The soldering gun uses a scaling method for usage (If i understand this correctly)

    "id": "soldering_iron",
    "type": "TOOL",
    "name": { "str": "soldering iron" },
    "charges_per_use": 1,
    "use_action": [
      {
        "type": "repair_item",
        "item_action_type": "repair_metal",
        "materials": [ "plastic", "lead", "tin", "zinc" ],
        "skill": "fabrication",
        "cost_scaling": 0.1, // I believe this scales the power usage based on the move cost.
        "move_cost": 1500
      },
`

`   One possible solution I can think of would be to override fields within the action itself to further customize items.

    "id": "small_repairkit",
    "type": "TOOL",
    "name": { "str": "firearm repair kit" },
    "charges_per_use": 100,

    "use_action": [ "GUN_REPAIR", [ "CROWBAR", 0 ], [ "HAMMER", 0 ], [ "HACKSAW", 0 ],
      {
        "type": "repair_item",
        "item_action_type": "repair_metal",
        "materials": [ "plastic", "lead", "tin", "zinc" ],
        "skill": "fabrication",
        "override charges_per_use": 1, <<<<<
        "cost_scaling": 0.1,
        "move_cost": 1500
      },

I believe that the addition of this accessibility can carry to other aspects of JSON and be beneficial in more than this one case. Since some tools may draw more or less power than others.

### Describe alternatives you have considered.

Another alternative would be to change GUN_REPAIR to use the same or similar system as the soldering gun:

`

      {
        "type": "repair_item",
        "item_action_type": "repair_gun",
        "skill": "gun",
        "cost_scaling": 0.1,
        "move_cost": 1500
      },
`

Other than adding more customization or changes to JSON, I've considered changing both the Firearm kit and Gunsmithing kit to a container like a first aid kit but with tools.

### Additional context

I've checked through the JSON docs and haven't found any info on the repair actions,

**Comment by new02DAY** [comment]
I'm working on #54116 and ran into this problem. I'm wondering if we should just change the cost per use of the kits to match the soldering iron? Since the soldering iron is the entire basis of the energy costs. The only difference between kits would be battery size. I think it'd be a good compromise until there's a change in how the kits are handled (vs. toolbox changes).

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
