### ISSUE TITLE
Treat ballistic plates like ammo

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#53624]
### Is your feature request related to a problem? Please describe.

Ballistic plates are cool and useful, but they're kind of annoying to manage. Either they take up space in your inventory view, or you hide the contents and make it hard to see if any of the mare shattered. And when one does shatter, you have to manually take it out of the vest (making sure not to drop it in your storage because it's just trash now) and then manually insert a new plate. For some reason you can't even insert all the plates at once, you have to do first one type and then the other.

### Solution you would like.

Make it possible to (r)eload the relevant armors the way you can tools and weapons. Maybe also hide the plates and just have a little counter in the name, like how cartridges in a magazine work.

**Comment by Photoloss** [comment]
And make shattered plates work like spent brass in a revolver, "EJECT_ON_RELOAD" casings.
