### ISSUE TITLE
NPC Hallucination Fire real weapons

### ISSUE THREAD

**Issue by EirenexTheDragon** [CleverRaven/Cataclysm-DDA#53621]
### Describe the bug

When i was hallucinating, i angered a Npc with a Mp40 semi auto and he shot me with real bullets as i came close. the damage was real, so were the 9x19mm casings on the grounds. i know it was a hallucination Npc because it left no corpse nor other items behind on death

### Steps to reproduce

1.Make your character Hallucinate. i used Pink tablets for that
2. Wait until a Npc with a gun spawns (took me a while, maybe theres a easier command to spawn hallu npc?)
3. Anger Npc and let it shoot at you

### Expected behavior

For Guns on NPC you hallucinate to not fire real bullets, to neither leave behinds

### Screenshots

![grafik](https://user-images.githubusercontent.com/41762755/146788456-37d45856-3ba4-4b5d-92b8-2fb395e73e0b.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 519d1b5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Unsure if it does that with every weapon, so it could really just have been with that Mp40-semi auto or some of the newer guns that havent been made hallucination variants off?

I know version is a few days off but i couldnt find any changes to hallucinations so it should still be valid

**Comment by Inglonias** [comment]
Update your experimental. This was fixed with #53538
