### ISSUE TITLE
Natural caves are surprisingly bright, sunny places, open to the sky

### ISSUE THREAD

**Issue by pjf** [CleverRaven/Cataclysm-DDA#53637]
### Describe the bug

All the caves in `mapgen/cave.json` are bright and sunny, with their ground-level insides open to the sky.

This is probably because they define the inside as `t_rock_roof`, which means the *floor* of the cave ends up being a "rock roof".

I'm guessing the palette can be replaced with `t_rock_floor`, but it's late in Australia and I don't have time to test.

### Steps to reproduce

1. Find a cave during the day
2. Walk around inside, looking at the sky
3. Go up one z-level to observe the lack of roof.

### Expected behavior

Caves are caves and can provide shelter. Otherwise they're gullies or ravines.

### Versions and configuration

- Version `cdda-experimental-2021-12-21-0353`
- No Hope mod used

**Comment by NetSysFire** [comment]
![image](https://user-images.githubusercontent.com/59517351/146957354-bb41b83d-5058-4c73-8fd1-d86839d49ad3.png)

Could reproduce.

**Comment by VanSHOE** [comment]
While trying to figure out how map gen works
I saw that in cave.json, there are multiple entries by the name cave, and no roof entries
All the floors themselves are made of t_rock_roof

Are roofs defined anywhere like for other buildings, or is this the actual issue?
