### ISSUE TITLE
Limited-water ponds still show as infinite when washing clothes

### ISSUE THREAD

**Issue by JyeGuru** [CleverRaven/Cataclysm-DDA#53638]
### Describe the bug

This is referring to the little one-tile ponds that were recently changed to have a limited amount of water in them. When washing clothes next to one, the interface still shows infinite and water does not appear to be consumed.

### Steps to reproduce

1. Craft a washboard
2. Get some filthy clothes
3. Find a puddle
4. Activate washboard
5. See that water shows as `0/inf`

### Expected behavior

Water shows as the amount in the nearby puddle(s)

### Screenshots

![image](https://user-images.githubusercontent.com/5215014/146944465-bdf984d7-68c3-4f22-bcb5-ab0153325f72.png)
![image](https://user-images.githubusercontent.com/5215014/146944513-b15bba63-ff1b-43a8-b981-faa475775f1f.png)
![image](https://user-images.githubusercontent.com/5215014/146944740-d77aaf9b-0e7f-4eea-b076-6eb55a46a5ca.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 49c6f2d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    My Sweet Cataclysm [my_sweet_cataclysm]
]

**Comment by NetSysFire** [comment]
This is because it *is* infinite. I just reproduced it next to a puddle and it did not reduce the water in the puddle, so it is technically infinite which is also a bug.

**Comment by RoyBerube** [comment]
It will also allow frozen water from the shallow pit as a water source.
