### ISSUE TITLE
Portal Storm Forever

### ISSUE THREAD

**Issue by morthein** [CleverRaven/Cataclysm-DDA#53642]
### Describe the bug

It seems like the storm in my game is lasting forever. I went on reddit to see about how long it stays since I never had one and they seem to say hours to a couple days. Mine has been like a week, but I noticed also online that people seem to talk about a portal forever bug?  Didn't see much about this on github so making a report about it since my game seems to maybe have that.

### Steps to reproduce

1. wait for a portal storm or debug change it
2. wait, see if it ever goes away, mine isn't.

### Expected behavior

It sticks around for awhile, then leaves.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 00a57e1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    No Hope [no_hope],
    Alternative Map Key [alt_map_key],
    Crazy Cataclysm [crazy_cataclysm],
    Extra Mutated Scenarios [extra_mut_scens],
    Mining Mod [Mining_Mod],
    No Rail Stations [No_Rail_Stations],
    Cars to Wrecks [cars_to_wrecks],
    Graphical Overmap [Graphical_Overmap],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by morthein** [comment]
For some reason it won't let me add the .zip with my game in it. I've done it before on another post (same game, different issue).  so...uhh.  I'm not sure what to do it just says "is not included in the list" and blocks the upload.

**Comment by Terrorforge** [comment]
Have you tried "Save and quit" and then loading? I also had a seemingly-infinite portal storm (#52491), but it cleared up shortly after I loaded the save again.

**Comment by morthein** [comment]
I did save and quit and try again and it stuck around for a couple of days before I just quit and started a new game. I still have the save, but I was waiting to see what was said before I debugged it gone. <--- feels cheat-y

**Comment by Ramza13** [comment]
Rats I had hoped #53435 would fix this.  If you have still have the save and it reproduces the issue I would love a copy because reproducing the issue has been hard for me so far.  If github isnt working are you able to share it via google drive or dropbox or something?  thanks

**Comment by Ramza13** [comment]
Is there any chance you were playing in a preexisting world you already had a character active in?

**Comment by morthein** [comment]
I'm trying to upload it to google drive.   Yeah, this is a game that i've had for about a few weeks.  I see your fix is 4 days old, but I have updated recently.

**Comment by morthein** [comment]
https://drive.google.com/file/d/11Dot3NxYSC5l6BZRFe3eAADzfU1FQejJ/view?usp=sharing

**Comment by Ramza13** [comment]
Thanks that save clarified exactly what happened in this case.  I think #53435 actually caused it.   I'm pretty sure the issue you have here should only happen if you updated to #53435 in the middle of a portal storm.  Basically I changed the way portal storms end and upgrading in the middle of a storm won't work correctly.  

For the moment you can use this item(add it to any json file you like and then debug spawn one) to end the storm. Everything should work normally after one use.
```
 {
    "id": "test_EOC",
    "type": "TOOL",
    "name": { "str_sp": "Test EOC" },
    "description": "Tests.",
    "weight": "1 g",
    "volume": "250 ml",
    "symbol": "!",
    "color": "light_red",
    "use_action": {
      "type": "effect_on_conditions",
      "description": "Touch the opening.",
      "effect_on_conditions": [ "EOC_CANCEL_PORTAL_STORM" ]
    }
  }
```

Fixing the actual issue in this case would be a lot of work and since it should only happen on updating between experimental versions I am not planning on fixing it.  

If this happens again to you then I am wrong about all of this and please let me know so I can get handle the issue.

**Comment by morthein** [comment]
oh ok.  cool, I can just debug quit it.  Thanks for checking it out.
