### ISSUE TITLE
Soft containers allows far less objects than they should

### ISSUE THREAD

**Issue by hostergaard** [CleverRaven/Cataclysm-DDA#53641]
### Describe the bug

When adding rigid objects to soft containers it allows far less than the volume and weight limits should allow.

I noted that it apparently only affects items with a length, aka rigid objects and as best I can tell the issue seem to be that apparently the game places every object sequentially or in a line when calculating if it can allow another item to be inserted. Or in other words, it adds all item lengths together already in the container together with the item you want to insert in and if the total is less than the allowed length it can be inserted, if not then you can't.

This makes no sense as you could simply place the items beside each other in the container instead of a line, the volume calculation sufficiently handles that. It should not add them all together and simply just check if the item inserted is less than what the bag allows without consideration to what is already in there.

Bug was discovered while trying to place small plastic bottles of container value 84mm in a plastic bag. It will allow 3 but not 4, the bag allows for 254mm so its my guess its an issue of length of all items in total. 

### Steps to reproduce

1. Get a plastic bag allowing 254mm of objects
2. Attempt to insert 4 plastic painkiller bottles of 84mm length each, totaling 336mm
3. Only 3 is inserted, totalling 254mm of container size
4. Cannot insert another small plastic painkiller bottle

### Expected behavior

Given that the pill bottles have a volume of 0.25L and the plastic bag can contain a volume of 6L then there should be room for 24 plastic painkiller bottles

### Versions and configuration

OS:  Windows 10

Version: 9473cf6 (tiles) 2021-12-17-0851 (2 days ago) Experimental

Mods: Lots

### Additional context

Might be a minor side bug, but at first I tought it was item length, but the plastic painkiller bottles are described as being 6cm but its pocket length allows for 84mm. If it was item length it would allow at least 4 bottles, but it only allows for 3 so it seems that for this it uses the length of allowed items of the pocket of the bottle rather than the actual item length. The side bug might be that the bottle allows for items longer than itself, although that is not entirely impossible as an item could be resting diagonally in the pocket and so according to pytagoras the allowed length should be a bit more than total length of the pocket itself. The problem I guess is more that its used for the purpose of calculating allowed length when its being inserted in containers (and that its all added together).

**Comment by Terrorforge** [comment]
This is likely just you having the plastic bag inside a container that can't fit the last bottle. Try (w)ielding the plastic bag, you should be able to fit everything in.

For reference:
![image](https://user-images.githubusercontent.com/5107449/146961089-7e4d5ad8-ec1f-4c99-a39d-ede82d0a5eca.png)
