### ISSUE TITLE
Have pocket pick up specific number of items (and costum items via labels)

### ISSUE THREAD

**Issue by hostergaard** [CleverRaven/Cataclysm-DDA#53643]
### Is your feature request related to a problem? Please describe.

Its kind of annoying when you want specific items to always be with you, particularly a specific number. Like, I want to bring 10 bandages with me always. 

### Solution you would like.

Being able to define specific number of items in a pocket or container to be picket up. Like, I want to keep with me a small supply of bandages and pills, right now I do it with a bunch of small pill bottles with high priority so I dont take too many of each and know that I have room. It would be nice to be able to say, hey, in this specific pocked I want to carry 10 bandages and 20 painkillers. More advanced it would be nice to able to make a and or system, so I can say 10 of bandages OR makeshift bandages and even better if I can prioritize which one I chose when more is available.

Note that it would be nice to also have options like more than, less than and exactly. So you can say have less than this of said item or exactly this. 

And another little detail would also be costum whitelist/blacklist. I have a habit of adding labels to things I carry, like "crowbar xCarry" that I use for shorting zones, so I short everything with a xCarry label into a zone so I can easily find the things I cary with me. Would be nice to have that work with pockets too. And to add to that, when you short out in zones it would fill up on things you designate as wanting to x number of in a given pocket.

### Describe alternatives you have considered.

Could be to somehow make autopickup manager (the one from the escape menu) to consider what you already have, like pick up x item when you have less than x item.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
