### ISSUE TITLE
Powered furniture: generator furniture needs its own UI

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#53646]
### Is your feature request related to a problem? Please describe.

We now have an excellent framework for stationary base power grids, made by @fris0uman. This uses the basic code for vehicles, but slices and dices it so that individual objects think they are part of the vehicle, but behave like furniture to the player and do not have a complex and out of place vehicle interaction menu.

The trouble is that we do need a few elements of the vehicle interaction menu, particularly for refueling generators and seeing how they are doing.

### Solution you would like.

We should have a simple custom interaction UI for stationary generators. This should be generalizable to gas generators, windmills, solar panels, and anything we might make as a stationary power supply. Mostly it should list power output; it could also list power demand. For generators with a fuel supply it needs to state the capacity and storage of the fuel supply, as well as fuel usage. Something along these lines:
![image](https://user-images.githubusercontent.com/45136638/146976505-36228a9a-f0a2-4741-84a2-05ff60c2c458.png)

The same UI might also be adapted to non-generator storage tanks for liquids, since we'll want to be able to have standing tanks that can pour into the generator, as well as potentially powered water heaters and things. So to summarize, this UI should be generally adaptable to:
- Solar panels, windmills, etc. to show current power output
- fuel powered generators to show power output, fuel storage in the grid, and fuel usage, as well as refuel and siphon options
- liquid storage containers to show liquid stored in this container

### Describe alternatives you have considered.

We could reinstate the vehicle interface just for these containers but that will be incredibly clunky and most of the information will be irrelevant.

### Additional context

There may be other use cases for a special interaction menu that I've forgotten. Let me know

**Comment by PatrikLundell** [comment]
I can imagine heaters/AC down the line, where you may want to set the desired temperature (actually being able to live in your "base" would be useful).
Heated liquid storage containers to keep the stored content liquid would be useful as well.
Computer controlled stills and chemical manipulation equipment powered via the grid to allow them to operate without human oversight would be useful, in particular if chemical manufacture gets set to take weeks for some steps.

A possible alternative or complement to a standard interaction for appliances might be a control panel to display and control the grid and its equipment (similar to the vehicle one in principle, but not necessarily in layout).

**Comment by Stone94** [comment]
I'd like to see a similar menu for appliances, but instead just showing a list of parts in the appliance to allow you to take specific parts and troubleshooting and parts that may need to be replaced, such as elements for ovens, compressors for refrigerators etc.
