### ISSUE TITLE
Add item description for vehicle components and appliances

### ISSUE THREAD

**Issue by Photoloss** [CleverRaven/Cataclysm-DDA#53655]
### Is your feature request related to a problem? Please describe.

For a long time seemingly random items have held particular value for their usage as vehicle components. These are not always obvious, using "hand mirrors" for inboard mirrors or "micro motors" as curtain motors next to the impossibility of plugging in a coffee maker or hotplate for example. An expansion of the stationary appliance system will only exacerbate this problem, while not every appliance will be suitable for vehicle integration there is no in-universe reason to deny plugging in a minifridge for example. Crafting category assignments can never cover items with both options, nor can they alert the player to valuable loot items in the field.

### Solution you would like.

Add two bullet points to the typical "misc item properties" bullet points where we also find conductance and weapon/armour flags.

One for

* This item can be <highlight colour\>installed in a vehicle.</highlight colour\>

and another for

* This item can be <highlight colour\>plugged in as an appliance.</highlight colour\>

These probably require new JSON item flags to toggle the indicator as querying furniture construction and vehicle component data for every item or vice versa seems inefficient.

Optionally a third flag

* This item can be <highlight colour\>used in vehicle construction.</highlight colour\>

might be useful to denote consumable components (nails, welding rods, superglue, rubber cement) which are not the installed components themselves but used in a supporting function as the "You could use it to craft:" tooltip does not adequately highlight vehicle applications. But it doesn't handle construction, faction camp or special item use either so this is far less of an issue and most of these components are fairly common anyway.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
