### ISSUE TITLE
Scale item retrieval time with occupancy/clutter

### ISSUE THREAD

**Issue by Photoloss** [CleverRaven/Cataclysm-DDA#53657]
### Is your feature request related to a problem? Please describe.

Right now backpacks have a lengthy item retrieval cost to represent rummaging through the large compartment. This does not reflect our ability to reach into an otherwise empty backpack and grab a water bottle. Likewise finding a handful of 8x40 caseless in a large cardboard box or a loot pile on the ground also containing wrenches, broken manhacks, sand etc. should be much slower than picking it up from a sorted shelf.

### Solution you would like.

Add optional values for minimum/maximum retrieval time, probably defaulting invoked-but-unspecified entries to 100 moves as the "standard discrete action" where necessary. Scale the retrieval time of each item based on the fraction of the total contents taken up by its ***type***. Meaning if I have a box full of 100 rocks it should be just as fast to retrieve 1 rock as if I only had 1 rock in the box and nothing else, whereas if I have 99 rocks and one rock-sized bottle in the box retrieving the bottle should take close to the maximum retrieval time and retrieving a rock should take close to the minimum retrieval time.

This functionality should also work with furniture/empty ground, but there should always be an override for things such as store shelves, tool boxes and other containers where a respectable level of organisation can be considered the default. Even regular bags might have [internal compartments](https://thegadgetflow.com/wp-content/uploads/2021/07/Haven-Athletic-The-Large-Duffel-gym-bag-001-1200x1060.jpeg) which don't qualify as independent pockets. Just interpreting the status quo of specifying a single integer move cost on pockets as "minimum" and "maximum" times being equal should suffice.

**Comment by anoobindisguise** [comment]
This could be a good time to give the Packmule and Disorganized traits more effects. Packmules can sift through heavy clutter far better than usual so the penalty is lower, vice versa for disorganizers.
