### ISSUE TITLE
Get rid of "are you sure" prompts for sludge trails

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#53659]
### Is your feature request related to a problem? Please describe.

Sludge trails are not obviously dangerous the same way acid puddles are, they are merely "difficult terrain" equivalent to walking over shallow water, benches, couches, etc. The prompt is needlessly tedious and annoying as it asks every step you take.

### Solution you would like.

Don't ask the player if they want to step in sludge.

### Describe alternatives you have considered.

Do it myself instead of complaining.

**Comment by catdach** [comment]
Personally, I can think of plenty of times where the prompt has saved the life of my characters. The immense slowdown from accidentally stepping in sludge is arguably more punishing than stepping in acid, depending on circumstances of course. Step in acid, you take some damage and are in pain for a while. Step in sludge, every zombie within a few tiles gets a bunch of free hits on you.

**Comment by Terrorforge** [comment]
I'm with catdach on this one, those trails are incredibly dangerous

But the prompts _are_ also very annoying when you're just trying to move after a fight.

So... a toggle hotkey? Or something like smashing, where it only gives you the "are you sure?" prompt if there are hostiles nearby?

**Comment by PatrikLundell** [comment]
I'd probably want something similar to seeing zombies, i.e. the ability to ignore for this "encounter". A possibility would be to mark every sludge tile within view as "ignore", but not have the flag survive an exit/re-entrance into the reality bubble.
