### ISSUE TITLE
Ultica has invisible spiked pit traps

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#53663]
### Describe the bug

I'm being prompted about wanting to move into a trap I can't see.

### Steps to reproduce

1. Load this save:
[Alfred.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7758850/Alfred.zip)
2. Move south
3. Get prompted about a trap

### Expected behavior

I expect to fall into the spiked pit and die.

### Screenshots

![image](https://user-images.githubusercontent.com/2125926/147009564-8b7f2b11-14c4-43fc-8827-9ad8f1eeb43b.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: aac4403 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Fewer Soldier Extras [Fewer_Soldiers]
]

**Comment by Inglonias** [comment]
Ok this looks more like an Ultica display issue than an actual bug.

**Comment by Maleclypse** [comment]
I've changed the tags based on your comment.
Let me know if I misunderstood.

**Comment by PatrikLundell** [comment]
I've encountered this type of a problem as well with whatever the default tile set is (i.e. playing with tiles but not having changed the tile set). I've encountered it near survivalist camps (which probably was pits) and I think I've encountered it with spiked board traps (and I further think I've been able to disable the latter). The version used was 0.F-0 stable and the default set of "mods".
I thought it was a display issue at the time.

**Comment by esotericist** [comment]
looking into it, it looks like the lmoe shelters place the trap without placing the terrain. the fact ultica has no indicator for it is undoubtedly an issue, but the fact the mapgen isn't putting the terrain down is i think the real problem

**Comment by PatrikLundell** [comment]
Thanks for looking into it. I'd suggest also looking at survivalist camp mapgen as well. and possibly any mapgen that places spiked pits. I think Rubik's "castle" has them in a visible form, and I believe the base camp mission to dig trenches and then spike them also results in visible spiked pits.

**Comment by Inglonias** [comment]
The reason the associated terrain is not placed is because the majority of the traps (all but one) are placed randomly. It is not trivial to also associate that with terrain, if I recall correctly.

**Comment by PatrikLundell** [comment]
It's not hard to place terrain with a probability, but it is messy to place sets, as you'd have to define single tile "chunks" that have a probability of appearing at specified tiles, each tile specified separately (i.e. you can't use a palette). 

However, do you need a trap field when the terrain itself is dangerous? If so, the base camp mission is incorrect, as it only places the terrain, I believe. Otherwise, it might be as simple as replacing trap fields with the terrain for the bugged mapgen versions.

**Comment by I-am-Erk** [comment]
Woops, mistook the base cause of this.

I think there are two solutions here:
1. Make the spiked pit trap `looks_like` `t_pit_spiked`, do the same for other terrain-furniture linked traps. This is a sanity check that ensures they won't get skipped on rendering if something goes wrong and will probably resolve this for stable.
2. Find a different way to place random traps in mapgen, or use a trap that doesn't require an underlying terrain. It can be done, especially using nested maps.

**Comment by I-am-Erk** [comment]
OK easy to fix the way this is done in mapgen for this trap.
