### ISSUE TITLE
Can't disassemble heavy items

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#53671]
### Describe the bug

In changing appliance furnitures to a separate detachable item which can be further disassembled, I've run afoul of an old UI issue, where you can't disassemble something too heavy to pick up. This does not make sense for most disassembly: any large object should be one you can work beside to disassemble.

### Steps to reproduce

1. Make a heavy item such as the oven in #53648
2. Have a strength less than about 20
3. Attempt to dismantle item

### Expected behavior

The ability to carry an item should not be a factor in its disassembly.

### Versions and configuration

 PR #53648 test branch. Windows tiles 64.

**Comment by dseguin** [comment]
It looks like this might be super easy to solve:
```diff
diff --git a/src/game_inventory.cpp b/src/game_inventory.cpp
index 461f4e24c7..164b4942ae 100644
--- a/src/game_inventory.cpp
+++ b/src/game_inventory.cpp
@@ -476,6 +476,10 @@ class pickup_inventory_preset : public inventory_selector_preset
         explicit pickup_inventory_preset( const Character &you ) : you( you ) {}
 
         std::string get_denial( const item_location &loc ) const override {
+            return get_denial( loc, false );
+        }
+
+        std::string get_denial( const item_location &loc, bool ignore_weight_vol ) const {
             if( !you.has_item( *loc ) ) {
                 if( loc->made_of_from_type( phase_id::LIQUID ) ) {
                     if( loc.has_parent() ) {
@@ -483,9 +487,10 @@ class pickup_inventory_preset : public inventory_selector_preset
                     } else {
                         return _( "Can't pick up spilt liquids." );
                     }
-                } else if( !you.can_pickVolume( *loc ) && you.has_wield_conflicts( *loc ) ) {
+                } else if( !ignore_weight_vol && !you.can_pickVolume( *loc ) && you.has_wield_conflicts( *loc ) ) {
                     return _( "Too big to pick up!" );
-                } else if( !you.can_pickWeight_partial( *loc, !get_option<bool>( "DANGEROUS_PICKUPS" ) ) ) {
+                } else if( !ignore_weight_vol &&
+                           !you.can_pickWeight_partial( *loc, !get_option<bool>( "DANGEROUS_PICKUPS" ) ) ) {
                     return _( "Too heavy to pick up!" );
                 }
             }
@@ -543,7 +548,7 @@ class disassemble_inventory_preset : public pickup_inventory_preset
             if( !ret.success() ) {
                 return ret.str();
             }
-            return pickup_inventory_preset::get_denial( loc );
+            return pickup_inventory_preset::get_denial( loc, true );
         }
 
     protected:
```

**Comment by wapcaplet** [comment]
Confirmed issue in experimental, with a large storage battery (400 kg) and a character with 8 STR. Using the `(` "Disassemble item" menu, the battery is indicated as "Too heavy to pick up", regardless of whether the "Dangerous Pickups" option is enabled, and regardless of whether the battery is sitting on an adjacent workbench.

The classic in-game workaround to this bug is to place the heavy item on the ground at your feet and `B`utcher it.

**Comment by I-am-Erk** [comment]
> Confirmed issue in experimental (0.F-4532-g [630da64](https://github.com/CleverRaven/Cataclysm-DDA/commit/630da649b6f69852f7520c4952f8e3c48ea71958)), with a large storage battery (400 kg) and a character with 8 STR. Using the `(` "Disassemble item" menu, the battery is indicated as "Too heavy to pick up", regardless of whether the "Dangerous Pickups" option is enabled, and regardless of whether the battery is sitting on an adjacent workbench.
> 
> The classic in-game workaround to this bug is to place the heavy item on the ground at your feet and `B`utcher it.

That is good to know for the short term. While it can be worked around with butcher I think we should fix it anyway, considering the number of heavy salvage items upcoming

**Comment by mqrause** [comment]
Looking at @dseguin 's suggestion, simply removing the call to `pickup_inventory_preset::get_denial` in the `disassemble_inventory_preset` should be enough if we simply don't want any denials. Which actually means there's no reason to inherit from `pickup_inventory_preset` at all. There shouldn't be any liquids showing up anyway and even if you could disassemble a liquid, you wouldn't pick that up but an in progress disassembly item instead, which should be fine again.
