### ISSUE TITLE
Crafting using filled containers as components

### ISSUE THREAD

**Issue by RDru** [CleverRaven/Cataclysm-DDA#53679]
### Describe the bug

Crafting something that uses a container as component, like aluminum powder, shows and allows to use all those containers no matter if they are empty or not. It does not inform of how many empty containers are available.

Also after answering "No" to crafting from non empty container all those containers are dropped from vehicle storage they were in.

### Steps to reproduce

1. Make 3 empty and 3 not empty aluminum cans.
2. Put them inside vehicle storage.
3. Craft 1 aluminum powder.
4. Answer "No" when asked about crafting from non empty container.

### Expected behavior

1. Crafting menu should not show non empty containers as components.
2. Crafting should not move or drop components wherever they are.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: aac4403 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by dseguin** [comment]
I'm sorry about the inconvenience. Both issues will be addressed by #53302.
