### ISSUE TITLE
Items not showing up in A I M or (V)iew

### ISSUE THREAD

**Issue by 321nick** [CleverRaven/Cataclysm-DDA#53676]
### Describe the bug

Filtering for an item using AIM or View wont work if its in an item (in my case, a survivor telescope in a plastic bag along with 8 other items

### Steps to reproduce

1.spawn a plastic bag
2. put a telescope in it, and some other stuff (i put 100 beans)
3.try Advanced Inventory Management or (V)iew, filter for Scope

### Expected behavior

i can still get these items from these containers with A I M and (V)iew

### Screenshots

theres a plastic bag above my avatar, it has a scope in it, AIM says there is none though: 

![image](https://user-images.githubusercontent.com/19196462/147083143-2d6f2a53-1549-4895-9432-f82c49c7a20f.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 9da956a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

### Additional context

sorry if this is an intended feature with modelling obfuscation of items in other containers, but.... as realistic as that may be, it just seems like it really slows down pace of doing things, adding complexity without any depth 99% of the time.  atleast, it would be entirely tolerable if we could do "Unload and drop all except liquids" for all items on a tile, allowing for easy access of items when their all on the floor.

**Comment by bombasticSlacks** [comment]
People are working on this or there is desire to fix it but my understanding is the AIM is awful to modify in C++ 

However your it would be tolerable if is already in game #53346

**Comment by morthein** [comment]
I had this happen once, realized I had a filter set from before (I wanted to mass separate splintered wood from chopped piles of wood quickly with AIM) and the filter doesn't reset when you close the window, thus showing my in new piles without splintered wood that there was nothing there, when in fact it was my filter doing it's job :(

**Comment by Je55eah** [comment]
I don't know if those things should be visible with "V", but when they are in an adjacent tile or on the ground below the character lets see that stuff.
