### ISSUE TITLE
"oven" tool quality

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#53684]
### Is your feature request related to a problem? Please describe.

Currently, baking bread and desserts only requires heat. On trying to add an oven item, I realized we don't presently track the ability to contain heat for baking. You can't really adequately bake a cake on an open hotplate or over a fire. If you're putting the object to be cooked directly onto the heat element (or on a pan directly on the heat element) you're going to get too much heat on the side touching the pan to do things like bake bread.

### Solution you would like.

Add an OVEN tool quality. I suggest at least 2 levels:

Level 1: an oven that can contain heat for makeshift baking. For example, a large pot on a hotplate could be used to make bread if you set up a rack inside it for the bread to sit on. A first implementation probably wouldn't need to actually use this quality level, but I'd say it's worth being ready for it as an option.

Level 2: a proper purpose built oven.

Level 1 could be used for simple breads and a few things like that, but most advanced baking is going to need level 2.

### Describe alternatives you have considered.

It might be worth also having a quality for indirect heating like wrapping stuff and putting it by a fire, but I'm not sure we need to track that as a separate quality.

### Additional context

Bear in mind that an oven can be made in the wilderness with rocks and mud, the level 2 quality doesn't need to be exclusive to an industrial age convection oven. That stuff can be added on a later pass though.

**Comment by Maleclypse** [comment]
Where would Dutch ovens fit into this level format?  I imagine it would be level two but I want an opinion before I add them.

**Comment by I-am-Erk** [comment]
Probably level 1. Can you bake a cake in a Dutch oven?

**Comment by Maleclypse** [comment]
> Probably level 1. Can you bake a cake in a Dutch oven?
> 
> Realistically I'm not sure they're even 1. Despite the name, they don't make heat application any less direct.

We always used them to bake cakes while camping in Boy Scouts because you could use them to make heat apply evenly across the contents from all sides.

**Comment by I-am-Erk** [comment]
Huh, I've never seen them do that. Perhaps we shall see have three oven levels then, with a third level being for highly technically and temperature regulated ovens, since there's no way you could do a fancy dessert in a dutch oven.

**Comment by Shodan14** [comment]
At some point, maybe there should also be differentiation between a lab-quality hotplate with adjustable temperature and a campfire.

**Comment by I-am-Erk** [comment]
Not unreasonable.

**Comment by Termineitor244** [comment]
@Maleclypse shouldn't this have been closed when #54309 was merged?
