### ISSUE TITLE
Ignore Distractions Option when Autowalking

### ISSUE THREAD

**Issue by SilverTemper** [CleverRaven/Cataclysm-DDA#53689]
### Is your feature request related to a problem? Please describe.

When autowalking, consistent noises (like alarms) will stop your character every step or two.

### Solution you would like.

Adding an option to ignore noises, such as the option when interacting with objects, would cut down on frustration and allow auto-walk to serve its purpose rather than requiring babysitting.

**Comment by morthein** [comment]
I generally have to wear an mp3 player or earplugs to avoid this in game, but I usually forget until the prompts start flooding in so I still have to stop, put them in, then start again, which is kind of babysitting. I'd like to add monsters to this as well, it prompts when you see something, but if I ignore, it doesn't ignore for long before it prompts for the same monster, even if they're not engaging me after I have walked a couple of feet and they have left my initial vision and reappeared (like through a window or to and shadow and back out so I can 'see' them again.)

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
