### ISSUE TITLE
One-sided conversation prevention for NPC's

### ISSUE THREAD

**Issue by nexusmrsep** [CleverRaven/Cataclysm-DDA#53687]
### Is your feature request related to a problem? Please describe.

Current way of how you interact with NPC's in conversations makes them feel shallow. Here's why: NPC is a static recipient of PC activities / inquiry.

Typical interaction boils down into:

- PC: Hello!
- NPC: Hello! What can I do for you?
- PC: Tell me about yourself and how you survived. 
- NPC: Sure, here goes...
 `<20 minutes later>`
 ... and then the shoggoth puked me out.
- PC: Yeah, right... Got anything to trade?
- NPC: Yeah `<trade>`
- PC: Any jobs?
- NPC: Yeah, find my cat!
- PC: Here is your cat.
- NPC: Great! `<reward>`
- PC: I have to go now.
- NPC: Bye.

How it should look like:

- PC: Hello!
- NPC: Hello! What can I do for you?
- PC: Tell me about yourself and how you survived. 
- NPC: Sure, here goes...
`<20 minutes later>`
 ... and then the shoggoth puked me out.
- PC: Yeah, right... 
- NPC: Wait! What about you? Who are you anyway?
- PC: Me? Now just a survivor, but by trade `<describes profession> <option to lie> <option to persuade yourself out of the conversation>`
- NPC: `<reaction to profession> <generic> <dislike option> <like option>`
- NPC: And how did you survive?
- PC: `<describes a personal story>`
- NPC: Awesome. <other reactions>
- PC: Got anything to trade?
- NPC: Yeah `<trade>`
- `(continuation)` Oi, you've got a nice `<item>`, how much for that? Perhaps I can muster `<some rare item>` for it next time you are here?
- PC: `<reaction options: accept/deny/else>`
- PC: Got any jobs for me?
- NPC: Yeah, find my cat!
- PC: Here is your cat.
- NPC: Great! Got any jobs for me? I'm a scavenger, I specialize with `<some items>`. Want me to get you something specific?
  `OPTIONAL EXAMPLE:` I'm a hunter. I can hunt you some prime venison. Interested?
- PC: I want to give you a special task. Do `<some kind of job that is feasible for an NPC, faction etc.>`
- NPC: Sure, It's done.
- PC: Great. `<reward>` I have to go now.
- NPC: Bye.

### Solution you would like.

There should be ways to reverse typical `PC asks NPC` trend and make it also `NPC asks PC`.
Possible branches:

1. NPC asks about PC's profession
2. NPC asks about PC's hobbies
3. NPC asks about PC's survival story / background
4. NPC is interested in buying one of PC's items for a good price / good barter item
5. NPC is interested in getting a job / quest from a PC

Ad. 1-2 - Professions/Hobbies
- NPC can ask it in chit-chat mode (small talk) and/or trigger reverse reaction as a reply to PC asking NPC for his
- Professions and Hobbies descriptions can be used as is or JSON's can be enhanced to contain relevant snippets
- JSON's can be enhanced to contain relevant snippets for NPC reaction(s): <neutral> <like> <dislike> <other>
- NPC could then would simply set to use whitelist and blacklist style of reactions: <like: biker> <dislike: gangster>

Ad.3 Backgrounds 
- they share some of the above but:
- IMHO professions should be separated from survival story / background to create a separate entity in character creation
- background story would need to be related to starting locations, sometimes to professions too, in other words: professions hobbies and locations should be able to enable and disable background stories in the pool (reason: consistency)
- background stories can be chosen at character creation from a pool or rolled randomly (per analogy to traits etc.)

Ad. 4-5 
Those are harder to implement and don't have any specific idea how it could be done at this moment.

But most important for all options: you don't bake the conversation and options into the NPC conversation JSON as a standard dialogue but as templates that relies on things defined elsewhere in separate JSONs.

### Describe alternatives you have considered.

Any other means of 'NPC has gained AI and is interested in inquiring PC about things' is relevant.

**Comment by PatrikLundell** [comment]
While NPC interest in the PC is realistic, it quickly becomes a drag when going over the same thing for the umpteenth time, so I'd prefer most of it to be abstracted away.
Greater reactivity to the PC and the PC skills/faction abilities/mutations/... would be good, though. I also like the suggestion that NPCs may be interested in performing tasks for the player (there's a little bit of that in the Tacoma commune).

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
