### ISSUE TITLE
Welding store

### ISSUE THREAD

**Issue by Alex-Folts** [CleverRaven/Cataclysm-DDA#53685]
### Is your feature request related to a problem? Please describe.

It would be nice if we had some dedicated place for welding equipment, something like gun store or gas station where you reliably find guns/ammo and fuel respectively.  So you look at the map of the city see welding store and know that you can find anything you need for welding in decent quantities, so we can aim specifically for welding things.

With addition of welding consumables it become more important to expand places where you can find them, garage is a good and realistic place, but it can't grow infinitely about how many stuff you can find there, adding dedicated shop would solve some problems with deficit of consumables. Such stores are real thing afterall.

### Solution you would like.

Unique store, it should reliably contain:

- welders
- welding goggles
- welding masks
- acetylene torches
- acetylene fuel
- cylinders with oxygen gas(additionally if we have: argon, helium, co2 cylinders)
- all types of welding consumables in great quantities
- other welding related things i forget about

The goal is that you enter store with empty pockets and leave with full welding gear.

### Describe alternatives you have considered.

Add more stuff to existing locations.

### Additional context

Got this idea while discusing https://github.com/CleverRaven/Cataclysm-DDA/pull/53683

Unfortunately adding new buildings to the game out of my skills, so i made this suggestion to motivate someone who think it is a good idea.

**Comment by ZhilkinSerg** [comment]
I don't think welding stores are a common thing in real life - it is too specific for an offline business site.

Still, welding consumables should possibly appear more often in garages, hardware and home improvement stores.

**Comment by Zireael07** [comment]
Hardware/home improvement stores are basically the proposed welding stores + some other stuff, at least in Europe.

**Comment by PatrikLundell** [comment]
My conclusion is that it should be a matter of updating existing facilities, so the consumables part of these stores would get their drop tables updated, and possibly get sections for these consumables. That may be within the reach of the abilities the OP may be able to gain with a reasonable amount of investigation.

**Comment by Alex-Folts** [comment]
I've probably explaine it wrongly, i mean something like [this](https://www.google.com/search?tbs=lf:1,lf_ui:3&tbm=lcl&sxsrf=AOaemvIrMsNtMA6v-LJcRBnoihIdLkBYJg:1640277706751&q=welding+gas+store&rflfq=1&num=10&ved=2ahUKEwiysqzQrvr0AhVExosKHSB5CTEQtgN6BAgVEAc#rlfi=hd:;si:16989260911774288545;mv:[[43.40321291622455,-69.49542323131188],[40.19373025690741,-76.41680995006188],null,[41.8185732444226,-72.95611659068686],8]). Here its all different but idea the same, bunch of stuff related to welding.

But ofc i might just add consumables to hardware store, it is also appropriate place. I just thought since there is specialized store we might add it.

**Comment by JonathanLochridge** [comment]
Potentially a welding heavy variant of the Hardware store would make sense.

There could also be a welding lab location other than garages?

I know a lot of community colleges have welding labs. (Not sure if there are colleges yet? Or just schools>)
