### ISSUE TITLE
DEBUG: could not rename file after death

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#53691]
### Describe the bug

When I die I sometimes get errors like the following:
```c++
 DEBUG    : could not rename file './save/Garriso/#c2FtZW5hbWU=.mm1' to './graveyard//#c2FtZW5hbWU=.mm1'

 FUNCTION : void game::move_save_to_graveyard()
 FILE     : src/game.cpp
 LINE     : 2500
 VERSION  : 0.F-4523-g00a57e1f7d

 DEBUG    : could not remove file './save/Garriso/#c2FtZW5hbWU=.mm1'

 FUNCTION : void game::move_save_to_graveyard()
 FILE     : src/game.cpp
 LINE     : 2506
 VERSION  : 0.F-4523-g00a57e1f7d
```

This is especially annoying because trace generation takes time.

### Steps to reproduce (updated)

1. Create a character, named "samename"
2. Travel a bit from your starting location
3. Quicksave
4. Verify that a dirrectory named `#c2FtZW5hbWU=.mm1` was created in your save file
1. Die
2. Repeat steps 1 though 5. Important: give the character exactly the same name as you did in step 1
2. Get the above error

### Expected behavior

No errors

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 0.F-4523-g00a57e1f7d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by morthein** [comment]
on latest version and I can confirm I also get this.  If I don't close the game out and reopen it, and try to make a new character on the same world (mine is set to reset on death) it crashes to desktop. Once reopened, it's fine.

**Comment by Ramza13** [comment]
Have you switched to control a follower before this happens?

**Comment by hexagonrecursion** [comment]
> Have you switched to control a follower before this happens?

No. I did not even know this is already implemented.

**Comment by hexagonrecursion** [comment]
Ok. I see, what happened. In the graveyard the names of files are based only on the character name and nothing else (e.g. time of death or random GUID). I often make characters with the same exact name:
* Characters I use for debugging are always named "tmp". This makes it easier to determine whether I am currently in a real playthrough or in a debugging world.
* My main character is always named Alice Smith for meta-universe reasons.

On Linux (and possibly other POSIX compliant systems) `rename(2)` allows you to replace an existing file, but does not allow you to replace an existing directory:
```c
rename("./save/Garriso/#c2FtZW5hbWU=.ano.json", "./graveyard/#c2FtZW5hbWU=.ano.json") = 0
rename("./save/Garriso/#c2FtZW5hbWU=.apu.json", "./graveyard/#c2FtZW5hbWU=.apu.json") = 0
rename("./save/Garriso/#c2FtZW5hbWU=.log", "./graveyard/#c2FtZW5hbWU=.log") = 0
rename("./save/Garriso/#c2FtZW5hbWU=.mm1", "./graveyard/#c2FtZW5hbWU=.mm1") = -1 ENOTEMPTY (Directory not empty)
```

I'll update the steps to reproduce to include the new findings

**Comment by hexagonrecursion** [comment]
This also happens if you backup a world and die multiple times for debug purposes.

**Comment by hexagonrecursion** [comment]
Assign this to me. I'll fix it
