### ISSUE TITLE
EOC_PORTAL_STORM_WARN_OR_CAUSE_RECURRING proc does not necessarily cause portal storm

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#53708]
### Describe the bug

When testing around portal storms, I noticed that the variable `EOC_PORTAL_STORM_WARN_OR_CAUSE_RECURRING`, does not necessarily trigger a portal storm. It may instead trigger warning messages and kick the can another 7 to 10 days down the road. In my test game, it took thirty in-game days for the first portal storm to finally occur.

### Steps to reproduce

1. Create a test game.
2. Save the game
3. In the save file (largest .sav file in your save folder), search for EOC_PORTAL_STORM_WARN_OR_CAUSE_RECURRING.
4. Note the turn it will occur
5. Use the debug menu (map -> change time) to set the current time to just before that happens.
6. Observe the warning and no storm.
7. Save again, and repeat steps 3 through 6. Note that it may take more than one try for a portal storm to occur.

### Expected behavior

I would expect the warning to indicate a portal storm is imminent, not for it to kick the can back a week. I started investigating this because my current character just survived a week and missed their first warning by being underground. The next warning is going to happen nine days out. I was under the impression portal storms would start occurring roughly a week after game start, While this CAN be the case, there is a lot of variance here. As I said, my first test game starting at a default time took until Spring 89 at around 6 PM before a portal storm actually happened.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 14aa061 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Fewer Soldier Extras [Fewer_Soldiers]
]

### Additional context

For all I know, this is intended behavior and I'm just misunderstanding how this whole thing is supposed to work. Let me know if this is how things are supposed to happen.

**Comment by Ramza13** [comment]
So the reason this happens is because all EOC_PORTAL_STORM_WARN_OR_CAUSE_RECURRING does is cause EOC_PORTAL_STORM_WARN to happen.  EOC_PORTAL_STORM_WARN displays a warning message and then queues up either itself(75%) or EOC_CAUSE_PORTAL_STORM(25%) in 1 to 6 hours.

**Comment by Inglonias** [comment]
That is not quite what is happening. Portal storms occur immediately after this event. I think someone needs to double check what's happening here.
