### ISSUE TITLE
Multiple Vehicle sprite/part selection issue

### ISSUE THREAD

**Issue by Kywi001** [CleverRaven/Cataclysm-DDA#53700]
### Describe the bug

door left vertical - unaligned on certain angle
off-road motorbike wheel - no rear option (assuming it's the same to all motorbike wheels)
wire basket - no option to change it to specific sprite. (i.e. bicycle wire basket, push cart sprites)
foldable engine crane, telescoping cantilever, boom crane - missing sprite (had a sprite if playing the version from google playstore)
multiple mounted guns - most doesn't have a sprite (just make them look the same atleast)

### Steps to reproduce

1. spawn new vehicle
2. build an identical one using the exact same parts and/or remove and add the parts from the spawned vehicle

### Expected behavior

should have the selections of said vehicle parts,
should have the sprites correctly aligned/shown

### Screenshots

![Screenshot_2021-12-23-12-04-20-584_com cleverraven cataclysmdda experimental](https://user-images.githubusercontent.com/95905384/147187373-9abb3ab1-99c4-4059-b71e-e9f7a549a4c2.jpg)
![Screenshot_2021-12-23-11-56-32-448_com cleverraven cataclysmdda experimental](https://user-images.githubusercontent.com/95905384/147187386-bc22cf80-6e4d-4216-9e17-7cee35a327ff.jpg)
![Screenshot_2021-12-23-11-56-46-318_com cleverraven cataclysmdda experimental](https://user-images.githubusercontent.com/95905384/147187392-54807913-8a4d-4180-86b7-410ff391bae4.jpg)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: Xiaomi; Model: Redmi 6; Release: 9; Incremental: V11.0.4.0.PCGMIXM; 
- Game Version: aa90e92 [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
