### ISSUE TITLE
Mad Militia are very accurate from afar

### ISSUE THREAD

**Issue by AcidAntOnAMinefield** [CleverRaven/Cataclysm-DDA#53707]
### Describe the bug

During my game I was spotted by a Mad Militia. 
Broad daylight, so the 50 daytime vision obviously helped. Once they were at around 30 or so tiles from me, they started unloading bullets. ALL of them hit me. 6 were enough to kill me. I "watched my last moments" and they were still shooting at me *while coming towards my dead body*. That I could count for at least 20 bullet cases on the floor. All his hits did over 28 damage as seen on "Screenshots" (picture) 
Also noticeable that it never even once missed a shot. 
Should also point out I was wearing a Modified Faraday Chainmail Suit with Kevlar plates, which gives me a 16 ballistic protection, 100% coverage. 

I save scummed to see what was going on. I killed it and noticed it had an AR handgun, empty, with a grand total of 24 .223 bullet cases on the floor. 

Keeping in mind that this gun only does 28 damage, it should do much less damage after applying the Armour benefits right? 
I figured "well, maybe I need to update, something may have changed in the past 2 days", so I fully updated it, created a test world and recorded it. (See: "Screenshots", video)

- This time I spawned a creature using debug mode and tracked it. The amount of bullets it has was reduced, but this time it had an M27, which justifiedly does more damage. It still doesn't explain how or why they have 10+ .223 ammo **and** what essentially is 100% accuracy from a long distance, and seem to be very keen on hitting the torso. 

### Steps to reproduce

1. Create a test world;
2. Spawn Mad Militia
3. Watch as it takes great joy in hitting you every time it pulls the trigger, turning your chest into a makeshift brass catcher.

### Expected behavior

Considering they are supposed to be "mad", they shouldn't be in full control of their "abilities", the miss chances should be higher the further away they are. This also highlights that armour protection is, effectively pointless unless I am misunderstanding the calculations there, which, if so, please enlighten me. 

### Screenshots

https://cdn.discordapp.com/attachments/367645652328644618/923593869109645363/unknown.png

https://www.youtube.com/watch?v=gJoG7RAl1-Q

### Versions and configuration

- OS: Windows 7
- Game Version: 14aa061 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]

**Comment by Terrorforge** [comment]
Monsters don't actually use the weapons they drop. Every Mad Militia deals the same amount of damage. Also, I'm not sure exactly how the damage calculations work, but it's definitely not as simple as the weapons dealing their listed damage. It's often as much as 50% more than that. For these reasons, 16 ballistic armor is really not very much you're getting shot with 5.56. You'll maybe survive one more shot, depending on your hp and how the damage comes out. You need like 40 ballistic to feel remotely safe, and even then it sometimes penetrates.

So there's nothing wrong with the armor mechanics, but this still sounds like a ridiculously (I would say frustratingly) dangerous enemy. Pretty much everything else with a gun spawns indoors, where you both expect it and have the opportunity to duck behind doors etc. I haven't encountered any myself, but if Mad Militia spawn in the overworld with a 50 tile sight radius, 75 aggression and perfect aim with 5.56, that just sounds like the game randomly deciding to kill you.

**Comment by AcidAntOnAMinefield** [comment]
As far as I could tell this one spawned outside. 
https://cdn.discordapp.com/attachments/367645652328644618/923572770657423380/unknown.png

It happened there, to the west of Surrey, where the Lab south of the Prision was. The Mad Militia was apparently somewhere in the vicinity as it approached me from the north side of the Lab.  (The door was to the west, my vehicle "airlocking" it). 

Yeah, I would assume 16 ballistic isn't really "great", the only feedback we get from them is that they shoot their "machine gun" - at the same time, the bullets they drop are .223, and their guns are apparently rifles (and again this would be with the assumption that they drop what they allegedly would use, kinda like Feral Humans do with Rocks and Pipes/Axes/Crowbars). Which I may add, kinda reminds me of how the early Feral Humans were with their "magic rocks" always hitting the torso regardless of how much armour you would have, way back when they were first introduced. 

I would also say that, for comparison sakes, the Feral Security Guards aren't even remotely as accurate, as I've seen them just absolutely miss a target 2 tiles away from them, and they use handguns themselves. 
So I am not sure what to suggest in order to make these a bit more "fair", other than restricting their spawns to specific buildings and changing their accuracy checks.

**Comment by Alex-Folts** [comment]
There was concerns about giving guns to monsters, but stuff were pushed anyway.

I would say if they have guns let it be shotguns, so they have advantage at close distance, at least in this case player would have options: run away, or attack it from distance. So you at least had a chance to draw your weapon.

Also obviously fix accuracy issues.

**Comment by Terrorforge** [comment]
> Yeah, I would assume 16 ballistic isn't really "great", the only feedback we get from them is that they shoot their "machine gun" - at the same time, the bullets they drop are .223, and their guns are apparently rifles (and again this would be with the assumption that they drop what they allegedly would use, kinda like Feral Humans do with Rocks and Pipes/Axes/Crowbars). Which I may add, kinda reminds me of how the early Feral Humans were with their "magic rocks" always hitting the torso regardless of how much armour you would have, way back when they were first introduced.

Based on their stat block, their gun is an AR-15. Which is not a machine gun, but is set up to use "burst" and "auto" in their stat block, and I have no idea what sort of shenanigans that may or may not result in. Based on the video, it looks like they only fire single-shot. I think they also only have 10 bullets, in which case the single-shot might actually make them more dangerous? If they have the same kind of added spread from burst firing as players, they could well exhaust their ammo before killing you. Dunno if they do, though.

Based on the PR in question, #52526, they are in act supposed to be this accurate. Supposedly their spawns were limited to LMOE shelters and cabins specifically because of problems like this, but I haven't tried to figure out if that is actually the case. And anyway, even if they do, LMOE shelters and cabins spawn on the overmap and ferals can open doors, so.

**Comment by Inglonias** [comment]
> There was concerns about giving guns to monsters, but stuff were pushed anyway.

That's what experimental is for. To test this stuff so we can decide what should stay and what should go.

> I would say if they have guns let it be shotguns, so they have advantage at close distance, at least in this case player would have options: run away, or attack it from distance. So you at least had a chance to draw your weapon.

This feels like a bad solution. Shotguns can kill in one hit in some conditions and if you stumble upon something like that in the dark, you could die with no counterplay.

> Also obviously fix accuracy issues.

This should be sufficient to resolve the problem.

**Comment by Alex-Folts** [comment]
> This feels like a bad solution. Shotguns can kill in one hit in some conditions and if you stumble upon something like that in the dark, you could die with no counterplay.

Well the idea behind this was: this creatures appears in mid game, at that point player should have at least some armor(and some ranged weapon), shotgun(loaded with pellets) have low efficiency against armored targets, also it have low efficiency at distance, so you should be fine fight this creatures from distance, yet shotgun shot have spread so it will hit you even if this things aim barely somewhere in your side, which is understandable since they should not aim carefully - they are mad. I'd at least tested this approach, maybe i'm underestimating shotguns(there was recent changes to how they work), but that's my vision of the situation.

In close combat shotgun would be bad, true, that's an issue. But think about rifles: its ammo have decent armor penetration, 1 lucky shot could kill character, we can fix accuracy so they will miss most of the time, but once in a while they will randomly hit, and if it hit someone in face - high chance to die, even from distance, it's a gambling.

**Comment by Maleclypse** [comment]
One solution that was done with another set of armed ferals was they were given special damaged guns that were more prone to missing.   I'm not sure if that solution got merged or another solution presented itself.

**Comment by Maleclypse** [comment]
During a couple tests it never missed.  Hit extremities an anecdotally appropriate number of times.

**Comment by I-am-Erk** [comment]
I remain of the opinion that hostile monsters with guns should *never* spawn at random, and should only be something you have to go to find, and have a lot of warning about.

**inaccuracy is not a fix**. You cannot plan for or fight inaccuracy, tactics don't help you. It just means that sometimes the monster kills you, and you can't do anything about it. We do not have a system that models taking cover from bullets and darting across the battlefield, so a feral that can pop a lucky cap in your head before you realize they popped up in the reality bubble is just *not fun*.

**Comment by LyleSY** [comment]
I've taken a couple of different runs at this in #59067 . I think I've got it right now
