### ISSUE TITLE
Autofarm Deathloop

### ISSUE THREAD

**Issue by Aeder1** [CleverRaven/Cataclysm-DDA#53710]
### Describe the bug

Stuck in a loop of running to the seed storage area and to the location I am trying to auto plant crops. Game becomes completely unresponsive through any commands and also refuses to alt tab and must be hard closed.

I believe it is due to some plots being planted already, or that I told an NPC to farm a little while before.

### Steps to reproduce

-Set a zone to plant crops, possibly with some planted in the zone. Unsure if the zone I am stuck to-from has same or different crops.
-Set up normal basecamp storage zones, seed storage zone and unsorted zone covering all previous zones.
-ctrl+y > autofarm
-Cry softly

### Expected behavior

seed go in plot

### Versions and configuration

0.F-3
No mods (except for no fungus)

### Additional context

[Homestead Horde - Loop.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7770850/Homestead.Horde.-.Loop.zip)

**Comment by Aeder1** [comment]
In the end I waited it out several days and collapsed asleep which cured it.
would still be nice to not have to wait it for approx 30 mins of irl time.

**Comment by hexagonrecursion** [comment]
In the save you have attached the character is already in the loop. It looks like this bug does not affect experimental.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: f8734ab [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi]
]

**Comment by TealcOneill** [comment]
@GuardianDll Cannot replicate.

**Comment by GuardianDll** [comment]
crops were changed recently, probably one of the changes fixed it
