### ISSUE TITLE
NPC with insomnia trait

### ISSUE THREAD

**Issue by flin4** [CleverRaven/Cataclysm-DDA#53715]
### Describe the bug

I've got one around me and she is constantly complaining about how she is deadly tired. Once i allow her to sleep she moves towards the bed but doesn't reach it immediately and returns to my PC. Then after some turns she  makes another try and again and again. It can last for couple or dozen times but finaly she's in the bed. But she starts to pretend that she's sleeping. I mean there's no sleep indicator but i still need to wake up her to activate. In fact i can see her sleeping sometimes in the morning but then she gets up and begins her same old story about how lack of sleep is worse than lack of food. And after all she doesn't consume any drugs and even chamomile tea wich can help with insomnia.

### Steps to reproduce

Just find her

### Expected behavior

I think it would easier to remove insomnia from NPC's traits or make its behavior not so weird. 

### Versions and configuration

android

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
