### ISSUE TITLE
Visibility and ability to pass based on volume in tile

### ISSUE THREAD

**Issue by vetall812** [CleverRaven/Cataclysm-DDA#53726]
### Is your feature request related to a problem? Please describe.

Right now, tiles have 'cover' that affects move cost, but that value does not include the volume of items on the tile. It seems the ability to step into a tile is defined separately as we cannot step into a tile with a tree on it, even if the tree covers just 80% of the tile.

Also, running through a tile with 1000L of items in it without any additional movement cost is a bit weird.

![image](https://user-images.githubusercontent.com/6676374/147334458-d3b8bf8d-6c25-4cef-a880-cbcaa39cd4cb.png)

### Solution you would like.

Terrain and furniture already have a "move modifier" and some flags that allow placing items on a tile.
Let's improve this: Keep flags for now but add "volume" for every terrain, item, furniture or vehicle part. Then add some additional rules to the movement, visibility or process of adding items to tile.

By default, a tile will have capacity for 1000L (with some exclusions).
Movement rule: Every 100L of volume adds +1 to move_cost, at 1000L (or move_cost=11) movement completely stops.
Vision rule: 300L blocks sight when prone, 600L blocks sight when crouching, 900L+ blocks sight when standing.
Items stacking: if items are not in a container or furniture then they form a pile. Additional items can be added to a pile if there is free volume remaining. If total volume exceeds 1000L then each 1L that is over adds a chance (1%) that the item will fall to an adjacent tile. This means a tile full of 100L barrels will not accept another barrel, but you can still try to stack a USB drive here.

PS. This function would be great for vehicle parts. Cargo carriers would be for cargo and the aisles would be desirable and usable.

### Describe alternatives you have considered.

Leave it as is )

**Comment by LeahLuong** [comment]
I like this suggestion but think fully cluttered tiles shouldn't completely halt movement, merely hinder it. Think of a situation where slaying so much actually fills all surrounding tiles, effectively soft-locking a game by preventing movement. Also, whomever implements this may need to be wary of its interactions w/ vehicles. Are storage spaces considered more organized & therefore more easily navigated?? Is a cargo space filled w/ items easier to get over than a full 50L box??

This suggestion occupies a sort of gray area betw/ what is furniture, terrain, or packable item; its time may be far in the future after the 1st 2 items have been more hashed out, as there are current efforts underway. 1 recent change made corpses containers for their worn/born items. Are corpses considered expandable containers for their contents & will that need to be updated to accomodate this suggestion??

Just thought it might be helpful to put some of my ruminations here.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
