### ISSUE TITLE
Marked Crafting Spots cost 200 movement points

### ISSUE THREAD

**Issue by CanSpellMutch** [CleverRaven/Cataclysm-DDA#53725]
### Describe the bug

Marked crafting spots cost 200 points to traverse and take >1 second to construct, resulting in a free way to slow down oncoming enemies.

### Steps to reproduce

Place a crafting spot and inspect it.

### Expected behavior

Should be 100 points to traverse like normal ground.

### Screenshots

![image](https://user-images.githubusercontent.com/96608968/147322123-17e42484-b115-4160-b478-cd654cca5e21.png)
![image](https://user-images.githubusercontent.com/96608968/147322170-d14a532d-0e7b-4a78-bacf-0844026f90f9.png)

### Versions and configuration

Windows 10
8b32af6

### Additional context

(my first bug report)

**Comment by Stone94** [comment]
Pretty sure decreasing the move cost would have the opposite effect, it would allow you to decrease the move cost of terrain to make it faster for you to travel, sounds like it needs to inherit the move cost of whatever its placed on.
