### ISSUE TITLE
Configurable text window maximum width and left-right-center float, for multihead setups.

### ISSUE THREAD

**Issue by Lee-Adamson** [CleverRaven/Cataclysm-DDA#53720]
### Is your feature request related to a problem? Please describe.

I run CDDA maximized across three portrait orientation monitors, for a total resolution of 4320x2560px.  Most windows are fully contained within one monitor, but the advanced inventory window in particular is a real pain in this configuration, as it spans all three and becomes rather clumsy.

I can also see as how it would also pretty much impossible to play the game maximized across a dual-head setup, as the centered windows would always be cut in half.

It would be pretty keen if there were a configuration option to set the maximum width and the left-center-right float of the different types of text window, so that the game could be made more usable on multihead setups.

### Solution you would like.

It would be pretty keen if there were a configuration option to set the maximum width and the left-center-right float, of the different types of text window, so that the game could be made more usable on multihead setups.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
