### ISSUE TITLE
Cannot sleep underwater even with appropriate mutations

### ISSUE THREAD

**Issue by gisaku33** [CleverRaven/Cataclysm-DDA#53732]
### Describe the bug

Neither Aquatic Sleeper or Aqueous Repose allow you to sleep underwater, instead just giving a message that "You cannot sleep while swimming."

### Steps to reproduce

1. Make a character and give them Gills or Cephalopod Gills, and either/both Aqueous Repose and Aquatic Sleeper.
2. Swim into deep water and attempt to sleep.
3. Cry, but nobody can tell because you're underwater.

### Expected behavior

Sleeping underwater should be both possible and receive the benefits also listed by Aqueous Repose/Aquatic Sleeper.

### Screenshots

![image](https://user-images.githubusercontent.com/23239811/147362077-7d2e4b44-30a8-41db-a86b-447c12dea4cd.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: c0953e1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Terrorforge** [comment]
Did you try moving down so you're really _under_ the water?

**Comment by gisaku33** [comment]
Yes, both swimming on top of water and after "diving" it gave the same message and didn't allow sleeping.
