### ISSUE TITLE
Frames install rod requirements

### ISSUE THREAD

**Issue by flin4** [CleverRaven/Cataclysm-DDA#53749]
### Describe the bug

Frame requires 30 welding rods to install, extra light and heavy duty 60. Where's the truth?

### Steps to reproduce

Look through vehicle istall menu

### Expected behavior

Depends on frame weight or same for all

### Versions and configuration

android, tiles, experimental

**Comment by Alex-Folts** [comment]
Extra light frames should require rods for aluminium, and rebalance install/repair cost. It is somewhere in my todo list. 

Rods tightly tied with welder charges, and extra light frame have abnormal requirements for welder charges.
