### ISSUE TITLE
Turret Changes (CROWS, Exodii and Hub01 laser turrets)

### ISSUE THREAD

**Issue by Kywi001** [CleverRaven/Cataclysm-DDA#53753]
### Is your feature request related to a problem? Please describe.

-CROWS turret map generated spawn having a fresh 4 belts of 500 ammo (too much ammo and inconsistency due to them, supposedly deployed for a long time now)
-CROWS turret you activate uses 1000 ammo instead of 2 belts of 500 ammo (inconsistency with the map generated ones)
-Hub01 Laser turret not dropping laser weapons
-Exodii turrets not dropping ammo despite dropping battle rifles

### Solution you would like.

CROWS 
-needed some tweaking to make map generated crows to have a random amount of belt ranging from 1 to 4 (because they have been there deployed for a long time now)
-deployable inactive crows should require belted ammo instead of ~1000 ammo
-should give a prompt of how many belts (upto 4) of ammo you want to give it
-should be able to unload/reload without the need to redeploying said turrets

Hub01 Laser Turrets
-should have either:
1. very very low chance to drop laser type gun/s on death
2. broken laser turrets to have laser type gun when disassembled and be irrepairable and will always drop a \. or x broken laser turret on death making it harder to get laser type guns from them (for balancing reasons)

Exodii Turrets
-make them drop a random amount of exodii specific ammo ~1000 on death (its not like theyre using air or metal scraps to fire a high caliber rifle that could kill from a far)

additional for the Exodii Quadruped, they should also drop random amount of ammo upon death.

**Comment by Maleclypse** [comment]
"-needed some tweaking to make map generated crows to have a random amount of belt ranging from 1 to 4 (because they have been there deployed for a long time now)"  I know this part is specifically what Kevin has said is the wrong fix for this problem.

**Comment by Zireael07** [comment]
@Maleclypse What is the right fix then? The crows ammo issue has been reported at least once already...

**Comment by Tommy-os** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/50413#issuecomment-890766041

**Comment by LeahLuong** [comment]
Altering turret drops to be more random doesn't seem like an "arbitrary" change. If they're placed where they would've spent some of their supply, why wouldn't they have less when you get to them?? Even when not placed thusly, is it possible armed forces may have commandeered a belt or 3  for use by their soldiers & manned turrets??

I also find getting hundreds of NATO rounds to be the primary motivation for going where CROWS II are found, regardless of what they happen to be guarding. Kind of silly to get city-clearing levels of ammo from blind throwing a 'nade around a corner or crouch-ramming w/ a throwaway vehicle.

**Comment by Kywi001** [comment]
I'm new to this game, specially to this github, but in my reasoning, there's literally 0 soldier npc or a feral soldier near military outposts/bunkers except the zombie soldiers inside military helipads and bases,
so this means that the soldiers either
1. tried to defend the said location until they succumbed to the outbreak or someone from their ranks are infected
2. dispatched somewhere for a mission due to the outbreak (in this case, deploying automated mechanical defenses)
3. decided to abandon post (which in this case, they wouldve brought everything that they could bring)

so in my (low iq) opinion, turrets should have difference in ammo count or have each military locations have different status (i.e. intact with everything inside untouched, overrun has no turrets or has broken turrets and has zombie soldiers inside out, and abandonned with almost nothing inside, I mean, theyre the military, they should be able to afford to have a few military vehicles near their posts)

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
