### ISSUE TITLE
Gun stores are a little too all-or-nothing

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#53755]
### Is your feature request related to a problem? Please describe.

I mostly love the changes to gun stores wrought by #50727, except for one tiny thing. All the ammo is in a single gun safe. This is a problem because it means that whether or not you get all the ammo you will need for the foreseeable future boils down to a single random chance. I find myself savescumming this all the time, and this is after I train up my lock picking proficiency to lower the chances of jamming the lock.

### Solution you would like.

There are a few ways to resolve this. The simplest solution is to split the ammo between two or more gun safes so a single jammed lock doesn't mean a gun store is useless. Another possibility is to change the container for the ammo from a gun safe to something that can't jam up and permanently lock away it's contents. Perhaps some stores have electronic gun safes instead?

### Describe alternatives you have considered.

The rationale given for locking up the ammo in the original pr makes sense. It isn't that major a problem. I just find it hugely disappointing to go to all the trouble of breaking into a gun store only to screw up with no way to correct it.

**Comment by Terrorforge** [comment]
There are ways to open safes other than picking them. Smashing them with a sledgehammer is probably the most practical. You _can_ use an acetylene torch, but I don't recommend it for ammo safes because it tends to set the ammo on fire.

You used to be able to jackhammer them as well, but last I checked that didn't actually work any more.

**Comment by Inglonias** [comment]
...I did not know that! That helps a great deal.

**Comment by Inglonias** [comment]
A homewrecker wielded by a str 8 or higher character (maybe lower, haven't tried) can eventually smash a gun safe. Homewreckers are easy enough that you can scrounge one together on day 1. Closing this issue.
