### ISSUE TITLE
favorited items could be used for crafting

### ISSUE THREAD

**Issue by mkrutov** [CleverRaven/Cataclysm-DDA#53768]
### Describe the bug

Favorited items could be used for crafting.

### Steps to reproduce

1. take 2 smartphones, mark 1 as favorite.
2. craft security camera using smartphone recipe

### Expected behavior

At very least craft should query user "Do you want to use favorite item?" or something in lines.
But preferred option would be to not use favorited items for craft, at all.

### Versions and configuration

    OS: Linux
        OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a;
    Game Version: b5228cf [64-bit]
    Graphics Version: Tiles
    Game Language: System language []
    Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Disable NPC Needs [no_npc_food],
    No Bionic Slots [no_cbm_slots]
    ]

**Comment by LeahLuong** [comment]
Placing items in your inv prior to crafting will offer you the option of using "on person" components.

**Comment by morthein** [comment]
Can't we just un-fav it to use it as a component again?  I really think purposely favorited items should remain sacred and safe.

**Comment by mkrutov** [comment]
@morthein that's the point of a bug. 

I've lost about 40 minutes trying to find my favorited smartphone only to realise it was just eaten by a craft without even asking me. :)
