### ISSUE TITLE
Duplicate items on game start with preset character.

### ISSUE THREAD

**Issue by ahmedcharles** [CleverRaven/Cataclysm-DDA#53777]
### Describe the bug

Duplicate items when starting a new game.

### Steps to reproduce

1. Make a world.
2. Make a character.
3. Make a template from that character.
4. Delete the character.
5. Make a new character from the template.
6. Look at inventory and observe duplicated clothing.

### Expected behavior

Only one of each item should be given to the character.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: b5228cf [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Stats Through Skills [StatsThroughSkills],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth]
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7776581/debug.log)
[debug.prev.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7776582/debug.prev.log)
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7776583/save.zip)

**Comment by TealcOneill** [comment]
Was not able to replicate with multiple templates and worlds. @GuardianDll 
OS: Windows
OS Version: 10.0.19045.4291 (22H2)
Game Version: cdda-experimental-2024-05-03-0220 abe3f76 [64-bit]
Graphics Version: Tiles
Game Language: System language []
Mods loaded: [
  Dark Days Ahead [dda],
  Disable NPC Needs [no_npc_food],
  Portal Storms Ignore NPCs [personal_portal_storms],
  Slowdown Fungal Growth [no_fungal_growth]
]
