### ISSUE TITLE
Choice of volume levels while speaking

### ISSUE THREAD

**Issue by lapis413** [CleverRaven/Cataclysm-DDA#53774]
### Is your feature request related to a problem? Please describe.

At the moment, we have the option to yell loudly in order to create noise, which can be used to manipulate zombies and certain animals. However, we only have a single volume level for this (barring having additional strength, which i think still increases the volume of your shouts?) which makes it a fairly limited tool.

### Solution you would like.

In the same menu as yelling, there could be a handful of other options to speak at different volume levels, in order to, for example, attract a handful of zombies to you rather than an entire herd. There probably shouldn't be too many of these, probably only two additional ones.

### Describe alternatives you have considered.

Some traits or mutations, such as self aware, could allow you to directly input the volume you want if you're confident in knowing how much sound you want to make. Alternately, the new options don't need to be yelling and could instead be something like stomping hard on the ground, or making some kind of noise with your equipment.

**Comment by morthein** [comment]
This can be achieved by yelling with your mouth encumbered also, automatically. It notes that your sound was muffled. I know it's not an exact volume control, but once you play with it a bit, you can get a sense of how muffled, 'muffled' is.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
