### ISSUE TITLE
New electricity damage is excessive

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#53772]
### Describe the bug

#53135 made some interesting changes to electricity, and therefore Shockers and their ilk, but the result is a bit too much. One shock often deals 30-40 damage and a load of Pain, and seems to follow you as you try to run away. Worse, if there's a husk or a trigger-happy shocker inside a room you can't see into, it'll charge up the walls, and when you get close, you'll take one of those massive bursts and be instantly crippled.

This is particularly egregious in the TCL after one or two months, because the high number of technicians that spawn means that after a few half-lives, the place is absolutely crawling with shockers.

### Steps to reproduce

1. Approach a room containing a shocker
2. Get zapped to hell and back

### Expected behavior

Would prefer if the game didn't punish you by taking off half your health and putting you in crippling pain just for walking up to a door.

### Screenshots

![image](https://user-images.githubusercontent.com/5107449/147395993-4084ff3a-50a8-4231-a803-a3ca20acc610.png)
Before getting shocked.

![image](https://user-images.githubusercontent.com/5107449/147395983-76410e0b-b1a3-4dd6-91d4-fb971f1a25b8.png)
After having had the audacity to walk up to a wall.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 579f907 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Extra Mutated Scenarios [extra_mut_scens]
]

### Additional context

They seem a lot less dangerous in open spaces, where their blasts mostly just dissipate, but it's difficult to engineer that kind o scenario, especially if you don't already know there's a shocker behind that door.

**Comment by Maleclypse** [comment]
@GoLoT I haven't tested it myself but it sounds like this person got shocked through a closed door?   I may be misunderstanding.

**Comment by GoLoT** [comment]
Yeah, sorry. Getting shocked through doors is intended but there was a bug that allowed fields to stack intensity over the intended cap (3). It's fixed in #53736 and #53604 is almost ready which will easily negate this damage while wearing decent boots (turnout/rubber boots and/or rubber padded footgear).

The expected damage after #53736 will be 1-3 to the feet (half to other bodyparts) with a 10-40% chance of being zapped. #53604 will make it very easy to negate this damage making you almost immune to low intensity fields. Keep in mind Husks will be VERY deadly at close range still, and direct hits from shocker balls will also hurt a lot.

**Comment by Terrorforge** [comment]
I just want to add that I've gotten deeper into the evolution, and discovered that zaptors are the fucking devil. The deal the same tremendous damage as shockers, but they're fast as lightning and impossible to hit, especially when you've already taken 150 pain before you've even had a chance to fire.

They might actually be the most dangerous enemy in the game? Haven't tested it, but I would unironically take my chances with a shoggoth over one of these bastards right now.
