### ISSUE TITLE
Holographic sight is too big

### ISSUE THREAD

**Issue by SirPendrak** [CleverRaven/Cataclysm-DDA#53788]
### Describe the bug

Commit #53180 made many changes to aiming, most of them being awesome. 

But it also changed specific model holographic sight was based on (model 512, before it was XPS2) and used official dimensions of this item wchich are far from real. 

Here we have XPS2
![XPS2](https://user-images.githubusercontent.com/43266802/147412748-69ee4736-c961-4c6a-a585-7b9046eeb47f.jpg)
Official info on it states it is 3.8 inches x 2.1 inches x 2.5 inches = 326ml but in reality if we take more detailed and simplified model we get 210ml, a volume we had before change. 

Simplified model for getting XPS2 volume
![XPS2 Volume 210ml](https://user-images.githubusercontent.com/43266802/147412789-f2578f0f-f82d-4a77-b96c-bdeb071e159c.jpg)

Here we have simplified model of Eotech 512 made to calculate  volume: 
![512 Volume 290ml](https://user-images.githubusercontent.com/43266802/147412882-57cddedb-b174-4c22-bc16-7fd391f110b7.jpg)
Official info states 5.6 inches x 2.1 inches x 2.5 inches = 480, but this model gives us 290ml

### Steps to reproduce

Get holographic sight
Notice that it is as big as your average pistol or dedicated sniper scope

### Expected behavior

The holo sight should be either 210ml, or 290ml, and not 480ml

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 34f079e [64-bit]
- Graphics Version: Tiles
- Game Language: Język systemowy []
- Mods loaded: [
    Dark Days Ahead [dda],
    Wyłącz potrzeby NPC [no_npc_food],
    Profesje bioniczne [package_bionic_professions],
    Bez stacji kolejowych [No_Rail_Stations],
    Sloty bioniczne [cbm_slots]
]

**Comment by ProjectileWaterfowl** [comment]
If volume is reverted, weight should also be. It seems the old values were based on the XPS2, since the weight was the same as well. If it's based on the 512, knock off 10 grams.
