### ISSUE TITLE
Zombies cant get clothes

### ISSUE THREAD

**Issue by kydsh** [CleverRaven/Cataclysm-DDA#53785]
### Describe the bug

when I move somewhere, I always get similar errors that are in the log

### Steps to reproduce

1. Move in some direction
2. Get error

### Expected behavior

I expect poor zombies to get their clothes

### Screenshots

![errrrr](https://user-images.githubusercontent.com/81353669/147411681-d91c2606-9d35-4d5b-b274-5557e59d9012.png)

### Versions and configuration

win 10

34f079e

russian

mods: [ "dda", "blazeindustries", "aftershock", "crt_expansion", "no_hope", "StatsThroughSkills", "speedydex", "stats_through_kills", "stamina_regen_buff", "crazy_cataclysm", "Graphical_Overmap", "WHALEYHAIR1" 
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7777127/debug.log)
[FrostPunk.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7777129/FrostPunk.zip)
]

**Comment by GoLoT** [comment]
The `mdeath::normal()` and `mdeath::splatter()` calls in https://github.com/CleverRaven/Cataclysm-DDA/blob/f8734ab57e2c11def95f3e905137755381106c47/src/monster.cpp#L2527-L2539
are expected to return a nullptr if the corpse can't be created but `make_mon_corpse()` calls `get_map().add_item_or_charges()` which returns a reference to the null item, not `nullptr`, when the item can't be added to the chosen position.

This null item is still a valid item and the `if (corpse)` calls only check that the pointer is null so the items are being added to a null item without pockets, causing the error. The easier fix is to return nullptr when calling `make_mon_corpse()` if the item is null (`corpse.is_null()`) in the `mdeath::splatter/normal` calls, or checking that the corpse is not a null item before trying to add items to the corpse. The latter involves changing all the `if(corpse)`checks in `drop_items_on_death()` and `monster::die()`.

I think this is a good first issue if anyone wants to fix it before I get to it.

An easy repro is to find/spawn a crater map special (the bugged ones that have ledges that lead to filled terrain) and spawning a zombie on top. The zombie will fall, die inside the wall and try to spawn a corpse. The wall will prevent placement of the corpse in that or any tiles around, causing the bug.
