### ISSUE TITLE
Proficiencies for martial art styles, and for different kinds of weapons beyond just their damage type (knives, short swords, long swords, katanas, hammers, pikes etc.)

### ISSUE THREAD

**Issue by cataclysmsurvivalist** [CleverRaven/Cataclysm-DDA#53789]
### Is your feature request related to a problem? Please describe.

Since archery is already covered in Proficiencies, I can't help but feel like it's a bit of an elephant in the living room that it's the _only_ weapon type that can be further mastered through practice.

### Solution you would like.

As we already have Bashing, Cutting, and Piercing weapon types, the next step would be giving Proficiencies that improve different martial arts/weapon styles. For example, Karate as it stands only depend on a high Unarmed skill. With a Proficiency aligned to it, it could just give the standard buff when first learned, but using it in real combat would allow you to master the knifehand and roundhouse kick.

Naturally, styles that revolve around weapons, like Niten Ichi Ryu and Barbaran Montante would require only weapon styles to be mastered instead of having their own martial art Proficiency, **but** their special skills and buffs would only activate when they're being used, like any other style. After all, in this instance you already have the "Proficiency", it's called just having the martial art style unlocked through books in the first place.

I imagine a lot of rebalancing would be necessary if implemented, but I feel martial arts/weapon styles could have their own identity that would make the game more realistic & satisfying, without making it bullshit hard like it is currently with the monster evolution rate that has yet to be nerfed.

**Comment by Terrorforge** [comment]
Afaik weapon proficiencies are planned, but idk what people have been planning to do with them re: martial arts.

We've had some discussions about how to incorporate weapon categories into MA, and it occurs to me that proficiencies might be the answer - if we so them backwards compared to crafting proficiencies, so they go from specific to general. E.g. if you use an arming sword, you'll get the arming sword proficiency, and then the medium sword proficiency, and then the general "sword" proficiency, and which weapons you can use with e.g. medieval swordsmanship is determined by those proficiencies.

Also fwiw you can nerf the evolution rate yourself, it's in the settings when you create a new world

**Comment by cataclysmsurvivalist** [comment]
>We've had some discussions about how to incorporate weapon categories into MA, and it occurs to me that proficiencies might be the answer - if we so them backwards compared to crafting proficiencies, so they go from specific to general.

It's what I had in mind, but I imagine Proficiencies would at some point need their own page or something, as it would get pretty huge. I don't mind scrolling down, but they're becoming a very important part of the game, so being able to see all the proficiencies you have/are mastering would be nice.

And yes, I know evolution rates are up to the player, but the default is too ridiculous as it is, and most people play it in the default. I think the reason it was raised was because the players were advancing too much and making the game a cakewalk, but now? Not only books have been nerfed (rightfully so, the theoretical/practical divide is a very good system) but we also have proficiencies that slow down how quickly you can craft high-tier equipment.

The game development has done a great job to slow down character progression in a way that doesn't feel artificial or forced while also making it more rewarding than it was before, but monsters are still more ridiculous than ever. Balance goes both ways, and I don't think it's right to just ignore how inflated monster evolution values are just because the players can fix it for themselves.

By the time I noticed it, I was fighting skeleton hulks without even having the time to craft real armor. And my monster evolution is set to 7 at the beginning of every game! I know this is an issue unrelated to Proficiencies, but I genuinely can't find a way to start its own issue without coming off as someone who's just "whining because the game is too hard" and who needs to "git gud".

**Comment by Terrorforge** [comment]
You know, I'm inclined to agree. The default balance should be geared towards casual and inexperienced players. We should expect veterans to make their games more challenging for themselves, not expect new players to figure out how to make their games easier.

And you make good points about the nerfs to books and crafting speeds meaning that it takes longer to get going. I was certainly taken aback by how deadly the zombies had gotten after the first time I knuckled down to craft survivor armor.

If you focus on those concrete points, I don't think you'll come across as whining.

**Comment by cataclysmsurvivalist** [comment]
Hm, if it isn't enough here, I'll try to start a new issue with the exact same words. Hope they take notice if that's the case, being a mid-tier player in a land made for high-tiers and powergamers isn't great fun as awesome as CDDA is.

**Comment by Terrorforge** [comment]
Yeah, you'll want to make a new issue. Devs look at issues, discussions halfway through the comments not so much.

**Comment by GoLoT** [comment]
Linking #53534 for reference since it also mentions proficiencies as an alternative approach.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.

**Comment by anothersimulacrum** [comment]
Implemented in https://github.com/CleverRaven/Cataclysm-DDA/pull/69156
