### ISSUE TITLE
Appliance fridge has the same storage capacity as a minifridge

### ISSUE THREAD

**Issue by Rjtheperson** [CleverRaven/Cataclysm-DDA#53797]
### Describe the bug

The Appliance fridge has the same 75 liter capacity as the vehicle mini fridge.

### Steps to reproduce

1. Obtain and place appliance fridge.
2. Obtain and install vehicle mini fridge.
3. Notice that both refrigerators have the same storage capacity.

### Expected behavior

The bigger refrigerator should have more capacity than the mini fridge.

### Screenshots

![image](https://user-images.githubusercontent.com/65632694/147422208-84071d89-fc66-4daf-925d-248d7ec046aa.png)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 34f079e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Rummaging [Rummaging],
    Graphical Overmap [Graphical_Overmap],
    Mythical Martial Arts [MMA],
    No Rail Stations [No_Rail_Stations]
]

### Additional context
When crafting the Fridge it has stats like this: 
 
"pocket_type": "CONTAINER",
        "rigid": true,
        "watertight": true,
        "max_contains_volume": "700 L",
        "max_contains_weight": "400 kg"
        
Upon placing it with the construction menu it goes down to 75 Liters.

**Comment by RoyBerube** [comment]
The volume is taken from the following json code, where each unit = 250ml:
https://github.com/CleverRaven/Cataclysm-DDA/blob/3c23511d057da50178b2e4e6db9a66bc42c8e5c4/data/json/vehicleparts/appliances.json#L17

The result is 75L. The info that indicates it is 700L is not being used. 

I changed the number to 2000 and get 500L in the resulting fridge after placing it.

Looking at a typical fridge with no freezer shows that 17.78 cubic foot or about 500L is around average. https://www.homedepot.com/p/Whirlpool-17-78-cu-ft-Freezerless-Refrigerator-in-White-WRR56X18FW/206891678#product-section-overview

**Comment by Rjtheperson** [comment]
Awesome, do you plan on making a PR to make that an official change?

**Comment by RoyBerube** [comment]
No one is objecting to the volume, so I'll give it a shot.
