### ISSUE TITLE
Menu For Organizing Pockets and Storage

### ISSUE THREAD

**Issue by bombasticSlacks** [CleverRaven/Cataclysm-DDA#53806]
### Is your feature request related to a problem? Please describe.

Currently it is getting cumbersome to organize your pockets appropriately.

Now that exterior pockets are in #53283 and with there being a desire for rummaging there is no longer almost always an objectively best pocket for an item. As well if rummaging becomes a thing having organized internal pouches (like a first aid box, tool box, pill planner) will be important.

There are a few things I would like to do (and like feedback on) related to this but this part is related to a general UI.

This is also partially related to #51612

### Solution you would like.

Add an additional tab to the inventory menu called something like "organize" which looks something like this:
![image](https://user-images.githubusercontent.com/4514073/147476888-c3bdf4e2-54f4-446e-9214-9de3cd16283c.png)

This is a paint mockup but the core idea would be: You could see what items are stored in what pockets and what items in a hierarchy like you see when doing pickup. This menu would combine the power of the pocket settings menu (when hovering a pocket) with the ability to reorganize items. On highlighting some items you will be able to move them to other pockets (if it has the space). I didn't show it well in the mockup because it gets tedious building the mockup but this menu would also let you put things in internal pockets of internal items. So you could move med supplies into an IFAK's pocket inside your Backpack. 

### Additional context
Wish list from other people:

- [ ] priority number next to the name of the pocket
- [ ] change the colour if the pocket has item restrictions
- [ ] descriptions included.

**Comment by Terrorforge** [comment]
I think it would be helpful if the pockets showed their priority and black/whitelist settings in some intuitive way. Maybe just the priority number next to the name of the pocket, and change the color if the pocket has item restrictions.

Another option that was suggested months ago is something like the layering menu for clothing that lets you visually sort pockets according to priority. That sounds great, but I'm not sure you could directly combine it with this menu without cluttering it, so maybe it'd have to be a separate window.

**Comment by bombasticSlacks** [comment]
Yeah I think shuffling pockets would muddle the intent of this menu (clear layout and hierarchy). The desire for this was born out of sometimes when I'm playing with complex pocket structures I just drop the bag or whatever so I can clearly see whats in what. 

That said I really like the other suggestions and will put them in the original feature notes when I get to implementing it.

**Comment by bombasticSlacks** [comment]
Oh I've done this lol closing
