### ISSUE TITLE
extended toolset shaws wrong quality

### ISSUE THREAD

**Issue by alp7292** [CleverRaven/Cataclysm-DDA#53809]
### Describe the bug

  "id": "toolset_extended", has      [ "CUT", 1 ],  while fake item has      [ "CUT", 2 ], so you still have      [ "CUT", 2 ], but info shows it wrong

### Steps to reproduce

check the value in items tools workshop

### Expected behavior

should have [ "CUT", 2 ],

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 83b08cc [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Arcana and Magic Items [Arcana],
    MST Extra [MST_Extra],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    alpermodd [alpermm]
]

**Comment by hexagonrecursion** [comment]
The bionic in question is now called "integrated multitool" (id: bio_tools).

There are two toggles: Extended Multitool and Integrated Multitool. The item in your hands comes from the Extended Multitool, cut 2 is provided by the Integrated Multitool.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: f8734ab [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by wapcaplet** [comment]
Working as intended.
