### ISSUE TITLE
Conversations on NPC dialogue are sometimes unreadable for mobile devices

### ISSUE THREAD

**Issue by AxemaVales** [CleverRaven/Cataclysm-DDA#53803]
### Describe the bug

Just as the title says. Long texts are cut-off and has no other ways to view the rest.

### Steps to reproduce

1. Play on a mobile device.
2. Talk to an NPC. Best to test this with the refugee center's merchant.
3. The conversation is cut-off.

### Expected behavior

It should show the rest of the dialogue. Pls bring back the side-by-side dialogue panel, or make it an interface setting.

### Screenshots

![Screenshot_2021-12-27-16-06-54-35](https://user-images.githubusercontent.com/73740745/147453484-08f6e7f4-e5e3-4a35-ad9b-ece847cffee4.png)

After pressing `e`

![Screenshot_2021-12-27-16-07-22-99](https://user-images.githubusercontent.com/73740745/147453505-fb514fa1-bd93-4956-83a4-d7c65771a169.png)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: OPPO; Model: A1601; Release: 5.1; Incremental: 1577332894; 
- Game Version: b5228cf [32-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by LeahLuong** [comment]
There are also mobile interface issues like this when it comes to the vehicle interaction & bionics menus. I believe there are a couple of other areas where text wraparound needs implementation but I can't remember them.

**Comment by LeahLuong** [comment]
Made this a feature request in #54756.

**Comment by AxemaVales** [comment]
Took a month and finally a hope to get this fixed.

**Comment by leemuar** [comment]
looks doable, Ill take a look at it

**Comment by Zireael07** [comment]
Is this still an issue? I understand there were some changes to both Android port and dialogues themselves since it was opened...
