### ISSUE TITLE
Filtering things by string "light" misbehaves

### ISSUE THREAD

**Issue by mkrutov** [CleverRaven/Cataclysm-DDA#53801]
### Describe the bug

I probably just don't understand something about the filter in various game menus.
Filtering things by string "light" doesn't work as expected. Example screenshot attached.

### Steps to reproduce

1. Have a bunch of items nearby. 
2. Use `w`ear, `/`AIM, or `g`rab menus
3. enter search term "light"

### Expected behavior

items with "light" in name, like "light amp goggles" or "light gloves", show up while other items are filtered out.

### Screenshots

![Screenshot_20211227_042536](https://user-images.githubusercontent.com/48674477/147431329-cfc0478e-4762-4843-941d-3aacd15e7ffd.png)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 34f079e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    DinoMod [DinoMod]
]

**Comment by dseguin** [comment]
The filter is matching against the hidden colour tags. The fix is very simple:
```diff
diff --git a/src/item_search.cpp b/src/item_search.cpp
index e2c651ca97..4b58b8051b 100644
--- a/src/item_search.cpp
+++ b/src/item_search.cpp
@@ -80,7 +80,7 @@ std::function<bool( const item & )> basic_item_filter( std::string filter )
         // by name
         default:
             return [filter]( const item & a ) {
-                return lcmatch( remove_color_tags( a.tname() ), filter );
+                return lcmatch( a.tname(), filter );
             };
     }
 }
```
