### ISSUE TITLE
Magiclysm: Technomancer Mana-Toolbar can't pry without charges

### ISSUE THREAD

**Issue by ilovehans10** [CleverRaven/Cataclysm-DDA#53813]
### Describe the bug

If you try to pry a crate/window with the technomancer mana-toolbar it will stop you if you don't have any charges and say:
"You attempt to pry open the window using your Technomancer mana-toolbar...
Your Technomancer mana-toolbar ran out of charges."
this seems like a bug to me as I doubt that you would be unable to pry with something crowbar shaped just because it ran out of charges.

### Steps to reproduce

1: Obtain a Technomancer mana-toolbar and a crate/window
2: Attempt to pry using the examine button
3: Get the message alerting you that you can't pry without charges

Alternatively
1: Obtain a Technomancer mana-toolbar and a crate/window
2: In the activate menu see that you can't activate any features of the crowbar when it is out of mana

### Expected behavior

As stated above I do believe that as the Technomancer toolbar is crowbar shaped it would make sense for it to be able to pry while it is out of charges. I believe that it is broken this way simply because of some standardization of the activation code that is prohibiting this.

### Screenshots

![image](https://user-images.githubusercontent.com/20823837/147495759-b0c466dd-de34-477f-8411-d4e49c0d0b63.png)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.F-4631-ga342e1eae3-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap],
    Magiclysm [magiclysm],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    C.R.I.T Expansion Mod [crt_expansion],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    Extra Mutated Scenarios [extra_mut_scens],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

Note my game version is only dirty because of some slight json editing I have done in totally unrelated files (stuff like adding belt clip tags to bags of holding)

**Comment by catdach** [comment]
Similar to #53607
