### ISSUE TITLE
Cannot use tailor's kit to modify clothes with leather, fur, or wool when more than 1 item required

### ISSUE THREAD

**Issue by StressedCondor** [CleverRaven/Cataclysm-DDA#53819]
### Describe the bug

You cannot modify clothing using the tailor's kit with leather, fur, or wool if it requires more than 1 leather patch, fur pelt, or felt patch respectively. It appears that the materials for these modifications are not properly discovered as available when multiple are required. The tailor's kit UI will display the options for these modifications as unselectable with a message like `Can't pad with leather (need x leather patches)` regardless of available resources. However, it is possible to modify clothing pieces which require only 1 of those resource. The steel plate and layered kevlar sheet modifications are available as expected when the resources are available. 

### Steps to reproduce

1. Create a character with a gambeson, pair of ankle socks, tailor's kit, 5 leather patches, 5 steel plates, 5 layered kevlar sheets, 5 fur pelts, and 5 felt patches.
2. Raise the character's skills to 10 (I don't know if this is necessary)
3. Apply the tailor's kit, select the modify clothing option, select the gambeson. This will display the leather, fur, and wool options as unavailable due to lacking resources. The steel plate and kevlar modifications will be available.
4. Apply the tailor's kit, select the modify clothing option, select the ankle socks. This will display the leather, kevlar, fur, and wool modifications as available. The steel plate modification is unavailable due to it being a restricted modification

### Expected behavior

When modifying a piece of clothing using the tailor's kit with leather, fur, or wool and the required amount of materials are available, then the modification should be able to be performed.

### Screenshots

**Inventory with appropriate materials**
![image](https://user-images.githubusercontent.com/96748194/147507458-93a30aef-feb3-43b9-8e55-2db7f9a98741.png)

**Modification UI for gambeson**
![image](https://user-images.githubusercontent.com/96748194/147507443-e2ce572c-57b9-48b4-93d8-eb95775adf88.png)

**Modification UI for ankle socks**
![image](https://user-images.githubusercontent.com/96748194/147507534-c48be348-2679-4e0d-b227-d854b7833727.png)

### Versions and configuration
Experimental build

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: f8734ab [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key]
]

### Additional context

**Relevant code**: 
Clothing modification definitions: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/clothing_mods.json
Tailoring resource definitions: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/items/resources/tailoring.json
Tailoring actor code: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/iuse_actor.cpp#L4545

**Stable release testing**
I could not reproduce this bug on the  0.F-2 release. All modification types are available as expected when following the steps outlined above.

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by GoLoT** [comment]
Bug introduced in #51576 when materials were changed into ammo-like items.

Fixed in #53604:
https://github.com/CleverRaven/Cataclysm-DDA/blob/6c8aa103b58018c53b2b1a6d900b635919f0b6f5/src/iuse_actor.cpp#L4601-L4604

**Comment by a-chancey** [comment]
Interesting, we were just having the debate today on discord about clothing parts not needing to be ammo. I'm gonna remove the ammo tag as part of #53436. I'll wind up implementing a new container for holding sheets as a bolt of fabric in the not too distant future, but rags and patches and scraps should be messy to transport.

**Comment by GoLoT** [comment]
@a-chancey any chance you could add the snippet I posted to one of your PRs? I think the plan is to turn materials back into generic items but the fix might be useful at some point if ammo-like items are used for clothing mods again.

**Comment by a-chancey** [comment]
@GoLoT im not seeing the snippet anywhere, or I would. I started today by changing cotton scraps to generic (and then had to do all of them due to copy-from), but my existing save had stacks of 100 of each scrap type get migrated to just 1 of each. I need to keep looking at this a bit further before I get into the recipe audit.

**Comment by GoLoT** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/6c8aa103b58018c53b2b1a6d900b635919f0b6f5/src/iuse_actor.cpp#L4601-L4604
`sew_advanced_actor::use()` in `iuse_actor.cpp` to allow checking for charges-

**Comment by matshou** [comment]
@GoLot you mention that that has been fixed in #53604, is this issue still valid then or not?

**Comment by GoLoT** [comment]
The PR was closed so the change didn't make it to master. I think someone changed rags, leather and so on back to generic items so the fix shouldn't be needed, but it's a quick fix if someone wants to PR it (see my last comment for the code changes).

**Comment by Mallowdust** [comment]
I just retested this, most updated experimental with no mods, just base game. As far as I can tell this is still not working for (felt patches, fur pelts, leather patches) because they are "ammo" layered kevlar panels don't have this, so they are working fine and you can modify clothing with them.

**Comment by a-chancey** [comment]
I'm still hung up by #54376 - once that's handled, I'll get the rest of the materials genericized. I just can't figure out how to pull it off properly so I'm stumped for the time being.

**Comment by Night-Pryanik** [comment]
No longer applicable after #58035.
