### ISSUE TITLE
Briefcase and wrist watch conflict when worn on same side

### ISSUE THREAD

**Issue by airportation** [CleverRaven/Cataclysm-DDA#53822]
### Describe the bug

Briefcase and wrist watch conflict when worn on same hand.

### Steps to reproduce

1. Get or cheat yourself a briefcase and a watch (should work with any; only tested with ordinary wrist watch)
2. Press your Sort Armor key
3. Notice how it tells you that "Wearing multiple items strapped to you on your left hand is adding encumbrance there."

### Expected behavior

Shouldn't have a conflict because wrist watches are worn on, supposedly, the wrist. Briefcases are however held in one's hands. At 8 INT, I should be aware of how to wear a watch.

### Screenshots

![grafik](https://user-images.githubusercontent.com/67428677/147514667-2c11bad2-9d76-44ca-baaf-a7c4efa5f93f.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: f8734ab [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    No Monsters [Only_Wildlife],
    Extra Mutated Scenarios [extra_mut_scens],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex]
]

**Comment by NetSysFire** [comment]
This looks like a limitation of the current clothing/layers system. Both the wrist watch and the briefcase can cover either hand and are strapped onto it, so the game thinks they might occupy the same space. Note that we do not have a "wrist" here, only a hand.

**Comment by KittyTac** [comment]
With the new changes where belts and harnesses no longer conflict it should be a simple JSON change to do the same for wrist watches and shopping bags/briefcases.

**Comment by LeahLuong** [comment]
Would it be possible to introduce a wrist location for arms?? Torso is subdivided into waist & itself. I think there's currently a limb rework underway, maybe this can be shoehorned in. After all, wrist watches are strapped to your wrist, not your hand. If this change is made, ankle should prob be done for legs as well.

Briefcase is somewhat unique in that it is held by a handle in 1 hand. This wouldn't really interfere w/ pistol shooting but would hinder reloading. Handling a rifle would be more difficult while still hanging onto a briefcase. & wielding a 2-handed melée weapon would be most hindered by a briefcase but 1-handed not so much. I don't believe the game fully models this as it ideally would be but it'd be nice to see the game get there someday.

**Comment by NetSysFire** [comment]
@Venera3 is doing the limb rework. Maybe they could say if the JSON change or a whole new limb part would be better.

**Comment by Venera3** [comment]
Yeah, it will probably be easy to fix with an extra sublocation but I haven't really looked into how those work yet. That will do for the moment, but it does kinda sidestep the whole multiwield question (as does the rest of Limb Stuff, for now).
