### ISSUE TITLE
Mad Militia - Accuracy Broken?

### ISSUE THREAD

**Issue by TheMurderUnicorn** [CleverRaven/Cataclysm-DDA#53824]
### Describe the bug

Recently, ferals with automatic weapons were added to the game.  I have been testing them to discuss them in an upcoming video.  In my testing they have apparently 99-100% accuracy, even when off-screen.  Even in a kevlar vest and SWAT armor, I am killed by 2 rounds to the torso.  This enemy does not seem to miss, has 5.56 ammo damage, can hit you from off screen, and comes with 10 rounds which are more than enough to kill you.

I don't know what the intended goal was here, but they are comically broken.  We limit the ammo given to ferals to show that they are not competent enough to gather ammo and reload their weapons.  And yet they possess the ability to have a 2 in rifles skill and a 2 in marksman.  They can't understand how to reload a gun but they understand how to perfectly execute distant players.

This needs balanced.  This will kill a lot of new players especially, but having an enemy literally shoot you from offscreen with more accuracy than you can get as the player is infuriating and is going to lead to a lot of feelsbads.

Please, go spawn a mad militia offscreen at around 20-30 tiles and witness their relentless accuracy and watch your character die immediately.

### Steps to reproduce

Debug spawn a mad militia just offscreen.
Wait in place for a little while.
Witness the 100% accuracy and immediate death of your character.

### Expected behavior

Ferals, to my understanding, would not really possess the ability to be this accurate with a weapon.  There may be some ferals that would be of higher intelligence that handle their, uh, feralism, in a meaningful way, but I believe Erk said they would be rare.  

Aside from that, from an actual gameplay balance sense, this is comically unbalanced.  As far as I can tell this thing is basically just a turret that can move and follow you.  My take on a feral with an assault rifle would be -- approach them at range, let them pop off wildly while they're far away/deplete their ammo, then move up and the two of you fight it out in melee.  Even in a gun to gun fight, human players *should* have the edge against a feral.  But with our current aiming system, I cannot hit anywhere near as accurate at they can at these ranges.  The player should definitely be the one with the edge in this circumstance, not some random crazed animalistic human that happens to have a firearm.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: f8734ab [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

### Additional context

Paprika suggested this may have something to do with the fake_dex and whatnot is being calculated.  I don't know if that's correct, I don't know anything about that.

It really is very obvious that it's not working as intended, though, go debug spawn a few of them and check the accuracy, it's much higher than it should be.

**Comment by TheMurderUnicorn** [comment]
Sigh.  Apparently this is a duplicate of an existing issue.  Wish I'd seen that before I typed out all this.  x_x

**Comment by wapcaplet** [comment]
Yeah, duplicate of #53707. Thanks anyway for writing it up.
