### ISSUE TITLE
shots from M16A4 autonomous TALON UGVs go through reinforced windows, reinforced glass doors and even other monsters in order to hit the player.

### ISSUE THREAD

**Issue by cataclysmsurvivalist** [CleverRaven/Cataclysm-DDA#53834]
### Describe the bug

It seems like TALON UGVs now have the ability to shoot bullets that phase through reality in order to home in on you. If this was only about going through monsters it would make _some_ sense, they are military supercomputers after all, and being able to not shoot their own is part of the AI, but going through reinforced glass makes no sense.

### Steps to reproduce

1. Spawn reinforced windows/reinforced glass doors
2. Put the player in one side, and the TALON UGVs in the other
3. Get shot through it

### Expected behavior

I'd expect the bulletproof glass to stop the bullet instead being penetrated by them.

### Versions and configuration

build type: windows-tiles-x64
build number: 2021-12-27-0903
commit sha: f8734ab57e2c11def95f3e905137755381106c47
commit url: https://github.com/CleverRaven/Cataclysm-DDA/commit/f8734ab57e2c11def95f3e905137755381106c47

**Comment by mkrutov** [comment]
Player can also shoot through reinforced glass with some success (much lower damage).

**Comment by Maleclypse** [comment]
Reinforced glass is not ballistic glass, which also exists.  Reinforced glass is the wired glass in firedoors.
