### ISSUE TITLE
Save fatal error

### ISSUE THREAD

**Issue by kydsh** [CleverRaven/Cataclysm-DDA#53831]
### Describe the bug

there is no way to load the save

### Steps to reproduce

1.load save file
2.get errors

### Expected behavior

expect to load

### Versions and configuration

windows 10

2021-12-28-0235

russian language

mods:  "dda", "blazeindustries", "aftershock", "crt_expansion", "no_hope", "StatsThroughSkills", "speedydex", "stats_through_kills", "stamina_regen_buff", "crazy_cataclysm", "Graphical_Overmap", "WHALEYHAIR1"

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7784285/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7784286/crash.log)
[world.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7784288/world.zip)

**Comment by ZhilkinSerg** [comment]
Your save is broken and there is nothing we can do here. Use savegame from one of your backups (start a new game and start doing backups if you don't have a backup available).

**Comment by ZhilkinSerg** [comment]
Additionally if you know a reliable way to reproduce the way to break a savegame - we can look into fixing that (if it is related to some code bug).

**Comment by kydsh** [comment]
> Additionally if you know a reliable way to reproduce the way to break a savegame - we can look into fixing that (if it is related to some code bug).

most likely the error occurred when, after the death of the previous character, I saved the world and continued to play with the new one, after I tamed the cat and performed other actions (in debugging), saving began to assign actions to the dead character and the world collapsed
