### ISSUE TITLE
Allow autodrive to go faster than 19 km/h

### ISSUE THREAD

**Issue by KittyTac** [CleverRaven/Cataclysm-DDA#53832]
### Is your feature request related to a problem? Please describe.

Autodrive is good and useful with the changes, it never crashed for me. But it goes really slowly, at most 19 km/h but often just 6. This makes it time-inefficient.

### Solution you would like.

Instead of having a speed cap of 19, make the cap be the speed that the vehicle was set to when autodrive was turned on, though it should slow down when needed, e.g taking turns slowly and slowing down or swerving to dodge obstacles. But e.g if you were setting your speed to 72 before opening the map and setting the target location, autodrive would go at 72 km/h at straight-aheads. This would make it far more efficient, time-wise.

### Describe alternatives you have considered.

Doing nothing and keeping this feature situational.

### Additional context

N/A.

**Comment by Terrorforge** [comment]
Honestly I would settle just for consistent 19km/h speeds. Whatever calculations determine that seem borked, because it only affects heavier/weaker vehicles, but it doesn't seem to matter that those vehicles are perfectly capable of running and navigating at well over 19km/h in normal gameplay

**Comment by KittyTac** [comment]
> Honestly I would settle just for consistent 19km/h speeds. Whatever calculations determine that seem borked, because it only affects heavier/weaker vehicles, but it doesn't seem to matter that those vehicles are perfectly capable of running and navigating at well over 19km/h in normal gameplay

19 km/h is still too slow for my tastes TBF. I like going 45.

**Comment by Alex-Folts** [comment]
I think autodrive speed could be set to speed limit for cities of New England, but not higher than vehicle's safe speed.

**Comment by PatrikLundell** [comment]
Higher speeds make the required calculations more difficult, as the code would have to juggle different acceleration and deceleration rates for different vehicles, resulting in more edge cases that would have to be managed, and more edge cases that aren't caught with the resultant [vehicle] crashes).

Not saying a higher speed limit wouldn't be desirable, just that it's harder to implement. I find it amazing that a working system has been implemented at all.

**Comment by a-chancey** [comment]
Yeah my mobile base likes to hit 12mph for a single turn, then slow back to 4mph for a few turns and repeats this, jerking back and forth and burning way more gas than needed with all the acceleration. It won't stay steady at all - I'd rather have stable 4mph than this situation. I can't even get a stable speed on a long clear straightaway or an empty bridge devoid of enemies, even if my auto drive path is shorter than the second level of the bridge. Something just breaks with big vehicles. 

And my motorcycle stays a steady 12mph and it feels like I'm _flying_.

**Comment by KittyTac** [comment]
> Higher speeds make the required calculations more difficult, as the code would have to juggle different acceleration and deceleration rates for different vehicles, resulting in more edge cases that would have to be managed, and more edge cases that aren't caught with the resultant [vehicle] crashes).
> 
> Not saying a higher speed limit wouldn't be desirable, just that it's harder to implement. I find it amazing that a working system has been implemented at all.

Yeah but why not make it go fast just on straight roads, slowing down to go around obstacles? That shouldn't be hard to implement.

**Comment by PatrikLundell** [comment]
> > Higher speeds make the required calculations more difficult, as the code would have to juggle different acceleration and deceleration rates for different vehicles, resulting in more edge cases that would have to be managed, and more edge cases that aren't caught with the resultant [vehicle] crashes).
> > Not saying a higher speed limit wouldn't be desirable, just that it's harder to implement. I find it amazing that a working system has been implemented at all.
> 
> Yeah but why not make it go fast just on straight roads, slowing down to go around obstacles? That shouldn't be hard to implement.

You're free to try to implement it. I suspect that you'll find that is isn't as straight forward as it might seem, or the implementor would already have provided it. However, if you pull it off, I'm sure going to be happy about it.

One thing that gets complicated with a larger range of speeds is prediction of the path so you know when you need to start to reduce the speed. It's not impossible to do, of course, but it requires care, looking out for edge cases, and a whole lot of testing. I'm also not sure how it will affect skidding and recovery from skidding.

**Comment by Meandering-Breviger** [comment]
This is me testing with helicopters. As a speed limit with helicopters is more poignant, especially with some helicopters having a very high max speed.

/src/vehicle_autodrive.cpp
```
// min and max speed in tiles/s
static constexpr int MIN_SPEED_TPS = 1;
static constexpr int MAX_SPEED_TPS = 3;
```
Bumping `MAX_SPEED_TPS` to 6 gives a seemingly stable 24mph whereas 12 gave me a buggy 48mph, where the speedometer blinked rapidly between 4 and 48mph.

Perhaps` MAX_SPEED_TPS` can be thrown into settings as an adjustable setting albeit an experimental one?

**Comment by KittyTac** [comment]
> This is me testing with helicopters. As a speed limit with helicopters is more poignant, especially with some helicopters having a very high max speed.
> 
> /src/vehicle_autodrive.cpp
> 
> ```
> // min and max speed in tiles/s
> static constexpr int MIN_SPEED_TPS = 1;
> static constexpr int MAX_SPEED_TPS = 3;
> ```
> 
> Bumping `MAX_SPEED_TPS` to 6 gives a seemingly stable 24mph whereas 12 gave me a buggy 48mph, where the speedometer blinked rapidly between 4 and 48mph.
> 
> Perhaps` MAX_SPEED_TPS` can be thrown into settings as an adjustable setting albeit an experimental one?

That seems like the best solution, say that it might lead to unintended behavior if put above 6.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
