### ISSUE TITLE
Edge case when manually spawning map extras adjacent to the player

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#53830]
### Describe the bug

There is an (apparently literal) edge case where spawning a map extra adjacent to the player via the debug menu yields an error.

### Steps to reproduce

1. Create a new world.
2. Spawn a map extra (I used `mx_crater`) one overmap tile away so it is still in your field of vision.
3. Witness an error

```
 DEBUG    : loading non-main map at (-1130,924,0) which overlaps with main map (abs_sub = (-1135,922,0)) is not supported

 FUNCTION : void map::load(const tripoint_abs_sm&, bool, bool)
 FILE     : src/map.cpp
 LINE     : 6624
 VERSION  : 0.F
```

### Expected behavior

No error. The map extra appears to be generated correctly though.

### Versions and configuration

- experimental (from 2021-12-21)

**Comment by Night-Pryanik** [comment]
I can confirm this error, though it pops even if I spawn map extra far away from my character's position.

**Comment by a-chancey** [comment]
I get the same error when building faction camp expansions currently

**Comment by NetSysFire** [comment]
Does it still work or does the error break it?

**Comment by a-chancey** [comment]
It still works, just throws the error
