### ISSUE TITLE
Methanol Byproduct from Crafting Moonshine Mash

### ISSUE THREAD

**Issue by Somus88** [CleverRaven/Cataclysm-DDA#53836]
### Describe the bug

Crafting Moonshine Mash with:
15 Water
12 Pumpkin
50 Sugar
2 Yeast
Will result in 105 Mash and a byproduct of 68750 Methanol (or 68.75L of Methanol)
The recipe, according to HHG, will make a byproduct of only 275 Methanol. I suspect there's a mistake in the recipe.

### Steps to reproduce

1. Make a world, spawn in 15 units of water in any container, 12 Pumpkin, 50 Sugar, 2 yeast, and the 'family cookbook' book for the recipe.
2. Craft a single batch of moonshine mash.
3. Watch as the game gives you 68L of Methanol.

### Expected behavior

I expected the byproduct to result in a more reasonable amount, like just 2L or something.

### Screenshots

![IMG_20211228_184226](https://user-images.githubusercontent.com/96776245/147568248-b81f0b44-00b8-4bf6-8ce5-020811e1634c.jpg)
![Screenshot_2021-12-28-18-54-58-13_a77f7b094295b5a083bf400fa615cbfb](https://user-images.githubusercontent.com/96776245/147568423-bd533530-287e-4ec7-93ca-8af0972391ef.jpg)

### Versions and configuration

- OS: Android 11, ColorOS 11.1
- Game Version: Stable 0.F-3
- Graphics Version: Tiles
- In-game Language: English
- Mods Loaded: dda, Disable NPC Needs, Bionic Professions, Magiclysm, No Fungal Monsters, Fuji's Military Profession Pack, Magiclysm No Class Limit, Speedydex, Stats Through Kills, Stats Through Skills

### Additional context

I'm all in for mass producing biodiesel but 68L Methanol from really cheap materials is just too much imo.

**Comment by Terrorforge** [comment]
I suspect the intent is to produce 275 units of methanol, but apparently the game uses methanol's "count" value of 250, interpreting "one methanol" as 250 units, and thus "275 methanol" as 275*250=68750 units.

Should be as easy a setting the byproduct methanol to 1, although that will make the UI a bit confusing.

**Comment by Maleclypse** [comment]
Methanol should be no more than 12-15% of the total product volume.  So whatever number it needs to be to fix it to around that percentage.

**Comment by Somus88** [comment]
```
{
  "type": "recipe",
  "activity_level": "NO_EXERCISE",
  "result": "brew_moonshine",
  "id_suffix": "pumpkin",
  "result_mult": 15,
  "byproducts": [
    [
      "chem_methanol",
      2
    ]
  ],
  "category": "CC_FOOD",
  "subcategory": "CSC_FOOD_BREW",
  "skill_used": "cooking",
  "difficulty": 2,
  "time": "30 m",
  "batch_time_factors": [
    95,
    4
  ],
  "book_learn": [
    [
      "distilling_cookbook",
      1
    ],
    [
      "family_cookbook",
      1
    ]
  ],
  "qualities": [
    {
      "id": "BOIL",
      "level": 2
    }
  ],
  "tools": [
    [
      [
        "surface_heat",
        30,
        "LIST"
      ]
    ]
  ],
  "components": [
    [
      [
        "water",
        15
      ],
      [
        "water_clean",
        15
      ]
    ],
    [
      [
        "pumpkin",
        12
      ]
    ],
    [
      [
        "sugar",
        50
      ]
    ],
    [
      [
        "yeast",
        2
      ]
    ]
  ]
}
```

Took a year to respond lol, but I think this is correct. 2 units of Methanol will result in 500 mL of Methanol which is around 13-14% of the resulting product, 3,75L of moonshine. Any suggestions are welcome!

**Comment by LeahLuong** [comment]
@Somus88 It looks like you've found the relevant code & understand it's a unit conversion issue. You should submit this as a PR for inclusion in an imminent release.
