### ISSUE TITLE
Add presistent examine screen to the left side of the get interface.

### ISSUE THREAD

**Issue by taivo-tobreluts** [CleverRaven/Cataclysm-DDA#53835]
### Is your feature request related to a problem? Please describe.

As a new player, I do a lot of examining when looting, as I have no idea what are the properties of every single item. Which ones have some useful tool property, what clothes have better stats, what items disassemble into useful materials?

Right now I have to press `e` on each individual item and then again to close the examine menu before looting, and with kitchen drawers and dressers having more than ten items each this takes some time.

### Solution you would like.

I propose a toggleable examine window on the left side of the screen while in get interface, similarly how it worked in the E.0 stable.

### Describe alternatives you have considered.

Simpler alternative would be able to move between items while the examine menu is open. That would mean you would have to press `e` once and it  would look less elegant, but would still improve the user experience a lot.

### Additional context

How it works now:
![current_behavior](https://user-images.githubusercontent.com/90152901/147567885-79b831ca-c745-4af5-9d55-0c772e19b83e.png)
What would make me super happy:
![proposed behavior](https://user-images.githubusercontent.com/90152901/147567916-c1920a03-633f-4fd4-901e-afef02a641e6.png)

**Comment by ZhilkinSerg** [comment]
80x25/24 is minimum supported terminal size.

**Comment by Zireael07** [comment]
Yes, but I think better use could be made of the space IF someone is running a bigger size?

**Comment by taivo-tobreluts** [comment]
> 80x25/24 is minimum supported terminal size.

That's why it would be toggleable, so that people with old laptops and square monitors can still keep pressing `o` as usual.

2021 Stream hardware survey shows that only 13% of people have a screen smaller than 1920x1080 with the numbers dropping fast.

**Comment by taivo-tobreluts** [comment]
> 80x25/24 is minimum supported terminal size.

What does this mean? Is it a technical limitation of the game engine?

**Comment by Zireael07** [comment]
@taivo-tobreluts: No, not a limitation of engine - a wish to support people who use standard console/terminal (e.g. blind players and people playing on really bad computers that don't support SDL)

**Comment by taivo-tobreluts** [comment]
I mean it would be optional, not something to replace the examine window entirely. 
How did the old examine/get combo interface in E.0 work with terminal mode?

**Comment by BrettDong** [comment]
> > 80x25/24 is minimum supported terminal size.
> 
> What does this mean? Is it a technical limitation of the game engine?

It is not a technical limitation, it means the game is required to support terminals as small as 80x25 because some players need it.

**Comment by spamman63** [comment]
Honestly just waiting until this feature comes back to play again, can't really do without it

**Comment by mqrause** [comment]
Is the menu code aware of the terminal size? That should make it easy to decide where to place the windows depending on the available space.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
