### ISSUE TITLE
Loose gambeson is considerably harder to repair than normal gambeson

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#53845]
### Describe the bug

Loosened a gambeson and noticed with 7 tailoring I had 0% chance to refit and 4% chance to damage. Put it back to normal and had 8% to refit , 0% to damage. Same with kevlar gambeson.

### Steps to reproduce

1. Loosen a freshly spawned gambeson.
2. Note before and after difficulty of retailoring.

### Expected behavior

Difficulty should be the same.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: cb14c61 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots]
]

**Comment by bombasticSlacks** [comment]
All the gambesons that are loose need a repairs like, pointing to their base version.

**Comment by NetSysFire** [comment]
Can reproduce, looks like the fix might be easy enough, too.
