### ISSUE TITLE
Attempting to drink dirty water through examine gives warning about raw meat

### ISSUE THREAD

**Issue by robob27** [CleverRaven/Cataclysm-DDA#53849]
### Describe the bug

When attempting to drink unclean water with a chance of parasites the player will be warned that eating raw meat is probably unhealthy. This seems to only happen when using "Examine" and "Consume it", and not when trying to drink dirty water through the Consume (E) menu.

### Steps to reproduce

1. Go to some water you can examine that is unclean
2. Attempt to consume the water using Examine and Consume It
3. Note the message about raw meat

### Expected behavior

I expect that the warning will not be about meat if I am drinking water. I mean it's a good tip but irrelevant in the context :P

### Screenshots

![image](https://user-images.githubusercontent.com/2104555/147609424-13c9c17f-bf52-4297-86cc-ec67b16f58e1.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 40ed6f5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

When initially created this issue stated that the issue didn't happen with toilets. I thought this was the case because I tried to consume that water with E rather than e. It does occur with toilets as well.

**Comment by robob27** [comment]
Looks like raw meat is hardcoded in to the consequence message [here](https://github.com/CleverRaven/Cataclysm-DDA/blob/a8b07e8705daac6764b7df1369aab834f172e8af/src/consumption.cpp#L827)

**Comment by NetSysFire** [comment]
Can reproduce. This is probably caused by murky water.

**Comment by NetSysFire** [comment]
#53760 is the PR that added murky water. I can not reproduce that in toilets but in swamps. The issue is the same though.
