### ISSUE TITLE
Treat Vehicle Parts with Different Damage/Degradation as Separate During Installation

### ISSUE THREAD

**Issue by legendblade** [CleverRaven/Cataclysm-DDA#53847]
### Is your feature request related to a problem? Please describe.

Prior to #52744 and #53431, when adding new parts to vehicles, it was annoying, but overall a non-issue when your character chose the most damaged steel frame ever instead of the stack of perfectly new shiny ones to use - it only really cost time(/food) and power.

Now that we have to use up consumables in order to both attach and repair vehicle parts (repairs which sometimes cost more than removing and reinstalling a new part), this has become far more problematic. This is compounded by the degradation aspect, in that we not only have to worry about a damaged part being chosen, but also part with more degradation.

Currently, the only two ways (I can think of) to ensure that you use the right part is:
- Pick up the specific part you want installed, forcing component selection (`12 steel frames nearby`, vs `1 steel frame (on player)`); which is annoying when you can only carry one of them but want to install a dozen
- Move all damaged parts out of range; less problematic for bulk work, but sometimes tracking down every busted part in range is a chore in itself

### Solution you would like.

I would propose that, when attaching parts, the component selection screen pops up if you have applicable parts that have different damage or degradation levels, and allows you to choose which one you want installed, grouped by their damage/degradation.

### Describe alternatives you have considered.

Another way to solve the core issue would be to have part installation prioritize the least damaged/degraded part, however, this feels like it ends up causing two other issues, namely:
- If you actually wanted a damaged part - for instance, you were working on two vehicles in close proximity and you only needed one to have good parts - you would end up with the same issue, only in reverse
- How do you balance damage versus degradation in the selection algorithm, and would everyone see it in the same way

Alternatively to having the component selection screen pop up every time - I can see that being annoying, adding an extra step to the process - a separate keybind could be added for "install" versus "install specific part", but that feels like overengineering the solution

**Comment by Alex-Folts** [comment]
Related https://github.com/CleverRaven/Cataclysm-DDA/issues/11706
