### ISSUE TITLE
[Magiclysm] Wildshape Cloak: Bear gives 200 eye encumbrance

### ISSUE THREAD

**Issue by gisaku33** [CleverRaven/Cataclysm-DDA#53853]
### Describe the bug

When putting on the Wildshape Cloak: Bear, your eye encumbrance goes to 200 and remains that way after removing the cloak. The encumbrance goes away when taking off/putting on something on the eyes.

### Steps to reproduce

1. Make a character and give them a Wildshape Cloak: Bear.
2. Wear cloak, check blindness.

### Expected behavior

Assuming this is unintended, to not be given massive eye encumbrance from the cloak.

### Screenshots

![image](https://user-images.githubusercontent.com/23239811/147621359-5c6971c3-8aca-4c2b-80a4-99eb2831055c.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: d239083 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

### Additional context

@GuardianDll asked me to ping him, so that is this part here, with the ping.

**Comment by GuardianDll** [comment]
one of the mutation that used in wildshape_cloak_bear is `WILDSHAPE:BEAR` that has ` "encumbrance_always": [ [ "eyes", 200 ] ]`
not sure is it really supposed to be so high, for example, the `WILDSHAPE:FISH` and `WILDSHAPE:DEER` have ` "encumbrance_always": [ [ "hand_r", 50 ], [ "hand_l", 50 ], [ "arm_r", 50 ], [ "arm_l", 50 ] ]`, but the real problem is fact its not turns off if you drop it on the ground, only if you put it onto your inventory. On a screenshot i have no mutation, but i still have his effect
![image](https://user-images.githubusercontent.com/67688115/147621801-7fbb452d-c555-4fec-833e-673960cfd5d2.png)

**Comment by ZhilkinSerg** [comment]
It is intended - see https://github.com/CleverRaven/Cataclysm-DDA/pull/42944:

![image](https://user-images.githubusercontent.com/16213433/147638765-47e43f21-fd81-4080-8b1a-811038b73116.png)

**Comment by NetSysFire** [comment]
But even that the encumbrance stays until you wear something that covers the eyes? That looks buggy to me tbh

**Comment by ZhilkinSerg** [comment]
Something's wrong with `encumbrance_always` then.

**Comment by gisaku33** [comment]
To clarify, 200 eye encumbrance doesn't just make it hard to shoot, it makes you completely blind and unable to see even a single tile away, are you sure blindness is intentional?
![image](https://user-images.githubusercontent.com/23239811/147772248-33db4dcc-9879-4f81-88b9-bd50fe9135b9.png)

**Comment by ZhilkinSerg** [comment]
There is a link to and screenshot from original implementation PR.

**Comment by gisaku33** [comment]
I'm aware, I was asking because they referenced "making ranged combat very difficult" where what it actually does is completely blind you, which seemed more severe than intended. If it is then it is, I was just making sure the blindness aspect was intended.
