### ISSUE TITLE
Let players disable firing modes on guns

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#53867]
### Is your feature request related to a problem? Please describe.

With guns that have multiple firing modes, it's often the case that you only regularly use one or two of them. For example, when I have an assault rifle with an underbarrel weapon, I frequently want to switch between semi-auto and burst with "F", but only want to use the underbarrel weapon situationally. Usually having to cycle an additional time and occasionally wasting ammo is merely annoying, but with an underbarrel grenade launcher preventing accidental discharge is a matter of life and death.

### Solution you would like.

Let players remove any firing mode(s) they wish from the "F" rotation.
![image](https://user-images.githubusercontent.com/5107449/147664135-31781019-b8ce-469f-b4fd-a5dbf92554b5.png)
While in this f->s (or f->F) firing menu, pressing * while highlighting a firing mode could take that mode out of the "F rotation", meaning you can only access it by going back into the f->s menu and selecting it manually.

This way, there's little risk of accidentally using that firing mode, but it remains available when needed.

### Describe alternatives you have considered.

If it wasn't broken (#53863) the "Burst-Fire Wielded Item" hotkey would go a long way towards solving this for me personally, but it doesn't offer protection against the disastrous accidental discharge of e.g. grenade launchers. This solution is also more flexible, and allows for things like disabling the semi-auto on the RM232 because you'd rather have 2-round and 4-round burst. disabling one rube of the Tavor-12 reserved for specialty ammunition, etc.

**Comment by Zireael07** [comment]
Seconding

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
