### ISSUE TITLE
Losing "leaping legs" mutation does not also lose leap spell

### ISSUE THREAD

**Issue by angryisosceles** [CleverRaven/Cataclysm-DDA#53860]
### Describe the bug

Losing the "leaping legs" mutation, either through purification/mutagen or through the debug menu, does not prevent the player from knowing and using the short leap spell, even if that spell was only added by the mutation.

### Steps to reproduce

1. Obtain the leaping legs mutation
2. Lose the leaping legs mutation
3. Go into the spell menu and cast leap

### Expected behavior

I expected to forget the short leap spell when I lost the legs, especially since I am not playing with the Magicalysm mod.

### Versions and configuration

OS: Windows 10
Game Version: d0422db
Graphics: Tiles
Language: English
Mods: Default (no magicalysm)

**Comment by GuardianDll** [comment]
i believe the `MUST_HAVE_CLASS_TO_LEARN` flag has something that allow to delete the flag when mutation is lost
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/magic.cpp#L1739

**Comment by GuardianDll** [comment]
Futher testing, that i made, due the #60707, shows that, as i predicted, `"spell_class": "LEAPING_LEGS",` and `MUST_HAVE_CLASS_TO_LEARN` flag really works as intended - the spell is gain by mutation, and deleted when mutation is gone
i guess we can just change the `spell_class` field's name to something another in the future, but right now it works 
![image](https://user-images.githubusercontent.com/67688115/188264496-a685e40b-7474-44e3-817a-cd7526beb661.png)
