### ISSUE TITLE
"Burst-Fire Wielded Item" hotkey not working

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#53863]
### Describe the bug

There is a "burst fire wielded item" hotkey that can be bound in the options, but it doesn't work properly. When wielding the M16A4, which has semi-auto and a 3-round burst, the key does nothing. When wielding the SCAR-H and M4A1, which both have semi-auto and a 4-round "auto" burst, the key brings up the firing menu, but it functions exactly like the default firing menu, firing in semi-auto or burst based on what mode the gun is currently set to.

### Steps to reproduce

1. Give yourself the aforementioned guns, w/ ammo
2. Bind a "Burst-Fire Wielded Item" key
3. Attempt to use the key to burst fire

### Expected behavior

Pressing the key should allow me to burst fire without manually changing the firing mode. It should recognize both 3-round bursts and 4-round full-auto.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: f8734ab [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by hexagonrecursion** [comment]
Confirmed

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: eacb7d9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
