### ISSUE TITLE
Inconsistent tailoring difficulty between cargo pants and army pants

### ISSUE THREAD

**Issue by JyeGuru** [CleverRaven/Cataclysm-DDA#53889]
### Describe the bug

Army pants are a straight upgrade over cargo pants (+5 warm, +0.13 protection, for max +1 extra encumbrance when full), but they are significantly easier to reinforce.

### Steps to reproduce

- Get a pair of cargo pants and a pair of army pants
- Get a tailoring kit, thread, and patchwork cotton bits
- Set tailoring to 3
- Activate kit on both cargo and army pants, noting the difficulty ratings

### Expected behavior

Army pants being the same, or harder, to reinforce than cargo pants

### Screenshots

![image](https://user-images.githubusercontent.com/5215014/147755855-213d5afd-e49b-4308-9731-a3cba592d21c.png)
![image](https://user-images.githubusercontent.com/5215014/147755857-d6103a79-b32c-4e16-adfe-811fefdb5f2d.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 3c154af [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA]
]

### Additional context

![image](https://user-images.githubusercontent.com/5215014/147755888-bc2ef3b1-dcde-416b-8f72-57af8f3ad429.png)

**Comment by a-chancey** [comment]
I'll peek at this while working on #53436 as part of the recipe audit I'm working on. Hoping to get through as much as I can this weekend, it's been a busy week and a half
