### ISSUE TITLE
Toad in a hole doesn't require fire/tools to cook

### ISSUE THREAD

**Issue by JyeGuru** [CleverRaven/Cataclysm-DDA#53885]
### Describe the bug

Toad in a hole can be made without a stove/fire

### Steps to reproduce

- Spawn yourself some unfertilized bird eggs and some bread
- Set food handling to at least 1
- Attempt to craft toad in the hole
- Observe that it is possible without any cooking implements or heat, despite saying "A cooked egg" and "toast" in the description

### Expected behavior

Cooking food would require something to cook on, and with

### Screenshots

![image](https://user-images.githubusercontent.com/5215014/147742243-937fda9b-4d56-42e3-bfe9-b528eba34ef4.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 3c154af [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA]
]

### Additional context

https://www.tasteofhome.com/recipes/toad-in-the-hole/

**Comment by ZhilkinSerg** [comment]
See #53309 and #53334
