### ISSUE TITLE
Let player replace vehicle components

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#53898]
### Is your feature request related to a problem? Please describe.

I quite like the changes introduced by #52744, but the the need to replace components wholesale introduces a rather annoying problem: in order to replace "base level" components like frames, you have to take off everything on that tile, replace the component, and put it all back on again. Even the quicker swap jobs can get a bit tedious now that you have to do them regularly.

### Solution you would like.

Introduce the ability to replace a component. This would consume the same amount of of time and materials and as removing and putting back all the relevant pieces, but could be done with a single button press.

### Additional context

![image](https://user-images.githubusercontent.com/5107449/147784928-4f3900d0-2dac-406d-b13f-d64a832c563d.png)
I am not thrilled about having to take all of these parts off individually to replace that frame

**Comment by Alex-Folts** [comment]
If you don't mind i'll try to describe my vision of how it can be done: we need to introduce "task batch" vehicle part, it is virtual part which can be added into any vehicle tile, in itself it contain list of operations which player or NPC can execute, all operations are applicable to the vehicle tile into which "task batch" installed, operations are:
- remove specified part
- install part from specified item(you can select particular item from list or use any available by default, it must show you which part it will gonna use so you will decide agreed on default or select from list)
- repair specified part
- mend specified defect
- siphon liquid from a tank
- refill tank
- unload cargo container or ammo from turret
- reload turret

Operations executed in strict order, player just select "work on task batch" and character will perform one by one operations specified in task's batch list, once operation from list completed it will removed from batch list and next starts(basically batch list is a stack, you always work on first item in a stack, if stack empty - task done and task item get deleted from vehicle tile). You can interrupt working on a task and resume it later selecting "working on task batch".

So "replace part" button will just generate task based on installed parts in the tile. I.e. for your screenshot it will create task batch with list like:

1. remove "heavy duty board"
2. remove "military composite heavy plating"
3. remove "32" armored wheel"
4. remove "heavy wheel hub assembly"
5. remove "heavy duty frame"
6. install "heavy duty frame"(using item selected by player from list when player pressed "replace part" button)
7. install "heavy wheel hub assembly"
8. install "32" armored wheel"
9. install "military composite heavy plating"
10. install "heavy duty board"

Additionally player can create tasks manually and add/remove/reorder operations in batch list and specify which item to use for install operation.
Also should be possible to create few task batches for different vehicle tiles.

So in the end, collection of task batches alone within empty vehicle will be essentially a blueprint of the vehicle, executing them one by one you will be able to assemble whole vehicle from scratch. Eventually this will allow for player to brainless assembling vehicles of any complexity just from blueprint(obtained by gameplay means or shared by other players), which would allow us to make vehicle building system lot more complex.

Hm, this comment alone worth a separate sugestion...

**Comment by PatrikLundell** [comment]
It probably can't be done safely before #44311 has been fixed.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
