### ISSUE TITLE
Error when setting up a camp

### ISSUE THREAD

**Issue by 321nick** [CleverRaven/Cataclysm-DDA#53890]
### Describe the bug

Establishing a camp causes an error to occur

### Steps to reproduce

1. Spawn in an evac shelter, with a NPC
2. Recruit NPC
3. Set up a camp in the evac shelter (also occurs with other camp types)

### Expected behavior

No error when setting up a camp. 

### Screenshots

![image](https://user-images.githubusercontent.com/19196462/147759791-a7393d6b-3227-4ba3-9377-2f6791174abb.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 5d4daeb [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

### Additional context

Also happens with some quest progression, like when you do the first couple of quests for the Hub 01 and the free merchants spawn, i got the error then aswell. i think it relates too overmap changes. 

debug.log:

https://gist.github.com/761b18a658a42994b41a253924f714c9

**Comment by Night-Pryanik** [comment]
Can't confirm on latest experimental as of 27 October 2024.
