### ISSUE TITLE
Canvas bag with items in it crashed my game when dismantled and per

### ISSUE THREAD

**Issue by UnsaneHawk** [CleverRaven/Cataclysm-DDA#53896]
### Describe the bug

During my current game I accidentally dismantled a canvas bag that had stuff in it and instantly crashed my game. The bigger problem is that it crashes immediately whenever I load my save file with the same error. Is there anything I can do to recover my save?

### Steps to reproduce

1. Put stuff in canvas bag
2. Dismantle it

### Expected behavior

Unloads items before dismantle or just crashes once and doesn't crash every load due to being prior to the dismantle.

### Screenshots

![image](https://user-images.githubusercontent.com/96886683/147780696-96d3aae7-4511-4ab1-bf2b-48c99ac42b28.png)

![image](https://user-images.githubusercontent.com/96886683/147780709-9db1ab38-5034-4a26-9518-9185a5ab07c0.png)

![image](https://user-images.githubusercontent.com/96886683/147780735-30cfad40-c67c-4f4c-9225-3a0ecfd0d3ab.png)

![image](https://user-images.githubusercontent.com/96886683/147780756-1f4846dd-efa9-430f-8eb0-943347426a1c.png)

### Versions and configuration

Windows 10
UndeadPeople (NEW)
0.F-2 (tiles)

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7794251/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7794252/debug.log)
[manual_backup.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7794283/manual_backup.zip)

**Comment by LeahLuong** [comment]
It looks like your game crashed during an autosave & while your char was performing the action. You need to edit your char file to set your char's action to "null"; something similar happened to me in #52775 & PatrikLundell was able to help me. I believe the 1st referenced thread in that issue gives the details if you'd like to make the attempt yourself. You should prob back up your game file before trying.

**Comment by UnsaneHawk** [comment]
> It looks like your game crashed during an autosave & while your char was performing the action. You need to edit your char file to set your char's action to "null"; something similar happened to me in #52775 & PatrikLundell was able to help me. I believe the 1st referenced thread in that issue gives the details if you'd like to make the attempt yourself. You should prob back up your game file before trying.

Tbh I'm not sure where to look for the action change

**Comment by GoLoT** [comment]
> Tbh I'm not sure where to look for the action change. Any idea where I should look?

Try opening save/WorldName/#randomcharacters.sav with a text editor and do a search for `"ACT_DISASSEMBLE"` and replace it with "`ACT_NULL`". Backup the file (or the whole folder just in case) first.

Linking related issue #53539 as they seem to share the same root cause (non-empty container being destroyed by the current activity).

**Comment by UnsaneHawk** [comment]
> 

Hey GoLoT I know its been a few days, but I still have been unable to find where my character file is located. Would it be under template instead (as they are a template)? The template file does seem like its being used, but I have been unable to locate my current action when searching it.

**Comment by UnsaneHawk** [comment]
[Emilia Ashton.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7800102/Emilia.Ashton.zip)

**Comment by GoLoT** [comment]
It's under `saves/WorldName/#randomcharacters.sav`. For your character it's `save/Lithopolis/#RW1pbGlhIEFzaHRvbg==.sav`. That file is just a text file you can edit to change `"ACT_REPAIR_ITEM"` to `"ACT_NULL"` but you can just unzip the file I attached and replace it instead.

**Comment by UnsaneHawk** [comment]
Thanks man, you're the best!
