### ISSUE TITLE
Sidebar Custom Catagory Fixed Height

### ISSUE THREAD

**Issue by ilovehans10** [CleverRaven/Cataclysm-DDA#53899]
### Describe the bug

The sidebar has a custom layout that I have started using with the removal of the self aware trait and at the current moment it appears that doesn't have a variable height. This seems like an error but if I am missing something or have misunderstood the way layout widgets work please let me know. I have tried to read the DOC files on sidebar but the section on root layouts is sparse.

### Steps to reproduce

1. Edit root layout either wide or narrow of data/json/ui/sidebar.json to include widgets that take up less than 8 lines
2. Start the game and load into a character 
3. Enable the sidebar to include custom
4. View the spacing of the sidebar

### Expected behavior

I would expect for the sidebar to compress into the blank space.

### Screenshots

![image](https://user-images.githubusercontent.com/20823837/147779055-1e1bfcf9-e4e5-4ae9-aacd-382d68548f68.png)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.F-4762-gef54539895 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap],
    Magiclysm [magiclysm],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    C.R.I.T Expansion Mod [crt_expansion],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    Extra Mutated Scenarios [extra_mut_scens],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
