### ISSUE TITLE
Use spawn_data to have some turrets start with less ammo

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#53897]
### Is your feature request related to a problem? Please describe.

Turret ammo spawns are an unfortunate balance issue: turrets are too easy a loot pinata for many players.

### Solution you would like.

Ideally we should continue to reduce the use of turrets overall until eventually most of them are phased out except in particular special cases. However, a more short-term solution and one that we'll need anyway is to check where a turret is spawning and manually review `spawn_data` to ensure that the ammunition levels are appropriate to spawn location.

- Turrets that are spawning in places where no conflict occurred should have lots of ammo
- Turrets spawning in active combat areas should have very little ammo, having spent days burning it on zombies that just keep getting back up.
- Turrets spawning in ambiguous locations where there may have been combat, it's unsure, should have a very random amount of ammo.

Spawn_data is applied at the mapgen level, for example:
```
        {
          "monster": "mon_crows_m240",
          "x": 10,
          "y": 1,
          "spawn_data": { "ammo": [ { "ammo_id": "762_51", "qty": [ 1200, 1600 ] } ] }
        }
```

### Describe alternatives you have considered.

Having far fewer turrets and replacing most of them with lore-appropriate enemies fulfilling the same function.

### Additional context

Ammunition still should be fairly plentiful, but it should mostly be a thing you are looting, not blowing up AI turrets for. The current mechanism leads to a very counterintuitive way to get a lot of just a few specific ammo types.

**Comment by JonathanLochridge** [comment]
It seems like the combat areas decreasing turret ammo would be something fairly easy to do for a partial fix. No idea what it would take for the random amounts of other turrets.
If anyone has some exampled for that which qualify I think I could probably reduce their ammo numbers. I could also do some JSON checking to find all the places that have turrets and evaluate them based on how much of a combat area they are. But that seems a bit time consuming. So it will probably be sometime for later at least if I did it. there might be some obvious examples that could be tweaked.

**Comment by GuardianDll** [comment]
write it on discord already, so copypaste it here
surprisingly, at this moment there is not so much places where turrets can have less than full ammo - its just the entrance of the silo, few places in microlabs, and some turrets in the necropolis. any another turrets are hided in place where no monsters or npcs occur
for me it feels this issue is a bit outdated for now

**Comment by I-am-Erk** [comment]
That just means that those turrets need this adjustment.

The ones in labs may also suit having their total ammo reduced since they're not necessarily complete milspec
