### ISSUE TITLE
Crashed while playing on Android 

### ISSUE THREAD

**Issue by RafaelLVX** [CleverRaven/Cataclysm-DDA#53895]
### Describe the bug

I was wearing a hiking backpack, then game asked if I should put down my pike, which is weird because normally armor doesn't mess with what I'm wielding, I tried ESCing out and then it crashed. It was unexpected, so I wasn't paying much attention though.

### Steps to reproduce

I tried now redoing the steps described on "describe the bug" and sure enough, game crashed again. I'm attaching a link to a video. https://photos.app.goo.gl/TPwiDvbx9pHhW8EH7

Going over the process a third time, I dropped the pike, then wore the hiking backpack, then picked pike back up, no problem. 

### Expected behavior

Not crashing. 

### Screenshots

https://photos.app.goo.gl/TPwiDvbx9pHhW8EH7

### Versions and configuration

Android 8.0 on a Huawei Mediapad M5. 

### Additional context

Files: https://1drv.ms/u/s!AlBF-Ft-T2VN4K8cmi-mSDbIGduxQA

**Comment by BrettDong** [comment]
Could you attach the save file (entire world folder)? It's difficult to reproduce and diagnose the bug without the save file.

**Comment by TealcOneill** [comment]
/Invalid I tried to replicate this with wearing and wielding a pike various ways on both android and pc. Never got the prompt and never crashed.
OS: Android
OS Version: Manufacturer: motorola; Model: moto g stylus 5G; Release: 12; Incremental: 216ba-695ce8;
Game Version: 0.G [64-bit]
Graphics Version: Tiles
Game Language: System language []
Mods loaded: [
  Dark Days Ahead [dda],
  Disable NPC Needs [no_npc_food],
  Portal Storms Ignore NPCs [personal_portal_storms],
  No Fungal Growth [no_fungal_growth],
  Bionic Professions [package_bionic_professions]
]
- OS: Windows
    - OS Version: 10.0.19045.4412 (22H2)
- Game Version: cdda-experimental-2024-06-10-0401 62b7550 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by Night-Pryanik** [comment]
Closing until reconfirmed.
