### ISSUE TITLE
Metal fileset can't be crafted without a metal fileset

### ISSUE THREAD

**Issue by GoLoT** [CleverRaven/Cataclysm-DDA#53903]
### Describe the bug

After the changes in #53883 there is no way to craft a metal fileset without a metal fileset because of a circular dependency between the swage and die set and the metal fileset. The only way around it is looting a swage and die set to craft a fileset or looting a fileset to craft a swage and die set.

The PR suggests that a new tool could be used as a makeshift file for some recipes. That could work as a fix/workaround to at least be able to craft the swage and die set.

### Steps to reproduce

1. Create a new character and set all skills to 10.
2. Open the crafting menu and find the swage and die set. See that it requires a metal fileset to craft.
3. Check the metal fileset and see that it requires a swage and die set to craft.

### Expected behavior

Have a way to craft either without each depending on the other.

### Versions and configuration

Game version: 75a01ca

**Comment by LeahLuong** [comment]
Aaaahhh, the ol' swage & die & fileset paradox! How did we humans ever get out of the Stone Age??

**Comment by kevingranade** [comment]
Yea my bad, I didn't trace through the dependencies.  As I outlined in that PR, you need:
Metal, Hammer, anvil, forge/fuel, chisel. tongs, (quenching medium, but we don't handle that).
In other words, yes remove the swage.
