### ISSUE TITLE
Activating tanning hide creates item with 0 amount

### ISSUE THREAD

**Issue by Light-Wave** [CleverRaven/Cataclysm-DDA#53901]
### Describe the bug

Once a tanning_hide is done tanning and you try to unfold it, you get an item with an amount of 0. The item is buggy, and you get no leather from disassembling it.

### Steps to reproduce

1. Spawn or craft a tanning hide
2. Wait until it is done (2 days?)
3. Activate the item
4. Try to interact with the item. It says it has Amount 0.
5. Dropping it does not show the green + in the interface when you are about to dropp it, but it can be done
6. Butcher it and see you get 0 leather from it.

### Expected behavior

Activating it should make the resulting item have an amount of 0.
Alternatively, activating it could use up all available items ready to be transformed and give that many of finished items, see #51417

### Screenshots

![Capture](https://user-images.githubusercontent.com/66904273/147787800-ed4ffdb8-1829-466a-a704-9863c71ae252.PNG)

### Versions and configuration

- Windows 10
- Build 2021-12-27-0903

**Comment by LeahLuong** [comment]
Cursory search shows this to be a dupe of #53094 & that it's being worked on in #53866. Pretty sure you should close this issue before more people see it.

**Comment by Light-Wave** [comment]
> Cursory search shows this to be a dupe of #53094 & that it's being worked on in #53866. Pretty sure you should close this issue before more people see it.

That is correct. #53866 fixes this.
