### ISSUE TITLE
UI for Aftershock Exoskeletons

### ISSUE THREAD

**Issue by Drew4484** [CleverRaven/Cataclysm-DDA#53900]
### Is your feature request related to a problem? Please describe.

Aftershock exoskeletons are modular, allowing the player to change out defensive plating and various modules. Unfortunately this is difficult to represent in the current inventory UI.

### Solution you would like.

Something along the lines of this as a pop-up menu, with the option to install/remove plates/modules.

This is a suit covering torso, arms, legs. There is an optional helmet, and a rear 'backpack' mount for a power supply or large storage options. Currently, installing plating or modules into a location requires opening the inventory, selecting the suit/power supply/helmet, and inserting the items. There is no easy way to see what items are in which locations other than the named plating. Additionally, the power supply modules are installed to the suit, then can have additional armor plating added. 

An ideal solution would be an activation menu option, presenting the choice to turn the suit on/off, or manage the suit. Managing the suit could look something like the attached chart, showing the loaded item name/condition/size/weight/remaining storage (for things like the ammo pouches). 
Selecting a slot on the left column, prompts removing if an item is present or installing a new item if the slot is empty.

![image](https://user-images.githubusercontent.com/57647637/147787190-8b28381d-026e-450f-bd95-67be18f4fd50.png)

### Describe alternatives you have considered.

Five page user manual.

**Comment by John-Candlebury** [comment]
Posted this in discord but I’ll also share it here:

The exo suits are pieces of armor with several holster type pockets that can only hold a single item each. These pockets are used to either mount armor into the suit or place other gadgets.

What is needed is some sort of holster manager menu, probably accesible as an item iuse. That shows what is currently contained in each pocket. And let’s you remove and place items into each individual pocket.

Ideally the exosuit pockets would not be fillable outside of this menu.

**Comment by bombasticSlacks** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/issues/53806 would probably be good enough for this?

**Comment by Drew4484** [comment]
> #53806 would probably be good enough for this?

I like that layout, it doesn't include the pocket descriptions (which are still very new) but otherwise that looks good to me. @John-Candlebury thoughts?

**Comment by John-Candlebury** [comment]
The menu should also be accessible through activating  the suits. And only show you the pockets in the suit

But it seems to do everything otherwise

**Comment by dseguin** [comment]
Would something like this work for you? (WIP exosuit menu, '`a`'ctivated with an iuse function)

https://user-images.githubusercontent.com/12537966/147866214-16f11d8b-b638-4aff-b354-e95f11a1924b.mp4

**Comment by John-Candlebury** [comment]
Yes that is excellent!

**Comment by dseguin** [comment]
Great! This just needs a little more work before I submit the PR. It will require some minor changes to the JSON definitions for exoskeleton pockets, but I will suggest the required changes to #53254 once the menu PR is merged.

**Comment by Drew4484** [comment]
> Great! This just needs a little more work before I submit the PR. It will require some minor changes to the JSON definitions for exoskeleton pockets, but I will suggest the required changes to #53254 once the menu PR is merged.

Looks terrific!
