### ISSUE TITLE
After migrating save Light level is stuck on "very dark"

### ISSUE THREAD

**Issue by kholat** [CleverRaven/Cataclysm-DDA#53902]
### Describe the bug

No matter where my char goes/does, the light level is "very dark" disallowing reading and such even in cases where the actual tile the character is on is "bright" when using the e'X'amine key.
save: https://www.dropbox.com/s/rlya6234ij1iswq/Colt.zip?dl=0

### Steps to reproduce

1. load up my save
2. see that the character is in "very dark" tile even if he holds a lit lantern, is outside in daytime, or similar.

### Expected behavior

already described

### Versions and configuration

- OS win 10
- version d6fecb3 (tiles)
- build 2021-12-30-1057
- mods:   "dda",
  "no_npc_food",
  "blazeindustries",
  "magiclysm",
  "No_Rail_Stations",
  "no_hope"

**Comment by ZhilkinSerg** [comment]
Which version are you migrating from?

**Comment by ZhilkinSerg** [comment]
You are in a basement in attached save and it is 9 pm - it should be pretty dark anywhere w/o lights. If you change time to 9 am - it is not dark.

**Comment by LeahLuong** [comment]
Heh, not only do we have to manage hallucinations in-game, they can affect us IRL!

**Comment by kholat** [comment]
> You are in a basement in attached save and it is 9 pm - it should be pretty dark anywhere w/o lights. If you change time to 9 am - it is not dark.

But if you turn on the flashlight for instance, its still "very dark" and its still not possible to craft or read.

**Comment by Zireael07** [comment]
@kholat IIRC a flashlight was never sufficient to craft or read.

**Comment by Maleclypse** [comment]
Seems like this can be closed.

**Comment by kholat** [comment]
Well, I can post a video or something if someone is interested, the issue does exist and is not fixed when migrating the save. You can close it but its not fixed is all i am saying.

**Comment by hexagonrecursion** [comment]
> kholat IIRC a flashlight was never sufficient to craft or read.

Your memory is incorrect. My character is able to read and craft by the light of a flashlight (id: flashlight) at 23:00 in a basement just fine.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: eacb7d9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by hexagonrecursion** [comment]
In your save you have a "darkness" effect with duration 4 and the PERMANENT flag affecting your character. If I remove it, you can craft and read just fine.

**Comment by kholat** [comment]
> In your save you have a "darkness" effect with duration 4 and the PERMANENT flag affecting your character. If I remove it, you can craft and read just fine.

huh?! wow thanks, how could that happen? Interesting, Im not using any weird mods that would do such a thing.

**Comment by Maleclypse** [comment]
It probably is an artifact you've picked up, yes.
