### ISSUE TITLE
Activity or zone for bandaging and disinfecting

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#53910]
### Is your feature request related to a problem? Please describe.

After getting a lot of injuries on different limbs, it can be tedious to apply bandages and/or disinfectants to all of them.

### Solution you would like.

Like other quality-of-life automations or zone activities such as auto-eat/drink, it would be nice to have a way to "bandage and disinfect everything" with a few keystrokes.

### Describe alternatives you have considered.

Even better if NPCs could participate as well, so everyone can patch each other up after battle.

**Comment by ElfLeaderMike** [comment]
Huge fan of this, I love the idea of automatically spending medical supplies for injuries with obvious treatment options. Sitting there and slowly selecting every limb for bandaging (and disinfection sometimes) after a blood fight gets old pretty fast.

**Comment by nexusmrsep** [comment]
In fact it would be beneficial, even from the perspective of future wound system, to display the `body window` (the UI that popups when u use bandage/disinfectant) as a standalone UI "widget" under some key binding. Not only it could be then used to display detailed info on medical condition of limbs (in future: wounds), but then it could be easily enhanced with local keybindings for "bandage all" and "disinfect all", etc.

**Comment by esarbe** [comment]
Maybe something akin to the 'hospital' zone of dwarf fortress with the ability to
- assign dedicated health care workers / doctors
- assign items to hospital and spawn missions to restock
- resting places for injured party members

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
