### ISSUE TITLE
Crash on quit.

### ISSUE THREAD

**Issue by ahmedcharles** [CleverRaven/Cataclysm-DDA#53914]
### Describe the bug

Crash on save and quit to main menu.

### Steps to reproduce

1. Hit ESC.
2. Select Save and Quit.

### Expected behavior

Not crash.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 75a01ca [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Stats Through Skills [StatsThroughSkills],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7795153/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7795154/debug.log)

**Comment by GoLoT** [comment]
Can't reproduce using the same version. Does it happen always or is it only with a specific save file? If it's the latter, can you share it?

**Comment by ahmedcharles** [comment]
Unfortunately, I reset the world without backing up the save. Sorry, I'm a software engineer so I should've been more careful.

**Comment by BrettDong** [comment]
Do you have a `.core` core dump file?

**Comment by ahmedcharles** [comment]
[core.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7796682/core.zip)

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-8727. No confirmation in half a year.
