### ISSUE TITLE
[Magiclysm] upgrading Technomancer Toolar to Technomancer Mana-Toolbar disables martial art

### ISSUE THREAD

**Issue by Lord-Helmchen** [CleverRaven/Cataclysm-DDA#53923]
### Describe the bug

Technomancer Toolbar can be used in Fior Di Battaglia, but the mana-toolbar cannot. Is this another oversight or does the style not translate well after the electronic is attached ?

### Steps to reproduce

check recipes

### Expected behavior

Preferably both qualify for FDB :)

### Versions and configuration

version 524a7db
build 2021-12-31-0620

**Comment by Maleclypse** [comment]
I think this could be fixed by adding a weapon category to both items for Fior?
