### ISSUE TITLE
Brutal Strike Can Cause Unboard Error

### ISSUE THREAD

**Issue by LeahLuong** [CleverRaven/Cataclysm-DDA#53935]
### Describe the bug

Knocking a char out of a vehicle space using Brutal Strike throws the error pasted below when you step into the unoccupied space. This happened to me when I knocked a bandit out of a side door & they were subsequently bitten to death by a chihuahua. Wish I could claim it was my guard dog but it was just some random feral.

Nothing game-breaking but I thought I should point it out. May also occur w/ super punches or other things that forcibly eject entities from vehicles.

### Steps to reproduce

1. Stand 1 space in from side of vehicle.
2. Strike BRUTALLY!
3. ???
4. PROFIT!!!

### Expected behavior

I expected that brutal strike level would increase, because all other skills can increase in level.

### Versions and configuration

Android 0.F-3 Tiles English vanilla

### Additional context

 DEBUG    : map::board_vehicle: passenger (<null>) is already there

 FUNCTION : void map::board_vehicle(const tripoint &, Character *)
 FILE     : /var/lib/jenkins/workspace/Cataclysm-Android/android/app/jni/src/../../../../src/map.cpp
 LINE     : 1010
 VERSION  : 0.F-3

**Comment by hexagonrecursion** [comment]
Confirmed

 DEBUG    : map::board_vehicle: passenger (Audie Perdue) is already there

 FUNCTION : void map::board_vehicle(const tripoint&, Character*)
 FILE     : src/map.cpp
 LINE     : 1038
 VERSION  : eacb7d9

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: eacb7d9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by LeahLuong** [comment]
Confirmation tag, please!
