### ISSUE TITLE
Add Accessories tab in + screen

### ISSUE THREAD

**Issue by VoleurVolant** [CleverRaven/Cataclysm-DDA#53936]
### Is your feature request related to a problem? Please describe.

When viewing worn items, the All tab is always a little bit crowded. Many items are worn on a body part, and can be viewed in that body part's tab, but items which are worn on no body part (primarily jewelry... and BADGES, I can't believe I forgot badges until I scrolled through and ran across my badges) can only be viewed in the All tab, mixed in with everything else. This is, obviously, a very minor problem, if it can really be classified as such.

### Solution you would like.

I would like to have a tab for viewing only items that are worn on no body part. Accessories seems like a good name for it. I'm not familiar with how the + screen works myself, so I may be underestimating how much of a hassle this would be; if it's not a simple filter to implement, it's probably not worth anyone's time.

### Describe alternatives you have considered.

Continue living as I always have. It's not game-changing, just a few extra keypresses and a little more thought when looking over my stolen treasures.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
