### ISSUE TITLE
Tutorial has lack of dummies where they should be

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#53941]
### Describe the bug

Tutorial mode has no dummies, when tip says they must be there

### Steps to reproduce

- Open tutorial
- See there is no dummies

### Expected behavior

Having dummies where they need to be

### Screenshots

![image](https://user-images.githubusercontent.com/67688115/147855458-b3f57f22-1c6f-4eca-97b5-2f6be225d832.png)
![image](https://user-images.githubusercontent.com/67688115/147855509-3b731d1b-73a4-44c1-8984-8e0d9bc0c570.png)
![image](https://user-images.githubusercontent.com/67688115/147855499-fd574cc9-7f0c-4505-b27c-fe3e14f8f273.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: d6fecb3 [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by Night-Pryanik** [comment]
This looks like an issue with tileset rather than with dummies themselves.
![изображение](https://user-images.githubusercontent.com/11132525/147857425-5d238342-db98-4719-93a3-185cf0dbe488.png)

**Comment by GuardianDll** [comment]
nope, they are definetly not here
![image](https://user-images.githubusercontent.com/67688115/147857573-866670e0-60f5-419d-800c-bdcfb548ddba.png)
i have no clue why it can happen

**Comment by Night-Pryanik** [comment]
Is this your second time starting the tutorial? Could you please delete the tutorial world and create a new one?

**Comment by GuardianDll** [comment]
Second screen is right after reset

**Comment by Night-Pryanik** [comment]
I really don't know why is this happening to you.
![изображение](https://user-images.githubusercontent.com/11132525/147857918-23ab4aad-acfd-445f-91c5-12356fb2cc39.png)

**Comment by hexagonrecursion** [comment]
I can not reproduce the bug either. The dummies only fail to spawn if a world named "TUTORIAL" already exists.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: eacb7d9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by GuardianDll** [comment]
Cant reproduce the bug from now
Looks like some odd glitch
