### ISSUE TITLE
Refugee Center Back Area Guard Being Shocked

### ISSUE THREAD

**Issue by JantDarvus** [CleverRaven/Cataclysm-DDA#53952]
### Describe the bug

Currently, the guard to the zombie-filled back area of the refugee centre stands right next to the wall. Changes to electricity from zombies means he now tends to get shocked whilst standing there, triggering him to barrel in and dragging other NPCs in with him into the carnage. In my case, I ended up with several dead NPCs (Uyen Tran, the Teamster and a Guard) as a result of this.

### Steps to reproduce

Visit the refugee centre, stand in the back area and wait for an electrical zombie to wander towards that wall.

### Expected behavior

Either the electricity shouldn't be passing through the wall or the guard should not be standing against the wall within shocking range.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 9da956a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Zireael07** [comment]
Why close? This seems a valid complaint...

**Comment by JantDarvus** [comment]
Discord drama. If anyone wants to bring this issue back up or deal with it, they can, but I don't.

**Comment by NetSysFire** [comment]
Regardless of discord drama, this is valid and probably caused by #53135

**Comment by GoLoT** [comment]
Since electricity spreading through walls was balanced around having insulation from gear and that PR isn't going to happen, I can probably change it so electricity still builds up in walls and shocks if you get close but limit its spread so it builds in place. That should help in this specific case, hopefully.
