### ISSUE TITLE
Magiclysm: ring of intelligence +1 (and other rings I've found) increase encumbrance of single hand by 50

### ISSUE THREAD

**Issue by mkrutov** [CleverRaven/Cataclysm-DDA#53959]
### Describe the bug

n/a

### Steps to reproduce

1. spawn ring of intelligence (or any other from magiclysm)
2. put it on
3. observe encumbrance in +

### Expected behavior

I don't think 50 is a correct value of encumbrance for the ring.

### Screenshots

![Screenshot_20220102_040546](https://user-images.githubusercontent.com/48674477/147864949-be9c67a6-d628-4d58-97d1-1395716b33ee.png)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 75a01ca [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    DinoMod [DinoMod],
    Disable NPC Needs [no_npc_food],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by casswedson** [comment]
As of 
- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Garuda; Description: Garuda Linux; Release: Soaring; Codename: White-tailed-eagle; 
- Game Version: 68cfef5
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]
]
![rings](https://user-images.githubusercontent.com/58050969/147865156-c2f70636-d609-485e-81b0-9cd9bf5c382c.png)

In this save I can wear any rings in any order, and they do not add any extra encumbrance
[rings.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7798498/rings.zip)

Also: https://discord.com/channels/598523535169945603/642349261320880128/927037523673358336 -> Webbed fingers did that
