### ISSUE TITLE
Skinning Kevlar Z's Gives Clean Sheets

### ISSUE THREAD

**Issue by LeahLuong** [CleverRaven/Cataclysm-DDA#53951]
### Describe the bug

This was remarked upon in #29142. #29149 allowed adding the "filthy" flag through JSON for item drops & perhaps this was never retroactively applied to the originating issue. #42486 presumably looked @ Kevlar Z butchery drops & added tainted leather as a possibility but I've only gotten clean Kevlar sheets from them so far. It may be that #50463 has overwritten what you get from skinning Kevlar Z's. I'm not sure who dropped the ball here but whomever it is should prob be notified & asked to fix this. If that's no longer possible, this is prob an easy JSON edit & a "Good 1st Issue" candidate.

### Steps to reproduce

1. Slay Kevlar Z.
2. RP Buffalo Bill.
3. ???
4. PROFIT!!!

### Expected behavior

I expected that Kevlar sheet level would increase, because all other skills can increase in level.

### Versions and configuration

Android 0.F-3 Tiles English vanilla

**Comment by Terrorforge** [comment]
I don't think kevlar sheets _can_ be filthy, is the thing. Part of the reason the tailoring materials are so messy right now (#53059) is that the various sheets are defined as ammo, which can't be filthy, and #50207 tried to work around that.

**Comment by LeahLuong** [comment]
@Terrorforge I think you're wrong about this. I seem to have a memory from as recently as 0.F-2 when I was washing Kevlar sheets I'd gotten from cutting up filthy motorcycle gear & combat boots. I remember thinking how little detergent it was taking; like, < 1 detergent/100 sheets. That may be a separate issue. I'll be sure to check for filthy sheets the next time I come across those items.

**Comment by Terrorforge** [comment]
No, you're right. I've definitely had filthy kevlar sheets, now that I think about it. Then I'm mistaken and this is probably an easier fix than I thought.
