### ISSUE TITLE
Getting errors about 'ENCH_TRAIT_MSKIN' with Mycogenesis mutation

### ISSUE THREAD

**Issue by Stadler76** [CleverRaven/Cataclysm-DDA#53956]
### Describe the bug

Upon obtaining the Mycogenesis-mutation I'm getting a lot of errors about `invalid enchantment id "ENCH_TRAIT_MSKIN"` like this:
```
 DEBUG    : Excessive error repetition detected.  Please file a bug report at https://github.com/CleverRaven/Cataclysm-DDA/issues
            invalid enchantment id "ENCH_TRAIT_MSKIN"

 FUNCTION : const T& generic_factory<T>::obj(const string_id<T>&) const [with T = enchantment]
 FILE     : src/generic_factory.h
 LINE     : 445
 VERSION  : 68cfef5
```

[This changeset](https://github.com/CleverRaven/Cataclysm-DDA/commit/b5dc3c4b38591017f1f8492f258effbbdd378e1a#diff-d7872f7c7460166e86f67025a4c318b207772f54ffcd3cb0aadc220df8e4cf96R1955) is adding it to `data/json/mutations/mutations.json` but it's nowhere defined in the code what the game should do with that enchantment.

### Steps to reproduce

1. Gain the Mycus mutation
2. Gain the Mycogenesis mutation

### Expected behavior

Game doesn't error upon achieving the Mycogenesis mutation.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 68cfef5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Stadler76** [comment]
@Ramza13: Could you look into this please?
A quick fix could be replacing
```json
"enchantments": [ "ENCH_TRAIT_MSKIN" ]
```
with
```json
"enchantments": [ { "condition": "ALWAYS", "values": [ { "value": "SPEED", "multiply": -0.2 } ] } ]
```
But I guess, you just forgot to implement `ENCH_TRAIT_MSKIN`?

**Comment by Ramza13** [comment]
Sigh, yea it looks like a bad merge.  I added inline EOCS in between working on these and it looks like made a mistake updaing that PR.  Good catch and I'll submit a fix when I get some time.
