### ISSUE TITLE
Remove redundant blueprint resource specifications

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#53965]
### Is your feature request related to a problem? Please describe.

When welding rods were introduced, a number of basecamp blueprints refused to cooperate, and their explicitly stated requirements were replaced with the usage of the existing functionality to let the game figure out the requirements based on what was constructed. During the processing of this, it was said that it would be a bad idea to convert all the recipes that state resource usage without having the "check_blueprint_needs" set to false to use auto calculation, because the resource calculation takes time and is performed during the loading of the save.
However, after mulling over the issue for a fair while, I'm not convinced there would be any additional load time if the resource specifications were removed, because it seems to me the issues encountered with blueprints were caused by a clash between the explicitly stated resource usage and the calculated one, which would imply the resources were actually calculated even with explicit resource declarations. If that is correct, removing explicit resource calculations that are not accompanied by a false "check_blueprint_needs" flag would reduce loading time marginally because there's less text to parse and there is no need for a comparison between the resources stated and the ones calculated.

In addition to that, it would reduce the number of things that trip up contributors when changing functionality.

Thus, I propose that all such recipes that do not "check_blueprint_needs" set to false should be stripped of their redundant explicit resource declarations.

### Solution you would like.

Strip all blueprints without "check_blueprint_needs" set to false of their resource declarations. This would be done over a fair number of "Pull Requests" (github gobbledigook for "please accept these changes").

### Describe alternatives you have considered.

IF there is a need/desire to cut down on recipe resource calculation is should be done by the introduction of a flag that states that the resources are pre-calculated, and and a tool that's capable of reading all such recipes and update them according to the current game definitions. The tool would be used pre release and by people who want to have recipes updated after changing things that may affect them. However, this would complicate things quite a bit, so a decision to go that route should only be taken after measuring how much time you'd save on game loading when pre calculating the resources compared to when performing them every time.

### Additional context

I may have drawn the wrong conclusions (e.g. by misunderstanding what "check_blueprint_needs" does). If so, I'd like to be corrected.

**Comment by NetSysFire** [comment]
Yes, it would be absolutely awesome to have this. It would save contributors a fair bit of work.

A relatively minor issue with the current python script checking PRs for clashes in blueprint needs is that its output is not even linted, so even if contributors apply the changes from the tool, the linter will potentially complain about overly long lines.
