### ISSUE TITLE
Improve soundpack validation

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#53966]
### Is your feature request related to a problem? Please describe.

If a soundpack references a nonexistent sound file (e.g. due to a typo like what happened in https://github.com/Fris0uman/CDDA-Soundpacks/pull/24), the game does not notice the mistake until it tries to play the sound.

### Solution you would like.

The game should validate the sound file names when loading the sound pack and produce debug mesages

### Describe alternatives you have considered.

Each soundpack author reinventing the wheal

https://github.com/Fris0uman/CDDA-Soundpacks/pull/24#issuecomment-1003716409
> Do you think it would be possible to have a script to detect those kind of errors as part of a github action to check PRs?

### Additional context

See also https://github.com/Fris0uman/CDDA-Soundpacks/issues/22 and https://github.com/CleverRaven/Cataclysm-DDA/pull/53709

**Comment by ZhilkinSerg** [comment]
Soundpack should be validated only once by its author/maintainer on soundpack release. We can keep verification script in the repo in tools folder.

**Comment by hexagonrecursion** [comment]
You validate the mods you load every time a game is loaded

**Comment by ZhilkinSerg** [comment]
Yep, because data consistency check is mandatory to ensure successful game loading. Soundpack file validation is not crucial at al and if we will implement it in-game it will only increase loading times for a very little gain.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
