### ISSUE TITLE
Reloading ammo into gun makes the gun bigger

### ISSUE THREAD

**Issue by Hirmuolio** [CleverRaven/Cataclysm-DDA#53974]
### Describe the bug

Reloading ammo into gun makes the gun bigger.

### Steps to reproduce

1. Spawn 10mm/.40 revolver.
2. Compare its volume when empty vs when full

### Expected behavior

Ammo inside the gun shouldn't make the gun bigger.

### Screenshots

![gun](https://user-images.githubusercontent.com/22011552/147885732-add27b71-3d58-44d1-9b03-d934689c78c5.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: b49f934 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

### Additional context

Just add `"rigid": true` into the magazine pocket of the guns.

Maybe `"rigid": true` should be the default for magazine pockets. Any magazine pocket where the ammo is stored "outside" could have `"rigid": false` in its definition.

**Comment by LeahLuong** [comment]
I think there's a Glock that grows in length when you load a large capacity clip into it. This makes sense as the clip protrudes far past the bottom of the pistol's grip IRL. Are you certain something like that isn't the case here??

**Comment by SirPendrak** [comment]
Using magazine well instead of rigidity might be safer solution.

**Comment by Hirmuolio** [comment]
This is about individual cartridges being put in. Not about magazines being put in.

Think about revolver. The revolver doesn't get bigger when you put individual rounds into it. It does get bigger here.

**Comment by LeahLuong** [comment]
Look, IDK how gun work. I just know when you push the little button on the bottom, it gets loud & fast metal comes out of the front hole. It's pretty badass.

**Comment by catdach** [comment]
So gun items generally use 1 of 2 different types of pockets `"MAGAZINE_WELL"` and `"MAGAZINE"` which is literally written in the code as:
```"pocket_type": "MAGAZINE_WELL",``` (this is for guns that use **external** magazines. ie: Glock, AR-15, most guns)
or 
```"pocket_type": "MAGAZINE",``` (this is for guns that use **internal** magazines. ie: shotguns(except the siaga), revolvers and most bolt action rifles.)
There is also the (confusingly named) pocket data field `magazine_well` (lowercase) which determines how much volume can be placed within the pocket before it starts adding to the volume of the overall gun. For example the pocket data for the Glock 31 looks like this:
```
"pocket_data": [ { "magazine_well": "250 ml", "pocket_type": "MAGAZINE_WELL", "item_restriction": [ "glock40mag", "glock40bigmag" ] } ]
```
and for a double barrel shotgun looks like this:
```
"pocket_data": [ { "pocket_type": "MAGAZINE", "rigid": true, "ammo_restriction": { "shot": 2 } } ]
```
So gun(or other item) that doesn't define either `"magazine_well": "(volume)"` or `"rigid": true` are going to have more volume when it is loaded, which for most guns doesn't make sense.

**Comment by catdach** [comment]
Anyway, I personally agree that at least for pockets with `"pocket_type" : "MAGAZINE"`, should probably have `"rigid": true` by default.

**Comment by SirPendrak** [comment]
Only magazineless weapons that I can imagine getting bigger when being reloaded would be crossbows, ?bows? and some rocket/grenade launchers, like an RPG-7. Do we have RPG in game? 

But thats mostly nitpicking, and small arms like revolers getting bigger can actually have gameplay consequences like not being able to fit gun in holster when loaded.
