### ISSUE TITLE
Is/use options beyond UPS

### ISSUE THREAD

**Issue by Drew4484** [CleverRaven/Cataclysm-DDA#53987]
### Is your feature request related to a problem? Please describe.

I would like to be able to add backpack tanks for things like compressed air, flammable liquids, belts of ammo, etc. 

### Solution you would like.

Additional flags in the line of IS_UPS and USE_UPS.
Possible options: NAPALM, COMPRESSED_AIR, BELTED_556, BELTED_50_BMG

### Describe alternatives you have considered.

Backpack tank:
IS_NAPALM
Wielded flamethrower:
USE_NAPALM

Power armor backpack:
IS_BELTED_AMMO
Wielded M249:
USE_BELTED_AMMO

**Comment by Maleclypse** [comment]
Is there a way to jsonize this?  Maybe call it `"detached/worn magazine"`?    I think that jsonizing would be preferred over adding additional special casing.

**Comment by Drew4484** [comment]
> Is there a way to jsonize this? Maybe call it `"detached/worn magazine"`? I think that jsonizing would be preferred over adding additional special casing.

Yeah maybe a line like "use_attached": "

> Is there a way to jsonize this? Maybe call it `"detached/worn magazine"`? I think that jsonizing would be preferred over adding additional special casing.

Yeah being able to specify the connection type ("use-attached": "flamable") would be easier to add going foward, just don't know how to implement that.

**Comment by Hirmuolio** [comment]
The UPS code is pretty nasty in some places. Best to not think too much about that.

A completely made from scratch system for out of item ammo sources would be the only way to do it. 
Large sections of `visitable.cpp` would need to die to make that possible and the places that used those would need rewrites.
Largest part of this would probably be rewriting how crafting counts materials/tools.
