### ISSUE TITLE
Item endochitin was loaded with charges, but can not have any! Pt. 2

### ISSUE THREAD

**Issue by LeahLuong** [CleverRaven/Cataclysm-DDA#53989]
### Describe the bug

#48281 was marked as stale but this issue is still popping up in 0.F-3. I encountered this originally in 0.F-2 but noticed there were efforts underway last year to fix this along w/ some related items. Were those efforts abandoned?? It's been months & I figured it would've been fixed in the latest stable release. Seems like a fairly minor code revision.

### Steps to reproduce

1. Kill insects until they drop endochitin.
2. Leave the area, reload the game, & return.
3. ???
4. PROFIT!!!

### Expected behavior

I expected that endochitin level would increase, because all other skills can increase in level.

### Versions and configuration

Android 0.F-3 Tiles English vanilla

### Additional context

 DEBUG    : Item endochitin was loaded with charges, but can not have any!

 FUNCTION : void item::io(Archive &) [Archive = io::JsonObjectInputArchive]
 FILE     : /var/lib/jenkins/workspace/Cataclysm-Android/android/app/jni/src/../../../../src/savegame_json.cpp
 LINE     : 2581
 VERSION  : 0.F-3

**Comment by hexagonrecursion** [comment]
I am sorry, but I could not reproduce the issue in experimental

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: eacb7d9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by LeahLuong** [comment]
That's strange because any work that might've been done for this issue would've been completed by Apr 7 of last year, according to #48308, well before release of 0.F-3. Not such a big deal since the error generated is seemingly just an annoyance but I get the feeling it's going to crop up again in the next stable release. I'm hoping not.

**Comment by NetSysFire** [comment]
I wonder if this is related to the tailoring overhaul or so. #53866 seems remotely relevant here.

**Comment by luminous030** [comment]
The same issue happened to me, I was loot science lab, suddenly this showed up. 
 DEBUG    : Item endochitin was loaded with charges, but can not have any!

 FUNCTION : void item::io(Archive&) [with Archive = io::JsonObjectInputArchive]
 FILE     : src/savegame_json.cpp
 LINE     : 2581
 VE
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7958497/debug.log)
RSION  : 0.F-3

**Comment by LeahLuong** [comment]
@luminous030 We're on the same version. I closed this issue because it's seemingly not popping up in the newest experimentals. Create a new bug report if you find this happening in the latest releases.
