### ISSUE TITLE
Potions from Magiclysm are considered valid food for auto-eat behaviour

### ISSUE THREAD

**Issue by mkrutov** [CleverRaven/Cataclysm-DDA#53997]
### Describe the bug

If you have potions of mana, cat's grace, ogre's strength and presumably others available nearby and have Auto-Eat zone for your character to feed, those potions are considered valid food and character would eat them up.

I don't know what/how priorities are given to different foods for purposes of auto-eat zones. Distance?

 I've had this set up (approximately):

100 smoked meats located 5 tiles away 
10 potions of mana located 6 tiles away
100 dehydrated meats located 6 tiles away

I've stayed in the location for a couple weeks, and had Auto-Eat zone. Over that couple weeks, character ate all smoked meats and then started eating potions with no desire to eat dehydrated meats instead. 

### Steps to reproduce

1. Make a valid auto-eat zone
2. Put potions nearby
3. Observe character eat potions

### Expected behavior

My expectations would be that Potions are not eaten automatically. Otherwise, see additional context for some more thoughts. 

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 75a01ca [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    DinoMod [DinoMod],
    Disable NPC Needs [no_npc_food],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

I'm not sure what and how is it currently implemented, so I'll describe what I'd expect from an auto-eat zone.

Let's say you have a 11x11 space covered by auto-eat zone. On edge of that space, there is smoked meat which has 2 days till it rots. Closer to player, there is smoked meat which has 2 weeks to rot. Even closer to player, there are 2 piles dehydrated meat which has 3 seasons to rot, one being one tile closer. On same distance, there is something sealed which doesn't have an expiry date. 

I'd expect character to eat furtherest (and closest to rot) meat first, then move on to smoked meat which is still fastest to rot compared to other options. After that, dehydrated meat comes and closest pile is eaten first. Last of all is sealed food. 

Since most potions don't have expiry date on them, I'd expect them to be eaten only as the last resort if eating them can't be avoided in implementation of auto-eat zones.

**Comment by mkrutov** [comment]
Lowering "fun" value to [less than -5](https://github.com/CleverRaven/Cataclysm-DDA/blob/eacb7d927ef76c23b199b862eaada31f1c13832a/src/activity_item_handling.cpp#L3177) would solve this issue, as well as introducing a new json flag "NO_AUTO_EAT". Not sure if NO_AUTO_EAT flag would be a desireable solution though, and I don't like arbitrary -5 cutoff point.

**Comment by hexagonrecursion** [comment]
Confirmed

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: e7cd5fb [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm]
]
