### ISSUE TITLE
(Extreme) Persistence Hunter does not affect stamina regen

### ISSUE THREAD

**Issue by KittyTac** [CleverRaven/Cataclysm-DDA#53993]
### Describe the bug

The lupine mutations Persistence Hunter and Extreme Persistence Hunter, meant to make stamina regen faster, have literally no effect on stamina despite #53603.

### Steps to reproduce

1. Make a character.
2. Debug stamina to 0.
3. Wait until you catch your breath, should take around 7 minutes.
4. Debug in Wolf threshold and add Extreme Persistence Hunter.
5. Repeat steps 2 and 3 and see that it's also 7 minutes.

### Expected behavior

The behavior is consistent with the description `You can pursue prey for days until they literally die from exhaustion.  It's too bad zombies don't fatigue either.` and the json tag `"stamina_regen_modifier": 0.2`. Make it affect cardio.

### Screenshots

N/A

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 3ff3369 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Kittymod [kittymod],
    Extra Mutated Scenarios [extra_mut_scens],
    Tankmod: Revived [Tankmod_Revived],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi]
]

### Additional context

N/A

**Comment by PatrikLundell** [comment]
Have you verified that the maximum stamina is the same in both cases, i.e. that there isn't an increased recovery rate masked by a larger pool?

**Comment by KittyTac** [comment]
> Have you verified that the maximum stamina is the same in both cases, i.e. that there isn't an increased recovery rate masked by a larger pool?

Yeah, it's the same, I tested. Indefatigable affects that with `"cardio_multiplier": 1.3` but PH doesn't have that tag (nor should it, it's supposed to make you not-exhausted faster).

**Comment by hexagonrecursion** [comment]
Both with and without the (Extreme) Persistence Hunter mutation the stamina pool is 8714.

(Extreme) Persistence Hunter does _slightly_ decrease the time it takes to regen from 0 stamina: 7min 17s drops to 6min 6s

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: eacb7d9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by LeahLuong** [comment]
Looks like OP wasn't **_persistent_** enough in thier testing of this issue. Get it?!

**Comment by KittyTac** [comment]
No I tested it, and it had 7 minutes with both. TBH if that's the case then it's a pretty negligible effect compared to its point cost and description. I'll test a buff for it.
