### ISSUE TITLE
Yule wreaths are impassable and irremovable

### ISSUE THREAD

**Issue by gisaku33** [CleverRaven/Cataclysm-DDA#53991]
### Describe the bug

After deploying a yule wreath, it becomes an impassable and irremovable pine wreath furniture. Can not be deconstructed, and when I tried to bash it down I could only hit the LMOE carpet and floor.

### Steps to reproduce

1. Place a yule wreath.
2. Attempt to deconstruct it.
3. Attempt to smash it.

### Expected behavior

I expected my wreath to be cozy and decorative, and not a permanent magical forcefield.

### Screenshots

![image](https://user-images.githubusercontent.com/23239811/147904984-b2e37207-7aa5-477b-9518-10822e7e5e6e.png)
![image](https://user-images.githubusercontent.com/23239811/147905055-6b593543-69e1-4bec-bcfa-0bbbad5d6b82.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 3ff3369 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

**Comment by NetSysFire** [comment]
You can still grab it though if that is of any help
