### ISSUE TITLE
[Magiclysm] Technomancer Toolbar cannot pry nails

### ISSUE THREAD

**Issue by Lord-Helmchen** [CleverRaven/Cataclysm-DDA#53996]
### Describe the bug

TToolbar now has nail prying 1, but it still can't be used for it, neither by examining a boarded up door, nor by (a)ctivating it nor via the actions menu.

### Steps to reproduce

Get a Technomancer Toolbar
find or construct boarded up door (or window)
try to unboard-up
get a crowbar
succeed

### Expected behavior

Technomancer (Mana-) Toolbar should be a strict uprade over a mundane crowbar

### Versions and configuration

version eacb7d9
build 2022-01-03-0731

### Additional context

#53201 was closed after nail prying quality was added, but problem persists

**Comment by catdach** [comment]
Probably just needs the "crowbar" use action or something, which might solve some other issues as well. I'll try to work on that tomorrow.
