### ISSUE TITLE
Grabbed through Z-levels and pulled into a lab.

### ISSUE THREAD

**Issue by Croctus** [CleverRaven/Cataclysm-DDA#54000]
### Describe the bug

Seems that a Phase Skulker pulled my character from the street of a town down into a lab. Could have been another enemy but I was placed directly beside the Skulker with the same "sickness" you get when you're teleported. My tileset shows a bloodshot eye above my head.

### Steps to reproduce

Could not reproduce the issue.

### Expected behavior

I didn't think Phase Skulkers could grab at all much less through multiple z-levels and solid rock.

### Versions and configuration

Game Version 0d20a08 experimental

**Comment by hexagonrecursion** [comment]
1. Could you please upload a zip archive of your save file?
2. Could you please:
    1. Load the save
    2. Press [ESC]
    3. Select "Debug Menu"
    4. Select "Info"
    5. Select "Generate game report". This should copy the report into the clipboard.
    6. Post the report here.
3. Find the ./config/debug.log file in your game folder and post it here too
