### ISSUE TITLE
Metal Detectors Are Based on the Science of Electromagnetism!

### ISSUE THREAD

**Issue by LeahLuong** [CleverRaven/Cataclysm-DDA#54007]
### Is your feature request related to a problem? Please describe.

Metal detectors don't currently exist in this game. It would be neat to be able to cobble 1 together & use it for a variety of applications.

People have suggested in past minefield discussions that this would be a handy tool to have. Buried landmines have been the death of many a char, especially Perception-challenged 1's, but that doesn't have to be the case.

I could also see a use for metal detectors in finding & perhaps assisting in the acquisition of CBM's. The detector could be used to determine initially if a corpse has a CBM & subsequently provide a bonus to dissection, either decreasing dissection time, raising success chance, or both.

Another possible application for metal detectors is prospecting. A detector could alert the player to the presence of rebar in constructions. If powerful enough, a metal detector can sense metallic ores in the earth. Who knows what hidden treasures can be found in shallow graves or corpse-filled pits?? Only those who aren't concerned w/ the moral implications will find out!

Metal detectors could lead to new mission possibilities, 1's where detecting metal is of the utmost importance. So exciting! Who doesn't want metal detectors?? The question is rhetorical. The answer: only those who wish to remain willfully ignorant of the existence of metal in their world.

In closing: metal detectors are based.

### Solution you would like.

Crafting a metal detector shouldn't be all that tough. The principle is rather simple: a battery is used to power a coil which generates an electromagnetic field. This field induces eddy currents in nearby metallic objects that are then detected by a 2nd coil in the device. Feedback from the device is given by audio or visual cues; even the blind or deaf can use them! I would suggest a pipe and scrap metal as sufficient for the body of the detector, basic electrical components for electromagnetic voodoo, & middling Electronics/Fabrication skills as sufficient for crafting. Medium batteries seem like a good power source. The recipe could be found in mid-lvl Electronics books.

Implementation of the actual metal detection will be trickier & I leave that to whomever decides to take this project on. Ideally, metal detection would apply to all squares immediately adjacent to the char. Feedback could be given through the compass or message log, indicating direction & strength of signal. Buried landmines should have a high probabilty of being revealed, if not guaranteed.

The prospecting version of handheld metal detector may need its own recipe. I don't think standard detectors have enough power to find metallic ores underground but devices w/ this capability have been made IRL. Perhaps a juiced up version of the above proposal would suffice, powered by a heavy battery: more components & skill required to craft, more muscle to carry the mass around, & more power to get those eddy currents flowing.

It's possible metal detectors could be found in military settings, electronics stores, or rarely in a sporting goods store near you. Mines may be a good place to find the heavy-duty version. Who knows if there's a random field encounter or isolated cabin where some hermit prospector was lookin' fur gowuld in them thar hills??

### Describe alternatives you have considered.

It's not hard to imagine the sad, sad case of a world w/out metal detection; we are already living in it. But it doesn't have to be this way!

### Additional context

Be sure to chime in if you have thoughts on how or why this feature should be implemented. I lack the capacity to bring this idea to fruition but perhaps I've planted a seed here, a seed which will 1 day grow into a beautiful, giant, man-eating plant that devours the lives & limbs of those who are willing to sacrifice to its cause. 1 can only hope.

**Comment by PatrikLundell** [comment]
- I believe mines have been developed to have the minimum amount of metal possible, exactly to prevent detection with metal detectors. I would expect such mines to be military, not the type you've get recipes for (and thus can encounter around bandits and survivors). That's one reason rats have been trained to sniff out the explosives instead (and rats are light enough not to trigger the mines, so the rats are reusable).
- If CBMs are made of metal they're probably made out of titanium, which is bio compatible but isn't magnetic (which is one reason that metal is used in expensive military submarines, MADs have a harder time detecting them (MAD = Magnetic Anomaly Detector).
- For prospecting I'd guess they'll use airborne detectors, probably similar to MADs.
- I don't see why you'd use metal detectors in (for resource digging: damned homonyms) mines. They map out the veins using geological methods.

Getting metal detectors to detect metal in man made items probably isn't trivial, though, as that would require the code to deduce what they're made of. If you smash roads the game gives you rebar, but the terrain itself just has a name for the road material, and it's the smashing action that actually produces the "hidden" resources. Probe smashing and dismantling everything around you (recursively) to determine if anything is made out of magnetic metal of a sufficient quantity is probably going to be expensive. in CPU terms.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
