### ISSUE TITLE
configurable crafting range in options

### ISSUE THREAD

**Issue by alp7292** [CleverRaven/Cataclysm-DDA#54014]
### Is your feature request related to a problem? Please describe.

for players who sorts their warehouse or death mobile(me) crafting range often isnt enough

### Solution you would like.

adding a debug option to configure crafting range from 0 to 12 or 1 to 12

### Describe alternatives you have considered.

or not add it if its too much trouble to add

**Comment by ZhilkinSerg** [comment]
This is a compile time constant. We don't want it to be configurable in runtime.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
