### ISSUE TITLE
configurable reality bubble range in options

### ISSUE THREAD

**Issue by alp7292** [CleverRaven/Cataclysm-DDA#54013]
### Is your feature request related to a problem? Please describe.

reality bubble range is often times not enough

### Solution you would like.

adding a debug option to modify range

### Describe alternatives you have considered.

or not add it if its too much trouble to add

**Comment by ZhilkinSerg** [comment]
This is a compile time constant. We don't want it to be configurable in runtime.

**Comment by Terrorforge** [comment]
> This is a compile time constant. We don't want it to be configurable in runtime.

Does that mean it would be possible to change if you compile the code yourself?

**Comment by PatrikLundell** [comment]
Well, yes, the code can be changed to change the value of constants. It can be noted that the effects of changing such constants probably haven't been tested, so things may well break in both expected and unexpected places. It's also possible that there are cases of poor programming practices in places in the code where knowledge of the value of the constant is used without actually referencing the constant itself, and so will break (not necessarily in visible ways, and C is known for its support of unchecked access of unrelated memory) when the value is changed.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
