### ISSUE TITLE
You cannot start driving an unfolded vehicle without stepping off, then stepping back on

### ISSUE THREAD

**Issue by Paprika-H** [CleverRaven/Cataclysm-DDA#54026]
### Describe the bug

When you unfold a vehicle, it unfolds on your tile that you stand on. However, to be able to ride it, you need to step off, then step back on it again. This is difficult if you have broken legs, or lack them. 

### Steps to reproduce

1. Get an unfolded vehicle (eg a wheel chair)
2. Fold it
3. Unfold it
4. Try to ride it, instead you'll get the pop up for the examination, despite being on the controls. 

### Expected behavior

I expect that when you fold a vehicle, and unfold it, you should be able to ride it and control it without having to step off of it and then back on. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 83137a8 [64-bit]
- Graphics Version: Tiles
- Game Language: Nederlands [nl]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by wapcaplet** [comment]
Confirmed, this has been an annoyance with folding bicycles for as long as I can remember.

**Comment by Paprika-H** [comment]
> Confirmed, this has been an annoyance with folding bicycles for as long as I can remember.

Has no one made an issue on it, or did I just miss it?

**Comment by wapcaplet** [comment]
> > Confirmed, this has been an annoyance with folding bicycles for as long as I can remember.
> 
> Has no one made an issue on it, or did I just miss it?

I could not find one in a quick search of open issues for "folding", so maybe it has gone unreported all these years.

**Comment by bouchacha** [comment]
I've encountered this issue as well. It was confusing the first few times it happened.
