### ISSUE TITLE
QoL: Allow siphoning from a vehicle into a CBM

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#54031]
### Is your feature request related to a problem? Please describe.

As far as I can tell there is currently no way to move fuel directly from a vehicle tank to a CBM - one has to siphon it into a container first.

### Solution you would like.

Allow the player to siphon fuel directly into a CBM (e.g. a gasoline fuel cell).

### Describe alternatives you have considered.

Keep this as is (less convenient)

### Additional context

Ref: https://github.com/CleverRaven/Cataclysm-DDA/issues/51334 https://github.com/CleverRaven/Cataclysm-DDA/issues/51301

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: eacb7d9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]
]

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
