### ISSUE TITLE
Cutlass listed for Cutting (intermediate) Practice but not usable

### ISSUE THREAD

**Issue by RegHog** [CleverRaven/Cataclysm-DDA#54035]
### Describe the bug

The cutlass is listed as one of the tool requirements for Crafting Practicing Cutting (Intermediate) but after finding a cutlass and wielding it the option is still red in the Practice crafting menu.  See attached
![cutlass](https://user-images.githubusercontent.com/97105769/148069070-e3376c9c-d5ec-40fa-9ff4-122fefc49218.PNG)
![Cutting Intermediate](https://user-images.githubusercontent.com/97105769/148069090-5c719ec5-99ee-4a93-8932-5d007c0cea26.PNG)
.
Note that after the screenshot I also made an armoured training dummy just in case that was causing a problem but the cutlass is still not showing as being available and when I try to do this practice it says "I can't do that".

### Steps to reproduce

1. Find a cutlass and wield or place nearby
2. Go to crafting menu and select Cutting (Intermediate) from the practice tab
3. See if cutlass is marked as green in the Tools available.

### Expected behavior

I would expect the cutlass to be usable for this practice task as stated and the text to be highlighted green in the crafting menu.

It does say that this cutlass is flimsy so is it not usable for this task and if so is there another better cutlass in the game?

### Versions and configuration

OS Windows 10
version 0426c7c
No mods except dark days ahead & No Fungal Growth
English language

**Comment by OtpalTS** [comment]
That cutlass is a fake version, the proper one is made from steel and has better stats. I wonder if it should be allowed to be used in training since it weight, balance and cutting properties are so different from an actual blade

**Comment by Michael1993** [comment]
I honestly think it having the same name is a great feature. It's always a thrill to spot a cutlass/pike/mace in a mansion or museum, only to find out it's just a cheap replica on closer inspection. 😄

**Comment by LeahLuong** [comment]
I, too, find delayed disappointment to be "thrilling" where by "thrilling" I don't mean its literal definition but some other, undisclosed meaning.

**Comment by RegHog** [comment]
Now I realise this is not a bug and that more than one item can have the same name I too quite like this dynamic.  This is after all an intermediate cutting lesson and to be able to use a 'cheaply made replica' with cutting 1 for this is unrealistic.  I will close this.
