### ISSUE TITLE
Recipes and action menu don't recognize arc welder with UPS conversion mod has charges.

### ISSUE THREAD

**Issue by epsimpson** [CleverRaven/Cataclysm-DDA#54036]
### Describe the bug

I have an arc welder with a UPS mod.  All recipes show arc welder in red.  The action menu shows it in red also, saying it needs 5 charges.

### Steps to reproduce

1. make an arc welder with a UPS mod.
2. make a UPS.
3. try to use the arc welder in a recipe and from the action menu.

### Expected behavior

I expected it to work like a soldering iron does under the same circumstances (that was how I had tested UPS when I tried it).  A UPS soldering iron works perfectly in recipes, and works perfectly from the action menu.

Soldering irons show white (selectable) in the action menu even if there is no battery attached, and only informs you of the missing charges when you try to use it.  That may not be optimal, but it is the present state, and it works.  Non-UPS arc welders without a battery, on the other hand, show as red (unselectable) in the action menu, just like a UPS welder.

### Screenshots

![Screenshot_arcWeldNoFindRecipe](https://user-images.githubusercontent.com/64863108/148070260-9de79191-31fb-43ab-880d-60fb6e373fa1.png)
![Screenshot_arcWeldNoFind](https://user-images.githubusercontent.com/64863108/148070274-e4c506d7-49d7-41ea-b0e8-024488a024ec.png)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.3 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-4888-g0426c7cb39 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

The screenshot showing what was in inventory has a UPS modded to accept car batteries, but the same is the case using a regular, unmodded UPS.

**Comment by Hirmuolio** [comment]
That is weird. Works for me.
![weld1](https://user-images.githubusercontent.com/22011552/148086547-e1201fe5-28dd-4bbb-abde-52277af25032.png)
![weld2](https://user-images.githubusercontent.com/22011552/148086548-33361bbe-56fe-4190-b008-8e022329d42b.png)

**Comment by epsimpson** [comment]
Weird.  Is it possible there was another charged welder nearby?  Here's my save file.  I thought it would be too big.

[AlexNoWeld.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7808847/AlexNoWeld.zip)

**Comment by epsimpson** [comment]
Never mind It was the wrong mod!!!
