### ISSUE TITLE
Mutation menu can't be closed

### ISSUE THREAD

**Issue by mqrause** [CleverRaven/Cataclysm-DDA#54039]
### Describe the bug

The mutation menu doesn't react to a bunch of inputs, most importantly to anything closing the menu.

### Steps to reproduce

1. Open mutation menu
2. Press `Esc` or any other key assigned to closing the menu, even custom ones

### Expected behavior

All registered keybindings work.

### Versions and configuration

Win 10 Tiles
0426c7cb39e6d4eb5ca0f5faa701bf378ff64e35

**Comment by mqrause** [comment]
Found the culprit in `mutation_ui.cpp`:
https://github.com/CleverRaven/Cataclysm-DDA/blob/cb11ca5e3a1668af1c87385576881f23376822a2/src/mutation_ui.cpp#L482
Because "PREV_TAB" always evaluates to true, the condition will be true and anything after it is skipped.

**Comment by jeanpaulrsoucy** [comment]
I can confirm this one using the latest experimental on Linux. I couldn't figure out any way to exit the mutation menu beyond killing the game process (potentially losing progress if you haven't saved recently).

**Comment by NoddingCrow** [comment]
Confirmed on 2022-01-06-1918, Windows. 
Mutation menu can be closed if you happen to be able to activate a toggleable mutation, otherwise is a hard lock requiring killing the process.

**Comment by jeanpaulrsoucy** [comment]
> Found the culprit in `mutation_ui.cpp`:
> 
> https://github.com/CleverRaven/Cataclysm-DDA/blob/cb11ca5e3a1668af1c87385576881f23376822a2/src/mutation_ui.cpp#L482
> 
> Because "PREV_TAB" always evaluates to true, the condition will be true and any condition after it is skipped.

Tagging @Rovallen, the author of #53764.

**Comment by Rovallen** [comment]
My bad, sorry! Made a PR with a fix. I truly deserve a boot to the head for such mistakes...
