### ISSUE TITLE
Moving with two broken legs takes too long

### ISSUE THREAD

**Issue by Paprika-H** [CleverRaven/Cataclysm-DDA#54032]
### Describe the bug

If you have two broken legs, it takes about 7 minutes to move one tile. I understand that moving with broken limbs is hard, but I don't think 7 minutes is realistic here, especially with 0 pain. 

### Steps to reproduce

1. Make a player have 0 health on both legs
2. Spawn in a watch to keep track of time
3. Move, and be in shock and awe of how slow it is. 

### Expected behavior

I expect the survivor to move a bit faster if they got two broken legs. I understand that moving with broken limbs is hard, but I don't think 7 minutes is realistic here, especially with 0 pain. 

### Versions and configuration

OS: Windows
OS Version: 10.0 2009
Game Version: 83137a8 [64-bit]
Graphics Version: Tiles
Game Language: Nederlands [nl]
Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
No Fungal Growth [no_fungal_growth],
Bionic Professions [package_bionic_professions]
]

**Comment by Zireael07** [comment]
If both legs are broken, he's crawling. And it's not military crawl, it's regular person crawl, slow as hell

**Comment by Paprika-H** [comment]
> If both legs are broken, he's crawling. And it's not military crawl, it's regular person crawl, slow as hell

If we assume a tile is 1m in terms of movement, it takes the survivor 7 minutes to crawl it, 1 meter in 420 seconds. That's 0.0024m/s, or 0.00857 kmph. A sloth is about 10x as fast as that. A sloth.

**Comment by Venera3** [comment]
Yeah, that's the player movement scors missing. I could see two solutions to it (at least, two *good* solutions) : Either movement scores could use the same `score, score_max` system manipulation score does, meaning e.g. your arms could have some "backup" movement score that would only come into effect at a very low move score to show you crawling.

Or the different movement modes could define which character modifier they use for calculating move costs - crawling still uses only your legs' scores, not your arms' lifting score. That could also come in handy if/when movement modes become a bit more flexible, but that's a tangent.

@dseguin thought on those options? I could probably special case prone to use a new modifier, but you've been doing some amazing work unhardcoding limb scores and character modifiers, so I'd rather not tack on more hardcode.

**Comment by dseguin** [comment]
I'm no expert, just voicing my thoughts:

Without legs, you're heavily leveraging your arms for movement, but only while prone (you don't use your arms to move if you're not on the ground). So I'd say that some arm-related score should definitely contribute to movement speed (lifting or otherwise), but only while prone. That would prevent your arms from enhancing movement speed while standing.
