### ISSUE TITLE
Single tile forest islands have too few trees

### ISSUE THREAD

**Issue by mqrause** [CleverRaven/Cataclysm-DDA#54040]
### Describe the bug

Despite being called forest, there are very few trees on small islands. I assume the terrain feathering feature #50733 caused this.

### Steps to reproduce

1. Start on an island, chances are it's forest.
2. See very sparse trees.

### Expected behavior

From my experience, small islands in lakes and rivers are pretty much all or nothing. So if it's forest, there should be trees everywhere.

### Screenshots

![grafik](https://user-images.githubusercontent.com/38702195/148090151-c88a7b64-917a-4a53-bcf2-39836b2a3a41.png)

### Versions and configuration

0426c7cb39e6d4eb5ca0f5faa701bf378ff64e35

**Comment by LeahLuong** [comment]
You can't eat your forest & have it too. This seems like a case of being unable to see the cake for the pies.

**Comment by RoyBerube** [comment]
Is it possible to turn off the feathering for shore tiles? It would affect all lake and river shores as well but makes sense to me.

**Comment by Zireael07** [comment]
@RoyBerube not necessarily, it should be possible to detect 1 tile big islands and exclude them from feathering

**Comment by mqrause** [comment]
> Is it possible to turn off the feathering for shore tiles? It would affect all lake and river shores as well but makes sense to me.

Yeah, that'd be my suggested solution, too. Single tile islands really aren't the only issue, it's just what I noticed first.
