### ISSUE TITLE
Mouse mutants can't wear masks and can't refit XL masks to themselves

### ISSUE THREAD

**Issue by mkrutov** [CleverRaven/Cataclysm-DDA#54047]
### Describe the bug

subj

### Steps to reproduce

1. Mutate a muzzle and tiny
2. Get a survivor mask and XL survivor mask
3. Try refitting/wearing them. You can refit regular mask, but can't wear it cause of muzzle; you can wear XL mask but can't refit it - its stuck at Huge.

### Expected behavior

I'd expect some mask to be wearable without being "huge", so XL mask should be refittable from its huge status to regular size (for mouse)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 75a01ca [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    DinoMod [DinoMod],
    Disable NPC Needs [no_npc_food],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Terrorforge** [comment]
This is probably because the regular and XL versions of the masks are different materials. Survivor mask is layered kevlar and leather, XL survivor mask is layered kevlar and plastic. You can also reinforce the regular mask but not the xl version, presumably for the same reaon.

**Comment by LeahLuong** [comment]
"XL" stands for "eXtra Large"; it makes sense it wouldn't fit a tiny mutant. XS clothing/armor was already raised as an issue in #47762 but it seems the PR for it -- #48152 -- was abandoned by its creator UmbralReaper.

@UmbralReaper You still out there somewhere??

**Comment by Terrorforge** [comment]
Kind of, but "XL" (or rather, the OVERSIZE tag) is also what allows you to wear a piece of gear if you have mutated anatomy, like any of the various muzzles. That's another reason I think we could do with a more dynamic clothing size system as suggested in #53496, but in the meantime the fact that mouse mutants can't use the mask that circumvents mutated anatomy to circumvent their mutated anatomy should be considered a bug.

**Comment by mkrutov** [comment]
@Terrorforge , mouse mutants can wear XL mask. They just get a *really* huge encumbrance from wearing XL stuff.
