### ISSUE TITLE
Adding more utility to smartphone

### ISSUE THREAD

**Issue by new02DAY** [CleverRaven/Cataclysm-DDA#54057]
### Is your feature request related to a problem? Please describe.

I'm not sure if it was discussed when the book scanning function was added, but I think we should be able to do the same with a smartphone. Not sure, but maybe with slight penalty to mitigation? But also maybe without, since device size shouldn't really impact anything. 

Also maybe add the ability to read SD cards? But this one is more understandable since no phone can read full-size SD cards. Maybe we can change them to micro-SDs? The way I see it, we use SD cards for full-size cameras (DSLRs, etc.) and micro-SDs are more ubiquitous (phones, drones, MP3 players, etc.). So I'm not sure what a good compromise would be. 

EDIT: thinking on it, I don't think any tablets/e-readers read full-size SD cards, either. So maybe we can add the read function to phones without contradiction (and just rename SDs to micro-SDs for detail).

It'd probably reduce the utility of the tablet, but make smartphones even more useful. 

EDIT: Similarly, it'd be great if we could use the smartphone while it's playing music or being used as a flashlight (ie. use it as a flashlight while playing music, or vice versa; also with reading ebooks if added). Another great addition would be allowing for the screen light (like the tablet), and modifying the flashlight to an increased radius.

### Solution you would like.

Add book scanning to smartphones. Maybe allow for SD card reading, as well.

### Describe alternatives you have considered.

Just use the tablet.

### Additional context

I understand it's low priority and a lot of work, since it's hardcoded, and not easily added via JSON. I've just reached that point in a recent run where I begin to min-max my scavenging gear, so removing the tablet, mp3, player, flashlight, reading light etc. would be handy.

**Comment by mkrutov** [comment]
(same for aftershock atomic smartphone as well)
