### ISSUE TITLE
Firearm (and gunsmith?) repair kits missing soldering action

### ISSUE THREAD

**Issue by new02DAY** [CleverRaven/Cataclysm-DDA#54056]
### Describe the bug

Firearm and gunsmith (presumably) repair kits are missing soldering actions/functions when activating. Also, less of an issue, but not sure why the pry actions are duplicated (see screenshots).

### Steps to reproduce

1. Spawn said kits.
2. Activate and see missing soldering actions/functions.

### Expected behavior

Kits should be able to solder.

### Screenshots

![image](https://user-images.githubusercontent.com/56372745/148151470-6b64a920-db4c-494f-bd96-6cefe7964846.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 8c498f6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    Player Mod [Player_Mod],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by hexagonrecursion** [comment]
I can confirm that neither the firearm nor the gunsmith repair kit offer to "cauterize a wound" or to "repair plastic, lead, tin and zinc" when you [a]ctivate them. I can also confirm that the recipe for the firearm repair kit includes a soldering iron. There appears to be no recipe for the gunsmith repair kit so I am not sure what do you base your assumption that it should act as a soldering iron on.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: eacb7d9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by new02DAY** [comment]
> I am not sure what do you base your assumption that it should act as a soldering iron on.

Thanks for the confirmation!
The gunsmith repair kit is supposed to be a more (battery) efficient version of the firearm kit, I think (25 charges vs. 100 charges). Although, it takes a larger battery (medium vs. ultra/light). As such, I'm just assuming it uses a soldering kit, as well. 

Ideally, we'd just rework gunsmithing away from kits, like what happened with toolboxes, like someone mentioned in another thread/report. 

EDIT: looks like someone tried addressing this, but was never resolved, see #45858 and #45486.
