### ISSUE TITLE
Issue with kevlar chainmail armors

### ISSUE THREAD

**Issue by new02DAY** [CleverRaven/Cataclysm-DDA#54055]
### Describe the bug

"kevlar chainmail armor" shows "Negligible Protection", while "XL kevlar chainmail armor" has the same stats as "XL chainmail armor".

### Steps to reproduce

1. Open crafting menu with character capable of crafting said armors.

### Expected behavior

Armors would reflect proper values.

### Screenshots

![image](https://user-images.githubusercontent.com/56372745/148151083-6d946b30-d111-4db7-ab8b-2a59aab0fe4b.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 8c498f6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    Player Mod [Player_Mod],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Drew4484** [comment]
This is part of my #53820 PR, I'll look at it tonight.

**Comment by new02DAY** [comment]
Thought this would close once the PR went through. Thanks for the quick fix!
