### ISSUE TITLE
"Failed to write player data to"

### ISSUE THREAD

**Issue by Peter-Stromboli** [CleverRaven/Cataclysm-DDA#54053]
### Describe the bug

every time when i open the game, it shows an error saying "Failed to write options to ".config/options.json": moving temporary file ".\config\options.json.18048.temp" failed.  And when this happens, i have to manually exit out.

If i mannage to get in the title screen, and click on my game, whenever i wish to save sed game, an error appears saying 
'Failed to write player data to "./(World name)/#SGFucyBFbG1hcw==.sav": Moving temporary file ".\save\(world name)\ #SGFucyBFbG1hcw==.sav.19828.temp" failed.

i have tried downloading lot of versions, i am running windows 11, but it started on windows 10. if you need any more information please ask for it... i really just want to play the best zombie game ever made.

### Steps to reproduce

I have no idea.

### Expected behavior

I expect the .Json files are the reason its messing up, but i dont know how to fix it.

### Screenshots

![Screenshot (5)](https://user-images.githubusercontent.com/97136774/148146084-aeff5d52-0718-4428-8ae1-b14e6b0b23d3.png)

![Screenshot (6)](https://user-images.githubusercontent.com/97136774/148146122-c203aee7-2740-4fe1-b67d-4eb20a1d62a1.png)

![Screenshot (7)](https://user-images.githubusercontent.com/97136774/148146232-0fbd52a4-72df-4057-9b64-9a25123bdcee.png)

### Versions and configuration

-Windows 11
-No matter the version
-if i try to change the graphics, the same "failed to write options to" error appears.
-English
-It matters not if i use mods or not.

### Additional context

An error message appears every time my game saves, or i change any of the controlls or change the graphics.

**Comment by LeahLuong** [comment]
I'm simply a fellow player of this game so you should prob wait for a 2nd opinion on this. That said, here are my thoughts:

You have not provided what version of the game you are running. Old versions may not be fully compatible w/ your OS.

No 1 else is encountering this issue (AFAIK) so it seems specific to you. Failure to write errors indicate your files may be read-only or you don't have high enough access on the system you are running. Have you checked the folder properties for your game?? Do you have admin on your OS??

It's possible your game files have somehow been corrupted. In that case, you can backup your save & try re-installing to restore the game to an uncorrupted state.

There may be more helpful info you can provide us w/ by digging up your crash.log or recent entries from your debug.log, both found in the config folder for the game.

**Comment by Peter-Stromboli** [comment]
> I'm simply a fellow player of this game so you should prob wait for a 2nd opinion on this. That said, here are my thoughts:
> 
> You have not provided what version of the game you are running. Old versions may not be fully compatible w/ your OS.
> 
> No 1 else is encountering this issue (AFAIK) so it seems specific to you. Failure to write errors indicate your files may be read-only or you don't have high enough access on the system you are running. Have you checked the folder properties for your game?? Do you have admin on your OS??
> 
> It's possible your game files have somehow been corrupted. In that case, you can backup your save & try re-installing to restore the game to an uncorrupted state.
> 
> There may be more helpful info you can provide us w/ by digging up your crash.log or recent entries from your debug.log, both found in the config folder for the game.

at this point its not about a profile, its about making the game work, i have uninstalled and re-installed multiple versions, and the same error messages occur with them all. 

Here is my debug.log

21:37:48.160 : Starting log.
21:37:48.161 INFO : Cataclysm DDA version bc28921
21:37:48.165 INFO : [main] C locale set to C
21:37:48.165 INFO : [main] C++ locale set to C
21:37:48.165 INFO : SDL version used during compile is 2.0.14
21:37:48.165 INFO : SDL version used during linking and in runtime is 2.0.14
21:37:48.240 INFO : Number of render drivers on your system: 5
21:37:48.240 INFO : Render driver: 0/direct3d
21:37:48.240 INFO : Render driver: 1/direct3d11
21:37:48.240 INFO : Render driver: 2/opengl
21:37:48.240 INFO : Render driver: 3/opengles2
21:37:48.240 INFO : Render driver: 4/software
21:37:48.240 INFO : [options] C locale set to C
21:37:48.240 INFO : [options] C++ locale set to C
21:37:48.240 INFO : Setting language to: 'en'
21:37:48.240 INFO : Language is set to: 'en'
21:37:48.240 INFO : [translations] C locale set to English_United States.1252
21:37:48.240 INFO : [translations] C++ locale set to C
21:37:48.357 INFO : Active renderer: 1/direct3d11
21:37:48.519 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
21:37:48.529 INFO : Setting language to: 'en'
21:37:48.529 INFO : Language is set to: 'en'
21:37:48.529 INFO : [translations] C locale set to English_United States.1252
21:37:48.529 INFO : [translations] C++ locale set to C
21:37:48.742 WARNING : opendir [./mods/] failed with "No such file or directory".
21:37:54.288 WARNING : opendir [./save/Windsor Hills/mods] failed with "No such file or directory".
21:37:58.680 INFO : Loaded tileset: UltimateCataclysm
21:38:07.290 : Log shutdown.

**Comment by LeahLuong** [comment]
Clicking on the version info link that appeared in your debug.log eventually lead me to the following:

https://discourse.cataclysmdda.org/t/error-game-is-unable-to-write-its-options-json-file/26701

It looks like some1 else was having the same issue & possible solutions are outlined near the bottom of the post.

**Comment by Peter-Stromboli** [comment]
> Clicking on the version info link that appeared in your debug.log eventually led me to the following:
> 
> https://discourse.cataclysmdda.org/t/error-game-is-unable-to-write-its-options-json-file/26701
> 
> It looks like some1 else was having the same issue & possible solutions are outlined near the bottom of the post.

AGH... i was sure that those things would work...  but it didnt... Shit confounds me XD

**Comment by hexagonrecursion** [comment]
Please provide the full path to where your installation of cataclysm: dark days ahead is.

**Comment by Peter-Stromboli** [comment]
> Please provide the full path to where your installation of cataclysm: dark days ahead is.

I have downloaded it to my desktop, my downloads folder, and my OS (C:) and all dont work.

**Comment by Peter-Stromboli** [comment]
> Please provide the full path to where your installation of cataclysm: dark days ahead is.

I have downloaded it to my OS (C:), my download folder and my desktop. alongside this i have also enabled all permissions on each download.

**Comment by Peter-Stromboli** [comment]
> > Please provide the full path to where your installation of cataclysm: dark days ahead is.
> 
> I have downloaded it to my OS (C:), my download folder and my desktop. alongside this i have also enabled all permissions on each download.

**Comment by Peter-Stromboli** [comment]
> Well, I tried to help. Hope some1 else w/ more technical knowhow happens by . . .

Your help is much appreciated, i thank you from the bottom of me heart.

**Comment by NetSysFire** [comment]
I think this might very well be windows related. I am no windows user and have no idea about windows but if you want something to try, create a new local user, install cataclysm there and try again. If it works, it might be an issue with your installation.
I suppose cataclysm might store its stuff in `%APPDATA%` or however it was called which is specific per user.

**Comment by new02DAY** [comment]
How do you run the game? From a launcher or cataclysm-tiles.exe? Can you try right-click (on launch or tiles.exe)>Run as administrator>Yes and see if that helps? If you do use the launcher, can you try running it from tiles.exe?

**Comment by Peter-Stromboli** [comment]
> How do you run the game? From a launcher or cataclysm-tiles.exe? Can you try right-click (on launch or tiles.exe)>Run as administrator>Yes and see if that helps? If you do use the launcher, can you try running it from tiles.exe?

I have tried the launcher and the cataclysm.exe, have set all permissions on, and have them run in administrator... it does not work my good sir.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
