### ISSUE TITLE
Improve treatment of default values in options UI

### ISSUE THREAD

**Issue by J-Fields** [CleverRaven/Cataclysm-DDA#54060]
### Is your feature request related to a problem? Please describe.

In the options menu (main menu > `Settings` > `Options`), the default value for the selected option is displayed inline with the description. The current implementation is quite basic; see [options_manager::cOpt::getDefaultText()](https://github.com/CleverRaven/Cataclysm-DDA/blob/9a985cf34f1da637d0e4ef0ccf5ef3b5c78e5cfd/src/options.cpp#L654).

I like to be aware of how my settings differ from the defaults, and the current UI does not help me out much in this regard.

### Solution you would like.

 A few ideas:
- The default value should be displayed on its own line after the description, and probably with a splash of color.
- There should be some indicator (different color text, a column with an asterisk, etc.) to see which options have been modified at a glance.
- There should be a keybinding to reset an option to its default (`r`, to match AIM's filter reset?). Maybe another to reset the whole page?
- Unnecessary, but seems neat - a 2 column "diff view" showing only the settings you've changed

### Describe alternatives you have considered.

They're mostly listed above.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
