### ISSUE TITLE
Mutable Overmaps only work on ground structures and below

### ISSUE THREAD

**Issue by Xaritscin** [CleverRaven/Cataclysm-DDA#54061]
### Is your feature request related to a problem? Please describe.

Found this problem while testing some overmap additions on #53858 

I read the doc files and checked examples of Mutable Overmaps in order to implement the first parts of termite mounds on mod but at the time of testing a new roof piece designed to cover the original Anthill structure it turns out the system cannot validate for coordinates above the surface.

The documentation doesnt mentione anything related to roofing and the examples found are all underground stuff like minilabs or mines so i had to improvise and see if the system would take it. but as per the reason of this issue, it didnt.

### Solution you would like.

Add a check up for above surface coordinates on the Mutable Overmap code. right now the "above" field applies only for joined connections but there's no filed for simple non connected roofing (roof that isnt connected to stairs or similar)

### Describe alternatives you have considered.

not bother with roofing and just make my structures on Fixed Overmap or Mutable but only walls at the surface.

### Additional context

I tried to follow the syntax of the Mutable Overmap file and created a coordinate for "open_air" or other names and added a new "roof" line to the Overmaps part like this

 

> "check_for_locations": [
>       [ [ 0, 0, 0 ], [ "land" ] ],
>       **[ [ 0, 0, 1 ], [ "roof" ] ],**
>       [ [ 0, 0, -1 ], [ "subterranean_empty" ] ],
>       [ [ 1, 0, -1 ], [ "subterranean_empty" ] ],
>       [ [ 0, 1, -1 ], [ "subterranean_empty" ] ],
>       [ [ -1, 0, -1 ], [ "subterranean_empty" ] ],
>       [ [ 0, -1, -1 ], [ "subterranean_empty" ] ]
>     ],
> 

and this

>  "overmaps": {
>       "surface": { "overmap": "termitemound_north", "below": "surface_to_tunnel", "locations": [ "land" ] },
>       **"roof": { "overmap": "termites_roof", "locations": [ "roof" ] },**

that was the only changes i did to add the roofing so in theory the system should compute that if im giving it the coordinates and all. didnt submit this to issues because its more of a code hiccup rather than a gameplay bug. outside of this the system has been working as intended and the json files were checked properly according to Github.

**Comment by LeahLuong** [comment]
> didnt submit this to issues

Did, in fact, submit to Issues . . .

**Comment by new02DAY** [comment]
> > didnt submit this to issues
> 
> Did, in fact, submit to Issues . . .

I think they meant "submit as bug report", hence the formatting as a feature request.

**Comment by jbytheway** [comment]
That won't work as written because `roof` isn't an `overmap_location`.  Indeed, I don't see any existing suitable `overmap_location` you could use; you'll have to define a new one.  You can find them in `data/json/overmap/special_locations.json`.  Define one for the `open_air` OMT.  You probably want to call the location `open_air` (or similar) too, rather than `roof`, because it's supposed to describe what's there before the special is placed, not what you're planning to place there.

When you tried this, what happened?  You should have got an error message about an invalid `overmap_location`.  If you didn't (but instead it just failed to spawn, for example) then that's probably a bug.

**Comment by Xaritscin** [comment]
After discussion with jbytheway. it appears the issue generated because there's no reference of an open air location in the vanilla files. will open a PR For this case
