### ISSUE TITLE
'Broken But Not Defeated' achievement's broken limb detection is broken.

### ISSUE THREAD

**Issue by cataclysmsurvivalist** [CleverRaven/Cataclysm-DDA#54069]
### Describe the bug

Upon breaking a limb, any sort of damage that goes towards that limb are counted as 'breaking' the limb again. In my last run for example, I broke an arm and hit a zapper zombie without gloves on. Since my left arm was already broken, once I hit it, the achievement counted my left arm being broken 6 times, despite the fact that I only broke it once.

### Steps to reproduce

1. Make a character and break a limb
2. Get that broken limb hurt again in any way
3. Check the achievement menu, and you'll see it registering the limb as broken multiple times despite you only breaking it once

### Expected behavior

While I know that harming a broken limb when it's in the process of being healed can reset it, I don't think harming an already broken limb should be counted by the game. I only broke my left arm once, the damage just reset the healing.

### Versions and configuration

os: Windows 10
build type: windows-tiles-x64
build number: 2021-12-31-2003

**Comment by hexagonrecursion** [comment]
Confirmed

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 4d22129 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
