### ISSUE TITLE
Killing zombie children gives no morale debuff

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#54077]
### Describe the bug

When killing zombie children, there is no post-kill morale penalty.

### Steps to reproduce

1. Spawn a zombie child
2. End their existence with your own two hands
3. Don't be all sad about it

### Expected behavior

It should make you feel bad to kill zombie children.

### Screenshots

Killed a zombie child:

![image](https://user-images.githubusercontent.com/238395/148285073-480ee389-5cd2-4593-8c35-f94a97745d2b.png)

No morale effects:

![image](https://user-images.githubusercontent.com/238395/148285025-b91a9674-70f7-4ccf-a6b8-1fd5efa011fb.png)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-4927-ga1f0736ce2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by wapcaplet** [comment]
For comparison, the same scenario repeated in 0.F-3 - a "You feel guilty for killing the zombie child" message upon death:

![image](https://user-images.githubusercontent.com/238395/148285393-166db8e4-fa63-4aad-bb36-f76bb5de9aae.png)

And a morale penalty aferwards:

![image](https://user-images.githubusercontent.com/238395/148285404-05595d3a-a74a-4967-a712-cb1d0ec5c517.png)

**Comment by GoLoT** [comment]
It seems to be a regression caused by #49439. There is a block of code missing in `monster.cpp`:

```cpp
        if( ( has_flag( MF_GUILT ) && ch->is_player() ) || ( ch->has_trait( trait_PACIFIST ) &&
                has_flag( MF_HUMAN ) ) ) {
            // has guilt flag or player is pacifist && monster is humanoid
            mdeath::guilt( *this );
        }
```

It needs to be re-added here: https://github.com/CleverRaven/Cataclysm-DDA/blob/a1f0736ce23627911f124d50967f7fe79cf40eae/src/monster.cpp#L2464-L2465

**Comment by wapcaplet** [comment]
> It seems to be a regression caused by #49439. There is a block of code missing in `monster.cpp`:

Good catch, I was just coming to the same conclusion. Though, there's also this new part of `spell_effect::guilt` that seems to be saying *only monsters* can cause the guilt effect?

https://github.com/CleverRaven/Cataclysm-DDA/blob/a1f0736ce23627911f124d50967f7fe79cf40eae/src/magic_spell_effect.cpp#L1265-L1268

**Comment by GoLoT** [comment]
The old signature for the guild function was `void mdeath::guilt( monster &z )` so I guess that's trying to enforce the same creature type as before. Maybe the guilt from killing NPCs is hardcoded somewhere else.

**Comment by wapcaplet** [comment]
> `caster` is the creature that caused the spell effect. In this case it's the monster that died. In spell_effect::guilt() there is an aoe effect that finds all characters in range and applies guilt penalties to them. That part seems right although I'm not sure if it should only apply to the killer because this will make you feel guilty for hostile NPCs killing stuff around you.

Oh, I guess that makes sense then.

I did a `git bisect` and found that the above PR was not the cause of this regression - the first bad commit was 7ede3279 from #48340

**Comment by Testudo-Cultu** [comment]
> > `caster` is the creature that caused the spell effect. In this case it's the monster that died. In spell_effect::guilt() there is an aoe effect that finds all characters in range and applies guilt penalties to them. That part seems right although I'm not sure if it should only apply to the killer because this will make you feel guilty for hostile NPCs killing stuff around you.
> 
> Oh, I guess that makes sense then.
> 
> Yeah, getting penalized for NPC actions would be problematic.

I dunno, ever seen Breaking Bad? Jesse seemed pretty upset about Todd shooting a kid, and we all know Todd's an NPC.

Stupid jokes aside though, it always seemed strange to me that the only morale penalty you can get from zombie children is from killing them. 

I wouldn't know if it'd affect balance/gameplay, if at all really, but it would make sense to have a small morale penalty applied just from seeing zombie children too. After all, it's not like they're in a very good spot before you decide to run them over with your car or beat them with a stick.

**Comment by matshou** [comment]
Since death effects are no longer hardcoded this needs to be handled in JSON.
