### ISSUE TITLE
Basecamp NPC possibly considers some but not all rocks her property?

### ISSUE THREAD

**Issue by VoleurVolant** [CleverRaven/Cataclysm-DDA#54089]
### Describe the bug

I assigned an NPC to dig northwest trenches, and when she returned most of the materials unearthed were appropriately unowned (or owned by the basecamp? Not sure what the distinction is, I could pick up or haul the dirt and most of the rocks and all the pebbles and sand, that's the important part). However, one large rock and seven flaking rocks were not. Attempting to pick up any of those specific rocks, and none of the others, "will be considered stealing." 

### Steps to reproduce

I have no idea how this occurred or how to make it happen again. I assigned another NPC to dig a different trench earlier in this basecamp's lifespan and I can pick up every item from that excavation, so it certainly does not happen every time.

### Expected behavior

I expected that if I can "steal" any of the materials produced by a basecamp task, I should be able to "steal" all of them - that they should all have at *least* the same ownership flags. Ideally, I would hope that when I assign an NPC to produce materials for me, I would be allowed to have those materials, or that the NPC would comment on their decision to claim a portion of those materials in some way.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 21.2.1; Codename: Qonos; 
- Game Version: 0.F-4752-ga9de8720d0 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Extra Mutated Scenarios [extra_mut_scens],
    Mythical Martial Arts [MMA],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    SpeedyDex [speedydex]
]

**Comment by hexagonrecursion** [comment]
Hello. Please upload your save file. This may help troubleshooting even if the issue can not be reproduced reliably.

**Comment by VoleurVolant** [comment]
Unfortunately I have already stolen the rocks from Elodia in that game when she went to bed and I forgot to back up the save in which she owned them. I wish I had.

**Comment by hexagonrecursion** [comment]
Upload what you have anyway. Elodia may be bugged or unusual in some hard-to-guess way.
