### ISSUE TITLE
Debug errors when zombies fall down into a crater

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#54094]
### Describe the bug

I get debug errors (see below) when zombies fall down into a crater. Note that saving and reloading "fixes" this by filling the crater with dirt.

14:24:05.588 ERROR GAME : src/do_turn.cpp:412: game:monmove: zombie can't move to its location!  (69:76:-1), solid earth
14:24:05.590 ERROR : src/item.cpp:1400 [ret_val<bool> item::put_in(const item&, item_pocket::pocket_type, bool)] tried to put an item (tank_top) count (1) in a container (null) that cannot contain it: pocket with type (CONTAINER) not found

### Steps to reproduce

1. Find or spawn the "crater" mapgen extra.
2. Lead some zombies to fall in.
3. See the debug errors.

### Expected behavior

I expected to get no errors.

### Screenshots

![DeepinScreenshot_select-area_20220106142706](https://user-images.githubusercontent.com/52621858/148376092-347304b6-1648-486e-89cc-1c9895d24a3d.png)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 4d22129 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

### Additional context

```c++
14:24:05.588 ERROR GAME : src/do_turn.cpp:412: game:monmove: zombie can't move to its location!  (69:76:-1), solid earth
14:24:05.590 ERROR : src/item.cpp:1400 [ret_val<bool> item::put_in(const item&, item_pocket::pocket_type, bool)] tried to put an item (tank_top) count (1) in a container (null) that cannot contain it: pocket with type (CONTAINER) not found
14:24:07.361 ERROR : src/item.cpp:1400 [ret_val<bool> item::put_in(const item&, item_pocket::pocket_type, bool)] tried to put an item (under_armor_shorts) count (1) in a container (null) that cannot contain it: pocket with type (CONTAINER) not found
14:24:08.276 ERROR : src/item.cpp:1400 [ret_val<bool> item::put_in(const item&, item_pocket::pocket_type, bool)] tried to put an item (pants_cargo) count (1) in a container (null) that cannot contain it: pocket with type (CONTAINER) not found
14:24:08.761 ERROR : src/item.cpp:1400 [ret_val<bool> item::put_in(const item&, item_pocket::pocket_type, bool)] tried to put an item (lowtops) count (1) in a container (null) that cannot contain it: pocket with type (CONTAINER) not found
14:24:09.176 ERROR : src/item.cpp:1400 [ret_val<bool> item::put_in(const item&, item_pocket::pocket_type, bool)] tried to put an item (socks) count (1) in a container (null) that cannot contain it: pocket with type (CONTAINER) not found
```

**Comment by NetSysFire** [comment]
Related to #53549 and #53785. Possible duplicate? Never saw those debug logs in any of those issues

**Comment by hexagonrecursion** [comment]
This is a dupe of https://github.com/CleverRaven/Cataclysm-DDA/issues/53549. Sorry.
