### ISSUE TITLE
Basecamp (field): Parkour obstacle course overwrites northwest shack

### ISSUE THREAD

**Issue by VoleurVolant** [CleverRaven/Cataclysm-DDA#54093]
### Describe the bug

Basecamp obstacle course location intersects with other predetermined structures as seen in screenshot, replacing five walls and four floor/roof tiles with rubber mulch

### Steps to reproduce

Establish field base camp (type 1)
Assign npcs to build shacks for ages until you have the northwest one 
Assign someone to build the obstacle course
Hit recall and watch as the northwest shack immediately loses half its walls

### Expected behavior

I expected for hard-won wooden walls that were built by an npc to not be overwritten by another npc's rubber mulch floor

### Screenshots

![image](https://user-images.githubusercontent.com/94157027/148375108-c2e73947-decd-4452-8b12-1c1b89b1c12a.png)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 21.2.1; Codename: Qonos; 
- Game Version: 0.F-4752-ga9de8720d0 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Extra Mutated Scenarios [extra_mut_scens],
    Mythical Martial Arts [MMA],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    SpeedyDex [speedydex]
]

**Comment by NetSysFire** [comment]
CC @Maleclypse?

**Comment by Maleclypse** [comment]
Yes, I believe this has already been fixed by #53969.  That PR should make it so the Parkour course can only be built for the H shaped faction hub, I think.

**Comment by hexagonrecursion** [comment]
Conformed fixed. 3ff3369 is affected, but eacb7d9 is not.
