### ISSUE TITLE
Enhanced Memory Banks CBM does not prevent skill rust

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#54095]
### Describe the bug

The Enhanced Memory Banks CBM says it's supposed to prevent skill rust. It does not.

### Steps to reproduce

1. Start as Bionic Student on default world. Make sure skill rust is on.
2. Give yourself Debug Life Support and 5 in all skills. Eat some batteries and set your battery system to auto-activate. Turn on your Enhanced memory Banks.
3. "Wait until night" repeatedly until it's about 8pm on day 63
4. Note that your skills start to rust
5. Repeat with the memory banks turned off, and with a character that doesn't have the CBM at all to confirm there's no difference.

### Expected behavior

The CBM does what it says it does.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: a1f0736 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

I'd guess this is related to splitting xp into practical/theoretical, but that is strictly a guess.

**Comment by eturner** [comment]
Seems that way to me as well
