### ISSUE TITLE
"If this is intentional, set the ALLOW_ON_OPEN_AIR flag on the furniture" when hordes are smashing houses

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#54092]
### Describe the bug

For testing purposes, I made a world with the population density of 50. I get some errors when the resulting hordes smash walls, causing buildings to collapse.

### Steps to reproduce

1. Create a world with 50x more monsters or just spawn a horde in a city.
2. Either randomly walk around or stand behind a building and yell, so the undead feel motivated to reproduce that bug for you.
3. Randomly get errors when buildings collapse.

```
 DEBUG    : Setting terrain t_open_air at (32,114,1) where furniture is f_chimney.  Terrain is_open_air
If this is intentional, set the ALLOW_ON_OPEN_AIR flag on the furniture

 FUNCTION : bool map::ter_set(const tripoint&, const ter_id&)
 FILE     : src/map.cpp
 LINE     : 1740
 VERSION  : 0.F
```

### Expected behavior

No error, I guess. I think when tiles collapse, the code should check for furniture, smash it and put the resulting items beneath the rubble on the ground.

### Versions and configuration

- experimental

**Comment by NetSysFire** [comment]
This also happens in pure wilderness when encountering craters

**Comment by PatrikLundell** [comment]
#56242 is another variant of this. In that case, fire caused the collapse.

I've encountered the crater issue when some item was generated on top of the smashed terrain. However, I think that is a case that can be dealt with using the flag system, while dynamic changes that cause a collapse can't be handled by mapgen flags.
