### ISSUE TITLE
Dropping should be interrupted when the enemies get dangerously close

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#54091]
### Describe the bug

Dropping items is not automatically interrupted when the enemies get dangerously close to you.

### Steps to reproduce

1. Wear a hiking backpack
2. Debug wish for 100 splintered wood
3. Spawn a zombie 30 tiles away from you
3. Notice that you do not get interrupted when the zombie gets dangerously close
4. The first automatic interruption is "Ouch, something hurts! Stop dropping?"

Alternatively:
1. Load the attached save file: [tmp.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7821270/tmp.zip)
2. Drop the 218 splintered wood under your feet
3. Notice that you do not get interrupted when the zombie gets dangerously close
4. The first automatic interruption is "Ouch, something hurts! Stop dropping?"

### Expected behavior

I expected dropping to work the same way as waiting, crafting and many other activities: if enemies get close, I get interrupted before they start attacking me

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 4d22129 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

### Additional context

Possibly related: https://github.com/CleverRaven/Cataclysm-DDA/issues/50979

**Comment by wapcaplet** [comment]
Confirmed; the drop don't stop until I get grabbed and bit:

![image](https://user-images.githubusercontent.com/238395/148628495-6101a2da-8247-4dd5-b357-b9f05e36fee2.png)

After I stop dropping, the zombie gets a bite, claw, and hit on me:

![image](https://user-images.githubusercontent.com/238395/148628520-a51854d0-727a-4189-9d31-c307cbcfc072.png)

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-5043-g9b986bb5a2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by hexagonrecursion** [comment]
I can reproduce this in 119e2fe, but not in f7e3308. This bug appears to have been fixed. Thanks.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 119e2fe [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: f7e3308 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
