### ISSUE TITLE
Add a propane torch

### ISSUE THREAD

**Issue by ISuckM8** [CleverRaven/Cataclysm-DDA#54109]
### Is your feature request related to a problem? Please describe.

We have propane now, but nothing that uses it.

### Solution you would like.

Add a propane torch that could be used for welding and metalworking ingame.

### Describe alternatives you have considered.

None.

### Additional context

![PropaneTorch-JumboFlame-700x700](https://user-images.githubusercontent.com/87550905/148440331-de824a58-bf9c-4258-ae21-c11d5c0c8d14.jpg)

**Comment by Drew4484** [comment]
You could start with the existing gasoline lantern and gasoline cooker to make propane versions of those, a torch would be similar to the acetylene torch. Mostly a matter of changing the fuel and magazine.

**Comment by ISuckM8** [comment]
I don't really have the time to make PRs nowadays, only future requests. 

I will try to make a propane torch when I have the time. No promises though, pretty unlikely.

**Comment by Drew4484** [comment]
#54143 resolves this.

**Comment by wapcaplet** [comment]
> #54143 resolves this.

Agreed; while that PR doesn't add the specific kind of torch pictured (commonly used for brazing/soldering in plumbing), it does add several other well-designed propane tools for cooking, lighting, and forging metal.

**Comment by Drew4484** [comment]
Oh actually there is supposed to be a burner torch that didn't get in the commit. I'll add it to the next batch.
