### ISSUE TITLE
Add a distinction between new a used Casings for handloading 

### ISSUE THREAD

**Issue by scavtoons** [CleverRaven/Cataclysm-DDA#54103]
### Is your feature request related to a problem? Please describe.

I've noticed that all ammo that the player makes is the same even when the bullets were pulled out manually or the casings were found in a store shelf, so it would be good to have a better final product when crafting if you use brand new casings. Having a distinction between used and new casings would make easier to have better ammo crafted by the player.

### Solution you would like.

Add a different item variant for casings when they're not used, and add recipes for new handloaded ammo.

### Describe alternatives you have considered.

Add measurement tools and a recipe for checking casing status with a fixed failure value to produce checked quality casings.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
