### ISSUE TITLE
Stores like grocery shops and mil. surplus needs a loot buff

### ISSUE THREAD

**Issue by ISuckM8** [CleverRaven/Cataclysm-DDA#54107]
### Is your feature request related to a problem? Please describe.

Currently, looting a grocery store is a waste because most of the time (94% of the time actually) they're gonna be looted. Hardware stores are mostly unlooted but they don't have much (Real-life hardware stores have a lot more supplies).

### Solution you would like.

Decrease the looted rate to 70% or so, and make it so the looted variants have more items to loot.

### Describe alternatives you have considered.

Since there were riots before the cataclysm, houses should have a high chance of having basements with food and military surplus equipment.

**Comment by Zireael07** [comment]
+1 to basements with food. Also looted stores shouldn't be as empty as they are.

**Comment by Jan-Blasiak** [comment]
I absolutely agree, over 5 ILR months of playing I've only seen two unlooted mil. surp.

**Comment by Night-Pryanik** [comment]
It's intended that stores in overwhelming majority of cases are looted. Unlooted store should be considered as an extremely rare gift of fortune, not an ordinary event. And no, 70% chance is still an ordinary event.

**Comment by ISuckM8** [comment]
> It's intended that stores in overwhelming majority of cases are looted. Unlooted store should be considered as an extremely rare gift of fortune, not an ordinary event. And no, 70% chance is still an ordinary event.

Then add basements with god knows how many cans of food and lots of mil. surplus equipment What? Things don't disappear out of thin air like that.

Plus, even a looted grocery store should have at least a handful of canned goods lying around, It's not common for a looted grocery store to be completely empty in real life.

**Comment by Night-Pryanik** [comment]
> Then add basements

Go ahead and add them, I'm not against.

> god knows how many cans of food

Eaten in time period between looting and the game start.

> lots of mil. surplus equipment

There already several types of basements which contain a decent amount of mil. surplus equipment. One may say some of it was looted from stores.

> Plus, even a looted grocery store should have at least a handful of canned goods lying around, It's not common for a looted grocery store to be completely empty in real life.

Two, three, ten, dozen waves of desperate - and hungry! - people came through the store. I doubt there would be but a single can of food left unattended.

**Comment by ISuckM8** [comment]
> Go ahead and add them, I'm not against.

I made this a feature request for a reason.

> Eaten in time period between looting and the game start.

Unlikely, they would've either died or went through perishable things first

> There already several types of basements which contain a decent amount of mil. surplus equipment. One may say some of it was looted from stores.

Yeah, but how common are they? Pretty rare, man. Rarer than what they need to be if they're supposed to represent looted mil. surplus stores.

> Two, three, ten, dozen waves of desperate - and hungry! - people came through the store. I doubt there would be but a single can of food left unattended.

Yeah, desperate. They won't be able to get every can of food, some might fall below the shelves and some people might ignore things like wet cat food and butter.

**Comment by NetSysFire** [comment]
I agree on the wet cat food and butter thing, but this is the Cataclysm, where we drink mustard.

**Comment by Night-Pryanik** [comment]
> if they're supposed to represent looted mil. surplus stores.

No, they ain't supposed. I didn't say "these basements contain ALL loot from the stores", I said "some of it". 
I personally think that most of the loot from the stores went to criminals, bandits and bands of marauders rather than solitary survivors. And it must be stored in some sort of bandits' camps rather than in basements.

> wet cat food and butter.

Ok, imagine we add wet cat food and butter to the list of loot for looted grocery stores. Would wet cat food be a good reason for you to go to these stores?

**Comment by ISuckM8** [comment]
> No, they ain't supposed. I didn't say "these basements contain ALL loot from the stores", I said "some of it". I personally think that most of the loot from the stores went to criminals, bandits and bands of marauders rather than solitary survivors. And it must be stored in some sort of bandits' camps rather than in basements.

over 99% of the population died during the cataclysm, including most criminals. Just because you're a criminal doesn't mean you get to survive in the cataclysm

> Ok, imagine we add wet cat food and butter to the list of loot for looted grocery stores. Would wet cat food be a good reason for you to go to these stores?

Better than absolutely nothing

**Comment by Night-Pryanik** [comment]
It seems that you have wrong picture about duration of the pre-Cataclysm events. Riots, civil unrest, and subsequent marauding started no less than 9 months before the start of the game. First wave of looting grocery stores and mil. surplus stores occurs. 

One may say that 9 months before the Cataclysm all production has stalled. No one produces food anymore. Perishables were eaten at most week after that. The only food source (for urban citizen) is canned products or taking food from dead hands of other survivors. Second wave of looting stores in a hope that first wave might have missed something.

Months are passing by, people are eating what they managed to loot from shops and stockpile in their basements or somewhere else. These supplies eventually end, and people are moving to previously looted shops once again. It's a big luck if they manage to find a single can of cat food.

People were dying through this period, sure, but number of survivors are still much bigger than 1%. Even 1% of 140-millions population of IRL New England is 140'000, and that's a big number. And all these people want to eat, and many of them are still trying to find something to eat in a n-wave of looting the same shops.

Fast-forward. Cataclysm. Game start. Dozens of looting waves passed, picking every single shop in the vicinity clean. Most of the houses are looted too, including their basements. Only big communities still have something to eat in their stockpiles.

These are my arguments. I simply don't understand how it's be possible to have any loot, even of a slightest value, in any store that weren't picked up by other survivors during, I repeat it once again, previous 9 months.

**Comment by ISuckM8** [comment]
Explain how restaurants still have food that only lasts for a week or two, milk doesn't last for 9 months, man. That, and the riots started occurring only a month ago, the blob escaped 9 months ago though.

**Comment by Night-Pryanik** [comment]
Ok, I admit, I forgot about new lore, which I wholeheartedly hate. All my arguments were about old lore.
Disregard all that I said, I'm out of this.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
