### ISSUE TITLE
Subdivide the "Drugs" category

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#54105]
### Is your feature request related to a problem? Please describe.

The "drugs" category is hard to get an overview of and pretty annoying to sort, both automatically and manually. It contains items that belong to many different categories, and usually many different items for each category. But you can't filter for those categories, so the only thing you can do for both autopickup and manual sorting is to go through the items individually, and it gets very tiring.

### Solution you would like.

Divide up the "drugs" category. Perhaps some form of "subcategory" system would be desirable, but otherwise I think it's fine to make it new categories entirely. Here are a couple of categories I would find helpful:

- Bandages
- Disinfectants
- Painkillers
- Medications (cough syrup, antibiotics)
- Supplements (multivitamins, injectable iron)
- Recreational (cocaine, marijuana)
- Prophylactics (flu shot, potassium iodide)

If we don't want to do half a dozen categories, I think we could at least stand to separate the trauma medicine (bandages, disinfectants and painkillers) from the rest.

### Additional context

![image](https://user-images.githubusercontent.com/5107449/148427337-3caa5990-e8c7-422f-b183-9dc45c08b6b8.png)
This is particularly egregious because I've got a lot of strength and haven't once tried to clean up my drugs, but it illustrates the fact that items that you want to consider together, such as bandages and medical gauze, are in completely different places. Codeine and Tramadol are basically on opposite sides of the screen.

**Comment by LeahLuong** [comment]
This kind of seems like 1st world problems:

"My painkillers are SO far apart when organized alphabetically that I don't have the 'strength' to deal w/ it!" Maybe if you sorted your list by weight, volume, or quantity they'd be closer together. Maybe you could break things up spatially so your trauma meds don't crowd out your eyespace for funtime drugs. I mean, nothing's stopping you from designating a specific space for frequently used items.

When it comes to item categorization, I think there are more pressing problems like chemical stuff & vehicle parts ending up in spare parts. The "Other" category is kind of a catchall for items that prob do belong in 1 of the other categories. I think there are bigger fish to fry considering the organization options currently available for this particular issue. "This ain't it, chief."

**Comment by ZhilkinSerg** [comment]
You can add new item categories via mod.

**Comment by Terrorforge** [comment]
> "My painkillers are SO far apart when organized alphabetically that I don't have the 'strength' to deal w/ it!"

Yes, I do in fact have brain problems that make this sort of thing difficult to deal with, thanks for noticing.

> Maybe if you sorted your list by weight, volume, or quantity they'd be closer together. 

I'm not tired of scrolling or whatever you think my problem is, I want to be able to get an overview of what I'm carrying and quickly and easily do things like sort items into various containers and quickly dump stuff I don't need.

> Maybe you could break things up spatially so your trauma meds don't crowd out your eyespace for funtime drugs. I mean, nothing's stopping you from designating a specific space for frequently used items.

No, I cannot, because I'm talking about my inventory, not sorting zones. And even if it wasn't, what do you expect me to do? Create a custom zone where I call out all of the dozen or so relevant items by name, individually? That's exactly what I'm sick of doing.

> When it comes to item categorization, I think there are more pressing problems like chemical stuff & vehicle parts ending up in spare parts. The "Other" category is kind of a catchall for items that prob do belong in 1 of the other categories. 

You're acting like this is some kind of massive undertaking. The minimum size of this is changing the category of like a dozen items.

Also, maybe I'm missing something, but in my personal experience the other categories don't need reorganizing nearly as much. I have never once looked at my chemicals and thought "man, I really wish this were divided up differently", because all that stuff just goes in the crafting pile. With drugs, organization and clarity actually matters because you need to separate the ones you want to carry with you and the stuff you just drop in your car/base.

> I think there are bigger fish to fry considering the organization options currently available for this particular issue. "This ain't it, chief."

What options? The lack of good organizational options is precisely my complaint. The ones that exist are either obnoxious to use because you have to call out each relevant item by name, or straight up do not work at all, like setting a pocket to autopickup antiseptic.

**Comment by Maleclypse** [comment]
Prophylactics (flu shot, potassium iodide) this one would really help new players as to when they should take things.

**Comment by LeahLuong** [comment]
@Terrorforge Pardon me for not presuming your "brain problems" would interfere w/ reasonable discussion. By the same token, please do not assume I'm a mindreader. Nowhere in your original post did you state these were invo problems; you seemed to be talking about general item management & categorization. This is why I offered advice on options for dealing w/ those issues.

When it comes to your invo, that looks like it could really use some tidying up! I generally only carry a very small amount of drugs (or anything, really) so I have more capacity to pick up other stuff. Hemostatic powder, antiseptic powder, a handful of painkillers (usually tramadol), & an inhaler if I'm not rocking a gas mask in case I breathe smoke. That's it. Bandages are too slow-acting to warrant bringing them into the field & practically all other meds are the same. If I get into a situation where I need to bandage or purge fungus/parasites,  it's time to retreat to my cache of supplies. If you did the same, you wouldn't have to deal w/ such a crazy invo list.

This game features a lot of invo management but you don't have to do all of it w/ your char's pockets.

**Comment by jiornojiovanni** [comment]
Personally i would create another category for recreational drugs, because while you use normal drugs to affect positively your character health and hp, you use the recreational ones to affect the mood, so having them mixed up is a bit weird.

**Comment by OptimisticNihlist** [comment]
Could there be subcategories? I don't think that's a feature at the moment but that would be a nice feature for many things. i.e. Ammo, guns divided into rifle, pistol, shotguns, launchers...
