### ISSUE TITLE
Items/liquids in bottles ignore pocket autopickup setting

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#54104]
### Describe the bug

If you whitelist an item in the pocket autopickup settings, and pick up a bottle containing only that item, it will not be put in that pocket. This causes problem with most medications for example, but it's particularly bad for liquids like Antiseptic, which can't be auto-sorted at all.

### Steps to reproduce

1. Spawn antiseptic (in bottle)
2. Spawn two items with pockets.
3. Set one with high priority and antiseptic whitelisted
4. Pick up bottle of antiseptic

### Expected behavior

All items can be sorted.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 3c42e07 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by hexagonrecursion** [comment]
Confirmed: the whitelist checks the container (small plastic bottle) instead of the contents (antiseptic)

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 0d43a6e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Graphical Overmap [Graphical_Overmap]
]
