### ISSUE TITLE
Rebalance the spawn rates of Martial Arts books in locations to more reasonable, realistic and logical rates

### ISSUE THREAD

**Issue by cataclysmsurvivalist** [CleverRaven/Cataclysm-DDA#54106]
### Is your feature request related to a problem? Please describe.

It's true that if the spawn rate of martial arts books is too high, it could break the early game. However, settling it at sub 20% is far too low and makes searching for them a nightmare, especially weapon-based ones, given that they don't really have a specialized place to find them other than the Barbaran Montante in mansions. What's more, most martial arts are completely nonsensical in their location rates.

The reason I believe some should be higher isn't even because it's annoying in and of itself. Rather, it's because at the current rate, dojos _aren't_ the most reasonable place to learn martial arts. It's military bases. Because even if the spawn rate for them is ridiculously small, bases are so huge that they're more likely to have at least one book lying around.

Oh, and they're MORE likely to have Official Taekwondo Training Manuals than dojos. I'm sorry but since when has the game been taking place in Seoul? Unless I am terribly behind in the lore, the military forces that operated in the cataclysm weren't Korean.

I think I understand the reasoning behind it; that is, martial arts as they currently are have no limitations or Proficiencies tied to them that slow down your growth when using them, so having too many martial arts mastered by one character could lead to him changing styles willy-nilly in the middle of combat without ever having to master each individual style, which is unrealistic and would make combat less interesting or fun as a result, so I don't expect the rate to be changed immediately, at least not as it is. What's more, you already have options to give you certain martial arts at the beginning of the game, so if it was too easy, those traits would become useless.

But the devs already talked about making martial arts more immersive through other gameplay mechanics such as adding Proficiencies to them (though I'm not a part of the development team so those rumors might not be 100% accurate), and the traits for martial arts don't cost a lot of points, so it's clear that they're not meant to be overpowering. So in the future, I hope increasing the rates to more reasonable amounts is considered while balancing martial arts.

### Solution you would like.

(All rates below are rough estimates, as I know the game rarely ever uses exact numbers when randomizing item spawns.)

-Martial arts styles that are already "native" to dojos at reasonably high rate (Judo, Karate, Taekwondo, Tai Chi) should have a significantly higher rate. Judo, Taekwondo and Karate should have a priority over any others, as the dojos are clearly designed with them in mind, given the kimono and gear that are found in them. Those three should be at 19% rate (from 16%), while Tai-Chi should be at 15% (from 13%).

-The Shotokan Karate Handbook should **not** be found in boxing gyms. It's true that karate punches synergize well with boxing in real life, but then again, so does Pankration (MMA) and Muay Thai. The fact that they hybridize well together is not good reasoning compared to other martial arts, as the two martial arts do not have a history together that is notable enough.

-Instead, Pankration and Muay Thai should replace Karate as styles that could be found in boxing gyms. While Karate has been noted to work well with Boxing on occasion, Muay Thai and Mixed Martial Arts have a far greater and well-documented history of complimenting boxers and pugilists. Ultimate Muay Thai should be found at a 4% rate (from 1%), same with The Modern Pankratiast.

-Boxing itself should be found at a 28% rate in boxing gyms (from 25%)

-ALL weapon martial arts that can be found in mansions (Medieval Swordsmanship, Barbaran Montante, Fior Di Battaglia, Fencing, Niten Ichi-Ryu and everything in-betweeen) should be found at a 3% rate. This would be an upgrade to most of them, **except** Barbaran Montante, which would be downgraded from the comparatively massive 8% rate it had before. I don't really understand why Montante was chosen as a special martial art to be found in mansions, but it doesn't really fit any more than all the other medieval styles (well, other than Niten Ichi-Ryu of course).

-Speaking of 8%, teashops should have a far less lower rate at which they house The Modern Swordsman. I get the classy gentleman = rapier wielder comparisons, but not only is it funny to even picture a teashop being a home to a bunch of sword-wielding butlers, but it doesn't even make a lot of sense anyways. Teashops are more stereotyped to British and Chinese customs, both cultures which historically preferred slashing sabers over thrusting rapiers, and the Fencing portrayed in-game is clearly drawn from French and Spanish schools of thought. A 2% or 3% rate is more than fair enough for it.

-Museums should also be places where you can find books on weapon-based fighting style. Medieval Swordsmanship should be at the top of the priority, as it is so generic it's clearly meant to represent all European infantry with no set focus on any one country or culture's history. Historic European Swordfighting should be found in museums at a 10% rate, with all the other weapon styles being found at a 3% rate.

-The rate at which you find The Modern Pankratiast and The Book of Five Rings in random homes should be raised from 0.01% to 0.03%, to signify the possibility of any houses once belonging to weeaboos or romaboos. More "mainstream" popular martial arts shouldn't ever be found in houses at all, since practitioners of those styles would be going to gyms or dojos to practice instead of studying them at home.

-And lastly, for military bases, Taekwondo should be replaced with Judo and Karate as martial arts that can be found there, both of which are styles that are far more common in the American armed forces for close quarters combat training than Taekwondo.

**Comment by Zireael07** [comment]
Agree with everything except second to last.

**Comment by PatrikLundell** [comment]
I agree with Zireael07. I don't have any first hand experience, but I'd expect somewhat serious martial arts practitioners to study at home and practice at their institutions. Less serious practitioners may settle for just the practice and replace study with instructions from instructors.

**Comment by epsimpson** [comment]
I, on the other hand, disagree with Zireael07.  The logic is backwards.  The curious look at books, the serious enter a dojo.  In all my years doing judo competitively, good enough to go to nationals annually, I never owned a single book on the topic.  I've borrowed a very few, but never for techniques.  I've had some videos, but only of workshops I've attended.  I am not aware of anybody in my dojo using books for anything other than philosophy, and that only really helps after you have reached a certain level.  In reality you're not going to learn it from a book anyway, so *any* logic you use to decide where to put the books is going to be artificial.  Look for places where either some sort of stereotypical fan might frequent, or alternatively for the *last* place you might expect it - such as an oddly preferred style for an underground fight club for computer geeks, and leave fliers or survivor notes hinting about it.  So for me, in this case, seek humorous references and anti-references more than "reality".

Try not to force everything to "make sense".  That's boring.  Sometimes things just are.  So in that vein, I'm good with the odd high rates, such as the tea shop, though 8% seems really high.

I love the thinking about where to find them, just please don't boost rates too much.  It should be insanely hard to collect them all, and if you want to play a particular style then pay for it up front.  From a realism standpoint, the idea of training out of a book, passing a test after a few hours of trying, and you're suddenly an expert at the exact level of your previously achieved melee and unarmed combat skill, is ridiculous and cries out for proficiencies.  From a game play perspective, the chances of finding a useful one is very low, and maybe that is as it should be.  The last thing I'd want is for cdda strategy to turn into a Kingdom of Loathing type thing - go to A and get x, go to B and get y, go to C and get z, every day planned out to maximum efficiency based on the number of turns you can expect to spend looking for each drop.

**Comment by Zireael07** [comment]
I mostly disagreed with the idea of increasing the Pankration spawn in houses (this is a very niche thing)

More MMA books in houses actually make sense due to what @epsimpson said (beginners having them to figure out what even is that thing).

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
