### ISSUE TITLE
Taekwondo and "force unarmed" attacks cost stamina based on wielded weapon

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#54117]
### Describe the bug

The stamina cost of unarmed attacks while using Taekwondo or Force unarmed is based on the object you are wielding, even though you're not attacking with it.

### Steps to reproduce

1. Select "Force unarmed" and/or "Taekwondo"
2. Wield something heavy
3. Attack

### Expected behavior

Unarmed attacks have unarmed attack stamina cost

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 3c42e07 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Extra Mutated Scenarios [extra_mut_scens]
]

### Additional context

I'm not 100% sure this actually qualifies as a bug, since you do still have to hold and deal with whatever you're holding. But just holding your heavy backpack while kicking should probably exhaust you less than swinging it around, and from a mechanical standpoint this further limits the utility of these already quite narrow options.

**Comment by LeahLuong** [comment]
It looks like #53954 may address this issue among others but you may want to check on it or pipe in if you feel it won't. Consider closing this issue if it's redundant.

**Comment by Venera3** [comment]
Force unarmed is a bit weird in general. In `melee_attack_abstract` considers you unarmed for most things (it checks the style forcing you unarmed), but stamina cost is outsourced to `Character::get_standard_stamina_cost` which explicitly checks your *wielded* item.
