### ISSUE TITLE
Bionic shotgun (Shotgun Arm CBM) can't fire reloaded dragon's breath shells

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#54136]
### Describe the bug

When shooting dragon's breath shell, reloaded out of the bionic shotgun, you just get projectiles that deals zero-damage "grazing" and no fire. Regular Dragon's Breath works.

At a guess, something to do with the -damage mod of the bionic shotgun crossing some kind of threshold with the reloaded damage modifier?

### Steps to reproduce

1. Have bionic shotgun
2. Attempt to shoot reloaded dragon's breath

### Expected behavior

The fire happens.

### Screenshots

![image](https://user-images.githubusercontent.com/5107449/148555622-38a4ac56-0e11-4ce4-8b1a-e791a3f9425c.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 3c42e07 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Extra Mutated Scenarios [extra_mut_scens]
]

### Additional context

While testing this, I discovered that the damage penalty of the bionic shotgun seems to be applying on a per-pellet basis, and -11 is therefore really harsh. Is that intended?

**Comment by catdach** [comment]
It's possible that the bionic shotgun was overlooked in the recent shotgun ballistics overhauls. Not sure why the -11 penalty is there to begin with though.

**Comment by Terrorforge** [comment]
The comments imply it's because it's got a short, six-inch barrel. Idk enough about shotgun ballistics to comment on that, but as I mentioned it's _much_ more severe penalty now, so it could probably stand to be adjusted.

The 12 gauge pistol also has a -5 damage penalty, which is also much more severe now, though not nearly as crippling.
