### ISSUE TITLE
"Asked to train" effect

### ISSUE THREAD

**Issue by ZeWoll** [CleverRaven/Cataclysm-DDA#54142]
### Describe the bug

I can see the "Asked to train" effect which says that I shouldn't be seeing it.

### Steps to reproduce

Ask a NPC to train you

### Expected behavior

I shouldn't see that effect

### Screenshots

![image](https://user-images.githubusercontent.com/88143686/148587376-ce8278fc-8a74-49ac-994a-69886800ca73.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 1793043 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by NetSysFire** [comment]
Can you provide your save?

**Comment by ZeWoll** [comment]
[Candice.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7832840/Candice.zip)

But the problem is that I continued playing a bit, I'll try to recreate the problem meanwhile.

**Comment by ZeWoll** [comment]
[Candice.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7832846/Candice.zip)

Alright, the NPC has the same tag now, after asking him to train me and failing the persuasion check, which isn't exactly the same problem.

**Comment by ZeWoll** [comment]
![image](https://user-images.githubusercontent.com/88143686/148636928-aaa6c04b-f88a-4ed2-b874-5904ffa65d1e.png)

After training the NPC, the same effect appears.

**Comment by Maleclypse** [comment]
Closed by #55468
