### ISSUE TITLE
Add welding mask spawns to the junkyard

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#54141]
### Is your feature request related to a problem? Please describe.

Junkyard currently spawns welding carts, but it does not spawn welding masks or goggles.

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/mapgen/junkyard.json

### Solution you would like.

Add welding mask spawns to the junkyard.

**Comment by new02DAY** [comment]
Maybe just bad RNG luck?

Goggles are supposed to spawn with a 30% chance with the cart. Found in vehicles/carts.json under welding_cart, line 200.
`"items": [ { "x": 0, "y": 0, "chance": 30, "items": [ "goggles_welding" ] } ]`
Also, in the tools_mechanic group, (line 46-47 in mapgen/junkyard.json
`{ "chance": 20, "repeat": 2, "item": "tools_mechanic", "x": 26, "y": [ 10, 12 ] },`
`{ "chance": 20, "repeat": 2, "item": "tools_mechanic", "x": 26, "y": [ 6, 8 ] },`

**Comment by hexagonrecursion** [comment]
Sorry. It does indeed spawn - just very rarely.
