### ISSUE TITLE
Variable intensity and directional lights

### ISSUE THREAD

**Issue by new02DAY** [CleverRaven/Cataclysm-DDA#54151]
### Is your feature request related to a problem? Please describe.

I was messing around with the smartphones, and I discovered that we don't have the ability to change light intensities from a device already emitting light. Similarly, the way the game treats flashlights is more similar to lanterns. It'd be great if we could define multiple light intensities per item (ie. multiple `transforms`, per #50277) and have optional directional lights.

It'd replicate how more modern flashlights work (multiple intensities, with directional functions). Some have reading light intensity and area, then lantern/flood, and high-powered directional (https://www.511tactical.com/au-en/response-hl-xr1.html).

### Solution you would like.

Multiple light intensities and directions. Either multiple `transforms` or `use_actions`. Ex. smartphone>smartphone (screen on)>smartphone (flashlight). This would also allow for different intensities with the current items (ex. lanterns), which could make charge cost variable, depending on player needs. With variable intensities, lanterns could last longer in a "reading light" mode compared to a "flood" mode.

### Describe alternatives you have considered.

Working with the current system of different items.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
