### ISSUE TITLE
[Aftershock] Stranded spacer : Spawned overmap tiles away from the pod

### ISSUE THREAD

**Issue by Zeropol** [CleverRaven/Cataclysm-DDA#54157]
### Describe the bug

I started a "Stranded spacer" scenario and spawned inside a ( locked ) house, 4 overmap tiles away from the escape pod.

### Steps to reproduce

I did not tried to reproduce, sorry.
I uploaded the savegame just in case this world is kinda specific. Most worlds options should be default. ( in particular, towns size and spacing are )

### Expected behavior

I expected to spawn on the same overmap as the escape pod.
Because it is was I'm used this scenario do.

### Screenshots

![image](https://user-images.githubusercontent.com/28099824/148625223-c358414d-9e9c-49ab-b41b-2046650175f4.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: cfafb47 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    No Hope [no_hope],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

It is the first character on a freshly generated world.
[Southborough.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7832086/Southborough.zip)

**Comment by John-Candlebury** [comment]
Yeah I can confirm this happens every now and then.

No Idea what causes it. However
