### ISSUE TITLE
Updating Narcolepsy Trait

### ISSUE THREAD

**Issue by ChrisGarrett23** [CleverRaven/Cataclysm-DDA#54161]
### Is your feature request related to a problem? Please describe.

As a Narcoleptic, there's a lot more than a die roll going on to determine your awake levels and I thought it would be interesting to break it out and implement some actual functionality to better represent this disease.

### Solution you would like.

Changing the Narcoleptic trait into two types, Catatonic and non Catatonic to better represent the disease. Also adding stimulates as a form of treatment, but timing is important.

### Describe alternatives you have considered.

Not making changes, or only doing Catatonic Narcolepsy, but I felt we should represent both correctly if we're going to do either.

### Additional context

There are primarily two forms of Narcolepsy, Catatonic Narcolepsy and non Catatonic.

Non Catatonic is essentially no matter how much rest you get, after a short amount of time you're tired again. As this continues without rest your focus drops drastically and at extremes hallucinations are possible as well. You may unintentionally fall asleep during moments of inactive actions such as reading, but it's unlikely during something like Driving even if you're very fuzzy. Think about it like going through life with bubble wrap duct taped to your head, everything is fuzzy and distant.

Catatonic is what we see in movies, someone just passing out. However this is significantly more likely during moments of types of stress. It absolutely can happen for no reason at all but more often than not it's related to a low Morale (in game turns) and can be triggered by many things without treatment.

-Treatment: responsible and regular use of stimulants can help just like an inhaler with Asthma, but it can easily go off by miss timing doses and such.

**Comment by Terrorforge** [comment]
Are stimulants the treatment for for both types?

**Comment by Maleclypse** [comment]
I think this would require c++ but it might be possible with the effect on condition system?

**Comment by ChrisGarrett23** [comment]
> Are stimulants the treatment for for both types?

Stimulants are a treatment often using in tandem with Sodium Oxybate (aka 'Ruffies') as treatment for both. The reason for Sodium Oxybate is that a Narcoleptic never hits the cycle of sleep that refreshes the mind, instead they immediately go to stage 4 of REM sleep where the brain is more active. Often times a narcoleptics brain is more active while asleep than it is while being awake. There's not really a stage 1-3 of sleep without Sodium Oxybate.

I'd also consider that Cataplexy would include potential damage from falling as well. Check out youtube for lots of interesting videos of people having cataplexy episodes to see how they are slightly aware right before falling.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
