### ISSUE TITLE
gfx/layering.json is not valid json

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#54167]
### Describe the bug

```
"item_variants": [

]
```
Should be:
```
{
  "item_variants": [

  ]
}
```

### Steps to reproduce

Just look at https://github.com/CleverRaven/Cataclysm-DDA/blob/610e7d5502c3571e36a9363e4eec1d8801af451b/gfx/layering.json
This is not correct rfc8259 JSON. Even if your parser swallows it fine, other parsers will reject it

### Expected behavior

Be rfc8259 compliant

### Versions and configuration

N/A

**Comment by leemuar** [comment]
@bombasticSlacks could you please look at this as an original commit author?

**Comment by bombasticSlacks** [comment]
this isn't actually parsed it's just an example file, however it should be an example file that actually works.  No one has ever tested it so good eye catching this issue.

**Comment by Maleclypse** [comment]
I'm sorry guys I don't know how to label this.  Any suggestions?

**Comment by bombasticSlacks** [comment]
Documentation + JSON would be what I lean to. It's a file that is a skeleton for people to use.

Also I'll fix this tomorrow I just had a bunch of other stuff I was focused on.
