### ISSUE TITLE
Improved sidebar sound meter

### ISSUE THREAD

**Issue by matshou** [CleverRaven/Cataclysm-DDA#54165]
### Is your feature request related to a problem? Please describe.

Currently it doesn't seem to be possible to see the noise level of an action that takes longer then a single turn to complete.

This is clearly visible when moving heavy furniture:

![cataclysm-tiles_CnMaCz3bFb](https://user-images.githubusercontent.com/16436920/148637564-048cb45c-6117-4bf5-b132-8d4c66975c6c.gif)

### Solution you would like.

Sound indicator should display the volume of **last action** performed by the player instead of the volume produced last turn.  
This would make it possible to easily see how loud our last action was.

**Comment by nexusmrsep** [comment]
Actually recent sounds made and their source should be logged into either:

- a separate log visible to player
- silently (no clutter) to standard output log, where they could be then displayed via a "show sounds" option etc.

**Comment by matshou** [comment]
Could you explain further how the *silent* output log and "show sound" option would work?
It would be fairly easy to print all sounds to the standard log but as you say that would clutter the log most of the times.

**Comment by nexusmrsep** [comment]
Even now code supports different kind of message types: info, warning, etc. One of them is debug which is only shown when debug status is on. My proposed solution is not entirely analogical, but let's say there would be a new type "silent" message, and the default sidebar display would ignore it but the message log would not. Then for every event when PC makes a non zero sound that normally is pushed to the sound widget, let's push it also to the silent message, in a form of let's say "Sound: [number] (reason)". It can be then read in the log. The log itself can be made to show/hide that info on command. Or perhaps just simply show it if the clutter is manageable.

There is also another approach: let the sound widget show highest recent sound, where recent can be a predefined portion of time, for ex. 3 seconds. This could be a rabbit hole, but I'm just pointing it out as a potential option.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
