### ISSUE TITLE
Pillowcases and their similarities to Shampoo Bottles (If you take a Pillow out of its Pillowcase you are unable to put it back in)

### ISSUE THREAD

**Issue by estebandellasilva** [CleverRaven/Cataclysm-DDA#54169]
### Describe the bug

So i accidently unloaded a downpillow from its pillowcase - and iam unable to put the pillow back inside.

### Steps to reproduce

Get Downpillow inside a pillowcase
unload the pillow 
try to but the pillow back inside the pillowcase

### Expected behavior

being able to perform basic hygene tasks like washing my pillowcases ;D and putting the pillow in the pillowcase

### Screenshots

![image](https://user-images.githubusercontent.com/89189872/148651050-d9aa0495-5aab-407a-acc6-80dcec580132.png)
not being offered to put the pillow in the pillowcase
![image](https://user-images.githubusercontent.com/89189872/148651064-f403bdb4-fdf8-484c-82bd-415d20328523.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: fe5028e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

**Comment by LeahLuong** [comment]
If you squeeze the air out of a shampoo bottle, you can kind of use the vacuum to slurp up some of the shampoo you want to put back. Maybe some sort of similar system could be implemented for pillowcases.

**Comment by new02DAY** [comment]
It's actually more of a UI issue. If the pocket that a pillowcase occupies can't accommodate a full pillowcase (pillowcase+pillow), it won't let you. But if you wield the pillowcase or if it's in an empty bag or something, you can insert a pillow. Give that a try, please.

BUT your issue brings up a good point. Right now, a pillowcase has a volume of 1L, and a pillow 1L. When we insert a pillow into a pillowcase, they sum to 2L. Which is weird. I think an empty pillowcase should have a lower volume (~0.1L). But it shouldn't also sum regardless.

**Comment by estebandellasilva** [comment]
It appears to be correct - i was carrying the pillow in my cargo pants (damn that must be some huge pockets there)
