### ISSUE TITLE
Silently open/close doors and windows

### ISSUE THREAD

**Issue by matshou** [CleverRaven/Cataclysm-DDA#54166]
### Is your feature request related to a problem? Please describe.

Many times when I am scavenging and I approach a door or a window I know is unlocked I always think to myself:

> What if a monster close-by hears me opening this door/window and foils my plans?

Because closing doors is so loud it is possible for monsters in adjacent buildings hearing it.

### Solution you would like.

I would like to propose adding an ability to open and close doors and windows silently.

This could be implemented in the following ways:

- Opening doors while crouching makes 3 (6) noise and costs 300 (100) moves.
- Closing doors while crouching makes 5 (10) noise and costs 270 (90) moves.

Opening and closing windows would follow the same implementation.
This would allow players to sneak around buildings more easily by trading move points for stealth.

### Describe alternatives you have considered.

Displaying a menu when opening/closing doors and windows that let's players choose whether to open/close normally or silently.
The problem with this approach is that it would add additional key presses that would be redundant in most situations as most times you want to open or close the doors normally.

### Additional context

See [feature branch](https://github.com/matshou/Cataclysm-DDA/tree/feat/54166) for implementation details.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
