### ISSUE TITLE
Inconsistensies with boomer zombie types avoiding danger

### ISSUE THREAD

**Issue by Oxideion** [CleverRaven/Cataclysm-DDA#54176]
### Describe the bug

Zombies in question: boomer, huge boomer, boomer glutton, bloated zombie, zombie necro-boomer and gasoline zombie.

Some of these (normal, huge and necro) have the flag "PATH_AVOID_DANGER_1" while the others don't. 

### Steps to reproduce

1. Create a field of fire that the zombies can't stumble around.
2. Spawn the zombies on the other side of the fire.
3. Watch as some suicide into the fire and others get perpetually stuck until the fire spreads and kills them or it extinguishes.

### Expected behavior

I would expect these zombies to either all or none avoid danger. It also seems strange to me for these zombies to avoid danger in the first place (unlike most other zombies), though perhaps the necro-boomer would be an exception.

### Versions and configuration

- OS Windows 10
- Game Version: eacb7d9 , (Build: 2022-01-03-0731)
- Ingame language: English
- Mods loaded: Bionic professions, Disable NPC needs, No fungal growth

**Comment by mkrutov** [comment]
It feels for me personally that all zombies should not avoid danger, except may be zombie masters. Why would they have self-preservation?

**Comment by Oxideion** [comment]
I feel the same. Necromancers and masters are supposed to be smarter support units. The necro-boomer somewhat follows the same idea hence why I think it could also avoid danger.
