### ISSUE TITLE
Protection values for a suit seem anomalously high

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#54177]
### Describe the bug

Suits provide an alarmingly high amount of protection for their encumbrance.

### Steps to reproduce

1. Find a suit
2. Examine the suit

### Expected behavior

Suits should be much more delicate, shouldn't they?

### Screenshots

![image](https://user-images.githubusercontent.com/2125926/148657417-7c6a6e55-98f9-41ed-b889-b446db11852f.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: fe5028e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    No Vault [No_Vault]
]

**Comment by Maleclypse** [comment]
There are a large number of items that didn't get fixed in the PR that reduced normal clothes armor values iirc.  I think it was thickness related?

**Comment by Inglonias** [comment]
Ditto the wool blazer, maybe.
