### ISSUE TITLE
Is it time to get rid of old-school labs?

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#54175]
### Is your feature request related to a problem? Please describe.

The old style hard-coded labs are the last remaining significant C++ generated structure in the game, and I feel that with the addition of Trans-Coast Logistics and microlabs as well as recent lore changes and updates, it might be time to start talking about removing them from the game entirely. I want to emphasize that this is only in relation to the ice labs and procedurally generated lab buildings. The microlabs and TCL labs would serve as replacements.

### Solution you would like.

Remove the old labs and all associated mapgen from the game, and bump up the spawn rate of TCL labs and microlabs to make up the difference. This would be the ideal approach, though I would also appreciate it if microlabs had some sort of armory or barracks to replace the baracks and armory of the old-style labs.

### Describe alternatives you have considered.

This is simply a request for discussion. Labs have quite a pedigree, having been in the game for at least as long as I have been playing, and I believe they date back to before the DDA fork even existed. If there's a good reason to keep them in the game, I'm open to it.

**Comment by Terrorforge** [comment]
I'd love to get rid of them, but there are a number of items that would need to be moved. Off the top of my head, I think the phase immersion suit and computer printout (plutonium battery recipes) only spawn in lab finales.

It would also severely reduce access to autodocs, rivtech weapons and certain rarer guns (barrett, SCAR-H) and their magazine, among other things. Not sure that's a bad thing, though? That stuff probably should be rare, and only found in places you have to actively assault. So I don't think I want microlab barracks. I want a microlab equivalent that's like a weapon research centre.

**Comment by nexusmrsep** [comment]
> I would also appreciate it if microlabs had some sort of armory or barracks to replace the baracks and armory of the old-style labs.

Absolutely not in my opinion. The scourge of old labs was their all-in-one genie in a box character - where you can literally loot one lab instead of an entire map, and you'd get everything what you need. Lab equipment - check. Military equipment - check. Ton of materials - check. Bionics - check. Mutagens - check. Medical equipment - check. Even RNG did not cut down their boastful lucrativeness.

They should change - but perhaps it should use the well established mapgen mechanism to change some of them to full military bases or barracks, evacuation bunkers (aka. Necropolis variants),  underground factories and facilities (weapons factory / hospital - medical / etc. ). Point here is - only one strict variant per location, and no all-in-one Frankenstein's monster.

**Comment by Maleclypse** [comment]
It would probably be good to create a project with a list of things needed to burn down the procgen labs. Here's a couple items I think might be beneficial.

[] Create mutable special ice and deep freeze labs
[] Adjust microlabs to have a more visible finale room
[] Create one or more variants of the research facility
[] I believe wist has said they want at least one variant of the TCL prior to eliminating procgen labs but I'd want to confirm that

**Comment by Venera3** [comment]
I'll be in the line to dance around that particular pyre but we need at least a lab specialized in high-tech boomsticks before that, I think: The mutable microlabs to cover nether bullshit/artifacts, the TCL and related locations for mutagen-related goodies, and a location to get the shiny guns and co from.

**Comment by Inglonias** [comment]
Alright. It sounds like I was jumping the gun here just a bit. Good to know. Thank you.
