### ISSUE TITLE
`compose.py` can't ignore subdirectories on windows

### ISSUE THREAD

**Issue by Fris0uman** [CleverRaven/Cataclysm-DDA#54174]
### Describe the bug

`compose.py` ability to ignore subdirectories implemented in https://github.com/CleverRaven/Cataclysm-DDA/pull/53083 doesn't work on windows

### Steps to reproduce

1. set some directories to be ingored as shown in #53083
2. compose --use-all
3. The sprites from that directory got composed anyway

### Expected behavior

1. set some directories to be ingored as shown in #53083
2. compose --use-all
3. The sprites from that directory are not in the resulting tileset

### Versions and configuration

NA this is a tool issue.

**Comment by sulyi** [comment]
But does it work?
