### ISSUE TITLE
Being able to prone/crouch on long grass to hide.

### ISSUE THREAD

**Issue by OmeleteDuFroMago** [CleverRaven/Cataclysm-DDA#54178]
### Is your feature request related to a problem? Please describe.

I see a bunch long grass here and there, even in big cities, would be cool to be able to use it as a way to hide from danger.

### Solution you would like.

Be able to use it as a hiding spot.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
