### ISSUE TITLE
Connections for mutable specials

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#54172]
### Is your feature request related to a problem? Please describe.

I'm still learning how mutable specials work but I'd like to be able to tie into connections like sewers.  The mutable microlabs seem to somehow connect into subways, I haven't quite figured out yet if only sometimes they connect into the subways by accident or how this is working.

### Solution you would like.

I'd like to be able to define connections similar to how fixed specials work.

### Describe alternatives you have considered.

I tried looking at it this morning to see if I could cargo cult the connections from `for( auto &elem : connections ) {` over to the mutable specials but it's beyond my level.

**Comment by Night-Pryanik** [comment]
> The mutable microlabs seem to somehow connect into subways

They ain't. Only static microlabs connect to subways.
