### ISSUE TITLE
Non-scope sights still kind of useless

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#54173]
### Is your feature request related to a problem? Please describe.

This is feedback on @wwkk222208 's aim overhaul (original #53106, merged #53180). As the original post states, for a long time it was the case that scopes were just far better than any other sights, and the increased time for precise aiming with scopes helped that somewhat. However, I still feel like there's very little reason to use any other kind of sight, for two reasons:

1. Red dot and holographic sights barely seem to do anything. They don't seem to influence accuracy at all, and only shave a few moves off aim times.
2. Obscuring your iron sights with a scope seems to have negligible impact on your non-precise aiming speed/accuracy. In combination with the above, this means that in close quarters, where you don't want to be firing Precise shots anyway, it's just as good as a rifle with a red dot or holo.

### Solution you would like.

Make red dots and holographic sights more worthwhile.

Make obscured iron sights actually matter, so there's a meaningful penalty to using a scope.

**Comment by wwkk222208** [comment]
Fine. I'll check it.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
