### ISSUE TITLE
Allow players with high Health Care skill to install bionics on friendly NPCs through surgery without an Autodoc.

### ISSUE THREAD

**Issue by cataclysmsurvivalist** [CleverRaven/Cataclysm-DDA#54189]
### Is your feature request related to a problem? Please describe.

Just as surgeons can install CBMs on the player, I don't see a reason why the player shouldn't be able to install CBMs if he has a high enough skill.

### Solution you would like.

When not using an Autodoc, installing CBMs on other people should require a high Health Care and Mechanics skill, a soft bed, anesthesia, a scalpel, and a lot of thread or sinew. The process should greatly affect weariness, to simulate the mental drain of real-world surgeries. It should also be significantly harder than when using Autodocs, with a higher chance of failure.

When installing CBMs on NPCs this way, the player's Health Care skill should also increase.

**Comment by new02DAY** [comment]
Maybe tie it to a surgeon profession (like helicopter pilots and flying)? Installing CBMs seems like a very highly specialized skill-set, even with health care and mechanic skills. Not even other healthcare professions (non-surgical) would be able to do it, I think.

**Comment by TealcOneill** [comment]
CBMs are becoming faction specific and you will only be able to get them installed in one place.

**Comment by cataclysmsurvivalist** [comment]
> Maybe tie it to a surgeon profession (like helicopter pilots and flying)? Installing CBMs seems like a very highly specialized skill-set, even with health care and mechanic skills. Not even other healthcare professions (non-surgical) would be able to do it, I think.

I think it should be better tied to a Proficiency, like most things. It's true that surgery and bionics are extremely narrow subjects to understand and practice, but even then there's no reason why a survivor wouldn't be able to learn it if he was willing to practice.

Hell, make it special, you could practice it by dragging zombies into beds and practicing installing CBMs on them. It's far-fetched, and may even be a waste of bionics, but you do need practice if you ever plan on installing one for real, and I always liked it when games do fun things like those that border on being easter eggs.

> CBMs are becoming faction specific and you will only be able to get them installed in one place.

That just sounds like a plainly awful idea, and a middle finger to pretty much everyone who has been getting used to the bionics system since the earlier days of development.

**Comment by TealcOneill** [comment]
I mean, it's already been this way for many months and I doubt they're going to delete the hundreds to thousands of hours of work they put into making a whole new faction just so a few players are happier. I personally really like the exodii and prefer it over the old CBM system.

**Comment by cataclysmsurvivalist** [comment]
> I mean, it's already been this way for many months and I doubt they're going to delete the hundreds to thousands of hours of work they put into making a whole new faction just so a few players are happier. I personally really like the exodii and prefer it over the old CBM system.

... You're not talking about the CBM _system_ at all. It's true that the Exodii are the exclusive owners of the best bionics in the game, but if they're who you were referring to, it's not as if the CBM system itself is exclusive to them and you'd be only able to become a cyborg with their help. So why did you talk about CBMs being faction specific?

**Comment by TealcOneill** [comment]
> 
In the new lore there are no cybernetics in our universe more advanced then we have right now. The CBMs come to our universe with the Exodii and if you're finding them elsewhere then it's either a bug or Erk has decided not to remove them completely because he's not finished with the Exodii yet.

**Comment by LeahLuong** [comment]
Tealc's right. CBM's as we've come to know them may live on in forks or mods but the Exodii are taking them over in the base game. Prob best to close this issue.

**Comment by cataclysmsurvivalist** [comment]
This is without a doubt the most brutal retconning of a game aspect I've ever seen. I suppose I should have heard the warning sirens when I saw the Broken Cyborg scenario no longer pop up in the character creation menu. And I have SO MANY questions in terms of gameplay too, like what will happen to Autodocs, or prototype/broken cyborg enemies in labs.

But even if CBMs can't be found in regular labs anymore, I don't see a reason why you shouldn't be able to install them in a follower yourself. So I think the issue should remain open, because even if CBMs can be only found in certain places, this issue is mainly about how they're installed onto NPCs, so it's still valid from my point of view.

**Comment by Venera3** [comment]
You're not doing solo brain surgery, especially not self-taught. Anything more involved than an appendectomy is a two-man job at least, and you'll never reach the levels of field sterility needed for implanting anything without massive complications. A pre-Cataclysm OR team, in a maintained lab OR, using proper trays, with intimate knowledge of the CBM's installation steps, probably, but you have none of that.

**Comment by Night-Pryanik** [comment]
> You're not doing solo brain surgery, especially not self-taught.

Doctor in Tacoma community is doing solo brain surgery without an autodoc. We need either make him lose this ability or give this ability to player, otherwise it's inconsistent.

**Comment by Venera3** [comment]
Yes, that should go. Whenever wound care becomes more involved than "just slap some cattail gunk on it" they (and any NPC with pre-Cataclysm medical training) will be worth their weight in gold, but until then closing the bionic loophole will have to do. Autodocs will probably survive this cycle as they stand, but long-term I have some plans to bring them down to more reasonable levels.

**Comment by cataclysmsurvivalist** [comment]
> Whenever wound care becomes more involved than "just slap some cattail gunk on it"

I believe this threshold you're referring to is called 'having a Health Care skill of 9 or higher'. And standard doctors, judging from the profession picks, start out with a Health Care rating of 4 or 5.

And I know that I'm essentially shooting myself on the foot by saying this, because the moment I do someone will rush to 'fix' the game by removing this feature, but you can get wound care on the same level of a paramedic and a Health Care of 3 by practicing with the help of a book using bandages until you mastered that skill.

It's a lore point that the cataclysm has buffed up human potential when mutating. Dexterity and intelligence can be increased to prodigial amounts. Even discounting _that_, unarmed is actually viable against crowds of undead armies depending on how much practice your survivor gets, and yes, solo surgery is viable in real life (but extremely rare because working with a team is obviously far safer than working alone).

Implant surgery is obviously an extreme stretch, especially considering the goal is to install cybernetics in it, but the risks (both from working solo and not being a professional surgeon) are already detailed in the failure chances, which I already acknowledged should be increased if you don't have the right Proficiency and a low Health Care skill. And most importantly, it's a good mechanic to tie to Health Care.

This entire design philosophy is reaching Reddit-tier levels of "in real life people died when they were 10 from a papercut because non-postmodernist society don't have ScienceTM" and it's starting to worry me. Why is it that whenever developers talk about 'realism' they really just mean 'nobody has ever been good at anything _ever_ and capable people don't exist'?

>OR, using proper trays, with intimate knowledge of the CBM's installation steps, probably, but you have none of that.

If only there were in-game guides that can be read by Autodocs and advanced computers that literally detail exactly what you described, and should by all means be allowed to be studied by the player like everything else given the right equipment (such as e-ink tablets or laptops).

Actually, I was thinking, is it realistic that the player just doesn't ever catch cancer randomly, or that there's no chance that we might stab ourselves with a sword and harm ourselves when wielding it? In fact, it's known that even pros aren't fallible, so I was thinking that swinging a sword should have a 75% chance of killing you instantly, and it should be decreased by 1% for every skill in slashing weapons you have.

Also, fighting bears? Ridiculous. Bears are super strong, nobody has ever killed them one-on-one. Regardless of how good your melee skill is, you should be thrashed automatically when fighting one with no chance of recovery. It's just not very realistic.

And I'm still waiting for that promised new update where installing and playing the game causes a bitcoin assassin to be immediately hired and come to your real-life house to shoot you in the face, which is the best way to simulate getting bitten by a zombie.

**Comment by cataclysmsurvivalist** [comment]
Yeah, nevermind I'm done.
