### ISSUE TITLE
Restore visibility of armor values of <1 in item descriptions.

### ISSUE THREAD

**Issue by VitreousEyes110** [CleverRaven/Cataclysm-DDA#54187]
### Is your feature request related to a problem? Please describe.

Recently #53888 changed how armor info is displayed, removing truly redundant information such as identical melee/ranged coverage and zero vitals coverage. However this also made it so that all armor values below 1 are no longer displayed in item descriptions, instead just saying "Negligible Protection". This information is not universally irrelevant and should be viewable by players in the item's description. The information is still viewable if checked in the 'W'ear menu, but this information should be accessible to the player from the normal item description menu. For example, in a situation where a player is deciding between two otherwise identical items, with one giving .1 protection and one giving .9, the obvious choice is the more protective item. However because of this change, the relevant information can't be gleaned from the armor section of the items' descriptions, instead requiring the player to check the 'W'ear menu to know their actual protection values.

### Solution you would like.

 - Restore the armor info entries of items with <1 protection to the descriptions of items.
 - Keep armor info entries with 0 protection value hidden.

### Describe alternatives you have considered.

- Restore the information, with color coding to suggest that the amount of protection given is relatively low.
- Add an option or keybinding to toggle displaying the negligible armor information.
- Remove the armor value information from the 'W' menu and any other places it's still visible, making low enough armor values indistinguishable due to the insignificant difference. Possibly also change all 'negligible' armor values to be equal.

**Comment by bombasticSlacks** [comment]
I can add it as a menu option. It's a lot of screen real estate as is.

**Comment by kevingranade** [comment]
Pass, precise data about stats is not needed.
