### ISSUE TITLE
Switching windows lets the text on the diary page vanish while editing

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#54184]
### Describe the bug

n/a

### Steps to reproduce

1. Open the diary.
2. Create your very first page.
3. Enter some text. Do not save the entry yet.
4. Switch windows. In this case I just switched virtual desktops, so cataclysm-tiles lost focus.
5. The text vanishes until you enter something again.

### Expected behavior

The text does not vanish.

It is very unlikely this is related to my window manager (awesomewm), since only a tiny part of the window does not get redrawn and literally everything else works fine. Resizing the window does not do anything, which is another indicator that my wm is doing fine. Might be related to tiles, may be related to Linux. Needs to be verified by someone else with a different setup.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.F [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Innawood [innawood]
]

**Comment by NetSysFire** [comment]
@LFKrause, mind looking at this, too?

**Comment by LFKrause** [comment]
I have looked at it. I know where the problem is, but I don't have the time to fix it at the moment. Maybe I can do it this weekend. 

The problem is that the Sting_editor_window class doesn't use a ui_adaptor, so it doesn't have a method for on_screen_resize() or for on_redraw(). So while in the loop of query_string(true) it will not change to on resize or redraw.

**Comment by NetSysFire** [comment]
It is fine, it is no critical error so take your time. Thanks for debugging and finding the cause already!
