### ISSUE TITLE
Rework gun repair, mending, repair kits (and misc. repair kit?)

### ISSUE THREAD

**Issue by new02DAY** [CleverRaven/Cataclysm-DDA#54185]
### Is your feature request related to a problem? Please describe.

I know this is a niche issue, so understandably a low priority. Just wanted to get it out there. 

Messing around with the gunsmith (GRK) and firearm repair kits (FRK), I realized that it's a bit of a messy setup. A quick Google search shows that for the most part, soldering/welding is really only for specific cases (ex. adding ribbing to shotguns, adding sling points to some older rifles). Once you remove the soldering/welding aspects, it's mostly a set of clamps, punches, bits, wrenches screwdrivers, hammers, etc. 

Especially with modern guns, anecdotally, most require very few tools to service. Not quite sure about older, niche guns, but that could be handled granularly.

### Solution you would like.

- Combine mend action into use item menu as a new action. It's not quite intuitive if you don't use guns much, and need to figure out how to clean them. I'm also not sure what else uses mend other than engines?
- Maybe combine/reduce the GRK/FRK into one kit? OR make repair/mend action success depend on quality (like lockpicks). I prefer the latter, as something you cobble together vs. a professional kit would have quality differences (not necessarily large ones, but probably enough to make it matter to success chance). Something like missing a specific punch and making do, vs. having a variety available.
- Rework crafting that makes use of GRK/FRK to separate out the tools (ie. GRK/FRK AND soldering/welding) depending on what's being done.
- Maybe rework adding some mods to require tools?

### Describe alternatives you have considered.

Ignore it.

### Additional context

Could also be extended to the misc. repair kit, which (in my mind) has the same issue, but to a lesser/lower impact degree. Maybe we could rework duct tape into a tool with the repair function of the kit? (Extending this, maybe it'd be a good idea to move thread/variations into tools, since that would keep them all under one logical category. Also maybe batteries, welding rods, solder, and other tool consumables?)

**Comment by LeahLuong** [comment]
Separating out the repair kits into individual tools seems somewhat problematic. W/out these centralized tools, the only alternative would seem to be defining repair reqs for each individual item. While that sort of granularity might be welcome for those hardcore realism players, most players might find the details overwhelming & the project of completing such an audit would be no mean thing in itself.

Additionally, I believe I-am-Erk intends to make mending a more prominent feature in the future. See #53500.

I would like to see FRK & GRK more strongly differentiated as well as some mods having tool quality reqs.

**Comment by new02DAY** [comment]
True, and there'd be no item tied to `gun repair`. Glad to see mend is being expanded, thanks for pointing it out.
I imagine the most flexible way to add tool requirements would require a new field like `min_skills` in the gunmod files.

**Comment by bombasticSlacks** [comment]
some gun mods like the full conversion kits actually do require skill, tools, and can break the gun. It's a bit of a buried feature tho. 

I agree in general however that the gunsmith kit and the firearm repair kit are redundant. Though having some tool set that you can use to get the ++ version of the gun makes sense to me IMO

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
