### ISSUE TITLE
Moving (some?) furniture on dropped liquid deplace the liquid

### ISSUE THREAD

**Issue by Zeropol** [CleverRaven/Cataclysm-DDA#54180]
### Describe the bug

I moved a flower pot around and it mopped some blood leftover from butchery.

### Steps to reproduce

1. Spill some liquid.
2. Move a flower pot, or possibly any furniture I don't know.
3. See the liquid is carried over with the pot.

### Expected behavior

Hauling a furniture on spilled liquid do nothing.
Or, hauling a furniture on spilled liquids makes more mess ( beware DF was/is famous for duplicating liquids in a comparable situation )

### Screenshots

https://user-images.githubusercontent.com/28099824/148657790-a0ef6674-bd3c-4a65-a71c-6e750300f760.mp4

![image](https://user-images.githubusercontent.com/28099824/148657749-feacc780-c5c4-43f6-9538-c9cfcfa2d1af.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: cfafb47 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    No Hope [no_hope],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

We are still able to mop the "trapped" liquids.
My flowers are safe !

**Comment by Night-Pryanik** [comment]
Mopping spilled liquid when furniture is moved onto it works as intended.

**Comment by Zeropol** [comment]
Sorry
