### ISSUE TITLE
Organize installed bionics and learned martial arts alphabetically rather than based on when they were installed/learned.

### ISSUE THREAD

**Issue by cataclysmsurvivalist** [CleverRaven/Cataclysm-DDA#54192]
### Is your feature request related to a problem? Please describe.

This is a small quality of life improvement that I don't expect would be taken seriously, but it's still something that really nags me. Besides it making it significantly less intuitive to navigate due to the lack of logic as to how those screens are presented, the lack of organization on these menus is something that saps a bit from the 'satisfaction' of checking on them,

### Solution you would like.

The Bionics and the Martial Arts menu should be organized based on alphabetical order, just as Traits and Mutations are. It's the best way to organize a menu.

I know this is minor, but I really think the interface design of a game are important even with small details like these.

**Comment by andrei8l** [comment]
The bionics menu is already sortable. It was one of my first PRs
![Untitled](https://user-images.githubusercontent.com/68240139/148669642-8bae5381-8e3c-4c8e-a48c-7d26ab231704.png)
Or is there another bionics menu?

**Comment by cataclysmsurvivalist** [comment]
>Or is there another bionics menu?

Yes, I was talking about the one in the Info menu.
