### ISSUE TITLE
"Mouse View" is not translated

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#54201]
### Describe the bug

https://github.com/CleverRaven/Cataclysm-DDA/blob/9fdb7ef59c81f805a4101b8b4ad4905b8c60a48f/src/live_view.cpp#L69

### Steps to reproduce

1. Use a locale other than english (in this case, a new non-english player asked for unrelated help, shared a screenshot which showed that)
2. Witness the untranslated string.

### Expected behavior

It should be able to be translated.

### Versions and configuration

- experimental

**Comment by BrettDong** [comment]
This string IS translated.
