### ISSUE TITLE
Infrared vision does not entirely take sleeping into account

### ISSUE THREAD

**Issue by JantDarvus** [CleverRaven/Cataclysm-DDA#54205]
### Describe the bug

When sleeping, Infrared Vision will still spot people in a tile next to you.

### Steps to reproduce

1. Give a survivor the Infrared Vision mutation.
2. Fall asleep with a person next to you (probably a friendly since otherwise you'll just get smacked awake anyway)
3. Behold their heat

### Expected behavior

When asleep, all vision is cut off unless someone adds/has added a 'sleep with half your brain at a time' kind of mutation. That'd be neat.

### Screenshots

![unknown 1](https://user-images.githubusercontent.com/45110965/148681564-a312c53f-b56a-450a-9679-00457fdc22f5.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 1793043 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Zireael07** [comment]
Why close?

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-012152.
