### ISSUE TITLE
[Aftershock] Orbital Distress Beacon categorized as a weapon

### ISSUE THREAD

**Issue by Zeropol** [CleverRaven/Cataclysm-DDA#54219]
### Describe the bug

The item *Orbital distress beacon* is categorized as a weapon.

### Steps to reproduce

1. Start the *Stranded spacer* scenario or use the debug menu to get the item

### Expected behavior

Maybe categorized as a tool ?

### Screenshots

![image](https://user-images.githubusercontent.com/28099824/148698917-f0255dd1-d933-42a8-bce8-65054e4d302f.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: cfafb47 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    No Hope [no_hope],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Maleclypse** [comment]
Closed by #54462
