### ISSUE TITLE
Expand the role of the Saltworks expansion to more of a chemistry lab role

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#54218]
### Is your feature request related to a problem? Please describe.

As the new versions of base expansions have been added in, I've noticed that there's really not a lot of love for the saltworks expansion. There doesn't seem to be any interest that I've seen to make a new saltworks version, and the new canteen version now includes brewery features that were shoehorned into the saltworks expansion for... some reason. The only thing left that saltworks even has going for it now is the ability to send NPCs to craft salt from salt water - which, okay, that's useful, and all, but having an entire expansion just for that one thing is rather... underwhelming.

### Solution you would like.

Expand the usefulness of the saltworks expansion, and maybe make use of the empty space in the northwest corner, by giving it more of a chemistry lab function.

### Describe alternatives you have considered.

-Adding more of a tannery function instead of a chemistry lab function
-Adding a chemistry lab function, and switching out the brewery for a tannery

**Comment by AmarinReyny** [comment]
> The reason I haven't made a new saltworks version is that it doesn't make any real world sense it apply magic to turn a piece of ordinary field into an infinite (swamp) salt water supply.
> 

Well, I think somewhere in the description it says that it just redirects some salt water from a nearby swamp into said field. Of course, that's not how it works in practice, since it can be built even without a nearby swamp.

> There's been a discussion (in conjunction with the appliances development) about a hospital/chemical production expansion that would allow you to produce (medical) drugs that would require long time of processing, thus needing computerized monitoring, but this hasn't been anywhere near implementation level.
> 

Understandable. Maybe it'll be more feasible when powered buildings are worked into the game?

> For tanning I'd rather expand the version 2 workshop with a tannery building, but I'm not sure there's enough tanning going on that there's really a use for it. Also, the current tanning recipes aren't really the type of recipes I'd feel a need to hand over to companions (i.e. things that take a long time to do, so you'd rather send off someone else to do it). A disadvantage with using the workshop is that the current UI gets unwieldy when the number of recipes available to an expansion grows.

I was thinking it would make sense for the saltworks because of how salt/salt water is used for curing hides/pelts, and if a saltworks would do that, then it would only make sense for it to also be able to do the next step, as well. Also, survivors can get a lot of pelts/hides from butchering, so it's less about how long it takes to cure/tan individual pelts/hides, and more about the amount of pelts/hides being tanned.

Side note, if you're worried about the workshop UI being unweildy (which I agree is a problem), maybe you could make a new type of expansion for working with softer materials such as cloth and leather? Or, maybe you could figure out how to divide the expansion mission options into categories, so it looks like a list with neatly divided sections and not just a wall of options?

**Comment by PatrikLundell** [comment]
Redirecting water is a huge effort of digging trenches for the water to flow along, and swamps are usually low lying terrain, so you'd probably somehow have to make it move upwards. Thus, I consider the saltworks to be completely unrealistic. If it was possible to build it on swamp terrain instead of field terrain I'd accept it (and still wouldn't use it, as swamps and their vicinity is now lethal).

There's a reason I mention the erecting of salt water tanks in version 2 of the canteen, even though there's nothing in the blueprint that can enforce the usage of them for that purpose...
It would be possible to add tanning recipes to that expansion. Personally I haven't done much butchering as looted food provides enough calories for companions, and pemmican for the PC doesn't require hunting that often.

I'm have too little understanding of the UI logic to improve the base camp UI to make sections (and my UI questions in the past still remain unanswered). In my view, an improved camp crafting UI would look similar to the PC crafting UI and would be auto populated with the available recipes that the available equipment support (and, ideally, the available equipment should be determined by scanning the area [allowing for manual changes to the camp], rather than dictated by the blueprints).

**Comment by AmarinReyny** [comment]
> Redirecting water is a huge effort of digging trenches for the water to flow along, and swamps are usually low lying terrain, so you'd probably somehow have to make it move upwards. Thus, I consider the saltworks to be completely unrealistic. If it was possible to build it on swamp terrain instead of field terrain I'd accept it (and still wouldn't use it, as swamps and their vicinity is now lethal).
> 

Understandable. By "lethal," are you talking about the presence of dangerous monsters, or are there now dangers in the actual terrain itself?

> There's a reason I mention the erecting of salt water tanks in version 2 of the canteen, even though there's nothing in the blueprint that can enforce the usage of them for that purpose... It would be possible to add tanning recipes to that expansion. Personally I haven't done much butchering as looted food provides enough calories for companions, and pemmican for the PC doesn't require hunting that often.
> 

To each their own, I guess, but I use butchering quite a lot to feed companions, and have looted food that can't be made any more saved in freezers for special occasions (I also like to pretend that the NPCs need tasty food to keep camp morale up every now and then, so sometimes I'll focus on distributing food that tastes good moreso than food that has high calories).

> I'm have too little understanding of the UI logic to improve the base camp UI to make sections (and my UI questions in the past still remain unanswered). In my view, an improved camp crafting UI would look similar to the PC crafting UI and would be auto populated with the available recipes that the available equipment support (and, ideally, the available equipment should be determined by scanning the area [allowing for manual changes to the camp], rather than dictated by the blueprints).

I agree - the way the camp recipes work right now is too arbitrary, and I've found myself modding in recipes on numerous occasions just because I want something mass-produced by an NPC that isn't already in the basecamp recipes. I've heard talk about switching over to what you've described - is that the plan going forward, or is the dev team still deciding?

**Comment by PatrikLundell** [comment]
Lethal: The monster, such as dragon flies, centipedes, etc.

I think adding the recipes you feel you need is a good workaround for those with sufficient knowledge to do it, but that's not a desirable state.

Base camp plans: I don't think there's much, if any, opposition to the ideas to improve the base camps as such, but there's been nobody appearing to actually take on the tasks, and the core team have other things that are higher on their respective priority lists. That's a constant issue with volunteer driven development, i.e. lots of people having ideas, but a lot fewer people actually taking on the job of implementing those ideas (I'm not implying putting forth ideas is bad! It IS bad to come up with ideas and then complain that there isn't somebody else that implements it for them [completely different from a rational discussion]). Thus, I don't think the core team will perform the bulk of the work.

**Comment by AmarinReyny** [comment]
> Base camp plans: I don't think there's much, if any, opposition to the ideas to improve the base camps as such, but there's been nobody appearing to actually take on the tasks, and the core team have other things that are higher on their respective priority lists. That's a constant issue with volunteer driven development, i.e. lots of people having ideas, but a lot fewer people actually taking on the job of implementing those ideas (I'm not implying putting forth ideas is bad! It IS bad to come up with ideas and then complain that there isn't somebody else that implements it for them [completely different from a rational discussion]). Thus, I don't think the core team will perform the bulk of the work.

Understandable. Thank you for letting me know.

**Comment by kevingranade** [comment]
"Hey maybe expand on this content" isn't really enough detail to justify leaving an issue around indefinitely. This issue has been around for almost a year now and other than some discussion right as it was opened it has just been sitting here.
It was pinned by the addition of a "Good First Issue" label, which I'm also not sure about as the lack of detail and the difficulty of working with faction camp expansions seems problematic.
