### ISSUE TITLE
Getting tire irons seems unreasonably hard.

### ISSUE THREAD

**Issue by FeepingCreature** [CleverRaven/Cataclysm-DDA#54212]
### Describe the bug

Looking at https://cdda-trunk.chezzo.com/qualities/WHEEL_FAST , there are three items that give the ability to fasten wheels. None of those can be crafted, and I just went through like twenty cars, a garage, and two hardware stores without finding any of them.

There are cars with spare tires that don't have tire irons. You need a tire iron to remove the tire from the vehicle. How exactly are they expecting people to use that spare tire?

This seems unrealistic.

### Steps to reproduce

Search for a tire iron.

### Expected behavior

You find one in places where a tire iron would be reasonably found.

Alternately, a makeshift tire iron could be added. I feel if I can make a wrench, I should be able to make a tire iron. They're not exactly complex mechanisms.

### Versions and configuration

Commit 0d43a6e2705b6b4c15e0138a3eb74d3d7d6deb99, cdda-experimental-2022-01-09-0903

**Comment by estebandellasilva** [comment]
Technically you should also be able to use a socket wrench set.

**Comment by FeepingCreature** [comment]
I did not see any tool with this quality over several ingame days of active searching.

**Comment by Zireael07** [comment]
Not too sure if the website referenced is still up to date?

**Comment by FeepingCreature** [comment]
Source:

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/requirements/vehicle.json#L3

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/vehicleparts/wheel.json#L232

**Comment by Alex-Folts** [comment]
There was old PR which increase chance of getting tire iron, jack and spare wheel in cars. But i dont really see its effect, maybe it wasn't merged or reverted or otherwise messed.

Probably we need to research how many cars out there in RL have aforementioned items, and adjust probability of finding those in the game.

**Comment by FeepingCreature** [comment]
Well, at least in Germany tire irons (a website assures me) should be included with any newly purchased car.

**Comment by estebandellasilva** [comment]
> Well, at least in Germany tire irons (a website assures me) should be included with every newly purchased car. That said, it isn't legally required.

As a Car mechanic who finished his apprenticeship in Germany i can say to you ... that its actually quite rare to find a car that has none - in most of those cases the people used it for something else and forgot to put it back

Also not a small amount of people own torque wrenches + socket wrenches so its acutally quite rare to meet someone who doesnt ... problem is i dont know if this applies to New England

**Comment by new02DAY** [comment]
Maybe add it to the spawn group that spawns bottle jacks and tires in cars? And replace ferals with crowbars with tire irons? I live in the northeast just south of the region, and have no clue where I'd find a crowbar in an emergency (outside of running to a store). I think I'm more likely to find a tire iron in the spare tire compartment of the old cars here.

This [mentions ](https://newsroom.aaa.com/2017/10/spare-aaa-finds-nearly-one-third-new-vehicles-missing-spare-tire/) availability. Also [this](https://www.consumerreports.org/tires/some-newer-cars-are-missing-a-spare-tire-a9928775934/). Maybe add a new item "lug wrench"? To add more options/variety?

**Comment by Alex-Folts** [comment]
We could implement it like so:
replace this 3 lines: 
https://github.com/CleverRaven/Cataclysm-DDA/blob/0d43a6e2705b6b4c15e0138a3eb74d3d7d6deb99/data/json/itemgroups/vehicles_fuel_related.json#L30
https://github.com/CleverRaven/Cataclysm-DDA/blob/0d43a6e2705b6b4c15e0138a3eb74d3d7d6deb99/data/json/itemgroups/vehicles_fuel_related.json#L31
https://github.com/CleverRaven/Cataclysm-DDA/blob/0d43a6e2705b6b4c15e0138a3eb74d3d7d6deb99/data/json/itemgroups/vehicles_fuel_related.json#L32
with this single entry:
```
      {
        "collection": [
          {
            "distribution": [ { "item": "wheel", "prob": 95 }, { "item": "deflated_wheel", "prob": 5 } ],
            "prob": 100
          },
          { "item": "jack_small", "prob": 80 },
          { "item": "tire_iron", "prob": 50 }
        ],
        "prob": 50
      }
```

Which means: there is 50% chance to find collection of items in the car

- collection will have in 95% of cases wheel, in rest 5% of cases wheel with flat tire(here we simulating that previous owner changed wheel recently), 
- 80% to find jack in this collection(20% chance that someone stolle it, it is not something you will steal but still), 
- 50% chance for tire iron(here we asuming that tire iron were often used as melee weapon)

And as mention above, give some ferals tire irons(to partially recover that 50% loss).

**Comment by FeepingCreature** [comment]
I still wonder if it makes sense to have, in many cars, a replacement wheel that the owner couldn't possibly have installed. But this would be a huge practical improvement anyways.
