### ISSUE TITLE
Add a recipie for an improvised "plier" wrench

### ISSUE THREAD

**Issue by mm04926412** [CleverRaven/Cataclysm-DDA#54214]
### Is your feature request related to a problem? Please describe.

https://www.amazon.co.uk/SHARP-Tec-Adjustable-Plumbing-Tongue-Capacity/dp/B083K4FKQ5/ref=sr_1_1_sspa?crid=N241M4H5AUIA&keywords=plier+wrench&qid=1641749745&sprefix=plier+wrench%2Caps%2C70&sr=8-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEzQlo1NkxTN1VUT0wzJmVuY3J5cHRlZElkPUEwODMzMTYxM1VPN082UzZHRFMxTiZlbmNyeXB0ZWRBZElkPUEwOTk2MDE4MzYxQllIQTNZVDdQNyZ3aWRnZXROYW1lPXNwX2F0ZiZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU=

Plier wrenches of the type shown above would be something someone could reasonably make out of wood. An improvised wrench of the "plier" design would be something a survivor could realistically make if they can make things like the knife spear.

### Solution you would like.

Add an improvised wrench recipie made of wood using the "plier" design.

**Comment by Alex-Folts** [comment]
Wood will not work. Minimum cast out of aluminium, but still questionable.

**Comment by ZhilkinSerg** [comment]
There aren't wooden wrenches. Makes no sense.

**Comment by mm04926412** [comment]
I don't see why wood wouldn't work for small things like adjusting a bike. Since the "plier" design is being used wood would only be a problem if it would be destroyed by the applied force.

**Comment by Zireael07** [comment]
@mm04926412: I don't think we have a way to restrict this to only small things like casters/bikes

**Comment by estebandellasilva** [comment]
> @mm04926412: I don't think we have a way to restrict this to only small things like casters/bikes

well technically you could make it like wheel fastening 1 / 2 but that would not make that much sense kinda
