### ISSUE TITLE
Rubiks 'help me install CBMs' option has some trade-based oddities

### ISSUE THREAD

**Issue by JantDarvus** [CleverRaven/Cataclysm-DDA#54211]
### Describe the bug

If you ask Rubiks for help installing a CBM, he'll let you pick one of the ones he has physically lying around his shop without having to actually buy them first, only paying the installation fee.
Additionally, if you ask him for help installing a CBM (any CBM, not just his own), choose what you'll give him to pay for it, but then choose 'No' when you see the prompt for failure chance, the trade made will still stand even though you've cancelled the process.

### Steps to reproduce

Have a chat with Rubiks about installing CBMs.
Either use one of his, free of charge-ish, or cancel a trade and notice he has a 'no backsies' policy.

### Expected behavior

You should not be able to use any CBM that's considered to be in his shop inventory, nor should cancelling at the last moment result in the trade made to pay for it still standing.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 1793043 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Maleclypse** [comment]
Confirmed on discord.

**Comment by Bossrman** [comment]
You can also pay to install a cbm that you found elsewhere, and sell the cbm to him to pay for the installation of it.

**Comment by RenechCDDA** [comment]
Resolved at some point, as of https://github.com/CleverRaven/Cataclysm-DDA/commit/c94dc0387513d5bba49eb7d74b2b51a7a4d8c4a0

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/39a4aa04-cf16-4500-a8dc-42acbf10c3af)

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/28f77b3f-60e9-453d-8dc3-4e82654fd1d6)
