### ISSUE TITLE
[Aftershock] Orbital Distress Beacon description is misleading

### ISSUE THREAD

**Issue by Zeropol** [CleverRaven/Cataclysm-DDA#54220]
### Describe the bug

The item *Orbital distress beacon* description states we can *"plant it [..] to attract rescuers, or more likely, bandits"*.
We are unable to do so.

### Steps to reproduce

1. Start the *Stranded spacer* scenario or use the debug menu to get the item.
2. Try to plant it ( try to activate, try to search something related in the build menu )

### Expected behavior

We can plant it.
Or, the description says it is broken.
Or, the description don't state we can plant it.

### Screenshots

![image](https://user-images.githubusercontent.com/28099824/148699138-efea1678-02d0-4fab-9eab-6b77bc329430.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: cfafb47 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    No Hope [no_hope],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

Sorry for reporting such minor issue.

**Comment by Maleclypse** [comment]
For whoever works on this, I think it would be best if activating this item gave an effect message about it blinking and beeping, then set off an eoc chain that had a chance to do one of three things between 12 and 36 hours later: A. Summons some friendly NPCs,  B. Summon bandit NPCs/Monsters C. Stopped beeping 36 hours later with nothing having happened.
