### ISSUE TITLE
JSONize or add option to reduce music flavor text in log

### ISSUE THREAD

**Issue by new02DAY** [CleverRaven/Cataclysm-DDA#54221]
### Is your feature request related to a problem? Please describe.

I always almost have my character listening to music. I appreciate the flavor text, but I sometimes miss important things because of the frequency of it. It might be just a "me" thing, though.

### Solution you would like.

Maybe the frequency could be JSONized, sorta like `x_in_y_chance` like [portal_storm_effect_on_condition.json](https://github.com/CleverRaven/Cataclysm-DDA/blob/0d43a6e2705b6b4c15e0138a3eb74d3d7d6deb99/data/json/portal_storm_effect_on_condition.json)? Or maybe a way to ignore it in the log?
### Describe alternatives you have considered.

I tried removing the text in snippets/music.json, but I still get some, which I think are default.  I would be more than happy to mod it out for myself, but a search doesn't show me where they're defined.
![image](https://user-images.githubusercontent.com/56372745/148699199-6eb958bb-4adc-4583-a11d-186282419576.png)

EDIT: found them in [iuse.cpp,](https://github.com/CleverRaven/Cataclysm-DDA/blob/8d79e714df88903b21be8b62bf095d4014ff02c8/src/iuse.cpp#L5859) but I have no experience in coding. From the way it reads to me they're required for the morale function? And it seems like I wouldn't be able to mod it out for myself.

EDIT2: I tried creating a blank snippets/music.json mod, but it doesn't seem to remove the text. I have to make the changes in the CDDA\cdda\data\json one.

**Comment by ZhilkinSerg** [comment]
Music message ought to be displayed once in 5 minutes and it was like that before we moved to 1 second turns. Thing is it was coded in such manner it is now displayed 6 times more frequently expected - once in 50 one second turns, instead of once in 50 six second turns.

https://github.com/CleverRaven/Cataclysm-DDA/blob/8d79e714df88903b21be8b62bf095d4014ff02c8/src/iuse.cpp#L5856

**Comment by LeahLuong** [comment]
Why would any1 pass up the opportunity for some bass-heavy, post-glam speed polka?!
