### ISSUE TITLE
Mechs don't spawn with their respective weapon

### ISSUE THREAD

**Issue by ERRORCODE509** [CleverRaven/Cataclysm-DDA#54238]
### Describe the bug

Both the recon and combat mech don't have their guns when spawned. It's in their JSON, but something must've broken it at some point. No idea what though.

### Steps to reproduce

1. Create a character on a fresh world
2. Spawn a recon mech and a military id card with debug
3. Get inside and try to shoot
4. Notice that there is no weapon and it cannot shoot.

### Expected behavior

For combat and recon mechs to have their respective weapons. Seeing as it's in the JSON but isn't working, I get the feeling this may be a C++ issue.

### Screenshots

![image](https://user-images.githubusercontent.com/75010328/148729778-cbf8d6c2-95d6-447c-b035-9bec09f4b00e.png)
![image](https://user-images.githubusercontent.com/75010328/148729835-82a666d3-e79d-4329-9def-3250379febc6.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 939ec93 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

On a related note, mechs are a bit underpowered for how rare and difficult to maintain they are. There's already a flag to make the mech protect the user when inside (the `MECH_DEFENSIVE` flag), but none of them seem to use it. Is this an oversight or is it intentional? It also feels like you should probably also be able to grab and drag things around while in a mech, as moving aside a car or something seems like the kind of thing you would be able to do.

**Comment by a-chancey** [comment]
I would like to point out whatever changed also broke existing Mechs. None of mine have weapons since this broke

**Comment by ERRORCODE509** [comment]
This bug has made me think about mechs a bit more. I've no idea as to how difficult it would be to implement, but wouldn't it be possible to use temporary pseudo-CBMs while piloting a mech to allow for mech abilities and multiple mech weapons? I know a mech-specific overhaul would probably never happen seeing as they aren't very prominent in-game, but a mount overhaul that does the same things could be more reasonable.

**Comment by LeahLuong** [comment]
stalebot recently marked #52857 but it may have relevance for whomever tackles this issue . . .

**Comment by IndeedIExist** [comment]
Still broken
![image](https://user-images.githubusercontent.com/103674770/163443563-a95b285d-9fc6-4c68-8e63-dc00c556ac35.png)

only my AR shows up, shouldn't the Lazer gun show up? I thought maby it was auto targeting but, it did not shoot the task force that was chasing me down the hallway.
