### ISSUE TITLE
Libraries have holes in the floor

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#54237]
### Describe the bug

Some variants of the library overmap special have holes in the floor (ledges).

### Steps to reproduce

1. Use the map editor to spawn a bunch of libraries
2. Walk to them (long range teleport masks this bug)
3. Find a variant with holes in the floor

### Expected behavior

I expected to find the concrete foundation in places where the wooden library floor is damaged.

### Screenshots

![DeepinScreenshot_select-area_20220110100832](https://user-images.githubusercontent.com/52621858/148729104-553eae78-e07c-4395-bf98-27e77e6001df.png)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: dd5c1fc [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

### Additional context

Possibly related: #53549

**Comment by Maleclypse** [comment]
I think it's wild that teleporting masks the bug.

**Comment by coyo7e** [comment]
This open air thing is super annoying, I've been finding holes all over in fields etc, which are the same thing. They instantly eat/kill enemies and items, and climbing down into them is a BAD BAD idea.

If you save/quit and then reload while in view of these type of glitchy open air spaces, the game likes to instantly cover them up as well with regular floor/dirt type tiles.
