### ISSUE TITLE
Rocket launcher bot in collapsed tower griefs the tower and destroys quest items

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#54239]
### Describe the bug

Now that it can actually fire, the TALON bot will set fire to huge amounts of the tower, and will usually destroy the nanofabricator console and the quest items from the Hub01 quest, robbing the player of their rewards through no fault of their own, with no way to prevent this from happening. 
It's worth mentioning that the templates are contained inside a wooden box, the box being flammable might be responsible for the destruction of the quest templates.

### Steps to reproduce

1. Go near a collapsed tower, preferably with the Light Retrieval quest active.
2. Observe rewards being destroyed by robot.

### Expected behavior

The rocket bot should probably be replaced with something less destructive, such as CROWS or a bunch of secubots. A hugely destructive rocket bot also doesn't make sense to deploy in this location because it would destroy the tower, something obviously undesirable to its staff pre-cataclysm. If it really is just the wooden box that's causing these templates to be destroyed then simply changing it to a metal container would work, but it doesn't fix the issue of the rocket bot being incongruous.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 55ae5ff [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots]
]

**Comment by bombasticSlacks** [comment]
I added the box, and it just seemed like the coolest option. A metal box would be just as reasonable I can't comment on the rocket bot.
