### ISSUE TITLE
Installing a seatbelt may cause items to dissappear

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#54235]
### Describe the bug

When you install a seatbelt or a 5 point harness, the game allows you to use ropes that have items inside them. Using those ropes results in the items becoming a part of the seatbelt. From the player's perspective it my seem like the items mysteriously disappeared. Note: I did get my broadsword back by removing the seatbelt.

### Steps to reproduce

1. Spawn a 4x4 car
2. Remove a seatbelt
3. Put something inside the rope (e.g a broadsword)
4. Use the rope to install a seatbelt
5. Notice that you no longer have a broadsword

### Expected behavior

I was confused by this. I remembered finding a broadsword, but later I could not find it and had no idea where it went. I did not expect the broadsword to become a part of the seatbelt. I expected it to be moved to my inventory or dropped on the ground (with a chat message).

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: dd5c1fc [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by Maleclypse** [comment]
I laughed at the idea of the broadsword tied into the seat belt rig.  
NPC: Are you sure this is safe?
PC: Why do all my new friends always ask that question?
NPC: What happened to everyone that has asked that question before?

**Comment by NetSysFire** [comment]
Still valid. Reopening. One of many casualties with stalebot
