### ISSUE TITLE
Oversight: CBM Surgery from Rubik is vulnerable to portal storms

### ISSUE THREAD

**Issue by Sirbab** [CleverRaven/Cataclysm-DDA#54233]
### Describe the bug

I'm not exactly sure if this is technically a bug, but while the dialogue with Rubik indicates that you're taken into a surgery suite with a robot to get CBMs, you're mechanically still standing outside in front of his booth.  If a portal storm sweeps in while you're undergoing surgery, you can end up very injured, in critical pain, or dead(?) as a result.

### Steps to reproduce

Not entirely sure this can be reproduced reliably unless one can trigger portal storms on demand, but the general idea is:
1: Wait until a portal storm is about to start.
2: Ask rubik to install some CBMs.
3: Watch as the room erupts in blood and you go into horrible agony as the void reaches for you all while happily sedated.

### Expected behavior

I would expect that one is reasonably safe within the exodii fortress from the portal storm as they seem the most knowledgable about portal "wobbling" of any NPCs to date.  Either please add a small roof in front of the bars of rubik's "cage" to protect the player, move the player somewhere safe for the surgeries, or otherwise protect the player from storms.  When i first encountered this, there was no warning of the portal storm before i started the surgery.

### Screenshots

![image](https://user-images.githubusercontent.com/1490991/148718926-732506e5-432d-4d55-b9ec-652e3f3909bc.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 9b986bb [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Cataclysm++ [Cata++],
    Magiclysm [magiclysm],
    Gun Cotton [guncotton],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    More Survivor Stuff [more_survivor_stuff],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Mutation Changes [Mutation_Changes],
    Useful Helicopters Experimental [useful_helicopters],
    Stats Through Kills [stats_through_kills]
]

**Comment by Sirbab** [comment]
It occurs to me that in the future one could actually go in the door to the room he's in... but tbh i didn't notice that was a door before this happens.  I still hold this isn't ideal behavior.

**Comment by Ramza13** [comment]
Just to note, you can cause a portal storm via teh debug menu.  Under game you can rune eocs and if you activate EOC_CAUSE_PORTAL_STORM you will get one.
