### ISSUE TITLE
Only one refugee center on the map.

### ISSUE THREAD

**Issue by ZerroERR0R** [CleverRaven/Cataclysm-DDA#54246]
### Is your feature request related to a problem? Please describe.

Only one refugee for map please. It is pretty bad for the feel of game.

### Solution you would like.

Some limit to how much unique buildings or locations can be in the world.

### Additional context

https://user-images.githubusercontent.com/97457777/148791195-3b48e518-842c-4efb-8284-97b7ec1b1603.mp4

Damn portal storms totally destroyed time and space.

**Comment by NetSysFire** [comment]
This is intentional because the world is procedurally generated. The refugee center is not unique either.
