### ISSUE TITLE
Add Oxy-Gasoline Torch

### ISSUE THREAD

**Issue by sdasd30** [CleverRaven/Cataclysm-DDA#54255]
### Is your feature request related to a problem? Please describe.

Welding and cutting torches that use gasoline and oxygen exist in addition to acetylene torches. They are considerably less common than acetylene torches, with only about 20 in operation in the US around 1998 and none of them in New England but I think it would be reasonable that at least a few would exist in New England around this time.

Oxy-gasoline torches use pressured liquid gasoline and an oxygen supply. They apparently cut faster and more efficiently than regular acetylene torches, and of course, use gasoline.

### Solution you would like.

Add an Oxy-Gasoline torch. A fuel supply crafted from a tool with pressurization, a welding tank, gasoline and an oxygen tank.

Maybe make the fuel cost of this new torch lower to represent the higher efficiency?

### Describe alternatives you have considered.

Don't add an oxy-gasoline torch.

### Additional context

I found out about oxy-gasoline torches from this Wikipedia article.

https://en.wikipedia.org/wiki/Oxy-fuel_welding_and_cutting#Gasoline

https://www.dndkm.org/DOEKMDocuments/ITSR/DND/Oxy-Gasoline_Torch.pdf

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
