### ISSUE TITLE
Method of Gas Dispersion

### ISSUE THREAD

**Issue by JantDarvus** [CleverRaven/Cataclysm-DDA#54251]
### Is your feature request related to a problem? Please describe.

In the collapsed tower dungeon, almost every enemy explodes into huge gas clouds. Whilst the poison can be dealt with with some kind of gas mask, the gas clouds block vision and linger for up to an hour. Combined that with the very tight, maze-like interior and it's a recipe for tedium since your only options are to be blind the entire time or lots and lots of waiting for an hour in a corner for gas to clear.

### Solution you would like.

Either gas clouds in general to clear out faster, the enemies in the collapsed tower to create considerably less - or no - gas on death, or some way to clear gas clouds away.

### Describe alternatives you have considered.

Infrared vision being actually able to see through gas clouds would be a niche alternative, but I'm planning to bug report the lack of this anyway.

**Comment by LeahLuong** [comment]
I totally agree. This scenario wouldn't be so bad if the mission took place unroofed so the gas could dissipate more quickly. Or if toxic gas just dissipated faster in general. I went thru like 1000 gas mask charges completing this mission.

!!! SPOILERS AHEAD !!!

By they way, did you encounter hounds doing this?? I don't think they occur there naturally but that I got super unlucky. I stepped around a corner, got grabbed by hanging entrails, & they started drowning me in shallow water right away. Tried to break the grab, failed, & took another full bar of torso damage from drowning. Panicked & used the teleport CBM for the 1st time. It got me out of there but after taking 5 steps I got blinded by teleglow ectoplasm & the turn after was warned about the approaching hounds. I didn't know anything about them @ the time but was already in retreat mode. By the time I returned, it was wall-to-wall hounds; everything is a corner under the collapsed tower! Liberal use of the teleporter & a large helping of luck later got me into the nanofab chamber. I did dozens of teleports but only had to deal w/ getting gooed once & a fungal infection in the ensuing teleglow, lucky me.

**Comment by PatrikLundell** [comment]
Spoiler tangent: Teleporting can cause teleglow, which can summon hounds. Thus, nothing to do with the location, but all to do with teleporting.

**Comment by LeahLuong** [comment]
Yeah, that's why I said I thought I got super unlucky. Less than a min after 1 stack of teleglow & ectoplasm & hounds both proc'd.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
