### ISSUE TITLE
Infrared vision cannot see through smoke/gas

### ISSUE THREAD

**Issue by JantDarvus** [CleverRaven/Cataclysm-DDA#54253]
### Describe the bug

Infrared vision is unable to see through smoke or gas, one of the few situations where i'd have expected it to give you an advantage.

### Steps to reproduce

1. Use infrared goggles or infrared vision mutation on a survivor (tested using the mutation).
2. Throw down smoke, gas or similar.
3. Attempt to see a valid creature through it.

### Expected behavior

I would expect infrared vision to provide you with some visibility through smoke, toxic gas or similar gas clouds.

### Screenshots

![unknown 1](https://user-images.githubusercontent.com/45110965/148809963-fb07d4ac-f861-47e3-8d39-475dd3e43e1c.png)
![unknown 1](https://user-images.githubusercontent.com/45110965/148809996-71ec6834-0acb-4f2d-9b2b-40c4c5341a66.png)
![unknown 1](https://user-images.githubusercontent.com/45110965/148810025-e17e281c-4992-4bf3-8939-c774aca6fe0b.png)
In the above images, I am standing in smoke with a valid infrared vision target next to me.
If I move away one tile, it is no longer visible.
As proof infrared vision is working (albeit in another slightly buggy way?), moving closer so I can see it but activating optical dampeners to blind myself shows the target.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 1793043 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by hexagonrecursion** [comment]
Confirmed. Infrared vision is stopped by smoke

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: c8a49e1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Graphical Overmap [Graphical_Overmap]
]

**Comment by Night-Pryanik** [comment]
Why close? The bug is still here.

**Comment by LeahLuong** [comment]
I believe the IR CBM can see thru the toxic gas made by bloated Z's. May hold a clue as to how to code a fix.

@Night-Pryanik @Zireael07 Jant may've stopped playing &/or decided his issues were being ignored due to lack of activity on them.

**Comment by LeahLuong** [comment]
Here's a screenshot from my game in 0.F-3:

![Screenshot_20220206-143349](https://user-images.githubusercontent.com/91638992/152712497-8bb6b13c-0025-4916-a90c-c15a4cefeb29.png)

My IR CBM is picking up 2 mobs in the center of a smoke cloud. I believe thick smoke can block IR but, as it thins out, heat signatures can be picked out. Prob same thing for why I've been able to see thru toxic clouds w/ IR.

**Comment by Zireael07** [comment]
OP reported it on experimental, it's possible there was a regression
