### ISSUE TITLE
Washing kevlar sheets uses no water or cleanser

### ISSUE THREAD

**Issue by RegHog** [CleverRaven/Cataclysm-DDA#54262]
### Describe the bug

Washing any amount of kevlar sheets uses no soap or water.  I washed 567 for free.  Everything else seems to be washing correctly now after the recent change with 54099 following my previous bug report regarding washing of items.  I'm not sure whether this is a new problem brought in with this update or whether it was present all along.

### Steps to reproduce

1. Get some filthy kevlar sheets and a washing kit.
2. Use multi clean to wash the kevlar sheets.

### Expected behavior

Kevlar sheets should use soap and water when washed in a scaling amount depending on amount washed.

### Versions and configuration

Windows 10
Tiles
No mods
Latest experimental as of 10th january am.

**Comment by RoyBerube** [comment]
It has something to do with volume calculating incorrectly. A stack of 200 weighs 1kg as it should, but volume is only 0.01L when it should be 800ml. 5g and 4ml per unit as defined in json.

I noticed Lycra is affected by the same issue - volume is way too low.

**Comment by dseguin** [comment]
Looks like the problem is that `"count"` is 100. Setting `"count"` to 1 seems to fix it:

![vol_fix](https://user-images.githubusercontent.com/12537966/148861049-d178acf5-11a6-4555-a9a2-a497e1010ff7.png)
