### ISSUE TITLE
Confirmation dialogs which have a "safe" response should be case insensitive for that response

### ISSUE THREAD

**Issue by J-Fields** [CleverRaven/Cataclysm-DDA#54276]
### Is your feature request related to a problem? Please describe.

Take, for instance, the character creation UI. Pressing `<Esc>` gives you a prompt that reads
```
Return to the main menu? (Case Sensitive)
```
I'm likely to hit `n` on this menu, expecting it to cancel the action, but the only keys accepted by this menu are `Y` and `N`.

### Solution you would like.

Convert `Y/N` dialogs to `Y/n` dialogs when the "no" option is safe and the "yes" option is risky. "Safe" meaning no more than 1-2 keypresses to arrive at that same menu with the world exactly as it was.

### Describe alternatives you have considered.

Keeping the `Y/N` prompts.
IMO using `Y/n` where appropriate reduces friction as well as potential for user error (because the user can rely more on the heuristic that uppercase letters are for more intentional actions).

**Comment by LeahLuong** [comment]
I believe there is an option for this in the interface settings. Of course, "safety" is never considered because that's something relative.

**Comment by J-Fields** [comment]
> I believe there is an option for this in the interface settings.

Good point, I wasn't aware of that! `Force capital/modified letters in prompts`; defaults to `True`. I'd rather not disable that, though, as it presumably affects all case-sensitive prompts. I'm looking for something more targeted.

> Of course, "safety" is never considered because that's something relative.

Absolutely true, but I think there's a reasonable cutoff (as I said above, no game-changing side effects and very minimal inconvenience) where it is acceptable.

**Comment by GuardianDll** [comment]
I would be glad if there would be an option to add some new buttons for them, so i can bind "ignore all" not only for `I`, but also for `p`, `a` and `c`, for example (so i can shoot without using `I` anymore).

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
