### ISSUE TITLE
[Innawood] Make repairing more things possible

### ISSUE THREAD

**Issue by kurtisvetter** [CleverRaven/Cataclysm-DDA#54270]
### Is your feature request related to a problem? Please describe.

Currently, in the Innawood mod, the only repairing tools that can be crafted and used are the wood, bone, and curved needles. This means that only cloth (i.e. wool, cotton, leather, fur) items can be repaired. Thanks to #54149, cotton items can be repaired. However, this still leaves items made out of metal, wood, paper, plastic, or chitin unrepairable. This makes chitin or metal armor and metal weapons unviable to use. 

### Solution you would like.

Repairing wood, paper, and chitin would be possible if the misc repair kit is obtainable. Currently, it requires an x-acto knife, which is loot only. This could be fixed by making the x-acto knife craftable, removing it from the requirements, or requiring some other craftable item such as a survival knife or makeshift knife. 

As for metal items, I'm not sure what the solution should be, since they would normally require an arc welder, which doesn't seem feasible to craft from scratch in an innawoods scenario. Perhaps a new item like a "blacksmith's repair kit" could be added, similar to a firearm repair kit in that it is a combination of many other tools. 

The only craftable plastic item I could find that would need repairing is the safety glasses. The recipe for these has been changed to require glass instead of plastic, so they should be made out of the glass material. 

### Describe alternatives you have considered.

If plastic chunks are made craftable by making bleach or vinegar obtainable, it might be possible to craft more useful plastic items, in which case some other solution would be needed to repair those items.

**Comment by kurtisvetter** [comment]
I will try to fix the misc repair kit and safety glasses issue myself. An item to repair metal would probably need some C++ to implement, barring just adding the makeshift arc welder to innawood.

**Comment by Light-Wave** [comment]
> If plastic chunks are made craftable by making bleach or vinegar

You can craft  unfermented vinegar and make vinegar that way. A bigger problem is that no milkable animals are spawning, to my knowledge. I would love a way to make plastic in Innawood though.

**Comment by kurtisvetter** [comment]
> A bigger problem is that no milkable animals are spawning, to my knowledge.

I have found a few horses and chickens, and a sheep and a cow in my playthrough. I think they are just very rare and I got lucky!

**Comment by Light-Wave** [comment]
> I have found a few horses and chickens, and a sheep and a cow in my playthrough. I think they are just very rare and I got lucky!

Oh TIL. That should mean plastic is craftable. Neat.

**Comment by Light-Wave** [comment]
On further inspection, it seems like they may spawn around ponds. Good to know.

> An item to repair metal would probably need some C++ to implement, barring just adding the makeshift arc welder to innawood.

You could potentially make an item like arc welder, but have it not use any charges_per_use. Although maybe we want to consume charcoal while repairing? If so I don't know how to do that.

**Comment by kurtisvetter** [comment]
> Although maybe we want to consume charcoal while repairing? If so I don't know how to do that.

Actually I think I can do this. I'll try to add this to my pull request. Something like a hammer, a pair of tongs, and a fileset maybe, and it takes like 10 charcoal per try.
