### ISSUE TITLE
Allow crafting sock mitts from any socks

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#54281]
### Is your feature request related to a problem? Please describe.

The game currently has several kinds of socks, but you can only craft sock mitts from one of them.

### Solution you would like.

Add all types of socks as possible components to the recipe

### Describe alternatives you have considered.

Add several different kinds of sock mitts - one for every type of sock

### Additional context

Originally reported here: https://github.com/CleverRaven/Cataclysm-DDA/issues/51014#issuecomment-904024776

**Comment by LeahLuong** [comment]
Yeah! & make it so you can cut up wool onesies into arm warmers, leg warmers, & torso warmers while you're @ it! All the body parts deserve equally-modular warming components!
