### ISSUE TITLE
Sock mitts inherit (poor fit)

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#54282]
### Describe the bug

Crafting sock mitts out of a poorly fitted pair of socks produces poorly fitted sock mitts

### Steps to reproduce

1. Debug wish for a pair of socks.
2. Notice that it has the "(poor fit)" tag
3. Craft sock mitts
4. Notice that the sock mitts inherited the tag

### Expected behavior

How well a pair of socks fits my legs should have no impact on how well it fits my hands

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: e23fd18 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Graphical Overmap [Graphical_Overmap]
]

### Additional context

Originally reported here https://github.com/CleverRaven/Cataclysm-DDA/issues/51014#issuecomment-904024776

**Comment by LeahLuong** [comment]
IDK if I agree w/ this. Foot & hand size are proportional; a baggy pair of socks for your feet is likely to be baggy for your hands. It doesn't really swing the other way; too tight socks for your feet will prob fit your hands alright. Maybe enact a probability mechanic for poor fit socks being crafted into mitts: 1/3 chance they remain a poor fit following crafting. Perhaps a 1/3 chance they fit better than normal sock mitts. The game should model the reality of sock mitts as closely as possible so as not to disturb the suspension of disbelief.
