### ISSUE TITLE
Copper Circlet crafting produces excessive amounts of Tinder

### ISSUE THREAD

**Issue by LadyCatnip** [CleverRaven/Cataclysm-DDA#54280]
### Describe the bug

When crafting the Copper circlet in magiclysm it produces 2000 tinder (that's 10 liters of tinder and 20 kilograms) as a Byproduct despite only using 3 splintered wood to craft.

### Steps to reproduce

1. Make a Character with the Magiclysm mod enabled.
2. Acquire the materials needed to craft the copper circlet, and craft it.
3. Have your inventory filled with 10 liters of compacted tinder despite using only .75liters of splintered wood in the recipe.

### Expected behavior

I expected the crafting to produce a reasonable amount of tinder, because a good portion of the wood would've been used to construct the circlet, with only a small amount being wasted as a byproduct. The splintered wood that would've been wasted during the crafting of the circlet would only amount to ~.10l of material leftover.

### Screenshots

![41b8671c8baf087638880d1b9c15576b](https://user-images.githubusercontent.com/41288411/148886045-1094b444-3f33-4108-b487-fe5a593d1946.png)

### Versions and configuration

-Windows 10
-Game Version: 482fc79
-Graphics version: Tiles
-Ingame Language: English
-Mods loaded: Bionic Professions, Aftershock, Magiclysm, Disable NPC Needs, No Fungal Growth, Bionic Slots, Stats through Skills, SpeedyDex.

**Comment by Sirbab** [comment]
Confirmed on my end.  
![image](https://user-images.githubusercontent.com/1490991/148893057-3d28d780-d3df-458a-8cd3-83f0131dbe6d.png)

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 9b986bb [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Cataclysm++ [Cata++],
    Magiclysm [magiclysm],
    Gun Cotton [guncotton],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    More Survivor Stuff [more_survivor_stuff],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Mutation Changes [Mutation_Changes],
    Useful Helicopters Experimental [useful_helicopters],
    Stats Through Kills [stats_through_kills]
]

**Comment by casswedson** [comment]
Fixed by #54388

**Comment by TealcOneill** [comment]
@Maleclypse You can close this one, #54388 fixed it.
