### ISSUE TITLE
Add pretty, beautiful and very beautiful to Elf-a mutation line 

### ISSUE THREAD

**Issue by scavtoons** [CleverRaven/Cataclysm-DDA#54299]
### Describe the bug

Right now the elf-a mutation line doesn't have access to the line of beauty related traits to reach Glorious mutation, to be able to reach it you need to use normal or rabbit mutagen.

### Steps to reproduce

Make a player and spawn some elf-a mutagen,  you will never reach the glorious trait by using it.

### Expected behavior

Elf-a mutagen should have access to "PRETTY", "BEAUTIFUL", "BEAUTIFUL2" mutations to correctly complete its evolution, 

### Versions and configuration

OS: Windows
OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
Game Version: 189c4bf [64-bit]
Graphics Version: Tiles
Game Language: English [en]
Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
No Fungal Growth [no_fungal_growth],
Bionic Professions [package_bionic_professions],
Blaze Industries [blazeindustries],
C.R.I.T Expansion Mod [crt_expansion],
Magiclysm [magiclysm],
Extra Mutated Scenarios [extra_mut_scens],
Mythical Martial Arts [MMA],
Bionic Slots [cbm_slots]
]

**Comment by NetSysFire** [comment]
Hmm. It appears you can reach Beautiful if you already have Pretty though.

**Comment by anoobindisguise** [comment]
Mutations in a category will add their prerequisites first. You can see this in the debug mutation menu, if you add Glorious to your character you will see yourself get Pretty, Beautiful, etc in order, you don't need to have all the prerequisites in order to gain the mutation. As an example Cephalopod has only Insanely Smart and Insanely Dexterous but it can still gain the smart/dexterous mutations pre-threshold.

**Comment by Maleclypse** [comment]
Because Glorious is a post thresh mutation you cannot start becoming pretty, etc until you have gone post thresh in Elf, then mutagen will work to get in addition to serum.

**Comment by scavtoons** [comment]
> Mutations in a category will add their prerequisites first. You can see this in the debug mutation menu, if you add Glorious to your character you will see yourself get Pretty, Beautiful, etc in order, you don't need to have all the prerequisites defined as part of that tree in order to gain the mutation. As an example Cephalopod has only Insanely Smart and Insanely Dexterous but it can still gain the smart/dexterous mutations pre-threshold.

Oh then the bug would be glorious being reachable without threshold if you use other mutagens?  I reached glorious on a not elf-a post-threshold character when i was testing.

**Comment by Maleclypse** [comment]
> > Mutations in a category will add their prerequisites first. You can see this in the debug mutation menu, if you add Glorious to your character you will see yourself get Pretty, Beautiful, etc in order, you don't need to have all the prerequisites defined as part of that tree in order to gain the mutation. As an example Cephalopod has only Insanely Smart and Insanely Dexterous but it can still gain the smart/dexterous mutations pre-threshold.
> 
> Oh then the bug would be glorious being reachable without threshold if you use other mutagens? I reached glorious on a not elf-a post-threshold character when i was testing.

Regular mutagen and rabbit should be able to get Pretty before post thresh.
