### ISSUE TITLE
Remove the book that teach CBM ?

### ISSUE THREAD

**Issue by Zeropol** [CleverRaven/Cataclysm-DDA#54294]
### Describe the bug

If I understood, CBM are not earth made no more.
The book *Augmentative Tech Review* still teach some CBM recipes, and the description of the book implie CBM are a well known earthling thing.

### Steps to reproduce

1. Spawn *Augmentative Tech Review*

### Expected behavior

The book don't exists.
Or, the book is Exodii ( do they even use books, wich language do they use ? ) and the descriptioin reflect this.

### Screenshots

![image](https://user-images.githubusercontent.com/28099824/148934032-5375881e-7367-49af-88a4-5177074e477d.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: cfafb47 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    No Hope [no_hope],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Venera3** [comment]
There are a few errant bionic spawns as well that need to be scrubbed - an electric shop layout, military bunkers, labs, that sort of thing.

**Comment by Zeropol** [comment]
I found some CBM in *Mine entrance* indeed.

**Comment by Terrorforge** [comment]
That book only teaches CBM recipes if you're running Aftershock. In the base game, CBMs cannot be crafted.

**Comment by mkrutov** [comment]
I'd propose to move all that stuff to AFS, not scrap it.

**Comment by LeahLuong** [comment]
Isn't there also a lab text that teaches how to make CBM body armor??

**Comment by Maleclypse** [comment]
> I'd propose to move all that stuff to AFS, not scrap it.

It's already in Aftershock, those are Aftershock recipes.
