### ISSUE TITLE
Apply Vital Number section in Label and Classic sidebar

### ISSUE THREAD

**Issue by Proxima-b** [CleverRaven/Cataclysm-DDA#54298]
### Is your feature request related to a problem? Please describe.

I really love the old selfaware trait, now it can only be done by Vital number #54228
But that was not available to label and classic sidebar.

### Solution you would like.

Apply Vital Number section in Label and Classic sidebar

### Describe alternatives you have considered.

Make custom sidebar truely "customizable"

**Comment by ZhilkinSerg** [comment]
Label and Classic sidebars are hardcoded and are working differently from jsonized custom sidebar. It is not currently feasible to add widget support there. Eventually you can create custom sidebar similar to these hardcoded layouts, but we are not there yet.
