### ISSUE TITLE
Inconsistencies with 4 broken limbs

### ISSUE THREAD

**Issue by RegHog** [CleverRaven/Cataclysm-DDA#54295]
### Describe the bug

I am assuming surviving 4 broken limbs and the following story is a rare occurrence but having gone through the whole process there are a few inconsistencies with having 4 broken limbs I feel need addressing.

I managed to get into another fight with a zombie hulk and lost.  Well, I thought I'd lost.  I failed miserably at trying to shoot it and then failed at running into my fire truck escape vehicle to flee so the hulk bashed me about like a rag doll until all my 4 limbs were broken.  Luckily I was wearing US military vest with full plates and an army helmet so I wasn't immediately killed.  I was annoyed that my friendly NPC was happily standing by and watching all this carnage.  Then all of a sudden the Hulk got close enough to be bashed to death by the NPC.  My initial joy at surviving was rapidly fading after all the noise attracted a fat zombie who strolled over to my immobile body and started bashing my head in.  How ironic I thought that after surviving a hulk I would be finished by a fat Z.  I was just fast forwarding until death, still wondering why my NPC was not killing this fat zombie and instead just there stood watching me die.  With almost no HP left on my head the penny finally dropped and I realised I had told the NPC to only attack enemies it can reach without moving.  (I realised the hulk had earlier only been lucky enough to be killed when it strayed close enough.)  So I changed the command so she attacked everything freely and she then finished off the fat zombie and everything else that turned up on the scene from all the noise, allowing me to fill up on codeine, bandage my head and spend the next 12 hours to crawl back inside my fire station base.  Another noob error was not changing the NPC sleeping rules so halfway through this never ending crawl she upped and left to go to bed.  By this time I was blind as well but luckily no more Z's turned up to finish me off.

All this time I was never expecting to actually survive or if I did then how on earth was I going to be able to carry on as I needed to craft 4 splints and apply said splints with 4 broken limbs.  So I was surprised to find that not only was crafting the splints possible, but fixing them in place was just as easy.  What else was I able to craft I thought.  As it turned out, anything I wanted to and without any time penalty.  Happy to realise this I spent the next week, while I recovered, on a crafting spree, only stopping to eat drink and sleep.  Luckily I had a huge stash of food and drink to keep me and the NPC sated.

That's the back story.  I am now happily recovered and out killing Zed's again.  Here are my list of inconsistencies found from this experience:

1. I could not read any books as I was told I was 'too weak to wield' the item due to my broken arms.
2. Although I could start any crafting recipe I had the ingredients for, if the task was stopped or interrupted then I was unable to continue the craft as I was again 'too weak to wield' the item due to my broken arms.
3. I could not do any practice crafting recipes however, which is to be expected.
4. Most tasks that involved holding an item in the hands was impossible as I 'was too weak'.
5. I was able to wash any items I wanted to even though that would involve wielding a washing kit.
6. I was not able to feed my NPC directly by wielding an item but had to store it in my inventory and then trade it with the NPC so they ate and drank by themselves.
7. I could wear any item of clothing or armour I wanted to.
8. I could close the fire station main gates during my crawl back.
9. I could disassemble anything although as for crafting if I interrupted the task then I could not continue it due to 'weakness'.

All the time I was able to craft anything and everything I wanted and had the ingredients for as long as I completed it in one sitting without putting it down.

### Steps to reproduce

1.  Break all 4 limbs and test out what you can actually accomplish in this state.

### Expected behavior

I would expect everything in the game to be affected in the same way by having 4 broken limbs.  

Either:
A) If it is not possible to read or continue an already started craft then it should also not be possible to start any new crafts.  ie having 4 broken limbs allows you to do nothing.
OR
B) If it is possible to craft anything from scratch then it should also be possible to read a book, continue an already started craft or anything else.  ie having 4 broken limbs still allows you to do everything normally.

At the moment we have both of the 2 extremes in play.  This is not an easy fix, as from a realism perspective choosing option B is clearly ridiculous.  It should be almost impossible to do anything with 4 broken limbs and if it is then it should take a LOT longer to achieve.  However, this is a game after all and if we go for option A and not allow anything with 4 broken limbs then it is just a matter of time before the character dies and the exhilaration from surviving a zombie hulk attack with 4 broken limbs will slowly evaporate with a slow death.

What is my solution to this then?  I have a couple of ideas, one covering both of the extremes from A and B above:
1. I would argue that surviving with 4 broken limbs in the first place is only possible if you have at least one friendly NPC.  I am too new a player to know of any other way a player could survive.  I assume that if you have been bashed enough to have 4 broken limbs then you would be unable to finish off the monster that caused the breaks and so the monster would just slowly finish you off.  I suppose an explosion could cause this or falling off a building.  So assuming you have a friendly NPC that also survives then could it be possible to allow the player to swap to that character instead and then they could be responsible for looking after the recuperation of your original character.  So, in this scenario it would be impossible to do anything with 4 broken limbs and the NPC would take over the prime character role.  However, this would then need to allow the swapping back to the original character at some point and then we have the argument of allowing this for other situations and to be possible at any time in the game.  I read a PR a few weeks ago about swapping characters on death so maybe this should be possible at any time in the game.
2. Allow everything to be possible with 4 broken limbs but slow it down considerably (at least 90%), similar to the movement cost time penalty which appears scaled reasonably enough to me from a game perspective.

It all comes down to a happy balance between gameplay and realism.  At the moment we have both of these extremes in place and some changes are required.

### Versions and configuration

windows 10 tiles
latest experimentals over the last week
no mods

**Comment by Venera3** [comment]
Yeah, with all extremities broken you shouldn't do much more than scream (for help, and in general). Where crafting speed is concerned the problem is that it's governed by manipulation score, which lives on the hands, which don't lose HP (since they have none) and effectivity  even if their main part is broken. The rest is things being inconsistently routed through `has_two_arms_lifting` and/or `can_wield` (and activities inconsistently going through wielding the used item). 

Reading is an interesting question, since the *intention* is to have backup manipulators (at least your mouth, in your case) to handle such low-impact activities but they don't come into play because of the abovementioned problem. Switching to an NPC for the time would be a reasonable solution, but we'd also need a way to get your now-NP character into your getaway vehicle on the double, and we don't have that yet.

Good list, thanks for writing it up!

**Comment by RegHog** [comment]
I forgot to mention about how I'd like to deal with the carrying of another character.  For example, if your character has 4 broken limbs then they could 'pass out' or 'become incapacitated' and then a pop up comes up asking "Your character has passed out/become incapacitated.  Would you like to swap to a nearby NPC character."  If you say yes then you then become that character and your original character behaves exactly like a corpse that can be hauled or lifted to safety, whether that be a vehicle or nearby base.  There is then a certain amount of time available to save the life of that original character who will then behave like an NPC.  If you select "no" then a certain random length of time passes before your character might regain consciousness or even die or maybe you can just be allowed to do what I did and crawl to safety.  I suppose this idea could be used to incorporate a new "unconscious" state that could have been caused by severe head trauma instead for example, although that might make the game too hard for the single (no NPC helper) player if they kept passing out on their own and becoming easy prey for monsters....

Just to add a bit more about my comment about it being "impossible" to do anything with 4 broken limbs in real life, I would adjust that to say it could be possible to do quite a lot if your hands were not broken and all the limbs were splinted but just take longer.  eg light crafting and reading.  Just a question of how you would actually manage to get those 4 limbs splinted in the first place.  Even with 2 good hands it would be hard.  Do we need to add Hit points for Hands and have them totally separate?

Maybe I am just overthinking this and we could just assume that they are all hairline fractures that set in 5 days and it's no big deal.  In any case consistency is needed.
