### ISSUE TITLE
Weird partial vehicles appearing inside shelters and other odd locations

### ISSUE THREAD

**Issue by pjf** [CleverRaven/Cataclysm-DDA#54290]
### Describe the bug

While doing an explore I found a shelter that had weird partial vehicles both inside, outside, and *through* it. These came with a lot of short ropes on the ground, roughly where one would have expected seats to be.

![cataclysm-wheres-my-car](https://user-images.githubusercontent.com/12072/148910270-332ea332-4849-48a5-9f4e-63fffd899f10.png)

### Steps to reproduce

Have not tried to reproduce, but I've attached a save:

- [WeirdCarsInShelter.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7845030/WeirdCarsInShelter.zip)

### Expected behavior

Cars are only outside of shelters and other buildings, and their missing parts haven't completely disappeared into thin air.

### Versions and configuration

- e2b23c474d847f311cd4aca8b7865c0b0797d00b (`cdda-experimental-2022-01-11-0719`) with some local, non-vehicle patches applied.
- Using No Hope mod

Game report:

```
- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-5167-g0954d407c3 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Alternative Map Key [alt_map_key],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    No Hope [no_hope],
    Bionic Slots [cbm_slots]
]
```

### Additional context

PR #49105 has only recently been merged, and may be related.

**Comment by vfank** [comment]
I just came here to post about this issue and found this report. Here is a partial section of a security van in the middle of an otherwise completely empty field. I'm on a recent Linux experimental with no vehicle mods active.

![Screenshot_20220424_003209](https://user-images.githubusercontent.com/104066945/164956963-05b46c46-cd73-4b72-aab5-47ee94816134.png)

**Comment by pjf** [comment]
I should mention that reverting #49105 resolved this issue for me at the time. (However I haven't played in a few months, so I can't comment on how easy/hard a revert is with the current codebase.)

**Comment by pjf** [comment]
I haven't seen these for a while, so I'm going to mark this issue as closed, and I'll re-open if they somehow return.
