### ISSUE TITLE
The custom sidebar does not show mana

### ISSUE THREAD

**Issue by Proxima-b** [CleverRaven/Cataclysm-DDA#54297]
### Describe the bug

The custom sidebar widget does not show mana stat, and there's no option to enable it.

### Steps to reproduce

1.Start a game with magicalysm mod.
2.Press }.
3.Choose custom sidebar.
4.Cannot see mana.

### Expected behavior

Have option to show mana stat in custom sidebar.

### Versions and configuration

Latest experimental.

**Comment by LeahLuong** [comment]
@wapcaplet Another 1 for the Woadmap??

**Comment by wapcaplet** [comment]
Yes, this is part of the "Immediate" plan in #53957
