### ISSUE TITLE
Tow Cable not removable from vehicle after #53596

### ISSUE THREAD

**Issue by a-chancey** [CleverRaven/Cataclysm-DDA#54301]
### Describe the bug

Currently there's no way to remove a heavy duty tow cable without editing the map file that contains the vehicle and deleting it there, or just disassembling the part that the tow cable was attached to. This has another unintended consequence of making tow cables one time use items.

Additionally, the game still acts as if both vehicles still have the tow cable attached, so you can't attach another one. This still happens if you manage to break the connection somehow, I somehow broke it by adding more wheels to the lead tow vehicle while connected to the car being towed (as I couldn't pull it offroad)

### Steps to reproduce

Spawn two vehicles and a tow cable
attach the tow cable to both, which removes it from inventory
examine the space where the tow cable was connected - there's no option to disconnect the tow cable

### Expected behavior

When I examine the space where the tow cable was connected, i should be able to disconnect it and recieve the tow cable back.

### Versions and configuration

- OS: Windows 11
- Version: e2b23c4 (tiles) Build 2022-01-11-0719
- Graphics Version: Tiles
- In Game Language: English
- Mods Loaded: dda, no_npc_food, no_fungal_growth, package_bionic_professions, No_Rail_Stations

### Additional context

The towing seems to be working properly from #53596 (though I still disagree with towing cables providing braking and that should be moved to a new tow bar or tow hitch type of item). I just can't unhook without disassembling part of the vehicles.

**Comment by new02DAY** [comment]
Has it ever allowed you to (e)xamine vehicle and remove the tow cable? I've always entered the vehicle screen and removed the part. And that still works.

**Comment by a-chancey** [comment]
I’ll check again but mine doesn’t show up on the vehicle screen.

**Comment by chrispikula** [comment]
By examining it, they likely mean going directly to the attached tile, there should be a prompt then to remove the cable or examine the vehicle.

**Comment by PatrikLundell** [comment]
The #53596 change to towing is not an ideal solution. A proper solution would have terrain have a significant breaking effect based on terrain (which is currently not factored, with only a generic rolling resistance, probably on a completely flat, hard surface, but ideally each wheel should be checked individually) and weight, so a heavy vehicle has a higher momentum, but also a higher resistance to rolling (in particular on soft terrain) which would partially offset the momentum. That should cause a free rolling vehicle to slow to a stop over a reasonably distance. While realistic, it would be tedious to use as a player.
If you tried to tow a vehicle like that in real life you'd slow to a stop very gently, but the game's speed increments are too coarse for that purpose (but well suited for normal driving).
I think it would be possible to remove the braking component of #53596 and just keep the logic that doesn't pull the towed vehicle unless the cable was taut, which should allow you to move a few tiles forward as the coasting towed vehicle approached until it eventually actually stopped, but that would have left the weird behavior of a swinging towed vehicle somehow accelerating to ram the tower on gentle turns at a constant speed, so you'd have to figure out what causes that and address it.

**Comment by a-chancey** [comment]
Ok so I loaded the game this morning, no tow cable showed up in the vehicle screen. Saved and quit, reloaded it again and now it's there and I could remove it. I'm so confused. 

I guess this closes the issue because I can't reproduce it now, even after connecting multiple vehicles again.

**Comment by LeahLuong** [comment]
@a-chancey Aaron, as issue author you have the capability of closing this issue.

**Comment by a-chancey** [comment]
> @a-chancey Aaron, as issue author you have the capability of closing this issue.

Yeah I just hadn't seen the option on mobile. Closed it now
