### ISSUE TITLE
Vehicles block resuming partial deconstructions

### ISSUE THREAD

**Issue by VoleurVolant** [CleverRaven/Cataclysm-DDA#54317]
### Describe the bug

If you begin a deconstruction that is under a vehicle tile (a shopping cart that got stuck because it could be pulled *onto* but not *off of* tall grass) and interrupt it, `e`xamining the tile only offers vehicle prompts and not 'continue construction' prompts. 

### Steps to reproduce

Pull a shopping cart over onto a patch of grass of any length
`*`, remove thata tile of grass
Interrupt the process with `.`
`e`xamine the tile, observe that there is no prompt to continue removing the grass.

Remove the shopping cart. 
`e`xamine the tile, observe that there is now a prompt to continue the construction and if refused there is a followup prompt to cancel. 

### Expected behavior

I expected to be able to resume tasks that can normally be resumed. I *can* just move all my heavy things out of the shopping cart long enough to get it off the tile and put them back, so it's not game-breaking, but this seems like an interface error, rather than just a hassle. If it's not suppose to be possible to deconstruct grass under vehicles, then it being impossible to continue would make sense, but it should then be impossible to begin.

### Versions and configuration

ongoing issue, still present in 0.F-5229-g55b805eb93.

**Comment by hexagonrecursion** [comment]
Confirmed

![DeepinScreenshot_select-area_20220114134828](https://user-images.githubusercontent.com/52621858/149503487-aedc19b6-9c67-4f1f-a3a3-b401dcf7e129.png)

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: c8a49e1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Graphical Overmap [Graphical_Overmap]
]
