### ISSUE TITLE
Temporary files not ignored by git

### ISSUE THREAD

**Issue by matshou** [CleverRaven/Cataclysm-DDA#54324]
### Describe the bug

Some temporary files generated by Visual Studio 2019 are not ignored by git.

### Steps to reproduce

Temporary CMake files:

1. Open solution in Visual Studio 2019.
2. Open Solution Explorer view.
3. Click `Switch between solutions and available views` button.
4. Switch back from file to solution view by clicking the button again.
5. See a bunch of temporary files generated in `./out` directory.

Temporary source files:

1. Open solution in Visual Studio 2019.
2. Build and launch the game with release configuration.
3. Edit a source file such as `magic.cpp` while the game is running.
4. See temporary files generated in ` msvc-full-features/enc_temp_folder` directory.

### Expected behavior

I expected temporary files generated by Visual Studio to be ignored by git.

### Screenshots

![GitHubDesktop_wCqr6gs4oA](https://user-images.githubusercontent.com/16436920/149112525-3bad4b00-ddb9-4ef3-912a-802dd977c61d.png)

### Versions and configuration

- OS: Windows 10
- Game Version: 0.F-5137-g6b4b134cd3

### Additional context

Output of `git status` command after editing source files while debugging:

```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   src/magic.cpp

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        msvc-full-features/enc_temp_folder/
```

Output of `git status` command after switching views in Visual Studio:

```
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        out/
```

List of files in `out` directory:

```
 |-build
 | |-x64-Debug
 | | |-.cmake
 | | | |-api
 | | | | |-v1
 | | | | | |-query
 | | | | | | |-client-MicrosoftVS
 | | | | | | | |-query.json
 | | |-CMakeCache.txt
 | | |-CMakeFiles
 | | | |-3.20.21032501-MSVC_2
 | | | | |-CMakeCCompiler.cmake
 | | | | |-CMakeCXXCompiler.cmake
 | | | | |-CMakeDetermineCompilerABI_C.bin
 | | | | |-CMakeDetermineCompilerABI_CXX.bin
 | | | | |-CMakeRCCompiler.cmake
 | | | | |-CMakeSystem.cmake
 | | | | |-CompilerIdC
 | | | | | |-CMakeCCompilerId.c
 | | | | | |-CMakeCCompilerId.exe
 | | | | | |-CMakeCCompilerId.obj
 | | | | | |-tmp
 | | | | |-CompilerIdCXX
 | | | | | |-CMakeCXXCompilerId.cpp
 | | | | | |-CMakeCXXCompilerId.exe
 | | | | | |-CMakeCXXCompilerId.obj
 | | | | | |-tmp
 | | | |-cmake.check_cache
 | | | |-CMakeError.log
 | | | |-CMakeOutput.log
 | | | |-CMakeTmp
 | | | |-git-data
 | | | | |-grabRef.cmake
 | | | | |-HEAD
 | | | | |-head-ref
 | | | |-ShowIncludes
 | | | | |-foo.h
 | | | | |-main.c
 | | | | |-main.obj
 | | |-DartConfiguration.tcl
 | | |-Testing
 | | | |-Temporary
 | | |-VSInheritEnvironments.txt
```

**Comment by ZhilkinSerg** [comment]
Add anything you want to be ignored to your local `.gitignore` or create a pull request to add them to https://github.com/CleverRaven/Cataclysm-DDA/blob/master/.gitignore.
