### ISSUE TITLE
Multi Cooker Battery cannot be changed

### ISSUE THREAD

**Issue by estebandellasilva** [CleverRaven/Cataclysm-DDA#54330]
### Describe the bug

Multi Cooker has a Battery according to its description. It uses Medium Batteries as Magazines. But you cannot unload the Batteries and reload only offers  liquids to be stored inside the Multicooker.
Unload does not remove the Battery

### Steps to reproduce

Get a Multi Cooker
Make Sure its empty
Try to replace the Battery

### Expected behavior

Being able to unload the Multi Cooker to replace the Battery

### Screenshots

![image](https://user-images.githubusercontent.com/89189872/149180764-d5fa8c93-4da7-4cb4-847e-3b8d9faec908.png)
![image](https://user-images.githubusercontent.com/89189872/149180967-3aa4cc1f-2509-4a28-9b00-55addf96262f.png)
![image](https://user-images.githubusercontent.com/89189872/149181115-ff875338-dad8-47e1-9ed8-55d29b13f117.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 96e8d40 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

**Comment by anoobindisguise** [comment]
I can confirm it wouldn't let me unload the battery. The multi cooker also took somewhere about 1190 charges to produce a single piece of lard, that can't be right. It seems all kinds of broken. Perhaps it should be changed over to be an appliance?

**Comment by Alex-Folts** [comment]
I did tried:

- you can reload it with battery if it dosnt contain battery
- you can reload it if battery have not 100% of charge
- you cant unload battery at all

**Comment by Hirmuolio** [comment]
The unloading problem seems to be caused by #53250

**Comment by LeahLuong** [comment]
Temp workaround seems to be using 'r'eload to swap in a battery w/ more charge. Strange this issue was discovered when 'U'nloading isn't necessary to get a fresh battery in & also less efficient.

**Comment by estebandellasilva** [comment]
> Temp workaround seems to be using 'r'eload to swap in a battery w/ more charge. Strange this issue was discovered when 'U'nloading isn't necessary to get a fresh battery in & also less efficient.

Thats because i wasnt going to use it - i normally remove the battery if i want to to throw on my battery pile and then disassemble it if it has anything i want - and since i wasnt able to unload i postet this issue
