### ISSUE TITLE
Unknown Crash happened while walking

### ISSUE THREAD

**Issue by scraw-darkblade** [CleverRaven/Cataclysm-DDA#54331]
### Describe the bug

Unknown Crash happened while walking.

### Steps to reproduce

1. Load the game
2. Walk near the marked vehicle
3. Exact location: 1'109, 0'152 on map

### Expected behavior

It shouldn't crash while walking around the world.

### Screenshots

[Uploading report.zip…]()

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: a34653b [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

 DEBUG    : item_location lost its target item during a save/load cycle

 FUNCTION : void item_location::impl::ensure_unpacked() const
 FILE     : src/item_location.cpp
 LINE     : 115
 VERSION  : a34653b

******

Above error was also happened when I tried to save on location: 1'109, 0'152 on map
(Did not tried to other location though)

**Comment by Zireael07** [comment]
Note: you didn't actually upload the file.

**Comment by scraw-darkblade** [comment]
[report.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7858256/report.zip)
