### ISSUE TITLE
Faction editing via debug menu

### ISSUE THREAD

**Issue by JantDarvus** [CleverRaven/Cataclysm-DDA#54337]
### Is your feature request related to a problem? Please describe.

As in #36386 the faction of an npc can cause issues in some cases. Being able to alter their faction when editing the npc would allow a solution to that, and presumably just be useful as a debug tool in general. 

### Solution you would like.

When using debug to edit an npc, include their faction add an editable option.

### Describe alternatives you have considered.

No alternative springs to mind.

**Comment by Zireael07** [comment]
Why close?

**Comment by kevingranade** [comment]
Actually our policy is not to accept debug feature requests, so closing.
