### ISSUE TITLE
Make water heater drop heating elements

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#54334]
### Is your feature request related to a problem? Please describe.

When you bash f_water_heater you get:
* scrap metal
* chunk of steel
* sheet metal
* copper wire
* rubber hose
* copper tubing
* scrap copper
* water faucet

I assume the heaters are powered by electricity. If so, it should drop heating elements.

### Solution you would like.

Add heating elements to the water heater drop list

**Comment by coyo7e** [comment]
Or add a pilot light. Gas-powered water heaters are also quite common.

**Comment by Terrorforge** [comment]
They do produce a pilot light when you disassemble them, so apparently they're gas heaters.

**Comment by coyo7e** [comment]
Also I belatedly noticed that the OP mentions bashing it apart - so it destroys some of the pieces anyway, which I overlooked. I know there are a few household items that constantly bug me that they do not have pilot lights, like furnaces or stoves. ;)

**Comment by hexagonrecursion** [comment]
> They do produce a pilot light when you disassemble them, so apparently they're gas heaters.

I see. Sorry.

**Comment by Terrorforge** [comment]
Hey, I didn't know either. I just went to check if the disassembled version gave heating elements, saw the pilot light and thought "wait... do these run on gas? is that a real thing?"
