### ISSUE TITLE
Bloated corvids and oversized crows fight eachother

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#54340]
### Describe the bug

Their monster IDs, `mon_mutant_crow` and `mon_mutant_crow_small` even indicate that the latter is just an evolution of the former.

### Steps to reproduce

1. Spawn both an oversized crow and a bloated corvid.
2. Watch them fight.
3. Be as confused as I am.

### Expected behavior

They should not fight. I witnessed a murder of oversized crows with one bloated corvid being spawned in the wild and this just seems sort of unnatural. The cause for this seems to be the different species of them, `BIRD` for the oversized crow and `MUTANT` for the bloated corvid.

Not too sure if this is intended or not, this is why I added the need confirmation label for now.

### Versions and configuration

- experimental

**Comment by PatrikLundell** [comment]
I've seen that as well in 0.F-0 stable, so the issue itself isn't new (but I haven't written an issue for it).

**Comment by NetSysFire** [comment]
Setting both species to `MUTANT` should do the trick.

**Comment by jackster483** [comment]
Went ahead and set both species to mutant, they are still fighting. Would like to highlight that this is the first issue I have ever tried handling for CDDA, so more ideas would be appreciated.
