### ISSUE TITLE
Twisted Firestarter

### ISSUE THREAD

**Issue by LeahLuong** [CleverRaven/Cataclysm-DDA#54346]
### Describe the bug

The Finger Lighter CBM does not offer a prompt for lighting a fueled brazier as other firestarters do on 'e'xamining the brazier. Instead, 1 must open the bionics menu, activate the CBM, & target the brazier w/ it.

I searched this topic before posting & it seems this CBM has quite a history of this sort of problem: difficulty lighting kilns, smoking racks, lanterns, joints, cigarettes, candles, molotovs, etc. I don't believe all of these issues were resolved but here's another.

In addition, the CBM isn't recognized on the '%' menu when it comes to "starting a fire quickly".

Finally, the CBM's firestarting ability isn't recognized by the Pyromaniac trait. You get the morale boost from being near a fire but not the the primary boost of lighting the fire you get from other firestarting sources.

Is it possible to give the CBM a "lighter" flag or somesuch to resolve these issues @ once??

### Steps to reproduce

1. You're a firestarter.
2. Twisted firestarter.
3. ???
4. PROFIT!

### Expected behavior

I expected that Finger Lighter CBM level would increase, because all other skills can increase in level.

### Versions and configuration

Android 0.F-3 Tiles English vanilla

### Additional context

It's possible #47694 addressed this issue in the latest builds but, if I'm reading it correctly, that PR went into effect before 0.F's release & should apply to my version.

@Ramza13 Eric, I believe you looked @ the code for this relatively recently. Thoughts??

**Comment by hexagonrecursion** [comment]
> The Finger Lighter CBM does not offer a prompt for lighting a fueled brazier as other firestarters do on 'e'xamining the brazier.

I can not reproduce this bug

![DeepinScreenshot_select-area_20220115114440](https://user-images.githubusercontent.com/52621858/149615715-205a5230-1fda-4efa-a5c2-b1d1bfb10874.png)

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 28c767d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Graphical Overmap [Graphical_Overmap],
    allow-me-to-switch-control-to-followers [allow-me-to-switch-control-to-followers]
]

**Comment by LeahLuong** [comment]
0.F released on Jul 3, 2021. 0.F-3 released on Nov 27. It appears work on #47694 was completed on Jul 4. Did the PR need a backport tag to make it into the latest stable?? If so, I'll be less likely to post issues like this in the future. I tried to clear this up in the charcoal water purifier issue w/ Zhilk but he never got back to me despite being @'d.

@hexagonrecursion #47694 may've addressed the issue you tested for but did you check the other 2?? Namely, Finger Lighter not listing in the '%' menu & Pyromaniac missing out on a bonus.

**Comment by hexagonrecursion** [comment]
In the future please do not lump many bugs together even if they are related in some way. It is often the case that they are debugged and fixed separately. Lumping them together makes it hard to keep track of the troubleshooting process.

> Finger Lighter not listing in the '%' menu

![DeepinScreenshot_select-area_20220116090240](https://user-images.githubusercontent.com/52621858/149649212-a397164e-73cc-47e7-bb8f-ce35c668557f.png)

> Pyromaniac missing out on a bonus.

![DeepinScreenshot_select-area_20220116090425](https://user-images.githubusercontent.com/52621858/149649279-6ad7d174-b7ae-4f04-aba6-d6036cc1aec3.png)

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 56ae13e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by LeahLuong** [comment]
@hexagonrecursion I believe I have good reasons for clumping these issues:

1. The fix may be as simple as a missing flag for all of them.
2. These issues were presumably addressed largely by 1 person, Ramza13, whom I queried in the OP (& who still hasn't weighed in).

Something fishy is going on here. The primary reason & originating issue for this thread was not getting the brazier prompt. I've since double- & triple-checked it & it now _**does**_ give me the prompt for using the CBM. The other issues remain; CBM doesn't appear in the '%' menu nor am I getting the 1st Pyro bonus. It's not like I lacked power the 1st time & I am simply burning splintered wood in my test cases.

I'm on the verge of closing this issue because it seemingly works in the latest builds but I'd like help understanding some things 1st. The screenshot provided in the last post shows "electric firestarter" in the '%' menu instead of naming the CBM & 5 kJ as the cost. Shouldn't the CBM be named?? In the latest stable, I believe Finger Lighter activates for 3 kJ. Was it determined somewhere the cost _**should**_ be raised?? Finally, how does the chronology I outlined previously line up w/ what I'm seeing in my game?? Were some commits pushed out to 0.F-3 but others not??

Please help me understand how the timing of the commits work so I don't make irrelevant threads in the future.

**Comment by LeahLuong** [comment]
@wapcaplet Eric, I don't think this qualifies for the "S2" tag. Finger Lighter _**seems**_ to be working as intended for the latest build but I'm still trying to get a handle on a couple of things. Would be nice if Ramza13 could comment before I close the thread.

**Comment by Ramza13** [comment]
So if I remember correctly the reason it shows "electric firestarter" rather than the CBM name is because under the hood the cbm is actually pretending to be an "electric firestarter" item.  I'm guessing the cost change was in unifying things but its been a while and I don't remember exactly why it changed.  If you think the numbers don't make sense that would be a bug so feel free to open one.

**Comment by LeahLuong** [comment]
@Ramza13 Thanks for getting back to me. Can you help me understand the timeline before I close the thread?? I outlined the timing of #47694 above & don't understand why it didn't take effect for the latest stable, 0.F-3. I'd not have even opened this issue if its effects were working in my current game.

**Comment by Ramza13** [comment]
So I don't know the details.  
Looking at the PR history again what I think happened was this.  #47694 was merged into .F-dev which was eventually turned into the current in progress 0.G I think.  There was some back and forth between 0.F and 0.F-dev but I guess this didn't make the cut.  Since 0.F-dev existed at the same time as 0.F stable was being worked on the times overlap.  Any more details that that though I forget, there were all kinds of merges and chaos going on.

**Comment by LeahLuong** [comment]
@Ramza13 Eric, I appreciate the feedback. It's too bad the merging process isn't more transparent for people like myself. I understand this repo's emphasis on the latest builds but I think stable players form a large portion of the playerbase as well. I suppose it's inevitable, for now, that already-patched issues will occasionally be raised on the boards.
