### ISSUE TITLE
Debug Hammerspace does not place appliances

### ISSUE THREAD

**Issue by UmbralReaper** [CleverRaven/Cataclysm-DDA#54349]
### Describe the bug

During testing for #54348 I discovered that when you attempt to place appliances (e.g. Place Fridge) with Debug Hammerspace active, no appliances are placed.

### Steps to reproduce

1. Debug mutate yourself Debug Hammerspace
2. Open Construction menu
3. Attempt to Place Fridge
4. Realise no fridge was spawned

### Expected behavior

I expected that the fridge would be placed, as other furniture works (e.g. Place Table and Place Still).

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 6ae3e36 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by hexagonrecursion** [comment]
Confirmed. Vehicle construction used to have a similar bug #51547

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 28c767d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Graphical Overmap [Graphical_Overmap],
    allow-me-to-switch-control-to-followers [allow-me-to-switch-control-to-followers]
]

**Comment by wapcaplet** [comment]
@hexagonrecursion Thanks for your continuing efforts reproducing and confirming issues. Please feel free to ping me to change tags in cases like this.
