### ISSUE TITLE
Negative weight remaining in quiver

### ISSUE THREAD

**Issue by JantDarvus** [CleverRaven/Cataclysm-DDA#54359]
### Describe the bug

Quivers in the inventory menu appear to be have zero weight bearing capability, zero volume and max length of 0, and on loading with arrows are still at zero volume but have negative weight capability. The quiver still works fine, so this appears to just be a UI issue.

### Steps to reproduce

1. Equip a quiver
2. Look at it?

### Expected behavior

The quiver should display accurate information relevant to the pocket within it.

### Screenshots

![image](https://user-images.githubusercontent.com/45110965/149362533-838746e7-7fec-4565-ad66-08dc9aff26e2.png)
![image](https://user-images.githubusercontent.com/45110965/149362645-48671d0a-4d91-482e-bbc6-9227ae8a05dc.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 7ddf235 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by wapcaplet** [comment]
Confirmed, an empty quiver indicates it cannot hold anything:

![image](https://user-images.githubusercontent.com/238395/149526464-64465ba4-ffdc-4611-bd88-ca6e79dca916.png)

And if I do put some arrows in, it has negative weight remaining:

![image](https://user-images.githubusercontent.com/238395/149526574-564a4a40-baa2-48d8-b1ee-7daab0cf6d64.png)

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-5234-g380414c908 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Zireael07** [comment]
Why close? It's been confirmed and AFAICT hasn't been fixed yet...

**Comment by wapcaplet** [comment]
Still reproducible in 0.F-5759-g689dfa57de
