### ISSUE TITLE
Build fails without localization: "use of undeclared identifier 'TranslationManager'"

### ISSUE THREAD

**Issue by Weker01** [CleverRaven/Cataclysm-DDA#54360]
### Describe the bug

Building the current git HEAD fails on archlinux with
```
src/cata_utility.cpp:78:9: error: use of undeclared identifier 'TranslationManager'
    if( TranslationManager::GetInstance().GetCurrentLanguage() != "en" ||
        ^
```

Git blame says this line was changed with 5662c6d8f6e452aa3eef2f486977856cfc678179.

### Steps to reproduce

Clone the repo and build with either
`make TILES=1 SOUND=1 RELEASE=1 USE_HOME_DIR=1 CLANG=1 LTO=1 LOCALIZE=0`
or
`make TILES=1 SOUND=1 RELEASE=1 USE_HOME_DIR=1 CLANG=0 LTO=1 LOCALIZE=0`.
At least that is what I tested.

### Expected behavior

Building without error.

### Versions and configuration

Archlinux
current git HEAD 2d3692043ae19d144bd806d6bd6247d54ae7b094

**Comment by BrettDong** [comment]
Removing `LOCALIZE=0` temporarily workarounds the error.

**Comment by Weker01** [comment]
Yes, I can confirm that it does.
