### ISSUE TITLE
[User experience][NPC team commands] What does "prepare for danger do"?

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#54368]
### Is your feature request related to a problem? Please describe.

 "Tell everyone on the team to prepare for danger" is one of the items in the [C]hat with NPC menu. Unfortunately it is not obvious what it is supposed to do. The name is too ambiguous and there is no help message displayed while you are still in the menu. The only way to find out what it does is to actually issue the order and notice that it prints a chat message: "We're in danger.  Stay awake, stay close, don't go wandering off, and don't open any doors." This is not ideal: a player might not expect the documentation to be delivered in such a roundabout way.

### Solution you would like.

Add a place in the menu where a longer description can be displayed.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
