### ISSUE TITLE
Z-Level view violation when hallucinations attack eachother

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#54364]
### Describe the bug

A hallucinatory jabberwock attacked a hallucinatory NPC:
```
ERROR : src/monster.cpp:1599 [bool monster::melee_attack(Creature&, float)] Z-Level view violation: the jabberwock tried to attack Leoma Kellogg.
```

### Steps to reproduce

1. Hallucinate two monsters that attack eachother
2. See the debug asswerion

### Expected behavior

No debug assertions

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: c8a49e1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Graphical Overmap [Graphical_Overmap]
]

### Additional context

This may have been the real cause of #53678

**Comment by GuardianDll** [comment]
can confirm it, played with hallucinations and got ton of this errors, but it has no impact for player except the error message
