### ISSUE TITLE
I can send an imaginary friend on a camp mission

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#54369]
### Describe the bug

My hallucinatory allies can complete real camp missions

### Steps to reproduce

1. Get an imaginary friend
    1. Debug add effect "hallu" 20000 *not* permanent
    1. Walk around until you hallucinate an NPC. This may take a while. I do not know how to make this quick.
    2. Verify that you have met a hallucination and not a real NPC. Debug -> player -> edit player / NPC -> Status Window. In the top left corner it should say "John Doe | Male | Hallucination" (the name and gender are randomized, but the "| Hallucination" tag is always present)
    1. (optional) save, quit and backup your world
    2. Befriend the NPC. This may take a few tries. Note: I did not use debug mind control out of concern that it might interfere with the experiment
2. Use a real NPC to build a camp
3. Send your imaginary friend to gather materials
4. Profit (1 .410 hull, 1 hickory nut, 1 hickory root, 1 rock, 6 sticks)

### Expected behavior

You should not be able to assign a hallucination to perform a camp mission

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: c8a49e1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Graphical Overmap [Graphical_Overmap]
]

### Additional context

Related: #53677

**Comment by PatrikLundell** [comment]
And what happens if you send off your hallucination on something that takes longer than your hallucination state lasts?
(Would be fixed regardless when hallucinations are blocked from being sent on missions, so an answer to that question would just satisfy some idle curiosity).
