### ISSUE TITLE
Quest givers let you send imaginary friends on missions

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#54372]
### Describe the bug

The Tacoma ranch foreman and several other quest givers let you send your followers to complete missions. This currently includes your reality-challenged (imaginary) followers.

### Steps to reproduce

1. Get an imaginary friend
    1. Debug add effect "hallu" 20000 *not* permanent
    1. Walk around until you hallucinate an NPC. This may take a while. I do not know how to make this quick.
    2. Verify that you have met a hallucination and not a real NPC. Debug -> player -> edit player / NPC -> Status Window. In the top left corner it should say "John Doe | Male | Hallucination" (the name and gender are randomized, but the "| Hallucination" tag is always present)
    1. (optional) save, quit and backup your world
    2. Befriend the NPC. This may take a few tries. Note: I did not use debug mind control out of concern that it might interfere with the experiment
1. Talk to the ranch foreman or any NPC that lets you send NPCs on a mission
2. Send your imaginary friend on a mission (e.g. carpentry work)

    Alice S: Andrey does this sometimes too.

3. Profit

### Expected behavior

You should not be able to send a hallucinated NPC on a real mission

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: c8a49e1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Graphical Overmap [Graphical_Overmap]
]

### Additional context

Related: #53677

**Comment by LeahLuong** [comment]
Would be funny if the NPC's had simply noticed you were addled & were playing along w/ your pathological delusions so as not to become another 1 themselves.

This hallucinatory cow looks like it will never run out of milk.
