### ISSUE TITLE
magiclysm misspelling

### ISSUE THREAD

**Issue by TadhgEomonn** [CleverRaven/Cataclysm-DDA#54382]
### Describe the bug

In Valzain dialogue.

Valzain: What stories have you broght me?

broght => brought

### Steps to reproduce

Go to forge, speak with Valzain.

### Expected behavior

Correct misspelled word.

### Versions and configuration

- Win 10
-  600018f (tiles)
-  English

**Comment by NetSysFire** [comment]
It is trivial to contribute a typo fix even if you don't know git, just navigate to that file in the repo and edit it, github will do the magic. Consider contributing a fix if you have the time and energy for that

**Comment by TadhgEomonn** [comment]
If I knew which file contained the misspelled word and how to navigate to it in github, I would make the correction myself. Perhaps you can enlighten me, NetSysFire.

**Comment by NetSysFire** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/search?q=broght, just make sure to change the branch on the upper left when clicking on the file to master and you should be able to edit
