### ISSUE TITLE
Condoms are missing several traits in their description

### ISSUE THREAD

**Issue by JantDarvus** [CleverRaven/Cataclysm-DDA#54398]
### Describe the bug

Condoms are not listed as 'not rigid' like other non-rigid containers despite provably being non-rigid (other than the obvious 'common sense' telling you that). I think condoms are also waterproof containers in CDDA, which isn't displayed either, although I haven't tested this to double-check.
I'm reporting this in case this is some kind of UI bug rather than because I think people are going to be especially confused by the nature of condoms and need the explanation.

### Steps to reproduce

1. Grab a condom
2. Look at it the description

### Expected behavior

Condoms should have the line 'This item is not rigid. Its volume and encumbrance increase with contents.' 

### Screenshots

![image](https://user-images.githubusercontent.com/45110965/149554653-a172f770-2bb7-48a9-bc59-505cbf7b0c80.png)
Screenshot showing that they definitely are not rigid containers but also showing the lack of that note on their description.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 7ddf235 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by dseguin** [comment]
Looks like the fix is pretty straightforward:

```diff
diff --git a/src/item.cpp b/src/item.cpp
index 3c5435fd06..23e43e4edb 100644
--- a/src/item.cpp
+++ b/src/item.cpp
@@ -4788,6 +4788,7 @@ void item::final_info( std::vector<iteminfo> &info, const iteminfo_query *parts,
     insert_separation_line( info );
 
     if( parts->test( iteminfo_parts::BASE_RIGIDITY ) ) {
+        bool not_rigid = false;
         if( const islot_armor *t = find_armor_data() ) {
             bool any_encumb_increase = std::any_of( t->data.begin(), t->data.end(),
             []( const armor_portion_data & data ) {
@@ -4797,12 +4798,14 @@ void item::final_info( std::vector<iteminfo> &info, const iteminfo_query *parts,
                 info.emplace_back( "BASE",
                                    _( "* This item is <info>not rigid</info>.  Its"
                                       " volume and encumbrance increase with contents." ) );
-            } else if( !contents.all_pockets_rigid() ) {
-                info.emplace_back( "BASE",
-                                   _( "* This item is <info>not rigid</info>.  Its"
-                                      " volume increases with contents." ) );
+                not_rigid = true;
             }
         }
+        if( !not_rigid && !all_pockets_rigid() ) {
+            info.emplace_back( "BASE",
+                               _( "* This item is <info>not rigid</info>.  Its"
+                                  " volume increases with contents." ) );
+        }
     }
 
     if( parts->test( iteminfo_parts::DESCRIPTION_CONDUCTIVITY ) ) {
```

It also looks like waterproof is indicated by the `can contain a liquid` blurb in the pocket description
