### ISSUE TITLE
Add basecamp missions related to other factions (such as trade)

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#54395]
### Is your feature request related to a problem? Please describe.

I have a rather large faction, consisting of four basecamps (with plans to add more), and more followers than I care to count. Given this, I find it rather un-immersive that my character is the only person in the entire faction who does any sort of interaction with any other factions, outside of Tacoma Commune missions. Of course, being able to send someone out for trading would still make sense even for smaller player factions.

### Solution you would like.

I think that there should be basecamp missions involving trade and other interactions with other factions; these missions could be ongoing, like the gathering missions. Trade missions could be categorized by things like what you want to get from the trade (such as food, certain types of tools and raw materials, or just cold, hard cash), and could maybe involve a zone of some kind for goods to be traded for such things that you could put items into, and then add them to the faction "trade value," in a similar manner to how distributing food adds calories to the faction's larder, with "trade value" being deducted over time the longer the follower is on the mission. These missions could even give some usefulness to the storehouse expansion, which currently doesn't have any missions at all beyond actually constructing the storehouse, by being tied to the storehouse.

Aside from trade, there could be other missions as well. More nefarious faction leaders might send followers to raid other factions, which wouldn't deduct trade value, but would be much riskier, and would make the targeted faction hostile. An option for a disguised raid might also be considered, which would have a chance of not making the targeted faction hostile. On the opposite end, a particularly well-off and benevolent faction might even be able to send followers to provide humanitarian aid, deducting trade value and/or stored calories in order to improve relations with the selected faction.

### Describe alternatives you have considered.

Pretending that it's somehow realistic that my faction is the only large-ish post-apocalyptic faction that doesn't conduct large-ish scale trade with other factions

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
