### ISSUE TITLE
Blood Transfusions

### ISSUE THREAD

**Issue by JantDarvus** [CleverRaven/Cataclysm-DDA#54416]
### Is your feature request related to a problem? Please describe.

Currently, hypovolemic shock still has no option to transfuse blood (most obviously your own, to avoid type issues) to save yourself in a dire situation despite this being listed as the expected solution in the description text of severe hypovolemic shock: 'You've lost a tremendous amount of blood, and you're standing on death's door. Transfusion might save you.'

### Solution you would like.

Some way to transfuse blood, even if only your own blood until some way of blood typing (presumably via hospital equipment) is included.

### Describe alternatives you have considered.

Whilst it wouldn't solve the problem at all, I suppose 'remove the mention of a transfusion' from the status description would at least remove that confusion.

### Additional context

![image](https://user-images.githubusercontent.com/45110965/149584572-83bb272e-3c0c-43c9-81d3-ecb8fca8ca13.png)

**Comment by LeahLuong** [comment]
Blood type is already a char quality & hospitals do have blood analysis machines that lack typing capability. I like this feature request but don't forget that blood storage is likely to need refrigeration!

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
