### ISSUE TITLE
An unrealistic amount of information can be gleaned from a distance about some vehicle parts that should be internal.

### ISSUE THREAD

**Issue by VitreousEyes110** [CleverRaven/Cataclysm-DDA#54424]
### Is your feature request related to a problem? Please describe.

The amount of information that a player can glean about a vehicle from a distance of up to 50+ tiles is notably unrealistic. By looking at vehicles from long distances, you can determine:

- If a tank that ought to be hidden has fluid inside, and if so what that specific fluid is, as well as if it's draining.
- If a battery that ought to be hidden is intact, and if it's draining.
- If an engine that ought to be hidden is intact, and if it has a fault.

These are obviously not things you could determine just from looking at a vehicle from a distance. This allows for 'scanning' vehicles from range to determine if they're in working condition or have fuel, without ever having to even approach them.

### Solution you would like.

A system that hides some vehicle parts from view unless the vehicle is directly examined and the vehicle menu is opened. If a part is something that ought to be internal, and it's in the same space as another part that ought to function as an exterior that conceals parts, then the internal part shouldn't be viewable from a distance.

- Exterior parts could completely hide the internal parts with no additional info, maybe something showing that they _can_ hide parts, but not whether or not they actually are.
- Exterior parts could display that they are hiding parts, but not specify what specific parts they're hiding, maybe how many they're hiding. Maybe something like "Quarterpanel (Hidden Parts)" or "Quarterpanel (2 Hidden)".
- All internal parts could still display, but without any additional info outside of their name such as repair level, faults, draining, fluid level, etc. Maybe indented underneath the concealing part similar to how container contents are displayed.

Whether or not a part is considered internal or a concealing exterior could be either hard-coded into each part, or maybe be something decided upon player installation or when the vehicle is spawned.

### Describe alternatives you have considered.

- Leaving things as they are. There's already some things that can't be discerned from a distance, like what specific fault an engine has, how charged a battery is, and how much fluid a tank contains, and that could be considered enough hidden information from a fun standpoint. Hiding more would mean players _having_ to individually walk up to vehicles to determine if they're drivable instead of being able to do it from range.
- Requiring manually popping the hoods of vehicles to see some parts, and relying on fuel gauges instead of knowing the exact amount of fluid in a tank. This would be even more realistic but seems like it could be excessive, in hiding information from the player, in added keystrokes and oversimulation, and in amount of work to implement.
- Completely hide all vehicle part information outside of the vehicle menu. This is excessive and would hide reasonably ascertainable information like the state of the tires, doors, seats, controls, etc.

### Additional context

Hiding this sort of information would not be an insignificant gameplay change, especially in the early game when players are hunting for working/near working vehicles. I'm very interested in what others think about this, and what solutions others may have.

**Comment by jeanpaulrsoucy** [comment]
Would hidden information be revealed from a distance for vehicles the player has already examined?

**Comment by VitreousEyes110** [comment]
> Would hidden information be revealed from a distance for vehicles the player has already examined?

It's relatively minor but I think internal parts should remain unviewable from a distance even if the player has previously examined the vehicle, mainly because the status of those parts can change. For example, if the player has examined a vehicle with a draining fuel tank, goes away for a bit and then returns, they shouldn't know if the fuel tank has become empty without re-examining it. Or in the same vein, if the player returns to find zombies bashing at their vehicle, unless the exterior part has been destroyed revealing the internal parts then they shouldn't know if their battery or engine has been damaged until they re-examine.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
