### ISSUE TITLE
Incorrect Construction Menu Description for  "Chop Log Into Planks"

### ISSUE THREAD

**Issue by coyo7e** [CleverRaven/Cataclysm-DDA#54427]
### Describe the bug

The "result" description for turning logs into planks via Construction Menu describes dirt, instead. It may have been copy pasted accidentally from another construction option, but it's unrelated to the action.

### Steps to reproduce

1. open Construction menu, go to Farming & Woodcutting or search for "plank" 
2. read item description in menu.

### Expected behavior

expected it to talk about planks, not dirt.

### Screenshots

![image](https://user-images.githubusercontent.com/80022377/149604924-3414c996-8f90-46c2-acb2-3143444cbaee.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 600018f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by NetSysFire** [comment]
The reason why it does so because the construction menu describes what tile is the end result: In this specific case you chop the tree trunk into bits and all that remains is dirt.

**Comment by LeahLuong** [comment]
But perhaps it's deeper than that! In the end,  so _**many**_ things are simply dirt . . .
