### ISSUE TITLE
Enhance Debug Life Support to reflect new Basic Life Requirements

### ISSUE THREAD

**Issue by VoleurVolant** [CleverRaven/Cataclysm-DDA#54431]
### Is your feature request related to a problem? Please describe.

The Debug Life Support mutation does not prevent the slow degradation of the cardio stat over time, and does not prevent the gradual loss of dietary vitamins. Getting scurvy and becoming too out of shape to run or engage in combat while testing things is a bit of a bummer.

### Solution you would like.

Expand the functions of Debug Life Support to include a 'freeze' on cardio and dietary vitamins.

**Comment by wapcaplet** [comment]
Can you provide steps to demonstrate how you know that "Debug Life Support" is not maintaining cardio?

**Comment by TealcOneill** [comment]
@GuardianDll I turned this on and then waited several weeks, never saw any nutrient issues and cardio didn't reduce at all.
