### ISSUE TITLE
Beginner Build errors: Makefile and Cmake 

### ISSUE THREAD

**Issue by paulwratt** [CleverRaven/Cataclysm-DDA#54436]
### Describe the bug

```
At global scope:
cc1plus: error: unrecognized command line option ‘-Wno-unknown-warning-option’ [-Werror]
cc1plus: all warnings being treated as errors
make: *** [Makefile:948: obj/tiles/achievement.o] Error 1
```
Really? does no one test these "fixes"?

and
```
cc1plus: error: pch/main-pch.hpp.gch: not used because `LOCALIZE' not defined [-Werror=invalid-pch]
cc1plus: error: unrecognized command line option ‘-Wno-unknown-warning-option’ [-Werror]
cc1plus: all warnings being treated as errors
make: *** [Makefile:948: obj/tiles/active_item_cache.o] Error 1
```
(`make ... LOCALIZE=1` then ^C (break build) then `make ... LOCALIZE=0`

### Steps to reproduce

follow instructions here for linux (- gettext) :
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/COMPILING/COMPILING.md

`make RELEASE=1 TILES=1 SOUND=1 LOCALIZE=0`

### Expected behavior

I expect the build scripts to function, at least to the level as described in the docs.

Why does `ASTYLE=0` _still_ try to run `astyle` (1st line of build output, if not found)?
Why does `LINTJSON=0` _still_ try to build `tools/format/json_formatter.cgi`

and why do you have to use `-DLOCALIZE=OFF` (not in the docs) for `cmake` and `LOCALIZE=0` (in the docs) for `make`

The are _not_ the sort of errors regular project devs are going to see (on avarage).

### Versions and configuration

generic

With commits locked for `0.G` this is a great time for someone to give the default build scripts (and their docs) some love, and we are talking _tweaks_ . The builds are really close to working out of the box, but you would not know that unless you have had more than _tertiary_ experience with either of them.

### Additional context

If someone were to ask nicely, I might be to at least be able to supply some PR's for simple _noob_ or _new to project_ mistakes like:
* not trying to execute `astyle` if its not present, set `ASTYLE=0`
* not testing for `astyle` if `ASTYLE=0` is set
* not building `tools/format/json_formatter.cgi` if `LINTJSON=0` is set
* not error out in previous build built with localization and now `LOCALIZE=0` is set
* add `make depends` to build and/or set those first

(I have power for a few days, so I can do this atm)

**Comment by BrettDong** [comment]
You are trying to use pre-compiled headers from a different build configuration and of course you get compile errors.

**Comment by ZhilkinSerg** [comment]
This is not an attitude we want from a contributor. Also you have provided very little useful information - no compiler version, no game version or commit hash you have used.

**Comment by paulwratt** [comment]
- OS: 
```
$ uname -a
Linux raspberrypi 5.10.63-v8+ #1496 SMP PREEMPT Wed Dec 1 15:59:46 GMT 2021 aarch64 GNU/Linux
$ gcc --version
gcc (Raspbian 8.3.0-6+rpi1) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
$ g++ --std=c++14
g++: fatal error: no input files
compilation terminated.
```
its generic.

Someone was just gonna blame some part of my OS or GCC as being the culprit.

It appears `DEBUG=0` causes most problems outside what I described above.

`./build $ cmake ../ -DLOCALIZE=OFF && make` builds till 67% and fails with `error: 2` in the tiles source.

Thesea are really basic build fails stemming from documentation and Makefile comments. Stuff u are _not_ gonna see if u are a regular project dev.

**Comment by BrettDong** [comment]
Your using precompiled headers in an incompatible build configuration to compile the project is your problem, not your OS's or your GCC's problem.

**Comment by esotericist** [comment]
> (`make ... LOCALIZE=1` then ^C (break build) then `make ... LOCALIZE=0`

just for someone else who might stumble over this and wonder about brettdong's replies:

if you change the invocation flags for make in a fashion like this (enabling/disabling features, optimization levels, etc) between builds without running `make clean` in between you are doing it wrong, and any errors that occur are not the responsiblity of anyone except the operator of the machine where the errors occur.

as for @paulwratt : this grade of hostility is the opposite of constructive. please reconsider how you approach things, and a good first step would be asking questions like "is it possible i have done something incorrectly" before assuming incompetence on the part of the other parties. (subsequent steps include asking *other* questions before assuming incompetence on the part of the other parties, and ideally not assuming incompetence at all).

**Comment by paulwratt** [comment]
re: "pre compiled headers" = (.pch) - ie. part of the _project_ build process.

OK, but _why_, there is no `libgettext-dev` so how is it even possible (with `LOCALIZE=1` the project default).

The `Makefile` says "Enable DEBUG if used with GDB", so I set `DEBUG=0`, which breaks the build.

even with `ASTYLE=0` it still has an "not found" on the first line of if its not installed, why?

_project devs_ and _package maintainers_ are _NOT_ going to see these issues, are they?

I realise _now_ that the Cmake build is _unofficial_, but have one make system _explicitly_ use ON/OFF an the other use 1/0 _breaks_ continuity in building. (maybe _that_ is just an opinion).

I saw you have "feature freeze" to release a version "0.G", so _maybe_ someone can spend some time making Cmake official _and_ cleaning up the `Makefile` (or even add `Makefile.for-dummies` which turns _OFF_ debug, localize, astyle, lintjson, runtests, and turns release _ON_).

BTW I got it to build by stripping the 1st _and_ last lines in the WARNINGS variable. It builds and runs fine with tiles and sound, from the git repo root.

**Comment by esotericist** [comment]
you still have a great number of misapprehensions, but i'm not interested in investing more time and energy into this as long as you are approaching the conversation with the attitude you are exhibiting.

your original issue was user error, please don't continue to rant in a closed issue.

if you want to ask questions to learn about any rationale relevant to specific elements of the build process, you might consider discussions in the development discord. but only if you're willing to assume a degree of competence and good faith. if you aren't prepared to do that, i ask you spend your time elsewhere.
