### ISSUE TITLE
QoL: Wait for followers when automoving

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#54434]
### Is your feature request related to a problem? Please describe.

The convoy moves at the speed of the slowest ship. If you automove with an NPC that is slower than you, the NPC gradually lags further and further behind.

### Solution you would like.

1. When the follower lags too far (e.g. 1.5 the distance she is supposed to follow you at), pause to wait for him
2. Print a chat message: "You wait for Jane Doe to catch up"

### Describe alternatives you have considered.

The current workaround is to move in short bursts and press 5 a bunch (make sure to have safe mode enabled!)

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
