### ISSUE TITLE
Add Propane/natural gas Trucks and Vehicles to Mine parking lots.

### ISSUE THREAD

**Issue by JonathanLochridge** [CleverRaven/Cataclysm-DDA#54433]
### Is your feature request related to a problem? Please describe.

I noticed that Propane had been added to the game. Propane vehicles are kind of a pet interest of mine. So, I thought I might suggest adding propane vehicles. Around where I am propane vehicles are used extensively by mining and drilling companies.(Not New England but US). Due to how depending on the Geography they often end up having to pump out natural gas pockets for safety. And they can save money by compressing it and using it on site to fuel vehicles. Although, it isn't worth pumping or shipping somewhere else generally.

### Solution you would like.

Add Propane tanks and vehicles to Mines. 

### Additional context

#54143 and #54066 are relevant to the topic.
I could probably add propane tanks to the mines as a loose drop when I have the time. Since they should already be implemented. assuming it is okay. But, I am unsure how I would edit the maps to add on map tanks? Assume they would be a large tanks size? Although, in that case they would act more as a potential obstacle than a useful feature.
There would be specialized hoses to transfer the pressurized contents.
although, if no one was opposed to it a simple spigot could be used as a short term measure?

**Comment by Drew4484** [comment]
These are on my to do list, but I won't get to them for a while. Intending to add standing tanks as furniture, a vehicle cooker part, and as a fuel option for certain engines. I've worked adjacent to propane vehicles but never done a conversion myself, so if you've got some familiarity with it I'd gladly take the help.

**Comment by JonathanLochridge** [comment]
Well, I haven't done a conversion yet. But, I am hoping to do one soon once I have the means. But, my best friend works with design related to refueling devices at mines. He works for a manufacturer of the devices.

Most conversion kits are for bifuel deisel vehicles. They have both a propane tank and a diesel tank usually. But they use the diesel sparingly. But, you can fit more energy per weight with compressed propane than diesel. But usually unless designed as dedicated engines. There are like 4-5 proper conversion kits for gasoline cars. And they have to be converted fully to propane. They aren't that popular. 

Although, the few on the open market sell for a lot. Even if the base car isn't that much. Pretty much any car can be converted with specialist skills without a dedicated kit. But, pretty much only people who are really into those cars or work with propane might know how to do that. So I think it would be simpler to not implement a method to convert vehicles. and just have them spawn as a pre-existing engine type. Although, once you had one setup adding extra tanks. Or replicating the same setup with the same engine in another car wouldn't be that hard. 

The main difficulty is that the types of hoses and connectors you need to hook it up changes from engine to engine. Also, getting a proper connector for connecting to a fueling location. You could run one off of normal propane canisters but that would be a bit inconvenient to work with but easier to setup. With that setup you would have two canisters and a section of pipe you could close with a valve running to each of them. And when one went out you would switch to the other and swap the empty one. 
this is probably the only setup type a non-specialist could make without a kit for their specific car. Although, maybe once I learn more I could discover a more practical way to replicate a kit?

But if you worked near them you might know more than I do.

**Comment by Drew4484** [comment]
Mostly an issue of how to represent it in game, probably sufficient to add the tank and include language in the description about any connection changes. That way we don't require new engines or adding new systems/layers to vehicles.

**Comment by JonathanLochridge** [comment]
Yeah, I agree that sounds fairly simple.
Although, simply adding the standing tanks as an extra propane supply would be cool. 
Currently reading through the location contributor guides.
An extra layer seems overkill.
Although, maybe have only particular engine sizes/types able to work with a propane tank? And we could maybe abstract part of it away by making pipes needed for install and having a connected proficiency you could learn from a book?
But, I know there is a toyota compact conversion kit. as well as one for mid-sized loading trucks. (Dump trucks, box trucks, etc.)

Also a slightly related idea would be to have methane generators on some dairy farms?
once we get the standing tanks.

**Comment by Drew4484** [comment]
Really any fuel gas is fair game, I added propane because it's common with gas forges. Syngas and Natural Gas are viable.

**Comment by JonathanLochridge** [comment]
Yeah, I guess technically Most of the cars I know of are actually natural gas run rather than propane.
although, I know there are actual propane vehicles?
Not sure how common they are?

**Comment by Alex-Folts** [comment]
If engines had mods(like guns have), we could add LPG kit as mod for a gasoline engine, which expand accepted fuels list with propane. Because essentially IRL those kits just add extra option for use another fuel. Similar mod could be done for methane gas, if at some point we will have it. Ethanol as fuel option could be added with such fuel mod too.

Having it as a mod means you can remove it from one engine and add to another, so you could salvage this kits it from cars you found on a road.

**Comment by JonathanLochridge** [comment]
Cool idea? Something like that is probably big enough that it wouldn't get merged until after 0.G.
Have you made an issue for that idea?
@Alex-Folts 

Although, I have heard some disparaging remarks towards how the mod system works from the main devs. So they may not be eager to do that.

**Comment by Alex-Folts** [comment]
> Cool idea? Something like that is probably big enough that it wouldn't get merged until after 0.G. Have you made an issue for that idea? @Alex-Folts

Not yet, i had this idea of engine mods before, but most potential mods had no gameplay value(things like turbochargers, water-methanol injection, intercoolers, nitrous oxide), this one with extra fuel options are first decent mod which would be actually useful in current game realities. Though i'd look for other useful engine mods before suggesting such mod system.

**Comment by JonathanLochridge** [comment]
Hmm, yeah that would be cool to do some brainstorming about. If I think of any I will let you know.
I wonder if it would work for letting steam engines use wood at lower effectiveness?

Although, to a degree I could see some of those features working fine as their own parts rather than an actual mod.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
