### ISSUE TITLE
Makeshift Drive Belt has Mechanics as a required skill twice

### ISSUE THREAD

**Issue by JantDarvus** [CleverRaven/Cataclysm-DDA#54448]
### Describe the bug

Makeshift Drive Belt lists Mechanics 2 as the primary skill but also Mechanics 1 as an 'Other' skill.

### Steps to reproduce

1. Make a character and have access to the recipe
2. Behold the oddness

### Expected behavior

Either Mechanics 2 to be the only thing listed or something else to be required in Other skills

### Screenshots

![image](https://user-images.githubusercontent.com/45110965/149631299-94184117-5317-4755-b2f2-bbf4ddc2feba.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 7ddf235 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by J-Fields** [comment]
Seems like this is because it's got `"skill_used": "mechanics"`, `"difficulty": 2`, and `"skills_required": [ "mechanics", 1 ]`. This also seems to be the case for at least `filter_air_makeshift` and `filter_liquid_makeshift`.

I assume this is unintended. Should we check for this situation in our automatic JSON validation? (I'd be happy to do so, if someone would point me toward that code).

**Comment by Alex-Folts** [comment]
Should be fabrication 1, or survival 1.

**Comment by leemuar** [comment]
Without mechanics skill? Making things for transport should require you to have mechanics knowledge. It's not about just making things, it's making for working mechanisms, thus mechanics required

> Should be fabrication 1(or survival 1) instead.

**Comment by Alex-Folts** [comment]
> Without mechanics skill? Making things for transport should require you to have mechanics knowledge. It's not about just making things, it's making for working mechanisms, thus mechanics required
> 
> > Should be fabrication 1(or survival 1) instead.

Instead of "mechanics 1" should be "fabrication 1". I was talking about "other skills". "Mechanics 2" already specified as primary skill.
The only thing i'm not sure - should it be fabrication or survival skill.

**Comment by leemuar** [comment]
Oh, sorry, I got it now. I vote for fabrication

> Instead of "mechanics 1" should be "fabrication 1". I was talking about "other skills". "Mechanics 2" already specified as primary skill. The only thing i'm not sure - should it be fabrication or survival skill.

**Comment by JantDarvus** [comment]
I just want to add that it seems the makeshift engine parts aren't alone. I just noticed that both Steel Plating and Steel Plate list Fabrication as both the Primary and Other skills. There may be a few like this hiding around, maybe need to automate rooting these out. Someone checking on stable showed that it didn't have it listed as both skills on those, however, so I'm not sure how it got introduced.
