### ISSUE TITLE
I don't know what to say for TALK_FREE_MERCHANTS_MERCHANT_Merch

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#54443]
### Describe the bug

I got the following error when talking to a refugee center merchant:
```
 DEBUG    : I don't know what to say for TALK_FREE_MERCHANTS_MERCHANT_Merch. (BUG (npctalk.cpp:dynamic_line))

 FUNCTION : std::__cxx11::string dialogue::dynamic_line(const talk_topic&) const
 FILE     : src/npctalk.cpp
 LINE     : 1127
 VERSION  : 28c767d
```

### Steps to reproduce

1. Talk to the merchant
2. Buy some merch
3. "I wanted to talk"
4. What's with these 'free merchant certified notes'?
5. Get the above assertion

### Expected behavior

No debug assertion

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 28c767d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Graphical Overmap [Graphical_Overmap]
]

**Comment by PatrikLundell** [comment]
I think line 121 of data/json/npcs/refugee_center/surface_staff/Smokes/free_merchant_shopkeep_talk.json should have a topic of TALK_FREE_MERCHANTS_MERCHANT_AboutMerch rather than TALK_FREE_MERCHANTS_MERCHANT_Merch.
