### ISSUE TITLE
User interface: communicate the "holster: true" pocket restriction (e.g. on a duffel bag)

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#54440]
### Is your feature request related to a problem? Please describe.

Some containers have a "holster: true" pocket. Example:

https://github.com/CleverRaven/Cataclysm-DDA/blob/e62f9be6610edd4b1d6036940fac6da89f46d141/data/json/items/armor/storage.json#L706-L741

> https://github.com/CleverRaven/Cataclysm-DDA/blob/293b3265ad767ccc665550391bfd511551fdfa41/doc/JSON_INFO.md
> "holster": false,                 // Default false. If true, only one stack of items can be placed inside this pocket, or one item if that item is not count_by_charges.

This restriction is not currently communicated in the item description:

![DeepinScreenshot_select-area_20220115112736](https://user-images.githubusercontent.com/52621858/149615234-e07705c1-a4e1-4c63-8541-74ceb7878683.png)

This results in a situation where it may be unclear to the player why an item refuses to go into a given pocket. This certainly did confuse me.

### Solution you would like.

Add a line saying: "this pocket can only contain one item"

**Comment by LeahLuong** [comment]
I believe the hiking backpack _**does**_ have holster pockets. There, the pockets delineate that items must fit in a sheath or have a minimum size or something. The duffel bag's pocket's holster quality is set to false; no further restrictions are placed on its single pocket beyond the duffel's mass, volume, & length restrictions. I'm pretty sure this "feature" already exists.

**Comment by hexagonrecursion** [comment]
> The duffel bag's pocket's holster quality is set to false

Nope. Read again:

https://github.com/CleverRaven/Cataclysm-DDA/blob/e62f9be6610edd4b1d6036940fac6da89f46d141/data/json/items/armor/storage.json#L728-L740

> no further restrictions are placed on its **single** pocket

Look at the screenshot and read the code again: there are *two* pockets. This is latest experimental.

**Comment by LeahLuong** [comment]
@hexagonrecursion You're right. I didn't scroll down far enough nor did I realize they'd added a pocket to the duffel in the latest builds. This issue may only apply to pockets updated recently. You may want to change the title of the thread to reflect that.
