### ISSUE TITLE
Critical error.

### ISSUE THREAD

**Issue by CEHA** [CleverRaven/Cataclysm-DDA#54447]
### Describe the bug

After installing from Google play I'm having error.

### Steps to reproduce

1 - Install.
2 - Game unpack resources.
3 - Have error.

### Expected behavior

Experimental build working fine after add 4 game staring options.

### Screenshots

Stable https://ibb.co/L0nZDSg
Error https://ibb.co/VMd6p9Q
Experimental https://ibb.co/VMd6p9Q

### Versions and configuration

Try stable version fom here and Google play, Install x64 version.
Android 5
Phone MEIZU m2

### Additional context

My phone have only one physical back button, maybe game can't find others and going to error.

**Comment by BrettDong** [comment]
Android 5 is too old for stable version. Either upgrade your Android OS version, or play experimental.
