### ISSUE TITLE
While Reading, No Warning Prompt From Seeing Zombie or Hearing Repeated Noises

### ISSUE THREAD

**Issue by coyo7e** [CleverRaven/Cataclysm-DDA#54456]
### Describe the bug

I was reading a book in my car in the daytime, 30+ squares away from a town. Suddenly I heard a machine-gun speed series of "wham!" noises and a zombie burst through the side of the car before I could hit Num5 to try and pause. I had ignored a water strider which was far out on the edge of my vision, but nothing else.

### Steps to reproduce

1. Start reading.
2.  Have zombie come toward you.

### Expected behavior

Expected warning that zombie had been spotted, or a warning of the noise of it bashing it's way through my car wall **300+ times.**

### Screenshots

![image](https://user-images.githubusercontent.com/80022377/149637526-8b9193bc-85c0-45fa-beb8-b00b47d55064.png)
![image](https://user-images.githubusercontent.com/80022377/149637537-36258858-2ae2-4ffd-bfe5-80ab259415a4.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: f1997bf [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by NetSysFire** [comment]
![image](https://user-images.githubusercontent.com/59517351/149644046-cb58ade1-01de-4b5d-86f3-7bad0d7cfedc.png)

![image](https://user-images.githubusercontent.com/59517351/149644032-6d3437d2-2115-4701-b4e5-cbaf2f77004d.png)

Can not reproduce. Check your safe mode ruleset. I wonder if it might be related to vehicles though.

**Comment by hexagonrecursion** [comment]
@coyo7e, are you able to reproduce this? If so, please describe the _exact_ steps to reproduce this bug.

**Comment by LeahLuong** [comment]
You can tell from the OP screenshots safe mode is off. This should prob be closed & chalked up to user error.

**Comment by hexagonrecursion** [comment]
safemode is irrelevant here. I **do** get a prompt when I see a zombie while reading even if safemode is off. This is why I asked for the exact steps to reproduce the bug.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 3f48036 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Night-Pryanik** [comment]
Closing as unconfirmed.
