### ISSUE TITLE
Aftershock Exoplanet doesn't spawn mutant child in TCL, no way to access research light green zone.

### ISSUE THREAD

**Issue by Chadtholomew** [CleverRaven/Cataclysm-DDA#54453]
### Describe the bug

In an exoplanet world, it doesn't spawn a mutant child in the medical zone so you can't progress into the light green zone because that's the only way to get a light green zone badge. 

### Steps to reproduce

1. Make a world with Exoplanet mod
2. Progress through the TCL
3. Get stuck

### Expected behavior

I expected to find a way to get into that zone without destructive means

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 21.2.1; Codename: Qonos; 
- Game Version: e2b23c47 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Aftershock: Exoplanet [aftershock_exoplanet]
]

**Comment by Maleclypse** [comment]
Thanks for letting me know that the blacklist needs to have the TCL added to it.  Hopefully one day we can do a whitelist so that only exoplanet locations appear in the exoplanet mod.

**Comment by John-Candlebury** [comment]
TLC doenst spawn in the exoplanet no more
