### ISSUE TITLE
Portal Storm Enemies Pushing character to Extreme Exhaustion

### ISSUE THREAD

**Issue by coyo7e** [CleverRaven/Cataclysm-DDA#54463]
### Describe the bug

I noticed that if you get stuck bandaging or stuff and get hit a bunch of times by portal storm enemies, you quickly end up at "Exhausted" however, it appears that the tiredness keeps going down. I'm not sure how far this goes, but after sleeping for 36 hours straight with no breaks except to eat, I finally got the character back up to "Tired" after some portal enemies caught me bandaging. 

This is extraordinarily unfun and can take quite a long time IRL if your character is in an area that has a lot going on (like near the refugee camp, near active faction camp, etc), and I'm not sure if it's intended to force a player to sleep for 10-20 minutes of IRL playtime to recover from enemies which only deal exhaustion.

### Steps to reproduce

1. Get hit to "Exhausted" by portal storm enemies.
2. Get hit some more.
3. Sleep until recovered.

### Expected behavior

Expected to be able to recover from Exhaustion after 18 hours of sleep.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: f1997bf [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by LeahLuong** [comment]
This may be related to #53644. How did you bandage?? 'E' or activation from inv?? It's also possible this type of attack simply needs a warning prompt.

**Comment by coyo7e** [comment]
'a'ctivating bandage. It's unrelated to the bandaging, as far as I can tell. 

I had this happen once before with a new character that got caught walking across a great big field while searching for a vehicle, and I accidentally swung a heavy backpack and got hit a ton of times - after that the character was so exhausted it was a downward spiral which I just bore out and had to sleep it off for well over 24-36 hours (in 4 hour increments because he started with a bad infection, so I lost track of how long it took the first time).

The attacks do give a message about draining you, and with ultica at least it causes the flash on your sprite (same as when a zombie child dies, or other effects hit you which seems a new feature that's pretty helpful.)

I don't mind being drained of tiredness to the point I've got to crawl to cover, it just feels like there's no floor to how badly you can get drained or maybe the floor is so low that it just feels that way - I was literally falling asleep while driving and stuff while trying to get to base lol

**Comment by hexagonrecursion** [comment]
Confirmed: it is possible to become so tired that you have to sleep for several days before you are fully rested - not the most exciting gameplay.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 56ae13e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by LeahLuong** [comment]
As noted in #53644, activating bandages can bypass warning prompts. Now the question is whether you get warning prompts for this sort of attack. You shouldn't get them while launching attacks using cumbersome items but prob should while doing non-combat-related, time-consuming activities.

In any case, there prob should be a lower bound for how tired these entities can make you.

**Comment by I-am-Erk** [comment]
I would suggest perhaps that the attack add an Effect to the player for 5-10 seconds, "drained" eg, and if you have the "drained" effect the creatures ignore you. That would limit how quickly you can accrue fatigue and stop you from getting ganked. Adding a lower limit to the effect is probably pretty hard to do, but if not we could do that instead.

**Comment by Night-Pryanik** [comment]
Fixed by #62431.
