### ISSUE TITLE
Powered quarterstaff does not work

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#54475]
### Describe the bug

Powered quarterstaff:

> This is an ironshod quarterstaff that has a high-voltage stun gun built into the handle.  The stun gun is wired to the metal caps at either end of the staff, allowing you to zap a dangerous opponent should beating them senseless with it prove too hazardous.

When I [a]ctivate it I get a message like "You shock the zombie" and battery charge is drained, but I do not notice any effect on the zombie.__

### Steps to reproduce

1. Debug wish for a powered quarterstaff
2. Load it with a battery
3. Spawn a zombie
4. [a]ctivate the staff
5. Look at the zombie

![DeepinScreenshot_select-area_20220116114343](https://user-images.githubusercontent.com/52621858/149653197-9c88aca2-1183-483a-a7e3-10dce38e6c22.png)

### Expected behavior

I expected a condition (e.g. "Shocked") to be displayed when I look at the zombie.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 56ae13e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by GoLoT** [comment]
Zombies have natural resistances to electricity now (as of #53736) and the zapped effect chance is based on damage dealt. It's possible that before the changes it relied on doing 1 point of electric damage and causing the zapped effect (it used to be guaranteed for any damage) and now it has to be rebalanced.

I'd say changing it to deal 5-10 electric damage should do it without breaking balance.

**Comment by LeahLuong** [comment]
Yeah, I tried this out before & found it to be garbage compared to ironshod. Possible edge use case where a hostile NPC has a sliver of torso health remaining; shock rarely misses (if ever??), penetrates armor, & deals torso damage. Still prob empties the battery & doesn't kill them. Minimal zap effect means they get to clobber you while you're repeatedly tazing them. Def could use a rebalance!

**Comment by anoobindisguise** [comment]
It should be deducting moves from them. The effect is more pronounced against tiny targets, those should be skipping multiple turns when zapped. When I was trying to make stun guns use a more realistic amount of charge (not 100kJ, real stun guns use like 25j) Kevin also instructed me to make the player's stun gun not do damage. And zombies aren't deterred by pain, making it unfortunately rather useless.
