### ISSUE TITLE
Powered tools lose qualities when convered to UPS

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#54471]
### Describe the bug

#52304 changed tools s.t. that they need charges to provide certain tool qualities.
This means that they don't work at all if you put a UPS mod into them.

### Steps to reproduce

Get an cordless drill and some sheet metal.
Learn all recipes.
Can make a draw plate.  (Req's drilling 2.)
Put a UPS on, fully charged, and put a ups conversion kit onto the drill.
Can no longer make draw plate.

### Expected behavior

That you can use a cord-converted cordless drill, and not just stare at it in concern.

### Screenshots

![image](https://user-images.githubusercontent.com/22281606/149647096-a3b4c872-5d4b-4470-9f84-8b6e1f5c9a8c.png)
![image](https://user-images.githubusercontent.com/22281606/149647106-2e53a104-682d-48a4-b2f8-fd6867f04255.png)

### Versions and configuration

Win 10, tiles, a34653b

I did mod my UPS to take a heavy battery mod, but that's about all that touches anything in this.

**Comment by wapcaplet** [comment]
The `ammo_remaining()` function should be including UPS charges, so I'm puzzled why it would report no charges:

https://github.com/CleverRaven/Cataclysm-DDA/blob/56ae13e791d1ca2320d12653c6c302cda2d568e6/src/item.cpp#L9627-L9630

**Comment by chrispikula** [comment]
Hmmm.  My only changes to the UPS were to remove the flags "NO_UNLOAD", "NO_RELOAD", and it does work for powering other UPS equipment, like the food dehydrator and arc welder.  Replacing those two tags does not re-enable the functionality, even with a fresh UPS that has no battery mod compartment added.

The only other thing I used my UPS for that's a bit uncommon was that I used it to cable charge my bionic power storage, but that shouldn't do anything after you remove the cable, yeah?

**Comment by wapcaplet** [comment]
I don't have much experience with UPS and admittedly didn't test it with the charged-tools PR, so I'm sure there's some other odd factor at play here. Will take a look tomorrow.

**Comment by hexagonrecursion** [comment]
Confirmed

![DeepinScreenshot_select-area_20220116100240](https://user-images.githubusercontent.com/52621858/149650648-aff5a0fe-fb3f-401a-829b-86fb79b7061b.png)

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 56ae13e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by Hirmuolio** [comment]
The `ammo_remaining()` needs to have the carrier as argument for it to see info of the carrier (for example how much UPS the carrier has.

So just changing all instances of `ammo_remaining()` into something like `ammo_remaining( carrier)` should fix this.

**Comment by Alex-Folts** [comment]
Offtopic, but why "drilling" quality require charges while "screw driving" dont? Is it part of this bug, or it is intended behavior?

**Comment by wapcaplet** [comment]
> Offtopic, but why "drilling" quality require charges while "screw driving" dont? Is it part of this bug, or it is intended behavior?

My thinking was that as long as you have a screw driving bit, a cordless drill can still be used (manually, unpowered) as a really awkward screwdriver, but can’t feasibly drill holes without power just by twisting your wrist.
