### ISSUE TITLE
Makeshift Bandage Does Not Train Health Care

### ISSUE THREAD

**Issue by coyo7e** [CleverRaven/Cataclysm-DDA#54473]
### Describe the bug

Refer to title - I noticed that all the lowish level medical supplies a player can make (except cattail jelly, which uses survival of course) rely on health care skill.. Except for the first one, makeshift bandage, which uses Tailoring. Even boiled/bleached makeshift bandages train healthcare. There are a number of level 0 tailoring items a player can make with rags, so it seems sort of redundant to have makeshift bandages tailoring as well.

This seems like a possible oversight which sometimes ends up with players making a huge batch and then re-applying them to a limb over and over to train to Health Care 1 - I saw two people posting that they spam-use makeshift bandages on themselves to train healthcare, although I never do that myself because it's crushingly boring imho. Boiling though can fail at skill 0, which means you waste tons of items.

I don't mind crafting an item and taking it apart repeatedly, or boiling my bandaids but the incremental gain of spamming bandages on onesself is quite slow even though rags are basically free and nearly unlimited once you can find a couple mattresses or chairs.

In my screenshot, you can see that all recipes requiring healthcare are orange because I'm still at 0 health care and they ALL require 1+ in the skill. It's not a huge huge hassle to bleach or boil some makeshift bandaids but it seems a little out of place that basic makeshifts aren't healthcare skill. I also wasted something like 180 makeshift bandages trying to craft boiled ones, despite it saying I wasted the water I also wasted the bandages each failure.

### Steps to reproduce

1. Obtain rags.
2. Open Craft Menu -> Makeshift Bandages.
3. Observe that it uses tailoring.

### Expected behavior

Expected Makeshift Bandages to raise healthcare skill above 0.

### Screenshots

![image](https://user-images.githubusercontent.com/80022377/149650698-1f1a14b6-3532-446a-b27a-fa37dbe0b10e.png)
![image](https://user-images.githubusercontent.com/80022377/149651102-7ec87810-68a2-4985-be6d-2bef587ef949.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: f1997bf [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Venera3** [comment]
What is the level of medical knowledge reasonably gleaned by pointing at a rag and going "you're a bandage now"?

**Comment by VitreousEyes110** [comment]
> This seems like a possible oversight which sometimes ends up with players making a huge batch and then re-applying them to a limb over and over to train to Health Care 1 - I saw two people posting that they spam-use makeshift bandages on themselves to train healthcare, although I never do that myself because it's crushingly boring imho. Boiling though can fail at skill 0, which means you waste tons of items.
> I don't mind crafting an item and taking it apart repeatedly, or boiling my bandaids but the incremental gain of spamming bandages on onesself is quite slow even though rags are basically free and nearly unlimited once you can find a couple mattresses or chairs.

The 'bandaging (beginner)' practice recipe allows training up from 0 to 1 health care with just makeshift bandages, and has no book/knowledge prerequisites.
![Screenshot (352)](https://user-images.githubusercontent.com/45680256/149652678-7c33b2fa-d8d1-4f82-9559-afeecebdb115.png)

The makeshift bandage recipe seems to just be using your bare hands to rip/tighten a .25L .18lb loose cloth rag into a .03L .15lb dense cloth bandage, and takes only nine seconds. I agree with Venera that it doesn't seem like something that would give insight on treating wounds, basic tailoring knowledge seems apt.

**Comment by coyo7e** [comment]
Beginner bandaging takes almost 90 minutes each shot. Making a makeshift bandage takes what, 12 seconds?

**Comment by VitreousEyes110** [comment]
> Beginner bandaging takes almost 90 minutes each shot. Making a makeshift bandage takes what, 12 seconds?

Practice recipes are done in 60 minute increments, spending components every hour interval. This doesn't mean that it takes an hour to gain a level in the skill being practiced, I'm fairly sure the xp gain over time during practicing is identical to a non-practice crafting recipe of the same difficulty. Testing with a fresh default character with 100 focus, it took ~3 minutes to go from health care 0 to 1. Presumaby it would take an identical amount of time to train from 0 to 1 if a batch of health care training makeshift bandages were crafted.

**Comment by LeahLuong** [comment]
This thread should prob be closed given the functionality of practice recipes. The gane used to be different but it seems to be in an improved state now. Stronger reasons than, "I'd like to go back to grinding makeshift bandages to get Health Care 1," need to be brought in order to revert the game to its previous state.

**Comment by wapcaplet** [comment]
Agreed, I think it's working as intended. Crafting bandages of any kind might teach you some interesting things about fabric and adhesives, but I can't see any reason it would teach you anything about health care.
