### ISSUE TITLE
Diary arrow key navigation

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#54472]
### Describe the bug

Using the up/down arrow keys moves the cursor up and to the right, and down and to the left, respectively.  End/Home key isn't standardized, and Pg Up/Pg Down don't do anything.  
The cursor also highlights the visible character after your typing location.  Which makes it a bit non-intuitive to figure out how to insert new characters or lines mid entry.

### Steps to reproduce

Type a block of text.
Use the arrow keys, and watch the cursor dance.

### Expected behavior

Up/down/left/right would work appropriately.  As well, Home/End/Pg Up/Pg Down should make sense.  That is, home/end should move to the start and end of line, rather than top and bottom of page.  PgUp/PgDown should be start and end of text entry, respectively.  This would be in line with most text editors while using short documents, yeah?

### Screenshots

Starting Position:
![image](https://user-images.githubusercontent.com/22281606/149648207-d987207e-6946-4cad-b37e-dd5a15541b23.png)
Up arrow:
![image](https://user-images.githubusercontent.com/22281606/149648219-4ccc1e96-0a03-4407-9968-9193fa3dc921.png)
Two Down arrows:
![image](https://user-images.githubusercontent.com/22281606/149648223-f4a74079-0533-4edd-8ee0-eee2c8c85e94.png)
Return to original position:
![image](https://user-images.githubusercontent.com/22281606/149648334-206fd3ab-f59e-4df9-b905-7dd25adeefbd.png)
Typing 123
![image](https://user-images.githubusercontent.com/22281606/149648246-f1a73d71-318c-4285-b39f-8fac4c837e00.png)
Two Left arrows:
![image](https://user-images.githubusercontent.com/22281606/149648257-0cffec88-8618-4ba8-95ad-7af86621fca6.png)
Four Right arrows:
![image](https://user-images.githubusercontent.com/22281606/149648261-bc0d3aa4-bef8-43c9-853c-0ca2d327be6d.png)

### Versions and configuration

Win 10,
Tiles,
v. a34653b
Don't think any mods can even touch the diary, but quite a few.

**Comment by J-Fields** [comment]
Can confirm. In testing I found other issues as well, `string_editor_window` at a minimum seems to be very broken.

I've maintained a vim emulator for a few years now so I should be able to fix it up 🙃

**Comment by pjf** [comment]
> I've maintained a vim emulator for a few years now so I should be able to fix it up upside_down_face

I never knew I wanted vim keybindings in the CDDA in-game diary until now. Thank you!

**Comment by J-Fields** [comment]
> I never knew I wanted vim keybindings in the CDDA in-game diary until now. Thank you!

Hahaha that would be awesome but for now I'm just planning on fixing it up so it works as you'd expect a more casual text editor to
