### ISSUE TITLE
Gram's vorpal strike technique does not work

### ISSUE THREAD

**Issue by Naadn** [CleverRaven/Cataclysm-DDA#54479]
### Describe the bug

In Magiclysm mod, Gram is a sword with vorpal strike technique that you can make from orichalcum. But no matter how many time I crit with  it, it always do normal crit damage instead the x99 vorpal strike as it said on description.

### Steps to reproduce

1. Obtain a Gram 
2. Wield it
3. Spawn some zombies
4. hit them until you get a crit

### Expected behavior

It do the cut damage multiply by 99 as it's description said.

### Screenshots

![image](https://user-images.githubusercontent.com/97841551/149667236-4bc5f836-78be-4741-ab4c-8383dfec575c.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 380414c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills],
    Bionic Professions [package_bionic_professions],
    C.R.I.T Expansion Mod [crt_expansion],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Extra Mutated Scenarios [extra_mut_scens],
    Mythical Martial Arts [MMA],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm]
]

**Comment by Venera3** [comment]
Vorpal strikes have a technique weight of `-250`, meaning they are only included in the melee tech roll 0.4% of the time. Assuming Magiclysm changes nothing about the tech itself fixing it is a one-line Good First Issue.

**Comment by LeahLuong** [comment]
Could this in any way be related to #52869?? Personally, I'd like to see the tech placed back in vanilla seeing as it's such a niche thing & no discussion was had prior to removing it.

**Comment by ZhilkinSerg** [comment]
> Could this in any way be related to #52869?? Personally, I'd like to see the tech placed back in vanilla seeing as it's such a niche thing & no discussion was had prior to removing it.

It is not related.
