### ISSUE TITLE
Allow folowers to read books from a e-inc tablet

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#54474]
### Is your feature request related to a problem? Please describe.

You can tell a follower to "please study from a book". This works for regular books, but not for books stored in a e-inc tablet.

### Solution you would like.

Make it possible for NPC followers to learn from books stored in a e-inc tablet

**Comment by LeahLuong** [comment]
Would also be nice if they continued reading even after attaining a lvl of proficiency. As it is, they put the book down as soon as they lvl up & require you to prompt them to continue reading.

**Comment by hexagonrecursion** [comment]
> Would also be nice if they continued reading even after attaining a lvl of proficiency. As it is, they put the book down as soon as they lvl up & require you to prompt them to continue reading. They should prob stop if they are no longer learning from a book.

Please report this as a separate issue.

**Comment by LeahLuong** [comment]
No need, this was feature requested years ago in #39129. #46679 is also a relevant thread. Just thought I'd give the ol' dead horse another whack.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
