### ISSUE TITLE
Crash upon starting a new game

### ISSUE THREAD

**Issue by moxian** [CleverRaven/Cataclysm-DDA#54489]
### Describe the bug

Started a new game, walked around a bit, realized i chose suboptimal background, suicided;

Started a new game -> preset character -> last character -> tweaked stats a tiny bit (got +nicotine addiction, and +to mechanics; probably irrelevant) -> tab tab tab -> crash. Attached.

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7878052/crash.log)

### Steps to reproduce

Does not reproduce

### Expected behavior

No crash.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 56ae13e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Alex-Folts** [comment]
You started with second character in the same world right?

**Comment by moxian** [comment]
No, the world was freshly created, since i have "World end handling" set to "Delete"

**Comment by dseguin** [comment]
Going by the stack trace in the crash log, this looks like the same bug as #53103. See `map::build_seen_cache(tripoint const&, int)` on line # 8.

**Comment by wapcaplet** [comment]
See also #52300
