### ISSUE TITLE
Add a notification which go when boats are at risk of sinkage 

### ISSUE THREAD

**Issue by JonathanLochridge** [CleverRaven/Cataclysm-DDA#54498]
### Is your feature request related to a problem? Please describe.

I realized that if boats go even slightly overweight they sink. Which is understandable. However, I think that not having feedback that something might go overweight is bad.

### Solution you would like.

Add a series of warning pop-ups for things which might cause a boat to go over it's weight limit.
1. stepping on a boat when the player weight with items is enough to sink it
2. log entries or warning when weight is at 90% of max for the boat(potentially configurable amount?)

### Describe alternatives you have considered.

Add something to the description of prebuilt boats to make the weight-sinking mechanics more clear to newer players. (Say people who do a magiclysm wizard island start.)

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
