### ISSUE TITLE
Thief mode enabled should enable picking up "stolen/owned items" with AIM

### ISSUE THREAD

**Issue by ElfLeaderMike** [CleverRaven/Cataclysm-DDA#54497]
### Is your feature request related to a problem? Please describe.

When using AIM to loot dead faction NPCs or NPC bases in general, you cannot interact with any loot marked as owned by a faction from AIM.

### Solution you would like.

I would like to interact with owned/faction items with AIM when thief mode is toggled to allow stealing.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
