### ISSUE TITLE
Add Giant Termites and pillbugs(isopods)

### ISSUE THREAD

**Issue by JonathanLochridge** [CleverRaven/Cataclysm-DDA#54496]
### Is your feature request related to a problem? Please describe.

 I thought of a few other giant insects we could add.
Termites would be particularly interesting as they would give an aboveground dungeon that is sort of analogous to ants. I could also see them investing primarily wooden buildings. Most of their towers should be multi-z level but extend mostly upward rather than downward. 
I also like pillbugs and think they are cool. 

### Solution you would like.

Implement Termite towers
Add very fast non-aggressive grasshoppers(Potentially attracted by crops/forests?)
Add giant pillbugs as a slow armored enemy who are also not super aggressive. 
(Potentially encountered more during rain or on upper levels of mines or other less inhabited underground areas?)

### Describe alternatives you have considered.

Termites could just spawn into existing skyscrapers and wood houses rather than building their own homes.

**Comment by PatrikLundell** [comment]
Are there termites in New England, or is that out of their range?

**Comment by Zireael07** [comment]
@PatrikLundell: See this map and table: https://www.termitestreatment.com/distribution-of-termites-in-usa/

I think the answer is a definite yes for the subterranean variety and a maybe for others (Massachusetts has two Xs in the table) - I'm not so sure what the differences between varieties are...?

**Comment by JonathanLochridge** [comment]
apparently grasshoppers are in the game but didn't come up on my search of the code. Weird. But cool. So it's just isopods and termites.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
