### ISSUE TITLE
Clean Water Recipe Takes Unrealistic Amount of Time

### ISSUE THREAD

**Issue by coyo7e** [CleverRaven/Cataclysm-DDA#54501]
### Describe the bug

Boiling clean water starts at almost 6 minutes for 1 unit, and reduces time for batches by only 20%, which is weird and a little unrealistic because you don't need to bring water to a boil for more than a few seconds to have it be sterile - it would seem more realistic to reduce batch time by 50-80% or reduce the overall time by probably 50% or so. Since many characters do this a lot, it can be a significant timesink and stamina-sink for a task that a person can start and walk away from until it's done.
 
Boiling water over an open campfire flame with an open-topped container does take a little while, but using anything resembling a stove (hotplate, gas/propane stove element, coffeemaker, tea kettle over a firepit, etc) you can boil a gallon of water in less than 10-15 minutes - most water boilers, gas stove elements, and coffee pots etc IRL can boil a gallon of water in 5-10 minutes easily, and I know from fluid and thermal dynamics that these times are entirely linear when scaled upward.

As an eagle scout and lifelong camper who's spent literally thousands of hours in the great outdoors, I can attest that 1 unit of water taking almost 6 minutes is sort of a crazy long amount of time for boiling 1/4 liter (~8oz) of water unless it's balanced for an open pit fire using a lidless container. Especially in small amounts, water boils quite quickly.

Possibly cooking over a campfire/etc should be its own recipe while using hotplates, coffeemakers, microwaves, etc, could be much quicker or the time could be reduced across the board. Or, having a constructable water boiling setup that works like smokers and tanning hides, etc, would be really nice.

### Steps to reproduce

1. Open Craft menu -> Clean Water.
2. Observe that recipe takes 5 minutes, 42 seconds for 1 unit (8 oz) and that  batch time for recipe is reduced by 20%.

### Expected behavior

Expected that boiling water with anything better than an open fire pit should be quicker when performed in small and large batches - it does not take an hour+ to bring 1 gallon (15 units) of water to a boil, IRL. It takes about 7-10 minutes for me to boil a half-gallon of water when I'm making a kettle of tea IRL.

### Screenshots

![image](https://user-images.githubusercontent.com/80022377/149708204-5959503c-0661-4790-ad8a-d32080cf62c3.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: f1997bf [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Zireael07** [comment]
> it's balanced for an open pit fire using a lidless container. Especially in small amounts, water boils quite quickly.

I believe that is the case.

**Comment by coyo7e** [comment]
Then tie how long it takes to the "Boiling" quality of the container used.

**Comment by NetSysFire** [comment]
See #49525.

You can also put water in your pot and drop it into the tile with the fire to boil it using physics. You can actually do other stuff while it boils. It is awesome.

**Comment by Alex-Folts** [comment]
Tell me power output of your heater, and i'll tell you how much time you need to boil X amount of water.

For boiling 1L of water at NTP(room temperature at sea level) you will need ~335kJ of heat, with 2kW heater it would take ~168 seconds to get water to boiling point.
(80(K) * 4.184(J/g*K) * 1000(g)) / 2000(J*s) = 167.5s

**Comment by coyo7e** [comment]
> See #49525.
> 
> You can also put water in your pot and drop it into the tile with the fire to boil it using physics. You can actually do other stuff while it boils. It is awesome.
Oh rad, I thought it would need a construction menu or something thanks!

**Comment by martin509** [comment]
> See #49525.
> 
> You can also put water in your pot and drop it into the tile with the fire to boil it using physics. You can actually do other stuff while it boils. It is awesome.

Worth noting that while this is a great little feature, I think the larger issue at hand is that batch crafting for a lot of food items is _way_ off. Some items have no batch time savings at all when they probably should (for instance, deluxe beans and rice), some have really low batch time savings (for instance, all varieties of tea only save 20% time which means a liter of tea takes 37 minutes to cook versus a cup of tea taking 11), and a ton have 80% batch time savings that, while nice, only kicks in above a certain threshold like 5 units which means that before then, the scaling still feels off. Water is just a victim of this in general - it has 20% batch savings just like tea.

**Comment by coyo7e** [comment]
I personally would love to have a discussion thread for normalizing food bath times, because I cook a lot and some recipes I can get but others just make little sense.. Sauteed fiddleheads iirc (I may be wrong, but it's the one that came to mind) can end up with several hours to make a medium-small batch but they don't have much VOLUME or DENSITY imho, so it ought to not be a pure linear growth time imho.

Taking the time to boil one potato IRL takes almost the same time as several potatoes irl, and you actually do not need to use an incremental amount of water as long as they're all covered for instance

**Comment by martin509** [comment]
Yep, I think that this issue in general is worth spinning off into a general food batch time thread. In terms of solutions you could probably set every food item to at least a 60-70% savings past 1 unit and then do a case-by-case pass on everything that doesn't feel right at that point.

**Comment by LeahLuong** [comment]
Would be nice if cooking utensil volume was somehow factored in as well. Boiling water is something that depends on energy investment so doesn't scale well w/ volume but baking recipes could really benefit. I could see this giving even more incentive to use the appliances being added to the game; not only can larger devices put more energy into cooking in a shorter time, they have increased capacity to get more batch time savings.

**Comment by coyo7e** [comment]
> Would be nice if cooking utensil volume was somehow factored in as well. Boiling water is something that depends on energy investment so doesn't scale well w/ volume but baking recipes could really benefit. I could see this giving even more incentive to use the appliances being added to the game; not only can larger devices put more energy into cooking in a shorter time, they have increased capacity to get more batch time savings.

I would love if cooking quality was a factor - for instance boiling a pot of water might take 10-30 minutes irl but with a lid, it cuts the time down by a huge amount. Sorry I don't recall ym thermodynamics classes offhand, but pressuring something while heating it, makes it heat a lot faster and eventually phase change a lot faster - otherwise we could never put gasses into liquid form (such as propane and propane accessories).. Phase change is potentially super dangerous and nasty but latent vs sensible heat is a real thing, and most amateur cooks learn it pretty quickly just by observation. 

(if you ever see someone get burnt by steam in a movie, that's like the epitome of latent heat vs sensible heat, fyi. There is so much energy stored in the gaseous boiled water that it is stuck and cannot do anything but release itself onto you once it touches your skin. I've been burnt irl by molten plastics, and it wasn't as bad as a steam burn irl)

**Comment by Daenyth** [comment]
I wonder if there's actively something wrong too. I'm on the 2/28 experimental build, I had 12L of water that was in progress, which I couldn't get to finish, so I set a dead hickory tree on fire to finish the recipe. The whole tree burned down and I only got the craft to 48%

**Comment by remd** [comment]
Leaving a large container of water to boil on a source of fire is **far** more time-efficient than using the clean water recipe since you can do other things while it reaches a boil. The water never evaporates either (tested 60L metal tank full of water for over 24h of boiling), so you don't even need to keep an eye on it.

Recipes like clean water, bone broth, etc. would benefit not only from tool quality offering speed modifiers, but also by introducing the ability to asynchronously craft. There's no need for the player to sit around and literally watch water boil. It's not fun and it decreases verisimilitude. I'm not sure if it's even clear to new players that they can simply leave water on a fire to boil and clean itself instead of wasting precious time in the early game using the recipe.
