### ISSUE TITLE
Portal Storm Enemy "Absence" Has Too Much Health

### ISSUE THREAD

**Issue by coyo7e** [CleverRaven/Cataclysm-DDA#54506]
### Describe the bug

Noticed today that Absences seem to have been buffed, and have 8 dodge and 150 health (I thought they were one-shottable, from what I recall fighting them in previous update). After smacking one 6 times (and missing a couple times) with a quarterstaff I was hit 4 times (with 10.8 effective dodge rating) and immediately had to go sleep to recover from "Tired," despite my character just having woken up from 9 hours of sleep.

This enemy can already effectively "lock down" a character from moving with its void spell thing, potentially in a scenario where they're already fleeing from serious danger. Combine with their ability to spawn in within 2-5 squares at any time during a portal storm, and their rather high health and defense, this makes them a pretty nasty threat, or at least one which can end up as a time-sink while you sleep off the tiredness.

Referring to shifting mass which has 10 health and 2 dodge, and impossible shapes which have 30 health and 8 dodge, absence seems pretty strong since even though it moves slowly it has a ranged ability, and it can spawn well within range to immediately hit the player with it.

### Steps to reproduce

1. Spawn absence.
2. Attack them.
2. Notice that they're rather hard to kill.

### Expected behavior

Expect Portal Storm enemies to go down in one or two good hits, and/or spawn further away/less frequently.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: f1997bf [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Venera3** [comment]
I don't know how to say this, but you're not supposed to be able to beat everything to death with a stick. Even if it's a nifty stick.

**Comment by PatrikLundell** [comment]
On the other hand you're not supposed to get screwed over by the game dropping certain death onto your head randomly. Sure, you're not supposed to be able to kill a shoggoth with a stick, but shoggoths don't just drop out of the sky randomly without the player having any influence over it.

**Comment by Venera3** [comment]
If you can beat the otherworldly horrors to death with a *stick* then portal storms kind of can't live up to their intended effect of "oh shit I gotta get into cover". They also warn players when approaching, and are pretty trivial to avoid (unless you're lost in the wilderness, but that's not really the normal experience by the time they drop).

**Comment by PatrikLundell** [comment]
How many hours of warning do you get? (I haven't actually played since they were introduced, and only encountered them during base camp construction testing, where they just happen when debug advancing time). Even if you're just foraging around your base camp it will take a fair while to return to it, and if you're traveling on foot to the nearest "town" for looting (e.g. because there aren't any available roads, so you have to walk through forests even if you have a vehicle) the walking takes time.

**Comment by NetSysFire** [comment]
>unless you're lost in the wilderness

Improvised shelters count as being inside. As long as you do not leave it or get lucky and giant appendages do not spawn while you e.g refill your water, you are safe. They are pretty easy to craft from scratch, too.

>How many hours of warning do you get?

I think it really depends. Sometimes you get warnings the whole day, sometimes you only get one warning and it starts very soon.

**Comment by SariusSkelrets** [comment]
Some portal storms monsters could be hit but the absence is described as ‘’empty space’’ in its description 

You still managed to hurt an empty space, and I think the description says everything about why they’re hard to kill: they technically aren’t real

The lock ability might need to be adjusted a little

**Comment by LeahLuong** [comment]
Linking #52475 in case the dev misses this thread & also because it's where they've requested feedback.

@Ramza13 Check your mentions, please! I @'d you in another thread but haven't heard back yet.

**Comment by NetSysFire** [comment]
All contributors are volunteers. Mentioning them yet another time is not going to help, quite the opposite: It might lead to them being annoyed about this. They might just be busy irl currently and only work occasionally on this, so let us be patient.

**Comment by Ramza13** [comment]
> Linking #52475 in case the dev misses this thread & also because it's where they've requested feedback.
> 
> @Ramza13 Check your mentions, please! I @'d you in another thread but haven't heard back yet.

Just want to say that I am following all feedback and just hadn't haven't gotten around to acting on all of it.  I hadn't thought about the fact that I asked for feedback and then went quiet though.  That does sound frustrating and I'm sorry.  I'll try to respond more quickly in the future.

Right now I'm working on the portal storm dungeon but more monster balances will come and I do appreciate peoples feedback like this as the numbers and strengths are still being worked on.

**Comment by anoobindisguise** [comment]
Portal Storms are basically a binary: either you are inside and ignore them, or you are outside and you die. There's not much more to it than that. Stay inside when a portal storm happens.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
