### ISSUE TITLE
Hotwiring Vehicles Does Not Train Mechanics, Vehicles, Or Electronics Skills

### ISSUE THREAD

**Issue by coyo7e** [CleverRaven/Cataclysm-DDA#54505]
### Describe the bug

Hotwiring cars is often very nerve-wracking, dangerous, time-consuming, and as far as I understand, based on the Mechanic skill. 

After spending 8+ hours trying to hotwire a van in a cleared-out area I noticed that my Mechanic skill is still 0 (0%) with knowledge 1 (0%). Since the RNG can sometimes leave a player without any cars they can find outside of one that requires hotwiring, and because stuff like portal storms now makes it way dangerous to walk for long distances (making cars much more desirable and almost required), it seems like it ought to be more rewarding and/or easier to accomplish this task which could involve up to three different skills, logically.

FWIW, I reloaded my save file after trying to hotwire a vehicle for 9+ hours (wasted almost an entire day's worth of daylight), and succeeded after 3 tries, which only took about 3-4 hours or so.

### Steps to reproduce

1. Find/spawn vehicle which needs hotwiring.
2. Attempt to hotwire car.
3. Check Mechanics, Vehicle, and Electronics skill, confirm no gain of skill.

### Expected behavior

Seems like hotwiring should either be progressive to indicate a process of elimination (how many times would one keep trying "the red wire" with no progress?) as the character tries each wire combo successively, or it should be like lockpicking and train up an apropos skill/proficiency when used, whether or not the player succeeds.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: f1997bf [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by hexagonrecursion** [comment]
@wapcaplet, confirmed

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 1e91f34 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]
