### ISSUE TITLE
[Query] World End Handling - Settings Toggle - No accidental deletion

### ISSUE THREAD

**Issue by Musketmarine** [CleverRaven/Cataclysm-DDA#54508]
### Is your feature request related to a problem? Please describe.

As somebody who flip-flops between resetting and keeping a world. I've had many times where I've almost accidentally hit the delete button when I die in-game when using the _Query_ setting in the **World end handling** section during World Creation.

### Solution you would like.

As it stands, I suggest the implementation of a toggle in **Settings** at the main menu, to simply turn off the ability to delete the world from the window that the _Query_ **World end handling** prompt that instantiates when the player dies during a run. In essence, the functionality to delete the world from the Main Menu will still remain even with the toggle on.

### Describe alternatives you have considered.

Alternatively the option could be greyed out, and prompt the player to delete the world from the main menu in the event the aforementioned **Settings** toggle is activated. 

In addition, there is an additional alternative of simply adding an "Are you sure prompt?" (I have not hit the delete button from the query menu, so I don't know if there is already one in place.)

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
