### ISSUE TITLE
Mutation Menu CtD

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#54504]
### Describe the bug

If you '!' and view details on your mutations, and use tab to swap between passive and active, you can get either a CtD or a bad description, based on which way you tab.

### Steps to reproduce

Take a half dozen starting mutations, as well as gourmand and night vision as to have two active mutations.
'!' and look at the details.
Hit tab till you CtD.

Pretty sure Activatable->Passive gives a bad description, whereas Passive->Activatable CtD's.

### Expected behavior

No CtD

### Versions and configuration

Win 10, tiles
e49949d

Several mods, but I don't think that's gonna cause this to happen, they all have regularly viewable descriptions.

### Additional context

#54279
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7879390/crash.log)
Nothing of value in debug log.

**Comment by dseguin** [comment]
Here's the fix:
```diff
diff --git a/src/mutation_ui.cpp b/src/mutation_ui.cpp
index 6d2bf0859a..1134486777 100644
--- a/src/mutation_ui.cpp
+++ b/src/mutation_ui.cpp
@@ -487,9 +487,9 @@ void avatar::power_mutations()
                 } else {
                     continue;
                 }
-                examine_id = GetTrait( active, passive, cursor, tab_mode );
                 scroll_position = 0;
                 cursor = 0;
+                examine_id = GetTrait( active, passive, cursor, tab_mode );
             } else if( action == "CONFIRM" ) {
                 trait_id mut_id;
                 if( tab_mode == mutation_tab_mode::active ) {
```

It crashes because it's trying to access the "active" array using the cursor position of the "passive" array. `GetTrait` should get the id after the cursor is reset.
