### ISSUE TITLE
Make digging pits a pauseable task.

### ISSUE THREAD

**Issue by FayFlightee** [CleverRaven/Cataclysm-DDA#54511]
### Is your feature request related to a problem? Please describe.

For someone that dig pits a lot, this is a big problem. Digging is extreme work which drains fatigue like crazy, however, you MUST finish it in one session or redo the entire process from scratch which horribly wastes time. It needs to be pause-able, like construction projects.

### Solution you would like.

Make digging pits into construction project probably, if you can make the fatigue cost vary on construction projects. Or make something similar for them.

**Comment by NetSysFire** [comment]
You actually can pause digging pits, but you must choose the same location for all the materials you dig out.

But I do agree, this is really annoying since the location you choose is invisible and you have to remember it or start from scratch.

**Comment by leemuar** [comment]
So is this issue about rendering? Make dig pit be rendered on screen instead of being invisible

**Comment by NetSysFire** [comment]
No it is not. The actual solution would be to pile up all the materials you get in realtime or have a proper in-progress pit tile you can resume digging from.

**Comment by coyo7e** [comment]
With Portal Storms happening, digging pits has become more annoying yeah. I got to 96% and had a portal storm hit and got attacked by enemies.. RIP the hole I spent hours digging. I would like to be able to pause them in-progress, similar to constructing/disassembling, crafting, etc.

**Comment by PatrikLundell** [comment]
I'd say having a pit-in-progress (or actually two: one for shallow and one for deep), plus the placement of any material extracted at the time of completion or interruption (real time would probably be a better simulation, but might have issues when out-of-bubble work is performed e.g. by a companion). A problem with an in-progress pit is that it would somehow have to store the progress information somewhere, but if progress is stored the material placement location can probably be stored as well.
