### ISSUE TITLE
Add version data in JSONs

### ISSUE THREAD

**Issue by ChainsawGarden** [CleverRaven/Cataclysm-DDA#54515]
### Is your feature request related to a problem? Please describe.

To help differentiate between versions of mods (and each version of the game) there should be a JSON entry that contains two pieces of "mod version" data:
One for the game version, one for the mod version.

This will ultimately aid in helping prevent end-users from using the wrong mods and wrecking their savegame.

### Solution you would like.

Something like the below two entries should suffice, JSON-wise:
```json
{
    "game": "0.F",
    "version": "1.0.0"
}
```

The game should parse the "game" entry first. If the current game version doesn't match the specified version, the game should let you know that "this mod is meant for a different version of the game". The user should have a choice to "USE ANYWAY" or "DO NOT USE" the mod. There should also be a setting to hide incompatible mods.

Maybe "game" could take an array, because the mod might be compatible with multiple game versions. For example: 
```json
{
    "game": ["0.E", "0.F", "0.G"],
}
```

### Describe alternatives you have considered.

Manually checking each and every JSON mod I have to make sure all of the data is compatible with the current version of the game.

### Additional context

im hungry

**Comment by ZhilkinSerg** [comment]
Version string is there. Mod authors and maintainers do not use it.

**Comment by ChainsawGarden** [comment]
I see. It looks like Mythos, TropiClysm and I think another core mod uses it, though I was looking through the JSON docs first and noticed there was no JSON entry for that.

Someone should add that to the JSON_INFO.md (or any applicable doc file)

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
