### ISSUE TITLE
Gloves protect from getting zapped with bionic weapons

### ISSUE THREAD

**Issue by drhead** [CleverRaven/Cataclysm-DDA#54518]
### Describe the bug

When attacking enemies like zapper zombies with bionic weapons like monomolecular blade, you get zapped if not using gloves, and not zapped if you are using gloves.

### Steps to reproduce

1. Equip something like monomolecular blade, with no gloves.
2. Attack a zapper zombie, you get zapped
3. Equip gloves
4. You won't get zapped now.

### Expected behavior

The expected behavior depends on what we'd want the bionics to be designed like lorewise, the only real requirement here is that the behavior is consistent either way.  It would be entirely reasonable for high-end combat bionics to be built with insulation or an integrated version of the dielectric capacitance system (don't really want your bionic supersoldiers to be countered by something like an electrified riot shield), or that it just has a protective barrier to stop it from cutting your own flesh while stowed.  But it's also a blade sticking out of the user's body, so it is reasonable that a possible design for it would have a conductive surface touching the user's flesh.  Should it be well-designed in universe or poorly designed?

Probably the easiest reasonable solution would be to make the monomolecular blade itself nonconductive, reasoning that it would be designed to resist such attacks, and to keep fingertip razors and claws as is.  I would expect using fingertip razors and claws without gloves to involve a lot of incidental contact between the enemy and the user's hands, so the existing behavior is actually reasonable for that.  

The alternative would be creating a new classification for weapons that conduct regardless of whether the user has gloves, and putting all bionic weapons in that classification.  Later in the game, bionic weapon users would then have to use the dielectric capacitance system to protect themselves from electric shocks.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: dc02e84 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Crazy Cataclysm [crazy_cataclysm]
]

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
