### ISSUE TITLE
Chapels in Prison and Prison Priests as a profession.

### ISSUE THREAD

**Issue by NickPowrz** [CleverRaven/Cataclysm-DDA#54512]
### Is your feature request related to a problem? Please describe.

As i noticed Prisons in CDDA don't have any kind of Chapels. So my proposition is to end this.

### Solution you would like.

To add chapels in prisons and Prison Priest as a profession in a Prison scenario.

**Comment by LeahLuong** [comment]
Your feature request has a higher likelihood of implementation if you leave the issue open. No guarantees . . .

**Comment by NickPowrz** [comment]
> Your feature request has a higher likelihood of implementation if you leave the issue open. No guarantees . . .

I did other because this issue bugged and got broken. My internet is bad, sry.
