### ISSUE TITLE
Add chapels in Prisons and Prison Priest as a profession.

### ISSUE THREAD

**Issue by NickPowrz** [CleverRaven/Cataclysm-DDA#54513]
### Is your feature request related to a problem? Please describe.

As i noticed, prisons in CDDA don't have any Chapels in it, with authentic Prison Priest profession for role-playing purposes, so here's suggestion to end this.

### Solution you would like.

Add chapels to prisons and Prison Priest profession for Prison scenario.

**Comment by JonathanLochridge** [comment]
Potentially the priest could have some sort of flag for starting locations similar to the guard maybe so you don't spawn in a cell.

**Comment by NickPowrz** [comment]
> 

Yes, forgot about it. You spawn in Chapel.

**Comment by NetSysFire** [comment]
Tempted to label this with good first issue, but modifying the existing prison and spawn for the chapel might be tough for new contributors.

**Comment by Night-Pryanik** [comment]
Just FYI island prison type B has both chapel and chapel priest (as miniboss).

**Comment by JonathanLochridge** [comment]
Cool, in that case you could maybe make a duplicate without the priest NPC be the prison type you spawn in to start with. And the move adding a non-island prison priest option to another issue. That way the part that is a good first issue might be able to be separated out?

**Comment by Night-Pryanik** [comment]
As @NetSysFire said, adding chapel to current prisons' mapgen isn't as easy task. It's possible, sure, but would require a lot of time and work.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
