### ISSUE TITLE
Text Indicators for the severity of a portal storm

### ISSUE THREAD

**Issue by 7erracotta** [CleverRaven/Cataclysm-DDA#54524]
### Is your feature request related to a problem? Please describe.

I think it would be really, REALLY cool if you could get a loose idea on how severe the next portal storm could be via the text indicators that come up before one begins. Plus, I think it would spook some people out.
." 

### Solution you would like.

For example, the text box for a mild/average portal storm would be "you hear faint humming in the distance." while a severe portal storm text box would be something like "you hear what sounds like a booming choir."

**Comment by NetSysFire** [comment]
We already got that.

https://github.com/CleverRaven/Cataclysm-DDA/blob/e53cf9c14510c5769f47bc6f6ae37025ac25ea45/data/json/snippets/effect_on_conditions.json#L92

https://github.com/CleverRaven/Cataclysm-DDA/blob/e53cf9c14510c5769f47bc6f6ae37025ac25ea45/data/json/snippets/effect_on_conditions.json#L105

https://github.com/CleverRaven/Cataclysm-DDA/blob/e53cf9c14510c5769f47bc6f6ae37025ac25ea45/data/json/snippets/effect_on_conditions.json#L118
