### ISSUE TITLE
Repairing things should utilize/train proficiencies from craft recipes

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#54527]
### Is your feature request related to a problem? Please describe.

If an item has a craft recipe, and is repairable, attempting to repair it should utilize the proficiency system.
Someone on the discord had tailoring & fab 8 from repairing things, and then wondered why they couldn't progress chitin work: they had no proficiencies at all but weren't getting very many failures, just stuck at 0% progress.  The proficiency was training, but it wasn't noticeable to them.

### Solution you would like.

Failure rates, as well as proficiency learning should come from an items craft recipe, if it has one.  Not sure what to do if it doesn't, perhaps a general basic & standard prof based on the material?

### Describe alternatives you have considered.

N/A

### Additional context

[discord convo](https://discord.com/channels/598523535169945603/598523535169945607/932766361338400799)

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
