### ISSUE TITLE
Custom sidebar section list needs a scrollbar

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#54532]
### Is your feature request related to a problem? Please describe.

When using the "custom" sidebar with more than 22 available "widgets" defined (such as when Magiclysm is in use, and the Mana widgets are included), the list of sections goes outside the bounds of the popup.

### Solution you would like.

There is a scrollbar function defined in `src/output.cpp` called `draw_scrollbar` (a shortcut to creating a scrollbar with the `class scrollbar`), which several other UIs make use of when lists are too long to fit.

Making the sidebar section list scrollable in the same way would be the ideal solution.

### Describe alternatives you have considered.

Making the popup taller is not a sustainable solution, nor is removing or combining sections. I think a scrollbar is inevitable.

### Additional context

![image](https://user-images.githubusercontent.com/238395/149853083-877efda3-a918-4d16-b08d-f559a87a6e90.png)

**Comment by LeahLuong** [comment]
You forgot to make the selling point this will make the Woadmap™ (#53957) that much more powerful!
