### ISSUE TITLE
Vehicle Tank Fullness

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#54538]
### Is your feature request related to a problem? Please describe.

So, with a recent update to vehicles, tanks on vehicles now respect those tank component mass limits.  Cool!  But this does mean that there are a large number of tanks that when filled with high density liquids, will be full at some smaller volume than what the ui indicates.  This makes it hard to know if they are full or not, or how much more you can add.

### Solution you would like.

On the UI for the tank display, beside the volume stored, to also have a % full beside that,  It should respects either the Volume/Volume or Mass/Mass of a liquid holding tank, showing which ever measurement has the smaller capacity.

### Describe alternatives you have considered.

Having a half dozen 20L jerrycans of chemicals on my battlebus all full at 15.4L, or 18.4L, etc.

### Additional context

Of note; this would have to be filtered for just liquids, given you can attach a 200L external tank that's full of 40 different items right now.

**Comment by PatrikLundell** [comment]
I understand that mercury is heavy, but what other liquids are so heavy that rigid containers designed to be able to at least contain water doesn't have a sufficient safety margin to be able to be filled with them? Sure, a jerrycan is intended for fuel which is lighter than water, but I would expect to be able to carry liquids of a reasonable weight in them anyway. The default weight limit probably should be somewhere around twice the weight of them filled with water.

This doesn't mean it wouldn't be useful to know that you've reached the weight limit when you've stored e.g. metal powder in them, though.

**Comment by chrispikula** [comment]
Nitric Acid, Hydrogen Peroxide (concentrated), Hydrochloric Acid, Liquid Soap are the ones I can find quickly.  (Being that I have them in my storage.)

Side note, magiclysm mercury is only 50% denser than water?  Hah!  Liquid Soap is more than 5x!
