### ISSUE TITLE
Modify the Map Extra related C++ code to reduce clumping.

### ISSUE THREAD

**Issue by JonathanLochridge** [CleverRaven/Cataclysm-DDA#54548]
### Is your feature request related to a problem? Please describe.

I find it a bit weird when several of the same Map Extra spawn to close to each other in a way that seems weird. It's most notable with wasp and dermatik nests commonly spawning right next to each other. Which seems like they would fight too much for that to make sense.
Or getting several drug dealer extras clumped in the same 5 tile area. Too far apart to seem like a really big deal gone wrong. And too close to seem feasible to have happened in the limited time before the cataclysm ended.

### Solution you would like.

Ideally a check could be added to identify nearby tiles for map extras when placing one. Ideally triggering a reroll of the the map extra type. Potentially a flag could be added so some map extras could disable this check if clumping makes more sense for that type of extra. 
I think looking like 3-5 tiles away would be good. 

### Describe alternatives you have considered.

Leave it as is with clumping as a desired feature.
-Allow clumping by default but have a tag to enable the new code for a extra.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
