### ISSUE TITLE
Crafting a headlamp using a flashlight loaded with a battery uselessly entombs that battery inside.

### ISSUE THREAD

**Issue by VitreousEyes110** [CleverRaven/Cataclysm-DDA#54543]
### Describe the bug

Crafting a headlamp using a flashlight containing a battery seals the battery inside the headlamp as an impractically unused component, leaving the headlamp uncharged despite having a battery as a component, and requiring disassembly to retrieve the battery.

### Steps to reproduce

1. Create a character with a flashlight containing a battery, as well as a long string, knife and fabrication 1.
2. Craft a headlamp.
3. Find the battery listed as contained within the flashlight component of the headlamp, completely unutilized.

### Expected behavior

The battery should either be removed from the flashlight when crafting begins or be actually loaded in the headlamp when crafting finishes instead of being entombed uselessly.

### Screenshots

Before crafting headlamp, battery loaded in flashlight.
![Screenshot (355)](https://user-images.githubusercontent.com/45680256/149890628-076a6c9b-5eb9-4343-8c65-bf45b1ed840a.png)

After crafting headlamp, battery not in inventory or loaded in headlamp, instead just listed as contained within the flashlight component.
![Screenshot (357)](https://user-images.githubusercontent.com/45680256/149890638-a883133a-5a45-46e2-b2dd-1762d14c0fc9.png)
![Screenshot (359)](https://user-images.githubusercontent.com/45680256/149902799-95ce9e5a-b72f-4b6e-8193-862182972ca9.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 1607
- Game Version: 8fe7f90 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by LeahLuong** [comment]
Have you tried disassembling the headlamp?? Survivors are a crafty sort & have been known to make separate battery compartments for their insidious designs which don't feature working contacts. I'm sure that battery's still in there somewhere!

**Comment by VitreousEyes110** [comment]
> Have you tried disassembling the headlamp?? Survivors are a crafty sort & have been known to make separate battery compartments for their insidious designs which don't feature working contacts. I'm sure that battery's still in there somewhere!
> 
> That wouldn't happen to be a peach-flavored flashlight (#54132) you used in that recipe, would it??

![Screenshot (359)](https://user-images.githubusercontent.com/45680256/149901347-eb76d15b-edda-4cf4-9036-fd190bc2dc9d.png)
So it _is_ in the headlamp, just trapped inside impractically, with the headlamp itself not utilizing it at all... I'll edit the issue to reflect that.
