### ISSUE TITLE
Add more library varients.

### ISSUE THREAD

**Issue by JonathanLochridge** [CleverRaven/Cataclysm-DDA#54553]
### Is your feature request related to a problem? Please describe.

Having more library variants would be cool.

 

### Solution you would like.

-Multi-story single tile Urban Libraries
-Flat large libraries with surrounding parking lots and grass/statues. Like a mini less dangerous park.
-Big Mega libraries: Lot's of books and rarer ones being more available.(potentially in a closed off or basement room? But more zeds than other libraries.

### Additional context

Should #54237 be fixed first?

I don't mind making some libraries. Although, I am currently a bit overwhelmed by their template and how it fits together. So, If I do end up making some significant ones I would appreciate some guidance.

**Comment by Maleclypse** [comment]
#54237 is not specifically related to libraries.  It's a different problem that is more visible in libraries.

**Comment by JonathanLochridge** [comment]
Good to have that cleared up. I should start on some as soon as I figure out how to get the town hall variant to not throw errors.

**Comment by LovamKicsiGazsii** [comment]
Mainlining the multi-tile public library from #29533 would be a nice start.
