### ISSUE TITLE
Add link to Monster.md from the new contributor starting guide:monsters

### ISSUE THREAD

**Issue by JonathanLochridge** [CleverRaven/Cataclysm-DDA#54551]
### Is your feature request related to a problem? Please describe.

I stumbled across MONSTERS.md buried in JSON_INFO.md and it has quite a few things that are useful for getting started making monsters. The getting started guide overviews the files you need to work with to make monsters but not how they are actually structured and work.

### Solution you would like.

To have a link to MONSTERS.md in the getting started monsters page.

### Describe alternatives you have considered.

To add more detail to the getting started page on how monsters are put together in the JSON.

### Additional context
Link to guide needing link: https://github.com/CleverRaven/Cataclysm-DDA/wiki/New-Contributor-Guide-Monsters
Monsters.md is in the doc folder. But here is a link there in the web interface. I think you can setup non-web dependent links in markdown. not sure how though: https://github.com/CleverRaven/Cataclysm-DDA/blob/e11bf599e9af3234c4bce7352aea0472aaa51ff9/doc/MONSTERS.md

**Comment by EMUL8ER** [comment]
Hey I am a beginner, I would love to contribute, can you assign this issue to me?

**Comment by JonathanLochridge** [comment]
@EMUL8ER 
So if you are looking to do this change in particular it would be a markdown change. Where you would add a little bit of text mentioning the monsters.md file from the appropriate new-contributor page. 
I found a couple guides on markdown if you aren't familiar with it. Although, I don't really know markdown either. It's on my to-learn list. https://www.tutorialsandyou.com/markdown/how-to-add-links-in-markdown-12.html
This is the guide which needs the link added to it: https://github.com/CleverRaven/Cataclysm-DDA/wiki/New-Contributor-Guide-Monsters
In retrospect I should have linked that in the OP.

improvements to documentation are important. Although, JSON changes are where a lot of new content is added. If you know C++ there is always a need there. Mlangsdorf would be a good person to contact if you want to get started there if you already know C++. I saw like a few small projects in it on your profile but I don't if you actually know it very well yet.

These are the primary hub guides for JSON changes if you haven't already read them:
https://github.com/CleverRaven/Cataclysm-DDA/wiki/Guide-to-adding-new-content-to-CDDA-for-first-time-contributors
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/.github/CONTRIBUTING.md

**Comment by strategineer** [comment]
The linked wiki page mentions doc/MONSTERS.md (see below):
> "monsters also have a monstergroups JSON object, which controls what monsters spawn where in a random function. This is partially documented in doc/MONSTERS.md."

We should be able to close this.


NB: If someone with wiki edit power wants to convert "doc/MONSTERS.md" here https://github.com/CleverRaven/Cataclysm-DDA/wiki/New-Contributor-Guide-Monsters into a link pointing to https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/MONSTERS.md, go ahead!
