### ISSUE TITLE
Fast metabolism trait

### ISSUE THREAD

**Issue by flin4** [CleverRaven/Cataclysm-DDA#54566]
### Describe the bug

Yeah, i'm playing with it. But sometimes (usually after craft) i missed a moment and got underweight and underfed effects. Then i need to eat tons of food to get back to normal. Couldn't guess how much till i found fitness band and saw the real numbers. You can check'em below ( kcal)

consumed 
today 11170, yesterday 15812
burned
today 1663, yesterday 3348

And that's for the moment i've missed. Actually it was over 20k kcal to get normal weight.

 

### Steps to reproduce

Play fast metabolic
Get fitness band
Get underweight

### Expected behavior

More slightly transition

### Versions and configuration

android, tiles, experimental, russian

**Comment by Maleclypse** [comment]
Underfed means you have been eating less than you burned for days prior.  This data isn't showing a problem yet.  We don't know what your debug visible calorie count for your reserves were to start with.   Attached saves with a description of how to show that the calories burned doesn't match up to changes in the calorie reserves are probably a minimum of what's needed in a report on this system.

**Comment by hexagonrecursion** [comment]
@flin4

1. Please upload your save file.
2. Please describe exactly:
    1. What did you do?
    2. What you expected to happen?
    3. What happened?

    If English is not your first language, please provide the above information both in your first language and in English.
 
This is what I can understand from your description so far:
1. You were crafting. Did you eat anything while crafting? How long did you spend without eating anything?
2. You became underweight and underfed.

**Comment by flin4** [comment]
there's fitness band stats for day before when i got warning about calories tense food and underweight day. consumed and burned calories are merely equal on other days

**Comment by flin4** [comment]
> Underfed means you have been eating less than you burned for days prior.  This data isn't showing a problem yet. <

there's about 10x consumed then burned

**Comment by hexagonrecursion** [comment]
@flin4 Создай, пожалуйста, zip архив своего мира и прикрепи его

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
