### ISSUE TITLE
Add Flaming and Biological caltrop dropping giant tumbleweeds

### ISSUE THREAD

**Issue by JonathanLochridge** [CleverRaven/Cataclysm-DDA#54565]
### Is your feature request related to a problem? Please describe.

My in game pyromaniac doesn't see enough !!fire!! or tire damage. Also tumbleweeds are cool! Or hot if they are flaming.

### Solution you would like.

Add tumbleweed mobs that move fast but are non-hostile and light a fire to most things they touch. (summer exclusive)
Add a tumbleweed monster that drops wooden caltrops which deflate tires if they run over them. 

### Describe alternatives you have considered.
Only add these to the desert mod.

### Additional context

Inspired by a short discussion on the non-dev discord.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
