### ISSUE TITLE
Portal Storm Teleport That Also Spawns Enemies - Does Not Interrupt Picking Up Items

### ISSUE THREAD

**Issue by coyo7e** [CleverRaven/Cataclysm-DDA#54569]
### Describe the bug

There's a new teleport (as of this morning's update, or so) where it throws you a ways away and also spawns in enemies at the same time. I was picking up multiple items from a crate and got teleported with enemies spawning in at the same time, but continued the pickup action and got hit a couple times before I could do anything so they had plenty of time to move up to me and hit me more than once.

For funsies, I almost landed on an active landmine - would it have been set off? Probably! lol

(screenshot doesn't show the landmined area, because I didn't stop to screenshot until I got popped around out of my car a little later, but it's at "9 minutes" you can see the message and subsequently being hit 3x)

### Steps to reproduce

1. Start Portal Storm
2. Pick up items from crate (or other containers, possibly?).
3. Observe being teleported and attacked multiple times before able to react.

### Expected behavior

Expected action to interrupt when teleported, to prevent multiple free enemy actions.

### Screenshots

![image](https://user-images.githubusercontent.com/80022377/150075668-5c130146-1387-4841-9349-1118da98cc57.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 98a8e80 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Ramza13** [comment]
This should hopefully be fixed once #54590 is merged.

**Comment by Ramza13** [comment]
So you don't have to close your bugs if they are getting fixed.  Once the PR that fixes them is merged it will close the bug automatically.  Not a big deal but if it takes a while to get merged it might prevent duplicate bug reports.
