### ISSUE TITLE
Power Grid/Appliances need removal options

### ISSUE THREAD

**Issue by RembOMC** [CleverRaven/Cataclysm-DDA#54576]
### Is your feature request related to a problem? Please describe.

Yes. The problem being that 'placed' 'appliances' cannot be removed/recovered at present.
In some cases destruction through smashing and such is said to be possible.

### Solution you would like.

'Unplace' construction options would make the most sense in light of the 'place' option being there. It would further clutter that menu up however, and since the vehicle framework is already used to interact with the vehicle perhaps a simple uninstall option would be best.

**Comment by catdach** [comment]
I thought the "Deconstruct Furniture" option in the (*)Construction menu did this already. Does it not? I haven't done much with appliances yet.

**Comment by RembOMC** [comment]
It does not. The deconstruct and decon simple options do not allow for the targetting of the appliance 'vehicle'
The interaction menu has no option, and asking around on the reddit revealed that the only people that have removed said vehicles did so by smashing it.
Also, when smashing, you seem to hit the floor, but i am told the vehicle does still take damage. Have bot confirmed this last bit

**Comment by Xenoamor** [comment]
I think it makes sense to extend the "Deconstruct Simple Furniture" option to support this as that is how things like fridges/ovens/lamps are gained in the first place. They are also built from the construction menu.
I think having it in the interaction would be inconsistent
