### ISSUE TITLE
Add debug option to remove status effects 

### ISSUE THREAD

**Issue by scavtoons** [CleverRaven/Cataclysm-DDA#54577]
### Is your feature request related to a problem? Please describe.

When testing effects it becomes a hassle to wait for them to be over just to see if they work correctly, also to test the capabilities of self updating effects like the ones related to nutrition. 

### Solution you would like.

We need an instant way to remove status effects preferably in the editt player/npc menu.

### Describe alternatives you have considered.

An option to revert a character to a previous state,it would be more complicated, but maybe more stable.

**Comment by Night-Pryanik** [comment]
Removing effect is actually possible through the debug menu. `Add an effect` -> `Show only active` -> select the one you need -> set duration to 0.
