### ISSUE TITLE
[Magiclysm]Increase the distance that Orc and Goblin camps spawn from cities.

### ISSUE THREAD

**Issue by JonathanLochridge** [CleverRaven/Cataclysm-DDA#54579]
### Is your feature request related to a problem? Please describe.

I think it makes more sense for orcs and goblins to be further from cities.
Originally suggested by maleclypse to solve an issue that guardianDil brought up in the discord which I agreed with. 

### Solution you would like.

Increase the min distance for Orc and goblin camps to spawn from cities.

### Describe alternatives you have considered.

Simply increasing the max distance so that some still spawn near cities but maybe less of them will?

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
