### ISSUE TITLE
Spurge flowers in New England do not have anti-asthmatic properties

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#54589]
### Describe the bug

It is not specified which specific species of spurge we have ingame but only one flower in the entire spurge flower genus appears to have these properties: [Euphoriba hirta](https://en.wikipedia.org/wiki/Euphorbia_hirta)
This plant lives in more tropical places than New England and has red flowers instead of yellow ones.

The one ingame *might* be [Euphorbia cyparissias](https://en.wikipedia.org/wiki/Euphorbia_cyparissias) but the exact species is not important, as there is no way the anti-asthmatic flowers grow here.

### Steps to reproduce

n/a

### Expected behavior

This is a tough one. I do understand that asthma is no joke (both irl and ingame) and spurge flowers (the item) help with wilderness playthroughs (which I am very fond of as you might know), but since this game tends to be about realism I propose removing spurge flowers (the item) and spurge tea.

Spurge plants found in New England actually tend to be mildly toxic it seems. I could not find a replacement plant yet and I would appreciate suggestions.

### Versions and configuration

n/a

**Comment by Venera3** [comment]
Yeah, down with bushcraft medicine. Most of them are straddling the line between being *very* optimistic and straight bullshit ~~which is of course on point for herbal medicine~~ so they could use a feasibility audit.

**Comment by coyo7e** [comment]
Since this is flagged "discussion", I would like to note that willowbark tea causes nausea instantly, even when the player only consumes 1 dose. Willow bark has been shown in multiple studies to be at least no worse for stomach irritation than aspirin, and potentially less irritating while being just as effective for reducing inflammation.

It only seems to last a minute or few, but it's still annoying to have this occur.

**Comment by NetSysFire** [comment]
I think this was done to balance it, so cheap herbal remedies are not just as good as the good meds you get from scavenging. There is apparently some nausea to be had, but I would not make it immediate: https://en.wikipedia.org/wiki/Willow#Medicinal

**Comment by coyo7e** [comment]
Sorry I pulled my info from Johns-Hopkins, not wikipedia. Aspirin is just as irritating to the stomach as willow tea.

**Comment by NetSysFire** [comment]
Everything related to defecation and stuff can not be implemented currently because we do not have this. Maybe some tummy ache can be used instead in the meantime.

**Comment by NetSysFire** [comment]
Interestingly, I just found out that datura has some positive effect on asthma, but it has tons of downsides.

https://en.wikipedia.org/wiki/Datura_stramonium#In_treatment_of_respiratory_diseases

This is undocumented but apparently already implemented.

https://github.com/CleverRaven/Cataclysm-DDA/blob/cecb4775bde77fd4637f08ab1f17478040eca1eb/src/suffer.cpp#L674-L680

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
