### ISSUE TITLE
`DEBUG    : item_location of item to be reloaded is not available` when reloading ammo belts

### ISSUE THREAD

**Issue by Hirmuolio** [CleverRaven/Cataclysm-DDA#54582]
### Describe the bug

Trying to fill ammo belt gives this debug message:

```
 DEBUG    : item_location of item to be reloaded is not available

 FUNCTION : virtual void reload_activity_actor::finish(player_activity&, Character&)
 FILE     : src/activity_actor.cpp
 LINE     : 4095
 VERSION  : d740104
```

The reload itself seems to work. Ammo  and ammo links turn into ammo belt.

### Steps to reproduce

1. Have empty ammo belt linkages and ammo for them
2. Activate the linkage to reload

### Expected behavior

No error.

### Versions and configuration

This is not in 0.F stable. The oldest compiled experimental on github is 2021-07-31-1843 and that has this bug.

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: d740104 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
]

**Comment by irwiss** [comment]
Can't reproduce on 4ee908511348aec9299ee9edf40dfab6d6671081
