### ISSUE TITLE
Making food destroyed calories.

### ISSUE THREAD

**Issue by moxian** [CleverRaven/Cataclysm-DDA#54592]
### Describe the bug

- found two pig corpses (killed by zombies, irrelevant)
- butchered them, obtained (among other things) porkbellies and chunks of meat
- batch-made 12 meat jerkies out of porkbellies
- batch-made 24 meat jerkies out of chunks of meat
- realized that the porkbelly jerkies have zero calories in them (but chunk-of-meat ones are fine)

![20220120-030526-cataclysm-tiles](https://user-images.githubusercontent.com/7831163/150265307-47001397-0050-419c-ad63-a983c7094746.png)

I'm reasonably confident that I did check the calories before crafting, and that porkbellies did have a pretty high number to them.

I have no idea how that happened, and i cannot reproduce this in a test world. I *think* i was interrupted during craft due to sun setting down and it getting too dark to craft, but I'm not sure.

### Steps to reproduce

Can't reproduce at will, sadly.

### Expected behavior

calories being preserved upon craft...

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 56ae13e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by BrettDong** [comment]
Does the number return normal after save and reload?

**Comment by moxian** [comment]
Oh! It does!

And here's the log of the botched crafting, in case this is helpful. No interruptions contrary to what I said in OP, but there is an autosave happeing: 
![20220120-052513-cataclysm-tiles](https://user-images.githubusercontent.com/7831163/150278894-4e440c52-f6bb-4278-a1af-c0b1bdd2fa2e.png)

**Comment by LeahLuong** [comment]
#51361 is 1 of the earlier reports of this issue & contains links to several others like it.

**Comment by moxian** [comment]
closing as duplicate.
