### ISSUE TITLE
Add guide to making scenarios. Then add link to new contributors page.

### ISSUE THREAD

**Issue by JonathanLochridge** [CleverRaven/Cataclysm-DDA#54593]
### Is your feature request related to a problem? Please describe.

I wanted to add a new scenario and discovered there was no guide for it. The basic elements were pretty easy to get down once I found the file for it. But there are several smaller things which are unclear. If someone made on it would be nice. If no one does than if I manage to figure out how to make them I might try making one? But I currently can't.

### Solution you would like.

Add guide to making scenarios. 
Then add link to new contributors page.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
