### ISSUE TITLE
Portal storms persist across games

### ISSUE THREAD

**Issue by moxian** [CleverRaven/Cataclysm-DDA#54599]
### Describe the bug

If you die during a portal storm and immediately start a new game, the new game would have active portal storm too.

### Steps to reproduce

1. Start a new game with "Outside during strong portal storm" scenario
2. Die before portal storm is over (suicide works)
3. Optionally, delete the world.
4. Without closing the game client, start a new game with non-portal-storm scenario (say, Evacuee)
5. See that Portal Storm is "still" raging on.

### Expected behavior

new world - new weather!

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 56ae13e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

quick github search brings me this comment https://github.com/CleverRaven/Cataclysm-DDA/issues/53625#issuecomment-998188350 which sounds very relevant

**Comment by LeahLuong** [comment]
It looks like #54482 is supposed to fix this. This is a dupe issue & prob irrelevant in the next experimental.

**Comment by moxian** [comment]
Closing as obsolete then, thank you.

**Comment by Ramza13** [comment]
This sounds like a different issue than the linked bug.  I'll take a look at it when I get some time.

**Comment by Ramza13** [comment]
So  #54482 would have had no effect on this at all.  I can't get this to happen but if you still can this sounds like a totally different bug.  If it wasn't for step 3 I'd know what was going on, the global variables for a world shouldn't reset but deleting the world totally prevents that.  

If you still see this let me know.  Thanks

**Comment by moxian** [comment]
As of the latest version, this does not reproduce on my end either. Not sure if this was #54482 or something else, but it's fixed.

**Comment by moxian** [comment]
Ok, i tried to bisect the problem, and I am no longer able to reproduce it even at my original `2022-01-15-2213` / 56ae13e despite seemingly following all my usual steps (and, yes, i'm 100% confident i've been deleting worlds in the OP).

I don't think there's value in reopening the issue given the lack of solid repro steps, so let's regard it as a weird fluke.
