### ISSUE TITLE
Error Occured on Fresh Start while Walking through field by swamp.

### ISSUE THREAD

**Issue by JonathanLochridge** [CleverRaven/Cataclysm-DDA#54603]
### Describe the bug

Error Occurred on Fresh Start while Walking through field by swamp. After finding and looting a single item from a non-zombie body.
'''
 DEBUG    : tried to put an item (blazer) count (1) in a container (null) that cannot contain it: pocket with type (CONTAINER) not found

 FUNCTION : ret_val<bool> item::put_in(const item&, item_pocket::pocket_type, bool)
 FILE     : src/item.cpp
 LINE     : 1399
 VERSION  : d740104
'''

### Steps to reproduce

1. Make player 
2. Walk by field by swamp
3. Keep going till you find a corpse.
4. Hope you can actually see the debug message

### Expected behavior

To not get a debug message.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: d740104 [64-bit]
- Graphics Version: Tiles
- Game Language: System language (English)
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by NetSysFire** [comment]
This looks oddly similar to #53785

**Comment by JonathanLochridge** [comment]
Maybe it's the same bug form. But I didn't see any zombies in sight at the time?

**Comment by NetSysFire** [comment]
Make sure there are no craters near you

**Comment by NetSysFire** [comment]
@JonathanLochridge If you know how, try using the patch mentioned just above and see if that fixes your issue
