### ISSUE TITLE
The encumbrance effects sections for some body parts contain duplicate, impertinent stats from the hands section.

### ISSUE THREAD

**Issue by VitreousEyes110** [CleverRaven/Cataclysm-DDA#54605]
### Describe the bug

In the '@' menu, in the area below the stats, encumbrance and speed sections is a space that shows how exactly the encumbrance of body parts influences the character. The sections for the mouth, arms, legs and feet contain duplicate information from the hands section that isn't pertinent to those parts. The head, eyes, torso and hands do not display this duplicate information.

The specific stats that are duplicated from the hands section into other body parts' sections are:

- Gun aim speed modifier
- Melee and thrown attack movement point modifier
- Reloading movement point cost
- Dexterity when throwing items
- Hand dispersion when using ranged attacks

### Steps to reproduce

1. Create a character and heavily encumber one of the body parts mentioned as bugged.
2. See the irrelevant information in that part's section which will remain at the default x1.00 / +0.00 since the hands aren't encumbered.
3. Encumber the hands and see the stats on the bugged part change due to hand encumbrance.

### Expected behavior

The hand information should be relegated only to its own section, and not be duplicated in other parts' sections implying that encumbrance on those parts influences those stats.

### Screenshots

The encumbrance effects section for the feet showing the duplicate hands information.
![FeetBugged](https://user-images.githubusercontent.com/45680256/150308105-39ef6f12-b6b3-484e-8362-42e6459e592d.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 1607
- Game Version: 13d52d1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-12178.
![изображение](https://user-images.githubusercontent.com/11132525/198817970-97d27cc8-48c4-4b38-9590-00e3ac178908.png)
