### ISSUE TITLE
Increase variety between Overmaps

### ISSUE THREAD

**Issue by JonathanLochridge** [CleverRaven/Cataclysm-DDA#54613]
### Is your feature request related to a problem? Please describe.

I started talking on the discord with a couple people and an agreement arrived that  a lot of overmaps were a bit too similar content-wise. As well as the number of NPCs being a little off the target number.
This particularly relates to overmap specials.
There are a few which make sense for them to be everywhere though. so that is good.
But, due to the math for the mapgen Pretty much every overmap special will occur at least once on every overmap.

### Solution you would like.

Make overmaps a little more sparse special wise. But not too much.
Potentially removing the part that reshuffles unchosen or invalid overmaps with a low max value back into the ones that can come up. 
Also add something to the C++ to track faction locations when they generate. That way breadcrumb missions can reference that instead of having to scan for a valid location to point at.

### Describe alternatives you have considered.

-Add a new tag for spawning specials that shouldn't appear in every tile. But, could possibly cluster so you get multiple in a tile.
-Simply reduce the max occurrences of some of the less common specials to make them a little sparser.
-Some larger scale structure to make it so that overmap special spawning checks adjacent overmaps(After long distance overhaul?)
-Shift some specials to uniques?
-Add more unique specials? 
-Variable spawn rates based on values of a flag or variable. Such as places that spawn more frequently near the refugee center. 
### Additional context
Ideas here collaboratively made with the assistance of bombastic slacks, vernera3, and Mogan.
-Ensuring Faction mission targets spawn more or are clustered around the factions would be good. Potentially
(Intuitively bandits and such would be more common near other people to rob.)

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
