### ISSUE TITLE
Still Sand

### ISSUE THREAD

**Issue by LeahLuong** [CleverRaven/Cataclysm-DDA#54619]
### Describe the bug

"Sand (1 charge)" is listed as a tool (not a component) for crafting a still but 1 charge of sand is consumed thru crafting. From #47226, the sand is presumably used in shaping the copper tubing & should not be used up. There, it's mentioned you _**should**_ get your sand back.

### Steps to reproduce

1. Craft still.
2. Still (still) don't give/get sand.
3. ???
4. PROFIT!

### Expected behavior

I expected that still level would increase, because all other skills can increase in level.

### Versions and configuration

Android 0.F-3 Tiles English vanilla

### Additional context

Personally, I'd like to see the sand simply removed from the recipe. Sand in CDDA is not as plentiful as IRL & it feels silly to dig a shallow pit (or multiple) or spend 10 mins pulling apart a sandbag barricade to get a single handful of sand so you can bend copper tubing. Could dirt be used as a substitute?? The description for dirt says it includes sand but you have no way of sifting it out.

**Comment by Drew4484** [comment]
Dirt doesn't work great for shaping, especially soil. Ideally you want something that is homogenous in size and thermal qualities that doesn't compact, and even some unfiltered sand is closer to that than most fill dirt. The results with poor material can cause kinks or breaks in the pipe as you work it.

**Comment by mqrause** [comment]
Setting the quantity to `-1` should fix using up the sand.
