### ISSUE TITLE
Revisiting the Antidote Issue

### ISSUE THREAD

**Issue by LeahLuong** [CleverRaven/Cataclysm-DDA#54621]
### Is your feature request related to a problem? Please describe.

Near the end of #25288, kevin "The Holy Hand" granade remarked if countermeasures were introduced for poisons, that might justify augmenting poisons. Today, we find ourselves in the opposite scenario: poisons _**have**_ been augmented but no countermeasures have been introduced. Blood Filter CBM can do it but we've always had that. Poison Resistant mutation is another old standby. I'm talking about craftable antidotes akin to what is talked about in the aforementioned thread.

### Solution you would like.

They should prob be perishable & need refrigerated storage. Would be neat if you could occasionally find viable doses in certain labs. A simple first pass could introduce a universal anti-venom but ideally we'd have a countermeasure for each _**type**_ of poison (paralytic, necrotic, enervating, etc.).

### Describe alternatives you have considered.

If CBM's are more plentiful thanks to complete Exodii implementation, then there may be no need for this feature request. Conversely, if they are rarer, the need is more urgent. Food for thought.

**Comment by coyo7e** [comment]
I agree that antidotes are super rare and difficult to obtain at the point where poison is an actual threat. It seems like it's currently all or nothing, you either can spot trapdoor spiders etc from 15 squares away while driving past at 45 mph, ignore piles of other spiders, rattlesnakes, etc, or your character is weak enough that they have a super low chance of surviving.

It'd be nice to have a universal antivenom kit type item spawn somewhat reliably in ambulances, hospitals, zoos, schools (do any school variants have a nurse's office? I don't think I've seen one,) doctor offices and the like. Even having a "bee-sting kit" epi-pen that helps would be a big help for many characters who can't just farm exodii or play mutation roulette. 

As it stands currently, I don't even think epinephrine shots do much to combat any effects but asthma?

**Comment by Venera3** [comment]
They all  have the prophylactic, RX-8(?), and Panaceus as terrestrial magic cures of different flavor and level of handwavyness (and Panaceus is *really* pushing it). 
Setting up anything like antivenin production in the postapocalypse isn't a reasonable goal, and real-life kits are anything but universal (and tend to be pretty rare). 
An epi-pen saves you in an anaphylactic reaction, it does nothing to the venom's main effect, and we don't have proper allergies.

**Comment by LeahLuong** [comment]
Setting up anything like mutagen production in the post-apocalypse isn't a reasonable goal. This is why you typically make only small batches of the stuff for personal use utilizing dedicated scientific equipment. This is what I'm suggesting for anti-venom although not as technical as extracting the genetic essence of terrestrial animals & infusing it w/ the blob's anomalous influence. More like farming the  blood lymph of livestock exposed to non-lethal doses of the poison of your choice. A syringe & some sort of separation apparatus would prob be sufficient.

Non-sequitur: Panaceus seems **extra**terrestrial based on its description.

**Comment by Venera3** [comment]
Mutagens are you tricking the eldritch god infesting your flesh into giving you cool new bits, explicitly breaking how biology works. Unlike extradimensional bullshit antivenom production is a real and very, *very* fiddly thing that should work as it does in reality - and no, you don't get to handwave away titer monitoring across a month of inoculation and separating plasma with "idk a syringe and a separation funnel". Generally anything involving blood products that don't end up in a sausage requires the level of infrastructure your survivor has no access to - a still functioning blood bank *could* maybe do it, but they'd have more useful things to do until supplies last.

**Comment by LeahLuong** [comment]
You know, you're right. Ain't no 1 got time for month-long titration & WHO-approved purity levels of antibody-based serum therapies! Modern problems call for modern solutions.

Look up Brian Lohse or Serpentides. They're working on manufacturing synthetic antivenom that acts as a chemical binder on multiple types of snake venom & that's shelf stable. In the near future world of CDDA, it's possible multiple such companies have arisen to corner various sections of the antivenom market, from reptiles to bugs to aquatic animals. Synthetic production methods have great potential to be much more easily regulated, less expensive, less time-intensive, & therefore more widely available. It's possible you could find a product like this @ your local pharmacy or inside your home's 1st aid kit. Maybe even something you could fabricate using a chemistry kit & the right knowhow.

The game already has books on toxicology & these could be updated w/ recipes for these antivenoms. The epi-pen already in-game could be given more functionality in countering anaphylaxis induced by bees, wasps, or snakes. & it's possible covert Science was being done in covert places where they kept thorough documentation of their methods & tools. What I'm saying is it's an opportunity for a secret lab extra where you might find giant, toxic fauna in captivity (or recently there) & other goodies (& baddies).

How cool would that be?? It would have to be cooler than sitting around for a month jabbing a horse w/ poisons in the hope it lives to produce a viable blood serum.

**Comment by Venera3** [comment]
The "synthetic" in that phrase means "can be made without natural products", not "take two parts bleach, one part lye, and scream APPLIED SCIENCE at it hard enough". After an orienting look through Lohse's publications (nice "do your own research!", by the way) I'm going to assume their synthetic antivenom involves protein encapsulation - that mechanism of action is not a thing you're going to be cooking up in your shed, be it liposome-based or a glycopeptide scaffold. 

That leaves us with finding the stuff, and not in your corner store - maybe oh I don't know, as part of an all-purpose emergency medication pack made for the military? It could even have a nice technobabbly codename, something like `<letter><letter> - <number>`, that's always a good format. 

Epinephrine still wouldn't help with bee/wasp stings' own effect.

More lab locations are always good to have, but they're very much a tangent to "venoms are not nice, let me make antivenom pretty please".

**Comment by LeahLuong** [comment]
@Venera3 Well, it's good to have you on board w/ the idea, if only begrudgingly. Also, thanks for complimenting my research. & let's be on honest: neither of us knows how this stuff is currently being made IRL. Maybe it is as easy as growing Penicillium & doing a voodoo mambo by the light of a full moon.

A possible 1st iteration of this feature may very well be simply introducing some consumable antivenoms of various sorts, as you suggest. Later, as we learn more about how they're made IRL, they can be made craftable in game. Simply having them in game will help create more opportunities to springboard to new lab designs, char creation options, & overhauls of existing assets. Imagine a zookeeper who works w/ poisonous reptiles, or an insect hobbyist w/ a penchant for toxic varieties.

**Comment by Venera3** [comment]
....no, I was slightly snarkily pointing out that RX-12 already exists in the game and does what you want.

**Comment by LeahLuong** [comment]
What??

**Comment by estebandellasilva** [comment]
Please correct me if iam wrong but it has been established that the player character is infected with the Blob. 
(which iss kinda seen in the increased healing rate of the characters)
Could this assumption be kinda used in creating a "survivor antidote" - because do we really need to cure the antidote or maybe we can give the blob inside the body of the player some support that it can defeat the poison/venom that iss currently affecting you? 
Should be a learnable recipe at high stats (applied science 6 + first aid 6 + survival 6) or you can find it in a researchnote or something like that because you arent the only person who tested such stuff.

**Comment by Venera3** [comment]
You're starting at "I want to be able to cook up X in my van" and working backwards. For that matter, you already *can* cook up blob-based slightly magic stuff to make you immune to venoms, or turn your blood to acid, or all the other weird stuff mutagen lets you get away with.

**Comment by estebandellasilva** [comment]
Maybe my approach iss different, but with the pandemic going and and the discoveries and stupidity combined we have seen the last years would you say that some survivors would not be desperate/stupid enough to test some stuff on themselves and maybe discover stuff that was not normal before people where infected with the magic space thingys that is also used to make mutagens. (discoveries which can give you effects which arent permanent)
And these informations and discoverys would be something you find more the longer the game iss going on (kinda the opposite of whats going on with stores being looted the longer the game goes on).
Heck you can go full stupid if you want and try the fight poison with poison approach and inject with a different poison to counteract the first one.(i kinda like the idea but i think this one iss unreasonable)
I am not saying this survivors antidote should be somthing thats a cureall for poison but it could give the player a way to fight it.

**Comment by LeahLuong** [comment]
Enhancement/Feature tag, please!

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
