### ISSUE TITLE
(Car) Stereo System Does Not Increase Focus When Used

### ISSUE THREAD

**Issue by coyo7e** [CleverRaven/Cataclysm-DDA#54627]
### Describe the bug

This seemed like a no-brainer: I was driving and wanted to save batteries on my mp3 player, so I turned on the car stereo system and went for a joyride. Sadly though, even after driving for over half (with Vehicles skill toggled off) an hour I gained no focus, despite it increasing the danger of driving slightly since it attracts attention from aggro monsters and some wildlife.

It seems like this is something that could be easily tweaked and which would make sense - people like to play music while driving! It could even increase the mood and/or focus of NPCs who're also in the vehicle with me!

### Steps to reproduce

1. Get near and/or drive a car with a stereo system.
2. Turn on stereo system.
3. Notice no focus gain despite it seeming to pull from the same list of music types etc.

### Expected behavior

Expected to gain focus while playing music.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: d740104 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by LeahLuong** [comment]
Unless this was broken by something in recent builds, it should still be working as intended. I'm in 0.F-3 (latest stable) & was able to get the max bonus for "Music" (+30) from stereo.

Make sure the stereo is installed on the same tile as the driver's seat. Press 'v' to view effects on morale & confirm the bonus isn't being countered by some other malus(es).

**Comment by coyo7e** [comment]
The stereo was in the driver compartment and in good condition. It was just a random car I found.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-12178.
![изображение](https://user-images.githubusercontent.com/11132525/198818065-3b807d89-bac6-4d19-8c09-0914373a4a46.png)
