### ISSUE TITLE
Several clothing items can't be cut up.

### ISSUE THREAD

**Issue by Pyritefoolsgold** [CleverRaven/Cataclysm-DDA#54625]
### Describe the bug

It seems like some items were missed when converting from cutting items into rags to cutting them into patchwork. So far I've identified:

Sundress,
Undershirt,
Pair of Socks, ankle socks, wool socks, XL Socks, XL Wool socks
Pair of white gloves, ~~Pair of studded gloves~~
Chestwrap
Skirt, Nanoskirt

There may be more, but those are the ones I either ran into in game or could easily find in the spawn menu. In my judgement all these should be cuttable, but there are some that arguments could be made for.

### Steps to reproduce

1: Make a character in a world
2: Spawn a pair of scissors and the above items
3: Put the clothing items on the ground and attempt to butcher them. 
4: Spawn a pair of jeans.
5: Put the jeans on the ground and butcher them, notice the 'cut up' option.

### Expected behavior

I expect that all the items I listed should be able to be cut up with scissors quickly, like a pair of jeans or a shirt can.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 497ae72 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by coyo7e** [comment]
Can't see studded items being cut up to make much of use, because the rivets leave holes in them and you shouldn't be able recover the rivetted studs themselves for anything of use. I've taken apart a lot of garments IRL and rivets are always just something you cut around and throw out.

**Comment by Pyritefoolsgold** [comment]
That's a valid point, removed those from my list.

**Comment by pjf** [comment]
I'd be happy enough with studded items giving a chance for some scrap metal, even if there's no other usable material.

A big part of me wanting to be able to cut up items is just to keep things tidy.

**Comment by cybercapitalism** [comment]
The issue seems to be that the items in question weigh less than the resulting subcomponents. Compare the weight of the sundress (0.13lbs) to the weight of a patchwork cotton clothing part (0.22lbs). This is true for each item on the list except for the studded gloves.

**Comment by Pyritefoolsgold** [comment]
If so, I think that's the problem for a lot of them. A sundress and a skirt should each weight at least a quarter pound.

This list seems to corroborate, though if any owners of the listed items would like to literally weigh in it would be appreciated. 

https://rocketmf.com/en/weight

**Comment by cybercapitalism** [comment]
While not the same, #54657 deals with a similar issue with how subcomponents and weight are measured.

And, here is the line dealing with the weight checks. 
https://github.com/CleverRaven/Cataclysm-DDA/blob/017f47190bf8c93488c9ef6f10ab814698fe20cf/src/iuse_actor.cpp#L1488

**Comment by coyo7e** [comment]
> The issue seems to be that the items in question weigh less than the resulting subcomponents. Compare the weight of the sundress (0.13lbs) to the weight of a patchwork cotton clothing part (0.22lbs). This is true for each item on the list except for the studded gloves.

imho, the issue is that some items are just not something you are able to take apart for parts, the ones which take extra time etc are just icing on the cake. I don't really care what the result is from most of the outliers, merely that there are outliers that make no sense - like towels not being cuttable or disassemble-able, when it seems obvious they should result in a couple/few rags and probably thread as well.

I bow to the OP iun this issue, and do not wanna add a bunch of extra items to their main point which I feel is strong and valid.

**Comment by Pyritefoolsgold** [comment]
After some review, I think the best solution for this end of the issue would be to reassign the weights for a few clothing items. I'd suggest around .5 lbs for a skirt and .6 for a sundress, and maybe right about .22 for the undershirt and chestwrap. Throw in a slight nudge up for the long underwear top and bottom and that would cover most of the items that keep being left behind after a clothes-butchering session.

**Comment by cybercapitalism** [comment]
> After some review, I think the best solution for this end of the issue would be to reassign the weights for a few clothing items. I'd suggest around 0.5 lbs for a skirt and 0.6 for a sundress, and maybe right about 0.22 for the undershirt and chestwrap. Throw in a slight nudge up for the long underwear top and bottom to get them over 0.22 and that would cover most of the items that keep being left behind after a clothes-butchering session.

Since the core issue is that the subcomponent has to be a standardized weight and does not care about surface area, I agree with this solution. I will edit the values and submit a PR.
