### ISSUE TITLE
Repetitive Disassembling Requires a Lot of Keypresses

### ISSUE THREAD

**Issue by coyo7e** [CleverRaven/Cataclysm-DDA#54622]
### Describe the bug

This is something that's kind of annoyed me for a while, especially since you often have to wield a lot of larger/heavier items to attempt to disassemble them: taking apart a large number of items requires a lot of keypresses, to the point it's kind of obnoxious imho. You have to open the menu, scroll to or search for the item unless you're lucky enough for it to be assigned a hotkey (which often changes between attempts, as the pile size changes), and possibly have to back out of the menu, wield the item, and then try again.

It seems like this is just an onerous task considering how often one needs to take things apart for materials etc.. My first thought was, _"Why not add the "**-**" key for "repeat previously crafted item" to disassembling items as well? It works for practising crafting already, and having it prompt the player to pick up nearby materials could make it easier to go through something like a large pile of smartphones, short strings, etc."_ Failing that, maybe just a new keybind or allowing the player to declare "x number of time" would be nice (it sometimes asks how many of a stack you want, but it seems inconsistent currently, where I can say to take apart x number of cotton sheets, but not x number of short strings for instance) something, to repeat disassembling the last item one worked on, would be helpful - even if it prompts about stuff that the player has wielded or worn or because they aren't carrying it (like crafting/practising currently works) it could speed up this process a lot, and help save people from carpal tunnel.

Thoughts?

### Steps to reproduce

1. Try to disassemble a large number of the same item type, without having to manually re-enter a filter or scroll through a long list, every time.

### Expected behavior

Expected the - key to repeat last craft, would consider disassembling items a crafting task and thus look for similar "materials" as the last thing I took apart.

### Screenshots

![image](https://user-images.githubusercontent.com/80022377/150453605-0dd41fd9-a5d7-4c1c-8b06-96aad73cf22a.png)

![image](https://user-images.githubusercontent.com/80022377/150453570-95f936ee-3e30-4ee1-8576-79de0d6e7b44.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: d740104 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Drew4484** [comment]
Have you tried the Disassembly Work zone?

**Comment by coyo7e** [comment]
No, I've never heard of such a thing but it doesn't show up in the normal construction menu, which indicates that I'd have to set up a faction base and have multiple NPCs and then declare jobs for it..?

**Comment by Drew4484** [comment]
> No, I've never heard of such a thing but it doesn't show up in the normal construction menu, which indicates that I'd have to set up a faction base and have multiple NPCs and then declare jobs for it..?

It's under zone management, press `Y` to bring up a list of zones, then 'A' to add a zone. Select 'Disassembly Work', place the zone, and anything you drop in that zone will be disassembled (with appropriate tools).  Once you've set zones, use 'O' to use them.

**Comment by coyo7e** [comment]
To be frank, faction bases and zones are already pretty complicated, and using a zone means I'd need to know exactly what I want tot ake apart and then move it all to that area, when it seems like I ought to just be able to say "take apart short strings 30 times" or hit the same key a few times if I just need to get a half-dozen lenses from phones or something.

**Comment by Drew4484** [comment]
You don't need a base for this, I designate a single tile near my workbench and drop things there as I sort inventory. You can also put a custom filter over the same tile as the zone and automatically sort things like phones into the disassembly zone, then batch disassemble things all at once. It isn't the exact solution you're asking for but it already exists in game and zones in general are very useful.

**Comment by LeahLuong** [comment]
Another option is putting all the things you want do disassemble on 1 tile, stand over it, & use the 'B'utcher command. Cut open 10 bundles of leather earlier today in 0 secs using just a few key presses.

Don't forget there's a setting to remove the query on disassembly.

This prob should have been a feature request but you made it a bug report. Either way, I recommend you close it before more people see you trying to put your foot deeper into your mouth.

**Comment by coyo7e** [comment]
Or you could just not be a jerk
