### ISSUE TITLE
The Tiny mutation and being smaller than human-sized should passively grant the hiding benefit of crouching.

### ISSUE THREAD

**Issue by RianQuenlin** [CleverRaven/Cataclysm-DDA#54635]
### Is your feature request related to a problem? Please describe.

_I posted this on the BN branch but I think it'd be a good addition to the main branch._

A character with the Tiny mutation is less than two feet tall at minimum and just over three feet maximum. This would result in them being smaller than many furniture tiles in the game such as counters, and smaller than a crouching human to begin with. Logic dictates they would not need to crouch to hide behind countertops and sofas but this is not the case in-game

### Solution you would like.

A character that has the Tiny mutation (and perhaps enemies smaller than human-sized) should treated as crouching for the purposes of concealment at all times.

### Describe alternatives you have considered.

I did consider suggesting a height threshold for cover, but description seems to be entirely cosmetic, and I assume this is by design.

Furniture could possibly be treated like a fence or other obstacle if it gives a certain level of cover if one is smaller than a human but this would probably be frustrating.

Enemies that are shorter than humans (and outliers like crawling zombie) could also benefit from this.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
