### ISSUE TITLE
Game crash when wants to refill container

### ISSUE THREAD

**Issue by Rabioxxx** [CleverRaven/Cataclysm-DDA#54636]
### Describe the bug

Game crash when choosing option "Refill container with water >Pour into a container > Hydration Pack" on the RV clean water tank. Also when choosing option "Fill available tank".

### Steps to reproduce

1. Load into the world "Hauula" with "Simon" character.
2. 'e'xamine NW tile - this one where vehicle tank (clean water) is.
3. Choose "Fill a container with water"
4. Choose "Pour into a container"
5. Choose "Hydration pack"
6. Game Crash

### Expected behavior

I expected to get water from clean water tank into hydration pack.

### Versions and configuration

- OS: Windows 10
- Game Version Build: 2022-01-15-1927
- Graphics version: a52fd9c (tiles)
- Ingame language: English
- Mods loaded: dda, Disable NPC Needs, No Fungal Growth, Bionic Professions

### Additional context

[Hauula.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7912827/Hauula.zip)
[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7912829/config.zip)

**Comment by BrettDong** [comment]
Fixed in #54578.
