### ISSUE TITLE
Camera photos no long make enemies temporarly blind

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#54639]
### Describe the bug

Several months ago (July-Sept 2021?), you could take a photo of an enemy at close range in a dark environment, and they'd become blind for a few turns afterwards.  They'd need to be within 3 or 4 tiles of the player, and the professional camera worked better than the normal or phone ones, (iirc!).

This no longer appears to be the case?  I tried to figure out _why_, but couldn't find any PR's about this.

### Steps to reproduce

Be in a dark room, with one or two zombies who use eyes to see.
Let them get close.
Take an exceptional photo of them.
See that they are not be blinded.

### Expected behavior

Temporary night blindness.

### Versions and configuration

Win 10, tiles, e49949d

Additional mod invariant.

**Comment by kurtisvetter** [comment]
I can confirm that with both the professional and regular camera, taking a picture of a regular zombie in the basement of a house, the zombie did not get blinded. I haven't used the cameras before this though, so I don't know if causing blindness ever worked in the past.

**Comment by chrispikula** [comment]
For further issue in the future,
