### ISSUE TITLE
Save compression

### ISSUE THREAD

**Issue by Nerdy314159265** [CleverRaven/Cataclysm-DDA#54634]
### Is your feature request related to a problem? Please describe.

Cataclysm generates a lot of tiny files and that makes it a pain when you need to copy it somewhere or compress a save manually, etc.

### Solution you would like.

Saves should be compressed into fewer and larger files.

Ideally either a compression format that allows for some relatively random access is used and the saves become monolithic 
or
save files are dynamically compressed and decompressed around the player with immediate surroundings sitting uncompressed to distant lands all in a large compressed file.

**Comment by Hirmuolio** [comment]
#44218 is step towards that. I think it only adaded support for loading compressed saves so you'd need to compress the save with external program.

**Comment by Nerdy314159265** [comment]
Based on the bash file given for making a compressed world save to test with it seems (if I'm remembering the commands right) like it only works by individually compressing the files and not compressing multiple files into a single compressed file.

It would save quite a bit of disk space still but the insane numbers of files (10s to 100s of thousands or more depending on your travel distance) is still an issue and there are more gains to be had by grouping files together.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
