### ISSUE TITLE
Can't auto-mop in the dark even though mopping doesn't require light

### ISSUE THREAD

**Issue by Rayeneth** [CleverRaven/Cataclysm-DDA#54641]
### Describe the bug

When I use "pick action" menu with shift-o and attempt to mop a zone it tells me it's too dark, however I an manually mop in the dark.

### Steps to reproduce

1. have mop at night
2. set a mop tile zone
3. shift-o, select mop area.
4. can't mop!
5. walk up to spilled liquid
6. a > mop
7. stain vanishes!

### Expected behavior

Either mopping needs to be a non-night activity or zone mopping shouldn't require light. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 5662136 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Generic Guns [generic_guns],
    Blaze Industries [blazeindustries]
]

**Comment by chrispikula** [comment]
The telescopic mop doesn't do it when wielded either, even during the day, at least on Win 10, tiles, e49949d.

**Comment by LeahLuong** [comment]
Survivors should get an auto-learned recipe @ Fabrication 1 to duct tape a flashlight to a mop (or telescopic mop) so dark-mopping is no longer such a hindrance. I mean, this is what I do when I encounter this situation IRL. I find it hard to believe the devs could've overlooked something simultaneously so crucial & yet so easy to implement!

**Comment by mqrause** [comment]
This is an issue for all multi activities. It just checks the available light level and not what's needed to perform the task.

https://github.com/CleverRaven/Cataclysm-DDA/blob/017f47190bf8c93488c9ef6f10ab814698fe20cf/src/activity_item_handling.cpp#L2989-L2995

**Comment by mqrause** [comment]
> The telescopic mop doesn't do it when using the auto-mop option and wielded either, even during the day

This doesn't seem to be from an in repo mod? It's unrelated to the issue anyway. Probably just missing the mop use action.

**Comment by chrispikula** [comment]
> This doesn't seem to be from an in repo mod? It's unrelated to the issue anyway. Probably just missing the mop use action.
Fair, yeah, that's on me.
It actually comes from the code that calls out the item, specifically:
https://github.com/CleverRaven/Cataclysm-DDA/blob/293b3265ad767ccc665550391bfd511551fdfa41/src/handle_action.cpp#L1915
