### ISSUE TITLE
Accepting Asthmatic's Mission Twice Crashes Game

### ISSUE THREAD

**Issue by coyo7e** [CleverRaven/Cataclysm-DDA#54648]
### Describe the bug

Ran into this just now, started the game and had the asthmatic NPC nearby, I picked up his quest and then tried to trade some stuff with him and backed out, which put me back to the initial "introduction" dialogue. I asked if I could help and accepted the quest again, and got an error about already having a mission - then game crashed out without leaving the error screen.

I don't usually try to trade with NPCs like that until they are following me however, it felt odd to have the "drop your weapon!" etc options pop up as soon as I backed out of the trade menu via ESC.. I wasn't sure if the quest might get screwed up if I didn't accept it again so I just did the acceptance a second time and poof, game over dude goodbye unsaved new character,

I used "Musician" and the new "(un)living History" Profession and Scenario, fwiw.

### Steps to reproduce

1. Spawn Asthmatic NPC, begin dialogue with them and accept their quest.
2. Before exiting dialogue, open trade menu and then exit out.
3. Note that the introduction dialogue pops up again, accept quest again.
4. Hit "I" for ignore error, and bam, crash.

### Expected behavior

Expected to not irretrievably crash.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: a3d494f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7917289/config.zip)

**Comment by LeahLuong** [comment]
Looks related to #52220 & possibly #52585. Common features are buggy conversation w/ intimidate options preceding a crash w/out log. It didn't generate a crash.log, right??

**Comment by coyo7e** [comment]
> Looks related to #52220 & possibly #52585. Common features are buggy conversation w/ intimidate options preceding a crash w/out log. It didn't generate a crash.log, right??

Don't think so, the crash.log file was nothing but a series of hex codes that looked like memory references or some such.
