### ISSUE TITLE
Hand encumbrance is too penalizing for melee

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#54646]
### Is your feature request related to a problem? Please describe.

Currently, hand encumbrance is roughly 2% slower attack speed per point of encumbrance. This feels too significant especially as many gloves have huge amounts of encumbrance, and the reduction in melee swing speed is very punishing. Logically speaking, wearing thick gloves should not really be making your swings slower, when wearing thick work gloves I'm not swinging a hammer any slower than I would be without and in fact might be able to swing better since they cushion my hand. This gets especially ridiculous when wearing boxing gloves, which while totally unsuited to holding weapons, will make your punches nearly 70% slower. If you were wearing some really heavy gauntlets, it might throw off your balance, but it shouldn't be affecting how fast you can swing a sword, stick, or what-have-you. 
There's no question that even mild amounts of hand encumbrance makes finesse tasks way more difficult, but attacking with a weapon or your bare hands does not require fine use of your fingers and shouldn't be affected as such.

### Solution you would like.

There are a lot of things hand encumbrance can affect. Speed to grab items from pockets, speed to apply bandages, ability to climb, reload a gun, craft items, pick locks, all of which are things that would fall under the manipulation score. If your hands were extremely heavily encumbered it might also affect your grip strength making it harder to hold onto a weapon, or anything for that matter. This could be represented by the manipulation score affecting the odds of being disarmed. 

### Describe alternatives you have considered.

The effect of hand encumbrance could also be reduced, and/or it could be given a "grace period" like other body parts. There could also be a compelling reason why encumbrance affects speed so much, but I'm not aware of what that would be.

**Comment by Venera3** [comment]
Yeah, swing speed should use the melee stamina modifier ( encumbrance-adjusted arm lifting score). I'll get at it soon, unless somebody else wants to pitch in.

**Comment by Alex-Folts** [comment]
Heavy gloves makes you swing slower because you need accelerate additional mass. I mean, try to swing fast with your hand holding 1kg weight, you'll feel it is slower.

**Comment by coyo7e** [comment]
> Heavy gloves makes you swing slower because you need accelerate additional mass. I mean, try to swing fast with your hand holding 1kg weight, you'll feel it is slower.
Sure however, encumbrance != weight. Winter gloves for instance are what, 50 encumbrance? And they weigh like half an ounce.

**Comment by Alex-Folts** [comment]
> > Heavy gloves makes you swing slower because you need accelerate additional mass. I mean, try to swing fast with your hand holding 1kg weight, you'll feel it is slower.
> 
> Sure however, encumbrance != weight. Winter gloves for instance are what, 50 encumbrance? And they weigh like half an ounce.

Yes that's the problem, we have single parameter encumbrance which cover all this inconveniences: you cant properly operate firearms with fingerless working gloves, but with this same gloves you can operate melee weapon just fine  - we don't have parameters to reflect this nuances. While weight of the gloves matters for melee weapon, but it doesn't take into account, instead used encumbrance to somehow reflect it.

**Comment by Maleclypse** [comment]
@Venera3 I've assigned this to you for ease of finding it later but people shouldn't treat that as Venera is the only person who can work on this and if you don't want to be assigned to this item let me know.

**Comment by Venera3** [comment]
Manipulation score influences ranged aim time, and *when* we get to multiwield (and with that, tracking which hand is holding which item) adding a weight-based scaling shouldn't be hard. I'd expect the wielded weapon to make more of a difference, which is already represented in weight's inherent effect on swing move cost, however.
