### ISSUE TITLE
Vehicle tap unable to fill container.

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#54642]
### Describe the bug

If you attempt to fill a container with a vehicle tap, you get a 'source vehicle not found' error.

### Steps to reproduce

Have two tanks of water on a vehicle.  (not sure if important.)
Have a faucet, and a container.
Examine the faucet, and 'Fill a container with Water'
At this point, it asks you to fill a container with your water(hot).  Which is weird, as the water in my roof-top tank is _not_ hot, and it's 19C outside.
Select your container (smaller than my tank, if that's important.)

Recieve error:
`11:18:59.822 ERROR : src/activity_handlers.cpp:1539 [void activity_handlers::fill_liquid_do_turn(player_activity*, Character*)] error in activity data: "could not find source vehicle for liquid transfer"`

### Expected behavior

Able to fill a container with water from a faucet.

### Versions and configuration

Win 10, tiles, e49949d

### Additional context

[trimmed.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7915548/trimmed.log)

**Comment by LeahLuong** [comment]
Is this a dupe of #54636?? Wasn't it fixed by #54578??

**Comment by chrispikula** [comment]
It's not a full game crash, just a debug error.  I also am not running that new of an experimental version, mine is 4 days old.

**Comment by chrispikula** [comment]
Appears to be fixed, closing.  Thanks for the info, @LeahLuong
