### ISSUE TITLE
Incorrect Description for Chicken Chunks Entree from MRE

### ISSUE THREAD

**Issue by coyo7e** [CleverRaven/Cataclysm-DDA#54658]
### Describe the bug

I noticed that this entree's description indicates that it's actively spoiling and exposed to the air, even while still sealed. 

The last sentence of the item description always says, "Exposed to the atmosphere, it has started to go bad."

Suggested edit: _"If exposed to the atmosphere, it will start to go bad."_

### Steps to reproduce

1. Spawn Chicken Entree MRE.
2. Examine chicken chunks entree.
3. Note final sentence does not match up with item's status if it's sealed.

### Expected behavior

Expected it to specify that it *would* quickly go bad when the seal is broken.

### Screenshots

![image](https://user-images.githubusercontent.com/80022377/150621138-2ebdc26c-e2c2-4834-a65a-ac409662a5e4.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: a3d494f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by LeahLuong** [comment]
It prob just means "atmosphere" in the figurative sense. As in, "The depressive, post-apocalyptic atmosphere of the world of CDDA." I bet it's the same thing for "bad" like you find in the phrase, "Bad to the bone." I mean, what chicken chunks wouldn't be more dank in a game like this??

**Comment by coyo7e** [comment]
> It prob just means "atmosphere" in the figurative sense. As in, "The depressive, post-apocalyptic atmosphere of the world of CDDA." I bet it's the same thing for "bad" like you find in the phrase, "Bad to the bone." I mean, what chicken chunks wouldn't be more dank in a game like this??

I was going to start on a campaign to rally for chicken soup's lousy caloric content at 65 kcalories per serving to be raised to be nearer to the "chicken chunk entree" (sounds appetizing don't it?), but then I googled a can of campbell's soup and it's only like 95. And I figured the included beef stick (wtfc, who comes up with those recipes!?) would add probably 150+ calories on its own.
