### ISSUE TITLE
Both XL black dragon armors' protection are "Negligible"

### ISSUE THREAD

**Issue by Naadn** [CleverRaven/Cataclysm-DDA#54666]
### Describe the bug

In Magiclysm, both black dragonscale and black dragonhide armors have very high protection value. Although the two normal suits are fine, both XL suits' protection are "Negligible protection". All demon chitin suit are fine, so there must some bug on the XL black dragon armors.

### Steps to reproduce

1. Debug to unlock all recipes
2. Look at the Enchanted table
3. Find the XL black dragon armors, any of them will work
4. Read their description

### Expected behavior

Both XL suits have same protection value as the normal suits.

### Screenshots

![image](https://user-images.githubusercontent.com/97841551/150630414-87575b91-0196-427f-8a1e-a041c70f8da0.png)
![image](https://user-images.githubusercontent.com/97841551/150630429-e5aab886-af07-4f45-ae47-f4731ead4470.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 2f4c5a5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills],
    Bionic Professions [package_bionic_professions],
    C.R.I.T Expansion Mod [crt_expansion],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Extra Mutated Scenarios [extra_mut_scens],
    Mythical Martial Arts [MMA],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm]
]

**Comment by catdach** [comment]
Looks like the "material thickness" and "environmental protection" fields aren't being inherited properly for some reason. It's strange that the XL demon chiton stuff isn't having the same problem.
