### ISSUE TITLE
Expanding the color menu

### ISSUE THREAD

**Issue by DoctorGoat** [CleverRaven/Cataclysm-DDA#54674]
### Is your feature request related to a problem? Please describe.

I was looking into changing some colors that were unpleasant on my monitor earlier when I realized how limited the options in the menu currently are. We have load template, but load template still loads the default color set and, as far as I can tell, provides no ability to define colors. Additionally, we can't edit colors ingame aside from assigning them to other colors. We also can't save templates.

### Solution you would like.

At minimum, support a colordef block in color templates, so that templates can include definitions for the base 15 colors currently in base_colors.json. This does not cause issues, and the game will happily load a completely different colordef right now if the base_colors.json is swapped out and the default template is reloaded. 

Optionally, adding a means of editing colors (press e to be prompted for RGB values, confirm/deny the replacement color) and saving the templates ingame would be pleasant. 

### Describe alternatives you have considered.

My only other real idea is manually editing base_colors.json and loading an empty template to force a refresh. I guess I could mess with my monitor settings, but adding options to adjust colors would be a good accessibility feature.

**Comment by DoctorGoat** [comment]
I would like to note two things here on further inspection. 

First, the color menu is a lot more complicated than I thought. The dk_ and lt_ prefixes can lead to invalid colors, which leads to being dumped back to the main menu. I'm not sure what can be done about that.

Second, the reason I discovered this was because of Windows' CAB content aware brightness feature. It may be easiest as a temporary solution to the game being too dark to add a contrast/brightness setting using whatever renderer comes in first on priority; If d3d11/d3d/opengl/opengles2 listen to SDL2 for a brightness/contrast adjustment, that'd be ideal. 

This is still something I think should be examined, but I can tell it's going to be more trouble than I originally thought it'd be. It might be for after 0.G.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
