### ISSUE TITLE
Calm down insect evolution

### ISSUE THREAD

**Issue by Paprika-H** [CleverRaven/Cataclysm-DDA#54677]
### Is your feature request related to a problem? Please describe.

Mutant bug evolutions scale way too much. For the most extreme example, take the praying mantis. It goes from praying mantis, 60 health, to giant praying mantis, which is 120 health. Doubled health, I can see that. Then it balloons into a great mantis, 2 400 health. Same thing with mosquitoes, 10 health, 20 health, then 400. Giant dragonfly? 50 to 1100. I feel this is absurd, especially compared to the zombies you'd expect to see that late into the game. Zombie hulks for example have 480 health, and the size of 875 liters. Fused dragonflies have a health of 1100, at 600L. Why a smaller creature has more than double the health I do not know. 

To add onto this, the mutant bugs are slow and have low morale. This just makes them annoying to fight, as the whole danger of early game bugs is that they're fast. With the heavily mutated ones, they slowly wander over to you, take a few hits, then try to escape. So either you hunt after them, wasting either a ton of ammo, or stamina and time, or just leave them for another day. You don't avoid them because they're dangerous, you avoid them because they're annoying. 

### Solution you would like.

Make insect evolutions differ, instead of just "oh now slow and tanky". I love the idea of the fused dragonflies laying a bunch of eggs, though I would like it to be slowed down somewhat. Lower the health of these insects and up the armour, and make the weak points easier for melee. This would help solve a bit of the "just get a bigger gun" issue that most monsters face, as you can't just get a bigger gun when it's armoured. Make the insects faster too, at least fast enough that a brisk walking pace is all you need to defeat them. Up the morale too, and add some more special attacks that lean into the insect. For example, blood bank mosquitoes bleeding you out, and then fleeing when the player is weak to mimic the behavior of mosquitoes just needing blood. It'll make hypovolemic shock a bit more of a threat, and something to prepare for. 

### Describe alternatives you have considered.

Remove the last stage of insect evolution, and instead have them rarely spawn in places of the original insect.

**Comment by Mikenyes** [comment]
If @Venera3 is okay with it, I'll take a crack at this- but I'll warn, me taking a crack at it does not equate to "calming it down".  I love the ideas of more varied and interesting final mutations, and agree this is an issue- not because they are too powerful, but because they are too samey and boring.

**Comment by Venera3** [comment]
Fused dragonflies are explicitly a hunk of mostly exposed meat, hence no armor. I wouldn't go with quite that much health these days ('bout 700 should do the trick), but they're eminently kiteable. The rest of megazord bugs being pretty meh is a fair observation, and it's something I'm working on changing but the bug reworks (see #45030 and the linked Discussion for the not-really up to date agenda) have taken a back seat lately. 

I'd *love* for there to be three alternate paths for each bug to take, with their own distinct flavor, but as long as the existing bugs are so universally samey as they are going deep on any one feels like a mistake.

On the progression side I think we're due a slight slowing down of monster evo in general. It will need a bit of thought put into it, and a discussion or three about the canonizable timeline of evolution, but it should happen sooner rather than later.

I know it's not your main point, but hulks are pretty left behind by the player power creep so I wouldn't use them as a measuring stick of lategame foes.

**Comment by Inglonias** [comment]
> On the progression side I think we're due a slight slowing down of monster evo in general. It will need a bit of thought put into it, and a discussion or three about the canonizable timeline of evolution, but it should happen sooner rather than later.

Turning down the default evolution speed from 4 to 6 or something could go a long way to fixing this.

**Comment by Venera3** [comment]
> > On the progression side I think we're due a slight slowing down of monster evo in general. It will need a bit of thought put into it, and a discussion or three about the canonizable timeline of evolution, but it should happen sooner rather than later.
> 
> Turning down the default evolution speed from 4 to 6 or something could go a long way to fixing this.

Not how things work, and way too lazy. The evolution scaling factor is used as a multiplier on monstergroup timers, so it would have a bunch of knock-on effects that are hard to anticipate without putting in the work a proper solution would need. Also, changing defaults at the drop of a hat is bad practice.

On health/etc scaling - progression of player capabilities is anything but linear, with the jump between mid and endgame being pretty damn close to exponential. Health isn't the most elegant way of compensating on the monster side, but it's pretty much the only option to mitigate our survivors' pile of 5,56 beside bulletproofing every monster (or a 60-tile leap attack, but that might be a bit over the top...).

**Comment by Paprika-H** [comment]
> > > On the progression side I think we're due a slight slowing down of monster evo in general. It will need a bit of thought put into it, and a discussion or three about the canonizable timeline of evolution, but it should happen sooner rather than later.
> > 
> > 
> > Turning down the default evolution speed from 4 to 6 or something could go a long way to fixing this.
> 
> Not how things work, and way too lazy. The evolution scaling factor is used as a multiplier on monstergroup timers, so it would have a bunch of knock-on effects that are hard to anticipate without putting in the work a proper solution would need. Also, changing defaults at the drop of a hat is bad practice.
> 
> On health/etc scaling - progression of player capabilities is anything but linear, with the jump between mid and endgame being pretty damn close to exponential. Health isn't the most elegant way of compensating on the monster side, but it's pretty much the only option to mitigate our survivors' pile of 5,56 beside bulletproofing every monster (or a 60-tile leap attack, but that might be a bit over the top...).

Seeing monsters ambushing survivors and other monsters would be a wicked cool addition

**Comment by catdach** [comment]
> On health/etc scaling - progression of player capabilities is anything but linear, with the jump between mid and endgame being pretty damn close to exponential. Health isn't the most elegant way of compensating on the monster side, but it's pretty much the only option to mitigate our survivors' pile of 5,56 beside bulletproofing every monster (or a 60-tile leap attack, but that might be a bit over the top...).

That's fair, scaling should definitely be more exponential than linear. I just think that the middle evolutions could stand to be a bit stronger, maybe even a new stage between the middle and final stages? but that's probably a lot of work to do for every bug. Meh, I'm nitpicking at this point so feel free to ignore me lol.

**Comment by LeahLuong** [comment]
Post a feature request for **ZOGATH, LORD OF THE UNDERWORLD, EATER OF KINGS**! I'll make sure to give it a thumbs up when I see it.

**Comment by Inglonias** [comment]
With #58547 and #58568, can we close this, or are there still outstanding issues?
