### ISSUE TITLE
Allow collapsing the sidebar HP display of similar bodyparts

### ISSUE THREAD

**Issue by Venera3** [CleverRaven/Cataclysm-DDA#54670]
### Is your feature request related to a problem? Please describe.

As part of the limb rework the current limb mutations will be moved over to actually mess with the underlying bodyplan of characters. In some combinations this will lead to pretty significant UI clutter as e.g. a cephalopod mutant will run around with 8 arm and 8 leg tentacles, each with its own HP pool and derived scores.

### Solution you would like.

Optionally collapse the HP bars of limbs of similar types and names, as long as their HP is roughly similar (or always, and display either an aggregated HP bar or the health of the most damaged limb).
Ideally the grouping would be definable in the bodypart def itself (something like an `UI_groups_with` list of BPs and a `UI_group_name`).

### Describe alternatives you have considered.

Accept not being able to see your minimap as an acceptable price to pay for transhumanity. 

### Additional context

The same grouping logic would be useful to include in `player_display.cpp:should_combine_bps`. I'll have a PR up soon that differentiates limbs if their HP is different, but for now it only checks for opposite parts (and that will be a fun question for tentacles on its own).

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
