### ISSUE TITLE
Towel Cannot be Butchered or Disassembled

### ISSUE THREAD

**Issue by coyo7e** [CleverRaven/Cataclysm-DDA#54684]
### Describe the bug

For some reason, towels are not something a player can cut up for cotton parts or rags. You can wield them, drop them on the floor, and use any variation you want but they are not something one can cut up..?

### Steps to reproduce

1. Spawn towel
2. Try to butcher/disassemble towel.

### Expected behavior

Expected towels to easily and quickly turn into cotton parts or rags, just like they do IRL when you use some scissors on them.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 017f471 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by LeahLuong** [comment]
You should prob have simply added a comment to this effect in #54625 rather than creating a new issue. You commented there recently so it's not like you're unaware of the thread. Prob unnecessary now I've linked it. Still, a waste of your time generating this thread when a sentence or 2 elsewhere would've sufficed, a waste of mine writing this to correct you, & a waste for pretty much any1 else who spends the effort reading this far.

**Comment by coyo7e** [comment]
> You should prob have simply added a comment to this effect in #54625 rather than creating a new issue. You commented there recently so it's not like you're unaware of the thread. Prob unnecessary now I've linked it. Still, a waste of your time generating this thread when a sentence or 2 elsewhere would've sufficed, a waste of mine writing this to correct you, & a waste for pretty much any1 else who spends the effort reading this far.

Jesus christ, what is wrong with you? I post in a thread, you say I'm adding more issues. I make a new thread, you tell me to post in someone else's thread. You are a serious asshole.

**Comment by LeahLuong** [comment]
@coyo7e Citation, please.

Also, please refrain from insults. Where justified, they are prob unnecessary & a detriment to positive change; where unjustified, they redound upon their utterer.

**Comment by cybercapitalism** [comment]
I was able to successfully (B)utcher a towel on the ground with a pair of scissors with version 
- OS: Windows
- OS Version: 10.0 2009
- Game Version: 2ed119b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

![image](https://user-images.githubusercontent.com/98280110/150963616-182ffed7-768f-461c-a954-5c03389fddab.png)
![image](https://user-images.githubusercontent.com/98280110/150963698-84d7b601-9e95-4f64-ade2-3aafe5d77ddb.png)

Am I doing something wrong?

**Comment by LeahLuong** [comment]
@cybercapitalism See OP:

> You can wield them, drop them on the floor, and use any variation you want but they are not something one can cut up..?

It's obvious you must be doing something wrong. Didn't you read the title thread?? Butchering's not supposed to work.
