### ISSUE TITLE
Game froze for several minutes trying to spawn an npc

### ISSUE THREAD

**Issue by moxian** [CleverRaven/Cataclysm-DDA#54683]
### Describe the bug

I was playing around in debug mode.

- started new game (all default survivor evacuee)
- revealed overmap
- teleported away from the shelter
- started crafting long cordage pieces
- game unexpectedly froze on 95% completion of 14th craft. After the craft completion the time is 07:00:49 PM which might be important?..

Inspecting the running process got me this stacktrace:

```
0x0000000000000000
cataclysm-tiles.exe!std::_Hash<std::_Umap_traits<pf::`anonymous namespace'::node_address,pf::A0x452dcbd1::navigation_node,std::_Uhash_compare<pf::`anonymous namespace'::node_address,pf::A0x452dcbd1::node_address_hasher,std::equal_to<pf::`anonymous namespa
cataclysm-tiles.exe!pf::find_overmap_path+0x744
cataclysm-tiles.exe!overmapbuffer::get_travel_path+0xef
cataclysm-tiles.exe!npc::set_omt_destination+0x60a
cataclysm-tiles.exe!npc::long_term_goal_action+0xb1
cataclysm-tiles.exe!game::perhaps_add_random_npc+0x3eb
cataclysm-tiles.exe!do_turn+0x414
cataclysm-tiles.exe!WinMain+0x825
cataclysm-tiles.exe!__scrt_common_main_seh+0x106
KERNEL32.DLL!BaseThreadInitThunk+0x14
ntdll.dll!RtlUserThreadStart+0x21
```

trying to get a peek of the trace again interminently has or doesn't have the first hashmap-related frame, but the rest (find_overmap_path and below) are still present.

While filing this report the game did unfreeze (presumably, succeeded in finding the path?). But it took longer than my patience, and in a normal run i would just angrily force-close the game.

### Steps to reproduce

n/a

### Expected behavior

Either:
- no freeze
- a warning that a freeze might happen
- the freeze happening at a more.. expected point in time. Like when trying to get to survivor center at the shelter console.
- a "hold on, it's taking a bit longer than we expected, we are not frozen, promise! Here, get a progressbar: 23342/13123123" kind of popup.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-5469-g8ba04d36fe [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by NetSysFire** [comment]
I wonder if this is somehow related to #49039

**Comment by mqrause** [comment]
I have freezes like that kind of regularly (every few ingame days), with varying durations. Usually while sleeping or doing activities. Didn't look into what happens during that time, though.

**Comment by Leland** [comment]
> Steps to reproduce
> n/a

Are you still able to repro this? Trying to do so on a release build – and including a save file – would both be super useful things if possible!

The stacktrace is helpful but without reproduction steps this might be a challenging issue to work on and keep open.

**Comment by moxian** [comment]
Ah, right.

No, i cannot reproduce it reliably, but i did back up the save after the issue occured initially:
[Walsenburg-freeze.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7922016/Walsenburg-freeze.zip)

**Comment by mqrause** [comment]
Happened to me while testing other stuff just now, so with running debugger I could look into it. I can see why that would take a while. Looping over a quintillion times...

![grafik](https://user-images.githubusercontent.com/38702195/150720102-d66fffbb-45cb-4c36-b392-ab462f5bde67.png)

Same call stack as described in the issue description.

**Comment by schealex** [comment]
i've created a new issue for this as i've not found this issue during my search for the error. Due to the newly added "hang on a bit..." behavior.
In my #63202 I've attached a save file which can be used to reliably reproduce this error within minutes.

I'd also be very glad if someone could change the tags as i don't belive this is strictly a performance topic but rather a bug. This has not been there before and as i've explained in my issue i've been playing high amount npc worlds before without any problem. But even with npc's on regular (low) settings it's rediculus to have the game hang for several IRL minutes.
