### ISSUE TITLE
Add guaranteed power armor spawns

### ISSUE THREAD

**Issue by CurtainsAmbasador** [CleverRaven/Cataclysm-DDA#54691]
### Is your feature request related to a problem? Please describe.

Power armor is not a reward, its a random event. I am more likely to find power armor in a field or cave then a military base, lab, or any realistic area. The most frustrating thing is that its been like this for years, and although I've played for 2+ years now I've never found a full suit.

### Solution you would like.

Have a static spawn for power armor.  A super dangerous area that appears later in an appropriate questline line with the promise of a single, random power armor variant. May be worthwhile for some to just try the RNG, but a static spawn for players invested and skilled enough should be an option.

### Describe alternatives you have considered.

Makeshift power armor using different exo-skeletons. While I haven't found any, I believe theres some form of industrial exo-skeleton in the game files. Having players find that skeleton, then with enough fabrication and electronics make a suit of survivor power armor sounds fun.

### Additional context

If anybody does pick this up then God bless you. Its been a pain since Ive started playing the game, and while I understand that power armor is SUPER strong I believe that it should still be accessible for late game. Also, if it was THAT strong than having it up to RNG just invites lucky day-one survivors to find a complete set in a field. Not very balanced, if that was the concern after all this time.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
