### ISSUE TITLE
No message when trying to pick up items that I can`t carry.

### ISSUE THREAD

**Issue by Joanakor** [CleverRaven/Cataclysm-DDA#54703]
### Describe the bug

When I try to pick up an item that I can not carry, nothing happens. No message, item just stays where it was staying. It is frustrating because I could think that I picked up some items, go somewhere and then realise that I did not take them.

### Steps to reproduce

1. Have almost full capacity in your backpack, sling etc.
2. Try to pick an item (like soda can);

### Expected behavior

Game should atleast prompt a player that he can`t pick an item.

### Screenshots

![cataclysm-tiles_0tVb57biMe](https://user-images.githubusercontent.com/30211338/150686337-56bcd7dc-bd05-48ec-8abb-6a8cf3bfce1c.png)
![cataclysm-tiles_iYS6d2caRp](https://user-images.githubusercontent.com/30211338/150686340-48c964c1-0d73-4770-bf85-3b5cd440b602.png)
![cataclysm-tiles_cVeKBlVggL](https://user-images.githubusercontent.com/30211338/150686498-2b883a0e-af47-459f-a6be-623849be6629.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: ee4600e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    C.R.I.T Expansion Mod [crt_expansion],
    Mining Mod [Mining_Mod]
]

**Comment by Joanakor** [comment]
Oh and sometimes this error occur when trying to pick up
![Uploading cataclysm-tiles_ivQBNWlGrs.png…]()

**Comment by LeahLuong** [comment]
Error message looks related to #54445.

**Comment by jeanpaulrsoucy** [comment]
I've noticed this too. If you instead try to pick up the item using advanced inventory management (`/`), you will receive the appropriate error message (e.g., no container to hold this item) rather than the silent failure you get using `g`.

**Comment by LeahLuong** [comment]
Rumor mill has it AIM is on its way out so it's important this issue is addressed before then.

**Comment by andrei8l** [comment]
This was fixed in #55136
![Screenshot from 2022-05-05 00-00-25](https://user-images.githubusercontent.com/68240139/166825186-2f382cff-2a6f-40a3-bd7c-c03132ff0b30.png)
