### ISSUE TITLE
Weather stuck in "Early Portal Storm" for multiple days

### ISSUE THREAD

**Issue by ccaviness** [CleverRaven/Cataclysm-DDA#54706]
### Describe the bug

The weather in my current save is stuck in "Early Portal Storm" for the last 2 or so days. This persists over full exit to desktop restart. I used the debug menu to set the weather to "Clear" and "Keep normal weather patterns"; neither one stayed, eventually the "Early Portal Storm" weather came back.

I examined the `master.gsav` file, and saw:
```json
"weather": { "lightning": false, "weather_id": "early_portal_storm", "next_weather": 6821172, "temperature": 62, "winddirection": 67, "windspeed": 7 }
```

Current time in game is day 79 22:45:02, which I think is game turn time `6821102`, just 70 seconds away. However, if I "wait until weather changes", over 24 hours pass with no weather change, still stuck on "Early Portal Storm". 

It's possible this is just a corrupt/broken save. See below.

### Steps to reproduce

Two or so in-game days previous, I had "Early Portal Storm" followed by a "Portal Storm", as expected. I got back in my vehicle to drive back to base to wait out the storm. While driving during the storm, I suddenly was attacked by something inside the vehicle, killing me with no warning despite safe mode enabled. I felt that was a bit unfair, so I force-quit the game. When I restarted, my vehicle was where it had been when I quit the game and some items had been duplicated.

The weird persistent "Early Portal Storm" weather has persisted since then, so it's possible there is just some weirdness/corruption in this save, and not an actual bug in the game.

### Expected behavior

Weather should not stay stuck in "Early Portal Storm" for multiple days/forever.

### Versions and configuration

- OS: macOS 12.2
- Game Version: 0-F.5519-gee4600e1e8
- Graphics Version: tiles
- Ingame Language: English
- Mods loaded: None

### Additional context

[Lindside.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7920936/Lindside.zip)

**Comment by ccaviness** [comment]
Possibly related to [issue](https://github.com/CleverRaven/Cataclysm-DDA/issues/52491).

**Comment by ccaviness** [comment]
If I change the `weather_id` in my `master.gsav`  to `clear`, the game starts up with Clear weather. But as soon as enough time passes for `next_weather`, the "Early Portal Storm" is announced and it stays that way even though I wait for a day.

I'm definitely not sure if `next_weather` timestamp is for normal weather changes or if it's specifically for Portal Storms?

**Comment by Ramza13** [comment]
So I will take a look at this.  However to end the storm what you can do is use the debug option Activate EOC(under game) then activate EOC_CANCEL_PORTAL_STORM

**Comment by ccaviness** [comment]
Thanks - I tried the `EOC_CANCEL_PORTAL_STORM` and it displayed the text that the storm was ending, but the weather stayed as "Early Portal Storm". I quit and restarted, but it was till there. I then did the cancel again, and then did "Keep normal weather patterns" again, and got clear. But when I waited another hour, it went back to "Early Portal Storm" again.

I'm not sure what all the data in the save files mean, but in the `#T3RoYSAnQ2FyYW1lbCcgQnJpbnNvbg==.sav` file I found this line: 
```
"queued_global_effect_on_conditions": [ { "time": 6828979, "eoc": "EOC_PORTAL_EARLY_MESSAGES" }, { "time": 6832059, "eoc": "ambient_subway" }, { "time": 6832096, "eoc": "ambient_lab_subway" }, { "time": 7034638, "eoc": "EOC_PORTAL_STORM_WARN_OR_CAUSE_RECURRING" } ],
```
Perhaps this is a problem? The time for `EOC_PORTAL_EARLY_MESSAGES` is, which is about 5 minutes from current in-game time. I'll try editing that out and see if it helps anything.

(N.B. as I mentioned it the initial description, I did force-quit the game a few in-game days ago after getting suddenly killed without any warning during a real portal storm, which may have caused some sort of save corruption.)

**Comment by ccaviness** [comment]
Removing `{ "time": 6828979, "eoc": "EOC_PORTAL_EARLY_MESSAGES" },` didn't work (though not sure if it was actually going to do anything). I loaded up, it was Clear weather, waited 5 minutes and got Early Portal Storm again.

¯\_(ツ)_/¯ maybe time to start a new character.

**Comment by Ramza13** [comment]
After more looking, run EOC_CAUSE_PORTAL_STORM instead.  It will make a full storm which you then should be able to cancel

**Comment by ccaviness** [comment]
This seems to have worked, thanks.

**Comment by ccaviness** [comment]
I haven't seen this recur.
