### ISSUE TITLE
Follower with splinted arms wields armor instead of knife

### ISSUE THREAD

**Issue by LeahLuong** [CleverRaven/Cataclysm-DDA#54712]
### Describe the bug

This is not a thread about a rat mutant having a bad time.

Splinting followers is currently problematic. The main issue I want to raise in this thread pertains to splinted arms. My follower had both arms broken & this caused them to drop their dory. Following splinting, they would wield a piece of their armor when detecting a hostile, usually their helmet, boots, or o-yoroi. I'm not sure what the condition is but they would subsequently drop the wielded item. It may be they detected another hostile & decided to switch to another blunt, it may be the game decided to do a check on whether they were actually capable of wielding an item. Either way, they were lagging behind & I missed seeing them dropping the item. I realized this was happening when the follower no longer had their helmet & I discovered their o-yoroi while backtracking. I tried giving them a trench knife because they were incapable of wielding their dory but it wasn't long before they dropped that in favor of their o-yoroi (which was a strictly worse weapon). This leads me to believe there is some sort of failing check process @ play.

Prior to posting I came across 2 related issues: #48911 & #49227. Both still exist in the latest stable.

In the former, a finished splint appears as just set. When you set a broken limb, it looks like this: =====. As it heals, each "=" is replaced by a "#" (e.g., a 40% healed limb looks like this: ##===). If a splinted limb takes damage, healing can lose progress & the splint can also be damaged. In all cases, when examining your follower's wounds, highlighting the broken limb gives the description that the limb has been set & needs time to heal, even when fully healed (which looks like this: =====). Unintuitively, you need to trade the splint away from them in order to complete the healing process. @ the very least, the UI should be corrected to show the limb as functional (#####) when it is & the description changed to tell the player the splint should be removed. Bandages disappear when used up & this creates an expectation the same will happen w/ a splint; I suggest this as a possible, better implementation for setting broken limbs.

In the 2nd issue linked above, splints are being duped. I believe this is because a new item is generated but the old item isn't deleted. Arm splints become either a left or right variant upon application. You can see this is the case when the splint is removed; "arm splint (right)" will no longer be able to rejoin a stack of arm splints.

Furthermore, I believe removal of a splint triggers the bug pasted below. After discovering #48911, I loaded my game to check if my follower's limbs had actually healed. I'd been a couple of in-game weeks monitoring the setting process but it looked like it had bugged out by getting stuck @ the "just set" stage. I loaded the game, traded the splints away, disinfected & bandaged both arms, dropped the used splints on a garbage pile, & saved & quitted; it was bedtime IRL & I wanted to check this 1 thing before hitting the hay. Game threw the error during save & quit then made it to the main menu. I reloaded, saw the game had retained what I'd just done, & saved & quitted w/out repetition of the error.

There is also an issue in recent memory where crafting can be started but not continued after pausing due to being unable to wield the in-progress item thanks to splinted arms.

Splinting was added quite early in this game's history & hasn't been meddled w/ much since. I think it's time to revisit this mechanic considering the issues I've raised here. It can prob wait until after the general limb overhaul but maybe it shouldn't.

### Steps to reproduce

1. Break your friend's arms.
2. Tie sticks to them.
3. ???
4. PROFIT!

### Expected behavior

I expected that arm splint (left) level would increase, because all other skills can increase in level.

### Versions and configuration

Android 0.F-3 Tiles English vanilla

### Additional context

 DEBUG    : item_location lost its target item during a save/load cycle

 FUNCTION : void item_location::impl::ensure_unpacked() const
 FILE     : /var/lib/jenkins/workspace/Cataclysm-Android/android/app/jni/src/../../../../src/item_location.cpp
 LINE     : 114
 VERSION  : 0.F-3

**Comment by Leland** [comment]
My attempt at summarizing your issue:

0. Follower breaks both arms. OP splints both arms.
1. Unequipped, splinted follower detects enemies.
2. Lacking a weapon, follower wields a piece of armor (e.g helmet) instead.
3. The wielded piece of armor is dropped at some point. (_I'm not clear why – are you @LeahLuong? Is this expected?_)
4. OP gives them a trench knife to use. Follower stubbornly switches to armor instead.

Everything except for maybe #3 makes this look like an issue with the follower _weapon selection logic_ – and not splints.

----

> This is not a thread about a rat mutant having a bad time.

Sorry to ruin your excellent pun! I changed your issue title because I wanted to make this one searchable under terms like "follower"

> I believe removal of a splint triggers the bug pasted below

Can you please separate this into a new issue, please? :smile: We generally try to keep to 1 bug per issue so that discussion is relatively easy.

----

Finally, any chance you have a save file?

**Comment by LeahLuong** [comment]
I posted a save in #54602 where Shawnna still has her splints on. It's in the Tacoma Commune parking lot so you'd prob need to go somewhere else to test how she keeps dropping stuff.

To be clear: Shawnna _dropped_ the trench knife to switch to her o-yoroi. I later picked it back up while tromping around the lab I was exploring w/ her in tow. IDK why she does this & I'm not even sure the player can wield items w/ 2 broken arms. This makes me think there is only a post facto check for it instead of a priori; check happens, game makes her drop, she wields something else, ad infinitum. I think wielding occurs when she detects a hostile, e.g., walking past the containment cell of a brute. Not sure what would cause a check & it seemed intermittent so it may be frustrating to reproduce.

The bug following splint removal is minor & I can't really be bothered to open a new issue. Not even sure it's connected but you can test it if you want in the save provided; I believe her arms have set & you can trade her splints away. Hopefully, if splints are reworked in the way I suggested above, the bug becomes superfluous.

FWIW, I believe searching scans a thread's contents, not just its title. I've been able to dig up past issues by using keywords found only inside.
