### ISSUE TITLE
Aluminum in scrap bronze recipe

### ISSUE THREAD

**Issue by ashGlaw** [CleverRaven/Cataclysm-DDA#54718]
### Describe the bug

Looking at the recipe for Scrap Bronze it seems the tin component can be replaced with aluminum, aluminum foil, and drink cans. That's very silly, as bronze is copper and tin, not aluminum. I mean, apparently "Aluminum Bronze" is a thing, useful for corrosion resistance, but that's not what the recipe is making.

### Steps to reproduce

It's right there in the recipe, lines 81-84 in materials.json, under the recipes folder. See the attached screenshot

### Expected behavior

I would expect tin or tin powder to be necessary for making bronze, and for aluminum to mind its own business

### Screenshots

![Scrap Bronze Recipe](https://user-images.githubusercontent.com/58862150/150704365-decbe1af-a4a1-41bb-8a15-4055c27d164d.png)

### Versions and configuration

N/A

### Additional context

This should be a **very** quick and simple fix

**Comment by Alex-Folts** [comment]
Aluminium bronze is a thing, [there is no reliable sources for tin in decent quantities](https://github.com/CleverRaven/Cataclysm-DDA/issues/54215#issuecomment-1008348761). 

So the options is: 
- craft aluminium bronze, 
- introduce magic sources of tin for crafting tin bronze(or make recipes use few grams of tin per 1 kg of bronze), 
- no craftable bronze at all.

**Comment by kevingranade** [comment]
You can make bronze, you can make Aluminum Bronze, for all purposes in game they're identical, so we call them the same thing.
Historically Copper/Tin bronze was dominant because tin was easier to acquire, in the modern world aluminum is pretty much everywhere, so it's reversed.
This is in contrast to "lead bronze" which is actually copper/tin/lead.
