### ISSUE TITLE
De-prioritize melee information for items that aren't meant as melee weapons

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#54710]
### Is your feature request related to a problem? Please describe.

When viewing the description info for an item, the "Melee damage", "Techniques when wielded", and "Average melee damage" sections are listed at the top for all kinds of items that aren't meant to be used as a melee weapon (such as an M4 rifle, army helmet, or a gallon of bleach).

Item descriptions are so lengthy, it would be better to prioritize the relevant info for the item, before showing the details of weird edge cases like bashing enemies with a gallon of bleach or the butt of your rifle.

### Solution you would like.

For items that are not weapons or tools, move the "Melee damage", "Techniques when wielded", and "Average melee damage" sections to further down in the item descriptions.

The relevant functions and their ordering is mostly in `src/item.cpp`; the melee stuff in question is from `item::combat_info`, invoked here from `item::info`:

https://github.com/CleverRaven/Cataclysm-DDA/blob/ee4600e1e837b8ed0f6c0d0351527142b476809c/src/item.cpp#L5195-L5202

A more intelligent reordering of `*_info` calls in this function could solve this issue.

### Additional context

M4 carbine showing its melee damage before its ranged damage:

![image](https://user-images.githubusercontent.com/238395/150695971-6fc08a0b-e1f1-406b-99be-383b6ead73a9.png)

Army helmet showing 14 lines of melee info before telling you `Covers: The head`:

![image](https://user-images.githubusercontent.com/238395/150695991-6652e92f-7071-45ef-a917-599b7df6830d.png)

Gallon jug of ammonia, making sure you know the critical hit chance well before knowing its total capacity:

![image](https://user-images.githubusercontent.com/238395/150695977-f7d9b3c7-2bb7-4518-84f0-084a5e7e555f.png)

And if I'm gonna attack someone with my knee pads, you better believe my knees will be in 'em when I do:

![image](https://user-images.githubusercontent.com/238395/150696054-0d2d4bd4-48f1-4bdc-bfee-6a1b029936c2.png)

**Comment by jeanpaulrsoucy** [comment]
Excellent suggestion!

**Comment by LeahLuong** [comment]
I generally agree but want to note that some guns do appear in the list of weapons compatible w/ Krav Maga. I usually want to know a gun's missile damage before mélée but CQC values are still quite relevant here.

**Comment by matshou** [comment]
This is one those issues that has always bothered you but you never thought too much about it until someone reported it.
