### ISSUE TITLE
Standing Mirror should let you see what they see at an angle

### ISSUE THREAD

**Issue by ElfLeaderMike** [CleverRaven/Cataclysm-DDA#54728]
### Is your feature request related to a problem? Please describe.

I moved a mirror in front of a window to let me keep an eye on the area, and to my great surprise I couldn't use the mirror as a mirror!

### Solution you would like.

The furniture piece "Standing Mirror" could function like a vehicle mirror to let you see what it sees, or more realistically, an angled view based on how you're looking at it.

### Additional context

It's not terribly important, its just more of an immersion/complexity thing that adds another bit of detail to CDDA. Like a player being tripped up bad in a clothing store because the mirrors make it near impossible to actually hide from vision.

**Comment by LeahLuong** [comment]
Would be nice but I think there's a lot of hidden complexity here. Wing mirror code might be useful but it's not 2-way; NPC's can't detect the player thru them. Also, IRL, there's a certain intelligence threshold to be overcome; many animals are too stupid to realize reflections correspond to reality. This would prob require a flag that would or wouldn't need to be applied for every entity to determine if they can use mirrors effectively.

**Comment by sulyi** [comment]
Creating 'reflection' using
```c++
void map::build_seen_cache( const tripoint &origin, const int target_z )
```
should be relatively easy.
Making logic (with good performance) deciding when to add position of the mirror to `seen_cache` is a different story.
It'd probably involve adding a new furniture (and terrain) flag.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
