### ISSUE TITLE
Activating & Deactivating Power Armor suits doesnt update encumbrance

### ISSUE THREAD

**Issue by John-Candlebury** [CleverRaven/Cataclysm-DDA#54722]
### Describe the bug

Activating & Deactivating Power Armor suits doesn't update encumbrance. This can let you fight using unpowered Field Combat exoskeletons, without facing any of the supposed encumbrance penalties.

### Steps to reproduce

1. Spawn a Heavy Field Combat Exoskeleton, UPS, and a spork. Wear the suit and wield the spork.
2. Notice you have the correct 60 encumbrance value.
3. Activate the suit, check the @ menu and notice an incorrect 60 encumbrance value.
4. Drop your spork, This causes encumbrance to update to the correct value of 20 after waiting one turn.
5. Deactivate the suit. Encumbrance remains at 20 until you grab the spork again.
6. Magic sporks?

### Expected behavior

The item transformation should trigger an encumbrance update.

### Versions and configuration

-Version: Latest Master
-Mods: DDA

### Additional context

Found while testing #53254 but as mentioned the bug is also present in vanilla objects.

**Comment by Nerezza** [comment]
Noticed this issue too, but I wasn't able to get to where I could regularly use my power armor to really be able to investigate it.

Relevantly the way power armor works is it's two different objects that swap json stats when you turn them on/off. The function handling the stat swapping probably needs to check if the item is worn, and call for an encumbrance refresh if it is.

**Comment by John-Candlebury** [comment]
Normal transformable armor does update correctly. I think the issue is found in the hardcoded encumbrance reduction Power Armors are supposed to get. Found  in line 803 of character_attire.

```
        const int armorenc = !power_armor || !it.is_power_armor() ?
                             encumber_val : encumber_val;
```
Removing this and updating the armors definitions to explicitly state the encumbrance reduction causes them to work properly.

I'd fix it but it might be worthwile for someone more knowledgeable to look at it.

**Comment by kevingranade** [comment]
That sounds totally reasonable.

**Comment by Broken27** [comment]
Honestly i think power armors should work with a normal transform function instead of being hardcoded.

It would make much easier to change the properties of the activated armor. (Like giving them an strenght buff, or giving activated power helmets  night vision).
