### ISSUE TITLE
"Car crash" scenario started in a house, with no cars.

### ISSUE THREAD

**Issue by moxian** [CleverRaven/Cataclysm-DDA#54731]
### Describe the bug

Started a new game in Car Crash scenario; spawned in a house. (But with limbs properly damaged)

Save: [Mukilteo-carcrash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7924272/Mukilteo-carcrash.zip)

### Steps to reproduce

n/a

### Expected behavior

Starting on the road, in a car.

### Screenshots

![20220124-092856-cataclysm-tiles](https://user-images.githubusercontent.com/7831163/150756635-87b5deca-5a8d-4be4-93bc-8bc6119bdd57.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 5ac1a12 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by LeahLuong** [comment]
I've seen Z's get knocked into buildings when I hit them in my vehicle. 1 time, an incandescent husk corpse ended up on the other side of a bank window from me w/out breaking the window. The eldritch power is strong w/ motorized vehicles.

**Comment by coyo7e** [comment]
> I've seen Z's get knocked into buildings when I hit them in my vehicle. 1 time, an incandescent husk corpse ended up on the other side of a bank window from me w/out breaking the window. The eldritch power is strong w/ motorized vehicles.

Please stay on topic

**Comment by Termineitor244** [comment]
/confirmed

![imagen](https://user-images.githubusercontent.com/53200489/166808424-7d8da2bd-4f0d-4e12-86fb-fc1c8f043abc.png)

The game spawned me in a metro station, no car on sight.
```

- OS: Windows
    - OS Version: 10.0.19044.1645 (21H2)
- Game Version: 8acdd5f [64-bit]
- Graphics Version: Tiles
- Game Language: Idioma del sistema []
- Mods loaded: [
    Futuros Días Oscuros [dda],
    Necesidades PNJ Desactivadas [no_npc_food],
    Profesiones Biónicas [package_bionic_professions],
    SpeedyDex [speedydex],
    Atributos a Través de las Muertes [stats_through_kills],
    Sin Crecimiento Fúngico [no_fungal_growth],
    Translate Complex Dialogue [translate_dialogue]
]

```

**Comment by XygenSS** [comment]
The scenario only places you correctly inside a vehicle if and only if the `road mayhem` map special is generated in the middle of nowhere with no other buildings around.

If there is a roofed building near the road mayhem you will be placed there.

Seems to be an issue with how the game decides where to place you.

**Comment by LyleSY** [comment]
Okay, I've learned some things trying to work on this. My current thinking for a fix is that a new map special is needed copying from road that has a spawn zone and that is tied to the Car Crash sloc and scenario. Ideally it should be outside of the city so it doesn't mess up any city spawns, which are necessarily very dense and almost all of them don't have a spawn zone designated yet. I'll try and get that together when I have time.
