### ISSUE TITLE
Let Rubik keep credit like Robofac

### ISSUE THREAD

**Issue by waxcatape** [CleverRaven/Cataclysm-DDA#54734]
### Is your feature request related to a problem? Please describe.

Installing CBMs with Rubik can sometimes be frustrating on account of having to barter something of the exact commensurate value in return.

### Solution you would like.

It would be a whole lot less annoying if you could, for example, trade an M4A1, which would give you enough credit to install 6-7 bionics (assuming the barter value of 120$ to 140$).

### Describe alternatives you have considered.

1) Implementing installing multiple bionics at the same time, but I assume it would be much harder to do,
2) Leaving things as is.

**Comment by RenechCDDA** [comment]
I cannot find a commit for when this was solved, but Rubik currently (b9c5366) works on a credit/debit system and prior credits will apply to CBM installation.
