### ISSUE TITLE
Loot zone for Containers accepts IFAK pouches and MRE packages as empty containers

### ISSUE THREAD

**Issue by Joanakor** [CleverRaven/Cataclysm-DDA#54737]
### Describe the bug

Trying to sort items from Unsorted zone results in IFAK pouch and MRE package being sorted to Containers zone while in Zone Manager it is said that this zone is only for **empty** containers.

### Steps to reproduce

1 .Create Containers zone
2. Obtain IFAK pouch or MRE package and try to sort it from Unsorted zone

### Expected behavior

IFAK pouch should be sorting to Drugs zone and MRE package to Food Zone.

### Screenshots

![cataclysm-tiles_4CmZZujc7y](https://user-images.githubusercontent.com/30211338/150819915-f4ee4083-8318-4215-82a8-18aae4be9eda.png)
![cataclysm-tiles_0ILYoj1b5T](https://user-images.githubusercontent.com/30211338/150819918-187e8928-eae6-4aa3-b244-6f46c0040cc1.png)
![cataclysm-tiles_8Bk8BRGPoS](https://user-images.githubusercontent.com/30211338/150819920-bca6c1fa-a9c4-4cda-9cad-8d49e6e20272.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 8f56778 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    C.R.I.T Expansion Mod [crt_expansion],
    Mining Mod [Mining_Mod]
]

### Additional context

Medkits while being a container are sorted just fine.
![cataclysm-tiles_KwWvtOYr40](https://user-images.githubusercontent.com/30211338/150820115-aa734d06-1149-4996-af2a-f77034ad5edc.png)
![cataclysm-tiles_ZeGgjReDkk](https://user-images.githubusercontent.com/30211338/150820120-f4889b42-dfe7-41ea-ae43-eeeeac94bfab.png)

**Comment by waxcatape** [comment]
It actually looks like any container that contains more than one kind of thing gets sent to a container loot zone.

**Comment by coyo7e** [comment]
Container logic is super busted right now, and unless a player understands the deep dive to autopickup and whitelist/blacklist, this is a huge pita. I constantly have rando tool. belts or pairs of jeans etc, inside my backpack, fill up with random items and it's really annoying.

Sheaths also no longer accept items like swiss army knives or multi tools, which I have a hunch is related to whatever is being tweaked for container code.
