### ISSUE TITLE
Crash on certain conditions

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#54739]
### Describe the bug

For some reason using minimuke cause a crash in some situations

### Steps to reproduce

- Open a branch with #54711
- Find an aircraft carrier map (atm spawns on a rivers, giant red `A`) 
- Find a reactor room on the -1 floor 
- Put and activate a mininike (only mininuke work, any another explosion work as intended) inside it
- Take a billion of errors:
```
DEBUG    : Setting terrain t_open_air at (67,82,-5) where furniture is f_rubble.  Terrain is_open_air
If this is intentional, set the ALLOW_ON_OPEN_AIR flag on the furniture
```
- After this the game crashes
the bug works only if bomb is in the very center of reactor (i think the reason is in such layered, onion-like pattern of this part of map)

### Expected behavior

Not having a crash

### Screenshots

reactor room
![image](https://user-images.githubusercontent.com/67688115/150825444-cdd5ab05-db55-4a4f-9f7a-89dddc8a38d5.png)
the crash
![image](https://user-images.githubusercontent.com/67688115/150825488-38556ff6-fd06-4d42-9ded-13d4289c60eb.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 51814ea [32-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

crash log
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7927227/crash.log)

**Comment by SariusSkelrets** [comment]
My guess is that the nuke tries to spawn rubble in open air and the game won't let it do that and crashes instead

A possible fix would be finding the code responsible for the rubble spawn and stop it from attempting to rubble-ify open air

**Comment by NetSysFire** [comment]
This alone should not crash the game though, see #54092

**Comment by GuardianDll** [comment]
Yep, no errors at all
