### ISSUE TITLE
"You mutilate the zombie soldier but do no damage"

### ISSUE THREAD

**Issue by Izicata** [CleverRaven/Cataclysm-DDA#5473]
I'm using a combat knife with no skill vs zombie soldiers, and I keep getting lines like "You gut the zombie soldier but do no damage" or "You mutilate the zombie soldier for 1 damage."

Doing no damage can't really be called mutilation, can it? There's lines for when ranged weaponry does no damage, but there doesn't seem to be any for when melee weaponry does very low damage or no damage at all.
##

**Comment by John-Candlebury** [comment]
It seems like this has been fixed sometime in the past two years
