### ISSUE TITLE
Items in trash cans should not be owned by a faction.

### ISSUE THREAD

**Issue by haveric** [CleverRaven/Cataclysm-DDA#54745]
### Is your feature request related to a problem? Please describe.

Walking around the refugee center, all of the items in the trash cans are still owned by the Free Merchants. Since they threw it away, I would expect the trash items to no longer be owned by them and be possible to take without stealing. This probably occurs in other faction related buildings as well.

### Solution you would like.

Remove ownership of items in trash cans in faction specific buildings.

Proposed implementation (for the refugee center) would be replacing:
```
    "object": {
      "faction_owner": [
        { "id": "free_merchants", "x": [ 0, 23 ], "y": [ 0, 23 ] },
        { "id": "free_merchants", "x": [ 24, 47 ], "y": [ 0, 23 ] },
        { "id": "free_merchants", "x": [ 48, 71 ], "y": [ 0, 23 ] },
        { "id": "free_merchants", "x": [ 72, 95 ], "y": [ 0, 23 ] },
        { "id": "free_merchants", "x": [ 96, 119 ], "y": [ 0, 23 ] }
      ],
      "fill_ter": "t_floor",
```
with
```
    "object": {
      "faction": "free_merchants",
      "fill_ter": "t_floor",
```

And then instead of having `jmapgen_faction` run at the end, the default faction would get passed through to all of the other mapgen, allowing them to override if needed. Some of the override functionality is added here: https://github.com/CleverRaven/Cataclysm-DDA/pull/56110

### Describe alternatives you have considered.

Leave it as is.

**Comment by LeahLuong** [comment]
It's not like garbage items are hard to come by elsewhere . . .

**Comment by NetSysFire** [comment]
That does not invalidate the issue.

In the Cataclysm I would imagine folks do more recycling or at least burn their trash for fuel though.

**Comment by haveric** [comment]
> It's not like garbage items are hard to come by elsewhere . . .

No, but sometimes you need that one item that happens to be in someone's garbage. Or perhaps you started a run near the refugee camp and don't have those "garbage" items yet. There's always other ways to acquire items; this could just be another one.

> In the Cataclysm I would imagine folks do more recycling or at least burn their trash for fuel though.

This feels like something they would have setup elsewhere for specific recycling of materials, perhaps even something that could be added down the road through quests?

**Comment by NetSysFire** [comment]
I would say the refugee center in general is very underprepared, so they would not have this. I think the lore for that it is a bunch of office employees being brought there in a bus. They do not have any outstanding survivalist skills, they are ordinary civilians who maybe do not even think about reusing their trash, so it would be fine by me to make the trash unowned but there is the complexity and actual implementation.

I have no idea how ownership is managed currently and it might be difficult to exempt something.

**Comment by haveric** [comment]
> I would say the refugee center in general is very underprepared, so they would not have this

I would somewhat agree with this. I know they supposedly have a whole vault setup underground with more functionality (lore-wise at least), but the above area is pretty limited. I'm also not sure how useful it would be to the player to assist them in constructing one vs the other planned expansion features (defenses, farming, etc.)

> I have no idea how ownership is managed currently and it might be difficult to exempt something.

My assumption is that ownership is applied generally to the whole region/map, but figured this would be something worth exploring. If someone can point me in the right direction of how ownership gets applied, I'd love to poke around the code a bit.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
