### ISSUE TITLE
Digital device length increases to fit scanned books

### ISSUE THREAD

**Issue by CalKerethi** [CleverRaven/Cataclysm-DDA#54743]
### Describe the bug

When a new book with a set length is scanned into a smartphone or e-ink tablet, the device's length will increase to that of the new book if it's longer. The effect isn't as noticeable with tablets since they're already 25cm long. No other measurements (volume/weight) seem to be affected.

### Steps to reproduce

1. Spawn a new smartphone and check its dimensions: 0.10 L, 0.23 kg, 5cm
2. Spawn a copy of 'Uniform Boy', a 20cm-long book. Skim it if it hasn't been identified yet.
3. Scan the book and check the phone's dimensions again: 0.10 L, 0.23 kg, 20 cm

The same effect can be tested with an e-ink tablet if you use one of the really big books like 'Legendary Bike Rides' (27cm).

### Expected behavior

The phone should remain 5cm long no matter how much data it's holding.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 8f56778 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

I realized after I posted this that the length is weird, since modern smartphones are more like 13-15cm longest side, but that's outside the scope of this particular bug.

**Comment by GuardianDll** [comment]
confirmed
phone before the scanning
![image](https://user-images.githubusercontent.com/67688115/150868487-258403f7-7872-4376-b49a-3a4d87137fdb.png)
and after
![image](https://user-images.githubusercontent.com/67688115/150868612-05e3d21e-9f05-4019-bdf8-8e1733b4d45e.png)
