### ISSUE TITLE
[Magiclysm] Enchanted weapons are not valid for Martial Arts

### ISSUE THREAD

**Issue by a-difabio** [CleverRaven/Cataclysm-DDA#54744]
### Describe the bug

As can be seen from the log, in the attached screenshot, the +1 version of the warhammer doesn't work with the Barbaran Montante martial art, while the unenchanted warhammer is a valid martial art weapon.
I assume there is the same problem also for the other enchanted weapons.

### Steps to reproduce

Learn Barbaran Montante martial art
Equip Warhammer +1

### Expected behavior

I expected that enchanted version of a weapon would be valid for the same martial arts as the base weapon.

### Screenshots

![image](https://user-images.githubusercontent.com/93767902/150839967-2c9fcbbb-8089-41bf-bb3e-8636d85c84d4.png)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 017f471 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Mythical Martial Arts [MMA],
    Magiclysm [magiclysm],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

**Comment by catdach** [comment]
This should be fixed once #51867 is finished. the only vanilla arts left are Barbaran Montante and the unarmed weapon arts. Barbaran Montante is one of the more complex arts in terms of categorizing the valid weapons for it, so I wanted to take the time to properly evaluate it. As for unarmed weapons...well that's its own can of worms, so they probably wont be done for a while 😅
