### ISSUE TITLE
Artisans' custom plated turrets become hostile to the player when attacked by monsters

### ISSUE THREAD

**Issue by waxcatape** [CleverRaven/Cataclysm-DDA#54752]
### Describe the bug

The custom plated turrets belonging to artisans start attacking the player if a third party attacks them.

### Steps to reproduce

1. Find the Artisans.
2. Find or spawn in monsters near the turrets.
3. Turrets become hostile to the player.

### Expected behavior

The turrets should only become aggressive to hostile monsters or whatever faction doing the actual attacking.

### Versions and configuration

- OS: Linux/NixOS 21.11
- Game Version: 017f471
- Graphics: Tiles
- Language: English
- Mods: dda, no_npc_needs, no_fungal_growth, speedydex

**Comment by NetSysFire** [comment]
This is more or less a known and more general issue. I swear I saw it reported already in the past but I can not find the issue I am looking for. Let us say you stumble upon a pack of dogs in the woods. A zombie emerges from the bushes. The dogs become hostile. Being hostile is currently a binary state so either the critter is peaceful and will not attack you or it will attack everything.

**Comment by waxcatape** [comment]
I have noticed dogs doing this but I chalked it up to this simulating dogs becoming distrustful or defensive. The worst thing with the turrets is, even their own friendly fire triggers hostility, which I find hilarious.

**Comment by coyo7e** [comment]
I lured a bunch of zeds and a couple mosquitoes to the plated turrets and after killing everything else, they chose me as a hostile RIP new playthrough.

I didn't post it because I'm sick of having leah police my posts but yeah, this happens and sucks when it does.

**Comment by LeahLuong** [comment]
Since it looks like I've been appointed deputy in these parts (ironically, only by the person who's complaining about it), it seems I'd better weigh in.

@coyo7e I don't have a problem w/ your posting new issues. But I do see it as problematic when you post issues w/out searching 1st, when you hijack threads by bringing in feature requests only tangentially related, & when you deride contributors for not working fast or good enough.

Here, you've essentially come in and said, "Yeah, happened to me too. Sucks. Also, Leah sucks." This is after NetSysFire explained why the issue's happening. Ask yourself: is this advancing the progress of this game's development?? Would it be more helpful if every1 who's experienced this issue commented something along the same lines, adding no more nuance than the OP??

I mean, try not to take it personally because I'd level these concerns @ any1 doing these things. But you need to accept some accountability for your own behavior. I'm sure this isn't the 1st time you've heard something like this & @ some point you have to take a look @ yourself as the cause of this response.

**Comment by coyo7e** [comment]
@LeahLuong Please do not ping me. Your posts are unfriendly and unwelcome, and I'm sorry that this is even something I have to bring up because I assumed a normal person would move on.

**Comment by kevingranade** [comment]
@coyo7e you need to drop this, I've reviewed the recent issues where you both posted, and while @LeahLuong could stand to tone things down a little (https://github.com/CleverRaven/Cataclysm-DDA/issues/54684#issuecomment-1019413592 was a bit much, "consider posting in #54625", and leaving it at that would have been prefferable), you are the only one that seems to be *picking a fight*.
Bringing up things that happened in other issues is not ok.
Blaming your behavior on other people is not ok.
Namecalling (https://github.com/CleverRaven/Cataclysm-DDA/issues/54684#issuecomment-1019526865) is very much not ok.

**Comment by Bulletfang** [comment]
The forge borns from the Magiclysm mod also turn hostile when attacked by zeds.

**Comment by LeahLuong** [comment]
Since this "is more or less a known and more general issue," should this thread be moved into Discussions??

How difficult would implementing the solution in "Expected behavior" (above) be??

**Comment by KurzedMetal** [comment]
I got this issue today but with an extra condition to reproduce.
I've got inside the Artisan's house without problem, turrets weren't aggressive to me.

Then I lured a Shocker close to them, they shoot them down for me, **as soon as I stepped into the tile the Shocker corpse was, I got "Hostile detected" message**, I moved away of the tile, and they didn't shoot, I got over the tile again, same message, skipped a turn on and they shot me...

In my case, it seems the tile with the corpse of the Shocker is making the turret agro to me.

Leaving info here in case it helps to debug it:

Save: [02-26 World.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8171782/02-26.World.zip)

Just move one step to the right (to the tile with the corpse) to reproduce it.

Info:
- OS: Windows
    - OS Version: 10.0.19043.1526 (21H1)
- Game Version: 6cea46d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by LyleSY** [comment]
Excited to see this, this has been an issue for DinoMod forever. The way it works there is a goose or beaver or something will decide to attack a pack of sauropods, those will aggro, and then they'll all attack the player. It's interesting but it makes no sense

**Comment by I-am-Erk** [comment]
So, I think the "accessible and acceptable for stable" way to solve this would be to differentiate "aggro to everything", "aggro to monsters" and "aggro to characters" as separate states. That's a nice intermediate to being able to allow complex monsters to store aggro against particular factions and individuals, and in the meantime will solve the vast majority of cases of inappropriate aggro.

**Comment by LyleSY** [comment]
I think this may be closed now
