### ISSUE TITLE
They See Me Scrollin', They Hatin'

### ISSUE THREAD

**Issue by LeahLuong** [CleverRaven/Cataclysm-DDA#54756]
### Is your feature request related to a problem? Please describe.

Here's a screenshot of me asking a follower for an overview of the faction camp system:

![Screenshot_20220124-105038](https://user-images.githubusercontent.com/91638992/150885856-76f037f9-bcf9-4161-a915-9f69a3e9fad5.png)

As you can see, the text on the left is cut off @ the top. This happens anywhere there are too many chars to display in that box & there is currently no keybinding to scroll up. This means I simply cannot know what wisdom an NPC has to impart to me anytime they become too verbose. PageUp & PageDown work for the righthand box when there are too many options to choose from.

Similar issues crop up w/ the vehicle interface. "{" & "}" work to scroll 1 of the windows but the other scrolling buttons are seemingly dysfunctional. This means I sometimes cannot read all the reqs for interacting w/ vehicle parts or see all the parts on a given frame w/out leaving the interface.

On the "@" screen, the status effects window simply doesn't scroll; when there are more than 5 effects ongoing the highlighter falls off the bottom & I have to guess each status from its effects noted in the central description window. Status effects are not named centrally & this makes it difficult to know what they are sometimes. Is it pain or heat causing my char's slowdown?? Which body part is bandaged &/or disinfected?? Also, the bionics window header can be seen on screen but none of the systems listed below it. You can see screenshots of my "@" screen posted in #54602. Note how the status effects window pushes proficiencies off screen. Thankfully, proficiencies can be highlighted & are named in the central description box.

I believe this feature request deserves an accessibility tag & any concomitant priority coming w/ that as these are likely issues impacting people who have any degree of vision impairment. In my case, I play on my phone so I can't really make the font size smaller w/out sacrificing readability nor make the terminal size larger w/out exceeding my hardware's capabilities.

### Solution you would like.

1. Functional keybindings for each UI window that can be interacted w/.
2. Full window visibility when said keybindings are employed.

### Additional context

Android 0.F-3 Tiles English vanilla

**Comment by J-Fields** [comment]
Related: #50928

**Comment by coyo7e** [comment]
It's pretty weird that the only way to get to camp commands is by asking your NPCs for a tutorial.

**Comment by Elshad19** [comment]
I have this problem as well. I am a fellow mobile user. Beside all that, when creating new character, I can't see full text of description in Scenario tab. I don't how to fix this. Mobile build needs UI fix in my opinion and some additional keybinds to be able to scroll up and down. ![Screenshot_2022-01-25-14-25-06-948_com.cleverraven.cataclysmdda.jpg](https://user-images.githubusercontent.com/87479123/150959251-f7498035-e857-449c-837d-ec0423f39d48.jpg)

**Comment by LeahLuong** [comment]
"Enhancement/Feature" tag, please!

**Comment by wapcaplet** [comment]
This is definitely a bug.

**Comment by LeahLuong** [comment]
It was written as a bug report in #53803 where it barely got any attention & was prob due to get nuked by stalebot. I made it a feature request because it's less something that can be addressed by a targeted code snipe & more a general overhaul of UI scrolling mechanics.

**Comment by I-am-Erk** [comment]
How is this doing with the changes to dialogue UI?

**Comment by leemuar** [comment]
This looks doable. Im currently implementing mouse support in https://github.com/CleverRaven/Cataclysm-DDA/issues/58106, including mouse wheel scroll and drag-and-drop.

If I read [the docs](https://wiki.libsdl.org/SDL_TouchFingerEvent) right, it looks like touch scroll handling is is exactly like drag-and-drop I've added recently in https://github.com/CleverRaven/Cataclysm-DDA/pull/58654

**Comment by leemuar** [comment]
What I need is a complete list of all UI windows where touch scroll is needed ASAP (to solve this issue and advance 0.G release)

- [ ]  NPC dialogue window
- [ ] Character creation, scenario description
- [ ] Vehicle interface
- [ ] Character menu, effect list

Anything else to add?

**Comment by ZeroInternalReflection** [comment]
> Anything else to add?

I believe I addressed scrolling issues with the character creation scenario tab in #59209, and the dialogue window _should_ be resolved once #61447 gets implemented.  Next on my personal to-do list is probably the character creation description tab (Not yet on your list, but there are some examples for how it behaves at small screen sizes in #58302).
