### ISSUE TITLE
mx_spider having trouble spawning over forest (?)

### ISSUE THREAD

**Issue by k4gi** [CleverRaven/Cataclysm-DDA#54765]
### Describe the bug

 I got this error message when approaching a spider-infested forest tile. Seems to suggest a dandelion was in the way somehow?

DEBUG    : In update mapgen mx_spider on forest, setting terrain to t_dirt (from t_grass_dead) at (11,11) when furniture was f_dandelion.  Resolve this either by removing the terrain from this mapgen, adding suitable removal commands to the mapgen, or by adding a suitable flag to the innermost mapgen: either ERASE_ALL_BEFORE_PLACING_TERRAIN if you wish terrain to replace everything previously on the tile or ALLOW_TERRAIN_UNDER_OTHER_DATA if you wish the other items to be preserved

 FUNCTION : virtual void jmapgen_terrain::apply(const mapgendata&, const jmapgen_int&, const jmapgen_int&, const string&) const
 FILE     : src/mapgen.cpp
 LINE     : 2573
 VERSION  : 671245d

### Steps to reproduce

i haven't the faintest idea lol

### Expected behavior

i've never seen this error before, that i can remember, so I guess I'm expecting spiders to be able to trample dandelions as they please

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 671245d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

  16:16:39.715 ERROR : (error message will follow backtrace)
    #0
      (dbghelp: @0x7ff774e96a8f[cataclysm-tiles.exe+0x1e6a8f]), 
      (libbacktrace: debug_write_backtrace(std::ostream&)+0xa3@0x1401e6a8f),
      (libbacktrace: 0x1401e6a8f    [unknown src]:0    [unknown func]),
    #1
      (dbghelp: @0x7ff774e9786a[cataclysm-tiles.exe+0x1e786a]), 
      (libbacktrace: DebugLog(DebugLevel, DebugClass)+0x20e@0x1401e786a),
      (libbacktrace: 0x1401e786a    [unknown src]:0    [unknown func]),
    #2
      (dbghelp: @0x7ff774e988dc[cataclysm-tiles.exe+0x1e88dc]), 
      (libbacktrace: realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x1ac@0x1401e88dc),
      (libbacktrace: 0x1401e88dc    [unknown src]:0    [unknown func]),
    #3
      (dbghelp: @0x7ff775cea738[cataclysm-tiles.exe+0x103a738]), 
      (libbacktrace: jmapgen_terrain::apply(mapgendata const&, jmapgen_int const&, jmapgen_int const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const+0x3e8@0x14103a738),
      (libbacktrace: 0x14103a738    [unknown src]:0    [unknown func]),
    #4
      (dbghelp: @0x7ff775205b1f[cataclysm-tiles.exe+0x555b1f]), 
      (libbacktrace: jmapgen_objects::apply(mapgendata const&, mapgen_phase, point const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const+0x157@0x140555b1f),
      (libbacktrace: 0x140555b1f    [unknown src]:0    [unknown func]),
    #5
      (dbghelp: @0x7ff77520ae0b[cataclysm-tiles.exe+0x55ae0b]), 
      (libbacktrace: apply_mapgen_in_phases(mapgendata const&, std::vector<jmapgen_setmap, std::allocator<jmapgen_setmap> > const&, jmapgen_objects const&, point const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)+0xa1@0x14055ae0b),
      (libbacktrace: 0x14055ae0b    [unknown src]:0    [unknown func]),
    #6
      (dbghelp: @0x7ff775220b8b[cataclysm-tiles.exe+0x570b8b]), 
      (libbacktrace: update_mapgen_function_json::update_map(mapgendata const&, point const&, bool) const+0x97@0x140570b8b),
      (libbacktrace: 0x140570b8b    [unknown src]:0    [unknown func]),
    #7
      (dbghelp: @0x7ff7751db281[cataclysm-tiles.exe+0x52b281]), 
      (libbacktrace: MapExtras::apply_function(string_id<map_extra> const&, map&, coords::coord_point<tripoint, (coords::origin)1, (coords::scale)1> const&)+0x151@0x14052b281),
      (libbacktrace: 0x14052b281    [unknown src]:0    [unknown func]),
    #8
      (dbghelp: @0x7ff77522e99e[cataclysm-tiles.exe+0x57e99e]), 
      (libbacktrace: map::generate(tripoint const&, time_point const&)+0x452@0x14057e99e),
      (libbacktrace: 0x14057e99e    [unknown src]:0    [unknown func]),
    #9
      (dbghelp: @0x7ff7751cabe2[cataclysm-tiles.exe+0x51abe2]), 
      (libbacktrace: map::loadn(tripoint const&, bool, bool)+0x31e@0x14051abe2),
      (libbacktrace: 0x14051abe2    [unknown src]:0    [unknown func]),
    #10
      (dbghelp: @0x7ff7751cb444[cataclysm-tiles.exe+0x51b444]), 
      (libbacktrace: map::shift(point const&)+0x4f4@0x14051b444),
      (libbacktrace: 0x14051b444    [unknown src]:0    [unknown func]),
    #11
      (dbghelp: @0x7ff774f8cb15[cataclysm-tiles.exe+0x2dcb15]), 
      (libbacktrace: game::update_map(int&, int&, bool)+0x1a9@0x1402dcb15),
      (libbacktrace: 0x1402dcb15    [unknown src]:0    [unknown func]),
    #12
      (dbghelp: @0x7ff774f8d72b[cataclysm-tiles.exe+0x2dd72b]), 
      (libbacktrace: game::update_map(Character&, bool)+0x43@0x1402dd72b),
      (libbacktrace: 0x1402dd72b    [unknown src]:0    [unknown func]),
    #13
      (dbghelp: @0x7ff7751c04a3[cataclysm-tiles.exe+0x5104a3]), 
      (libbacktrace: map::displace_vehicle(vehicle&, tripoint const&, bool, std::set<int, std::less<int>, std::allocator<int> > const&)+0xaf1@0x1405104a3),
      (libbacktrace: 0x1405104a3    [unknown src]:0    [unknown func]),
    #14
      (dbghelp: @0x7ff7751c4da8[cataclysm-tiles.exe+0x514da8]), 
      (libbacktrace: map::move_vehicle(vehicle&, tripoint const&, tileray const&)+0xb90@0x140514da8),
      (libbacktrace: 0x140514da8    [unknown src]:0    [unknown func]),
    #15
      (dbghelp: @0x7ff775627fe2[cataclysm-tiles.exe+0x977fe2]), 
      (libbacktrace: vehicle::act_on_map()+0x75c@0x140977fe2),
      (libbacktrace: 0x140977fe2    [unknown src]:0    [unknown func]),
    #16
      (dbghelp: @0x7ff7751b9246[cataclysm-tiles.exe+0x509246]), 
      (libbacktrace: map::vehproceed(std::vector<wrapped_vehicle, std::allocator<wrapped_vehicle> >&)+0x8a@0x140509246),
      (libbacktrace: 0x140509246    [unknown src]:0    [unknown func]),
    #17
      (dbghelp: @0x7ff7751b9425[cataclysm-tiles.exe+0x509425]), 
      (libbacktrace: map::vehmove()+0x157@0x140509425),
      (libbacktrace: 0x140509425    [unknown src]:0    [unknown func]),
    #18
      (dbghelp: @0x7ff774eddc4d[cataclysm-tiles.exe+0x22dc4d]), 
      (libbacktrace: do_turn()+0xae1@0x14022dc4d),
      (libbacktrace: 0x14022dc4d    [unknown src]:0    [unknown func]),
    #19
      (dbghelp: @0x7ff7760bd720[cataclysm-tiles.exe+0x140d720]), 
      (libbacktrace: main+0x17db@0x14140d720),
      (libbacktrace: 0x14140d720    [unknown src]:0    [unknown func]),
    #20
      (dbghelp: @0x7ff774cb13c1[cataclysm-tiles.exe+0x13c1]), 
      (libbacktrace: _tmainCRTStartup+0x231@0x1400013c1),
      (libbacktrace: 0x1400013c1    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc11/gcc-11.2.0.build_/mingw-w64-v9.0.0/mingw-w64-crt/crt/crtexe.c:323    __tmainCRTStartup),
    #21
      (dbghelp: @0x7ff774cb14d6[cataclysm-tiles.exe+0x14d6]), 
      (libbacktrace: WinMainCRTStartup+0x16@0x1400014d6),
      (libbacktrace: 0x1400014d6    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc11/gcc-11.2.0.build_/mingw-w64-v9.0.0/mingw-w64-crt/crt/crtexe.c:178    WinMainCRTStartup),
    #22
      (dbghelp: BaseThreadInitThunk+0x14@0x7ff9602b7034[KERNEL32.DLL+0x17034]), 
      (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
      (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
    #23
      (dbghelp: RtlUserThreadStart+0x21@0x7ff960bc2651[ntdll.dll+0x52651]), 
      (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
      (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  Backtrace emission took 0 seconds.
  (continued from above) ERROR : src/mapgen.cpp:2573 [virtual void jmapgen_terrain::apply(const mapgendata&, const jmapgen_int&, const jmapgen_int&, const string&) const] In update mapgen mx_spider on forest, setting terrain to t_dirt (from t_grass_dead) at (11,11) when furniture was f_dandelion.  Resolve this either by removing the terrain from this mapgen, adding suitable removal commands to the mapgen, or by adding a suitable flag to the innermost mapgen: either ERASE_ALL_BEFORE_PLACING_TERRAIN if you wish terrain to replace everything previously on the tile or ALLOW_TERRAIN_UNDER_OTHER_DATA if you wish the other items to be preserved

**Comment by PatrikLundell** [comment]
This is new functionality, so it's not surprising the message hasn't been seen before. It's essentially an indication that someone should review the map gen of whatever was detected to have an issue (in this case the spider nest).

That someone should decide what to do when "furniture" is found on top of the terrain being modified, and I agree that if spiders trample the terrain, they should also trample the flora on top of it. I suspect ERASE_ALL... is the correct choice, as that should also get rid of flora in the disguise of items (e.g. mustard), but someone who understands the new flags in detail should make the decision.
