### ISSUE TITLE
Different merchants inventory keeps blowing up

### ISSUE THREAD

**Issue by waxcatape** [CleverRaven/Cataclysm-DDA#54776]
### Describe the bug

When trading with Robofac, Exodii and the Refugee Center, their stocks keep updating every time you initiate dialogue, provided that you have already traded with them in the past. Their inventory eventually grows to gargantuan proportions. The artisans seem unaffected, though I might not have triggered the bug with Cody for some weird reason, I'm not sure.

### Steps to reproduce

1. Find one of the following merchants: Rubik, the Intercom, Smokes.
2. Trade / do missions with them (bring anesthetic for Rubik, Return Field Data for the Intercom, Unknown Recipient for Smokes). I'm not 100% sure if missions matter.
3. Wait for the next restock.
4. Return to the merchant.
5. Start dialogue several times, confirm that the inventory keeps growing.

### Expected behavior

1. Shop restocking should take reasonable time.
2. Old inventory should disappear from time to time.

### Screenshots

Rubik's inventory, first state:
![Screenshot from 2022-01-25 22-43-09](https://user-images.githubusercontent.com/89343493/151048107-96c64f5f-1a2b-42d6-9511-e7241809f23d.png)

Rubik's inventory, after 2 more dialogue prompts (which is to say, I closed the dialogue window and talk to Rubik again twice):
![Screenshot from 2022-01-25 22-46-25](https://user-images.githubusercontent.com/89343493/151048620-57234503-12c8-4976-92d0-ec5577ee7653.png)

The Robofac Intercom (note the number of pages in the bottom left corner):
![Screenshot from 2022-01-25 22-53-23](https://user-images.githubusercontent.com/89343493/151049439-5d09809c-1a48-4a7c-9c63-c9db405f7755.png)

Smokes from the Refugee Center:
![Screenshot from 2022-01-25 22-54-53](https://user-images.githubusercontent.com/89343493/151049624-ecb83cc7-74c7-4460-9703-f77252dbbd39.png)

### Versions and configuration

- OS: Linux/NixOS 21.11
- Game Version: 04143c6
- Graphics: Tiles
- Language: English
- Mods: dda, no_npc_needs, no_fungal_growth, speedydex

### Additional context

I'm creating this issue despite the existence of #54407 because it seems like a more general issue and to prevent people from potentially looking in the wrong place for the cause of this bug. 

My own conjecture is that there's something wrong with the shop_restock function in npc.cpp, but I don't have the coding knowledge to confirm or fix it. 

Also, talking to Rubik after the first restock teleports you into a ledge and makes you fall (see #54695 ). Doesn't happen to other merchants.

**Comment by Nerezza** [comment]
I've been investigating https://github.com/CleverRaven/Cataclysm-DDA/issues/54407 and I've discovered that Rubik's problem is probably being caused by them being deleted by the game, and a new one spawning in with new CBMs.

Look underneath the merchants when you trigger stock bloat and see if they have dropped items underneath them, those would be the items left behind with the NPC is deleted and if they're there would mean that every NPC affected is being deleted and respawned for some reason.

**Comment by waxcatape** [comment]
This sounds plausible, as you trade with Rubik, the room gets full of wares. Also, I've noticed that when you get teledropped and escape the dialog window, if you are in the room, Rubik is actually not present until you pass a turn or do something that takes a game tick. The value difference is also there and it can actually get quite significant (e.g. combat knives can be anything from $17 to $24).

**Comment by Jan-Blasiak** [comment]
> I've been investigating #54407 and I've discovered that Rubik's problem is probably being caused by them being deleted by the game, and a new one spawning in with new CBMs.
> 
> Look underneath the merchants when you trigger stock bloat and see if they have dropped items underneath them, those would be the items left behind when the NPC is deleted and if they're there would mean that every NPC affected is being deleted and respawned for some reason.
> 
> Oh another sign is that the value of bought or sold items changes slightly when you open the trade interface. For some reason every few Rubiks values everything like 0.05% more than the others did.

OH! I think it may even relate to the mission bug! Sometimes active missions which were left for a few IG weeks become impossible to finish due to the fact that NPCs giving them seem to forget that the mission in question was issued, and they give it again.

**Comment by bombasticSlacks** [comment]
So Rubiks thing is a different can of worms.

For this unless you can show that it's explicitly talking to them in rapid succession which I can't recreate it. It seems like they just restock with WAY too many items. Since on restock the Hub merchant for example tries to stock 7500$ worth of items which depending on RNG can end up being upwards of 200+ items
