### ISSUE TITLE
World option: No starting NPC spawn

### ISSUE THREAD

**Issue by morthein** [CleverRaven/Cataclysm-DDA#54773]
### Is your feature request related to a problem? Please describe.

I think there should be a world option to override your starting scenario (such as the default survivor -> Evacuee) to make it so you do not start with a neutral NPC near you. There are some scenarios that have this as a condition and if I'm not mistaken, I thought this used to be an option once upon a time?

### Solution you would like.

It could be a simple toggle in the world gen options to ignore starting NPC generation.

### Describe alternatives you have considered.

Currently, I just avoid scenarios where there's someone else. I like all my NPCs to be random.

**Comment by Night-Pryanik** [comment]
This option actually existed for some time not so long ago (#24551), but eventually has been removed (#41858). I'm absolutely sure it won't be returned.

You can still disable starting NPC spawn by editing scenario json.

**Comment by morthein** [comment]
Oh, brilliant!   I added "LONE_START" to all my scenario flags so no more pesky starting NPC.  Thanks for the suggestion.  Since it was purposely removed, ill close this with this comment.
