### ISSUE TITLE
[Innawoods] Nails are uncraftable 

### ISSUE THREAD

**Issue by Paprika-H** [CleverRaven/Cataclysm-DDA#54782]
### Describe the bug

Nails require chunks of steel or scrap metal to be made, however when you craft lumps of steel it disassembles into iron ore, rendering scrap metal and chunks of steel unobtainable. 

### Steps to reproduce

1. Make lumps of steel
2. Get a hacksaw
3. Disassemble the lumps to get iron ore

### Expected behavior

I expect to get chunks of steel from disassembly of lumps of steel.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 6a794f1 [64-bit]
- Graphics Version: Tiles
- Game Language: Nederlands [nl]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Innawood [innawood],
    No Fungal Monsters [No_Fungi]
]

**Comment by NetSysFire** [comment]
cc @Light-Wave?

**Comment by Light-Wave** [comment]
This has worked before, so it is a fairly new issue.
Perhaps the iron refining recipe needs a "reversible": false
I'll look into it.

**Comment by Paprika-H** [comment]
> This has worked before, so it is a fairly new issue. Perhaps the iron refining recipe needs a "reversible": false I'll look into it.

Much appreciated!

**Comment by Light-Wave** [comment]
This happened due to #54606
The last steel to steel_lump recipe seems to confuse the game, making lumps not reversible. Looking into a fix now. A temporary fix would be to remove the last recipe that commit added.
