### ISSUE TITLE
vehicles colliding with "null part"

### ISSUE THREAD

**Issue by k4gi** [CleverRaven/Cataclysm-DDA#54796]
### Describe the bug

the pickup truck i just backed into had a frame destroyed, and it looks like since it's gone now the game didn't know how to describe what I ran into

i don't want to assume though

### Steps to reproduce

?

### Expected behavior

The Zoom Zoom Car's frame collides with the Pickup Truck's XX frame (destroyed)

or something

### Screenshots

![image](https://user-images.githubusercontent.com/26471575/151117167-d2666b8f-eeac-4b87-b3b6-8722b0f82327.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 51f7d93 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by jworkman01** [comment]
If this is actually a bug and is not the desired output, I can take a look into this as well.
