### ISSUE TITLE
Make more enchanted items "oversize" so they're wearable mutated

### ISSUE THREAD

**Issue by Naadn** [CleverRaven/Cataclysm-DDA#54804]
### Is your feature request related to a problem? Please describe.

Magiclysm have lots of DND inspired elements like spells and magical equipments and many of them are very hard to find even with forge of wonders. But when I using one of the mutation route provide by this mod, the black dragon mutation, many hard earned magical items will inevitably be destoryed because that route will restrict gear to pretty much all your body. But in DNDs, most magic item have power to resize themselve from huge giants to small halfings without any problem (even beholder can use rings in a weird way). I hope when playing with the hardest mutation to craft (due to how hard to kill a black dragon and the time consuming recipe to make a single dose of serum), people can keep using those rare magical items without any problems.

### Solution you would like.

- Add oversize flag to more enchanted gears like boots, rings, belts and bracers so they can used even with mutation.

### Describe alternatives you have considered.

Add even harder to find but mutation friendly version of those items.

**Comment by Leland** [comment]
Updated your title slightly so it's clear you want this for mutated purposes! 

> Add even harder to find but mutation friendly version of those items.

I don't personally run Magiclysm but my $0.02 is that this seems a pretty reasonable way to proceed.
