### ISSUE TITLE
crash in mod

### ISSUE THREAD

**Issue by dmklszhlb** [CleverRaven/Cataclysm-DDA#54805]
### Describe the bug

it will crash in my mod environment,When choosing characters, as soon as I choose my mod characters, the game will collapse.but items and mutations has no error, when I choose other professions,the game can be running,and items can be use too.(
Strangely,it can be normal running in this morning)
[舰娘mod v0.2.2 实验版.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7941747/mod.v0.2.2.zip)

### Steps to reproduce

1.There is no problem with the selection interface
2.But if I click, it will report a negligible error
3.Then there will be a point error
4.so I set it to unlimited, it'll crash when I start
5.But in another ordinary opening archive,it have no problem when I debugging everything in my mod

### Expected behavior

it really Strange(laugh

### Screenshots

I took a screenshot of these steps
[step.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7941784/step.zip)

### Versions and configuration

windows 10
1acfc7c
chinese
only my mod

### Additional context

[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7941796/config.zip)

**Comment by dmklszhlb** [comment]
I think I find why ,
"fatigue_modifier": 
"fatigue_regen_modifier":
these can't start as professions

**Comment by LeahLuong** [comment]
Good to know! Well, if it's working & the issue's resolved, you should close the thread.

**Comment by dmklszhlb** [comment]
> Good to know! Well, if it's working & the issue's resolved, you should close the thread.
sorry,I forget it. 
But I think The reason for this error that is something wrong with the game code?maybe 😂
thank U for your reply💕, I will close the thread immediately.😂
