### ISSUE TITLE
CBM pseudo item(s) count(!s) as a consumable crafting component and fails craft at 0%

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#54809]
### Describe the bug

The Intravenous Needletip CBM, or bio_syringe if you prefer, provides `"passive_pseudo_items": [ "syringe" ]`.  This is great, except for when you want to make something that uses a syringe as a component, such as the epinephrine autoinjector.  

You get a popup asking which syringe you want to use, as shown in the image below, even when you don't have one on your person.

### Steps to reproduce

Install Intravenous Needletip CBM
Get items and skills for a epinephrine autoinjector
Have all non-pseudo syringes needed not on your person
Attempt to rip out your bionic syringe
...
~~Profit?~~
Fail to finish the craft.

### Expected behavior

Pseudo don't get to be counted as consumable items for crafting, only as tools or tool qualities.

### Screenshots

![image](https://user-images.githubusercontent.com/22281606/151209973-8188bc01-164e-490d-84bb-7cb4e984e6d1.png)

### Versions and configuration

Win 10, tiles, e49949d

**Comment by LeahLuong** [comment]
This reminds me of #22789. Possibly related??
