### ISSUE TITLE
Swap on death does not work if all my followers are far away

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#54806]
### Describe the bug

#53606 introduced a new mechanic: if I die and I have follower NPCs in my faction, I can continue the game as one of the NPCs instead of a complete game over. C:DDA is going through a very welcome paradigm shift (see #53523).

Unfortunately this mechanic is broken - it does not work if my followers are too far away.

### Steps to reproduce

1. Use debug mind control to get a follower
2. Tell the follower to guard
3. Walk 10 overmap tiles away
4. Die (note: suicide currently never allows you to continue the game as a folower, to test this bug you'll have to die the slow and painful way)
5. See that the backup failed

### Expected behavior

I should be able to continue the game as a follower regardless of how far away the follower is

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: ef67fb9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by aivct** [comment]
It's strange, because in debug mode I can have a follower NPC in another map chunk ~50 overmap tiles away and I can switch perfectly (albeit with a lag spike that made me fear the game was going to crash). Haven't played switching on death though.

**Comment by hexagonrecursion** [comment]
The `{ "npc_allies": 1 }` test fails if there are no allies in the reality bubble. I have removed the test and was successfully able to switch character on death but now I get the prompt even if there are no alive allies to switch to.

https://github.com/CleverRaven/Cataclysm-DDA/blob/86fe522ddda2f5aba3efd619e5f8ff9f875dd2b3/data/json/effect_on_condition.json#L322-L328
