### ISSUE TITLE
NPC follower who agrees to follow, seems to ignore command "follow me" after set to guard

### ISSUE THREAD

**Issue by coyo7e** [CleverRaven/Cataclysm-DDA#54822]
### Describe the bug

I noticed this on a couple NPCs now, not sure if it's specific to the NPC or just because their wanted quest was not yet completed however, when you convince them to come with the player via a Social skill check, and then they get banged up (or are just bad in combat) and then they are asked to "follow me" after being set to guard, they ignore the "come with me" option, even after repeated attempts.

Unsure if this is related to their trust level or not however, it is annoying to set an NPC to guard a spot and then realize they won't come with me until I (assumedly) manage to complete their quest. Some quests take a lot of exploring and searching (such as the "relic" quest) so this can end with an NPC left behind accidentally, possibly in a dangerous area.

They seem to accept the order to come with player, but then continue to act in the same manner as a guard NPC and if you converse with them again, they will continue to refuse to leave the area or stop guarding.

Specifically for the instance I'm currently looking at, it's the NPC who asks the player to find a relic.

Even forcing a new social check would be helpful in this circumstance, and at least make the AI behavior seem more logical.

### Steps to reproduce

1. Spawn NPC.
2. Use Social check to convince them to travel with player.
3. Set NPC to guard.
4. Notice they will not re-follow player.

### Expected behavior

Expect a follower who chooses to come with the player, would also accept re-following the player when given the apropos command, regardless of trust levels etc.

### Screenshots

![image](https://user-images.githubusercontent.com/80022377/151242798-c19001e1-1265-4a9e-b856-bfdc34dd4afd.png)

![image](https://user-images.githubusercontent.com/80022377/151242849-fd9d91bf-9707-410d-8342-5c72bbc371e1.png)

![image](https://user-images.githubusercontent.com/80022377/151242893-bcb12ec4-4386-4fbc-8fdc-b451744ce577.png)

![image](https://user-images.githubusercontent.com/80022377/151242957-74d6a619-1423-4b82-9b16-29355d518aa0.png)

(NPC is set to "follow always" "within 4 squares" and does not do so)

![image](https://user-images.githubusercontent.com/80022377/151250008-c6527cdb-3659-44da-9938-4ba7c42ad566.png)

They also can be quite spammy and ignore commands like to not pick up items or use ranged/loud weapons, etc

![image](https://user-images.githubusercontent.com/80022377/151251186-0c949521-a060-41d5-8273-132a8ad9d390.png)

Within 1 or 2 minutes of gameplay, this NPC has literally picked up, sometimes wielded, and then dropped literally hundreds of items. Goodbye player log!

No zones have been declared, this NPC is just YOLOing around the garage I parked inside.

![image](https://user-images.githubusercontent.com/80022377/151251275-e1d700c5-aeca-4f11-8429-cb1408fa0bd6.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 8f56778 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

**Comment by LeahLuong** [comment]
I wonder if this is related to #36386. Do your followers show up as "Neutral" or "Friendly" when 'V'iewing nearby creatures?? Have you been savescumming??

**Comment by coyo7e** [comment]
> I wonder if this is related to #36386. Do your followers show up as "Neutral" or "Friendly" when 'V'iewing nearby creatures?? Have you been savescumming??

Good question. I will go and try to re-create it because this charfile has been savescummed once after a zombie child killed him while he was trying to drop a pile of items.

**Comment by coyo7e** [comment]
It does seem as though it may be related to savescummed charfile. at least with initial spawn and success, I was able to make an NPC re-follow after waiting a couple minutes before trying.

**Comment by Leland** [comment]
As an aside, I deeply appreciate how detailed your issue descriptions are! Since you've been going the extra mile, here are two more things that you can do in future filings if you feel so inclined:

- Attempt to reproduce on a world with no mods enabled (fewer variables for fixers to investigate!)
- Provide a savefile

Neither are required to file issues here, of course – and the detailed descriptions mean you're already doing more than 90% of what we see here.

**Comment by coyo7e** [comment]
I did reproduce this on a world with the same mods (I only ever use the enhanced overmap, stats to skills, speedydex, and stats through kills,) and without the character dying, I was able to successfully make the NPC stand to guard and then refollow. At that point I bow to previous occurrences which sound like they're probably the same thing and somehow related to data being deleted during savescumming - is there for instance an NPC "trust level" stat saved somewhere, which seems to be getting deleted when someone savescums? Seemed likely enough to let it lie at that point.

Thanks and take care!

**Comment by coyo7e** [comment]
Oh fwiw, this NPC is continuing their terribly-spammy behavior to the point it's become a chore to even move around inside the building near them. They're currently wearing a short rope, containing a short rope holding another short rope holding a canteen full of several random items, and constantly swapping between glocks. 

I'm about to just kill them to make the game less sluggish.
