### ISSUE TITLE
Add the ability for monsters and animals to "grow into" instead of having to use "upgrade into"

### ISSUE THREAD

**Issue by Paprika-H** [CleverRaven/Cataclysm-DDA#54821]
### Is your feature request related to a problem? Please describe.

I'm annoyed when I play with a high evolution multiplier and it makes farming of livestock so much harder, as baby animals take forever to grow up and produce useful stuff. Also it's weird that baby animals can just randomly grow up into their adult versions, whether it's been 1 day or 20.  

### Solution you would like.

Instead of having an "upgrades into", which is affected by the evolution timer, make stuff like baby animals "grow into"

**Comment by Venera3** [comment]
Baby animals universally use `age_grow`, though.

**Comment by Paprika-H** [comment]
> Baby animals universally use `age_grow`(e: which is not influenced by evolution timers or season lengths, for the record), though.

Welp, serves me right for not looking in deep enough :P
