### ISSUE TITLE
Pressing Numpad-0 seems to bring up "View Help" menu in odd contexts

### ISSUE THREAD

**Issue by coyo7e** [CleverRaven/Cataclysm-DDA#54828]
### Describe the bug

Came across this by accident, but if you begin to eat something or do some other actions (which I have not delved in-depth yet)which you can "pause," via various means or outside occurrences, it brings up the basic "View Help" menu if you hit a key that points to it.

I did rebind "pause" to "space bar" (because I often hits space bar and assume it pauses stuff) but that's the only thing I've mucked with that I can fathom could have caused it.

### Steps to reproduce

1. Begin to eat food.
2. Hit Numpad 0
3. Notice you are brought to "View Help" menu.

### Expected behavior

Assumed it would ignore invalid inputs, or give player feedback.

### Screenshots

![image](https://user-images.githubusercontent.com/80022377/151259934-512d1a60-902f-42df-87a7-a7593fe19d2e.png)
 
![image](https://user-images.githubusercontent.com/80022377/151259988-ff005702-0626-4983-96a5-8a44628d7127.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 8f56778 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

**Comment by chrispikula** [comment]
Check your key bindings to make sure you don't have any undefined key binds.  That is, say, for something like move left you should have `j or LEFT or 4`.  If you see, instead, ` or LEFT or 4', that is an undefined keybind that has anomalous triggering properties, as I discovered myself while using alt tab with such.

**Comment by Night-Pryanik** [comment]
Confirmed, but I see nothing wrong with this behavior. Numpad-0 is binded to show help by default. Showing help while consuming (or during any other activity) isn't a bug. You can also do some other things during long activities, for example, you can look at your character menu by pressing `@`. If you don't want to look at "unwanted" menus during activities, just don't press any unneeded keys.
As game ain't necessarily guaranteed to ignore "invalid" keypresses during activities, I'm closing this.
