### ISSUE TITLE
Chibi_Ultica Hooves Off-set and using ULTICA's Hooves.

### ISSUE THREAD

**Issue by LordBarkBread** [CleverRaven/Cataclysm-DDA#54832]
### Describe the bug

Chibi_Ultica's tileset config seems to be using ULTICA's Hooves "fg":.

### Steps to reproduce

1.Using Chibi_Ultica tileset mutate player with HOOVES
2.See as below, they are offset and using the wrong graphic
![hooves2](https://user-images.githubusercontent.com/97002254/151267036-11cbfbbe-1aa8-491e-bf47-356c002bb014.png)
 

### Expected behavior

Upon checking within the Chibi_Ultica Tile_config.json
Editing the .json  { "id": "overlay_female_mutation_HOOVES", "fg": 5294 },
                            { "id": "overlay_male_mutation_HOOVES", "fg": 5295 }
Which are incorrect placement.
Should read instead to.
                            { "id": "overlay_female_mutation_HOOVES", "fg": 371 },
                            { "id": "overlay_male_mutation_HOOVES", "fg": 371 }
![hooves1](https://user-images.githubusercontent.com/97002254/151267445-def7f101-a3b9-4770-b495-0d84f952a1f4.png)
,

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 5662136 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Autodoc Harmless and Perfect [autodoc_harmless_perfect]
]

### Additional context

Just as a sidenote I've only used git once so I hope this was helpful enough, all that needs to be edited into the file is.
 
                           { "id": "overlay_female_mutation_HOOVES", "fg": 371 },
                            { "id": "overlay_male_mutation_HOOVES", "fg": 371 }

**Comment by LeahLuong** [comment]
You already brought this up in #53982 but it's good you've done some code diving since. Next time, append a new comment to your previous post rather than open a new issue.
