### ISSUE TITLE
Lightstrips do nothing but delete batteries

### ISSUE THREAD

**Issue by ChucklesTheBeard** [CleverRaven/Cataclysm-DDA#54831]
### Describe the bug

Lightstrips used to be a long-lasting but un-toggleable light source for reading at night.

Right now, they seem to instantly run out of charge, delete batteries, and revert to "lightstrip (inactive)" when activated.

### Steps to reproduce

1. Obtain lightstrip & light battery.
2. Reload lightstrip with battery.
3. Activate lightstrip.

### Expected behavior

"You irreversibly activate the lightstrip."

"lightstrip (inactive)" turns into "lightstrip (active)", providing a small but un-toggle-able light source and slowly draining the attached battery.

### Screenshots

https://www.twitch.tv/videos/1276924772?t=02h54m10s

### Versions and configuration

Report taken from a stream, I don't have this in the debug menu's format, sorry.

Game version 9dbadbd

Mod list:
Dark Days Ahead
Disable NPC Needs
No Fungal Growth
Bionic Professions
Aftershock

### Additional context

also reported on Reddit - https://old.reddit.com/r/cataclysmdda/comments/sbtt05/lightstrips_dont_work_at_all/

**Comment by coyo7e** [comment]
Is this a dupe, or is another person bringing it up? Lightstrips should not last that long in any case since they are just raw-dogging to a battery which ought to burn them out within moments, if not a couple minutes. That is the entire point of breadboards and resistors, etc.

Ignoring basic electronics theory is not the way to make light sources which have no negatives to actually learning the skill and making a flashlight or lamp, etc.

**Comment by moxian** [comment]
Lightstrips are not even craftable anymore.
I think the better way would be to completely remove them, and replace with light bulbs.

The only way to obtain lightstrips currently is by deconstructing flashlights anyway, and the only reason we are getting those, and not flashbulbs is a technicality of the components ordering in the recipe.

One can argue that it'd be nice to have a low-brightness night reading light recipe (out of a light bulb and some random hand-wavy electronic parts (treat them as appropriate resistors if you will)) "as a replacement", but given the existence of this bug, it'd be more of a new addition technically (or "re-introduction" maybe).

**Comment by ChucklesTheBeard** [comment]
Hm, I wasn't expecting electronics rants. This issue is regarding a cut and dry bug report. If there's a balance issue of where lightstrips are sourced from, or if the description doesn't line up, that should really be addressed separately.

---

The negative for a lightstrip has always been the (rather silly imo) notion that you can't shut it off; it will, most definitely, use up a battery, and if you're spotted you must dispose of it to hide in the dark again instead of just toggling it inactive. Are individual components tracked in any other recipes? If not, does it really matter that much if a *car headlight LED assembly* or *the electronics of a flashlight, which itself takes a battery* gets plugged into a battery? Is it really that much of a stretch to suggest the survivor also used something so complicated as one resistor to bring the power draw & brightness down?

**Comment by chrispikula** [comment]
@coyo7e Any lightstrip you can buy tends to have in-built smd resistors for every two or three LED's on the strip, no worries about burning them out, just apply the proper voltage range.

**Comment by coyo7e** [comment]
"Any lightstrip you can buy" As in the ones you install onto a pickup as a "bully-bar" or something? Yes of course they have everything needed installed however, taking apart a lamp or flashlight doesn't end up with a lightstrip and all resistance etc already included - the PCB is usually obscure and falls flat off the item, which is why you cannot get a "breadboard" off any piece of electronics you take apart.

Most newer electronics also cut the leads off of everything that's soldered to a board, which means you cannot even re-use the parts unless you're really, really good at soldering and handling tiny bits of metal. I go out of my way to glean older electronics from the 70s-80s-90s IRL, largely because they were crafted by hand and that means you can disassemble them by hand and get usable parts from them. 

Go to the dollar store, buy a few electronic doohickies, and take them apart, tell me how many usable parts you come away with - not many! They're designed that way.

**Comment by chrispikula** [comment]
Er, I was under the impression that lightstrips in this game were specifically a lightstrip, that is, a technological divergence from the real-world usage of bulbs everywhere.  Has that changed?  And by lightstrip, I was initially thinking the ones that you can stick under your counter.  These things:
![image](https://user-images.githubusercontent.com/22281606/151450585-68d51f38-ec07-4ff1-b3b9-c74ac473a722.png)

Also, what would you buy today that is still monolithic through hole?  :-p  That stuff is bulky, and bulky=somewhere you can save money.  I remember back when I did salvage old tech, and anything hand soldered always bent the leads so you couldn't even take them off even after removing the solder.  Even with a solder pot, you couldn't reliably get em off without a decent chance of ripping a lead or two off an IC.

**Comment by coyo7e** [comment]
If they were that kind of thing, it wouldn't make sense to receive them from every flashlight.

**Comment by Zireael07** [comment]
@coyo7e: Yep, probably some confusion and/or holdover from the time when CDDA was supposed to be set in more of a future/sci-fi-ish world.

**Comment by chrispikula** [comment]
> And I'm sorry, but I honestly had no idea what "monolithic through hole" means however, 

It if has leads that go through holes in a pcb, it's monolithic.  If it's not, it's surface mount.  Surface mount components cost fractions of monolithic components.

Monolithic:
![image](https://user-images.githubusercontent.com/22281606/151554855-dab5aaa4-2458-4d98-9ac8-43845c5fc810.png)

Surface mount stuff with two via's for a monolithic component in the centre:
![image](https://user-images.githubusercontent.com/22281606/151555000-1b83a2cd-4282-4ae8-838a-795580db15ac.png)

**Comment by Maleclypse** [comment]
Has this been confirmed as a bug?

**Comment by ChucklesTheBeard** [comment]
It's happened to at least 2 people separately. I haven't confirmed it's
still present since seeing it happen live in the linked stream.

**Comment by coyo7e** [comment]
I just spawned a lightstrip (inactive) and stuck a battery into it, it immediately turned on, displayed the battery, and I was able to unload the battery with no ill effects. FWIW there are two distinct lightstrip items in the debug spawn menu, one that seems to have no battery and is turned on and seems to run indefinitely and cannot be reloaded or unloaded, while the one labelled "(inactive)" which can be reloaded normally. 

![image](https://user-images.githubusercontent.com/80022377/152045716-7142137c-55bc-434e-bd78-8be005a0b6d8.png)

![image](https://user-images.githubusercontent.com/80022377/152045790-0c253ece-4e30-499c-a8b4-6455a1455927.png)

![image](https://user-images.githubusercontent.com/80022377/152045753-f7a3cd3e-2341-47a9-8910-57ef7b1daf14.png)

![image](https://user-images.githubusercontent.com/80022377/152046045-cd372a4a-6886-4b8d-a44a-c970dbc76735.png)

**Comment by ChucklesTheBeard** [comment]
Confirmed

![image](https://user-images.githubusercontent.com/12536545/152067657-7d623309-fb19-4307-9539-87c5ddbe322f.png)

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 1d4f464 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

Steps to reproduce:
1. Obtain flashlight.
2. Disassemble flashlight to obtain lightstrip (inactive).
3. Obtain light battery.
4. Reload lightstrip.
5. Activate lightstrip.

@coyo7e Could you run a debug report please? Debug menu -> `i`nfo -> Generate game `r`eport

**Comment by coyo7e** [comment]
@ChucklesTheBeard No problem, I'm currently running the newest experimental version as of 2/1/2022 I think, I usually hit the update button in the morning each day. I can't upload a copy of the charfile I'm using since I didn't start the thread.

Any idea what version the stream you were watching was using by chance? If they were on 0.F on something, who knows what's been changed/fixed/etc since then.

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 272b7a4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by ChucklesTheBeard** [comment]
A link with a timestamp is in the original report, I copied the version
from the main menu at the start of the stream.

**Comment by LeahLuong** [comment]
@Maleclypse Not sure "Vehicles" is the right tag here. OP confirms their own bug report but says they wrote the report based on seeing a Twitch stream. I guess that counts??

**Comment by Maleclypse** [comment]
> @Maleclypse Not sure "Vehicles" is the right tag here. OP confirms their own bug report but says they wrote the report based on seeing a Twitch stream. I guess that counts??

I thought lightstrips were vehicle parts? If not happy to change the label.

**Comment by x-qq** [comment]
This issue still very much exists.

**Comment by Hirmuolio** [comment]
Seems like the pocket data is on the wrong item. Only the inactive variant has pocket data so activating it makes the pocket go away and probably breaks things.
