### ISSUE TITLE
Spiders fall into their own sinkholes and die

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#54849]
### Describe the bug

Spiders in a spider pit can fall into their own traps.

### Steps to reproduce

1. Teleport into a spider pit (surface).
2. Wait some turns.
3. The spiders trigger sinkholes.

![image](https://user-images.githubusercontent.com/59517351/151460068-f18b5665-b015-461e-b79b-b1c39e88016d.png)

(Also a minor case of #7533)

For more context, this is my debug playtesting world where all my stats are 25 which is why I spotted that sinkhole immediately and freely use the debug teleport ability.

### Expected behavior

Spiders should be immune to sinkholes or the sinkholes present should be turned into web-filled sinkholes, providing immunity to spiders but you get webbed and fall.

### Versions and configuration

- experimental

**Comment by jworkman01** [comment]
I would like to work on this issue if it is available. I am new to open source and this seems like a good first issue to attempt.

**Comment by jworkman01** [comment]
Cool thanks!
