### ISSUE TITLE
[ Feature request ] Give NPC Medic order

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#54865]
### Is your feature request related to a problem? Please describe.

If I've got an NPC with better medical skills than myself, I should be able to request that NPC use up any available healing supplies in their inventory to heal those around them including myself.  

### Solution you would like.

Basics:
It should work through the NPC command menu.
It should use medical supplies in their inventory.
They should be able to work on both the PC and other NPCs.

Bonus round: 
You can set a guideline to only heal limbs worse than x health bars.
You can set a zone that has NPC usable medical supplies that the medic will use.
You can set the NPC to always refill their inventory from a zone when they have less than specific amounts of medical supplies.

### Describe alternatives you have considered.

This is suggestion only from my end.

**Comment by LeahLuong** [comment]
Don't followers already have an automatic function for this?? I've never entrusted my followers w/ drugs but they have a conversation point where they say they will use them on themselves 1st before tending to others.

Don't get me wrong, it would be nice to have more control over that process, especially w/ a specific zone. This was brought up in #53910.

**Comment by morthein** [comment]
Zoning would be nice for this, but a direct command would be way more useful in the field. NPCs do use bandages, but it's really unclear when. I've had some npcs not use them and continue to bleed while others seemed to use them as normal. Was their first aid skill the reason?  I'm really not sure and don't have those games anymore to check.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
