### ISSUE TITLE
Update "restricts_gear" in mutations to use the new bodyparts

### ISSUE THREAD

**Issue by Jarewill** [CleverRaven/Cataclysm-DDA#54872]
### Is your feature request related to a problem? Please describe.

Currently mutations restrict gear if worn on a specific limb, even if it doesn't make any sense, such as the Hub 01 greaves being blocked out due to having a tail, even if they only cover the shins and knees.
There is a flag that gets around this issue called ALLOWS_TAIL, but I believe I have a better idea.

### Solution you would like.

The idea is to be able to specify what part of the limb a mutation restricts, such as tails restricting only hips. (and maybe thighs)
That way the tail mutations will no longer block out any items they shouldn't, just because they lack the relevant flag.

This will also allow for more specific mutations, for example: Elbow spikes that give a strong attack, but prevent wearing long sleeved clothing/armor.

### Describe alternatives you have considered.

Keep using the ALLOWS_TAIL instead.
Also give that flag to the Hub 01 greaves in this case.

### Additional context

In #54810 I was told to open a new issue about it, so I did.
I apologize for necro'ing a closed issue from 2 days ago, I didn't realise when it was closed until after I posted there.

**Comment by bombasticSlacks** [comment]
To paraphrase @Venera3 who is working on the overhaul to something similar to this suggestion they said something along the lines of: I haven't really looked into the sublimb stuff yet.

So this (or something similar) is in the pipeline. The delay is Venera is already plugging away at stuff in an order they want, and no one else really seems to have the drive. If someone wanted to implement this suggestion now it probably wouldn't be too hard. Mutations can have a "blocks_sublimb" attribute, or something similar and then where the code normally checks it also compares the bodies blocked sublimbs vs the armors covered sublimbs.

**Comment by Venera3** [comment]
The armor stuff will take somebody codier than me to hook up properly(wink, wink, nudge nudge). The way I could imagine it is filtering based on the sublimbs the bodypart is defined with, this would of course need armor to accept alternative coverage arrays -e.g. elbow pads either covering left/right elbow or Insect Leg legs' left/right 1st joint, stuff like that. When *that* happens we'd need a way for a bodypart to define which sublimb to block from the connecting upstream/downstream part - tails blocking waist on your torso, if you have a torso with a waist. 

I'll need to give the system a think and write up an issue on how it could work, but I haven't found the time yet.

**Comment by Jarewill** [comment]
Alright, I see.
Thank you both for your time.

So, if I understand correctly, for now there's no reason to update the mutation code as there's another bodypart overhaul in progress?
If so, should this issue be closed?

**Comment by bombasticSlacks** [comment]
feel free to add those allow tail flags to the leg guards for now! and it is being worked on so no reason to close this.

**Comment by Jarewill** [comment]
Alright, I'll try.
However this is the first time using GitHub for me, so it will take some time.

**Comment by bombasticSlacks** [comment]
If you add it here: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/items/armor/robofac_armor.json#L219 it will apply to all of the different versions.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
