### ISSUE TITLE
Unspecified strapped items conflicting with "hanging off" items

### ISSUE THREAD

**Issue by Jarewill** [CleverRaven/Cataclysm-DDA#54871]
### Describe the bug

Wearing an item that is strapped to the torso without a specified area conflicts with items that are "hanging off back/front" and adding extra encumbrance.
For example if you wear a heavy load bearing vest and a duffel bag, you are going to get 9+4 encumbrance total.
This looks like an oversight to me, as other variants of the load bearing vest work perfectly fine with backpacks.

I noticed this issue also happening with the scavenger gear armor.

### Steps to reproduce

- Debug in a heavy load bearing vest and a duffel bag
- Wear them both at the same time
- Note the added encumbrance penalty

### Expected behavior

Being able to wear a vest and a backpack without being penalized for it.

### Screenshots

![image](https://user-images.githubusercontent.com/98614648/151615121-b7f3c97f-51b3-47b1-95c6-cabe42a135b4.png)
![image](https://user-images.githubusercontent.com/98614648/151615156-2de94d43-2764-4850-b4b8-75afa14a46fc.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 64b4f57 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

In the Scavenger Armor Overhaul pull request (#53533) it was noted that unspecified strapped items shouldn't interfere with backpacks, but that appears to not be the case.

**Comment by LeahLuong** [comment]
Duffel isn't really a backpack; it typically only has a single strap & a couple of carrying handles. Makes sense to me this would me more cumbersome than a backpack as backpacks closely hug your body while a duffel is just sort of loosely dangling by that single strap. Do you encounter this issue w/ items besides the duffel??

**Comment by Jarewill** [comment]
Yes, as I said in the issue those items interfere with any items on the "hanging off" layer, such as normal backpacks and single point slings.
Any item that says that it's hanging off of the back or front will interfere with an item with an unspecified layer.

**Comment by LeahLuong** [comment]
Pardon me if you see this as pedantic or semantic, but isn't the torso a "specified" area??

> other variants of the load bearing vest work perfectly fine with backpacks.

> Yes, as I said in the issue those items interfere with any items on the "hanging off" layer, such as normal backpacks and single point slings.

???

**Comment by Jarewill** [comment]
I apologize for not making myself clear, as English is not my primary language.
What I mean is basically this:
This is the coverage entry for the heavy load bearing vest:
![image](https://user-images.githubusercontent.com/98614648/151623897-9d79c124-3b05-492e-b735-708145cc323d.png)
While this is the coverage entry for the normal load bearing vest:
![image](https://user-images.githubusercontent.com/98614648/151623917-ff9f43f6-a8f7-414f-a24a-1b271723a351.png)
As you can see, the normal one specifies that it only covers the upper torso, while the heavy one doesn't

I would understand that the heavy vest covers both the upper and lower torso by that, but that doesn't seem to be the case.
Once again in #53533 it was mentioned that if an item on the strapped torso layer has no specification, it would not interfere with backpacks and such, but that doesn't seem to be the case.

**Comment by LeahLuong** [comment]
@bombasticSlacks Dillon, can you make sense of this?? You authored the commits for this, after all.

**Comment by bombasticSlacks** [comment]
I've actually been working on this this afternoon. This info is useful thank you.

**Comment by bombasticSlacks** [comment]
> I would understand that the heavy vest covers both the upper and lower torso by that, but that doesn't seem to be the case.

this assumption is correct, 
torso is technically only upper torso and lower torso (hanging locations are handled specially even though they are technically torso).
So it's just if an item covers all the locations in an area to save space the UI doesn't show the specifically stuff. 

Again I am currently working on this. I was using different items though so presenting this stuff is really helpful thank you.

**Comment by Jarewill** [comment]
I see, thank you for your work on this.
And I am sorry for not making myself clear initially.

**Comment by bombasticSlacks** [comment]
FWIW it was clear to me 😄 

It's gonna take some time to solve but I'll sort it out.
