### ISSUE TITLE
Gunsmith/Blacksmith vendor home is always hostile

### ISSUE THREAD

**Issue by shekel-snatcher** [CleverRaven/Cataclysm-DDA#54876]
### Describe the bug

Upon entering the vendor area within the fenced off border, turrets appear to ignore the player but will eventually become hostile and shoot the player without warning. The vendor area spawned in a somewhat hostile environment, between a wyrd spider nest and fungal spores.

### Steps to reproduce

1. Enter the designated vendor home, attempt to trade with vendors, etc.
2. Within a in-game minutes, multiple turrets change behavior from "ignoring" to "tracking"
3. Turrets become hostile with no warning and shoot players immediately, attempted with both a firearm in-hand and worn on the torso. 

### Expected behavior

Turrets within the vendor area would shoot hostile monsters on sight, but would always ignore the player unless the player attacks or steal from the vendors.

### Screenshots

![image](https://user-images.githubusercontent.com/98622549/151632304-2865df6b-7207-4090-994d-a2e20725974f.png)
![image](https://user-images.githubusercontent.com/98622549/151632362-0bbe2845-62e5-4a05-b3fd-27fed0b0638f.png)

### Versions and configuration

- OS Windows 10
- Branch: Experimental
- Platform: Windows x64(64-bit)
- Build: 2022-01-28-0753
- Mods loaded: 
Dark Days ahead
Disable NPC needs
No Fungal Growth
Bionic Professions
C. R. I. T. Expansion Mod
No Freeze
No Rail Stations
Graphical Overmap
Mole Mutation

**Comment by GuardianDll** [comment]
Can expect that turrets become hostiles by detecting some monsters nearby, thats an AI issue (and i hope someone made a bugreport about it)

**Comment by LeahLuong** [comment]
I believe this was brought up in #54752.

**Comment by shekel-snatcher** [comment]
> I believe this was brought up in #54752.

Thank you! I looked for this issue but couldn't find anything on it. Looks to be the same issue. I'd never seen the area before and thought it was a cool idea for a vendor hub, just bummed that it'd kill my character just to trade.
