### ISSUE TITLE
Hunting lodge use the wrong nested chunk direction

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#54878]
### Describe the bug

Hunting lodge uses a default basement chunks to generate stuff: `room_6x6_woodworker`, `room_6x6_bike` `room_6x6_office_E`. From all of them, only `room_6x6_office_E` has correct position to enter (from the east, as you can see in the name), another two uses a south version, and has lack of another direction versions

### Steps to reproduce

Find some hunting lodge
with some propability it would have a wrong positioning (~80%)

### Expected behavior

having correct versions of chunks
having an entrance from both east and south sides

### Screenshots

wrong position of chunk
![image](https://user-images.githubusercontent.com/67688115/151634243-0cc273a3-5514-44c7-b2da-8e171194b1a4.png)
right position of chunk
![image](https://user-images.githubusercontent.com/67688115/151634714-8f213ab8-82fe-4c7c-99f2-d120d66f621d.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 64b4f57 [32-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    SpeedyDex [speedydex]
]

**Comment by Night-Pryanik** [comment]
@Maleclypse are you working on this?

**Comment by Maleclypse** [comment]
No I'm not currently.  I assigned myself so I wouldn't forget about it but I haven't gotten to it yet.  I'll remove my assignment.  Thank you!
