### ISSUE TITLE
sleep until dawn

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#54875]
### Is your feature request related to a problem? Please describe.

often when I go to bed I set the alarm for when I think it will be light out and I have to guess when that will be.

### Solution you would like.

an option for set an alarm to be set for dawn so you can maximize the use of light in a day. a sleep until dark would probably also be useful for nocturnal builds for the same reason.

### Describe alternatives you have considered.

leaving as is

**Comment by chrispikula** [comment]
A minor work-around until you get a PR to help with this is that you can sleep in a safe spot that will get sunlight.  
If your vehicle has curtains on every window, open the one just to beside where you sleep, or maybe a tile over.  You'll wake at near the crack of dawn.

**Comment by robotic-gamer** [comment]
I'm fine with just guessing. It just seemed like a very easy thing to add that would improve the game. Thanks for the advice.

**Comment by LeahLuong** [comment]
I believe Ramza13 has plans to implement portal storm effects that turn night into day & vice versa. Please take note, whomever decides to attempt implementation of this feature; there may be a conflict if the alarm is set to "dawn" but the game is calling that function for the portal storm. On the same note, I believe the wait command has options for dawn & dusk. These may help as examples for how to code this feature.

**Comment by robotic-gamer** [comment]
my thinking was the game would just calculate how long until dawn then set the alarm to go off then (ie wake up in 8 hours, 25 minutes and 32 seconds). in the event of a portal storm your wake up time would be unaffected. This would make sense from a realism sense in that the player would know what time dawn is and would just set the alarm to go off at that time.

**Comment by Leland** [comment]
Since it'll probably be asked: in terms of realism – as phones and clocks don't have a "Dawn" button (and the internet is not available in CDDA) – the head canon for this might simply be that the player character had seen when the sun rose the day prior and sets the alarm to the same.

**Comment by oosyrag** [comment]
Well the player and player character should be pretty well interchangeable in this situation. Does the player know what time dawn is? Then they can set the alarm manually as it is (is being off by half an hour a huge deal?). If the player doesn't know what time dawn is, the player character also probably wouldn't know for the same reason - slept with the blinds closed or in a basement ect. 

Even in real life I don't really know exactly when dawn is at my own location without looking it up, most people do not have a reason to wake up exactly when the sun comes up.

**Comment by chrispikula** [comment]
What about a recipe that uses, as a tool, a book that's about as fun to read as the phonebook, but allows you to craft a daytime alarm?  It goes off at dawn, and then transforms back to a normal clock or watch.  'A Detailed Analysis of New England Historical Weather Data' or somesuch.  Just something that even the title gives you little shivers of how unbelievably dry it is.

**Comment by Zireael07** [comment]
@oosyrag: You don't need exact knowledge of when dawn is, you just need some sort of a light sensor (wouldn't work for the basement case, but for all others... well)

**Comment by robotic-gamer** [comment]
also you can get the exact time dawn is by going into the wait menu. So the game already implies the player knows when dawn is.

**Comment by RabblerouserGT** [comment]
> Since it'll probably be asked: in terms of realism – as phones and clocks don't have a "Dawn" button (and the internet is not available in CDDA) – the head canon for this might simply be that the player character had seen when the sun rose the day prior and sets the alarm to the same.

I have two ideas considering this.

- Weather CBM could allow you to have a very exact alarm, possibly. Depends on what the lore concerning weather CBM might say.
- There is a "look up at the sky" command in ENTER > [1] Look > [1] Look at the Sky. Perhaps have it set to if you've recently (within 2 weeks maybe? or within the season if you're feeling generous) looked at the sky. Also POSSIBLY gate this whole thing behind a survival skill check.

**Comment by Zireael07** [comment]
Related: #50869
