### ISSUE TITLE
Auto pickup max quantity

### ISSUE THREAD

**Issue by matshou** [CleverRaven/Cataclysm-DDA#54879]
### Is your feature request related to a problem? Please describe.

I don't like that I have to manually sort through content after auto picking it up and removing excess items.

### Solution you would like.

Auto pickup should have a configuration value for each item entry that determines the maximum count an item in inventory is allowed to have before auto pickup stops working for that item. The feature should become suspended for that item until the item count drops below the max quantity value specified by entry configuration value.

For example let's say the player wants to go scavenging and is interested in finding and looting 5 units of water. He starts his journey with 2 units of water so with this feature implemented he would create a new auto pickup entry for water and configure it to only allow up to 7 units of water. During his scavenging trip he would pick up (either manually or via auto pickup) additional 5 units of water after which the auto pickup entry for water would no longer work until there is less then 7 units of water present in his inventory. He would return to his base, unload the water and either disable or remove the entry from auto pickup manager.

### Describe alternatives you have considered.

I have considered manually sifting through auto picked content to remove excess item count but I quickly concluded that having this automated in a configurable way is a much better idea.

### Additional context

_No additional context available._

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/a-way-to-improve-auto-pickup/10479/8

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
