### ISSUE TITLE
Introduce pseudo furniture and terrain tiles usable in blueprints to "dismantle" it

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#54889]
### Is your feature request related to a problem? Please describe.

The current fire station base camp emulates dismantling of furniture by clearing it and leaving a pile of items calculated by hand. It would be good if that calculation could be done automatically and with dynamic results.
Similarly, it would be good to be able to order the "dismantling" of "terrain" and have the game figure out the time and tools needed and the resultant products based on the actual terrain.

### Solution you would like.

Introduce e.g. "t_dismantle" and "f_dismantle" as pseudo (or virtual, if you like) terrain/furniture. Once specified in a blueprint, code would examine the actual terrain/furniture at the tile and determine the tools and time needed to "dismantle" it, as well as whether it's not possible to do (indestructible terrain), ideally taking a character selected to perform the task into consideration.
The result of these calculations for a construction (destruction?) recipe would then be summed up and presented as the required time and materials.
Once such pseudo terrain tiles are applied, they would change the terrain into one appropriate for the tile with the items resulting from the "dismantling" on top of it. This would e.g. mean that dismantling an underground tile would result in the same result as manually digging out that tile, with soil/rock floor dependent on the location (at least until underground tiles are differentiated as different tiles rather than on depth) and with same soil/rock results as for a manual digging action.
Note that this would require the functionality to have some "smarts" so it can cut down a tree, for instance.

### Describe alternatives you have considered.

- Different names, of course, such as "t_pseudo_dismantle" to make it clear it's a pseudo tile that should never actually appear as and actual tile, in addition to something that might be better than "dismantle".
- Change the current furniture dismantling action to similarly have its time and tools required being dependent on what the actual item is, rather than whether it just supports the appropriate dismantling action. However, I think that's a different issue, and that a furniture dismantling tile functionality ought to be reasonably easy to update to make use of that functionality if it is implemented.
- Also introduce "t_smash" and "f_smash" for destructive modification of terrain/furniture.

### Additional context

Currently blueprints just replace whatever is there with whatever is specified to be in its place. I think it might be useful to make it possible to modify the location in a way that's dependent on what it looked like previously, and think that it might also be applicable to "normal" map generation if a smashed up version of a location could be generated by applying a "smashing up" pass on it.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
