### ISSUE TITLE
Add "allergy" filter to AIM/Zones/Inventory menus

### ISSUE THREAD

**Issue by ElfLeaderMike** [CleverRaven/Cataclysm-DDA#54899]
### Is your feature request related to a problem? Please describe.

When trying to eat food from my giant lazy pile of loot, it gets fairly annoying to sort through the list of red food items that slowly stack up from all my mass house zone looting. Using material filters doesn't work because most of the food is contained within a container so it bypasses said filter.

### Solution you would like.

I'd like to be able to type -allergy in any inventory screen (especially the eat menu!) and only see food I can eat without any consequences.

### Describe alternatives you have considered.

Leaving as is to increase menu gameplay time.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
