### ISSUE TITLE
Joint Servo CBM's description problem.

### ISSUE THREAD

**Issue by luminous030** [CleverRaven/Cataclysm-DDA#54893]
### Describe the bug

This CBM's description hasn't mentioned power cost. Is it a bug or on purpose?

### Steps to reproduce

1. Joint Servo CBM
2. Install it.

### Expected behavior

I expected that description to include the power cost, about 35J per move perhaps?

### Versions and configuration

- OS: [ Windows 10 ]
- Game Version: [ 0.F-3 ]
- Graphics version: [ Tiles ]
- Ingame language: [ Chinese (Simplified) ]

**Comment by LeahLuong** [comment]
The CBM has a different cost while running (crouching?? [prone??]) & this cost can be offset w/ Joint Torsion Ratchet. If all this info can't be fit in the bionics screen, the CBM's description should @ least mention it consumes power based on movement.

**Comment by Night-Pryanik** [comment]
The info is here as of 0.F-12178
![изображение](https://user-images.githubusercontent.com/11132525/198833046-c3ca0f1a-16f7-4a7f-86cc-ea9eceac7ad7.png)
