### ISSUE TITLE
Very large items disappear when dropped

### ISSUE THREAD

**Issue by VarrenKrytor** [CleverRaven/Cataclysm-DDA#54891]
### Describe the bug

By batch crafting 50 of a large item, you can make a very big craft.  If you wield then drop it, it will disappear from the world.

### Steps to reproduce

1. Batch craft 50 Wooden Panel at a workbench
2. Wield the resulting in progress craft
3. Drop it on the workbench

Now it's gone

### Expected behavior

Items should not disappear from the world.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 64b4f57 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Stats Through Kills [stats_through_kills]
]

### Additional context

Related to #54890

**Comment by PatrikLundell** [comment]
The reason it disappears is that tiles have a maximum storage capacity, and if there is no tile that has enough capacity to hold the item the item disappears. The game essentially doesn't support items larger than what can be stored on an empty tile (there is some furniture that has a larger storage capacity, but that's really a niche case, and that space is provided by having multiple shelves, and so isn't for a single item anyway).

The game should not allow batch crafting of in-progress items larger than what can be stored on a workbench, and single crafting items larger than what can be stored on an empty tile.

**Comment by LeahLuong** [comment]
This appears to be a dupe of #36968.
