### ISSUE TITLE
Health is always -200 no matter what

### ISSUE THREAD

**Issue by Devengel** [CleverRaven/Cataclysm-DDA#54896]
### Describe the bug

no matter what i do health is always set to -200 and eating health/debugging it out doesn't seem to work?

### Steps to reproduce

Try my save below, try debugging it out, it'll come back. 

### Expected behavior

something got confused and its making my health & tiredness suffer

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 64b4f57 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Mythical Martial Arts [MMA],
    Graphical Overmap [Graphical_Overmap],
    Magiclysm [magiclysm],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills]
]

### Additional context

[YeeHaw.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7963722/YeeHaw.zip)

**Comment by ProgrammerForFun** [comment]
I downloaded your save and cheked your character: you have bloodworms
How to see it: spawn and install the Blood Analysis CBM, then use it, parasites aren't shown in character screen

**Comment by Leland** [comment]
Closing for now! If you want some more advice on how to do the above, consider posting over in the Discourse yonder: https://discourse.cataclysmdda.org/
