### ISSUE TITLE
Changing aiming rules have no "Never mind" option

### ISSUE THREAD

**Issue by Faalagorn** [CleverRaven/Cataclysm-DDA#54898]
### Describe the bug

Other options have an option of "Never mind", to quit without changing a thing. It seems that aiming options are lacking this option.

### Steps to reproduce

1. Talk to NPC (e.g. by starting new game as Evacuee)
2. Make the NPC join your faction if not done so already
3. Choose "I want to give you some commands for combat."
4. Choose "Change your aiming rules…"
5. Observe no "Never mind" option.

### Expected behavior

Being able to get back without changing aiming rules.

### Screenshots

![screenshot_2022-01-29-155858](https://user-images.githubusercontent.com/4951331/151665856-30db07c5-2f28-4fd7-90e3-d0006af8c2c3.png)
![screenshot_2022-01-29-155849](https://user-images.githubusercontent.com/4951331/151665858-7f319b31-9489-4d1a-b886-d055009c5bcb.png)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.F-5670-g1bba9b703bd [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by haveric** [comment]
This was fixed by [PR #55333](https://github.com/CleverRaven/Cataclysm-DDA/pull/55333)

**Comment by Faalagorn** [comment]
Thanks! I guess I missed that, I'll see it when I'll be back at home, but I'll go ahead and close the issue now :)
