### ISSUE TITLE
Add separate male/female strings for Traits (mutations)

### ISSUE THREAD

**Issue by Faalagorn** [CleverRaven/Cataclysm-DDA#54901]
### Is your feature request related to a problem? Please describe.

I discussed it briefly with @BrettDong on the official Discord, but it would be nice to have separate strings for traits (mutations) for Male and Female in character creation, similar to how scenarios, professions and even backgrounds have. This would allow some languages, e.g. Polish to have more natural and less forced translations especially for mutation descriptions.

### Solution you would like.

Add separate translations for Male and Female mutations/traits

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
