### ISSUE TITLE
Add ability to change gender with @ sign when on scenario screen

### ISSUE THREAD

**Issue by Faalagorn** [CleverRaven/Cataclysm-DDA#54902]
### Is your feature request related to a problem? Please describe.

Currently, you can change gender when on Profession and Background character creation screen, but not on scenario screen. It would be nice if that could also be switched on that screen too.
![screenshot_2022-01-29-174407](https://user-images.githubusercontent.com/4951331/151669413-b47cd6b5-a064-4ef7-9c31-6de78e23dbf6.png)
![screenshot_2022-01-29-174404](https://user-images.githubusercontent.com/4951331/151669414-c65e6d19-3fd6-40ea-a304-56b5c16bbe41.png)
![screenshot_2022-01-29-174400](https://user-images.githubusercontent.com/4951331/151669415-dd819cf1-77ba-4fcf-b5ac-38688c19bdc5.png)

### Solution you would like.

Add "Press @ to switch to XXX female/male".

**Comment by Jan-Blasiak** [comment]
I'm having viethub flashbacks.
