### ISSUE TITLE
Graphical glitch while moving character

### ISSUE THREAD

**Issue by TadhgEomonn** [CleverRaven/Cataclysm-DDA#54911]
### Describe the bug

While moving character, intermittently the steering/selecting box (white picture frame shape in Chibi_Ultica) appears and rapidly disappears to the left (east) of the character icon/sprite. The same selecting/steering icon appears when opening the escape-key menu and persists until the menu is closed. I am using the Chibi_Ultica tile set, but the same behavior is evident with most other tile sets. 

### Steps to reproduce

Start game; move character; observe distracting glitch.

### Expected behavior

This should not appear, unless the character is looking around.

### Screenshots

The glitch flashes on and off intermittently and randomly every few moves. Hence a screenshot is not possible. A video would capture the behavior, but I do not have a video.

### Versions and configuration

Win 10
version 1bba9b7 (tiles)

**Comment by mqrause** [comment]
You most likely accidently shifted the view with `H`. Press `L` to shift it back the other direction.

I'm not sure if that's how it's supposed to behave even with a shifted view, though.

**Comment by TadhgEomonn** [comment]
@mqrause, 

You are correct, sir. I inadvertently must have typed 'H'. Problem solved from my perspective.

As for the strange and distracting behavior while in shifted view I can add nothing, having no prior experience.

Thank you. Sorry to have cluttered the issue pool with my noob mistake.

**Comment by LeahLuong** [comment]
Same thing happens w/ NeoDays tileset. I appreciate this feature because it informs me if my screen is off-center. I vote for closing this issue.

**Comment by mqrause** [comment]
I'm sure there are better and more consistent ways to communicate that. And I'm not even sure that communication is relevant if that's the only thing that makes you notice it's off-center in the first place. You might even want it to be offcenter and then it's just a distraction.
