### ISSUE TITLE
Move most pieces of armor to the strapped layer

### ISSUE THREAD

**Issue by Jarewill** [CleverRaven/Cataclysm-DDA#54916]
### Is your feature request related to a problem? Please describe.

I thought about opening a new discussion, but I don't have the ability to, and I couldn't find any discussion about this, so I apologize if this is the wrong place to do it.
I wanted to talk about the layer choices and hear what other people have to say about them.

Personally I find it quite weird how a cuirass conflicts with a hoodie, while it doesn't conflict with a utility vest.
Maybe I don't understand something, but I feel like it should be the other way around: Cuirass conflicting with the vest, but not with the hoodie.
While I don't have an actual cuirass, I do have plastic motorcycle armor (which I think would be similar to the hard chest guard from the game), and wearing it over a hoodie wasn't much different than wearing it alone.
Another example is how a ballistic vest conflicts with the army jacket, despite most soldiers being issued with that combination.
It's also pretty odd how one type of vest (such as the utility vest, strapped) is on a completely different layer from the other type (ballistic vest, outer)

### Solution you would like.

Move the various armors (plate, scrap, ballistic vest, SWAT, knee/elbow pads) to the strapped layer to make them fit with other vest items (utility, load bearing) and prevent conflicts with clothing.

### Describe alternatives you have considered.

Keep the layers as is.
Move the strapped vests to the outer layer instead to fit with the others.

### Additional context

This was something that was bothering me for a while now, as it didn't make much sense as to why those layers were chosen for armor.
It sounds like easy json fixes, so I could work on this, as I probably should figure out how github works.

However I also wanted to hear what other people think about this.
Maybe there's just something I'm not understanding about the layer choices.

**Comment by Drew4484** [comment]
This is a good initiative, one thing to consider: armor can exist on multiple layers now. 

This means you could have a jacket (cloth 100% coverage on normal layer) with added plates (steel, 80% coverage on outer layer).

So looking at the existing armors, if it has cloth or some other kind of soft layer, consider changing that to normal and leaving plating on outer. In cases where the materials are integrated (nylon/kevlar vest) it would make sense to keep them on one layer, likewise if it's just the outer 'shell' like a cuirass it makes sense to have that on the outer layer.

**Comment by LeahLuong** [comment]
Although this isn't exactly a dupe issue, it seems to have significant overlap w/ #52514. Consider moving the points you've made here into that issue (that weren't already raised there) & closing this issue.

**Comment by Drew4484** [comment]
So that discussion was from before armor could be on split layers, your goal is still a good one and worth the work. I need to start making a pass through metal armor and replacing IRON and STEEL with grades of steel, if you're going to continue on this project I'd love to colab on that aspect.

**Comment by Jarewill** [comment]
> This means you could have a jacket (cloth 100% coverage on normal layer) with added plates (steel, 80% coverage on outer layer).

Jackets (light, leather, army) already exist on the outer layer, which makes sense since they are worn over shirts.
However that makes them interfere with armor, which I believe shouldn't be the case. (I didn't have issues wearing plastic armor and elbow pads over my hoodie in real life)

> So looking at the existing armors, if it has cloth or some other kind of soft layer, consider changing that to normal and leaving plating on outer. In cases where the materials are integrated (nylon/kevlar vest) it would make sense to keep them on one layer, likewise if it's just the outer 'shell' like a cuirass it makes sense to have that on the outer layer.

I understand that in the case of the armored leather jacket, which is just a jacket with added plates on top of it, but should that be the case of armors that have straps to keep them in place?
Yes, the straps are under the armor, but if they would be kept on a different layer they would interfere with clothing on that layer, which I don't think a few straps would be an issue with clothing.
For example gambesons worn under plate didn't interact badly with the straps keeping the armor in place. (At least not to my knowledge)

> Although this isn't exactly a dupe issue, it seems to have significant overlap w/ #52514. Consider moving the points you've made here into that issue (that weren't already raised there) & closing this issue.

I must have somehow missed that issue.
Alright, I will move my points and close this one.
