### ISSUE TITLE
Dialogue-box toggle-key request

### ISSUE THREAD

**Issue by TadhgEomonn** [CleverRaven/Cataclysm-DDA#54928]
### Is your feature request related to a problem? Please describe.

There is an inconsistency in the user interface when pressing (e) to examine an item within another dialogue box. Sometimes the (e) key works as a toggle, both opening the examine box and closing it--which is good design. While in other circumstances (e) key opens the examine box but does not close it, necessitating the user to find the correct closing key (frequently the Escape key).  

### Solution you would like.

I would like to see the toggle functionality for (e) examine box be consistently used. Always functioning as a toggle: open examine box | close examine box. 

This toggle feature is a major user interface efficiency: your fingers need not jump all over the keyboard to find the (Esc) key (for example).

There are other instances of this behavior in the user interface that could also benefit from this small change; unfortunately, being a relatively new player, I can not catalogue every instance where this would be a quality-of-life improvement. But I believe the game, which so intensely uses the entire keyboard and only the keyboard (primarily), would work more efficiently and intuitively by expanding the use of toggle keys for entering or exiting dialogue boxes.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
