### ISSUE TITLE
Portable Power UPS

### ISSUE THREAD

**Issue by LeahLuong** [CleverRaven/Cataclysm-DDA#54929]
### Is your feature request related to a problem? Please describe.

UPS could be made more portable w/ specific clothing items designed for it.

### Solution you would like.

I'd like to see @ least 3 clothing items introduced into the game designed specifically for UPS: a holster strapped to the leg, a fanny pack for the waist, & a backpack. Ideally, the holster & fanny would have room for exactly 1 UPS each while the backpack would have 2 fitting pockets. The fanny & backpack might have additional loops or small pockets for tools.

Lorewise, I see these accessories as something technicians or laborers would have. I'm thinking of a construction worker who makes frequent use of an electric jackhammer but these carrying cases might also see military use.

Because these cases are carefully tailored to accommodate UPS's & little else, they would have a low encumbrance factor. A survivor w/ middling Tailoring could prob craft these from cotton & plastic.

I think adding these items to the game & sprinkling them amongst appropriate loot tables could really help bring UPS use to more prevalence. It might also enable new design space for players & devs alike. Just think of all the things you could do w/ such unfettered power w/in such easy reach! No longer will gov't regulations &/or concerns for personal safety hold you back from crafting the electricity-based arsenal of your dreams!

### Describe alternatives you have considered.

Oh, pshaw! There's only 1 future & it includes carrying cases specifically designed for UPS.

### Additional context

I noticed heavy battery (high-capacity) has a volume of 1.5L, the same as the UPS which contains it. This is a physical impossibility unless the UPS is non-rigid (which I don't believe it is)! This feature request may entail changing either UPS or battery size.

Advanced UPS's are slightly smaller than their original flavor variety so might warrant their own series of accessories. Time enough to worry about that after a 1st pass implementation.

**Comment by a-chancey** [comment]
Sounds like you're on stable. 

The UPS is now larger than the heavy battery (UPS is 2.5L now), and the advanced UPS has been removed from the game.

**Comment by chrispikula** [comment]
The UPS also works while it is in a backpack, iirc.  You don't need to wear it.

**Comment by a-chancey** [comment]
You are correct. It’ll work as long as it’s with you (possibly even just in the same square, I can’t remember there, but I think I could use the ones from vehicle storage beneath me)

**Comment by LeahLuong** [comment]
I am playing on the latest stable (0.F-3).

I do realize you can throw it in a backpack you're wearing but I think my request is still justified. No holster fits a UPS & accessories designed specifically for UPS would have less encumbrance than those not.

This also makes sense from a lore standpoint. Many people have cases for their phones. Sure, they could carry their phones in plushies w/ a pocket or wrap them in a towel but they don't because the market has solved this problem. I argue it would've done the same for UPS in the world of pre-apocalypse CDDA.

**Comment by a-chancey** [comment]
I mean, the UPS fits in a purse or a backpack. It's a 5" cube roughly. It's literally a portable power pack with swappable batteries. It really doesn't need its own holster, you're never drawing it.

**Comment by LeahLuong** [comment]
@a-chancey Aaron, I'm not saying you need a holster so you can quick draw it for those times you need power fast. I'm saying you need a holster because otherwise you have no option of carrying UPS's on your legs efficiently. I almost feel like I'm feeding a troll here but maybe you genuinely have difficulty w/ conditional negatives.

**Comment by a-chancey** [comment]
I never intended to come off as a troll, so for that I apologize.

I'll just leave one suggestion and stop commenting on this issue:

Maybe we just need a belt clip tool mod that can attach to the UPS and clip it to your belt.

**Comment by chrispikula** [comment]
@a-chancey 

I once made a lamp use UPS power.  You didn't need to be directly adjacent to it for it to work, once you put it on the ground.  Now, I'm not sure if that was it taking time to use it's 1kj of transient charge, or distance (of the top of my head, I think it was a 3 tile radius in which it would always work), but it was funny to me at the time.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
