### ISSUE TITLE
Back Bay Limbo

### ISSUE THREAD

**Issue by LeahLuong** [CleverRaven/Cataclysm-DDA#54925]
### Describe the bug

Borichenko gives you a mission to recruit 5 people to help w/ cleaning the back bay of the refugee center after you complete the mission to clear it of Z's. It's possible to fail your Social skill checks enough times that you will find yourself unable to complete the mission. This effectively blocks access to his quest chain.

### Steps to reproduce

1. Clear out the back bay.
2. Talk to Borichenko.
3. Fail to convince any1 else to help clean.
4. Pay 10 Merch to recruit 2 people from downstairs.
5. Realize you were scammed.

### Expected behavior

I expected there to be a failure condition for the mission. As it stands, I'm out 10 Merch & the mission is permanently stuck in the active missions section.

### Versions and configuration

Android 0.F-3 Tiles English vanilla

### Additional context

Would be nice if there were more options to buy your way to success using Merch. Alternatively, being able to leverage the good will you've gained from doing other missions in the center could help. What about dialogue options for recruiting the beggars to help??

**Comment by LeahLuong** [comment]
Linking #30579 for when that moves ahead.

**Comment by PatrikLundell** [comment]
Paying (some of) the beggars to help with the work sounds like a good idea. They're short of food, and so should be desperate to take any paid job that doesn't place them in actual danger.

**Comment by LeahLuong** [comment]
Although I'd like the option, hiring the beggars may still leave the issue unresolved if you recruit them to your faction before completing the back bay. My main problem is such a simple mission that gates other missions shouldn't have a possibility of getting stuck. Still, I understand this area is a WIP; completing Borichenko's missions doesn't even result in the refugees making use of the back bay.

**Comment by I-am-Erk** [comment]
You need to work on your people skills obviously.

But seriously, I should add a few other ways to circumvent this. Easiest is to have at least one refugee that will agree no matter what, but what I think I'll do is track how many refusals you've had, and give you a freebie if you get too many.

Another, more fun, harder option would be to make it possible to get a follower to do it, and a less fun but more realistic option would be to do it yourself
