### ISSUE TITLE
Falling Into Water to Reduce Fall Damage

### ISSUE THREAD

**Issue by KeaneCarotenuto** [CleverRaven/Cataclysm-DDA#54931]
### Is your feature request related to a problem? Please describe.

I jumped from 3 stories up, into some deep water, and took a fair amount of fall damage, as well as damaging some of my clothes.
There was no indication that falling into the water was any better than hitting the ground.

### Solution you would like.

Falling/jumping into water from heights should reduce fall damage.

Ideally, the players Athletics (water movement) skill, would contribute to how much damage is reduced (the character knows how to dive / land in the water better)

The character's weight, and equipment weight could also be considered for damage reduction/increase.

### Describe alternatives you have considered.

Easy solution would be to make falling into water deal no damage to the player.

### Additional context

An example:
![image](https://user-images.githubusercontent.com/16412361/151689427-97aae1d5-60f0-4128-ae70-ea63df457ed5.png)

**Comment by Zireael07** [comment]
Counterpoint: https://publicaffairsworld.com/how-far-can-you-fall-into-water-without-dying/ (best thing google spat at me, but fall damage when falling into a pool was something commonly "busted" in myth busting TV programs)

Yes, you take slightly less damage but very slightly so,

**Comment by KeaneCarotenuto** [comment]
Oh yea for sure, ideally it would scale with height.
In the situation mentioned, it was only 3 stories up (~12m / 14f), compared to the 76m (250f) mentioned in the article.
Even I, an absolute novice at landing in water, have jumped off a diving board at 10m, and only had slightly sore feet.

The reason I thought to request this feature, is because of the experience I just had.
Looking to get out of danger, I jumped off a building into water, only to find I took just as much, if not more damage doing so.

**Comment by Zireael07** [comment]
Ah, good point to compare 3 stories to a diving board, from which people routinely fall w/o damage. For some reason, I thought we were talking of a much higher height

**Comment by Venera3** [comment]
It's already considered. Per `character.cpp:10664 Character::impact(`:
```
if( here.has_flag( ter_furn_flag::TFLAG_SWIMMABLE, p ) ) {
            const int swim_skill = get_skill_level( skill_swimming );
            effective_force /= 4.0f + 0.1f * swim_skill;
            if( here.has_flag( ter_furn_flag::TFLAG_DEEP_WATER, p ) ) {
                effective_force /= 1.5f;
                mod /= 1.0f + ( 0.1f * swim_skill );
            }
        }
```
Meaning even shallow water reduces the effective impact force to its quarter (potentially up to one-fifth at 10 athletics). This is *after* the usual fall damage reduction calc using dex/parkour instead of replacing it.

**Comment by KeaneCarotenuto** [comment]
> It's already considered. Per `character.cpp:10664 Character::impact(`:

Oh wow okay! I guess I misjudged how much damage I would be taking if it were solid.
Thank you very much for pointing this out!
