### ISSUE TITLE
Vehicle eats 100% of gas in it instantly

### ISSUE THREAD

**Issue by VarrenKrytor** [CleverRaven/Cataclysm-DDA#54934]
### Describe the bug

See attached save.  Fill the vehicle with gas, turn on the vehicle.  Attempt to move forward.  The vehicle dies, the gas tank is empty.  The tank is not damaged (Not that a damage tank could leak that much that fast anyway.  Please note that this happened after the engine died during redlining it in an Early Portal Storm.

### Steps to reproduce

1. Open the save game
2. Fill the car (named Blockhead) with the fuel to the right of it
3. Start the car and try to move forward

### Expected behavior

Fuel is consumed at a normal rate

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 7684355 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Stats Through Kills [stats_through_kills]
]

### Additional context

Due to crashes somehow my save is duplicated around 4 times in the world file.  Just open the most recent one (For me the one on the bottom of the list)

**Comment by VarrenKrytor** [comment]
Attached save

**Comment by VarrenKrytor** [comment]
Attached save

**Comment by VarrenKrytor** [comment]
Save file isn't attaching.  No idea why, github freaks out when I place it here.

**Comment by VarrenKrytor** [comment]
Note: Taking the entire vehicle apart and rebuilding from scratch fixed it.  Other vehicles work fine.  Replacing the engine alone didn't fix the issue.  I suspect the issue was attached to that vehicle object.

**Comment by chrispikula** [comment]
There is a file size limit.  How big was your .zip'd save?

**Comment by Alex-Folts** [comment]
> Note: Taking the entire vehicle apart and rebuilding from scratch fixed it. Other vehicles work fine. Replacing the engine alone didn't fix the issue. I suspect the issue was attached to that vehicle object.

Try replacing only fuel tank. Remove and install it back, or remove and install another tank. It could be bugged tank, just guess.

**Comment by VarrenKrytor** [comment]
I should have tried replacing the tank.  File is 25.8MB

**Comment by LeahLuong** [comment]
You can share your .sav by posting a link to it on a service such Google Drive where you have made the file available.
