### ISSUE TITLE
To serve man, morale boost too strong.

### ISSUE THREAD

**Issue by Xindage** [CleverRaven/Cataclysm-DDA#54933]
### Describe the bug

To server man book gives too much morale even if you're a psychopath, i find ok to it giving some morale but it's beating drugs right now.

### Steps to reproduce

1. Get a Cannibal or Psychopath character.
2. Read the book like 4 times.
3. Try drugs.

### Expected behavior

Some good morale boost like 40, around that.

### Screenshots

![image](https://user-images.githubusercontent.com/6380147/151692149-98649043-ca2f-4998-bdb0-77b2fbb119a4.png)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.3 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock]
]

### Additional context

By the way I think that Psychopath should receive less 3 points of bonus when reading this book (5 -> 2)

**Comment by GuardianDll** [comment]
True, the moral buff is really huge, but is it intended the book mood buff are gone after 10-15 minutes after reading?
![image](https://user-images.githubusercontent.com/67688115/151698260-6ebbdc05-1aaf-44a1-b8ac-7174705b9d29.png)

**Comment by Xindage** [comment]
it appear to stay for like 45 minutes (more or less) while it seems to be not much you can keep maintaining this morale by occasionally read the book every half hour, it really help gaining skills on crafting.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
