### ISSUE TITLE
Weaponised rebar is flimsy

### ISSUE THREAD

**Issue by Jarewill** [CleverRaven/Cataclysm-DDA#54945]
### Describe the bug

Pointed rebar, sharpened rebar and the rebar spear are all tagged as flimsy, despite the base rebar not having that flag.
Pointed and sharpened are just the base item sharpened at the end, so that shouldn't affect it's durability, while the rebar spear actually requires welding, which I don't think comes off easily.

Taking a look at a similar item, the pipe, it's sharpened variant isn't flimsy and it's (basic) spear variant is actually sturdy.
The basic pipe spear's description states that it's just "three pipes tightly fit together", so it really shouldn't be sturdy.

### Steps to reproduce

- Debug in a pointed rebar, sharpened rebar and rebar spear.
- Look at the description and notice it's labelled as flimsy.

### Expected behavior

Pointed and sharpened rebar not being flimsy like the base item.
Rebar spear being sturdy.
Basic pipe spear not being sturdy.

Alternatively the base rebar item also being flimsy like the others.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 64b4f57 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

I could have filed this as a pull request, but my first one is still open and I would rather know I did everything correctly before starting another one.

**Comment by Maleclypse** [comment]
Rebar bends when you stick it in something and pull it in a direction.   I would think anything short of welding three of them together would probably result in a flimsy item.

**Comment by LeahLuong** [comment]
Rebar's resistance to shearing force is related to its gauge. While thin rebar is quite easy to bend by hand, I don't think you would find it so easy to bend a 2" thick piece of steel. Here's a chart:

![Screenshot_20220130-211306](https://user-images.githubusercontent.com/91638992/151742465-8635713f-066b-41fc-ade3-c895904e1b96.png)

Now, puzzle out what bar size is found in CDDA.

**Comment by oosyrag** [comment]
Considering rebar is what you get for cutting prison cell windows, I would assume they are not the bendy kind.

**Comment by Jarewill** [comment]
Alright, I can understand the rebar bending out of shape when attacking.
However there is still the inconsistency of the base rebar item not being flimsy, while the sharpened rebar being flimsy.
Sawing off the end of a rebar to a point shouldn't lower it's durability.

So if the weaponised rebar weapons are really meant to be flimsy, then at least the base rebar item should also be flimsy.
Because if stabbing something with a rebar is enough to bend it out of shape, smashing things with it should be more likely to bend it as well.

**Comment by LeahLuong** [comment]
You can still bash things pretty effectively w/ a bent club. Stabbing things w/ a bent spear is much less effective because the more bent it is, the less thrusting force is transmitted & what isn't thrusting is being used to bend/break the spear further.

**Comment by robotic-gamer** [comment]
flip side of that argument is that means your spear damaged is now at worst a club (ie all damage to the spear should do is lower the pierce damage not straight up destroy the spear). other notes
- the advanced rebar spear consisting of two pieces of rebar welded together is still flimsy
- if bent rebar is bad why can't you just re-bend it straight in fight by using it as a club in the right direction?

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
