### ISSUE TITLE
Faction NPCs fight over a single bed

### ISSUE THREAD

**Issue by KeaneCarotenuto** [CleverRaven/Cataclysm-DDA#54953]
### Describe the bug

Despite having enough beds for all four of my NPCs in the faction camp, they only ever try to use one bed.
They constantly tell each other to move out of the way as they try to move onto the bed tile.

### Steps to reproduce

1. Create faction camp
2. Get multiple NPCs in camp
3. Build enough beds for NPCs
4. Tire them all out by keeping them awake (ask them to follow you and craft for a while)
5. Return them to working at the camp
6. Watch as they fight over a single bed tile

### Expected behavior

NPCs would check if there is a free bed.
    if free bed - NPCs would move to a bed that is not already in use.
    if no free bed - NPCs would sleep on the floor.
        - NPCs may complain about no free bed (?)

### Screenshots

![bed](https://user-images.githubusercontent.com/16412361/151720854-5c320cb1-8685-41d3-a6bc-eda138f67e2d.PNG)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm]
]

**Comment by LeahLuong** [comment]
Personally, I'm partial to, "Move your ass, piece of ass!"

Based on discussion in #33853, it seems followers won't look very far for a bed. Try 'G'rabbing the beds & pulling them closer to your own so more beds are closer to your char.

**Comment by PatrikLundell** [comment]
If I understand it correctly, the issue (which is old) is that characters assigned to camps grab the first free bed and keep thinking it's their bed when removed from and later returned to the camp, while the camp allocates beds to characters based on which beds are currently allocated, resulting in multiple characters getting assigned to the same bed.

Personally I avoid this issue by simply not assigning companions to camps (except through fat fingering and immediate recovery).

**Comment by KeaneCarotenuto** [comment]
Thanks Leah, I will attempt to move all of the beds closer to where my character is. Forgive me if I am wrong, but I feel like that would only help if the NPCs were following my character, and not stationed at the base? Perhaps I will move the beds closer to the center of the base too, and see if that helps.

Your explanation makes sense Patrik, but unfortunately I do want my NPCs to work at the camp, so I cannot afford to avoid the issue. Maybe reconstructing/moving the beds will help in some way with the allocation.

In either case, I will test it a bit more.

**Comment by PatrikLundell** [comment]
My understanding is that bed allocation should work if you only add companions to the base camp and never remove them, and, possibly, if you only add new companions to a camp when all previously allocated companions are present (and added) in it before you add a new one (dead companions won't compete with live ones over beds, so those companions can be disregarded).

Also note that you can order companions about via the bulletin board without them being allocated to the camp, but I assume you want them to engage in tasks specific to allocated companions.

**Comment by morthein** [comment]
I would like it if the followers were allowed to look further for a place to sleep. Too often, there are bases I have that have beds up or down stairs and yet, they complain and ultimately sleep on the floor.  They should look for beds up and down z-levels and make their way there, at least.  Plus, is it possible to have an npc temporarily claim a spot on a bed when he\she needs sleep to prevent other npcs from doing that top-bunk-child-behavior of fighting over beds?  If one npc claims it until they wake up, can it just flag it as ineligible to others for the duration of their sleep?
