### ISSUE TITLE
pocket system removed autowield functionality

### ISSUE THREAD

**Issue by SummGai** [CleverRaven/Cataclysm-DDA#54958]
### Is your feature request related to a problem? Please describe.

so when I stripped naked I couldn't pick anything up. I had never used the W key before to wield something. I fail to see *why* there is a key for that explicitly when there's a key to pick things up. This new system is...there? I don't see how it improves things enough to justify the removal of a function as basic as 'automatically pick up item and place it in your hands' thus forcing users to learn to use the W key to wield something just so they can equip it as clothing if that's their intent.

### Solution you would like.

have G let the user pick up an item and auto wield it if its too big to fit in your inventory.

**Comment by coyo7e** [comment]
FYI, please be sure to use proper caps for a specific issue about a command. This can help prevent confusion and sometimes you might find an alternative command that behaves in a useful manner. 

'w'ield is extremely important, and it's actually required to manipulate a lot of non-weapon stuff, be it carrying a heavy backpack so you can drop it rapidly enough to not get torn up by surprise enemies, figuring out how to pick up and move a 700 lb exodii robot chassis to a workbench for disassembly, or figuring out how to carry a 100L barrel to your car. You literally cannot do a lot of stuff without 'w'ielding it. 'G'rab is an already-existing feature which is also extremely important and used for specific other uses.

'w'ield also automatically looks at all nearby squares including where the PC is standing, which means you can just hit "w" and then '/' to filter to pull an item out of a car or several squares of clutter, and it automatically puts it first in the 'a'ctivate and reload lists which is very useful as well.

**Comment by LeahLuong** [comment]
@SummGai This seems more like an anti-feature request than a feature request. If I understand you correctly, you are saying the pocket system should be removed so that when you strip naked you can 'G'rab items w/ your hands in order to wield them.

Wow.

**Comment by WhitePaperWraper** [comment]
I'd like to see the 'g'rub automatically prompt me to 'w'ield & 'W'ear stuff too. This made it easier to move my treasures in the early game without relying on the less safe '\' hauling.
It was also simpler to 'g' - wield or 'g' - Wear an item if I know the tile it's laying on, as I wouldn't need to sort through 9 tiles potentially filled with loot.
I don't see why it would fundamentally conflict w/ the pocket system tho

**Comment by Mikenyes** [comment]
You can still do this.  Pressing 'w' while hovering an item when in the 'g' screen will wield it, same with 'W' and Wear.  It says so in a blurb at the top of the 'g' screen.
