### ISSUE TITLE
There is too much Z-level activity around labs to make a lab start playable on slower machines.

### ISSUE THREAD

**Issue by gmlacrosse** [CleverRaven/Cataclysm-DDA#54969]
### Describe the bug

If the character starts in a lab with a lot of z-level activity (i.e. multiple open portals and lots of units fighting near the portals) it makes the game unplayable. The player will be stuck on hours-long waits for things like crafting and sleep.

### Steps to reproduce

Start in a lab scenario.

### Expected behavior

Ideally, the player would have no extra wait time if there isn't too much z-level processing going on.

### Versions and configuration

Windows 10
Latest Experimental Build 1-30-2022

**Comment by LeahLuong** [comment]
This isn't so much a bug as a feature. Older versions allowed you to toggle Z-lvl processing off. Another alternative for sidestepping this issue is upgrading your hardware. Short of playing an older version, avoiding lab starts, or git gud PC, you're not going to see this problem solved anytime soon. Pretty sure the devs aren't going to rollback mandatory Z-lvl processing or whip up some new code process that is an order of magnitude faster.

On the bright side, old-style labs are on their way out & their replacements may be less Z-lvl intensive.

Please consider closing this issue when it doesn't get much more attention than I've shown it here.

**Comment by gmlacrosse** [comment]
I have a fast PC, graphics card, I7 CPU, lots of rams, and it was taking 15-20 mins per sleep cycle.  The problem isn't the mandatory z-level processing. Because it works fine in a city setting with 2-3 z levels. I believe the problem is caused by the multiple portals, nearby slim pits, and mi-go encampments all combine to create a massive number of units in a relatively small area around the portals. You see numerous exception messages about trying to put a monster where there is already a monster located.

**Comment by gmlacrosse** [comment]
I'm attaching an image of the ground floor at a lab after I used the debug menu to destroy all monsters.
![image](https://user-images.githubusercontent.com/3780675/151899219-0511dc27-7eca-4f56-8f30-639f56bae07d.png)

**Comment by gmlacrosse** [comment]
![image](https://user-images.githubusercontent.com/3780675/151899486-fc57c76f-0b60-4fae-b844-0670756e9206.png)

**Comment by Maleclypse** [comment]
I see you are experiencing a slimepocalypse, if I'm viewing that correctly?

**Comment by MochaModifier** [comment]
Is a 'slimepocalypse' still possible in the newer versions?

I'm on the cusp of escaping a lab and it's ever growing slow down issues - and made the mistake of taking a nap before leaving. I've been here for going on half an hour and still haven't woken up - and been googling around trying to see if there was any known reason why this was

![image](https://user-images.githubusercontent.com/38334602/158181404-1f578c81-05f9-4218-8b71-b6176c497925.png)
Game seems to top out about about 12% CPU utilization
![image](https://user-images.githubusercontent.com/38334602/158181640-c9b4a999-e17b-466e-bf52-59981cd7fe57.png)

**Comment by MochaModifier** [comment]
> Is a 'slimepocalypse' still possible in the newer versions?
> 
> I'm on the cusp of escaping a lab and it's ever growing slow down issues - and made the mistake of taking a nap before leaving. I've been here for going on half an hour and still haven't woken up - and been googling around trying to see if there was any known reason why this was
> 
> ![image](https://user-images.githubusercontent.com/38334602/158181404-1f578c81-05f9-4218-8b71-b6176c497925.png) Game seems to top out about about 12% CPU utilization ![image](https://user-images.githubusercontent.com/38334602/158181640-c9b4a999-e17b-466e-bf52-59981cd7fe57.png)

My god
![image](https://user-images.githubusercontent.com/38334602/158190556-b3514137-c4b0-4173-8acd-8502ab881466.png)
