### ISSUE TITLE
template issues, inventory from scenario character saved when character template is saved

### ISSUE THREAD

**Issue by SummGai** [CleverRaven/Cataclysm-DDA#54960]
### Describe the bug

so when you save a character as a preset character the scenario items (shirt, matchbooks etc) are saved even if you dropped them previous to saving the template. This can cause the character's inventory to become bloated with useless flotsam. It would be nice if the scenario items stopped spawning on the newly made preset character.

### Steps to reproduce

make a character.
save character from world.
spawn character in new world.
repeat a few times.
watch character's inventory bloat with items from the initial scenario design.

### Expected behavior

only the items the character had on them when they were saved should spawn when the character is created. That way the player doesn't have to deal with items they didn't want when starting a new game with their custom character.

### Versions and configuration

windows 10 (64 bit)

**Comment by LeahLuong** [comment]
I like how the title has "template issues" & you bear this out by showing you have issues using the bug report template. Please let us know what version of the game you are running. The "Steps to reproduce" are largely irrelevant w/out knowing the version to attempt reproduction on.
