### ISSUE TITLE
Game Crash on Siphoning Fuel Into Vehicle With Working Empty Tank, From Other Vehicle Tank

### ISSUE THREAD

**Issue by coyo7e** [CleverRaven/Cataclysm-DDA#54979]
### Describe the bug

Had this happen a couple times in a row today so I figured I'd report it as well as possible: tried to siphon fuel from a motorcycle tank to a Hybrid Car that had 0 fuel, and the game immediately crashes out with a seg fault. I drove back the same vehicle to the same location in slightly differing circumstances, tried again, same thing. Vehicle's smart controller is in good condition and off, vehicle was turned off. 

I fortunately had a gallon jug nearby and was able to siphon fuel into this usable container and then refill the vehicle from the container, successfully. After putting some fuel into a smaller container and putting it back into the motorcycle and then siphoning directly from the bike to the car with a now-partially-full tank, it works fine. My gut feeling was that the tank was empty and the smart controller or something was being funky, but the smart controller seemed to be turned off. After repeatedly experiencing the crash trying to siphon into an empty vehicle tank in either direction though, that fit my first gut feeling as well that it has to do with the tank container being fully empty.. 

Using a smaller container _(glass bottle that I drunk the beer out of)_ than the available fuel does NOT crash when siphoning from the container into the tank via "re'f'ill", nor did siphoning into either tank when it's already got the right fluid "primed" inside it to some extent, again it feels like something is wonky with the game getting screwy with the (liquid?) type in the empty container, somehow. Only other thing that's been noticeably odd this run I just started was that I put a cowboy hat into a mostly empty golf bag and got a "container has no usable pockets" type error and the hat itself completely vanished, never to be seen again. 

After emptying the car's fuel tank into the same bike _(with a gallon jug and/or smaller container followed by normal siphoning)_ and then re siphoning from the bike to the empty car, same crash. Trying to siphon all fuel from the car into the bike with a empty tank, causes same crash. For funsies and now that I had a solid save file nearby, I tried starting up the car and siphoning into its empty tank while it was driving, hoping the smart controller could figure out things and fix it, but got, same crash. The bike has a immobilizer on it and no electric motor/etc so I couldn't easily turn it on and try in reverse way with a non-hybrid vehicle.

Updated to most recent experimental as of this morning. I am standing near a burning building and getting some empty_air errors on and off but they seem entirely unrelated as things come crashing down.

I've provided save file standing between two vehicles with all items and stuff as I mentioned in inventory or nearby, after I was able to reproduce the crash a half-dozen times with the two vehicles, but it seems directly related to the tank of the target vehicle being totally empty and using the 's'iphon command directly into a nearby vehicle. I haven't tried with other vehicles because I haven't found any, and with a save file someone else can easily reproduce it right on the spot. Save should be totally playable from this point although I'm short on basic hand tools currently. Sorry that my character is drunk, I did it for science!

Good luck and thanks!

### Steps to reproduce

1. Spawn Hybrid Car and empty its fuel tank.
2. Attempt to siphon fuel into it via rubber hose and nearby vehicle.
3. Instant segmentation fault and hard crash.

### Expected behavior

Expected to successfully refill a working vehicle tank without any fuel in it, from a working vehicle tank that does container fuel.

### Screenshots

![image](https://user-images.githubusercontent.com/80022377/151879238-f2393e7d-81c4-488c-80cc-43473c2c2406.png)

![image](https://user-images.githubusercontent.com/80022377/151879200-fb6eae87-abda-4b4d-bbce-e6049aa229f3.png)

![image](https://user-images.githubusercontent.com/80022377/151879732-c8b92064-9d7b-40c9-bc2f-467c581faa21.png)

![image](https://user-images.githubusercontent.com/80022377/151879753-a867f651-c247-45fe-92a6-f5dabb65fbaa.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 272b7a4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7974494/crash.log)

[Bloomsburg - Copy.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7974587/Bloomsburg.-.Copy.zip)

**Comment by AcidAntOnAMinefield** [comment]
I have a similar thing happening to me but it happens when I examine a vehicle and I am not quite sure what leads to this.

**Comment by Lee-Adamson** [comment]
I confirm this bug.  Trying to fill an empty tank on an RV I just found crashes the game every time, regardless of what I try to put it in.  Crash happens siphoning, at gas pump, and when trying to (U)nload a container of fuel from inventory into vehicle.  Can provide save game if needed.

**Comment by Lee-Adamson** [comment]
Addendum:  When I roll back to 7684355, the bug disappears.  I have not tried any experimentals that may have been released in-between, though.

**Comment by coyo7e** [comment]
> I confirm this bug. Trying to fill an empty tank on an RV I just found crashes the game every time, regardless of what I try to put in it. Crash happens siphoning, at gas pump, and when trying to (U)nload a container of fuel from inventory into vehicle. Can provide save game if needed.
> 
> Devuan Gnu/Linux amd64.

Does it happen, specifically, when you 'e'xamine the vehicle and then re'f'ill the the tank from a container you're carrying or on the ground, rather than 's'iphoning or using pumps? It works fine when I use the re'f'ill method with a container.

**Comment by Lee-Adamson** [comment]
> Does it also happen, when you specifically 'e'xamine the vehicle and then re'f'ill the the tank from a container you're carrying or on the ground, rather than 's'iphoning or using pumps? It works fine when I use the re'f'ill method with a container from within the vehicle menu. I didn't even know I could 'U'nload liquids into a vehicle like that lol

No sir, (f)illing from the vehicle details screen appears to work as expected.

**Comment by Alex-Folts** [comment]
Could be related to this PR: https://github.com/CleverRaven/Cataclysm-DDA/pull/54387 it do something with vehicle tanks.

**Comment by coyo7e** [comment]
#54983 sounds super-similar as well. I'd be curious if the fridge in that post was empty but the whole fill/refill etc dynamic feels related

**Comment by VarrenKrytor** [comment]
Same issue here.

**Comment by Lee-Adamson** [comment]
> #54983 sounds super-similar as well. I'd be curious if the fridge in that post was empty but the whole fill/refill etc dynamic feels related to some sort of container/pocket logic going wonky when it's maybe not happy with what was already inside or not inside.
> 
> 54983 deffo caused a seg fault and instant crash to desktop which is the initial overall symptom here, as well as being on an identical update version.

For what it's worth, I've gotten two segfaults while trying to eat a sandwich contained in the RV fridge, in addition to the stuff with the tanks.  I can't seem to reproduce it reliably, though.
