### ISSUE TITLE
Using 'esc/q' to back out of the 'f'ire menu with some weapons passes lots of time without warning

### ISSUE THREAD

**Issue by VitreousEyes110** [CleverRaven/Cataclysm-DDA#54973]
### Describe the bug

With certain weapons, pressing 'f' to open the fire menu then pressing 'esc/q' to back out of/close the fire menu results in time passing without warning. The amount of time passed seems dependent on the movement point cost of removing the weapon's ammunition from the container it's stored in. In my testing for example, a quiver passed ~1 second whereas a short rope passed ~24. That amount of time passing without the player having a warning pop up, presumably when they were considering shooting a nearby enemy, could be lethal.

Tested with a few weapons:
- Short Bow - Bugged.
- Staff Sling - Bugged.
- AR-15 - Works fine.

### Steps to reproduce

1. Create a character, give them:
- A watch to see the exact time
- A short bow
- A quiver
- Arrows, inside the quiver

2. Wield the bow, spawn a zombie that can see the character.
3. press 'f', then 'esc/q', see time pass and the zombie move closer.
4. Swap the quiver out with the much slower to interact with short rope, and repeat step 3 to see a massive and dangerous amount of time passing.

### Expected behavior

Entering the fire menu, then backing out of it should cost no time, or at least have a warning before passing huge amounts of time.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 1607
- Game Version: 272b7a4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by coyo7e** [comment]
With the weapon types you mention it sounds realistic but not super intuitive/fun, yeah. Leaving an arrow nocked takes up at least one hand afterward though, while leaving a stone in a sling/staff sling is next to impossible.

Seems like a prompt option to drop the ammo on the ground while canceling would be the best option but would maybe involve extra code.

**Comment by SariusSkelrets** [comment]
For me, all the act of placing the arrow in the bow and firing should happen after pressing enter. Pressing "f"ire is wanting to shoot something and should be able to be cancelled as you simply changed your mind before even reaching for an arrow

Drawing an arrow could be influenced by reach time but that modifier should apply after pressing enter in the fire menu, not even before you choose your aiming

**Comment by VitreousEyes110** [comment]
In [src/activity_actor.cpp](https://github.com/CleverRaven/Cataclysm-DDA/blob/388d316c59b0ba34b08d180f3bb574f5b5168e1c/src/activity_actor.cpp)

    if( aborted ) {
        act.moves_left = 0;
    } else {
        if( !trajectory.empty() ) {
            fin_trajectory = trajectory;
            act.moves_left = 0;
        }
        // If aborting on the first turn, keep 'first_turn' as 'true'.
        // This allows refunding moves spent on unloading RELOAD_AND_SHOOT weapons
        // to simulate avatar not loading them in the first place
        first_turn = false;

        // Allow interrupting activity only during 'aim and fire'.
        // Prevents '.' key for 'aim for 10 turns' from conflicting with '.' key for 'interrupt activity'
        // in case of high input lag (curses, sdl sometimes...), but allows to interrupt aiming
        // if a bug happens / stars align to cause an endless aiming loop.
        act.interruptable_with_kb = action != "AIM";
    }

From the comment, it seems like it's explicitly intended to refund spent movement points and act as if the weapon was never loaded in the first place, assuming it's aborted on the very first turn. It just isn't working as intended.

Even in that system, if the player aims slightly with '.' then decided not to fire with 'esc/q', they would still experience possibly lots of time passing without an option to, presumably, drop the ammo instead of spend the time to unload it back into its original container.

**Comment by VitreousEyes110** [comment]
void aim_activity_actor::unload_RAS_weapon()
{
    // Unload reload-and-shoot weapons to avoid leaving bows pre-loaded with arrows
    avatar &you = get_avatar();
    item *weapon = get_weapon();
    if( !weapon ) {
        return;
    }

    gun_mode gun = weapon->gun_current_mode();
    if( gun->has_flag( flag_RELOAD_AND_SHOOT ) ) {
        int moves_before_unload = you.moves;

        // Note: this code works only for avatar
        item_location loc = item_location( you, gun.target );
        you.unload( loc, true );

        // Give back time for unloading as essentially nothing has been done.
        if( first_turn ) {
            you.moves = moves_before_unload;
        }
    }
}

The specific function that unloads RELOAD_AND_SHOOT weapons, explicitly tries to refund the movement points for unoading the weapon, but again must not be working as intended.

**Comment by VitreousEyes110** [comment]
I think the best solution would be:

- In the case of pressing 'f' them immediately pressing 'esc/q', all points should be refunded and treated as if the ammo was never loaded in the first place, as is apparently intended.
- In the case of pressing 'f', then aiming any amount resulting in time passing, then pressing 'esc/q', the player should be given a pop-up asking if they'd like to drop the ammo for no movement point cost, or place the ammo back in its original container with a displayed movement point cost.

I'd love to hear what ideas others might have.

**Comment by VitreousEyes110** [comment]
#54997 makes this issue redundant.
