### ISSUE TITLE
Monster attack that ages one year

### ISSUE THREAD

**Issue by LyleSY** [CleverRaven/Cataclysm-DDA#54971]
### Is your feature request related to a problem? Please describe.

N/A

### Solution you would like.

A new monster special attack that increments the players age by one year and prints the message "You feel a little older suddenly". Ideally with some mechanical game consequences for age I don't think exist yet. Seems like a good fit for flaming eyes, maybe others

### Describe alternatives you have considered.

N/A

### Additional context

Inspired by https://www.reddit.com/r/cataclysmdda/comments/sgv2pv/does_aging_kills_you_are_there_any_positive/

**Comment by SariusSkelrets** [comment]
The main problem would be simulating all what old age (or sudden aging) brings and when it start causing issues. Currently, I don't think age change anything in the game and that's fine

Also, an aging-inducing attack would mean something that you cannot heal from under any circumstance and that's another can of worms. For example, placing such an attack on flaming eyes would only create a "gotcha" enemy, as they were in the time they had lasers

**Comment by LeahLuong** [comment]
How would this feature interact w/ mutants?? Mice live short lives thanks to their fast metabolism while trees are on the other end of the spectrum. Would the aging attack scale based on mutation progress or would mutants already have some sort of lifespan factored in??

**Comment by robotic-gamer** [comment]
an alternative would be for it to occur standing outside in portal storms. by making it have an equal chance to lower your age by the same amount statistically speaking it would be effectively cosmetic.

**Comment by PatrikLundell** [comment]
Doesn't fit the game in my view. Magic effect could be placed in mods with magic.

I can't conceive of any way an attack could cause the effects of aging, as that's not the addition of a number to a meter, but rather the compound effects of telomere shortening (somehow causing cell division to fail more often), mitocondrial degeneration, DNA damage, and other form of cell and structure damages to the body.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
