### ISSUE TITLE
(Feature needed) Unrealistic lack of carrying ability with one broken arm

### ISSUE THREAD

**Issue by Silvenius** [CleverRaven/Cataclysm-DDA#54970]
### Describe the bug

I should be able to attach a shoulder strap to a gun on the ground with one arm, and/or be able to transport (but not wield) a rifle with one hand, assuming I'm strong enough. Or at least pick it up and carry it to the car, or drag it by the barrel or stock if I needed.

As it stands, I've crafted a shoulder strap but can't attach it or pick up the rifles on the ground to preserve them while I get fixed up. 

### Steps to reproduce

1. disable/break one of your two arms
2. try to pick up a rifle, fail
3. try to craft shoulder strap, succeed
4. try to attach strap to rifle on ground, fail

### Expected behavior

I would expect to realistically manipulate an object like this, particularly one so crucial to my character's survival

### Versions and configuration

latest experimental

**Comment by LeahLuong** [comment]
Have you tried 'W'earing the rifle from its position on the ground?? I believe you can do that if you have a back holster for it & it lacks a shoulder strap (or if it doesn't). Otherwise, use '\' to haul the item along the ground as you suggest in your post.

Please close the issue if you find my suggestion works.

**Comment by Silvenius** [comment]
The issue I described does not have to do with back holsters as an item unfortunately. If I have the use of only one hand, I should be able to close the grip of that free hand around the barrel of a rifle and at least drag it to a truck and put it inside.

**Comment by LeahLuong** [comment]
So backslash isn't working to haul along the ground??

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
