### ISSUE TITLE
Mansion Faction Camp Bed Bug

### ISSUE THREAD

**Issue by BattleToaster1** [CleverRaven/Cataclysm-DDA#54984]
### Describe the bug

The mansion Faction Camp will state it needs more beds for expansion when it is attempted but doesn't provide a way to build them. It does not recognize player made beds.

### Steps to reproduce

1. Expand enough times for it to require beds to expand further.
2. Expand your base through camp bulletin board.
3.  " You will need more beds before you can expand your base"
4.  No way to satisfy this requirement.

### Expected behavior

Be able to build beds.

### Versions and configuration

OS: windows
Os version:10.0 2009
Game version: 272b7a4 [64-bit]
Graphics version: tiles
Game language: system language []
Mods loaded:
Dark days ahead [dad]
Disabled npc needs
Bionic professions

**Comment by haveric** [comment]
I can confirm, but there doesn't appear to be any further functionality to mansion basecamps at this time. It seems to only allow the basic farming and foraging.

**Comment by LeahLuong** [comment]
Evac shelter famps gain beds by 1st building bedrooms & then furnishing said bedrooms thru the bulletin. If you lack those bulletin options, then haveric is prob correct that the mansion famp isn't fully implemented.

**Comment by PatrikLundell** [comment]
The faction camp system is designed to require two camp construction beds per expansion (rounded up), so if the camp doesn't provide at least 15 beds it can't make use of the full set of expansions. Note though that all current expansions require a field tile, so some or all of the possible expansion tiles of a mansion are probably taken up by the mansion itself (until someone makes mansion specific expansions).
It's possible to work around the bed/expansion restriction by having the recipes for the camp increase the number of virtually provided beds without actually making any.

**Comment by PatrikLundell** [comment]
Version 2 of the field base camp bypasses the requirements for beds to be allowed to start expansions as I didn't think it made sense. I may be quite happy to stay in my luxury RV while building expansions, for instance (in particular agriculture, as you want to get seeds into the ground as quickly as possible to be able to get a harvest as soon as possible). Thus, you probably used that version. As far as I know, that's the only base camp that does get rid of it, though.

I think it would be possible to make mansion specific expansions, but it may well be rather difficult. I'm not sure the mansion tiles have different designations that would allow you to tailor expansions to match the layout that's present in that particular tile. If they just say "mansion", any expansion could go into any of the eligible expansion tiles, and they probably don't have identical room layouts...

Looking at what different base camps provide is reasonably easy by looking at the files that describe them, but if you want to see how it actually fits with the locations you'll probably have to construct them.

If you want to help flesh out base camps you should select one you're interested in working with and improve that one, finally submitting what's called a Pull Request (PR) (which is weirdo language for "please accept and include this" used by Github). Once you've done the first one you can then determine which one you want to continue with.
Note that reviewers don't like giant submissions, so submit one improved/new base or one expansion at a time (and if you're constructing buildings out of different materials, split the submissions into one base with the first material and then a new one for each new material).

A hint is that the evac shelters are in need of some cleaning up regarding furniture left behind from the original, in particular version 2, which has lockers blocking some paths (so you have to drag them out of the way) to get through.

Also note that anything posted in the discussion boards is likely a waste of time: the core developers probably won't look at it until you've actually submitted a Pull Request, so only then do you have a chance to actually get some feedback.

**Comment by haveric** [comment]
@PatrikLundell Thanks. I am familiar with the git process already and have been doing minor PRs already. I'm hoping to improve everything about basecamps, not just expanding out an existing one, but I know that will be a giant undertaking. I'm starting with kevin's advice to audit the existing ones. Since you seem familiar with them, is there somewhere outside of here like discord that I can reach out to you to discuss more things in-depth?

**Comment by PatrikLundell** [comment]
I don't do asocial media, but I do look at The Drawing Board [https://discourse.cataclysmdda.org/c/game-talk/the-drawing-board/10](https://discourse.cataclysmdda.org/c/game-talk/the-drawing-board/10).
I'm happy to answer questions (that I can answer, of course) and provide advice (again, withing my capability).

**Comment by haveric** [comment]
@PatrikLundell I'd like to avoid bloating this discussion here any further. Is there somewhere better that we could communicate directly rather than a forum or issue format for further discussion?

**Comment by PatrikLundell** [comment]
Not really. A forum topic won't be cluttered, though. There's very little interest in this kind of things.

**Comment by LeahLuong** [comment]
IDK if BattleToaster1 will appreciate your filling up his thread w/ off-topic discussion. This repo does have a "Discussion" tab (found above) & it would behoove you to start a topic there rather than continuing here if you are not going to address the issue @ hand.

New discussion topic creation is restricted to project devs so you will likely need to make a new thread here ("Issues") & put "Discussion" in the title. Make sure to request the "Suggestion/Discussion" tag & ask that your thread be moved to the other section.

**Comment by Maleclypse** [comment]
> IDK if BattleToaster1 will appreciate your filling up his thread w/ off-topic discussion. This repo does have a "Discussion" tab (found above) & it would behoove you to start a topic there rather than continuing here if you are not going to address the issue @ hand.
> 
> New discussion topic creation is restricted to project devs so you will likely need to make a new thread here ("Issues") & put "Discussion" in the title. Make sure to request the "Suggestion/Discussion" tag & ask that your thread be moved to the other section.

I'm pretty certain the discussions tab is closed to non-members.
