### ISSUE TITLE
Crash-To-Desktop When I Put Something in the Fridge

### ISSUE THREAD

**Issue by hopefulruins** [CleverRaven/Cataclysm-DDA#54983]
### Describe the bug

Playing around with the new electrical grid system, my game crashes to desktop when I put something in the fridge. The error I receive is attached below.
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7975315/crash.log)
 

### Steps to reproduce

1. Set up an electrical grid
2. Attach a fridge
3. Attempt to place food inside using the "fill tank" option
4. Crash

### Expected behavior

I assume that the fridge should not cause a crash to desktop with a segmentation fault. But it does. 

### Screenshots

![Capture](https://user-images.githubusercontent.com/98789641/151900916-322d7701-b128-4dc6-a4d3-3c6e3b80b253.PNG)

### Versions and configuration

Latest version (272b7a4)

**Comment by LeahLuong** [comment]
@kevingranade It looks like #54387 may be @ the root of this issue & #54979, based on its description & timing.
