### ISSUE TITLE
screenshot shortcut

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#54981]
### Is your feature request related to a problem? Please describe.

the inability to take screenshots using in game controls of anything but the default view.

### Solution you would like.

a by default unbound key that takes a screenshot.

### Describe alternatives you have considered.

leaving as is

### Additional context

this could be useful for taking screenshots of things like the crafting menu. using the windows screenshot short cut is inconvenient because it leaves in non-game related things in (in the extreme case with multiple monitors it includes the other monitor).

**Comment by coyo7e** [comment]
FYI if you hold the Alt key when using the built-in windows screenshot "PrintScreen" button (ALT+PrtScreen), it will only screenshot the currently active window. 

This includes being friendly to multi-screen monitor setups as well as pop-up crashlogs etc, and can save the work of cropping images via Paint, etc. I use this all the time while watching a movie on my second monitor with one or more than one application running in another window fullscreen or not, which I wanna copy, or to only copy the currently active window to clipboard.

**Comment by ZhilkinSerg** [comment]
`Win`+`Shift`+`S`

**Comment by robotic-gamer** [comment]
noted. I'll go ahead and close this. though including it in key binding would make the feature easier to find as that is the go to to finding how to do something.

**Comment by ZhilkinSerg** [comment]
Taking screenshot is a functionality that should not be really part of the game - it is up to operating system or dedicated software to make screenshots.

**Comment by LeahLuong** [comment]
@ZhilkinSerg What about removing the IG functionality for screenshotting?? It's kind of a joke & I found it to be a red herring when trying to get a relevant capture myself.

**Comment by ZhilkinSerg** [comment]
> @ZhilkinSerg What about removing the IG functionality for screenshotting?? It's kind of a joke & I found it to be a red herring when trying to get a relevant capture myself.

I am not really sure what are you talking about. What's IG?

**Comment by LeahLuong** [comment]
@ZhilkinSerg IG = In-Game. Screenshotting from there captures only 1 screen (main game) that humorously features the very option to screenshot front & center.

**Comment by coyo7e** [comment]
> @ZhilkinSerg IG = In-Game. Screenshotting from there captures only 1 screen (main game) that humorously features the very option to screenshot front & center.

Interesting point, I haven't checked the keybinds but if screenshot isn't a feature in every submenu's keybind list, it would make sense that it's actually nonexistent in most contexts in-game.

I used to write lots and lots of small how-to guides for basic computer-related tasks so learning to use the niche features of the basic on-keyboard screenshot button taught me a ton, to the point I often wonder why so many games include their own screenshot key that often is a lot more annoying than the basic "copy image to clipboard" functionality that the normal one uses.

There are a lot of farticles written online about how to take screenshots, which point to third party software or obscure stuff like using the windows gamebar
