### ISSUE TITLE
another segmentation fault

### ISSUE THREAD

**Issue by Devengel** [CleverRaven/Cataclysm-DDA#54991]
### Describe the bug

Segmentation fault appears when pressing f while examining the deathmobile you're in

### Steps to reproduce

1.Download the save below(very light)
2.open the save in the game.
3.examine the deathmobile you're in
4.press F
5.Segmentation of doom appears.

### Expected behavior

The ability to be able to fill containers installed on the vehicle without the game crashing

### Screenshots

![image](https://user-images.githubusercontent.com/71761521/151966643-616121be-426a-43c1-93d9-87284c2e6538.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 272b7a4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Mythical Martial Arts [MMA],
    Graphical Overmap [Graphical_Overmap],
    Blaze Industries [blazeindustries],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7978301/crash.log)
[Cedar Hill.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7978303/Cedar.Hill.zip)

**Comment by Devengel** [comment]
update: i think this PR  #54987 fixes the issue?

**Comment by LeahLuong** [comment]
@Devengel You are likely right; this appears to be in the process of getting fixed & should be alright in an impending release.

Hopefully, linking the PR will get this 1 to automagically close when that completes. Please close this issue if it doesn't & the issue resolves in a new experimental.
