### ISSUE TITLE
Skin Tones Block Mutations

### ISSUE THREAD

**Issue by OmniscientQ** [CleverRaven/Cataclysm-DDA#54992]
### Describe the bug

The basic skin tones available at character creation cannot be overwritten by mutations that carry the 'skin_tone' tag, even when selecting them from the debug menu. The mutations Phelloderm and Demon Skin both have this tag, and they will overwrite one another just fine, but the 'natural' ones are immune to being overwritten.

### Steps to reproduce

1. Make a new character with any skin tone.
2. Attempt to mutate Phelloderm, either with serum or the debug menu.
3. See no change.
4. Remove the natural skin tone.
5. Try to mutate Phelloderm again.
6. Profit.

### Expected behavior

The skin tone traits should be like any other starting trait - over-writable, but you can purify your way back to them if you want.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.3 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-5739-g1d4f46406d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Stats Through Skills [StatsThroughSkills],
    Disable NPC Needs [no_npc_food],
    Bionic Slots [cbm_slots]
]

**Comment by LeahLuong** [comment]
Huh, playing 0.F-3, I'm pretty sure I got a message log entry telling me I lost my skin tone when I 1st gained Phelloderm. I kept doing mutagenic serums & subsequently lost Phelloderm & don't recall regaining the skin tone.

Is there a way to check skin tone?? I don't think NeoDays displays skin tone & I never gave it much thought until seeing this thread.
