### ISSUE TITLE
Eating too Much Candy/Soda Pop and other High-Sugar Junk Foods Etc, Should Cause Nausea, Vomiting, etc.

### ISSUE THREAD

**Issue by coyo7e** [CleverRaven/Cataclysm-DDA#55001]
### Is your feature request related to a problem? Please describe.

I have been wondering this for a while, but why do some foods reduce the happiness gain incrementally (often by a lot) over subsequent "doses", while some stuff like candy, chocolate bars, etc, never reduce the happiness gain, or cause any ill effects at all outside of potentially ending up overweight/obese? Vitamin deficiencies seem to take so much time that I don't think I've ever actually had it happen to a character I was playing - but I tend to occasionally eat a gummy vitamin in the game as they provide a happiness bonus.

Drinking 1 dose of willow tea or consuming many foods or drugs in the game causes instant nausea, often without even notifying the player, but I can live on nothing but pure sugar or chocolate and gummy candies for weeks and my character is totally fine with it. 

I would dare someone to like, sit down and eat 20 pixie stixx in a row IRL and not feel pretty poorly afterward _(I would literally rather try the "Cool hand Luke" bet where the guy eats 50 eggs in a row, https://www.youtube.com/watch?v=k3oMPqUTxCE , than eat a huge number of pixie stixx, due to previous experience with overdoses of candy)._ Eat nothing but candy for a few days running and you will feel rather poorly IRL, you would probably feel as bad or worse than if you consumed nothing but beer/wine/etc for several days running because at least beer has some wholesome ingredients rather than pure empty calories and chemical flavor enhancers.

### Solution you would like.

I feel that eating large numbers of high-sugar foods should cause some temporary ill effects. Eating from a different "stack" of the same type of food, should always reduce happiness gains as if they were all from the same stack, despite some (junk-) food items seeming to be immune to this in-game.

### Describe alternatives you have considered.

Leave it the way it is, where most foods lose happiness gain after more than one subsequent dose, and candy can be eaten forever, even without "Sweet Tooth" or similar mutations.

### Additional context

I recall that once as a small kid, I ate all my Halloween candy in one sitting because my parents didn't take it away from me, and I got pretty nauseous and ended up puking all over the place and being sick all night with a "sugar high" that involved nausea, sweats, shivers, etc. It was rather unpleasant, and I ended up being unable to eat some kinds of candy for years afterward because I'd made an unconscious association between my sugar overdose, the nausea etc, and certain kinds of candy.

I also ate a whole bottle of "Flintstones" vitamins as a kid and felt pretty gross for a while, although I didn't get super ill from it or jaundiced or anything.

----

As an aside, I noticed that some kinds of foods will only reduce in their 'happiness gain' per "dose", if they're in the same stack/wrapper. IIRC things like crackers that - often but not always - come in one-dose packaging can be eaten in succession without a reduction of happiness gain as long as you eat from a different "stack" of them. This is pretty easy to abuse.

**Comment by oosyrag** [comment]
Sugar high as a debuff sounds like a pretty solid idea. Maybe a less intense version of adrenaline rush. Or existing debuffs with varying durations could be used like adrenaline, shakes and nausea, although I would hope the intermediate side effects would discourage consuming enough sugar to get to nausea and vomiting. The fullness system is probably enough to cover that.

Going through all the foods to add a high-sugar tag may be tedious though, as well as defining what exactly constitutes as high-sugar, which could be somewhat subjective.

**Comment by CalKerethi** [comment]
I bet this could be implemented pretty cleanly with existing mechanics by using the vitamin system, similar to toxins. It wouldn't save the change author from having to go through every food, but it would provide a much more objective way to define high or low sugar items. Mutations could increase or decrease your tolerance by playing with the absorption and elimination numbers.

Ideally it would only come into play for the short-term sugar high/crash debuff suggested above, because tracking the long-term effects of sugar on the body wouldn't be fun for the player or the developer. A diabetes starting trait that makes you manage your blood sugar more carefully, on the other hand, might be kind of cool for a challenge?

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
