### ISSUE TITLE
electric shock alarm

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#55000]
### Is your feature request related to a problem? Please describe.

heavy sleeper not hearing the alarm.

### Solution you would like.

a device that your prompted to turn on when going to bed. in the event of a loud enough noise (like your alarm) it shocks you causing minor pain and waking you up.

### Describe alternatives you have considered.

a shock device in place of an alarm for a normal device with an alarm clock feature.

### Additional context

It could be constructed easily by hooking up a microphone (electronic scrap) to an amplifier that then is set up to shock you.
Drawbacks would be it consuming power per activation and minor pain.
It could also be used with glass shards or bubble wrap to make a more effective alarm when sleeping

**Comment by Zireael07** [comment]
A vibrating alarm clock like the ones used IRL by the hearing impaired would also solve the problem.

**Comment by coyo7e** [comment]
OP: fyi the "Heavy Sleeper" trait also increases the amount of pain required to wake the player, iirc.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
