### ISSUE TITLE
Un-explained shift during update map 

### ISSUE THREAD

**Issue by bombasticSlacks** [CleverRaven/Cataclysm-DDA#55003]
### Describe the bug

In the isolated artisans base which is surrounded by spike pits if you invoke a mapgen update while in Jays house you can end up in a spike pit and take the damage because of the shift at https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/mapgen.cpp#L7625. 

Alright it's not the shift that is the problem and I'm working on solving it. 

### Steps to reproduce

Trigger a map update. Like using the code in #55002 while standing in the locations in the image provided.
Note you take damage
Then are back to your original position

### Expected behavior

Not teleport into a spike pit during a conversation

### Screenshots

Danger zones
![image](https://user-images.githubusercontent.com/4514073/152050003-8b32b050-c077-437a-8c14-0cc43115f4c4.png)

Call Stack When you get SPIKED
![image](https://user-images.githubusercontent.com/4514073/152050048-ca257dc2-c7c1-4686-8128-4ebbc9d4aee3.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-5739-g1d4f46406d-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by jbytheway** [comment]
The code you've linked looks like a hacky workaround for the long-standing issue of updating the map within the reality bubble and the strange side-effects that induces. One would probably want to look back at when that code was added and why to learn more.
