### ISSUE TITLE
New NPC DEBUG message observed

### ISSUE THREAD

**Issue by Headjack** [CleverRaven/Cataclysm-DDA#5501]
I'm no stranger to "Failed reload" or so-and-so tried to eat a lighter, but a new one to me showed up. "Megan Bennett tried to use item with null invlet". This was immediately after trading them some Methamphetamine, so she may be trying to use it.

**Comment by illi-kun** [comment]
This should be closed since BevapDin modified code responsible for using invlets by NPCs (see PR mentioned above).

**Comment by mugling** [comment]
Agreed

**Comment by Headjack** [comment]
Megan thanks you, she's done well in rehab over the last two years.
