### ISSUE TITLE
Can seal everything

### ISSUE THREAD

**Issue by Jarewill** [CleverRaven/Cataclysm-DDA#55013]
### Is your feature request related to a problem? Please describe.

Currently the can sealer item works as a tool for crafting recipes.
Those cover a lot of possible items, such as canned meat, but it doesn't have everything.
It would be really nice to be able to put anything into a can and use the item to seal whatever was put inside.

### Solution you would like.

(a)ctivation menu for the can sealer item that allows the player to select any tin can and seal it with it's contents.
Idea on how it would work:
- Player puts some food / drink inside a tin can.
- Player (a)ctivates the can sealer and selects the tin can with the food they want to seal.
- Can sealer checks if the player has some scrap metal (as that's what the recipes use) and if they do, seals the item within the can.
- Sealing takes some time. (4 minutes maybe?)

### Describe alternatives you have considered.

Keep using the current crafting method, but I feel it's very limited.

### Additional context

When I noticed my soup was about to spoil, I thought about sealing it in a can.
I crafted the can sealer item, poured the soup into some medium tin cans and tried to seal it, but I was unable to.
The crafting recipes for sealing the soup involved crafting it from scratch and didn't accept the already made item.

**Comment by coyo7e** [comment]
While a cool idea, re-sealing food doesn't really make it last forever unless you're really lucky. You'd need to re-"pasteurize" it first and even then there would be drawbacks, like potentially losing nutrition value etc. Honestly it's way more feasible to just freeze stuff like that although again, there are drawbacks like the vascular material breaking down so it gets mushy (which is already in-game)

Even a jar of pickles can get gnarly if you stick a dirty hand inside the jar and touch the brine or side of the jar etc. Commercial brines are crazy-high in salt and acidity but they can and will go bad even while refrigerated. Home pickling and fermenting can be mildly dangerous in terms of catching food poisoning if you don't know what to watch for or just get unlucky and a few microbes waft into a container while it's within the "danger zone" temperature wise.

**Comment by Jarewill** [comment]
Ah, I see.
I guess that means this feature request falls flat on it's face.

I don't know if I should close it now, or maybe wait a bit and see what others have to say about this.
Though what you said has pretty much debunked the idea of using the can sealer like that.

**Comment by coyo7e** [comment]
Sorry to be a Debby-Downer, I've gotten food poisoning, worked in food service on and off a few times over the years, and food safety is really a hazy thing where it's "better safe than sorry" almost always.

Te alternative would be to add a random chance that any cooked/found/prepared foods have a chance to make the character ill, and if you've ever played RimWorld, you know that food poisoning is un-fun and can literally ruin a playthrough, and that it's almost impossible to avoid if there's any chance at all of it happening in-game, lol

**Comment by Jarewill** [comment]
I think points against this feature have been raised already, using the can sealer in such way doesn't make sense.
At least I learned something about food today!
