### ISSUE TITLE
Advanced Inventory Management(AIM) - You cannot transfer items from within a container inside your inventory

### ISSUE THREAD

**Issue by martosss** [CleverRaven/Cataclysm-DDA#55020]
### Describe the bug

In the AIM, when I select a container, I can't use the "C" button to open that container and manipulate(view/sort by .../drop/use/wear...) the items inside. Containers act as a single unit of storage although there is a "C" button that supposedly opens the container and lets me acces its contents.

I also tested with different containers(experimental version only):
- wielded canning pot or any other pot that contains another item(or another container inside) allows me to click "c" and displays an empty menu and says "invalid container" when it opens the contents.(experimental version only)
- a duffel bag in my inventory or on the ground that contains a random pot also cannot show the c menu (experimental version only)
- It might work for some random containers, or with liquids? I've seen it work, so I'm not sure when exactly it breaks, but it breaks most of the time.

### Steps to reproduce

1) give yourself a pair of jeans, a plastic bag and a piece of paper.
2) Wear the jeans => put the paper and plastic bag inside your inventory so that they're stored inside your jeans => insert the paper inside the plastic bag using the inventory or the AIM menu(either works, the important part is that the paper is now stored inside the plastic bag, which, in turn, is stored inside your jeans ... I expect you have enough storage for both items and some extra, Being naked would be an exception that I don't want to discuss, as then you don't have any place in your inventory to store other items and things get trickier)
3) Now open the AIM menu and on one side select the plastic bag that contains the paper and on the other side of the menu select the ground beneath you.
4) You cannot use the "C"(container) option to access the paper inside the plastic bag and throw it on the ground. The "C" option is unavailable??? If you try typing "c" You get a prompt "You can't put items in there", as if that place doesn't exist.

### Expected behavior

A) The "C" button is available for any container in my inventory or that I am wearing - bags, backpacks, clothing, etc
B) I can use it to view items inside that container and sort them by category/weight/volume/etc.
C) I can transfer some items to a tile around me or to my inventory(between that container and the inventory, in effect unloading that item from that container)
D) I can transfer items between 2 containers that are either in my inventory or in my direct surroundings. Currently that's not possible at all.

D.1   ) If on 1 side of the menu there is a container that is part of my inventory, then 
D.1.1) taking an item from there is counted as unloading + 2nd action to move that item somewhere?
D.1.2) putting an item inside is counted as inserting that item in that container?

D.2   ) If on 1 side of the menu there is a container that is on the ground, then
D.2.1) taking an item from there is counted as unloading + 2nd action to move that items somewhere?
D.2.2) putting an item inside is counted as inserting  that item in that container - so you "drop" the item in that tile and then you also count an "insert" operation for that container?

I'm not sure how the game currently treats (unloading an item from a container) vs (wielding an item) - maybe wield = unload + grab ? ... or ...  unload = grab + store in inventory? In any case, one of those options should be chosen in the place of "unloading" in cases D.1-D2, so your hands might have to be free to perform those actions?

### Screenshots

![image](https://user-images.githubusercontent.com/7064677/152179056-994dcc63-ee4f-4a16-9ef1-ef63a860d052.png)
![image](https://user-images.githubusercontent.com/7064677/152182652-e67aeb90-a53b-410a-984f-c8f1712e9fde.png)

### Versions and configuration

Windows 8.1
Game version - Tested both on experimental(2022-01-31-0804) and Stable(0.F-3) branches
Graphics - tile
Ingame language - English - the default
Mods loaded - the default, both my original scenario in the Stable version and the test in experimental:
>>Dark Days Ahead [dda]

**Comment by Je55eah** [comment]
I have seen that usually the items in my containers and nested containers are listed in my inventory. That's fine, but it isn't always obvious which container the item is in. It isn't clear to me when the "C" function works or what it is designed to target. Perhaps after the user presses "C" they might be allowed to select a container from the interface which "i""i" loads. The "i""i" interface is very handy and it would be useful if every container in that list could get a function to mark it as the "active left/right AIM container" and open the AIM with that container in the left or right pane. I'm not sure if those keys are already used on that screen, but the "/" and "\" might be good options. Then "c" would open the "i""i" container inventory and "/" or "\" would go back to the AIM. 

It would also be useful for this purpose and in general, if the "i""i" container menu included containers that were around the character on the ground, in lockers, and even on NPCs.
