### ISSUE TITLE
Allow comparing (recipe result) with (inventory item)

### ISSUE THREAD

**Issue by martosss** [CleverRaven/Cataclysm-DDA#55023]
### Is your feature request related to a problem? Please describe.

Use case - you browse recipes and find an item that you think looks nice(say a bag with 5 pockets, or a helmet, or a weapon) ... It's nice to be able to compare it to your currently equipped item or to be able to open inventory and browse your items without losing your selected recipe(and filter) view.

Currently I have to open recipes and dig through it to find the recipe I need, then close the window, open my inventory and look at an item that looks like the recipe, then close inventory, open crafting again, use filtering / browsing to find the recipe again and decide  whether i want to craft it ... or do that multiple times if I forget some stat in the meantime.

### Solution you would like.

Implement the "compare items" option inside the crafting menu to compare the description of the recipe result with another item's description:

option 1) When you select a recipe and press a button, say the default compare items[I}, you open the comparison window where you have to choose one of your items that you wish to compare with the recipe, the same way like the comparison window works, however, the recipe is automatically selected and you only need to select another item to compare it with

option 2, harder to implement?) When you click "compare recipes", a window pops up where you select 2 items among all recipes and your inventory that you wish to compare, potentially being able to compare even 2 recipe items?
+ adds more functionality
- the list of options will be huge, you will definitely need a good filter to choose items quickly

option 3) same as 2, but instead of all recipes, select only the current list of selected recipes, be it from a category or from a filter. That will limit the list and make it easier for people to choose either 2 recipes or a recipe + item from inventory. The list of all recipe items will be displayed as a separate category "recipe"

### Describe alternatives you have considered.

- screenshot the recipe ? But if the resulting description is too big and needs scrolling even that alternative may be too cumbersome
- google the item in the background  in the hitchhiker's guide or in the wiki or in the game code ... cheating, and the game shouldn't require me to use additional software to play it, it should be self-sufficient.
- use the debug menu and spawn the recipe item and compare it with my inventory and then delete it ... cheating ... and if I'm going on that path I might as well spawn all the items I need and forget about crafting

- add recipe as favorite - I just thought of that while I was writing this ... this could help with finding the recipe faster ...
!!! However, if I'm using the favorites menu already and it's full of items, then this approach would be problematic, as I would still need to find the recipe in the list of favorites
!!! if I'm looking at a category of recipes that I want to choose from, so I'm trying to choose between 2-3, or 10 recipes, then favorites doesn't really help with that.

**Comment by morthein** [comment]
I would like to suggest adding this same feature, if possible, to an npcs armor as well. It would save some time not having to do all the same as described above.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
