### ISSUE TITLE
CRIT Expansion Mod: CRIT Automatic Rifleman Profession starts without pants 

### ISSUE THREAD

**Issue by KeaneCarotenuto** [CleverRaven/Cataclysm-DDA#55043]
### Describe the bug

The specified profession only has boxers, and no pants and/or protection on.

### Steps to reproduce

1. Have CRIT mod installed
2. Start game as "CRIT Automatic Rifleman"
3. Notice lack of pants

### Expected behavior

Profession has some kind of pants.
e.g. Army Pants, CRIT pants, Cargo Pants, etc

### Screenshots

![image](https://user-images.githubusercontent.com/16412361/152271174-0122116d-2e2f-4090-9ce2-7cd7ff2d9b2e.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    DinoMod [DinoMod],
    More City Locations [cityside],
    Magiclysm No Class Limit [magiclysm_no_class_limit],
    Useful Helicopters Experimental [useful_helicopters]
]

**Comment by jeanpaulrsoucy** [comment]
Would changing the profession name to "Commando" be an adequate fix?

**Comment by KeaneCarotenuto** [comment]
Get rid of the boxers too, throw in a little joke in the description, and I'd be ready to mark this as solved 😄

**Comment by KeaneCarotenuto** [comment]
I will try and fix this issue myself. Should be a good intro on how to contribute :)

**Comment by KeaneCarotenuto** [comment]
#55057 
I made the required changes, and sent a pull request. I'm not entirely sure I have done this right.

**Comment by LeahLuong** [comment]
@KeaneCarotenuto Good work on the PR! Only 1 step left to completion. There are many threads w/ the "Good 1st Issue" tag like this that new contributors can help out w/ just as you have.
