### ISSUE TITLE
brandied fruit

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#55040]
### Describe the bug

brandied fruit when consumed results in no alcohol intoxication. Consuming it in excess however can cause alcohol addiction.

### Steps to reproduce

consume brandied fruit observe affects

### Expected behavior

either brandied fruit causes all or none of the affects of consuming alcohol.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 372311f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    No Hope [no_hope],
    Stats Through Skills [StatsThroughSkills],
    Bionic Slots [cbm_slots]
]

**Comment by morthein** [comment]
From a quick look online, it seems the brandied fruit would be alcoholic until it was cooked into something, in which the heat removes the alcohol (it states it burns away the alcohol when baked in a cake or such).  So I suppose it could intoxicate, but when used as an ingredient that requires something like a fire, it can't/shouldn't cause that effect.

**Comment by robotic-gamer** [comment]
the issue is I find it most convenient to just eat brandied fruit as is because other then the hidden alcohol addiction risk the stats for it are decent. I prepared the stuff because I was hoping for a preserved form of fruit for the winter that did not have a limited shelf life. the bug is really the alcohol addiction risk without any alcohol intoxication when consumed. this can lead to players eating it in large quantities thinking its safe and only learning of their mistake when they start suffering alcohol withdrawal.

**Comment by LeahLuong** [comment]
Suggested workaround until this issue is addressed: get a food dehydrator to preserve fruit instead of using alcohol.

**Comment by Maleclypse** [comment]
Brandied fruit should give full effects of alcohol unless it's been used in making some other recipe where the alcohol is cooked out. But brandying preserves the fruit by submerging it entirely in alcohol so it would make sense to have alcohol effects.
