### ISSUE TITLE
Innate Weaponry Techniques??

### ISSUE THREAD

**Issue by LeahLuong** [CleverRaven/Cataclysm-DDA#55041]
### Describe the bug

Here's a screenshot of me getting what I believe is a Brutal Strike technique proc from my Mandibles mutation:

![Screenshot_20220202-082932](https://user-images.githubusercontent.com/91638992/152266977-e0b95668-7ffc-4e9f-aec4-eda7d6e1ce4f.png)

I don't believe Mandibles has that technique nor that small slimes have a vulnerability to getting knocked back on their own. My char is wielding a nodachi which does have Brutal Strike & I believe the technique may be getting carried over. That or this is some weird corner case where a mixed up order of operations applied my sword's technique but the sword didn't get to apply its damage because the Mandibles had already killed the target. Either way, this effectively gave Mandibles Brutal Strike & seems like a bug.

It makes me wonder whether other weapon techniques can be passed on to mutation procs.

### Steps to reproduce

1. Wield a Brutal Strike weapon.
2. Attack w/ Mandibles.
3. ???
4. PROFIT!

### Expected behavior

I expected that Mandibles level would increase, because all other skills can increase in level.

### Screenshots

See above.

### Versions and configuration

Android 0.F-3 Tiles English vanilla

**Comment by Venera3** [comment]
Yes, mutation attacks are an on-top proc that happen before the normal tech does, do their own damage instance(s) and print their own message.

**Comment by LeahLuong** [comment]
@Venera3 In that case, shouldn't the Brutal Strike not have happened?? I'm happy to close this if it's intended behavior but it seems buggy to me.

I'm noticing now the attack used the nodachi's normal attack speed but prob shouldn't from a gameplay perspective. Had this happened w/ Wide Strike & an adjacent enemy, I suppose I'd be happy the attack applied to the neighbor. Still, I'd be happier if the mutation proc was simply a simultaneous attack that uses a small amount of moves; if the Mandibles kill an enemy, there shouldn't be a follow-thru attack.

By the way, how does the mutation proc work w/ Ninjutsu's Sneak Attack?? I haven't noticed any differences in the message log but it would suck if it's applying the damage buff to such a small attack that takes priority.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
