### ISSUE TITLE
[(] Disassemble menu closes after you disassemble a single item

### ISSUE THREAD

**Issue by martosss** [CleverRaven/Cataclysm-DDA#55058]
### Describe the bug

In the "Disassemble item" menu, when you disassemble an item, the menu closes.
This means you have to open it and scroll back to the previous place where you were in case you want to disassemble multiple items

### Steps to reproduce

1. Open the disassemble menu, default is "("
2. Disassemble a single item
3. The menu closes, not allowing you to continue disassembling where you left off.
- This is especially an issue later in game when you have multiple candidate items for disassembly and you have to scroll each time to reach the last position.

### Expected behavior

**The [(] Disassemble menu in step (3) stays open and focused** on the same line where you previously were, allowing you to scroll slowly through it and disassemble all items in your direct vicinity with ease.

This **behaviour is already present for the [E]at menu** and it's awesome - you can eat multiple items on one sitting without having to open the [E]at menu 5 times and scroll down to whatever you wanted to eat before.

**All management menus should have a "management" behavior**, where they stay open and allow you to continue managing that part of the game, disassembling items in this case.

### Screenshots

![image](https://user-images.githubusercontent.com/7064677/152327255-deb7925a-04c2-4e80-98cb-927ea27ec4bd.png)

### Versions and configuration

Windows 8.1 64 bits
tested both on Stable(0.F-3) and experimental|(x64-2022-01-31-0804)
Tiles
English
default mods(dda)

**Comment by coyo7e** [comment]
This behavior bothers me a lot as well because it can make something as simple as taking apart 4 pieces of string in a row, an arduous task in terms of opening the menu, scrolling to the item, taking it apart and then repeating for each subsequent item.

Some Items seems to already have an expanded interface (like cloth clothing parts iirc) that allows you to immediately choose how many of the stack you want to take apart, but it's super rare for that feature to work on anything but a handful of seemingly very explicit items.

**Comment by martosss** [comment]
To be honest, I've found a "workaround" solution, which is to pick up the items that I want to disassemble, say 20 spoons, and then open Advanced inventory management(AIM) menu, then activate caps lock, then go to spoon and hit E => D ... that way you stay focused on the spoon and can disassemble multiple ones.
- The problem is that I can't easily figure out which items to pick up for disassembly.
Usually I'd like to see the resulting ingredients that I'd get and how long it takes for the disassembly process. For example Disassemble only clothing that gives you Lycra and takes relatively little time(say 1 hour, not 6-8).

This change would combine those three ways to organize things - by materials, time needed and number of items to disassemble, so I think it's the right thing to do.

**Comment by a-chancey** [comment]
As a workaround for now:

I drop all the items I want to disassemble onto my current square and use the (B)utcher menu to disassemble
