### ISSUE TITLE
There's no way to set custom hotkeys for the [e]xamine menu

### ISSUE THREAD

**Issue by martosss** [CleverRaven/Cataclysm-DDA#55056]
### Describe the bug

when you select an item in your inventory and click [e] to examine it, there's no way to change the hotkeys of the different actions for this item, say to [D]isassemble, or [d]rop, or [w]ield etc

### Steps to reproduce

1) open inventory, or AIM
2) scroll to an item in your inventory
3) press "RETURN"(inventory) or "e"(AIM menu) to open the [e]xamine menu(that's the default key, you might have changed it)
4) in this menu there's no way to change hotkeys for different actions that can be performed with this item

### Expected behavior

When I open the hotkey bindings menu with "?" on step 4 I expect to have the different actions listed as 
- candidates for hotkey change,
- also as to show me what actions I can perform from that menu, purely informative for noobs

### Screenshots

![image](https://user-images.githubusercontent.com/7064677/152323633-b310a284-8afb-48b6-9fc7-3e24af1a5707.png)

### Versions and configuration

- Windows 8.1 64 bits
- tested both on Stable(0.F-3) and experimental|(x64-2022-01-31-0804)
- Tiles
- English
- default mods(dda)

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
