### ISSUE TITLE
mx_sewer_mntS missing mapgen flag

### ISSUE THREAD

**Issue by k4gi** [CleverRaven/Cataclysm-DDA#55050]
### Describe the bug

mapgen is giving me another error about these ERASE_ALL_BEFORE_PLACING_TERRAIN and ALLOW_TERRAIN_UNDER_OTHER_DATA flags.

### Steps to reproduce

?

### Expected behavior

going by the IDs mentioned, maybe ALLOW_TERRAIN_UNDER_OTHER_DATA is the right one in this case. But I'm not familiar with these map tiles

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 689dfa5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

`ERROR : src/mapgen.cpp:2573 [virtual void jmapgen_terrain::apply(const mapgendata&, const jmapgen_int&, const jmapgen_int&, const string&) const] In update mapgen mx_sewer_mntS on sewer_ew, setting terrain to t_metal_floor (from t_sewage) at (5,13) when item 55gal_drum existed.  Resolve this either by removing the terrain from this mapgen, adding suitable removal commands to the mapgen, or by adding a suitable flag to the innermost mapgen: either ERASE_ALL_BEFORE_PLACING_TERRAIN if you wish terrain to replace everything previously on the tile or ALLOW_TERRAIN_UNDER_OTHER_DATA if you wish the other items to be preserved`

**Comment by wapcaplet** [comment]
Should be fixable by adding the `ERASE_ALL_BEFORE_PLACING_TERRAIN` flag, like previous fix #54797
