### ISSUE TITLE
Dizzy Crawling Knockdowns

### ISSUE THREAD

**Issue by Grubleafeater** [CleverRaven/Cataclysm-DDA#55053]
### Describe the bug

When moving while lying down and dizzy, you occasionally may be 'downed'. This makes no sense--you can't fall over if you're already lying down.

### Steps to reproduce

Be dizzy--say, as a effect from withdrawl.

Lie down.

Move around.

### Expected behavior

I would expect to not be downed while crawling.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 689dfa5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

**Comment by LeahLuong** [comment]
You may not be able to fall down while prone but you can get flipped over & ineffectually wave your limbs around in the air! Oh, yes!

**Comment by Night-Pryanik** [comment]
> Is this fixed by #55128??

Yes, it's fixed.
