### ISSUE TITLE
Propane can be wielded with no container

### ISSUE THREAD

**Issue by AdamChirnside** [CleverRaven/Cataclysm-DDA#55068]
### Describe the bug

Propane can be taken out of a valid tank, and wielded or stored anywhere.

### Steps to reproduce

1. Unload a propane tank

### Expected behavior

Propane is a liquid when compressed, and a gas at normal pressure and room temperature. Propane tanks probably shouldn't be unloadable, but maybe someone knows some method for doing that usefully.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 272b7a4 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    Arcana and Magic Items [Arcana],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Maleclypse** [comment]
So does it not evaporate when you unload it?   It's marked as a gas in the propane json entry.

**Comment by AdamChirnside** [comment]
No it doesn't evaporate. And it can be loaded back into a propane tank

**Comment by robkuijper** [comment]
I've been playing around with this a bit.

Unloading a wielded propane tank (just using a small one) drops the propane on the ground (without warning).
Waiting does not seem to make the propane evaporate.

Trying to pickup the propane again with `(g)` interface (while still wielding the tank) flags the propane as a valid pickup, but is not actually picked up during the activity.

Using AIM, the propane can be shifted around to nearby tiles. What's also interesting is that trying to add propane to worn items without wearing anything yields the following interface. After confirming 2, the propane is (again) not actually picked up.
![image](https://user-images.githubusercontent.com/7792876/152782329-d7a742f2-487c-4a9e-98c9-2864c8de55c1.png)

**Comment by TealcOneill** [comment]
Fixed by #69933. @GuardianDll
