### ISSUE TITLE
Hot water taken from a vehicle tank will spontaneously freeze (again)

### ISSUE THREAD

**Issue by railmonkey** [CleverRaven/Cataclysm-DDA#55066]
### Describe the bug

As of the most recent experimental, water in vehicle tanks has the (hot) tag and keeps it when used to fill a container. This would be fine, but when it cools off, it _keeps_ cooling until it is frozen, even in the middle of summer. I remember there being a similar bug a long while back, but I can't find any PRs that would explain its return. 

### Steps to reproduce

1. Open attached save.
2. Wait 10 in-game minutes.

### Expected behavior

I expect that water taken from vehicle tanks should normalize to equilibrium and not break the laws of thermodynamics. If I don't even have the ability to make a proper milkshake yet, my canteen should not be freezing.

### Screenshots

![image](https://user-images.githubusercontent.com/6116024/152408947-b4f2f6a8-e444-44af-84a1-3a90a6772d1e.png)
Note the date and indicated temperature.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 97d8c8b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Extra Mutated Scenarios [extra_mut_scens],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

[Smiley Park.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7997354/Smiley.Park.zip)

**Comment by coyo7e** [comment]
The time it takes for food/water/etc to freeze is often super inexplicable in my experience as well. I have even tested tit with thermoses vs other containers and stuff and there does not seem to be any actual use to thermoses, they do not keep things contained within them hot, or cold, any longer than a plastic pill bottle can.

**Comment by Hirmuolio** [comment]
It seems like taking water from the kitchen unit creates water with invalid temperature.
It is labeled hot, its temperature is 0 K and its thermal energy is 0 kJ.
Siphoning seems to give normal water.

**Comment by LeahLuong** [comment]
It looks like you've discovered ice-nine. Be _**very**_ careful about letting it get into contact w/ other types of water!

I believe #40732 is the prior issue you remember. Hirmu did the work addressing that in #42825 so prob knows what he's talking about.

@Hirmuolio In #42825, you say the water should be copying attributes from its parent container. Why is this different w/ the kitchen unit?? Perhaps fixing this issue could be as simple as mimicking the siphon action from vehicle tanks.

**Comment by railmonkey** [comment]
@LeahLuong That's the one, yeah. For the rest, I'll take it on faith. I knew temperature handling was pretty wonky, but I forgot _how_ wonky.
