### ISSUE TITLE
Android save location

### ISSUE THREAD

**Issue by shebang79** [CleverRaven/Cataclysm-DDA#55074]
### Is your feature request related to a problem? Please describe.

Hi! 

An option to change the data folder would be really great for Android, or at least, where it puts your save files.

In my use case, for example, I send my save between my desktop and my phone. But it's extremely slow even on a reasonably fast phone (Pixel 4 xl in my case) to actually move the whole save folder around, especially as your game gets longer. An easy solution would be to just use something like rsync -- actually pretty easy to do, but with newer Android versions access to the /android/data folder are restricted for some annoying reason. 

### Solution you would like.

An option to specific where my data / save files go. Maybe an alternate places to put mods, gfx and sound packs, etc.

It seems Google is intent on making Android as annoying as possible, so this will probably solve future problems anyway.

### Describe alternatives you have considered.

Well, some filemanagers do allow access to the data folder, but this doesn't really solve the problem in a good way, and doesn't help me because games that have run longer can easily take 20-30 minutes to actually move save files to the correct location.

**Comment by BrettDong** [comment]
Previous discussion: #49310
