### ISSUE TITLE
There is no officila "linux tiles" asset for 0.F-3

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#55089]
### Is your feature request related to a problem? Please describe.

 0.F-3 has linux-curses, but no linux-tiles

https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/0.F-3

### Solution you would like.

add a linux-tiles asset to 0.F-3

**Comment by dseguin** [comment]
Duplicate of #53369 and #53122

**Comment by hexagonrecursion** [comment]
Sorry. I did search, but somehow failed to find the issues. Thank you.
