### ISSUE TITLE
Sleeping w/ Reflex Photophore (on) Triggers Warning

### ISSUE THREAD

**Issue by LeahLuong** [CleverRaven/Cataclysm-DDA#55082]
### Describe the bug

See title.

### Steps to reproduce

1. Wait for Reflex Photophore to activate.
2. Sleep.
3. ???
4. PROFIT!

### Expected behavior

Player has no direct control over it so no warning should be shown.

### Versions and configuration

Android 0.F-3 Tiles English vanilla

**Comment by wapcaplet** [comment]
Cannot reproduce issue.

Reflex photophore is on:

![image](https://user-images.githubusercontent.com/238395/152668753-8a58446d-fef8-4c13-b122-471126447922.png)

Attempting to sleep gives no warnings:

![image](https://user-images.githubusercontent.com/238395/152668761-62b982ec-2496-4701-9cf9-52e43404bbf5.png)


- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-5861-g3111ca2fdf [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by LeahLuong** [comment]
I mentioned this in #51717 but it didn't look like it was addressed by #55052. Wish I'd screenshotted it but I didn't know how to @ the time of that post.

@Night-Pryanik Was it fixed in #55052??

**Comment by Night-Pryanik** [comment]
> Was it fixed in #55052?

No, it wasn't.

**Comment by LeahLuong** [comment]
Well, I guess I'll close this since it's not reproducible on the latest. I really wonder how this was patched; was unable to find a PR that might have done this.
