### ISSUE TITLE
Vehicle-based auto-drink and auto-eat zones stop working after I move the vehicle

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#55091]
### Describe the bug

I like the auto-eat and auto-drink features - they allow me to stay hydrated and fed while crafting. Just like any other zone auto-eat and auto-drink zones can be bound to a vehicle part - just put your food in the right cargo space and never worry about becoming hungry while crafting again.

Unfortunately this is currently broken: the zones stop working as soon as the vehicle moves.

### Steps to reproduce

1. Spawn a 4x4 car
2. Create a 1x1 zone over one of its trunks. The game will prompt you to choose to bind the zone to the vehicle part or not. Say yes.
3. Debug wish for 10 bottles of clean water and put them in the trunk
4. Debug set your thirst to 500
5. Wait for 1 hour. Notice that auto-drink works
6. Debug set your thirst to 500 again
7. Drive the vehicle 1 tile north
8. Wait for 1 hour.
9. Now auto-drink does not work.

### Expected behavior

Vehicle-based auto-drink and auto-eat zones should continue working after the vehicle moves

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 97d8c8b [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]

### Additional context

For now I am using a workaround: after moving my vehicle and before crafting I create a new zone. Any zone. Anywhere. Creating e.g. a "chop trees" zone and saving the changes makes the bug go away until I move the vehicle again.

**Comment by wapcaplet** [comment]
Confirmed with the provided steps.

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-5861-g3111ca2fdf [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by snipercup** [comment]
I have this issue as well. Even deleting and re-adding the zones to the vehicle part my character isn't auto eating while reading. If you look up 'auto eat zone' on discord you can see multiple people having issues with the zone. The last search result is from October 4 2022.

- OS: Windows
    - OS Version: 10.0.22000.1098 (21H2)
- Game Version: bd17c48 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Tamable Wildlife [Tamable_Wildlife]
]
