### ISSUE TITLE
Gun Description missing a \n, improperly passing tests?

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#55097]
### Describe the bug

How does this: 
![image](https://user-images.githubusercontent.com/22281606/152569192-a03d2798-b84c-4da7-9d63-18d0b0a2f2cd.png)

Pass the tests:
![image](https://user-images.githubusercontent.com/22281606/152569902-0f8f6a34-c43c-4e92-9139-28a9aa9e7257.png)

![image](https://user-images.githubusercontent.com/22281606/152569218-37a35118-9bdc-44ac-87e1-592b559612f4.png)

Both tests appear to check for \n, which I don't see between the Sight Dispersion: xxx and Effective Recoil: xxx?

Is this a \n\r piece of windows fuckery?

### Steps to reproduce

Inspect any gun.

### Expected behavior

That the two stats are on different lines.

### Versions and configuration

Win 10, Tiles, 07de00c

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
