### ISSUE TITLE
overmap_terrain_coverage test consumes HUGE amount of RAM

### ISSUE THREAD

**Issue by BrettDong** [CleverRaven/Cataclysm-DDA#55104]
### Describe the bug

`overmap_terrain_coverage` test is very demanding of RAM.

I am unable to complete the test suite on a 4GB RAM laptop. The program either gets killed by the kernel, or fails at `overmap_terrain_coverage` test with `bad_alloc`. Then I tried to run `overmap_terrain_coverage` test on another (Windows) computer and observed that it consumes more than 5GB of RAM (MSVC x64 Release mode):
![Untitled](https://user-images.githubusercontent.com/21075502/152585144-fbce80ac-057e-4f50-9bc5-166c43114de6.png)

### Steps to reproduce

1. Run the test `./tests/cata_test "overmap_terrain_coverage"`
2. Observe RAM usage

### Expected behavior

Not to consume that amount of RAM.

### Versions and configuration

version: commit 9fb7080268f2e90968a817175ca142f182441e43

### Additional context

I tried to run heap profiling in Visual Studio, but the heap profiler ran out of `C:\` disk space after writing 30GB of event trace data before `overmap_terrain_coverage` ever finished, and crashed Windows system. Nonetheless, I recovered some heap profiling data, and seems that there is huge amount of `submap` class instances being allocated on the heap, but never gets deallocated in `overmap_terrain_coverage` test.

https://github.com/CleverRaven/Cataclysm-DDA/blob/9fb7080268f2e90968a817175ca142f182441e43/src/mapgen.cpp#L204-L214

**Comment by LeahLuong** [comment]
Related to #50344??

I think this is an area where a lot of code optimization needs to happen. My game regularly crashes if I'm traveling on the overmap too quickly w/out frequent saves. Saving seems to clear some overloading register somewhere & stalls a crash. If it does crash, no .log is generated. Saving itself requests memory from the same pool & sometimes precipitates a crash w/ sometimes strange effects like vehicle/mob displacement or item duplication/deletion.

**Comment by BrettDong** [comment]
> Related to #50344??
> 
> 
> 
> I think this is an area where a lot of code optimization needs to happen. My game regularly crashes if I'm traveling on the overmap too quickly w/out frequent saves. Saving seems to clear some overloading register somewhere & stalls a crash. If it does crash, no .log is generated. Saving itself requests memory from the same pool & sometimes precipitates a crash w/ sometimes strange effects like vehicle/mob displacement or item duplication/deletion.

No, this issue is specific to overmap terrain coverage test and isn't related to jmapgen data structure nor gameplay.

**Comment by jbytheway** [comment]
I am profiling the memory usage.  I found and fixed one big waste of memory already.  I'll keep poking for a while to see if anything else looks like a quick win.

**Comment by jbytheway** [comment]
#59313 is a partial fix.

**Comment by akrieger** [comment]
The baseline usage is bad but there's transient vector reallocations that really cause memory usage to spike.
![image](https://user-images.githubusercontent.com/667719/180360560-39c4dc52-b6ed-427b-a01b-238959d75670.png)

**Comment by akrieger** [comment]
Over 5 million spawns seems like a bit much. And the test ain't over yet.
![image](https://user-images.githubusercontent.com/667719/180360779-bc5d4725-cda6-4033-888d-9e5a2dc251d4.png)

**Comment by jbytheway** [comment]
Five million spawns has to be some kind of bug.  I'll see if I can reproduce that.

**Comment by jbytheway** [comment]
Left the test running repeatedly for about eight hours with a sanity check to trigger an error if the spawns ever exceeded 1000 and I've not been able to reproduce this.  I think it must be something platform- or compiler-specific (I'm on Linux / gcc 12).

Ideas for how you might track this down:
* It might be something like a heap corruption?  Try running with ASan.
* Check which `oter_id` is being generated when these large numbers of spawns happen.
* Are these large numbers of spawns happening in the `tinymap` object used by the tests, or the global `map` object?  If each new test mapgen is adding something to the same global map then I can see that might be an issue.  We have had that issue with vehicle caches in the past.

**Comment by akrieger** [comment]
Well, I tried asan on windows and it seems to completely break the std::string( const char * ) constructor because it results in strings that aren't NUL terminated internally. However it doesn't seem like I can repro the 5M spawns anymore. It's possible that I rebased past a fix, so I'll spend at least a little bit of time trying to track that down for curiosity sake.

**Comment by anothersimulacrum** [comment]
I'm getting massive memory allocation from `map::add_spawn`, possibly what akrieger was getting:
![image](https://user-images.githubusercontent.com/42699974/180867697-c604b361-db50-4ca3-9b6f-9ae39f15588f.png)

It's not consistent, though.

**Comment by anothersimulacrum** [comment]
Anyone else get it with `--rng-seed=1658785006`? It's consistent with that for me.
Make command: `CXXFLAGS=-fno-omit-frame-pointer LDFLAGS=-fuse-ld=lld make -j24 CCACHE=1 BACKTRACE=1 LIBBACKTRACE=1 RELEASE=1 TILES=1 SOUND=0 STRING_ID_DEBUG=1 DEBUG_SYMBOLS=1 ASTYLE=0 LINTJSON=0 RUNTESTS=1 CLANG=clang++`

**Comment by anothersimulacrum** [comment]
I don't get it with g++,

**Comment by jbytheway** [comment]
My plan for reducing overmap memory usage is twofold:
* Make `mongroup` smaller.  I've already brought it down from 160 bytes to 144 bytes (#59528) and there's a lot more fat that can be trimmed.
* Make `map_layer` use a sparse representation for layers which are mostly uniform (which should be nearly all of them).

**Comment by jbytheway** [comment]
> Anyone else get it with `--rng-seed=1658785006`?

I was unable to reproduce with that build command and options. Can you say which commit you built and what your test command was?

**Comment by anothersimulacrum** [comment]
32ee0b1131cbb01d8cd149aa1d2cd07abb26b964, `tests/cata_test --rng-seed=1658785006`

**Comment by anothersimulacrum** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/59488 rebased onto de4bd30fa45f5bbfab032d54844b8369e86dcdf0 did not improve the situation. Though I notice that's since been merged, let me grab master.

**Comment by akrieger** [comment]
I couldn't repro on windows with that seed either. But I will keep rerunning the test with random seeds and see if I can get one to break.

**Comment by akrieger** [comment]
I can't repro in WSL with that commit and that seed either, running the test in isolation. Maybe there's some cross test corruption happening.

**Comment by jbytheway** [comment]
I was able to repro @anothersimulacrum's example on that commit with those options running all the tests, but not that test alone.  I'm working now on reducing the set of tests to the minimum required to reproduce.

**Comment by jbytheway** [comment]
So I've narrowed down (at least one instance of) the issue to this line placing monsters from `GROUP_PETS` in `lodge_ground_glooscap2`:

https://github.com/CleverRaven/Cataclysm-DDA/blob/2fbf47cd521bad5f989ef0630cfdf61b6c70fc3a/data/json/mapgen/hunting_lodge.json#L80

That's all I was able to figure out today.

**Comment by akrieger** [comment]
What's your process for narrowing it down? Is this something we can help parallelize?

**Comment by jbytheway** [comment]
I use the automated script for minimizing sets of tests required to reproduce issues (it's in `tools/reduce_tests.sh`.  It took many hours in this case, but it did it while I wasn't there, so not an issue.  The result is the following command which still reproduces the issue for me:
```
./tests/cata_test --rng-seed 1658785006 name_generation,npc_can_target_player,default_overmap_generation_always_succeeds,overmap_terrain_coverage
```
Now that I have a reasonably fast reproducing case, it's time to go digging in the debugger...

**Comment by jbytheway** [comment]
It looks like there is some situation when `MonsterGroupManager::GetResultFromGroup` will return a non-empty list of spawns but not decrement the `quantity` passed to it.  This results in many repeated spawns as spawning will repeat as long as `quantity` is non-zero.

**Comment by jbytheway** [comment]
I think I know what the problem is and how to fix it. Tomorrow I'll try to create a unit test for it.

**Comment by jbytheway** [comment]
Putative fix in #59724.

**Comment by hexagonrecursion** [comment]
@akrieger 

> Well, I tried asan on windows and it seems to completely break the std::string( const char * ) constructor because it results in strings that aren't NUL terminated internally.

I do not see why this would count as "broken". std::string is not required to be NUL terminated by the C++ standard as far as I know. Only std::string::c_str() is guaranteed to return a NUL terminated string

**Comment by akrieger** [comment]
It's 'broken' because it causes later things that try to read or copy the string to blow up because they run off the end of the string through no fault of their own because it no longer conforms to spec, because none of the rest of the implementation of string handles it not being nul terminated in the constructor.

As an aside, there's various constraints as to the implementation of string that essentially require it to be internally nul terminated and contiguous. For example operator[] requires a reference to `CharT` if index == size() https://en.cppreference.com/w/cpp/string/basic_string/operator_at. data and c_str are required to be constant time so they cannot realloc internally, and as of c++11 "c_str() and data() perform the same function" https://en.cppreference.com/w/cpp/string/basic_string/c_str. data explicitly returns a pointer to the internal storage and is for writing-through and the spec requires it to be nul terminated in c++11 (again, because data and c_str now perform the same function). https://en.cppreference.com/w/cpp/string/basic_string/data

**Comment by hexagonrecursion** [comment]
@akrieger Thanks. I did not know about data() having tighter constraints since C++11. This may be a bug in the sanitizer then. If you can reproduce this with latest clang or gcc, this should probably be reported upstream.

**Comment by akrieger** [comment]
This was compiling with msvc's implementation of asan, not clang's.
