### ISSUE TITLE
Deluxe sandwich recipe doesn't recognize ingredients

### ISSUE THREAD

**Issue by martosss** [CleverRaven/Cataclysm-DDA#55102]
### Describe the bug

I'm looking at the recipe for deluxe sandwich. It can't recognize that I have cracklins or hard cheese (2 of the ingredients among others). So currently it's showing me that I don't have any cracklins or hard cheese to cook it with, although I have both, one in my inventory, the other on the ground next to me.

### Steps to reproduce

1) Learn the recipe for deluxe sandwich
2) get hard cheese and cracklins
3) check that the recipe doesn't recognize that you have these ingredients

### Expected behavior

The recipe accepts those ingredients, as they're listed in the recipe, obviously.

### Screenshots

![image](https://user-images.githubusercontent.com/7064677/152583198-5eef0991-5fb8-4e0c-a7c9-46bc29efd0a9.png)
![image](https://user-images.githubusercontent.com/7064677/152583805-a12084ef-4aec-44fc-a505-df1bd113c5ed.png)

### Versions and configuration

Win 8.1
Stable 0.F3
Tiles
English
dda mod

### Additional context

I used a filter to find that recipe, but just finding it from the recipe list without any filter also doesn't recognize the ingredients.
Also, other recipes successfully recognize those ingredients, so it's not the problem with the ingredients(say that one is frozen, or the other is fresh), the problem is specifically with this recipe.

**Comment by LeahLuong** [comment]
I think the recipe also doesn't respect calorie inputs sometimes. I only have my anecdotal experience to share but the displayed caloric value of deluxe sandwiches on the 'E'at menu wasn't filling my char up like other foods. Eating when just obtaining the "Very Hungry" status would take like 2500 calories of deluxe sandwiches but only like 1200 from other foods to get to "Satisfied" status. Deluxe sandwiches have decent satiety so I don't believe that was a determining factor.

I experienced this in 0.F-2 & -3 but have not come across OP's issue.

**Comment by moxian** [comment]
Cannot reproduce.
![20220204-222912-cataclysm-tiles](https://user-images.githubusercontent.com/7831163/152611762-c73fd4d6-90c1-4a4f-88c5-bf7e44d39ede.png)

Do you have a save showing the issue?

**Comment by martosss** [comment]
@moxian There you go, a save file, I tried it on my experimental version, too, with even more crazy results - recipes are split roughly 50-50 at recognizing cracklins, the hard cheese is also broken for multiple recipes.
[Rogers City.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8006777/Rogers.City.zip)

I think there is some kind of duplication of ingredients, where you have 2 places that say "cracklins", but they're different types of cracklins .... maybe due to toxicity - 1 is clean ,whereas the other is dirty intoxicated and the game doesn't like it therefore?

Here are some pictures from other dishes from my experimental, playing the same save file:

![image](https://user-images.githubusercontent.com/7064677/152616153-d86a6832-914d-4462-a77a-7b28d3df3f61.png)
![image](https://user-images.githubusercontent.com/7064677/152616171-e80f6e66-c5db-424a-9b70-a0807929872f.png)
![image](https://user-images.githubusercontent.com/7064677/152616198-67b7c827-d227-4f68-bc81-ee12decb45b1.png)
![image](https://user-images.githubusercontent.com/7064677/152616221-e9f47a87-d296-4c9f-87da-a5e86ade3653.png)
![image](https://user-images.githubusercontent.com/7064677/152616244-01cf2b95-544b-4655-831c-0eeb4f4d3239.png)
![image](https://user-images.githubusercontent.com/7064677/152616263-19ca6e58-d792-48b9-9148-611152889dd3.png)

**Comment by martosss** [comment]
Here's another funky recipe - a wheat-free reuben sandwich that has 2x cracklins in the recipe, and only one of them is recognized.
So, I guess the 2nd version of cracklins is used in other places and it's not being recognized in some cases
![image](https://user-images.githubusercontent.com/7064677/152616717-23573e63-3d95-4be2-8c3a-58720842393b.png)

**Comment by martosss** [comment]
I think I already see the cracklins problem - there are multiple versions of cracklins in the game - look at the spawning menu:

![image](https://user-images.githubusercontent.com/7064677/152617139-baaa2094-5c1f-417e-8279-658b822ad359.png)

There are 5 different cracklins!!! They have either "human mean" or "toxic" or both, or none ... That's in my experimental version **"tiles-x64-2022-01-31-0804"**

**Comment by martosss** [comment]
So the solution could be to rename the different versions of cracklins to
"Mutant cracklins" vs "Human cracklins" vs ... something else ... toxic human? so that players can see that recipes require a specific type of cracklins(which makes no sense in real life, but whatever).

A better solution would be to allow all kinds of cracklins and add different amount of Toxicity to the final product, 0-100-1000% depending on the ingredients

**Comment by moxian** [comment]
Your cracklins and cheese in the save are frozen, and as such are not accepted as ingredients. Reheating them in a copper pot makes them recognized as useable
![20220205-000452-cataclysm-tiles](https://user-images.githubusercontent.com/7831163/152619093-8d331eed-2830-491d-9d0a-0c40551828d9.png)

**Comment by martosss** [comment]
Ah, so recipes that don't require fire don't accept frozen ingredients!!! I understand the problem now ... That makes some kind of sense ... but ... 

Well, that is ridiculous ... I'm cooking it next to a fire ... so the frozen ingredient should be included in the list as a potential candidate for defrosting...

**Comment by martosss** [comment]
Potential solution - allow cooking, but transfer the "frozen" status from the ingredients to the result, forcing me to defrost the result after preparing it.

**Comment by moxian** [comment]
I think this is ultimately a duplicate of #50387 / #37135

**Comment by martosss** [comment]
OK, so what can we do to fix this?
1) Change the function that checks for frozen status to return always true if there's a "stable fire" nearby?
+ That will **fix the current problem** - frozen ingredients will be shown in case there's a fire source of any kind nearby
- However, you will **not use any time** to defrost the food in case you decide to execute the recipe. I think this is a neglible downside, since usually defrosting time is very short in any case.

2) do (1) and on top of that, use extra time to defrost frozen ingredients

3) do (1) and (2) and on top of that, implement them in case of an unstable fire source

Can we agree, that in the timeline 1-2-3, the 1st step is a good start and should be implemented?

**Comment by martosss** [comment]
` return !component.has_flag( flag_FROZEN ) || component.has_flag( flag_EDIBLE_FROZEN );`

So this line should be changed to something like 

 return !component.has_flag( flag_FROZEN ) || component.has_flag( flag_EDIBLE_FROZEN ) **|| there_is_fire_nearby()**;

Now we need someone who knows the name of that function and how to edit it in the code?

**Comment by martosss** [comment]
OK, I think I found what we need. This function should control how a character uses fire:

https://github.com/CleverRaven/Cataclysm-DDA/blob/0d23870736b117178c44e3afdfd1badcb678c129/src/character.cpp#L8629-L8657

So if we use the first part, `get_map().has_nearby_fire( pos() )`, that should be our "fire_nearby()" function.

I'm not sure if we can call this "get_map" and "pos" functions from inside the recipe.cpp ... I hope we can?
Can someone who's familiar with the codebase confirm?
