### ISSUE TITLE
Famptinder, Pt. 2

### ISSUE THREAD

**Issue by LeahLuong** [CleverRaven/Cataclysm-DDA#55109]
### Describe the bug

Using the faction camp (AKA "famp") bulletin board to have a follower craft cooked veggies from plant marrow results in a much larger tinder usage than the recipe states. 93 plant marrow used up 11k+ tinder where it should've only cost 465.

### Steps to reproduce

1. Make the famp.
2. Make the cooked veggies.
3. ???
4. PROFIT!

### Expected behavior

I expected that famptinder level would decrease, but not by nearly as much!

### Versions and configuration

Android 0.F-3 Tiles English vanilla

### Additional context

I'll try to test out more cooking recipes when I have access to a follower & ingredients to see if this tinder cost isn't isolated to just this 1 recipe.

**Comment by LeahLuong** [comment]
Here are some screenshots showing the differing costs of cooking chunks of meat:

![Screenshot_20220208-140235](https://user-images.githubusercontent.com/91638992/153114301-374deb1c-fbdf-4836-a576-eccc94aba045.png)

As advertised.

![Screenshot_20220208-140308](https://user-images.githubusercontent.com/91638992/153114354-d542f71e-56f0-4364-b0fb-f1595ff58aa1.png)

Selecting the batch size.

![Screenshot_20220208-140322](https://user-images.githubusercontent.com/91638992/153114403-e45333db-ab5c-4bc4-977d-48b19c1cf9ff.png)

Cost @ sale.

Those 18 chunks _**should**_ have cost 126 tinder based on the 1st screen. Actual cost was 25x this exactly & this jibes w/ my experience cooking plant marrow.

I'm also noticing it's listing 3x the amount of charcoal I have stocked. There seem to be multiple number conversion errors in the famp system.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
