### ISSUE TITLE
Famptinder

### ISSUE THREAD

**Issue by LeahLuong** [CleverRaven/Cataclysm-DDA#55108]
### Describe the bug

Using the faction camp (AKA "famp") bulletin board to have a follower craft tinder results in a duplicate batch # query. This was noted by PatrikLundell in #52459. The 1st query works, subtracting resources & giving the player a message saying who was sent to craft tinder. After clearing the message, the query pops up again; it's seemingly ignored as resources are not subtracted.

### Steps to reproduce

1. Make the famp.
2. Make the tinder.
3. ???
4. PROFIT!

### Expected behavior

I expected that famptinder level would increase, because all other skills can increase in level.

### Versions and configuration

Android 0.F-3 Tiles English vanilla

### Additional context

Stay tuned for pt. 2 of this epic saga!

**Comment by LeahLuong** [comment]
Canceling the 1st batch query will bring up the 2nd, after which canceling you'll be told no 1 was sent.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
