### ISSUE TITLE
Fior di Battaglia is not a fitting martial art manual for polearms/axes specifically

### ISSUE THREAD

**Issue by Testudo-Cultu** [CleverRaven/Cataclysm-DDA#55116]
### Is your feature request related to a problem? Please describe.

Fior di Battaglia covers much more than just polearms and axes. Le Jeu de la Hache is a more fitting martial art manual for axes and polearms.

### Solution you would like.

First idea is to rename Fior di Battaglia to Le Jeu de la Hache and keep everything the same.

Second idea is to merge Fior di Battaglia and Medieval Swordsmanship. This could be seen as overpowered, but personally I think this would be a good change, since you can find axes far more easily than swords anyway; especially now that feral humans can drop fire axes. The merged martial art could either keep the name Fior di Battaglia or simply be renamed to HEMA.

Third idea is to repurpose Fior di Battaglia as a sort of Krav Maga of medieval martial arts by letting it function on almost all medieval weapons. This way Medieval Swordsmanship would still have a purpose, and would generally be superior to Fior di Battaglia if someone manages to actually find or make a sword.

### Describe alternatives you have considered.

The final idea is to leave it as it is. My proposal only makes these martial arts more accurate to their real counterpart and is by no means critical.

### Additional context

https://wiktenauer.com/wiki/Le_Jeu_de_la_Hache_(MS_Fran%C3%A7ais_1996)
https://wiktenauer.com/wiki/Fior_di_Battaglia_(MS_Ludwig_XV_13)
https://en.wikipedia.org/wiki/Fiore_dei_Liberi

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
