### ISSUE TITLE
Mapgen error with 30gal_drum and mx_sewer_pipesG

### ISSUE THREAD

**Issue by AdamChirnside** [CleverRaven/Cataclysm-DDA#55119]
### Describe the bug

When driving on the surface, an error popped up. See Additional Context section

### Steps to reproduce

Unknown

### Expected behavior

No such error

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 272b7a4 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    Arcana and Magic Items [Arcana],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

 DEBUG    : In update mapgen mx_sewer_pipesG on sewer_ns, setting terrain to t_bridge (from t_sewage) at (13,0) when item 30gal_drum existed.  Resolve this either by removing the terrain from this mapgen, adding suitable removal commands to the mapgen, or by adding a suitable flag to the innermost mapgen: either ERASE_ALL_BEFORE_PLACING_TERRAIN if you wish terrain to replace everything previously on the tile or ALLOW_TERRAIN_UNDER_OTHER_DATA if you wish the other items to be preserved

 FUNCTION : virtual void jmapgen_terrain::apply(const mapgendata&, const jmapgen_int&, const jmapgen_int&, const string&) const
 FILE     : src/mapgen.cpp
 LINE     : 2573
 VERSION  : 272b7a4

**Comment by PatrikLundell** [comment]
Thanks for reporting it. This error essentially says that someone needs to clean up the generation of the terrain referenced using recently introduced functionality that allows such cleanup. It shouldn't affect the game play.

**Comment by LeahLuong** [comment]
Related to #55050. Method of fixing seen in #54797.

**Comment by cake-pie** [comment]
This was [fixed](https://github.com/CleverRaven/Cataclysm-DDA/pull/55147/files#diff-4c173d5bac7d6d640d5522e91d8c42438265660f9043a3d3766d2644dd6712eeR650) in #55147 and can be closed.
