### ISSUE TITLE
Improve the "tip of the day" 

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#55122]
### Is your feature request related to a problem? Please describe.

Tips are great, but usually people ignore them, and open the save file instead

### Solution you would like.

Add a "tip of the day" block to loading screen, how it maded in most popular games, so people can read them while loading the save file (usually it lasts long enough so you can read it without a problem)

### Additional context

Also it would be cool to have some tips related to hidden mechanics, for example, about teleglow or cardio

**Comment by AcidAntOnAMinefield** [comment]
I'd probably add to this:
Make it so this tip (or a better phrasing of it): "You can boil your water overtime if you place it in a metal or glass container and on a fire (Stove, Oven, Brazier) while you do something else." is shown, as it is doesn't seem to be a widely known thing.

**Comment by Night-Pryanik** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/issues/28344#issuecomment-466731890

I was said that it's not a good idea.

**Comment by Fris0uman** [comment]
Yeah loading time can go pretty fast. Maybe increasing font size of the tip on the main screen?

**Comment by GuardianDll** [comment]
> loading time can go pretty fast
I have nearly 10-15 seconds without mods

**Comment by Fris0uman** [comment]
Yes, but it depends on your machine and overall we want it to go as fast as possible.

**Comment by Night-Pryanik** [comment]
> Why not make it on the very bottom of the screen, or somwhere on the left/right side? Is there some limitation for it?

No, we could print it anywhere.

**Comment by GuardianDll** [comment]
So the only reason to not make it because we are interested in making loading as fast as possible, right?
In that case i see no problem here - i dont think phone users have a great hardware to get 2-3 second loadings

**Comment by VitreousEyes110** [comment]
> I'd probably add to this: Make it so this tip (or a better phrasing of it): "You can boil your water overtime if you place it in a metal or glass container and on a fire (Stove, Oven, Brazier) while you do something else." is shown, as it is doesn't seem to be a widely known thing.

Exists as a tip already

```
  {
    "type": "snippet",
    "category": "tip",
    "text": [ "Save time.  Instead of using a recipe, place water in a container on a fire to boil it." ]
  },
```

On loading, a solution could be adding a setting that, if turned on in the options, halts the game once loading is completed and leaves the tip on screen until the player presses a button to continue into the game.

**Comment by AcidAntOnAMinefield** [comment]
Would it be possible/feasible for the "tips" to show up when a player is sleeping, for example? 
Of course, that would probably require making them optional/toggleable. But during the time a player sleeps or crafts, especially items that take a long time to craft, they would have something to read instead of staring at the % going up or at the "processing" message.

**Comment by PatrikLundell** [comment]
Essentially the same problem as with the loading screen: It's something we want to go as quickly as possible, and we don't want to be forced to do an extra key press to get rid of something that is there as a distraction while waiting for something. This means that for sleeping/crafting, the tip would have to appear somewhere on the screen where there isn't anything the player would want to see when done. If you can find such a place, I would guess it would be possible to have it go away on your first action. I guess that if you can find this magic location, the message could be made to go away on the first action after a load as well. However, I doubt that location exists...

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
