### ISSUE TITLE
Gunsmith & Firearm Repair Kits need batteries to pry open crates

### ISSUE THREAD

**Issue by AcidAntOnAMinefield** [CleverRaven/Cataclysm-DDA#55123]
### Describe the bug

The Gunsmith and Firearm repair kits have, as part of their components, a Hammer, which has a prying ability of 1 - the same as a Makeshift Crowbar. 

However, if you try to open a sealed crate with them, the result will be the game telling the player they have no charge to work with. It also seems that the game prioritizes these kits for prying purposes, even if you have an actual loose hammer or crowbar in your inventory for this.

Seeing as they are "kits", one would assume that the hammer, as well as any other non-battery related tools, would not be converted to requiring batteries to operate - as in, someone would just be able to open the box/unfold the folder the items are in, retrieve what they need and use it.

However, if you reload them with batteries, to pry open a crate, the Firearm repair kit uses 100 charges, the gunsmith repair kit uses 25.

### Steps to reproduce

1. create a world in a scenario that gives you easy access to crates ("Safe Place" > "Light Industries"), give yourself 20 strength;
2. Debug yourself a Hammer, a makeshift Crowbar, a gunsmith repair kit and a firearm repair kit with no batteries.
3. Align the 5 crates in a way so that you can try and open 1 crate with each tool.
4. Notice that the 2 kits will not operate without batteries. 
5. Recharge them with a Light and Medium Disposable Batteries (Firearm and Gunsmith kit respectively)
6. Notice as crates can now be opened, but Battery charges will be used instead.

### Expected behavior

Using a non-powered tool from a tool bundle item should not require for charges to be used, as placing a hammer or a chisel inside a box / bag does not make them automatically electrical tools.

### Screenshots

![image](https://user-images.githubusercontent.com/80117149/152644467-99bb8b2e-c415-4a02-a30d-0e5110a7388a.png)

### Versions and configuration

- OS: Windows
    - OS Version: Windows 7
- Game Version: 7efd4f5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]

### Additional context

Log order is reversed: 
Older messages below, newer messages above. 
Order of tool usage:
Makeshift Crowbar > Hammer > Firearm Kit > Gunsmith kit. and after reloading, "Firearm Kit > Gunsmith Kit".

**Comment by Maleclypse** [comment]
This seems to be a common bug with powered toolsets which also have unpowered qualities.

**Comment by wapcaplet** [comment]
Confirmed. Prying open a crate with a firearm repair kit consumes 100 battery charges.

I think the fix will be two-fold:
- Change those kits to use "charged_qualities" for all the ones that should be battery-powered (#52304)
- Change the tool action/usage code so inherent "qualities" (those not needing battery power, like prying) do not actually consume battery power when used, while "charged_qualities" do consume power

**Comment by wapcaplet** [comment]
Related to #54120
