### ISSUE TITLE
Crafting should stop at the first signs of coughing

### ISSUE THREAD

**Issue by martosss** [CleverRaven/Cataclysm-DDA#55135]
### Describe the bug

You craft something and you start coughing due to fire.
result - the character keeps crafting and coughing until he starts chokes or a zombie comes to help him with his asthma

### Steps to reproduce

1) Start a fire at an oven or a stove and keep the fire going with enough wood.
2) Have environment protection below 7 and no mods[/mutations?] that would disable smoke effects
3) Start a long craft(longbow in my case) next to that fire and wait until the fire generates smoke in your tile
4) Currently the character coughs 10-15 times before the game pauses the crafting process.
![image](https://user-images.githubusercontent.com/7064677/152656289-6eddee44-83a5-4224-a41e-32cb7d355fd9.png)

### Expected behavior

The game pauses the crafting at the first signs of coughing and you can take appropriate action - start wearing a mask, use an inhaler or w/e.

That is what would happen in real life - you don't wait until you choke to death or are swarmed by zombies.

### Versions and configuration

Win 8.1 Stable 0.F-3 english vanilla

**Comment by mqrause** [comment]
This was added in #54727.
