### ISSUE TITLE
Creating worlds with extremely long world names lets the input field look weird

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#55148]
### Describe the bug

I held down `d` and got funny little effects.

![image](https://user-images.githubusercontent.com/59517351/152674486-be719605-e02e-49b5-9f59-4057fffcf88d.png)

### Steps to reproduce

1. Create a world.
2. Choose an incredibly long string as the world name or just hold down any key.
3. Witness the partial interface "corruption"

The existing text, such as "Use [*] to pick a random name for your world" gets overwritten ,too.

![image](https://user-images.githubusercontent.com/59517351/152674677-e873b445-31bf-40aa-9463-d1e391901906.png)

### Expected behavior

There should be a reasonable max length. Also using an world name of absurd length means the world creation fails silently because of file system limits (I assume).

Setting the priority to low because you have to deliberately try to trigger this bug.

### Versions and configuration

- experimental, tiles, Linux

**Comment by NetSysFire** [comment]
![image](https://user-images.githubusercontent.com/59517351/152674859-c1372f6d-6596-44f2-b696-aaf4322743f4.png)

Using the World menu on worlds with names which are long also looks weird.

![image](https://user-images.githubusercontent.com/59517351/152674908-fa9d244b-9830-4b7d-9449-e4a3878930b0.png)

More weirdness.

**Comment by robkuijper** [comment]
I think I found a fix for this.
Question is what would be a proper absolute max? I don't see myself making world names any longer than +/- 50 characters, but that might be different for some people.

**Comment by NetSysFire** [comment]
The absolute max is what the file system allows in terms of length of file names (255 chars?).
A reasonable max would be something that fits in one line or the predefined input field, the latter is probably better.

**Comment by PatrikLundell** [comment]
I wouldn't be surprised if the number of multi byte characters fitting into a file name would be smaller than the OS file name size, as the OS restriction is probably in bytes, not number of characters.
Also, the restriction shouldn't be shorter than the longest possible auto generated name (after translation).

**Comment by robkuijper** [comment]
It looks like the underscore input soft 'limit' is set to 32 utf-8 characters. By soft limit, I'm referring to the underscores that are shown in the world name.
It doesn't look like any of the auto-generated world names (English or other) get even close to that 'limit' (most being sub-20).
Hard limit could be set to either 32 or 64 utf-8 characters, which would both be very generous?
