### ISSUE TITLE
Game quits with segmentation fault if mutation has circular dependency

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#55151]
### Describe the bug

If the "Saprophage" mutation JSON is altered so its "prereqs" includes another mutation that requires "Saprophage" itself (creating a circular dependency), the game crashes with a segmentation fault when acquiring the mutation.

### Steps to reproduce

1. Change the "Saprophage" mutation JSON, adding "ROOTS3" to its "prereqs":

```diff
     "id": "SAPROPHAGE",
-    "prereqs": [ "ROOTS2" ],
+    "prereqs": [ "ROOTS2", "ROOTS3" ],
```

2. Load game, and acquire either the "Saprophage" or "Rooter" mutations. Segmentation fault occurs.

### Expected behavior

Game should not crash.

Mutations with circular or otherwise unresolvable dependencies should be detected at JSON load/validation time.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-5861-g3111ca2fdf [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

No crash.log is generated, and [debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8010443/debug.log) has nothing useful in it.

Bug reported by OmniscientQ on discord

**Comment by dseguin** [comment]
Related #53457
