### ISSUE TITLE
Lamp oil, tainted tallow inconsistency

### ISSUE THREAD

**Issue by Liork0** [CleverRaven/Cataclysm-DDA#55154]
### Describe the bug

Lamp oil recipe *seem* to be outdated, it take either 6 chunk of fat (of any kind) OR 2 tallows (of any kind).
All tallow recipe takes 3 chunks of fat as a input and give off 12 tallow as ouput (ratio of 1:4) , except for the tainted tallow recipe which take 4 tainted fat for 2 tainted tallow (ratio of 2:1) in addition of lacking the proficiency "Food preparation" and "Knife skills".
In addition, the recipe for demi human tallow also lack the proficiency but is otherwise consistent with the other tallow recipe.

### Steps to reproduce

1 : Open crafting menu
2a/b : Filter for c:fat,c:tallow / Filter for tallow (Assuming all recipes are known)
3a : All recipes shown follow the logic of 1 fat = 4 tallow, except for lamp oil
3b : All tallow recipe show 12 portions crafted for 3 fats inputted, except for tainted tallow which also lack proficiency.

### Expected behavior

What I expected for lamp oil : Craft the same quantity regardless if I used raw vs refined resources.
What is currently happening : Using the 6 chunks of fat , enough for one craft of lamp oil, I could make 24 tallows which would enable me to make 12 portions of lamp oil.

Tainted tallow : Should follow the same logic as the other tallow recipe, 3 tainted fat for 12 tainted tallow along with the same proficiency requirement

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 7efd4f5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Extra Mutated Scenarios [extra_mut_scens],
    Magiclysm [magiclysm]
]

**Comment by chrispikula** [comment]
I thought that was because, with more refinement steps, you get more?

Isn't there slightly higher skill requirements as well, or am I remembering wrong?

**Comment by LeahLuong** [comment]
I think the reason it's tainted is because there are bits of blob in it. Refinement gets rid of some of it but you still end up w/ a tainted product & a lower yield. That part makes sense.

The process of refinement in all cases should be aided by proficiency &, if anything, refining tainted components should prob take _**more**_ skill. I think that's the part that needs fixing.

**Comment by chrispikula** [comment]
Ah, sorry, I mis-read the issue, and thought you were going with how biodiesel has different yields if you go direct from fat, vs indirect via tallow.  Ignore my mutterings!
