### ISSUE TITLE
wasp nest in dark skies above

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#55160]
### Describe the bug

a wasp nest spawned with no wasps

### Steps to reproduce

explore and find an empty nest

### Expected behavior

either a wasp nest with giant wasps or no wasp nest

### Screenshots

![image](https://user-images.githubusercontent.com/78816055/152695603-0d8e79cb-7bb1-4de1-9cce-605f78885071.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 372311f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Dark Skies Above [darkskies],
    Stats Through Skills [StatsThroughSkills],
    Bionic Slots [cbm_slots]
]

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
