### ISSUE TITLE
sulfur substitutes for black powder

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#55169]
### Is your feature request related to a problem? Please describe.

the lack of renewable black powder for non-nomadic runs

### Solution you would like.

the ability to use methanol, or ethanol as sulfur substitutes in black powder making

### Describe alternatives you have considered.

- the ability to use red phosphorus in place of sulfur and craft it renewably 
- sodium chlorate based explosives 

### Additional context

the purpose of sulfur is to reduce black powders ignition temperature, alcohols can replace sulfur in this role.

**Comment by oosyrag** [comment]
Ref [sulphurless black powder](https://pyrodata.com/definitions/Black-Powder-Sulphurless)

**Comment by ElfLeaderMike** [comment]
It says the sulfurless recipe uses isopropyl alcohol. Is there a reference supporting the use of ethanol/methanol?
Also is sulfurless black powder viable for use in all guns that black powder can be used for now? 

Currently the antiseptic recipe implies we have no Isopropanol in the game, but 70% Isopropanol is a very common antiseptic. This might lead into a separate discussion of having different antiseptics.
![image](https://user-images.githubusercontent.com/22645231/154019903-f08aec3d-8ee8-4091-9cd4-855e85c5547f.png)

**Comment by robotic-gamer** [comment]
it doesn't have to be specifically isopropanol, isopropanol was just given as an example of something that works that is pretty easy to get ahold of in the modern world. the only properties that make it work is its an low carbon numbered alcohol that is a good solvent. methanol and ethanol both also meet the definition of something that will also work. That being said isopropanol doesn't mix with salt which could make it work different. However that still means the closely related acetone could work as a substitute. acetone can easily be produced by dry distilling a mix of vinegar and limestone. if needed you could then hydrogenate acetone to isopropanol with hydrogen and a platinum catalyst https://www.researchgate.net/publication/49608535_Catalytic_Hydrogenation_of_Acetone_to_Isopropanol_An_Environmentally_Benign_Approach/fulltext/0e60c684f0c493afa4b5f26b/Catalytic-Hydrogenation-of-Acetone-to-Isopropanol-An-Environmentally-Benign-Approach.pdf

**Comment by wapcaplet** [comment]
Resolved by #55486
