### ISSUE TITLE
TCL drones cause extreme lag

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#55177]
### Describe the bug

The scanner drones in TCL scan the player every turn causing extreme lag whenever they are on screen.

### Steps to reproduce

1. Go to TCL.
2. Observe Drone behavior.

### Expected behavior

They should scan once and not repeatedly.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 72ce112 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots]
]

**Comment by andrei8l** [comment]
I've playtested in the TCL a little bit and I believe this is fixed after #58546. Can anyone confirm?
