### ISSUE TITLE
craftable red phosphorus

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#55170]
### Is your feature request related to a problem? Please describe.

lack of effectively renewable explosives

### Solution you would like.

craft able red phosphorus
recipe could be
bone meal + sand + charcoal ---> white phosphorus
the white phosphorus can then be turned into red phosphorus by heating in an air tight container

### Describe alternatives you have considered.

leaving as is.

### Additional context

bone meal is a stand in for calcium phosphate rock.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
