### ISSUE TITLE
Breaking all limbs stops time

### ISSUE THREAD

**Issue by Mikenyes** [CleverRaven/Cataclysm-DDA#55183]
### Describe the bug

If you break both arms and both legs, your base move cost becomes 0, and you can move around at light speed while prone.

### Steps to reproduce

1. Make a new player
2. Break all limbs
3. Observe that your base move cost becomes 0 and that enemies do not move no matter how many tiles you crawl

### Expected behavior

I would expect that with 4 broken limbs, I would barely be able to crawl a tile in several minutes.

### Screenshots

![image](https://user-images.githubusercontent.com/25803648/152738145-e6957b7b-318f-42cd-933b-a49ea2283360.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-5865-g71e19456d3-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by dseguin** [comment]
This is an oversight from #54194. I forgot to add a max value to the crawl modifier :P

Anyway, the fix is dead-easy:
```diff
diff --git a/data/json/character_modifiers.json b/data/json/character_modifiers.json
index a273149988..26527a67ea 100644
--- a/data/json/character_modifiers.json
+++ b/data/json/character_modifiers.json
@@ -88,7 +88,7 @@
     "id": "crawl_speed_movecost_mod",
     "description": "Crawl speed movecost modifier",
     "mod_type": "x",
-    "value": { "limb_score": "crawl", "nominator": 1.2 }
+    "value": { "limb_score": "crawl", "max": "max_move_cost", "nominator": 1.2 }
   },
   {
     "type": "character_mod",
```
