### ISSUE TITLE
Feral Humans/Tough Zombies should spawn inside dojos 

### ISSUE THREAD

**Issue by 7erracotta** [CleverRaven/Cataclysm-DDA#55191]
### Is your feature request related to a problem? Please describe.

I think the dojos in the game are  currently VERY low risk with high reward, as martial art styles with the right character can be incredibly powerful and it can be pretty easy to just walk in and out of a dojo with little conflict.

### Solution you would like.

about one feral human or two to four tough zombies should spawn in the locker rooms/ main room of dojos to help increase the difficulty of the location and satisfaction of getting a martial arts book.

**Comment by ka3ax01** [comment]
Can I work on this? I am looking for my first contribution. If you let me try this issue, can you navigate through all of the processes that I should know?

**Comment by NetSysFire** [comment]
You do not need to ask. Just read [CONTRIBUTING.md](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/.github/CONTRIBUTING.md), create a PR fixing this and also specify a closing keyword to link your PR to this issue so if it gets merged this issue gets closed.
