### ISSUE TITLE
Honey should be able to be used as a weak disinfectant.

### ISSUE THREAD

**Issue by Nore5515** [CleverRaven/Cataclysm-DDA#55190]
### Is your feature request related to a problem? Please describe.

Honey has surprisingly significant healing properties, including antibacterial. In game you cannot smear honey over a dirty wound in an attempt to disinfect it. 

### Solution you would like.

Knowing that honey is usually found in bottles that have 30+ honey, having 30 weak disinfectant from a single kitchen would be ridiculous. 
I imagine something like "honey smeared bandage" could have a very low antiseptic property and cost 1 rag and 10 honey to make. Same way that an antiseptic soaked rag works, but with a weaker antiseptic property?

### Describe alternatives you have considered.

- Not implementing this.
- Concentrated honey that can work as a disinfectant (same way as making makeshift antiseptic, but weaker).

### Additional context

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3609166/

"The antimicrobial activity in most honeys is due to the enzymatic production of hydrogen peroxide. However, another kind of honey, called non-peroxide honey (viz., manuka honey), displays significant antibacterial effects even when the hydrogen peroxide activity is blocked."

I'd be willing to try to implement this! Seems simple enough...

**Comment by Venera3** [comment]
Gods no. Honey can be a not-always-horrible cover on a simple wound, but we don't *have* simple wounds - the only kind we track are complicated bites, which is not something to just smear something on and forget.

For that matter, we also don't have any"weak" antiseptics, the only distinction being "do you need one or four doses", which is very optimistic.

**Comment by Nore5515** [comment]
Ah, alright. Would having it instead be a slight upgrade to the standard makeshift bandage work then? Instead of being very poor bandaging quality, just poor?

**Comment by Zireael07** [comment]
> For that matter, we also don't have any"weak" antiseptics,

Nit: we do - cattail jelly.

**Comment by Nore5515** [comment]
Cattail jelly is actually what got me down the rabbit hole of natural antiseptics! Honey has some quite impressive healing properties, so if it can't be used as an antiseptic, it should absolutely improve healing speed/bandage quality. One could even sterilize the honey for medical use.

To be clear, the actual antiseptic properties of honey comes from the hydrogen peroxide within it (and the extremely high sugar content). It's honestly quite impressive.

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6589292/

**Comment by AcidAntOnAMinefield** [comment]
> For that matter, we also don't have any"weak" antiseptics

We do. Aside the Cattail Jelly referenced above, Antiseptic and Antiseptic Powder have a disinfectant_power of 4. Makeshift Antiseptic has a disinfectant_power of 3 and the alcohol wipes have a disinfectant_power of 2.

**Comment by estebandellasilva** [comment]
While i do think this is a neat idea - reading different articles most state that honey should mostly be used for oral consumption (sore throat and so) - yes it can be used to treat wound but as it stand its a special honey that also has been treated - if you want to implement it it would be some kind of special find but not the basic run of the mill stuff you find in every home.

**Comment by Nore5515** [comment]
Honey for medicinal uses is recommended to be sterilized via gamma radiation, so that works out. Sterilized honey could be a rare find, and I suppose you could irradiate your own in an irradiation plant! Although if you're doing that, you likely don't _need_ sterilized honey.

(relevant article)
https://pubmed.ncbi.nlm.nih.gov/7556583/

**Comment by estebandellasilva** [comment]
Yes but you are ignoring the main point - Manuka Honey from New Zealland ist the Honey they say it has these high antibacterial properties for woundhealing - because of its high MGO levels (more than 100mg/kg) normal Honey has a lot less and iss less effective in this regard.
So unless this specific honey is used that effect of the honey would be a lot less as an antispetic

**Comment by Nore5515** [comment]
That's actually a type of honey that has no hydrogen peroxide but still manages to maintain antiseptic properties. All normal honey holds antiseptic properties (due to the hydrogen peroxide activity). 

(also relevant article)
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3609166/

**Comment by estebandellasilva** [comment]
I get you point - but they always talk about MEDICAL GRADE HONEY - the normal Stuff iss not usefull in that regard

**Comment by Nore5515** [comment]
Huh! Did some research, table honey _can_ be used as an antibacterial, but it varies wildly based on what type of honey. From what I understand it varies based on where it came from (i.e. lavender and eucalyptus have strong antibacterial properties but buckwheat has none at all!). Some types of honeys can actually _cause_ infections due to their low antibacterial properties and the presence of infectious spores.

Since I am NOT about to add 17 different types of honey just to simulate a few antibacterial types, I'll go ahead and close this issue! Medicinal honey makes sense to be its own issue.

(last article)
https://www.hmpgloballearningnetwork.com/site/wounds/content/a-comparison-between-medical-grade-honey-and-table-honeys-relation-antimicrobial-efficacy
