### ISSUE TITLE
Improve filtering on CBMs/Spells

### ISSUE THREAD

**Issue by DoctorGoat** [CleverRaven/Cataclysm-DDA#55192]
### Is your feature request related to a problem? Please describe.

When playiing with a bunch of mods, you can end up with a frankly gigantic menu of spells or bionics, to the point where open magic menu. searching, and typing part of the spell name can be an optimal way to find a spell. This doesn't work for bionics, as you will end up using whatever is bound to / (which is, oddly, not blacklisted like S or A) and this can be a very bad time. For example, I was laying in bed, looking for my leukocyte breeder system, hit /, and used Sonic Resonator in bed. Thankfully, no glass was nearby. 

### Solution you would like.

The Sort Inventory Letters interface from Swap Inventory Letters and the + and - sort buttons that are used for the autopickup and zones menus would be very nice to have in these menus,, with +/-/whatever the sort key ends up being being blacklisted from being used for CBMs. 

CBMs sorted "manually" also end up quite backwards; blank ASCII leads to #()./@, then caps, then lowercase, then {|}. The A-Z are in the right order though, though they're followed by a few symbols and then a-z

Ideally, we'd have a-z/A-Z/symbols, and be able to sort with +/- 

### Describe alternatives you have considered.

Manually sorting the CBMs I use, uninstalling the ones I don't, only reading spells that I intend to use, etc. This is more effort than less, but being able to have the spell menu work like clothing sorting so you can tab between schools instead of having one singular list would be neat. 

### Additional context

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-5861-g3111ca2fdf [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Battle Maid Redux [battle_maid],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Cataclysm++ [Cata++],
    Magiclysm [magiclysm],
    Nechronica Redux [Nechronica_Redux],
    Pneumatic fun [pneumo_fun],
    XEAS [XEAS],
    Homestead Instruments Inc. [homestead],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    MST Extra [MST_Extra],
    DinoMod [DinoMod],
    <color_light_blue>Lighter Weariness</color> [light_weariness],
    Mythical Martial Arts [MMA],
    <color_yellow>Mythical Martial Arts - Mods Extension</color> [MMA_Mods_Extension],
    Extra Mutated Scenarios [extra_mut_scens],
    Food Irradiator [food_irradiator],
    Hydroponics [hydroponics],
    Morlock Village [morlock_village],
    Tankmod: Revived [Tankmod_Revived],
    Magiclysm Revamp and Additions [magicrevamp],
    ProjectKawaii [ProjectKawaii],
    Whaleys Hair Mod (UDP Tweaks) [WHALEYHAIR_UDP],
    Disable NPC Needs [no_npc_food],
    Easy Containers [sch_easy_containers],
    No Bionic Slots [no_cbm_slots],
    No Fungal Growth [no_fungal_growth],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    ZSFIXED_C:DDA Extra Professions & Gears [ZSFIXED_cddaxp],
    Arcana and Magic Items [Arcana],
    Hazel Mod [hazel_mod]
]

![image](https://user-images.githubusercontent.com/11859483/152827884-252fa771-62bf-4ea5-9aa2-2615aa6dd21c.png)

This isn't even including the CBMs I want most, I think I have to go fin Cata++ labs for those. I'm not using CBM slots because I'll do that in some other run, I'm having fun collecting them.

magicrevamp removes schools being exclusive, so you can be an biomancer druid or kelvinist stormshaper or whatnot. This admttedly does increase the bloat to the menu, but being able to sort them would still be pleasant.

**Comment by GuardianDll** [comment]
Also having `*` button would be pretty useful imo

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
