### ISSUE TITLE
Add diary action to the journal

### ISSUE THREAD

**Issue by Entity-y** [CleverRaven/Cataclysm-DDA#55201]
### Is your feature request related to a problem? Please describe.

The journal currently implemented in the game is bare-bones, acting more as a folder for holding notes and maps.

### Solution you would like.

Add the diary action to the journal. 

Have stats and progression only be updated when the journal and writing utensil is in the inventory or within line of sight.

### Describe alternatives you have considered.

Remove the journal from the game entirely and continue to have the diary be it's own thing in the UI.

Limiting the number of diary pages available to the amount of paper left in the journal to encourage making a new journal at some point.

### Additional context

Turning the diary into a physical item would add to the realism and enhance the flavor of multi-character worlds.

**Comment by chrispikula** [comment]
If this is done, I highly recommend that the current diary get migrated into such an item, even if it needs to poof into existence, otherwise I'll be significantly sad.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
