### ISSUE TITLE
Vehicle repair costs do not account for degradation

### ISSUE THREAD

**Issue by Waladil** [CleverRaven/Cataclysm-DDA#55200]
### Is your feature request related to a problem? Please describe.

When repairing a vehicle, there are resource costs, based on how badly damaged the part is. This repair will return the part to it's "maximum" HP, which is reduced by how badly degraded the part is. 

However, these two interact in an illogical fashion: If you have an object with very low current and max HP, the total cost for the repair is high, even though the amount of HP repaired is small. For example, repairing a steel plating at pink \ with pink degradation costs 54 welding resources plus 45 scrap metal. Repairing a different steel plating at yellow |\ and yellow degradation costs only 18 welding resources and 15 scrap metal, one-third the cost. But both repairs will restore roughly amount of HP. 

### Solution you would like.

To mitigate this, I think the game should scale the cost on degraded max part HP minus current part HP, so patching  nearly-broken items can be economically viable if replacements haven't yet been found.

### Describe alternatives you have considered.

The time investment could be left the same, since it stands to reason that trying to keep a nearly-broken thing together still takes more time and effort than small patches on a nearly pristine thing.

**Comment by Alex-Folts** [comment]
If i right understand, i test this some weeks ago: UI show wrong repair cost, but when you do repair amount of components used are proper, i.e. you pay with components for amount of damage actually restored.

I'll double check this, but it seems UI problem - it show wrong numbers.

**Comment by Waladil** [comment]
I'll confirm it as well. If so, that's just a straight-up bug that needs to be fixed
