### ISSUE TITLE
Inconsistent fatigue display

### ISSUE THREAD

**Issue by martosss** [CleverRaven/Cataclysm-DDA#55209]
### Describe the bug

My morale is suffering although my fatige level isn't displayed as "tired" or "sleep deprived"
Here is a view of the morale, saying "fatigue -40", yet you can see on the right my "Rest" status is not "tired", also in my character sheet my effects don't have "sleep deprived". In fact, I don't expect to get sleep deprived since I slept recently(1 day ago), so I should be still good to go. I'm expecting sleep deprived to kick in if I stay away 1 more day.
![image](https://user-images.githubusercontent.com/7064677/152994874-3a690468-d8f8-4bc4-ada2-01f8c510a5d9.png)
character sheet:
![image](https://user-images.githubusercontent.com/7064677/152995006-758ced73-1e2b-4930-9245-dd7fb1634f53.png)
sleeping info:
![image](https://user-images.githubusercontent.com/7064677/152995526-64186024-bb77-4a14-8cfe-79311cecd333.png)
Here's my recent action log
![image](https://user-images.githubusercontent.com/7064677/152996744-50166fe7-d601-4007-aa46-cec3696cf062.png)
![image](https://user-images.githubusercontent.com/7064677/152996675-f51c22bf-32db-4303-a342-fa9a69954c95.png)

### Steps to reproduce

A combination of crafting, drinking green tea(lowers fatigue), reading books and then crafting again.

I'm not sure when exactly it happens.
1) I was tired.
2) I drank some green tea and was not tired anymore due to the tea.
3) However, now the fatigue is climbing up and it is affecting my morale without being displayed on the right.

I tried walking for left-right for a few minutes and the "tired" message showed up 2-3 minutes later. So basically the Tired message is a few minutes late. So I suspect that during the 5minute interval where I'm exactly at 192 fatigue I'm getting morale loss, but I'm not getting that "Tired" message.

### Expected behavior

1) If my morale is suffering I should get the respective text, either "sleep deprived" in my char-sheet or "tired" on the right.

2) There should be some intermediate state of fatigue("slightly tired") where I don't incur any morale penalties, but I get a warning that I'll be getting tired soon, so I can take appropriate action, say drink tea/coffee, or avoid battle right at that moment.
- That should happen 1-2 hours before actually getting tired, so around 175 fatigue(currently the tired message comes up at 192 fatigue? And I gain 1 fatigue/5min?)

The idea is that I need to know that I'm tired in order to take respective measures. Without being informed that I'm tired I'm suddenly getting slammed with morale loss without any time to react.

### Versions and configuration

Win 8.1, v. Stable 0.F-3, tiles, English, vanilla

**Comment by Moumix3** [comment]
Isn't it because you're "weary" from the weariness system?

**Comment by martosss** [comment]
As far as I know "weary" and "concerning symptoms" don't affect your morale.

- I've had concerning symptoms and even the worse case - unnerving symptoms, but my morale was perfectly fine.
- Also, I've been very "weary" from cutting trees and my morale was still OK.

You can see the effect of weary in your character sheet(@) - it makes "hard actions" cost even more points, for example if you walk while being overburdened with weight and you're weary - you'll walk even slower, because you're weary.

But if you perform "non-strength-related actions", like reading a book, or cooking, or eating, that doesn't get penalized in any way from being weary. Weary only means you need to take a break from doing heavy lifting/hard work(chopping trees, carrying a lot of stuff ... )

- The problem here is that the "Tired" message gets dispalyed a bit later than the actual penalty for getting tired.
- A deeper problem for me is that there's no intermediate stage of "slightly tired" where you know you'll need sleep soon, but you're still not suffering morale due to tiredness.

**Comment by oosyrag** [comment]
Add "drowsy" as a fatigue state that has no effect before tired?

**Comment by l29ah** [comment]
I think it's a bug. Both of these should be tied to fatigue_levels::TIRED (src/display.cpp:753, src/character.cpp:3263) but somehow kick in at different time.
