### ISSUE TITLE
Varied NPC Biometrics, Please!

### ISSUE THREAD

**Issue by LeahLuong** [CleverRaven/Cataclysm-DDA#55206]
### Is your feature request related to a problem? Please describe.

Every NPC who survived the Cataclysm is 25 yo, 5'-9", Normal weight, & has A+ blood type.

Here's an example:

![Screenshot_20220207-193015](https://user-images.githubusercontent.com/91638992/152941468-16da8156-d838-4e3a-bc1d-a5d5418645d3.png)

### Solution you would like.

Ideally, these characteristics would be randomized w/in sensible, normal distributions.

Additionally, certain preset NPC's should have set values. For example, the beggar Brandon Garder's backstory would lead you to think he's @ least middle-aged; prob more than that considering his vision problems & apparent arthritis.

### Describe alternatives you have considered.

If the above can't be implemented, maybe shoehorn in some lore bits about why only people of a certain specific blood type, unique age, exact height, & particular morphology made it past the 1st days of the Cataclysm.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
