### ISSUE TITLE
Selected overmap tile is not centered

### ISSUE THREAD

**Issue by PlutusPleion** [CleverRaven/Cataclysm-DDA#55212]
### Describe the bug

The selected tile when looking at the map is no longer centered: 

It only started happening since today's PRs in experimental. I think what caused this is [#55161](https://github.com/CleverRaven/Cataclysm-DDA/pull/55161) . 

### Steps to reproduce

- Use latest experimental (one used in test is 2022-02-08-1127)
- Use any overmap tileset ( one in picture is surveyor's tileset)
- Open map
- Check for center/selected square to be offset (some tilesets are only offset at different zoom levels)

**Update: it seems using any overmap tileset causes an offset. Some tilesets are fine at default zoom, but changing the `z`oom will cause the offset issue for this tileset as well.**

### Expected behavior

Selected tile should be centered

### Screenshots

![This is an image](https://i.imgur.com/oxJ4oW5.png)

### Versions and configuration

2022-02-08-1127 Experimental

**Comment by PlutusPleion** [comment]
Reloaded on **older** experimental **2022-02-07-2131**

![](https://i.imgur.com/HLyCNYL.png)

and it's working correctly, so it's definitely from a recent PR.

**Comment by CalKerethi** [comment]
I'm using Chibi Ultica (if tileset matters for this bug), and it works perfectly at 100% zoom level but shows this behavior at any other.

**Comment by Night-Pryanik** [comment]
This is happening only with "use tiles to display overmap" setting toggled on. Since I don't use tiles for overmap, I didn't test this option when I was working on #55161.

**Comment by moll** [comment]
I can confirm this, too. When I zoom fully in, the selection circle is entirely out of view.

**Comment by Absurdides** [comment]
Also for me on latest experimental.

**Comment by Xenoamor** [comment]
That was my first attempt but it turned out to be something deeper. It was using the terrain tile size rather than the overmap tile size. Shall submit a PR shortly!
