### ISSUE TITLE
Vehicles shouldn't spawn with permanent damage

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#55213]
### Is your feature request related to a problem? Please describe.

The part degradation mechanic is intended to prevent the player from repeatedly repairing the same part over and over with no loss in quality. It takes several repairs to kick in, but most vehicles spawn with many parts already severely damaged beyond repair. This probably shouldn't happen because most vehicles have not been repeatedly repaired over and over enough for this to matter, they got into one wreck and that was it. Maybe a maniac came and slashed the tires and stole the steering wheel but those parts would have needed full replacements anyways.

### Solution you would like.

Pre-spawned vehicles should be able to be repaired to full strength. The cost in welding fuel and components is already considerable enough to make this a serious commitment.

### Describe alternatives you have considered.

Being able to actually replace parts (#53898) would help a lot since you'd no longer need to completely disassemble a section to replace a bad frame, but you still probably shouldn't need to hunt down several new vehicle parts to replace the unfixable parts of your vehicle at least until it starts becoming severely battle damaged.

**Comment by CalKerethi** [comment]
Counterpoint: I love playing with No Hope and most of the cars as wrecks, and having a little scavenger hunt for each part I want to replace in my fixer-upper. The random part degradation values enhanced that a lot. But for abandoned (not wrecked) cars in unmodded gameplay, I agree busted up but fully repairable seems reasonable.

**Comment by NetSysFire** [comment]
No Hope is great and I would say it is reasonable for vehicles to spawn fully busted if they were in a bad crash. It depends on the crash though. Seeing the big wrecks with multiple cars fused together, it makes sense for them to be beyond repair. Many of them may have also just burned to the ground which explains the extensive damage. Seeing all the "riots" and aggressive behavior the "rioters" have, it is no wonder that many cars, especially in cities, are badly damaged. However, this needs some more complex changes so assuming a car was not damaged by a crash or fire but by "rioters", the exterior has to be damaged to the point they can get into the inside of the vehicle. Alternatively there needs to be a broken or open window, unlocked door etc, you get the idea.

However, it may just be balanced enough if you can salvage the wrecks for parts to forge (quite literally) together your new parts or encourage using parts made from local plant or wildlife, which also requires lots of work to research, balance and add.

**Comment by a-chancey** [comment]
I'd counter this by directing you to [JustRolledIntoTheShop](http://www.reddit.com/r/JustRolledIntoTheShop) on Reddit. 

People drive some nearly totaled cars IRL. Not everyone has the money to keep their car in pristine condition. 

For wheel damage, maybe they are balding or bulging on the sidewall. Maybe they backed into a parking lot light pole and bent the frame.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
