### ISSUE TITLE
Attempting to pick up a battery inside a tool and then [w]ielding the tool crashes the game

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#55227]
### Describe the bug

segfault crash. [w]ielding the tool while having the battery highlighted to be picked up causes this in the pickup menu. not sure if it affects other things as well, I did not see the crash when trying to do the same thing with a cardboard box of candy peanuts (with cardboard box as the "tool" and peanuts as the "battery"

### Steps to reproduce

self explanatory. I killed a zombie scientist and did this by accident causing the crash and then could consistently reproduce it

### Expected behavior

no crash

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 44b27ad [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Hope [no_hope]
]

**Comment by dseguin** [comment]
#### Some missing details:
- The crash only occurs if the player's inventory is full
- There must be other items in the pickup list other than the tool/battery
- Crash log: [crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8029054/crash.log)

#### Steps to reproduce:
1. Spawn 100 rags (or enough small items to fill inventory)
2. Spawn a flashlight and a light battery
3. Reload flashlight and drop it
4. In the `g` pickup menu, select the battery for pickup, then `w`ield the flashlight

![pickup](https://user-images.githubusercontent.com/12537966/153113568-5bc0ca36-ac42-4d29-a473-83aaa02aca74.png)

#### Possible fix (briefly tested, appears to work):
```diff
diff --git a/src/inventory_ui.cpp b/src/inventory_ui.cpp
index 807886d607..c407a01718 100644
--- a/src/inventory_ui.cpp
+++ b/src/inventory_ui.cpp
@@ -3062,7 +3062,9 @@ void pickup_selector::apply_selection( std::vector<drop_location> selection )
 {
     for( drop_location &loc : selection ) {
         inventory_entry *entry = find_entry_by_location( loc.first );
-        set_chosen_count( *entry, loc.second + entry->chosen_count );
+        if( !!entry ) {
+            set_chosen_count( *entry, loc.second + entry->chosen_count );
+        }
     }
 }
```
