### ISSUE TITLE
Recipe copy-from doesn't carry over activity_level

### ISSUE THREAD

**Issue by Jarewill** [CleverRaven/Cataclysm-DDA#55224]
### Describe the bug

When fixing chainmail armors, I noticed the normal chainmail armor and it's kevlar variant had different activity level scores.
Normal chainmail armor was activity level light, while the kevlar one was moderate.
Looking at the recipe code, I noticed the kevlar recipe didn't specify an activity level, but rather copied-from the normal one, which did specify activity level light.
I think that might be an oversight.

### Steps to reproduce

- Look at recipes for "chainmail armor" and "kevlar chainmail armor" and compare activity times.

### Expected behavior

For kevlar chainmail armor to also be a light activity, considering both actions are identical and the kevlar recipe copies-from the normal one.

### Screenshots

![image](https://user-images.githubusercontent.com/98614648/153091298-3dc32f8d-2ae7-4830-b18c-b72557f94aaa.png)
![image](https://user-images.githubusercontent.com/98614648/153091299-3b4624af-fcf8-483e-aea5-5a3ac6e9f23e.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 9fb7080 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots]
]

### Additional context

I can fix this in the PR I opened for chainmail armor fixes, but I feel like this is an oversight worth reporting first.

**Comment by anothersimulacrum** [comment]
That is more or less a symptom of the fact it is supposed to be mandatory, but is not https://github.com/CleverRaven/Cataclysm-DDA/blob/44b27ad5d59807c7e6b0246a9cf3e0c5db87027e/src/recipe.cpp#L243
