### ISSUE TITLE
You can have Bad Knees and Strong Knees mutations at the same time

### ISSUE THREAD

**Issue by MaxD98** [CleverRaven/Cataclysm-DDA#55237]
### Describe the bug

As title says, you can gain the Strong Knees mutation from the Batrachian tree even if you already have Bad Knees.

### Steps to reproduce

1. Choose the Bad Knees trait from character creation or debug menu.
2. Gain the Strong Knees mutation from debug menu or mutagen.
3. See that you can have those two mutations at the same time.

### Expected behavior

I expected that those mutations should be mutually exclusive like Fast metabolism and Light Eater.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: d065e00 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by LeahLuong** [comment]
Related issue in #54602. Still awaiting confirmation & application of "Bug" tag.

**Comment by robotic-gamer** [comment]
another related issue that was brought up on the forums was how switching healer mutations has a few problems (apparently poor and imperceptive healer can't be mutated out of by anything in game) https://discourse.cataclysmdda.org/t/how-do-you-get-the-fast-healer-mutation/27586/12

**Comment by MaxD98** [comment]
> another related issue that was brought up on the forums was how switching healer mutations has a few problems (apparently poor and imperceptive healer can't be mutated out of by anything in game) https://discourse.cataclysmdda.org/t/how-do-you-get-the-fast-healer-mutation/27586/12
Thanks for that info. I also tried to get Fast Healer from both Imperceptive and Poor healer starting traits and failed. But then (thanks to amazing Hitchhiker's Guide) I found that both Imperceptive and Slow Healer traits now have "purifiable": false" at their JSON, so I don't think of any kind of oversight. Seems like some intentional nerf, maybe because you can now not only level up your  first aid skill  but you also can gain the "Wound Care" and "Wound Care Expert" proficiencies, which as I think can boost your healing rate, especially the "Wound Care Expert".

**Comment by MaxD98** [comment]
> Related issue in #54602. Still awaiting confirmation & application of "Bug" tag.
> 
> Not sure this is a good 1st issue if the root problem is more widespread than a simple JSON edit.

Seems that some mutations now are some kind messed up. When I was testing inability to gain Fast Healer from Poor and Imperceptive Healer starting traits, I also discovered some strange thing - my Fragile trait should be transformed into Resilient after crossing the threshold, but somehow this strange thing just happened
![Screenshot_103](https://user-images.githubusercontent.com/99319891/153657924-1da5bf7e-3969-4d86-a99b-17c500c03aad.png)

**Comment by robotic-gamer** [comment]
that does not look like like a bug, what's going on is it is taking you towards resilient but did not mutate you enough. specifically you need extremely strong before you can get resilient (at least according to the wiki). helping to confirm this is how strength mutations like strong are technically not a mutation in medical but medical mutagen gave it to you anyway because it is mutating you towards extremely strong so it can give you resilient. easy way to confirm this is to take more medical mutagen.

**Comment by MaxD98** [comment]
Yes, seems that I forgot about how exactly mutating in Resilient works. I remember that I was mutating into Resilient from Pain Junkie in 0.F-3, but I never encountered situation like this before or just don't remember for sure. Maybe this is recent change to mutation process with all mutagens now work like some kind of vitamins. Anyway, I don't have much experience with new experimental and can mistake about this new stuff.
