### ISSUE TITLE
Chop Shop order does nothing

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#55232]
### Describe the bug

When activating the Chop Shop order for a garage in a 0.E0 save it does nothing, i.e. returns immediately without asking to send anyone.

Edit: The job doing nothing might be caused by hacking in the code. However, the mission still shouldn't appear unless it can actually be performed.

### Steps to reproduce

Haven't verified anywhere else, so take the steps with a grain of salt.

1. Load a save with a garage expansion.
2. Go to the bulletin board and tab to the garage.
3. See the Chop Shop order.
4. Activate the Chop Shop order.
5. You're returned without any feedback.

### Expected behavior

The Chop Shop order shouldn't be available, which should make the Garage expansion unavailable (as that's the only functionality of it in both versions, as far as I know).

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-5950-g44b27ad5d5-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

### Additional context

I was mucking about the code and saw that the code for returning from the Chop Shop displayed a message about it being deprecated. Decided to try the functionality in an existing save and found the order is still there, but does nothing. I believe the order should be removed completely.

**Comment by a-chancey** [comment]
Chop shop should just be removed as a mission, as you now just use a vehicle deconstruction zone

**Comment by LeahLuong** [comment]
Using this famp directive in 0.F-3 gives an error message telling you to use a vehicle disassembly zone instead. The order prob should be removed when some1 gets a chance but I'm not so sure about the garage expansion itself. I believe there is work underway to cause vehicle degradation over time (related to portal storms??). The garage could help w/ protecting your vehicle(s) & may gain future utility as well.

**Comment by PatrikLundell** [comment]
I'm not talking about removing the garage, only the task. However, since it's the only task provided by the garage, it causes the garage to disappear as a reachable tab on the bulletin board and get the same status as e.g. the Storehouse expansion, which doesn't provide any bulletin board actions either once it has been fully constructed.

As an aside, I would want the garage to be possible to be upgraded to a ceiling mounted lifting system so that all tiles on the active part of the garage had the lifting capability. However, that would require someone to implement the code for the underlying functionality.

**Comment by a-chancey** [comment]
I don't think the tab being unreachable would be a problem once it's fully upgraded. 

I do agree on ceiling lifts - followers seem to not be able to use lifting quality from stationary lifts around the vehicles so I always have to remove the wheels, hubs and engine before they can finish

**Comment by PatrikLundell** [comment]
I actually haven't had any problems with companions using stationary lifts around the vehicles provided they're placed to reach everywhere (usually requires 3 lifts). Wheels weren't removable by companions when I used the functionality, so I had to remove them manually, and one vehicle (APC?) has a very fiddly layout that allows you to remove the engine only if the lift is in a specific tile and you stand on that tile as well because of visibility issues.
The problem with using the current lifts is that they have to be placed right next to the vehicle to cover the required area, and you have to move them to get any vehicle with wing mirrors in between them. Also, the lifts are vehicles themselves and will get dismantled if they're inside the dismantling zone, requiring you to constantly fiddle with the zones to make sure you cover the whole vehicle but not the lifts (which may need to be either in front or behind the vehicle to get full coverage).
I've made sure the companions carry the required equipment in their inventory, including jacks, to make sure they can remove everything.
