### ISSUE TITLE
Matchbook Charges - Red Phosphorous

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#55248]
### Describe the bug

Making Red Phosphorous with Matchbooks doesn't seem to try to count the available number of charges, so when you batch make it, 50 is a 'possible' option, even if you only have 21 total available 'charges'.

It's also a zero-weight craft, which pops up an error complaining about that.

### Steps to reproduce

Get 20-40 matchbook charges
See that in batch crafting red phos, 2,3..50 are all white text, suggesting you have the required components.
Get the error pop up on crafting
Fail to complete the craft if you chose 2 or more to batch.

### Expected behavior

As per other crafting.

### Versions and configuration

Win 10, Tiles, d08dddd

### Additional context

 DEBUG    : Item 'in progress red phosphorous (0%)' with zero volume

 FUNCTION : int item::charges_per_volume(const volume&) const
 FILE     : src/item.cpp
 LINE     : 1124
 VERSION  : d08dddd

**Comment by robotic-gamer** [comment]
I'm pretty sure the issue is that the matchhead charges are being used up as a tool and not a component

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
