### ISSUE TITLE
My Rocket Is Too Long (Must See!)

### ISSUE THREAD

**Issue by LeahLuong** [CleverRaven/Cataclysm-DDA#55251]
### Describe the bug

![Screenshot_20220209-090450](https://user-images.githubusercontent.com/91638992/153298790-1293167c-8133-448b-a1d6-1d8daa4bfe70.png)

There it is. Here's a link to a website listing its IRL specs:

https://arconpartners.net/products/ammunition/grenade-launchers/40-mm-og-7v-round-with-high-explosive-fragmentation-grenade-og-7-for-40-mm-hand-grenade-launcher-rpg-7v/

595mm converts to ~24".

### Steps to reproduce

Kids view this website!

### Expected behavior

I expected that OG-7V 40mm rocket level would increase, because all other skills can increase in level.

### Versions and configuration

Android 0.F-3 Tiles English vanilla

### Additional context

Just a little off the top, please. Weight should prob be scaled down to 3.86# & V may need adjustment.

**Comment by catdach** [comment]
Based on these calculations **volume** should be about 0.75L:
![image](https://user-images.githubusercontent.com/93795131/153305253-305ab9b3-e60b-415c-8148-036b35f8fb5d.png)
As for weight, 1.75 kg is about 3.85 lbs (should that be added to the "weight of fused grenade"? I have no idea)
