### ISSUE TITLE
Add keybinds for get_liquid_target actions

### ISSUE THREAD

**Issue by haveric** [CleverRaven/Cataclysm-DDA#55277]
### Is your feature request related to a problem? Please describe.

While working on https://github.com/CleverRaven/Cataclysm-DDA/pull/55230, I found that the only hardcoded keybind left was the 'c' for `Pour into a container`.

Benefits of adding keybinds:
- Anyone can customize them if they want
- Can remove the last hardcoded keybind from the tutorial

### Solution you would like.

Add new keybinds for:
- Consume It
- Pour into a container
- Pour on the ground

Update the hardcoded `<color_yellow>'c'</color>` with `<keybind:LIQUID_POUR>` (or whatever the name ends up being) in the tutorial.json once https://github.com/CleverRaven/Cataclysm-DDA/pull/55230 is merged.

### Describe alternatives you have considered.

Leave it hardcoded. This is a pretty minor inconvenience.

### Additional context

![image](https://user-images.githubusercontent.com/985060/153119941-29901386-e3b1-410b-903a-1453b7577344.png)

**Comment by Maleclypse** [comment]
Closed via #55310

**Comment by haveric** [comment]
@Maleclypse This is not fixed by #55310. That was a misunderstanding of the change needed for this and that part was reverted. This request is to add new keybindings to the liquid actions menu and only then update the one hardcoded keybinding left in the tutorial, which have not been implemented yet.

**Comment by haveric** [comment]
@Maleclypse Sorry to ping again, but can you re-open this issue as it is not fixed by the aforementioned issue?

**Comment by Maleclypse** [comment]
No problem:)

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
