### ISSUE TITLE
ACTION_PICKUP lessons are not triggered in the tutorial

### ISSUE THREAD

**Issue by haveric** [CleverRaven/Cataclysm-DDA#55276]
### Describe the bug

ACTION_PICKUP lessons are not triggered in the tutorial. From what I have tested, the `item it( player_character.last_item, calendar::turn_zero );` seems to return a null item.

Discussion from Snup on discord:
"So what I think is supposed to happen is that player_activity::do_turn does the action that sets Character::last_item. Then game::handle_action calls the part you quoted there and after that Character::process_turn sets last_item back to itype_null. What confuses me is that there are two blocks that call player_activity::do_turn in do_turn. The second one happens after game::handle_action is called, so it would always be itype_null in there. But I don't know why the first one wouldn't handle it already. Can't say much more without stepping through it in debugger, but I can't do that right now."

Because these lessons are not sent, I believe there are other lessons that will be missing/broken as well since `LESSON_GOT_WEAPON` is supposed to spawn a zombie, but that will be one or more new issues once this is solved.

### Steps to reproduce

1. Start the tutorial
2. Progress to the gun racks or armor sections.
3. Pickup an applicable item (armor, gun, ammo, lighter, food, melee weapon)
4. No LESSON_GOT_<thing> message appears

### Expected behavior

Pickup actions should show their lessons.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 03e7363 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by LeahLuong** [comment]
#55230 is merged but this thread isn't closed. Shouldn't it be??

**Comment by haveric** [comment]
> Shouldn't it be??

No. I had a task there to create this issue, which is why the reference exists.
