### ISSUE TITLE
Mouse's Archery Re-integration Ideas/Plans

### ISSUE THREAD

**Issue by Custard-Mouse** [CleverRaven/Cataclysm-DDA#55278]
### Is your feature request related to a problem? Please describe.

I decided to take a peak at archery since I was hoping to implement some new recipes and items to expand the diversity of bows players have available, while digging through the current system and doing some online research I found a number of interesting facts that showed both some valid things the current system assumes, but also some major issues the current system has.

I'm planning on trying to tune myself up to task to begin integrating a new system but my familiarity with the code base and with C++ is very very low, for reference my one and only PR so far is some small string changes. I'm hoping I can get both feedback from other contributors and players for ideas and changes to the system I'm planning, and would welcome any assistance on C++ implementation or guidance.

### Solution you would like.

**Systems for review:**

- (1)-Bow Damage

    - (A)-The Current System

        The current system works on a educated assumption that arrow damage is proportional to the momentum it carries. Each bow was calculated through a chart to find how it performed with a arrow of a fixed weight of 30 grams, or around 460 grains. The momentum value achieved through this calculation was weighed against recommended momentum values for hunting certain game, this was to figure out how each bow should be performing in game, as there was now the constant, "IRL this bow's momentum value with this arrow can kill X with regularity, we know X has this much HP and Armor so this bow should be able to do this much damage". At some point this was able to be simplified to a rule to take the slugs value multiply by 150 and then subtract that by 32 and that would be base damage, later down the road the 5x crit change occurred and some tweaks happened during that which makes this rule not seem super applicable any more, but for now a assumption that something like a new bow in this system would have it's base damage calculated by taking it's slugs value with a 30 gram arrow, multiplying by 150, subtracting 32, and then dividing by 5 would be close to where its base damage would end up.
        
    - (B)-The Problems with the Current System

       While the assumption of arrow damage being proportional to it's momentum seems valid, a number of issues crop up with the implementation of this. In archery there is a term called GPP, (Arrow) Grains Per (Bow Draw Weight) Pounds. While compound bows used for target shooting will often shoot arrows that have a quite low GPP ratio, from 5-7, this low GPP ratio is known to be problematic for more traditional bows, and is why modern bows outperform traditional bows in speed. On many forums for bowhunting or traditional archery I found that most folks would reference what was known as the 10GPP rule, this was mainly for comparing different bows but was also due to knowledge that around 10GPP is what most bows should be shooting for hunting. For reference, here are some GPP values for the currently included self bows in the game shooting the currently assumed 30 gram (460 grain) arrow, the survival bow is at a whopping 15.33GPP ratio, the short bow is at a slightly light 9.2GPP ratio, the longbow is firing quite low at around a 6.57GPP ratio, and the wooden greatbow is firing incredibly low at a 3.17GPP ratio. Almost none of the self bows besides the short bow is firing anywhere near a appropriate hunting load, which means the momentum they can push a arrow to is going to suffer greatly, for the greatbow I was able to find this video to get some better estimates for what a greatbow/warbow can achieve (https://www.youtube.com/watch?v=OyEc8tkGBJc&t=39s) in this one of the arrows used is at 75 grams (~1160 grains), which in relation to the 145lb bow he fires it out of has a 8GPP, slightly low but much better then 3.17, when I calculate the momentum from the achieved FPS of the arrow (194.6fps) and its weight we get a whopping 1.0 slugs, compared to the current value that the 145lb greatbow in game is balanced around which is 0.51 slugs. There is another factor realism wise that crops up, too low a GPP out of a traditional bow can cause some big problems. The first of these issues is that unless the arrow is strong enough, the force being applied to it can cause it to break violently, potentially harming the shooter, secondly a low GPP out of a traditional bow forces the bow itself to absorb more energy, which can damage or break the bow. Overall most bow's are performing outside of their effective hunting GPP, which is currently compacting the spread between weaker and more powerful bows and limiting the usefulness of bows above around 50lbs draw weight.
    
    - (C)-The Quick Fix for Damage

       Add new arrow types that would be within these bows 9-11GPP ratio range, lock bows to only shoot proper arrows for their draw weight, and simply calculating a new slugs value and using that to determine damage, while this would be a much quicker patch then anything else and would require no systematic changes it does still leave bows in a relatively odd place IMO and requires any added bows to be recalculated through a formula to determine base_damage.
            
- (2)-Accuracy and Range
    
    - (A)-The Current System

       Admittedly this is where my knowledge of the codebase drops off a cliff, I'm not yet familiar with the current system to know if there really are any issues, but mechanically I would like to suggest some changes to take advantage of the overall solution to archery I think should be implemented.
            
    - (B)-The Suggested System

       Accuracy in archery IRL seems to come from one place primarily, skill, a skilled archer can adjust to different bows and arrows with varying GPP and find their groove in terms of precision. A novice archer on the other hand will run into issues with accuracy, both their nominal precision should be lower but they should also struggle to compensate for heavy arching arrows as well, faster and flatter shooting lighter arrows should give a novice archer a edge over when they try to shoot slower and more arched heavier arrows. This change would give players a reason to fire arrows with lower GPP values even if it would mean them losing some damage, if a player wielding a 70lbs longbow knows that they still do enough damage to take down a deer with a lighter arrow, but that it'll be easier for them to score that shot, they'll be able to take advantage of the versatile tool that is their bow in a new and interesting way. What I am currently struggling with is how to order these modifiers, skill should be the primary modifier, kicking in after all other factors most likely as to represent a skilled archer being able to compensate for the non-optimal set-up they might be using.
    
        Range is a tough question, mainly due to their being so many factors, a simple answer would be just to take the FPS that the arrow would be launched at out of that bow, multiply by a constant, and use that to determine what range that bow and arrow combo would have, since bows and arrows of different types are cross-compatible this would mean a integration on the C++ side of things and being able to pass into the UI the range as was calculated. This solution might cover the bases but some other factors that could be included in the calculation if we can find some reasonable constants for them would be arrow mass, cross_sectional_area, and drag, though due to the the games abstraction with and usage of a tile based system even just something like adding using arrow mass and FPS would probably be as accurate as the calculation would need to get to cover the bases. Like the accuracy system this will probably usually mean that a lower GPP arrow out of a bow will actually benefit here, giving the players even more of a reason to try different arrow weights to see how their system performs. This would bring a quite nice layer of authenticity to bows since it seems much of the discussions around archery center around people preferences of bow/arrow combinations, and what sort of GPPs they aim for to accomplish certain tasks (hunting, target shooting, or fun).

**A unified yet work intensive solution:**

- The sort of unified systems solution I see to this would be mostly all on the C++ side I imagine, though with it the JSON structure for bows and arrows would see some changes as the bows and arrows themselves wouldn't be holding any damage or range information. On the C++ side, when bow range needs to be passed upon the player hitting "f" to bring up the firing screen there would have to be a function that would take in draw_weight from the bow and arrow_mass from the arrow and return a range value based on the calculated GPP ratio and multiplied by some modifiers and a constant, when the player aims at a target the accuracy of their shot I base_dispersion should first be effected by the speed at which their arrow will be shot at, with a arrow that's faster then some neutral point benefiting in accuracy and a arrow slower then that point losing some accuracy, this new value should then be effected by the skill and proficiency effects before being passed to the UI, when the player decides to take a shot there should be a check depending on bow_type that will determine if the arrow they were shooting was dangerously light for their bow, if it was it'll determine how dangerously light it was and roll based on that severity this will end with either the shot being made with no ill effects, the shot being made but the bow being damaged to some severity, or the arrow breaking and the player receiving a wound on their arm to some severity, potentially also a combination of the last two if the roll is very bad, when damage needs to be passed there would be a calculation based on the GPP of the arrow in relation to that bows draw_weight that would be passed as the damage before other calculations (most likely including the arrows damage multiplier) are made. Beyond the system side changes there would need to be a variety of arrows added to be able to allow these bows some more tools for their toolkits and enable them to fire at a appropriate hunting load. 

- One of the primary advantage of this system is a major hands off approach to introducing more bows and arrows in the future, accuracy, range, and damage would all be calculated by the C++ meaning all someone would need to add to the JSON would be the bows bow_type and the draw_weight of that new bow, and arrows would lose the need to implement any range or damage information on them (besides a damage multiplier for arrow head shape). The major player side benefit of this solution is bows feeling massively more authentic and a deeper system they can tinker around in to get the performance they want.
          
**Other thoughts and or down the road things I'd like to do:**

- I originally was hoping to just try and add some new bows and arrows and try and add curing wood staves as things into the game, but as I looked into the system for bows I found that this all lay ahead of those really being a primary concern for archery. I would still like to do this at some point and add in a handful of bow technologies the player can craft and give each type a few options for bow_length, like a short bow, hunting/longbow, and war/greatbow variety for each type, most likely the short bows would receive some flat efficiency downgrade, while the greatbows get a efficiency increase.

- I would like to see some system in the crafting menu where after the player selects a bow or arrow to craft they are given a screen to determine some other variables, mainly this is so we could add a variety or spectrum of draw_weights for certain bows and of masses for arrows and allow players to craft these things without having a cluttered crafting screen.

- Down the line I think that finding a way to benefit better bowyers with just making flat better bows of any kind would be nice, but trying to have that many variables seems a bit like a chunky bit of coding to do. Basic thoughts would be some sort of efficiency modifier that a bow would be calculated to have on craft, better bowyers would roll a better number here as well as potentially being able to craft a bow with a specific draw_weight with less variability, maybe also increasing bow durability with bowyer proficiency as well. This idea would be cool, but probably even more difficult to implement with fletching and arrows.

### Describe alternatives you have considered.

- There is certainly a quick fix for the damage issue certain bows have, but it does nothing to engage with the systems behind bows that would make a authentic implementation quite difficult.

- I am going to be working on bootstrapping up my knowledge of the codebase to begin trying to understand it enough to implement these ideas, but any cooperation or guidance on these ideas would be massively beneficial.

### Additional context

Any feedback on any of the ideas I've built up, the structure of this roadmap, or the concepts of it would be greatly appreciated. Any help or guidance in terms of following through with implementing such a system is also appreciated. :D

**Comment by bombasticSlacks** [comment]
I'm currently working on perspiration but that *seems* to be wrapping up.

After that I can JSONify draw_weight and arrow_mass if you would like it's not the most obvious thing to get working if you aren't familiar with it. Once that is the case you could add them as attributes and then use them while tinkering.

However I would say that you could perhaps abstract those from the current "min_strength" of bows and the literal weight of the arrows. However if you want a more correct "draw_weight" that is exactly the value as written, I think it would make sense. 

> player decides to take a shot there should be a check depending on bow_type that will determine if the arrow they were shooting was dangerously light for their bow, if it was it'll determine how dangerously light it was and roll based on that severity this will end with either the shot being made with no ill effects, the shot being made but the bow being damaged to some severity, or the arrow breaking and the player receiving a wound on their arm to some severity, potentially also a combination of the last two if the roll is very bad,

For this I would recommend just having it not let the player shoot arrows that light. Though I love a risky play of desperation our players like to hurt themselves with systems and then complain they are bad forever.

> and arrows would lose the need to implement any range or damage information on them (besides a damage multiplier for arrow head shape).

As far as I know arrows are already just a damage multiplier and a penetration value so it would just be about getting those to fit in the new system.

> when the player aims at a target the accuracy of their shot I base_dispersion should first be effected by the speed at which their arrow will be shot at, with a arrow that's faster then some neutral point benefiting in accuracy and a arrow slower then that point losing some accuracy, this new value should then be effected by the skill and proficiency effects before being passed to the UI

I believe a lot of this is already currently working in the system as is.

The only immediate thing I'm hesitant about saying would be doable is the on the fly range changes. It might be but I haven't looked at the code.

**Comment by LeahLuong** [comment]
Good to see archery in this game getting some attention. I believe bows have a system in place for tuning them for higher Strength users & perhaps this could be related to GPP & a good spot to briefly explain that to players.

**Comment by Custard-Mouse** [comment]
> Good to see archery in this game getting some attention. I believe bows have a system in place for tuning them for higher Strength users & perhaps this could be related to GPP & a good spot to briefly explain that to players.

They do! I'm looking at that right now to see if I can hook into where that system was and try and get it to return a value based on some rough assumption of the FPS of the arrow.

**Comment by Custard-Mouse** [comment]
Okay, new plan for range based on a conversation with Kevin on the discord, max bow range will be out at around 40 tiles, almost all bows will be able to start aiming at that range but actual effective range will be determined by skill and probably some other factors, lighter bows below a threshold (currently set to 70) will drop off from 40 tiles. I'm also trying to see if I can JSONize a draw_weight value, luckily it looks like I should be able to get arrow weight from the weight_to_info function that items have so no worry about making a arrow_weight value. I'm building my range changes currently and going to test out a short bow and long bow to see if the changes seem to have worked.

**Comment by martosss** [comment]
@Zireael07 A google search for "bow FPS" gives "feet per second"

**Comment by Custard-Mouse** [comment]
Okay, got a ugly system in place for now to scale bow range out to 40 tiles as bow draw_weight goes up to 70lbs (which is what the long bow has) I may set-up this calculation to also use arrow weight, since something like the explosive arrow should massively impact the range you can reasonably shoot at. I'm going to have to tweak some things, mostly I'm going to have to add the STR_DRAW flag to the bows and switch back to the system that checks for that flag and not just PRIMATIVE_RANGED_WEAPON since that also covers bolas and the crossbows I believe. Next big system I need to go and poke at is damage calculations on hit, anyone know where I should start peaking at to find that stuff?

**Comment by Shodan14** [comment]
Looking forward to this, always loved archery in CDDA.

**Comment by NetSysFire** [comment]
Tried making arrows and bolts a bit more consistent in #52570 but failed due to merge conflicts and other priorities, feel free to utilize any ideas you may find useful.

**Comment by kevingranade** [comment]
I strongly recommend you start off with your "quick fix for damage" change, or even just splitting off custom arrows for the bows with the worst GPP matches with existing bows, i.e. the makeshift/survival bow and greatbows.

That will adress the worst issues, doesn't require any new logic, and most likely won't require walking it back later.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
