### ISSUE TITLE
Character catches common cold immediately after spawning.

### ISSUE THREAD

**Issue by Hatfish** [CleverRaven/Cataclysm-DDA#55287]
### Describe the bug

Created a blank character with no traits or hobbies, default stats, default profession and starting location, etc.  Immediately upon starting the game they came down with the common cold.

### Steps to reproduce

1. Generate a clean world and a clean character.
2. Roll the dice?
I tried to reproduce this a couple times with the same character to no avail.  It's probably an astronomically low chance to catch the cold this quickly.

### Expected behavior

Expected a fresh character to not start the game sick outside of scenarios which would cause it to happen.

### Screenshots

![image](https://user-images.githubusercontent.com/8237862/153639991-ebbff7b2-2627-4838-9685-71d5daff123d.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: cc83f7a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

### Additional context

[New folder.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8050634/New.folder.zip)
Here's the save and debug.log, in case that helps at all.

**Comment by oosyrag** [comment]
You got fantastically (un)lucky. 

In the code, there is a check if you got sick every 30 minutes, with the normal rate of 3 times a year for a normal non-disease resistant person, and half again as much for a healthy person. There is no artificial grace period of disease immunity for the start of the game. 0.08% chance of getting sick on any given check, and a 1/6 chance after that that it was a flu and not the cold.

I don't see any particular reason why a random survivor might be immune to sickness when the cataclysm hits. For how long would they have this immunity? It's not game ending, and I'd argue it even adds significant flavor to the character/playthrough.

**Comment by LeahLuong** [comment]
Yeah, this thread seems more humblebrag than bug report; that is, unless "bug" is taken to mean something else than it usually does here. If this happens so close to start & you don't feel like dealing w/ it, restart. Not like there aren't a plethora of worse things that can happen soon after making a char.

**Comment by Hatfish** [comment]
Alright, closing since it's not a bug.
