### ISSUE TITLE
Segmentation fault on game load

### ISSUE THREAD

**Issue by oosyrag** [CleverRaven/Cataclysm-DDA#55303]
### Describe the bug

Crash upon loading a save. Save attached.

May be related to other save corruption issues, but this is on stable and the others I found were experimental.

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8052633/save.zip)

### Steps to reproduce

Load game world Vandergrift - Brandon Little. Other characters work fine.
After loading and finalizing files, errors occur regarding items - locations and parents and targets. After skipping errors, game crashes.
Starting up game again shows "Segmentation fault" crash report.

### Expected behavior

Load savegame successfully.

### Versions and configuration

19:11:27.121 : Starting log.
19:11:27.121 INFO : Cataclysm DDA version 0.F-3
19:11:27.121 INFO : [main] C locale set to C.UTF-8
19:11:27.121 INFO : [main] C++ locale set to 
19:11:27.121 INFO : SDL version used during compile is 2.0.12
19:11:27.121 INFO : SDL version used during linking and in runtime is 2.0.12
19:11:27.141 INFO : [options] C locale set to C.UTF-8
19:11:27.141 INFO : [options] C++ locale set to 
19:11:27.141 INFO : Read Android system language: 'en_US'
19:11:27.141 INFO : Setting language to: 'en'
19:11:27.141 INFO : Language is set to: 'en'
19:11:27.141 INFO : Read Android system language: 'en_US'
19:11:27.326 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
19:11:27.852 INFO : Read Android system language: 'en_US'
19:11:27.852 INFO : Setting language to: 'en'
19:11:27.852 INFO : Language is set to: 'en'
19:11:27.852 INFO : Read Android system language: 'en_US'
19:11:28.022 WARNING : opendir [/storage/emulated/0/Android/data/com.cleverraven.cataclysmdda/files/mods/] failed with "No such file or directory".
19:11:28.057 INFO : Read Android system language: 'en_US'
19:11:28.062 INFO : Read Android system language: 'en_US'
19:11:28.062 INFO : Read Android system language: 'en_US'
19:11:28.062 INFO : Read Android system language: 'en_US'
19:11:36.888 INFO : Read Android system language: 'en_US'
19:11:36.889 INFO : Read Android system language: 'en_US'
19:11:36.890 INFO : Read Android system language: 'en_US'
19:12:02.294 WARNING : opendir [/storage/emulated/0/Android/data/com.cleverraven.cataclysmdda/files/save/Vandergrift/mods] failed with "No such file or directory".
19:12:07.616 INFO : Loaded tileset: Chibi_Ultica

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8052629/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8052631/crash.log)

**Comment by oosyrag** [comment]
Is it still the case that there's no built in auto backup or any way other way to roll back a save?

**Comment by LeahLuong** [comment]
Crash log seems to indicate you were mid-repair on something. How did you leave the game last time??

I believe there may be a launcher which provides a backup function but you'd have to find it on your own. I periodically backup a .zip of my game on Google Drive.

**Comment by oosyrag** [comment]
On the phone, I often "alt tab" out to do other things, and occasionally when I go back the game starts from the title screen. Usually I try to manually manually quick save before leaving, but don't anyways remember to. I figure even if I lose a little progress back to the last auto save it's not a big deal. Did I somehow manage to quit during an auto save that resulted from time passing during crafting?

**Comment by LeahLuong** [comment]
If the game is restarting when you go back to it, this is more of an Alt-F4 than an Alt-Tab. I've heard this sort of savescumming move can result in file corruption but I think that's rare. Still, I believe there are safeguards for when the game crashes during an autosave during a repair; it happened to me once while using a tailoring kit. The game threw some errors on reload but was able to proceed normally after.

This sort of seg fault was addressed in #54323 & is prob why you've only seen this in a stable release. You could try editing your save file to set your char action to null as detailed by ToxiClay in #48765. It looks like you've made a backup here so what've you got to lose??

**Comment by oosyrag** [comment]
I've migrated the save to experimental and it runs! With a bunch of other errors but oh well, at least I can continue. Thanks for the help.
