### ISSUE TITLE
Liquid Liquidation

### ISSUE THREAD

**Issue by LeahLuong** [CleverRaven/Cataclysm-DDA#55305]
### Is your feature request related to a problem? Please describe.

I dislike how spilled liquids remain indefinitely. Beverage containers crushed by my vehicle leave permanent marks on the landscape. Liquids dumped out over soil persist thru the seasons.

### Solution you would like.

I saw #35288 went stale & was closed but I have a simpler request than modeling evaporation: delete spilled liquids after a relatively short time. I think 1 day would be the upper limit but an hour or 2 would prob be better.

This would be a good 1st step towards modeling evaporation. Modifiers for deletion status could later be put in place. For example, different deletion times for different liquids, surfaces, ambient temperatures. Liquids under a roof or in shadow could have delayed deletion.

I know that rotten things have a deletion timer so it prob won't be that much different for spilled liquids.

### Describe alternatives you have considered.

Alternatively, there could be a secret follower mission unlocked by slaying 5 shoggoths while the moon is full. You'd have to be naked & wielding a spork while dealing the finishing blow each time. Upon unlock, you could request any follower -- @ any time! -- to tidy up the place. They would proceed to locate a mop -- which you conveniently put in a basecamp tool storage zone beforehand -- & then pathfind to each spilled liquid using an efficient traveling salesman algorithm. @ each spilled liquid location, they would activate their mop & -- in the span of a single second! -- clear any amount of spilled liquid(s) in that square. Upon dealing w/ every spilled liquid in sight, said follower would return the mop to the basecamp tool storage zone (!!!) w/ the words, "Thy will be done, Master!" This secret mission would also come packaged w/ a unique, unlockable achievement so you could brag to all of your friends about it.

Another thing I thought of is craftable cleaning robots w/ a specific emphasis on mutilating spilled liquids. 1st, you'd need to acquire a Talon UGV chassis & its intact components. But, instead of a gun, these bad dogs wield a mop! So, next, you'd need to find a mop. After that, it's a simple task of locating a nanofabricator, 1400 nanomaterial capsules, & the design blueprint for a Mop-bot 9000™. W/ Computer 8 & Electronics 10 skills, it should only take about 36 continuous hours @ the nanofabricator console to come away w/ a Mop-bot 9000™ of your very own &, you guessed it, a unique unlockable achievement to show off to all of your friends! This new follower would have only 1 function, detailed in the paragraph above. The bonus here is that there's no mussing w/ basecamp zones or dialogue menus; just say the word, boom!, bam!, "Thy will be done, Master!"

If the main feature request can't be implemented, please @ least consider putting Mop-bot 9000™'s in the game.

### Additional context

This feature may interfere w/ the most precious toilet water so special dispensation will prob need to be made for this exceptional liquid. We can't have all the toilet water getting deleted on day 1 of the Cataclysm; that would truly be cataclysmic!

**Comment by Drew4484** [comment]
This also would delete fuel from gas pumps, AFAIK.

**Comment by LeahLuong** [comment]
Oh, p'shaw! All gas in station pumps evaporating on day 1 would hardly be noticed. This is why I didn't even think it worth mentioning in my feature request.

**Comment by oosyrag** [comment]
This would potentially be devastating for my character's bathtub full of blood he uses for his immortality rituals.

Seriously though, I think bathtubs and toilets utilize similar code? As opposed to water heaters. I didn't realize gas pump gas was 'on the floor' either. Would changing them to be containers like water heaters and storage tanks work?

Is mopping blood something that people enjoy doing? Would this be better as a mod or baked in?

**Comment by chrispikula** [comment]
There's also winter, where you can, iirc, use a hammer to break up frozen fluids to pick them up off of floors.
