### ISSUE TITLE
DEBUG    : Error: Json error: data/json/mutations/mutation_eocs.json experimental build 2022-02-11-2342

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#55301]
### Describe the bug

```
 DEBUG    : Error: Json error: data/json/mutations/mutation_eocs.json:10:5: invalid sub effect syntax: { "u_set_queue_eoc": [ "EOC_BIOLUM3_cast" ], "time_in_future_min": 2, "time_in_future_max": 2 }
    

      { "arithmetic": [ { "u_val": "stamina" }, "-=", { "const": 700 } ] },
      { "u_set_queue_eoc": [ "EOC_BIOLUM3_cast" ], "time_in_future_min": 2, "time_in_future_max": 2 }
    ]
    ^
     ,
    "false_effect": [ { "u_message": "You don't have enough stamina to activate your Bioluminescent Flare.", "type": "bad" } ]
  },


 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 783
 VERSION  : e2d561b
```

### Steps to reproduce

Unzip experimental build 2022-02-11-2342. https://github.com/CleverRaven/Cataclysm-DDA/releases/download/cdda-experimental-2022-02-11-2342/cdda-linux-tiles-x64-2022-02-11-2342.tar.gz
Launch
New game
Play Now
DEBUG error

### Expected behavior

1/ no error
2/ update the build process to include a json syntax validation

### Versions and configuration

Ubuntu 22.04
English

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8052400/debug.log)

**Comment by ccaviness** [comment]
This was caused by #55044. I don't know enough about what this is supposed to look like to make a fix.

**Comment by ccaviness** [comment]
FYI: I edited my local `data/json/mutations/mutation_eocs.json` and removed the whole  `{ "u_set_queue_eoc": [ "EOC_BIOLUM3_cast" ], "time_in_future_min": 2, "time_in_future_max": 2 }` line, as well as the trailing comma at the end of the previous line, and things load normally.

**Comment by dseguin** [comment]
It's possible that the intention was to name the field `"queue_eocs"`:

```diff
diff --git a/data/json/mutations/mutation_eocs.json b/data/json/mutations/mutation_eocs.json
index 23bd5eb9e2..1c1469fc14 100644
--- a/data/json/mutations/mutation_eocs.json
+++ b/data/json/mutations/mutation_eocs.json
@@ -6,7 +6,7 @@
     "effect": [
       { "u_assign_activity": "ACT_GENERIC_EOC", "duration": "3 seconds" },
       { "arithmetic": [ { "u_val": "stamina" }, "-=", { "const": 700 } ] },
-      { "u_set_queue_eoc": [ "EOC_BIOLUM3_cast" ], "time_in_future_min": 2, "time_in_future_max": 2 }
+      { "queue_eocs": [ "EOC_BIOLUM3_cast" ], "time_in_future_min": 2, "time_in_future_max": 2 }
     ],
     "false_effect": [ { "u_message": "You don't have enough stamina to activate your Bioluminescent Flare.", "type": "bad" } ]
   },
```

That up there appears to load fine
