### ISSUE TITLE
Too many spiders, too maaaany spiders

### ISSUE THREAD

**Issue by Musteval** [CleverRaven/Cataclysm-DDA#55318]
### Describe the bug

I was sitting in my home base on experimental when I saw something tunnelling across the road. I went over to investigate, figuring it was a worm, but it turned out to be 20-30 giant trapdoor spiders, which appeared one by one and murdered me. I asked in Discord and it sounds like this isn't supposed to happen - feel free to close if this is actually a feature, but I didn't see anything in the code or commit history that looked like it was supposed to cause this.

I tried to make myself invincible so I could figure out what was going on, but I guess the "invincibility" mutation doesn't stop you from bleeding out, so I died before I was able to see if there was some kind of worm casting the "summon trapdoor spiders" spell or if it was just the spiders by themselves. I have "delete world on death" enabled so I don't have a savefile either, sorry!

### Steps to reproduce

Don't know how to repro.

### Expected behavior

30 spiders don't show up in my home base out of nowhere.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: e27abe9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Stats Through Kills [stats_through_kills]
]

**Comment by NetSysFire** [comment]
First of all, the thing you have encountered is a trapdoor spider den. Those things are very dangerous. You can reproduce it by debug spawning the trapdoor spider map extra (`mx_Trapdoor_spider_den`, debug menu -> map -> spawn map extra).

Make yourself invincible but not invisible and walk into the den.

**Comment by LeahLuong** [comment]
I've yet to encounter this critter but that sounds like strange behavior. Real trapdoor spiders do create a burrow but aren't really known for tunneling underground to catch their prey; they leap out of their burrow when they sense vibration or see them from the trapdoor.

It would also be strange if something was casting trapdoor spider summoning spells when you don't list a mod that has those AFAIK.

Nice "bug" report.

**Comment by Night-Pryanik** [comment]
@LeahLuong this map extra is from vanilla.

**Comment by NetSysFire** [comment]
One thing I can imagine without diving into the code is a similar issue the eyebots had when they could infinitely summoned police bots. Trapdoor spiders might be able to infinitely spawn more of them.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
