### ISSUE TITLE
Downspout Balance

### ISSUE THREAD

**Issue by oosyrag** [CleverRaven/Cataclysm-DDA#55327]
### Is your feature request related to a problem? Please describe.

Downspouts are very powerful tools to escape zombies. However, the ability for a normal person to use a downspout to climb onto a roof is questionable. The feasibility of success while encumbered, carrying a heavy load, or without free hands is even more farfetched.

### Solution you would like.

Without removing the ability to climb them completely, some possible thematic nerfs to downspouts could include requiring free hands to climb them or significantly higher failure rates that scale with weight. This would pressure players to drop their loot and weapons as a tradeoff for using this otherwise low risk method to attempt escape.

A clever survivor might utilize their throwing skill to bypass these new requirements, if they have the time, ability, and foresight to do so.

This change would have minimal impact to a start such as surrounded, where the character who relies on rooftops to escape are not carrying much to begin with and can still utilize that strategy.

Somewhat related: Add [<] climb as contextual shortcut for Android to climb when standing on a downspout.

### Additional context

Some previous discussion had likened the ability to climb downspouts as similar to climbing ropes, which I disagree with. While a downspout may reasonably support the weight of a survivor fine if anchored well, they are smooth, rigid, awkwardly sized, and usually attached to a wall or column without a gap, meaning no space to wrap arms or legs around. These all result in additional climbing difficulty, not to mention the possible eave, which would be extremely difficult to get around and over (very little leg support/leverage can be utilized to traverse an overhang).

**Comment by LeahLuong** [comment]
I always thought climbing downspouts seemed sketchy. IDK if they have sturdy, cast iron, rustproof designs in New England but most of the 1's I've seen are flimsy aluminum that are barely anchored to a wall using short screws. I imagine most people trying to climb 1 would simply tear it out of the wall before they got very far up, even completely unencumbered. Assuming the spout held & the climber had the strength to climb up, most buildings have an overhang of several feet that even professional rock climbers would have some difficulty navigating, not to mention how flimsy the gutters would be while trying to mantle.

This feat really should require decent Athletics & Strength as well as a heaping dose of luck to ensure the spout & gutter can withstand way more weight than they were designed for.

**Comment by Night-Pryanik** [comment]
Climbing downspouts is outright gamey and thus is liked by majority of players. Nerfing them to realistic levels means making them almost unusable and will lead to waves of hate.

**Comment by oosyrag** [comment]
There's room between get out of zombie free and unusable, as well as immersion enhancements such as attempting to toss your stuff on the roof, or making a plan to get your stuff back later when better prepared. 

The difference between "normal people can't climb a downspout" and "normal people can't climb a downspout without their hands free and carrying 40 pounds on their back while wearing halfplate" is fairly significant, and I'm glad to hear it already is accounted for. 

Specifically I'd like to see the penalties kicking in earlier and harder, while keeping the current success rate similar or only slightly less for a fresh unencumbered average survivor. Even if the failure rate for that goes up to 15-20%, it's not an instant death sentence, as you'll generally be able to try again, and multiple failures in a row would be unlikely.  Tweaking the numbers themselves can be pretty subjective and biased towards engaging gameplay.

As far as realism goes, there are liberties that's can be taken with interpreting downspouts, such as the lack of eaves on flat roofed buildings (although those generally wouldn't have gutters either), and the sturdiness of the material and construction.

**Comment by morthein** [comment]
" IDK if they have sturdy, cast iron, rustproof designs in New England but most of the 1's I've seen are flimsy aluminum that are barely anchored to a wall using short screws"

This.  
Climbing up a downspout where I live is a never-gonna-happen even for a naked 80lb kid, let alone anyone with more weight or carrying things.  Perhaps in NE they use cement anchors instead of 0.5" screws for those spouts, but i've found this to be a laughable unrealistic feature that is a nah-nah-you-cant-get-me and  get-out-of-zombie-hell free card on almost EVERY building.  We don't have to take away the feature, but it needs a going over for sure to underpower it a lot.

**Comment by oosyrag** [comment]
Additional context: I'm wearing a 40 lb backpack, holding a shotgun, wearing rollerblades, riot gear, and have a spear strapped to my back. My weight ratio is 2/3, and I'm slightly more physically capable than a normal person with 9 str and 10 dex. My final chance to slip is 10%.

I don't want to nerf downspouts to oblivion, but there is some magic involved here that I can do this without hands or feet.
![Screenshot_20220213-123748_6fe8938556442e3d4f710ab4f9a16601__01](https://user-images.githubusercontent.com/26992604/153774709-3b21b3ad-91ca-4972-8353-7b7b87581587.jpg)
![Screenshot_20220213-123337_6fe8938556442e3d4f710ab4f9a16601__01](https://user-images.githubusercontent.com/26992604/153774718-79410ee9-a6d4-4487-8579-234b13fef502.jpg)

**Comment by morthein** [comment]
Perhaps we could change it to reflect more things (climbing in general also) it could take into account other things like the shoes and gloves (if any) we're wearing, our current physical weight (not including encumbrance) , our athletic skill (this will give athletics another reason other than swimming). Failing a climb should damage/break the spout or thing we're climbing on if applicable also.

**Comment by robotic-gamer** [comment]
perhaps instead of a gamble, you either can or can't climb it like jumping a 1 gap. alternatively prompt a warning that tells you the odds like installing cbms that way the risks are transparently given to the player.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
