### ISSUE TITLE
When entering Trans-Coast Logistics, game breaks

### ISSUE THREAD

**Issue by cddagamelaggudoutside** [CleverRaven/Cataclysm-DDA#55322]
### Describe the bug

When I entered a Trans-Coast Logistics place my game started having massive input delay. I continued through and saw all the zombies stood still and all the enemies swapped their textures rapidly. attacking them did nothing but I was able to kill them, then when I saw a turret, it shot me, so I went around a corner, when I re peeked it, it was gone

### Steps to reproduce

1. Enter Trans-Coast Logistics

### Expected behavior

I expect the game to not lag, and all enemies to attack me

### Screenshots

![qwgadgasd](https://user-images.githubusercontent.com/99561798/153728540-5dd1fb56-9db6-45e8-852f-c4fb5cc990b0.JPG)
Zombies not attacking me and standing still

### Versions and configuration

-Windows 10
-Mods are: DDA, Disable NPC Needs, No Fungal Growth, Bionic Professions, Stats through Skills, Stats through Kills
-Game version e27abe9
-English
-Graphics are UltiCa for tiles and map

### Additional context

My game never crashed, and when I left the are the game turned normal again

**Comment by robotic-gamer** [comment]
most likely related to #55177

**Comment by Waladil** [comment]
I've been having a bunch of problems with TCL. I've had massive input lag but only on some floors at some times, other times its fine, and often I'll get "telepathic" vision of hostiles through walls as I move, but they disappear as soon as I finish the step. Also, the turrets and a feral security guard have shot me through ballistic/laminated glass a few times.

Most recently, when trying to blow up one of the turrets with a grenade from around the corner, I threw two grenades to two different tiles and both apparently fell *through* the floor. The tile says it's concrete floor and I can see shell casings sitting on it, but my grenades didn't damage/destroy the turret and the log reported that I heard explosions from northwest and below, so I guess my grenades somehow phased through the floor and blew up something else beneath my feet.


It feels like the various walls aren't properly "connected" and there are gaps between them but I have no idea how a tile-based roguelike could have bad tile "connections." The input lag could come from the AI knowing where you are and trying to path to you but not having any valid paths

**Comment by tempestnano** [comment]
I just encountered this bug, and here is my capture of the enemies swapping textures. The textures are swapping every turn, and the zeds just stand there. With a little music, this would add a "Crypt of the NecroDancer" feel. If I leave TCL, the lag and behavior return to normal.
![TCl glitch](https://user-images.githubusercontent.com/7892308/172982848-13418bca-de29-43a0-b8d8-442a17ad4f5b.gif)

**Comment by I-am-Erk** [comment]
Seeking confirmation that this remains an issue as I believe there has been some work on this. Have already put out a request to get a perf check on some of the TCL drones and things

**Comment by LyleSY** [comment]
I'm not able to replicate this on Mac with newest experimental. Works great. 
<img width="1054" alt="Screen Shot 2022-11-23 at 9 13 41 PM" src="https://user-images.githubusercontent.com/26608431/203678989-c093bbec-bed8-409f-8d48-bd90a390e32e.png">

**Comment by I-am-Erk** [comment]
I believe this is resolved now. Let me know if not.
