### ISSUE TITLE
Excellent Survivor Hood

### ISSUE THREAD

**Issue by LeahLuong** [CleverRaven/Cataclysm-DDA#55331]
### Describe the bug

XL survivor hood has jank stats. Light survivor hood & XL light survivor hood have the same stats for encumbrance & protection values. Not only is XL survivor hood worse than its ordinary counterpart, it's worse than XL light survivor hood, having greater encumbrance & lower protection values **in each category**.

### Steps to reproduce

1. Unlock the kernel's secret recipe.
2. Press '&'.
3. ???
4. PROFIT!

### Expected behavior

I expected that survivorhood level would increase, because all other skills can increase in level.

### Versions and configuration

Android 0.F-3 Tiles English vanilla

**Comment by Gavin-319** [comment]
> I expected that survivor hood level would increase, because all other skills can increase in level.

Except Survivor Hoods are an item and not a skill. Why would it increase or have levels in the first place? Armor and items don't have quality in CDDA, XL stands for Extra Large not Excellent. They aren't supposed to be better than the normal ones, just for mutants the size of pickup trucks that can't wear the normal ones.

Though the survivor hood having lower protection than a light hood may be a problem.

**Comment by a-chancey** [comment]
They do have a point, though. The XL survivor hood _is_ objectively worse than the regular version 

Regular is 8b\10c\14ba

XL is 6b\7.5c\10.5ba

The regular and xl light survivor hoods are both 6\8\12

The stats on the XL Survivor Hood are wrong.

**Comment by LeahLuong** [comment]
@Gavin-319 Survivorhood ≠ survivor hood. Once survivorhood level increases, thriving & transcendence is obtained. See:

https://www.google.com/amp/s/www.goodtherapy.org/blog/stages-of-trauma-recovery-what-it-means-to-be-a-survivor-0803155/amp/

Also, you may want to take a look @ #54047 for a better understanding of what "XL" means in the context of this game we play.

**Comment by Zireael07** [comment]
@LeahLuong: Can you please not make jokes, especially jokes that rely on English language mastery? Many of the players are not native speakers of English...

**Comment by Gavin-319** [comment]
@Zireael07 Funnily enough, I am an English native and even I didn't get it, partially because this is a bug report and not a reddit thread and also because it just doesn't make sense. I actually thought it was serious and they had no idea what the hell they were talking about, or at least it sounded that way.
