### ISSUE TITLE
Key press in Pocket auto pickup setting bugged on multi-pocket item

### ISSUE THREAD

**Issue by HKMist** [CleverRaven/Cataclysm-DDA#55344]
### Describe the bug

Happen after update from build 2022-02-09-1728 to 2022-02-13-0707

When in pocket auto pickup setting of multi-pocket item, some of the key (c,b,w) cause the game to leave the setting menu rather than do what they suppose to do. i key work normally.
Item with only one pocket seem not affect by this bug.

### Steps to reproduce

1.Get a multi-pocket item
2.open pocket auto pickup setting of that item
3.Press either c, b or w key

### Expected behavior

Can set white/black list category for said item

### Versions and configuration

Cataclysm-DDA experimental build 2022-02-13-0707

**Comment by CalKerethi** [comment]
Can confirm. Those keys are removed as part of my pull request #55323 (because I needed it fixed for my testing), so if that ends up merged then it will resolve this too.

**Comment by catdach** [comment]
Something to note, in my testing this also happens for the (d) key, and for some reason the (a) key. 

The (a) seems particularly odd  as it doesn't have any function in the menu at all as far as I know.

Also the upper case inputs for these letters (C, B, W, D, A) (both via caps-lock and/or shift) results in nothing happening. Which is quite unsurprising TBH, but _could_ be helpful I guess.
