### ISSUE TITLE
Missing barter values on multiple Aftershock items

### ISSUE THREAD

**Issue by DoctorGoat** [CleverRaven/Cataclysm-DDA#55340]
### Describe the bug

I cleared out the Magiclysm forge yesterday with a single Aftershock item worth over a million dollars that didn't have a barter value.  A few I just found with a quick scan:

    "id": "afs_sentinel_cloak",
    "id": "q_solarpack",

You can likely write a regex to check for id/price/no price_postapoc before hitting a } and find all of the cases.

### Steps to reproduce

1. Have Aftershock.
2. Dig around in ruins. If you wan a fast, easy way, get the Magiclysm Revamp and Additions mod and pop a level 25 Sonic Demolition any time the ground around you isn't just items.
3. Profit! (literally!)

### Expected behavior

These things should be worth a lot but not literally the entire value of four or five forge of wonders .

### Screenshots

![image](https://user-images.githubusercontent.com/11859483/153760620-df268c6f-9ed2-4a95-9314-a7baf44e8a19.png)

### Versions and configuration

Versions and configuration

    OS: Windows
        OS Version: 10.0 2009
    Game Version: https://github.com/CleverRaven/Cataclysm-DDA/commit/44b27ad5d59807c7e6b0246a9cf3e0c5db87027e [64-bit]
    Graphics Version: Tiles
    Game Language: System language []
    Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock]
    ]

**Comment by John-Candlebury** [comment]
Wait so are you somehow selling something worth 15K for about a hundred times the price?

**Comment by DoctorGoat** [comment]
Good lord, no, let me go and find the exact items that I was running into instead of trusting my quick text search.

Inactive tank drone, inactive tripod, and inactive chicken walker are ones I can definitely say are worth a million right now. I'm sorry, I wasn't checking the values correctly. All three of those date back to before the current Aftershock. 

There are items that seem to be missing a post-Cataclysm value, but they're generally lower like that. I'm sorry for the confusion.

**Comment by John-Candlebury** [comment]
No really a bug
