### ISSUE TITLE
Magiclysm NPC's stuck in a loop of "(x) completed his task" without taking any action in combat - confirmed broken by Experimental 2022-02-12-0725 up

### ISSUE THREAD

**Issue by zantimer** [CleverRaven/Cataclysm-DDA#55353]
### Describe the bug

As the title says. No matter the combination of set rules, they'll drop their weapon if they have one, presumably in an attempt to cast, but will just stand there idly without a move until they die

### Steps to reproduce

1. Start The Wizard's Vacation scenario
2. Recruit NPC on top of the tower
3. Take him outside to die

### Expected behavior

I expected them to cast (they were able to in an experimental few days ago, idk if in stable as well), or at least use their weapon/fists to fight

### Screenshots

![image](https://user-images.githubusercontent.com/99617630/153774674-2ea978d5-9667-4db1-b14a-b004c52704dd.png)

### Versions and configuration

- OS - Win 10 
- Game ver - Experimental 2022-02-13-0707
- Graphics - Tiles
- Language - English
- Mods 
Disable NPC Needs
No Fungal Growth
Bionic Professions
Magiclysm
Make bows great again
Mythical MMA
Mythical MMA mods extension
Graphical Overmap
Graphical Overmap Magiclysm
SpeedyDex
Stats through skills

### Additional context

I have tried disabling the use of ranged weapons, grenades, all possible engagement rules, creating new worlds and so

EDIT: non-magiclysm NPC's do not have any issues

**Comment by zantimer** [comment]
![image](https://user-images.githubusercontent.com/99617630/153778849-4015c870-f9fc-4b9f-a5fb-223d6e448903.png)
I just found out about the debug log, and this is what it shows

**Comment by LeahLuong** [comment]
It would seem the action you requested of Teodoro was too terrible to be named . . .

**Comment by zantimer** [comment]
I have since created a myriad of new worlds with same mods, and tried to enable Magiclysm only.
I have also updated to the latest experimental as of minutes ago, deleting all traces of CDDA on my computer beforehand, and the issue still persists. I might also add at this point, that removing all spells from the NPC made him engage enemies as normal.
Absolutely no combination of rules, nor clearing overrides haven't fixed it either, not on older, not on this experimental. I don't think you're going to need a save from me at this point, but I'll be happy to provide that or even the whole game folder if you still think it's my end only.
I will try and go back through experimental versions to see if I can find a build w/o the issue, but that might take some time.

**Comment by zantimer** [comment]
I've backtracked quite a few days on experimentals and the issue was no more, prompting me to believe there indeed is something that broke that functionality. I will keep going and update this post when I find which release messed with it

**Comment by zantimer** [comment]
Found the build breaking it. 

Builds from experimental 2022-02-11-2240 to 2022-02-12-0620 do not launch at all due to an syntax error with mutations, I doubt it has anything to do with the modlist

Build 2022-02-12-0725 is where the issue appears.
Builds before 2022-02-11-2240 work immaculately.

**Comment by LeahLuong** [comment]
Good work narrowing down the build & figuring out that the problem seems to be w/ spells. My guess is that some interaction betw/ EOC's, NPC's, & spells was overlooked in either #55302 or #55044. kevin has asked me not to @ others to help w/ troubleshooting so I guess we just have to cross our fingers that some1 in the know happens upon this thread.

**Comment by MNG-cataclysm** [comment]
I tested this on version 4f45027 [64 bit], and this error did not appear. The magus spellcast as they were supposed to.

**Comment by ehughsbaird** [comment]
Cannot reproduce on 74abea8db3dd071c52dbf04b9baf71a28301f902. The NPC successfully killed three zombies with magic.

**Comment by I-am-Erk** [comment]
Appears resolved. Please contact a cleverraven member to reopen this if my info is incorrect.
