### ISSUE TITLE
Gun mods display weapon ids in "Used on" block instead of weapon names once again

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#55369]
### Describe the bug

Basically, what's on the title.

#35251 and later #35280 fixed this issue two years ago, but it seems that #40637 broken something.

### Steps to reproduce

Obtain any gun mod with a specific set of weapons this mod can be used on, like `drop-in auto sear`. Open item info menu, check `Used on:` block.

### Expected behavior

Game displays weapon names instead of weapon ids.

### Screenshots

![изображение](https://user-images.githubusercontent.com/11132525/153845868-3ec16c74-3662-420e-85fb-2e5c37d9d32a.png)

### Versions and configuration

0.F-6088.

**Comment by catdach** [comment]
looks like #40637 replaced the following:
```
        {
            std::string id_string = item_controller->has_template( used_on.name() ) ? nname( used_on.name(),
                                    1 ) : used_on.name();
            return string_format( "<info>%s</info>", id_string );
        }
```
in favor of
```
        {
            return string_format( "<info>%s</info>", used_on.name());
        }
```
I don't know what any of that code does, but I suspect that's what the problem is.

If you want to look at the change in the #40637 PR "Files changed" it's after line "2341    2359" in item.cpp
