### ISSUE TITLE
Simplify charcoal kiln usage

### ISSUE THREAD

**Issue by martosss** [CleverRaven/Cataclysm-DDA#55373]
### Is your feature request related to a problem? Please describe.

The charcoal kiln usage is very cluttered with interface. Supposing you have a charcoal kiln, to use it you need to:
1) craft filled charcoal kiln
2) activate to fire up
Then wait, then
3) activate again
4) disassemble

Those are 4 steps that all require going in some menu and digging through all the items until you find the charcoal kiln, which is very annoying.

This is even worse when you want to use more than 1 kiln repeatedly:
you need to repeat steps 3),4),1),2) multiple times - once for each kiln.

### Solution you would like.

2-fold solution:
- Combine steps 1) and 2), into a single **step A) - activate a kiln to instantly fill it with charcoal and start it**(select items that you'd want to use);
- Combine steps 3) and 4) into a single **step B) - activate a finished kiln to disassemble it and take out the charcoal**.

### Describe alternatives you have considered.

You could even think about a single step - activate a kiln - fills it up with charcoal and starts it ... then after some time the kiln automatically finishes and drops charcoal on the floor.
This would cut the actions needed to just 1, but it's probably a bit unrealistic, because you should be required to inspect it after it's finished and spend time to finish the process.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
