### ISSUE TITLE
Taekwondo - gear damaged in offense should be shoes/leg not gloves

### ISSUE THREAD

**Issue by PlutusPleion** [CleverRaven/Cataclysm-DDA#55375]
### Describe the bug

In Taekwondo offense is generally using kicks. The game currently will damage your **gloves** by "force of blows" rather than your shoes or leg.

The kicks are clearly reflected in the flavor text:

"You spin and **back-kick** %s, right in the center of gravity"
"You turn slightly and **side-kick** %s", "<npcname> turns slightly and side-kicks %s"
"You crouch low and **sweep-kick** %s", "<npcname> crouches low and sweep-kicks %s"
"You **roundhouse kick** %s", "<npcname> roundhouse kicks %s"
 "You fake a **kick** at %s", "<npcname> fakes a kick at %s"

![](https://upload.wikimedia.org/wikipedia/commons/5/5d/Milad_Kharchegani_at_the_2016_Summer_Olympics.jpg)

### Steps to reproduce

1. Use Taekwondo fighting style
2. Equip glove, legs and shoes
3. Attack zombies enough until you receive "Your %s is damaged by the force of the blow!"
4. See that your gloves are the ones being damaged

### Expected behavior

Leg/ shoe should be the one that's damaged by your offensive attacks while using Taekwondo style, not your gloves.

### Versions and configuration

Any

### Additional context

inspired by:
- https://www.reddit.com/r/cataclysmdda/comments/sr3g80/my_kick_was_so_powerful_my_hands_were_hit_by_it/
- current favorite fighting style is taekwondo in game

**Comment by Zireael07** [comment]
I believe it's a duplicate of an existing issue, but I can't find it atm.

**Comment by PlutusPleion** [comment]
> I believe it's a duplicate of an existing issue, but I can't find it atm.

You are correct, found it #52001

I will close issue
