### ISSUE TITLE
Hair style is not vidible in the @ menu

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#55379]
### Describe the bug

I got a haircut from Vanessa at the refugee center. I can confirm that I did get the right trait, but there was no indication that anything changed in the UI. At thirst I even thought that the dialogue option is broken.

### Steps to reproduce

1. Spawn with a haircut or get one from Vanessa
2. Notice that the information about your haircut is completely hidden

### Expected behavior

I expected to see my haircut in the trait list on the @ screen

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 001d98b [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Graphical Overmap [Graphical_Overmap]
]

**Comment by CalKerethi** [comment]
That used to show, so I think it was purposefully hidden to keep the list (slightly) more compact. You can still see those cosmetic traits in the Mutations screen.

**Comment by Gavin-319** [comment]
The mutation list in the @ menu is heavily shortened iirc, anything not functional (at least in a noticable way) is cut out to make the list shorter. Cosmetic traits appear in the passive tab of the Mutations screen though.

**Comment by hexagonrecursion** [comment]
The info used to be there so I got confused.

> You can still see those cosmetic traits in the Mutations screen.

UX issue: how is the player supposed to figure this out?

**Comment by LeahLuong** [comment]
I believe tileset authors have the option of giving the char sprite different looks based on bionics or mutations but many tilesets are not so complete. Of course, those playing ASCII are reliant on finding the mutations screen for this sort of info. It would be silly for a barber to tell you to press '[' to admire your new do & the tutorial would be overwhelming if it went into this kind of detail. It's expected that some things will be left to the imagination in a game that ships ASCII as default.

@hexagonrecursion How would you like this issue resolved??

**Comment by hexagonrecursion** [comment]
> How would you like this issue resolved??

I am not sure.

**Comment by LeahLuong** [comment]
Hey, no reason to close the issue. I wasn't challenging the legitimacy of the thread, just curious. It seems to be the case this was once a part of the @ screen.

I can understand moving this out of the "TRAITS" section seeing as how it doesn't have a functional purpose. But neither blood type nor age in the "STATS" section have functional impacts. @ least skin color is affected by certain mutations & IDK if the acid blood mutation changes blood type. Perhaps hairstyle & skin color deserve places in the "STATS" section alongside blood type & age.
