### ISSUE TITLE
NPCs drop all installed bionics when their bodies rise as zombies

### ISSUE THREAD

**Issue by ElfLeaderMike** [CleverRaven/Cataclysm-DDA#55389]
### Describe the bug

When a dead NPC rises from the dead into a zombie form, all of their bionics drop on the ground without dissection.

### Steps to reproduce

1. Spawn NPC
2. Install any bionics into them
3. Kill them and wait a day for them to rise
4. Bionics will be on the tile where the body was "risen"

### Expected behavior

I expect the bionics to stay in the body or only get them via dissection of the corpse/zombie.

### Screenshots

![image](https://user-images.githubusercontent.com/22645231/153962267-58267927-5589-4fe4-b39d-39cb00a28c43.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: c7ffe3e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock]
]

### Additional context

PrepNet orchards from Aftershock revealed this one to me, as NPCs who spawn with many bionics. Visiting a previous location where I killed the NPC and didn't pulp their body, his entire loadout dropped without any dissection required. Not sure how many NPCs spawn with bionics preinstalled but it sure doesn't seem intended.

**Comment by LeahLuong** [comment]
It seems the game remembers which bionics they had while alive so, hopefully, this isn't too hard to fix. Weird they even have that programming; I'd have thought the bionics would disappear & you'd be reliant on good harvest table RNG.
