### ISSUE TITLE
data/fontdata.json and data/mods/replacements.json complicate the use of jq

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#55398]
### Is your feature request related to a problem? Please describe.

Most json files in C:DDA contain an array of one or more objects, but there are two special files: data/fontdata.json and data/mods/replacements.json

https://github.com/CleverRaven/Cataclysm-DDA/blob/c7ffe3e41db43765dac22e2868281f7adb801436/data/fontdata.json#L1-L16
https://github.com/CleverRaven/Cataclysm-DDA/blob/c7ffe3e41db43765dac22e2868281f7adb801436/data/mods/replacements.json#L1-L131

Because of their unconventional shape I have to explicitly blacklist them when I recursively scan the json files:
```sh
find data/ -not -path data/fontdata.json -not -path data/mods/replacements.json -name '*.json' -exec jq '.[].id' {} +
```
If I do not, I get errors from jq:
```sh
find data/ -name '*.json' -exec jq '.[].id' {} + >/dev/null 
jq: error (at data/mods/replacements.json:131): Cannot index array with string "id"
jq: error (at data/fontdata.json:16): Cannot index string with string "id"
```

### Solution you would like.

1. Move the file outside of ./data

### Describe alternatives you have considered.

2. Change the file extension to .txt
3. Wrap the file into an array

**Comment by Cenness** [comment]
Both files are valid json.
You could either redirect errors to dev null with 2>/dev/null, or use try catch instruction in jq:
```
# find data/ -name '*.json' -exec jq 'try .[].id catch ""' {} + >/dev/null | wc -l
# 0
```

**Comment by ZhilkinSerg** [comment]
Your `jq` command `.[].id` is to find objects with `id` node in these json, but these files do not contain any game entities definitions, so they don't have this node.

Just add these files to blacklist and that's it.
