### ISSUE TITLE
Magiclysm's Soulfire attunement enchantment indiscriminately targets neutral monsters and NPC

### ISSUE THREAD

**Issue by b3brodie** [CleverRaven/Cataclysm-DDA#55397]
### Describe the bug

The soul_pressure enchantment from Magiclysm's Soulfire attunement currently damages every nearby monster and NPC without discrimination for hostility.  This makes it imposible to interact with neutral NPC's and also prevents any potential neutral animal interaction as well.  I find it unlikely that this is the intended effect, but if it is more warning would be appreciated.

### Steps to reproduce

1) Acquire Soulfire attunement
2) Stand near neutral mob or NPC
3) Watch them burn to death

### Expected behavior

Neutral Mobs and NPC's do not burn to death.

### Versions and configuration

OS: Windows 10
Game version: d08dddd
Mods Loaded: 
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]

**Comment by LeahLuong** [comment]
If you give a man a fire, he's warm for a night. If you set a man on fire, he's warm for the rest of his life. If you give an NPC a man whose soul is on fire, how can you expect the situation not to get heated??

**Comment by GuardianDll** [comment]
Think the reason is because `"valid_targets": [ "hostile" ],` describe neutral creatures as enemies.

**Comment by Mer1ck** [comment]
Would it be possible to add a toggle in the mutations menu? It seems like it would be a decent enough fix as opposed to redefining "hostile"

**Comment by MNG-cataclysm** [comment]
> Would it be possible to add a toggle in the mutations menu? It seems like it would be a decent enough fix as opposed to redefining "hostile"

I've tried that as a fix, it didn't work.  I've been thinking about converting the enchantment into a spell, allowing the player to toggle it at will.
