### ISSUE TITLE
Don't spawn giant ladybugs or mantises day one

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#55409]
### Is your feature request related to a problem? Please describe.

These two bugs are both similar in that they are incredibly deadly to a new character, faster than the character, aggressive on sight, and totally abnormal to appear this early into the cataclysm given their degree of mutation.
In particular the mantis is totally misrepresented by the game as a "mildly dangerous" 9 difficulty enemy, but it has 8 melee skill, does 18 cut damage, is faster than you, has grapples, leaps, and enough armor to shrug off most of what an early survivor can throw at them. I've, no joke, been killed by one from full HP in the time it took me to draw my rifle from a golf bag the moment I saw one around the corner. The ladybug is at least shown in a big red name but the mantis feels like some sort of cruel joke especially given its evolutions become even more lethal.
Wasps are also pretty bad and can be lethal, plus they can spawn virtually anywhere due to their alternate nest type, but at least they *usually* are engaged with zombies giving you time to leave the area, or spawn in clearly visible nests out in the open that you can avoid.
Giant dragonflies are also awful but they can be avoided by never going to a swamp, but ladybugs and mantises appear everywhere.
### Solution you would like.

Don't spawn these enemies so early into the cataclysm. 

### Describe alternatives you have considered.

- Introduce a weaker ladybug before the gigantic mutant appears.
- Tone down the mantis line in general, they're all mental (2400 hp great mantis). 
- The praying mantis is also seemingly bugged. It does 18 cut damage when its evolution, the giant praying mantis, only does 10 cut damage. 
- Lower their speed. Giant insects are usually slower than their smaller counterparts which reflects real life, bigger creatures have to move a lot more muscles and are much slower relative to their size, or even relative to smaller animals. Lethal enemies that spawn early shouldn't also be faster, it just makes them a RNG death if you stumble into one without having a car nearby.

ALSO: per the design doc, mantises should have lower melee skill - "Nominal skill: 4 (average critter; most zeds & giant insects)" whereas 8 is "Very high skill: 8 (dangerous opponent; dark wyrm, vinebeast)"

### Additional context

Ladybugs and wasps, being flying, have the extremely annoying ability to sneak up on the player by abusing z-levels. There is also a bug (heh) where they can hit you, but you cannot hit them back due to a XY mismatch, you have to move underneath their square to be able to attack them even though they can hit you from their location. This would ideally also be something to have fixed as it only exacerbates these enemies being problematic.

**Comment by Paprika-H** [comment]
Mantis have a vision range of 8, and ladybugs have a vision range of 20. It's the same thing as a wasp, just avoid it until you can fight it. If you get absolutely floored by a giant ladybug, don't approach it next run. They're also both pretty rare, and quite easy to avoid.

**Comment by anoobindisguise** [comment]
> Mantis have a vision range of 8, and ladybugs have a vision range of 20. It's the same thing as a wasp, just avoid it until you can fight it. If you get absolutely floored by a giant ladybug, don't approach it next run. They're also both pretty rare, and quite easy to avoid.

Look, I know "get good" is a tried and true argument, but it doesn't change the fact that the mantis does more damage than its evolution, breaks design guidelines by having twice as much melee skill as it is "supposed" to have, and that the game blatantly lies about how dangerous it is. The only way to discover their actual danger level is to be murdered by one after mistakenly assuming it was about as dangerous as a tough zombie (7 danger, also mildly dangerous)

**Comment by Paprika-H** [comment]
> > Mantis have a vision range of 8, and ladybugs have a vision range of 20. It's the same thing as a wasp, just avoid it until you can fight it. If you get absolutely floored by a giant ladybug, don't approach it next run. They're also both pretty rare, and quite easy to avoid.
> 
> Look, I know "get good" is a tried and true argument, but it doesn't change the fact that the mantis does more damage than its evolution, breaks design guidelines by having twice as much melee skill as it is "supposed" to have, and that the game blatantly lies about how dangerous it is. The only way to discover their actual danger level is to be murdered by one after mistakenly assuming it was about as dangerous as a tough zombie (7 danger, also mildly dangerous)

Changing those values would do a lot more than to just stop them from spawning for the first few days

**Comment by Venera3** [comment]
Yeah, ladybugs are a bit too angry for my tastes. In general, bug progression could stand to slow down a bit apart from some specific locations to give a sense of post-cataclysm progression. I have a few balance changes lined up for the freezes of this cycle, this should fit in nicely with that.

(I'd of course like it more if we had smaller variants and a more interesting progression for them, but that's more work.)

**Comment by a-chancey** [comment]
I will say: lady bugs are brutal on a golf course start. I wind up with one right out back about 50% of the time I've done one, locking me out of the upstairs food and the carts out back due to it being ready to murder me.

**Comment by MylieDaniels** [comment]
@Venera3 About a week before this issue I had begun a comprehensive rework of the arthropods added by the Bug's Life mod merge, which included the ladybugs and mantises.  Could we speak on Discord about how to best collaborate or decide which of us should tackle this issue?

**Comment by I-am-Erk** [comment]
I think a reasonable solution here is to spawn smaller versions of the ladybugs and mantids, as well as the wasps, which are more of a nuisance than a threat, and then have them get bigger with time. However I agree that the deadly insects should be dialed back at first. Having them grow bigger is a nice way to again improve the feel of "I gotta get better before the world gets better than me" that we are aiming for.

**Comment by LyleSY** [comment]
I believe this is now complete. Is there anything else needed I'm missing?

**Comment by anoobindisguise** [comment]
> I believe this is now complete. Is there anything else needed I'm missing?

seems like it to me! I appreciate everyone's work on this, now I can go be salty about something else.
