### ISSUE TITLE
Reducing the concentration of hydrogen peroxide should be easier

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#55410]
### Describe the bug

The current recipe that turns concentrated hydrogen peroxide into regular hydrogen peroxide requires:
1. Boiling 2 (Why?)
2. Chemical making 1 (possibly reasonable)
3. A source of heat (tool: "surface_heat") (Why?)
4. Applied science 3 (Why?)
5. Health care 3 (Why?)

### Steps to reproduce

https://github.com/CleverRaven/Cataclysm-DDA/blob/9526b31aabeb7a058f34dec00cd424fbb87abc9e/data/json/recipes/recipe_medsandchemicals.json#L725-L741

### Expected behavior

As far as I can tell to _reduce_ the concentration of hydrogen peroxide I just need to mix it with water in the right proportions. See https://healthfully.com/mix-hydrogen-peroxide-water-7459720.html

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 735e42d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Graphical Overmap [Graphical_Overmap],
    allow-me-to-switch-control-to-followers [allow-me-to-switch-control-to-followers]
]

**Comment by chrispikula** [comment]
Our concentrated H2O2 is way more than 35%.  More like 90+%.  Pretty sure that adding water to the concentrated solution is exothermic, that is, it's likely going to boil.
![image](https://user-images.githubusercontent.com/22281606/154125024-430d63fe-d13d-493e-839c-b6c82714b5b5.png)

IIRC Negative means that the enthalpy of the solution is going down, ie, exothermic, ie, heat's coming out, but I'd like someone to double check me on this.  I always get negatives and positives mixed up w.r.t. thermodynamics, as half the time they talk about the system as just the chemical, or as the solution, _and_ I hate it.

The health care bit, yeah, I don't get.  Maybe as a Applied Science 3 OR Health Care 3, but not both.

**Comment by robotic-gamer** [comment]
the only complicated bit is that normal water may contain impurities that catalyze the decay of hydrogen peroxide. the easiest way to fix that is to require distilled water which water, a tool with distilling 1 and a heat source could be used as an analog.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
