### ISSUE TITLE
Android Portable SD

### ISSUE THREAD

**Issue by LeahLuong** [CleverRaven/Cataclysm-DDA#55418]
### Describe the bug

This isn't really a bug but it's definitely not a feature request & I couldn't find it in an FAQ or discussion. Don't know where better to put this.

I'm trying to move my game into the portable storage on my phone & play it from there so it's not taking up internal space. I was successfully able to do this for another game (Star Realms) by simply dragging all the files over. The executable seems to have no issue finding & running the game; ejecting the SD card & trying to run it shows the opening screen & then it hangs on a black screen. W/ CDDA, it simply shows a black screen instead of trying to boot up while the SD card is mounted.

I think it's merely an issue of finding the .exe or .bat for CDDA & changing a pointer but I've been unable to locate it. For that matter, I don't know where to find the Star Realms .exe; both of them have an icon on my home screen but I can only choose to let them live there or put them back in the apps drawer.

Please let me know which file to edit & what needs to be changed to get this working.

### Steps to reproduce

N/A

### Expected behavior

N/A

### Versions and configuration

Android 0.F-3 Tiles English vanilla

**Comment by LeahLuong** [comment]
Since opening this thread, I discovered Star Realms had permission to use storage while CDDA didn't. Enabling it for CDDA didn't fix my issue.

I ejected the SD, cleared the data for CDDA which wiped out all game folders but left the desktop icon, & mounted the SD once more. Tapping the icon caused the game to somehow reinstall itself despite not having the download @ cataclysmdda.org for 0.F-3 in my "Downloads" folder available. I have a duplicate installation on my SD containing my save (hence why I ejected before clearing data) but the newly installed version of CDDA was unable to see it or my options.json or panel_options.json.

I'm still fairly sure this is an issue w/ the executable missing the proper pointer but I don't know how to change it.

**Comment by Zireael07** [comment]
@LeahLuong: What is your Android version? As someone whose internal storage was usually low because the phones were old, I discovered that the ease of using the SD for apps depends on Android version. Some versions only allow the save data to be stored, some allow everything... IIRC Android 7-8 was the best, then 9-10-11 started making transferring apps to SD difficult/impossible  without root again :(

**Comment by LeahLuong** [comment]
@Zireael07 It looks like I'm running Android 6.0.1. I believe this was introduced shortly after the discovery of fire but prior to invention of the wheel. Sliced bread had many more years before coming into fashion.
