### ISSUE TITLE
Respect LC_* variables on Linux

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#55425]
### Is your feature request related to a problem? Please describe.

I live in Europe and many other players are also not based in the US. When first launching the game, it defaults to using imperial units which I can not read as intuitively as the metric ones.

### Solution you would like.

On the very first start, check for those variables and use them as accordingly. `LC_MEASUREMENT` would be appropriate here.

I tagged this with OS: Linux but I am pretty sure there is also be a Windows equivalent and the Linux solution might also work for macOS.

### Describe alternatives you have considered.

A potentially better alternative would be a "Use system default" value for this, just as with the language.

**Comment by NetSysFire** [comment]
What do I need to do to repel stalebot from such issues? What label is needed here?

**Comment by BrettDong** [comment]
This feature is implemented for glibc Linux distributions in #58789. Can this issue be marked solved?

**Comment by NetSysFire** [comment]
Looks like it.
