### ISSUE TITLE
calcium carbonate

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#55420]
### Is your feature request related to a problem? Please describe.

limestone (a type of rock) should be a distinct item from calcium carbonate (a chemical compound) so that when/if other sources are added (like egg shells) it does not sound odd.

### Solution you would like.

calcium carbonate as a distinct item produced from limestone by grinding (similar to rock salt and salt)

### Describe alternatives you have considered.

just renaming limestone as calcium carbonate

### Additional context

this was prompted by comments in #55415

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
