### ISSUE TITLE
Water striders could use a nerf/rarer spawns to prevent fishes going extinct on the first day

### ISSUE THREAD

**Issue by zantimer** [CleverRaven/Cataclysm-DDA#55423]
### Is your feature request related to a problem? Please describe.

I have noticed that since their addition, kind of a water body where water striders spawn means that any kind of fishing will be a waste of time. 

### Solution you would like.

I do not really have a clue how CDDA handles it spawns, therefore I am unsure how the problem could be tackled.

However one solution that stands out to me would be making normal medium/small fish faster than everything else

### Describe alternatives you have considered.

- Water striders could be made slower in water
- they could be, if possible, vastly reduced in numbers, from their now usual groups of 6 to 12 to single units, or groups up to three

### Additional context

I feel that however petty it may seem, it is quite a big issue that imho kills off a previously viable water-based playstyle, that I think already comes with it's own many dangers and inconveniences as it is.

Also, this one I'm not sure about, the nalads seem to be still contributing to the anti-fish efforts of striders, not as zealously as before though

**Comment by Venera3** [comment]
They can't really catch fish - they have 50/55 speed and SWIMS, meaning they swim two tiles a turn and waddle along on land with 2turns/tile give or take. Contrast that to fish's 150 speed + SWIMS translating to 30 tiles of swimmable terrain per turn if they really want to leg it (and don't dive). Do you actually see fish corpses around, or is it a "where them fish at" problem?

**Comment by zantimer** [comment]
Now that's weird, I have assumed they're the problem cuz of being an "new addition" to me. 
I do indeed see corpses strewn about,  which was what prompted me to post, mainly of fish that comes up/jumps from the water, but not limited to either, especially visible if in proximity to nalad water terrorist areas.
I also understand that the only "truly sustainable" fish would be salmons due to laying roe, unless that changed

**Comment by CalKerethi** [comment]
I don't see a lot of random fish corpses in my game. A few sometimes, but maybe the the bigger issue is striders constantly chasing them out of the reality bubble. That would mess up fishing just as badly as killing them if it's the case.

**Comment by LeahLuong** [comment]
Maybe 1 solution would be to make it so water striders ignore fish & vice versa. Water striders IRL stand atop the water surface & can't effectively get below because of surface tension. For that matter, water striders IG are somewhat unrealistic because their size would preclude them from being able to stride on water; their larger size & mass would counteract the effect of surface tension causing them to sink.

**Comment by zantimer** [comment]
@CalKerethi that is much more of a possible source and outcome of the problem, now that I've visualised it. Especially since my primary "test areas" were lakes, that are very prone to having swamps on the banks, that'd serve as kill zones for the bolting fishes
I wonder if there is a way to rubber band a creature to it's spawn spot, if so, making fishes teleport back in the tile after trying to leave it/being gone for x amount of time could be a solution. It does not sound very resource friendly though, however I have absolutely no clue about the impact of such "features".

**Comment by Venera3** [comment]
For the record, you don't need to have monster fish around to be able to fish.

**Comment by zantimer** [comment]
I've since did my best to test it, and having spawned on a lake without water striders at all made fishing go back to normal, while I still have seen corpses. I'm pretty sure it means that CalKerethi was right about them being chased out of reality bubble.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
