### ISSUE TITLE
Make flags determine whether or not the NPC AI will consider items as able to be wielded/thrown

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#55430]
### Is your feature request related to a problem? Please describe.

A complaint I see a lot on Reddit is that NPCs will wield ridiculous items, like helmets, saw blades, and other things that aren't good for using as melee weapons. I've also experienced my cyborg companions throwing an infinite supply of monomolecular blades at zombies.

### Solution you would like.

I'd like for new flags, something like NPC_WIELD and NPC_THROW, to be introduced to items that control whether or not the AI for NPCs will even consider an item as able to be wielded or thrown. The NPCs' AI would check to see if these flags are present on an item before the NPC decides to wield it; if neither the NPC_WIELD nor NPC_THROW flag are present, then the AI will automatically skip over the item, and either keep checking until an item with the appropriate flag is found, or give up on wielding an item at all. Something similar should happen when an NPC wants to throw an item; if the item doesn't have the NPC_THROW flag, they'll skip over it until they find one that does, or else just give up on throwing. I also think that the NPC_THROW flag should include the functions of the NPC_WIELD flag by default, given that items seem to need to be wielded in order to be thrown anyway..

### Describe alternatives you have considered.

Making the flags prevent wielding/throwing, rather than enable. Given that this would involve applying flags to a far greater number of items, I don't think this is a good alternative.

**Comment by PatrikLundell** [comment]
I don't think preventing the wielding of items unsuitable for combat would be a good idea, as there are use cases for companions carrying things in their hands that they could not fit into their inventories for transportation purposes (I know companions tend to refuse to wield "inferior" items currently, but I don't think that's a strong argument for making it worse).

That said, I agree an increased degree of "common sense" in what and how companions use items for combat would be welcome.

**Comment by AmarinReyny** [comment]
> I don't think preventing the wielding of items unsuitable for combat would be a good idea, as there are use cases for companions carrying things in their hands that they could not fit into their inventories for transportation purposes (I know companions tend to refuse to wield "inferior" items currently, but I don't think that's a strong argument for making it worse).
> 
> That said, I agree an increased degree of "common sense" in what and how companions use items for combat would be welcome.

Given the AI's tendency to wildly throw things and switch which items (suitable for combat or otherwise) NPCs wield regardless, those items already aren't safe in NPC hands. Still, you have a point. Maybe these flags could be a part of a larger NPC AI overhaul, rather than a standalone solution?

**Comment by CalKerethi** [comment]
I think the NPCs already have enough information to resolve _some_ of our problems with them. If the suitability measure considered:

* Flags that already exist. Never use HURTS_WHEN_WIELDED for the sawblade, ban throwing BIONIC_WEAPON because that should be impossible, others?
* A vague estimate of the value a worn item is currently providing as armor. Nothing fancy, just enough to say that taking your helmet off to hit things with it is probably a bad idea, but unwearing your rifle with shoulder strap remains an excellent plan. Hitting things with a belt is probably okay, given that it's not that protective as clothing, as long as it's legitimately a better weapon than their fists.

Disclaimer, I haven't looked at the code, so I'm making some assumptions.

**Comment by AmarinReyny** [comment]
> * Flags that already exist. Never use HURT_WHEN_WIELDED for the sawblade, ban throwing BIONIC_WEAPON because that should be impossible, others?

That could work for the specific examples I've mentioned. Other examples I can think of are guns, since shooting with a gun is generally going to be more effective than throwing it. I briefly looked at the JSON files for some of the guns, though, and not all of them have flags that can be used for this purpose.

**Comment by CalKerethi** [comment]
> Other examples I can think of are guns, since shooting with a gun is generally going to be more effective than throwing it.

Oh boy, mine haven't done that to me yet. I imagine anything with available ammunition could be safely excluded from throwing. I won't argue against the idea of adding more flags where they're needed, of course, just exploring what we already have available. Oh, and I poked through a few items and found that NPC_THROWN already exists on certain items!

**Comment by AmarinReyny** [comment]
> > Other examples I can think of are guns, since shooting with a gun is generally going to be more effective than throwing it.
> 
> Oh boy, mine haven't done that to me yet. I imagine anything with available ammunition could be safely excluded from throwing. I won't argue against the idea of adding more flags where they're needed, of course, just exploring what we already have available. Oh, and I poked through a few items and found that NPC_THROWN already exists on certain items!

Huh... Interesting. I looked at its description on [this page](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON_FLAGS.md), and now I'm wondering exactly how it differs in intent/function from what I've described.

**Comment by morthein** [comment]
After firing up my test game and going through the motions, this function seems to stop them from using said guns now too.  I seem to remember this only stopping them from throwing the gun. Scratch what I said, I guess.  Although you can still use it and just manually tell them to fire again when needed (turned ranged use back on). That still works, but it's like doing long division every time. :-(

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
