### ISSUE TITLE
NPCs with 'Huge' attempt to use beds in vehicles

### ISSUE THREAD

**Issue by Arokha** [CleverRaven/Cataclysm-DDA#55446]
### Describe the bug

They repeatedly path to the bed, open the car door (if allowed to open doors), take one step towards the bed (usually onto a seat or something), and then repeat this forever trying to reach the bed. Often it harms performance because every turn they attempt to reach the bed, often closing/opening doors several times. Especially poor performance during time accelerated periods like crafting and sleep.

### Steps to reproduce

1. Have an NPC with the 'Huge' trait
2. Grab a vehicle with beds, like the Luxury RV for example
3. Have NPC follow you or guard nearby the RV
4. When NPC tries to sleep, they will harm performance with their pathing attempts

### Expected behavior

NPCs to seek out another bed that they can actually reach. I don't know what pathfinding this game uses but I assume there's a reachability validation on each tile as it builds the path, and vehicles with roofs should not be valid to NPCs with 'Huge'.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: openSUSE; Description: openSUSE Tumbleweed; Release: 20220207; Codename: n/a; 
- Game Version: 973d737 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

**Comment by LeahLuong** [comment]
Not only is follower pathfinding sketch, their ability to find a decent bed is questionable. See #54953.

@ least 2 different angles of attack for this problem.
