### ISSUE TITLE
Rubik gives away thread and cardboard boxes for free

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#55444]
### Describe the bug

The exodii trader - Rubik sells many items kinds of items. Surprisingly they are willing to part with a pile of cardboard boxes and bulk quantities of thread for a total of $0.

### Steps to reproduce

1. Load this save 
[free-loot.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8082933/free-loot.zip)
2. Trade with Rubik
3. Buy all the free stuff

### Expected behavior

Rubik should charge me for thread, cardboard boxes etc.

### Screenshots

![DeepinScreenshot_select-area_20220216223008](https://user-images.githubusercontent.com/52621858/154341276-24d9af82-126c-4196-98eb-fbb41bf2617d.png)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: cc10e0c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by LeahLuong** [comment]
Many merchants will occasionally offer "free" items. I like to think they're happy to be rid of those cluttering, low-value things.

**Comment by andrei8l** [comment]
This was just an integer truncation error and I'm pretty sure I've fixed it in #58141
![Screenshot from 2022-07-03 16-25-47](https://user-images.githubusercontent.com/68240139/177041853-0ac5aecc-481d-4119-8ea1-8df067824272.png)
