### ISSUE TITLE
Make it harder to accidentally attack an exodii

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#55442]
### Is your feature request related to a problem? Please describe.

It is too easy to accidentally attack an exodii. Unlike non-hostile NPCs, bumping into an exodii automatically attacks her or him. While exploring their main base I have accidentally attacked them one too many times and got murdered by a quadruped.

The base if packed full of them and they move - they might move into your path.

### Solution you would like.

The game should prompt me when I move into a non-hostile exodii similarly to how it prompts me when I walk into an NPC.

### Describe alternatives you have considered.

Walking with point-and-click is safe, but keyboard is not.

**Comment by LeahLuong** [comment]
Perhaps this functionality should be implemented for all neutral mobs. Accidentally walking into a cow or horse can be quite dangerous for starting chars.

**Comment by Gavin-319** [comment]
Seconding the all neutral mobs idea. Had to save-scum a few days ago when I fat fingered the wrong move button and punched one of Cody's turrets.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
