### ISSUE TITLE
My feet become wet when I walk on top of a scrap metal bridge

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#55440]
### Describe the bug

There are a number of places in the exodii main base where shallow water is covered by a scrap metal bridge. Surprisingly, my feet become wet when I walk *on top* of the bridge.

### Steps to reproduce

1. Find the exodii main base
2. Find a shallow water with a bridge over it
4. Open the v menu.
5. See that you are not wet
3. Walk on the bridge
4. Open the v menu.
5. See that you are wet

### Expected behavior

Walking on the bridge should protect my feet from becoming wet.

### Screenshots

![DeepinScreenshot_select-area_20220216211130](https://user-images.githubusercontent.com/52621858/154328911-dc8d79f3-e6d9-4045-baaa-6d9eb1f51418.png)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: cc10e0c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]

### Additional context

The easiest fix would probably be to change the bridge from furniture to terrain

**Comment by LeahLuong** [comment]
In addition to the above proposed solution, #40026 or #45835 may offer solutions.
