### ISSUE TITLE
Special overmap features (Ref Center, Exodii, etc) should spawn closer to start more consistently

### ISSUE THREAD

**Issue by drhead** [CleverRaven/Cataclysm-DDA#55453]
### Is your feature request related to a problem? Please describe.

I've been told that moving CBMs to Exodii is intended to improve access to make them accessible before they are obsolete. I don't think this is necessarily being accomplished due to the fact that it can't be guaranteed that a refugee center or Exodii base is particularly accessible -- my ongoing game, for example, had its ref center spawn an overmap and a half away.  Beyond that, the refugee center is important in a lot of other ways and is one of the things that makes the game world feel most alive, and it's not very enjoyable to find that your spawn is extremely far from it -- and if you persist, by the time you feel like making the journey, all of the rewards are probably just low-level garbage.

### Solution you would like.

If possible, I think map generation should be reworked to make sure that refugee centers spawn near evac shelters.  I think that ideally, I would want to see evac shelters clustered around a refugee center -- it would make a bit more logical sense anyways to have the evac shelters somewhat close.  One way of implementing this might be to make the refugee center always spawn at 0'0, 0'0.  This would also tie in well with previous ideas of making unique overmap sites actually unique.

This would also allow further organization of the map into "difficulty zones" of sorts if that's something that was desired (i.e. the area around the evac shelters and ref center are safer, but going further away makes more hazardous maps spawn).

### Describe alternatives you have considered.

Probably the easiest workaround is to just regenerate the world until the refugee center is reasonably close, but 

1. that doesn't let me know if other specials exist and I can't check that without spoiling the rest of the map, 
2. I can't check the refugee center like this without an evac shelter start and 
3. I probably shouldn't be getting map output that makes me want to reroll.

**Comment by Inglonias** [comment]
A workaround in the meantime is to use the "Safe Place" starting scenario to spawn at the refugee center from the get-go.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
