### ISSUE TITLE
Debug game report shows wrong OS version on Windows

### ISSUE THREAD

**Issue by xuvatilavv** [CleverRaven/Cataclysm-DDA#55454]
### Describe the bug

The game report claims I'm running Windows 10.0 version 2009 when I'm currently on Windows 10 version 21H2.

I've also noticed here on GitHub there are only 6 total issues reporting version 21H1, and none with version 21H2, which is rather suspicious. Seems like a lot of current issues may have the wrong version included.

Sorry if there's already an existing issue on this, it's a little hard to search for since the game report is present in every issue.

### Steps to reproduce

1. In CDDA, load any character in any world.
2. Generate a game report from the debug menu. (Main menu > Debug Menu > Info > Generate game report)
3. Paste the report somewhere for reference.
4. In Windows Settings, go to System > About.
5. Observe that the OS version from the game report is different from the version reported in Windows Settings.

### Expected behavior

The game report and the OS should show the same OS version.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 1ed949a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Generic Guns [generic_guns],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Crazy Cataclysm [crazy_cataclysm],
    Stats Through Kills [stats_through_kills]
]

### Additional context

System info as reported in Windows Settings:
Edition	Windows 10 Home
Version	21H2
Installed on	‎26 ‎Nov ‎2021
OS build	19044.1526
Experience	Windows Feature Experience Pack 120.2212.4170.0

**Comment by LeahLuong** [comment]
The attitude around this git is fairly laissez-faire; your implementation of this feature is likely to be the permanent 1, @ least until it breaks again. I'd recommend making it as robust as you can. I think you already understand version reporting is mainly there for troubleshooting. What's the worst that could happen??
