### ISSUE TITLE
An option to hide non-weapon/tools Melee damage

### ISSUE THREAD

**Issue by martosss** [CleverRaven/Cataclysm-DDA#55451]
### Is your feature request related to a problem? Please describe.

Melee damage for items that are not weapons or not tools makes very little sense. Most of the time it's just useless information that's distracting the player from what he wants to see - the relevant item info, e.g.
- Spoilage condition & nutrition for contents of a can/jar instead of melee damage, or 
- Simpler interface for everything else ... Do I need to see melee damage for an armor piece?

### Solution you would like.

A toggle in options that would:
- Hide melee damage for items that are not weapons and not tools. This can be applied in both item description and crafting recipes.
- Specifically for containers, show content info in case of foods - a can contains beans, I don't care about melee damage with that can, I want to see the beans' expiration date and nutrition!

Result:

1) De-clutter the interface - show relevant information for the item you're viewing.
2) Decrease scrolling

### Describe alternatives you have considered.

1) Exclude other items that can be used as weapons but don't fall in those 2 categories?
- Spare parts? However, there are many items without any damage or low damage in this category.

2) Exclude items with damage higher than a certain threshold - more than 5 or 10 bash/cut/pierce?

- stout branches, bricks, planks, lumps of steel, pipes, rebars are all good candidates with 10+ bash dmg and all spare parts, so either rule 1) or 2) might work.
 
I tend towards (2), because
A) Not all spare parts have "good enough" dmg to be worth displaying.
B) There might be items in other categories with high damage.

3) Any better ideas?

**Comment by NetSysFire** [comment]
#54721 already addressed some of this

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
