### ISSUE TITLE
Rework on "hand forged" medieval artifacts

### ISSUE THREAD

**Issue by GenericDwarf** [CleverRaven/Cataclysm-DDA#55456]
### Is your feature request related to a problem? Please describe.

Currently, you can use a very crude and primitive rock forge, an anvil made from casting scrap metal with a clay crucible, and scavanged/expedient made tools and dies to forge a medieval weapon/set of armor, and the resulting work would be no different from a genuine, state of the art piece made by a professional with a full blacksmith setup. While a skilled survivor would definetly be able to hand forge a sufficient weapon shaped like a medieval sword, it wouldn't be as sturdy and durable as a proper one, especially since their current recipe don't consider even basic smithing techniques such as tempering and annealing.

### Solution you would like.

My proposed solution is to add a new "variant" of ancient equipment on a similar way we have budget steel or aluminum replicas, which would be identical to "genuine" ones stat wise, but lacking the sturdy tag. With appliances on the horizon, to make a proper, sturdy weapon/armor you would need specialized equipment and ingredients (ideally ones you can't make from scavanged bits and pieces), while the current recipes would net you a crude version of the same weapon/armor that doesn't last as long.

### Describe alternatives you have considered.

A possible alternative is to swap the current recipes output to their "budget steel" variant while locking the genuine pieces behind proper equipment, but that would probably disincentivize doing those recipes at all.

**Comment by LeahLuong** [comment]
I believe #53500 will address this issue more comprehensively in the long-term.

**Comment by bananapheasant** [comment]
I agree very much that the ideal end would be Item qualities where materials used, player stats and proficiencies, and other factors can affect how well a weapon or item performs. Qualities for food, weapons, and gear. Would give great versatility and more strategy and reason for crafting well.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
