### ISSUE TITLE
add composite filters for the search on the crafting menu

### ISSUE THREAD

**Issue by jfferson** [CleverRaven/Cataclysm-DDA#55463]
### Is your feature request related to a problem? Please describe.

It is hard to get used to the long list of itens on the menu and associate it with your current possibilities. The current filters work to a certain degree, but it still takes a long time of the game. As it is it still leaves a lot of complexity on the combination of components, skill levels and attributes

### Solution you would like.

the search instead of using a single filter could use a mask that would allow multiple to be used such as _aspect_: , , , ;_aspect_:...

### Describe alternatives you have considered.

another possibility is to allow to search within an already presented retrieved list from the previous search

**Comment by mqrause** [comment]
You can already apply multiple filters by separating them with a comma.

**Comment by mqrause** [comment]
Since the filter is remembered, you can already do a narrowing search.

**Comment by chrispikula** [comment]
As an example for OR searches: let's say I want to compare jerrycans, and metal tanks, or plastic jugs and tin cans.  Both are liquid containers, but searching 'd:contain a liquid' will be awful, and need several subsequent sub-searches to refine.

I both love and hate d: searches.  Waiting 5 minutes to process a single search, only to realize you made a spelling error?  Or if you aren't exactly sure what you're searching for?

I'd totally love a sub-search when I do those.  I ran into this recently while doing some molle stuff, and it's significantly faster to search the json files outside the game than to ever use d:load bearing vests.  I don't think we should expect players to open up notepad++ and do a directory string search, yeah?

Strangely enough, I've also noticed longer search strings take longer to process than shorter strings, which is weird to me: shouldn't there be some sort of short-circuit evaluation exit?  If you can't find 'loaf be', why continue searching for the rest of 'loaf bearing vests'?  (Aka, that 5 minute misspelling I made above.)

Your note about favorites is important, but I also kind of wish we had a way to make temporary favorites: my current favorites list already has a few dozen items in it, and I can easily miss finding what I just added, especially if I currently don't have the ingredients!  :-p

**Comment by chrispikula** [comment]
> Try "q:boil" or "q:contain"? That even works outside recipes, but I thought the OP meant exactly the crafting menu.

Neither of those would have let me find out that the fridge is a valid pocket for storing liquid.  :-p  500L of it in case you were wondering.  But only 400Kg.

**Comment by jfferson** [comment]
thanks for the responses, it is a great thing that the game already implements that feature

**Comment by martosss** [comment]
> > Try "q:boil" or "q:contain"? That even works outside recipes, but I thought the OP meant exactly the crafting menu.
> 
> Neither of those would have let me find out that the fridge is a valid pocket for storing liquid. :-p 500L of it in case you were wondering. But only 400Kg.

There's no way to see the freezer/fridge's details unless you build it, which is annoying and needs changing, I agree ... but that goes for all vehicle parts.
IMHO it's not the fault of the filter system, it's the fault of the vehicle system. I had to watch a youtube tutorial to see how to use a cantilever to lift heavy stuff(robot corpse or engine) ... and the guy in the tutorial also had trouble doing it! :laughing:
