### ISSUE TITLE
Pebbles do not fit in the stone pouch

### ISSUE THREAD

**Issue by FourGreenFields** [CleverRaven/Cataclysm-DDA#55462]
### Describe the bug

Pebbles do not fit in the stone pouch, though logically they probably should.

### Steps to reproduce

1. Get stone pouch
2. Get pebbles
3. Select stone pouch in the inventory and attempt to insert

### Expected behavior

I expected pebbles to fit in the stone pouch. Ideally in greater number than rocks.

Pebbles are "rocks" after all, and both are used as ammo (though for different weapons). I'm also not aware of any special "ammo storage" item for pebbles, which they probably should have.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-3 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by bombasticSlacks** [comment]
easy first fix for someone. The following item has an example of how to make a pocket hold multiple different types of ammo:

```json
  {
    "id": "tactical_shotshell_pouch",
    "repairs_like": "legrig",
    "type": "ARMOR",
    "//": " stats taken from: https://condoroutdoor.com/ma12-shotgun-ammo-pouch.html",
    "name": { "str": "tactical shotshell pouch", "str_pl": "tactical shotshell pouches" },
    "description": "A pouch designed to hold shotgun shells or 308 rounds keeping them accessible and secure.  Has MOLLE straps for attaching to a belt or vest.",
    "weight": "300 g",
    "volume": "250 ml",
    "price": 2000,
    "price_postapoc": 200,
    "material": [ "nylon" ],
    "symbol": "[",
    "looks_like": "holster",
    "color": "dark_gray",
    "pocket_data": [ { "ammo_restriction": { "410shot": 12, "shot": 12, "20x66mm": 12, "signal_flare": 12, "308": 20 }, "moves": 30 } ],
    "material_thickness": 0.5,
    "flags": [ "WAIST", "WATER_FRIENDLY", "PALS_MEDIUM" ],
    "armor": [ { "encumbrance": 2, "coverage": 10, "covers": [ "torso" ] } ]
  },
```
