### ISSUE TITLE
It is hard to figure out how to complete the "Find Source of Robots" mission

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#55460]
### Is your feature request related to a problem? Please describe.

I have accepted the mission "Find Source of Robots" from the old guard representative at the refugee center. The mission created a marker pointing at the exodii main base. I have traveled to the marker and talked to Rubik, but the mission did not update. At this point I was confused: what else does the mission want from me? How do I complete it? Is it bugged?

It turns out that I was supposed to go back to the representative **and** select a specific topic in the dialogue.

There are two sources of difficulty here:
1. Zero feedback for the player after talking to Rubik
2. Unlike most quests, it is not enough to talk to the the quest giver after you complete it - you have to notice that there is a new option in the dialogue.

### Solution you would like.

How I think the mission should behave:
1. When the mission is accepted: mark the exodii base (same as now)
2. When I talk to Rubik: move the mark back to the quest giver
3. Complete the mission as soon as I talk to the representative again

If this is not currently possible in JSON, we should consider changing the JSON API to support this type of mission.

### Additional context

The current implementation: MISSION_OLD_GUARD_REP_3 is an MGOAL_GO_TO mission. MGOAL_GO_TO is an oddball: when **not** given by an NPC it can be completed simply by reaching the destination, but when given by an NPC like in this case it can only be completed:

* By talking to the quest giver *while* at the target location _or_
* By an explicit mission_success effect

https://github.com/CleverRaven/Cataclysm-DDA/blob/97018efac327385dca803906e5fe54097ce31dd8/data/json/npcs/refugee_center/surface_visitors/NPC_old_guard_representative.json#L241-L268

MISSION_OLD_GUARD_REP_3 uses mission_success

https://github.com/CleverRaven/Cataclysm-DDA/blob/97018efac327385dca803906e5fe54097ce31dd8/data/json/npcs/refugee_center/surface_visitors/NPC_old_guard_representative.json#L140-L156

**Comment by Maleclypse** [comment]
I think what you are suggesting is a possible mission design but I'm not 100% on that.  There are a number of similar options in mission creation where it isn't easily clear what the difference is when adding new missions.
