### ISSUE TITLE
Amigara horrors each drop an artifact

### ISSUE THREAD

**Issue by CalKerethi** [CleverRaven/Cataclysm-DDA#55475]
### Describe the bug

When slaying a group of Amigara horrors at a fault site, every horror dropped an artifact.

### Steps to reproduce

1. Jump to different mines until you find one with the long minecart track down to the odd fault.
2. Log into the computer and disturb that which should not be disturbed.
3. Regret your choices. Defeat the horrors, hopefully.
4. Check inside the bodies and see how many have artifacts.

### Expected behavior

I believe the intent was to only drop an artifact when the last horror of the encounter dies. Possibly related, I was able to move away from the fault after the first horror died, and I think that should also only trigger after the encounter is over.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 97018ef [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Gavin-319** [comment]
I killed a bunch of them in a mine earlier and not a single one dropped an artifact. They all dropped a bunch of Arcana parts though so it might be Arcana disabling artifact spawns or something but to me it looks like artifact drop rates are extremely random.

**Comment by a-chancey** [comment]
Yeah, that's likely an interaction with Arcana. I killed 4 recently on stream and each dropped an artifact.

**Comment by Night-Pryanik** [comment]
Amigara death function was broken in #49439 when mdeath functions were converted from hardcode to jsonified spells. I'm not sure if it's possible at all to properly rework checks for existence of other amigaras via json means.

I suggest reverting changes from #49439 related to amigara and make them hardcoded again.
