### ISSUE TITLE
Unable to unload RC Car

### ISSUE THREAD

**Issue by Arokha** [CleverRaven/Cataclysm-DDA#55481]
### Describe the bug

`U`nload does not work on the RC car. It does nothing. You can still `r`eload it with nearby batteries, though, so it doesn't block use.

### Steps to reproduce

1. Have an RC car with an ultralight battery (the type it accepts).
2. Attempt to `U`nload the RC car, menu closes, but checking inventory shows it's still got the battery.

### Expected behavior

The battery is removed from the RC car.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 7fa132e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

### Additional context

[McGill.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8099394/McGill.zip)
Here's the save file. I'm standing on the RC car. Just hit `U`nload and pick the RC car. The mods are all stock mods so shouldn't have an issue loading.

**Comment by haveric** [comment]
Can confirm. Unloading a flashlight works perfectly fine, but unloading an RC car does nothing.

**Comment by LeahLuong** [comment]
I believe this issue is related to #54330. The RC car has multiple pockets & I think this is confusing the 'U'nload command in the same way. There may be other items like this: battery-using items w/ additional pockets.
