### ISSUE TITLE
Pre-rendered Wooden Cruiser floors are treated as deep water

### ISSUE THREAD

**Issue by zantimer** [CleverRaven/Cataclysm-DDA#55483]
### Describe the bug

The Wooden Cruisers, oft spawning at freshwater research stations, have went out of my playthroughs since I went back to experimentals approximately 10-20 days ago due to me assuming that a massive stamina loss while moving and mood maluses are intended features.
However, having ran into one again, I have noticed that the stamina, weariness and mood maluses correspond directly to my character's athletics, being the same as swimming in deep water - +/- a bar of stamina per ten tiles moved, that gets slightly reduced, but not nullified by crouching/going prone. 
The issue persisted on other Wooden Cruisers, but not any other boat

### Steps to reproduce

1. Spawn at/teleport to a freshwater research station/other places with possible pre-rendered Wooden Cruisers
2. Get onto the ship
3. Look at V to see a maximum wet debuff after a tile, and a bar of stamina gone after going from back to the top of the ship

### Expected behavior

I expected that keeping balance on a ship would be more difficult, therefore more tiresome, than land, but not to as extreme of a point.

### Screenshots

![image](https://user-images.githubusercontent.com/99617630/154741482-a2605ee3-d423-4939-acb8-8c7c3ab0279d.png)

Start point, fresh rested, well fed survivor

![image](https://user-images.githubusercontent.com/99617630/154741756-9c3fc4d2-e1f9-4c2c-8ad7-c4ab11d748e9.png)

End point, ten tiles moved, a bar of stamina gone

### Versions and configuration

OS Windows 10 
game ver Experimental 2022-02-15-0701, as well as older versions and the newest experimental 2022-02-18-0721, as well those inbetween
graphics tiles
 language English
mods
Disable NPC Needs
No Fungal Growth
Bionic Professions
Magiclysm
Make bows great again
Mythical MMA
Mythical MMA mods extension
Graphical Overmap
Graphical Overmap Magiclysm
SpeedyDex
Stats through skills

### Additional context

I am somehow convinced at this point that the "perpetrator" here is wooden aisles, as the usual boat hull slowdown still kicks in, even though they are in a good state

**Comment by LeahLuong** [comment]
Does your char get wet when doing this?? Maybe the game doesn't think you're in a vehicle while traversing the aisles.

**Comment by zantimer** [comment]
Yes, as soon as the character steps on the first boat tile, be it door or just aisle, they get the maximum malus for Wet in the mood menu, as well as the losses of stamina/weariness are also corresponding on a scale 1:1 to swimming in deep water.

**Comment by LeahLuong** [comment]
Then this is either overlooked by #40026 or there is something strange w/ the way Wooden Cruisers are built.
