### ISSUE TITLE
Crash on crafting modified M203

### ISSUE THREAD

**Issue by utechenko-v** [CleverRaven/Cataclysm-DDA#55505]
### Describe the bug

Crash on crafting modified M203 - on crafting finish.

### Steps to reproduce

1. Get components for modified M203 crafting
2. Go to your faction camp with some NPCs (not sure if it is important)
3. Start crafting and craft it to the end
Result: game crashed at the end of crafting, Segmentation fault (logs and savefile attached)

### Expected behavior

Modified M203 should be successfully crafted, there should be no crash.

### Versions and configuration

- OS: Windows 10
- Game Version: 
- - build type: windows-tiles-x64
- - build number: 2022-02-19-0828
- - commit sha: 6149a274ae843027641432961c9fd197b9ebf3ec
- Graphics version: Tiles
- Ingame language: Ukrainian (partial translation)
- Mods loaded: dda, no_npc_food

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8102358/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8102359/crash.log)
[save_2022_02_19.zip.001.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8102376/save_2022_02_19.zip.001.zip)
[save_2022_02_19.zip.002.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8102377/save_2022_02_19.zip.002.zip)
* Note: savefile archive has been split in 2 parts and renamed - probably need to rename it back to "save_2022_02_19.zip.001" etc. to unzip

**Comment by bombasticSlacks** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/55500 should fix this too
