### ISSUE TITLE
Three spaces are present in one follower dialog

### ISSUE THREAD

**Issue by Faalagorn** [CleverRaven/Cataclysm-DDA#55508]
### Describe the bug

There are three spaces instead of two (so there's one extra space somewhere in the code) in the follower's response describing the engagement modes that appear after selecting "Change your engagement rules", between the description of the follow distance and silence.

### Steps to reproduce

1. Make NPC to become your follower.
2. Talk to them.
3. Select "Change your engagement rules".
4. Observe the resonse and watch for three spaces instead of regular two between options descriting distance and silenced weapons.

### Expected behavior

Only show two spaces

### Screenshots

![screenshot_2022-02-19-201041](https://user-images.githubusercontent.com/4951331/154815795-6df92eae-507c-4121-bf87-2b95d6d2a548.png)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.F-6205-g7fa132e8449 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Tried troubleshooting the issue on Discord, but were unable to do so, so maybe someone more clever than me could do it. Shouldn't be something too hard, so possibly a good first issue.

**Comment by xuvatilavv** [comment]
After playing around in Paint, it appears to be four spaces:

![154815795-6df92eae-507c-4121-bf87-2b95d6d2a548](https://user-images.githubusercontent.com/18742123/154848691-c73a7e12-3ece-4439-ad8b-9b1d78146b1b.png)

From what you linked in Discord, it's probably two of these being "No" in a row:

https://github.com/CleverRaven/Cataclysm-DDA/blob/f0f6f190a1844e7a8c15046e5d57eddf84488bad/data/json/npcs/TALK_COMMON_ALLY.json#L254

**Comment by Faalagorn** [comment]
> After playing around in Paint, it appears to be four spaces (unless I've got the kerning wrong):
> 
> ![154815795-6df92eae-507c-4121-bf87-2b95d6d2a548](https://user-images.githubusercontent.com/18742123/154848691-c73a7e12-3ece-4439-ad8b-9b1d78146b1b.png)
> 
> From what you linked in Discord, that could be something like two of these being "no" in a row:
> 
> https://github.com/CleverRaven/Cataclysm-DDA/blob/f0f6f190a1844e7a8c15046e5d57eddf84488bad/data/json/npcs/TALK_COMMON_ALLY.json#L254
> 
> Or just one? Depends on how it inserts the normal sentence separator.

That might make sense, since in Polish, when I replaced two spaces for one, it seems to be two spaces instead?
![screenshot_2022-02-20-175015](https://user-images.githubusercontent.com/4951331/154854090-2119342f-1777-4faa-90c6-2c12b2758954.png)

If so, do you think there's an easy fix for it?

**Comment by xuvatilavv** [comment]
> If so, do you think there's an easy fix for it?

I'm not sure, I've never touched this before either. I'm looking into it but I haven't found much yet. Just that this function appears to be related to building the string:

https://github.com/CleverRaven/Cataclysm-DDA/blob/f0f6f190a1844e7a8c15046e5d57eddf84488bad/src/condition.cpp#L1751

Still trying to figure out how it works.

**Comment by xuvatilavv** [comment]
This might be above my head as well, sharing my progress so I can go rest my brain a bit in case anyone else wants to pick it up.

The function I mentioned above just builds the conditions to be used elsewhere, this looks like where the yes/no decision would occur:

https://github.com/CleverRaven/Cataclysm-DDA/blob/f0f6f190a1844e7a8c15046e5d57eddf84488bad/src/npctalk.cpp#L4627-L4649

This is where the "and" would be constructed, if it's a duplication issue it might be related to this:

https://github.com/CleverRaven/Cataclysm-DDA/blob/f0f6f190a1844e7a8c15046e5d57eddf84488bad/src/npctalk.cpp#L4563-L4584

These parts of the dialog system & JSON loading look to be very generically written and used everywhere, so I feel like if it was duplication it'd be showing up in a bunch of other places. I might be looking in the wrong area, not sure what else it might be.

Oh, one question though, if you set an override for silenced weapons (not sure what that is, whatever makes it use the `"  OVERRIDE: "` string), does a similar issue happen?
