### ISSUE TITLE
NPC attitudes should govern starting rules

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#55507]
### Is your feature request related to a problem? Please describe.

Neutral NPCs starting rules for “investigate unseen sounds” etc should depend on their attitude ratings like fear and bravery. 

### Solution you would like.

Portal storms to be investigated or not based on random chance and internal stats for NPCs. 

### Describe alternatives you have considered.

None

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
