### ISSUE TITLE
Vehicle parts with the same name as another part can't be installed

### ISSUE THREAD

**Issue by CalKerethi** [CleverRaven/Cataclysm-DDA#55511]
### Describe the bug

When installing a vehicle part that has multiple entries with the same name (windshield, bike basket, seat, others), only one of them can be used. In some cases, multiple entries show up in the shape menu but all have the same end result. The full variants from #48798 don't appear to have entries at all.

### Steps to reproduce

1. Load a tileset (I was using UltiCa) that distinguishes between windshield and windshield_full.
2. Spawn a Luxury RV.
3. Remove one of the side windows in right side of the living area.
4. Try to reinstall it in the same shape (windshield Right Vertical). It will show up as the short kind from the cab instead.

### Expected behavior

Different options on the shape menu should switch to their associated look. Full variants should be selectable.

### Screenshots

![image](https://user-images.githubusercontent.com/85195781/154818187-e313b626-6514-4f08-a98a-4c7bbbf06f78.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 6149a274ae [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

The core of the issue seems to be that parts with the same name are merged into one choice, but the shape menu can't change the vehicle part ID, only the variant. Any potential fix I could come up with would touch a lot of stuff. It can be worked around in the JSON by giving variants unique names ("full windshield", "wheelchair basket", "windshield seat"...), but then the shape menu can't be used to switch between them.

**Comment by LeahLuong** [comment]
I wonder if #55426 broke this. Testing on a version from before 2022-2-16 might show.

**Comment by dseguin** [comment]
> I wonder if #55426 broke this. Testing on a version from before 2022-2-16 might show.

The version in the bug report is from before that PR was merged.
