### ISSUE TITLE
Bō length exceeds length of primary ingredient

### ISSUE THREAD

**Issue by a-chancey** [CleverRaven/Cataclysm-DDA#55514]
### Describe the bug

The recently added bō is 180cm, carved and oiled lovingly out of a plank, which is only 130cm.

### Steps to reproduce

Hit fab 5
Try to make a bō with a plank and oil
Succeed
marvel at the blob magic adding over a foot and a half of length to the wood. 

### Expected behavior

I expect materials to not grow in length, especially when being carved and with no fasteners to attach pieces together. 

### Versions and configuration

- OS: windows 10
- Build: experimental from 2/17, but it’s still the same recipe currently
- Language: English
- Mods loaded: dda

### Additional context

Should be an easy fix. It just needs the item changed to a long stick instead of a plank.

**Comment by Maleclypse** [comment]
Easiest thing then would be adjust it to require wooden beam then probably.

**Comment by LeahLuong** [comment]
Heavy wooden beams are crafted from 6 logs. They can be cut into 4 wooden panels which themselves can be cut into 4 planks apiece.

Using a wooden beam seems like overkill when quarterstaves are made from long sticks.

**Comment by Sniper27IT** [comment]
Wooden beam has a similar issue: it is used to craft Long Pole which has a lenght of 305 cm, but the beam has a lenght of 244cm.
Long Stick or Long Pole would be both viable as solution to craft the Bo; IMHO Long Stick maybe is better, a Bo and a Quarterstaff are similar weapons so is reasonable to craft a Bo from a Long Stick.

**Comment by anoobindisguise** [comment]
Long Pole is what's needed to make pikes, since it's straighter and more fine than a random long stick you found, it could be a good alternative. You can always shave it down.
