### ISSUE TITLE
Eliminate Sort Spam

### ISSUE THREAD

**Issue by LeahLuong** [CleverRaven/Cataclysm-DDA#55521]
### Is your feature request related to a problem? Please describe.

This is what happens when you assign a follower to a faction camp (AKA "famp") & they have sorting loot as a priority w/ nothing else to do (in 0.F-3):

![Screenshot_20220219-195620](https://user-images.githubusercontent.com/91638992/154834081-2a3bae9b-a0f9-4bdb-a04a-03e48d65cefa.png)

Now, imagine this w/ multiple followers who are either waiting around to sort loot or doing productive things in addition to the messages generated by your own char's activities.

### Solution you would like.

I think it would be good if the loot sorting message was eliminated altogether when a follower is assigned to a base. You presumably assigned them & set their priority for it so needn't be informed of it so regularly.

### Describe alternatives you have considered.

Shortening the message for "completing" the sorting task would make it take up less real estate & seem less spammy. If it can't be masked entirely, @ least make it less wordy.

Alternatively, it might be better to simply run a check for whether there is anything to sort in the 1st place; finding nothing, there'd be no reason to begin the task & subsequently "complete" it.

### Additional context

Keep in mind that a solution which takes up less system resources is prob better. Fully staffed famps can begin to bog down during time-intensive tasks (e.g., reading, crafting, sleeping).

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
