### ISSUE TITLE
Monster spells can not be used in melee

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#55528]
### Describe the bug

The game dont allow to use spells for monsters, if the enemy on 1 tile range, and use default melee instead (which is not okay sometimes, especially if you try to make AoE melee attack)
for example:

### Steps to reproduce

0. Give your character Debug invincibility
1. Spawn boomer glutton
2. approach to him on 1 tile range
3. spam `.`
You can see it doesnt vomit sludge and spews bile anymore, instead it only attack you in melee

### Expected behavior

Allow to use spells in melee combat, same as another `special_attacks`
or
Make a field in `special_attacks`, that allow to use the spell in melee combat

### Screenshots

![GIF 20 02 2022 15-05-22](https://user-images.githubusercontent.com/67688115/154846618-3dfcd065-9d82-4a2c-9374-05c8c8b75275.gif)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 919d0fc [32-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]
]

**Comment by Venera3** [comment]
If you're invisible you're not a valid target for special attacks - random-walking or scent/sound-tracking monsters bumping into you triggers a normal melee attack.

**Comment by GuardianDll** [comment]
it doesnt work with another monster either
![GIF 20 02 2022 15-37-10](https://user-images.githubusercontent.com/67688115/154847932-9152e1d6-c54e-4198-a5bd-311e276eb2a5.gif)
![GIF 20 02 2022 15-38-19](https://user-images.githubusercontent.com/67688115/154847976-7ade5f0d-cf91-460c-b558-aa9469507344.gif)

**Comment by GuardianDll** [comment]
oh, mistake, i write "debug **invincibility**"

**Comment by Venera3** [comment]
Okay, the problem seems to be that they have a 1-turn cooldown on bites and a 28-turn one on the spell. Bumping the bite cooldown to 2 lets them get a spell off when in melee range.

**Comment by GuardianDll** [comment]
if it were that easy i didn't open the issue here
`"cooldown": 28` -> `"cooldown": 2,`
![GIF 20 02 2022 20-47-34](https://user-images.githubusercontent.com/67688115/154861432-59b6ba80-5887-483e-a2bd-a1bd1129e8f6.gif)
(i test it with another creature, that had 0 cooldown, this is just the closest example that has spell attacks)

**Comment by Venera3** [comment]
You want their *bite* to be on cooldown. If you set their bit to 2 turns they can fire the spell (unsurprisingly, I tested it before commenting...).

**Comment by GuardianDll** [comment]
hmmm
just delete all another attacks, and it began to use it.
thats odd, because in #55509 `mon_shambling_mound` in almost same conditions use it only once per 5-10 seconds, and i dont understand why

**Comment by Maleclypse** [comment]
This looks good to close, if I'm reading this correctly if you have one special attack that can be used every turn then the monster will use it every turn and never use their other attacks?
