### ISSUE TITLE
Json error: <unknown source file>:EOF: "variants" missing loading any character

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#55536]
### Describe the bug

 DEBUG    : Error: Json error: <unknown source file>:EOF: "variants" missing

 FUNCTION : load_character_tab
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\main_menu.cpp
 LINE     : 1069
 VERSION  : f0f6f19

### Steps to reproduce

1. Create a character
2. Save your character
3. Load the saved character.
4. Get the error described above
5. Try to load again
6. Load successfully.

### Expected behavior

No errors in this context.

### Screenshots

N/A

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: f0f6f19 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Disable NPC Needs [no_npc_food],
    Fewer Soldier Extras [Fewer_Soldiers],
    No Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    No Vault [No_Vault],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

### Additional context

Here is my save file, in case you can't reproduce this issue on your machine.

It is completely possible that this issue is somehow specific to my computer, but I figured I would report it.

[Aldrin.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8104703/Aldrin.zip)

**Comment by ZhilkinSerg** [comment]
Broken mods probably.

**Comment by Inglonias** [comment]
There are two sources for the mods I use - my own brain and the default mods that come with the game. That definitely narrows things down if you're right. I suspect it's the fewer soldier extras mod I made.

**Comment by Inglonias** [comment]
I was able to reproduce the problem after creating a world with zero mods outside of the core game files.

Look, if you can't reproduce the issue, just say that. I'd believe you1

**Comment by Inglonias** [comment]
Updating the game did not resolve the issue.
 DEBUG    : Error: Json error: <unknown source file>:EOF: "variants" missing

 FUNCTION : new_character_tab
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\main_menu.cpp
 LINE     : 870
 VERSION  : 5822d67

**Comment by ZhilkinSerg** [comment]
Which tileset are you using?

**Comment by Inglonias** [comment]
ultica for graphics, retroASCII for overmap

**Comment by dseguin** [comment]
Is it possible that your tileset is out of date? Try checking `gfx/UltimateCataclysm/layering.json` to see if the changes from https://github.com/I-am-Erk/CDDA-Tilesets/pull/1240 are applied

**Comment by Inglonias** [comment]
Replacing my layering.json file with the contents of the file in the repo did the trick. Excellent detective work.

**Comment by Inglonias** [comment]
Root cause of this issue was due to Catapult migrating my tilesets between updates.
