### ISSUE TITLE
Running the game in gdb

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#55531]
### Describe the bug

I am trying to run the game in gdb to get some traces, but it does not work.

### Steps to reproduce

Both tiles and curses hang on loading a save with gdb.

1. `gdb cataclysm`
2. `run`
3. It fails due to forks.
4. `set detach-on-fork off`, `set schedule-multiple on`
5. Program terminated with signal SIGPIPE, Broken pipe. The program no longer exists.

1. `gdb cataclysm-tiles`
2. Even with the above options, it hangs and eventually also emits SIGPIPE and breaks.

### Expected behavior

It would be great if there are instructions on how to get traces of cdda, since I want to go through crashes I reported and add traces to them but I am no dev and actually have no clue about gdb, I only know the very basics.

### Versions and configuration

- experimental

**Comment by Qrox** [comment]
What is your system and gdb version? I ran the game in MinGW-w64 gdb 8.1 on Windows and successfully loaded a save. It was slow but it eventually loaded.

You can also try attaching to the process after the save is loaded. Find the PID, start gdb, and enter `attach <PID>` should do it.

**Comment by NetSysFire** [comment]
This is Arch Linux with gdb 11.2. I built cdda unstripped for the debug symbols, which resulted in a 1.5 gb binary. After more debugging I found out that for some reason it freezes on any error without even running in gdb and got more weird behavior using this giant binary and eventually gave up.

**Comment by Qrox** [comment]
Not sure if that's related to the binary size, but you can use the following command to move the debug symbols to a separate file and link to it from the binary:

```
objcopy --only-keep-debug cataclysm-tiles.exe cataclysm-tiles.debug
strip --strip-debug --strip-unneeded cataclysm-tiles.exe
objcopy --add-gnu-debuglink=cataclysm-tiles.debug cataclysm-tiles.exe
```

**Comment by NetSysFire** [comment]
I use a PKGBUILD for building (adapted version of cataclysm-dda-git). I will split the binary using its options.

Overall I got some really weird behavior with the debug build, like any JSON errors are freezing the game which is apparently caused by invisible error dialogs which go away when I press any key and for a fraction of a second I can see the usual red debug message, which doesnt happen with the normal build.

**Comment by NetSysFire** [comment]
Using debug symbols in a separate file actually makes everything work correctly.
