### ISSUE TITLE
json-errors

### ISSUE THREAD

**Issue by Keesaev** [CleverRaven/Cataclysm-DDA#55533]
### Describe the bug

Linux 5.15.0-18-generic Ubuntu 22.04 Jammy Jellyfish. Recently updated Ubuntu from 20 to 22, installed 0.F-3 over 0.D

0.F-3 tiles starts with this message:

```
 DEBUG    : (json-error)
Json error: <unknown source file>:2:18: Invalid or misplaced field name "fontblending" in JSON data

{
  "fontblending":
                 ^
                  false,
  "fontwidth": 8,
  "fontheight": 16,


 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : src/json.cpp
 LINE     : 122
 VERSION  : 0.F-3

```
Seems like json has an extra '\n' symbol
Same messages are displayed for:
* fontheight
* fontsize
* fontwidth
* map_fontheight
* map_fontsize
* man_fontwidth
* overmap_fontheight
* overmap_fontsize
* overmap_fontwidth

Cant really find these corrupt files with `grep -nir fontblending $(dpkg -L cataclysm-dda-data | grep .json)`
Do I have to purge and reinstall? I have some save files that I dont want to loose

### Steps to reproduce

1. Linux 5.15.0-18-generic Ubuntu 22.04 Jammy Jellyfish
2. Install 0.F-3 over 0.D (not sure if necessary)
3. `sudo apt install cataclysm-dda-curses cataclysm-dda-data cataclysm-dda-sdl`
4. Run 'tiles' executable
5. Error appears before main menu is shown

### Expected behavior

jsons should be parse-able?

### Versions and configuration

- Linux 5.15.0-18-generic Ubuntu 22.04 Jammy Jellyfish.
- 0.F-3
- log:
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8104467/debug.log)

**Comment by LeahLuong** [comment]
On my install, options.json is found in com.cleverraven.cataclysmdda/files/config/. You might want to check the entry for FONT_BLENDING to see if something is wrong w/ the way it's written as compared to neighboring settings; it should be about halfway down scrolling thru the file. My entry for that looks like this:

  { "info": "If true, fonts will look better.", "default": "Default: False", "name": "FONT_BLENDING", "value": "false" },

If that doesn't yield anything, you should be able to make a copy of your save folder, put it somewhere else, & try reinstalling. Should be in the same files folder as config. After reinstallation, you should be able to drop your save folder back in place & try firing it up again.
