### ISSUE TITLE
NPC & vehicle error after trying to make the NPC sleep inside of it

### ISSUE THREAD

**Issue by WhitePaperWraper** [CleverRaven/Cataclysm-DDA#55534]
### Describe the bug

NPC throws errors (1) when moving, Doesn't follow me inside a vehicle.
After messing around a bit, I found out that visiting a certain tile inside the vehicle throws another error(2), but fixes the NPC

Error 1:
>19:48:03.801 ERROR : src/map.cpp:1103 [void map::unboard_vehicle(const tripoint&, bool)] map::unboard_vehicle: vehicle not found

Error 2:
>20:03:38.351 ERROR : src/map.cpp:1064 [void map::board_vehicle(const tripoint&, Character*)] map::board_vehicle: passenger (Todd Castle) is already there

### Steps to reproduce

1. Have a sleepy NPC-buddy
2. Make him enter a car, because the back seat may provide some semblance of comfort
3. Allow them to sleep when they're in the car, wait for them to lay down
4. Go foraging in the woods
5. When coming back, find them outside of the car, sleeping
6. Wake them up
7. They won't enter the car, keep spamming errors

### Expected behavior

NPC should get into the vehicle, without throwing an error

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 11 (bullseye); Release: 11; Codename: bullseye; 
- Game Version: c7ffe3e [64-bit]
- Graphics Version: Tiles
- Game Language: System language [] // en-us 
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8104496/debug.log)
Save before I found a way to "fix" the npc. Enter the second seat on the right-hand side inside the armored car or the driver side backseat of the civilian car to trigger the second error and "fix" the NPC's AI
[American Canyon (copy 1).zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8104499/American.Canyon.copy.1.zip)

Thanks for your time

**Comment by LeahLuong** [comment]
Similar to #53475 & #53546. The game stores vehicles & NPC's slightly differently & this sometimes results in these discrepancies. Try syncing up your sleep cycles w/ your followers so you don't have to leave them in your vehicle where the reality bubble may unload & load them incorrectly as you leave their area & return.

This will hopefully be addressed in the future but may have to wait until after 0.G's release.
