### ISSUE TITLE
Neutral NPC following player can't be moved out of the way

### ISSUE THREAD

**Issue by IdolTears** [CleverRaven/Cataclysm-DDA#55544]
### Describe the bug

NPC that follows the player around for a mission can not be moved out of the way when they e.g. block an exit, because they are neutral and not friendly 

### Steps to reproduce

1. Accept a quest to lead a neutral NPC somewhere 
2. NPC can only be lured away
(3. With NPC still neutral, walk a few spaces into a small room until NPC stands in the door
4. Cry if the room is too small to lure them inside)

### Expected behavior

Let the player use the swap places or push out of the way commands on neutral NPCs (or possibly restricted to mission NPCs) 

### Screenshots

![cataclysm-tiles_olyUv0ipuL](https://user-images.githubusercontent.com/100101247/154871387-1a2d33eb-8d20-4111-aa23-00a1df33360c.png)
![cataclysm-tiles_XnIRBdiKWs](https://user-images.githubusercontent.com/100101247/154871536-69acdfe9-1063-40be-80fe-4f598b69990b.png)

### Versions and configuration

- OS: Windows 10
- Version: 5822d67 
- Build: 2022-02-20-1818
- Graphics: Tiles
- Language: English
- Mods: default (Dark Days Ahead, Disable NPC Needs, No Fungal Growths, Bionic Professions)

**Comment by LeahLuong** [comment]
Related to #54263. "Expected behavior" seems totally reasonable & possibly an easy fix. Then again, who knows what mischief players will get up to w/ their newfound power to move neutral NPC's wherever they want??

Technically, you can currently displace neutrals by pushing a friendly into them. You know, once you let Pandora out of his box, you can't just put him back in there.

**Comment by IdolTears** [comment]
Yeah, I am worried about potential repercussions, which is why I suggested limiting it to mission NPCs, if that is actually possible without too much work (because while it is a very annoying edge case, it _is_ an edge case). Still potential for mischief, but a lot more limited, I think.

Alternatively, the mission could simply be removed. Would be a bit of a shame, though, I liked the urgency of having to take care of it as soon as possible to make the pyromaniac more predictable. 
Or perhaps a dialogue option that makes the NPC move somehow could be added?
