### ISSUE TITLE
NPC cannot choose correct melee weapons

### ISSUE THREAD

**Issue by Proxima-b** [CleverRaven/Cataclysm-DDA#55555]
### Describe the bug

Many of enemy NPC have either high unarmed skill level or at lease some sort of melee so it is reasonable to think they will use proper weapons or unarmed attack.
But instead, they throw their weapons towards my and take off their belts and helmets and weld it as weapon, resulting being kill by me fairly easily

### Steps to reproduce

1.Find hostile NPCs with melee weapons.
2.Agitate them then runing always.
3.NPCs chasing you, throw their melee weapons at you.
4.They take off their belts and weld it to attack you.

### Expected behavior

Idealy, make NPCs use proper melee weapon.
Or ban NPCs from using their weared armors as weapons.

### Versions and configuration

Latest experimental.

**Comment by LeahLuong** [comment]
You raised this as an issue in #54667 where Leland marked it as a dupe of #38609 & closed the issue. Stop posting dupe issues.

**Comment by Proxima-b** [comment]
> You raised this as an issue in #54667 where Leland marked it as a dupe of #38609 & closed the issue. Stop posting dupe issues.

I don't believe this is the same issue, #38609 specified that NPCs won't use ranged weapon advantages. However this issue is about NPCs throw out melee weapon and weld armor as weapon.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
