### ISSUE TITLE
Cataclysm not completely closing on close.

### ISSUE THREAD

**Issue by EkarusRyndren** [CleverRaven/Cataclysm-DDA#5555]
Just went to delete my test folder (Build g609d70a) and was given a "files in use" warning, checked the task manager and discovered four "cataclysm.exe*32" processes going, using about 20,000 KB of my RAM.

[Bug - Windows, Console Build]
[Needs Confirmation]

**Comment by mugling** [comment]
Closed as ancient. If reproducible with any recent copy of `master` can be reopened
