### ISSUE TITLE
Nomad harness requires a climate control kit

### ISSUE THREAD

**Issue by Jarewill** [CleverRaven/Cataclysm-DDA#55564]
### Describe the bug

After the nomad armor overhaul in #53567, the nomad harness was added, which included useful functions such as a water purifier and a flashlight.
However in it's crafting recipe it also requires an external climate control kit, even though it doesn't have climate control like the advanced nomad suit.

### Steps to reproduce

1. Read the nomad jumpsuit blueprint
2. Check the recipe for the nomad harness

### Expected behavior

The nomad harness to not require a part it doesn't have the action for.

### Screenshots

![image](https://user-images.githubusercontent.com/98614648/154991432-4761628d-1542-4e49-a4ee-db6082ed15fd.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 20H2
- Game Version: 6c74cc8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

@bombasticSlacks 
I could have filed a PR that changes this, but I wanted to ask you about it first.
The harness does not provide climate control, so what is the external climate control kit doing in it's recipe?
Maybe I'm not understanding something.

Though the harness does provide a water purifier, even if it doesn't require it in the recipe.
I don't think climate control would provide the same ability as an actual water purifier, so maybe I could change it to that instead?

**Comment by bombasticSlacks** [comment]
Thanks for pinging me.

It's just a mistake when I was copying things. So the climate control kit should be removed.

You could add a purifier if you wanted but I assumed that the purification could be done with just the wiring kit and CBM power (similar to how a kettle works). I don't have strong feelings either way.
