### ISSUE TITLE
Real life radiation glow is blue, not green

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#55587]
### Describe the bug

If you examine items which would contaminate you with radiation, they are described as glowing sickly green, which is not realistic.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/59517351/155076225-1d05ff2e-2944-4e3d-aa2a-cbdc2d6fd42a.png)

### Expected behavior

This is a tough one. The purely realism-based approach would be to change it to a blue glow, but everyone associates radiation with a green glow, so it might confuse players. HOWEVER:

This exact thing caused people, even a little six year old girl, to die horribly and painfully in real life. See https://en.wikipedia.org/wiki/Goi%C3%A2nia_accident#Opening_the_capsule, [Cherenkov radiation](https://en.wikipedia.org/wiki/Cherenkov_radiation) is real.
The Chernobyl survivors also reported a beautiful, laserlike blue glow above the reactor, which was Cherenkov radiation.

Changing this is trivial, as it only requires a simple string change. I did not flag it as a good first issue on purpose because I know that there might be people who disagree with this and I do not want a curious first-time contributor to work on something that is never going to get merged anyways and get discouraged, so this needs to be discussed and approved first before the label get applied.

### Versions and configuration

- experimental

**Comment by oosyrag** [comment]
https://www.thoughtco.com/do-radioactive-elements-glow-in-the-dark-608653#:~:text=In%20books%20and%20movies%2C%20you,bright%20blue%20or%20deep%20red.

Not all radioactive glows are the same color.

**Comment by Qrox** [comment]
Maybe add this as a news snippet: "Safety regulations require all civilian-use radioactive materials contain luminescent additives to give them the stereotypical green glow to warn users of radioactive leaks."

**Comment by AtomicFox556** [comment]
Why not change it to just mention the fact that an item is radioactive? Some sources of radiation don't glow at all, and those that do have various colors depending on what element it is.

**Comment by venum4k** [comment]
The description already says it's radioactive so changing the glow colour wouldn't really remove any information.

**Comment by LeahLuong** [comment]
Atomic nightlight & lantern produce Cherenkov blue glows while their respective recipes do _**not**_ contain water. Even if they did, the amount of shielding necessary to make them safe would render them useless as portable light sources.

**Comment by chrispikula** [comment]
I mean, marketing?  The Aftershock world likes it's publicly available plutonium.  They probably even advertise Cherenkov blue lipstick and hair dye.

**Comment by PsyXypher** [comment]
You could right "This item is damaged and is giving off deadly radiation!" or something. 

My reasoning for this is that a PC can pick up a vial of mutagen and immediately identify it as such. Since item identification isn't a thing in Cataclysm I don't see the harm in it.

**Comment by chrispikula** [comment]
> Also i think even air will glow with high enough radiation intensity. Isnt this effect similar to Aurora?

What you're thinking about is due to magnetic fields and plasma, which needs either very low atmospheric density, and huge area magnetic fields, or instantly lethal amounts.

Cherenkov radiation is specifically a result of particles going faster than the group velocity speed of light inside a material, akin to how a plane going faster than the speed of sound makes a sonic boom.  You can derive your Cherenkov spectrum from the index of refraction and particle velocities.  Air has an index of refraction of ~1.0001, so you'll never get visible colour from Cherenkov sources from something small until well after other effects have sterilized the surrounding area, or your nuclear bomb has just gone boom.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
