### ISSUE TITLE
Add ALLOW_TERRAIN_UNDER_OTHER_DATA to version 2 base/expansion layout indications

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#55590]
### Describe the bug

When expanding a faction base camp with a storehouse version 2 a debug error message complaining about a 9_mm_casing lying on the ground was produced. This issue will affect all version 2 base/expansion layouts.

### Steps to reproduce

1. Generate a field faction camp next to a field with some items on it.
2. Survey/expand the base onto the field with a version 2 expansion.
3. Get error message.

### Expected behavior

No error message, and items left undisturbed.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-6208-g7afb92d83f-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

This issue is the result of the introduction of new tags to clear/retain items when modifying terrain with blueprints, with the resultant need to update existing implementations to deal with the new functionality and checks. It can be noted that ignoring the error allows the player to continue to play with the desired functionality, so the issue isn't critical.

The version is "dirty" because I'm working on a PR. That work is unrelated to the error message, however.

Since all version 2 base/expansions use the same logic, all of them should be affected. The correct action is to add the token in the description to these.

I don't know if ALL faction camp blueprints are affected by this. There is a risk that is the case. If it is, the correct action is, again, to add the token to all "normal" blueprints, as you don't want the constructions to destroy things that happen to be dropped on those tiles (without there being any indication of exactly which tiles a blueprint will affect: the version 2 layouts are only an indication of where any blueprint will modify things, and the others don't have any indications at all).
There may, however, be oddball "unusual" blueprints where you may actually want to remove items, but it's not likely. There is a "furniture" token to explicitly remove furniture on a tile, so all furniture can be handled by the blueprint, leaving only items to cause trouble (vehicles already prevent constructions to be finalized).

**Comment by LeahLuong** [comment]
If something is built over an item, doesn't it simply place the item on top, still accessible to the player?? If so, the error message seems superfluous.

**Comment by PatrikLundell** [comment]
It does. However, when it happens to the vast majority of map activity, i.e. "normal" map generation outside of the camp and npc faction context, it is an issue where the map designer has to determine whether to obliterate the items that may have been spawned there, or leave the items on (or sometimes in) the spawned terrain. That's why the flags listed by the error message exist: to specify whether to remove items or leave them.
Accessibility depends on whether the PC can stand next to the location when something impassable is built there, though. A collapsed tower basement can well contain items you have to dig to get to, for instance (or at least it could in 0.E-2, although the quest object wasn't among those...).
