### ISSUE TITLE
Should leather have 2 blunt damage resist and not 1?

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#55594]
### Is your feature request related to a problem? Please describe.

Recently, Leather was changed from 2/2 protection to 1/3, reducing its blunt damage protection in favor of more cut protection. Leather is a pretty tough material and traditionally firefighter helmets were made of leather implying that there is a notable protective quality to it from impact. 

### Solution you would like.

Leather could probably afford to be 2/3 protection rather than 1/3. Cotton can only really be better at absorbing blunt impacts because it is easier to layer multiple mm of cotton as it is a lighter material.

### Describe alternatives you have considered.

It's possible that this doesn't need to change and it's correct as it is, although per mm of thickness I imagine leather should be better than unlayered kevlar, wool, cotton and other textiles. 

### Additional context

I mostly wanted to gauge opinions on this before I submitted a PR. Obviously the change itself is pretty trivial to make but it has a lot of balance implications.

**Comment by MylieDaniels** [comment]
It doesn't need to be a full integer increase, by the way.

**Comment by Aerin-of-the-Toast** [comment]
I might have played it too conservatively with the numbers I chose: I only did 1/3 to make the ratio more accurate with itself rather than in relation to other materials. Leather is more cut resistant than kevlar as well, isn't it? It's possible 2 bash 4 cut might even be more correct.

Basically I only did 1/3 cuz I only thought "leather is more abrasion resistant than it is bash resistant" without thinking about how leather is more bash resistant than equally-thick cotton or more cut-resistant than leather.

**Comment by oosyrag** [comment]
First few results returned by Google indicate that leather isn't superior to kevlar in terms of cut resistance for for similar thickness.

**Comment by bombasticSlacks** [comment]
Looking at cut resistance here https://www.motorcycleforum.com/threads/abrasion-chart.100827/

it's Kevlar > Cordura (nylon) > high quality leather

**Comment by anoobindisguise** [comment]
> Looking at cut resistance here https://www.motorcycleforum.com/threads/abrasion-chart.100827/
> 
> it's Kevlar > Cordura (nylon) > high quality leather
> 
> thought there are plenty of tests

I'm also seeing

> Tests are conducted all the time to compare the abrasion resistance of motorcycle riding gear materials and leather always comes out on top as the most durable material. Furthermore, leather does not melt from friction, it will cushion your fall more than motorcycle textiles would and it offers the best protection against a road rash. The fact that leather also lasts through multiple crashes whilst textiles will probably only last through one, says a lot about the difference in protection and impact between the two materials.

**Comment by oosyrag** [comment]
I would not classify abrasions and road rash as "cutting damage".

**Comment by bombasticSlacks** [comment]
True I was looking at cordura and sort of muddled things with motorcycle tests though there is value there for wear and tear. 

Here's a source for kevlar being 4x more cut resistant than leather. https://www.911gear.ca/blog/duty-gloves-/post/duty-gloves---part-3---glove-types---glove-life.html#:~:text=KEVLAR%20%2D%20Designed%20by%20the%20Dupont,more%20cut%20resistant%20than%20leather.&text=If%20your%20lining%20is%20yellow,Kevlar%20is%20not%20puncture%20resistant.

**Comment by bombasticSlacks** [comment]
Well now you've got me looking at real sources and not only does this white paper put kevlar at 4x the cut resistance to leather it puts cotton at more cut resistant than leather. Using a test very similar to cut attacks in game. 

https://www.google.com/url?q=https://www.mcrsafety.com/~/media/mcrsafety/publications/product-guides/kevlar-cut-testing-jce_cppt.pdf&sa=U&ved=2ahUKEwj26_OUh5X2AhXRlIkEHfN9CcUQFnoECAMQAg&usg=AOvVaw1d2wU7nlw02JkJxNdWcaPL

**Comment by Zireael07** [comment]
@bombasticSlacks: When researching for a fic I wrote, I discovered cotton is surprisingly resistant (esp. when wet!)

**Comment by SirPendrak** [comment]
Lether being 3x as ressistant to cuts puts in question why gambesons were much, much more frequently used in history than lether armors. 

> I would not classify abrasions and road rash as "cutting damage".

**Comment by anoobindisguise** [comment]
> Lether being 3x as ressistant to cuts puts in question why gambesons were much, much more frequently used in history than lether armors.

leather is much more restrictive and much more expensive, you can layer more mm of cotton than leather with similar levels of encumbrance. Equivalent thickness of leather is better than cotton, but they rarely have equivalent thickness afaict.

**Comment by oosyrag** [comment]
> Equivalent thickness of leather is better than cotton

Source? 

https://www.google.com/search?q=cut+resistance+equivalent+thickness+leather+vs+cotton&oq=cut+resistance+equivalent+thickness+leather+vs+cotton&aqs=chrome..69i57.11969j0j4&client=ms-android-oneplus&sourceid=chrome-mobile&ie=UTF-8

First few google results indicate cotton is more cut resistant at equivalent thicknesses. Also see link above.

My understanding of sirpendraks comment was that leather being 3x more cut resistant (not necessarily a fact, but what is being represented in the game) is incongruous with what was actually used historically.

**Comment by bombasticSlacks** [comment]
> leather is much more restrictive and much more expensive, you can layer more mm of cotton than leather with similar levels of encumbrance. Equivalent thickness of leather is better than cotton, but they rarely have equivalent thickness afaict.

That white paper I linked has the oz/yard^2 for each material they cut test and it does not agree with this statement.

**Comment by kevingranade** [comment]
No support for upping leather cut resistance.
