### ISSUE TITLE
Error screen when opening item list near finished charcoal kiln

### ISSUE THREAD

**Issue by Liork0** [CleverRaven/Cataclysm-DDA#55604]
### Describe the bug

An error message is thrown up whenever I bring up the "Item list in view" (V) after I "e"xamine a charcoal kiln and leaving the charcoal in.
 
Debug  line read as following : "tried to put an item (charcoal) count (2400) in a container (fake_char_kiln) that cannot contain it: pocket unacceptable because tried to put too many charges of ammo in item 
(full screenshot down below)
 
Message can be safely dismissed and bring up the "Item list in view" and happen only if within 6 tiles of the charcoal kiln, vision of it doesn't matter (ie must be in 6 tiles accessible by character)

### Steps to reproduce

1 : Examine a finished charcoal kiln (input is 2 log)
2 : Bring up Item in view (V) within 6 tiles pathable by character player.
3 : Error screen comes up

### Expected behavior

No error screen should happen, although the charcoal kiln itself hide item if you are not adjacent, which have 2 different expected behavior
1 : If adjacent to kiln, charcoal should be in item in view menu
2 : if not adjacent, charcoal should be hidden in item in view menu

### Screenshots

![Capture d’écran (1)](https://user-images.githubusercontent.com/99130783/155242234-496f6294-e06a-4ea9-b87e-7af23953d187.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 51e44ef [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by LeahLuong** [comment]
I was unable to reproduce this using my faction camp's (AKA "famp's") forge's charcoal kiln, w/ 2400 charcoal or more.

I imagine "fake_char_kiln" refers to the portable version. 1 way of avoiding this -- & keep in mind this is just my speculation! -- would be to remove the charcoal from the finished kiln instead of leaving it in there after 'e'xamining it. After all, the charcoal kiln's primary purpose is producing charcoal; it's not really functional if you don't remove its product before trying to make more.

**Comment by dholmes215** [comment]
I hit what appears to be this same issue, and have a save file (attached) that seems to reproduce it whenever I open the crafting menu or item view menu.  Loading the save and performing either of those actions should do it. I am running my own build from a couple days ago.

```
 DEBUG    : tried to put an item (charcoal) count (2420) in a container (fake_char_kiln) that cannot contain it: pocket unacceptable because tried to put too many charges of ammo in item

 FUNCTION : put_in
 FILE     : C:\git\Cataclysm-DDA\src\item.cpp
 LINE     : 1400
 VERSION  : 0.F-8717-g0ac1478845-dirty
```

This is the stack trace when it happens:

```
cataclysm-tiles.exe!input_manager::get_input_event(keyboard_mode preferred_keyboard_mode) Line 3747
cataclysm-tiles.exe!debug_error_prompt(const char * filename, const char * line, const char * funcname, const char * text, bool force) Line 369
cataclysm-tiles.exe!realDebugmsg(const char * filename, const char * line, const char * funcname, const std::string & text) Line 531
[Inline Frame] cataclysm-tiles.exe!realDebugmsg(const char * const <args_0>, const char * const) Line 78
cataclysm-tiles.exe!item::put_in(const item & payload, item_pocket::pocket_type pk_type, bool unseal_pockets) Line 1399
cataclysm-tiles.exe!inventory::form_from_map(map & m, std::vector<tripoint,std::allocator<tripoint>> pts, const Character * pl, bool assign_invlet) Line 529
cataclysm-tiles.exe!inventory::form_from_map(map & m, const tripoint & origin, int range, const Character * pl, bool assign_invlet, bool clear_path) Line 500
cataclysm-tiles.exe!inventory::form_from_map(const tripoint & origin, int range, const Character * pl, bool assign_invlet, bool clear_path) Line 471
cataclysm-tiles.exe!Character::crafting_inventory(const tripoint & src_pos, int radius, bool clear_path) Line 568
cataclysm-tiles.exe!select
[Pinebluff-charcoal-pocket-unacceptable.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8820592/Pinebluff-charcoal-pocket-unacceptable.zip)
_crafting_recipe(int & batch_size_out, const string_id<recipe> goto_recipe) Line 952
cataclysm-tiles.exe!Character::craft(const cata::optional<tripoint> & loc, const string_id<recipe> & goto_recipe) Line 326
cataclysm-tiles.exe!game::do_regular_action(action_id & act, avatar & player_character, const cata::optional<tripoint> & mouse_target) Line 2300
cataclysm-tiles.exe!game::handle_action() Line 2899
cataclysm-tiles.exe!do_turn() Line 704
cataclysm-tiles.exe!WinMain(HINSTANCE__ * __formal, HINSTANCE__ * __formal, char * __formal, int __formal) Line 766
```
