### ISSUE TITLE
Double definition bug

### ISSUE THREAD

**Issue by Junkinmytruck69** [CleverRaven/Cataclysm-DDA#55606]
### Describe the bug

The second character used in the same world causes the double definition error message and if skipped, makes the game crash frequently. 

![image](https://user-images.githubusercontent.com/78941154/155248096-024b3f02-3b83-4eaa-9617-e2588adde817.png)
![image](https://user-images.githubusercontent.com/78941154/155248209-42263d1c-bb16-48d0-8751-b788c4066c5c.png)
![image](https://user-images.githubusercontent.com/78941154/155248226-e173609b-13e0-4e12-a5e2-f5dded0b41ff.png)
![image](https://user-images.githubusercontent.com/78941154/155248239-c68edafc-e18e-4f04-996e-dbfb7cadbbea.png)

### Steps to reproduce

1. make a new world
2. create new character
3. suicide character
4. create 2nd new character
5. Error message happens either before or after the new character screen
![image](https://user-images.githubusercontent.com/78941154/155248870-2486d4e5-617f-4951-b01a-a8cf3dde100f.png)

### Expected behavior

No errors and a generally stable game.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 21H1
- Game Version: 30df995 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    Graphical Overmap [Graphical_Overmap]
]

### Additional context

If skipped the game suffers from random crashes with no error messages or permanent freezing

**Comment by LeahLuong** [comment]
Do the errors occur when running Alt Map Key w/out Graphical Overmap & vice versa?? Have you tried running w/ only default mods??

The "DEBUG" line in all those errors seems to indicate _the calls are coming from inside the house_. In other words, "(dda)" may indicate the base game "mod" has the dupes.

**Comment by Junkinmytruck69** [comment]
I realized after submitting the bug report that it was randomly happening
regardless of which mods  were active.

I will dig into it more after work and hopefully have a way to fix this
issue for others.

**Comment by Junkinmytruck69** [comment]
Update, the bug I'm getting is on the second character I play with in the
same world.

Setting the world to auto delete after every death solves the issue.
No clue why but it's at least a bandaid fix

**Comment by LeahLuong** [comment]
Reviewing OP for this thread seems wildly different than what you now understand about this issue. Please consider amending the bug report w/ cross-outs so when some1 is able to tackle this issue, they've a clearer understanding.

I don't believe this issue's come up before & it seems pretty easy to reproduce based on your description so it makes me think a recent PR broke something.

**Comment by nemesis688** [comment]
I can reproduce this bug by simply by loading into a game, then save and quitting, and finally trying to load back into a game. Shutting the game down fully stops it from occurring.

**Comment by AriaMoradi** [comment]
I have the same issue, running a build from f7c92b9d2f7964295fb4f09b4e5780b2f0c6d469 (I can confirm that the issue is not present in Frank.3)

### Reproduction method
- open the game
- create a new character
- start the game
- die (i.e. suicide)
- exit the game session (last words and all) 
- new game in the same world
- open any character creation menu
- same exceptions as the op
- If you hold space bar and persist through, the game initializes correctly and you get to the character creation menu just fine and you can start the game.  
- If you exit the game and restart, the issue is fixed

```
- OS: Linux
    - OS Version: <unknown> (It's ArchLinux)
- Game Version: f7c92b9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]
```

The first exception is
```
 DEBUG    : default (butchery_requirements) has two definitions from the same source (dda)!

 FUNCTION : static void mod_tracker::check_duplicate_entries(const T&, const T&) [with T = butchery_requirements; std::enable_if_t<mod_tracker::has_src_member<T>::value>* <anonymous> = 0]
 FILE     : src/mod_tracker.h
 LINE     : 76
 VERSION  : f7c92b9
```

**Comment by oosyrag** [comment]
#55916 has identified when this error started occurring. https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-02-21-2034

**Comment by Inglonias** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/compare/cdda-experimental-2022-02-21-1902...cdda-experimental-2022-02-21-2034

**Comment by Inglonias** [comment]
Ok, so, uh... The reason this started happening during that build is because that's when we started checking for this behavior. In this commit: https://github.com/CleverRaven/Cataclysm-DDA/commit/3652933106567436722f639b7e54326764f92f2b

@anothersimulacrum

**Comment by Inglonias** [comment]
I took a peek through all the errors getting thrown. These are the classes not being unloaded correctly when we close a world:

`butchery_requirements
disease_type
item_category
zone_type
ter_furn_transform
relic_procgen_data
ascii_art
`

**Comment by Inglonias** [comment]
Looks like the function responsible for this stuff is in do_turn.cpp at line 65: cleanup_at_end()

**Comment by kevingranade** [comment]
Just a spot check says that e.g.  butchery_requirements::reset_all() exists, but is never called.
It looks like these are normally called from DynamicDataLoader::unload_data().
