### ISSUE TITLE
deconstructing refrigerator placed by mapgen returns components

### ISSUE THREAD

**Issue by a-chancey** [CleverRaven/Cataclysm-DDA#55608]
### Describe the bug

When deconstructing the refrigerator placed by mapgen, it returns the refrigerator components still, rather than the placable furniture "fridge" item, similar to the disconnected oven item.

There is no option for Deconstruct Simple Furniture, either

### Steps to reproduce

1. find a refrigerator in a house
2. deconstruct it.
3. refrigerant tank!

### Expected behavior

I should get a fridge item to place elsewhere.

### Versions and configuration

- OS: Windows
    - OS Version: 11
- Game Version: 6ca3ef2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [english]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations]
]

**Comment by martosss** [comment]
Wouldn't that be too overfrozen? ... supposedly those components are the only thing you can salvage from the fridge in the house, since it's been already used by its previous owners.

**Comment by a-chancey** [comment]
What? It should be like the oven, which gives you a “disconnected oven”. You can then deconstruct that item for the parts. 

Like in real life you can unplug and move a fridge.
