### ISSUE TITLE
Vehicle reactors don't generate power on the vehicle UI and can't recharge other connected vehicles.

### ISSUE THREAD

**Issue by Gavin-319** [CleverRaven/Cataclysm-DDA#55602]
### Describe the bug

If a vehicle has a loaded and active reactor onboard, the reactor will charge the batteries, but the vehicle UI still registers +0 watts as long as the engine is off, and still registers the batteries as draining if other electronics are turned on, though the batteries actually charge and never drain thanks to the reactor running. Additionally, if the player cables the reactor-loaded vehicle to another with dead batteries, that vehicle's batteries will never charge.

### Steps to reproduce

1. Spawn in vehicle with empty batteries
2. Install a reactor into it, fill it with cells and turn it on
3. Turn on the vehicle's headlights after the batteries start charging
4. The vehicle UI will report that the batteries are being drained
5. Cable other vehicle to the reactor vehicle
6. Vehicle batteries do not charge

### Expected behavior

I expected the vehicle UI to report influx of power like they do when recieving power from an alternator, and also for other vehicles to recharge when connected.

### Screenshots

![image](https://user-images.githubusercontent.com/99597116/155239370-a921cad4-1cca-448f-aa0f-fb46b251d545.png)

Apologies if I did this wrong, this is my first time to try screenshotting Cataclysm. Seen here, the reactor is generating a lot of power, but the batteries list as draining regardless.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: ee956f5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Arcana and Magic Items [Arcana],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    C.R.I.T Expansion Mod [crt_expansion],
    DinoMod [DinoMod],
    Mythical Martial Arts [MMA],
    <color_yellow>Mythical Martial Arts - Mods Extension</color> [MMA_Mods_Extension],
    No Rail Stations [No_Rail_Stations],
    Tankmod: Revived [Tankmod_Revived],
    Disable NPC Needs [no_npc_food],
    No Bionic Slots [no_cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Culinary Days Ahead [culinary_days_ahead]
]

**Comment by Gavin-319** [comment]
The reactor works on bionic power, I'm just a dunce and didn't realize I had to actually turn the cable charger on.

**Comment by LeahLuong** [comment]
@Maleclypse I think Gav was explaining the reason for title change & not requesting closure for the thread.
