### ISSUE TITLE
Arm and leg armor consistency (single or double)

### ISSUE THREAD

**Issue by PlutusPleion** [CleverRaven/Cataclysm-DDA#55628]
### Describe the bug

One of the recipes for tempered heavy plate armor asks for 2 arm guards and 2 leg guards. This and its description leads me to believe that this is only one and not for both sides.

The armor does not have the "sided": true and has the ONLY_ONE flag meaning you can only wear one and that you are covered for both left and right limbs.

### Steps to reproduce

1. Load game
2. Look at tempered heavy plate armor recipe (2nd one that is combining already forged parts) and see it requires 2
3. Attempt to wear two tempered arm guards
4. See tempered arm guards is both in left and right arms in `+` relayer menu

### Expected behavior

Either these items should represent both sides and only require one for the full suit recipe 

or

The item should remain singular but you should be able to wear two

### Screenshots

![](https://i.imgur.com/NsWy8Pi.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 27ab2a5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Blaze Industries [blazeindustries]
]

### Additional context

Likely it's similar for the other variants

**Comment by MylieDaniels** [comment]
Agreed, and I'd prefer making them singular and sided to accommodate future tweaks to limbs.

**Comment by Drew4484** [comment]
Addressed in #55582, the intent is for each limb to be a separate item, but I initially didn't realize that ONLY_ONE would conflict with both limbs under the current system. #55566 will address this in a better way so the flag won't be needed.
