### ISSUE TITLE
'this' pointer is null [-Werror=nonnull]  on line 163 in src/npctalk.h 

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#55626]
### Describe the bug

CI is currently broken on GCC 11, Ubuntu cross-compile to MinGW-Win64, Tiles, Sound

1. Build failure introduced by 90f84f41045905cb051c8e9f896e8ffa0ea09a35
2. The pointer it thinks may be null is `npc_list[i]`.
3. This is a false positive
4. See also https://gitlab.com/inkscape/inkscape/-/issues/2206

### Steps to reproduce

Run the CI

### Expected behavior

it compiles

### Versions and configuration

8f8e2b4742118268cf03886933762d5d897547c9

**Comment by hexagonrecursion** [comment]
IMHO the cleanest solution is to add a new method to character to get rid of the need to dynamic_cast

**Comment by mqrause** [comment]
#55609

**Comment by hexagonrecursion** [comment]
Fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/55609
