### ISSUE TITLE
Weird behavior after wall wires setup

### ISSUE THREAD

**Issue by Shibimon** [CleverRaven/Cataclysm-DDA#55635]
### Describe the bug

I dabbled with wall wiring in a rural house im using but was missing a power source, so i got a vehicle filled with solar panels and connected it to the external wall of the rural house but didnt seem to work, so i tried to plug some individual wired walls to the next one on a beeline to my appliances inside, and now works, but reading, crafting, and i assume any auto-time-advance related activities are slowed to a crawl, like a full minute or two between each book update when reading.

Connecting lots of wall wires seem to bug something up slowing game to unplayable state on auto-time-advance related activities.

### Steps to reproduce

I have a setup like this:
(Every ">" is a wall i manually connected to the next link)
Car with panels>>>>>door>>>hallway>*>>>standing lamp
*(I have a welding cart i found with a battery here, don't know if its affecting the issue)

### Expected behavior

Connecting a vehicle to a house external wall should automatically connect it to the entire house, and i understand this tools are new and being worked on, but we should have ways to reset and/or hide them.

Connecting walls shouldn't make the game slow to a crawl.

### Screenshots

![imagen](https://user-images.githubusercontent.com/43771067/155482055-ab301347-19ca-4581-a700-b0d3ec26ae4b.png)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 6ca3ef2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Mythical Martial Arts [MMA],
    No Rail Stations [No_Rail_Stations],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    No Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
    Magiclysm No Class Limit [magiclysm_no_class_limit]
]

**Comment by Zireael07** [comment]
Wiring is known to have a performance cost, unfortunately.

**Comment by LeahLuong** [comment]
If it's a rural house, you may have a method of shortening the circuit by relocating the solar car. I believe if there are fewer links in the chain, it'll run smoother.

It may be some time before the coding for this part of the game is optimized or improved beyond what it is now.

**Comment by AcidAntOnAMinefield** [comment]
I have noticed that even walking, running or driving a vehicle (even with auto-drive) the game seems much slower than it was about a month or so ago. Unsure if it is due to this new Power Grid addition being too heavy on the game or if there's something else. Installed a clean version, changed to Catapult launcher for proper updating to rule out any potential issue related to the old launcher, but nope. Still the same.

**Comment by Knut-Aage-Hofseth** [comment]
I looked a bit at this behaviour in game.

Test case:
Expose wiring in several wall tiles.
Connect the wires back and forth and excessive amount of times. (10 wall wires, at least 4 connections each)

Result:
Speed up during waiting slows to a crawl. As in 5 IRL seconds per 5 in game minutes or even slower.

Addition:
Removing the wall wires by going through the examine menu and selection take down appliance on all of them speeds the game up again.
