### ISSUE TITLE
National Guard point cost balance

### ISSUE THREAD

**Issue by Grubleafeater** [CleverRaven/Cataclysm-DDA#55640]
### Is your feature request related to a problem? Please describe.

The National Guard start on crashed helicopter costs 3 points, has NO gear to speak of, and only has 2 skills at 2.

In contrast, Military Recruit starts you with 2 skills at 2, 5 at 1, an assault rifle, 2 spare mags, a combat knife, and full army gear. Also gunsmithing. For 4 points.

### Solution you would like.

The National Guard should probably cost 2 points, not 3....or get some proficiencies.

**Comment by a-chancey** [comment]
It's supposed to come with a go bag as well, which has a selection of decent gear when unpacked.
