### ISSUE TITLE
tortilla chips recipe lists oil as tool

### ISSUE THREAD

**Issue by martosss** [CleverRaven/Cataclysm-DDA#55642]
### Describe the bug

tortilla chips uses oil as ingredient and as tool

### Steps to reproduce

look at the recipe

### Expected behavior

Don't list oil as **tool** if it's also needed as a **component**.

### Screenshots

![image](https://user-images.githubusercontent.com/7064677/155576756-e86dbcc2-cb0e-492e-82ab-c8e03e1d78e2.png)

### Versions and configuration

Win 8.1, Stable 0.F-3, tiles, english, default mod + "@" soundtrack

**Comment by Shibimon** [comment]
Irl the lipid part (oils) are both in the dough and in the cooking surface, i don't see what's wrong in this recipe.
And you could make something like butter as ingredient and animal cooking oil for tool as roleplaying, resource management, or even vitamin micromanaging purposes.

**Comment by LeahLuong** [comment]
Have you tested this w/ exactly 2 oil on hand for crafting?? My guess is the recipe doesn't work then & having oil as a tool simulates being able to reclaim the excess not absorbed by the chips after cooking.

**Comment by martosss** [comment]
I haven't tested it with exactly 2 oil.
Why wouldn't it work?
And why would you claim any excess oil if there are no byproducts listed(such as cracklins when crafting lard)?

**Comment by oosyrag** [comment]
I'm going to hazard a guess that this represents the oil needed to fry something, but it's not added to the caloric value of the product, while the oil as a component is.

**Comment by LeahLuong** [comment]
For consistency's sake, the "tool oil" prob should be moved to "byproducts" & the component req for oil incremented to a reasonable value for cooking the given volume of tortilla chips. Of course, the relationship of 2 less "byproduct oil" than "component oil" should be preserved unless this is judged to be the incorrect amount. I believe the calorie calc was done for this volume of oil.

**Comment by LeahLuong** [comment]
3.75L of cooking oil = 240 units. No, I don't believe 0.0625L is enough oil to fry the given # of tortilla chips in the given amount of time. Cooking websites seem to indicate you need a cm or 2 of depth in a skillet to do this. This translates to 0.5-1L of oil in order to accomplish. So, 32-64 oil needed to start & you should get back 2 less once done, assuming 2 is actually the amount absorbed. I'm leary of making that assumption given what I've seen of how this recipe was authored.

**Comment by oosyrag** [comment]
So... remove tool oil!
