### ISSUE TITLE
update_mapgen is not rotating correctly

### ISSUE THREAD

**Issue by curstwist** [CleverRaven/Cataclysm-DDA#55645]
### Describe the bug

When update_mapgen is invoked (tested using the TCL), the map is not rotating to match the main map's orientation.

### Steps to reproduce

1. New world, tcl concourse start.  Any start will have the error, this is just convenient.
2. Make sure it didn't spawn in it's default orientation (Security OMT to the left/west).
3. Pass turns until the update_magen triggers.  If you pick up the lanyard, it won't trigger.
4. You may trigger a furniture overlay error because the update is placing the map at the wrong place, over furniture.
5. Look for the red floor marking which should be aligned to open walls that have bots behind them.

Make sure the TCL is in any rotation besides its default debug spawn layout to replicate the error.  Any North/South orientation for the concourse, or the one with the security tower to the east will have the error.

### Expected behavior

The layered maps should rotate with their main maps.

### Screenshots

N/S: note the red floors
![turned map sample](https://user-images.githubusercontent.com/39442864/155603259-397f2bd9-9b05-4537-91f3-ea10162f0c37.PNG)

E/W

![east-west not ok](https://user-images.githubusercontent.com/39442864/155604134-78329a46-e77d-4dc9-9e63-3be9965849d0.PNG)

W/E (working and default orientation)
![west-east ok](https://user-images.githubusercontent.com/39442864/155603385-f7cd2dad-58eb-4112-bca4-706d2ea19242.PNG)

This seems to effect all update mapgen.  Here is a sample using the bot triggered update:

![sample 2 with drone trigger](https://user-images.githubusercontent.com/39442864/155603468-1befa466-db46-47e5-b209-df6709685103.PNG)

I've heard reports that this effected other spawns but haven't tested them yet.  I think someone mentioned an NPC triggered update.

### Versions and configuration

Newest build, WIndows 10

### Additional context
@Ramza13 , maybe related to the new flag "NO_UNDERLYING_ROTATE" from #55538?

**Comment by haveric** [comment]
I can confirm as I ran into this issue when attempting to work on https://github.com/CleverRaven/Cataclysm-DDA/issues/33525 3 days ago.

**Comment by Ramza13** [comment]
Turns out this was my fault based on a misunderstanding of c++ constructor behavior.  I've added a fix to #55614
