### ISSUE TITLE
extra recipe for making a "blocked funnel" makeshift liquid container (idea)

### ISSUE THREAD

**Issue by pcdms-rygonia** [CleverRaven/Cataclysm-DDA#55652]
### Is your feature request related to a problem? Please describe.

hi this is not a problem, just a user expectation / suggestion.

a funnel has some uses, especially for being able to collect water when it rains, and storing it into another container...but not itself, via 1 recipe.

### Solution you would like.

to be able to craft a "blocked funnel", using the following in a recipe.:
1 Funnel
+
1 Lump of Clay

and the blocked_funnel would allow a player to temporarily store liquid, at least while the funnel is being held, or placed into the ground (but not when inside general inventory or pockets)

### Describe alternatives you have considered.

the rationale of this, is because sometimes when i wash a funnel in real life, i often block the bottom of it with my hand, to fill it up with water, (which works quite well), so that i can pour it around the sink later..... maybe in cdda, a player might need to carry some water somewhere and this way they at least can have a makeshift container for liquid :)

an alternative process could be to have a recipe, requiring rags + duct tape, but usually 1 clay can easily be found by digging, and i believe a wet/regular lump of clay (like plasticine) would be watertight.

### Additional context

(i was trying this in a test build of 0.F, using a custom debug of knowing all recipes, in case i missed a recipe for it, as well as using infinite carry/no pockets/no length limits, just to test some mechanics in the game)

Build number : # 11 002
Build version: 0.F-3
Major version: 0.F)

**Comment by LeahLuong** [comment]
While this proposal shows some ingenuity & may have some marginal utility in edge cases, I think it shouldn't be added to the game. The crafting screen is quite bloated w/ recipes as it is. By the time a char encounters a funnel, they've likely come across dozens of containers more suitable for the carrying of liquids that don't involve crafting @ all.

While the devs could add every single IRL thing & combination of things to this game given enough time & resources, @ some point it becomes less game & more encyclopedia.

**Comment by pcdms-rygonia** [comment]
ah thanks :)
im still new to the game, but can you imagine finding only a funnel near the start of a game....it could save a cdda life :)

**Comment by oosyrag** [comment]
I have difficulty imagining finding a funnel before another suitable liquid container, or the ability to carry water and not being able to boil it having any impact on survivability.

**Comment by pcdms-rygonia** [comment]
hi thanks very much elfleadermike for coding it, (how do i add it to my game btw, or does it need to be officially accepted into the code?
sorry if more veteran players feel it doesnt add much. (i saw a hide-recipe option which might help) but i will try and keep a spare funnel as a blocked funnel for those moments when suddenly a recipe has a liquid by-product, and i can use it temporarily.

**Comment by oosyrag** [comment]
You can copy the changes directly into your own game files. Go to the pull request and look in the changed files tab to see which files were changed and how.

Alternately, you can download the entire file(s) to replace yours with, by going to the development branch linked in the pull request. Use the link at the top of the PR that says ElfLeaderMike:blocked-funnel

**Comment by pcdms-rygonia** [comment]
ah thanks oosyrag :)

**Comment by pcdms-rygonia** [comment]
hi i copied the new code lines into my local game and it works great.
i can store water for example, and the blocked funnel can also hold some other loose items like a candle or credit card, which is great on several levels :)

**Comment by I-am-Erk** [comment]
we should just make all funnels open containers, and add a line to the description about how "you can block the funnel with just about anything, even your thumb, and use it to carry liquids in an emergency".
