### ISSUE TITLE
huge cpu lag experienced when player has lots of items and containers picking up certain objects

### ISSUE THREAD

**Issue by pcdms-rygonia** [CleverRaven/Cataclysm-DDA#55654]
### Describe the bug

this was originally posted on this page below:
https://github.com/CleverRaven/Cataclysm-DDA/issues/55631
(as it could be related, but just also creating here as a separate bug as requested, and with files/saves necessary to reproduce)

the bug itself, is that after a certain point, the game seems to be trying to calculate too much stuff, and potentially hanging /crashing the game for several seconds or minutes, but only during certain item pickups.... (process explorer showed the game on max cpu % trying to do 3million, 300million or 3billion calculations/iterations, just for picking up more than a few glass shards, rags or planks....but only after a certain amount of items were picked up.

basically, i wanted to try a game with all recipes unlocked, to test out how the game works (and to know what is already in the game so that some suggestions i posted werent already doable) :)

to allow me to pick up everything regardless of weight, volume size, or item length, i used the pockets universe debug mode, so that i had a 100000 volume/weight backpack, and tweaked Very strong back to allow for a large length size.

this worked great for about 50 in-game days, and there was no lag, but then something happened (maybe a threshold of items was reached, i have about 5500 items), and while most actions are lag-free (such as eating, recipe searching, moving ground items from left to right, walking, fighting, shooting, reloading etc, the lag happens when picking up certain objects in multiples, such as shards and rags. (but picking up 1 weapon for example, or 1 plank is not as bad).

### Steps to reproduce

extract the attachments using winrar to get the standalone folder of cdda. (this includes current world/saves/mods/code etc, but not any soundpacks)
+
load up   "world_name": "40ktest",   "character_name": "Sororitass"
+
just to the east of the car, there are some items on the ground, try to press g and pick them all up.
+ if you drop 1 fishing spear, and pick it up, within a second or 2, real time you pick it up, but if you deconstruct a window, or a bed, and try to pick up the items (such as several glass), or 30 rags, or even if you kill a zombie wearing clothes and try to pick up multiple clothing, the game will try to calculate millions and billions of things, freezing the game (for me) sometimes for 30 seconds to 5 minutes, and then everything works again, until that action is tried again.

### Expected behavior
(especially when using debug mode with pockets universe and a code tweak to strong back, the expected behaviour is to 
to pick up items without any noticable slowdown. (and regardless of weight/volume/length attributes). 

for example, the game would ideally simply "move" items you pick up, and put them into the fake (pocket universe) worn backpack.
but instead, it seems to be trying to "calculate" stuff. :o)

### Screenshots

i cant really show this in a screenshot, but might be able to make a vid clip, but it would only show a frozen screen. that is why i uploaded the game folder so that you can experience the exact same thing as me (hopefully) :)

### Versions and configuration

this is version 0.f-3 (with several mods in the mods folder, but only some are enabled), and i tweaked some settings for strong back, and tried to fix some seemingly unrelated mod warnings that some mods had (like multitile true tiles, or some item syntax) but as far as i can tell, those are not related to the issue, since the issue only seems to have happened later in the game when there are lots of containers and items).

### Additional context

(attached for you minus sound packs)

**Comment by pcdms-rygonia** [comment]
[cataclysmdda-0.F-Windows_x64-Tiles-0.F-3-40k_mods-mostlyfixed-4--sororitas.part01.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8138452/cataclysmdda-0.F-Windows_x64-Tiles-0.F-3-40k_mods-mostlyfixed-4--sororitas.part01.zip)

[cataclysmdda-0.F-Windows_x64-Tiles-0.F-3-40k_mods-mostlyfixed-4--sororitas.part03.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8138479/cataclysmdda-0.F-Windows_x64-Tiles-0.F-3-40k_mods-mostlyfixed-4--sororitas.part03.zip)
[cataclysmdda-0.F-Windows_x64-Tiles-0.F-3-40k_mods-mostlyfixed-4--sororitas.part02.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8138483/cataclysmdda-0.F-Windows_x64-Tiles-0.F-3-40k_mods-mostlyfixed-4--sororitas.part02.zip)
[cataclysmdda-0.F-Windows_x64-Tiles-0.F-3-40k_mods-mostlyfixed-4--sororitas.part06.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8138497/cataclysmdda-0.F-Windows_x64-Tiles-0.F-3-40k_mods-mostlyfixed-4--sororitas.part06.zip)
[cataclysmdda-0.F-Windows_x64-Tiles-0.F-3-40k_mods-mostlyfixed-4--sororitas.part07.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8138504/cataclysmdda-0.F-Windows_x64-Tiles-0.F-3-40k_mods-mostlyfixed-4--sororitas.part07.zip)
[cataclysmdda-0.F-Windows_x64-Tiles-0.F-3-40k_mods-mostlyfixed-4--sororitas.part08.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8138522/cataclysmdda-0.F-Windows_x64-Tiles-0.F-3-40k_mods-mostlyfixed-4--sororitas.part08.zip)
 
[cataclysmdda-0.F-Windows_x64-Tiles-0.F-3-40k_mods-mostlyfixed-4--sororitas.part09.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8138533/cataclysmdda-0.F-Windows_x64-Tiles-0.F-3-40k_mods-mostlyfixed-4--sororitas.part09.zip)
[cataclysmdda-0.F-Windows_x64-Tiles-0.F-3-40k_mods-mostlyfixed-4--sororitas.part04.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8138535/cataclysmdda-0.F-Windows_x64-Tiles-0.F-3-40k_mods-mostlyfixed-4--sororitas.part04.zip)
[cataclysmdda-0.F-Windows_x64-Tiles-0.F-3-40k_mods-mostlyfixed-4--sororitas.part05.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8138544/cataclysmdda-0.F-Windows_x64-Tiles-0.F-3-40k_mods-mostlyfixed-4--sororitas.part05.zip)

**Comment by pcdms-rygonia** [comment]
my comments from the other github issue:

 i have been using 0.F-3 this month, to try and learn the game, so to get a feel for things i just wanted to play with the debug infinite pocket dimension option, (to basically ignore weight, length, and volume limits), just to focus on learning the base game mechanics. (possibly slightly cheaty i know but it was for science) :o)

however, after having an issue with my local test game (after about 50 days worth of picking up pretty much everything i could carry), i found a problem where even just picking up 2 or more planks/shards, or clothing with pockets, causes something like 3million to 3billion cpu cycles (maxed out).... and maybe it is due to the game, trying to iterate over and over, which nested item or which pocket to put 1 shard in and is related to this?

(i had also tweaked the pocket universe debug to the following)

{
"id": "debug_backpack",
"type": "ARMOR",
"name": { "str": "debug pocket universe" },
"description": "A pocket universe. Can store approximately 384 * 10^6 bugs.",
"weight": "1 g",
"volume": "1 L",
"price": 0,
"price_postapoc": 0,
"material": [ "cotton" ],
"symbol": "[",
"looks_like": "backpack",
"color": "yellow",
"encumbrance": 0,
"max_encumbrance": 0,
"pocket_data": [
{
"rigid": true,
"pocket_type": "CONTAINER",
"max_contains_volume": "100000 L",
"max_contains_weight": "100000 kg",
"moves": 1,
"max_item_length": "1 km"
}
],
"warmth": 0,
"material_thickness": 0,
"flags": [ "BELTED", "WATER_FRIENDLY", "TARDIS" ]
}

and the mutations file i had edited to this for last line in weight capacity modifier:

{
"type": "mutation",
"id": "STRONGBACK",
"name": { "str": "Strong Back" },
"points": 2,
"description": "You are capable of carrying far more than someone with similar strength could. Your maximum weight carried is increased by 35%.",
"starting_trait": true,
"valid": false,
"cancels": [ "BADBACK" ],
"weight_capacity_modifier": 100.35
},

**Comment by pcdms-rygonia** [comment]
for example, IF using debug mode, for the game to try to just pickup the items into the quickest (realtime) amount of time, instead of starting any more complex calculations about which place is more efficient?

(the debug backpack has about 5475 items currently)

**Comment by oosyrag** [comment]
Did you check if this happens on experimental?

There have been 6 months of more worth of changes since stable. Your issue may be already fixed.

**Comment by pcdms-rygonia** [comment]
ah hi oosyrag, 

i was just seeing this post which sounded like it might be the fix, but not sure:
https://github.com/CleverRaven/Cataclysm-DDA/pull/53953

have you got a link to the latest expermental i can try?
this is the version my game shows: (which i got earlier this month)

Platform     : Windows_x64
Graphics     : Tiles
Build number : # 1 1 0 0 2
Build version: 0.F-3
Major version: 0.F

**Comment by pcdms-rygonia** [comment]
i just found "cdda-windows-tiles-x64-msvc-2022-02-23-0614.zip" i can try that to see...

**Comment by Zireael07** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/53953 is a fix for an issue introduced in experimentals, which wasn't present in 0.F.

Your issue sounds like https://github.com/CleverRaven/Cataclysm-DDA/issues/41934 or https://github.com/CleverRaven/Cataclysm-DDA/issues/48937

**Comment by pcdms-rygonia** [comment]
hi i tried with the experimental (after frantically trying to apply fixes to mods json which the new version was refusing to load the save and finding more syntax warnings :) but the problem still seems to be there.

hi zireal07 thanks it could be related to that issue (although picking up multiple items loose or batch, did not have a problem near the start of the game, it was only after about 1-2 months that it started happening (by then i had more items and containers on me).

the basic notion of picking up several loose items taking up some more in-game time (seems ok, especially if certain items/tools/gloves can speed it up), but the amount of real time (cpu cycles) shouldnt take long... i think this is where the issues could be related, because it seems as though the game is trying to frantically run through several (million) iterations with max cpu cycles, for about 20 seconds, for just 2 loose rags... and a lot more for say 30 rags. :)

**Comment by pcdms-rygonia** [comment]
im just an amature :) but maybe someone can run my attached version with some kind of software stepping tool or something to actually see what steps the game is trying to do at those points in time ;)

**Comment by hungpham2411** [comment]
I'm also experiencing this performance issue. A thousand items in backpack causes actions like opening inventory take at least several seconds.

**Comment by akrieger** [comment]
@hungpham2411 please open a fresh issue, the code changes so much a 4 year old issue is unlikely to have any relevance.

**Comment by kevingranade** [comment]
Also if your only method for triggering the issue is using debug items it's not really a valid issue, we would need it to be reproduced without the debug features.
