### ISSUE TITLE
"soap_holder" to have material and give some soap flakes (idea)

### ISSUE THREAD

**Issue by pcdms-rygonia** [CleverRaven/Cataclysm-DDA#55651]
### Is your feature request related to a problem? Please describe.

hi this is not a problem, just a user expectation / suggestion.

a soap dish appears to not be usable, but it would be good it if had a material attribute, and a chance to obtain a few soap flakes.

### Solution you would like.

to be able to disassemble / butcher the soap dish, so that it returns the following:
1 plastic chunk
+
3 soap flakes.

### Describe alternatives you have considered.

the rationale of this, is because when i looked at my own soap dish, it had some dry soap stuck to the sides, which would in theory yield a few soap shards :)

an alternative process could be to have a recipe, requiring a Tool with Chiselling 1 (but that might be overkill, and a simple "butcher soap dish" might be ok :)

### Additional context

(i was trying this in a test build of 0.F, using a custom debug of knowing all recipes, in case i missed a recipe for it, as well as using infinite carry/no pockets/no length limits, just to test some mechanics in the game)

Build number : # 11 002
Build version: 0.F-3
Major version: 0.F)

**Comment by pcdms-rygonia** [comment]
here is a screenshot example of the soap dish in game.
![cdda-suggs-0 F_modded--soap_dish-to_also_get_2_soap_flakes](https://user-images.githubusercontent.com/5255017/155636859-f70b2894-9700-43ce-9219-ca7316825dc7.png)

**Comment by pcdms-rygonia** [comment]
hehe, yeah thats a good idea for randomised version (1 regular soap dish, and 1 with flakes) :)

**Comment by schoolcf** [comment]
could make it a container that sometimes holds soap in it

**Comment by pcdms-rygonia** [comment]
ah i never thought of that, i dont mind :)

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
