### ISSUE TITLE
Off-hand use, two handed weapons, etc

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#55660]
### Is your feature request related to a problem? Please describe.

Recent attack vectors update using limbs for attacks has got me thinking again about how you hold and operate weapons and tools. I believe this would be a reasonable step forward and open many options for how people can play and interact with the world.

### Solution you would like.

Ability to use individual hands. This would allow many new abilities like:
- "dual wielding" weapons (character could be set to use a certain hand preferentially but use secondary hand when needed and switch quickly) 
- Switching items between hands.  This would take some (small) time, but much less than grabbing from a bag or even off of the ground.
- Flashlights could be held alongside a weapon and changed to require wielding to efficiently cast light. (a light inside your bag shouldn't really do much). Maybe casting a directed illumination when wielded. 
- When main hand is broken, crippled, etc, other hand will need to be used to wield.
- Some larger weapons can only be used two handed, and most weapons are more effective if used with both hands (club, sword, pipe, etc.
- Ability to pick up and carry items in free hand (fire extinguisher, gallon jug, etc). Possibly able to grab and drag medium weight items with one hand (chair), but need both hands for heavier object (fridge).

### Additional context

Extra thought on the flashlights and illumination. We could possibly implement an orientation for where the character faces, being the direction last moved in/ attacked or turned towards. Pressing any direction other than the one you are facing would initially change your orientation with little time passing (though it should probably cost about the same as one movement turn). Pressing the direction you are facing in would move your character normally. Or assign separate keys for movement and turning/orientation but that could get complicated. i am unsure this could be implemented in curses, however.

The direction you are attacked from then could greatly affect how you can react.

**Comment by Zireael07** [comment]
I think this proposal is more like the immediate next FAQ entry, "holding something in off hand"

**Comment by bananapheasant** [comment]
Thank you. I understand dual-wielding as a combat technique is not efficient or wise. That isn't my main concern here at all. I wasn't even proposing that you fire/use multiple weapons simultaneously.

I see that the entry for holding something in your off-hand was a feature discussed and planned perhaps. That is much more in line with what i envisioned.

**Comment by bananapheasant** [comment]
I do think this could open the possibility for some specific martial arts to use dual wielded daggers for some techniques perhaps. It would lay the groundwork for mods to take greater usage of the off-hand options not in vanilla.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
