### ISSUE TITLE
Find a small typo when read through RP#55233's code that merged yesterday

### ISSUE THREAD

**Issue by Naadn** [CleverRaven/Cataclysm-DDA#55691]
### Describe the bug

RP#55233 have merged yesterday and when I read through codes to understand how the new mechanism work, I have notice a small typo. More specific is magiclysm's Black Dragon Metamorphosis effect's description got replaced with mi-go mutagen.

### Steps to reproduce

1. Open https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/mods/Magiclysm/effects/effects.json
2. Search mutagen_black_dragon
3. Look at the third line of its desc 

### Expected behavior

It should write as "You consumed a life-changing amount of black dragon mutagen."

### Screenshots

![image](https://user-images.githubusercontent.com/97841551/155838336-9ceefeba-81c8-465e-8c54-9d6d68d97fbb.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.527 (21H2)
- Game Version: d9840e8 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Stats Through Kills [stats_through_kills],
    Bionic Slots [cbm_slots],
    Bionic Professions [package_bionic_professions],
    C.R.I.T Expansion Mod [crt_expansion],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Extra Mutated Scenarios [extra_mut_scens],
    Mythical Martial Arts [MMA],
    No Rail Stations [No_Rail_Stations],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm]
]

**Comment by MylieDaniels** [comment]
Whoops, thanks for noticing this!  I'll be fully honest, for mod categories I only handwrote Mi-Go and then copy-paste-replaced for the other categories, as I play modless and was wanting the mod authors to have a chance to flavor their mutagen effects better than I could.
