### ISSUE TITLE
Artifact speed is *way* OP for already fast characters.

### ISSUE THREAD

**Issue by tempestnano** [CleverRaven/Cataclysm-DDA#55699]
### Describe the bug

My character, fleet footed and wearing rollerblades has a normal walking (rollerblading) speed on roads of 44. I just acquired an artifact  that:

[ { "has": "WIELD", "condition": "ALWAYS", "modified_bodyparts": [  ], "mutations": [  ], "values": [ { "value": "MOVE_COST", "add": -39 } ] } ]

This changes my walk speed to 7 (56 miles per hour). My run speed goes as low as 3 (113 miles per hour). 

When I add the roadrunner mutation, I hit speed zero when walking. Infinite speed!

### Steps to reproduce

Make a player with fleet footed, add rollerblades, and then generate artifacts until you get one that offers ludicrous speed.

### Expected behavior

I would expect artifacts to be multiplicative instead of additive, so they would increase/decrease speed by a fraction of the current speed.

### Screenshots

With just fleet footed:
![unknown](https://user-images.githubusercontent.com/7892308/155849794-11e30780-d66a-42a5-94d2-b5759e882754.png)
With roadrunner:
![image](https://user-images.githubusercontent.com/7892308/155849937-91d1a585-0ce9-4580-bed9-179a6c308287.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1348 (21H1)
- Game Version: 6cea46d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Hope [no_hope],
    Bionic Slots [cbm_slots]
]

### Additional context

Alternatively, we could add red/blue shifting mechanics.

**Comment by oosyrag** [comment]
Alternatively, the earth implodes upon taking a step with 0 move cost as you apply enough force to surpass the speed of light.
