### ISSUE TITLE
Commit d6f5cff566213 makes it impossible to mutate

### ISSUE THREAD

**Issue by seerdecker** [CleverRaven/Cataclysm-DDA#55700]
### Describe the bug

character::mutate() is not called anywhere when you take mutagens. You cannot mutate.

### Steps to reproduce

Take mutagens. Nothing will happen.

### Expected behavior

Mutate.

### Versions and configuration

Commit d6f5cff566213 

### Additional context

Revert the patch.

**Comment by seerdecker** [comment]
Yeah. You're going to wait a long time indeed.

**Comment by seerdecker** [comment]
The thing is that is supposed to trigger the mutation change isn't triggering anything, c.f.
```
"type": "effect_on_condition",
    "id": "changing_mutate",
    "//": "Time for mutation!",
    "recurrence": [ "1 h", "6 h" ],
    "condition": { "and": [ { "u_has_flag": "CHANGING" } ] },
    "deactivate_condition": { "not": { "u_has_flag": "CHANGING" } },
    "effect": [
      {
        "run_eocs": [
          {
            "id": "changing_mutate2",
            "//": "Mutate!",
            "condition": { "compare_int": [ { "u_val": "vitamin", "name": "mutagen" }, ">=", { "const": 300 } ] },
            "effect": [
              { "u_message": "You feel a deep, churning sensation fill your body.", "type": "mixed" },
              { "u_mutate": 0 },
              { "arithmetic": [ { "u_val": "vitamin", "name": "mutagen" }, "-=", { "const": 60 } ] },
              { "arithmetic": [ { "u_val": "vitamin", "name": "mutagen" }, "-=", { "rand": 80 } ] }
            ],
            "false_effect": [ { "run_eocs": [ "changing_reqs_not_met" ] } ]
          }
        ]
```

**Comment by MylieDaniels** [comment]
Hi, I'm the commit author!  Don't worry, **{ "u_mutate": 0 }** calls Character::mutate() in non-legacy mode and causes you to mutate.  It seems to be line 16 of the excerpt you have posted.

**Comment by seerdecker** [comment]
```
git grep -i "u_mutate"
data/json/mutations/changing_eocs.json:      { "u_mutate": 0 }
data/json/mutations/changing_eocs.json:              { "u_mutate": 0 },
doc/NPCs.md:`u_mutate`, `npc_mutate`: `chance_int`, *optional* `use_vitamins: vitamin_bool` | Your character or the NPC will attempt to mutate, with a one in `chance_int` chance of using the highest category, with 0 never using the highest category, requiring vitamins if `vitamin_bool` is true(defaults true)
doc/NPCs.md:`u_mutate_category`, `npc_mutate_category`: `category_str`, *optional* `use_vitamins: vitamin_bool` | Your character or the NPC will attempt to mutate in the category `category_str`, requiring vitamins if `vitamin_bool` is true(defaults true)
src/npctalk.cpp:    } else if( jo.has_member( "u_mutate" ) ) {
src/npctalk.cpp:        subeffect_fun.set_mutate( jo, "u_mutate" );
src/npctalk.cpp:    } else if( jo.has_member( "u_mutate_category" ) ) {
src/npctalk.cpp:        subeffect_fun.set_mutate_category( jo, "u_mutate_category" );
```

u_mutate is not linked to anything AFAICT.

I also tested the code. I woke up in a lab, took the rabit primer, tried to sleep for 16 hours, nothing happened.

**Comment by MylieDaniels** [comment]
In line 7 of the excerpt you just posted, the function set_mutate, which interprets arguments and then calls Character::mutate(), is called!  And that's correct, as primers will not mutate you alone!  That's why they are called **primers** now.

**Comment by seerdecker** [comment]
OK, one note. Vitamins + mutagens triggering through something called 'npctalk.cpp' is not the best code organization.

And yes, it's not clear at all what you need to do, despite having spent 1 hours reading the code.

**Comment by MylieDaniels** [comment]
I'm sorry, but EOCs universally work through npctalk.cpp, condition.cpp, and dialogue.h, to avoid duplicated code.
I advise that instead of reading the code, you begin by reading the detailed writeup that explains precisely how it works and how it, which should be accessible via the commit in question.
In addition, try reading the item descriptions - they have changed as well as the item names.

**Comment by seerdecker** [comment]
Alright, I read the PR description, and I figured out the system, mostly.

The item description says this: "A processed mutagenic primer as white as a full moon.  You need a syringe to inject it and prime your body for mutation."

I.e. the description essentially says, "inject this and you'll start to mutate". The mechanics are obscure for anyone not a code diver. How do you expect people to figure out the interactions between 2 different sets of vitamins, with unobservable thresholds, where not having enough of one set prevents getting the desired mutations and having too much being dangerous?

**Comment by seerdecker** [comment]
In its current form, I don't see how this change adds to the game. It adds complexity and it encourages the player to read the code to figure out how to mutate correctly. What's the point? It doesn't have to be more complicated than "you inject mutagen of a category and then you mutate toward it". I suppose you could make it take more time for the mutation effect to trigger to make the process more realistic. For the rest, the change makes the game more tedious and less enjoyable to me.

**Comment by MylieDaniels** [comment]
I'm very sorry you feel that way, and hope that time will change your mind.  However, change is working as intended, and this issue is not about your opinion of the change - the issue incorrectly states that an undesired effect and/or bug has occurred, which has been proven and acknowledged to be untrue.  

Requesting this issue be closed.

**Comment by seerdecker** [comment]
Sure, closing.
