### ISSUE TITLE
After cutting plastic sheet gives more than takes to craft

### ISSUE THREAD

**Issue by Kavot** [CleverRaven/Cataclysm-DDA#55704]
### Describe the bug

Sorry, i play russian version so I can missname entities

New plastic sheet (жёсткий пластиковый лист) requires 200 plastic pieces (кусок пластика) for crafting. After cutting it gives me 294 plastic pieces back. This makes no sense.

### Steps to reproduce

1. Craft a hard plastic sheet (
2. Put it under your feet and use "B" to cut it
3. You get around 290 pieces of plastic back

### Expected behavior

I expect to get less plastic then i used for crafting.

### Versions and configuration

Sorry i didnt understand how to do it.
OS - Windows 7
Game version 0.F-3

**Comment by PatrikLundell** [comment]
The easiest way to get the Version and Configuration info is to escape to get the game menu, select the Debug Menu option (at the end, I think), info, and then "generate game report". This copies the info to the clipboard, and you can then paste it into the bug report (ctrl-v, using the "normal" latin key association).

**Comment by haveric** [comment]
Tested on experimental and am unable to replicate this:
- OS: Windows
    - OS Version: 10.0.19044.1586 (21H2)
- Game Version: 0.F-7045-gd1776b24fe [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

The item referenced is the `rigid plastic sheet`. Spawned a bunch in and Butchered them with a combat knife and butchering kit. Results seem to be between 188-200:
![image](https://user-images.githubusercontent.com/985060/160242648-7a499e2b-1a0e-4391-9ee4-335eb99e9caa.png)

Setting all skills to 10 gives more, but never above 200:
![image](https://user-images.githubusercontent.com/985060/160242680-92bc6d86-9206-432a-866d-19fa0cc6a4e9.png)

Can confirm that this _WAS_ broken on 0.F-3 (Tested with a butchering kit)
- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

![image](https://user-images.githubusercontent.com/985060/160243084-403fc5a9-d157-4f11-952b-0364398aaacd.png)

@Maleclypse I think this can be confirmed/closed as already fixed.
