### ISSUE TITLE
Practicing computers (advanced) causes an error for being 0 volume

### ISSUE THREAD

**Issue by catdach** [CleverRaven/Cataclysm-DDA#55703]
### Describe the bug

Practicing computers (advanced),(and possibly other 0 volume practice crafts) causes an error.

### Steps to reproduce

1. try to make the practice craft for computers (advanced/intermediate)
2. error pops up

### Expected behavior

no error's occuring

### Screenshots

![image](https://user-images.githubusercontent.com/93795131/155855012-37ae4c45-12b0-4aa6-afbe-40737df2b45b.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1526 (21H1)
- Game Version: 6cea46d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Magiclysm [magiclysm],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    C.R.I.T Expansion Mod [crt_expansion],
    Blaze Industries [blazeindustries]
]

### Additional context

Also happens with computers (intermediate), possibly happens with all 0 volume practice crafts I haven't tried any others yet? The crafting continues as normal, the error popup is just annoying.

**Comment by LeahLuong** [comment]
Back in #52532, I said:

> But don't you want your world populated by physical manifestations of your unfulfilled commitments, just like real life??

This issue may also be related to #53729, #52625, & #51567, if not a dupe of 1 of them. It's hard to tell given the sparsity of info given in "Steps to reproduce".

**Comment by catdach** [comment]
sorry, I think it's a dup of #51567
