### ISSUE TITLE
Portal storm teleported me 200+ map tiles

### ISSUE THREAD

**Issue by venum4k** [CleverRaven/Cataclysm-DDA#55712]
### Describe the bug

I was in my mobile base vehicle thing making some lye when a portal storm hit, I decided to carry on crafting because so far in this playthrough my vehicle's been reliably safe from portal storm monsters and effects when the doors are all shut. A few increments after pressing ignore the portal storm teleports me about 220 tiles across the map to a light industry area I'd spent about a week at previously. I decided to play it out, taking shelter in the nearby building and waiting for the storm to disappear. After that I started walking back, found a car on the way and drove the rest of the distance. As soon as I step inside my vehicle again I get sent 220 tiles to the same light industry area, in the same tile I waited out the storm in with the message "you feel as if you just rewound a few seconds". This is somewhat disruptive to the playthrough and seems like an unintended behaviour from the storm. After writing this up I did some testing, if I teleport back to my vehicle after being teleported back and let the time-rewind happen a few times and make sure the portal storm creature has disappeared then it clears itself up. I'm aware that my save is a bit heavy with some mods that aren't exactly up-to-date but I wouldn't have thought they would affect portal storm effects.

### Steps to reproduce

1. Head to the "SWAT Van" marked on the map
2. Walk inside
3. Get teleported pretty far

### Expected behavior

I expected that the storm might do some minor teleportation and after it ended the effects would stop because portal storms are supposed to be self-contained incidents that don't repeat the exact same effect when you go to a certain spot.

### Screenshots

![image](https://user-images.githubusercontent.com/1928247/155865679-4d569fc1-0f3d-4edb-b48d-e78ab8d42fcf.png)
![image](https://user-images.githubusercontent.com/1928247/155865683-a3fdbc55-0db6-4736-a9d4-85ab44b1f4bc.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1526 (21H1)
- Game Version: bedfc51 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Mythical Martial Arts [MMA],
    Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    DinoMod - UndeadPeople Tileset [DinoModUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    My Sweet Cataclysm - UndeadPeople Tileset [My_Sweet_CataclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

[Bee Branch 27.02.2022 bug save1.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8147879/Bee.Branch.27.02.2022.bug.save1.zip)
Sorry about the nested zip file, git wouldn't accept the zip's size so I made a 7zip and used zip as a container

**Comment by LeahLuong** [comment]
It looks like is the culprit #53563. I believe you _should've_ been safe in your vehicle & the effect ended w/ the storm.

**Comment by Ramza13** [comment]
> It looks like is the culprit #53563. I believe you _should've_ been safe in your vehicle & the effect ended w/ the storm.

Actually that PR is unrelated.  The teleport effect can be caused by either absence attacks or randomly even while indoors.  

The issue here is that the absence is attacking either an NPC or another monster.  The code to queue EOCs wasn't handling the situation correctly.  I'll have a fix up shortly.
