### ISSUE TITLE
Tab does not show up at description-mobile issue

### ISSUE THREAD

**Issue by CDDA32** [CleverRaven/Cataclysm-DDA#55714]
### Describe the bug

The bug is that when trying to complete the character creator and get into the world the tab button will not show up at description

### Steps to reproduce

1. Go to custom character from main menu
2. Complete character customization until description of character

### Expected behavior

I expected that the tab button would show up

### Screenshots

![Screenshot_20220226-194814_6fe8938556442e3d4f710ab4f9a16601](https://user-images.githubusercontent.com/87286880/155867414-83666de7-61ef-4bf1-acf1-b195e64cf386.jpg)

### Versions and configuration

- os OxygenOS 10.5 
- game version bedfc51
- graphics version tiles 
- ingame language English
- mods loaded dark days ahead
disable NPC needs
no fungal growth
bionic professions

**Comment by oosyrag** [comment]
Duplicate #55563, candidate for release blocker? If that's a thing that's still under consideration at the moment.

**Comment by CDDA32** [comment]
> Duplicate #55563, candidate for release blocker? If that's a thing that's still under consideration at the moment.

Yeah feels like hotkeys are just messed up on mobile

**Comment by LeahLuong** [comment]
@oosyrag Aren't you able to close issues?? Dupe issues usually are in favor of the original once linked. Also, this should prob have the dupe tag.

**Comment by oosyrag** [comment]
I can, but this one was clearer and as a newer contributor I'm not comfortable unilaterally closing issues, so I'll leave that for more veteran team members for now. Also I started tagging from newest first so didn't go back far enough to tag the other one.
