### ISSUE TITLE
can half build staircases indoors

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#55713]
### Describe the bug

you can build the first phase of a wooden staircase indoors, but are stopped from finishing it due to there being a roof above it.

### Steps to reproduce

try building a wooden staircase indoors

### Expected behavior

you either can completely build a staircase indoors or you can't even start construction of the first phase. Not you can build the first half then are abruptly stopped.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 372311f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Hope [no_hope],
    C.R.I.T Expansion Mod [crt_expansion],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    Stats Through Skills [StatsThroughSkills],
    Bionic Slots [cbm_slots]
]

### Additional context

making this worse is that the game provides zero feedback as to why you can't finish the staircase, If you have just enough materials for the second phase but not planks to repeat the first. the "Build Wooden Staircase" is lit up indicating you can build something in it, the Requires for a "half-built wooden stairs" is green indicating its acceptable its just that the game won't let you select the tile. I can image this stumping other players who made a base out of a prebuilt building like a cabin and wanted a safer way to the roof then climbing the drainpipe. the ability to half build the stairs indoors is a massive red herring.

**Comment by LeahLuong** [comment]
This seems realistic. 1 _would_ have difficulty completing a staircase when obstructed by a ceiling. That said, players _should_ get feedback for why it's unable to be completed. Have you tried removing the blocking roof in order to complete construction??

**Comment by robotic-gamer** [comment]
I am unsure how to remove the blocking roof as there does not seem to be a "remove roof" construction task, smashing requires a good bashing tool and can cause collateral damage (not something you want to do to your base) my current method for dealing with it is smashing a window which tends to remove the roof above the window then building the stairs there. Lastly I wall in the staircase to make it indoors and repair any collateral damage from smashing the roof

**Comment by martosss** [comment]
You can climb on the roof and "dig basement"(or whatever it's called) to remove the roof?

**Comment by anechoic525** [comment]
I had the same issue constructing a staircase inside of an existing building.  There needs to be a 'remove wood ceiling' construction option or the ability to smash a wood floor when standing next to it.
