### ISSUE TITLE
Automatic Issue Triage Bot

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#55729]
### Is your feature request related to a problem? Please describe.

We have dozens of new issues and PRs every week.  Triaging all these items is a multi person effort and can often get days behind. 
I believe that we have enough issue history that an automatic issue triage bot would work.

### Solution you would like.

I found this "build your own issue triager" post https://github.blog/2018-10-31-automating-issue-triage-with-github-and-recastai/

I'd planned to do it myself but it's been sitting on my to do list for a couple weeks.  

### Describe alternatives you have considered.

Not creating an issue about it.

**Comment by LeahLuong** [comment]
"Heh! As if robots will ever replace workers w/ high executive function anytime soon!"

-- famous last words

**Comment by casswedson** [comment]
We have a little of bit progress
![Screenshot from 2022-02-27 18-27-02](https://user-images.githubusercontent.com/58050969/155904560-5a87557c-cdc4-4c78-9095-a84e84ceb674.png)

**Comment by casswedson** [comment]
By the way, I am still looking for improvements regarding this side of the project management, a

**Comment by Maleclypse** [comment]
Would you like me to close this and create a project management issue or project?

**Comment by casswedson** [comment]
I think a wish list kinda deal as an issue would be good to have, we'll probably get a few maintainers to share what's on their to-do list
