### ISSUE TITLE
When beavers attack! Unusual aggressiveness

### ISSUE THREAD

**Issue by MisterFelixFox** [CleverRaven/Cataclysm-DDA#5573]
Beavers aren't aggressive animals and usually only attack a human if they feel trapped.

My character, who had *animal empathy*, had legions of beavers trying to maul him at every turn! I don't think that's correct.

**Comment by illi-kun** [comment]
I can't reproduce the bug in current ```master``` - 5 beavers spawned via debug show no aggression. I guess #12548 could be a fix for this issue.
