### ISSUE TITLE
Fampplow

### ISSUE THREAD

**Issue by LeahLuong** [CleverRaven/Cataclysm-DDA#55739]
### Describe the bug

Here's a lovely panoramic of my faction camp (AKA "famp") farm:

![Screenshot_20220227-145118](https://user-images.githubusercontent.com/91638992/155921626-39492352-7486-4695-bed5-869bae30c20f.png)

Note the missing rows where there's dirt. Here's a pic of my famp's farm expansion screen:

![Screenshot_20220227-145202](https://user-images.githubusercontent.com/91638992/155921890-0b8001da-8635-437d-b83d-83846f484f61.png)

Note the # of tiles to be plowed.

### Steps to reproduce

1. Make the famp farm.
2. Harvest the famp farm.
3. ???
4. PROFIT!

### Expected behavior

I expected to be able to order my followers to plow the land in preparation for the next seeding after having them harvest.

### Versions and configuration

Android 0.F-3 Tiles English vanilla

### Additional context

Oats went from seed to maturity really fast. Does any crop grow faster?? Is it intended they grow in a couple of weeks or does this warrant another bug report??

**Comment by LeahLuong** [comment]
This may be related to #50982. I can't remember if I manually planted the crops or ordered a follower to do it. Prob the former & that's why the furrows reverted. That may explain why the expansion doesn't recognize them.

**Comment by robotic-gamer** [comment]
different crops do grow at different speeds, I believe wheat grows extra slow and I guess oat grows faster then average

**Comment by LeahLuong** [comment]
I manually tilled the reverted tiles w/ an entrenching tool & was able to replant using the farm expansion screen. Hopefully, those oats (of course!) mature before it gets too cold & I get to see what happens in the next harvest.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
