### ISSUE TITLE
It appears root beer doesn't restore any thirst

### ISSUE THREAD

**Issue by YouFokinWotM8** [CleverRaven/Cataclysm-DDA#55732]
### Describe the bug

Drinking root beer will provide hunger nourishment, but not thirst.

### Steps to reproduce

Chug root beer.

### Expected behavior

Drinking any food related liquid should get rid of some of your thirst.

### Versions and configuration

Most recent experimental version as of 2/27/2022.

**Comment by oosyrag** [comment]
Unable to reproduce. New game, debug set 50 thirst, spawn/drink root beer, wait 5 minutes, thirst at 33.
build type: windows-tiles-x64
build number: 2022-02-27-1338

Try drinking more, or waiting a bit to process the liquid in your stomach. Note that root beer is only -18 thirst as opposed to water's -50 per drink.
