### ISSUE TITLE
Remove Primitive rock drill

### ISSUE THREAD

**Issue by Anybodydeadyet** [CleverRaven/Cataclysm-DDA#55744]
### Is your feature request related to a problem? Please describe.

It appears that the primitive rock drill and it's qualities "rock drilling 1" have no purpose in the current game. They can't be used to craft anything nor be used to interact with the environment. Googling it brings up no results on how to use it or it's effects.

### Solution you would like.

Simple remove it from the game or hide it from the crafting options available. 

### Describe alternatives you have considered.

Give it a function, perhaps in some of the stone tools?

**Comment by Kamejeir** [comment]
https://nornagon.github.io/cdda-guide/#/tool_quality/DRILL_ROCK

**Comment by Anybodydeadyet** [comment]
Oh my I missed those thank you.

**Comment by WilliamWasNeverHere** [comment]
The knife spear requires "drilling 1" but the primitive rock drill isn't counting towards the quality for some reason, despite the description saying it has the drilling 1 quality
