### ISSUE TITLE
Multiplayer, through...time travel?

### ISSUE THREAD

**Issue by ikrarkjr** [CleverRaven/Cataclysm-DDA#55749]
### Is your feature request related to a problem? Please describe.

Below is my idea as to how multiplayer can be implemented, in a way that makes sense. Not code-wise, but logic-wise. The most straightforward initial idea of translating normal CDDA to multiplayer, would be having each player take their turn like chess, but no one would play that. And I'm sure if you're reading this you probably have thought/seen other ways before, but nothing really _works_. I believe I have solved the problem in _**theory**_, but obviously not practice. 
This person ->https://github.com/stolencatkarma/CataclysmLD<- Has a sort of multiplayer. However upon looking further, from how they describe it, it seems it is impossible for players to be nearby eachother. This is a deal breaker for me, and I figured I could improve it. Maybe by a lot.

### Solution you would like.

The game already has a set time for each character(player), in the second-minute-hour-day-season-year. Now, you have all actions of all players logged, for each time(turn).
Example of multiplayer: Three players in one world
Player 1 is at 2 days in.
Player 2 is at 1 day in.
Player 3 has yet to start.
Player 1, the first to travel forward in the timespan (Day 2), sees no other players. And it's ALMOST like being singleplayer. (I will get back to this).
Player 2 enters the timespan player 1 was in, and sees player 1's actions and the world's reactions to player 1. Essentially think of it like time travel, all of player 1's actions and the outcomes WILL happen, regardless of player 2's actions.
-In the case of stuff built (Player 2 tries to create a table in the past where player 1 has already made a wall in the future) since Player 1 already consumed resources, Player 2 simply has their action cancelled and told they cannot do that.
-In the case of enemies, since player 1 will already have taken damage(or could've), consuming hp in the fight, it wouldn't make sense for player 2 to just be able to kill or move enemies before they reach their death by player 1. Solution for this: enemies will still attack player 2, however they will stay in the same area, to return back to the spot they are destined to fight player 1. Also they will be unkillable. (This is the better solution to them just being AFK and stupid, as you can just run away and not fight them, as they wont chase you). Any enemies that end up living, and get intervened by player 2 in the past, will have the health they had before fighting player 1 (full hp most likely), and can still be moved and even killed by player 2. While this doesn't exactly make sense, it is likely to be completely unnoticeable to player 1. (especially, given that there are many copies of the same exact enemy).

Player 3 would then see player 2 how player 2 saw player 1. But also see player 1 as well. So player 3 would see two 'NPC' players going about, and player 3 can't change most of the things before they should happen, as destined in player 1 and player 2's games to occur.

FINALLY, back to player 1, they see everything AS IT IS DONE by player 2 and player 1, but player 1 does not see the characters of player 2 and 3. For example, if player 2 makes a chair, or kills an enemy, it will pop into existence, or pop dead, in player 1's game. This CAN potentially be a bit silly. While being in combat SHOULD disallow player 2 from killing the enemy, player 1 could be LOOKING at an enemy, and it suddenly just dies for (seemingly) no reason.

### Additional context

Thank you for reading this.

**Comment by ZhilkinSerg** [comment]
See https://github.com/CleverRaven/Cataclysm-DDA/wiki/Frequently-Made-Suggestions#Multiplayer

**Comment by ikrarkjr** [comment]
> See https://github.com/CleverRaven/Cataclysm-DDA/wiki/Frequently-Made-Suggestions#Multiplayer

The game loop of DDA includes a large number of activities that pass a large amount of time with no or minimal player input.
Some have proposed requiring coop mode, but that doesn't change the fact that there are huge number of scenarios where a player gets stuck with nothing to do for an extended amount of time.
**This is resolved with the system I stated**
This isn't just the obvious things like crafting and sleeping, but simply moving around tactically and examining the inventory and examining surroundings and menu interaction are not streamlined for short turn times. This has implications for every part of the game, and I am not interested in making those adjustments.
**This as well**
The synchronization issues go much deeper than you seem to think they do, and resolving them would require overhauling most of the core game code.
**This is unknown for me, but the only part that's valid here**
I'm not interested in dealing with the security issues inherent in multiplayer network support.
**There is another project for multiplayer, so the idea is just for anyone to create.**

>This will go out of sync faster then it took you to write this post.

I assume of course that you are right. If it would be anything like syncing for other games (For example, Rimworld's multiplayer mod, which is converting a singleplayer game to multiplayer and requires syncing) you could do daily (in game) syncing, instead. This would make things more janky, as for example you could end up with multiple players building someone in the same tile by accident.
Alternatively, you could have the most-time-advanced character be the host world that others sync to. Only the structures, as in walls, floors and furniture, would be shared between players. Items, mobs, etc, would be client side. All that would need to be synced was at what time structures were changed in the world, and have it follow my previous idea of disallowing building on tiles that change into something else in the future, or destroying structures. The host would accept only syncing of structures built by others. Of course, in this instance there should be some form of item trading between players, to which a good way would be to make items placed into a specific furniture like a chest (easy) or any kind of furniture from ovens to fridges (hard).

I feel like any issues could be ironed out, in _some_ way. Even in the gutted version as the last option I stated above, it would still definitely be fun, and I know several others who would love it.

**Comment by ProjectileWaterfowl** [comment]
You'd have to be constantly referencing many, many different copies of the save file to enforce the timeline on that last option. It'd also pretty much completely ruin AI interaction, as their paths would be set in time as long as one player has them in their reality bubble, meaning anyone else who interacts with them is effectively invincible, but so are they. Items would either be able to be duplicated or also have to be protected, meaning if they're in a player's reality bubble, anyone in the past up until that point would be unable to take it. You'd be better off with the chess version or the one where you don't make contact.

**Comment by LeahLuong** [comment]
This thread pretty much jumped the shark when time travel was introduced. As long as we're playing the game of repurposing the link Zhilk posted & showing our version of it, here's my entry:

> The synchronization issues go much deeper than you seem to think they do

Followed by:

> This is unknown for me, but the only part that's valid here

Makes for a delightful juxtaposition, don't you think??

**Comment by ZhilkinSerg** [comment]
We won't be adding any network code to CDDA.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
