### ISSUE TITLE
eating single corn cob eats whole stack

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#55741]
### Describe the bug

when you eat a corn cob raw straight from harvest the whole stack of corn cobs turn to empty corn cobs despite the fact you just ate once.

### Steps to reproduce

get a stack of corn cobs
eat it once
observe entire stack turns to empty corn cobs

### Expected behavior

eating once will generate one empty corn cob and remove one corn cob.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 372311f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Hope [no_hope],
    C.R.I.T Expansion Mod [crt_expansion],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    Stats Through Skills [StatsThroughSkills],
    Bionic Slots [cbm_slots]
]

### Additional context

its clear the implementation of what happens when you eat a corn cob is faulty ie its converting the entire stack rather then just a part of it.

**Comment by estebandellasilva** [comment]
Dublicate

https://github.com/CleverRaven/Cataclysm-DDA/issues/50002

https://github.com/CleverRaven/Cataclysm-DDA/issues/51533

I think someone mentioned it is caused by the fact that you get the cob - an effect no other food currently has

**Comment by robotic-gamer** [comment]
closing due to duplicate
