### ISSUE TITLE
It's possible to place a knife spear in a spear strap stored in a travelpack

### ISSUE THREAD

**Issue by RychuP** [CleverRaven/Cataclysm-DDA#55742]
### Describe the bug

As per title.

### Steps to reproduce

1. Place a spear strap in a backpack
2. Activate the spear strap and store a knife spear in it

### Expected behavior

Spear strap takes into account the size of a pocket it is stored in and rejects spears if they won't fit.

### Screenshots

![cdda](https://user-images.githubusercontent.com/60892050/155929239-bbd48df6-41e0-462a-96bf-0b26fee2cb16.png)

### Versions and configuration

0.F-3 Frank-3

**Comment by robotic-gamer** [comment]
perhaps containers in general should inherit the length of things contained within them if that length exceeds the containers length

**Comment by catdach** [comment]
> perhaps containers in general should inherit the length of things contained within them if that length exceeds the containers length

container's already do that, you can't place a spear strap with a spear in it into a backpack in any other way. usually when something like this happens the spear strap would automatically fall out of the backpack.
