### ISSUE TITLE
Critters leaving the cell when I leave

### ISSUE THREAD

**Issue by EkarusRyndren** [CleverRaven/Cataclysm-DDA#5575]
Can anyone confirm this? I thought this was fixed. It's also despawning critters on long-range debug TP.

I can confirm they're not just wandering off into the night, exploring a lab and the turrets left.

[g609d70a]
[Bug]
[Needs Confirmation]
##

**Comment by eliotcougar** [comment]
Can't reproduce in 0.C-19186-g23a9665 (tiles)
