### ISSUE TITLE
Have options to disable Portal Storm

### ISSUE THREAD

**Issue by CutenessOverloaded** [CleverRaven/Cataclysm-DDA#55768]
### Is your feature request related to a problem? Please describe.

First, if you have a farm without roof, they will kill all you animals. 
Second, It breaks all your schedule. 
Finally, I'm not fans of alien

Here my story, at the very beginning I already think it was a bad feature because it just breaks all my schedule and I also didn't understand why a portal storm is in a zombie apocalipse, it just doesn't make sense for me but at that point I'm not hating it yet.

But after I got my first horse I found the problem, I was very happy that day because I do think it is cool to have horses in the zombie apocalipse. I didn't have a horse stable built yet, so I left them outside my house because I don't think they like to stay inside after that I went to sleep. After I woke up, the portal storm was already there then I check my horses from the window and say "Good morning" to them, but I could only see their bodies. I was mad so I reload the save and I bring them to the zoo nearby hope it is safe there. The next day all the animals in the zoo dies.

### Solution you would like.

Have options to disable Portal Storm in the "world Defaults" and the "Current World" options or in the "Debug" options

### Describe alternatives you have considered.

Make a mod that disable Portal Storm like Disable NPC Needs

**Comment by oosyrag** [comment]
Per #52432, it is unlikely that the option to disable portal storms will be added to the game.

However,  that commit has the change you can add manually to your own game files to do so if you want.

**Comment by robotic-gamer** [comment]
Actually I would like the option to edit the chance of portal storms occurring in the world generator like loot spawn rate. That way people can change the frequency as they see fit. It would allow disabling it by setting the chance to 0. Or you can increase the difficulty by setting the chance to a higher percentage.

**Comment by CutenessOverloaded** [comment]
> ###

Ya, so now I just edit the data folder to let storm do nothing instead

**Comment by LeahLuong** [comment]
Although this isn't technically a dupe issue, the subject has come up several times before. Based on the comments in #52432 & the fact OP has resolved their issue, this thread should be closed.

@robotic-gamer I like the idea of a slider for storms & you should prob make a feature request for it. Having a default setting w/ storms on shows players how the game's meant to be played & most prob will play it that way. Those that don't won't be forced & players will have another tool for ratcheting up the difficulty if they so choose.

**Comment by ZhilkinSerg** [comment]
Everything is in JSON and is easily moddable. There is an example of the mod that messes with portal storm in https://github.com/CleverRaven/Cataclysm-DDA/pull/52432
