### ISSUE TITLE
Size-based scaling of body fat and hunger calculations

### ISSUE THREAD

**Issue by Plagueis-The-Wide** [CleverRaven/Cataclysm-DDA#55764]
### Is your feature request related to a problem? Please describe.

As of right now, the game's food systems, excluding that of calories burnt during activity, are based on flat values, requiring larger characters to be in an almost constant state of eating due to undersized stomachs, and unable to meaningfully store calories long-term without suffering penalties to their health. At the same time, smaller characters that are supposed to be penalized by the difficulty of feeding themselves (esp the Mouse, which is intended to suffer from a hyperactive metabolism to offset it's advantages).

### Solution you would like.

Scale the Healthy Body Fat/Stored Calories values and the size of the Stomach to the size or height of the player. This will achieve two things.

1: It will realistically reflect the larger mass and corresponding greater storage and processing capacity of larger creatures. This will benefit players starting with a greater height and/or those going down the large/huge mutation lines. Consider the behavior patterns of macropredators like the Polar Bear, Orca Whale, or similar, and how long they can last between meals.

2: It will on the other hand, penalize small/tiny mutation and similar builds that have as of right now, been getting a proverbial "free lunch", especially the sole advanced tiny threshold, Mouse, which is meant to be penalized by a constant need to feed, but due to having the same stomach size and stored bodyfat as a full-sized man, has effectively negated it's own downsides while continuing to enjoy the increased speed, omnivory, and stamina benefits.

**Comment by NetSysFire** [comment]
The current height property of characters you specify when creating a character is just cosmetic. I assume you are referring to the size mutations, like Crafty, Freakishly Huge and similar?

**Comment by Plagueis-The-Wide** [comment]
> The current height property of characters you specify when creating a character is just cosmetic. I assume you are referring to the size mutations, like Crafty, Freakishly Huge and similar?

Is it? I was under the impression height affected  stamina and kcal consumption from a reddit post. My mistake.

But yes, in that case, those.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
