### ISSUE TITLE
Monstergroups are not categories (No Fungal Monsters mod)

### ISSUE THREAD

**Issue by xuvatilavv** [CleverRaven/Cataclysm-DDA#55767]
### Describe the bug

The `No Fungal Monsters` mod is using this rule:
```json
  {
    "type": "MONSTER_BLACKLIST",
    "categories": [ "GROUP_FUNGI", "GROUP_FUNGI_TOWER", "GROUP_FUNGI_FLOWERS" ]
  },
```
These groups are from `data/json/monstergroups/`, which are not checked for monster whitelists and blacklists, and thus has no effect. The `categories` list in monster whitelists and blacklists only compares against the `categories` tag within the monster's definition.

### Steps to reproduce

To easily verify that `GROUP_*` is not used for blacklists:
1. Make a mod with a blacklist containing `GROUP_ZOMBIE`
2. Generate a world with the mod and join it with a random character
3. Observe that all kinds of monsters spawn, including members of `GROUP_ZOMBIE`

And the opposite, to confirm for whitelists:
1. Make a mod with an exclusive whitelist containing `GROUP_ZOMBIE`
2. Generate a world with the mod and join it with a random character
3. Observe that no monsters of any kind will spawn.

For convenience, the mods: [test_whitelist_blacklist_group.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8160153/test_whitelist_blacklist_group.zip)

### Expected behavior

No Fungal Monsters should either:
 - use `species`
 - have its own `categories` tag and add it to the relevant monster definitions
 - list all the monsters individually
 
If the `monsters` list is already all current fungal monsters, just remove the `categories` section here to be an accurate example for new mod devs.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1526 (21H2)
- Game Version: f8b23b8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Documentation inbound in #55711

**Comment by Maleclypse** [comment]
No Fungal Monsters is an obsoleted mod so I'm going to close this.  But we appreciate the documentation you are adding to make this more usable for modders.
