### ISSUE TITLE
Faraday chainmail suit not ELECTRIC_IMMUNE

### ISSUE THREAD

**Issue by Sathra225** [CleverRaven/Cataclysm-DDA#55778]
### Describe the bug

The normal and XL faraday chainmail suits don't protect against electricity anymore. The XS version does.
Seem to be missing flags.

### Steps to reproduce

1.Equip faraday chainmail suit.
2. Interact with electrical dischargers.
3. Pain.

### Expected behavior

Faraday chainmail suits would function as they did previously and as the description states.

### Versions and configuration

Current experimental.

**Comment by Kamejeir** [comment]
if you're normal-sized, then the gamer move appears to be to make an XS version and simply resize it for less weight overall
