### ISSUE TITLE
Items Sold/Consumed Through NPC dialogue should be first unloaded

### ISSUE THREAD

**Issue by bombasticSlacks** [CleverRaven/Cataclysm-DDA#55771]
### Is your feature request related to a problem? Please describe.

I'm working on lots of prototyping stuff for different NPC's

When you give an NPC something with a battery or items in it, they vanish which seems incorrect.

### Solution you would like.

Before consuming or selling an item you really should handle its contents.

### Describe alternatives you have considered.

Currently I just warn the player to remove all the contents before trading but this is definitely going to be frustrating for players. 

### Additional context

@Ramza13 want to know what you think.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
