### ISSUE TITLE
broken one overmap tile bridge

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#55779]
### Describe the bug

bridges can generation can apparently bug out resulting in what you see in the screenshot

### Steps to reproduce

repeatedly generate map until you get a one over map tile bridge, observe it is broken

### Expected behavior

not to generate in a nonsensical way

### Screenshots

![image](https://user-images.githubusercontent.com/78816055/156286851-52647667-0508-4ea1-bdc5-294042a8ffd0.png)
![image](https://user-images.githubusercontent.com/78816055/156288160-4bc3bbfb-0c32-42ce-ab61-2312f91de168.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 372311f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Hope [no_hope],
    C.R.I.T Expansion Mod [crt_expansion],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    Stats Through Skills [StatsThroughSkills],
    Bionic Slots [cbm_slots]
]

### Additional context

I have no idea what caused this. note the brown N note is my start location and this is a fresh world.

**Comment by LeahLuong** [comment]
Looks very similar to #22133. This seems relevant:

https://github.com/CleverRaven/Cataclysm-DDA/issues/46844#issuecomment-767230005

Please consider posting a link to your save to help w/ tracking this bug down.

**Comment by robotic-gamer** [comment]
closing as it is apparently a duplicate
