### ISSUE TITLE
Some contradictions among Profession / Background / Traits.

### ISSUE THREAD

**Issue by kwl01skz** [CleverRaven/Cataclysm-DDA#55770]
### Describe the bug

Sometimes we are allowed to choose the _traits_ that should not be selected.
Sometimes we are not allowed to cancel unwanted _traits_.

### Steps to reproduce

1, New Game - Custom Character
2, scenario : Helicopter Crash
3, profession :  National Guard
4, traits : Sleepy + Far-Sighted
5, reselect profession : Bionic Sniper ( Operation is allowed )
6, background: Video Gaming
7, cancel background:  Video Gaming ( "The trait [Less Sleep] conflicts with background [Video Gaming]'s trait [Less Sleep]." )

The key to the problem is that if we choose a _traits_, then go back to _background_ or _profession_ and  choose a contradiction with _traits_, these problems will occur.
This is not a problem caused by MOD.

### Expected behavior

step 5.
Telescopic Eyes(from Bionic Sniper) and Far-Sighted cannot coexist, so we should get a prompt "The following bionics prevent you from taking this trait: Telescopic Eyes." 

step 7.
Allowance to cancel background.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Linuxmint; Description: Linux Mint 20.2; Release: 20.2; Codename: uma; 
- Game Version: 0.F-6423-gf8b23b8fbb [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions]
]

**Comment by oosyrag** [comment]
Perhaps the simplest fix would be to make it so that any change to a prior tab resets all following tabs, similar to what happens when the scenario is changed.

**Comment by kwl01skz** [comment]
> ### 描述错误
> 有时我们可以选择不应该_选择的特征。_有时我们不允许取消不需要_的特征_。
> 
> ### 重现步骤
> 1、新游戏-自定义角色2、剧情：直升机坠毁3、职业：国民警卫队4、特质：困+远视 5、重选职业：仿生狙击手（允许操作） 6、背景：视频游戏 7、取消背景：视频游戏（“特质[睡眠不足]与背景[电子游戏]的特质[睡眠少]冲突。
> 
> 问题的关键在于，如果我们选择一个特质，然后回到_背景_或_职业_，选择与_特质_相矛盾，这些问题就会出现。这不是MOD引起的问题。
> 
> ### 预期行为
> 第5步。伸缩眼（来自仿生狙击手）和远视不能共存，所以我们应该得到提示“以下仿生学阻止你采取这种特征：伸缩眼。
> 
> 步骤 7.允许取消背景。
> 
> ### 截图
> _无响应_
> 
> ### 版本和配置
> * 操作系统： Linux
>   * 操作系统版本： 分发服务器 ID： Linuxmint;描述： Linux Mint 20.2;版本： 20.2;代号：乌玛;
> * 游戏版本： 0.F-6423-gf8b23b8fbb [64位]
> * 图形版本：磁贴
> * 游戏语言： 英语 [英文]
> * 加载的模组： [ 黑暗的日子 [dda]， 仿生职业 [package_bionic_professions]
>   ]
> 
> ### 其他上下文
> _无响应_
