### ISSUE TITLE
Option to use Grass Sheets for Door Curtains

### ISSUE THREAD

**Issue by Myfharad** [CleverRaven/Cataclysm-DDA#55789]
### Is your feature request related to a problem? Please describe.

So I've been playing a lot of Innawoods recently and because of the lack of metalworking tools and such I can't really make nails for doors when I'm building a little hut or shelter for my Character. This can also come at a detriment if Portal Storms aren't allowed to be turned off by the average cdda player or if Innawoods does not disable them, as there is no way to build a door to protect yourself during these storms. I have tried prone-ing around half-walls and Improvised Shelters, and Portal Storm enemies still find you regardless.

### Solution you would like.

I'd like for the item [Grass Sheet] to be allowed as a building material for Door Curtains rather than just [Sheet]s alone in the recipe.

### Describe alternatives you have considered.

I was thinking about dipping my hand in either making the feature accessible for myself or making a [Thatch Door] type construction build that would be like the primitive door for those playing a non-city survival playthrough or Innawoods player, but I do want other players (Innawoods or Primitive Survival Vanilla) to be able to feel like they didn't just build a home and now can't really build a door.

**Comment by Light-Wave** [comment]
There's a massive nerf to portal storms in the innawood mod incoming in #55644
But I also agree that grass sheets for door curtains would be great.
