### ISSUE TITLE
Isherwoods Prefer Archery

### ISSUE THREAD

**Issue by LeahLuong** [CleverRaven/Cataclysm-DDA#55780]
### Describe the bug

Most of the Isherwoods I've encountered are armed w/ a bow of some sort but have a gun @ their feet. Each gun has a "!" & I've not been tempted to steal them.

### Steps to reproduce

I imagine you simply find the family farm & 'V'iew items in their presence. So many of them are like this it can't be unique to my playthrough.

### Expected behavior

I expected a sensible storage method for loose firearms from a survivalist family like the Isherwoods. Maybe they're conserving their ammo but they're doing a piss-poor job of conserving their guns. 1 doesn't really work w/out the other.

### Versions and configuration

Android 0.F-3 Tiles English vanilla

**Comment by oosyrag** [comment]
Do you have more details regarding the specific way you would like to see this resolved?
It looks like they spawn with both the items, and decide to use one and drop the other. 
We could update the AI, have them spawn with only one or the other, add more secured guns to mapgen instead of on the npcs, ect...

**Comment by LeahLuong** [comment]
The Isherwood farm doesn't seem built-out enough to be a commercial endeavor; I get the sense the family was simply eking out a subsistence pre-Cataclysm. As such, they prob shouldn't have many guns, if any. If they're defaulting to bows, take the guns away; seems silly to give them both when they're only going to use 1. They may also need loaded quivers because having a bow w/ 1 arrow is only marginally more useful than a gun w/ 1 bullet.
