### ISSUE TITLE
option to set portal storm frequency

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#55783]
### Is your feature request related to a problem? Please describe.

I can conceive of several non-contrived reasons for players to want to change the frequency of portal storms. These include:
- increasing the difficulty by increasing portal storm frequency
- decreasing the difficulty by decreasing portal storm frequency
- disabling portal storms by setting the frequency to 0
- causing permeant portal storms by setting the frequency to a crazy high number

### Solution you would like.

the option to adjust the frequency in world gen like loot spawn frequency.

### Describe alternatives you have considered.

mods that change the frequency

### Additional context

this issue was prompted by comments in #55768

**Comment by oosyrag** [comment]
I think it is relatively more palatable. But options in general are often a pain as far as code goes.

**Comment by ZhilkinSerg** [comment]
Everything is in JSON and is easily moddable. There is an example of the mod that messes with portal storm in https://github.com/CleverRaven/Cataclysm-DDA/pull/52432
