### ISSUE TITLE
Can't take control of vehicle inside TCL

### ISSUE THREAD

**Issue by tinukedaya** [CleverRaven/Cataclysm-DDA#55799]
### Describe the bug

Driving in a vehicle inside the TCL the car crashes and I get slammed out of my seat for no obvious reason. I'm in the middle of "empty" space when this happens. 

In one case after I was slammed out of it I can't take control of my self-made buggy. I only have the option to turn on/off engine and control electronics, etc. although the seat/vehicle controls are fine (in general I just can't see anything wrong with the buggy).

Interesting thing (and not sure if it's relevant): in certain places I get to see enemies on my sidebar, but once I wait, or try to take screenshot, or "look around" they disappear and I can't actually see them anywhere.

Also at one place I do get this debug error, (again, not sure if it's relevant to the above issue).

 DEBUG    : Ran out of available textures in the pool.

 FUNCTION : SDL_Texture_Ptr pixel_minimap::shared_texture_pool::request_tex(size_t&)
 FILE     : src/pixel_minimap.cpp
 LINE     : 142
 VERSION  : f8b23b8

(and of course there is this insane LAG inside TCL, but that IS another issue)

### Steps to reproduce

Drive around the inside of the TCL I guess (not the parking lot outside the building).

### Expected behavior

I can drive around freely on empty road in the building and pick up my loot without being thrown out of the vehicle.

### Screenshots

![Ronni Magnusson _2022-03-03T12-16-38](https://user-images.githubusercontent.com/19891532/156558723-d844976d-3515-400d-a271-caf15ea64883.png)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: f8b23b8 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    No Rail Stations [No_Rail_Stations],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by tinukedaya** [comment]
Additional info... I tried to tow the Buggy out of the TCL... Placed an old beat up Van next to it, attached attached tow cable, drove away. The Buggy never moved even tho I drove about 40 tiles away and the cable is still connected, never snaps.

**Comment by tinukedaya** [comment]
[Shelter Bay.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8177696/Shelter.Bay.zip)

the save file for testing

**Comment by LeahLuong** [comment]
May be related to #55019. My guess is the vehicles are somehow triggering ledges & that's what's causing them to get stuck. There's a recent, 2nd save provided for testing in that thread.

The debug error regarding textures may simply be a buffering problem caused by the density of TCL & is prob unrelated to the main issue here. TCL lag has been noted by other players & there are multiple possible causes; 1 possible cause is the texture pool being overtaxed.
