### ISSUE TITLE
Installing fuel tanks with items in them results in a crash

### ISSUE THREAD

**Issue by ZombieZilla** [CleverRaven/Cataclysm-DDA#55797]
### Describe the bug

Installing a fuel tank with items inside it, onto a vehicle results in the game crashing

### Steps to reproduce

1. Obtain "Metal Tank (60L)"
2. Insert any item into it
3. Install onto vehicle
4. Observe crash

### Expected behavior

Fuel tanks with items in them to not display as a valid component for installation onto a vehicle

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22557.1 (Dev)
- Game Version: 2c922b0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8176662/crash.log)

**Comment by oosyrag** [comment]
Unable to reproduce in f7c92b9, 2/27 experimental. 60L tank with item in it was not a valid 60L tank to install a Vehicle Tank (60L). Removed item and could install.

**Comment by LeahLuong** [comment]
@oosyrag Isn't OP version more recent than the 1 you tested??

**Comment by oosyrag** [comment]
It is, that's why it's tagged needs confirmation and not can't reproduce.

Knowing that it had worked in the near past makes it easier to track down the change that may have caused it.

**Comment by casswedson** [comment]
/confirmed on 
- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 21.2.6; Codename: Qonos; 
- Game Version: 12933403 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8628231/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8628232/debug.log)
[test.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8628233/test.zip)
