### ISSUE TITLE
No autoinsert containers are autoinserted if inside another container

### ISSUE THREAD

**Issue by ymber** [CleverRaven/Cataclysm-DDA#55800]
### Describe the bug

Painkiller bottles that I set no autoinsert on are getting stuff automatically put in them when they're in my IFAK pouch.

### Steps to reproduce

1. Debug in IFAK pouch, painkiller bottle, aspirin.
2. Set no autoinsert for both containers' pockets.
3. Insert aspirin into painkiller bottle to half fill it.
4. Insert painkiller bottle into IFAK pouch.
5. Insert anything else that will fit in the painkiller bottle into the IFAK pouch.
6. It got autoinserted into the painkiller bottle.

### Expected behavior

Setting no autoinsert prevents items from being automatically inserted into a container in all conditions.

### Versions and configuration

Current experimental at e0ad823f1f47a78211a509d50932720ef0112f51. No relevant mods.

**Comment by oosyrag** [comment]
Linking issue to #55631 as potentially related.
