### ISSUE TITLE
Can't take down/deconstruct electric kiln after placing

### ISSUE THREAD

**Issue by geskeca** [CleverRaven/Cataclysm-DDA#55801]
### Describe the bug

When placing an electric kiln with the construction menu, there is no way to take it down with examining nor a way to deconstruct it with the deconstruct furniture and simple deconstruct furniture options

### Steps to reproduce

1. Place an electric kiln with the construction menu
2. Try deconstructing/taking it down with either deconstruct furniture, simple deconstruct furniture, and examine > take down appliance
3. The game doesn't let you deconstruct the kiln and there isn't an option in the examine menu to take it down.

### Expected behavior

When placing a kiln you should be able to uninstall/take it down?

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 97018ef [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by LeahLuong** [comment]
#55583 was merged a week ago & should address this issue. Please try updating your game version & reproducing this issue after creating a backup.

**Comment by geskeca** [comment]
After updating to the most recent version there is now an option to take down the kiln
