### ISSUE TITLE
Increased Zone Manager Range 

### ISSUE THREAD

**Issue by alp7292** [CleverRaven/Cataclysm-DDA#55812]
### Is your feature request related to a problem? Please describe.

Zone manager range is currently 50 tiles and it makes sorting 3x3 or more buildings harder as it stops halfway when you are sorting or you dont have enough range to sort buildings

### Solution you would like.

making zone manager range 100

**Comment by PatrikLundell** [comment]
It's not possible to have a range larger than the size of the reality bubble, which has a range of 60 (2½ world tiles).
