### ISSUE TITLE
Expanded bronzesmithing

### ISSUE THREAD

**Issue by Jarewill** [CleverRaven/Cataclysm-DDA#55815]
### Is your feature request related to a problem? Please describe.

With the new plate armor updates, I realised that bronze was mostly left alone, which is a shame as that can be an early game alternative to blacksmithing.
So I wanted to start a discussion here about the future of bronzesmithing.

Currently the only armor and weapons that can be made from bronze are historical pieces from Greece and Egypt as well as generic greaves.
However, those recipes (except the greaves) require a historical armorsmithing book, which might not be easily available.
I wanted to suggest a generic bronze armor and weapons (such as how there is the scrap suit and metal sword) that are lower quality than proper historical weapons.

My reasoning for this is to let players that can't obtain those books to still be able to craft a suit of metal armor and weapons, even if they will be lower quality.

### Solution you would like.

Introducing a few more survivor-made bronze items to add to the current bronze greaves:
- A cuirass that's a worse version of the bell cuirass, maybe it gives more encumbrance or maybe having less thickness?
- A helm (maybe two variants for closed and open)
- Vambraces and maybe also arm guards
- Bronze sword and spear, that are worse versions of the xiphos and dory (unbalanced and/or weaker hitting)
- Maybe other weapons such as a mace (upgrade to the trench mace) or axe

All those items should have auto-learned recipes to let players craft them without needing to find books.

### Describe alternatives you have considered.

I'm open to anything regarding this.

### Additional context

I am not a smith in any way, so I don't know about the specifics of working with bronze or making weapons/armor.
However I am willing to work on adding new pieces of bronze armor and/or weapons.
But before that, I wanted to start a discussion here on how it should be handled.

**Comment by oosyrag** [comment]
Higher encumbrance/weight and more materials used seems like a fair balance for someone who is trying to make a suit of armor and has no idea what they were doing. Lower defense could be too if the pieces don't fit together very well. 

Alternatively, a relatively low coverage item could represent a simple strapped chestguard breastplate that should be relatively simple to make.

I doubt you'd be able to make usable gauntlets or greaves at all without some knowledge though.

**Comment by Drew4484** [comment]
> ### Is your feature request related to a problem? Please describe.
> 
> With the new plate armor updates, I realised that bronze was mostly left alone, which is a shame as that can be an early game alternative to blacksmithing.
> So I wanted to start a discussion here about the future of bronzesmithing.
> 
> Currently the only armor and weapons that can be made from bronze are historical pieces from Greece and Egypt as well as generic greaves.
> However, those recipes (except the greaves) require a historical armorsmithing book, which might not be easily available.
> I wanted to suggest a generic bronze armor and weapons (such as how there is the scrap suit and metal sword) that are lower quality than proper historical weapons.
> 
> My reasoning for this is to let players that can't obtain those books to still be able to craft a suit of metal armor and weapons, even if they will be lower quality.
> 
> ### Solution you would like.
> 
> Introducing a few more survivor-made bronze items to add to the current bronze greaves:
> - A cuirass that's a worse version of the bell cuirass, maybe it gives more encumbrance or maybe having less thickness?
> - A helm (maybe two variants for closed and open)
> - Vambraces and maybe also arm guards
> - Bronze sword and spear, that are worse versions of the xiphos and dory (unbalanced and/or weaker hitting)
> - Maybe other weapons such as a mace (upgrade to the trench mace) or axe
> 
> All those items should have auto-learned recipes to let players craft them without needing to find books.
> 
> ### Describe alternatives you have considered.
> 
> I'm open to anything regarding this.
> 
> ### Additional context
> 
> I am not a smith in any way, so I don't know about the specifics of working with bronze or making weapons/armor.
> However I am willing to work on adding new pieces of bronze armor and/or weapons.
> But before that, I wanted to start a discussion here on how it should be handled.

Bronze is petty good metal, steel is just enough better and easier to obtain raw materials for (depending on your region). The current bronze in game is a copper/tin or copper/aluminum alloy. Of the two, copper/aluminum is tougher and harder. 

The major elements are fairly common in game. Copper, tin, and aluminum have other uses that would be in competition with making bronze.

Making either is relatively simple, the two flavors are distinct enough that I'd recommend either two types of bronze or just using aluminum/copper alloy for the higher strength. The lower temperatures required means less fuel consumed compared to steel.

As has been mentioned above, bronze is heavy, and more suited to partial cover rather than complete plate suits. It also works well for scale and lamellar. For weapons it really doesn't have any advantages over steel, it is more brittle which we could represent with low chip defense.

**Comment by Jarewill** [comment]
> Higher encumbrance/weight and more materials used seems like a fair balance for someone who is trying to make a suit of armor and has no idea what they were doing. Lower defense could be too if the pieces don't fit together very well.
> 
> Alternatively, a relatively low coverage item could represent a simple strapped chestguard breastplate that should be relatively simple to make.

The bell cuirass has 15 encumbrance (7 when fitted), 90% coverage and 3 thickness.
It's also sturdy and weights 5.9kg

My potential idea for the survivor bronze cuirass would be to make it more similar to the scrap cuirass, except made with bronze.
So it would have 80-85% coverage on the torso, 15 encumbrance can be kept, but without the ability to fit it and only having 2 thickness.
That would put it at 8 cut, 10 bash and 4 ballistic.

Of course that's just my initial idea.
I will accept any tweak to those values.
> I doubt you'd be able to make usable gauntlets or greaves at all without some knowledge though.

I can understand not being able to make gauntlets, however some form of forearm protection could potentially be made.
Currently there are bronze greaves in the game that only cover the shins and knees and are autolearned, so a new "bronze vambraces" item that only covers the forearms could also be possible using the same method, no?
> As has been mentioned above, bronze is heavy, and more suited to partial cover rather than complete plate suits. It also works well for scale and lamellar. For weapons it really doesn't have any advantages over steel, it is more brittle which we could represent with low chip defense.

I understand that, that's why I proposed just adding a few pieces of bronze armor.
Those being the cuirass, vambraces and greaves. (which are already in game)
Those combined wouldn't give protection to the whole body, only covering the forearms, shins and torso.

As for the weapons, while they might not be as good as steel, being able to forge a weapon in runs where steel or recipe books are not that accessible would still be useful.
And regarding the chip resistance, bronze already is weaker than even low carbon steel. (15 chip of bronze vs 17 of lc steel)

**Comment by Drew4484** [comment]
> > Higher encumbrance/weight and more materials used seems like a fair balance for someone who is trying to make a suit of armor and has no idea what they were doing. Lower defense could be too if the pieces don't fit together very well.
> > 
> > Alternatively, a relatively low coverage item could represent a simple strapped chestguard breastplate that should be relatively simple to make.
> 
> The bell cuirass has 15 encumbrance (7 when fitted), 90% coverage and 3 thickness.
> It's also sturdy and weights 5.9kg
> 
> My potential idea for the survivor bronze cuirass would be to make it more similar to the scrap cuirass, except made with bronze.
> So it would have 80-85% coverage on the torso, 15 encumbrance can be kept, but without the ability to fit it and only having 2 thickness.
> That would put it at 8 cut, 10 bash and 4 ballistic.
> 
> Of course that's just my initial idea.
> I will accept any tweak to those values.
> > I doubt you'd be able to make usable gauntlets or greaves at all without some knowledge though.
> 
> I can understand not being able to make gauntlets, however some form of forearm protection could potentially be made.
> Currently there are bronze greaves in the game that only cover the shins and knees and are autolearned, so a new "bronze vambraces" item that only covers the forearms could also be possible using the same method, no?
> > As has been mentioned above, bronze is heavy, and more suited to partial cover rather than complete plate suits. It also works well for scale and lamellar. For weapons it really doesn't have any advantages over steel, it is more brittle which we could represent with low chip defense.
> 
> I understand that, that's why I proposed just adding a few pieces of bronze armor.
> Those being the cuirass, vambraces and greaves. (which are already in game)
> Those combined wouldn't give protection to the whole body, only covering the forearms, shins and torso.
> 
> As for the weapons, while they might not be as good as steel, being able to forge a weapon in runs where steel or recipe books are not that accessible would still be useful.
> And regarding the chip resistance, bronze already is weaker than even low carbon steel. (15 chip of bronze vs 17 of lc steel)

I'm currently updating the scrap armor (#55832) and should have that ready later today.

**Comment by LeahLuong** [comment]
Material availability is something I was thinking about earlier today, specifically: acquiring steel. Cars used to be primarily constructed of the stuff but modern autos feature a lot more aluminum & plastic.

Bronzesmithing becomes more valuable in a survival scenario when steel is harder to come by. Thinking about submitting a feature request unless some1 beats me to the punch . . .

**Comment by Drew4484** [comment]
> Material availability is something I was thinking about earlier today, specifically: acquiring steel. Cars used to be primarily constructed of the stuff but modern autos feature a lot more aluminum & plastic.
> 
> Bronzesmithing becomes more valuable in a survival scenario when steel is harder to come by. Thinking about submitting a feature request unless some1 beats me to the punch . . . 

I've been slowly converting armor materials, cars are high on the priority since they should give a reasonable variety of materials. If you want to take on any of that piece by piece, by all means dive in.

**Comment by Sathra225** [comment]
I was thinking of adding bronze darts (possibly like plumbatae with lead) and an epsilon axe (very early polearm). Possibly something like a bill/brush axe as well (which could be another item with grass_cutting).

**Comment by Drew4484** [comment]
> I was thinking of adding bronze darts (possibly like plumbatae with lead) and an epsilon axe (very early polearm). Possibly something like a bill/brush axe as well (which could be another item with grass_cutting).

Weapons are easy to handle as the only thing that would change with a material update would be the overall durability of the weapon.
