### ISSUE TITLE
Mapgen: Incorrect bridge generation

### ISSUE THREAD

**Issue by KurzedMetal** [CleverRaven/Cataclysm-DDA#55826]
### Describe the bug

My world generated an inaccessible bridge.

### Steps to reproduce

Not sure how to force to reproduce this.

### Expected behavior

An accessible bridge

### Screenshots

![image](https://user-images.githubusercontent.com/1426680/156865397-fc47b50b-f759-422f-ac39-837519bef4f7.png)

![image](https://user-images.githubusercontent.com/1426680/156865382-6d6b6f4b-6b4e-4638-95e0-7edde374338d.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1526 (21H1)
- Game Version: 6cea46d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by oosyrag** [comment]
Linking for duplicate #46844. Please consider including a save file to assist in resolving the issue.

**Comment by Night-Pryanik** [comment]
Closing as duplicate.

**Comment by KurzedMetal** [comment]
I don't think that's a duplicate, but whatever, it's fine by me.

**Comment by LeahLuong** [comment]
Yeah, this looks closer to #22133 or the more recent #55779. Still, all these issues fall into the category of faulty bridge generation & will hopefully be addressed in 1 PR.

**Comment by oosyrag** [comment]
It's okay, closed issues are still available for review and linked to the other topics. It may not be exactly the same but a fix will likely address all of them. The issue can also be reopened of necessary if it remains afterwards.
