### ISSUE TITLE
RetroASCII tileset is missing

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#55823]
### Describe the bug

The RetroASCII tileset is my preferred choice for overmap tiles, and it seems to have gone missing sometime in the last month

### Steps to reproduce

N/A

### Expected behavior

Where did it go?

### Screenshots

N/A

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1526 (21H1)
- Game Version: 2250560 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Disable NPC Needs [no_npc_food],
    Fewer Soldier Extras [Fewer_Soldiers],
    No Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    No Vault [No_Vault],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

**Comment by oosyrag** [comment]
I believe it was renamed to ASCIITiles.
