### ISSUE TITLE
Ballistic Plates In Ablative Pockets Display With Armor

### ISSUE THREAD

**Issue by bombasticSlacks** [CleverRaven/Cataclysm-DDA#55840]
### Is your feature request related to a problem? Please describe.

Something I'm planning to tackle myself (though someone else could jump on it). Just waiting on the outfit wrapper where this logic should go.

It's something hard to tell if your ablative plates are actually in the vest giving you defense. 

### Solution you would like.

Ablative plates you have in a vest providing defense should display with your armor (and be nested under the vest)

### Additional context

![image](https://user-images.githubusercontent.com/4514073/156895040-cff864f9-69c4-4c0d-bde1-9e2afe1f38e5.png)

**Comment by andrei8l** [comment]
> Just waiting on the outfit wrapper where this logic should go.

If this is only an UI issue then you can fix it already from `inventory_selector::toggle_categorize_contained()`
<details>
<summary>dirty patch</summary>

```diff
diff --git a/src/inventory_ui.cpp b/src/inventory_ui.cpp
index 399c113a21..d4d9ba8f09 100644
--- a/src/inventory_ui.cpp
+++ b/src/inventory_ui.cpp
@@ -2450,9 +2450,18 @@ void inventory_selector::toggle_categorize_contained()
                     // might have been merged from the map column
                     custom_category = entry->get_category_ptr();
                 }
-                add_entry( own_inv_column, std::move( entry->locations ),
-                           /*custom_category=*/custom_category,
-                           /*chosen_count=*/entry->chosen_count, entry->topmost_parent );
+                item_location const loc = entry->locations.front();
+                if( ( loc->has_flag( STATIC( flag_id( "ABLATIVE_LARGE" ) ) ) or
+                      loc->has_flag( STATIC( flag_id( "ABLATIVE_MEDIUM" ) ) ) ) and
+                    loc.parent_item()->contained_where( *loc )->get_pocket_data()->ablative ) {
+                    custom_category = &item_category_ITEMS_WORN.obj();
+                    inventory_entry const blorg( entry->locations, custom_category );
+                    replacement_column.add_entry( blorg );
+                } else {
+                    add_entry( own_inv_column, std::move( entry->locations ),
+                               /*custom_category=*/custom_category,
+                               /*chosen_count=*/entry->chosen_count, entry->topmost_parent );
+                }
             } else {
                 replacement_column.add_entry( *entry );
             }
```
side note: I would have expected `item::is_ablative()` to tell me if this item is a piece of ablative armor rather than if it has ablative pockets.
</details>

It's kinda hacky, but editing `character/outfit::is_worn()` seems too invasive.

**Comment by bombasticSlacks** [comment]
Yeah is worn would be too much. I'll take a look at this tomorrow thank you. 

There isn't really a limit to what things can be ablative armor, since for example ablative mantles and ablative skirts also exist. And in the future an ablative armor might be wearable as part of armor or on its own so it's impossible to really say if an armor itself is compatible as an ablative plate (without tedious hardcoding), whereas it's easy to cache if an armor has ablative pockets.
