### ISSUE TITLE
Adv. Inv. Manager not listing all books/manuals in inventory

### ISSUE THREAD

**Issue by TadhgEomonn** [CleverRaven/Cataclysm-DDA#55866]
### Describe the bug

Check my inventory (i) and I find a certain number of books and manuals. Choose to use Advanced Inventory Manager (AIM) to move books/manuals from inventory to a book shelf. Result: some but not all the books/manuals are listed in my inventory, consequently I cannot transfer all the books/manuals to the book shelf (or any other place) using AIM. Going back to regular Inventory (i) and the missing items are listed. Using multiple Drop (D) does show the disappearing items.

Not sure if this problem is restricted to particular books or manuals; have noticed that cook books/manuals are an example of a book/manual that is disappearing from the inventory list within the AIM. 

This bizarre behavior of missing books/manuals is complicated by the annoying and confusing habit of the program storing books and manuals (and all other types of items) into appropriately sized containers. Locating sneakily hidden items that are inside of other containers is most frustrating. 

### Steps to reproduce

1. Give a character some number of books and manuals.
2. Use regular inventory to verify which books and/or manuals the character possesses.
3. Open Advance Inventory Manager and check which books/manuals are listed and which are missing.
4. Go back to inventory to be sure you still have the missing books/manuals and that they have not been hidden within some container.
5. Scratch your head.

### Expected behavior

Items in inventory should be consistently listed, regardless which method one uses to check: regular inventory or advanced inventory. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1526 (21H1)
- Game Version: 2c922b0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Arcana and Magic Items [Arcana],
    Magiclysm [magiclysm],
    MST Extra [MST_Extra],
    Dorf Life [Dorf_Life],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by oosyrag** [comment]
Can you reproduce this without mods?

**Comment by LeahLuong** [comment]
It may be you've accidentally applied a filter to your AIM. Have you tried 'r'esetting it??

**Comment by TadhgEomonn** [comment]
It is not a case of mistaken filter setting.

At the moment, the only manual that disappears (in AIM) when moved to inventory (that my character possesses) is _Cucina Italiana_. I do not have any other cook books/manuals to test this. 

If I find time, I may try testing sans mods, but no promises.

**Comment by martosss** [comment]
What I've noticed regarding this is that if you store items inside a container that you're not wearing(a plastic bag/condom/bottle/balloon/cardboard box....) they're not displayed when using AIM, they're "hidden" inside that container.

As a solution you can use "Drop items on nearby tile" and then you'll see all items( works on 0.F-3 Stable for me).
You can also just not store things inside containers(unless the AIM decides to do that due to optimization reasons).

**Comment by TadhgEomonn** [comment]
In the case of the missing books in AIM I have ruled out the case of book hidden inside a jar/bag/pot etc.

**Comment by TadhgEomonn** [comment]
After more than a week waiting for the old version of Rémy Roy's Game Launcher to find the CDDA updates, I updated to the new fork (Gonzalo López). Plus made updates to the Arcana mod. Result: the missing book in AIM has been found (Cucina Italiana).

So, I think that this issue has resolved itself (if it was not a figment of my imagination to begin with).
