### ISSUE TITLE
Cannot load character after 'Saving and Quit' in game. Need to restart entire game.

### ISSUE THREAD

**Issue by alanchengg** [CleverRaven/Cataclysm-DDA#55916]
### Describe the bug

 DEBUG    : default (class butchery_requirements) has two definitions from the same source (dda)!

 FUNCTION : check_duplicate_entries
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\mod_tracker.h
 LINE     : 76
 VERSION  : a139c2e

### Steps to reproduce

1. Clean unzip of windows x64.
2. Make character, doesn't seem to matter what options. I just tab to the end.
3. Everything loads as expected/normal.
4. Save and Quit to main screen
5. Load character
6. Get tons of DEBUG errors as stated above.

### Expected behavior

I expect the game to load as normal. I was able to track down when this issue starts to happen. Something changed on [this build](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-02-21-2034). Builds prior do not have the loading issue.

As far as I know, it still happens on the latest experimental builds.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 21H2
- Game Version: a139c2e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

-----------------------------------------
18:48:42.259 : Starting log.
18:48:42.260 INFO : Cataclysm DDA version a139c2e
18:48:42.260 INFO : [main] C locale set to English_United States.utf8
18:48:42.260 INFO : [main] C++ locale set to 
18:48:42.260 INFO : SDL version used during compile is 2.0.14
18:48:42.260 INFO : SDL version used during linking and in runtime is 2.0.14
18:48:42.285 INFO : Number of render drivers on your system: 5
18:48:42.285 INFO : Render driver: 0/direct3d
18:48:42.285 INFO : Render driver: 1/direct3d11
18:48:42.285 INFO : Render driver: 2/opengl
18:48:42.285 INFO : Render driver: 3/opengles2
18:48:42.285 INFO : Render driver: 4/software
18:48:42.287 INFO : [options] C locale set to English_United States.utf8
18:48:42.290 INFO : [options] C++ locale set to 
18:48:42.290 INFO : Setting language to: 'en'
18:48:42.290 INFO : [i18n] Scanning core translations from lang/mo/
18:48:42.290 INFO : [i18n] Scanning mod translations from ./mods/
18:48:42.292 WARNING : opendir [./mods/] failed with "The system cannot find the path specified.".
18:48:42.419 INFO : Active renderer: 1/direct3d11
18:48:42.631 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
18:48:42.701 INFO : Setting language to: 'en'
18:48:42.844 WARNING : opendir [./mods/] failed with "The system cannot find the path specified.".
18:48:50.114 WARNING : opendir [./save/Golden Lakes/mods] failed with "The system cannot find the path specified.".
18:48:50.568 INFO : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\mod_tracker.h:64: Tried check if 'FakeSpecial_s_gas' had a duplicate, but type 'class overmap_special' does not track object sources
18:48:59.398 INFO : Loaded tileset: UltimateCataclysm
18:48:59.699 INFO : Loaded tileset: UltimateCataclysm
18:49:12.618 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\mod_tracker.h:76 [check_duplicate_entries] default (class butchery_requirements) has two definitions from the same source (dda)!
18:49:41.483 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\mod_tracker.h:76 [check_duplicate_entries] bad_food (class disease_type) has two definitions from the same source (dda)!
18:49:41.863 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\mod_tracker.h:76 [check_duplicate_entries] guns (class item_category) has two definitions from the same source (dda)!
18:49:42.296 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\mod_tracker.h:76 [check_duplicate_entries] magazines (class item_category) has two definitions from the same source (dda)!
18:54:18.059 : Log shutdown.
-----------------------------------------

**Comment by oosyrag** [comment]
Thanks for identifying the build this started occurring. Closing as duplicate.
