### ISSUE TITLE
The MSVC team recently test Cataclysm_DDA project failed to run "Cataclysm-test-vcpkg-static-Release-Win32.exe" test on release and debug configuration on Windows_x86

### ISSUE THREAD

**Issue by Apriltanq** [CleverRaven/Cataclysm-DDA#55919]
### Describe the bug

Cataclysm_DDA failed to run run "Cataclysm-test-vcpkg-static-Release-Win32.exe" test on release and debug configuration with MSVC on windows x86. Could you please help look at this issue or provide some workarounds? Thanks in advance.

### Steps to reproduce

1. git clone https://github.com/CleverRaven/Cataclysm-DDA F:\gitP\CleverRaven\Cataclysm-DDA
2. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=x86 -arch=x86
3. cd F:\gitP\CleverRaven\vcpkg
4. .\bootstrap-vcpkg.bat -disableMetrics
5. .\vcpkg integrate install
6. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=x86 -arch=x86
7. cd F:\gitP\CleverRaven\Cataclysm-DDA\build_x86
8. msbuild /m /p:Platform=x86 /p:Configuration=Release ..\msvc-full-features\Cataclysm-vcpkg-static.sln /p:OutDir=F:\gitP\CleverRaven\Cataclysm-DDA\build_x86 /t:Rebuild 2>&1
9. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=x86 -arch=x86
10. cd F:\gitP\CleverRaven\Cataclysm-DDA
11. F:\gitP\CleverRaven\Cataclysm-DDA\build_x86\Cataclysm-test-vcpkg-static-Release-Win32.exe 2>&1

### Expected behavior

For Cataclysm-DDA, "Cataclysm-test-vcpkg-static-Release-Win32.exe" test should be run pass on the windows.

### Versions and configuration

OS: Windows 10
Language: English

### Additional context

[test.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8194723/test.log)
[test.log.0.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/8194724/test.log.0.txt)
[test.log.2.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/8194725/test.log.2.txt)
[Cataclysm_DDA_x86 build.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/8194727/Cataclysm_DDA_x86.build.txt)

**Comment by ZhilkinSerg** [comment]
Your build log file tells build was successful.

**Comment by Apriltanq** [comment]
> Your build log file tells build was successful.

Yes, this project was failed with tests.

**Comment by BrettDong** [comment]
Try building for x64 target. Unit tests need around 5GB of RAM, so you may encounter bad alloc in 32-bit.

**Comment by Apriltanq** [comment]
Thanks for your patience and let me know this issue.
