### ISSUE TITLE
Mission "find 30 bandages for Uyen Tran from a refugee center has error display

### ISSUE THREAD

**Issue by martosss** [CleverRaven/Cataclysm-DDA#55912]
### Describe the bug

When you complete that mission the display text has a glitch and doesn't show how many Merch you're getting. (it's the second one he gives you, the first one is to bring him antiseptic).

### Steps to reproduce

I guess complete the mission and read the text

### Expected behavior

The text displays "7 Merch", not code.

### Screenshots

![image](https://user-images.githubusercontent.com/7064677/156948787-451a8b1b-08b0-4425-94c2-96d921fcd8ca.png)

### Versions and configuration

Win 8.1 x64, 0.F-3 Stable, tiles,  English  + "@" soundtrack

**Comment by oosyrag** [comment]
Does not happen in latest experimental.

Note that issue reports for stable are not particularly usable, as there have been over 6 months of work done since then and 0.F is highly unlikely to be updated anymore at this point.
