### ISSUE TITLE
Cows can't defend themselves

### ISSUE THREAD

**Issue by LyleSY** [CleverRaven/Cataclysm-DDA#55910]
### Describe the bug

When attacked by the player or another monster, cows slowly run away and do not attack at all, despite having     "anger_triggers": [ "HURT" ],  set. I'm not sure if that trigger is broken or if cow aggression is set too low for it to make any difference.

### Steps to reproduce

1. Debug yourself a cow
2. Murder it with your bare fists

### Expected behavior

Cow would run, then attack if cornered instead of allowing itself to be slowly killed by a smaller predator

### Versions and configuration

Latest experimental

### Additional context

Trying to figure out the whole aggression/trigger system to see what if anything works

**Comment by martosss** [comment]
Cowpocalypse!
Maybe cows are pacifists? You can similarly corner crows in U shaped building inside parts and fist them to death, so my explanation is that they have the same behavior - just no attack skill. I agree, though, cows have horns and are generally dangerous animals to mess with, unlike crows. [example](https://abc7chicago.com/psychotic-cow-nearly-killed-man-alvin-by-braford-cows/5655964/)

Regarding zombie aggression - zombies tend to love basements. You can dig a house floor to open the basement and then lure stuff to the hole so they fall and get trapped in the basement ... This is a much bigger issue if you ask me. I have 10 basements in my town full of zombies that just stay there.... and they're usually the hard-to-kill kind of zombies that I want to avoid if possible.

**Comment by LeahLuong** [comment]
I think "Cattleclysm" has a nicer ring to it.
