### ISSUE TITLE
prisoner group doomed to die

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#55917]
### Describe the bug

while trying the new prison island challenge I noticed that in every single attempt the zombies manage to eventually kill the important prisoner npcs

### Steps to reproduce

startup the prison island start, survive long enough to observe that within the first few hours all the important npcs are dead.

### Expected behavior

The important npcs survive when left alone the vast majority of the time

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 372311f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Hope [no_hope],
    C.R.I.T Expansion Mod [crt_expansion],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    Stats Through Skills [StatsThroughSkills],
    Bionic Slots [cbm_slots]
]

### Additional context

I also noticed that when using fresh worlds the game frequently throws the error of being unable to locate a start location within 3 overmap tiles. I suspect this has to to do with the island prison being rare due to needing to spawn in a lake.

**Comment by Night-Pryanik** [comment]
> The important npcs survive when left alone the vast majority of the time

This is rather heavy rng-dependent. In my playtests they managed to survive most of the time.

And I don't think they must survive all the time. They are mere prisoners without any superpowers after all. They might be slightly better equipped, but that doesn't make them invincible.

**Comment by robotic-gamer** [comment]
its just in my dozen or so attempts they always seem to die. Could it be that when they spawn heavily were I am killing me before I can observe them they spawn light were the prisoners are allowing them to survive, giving me the false impression that they are doomed?

**Comment by Night-Pryanik** [comment]
First of all, please tell me your monster spawn setting.
Second, please tell me what do you mean by "vast majority of the time".
Third, something might've changed after my tests, and now they are indeed are dying more likely. More tests needed.

**Comment by robotic-gamer** [comment]
1) my settings are the default (note I have the no hope mod)
2) I have attempted a dozen or so times and have yet to encounter them surviving

**Comment by Zireael07** [comment]
No hope mod is pretty likely to be the culprit here.

**Comment by robotic-gamer** [comment]
tried just with the default mods and waited in a cell until noon with fresh world every time, heres how it went
1) dead within the first few hours (before noon)
2) dead within the first few hours (before noon)
3) dead before noon (realized waiting to midnight is overkill)
4) failed to find start within 3 overmap tiles
5) 3 random prisoners survived, none are important like the leader
6) failed to find start within 3 overmap tiles
7) all died within 2 hours (found cellphone in cell)
8) game crashed (probably unrelated)
9) most alive (but leader dead?). all dead before dark
10) most alive (again no leader). by dark only 3 survivors, none are special
11) all but two dead by noon, again no leader, noteworthy is the game spawned me in a guard tower
12) game crashed (probably unrelated)
13) all dead by noon
14) all dead by noon
15) most alive by noon, all dead by dark
16) by noon one survivor, survived till dark (not important unfortunately)

I could keep going if anyone still not convinced
the worlds mod info

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 372311f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

screenshot of world settings
![image](https://user-images.githubusercontent.com/78816055/157121257-4d6bdf42-dc30-4400-8fd6-179620d193c5.png)

**Comment by Night-Pryanik** [comment]
You have doubled the monster spawn setting, and it's not the default setting as you said.

**Comment by robotic-gamer** [comment]
oh my mistake, I must have forgot I made that change. testing on the default spawn shows that seems to have made the difference. closing issue now.
