### ISSUE TITLE
AIM: Cant Select items in non watertight container

### ISSUE THREAD

**Issue by 3l3m01** [CleverRaven/Cataclysm-DDA#55923]
### Describe the bug

The AIM should allow the player to look into containers, using the "Select items in container" option. This only works with watertight containers/ 

### Steps to reproduce

1. Find a Small Cardboard Box
2. Verify that it cannot be opened in AIM.

### Expected behavior

The container could be opened the same as other containers.

### Screenshots

Plastic bottle has the [C] key active:
![image](https://user-images.githubusercontent.com/15616146/156991847-d412243f-7a1b-4d36-83c1-b9f183770935.png)
Small Cardboard Box does not:
![image](https://user-images.githubusercontent.com/15616146/156991942-175c82b5-886c-44f2-af6f-69c5f8781a70.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.17134.2208 (1803)
- Game Version: 2c922b0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

The opening of the container is explicitly forbidden in the cpp code: advanced_inv_area.cpp:232. no idea why

**Comment by LeahLuong** [comment]
This seems related to #55020, if not a dupe.

**Comment by 3l3m01** [comment]
Not completely. 
I made issue too #55925, that is a dupe of #55020,
In that issue you can open the container, and the panel changes, but the description of the panel is "invalid container".
In this case, the can_put_item call returns false, meaning the option to open the container remains red, and if you try to open it, you get the "you cannot put items there" message.
This is caused by an explicit check in the code: if the item is not watertight, you cannot put things there. Its very easy to fix, you just need to remove that if, but the question is what else would it break? (maybe putting liquids into non watertight stuff?)
