### ISSUE TITLE
Volumeless Ammo created when installing turrets, dropping it causes ctd

### ISSUE THREAD

**Issue by MarceloLaser** [CleverRaven/Cataclysm-DDA#55921]
### Describe the bug

On installing a M249 turret on my vehicle, a single unit of weightless, volumeless ammo from the M249 is spawned inside my inventory. On attempting to drop that ammo, or trade with any NPCs while holding it, game crashes.

### Steps to reproduce

1. Install M249 (available on the floor) on the vehicle provided in the save file. Vehicle already has turret mounts.
2. Attempt to drop spawned ammo item using the 'd' menu. Should not work.
3. Attempt to drop spawned ammo item using the advanced inventory menu. Should cause ctd.
4. Attempt to trade with NPC follower available inside base building while holding spawned ammo. Should cause ctd.

### Expected behavior

No random ctd-causing ammo item should be spawned.

### Versions and configuration

- OS: Windows 10.
- Game version: Experimental 2022-03-03-0253, installed through catapult
- Mod loadout: dda, no_npc_food, no_fungal_growth, package_bionic_professions, aftershock, blazeindustries, crt_expansion, magiclysm, DinoMod.
- Graphics: Tiles (Ultica).
- Language: English.

### Additional context

[Meadow Bridge.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8194913/Meadow.Bridge.zip)

**Comment by LeahLuong** [comment]
Pretty sure this didn't happen when I installed that gun on my vehicle in 0.F-3 vanilla. A PR since the last stable broke something or it's 1 of your mods, IMO.

**Comment by MarceloLaser** [comment]
Those are all mods included in the base repo, so if it is one of the mods, I still reckon the bug report goes here, right?

**Comment by LeahLuong** [comment]
I believe so. If it's the mod causing the issue this may be farmed out to the creator but I think that's unlikely.

**Comment by Night-Pryanik** [comment]
Can't confirm in 0.F-8650. Ammo belt from loaded M249 is automatically unloaded on installing and is placed into player inventory, so no more spawning volumeless ammo.
