### ISSUE TITLE
AIM: trying to put items from a container into the same container crashes the game

### ISSUE THREAD

**Issue by 3l3m01** [CleverRaven/Cataclysm-DDA#55926]
### Describe the bug

When you use the "Select items in container" option, you can put other items into the container. If try to move items from the same containers, the game crashes. It is important to have at least half of the container empty. 

### Steps to reproduce

1. Get a plastic bottle with water(2)
2. Drink one water
3. Put the bottle to the ground
4. Open the bottle with AIM, and on the other panel open the tile where the bottle is
5. Try to put the bottle into itself

### Expected behavior

Get some error message.

### Screenshots

![image](https://user-images.githubusercontent.com/15616146/156995552-3b7971f2-afe5-4b6d-ad50-cda186010051.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.17134.2208 (1803)
- Game Version: 2c922b0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8196098/crash.log)

**Comment by LeahLuong** [comment]
This may be what was encountered in #49954. Does that error message look familiar??

**Comment by 3l3m01** [comment]
Not really. This one crashes with a segmentation fault:
![image](https://user-images.githubusercontent.com/15616146/157188430-98942a93-b9b0-43dc-a08d-dcc2262ded37.png)
