### ISSUE TITLE
Game hang on approaching "Missing Caravan" quest bandit NPCs

### ISSUE THREAD

**Issue by Crupette** [CleverRaven/Cataclysm-DDA#55936]
### Describe the bug

When I drive out to the quest area the game hangs and is locked at 100% CPU usage forever. The hang occurs the tick after the NPCs are in the reality bubble. Teleporting to the NPCs does not fix the hang.

### Steps to reproduce

1. Obtain the missing caravan quest from the merchant NPC
2. Drive out to the site
3. Freeze for all eternity

### Expected behavior

I expect the game to not hang, or atleast give me an error message.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Artix; Description: Artix Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.F-6551-g15d894d660 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    C.R.I.T Expansion Mod [crt_expansion],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

### Additional context

Because the game hangs, I don't have an error log to provide. However, I can give my save file.

[save.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/8200828/save.tar.gz)

**Comment by Crupette** [comment]
With some surface level debugging in GDB, the issue appears to be in ```item_contents::all_items_top```. Specifically, the contents variable appears to be malformed, because calling the size() function does not return. The list may be unterminated.

**Comment by Crupette** [comment]
I couldn't recreate the problem on a fresh world. Sorry for the concern. I guess the save got corrupted somehow.

**Comment by LeahLuong** [comment]
Testing if I need to comment a thread to drop an emote.
