### ISSUE TITLE
Improve interaction with deposits

### ISSUE THREAD

**Issue by oosyrag** [CleverRaven/Cataclysm-DDA#55935]
### Is your feature request related to a problem? Please describe.

Utilizing a deposit via the construction menu is unintuitive. A common issue is that new players try to dig up a deposit and then wonder why they do not get the expected material.

### Solution you would like.

I haven't thought of a great solution for this, but some ideas include either digging up deposits to give the expected resources directly, or a prompt that directs players to the construction menu when attempting to dig on a deposit tile.

### Describe alternatives you have considered.

Edit: Add directions in the description of tile, allow harvesting via (e)xamine or (a)ctivate

**Comment by a-chancey** [comment]
Yeah the first time I did it, I didn't realize there was a construction option for harvesting clay and I just dug out the deposits. Even a Popup to confirm "do you want to dig or harvest {resource}?" Would be helpful

**Comment by LeahLuong** [comment]
This is very similar to #41893, still open. Work was done on this issue & subsequently seemingly abandoned.

I think the numbers for the extraction actions need a look as well. My char spent 2+ hrs extracting 10L of sand from a playground sandbox using an entrenching tool; I could do that IRL in a couple of mins using my hands.
