### ISSUE TITLE
Dark Skies Above outdated copy-from 

### ISSUE THREAD

**Issue by HeYaoDaDa** [CleverRaven/Cataclysm-DDA#55931]
### Describe the bug

![image](https://user-images.githubusercontent.com/37257891/157066362-543faab3-c0a6-4e6c-8c19-1ecd11faf611.png)
![image](https://user-images.githubusercontent.com/37257891/157066438-1125f123-f271-409b-a670-8035445432de.png)
There are no two professions in the game.

### Steps to reproduce

look [data/mods/Dark-Skies-Above/overrides/professions.json](https://github.com/CleverRaven/Cataclysm-DDA/blob/a139c2e8c951359de3c6f8f570e0caf55393894a/data/mods/Dark-Skies-Above/overrides/professions.json)

### Expected behavior

delete

### Versions and configuration

Cataclysm-DDA experimental build 2022-03-07-0703

**Comment by LeahLuong** [comment]
Roller Derby Player was added in #8643. Game Master was added in #24477. They're in the base game (AFAIK) & they appear in the list you linked, updated for the mod. Are they not appearing IG when you have the mod running??

**Comment by HeYaoDaDa** [comment]
> Roller Derby Player was added in #8643. Game Master was added in #24477. They're in the base game (AFAIK) & they appear in the list you linked, updated for the mod. Are they not appearing IG when you have the mod running??

now you can find they in base game? Added mods and I can't find them either.

**Comment by LeahLuong** [comment]
0.F-3 vanilla:

![Screenshot_20220307-220501](https://user-images.githubusercontent.com/91638992/157177236-069e4d7e-a110-4822-a7b7-f80a12fd3227.png)

![Screenshot_20220307-220515](https://user-images.githubusercontent.com/91638992/157177282-2e19b7be-1096-48a6-b62e-687da7a46425.png)

**Comment by HeYaoDaDa** [comment]
> 0.F-3 vanilla:
> 
> ![Screenshot_20220307-220501](https://user-images.githubusercontent.com/91638992/157177236-069e4d7e-a110-4822-a7b7-f80a12fd3227.png)
> 
> ![Screenshot_20220307-220515](https://user-images.githubusercontent.com/91638992/157177282-2e19b7be-1096-48a6-b62e-687da7a46425.png)

ho, I in Cataclysm-DDA experimental build 2022-03-07-0703, I look 0.F3,they is exist, but in experimental they is miss, I can't find when they were deleted

**Comment by 3l3m01** [comment]
They have become hobbies in https://github.com/CleverRaven/Cataclysm-DDA/pull/50333.
