### ISSUE TITLE
Magiclysm 'copy-from': 'STR_UP_ALPHA'

### ISSUE THREAD

**Issue by HeYaoDaDa** [CleverRaven/Cataclysm-DDA#55930]
### Describe the bug

STR_UP_ALPHA doesn't seem to exist. but why game no error?
![image](https://user-images.githubusercontent.com/37257891/157065549-6485f10e-b85c-4dc4-9b55-91c3b0bf9dc0.png)

### Steps to reproduce

look [data/mods/Magiclysm/traits/manatouched.json](https://github.com/CleverRaven/Cataclysm-DDA/blob/d6f5cff566213a662755e914fffb948b49d2524c/data/mods/Magiclysm/traits/manatouched.json)

### Expected behavior

Should be delete.

### Versions and configuration

Cataclysm-DDA experimental build 2022-03-07-0703

**Comment by Maleclypse** [comment]
Should be `"STR_ALPHA"`.
