### ISSUE TITLE
Don't Look @ Me While I'm Training!

### ISSUE THREAD

**Issue by LeahLuong** [CleverRaven/Cataclysm-DDA#55945]
### Describe the bug

This is the menu you get when reading an MA manual:

![Screenshot_20220307-123637](https://user-images.githubusercontent.com/91638992/157166655-020c368d-d035-4b0f-bc33-7a8ba3b3148c.png)

This is the menu you get when reading an MA manual w/in training distance of a conscious follower:

![Screenshot_20220307-123453](https://user-images.githubusercontent.com/91638992/157166783-7cfa0d48-2ada-4ec5-a0f6-2340da4faf09.png)

In the 2nd menu, there is no option for continuous reading. This makes it so you need to hide from followers in order to train an MA w/out mashing.

### Steps to reproduce

1. Get a follower.
2. Get a book.
3. ???
4. PROFIT!

### Expected behavior

I expected that martial art level would increase, because all other skills can increase in level w/out mashing.

### Versions and configuration

Android 0.F-3 Tiles English vanilla

**Comment by oosyrag** [comment]
Is read until you gain a level not the same thing?

**Comment by LeahLuong** [comment]
It's not very clear in the pic but the option is gray, unselectable. Lvls are not gained w/ MA's; you either know them or you don't. Followers can't learn them & so the 2nd menu prob shouldn't ever appear.

**Comment by catdach** [comment]
Looks like the code is checking for if there are NPCs nearby before checking if it's a martial arts manual. Which ends up in the menu in second screenshot being shown without the check for the book being an MA-manual being done _at all_. should be easy to fix, just move the martial arts check above the NPC check or add a "and !MA_manual" to the NPC menu check. 

It's kinda weird that it procs the NPC check in the first place considering MA-manuals have no skills or happiness attached to them, I guess it considers NPCs "_able_" to learn from the manuals even though they can't get the martial art from it.
