### ISSUE TITLE
It shouldn't be possible carrying more than the allowed volume.

### ISSUE THREAD

**Issue by Sheco** [CleverRaven/Cataclysm-DDA#5594]
When you drop or take off an item with storage, the character shouldn't just hold on to the items that might have been stored in it, becoming crippled for carrying so much volume somehow.

I think the most reasonable solution would be to drop some items, when they "overflow" the maximum carrying volume.

The idea is that when you take off an item container, you have to empty it and pack it, to store it in another item container, the player should manage the process of emptying the item container somehow.

An easy solution would be opening an AIM window (or a regular drop window) when taking off an item container to force the player to drop items until the character is not holding more volume than the limit.

I've noticed you can usually pick up 1 or 2 units above your maximum allowed volume, incurring in encumberance penalties, I think this shouldn't be allowed.

**Comment by kevingranade** [comment]
This is implemented, yay.
