### ISSUE TITLE
Encumbrance for load bearng v

### ISSUE THREAD

**Issue by Arokha** [CleverRaven/Cataclysm-DDA#55940]
### Describe the bug

The sort armor menu will only not warn you if you're wearing the `load bearing vest with sling` as the lowest torso item, despite being strapped, and tells you to keep lowering it, despite increasing encumbrance penalties for doing so.

### Steps to reproduce

Equip some torso armor and a load bearing vest with sling. The 'natural sort' on equip will put it last. Open the sort menu and play around with the layer and read the messages.

### Expected behavior

Strapped equipment should be outside other equipment and the sort armor menu should not give bad advice.

### Screenshots

![image](https://user-images.githubusercontent.com/15028025/157132245-ed33cdfa-bfbf-4c2b-88ff-18cf8cf63fc2.png)

Well this is where it equipped it, why's it complaining? I'll move it lower...

![image](https://user-images.githubusercontent.com/15028025/157132290-e03a05b0-d1df-4b52-bacd-2f2af63259ca.png)

Oh now it's even worse. So, yeah.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: openSUSE; Description: openSUSE Tumbleweed; Release: 20220228; Codename: n/a; 
- Game Version: 0.F-6545-gccfc9fdcbf4-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Avali Mutations [avali]
]

### Additional context

Item was recently added. Not sure it ever worked.

**Comment by LeahLuong** [comment]
I can't tell how up-to-date your game version is. #54897 caught some issues w/ LBV but perhaps it missed this. If not, it could be that updating will fix this.

**Comment by ProjectileWaterfowl** [comment]
I've had this problem with latest.

**Comment by molkero** [comment]
Looks like the lbv layering gets borked when you add things like the sheath to it.
