### ISSUE TITLE
registering already built furniture as camp expansion

### ISSUE THREAD

**Issue by Shadesmar99** [CleverRaven/Cataclysm-DDA#55953]
### Is your feature request related to a problem? Please describe.

when i already built a wood stove, i dont see the need to expand my camp with another wood stove, just to get access to the other upgrades

### Solution you would like.

a function that lets me register the already built wood stove as part of my camp (as expansion to circumvent the need for a camp wood stove)

### Describe alternatives you have considered.

well... i could deconstruct my wood stove and have it constructed again by me stoopid followers... which i need to teach the skill first.... which is a bit ridiculous

**Comment by PatrikLundell** [comment]
The way forward, as I see it, would be to have logic that scanned what constructions exist in the base/expansions to determine what capabilities to provide. However, for this to be possible there would have to be something that defined what constructions/furniture/appliances contributes in the form of functionality, and, quite possibly, how groups of "equipment" would provide additional functionality.
The current logic has the "recipes" that construct base/expansion parts explicitly specify "provides" that either enables hard coded functionality (like hunting) or recipe groups (which define specific recipes made available). There isn't any logic that enables recipes, which is what would be needed for scanning to work.
There's also the issue with the current base camp interface which lists all crafting recipes in a single list together with all the other actions available, and that would be a very cumbersome interface for every recipe in the game: the UI would need to support crafting recipes sorted into categories, possibly in the same way the regular crafting interface does. In addition to that, the game currently can't handle companion crafting of liquids as the step where you're asked into which containers you want to store the liquids doesn't exist, so you'd end up with the liquids dropped on the ground. Either some logic for handling this has to be added, or a filter to exclude such useless recipes from companion crafting is needed (it's possible to define recipes where the container is part of the recipe, so the product is e.g. a bottle of milk, but there isn't any crafting logic that can adjust the output container based on the input container, i.e. you can specify that the recipe requires one of several types of containers, but the container of the product is fixed, so if you chose gallon jugs as input, the output would still produce e.g. glass bottles of milk).

It can also be noted that some expansions (canteen and workshop) contain a progression where additional construction provides access to additional crafting recipes. This is partially a somewhat artificial way to provide a sense of progress that doesn't exist for player crafting, where basically any heat source allows you to craft any kind of food, regardless of how complex a setup you'd need in reality. I imagine it would be rather difficult to make a pizza using a rusty tin can over an open fire, but the game doesn't have the granularity needed to distinguish what you can and can't do (and it would probably be a chore if it did on too detailed a level). The companion crafting progression is a way to indicate a progression up the complexity ladder, even if the constructions providing additional functionality isn't actually directly related.

Another problem with a mixture of player construction and construction missions is that the construction missions use blueprints that are defined to be placed at predetermined locations, replacing whatever was there before (which would be nothing for a well constructed hub/expansion when the player hasn't constructed anything) without any way to arrange for a merge. Also note that there is currently no way to see where a hub/expansion construction will be placed, although the version 2 hub/expansions provide a bare dirt outline to provide an indication of where construction will occur if the base/expansion is fully constructed.

It IS possible to hack additional constructions into a base/expansion that does nothing but enable specific recipe groups or enable hard coded functionality, but as the matter stands currently I don't think it would be a good idea to do that as part of the hubs/expansions. However, if you do hack it for personal use, once a functionality has been enabled it will remain enabled even if you update the game (for as long as compatibility is maintained, of course).
