### ISSUE TITLE
missing folders

### ISSUE THREAD

**Issue by solidheron** [CleverRaven/Cataclysm-DDA#55954]
### Describe the bug

A series of critical errors come from the fact that there is two missing folders.
"./modes" and "./saves/[world name]/mods"
the errors will result in a long list of [check_duplicate_entries] before crashing and losing a save file

### Steps to reproduce

1. start new game (you might need a virtual machine running windows)
2. create charter and world, or do play now
3. save and quit
4. enter back into game

### Expected behavior

the code should create a "./modes" and "./saves/[world name]/mods" file if there isn't one or the code shouldn't call for either folders if it doesn't exist

### Screenshots

![Screenshot from 2022-03-08 10-39-37](https://user-images.githubusercontent.com/101203357/157284370-966f464c-7f30-401c-b35f-9c4971448411.png)

### Versions and configuration

2022-03-08-0607

### Additional context

in the screenshot just look at the warnings

**Comment by ZhilkinSerg** [comment]
Are you using any third party mods?

**Comment by oosyrag** [comment]
The check duplicate entries errors are unlikely to be related - it could be safely ignored without causing a crash or save file corruption. Also a fix was pushed for that today.

**Comment by BrettDong** [comment]
"folder not exist" is just a warning and has nothing to do with subsequent errors you encountered.
