### ISSUE TITLE
Spawning items in vehicles is MASSIVELY underused

### ISSUE THREAD

**Issue by NaturesWitness** [CleverRaven/Cataclysm-DDA#5595]
While looking at vehicles.cpp, I just noticed something;  despite having a system to spawn items in vehicles, 99% of the vehicles spawn with nothing.  Nada.  Zip.
I guess it's just something that got overlooked (the vehicle item code is pretty new), I think we should make an effort to add a few spawns to all the vehicles.  We don't want military trucks and swat vans to be loot piñatas, but they should at least have a chance to have SOME stuff lying in them.  Same with an umbrella occasionally in the back seat of a car, a spare tire or jack in the trunk, etc.  All those little things that get left lying around and make a car a CAR, and not just some mobile metal box.

Does anyone want to work on this?  Or have any good ideas for items to include?  I may even take a crack at it myself if nobody is interested.

**Comment by illi-kun** [comment]
I'm ready to implement missing items, and I need to hear your ideas about appropriate items in these vehicles:
- wheelchair
- unicycle
- bicycle
- bicycle_electric
- scooter
- scooter_electric
- motorcycle
- shopping_cart
- wheelbarrow
- handjack
- electric_car
- car_sports
- car_sports_electric
- flatbed_truck
- car_mini
- beetle
- bubble_car
- military_cargo_truck
- apc
- apc-gl
- aapc-mg
- aapc-gl
- armored_car
- humvee
- humvee_gl

**Comment by Coolthulhu** [comment]
It would be the best if the item spawns rather generic.
Not "cigarettes in a Car brand car", but "light drugs in civilian vehicle".
That way it would both make sense and be easy to reuse.

Needed groups are:
* Car tools and emergency utilities (small extinguishers, first aid, flashlights)
* Clothing
* Army gear (not just weapons - UPSes, radios, first aid, MREs)
* Backup fuel containers (currently empty due to technical limitations) like jerrycans
* Motorcycle gear (clothing, helmets)
* Food that can be easily eaten while driving. Especially fast food
* Everyday utilities (knives, multitools, screwdrivers)

**Comment by Zireael07** [comment]
Like the way you're thinking, Coolthulhu!

**Comment by qbradq** [comment]
Here are my suggestions. I hope this helps you with some ideas, and I am very excited for the PR!

- wheelchair
  - over-the-counter drugs
- unicycle
  - monocle (what else :) )
- bicycle, bicycle_electric, handjack
  - nothing (where would it go?)
- scooter, scooter_electric
  - scarfs and warm hats
- motorcycle
  - leather jacket, light drugs
- shopping_cart
  - trash (like paper wrappers, plastic bottles, etc)
- wheelbarrow
  - tools, rags and nails
- electric_car, car_sports, car_sports_electric, bubble_car
  - nice clothing
  - upper-class snack items (granola, juices, mineral water)
  - light drugs
- flatbed_truck, car_mini, beetle
  - household tools (wrench, screwdriver)
  - household chemicals (bleach, ammonia)
- flatbed_truck, car_mini, beetle, car_sports
  - fuel containers
- flatbed_truck, car_sports
  - fuel containers
  - knives
  - hand guns and ammo (rare)
- military_cargo_truck, apc, apc-gl, aapc-mg, aapc-gl, armored_car, humvee, humvee_gl
  - military weapons and ammo, gear, food and passes
- flatbed_truck, military_cargo_truck
  - heavy tools (cordless drill, cement mixer, welder, acetylene tourch, etc.)

**Comment by illi-kun** [comment]
@Coolthulhu, yeah, that's how I'm trying to do it, thanks for ideas of item groups.
@Rivet-the-Zombie I didn't know about such possibility, sounds really cool! I'll try to use that.
@qbradq, I love your ideas, especially monocle & scarves!

**Comment by illi-kun** [comment]
Unfortunately, some of vehicles have no storage place (scooters, bicycles, wheelchairs), so some nice ideas can't be implemented. The rest of ideas (not all but the most part of them) is implemented in coming PR.
