### ISSUE TITLE
Can't Remove/Drop Clothing You Are Wearing

### ISSUE THREAD

**Issue by Cpl-Jordan** [CleverRaven/Cataclysm-DDA#55964]
### Describe the bug

You can not drop clothing you are wearing or take them off.

### Steps to reproduce

1. Make a Character
2. Press T to take off clothing
3. See that you can not take off any clothing.

### Expected behavior

Being able to drop clothing you are wearing or taking them off.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1526 (21H1)
- Game Version: c460657 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

It seems version b6afc5a of CDDA works fine when it comes to taking off clothing. But in version a1802d1 the issue appears. Might have to do with #52741

**Comment by geskeca** [comment]
Same for me, I noticed my character was very warm when it was 13C outside which doesn't make sense, I tried to take off some clothing and it says "You are not wearing that item" and doesn't even let me drop the clothing either.

Game Version: a166404 [64-bit]

**Comment by YuPro** [comment]
Posted on reddit, think it'll be better if duplicated here:

«Saw issue on github already, waiting for patch. For now looks like it's best decision to not use last build (2022-03-09-0821), maybe even some builds before it.»

«After loading existing save (which was already overwritten by latest build) on 2022-03-08-1705 I lost all inventory. So no continuing existing runs for me either. Alt-F4 to not kill run completely.»

**Comment by venum4k** [comment]
I updated from https://github.com/CleverRaven/Cataclysm-DDA/commit/48260d313074b1f13d073e5950f12ef0d20e5749 and I've also been getting this issue.
