### ISSUE TITLE
Items that won't fit in pockets can't be wielded from the (g) menu

### ISSUE THREAD

**Issue by SariusSkelrets** [CleverRaven/Cataclysm-DDA#55968]
### Describe the bug

Items too big to find a valid pocket can't be picked up from the ground with (g) and must instead be picked up with (w)

### Steps to reproduce

1. Start as survivor
2. Spawn something too big for your pockets or delete your clothes and spawn something
3. Try to pick it up with (g)
4. Notice how you can't
5. Try to wield it with (w)
6.  Suddently you can

### Expected behavior

Being able to wield an item too big for my pockets from the menu designed for picking stuff up

There's alos some situations where you want to wield multiple objets that are too big to fit in quick succession, which you can't do from (w) since it only works for one item at a time

### Screenshots

![can't pickup](https://user-images.githubusercontent.com/68650913/157464759-e8cf9aee-a77c-42c3-a65c-18173d5f4c58.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 21H2
- Game Version: 8f8e2b4 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by mqrause** [comment]
You can wield the highlighted item by pressing `w` in the pickup menu.

Not sure what the use case for wielding multiple items would be, since they just drop to the floor one you wield the next one.

**Comment by adiosmi-go** [comment]
This is so inconvenient for android users since we need to clicking the back button then w button after because in some cases the shortcut didn't shown up
