### ISSUE TITLE
Sir Tenderloin the Toothsome

### ISSUE THREAD

**Issue by LeahLuong** [CleverRaven/Cataclysm-DDA#55962]
### Describe the bug

There are several books which seemingly contain recipes which have no possibility of crafting. Following is a list of some of the 1's I've found in my cookbooks; the list is by no means exhaustive.

From Dainty Dishes Fit for a King:

![Screenshot_20220308-173802](https://user-images.githubusercontent.com/91638992/157379072-64c6b463-93d7-4d5a-978d-626034e15c5c.png)

Note the Sticky Rice Hedgerows, Sir Tenderloin the Toothsome, & the 5 (!!!) instances of Royal Penny Tea.

From Food Fashions for Young Moderns:

![Screenshot_20220308-174045](https://user-images.githubusercontent.com/91638992/157379456-ef18bec5-2ebe-4c68-9426-d33ba5552142.png)

Note the Low-Carb Sashimi Donburi, Shagbark Nut Ambrosia, & Spaghetti Luchetto.

From Liver-Licious Recipes Your Kids Will Love:

![Screenshot_20220308-174307](https://user-images.githubusercontent.com/91638992/157380000-a534179a-df7b-4f50-8109-da7903cf8af3.png)

Note the Buttery Duck Bites.

The pattern seems to be capitalized entries in the recipes list but this is by no means consistent; family cookbook contains a recipe for Mexican hot chocolate which **_is_** craftable. I'm pretty sure there are other recipes from different book types which are capitalized **_&_** craftable. Here's a pic from another cookbook:

![Screenshot_20220308-175010](https://user-images.githubusercontent.com/91638992/157380740-66511299-5abb-4437-8f06-b2076b1e8a8f.png)

Note the new york wiener. "New York" is a proper noun & **_should_** be capitalized but isn't. This recipe is craftable.

This is a very information-rich game as it is & there is room enough in the description box of items for flavor-related (NPI) text. I can't really think of any good reasons to include filler text like this, let alone 5 separate & identical entries for an item which isn't craftable (i.e., Royal Penny Tea). But I can think of a few reasons not to:

1. The recipes list is meant to serve as a condensation of the actionable options available to the player. There's a reason it doesn't include the entire contents of each book for the player to pore over.
2. Placeholders for future recipes are unnecessary; future recipes can be added later w/out taking up the player's time & attention now.
3. Adding "red herrings" like this is disrespectful of the player's time & attention. Yes, there's some fun in encountering Sir Tenderloin the Toothsome for the 1st time but reading Royal Penny Tea 5 times in a row gets old while you're doing it. The description box is for people who want to soak in the lore or are encountering an item for the 1st time, not the recipes list.

It may be these "red herring" recipes are covering up actual recipes. Sir Tenderloin the Toothsome may be a stand-in for glazed tenderloins. Yet I have other books that **_do_** contain that recipe & neither I nor my char can tell the difference. That's preposterous. If the char knows, that info shouldn't be restricted from the player; if the player knows or can reasonably infer it, there's no reason to obfuscate it like this when scanning what's supposed to be a straightforward readout of a book's condensed knowledge.

Furthermore, the char is presumably able to read these books in depth & would have some inkling of what goes into these recipes. The player gets none of that, just a dead end search while looking thru the ponderous crafting menu. These recipes should be removed from the game or their true names revealed.

### Steps to reproduce

1. Get those books.
2. Read them.
3. ???
4. PROFIT!

### Expected behavior

I expected that Buttery Duck Bites level would increase, because all other skills can increase in level.

### Versions and configuration

Android 0.F-3 Tiles English vanilla

**Comment by remd** [comment]
I think I see 3 different issues here.

1. It looks like the "red herring" recipes were added in #36793. The intention seems to be that these recipes have flavorful titles in these particular books. "Dainty Dishes Fit for a King" contains a recipe for glazed tenderloins named "Sir Tenderloin the Toothsome" and so on. If the flavorful recipe names only appear in the item descriptions and don't add flavor text recipes to the crafting menu I'm not sure there's a glaring issue here.
2. #38515 added burdocks to flora, with associated recipes. The changes to `data/json/recipes/recipe_food.json` re-used the flavor text name "Royal Penny Tea" for 4 new recipes, resulting in 5 recipes in Dainty Dishes Fit for a King for 5 different items all with the same flavor text. These should probably get new flavor text recipe names.
3. "new york wiener" is simply the name of that item. It could certainly be adjusted for the proper noun. https://github.com/CleverRaven/Cataclysm-DDA/blob/d13be2801d5f66b8c14bf2e7168e6f62f154a35b/data/json/items/comestibles/junkfood.json#L1326

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
