### ISSUE TITLE
All clothing insulates all bodyparts

### ISSUE THREAD

**Issue by Crupette** [CleverRaven/Cataclysm-DDA#55972]
### Describe the bug

When wearing clothing, each worn item counts towards every body part instead of what it should cover.
i.e. Shoes provide warmth to every body part instead of just the feet

### Steps to reproduce

1. Create a naked character
2. Give the character a pair of wool socks
3. Now every bodypart has +30 warmth

### Expected behavior

Only the feet should have +30 warmth

### Screenshots

Without the socks:
![2022-03-09-131237_525x180_scrot](https://user-images.githubusercontent.com/9892691/157504897-8e5f5674-0e88-45fc-a3df-a739f98c7e6b.png)
With the socks:
![2022-03-09-131257_520x152_scrot](https://user-images.githubusercontent.com/9892691/157504866-e66fbe61-a393-4592-9b73-fabe8b6f745c.png)
![2022-03-09-131133_700x376_scrot](https://user-images.githubusercontent.com/9892691/157504896-017e85e9-74b6-46cb-bc14-14ca7f19becb.png)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Artix; Description: Artix Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.F-6672-ga166404108-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    No Fungal Growth [no_fungal_growth]
]

### Additional context

Likely related to #52741

**Comment by 42Forty2** [comment]
Can confirm: new characters begin overheating immediately. Additionally, clothing can't be removed - whether using T or D, you get a message with "You are not wearing that item."
