### ISSUE TITLE
SegFault when unwielding a bow into bow sling

### ISSUE THREAD

**Issue by Ivan-Shestakov** [CleverRaven/Cataclysm-DDA#55979]
### Describe the bug

When my character tries to un-wield the composite bow and store it in a worn bow sling, the game segfaults and crashes.

### Steps to reproduce

1. Debug a composite bow + bow sling.
2. Wield the bow and wear the sling.
3. Un-wield the bow - observe seg-fault and game crashes to console.

### Expected behavior

The bow should be stored in the bow sling.

### Versions and configuration

OS - MacOS Big Sur 11.6.4
Game version - built myself from git commit hash 56af356530ac3a76b27d8d7130b9a83084fb79cb
Build command `gmake -j 8 RELEASE=1 TILES=1 LOCALIZE=0 SOUND=1 CLANG=0 ASTYLE=0 RUNTESTS=0 LINTJSON=0`
Tileset - ChibiUltica
Active World mods: 

- disable_npc_needs
- no_fungal_growth
- innawood
- dinomod
- stats_through_skills

### crash.log
The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 0.F-6680-g56af356530-dirty
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

    0   cataclysm-tiles                     0x0000000102f17930 debug_write_backtrace(std::ostream&) + 46

    Attempting to repeat stack trace using debug symbols…
    backtrace: Could not extract binary name from line

### debug.log (2 crashes on different save files.
-----------------------------------------
00:16:57.522 : Starting log.
00:16:57.522 INFO : Cataclysm DDA version 0.F-6680-g56af356530-dirty
00:16:57.524 INFO : [main] C locale set to C
00:16:57.524 INFO : [main] C++ locale set to C
00:16:57.524 INFO : SDL version used during compile is 2.0.20
00:16:57.524 INFO : SDL version used during linking and in runtime is 2.0.20
00:16:57.675 INFO : Number of render drivers on your system: 4
00:16:57.675 INFO : Render driver: 0/metal
00:16:57.675 INFO : Render driver: 1/opengl
00:16:57.675 INFO : Render driver: 2/opengles2
00:16:57.675 INFO : Render driver: 3/software
00:16:57.679 INFO : [options] C locale set to C
00:16:57.679 INFO : [options] C++ locale set to C
00:16:57.817 INFO : Active renderer: 0/metal
00:16:57.947 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
00:16:58.637 WARNING : opendir [./mods/] failed with "No such file or directory".
00:17:04.931 INFO : src/mod_tracker.h:64: Tried check if 'Strangle Temple' had a duplicate, but type 'overmap_special' does not track object sources
00:17:05.094 WARNING : opendir [./save/Dawn_v3/mods] failed with "No such file or directory".
00:17:13.180 INFO : Loaded tileset: Chibi_Ultica

-----------------------------------------
00:33:46.727 : Starting log.
00:33:46.728 INFO : Cataclysm DDA version 0.F-6680-g56af356530-dirty
00:33:46.732 INFO : [main] C locale set to C
00:33:46.732 INFO : [main] C++ locale set to C
00:33:46.732 INFO : SDL version used during compile is 2.0.20
00:33:46.732 INFO : SDL version used during linking and in runtime is 2.0.20
00:33:46.921 INFO : Number of render drivers on your system: 4
00:33:46.921 INFO : Render driver: 0/metal
00:33:46.921 INFO : Render driver: 1/opengl
00:33:46.921 INFO : Render driver: 2/opengles2
00:33:46.921 INFO : Render driver: 3/software
00:33:46.924 INFO : [options] C locale set to C
00:33:46.924 INFO : [options] C++ locale set to C
00:33:47.043 INFO : Active renderer: 0/metal
00:33:47.184 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
00:33:47.935 WARNING : opendir [./mods/] failed with "No such file or directory".
00:33:55.443 WARNING : opendir [./save/TEST/mods] failed with "No such file or directory".
00:33:55.750 INFO : src/mod_tracker.h:64: Tried check if 'FakeSpecial_s_gas' had a duplicate, but type 'overmap_special' does not track object sources
00:34:03.167 INFO : Loaded tileset: Chibi_Ultica

**Comment by Ivan-Shestakov** [comment]
Can't upload a save file, but for reproducing, I literally spawned 2 items and used them as described in main section

**Comment by LeahLuong** [comment]
I wanted to drop a thumbs up emote on your post but seemingly can't do so w/out 1st commenting on the thread. Good job on writing out a thorough bug report & following up w/ a debug test when the file uploader borked (as it so frequently does)!

Any1 know why emote functionality changed a few days ago??

**Comment by haveric** [comment]
I'm unable to replicate this, so it might be a build specific or mod related issue.

- OS: Windows
    - OS Version: 10.0.19044.1586 (21H2)
- Game Version: 0.F-6693-gf34f3ac263 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

> Any1 know why emote functionality changed a few days ago??

I see no functionality change here, might be a browser issue on your end.
