### ISSUE TITLE
AIM Container handling

### ISSUE THREAD

**Issue by 3l3m01** [CleverRaven/Cataclysm-DDA#55998]
### Is your feature request related to a problem? Please describe.

AIM has some primitive handling of containers, mostly from before the new containers.
The current behavior allows the player to open a watertight container, and transfer liquids into it from other watertight containers. The liquid cannot be transferred out, and nothing else can transfer.

### Solution you would like.

I would like AIM to be able to handle the new containers, to make moving items between them easier.

This requires multiple things, like allowing to open nested containers, open containers at both side, allow to move any items, etc. 
On the other hand it would be cool if you could use it to move liquids as well. So if there is already liquid in a container the current behavior would resume, and if the container you try to move doesn't fit, and contains liquid, the game would ask if you wanna move the liquid. 

So for the AIM Container support the following should be implemented:

- [ ] Have two container panes that can be open at the same time
- [ ] Allow opening nested containers
- [ ] Allow going back to the parent container
- [ ] Allow opening pockets (would probably need a chooser)
- [ ] Rewrite move code to work like inserting into container
- [ ] Make moving liquids possible
- [ ] Show the content of certain containers in the AIM menu

**Comment by nemesis688** [comment]
I think the last point is the feature I'd personally want the most. 

I would just like it if a container that has multiple items in it for AIM to show me each item with respect to the 'hidden' setting. Ideally the individual items would also get sorted when using AIM in its Category setting but also just having them displayed under the container would be a big QoL change of me. As it is, the showing of items in a container only seems to work correctly if they are less than 2 layers deep or only have one item in it. So a backpack with a box that has 6 items in it will not tell you at a glance what is in it.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
