### ISSUE TITLE
Allow mapgen to associate single tile "chunks" to "rows" characters

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#55993]
### Is your feature request related to a problem? Please describe.

The current farm generation uses a palette to associate "D" to furrowed earth terrain. At the same time, the mapgen objects also associate "D" to a "sealed_item" corn plant 70% of the time and nothing the rest of the time. This leads to the terrain always being furrowed earth, while 70% of those tiles having crop on them, but furrowed earth should disappear when they're planted, so you should really have furrowed earth 30% of the time and dirt with crops on it 70% of the time. While you can assign percentages to the terrain to get a 70/30 split, the RNGs aren't synchronized.

There are additional cases where this would be advantageous, such as the placement of vents that produce fields, although the farm field case is where it becomes really cumbersome to place each chunk individually.

### Solution you would like.

One of two alternatives (or something better someone else comes up with):
A. Introduce a new mapgen class e.g. called "bundle" that would allow you to define a set of one of each kind of thing you can define in palettes (explicit and implicit), such as terrain, furniture, item, sealed item, etc. The syntax for "object" would allow you to define an association between "bundles" and a character in the same way as normal. That means that you would be able to associate a character to one of a set of bundles with weights for each bundle. When a bundle is resolved the elements of the RNG selected bundle would all be applied together.

B. Allow the "place_nested" syntax to associate a "chunks" entry to a character as a mutually exclusive alternative to an x/y coordinate pair. This has the advantage that no new class would be needed. It might also be useful for chunks that are larger than a single tile, but may well be confusing.

### Describe alternatives you have considered.

Fix the farm field generation bug by replacing each and every one of the rather numerous "D" characters for farm fields with a "place_nested" entry placing a chunk containing a furrow with a 30% chance and one with a sealed_item on dirt with 70% chance, getting the coordinates correct for each of them.

### Additional context

There are other cases where you might want to define a set of things for a tile, such as e.g. things on a table when a table is placed, or an alien creature/growth with a percentage chance only on alien terrain.

**Comment by haveric** [comment]
I've been meaning to look at the crop placement bugs. I don't think it's a complicated issue, but I haven't dug into it yet. I'll try to take a look tonight and update if I make any progress.

**Comment by PatrikLundell** [comment]
The crop planting bug manifested in map gen is easy in principle: just replace every farm plot tile with a chunk with a weight, but there are hundreds of those, which is why I backed off and wrote this instead.

If you're talking about base camp planting/harvesting it likely would be a code issue that's simple to fix (assuming it doesn't work properly currently: I've never used it, but rather planted/harvested with my PC), provided planting works 100% of the time as it does when you do it manually (if a blueprint is used, as it seems from the description. If code is used to deal with each tile uncertainty can easily be handled by changing the terrain and item concurrently).

**Comment by haveric** [comment]
> just replace every farm plot tile with a chunk with a weight

I'm hoping there's a better solution than this, but I won't know until i dig in more.

> base camp planting/harvesting

I can test this as well. I seem to recall it being an issue, but it's been a while since I've tested it. I know the Tacoma planting is working as it should, so if it's in code, it would be easy to fix here too.

**Comment by haveric** [comment]
Initial testing looks good for the draft PR I created with a very minor code change. I'll do some more testing later for basecamps and I might investigate the seed growth issue on late starts while I'm digging into this.

This only fixes the farm part of your request of course. I'm not familiar with the vent side of this issue, but with some more info, I might be able to assist there as well.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
