### ISSUE TITLE
Allow frozen items in some comestibles

### ISSUE THREAD

**Issue by DoctorGoat** [CleverRaven/Cataclysm-DDA#56004]
### Is your feature request related to a problem? Please describe.

I'm playing with Arcana and I've noticed some oddities in what DDA will allow for certain recipes.

Frozen paper will work on a recipe, but it can't be a comestible. Frozen bones are the same way, which stops the making of bonemeal with them if they're frozen. 

### Solution you would like.

A tag on a recipe to ignore frozen ingredients would be nice. Alternately, https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/recipe.cpp#L973 could be modified to `if( result.has_temperature() && !hot_result() && !has_flag( "ALLOW_FROZEN" ) ) {` and I believe that would work. 

### Describe alternatives you have considered.

Some sort of flag that tags an item as a heat source automatically allowing the use of frozen items in recipes if the player is within the 6-tile game constants range. Hotplate/Fire maybe? It'd be good to have it as a tag so mods can use it for items that are less conventional for fire/heating.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
