### ISSUE TITLE
Allow Follower NPCs to assist player with dragging furniture

### ISSUE THREAD

**Issue by Faalagorn** [CleverRaven/Cataclysm-DDA#56009]
### Is your feature request related to a problem? Please describe.

It stemmed from Discord discussion, but it seems that currently there's no way for the follower NPCs to assist player with dragging/moving furniture that are grabbed with `G` key.

It would make sense fir fikkiwers to assist with that, similar to how they assiste with crafting/smashing/etc.

### Solution you would like.

If a player have a follower NPC with them, the follower should assist player with moving items that are `G`rabbed.

### Describe alternatives you have considered.

Assuming control for NPC to allow grab, however it's only available from debug currently, until #53523 will be fully implemented.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.

**Comment by Brambor** [comment]
@Night-Pryanik

> Closing as stale

But you closed it as not planned. There is a difference, right? One might search for stale issues and this would not show up, right?

Otherwise I don't understand the _closing as X_ mechanics.

**Comment by Zireael07** [comment]
@Brambor GH only allows closed as completed and closed as not planned. I admit I do not understand the reasoning behind closing stale issues either, as it makes them difficult to find.
