### ISSUE TITLE
"Nacreous Shell" mutation do not work properly in activated state

### ISSUE THREAD

**Issue by Kosolaper** [CleverRaven/Cataclysm-DDA#56003]
### Describe the bug

"Nacreous Shell" mutation do not provide isolation buff and visibility/movement debuffs in active state. 

### Steps to reproduce

1. Make any surviour.
2. Get "Nacreous Shell" mutation in any way. Preferably by console.
3. Activate "Nacreous Shell" mutation.

### Expected behavior

Expected properly working buffs and debuffs upon activation of mutation in question.

### Versions and configuration

- OS: Windows 10
-   Version: 2004
-   OS build: 19041.1415
- Graphics version: Tiles
- Game version: 2c922b0 (2022-03-01-1530)
- Mods loaded: {
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
No Fungal Growth [no_fungal_growth],
Bionic Professions [package_bionic_professions],
Avali Mutations [avali],
Magiclysm [magiclysm],
No Hope [no_hope],
Mythical Martial Arts [MMA],
Stats Though Skills [StatsThoughSkills]
}

**Comment by TealcOneill** [comment]
Can't reproduce. If you activate you can no longer move but you have to wait a turn for the vision impairment to kick in. @GuardianDll 
OS: Windows
OS Version: 10.0.19045.4291 (22H2)
Game Version: cdda-experimental-2024-05-03-0220 abe3f76 [64-bit]
Graphics Version: Tiles
Game Language: System language []
Mods loaded: [
  Dark Days Ahead [dda],
  Disable NPC Needs [no_npc_food],
  Portal Storms Ignore NPCs [personal_portal_storms],
  Slowdown Fungal Growth [no_fungal_growth]
]
