### ISSUE TITLE
Make grass cutting worthy

### ISSUE THREAD

**Issue by Katanasoul91** [CleverRaven/Cataclysm-DDA#56001]
### Describe the bug

Having a digging tool of 1, or a tool with cutting grass of 1 make no difference when you try to cut grass in order to get hay making the construction of a stone sickle useless in comparason.

### Steps to reproduce

Go to construction menu.
Check both Remove Grass and Cut Grass requirements and tools needed.

### Expected behavior

Cutting grass not only need a more specific type of grass and a specific tool, so it could make sense the six minutes it currently take be cut down to one, or maybe two.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 20H2
- Game Version: 6ca3ef2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Innawood [innawood],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    DinoMod [DinoMod]
]

**Comment by merrygin** [comment]
This is something that bugged me for a while, too. Solving this should be pretty straightforward. Just increase yields for grass cutting and decrease amount of time. Make new construction recipes for better grass cutting (as proper sickles should aslo be better than the stone sickle). I think it could even be debated if the "remove grass" should even yield grass, at least with crude tools. As I am imagining it, it is much more about destroying the grass, any byproduct is just a bonus. Especially with digging 1 tools this should be rather destructive, also as incentive to invest time into proper equipment. Maybe using a better digging tool also increases the chance not to destroy the grass in the process. But I actually think renaming this from "remove grass" to "destroy grass" would also make the differences/benefits of each more clear.

 I'll try to whip up a PR today or tomorrow.
