### ISSUE TITLE
New EOCs won't work in old world

### ISSUE THREAD

**Issue by MikuMiddo** [CleverRaven/Cataclysm-DDA#56014]
### Describe the bug

I found this issue after update a mod,you can find more detail in this issue [#Cannot get mutations form the nano serum](https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/372)
you need crate a new world to make a EOC update work,I think this may have bad effect who wants to play their old save

### Steps to reproduce

1.crate a new world as old_world
2.update EOC
3.crate a new world as new_world
4.trigger the EOC,you will find EOC only works in new_world

### Expected behavior

It should do the same in old_world and new_world

### Screenshots

Try trigger same EOC in old_world
![image](https://user-images.githubusercontent.com/53809752/157815420-8841dc28-3dd8-4316-8389-ce7ef2b45508.png)

Try trigger same EOC in new_world
![image](https://user-images.githubusercontent.com/53809752/157812839-137ee7ec-35f4-4bfb-9e5c-eb763c5e762d.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1586 (21H2)
- Game Version: d2f6310 [64-bit]
- Graphics Version: Tiles
- Game Language: 系统语言 []
- Mods loaded: [
    浩劫余生 [dda],
    禁用NPC需求 [no_npc_food],
    禁止真菌增殖 [no_fungal_growth],
    生化职业 [package_bionic_professions],
    <color_light_blue>BL9-100%-怪物耐性版</color> [BL9_100monres],
    <color_light_red>Secronom</color> [secronom],
    <color_light_red>Secronom+ 传说扩展包</color> [secronom_lore_expansion],
    C.R.I.T 扩展 [crt_expansion],
    Cataclysm++ [Cata++],
    X.E.A.S. [XEAS],
    大魔法 [magiclysm],
    变异NPC [mutant_npcs_new],
    <color_cyan>奥术与魔法物品</color> [Arcana],
    灵能 [psychiclysm],
    流浪大师 [wandering_masters],
    余波未尽 [aftershock],
    纳米科技Goats版 [adv_gear],
    莫辛纳甘 - 纳米 [mosin_EX],
    让弓弩再次伟大 [bow_opness],
    Rivtech 光束剑 [beamswordmod],
    气动的乐趣！ [pneumo_fun],
    载具增强包 [blazemod],
    夺命武器 [vorpal_weapons],
    死叶的虚构枪械 [FIC_Weapons],
    手工制作弹匣与弹链 [SD_Magcrafting],
    朱红 [VermilionMod],
    <color_light_blue>减轻疲惫程度</color> [light_weariness],
    更多变异 [even_more_mutations],
    更多幸存者笔记 [more_survivor_notes],
    矿物勘探 [Mining_Mod],
    载具与取向扩展 [ks_variety_pack],
    Oa更多开局地点-船 [Ships],
    基因科技研究所 [oa_early_game_mutations_mod],
    莫洛克村 [morlock_village],
    水塔 [water_towers],
    威利的高层建筑 [whaleys_tallbuild],
    移除火车站 [No_Rail_Stations],
    掘进机及其他矿车 [Heavy miners],
    坦克扩展 重生 [Tankmod_Revived],
    折叠式车辆部件 [deoxymod],
    大魔法数值翻倍 [magicrevamp],
    杂项大魔法扩展 [demon_spider_a],
    充实的玩家特征 [amplified_players_features],
    深入埋藏点 [sarcophagi_access],
    Useful Helicopters [useful_helicopters],
    变异调整 [Mutation_Changes],
    更多军事职业 [More_Military],
    技能提升属性 [StatsThroughSkills],
    敏捷速度加成 [speedydex],
    杀怪提升属性 [stats_through_kills],
    完全可靠医疗仪 [autodoc_harmless_perfect],
    阻止僵尸复活 [no_reviving_zombies_fix],
    余震个人用强化模组 [After_Shock_Personal_UsageMod],
    落樱之鱼的侧边栏扩展 [lyzy_sidebar],
    Tekitou的商业建筑扩展 [tekitoumap]
]

**Comment by ZhilkinSerg** [comment]
We do not support any third party mods here.

**Comment by DoctorGoat** [comment]
Are there situations where this has issues in the base game? I haven't picked into this much, but I made sure the last issue I posted that I ran into first in one of that author's mods also had a situation where it was affecting the base game.

**Comment by MikuMiddo** [comment]
> Are there situations where this has issues in the base game? I haven't picked into this much, but I made sure the last issue I posted that I ran into first in one of that author's mods also had a situation where it was affecting the base game.

May only old save can be effected,I test with lastest exp version save but cannot reproduce it,may this should close till I find the more actually way to reproduce it
