### ISSUE TITLE
CBM glare compensators aren't usable for welding, glare quality need to be updated

### ISSUE THREAD

**Issue by Aeiouuu01234** [CleverRaven/Cataclysm-DDA#56016]
### Describe the bug

The glare quality on the fake googles of the glare compensators CBM is set to 1, and cannot be used for welding

### Steps to reproduce

- Install glare compensators
- try to weld a component

### Expected behavior

To have anti glare qualities

### Screenshots

![FNmSI4M6B2](https://user-images.githubusercontent.com/52901609/157827745-a3452f55-5863-427d-9465-d3ec2bed96b8.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1499 (21H2)
- Game Version: 48260d3 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Engineering essentials [EngineeringEssentials],
    Magiclysm [magiclysm],
    Make bows great again [bow_opness],
    MST Extra [MST_Extra],
    Crazy Cataclysm [crazy_cataclysm],
    Deadly Zombie Virus [deadly_bites],
    Extra Mutated Scenarios [extra_mut_scens],
    Mining Mod [Mining_Mod],
    More Survivor Stuff [more_survivor_stuff],
    Mythical Martial Arts [MMA],
    Caches [P_Caches],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Resource Crops [resource_crops],
    Plant Crops [resource_crops_plants],
    No Fungal Growth [no_fungal_growth]
]

**Comment by Night-Pryanik** [comment]
Can't confirm on vanilla 0.F-6730.
Also, welding goggles have the same `GLARE` quality of 1 as Anti-Glare Compensators bionic.

My inventory
![изображение](https://user-images.githubusercontent.com/11132525/157833751-fda6c936-b123-40b6-ba78-8b96aa593fc8.png)

My bionics
![изображение](https://user-images.githubusercontent.com/11132525/157833848-8804bfff-14ac-4a5b-a756-73737e79a3c4.png)

Tried to craft 100L steel drum
![изображение](https://user-images.githubusercontent.com/11132525/157833974-315e60d4-bfc4-451c-9c10-727fb450d8bb.png)

Could you recheck the issue on vanilla?
