### ISSUE TITLE
cat food toxin free

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#56012]
### Describe the bug

In aftershock I used frostbitten meat to make wet cat food. the cat food claims to be made from cooked meat and has no toxins

### Steps to reproduce

kill moxie
butcher moxie
make cat food out of meat
observe no toxins in cat food

### Expected behavior

cat food made with toxin containing meat containing toxins

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 372311f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Hope [no_hope],
    C.R.I.T Expansion Mod [crt_expansion],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    Stats Through Skills [StatsThroughSkills],
    Bionic Slots [cbm_slots]
]

**Comment by Maleclypse** [comment]
Frostbitten meat doesn't contain toxins.
