### ISSUE TITLE
Give Magiclysm's clothes and armors some breathability

### ISSUE THREAD

**Issue by Naadn** [CleverRaven/Cataclysm-DDA#56020]
### Is your feature request related to a problem? Please describe.

After the sweating update, many vanilla material have breathability to determine their heat dissipation ability. But magiclysm's material  haven't update yet so if someone wear its clothes and armors they will sweating non stop.

### Solution you would like.

Add breathability value to magiclysm's materials like black_dragon_hide, black_dragon_scales, parabolan_wool and demon_chitin .

### Describe alternatives you have considered.

don't

### Additional context

Check other mods' material, they may haven't update the breathability too.

**Comment by Maleclypse** [comment]
I’m adding Aftershock label as this probably needs to be done there too.

**Comment by bombasticSlacks** [comment]
The good news is mod developers really like adding metal and the default state is IMPERMEABLE.

I went to look at aftershock and just ended up doing the like 6 materials that need it.
