### ISSUE TITLE
Condom in wallet doesnt get auto outed to inventory when filled with water

### ISSUE THREAD

**Issue by Drawman12** [CleverRaven/Cataclysm-DDA#56034]
### Describe the bug

Title is explanatory enough

### Steps to reproduce

Get wallet.
Put several condoms in it
Turn off auto pocketing for the wallet (idk if it is related)
Go near a water dispenser
Fill the condoms with water

### Expected behavior

It should out itself from the wallet into my backpack or my hand

### Screenshots

![Ekran görüntüsü 2022-03-11 224815](https://user-images.githubusercontent.com/101427784/157947966-faf34573-3ff8-4318-91c4-2df212b58ada.jpg)

### Versions and configuration

Latest experimental(11h ago or sth)

**Comment by oosyrag** [comment]
Duplicate #55647, thanks for the report though.
