### ISSUE TITLE
Sound preloading json handling is broken

### ISSUE THREAD

**Issue by kuydrac** [CleverRaven/Cataclysm-DDA#56036]
### Describe the bug

When starting the game with a soundpack with a json file for preloading SFX, there's a json error about a missing required field 'id' in the config/debug.log.  Because of the error, many sounds/music from the soundpack won't load correctly.  

From looking at previous commits, I'm guessing this was just a copy-paste error in the src/sdlsound.cpp file, lines 380-395. The lines calling the get_string, has_bool, and get_bool functions, should be using the "aobj" object instead of the "jsobj" object.

### Steps to reproduce

1. In Settings, choose soundpack that preloads SFX.
2. Restart game and notice music/sounds aren't playing as expected.

### Expected behavior

I expected soundpacks with preloading SFX to work.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1526 (21H1)
- Game Version: 640d061 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Error from the config/debug.log:

14:51:08.407 ERROR SDL : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\sdlsound.cpp:741: failed to load sounds: Json error: sound/Otopack/preload.json:44:1: missing required field "id" in object: {
    "type": "sound_effect_preload",
    "preload": [
      { "id": "environment", "variant": "thunder_far" },
      { "id": "environment", "variant": "thunder_near" },
      { "id": "environment", "variant": "WEATHER_FLURRIES" },
      { "id": "environment", "variant": "WEATHER_RAINY" },
      { "id": "environment", "variant": "indoors_rain" },
      { "id": "environment", "variant": "WEATHER_SNOW" },
      { "id": "environment", "variant": "WEATHER_SNOWSTORM" },
      { "id": "environment", "variant": "WEATHER_THUNDER" },
      { "id": "environment", "variant": "WEATHER_DRIZZLE" },
      { "id": "environment", "variant": "daytime" },
      { "id": "environment", "variant": "nighttime" },
      { "id": "environment", "variant": "indoors" },
      { "id": "environment", "variant": "underground" },
      { "id": "environment", "variant": "alarm" },
      { "id": "environment", "variant": "deafness_shock" },
      { "id": "environment", "variant": "deafness_tone_start" },
      { "id": "environment", "variant": "deafness_tone_light" },
      { "id": "environment", "variant": "deafness_tone_medium" },
      { "id": "environment", "variant": "deafness_tone_heavy" },
      { "id": "plmove", "variant": "walk_grass" },
      { "id": "plmove", "variant": "walk_dirt" },
      { "id": "plmove", "variant": "walk_metal" },
      { "id": "plmove", "variant": "walk_water" },
      { "id": "plmove", "variant": "walk_tarmac" },
      { "id": "plmove", "variant": "walk_barefoot" },
      { "id": "plmove", "variant": "clear_obstacle" },
      { "id": "plmove", "variant": "fatigue_m_high" },
      { "id": "plmove", "variant": "fatigue_m_med" },
      { "id": "plmove", "variant": "fatigue_m_low" },
      { "id": "plmove", "variant": "fatigue_f_high" },
      { "id": "plmove", "variant": "fatigue_f_med" },
      { "id": "plmove", "variant": "fatigue_f_low" },
      { "id": "danger_low", "variant": "default" },
      { "id": "danger_medium", "variant": "default" },
      { "id": "danger_high", "variant": "default" },
      { "id": "danger_extreme", "variant": "default" },
      { "id": "radio", "variant": "inaudible_chatter" }
    ]
  }

    ]
  }
]
^

**Comment by kuydrac** [comment]
Here's a link to the code:

https://github.com/CleverRaven/Cataclysm-DDA/blob/1a46a4d3f2b42458d3012c4f4c443faa5e235dce/src/sdlsound.cpp#L380-L395

**Comment by dseguin** [comment]
Sorry about that! This was broken by #55633.
