### ISSUE TITLE
Hub 01 Modular Defense System Duplication Glitch

### ISSUE THREAD

**Issue by Hegamonia** [CleverRaven/Cataclysm-DDA#56043]
### Describe the bug

The Hub 01 Modular Defense System duplicates fluids that don't exceed 1.5L in volume

### Steps to reproduce

1. Acquire the Hub 01 Modular Defense System
2. Go into the crafting menu and craft 1.5L or less of any containable fluid (clean water was easiest for testing purposes)
3. Alternatively, (u)nload a water bottle, or other object containing 1.5L or less fluid
4. Insert the fluid into the Hub 01 Modular Defense System
5. Go into the (i)nventory. There should now be double the amount of fluid in the Hub 01 Defense System; e.g. two units of water from a bottle will turn into four units in one pocket, or six units of water will turn into twelve, filling both pockets

### Expected behavior

The Hub 01 Modular Defense System should be only filling its reservoirs with fluid equal to what you insert; it should not be doubling that quantity out of thin air

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19041.1415 (2004)
- Game Version: e4e6681 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Extra Mutated Scenarios [extra_mut_scens],
    Military Profession Pack [military_professions],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by bombasticSlacks** [comment]
Easy fix is to make it have 1 3L pocket instead of 2 1.5L pockets. This is related to other issues with watertight containers I think.

**Comment by dseguin** [comment]
You could also fix it at the source if you wanted to :P

```diff
diff --git a/src/character.cpp b/src/character.cpp
index 6fd59b901f..0be11d9fa4 100644
--- a/src/character.cpp
+++ b/src/character.cpp
@@ -5420,7 +5420,7 @@ bool Character::sees_with_specials( const Creature &critter ) const
 bool Character::pour_into( item &container, item &liquid, bool ignore_settings )
 {
     std::string err;
-    const int amount = container.get_remaining_capacity_for_liquid( liquid, *this, &err );
+    int amount = container.get_remaining_capacity_for_liquid( liquid, *this, &err );
 
     if( !err.empty() ) {
         if( !container.has_item_with( [&liquid]( const item & it ) {
@@ -5435,6 +5435,11 @@ bool Character::pour_into( item &container, item &liquid, bool ignore_settings )
         return false;
     }
 
+    // get_remaining_capacity_for_liquid doesn't consider the current amount of liquid
+    if( liquid.count_by_charges() ) {
+        amount = std::min( amount, liquid.charges );
+    }
+
     add_msg_if_player( _( "You pour %1$s into the %2$s." ), liquid.tname(), container.tname() );
 
     liquid.charges -= container.fill_with( liquid, amount, false, false, ignore_settings );
```

That should let you use multipocket liquid containers properly

**Comment by Hegamonia** [comment]
This is great to hear, but unfortunately I'm playing through the Catapult Launcher, not the git source. Would this work as-is for a PR, so it can be added into a future update for Experimental?

**Comment by dseguin** [comment]
I can commit it to a PR, I'd want to write unit tests for it anyway just to make sure it doesn't break anything

**Comment by bombasticSlacks** [comment]
I'm definitely down for the *actual* solution thanks dseguin, to the rescue again.

**Comment by Hegamonia** [comment]
That would be much appreciated, yeah. Thanks!
