### ISSUE TITLE
Debug spawning item menu "find" no longer working again

### ISSUE THREAD

**Issue by MikuMiddo** [CleverRaven/Cataclysm-DDA#56051]
### Describe the bug

Use the ‘find’ function in the debug item spawning menu cannot input any words and also block the [quit] function. It looks similar to the issue #54355

### Steps to reproduce

1.Into the debug spawn menu
2.Press [/] to active find function
3.You will find you cannot type any character or even quit the mune

### Expected behavior

Normally using the filter and quit

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1586 (21H2)
- Game Version: b0a8d8c [64-bit]
- Graphics Version: Tiles
- Game Language: 系统语言 []
- Mods loaded: [
    浩劫余生 [dda],
    禁用NPC需求 [no_npc_food],
    禁止真菌增殖 [no_fungal_growth],
    生化职业 [package_bionic_professions]
]

**Comment by BrettDong** [comment]
Cannot reproduce.
<img width="1312" src="https://user-images.githubusercontent.com/21075502/159187592-350e8b71-16ff-4dde-907d-380d57025f96.png">

**Comment by MikuMiddo** [comment]
> Cannot reproduce. <img alt="" width="1312" src="https://user-images.githubusercontent.com/21075502/159187592-350e8b71-16ff-4dde-907d-380d57025f96.png">

It was fixed in the lastest version
![image](https://user-images.githubusercontent.com/53809752/159197167-92fe9396-6928-4336-ad36-3ce3ceb45eba.png)
This issue should be close
