### ISSUE TITLE
Bugs with "Wearing multiple items..." info in Sort Armor menu

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#56055]
### Describe the bug

"Wearing multiple items..." info in Sort Armor menu is showing the same body parts several times. Also this info hides some body part when enumerating body parts.

### Steps to reproduce

Wear two sweatshirts and open Sort Armor menu, check middle pane with "Wearing multiple items..." info.

### Expected behavior

No duplicating and no invisible body parts in aforementioned info text.

### Screenshots

![изображение](https://user-images.githubusercontent.com/11132525/158019661-a7396f70-0b35-43d0-b3fa-06505394959d.png)

### Versions and configuration

Windows 10 x64, 0.F-6755.

**Comment by bombasticSlacks** [comment]
It's probably counting for each sublocation but then displaying the actual bodypart. So it could instead be saying "left forearm, left elbow, left upper arm, left shoulder, right forearm, etc. etc.

Probably an easy fix for someone just need to either print the right things and consolidate whole limbs together, or make it not duplicate at all.
