### ISSUE TITLE
Replace redefined flags with "extend" in XL and XS items

### ISSUE THREAD

**Issue by Jarewill** [CleverRaven/Cataclysm-DDA#56059]
### Is your feature request related to a problem? Please describe.

With #55969 and #56042 I realised a lot of armors in torso_armor.json have redefined flags in their XL and XS versions.
While it doesn't seem to cause issues currently, it's still something that I think should be addressed.
With how it is currently, a contributor would have to change the flags in all 3 versions, which if they forget to, that might cause inconsistencies with other versions.

If the redefined flags were replaced with the following:
`"extend": { "flags": [ "OVERSIZE" / "UNDERSIZE" ] }`
That would make it so only one item would need to be updated and there wouldn't be inconsistencies between versions.
At least in theory.

Of course while I mentioned torso_armor.json specifically, I feel this might be an issue with other files as well.

### Solution you would like.

Going through all armor files and replacing any redefined flags in XL/XS variants with "extend".

### Describe alternatives you have considered.

Removing XL/XS versions entirely, replacing them with (automatic when crafted) refitting using tailoring.
That will most likely require a lot of changes to C++ code, which is currently above my skill.
So I will stay with the first idea.

### Additional context

Mostly posting this as a reminder for myself later when the mentioned PRs get merged.
I wouldn't want to start working on this right now if it can cause conflicts.

Of course if anyone wants to step in and do it, feel free to.

**Comment by sulyi** [comment]
I don't know what's the eta on mentioned PRs. If I can keep up the current pace mine will take a couple more days.
But I don't mind if it get pushed back. 
I setup my workflow anticipating conflicts, so I'm ready for resolving them as they come.

**Comment by Jarewill** [comment]
Matters when they get merged.
That will probably happen in the next batch of merges, so we have to wait for now.
I am also waiting for my PR's tests to be restarted before I open it.
