### ISSUE TITLE
Appliances can't display tiles even if they have "looks_ike"

### ISSUE THREAD

**Issue by KittyTac** [CleverRaven/Cataclysm-DDA#56052]
### Describe the bug

Appliances always show up as fallback ASCII letters even if they have "looks_like" specified in the json.

### Steps to reproduce

1. Install an oven (note that it has "looks_like": f_oven).
2. See that it looks like a # instead of an oven sprite.

### Expected behavior

For looks_like to act properly.

### Screenshots

![image](https://user-images.githubusercontent.com/52408044/158011969-72573c68-00d0-4534-8d20-2184230011af.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.18363.1256 (1909)
- Game Version: b0a8d8c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Kittymod [kittymod],
    Extra Mutated Scenarios [extra_mut_scens],
    Tankmod: Revived [Tankmod_Revived],
    No Rail Stations [No_Rail_Stations],
    No Fungal Growth [no_fungal_growth]
]

### Additional context

N/A

**Comment by Fris0uman** [comment]
I think it works if you set the looks_like to another vehicle part, but it doesn't work across types, same for every other vehicle parts. I think the vehicle table has the same issue in Ultica

**Comment by KittyTac** [comment]
> I think it works if you set the looks_like to another vehicle part, but it doesn't work across types, same for every other vehicle parts. I think the vehicle table has the same issue in Ultica

The table looks fine actually. 
![image](https://user-images.githubusercontent.com/52408044/158012114-76adb5f9-5c19-4d7f-976a-aa6dd9e62f5f.png)

**Comment by Fris0uman** [comment]
My bad the table has its own sprite and doesn't use looks_like https://github.com/I-am-Erk/CDDA-Tilesets/blob/master/gfx/UltimateCataclysm/pngs_incomplete_32x32/vehicle/other/veh_table.png

**Comment by KittyTac** [comment]
The solution would be simply to copy over the terrain sprites and make them vehicle sprites for the appliances then.

**Comment by Fris0uman** [comment]
That doesn't solve the engine issue of looks_like not working across types
