### ISSUE TITLE
Autopickup picks up adjacent sealed comestibles without matching rule

### ISSUE THREAD

**Issue by remd** [CleverRaven/Cataclysm-DDA#56063]
### Describe the bug

When moving through the game world occasionally I am picking up sealed comestibles without asking my character to do so and without any autopickup rules set that would match the item.

Even if I don't have room for the item my character still tries to pick up the item.

### Steps to reproduce

1. Turn on autopick up with auto pickup adjacent enabled.
2. Walk near sealed comestibles without matching autopickup rules.
3. Notice that some of them are automatically picked up.

### Expected behavior

Only items matching auto-pickup rules should be picked up.

### Screenshots

I instructed my character to pick up the ketchup bottles, and then I walked into a house's pantry containing a variety of sealed drinks and foods.

![image](https://user-images.githubusercontent.com/1325809/158034886-aa3d44a9-3e83-4f0c-8316-fdd94d4b52f4.png)

My autopickup configuration:
![image](https://user-images.githubusercontent.com/1325809/158034921-8c72fcf5-7646-4c92-b18d-70b9a02c2958.png)
![image](https://user-images.githubusercontent.com/1325809/158034926-6f88e9a6-612d-43c9-8b93-e6bb6627ad32.png)

Autopickup options:
![image](https://user-images.githubusercontent.com/1325809/158034937-816f7907-0178-4b21-ba71-bc2b0d816d33.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1586 (21H1)
- Game Version: b0a8d8c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

Dropping items and then moving again causes the character to choose other adjacent sealed comestibles to pick up seemingly at random:
![image](https://user-images.githubusercontent.com/1325809/158035157-64710a22-2b55-4c82-a8b3-3662ea6d2030.png)

**Comment by ektoplazm** [comment]
can confirm this on version ef1e34c

**Comment by remd** [comment]
I noticed last night at a refugee camp that it's even attempting to do this on owned goods despite my setting for `Auto pickup owned items: False`. I walked through the guarded stockroom with the canned goods and the game attempted to pick them up and asked for confirmation before stealing.
