### ISSUE TITLE
Rendering issue where half of bottom tile row remains "stuck" from previous frames, requires game restart to fix

### ISSUE THREAD

**Issue by remd** [CleverRaven/Cataclysm-DDA#56064]
### Describe the bug

Occasionally while playing I will have a rendering issue appear where the bottom half of the bottom row of tiles remains stuck forever regardless of zooming in and out, alt-tabbing, save/quit and reload, etc.

The only fix is to restart the game entirely.

This seems like an intermittent issue and may be related to alt-tabbing. I often play the game for long periods and leave it alt-tabbed for minutes at a time while surfing the Internet or watching videos. However, this is not consistent or reproducible - as an example, I left the game alt-tabbed for 5-10 minutes while writing this issue and when I tabbed back in the issue **was not** present.

I have had this issue occur less than 5 minutes into a session, and also not show up for over an hour of play. 

### Steps to reproduce

1. Play Cataclysm for a while, perhaps alt-tabbing occasionally to look at web browser
2. Watch for bottom tile row rendering issue to appear

### Expected behavior

Moving around, zooming in and out, saving and reloading would appropriately re-render the entire scene.

### Screenshots

![image](https://user-images.githubusercontent.com/1325809/158035819-9fa8aacc-62f9-4989-80c0-d337fe2965db.png)

Please zoom in on this screenshot and observe the center area where you can see part of a bathroom (most recognizably a bathtub and toilet) of a house from rendered frames 'stuck' in the bottom of the main menu.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1586 (21H1)
- Game Version: b0a8d8c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Qrox** [comment]
Could you please post your graphics settings, such as fullscreen mode, font size, renderer, etc?

**Comment by remd** [comment]
https://gist.github.com/remd/3fde03bdcc2dafb9b279fb12d8b7464b

**Comment by Qrox** [comment]
With that configuration I can reproduce a similar glitch where random pixels appear in the undrawn edge area when alt-tabbing back, and it may have something to do with the handling of `SDL_RENDER_TARGETS_RESET` event. I'm working on a fix.

**Comment by remd** [comment]
I noticed tonight that this started immediately after closing/ignoring a debug error message.

**Comment by remd** [comment]
It's been a while since I last played so I'm not sure when this was reintroduced but this seems to have returned. I'm on current experimental (2025-06-07-0832). I did not receive any debug error message beforehand or after which used to be the cause. I did alt-tab before this though.

![Image](https://github.com/user-attachments/assets/f5013676-2c88-40fc-acfb-addda728bf45)
