### ISSUE TITLE
Game randomly boots me out

### ISSUE THREAD

**Issue by SoggyLemon** [CleverRaven/Cataclysm-DDA#56068]
### Describe the bug

Not even a crash log or anything, just straight up kicks me out the game.

### Steps to reproduce

I just try to play and it does it by itself

### Expected behavior

For the game to not boot me out.

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: Amazon; Model: KFSUWI; Release: 5.1.1; Incremental: 40.6.5.9_user_659658220; 
- Game Version: 679f478 [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by SoggyLemon** [comment]
ah i forgot to mention, it lets me play for like 5 minutes and then it kicks me out.

**Comment by ZhilkinSerg** [comment]
You are running out of memory. 2 GB of RAM on your device is probably not enough to run in a long term. You can try to save more frequently - saving should clean up the memory.

**Comment by SoggyLemon** [comment]
> 

damn, ok i see why it crashes now, thanks.
