### ISSUE TITLE
Allow you to back out of conversations with NPCs without being forced to make them angry

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#56076]
### Is your feature request related to a problem? Please describe.

I've had a number of cases where the only conversation options you have when initiating conversations with NPCs will make them angry with a high probability. Rather than threatening them or whatever other offensive alternatives you get, you should be able say "bye", or at least escape out. This is particularly bad when the NPC starts with saying something like "drop your weapon and back off", where you can't even back off, as they'll start shooting as soon as you've taken one of the forced offensive options.

### Solution you would like.

When met with an angry response, you should be able to leave with "bye" or using escape. This shouldn't guarantee a non hostile approach from the NPC, but at least it shouldn't aggravate them further.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
