### ISSUE TITLE
Saving to the graveyard should be optional 

### ISSUE THREAD

**Issue by schauveau** [CleverRaven/Cataclysm-DDA#56079]
### Is your feature request related to a problem? Please describe.

In my graveyard, the average size is about 25MB per save so for a frequent player who dies at least once or twice a week, the graveyard can quickly consume GBs of disk space. I manually cleared my graveyard 3 months ago and it is already at 430MB. 

Also, it seems to me that most players do not care and may not even know about the graveyard. 

### Solution you would like.

Consequently, I propose that the use of the graveyard should be controlled by an option. The 2 obvious choices are "always" and "never" but more advanced behaviors could be to ask the user after each death or to put a limit to the number of saves.

**Comment by Inglonias** [comment]
alternatively, an option can be created for a maximum size, and the oldest saves can be deleted when that size limit gets hit.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
