### ISSUE TITLE
Add support for multiple burst modes

### ISSUE THREAD

**Issue by NaturesWitness** [CleverRaven/Cataclysm-DDA#5609]
Was reading some comments on the forums, and it seems a lot of people would like a way to fire smaller bursts with some of the full-auto weapons.  It occurred to me, would it be possible to change the "burst" field in the item jsons to accept multiple values?  

For example, a weapon could have "burst": [3, 10] and be able to cycle from single shot, 3-round burst, and 5-round burst with the burst mode key.

How hard would it be to implement something like this?

**Comment by chaosvolt** [comment]
This would also mesh well with guns that are fully-automatic but lack selective fire, if you can assign randomly-selected burst lengths from a range of minimum and maximum shots.

**Comment by mugling** [comment]
Now supported in `master`
