### ISSUE TITLE
Activated "Hyper-Metabolism" mutation increasing weariness drastically

### ISSUE THREAD

**Issue by Kosolaper** [CleverRaven/Cataclysm-DDA#56094]
### Describe the bug

Upon activation of "Hyper-Metabolism" mutation, calories start to burn and because of that weariness start increasing fast.

### Steps to reproduce

1. Make any surviour.
2. Get "Nacreous Shell" mutation in any way. Preferably by console.
3. Activate "Nacreous Shell" mutation.
4. Wait 30 minutes.

### Expected behavior

I expected that calories burning for healing would not exceed weariness gain of very heavy work types.

### Versions and configuration

OS: Windows 10
Version: 2004
OS build: 19041.1415
Graphics version: Tiles
Game version: a7c2d6d / 2022-03-13-0619
Mods loaded:
{
  Dark Days Ahead [dda]
}

**Comment by SariusSkelrets** [comment]
According to the discussion in #45687, it's not directly intended but was considered to make enough sense to be left in.

AFAIK this mutation is less for general regeneration but more for healing in a safe place

**Comment by Kosolaper** [comment]
Ok
