### ISSUE TITLE
Quick tea crafting — similar to unattended water boiling. (I may be able to code something myself, but need advise.)

### ISSUE THREAD

**Issue by Tamior** [CleverRaven/Cataclysm-DDA#56095]
### Is your feature request related to a problem? Please describe.

You can boil water by simply putting a pot with water on a heat source (and go do something else as it boils).

Something similar should exist for making tea. Watching tea boil for hours every day is neither fun nor realistic.

### Solution you would like.

At least two ways I can think of implementing it:

1) Conventional crating recipe that is **much** faster but requires `clean water (hot)` as one of the ingredients. I can probably try to code this myself.

2) Same as water boiling — put all tea ingredients into a pot, put the pot onto a heat source and it cooks. While this does sound more "realistic", I'm pretty sure this **can't be** jsonised in the current framework. And I'm not expert enough on the C++ size of code to estimate how easy it would be. And I'm even less sure it's even a good idea to hardcode it.

 

### Additional context

Please advise.

**Comment by ProjectileWaterfowl** [comment]
Would making the bulk crafting savings larger work?

**Comment by remd** [comment]
#46775 introduces unattended time to recipes and would likely solve this problem.

It's probably better to focus efforts on that as opposed to implementing unattended cooking individually for different things (boiling water into clean water is an exception).

**Comment by DIBAOS** [comment]
> #46775 introduces unattended time to recipes and would likely solve this problem.
> 
> It's probably better to focus efforts on that as opposed to implementing unattended cooking individually for different things (boiling water into clean water is an exception).

It obviously has many in common, but I think cooking or stewing food would be a little bit easier than making other stuff in recipe. For example, we could put food and water in one pot and calculate their weight and volume together (but it may be one difficult thing to make the mixture's state clear while it fixes solid with liquid, if we can solve, it would blaze new trails), then boil it like boil water unattendedly, we don't need to focus on it. Analogously, this method could also be used to make cooked meat or cattail stalk and so on but not only tea and soup.

**Comment by sbenzaquen** [comment]
Is there a way to set a recipe to only accept HOT ingredients using only json?
I was looking myself into making the quick tea recipe with hot clean water as an ingredient, but I did not find a way to specify this in the recipe. Can I somehow specify `flag_HOT` in the `"components"` section of the recipe?
