### ISSUE TITLE
Two vehicles generated on top of each other

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#56101]
### Describe the bug

As can be seen by the image below, two vehicles are generated overlapping, without merging into a wreck. I don't think this is supposed to happen.

### Steps to reproduce

1. Travel around until this happens.

### Expected behavior

Vehicles either merged into a wreck or the second vehicle not spawning.

### Screenshots

![Screenshot (219)](https://user-images.githubusercontent.com/22739822/158220364-dcf30e68-3b70-4855-9b78-cfddf70d55d6.png)

![Screenshot (222)](https://user-images.githubusercontent.com/22739822/158222576-01455b27-5a25-486f-aa59-037afaf56811.png)

![Screenshot (224)](https://user-images.githubusercontent.com/22739822/158222602-17f4aea2-bd93-4303-a9d8-ca13496d2498.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1586 (21H1)
- Game Version: 53f9bd3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

The first one is a minivan and the second one is a police car. The order is deduced from the fact that a police car shaped chunk of the minivan is missing.

**Comment by PatrikLundell** [comment]
I did comment on that in Additional Context, and have now updated the image section with the two wrecks.

Also, unless wrecks have changed since I played last, the wreck has the vehicles indicating some kind of collision, not overlapping as if they moved in the same direction.

**Comment by Fris0uman** [comment]
Looks like normal behaviour after https://github.com/CleverRaven/Cataclysm-DDA/pull/49105

**Comment by PatrikLundell** [comment]
OK. I still think this is worse than it was before when vehicles are just piled on top of each other rather than actually forming a wreck. It would have been different if there had been some logic to actually cause a collision where vehicles seemed to have run into each other rather than one vehicle materializing partially inside another.

**Comment by kevingranade** [comment]
Yea I've been staring at this feature a lot since I've been debugging fake parts.
What one could do is take the new vehicle and back it up until it no longer overlaps with anything (bailing out if the back end collides with anything), then give it a velocity and run one tick of movement to have the collision code kick in.

A tricky outcome to deal with there is the rammed vehicle being moved, maybe we just disallow momentum transfer.

**Comment by PatrikLundell** [comment]
I think the back up part is a good approach, although I wouldn't mind a single tile overlap/obliteration of the first vehicle's overlapped tiles as a first approach, with collision simulation being done as a refinement, as I wouldn't be surprised if it took a fair while to get that right (especially since that may result in desires to tweak the force transfer handling to yield more realistic collisions (whatever that means, when the game vehicles don't have deformation zones, but comparisons to wrecks from the 1950ies or so might come close)).
