### ISSUE TITLE
[Android] Disappearing shortcut key

### ISSUE THREAD

**Issue by MikuMiddo** [CleverRaven/Cataclysm-DDA#56115]
### Describe the bug

The shotcut in the character description tab disappear

### Steps to reproduce

1.Into the crate character
2.keep pressing [tab] shotcut to the description tab
3.find it disappear

### Expected behavior

it should normally appear

### Screenshots

![%BU%EX866 LV 3DN%G4V(BJ](https://user-images.githubusercontent.com/53809752/158388577-8cde5fcc-f28a-46ff-8589-b417951c7acf.jpg)
![C9~FIVUFZ~~QE_35`Q%QB](https://user-images.githubusercontent.com/53809752/158388622-e3f39be8-7afc-4658-ac9f-7e84dea0d87a.jpg)
![C9~FIVUFZ~~QE_35`Q%QB](https://user-images.githubusercontent.com/53809752/158390983-1d35e7a0-2335-4516-ad51-fbd0d4f3adb7.jpg)

![279E~N@EK8ZCF5P{DRQ8I70](https://user-images.githubusercontent.com/53809752/158409874-7c655583-d2f6-4653-a7af-ed18e1910cd9.gif)

### Versions and configuration

[cdda-android-x64-2022-03-15-0611.apk](https://github.com/CleverRaven/Cataclysm-DDA/releases/download/cdda-experimental-2022-03-15-0611/cdda-android-x64-2022-03-15-0611.apk)

**Comment by oosyrag** [comment]
Duplicate #55714, thanks though!
