### ISSUE TITLE
Giant trapdoor spider is too dangerous and unavoidable in the wild

### ISSUE THREAD

**Issue by DIBAOS** [CleverRaven/Cataclysm-DDA#56133]
### Is your feature request related to a problem? Please describe.

Recently I create a lot of save files with innawood Mod, but none of them last over 1 month, and nine times out of ten I was killed by trapdoor spiders but not starve or cold. I just don't know how to tackle it because I can't see it unless it assault me first, and I angled to battle with them with my spear but it always fail even I wear chitin armor, it grabbed me and I can't breathe, my body was bleeding. Is that anything I missed?

### Solution you would like.

At least reduce its spawn frequency.

**Comment by NetSysFire** [comment]
cc @Light-Wave as they are the author of the mod but the mod is not really the cause (well, minus you having more primitive gear). I have not looked into the regional map settings but it may very well be that trapdoor spider nests are pretty common due to the lack of other map extras in Innawood.

There is #55318 and also #54227, which make matters worse (imho grabs should be able to deplete stamina but not really suffocate you unless a hulk is grabbing and therefore crushing you or something grabs you while in the water). They do strike you by surprise and since there are so many of them, they are absolutely deadly, I agree. However, real life trapdoor spiders strike their prey by surprise, too. They grab them and pull them into their den, which is really, really hard to spot.

My balance proposal would be to actually make the trapdoor spiderden discoverable like any other normal trap, so you could have a bit of leeway before stumbling upon one.
As seen in [this video](https://www.youtube.com/watch?v=6ui0hbv3wVs), it is really hard to spot those though and you need to know what to look for, plus they are incredibly quick to capture their prey. Also I am not sure if they would really appear in groups in real life.

**Comment by DIBAOS** [comment]
> cc @Light-Wave as they are the author of the mod but the mod is not really the cause (well, minus you having more primitive gear). I have not looked into the regional map settings but it may very well be that trapdoor spider nests are pretty common due to the lack of other map extras in Innawood.
> 
> There is #55318 and also #54227, which make matters worse (imho grabs should be able to deplete stamina but not really suffocate you unless a hulk is grabbing and therefore crushing you or something grabs you while in the water). They do strike you by surprise and since there are so many of them, they are absolutely deadly, I agree. However, real life trapdoor spiders strike their prey by surprise, too. They grab them and pull them into their den, which is really, really hard to spot.
> 
> My balance proposal would be to actually make the trapdoor spiderden discoverable like any other normal trap, so you could have a bit of leeway before stumbling upon one. As seen in [this video](https://www.youtube.com/watch?v=6ui0hbv3wVs), it is really hard to spot those though and you need to know what to look for, plus they are incredibly quick to capture their prey. Also I am not sure if they would really appear in groups in real life.

Thanks for your nice reply :) I know this kind of spider isn't from Mod, but I think it has been more dangerous while we haven't modern stuff, I think of grab makes me suffocated maybe because of the translated description, but it indeed hold me immediately and I'm very hard to get free. As you say, real life trapdoor spiders strike their prey by surprise, that's true, but in this game, sometimes I wasn't walk straight to their lair but they digged and tunneled to me, it's a giant kind, something wrong I can't notice and hear it at all, and when I try to escape it keeps chase and hunt me (real world trapdoor spider won't be like that). Alright, I just can't accept that so powerful creatures T _ T

**Comment by DIBAOS** [comment]
> I fully agree that they are way too plentiful and too powerful. I had a group of them spawn near me in my own Innawood playthrough, and I ended up savescumming a lot as they killed me repeatedly early game. Later on I found that chitin armor + gambeson gave acceptable protection against them one-on-one, but they sure were overly plentiful. And they upturned most of the soil in the surrounding plains before I got them under control, which in itself made traversing the area annoying. Some ideas for a nerf:
> 
> * Reduce the number spawned
> * Make them unable to tunnel after surfacing. Maybe have some way for them to turn back into their trap form after a while?
> * Making them unwilling to move far from their spawn point would be nice. Right now they wander all over the map. Not sure how easy such a behavioural change would be to implement in json though.
> * Make the trap discoverable
> * Maybe sprinkle some bones in the area to make it clear that something dangerous lives there.
> 
> Also, perhaps map extras for Innawood should be rebalanced given that so many have been removed, making the ones that remains overly common.

Yea, you gave a lot of valuable points of view. In our real life, trapdoor spiders only live, hunt and breed by their lairs, and they don't like to migrate (according some trapdoor spider paper survey).
More about it, I feel that map extras for Innawood could spawn more wild animals habitat (not the mutant kind), because I think it maybe has less radiation in wilderness without human civilization, virtually we become hard to encounter horse, pig, sheep and cow for there are no human farms. Only dogs and insects have a lot. It makes me have less interests in hunting because just a few mutant monster produce fur and I really don't want to eat mutant organ and meat.

**Comment by Light-Wave** [comment]
Yeah having more map extras for non-mutant animals sounds like a good idea as well.

**Comment by Light-Wave** [comment]
Might be considered solved by #56348

**Comment by DIBAOS** [comment]
> Might be considered solved by #56348

Wonderful amazing. I'll try it right away.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/giant-trapdoor-spiders/28047/10
