### ISSUE TITLE
Hope can add "dig" into player’s "construct terrain" panel

### ISSUE THREAD

**Issue by DIBAOS** [CleverRaven/Cataclysm-DDA#56135]
### Is your feature request related to a problem? Please describe.

Every time I try to use my digging stick to make a shallow pit, I almost exhausted to death, because I must complete this work at one time or I will restart from zero again. So I hope add dig action to construct terrain(*) so I can suspend it and take a breath : )

### Solution you would like.

Add "dig" into player’s "construct terrain" panel

**Comment by Inglonias** [comment]
Similar request for knocking down walls with a pickaxe or jackhammer.

**Comment by FayFlightee** [comment]
Duplicate of #54511. But I'm working on it.

**Comment by NetSysFire** [comment]
Duplicate of #54511.
