### ISSUE TITLE
Random crash ... "bad alloc"

### ISSUE THREAD

**Issue by martosss** [CleverRaven/Cataclysm-DDA#56134]
### Describe the bug

I played for 4-5 minutes, exited without saving(alt+f4), then restarted the game and after playing for 1 more minute the game crashed.

I was just mounting my bike and making a turn to go and loot.

### Steps to reproduce

not sure

### Expected behavior

no crash

### Versions and configuration

Win 8.1, Stable 0.F-3, tiles, English, no mods + "@" soundtrack

### Additional context

[save22.03.16,13h20min.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8262139/save22.03.16.13h20min.zip)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8262143/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8262144/debug.log)

**Comment by Maleclypse** [comment]
I've been having a ton of ctd events in a recent attempt at a playthrough.

**Comment by KorGgenT** [comment]
so if we don't know how to reproduce it, how will we know when to close this issue?

**Comment by mlange-42** [comment]
Having a crash with a similar backtrace/crash.log. It crashes a few game-minutes after the start of the first portal storm. In a previous game (experimental version from around 2 weeks ago), I had a similar issue, right after the start of the portal storm.

Win 10, Version 714f560, tiles, English, mods: `dda`, `no_npc_food`, `no_fungal_growth`, `Only_Wildlife`

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8307509/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8307510/debug.log)
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8307522/save.zip)

**Comment by BrettDong** [comment]
> Having a crash with a similar backtrace/crash.log. It crashes a few game-minutes after the start of the first portal storm. In a previous game (experimental version from around 2 weeks ago), I had a similar issue, right after the start of the portal storm.

> Win 10, Version https://github.com/CleverRaven/Cataclysm-DDA/commit/714f56009aa31d49160d450c8ebaa683fff8dc46, tiles, English, mods: dda, no_npc_food, no_fungal_growth, Only_Wildlife

The crash you had is a different bug and please file a separate issue to track that.
