### ISSUE TITLE
Worn unarmed weapons no longer add damage to attacks

### ISSUE THREAD

**Issue by TheShadowFerret** [CleverRaven/Cataclysm-DDA#56138]
### Describe the bug

Weapons that are *worn* to increase your punch damage, such as skewer knuckles, do not add their melee damage to your strike. If you give them UNARMED_WEAPON and then *wield* them, then it works.

### Steps to reproduce

1. Add UNARMED_WEAPON to skewer knuckles.
2. Spawn zombie.
3. Punch zombie with knuckles worn as intended, see that your strikes are same as empty-handed(no bleeding or increased damage).
4. Wield skewer knuckles & slap zombie with them, see bleeding + increased damage.

### Expected behavior

Not needing to slap enemies with my knuckles since they were intended to worn to punch since #54313.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.556 (21H2)
- Game Version: e033309 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

This was tested with both Brawling and multiple martial arts to make sure I wasn't just using a technique with an inapplicable attack vector.

**Comment by remd** [comment]
Could be related to #52741.

**Comment by Heitomos** [comment]
I'd like to add that Ki Strike from the MMA mod is also no longer being added to damage.

**Comment by Heitomos** [comment]
I want to bring this one up again. It's been over a month since the fix failed and we still can't punch things properly. :(

**Comment by Termineitor244** [comment]
A fix is on the works, but the one doing the PR is sick and not in the best moment to code right now, so you will have to wait some more time.

**Comment by jkoudys** [comment]
Thanks for reporting this issue @TheShadowFerret . I was recently disappointed after training up to unarmed5 by boxing a skeletal juggernaut I'd locked in a cage over a few days. Thought I'd zip through a city at night beating all the Zs with my impact knuckles, but got an unpleasant surprise.
