### ISSUE TITLE
Inconsistent Capitalization in Profession Bionics

### ISSUE THREAD

**Issue by jkopesky** [CleverRaven/Cataclysm-DDA#56144]
### Describe the bug

When browsing profession bionics for any profession with Alloy Plating, the head and torso CBMs are listed as:
"Alloy Plating - head
Alloy Plating - torso"

The leg and arm bionics are listed as:
"Alloy Plating - Legs
Alloy Plating - Arms"

### Steps to reproduce

1. Enter character creation.
2. Move to 'Professions' page.
3. Scroll down to Prototype Cyborg.
4. Check Profession Bionics.

### Expected behavior

'head' and 'torso' should be capitalized (i.e. 'Head' and 'Torso') to match with 'Arms' and 'Legs', as well as to match with the styling of other profession bionics.

### Screenshots

![Inconsistent](https://user-images.githubusercontent.com/55217074/158698308-f5ab585c-63e5-4854-94d0-98f46e6d1111.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.556 (21H2)
- Game Version: 8bc0694 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Crazy Cataclysm [crazy_cataclysm],
    Mythical Martial Arts [MMA],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Manual Bionic Installation [manualbionicinstall],
    Safe Portable Autodoc [safe_portable_autodoc],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by haveric** [comment]
This might be a mod overwriting the items. This is what's here with the base game:
![image](https://user-images.githubusercontent.com/985060/158739846-8ce9f34d-84a2-4728-8782-20bcdadd55a4.png)

**Comment by jkopesky** [comment]
So it is. I should've loaded an unmodified world before posting an issue. Given that this doesn't pertain to the base game, I'm going to mark this issue as resolved.
