### ISSUE TITLE
Pocket Proposal - Add "Organize Inventory" action

### ISSUE THREAD

**Issue by Widdershin** [CleverRaven/Cataclysm-DDA#56155]
### Is your feature request related to a problem? Please describe.

I think a lot of the current contention around pickup rules comes down to the two following usecases:

* Quick - I want to pick up items as quickly as possible, without having to choose where they go (e.g. looting at night)
* Optimal - I want to have my inventory perfectly organized according to pocket autopickup rules (e.g. meds in nested IFAK pouch, mags in pouches)

Right now in the latest experimental, only the quick usecase is well supported as far as I can tell, and many efforts so far to support the optimal usecase have hurt the quick usecase.

### Solution you would like.

By default, all item pickups should happen as quickly as possible while respecting pocket blacklist/whitelists.

I propose a new action the player can take, Organize Inventory. As much as possible, this would reorganise the inventory so that items are stored appropriately following the pocket autopickup rules and priorities.

Organize Inventory could be under the O menu, like Sort out loot, or via an action on an individual bag.

This would allow players to satisfy both usecases, grabbing loot as fast as possible while in danger, and then organizing the inventory when they're safe and can afford to spend many action points.

It could also be nice to have an option where items are stored optimally when in safe mode, and otherwise stored quickly.

Part of why I like this idea is because it feels realistic to throw things in your bag when you're in a rush and then to sit down and sort it out when you have some time. I'm constantly wishing I could do this automatically in my current playthrough.

### Describe alternatives you have considered.

* Always picking up items optimally - could require too many action points in dangerous situations (this is still my preferred alternative of all of these)
* Asking players when picking up items - annoying
* Having a setting for quick/optimal all the time - not nuanced enough, many players will want both usecases
* Having a different pickup hotkey for different strategies - confusing for new players, could still be useful
* Being able to toggle pickup mode manually - could be useful but annoying to keep track of

### Additional context

I'm interested in working on this issue, but I'd want to make sure it's actually desired first. Please let me know if you have a usecase I haven't considered or if this change would make your playthroughs worse.

See also: #56129

**Comment by bombasticSlacks** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/54834 might accomplish what you desire.

Feel free to pick this up though I've been very busy with other stuff.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
