### ISSUE TITLE
Nomad Plate missing Nomad Jumpsuit.

### ISSUE THREAD

**Issue by QuintusAquila** [CleverRaven/Cataclysm-DDA#56156]
### Describe the bug

Nomad Plate's description includes a breathable Lycra jumpsuit and Kevlar Spall Liner, but it currently has 1% Lycra coverage and 2% kevlar on the torso. Its currently plate with lycra and kevlar straps.

### Steps to reproduce

Get Cody to make Nomad Plate, wait five weeks, look at nomad plate.

### Expected behavior

The description dosen't include a lycra jumpsuit, or the armor does include a jumpsuit.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.556 (21H2)
- Game Version: 03d89b0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by bombasticSlacks** [comment]
thanks for reporting this that's a big woops from me.
