### ISSUE TITLE
(hot) food does not rot

### ISSUE THREAD

**Issue by SnowyFlare** [CleverRaven/Cataclysm-DDA#56157]
### Describe the bug

I discovered some odd behavior when it comes to temperature and rot timers. At a sufficiently high temp environment, such that the comestible becomes (hot), the item in question will no longer advance rot timers, as far as I am able to tell at least.

In my test world a group of pigs spawned right next to the hot spring, which I used to show their pulped corpses would remain fresh indefinitely in the scorching waters.

### Steps to reproduce

1. The method I discovered initially, obtain, or use the debug menu, to place a perishable item in a hot spring. If placed in a proper location, it becomes (hot), after waiting and/or advancing time via the debug menu, the items rot timer will not visibly advance

2. The next immediately obvious method is placing the food items inside a nested container and placing them over a contained fire, using a firewood source and waiting several days to the same result.

//I'm unsure if lava tiles are discoverable in the current map generation, but I'm sure the same concept applies. If you were wondering mi-go tours seem to be specifically protected from this via the sauna and foul air effects specifically causing decay on their own.

### Expected behavior

This rot-halting behavior might make sense for items being frozen, if indeed that's how frozen items work. But the behavior of hot food items never spoiling struck me as odd.

Never-the-less I'm unable to say independently that this is not intended. Only that taken to it's extreme, (while seemingly impractical either from the constant fuel needed for a fire or the danger presented by environments that enable it), storing food indefinitely at such temperatures is strange to think about.

Though it seems like a stretch to think that every perishable item stored ~>40C, will keep indefinitely with no repercussions

### Screenshots

![Screenshot (355)](https://user-images.githubusercontent.com/81720283/158748678-da66e95a-e85d-4fcc-a2fc-014b6064184b.png)

### Versions and configuration

- OS: Windows
- Game Version: 03d89b0 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [ Dark Days Ahead [dda] ]

### Additional context

A quick Google search suggested that bacteria proliferates rapidly between 5 and 60 degrees C. the temperature reported from the in-game thermometer seems to suggest that the tile will cause the item to become hot at just below 40C

That's it for my report, do with this information as you will.

//It's irrelevant but I was just trying to figure out if high temperatures made foot rot _quicker_ in my attempt to plan out the hatching of eggs.

**Comment by Marrim** [comment]
I believe this is by design, but a case can be made to change the upper bound to 60C.

**Comment by Hirmuolio** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/item.cpp#L7094

Foods below 32 F (0 C) or above 145 F (62 C) do not rot. At 40 C they should still rot and fast.

If you enable debug mode you can see the temperature of the item in item info (in in 0.00001 K).
