### ISSUE TITLE
Graphic time panel should indicate AM/PM

### ISSUE THREAD

**Issue by sulyi** [CleverRaven/Cataclysm-DDA#56169]
### Is your feature request related to a problem? Please describe.

Visual behaviour of time indicator (no watch).

Dawn and dusk appear the same.

### Solution you would like.

Add colour selection logic to:
https://github.com/CleverRaven/Cataclysm-DDA/blob/86fe522ddda2f5aba3efd619e5f8ff9f875dd2b3/src/panels.cpp#L534
and
https://github.com/CleverRaven/Cataclysm-DDA/blob/86fe522ddda2f5aba3efd619e5f8ff9f875dd2b3/src/panels.cpp#L556

### Describe alternatives you have considered.

Some other visual representation.
I can't think of any.

### Additional context

Minor.

**Comment by Zireael07** [comment]
Why close?

**Comment by sulyi** [comment]
I don't want to regret having it.

**Comment by sulyi** [comment]
I was a mistake.

**Comment by sulyi** [comment]
I laughed so much harder on misspelling since you are subscribe then otherwise would have.

**Comment by AcidAntOnAMinefield** [comment]
If you know the sun rises on the east and that the sun sets on the west, that should be pretty self-explanatory, no?

**Comment by sulyi** [comment]
Fixed.
