### ISSUE TITLE
recipe cover

### ISSUE THREAD

**Issue by HeYaoDaDa** [CleverRaven/Cataclysm-DDA#56161]
### Describe the bug

Some recipe are covered, so they can't be found in the game.

1. lc_chainmail_arms
2. pistol_stock
3. thread (id_suffix:spinningwheel)
4. xl_ch_chainmail_hood
5. xl_qt_chainmail_hood
6. xs_hc_chainmail_hood
7. xs_mc_chainmail_hood
8. xs_lc_chainmail_hood
9. xs_ch_chainmail_hood
10. xl_lc_chainmail_arms
11. propane_cooker
12. xs_qt_chainmail_hood
13. xl_gambeson_vest
14. armor_scrapsuit
15. armor_tiresuit
16. xs_armor_lightplate
17. xs_lc_chainmail_arms
18. gambeson_vest
19. k_gambeson_vest
20. gambeson_vest_xs
21. xl_k_gambeson_vest
22. k_gambeson_vest_xs
23. pot_copper
24. with_power_saw
25. xl_mc_chainmail_hood
26. tshirt
27. xl_lc_chainmail_hood
28. xl_hc_chainmail_hood
29. chem_nitric_acid
30. chem_hmtd

### Steps to reproduce

1.unlock all recipes
2.search recipe

### Expected behavior

These recipes should exist.

### Screenshots

in json:

![image](https://user-images.githubusercontent.com/37257891/158816028-f6be14b5-08f2-4ed7-a939-83739aa79f2b.png)

in game

![image](https://user-images.githubusercontent.com/37257891/158816098-b3b0e651-c4c0-4b16-9abf-9d5f207773b8.png)

### Versions and configuration

cdda-experimental-2022-03-17-0510

**Comment by ZhilkinSerg** [comment]
Probably `"id_suffix"` is missing for missing recipes.

**Comment by remd** [comment]
Is it possible that some recipes are simply duplicated such as `lc_chainmail_arms`?

I don't see any difference between these two recipe definitions for that item.
https://github.com/CleverRaven/Cataclysm-DDA/blob/86fe522ddda2f5aba3efd619e5f8ff9f875dd2b3/data/json/recipes/armor/arms.json#L484-L499

https://github.com/CleverRaven/Cataclysm-DDA/blob/86fe522ddda2f5aba3efd619e5f8ff9f875dd2b3/data/json/recipes/armor/arms.json#L518-L533

Is the correct fix for those cases simply to remove one of those duplicates? Or am I missing something?
