### ISSUE TITLE
More realistic and balanced static drag for wind turbines on vehicle

### ISSUE THREAD

**Issue by vivi00790** [CleverRaven/Cataclysm-DDA#56167]
### Is your feature request related to a problem? Please describe.

-3000 drag for large wind turbine is unrealistic. 2 wind turbine make a 10t vehicle maxspeed drop from 150km/h to 7km/h.

To support my point, ram air turbines(RAT) has been installed on aircrafts as emergency power supply for a long time. It wouldn't be an emergency generator choice if it made a 95% speed drop. There's also [a paper](https://www.researchgate.net/publication/343708946_Aerodynamic_design_and_testing_of_a_Ram_Air_Turbine_for_Small_Fixed-Wing_UAVs) suggested that RATs may extend flying time of UAVs.

Imo this is a lazy and destructive way to prevent player from getting eazy source of vehicle power. One shouldn't lose 95% of speed by simply put two fan on top of his car!

### Solution you would like.

Wind turbines is useless when powering itself moving, it's simple physics. However it should still generate power while it's static and under wind.

Therefore my solution will be: Wind turbines can still generate power with natual wind while vehicle speed under a threshold. While over that speed threshold, wind turbines will start draining power instead to simulate increasing air drag cause vehicle harder to move (or dynamicly increase vehicle air drag)

### Describe alternatives you have considered.

just lower the static drag if you want KISS

### Additional context

some refs:
https://www.vwvortex.com/threads/why-hasnt-any-electric-car-manufacturer-ever-put-a-rat-ram-air-turbine-on-their-cars.8649321/
https://en.wikipedia.org/wiki/Ram_air_turbine

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
