### ISSUE TITLE
tileset bug NPC body absent

### ISSUE THREAD

**Issue by beeeeebo** [CleverRaven/Cataclysm-DDA#56178]
### Describe the bug

![Screenshot_20220314-204140_Cataclysm DDA (experimental)](https://user-images.githubusercontent.com/101843873/158912472-6436ec69-27ff-4539-b1bf-b1d1fea6c3f9.jpg)

### Steps to reproduce

Game started fine the only thing I did besides play the game is trade with the NPC. Also their held inventory dropped on the floor 

### Expected behavior

I expect the npc to load normally

### Versions and configuration

Android
Experimental 
Latest version

**Comment by Fris0uman** [comment]
Not quite fixed yet, but as soon as the tilesets get updated it will be fixed.
