### ISSUE TITLE
Feral humans hitting me with rocks while driving a car

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#56173]
### Is your feature request related to a problem? Please describe.

I am always frustrated when I'm driving a car through a town and the car gets smashed up such that it is no longer enclosed, but ferals are able to hit me with 100% accuracy as I zoom past them at 20mph because driving a car hard-locks my dodge at 0 making all of their rocks hit automatically.

### Solution you would like.

The accuracy of feral humans' rocks should respect the speed at which the player is traveling. Currently the ferals abuse the fact that the car remains perfectly still while processing enemies' turns even though it is "still" for a total of 0 seconds, it's a bit of video game weirdness. I would add the player's MPH to their effective dodge calculation against rocks if they are in a vehicle.

### Describe alternatives you have considered.

Doing this myself, if I can find out how I will.
Also, zombies hopping into your car at 20mph when they can barely stumble in a straight line is really silly, it should be non trivial to board a moving vehicle also. Such as a dodge check against the current MPH (so 5 dodge vs 20mph = 25% chance to not get ran over while trying to board the vehicle, if player has 10 dodge, they can board an 8mph vehicle 100% of the time safely). Again, I'm not sure how to do this, but I can certainly at least try my hand at it.

**Comment by fairyarmadillo** [comment]
Rather than adding to the player's dodge skill, maybe a penalty to accuracy for all ranged weapons would be more appropriate? It's also hard to shoot a gun at someone who is driving quickly IRL, for example.
