### ISSUE TITLE
Frozen Mutagenic Primer, Catalysts and Purifiers disapearing after storing in my vehicle and sorting my loot

### ISSUE THREAD

**Issue by KurzedMetal** [CleverRaven/Cataclysm-DDA#56174]
### Describe the bug

I looted a Frozen Lab for some mutagenic primers, catalysts, purifiers. Obviously everything was "(frozen)" (important to reproduce!)
I happily went to my Vehicle, stored the stuff in my Cargo and sorted my loot ("O o" keys)
A few moments later tried to search for the mutagenics I found, and I noticed only the empty test tubes and flasks were there but no primer, catalysts or purifiers! they just disappeared!

### Steps to reproduce

I'm not sure how to reproduce it from zero, not sure if it's the containers, the particular content/liquid, some cargo being capped, my auto-sort configuration, or if other liquids are affected.
So I'll leave my precise save to reproduce it (which can be used to reproduce 100% of the time)

SAVE: [World 03-11.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8292758/World.03-11.zip)

My save already have some frozen mutagenic primers in the inventory so you can skip steps 2 and 3, but I just wanted to describe what I did or needs to be done to generate them.

1. Open my save
2. Use debug to create a any mutagenic primer in a test tube
3. MAKE SURE IT IS FROZEN or won't reproduce (I didn't know how to debug that so I created a normal one and froze it in the Frozen Lab by waiting some time)
4. Drop the frozen mutagenic primer in any Vehicle cargo space
5. Use the "sort out my loot" feature of the zones manager
6. Open advanced inventory, filter by "mutagenic", search all cargo, you won't find any mutagenic primer.
8. Change the AIM filter to "test tube" and you'll see empty ones that should actually contain the mutagenic primers (liquid is lost, but not the container).

NOTE: If I drop the mutagens and I wait until they are cold, not frozen, and then I sort, they don't seem to disappear.

### Expected behavior

Items shouldn't simply disappear from cargo spaces in my vehicle.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1586 (21H1)
- Game Version: 8bc0694 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth]
]

**Comment by Maleclypse** [comment]
Are the containers holding the liquids open, so they spill when set down?

**Comment by KurzedMetal** [comment]
I don't think so:

1. I didn't notice any message about that when I reproduced it
2. I did move my car to check the floor and didn't see any liquid there, it basically banished.
