### ISSUE TITLE
NO_HOPE Ammo spawning near windows in houses

### ISSUE THREAD

**Issue by wackedoutdj** [CleverRaven/Cataclysm-DDA#56176]
### Describe the bug

For some reason, ammo is spawning near nearly every window in a house with the No_hope mod activated

### Steps to reproduce

-Make a new world
-debug teleport to a house
-see tons of ammo (2.0 item spawn helps too)

### Expected behavior

No ammo should spawn. Maybe broken glass got replaced by ammo spawn?

### Screenshots

![ammo](https://user-images.githubusercontent.com/101839971/158904528-aa2d0244-c559-4ce9-ba93-add104ea9408.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.556 (21H2)
- Game Version: 86fe522 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    No Hope [no_hope]
]

**Comment by Night-Pryanik** [comment]
#56147 should help with this.

**Comment by Maleclypse** [comment]
Closed by #56147
