### ISSUE TITLE
Make it possible to pour liquids into wooden barrel and to craft out of it

### ISSUE THREAD

**Issue by Zireael07** [CleverRaven/Cataclysm-DDA#5617]
Forum thread: http://smf.cataclysmdda.com/index.php?topic=5049.15

Some ideas floated around include:
- a funnel over a container should accept any liquid
- a hose over a container should allow siphoning
##

**Comment by narc0tiq** [comment]
This may be closable now -- you can definitely unload a liquid into a container you're standing on, and you should also be able to craft using a liquid from a container on the ground (within crafting distance). Can I get a confirmation on that?

**Comment by Rivet-the-Zombie** [comment]
I think the second point is asking for the ability to manually transfer an amount of liquid from a container on the ground into a container in your inventory. We still don't have any means of doing that.
