### ISSUE TITLE
genetic downward spiral doesn't work properly

### ISSUE THREAD

**Issue by shadowsapex** [CleverRaven/Cataclysm-DDA#56181]
### Describe the bug

the trait genetic downward spiral just prints the message "Your body tries to shift, tries to change, but only contorts for a moment.  You crave a more exotic mutagen." 

after waiting for 10 days, I still have gotten no mutations. injecting a primer did get me mutations in short order 

having enough starting mutations to push one mutation category to the top circumvents this problem, but starting traits don't count towards this. I suspect that on a normal (non-experiment) character, you will never be able to get genetic downward spiral running unless you first mutate some other way. genetic chaos is fine because it doesn't count as a starting trait, properly giving the chimera category. 

also i have a suspicion that because of the way instability works, the first few mutations you gain (off downward spiral) before it's had a chance to build up are really likely to be good mutations, which changes the dynamics of the trait since the early game is the most challenging part. 

### Steps to reproduce

make a character with only genetic downward spiral
wait 

### Expected behavior

if this is intended behavior it should not be, since it drastically changes the way genetic downward spiral works (now only builds up instability and doesn't affect a non-mutated character). it's a fun and unique trait which used to put pressure early game and i hope its functionality is preserved through the mutation overhaul. also it and its related traits (genetically unstable, genetic chaos) should have their randomness preserved, either picking out-of-category traits or randomly picking a category, since as things stand, genetically unstable and genetic chaos will always mutate toward chimera

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1586 (21H1)
- Game Version: d703f84 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by MylieDaniels** [comment]
This is intentional, and is the reason that GDS was nerfed in point gain.  Future changes will add a stranger variant.

**Comment by shadowsapex** [comment]
> This is intentional, and is the reason that GDS was nerfed in point gain. Future changes will add a stranger variant. True randomness may be re-added.

well currently it gives 8 free points on a non-mut character. also, what _is_ its intended functionality? the instability is fine but as it stands it works drastically different on a normal character vs a mutated character, in a way that's never communicated to the player

**Comment by MylieDaniels** [comment]
Points are irrelevant, tbh.
The intended functionality is that it mutates mutants, and causes instability to all.
The in-game text you cited is a way that it communicates to the player.

**Comment by NetSysFire** [comment]
>The intended functionality is that it mutates mutants, and causes instability to all.

I feel like this should potentially be clarified in the description of the trait.
