### ISSUE TITLE
Get more information from @'s nose and ears

### ISSUE THREAD

**Issue by DIBAOS** [CleverRaven/Cataclysm-DDA#56187]
### Is your feature request related to a problem? Please describe.

There are five basic human senses: touch, sight, hearing, smell and taste, every that is essential for living and usually works with each other. In CDDA, the touch, sight and taste have a relatively reasonably system, but something lacks in hearing and smell, cut to the chase, players are hard to get worthy information from @'s nose or ears, only when we are blame that could find some voice sources, besides @ just perceive some special voices from side text (obviously it hasn't same position accuracy while we're blame and hard to say intuitive only by words, approximate number would better). 

### Solution you would like.

Add voice source icon like that we're blame.
Making a fuzzy intensity of big or weird sounds, words are ok, but number better.
Smell system maybe likes hear system (voice source icon and odor source icon), but I haven't thought too much yet.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
