### ISSUE TITLE
Smokes will smash his own window out if he hears a noise he can't see

### ISSUE THREAD

**Issue by TheShadowFerret** [CleverRaven/Cataclysm-DDA#56193]
### Describe the bug

If Smokes the refugee center merchant hears a noise he can't see, he will smash the reinforced glass down protecting him with his Halligan bar(which he will always spawn with).

### Steps to reproduce

1. Stand outside the door into Smoke's room or where he cannot see you.
2. Yell or otherwise make a noise.
3. He will smash his storefront window down to investigate it.

### Expected behavior

Not being able to easily cheese my way into stealing the merchant's inventory with my voice and a draggable, LoS-blocking furniture like one of the lockers or bookcases in the center.

### Screenshots

![image](https://user-images.githubusercontent.com/99621099/159062189-f5472780-1ea6-422c-9fab-fb304a45a046.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.556 (21H2)
- Game Version: 714f560 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth]
]

### Additional context

Changing his carried weapon to a New York hook or fire axe would both keep his firefighter background and prevent him from being stupid.

**Comment by Night-Pryanik** [comment]
Closing in favor of #56990 as I think both of these issues are essentially the same, but #56990 was set as a release blocker.
