### ISSUE TITLE
The diary knows the precise time always

### ISSUE THREAD

**Issue by ZombieZilla** [CleverRaven/Cataclysm-DDA#56202]
### Describe the bug

When creating a diary entry with no knowledge of the time, it will output the precise time to the second.

### Steps to reproduce

1. Remove all methods of timekeeping on you
2. Create diary entry
3. See exact time

### Expected behavior

The diary entry should either display "???", or basics such as Early Morning, Midday, Evening (if you are able to see the sky)

### Versions and configuration

N/A

**Comment by NetSysFire** [comment]
Ping @LFKrause, as they are the one who added the diary functionality
