### ISSUE TITLE
can't load or create new character because of an error in monsters.json

### ISSUE THREAD

**Issue by LonelyMusicDisc** [CleverRaven/Cataclysm-DDA#56217]
### Describe the bug

title is it really, I suspect it has to do with colors and color templates but no idea beyond that

### Steps to reproduce

1. open the game
2. new game or load game

### Expected behavior

you'd load into the game and play

### Screenshots

![image](https://user-images.githubusercontent.com/37805980/159124650-0b317ebf-fe18-4061-9047-7fa12b0816ad.png)

### Versions and configuration

- OS : Linux mint 20.2
- Game Version: 0.D
- Graphics version: terminal, same regardless though.

### Additional context

[debug.log](https://pastebin.com/JFUgTpU6)

**Comment by NetSysFire** [comment]
0.D is really ancient. Is this a typo?

Can not reproduce. It is probably caused by one of your mods, which might explain the weird path. Try a new, clean world without any mods.

**Comment by ZhilkinSerg** [comment]
We won't backport any fixes to 0.D. Try to reproduce it on a newer version.

**Comment by LonelyMusicDisc** [comment]
ah updated and it's working now, damn old packaging repos
