### ISSUE TITLE
Ammo Boxes!

### ISSUE THREAD

**Issue by ISuckM8** [CleverRaven/Cataclysm-DDA#56211]
### Is your feature request related to a problem? Please describe.

Isn't it strange that no one in this wonderful section of the United States has ever attempted to put ammo in boxes? Why do shopkeepers sell ammunition on their own? Why don't they put them in boxes and sell them that way?

### Solution you would like.

Hear me out. Universal ammo boxes. One for each gun type, to be exact. Shotguns, rifles and pistols. Pistol boxes could hold 40 rounds of any pistol kind. Rifle boxes could also hold 40 rounds. Shotgun boxes could hold 20 shells. Values may change, but you get the idea.

### Describe alternatives you have considered.

1 - Implement an ammo box for every single caliber, but that's too much work and will be a pain to implement to recipes.

2 - Also universal ammo boxes but with more variety. There will be universal ammo boxes for revolvers and pistol calibers for example.

### Additional context

I might start a PR myself, though it will take a while for me to completely execute it due to my real-life commitments.

**Comment by bombasticSlacks** [comment]
I would say it shouldn't be a generic "40" or "20" but the exact number that the round is normally sold in. If your replacing all the spawns you may as well do it right. So .22 is sold in 100 or 150. Those values are already the "count" that you get in game IIRC.

**Comment by bombasticSlacks** [comment]
I can tackle this is #56191 since after it is done I'd have to change everything anyways.

**Comment by bombasticSlacks** [comment]
Actually sorry to rescind my earlier statement but I'm not sure it's a good idea currently. Vetal just made like 200 sprites for every ammo in the game and it seems wrong to trash all that work or hide it behind cardboard boxes. 

So it would have to be 1 box per ammo and per ammo type, with a looks like to the round itself which is more than I want to tackle right now.

**Comment by ISuckM8** [comment]
That's a lot of work, and this isn't factoring the eventual implementation of those boxes into recipes in the future.

**Comment by catdach** [comment]
hmm...in theory, how hard would it be to have an item change it's sprite based on (or use the sprite of the) last item/ammo type inserted into it? I'm guessing it would be pretty hard, but I honestly just don't know.

**Comment by ISuckM8** [comment]
That would require writing new code in C++, and most of us have more important things to do than make cosmetic modifications.

**Comment by PatrikLundell** [comment]
While ammo boxes would make real world sense, it would add to game chore due to the blasted container juggling the game currently has (you'd introduce pill container "fun" for ammo as well).

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
