### ISSUE TITLE
shotgun ammo uses same separator as recipe books

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#56235]
### Describe the bug

the various  blackpowder/improvised shotgun rounds use "," to separate parts of the name ex "00 shot, black powder, scrap loaded". the problem with this is that "," is also used in recipe books to separate different items that the book contains recipes for. The net result is that the bits with the shotgun rounds in it are very confusing to read (see attached picture)

### Steps to reproduce

look at any book that has these recipes

### Expected behavior

items not to use the same separator as the recipe books that can contain them

### Screenshots

![image](https://user-images.githubusercontent.com/78816055/159149856-8f3304ae-f3cf-4472-8435-4a53118a0e82.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19041.1052 (2004)
- Game Version: 03d89b0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Hope [no_hope],
    C.R.I.T Expansion Mod [crt_expansion],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    Bionic Slots [cbm_slots],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

I was not sure if this should be presented as a bug or feature request so sorry to anyone that thinks this should have been presented as a feature request. 
I am pretty sure there is probably books that look even worse then this.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
