### ISSUE TITLE
fd_gas_vent does not immediately emit toxic gas

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#56234]
### Describe the bug

While working on #55211, I noticed this problem quite often, but it is inconsistent and does not appear every time. I suspect it has something to do with the reality bubble.

Labelled as need confirmation because this is sort-of hard to reproduce and it is also low priority because it is highly unlikely a player will ever encounter this one without using debug shenanigans like I do.

### Steps to reproduce

1. Spawn a `fd_gas_vent` with any intensity (but at least 1)
2. Notice that it does not emit toxic gas even after waiting.
3. Teleport some overmap tiles away (one fastscroll move in one direction is enough).
4. Teleport back to the vent you have spawned.
5. Wait a few turns.
6. It suddenly emits toxic gas.

### Expected behavior

It emits toxic gas immediately after spawning.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.F [64-bit] (aeeed331c0cbaa8107d005bbfd6ab2157a901e41)
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by PatrikLundell** [comment]
A few thoughts:
- Does it work if you move the reality bubble away and back "normally" i.e. by having the character walk/drive away and back (I would expect it to do so)?
- If this issue happens only on debug spawns it isn't particularly important, although the debug spawning code might want to update whatever it would need to update to detect the newly spawned field.
- However, it would be a more serious issue if a "proper" use didn't work correctly, such as e.g. map changes triggered by an alarm (similar to how failing to hack some terminals can open doors and release bots). If a trigger should have a vent pop open and emit gas, the gas should actually be emitted.

**Comment by TealcOneill** [comment]
I don't think I managed to reproduce this. The two and three levels of vent immediately spat out gas but the level one takes 15-20 turns between gas expulsions. This means it can take a little bit for it to make visible gas but I didn't have to teleport away to see the gas.
@GuardianDll 
OS: Windows
OS Version: 10.0.19045.4291 (22H2)
Game Version: cdda-experimental-2024-05-03-0220 abe3f76 [64-bit]
Graphics Version: Tiles
Game Language: System language []
Mods loaded: [
  Dark Days Ahead [dda],
  Disable NPC Needs [no_npc_food],
  Portal Storms Ignore NPCs [personal_portal_storms],
  Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by NetSysFire** [comment]
I can not reproduce this anymore, too. Hooray!
