### ISSUE TITLE
Burning building results in spam about terrain t_open_air where furniture is f_rubble

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#56242]
### Describe the bug

 DEBUG    : Setting terrain t_open_air at (127,42,1) where furniture is f_rubble.  Terrain is_open_air
If this is intentional, set the ALLOW_ON_OPEN_AIR flag on the furniture

 FUNCTION : ter_set
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\map.cpp
 LINE     : 1769
 VERSION  : 53f9bd3

This happens a lot when I accidentally set an apartment tower on fire (I intended to set fire to a hedge maze adjacent to it).

### Steps to reproduce

Partial a guess:

1. Set fire to a building higher than one story.
2. Watch spam until you give up and ignore it.

### Expected behavior

No spam when buildings burn and things cave in (a guess is that zombies smashing through buildings ought to be capable of generating similar spam as well).

### Screenshots

Offset screen image of the hedge maze and adjacent apartment tower:

![Screenshot (226)](https://user-images.githubusercontent.com/22739822/159156961-c8339405-597a-4a17-86af-2a8b573f6afd.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1586 (21H1)
- Game Version: 53f9bd3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
+ "mod" in the form of hacking portal storms to do nothing as the actual mod to do so was rejected.

**Comment by PatrikLundell** [comment]
This is a variant of #54092.

**Comment by MrHrulgin** [comment]
It seems this one has reoccured. I set a fire on the second floor of a house, and got:

 DEBUG    : Setting terrain t_hole at (45,50,1) where furniture is f_rubble.  Terrain is_open_air
If this is intentional, set the ALLOW_ON_OPEN_AIR flag on the furniture

 FUNCTION : ter_set
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\map.cpp
 LINE     : 2210
 VERSION  : 2a67568
