### ISSUE TITLE
reloading something that isn't in your inventory can cause it to stop existing.

### ISSUE THREAD

**Issue by redguy999** [CleverRaven/Cataclysm-DDA#56256]
### Describe the bug

reloading an item that is in a container and doesn't fit in your inventory will cause it to stop existing.

### Steps to reproduce

1.  have a reloadable item in a container but not in your inventory.
2. attempt to reload it.
3. get an error message
4. notice that you can't find it anymore.

### Expected behavior

The item to keep existing.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19042.1586 (20H2)
- Game Version: 178dbc8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

### Additional context

My character is/was unable to wield some items when I encountered this bug, which might be the issue.

**Comment by redguy999** [comment]
Seems github won't let me upload the zip file at all which is annoying.

**Comment by haveric** [comment]
> Seems github won't let me upload the zip file

I think the max size is 25Mb which is probably what you are running into. You can always host it on google drive (or some other file sharing service) and link it here.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-12274.
My completely naked character wielded light battery. Adjacent to me, on the ground, was a dive bag with a flashlight without battery. I pressed `r` and selected flashlight in a bag. I reloaded flashlight without any problems.
