### ISSUE TITLE
Sandpaper recipe

### ISSUE THREAD

**Issue by lfaga** [CleverRaven/Cataclysm-DDA#56269]
### Is your feature request related to a problem? Please describe.

The metalworking chisel and metal fileset recipes interlock each other. The chisel needs a tool with grind quality and the fileset uses the chisel.

### Solution you would like.

I propose to implement a sand paper recipe (maybe paper + superglue + sand) to break the chisel - fileset recipe deadlock.

**Comment by TheShadowFerret** [comment]
https://nornagon.github.io/cdda-guide/#/item/stone_polishing
https://nornagon.github.io/cdda-guide/#/item/scraper_steel

There is no deadlock 🤔

**Comment by Sathra225** [comment]
Actually its only the Polishing Stone that doesn't need a chisel or fileset to craft of all the Grinding 2 tools.
The electric polisher is also Grinding 2 but is non-craftable.

**Comment by catdach** [comment]
> > https://nornagon.github.io/cdda-guide/#/item/stone_polishing https://nornagon.github.io/cdda-guide/#/item/scraper_steel
> > There is no interlock 🤔
> 
> I was in a lab start scenario. I had no "large rock" available, nor the books with the scraper steel recipe. Anyways, a sand paper recipe seems pretty reasonable request.

Ok so, asking for a sand paper recipe is fine, but please don't say that there is a problem like interlocking recipes when there isn't one. Not having access to a "large rock" in a challenge scenario does not make these recipes are interlocked

>nor the books with the scraper steel recipe.

You shouldn't need a book, the recipe is auto learned at fabrication 4 (which is also when you auto learn the recipes for the metalworking chisel and metal fileset)

Even if they were interlocked, I'm not even sure how sandpaper would help you as it only has filing 1, and you need a tool with grinding 2.

Also we already have a recipe for sand _leather_ which makes a sand paper recipe kinda unnecessary.

**Comment by lfaga** [comment]
Well, then close the request... sand leather?

> > > https://nornagon.github.io/cdda-guide/#/item/stone_polishing https://nornagon.github.io/cdda-guide/#/item/scraper_steel
> > > There is no interlock 🤔
> > 
> > 
> > I was in a lab start scenario. I had no "large rock" available, nor the books with the scraper steel recipe. Anyways, a sand paper recipe seems pretty reasonable request.
> 
> Ok so, asking for a sand paper recipe is fine, but please don't say that there is a problem like interlocking recipes when there isn't one. Not having access to a "large rock" in a challenge scenario does not make these recipes are interlocked
> 
> > nor the books with the scraper steel recipe.
> 
> You shouldn't need a book, the recipe is auto learned at fabrication 4 (which is also when you auto learn the recipes for the metalworking chisel and metal fileset)
> 
> Even if they were interlocked, I'm not even sure how sandpaper would help you as it only has filing 1, and you need a tool with grinding 2.
> 
> Also we already have a recipe for sand _leather_ which makes a sand paper recipe kinda unnecessary.

You are right, sandpaper has filing... didn't noticed it... So it's even worse, there's no way to make a chisel without a big stone. Also, I was checking the steel scraper recipe... it requires the use of a metal fileset... Isn't a little silly to require a qrind 2 tool to make another grind 2? This filing - grinding stuff feels half baked... The other fabrication stuff flows so nicely, starting in a lab with nothing I ended forging my own tools, but i couldn't make a silly fileset... Thank god the pickaxe didn't needed one so in the end I managed to escape.
