### ISSUE TITLE
Physical activity should produce extra body heat

### ISSUE THREAD

**Issue by Marrim** [CleverRaven/Cataclysm-DDA#56274]
### Is your feature request related to a problem? Please describe.

Currently it appears impossible to get warm by doing any sort of physical activity, despite in reality it being the most obvious short-term solution. And performing hard work in an already hot environment seems to not cause any extra sweating or overheating compared to standing still in a hot environment.

### Solution you would like.

Expending calories should raise body heat appropriately.

### Describe alternatives you have considered.

Alternatively, do not raise body heat but instead adjust the optimal temperature based on current physical activity level.

### Additional context

Easily tested by doing a winter start and selecting the "exercise" activity. The effect on warmth is either not noticeable, or not present at all.
Also, when you shiver, that's a reflex by which your body tries to generate more heat. One might want to consider simulating that aspect as well.

**Comment by Shibimon** [comment]
Maybe is not enough as it should to prevent the cold, but crafting or doing weary activities during normal and hot climate definitely affect your temperature.
And i think that indeed shivering should raise the player temperature, and also being wet from swet decrease it, and if they already do those things, it should be a bit more noticeable.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
