### ISSUE TITLE
Inconsistent damage location reporting

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#56277]
### Describe the bug

Making a "headshot" which is reported to hit the leg, resulting in bleeding from the head.

### Steps to reproduce

1. Fire at a zombie with a bow (the weapon probably doesn't matter)
2. Keep doing so until you get a "Headshot!" report.
3. See the following report state that the hit location isn't the head (arm and leg seen just now), or repeat the earlier steps until you do.
4. Aim another shot at the zombie, and see bleeding from the head.

### Expected behavior

The reported hit location should match the location that's actually caused to bleed, and it probably shouldn't be called a Headshot unless it hits a/the head, but it actually seems to hit the head.

### Screenshots

![Screenshot (227)](https://user-images.githubusercontent.com/22739822/159231639-8ce49578-5d99-4f92-9d2d-73301a0a8370.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1586 (21H1)
- Game Version: 53f9bd3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
+ JSON hack to disable portal storms, as the PR that made it a mod was rejected.

**Comment by Night-Pryanik** [comment]
Resolved by #56104.
