### ISSUE TITLE
Generic mutagen should be able to cause mutations by itself

### ISSUE THREAD

**Issue by SariusSkelrets** [CleverRaven/Cataclysm-DDA#56280]
### Is your feature request related to a problem? Please describe.

The new mutation system made that you can't mutate with generic mutagen no matter how much you took if you don't take targeted mutagen too

I feel like allowing the player to not choose a path and simply chug untargeted mutagen then see what happens, as it was possible before, should be a feature of the game

### Solution you would like.

Generic mutagen causes mutations even without targeted mutagen in the organism

It would also allow players to mutate as soon as they find basic mutagen

### Describe alternatives you have considered.

Letting new players try to learn what exactly is "exotic mutagen" by themselves

**Comment by MylieDaniels** [comment]
My goal is to address this in a different manner as I continue to rework mutations and mutagen.  An overhaul to mutagen crafting and acquisition is in the works, and I understand this is a semi-awkward period for mutagen in terms accessibility.  I'd rather not make changes that will be reverted by the next step in the larger process, but I will quickly move part of one of the pending features to a small PR that should make this nicer to work with.
