### ISSUE TITLE
Impossible quest from an NPC (season-locked)

### ISSUE THREAD

**Issue by OnTheDouble** [CleverRaven/Cataclysm-DDA#56298]
### Describe the bug

An NPC gave me a quest to gather 80 cattail stalks but they are only available outside winter. It's day 12 of winter right now.

### Steps to reproduce

1. Meet an NPC in the winter.
2. Ask to help them.
3. Get cattail stalk quest.
4. Try to harvest cattails.
5. Only get roots but not stalks. Quest is soft-locked until spring.

### Expected behavior

Expected behavior would be to check season before giving a season-dependent quest.

### Screenshots

![image](https://user-images.githubusercontent.com/82908191/159518441-7c75eab2-c963-4613-b76a-84175e01aa31.png)
![image](https://user-images.githubusercontent.com/82908191/159518527-e0e6d7ce-6835-4de3-adde-1f5a97d301f5.png)

### Versions and configuration

2022-03-22-0540

**Comment by oosyrag** [comment]
Considering the other starting quest is to kill one of the toughest enemies in the game, I'd say that the NPCs don't particularly care about your ability to complete their quests at all.

**Comment by Night-Pryanik** [comment]
AFAIK there's currently no way to set conditions for missions to start, so it's not a Good First Issue at all.
