### ISSUE TITLE
[magiclysm] zowlbear predator spawning on day 1

### ISSUE THREAD

**Issue by esotericist** [CleverRaven/Cataclysm-DDA#56307]
### Describe the bug

on day 1 of a new magiclysm run encountered a zowlbear predator

### Steps to reproduce

1. start magiclysm world
2. drive around 
3. find terror in magic zombie form

### Expected behavior

i would expect evolved owlbear zombies to be showing up later than day 1, since owlbear zombies are already terrifying enough

### Screenshots

![image](https://user-images.githubusercontent.com/1569754/159645772-1cfe7695-5e3c-4bf6-a2e2-22f10174f8bd.png)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.4 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-6872-g4292c96862 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    eso_ui_bits_msx [eso_ui_bits_msx],
    Magiclysm [magiclysm]
]

### Additional context

if evolved zombie owlbears can spawn on day 1, there might be other critters that can, too. i haven't looked deeply at it tho

**Comment by Fris0uman** [comment]
I think this https://github.com/CleverRaven/Cataclysm-DDA/blob/776eb720661d8b486deda73144f58f0546cddb7c/data/mods/Magiclysm/monstergroups.json#L66
is likely to be the culprit
