### ISSUE TITLE
Steel scraper recipe shouldn't require metal fileset

### ISSUE THREAD

**Issue by catdach** [CleverRaven/Cataclysm-DDA#56301]
### Is your feature request related to a problem? Please describe.

The steel scraper is an alternative to the polishing stone and as a relatively simple tool with the `grinding 2` quality. The problem is that the recipe for the "steel scraper" requires the "metal fileset", an item which _itself_ has `grinding 2` so there would never be a reason to make a "steel scraper". I don't know enough about metal working to say with confidence what _should_ be required to make this tool, but it probably shouldn't need a tool that is superior to it in every way, as that makes it's existence pretty redundant. 

### Solution you would like.

Have the recipe require, _at most_, `grinding 2` instead of the fileset. (could be grinding 1, but no tools have grinding 1)

 If it really needs a tool with `filing 2` then there should probably be some more tools with that quality, as the only one with that currently is the metal fileset. Having it be grinding 2 still has the problem that it's a tool with grinding 2 that needs grinding 2; However, while the polishing stone is very easy to make, it is also very large and heavy, so the steel scraper would be useful in that it is much easier to carry around.

### Describe alternatives you have considered.

replacing the metal fileset from the `"blacksmithing_standard"` requirements group with the grinding quality, and possibly the filing quality.

giving sandpaper and sand-leather `grinding 1` (the steel scraper recipe would still need to be changed though).

replacing the filing quality with grinding entirely.

removing the steel scraper item.

### Additional context

Was pointed out that the steel scraper was hard to get to (as well as some other metal working tools) in #56269

The steel scraper was added in #51698

I had some trouble finding real world examples of this tool (googling "steel scraper" result in tools for paint and drywall), The closest I could find was [this ](https://www.anvilfire.com/21st-century-blacksmithing/basic-tools/Chinese/draw-horse/)traditional Chinese/Japanese metalworking tool, the Japanese word for it is apparently "Sen"? maybe all you need is that bit in the middle that actually contacts the metal? Idk, I have very little experience with metal working in general, much less ancient techniques from China and Japan.

oh, I also found [this ](https://www.reddit.com/r/woodworking/comments/3gu1ac/is_this_guy_using_a_draw_knife_to_shape_metal/)reddit thread which may or may not be relevant. 

Regardless, it seems like a simple enough tool that wouldn't need very complex tools to make it.

**Comment by Sathra225** [comment]
From looking up how Sen are made, there doesn't seem to be a way to make them without using a grinding tool (polishing stone at minimum). Particularly for what grinding 2 does. They're hard steel too, so the recommended base to make your own is a metal file...
Apparently they can be sharped to a rough grit, but that seems to be for Sen used for rough cutting (more like filing). So maybe with sandpaper? There's 2 recipes that call for grinding 1 as well (plastic shank and zinc powder).

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
