### ISSUE TITLE
Unarmed Damage ignores worn fist weapon and Ki Strike

### ISSUE THREAD

**Issue by Heitomos** [CleverRaven/Cataclysm-DDA#56312]
### Describe the bug

I made a new character with Ki Strike, but level 0 Unarmed to have something of a martial arts rise. However, I've noticed my damage never increases, regardless of what I do. I've tried Brawling, Boxing, and Pankration against a Fat Zombie I was spawning in. With or without Ki Strike my damage is the same. I also spawned in some Impact Knuckles and Skewer Knuckles. Wearing them did nothing to affect my damage, but they worked when I Wielded them, which isn't how they are supposed to work now.

### Steps to reproduce

1. Make a character with Ki Strike, 14 Strength, and Unarmed 10.
2. Spawn Impact Knuckles and Skewer Knuckles.
3. Spawn a Fat Zombie
4. Punch it to death
5. Swap weapons and repeat from step 3.
6. Damage is tiny across the board.

### Expected behavior

Wearing fists and Ki Strike should both (edit: but independently, they don't stack) increase my overall unarmed damage.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19042.1586 (20H2)
- Game Version: b87878f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Generic Guns [generic_guns],
    Mythical Martial Arts [MMA],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex]
]

**Comment by oosyrag** [comment]
Duplicate #56138
