### ISSUE TITLE
Jay Rucker's second mission fails to generate target

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#56315]
### Describe the bug

When asking Jay if he wants something done after having completed his first mission and accepting a new mission an error is generated.

 DEBUG    : Unable to find and assign mission target radio_tower_1.

 FUNCTION : find_or_create_om_terrain
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\mission_util.cpp
 LINE     : 251
 VERSION  : 53f9bd3

followed by:

 DEBUG    : Mapgen update function called with overmap::invalid_tripoint

 FUNCTION : update_map
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\mapgen.cpp
 LINE     : 7620
 VERSION  : 53f9bd3

The latter message is probably just a result of the failure to generate a proper location as reported by the first mission.

### Steps to reproduce

1. Hand in the USB for the first mission.
2. Save (optional)
3. Ask if he needs something else done.
4. Accept the mission.
5. Get the error report.

### Expected behavior

Mission generated successfully.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1586 (21H1)
- Game Version: 53f9bd3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
+ Hack to disable portal storms as the mod to do so was rejected.

### Additional context

A Hub01 has been found a fair distance to the north of the pair's location, although it hasn't been visited, and most towers I've been able to get to have been climbed. Most of the map south of the pair's location remains unexplored.

I've tried to ask for the mission 3 times (by closing the game and loading the latest save) and it fails the same way every time.

**Comment by a-chancey** [comment]
This one failed for me yesterday so I debugged it, and the following one also failed to place the robofac location.

**Comment by bombasticSlacks** [comment]
yeah this was just a mistake with his base def. I thought I fixed this weeks ago... I'll push a fix now, He just isn't supposed to have a second quest.
