### ISSUE TITLE
Stamina/Exhaustion System for living creatures NPC

### ISSUE THREAD

**Issue by scraw-darkblade** [CleverRaven/Cataclysm-DDA#56318]
### Is your feature request related to a problem? Please describe.

Most of the living creatures are very fast like deer, birds and we get it but it seems these creatures are running forever without tiring. It is not even real. Which I think should be implemented.

### Solution you would like.

Living creatures in CDDA should tire/exhausted because that's the way it should be.

**Comment by Theawesomeboophis** [comment]
Adding onto this a bit, I would love a system where animals sleep if it's possible.

**Comment by AcidAntOnAMinefield** [comment]
Adding to this:
Enemy creatures / NPCs should also be affected by weather conditions and temperature. It makes no sense that the player is the only single living being in this world that suffers penalties for that.

- Too Cold? You're slow now.
- Too Warm? You're slow now. 
- Damp Mouth? No point in living anymore. 
- A little bit sweaty? Guess there's no point in living anymore too.
