### ISSUE TITLE
Crafting variations

### ISSUE THREAD

**Issue by Drew4484** [CleverRaven/Cataclysm-DDA#56326]
### Is your feature request related to a problem? Please describe.

Crafting (non-food) items currently requires a separate entry for every variation (material, size). This leads to menu bloat, the new plate and chainmail options result in close to two hundred entries. Many other items have at least three crafting options (standard, XL, XS). 

### Solution you would like.

Crafting menus allowing selection of size and material would simplify our menus and make more variant items manageable. Using the example of light plate armor:
**Current**
1. In the crafting interface, navigate to armor suits, see 30 variants of plate mail suits.
2. Decide what grade of steel to make armor from
3. Check for XL/XS variant
4. Select "Light tempered steel plate armor"
5. Craft
**Proposed**
1. In the crafting interface, navigate to armor suits, see "Light plate armor", "Plate armor", and "Heavy plate armor".
2. Select "Light plate armor"
3. Menu pops up, prompts selecting material to use. Possibly show difference in stats?
4. Selecting material prompts size selection. Shows material costs.
5. Craft

This proposal does not remove any number of steps but does cut down on the number of recipes to look through. This would make recipe list bloat a non-issue if we wanted to add more scrap steel items for a starting survivor, or things like ballistic plate inserts. We could also use this to use other metal options like bronze as crafting options without requiring separate menu entries.

### Describe alternatives you have considered.

The alternative to this is to just keep adding items and variants, which doesn't break anything, just makes selecting the right item for the player difficult.

### Additional context

This might require a new JSON entry, something like `"Variant_of": "armor_lc_lightplate"` to distinguish which items would appear in the submenu.

**Comment by Jarewill** [comment]
I must say, this is very needed in my opinion.
I think the armor updates you are working on are great, but the amount of bloat added to the crafting menu has been really annoying.
This would solve a lot of my issues with the current implementation.

**Comment by Terrorforge** [comment]
As I expounded on in #53496, I think the ideal would be to do this programmatically in as far as possible. Sure, it's a problem the the player is faced with hundreds of near-identical entries in the crafting menu, but it's an almost equally big problem that the devs are faced with hundreds of near-identical entries in the files. E.g. if you wanted to edit the thickness of plate armor right now, you would have to go in and manually change dozens of entries spread across several different files.

I don't think you could solve 100% of variant item problems programmatically so some kind of "variant_of:" function would still be necessary, but for something like armor materials it should be entirely possible to make a system where you have one entry for the item that has Material entries along the lines of "type: lc_steel OR mc_steel OR ..."

**Comment by Drew4484** [comment]
This is effectively resolved by @bombasticSlacks and @ANickelN's work on nested recipes.

**Comment by Zireael07** [comment]
@Drew4484: This is only a solution from UI/UX point of view. If a dev wanted to create, e.g. several different plate armors, or several sword variants, they still need to create lots of item/recipe entries.

**Comment by Drew4484** [comment]
> @Drew4484: This is only a solution from UI/UX point of view. If a dev wanted to create, e.g. several different plate armors, or several sword variants, they still need to create lots of item/recipe entries.

I agree and I'm in the middle of adding a ton of recipes, which sucks to do. But at least now I can add them without players sending me pictures of my front door.
