### ISSUE TITLE
Platinum grille requires too much platinum

### ISSUE THREAD

**Issue by YourCompanionCube** [CleverRaven/Cataclysm-DDA#56321]
### Describe the bug

The crafting recipe for a platinum grille requires 100 platinum, which is 5 liters and 1 kg, to electroplate a steel grille with just enough to act as a catalyst in chemical reactions (and another oddity is that it's only used in nitric acid, where straight platinum is used in several other recipes as a catalyst but that's not the point of this issue specifically)

The stated weight difference between the steel grille and the platinum plated one is also only 60 grams, which still seems a bit high to just be a layer of plating

### Steps to reproduce

n/a

### Expected behavior

That a more reasonable amount would be required, especially with the amounts you get from breaking down platinum jewelry being comparatively low and mufflers (standing in for catalytic converters) being even lower

### Versions and configuration

Latest experimental as pulled from Hitchhiker's Guide to the Cataclysm

### Additional context

[Platinum](https://nornagon.github.io/cdda-guide/#/item/platinum_small)
[Platinum grille](https://nornagon.github.io/cdda-guide/#/item/platinum_grille)
[Steel grille](https://nornagon.github.io/cdda-guide/#/item/steel_grille)

**Comment by a-chancey** [comment]
Platinum is inexplicably defined as "ammo" and has a stack size of 200

This means that 200 units of platinum are the item's defined volume of 50ml - so it's only 25ml per 100 units.

However, it is 5g per unit so 100 is 500g of platinum needed total, which means it's wasting 88% of the platinum while plating
