### ISSUE TITLE
UPDATE: Fire drills neither show charges nor take damage from use. Again.

### ISSUE THREAD

**Issue by OnTheDouble** [CleverRaven/Cataclysm-DDA#56340]
March 21 update fixed the issue with fire drills not showing signs of use. The bow fire drill began taking damage with use. ![image](https://user-images.githubusercontent.com/82908191/160121389-aa4250b2-03e1-4b60-b681-973d2cf38184.png)

It's March 25 and I no longer see fire drills take damage or show charges. Please investigate.

[Link to the previous issue somehow didn't go through.](https://github.com/CleverRaven/Cataclysm-DDA/issues/56219)

**Comment by ZhilkinSerg** [comment]
Why did you close the original issue? It was not resolved. Linked PR with the fix was not even merged yet.

**Comment by OnTheDouble** [comment]
True but as you can see I was satisfied with the new mechanic of fire drills taking damage. I thought it would conflict with my proposed solution of showing charges so I closed it.

**Comment by Croisis** [comment]
I've missed the taking damage fix completely TBH but wouldn't it be kinda weird to be able to fix a plank with burned holes in it with just duct tape (using the misc repair kit since it is wood material)? Unless it also got a NO_REPAIR flag...?
I see nothing in the fire.json history related to durability damage either so color me confused...

**Comment by OnTheDouble** [comment]
Yep that's why I closed it. I saw a new working mechanic despite your fix not getting merged and thought someone else got a different idea and fixed it in another way. Count us both confused I guess.

**Comment by Croisis** [comment]
I've updated the description of the original pull request to also cover this issue as well.

**Comment by OnTheDouble** [comment]
Just an update to show you that [even Rycon struggles to understand why a completely fine bow fire drill suddenly stops working](https://youtu.be/exrsThvtXEs?t=249). This is poor UX and needs improving.

**Comment by Maleclypse** [comment]
Closed by #56219
