### ISSUE TITLE
skull pig (undead boar) flees when injured despite being zombie

### ISSUE THREAD

**Issue by esotericist** [CleverRaven/Cataclysm-DDA#56352]
### Describe the bug

watched a skull pig flee from a police bot after taking some damage.

### Steps to reproduce

1. harassed eyebot
2. police bot happened
3. kited police bot away from operational area 'cuz i had wasps to kill
4. found skull pig
5. kited police bot to skull pig
6. watched skull pig run away after the fight started

### Expected behavior

boars are pretty well renowned for their insistence on fighting well past any reasonable point while alive. an undead boar should very well have the opposite of survival instincts.

### Screenshots

![image](https://user-images.githubusercontent.com/1569754/160224046-3fd86bf7-2d51-4648-8340-5c2e343ec1e6.png)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.4 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-7043-ga1c5d0a9c5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    eso_ui_bits_msx [eso_ui_bits_msx],
    Magiclysm [magiclysm]
]

### Additional context

build is master as of cdda-experimental-2022-03-25-1951, i just compiled it locally 'cuz it was less hassle than downloading one. weird how that works.

**Comment by Maleclypse** [comment]
So weirdly it copies from `"mon_zombie_pig"` so I'm wondering if they both will run or only the skull pig?   I'm assuming this is related to whatever causes #54002

**Comment by RoyBerube** [comment]
The skull pig has the hit and run flag added. That might explain the running away part.

**Comment by Maleclypse** [comment]
I moved this to needs confirmation as I intended for the hit and run behavior.   The only way this is an actual bug is if they flee and never return in which case it's a problem with the hit and run flag.

**Comment by Maleclypse** [comment]
![fleshraptor](https://user-images.githubusercontent.com/54345792/160524282-7d75b80f-fe86-4c05-a9f6-5f817e75ffdc.png)

The Flesh Raptor also shows as fleeing when it is only repositioning during a hit and run attack.
