### ISSUE TITLE
Wilderness survivor armour

### ISSUE THREAD

**Issue by Sathra225** [CleverRaven/Cataclysm-DDA#56379]
### Is your feature request related to a problem? Please describe.

Without Kevlar, the arguably iconic Survivor armour series (or kevlar jumpsuits now) isn't possible. I'm not actually sure if its possible to make 100% coverage normal layer armour without uncraftable materials that isn't extremely hot (gambeson).

### Solution you would like.

Making something similar (but obviously worse) out of leather, cloth, chitin and steel. Possibly a second line from biosilicified chitin.
Essentially a cloth jumpsuit with leather padding plus chitin and/or steel reinforcing high-risk areas. So a jumpsuit with chitin/leather lamellae/scales and steel plates over vitals. Or steel plates are only in the heavier versions, and its chitin for the others.
Not sure what to call it though. Wildcraft jumpsuits? Wilderness survivor (blank)?

### Describe alternatives you have considered.

Not sure, these are basically just jumpsuits with plating. It could be leather reinforced jumpsuit, chitin reinforced jumpsuit and steel reinforced jumpsuit.
Maybe have them be crafted from the preceding version.
Could use bronze instead of steel because...more bronze uses?

### Additional context

Honestly, this is something I've been thinking about for the Innawoods mod. I like the basic idea of survivor armour (handcrafted protective gear for a new world), and not being about to make it saddens me a little.
Wanted to get some feedback first though.

**Comment by NetSysFire** [comment]
I'd like to see bark armor, you sew layers of bark onto thick cloth for some weak makeshift armor.

**Comment by anothersimulacrum** [comment]
CC @Light-Wave

**Comment by Sathra225** [comment]
Yeah, been waiting for the tailoring stuff to settle down before working on this. The bark armour though...maybe rattan-style instead, like was used in various pre-colonial cultures? Would need something applied to it to protect from rot, maybe rosin or something like lacquer.

**Comment by NetSysFire** [comment]
I could not find sources that state that bark armor was really used in real life. Paper armor was used in China but when I search for bark armor I mostly get results for mmorpg armor sets.

**Comment by Sathra225** [comment]
yeah, that's why I suggested rattan-esque armour. Also known as wicker armour. Its roughly like a tightly-woven basket in the shape of a cuirass and other armour pieces.
I'm just not sure how good it was. I think it would be roughly like the paper-lamellar armour effectively (good vs piercing, okay vs cutting, poor vs bashing).

**Comment by NetSysFire** [comment]
I have thought about layering birch bark. Birch bark should be reasonably flexible, similar to paper. Layer it and you potentially got a decent-enough result.

**Comment by Sathra225** [comment]
Hmm, I thought it was more like cardboard.
Thinking about it, with some glue, and some way to stitch them them together and compression...you could make something like an o-yoroi. Overlapping plates on a harness kinda thing. It'd be pretty heavy though.

**Comment by Light-Wave** [comment]
I'm not terribly interested in adding bark armor to the Innawood mod. I think such a thing should be in mainline or not at all.

That being said, we already have 2-by-arm guards made of pieces of wood strapped to your arm in both mainline and Innawood. I could see a case for adding leg guards and maybe a chest plate made of wood [(like this?)](
https://i.pinimg.com/564x/5c/c3/11/5cc311e6c5d5787ee17365b2e558662b.jpg) to mainline.

**Comment by Sathra225** [comment]
Ah yeah, will have to fix that at some point too. Getting cotton patches early in Innawoods isn't obvious (it involves making a clothing item or sheet out of fibercloth, then cutting it up and cutting up the patchwork cotton sheet).

**Comment by evankimori** [comment]
> Ah yeah, will have to fix that at some point too. Getting cotton patches early in Innawoods isn't obvious (it involves making a clothing item or sheet out of fibercloth, then cutting it up and cutting up the patchwork cotton sheet).

Thanks for answering this. I was wondering how the CotPat system worked as it's pretty vague in areas and was considering doing an Issue ticket for it. Thanks for the hard work anyway on the system changes and hope that a solution can be added soon. :)

At least now I can stop mad rummaging bushes wondering why Cotton Seeds weren't spawning. XD
