### ISSUE TITLE
Fit-over sunglasses cannot be worn over corrective glasses

### ISSUE THREAD

**Issue by Ilysen** [CleverRaven/Cataclysm-DDA#56384]
### Describe the bug

Fit-over sunglasses are no longer wearable over corrective glasses due to them both being classified as rigid. Because the game strictly prevents you from wearing two rigid items on the same body part, they can no longer be worn together, even though fit-over sunglasses are explicitly designed to be worn over corrective glasses.

### Steps to reproduce

1. Spawn in some corrective sunglasses and fit-over sunglasses.
2. Put on one item or the other.
3. Observe that you can no longer wear both items at the same time; you'll get a notification that you can't wear two rigid items over your left eye.

### Expected behavior

Fit-over sunglasses are designed specifically to be worn over corrective lenses, hence the name. They should be wearable together.

### Screenshots

![image](https://user-images.githubusercontent.com/47678781/160286770-9dffb34c-8597-4ea4-9e39-bd15b1caf082.png)
![image](https://user-images.githubusercontent.com/47678781/160286774-2b259212-81ff-4516-876d-c4b7332264b8.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1586 (21H2)
- Game Version: https://github.com/CleverRaven/Cataclysm-DDA/commit/0cc5c0532ed9c6cade64d035cc83fced659604a8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    No Rail Stations [No_Rail_Stations],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth]
]

### Additional context

I'm fairly certain that this is a direct result of #55566.

**Comment by lfaga** [comment]
I have only the default mods and having the same issue. I was reading the PR... great! More useless complications instead of actual game content...

**Comment by TheShadowFerret** [comment]
Additional conflicts: Riot helmet, safety glasses, motorcycle helmet w/ visor down

**Comment by Theawesomeboophis** [comment]
Would Adding the Outer_Layer flag to these items fix this, or would that cause more problems?

**Comment by bombasticSlacks** [comment]
They should just have a new flag for compliant with other rigid armor. I figured I would miss some obvious stuff, I'm also planning on making a Reddit post about this.
