### ISSUE TITLE
NPC conversations should gray out once you've exhausted all options, until new dialogue gets added

### ISSUE THREAD

**Issue by haveric** [CleverRaven/Cataclysm-DDA#56385]
### Is your feature request related to a problem? Please describe.

When talking to an NPC with a lot of conversation topics, it can become confusing as to what you've already inquired about or when a new topic has been added that you haven't discussed.

### Solution you would like.

Some kind of `read`/`unread` status set for conversations. When unread, the text stays the current white color. When read (or all children topics have been read), it changes color to gray. 

I'm not sure on the easiest solution to implement this, but I can see where there would be times it would be wanted and others where it wouldn't (NPC commands for example wouldn't want this).  This might mean a variation of `talk_topic` would be created that tracks `read` status and/or dialogue variables could be used to manipulate. I'm sure this is going to cause all kinds of headaches to implement, but from a player's perspective, this would be a huge quality of life improvement.

### Describe alternatives you have considered.

Manually doing this with dialogue variables for some conversations.

**Comment by chrispikula** [comment]
I would think that this _shouldn't_ be the case for follower orders, but, yeah, I like this.

**Comment by haveric** [comment]
> I would think that this _shouldn't_ be the case for follower orders, but, yeah, I like this.

Agreed. I mentioned this with "NPC commands for example wouldn't want this". I'm sure there are other cases that would be exceptions as well, such as trading.

**Comment by PatrikLundell** [comment]
It would certainly be useful if this info was persistent, as I currently keep checking for whether NPCs have any tasks for me in case something has triggered one to actually appear, and having it greyed out until there actually is a change of the underlying state would be rather convenient.

It can be worth keeping in mind that the dialogs in the game probably aren't the complete extent of the conversations held, but rather a compression down to the essential parts, skipping talk about the weather, general state of things, etc., so knowing that there is something new to "officially" ask about shouldn't be considered magically knowing it: the NPC probably hinted at it somewhere in the "unrecorded" conversation.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
