### ISSUE TITLE
Looking at the shoulder strap or its recipe crashes the game

### ISSUE THREAD

**Issue by TheShadowFerret** [CleverRaven/Cataclysm-DDA#56382]
### Describe the bug

Attempting to looking at a shoulder strap, its recipe, or attempting to remove one from a gun that spawns with it will crash the game.

### Steps to reproduce

1. Get fab 1 so you unlock shoulder strap recipe/find an unattached shoulder strap/pick a profession with a gun that has one.
2. Attempt to look at the recipe/look at the item/detach the shoulder strap or look at the gun.
3. Crash.

### Expected behavior

No crash

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.556 (21H2)
- Game Version: 0cc5c05 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[SStrapCrash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8357768/SStrapCrash.zip)
[WorldSettings.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8357775/WorldSettings.zip)

**Comment by Ilysen** [comment]
Can confirm that this is happening on commit `0cc5c05` as well.

**Comment by Kasgigz** [comment]
I have the same issue with 0cc5c05 too. Trying to inspect a weapon that has a shoulder strap already attached (like military profession spawn) will also crash the game

**Comment by tstormn3tw0rk** [comment]
Same issue with [0cc5c05](https://github.com/CleverRaven/Cataclysm-DDA/commit/0cc5c0532ed9c6cade64d035cc83fced659604a8), and since its at the top of the weapons tab it makes switching to that tab at all impossible for me

**Comment by rmzalbar** [comment]
Same behavior affecting gunmod/accessories/belt_clip as well
