### ISSUE TITLE
Charcoal smoker furniture multiplicates.

### ISSUE THREAD

**Issue by tinukedaya** [CleverRaven/Cataclysm-DDA#56397]
### Describe the bug

In my latest run through I settled in a Swamp Shack and while I tried to reload the smoking racks there with Charcoal a weird thing happened. They sort of multiplied... see screenshot. 

The other actually shown the Basecamp Charcoal Smoker twice (with one loaded with charcoal (there was also no way to get the charcoal out) and second empty). When I deconstructed it I received some sticks, rocks and 2x the Basecamp Charcoal Smoker item (could be unloaded, so I got the charcoal back). 

Also, first thing I noticed as weird was, that when I reloaded the smokers for the first time it did not work with the recipes. I tried to do some cooking and the crafting menu did not register the smoker as available heat source... 

### Steps to reproduce

I guess try to find the shack and try to reload it with charcoal. 

### Expected behavior

Reload the smoker with charcoal and use it while cooking and not multiplicate into other items. 

### Screenshots

![image](https://user-images.githubusercontent.com/19891532/160296297-cee92d66-6b70-4051-9aad-0d44516babed.png)

![image](https://user-images.githubusercontent.com/19891532/160296369-ddec78ec-34b4-483a-a577-a10e447f41c3.png)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0cc5c05 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    No Rail Stations [No_Rail_Stations],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Sathra225** [comment]
This happens with player-built smoking racks too. 
I tried deconstructing and rebuilding, but on reloading the newly built one with 2000 charcoal and 'Inspecting' it contained 2 empty 'basecamp charcoal smokers' and 1900 charcoal.

**Comment by FayFlightee** [comment]
![image](https://user-images.githubusercontent.com/71143790/160473166-11b6762e-6ecc-4f7a-a6bd-729842a9d0f9.png)
Uhhh.... yeah, same story here.

**Comment by FayFlightee** [comment]
I think #54870 PR is the cause.

**Comment by helpfulchicken** [comment]
I have this issue too. It seems to pull a basecamp kiln from a nearby player made clay kiln, in addition to smoker or forge. It can lead to charcoal duplication.

There doesn't seem to be any way to remove the basecamp items directly, but when I try to light the smoker, it declares that one of the present basecamp items is not valid food and spits it out. Doing that repeatedly eventually empties the offending items.

If the basecamp items have charcoal in them, it appears to lead to free charcoal.

**Comment by RoyBerube** [comment]
Playing the game over the weekend I was able to consistently get this dupe bug with the charcoal smoker. Now that I'm trying to debug it, I can not make it happen. 

And of course my character died and I deleted that world already. Sigh.

**Comment by Sathra225** [comment]
New interesting bit of info: In my current game, I've found that it will always spawn at least one (sometimes 6) 'basecamp charcoal smoker' if I reload a smoker with charcoal _off the ground_.
If I'm _carrying_ the charcoal, it works properly.

**Comment by FayFlightee** [comment]
Already solved by #56479 PR.
