### ISSUE TITLE
Allow crafting of cotton clothing parts from the components they dissasemble into (rags)

### ISSUE THREAD

**Issue by tstormn3tw0rk** [CleverRaven/Cataclysm-DDA#56392]
### Is your feature request related to a problem? Please describe.

Currently the only way to repair most clothes is with cotton clothing parts, and currently the only way to get cotton clothing parts is by dissassembling things that contain them. 

### Solution you would like.

Since cotton clothing parts dissassemble into rags, they should be craftable with rags too, or at the very least craftable in some respect

**Comment by Zireael07** [comment]
Unclear whether you want crafting or repairing to accept rags?

**Comment by robotic-gamer** [comment]
I think they want a more obvious way to turn rags into repairing clothing. currently it seems the only way to do that is the impractically slow: rag--->thread---->cotton sheet--->sheet--->patchwork cotton sheet--->patchwork cotton clothing part.

to solve perhaps:
rag--->thread type material--->patchwork cotton clothing part.

**Comment by Maleclypse** [comment]
#54256 should start contributing to this.
