### ISSUE TITLE
CTD when browsing through recipes

### ISSUE THREAD

**Issue by tinukedaya** [CleverRaven/Cataclysm-DDA#56399]
### Describe the bug

Seems like it's the Shoulder Strap recipe. when I try to display it I get CTD. 

### Steps to reproduce

- See attached save file, open the crafting menu > weapons and go down till you reach the Shoulder Strap
- Watch the game crash

### Expected behavior

Game not crashing when browsing through the recipes... 

### Versions and configuration

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8358320/crash.log)
[Shelter Bay.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8358324/Shelter.Bay.zip)

**Comment by TheShadowFerret** [comment]
Dupe of #56382

**Comment by tinukedaya** [comment]
Oh missed that one. Closing...
