### ISSUE TITLE
Hub 01 HWP CTD

### ISSUE THREAD

**Issue by Hegamonia** [CleverRaven/Cataclysm-DDA#56409]
### Describe the bug

Interacting with the Hub 01 Hybrid Weapons Platform (HWP) to either examine it from the inventory, or detach gunmods, causes the game to crash to desktop

### Steps to reproduce

1. Spawn in the Hub 01 HWP, plus the Sling mod
2. Attach the sling to the HWP
3. If the game has not crashed at this point, go into the inventory menu, and examine the weapon
4. Game should almost immediately crash to desktop without further warning
5. Alternatively, attempt to remove the mod from the weapon, which will cause Step 4 to occur

### Expected behavior

The Hub 01 HWP w/sling shouldn't crash the game to desktop

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19041.1415 (2004)
- Game Version: e699348 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Extra Mutated Scenarios [extra_mut_scens],
    Military Profession Pack [military_professions],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by bombasticSlacks** [comment]
a fix is already up for this I believe #56405

**Comment by Inglonias** [comment]
I compiled a version of e0dc297 with 56405 included. You can grab it here. https://www.dropbox.com/s/x81wtw1tcnupads/cataclysm-tiles-dirty.exe
