### ISSUE TITLE
Autodrive with bicycle crashes into obstacle

### ISSUE THREAD

**Issue by actually-a-cat** [CleverRaven/Cataclysm-DDA#56402]
### Describe the bug

In this specific situation, autodrive will crash the bicycle into a parked vehicle.

### Steps to reproduce

1. Load provided save file
2. `^` the bicycle you're standing on
3. Set autotravel to coordinates `0, 0'117, 0'86` (Y-intersection north-north-west of starting position)
4. `I`gnore the spider on the way
5. Be ejected from autodrive by colliding with an RV

### Expected behavior

The obstacle is easy to avoid, and if it can't be avoided, at least autodrive should bail out before crashing as it normally does.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19042.985 (20H2)
- Game Version: 3b9e1a3 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth]
]

### Additional context

[Marquette.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8358360/Marquette.zip)

**Comment by Sutremaine** [comment]
Reproduced in e31f874 using provided save.
