### ISSUE TITLE
Larwick Overmap doesn't display fast travel path

### ISSUE THREAD

**Issue by FinjyOpops** [CleverRaven/Cataclysm-DDA#56425]
### Describe the bug

Using Larwick Overmap, the Shift+W fast travel method still works, but it doesn't seem to display the path my character will follow.

### Steps to reproduce

1. Enable graphical Larwick Overmap in settings
2. Press Shift+W at the spot you'd like to travel

### Expected behavior

I expected it to show the path like other map options do.

### Screenshots

[Example](https://i.ibb.co/dg5QPj7/image.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.556 (21H2)
- Game Version: e0dc297 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by BoatNectar** [comment]
I've been experiencing this issue as well.

**Comment by Inglonias** [comment]
turns out the most recent commit to the tilesets repo two days ago solved this issue. I'll try to get you the composed tileset attached here so you can use it early, but know that next time there's a tileset update, this will be resolved.

**Comment by Inglonias** [comment]
[Larwick_Overmap.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8375739/Larwick_Overmap.zip)
This should resolve this issue until the next tileset update occurs.

**Comment by esotericist** [comment]
this has been resolved now that the tileset has been updated.
