### ISSUE TITLE
Women spawn with bra over shirt

### ISSUE THREAD

**Issue by FinjyOpops** [CleverRaven/Cataclysm-DDA#56424]
### Describe the bug

Women seem to spawn wearing their bra over their shirt. This is reflected by some of the tilesets, like MSXotto+.

### Steps to reproduce

1. Make a female character
2. Observe sprite or press + to view clothing layers

### Expected behavior

I expected underwear to be worn under.

### Screenshots

[Layers](https://i.ibb.co/64zMYWW/image.png)
[Sprite with bra](https://ibb.co/xh9Lphw)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.556 (21H2)
- Game Version: e0dc297 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by NetSysFire** [comment]
Potentially related: #55686
