### ISSUE TITLE
Hazmat unit does not spawn with hazmat suit. 

### ISSUE THREAD

**Issue by Smiles-5m1l35** [CleverRaven/Cataclysm-DDA#56436]
### Describe the bug

The hazmat unit profession does not spawn with the hazmat suit equipped. 

### Steps to reproduce

1. Spawn into world as hazmat unit
2. No hazmat suit

### Expected behavior

I expected that the hazmat unit profession would spawn with a hazmat suit but did not.

### Screenshots

![image](https://user-images.githubusercontent.com/102507376/160462148-1ff17b94-c25b-4a36-ae56-20d313c3376b.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1586 (21H1)
- Game Version: e0dc297 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by TheShadowFerret** [comment]
Now fixed by #56398.
![image](https://user-images.githubusercontent.com/99621099/161461425-312d11e2-c72a-4f46-9cf5-ec3bc6746900.png)
*Pokes close issue button*

**Comment by ducanishah** [comment]
Just verified on latest experimental! I would appreciate if this were closed to be off the "good first issues" list. :p
