### ISSUE TITLE
Add ability to clean yourself in a bath or shower  

### ISSUE THREAD

**Issue by Igryn** [CleverRaven/Cataclysm-DDA#56445]
### Is your feature request related to a problem? Please describe.

Currently the only way to clean your wounds is antiseptic, using soapy water is not really the thing people do in the way we use antiseptics. Soap and other detergents were crucial in medicine after adopting them but cant be used in game for the same purpose

### Solution you would like.

Add an ability to take baths, showers or even washing yourself in any sufficiently big body of water. It could be done with or without soap with different levels of effectiveness, or only with detergents. Ideally it could provide a way to clean wounds, speed up healing the same way antiseptics doo.

### Describe alternatives you have considered.

Leaving it as is or treat soapy water as mild antiseptic

### Additional context

It could provide small morale boost similar to the way eating at the table does. Some traits also could be implemented regarding how hygiene affects your morale.
Also could affect how smelly your character is depending if he washed recently
If you wash in some other liquid like raw sewage it could maybe apply some negative effect to your wounds

**Comment by Igryn** [comment]
To avoid problems with plumbing systems structures like manually filled shovers could be added, which may appear as naturally of constructible buy player

**Comment by BoatNectar** [comment]
These might be found nearby campgrounds and campsites.

**Comment by AcidAntOnAMinefield** [comment]
> Currently the only way to clean your wounds is antiseptic;

Taking a shower or a bath should "help" in cleaning light wounds (scratches), but not the wounds that require usage of antiseptic, ie the "deep wounds"/bite wounds.

Although, we do have Alcohol Wipes in game, which work for that purpose as well.

**Comment by Igryn** [comment]
> > Currently the only way to clean your wounds is antiseptic;
> 
> Taking a shower or a bath should "help" in cleaning light wounds (scratches), but not the wounds that require usage of antiseptic, ie the "deep wounds"/bite wounds.
> 
> Although, we do have Alcohol Wipes in game, which work for that purpose as well.

Should also apply a healing boost. Its just common sense that if you don't wash yourself then ascratsches and wounds will heal not as fast
