### ISSUE TITLE
Dinomod dino nests conflict with Innawood

### ISSUE THREAD

**Issue by LyleSY** [CleverRaven/Cataclysm-DDA#56457]
### Describe the bug

Both Innawood and DinoMod mods have entries for the forest_water and forest extras lists in their regional_overlay.json . @Light-Wave confirms that neither is intended to cancel the other, but it looks like Innawood is completely overwriting DinoMod's version, blocking 30+ dino nests from spawning in mapgen. We think that's a bug.

### Steps to reproduce

Start a game with both DinoMod and Innawood enabled in worldgen. Teleport around in forests and swamps and see none of the 30+ dino nests spawn. See a million wasp nests instead. 

### Expected behavior

Fewer wasp nests and some dino nests

### Versions and configuration

Latest experimental

### Additional context

Thanks to all the players having fun with both mods, it's wonderful to see

**Comment by Light-Wave** [comment]
So I tested setting the weight of one of the nests to 300000, and that made it spawn. So there doesn't seem to be a bug that completely stops nests from spawning. Perhaps it's just a bit too rare?

Then again, I've been watching Rycon Roleplay playing with Innawood and Dinomod, and I don't think he have found a single dino nest, which he should have if they spawned correctly. So I'm not sure what is going on.

**Comment by LyleSY** [comment]
Interesting, thanks. Both mods are using the same chance: 20 and each dino nest has a weight of 30. 30*30 gives 900, so they should be showing up more than ponds or clay deposits in swamps and forests, unless I'm missing something important about how mapgen works which is very possible

**Comment by LyleSY** [comment]
Ha, new ep showed a nest. I think we're good here, the balance is just odd. Maybe I'm salty because my last test game spawned me next to two wasp nests.
