### ISSUE TITLE
Western Boots Unable to fit any holdout Pistol

### ISSUE THREAD

**Issue by TheLyca0n** [CleverRaven/Cataclysm-DDA#56456]
### Describe the bug

Boots currently act as a small pocket instead of a holster.

### Steps to reproduce

Spawn in all small holdout pistols and attempt to insert them into the western boots as a holster

### Expected behavior

Current description needs to be modified and the boots rebalanced for no holster or holster-able dimensions need to be modified to accommodate any firearm

### Versions and configuration

Latest experimental windows 10

**Comment by Meandering-Breviger** [comment]
Confirmed this happens tried the Bond Arms Derringer and the Jennings both under the western boots limit of 
```
"max_contains_volume": "250 ml",
"max_contains_weight": "600 g",
```
