### ISSUE TITLE
Casting recipes to re-include molds and crucibles

### ISSUE THREAD

**Issue by orbayyazanlar** [CleverRaven/Cataclysm-DDA#56473]
### Is your feature request related to a problem? Please describe.

Casting type production misses two steps at the moment: "how to smelt" and "where to cast" does not exist in recipes. Previously "swage and die set" had been serving this purpose. Sand casting mold is also usable, even more realistically with the changes I submitted in previous request. Recipes exist at the moment can be used only if you have a big, previously shaped metal part like a frame or an ingot. There is no way of shaping x amount of small parts of steel without smelting them first.

Let me explain step by step how we do casting at the moment:

- Metal smelts in forge (which do not have crucibles)
- Smelt metal is cooled down and preliminary shaped somewhere  (missing step)
- It is then shaped by tools like fileset, hotcut etc.

As stated, previously swage and die set has served this shaping purpose, crucible was missing all along. Now swage and die set has been removed from most recipes.

### Solution you would like.

a) Introduction of crucible to weapon crafting recipes that utilize "small pieces" of metal to simulate smelting.

b) Adding "swage and die set" and "sand casting mold" to casting recipes

### Describe alternatives you have considered.

Making different recipes for utilizing large parts of steel and small parts seperate, which is just a UI cluster. 

### Additional context

Sand casting mold and clay crucible are easy to make tools, which should be utilized more.

**Comment by Sathra225** [comment]
You don't cast steel like you do bronze or copper. Its heated till malleable then hammered into shape. While hot, it can also be forge-welded by...well, heating it up and hammering them together (with a flux and metal filing mix).
As I understand it, the swage and die sets are tools to shape hot steel around by hammering.

**Comment by orbayyazanlar** [comment]
While it is possible, heat fusing small materials would be much more arduous than smelting- and more brittle as well. I have studied metallurgy and worked in aluminium, steel, iron and copper casting industry, so believe me when I say it. 

Let me ask you, for a machete utilizes 40 scraps, 8 chunks or 2 lumps. Imagine heat fusing 40 pcs of scrap metal into a machete. It is just unfeasible. You CAN heat shape big parts into smaller ones at ease, but small to big is just not worth it- and would likely be brittle in any case.

There is also the fact that any "steel" you see around is either coated or painted to prevent corrosion- unless they are stainless steel of course. During smelting process these impurities are removed by forming a slag. There is a work in progress to implement this as well. What I am suggesting is in accordance with it.

**Comment by Sathra225** [comment]
That's...a completely different issue. That would be more restricting recipes to only using certain minimum sizes of base material. There are already recipes for converting scrap/chunks to chunks/lumps (which do use a crucible). Though I think the scrap/chunk/lump substitutions are meant to be abstractions for a required mass of metal. Same with how they skip any annealing/quenching/etc steps.
Also, doesn't steel melt at a higher temp than sand in the first place? How would a sand casting mold work for that? I'm not actually sure if the in-game forge options could even get to those temps realistically and it was just handwaved.

Note: I've also thought it was odd scrap metal was included in the recipes, but just assumed it was added to avoid demanding extra crafting steps (i.e. iron value = whatever). Either change (remove scrap, add crucible) sounds reasonable to me.

**Comment by orbayyazanlar** [comment]
Sand casting in steel is less used due to high requirements in automotive industry and there are more commercially viable production methods for other parts. There are indeed many casting methods and sand casting has the lowest strength compared to higher end techniques, yet it is still feasible for a DIY blacksmith. Ideal method would be to prepare a metal mold for the given shape- but that would both take time and annoy players. A skilled sand caster can carve any shape on sand with little effort. Feasible both gameplay wise and *close enough* in science.

Both sand and clay being easy to find materials, crucible and sand casting mold already being in the game, why not implement them to a wider degree?

Also my point in suggesting this was that there are missing steps in blacksmithing. We can either assume they are done *somehow* during process, or just add another tool for recipes.

**Comment by Sathra225** [comment]
Huh, more you know. Seems reasonable then.
