### ISSUE TITLE
EOD gear to spawn in military locations

### ISSUE THREAD

**Issue by orbayyazanlar** [CleverRaven/Cataclysm-DDA#56471]
### Is your feature request related to a problem? Please describe.

Currently EOD gear only spawn in police buildings. Military itself would always have a mine/explosive defusal unit- at least in a battalion formation.

### Solution you would like.

Adding spawn chance of EOD gear in (some) military locations, army base being the most likely candidate.

**Comment by TheShadowFerret** [comment]
There should also be an EOD profession ^_^

**Comment by jacobchess13** [comment]
Maybe add a chance for EOD gear to spawn in the minefield bridge extra?

**Comment by anoobindisguise** [comment]
EOD gear does spawn in at least SOME military locations - I frequently find them in TCL armories. Though not in bunkers or outposts from what I've seen.
