### ISSUE TITLE
Luggage cart falling forever creating lots of lag and smashing noises

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#56477]
### Describe the bug

There are hundreds of instances of a smashing noise occurring every second in the hotel south of my character. It began when I started burning down the bank. Not sure what's happening here. If I walk into the hotel, there is an incredible amount of lag.

EDIT: It looks like the source of the noise is a luggage cart trapped on a ledge above the hotel lobby, falling forever and making noises.

### Steps to reproduce

1. Load the attached save
2. Listen

### Expected behavior

Not this?

### Screenshots

![image](https://user-images.githubusercontent.com/2125926/160916361-3bc59a9f-b5b2-4060-995b-054f4ba8bd0e.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1586 (21H1)
- Game Version: 0b63322 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    No Vault [No_Vault],
    ASCIITiles overmap color fix [colors_fix_asciitiles]
]

### Additional context

Forgot to actually attach the save file.
[Charon.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8399420/Charon.zip)

**Comment by Inglonias** [comment]
I wanted to follow up by saying that this bug is really, really funny.

**Comment by RoyBerube** [comment]
Skylights have the NO_FLOOR flag. Removing that would solve the problem.

Pushing furniture onto a skylight just lets the item fall through without any issues. Any vehicle causes this bug. It looks like the vehicle is trying to break the skylight before falling but is not succeeding. Also the player cannot step onto a skylight without falling.

IMO removing the NO_FLOOR flag is the simplest solution. Skylights are built to be a lot stronger than a regular window - I think it is safe to assume that they can hold up to the odd item or weight of a person.

**Comment by NetSysFire** [comment]
Sort-of relevant: #27081
