### ISSUE TITLE
Sand Casting Mold recipe correction

### ISSUE THREAD

**Issue by orbayyazanlar** [CleverRaven/Cataclysm-DDA#56472]
### Is your feature request related to a problem? Please describe.

a) Sand casting mold is too small to accommodate the products it is made with, being 0,4L and 0,54 kg - there is no way you can cast a xiphos with 1,25 L of sand. 

Let us say you'll cast a sword blade that is 75 cm in length, you'll need at least +10 cms in each end to keep the mold stable - making the mold size for it 25 in width (adding blade's width), 20 in height and almost a meter in length. This equals to 50 L of sand. As unit per sand is 0.25 L, this makes 200 sand required to cast a blade. Much less would be required to cast a spearhead of course, but a median way can be found. 

Note that sand is reclaimable in sand casting.

b) Sand casting (in this case, "green sand") includes roughly 10% bentonite (clay) in volume as a binder

### Solution you would like.

a) Enlargening sand casting mold to be appropriate for  the weapons it can be cast with to a median size that will not be annoying, but still realistic.

b) Adding 10% clay requirement to recipe. For 50 liters of "green sand" example I said above, 45 L (180 pcs) sand and 5L ( 20 pcs) lump of clay would do.

### Describe alternatives you have considered.

Keeping the things as they are

### Additional context

I will be adding another request to greatly expand sand casting mold usages.

**Comment by Maleclypse** [comment]
I think large weapons sized molds should probably require a furniture version of the sand casting mold.

**Comment by RenechCDDA** [comment]
This seems to have been cleared up since the issue was opened. The base "sandcasting mold" requires 6.75L of sand, there are different sized molds, and all of them require some amount of clay in proportion to the sand.

Please open a new issue (or PR!) with specifics if you see any further problems like this.
