### ISSUE TITLE
Barbed Wire Damage or Slows Player Down

### ISSUE THREAD

**Issue by tonezdinny** [CleverRaven/Cataclysm-DDA#56485]
### Is your feature request related to a problem? Please describe.

There should be a action done to the player when walking over barbed wire. 

### Solution you would like.

I feel like when a player walks over barbed wire there should be something done with the player. I would say walking over barbed wire should slow down the player like it states when walking through long grass or at least warns (does damage) the player like in the same situation when walking in to a rose bush.

**Comment by Night-Pryanik** [comment]
Last I checked, barbed wire indeed slowed down and damaged player (and other creatures too).

**Comment by Night-Pryanik** [comment]
![изображение](https://user-images.githubusercontent.com/11132525/161436101-fe49552e-0651-45f9-8735-4b6d0a561670.png)

I got slowed down and I got bleeding when stepped on a barbed wire.

**Comment by Night-Pryanik** [comment]
Closing as requested stuff is already here.
