### ISSUE TITLE
Windowed Borderless mode minimizes on window focus change

### ISSUE THREAD

**Issue by rmrfslash** [CleverRaven/Cataclysm-DDA#56484]
### Describe the bug

If the "Fullscreen" option in Options -> Graphics is set to "Windowed borderless" the game should not minimize on alt-tab, start menu open, or any other window focus change.

### Steps to reproduce

1. Open CDDA -> Options -> Graphics -> Fullscreen set to "Windowed borderless"
2. Save changes and restart CDDA for setting to take effect.
3. Press the Windows key on a keyboard (or click on another window, anything that triggers a window focus change)
4. Observe CDDA get minimzed

### Expected behavior

CDDA should not be minimized (when in  "Windowed borderless" mode).

### Versions and configuration

OS: Windows 10 Pro version 10.0.19042 Build 19042
CDDA Version: 3d0002b

**Comment by Qrox** [comment]
Borderless window was reported in #45902 to obscure other windows and the desktop after losing focus, and pressing `win+d` in game does not return user to the desktop, so it was changed in #50360 to minimize on focus loss. It would be nice if we can treat alt-tab, `win` and `win+d` differently but I don't know how that can be done.

**Comment by rmrfslash** [comment]
@Qrox Thank you for the context. My opinion is that borderless window mode must have `SDL_SetHint(SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS, "0" );` otherwise there really is not point to have this option in the settings.

I believe you can handle cases like `alt-tab`, `win`, and `win+d` manually in your `input_manager::pump_events()` loop by checking `GetKeyState` and telling the HWND to minimize when appropriate.

**Comment by alef** [comment]
On a multi-monitor setup with "_Activate a window by hovering over it with the mouse_" enabled in Control Panel's "_Ease of Acces Center_", there is no need to press keys for `cataclysm-tiles.exe` to loose focus.
By using _Rendered:_ `direct3d11`, the _Fullscreen:_ options `Fullscreen` and `Windowed borderless` seems to just work the opposite way as one expects when the mouse pointer moves to other monitors:
- `Windowed borderless` hides the window on loosing focus
- `Fullscreen` keep the window visible
