### ISSUE TITLE
Comparison glitch

### ISSUE THREAD

**Issue by Aracken43** [CleverRaven/Cataclysm-DDA#56489]
### Describe the bug

The bug happens when I try to compare a 5 round shotgun to a six round shotgun. It instantly crashes the game.

### Steps to reproduce

1. Obtain the 5 round and six round shotgun (unsure if it's limited to just those items)
2. Attempt the two using the I command.

### Expected behavior

I expected it to compare both, because I was trying to find out which one is better to have as an emergency weapon.

### Versions and configuration

Windows 10
Cdda version 3/28
Cdda tiles
Language: English
No mods loaded

**Comment by casswedson** [comment]
Can't reproduce on.
- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 21.2.6; Codename: Qonos; 
- Game Version: 12933403 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
possibly fixed by #56405 as stated by Roy
