### ISSUE TITLE
Web Bridge Mutation

### ISSUE THREAD

**Issue by Theawesomeboophis** [CleverRaven/Cataclysm-DDA#56499]
### Is your feature request related to a problem? Please describe.

I would like a Web Bridge mutation that works like Arachnitect does in BN https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1234
I think it would be cool to have something like this in dda.

### Solution you would like.

A Mutation called Web Bridge that works like Bn's Arachnitect, allowing easier travel between rooftops.

### Describe alternatives you have considered.

Not Submitting this request.

### Additional context

The implementation for this will need to be tweaked, as the suspension mechanic caused performance issues within Bn.
( Edit: Mutation was not web rope)

**Comment by MylieDaniels** [comment]
A few major changes would be necessary to the code present in the linked PR, but the concept seems very interesting.
