### ISSUE TITLE
flatjaw tong recipe violates conservation of mass

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#56503]
### Describe the bug

flatjaw tongs when crafted can produce more metal then consumed (3 chunks of steel is more metal then one nail)

### Steps to reproduce

observe that the flatjaw tongs produces more metal as a byproduct then it takes to craft it

### Expected behavior

you net lose metal when crafting metal tools

### Screenshots

![image](https://user-images.githubusercontent.com/78816055/161179769-24510dc2-fe67-4b61-a191-9d2aa2dfb8d5.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19041.1052 (2004)
- Game Version: 03d89b0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Hope [no_hope],
    C.R.I.T Expansion Mod [crt_expansion],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    Bionic Slots [cbm_slots],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

I did look and it seems no one has reported this issue yet, that or it was fixed before an issue was raised and i just got unlucky in my version.

**Comment by RoyBerube** [comment]
PR #55347 did it.
