### ISSUE TITLE
Followers will not go down into subway stations after you

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#56501]
### Describe the bug

I have an NPC follower who will not go down the stairs into subway stations after me, unless I debug control them to do so.

### Steps to reproduce

1. Have an NPC follower.
2. Descend from Z-level 0 of a subway station to Z-level -1.
3. Observe the NPC never follows you down.

### Expected behavior

I expect the NPC follower to know how the stairs work.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1586 (21H1)
- Game Version: 0b63322 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    No Vault [No_Vault],
    ASCIITiles overmap color fix [colors_fix_asciitiles]
]

### Additional context

I suspect this is happening because the stairs in subway stations also teleport you. Suggest redesigning the subway station to avoid having to do this.

**Comment by PatrikLundell** [comment]
The disconnected stairs is an issue. If I understand it correctly, there is a problem with having different Z levels rotate based on a "master" level rotation.

I don't know of it's still an issue, but in 0.E-2 companions didn't know how turnstiles worked, and thus couldn't follow you through them. The work around for that was to lead them through the ticket booth. Obviously, that issue won't be encountered until you actually manage to get the companion with you.

You might want to try to lead the companion down through both ends of both sets of stairs to see if one works, and you may also want to pace back and forth (or spend time in some other way) to give the companion time to path along some convoluted route to catch up with you, if that might be the case.

**Comment by RoyBerube** [comment]
The problem looks like it is because the ground floor level and the mid level get flipped 180 degrees so the stairs don't line up. No mobs or npcs will path up or down when that happens.

I've seen this happen a few times recently and this layout is always the case.
