### ISSUE TITLE
Mod suggestions: Generic and Simplified features

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#56511]
### Is your feature request related to a problem? Please describe.

Generic Guns is a core mod that represents an interesting accessibility feature and gameplay style change, allowing players to reduce the more simulationist aspects of CDDA without sacrificing basic gameplay function. We could use more features like this.

### Solution you would like.

In designing Generic Item type mods, it's important to be cautious about game balance. These mods do make the game easier, by allowing loot to become more cross-purpose. For this reason and for player choice it's probably a good idea to keep these kind of mods to individual packages. Activating them all would make for a substantially easier game. To balance that, it might at some point be necessary to have these mods also inherently reduce the spawning of associated items... or, we could just let people decide how easy they want their cataclysm to be.

Some suggestions for Generic Item mods that could exist:
- Generic Crafting: Replace a number of specific crafting items with more minecraft-like vague components. Rags, wool patches, etc may become just "cloth". Hinges, springs, sheet metal, chunks of steel could all be abstracted to "scrap". Various plank parts could be changed to "wood". Some of the more esoteric crafting parts could either be removed, or pulled back to their abstract equivalent, turning zippers into "fasteners".
- Generic Weapons and Armour: Make melee weapons and armour similar to generic guns. We don't need to distinguish between an arming sword, a broadsword, and a rapier: they can all be "sword". 
- Generic Food: Dial back the food level of detail a bit. Instead of thirty types of sandwich, just have a "sandwich" option. "Pizza", "pasta", "nachos", and many other foods that have multiple variants can be similarly simplified. The contaminant and ingredient tracking system can help to ensure these final products still keep an eye on food allergies.
- Generic Monsters: reduce the number of near-identical variants and mutants, especially location specific monsters.
- ~~Reduce Clutter~~ I had suggested this as a performance mod, but according to Kevin's profiling, the items that could be removed this way do not have a significant impact on performance, so there's not much point in this one.

In addition to Generic Item mods, it would be worth considering "simplified mechanics" mods. This can be a bit of a minefield, so I would like to lay a primary ground rule: new mechanics that are still under construction should **never** be considered for simplification. This feature is appropriate to older, well tested, basically complete mechanics that we are now ready to objectively evaluate and simplify. Otherwise, this will become something we explicitly want to avoid, where people who dislike change demand an on-off switch for every new feature, in turn becoming an inescapable coding nightmare of switches.

A feature simplification mod should work within the construction of existing features, using minimal changes to hide the back-end from the user and make them easier to learn and play with, ideally without sacrificing much balance. For example:
- Simplified Hunger: Have hunger display based on the calories you've eaten today, rather than stomach fullness. Consider increasing stomach size or removing/reducing the effects of stomach size as well (it's more coding but I'd suggest that stomach size still be tracked, but the penalties changed, so if you overfill your stomach it gives you fatigue and a little pain instead of making you throw up). This system might also remove your calorie stores and obesity stuff, or reduce them a lot, so that it becomes much easier to starve like in most less-simulation type games.
- Simplified Stamina: Blur Stamina and Weariness (and maybe fatigue) so that the player doesn't need to track so many variables. I am open to suggestions for how to do this in ways that don't break the game: remember, the purpose of weariness is to limit how much energy a player can spend in the day. My favourite thought here so far is to have this depend on Simplified Hunger, which in turn makes Weariness less important... you now can just eat and eat all it takes to stay full with your high activity. Perhaps in this Simplified Hunger system, your calorie deficit should now cause Weariness effects instead, so as you become more and more hungry you slow down until you've eaten. This is much gamier, which is sort of what we're going for, but accomplishes the same ultimate goal.
- Gamified Skills: This would require a fair bit of coding I think, but it would be neat to have a system where, when you level skills, you can use skill points to purchase proficiencies as if they were abilities. In this model, I think you'd choose if you want to level the skill, *or* gain a proficiency. Gaining a proficiency would drop your skill XP by a percentage based on the time_to_learn for that proficiency. You'd probably stop gaining proficiency XP the normal way in this model and instead just buy them. We might want to have some JSON allowing us to add skill level requirements to proficiencies this way, to create a more classic game feel.
- Gamified Inventory: Treat all worn pockets as, rather than their own space, a buff to your total inventory space. Many worn items, like holsters, may still have their own separate storage space, but a lot of stuff like fanny packs and cargo socks just adds to your overall total inventory space when you put it on. This allows keeping the best parts of nested inventory but removing a lot of the micro, while still being fully supported by the nested inventory system. Alternatively, a simpler (to make) inventory mod might just remove length restrictions from all pockets.

### Describe alternatives you have considered.

This is born out of brainstorming how we could have a mod supporting more "gamish" play that feels like a classic survival sandbox game rather than our complex and weird apocalyptic fun. I think supporting it as separate mods is neat because it allows people to pick and choose what they find too complex to track, like we do with Generic Guns, hallowed be its name.

### Additional context

To reiterate, the key here is that simplification mods should never be designed to remove a feature in progress for those that don't want to playtest it. That is why we have a stable version and we are not going to double that workload. Rather, they should target well established features, and the aim should by-and-large be "for people who want to track less stuff, how can we make this easier for them, without reducing their game experience". These add new variants of good features, rather than rolling them back. An ideal simplification mod should reduce user cognitive burden without actually reducing the game features themselves.

**Comment by AtomicFox556** [comment]
I think mods such as Generic Food and Generic Crafting would require way too much maintenance effort to be worth it (essentially any time a new recipe is added, it'd need to have a "generic" version written as well) unless there was a way to automatically alter all the previously loaded recipes based on a list of "specific->generic" item substitutions contained within the mod.

This would simplify the maintenance to just adding an item ID to a list of item ID migrations just like how it's currently done for Generic Guns mod.

**Comment by I-am-Erk** [comment]
Yes, any generic item mod is going to need a similar structure to Guns, and in turn for some that will mean some kind of somewhat robust way of identifying what items the mod is supposed to cover.

**Comment by AcidAntOnAMinefield** [comment]
This would actually be very much appreciated, especially for those that just really want to play the game and have some fun without having to deal with hundreds of different types of things nagging at them all the time. (Plus it would drastically increase accessibility too). 

> I think mods such as Generic Food and Generic Crafting would require way too much maintenance effort to be worth it (essentially any time a new recipe is added, it'd need to have a "generic" version written as well)

Wouldn't it be possible for the "mods" to have a sort of "exclusion" function? 
Say, like, the food mod would work like this:
- blacklists all the items under the [food] list (instead of blacklisting items individually) first;
- then adds [generic food item] over that;

Same with the guns, blacklist all [guns],[magazines] and [ammo], and then add the generic variants. 

You don't necessarily need to have a generic recipe for every new item that is added: if you have 30 different entries of "soup", you just need 1 "generic soup".

**Comment by I-am-Erk** [comment]
We already have a function called `migrate` that turns an item of type x into an item of type y. That's how Generic Guns works.

**Comment by I-am-Erk** [comment]
Still desired but I'll let it fade into the mists unless someone becomes excited.
