### ISSUE TITLE
Researchable recipes

### ISSUE THREAD

**Issue by hostergaard** [CleverRaven/Cataclysm-DDA#56528]
### Is your feature request related to a problem? Please describe.

So right now there is recipes there is autolearnable, and recipes that are not. But I feel there is a lot on both sides that should be neither, or rather both in a way.

There is a lot of autolearnable I find that an average person should not just immediately know how to make, yet there is also plenty I non autolearnable things I feel that with enough time and experiments should be able to figure out how to make work. Basically things that you may be aware of to vague degree or simply things you realise you need and then experiment to figure out a solution. 

I have posted about the makeshift steam engine. 

### Solution you would like.

Make certain recipes that are not auto learnable (and some auto learnable) able to be learned without a recipe book trough a lengthy (depending on how complex it is) set of experimentations to unlock said recipes. 

### Describe alternatives you have considered.

Described in another post, make certain recipes conditionally auto learnable. I feel like it would work great in tandem, with having certain recipes researchable under certain conditions, like stats or profession. 

### Additional context

The exact details of how to implement it is an open question.

It could be done like the training recipes. Or maybe have it so researchable have an of color, and you need to spend a percentage of the resources and time to research it and then have a random change of succeeding in unlocking it depending on stats, previous attempts and so on.

**Comment by PatrikLundell** [comment]
I would probably try to implement a system parallel to the proficiency one, so a "research recipe" would "train" the practical knowledge needed to discover/write down/unlock the recipe. Unfortunately, it's probably hard to automate it such that research recipes could be generated automatically unless blocked or overridden, as it probably is hard to automatically determine what consumables you'd need for your experiments.

An alternative or complement might be to use the proficiency system to unlock a list of recipes when a proficiency is mastered, or, even more complex, when a combination of proficiencies is mastered. However, it would probably not be easy to maintain.

**Comment by merrygin** [comment]
Another alternative might be having essentially all recipes autolearned, but separate the crafting difficulty from an autolearn difficulty. So you might be able to make a thing with fabrication 6, but to come up with the recipe by yourself is a difficulty of fab 9, or something along those lines. Might be constricting in its own way, but the existing practice recipes system would be sufficient for it to work (or would make it even more important).
