### ISSUE TITLE
Conditional autolearning recipes

### ISSUE THREAD

**Issue by hostergaard** [CleverRaven/Cataclysm-DDA#56527]
### Is your feature request related to a problem? Please describe.

I made another post asking that steam engines should be auto learnable and it had me thinking, yeah, an 6 int curl would probably struggle with that and not know how to do it, but 12 int university student would probably have enough simple base knowledge from childhood and intelligente be able to figure out how to make a primitive steam engine on his own. You boil water under pressure that then drives up a piston which provides motion. The basics are pretty simple, even if all the bells and whistles (ha!) of making efficient and high quality steam engines are more complicated.

It had me thinking then that binary system of something being learnable don't present the vastly different mental capacities, background knowledge and such. 

### Solution you would like.

Have certain recipes that is not currently auto learnable be auto learnable if you have certain intelligence or meet certain other conditions other than simply the particular skill. 

Like the makeshift steam engine, we all have a vague understanding at least how it works, someone with a little bit of intelligence should be able to figure it out.

### Describe alternatives you have considered.

Make recipes researchable. That is, certain recipes aren't auto learnable but should be researchable.

**Comment by robotic-gamer** [comment]
the easiest way to implement this would be to create a recipe that makes a "book" (research notes) that contains the recipe you "researched" (crafted). to avoid clutter these could be put in there own tab.

**Comment by x-qq** [comment]
I think researchable recipes is a way to go.
