### ISSUE TITLE
Unexplainable Crash when building on my faction camp

### ISSUE THREAD

**Issue by scraw-darkblade** [CleverRaven/Cataclysm-DDA#56532]
The game is crashing when building issuing building orders at faction camps

**Comment by BrettDong** [comment]
The crash log suggests the crash is unrelated to the faction camp. It is caused by some player activity your avatar character was doing when an auto-save was triggered.

**Comment by scraw-darkblade** [comment]
My bad. I don't know how to read those and just related the crash to what happened.

**Comment by BrettDong** [comment]
It would be helpful if you can provide information on how to reproduce the crash.
