### ISSUE TITLE
Asking Rubik to cyborgify the PC incorrectly complains about the lack of an anesthesia kit

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#56542]
### Describe the bug

The first reponse to "I've brought you those anaesthetic kits for you. Can you help me out?" is a popup saying
"You don't have a anesthesia kit". When the popup is dismissed, the following error report is generated:

 DEBUG    : Attempted a recipe with no available components!

 FUNCTION : select_item_component
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\crafting.cpp
 LINE     : 1798
 VERSION  : 53f9bd3

However, the dialog continues, the mission is completed, the bionic kit is installed, but the anesthesia kit isn't consumed.

### Steps to reproduce

1. Activate the bionic kit installation quest with Rubik.
2. Bring a single full anesthesia kit, which contains the required amount (6000 ml).
3. Enter the dialog above.

### Expected behavior

No complaint popup, no error report, and kit consumption (or, rather, the contents, leaving an empty kit).

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1586 (21H1)
- Game Version: 53f9bd3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
+ JSON "mod" to disable portal storms as the mod PR for it was rejected.

**Comment by haveric** [comment]
There is some weird stuff going on with this quest. I was able to get the error when first getting the quest via "Two, uh, anesthetic kits, coming up.  I'd better start looking."

I think there's an issue going on with the quest asking for just anesthetic, but it's intended to be completed via dialogue. Trying to figure out what exactly is happening though as I'm not sure why the error is appearing for this. My quest is autocompleting without consuming anything, which I think is a different issue.

**Comment by PatrikLundell** [comment]
The quest ought to consume the fluid and not the kit itself, which might be why nothing is consumed if it requests the kit at one place and the contents at the other (or vice versa).

As an aside, the dialog uses the spelling "anaesthesia" while the inventory and popup uses "anesthesia" which looks like an English vs American spelling issue ('ae' vs 'e').

**Comment by haveric** [comment]
Yup, this wasn't possible before my PR https://github.com/CleverRaven/Cataclysm-DDA/pull/55986. I'm testing the switch to consume the anesthetic instead now and making the mission never complete unless it's through dialogue. That seems to be fixing everything.

> anaesthesia
I reworded it for this, but there's another instance of it as well that I can fix.

Just doing some final testing, but PR will be up soon.
