### ISSUE TITLE
Display a warning when opening sealed containers

### ISSUE THREAD

**Issue by Faalagorn** [CleverRaven/Cataclysm-DDA#56567]
### Is your feature request related to a problem? Please describe.

Currently, when pouring (reloading), or instering items to a container (with e), or when eating or using items in crafting, no warning is shown when a sealed container is being used and seal is getting broken.

### Solution you would like.

Show a warning message (similar to the one before stepping into bush) whenever a sealed container is open. Ideally something that can be turned off in options in case someone finds the message annoying.

### Describe alternatives you have considered.

Have an option to open seal manually, but that would lead to needless micromanagement.

### Additional context

Hopefully it wasn't suggested yet, but checking for seal in issues displayed way too many results sadly. I found #55298 which in turn refers to #46520, but both issues seam to deal with the problems of keeping seal intact, not the accidental opening of it.

**Comment by Termineitor244** [comment]
I suggest to only display this warning when the sealed container contains (ha!) perishable food, since even water comes in sealed containers.

**Comment by Faalagorn** [comment]
> I suggest to only display this warning when the sealed container contains (ha!) perishable food, since even water comes in sealed containers.

For simplicity I don't mind the message for all the containers, but it could be either way, or with an option to be toggled – especially as someone pointed on Discord that sealed perishable foods won't get dissolved in water, so there's a use for keeping them that sealed, too. :)
