### ISSUE TITLE
Leather Reclining Seat typo

### ISSUE THREAD

**Issue by Bulletfang** [CleverRaven/Cataclysm-DDA#56568]
### Describe the bug

The description for the reclining leather seat doesn't seem to make sense due to what seems a typo. A reclining backrest doesn't make a seat a less comfortable bed, but the opposite, or at least no difference at worst.

### Steps to reproduce

1. Examine a reclining leather seat

### Expected behavior

Description says that a reclining backrest makes a seat a more comfortable bed.

### Screenshots

![311111](https://user-images.githubusercontent.com/45204409/161453298-48ebd09a-703f-4fc2-81c2-9213ae1e5272.JPG)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1586 (21H1)
- Game Version: ba5e863 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

None.

**Comment by PatrikLundell** [comment]
I believe the intention is to say that despite the seat reclining, the seat is uncomfortable to sleep in nevertheless, as it's not designed or intended to be a proper bed.

**Comment by Bulletfang** [comment]
It literally says in the second sentence "You can sleep here comfortably."

**Comment by PatrikLundell** [comment]
Yes, I know that. I don't think that's correct, though. Comfortable compared to the bare ground, yes, but not compared to something akin to a bed.

**Comment by Night-Pryanik** [comment]
Literally what PatrikLundell said. It's not a typo.
