### ISSUE TITLE
Piercing weapons do not seem to be raising piercing weapon skill very much (or at all?)

### ISSUE THREAD

**Issue by MisterFelixFox** [CleverRaven/Cataclysm-DDA#5656]
I've noticed that when I use spears and the like, my bashing weapons skill skyrockets while my piercing weapons skill stays very low.

I found a bee sting (0 bashing, 10 piercing) and did some testing: I started at piercing weapons 0 with 37% towards the next skill increase and bashing weapons 1 with 69% towards the next skill increase. After stabbing seven zombies to death using the bee sting, I saw an increase of 2% to bashing weapons, but no change to piercing weapons.

**Comment by Rivet-the-Zombie** [comment]
This was fixed very recently.
