### ISSUE TITLE
'play now' erroneously uses existing worlds, even if occupied by a living character

### ISSUE THREAD

**Issue by esotericist** [CleverRaven/Cataclysm-DDA#56569]
### Describe the bug

while doing a merge test for a pr, i realized i needed a new save, and didn't feel like manually creating a world. so i decided to use 'new game -> play now' to get something quickly set up.

it did not ask for a save to use, or prompt to overwrite a save, or anything. it just loaded up a new character.

problem: it did it in an existing *active* world. this resulted in two characters in the same world and, more pressingly, new overmap data potentially being written out.

### Steps to reproduce

1. have an existing occupied world a your last used world
2. press 'new game' then 'play now' on the main menu
3. save and quit
4. attempt to load your pre-existing world
5. behold as you are prompted which character to load

### Expected behavior

play now should make a new world, or at minimum prompt for an unoccupied world. it definitely shouldn't use an existing occupied world.

### Screenshots

screenshot of the folder after it arrived in the undesired state
![image](https://user-images.githubusercontent.com/1569754/161454793-201f5a08-2311-429e-b847-c8264bc658af.png)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 11 (bullseye); Release: 11; Codename: bullseye; 
- Game Version: ba5e863 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    eso_ui_bits_msx [eso_ui_bits_msx],
    No Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm]
]

### Additional context

i've since excised the data from the unwanted test character, but i'm not 100% sure how intact my save is. my understanding of what all gets written that's per-character and what isn't is tenuous. it seems to work so far, if this turns out to be genuinely save corrupting i'll update this issue.

**Comment by NetSysFire** [comment]
I am not sure if this a bug. It existed since at least 0.E. I do agree though that maybe an option to use a new world might be good to have although it might be tough to implement due to choice of mods for the new world. Using the default set of mods might be considered "boring" (yet it is safe) but just enabling any random mod for a world seems very prone to breakage.

**Comment by esotericist** [comment]
i'm of the very firm opinion dumping a new character's data into an occupied save is 100% a bug. it existing a while is not a justification for destructive behavior. it's not like we surface an option for backing out the new character from the world, and i'm as of yet unconvinced it isn't actually damaging to any of the prior data.

besides, play now already has 'use default evacuee scenario' baked into it. using the game's default mods (or the player's personally set default mods) wouldn't be that big a stretch from an expectation standpoint.

**Comment by ZhilkinSerg** [comment]
I strongly agree: while we do allow multiple player characters in the same world, it is only single player character per world that should be supported.
