### ISSUE TITLE
"Active Noise Control" mission from Banker Throws up Exception

### ISSUE THREAD

**Issue by GordanGeeko** [CleverRaven/Cataclysm-DDA#56574]
### Describe the bug

When I accept mission to investigate bug from the Hub Radio Tower from the Ammo Broker Artisan, it throws up two errors, and doesn't create a bread crumb on the map. When I teleport to the Radio Tower nearest to  the Hub, there is nothing to investigate, also.

The Hub Merc mission of the same name works as it should, only this one doesn't. Same issue happens if I have done the Merc version or not.

### Steps to reproduce

1. Go to the Artisans.
2. Complete all missions up until Activate Noise Contorl.
3. Try to activate it and get my errors.

### Expected behavior

It should create a map marker to follow and allow me to complete this mission.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1586 (21H2)
- Game Version: b66a9b5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    No Fungal Monsters [No_Fungi],
    Aftershock [aftershock],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP]
]

### Additional context

 DEBUG    : Unable to find and assign mission target radio_tower_1.

 FUNCTION : find_or_create_om_terrain
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\mission_util.cpp
 LINE     : 251
 VERSION  : b66a9b5

 DEBUG    : Unable to find and assign mission target radio_tower_1.

 FUNCTION : find_or_create_om_terrain
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\mission_util.cpp
 LINE     : 251
 VERSION  : b66a9b5

**Comment by PatrikLundell** [comment]
This mission wasn't supposed to exist. #56315 reported this and #56365 fixed it.
