### ISSUE TITLE
Introduce storage battery case as an appliance

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#56576]
### Is your feature request related to a problem? Please describe.

It would make sense to allow appliance grids to recharge storage batteries for use in vehicles. It's currently possible to manually install and remove storage batteries as appliances, but it takes some time (in particular if you're shifting several of them). Storage battery cases seem like the ideal use for recharging storage batteries for vehicles.

### Solution you would like.

Introduction of the storage battery case as an appliance.

### Describe alternatives you have considered.

Either spend time placing/removing storage batteries to appliance grids, or continue to use recharging vehicles.

Creating some sophisticated recharging station that's capable of draining fixed batteries to charge batteries in storage battery cases for a better charging logic (the current logic charges everything to the same level, so rather than having the prioritized batteries at 100% and the fixed batteries at 50%, you'd have everything at 75%, if there was an equal number and sizes of each).

### Additional context

Battery pack swapping is something that's being used in the real world, although at a small scale. The real world use certainly doesn't charge the battery packs in solar vehicles...

I believe there's a call for fleshing out the set of appliances, and I think this is a good candidate.

**Comment by Maleclypse** [comment]
Did #55265 close this?

**Comment by PatrikLundell** [comment]
No. That PR added the storage batteries themselves as appliances. The purpose of using cases to host the batteries is that you save time by just docking batteries into/out of the case attached to the grid, rather than wiring them directly to the grid and then manually disconnect them.

There is no mentioning of cases in the PR text, and I can't see any mentioning in them in the last commit either.
