### ISSUE TITLE
Explored part of the map becoming unexplored and NPC's disappearing from this part

### ISSUE THREAD

**Issue by Endertron51** [CleverRaven/Cataclysm-DDA#56573]
### Describe the bug

One day when loading my map after a update I got a error message, I ignored thinking it would be nothing important, I stayed at my base doing things for days, until I noticed that a big part of the map which I already have seen became unexplored in a giant rectangular pattern, on the way to the refugee camp which was on this part of the map, A 3x3 mansion tile appeared where it never was, but it was just on the map, I drived to the location and seen nothing but a field with shadows on the day, as if the mansion was above me which I can't confirm if it was or not, when I reached the refugee camp, there was no NPC's, I've already talked to the NPC's which was previously on that place, and they where gone now, this erased some portion of the game content to my game as I've been told that NPC's quests can take me to some interesting places.

I "solved" this problem loading my last backup from 6 days ago which made me lost some progress but not the whole world and character, But it happened again today on april 3rd when I loaded my character, I reloaded a recent backup which I did in fear of happening again and loaded to take a screenshot of the error, but it loaded normally, and then happened again later today (april 4th)
This seems to happen sometimes or not, that's the reason that I can't upload a screenshot of the map.

### Steps to reproduce

I'm not sure how to reproduce this, I literally started to play this game about a month ago with a common custom character evacuee at a default world, until after mid summer using almost no mods and doing save scumming which I don't know if it can destroy my game like this.
I noticed this happened when I updated my game and opened it on april 1st, I don't have programming skills but maybe this is happening because of the frequent experimental updates

### Expected behavior

Explored map doesn't become unexplored
NPC's don't disappear along with the explored map
If possible stop mansions from appearing as a large shadow on a field and as proper buildings

### Versions and configuration

OS: Windows 7, 64-bit
Branch: Experimental
Version: ba5e863 (tiles)
Build: 2022-04-03-2051
Ingame language: English
Mods loaded:
- Dark Days Ahead
- Disable NPC Needs
- Bionic Professions
- No Fungal Growth

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8407152/debug.log)
[Salada.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8407153/Salada.zip)

**Comment by PatrikLundell** [comment]
It might not be it, but I'd check the hard disk integrity, as it seems files in the save may have been deleted or corrupted.

**Comment by Endertron51** [comment]
> It might not be it, but I'd check the hard disk integrity, as it seems files in the save may have been deleted or corrupted.

Considering what you said, the unstable energy supply of my place suddenly turning off my laptop and the fact that I found no one with the same problem as mine, it's highly possible.
I did a chkdsk /f, and if the problem return, I will consider creating another world/character before making a bug report, as this world/character maybe are doomed, Thanks for the help.

**Comment by PatrikLundell** [comment]
Suddenly losing power can definitely corrupt files, as Windows (at least) can cache files for writing rather than actually do it when the program orders it to do so.
