### ISSUE TITLE
The crafting interface should not show multiple entries for the same thing

### ISSUE THREAD

**Issue by Arjan219** [CleverRaven/Cataclysm-DDA#56580]
### Is your feature request related to a problem? Please describe.

It bugs me how the crafting interface is cluttered by multiple entries to make the same thing.
Currently: one recipe to make a 3L jar of soup, one recipe to make a 0,5L jar of soup, and one recipe to make a medium tin can of soup. All three are the same soup, and the only difference is the container it's in.
It's understandable if the methods for crafting an item are significantly different, but here it's all just [FOOD] in [CONTAINER].
![Screenshot from 2022-04-04 13-37-19](https://user-images.githubusercontent.com/28710711/161539769-383f8fb5-ebc1-4c2e-8399-e731cc04c444.png)

### Solution you would like.

1. Replace the three recipes with a single recipe for just the soup.
2. When crafting finishes the player is prompted whether he wants to consume/store/dump his food, at which point he can decide for himself what container he wants his soup in.
3. In a separate action, the player can use a can sealer to seal any cans and jars with food in them. If at this point the food is hot, it succeeds and the can becomes (sealed).

### Describe alternatives you have considered.

Alternatively the separate recipes might be collapsed under a single entry which, when selected, would unfold to ask the player which variation he would like to make, though this would only hide the clutter instead of solving it.

**Comment by bananapheasant** [comment]
I think the crafting system needs an overhaul. Many ways to change it, but intuitive and adaptable is what i would like. Condensing similar items into one with options for how and what to craft.  Creating this system with future implementations of item qualities and the like.

So perhaps a menu with tabs for types of crafted items like we have now. And then base items with options. So a food section for crafting might have various ways to sort for recipes with options to see learned recipes, recipes from books, custom /saved recipes, or create from scratch. Types of food recipes could include Salads, Soups, Sandwiches, Meat, Breads, Pastries, etc.

If you select to create a soup, you can then select what kind of base, ingredients, how to cook it, how much to make, etc.

If nothing else, i think a good discussion between many people is good to brainstorm the best crafting system for the future of CDDA

**Comment by Inglonias** [comment]
Talking about overhauling the crafting system's UI is all well and good. We just need to find a person who's brave enough to actually do it. A list of requirements and a mock-up with pictures is usually the first step in a process like this.
