### ISSUE TITLE
Oversight - Killing NPC at Marloss pilgrimage gives -80 "Killed Innocent" mood debuff.

### ISSUE THREAD

**Issue by Jan-Blasiak** [CleverRaven/Cataclysm-DDA#56584]
### Describe the bug

Killing NPC at Marloss pilgrimage gives -80 "Killed Innocent" mood debuff.

Since when anyone associated with one of the tendrils of the Apocalypse is even remotely innocent?

### Steps to reproduce

Headshot NPC at Marloss pilgrimage, see your mood.

### Expected behavior

+20 "Had it coming!" Mood buff for anyone NOT posessed by the fungi or something similar.

### Versions and configuration

2022-03-21-0633

### Additional context

Terrible oversight.

**Comment by Night-Pryanik** [comment]
Expected behavior is wrong. 
These people didn't cause the Apocalypse. Their sect was founded _after_ the Apocalypse. Thus, they are innocent, you're a murderer, and this mood debuff is absolutely justified.
