### ISSUE TITLE
Ideas on portal storm/pocket dimension artifact expansion

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#56582]
### Is your feature request related to a problem? Please describe.

(so i was a dummy when i made this and thought EOC meant Enemy of Concern, ie boss, idk why. but im not changing it all not and it still kind of applies with Event on condition...)

This is an idea built upon #56566 with portal storm EOCs that drop artifacts. This aims to add new elements to the sci-fi realm of CDDA and open up branches to expand upon lore and gameplay-wise and give new end game content with potentially extreme risk/reward.

This ties in with various factions, portal storms, and pocket dimensions. The lore needs much work. 

### Solution you would like.

**Lore Thoughts** -
Artifacts are the name given to objects of unidentified origin that are able to store and use energies like those found in portal storms. These near unobserved objects are highly advanced with extra-dimensional functions, possibly existing between or in multiple dimensions. It is believed they are inanimate and without consciousness. Most artifacts are fractured and only pieces remain, with most being treasured and protected by camps of various factions, powerful leaders or renegades. Fully operational artifacts are believed to have been used to create or contains rifts between dimensions and alter states of matter. Their properties appear cross-dimensional, unstable, and in general are very unknown.

Artifacts are able to distort or control aspects of the fabric of space-time primarily. It is unclear if they are _Blobian_ in nature, created by the Mi-Go to capitalize on technologies of the Blob, _Exodiian_ tech, or something else entirely. Likely, it is an ancient tech used by the blob that has been superseded with more powerful or reliable means of manipulation. They are, however, powered by the same energy created in portal storms - shaking and radiating a terrifying glow when in proximity. 

It is likely that being in possession of such an artifact, especially if restored, would draw attention.

**Mechanics** -
Artifact pieces, and in rare cases operational artifacts (possibly), can be obtained from EOCs in portal storms, from EOCs in pocket dimensions, or from special locations in game where they are heavily protected by strong faction camps. Artifact pieces can be assembled or combined to form complete artifacts, but this requires energy from a Portal Storm. Artifacts can be broken down or altered during portal storms as well. Artifacts store energy from portal storms and are able to drain this energy at any time to trigger one of many powers.

Powers could include:
- Warping space-time around the object making it unable to be seen (invisibility if holding and using).
- Creating a rift in the fabric of reality and creating a pocket dimension/opening access to a pocket dimension in that location
- Creating a localized electrical discharge in the air (lightning spell)
- Warping space-time to translate distances in the current dimension (teleportation)
- Localized warping of space-time to prevent attacking into or out of  (barrier)
- Distort and swallow up light in localized area (darkness around user)
- Ability to close portal storm or negate local effects from one
- Ability to banish another creature to a different dimension

Perhaps some will have more negative effects like:
- Artifact disappearing into another dimension
- Summoning otherworldly creatures
- Teleporting user and/or artifact to a random location
- violent implosion of space and/or time

### Describe alternatives you have considered.

Lore could go a lot of ways.

Major purpose is to give reasons to prepare and traverse in portal storms, and add new end game content.

Possibly have end game, high level creatures in possession of an operational artifact. A creature that would make other challenges pale in difficulty.

### Additional context

This is nothing i can create myself right now, i just want to put it out there and see if anyone thinks this is feasible, beneficial to gameplay, lore-friendly, etc. Very open to ideas, want to hear what you all think, especially those more involved in the lore, mechanics, and major development of CDDA.

**Comment by fairyarmadillo** [comment]
A weaker barrier that kept small particles and gases away from the player for a time could be cool, sort of an air bubble that blocked hot air/rain/acid spray/poison/smoke/spores but would allow bullets and zombies through.

Sounds a bit niche, but sometimes you don't have PPE and need to get from point A to point B. It could even block some radiation if alpha/beta/gamma sources are ever split out.
