### ISSUE TITLE
Some belt items cover whole torso instead torso_waist after PR#56376

### ISSUE THREAD

**Issue by Naadn** [CleverRaven/Cataclysm-DDA#56586]
### Describe the bug

After [PR#56376](https://github.com/CleverRaven/Cataclysm-DDA/pull/56376) belts got changed from `WAIST` to `BELTED` flag and specifically covered the `torso_waist`. But I have find out that `belt_pockets_lesser`, `mbelt_pockets_greater` and `mbelt_weaponry` in magiclysm covered whole torso intead. Due to they all inherit `mbelt_leather` but changed the `"armor"` line so they don't inherit the `"specifically_covers": [ "torso_waist" ]` part.

### Steps to reproduce

1. Spawn `belt_pockets_lesser`, `mbelt_pockets_greater` and `mbelt_weaponry`
2. Look at where they covered

### Expected behavior

They have "Specifically : the waist" line

### Screenshots

![image](https://user-images.githubusercontent.com/97841551/161608131-f8e63d91-ac23-4d2a-a4b5-c29020d467c4.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.556 (21H2)
- Game Version: 3a2a5bc [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Stats Through Kills [stats_through_kills],
    Bionic Slots [cbm_slots],
    Bionic Professions [package_bionic_professions],
    C.R.I.T Expansion Mod [crt_expansion],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Extra Mutated Scenarios [extra_mut_scens],
    Mythical Martial Arts [MMA],
    No Rail Stations [No_Rail_Stations],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm]
]

### Additional context

The PR is closed when I find this so I have make a new issus for this bug.

**Comment by Jarewill** [comment]
I missed those.
I only changed the armor definitions of mbelt_leather, thinking it would apply to all others, but apparently not those ones.
I will make a PR fixing this in a bit.
