### ISSUE TITLE
Allow gun mods to prevent a firearm from shooting when activated.

### ISSUE THREAD

**Issue by DoctorBoomstick** [CleverRaven/Cataclysm-DDA#56606]
### Is your feature request related to a problem? Please describe.

This is something which came up when I was trying to rework some guns to be mor fateful to their real life counterparts, specifically the Kel-Tec Sub 2000. As things stand, there is no way to influence a gun to keep from firing under certain conditions short of causing it to mis fire. This is problematic when some guns, like transforming firearms like the Sub 2000 which fold in half, are meant to be rendered inoperable when folded.

### Solution you would like.

Create something like a flag for gun mods which makes them keep firearms from being able to be shot, to properly simulate mechanisms and folding stocks which keep weapons from firing when in use.

### Describe alternatives you have considered.

Ah, I’d guess… do nothing and leave things how they are.

**Comment by catdach** [comment]
Ok so, here's one idea; Modify the firing modes of the gun. Some in game example of this are the full-auto conversion gun-mods. This is the line from the lightning link:
`"mode_modifier": [ [ "DEFAULT", "auto", 14 ] ],`
So _in theory_, if I wanted to make a plug-bayonet I would give it a line like this:
`"mode_modifier": [ [ "DEFAULT", "bayonet", 2, [ "MELEE", "REACH_ATTACK" ] ] ],`
For your case I would put into the stock(folded) a line like: 
`"mode_modifier": [ [ "DEFAULT", "disabled", 0, [ "MELEE" ] ] ],"`
Which _should_ basically turn it into a melee attack 
(side note: the kel tec sub-2000 uses a generic folding stock so it would need a new one specific to that gun)

I haven't tested it, but that's what I would try.

**Comment by DoctorBoomstick** [comment]
hum, interesting and clever work around. on the advice of somebody in the discord I just switched the firing rate to 0 rounds, but that just threw up a big fat error telling me that I was trying to fire 0 rounds out of the weapon, which was no bweno, in the game's books. I didn't know that you could basicly turn it into a melee attack. I already created a new mod for the Sub 2000, so I'll paste in your helpful example and see how it runs. thanks for the idea.
