### ISSUE TITLE
Chibi Ultica Leg tentacle sprite bug

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#56602]
### Describe the bug

In Chibi Ultica, the leg tentacle mutation sprite appears to use an arm tentacle sprite, rather than MSXOtto+'s leg tentacles. It also covers part of the face in a way that doesn't look intentional.

### Steps to reproduce

Make a character with leg tentacles
Strip naked
Look at the character in Chibi Ultica vs MSXOtto+

### Expected behavior

The leg tentacles sprite should cover the legs, not the arms. If it's meant to be a different sprite from MSXOtto+, it needs to be moved down several pixels.

### Screenshots

![image](https://user-images.githubusercontent.com/94415528/161878960-3321e4ed-e07c-4827-99d6-1bac1fc76831.png)

This character has tentacle legs and normal human arms.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1586 (21H1)
- Game Version: df6d5f0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Fris0uman** [comment]
It'll get fixed in the next tileset update
