### ISSUE TITLE
Weapon mod "folding stock" reduces volume but not length.

### ISSUE THREAD

**Issue by GewieG** [CleverRaven/Cataclysm-DDA#56607]
### Describe the bug

Installing the weapon "folding stock" on a weapon does not decrease the length of the weapon, even though that is the effect of a folding stock in real life and in the items description.

### Steps to reproduce

1. Observe starting length of gun.
2. Install mod on gun.  I tried it on the HK417.
3. Observe length of gun after install.

### Expected behavior

Length should decrease due to the ability to fold the stock of the gun.

### Screenshots

![mod install screen shot](https://user-images.githubusercontent.com/103043985/161753249-1b760c61-c3c6-44f4-bd77-fb75ea165619.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Fuji's Military Profession Pack [fuji_mpp],
    Bionic Slots [cbm_slots]
]

**Comment by TheShadowFerret** [comment]
You have to manually fold it since #55802, there is no bug.

![image](https://user-images.githubusercontent.com/99621099/161782710-1bddd757-20b6-46c3-ae3e-95139500d893.png)
![image](https://user-images.githubusercontent.com/99621099/161782763-f466c015-1912-4d8d-9347-43cdf982973c.png)

**Comment by catdach** [comment]
I noticed that you're playing on stable, this issue should be resolved by #55802, which is only in experimental right now AFAIK.
