### ISSUE TITLE
Zombie MRE entrees rotting

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#56611]
### Describe the bug

I killed some zombie soldiers in a science lab on Spring 70, and some of their MRE entrees were unsealed and rotten.

### Steps to reproduce

Make a character, kill a zombie soldier, check out its MRE entree.

### Expected behavior

The MREs should all be sealed and unrotten.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1586 (21H1)
- Game Version: df6d5f0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by TheShadowFerret** [comment]
#48827 added both a new and used version, this is not a bug.

**Comment by fairyarmadillo** [comment]
> #48827 added both a new and used MRE drop, this is not a bug.

MRE entrees are only one bite, maybe they should be split into two and the used entrees should be half eaten? It makes sense that they wouldn't all be sealed, but it was unclear to me what had happened when I found these items.

**Comment by fairyarmadillo** [comment]
Since this isn't technically a bug I'm closing this.
