### ISSUE TITLE
Can't build second stage of wood wall 

### ISSUE THREAD

**Issue by LordMaddog** [CleverRaven/Cataclysm-DDA#56614]
### Describe the bug

trying to build the second stage of the wood wall but says can't build here

### Steps to reproduce

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8420405/save.zip)

try to build wall but says can't build here

### Expected behavior

Wall is built

### Versions and configuration

[VERSION.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/8420407/VERSION.txt)

**Comment by haveric** [comment]
You appear to be missing wooden panels/sheets, so I'm pretty sure this isn't a bug:
![image](https://user-images.githubusercontent.com/985060/162103487-2653e221-b996-4892-8c19-fe07c2ebf652.png)

**Comment by LordMaddog** [comment]
ah thanks

**Comment by haveric** [comment]
@LordMaddog You can probably close this at this point, unless you've found something else that's causing an error with this.
