### ISSUE TITLE
When crafting items that contain thread, some recipes appear to fail immediately and prompt to consume more thread, duplicating it

### ISSUE THREAD

**Issue by iceblaster** [CleverRaven/Cataclysm-DDA#56613]
### Describe the bug

As the title says, when crafting items in the armor category, items that use thread appear to fail immediately and prompt to consume more thread, only to ask again and again when you select yes and continue. Additionally there appears that this may duplicate thread in the process, as thread will be spawned in your inventory and on the floor.

When hitting no and continuing manually though, the bug does not appear to manifest sometimes.
Addendum: selecting thread from nearby seems to be the cause of the issue, as selecting from the person does not cause anything.

### Steps to reproduce

1: Spawn a player, give them a sewing tool, and thread to use it with.
2: Attempt to craft a balaclava
3: Select yes
4: Select thread from nearby
5: Check inventory or floor for duplicated thread.

### Expected behavior

When crafting items with thread, it shouldn't continually ask for more thread without prompting, and not duplicate thread.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.14393.0 (1607)
- Game Version: ed4559e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

### Additional context

[Wewoka.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8420069/Wewoka.zip)
The save file where I have got this issue to occur. To the right of the player is 290 thread which I spawned in addition to the tailoring kit on the floor beneath them. To the diagonal right is a denim shorts which I crafted during the attempt. In their hands, an in progress balaclava will be present. It is likely the bug will not immediately make itself known by continuing, so you will need to perform the step yourself.

**Comment by Termineitor244** [comment]
This occurred to me and at least 2 other users mentioned it too on discord (So, confirmed).

It indeed seems to happen because of the location of the thread, in my own experience with the bug.
