### ISSUE TITLE
Aprons conflict with belts now

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#56620]
### Describe the bug

Recently Belts were moved away from the hardcoded belt layer and added instead to a real torso layer. Because aprons cover 70% of 100% of the torso, so it now conflicts and causes extra encumbrance.

### Steps to reproduce

1. Wear a belt.
2. Wear an apron.
3. observe conflict

### Expected behavior

Apron layering is weird due to being on the strapped layer. There's no easy way to layer it easily, although I had previously put out a PR #55441 but it's unclear if this is the best way to implement it because it will still conflict with fanny packs and purses.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.556 (21H2)
- Game Version: c1f4cf8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots]
]

**Comment by Jarewill** [comment]
I can't replicate this on ba9af2e
![image](https://user-images.githubusercontent.com/98614648/161980978-b93f6c8f-fb36-4b87-a4b6-9b1af64b483d.png)

**Comment by anoobindisguise** [comment]
> I can't replicate this on ba9af2e ![image](https://user-images.githubusercontent.com/98614648/161980978-b93f6c8f-fb36-4b87-a4b6-9b1af64b483d.png)

You are correct. I took my police belt off and put it back on and it resolved itself. Sorry everyone!
