### ISSUE TITLE
Let light through but not sight

### ISSUE THREAD

**Issue by Fris0uman** [CleverRaven/Cataclysm-DDA#56633]
### Is your feature request related to a problem? Please describe.

Standing in front of stained glass windows in broad day light and yet I'm still in darkness.

![image](https://user-images.githubusercontent.com/41293484/162074163-00faf894-ea09-45fb-a0bd-f2ab5eb388a4.png)

It would be nice if the engine could support letting light through a tile without making the tile see through

### Solution you would like.

Being able to have some terrain/furniture obstruct sight without bloking light completly. It could allow stained glass to let light through but alos stuff like having some light pass throguh boarded up windows or under doors.

**Comment by RAldrich** [comment]
This is reasonably straightforward on the player vision side of things, the lighting code is already split between light transparency and vision transparency, and supports translucency / light attenuation. I have working version that lets light through but prevents player vision.

I still need to figure out the monster vision code half of it, as they seem to be able to be able to asymmetrically see the player for 6 tiles or so.

That monster behavior might actually be desirable though, insofar as it lets them see motion behind the window? I'll probably try to figure out why it's happening either way before I post a PR for this.

**Comment by Brambor** [comment]
- Implemented by #76290.
