### ISSUE TITLE
Pick up items from nearby tiles ((g) menu) specifying amount conflicting hint and keybind

### ISSUE THREAD

**Issue by k0r4y** [CleverRaven/Cataclysm-DDA#56648]
### Describe the bug

![afbeelding](https://user-images.githubusercontent.com/26572988/162190184-d0683fdb-4beb-4f0d-99ff-9c22a22a6979.png)
"To pick x items, type a number before selecting".

If the action in the next image is bound to a key (which it is by default)
![afbeelding](https://user-images.githubusercontent.com/26572988/162190355-97b1ccf9-1871-4ebb-9be7-9cd85d25206a.png)
the action described in the first image (inside green box) stops working, this action is bound by default to (g) in the menu.

After unbinding the action it works as implied by the hint in the first image.
Number keys work like arrow keys for 2,4,6 and 8 if the "mark specific amount of item" action is bound in the (g) menu, so pressing 6 would move the whole stack of the highlighted item to the ''items to pick up'' column.

### Steps to reproduce

1. Be adjacent to any item stack.
2. Press (g).
3. Press any number key (on any highlighted item stack).
4. Press right arrow key.

![afbeelding](https://user-images.githubusercontent.com/26572988/162191751-13c313fd-c7f2-44ce-873b-2af3f023dfef.png)

### Expected behavior

I expected that after pressing (for example) 2 and then right arrow key it would select only 2 of for example the bandages.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1586 (21H1)
- Game Version: 69830f8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Note: this has nothing to do with numlock, my keyboard has no numpad, also tried this with on-screen keyboard numpad keys in Windows 10 and behaves exactly as the 2nd row number keys on a TKL keyboard for this bug.

**Comment by Qrox** [comment]
That hint is hardcoded both in code that uses the multiselector menu and in derived classes of the multiselector menu. It will need some refactoring to properly fix all of these menus and to separate user provided hint from keybindings hint.

**Comment by mqrause** [comment]
> If the action in the next image is bound to a key (which it is by default)
> ![afbeelding](https://user-images.githubusercontent.com/26572988/162190355-97b1ccf9-1871-4ebb-9be7-9cd85d25206a.png)
> the action described in the first image (inside green box) stops working, this action is bound by default to (g) in the menu.

Just wanted to mention this is not true, it's unbound by default.
Better keybinding-aware hints would still be great, though. Currently they're pretty much static. Even the other hints in the pickup menu that use actually bound keys don't update when you change the bindings until you close and reopen the menu.
