### ISSUE TITLE
Spore-Dusted affecting Mycus

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#56653]
### Describe the bug

Mycus characters who encounter spores wind up getting hit with the spore-dusted effect, which greatly slows them for long periods of time. They necessarily spend a lot of time around fungal monsters and terrain, so this winds up being somewhat unavoidable.

Since the text of Mycus Identity reads, "We have synchronized our local physiology with that of the Mycus. Any spores we may encounter will not attempt to germinate inside the local system, and we may traverse Mycus biospheres easily, as native bioforms shift shape to accommodate us," it seems like an oversight that this condition can affect characters with the mutation. Mycus characters are already dealing with a 20% speed reduction from Mycus Fireproofing and I doubt that a total 50% speed reduction basically at all times was the intent here.

### Steps to reproduce

Make a character with Mycus Identity. Stand around in fungal fields and become too slow to fight.

### Expected behavior

Mycus Identity should protect the Mycus from its own spores.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1586 (21H1)
- Game Version: 9f22143 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by Venera3** [comment]
Good first issue, if somebody wants to take a crack. The barebones solution would amount to adding
```
    "resist_traits": [ "M_IMMUNE" ],
    "base_mods": { "speed_mod": [ -7, 0 ] },
    "scaling_mods": { "speed_mod": [ -3, 0 ] }
```
to ´data/json/effect.json´ in the definition of the effect to remove the negatives. For extra credit one could include a `reduced_desc` to tell the player it feels nice, and/or some actual bonuses to being covered (by using positive base/scaling mods as the second value).

**Comment by fairyarmadillo** [comment]
@Venera3 I've tried implementing this fix on my end. It does prevent the speed loss, however the reduced_desc doesn't show up and the effect's description still says speed -7. Is reduced_desc functioning properly? I don't see it being used anywhere else.
