### ISSUE TITLE
Attached MOLLE/PALS holsters not accessed for storing pistols

### ISSUE THREAD

**Issue by BGASM** [CleverRaven/Cataclysm-DDA#56652]
### Describe the bug

On latest experimental version save loaded with error:
`DEBUG    : error: item glock_19 cannot fit into pocket while loading: item is too long`

Character's glock was no longer stored in Tactical Holster, which was attached to a MOLLE Webbing Belt. The Tactical Holster works as expected when detached and worn on hip.

Same unexpected behavior when holster was attached to Load Bearing Vest and Load Bearing Vest with Sling.

Same behavior when attempting to holster Kel-Tec PF9.

I couldn't comb through JSON files to look for other PALS holsters to test out, but I did notice that the load bearing vests had a craft for a version with a rifle sling, and that holstering used the activate functionality. I wonder if this is related to the game not running the holster functions on attached ammo_pouches.

Edit to add: Size of both pistols were within limits for the holster.

### Steps to reproduce

1. Enter game, drop all gear
2. Debug spawn Tactical Holster, MOLLE Webbing Belt, load bearing vest, and Glock 19
3. Wear belt
4. (A)ctivate belt
5. Attach Tactical Holster
6. Wield / Unwield Glock 19
7. Fail
8. Retest steps 4-7 on load bearing vest.

### Expected behavior

Expect pop-up requesting action when unwielding pistol, specifically to store in MOLLE Webbing Belt > Tactical Holster
Expect Inventory > Examine > Insert to give me option to store pistol in MOLLE Webbing Belt > Tactical Holster

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1586 (21H2)
- Game Version: 69830f8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap],
    Blaze Industries [blazeindustries],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8445232/debug.log)

**Comment by SamGondra** [comment]
Seems to have been fixed with #56367 and/or #56655
tested in (2022-04-10-0547)
