### ISSUE TITLE
Spot Loader for multiple base

### ISSUE THREAD

**Issue by linonetwo** [CleverRaven/Cataclysm-DDA#56666]
### Is your feature request related to a problem? Please describe.

With a translocator gate, you may create multiple bases, one for living, and one for farming. Then you will need something like Spot Loader in Minecraft to keep plants on the farm growing while you are in your living room.

This will be useful too if you want to keep solar panels charging the battery while you are out

### Solution you would like.

When checking reality bubble, check the Spot Loader's location too?

### Describe alternatives you have considered.

Maybe allow all friendly to have a trait that can be toggle by chatting, that enable reality bubble around NPC with this trait?

**Comment by anothersimulacrum** [comment]
A variety of processes are updated when an area enters the reality bubble. What is the ploblom prompting this issue?

**Comment by b3brodie** [comment]
To address the farming point, this definitely does work without need for a "spot loader".  In fact, the crop growth only updates when they re-enter the reality bubble.  If they were permanently loaded somehow, they would never grow at all.

**Comment by linonetwo** [comment]
Sorry I was mostly thinking about electricity when posting this. Maybe they can be updated on re-entering too...
