### ISSUE TITLE
[innawood] Add some recipe for cable

### ISSUE THREAD

**Issue by LoganSan** [CleverRaven/Cataclysm-DDA#56676]
### Is your feature request related to a problem? Please describe.

In last update was added item - makeshift_transformer
It is crafted by cables, but only way to craft it - find raw_milk (needed for plastic_chunk -> duct_tape -> cable). Goats/Cows/Sheepes does not spawned in world (or i didn't find any way to find it), but what do you think about add recipe of cable by isolation copper_wire by rubber_chunk?

### Solution you would like.

I think this recipe should by enough:
```
  {
    "type": "recipe",
    "activity_level": "LIGHT_EXERCISE",
    "result": "cable",
    "category": "CC_ELECTRONIC",
    "subcategory": "CSC_ELECTRONIC_COMPONENTS",
    "skill_used": "fabrication",
    "skills_required": [ "electronics", 2 ],
    "difficulty": 2,
    "time": "10 m",
    "autolearn": true,
    "charges": 6,
    "qualities": [ { "id": "CUT", "level": 2 } ],
	"tools": [ [ [ "tongs", -1 ] ], [ [ "surface_heat", 1, "LIST" ], [ "forge", 1 ], [ "oxy_torch", 1 ] ] ],
    "components": [ [ [ "copper_wire", 6 ] ], [ [ "chunk_rubber", 1 ] ] ]
  },
```

**Comment by ERRORCODE509** [comment]
Farm animals to spawn from what I recall, it's just really rare.

**Comment by Light-Wave** [comment]
Farm animals spawn around ponds. But I agree that they are too uncommon. I would like to see more ways to get milk, but using rubber is also a reasonable alternative.
