### ISSUE TITLE
Basecamp zones are created on worldgen

### ISSUE THREAD

**Issue by ZombieZilla** [CleverRaven/Cataclysm-DDA#56673]
### Describe the bug

All zones defined within nested chunks in `data\json\mapgen\basecamps\expansion\` are created when a world is initially loaded, causing 120 useless NPC Ignore Sound zones to be created in the north-western corner of your starting overmap. This only creates the zones, it does not generate the structures themselves.

### Steps to reproduce

1. Create a new world
2. `Shift`+`Y` to open zone manager, `S` to display distant zones
3. 120 NPC Ignore Sound zones will be listed to the North-West

### Expected behavior

The zones should only be generated when the nested chunks are spawned

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22471.1000 (Dev)
- Game Version: 0.F-7357-ge48cccf453 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Additionally, if you Save&Exit without saving the zone manager, they will be gone permanently (Which should be fixed, for when they work as intended), but the game will still try to generate them every time you load into the world

**Comment by andrei8l** [comment]
/confirmed

This happens whenever the blueprints requirements are auto-calculated. The mapgen runs on a temp map, but the zones are applied to the real zone manager.
