### ISSUE TITLE
RC-controlled light sources does not provide light until picked up

### ISSUE THREAD

**Issue by Antrocon** [CleverRaven/Cataclysm-DDA#56679]
### Describe the bug

RC-controlled light sources (smart lamps, RC-modified lanterns) does not provide any light when active until they're picked up by player. This makes the RC-control feature quite useless, as light cannot be activated from safe distance.

### Steps to reproduce

1. Make player, debug spawn smart lamp, RC control, 2 ultra-light batteries
2. Reload lamp & rc-control
3. debug set time to 23:00
4. drop smart lamp onto tile next to you
5. press "blue" button on rc-control
6. observe name change for lamp to "smart lamp (on)", but no light provided, all cells still shown as "very dark"
7. pick up lamp, immediately observe surroundings being lighted
8. (optional) drop lamp again, confirm light still persists

### Expected behavior

expected surrounding area to be lighted by smart lamp on step #6

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1526 (21H1)
- Game Version: a8f0168 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by dragar99** [comment]
after following all the step provided the lamp did not turn on until I brought the lamp into my inventory as the bug described.

Versions and configuration
OS: Windows
OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
Game Version: 0.F-3 [64-bit]
Graphics Version: Tiles
Game Language: System language []
Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
Bionic Professions [package_bionic_professions]
]

**Comment by AustinBoyd9** [comment]
Hi there,

I repeated the above steps and found the same behavior: **the smart lamp does not emit light despite reading smart lamp (on), but picking up this lamp generates light**

Debug information:
- OS: Windows
    - OS Version: 10.0.22000.556 (21H2)
- Game Version: e0dc297 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by tonezdinny** [comment]
I can also confirm this bug, I repeated the steps and I am getting the same results as the post and the comments provided above. 

Versions and configuration 

OS: MacOS
OS Version: MacOS Monterey version 12.1
Game Version: 0.F-3 [64-bit]
Graphics Version: Tiles
Game Language: System language []
Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
No Fungal Growth [no_fungal_growth],
Bionic Professions [package_bionic_professions]
]
