### ISSUE TITLE
Mycus Fireproofing fails vs indoor fires

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#56670]
### Describe the bug

The Mycus Fireproofing mutation allows you to walk around on hot lava, endure the inside of mi-go towers, soak lasers, and stand around in outdoor infernos, but for some reason you still take a fair bit of damage if you're standing in an indoor house fire. I think it has something to do with the max level hot air fields that generate indoors, but it's hard to tell. My guess is that they're dealing damage directly in a way that bypasses the body part heat code or fire armor.

### Steps to reproduce

Debug mycus fireproofing mutation in
Set a house on fire
Stand inside
Take damage
Stand in outdoor fires, magma, napalm, etc., take no damage

### Expected behavior

The mutation should work consistently.

### Versions and configuration

OS: Windows
OS Version: 10.0.19043.1586 (21H1)
Game Version: https://github.com/CleverRaven/Cataclysm-DDA/commit/df6d5f0622522674c2fc791927e9537ee9407c6f [64-bit]
Graphics Version: Tiles
Game Language: System language []
Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
No Fungal Growth [no_fungal_growth],
Bionic Professions [package_bionic_professions]
]

**Comment by Night-Pryanik** [comment]
Closing as unconfirmed.
