### ISSUE TITLE
Disassembling oven door produces more stuff than it should

### ISSUE THREAD

**Issue by Vamael** [CleverRaven/Cataclysm-DDA#56671]
### Describe the bug

Disassembling oven door (10kg, 20L) produces, among other things, a reinforced glass sheet (137kg, 63L).

### Steps to reproduce

1. Find an oven
2. Disassemble it 
3. Disassemble an oven door
4. Make stuff from thin air

### Expected behavior

Law of physics are to be obeyed.
Pane of reinforced glass is 11,5kg and 5,3L, so maybe that was the intended result?

### Screenshots

![le bug](https://user-images.githubusercontent.com/49615683/162462426-1b755134-5524-4115-9c2c-a5366f0d43ff.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19041.1415 (2004)
- Game Version: 3d0002b [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    <color_light_green>Real Dark Skies</color> [realdarkskies],
    <color_light_red>Secronom</color> [secronom],
    <color_light_red>Secronom+ Lore Expansion</color> [secronom_lore_expansion],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    Battle Maid Redux [battle_maid],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Cataclysm++ [Cata++],
    Engineering essentials [EngineeringEssentials],
    Magiclysm [magiclysm],
    Pneumatic fun [pneumo_fun],
    Steampunk Mod [steampunk_arcanum],
    Wandering Masters [wandering_masters],
    XEAS [XEAS],
    Adurnsyl's Assorted Arms and Armour [AAA],
    Advanced Technologies [advtech],
    Aftermarket Leadworks [aftermarket_leadworks],
    Alexs Mutant Power Armor [mutated_arsenal],
    Anti-fungicidal equipment [anti_fungicidal_equipment],
    Armor Up! Survivor Expansion [ArmUpSurvEx],
    Arsenal Breach [arsenal_breach],
    Artyoms' Gun Emporium - Reloaded [Arts' Guns],
    BioCo Content [bioco],
    Bionic Space Expander [Bionic_Space_Expander],
    Bootleg Walkers [Bootleg_Walkers],
    Cataclysm: Second Chance [expansion_tefnut],
    CBM Equipment [CBM_Arms],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    Crude & Improvised Items [crude_improvised],
    ETC Handguns etc [ETC_handguns_etc],
    Fallout New England [fallout],
    Generic Guns [generic_guns],
    Gun Cotton [guncotton],
    Homemade Fungicide [homemade_fungicide],
    Homestead Instruments Inc. [homestead],
    Icecoon's Arsenal [ew_pack],
    Locked and Loaded [Locked_and_Loaded],
    Makeshift engine hoist [makeshift_engine_hoist_mod],
    MakeshiftCanteen [MSCanteen],
    Modern Weapon Pack Expanded [modern_weapon],
    MST Extra [MST_Extra],
    Nimian Manufacture Guns [NM_wpns],
    Pressure Weapons [pressure_weapon],
    Project APEX [apex],
    Ricky's Future Armory [futurearmory],
    Scaly Duds [ScaDu],
    Tefnut's Expansion: Magiclysm Items [expansion_tefnut_magiclysm],
    Compatible Add Bandits [GOV_BANDITS],
    DinoMod [DinoMod],
    More Monsters [mo_monsters],
    Mutant Animals [mutant_animals],
    Mutant Insects [mutant_insects],
    World on Fire [World_on_fire],
    Mythical Martial Arts [MMA],
    <color_yellow>Mythical Martial Arts - Mods Extension</color> [MMA_Mods_Extension],
    Alternative Map Key [alt_map_key],
    CDDA Variety Pack [ks_variety_pack],
    Collapse beneath [Collapse_beneath],
    Extra Mutated Scenarios [extra_mut_scens],
    MoDK [MoDK_ID],
    Monstergirl Professions [monstergirl_professions],
    No name () [],
    More Survivor Stuff [more_survivor_stuff],
    Mythical Martial Arts - Magiclysm [MMA_Magiclysm],
    NPC Recruitment Options [recruitment_options],
    Tekitou Map Commercial Overhaul [tekitoumap],
    Vampiric Stuff [vamp_stuff],
    Vampiric Stuff + Arcana Mod Extension [vamp_stuff+arcana],
    Alternative Basement Layouts [basement_extension],
    Beta National Guard Camp [national_guard_camp_alt],
    EXTENDED_BUILDINGS [ZSFixed_Extended_Buildings],
    More City Locations [cityside],
    Prepper Caches [prepper_cache],
    Sarcophagi Access [sarcophagi_access],
    Ships From Oa Additional Buildings [Ships],
    Trailer Parks [trailerpark],
    Folding Parts pack [deoxymod],
    Greiger Vehicles [greicars],
    Roadheader and other mining vehicles [Heavy miners],
    Shrub it off [shrub_mod],
    Tankmod: Revived [Tankmod_Revived],
    Miscellaneous Magiclysm Expansions [demon_spider_a],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Abrahms Recipes 1 [AbrahmsRecipes1],
    Merchant Mod [Merchant],
    Road Warrior Mod [madmax],
    Whaleys Hair Mod (UDP Tweaks) [WHALEYHAIR_UDP],
    Bionic Slots [cbm_slots],
    Fewer Farms [Fewer_Farms],
    Magiclysm No Class Limit [magiclysm_no_class_limit],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    Sly's Mutation Revamp Station [sly_mutation_revamp],
    Sly's Mighty Morphin Mutation Station [sly_mutation_improvements],
    Stats Through Kills [stats_through_kills],
    Useful Helicopters Experimental [useful_helicopters],
    ZSFIXED_C:DDA Extra Professions & Gears [ZSFIXED_cddaxp]
]

### Additional context

Json from the screenshot is taken directly from the github repo. 
Is there a test that checks wheter disassembled recipes don't produce more stuff than the thing they are made of?

**Comment by haveric** [comment]
The glass in ovens would more likely be tempered glass rather than bulletproof reinforced glass, but we only have tempered_glass_sheet as far as I can tell, which is far too big as well to be what is used in most ovens as far as I can tell. I'm not sure if making a smaller sheet to be used in ovens makes sense here, but it might be an option, but it would then need to have more uses added for it.

**Comment by chrispikula** [comment]
It should probably be a pane of reinforced glass instead.
