### ISSUE TITLE
Canola has no use (Biodiesel related)

### ISSUE THREAD

**Issue by Traple** [CleverRaven/Cataclysm-DDA#56688]
### Is your feature request related to a problem? Please describe.

Canola oil has no use and as far as I am aware can't be found in-game. 
https://nornagon.github.io/cdda-guide/#/item/canola

### Solution you would like.

First the player has to be able to find Canola (either in the wild or in certain locations). I don't think I've ever found Canola in-game, I'm not a 100% sure it doesn't exist.

Implement canola as a plant that can be found in the Cataclysm that has a use in the Biodiesel recipe (or is an alternative biodiesel recipe).
Another way to do this might be to make a recipe that turns canola into vegetable cooking oil. This way it can be used in the biodiesel recipe.

I am by no means an expert in the petrol industry, so if this is not realistic / possible to be done by someone in game I suggest removing canola from the game (because it doesn't do anything gameplay wise). 

### Describe alternatives you have considered.

Remove canola from the game files.

### Additional context

I have no idea how difficult this is to implement, if this takes a lot of work removing the item might be a better option (I don't think it will have that much gameplay effect).

**Comment by merrygin** [comment]
It's the canola seeds that you can use for veggy oil (and the veggy oil then to produce biodiesel).
However, there is **no recipe to produce canola seeds** in seeds.json. 

It would be very simple matter of copying an entry for another vegtable there and just replace the other vegtable's name with "canola". Would be a very good first issue!

**Comment by Traple** [comment]
Creating a new vegetable with a seeds recipe sounds like a great solution. 
Does that automatically place it in loot tables / foraging locations? For foraging does it also requires specific seasons in which you can find / harvest canola?
Does that also mean that canola's can be planted / farmed or does that require additional work? 

If someone would like to take the honours of turning this into a PR, feel free!

**Comment by SamGondra** [comment]
Canola Seeds are in the game (experimental 2022-04-10-0547) - there is no seed recipe because you harvest only seeds from the plant when planted. Oil recipe is also in.
What I don't know if it is possible to find besides foraging, I at least can't find any refences in JSON for it, not sure if 'Hitchhiker's Guide to the Cataclysm' intentionally leaves out foraging.

**Comment by Traple** [comment]
You are right, my mistake. It is possible to forage canola seeds, plant them and you harvest the seeds directly. According to Hitchhiker's it is not possible to find them anywhere else in the world besides foraging (maybe we should change this?). 

It is still weird that there is a canola entry even though we only have and use seeds. Is this used in some hidden values or something? If not maybe we can delete this entry (if we only need the seeds anyway)?

![canola forage](https://user-images.githubusercontent.com/5754894/162618717-d960943e-e7e8-46ca-b2d8-8ddd50a017d6.JPG)
