### ISSUE TITLE
Reduce memory usage

### ISSUE THREAD

**Issue by throwaway1037** [CleverRaven/Cataclysm-DDA#56683]
### Describe the bug

CDDA uses a lot of RAM at times.
By lazily loading data as needed, eg. tiles, JSON data, etc. the game could initially load quicker and take up a lot less memory whilst being played.

### Steps to reproduce

1. Play game
2. Observe long loading times and high RAM usage.

### Expected behavior

The game loads quicker and uses less RAM.

### Versions and configuration

- All(?)

**Comment by anothersimulacrum** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/issues/50344

**Comment by throwaway1037** [comment]
The game as a whole uses lots of RAM because data is not loaded lazily, I presume.

**Comment by MylieDaniels** [comment]
I would just like to put it out there that this user has been banned from making issues on numerous game repositories (I notably remember them from Mindustry) for repeatedly making broad feature requests and labeling them bugs, fighting about why devs should magically have the ability to resolve those requests, and trolling.

**Comment by throwaway1037** [comment]
@MylieDaniels, this is false.
I made a specific bug report about software freedom which the devs disagreed with and therefore interpreted as a feature request.
Unfortunately, that particular dev also interpreted a discussion about licensing and software freedom as "trolling".

**Comment by BrettDong** [comment]
> That is the root cause of the issue.

Have you profiled heap usage to come to this conclusion?

**Comment by ZhilkinSerg** [comment]
No need for guesses here, if you want this issue to be actionable - go and profile, then work on making memory footprint smaller.

**Comment by kevingranade** [comment]
If you don't have a specific and actionable recommendation, this is not a valid issue.
