### ISSUE TITLE
Line of sight behind walls parallel to a door

### ISSUE THREAD

**Issue by Sheco** [CleverRaven/Cataclysm-DDA#5668]
When peeking around corners, your character is exposed to the enemies, at the moment you exit the look around mode. There's a visual anomaly too.

How to reproduce, place an enemy turret following the friendly sample layout included here.

```
    +------
    |
    |@
2   '
    |
    |
    +------
```

Peek down, move the cursor anywhere you want. (X, down, then look around)
After pressing escape or q, your character will be placed at the look around cursor, getting damage from the turret.

The first issue is the visual glitch, where your character is placed at the look around cursor. This seems to be only a visual representation mistake, your character actually is in the location you're peeking, which is in sight and range of the turret.

It doesn't matter where your cursor is, you'll be hit by the turret.

**Comment by kevingranade** [comment]
My recent overhaul forces monster vision of the player to match the player's vision of monsters, so now you can see into the building the same way, but the monster can see you as well.
In some ways this makes monster/player vision even more asymmetric, but it makes it reciprocal.
