### ISSUE TITLE
on android i get white lines everywhere!

### ISSUE THREAD

**Issue by themadrpgfan** [CleverRaven/Cataclysm-DDA#56680]
### Describe the bug

so when i use any tileset i get these white or black lines it changes depending on terrian and tile set its seriously irretating and i for some reason cant fix it regardless of what i do

### Steps to reproduce

no idea because ive been only mildy able too find others with the issue

### Expected behavior

clear screen

### Screenshots

![Screenshot_20220408-153544_Cataclysm_DDA_experimental](https://user-images.githubusercontent.com/103291656/162544839-d5d9f536-4adb-42d4-ab5b-750633cd038b.jpg)

### Versions and configuration

latest expimental and im using the undeadpeople tileset mainly

### Additional context

doesnt crash so i go no clue

**Comment by themadrpgfan** [comment]
note i tried it with everything exactly on the pc version and on there no lines
so its only on android i suppose

**Comment by Zireael07** [comment]
It's not an Android specific issue - people have had it on PC too. I can't find other reports right now but that's due to something called IIRC tile bleed where the renderer grabs pixels outside of the tile it's supposed to (that's why many games have a margin of 2-3 px between individual tiles)

**Comment by themadrpgfan** [comment]
So how do I fix it?

**Comment by Zireael07** [comment]
People have had success switching to the other renderer (if they had the issue on OpenGL, they picked DirectX, and the other way around)

**Comment by themadrpgfan** [comment]
How do I changerenderer on android? Anytime I enable software renderer it crashes

**Comment by themadrpgfan** [comment]
And it's unopenable

**Comment by NetSysFire** [comment]
On a PC I would advise you to get your text editor out and edit the json file containing the config. Unfortunately due to Androids nature you can not edit raw configs without root, so you may need to purge the apps data (not cache) which will also delete your worlds. If you have not done anything you want to keep yet, just go for it. If not, I would check the internal storage for your worlds perhaps, because I do the exact path the app where the worlds are saved and you might be lucky and can backup them before purging the apps data.

**Comment by themadrpgfan** [comment]
I'm confused I don't really know what any of that means:(

**Comment by themadrpgfan** [comment]
How exactly do I do that

**Comment by themadrpgfan** [comment]
I cleared my data and reinstalled my tileset and white lines still:(

**Comment by themadrpgfan** [comment]
And what's need confirmed mean

**Comment by NetSysFire** [comment]
Now you can at least start cdda again and experiment with the renderer and related settings

**Comment by themadrpgfan** [comment]
And there's noway too change renderer on android

**Comment by themadrpgfan** [comment]
So I'm very confused on what to do still

**Comment by NetSysFire** [comment]
alright, lets start with the simple stuff. what android version is this? did you try turning your device off and on again? is it fully updated?

**Comment by themadrpgfan** [comment]
Latest version it's a Samsung galaxy tablet 8a 10.5 and yes I have

**Comment by NetSysFire** [comment]
"Latest version" gets old really quickly. What is the exact android version?

**Comment by themadrpgfan** [comment]
Leg me check

**Comment by themadrpgfan** [comment]
Android version 11

**Comment by themadrpgfan** [comment]
What next

**Comment by Kalvenor** [comment]
> What next

Have you found any solutions? I'm experiencing the exact same problem and UDP tileset is the one which reduces it the most. Is there a way to change renderer on Android other than changing between hardware and software ones? And which config file are we talking about here that needs to be edited?
