### ISSUE TITLE
lore tab acting up.

### ISSUE THREAD

**Issue by mrduck-ux** [CleverRaven/Cataclysm-DDA#56692]
### Describe the bug

My character currently has 9 lore entries I have not actually found. The majority of them revolve around cooking mutant body parts, and the final one is from a pair of denim shorts.

### Steps to reproduce

I unfortunately have no idea how to reproduce this. My initial thought was that it was related to me cooking meat, but at some point 2 of them got added without me cooking meat.

### Expected behavior

The expected behavior is to not get random bits of lore that I haven't found.

### Screenshots

![Screenshot_20220409-082402_6fe8938556442e3d4f710ab4f9a16601](https://user-images.githubusercontent.com/67364151/162574044-0ca35189-2623-4ba9-a8b7-70fbab988950.jpg)

### Versions and configuration

OS: android 11
Game version: 8c92c6d
Graphics: tileset (UltiCa)
In-game language: system language (English)

**Comment by bombasticSlacks** [comment]
Yeah we need to flag lore vs non lore snippits. It isn't hard just tedious work so I haven't gotten to it.
