### ISSUE TITLE
Suggestion: Increase duration between Portal Storms, their lenght and the severity of effects they cause.

### ISSUE THREAD

**Issue by Jan-Blasiak** [CleverRaven/Cataclysm-DDA#56700]
### Is your feature request related to a problem? Please describe.

Currently Portal Storms are just an another type of weather, a nuisance which forces you to take shelter for a few hours every week.

This is definitely what such monumental disasters **_SHOULDN'T_** look like.

### Solution you would like.

Portal storms should be events which fill player with both dread and avarice, they should be rare events, which would both pose considerable risks, and allow player to gain unique boons.

This is just a quick blurb, brought by dissatisfaction with portal storms. I could debate on-and-on what could be included, which many people probably have, but I have no idea to the game's limitations.

What I can say, is that Portal Storms currently feel too common, too short and too boring. They are just a type of weather in which you REALLY should stay at home.

I'd love to see them expanded.

### Additional context

Game is becoming better and better every day!

Keep it up!

**Comment by shenmuyunzhuang** [comment]
I think the storm should be suspended or there should be a weak period of time for players to venture out to perform tasks. At present, the intensity of the storm is unacceptable

**Comment by Myfharad** [comment]
I agree, if the player knows how to play around them its just "go inside and hide until weather changes", and rather than feel special or scary it just becomes an annoyance
