### ISSUE TITLE
Allow the player to ask Rubik about Zomborg and Quadroped guarded structures

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#56702]
### Is your feature request related to a problem? Please describe.

I've seen sites "guarded" by Exodii Quadropeds and Zomborgs, but I've kept away from the because I (and my character in particular) doesn't have any idea whether investigating them would annoy the Exodii.
It would be useful to have a question about these as one of Rubik's conversation topics.

### Solution you would like.

Tell Rubik that you've seen small structures that has some resemblance to the Exodii "fortress", with some of them guarded by quadupeds, and some by something hostile that vaguely resembles Exodii workers, and you'd like to know what they are and what their relations to the Exodii is.

It would be even better if such a question would be unlocked only if you've actually encountered any such structures.

### Describe alternatives you have considered.

Continue playing to see if Rubik eventually comes up with a quest or something that clarifies things. So far I've traded for everything he's got that's even sort of useful, but the inventory hasn't been turned over yet, despite it being a fairly long time since I met him the first time (almost a month, at a guess. Got a cold that cleared up in the mean time). I've also had a bunch of CBMs installed by him, which may or may not contribute to the trade value. Thus, I guess I'm not too far into his quest line.

**Comment by fairyarmadillo** [comment]
Over [here](https://github.com/CleverRaven/Cataclysm-DDA/pull/56540) you can see that I_am_Erk seems to refer to them as drop pods. Putting furniture or other decorations around that would clarify their purpose, and maybe having some be broken open to show the inner workings would be cool.

**Comment by PatrikLundell** [comment]
Yes, I, the player, sort of know these are pods (I overstated my own ignorance a little above. Sorry if that led you to waste time helping out), and signs indicating how to reach Rubik strengthens the connection (apart from being constructed similarly and having quads around them), but that still doesn't tell the PC what they are or what the PC is allowed to do with them. Am I allowed to kill the zomborgs? Am I even encouraged to do so? May I open the as yet unrecovered pods?

**Comment by bombasticSlacks** [comment]
You can use the new snippet trigger system. So that after inspecting certain items, monsters, or notes that triggers a variable so you know to ask RUBIK

**Comment by fairyarmadillo** [comment]
I wasn't just trying to explain that to you OOC, I was mentioning it as it seemed like information relevant to the issue if someone other than I_am_Erk wanted to address it.

**Comment by NetSysFire** [comment]
Pinging @I-am-Erk here because their opinion is needed and assigning them would be inappropriate.

**Comment by MNG-cataclysm** [comment]
> You can use the new snippet trigger system. So that after inspecting certain items, monsters, or notes that triggers a variable so you know to ask RUBIK

Where could I find an example of this new system?

**Comment by I-am-Erk** [comment]
This would be very appropriate to add to the game, but yeah it should be governed by variables that activate when you encounter  these things. I'd be happy to write Rubik's dialogue for anyone that wants to do the JSON part.

**Comment by MNG-cataclysm** [comment]
@I-am-Erk I could do the JSON part, and put it in another draft. 

Also, your concatenate line in #62335 disappeared while I was fixing bugs. Could you re-add that, please?

**Comment by MNG-cataclysm** [comment]
@bombasticSlacks Do you know where the snippet trigger system is used?
