### ISSUE TITLE
More specialised woodworking recipes

### ISSUE THREAD

**Issue by ZombieZilla** [CleverRaven/Cataclysm-DDA#56718]
### Is your feature request related to a problem? Please describe.

#56628 added a lot of working machines to the appliance system, however a lot of them are lacking many recipes, leaving little point to actually set them up inside your base. 

### Solution you would like.

Potentially for some recipes to be changed to require those machines specifically, or for new recipes to added entirely.

### Describe alternatives you have considered.

Doing it myself

**Comment by PatrikLundell** [comment]
The longer term goal should be to have recipes make use of these machines as tools, and have such tools decrease the time and effort it takes to perform the task.

Until that support is present, the work around would be to introduce machine specific (or, rather, machine property specific) recipes that have these benefits. There are currently a small number of companion crafting recipes for base camps (workshop expansions) that do this with a drop hammer.
