### ISSUE TITLE
Charcoal from Charcoal Kiln disappears when reloaded to a nearby smoking rack

### ISSUE THREAD

**Issue by jeffplata** [CleverRaven/Cataclysm-DDA#56725]
### Describe the bug

Charcoal from the charcoal kiln disappears (as if applied or used) when reloading a nearby smoking rack. (E)xamining the nearby smoking rack does not enable the option to light up the rack, just asking for more charcoal reloads. Repeatedly examining the smoking rack diminishes the quantity of the charcoal in the kiln until there is not enough to load the smoking rack.

This does not happen if the charcoal is first ~~removed from the kiln~~ put into inventory. We first examine the kiln after burning charcoal, then the charcoal 'surfaces' and it becomes available for use with the nearby smoking rack, but then the bug described above happens.

### Steps to reproduce

1. Build a charcoal kiln
2. Build an adjacent smoking rack
3. Finish burning charcoal in the kiln
4. Insert some food to be smoked in the smoking rack
5. Examine the kiln
6. Examine the smoking rack and fill it with charcoal from nearby kiln
7. Examine again the smoking rack; option to light is not available
8. Load charcoal again; Quantity of charcoal loaded is deducted from the kiln

### Expected behavior

The option to light the smoking rack should be enabled after full loading it with charcoal from nearby kiln.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1586 (21H2)
- Game Version: a8f0168 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Hope [no_hope]
]

**Comment by Traple** [comment]
I think this is related to #56689? I've had this problem before as well.
