### ISSUE TITLE
CTD on Wayland when changing window fullscreen with scaling >1

### ISSUE THREAD

**Issue by adlainewson** [CleverRaven/Cataclysm-DDA#56724]
### Describe the bug

On Wayland, with scaling set to >1: 
    - setting Fullscreen to "Maximized" produces immediate CTD on launch. 
    - setting Fullscreen is set to "Fullscreen" or "borderless window", game launches in fullscreen but CTD when changing window state using the WM
    - setting Fullscreen to Off game launches normally but ignores scaling
 
All the CTDs give the same "Arithmetic Error." The CTDs do not occur on my same system and same config, but using XWindows.

### Steps to reproduce

Launch game on Wayland with Fullscreen option set to Maximized and scaling>1,
OR
Launch game on Wayland with Fullscreen option set to Yes and scaling>1, then exit fullscreen using WM
OR
Launch game on Wayland with Fullscreen option set to borderless window and scaling>1, then exit fullscreen using WM

### Expected behavior

no CTD

### Screenshots

Resizing game window lower than threshold produces immediate crash

![2022-04-10T09:25:00,818980403-07:00](https://user-images.githubusercontent.com/10458698/162629483-dded885b-53b7-4d19-a22f-e72f2c5ccd6b.png)
![2022-04-10T09:25:23,024017628-07:00](https://user-images.githubusercontent.com/10458698/162629480-63ea1aba-12ad-4785-af07-23b5a77efc2c.png)

### Versions and configuration

OS: Arch Linux, kernel 5.17
WM: sway 
Game version: 0.F, Tiles

### Additional context
Tried both opengl and software renderers.

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8458498/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8458509/debug.log)
[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8459409/config.zip)

**Comment by andrei8l** [comment]
Can't reproduce on mutter with either `SDL_VIDEODRIVER=wayland` or `SDL_VIDEODRIVER=x11` . Your crash log indicates a zero-sized window (or no window), which might be a sway or SDL issue.

Can you upload your config folder?

**Comment by adlainewson** [comment]
Interesting. config dir now attached above.

**Comment by adlainewson** [comment]
I managed to reproduce this crash on Xwindows, again by shrinking the window below a threshold when using an ingame fullscreen setting other than Windowed

**Comment by Qrox** [comment]
It seems your window is 78 characters wide when it crashed. A minimum size of 80 characters is set during initialization, but it seems your system ignored it, which may have caused something to go wrong.

My guess is that in `main_menu::init_windows`, `w_open` is created with `( TERMX - total_w ) / 2` as the x coordinate, which when `TERMX` is below 79 becomes negative. In `catacurses::newwin` in `cursesport.cpp`, an null window is returned when the x position is negative, which has a zero width, so in `main_menu::print_menu_items`, dividing by the window width causes a division-by-zero error.
