### ISSUE TITLE
More things should satisfy pyromaniacs.

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#56738]
### Is your feature request related to a problem? Please describe.

Pyromaniacs are satisfied when they light fires with matches or lighters, but that's about it. The pyromania debuff hits multiple times a day and while it's not hard to keep a brazier and some wood splinters nearby, it would feel more consistent and better motivate certain playstyles if a few more common fire-related activities satisfied pyros.

### Solution you would like.

Off the top of my head:
- [ ] Working a forge
- [x] Using the bionic firestarter
- [x] Firing a flamethrower 
- [x] Firing a dragon's breath shotgun round
- [x] Setting off molotovs or incendiary grenades
- [x] Lighting enemies on fire (IE with lasers)
- [x] (Magiclysm) Casting spells that produce or create flames
- [ ] Using an acetylene torch to weld or cut metal
- [ ] Killing a gasoline zombie or other similar enemy and causing a fireball
- [x] Starting up a charcoal or brick kiln (portable or furniture version)
- [x] Starting up a charcoal smoker

### Describe alternatives you have considered.

Pyros could get the urge less often, which would make it less of a repetitive chore so we wouldn't need the variety. The above changes might also require a reduction in the points given by the trait at chargen.

Pyromania IRL is also treated with psychiatric care, namely anxiolytics and antidepressants. Maybe those could stave off the effects but blunt the benefits?

**Comment by Cerberus1746** [comment]
I would even say that putting fire out should give a mood de buff

**Comment by fairyarmadillo** [comment]
I'm not sure whether real life pyromaniacs are made unhappy by the act of extinguishing a fire. From what I can find online, many actually become firefighters, and while that's obviously putting them in a position to cause problems and hurt people, there's nothing to suggest that the act of putting a fire out is especially stressful to them.

**Comment by Cerberus1746** [comment]
That is true, but I mean to avoid people being like "light a fire, put out the fire, light the fire, put out the fire, light the fire, put out the fire"

**Comment by fairyarmadillo** [comment]
I feel like tying pyromania satisfaction to varying levels of player-caused destruction would handle that in a realistic manner.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
