### ISSUE TITLE
(Experiment Scenario) Gills Trait Can Not Be Picked

### ISSUE THREAD

**Issue by Kusbasili** [CleverRaven/Cataclysm-DDA#56737]
### Describe the bug

The gills trait can not be picked in the Experiment scenario even with no other traits/mutations selected, it counts towards your advantage points limit but resets when the tab is switched

### Steps to reproduce

1. Make a new world
2. Make a new character
3. Pick the Experiment scenario
4. Attempt to pick the Gills trait/mutation

### Expected behavior

I expect to be able to pick the gills trait because the gills trait is on the traits list.

### Versions and configuration

Version 9f9b09d (tiles)
Build 2022-04-10-0547

**Comment by NetSysFire** [comment]
Closing in favor of #57748.
