### ISSUE TITLE
Help from Nursebot is way overtuned

### ISSUE THREAD

**Issue by Fris0uman** [CleverRaven/Cataclysm-DDA#56742]
### Describe the bug

Nursebot  are supposed to provide a small bonus to surgery success chance but seem to instead provide a huge bonus and make any surgery an almost guaranteed sucess

<https://youtu.be/zsqhZX69xWk?t=846> see Vorm going from 64% of failure to 4% with the nursebot.

I don't know if I messed up my testings in https://github.com/CleverRaven/Cataclysm-DDA/pull/36798 or if something changed since then but this should probably be tuned down

### Steps to reproduce

1. Get a Nursebot to help
2. See chance of failure go down drastically

### Expected behavior

See chances of failure go down by maybe 10% but not 60%

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1586 (21H1)
- Game Version: 0.F-7411-g9f9b09d90d-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]
]

**Comment by toweroglass** [comment]
I was about to comment that i didn't notice anything crazy while removing cbms from my prototype cyborg. I have ready access to a autodoc with or without a nursebot. But maybe the formula is not the same for install and uninstall?

**Comment by haveric** [comment]
> I was about to comment that i didn't notice anything crazy while removing cbms from my prototype cyborg. I have ready access to a autodoc with or without a nursebot. But maybe the formula is not the same for install and uninstall?

The nursebot only provides assistance if you are wearing a doctor's badge. If you're not, there is no bonus.

**Comment by haveric** [comment]
From what I'm seeing, this was additive when https://github.com/CleverRaven/Cataclysm-DDA/pull/36798 got implemented :
https://github.com/Fris0uman/Cataclysm-DDA/blob/4fa8ade2acc139f958117fe69f079732c3b565f5/src/bionics.cpp#L1610

I'd be willing to take a look at this tonight, but I'll have to dig into the code some more and do some thorough testing to make sure everything working as it should.
