### ISSUE TITLE
Mutation "Pain Recovery" is not working

### ISSUE THREAD

**Issue by waveyl** [CleverRaven/Cataclysm-DDA#56759]
### Describe the bug

Mutation "Pain Recovery" is not working.

### Steps to reproduce

Debug:

without Pain Recovery
1. Set pain value to 5000
2. wait for 30 minutes
3. See pain value is 4428

with Very Quick Pain Recovery:
1. Set pain value to 5000
2. wait for 30 minutes
3. See pain value is 4428

### Expected behavior

Result of second case is lower than first one.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1620 (21H2)
- Game Version: b54ab40 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Seems caused by #35300

**Comment by AustinBoyd9** [comment]
Hi there,

After repeating the above steps I can confirm that the "very quick pain recovery" mutation does not improve the amount of pain recovered after 30 minutes.

Debug Info:

- OS: Windows
    - OS Version: 10.0.22000.556 (21H2)
- Game Version: e0dc297 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
