### ISSUE TITLE
Introduce an unsorted transportation zone

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#56750]
### Is your feature request related to a problem? Please describe.

When moving loot from looted placed I first move it to somewhere (a pile in the case of a lab, a foldable shopping trolley for "normal" looting. etc. It would be useful to be able to paint a normal Unsorted Loot zone over the source pile, then Unsorted transport zones tied to my transport vehicle, and then sort the loot to move everything in the Unsorted zone onto the vehicle's zones.
Once at the destination, disable the new zones and either use Unsorted zones on the vehicle (or enable such zones), or park on top of a fixed unsorted zone (which may sort away things you actually want to keep in the vehicle).

AIM works well when the source and target are both in range, while dropping stuff from the inventory has the rather annoying property of falling through the bottom of the vehicle when the tile gets full, which is easy to miss, and then have to be moved to an unfilled tile (typically with AIM). That can also be rather costly in time if you're dealing with large amounts of "handle one item at a time" items, such as rags. Clearing out tailoring supplies can take hours because of that, and you don't want to move things more times than you absolutely have to.

### Solution you would like.

The introduction of a new zone type that acts as a target for everything in Unsorted zones. It would have a lower priority than dedicated zones. It would be a bonus if it also served as a regular Unsorted zone for items that have "proper" zones defined, which would mean that you didn't even have to flip zones back and forth on your vehicle.

### Describe alternatives you have considered.

Make custom zones that serves the purpose above. There's a lot of typing, though, although I guess it's possible to save the string elsewhere for reuse.

Another alternative would be to add a flag to Unsorted zones that would allow you to turn one of those into the new type.

**Comment by andrei8l** [comment]
A custom zone with an empty filter already works like this, doesn't it? You can bind it to a vehicle as well.

**Comment by PatrikLundell** [comment]
I tested a static empty custom zone, and it worked as @andrei8l described. Problem solved!
