### ISSUE TITLE
Gun deleted when wielded from a holster and then replaced in the same now-filled holster

### ISSUE THREAD

**Issue by Sutremaine** [CleverRaven/Cataclysm-DDA#56752]
### Describe the bug

Game throws an error message when unwielding a gun into a holster, silently deletes gun.

 DEBUG    : tried to put an item (glock_22, amount -1) in a container (survivor_belt_notools) that cannot contain it

 FUNCTION : int item::fill_with(const item&, int, bool, bool, bool)
 FILE     : src/item.cpp
 LINE     : 11334
 VERSION  : e31f874

### Steps to reproduce

1. Have a character with a gun (3.21c, 1.09kg) in a holster (survivor belt) and not much remaining storage on their person.
2. Wield the gun. Pick up some random stuff until the holster is occupied. Item here was two roach eggs (2.00c, 0.60kg).
3. Wield the gun again, bringing up the prompt to select a container. Pick the survivor belt (holster is 4.00c and 2.00kg, min volume 1.200c).

### Expected behavior

Gun remains in hand and does not get deleted or auto-dropped.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1586 (21H2)
- Game Version: e31f874 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Sniper27IT** [comment]
I'm having this too, it happens even if you don't place anything else inside the survivor belt. The only way i'm dealing with this is to avoid the holster prompt when unwielding the gun/weapon (i lost 3 combat knives and 2 glocks this way), open the inventory, go to the belt menu and use "insert". You can also use the (A)ction menu and choose the belt, it brings up another storage/draw prompt safe to use

**Comment by Hirmuolio** [comment]
Most likely related to #56609

**Comment by iceblaster** [comment]
Chiming in to say I've had this happen with other objects besides guns in survivor belts, as well as with a regular tool belt.
