### ISSUE TITLE
Magiclism+CRIT matrial bug

### ISSUE THREAD

**Issue by Relvl** [CleverRaven/Cataclysm-DDA#56766]
### Describe the bug

'CRIT blade-work' style wont works with an enchanted melle knives from the Magiclism, at least with:
```
        "knife_combat_plus_one",
        "knife_combat_plus_two",
        "knife_hunting_plus_one",
        "knife_hunting_plus_two",
```

Weapons: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/mods/Magiclysm/items/enchanted_melee.json
Martial (style_crt_blade): https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/mods/CRT_EXPANSION/martial/CRT_Bladework.json

![image](https://user-images.githubusercontent.com/4003026/162986218-c441eaa0-b8b1-4ebf-a47e-89c31020d33a.png)

### Steps to reproduce

Make player with CRIT style perk, select the CRIT blade-work, debug add any magiclism's enchanged knife-like weapon.

### Expected behavior

CRIT blade-work should works with +1 and +2 combat knife and similar knife-like weapons from the magiclism.

### Versions and configuration

Game version: latest experimental (2022-04-12-0728)
Mods loaded: CRIT_EXPANSION, Magiclism

**Comment by NetSysFire** [comment]
afaik CRIT will be replaced by a new mod, see #56480

**Comment by Maleclypse** [comment]
Closing as CRIT has been obsoleted.
