### ISSUE TITLE
Chainmail coif cannot be worn under other helmets due to being considered rigid

### ISSUE THREAD

**Issue by Sirbab** [CleverRaven/Cataclysm-DDA#56774]
### Describe the bug

Chainmail coifs, and reportedly a kevlar helmet liner cannot be worn in conjunction with other rigid helmets, which entirely defeats the purpose of such items.  This is due to chainmail being considered a rigid type of armor, which at face value doesn't seem to make much sense.  This extends as far as i can see to all chainmail pieces.

### Steps to reproduce

1: Spawn a character with a chainmail coif, and chitinous helmet. 
2: Put on chainmail coif, then try to wear the chitinous helmet.
3: Observe the game telling you that you cannot wear two rigid forehead items at once.

### Expected behavior

I would expect that this would work like it did months ago, wherein chainmail was flexible and able to be worn comfortably under more rigid armors.

### Screenshots

![image](https://user-images.githubusercontent.com/1490991/163089975-376d4af7-4962-4058-8f12-e52618864047.png)
![image](https://user-images.githubusercontent.com/1490991/163090026-653cb9b2-f4b0-4d28-b5c0-00bd731e53f3.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1586 (21H1)
- Game Version: 2b38de5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

### Additional context

As an aside, is it intended that chainmail armor is worn in the outer layer? By normal layering, this means you would be wearing chainmail over other armors or helmets, which doesn't make any sense to me.

**Comment by Maleclypse** [comment]
So for chainmail coif I imagine it would go on normal layer, you'd have a liner under it on inner layer and then any other helmet you use on the outer layer.

**Comment by Sirbab** [comment]
> So for chainmail coif I imagine it would go on normal layer, you'd have a liner under it on inner layer and then any other helmet you use on the outer layer.

At the very least some helmets already exist on the normal layer, so if that was done, i'd suggest an audit of helmet layers such that this doesn't become a different problem.

**Comment by Maleclypse** [comment]
Some helmets probably shouldn’t allow chain mail coifs under them. I imagine modern army helmets might have issues working well with it.

**Comment by DalenTalas** [comment]
> Some helmets probably shouldn’t allow chain mail coifs under them. I imagine modern army helmets might have issues working well with it.

I work with chainmail, and I see no problem whatsoever. Other than ensuring the helmet and chin strap are of the right size.

**Comment by Maleclypse** [comment]
![suspension helmet](https://user-images.githubusercontent.com/54345792/163582118-da8ef9f0-247f-4608-8a28-7e94a84736ea.png)

Anything with a suspension system wouldn't really work with chainmail coif.

**Comment by DalenTalas** [comment]
![image](https://user-images.githubusercontent.com/74809740/163583944-40106ef2-d767-43e1-a81a-bdd064723ec2.png)

Don't see why.

**Comment by Maleclypse** [comment]
> ![image](https://user-images.githubusercontent.com/74809740/163583944-40106ef2-d767-43e1-a81a-bdd064723ec2.png)
> 
> Don't see why.

That’s excellent thank you for sharing exactly the helmet I believe should be able to go on the outer lair and not conflict with chain mail.   Glad to see we are in agreement.

**Comment by Aithron** [comment]
I discussed this with some of the folks in the dev discord and I’ll be working on this and a few other edge cases over the next few days.

**Comment by anoobindisguise** [comment]
I fixed this a long time ago by making Chainmail non-rigid (but still uncomfortable to wear on bare skin) so this can be closed.
