### ISSUE TITLE
[$185] Bandaging while danger near doesn't stop bandaging, even to death.

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#56776]
**-->** #53644 **<-- All discussion should happen there**

I am sorry. Due to technical difficulties the total bounty amount for the [bounty](https://app.bountysource.com/issues/105211069-bandaging-while-danger-near-doesn-t-stop-bandaging-even-to-death) I posted on #53644 is displayed incorrectly ($0 instead of $185). The bountysource support team told me "Could you please **recreate** the issue on Github so that we can **move** the bounties?".

If they move the bounty to the new issue both issues will have to be kept open until bandaging is fixed

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/possible-problem-with-proximity-hurt-warnings/27781/2
