### ISSUE TITLE
Make Mr. Lapin an actual rabbit mutant

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#56787]
### Is your feature request related to a problem? Please describe.

It always felt weird that a guy who's allegedly becoming more rabbit-like in dialogue doesn't actually have much for rabbit-like mutations. This is even more the case now that there are mutations specifically for the rabbit mutation category.

### Solution you would like.

Change Mr. Lapin's mutations to include the newer rabbit mutations.

### Describe alternatives you have considered.

1. Pretending that rabbits have hooves
2. Ignoring how unimmersive it is that my survivor can't point out to Mr. Lapin that, despite having obviously mutated, he's not actually more rabbit-like

**Comment by Maleclypse** [comment]
This will probably be easiest for you to do.

**Comment by I-am-Erk** [comment]
I would suggest that he actually be made non-mutant to start, and you could potentially add a quest line to bring him rabbit mutagen once you discover it.

**Comment by AmarinReyny** [comment]
> This will probably be easiest for you to do.



> I would suggest that he actually be made non-mutant to start, and you could potentially add a quest line to bring him rabbit mutagen once you discover it. Or, you could keep him a mutant, add the ability to comment on his hooves, add a brief dialogue tree where he discusses how he's mutated but he has no control over it, and then add quests to bring him rabbit mutagen.

Are you saying you want me to contribute this? I've never done anything like this before. I could probably write the code, but I don't know how I'd submit it as a PR.

**Comment by Maleclypse** [comment]
You have a vision for how you’d like it done. Mr Lapin was my second addition to the game and I’m content with it currently. So the most likely source of change would be you since I’ve got a laundry list of things I’m working on. I’m not opposed to your changes, I just don’t know when they’ll happen if ever.

**Comment by AmarinReyny** [comment]
> You have a vision for how you’d like it done. Mr Lapin was my second addition to the game and I’m content with it currently. So the most likely source of change would be you since I’ve got a laundry list of things I’m working on. I’m not opposed to your changes, I just don’t know when they’ll happen if ever.

With that said, I'd still like to be respectful toward your wishes regarding your creation. I had a similar conversation with Erk about the Exodii. Are there any boundaries you want me to not attempt to cross, not as a developer of CDDA, but as the writer of Mr. Lapin?

**Comment by Maleclypse** [comment]
As long as he stays focused on community building / mutual aid I'm pretty ok.  A spark of misplaced hope in a hopeless situation.   And at the bare minimum he needs to stay more human than rabbit mutant at least on introduction.   If you decide to pursue getting him rabbit mutagen to attempt to direct his mutations that's fine with me.

**Comment by AmarinReyny** [comment]
> As long as he stays focused on community building / mutual aid I'm pretty ok. A spark of misplaced hope in a hopeless situation. And at the bare minimum he needs to stay more human than rabbit mutant at least on introduction. If you decide to pursue getting him rabbit mutagen to attempt to direct his mutations that's fine with me.

As an anarchist, I love seeing such ideas show up in the games I play. That said, is something like [this](https://drive.google.com/file/d/1CyoFA9OoM0f5tPB-ptaD7efMIKePXew6/view?usp=sharing) acceptable? I added a response to the TALK_WARRENER_DOING topic that will lead further into getting him mutagen, but the majority of what I've added is at the end.
