### ISSUE TITLE
NPCs cannot move near wall wirings

### ISSUE THREAD

**Issue by Antrocon** [CleverRaven/Cataclysm-DDA#56784]
### Describe the bug

NPCs cannot move near exposed wall wirings for some reason. this makes them quite useless in player camps, as they just stuck in place unable to move to places where they need to do any activities like chop logs into planks or deconstruct objects.

### Steps to reproduce

1. spawn player & npc, spawn multitool for player
2. befriend npc, order to follow, 2 tile range
3. move to any building
4. observe npc following and entering rooms as expected
5. enter room, make npc enter it as well
6. expose wirings near doorway
7. exit the room through said doorway keeping npc in LOS
8. observe npc stop near doorway not following you
9. remove wirings (take down the appliance)
10. observe npc is able to move through doorway again and follow you

### Expected behavior

expected npcs to navigate as ususal and not be stopped by wirings and/or extension cords/appliance cords.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1586 (21H2)
- Game Version: a1cea1e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by RoyBerube** [comment]
The NPC is actually trying to move through the wall, not avoid it. Adding the "OBSTACLE" flag to the ap_wall_wiring lets the npc path correctly.

I'm not convinced this is the best solution - will take a deeper look at the npc pathfinding code.
