### ISSUE TITLE
Bathrooms in labs spawn with no water

### ISSUE THREAD

**Issue by Drac4** [CleverRaven/Cataclysm-DDA#56783]
### Describe the bug

Bathrooms in 2 floor labs that you can access through subway spawn with no water.

### Steps to reproduce

1. Go to a 2 floor lab through subway.
2. Go to the bathroom.
3. There is no water in toilets.

### Expected behavior

Water spawns in bathrooms, because water spawns in bathrooms everywhere else.

### Screenshots

![image](https://user-images.githubusercontent.com/103594835/163233751-24476f1b-ef6b-413b-977f-75afb9f1699a.png)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.F-3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by dragar99** [comment]
I started inside the lab and found that it had water inside the toilets.

Versions and configuration
OS: Windows
OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
Game Version: 0.F-3 [64-bit]
Graphics Version: Tiles
Game Language: System language []
Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
Bionic Professions [package_bionic_professions]
]

**Comment by Drac4** [comment]
> I started inside the lab and found that it had water inside the toilets.
> 
> Versions and configuration OS: Windows OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version Game Version: 0.F-3 [64-bit] Graphics Version: Tiles Game Language: System language [] Mods loaded: [ Dark Days Ahead [dda], Disable NPC Needs [no_npc_food], Bionic Professions [package_bionic_professions] ]

That's the problem, you started in a lab, you cannot start in these kinds of labs, the kind of lab you can start in are labs that have multiple floors, this is a different kind of a lab. If you could start in this kind of a lab you would die immediately, as they are far more dangerous. 

There are 3 kinds of labs, the labs you can start with have multiple floors, these can also sometimes be cold labs, but cold labs also fall into this category. There are the 2 floor labs that appear to be a variation of the 1 floor labs that were present in the previous version, and then there are the 1 floor labs that appear to be identical to the 1 floor labs from the previous version. The issue appears in 2 floor labs and 1 floor labs.

**Comment by tonezdinny** [comment]
I spawned inside the lab and was able to find water in the bathroom toilets. 

Versions and configuration
OS: Mac
OS Version: MacOS Monterey Version 12.1
Game Version: 0.F-3 [64-bit]
Graphics Version: Tiles
Game Language: System language []
Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
Bionic Professions [package_bionic_professions]
]
