### ISSUE TITLE
Nomad bodyglove and bodymesh breathability

### ISSUE THREAD

**Issue by Chroniclerope** [CleverRaven/Cataclysm-DDA#56798]
### Describe the bug

Despite the description being that they are a breathable fabric, and incorporate lycra, these suits have 0 breathability,. making them the worst clothing to wear in the game.

And as a side note, it says its supposed ot protect from electricity but it has the same protection as any other non conductive clothing.

### Steps to reproduce

Reference item in the game to see 0 breathability.

### Expected behavior

If this is meant to be a breathable article of clothing, 80-110 would be expected given items with lycra all have 110 breathability.

Removing the rubber as a material can solve this as it doesn't affect electrical protection as it is right now and only hampers the purpose of the item, as well as possibly cotton.  Additionally, the code on the nomad bodymesh is faulty, the extend function to add kevlar to it doesn't function.

### Versions and configuration

Build: 2022-04-10-0547

**Comment by catdach** [comment]
It seems like this is a problem for a lot of items (basically anything that has any plastic or rubber as a material). Hopefully #56691 will help to fix this sort of problem.

**Comment by Drew4484** [comment]
> It seems like this is a problem for a lot of items (basically anything that has any plastic or rubber as a material). Hopefully #56691 will help to fix this sort of problem.

Override shouldn't be necessary in most cases where the armor has been detailed out. As it is right now, the rubber is 33% of the material used, if this was updated to the new armor system that could be adjusted which would solve the breathability.

**Comment by catdach** [comment]
> > It seems like this is a problem for a lot of items (basically anything that has any plastic or rubber as a material). Hopefully #56691 will help to fix this sort of problem.
> 
> Override shouldn't be necessary in most cases where the armor has been detailed out. As it is right now, the rubber is 33% of the material used, if this was updated to the new armor system that could be adjusted which would solve the breathability.

I don't quite understand. What new armor system are you talking about?

**Comment by Drew4484** [comment]
> > > It seems like this is a problem for a lot of items (basically anything that has any plastic or rubber as a material). Hopefully #56691 will help to fix this sort of problem.
> > 
> > 
> > Override shouldn't be necessary in most cases where the armor has been detailed out. As it is right now, the rubber is 33% of the material used, if this was updated to the new armor system that could be adjusted which would solve the breathability.
> 
> I don't quite understand. What new armor system are you talking about?

Look at the JSON [here](https://nornagon.github.io/cdda-guide/#/item/armor_qt_heavyplate). Using this layout we can specify how much of each material covers which parts of the body and how thick each section is. For clothing with various materials, the old system divided it equally, so the bodyglove is 33% rubber. If we changed that to use the new armor system we could adjust that with more precision, making the rubber a smaller portion, and increasing the breathability.

**Comment by Chroniclerope** [comment]
> 

Excellent, that certainly takes more work but it can meaningfully represent these armors much better.

**Comment by OldFriendEr** [comment]
I have tried to use material layers to fix the breahtability, but it nerfed the protection values to the ground since those depend on the material layers, atm rubber applies full protection as it was fully covered in it @bombasticSlacks, mentioned that he will work on exodii armor materials later, so right now a band-aid with breathability override will suffice.

**Comment by OldFriendEr** [comment]
My PR was merged, so in the next eorking experimental thia issue should be resolved

**Comment by bombasticSlacks** [comment]
as said above this was solved forever ago so I'm closing
