### ISSUE TITLE
Add more spawn locations for hops rhizomes

### ISSUE THREAD

**Issue by EthanBooher** [CleverRaven/Cataclysm-DDA#56790]
### Is your feature request related to a problem? Please describe.

There is a severe lack of (renewable)hops for beer production in the game. 

### Solution you would like.

Hops rhizomes should be found in gardening stores, home improvement megastores and anywhere else seeds may spawn.

### Describe alternatives you have considered.

I x

### Additional context

There is a strong brewing culture in New England especially in and around Massachusetts. I used to live in Maine and there was a plethora of assorted breweries and a few hops farms. New England is also one of the main regions in the United States where hops are grown as well(though this is a rather new trend). I believe adding more spawn locations to the game would help to add a bit "flavor" to the game.

**Comment by robotic-gamer** [comment]
the main alternative I can think of would be "hopless"/gruit beer that does not use hops. one option would be mugwort which would help address how its only current use (anti-parasite) is really very niche and not really useful.

**Comment by Rivet-the-Zombie** [comment]
>the main alternative I can think of would be "hopless"/gruit beer that does not use hops. one option would be mugwort which would help address how its only current use (anti-parasite) is really very niche and not really useful.

Why not all of the above?

**Comment by AlecVoid** [comment]
Ya, we need more hops!
