### ISSUE TITLE
Why can't my smartphone turn on the flashlight and mp3 at the same time?

### ISSUE THREAD

**Issue by lumiamilk** [CleverRaven/Cataclysm-DDA#56794]
### Is your feature request related to a problem? Please describe.

Why can't my smartphone turn on the flashlight and mp3 at the same time?
There is no option for flashlight when mp3 is turned on, and there is no option for mp3 when flashlight is turned on.
Isn't there a way to turn on the flashlight and the mp3 at the same time?
It's so weird that smartphones can't turn on mp3 and flashlight at the same time

### Solution you would like.

Smartphone can turn on mp3 and flashlight at the same time

**Comment by DalenTalas** [comment]
Someone correct me if I'm wrong, please.

If I understand the inner workings of the game correctly, "smartphone" and "smartphone with flashlight on" are two different items. (A)ctivating one of them turns the item into the other. Most likely, a "smartphone with BOTH the flashlight and MP3 player on" is simply not implemented.

Could be the reason for #56828.
