### ISSUE TITLE
JSONize "connects_to" field and add a few rendering features

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#56805]
### Is your feature request related to a problem? Please describe.

The `connects_to` attribute in terrain and furniture lets us designate what terrain and furniture connects to, as the name implies. It's used for things like making two similar walls tile together properly both in ASCII and graphical rendering. Currently, adding a connection group is a mild pain as it requires editing C++ - mapdata.cpp and mapdata.h contain a list of the `connects_to` terrain. See [this PR](https://github.com/CleverRaven/Cataclysm-DDA/pull/51621/files#diff-7abae324ade4ea2e8fcdcea7ba39c8f52c1df21ba2664abe503935ee4af9031a) for an example of the current syntax and necessary changes.

### Solution you would like.

This is really two connected issues that should likely be implemented as two PRs for simplicity of testing.

1. Make `connects_to` straight JSON.
2. Add assymetric `connects_to` options, and terrain/furniture with multiple `connects_to` groups.

#### 1. Make `connects_to` straight JSON.
I suspect this would be pretty straightforward: we just need that mapdata.cpp and mapdata.h section to parse the appropriate JSON.

I would suggest this be done by creating a new JSON object of type `connection_group`, to make step 2 here easier. Then we'd have a json file `connections.json` that contains all the things currently in mapdata.cpp as a list. An individual object would look like this:

```json
{
  "type": "connection_group",
  "id": "CONNECT_WALL",
  "connection": "terrain",
  "name": "WALL"
}
```
`connection` here would accept a list, and the options for now are `terrain` and `furniture`. Later we might have connections for other things. This may be unnecessary if the code can just implicitly make whatever the thingy is connect with other thingies of its type.

`name` is the value we enter into the terrain/furniture's `connects_to` attribute.

#### 2. Add assymetric `connects_to` options

This would allow us to have a terrain that will connect to an adjacent terrain, but that adjacent terrain will not return the connection. For example, a wall would connect to a door, giving the wall a smooth transition into the doorway, but the door would *not* connect to the wall, allowing us to have door sprites that connect to each other but show an edge where they meet the wall (eg. multi-tile garage doors, which currently cannot be properly rendered, or large windows, or double doors that don't have a pillar in the middle).

This would require some more complex syntax in the connection_group object:
```json
{
  "type": "connection_group",
  "id": "CONNECT_WALL",
  "name": "WALL",
  "connect": "terrain",
  "additional_connect": [ "CONNECT_DOOR", "CONNECT_WINDOW" ]
},
{
  "type": "connection_group",
  "id": "CONNECT_DOOR",
  "name": "DOOR",
  "connect": "terrain",
  "rotation_inheritance": "CONNECT_WALL"
}
```
In the `WALL` example, the `additional_connect` attribute lists any other groups that the wall terrain should render as if it is connected to.

In the `DOOR` example, `rotation_inheritance` means a single door tile in the middle of a vertical wall should inherit the vertical rotation from the surrounding WALL connection group, even though it doesn't render as connected to the wall in any other way.

This fairly simple (I hope) infrastructure would allow some really interesting stuff, like having certain tiles that use connections to stuff like floors to render differently on the inside and outside facing portions.

### Describe alternatives you have considered.

For garage doors and similar, we could get around this by having more unique terrain IDs to allow specific rendering. We could also look into some more complex algorithmic changes like we did with rotation, and for some possible uses of this we will eventually need that.

**Comment by mlange-42** [comment]
FYI subscribers: Working on part 2 of the solution in #61336.

**Comment by mlange-42** [comment]
FYI: Working on JSONizing the groups themselves. Group definitions will look like this:

```json
{ 
    "type": "connect_group",
    "id": "conn_WALL",
    "name": "WALL",
    "group_flags": [ "WALL" ],
    "connects_to_flags": [ "WALL" ],
    "rotates_to_flags": [ "SOME", "FURNITURE", "FLAGS" ]
}
```

The last three properties are optional and implement the current stuff that is implied by tags.

**Comment by mlange-42** [comment]
Here we go: #61611
