### ISSUE TITLE
Code owner file does not work correctly

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#56802]
### Describe the bug

No reviews are requested automatically for some people. I noticed this in https://github.com/CleverRaven/Cataclysm-DDA/pull/56796

### Steps to reproduce

Open https://github.com/CleverRaven/Cataclysm-DDA/blob/master/.github/CODEOWNERS, see errors

### Expected behavior

Reviews should somehow be able to be requested for people not in the organization.

### Versions and configuration

n/a

**Comment by Qrox** [comment]
FIxed by #66072.

**Comment by NetSysFire** [comment]
Closing as fixed then. Hooray!
