### ISSUE TITLE
Rigid jewelry causing discomfort

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#56817]
### Describe the bug

[This PR](https://github.com/CleverRaven/Cataclysm-DDA/pull/56626) fixed a few rigid items, but it looks like among other things, dental grills and cufflinks are still causing discomfort.

### Steps to reproduce

Wear a dental grill and some cufflinks, probably other jewelry too. Notice that it is causing discomfort like rigid armor.

### Expected behavior

These items should not be uncomfortable.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1645 (21H1)
- Game Version: 5fe200b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Abellmio** [comment]
Hi there - I'm new to this codebase, but I'm looking to get started in first issues, so this seemed a worthy spot.

Digging around a little, it looks like the flags which indicate a lack of discomfort from rigidity is PADDED, but the ones jewelry have NO_WEAR_EFFECT. I'm not super clear on how/where the flags evaluate (like I said, new!) but NO_WEAR_EFFECT seems to logically evaluate to not having any impact at all, given that it literally is not defined as a constant in flags.cpp or flags.h.

How this should be resolved seems kinda up to opinion from a more experienced dev. The easy fix might be to just change all these items to padded for now, but that might create some sort of knock-on effect that's not clear. I will ask in the discord to see if anyone is interested in giving me a hand.
