### ISSUE TITLE
Smartphone with a flashlight on falls out of the smartphone case

### ISSUE THREAD

**Issue by DalenTalas** [CleverRaven/Cataclysm-DDA#56828]
### Describe the bug

When the smartphone's flashlight is on, it falls out of the smartphone case once another item is picked up. A turned on smartphone cannot be inserted in the case.

### Steps to reproduce

1. Spawn a smartphone, a smartphone case, and a random item.
2. Pick up the case, place the smartphone inside.
3. Turn on the smartphone flashlight.
4. Pick up the random item. Notice the smartphone on the ground.

### Expected behavior

Smartphone cases should be study enough to survive photonic pressure of the smartphone's LED without disgorging their contents.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1645 (21H1)
- Game Version: f37635a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

If I understand the inner workings of the game correctly, "smartphone" and "smartphone with flashlight on" are two different items. Could be that the filters on the case do not allow for the latter to be placed inside.

**Comment by DalenTalas** [comment]
Extant in f37635a. Updated description with version and additional behavior.

**Comment by Maleclypse** [comment]
I’m pretty certain you’ve identified the issue in your additional context.
