### ISSUE TITLE
Repair menu should show quantities of material consumed by repairs

### ISSUE THREAD

**Issue by DalenTalas** [CleverRaven/Cataclysm-DDA#56829]
### Is your feature request related to a problem? Please describe.

Repair menu shows the quantities of materials _available_ for the repair, but nor the quantities _consumed_ by the repair.

E.g., when repairing a plate carrier, with 3 pieces of synthetic fabric and 1 layered Kevlar panel available, the interface displays:

synthetic fabric (3), layered Kevlar panels (1)

### Solution you would like.

Quantities of consumed ingredients should be displayed.

E.g, in the above example (if I remember the quantities correctly), things should appear as:

synthetic fabric (3/3), layered Kevlar panels (3/1)

### Describe alternatives you have considered.

With the way the interface works currently, I've inadvertently ended up consuming more valuable ingredients than I expected.

**Comment by AsterAdelfa** [comment]
Sounds like a reasonable idea

**Comment by DalenTalas** [comment]
This is now mostly implemented in the new repair interface. The one thing I'd still want to see is the number of items to be consumed by the repair.

**Comment by Zireael07** [comment]
Candidate for QoL tag imho
