### ISSUE TITLE
Vitamins A and B12 are not found in meat.

### ISSUE THREAD

**Issue by danielkwinsor** [CleverRaven/Cataclysm-DDA#56838]
### Describe the bug

Cooked Liver (from a wild boar, I doubt that matters) has no vitamin A or B12, despite it being in the actual description.  Other meats have similar issue, mostly on vitamin B12.

### Steps to reproduce

Cook liver, eat it.

### Expected behavior

Expected lots of vitamins, as previously set, with variance by type of meat.  If an animal needs it to survive, they've got it in their meat, and I should get it from their meat.  Vitamin C might have been present in different amounts.

### Versions and configuration

2022-04-13-0549

### Additional context

I remember this working as of 6-8 months ago when I last played, although also I remember some changes being made

**Comment by Fris0uman** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/55466
Working as intended vit A and B never had any effect and are not in the game anymore. See linked PR for more information

**Comment by danielkwinsor** [comment]
The PR makes sense.  What brought me over was the description in Cooked Liver says in its description that it has A B.  What is your recommendation on this?

**Comment by Fris0uman** [comment]
I don't think it's a problem, but you can go edit the description to remove the mention of vitamins if you want.
