### ISSUE TITLE
Write a test to check whether descriptions start with uppercase letter and ends with full stop

### ISSUE THREAD

**Issue by Faalagorn** [CleverRaven/Cataclysm-DDA#56839]
### Is your feature request related to a problem? Please describe.

In many of my PRs I fixed descriptions lacking full stop and with a wrong casing. I think it should be possible to write a test to check that which doesn't sound hard to do come up with and without many fake positives, currently the lack of double spaces seems to be checked that way, see e.g. [this test run](https://github.com/CleverRaven/Cataclysm-DDA/runs/6014922390?check_suite_focus=true#step:16:189). This would prevent those issues in the future, especially where new content/mods gets added and aid in finding them in future surely!

### Solution you would like.

Write a test to check if description fields start with a uppercase letter and end with a `.`.

### Describe alternatives you have considered.

* Write the test myself (though it will take a time to learn it).
* Come up with more ideas for such tests based on the rules in the [MANUAL OF STYLE](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/MANUAL_OF_STYLE.md), e.g. checking whether Cataclysm, Discontinuity, Exodii, Marloss, Mycus, Autodoc, Kevlar and Nomex, etc. or skill/stat/mutation/spells/etc. names are properly capitalized.

### Additional context

See #56745, #56697, #56698, #56373 for examples where I found and fixed such issues manually.

**Comment by PatrikLundell** [comment]
If such a test is written, it would have to recognize the other termination markers as well ('?", "!", and any others, if there area any).

**Comment by Faalagorn** [comment]
> If such a test is written, it would have to recognize the other termination markers as well ('?", "!", and any others, if there area any), as well as legal non letter initial characters (primarily numbers, but there might be others, such as the inverted characters used in Spanish, if someone was making a Spanish greeting).

There are some runic, hebrew and morse code strings in the game, not sure if these are in beginning or the end of the descriptions though, but I guess there could be made an exception for these.

**Comment by PatrikLundell** [comment]
I think it's OK for runic etc. to "fail" the tests provided there's a way to mark strings as being exempt from testing (which would also allow for the writing of SMS-ish, although I don't know how you'd go about actually speaking the mess).
