### ISSUE TITLE
leather backpack does not have the newly added pockets.

### ISSUE THREAD

**Issue by FayFlightee** [CleverRaven/Cataclysm-DDA#56835]
### Describe the bug

The clip pockets had been added in #53162, yet leather backpack did not get such luxury despite the backpack having it.

### Steps to reproduce

1. Spawn a backpack and leather backpack.
2. Compare them and check their pockets.

### Expected behavior

I'd have hoped that the leather backpack have all the extra pockets like tucking things between back and backpack for long guns.

### Screenshots

![image](https://user-images.githubusercontent.com/71143790/163663234-8600c4c4-4ef7-45fb-8d1f-bd298ef57ea8.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1645 (21H2)
- Game Version: 8e5d4aa [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

**Comment by bombasticSlacks** [comment]
It's supposed to be a fashionable bag so it definitely wouldn't have clips for carabiners or compression straps. I don't have any issue with someone adding the "tucked between the back" pocket tho!
