### ISSUE TITLE
"Select items in container" for advanced inventory manager is not working correctly.

### ISSUE THREAD

**Issue by FayFlightee** [CleverRaven/Cataclysm-DDA#56847]
### Describe the bug

As title said, the "Select items in container" for advanced inventory manager (by default it is c or C when in advanced inventory manager, which is /) is not working correctly. When you have multiple items inside one, it shows only one or not at all.

### Steps to reproduce

1. Have any storage container.
2. Store **several** items inside it.
3. Select the container in Advanced Inventory Manager
4. Select its contents inside. (again, by default, this is c or C within the advanced inventory manager.)

### Expected behavior

Would've liked it to list all items inside, not just one, or not at all.

### Screenshots

![image](https://user-images.githubusercontent.com/71143790/163677894-912f1c01-1300-4513-9c9b-22cca29d768f.png)
Top is showing it in the normal i inventory.
Bottom left is when examined while wielding the container (which is shown within the w section of advanced inventory manager, the worn items.)
Bottom right is when examined while the container is left on the floor. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1645 (21H2)
- Game Version: 8e5d4aa [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by ThePirate42** [comment]
I have the same problem with 0.G (non experimental). Using container on a reinforced garbage bag shows just one of the several items in it.
