### ISSUE TITLE
Sheet metal and small metal sheet seriously need length assignment.

### ISSUE THREAD

**Issue by FayFlightee** [CleverRaven/Cataclysm-DDA#56845]
### Is your feature request related to a problem? Please describe.

Simply that, but also includes small metal sheets.
Sheet metal is only 10cm, which is likely autoassigned. And it's not quite right for something that can be used for, say, car's quarterpanels or roofs.
Same probably is the same for small metal sheets too, 6cm seems way too short.

### Solution you would like.

I don't know what would be their appropriate length, but they need more than these current numbers.

**Comment by onura46** [comment]
On their longest sides sheet metal is already 100cm and small sheet metal is 20cm. This report seems inaccurate compared with the latest experimental.

**Comment by FayFlightee** [comment]
> On their longest sides sheet metal is already 100cm and small sheet metal is 20cm. This report seems inaccurate compared with the latest experimental.

It was relevant at the time the issue came out. Someone fixed it without linking this one, I think.

**Comment by FayFlightee** [comment]
Either way I'll close it now I suppose. The sheet metal and small metal sheet used to have auto-assigned 10cm and 6cm respectively.
