### ISSUE TITLE
Blunderbuss ammunition currently shoots only 1 projectile.

### ISSUE THREAD

**Issue by FayFlightee** [CleverRaven/Cataclysm-DDA#56842]
### Describe the bug

#52583 made shotguns shoot multiple pellets projectiles, but such system is **not** applied to blunderbuss ammunition yet.

### Steps to reproduce

1. Spawns some blunderbuss shot, or any other blunderbuss ammunition that aren't slugs.
2. You'll be able to clearly see it lists the amount as 1. 

### Expected behavior

Expected the blunderbuss to get the same shotgun treatment as the others since the PR.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1645 (21H2)
- Game Version: 8e5d4aa [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

**Comment by catdach** [comment]
Looks like this as fixed by #52833

**Comment by FayFlightee** [comment]
> Looks like this as fixed by #52833

It was not.
