### ISSUE TITLE
Crashing when launching game

### ISSUE THREAD

**Issue by Endertron51** [CleverRaven/Cataclysm-DDA#56851]
### Describe the bug

After updating the game I clicked on launch game several times and all of them didn't open the game window and immediately opened the launcher again, I reversed to the previous version but still didn't opened.

### Steps to reproduce

Click on launch game

### Expected behavior

Open the game

### Versions and configuration

OS: Windows 7, 64-bit
Branch: Experimental
Version: 89dce91 (tiles)
Build: 2022-04-16-1527
Ingame language: English

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8500367/crash.log)
[Salada.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8500374/Salada.zip)
[Industrial Disease.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8500378/Industrial.Disease.zip)

**Comment by TheShadowFerret** [comment]
Duplicate of #56813, #56836 will fix this.

**Comment by DalenTalas** [comment]
This issue should have been resolved in the latest update at this point.

**Comment by BrettDong** [comment]
Fixed in #56836, please try the latest experimental version https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-04-17-1523 .

**Comment by Endertron51** [comment]
It really was fixed on the latest experimental, thanks for the help.
