### ISSUE TITLE
Opening the faction menu crashes to desktop

### ISSUE THREAD

**Issue by DalenTalas** [CleverRaven/Cataclysm-DDA#56864]
### Describe the bug

Opening the faction menu results in a crash with the following error message (see screenshot). This appears to be independent of the key binding.

### Steps to reproduce

1. Get a couple NPCs.
2. Possibly optionally, give everyone a two-way radio.
3. Open the faction menu.

### Expected behavior

A faction menu should appear instead of an error message.

### Screenshots

![image](https://user-images.githubusercontent.com/74809740/163694115-4e791325-7648-400d-b0d6-4bb2df770032.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1645 (21H1)
- Game Version: f37635a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Crash and debug lobs: 

[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8500770/config.zip)

**Comment by andrei8l** [comment]
Can't reproduce. Please upload the save file
