### ISSUE TITLE
combat exoskeleton cant be spawned from debug

### ISSUE THREAD

**Issue by Snowy597** [CleverRaven/Cataclysm-DDA#56861]
### Describe the bug

As the title states, the combat exoskeleton cannot be spawned. If you try to it will simply get sent to the shadow realm.

### Steps to reproduce

1. Enable debug menu
2. Go to Spawning
3. Spawn item
4. Search for combat exoskeleton 
5. Spawn it

### Expected behavior

I expected the combat exoskeleton to spawn, but it didnt.

### Versions and configuration

OS: any OS 
Mods: Blaze Industries and  Dead Days Ahead

**Comment by Night-Pryanik** [comment]
Huh?
![изображение](https://user-images.githubusercontent.com/11132525/163701735-c8136fdd-9b73-4aff-8a51-12ee8294ff7b.png)
![изображение](https://user-images.githubusercontent.com/11132525/163701741-e3fef139-6067-4667-bbad-ac33c1499db0.png)

**Comment by ZhilkinSerg** [comment]
You were probably standing over the big pile of items or terrain/furniture that can not hold any items. Try to spawn it when there aren't any items nearby.

**Comment by Night-Pryanik** [comment]
Closing as unconfirmed.
