### ISSUE TITLE
More ways to heal animal companions (Non-npc companions)

### ISSUE THREAD

**Issue by Termineitor244** [CleverRaven/Cataclysm-DDA#56878]
### Is your feature request related to a problem? Please describe.

Currently you have to wait for the natural healing of your pets or use spells if you are playing in magyclism, you are not able to just grab some bandages and apply them to the wounds of your pets, helping their natural recovery after a fight, this makes it very difficult to use them in a fight because every wound can take a lot of time to recover.

You can't stop the bleeding of your pets either! And that robs them of HP quickly, and you should be able to stop their bleeding pretty easily with some bandages!

### Solution you would like.

To have more ways to heal animal pets, like using bandages on them, this should also stop (or have a probability to stop) their bleeding.

### Describe alternatives you have considered.

To have my dogs just die of small wounds and cuts.

**Comment by BjoHart** [comment]
Would be nice!
