### ISSUE TITLE
Mobile - Escape Button On Keybinds Menu

### ISSUE THREAD

**Issue by TheOGMiyagi** [CleverRaven/Cataclysm-DDA#56879]
### Is your feature request related to a problem? Please describe.

When using the mobile version of C:DDA, I often find myself in the `Keybinding` Menu.
Every time I have accessed this menu, I have been unable to navigate out of the menu. This is because Samsung Keyboard nor my preferred keyboard have an `ESC` Key.

### Solution you would like.

As there are a few very useful virtual keys on the screen, I simply ask that `ESC` be added as one.

Why implement 

### Describe alternatives you have considered.

Unfortunately, I have not been able to consider an alternative solution; without some form of navigation built into the on-screen controls, the only solution is players installing a keyboard app specifically to play C:DDA with.

By providing a tool to navigate out of this menu trap, you eliminate the necessity of another keyboard or, in a worst case scenario, forcing C:DDA to stop at the cost of progress.

### Additional context

As shown below, using `Q` to exit only searched for that letter within the menu, making navigation impossible.
![Uploading Screenshot_20220417-093203_Cataclysm DDA.jpg…]()

**Comment by Qrox** [comment]
I think you can double tap to input the ESC key.
