### ISSUE TITLE
"extend" and "delete" do not work for fields other than flags and effects

### ISSUE THREAD

**Issue by ZombieZilla** [CleverRaven/Cataclysm-DDA#56877]
### Describe the bug

The "extend" and "delete" functions do not work on fields other than flags and effects

### Steps to reproduce

1. Create a new `vehicle_part`
2. `copy-from` another vehicle part with the `folded_volume` field
3. `delete` the folded_volume, as it implicity adds the `FOLDABLE` tag
4. The created vehicle part can still be folded, the `delete` did not work

### Expected behavior

The `delete` function should be able to remove all fields, not just effects and flags.

OR, if they are *only* supposed to work on those two, throw an error if they are used on another.

### Versions and configuration

N/A

### Additional context

As far as I can see, #56876 is the only instance that suffers from this issue, having to redefine most of the battery_car fields to work around said issue.

**Comment by catdach** [comment]
My understanding was that the `extend` and `delete` functions were only meant to deal with fields that contain an array, and are only able to change what is in the array. What you're describing definitely sounds useful though.

**Comment by GuardianDll** [comment]
#56785's author is also suffer from this
This must be really good addition that improve the work with stuff, and will allow us to inherit way more thing instead of labor copypasting (which means instead of adding few strings some person need to add a few dozens of one)
