### ISSUE TITLE
Tire Irons should spawn more, and also be renamed to Lug Wrenches

### ISSUE THREAD

**Issue by EnzoMonroe** [CleverRaven/Cataclysm-DDA#56881]
### Is your feature request related to a problem? Please describe.

Tire irons are required to change a car's tires, but seem to be quite rare. According to the HHG (https://nornagon.github.io/cdda-guide/#/item/tire_iron), they have only a 31% chance of spawning in garages! Changing a car's tires is one of the most common tasks an auto shop does, and they should have tire irons on hand--even assuming some or most have been looted by the time the player arrives. Tire irons should also spawn frequently in car trunks; many cars have a lug wrench in the trunk to go along with the spare tire.

Also, what the game calls a "tire iron" is actually a lug wrench, so it should be renamed accordingly.
Tire iron: https://en.wikipedia.org/wiki/Tire_iron
Lug wrench: https://en.wikipedia.org/wiki/Lug_wrench

### Solution you would like.

Rename the Tire Iron to Lug Wrench.

Lug wrenches should spawn frequently in garages and car trunks, and less frequently (but still more than their present rarity!) in other locations where tires are changed, such as residential garages, rural homes and farms, and military bases.

### Describe alternatives you have considered.

Renaming tire irons isn't totally necessary.

**Comment by Davi-DeGanne** [comment]
I am working on this, should have a PR up within a day or two
