### ISSUE TITLE
trade/pickup/inventory menu missed some shortcut buttons

### ISSUE THREAD

**Issue by heiyu17** [CleverRaven/Cataclysm-DDA#56885]
### Describe the bug

some shortcut buttons do not drawn on the screen after closing **inventory** menu for the first time.

### Steps to reproduce

In 0.F-3
1. Start a new game and open inventory.
2. Each shortcut is drawn as a button.
3. Close inventory and open it again.
4. Examine shortcut button is no longer drawn on the screen.

In latest experimental
1. Start a new game and pick up items from one nearby tile.
2. Close the menu and trade with NPC.
3. The shortcut buttons of trade menu is same as pick up menu. Event though there is no binding key for Wield(w), it is still drawn on the trade menu.
4. Close trade menu and open inventory menu.
5. Some shortcut buttons are no longer drawn on trade/pickup/inventory when opening them.

### Expected behavior

shortcut button dose not match context

button list on trade/pickup/inventory reset to a fixed list

### Versions and configuration

OS: Android
Version: 0.F-3 and Latest Experimental
Graphics: Tiles
Mods loaded: dda
Language: English

**Comment by heiyu17** [comment]
Those disappeared useful button
trade menu : TAB
since Android normal input method dose not have TAB, solution is binding another key to replace TAB
picking menu : Wield(w), Wear(W)
A time wasting method is entering back button first to enter key...

**Comment by andrei8l** [comment]
Does this fix it? I cannot test for Android at the moment
```diff
diff --git a/src/inventory_ui.cpp b/src/inventory_ui.cpp
index b7a814cd26..182c9d4ee0 100644
--- a/src/inventory_ui.cpp
+++ b/src/inventory_ui.cpp
@@ -3654,6 +3654,12 @@ trade_selector::trade_selector( trade_ui *parent, Character &u,
       _ctxt_trade( "INVENTORY", keyboard_mode::keychar )
 {
     _ctxt_trade.register_action( ACTION_SWITCH_PANES );
+#if defined( __ANDROID__ )
+    std::vector<input_event> const evlist =
+        inp_mngr.get_input_for_action( ACTION_SWITCH_PANES, _ctxt_trade.get_category() );
+    _ctxt_trade.register_manual_key( evlist.front().get_first_input(),
+                                     _ctxt_trade.get_action_name( ACTION_SWITCH_PANES ) );
+#endif
     _ctxt_trade.register_action( ACTION_TRADE_CANCEL );
     _ctxt_trade.register_action( ACTION_TRADE_OK );
     _ctxt_trade.register_action( ACTION_AUTOBALANCE );
```
