### ISSUE TITLE
Regular sunburns and sunscreens/sunburn ointments

### ISSUE THREAD

**Issue by Termineitor244** [CleverRaven/Cataclysm-DDA#56889]
### Is your feature request related to a problem? Please describe.

#56705 implements better mechanics for albino and sun sensitive characters, but, after returning from the beach without any sunscreen on me, well... I got terrible sunburns! Even though I was just a few hours on the sun, and I'm not albino or something.

### Solution you would like.

To have regular sunburns implemented on the game, where if your character is outside for a few hours on a sunny day (or many more hours on a normal day) and it doesn't have at least certain degree of coverage by clothing on its body then it suffers a sunburns effect on its affected body parts, with pain and reduced speed.

But! With a new item you can protect yourself from sunburns! Sunscreen! You just need to apply it on your body before your sun exposure and you will be protected for a few hours (with a "sunscreen protection" effect).

In case you forgot to apply one before exposure, you can accelerate/lessen your sunburn recovery with special ointments (like me).

### Describe alternatives you have considered.

To not force our players to take care of their skin on a sunny day! ;D

**Comment by TheShadowFerret** [comment]
*Wonders if this could be used so Burn Care isn't learned only by kill scorched zombies*
🤔

**Comment by Termineitor244** [comment]
> _Wonders if this could be used so Burn Care isn't learned only by kill scorched zombies_ 🤔

Haha would be cool! But I think it would be difficult since the proficiency is more 'third degree burns treatment" than "regular sunburn treatment"

**Comment by fairyarmadillo** [comment]
Skin tone and age could be a factor here too. I know the former one is stepping into iffy territory but [the Fitzpatrick scale](https://en.wikipedia.org/wiki/Fitzpatrick_scale) provides a handy reference for skin tone and sunburn. Older people are also more susceptible to sunburn as their skin isn't as resilient.

Other things can cause sunburns too - [welding is one of them](https://www.weldingboss.com/can-you-get-sunburned-from-welding/), and sunscreen actually protects from that. Atomic bombs (IE mininukes or possible portal storm effects) can cause flash burns at a distance that resemble sunburns, but from what I can see, that's not UV radiation.

**Comment by Termineitor244** [comment]
> Skin tone and age could be a factor here. I know the former one is stepping into iffy territory but [the Fitzpatrick scale](https://en.wikipedia.org/wiki/Fitzpatrick_scale) provides a handy reference for skin tone and sunburn. Older people are also more susceptible to sunburn as their skin isn't as resilient.
> 
> Other things can cause sunburns too - [welding is one of them](https://www.weldingboss.com/can-you-get-sunburned-from-welding/), and sunscreen actually protects from that. Atomic bombs (IE mininukes or possible portal storm effects) can cause flash burns at a distance that resemble sunburns, but from what I can see, that's not UV radiation. I've also heard of people catching "sunburns" from forging but from the description it sounds more like they're just getting low level burns from the heat.

I did consider skin tone, but... Well, yeah.

Age would be a safer approach, and welding and portal storm effects are things that could give sunburns too and would be fun to have around!

If I could I would like to try and tackle this issue, but I'm not confident of what I can achieve with my knowledge of C++, maybe with EOCs, but I could not include age or welding then.

Good ideas and info nonetheless!

**Comment by fairyarmadillo** [comment]
One thing I recommend in that case is that you calibrate the burn rate for a medium skin tone on the Fitzpatrick scale. Fair-skinned people burn very fast compared to everyone else and it would really stick out if they were the model all characters used.

**Comment by Willenbrink** [comment]
In general I'm opposed to this change. While this change would be nice, implementing and balancing it would take a lot of effort and in the end the impact would be relatively small.
Sunburn is primarily a concern for us as we mostly don't spend significant amounts of time in the sun around the year but have rare high exposures (e.g. going to the beach/sea/on vacation). Once the body adapts to frequent high exposures that problem almost completely disappears as a person can tan within (I guess) 2 weeks to a level that protects them completely from the sun in the northern area that CDDA is set in. It would be a more severe issue near the equator as the stereotypical white caucasian has lost the ability to tan to the darker colors needed there.
In addition most levels of sunburn we talk about are basically insignificant in CDDA. Reddening is completely irrelevant, touch sensitivity almost (should perhaps lead to a focus loss as scratching, clothes etc. can irritate the skin more easily) and the more extreme sunburns, that are painful without touching and may result in blisters, are difficult to reach in a northern climate. Skin cancer is also not a concern for the timescales we are working on.

So, the game starts in the spring, tanning happens quickly and the effects of sunburn are mild for anything besides extreme sunburn. As a result I believe the impact of a more accurate sunburn simulation to be negligible.

You can also read more on Wikipedia and see some pictures on how dark even white skin can turn. Unfortunately I haven't found any article on specifically tanning ability but I believe it isn't a problem for a game set at northern latitudes:
https://en.wikipedia.org/wiki/Sun_tanning
https://en.wikipedia.org/wiki/Human_skin_color#Exposure_to_the_Sun

**Comment by Termineitor244** [comment]
> While this change would be nice, implementing and balancing it would take a lot of effort and in the end the impact would be relatively small.

I'm somewhat of the same mind after I tried to think of possible implementations, and even without that, we are now in feature freeze so this would have to wait until the next dev cycle...

Thanks for the rest of the info, I think I will refrain of trying to implement regular sunburns for the foreseeable future, I would like to have sunscreens though, for the albino/sun sensitive characters at least.

**Comment by Willenbrink** [comment]
Sunscreen would certainly be nice for albinos but I'm not sure how welcome that change would be. Sunscreen as a item would then be completely useless 99% of the time and it would also suggest to players that something like sunburn exists (and not only for albinos). Although, thinking about it, sunblocker would work better I guess, especially with a description about only benefiting albinos and sun sensitive people. I also hope it shouldn't be to difficult to implement so I will look into it sometime next week.
Regarding the freeze, it shouldn't be a problem for the PR to sit around for some time as it interacts with only very few other features and so shouldn't become outdated.

**Comment by fairyarmadillo** [comment]
When playing today I got a bit too cold during like a single hour's exposure and my head was at half HP for a couple days. It made me realize that we now have the tools to push hypo/hyperthermia to effects so that people recover from them in a more reasonable amount of time. 

Doing that would require seperately modeling frostbite and burns, and sunburns are basically just first degree burns with very similar symptoms and care. With all that in mind, I recommend holding off on sunburns until burn injuries in general are modeled in a more interesting way than simple HP loss, and then treating them as weak burns. We have a Burn Care proficiency, so I'm assuming there are plans for that at some point.
