### ISSUE TITLE
Rubik uninstall cost

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#56886]
### Describe the bug

Installing a bionic with Rubik costs around $20, removing it is upwards of $500. I'm not sure this is intended, I couldn't find any documentation about it. These prices appear to be constant, so if the exodii bungle an install and stick you with a bionic nostril, they will charge you $500 for a 90% chance to fix their mistake.

You can also have Rubik install bionics off his shelf for $20 without buying them, so there's no reason to ever purchase them from him in the trade menu. Since bionics in your inventory also cost $20 to install, that seems wrong.

### Steps to reproduce

1) Go see Rubik
2) Get an install
3) Check his uninstall prices

### Expected behavior

Bionics should not be installable via Rubik's dialog menus if they're in his shop inventory, the player should either have to buy them first, or the install prices should include the price of the unowned bionic.

Uninstalling bionics should not be 50 times pricier than installing them. Either a flat rate or a sliding scale based on surgery time and maybe other factors would make sense.

Some sort of credit, refund, or non-charge for failed surgery could be implemented, especially if the bionic is destroyed, or Rubik's dialog should probably reflect that he or at least his people are cutthroat enough to screw their patients worse than the US health care system. This might just be me but he comes across as nicer than that.

### Versions and configuration

* OS: Windows
  * OS Version: 10.0.19043.1645 (21H1)
* Game Version: https://github.com/CleverRaven/Cataclysm-DDA/commit/8af3a1abcd6bf896da5a8a2b2d7adc00ff07aef9 [64-bit]
* Graphics Version: Tiles
* Game Language: System language []
* Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
No Fungal Growth [no_fungal_growth],
Bionic Professions [package_bionic_professions]
]

**Comment by haveric** [comment]
There are a couple issues going on here. One is that you can install bionics without paying for them, which is an install/uninstall menu issue where it should exclude non-owned items. The other is involving bionic prices. From [discussion on reddit](https://www.reddit.com/r/cataclysmdda/comments/tzbgpi/changelog_from_the_last_week_1_8_apr/i412zcq/) from the last changelog, Erk confirmed CBMs are currently undervalued and in need of a rebalance. The final issue is that of the cost of installing vs uninstalling. The current formula works like this:
- Installing: 2 * bionic's value
- Removing: flat $500 + .25 * bionic's value

Which might be fine once bionic prices get rebalanced, but at minimum needs to be made more clear in the dialogue. Installing is currently way too cheap for most bionics and these either need to be a flat value for each, or balanced alongside the bionic prices to make sure they are at reasonable levels.

**Comment by fairyarmadillo** [comment]
$500 is a huge amount of money. The endgame Hub 01 quest only pays $400, and that's a huge and very dangerous dungeon. I'm aware I could load up all the crap guns from multiple stores or haul in thousands of zucchini, but that seems like a lot of schlepping.

I agree it shouldn't be cheap, but taking out your finger razors shouldn't be more expensive than buying an invisibility cloak.
