### ISSUE TITLE
New scenario: Beach Panic, swimmer professions and swimmer ferals

### ISSUE THREAD

**Issue by Termineitor244** [CleverRaven/Cataclysm-DDA#56891]
### Is your feature request related to a problem? Please describe.

There are no dedicated swimmer professions!

### Solution you would like.

**This is a feature I'm planning on working upon, but I decided to share my ideas here to gather feedback and in case anyone wants to help implement them.**

A new scenario: _Beach Panic_ where the player starts in a lake/river shore or in a pool, surrounded by swimmer zombies and a new kind of enemy: a swimmer feral!

Scenario mission: To avoid suffering sunburns (#56889) for a week and to escape alive from the beach.

Professions:

-Naked (maybe a nudist beach?)
-Towel and soap profession (Same reason)
_**New:**_

_-Swimmer:_ Starts with 3 - 4 athletics skill, common swimmer clothing (bikinis and the like) and a neoprene bag (to be added) with a beach volleyball, a towel, a cellphone in a waterproof case and some sunscreen (to be added).
_-Diving enthusiast:_ Starts with 4 - 5 athletics skill and some diving equipment.
_-Ship owner:_ Starts with 3 driving and athletics skill, and a boat with wheels to drag it on ground (I'm not sure we have one?).
-Maybe more...

New enemies:

_Feral swimmer:_ Like a zombie swimmer, but alive, and capable of real swimming because of remant memory and proper swimming clothing, _can throw improvised sand balls to you for 1 damage_.

_Feral swimmer (Googles)_ Same as the normal version, but capable of seeing underwater!

### Describe alternatives you have considered.

To have feral swimmers throw some water at you (0 damage) in crazy cataclysm, or beach volleyballs.

Or to start in a dock too.

### Additional context

This additions were though of after a good, normal and not crazy visit to the beach in real life.

**Comment by Night-Pryanik** [comment]
Cataclysm: Dead Island Ahead?
