### ISSUE TITLE
Taking down furniture with items inside

### ISSUE THREAD

**Issue by mx-moonling** [CleverRaven/Cataclysm-DDA#56898]
### Is your feature request related to a problem? Please describe.

Currently, when you take down a large cardboard box, the contents remain on the floor. This doesn't make sense, and being able to quickly pick up a large box of items would encourage more people to use the storage system in place.

### Solution you would like.

When taking down a cardboard box, you receive the item holding whatever contents it had while a piece of furniture. Items that are too heavy or too long to fit would fall on the floor beneath it.

### Describe alternatives you have considered.

Implementing a weight and length limit on certain tiles for storage, though this seems much less convenient and realistic. A cardboard box can hold much heavier items on the ground then when lifted.

Destroying the container when trying to pick up a box with too heavy contents. This idea seems rather cruel and unnecessary, and wouldn't have any real benefit.

### Additional context

I am working on adding new boxes for containing items, that are more sturdy and thus more useful. I have not yet made a furniture version, but if this is implemented, I would create a furniture version of all medium and large boxes, to give more storage options.

This would also allow a direct connection between the sorting zone system and the pockets system: you would place a box in a sorting zone, sort all items automatically, and pick up your now sorted box.

**Comment by DalenTalas** [comment]
Should work with fridges as well.
