### ISSUE TITLE
Feline samples should be obtainable by dissecting shorthair cats, bobcats and cougars.

### ISSUE THREAD

**Issue by cataclysmsurvivalist** [CleverRaven/Cataclysm-DDA#56905]
### Is your feature request related to a problem? Please describe.

Currently, feline samples are only valid as lab drops. It should be possible to obtain them through dissecting felines.

### Solution you would like.

Dissecting shorthair cats, bobcats and cougars should result in obtaining feline samples.

**Comment by Fris0uman** [comment]
Fixed by #56608
