### ISSUE TITLE
Refugee Center NPCs throw instead of shoot

### ISSUE THREAD

**Issue by danielkwinsor** [CleverRaven/Cataclysm-DDA#56908]
### Describe the bug

On every playthrough I've done since 0.C, the Teamster has always thrown their gun at the zombies that emerge from the locked room in refugee center.  They also don't engage very well.  They might equip their helmet and throw that too.  

I know it's a separate thing, but it could be mentioned that the refugees from the next room over can just stand there watching, not engaging.  Would be nice if they helped too.

### Steps to reproduce

Save many overmaps away from refugee center.
Enter refugee center
Trigger zombies to break out
Observe
Repeat from original save.

### Expected behavior

Expect them to shoot

### Versions and configuration

6a35b49

**Comment by dseguin** [comment]
Possibly fixed by #56746. Could you update to the most recent release and see if it happens again?

**Comment by danielkwinsor** [comment]
Latest version 4-19, the glock is now on the ground at the teamster's feet.  Teamster dropped the glock, wielded a can of soda, threw the soda

**Comment by danielkwinsor** [comment]
The broker just wielded a can of pickles and threw that.

**Comment by danielkwinsor** [comment]
They'll even throw combat knives.

**Comment by NetSysFire** [comment]
#56102 is vaguely relevant here.

>Teamster dropped the glock, wielded a can of soda, threw the soda
>The broker just wielded a can of pickles and threw that.

wtf lol, stuff like that never stops amusing me.

**Comment by Nerezza** [comment]
I had a generic NPC out in the world put their loaded Glock away to throw stuff at me instead. I decided to stand just outside the range they were throwing things at for a few turns to see what would happen and only after like an in-game minute did they finally pull their glock back out and try to shoot me.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/npc-throwing-their-weapons-problem/28312/10
