### ISSUE TITLE
Multiple city labels overlap in a non-city area

### ISSUE THREAD

**Issue by onura46** [CleverRaven/Cataclysm-DDA#56907]
### Describe the bug

Multiple city labels appear to overlap on the overmap in an area that doesn't actually contain a city. Three different cities claim to be there and the appearance of the label changes depending on where the selector is positioned on the overmap.

It's worth noting that the center of this city apparently lies on the very corner of the initial map generated at spawn and the surrounding area seems to be divided accordingly. Please check the attached video or download the save file.

### Steps to reproduce

I can't be sure why this is happening but I'm guessing.

1. Generate new worlds until a city center is generated at the very corner of the initial map.
2. Observe that map generation has trouble deciding where city boundaries are and may duplicate city labels.

### Expected behavior

I expected a relatively seamless transition into a city area with one name. Map generation usually handles this without issue.

### Screenshots

https://user-images.githubusercontent.com/67405765/163880619-80072a40-6b4a-474b-b0c9-3adbdec45248.mp4

### Versions and configuration

OS: Windows 10
Game Version: https://github.com/CleverRaven/Cataclysm-DDA/commit/529fb0f335983f3a4b7f6c857b7d4f22f9608797
Graphics: Tiles
Language: English (US)
Mods: dda, blazeindustries, package_bionic_professions, no_fungi, no_npc_food, StatsThroughSkills, stats_through_kills, speedydex, extra_mut_scens, crazy_cataclysm, no_fungal_growth

### Additional context

[Ledgewood.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8508264/Ledgewood.zip)

**Comment by anothersimulacrum** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/56895 will fix.

**Comment by onura46** [comment]
OK, thank you! Sorry, I totally missed that PR!
