### ISSUE TITLE
Broken vehicle (portions) spawn

### ISSUE THREAD

**Issue by jeffplata** [CleverRaven/Cataclysm-DDA#56911]
### Describe the bug

Vehicle portions keep spawning anywhere the RNG likes, usually in weird or inappropriate places and has the bad effect of blocking important paths. This is observed in between exit and game reload.

Related public posts: 
https://www.reddit.com/r/cataclysmdda/comments/u6vrhf/broken_vehicle_spawn/
https://www.reddit.com/r/cataclysmdda/comments/tzqviw/no_hope_mod_bug/

### Steps to reproduce

Just be keen observant. Return to places you've been and you will notice new vehicle portions strewn all over the place. Very random but it seems to get more frequently.

### Expected behavior

should not happen at all.

### Screenshots

![image](https://user-images.githubusercontent.com/29348635/163916672-3224b62f-dabf-490e-9d48-fa15fdfff096.png)
![image](https://user-images.githubusercontent.com/29348635/163916690-6c49d492-9dcb-46c7-806c-220360022259.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1586 (21H2)
- Game Version: 8fa8088 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Hope [no_hope]
]

### Additional context

Using No Hope mod, but someone not using it reported encountering this bug too.

**Comment by Golfavel** [comment]
I've also experienced this multiple times in normal (non-No Hope) games, once even in the tutorial. This is my most recent find:
![Screenshot_20220421_194823](https://user-images.githubusercontent.com/32048635/164580516-0005778c-8456-4245-86f7-f12fdb5bbac3.png)
.

**Comment by Termineitor244** [comment]
I too experimented this issue in a normal game.

/confirmed
