### ISSUE TITLE
Integrated armors from mutation break other mutations

### ISSUE THREAD

**Issue by Amoebka** [CleverRaven/Cataclysm-DDA#56919]
### Describe the bug

There are numerous mutations that only activate when a certain body part is completely naked. The newly added intergrated armors (chitin, bark, fur, etc) count as clothing for the purpose of this check, messing it up.
The most ridiculous example is spiders: having epicuticle and/or other chitinous pieces completely negates the dodge bonus from furred plate and imposes dexterity penalties from arachnid arms.

### Steps to reproduce

0. Get naked.
1. Debug the Sclerotin Plate mutation with all the prereqs.
2. Debug the Furred Plate mutation.
3. Observe that you receive no bonus to dodge from it because "you are wearing clothes".
4. Debug the Arachnid Arms mutation.
5. Observe you get no dexterity bonus because "you are wearing torso armor".

### Expected behavior

Natural integrated armors don't count as wearing clothing.

### Versions and configuration

Win 10, tiles.
Build 2022-04-15-0755

### Additional context

For context, the issue was introduced with integrated armors in #56329 (@MylieDaniels). I'm 99% sure this was not an intentional change.

**Comment by MylieDaniels** [comment]
Ah, my apologies, a few armor changes were happening at the same time and this slipped through.

**Comment by Bossrman** [comment]
There are a multitude of other problems with this, I've had 3 seperate integrated armors from spider and it results in like 40 encumbrance on all limbs (and pratically immune to damage) and than a portal storm occured, the intangibility removed my integrated armor, when I became tangible again, it didn't come back.

**Comment by Mer1ck** [comment]
I've noticed that with fur, you can also cut up your integrated armors, destroying them permanently. While I guess you could "shave" yourself, it does ruin the mutation and its effects.

**Comment by Heitomos** [comment]
Possibly related to this, before I make a request of my own: Protective Bark from the Plant tree (presumably) is causing full body discomfort, even though it's my own skin, causing a debilitating 20% speed loss.
