### ISSUE TITLE
Add a Craftable/Constructable Sun Dial

### ISSUE THREAD

**Issue by SoggyDeafGuy** [CleverRaven/Cataclysm-DDA#56912]
### Is your feature request related to a problem? Please describe.

With the innawood mod in mind, I think it would be cool to add a semi primitive way to tell the time, besides just looking at the sun.

### Solution you would like.

>Instead of telling the time down to the exact second, like a wrist watch would, It can go in 30 minute increments.

>Takes a long time to make because you have to wait an hour to mark the "clock"

>Can only use it during the day, on the surface (duh :p)

### Describe alternatives you have considered.

Can either be a handheld device you craft, or something you construct.

**Comment by Light-Wave** [comment]
It would be great to have a sun dial as a building that requires direct sunlight to opperate and tells you the time when you are nearby. But I suspect C++ code is needed to implement it.

**Comment by evankimori** [comment]
I've been plumbing with this idea for quite some time with the mod but never got around to actually making the suggestion post like this one!

Initial thought was that it would be done through Construction req Stone tools at the very least, must be on overworld surface or at least constructed under Sky visibility. Has any more discussion or work has been done on this idea?
