### ISSUE TITLE
Error when creating new character, new map

### ISSUE THREAD

**Issue by dhasial** [CleverRaven/Cataclysm-DDA#56920]
### Describe the bug

Lab tech + some more skills, freeform points:
 DEBUG    : switch does not handle case f_null
 FUNCTION : Id mapgen_value<Id>::switch_source::get(const mapgendata&) const [with Id = int_id<furn_t>]
 FILE     : src/mapgen.cpp
 LINE     : 1323
 VERSION  : e9e4d30

### Steps to reproduce

1. Try to put a Lab Technician character in the Bottom of Labs
2. Get first error + game crash

### Expected behavior

I expect that I could put a Lab Tech character in a specific map and also be able to add freeform skill points to them without it crashing. It seems to still error without changing any points, but the game still loads. Trying to apply points, skills, etc. causes the above error and a complete crash. I wouldn't be surprised if the mods were causing this, I'm going to try and test without mods when I can.

### Versions and configuration

- OS: Debian Sid
- Game Version: Cataclysm-DDA experimental build 2022-04-19-0750
- Graphics version: Tiles
- Tileset: NeoDays
- Ingame language: English
- Launcher: Catapult
- Mods: Everything in Kenan modpack + the default mods
- Complete modlist:Aftershock,CrazyCataclysm,easy_proficiency,Miscellaneous_Magiclysm_Expansions,secronom,BL9-100%_monster_resilience_version,CRT_EXPANSION,Generic_Guns,MMA,secronom_lore_expansion,BL9-140%_monster_resilience_version,CulinaryDaysAhead,Lighter_Weariness,MMA_Mods_Extension,vamp_stuff,BL9-175%_monster_resilience_version,Dino_Mad_Science,Magiclysm,My_Sweet_Cataclysm,vamp_stuff_arcana,BlazeIndustries,DinoMod,MagicRevampAddition,no_cbm_slots,World_On_Fire,blazemod,easy_containers,Make_Bows_Great_Again,pixels_fuckery

**Comment by ZhilkinSerg** [comment]
Try to reproduce the issue without any third party mods.

**Comment by Dhamma-valence** [comment]
I can confirm that it doesn't happen when all mods including stock are disabled. So it's definitely a mod and not the core game's problem. Now to figure out which mod it is..
