### ISSUE TITLE
Lump of steel vs lump of steel vs lump of steel case 

### ISSUE THREAD

**Issue by stelscarrot** [CleverRaven/Cataclysm-DDA#56924]
### Is your feature request related to a problem? Please describe.

I am always frustrated, when I can't tell the difference between steel types when crafting

### Solution you would like.

Instead of behaving like this, there should be a way to differentiate them without looking into description. For instance change the names into "Lump of steel (high)" or "Lump of steel (h)".

**Comment by PatrikLundell** [comment]
#56913 did this yesterday... It hasn't been approved yet, though.

**Comment by stelscarrot** [comment]
> #56913 did this yesterday...

Huh, I once again hasn't searched good enough

**Comment by Zireael07** [comment]
Issues shouldn't be closed until the PR is merged, though.
