### ISSUE TITLE
Game crashes every time a zombie dies

### ISSUE THREAD

**Issue by Bulletfang** [CleverRaven/Cataclysm-DDA#56934]
### Describe the bug

The game crashes every time a zombie or the player character dies.

### Steps to reproduce

1. Kill a zombie.
2. Experience game crash.

### Expected behavior

No crashing.

### Screenshots

![54352354](https://user-images.githubusercontent.com/45204409/164114680-330e06de-5f26-4903-8a2f-662253d34068.JPG)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1645 (21H1)
- Game Version: e9e4d30 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

[logs and save file.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8516931/logs.and.save.file.zip)

**Comment by andrei8l** [comment]
#56915 should have fixed it. Can you try with a newer build? If it's still broken, please upload your memorial folder.

**Comment by Bulletfang** [comment]
The crashes no longer occur after updating, thank you kindly.
