### ISSUE TITLE
Bō is impossible to find unless you know how to write the ō special character

### ISSUE THREAD

**Issue by OnTheDouble** [CleverRaven/Cataclysm-DDA#56938]
### Describe the bug

In the crafting menu the bō is the only weapon with a special character in it.

It's unreasonable to expect an average player to know how to write it if they want to find this weapon.

### Steps to reproduce

1. Open crafting menu
2. Try to find bō
3. Fail because you are an average Joe and have no idea how to write ō with a US keyboard
4. Try to find bo instead
5. bō is not there

### Expected behavior

Either let the player find "bō" using "bo" or rename "bō" into "bo".

### Screenshots

![image](https://user-images.githubusercontent.com/82908191/164133203-810752b5-b593-4708-83d9-cde6bab24f7e.png)

### Versions and configuration

2022-04-19-1752 WIN 64

### Additional context

This is a problem in other situations as well:
- finding items nearby [V]
- using advanced inventory filter [/]
- using multi[d]rop, etc.

**Comment by fairyarmadillo** [comment]
In english, the item is usually just called a bo or a bo staff. I get the idea, but we don't write katana as 刀.

**Comment by OnTheDouble** [comment]
> In english, the item is usually just called a bo or a bo staff. I get the idea, but we don't write katana as 刀.

Renaming to "bo staff" is a good alternative. As a non-English speaker I want native input from you guys of course.

**Comment by fairyarmadillo** [comment]
> > In english, the item is usually just called a bo or a bo staff. I get the idea, but we don't write katana as 刀.
> 
> Renaming to "bo staff" is a good alternative. As a non-native speaker I want native input from you guys of course.

Oops, deleted my comment before I saw you replied because I felt it was unnecessary. That's my input though, we don't typically use the ō in english.

I can think of one other item, the zweihänder, that uses a nonstandard letter. I would suggest that one be changed too. It doesn't suffer the same problem because players can search zwei and find it OK, but maybe the rule should be that item names should be able to be easily typed using a standard keyboard for the language the game is being played in. Nonstandard letters can be used in the item description for clarity's sake.

I think bo staff is best in this case as a lot of items have "bo" in them and you'll still have some trouble finding it among your longbows, bottles, books, etc.

**Comment by Cerberus1746** [comment]
The search could have the special characters simplified when comparing, as in strip accents.

**Comment by Faalagorn** [comment]
I pretty much mentioned it in https://github.com/CleverRaven/Cataclysm-DDA/pull/57299#issuecomment-1120209375 but I agree that the search should show all results, similar to how Firefox or other modern software allow to. In Firefox, there's an option to exact match, but I don't think it's really required here.

**Comment by BrettDong** [comment]
This would need a Unicode library like `icu4c` to do the _Canonical Decomposition_ on accented characters to decompose them to _Normalization Form D (NFD)_ (`'ô'` -> `('o', 'ˆ'`).

**Comment by Cerberus1746** [comment]
> This would need a Unicode library like `icu4c` to do the _Canonical Decomposition_ on accented characters to decompose them to _Normalization Form D (NFD)_ (`'ô'` -> `('o', 'ˆ'`).

There's no builtin c++ decoding that would just transform ô to o?

**Comment by BrettDong** [comment]
> There's no builtin c++ decoding that would just transform ô to o?

It's not part of the C++ language.

**Comment by fairyarmadillo** [comment]
Would it be easier to introduce synonyms/aliases that could be added to items via json? It would probably get annoying if it got overused, but there are probably a couple items that such a feature could be used for, and it might be useful in other languages as well.

**Comment by Cerberus1746** [comment]
> Would it be easier to introduce synonyms/aliases that could be added to items via json? It would probably get annoying if it got overused, but there are probably a couple items that such a feature could be used for, and it might be useful in other languages as well.

Sounds like the simplest option indeed in this case

**Comment by jbytheway** [comment]
There is a related issue where searching is supposed to be case-insensitive but that doesn't work reliably for all languages.  Both require something like ICU (a Unicode library) to fix.

> Would it be easier to introduce synonyms/aliases that could be added to items via json?

That's OK for English names, but it's not easy to make that work when the translated name needs an alias but the English one didn't.
