### ISSUE TITLE
Aim/Examine box/reticule appears in same spot every time I move

### ISSUE THREAD

**Issue by Dhamma-valence** [CleverRaven/Cataclysm-DDA#56939]
### Describe the bug

If I press any movement key, the aim/examine box reticule appears in the same tile for exactly the time that I am holding down a keypress, disappearing after the release. Also, pressing `e` to examine will snap to the bugged tile location, as will opening the main menu. For me the bugged tile's location was five tiles down from my character, and it somehow moved one tile to the left of that after swapping between aiming and examining in an attempt to get rid of it). I doubt that the specific location matters much though, but I figured I'd include it just in case.

I believe it happened after my character first aimed and shot with a gun (but not immediately, after having fired it roughly 100 times). I think something is almost "stuck" with the aim/examine logic which causes it to appear on the keypress when it should not. I also was adjusting aim level to various degrees, possibly related, maybe no.

I will say that I'm not sure whether it's aiming or examining that it's related to, just that the tile that's bugging out is the same tile as is used in both.

### Steps to reproduce

I honestly have no idea.

### Expected behavior

I expected that the aim/examine tile would only occur when part of the associated function, and not in a random location while moving, in the main menu, or examining/aiming.

### Screenshots

https://github.com/Dhamma-valence/images/raw/main/CDDA_examine_tile_bug.png

I had major issues trying to record a gif of the bug, so I don't have that, but hopefully this image will give you a decent idea of what I'm looking at.

### Versions and configuration

- OS: Debian Sid
- Game Version: Cataclysm-DDA experimental build 2022-04-19-1752
- Graphics version: Tiles
- Tileset: NeoDays
- Ingame language: English
- Launcher: Catapult
- Mods: All mods, including stock, disabled

**Comment by Dhamma-valence** [comment]
I've realised that my view was offset, and the reticule was actually marking the center of the screen. If I move the view to get the reticule over my character, it goes away. Is this the intended behaviour?

**Comment by PatrikLundell** [comment]
Various things, in particular traveling in a vehicle, results in the center being offset. There is a key to recenter (I think the default binding is ':'). It's definitely useful to see a little bit further ahead while traveling at speed, so the offsetting itself has a use.
