### ISSUE TITLE
Odd slightly brighter area in evac shelter basement

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#56935]
### Describe the bug

There's a spot in the basement of evac shelters that makes it difficult to see for no apparent reason.

### Steps to reproduce

1. Go into an evac shelter
2. Check the basement.
3. Activate the "Display Lighting" function of the debug menu.

### Expected behavior

Brightness remains the same in all areas.

### Screenshots

Screenshot with "Display Lighting"
![Screenshot with "Display Lighting"](https://user-images.githubusercontent.com/2125926/164122474-983cf9e6-1b9c-4d5c-9940-a6abc10ac337.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1645 (21H1)
- Game Version: 3ad05f9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    No Vault [No_Vault],
    ASCIITiles overmap color fix [colors_fix_asciitiles]
]

**Comment by toweroglass** [comment]
my god! that has been there for so long i just started noticing it

**Comment by haveric** [comment]
From a quick look, this appears to be happening due to the stairs being misaligned from the shelter_1 variant, meaning that a new shelter_under will need to be created for this variant. I can take a stab at creating one, but if anyone else wants to, feel free.

**Comment by Inglonias** [comment]
Creating different basements for each of the shelter types would be pretty cool, so if you or anyone else feels up to making something like that...
