### ISSUE TITLE
Optimization: disable line of sight calculations on an npc

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#56957]
### Is your feature request related to a problem? Please describe.

Places like the refugee center can become extremely laggy, especially on older computers, due to the number of NPCs around.  Most of the time, these NPCs are needlessly complex and could be made much more simple to save calculations.

### Solution you would like.

My understanding is that of all the things NPCs track, line of sight is the most taxing. LoS is important to lots of things, but it really isn't needed for someone like the refugee center merchant or most of the beggars, except in particular circumstances.

I suggest an effect, "npc_complex", that can be defaults `true` but can be `false`. When `false`, NPCs no longer check line of sight, or perhaps refresh it much slower (10x or 100x slower). If possible I'd prefer the slower refresh, so that we do still have some LOS checking for pathfinding and such.

Most NPCs in the refugee center aside from guards should have this `false` by default. However using Effect on Conditionals, we can add a common EoC to rehenable npc_complex temporarily for nearby NPCs if hostilities are occurring. This re-enable effect can be a temporary one, allowing NPCs to spring to life and then resume their low power mode when done.

### Describe alternatives you have considered.

Another option is to convert static NPCs to talking monsters. I am seriously considering this, but it loses some useful features and will require a bit more coding for inventories and things. Another option is an effect to temporarily turn a monster into an NPC when it matters, but I think that's more trouble than it is worth.

Npc_complex could include many other high proc functions, but I don't know what they'd be. Most of these static NPCs really don't need to do much except stand around and have an inventory... If I want to move them around and do complex things I can have the effect that moves the NPC also turn it on for the duration.

### Additional context

When I start mapping out the refugee center basement, we're gonna be forced to have this or something similar. Hub01 and other large factions are also going to need it.

**Comment by dseguin** [comment]
Since creature LOS gets called from `sees`, I added early returns in `Character::sees` and `Creature::sees` when the creature is an NPC (basically disables sight for NPCs), just to see how that would affect performance:

##### Before

![before_sees](https://user-images.githubusercontent.com/12537966/164296302-ef82c285-25d3-4c77-9524-d4a2488b7777.png)

##### After

![after_sees](https://user-images.githubusercontent.com/12537966/164296315-83e384f5-5b0d-4fe1-8567-e190671420e5.png)

Didn't really notice a huge difference in-game, but maybe I'm looking in the wrong place.
