### ISSUE TITLE
Remove the prompt to pulp acid filled corpses if the character has enough environmental protection to not get a prompt when walking onto pools of acid

### ISSUE THREAD

**Issue by Drac4** [CleverRaven/Cataclysm-DDA#56954]
### Is your feature request related to a problem? Please describe.

Why is it relevant to still give a prompt about pulping acid filled corpses if I have enough environmental protection on legs and feet so that I don't get a prompt when moving onto pools of acid?

### Solution you would like.

Remove the prompt to pulp acid filled corpses if the character has enough environmental protection to not get a prompt when walking onto pools of acid.

**Comment by PatrikLundell** [comment]
Have you verified that there isn't any splashing above the legs when pulping?
