### ISSUE TITLE
Fixed Scenario creates characters with 100+ in every attribute

### ISSUE THREAD

**Issue by OnTheDouble** [CleverRaven/Cataclysm-DDA#56955]
### Describe the bug

The game allows for ridiculous attributes if you change attribute limit and select Fixed Scenario.

### Steps to reproduce

1. Go to Settings -> Options -> Debug -> Set all points to max (that would be 1000)
2. Select New Game -> Play Now (Fixed Scenario)
3. Receive a character with 100s in every attribute while the game limits max attribute to 20 at normal character generation

### Expected behavior

Limit Fixed Scenario attributes to the same value as all other Character Generation modes: 20

### Screenshots

![play_now_cdda](https://user-images.githubusercontent.com/82908191/164257223-a1e84b8c-7f85-4371-8b99-3371f436afeb.png)

### Versions and configuration

2022-04-20-0553 Win 64x Catapult

### Additional context

![image](https://user-images.githubusercontent.com/82908191/164257784-b115d383-1d1e-4a00-964a-41a808ade2d4.png)

**Comment by Night-Pryanik** [comment]
I'm not sure what's wrong here. You deliberately set maximum available points to 1000 and then you don't like the fact that game uses these 1000 points during character creation?

**Comment by OnTheDouble** [comment]
When you set these points to 1000 in Custom Character you can only go as high as 14. 
![image](https://user-images.githubusercontent.com/82908191/165590393-ecf932be-1476-4503-97f9-75eee2e6898b.png)
For Single Pool, the same.
![image](https://user-images.githubusercontent.com/82908191/165590505-5972e3f6-dc1a-439f-8ea3-2f87c723afb4.png)

In Freeform, it's 20.
![image](https://user-images.githubusercontent.com/82908191/165590586-4a86e0ba-5310-49e9-b522-4bfedd782846.png)
But for Fixed Character, it's all the way to 140s.

I only want to discuss why there's no consistency because it looks strange.

**Comment by OnTheDouble** [comment]
> I'm not sure what's wrong here. You deliberately set maximum available points to 1000 and then you don't like the fact that game uses these 1000 points during character creation?

[According to the design doc, Stats are capped at 20. ](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/GAME_BALANCE.md#stat-system-scaling)

> Superhuman: >20 (**Anything beyond this should require bionics or mutations**.) -- the bold is mine

So my point is the stats that go beyond 20 are impossible to have without mutations or bionics because you guys specifically said it in your design doc :)

In addition to that, when you use the Random Character start you can go back to the STATS tab and lower any stat to 4 but **you cannot then raise it again beyond 14** which is how it should be for anything other than Freeform where it's capped at 20.
![2022-09-09_04-43-42](https://user-images.githubusercontent.com/82908191/189254908-e331c9a8-9cbf-4b30-a7e0-1b9c0a7b0401.png)

![2022-09-09_04-44-41](https://user-images.githubusercontent.com/82908191/189254917-f0f5d8fc-69cc-4abf-8da7-a467fe156dcb.png)

**Comment by OnTheDouble** [comment]
I think the issue has been open long enough without any action so I am closing it.
