### ISSUE TITLE
There is no indication of the equipment need for the Hide Site faction camp action

### ISSUE THREAD

**Issue by Sofistico** [CleverRaven/Cataclysm-DDA#56952]
### Describe the bug

In the faction ledger, under Setup Hide Site, there is no indication of the materials needed, so when a player presses the button to select a site, the game tells the player that he doesn't have the material needed and then doesn't procced to tell what he needs, so there is a need for a clearer information of what is needed.

### Steps to reproduce

1. Have a base faction upgraded to the level so that the action "Setup Hide Site" is displayed.
2. Select it and note it's description that doesn't say what material, if any, is needed.
3. Select the tile
4. Note that the game cancels the action because there is no material needed, but doesn't tell what is needed.

### Expected behavior

The game should display the materials, if any, that are needed.

### Screenshots

Step 2:
![image](https://user-images.githubusercontent.com/59299346/164232038-71dfd771-45f9-4589-9f0a-f09b0b4e78ef.png)

- Step 4:
![image](https://user-images.githubusercontent.com/59299346/164231953-1d152737-cfd8-4f9c-a841-0eed6d8dd045.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19042.1645 (20H2)
- Game Version: a820c3e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Mythical Martial Arts [MMA],
    Stats Through Kills [stats_through_kills]
]

**Comment by PatrikLundell** [comment]
I don't understand the action, but I think you just move "stuff" there. However, when I tried to use it I only received a list of inventory items to move there when the character was blind (but not when the blindness was worked around), and in that state the action fails because the PC can't see anyone to send. I didn't bother to investigate it further because I don't find the functionality useful.
