### ISSUE TITLE
Give Proficiencies their own menu in the info options to ensure the HUD is less cluttered and more informative.

### ISSUE THREAD

**Issue by cataclysmsurvivalist** [CleverRaven/Cataclysm-DDA#56966]
### Is your feature request related to a problem? Please describe.

The Proficiencies system is becoming more and more detailed, involving everything from crafting, dissections and archery, to medicine and self-defense against things like electrical weaponry. This has been, to my experience, a very good way to increase game depth, and I've ever heard some rumors about the devs working on weapons and martial arts styles to add to the list.

### Solution you would like.

As the list of Proficiencies grow, from unique skills to daily things like Food Handling and fighting styles, it would be best to also expand the Proficiency info screen itself by giving it its own menu, just like Medical now has its own part in the info action options.

The menu could also provide more exact information for every skill. For example, the player can't really see what Basic Archer Form and Natural Exoskeleton do once mastered just by looking. A new menu could give them enough space to allow exact numbers and descriptors on what advantages they provide.

**Comment by dseguin** [comment]
Did you look at #56549?

**Comment by cataclysmsurvivalist** [comment]
> Did you look at #56549?

I have, I understand if it remains this way because it's efficient enough as it is, but I still believe Proficiencies having their own, bigger menu like Medical currently does would be better.
