### ISSUE TITLE
Cutting training doesn't detect the training dummy item

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#56961]
### Describe the bug

See the screenshot.

### Steps to reproduce

Load the attached game and try to "craft" `cutting (beginner)`.

### Expected behavior

"Crafting."

### Screenshots

![](https://tinystash.undef.im/il/3Hc47TS8NY5DegW2pwZTg1MsBP2V7RBmiTbtyKvsb6TDZKKzEPiaSjY8H5UbbAQXVUfna3Po2U6xDpruFf6v7b24)

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.F-7599-g931ad4f51d-dirty [64-bit]
- Graphics Version: Curses
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

https://tinystash.undef.im/il/4qiLyfHAkN8Pwmi84BfxsHKr1SLtRb59zNMeGpJUmwkJCdtDKsH1bPiXAm59y7iJnFDiyY8usQRjKPUtUhqhGmJt

**Comment by Aerin-of-the-Toast** [comment]
You have to install the training dummy as furniture through the * menu now, you can't just use it in item form anymore.
