### ISSUE TITLE
"Human Anatomy" Proficiency, trained by dissecting human corpses, and helped by certain books like The Big Book of First Aid.

### ISSUE THREAD

**Issue by cataclysmsurvivalist** [CleverRaven/Cataclysm-DDA#56967]
### Is your feature request related to a problem? Please describe.

Human corpses provide massive morale debuffs unless you're a psychopath, but in a situation like _this,_ understanding human biology sounds like one of the most precious skills someone could have.

### Solution you would like.

Human Anatomy should be a Proficiency obtained either by dissecting humans or selecting certain professions in the character creation menu.

Having Human Anatomy mastered would remove the debuff from dissecting other humans if you don't have the  Psychopath/Cannibal traits, and also help with the Health Care skill. It should also increase the odds of you obtaining a human sample upon dissecting other humans.

### Describe alternatives you have considered.

This is mostly unrelated but I also believe Spiritual characters should be able to avert the morale debuff from dissections, with a message like "you offer a brief prayer to the departed". In most Abrahamic religions and denominations, dissections are considered to be different from desecration of the dead, and in the late medieval times, the Catholic Church often stepped in to openly promote certain medicinal missions to study human anatomy through dissections, because peasants were horrified otherwise as they thought the physicians trying to research human biology were cannibals/grave robbers.

**Comment by Sirbab** [comment]
Why did you close this?
