### ISSUE TITLE
Military and police turrets do not trigger safe mode despite rules saying they should

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#56965]
### Describe the bug

Safe mode is not triggered by a riot control platform despite safe mode rules to the contrary

### Steps to reproduce

1. Load the following safe mode rules file: [safemode.json.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/8526244/safemode.json.txt)
2. Spawn a riot control platform, CROWS turret, or milspec searchlight. (Searchlight needs to be added to the attached rules)
3. Safe mode does not stop me from moving
4. Move within 10 tiles of the turret (after becoming invincible). Note that safe mode does kick in due to a rule that just says *.

### Expected behavior

Safe mode will stop me.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1645 (21H1)
- Game Version: d857d7d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    No Vault [No_Vault],
    ASCIITiles overmap color fix [colors_fix_asciitiles]
]

### Additional context

I suspect this is happening because these enemies are completely immobile.

**Comment by LyleSY** [comment]
I'm having trouble finding it in the JSON folder but the monster browser claims it has aggression correctly spelled out

**Comment by Inglonias** [comment]
Further testing reveals this applies to any immobile enemy in the game.

**Comment by Inglonias** [comment]
Closing. Turns out I'm an idiot who let their safe mode rules get too complex.
