### ISSUE TITLE
The flamethrower mounted on the car didn't work

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#56977]
### Describe the bug

The flamethrower mounted on the car didn't work。

### Steps to reproduce

I installed the turret control module on the car, and I installed the flamethrower. After that, it didn't work as well as other vehicle-mounted weapons.

### Expected behavior

Under normal circumstances, it will work just like any other vehicle-mounted weapon.

### Screenshots

![car](https://user-images.githubusercontent.com/93122052/164408675-ce48c719-921e-4578-8052-28b2eedd3904.png)
![dialo](https://user-images.githubusercontent.com/93122052/164408752-e7b4eefa-ee19-48b7-9a7a-5322bcae73ee.png)

### Versions and configuration

* OS: Windows
* Game Version:  bd20f38  [64-bit]
* Graphics Version: Tiles
* Game Language: English [en]
* Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
No Fungal Growth [no_fungal_growth],
Bionic Professions [package_bionic_professions]
]

**Comment by Hirmuolio** [comment]
You don't have ammo for the flamethrower. The system seems to be a bit wrong and requires some JSON changes.

The mounted flamethrower has "USE_TANKS" flag so it tries to take ammo from vehicle tanks. None of which contain flamethrower fuel (napalm, gelled gasoline or flamethrower fuel).

The mounted flamethrower uses flamethrower as base item. That flamethrower uses magazine so the mounted flamethrower also takes magazines.

The "USE_TANKS" overrides any magazines. So if the tanks have no ammo for the gun it won't be able to fire even though it has magazine.

Probably the turret flamethrower should be changed to not take magazines.

**Comment by irwiss** [comment]
Flamethrowers should work if you use 'flamethrower fuel' instead of napalm and somehow unload the magazine, as they detach magazine(fuel tank) when installed
Tested on f0d7703
