### ISSUE TITLE
Windows (VCPKG) compilation of CDDA broken for SDL2?

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#56975]
### Describe the bug

I can no longer compile CDDA. It worked 17 days ago, but didn't when I tried about a week ago and hasn't worked since (pulling the latest master every time).

As far as I can tell, it tries to build SDL2-2.0.14, which seems to be from December 2020. That fails because it tries to download mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst from a bunch of different mirrors where this version is older than any of the ones present.

### Steps to reproduce

1. Pull latest master.
2. Try to compile.

### Expected behavior

Successfully compile the latest master version.

### Versions and configuration

Windows 10.1, CVPKG

### Additional context

I'm not sure this is actually CDDA related, as VCPKG has updated itself as well. As far as I know I didn't update until after it failed, but I can't swear that there wasn't an update after the last successful compilation.
I also have no idea where SDL2 comes into the picture, apart from compiling CDDA triggers the problems.

**Comment by BrettDong** [comment]
I can compile. Update your `vcpkg` and rerun integration.

**Comment by PatrikLundell** [comment]
Thanks. I thought it was probably something on my end. vcpkg is updated to the latest (as per the prompts it gives, anyway. The latest time was yesterday or the day before).

I don't know what "rerun integration" means, though. Build and clean does not help, and I fail to find "integration" among any of tabs.

**Comment by BrettDong** [comment]
After `git pull` to update `vcpkg`, rerun `./bootstrap` and `./vcpkg integrate install`. If it still tries to download `mingw-w64-i686-libwinpthread-git-8.0.0` then `vcpkg` is still somehow in the old version.

**Comment by PatrikLundell** [comment]
Thanks for your great help!

And yes, it was Visual Studio that upgraded itself, not vcpkg...

In case anyone else has the same issue, "./bootstrap" turned out to be ".\bootstrap-vcpkg" and the corresponding backslash translation was needed for the integration command, using Powershell.
