### ISSUE TITLE
swag bag takes too long to drop

### ISSUE THREAD

**Issue by PLUUZ** [CleverRaven/Cataclysm-DDA#56986]
### Describe the bug

The worn swag bag takes 4 to 6 seconds to drop depending on how much is inside it.

### Steps to reproduce

Fill a swag bag with stuff.
Wear it.
fill it with stuff
drop it and observe how much time it takes

### Expected behavior

The swag bag is just a canvas sacked, thrown over the shoulder like a santa claus bag, right, or carried in the hand.

I would expect that it takes like 1 second to drop regardless of how much stuff is in it, since you just let go of it and it falls to the ground

### Versions and configuration

Linux curses a820c3e (exp. build April 20)

### Additional context

Seems like a problem that would have been addressed by this stale PR that wasn't fully merged #50179

**Comment by mqrause** [comment]
I'm not sure it's really just supposed to fall to the ground rather than carefully placed on the floor to not damage the stuff inside.

**Comment by PLUUZ** [comment]
If you suddenly see an enemy in combat I don't think you're going to spend 4-6 seconds carefully placing something on the floor. 

Anyway, the amount of time it takes to carefully put a bag that's in hand/over the shoulder on the floor isn't 4-6 seconds.  It's more like 1 second, or max 2.  (i just tried it)
