### ISSUE TITLE
Cannot insert larger items into a gallon-sized zipper bag

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#56983]
### Describe the bug

Even a much smaller zipper bag can fit more stuff inside.

### Steps to reproduce

Load the attached game, `/`, select the `gallon-sized zipper bag`, `e`, `i`, note it can't even fit the `scrap of meat`, unlike a `zipper bag`. 

### Expected behavior

Being able to stuff stuff into the bag.

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.F-7644-gbd20f38a38-dirty [64-bit]
- Graphics Version: Curses
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

https://tinystash.undef.im/il/4s3aEuHcF5TnnE8Y8LZ3zvcDMrBDPHTSN5CNz2pBW51sS3WtX71Fnb99fkYA7iBmf6k5J4VJsTtjUcJYNjtoYcVN

**Comment by andrei8l** [comment]
Your zipper bag is inside the chef's jacket
![Screenshot from 2022-04-21 16-19-22](https://user-images.githubusercontent.com/68240139/164466787-e3cdb386-8e00-48ce-ae79-d188cd8bd966.png)
which is full
![Screenshot from 2022-04-21 16-19-36](https://user-images.githubusercontent.com/68240139/164466826-4c03423a-3e7f-40c2-81ce-4ec56113dce0.png)
You can insert items in the zipper bag if you take it out of the jacket (ex: wield)
![Screenshot from 2022-04-21 16-19-48](https://user-images.githubusercontent.com/68240139/164466915-2f9f35a2-fe52-43d1-9ca3-5313f26c9eb2.png)

**Comment by l29ah** [comment]
Ohh, thank you!
Sadly there's no similar volume check when i fill my condom from a puddle.

**Comment by Zireael07** [comment]
@l29ah: Condom is a weird edge case that has a separate issue somewhere.
