### ISSUE TITLE
Controller support improvements

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#56996]
### Is your feature request related to a problem? Please describe.

Playing Caves of Qud lately, saw the controller option and tried it.  It is implemented shockingly well and is now my favorite way to play. Made me wonder if it is feasible in CDDA. There are vastly more keybindings and actions available at any given time. There is also the keyboard only preference and focus in traditional roguelikes. CDDA on mobile sounds crazy too but with adjustments and customizing even that works very well.

I not only this this is possible in CDDA, but also a very fun and engaging way to experience it.

### Solution you would like.

The goal would be to provide as full and customizable a gameplay experience as possible with Controller only input. CoQ is a great blueprint. The movement system is well done and the alt function is terrific, expanding the number of controller inputs. The alt-button works by changing other buttons to a 2nd layout while its held (usually the LT button).

A simplified Use button would be nice. The (e)xamine button for controller could be used for examining terrain (using control stick direction or at the players location with no extra input). Use for examining, talking to NPCs, but also to open and close doors. 

Menu navigation should be quite easy and actually more intuitive with LB/RB, LT/RT, and control pad input for switching between panels and tabs, rather than the various ways we have on keyboard. In game the left stick direction would apply to movement, examining, and other actions. Here is my example for how a default binding could look.

![control-example](https://user-images.githubusercontent.com/92204064/164534558-0ec871c3-3bb8-41fb-983b-a3ca7905c58c.png)

A customizable, radial quick menu (or similar) for special actions or using items would be nice. Mobile uses the shortcuts bar for recent and contextual input, so new functionality is not out of the picture. But even without that, it should be relatively friendly for most gameplay. Advanced actions like zones, looking at sky, peeking around corners, etc can all be performed easily enough with the Actions menu (Enter).  All keybindings can be changed of course. Saving layouts and having multiple would be very useful.

### Describe alternatives you have considered.

getting a mini Bluetooth keyboard...

concerning controller bindings, having 2 alt modes is an option but may be too complicated.

### Additional context

This would provide a whole new way to experience and enjoy Cataclysm while increasing accessibility. It could even open the door to possible console ports in the future. Sitting on the couch with friends and playing CDDA on a TV (from PC or console) would be a very enjoyable time.

Also this whole things is a mess, i will clean stuff up and clarify soon but i want to get it out there! Want to hear and thoughts or suggestions.

**Comment by liminalRoar** [comment]
ok so i just actually realized that CDDA does have (basic) controller support. Which is cool, but it could def use some work i think

**Comment by jiornojiovanni** [comment]
This would definitively help on mobile and other platforms. I could play on my fire tv with this 😄

**Comment by rumly111** [comment]
Let's be honest. Traditional roguelikes are meant to be played with keyboard :)

But gamepad is still possible. You could make the left or right bumper emulate keyboard Shift key, so in theory you can get an alternative "layout" for some of the keys (for example lower and upper "H"). That would make the code quite ugly, though.

Maybe the solution is to throw out gamepad events altogether, and just emulate keyboard presses with the gamepad.

**Comment by liminalRoar** [comment]
newer version-
![control-example2](https://user-images.githubusercontent.com/92204064/164720630-48482bc1-37b7-454f-9d3d-4631061e3788.png)

I think gamepad events is def the way to go. I'll have to look into how alternate layouts are normally done with controller. I have seen more games using it.

**Comment by robclouth** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/84269

I've implemented most of this
