### ISSUE TITLE
[Innawood] make yoke_harness recipe "autolearn": true

### ISSUE THREAD

**Issue by LyleSY** [CleverRaven/Cataclysm-DDA#56992]
### Is your feature request related to a problem? Please describe.

Innawood makes it impossible to build a yoke and harness. Youtube commenters say and I agree that that isn't intended by the mod. 

### Solution you would like.

The simplest fix appears to be giving yoke_harness  and any other needed recipes to build a wagon   "autolearn": true

### Describe alternatives you have considered.

Handling this in DinoMod (bug report went to me) but that doesn't appear to be where the problem lies

### Additional context

Requested in comments here https://www.youtube.com/watch?v=i-x6NXfwsNo

**Comment by Sathra225** [comment]
already done in #56553
