### ISSUE TITLE
Portal Storm NPCs

### ISSUE THREAD

**Issue by Mer1ck** [CleverRaven/Cataclysm-DDA#57004]
### Is your feature request related to a problem? Please describe.

During portal storms, many voices can be heard making various promises and claims, though these are quite simple lies and give no incentive to actually risk going out to see what's really beyond the veil.

### Solution you would like.

I had the idea that perhaps there could be a low chance for an eldritch NPC to spawn, offering to make good on such claims in return for a task. (Essentially a standard NPC quest) Such tasks could vary, but my initial thought was that they would involve making a construction of sorts that would serve to give the entity a foothold in our reality, allowing them to influence the world outside of portal storms. 

In return the entity could offer various boons or items, ranging from mild and risk free to largely beneficial yet self-destructive. Current ideas include mild artifacts, or some sort of "cosmic drugs" in the guise of forbidden knowledge that give considerable intelligence boosts, though have considerable withdrawal symptoms and bring you crawling back to the entity to acquire more in return for more of your service.

Essentially, its adding otherworldly NPC merchants that sells you eldritch crack and alien equipment in return for completing their quests. One could also add NPCs that are wholly malicious, and trick you into screwing yourself over for their own benefit rather than establishing any sort of deal.

### Describe alternatives you have considered.

The only alternative that I thought of was to take this to the Arcana Mod, since it seems rather close to what they've been working on with eldritch entities and magical artifacts.

### Additional context

I have incredibly little coding so I'm afraid I cannot contribute to the construction of this addition in any meaningful way.

**Comment by Mer1ck** [comment]
This is one of my first posts here, so I give my apologies in advance if there was something I missed that somehow makes this invalid or inappropriate somehow.

**Comment by Inglonias** [comment]
I don't know about if quests are possible, considering how ephemeral portal storms are. That said, summoning NPCs who talk to you in a more cogent way than the portal monsters do would be really cool.

**Comment by cataclysmsurvivalist** [comment]
This feels less like it's stretching into fantasy instead of sci-fi. I actually think it could be cool, but if implemented, should remain exclusively on the Arcana mod.

**Comment by Extra-Crispy** [comment]
There's no real solid boundary between what defines 'too much fantasy for your sci-fi,' considering the fact that much of the entire scenario is defined by otherworldly monsters and influences. There's already practically an entire faction of NPC's who have stepped through the veil, offering goods in exchange for services; I don't think it's too unreasonable for maybe in the very least have one of those hands that are reaching through a portal drop something useful or rare, should you kill or interact with it appropriately

**Comment by Mer1ck** [comment]
> I don't know about if quests are possible, considering how ephemeral portal storms are. That said, summoning NPCs who talk to you in a more cogent way than the portal monsters do would be really cool.

One thought I had that most quest chains could start with creating a structure, like an altar or stone cairn, unique to that particular entity. Once created, and perhaps when other conditions are met, (maybe the structure requires a brazier or something adjacent to it?) it'll spawn an immobile NPC named as "Fragment of -entity-" that you can continue your interactions with outside of portal storms. It would solve the possible issue of waiting for portal storms to continue any quests, or dealing with making sure that the same NPC is spawned regularly.

**Comment by PatrikLundell** [comment]
I hate portal storms with a passion, so take the below with a grain of salt.

I don't think it's suitable lore wise to have a comparatively simple construction act as a dimensional mooring point (that's what religions have claimed to do for thousands of years, with dubious success). A focus structure is perfectly fine, though. However, if the entity is capable of reaching through only during storms, that ought to remain the case. Allowing interaction only during storms provides a level of unpredictability that would be unique to that "faction", which I think would be good from a flavor perspective.

**Comment by Mer1ck** [comment]
> I hate portal storms with a passion, so take the below with a grain of salt.
> 
> I don't think it's suitable lore wise to have a comparatively simple construction act as a dimensional mooring point (that's what religions have claimed to do for thousands of years, with dubious success). A focus structure is perfectly fine, though. However, if the entity is capable of reaching through only during storms, that ought to remain the case. Allowing interaction only during storms provides a level of unpredictability that would be unique to that "faction", which I think would be good from a flavor perspective.

Then perhaps instead of serving as an anchor, it could instead be used as a dead-drop of sorts to exchange materials between the entity? If you have X items in a certain spot during the portal storm, then when the storm is over the items are replaced with the appropriate payment. 

Though, in regards to a semi-permanent anchor, if this is integrated as part of the Arcana mod then the initial structure could be upgraded with various arcane sub-structures imbued with essence and the appropriate artefacts. I suppose this also gives a progression path to pursue, rather than having reliable interaction right from the start.

**Comment by PatrikLundell** [comment]
I guess a dead drop might work for rigid transactions (although it might actually be tricky to implement delayed item replacement both in and out of the reality bubble), but if you want the flexibility of trading (select what to get and what to give) you need to interact, and the same probably goes for quests.

Of course, if it's placed in a magic mod of some kind, magic presumably works, so an anchor is presumably feasible.

**Comment by Mer1ck** [comment]
In addition, even without magic, interaction during early portal storms could make safe interactions feasible. The walls between realities could thin enough for them to get through to a specific destination, but not so thin that everything else can force its way through just yet.

**Comment by Jan-Blasiak** [comment]
I love the idea, and I would love for Portal Storms to be less like "just a terrible weather", and more like an actual extra-planar contact.

[Link to my minor idea](https://github.com/CleverRaven/Cataclysm-DDA/issues/56700)

**Comment by Mer1ck** [comment]
What are some of your ideas for various entities and patrons, along with their preferred favors and gifts?
So far all I have thought of would be someone on the malicious end, providing powerful yet self destructive boons in return for morbid sacrifices such as fresh human corpses. 

On the other end, a more neutral entity that gives some mild boons in return for rather mundane tasks and services. 

As for rewards, I was thinking:
- Mote of Forbidden Knowledge, a consumable that gives a large Int buff for a moderate time, but comes with a heavy risk of addiction and after a while heavy withdrawals. 
- Eldritch Blood, same as above but buffs strength and stamina rather than intelligence. 

We could also consider targeted mutations that fit whatever theme that fits with a particular entity. 
Thoughts?

**Comment by Inglonias** [comment]
This is an easy excuse to make some cool and new artifacts. Artifacts have been somewhat neglected after procedurally generated artifacts were retired. We can use this as an excuse to make some interesting artifacts with cool effects.

**Comment by Mer1ck** [comment]
One artefact would be the bio blade/sword. 
Itd make more sense to get it from an eldritch being than found in a lab.

**Comment by rathkiee** [comment]
Could have an NPC that you can converse with whose speech is all garbled, it is from an alternate dimension after all. After the conversation with the player it teleports them to the closest roofed area. 
Essentially introducing a benevolent creature to interact with during Portal Storms. 
Long term there could be a quest associated with getting to a lab or something to translate, but no need to start with that.
