### ISSUE TITLE
Increase the animal spawn rate for forests and cleared-out cities

### ISSUE THREAD

**Issue by cataclysmsurvivalist** [CleverRaven/Cataclysm-DDA#57000]
### Is your feature request related to a problem? Please describe.

There are too few animals around forest regions, and seeing animals around cleared-out cities are very rare. Both of those situations are very unnatural compared to reality, as it is very common to see animals even in urban places provided there are trees around, and animals move in abandoned cities very frequently.

All in all, animals are so rare that you'd be hard-pressed to picture how any hunter could ever manage to sell venison considering it's a rare delicacy in this world, and players often hesitate when hunting out of fear they might cause animals in a region to go extinct after like 1-2 successful game hunting.

### Solution you would like.

Animals should be more common in forests and places not densely-packed with zombies.

### Additional context

Admittedly, this is just as much for gameplay as it is for lore and immersion. Having a higher spawn rate for animals would ensure you don't need a working electrical fridge every time you go out to hunt for organs and meat out of fear they might spoil before you even get to cook them, or having to make a sadistic choice between resources and samples every time you're considering mutating your character. But I insist this is mostly about realism; real-life animals reproduce and repopulate far faster than what the game emulates.

**Comment by Jan-Blasiak** [comment]
ABSOLUTELY! 

I am currently living in a large farmhouse, next to both large meadows and a sizable forest, but I can barely find any animals running about, and of those that are nearby, only escaped chickens multiply.

**Comment by Maleclypse** [comment]
I believe that we can do some dynamic spawning now with EOCs but I'm not sure of that. @Venera3  if it can be done and you know how to do it please tag me with an example and I'll add it to the documentation/make a good first issue for it.
