### ISSUE TITLE
Invaild field types id for fd_smoke_overlay for brazier

### ISSUE THREAD

**Issue by Spacer-1970** [CleverRaven/Cataclysm-DDA#57010]
### Describe the bug

There is an error for the smoke from the brazier, when you start a fire in a brazier and wait for smoke to generate, instead of showing smoke, there is an error for  invalid field types id for fd_smoke_overlay and shows a white percent sign instead.

### Steps to reproduce

1.Set up a brazier.
2.Put firewood in the brazier and light a fire in the brazier.
3.Wait for some time to pass.

### Expected behavior

I expected to see the sprite for smoke instead of the error.

### Screenshots

![Screenshot (25)](https://user-images.githubusercontent.com/92626947/164598993-1766ac03-02e1-46c3-aa71-3478968c599d.png)
![Screenshot (26)](https://user-images.githubusercontent.com/92626947/164599255-067b81b2-8b1e-4cff-9caa-16f5ad89ded2.png)

### Versions and configuration

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8536751/debug.log)

**Comment by MNG-cataclysm** [comment]
I tested this in version 2022-09-04-0601, and the error never appeared or showed itself.  I think it might have accidentally been resolved somewhere along the line.

**Comment by Fris0uman** [comment]
Fixed by https://github.com/I-am-Erk/CDDA-Tilesets/pull/1311 basically that PR properly added the files from pngs_tall_32x64 into ChibiUltica and that's where the smoke overlay is. Before that Chibi add the json but not the sprite going with it and it was causing the error
