### ISSUE TITLE
Removing real-time calorie counting in consume menu 

### ISSUE THREAD

**Issue by Golfavel** [CleverRaven/Cataclysm-DDA#57013]
### Is your feature request related to a problem? Please describe.

With the introduction of the calorie counting feature with smartphones, you're now given the choice of being able to accurately know how many calories your character has consumed; however, while using this normally via (a)ctivating the device and choosing the option would normally give the player a choice (exchanging some battery power for an accurate calorie report), the consume menu bypasses this exchange and freely shows this information.

### Solution you would like.

The consume menu should no longer report an accurate calorie intake in real-time. Instead, it should report the most recent reading for the day, and if anything new has been consumed, show a "+" next to the number as an indication that the player has consumed more since they last checked their phone. The previous day's count will also follow this premise to encourage players to check the device at least once a day if they want an accurate report.

### Describe alternatives you have considered.

Disabling the consume menu's calorie count entirely and requiring the player to remember their last report themselves.

**Comment by Amoebka** [comment]
That's just adding additional keyboard clicks for no good reason. Smartphone charge isn't some rare valuable resource, letting the players to "cheat" 1 charge a day for QoL purposes is fine.

**Comment by I-am-Erk** [comment]
I would accept a solution to make opening your Eat menu take charges from your phone, perhaps, but for a QoL feature this seems needlessly punishing, and even the charge part is a little rough
