### ISSUE TITLE
Identical clothing made of high (Lycra) breathability material performs worse than poor (Fur) at lowering body heat

### ISSUE THREAD

**Issue by kenneth-ellis** [CleverRaven/Cataclysm-DDA#57033]
### Describe the bug

As I understand it, the intent of the new perspiration mechanics and breathability values is to allow the player to (somewhat) better cool off in hot weather by sweating, just as in real life.  Being _wet_ from sweat isn't the thing that cools the player (or a real person) down but rather the evaporative cooling (https://en.wikipedia.org/wiki/Evaporative_cooler#Physical_principles) effect carries heat away and reduces body temperature.

So if we sweat, but something (like wearing non-breathable clothing) prevents the sweat from _evaporating_ efficiently, this impedes the evaporative cooling effect so body temperature will remain higher.  (The person will also feel uncomfortable and 'muggy' with all the sweat trapped against their skin and unable to evaporate)

Based on this -- clothing with high breathability like Lycra (110) should perform better than those with poor breathability like Fur (30) in terms of allowing the player to stay cool and comfortable in hot weather.

Instead what I have observed through some methodical testing is that the opposite seems true:  A player wearing an otherwise identical (same coverage, same warmth, same flags, only material changed) jumpsuit made of Lycra and simply standing in the sun for several hours ends up with _higher_ body temperatures and incurring more Heat-Slowdown penalties for longer than one wearing a Fur jumpsuit.

Breathability does appear to be 'working' in the sense that the Lycra wearing player stays _dryer_ overall and does not end up with "Wet" morale penalties like the Fur wearing player.  However the enhanced sweat _removal_ the Lycra wearing player gets doesn't appear to translate into enhanced _evaporative cooling_ the way one would expect.

[test_jumpsuits.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8543915/test_jumpsuits.zip)

[Eskridge.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8543921/Eskridge.zip)

### Steps to reproduce

It's a bit difficult to accurately test this in-game currently since the different clothing items with different materials/breathability values _also_ have completely different warmth, coverage, flags, and other variables that would confuse the issue.  So in order to perform a 'clean' test I quickly modded some identical jumpsuits with 95% coverage of torso, arms, legs, and feet and 60 warmth.  I started with a newly generated world with starting day in Summer on the latest experimental and a no-skills no-traits all 8-8-8-8 character.

1. Load up the attached save which I used as the starting point for all tests performed, along with the test_jumpsuits.zip mod.
2. Use Debug menu to set Weather to Clear and Wind Speed to 0 (in that order) to remove these variables that might affect the test.
3. Find test jumpsuits of Fur, Cotton, and Lycra on the ground at your feet along with some bottled water.
4. Note that player is already Turgid as I started by drinking two bottles of water to allow for plenty of sweating.
5. Wear the Lycra jumpsuit.
6. Wait 1 hour and observe body temperature results via debug menu, check status/morale penalties & Heat Slowdown.
7. Drink a unit of water to replenish sweat & Wait 1 more hour, observe results again.
8. Drunk another unit of water, wait 1 more hour, observe results.
9. Repeat the above by reloading the save and wearing the Fur jumpsuit instead.
10. See that wearing an identical jumpsuit with 30 breathability (fur) results in lower overall body temperature and less Heat Slowdown than 110 breathability (Lycra) over time.

### Expected behavior

I expected the Lycra (high 110 breathability) to not only more efficiently _remove_ sweat from the player, but for the improved moisture-wicking evaporation to much more effectively cool the player than Fur (poor 30 breathability) garment with otherwise identical properties.

In general, the player should be able to maintain noticeably cooler body part temperatures while wearing high breathability clothing as a result of all that sweat efficiently evaporating away & causing evaporative cooling effect _rather_ than being trapped against their skin making them soaked and miserable.

Right now it seems the "soaked and miserable" part of poor breathability is working, and the "fast sweat _removal_" part of high breathability is working, but the "enhanced evaporative cooling effect" of high breathability is _not working_.  

### Screenshots

Baseline before starting tests, naked: Summer day 35 @ 11 AM, 75 F with "Clear" weather & 0mph wind set by debug menu - player drank 4 units of water for 'Turgid' status:
<img width="1280" alt="Naked-Baseline-11AM" src="https://user-images.githubusercontent.com/37091572/164787615-3613b2b4-cb9f-4d54-b631-a34a3f01f2f2.png">

After wearing **FUR** test jumpsuit (95 coverage, 60 warmth, 30 breathability) for **1 hour** & drinking 1 unit water:
<img width="1280" alt="Fur-1HOUR" src="https://user-images.githubusercontent.com/37091572/164788442-4b1d9883-fbcd-48df-9838-6ecbf7d1f9d8.png">

After wearing **FUR** test jumpsuit for **2 hours** & drinking 1 unit water:
<img width="1280" alt="Fur-2HOUR" src="https://user-images.githubusercontent.com/37091572/164788481-ebec56a1-1482-41aa-93be-4cd6c52d789b.png">

After wearing **FUR** test jumpsuit for **3 hours**:
<img width="1280" alt="Fur-3HOUR" src="https://user-images.githubusercontent.com/37091572/164788582-d3b97835-26cc-4bc7-a608-bbae518822cc.png">

After wearing **LYCRA** test jumpsuit for **1 HOUR**:
<img width="1280" alt="Lycra-1HOUR" src="https://user-images.githubusercontent.com/37091572/164788830-bc9eec18-2378-4236-ba9b-dcd7493facd6.png">

After wearing **LYCRA** test jumpsuit for **2 HOURS**:
<img width="1280" alt="Lycra-2HOUR" src="https://user-images.githubusercontent.com/37091572/164788920-989f23af-7d97-40fb-93d0-d0d92901f425.png">

After wearing **LYCRA** test jumpsuit for **3 HOURS**:
<img width="1280" alt="Lycra-3HOUR" src="https://user-images.githubusercontent.com/37091572/164788966-fcb2216d-c843-4703-a6fd-308d3bcc0c07.png">

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22598.200 (22H2)
- Game Version: 61562af [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Temperature Test Jumpsuits [testing_jumpsuits]
]

**Comment by bombasticSlacks** [comment]
I'm gonna try to look into this when I get a chance
