### ISSUE TITLE
Move the Necropolis to a mod for now, and rework it in the future

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#57030]
### Is your feature request related to a problem? Please describe.

The Necropolis is a great piece of content that, unfortunately, has become quite dated both in terms of lore and in terms of gameplay. Nobody has been keeping up on it and it's starting to develop bugs, issues, and omissions that are adding up to a bit of maintenance and release blockers.

### Solution you would like.

Ultimately, the Necropolis should be converted to something more suited to our lore (I suggest a bunker set aside by a cult of wealthy oligarchs connected to XEDRA and the government).

The missions for the Necropolis should be moved to another faction, or at least another quest giver, and adapted to a different location: the marshall missions should feel more 'savage wasteland' and less 'military spelunker'.

In the meantime, the Necropolis should be kept available for parting out or playing, but moved to a mod to indicate its status.

### Describe alternatives you have considered.

Obsoleting it would also be an option but it makes me sad.

Rather than either of these, someone could just step in and start parting out and updating the content, but that is not a small task.

**Comment by fairyarmadillo** [comment]
Just a heads up for whoever does this, I think there might be at least one reference to the necropolis in the lab terminal snippets. I believe it's the one that talks about one of the scientists taking a potential cure for the outbreak to a place called The Vault. If that's correct you may want to edit or remove it (or not, but know it's there).

**Comment by Perset** [comment]
Would it be acceptable to create a mod that disables the special, npcs, and snippets, but leaves the code in? Instead of migrating the code to a mod, if I understand what you're describing. I don't know whether the popular mods of cdda are dependent on the necropolis content, so might it be a problem if it was taken out?

**Comment by I-am-Erk** [comment]
We don't really manage our content based around the possibility that a mod outside our repo *might* be using it.  Since the necropolis in its present state isn't likely to stay, we shouldn't leave a half formed vestige of it in game.
