### ISSUE TITLE
Problems with inventory screen collapsing and expanding

### ISSUE THREAD

**Issue by RandDenner** [CleverRaven/Cataclysm-DDA#57044]
### Describe the bug

There's a problem with the inventory involving containers and collapsing and expanding the inventory listing.

### Steps to reproduce

In an inventory with stuff in a container, navigate to the container holding items:
![image](https://user-images.githubusercontent.com/73523034/164851816-8b729252-9983-41e0-ae83-d2cbb78dc014.png)
Push the > command to collapse the container list:
![image](https://user-images.githubusercontent.com/73523034/164852214-b490371c-945c-445e-8843-027a38884045.png)
Now push the < command to re-expand:
![image](https://user-images.githubusercontent.com/73523034/164852855-0872fd08-2b9a-438e-8f92-24d069a6a445.png)
Close and re-open the inventory and it goes back to normal:
![image](https://user-images.githubusercontent.com/73523034/164855364-44e5936f-7107-4a4d-9222-4065ff7bd8a2.png)
But only if you have it expanded. If it's closed when container inventories are collapsed and re-opened, it re-opens collapsed and if you attempt to expand it, you get a slightly different weird menu again:
![image](https://user-images.githubusercontent.com/73523034/164858868-993ed7ed-90c6-4682-8de1-778c3a0c0065.png)

### Expected behavior

Not this. Returning to the regular inventory is preferable.

### Versions and configuration

Latest experimental branch for Windows
Vanilla install

**Comment by RandDenner** [comment]
@andrei8l I think you should have a look at this.

**Comment by RandDenner** [comment]
Further testing:
First aid kit and survival kit in runner pack IN messenger bag:
![image](https://user-images.githubusercontent.com/73523034/164861544-2232ceef-7783-4c6a-adb2-dd0e8fb75081.png)
Collapse runner pack pressing >:
![image](https://user-images.githubusercontent.com/73523034/164861577-c77e05c6-b0ac-4895-a616-78513926db3e.png)
Expand runner pack pressing <:
![image](https://user-images.githubusercontent.com/73523034/164861619-e3038009-77fa-44b1-bc91-916d46f3f5ef.png)
Same sort of problem with a different method.

**Comment by Night-Pryanik** [comment]
More bugs: 
- pressing `;` to change inventory to show item categories isn't working at all if all containers are collapsed.
- if all containers are collapsed, press `<` to expand, then press `>` to collapse, then press `;` to show item categories. Triangle symbol disappears. 
![изображение](https://user-images.githubusercontent.com/11132525/165578360-c87377f9-d2f7-43d6-a3d1-20451853cf32.png)

**Comment by IndecisionTree** [comment]
/confirmed as of 044406a8ebb6673c00f886cc20bc19e9d2fe3fa6 the reflow issue still exists
