### ISSUE TITLE
Clean water gives parasites

### ISSUE THREAD

**Issue by TheShadowFerret** [CleverRaven/Cataclysm-DDA#57046]
### Describe the bug

Clean water can give parasites, despite being clean.

### Steps to reproduce

1. Find a water heater
2. Drink the clean water.
3. You will get the unhealthy warning, and can get parasites.

### Expected behavior

Not getting parasites from *clean* water.

### Screenshots

![image](https://user-images.githubusercontent.com/99621099/164862358-5d3a9d99-2cbc-41d6-aaaf-fd628015053d.png)
![image](https://user-images.githubusercontent.com/99621099/164878715-81c2d3e0-2e6b-4820-82d6-6568249a980a.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.613 (21H2)
- Game Version: 40392e5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA],
    Aftershock [aftershock],
    DinoMod [DinoMod],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Stats Through Kills [stats_through_kills]
]

**Comment by ZhilkinSerg** [comment]
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/55101

**Comment by ZhilkinSerg** [comment]
Related to https://github.com/CleverRaven/Cataclysm-DDA/issues/54097

**Comment by TheShadowFerret** [comment]
No longer replicable 🎉

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.613 (21H2)
- Game Version: 4f506d1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Aftershock [aftershock],
    Mythical Martial Arts [MMA],
    DinoMod [DinoMod],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills]
]
