### ISSUE TITLE
Combustion engine volume is much too low

### ISSUE THREAD

**Issue by batekulve** [CleverRaven/Cataclysm-DDA#57054]
### Describe the bug

Gas and diesel engines are much smaller in Cataclysm than they are in real life.
A 2-cylinder engine is 2L, which would fit inside a DVD player I had nearby (2.4L).
A 4.75L "powerful 6-cylinder combustion engine" can easily fit in one of my shoeboxes (11.3L) twice over!
[This real life 2-cylinder, 22 HP engine](https://www.harborfreight.com/22-hp-670cc-v-twin-horizontal-shaft-gas-engine-epa-61614.html) is about 125L if I did my conversions right. It's recommended for lawnmowers. It weighs 50kg.

This is causing the engines to have a ridiculously high density, as noted by these issues: #48512 and #54811

### Steps to reproduce

Just look at the JSON and compare it to any real-life engine.

### Expected behavior

Volume should be higher, and weight needs to be adjusted to match so that the density is something reasonable. The real life 2-cylinder I linked in the bug description has a density of 0.4 g/cm3. This low number is probably due to a lot of plastic parts being in modern engines, in addition to the empty space inside it.

### Versions and configuration

Game Version: experimental build 2022-04-23-0523

### Additional context

Realistically, I'm probably going to end up fixing this, but I'm creating an issue to keep track of the numbers and links.

**Comment by PatrikLundell** [comment]
The dimensions seem to be for the compartment it's supposed to be mounted in, allowing for space to actually mount it and so on, given the extremely low density (or might be the dimensions of the box it's shipped in). That box would float (and you can toss in a smallish adult human for good measure), if tossed into water with the engine inside, being about half as dense as normal wood.

I don't know anything about how engine dimensions are supposed to be used, though. Checking the dimensions gave about the same results as you have (128.X liters).

**Comment by batekulve** [comment]
Good point. I'll try to find other sources of engine block dimensions.
