### ISSUE TITLE
Smartphone and Waterproof Phone Cases Usability Issue

### ISSUE THREAD

**Issue by estebandellasilva** [CleverRaven/Cataclysm-DDA#57076]
### Describe the bug

So since the new Smartphone Cases are here i thought of using one - to listen to music and i dropped it.
Because one you start to use it ( i my case listening to music) it causes you to remove the Phone from the Phonecase (and drop it after moving)

You are also not able to put it back inside the phonecase during the time it is active

### Steps to reproduce

Get Phone - Activate Function (tested with Music) - Phone gets dropped and removed from Phone Case

### Expected behavior

Use the Phone inside the Phonecase without removing it

Maybe change the Phonecase to an upgrade like with guns.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19042.1645 (20H2)
- Game Version: dd9f086 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

**Comment by Ilysen** [comment]
The fix this was merged a little bit ago earlier today - #57019

**Comment by NetSysFire** [comment]
Closing as it is already fixed.
