### ISSUE TITLE
Hub 01 HWP (none) trade crash

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#57084]
### Describe the bug

The Hub 01 HWP with no barrel attached causes a crash if you open a trade menu while it's in your inventory or on the ground. Attaching a barrel prevents this.

### Steps to reproduce

1) Get a Hub 01 HWP
2) Don't put a barrel on it
3) Try to trade (I traded with the Hub 01 intercom, but it also crashed with the auxilliary outside)
4) crash

### Expected behavior

The game shouldn't crash.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1645 (21H1)
- Game Version: 4f506d1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by andrei8l** [comment]
Base HWP has ammo defined as `NULL` and I'm not sure why. Quick patch for this crash:
```diff
diff --git a/src/item.cpp b/src/item.cpp
index 5c8667b305..e5508c03ad 100644
--- a/src/item.cpp
+++ b/src/item.cpp
@@ -10386,8 +10386,8 @@ bool item::uses_magazine() const
 itype_id item::magazine_default( bool conversion ) const
 {
     // consider modded ammo types
-    if( conversion && !ammo_types().empty() ) {
-        const itype_id ammo = ammo_default();
+    itype_id ammo;
+    if( conversion && ( ammo = ammo_default(), !ammo.is_null() ) ) {
         for( const itype_id &mag : contents.magazine_compatible() ) {
             auto mag_types = mag->magazine->type;
             if( mag_types.find( ammo->ammo->type ) != mag_types.end() ) {
```
though there may be other places where null ammo/magazine can crash.
