### ISSUE TITLE
Standing fan appliance

### ISSUE THREAD

**Issue by ZombieZilla** [CleverRaven/Cataclysm-DDA#57099]
### Is your feature request related to a problem? Please describe.

Provides a way to cool down an area using an appliance that doesn't generate an exhaust

### Solution you would like.

Standing fan appliance, almost the same as the mountable cooler vehicle part, but appliance only and does not produce an exhaust

### Describe alternatives you have considered.

Doing it myself, but I am lazy and it would also require to be added to a lot of itemgroups for spawning

**Comment by Qrox** [comment]
A standing fan does not technically cool down an area though, it increases air flow which makes the human body cools down quicker by evaporation of sweat. Other items such as food cannot benefit from a standing fan (unless the fan also brings in colder air), since food does not sweat.
