### ISSUE TITLE
Recommendations on barrel and muzzle devices

### ISSUE THREAD

**Issue by nameless-feng** [CleverRaven/Cataclysm-DDA#57102]
### Is your feature request related to a problem? Please describe.

Why "acceptable_ammo" can not be used on firearms that have changed the caliber

M4A1 (5.56x45mm)
-Install [.300blk gunmod]

M4A1 (.300blk)(.300blk gunmod)
-Unable install [.300blk ported barrel gunmod]
	-"acceptable_ammo": [ "300blk" ]
-but can be installed [5.56x45mm ported barrel gunmod]
	-"acceptable_ammo": [ "223" ]
### Solution you would like.

[
    {
        "id":"barrel_ported_223",
        "type":"GUNMOD",
        "looks_like":"barrel_ported",
        "name":{
            "str":".223 ported barrel"
        },
        "description":"A ported barrel redirects exhaust gases to compensate for muzzle climb, improves recoil but increases noise and reduces accuracy slightly.This one is used for .223 (5.56x45mm) bullets.",
        "weight":"225 g",
        "integral_weight":"0 g",
        "volume":"200 ml",
        "integral_volume":"0 ml",
        "price":72000,
        "price_postapoc":500,
        "install_time":"5 m",
        "material":[
            "steel"
        ],
        "symbol":":",
        "color":"light_gray",
        "location":"barrel",
        "mod_targets":[
            "smg",
            "rifle",
            "pistol",
            "shotgun"
        ],
        "acceptable_ammo":[
            "223"
        ],
        "dispersion_modifier":15,
        "handling_modifier":4,
        "loudness_modifier":8,
        "min_skills":[
            [
                "weapon",
                5
            ]
        ],
        "flags":[
            "IRREMOVABLE"
        ]
    },
    {
        "id":"barrel_ported_300BLK",
        "type":"GUNMOD",
        "name":{
            "str":".300BLK ported barrel"
        },
        "looks_like":"barrel_ported",
        "description":"A ported barrel redirects exhaust gases to compensate for muzzle climb, improves recoil but increases noise and reduces accuracy slightly.This one is used for 300BLK (7.62x35mm) bullets.",
        "weight":"225 g",
        "integral_weight":"0 g",
        "volume":"200 ml",
        "integral_volume":"0 ml",
        "price":72000,
        "price_postapoc":500,
        "install_time":"5 m",
        "material":[
            "steel"
        ],
        "symbol":":",
        "color":"light_gray",
        "location":"barrel",
        "mod_targets":[
            "smg",
            "rifle",
            "pistol",
            "shotgun"
        ],
        "acceptable_ammo":[
            "300blk"
        ],
        "dispersion_modifier":15,
        "handling_modifier":4,
        "loudness_modifier":8,
        "min_skills":[
            [
                "weapon",
                5
            ]
        ],
        "flags":[
            "IRREMOVABLE"
        ]
    }
]

**Comment by Termineitor244** [comment]
Are you trying to suggest new items? If you already have the data entries of what you want, you could make a PR to try and getting it merged, but just pasting the item entries in the suggestions here will not do you much good, specially if it lacks of any explanation whatsoever and spaces/style.
