### ISSUE TITLE
Hazmat type suits claim to protect from gas when they don't.

### ISSUE THREAD

**Issue by Bossrman** [CleverRaven/Cataclysm-DDA#57106]
### Describe the bug

For some reason, protective suits such as hazmat suit, activity suit, and the hub01 envinronmental suit claim they "completely protect you from any gas" which is false. Being in a field of any type of gas will apply the effect regardless of if you have the protective suit on or not.

### Steps to reproduce

1. wear a protective suit of some form.
2. Encounter any form of gas, spawn a bloater zombie in debug and kill it for example.
3. Get poisoned despite it saying it protects you

### Expected behavior

I would expect the suits to not claim they protect from gas when they don't, it makes sense that they don't (they don't cover the mouth) but then why do they claim to do so? I feel that the "completely protects from any gas" should be removed.

### Screenshots

![Screenshot 2022-04-23 232647](https://user-images.githubusercontent.com/103338082/164959778-26b11a1d-154f-4efb-b58d-8523ad9a2e88.png)
![Screenshot 2022-04-23 232710](https://user-images.githubusercontent.com/103338082/164959785-9c9c9de3-4d0f-4dd5-a88e-ca428b96446f.png)
![Screenshot 2022-04-23 232725](https://user-images.githubusercontent.com/103338082/164959786-d929a7c8-b45d-45d5-b29d-3e256b823488.png)

### Versions and configuration

OS. Windows 10
Game version: "cdda-windows-tiles-x64-msvc-2022-04-22-0412"
mods loaded: Dark days ahead, no fungal growth, disable npc needs, bionic professions.

**Comment by MelacholicMimic** [comment]
As far as I'm aware, every one of these suits explicitly mentions you need to wear a gas mask for full protection. Furthermore, expecting a piece of clothing that doesn't cover your face will somehow protect you from inhaling gas seems very strange to me.

**Comment by Amoebka** [comment]
"Protects from gas" refers to gases that burn skin on contact. I'm not sure they even spawn anywhere in the game these days expect for a rare artefact activation effect. You need a gas mask for anything you inhale.

**Comment by Zireael07** [comment]
In that case, that protects from gas line ought to be reworded. By reading the description, I'd expect to be protected from gas even though it doesn't cover the face.

**Comment by Bossrman** [comment]
> As far as I'm aware, every one of these suits explicitly mentions you need to wear a gas mask for full protection.

Not all of them, the activity suit doesn't the closest to that is saying it can be worn with a helmet. In my most current playthrough (an older version, the one listed here is what I tested for confirmation) It was the first hazmat type suit I found.

**Comment by MelacholicMimic** [comment]
> "Protects from gas" refers to gases that burn skin on contact. I'm not sure they even spawn anywhere in the game these days expect for a rare artefact activation effect. You need a gas mask for anything you inhale.

It gets used for fungicide/insecticide gas if you have the relevant mutations, although reading through this, it looks like it hasn't been updated when gas masks were changed to use filters instead of an env protection threshold.
https://github.com/CleverRaven/Cataclysm-DDA/blob/77235b67732c05638887a1a5f023800957801f52/src/map_field.cpp#L1753-L1778


> In that case, that protects from gas line ought to be reworded. By reading the description, I'd expect to be protected from gas even though it doesn't cover the face.

But why? If you instead had dry suit gloves with the description, “This gear completely protects you from getting wet.” you wouldn't expect your head to stay dry when you jump into a river. It feels redundant to mention worn gear will only protect you on the body parts covert by said gear.

**Comment by Bossrman** [comment]
I mean, you still do need a gas mask for that, so it doesn't "completely" protect.

**Comment by MelacholicMimic** [comment]
Well, you're technically correct. The suit should prevent most, if not all damage to your limbs, but that's more of an implementation problem. I will still argue that with application of common sense "completely protects" can only be interpreted as "grants immunity in the scope of the item" as opposed to "protects all of you"

**Comment by Bossrman** [comment]
but if you look at like a combat exoskeleton, it says it "when worn with a power armor helmet fully protects from radiation" so the principle exists that if you need multiple pieces to achieve an effect it should state that
