### ISSUE TITLE
Magiclysm's Gunblade change suggestion to be used with mod martial arts

### ISSUE THREAD

**Issue by Zaixun** [CleverRaven/Cataclysm-DDA#57111]
### Is your feature request related to a problem? Please describe.

Magiclysm's gunblade currently is a gun that fits in a sword sheath and is durable, but incapable of being used in non-vanilla martial arts because it's a gun and lacks weapon category.

### Solution you would like.

Gunblade should be a melee weapon with gun_data used to have bullet firing capability so the gunblade can have weapon categories and have better compatibility with martial arts mods. Also this change could probably enable magiclysm to get rid of martialarts.json and use weapon category only.

### Additional context

I used the gun_data as a way to temporarily store gun mods on a transforming melee/ranged weapon with weapon category so I know that it's at minimum capable of having gun mods attached on

**Comment by Termineitor244** [comment]
The weapon could use a weapon category, their length makes me think they are a type of sword, so one of the sword categories should fit.

The magiclysm weapons in general could use an audit of weapon categories, if I (or nobody else) have not make it in a week or so, ping me to remind me to do it

**Comment by catdach** [comment]
> The magiclysm weapons in general could use an audit of weapon categories

Most of ```data/mods/Magiclysm/items/enchanted_melee.json``` was covered in #55756, everything else probably still needs doing
