### ISSUE TITLE
Pistol Bayonet is Unuseable

### ISSUE THREAD

**Issue by Kantonine** [CleverRaven/Cataclysm-DDA#57119]
### Describe the bug

Pistol bayonets don't add piercing damage on the handgun they're attached to, and don't display a damage change in menus

### Steps to reproduce

1. Find/Spawn pistol of choice
2. Find/Spawn Pistol Bayonet
3. Attach Bayonet
4. Note lack of damage from bayonet on gun

### Expected behavior

I expect pistol bayonets to be in line with the makeshift bayonet.

### Screenshots

![image](https://user-images.githubusercontent.com/91917075/164981924-4868bef9-1f37-4d1d-8986-3c274e5a009f.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.613 (21H2)
- Game Version: 0b45ac6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by andrei8l** [comment]
It's just missing a mode modifier in JSON. This seems to work:
```diff
diff --git a/data/json/items/gunmod/underbarrel.json b/data/json/items/gunmod/underbarrel.json
index 52005a446c..a3c4e1f592 100644
--- a/data/json/items/gunmod/underbarrel.json
+++ b/data/json/items/gunmod/underbarrel.json
@@ -484,6 +484,7 @@
     "mod_targets": [ "pistol" ],
     "min_skills": [ [ "weapon", 2 ], [ "melee", 1 ] ],
     "qualities": [ [ "CUT", 1 ], [ "BUTCHER", 15 ] ],
+    "mode_modifier": [ [ "REACH", "bayonet", 1, [ "MELEE" ] ] ],
     "flags": [ "STAB" ]
   },
   {
```
