### ISSUE TITLE
Isometric rendering seems borked

### ISSUE THREAD

**Issue by kazimuth** [CleverRaven/Cataclysm-DDA#57123]
### Describe the bug

I've always loved the HitButton_iso tileset and recently came back to the game and wanted to try and get it working again. I reconstituted it from [this repo](https://github.com/I-am-Erk/CDDA-Tilesets) and added an "iso" flag to the tileset.json. 

Unfortunately it doesn't quite work correctly:
<img width="1128" alt="borked" src="https://user-images.githubusercontent.com/555667/164991072-55c44f7b-aea5-4d9e-830d-4db0393b3e20.png">

The main screen is still rendering on a grid, but if you look at the minimap, you can see it's rendering isometrically. So this seems like some sort of bug in the isometric rendering code.

### Steps to reproduce

Download the tileset from here: https://github.com/kazimuth/Cataclysm-DDA/tree/HitButton_iso_again/gfx/HitButton_iso)

Enable it (e: in the main menu, *before* loading a save), restart the game, and load a save.

### Expected behavior

The main screen should draw isometrically.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1645 (21H2)
- Game Version: 3ad05f9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

I'd be down to be a maintainer for HitButton_iso (add new sprites etc) if we can get isometric rendering working again.

**Comment by kazimuth** [comment]
Update: wait, on a fresh build from latest master this issue goes away. Strange. So uh, I'm gonna close this.

**Comment by kazimuth** [comment]
Wait, aha, I figured it out. If you start the game, set the graphics to HitButton_iso, close the game, reopen, and start playing, the game will not render isometric. If you change to another tileset, then change back to HitButton_iso, isometric rendering works correctly. 

I suspect there is some sort of improper caching or misreading of the global iso_mode option going on:

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/cata_tiles.cpp#L660
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/cata_tiles.cpp#L1258

But I'm not entirely sure that's where the issue is.

**Comment by Qrox** [comment]
> start the game, set the graphics to HitButton_iso, close the game, reopen, and start playing, the game will not render isometric

I was unable to reproduce it, loaded a save right after starting the game and the tileset was rendered correctly.

**Comment by I-am-Erk** [comment]
I've been testing the game in smash button iso pretty regularly and haven't had this problem... I can try it out again tomorrow and make sure

**Comment by kazimuth** [comment]
May just be a bug on my machine 🤷

**Comment by esotericist** [comment]
i've just run into this myself with a recent tiles build ([2022-08-06-1614](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-08-06-1614)) on linux, and as the issue mention from qrox above indicates, fris encountered it as well on windows.
