### ISSUE TITLE
Allow dedicated safe mode rule sets for fast travel 

### ISSUE THREAD

**Issue by MelacholicMimic** [CleverRaven/Cataclysm-DDA#57120]
### Is your feature request related to a problem? Please describe.

With the excellent improvements to the autodrive feature, the game has reached the point where the player can reliably automate almost any long distance travel. 
This however introduces some dangers if one has custom safe mode rules. For instance, I have most enemies that only turn hostile if the player is relatively close to them excluded from mine, as it leads to mostly redundant prompts. 
Coupled with how fast travel tries to navigate around obstacles, “vehicle holes” when driving diagonal and the frame skipping, this has lead to multiple occasions of very undesired and very angry cougar/spider passengers. This can turn out pretty dangerous for characters that don't have their shotgun riding shotgun.

### Solution you would like.

Add a travel method tab to the safe mode manager that, similar to the mode tab, allows for the selection between manual | automatic | both 

### Describe alternatives you have considered.

Leave it as it is.

**Comment by Inglonias** [comment]
I have good news for you. This was implemented already with #53109. You can already make safe mode rules that only happen while you are driving. Just make sure that safe mode actually turns on while driving in the options screen.

**Comment by MelacholicMimic** [comment]
> I have good news for you. This was implemented already with #53109. You can already make safe mode rules that only happen while you are driving. Just make sure that safe mode actually turns on while driving in the options screen.

Yes, I am aware of this feature, I do even use it to describe my desired solution. What I am referring to is this: #49455 
My problem is, for me (and I would guess other long time players as well), there aren't many things that warrant extensive use of safe mode. 
Most rules are either an early warning system for hulks, juggernauts, and so on, rare enemies, or, if low on food, some butcherable animal I might miss while driving. I currently have 0 overlap between regular rules and rules I would like to be in effect when I use the fast travel feature. This means I currently have to en-/disable multiple rules each time or be prepared to save scum, which comes with its own sets of issues.
