### ISSUE TITLE
Can't Aim Up And Down Z-levels

### ISSUE THREAD

**Issue by bombasticSlacks** [CleverRaven/Cataclysm-DDA#57132]
### Describe the bug

scene doesn't render up and down zlevels correctly

### Steps to reproduce

1. Spawn an m4
2. Aim
3. try to look up or down a zlevel

### Expected behavior

Should be able to see the other levels

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1645 (21H2)
- Game Version: 01565ec [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by AlbertNewton** [comment]
I think this is because when you're shooting your view remains focused on you and not the targeting crosshair. I think the view should follow the aim point, which would include across Z levels.

**Comment by Maleclypse** [comment]
Need to be checked post the merged PR above.
