### ISSUE TITLE
Translation lost/changed back

### ISSUE THREAD

**Issue by heiyu17** [CleverRaven/Cataclysm-DDA#57144]
### Describe the bug

#57049. I really like that translation update, because it made all options/loading entries translated. But these translations changed back into English in later version.

Items' translations are still displaying fine.

### Steps to reproduce

Changed back: (option)
Detailed containers

Lost: (option)
Sound enabled
Display actions in "use item" menu
Suppress "Unknown command" messages
Night version color overlay
Day/Night cycle

Changed back: (world loading)
Effect types
Addiction types
Mutation categories

### Expected behavior

I am not a professional, so i don't know

### Versions and configuration

Ingame Language: except English
Game Version: c62a895 last no-bug version i tested

**Comment by Qrox** [comment]
That's what happens when strings are changed in the source files. Please wait for the next translation update.
