### ISSUE TITLE
Weirdly spawning towns

### ISSUE THREAD

**Issue by tinukedaya** [CleverRaven/Cataclysm-DDA#57148]
### Describe the bug

In my current run through I noticed some weird towns on my map. Some of those quite big, but have no name. One I just visited has a name, but no buildings... 

### Steps to reproduce

Don't know.

### Expected behavior

Towns have names and if they have a name they also have buildings.

### Screenshots

![image](https://user-images.githubusercontent.com/19891532/165116173-a29cfc77-15c1-483c-9852-478177e61d4f.png)
![image](https://user-images.githubusercontent.com/19891532/165116299-d3c433d9-445c-4047-9d06-3dd9ad765cbe.png)
![image](https://user-images.githubusercontent.com/19891532/165116450-47ef114e-565b-45ac-a992-e1f44de018e4.png)
![image](https://user-images.githubusercontent.com/19891532/165116927-bc9c113c-9663-48f5-99bb-86b872023b9d.png)
[Shelter Bay.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8555707/Shelter.Bay.zip)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 77235b6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    No Rail Stations [No_Rail_Stations],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Inglonias** [comment]
The town with no name you provided an image for is actually working as intended. Since I can't use spoiler tags on GitHub, I will say no more.

**Comment by ZhilkinSerg** [comment]
> The town with no name you provided an image for is actually working as intended. Since I can't use spoiler tags on GitHub, I will say no more.

https://gist.github.com/jbsulli/03df3cdce94ee97937ebda0ffef28287

**Comment by tinukedaya** [comment]
Ok, I can see, that the one without name is on purpose (it's twice there quite close to each other... that is ok too? You can see the second one in the top right corner of one of the screenshots.)... 

But what about the one town without buildings? Which weirdly enough, as I just noticed, has two names! :open_mouth: 

![image](https://user-images.githubusercontent.com/19891532/166331114-4540bf1f-a42a-486c-b112-696c0b0fef3e.png)
![image](https://user-images.githubusercontent.com/19891532/166331198-873e0f80-0080-4400-b2ff-7bc6a59df195.png)

If I move the cursor close enough to close the long name, the shorter one appears.
