### ISSUE TITLE
Taekwondo scales batle-axe damage

### ISSUE THREAD

**Issue by OldFriendEr** [CleverRaven/Cataclysm-DDA#57155]
### Describe the bug

Just tired to use taekwondo expecting some side kicks, but dealt unexpectedly high damage with back-kick 138! then dropped the battle axe only to deal 10-12, with brawling i deal 50-60 with the same battle-axe

### Steps to reproduce

1. wield any mele weapon
2. select taekwondo
3. notice no buffs, but increased damage and applied techniques

### Expected behavior

it is hard to tell but according to the description this MA shouldn't scale any melee weapon damage

### Screenshots

![image](https://user-images.githubusercontent.com/17822510/165170503-97385b98-855b-4650-b4e6-8a630ddecf33.png)

### Versions and configuration

Windows 10
Experimental 2022-04-25-1823 
615ddec (tiles)

**Comment by NetSysFire** [comment]
@Hymore246, as the resident martial art specialist, could you look into this please?

**Comment by Heitomos** [comment]
There seems to be an issue with Martial Arts and Attack Vectors - like where the attack is coming from. It could be related, as right now most fist weapons do nothing.

**Comment by Wyghab** [comment]
Wasn't there an issue with fist weapons that are not wielded in hand not being counted? Seems to be related to the attire thing. Think it simply just doesn't consider worn gloves as possible weapons for martial arts. (Faulty logic with certain functions that check for unarmed?)

**Comment by Heitomos** [comment]
> 

Yes, mutations like Claws are also failing to work.
