### ISSUE TITLE
Cold Blooded compatibility

### ISSUE THREAD

**Issue by madladthad42** [CleverRaven/Cataclysm-DDA#57162]
### Is your feature request related to a problem? Please describe.

Frustrated by the fact that there's nothing i can do to prevent a ~ -60% speed debuff while exploring an ice lab with the cold blooded trait

### Solution you would like.

Instead of the debuff being solely related to the outside temp, could the climate control CBM, or electric thermal gear help reduce the penalty?

**Comment by Amoebka** [comment]
Electric thermal gear definitely should be changed to reduce the penalty.
In the meantime, you can keep a working space heater in your backpack. Hot air fields raise the tile temperature.
