### ISSUE TITLE
Gun mod locations

### ISSUE THREAD

**Issue by Pritzwalk** [CleverRaven/Cataclysm-DDA#57160]
### Describe the bug

Several guns cannot attach gun mods due to their json referencing outdated mod locations.

### Steps to reproduce

1: Load in a character with max skills.
2: Spawn any weapon that has a mod location that includes the word "mount"
3: Spawn in any gun mod that uses that slot and try to attach it.

### Expected behavior

You should be able to attach the gun mod if you have the relevant skills.

### Screenshots

Saiga cant equip underbarrel laser despite saying it has an underbarrel slot 
![4](https://user-images.githubusercontent.com/103595335/165192059-641b3433-4bf5-491c-9535-060c90b060af.png)
![1](https://user-images.githubusercontent.com/103595335/165192028-fa328a88-39d9-4828-b510-b011e2d53cea.png)

When the json is changed to remove the word mount from mod locations it works
![3](https://user-images.githubusercontent.com/103595335/165192127-252f3181-e549-4870-ae70-5555c4727f0d.png)
![2](https://user-images.githubusercontent.com/103595335/165192200-b7a05297-179f-4ef3-bd65-3a96b2668a4c.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1526 (21H2)
- Game Version: 209b7d1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by toweroglass** [comment]
This isn't conveyed very clearly in the game but a "sights mount", for example, means you can attach a mount for sights to the gun. this is a permanent alteration to a gun that doesn't take sight mods out of the box.

**Comment by Pritzwalk** [comment]
If thats the case then fair enough I wish was a bit clearer then.

**Comment by catdach** [comment]
Basically just echoing toweroglass; this isn't a bug, it's intentional. These mod locations are meant for the items in ```json\items\gunmod\mount.json``` which then let you modify your gun further.

**Comment by Pritzwalk** [comment]
Fair enough it does seem to be intended just not clear.
