### ISSUE TITLE
Impossible shape throws a "Tried to use an invalid alpha talker" error every several turns

### ISSUE THREAD

**Issue by Gantolandon** [CleverRaven/Cataclysm-DDA#57175]
### Describe the bug

My character sits in a building during a portal storm. Several times an impossible shape is spawned. Seeing my character through the window, it tries to use some attack, but this only results in an error message with the following debug message: "ERROR : src/npctalk.cpp:1693 [talker* dialogue::actor(bool) const] Tried to use an invalid alpha talker"

### Steps to reproduce

1. Wait until the portal storm.
2. Enter a building with windows.
3. Stand near the window.
4. Wait until an impossible shape spawns.
5. Skip turns.

You can use the provided save file, which already has the impossible shape spawned: https://www.dropbox.com/s/jm5846v712q4d40/Aneta.zip?dl=0

### Expected behavior

No error message, the impossible shape does what it needs to do.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1645 (21H2)
- Game Version: 90c3b39 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8565087/debug.log)

No crash.log, as the game hasn't crashed yet.

**Comment by andrei8l** [comment]
```diff
diff --git a/data/json/monster_special_attacks/spells.json b/data/json/monster_special_attacks/spells.json
index 247ba5925a..888ceacadd 100644
--- a/data/json/monster_special_attacks/spells.json
+++ b/data/json/monster_special_attacks/spells.json
@@ -416,7 +416,7 @@
     "id": "impossible_shape_attack",
     "name": { "str": "Impossible Shape Attack" },
     "description": "Hurts you mentally.",
-    "valid_targets": [ "hostile", "ground" ],
+    "valid_targets": [ "hostile" ],
     "max_level": 1,
     "flags": [ "SILENT", "NO_HANDS", "NO_LEGS" ],
     "base_casting_time": 75,
```

**Comment by Gantolandon** [comment]
I can confirm that the adjustment in the comment above makes the impossible shape no longer throw an error every time it attacks.

**Comment by Moth-Tolias** [comment]
is the bug just that `ground` isn't meant to work with this attack [and can therefore be fixed by removing `ground` from the json as seen above] or is ground a valid target and there's a missing check somewhere?

if it's just the json and nobody else has already claimed it, we'd like to do this

**Comment by andrei8l** [comment]
`u_can_see`, `u_add_effect`, and `u_add_morale` used here need an alpha talker so they can't be cast on the ground. You can add a safety check to set alpha to player character if one is not provided (like in `u_message`), but I'm not sure if that makes sense. In this case it'd let impossible shapes attack through windows which is probably desirable.

**Comment by Moth-Tolias** [comment]
guess i got sniped while i was trying to understand the code. ah well.
maybe an assert should be added to the place that loads the spell json, so that errors like these can be caught ahead of time in the future?
