### ISSUE TITLE
Allow hiding basecamp recipes

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#57174]
### Is your feature request related to a problem? Please describe.

Basecamp recipe lists can get very bloated due to the sheer number of recipes available, even before modding. A lot of these recipes are ones that aren't needed on a regular basis, such as tools and weapons, and simply take up space on the menu once the need for the items in question has been fulfilled. Some recipes  aren't really useful under any reasonable circumstances, such as the scrap armor and crude sword (since by the time you're able to have them crafted at a basecamp, it's pretty likely you already have better equipment readily available). Furthermore, some construction recipes may be undesired by a player who has an alternative in mind, such as the palisades for the new farms.

### Solution you would like.

I would like to be able to hide basecamp recipes in the same way that recipes in the crafting menu can be hidden.

### Describe alternatives you have considered.

1. Living with the bloat
2. Modding out recipes I don't need at any given time, only to mod them back in when I find that I do need them again

**Comment by PatrikLundell** [comment]
A proper solution for crafting would be to give basecamp crafting a UI similar to the one used for PC crafting. That wouldn't help with unwanted construction entries, though.

If hiding/displaying of regular level (i.e. the only one, currently) menu entries was implemented it would deal with the crafting entries until they're moved to a crafting level, though (where filtering of them ought to be implemented).

There might be some complications, though, as the set of entries displayed changes and versions are updated (or the language used is changed), so something suppressed might not actually exist if you try to reveal it. There's also the issue of how to identify what you're suppressing, as entries are just strings of text at the display level.
