### ISSUE TITLE
Helicopter Crash earning too much points

### ISSUE THREAD

**Issue by Leosky** [CleverRaven/Cataclysm-DDA#57178]
### Is your feature request related to a problem? Please describe.

Helicopter Crash start give 5 points for a start with few minor bleedings, in a isoled location (low risk to attract zombies from nearby locations. The helicopter give good chance to give medikits/ifaks from the location loot or eventual soldiers/lab zombies giving a good chance to be able to heal straight from the location without any danger/challenge and some other good loots (in tests i got some start with ridiculously good loots like high-end guns or drugs.

### Solution you would like.

Adding a fracture to a limb could give a better balance for this start as it can't be cured from the start if you find medkit/ifak. The challenge would be deported to having to find food with broken limb but still not enough for justify 5 points as the location itself is located most of the time in the rural area, near farms on the few start i made, so maybe lowering to 3-4 points could be necessary to be more balanced.

### Describe alternatives you have considered.

* I considered adding heavier bleeding but it would be still be the same "medkit/ifak in the helico ? -> 1) no: die and restart, 2) yes: full win" loop.
* Changing the location to a crash in a city with a surrounded start. But there is still possibilities to get in a too small city.
* Making larger crash location with higher challenge, but it would require lot more time/experience to make and combat oriented things would be squished with the starting guns.

### Additional context

Combined with combat medic profession costing 5 too, you have a strong survivor with weapon with 0 points and almost no risks. Combat medic should cost more points regardings of what it give.

**Comment by Leosky** [comment]
I forgot to say it's for discussion, i can make the changes myself after discussion.

**Comment by Termineitor244** [comment]
> "medkit/ifak in the helico ? -> 1) no: die and restart, 2) yes: full win" loop.

That's a horrible behavior around which to balance things around... The start could maybe have its offered points reduced by 1 or changed to be more interesting, but the current balance is mostly fine, I started several times surrounded by zombie soldiers (even a zombie bio-operator) which is a pretty good way of compensating for the points offered, of course, the player can save scum what they want, but that should not affect the standard difficulty of the scenario (And there are discussions around how the point system does not help balancing things, I would like for it to be gone for good).

**Comment by Leosky** [comment]
> > "medkit/ifak in the helico ? -> 1) no: die and restart, 2) yes: full win" loop.
> 
> That's a horrible behavior around which to balance things around... The start could maybe have its offered points reduced by 1 or changed to be more interesting, but the current balance is mostly fine, I started several times surrounded by zombie soldiers (even a zombie bio-operator) which is a pretty good way of compensating for the points offered, of course, the player can save scum what they want, but that should not affect the standard difficulty of the scenario (And there are discussions around how the point system does not help balancing things, I would like for it to be gone for good).

Yeah, save scumming shouldn't be considered but still, bio operator against gun is no match and free loot. The point is around the danger of the location at the start, there is no way to compare helico crash next of infected for 4 points. Infection is a kind hard to cure condition, and the start is surrounded.




> I do think the balance is fine as is, especially since deserted island was included as a possible spawn location.
> 
> > eventual soldiers/lab zombies giving a good chance to be able to heal straight from the location without any danger/challenge and some other good loots (in tests i got some start with ridiculously good loots like high-end guns or drugs.
> 
> You're treating this as if the associated classes were free. Some of them will make it trivial, sure, but that shouldn't be what the scenario is balanced around of. If we follow this logic, it should actually be worth more than it is, since the net 2 points I get from National Guard are not really enough compared to default evac start.

National Guard start with a go bag with gun and ifak inside. It worth it-self 2 point if you compare to some other start with even less stuff.

**Comment by anoobindisguise** [comment]
TBH there shouldn't even be zombies at the heli crash spawn, you just crashed and the corpses didn't have time to zombify. It makes sense for generic crashes (crashed unknown # of days ago) but not for the player's.

**Comment by Termineitor244** [comment]
> TBH there shouldn't even be zombies at the heli crash spawn, you just crashed and the corpses didn't have time to zombify. It makes sense for generic crashes (crashed unknown # of days ago) but not for the player's.

Good point, maybe changing the scenario to spawn surrounded by the things that hit you would make more sense.

**Comment by MelacholicMimic** [comment]
>National Guard start with a go bag with gun and ifak inside. It worth it-self 2 points if you compare to some other start with even less stuff. 

Career Politician then. 

>bio operator against gun is no match and free loot

But the scenario doesn't give you a gun. That's the point I'm trying to make. The class gives you that gun and you are using your points for that. Guns are a kind of a moot point anyway since they will invalidate the start of nearly any scenario.
 
Is starting, alone, bleeding, in pain, slowed, possibly on an island, most likely next to a zombie of varying difficulty worth 5 points? Probably, the point costs are arbitrary at best. You could lower it to 4, sure, then again infected is arguably free points if you pick lumberjack and properly utilise the npc.  
A broken limb defiantly feels like too much and should probably get a scenario on its own anyway. I find the other solutions similarly overtuned.

**Comment by Leosky** [comment]
> > National Guard start with a go bag with gun and ifak inside. It worth it-self 2 points if you compare to some other start with even less stuff.
> 
> Career Politician then.
> 
> > bio operator against gun is no match and free loot
> 
> But the scenario doesn't give you a gun. That's the point I'm trying to make. The class gives you that gun and you are using your points for that. Guns are a kind of a moot point anyway since they will invalidate the start of nearly any scenario.
> 
> Is starting, alone, bleeding, in pain, slowed, possibly on an island, most likely next to a zombie of varying difficulty worth 5 points? Probably, the point costs are arbitrary at best. You could lower it to 4, sure, then again infected is arguably free points if you pick lumberjack and properly utilise the npc. A broken limb defiantly feels like too much and should probably get a scenario on its own anyway. I find the other solutions similarly overtuned.

Okay got it, let's consider just Helicopter crash as refugee. With current bleed mechanic, the bleed last... may be one hour at most, the pain, 6-8h. Is this worth 5 points ? Not really... 
If i had to consider a start in a evacuees shelter with theses impairment, i would barely give it 2 points. Now does the possibility to have a few soldiers near worth 3 points ? definitively not. 

A 5 points is a start needing a bit of mastery, and this start definitively doesn't need a lot of it. Compared to the 6 points for Island Prison or 4 for Infected requiring both way more knowledge to get out of initial conditions.

**Comment by MelacholicMimic** [comment]
**Best case scenario:** You're in a field with a bit of pain/damage and a light bleed. Since you get no NPC or food/water you'd get in evacuee I would put this at -2 points.
**Worst case scenario:** You're on an island, 3 limbs are down to “||...”, you're in unimaginable pain and have heavy arterial bleeding. There are 2 zombie pilots 2 tiles away from you, and the next closest shore is another 6 over map tiles away. I'd give this one -8 Points.  

A middle ground of 5 points is fine imo. But as multiple people have pointed out so far, the point system is inherently flawed. There is no underlying balance guideline, and if there ever was, it has been severely outgrown by the scope of the game. Most existing scenarios have very little to do with how they were originally intended, but the point cost is still the same. See broken cyborg start for example.

**Comment by Leosky** [comment]
> Let me tell you a secret - the points are a lie.
> 
> All of the chargen process is completely, absolutely inbalanced, and it will be probably be completely overhauled at some point.

Well, it's most than needed

**Comment by anoobindisguise** [comment]
We can probably just close this since points are outright 100% going away.
