### ISSUE TITLE
Numpad Enter does not function

### ISSUE THREAD

**Issue by onura46** [CleverRaven/Cataclysm-DDA#57182]
### Describe the bug

Numpad Enter no longer functions the same as Enter in menus like it used to. I believe it's probably related to changes in #57139.

### Steps to reproduce

1. Start up an experimental version of the game and navigate the menus a bit
2. Note that Numpad Enter can't be used in menus like Enter can

### Expected behavior

"Enter" and "Numpad Enter" should function the same.

### Versions and configuration

OS: Windows 10
Game Version: x64 MSVC https://github.com/CleverRaven/Cataclysm-DDA/commit/3e81ac151aa06a98aaa35de64a3b118425ecdfcf
Graphics: Tiles
Language: English (US)
Mods: dda, blazeindustries, package_bionic_professions, no_fungi, no_npc_food, StatsThroughSkills, stats_through_kills, speedydex, extra_mut_scens, crazy_cataclysm, no_fungal_growth

**Comment by Leosky** [comment]
I had to rebind numpad enter too. Seems an issue with the symbol/key_code for numpad enter not being considered as normal enter.
