### ISSUE TITLE
Shocker zombies have infinite range

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#57199]
### Describe the bug

Shocker zombies have infinite range. Anecdotally they also seem to be doing WAY more damage than before but this could just be because I'm getting caught dead center in the cloud rather than the fringes which do less damage since I usually tried to position around their max range (which is impossible now)

### Steps to reproduce

1. Go to an open sewer.
2. Observe.

### Expected behavior

They are supposed to have 8-10 tiles of range or so. If anything it should even be less than this, shocker zombies violate physics so hard that no amount of Blob Magic can explain it away. Currently letting one of these into your LOS is more or less a death sentence, because they do insane damage that passes through all obstacles, and even with 120 speed and fleet-footed, with no pain and full stamina, they *still* move faster than me...

### Screenshots

![Screenshot 2022-04-26 193334](https://user-images.githubusercontent.com/56016372/165429842-ff47bffb-8ae3-4cec-b623-5458bc910796.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.613 (21H2)
- Game Version: 90c3b39 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots]
]

**Comment by Night-Pryanik** [comment]
Yeah, it seems like I accidentally removed range restriction in #56871.

**Comment by PatrikLundell** [comment]
I think this means @Night-Pryanik provided the confirmation the tag is asking for?
