### ISSUE TITLE
QoL because of the last update. KEYPAD_ENTER vs ENTER as a confirm choice action

### ISSUE THREAD

**Issue by OnTheDouble** [CleverRaven/Cataclysm-DDA#57198]
### Is your feature request related to a problem? Please describe.

Apparently since the April 26 update the devs separated ENTER and KEYPAD_ENTER buttons.

This means that we can now use KEYPAD_ENTER for other things which is cool (I guess?).

What's not cool is if you actually liked using KEYPAD_ENTER for confirm choice action you are in trouble. Because right now there's **NO WAY** to assign KEYPAD_ENTER to Confirm Selection. It's greyed out. 
![image](https://user-images.githubusercontent.com/82908191/165420138-a29787a3-f31e-428c-9ad6-5afc4c58ddcb.png)

### Solution you would like.

Make Confirm Action configurable so we can assign KEYPAD_ENTER to confirm as it was before.

I mean... we can restore it for advanced inventory as Move a Single Item.

![image](https://user-images.githubusercontent.com/82908191/165420656-23320c12-3f56-429f-abfb-030f07f5b632.png)

Why not everywhere else? In [W]ear menu. In multi[d]rop menu. In [w]ielding menu. In Main Menu.
![image](https://user-images.githubusercontent.com/82908191/165421337-a75364c2-1e79-4405-9264-24a32721732d.png)
![image](https://user-images.githubusercontent.com/82908191/165421436-bcf52665-d901-481e-acbd-c993353dad35.png)

### Describe alternatives you have considered.

Suffering a huge QoL loss because KEYPAD_ENTER is so close to my right hand and my movement buttons while ENTER is in the middle of the keyboard and close to neither of the player's hands.

### Additional context

The whole reason to have a selection in menus is to allow the player to skip using Y, N, or other related buttons and use directional buttons instead. Stripping the player of this alternative is bad UX.
![image](https://user-images.githubusercontent.com/82908191/165421745-ee5dbf74-033d-4cca-b82a-30c2136746d6.png)

**Comment by dseguin** [comment]
Most likely related to #57139

**Comment by Qrox** [comment]
AFAIK greyed out means the keybinding is global, in which case you can press `=` to assign it. The change to separate RETURN and KEYPAD_ENTER was to ensure consistency between the curses and tiles builds, in addition to allowing assigning the keys as separate keys.
