### ISSUE TITLE
stale bot and github actions bot seems to be fighting with each other

### ISSUE THREAD

**Issue by BrettDong** [CleverRaven/Cataclysm-DDA#57211]
### Describe the bug

![image](https://user-images.githubusercontent.com/21075502/165593180-51c58480-cbf1-4c42-862f-38d8e67ab60b.png)

### Steps to reproduce

See https://github.com/CleverRaven/Cataclysm-DDA/pull/54711

### Expected behavior

Two bots not to repeatedly adding and removing `stale` label.

### Versions and configuration

N/A

**Comment by jeanpaulrsoucy** [comment]
![Simpsons_Monkey_Knife_Fight](https://user-images.githubusercontent.com/31170087/166115419-1e7407ff-9f0c-476c-9cdf-65ef844552a6.jpg)

**Comment by Maleclypse** [comment]
It seems to have stopped.  Is this resolved?
