### ISSUE TITLE
Charcoal Forge furniture dosen't reload coal

### ISSUE THREAD

**Issue by tkulpa** [CleverRaven/Cataclysm-DDA#57216]
### Describe the bug

Placed Charcoal Forge dosen't take coal while reloading it (by 'e'xamine) but you can reload it with coal while holding it as an item

### Steps to reproduce

1. Create **charcoal forge** item
2. Create **coal**
3. Reload **charcoal forge** with **coal**
4. You can craft items that are using **charcoal forge** with charges
5. Open construction menu and use **Place Forge** to place **charcoal forge** as a furniture
6. Create **coal**
7. Try to 'e'xamine standing forge to reload it
8. You can't, it says that you need charcoal to reload this forge

### Expected behavior

There is consistency between item and placed item as a furniture, both should be able to be reloaded with coal (or shouldn't if thats the case)

### Screenshots

![image](https://user-images.githubusercontent.com/18174866/165629702-7fc62b6a-5a17-4520-a248-a20e5b0d71c1.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1645 (21H2)
- Game Version: 0.F-7877-gd6087a2d18 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by RoyBerube** [comment]
Reloading furniture and items use a different code path to determine the available ammo.

Reloading an unplaced charcoal forge in you hands uses Character::list_ammo() which respects the ammo_type flag to look for ammo with that flag.

Reloading a placed forge uses the static function reload_furniture(), which only looks for the default ammo itype_id. It is not using the ammo_type flag. The default ammo itype_id for the forge is charcoal.

Charcoal and coal both have ammo_type as charcoal.

**Comment by RoyBerube** [comment]
I'm about 90% done to finishing a fix for this. Had a few false starts but have settled on a solution that should work nicely.
