### ISSUE TITLE
Butcher shop roof is inconsistent

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#57223]
### Describe the bug

`You may be unable to return back down these stairs.  Continue up?`

### Steps to reproduce

Load the game and climb up the stairs.

### Expected behavior

Not spawning inside a pipe with no way out on the roof.

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.F-7899-g6d87e1bec0-dirty [64-bit]
- Graphics Version: Curses
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

https://tinystash.undef.im/il/jN9aiaFtkjzLEjTquiwTd3sp1igswzGQitwRxUsNdyVcR5UGVcySc33wKuGZVjMbSJopxWynoWtE9CohhxLUj2T

**Comment by PatrikLundell** [comment]
I've encountered a case where a normal looking staircase in what seemed to be an undamaged building displayed that message (or something close enough). I don't know if it was a butcher shop, though, so I don't think it counts as a confirmation.
