### ISSUE TITLE
Game freezes when approaching base and also on river

### ISSUE THREAD

**Issue by snipercup** [CleverRaven/Cataclysm-DDA#57229]
### Describe the bug

First, when loading Yocemento, the game will freeze if you drive the car south towards the evac shelter where my base is. It has 1 NPC

Secondly, when loading Sprague River the game instantly freezes. The caracter is on a boat on a river approaching one of the islands.

In both cases the CPU jumps to 15% or one full core of CPU and the game cannot be interacted with. I've waited over 20 minutes in both saves.

### Steps to reproduce

Load attached save. 

For Yocemento, approach the base in the evac shelter
For Sprague River no further action is needed, the game freezes right away.

### Expected behavior

Approach the base and ride the boat without the game freezing.

### Screenshots

![image](https://user-images.githubusercontent.com/50166150/165821454-ce719865-4af6-48c4-ab95-a7ddf1efd57c.png)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 8.1
- Game Version: 9305a5f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]
]

### Additional context

I looked at #38630 but there the issue was a lot of NPCs and items which isn't the case now.
[Sprague River.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8585429/Sprague.River.zip)
[Yocemento.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8585430/Yocemento.zip)

**Comment by fairyarmadillo** [comment]
I had a crash when updating my save to today's experimental because it loaded in a random car that hadn't been there before on top of my car. This was outside a campground that I'd already explored.

**Comment by andrei8l** [comment]
These are all different issues. The NPC from Yocemento is working through 20 million moves and the real cause of that is likely some other bug that occurred earlier in your save.

@fairyarmadillo please open a separate issue for your crashes.

**Comment by snipercup** [comment]
Thank you for looking into it. I hope #57235 will save my Sprague River game. 
For Yocemento I will load an earlier save and repeat the steps I did before and see if the result is the same.

**Comment by snipercup** [comment]
Welp, my old Yocemento  save is gone so I won't be able to reproduce it anytime soon. So forget about that.
I'll try my Sprague River save again when #57235 is merged and close this issue if it works.

**Comment by snipercup** [comment]
After waiting long enough, I reached the shelter! It seems like the NPC is looking for a tool every tick:
![image](https://user-images.githubusercontent.com/50166150/165999409-b9cbb5b3-c5b7-4ab4-b5c1-621bba969c28.png)

Is this something that can be fixed or is it cause by a bug earlier in the game?
I attached the save file where the screenshot came from. When you move the game freezes for 2 seconds.

![image](https://user-images.githubusercontent.com/50166150/166000312-c451bedd-6707-444f-86f1-96652ff4afe8.png)

I'll cancel the construction blueprints to stop him from looking for tools for now.

**Comment by andrei8l** [comment]
> Edit 2: It stops when I drop a hammer in the camp storage zone

I can't reproduce that. The problem here is that `t_window_empty` lacks the flag `BARRICADABLE_WINDOW` so the construction activity gets stuck in a bizarre loop. The "...is trying to find necessary items..." comes from a poor assumption at `activity_item_handling.cpp:859`

<details>
<summary>patch</summary>

```diff
diff --git a/data/json/furniture_and_terrain/terrain-windows.json b/data/json/furniture_and_terrain/terrain-windows.json
index 52f8d2a519..59a2c01f6b 100644
--- a/data/json/furniture_and_terrain/terrain-windows.json
+++ b/data/json/furniture_and_terrain/terrain-windows.json
@@ -431,7 +431,8 @@
       "THIN_OBSTACLE",
       "SMALL_PASSAGE",
       "PERMEABLE",
-      "WINDOW"
+      "WINDOW",
+      "BARRICADABLE_WINDOW"
     ],
     "bash": {
       "str_min": 10,
```
</details>
This JSON patch fixes the problem here, but this build activity loop needs to be improved in general so it doesn't get stuck like this.
