### ISSUE TITLE
Revived Ferals drop non-filthy clothing.

### ISSUE THREAD

**Issue by Sathra225** [CleverRaven/Cataclysm-DDA#57221]
### Describe the bug

If a feral human variant (and likely non-feral) dies then the revive timer brings them back as a zombie, their clothes are still clean. 

### Steps to reproduce

1. Kill feral human.
2. Wait several hours till they revive as a zombie.
3. Kill said zombie, note non-filthy clothes.

### Expected behavior

That the clothes would be (filthy).

### Versions and configuration

Latest experimental.

### Additional context

I haven't verifed it, but it's possible that when the new zombie evolves their clothing is still clean(-ish). Might be why evolved zombies can sometimes be found with non-filthy clothing.

**Comment by estebandellasilva** [comment]
![image](https://user-images.githubusercontent.com/89189872/165831036-97e87f6d-6438-4d3d-8939-e18a64184ecf.png)
I assume it was one from the Batch i already mentioned on the discord

**Comment by Termineitor244** [comment]
Confirmed with a bunch of mansion ferals.

/confirmed
