### ISSUE TITLE
New Starting Scenario: "Embark"

### ISSUE THREAD

**Issue by Xaritscin** [CleverRaven/Cataclysm-DDA#57238]
### Is your feature request related to a problem? Please describe.

Most if not all the starts are for players wanting a day 1 survival challenge but there's not one dedicated to setting up camp which is one of the big features in the game once you get your needs going.

### Solution you would like.

"Embark" is a homage to Dwarf Fortress and its starting party in Fort Mode. Its a Basecamp construction escenario with the following features:

-7 starting NPCs from which the player has to select one as its main character
-a premade wagon vehicle pulled by livestock
-1 or 2 pets
-enough supplies to set up an initial basecamp on the embark site (or you know, enough to move elsewhere using the wagon)
-locations avaliable to select on start are all designed around wilderness areas

Each of the NPCs has a profession analogue to DF fortress jobs like Expedition Leader, Mason, Carpenter, etc. with their own skillset and proficiencies. The goal is for the player to make use of these resources on day one to start building a base and then maybe start exploring and doing expeditions into other overmap locations.

This assuming the mutated wildlife and evolved zeds dont pose an end to the adventure.

### Describe alternatives you have considered.

just let people discover basecamp content after becoming unstopable mutated/cyborg ubermensch with a top gear deathmobile.

### Additional context

This is an idea i was discussing the other day on discord. putting it here on issues to see if someone wants to pick it up.

**Comment by PatrikLundell** [comment]
This doesn't make that much sense. CDDA and DF are very different games (good luck with a generational "fortress" in CDDA). Part of the challenge of CDDA is to acquire the resources for a base camp (assuming, of course, you're interested in building them).
I believe you can usually recruit the Refugee Center beggars fairly quickly assuming you've managed to recruit the starting NPC. Part of the challenge then is to train them to actually be able to construct a camp.
Also note that a CDDA base camp is "done" in a limited amount of time, so once done you'd have to find something else to do.

**Comment by ZhilkinSerg** [comment]
You can already do that with existing functionality in a mod.
