### ISSUE TITLE
NPCs don't own the contents of their containers

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#57241]
### Describe the bug

NPCs only own the parent container of items that generate on their territory. They don't own the contents themselves. I can walk into the refugee center and swipe the beans inside a can and it isn't registered as theft, but if I then try to take the empty can with me the game will warn me about theft.

### Steps to reproduce

1. warp to a refugee center.
2. engage in a miniscule quantity of larceny
3. Observe NPCs not caring about your foul deeds

### Expected behavior

I imagine this is self explanatory

### Screenshots

![image](https://user-images.githubusercontent.com/56016372/165872534-1cc91085-0af4-416b-ba7a-ac516dcf7eb2.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.613 (21H2)
- Game Version: 97334d5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

I also somehow managed to steal the SPAM inside a container without unsealing it but that's an entirely unrelated issue.

**Comment by Night-Pryanik** [comment]
Related: #50617.
