### ISSUE TITLE
Items that can't be worn directly are shown in the Wear Item menu

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#57240]
### Describe the bug

When using the `W`ear item menu, items that cannot be worn directly such as ESAPI ballistic plates are displayed and selectable in the menu.

### Steps to reproduce

1. Acquire some ESAPI or ESBI ballistic plates, and have them in inventory or on the ground nearby
2. Press `W` to wear items
3. See ballistic plates in the Wear item menu

### Expected behavior

Items that can't be worn directly should not be displayed in the Wear item menu.

### Screenshots

![image](https://user-images.githubusercontent.com/238395/165870600-629949dc-8e11-4f65-ae2b-e0ad92c9e170.png)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-7779-g77235b6773 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Generic Guns [generic_guns],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by andrei8l** [comment]
```diff
diff --git a/src/game_inventory.cpp b/src/game_inventory.cpp
index 6a54bd08dd..5686eb9661 100644
--- a/src/game_inventory.cpp
+++ b/src/game_inventory.cpp
@@ -357,7 +357,8 @@ class wear_inventory_preset: public armor_inventory_preset
 
         bool is_shown( const item_location &loc ) const override {
             return loc->is_armor() && !you.is_worn( *loc ) &&
-                   ( bp != bodypart_id( "bp_null" ) ? loc->covers( bp ) : true );
+                   ( bp != bodypart_id( "bp_null" ) ? loc->covers( bp ) : true ) &&
+                   !loc->has_flag( flag_CANT_WEAR );
         }
 
         std::string get_denial( const item_location &loc ) const override {
```
Not sure that this needs to be fixed though.
