### ISSUE TITLE
Wooden Support Beams for Underground Projects

### ISSUE THREAD

**Issue by Myfharad** [CleverRaven/Cataclysm-DDA#57280]
### Is your feature request related to a problem? Please describe.

Ive always thought of living underground as fun Zombie Apocalypses games,a nd I always try to in CDDA, but when I do dig underground on Experimental usually the grass above caves in, now I heard that you need to use supports to keep it from caving in, and while thats fine because there are metal supports, I dont think they should be limited to only being metal. 

By the time most CDDA players have concrete making and Fabrication 9 I dont believe anyone would be like 
"Yeah imma just go live underground"
since they would be pretty established by then, and usually I find a base to live in early on and stay there.

Now I wanted to build a little underground cellar to live in and realized I need Fabrication 9 to be able to make supports, it kinda really discouraged me.

I believe CDDA has alot of untapped potential for underground projects, and it would help those who want an early jab at the building underground projects.

### Solution you would like.

Maybe an  Wooden Support beam construction? or some other variant that would allow the ground to not cave in one z-level down.

### Describe alternatives you have considered.

Maybe lowering Metal Support Beam's Fabrication Construction Level? 

I don't know

### Additional context

![depositphotos_75768665-stock-photo-long-tunnel-through-gypsum-mine](https://user-images.githubusercontent.com/100801849/166083395-1b22d2e5-cdb0-4a99-9046-1dd114510bac.jpg)
What I envision they would look like
![salt-caves-near-krakow-underground-corridor-with-support-beams-2A29JA5](https://user-images.githubusercontent.com/100801849/166083405-35b96522-bab1-4bb1-b8d2-45979339af11.jpg)

**Comment by ERRORCODE509** [comment]
Any wall that supports a roof is considered a "support" for the sake of holding up the ceiling. Seems odd that we don't have generic supports though.

**Comment by Tairesh** [comment]
The problem with this is CDDA currently doesn't support building something on a floor, we need to create replacing furniture for every floor type like "stone floor with wooden beams" and "dirt floor with wooden beams" and whatsoever.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
