### ISSUE TITLE
Most of Smokes's wares are not present when entering the refugee center at certain rotations

### ISSUE THREAD

**Issue by Ilysen** [CleverRaven/Cataclysm-DDA#57288]
### Describe the bug

When Smokes and his shop are first generated, the utility shelf that holds the faction's unsorted zone is not stocked with its initial stuff if the refugee center is rotated to the north or east. The zone is still there, as unsorted items that Smokes himself generates with are still moved to the shelf; however, none of the other items appear. Restocking over time appears to populate the shelves as normal.

### Steps to reproduce

1. Approach a refugee center rotated in each direction **naturally**; teleporting right up to the doors and walking in appears to prevent this bug, which I imagine is one reason it slipped through.
2. Enter the north and eastern centers (roads going south and west) and see that the shelf is empty.
3. Fast-forward time by one season or another large amount, and trade with Smokes. See the shelf restock.
4. Enter the south and western centers (roads going east and north) and see that the self is stocked as normal.

### Expected behavior

The shop at the refugee center should be stocked correctly on all rotations, and not just two of 'em.

### Screenshots

<details><summary>Smokes's shop at the north rotation, game start. The center was entered by walking down the road from the end of it.</summary>

![cataclysm-tiles_0C3V8DQDy6](https://user-images.githubusercontent.com/47678781/166092307-7eb6e39e-af4d-41bd-bf0e-2934c2c5910a.png)
</details>

<details><summary>Smokes's shop at the north rotation, one season fast forwarded.</summary>

![cataclysm-tiles_qRL9eWlkH3](https://user-images.githubusercontent.com/47678781/166092346-801bac88-19d9-4d10-a6ec-a98939469460.png)
</details>

<details><summary>Smokes's shop at the north rotation, game start. The center was entered by teleporting to the doors and walking in; note that the shelf is stocked when teleporting, but not when walking there yourself.</summary>

![cataclysm-tiles_2bKhSiVoSa](https://user-images.githubusercontent.com/47678781/166092354-b688e28c-15b4-4223-84b1-95f7898fcd2d.png)
</details>

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1645 (21H2)
- Game Version: 0.F-7941-gc5953acae3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    No Rail Stations [No_Rail_Stations],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth]
]

### Additional context

This might be related to #57156.

I imagine that this happens, for whatever reason, because the `LOOT_UNSORTED` zone is on a different overmap tile than the other zones. Manually moving the zone to the same tile as the other ones appears to fix this for the affected rotations, but I have absolutely no idea why it only affects two rotations to begin with >.>

**Comment by andrei8l** [comment]
/confirmed

> because the LOOT_UNSORTED zone is on a different overmap tile than the other zones

No, the zones are fine and definitely on the same overmap tile since #57156, but the unsorted items aren't place for some reason. I'll look into it; thanks.
