### ISSUE TITLE
Removing broken down vehicle tires do not yield any rubber.

### ISSUE THREAD

**Issue by FayFlightee** [CleverRaven/Cataclysm-DDA#57307]
### Describe the bug

What the title said. With the rubber stuff being added in general, this feels like an obvious issue.

### Steps to reproduce

1. Spawn/find vehicles with broken wheels.
2. Remove the wheels. 
3. disappointment.

### Expected behavior

At least it should yield a few rubber chunks. Or rubber tire chunks/strips.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1645 (21H2)
- Game Version: c5953ac [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

**Comment by jeffplata** [comment]
Can confirm. Intentional?
/confirmed

**Comment by FayFlightee** [comment]
> Can confirm. Intentional?

I mean, not sure why broken down tires can't at least yield some chunk of rubber.
