### ISSUE TITLE
Alcohol freezes in a fermenting vat outside during winter

### ISSUE THREAD

**Issue by Benny-Bear** [CleverRaven/Cataclysm-DDA#57300]
### Describe the bug

Making alcohol during winter is impossible if the vat is located outside because it freezes solid.
I haven't seen it go below 4 degrees during winter so far and I don't think alcohol freezes anywhere near that.
Since the batch is done brewing it should be considered alcohol at that point.
![image](https://user-images.githubusercontent.com/29996039/166099110-deed26ea-9fe1-45d3-a698-2d490a4b8540.png)

### Steps to reproduce

Make some wort/wash 
It's cold outside
Brew ya up something to keep you warm
It freezes solid when its done and you are a unhappy winter survivor

### Expected behavior

Alcohol freezes at like -30 or so according to google
This is the worst freeze distillation I've ever seen

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1645 (21H2)
- Game Version: 1fa5cd4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by PatrikLundell** [comment]
Yes, the game doesn't seem to have any logic to change the freezing point of water based solutions depending on what's mixed into it and in what proportions. Salt water also freezes at the fresh water freezing point of 0 Celsius.

While pure alcohol freezes at a rather low temperature, fermentation doesn't bring the alcohol concentration above 20% or so. This means it will freeze at a lower temperature than pure water, but at a considerably higher one than pure alcohol.

**Comment by Hirmuolio** [comment]
Adding `"freezing_point": X` to the moonshine wash json should fix this.

I am not expert on brewing but doesn't fermenting require quite warm temperatures to work?

**Comment by leemuar** [comment]
I guestimate it to be -15C based on @PatrikLundell  comment and item's description (it is not distilled and have solids and contaminants)
