### ISSUE TITLE
Dust mask not having more environmental protection than scarves

### ISSUE THREAD

**Issue by geskeca** [CleverRaven/Cataclysm-DDA#57304]
### Describe the bug

A dust mask has the same environmental protection stat (2), as scarves, with a fur scarf having even more protection than the dust mask (3).

### Steps to reproduce

Get any scarf and compare it to a dust mask

### Expected behavior

From my understanding environmental protection is protection against smoke/dust and airborne illness. It seems wrong to me that a scarf would protect more against these things, and makes it so that the dust mask is useless with the increased mouth encumbrance.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1586 (21H1)
- Game Version: 9305a5f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Termineitor244** [comment]
/Confirmed

But this opens the question of how much should these items protect?... I will see if I can make a pass on some of these objects later.
