### ISSUE TITLE
Debug message when getting to the water dispenser in the tutorial

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#57316]
### Describe the bug

See title.

### Steps to reproduce

1. I bound examine to `s` (nethack-style).
2. I got to the water dispenser.

```
 DEBUG    : Invalid/Missing <keybind>: 'examine'

 FUNCTION : void replace_keybind_tag(std::string&)
 FILE     : src/output.cpp
 LINE     : 1985
 VERSION  : 0.F-7779-g77235b67732
```

3. The next dialogue had "<Unbound locally!>" instead of the expected `s`. Examining works perfectly.

### Expected behavior

No debug message.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.F-7779-g77235b67732 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by NetSysFire** [comment]
Aaaand found another one by getting to the end of the tutorial.

```
 DEBUG    : Invalid/Missing <keybind>: 'save'

 FUNCTION : void replace_keybind_tag(std::string&)
 FILE     : src/output.cpp
 LINE     : 1985
 VERSION  : 0.F-7779-g77235b67732
```

![image](https://user-images.githubusercontent.com/59517351/166129404-22f738b6-2932-4f9b-8d4d-30340121e84d.png)

Save is bound to ctrl+s

**Comment by NetSysFire** [comment]
Probably related to #55230. cc @haveric

**Comment by haveric** [comment]
I've seen some keybind changes come through recently that might have affected these. Either there are some references that need updating or they have exposed issues in my original code. I'll dig into these today and report back.

**Comment by haveric** [comment]
I'm not able to replicate the specific issues you are seeing, but I suspect this has to do with key input type and/or some issue with rebinding keys (local/global difference?) Perhaps @Qrox would be able to assist in debugging this?

**Comment by NetSysFire** [comment]
Do you need anything else, like my keybind config?

**Comment by haveric** [comment]
> Do you need anything else, like my keybind config?

It certainly can't hurt. Also, your options (or specifically whether you are using keycode or symbol input). With those, I can take a closer look later.

**Comment by Qrox** [comment]
The debug message is shown because `is_registered_action` always returns false in `replace_keybind_tag` because no action is actually registered in the input context.

The bindings are probably displayed as `Disabled` because there are keys bound to the action but none is usable in the current context (for example, if the action is bound to keys in the symbol mode, but not in key code mode, and key code mode is currently active), so it might have something to do with your keyboard mode settings.

**Comment by NetSysFire** [comment]
[keybindings.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/8601898/keybindings.txt)

Here are my keybindings. Github does not like the json extension but because its plaintext it does not matter anyways.
Keyboard mode:

```json
"name": "SDL_KEYBOARD_MODE", "value": "keychar"
```

**Comment by Qrox** [comment]
I think I know what's wrong: in the first popup, the action you bound `s` to is `examine_and_pickup`, whereas the popup shows the bindings for `examine` which is unbound. In the second popup, you bound `ctrl+s` to `quicksave` where as `save` is unbound in symbol mode. So the debug message needs to be fixed or removed, but the keybindings are displayed correctly albeit confusingly. Maybe we can make it more clear by refering to all four actions in the popup text.

**Comment by haveric** [comment]
Yeah, I'm ok with the debug message going. Maybe instead we could parse the tutorial in some tests in order to verify the default keys are all set?

**Comment by Qrox** [comment]
That would be nice, but the player may still be confused if they change the keybindings before starting the tutorial.

**Comment by haveric** [comment]
> That would be nice, but the player may still be confused if they change the keybindings before starting the tutorial.

I think combining both of our solutions would be the best path forward then.
- Adding extra actions to the dialogs (examine_and_pickup and quicksave)
- Possibly add new defaults to symbol mode?
- Remove the debug message
- Ideally add some test cases to check against default keys.

**Comment by NetSysFire** [comment]
I am not familiar with what you both are talking about at all, so forgive me if this misses the point.

What about a sort-of fallback mechanic? `examine` and `examine_and_pickup` (or `save` and `quicksave`) both have the same effect for gameplay purposes, so why not add special cases for them? As in if the former is unbound but the latter is not, just use that instead. That would need to be hardcoded or there should be a "equals_to" json property you could assign to these keybinds to define the fallback.

The only problematic thing that would still remain is when both are unbound, potentially a configuration error since examine is pretty essential and used often.

**Comment by NetSysFire** [comment]
Can no longer reproduce. Hooray!
