### ISSUE TITLE
Add the ability to obtain samples from living friendly creatures/NPCs

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#57312]
### Is your feature request related to a problem? Please describe.

Short answer: I don't like the idea of having to kill my pets in order to become more like them.

Long answer: As discussed in the comments of [this issue](https://github.com/CleverRaven/Cataclysm-DDA/issues/56937), there's a realistic possibility of obtaining samples without having to kill the donor; requiring the donor to be dead in all circumstances is unrealistic, and limits RP options for characters experimenting with mutagen.

### Solution you would like.

As mentioned in the comments on the aforementioned issue, there's the idea of being able to ask an NPC who trusts you enough to provide samples. Expanding on this, I feel like samples ought to also be able to be taken from friendly creatures, such as tamed dogs/cats/farm animals, or even friendly dermatiks (I'm imagining a survivor trying to mutate into an insect in order to be a better parent to their dermatik babies).

### Describe alternatives you have considered.

1. Murder
2. Relying entirely on samples taken from killed hostiles/labs

**Comment by fairyarmadillo** [comment]
Maybe the doctor at the refugee center could sell you human samples on the sly if you passed a speech check or did something for him? He's been screening incoming refugees to filter mutants out, it's possible the government could have told him how to get samples for testing, and now they're just on ice.

**Comment by DamienRoyan** [comment]
>He's been screening incoming refugees to filter mutants out

Wait that's a thing!? I thought he just good ol' doctorino
