### ISSUE TITLE
The game appears to randomly create new worlds

### ISSUE THREAD

**Issue by Ilysen** [CleverRaven/Cataclysm-DDA#57349]
### Describe the bug

This is a really strange one. Whenever at least one world is present, entering the main menu will create a new one with the default settings. This happens both when booting the game and when exiting to the main menu from an existing world.

For some insane reason, this only seems to happen on a manually compiled version of the game. Downloading the latest experimental with Catapult causes no such problems.

### Steps to reproduce

1. Start with an empty world list.
2. Create a new world with any settings.
3. Quit the game and reopen.
4. See that a new randomly-generated world has appeared.
5. Enter either of the new worlds with a new character, then save and exit.
6. Another new world has appeared.

### Expected behavior

Worlds should not randomly appear without prompting.

### Screenshots

Step 1: Empty world list.
![image](https://user-images.githubusercontent.com/47678781/166166424-dc7c006a-16d5-4648-ad39-d59a753a89fe.png)

Step 2: I've created a new world using the default settings.
![image](https://user-images.githubusercontent.com/47678781/166166428-72a21600-1eef-4a85-b619-de2dceceb74d.png)

Step 3: I rebooted the game. San Augustine was not a world I created myself; it appeared on its own.
![image](https://user-images.githubusercontent.com/47678781/166166437-1f15919c-d6ac-4017-9e53-c22a4b8da344.png)

Step 4: I created a default character in `test 1`, then saved and quit. Lawrenceville has appeared now, which I also didn't make.
![image](https://user-images.githubusercontent.com/47678781/166166455-61dac1b8-c3ed-4e9b-a8e6-f52d63761817.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1645 (21H2)
- Game Version: 0.F-7993-gc86ae6d53b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    No Rail Stations [No_Rail_Stations],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth]
]

**Comment by Ilysen** [comment]
I have no idea why, but reinstalling the repo from scratch seemed to fix this. I have no idea what might have caused this problem. Rest in peace, all the changes I forgot to stash. ;-;

**Comment by anothersimulacrum** [comment]
> I have no idea why, but reinstalling the repo from scratch seemed to fix this. I have no idea what might have caused this problem. Rest in peace, all the changes I forgot to stash. ;-;

Consider `git clean -xdf` in the future.

**Comment by Ilysen** [comment]
thanks a ton. my git knowledge isn't amazing - it's just enough to do the stuff that I already do. the best lessons are hard-learned, though, and all that.
