### ISSUE TITLE
FILTHY custom-flags doesnt work in palettes

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#57343]
### Describe the bug

When you add `"custom-flags": [ "FILTHY" ]` to item inside the palette, it doesnt work

### Steps to reproduce

1. Open any palette with easily accessible clothes
2.  add `, "custom-flags": [ "FILTHY" ]` on the end of the item, for example, 
`"W": [ { "item": "allclothes", "chance": 60, "custom-flags": [ "FILTHY" ] } ]`
3. open the game
4. find nothing changed, and the items are not filthy

### Expected behavior

Naturally generated filthy clothes

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1586 (21H2)
- Game Version: 8206614 [32-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Night-Pryanik** [comment]
`custom-flags` works only for specific item, not for item groups.

**Comment by GuardianDll** [comment]
So there is no way to add such function? I don't really want to make another loot group just to add flag

**Comment by Night-Pryanik** [comment]
Unfortunately, there isn't.

**Comment by Maleclypse** [comment]
Please reopen as a feature request, if desired.
