### ISSUE TITLE
Sporogenesis mutation gives infinite calories

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#57346]
### Describe the bug

Mycus characters get the Mycus Sporogenesis mutation, an activatable ability that produces fungal spores on command. It is supposed to cost 69 calories and thirst, but for some reason the thirst it creates goes away almost immediately, and instead of deducting calories from the player, it adds them. This means the mutation is infinitely spammable and gives you free food.

### Steps to reproduce

Make a character, add mycus, mycus identity, and mycus sporogenesis mutations.
Check calorie totals.
Use sporogenesis via the [ menu. You can infinitely spam it by pausing for a couple turns after it says using it more will kill you.
Check calorie totals.
Pause a few turns and note that any level of thirst vanishes in seconds.
Keep doing it and get super fat.

### Expected behavior

Sporogenesis should cost calories, not add them, as food is the way the Mycus motivates its guides and spores shouldn't violate conservation of matter.

Sporogenesis should probably not cost thirst, as Mycus Feeder makes the player immune to thirst anyway.

The ability probably shouldn't be infinitely spammable

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1645 (21H1)
- Game Version: d2cecff [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Fris0uman** [comment]
Likely caused by #56728 that accidently flipped the sign of calorie consumption for mutation. I'm fixing it right now.
