### ISSUE TITLE
Mercenary Coat requires the exact US Ballistic Vest

### ISSUE THREAD

**Issue by sonphantrung** [CleverRaven/Cataclysm-DDA#57352]
### Describe the bug

Despite having the same stats as US Ballistic Vest, themed US ballistic vests doesn't satisfy Mercenary Coat recipes requirement

### Steps to reproduce

Ballistic vests from SWAT zombie, zombie cop, National Guard Ballistic Vest doesn't satisfy the requirement but the vest with the exact US Ballistic Vest name

### Expected behavior

It should also support themed ballistic vests

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1645 (21H2)
- Game Version: c86ae6d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by bombasticSlacks** [comment]
The SWAT vests should work. The other ones have different coverage (they aren't as long) so it wouldn't make sense.

**Comment by Maleclypse** [comment]
Please comment to reopen if the SWAT vest doesn't work.
