### ISSUE TITLE
add line of buttons that are available most common actions at least in tile version of game

### ISSUE THREAD

**Issue by drjoms** [CleverRaven/Cataclysm-DDA#57356]
### Is your feature request related to a problem? Please describe.

remembering 20+ shortcuts is unreasonable. Not only that, its relatively hard to get a function that you need right there right then.
And to make things worse, if I don't play game for a few weeks, and come back to it - I WILL forget shortcuts.

### Solution you would like.

Please add line of buttons at the bottom where you can see name of button, like eat/drink/sleep.
Would be nice if list was dynamic. You come to door, now there is new button becomes available, open/close door.

Also, when you hover mouse over it, there should be small pop up, that says keyboard shortcut.

### Describe alternatives you have considered.

right click on item may/should give whole list of things you can do with object.

**Comment by Night-Pryanik** [comment]
Press Enter, and you'll get a comprehensive list of most actions you can do in the game, without the need to remembering shortcuts.

**Comment by drjoms** [comment]
> Press Enter, and you'll get a comprehensive list of most actions you can do in the game, without the need to remembering shortcuts.

Thats:
1. extra action user needs to take that does not really benefit user.
2. no it doesn't.

I stay next to baseball bat. I need to put in my hands. I hit enter. There is NOTHING about "w" button immedeatelly.

That means I need to go into SUB menu, so it's a SECOND menu that I don't need.
Only THEN i can see 'w' for wield.
Instead I could have an option on button of my screen that:
1. Says 'Wield'
2. And upon hovering over it - I could have "w", as reminder of shortcut.

Or no hovering. Both command AND shortcut in same button.

To make things worse, If I have 2 layers of shortcuts for simple action, user starts getting confused.
And while we are at it, why not make right click on the thing to pop up with list of actions that can be performed on the item.

**Comment by Zireael07** [comment]
Right click etc are only available in tiles build. Remember that cataclysm is also available as curses.

**Comment by Night-Pryanik** [comment]
> why not make right click on the thing to pop up with list of actions that can be performed on the item.

I'm not against it, you're welcome to implement it.

**Comment by BrettDong** [comment]
The majority of Roguelike games, including NetHack and Angband, are “unreasonable” by your standard.

**Comment by drjoms** [comment]
> Right click etc are only available in tiles build. Remember that cataclysm is also available as curses.

Which is fine with me, please implement feature in Tiles mode/build.

**Comment by drjoms** [comment]
> The majority of Roguelike games, including NetHack and Angband, are “unreasonable” by your standard.

We can cling to a bad interface that was dictated by limitations of platform from 20+ years ago, OR we can use something that is:
1. Modern and does same thing but more intuitively AND faster. I am at least one user who has issues with interface. But... Don't consider me. Make a poll, ask end users.
2. Appeal to bigger crowd who love game but hate remembering 50+ shortcuts.(or is it 100+ ?)
3. Appeal to crowd who don't want to **RE-LEARN** shortcuts for game they played a month+ ago.
4. Make people who already left game for that exact reason to reconsider and come back.

I have seen a few youtube videos of game where people who played the game were struggling with controls, asking people in their chat to help with shortcuts, etc.
If I am forced to look in wiki how to paint a wall in game where its an option and my char has both paint AND brush(and you can't find it!) - you know that interface/controls are a problem.
This gives very sour taste. Game has potential, but its one of stumbling blocks for sure.

**Comment by ZhilkinSerg** [comment]
There is nearly zero interest in bringing in bigger crowd, but one can work on enhancing interface without compromising UI consistency between Tiles and Curses builds - e.g. you can start from bringing on-screen shortcuts from Android to desktop versions.

**Comment by Zireael07** [comment]
Actually I believe on-screen shortcuts could be done in curses, too (devote a line to them at the bottom and list them with an accompanying keybind since you can't use the mouse in curses)
