### ISSUE TITLE
Cannot move around placed foot locker recharging station

### ISSUE THREAD

**Issue by FayFlightee** [CleverRaven/Cataclysm-DDA#57364]
### Describe the bug

When you grab and try to drag the foot locker recharging station to relocate it, it got stuck on... nothingness. Literally nothing.

### Steps to reproduce

1. Place down a foot locker recharging station through "place recharging station" in construction menu. It doesn't even need to be plugged.
2. Grab it.
3. Try to drag it around.

### Expected behavior

Should've followed you around like when you grab a shopping cart.

### Screenshots

![image](https://user-images.githubusercontent.com/71143790/166250249-1b901c0d-3ece-4b1f-a23e-4c602e10d57e.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1645 (21H2)
- Game Version: c5953ac [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by RoyBerube** [comment]
Problem confirmed. Freshly placed with no items inside it cannot be grabbed and moved.
