### ISSUE TITLE
Crash when openning the game

### ISSUE THREAD

**Issue by Endertron51** [CleverRaven/Cataclysm-DDA#57374]
### Describe the bug

For the past two builds my game crash when I click launch game

### Steps to reproduce

Click on launch game

### Expected behavior

The game open

### Versions and configuration

OS: Windows 7, 64-bit
Branch: Experimental
Version: dd1c695 (tiles)
Build: 2022-05-02-2115
Ingame language: English

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8606402/crash.log)

**Comment by harakka** [comment]
Tested with all 4 Windows releases (https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-05-02-2115) and couldn't reproduce. Game starts and new game loads with Play Now.
Win10 Pro build 19043.1645

**Comment by Endertron51** [comment]
Thanks to the CDDA discord I discovered this is a problem that may happen because of the launcher that I use (CDDA Game Launcher) due to compiler related things, opening the game directly solved this.
