### ISSUE TITLE
I hope there will be children.

### ISSUE THREAD

**Issue by 337722** [CleverRaven/Cataclysm-DDA#57376]
### Is your feature request related to a problem? Please describe.

I hope children can appear. I remember that the basement of the refugee center was originally intended to be a place for children.

### Solution you would like.

Add children NPC in the game.

**Comment by Qrox** [comment]
There has been some discussion on it in #52151.

**Comment by KittyTac** [comment]
Devs said no to on-screen child NPCs.

**Comment by I-am-Erk** [comment]
> Devs said no to on-screen child NPCs.

No we didn't? I'm planning on adding them when I get to the refugee center basement. They'll be set up in such a way that people who don't want to engage with that content can easily turn them off without any consequences besides the occasional bit of dialogue where someone talks about kids that aren't there.

This isn't really an issue though.
