### ISSUE TITLE
Option for view to follow Aiming reticle when firing weapons.

### ISSUE THREAD

**Issue by liminalRoar** [CleverRaven/Cataclysm-DDA#57378]
### Is your feature request related to a problem? Please describe.

Firing weapons on mobile can be a bit of a pain with the smaller scree. Even when zoomed out, you cannot see where you are aiming unless it is short range.

### Solution you would like.

An option for the camera to follow the reticle while aiming is the best solution i can think of. Had wanted this before, and saw someone mention it recently without the "for mobile" context and remembered how handy it really would be.

### Describe alternatives you have considered.

When aiming, move the camera to the midpoint between the players and firing reticles positions or some more advanced optimal location. Would take some more work, but likely would look nicer.

**Comment by fairyarmadillo** [comment]
This would also help fix the visual confusion that occurs when aiming up and down Z levels.

**Comment by PatrikLundell** [comment]
Yes, it's a pain when you're trying to aim at something that moves quickly towards you, but you can't see it because the enemy is off vertically (as I have a screen that provides much more space horizontally). Zooming out ought to work, though.

**Comment by liminalRoar** [comment]
Zooming does work, i actually just discovered you can use the "v" key to toggle between aiming and moving the camera. it works pretty well. I still think an option for "camera follows aim" could be useful.

**Comment by catdach** [comment]
Have y'all tried this option under "interface"?:
![image](https://user-images.githubusercontent.com/93795131/166506042-204e7de6-8b73-40ad-9392-28abea960948.png)

**Comment by liminalRoar** [comment]
Oh wow, i thought that was just an auto target, but yeah that is it.. welp. thanks!

**Comment by catdach** [comment]
AFAIK default options are a bit of a thorny problem. People are so radically different and have such radically different circumstances that it's almost impossible to say anything concreate about what "_most people_" would prefer. like, I prefer the option to be off because I play on pc and it can be really annoying to have the camera jumping around from the target, back to the player, back to the target, back to the player, over and over after every shot. That's just me, I'm no authority on what the default options are (or should be), but Imagine that it's a very difficult and nuanced issue.

**Comment by PatrikLundell** [comment]
Thanks for bringing the option to our attention. I'll try it out when I get into a fight and determine whether I want to leave it on or not...

**Comment by liminalRoar** [comment]
that makes sense about not wanting it on PC. i wonder if it is possible to have it set to default on mobile only. Either way, i know about the setting now so im glad to have found that. thanks again!

**Comment by fairyarmadillo** [comment]
I never knew that option existed, thanks!

The default options are silly. The game starts with sepia for remembered areas and no brand names on guns. smh damn
