### ISSUE TITLE
Repeated instances of monster position conflict.

### ISSUE THREAD

**Issue by Ilurker** [CleverRaven/Cataclysm-DDA#57394]
### Describe the bug

When passing through generally the same area, a spammy error notifying a failure to move various creatures into a location which already has a small slime present. There are also various other invalid movement-related errors on display, such as zombies improperly attempting to move into tiles occupied by impassable scenery. The areas where the bug is observed are roughly proximal, though on a different Z-level, to a subway system.

No instability has been noted and no abnormal in-game behaviour has been observed.

Backtrace emission took 0 seconds.
(continued from above) ERROR : src/creature_tracker.cpp:127 [bool Creature_tracker::update_pos(const monster&, const tripoint&)] update_zombie_pos: wanted to move the flying polyp to 8,76,-4, but new location already has the small slime
14:45:40.020 ERROR : (error message will follow backtrace)
  #0
    (dbghelp: @0x6b5b96[cataclysm-tiles.exe+0x2b5b96]), 
    (libbacktrace: debug_write_backtrace(std::ostream&)+0x56@0x6b5b96),
    (libbacktrace: 0x6b5b96    [unknown src]:0    [unknown func]),
  #1
    (dbghelp: @0x6b69f6[cataclysm-tiles.exe+0x2b69f6]), 
    (libbacktrace: DebugLog(DebugLevel, DebugClass)+0x2c6@0x6b69f6),
    (libbacktrace: 0x6b69f6    [unknown src]:0    [unknown func]),
  #2
    (dbghelp: @0x6baff0[cataclysm-tiles.exe+0x2baff0]), 
    (libbacktrace: realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x50@0x6baff0),
    (libbacktrace: 0x6baff0    [unknown src]:0    [unknown func]),
  #3
    (dbghelp: FT_Set_Named_Instance+0x217c9@0x1531d29[cataclysm-tiles.exe+0x1131d29]), 
    (libbacktrace: void realDebugmsg<>(char const*, char const*, char const*, char const*)+0x239@0x1531d29),
    (libbacktrace: 0x1531d29    [unknown src]:0    [unknown func]),
  #4
    (dbghelp: @0x6d6ce1[cataclysm-tiles.exe+0x2d6ce1]), 
    (libbacktrace: debug_menu::debug()+0x65c1@0x6d6ce1),
    (libbacktrace: 0x6d6ce1    [unknown src]:0    [unknown func]),
  #5
    (dbghelp: @0x84fbea[cataclysm-tiles.exe+0x44fbea]), 
    (libbacktrace: game::handle_action()+0xfda@0x84fbea),
    (libbacktrace: 0x84fbea    [unknown src]:0    [unknown func]),
  #6
    (dbghelp: @0x7ffd1b[cataclysm-tiles.exe+0x3ffd1b]), 
    (libbacktrace: game::do_turn()+0xe6b@0x7ffd1b),
    (libbacktrace: 0x7ffd1b    [unknown src]:0    [unknown func]),
  #7
    (dbghelp: FT_Set_Named_Instance+0x7393f9@0x1c49959[cataclysm-tiles.exe+0x1849959]), 
    (libbacktrace: main+0x11c9@0x1c49959),
    (libbacktrace: 0x1c49959    [unknown src]:0    [unknown func]),
  #8
    (dbghelp: @0x4013bd[cataclysm-tiles.exe+0x13bd]), 
    (libbacktrace: _tmainCRTStartup+0x23d@0x4013bd),
    (libbacktrace: 0x4013bd    ../gcc-5.5.0.build_/mingw-w64-v6.0.0/mingw-w64-crt/crt/crtexe.c:341    __tmainCRTStartup),
  #9
    (dbghelp: @0x4014cb[cataclysm-tiles.exe+0x14cb]), 
    (libbacktrace: WinMainCRTStartup+0x1b@0x4014cb),
    (libbacktrace: 0x4014cb    ../gcc-5.5.0.build_/mingw-w64-v6.0.0/mingw-w64-crt/crt/crtexe.c:197    WinMainCRTStartup),
  #10
    (dbghelp: BaseThreadInitThunk+0x14@0x7ffe15197034[KERNEL32.DLL+0x17034]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #11
    (dbghelp: RtlUserThreadStart+0x21@0x7ffe15b22651[ntdll.dll+0x52651]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),

### Steps to reproduce

1. Walk around aimlessly
2. Observe errors

### Expected behavior

Presumably, the zombies stick to their own area and respect one another's personal space

### Versions and configuration

0.F Stable
No NPC Needs mod
Ultica tileset
Otopack sound pack
CDDA Game Launcher installation on Windows 10 Pro

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8614326/debug.log)

**Comment by PhiloTFarnsworth** [comment]
Here's some of the same behavior observed across two saves in the experimental [eb07c6a](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-05-04-0359) release.  This behavior was observed in the Mall in both saves.

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8627314/debug.log)

**Comment by psuedolet** [comment]
Potentially a duplicate of  #46733

**Comment by Ilurker** [comment]
I believe I found the cause of this - when venturing into the lower levels of the lab underneath the location in which the error occured, I found a grouping of dozens of active small slimes and the remains of many others around high level enemies, such as flaming eyes and polyps. I believe the splitting mechanic combined with the high slime density results in the game not having a location to place down the new creatures, or perhaps that the sheer volume of turn to turn pathing produces abnormal behaviour.
