### ISSUE TITLE
Make stealing from refugee center (and other NPC owned areas) harder

### ISSUE THREAD

**Issue by 321nick** [CleverRaven/Cataclysm-DDA#57396]
### Is your feature request related to a problem? Please describe.

using basic knowledge of game mechanics, stealing from a refugee center isnt really hard or a risk in any sense. Just grab and move a couple of lockers to block LOS, and pick up items. 

### Solution you would like.

1) have a Refugee NPC always follow and stay adjacent to the player for the duration of their stay in the center. They can have the option to swap positions unlike other NPCS, so they dont get the player stuck anywhere

2) Grabbing furniture should prompt the NPC to ask the player to release it, and if they refuse, become hostile.

3) When leaving or entering the center, the NPC should search the player for any stolen items owned by the free merchants. 

### Describe alternatives you have considered.

idk any alternatives.

### Additional context

idk any additional context.

**Comment by Night-Pryanik** [comment]
Related: #27467.

**Comment by PatrikLundell** [comment]
Forbidding the dragging of furniture is risky: It's possible to be stuck in the back bay by blocking NPCs drawn to the area by the fighting, with the only way out being to move some of the furniture to create a passage (it might work to smash the furniture, and it might work to shout to cause the blocking bugger to move to investigate).
