### ISSUE TITLE
Can't put on leg splint

### ISSUE THREAD

**Issue by Boonlike** [CleverRaven/Cataclysm-DDA#57393]
### Describe the bug

My right leg is broken. When I make a leg splint and try to put it on, it give me the message "You don't have any broken limbs this could help." the splint turns into "leg splint (left)", and it won't let me change sides for the splint since I'm not wearing it.

### Steps to reproduce

1. Break your right leg.
2. Make a leg splint.
3. Try to wear it

### Expected behavior

I expect to be able to splint my broken leg. Either by it auto selecting the correct leg, letting me manually select the leg, or let me put splints on limbs even if they're not broken so I can change sides that way.

### Screenshots

![image](https://user-images.githubusercontent.com/84247285/166561982-d38f916d-23e8-40d7-9b1c-b7a49165f8ec.png)

![image](https://user-images.githubusercontent.com/84247285/166562043-4a008370-ce45-4f24-b757-aff70550a004.png)

![image](https://user-images.githubusercontent.com/84247285/166562148-19f20c01-2078-4f71-a946-9a3638f97145.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1645 (21H2)
- Game Version: 5fd4bfe [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    Alternative Map Key [alt_map_key],
    Stats Through Skills [StatsThroughSkills]

**Comment by Boonlike** [comment]
I should add that this isn't my first broken leg this run. I can't remember if it was my right or left leg that was broken the first time. I don't know if that could have an effect on this issue.

**Comment by Wyghab** [comment]
I documented this issue #56721. Right side limbs cannot benefit from splints unless you break both sides and apply two splints. This is because the splints are assigned to left side by a function that tries to select the correct side based on rigid armor, before an additional check if they can actually wear it.

**Comment by Boonlike** [comment]
Ah, ok. I took a quick look and didn't see the issue open already, thought it might be a new bug.

**Comment by Boonlike** [comment]
Duplicate issue to #56721
