### ISSUE TITLE
Repeat last action

### ISSUE THREAD

**Issue by FunnyMan3595** [CleverRaven/Cataclysm-DDA#574]
It's possible to repeat the last crafting recipe, but it would be extremely useful to be able to repeat other tasks, like attempting repair with a needle and thread.  A single repair operation could have a keystroke like a!r.  While item key reassignment can make this a less awkward operation, a simple (for the user) "repeat" command would be a lot nicer.

**Comment by Oskar636** [comment]
Maybe we can even assign it to " - " as we won't have a need to have 2 seperate keys to repeat the last action

**Comment by illi-kun** [comment]
Discussed in details in linked issues.
