### ISSUE TITLE
Resuming a item you are crafting makes it disappear 

### ISSUE THREAD

**Issue by Myfharad** [CleverRaven/Cataclysm-DDA#57405]
### Describe the bug

If you "Activate" a "In Progress" craft in your inventory/equipped the item will disappear 

### Steps to reproduce

1. Have an in progress craft in your inv
2. "Activate" it without or without equipping it 
3. Item disappears

### Expected behavior

I expect it to auto equip the craft and continue the craft

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1645 (21H2)
- Game Version: 8c4fc2a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by andrei8l** [comment]
Can't reproduce. I have an in-progress craft in inventory:
![Screenshot from 2022-05-04 12-39-59](https://user-images.githubusercontent.com/68240139/166658198-e39d21ee-1da4-45aa-a896-f9394a56dad0.png)
and 'a'ctivating it makes my character wield it and start working on it:
![Screenshot from 2022-05-04 12-40-18](https://user-images.githubusercontent.com/68240139/166658298-43644d5c-6013-453e-b79d-95d9809ea19b.png)
Same result if I examine the item first and choose activate.

Please provide a save file where this happens

**Comment by Myfharad** [comment]
> Can't reproduce. I have an in-progress craft in inventory: ![Screenshot from 2022-05-04 12-39-59](https://user-images.githubusercontent.com/68240139/166658198-e39d21ee-1da4-45aa-a896-f9394a56dad0.png) and 'a'ctivating it makes my character wield it and start working on it: ![Screenshot from 2022-05-04 12-40-18](https://user-images.githubusercontent.com/68240139/166658298-43644d5c-6013-453e-b79d-95d9809ea19b.png) Same result if I examine the item first and choose activate.
> 
> Please provide a save file where this happens

https://drive.google.com/file/d/1hzi0KjRqhwchDmSYVQEXiGKyTY1IklGX/view?usp=sharing

It happened once before and thought it was a bug, but the Wakazashi I was crafting disappears everytime I try to finish it. I tried crafting something else but it wont replicate now ):< 

I don't know if it has something to do with the forge since the item before that disappear was "a pair of flatjaw tongs" and now the wakizashi I was crafting.

maybe im overlooking something completely obvious but it felt like a bug to me

**Comment by andrei8l** [comment]
/confirmed

The craft has a batch size of 0. Not sure how that happened
