### ISSUE TITLE
Substantial lag in rain (probably wetness+coverage code bottleneck)

### ISSUE THREAD

**Issue by dissociativity** [CleverRaven/Cataclysm-DDA#57404]
### Describe the bug

While it's raining, even if animations are turned off it seems to lag heavily, then the game performs great, I'm using an 8 core i7 10875h that can clock up to 5.1ghz on a single core, so single threaded performance isn't a problem here.

If I would guess this is something to do with wetness calculation code, this is to say that additive wetness probably should not be calculated all at once every single turn, there's no real benefit to doing this in neither realism nor gameplay, though the code itself shouldn't make the game crawl to a near-halt on a fairly decent cpu even as is imo.

The game in theory is lagging due to wetness being re-calculated for every single body part, every turn with coverage and breathe-ability in mind (the sweating code may be related possibly, though my character was cold)

**This does not happen when the player is sheltered from the rain**

### Steps to reproduce

Rain starts
Get wet
Lag
Rain stops
game peforms buttery smooth even though character is still damp in various body parts

### Expected behavior

Game runs consistently between weather types

### Versions and configuration

Cataclysm DDA version eb07c6a
Windows 10 x64
x64 tiles version
using brownlikebears tileset

**Comment by dissociativity** [comment]
to be clear, turning animations on or off makes zero difference here, so my hypothesis must be close

**Comment by Maleclypse** [comment]
Could you attach a save file where it is doing so?   I was unable to replicate on a clean install and I'm wondering if there may be other variables I was unable to account for.  Thanks!

**Comment by taatu** [comment]
I also experienced this, with the lag ending immediately upon the end of the rain, and starting again when the rain started again. However upon saving and reloading, the lag did not repeat even after the rain stopped and later started again. The  game had already been loaded for about 6 in-game hours with lots of driving around. Couldn't get it to happen again afterwards.

version b9c5366
Linux Mint 20.1

**Comment by anothersimulacrum** [comment]
It's impossible to tell what the bottleneck is without profiling. I'd advise against making guesses, because it just wastes time.
