### ISSUE TITLE
FLAGS support for map extras

### ISSUE THREAD

**Issue by LyleSY** [CleverRaven/Cataclysm-DDA#57414]
### Is your feature request related to a problem? Please describe.

Currently there is no way to manage map extras across mods. This issue popped working on #57410 where a DinoMod map extra should be blocked by Innawood and probably Dark Days of the Dead too, but that's not possible.

### Solution you would like.

FLAGS support for Map Extras

### Describe alternatives you have considered.

Patch mods for every variant of every mod and each combination

### Additional context

Thanks to @Light-Wave and @anothersimulacrum for helping me think this through

**Comment by Light-Wave** [comment]
Copying my notes over here
Loading of map_extras seems to happen in map_extras.cpp, function load( const JsonObject &jo, const std::string & ), line 2972.
Meanwhile, checking of blacklists and whitelists seem to happen in overmap.cpp, fuction populate(), line 2824.
Presumably, we would want to grab the code from overmap.cpp and run it in map_extras.cpp. But we also need to make sure it is run after all blacklists and whitelists are finished loading.

**Comment by Light-Wave** [comment]
Another alternative would be to look into issue [#48589](https://github.com/CleverRaven/Cataclysm-DDA/issues/48589), Conditional object loading based on user's installed mods.
