### ISSUE TITLE
Humvees (and most other heavy duty vehicles) weigh far too much compared to their real life counterparts

### ISSUE THREAD

**Issue by Wyrdean** [CleverRaven/Cataclysm-DDA#57411]
### Is your feature request related to a problem? Please describe.

In cdda, humvees weigh roughly 11,000kg, while irl they weigh roughly 3,856 kg at max gross weight. (2,676 kg max curb weight)

### Solution you would like.

Reduce the weight of heavy-duty frames by roughly 3x-4x

### Describe alternatives you have considered.

Replace the frames the humvee uses with those of another material

**Comment by Drew4484** [comment]
Vehicle weights are all off when compared to a RL equivalent since we don't have all the same parts and components. However the closer we can get to RL the better for this case. What does the weight look like with standard steel frames?

**Comment by Wyrdean** [comment]
Using steel frames instead, it would be 2400 kg lighter

**Comment by Drew4484** [comment]
> Using steel frames instead, it would be 2400 kg lighter

That's a step in the right direction, in general the Humvee might be overbuilt with heavy duty parts as IRL they aren't *that* tough. So if swapping the frames/boards plus trading in the military composite armor, gets it closer to the IRL weight that seems like a reasonable change.
