### ISSUE TITLE
nested mapgen error when NPC comes back from creating basic farm plot mission

### ISSUE THREAD

**Issue by snipercup** [CleverRaven/Cataclysm-DDA#57418]
### Describe the bug

When recalling the NPC from the create farm plot expansion, this error shows up:
![image](https://user-images.githubusercontent.com/50166150/166749404-e03ee75f-78cb-42a8-88cc-38a7965d931a.png)

### Steps to reproduce

- Load the attached save
- Interact with the billboard on the tile southeast of the player
- Recall the NPC from the farm basic plots mission (which I made one maptile to the north)
- Observe error

[Yocemento.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8624904/Yocemento.zip)

### Expected behavior

Create the basic farm plot without throwing the error

### Screenshots

This is the mission the NPC is recalled from:
![image](https://user-images.githubusercontent.com/50166150/166750429-c75ddb94-5acb-40d7-bd19-ea7f0d509a42.png)

After ignoring the error, the farm plots seem to be created at least:
![image](https://user-images.githubusercontent.com/50166150/166755531-0daed5e2-683a-402c-9675-4dc85f7def9a.png)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: f97c81e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]
]

### Additional context

The error in text form:
```
DEBUG    : In nested mapgen bc_prim_farm_long_fields in update mapgen faction_base_field_camp_farm_1 on faction_base_farm_0, setting terrain to t_dirtmound (from t_dirt) at (4,4) when item ash existed.  Resolve this either by removing the terrain from this mapgen, adding suitable removal commands to the mapgen, or by adding a suitable flag to the innermost mapgen: either ERASE_ALL_BEFORE_PLACING_TERRAIN if you wish terrain to replace everything previously on the tile or ALLOW_TERRAIN_UNDER_OTHER_DATA if you wish the other items to be preserved

 FUNCTION : virtual void jmapgen_terrain::apply(const mapgendata&, const jmapgen_int&, const jmapgen_int&, const string&) const
 FILE     : src/mapgen.cpp
 LINE     : 2604
 VERSION  : f97c81e
```

**Comment by PatrikLundell** [comment]
The error is harmless in itself. It basically says that the definition should be updated to use relatively newly introduced flags (in this case the one that preserves items).
