### ISSUE TITLE
Arms or Legs Cannot Be Replaced via CBM Enchantments

### ISSUE THREAD

**Issue by EmmjayXII** [CleverRaven/Cataclysm-DDA#57425]
### Describe the bug

After replacing a player character's arms or legs via an enchantment (e.g. a CBM enchantment effect) by adding a new limb and removing the old limb, the game throws out an error message, saying, e.g., "could not find bodypart leg_r in [character's] body").

For legs, in particular, replacing a character's human legs via CBM appears to force them prone, regardless of whether they have replacement legs.

### Steps to reproduce

1. Create a test limb and CBM that replaces an arm or leg with that test limb. 
2. Create a new character and give the character the debug bionic installation mutation.
3. Spawn a copy of the limb replacement CBM.
4. Install the limb replacement CBM.
5. For legs, attempt to replace both a character's legs, then move once. 

### Expected behavior

I expected that the limb would be replaced with the substitute limb, which would function as a full replacement of the original limb.

### Screenshots

![CDDA Bug](https://user-images.githubusercontent.com/104940981/166825431-1b35c2ab-6a49-4117-914f-fbbbf2633905.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.613 (21H2)
- Game Version: 6cb173c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Expanded Bionics [Expanded_Bionics]
]

**Comment by KorGgenT** [comment]
Character::get_working_leg_count() checks for bodypart ids, instead of general limbs. i'll try to look into it but please don't wait for me if anyone else wants to fix it.

**Comment by anoobindisguise** [comment]
this can be closed now. prosthetics and other limb additions have made it no longer true.

**Comment by Night-Pryanik** [comment]
Closing per @anoobindisguise's reply.
