### ISSUE TITLE
Game doesn't print message about ranged weapon sounds

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#57437]
### Describe the bug

Firing a noisy ranged weapon should be accompanied by message in the log, according to the `item::gun_noise` in `ranged.cpp`, which has a variety of sounds for different types of weapons:

https://github.com/CleverRaven/Cataclysm-DDA/blob/c2e3aafc7a13e2059e4a23142dfc89b8b8e72923/src/ranged.cpp#L1928-L1982

Despite that, no messages appear in the log.

### Steps to reproduce

- Get yourself a crossbow and a bolt.
- Fire crossbow.
- Observe no message in the log.

### Expected behavior

Messages appear in the log when firing from weapons.

### Screenshots

![изображение](https://user-images.githubusercontent.com/11132525/166887467-58e4356d-6e62-43bc-ae43-3c8a03da0c94.png)

I fired from V29 laser pistol. Since it has the `LASER` flag, according to the code, the sound should be `Fzzt!`. No message appear at all.

### Versions and configuration

- Windows 10 x64;
- 0.F-8087;
- Tiles;
- Default mods only.

**Comment by FayFlightee** [comment]
Damn, so they are supposed to have noise?

**Comment by Night-Pryanik** [comment]
Yep. They actually produce noise, but no sound messages.

**Comment by toweroglass** [comment]
> Damn, so they are supposed to have noise?

bashing zombies makes noise too. just not a lot. you might alert zombies within 5 tiles, but it won't alert a horde the way a gun shot will.

**Comment by stubkan** [comment]
I noticed during my testing that when I am deafened I can hear bullets hitting things around me, but when my sound returns, I lose that ability.....   

very odd

**Comment by Zireael07** [comment]
Probably a case of inverted logic somewhere then
