### ISSUE TITLE
Add explanation for variable types and context in EFFECT_ON_CONDITION.md

### ISSUE THREAD

**Issue by onura46** [CleverRaven/Cataclysm-DDA#57434]
### Describe the bug

This came from a conversation with maleclypse, who pointed out that explanations for type and context weren't in the markdown. Though they do get brief mentions in NPCs.md, it's never explained whether they're arbitrary or defined somewhere.

### Steps to reproduce

N/A

### Expected behavior

N/A

### Screenshots

![EOC](https://user-images.githubusercontent.com/67405765/166855894-64da5f9f-442a-4105-87b9-0aba3795c358.PNG)

### Versions and configuration

OS: Windows 10
Game Version: x64 MSVC latest experimental
Graphics: Tiles
Language: English (US)
Mods: dda, blazeindustries, package_bionic_professions, no_fungi, no_npc_food, StatsThroughSkills, stats_through_kills, speedydex, extra_mut_scens, crazy_cataclysm, no_fungal_growth

**Comment by I-am-Erk** [comment]
#57454 addresses some of this, keep an eye and see if it sufficiently answers your questions

**Comment by onura46** [comment]
Yeah, the new documentation is very thorough! I'll keep an eye on it going into the future, but it definitely covers the original issue here.
