### ISSUE TITLE
Cranberry radio transmitter quest too harsh and meta game dependent

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#57436]
### Is your feature request related to a problem? Please describe.

Should this be a bug report instead?

The Hub01/Cranberry radio transmitter mission is rather problematic because:
- Any mission where an NPC latches onto you is a problem, since you're stuck with them until the mission is completed.
- The enemy encountered basically demands a specific type of protective measures. If you don't have it, it will probably take weeks of full time work to manufacture it.
- A property of the enemy makes it almost certain that things go out of hand before you understand what's happening.

### Solution you would like.

- Any mission that has an NPC latch onto you ought to have the option to postpone the mission and unlatch the NPC so that the PC can return later after preparing for what's detected or the NPC has revealed after the mission has been accepted.
- Tune down the rate of explosive difficulty expansion of the gotcha.

### Describe alternatives you have considered.

I save scummed about 5 times before figuring out what was going on and managing to deal with it without protection by using the environment and ranged weapons (that had a poor hit chance against most enemies). However, that's not how the game is supposed to be played.

Retreat and spend the next few weeks crafting and then return to see if the guesses are correct, while hobbled by an NPC that doesn't know how to run (none of them do) until the quest is done or the NPC dies because it doesn't know how to run.

**Comment by andrei8l** [comment]
Hub environment suit completely protects you from the leech special attacks and almost completely from their basic attacks. Cranberry is already wearing one and you can also get one basically for free. I rather thought this one was a cakewalk...

**Comment by PatrikLundell** [comment]
I haven't been offered any hub environmental suit and it didn't show up for sale either, just the same stuff as before (the same parts I've already bought and was wearing), unless I've missed something. I checked what they had for sale after handing in the dead man's mind quest, to see if something new appeared. I noted that Cranberry didn't seem to take any damage, though.

I took up the quest immediately as Cranberry showed up, which was after handing in the dead man's mind quest, which I believe would be what most people would do.

However, if the suit is available for sale, I agree it's reasonable to take a look at the danger faced and return to buy one with Cranberry in tow. The type of protection needed was described fairly well by the enemy description.

**Comment by Jan-Blasiak** [comment]
though I think the mission is indeed a cakewalk, I also think there should be an option to tell the escorting NPCs to wait somewhere.

**Comment by PatrikLundell** [comment]
I'm just checking back at Hub01 and am verifying that no environment suit is on sale. There's probably a probability for it to show up, and I happened to get unlucky. However, given the nature of the quest, this item should probably be guaranteed.

**Comment by PatrikLundell** [comment]
"Knowing what will come" is meta gaming. That's reasonable for RPGs where you're supposed to find out what you're up against, reload, and retry, but not in a rogue-like.

A number of people have said above that the quest is easy when you're prepared for it. The problem is that you have no info on which to prepare, so you'll have to find out by going there (and thus have cast the quest acceptance die). If the RNG rolls your way you can easily return to the hub and buy a McGuffin (that presumably is very useful elsewhere as well: I've never seen it), but if they don't, the quest is basically screwed, at least for a long time (assuming you retreat in time, which I could have done, and would have done hadn't I had to lug the quest giver along. With the quest giver, save scumming it is!).
