### ISSUE TITLE
Zombies Riding in Bike baskets

### ISSUE THREAD

**Issue by Beneficial-Insurance** [CleverRaven/Cataclysm-DDA#57430]
### Describe the bug

Zombies can ride in a bicycle basket. [Image of Bike Basket for reference](https://www.lifesavvy.com/p/uploads/2021/12/29f89c43.jpg?width=720&height=450&fit=crop&trim=2,2,2,2&fit=crop). It is ridiculous for a human sized zombie or even a child sized zombie to jump into one, especially while the bike is still moving.

### Steps to reproduce

Get on bike. Ride it. Watch as zombie jumps on basket and rides along with player

### Expected behavior

I would expect that the zombie not be able to ride on a bike basket.

### Versions and configuration

Windows Ten
Every version; it's probably a JSON fix.

**Comment by PatrikLundell** [comment]
I'm not sure it's silly for something to ride ON a basket, assuming it's sturdy enough to carry the weight. The front basket in the image would probably fall off if you tried to straddle it, while the back one might work (or get squashed, with the frame still supporting you).

**Comment by Jan-Blasiak** [comment]
That's vehicle simulation feature.

If an entity can get on a vehicle tile it can ride the vehicle.
