### ISSUE TITLE
Impossible to select the cargo space for repair

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#57438]
### Describe the bug

Impossible to select the cargo space for repair

### Steps to reproduce

Load the attached game, `e`xamine the vehicle, `lljjj`, `r`epair, hit `j` until you see you cannot reach `-|.▃ cargo space (vol: 484.03/500.00 L)-` with it.

### Expected behavior

Being able to repair or at least see what's required for the repair.

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.F-8098-ge1a449fe4c-dirty [64-bit]
- Graphics Version: Curses
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

https://0x0.st/oADd.zip

**Comment by Jan-Blasiak** [comment]
AFAIK that's a feature.

If a part is too badly damaged it has lower max health.

**Comment by PatrikLundell** [comment]
Weirdly enough, it's possible to "repair" an XX part, which results in it being replaced. That's probably only available if a replacement part is available, and might work the same in that save (haven't tested).

**Comment by toweroglass** [comment]
> Weirdly enough, it's possible to "repair" an XX part, which results in it being replaced. That's probably only available if a replacement part is available, and might work the same in that save (haven't tested).

Hopefully soon someone will add a feature to choose to replace damaged part with a new one. for now you will need to remove the damaged item and replace.

**Comment by RoyBerube** [comment]
Some feedback would help when a part can no longer be repaired. You can't tell if it is because a lack of tools, lack of parts, or just too worn out. It is a bit too streamlined right now - it just skips over parts with no information why.

**Comment by hexagonrecursion** [comment]
This sounds like a duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/54244
