### ISSUE TITLE
about the latest menu display in the cdda android version

### ISSUE THREAD

**Issue by MarcellStar1** [CleverRaven/Cataclysm-DDA#57442]
### Is your feature request related to a problem? Please describe.

in this experimental version it is necessary to add an option to change the menu display to the previous display in the stable version

**![image](https://user-images.githubusercontent.com/102535979/166924423-a03dec4e-9657-4fb8-bc28-f6c6aeed85b6.png)** <<--- I feel that the menu display in the latest experimental version is less comfortable to use, especially on the mobile version

**![image](https://user-images.githubusercontent.com/102535979/166924739-4d453f9c-6e2d-475d-ab64-d5705e279ab7.png)** <--- Menus with a simple display are more comfortable to use and rarely experience wrong pressing, especially on the mobile version

### Solution you would like.

the option to change the menu display as before, and it also affects the appearance of other menus such as the display of selecting bullets when reloading

**Comment by BrettDong** [comment]
There is an option called Native Android UI in settings.

**Comment by MarcellStar1** [comment]
> There is an option called Native Android UI in settings.

wow perfect, apparently there is already an option to change it.
Thank you in advance
