### ISSUE TITLE
Consuming (E) or using (a) bandages closes the Consume or Use menu after the action

### ISSUE THREAD

**Issue by jeffplata** [CleverRaven/Cataclysm-DDA#57441]
### Describe the bug

The Consume Item or Use Item menu closes after selecting to use bandages once. The menu/window used to stay open and the action can be repeated until Escape is pressed. Not anymore. Applying bandages to all parts of the body requires opening the Consume or Use menu several times. QoL gone.

### Steps to reproduce

Easy.

### Expected behavior

After one action of using bandages, the game used to return to the Consume item or Use item menu/window so that same action may be repeated.

### Versions and configuration

- OS: Windows
    - OS Version: 6.3 9600
- Game Version: c2e3aaf [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Consuming water or pills are not affected.

**Comment by haveric** [comment]
/confirmed I am seeing the same behavior by trying to apply multiple bandages.

**Comment by RoyBerube** [comment]
Dang, that is a bit of a mistake. Will take a look at it.
