### ISSUE TITLE
j and k cannot be used in debug item spawn search

### ISSUE THREAD

**Issue by haveric** [CleverRaven/Cataclysm-DDA#57440]
### Describe the bug

j and k are scrolling the result list when trying to search in the debug item spawn menu

### Steps to reproduce

1. Debug -> Spawn an item.
2. Type `/` to search.
3. Try searching for something with a j or k in it, such as a makeshift item.
4. See the list scrolling instead of typing the letters.

### Expected behavior

j and k should only scroll after you hit enter, like the arrow keys do and should work in the search.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1645 (21H2)
- Game Version: 0.F-8083-g1293340378-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

I'm in key input mode of "Symbol"

This only started happening recently, but I'm not sure how recently or which PR caused it.

**Comment by GuardianDll** [comment]
also 2 and 8

**Comment by RoyBerube** [comment]
I noticed the same thing. Changing the keybinds to remove those letters solved it. But yeah it is an annoyance.
