### ISSUE TITLE
Autodocs destroy splints if you're wearing rigid clothing on your arms or legs

### ISSUE THREAD

**Issue by Testudo-Cultu** [CleverRaven/Cataclysm-DDA#57444]
### Describe the bug

Autodocs will destroy splints if there's a conflicting rigid piece of clothing in the way, rather than simply failing to apply the splint.

### Steps to reproduce

1. Break an arm or a leg
2. While wearing something rigid, such as a subject suit (why is this rigid anyway?) try having an autodoc give you a splint
3. Notice that the supply of splints has decreased, but your arm or leg is still floppy and broken and won't heal

### Expected behavior

Autodocs shouldn't destroy splints, but should have a check for whether or not a splint can actually be applied. If a splint cannot be applied, there should be a message describing how/why it failed to apply the splint.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.18363.1500 (1909)
- Game Version: 4974cb9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Crazy Cataclysm [crazy_cataclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Aftershock [aftershock],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by Night-Pryanik** [comment]
Yeah, there's already `// TODO: fail here if unable to perform the action, i.e. can't wear more, trait mismatch.` in bonesetting function.

**Comment by Amoebka** [comment]
I haven't tested it, but I'm guessing characters with integrated rigid armors (spiders, etc) can't wear splints and heal limbs at all? Can someone confirm?

**Comment by Testudo-Cultu** [comment]
> I haven't tested it, but I'm guessing characters with integrated rigid armors (spiders, etc) can't wear splints and heal limbs at all? Can someone confirm?

I hadn't even thought of it, but I'm almost certain you're right. I'll test this later and make a new issue for it, assuming someone else doesn't do it before me.

**Comment by Testudo-Cultu** [comment]
> I haven't tested it, but I'm guessing characters with integrated rigid armors (spiders, etc) can't wear splints and heal limbs at all? Can someone confirm?

I just tested it and ran into another issue, but splints with integrated rigid armor is indeed broken.
