### ISSUE TITLE
Items unable to be put into (heavy) load bearing vest with sling's sling pocket

### ISSUE THREAD

**Issue by Jninja1** [CleverRaven/Cataclysm-DDA#57456]
### Describe the bug

When I try to put an item into the pocket of a load bearing vest with sling, it doesn't allow it and despawns the gun

### Steps to reproduce

1) Have load bearing vest with sling
2) Have gun that can go into sling pocket
3) Insert gun

### Expected behavior

I expect that the gun gets stored properly.

### Screenshots

 DEBUG    : tried to put an item (ksg, amount -1) in a container (load_bearing_vest_sling) that cannot contain it

 FUNCTION : int item::fill_with(const item&, int, bool, bool, bool)
 FILE     : src/item.cpp
 LINE     : 11333
 VERSION  : c2e3aaf

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.613 (21H2)
- Game Version: c2e3aaf [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Cataclysm++ [Cata++],
    Locked and Loaded [Locked_and_Loaded],
    MADA Mod [MADA_bows_rebalance],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    DinoMod [DinoMod]
]

**Comment by TheShadowFerret** [comment]
![image](https://user-images.githubusercontent.com/99621099/167035930-a29a38d8-ac0c-47f1-8233-8417456eb526.png)
- OS: Windows
    - OS Version: 10.0.22000.613 (21H2)
- Game Version: d252a42 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

🤔

**Comment by Hirmuolio** [comment]
Most likely same as #56609
