### ISSUE TITLE
Exodii weapons to add in the future

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#57455]
### Is your feature request related to a problem? Please describe.

Discussion around the PA md. 71z and 68 has led, as such things do, to discussion of what other fictionalized weapons the exodii might be carting around from other dimensions. At some point we should have the definitions for these weapons added into the game, and make them lootable by doing things like dissecting quads, or rarely, finding exodii supply caches.

### Solution you would like.

In general, exodii weapons share a few features.
- Easy maintenance. They tend to use stuff with a tech level capping around the 1970s, for easier machining of parts.
- Heavy and high caliber. The zombies we see in game are the *tip of the iceberg*. Remember that the exodii always eventually have to flee to another dimension. Things get rough as evolution goes on.
- Not too much ammo reliance. The exodii like using burst fire, but try to avoid automatic fire as bullets are always scarce for them.

Exodii have several design considerations that apply differently than to modern weaponry.
- They can manufacture nitrocellulose, but it's a bottleneck. The more explosive/propellant required, the harder it is to justify a round. For larger and stationary things, they love using springs and slings.
- They have ubiquitous access to mechanical winches and targeting assistance
- Recoil and weight are almost non-entities. Their largest guns are for mounting on a 600kg four-legged walking tank. However, they do like to have human-portable weapons both for the non-exodii they sell to, and for the exodii that are still in roughly human sized bodies. Additionally, they generally prefer weapons they can pick up, fire, and discard if damaged to weapons that are built into their frames.

From a design and lore perspective, exodii weapons should give intriguing hints about the timeline they came from. They also should show a widely varied series of Earths, in a brief and intriguing snapshot. I don't want a whole bunch of alternative world war 2 weapons from europe.

#### The Big Gun: Qinghai 1.5x1.8cun launcher
This is the exodii "hand" cannon. It is probably their very favourite gun platform, so even though they have long since run out of the original grenades it used to shoot, they've brought it along. Over decades, or perhaps centuries, of use and adaptation, it has become quite different from what it was.

Originally, the Qinghai was a pump-action 4-round launcher with a bore that's about 30mm in diameter, loosely similar to a [China Lake grenade launcher](https://en.wikipedia.org/wiki/China_Lake_grenade_launcher) at least in appearance. Like the CL it fired grenades, as well as slugs and flechette rounds. However, it comes from a timeline where personal powered exoskeletons and armour became commonplace much earlier and largely filled the role of tanks (also, apparently, a timeline where Imperial China was involved in a war where they deployed power armour at a 1960s tech level). The Qinghai was engineered to be able to lob low-velocity grenades, but also to fire high-velocity rounds with a blast and recoil that would not be possible without power armour. For obvious reasons, this appealed to the exodii. To their delight as they began playing with it, they found the Qinghai was remarkably overengineered and suited to a wide range of uses.

To the exodii, the Qinghai is less a specific weapon, and more of a platform. They still field a modified but recognizable Qinghai to fire grenades and simple flechette rounds, as well as a large JHP round contained in a sabot for use against small hulks. However, its more impressive use is heavily modified: the same basic body is extended with a longer rifled barrel, and used to fire large rounds at high speeds. This weapon is the Qinghai Hulkbuster. It should not be used to fire grenades. Please don't use it to fire grenades. Its primary round is a ~30mm JHP round, which is used to explode hulks and high priority targets at range, essentially the anti-zombie equivalent of an anti-materiel rifle. This gun is used against real hulks. We do not yet have the monsters it is meant to fight in game yet. When you see this thing, again, remember that the exodii are always forced to pull back eventually.

Both formats of the Qinghai are not safe to be used by an unaugmented human, and we don't (afaik) currently have the resources to model this. Firing a grenade from a Qinghai should be safe for a sufficiently tough person (in that capacity it's not much different from a China Lake launcher), but any other round has a recoil that would at best knock you a tile back, and most of the time would probably break a limb.

The exodii do not have a lot of ammunition for their Qinghai class weaponry, and so they hoard it for special occasions. At the stage of the game we're at, they probably aren't using it at all, but are making and hoarding the ammo they depleted before their last jump. However, if the player comes into possession of a Qinghai weapon, they'd probably be glad to share you the specs for ammo, especially if you get them some propellant in return.

#### Close Quarters Weapons: "Calacmul ••••" Olmec revolver shotgun
The exodii sidearm is a very big revolver that fires shotun shells roughly equivalent to a 12-gauge in size. The barrel is probably around 30cm long. It was developed in the equivalent to the late 19th / early 20th century by an Olmec civilization that survived to the post-colonial era as an independent culture, largely due to the organized militia they had to develop to defend themselves from the constant threat of attack from the vicious saurian attacks constantly flowing from the dinosaur infested rainforests to their south. That was a tough dimension to survive in, let me tell you. In that setting, there was a lot of incentive to develop a rapid-cycling close assault weapon long before semiautomatics were invented, and thus, the Calacmul.

For the exodii, the Calacmul occupies a space in between melee, where physical weapons dominate, and range, where a rifle or crossbow is better. It has a wide spread and enormous kick, making it fail against armour at a distance but capable of pulping a zombie inside the kill zone. In general it sees the same use a pistol sidearm would: a backup weapon for close quarter emergencies.

#### Flamethrower: NYD
The final modern weapon the exodii use is a flamethrower. Here I am imagining something developed by a Zulu kingdom in a timeline where they had won the anglo-zulu war and survived to at least world war 1. What it uses for fuel and what kind of traits it has are TBD.

#### Medieval Weaponry
Here is where things get weird, and I will fill out this area later. The exodii have a bottleneck on propellants, so they use quite a lot of springs, drawn rapidly by mechanical winches. It is common for them to use extremely high-draw crossbows, and this is part of why we don't see a lot of armour piercing rounds for their guns: There isn't much in the way of zombie armour that will resist a steel bolt fired from a 2000-lb draw spring steel crossbow.

Besides stupidly huge crossbows, the exodii also favour trebuchets and other siege weapons for base defense. The only disadvantage to these devices, from their perspective, is size: a trebuchet can lob a bomb, large rocks, or huge chunks of spiked steel at incredible distance and velocity, especially when you make the trebuchet from spring steel and draw it with a massive hydraulic system powered by a nuclear reactor.

### Describe alternatives you have considered.
I'm open to suggestions, primarily for combat niches not covered above.

### Additional context
Presently, these systems don't have any strong reason to be in game. The player can't use them yet and they are hard to get. However, eventually, these will be things an augmented player may wish to try out, and getting the ideas laid out is a good start.

In general before making realism comments remember, these are adapted versions of weapons from alternate timelines. They probably made some sense to us in their original form but they now exist to be fired by giant robots against enormous zombie mutants... the rules of a regular battlefield still apply, but only through that lens. Also do you *want* to stop us from having a cyborg firing an enormous pump-action anti-zombie rifle loaded with JHP rounds the size of a small to-go mug?

**Comment by PatrikLundell** [comment]
Given this background I'd expect them to also use melee weapons, tailored to their "biologies", of course, since melee weapons don't waste any ammo at all, especially with this early phase trivial nuisances we've got currently.

Also, if they've got essentially limitless power energy weapons might be useful, in particular rail/coil gun type ones, at least for base defense.

**Comment by fairyarmadillo** [comment]
For the crossbows, what about something that used bionics or technology to achieve performance that wouldn't be feasable for a normal person using a hand crank? There's a pneumatic crossbow here, for example: [https://www.youtube.com/watch?v=CWDJdLWqqn4](https://www.youtube.com/watch?v=CWDJdLWqqn4) 

Crossbows are super cool but they aren't very useful in CDDA because you're usually alone and being mobbed by melee enemies. At best you get one shot off and drop it, which doesn't seem ideal. If the Exodii bow solved that problem somehow, it'd be neat.

There's no reason it would have to specifically be pneumatics and not like bionic power or something, but that would open up some interactivity with Jenny at the refugee center, plus pneumatic weapons are really popular in Russian postapocalyptic fiction, which sorta vibes with the Exodii's Baltic(?) theme.

**Comment by keampe** [comment]
So, you want a Sci Fantasy/Steampunk vibe _and_ want it to be realistic? 

Well, ok, lets give it a shot! 

The comments above about railguns is spot on, IMO. Any place where you have a large nuclear reactor you probably should go the Railgun/Laser/Plasma thrower route. By plasma I don't mean actual plasma, but anything super heated and sprayed out at the enemy, like aluminum raised to the point of steam. It's be like a Thermite thrower. Speaking of thermite, this is easy to make - elemental iron and aluminum are relatively easy to come by if you have Exodii level of tech and it makes a great anti anything weapon.

Picture a spherical bomb filled with thermite loaded onto a catapult. Your advanced targeting tells you the time to target so it sets a fuse. when the charge is 20ft over the target, it goes off, spreading thermite over a large area. Simple and effective.

Another last ditch weapon might be a ballista with a trailing wire. This is to be used when something nasty has breached the outer gates. The ballista shoots the creature and then opens up the nuclear reactors entire output in a giant short circuit. the circuit being completed by conduits running under the floor back to the base.

For personal weapons - How about an engine gun? You squeeze the trigger, the spark plug goes off igniting the fuel in the chamber sending the bullet downrange. The recoil loads another bullet and sprays fuel into the chamber. This is basically how a fuel injected engine works, except the cylinder, being the bullet, is launched as the projectile. As to the rate of fire, how many RPM can an engine do?

Wait..... is this a gas guzzling fully automatic gun? Might as well spray paint it red, white and blue and have some gold truck nuts dangling from the trigger guard....

Anyway, more later!

   - Shane

**Comment by keampe** [comment]
Here's more!

We already have some pneumatic weapons in game which were taken out on the basis that the survivor, using improvised tools, wouldn't be able to make tight enough seals. Perhaps the Exodii can. Solves the propellant problem for small arms.

So, the return of the pneumatic bolt driver and assault rifle! Perhaps these should not be repairable - you take them back to the Exodii for that.

   - Shane

**Comment by I-am-Erk** [comment]
Railguns are honestly a pretty dumb idea for a faction looking for reliable, easy tools. I don't recommend getting into those weeds. Also note that I'm not going for a steampunk vibe here at all.

Pneumatic weapons are an option, but I am pretty skeptical that they'd ever be superior in terms of reliability, reproducibility, and maintenance to a crossbow, if filling the same niche, nor as effective as an assault rifle in that niche. Anything that would require bringing the device back to a specialized manufacturing facility in the exodii base for repairs is a good example of something that isn't really their style.

They might use fossil fuels as explosives on occasion but since they can't produce them it's not something they'd use in a 'favourite gun', they can't rely on finding them a lot of the time.

Thermite's an interesting idea, I might have to look into its anti-personnel options.

**Comment by PatrikLundell** [comment]
What about crossbow attachments that winds the bow up with the press of a button if present, and that they'd have to wind up manually otherwise? The reason for a powered assist wouldn't be draw strength, but speed. If they're (generally) strong enough to just pull the string back and attach it to the release with their hands a major crossbow drawback is reduced (one shot and then melee, unless they fight in squads with melee fighters that keep the enemy at bay while they reload, which doesn't seem to be the case).
Another alternative would be an optional crossbow bolt magazine that would push a new bolt into place as the previous one has been fired (which would work well with an automated cocking attachment, either pneumatic or powered by fuel or electricity.

**Comment by I-am-Erk** [comment]
I'd imagine it'd use a battery powered draw for non-cyborgs, and cyborgs would just plug it in to their internal battery. Or it might just be a very high draw crossbow that they pull manually, but I think mechanical advantage favours a winch either way. I don't see any reason it couldn't have a magazine.

**Comment by fairyarmadillo** [comment]
> I'd imagine it'd use a battery powered draw for non-cyborgs, and cyborgs would just plug it in to their internal battery. Or it might just be a very high draw crossbow that they pull manually, but I think mechanical advantage favours a winch either way. I don't see any reason it couldn't have a magazine.

IDK if you've playtested them lately, but crossbows are practically useless in the game for the same reason they would be in real life - the reloads are too slow and the damage is not very good. If they can solve those problems with technology that's great. A standard crossbow is just not a very good zombie apocalypse weapon.

Exodii have pneumatic muscle CBMs, so they'd be really effective at using stuff like the compound greatbow. Or at least I think they would, it's not actually clear to me if the workers and quadrupeds (are the quads people?) have supplementary cbms like the player or if they ditched all that for almost full body prostheses.

**Comment by keampe** [comment]
Hmmm... If they have high speed winches..... Ever seen a football throwing machine? A couple of small wheels that rotate very fast to launch the ball and one to make it spin. You could do a more powerful version of this to launch bullets - IIRC some electric airsoft guns work this way. You could even have a barrel lined with consecutive wheels each pulling the bullet faster as it travels down. This thing could also easily be fully automatic.  

Or..... Javelins. How hard can a cyborg throw a javelin?

As to the pneumatic guns, look at the Girardoni air rifle. It was reliable enough for Lewis and Clark to bring on their expedition and was demonstrated to every group they met. There is no mentions of any problems with it as far as I know. Pneumatic weapons never gained traction because gunpowder became so much more available and is, quite frankly, much more convenient to use. If you're lacking in propellant pneumatics suddenly  become much more attractive.

Also occurs to me that the Engine gun could just as easily be a steam gun - no hydrocarbons needed, just electricity to flash water to steam. 

 - Shane

**Comment by PatrikLundell** [comment]
Javelins have the issue of being large, so a cyborg wouldn't be able to carry many of them.

Steam has the problem of being bulky as you'd need to cool the steam down and recycle it, or carry a water tank with "propellant". That's less of an issue with a fixed installation, though.

**Comment by I-am-Erk** [comment]
> IDK if you've playtested them lately, but crossbows are practically useless in the game for the same reason they would be in a real life cataclysm - the reloads are too slow and the damage is not very good. If they can solve those problems with technology that's great. A standard crossbow is just not a very good zombie apocalypse weapon.

Bear in mind that the exodii already have assault rifles. This isn't describing a replacement weapon for the PA Md. 68.

**Comment by fairyarmadillo** [comment]
If the exodii have a solution to the ineffectiveness of crossbows compared to regular bows (either via super powerful shots or faster loads) then that's great because that's a niche the game is missing.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
