### ISSUE TITLE
Game crashes when hiding sprite with no clothing on

### ISSUE THREAD

**Issue by brassmaster2357** [CleverRaven/Cataclysm-DDA#57459]
### Describe the bug

Pressing the "Hide sprite" key in the armor menu without anything worn will cause the game to crash. That's all.

### Steps to reproduce

1. Remove all clothing
2. Open armor menu
3. Press H (or whatever key you bound "Hide sprite" to)
4. Crash!

### Expected behavior

I expected the game to just give a little "You can't do that!" message, like when you try to craft an item you don't have materials for.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19042.1645 (20H2)
- Game Version: 08f7ccb [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Innawood [innawood],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    No Freeze [no_freeze],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Safe Portable Autodoc [safe_portable_autodoc],
    Manual Bionic Installation [manualbionicinstall],
    Clean CBMs [clean_cbm],
    Stats Through Skills [StatsThroughSkills],
    No Fungal Growth [no_fungal_growth],
    Mining Mod [Mining_Mod]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8636411/crash.log)

**Comment by haveric** [comment]
/confirmed Replicated and fixed via linked PR
