### ISSUE TITLE
Gold ring is flashy but not fancy!

### ISSUE THREAD

**Issue by OnTheDouble** [CleverRaven/Cataclysm-DDA#57460]
### Describe the bug

In CDDA jewelry has FANCY property which gives a morale bonus to the player. Yet the Gold Ring is not fancy somehow. Its description tells us it's flashy though... I see a contradiction.

### Steps to reproduce

1. Go to Crafting Menu
2. Find "gold ring"
3. Fancy is not one of the ring's properties

### Expected behavior

Jewelry made of precious metals should be fancy.

### Screenshots

![image](https://user-images.githubusercontent.com/82908191/167037146-8b979290-cb7e-49c5-976f-d57206766e7e.png)

### Versions and configuration

2022-05-05-1855 Experimental Win 64

**Comment by SamGondra** [comment]
Can confirm.
Will probably look into it Tomorrow, I had intended to revisit jewelry to add coverage anyway.
(Or someone else can take it up - should be a very simple first issue)

**Comment by OnTheDouble** [comment]
Thanks for looking into it!

**Comment by leemuar** [comment]
imho gold ring is not fancy, it's just a boring ring of gold)
