### ISSUE TITLE
Cleaning a gun with soapy water uses 8 liters. This is too much.

### ISSUE THREAD

**Issue by EnzoMonroe** [CleverRaven/Cataclysm-DDA#57464]
### Is your feature request related to a problem? Please describe.

Using the [m]end menu to clean a fouled firearm, the first step is to clean it. There are various solvents available. 

The first category of these includes gasoline, denatured alcohol, diesel, and ethanol, and consumes 125 units in each case. I believe these are measured in units of 0.001 liters each, judging by the fact that the 560 units of gasoline my character is standing next to has a volume of 0.56 liters. 0.125 liters of solvent to clean a gun's barrel seems like a lot for a pistol, but probably reasonable for a rifle.

The second category includes ammonia and bleach, and asks for 2 units of either. Bleach and ammonia are measured in units of 0.125 liters, so twice as much of either is required here for no reason that I can determine. Kind of annoying, but not a big deal.

Next, we have vinegar. 16 vinegar is required to clean a firearm. Vinegar appears to be measured, maddeningly, in units of 0.015625 liters, judging by the fact that 240 units of vinegar occupy 3.75 liters. This means it takes 0.25 liters of vinegar to clean a gun. Having personal experience using vinegar as a solvent to clean things, using that much is kind of a silly amount. But okay, moving on.

Okay, last, we have soapy water. 32 units of soapy water is required to clean a gun. One units of soapy water is 0.25 liters. Therefore, we need 8 liters of soapy water to clean a gun barrel. This is far, far too much.

### Solution you would like.

I am not prepared to judge which solvent would be most efficient, so I would suggest making the amount of solvent required as even as possible across the various options. Therefore, I would suggest that 0.125 liters be used for those solvents that have units that small (i.e. everything but the soapy water) and 0.25 liters for the soapy water. Alternately, a more in-depth solution would be to make soapy water have smaller units, and have it also use 0.125 liters.

**Comment by RoyBerube** [comment]
Someone just has to do a balance pass on faults_gun.json. Just 2 units  of soapy water should be plenty imo.
