### ISSUE TITLE
Rigid Hub modular defense anchor

### ISSUE THREAD

**Issue by Gotdamnmiracle** [CleverRaven/Cataclysm-DDA#57461]
### Describe the bug

Both the 5-point anchor and the hub modular defense items are non-rigid. When handed over to the Hub they give you back the rigid hub modular defense anchor. 

This presents a problem through both gameplay and logic. How can two non-rigid objects form a rigid one? Essentially adding a harness with a big buckle to a poncho does not sound like it should be made rigid all of a sudden. This is a problem with gameplay because it disallows the anchor to be worn with the phase-immersion suit- again, odd because both the modular defense and 5-point anchor can be worn over it on their own.

### Steps to reproduce

1. Obtain modular defense and 5-point anchor. (either spawning items or gameplay)
2. Observe items non-rigidity.
3. hand over to Hub 01 and wait...
4. Collect rigid hub modular defense anchor
5. Try to wear over phase-immersion suit (or any single piece rigid outer-clothing) and be told you cannot wear it.

### Expected behavior

I expect that the resulting item should be non-rigid or at the very least functional with the phase-immersion suit.

### Versions and configuration

- Game version: [cdda-windows-tiles-sounds-x64-msvc-2022-05-05-0358]

**Comment by bombasticSlacks** [comment]
good catch on this one, your logic is sound but it's just an oversight.
