### ISSUE TITLE
Mutated skin (E.g. protective bark, phelloderm, epicuticle) can be permanently destroyed

### ISSUE THREAD

**Issue by Testudo-Cultu** [CleverRaven/Cataclysm-DDA#57479]
### Describe the bug

Mutated skins visible in the (W)ear menu can be destroyed permanently, making the mutation it belongs to meaningless.

### Steps to reproduce

1. Have mutated skin, such as protective bark
2. Stand in a fire for a second or two
3. Have your skin permanently melt off, leaving you with a skin mutation that does nothing

### Expected behavior

This would be cool if the infrastructure for permanent injuries existed, but at least for now, mutated "apparel" should be indestructible or at least regenerate.

### Screenshots

![image](https://user-images.githubusercontent.com/65055502/167148394-d7a77666-c42b-4f8b-a578-37d9824644df.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.18363.1500 (1909)
- Game Version: 4974cb9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Crazy Cataclysm [crazy_cataclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Aftershock [aftershock],
    No Rail Stations [No_Rail_Stations]
]

**Comment by Nerezza** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/e36a58ab23fff4ecc1d649bcc51d49c26454275d/src/character_attire.cpp#L1722 
outfit::absorb_damage here doesn't seem check for the "UNBREAKABLE" flag on armor before doing damage to it.
