### ISSUE TITLE
Heating up food takes an unknown amount of time

### ISSUE THREAD

**Issue by Benny-Bear** [CleverRaven/Cataclysm-DDA#57472]
### Is your feature request related to a problem? Please describe.

When you use a hotplate to heat up food you have no idea how long it will take to complete.
I tried to heat up a stack of 650 corn from frozen and after taking 12 hours I gave up and the entire stack was still frozen.

### Solution you would like.

Some system of informing the player of how long heating up food will take so that they know they need to break up the stacks if its going to take literally forever.
Could do some sort of rough guestimate based on cooking skill, or an exact value based on magic.

### Describe alternatives you have considered.

Being able to pause and restart reheating food.

**Comment by PatrikLundell** [comment]
I'm fairly sure it is not *literally* taking forever. Just a bloody long time. Literally literally means literally, i.e. exactly as written, not as a parable or exaggeration. You're probably looking for the word "virtually".

**Comment by Benny-Bear** [comment]
There's no way to see how long its going to take so I see dying of dehydration or passing out before being able to finish is *literally* forever for the player.

**Comment by Karlington2** [comment]
https://www.youtube.com/watch?v=1ydBhh4dR1I
