### ISSUE TITLE
Using the "reload" interface to combine liquids displays invalid candidates and silently fails when those candidates are selected, while still deducting move points and indicating in the log that the action was successful

### ISSUE THREAD

**Issue by Ilurker** [CleverRaven/Cataclysm-DDA#57484]
### Describe the bug

When using the reload interface to combine containers of liquid, the game shows and does not provide an interface to adequately differentiate between actual combinable liquids, and liquids which are very similar but which can not be combined. Selecting one of these mismatched liquids via the reload interface silently fails, but still deducts move points and completes the other relevant tasks to the action, such as moving the destination bottle into the inventory.

For instance, my character has seven seperate animal cooking oil objects, of various volumes, in seven different containers. The total volume of all the containers is around 3L. By using the insert command, I am able to pour one container into a 3L jar. I then use the reload command, which displays all animal cooking oil in range. Of the cooking oils in range, none are actually combinable due to being made of differing ingredients (tallow vs lard, clean water vs normal water, etc, mutant fat vs regular fat, etc).

While it may ultimately be unrelated, in the course of researching this behaviour and producing these screenshots, I generated a very long list of inventory-related errors on the save file. These errors do not preclude the game from loading, but may be related to the repeated errors and unexpected behaviour. I have no observed any gameplay effects following these errors, but due to their volume it is likely I will need to roll back to a backup save. Log attached.

Example screenshots:

![image](https://user-images.githubusercontent.com/104868222/167188190-299219e0-b885-4bd6-bed4-5e4a8e20ae5e.png)
Starting conditions.

![image](https://user-images.githubusercontent.com/104868222/167188474-abe47303-9732-477f-b518-87032c7f11c7.png)
Initial attempt to combine all via the Insert command. Note the error message in the log. A single container's worth of cooking oil has transferred, as is expected. Note the timestamp.

![image](https://user-images.githubusercontent.com/104868222/167188657-c4acc234-6ba4-46ca-a0bc-da6d8c327335.png)
The reload interface for the 3L glass jar, showing all the animal cooking oils as valid candidates to be combined. There is no further information on any of the candidate liquids to differentiate them from one another, besides their container and quantity.

![image](https://user-images.githubusercontent.com/104868222/167189429-33131445-a0ae-4f7f-9c5b-f878ea6fc140.png)
Misleading message indicating a successful "reload" of the 3L jar of cooking oil. Note that the time has changed, indicating the moves have been spent as well. The "never mind" entry is a result of an errant keypress while attempting to take a screenshot and is not typical of the error.

![image](https://user-images.githubusercontent.com/104868222/167189871-f6d4adf6-029e-4d7e-b96f-305082228043.png)
Second attempt at reloading, this time we'll use the second.

![image](https://user-images.githubusercontent.com/104868222/167190126-f6185823-bed5-45f4-9526-760efefe5dbf.png)
Again, indication of success and moves deducted.

![image](https://user-images.githubusercontent.com/104868222/167190273-8c6b93f2-441c-46d8-a766-1c49e022ba23.png)
Confirmation of failure to combine.

![image](https://user-images.githubusercontent.com/104868222/167191543-6a3539f3-0bcc-4b84-8c5a-432fe1b677c4.png)
An example of a successful combination - one of the bottles was made from the same batch of oil and split between different containers. On successfully combing them, the same message and deduction of moves occurred. This serves to illustrate how opaque the reloading system can be, especially when it makes it difficult for players to access information about why the combination might have failed.

### Steps to reproduce

1. Produce several seemingly identical batches of liquids which differ only by their ingredients
2. Utilize the "reload" interface to attempt to combine the liquids
3. The game should silently fail the action, but behave in all other respects like it completed successfully

### Expected behavior

The reload list should exclude liquids which are not actually combinabe, either by not listing them at all, or more preferably, listing them with an overlaid error message (similar to the one used in the consume interface to indicate a food or beverage can not be eaten in its current state)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8642661/save.zip)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8642667/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8642668/crash.log)

**Comment by Hirmuolio** [comment]
Does not seem to happen in latest experimental.
