### ISSUE TITLE
Hub 01 environment suit not compatible with boots

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#57482]
### Describe the bug

It seems odd to be sent into harms way in cramped spaces using the suit and other hub 01 protective equipment, but not being able to wear any boots to protect the feet against damage. For some reason attempting to wear combat boots together with the suit causes a rigid conflict on the foot arch "Can't wear more than one rigid item on left foot arch".

At a guess there's something in the sub location system that makes the foot arch rigid by default.

### Steps to reproduce

1. Wear Hub 01 environmental suit
2. Try to wear combat boots (or change the order in which you try to put on the equipment).

### Expected behavior

A soft body suit ought to be able to be used together with boots just as it is able to be worn together with gloves.

### Screenshots

Combat boots worn first:
![Screenshot (244)](https://user-images.githubusercontent.com/22739822/167176982-4a1078d9-9ecb-48f1-b6b6-88f144ad58bf.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1645 (21H1)
- Game Version: 30c8dc3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by bombasticSlacks** [comment]
It covers the feet, it has footwear already included

**Comment by PatrikLundell** [comment]
Yes, it covers the feet, but it doesn't have to be rigid because of that. I don't believe socks are rigid, for instance. If, for whatever reason, it cannot be combined with normal boots, Hub01 ought to have developed outer layer boot to allow the suit to be worn in hostile encounters without leaving the feet essentially unprotected against non environmental assault.

**Comment by bombasticSlacks** [comment]
All shoes are normal layer so they would conflict with the included shoes. 

Even if it didn't conflict the reason all actual footwear is rigid is because of the soles. You can't stuff soled sneakers in other soled footwear it wouldn't make any sense.

**Comment by PatrikLundell** [comment]
Galoshes are worn outside of normal shoes to protect them.

**Comment by bombasticSlacks** [comment]
From what I can see goloshes don't appear to have a notable sole. So I would argue in our system they would be considered soft which would be fine. They also wouldn't work as footwear on their own. 

I think galoshes, rain covers, and such are a far cry from the original request to wear two sets of footwear.

**Comment by PatrikLundell** [comment]
I disagree that it's a far cry from it. A dedicated outer Hub 01 protective footwear would solve the problem (assuming, of course, the suit actually has soles, and doesn't have soft bottom cover (like socks do).

**Comment by ZaricaDemoni** [comment]
Rubber boots iirc exist ingame, which are a real world protective boot for hazards. Is it wrong to assume the Hub 01 protective suit would have built in rubber boots? If its not stated for such, it should be, as that would both fix this problem and make sense.

**Comment by fairyarmadillo** [comment]
As far as I am aware, real-life hazmat suits do not have fully soled shoes on them. The ones I am seeing end in basically socks and then you put normal boots on over those and sometimes a slip cover over that.

**Comment by Nerezza** [comment]
https://www.globalsafetyco.com/ppecloth_duptlvlb.htm
Found a vendor of Dupont hazmat suits. Level B which seems like the closest to what the Hub provides us.

None of the suits incorporate boots, socks/booties are optional.

Only one of the suits incorporates gloves.

All of the suits are intended to be worn with a helmet (hard hat irl), even the encapsulating SCBA one.

**Comment by bombasticSlacks** [comment]
Its a modified CBRN suit otherwise it would be bulky and high encumbrance.

Also with things like the Hub suit we have to assume you are wearing it correctly IE that you are perfectly insulated. If you wore runners with a suit like this it wouldn't provide it's electrical protection or its full body hazard protection.

So if someone want's to code rules for testing if you're shoes are long enough to tuck into a CBRN suit that would be an exceptionally involved solution and kinda stupid.

Otherwise the solutions as I see it are:

Make the current footwear armor entry more akin to the attributes of soldier boots, rubber boots, or something new made out of rubber and other materials. The downside of this is that all the current boots are poorly defined so this isn't really an increase in fidelity. 

Make the current footwear entry OUTER layer which would make it no longer count as your shoes and they would be covers / goloshes.

Both of these solutions are very easy to do.

**Comment by LikeableKiwi** [comment]
I am actually quite Curious... Can't wear EOD foot protection with it even though it's classified as an outer clothing piece.

**Comment by bombasticSlacks** [comment]
It would be because the included boots have a steel shank and a few other metal reinforcements which conflict with other inflexible hard items like the EOD footwear.

**Comment by bombasticSlacks** [comment]
Anyways this is done so I'm closing this
