### ISSUE TITLE
Using the last first aid item in a stack, contained on a different tile, throws an error and allows it to be used infinitely

### ISSUE THREAD

**Issue by Ilysen** [CleverRaven/Cataclysm-DDA#57494]
### Describe the bug

When consuming a first aid item stored on a tile and not in your inventory, such as a bandage or antiseptic, it will function normally until attempting to consume the final use or charge of that item. When it does so, removing the item will fail, resulting in the charges being reduced to zero or even negatives while still applying the effects. This results in being able to use the same item on yourself infinitely many times, so long as it remains on the same tile. Attempting to pick up the item using the advanced inventory manager will hard crash the game.

I'm not sure the full extent of items this happens with; I observed it happening with bandages, adhesive bandages, antiseptic, and antiseptic powder. This is probably caused by #57317.

### Steps to reproduce

1. Create a new world, or use an existing one.
2. Either grab a single first aid item, or use charges from a stack until you have one remaining.
3. Put the item on the ground near you, and apply.
4. See the error message appear. After clearing the error, you'll be left with an item with zero or negative charges.
5. Use the single first aid item to patch up every body part; observe that the charges continue further into the negative.

### Expected behavior

First aid items shouldn't throw errors when you use them.

### Screenshots

![image](https://user-images.githubusercontent.com/47678781/167225815-16d35ce2-aaff-4e9a-99bd-af8340200f05.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1645 (21H2)
- Game Version: 0.F-8124-gc68b9c6c35 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

Here's the error message thrown when using a regular bandage:
```
 DEBUG    : did not found item bandage to remove it!

 FUNCTION : i_rem
 FILE     : C:\Cataclysm-DDA\src\character_inventory.cpp
 LINE     : 248
 VERSION  : 0.F-8124-gc68b9c6c35
```

**Comment by RoyBerube** [comment]
Confirmed. The steps do lead to that outcome. Taking a deeper look at it now.

**Comment by RoyBerube** [comment]
I have a working fix for this problem - it was a tricky one for a number reasons. Should have it submitted in 1 or 2 days.
