### ISSUE TITLE
Segfault while Saving

### ISSUE THREAD

**Issue by Xtrem532** [CleverRaven/Cataclysm-DDA#57497]
### Describe the bug

Got a Segfault while Saving and Quitting

### Steps to reproduce

Esc -> Save and Quit -> Crash

### Expected behavior

No Crash

### Versions and configuration

- OS: Win 10 Education 19044.1645
- Game: x64 Tiles 30c8dc3e75c847e2354c16d06dbd03601f77a499 
- Language: English (OS is German)
- Mods:
  - "dda"
  - "no_npc_food"
  - "package_bionic_professions"
  - "blazeindustries"
  - "StatsThroughSkills"

### Additional context

Loading the save afterwards suceeded, immediatly saving it again without doing anything aswell. As far as I can tell, nothing got lost.

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8644088/save.zip)
[logs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8644090/logs.zip)

**Comment by snipercup** [comment]
Cannot reproduce:
- Load save file
- Move 3 tiles south
- Press esc -> save and quit -> quit

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 8.1
- Game Version: 46d0df6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Stats Through Skills [StatsThroughSkills]
]
