### ISSUE TITLE
Limb blocking causes more damage to armor than usual

### ISSUE THREAD

**Issue by Reuvin** [CleverRaven/Cataclysm-DDA#57503]
### Describe the bug

Blocking with limbs has a habit of causing damage to armor faster than usual. 

### Steps to reproduce

1. Create a new world
2. Make a character with 10 in melee and unarmed for maximum amount of blocked attacks
3. Strip naked, equip a full body armor suit of choice with the "BLOCK_WHEN_WORN" tag
4. Spawn a zombie and let it go to town on you until the armor takes damage
5. Exit the world and create a new character with 0 unarmed and 0 block
6. Strip naked and equip the same full body armor suit used in prior testing again
7. Spawn a zombie and let it go to town on you and notice that the armor will last far longer just eating hits than if it was being actively used to block with

### Expected behavior

I imagine blocking with a limb would simply cause the standard armor damage check, but blocking with arms causes damage to the armor far faster than if the armor had just taken the hits normally. This leads to a high melee skill being a detriment to a character after they begin to use guns as a primary weapon in conjunction with quality armor, as it means their armor will break faster than if they had never used their melee skill in the first place.

### Screenshots

![Screenshot (11)](https://user-images.githubusercontent.com/105094308/167238772-dfe11524-f49b-4387-991a-422a95fff548.png)
The initial stat spread of the high melee character

![Screenshot (12)](https://user-images.githubusercontent.com/105094308/167238776-c4f59ef3-0c5a-4886-b008-89d5751e422c.png)
I added deadened after the initial testing because I realized that the stat drops due to pain could be influencing the test

![Screenshot (13)](https://user-images.githubusercontent.com/105094308/167238821-0201db46-efab-4688-940c-970004b8d962.png)
The time when the tempered heavy plate armor took damage while actively blocking with arms (Specifically at 8:07:55)

![Screenshot (14)](https://user-images.githubusercontent.com/105094308/167238842-4df4bb12-773d-4ec6-9274-71dd3a8cf669.png)
The stat spread of the 0 melee skill character (note that I simply reloaded the prior save and changed the melee skills to 0 from the 10 they were at)

![Screenshot (15)](https://user-images.githubusercontent.com/105094308/167239004-9ee000c5-41f2-4f25-870a-c004373239b4.png)
Half an hour after the start of testing

![Screenshot (16)](https://user-images.githubusercontent.com/105094308/167239020-8cebe8a4-4c9a-4301-8c50-22d913fecb07.png)
![Screenshot (17)](https://user-images.githubusercontent.com/105094308/167239023-67e35a64-4e13-4426-afaf-a80c75efb0dc.png)
A full hour after the start of the test in game. The armor is left completely unharmed on the character incapable of limb blocking. 

### Versions and configuration

Experimental build 2022-05-06-1613

**Comment by Keyanos** [comment]
@bombasticSlacks Since you requested to be tagged with the creation of this bug report, here you are.

**Comment by RoyBerube** [comment]
I'm looking at the `Character::handle_melee_wear()` method and some issues stand out:

- Higher character strength increases chance to damage your armor for no benefit.
- The sturdy and flimsy flags are not factored in.
- The number of body parts covered is not factored in.

The way that armor normally takes damage is in `item::damage_armor_durability()` . Among other things, It uses the sturdy and flimsy flags and number of body parts covered.

Damage taken is calculated by chance - either it takes damage or is unscathed. Currently the odds of armor taking damage when blocking are much greater than when the armor takes damage the normal way. There is room for improvement.

**Comment by bombasticSlacks** [comment]
IMO the simplest solution is to just have it so that if the best_shield is a worn piece of armor and you block with it instead of going into handle_melee_wear it should call a wrapper function that calls item::damage_armor_durability based on the incoming damage and based on what damage_armor_durability returns damages or destroys the item.

**Comment by bombasticSlacks** [comment]
Also worth saying the "handle_melee_wear" stuff needs to exist for weapons I think but for armor there really should be parity on damage outcomes.
