### ISSUE TITLE
Dino corpse sprite doesnt shows up

### ISSUE THREAD

**Issue by WFeron** [CleverRaven/Cataclysm-DDA#57509]
### Describe the bug

I have read the monster.json for dinomod. it says most huge sized dino is copy-from:mon_apatosaurus including mon_brontosaurus. i used the dino sprite from kennan modpack and installed the sprite jpg(s) to DinoMod mods folder. alive both Apatosaurus and Brontosaurus shows a sprite but when killed only Apatosaurus left behind corpse sprite. this affect not only Brontosaurus but others with copy_from:mon_apatosaurus.

### Steps to reproduce

1. Spawn both Apatosaurus and Brontosaurus
2. Kill both dino
3. Apatosaurus left behind corpse sprite but Brontosaurus didn't

### Expected behavior

I expected that Brontosaurus and others with copy_from:mon_apatosaurus also left behind corpse sprite 

### Screenshots

![1](https://user-images.githubusercontent.com/105108342/167251035-fe943214-4abd-4c86-aea0-a3f07d65baa5.png)
![2](https://user-images.githubusercontent.com/105108342/167251036-fc01457c-2b07-4893-ab9e-ac5240450738.png)

### Versions and configuration

OS: Windows 10
Version: 589bcb2
Tileset: tried on UndeadPeople and Ultica

**Comment by LyleSY** [comment]
I've taken a couple of different approaches to address this. It looks like manually defining the corpses and assigning them a sprite isn't working. It may be possible but just too time consuming, so instead I've just submitted art for brontosaurus for UDP. Hopefully that fixes. There's still a lot of missing art in UDP, but it's by far the most complete for DinoMod. I've also been working on shoring up the art that ships with the game to at least get some basics covered.

**Comment by LyleSY** [comment]
Brontosaurus art is bugged and also I should have made art for the corpse. I'll try and do that. I expect there is a code fix that could enable copy_from to populate to corpses, but that's beyond my abilities

**Comment by LyleSY** [comment]
Fixed in UDP by https://github.com/Theawesomeboophis/UndeadPeopleTileset/pull/88 Thanks!
