### ISSUE TITLE
Rubik's exodii fortress is a source of free (and extremely nice) stuff

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#57505]
### Describe the bug

first of all, there are a LOT of sealed crates that you can open with a crowbar
some of them have clips with ammo, some have rifles
ALSO unloading stuff doesn't count as stealing
ALSO exodii workers don't actually mind you stealing their stuff

### Steps to reproduce

Go in with a crowbar, return with thousand of badass rifle rounds and tools from parallel world.

### Expected behavior

No extremely powerful free loot.

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.F-8118-gefe36ec1a1-dirty [64-bit]
- Graphics Version: Curses
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

**Comment by toweroglass** [comment]
narc.

serious: I noticed it now flags it as stealing. they don't actually care? I'm always super sneaky opening the boxes out of site. it's a good source of metalworking supplies.
