### ISSUE TITLE
Internet connection change statters

### ISSUE THREAD

**Issue by Unlite** [CleverRaven/Cataclysm-DDA#57511]
### Describe the bug

I have a vpn for my work purposes on my pc. After i've change my internet connection from one internet connection to another while ingame (from any to any other), game begins to full freeze for like 3-5 minutes in every 20-40 minute gaps.
Restarting game doesn't helps, only PC reboot.

### Steps to reproduce

1. Launch the game
2. Change internet connection from one to another (VPN or any another internet connection).
3. In some time you will game freezes.
4. Launching the game after, will take from 2 to 5 minutes.

### Expected behavior

I expect that a changing my internet connection while playing not affect my single player game expirience.

### Versions and configuration

- OS: Windows 10 Pro x64
- Game version: 0.F-3
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: The default list for this game release

**Comment by NetSysFire** [comment]
If we had a voodoo label, I would assign it to this issue.

This sounds so weird I bet it is not related to the game but one of its components (e.g SDL) or something underlying, like the path to where you installed Cataclysm DDA.
I have no idea about windows, but if you were on linux I would tell you to `strace` the application.

**Comment by Unlite** [comment]
@NetSysFire Yeah, i know, i'm a dev myself, and i am super surprised such issue to be

**Comment by Unlite** [comment]
Ok, maybe it is on my side, bcs i could not repeat such issue on another pc, so i'm closing the issue
