### ISSUE TITLE
TCL drones can scan otherworldly enemies, causing massive lag

### ISSUE THREAD

**Issue by EtherealMoon0** [CleverRaven/Cataclysm-DDA#57521]
### Describe the bug

A tear in reality spawned flaming eyes and other critters, which wandered into a room with multiple TCL security drones, who scanned them every turn and caused unbearable lag. This is probably only a problem for passive creatures that don't actually attack, like flaming eyes and gracken.

### Steps to reproduce

1. Spawn a few TCL security drones. 
2. Spawn a flaming eye or gracken nearby.
3. Wait for 5 minutes and listen to your CPU struggle.

### Expected behavior

From a performance perspective, drones don't scan zombies, so they probably shouldn't try to scan otherworldly beings. To be fair, seeing them properly call in security on the aliens would be pretty neat.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1645 (21H2)
- Game Version: 46d0df6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Crow's Hairstles 2: Bright [hairmod2_bright],
    Crow's Hairstles 2: Ears and Tails [hairmod2_earsAndTails],
    Crow's Hairstles 2: Natural [hairmod2_natural],
    Whaleys Hair & Tattoo - 0.F [WHALEYHAIR1],
    Extra Mutated Scenarios [extra_mut_scens],
    Bionic Slots [cbm_slots],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by Jan-Blasiak** [comment]
/confirmed YES!

Fs! Those drones are unbelievably stupid! They cause SO MUCH LAG I lost 2h of gameplay because I had to shut down CDDA because it took 30 min to sleep through 1h of those stupid drones scanning everything few floors below.

**Comment by Wyrdean** [comment]
Drones in general should scan less often as well, they can cause non-insignificant lag even when they're just scanning players

**Comment by andrei8l** [comment]
The lag should be fixed now. Is it really a bug that drones can scan monsters though?

**Comment by Maleclypse** [comment]
Someone who is able to profile differences might get a different result but I waited 30 minutes in the TCL and then I deleted the ability for drones to scan at all and reloaded the game and waited 30 minutes in the TCL.  Same spot.  I couldn't tell a measurable difference between the two wait periods. Both were quite long.

**Comment by I-am-Erk** [comment]
I think we need a profile test on this before we can suggest a fix, but it sounds like it should remain a blocker.

**Comment by LyleSY** [comment]
I attempted to test this with newest experimental on Mac and it did scan me a few times but I didn't notice any lag. I spawned an albino penguin but it didn't seem interested. I don't know whether this is the ideal long term state, but it doesn't seem broken
<img width="1040" alt="Screen Shot 2022-11-23 at 9 31 03 PM" src="https://user-images.githubusercontent.com/26608431/203681320-c06442df-38fb-4666-98ba-badea0f8b132.png">

**Comment by andrei8l** [comment]
I've fixed this particular issue (drones scanning every turn and freezing the game) in 23e41229099e6a9ee9daf40101064ffc93c5af26. There is still room for improvement in the mapgen update chain, but I don't think we need to keep this issue open for them.

**Comment by I-am-Erk** [comment]
I'll accept this as resolved then. Thank you.
