### ISSUE TITLE
"Pick <plant>" is missing a question mark

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#57522]
### Describe the bug

While working on a PR and testing it I discovered this:

![image](https://user-images.githubusercontent.com/59517351/167268566-1dc48aa3-785a-4df6-8ef8-a9106b55a076.png)

### Steps to reproduce

1. Try to harvest any plant.
2. Notice the missing terminal punctuation

### Expected behavior

It has appropriate terminal punctuation.

I am fairly sure this is caused by

https://github.com/CleverRaven/Cataclysm-DDA/blob/42ddccb6ef00826dec8301ccfa4e4f57f0af656b/src/iexamine.cpp#L2194-L2200

Yet I am not fixing this myself because I am too lazy to compile and test. I'd bet you don't even need `query_string` and can turn this into a oneliner.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.F-7779-g77235b67732 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by leemuar** [comment]
fixed
