### ISSUE TITLE
Include a key to report vehicle parts when examining tiles on the look around menu.

### ISSUE THREAD

**Issue by DoctorBoomstick** [CleverRaven/Cataclysm-DDA#57544]
### Is your feature request related to a problem? Please describe.

Vehicles, whether crafting, driving, or customizing them, are a large feature of the game and are a corner stone of late game advancement. However, interacting and actually using vehicles in any meaningful manner is nearly impossible with the tools available, and are very impractical to utilise for blind users who rely on screen readers. As I’ve already described in issue #56507, people who play CDDA with accessible technologies often do so by making heavy use of the look around menu. I have gone into detail with the usage and various issues of this system in the linked issue, but for the sake of completeness I will summarise here as well. As a rule of thumb, when ever a blind person such as myself enters an area that is not intimately familiar, such as on looting runs, they normally scout out the tiles around them by bringing up the look around panel, and using the t, c and f keys respectively to check for terrain, monsters, and furniture. These are incredibly useful functions, as they make the game playable by allowing the user to build a mental picture of the space around them, and the game would otherwise be completely unusable without their presents as the player would have no idea of what’s around them. Unfortunately, this is true for vehicles and appliances. As vehicles use a different layer than normal terrain or furniture, their existence is not ever reported by using the prior described keys, and as such the player will never realise that there is a vehicle even when directly looking at a tile which houses part of one.
For example, let’s picture the following scenario. The player is standing on one side of a street and wishes to get to the other side, whilst in the middle of the street there’s a fully functional Humvee. The player brings up the look around menu and looks in a strait line across the road to check that everything’s clear, using the t, c and f keys to make sure that there isn’t any obstacles between them and the other end of the road. In doing so, they happen to look at a tile on which part of the Humvee is on. thanks to the fact that none of the keys report the existence of the vehicle, and there is no other way to check that a vehicle is present short of actually seeing it, the player never realises that the Humvee is there. The player then starts to cross the street, in which one of two things could possibly happen. The first scenario has the player, by good fortune, just happen to walk into a part of the vehicle which wasn’t a door or other passable tile. Realising that there’s more than likely a car of some description there, the player would try to use screen reader controls to look at the tile as reported by the look around menu when not in the (e)xamining function. This is incredibly tedious and frustrating, as it takes a good few minutes to even just look at one tiny part of the vehicle. Even if the player was to locate key components of the Humvee, such as the controls, get in, understand which side the car is facing, and actually start driving, the inability to see the presents of other cars would inevitably mean the player would sooner or later crash headlong into a car that they can’t even realise is there, until they smash their shiny new Humvee into it and probably die instantly. Scenario two sees the player walk onto a part of the vehicle which was passable, such as a door, in which case the player would primly walk strait through, never even realizing that they had just passed right through a fully working vehicle.
I can say with full confidence that I’ve died more times in the game from trying to mess with vehicles, than as a result of any hostile action. Part of this is due to the fact that sometimes, when running from a monster, the player can get themselves stuck on a vehicle in a reverse kiting manoeuvre, which considering that the creature was so deadly that they were trying to run from it in the first place, more than likely ends in the character ending up deader than my sole when realising I might have calmly strolled right passed a fully armed and stocked military APC with a .50 machinegun mount.

### Solution you would like.

I suggest that, similar to the functionality present when pressing the t, f, and c keys, another key, v seems fitting, would be introduced to report any vehicle parts or appliances present on the selected tile. When pressing this key, a list of all the present vehicle parts would be announced, ideally starting from the base to the top component. For example, if the player looks at a tile which houses the control section of a vehicle, they could press x to enter the look around menu, hit e to go into examining mode, and lastly punch v, which would report something along the lines of, “vehicle name, base component of vehicle (EG) heavy frame, and any other components on that tile in a list (EG, seat, 5-point harness, controles, ETC.)”. In addition, I think it would be a good idea to introduce a new auto notes setting which would automatically mark vehicles on the over map. In this way, a blind player would at least know that something’s there.

### Describe alternatives you have considered.

We’ve got a lot of smart people working on this game. Have we ever considered making eye improving mutagens and CBMs a real thing. Pretty please.

**Comment by Zireael07** [comment]
Nitpick: replace the - mark with a hash (#) to make the issue link pop up automatically.
