### ISSUE TITLE
Game crash when crafting in my base cave, but not elsewhere

### ISSUE THREAD

**Issue by hostergaard** [CleverRaven/Cataclysm-DDA#57543]
### Describe the bug

Game crashes and I get a segmentation fault when I try to craft something (By something I mean anything. No matter what I craft it crashes) in the cave I use as base. If I go outside I can craft just fine. 

Save:

[Pica.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8649927/Pica.zip)

### Steps to reproduce

1. Try to craft anything in the cave
2. Crashes

### Expected behavior

1. Try to craft in the cave. 
2. Successfully craft

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19042.1645 (20H2)
- Game Version: 0a6883a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    XEAS [XEAS],
    Alternative Map Key [alt_map_key],
    Extra Mutated Scenarios [extra_mut_scens],
    Mining Mod [Mining_Mod],
    Mythical Martial Arts [MMA],
    Graphical Overmap [Graphical_Overmap],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Gun Cotton [guncotton],
    DinoMod [DinoMod],
    Innawood [innawood],
    More Survivor Stuff [more_survivor_stuff],
    MSX Black Military Cars [UDP_BlackMilitaryCars]
]

### Additional context

This is an older save I did not play for a few weeks, crashes after I updated it to play again (my old computer died, needed a new one). 
 

I tried various things, deconstructing the table. Crafting other stuff. Different places in the cave. Always crashes.  

Crash report:

The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 0a6883a
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

  #0
    (dbghelp: @0x7ff6caff63e0[cataclysm-tiles.exe+0x2063e0]), 
    (libbacktrace: debug_write_backtrace(std::ostream&)+0x9e@0x1402063e0),
    (libbacktrace: 0x1402063e0    [unknown src]:0    [unknown func]),
  #1
    (dbghelp: @0x7ff6cafdf4f1[cataclysm-tiles.exe+0x1ef4f1]), 
    (libbacktrace: log_crash+0x1d2@0x1401ef4f1),
    (libbacktrace: 0x1401ef4f1    [unknown src]:0    [unknown func]),
  #2
    (dbghelp: @0x7ff6cafdf71f[cataclysm-tiles.exe+0x1ef71f]), 
    (libbacktrace: signal_handler+0x52@0x1401ef71f),
    (libbacktrace: 0x1401ef71f    [unknown src]:0    [unknown func]),
  #3
    (dbghelp: @0x7ff6cb8ddac2[cataclysm-tiles.exe+0xaedac2]), 
    (libbacktrace: gnu_exception_handler+0x182@0x140aedac2),
    (libbacktrace: 0x140aedac2    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc11/gcc-11.2.0.build_/mingw-w64-v9.0.0/mingw-w64-crt/crt/crt_handler.c:224    _gnu_exception_handler),
  #4
    (dbghelp: _C_specific_handler+0x98@0x7ff95d417ff8[msvcrt.dll+0x27ff8]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #5
    (dbghelp: _chkstk+0x11f@0x7ff95e6920cf[ntdll.dll+0xa20cf]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #6
    (dbghelp: RtlRaiseException+0x434@0x7ff95e641454[ntdll.dll+0x51454]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_
[Pica.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8649924/Pica.zip)
pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #7
    (dbghelp: KiUserExceptionDispatcher+0x2e@0x7ff95e690bfe[ntdll.dll+0xa0bfe]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #8
    (dbghelp: @0x7ff6cb3424e7[cataclysm-tiles.exe+0x5524e7]), 
    (libbacktrace: map::use_charges[abi:cxx11](tripoint const&, int, string_id<itype> const&, int&, std::function<bool (item const&)> const&, basecamp*, bool)+0x567@0x1405524e7),
    (libbacktrace: 0x1405524e7    [unknown src]:0    [unknown func]),
  #9
    (dbghelp: @0x7ff6cafcb421[cataclysm-tiles.exe+0x1db421]), 
    (libbacktrace: Character::consume_items[abi:cxx11](map&, comp_selection<item_comp> const&, int, std::function<bool (item const&)> const&, tripoint const&, int, bool)+0xf9@0x1401db421),
    (libbacktrace: 0x1401db421    [unknown src]:0    [unknown func]),
  #10
    (dbghelp: @0x7ff6cafcb6e0[cataclysm-tiles.exe+0x1db6e0]), 
    (libbacktrace: Character::consume_items[abi:cxx11](comp_selection<item_comp> const&, int, std::function<bool (item const&)> const&, bool)+0x70@0x1401db6e0),
    (libbacktrace: 0x1401db6e0    [unknown src]:0    [unknown func]),
  #11
    (dbghelp: @0x7ff6cafbd40f[cataclysm-tiles.exe+0x1cd40f]), 
    (libbacktrace: craft_command::create_in_progress_craft()+0x28b@0x1401cd40f),
    (libbacktrace: 0x1401cd40f    [unknown src]:0    [unknown func]),
  #12
    (dbghelp: @0x7ff6cafce7d8[cataclysm-tiles.exe+0x1de7d8]), 
    (libbacktrace: Character::start_craft(craft_command&, cata::optional<tripoint> const&)+0x64@0x1401de7d8),
    (libbacktrace: 0x1401de7d8    [unknown src]:0    [unknown func]),
  #13
    (dbghelp: @0x7ff6cafbc46d[cataclysm-tiles.exe+0x1cc46d]), 
    (libbacktrace: craft_command::execute(bool)+0x55f@0x1401cc46d),
    (libbacktrace: 0x1401cc46d    [unknown src]:0    [unknown func]),
  #14
    (dbghelp: @0x7ff6cafc11d7[cataclysm-tiles.exe+0x1d11d7]), 
    (libbacktrace: Character::make_craft(string_id<recipe> const&, int, cata::optional<tripoint> const&)+0x11@0x1401d11d7),
    (libbacktrace: 0x1401d11d7    [unknown src]:0    [unknown func]),
  #15
    (dbghelp: @0x7ff6cafc371e[cataclysm-tiles.exe+0x1d371e]), 
    (libbacktrace: Character::craft(cata::optional<tripoint> const&, string_id<recipe> const&)+0x5c@0x1401d371e),
    (libbacktrace: 0x1401d371e    [unknown src]:0    [unknown func]),
  #16
    (dbghelp: @0x7ff6cb13e
[Pica.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8649915/Pica.zip)
a4c[cataclysm-tiles.exe+0x34ea4c]), 
    (libbacktrace: game::do_regular_action(action_id&, avatar&, cata::optional<tripoint> const&)+0x2f0c@0x14034ea4c),
    (libbacktrace: 0x14034ea4c    [unknown src]:0    [unknown func]),
  #17
    (dbghelp: @0x7ff6cb14246e[cataclysm-tiles.exe+0x35246e]), 
    (libbacktrace: game::handle_action()+0xafa@0x14035246e),
    (libbacktrace: 0x14035246e    [unknown src]:0    [unknown func]),
  #18
    (dbghelp: @0x7ff6cb03fa9a[cataclysm-tiles.exe+0x24fa9a]), 
    (libbacktrace: do_turn()+0x533@0x14024fa9a),
    (libbacktrace: 0x14024fa9a    [unknown src]:0    [unknown func]),
  #19
    (dbghelp: @0x7ff6cc2cb5ad[cataclysm-tiles.exe+0x14db5ad]), 
    (libbacktrace: main+0x18fb@0x1414db5ad),
    (libbacktrace: 0x1414db5ad    [unknown src]:0    [unknown func]),
  #20
    (dbghelp: @0x7ff6cadf13c1[cataclysm-tiles.exe+0x13c1]), 
    (libbacktrace: _tmainCRTStartup+0x231@0x1400013c1),
    (libbacktrace: 0x1400013c1    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc11/gcc-11.2.0.build_/mingw-w64-v9.0.0/mingw-w64-crt/crt/crtexe.c:323    __tmainCRTStartup),
  #21
    (dbghelp: @0x7ff6cadf14d6[cataclysm-tiles.exe+0x14d6]), 
    (libbacktrace: WinMainCRTStartup+0x16@0x1400014d6),
    (libbacktrace: 0x1400014d6    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc11/gcc-11.2.0.build_/mingw-w64-v9.0.0/mingw-w64-crt/crt/crtexe.c:178    WinMainCRTStartup),
  #22
    (dbghelp: BaseThreadInitThunk+0x14@0x7ff95d0d7034[KERNEL32.DLL+0x17034]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #23
    (dbghelp: RtlUserThreadStart+0x21@0x7ff95e642651[ntdll.dll+0x52651]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),

**Comment by RoyBerube** [comment]
I've heard that the multicooker can cause problems like this. 

Personally, I wouldn't mind seeing it removed from the game. It creates more trouble than it is worth.

**Comment by hostergaard** [comment]
> I've heard that the multicooker can cause problems like this.
> 
> Personally, I wouldn't mind seeing it removed from the game. It creates more trouble than it is worth.

Appreciate the feedback, issue here tough is that I am doing a Innawood challenge (no civilization) so I don't think I have a multicooker. I do have various other self made equipment to cook with. What more is, it does not matter what I craft, just that I craft in the cave. At first I thought maybe it was that I was using a table to work on it with. Deconstructed table. Still crash. Then I put all the needed stuff in my inventory, in case its cause it was not in my inventory. Still crash.

Here is the save

https://1drv.ms/u/s!AuTeCJswQ5gAiWzqNhRWWDA811Df?e=AjpLvV

**Comment by RoyBerube** [comment]
Thanks for the save upload. I'll take a look at it.

**Comment by RoyBerube** [comment]
@hostergaard  Do you happen to recall when the 4 bloomery and 2 basecamp forge items appeared in the smoker? As in, when the last one appeared there.

That is a bug that might be fixed but am not certain. If they are recent - within the last month on experimental- then the bug still exists.

**Comment by hostergaard** [comment]
@RoyBerube Welcome. Hmm, about... a month or two months back? Can't tell exactly as I simply set them aside, tough its been buggy like that for a while.

Tough, I can tell you that this youtube lets play experienced the same bug somewhere in the middle of the series.

https://www.youtube.com/watch?v=ZH-tg6Z-ajI&list=PLxIQ9fpV90xOclq5QOxzMn6ecVOMVyjy3

I remember he ran into the same bug, tough I can't remember exactly which video, it at least can help track down the time of the bug. Well worth a watch by the way, even if you don't plan on watching it for tracking down the bug.
