### ISSUE TITLE
Evac Center fills up with visitors

### ISSUE THREAD

**Issue by andrei8l** [CleverRaven/Cataclysm-DDA#57549]
### Describe the bug

The visitors from #56940 aren't despawning.

### Steps to reproduce

1. Go to evac center
2. Finish `FMShopkeep_Mission1`
3. Go out of reality bubble
4. Wait a few weeks
5. Go back to evac center

### Expected behavior

Visitors should despawn

### Screenshots

<details>
<summary>Status on my second visit to the evac center</summary>

![Screenshot from 2022-05-08 18-37-15](https://user-images.githubusercontent.com/68240139/167304128-77723293-ae60-45ac-b532-27cd560b9ea1.png)
</details>

<details>
<summary>After waiting 2 days outside the reality bubble, 2 more NPCs spawned and none despawned (except maybe one John Bailey, which was then replaced by another?)</summary>

![Screenshot from 2022-05-08 18-46-12](https://user-images.githubusercontent.com/68240139/167304169-4ef5b237-a6d6-49d2-bfea-2adff1ddc824.png)
</details>

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.F-8162-g9f850de15d-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Slots [cbm_slots],
    No Fungal Growth [no_fungal_growth],
    Massachusetts [MA]
]

**Comment by andrei8l** [comment]
```diff
diff --git a/src/npctalk.cpp b/src/npctalk.cpp
index 003546ea74..76934ea949 100644
--- a/src/npctalk.cpp
+++ b/src/npctalk.cpp
@@ -4325,7 +4325,7 @@ void talk_effect_t::parse_sub_effect( const JsonObject &jo )
     } else if( jo.has_member( "mapgen_update" ) ) {
         subeffect_fun.set_mapgen_update( jo, "mapgen_update" );
     } else if( jo.has_member( "remove_npc" ) ) {
-        subeffect_fun.set_mapgen_update( jo, "remove_npc" );
+        subeffect_fun.set_remove_npc( jo, "remove_npc" );
     } else if( jo.has_member( "revert_location" ) ) {
         subeffect_fun.set_revert_location( jo, "revert_location" );
     } else if( jo.has_member( "place_override" ) ) {
```
I can't PR atm

**Comment by Nerezza** [comment]
So many John Bailey clones.

**Comment by toweroglass** [comment]
> So many John Bailey clones.

A John Bailey spawned next to me in the middle of a field and started talking to me about the refugee center.

Yesterday I woke up to an error about quests and then a "survivor" opened my door and started talking about the refugee center. It seems when the counter is ready to spawn new npcs, it just throws them next to you if you aren't close to the center.

**Comment by andrei8l** [comment]
> A John Bailey spawned next to me in the middle of a field and started talking to me about the refugee center.
> 
> Yesterday I woke up to an error about quests and then a "survivor" opened my door and started talking about the refugee center. It seems when the counter is ready to spawn new npcs, it just throws them next to you if you aren't close to the center.

Please open a separate issue for that. I think it  happens if there's no evac center in your current overmap.

![Screenshot from 2022-05-09 18-15-32](https://user-images.githubusercontent.com/68240139/167441612-491e4001-3ee9-4ef7-8062-63ad1517a9d7.png)

**Comment by Nerezza** [comment]
John Bailey is now the protagonist.
