### ISSUE TITLE
Having mutation as trait dont allow to get another type of this mutations

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#57575]
### Describe the bug

Having mutation as trait dont allow to get another type of this mutations

### Steps to reproduce

- Spawn a character with `Poor Healer` trait (don;t use debug mutate)
- Start a medical mutation sequence
- Find you can't get any healing related mutation

### Expected behavior

Being able to rewrite the trait mutations, as it was before

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1586 (21H2)
- Game Version: c68b9c6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Zireael07** [comment]
@ERRORCODE509 I believe you're right

**Comment by fairyarmadillo** [comment]
> Don't quote me on it, but I'm fairly certain that's intentional. Traits taken on startup are given an additional flag that marks them as a "base trait," which I believe prevents mutations from removing them.

Isn't that both highly gameable and sort of nonsensical? You can easily just take positive traits that prevent you from getting your intended line's negatives.

**Comment by Maleclypse** [comment]
> > Don't quote me on it, but I'm fairly certain that's intentional. Traits taken on startup are given an additional flag that marks them as a "base trait," which I believe prevents mutations from removing them.
> 
> Isn't that both highly gameable and sort of nonsensical? You can easily just take positive traits that prevent you from getting your intended line's negatives.
> 
The issue it was intended to solve is the amount of negative traits that could be removed fairly easily with only a couple mutagens

I imagine there's probably a healthy medium where taking "FRAIL" has some level of impact much of the game while not being a permanent trait but I don't know what it is.

**Comment by Jan-Blasiak** [comment]
> Don't quote me on it, but I'm fairly certain that's intentional. Traits taken on startup are given an additional flag that marks them as a "base trait," which I believe prevents mutations from removing them.

Wait.

I've had my "strong stomach" base mutation removed by 'Alpha' serum.

**Comment by fairyarmadillo** [comment]
> > > Don't quote me on it, but I'm fairly certain that's intentional. Traits taken on startup are given an additional flag that marks them as a "base trait," which I believe prevents mutations from removing them.
> > 
> > 
> > Isn't that both highly gameable and sort of nonsensical? You can easily just take positive traits that prevent you from getting your intended line's negatives.
> 
> The issue it was intended to solve is the amount of negative traits that could be removed fairly easily with only a couple mutagens
> 
> I imagine there's probably a healthy medium where taking "FRAIL" has some level of impact much of the game while not being a permanent trait but I don't know what it is.

But there are already two:

You need to live long enough to get enough mutagen to get rid of it (it isn't easy!) and it comes off in steps. Frail doesn't just turn into tough, you have to roll the tough mutation, which steps frail down into flimsy, then roll it again, which steps it down to nothing, then roll it again, which steps it up to tough. You gain a few hundred instability just from doing that, which negatively impacts your use of mutagens pretty much for the rest of your life.
