### ISSUE TITLE
Vehicle cargo should add all the spaces togeter and make them avialable to all spaces for purpose of calculating available volume

### ISSUE THREAD

**Issue by hostergaard** [CleverRaven/Cataclysm-DDA#57572]
### Is your feature request related to a problem? Please describe.

There is something rather odd with cargo spaces in the game. If you add (numbers not reflecting actual game values, just giving an example) nine 100 liter spaces in a grid on a vehicle, the largest object you can store is still 100 liters in volume. You would expect in real life that you would be able to add at least 900 liter objects (well, more, cause of cubic growth and space above etc etc) to that cargo area. 

This is particularly noticeable when building a primitive wooden cart when building a wooden cart, and the largest cargo space I can make is sub-100 liters. Like, why can't I carry larger items by volume if I have multiple cargo spaces? And to add to that, long items should be able to just stick out the back and not take up cargo space.

### Solution you would like.

I came up with a term to describe my idea; overloading.

Basically, when you build a cargo space adjacent to each other, they all add their volume together for the purpose of how much space is available in total that can be used by any one of the cargo spaces and is debited from them all.

So if I have nine 100 liter spaces connected I can load each with 100 liters, or I can for example load a 900 liter object in one space and that will take all the space in all the connected cargo spaces. 

### Describe alternatives you have considered.

Simply remove volume constraints and let it be balanced by weight alone

### Additional context

Now, there is some considerations to other aspects.

- A large total volume can hold more than several smaller volume of same size by nature of being able to to fit things together better. One could argue there should be a bonus to total space.
- 
- Without a roof, or if the cargo area is open to the back like a pickup truck, one could conceivably pile things very high or let them hang out by the end. One could argue a bonus to total space if this was the case. Tough you could add an requirement for there to be attachments points and ropes to tie it all the things down for this to be the case. 
- 
- To add to that, one could argue that things not tied down in open cargo spaces, would be at risk being flung about in crashes like characters without seat belts. 
- 
- There is something to be said that only item larger than the volume of the space could access the overloading space of the other cargo spaces. So in the example above, a 130 volume item would be able to steal 30 volume from another space, but a 30 volume item in a full 100 space should simply be put in another space. 
- 
- The reason in real life for things like cargo shelves would not be increased space, as you can just pile things up, but rather speed or retrieving items and not crushing things below. A simple solution then is that the benefit that cargo shelving gives is quick retrieval compared to a pile tied down in a cargo space.

**Comment by ZaricaDemoni** [comment]
I feel, compelled to agree to a degree. Something that's bothered me is some items you can irl store in the back of a vehicle, cant be stored. Take a freezer for example, its 900L of volume, yet, there's no way to put this in a vehicle due to volume. If there was a way to force this object to say overload that one spot to where nothing else could fit there with it, it would be nice. Example - flatbed trucks have cargo spots for 500L, so even a flatbed truck can not carry a freezer.

**Comment by hostergaard** [comment]
Yeah, for me its playing an innawood challenge and realizing that no matter how big a wooden cart I made the largest object I could have in the cart was... 75L I think? Travois being the largest wooden cargo I can make I think. Can't remember precisely. Just tough that maybe there should be a way for large carts to lug about large item.

**Comment by harmonickolobok** [comment]
We already have some multitile doors that open/close simultaneously if you interact with any of their tiles. Would it be possible if we have a single "space" that would just be accessible from any tile of the connected cargo spaces? That space would have size of sum of all cargo space sizes. As a starter bug prevention we could prohibit uninstalling any of the cargo spaces while that unified space isn't empty.
P.S. To somewhat mitigate improved access for items(from any cargo space tile) - move cost of getting an item can depend on fullness of this space.
