### ISSUE TITLE
Segmentation fault in `Interface`/`Debug` options

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#57590]
### Describe the bug

There is a segmentation fault in `Interface` and `Debug` option while using `page down` button

### Steps to reproduce

- open the `Options`
- move to `Interface` or `Debug` settings
- press `page down` for a bunch of times
- segmentation fault

### Expected behavior

Not having the segmentation fault

### Screenshots

![image](https://user-images.githubusercontent.com/67688115/167486079-3d11f77f-bf4a-4c79-b8a7-bb376333a096.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1586 (21H2)
- Game Version: 6779b81 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

I dont really know is it my pc or is it a real bug
`page up` works fine
also its not related to the world, the bug can occur right from the main menu

**Comment by NetSysFire** [comment]
>I dont really know is it my pc or is it a real bug

I can reproduce. This is a fun bug.

**Comment by RoyBerube** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/0e97f8b5308ffbdc1060e27c6163341e5bcdb9e5/src/options.cpp#L2893

Array out of bounds. Trying to get element 63 - iCurrentLine - of a size 56 array.
