### ISSUE TITLE
Magiclysm and the Exodii

### ISSUE THREAD

**Issue by keampe** [CleverRaven/Cataclysm-DDA#57595]
### Is your feature request related to a problem? Please describe.

With the Exodii coming in to be the sole source of CBM's, Magiclysm is going to have some lore problems.
These being:
 - The Blood Power CBM
 - The Technomancer spell the use Bionic power to fuel.

With no CBM's in the world before the Exodii arrive, these should not exist.

### Solution you would like.

I can see 3 solutions for this:

1. Remove them from the game. Makes me a sad panda, but it would work.
2. Give all these to the Exodii merchant. They've travelled through many dimensions, not too hard for them to have run across magic before.
3. Change the power source for those Technomancer spell and either remove the CBM or give it to the Exodii merchant.

Not sure which is best TBH.

 - Shane

### Describe alternatives you have considered.

Leaving the weirdness in the game and not explaining it.

### Additional context

Occurs to me that other mods may have similar problems, and that Manatricity should be added to the list of spells.

 - Shane

**Comment by keampe** [comment]
Just in to say that I'm willing to do the work, I just need to know which way to go in terms of the PR.

   - Shane

**Comment by catdach** [comment]
I think it's fine the leave things where they are, _for now_ at least. It doesn't seem too far fetched to say that mages got their hands on CBMs through some magical-interdimensional-anomaly shenanigans, and that techno/bio-mancers have been experimenting with new CBM designs and new spells that synergize with them. (and maybe some form of bio-magical installation). Alternatively, these might be extremely recent inventions from technomancers who did some trading with the Exodii almost as soon as they arrived. It really can go in alot of directions and isn't _super_ difficult to explain lore-wise, So I would honestly leave this stuff until maybe the Exodii themselves are more fleshed out. 

Of the other options; scraping **everything** involving bionics from Magiclysm would be a shame. _Moving_ everything possible (attunement related stuff might be an issue?) to be sold by the Exodii merchant seems very boring. 

Regardless, there are what? **2** CBMs? and a **handful** of related spells? So I'm not sure how much it's worth doing anything in this area unless you also plan on expanding it.

**Comment by GuardianDll** [comment]
Another good option is to replace the name of the and/or replace the installing by autodoc and use some another tool. This will allow us to not be depended to exodii lore, and we could use the cbms in any another places, as a separate magic technology (even its still a cbm in code)
