### ISSUE TITLE
Power Armor Hauling Frame Cannot Be Equipped

### ISSUE THREAD

**Issue by GexitheHundredth** [CleverRaven/Cataclysm-DDA#57610]
### Describe the bug

Version: a2ea872
Build 2022-05-10-1434

Tried wearing the Hauling Frame with the Heavy PA and it said I could not wear it over PA. Used debug to try all the other PA types but I still could not equip it.
I also did a bit of research and apparently a similar bug happened in 2020 that was "caused by #40866" with the line being <src/character.cpp:3012 - if( elem.get_covered_body_parts().make_intersection( it.get_covered_body_parts() ).any() &&> and <body_part_set::make_intersection()> screwing up.

Edit:
I found that this is the error that is most likely the cause:
 ```
DEBUG    : Missing item definition: power_armor_frame_on

 FUNCTION : const itype* Item_factory::find_template(const itype_id&) const
 FILE     : src/item_factory.cpp
 LINE     : 2321
 VERSION  : 064ac27
```

### Steps to reproduce

1. Obtain and install Power Armor CBM
2. Equip any Power Armor
3. Go to equip Power Armor Hauling Frame
4. It says you can't wear it over power armor

### Expected behavior

I expected it to be equipable because it is a Power Armor component and the helmet is equipable.

### Versions and configuration

Windows x64 (64 bit)
Version: 064ac27
Build 2022-05-10-2025

**Comment by GexitheHundredth** [comment]
Update: I appear to be missing item definitions for my power armor components. Hope that can help

**Comment by Maleclypse** [comment]
@Drew4484  Has this been fixed in any of the recent PA PRs?

**Comment by Drew4484** [comment]
> @Drew4484  Has this been fixed in any of the recent PA PRs?

Not that I'm aware of, my only recent change to the core power armor was #58134, which worked at testing.
