### ISSUE TITLE
Empty and unsupported 2nd floor in motel

### ISSUE THREAD

**Issue by ggttttggggtt** [CleverRaven/Cataclysm-DDA#57620]
### Describe the bug

I found a motel with a strange unsupported floor.

### Steps to reproduce

1. Look for motels
2. Floor might be weird

### Expected behavior

This doesn't seem like intended generation.

### Screenshots

![image](https://user-images.githubusercontent.com/87790164/167745209-4d8ba296-749a-471b-b6c9-908010be1299.png)
![image](https://user-images.githubusercontent.com/87790164/167745305-5602e574-86e7-4630-a15e-9e6c6bce9881.png)
![image](https://user-images.githubusercontent.com/87790164/167745687-fb521373-0364-474b-90ec-548e451aeff5.png)

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: c228b98 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Maleclypse** [comment]
@casswedson I think the S1 label is no longer appearing on bug issues.  Is that intentional?

**Comment by casswedson** [comment]
Ah, right I didn't say anything about it, did I? I tested it in this issue https://github.com/casswedson/issue-labeling/issues/12 it labels stuff automatically using the author's authentication or whatever, and here it does label the issue as S1 I don't _think_ it needs anything special to work, seems like a good old case of it not liking the cdda repo

I don't mind reverting #57534 it would fix things for sure, I don't mind either way

**Comment by Maleclypse** [comment]
Weird. Um I'm going to tag in @akrieger and @dseguin because their understanding of Github actions far surpasses mine and they may have ideas beyond reverting it.

**Comment by dseguin** [comment]
> Weird. Um I'm going to tag in akrieger and dseguin because their understanding of Github actions far surpasses mine [...]

No idea what's going on there. Even weirder that the `<Suggestion / Discussion>` label is working fine. I can only remotely guess that it might be some kind of conflict with another action. Not sure I can be much help beyond that :P

**Comment by akrieger** [comment]
Lets move the tagging discussion to #57629
