### ISSUE TITLE
Wall wiring not available for most constructed base camp walls

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#57627]
### Describe the bug

Wall wiring for appliance grids only support a limited set of walls. Unfortunately, most of the construction materials available to faction camps are ones NOT supported (as I found out trying to reveal wall wiring from metal walls).

### Steps to reproduce

1. Construct base camp buildings out of metal.
2. Try to extract wall wiring from the walls.
3. Find it doesn't work and try to figure out why.

### Expected behavior

Support wall wiring from all faction camp construction materials, or at least give a clear warning that most materials don't support that.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1645 (21H1)
- Game Version: 0.F-8256-g2d03a277c3-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Wall wiring is supported if the flag "WIRED_WALL" is present in the terrain specification for the wall.
Here's a list of constructed walls that don't support wiring:
- t_adobe_brick_wall
- t_wall_metal_corrugated
- t_scrap_wall
- t_wall_wattle
- t_junk_wall
- t_wall_rammed_earth
- t_wall_dirt
- t_wall_resin

I believe scrap, wattle, junk, rammed_earth, and resin are used for faction camps.

While it makes sense for some materials not to have wiring (and for base camp construction not install wiring as there's no wire in the construction recipes), it needlessly penalizes some base camp material choices. If some materials are deemed not suitable for it for realism reasons the player ought to be notified about it.

**Comment by bombasticSlacks** [comment]
I will extend this also applies to LMOE shelters which have a number of non wired walls.

A combination of allowing exterior wiring construction and differentiating player made vs found walls seems sensible.

**Comment by PatrikLundell** [comment]
In the list above (made by looking at the JSON file), I didn't include any of the walls that were indicated to be damaged, as it would make sense that walls that are sufficiently damaged wouldn't have working wiring.

I definitely think the long term solution would be to allow the player to add wiring, but I don't know how hard that would be to implement. An indication (apart from the revealing action being greyed out) that there isn't any wiring in the walls would be good.
I also think wall construction options with and without wiring ought to exist, which I think means each constructible kind of wall would need to exist in two variants (differentiating via flags probably won't work, as only the terrain is stored, not flags).

**Comment by fairyarmadillo** [comment]
Can walls use copy-from? That would make the solution pretty simple.

**Comment by Maleclypse** [comment]
What about adding "conduit wiring" or something else as an additional construction option to walls that aren't appropriate for wiring to be inside of them.
