### ISSUE TITLE
Minimum vehicle speed too high and also inconsistent

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#57639]
### Describe the bug

When trying to carefully drive a vehicle at minimum speed to handle delicate situations the vehicle sometimes moves two tiles rather than one, resulting in collisions.
Also, the minimum speed from stand still is 6 km/h, while the "minimum" speed from a reasonable marching speed is 8 km/h, i.e. reducing a high speed has a last speed step before 0 being 8 km/h.

Note that I'm talking about the speed set by the player: the actual speed can differ from this for various reasons, which is not an issue.

### Steps to reproduce

1. Start a vehicle from stand still and increase the speed one step (resulting in 6 km/h set as the target speed).
2. Move straight forward one tick at a time. Note that you sometimes moves two tiles in a tick rather than 1.
3. Accelerate to somewhere around 50 km/h.
4. When reaching the target speed, reduce it down to the lowest non zero step. Note that it's higher than the one you get when increasing speed from zero. This seems to increase the rate of unexpected two tile movements, although I haven't measured it beyond casual observation.

### Expected behavior

Minimum set vehicle speed should be exactly one tile per tick both when accelerating from zero and decelerating from all higher speeds.

### Versions and configuration

It's been this way for a long time...

- OS: Windows
    - OS Version: 10.0.19043.1645 (21H1)
- Game Version: 30c8dc3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
+ JSON addition of Wind Mill to workshop 2 blacksmith recipes.
+ JSON "mod" to disable portal storms as the PR that provided such a mod was rejected.

### Additional context

Two comparatively recent changes have increased the problems with this issue somewhat:
- Vehicle repair now uses up huge numbers of welding consumables (and some repairs have used rare consumables for a long time already).
- Vehicle damage not being fully repairable means parts have to be replaced eventually.

**Comment by toweroglass** [comment]
maybe this is due to how mph is converted to km/h? I've literally never had this happen ever using miles.

**Comment by PatrikLundell** [comment]
As far as I know the display settings are just that. They'd be subjected to rounding, of course, but that should be it. If a tick is a second and a tile is 1 meter, the minimum speed ought to be set to exactly 3.6 km/h. Also, I believe the internal system is essentially metric, so if anything WOULD be off it would be the random unit one.
However, if you engage in precision parking (e.g. exactly one tile away from a wall, or exactly one tile away from a vehicle you intend to tow) you'll probably eventually find that you might not just make minor mistakes.

**Comment by toweroglass** [comment]
I've literally never jumped two tiles when driving at minimum speed. if you are trying to maneuver left and right to line it up that might be a different animal, but I rarely come to a crawl in non cardinal directions.

**Comment by PatrikLundell** [comment]
I'm talking cardinal directions. If anything, non cardinal ones would have a lower probability of moving further than expected, as some of the velocity is redirected sideways.

When trying to squeeze through tight spots I frequently move at minimum speed in non cardinal directions, but, as mentioned, it's a different use case.

**Comment by RoyBerube** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/2bdeed8bc5cdba267ad97b53f96108e21bc0513f/src/vehicle_move.cpp#L1430

That is the cause of the extra speed, I believe. Each tile per second equates to 400 velocity. I'm not sure what this is for, but it retains the extra 100 velocity when slowing down from a high speed.
