### ISSUE TITLE
 Toad in a hole vs Egg in a basket, a food item situation noticed by an English friend

### ISSUE THREAD

**Issue by ZaricaDemoni** [CleverRaven/Cataclysm-DDA#57638]
### Is your feature request related to a problem? Please describe.

This ended up in a oddly confusing and interesting discovery about IRL foods, because Toad in a Hole (in-game), is an Egg in a basket, which is normal, they share the name IRL, however, there's another meal called Toad in a Hole, that has nothing to do with Egg in a basket. Toad in a Hole, is also a classic English dish, comprised of pork sausages laid inside of Yorkshire pudding in a casserole dish.

### Solution you would like.

Simply renaming Toad in a Hole to be Egg in a Basket, would help some localisation, plus would open up the original name for its proper English counterpart incase more food recipes get added later.

**Comment by Maleclypse** [comment]
Resolved in #57722
