### ISSUE TITLE
can't start a new game

### ISSUE THREAD

**Issue by yaunut** [CleverRaven/Cataclysm-DDA#57647]
### Describe the bug

can't start a new game
debug log attached

### Steps to reproduce

trying to get started with these mods
![1](https://user-images.githubusercontent.com/51860240/168120589-b1b827b0-903a-48cc-8682-181f3b28bbf6.png)
log
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8680882/debug.log)
s

### Expected behavior

the game returns to the menu

### Versions and configuration

os - WIN10
version 7a89bbe (tiles)
bild 2022-05-12-0506

**Comment by Night-Pryanik** [comment]
According to debug log you provided, the error is caused by third-party mod, namely `nocts_cata_mod-0.D`. Honestly it's no wonder it throws error, as seems like it's supposed to work on 0.D, which is HEAVILY outdated as for now.
We don't fix errors related to third-party mods, your best bet is to ask mod's author to resolve errors and/or update the mod to current versions.

**Comment by ERRORCODE509** [comment]
Looks like you're trying to use Lua mods too. Lua support was dropped awhile ago and no longer functions. Considering the mods that I can do you have installed, it looks like you downloaded a bunch off of the launcher. Don't use those, most of them no longer function. The mods on the Catapult launcher are actively maintained (last that I checked) and are much more likely to work.

**Comment by yaunut** [comment]
> Похоже, вы тоже пытаетесь использовать Lua-моды. Поддержка Lua была прекращена некоторое время назад и больше не функционирует. Учитывая моды, которые, как я вижу, вы установили, похоже, что вы скачали кучу с лаунчера. Не используйте их, большинство из них больше не функционируют. Моды на Catapult launcher активно поддерживаются (последнее, что я проверил) и с гораздо большей вероятностью будут работать.

maybe you have a link to Catapult launcher?

**Comment by ERRORCODE509** [comment]
> maybe you have a link to Catapult launcher?

Yep, here you go: https://github.com/qrrk/Catapult

**Comment by yaunut** [comment]
> > может быть, у вас есть ссылка на Catapult launcher?
> 
> Да, вот так: https://github.com/qrrk/Catapult

Thanks, I'll check it out
