### ISSUE TITLE
I'm wearing Apis as a skin-suit

### ISSUE THREAD

**Issue by Boonlike** [CleverRaven/Cataclysm-DDA#57646]
### Describe the bug

After killing Apis she dropped her mutated bug armor as loot. I was able to wear it and it's now permanently attached to me.

### Steps to reproduce

1. Find Apis
2. Kill Apis
3. Wear Apis' skin
4. Become Apis

### Expected behavior

I expect to not be able to just take Apis' skin armour and wear it. At the very most I would expect to be able to butcher her for chitin.

### Screenshots

![image](https://user-images.githubusercontent.com/84247285/168117133-3c59a069-9838-48f7-94b9-8f1de723fa2a.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1645 (21H2)
- Game Version: 1d42ceb [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    Alternative Map Key [alt_map_key],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

Also, the sclerotin plate doesn't have the "PADDED" flag, I don't know if that was intentional or not.

**Comment by fairyarmadillo** [comment]
Epicuticle has padded so sclerotin plate doesn't need it, as there's normally no way to have the latter without the former.

**Comment by Boonlike** [comment]
> Epicuticle has padded so sclerotin plate doesn't need it, as there's normally no way to have the latter without the former.

Ah, gotcha. Definitely skipped a few steps on my way to becoming a bug man. I'll probably de-bug (ha) the armour off next time I play.

**Comment by fairyarmadillo** [comment]
Sorry, I meant to say that epicuticle has SOFT. Same difference, but it might matter to anyone reading this.
