### ISSUE TITLE
Picking up items can put them into a wielded corpse

### ISSUE THREAD

**Issue by aleksandrtikh** [CleverRaven/Cataclysm-DDA#57643]
### Describe the bug

When the character is wielding a corpse while having no other inventory space, picked up items will get put inside the corpse. While a corpse is wielded, you can see increased volume in the inventory screen.

### Steps to reproduce

1. Have no free inventory space
2. Wield a corpse
3. Try to pick up an item via 'g' or advanced inventory manager.

### Expected behavior

Should not be able to store picked up items inside a corpse, as they normally can't be used as containers.

### Screenshots

![image](https://user-images.githubusercontent.com/39463222/168042669-80109ab6-7750-42a2-9546-78a1002c65f2.png)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 7a89bbe [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Maleclypse** [comment]
Turducken

**Comment by tornikeo** [comment]
We need to add a *sqwearell*. A high capacity wearable squirrel corpse.

**Comment by Night-Pryanik** [comment]
Can't confirm on latest experimental as of 22 October 2024.

I have no free inventory space and I'm wielding a corpse of a crow.
![изображение](https://github.com/user-attachments/assets/149ec8a3-8134-4d54-8058-f18e99a38833)

I'm trying to pickup something. The game says I have no pocket to hold anything.
![изображение](https://github.com/user-attachments/assets/a0b62b63-ad0f-4a3d-a892-7c69cab5b368)

Closing until reconfirmed.
