### ISSUE TITLE
Hallucination Fungal enemies can still cause fungal parasites.

### ISSUE THREAD

**Issue by 9600bauds** [CleverRaven/Cataclysm-DDA#5765]
After starting a run as Hobo, I found myself hallucinating from alcohol nearly constantly.
By the end of day two, I was suddenly struck by a Fungal parasite, even though I had never visited a fungal spire or seen any real Fungaloids in the city. The only explanation I can think of is that a hallucination Fungal enemy caused the parasite.

EDIT: I should clarify that this was a fungal spore "disease", not an infection on a limb.

**Comment by mugling** [comment]
Closed without confirmation at 2 years
