### ISSUE TITLE
Sassafras Trees and craftable root beer

### ISSUE THREAD

**Issue by Benny-Bear** [CleverRaven/Cataclysm-DDA#57658]
### Is your feature request related to a problem? Please describe.

As somebody who lives in Texas I don't know much about sassafras trees, but from my research they are native to NE and surrounding areas if somebody lives in areas with these trees feel free to correct me.  "A deciduous tree (or shrub) native to North America, growing sassafras trees can grow to 30 to 60 feet tall by 25 to 40 feet wide"

A use of these trees is the production of root beer and is how it was traditionally made.
A recipe for root beer that I found is:

![image](https://user-images.githubusercontent.com/29996039/168167301-afe191cf-9bcd-4719-a7d7-18f6e57a39a7.png)
Said recipe makes 10 servings or 2 1/2 Quarts and takes roughly 40 minutes.
It seems the preferred roots to use for root beer are of saplings of 1-2 years old, but I couldn't find anything saying older tree roots couldn't be used.
Kevin has commented on discord of how to sub for the soda water:

![image](https://user-images.githubusercontent.com/29996039/168167589-debb5ae3-0c07-4498-a48a-2533c4114985.png)

Another interesting way to use these trees from my research is you can apparently make MDMA out of them. I didn't look into the specifics because we don't even have MDMA in the game but its a possibility.

### Solution you would like.

1. Sassafras trees generating in forests
2. Extracting the roots from them
3. Crafting root beer

More variety of native trees are always nice.

### Describe alternatives you have considered.

Not having 200L tanks of root beer

### Additional context

Source of recipe
https://www.simplyrecipes.com/recipes/homemade_sassafras_root_beer/

**Comment by kevingranade** [comment]
When I said do that to carbonate,  I meant add that to the whole batch. Just sugar,  water and yeast is not going to make a usable seltzer water AFAIK.

Basically add yeast to the recipe you have and it needs a fermentation step, but just a day or two.
