### ISSUE TITLE
Some dehydrated fruit are named, and some are not

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#57650]
### Describe the bug

Bug or feature request?

When you dehydrate fruit, you sometimes end up with it being described by name, and sometimes just as dehydrated fruit.
It would be good if all dehydrated fruit was named so you can see what it actually is.

### Steps to reproduce

1. Dehydrate various kinds of fruit
2. Find that some are named and some are not.

### Expected behavior

All of them would be named.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1645 (21H1)
- Game Version: 30c8dc3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

As far as I can tell, the reason for this is that fruit_dishes.json lists a set of fruit in the dehydration recipe (as well as in a bunch of other recipes), and there is a similar logic in veggy_dishes.json.

Thus, it ought to be a simple matter of transpiration to find the various kinds of fruit and veggies that exist and extend these lists. The question, though, is whether there are any that shouldn't be included.

I've found that popcorn kernels can't be smoked, but have to be dried "manually" (there's a recipe for it), and that's probably because popcorn_raw in raw_veggy.json) doesn't have the "SMOKABLE" flag (why? the recipe lists char_smoker as a tool. An oversight that should be corrected?). Are there other flags that determine whether fruit/veggies can be processed by the various recipes in x_dishes.json?

**Comment by Maleclypse** [comment]
It’s an easy fix just adding conditional names I believe?

**Comment by PatrikLundell** [comment]
The actual work is easy.

The hard part is to know whether anything should be excluded (and why). The popcorn mentioned above is the example of an exemption I've found, but don't understand whether its intentional or just an oversight. Unless someone has an argument for why it's intentional I'll assume it's just something that's fallen by the wayside during development.
