### ISSUE TITLE
Aiming view cone breaks or locks sometimes

### ISSUE THREAD

**Issue by stubkan** [CleverRaven/Cataclysm-DDA#57652]
### Describe the bug

The viewing angle you can see when you aim breaks sometimes.

Bug 1 
When you are standing still or trying to shoot from a vehicle, the view does not update.  You can drive around, change your held gun to a spear for example, and until you walk - the view stays aim restricted.

Bug 2
Sometimes the view randomly goes to a small circle when you shoot, instead of an aiming arc - cutting your view off from the target, and breaking the firing process.

### Steps to reproduce

Bug 1
Sit on a bicycle and shoot a gun. Ride around with broken view angle.

Bug 2
Also, dont know how to reproduce the 2nd bug, it just seems to randomly happen when I am firing a gun, the view shrinks to a small perfect circle and the monster you are aiming at disappear from view, breaking your aim process.

### Expected behavior

The view calculation should update dynamically with each game tick/action, not seemingly when you walk only. 

### Screenshots

Bug 1 -Aim view does not update when you do not move with your legs.  For example, when you are driving around.
![wielding different things doesnt stop it](https://user-images.githubusercontent.com/34361592/168145693-ef8c57bf-330c-437b-8e42-7adae7970952.png)

Also, the aim-modified view angle seems to move with you with long intervals, so you get strange behaviour, such as riding your bicycle into darkness.
![image](https://user-images.githubusercontent.com/34361592/168149084-023514d6-4a5a-4dab-bb47-7c1219a4bf04.png)

Bug 2 - Aiming randomly gives you a small circle, breaking your aiming process when aimed enemy is outside it.
![aiming circle fucks up and loses target](https://user-images.githubusercontent.com/34361592/168145403-c3b4f8cb-6b06-4f88-9aa4-55f64968309d.png)

Just lost another target here in the middle of firing, by the view going to a circle.  I think it is the max aiming viewing angle being too extreme and making everything go dark, because the arc is too narrow?
![image](https://user-images.githubusercontent.com/34361592/168149020-1e5b13f4-ea07-4d00-8928-586cc37905d5.png)

### Versions and configuration

Latest Experimental
- OS: Linux
    - OS Version: Distributor ID: Linuxmint; Description: Linux Mint 20.1; Release: 20.1; Codename: ulyssa; 
- Game Version: 57d911c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    SpeedyDex [speedydex]
]

**Comment by stubkan** [comment]
Also, the aim-modified view angle seems to move with you with long intervals, so you get strange behaviour, such as riding your bicycle into darkness.  See attached picture

![driving aim wrong](https://user-images.githubusercontent.com/34361592/168146626-69e768f0-df51-47aa-a10a-cebbcc20a6a8.png)

**Comment by PatrikLundell** [comment]
Essentially #57537

**Comment by stubkan** [comment]
Ah. I searched, couldnt find any, thanks. 

Unsure if I should remove this one because that Issue does not mention Bug 2 here though, the fov view disappearing, becoming small circle, stopping you from shooting things outside it.
