### ISSUE TITLE
Moving the furniture delete poured liquids

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#57657]
### Describe the bug

If you move furniture on the poured liquid, it would be deleted.

### Steps to reproduce

1. Spawn a chair
2. Pour some liquids nearby
3. Move the chair onto the liquid
4. The liquid is gone

### Expected behavior

Liquid is still here

### Screenshots

![GIF 12 05 2022 22-13-34](https://user-images.githubusercontent.com/67688115/168161302-2e7a32bd-274c-4cd9-9c2f-102ea8d99135.gif)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1586 (21H2)
- Game Version: 6779b81 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

The mop is dead. Long live the mop.

**Comment by Night-Pryanik** [comment]
This is intended behavior.
