### ISSUE TITLE
Attempting to to holster an item you are wielding into a pocket that has been whitelisted for another item deletes it

### ISSUE THREAD

**Issue by toweroglass** [CleverRaven/Cataclysm-DDA#57664]
### Describe the bug

I have a survivor harness with a mace assigned to it. i was wielding a rifle whilst my mace was not in my inventory. when i tried to put the rifle away i instinctively inserted it into the harness holster and got the following error:

 DEBUG    : tried to put an item (ruger_mini, amount -1) in a container (survivor_vest) that cannot contain it

 FUNCTION : fill_with
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\item.cpp
 LINE     : 11695
 VERSION  : aa6a7f8

and the ruger mini-14 was completely gone.

### Steps to reproduce

1. create a character with a survivor harness, a mace and a rifle (don't think the specifics matter but haven't tested it much further).
2. in auto pocket pickup settings assign the holster in the harness with 'i'
3. leave the holster empty and wield the rifle.
4. holster the rifle using 'w'
5. choose the survivor harness
6. yeet your rifle into the abyss
7. regret.

### Expected behavior

I would expect the game would allow me to override my setting when i choose the holster. worst case tell me i've disallowed that pocket.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1645 (21H2)
- Game Version: aa6a7f8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    No Fungal Growth [no_fungal_growth]
]

**Comment by Hirmuolio** [comment]
Most likely related to #56609

**Comment by toweroglass** [comment]
> Most likely related to #56609

I'm glad i tested it in a new save. i tried everything to make it happen again and 100% it was because it was reserved for another item.

**Comment by Heaper327** [comment]
The bug still exists in this week's build (da364ef):
[bugged.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8825178/bugged.zip)
Try to holster the FN57 in the shoulder holster and observe how it vanishes.

**Comment by Night-Pryanik** [comment]
Can't reproduce on 0.F-8778:
![изображение](https://user-images.githubusercontent.com/11132525/171664241-25840e30-5f41-489e-b094-621204470ee8.png)

**Comment by Heaper327** [comment]
> Can't reproduce on 0.F-8778:
> ![изображение](https://user-images.githubusercontent.com/11132525/171664241-25840e30-5f41-489e-b094-621204470ee8.png)

I found out why I still have this bug. The PR that fixed this bug was only integrated into the build today, so my build did not include it.

**Comment by toweroglass** [comment]
I haven't been staying current because I'm playing with non-integrated mod(s), but now I'm tempted to because I would love to stop debug-spawning new items in when i accidentally delete them. Maybe I'll backup my save and give it a go.
