### ISSUE TITLE
A setting to reduce, or disable entirely, the vertical noise propagation. 

### ISSUE THREAD

**Issue by Sinistrem** [CleverRaven/Cataclysm-DDA#57678]
### Is your feature request related to a problem? Please describe.

Any loud noise (screamer, gunfire, mutant barks, etc.) sends all floors of any multi level complex into furniture smashing, wall destroying madness. This is especially noticeable in TCL with its multiple floors, high enemy density, and a wide array of noise sources.

Just getting to its subway level and triggering a screamer caused a single turn to start taking up to 4 seconds of real time. This is also followed by massive cave ins and level architecture destruction, it's not unusual to see entire new "rooms" dug up by multiple hulks / skeletal juggernauts. 

This also turns many carefully designed rooms into craters filled with rubble, generally making looting less enjoyable, not to mention damage to the majority of key card readers, making keycards/hacking worthless as you are forced to just demolish walls instead.

### Solution you would like.

Implement a z-level noise limiter/disabler for those of us who would prefer performance, the ability to use keycard readers, as well as being able to enjoy the aesthetics intended by the map maker over the realism of vertical sound spreading.

### Describe alternatives you have considered.

Toning down the wall smashing behaviour of zombies (especially the hulk and juggernaut variants), making zombies ignore certain types of ambient sound sources (i.e. barking or mutant shouts), making card readers sturdier / less likely to be attacked by Zs. Changing enemy composition in such places to feature less "loud" zombie types (screechers, boomers, other exploding enemies). I lack technical knowledge about the intrincites of this game's inner workings, but basically anything to reduce the severe lag and wide spread map destruction in endgame multi-level complexes, especially after a long period of zombie evolution.

### Additional context

None.

**Comment by Maleclypse** [comment]
So you may have an actual issue here but I’m closing this since it’s a feature request that won’t ever happen.
