### ISSUE TITLE
Several BM security drone lag issues.

### ISSUE THREAD

**Issue by Sinistrem** [CleverRaven/Cataclysm-DDA#57680]
### Describe the bug

BM security drone causes immense lag on multiple occasions. 

1. Scanning the player without a correct zone badge. The drone will keep scanning and calling security every single turn, causing lag until killed or until you acquire a badge.

2. Scanning unseen hunter. I'm not sure whether there may be any other enemies causing it, but for some reason a BM security drone was repeatedly scanning an unseen hunter (see screenshot). This was enough to cause tremendous lag, enough to completely freeze every single zombie on the floor, allowing you to walk around killing everything. Not that you would be happy about it, since it caused a single turn to take multiple real life seconds.

### Steps to reproduce

For the first issue:

1. Enter TLC without any zone badges.
2. Approach a BM drone.
3. Start skipping turns.

For the second issue, I'm not sure about how to reproduce it due to the weird circumstances surrounding it (it began couple turns after I first entered the floor containing the drone, and persisted until I accidently found and killed it). Perhaps spawning a drone and an unseen hunter near each other will do the trick.

### Expected behavior

1. Drone would scan you once, call the security if needed, and flee if approached (I assume it is supposed to behave similarly to eyebots)

2. Drone either shouldn't scan non-player entities, dispatch security on sight or scan them once before dispatching security.

### Screenshots

![Unseen](https://user-images.githubusercontent.com/104842796/168402388-3297a93e-e8f1-4caf-9fcf-f79cfc8b224c.png)

### Versions and configuration

- WIndows 10
- Latest experimental -7c0b8b2
- Tiles
- English
- Mods: dda, no npc food, no_fungal_growth, package_bionic_professions, blazeindustries, generic_guns.

**Comment by PatrikLundell** [comment]
My experience is that they scan you every turn regardless of whether you have a badge or not, causing lag until you hunt them down and destroy them. The only difference is that they'll call security if you don't have a badge, but they'll soon run out of security to call (in each particular area).
And yes, they scan zombies every turn as well, increasing the lag when zombies are present.

**Comment by toweroglass** [comment]
I've noticed this many times but don't know how to specifically reproduce, but occasionally all zombies and drones will freeze while they continuously scan you. the only way to break this sort of spell is break line of sight between yourself and the drone.

**Comment by Jan-Blasiak** [comment]
absolutely /confirmed

My lab run was sometimes seriously painful

**Comment by ZaricaDemoni** [comment]
Ive noticed it with the large drones on the lower floors, they can scan you multiple times per tile movement causing extremely slow game-play especially if 2 of them spot you in a lit area from a distance. I've had the smaller ones on the ground floor only scan me once, and then leave but the larger ones seem to not stop scanning, whether they call security or not. 

Note - Labs tend to just have slow turns periodically from amount of stuff in them, try looking for a room full of nothing but slimes, Jan, as that was the secondary culprit for my lab issues.
