### ISSUE TITLE
Scrolling the options menu can crash the game

### ISSUE THREAD

**Issue by FredrIQ** [CleverRaven/Cataclysm-DDA#57686]
### Describe the bug

Scrolling the options menu down with the menu cursor on a particular item can crash the game. I believe this to be an off-by-1 issue with scrolling to the bottom of a menu.

### Steps to reproduce

* Open a terminal with dimensions 112x30
* Press t to access Settings
* Press o to access Options
* Press arrow down, meaning the cursor is now on line 3 (Auto pickup enabled)
* Press Page Down thrice. Cursor will move to 15 (Dangerous pickups), then 27 (Autosave), then crash

### Expected behavior

The game will not crash, instead the cursor will place itself on the bottom option (37: DeathCam). The reason why I expect this result is that ideally you shouldn't be able to crash the game.

### Versions and configuration

I didn't see a way to check version in-game (I just decided to try the game out and thus haven't actually started a game yet), but I am using the package in the Archlinux repos, and the package version is denoted as "0.F.3-2". I am playing in terminal through tmux.

### Additional context

The crash gave the following terminal output:

tl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = cata::optional<std::__cxx11::basic_string<char> >; _Alloc = std::allocator<cata::optional<std::__cxx11::basic_string<char> > >; std::vector<_Tp, _Alloc>::reference = cata::optional<std::__cxx11::basic_string<char> >&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.
      Aborted (core dumped)

I had no crash.log, and the debug.log doesn't seem to contain anything useful. But I'll post it below anyway.

-----------------------------------------
08:21:11.233 : Starting log.
08:21:11.233 INFO : Cataclysm DDA version 0.F
08:21:11.235 INFO : [main] C locale set to en_US.UTF-8
08:21:11.235 INFO : [main] C++ locale set to en_US.UTF-8
08:21:11.235 WARNING : opendir [/usr/share/cataclysm-dda/sound] failed with "No such file or directory".
08:21:11.271 WARNING : opendir [/usr/share/cataclysm-dda/gfx/] failed with "No such file or directory".
08:21:11.271 INFO : [options] C locale set to en_US.UTF-8
08:21:11.271 INFO : [options] C++ locale set to en_US.UTF-8
08:21:11.272 INFO : Setting language to: 'en'
08:21:11.272 INFO : Language is set to: 'en'

**Comment by ZeroInternalReflection** [comment]
I can confirm this behaviour in the current arch package, but everything seems to work correctly in the latest experimental.  I'm guessing this is the same underlying problem as #57590 and is fixed by #57594.
