### ISSUE TITLE
Eximing bulletin in faction camp board crashed game.

### ISSUE THREAD

**Issue by NudlaCZ** [CleverRaven/Cataclysm-DDA#57696]
### Describe the bug

My game crashed after I eximed bulletin board in faction camp.

### Steps to reproduce

1. Have faction camp with bulletin board
2. Exime bulletin board

### Expected behavior

I expected that I open faction camp menu.

### Screenshots

![image](https://user-images.githubusercontent.com/61628814/168441776-87c3967d-cb83-4d5c-9676-1800256677c1.png)
![image](https://user-images.githubusercontent.com/61628814/168441795-5a99fa92-4eb8-485e-b1cd-345bbadbcc80.png)

### Versions and configuration

Windows 10
VERSION: 5f60b52
Mods: dda, package_bionic_professions, blazeindustries, crt_expansion, no_hope, No_Rail_Stations, Graphical_Overmap, StatsTroughSkills, speedydex

### Additional context

The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 5f60b52
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

  #0
    (dbghelp: @0x7ff7d5267a10[cataclysm-tiles.exe+0x207a10]), 
    (libbacktrace: debug_write_backtrace(std::ostream&)+0x9e@0x140207a10),
    (libbacktrace: 0x140207a10    [unknown src]:0    [unknown func]),
  #1
    (dbghelp: @0x7ff7d5250b21[cataclysm-tiles.exe+0x1f0b21]), 
    (libbacktrace: log_crash+0x1d2@0x1401f0b21),
    (libbacktrace: 0x1401f0b21    [unknown src]:0    [unknown func]),
  #2
    (dbghelp: @0x7ff7d5250d4f[cataclysm-tiles.exe+0x1f0d4f]), 
    (libbacktrace: signal_handler+0x52@0x1401f0d4f),
    (libbacktrace: 0x1401f0d4f    [unknown src]:0    [unknown func]),
  #3
    (dbghelp: @0x7ff7d5b52852[cataclysm-tiles.exe+0xaf2852]), 
    (libbacktrace: gnu_exception_handler+0x182@0x140af2852),
    (libbacktrace: 0x140af2852    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc11/gcc-11.2.0.build_/mingw-w64-v9.0.0/mingw-w64-crt/crt/crt_handler.c:224    _gnu_exception_handler),
  #4
    (dbghelp: _C_specific_handler+0x98@0x7ffa0bd27ff8[msvcrt.dll+0x27ff8]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #5
    (dbghelp: _chkstk+0x11f@0x7ffa0c11209f[ntdll.dll+0xa209f]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #6
    (dbghelp: RtlRaiseException+0x434@0x7ffa0c0c1454[ntdll.dll+0x51454]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #7
    (dbghelp: KiUserExceptionDispatcher+0x2e@0x7ffa0c110bce[ntdll.dll+0xa0bce]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #8
    (dbghelp: @0x7ff7d5ee1c16[cataclysm-tiles.exe+0xe81c16]), 
    (libbacktrace: mission_id::mission_id(mission_id const&)+0x6@0x140e81c16),
    (libbacktrace: 0x140e81c16    [unknown src]:0    [unknown func]),
  #9
    (dbghelp: @0x7ff7d511842b[cataclysm-tiles.exe+0xb842b]), 
    (libbacktrace: basecamp::is_hidden(ui_mission_id)+0x81@0x1400b842b),
    (libbacktrace: 0x1400b842b    [unknown src]:0    [unknown func]),
  #10
    (dbghelp: @0x7ff7d567c9dd[cataclysm-tiles.exe+0x61c9dd]), 
    (libbacktrace: mission_data::add(ui_mission_id const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool)+0x9f@0x14061c9dd),
    (libbacktrace: 0x14061c9dd    [unknown src]:0    [unknown func]),
  #11
    (dbghelp: @0x7ff7d567cc3b[cataclysm-tiles.exe+0x61cc3b]), 
    (libbacktrace: mission_data::add_start(mission_id const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)+0x5f@0x14061cc3b),
    (libbacktrace: 0x14061cc3b    [unknown src]:0    [unknown func]),
  #12
    (dbghelp: @0x7ff7d530ba6d[cataclysm-tiles.exe+0x2aba6d]), 
    (libbacktrace: basecamp::get_available_missions_by_dir(mission_data&, point const&)+0x3d9@0x1402aba6d),
    (libbacktrace: 0x1402aba6d    [unknown src]:0    [unknown func]),
  #13
    (dbghelp: @0x7ff7d5310b03[cataclysm-tiles.exe+0x2b0b03]), 
    (libbacktrace: basecamp::get_available_missions(mission_data&)+0x967@0x1402b0b03),
    (libbacktrace: 0x1402b0b03    [unknown src]:0    [unknown func]),
  #14
    (dbghelp: @0x7ff7d53c6d80[cataclysm-tiles.exe+0x366d80]), 
    (libbacktrace: iexamine::bulletin_board(Character&, tripoint const&)+0x130@0x140366d80),
    (libbacktrace: 0x140366d80    [unknown src]:0    [unknown func]),
  #15
    (dbghelp: @0x7ff7d537f40e[cataclysm-tiles.exe+0x31f40e]), 
    (libbacktrace: game::examine(tripoint const&, bool)+0x60c@0x14031f40e),
    (libbacktrace: 0x14031f40e    [unknown src]:0    [unknown func]),
  #16
    (dbghelp: @0x7ff7d537fb4a[cataclysm-tiles.exe+0x31fb4a]), 
    (libbacktrace: game::examine(bool)+0x2f4@0x14031fb4a),
    (libbacktrace: 0x14031fb4a    [unknown src]:0    [unknown func]),
  #17
    (dbghelp: @0x7ff7d53ae7b4[cataclysm-tiles.exe+0x34e7b4]), 
    (libbacktrace: game::do_regular_action(action_id&, avatar&, cata::optional<tripoint> const&)+0x1364@0x14034e7b4),
    (libbacktrace: 0x14034e7b4    [unknown src]:0    [unknown func]),
  #18
    (dbghelp: @0x7ff7d53b3d7e[cataclysm-tiles.exe+0x353d7e]), 
    (libbacktrace: game::handle_action()+0xafa@0x140353d7e),
    (libbacktrace: 0x140353d7e    [unknown src]:0    [unknown func]),
  #19
    (dbghelp: @0x7ff7d52b1192[cataclysm-tiles.exe+0x251192]), 
    (libbacktrace: do_turn()+0x533@0x140251192),
    (libbacktrace: 0x140251192    [unknown src]:0    [unknown func]),
  #20
    (dbghelp: @0x7ff7d65417bd[cataclysm-tiles.exe+0x14e17bd]), 
    (libbacktrace: main+0x18fb@0x1414e17bd),
    (libbacktrace: 0x1414e17bd    [unknown src]:0    [unknown func]),
  #21
    (dbghelp: @0x7ff7d50613c1[cataclysm-tiles.exe+0x13c1]), 
    (libbacktrace: _tmainCRTStartup+0x231@0x1400013c1),
    (libbacktrace: 0x1400013c1    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc11/gcc-11.2.0.build_/mingw-w64-v9.0.0/mingw-w64-crt/crt/crtexe.c:323    __tmainCRTStartup),
  #22
    (dbghelp: @0x7ff7d50614d6[cataclysm-tiles.exe+0x14d6]), 
    (libbacktrace: WinMainCRTStartup+0x16@0x1400014d6),
    (libbacktrace: 0x1400014d6    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc11/gcc-11.2.0.build_/mingw-w64-v9.0.0/mingw-w64-crt/crt/crtexe.c:178    WinMainCRTStartup),
  #23
    (dbghelp: BaseThreadInitThunk+0x14@0x7ffa0bc57034[KERNEL32.DLL+0x17034]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #24
    (dbghelp: RtlUserThreadStart+0x21@0x7ffa0c0c2651[ntdll.dll+0x52651]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),

**Comment by PatrikLundell** [comment]
Can you provide a save that demonstrates the issue? It would have to be a link to some external storage service.

**Comment by NudlaCZ** [comment]
1. I built it beacause that spot seemed more practical and it worked fine before I updated.
2. I am pretty sure I didnt.

**Comment by PatrikLundell** [comment]
Thanks for your answers.

I don't think a second bulletin board is a problem: it seems the game is finding and working with any board as long as it's within the center tile.

The reason I asked about hiding missions is because the logic involving that looks to be involved in the stack trace, somehow. I've looked at that code, but can't see anything obviously wrong, so I think a save that can be used for debugging is needed.

**Comment by NudlaCZ** [comment]
https://1drv.ms/u/s!AvjoeYXlzbHPaYCehQnk8VvwX5c

**Comment by PatrikLundell** [comment]
It's a stupid bug. The data structure is set up to be one too small... A PR to fix it will be posted shortly.
