### ISSUE TITLE
Vacuum sealing recipes do not indicate that sealed bags will be used

### ISSUE THREAD

**Issue by toweroglass** [CleverRaven/Cataclysm-DDA#57708]
### Describe the bug

Might be a feature request, but I think when you vacuum seal an item it should let you know if you are going to break the seal of a vacuum sealed bag for the crafted item. Possibly even unsealed items too. I'd rather not fill my inventory with salt and potato chips unless i choose to.

In general this is already done with items containing liquids and i think this should apply to non-water-tight items as well.

### Steps to reproduce

1. vacuum seal some veggy chunks
2. vacuum seal some fruit slices. use the vacuum packed bags it suggests, thinking they are old empties.
3. your veggy chunks are now unsealed and rotting.

### Expected behavior

I would expect not to compromise one seal to achieve another.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1645 (21H2)
- Game Version: aa6a7f8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    No Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries]
]

**Comment by I-am-Erk** [comment]
I think this should be fairly easy to fix by adding a bit of code so that the sealer does not accept an already-in-use bag as a possible ingredient... empty unsealed bags only. It is a silly enough and obnoxious enough bug that I think it should remain a blocker. Please let me know if it's more complex to fix than it appears. If so, we may still be able to add a janky fix for stable.

**Comment by cathalpern** [comment]
I can take a look at this if no one else has picked it up

**Comment by cathalpern** [comment]
Spent a couple hours looking through the relevant code this evening. I can see a couple really hacky ways to fix, but would like to get to root cause on why this works with other recipes, like canning, but not with vacuum sealer ones. Gonna spend some more time on it tomorrow.
