### ISSUE TITLE
Player character randomly lets go of vehicle control while driving

### ISSUE THREAD

**Issue by Heaper327** [CleverRaven/Cataclysm-DDA#57717]
### Describe the bug

While driving a vehicle, the player character sometimes randomly let go of the vehicle control. If this happens while the vehicle is moving, the vehicle will run you over. Pressing the ^ key does not let you regain control of the vehicle. You need to move to another tile and move back to the driver's seat to control the vehicle again.

I suspect that this happens when the weariness level of the character changes while you are driving, but this is just based on my observations.

### Steps to reproduce

1. Load the attached save 
2. Wait a turn
3. Observe how you lose control of the SUV, while consequently runs you over
[bugged save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8694335/bugged.save.zip)

### Expected behavior

You do not lose control of your vehicle randomly and get killed.

### Screenshots

<img width="506" alt="Screen Shot 2022-05-14 at 11 59 01 PM" src="https://user-images.githubusercontent.com/29885616/168457946-adcd1d12-0238-43f9-9a40-e25e6d881486.png">
Vehicle control menu once you lose control

### Versions and configuration

- OS: MacOs
    - OS Version: Darwin Allens-Macbook-2.local 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64
- Game Version: 7a89bbe [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Translate Complex Dialogue [translate_dialogue],
    Bionic Slots [cbm_slots]
]

**Comment by PatrikLundell** [comment]
/confirmed

I'm not able to read the log, so can you tell us what you did immediately prior to the save (might be nothing of interest, of course)? It might be a side effect of something else (I know handing in a quest at the Tacoma farm (and probably elsewhere) while sitting at the driver's seat removes you from being able to control the vehicle as well).

I haven't had this happen to my character when recovering stamina (or any time while actually driving). The character is under the influence of pain killers, but that ought not to have such a severe effect.

**Comment by andrei8l** [comment]
Caused by `EOC_RandEnc_Roadstop_remove`, or more specifically by `mapgen_update` since you happen to be in bounds of the updated map. Introduced by #55021.

Potential fix:
```diff
diff --git a/src/game.cpp b/src/game.cpp
index 307c15715e..b0a1b3075c 100644
--- a/src/game.cpp
+++ b/src/game.cpp
@@ -10209,7 +10209,7 @@ void game::place_player_overmap( const tripoint_abs_omt &om_dest, bool move_play
     for( monster &critter : all_monsters() ) {
         despawn_monster( critter );
     }
-    if( u.in_vehicle ) {
+    if( u.in_vehicle and move_player ) {
         m.unboard_vehicle( u.pos() );
     }
     for( int z = -OVERMAP_DEPTH; z <= OVERMAP_HEIGHT; z++ ) {
```

**Comment by PatrikLundell** [comment]
Hm. this looks like it would also solve #57581 (as I hinted at above).

**Comment by Heaper327** [comment]
> /confirmed
> 
> I'm not able to read the log, so can you tell us what you did immediately prior to the save (might be nothing of interest, of course)? It might be a side effect of something else (I know handing in a quest at the Tacoma farm (and probably elsewhere) while sitting at the driver's seat removes you from being able to control the vehicle as well).
> 
> I haven't had this happen to my character when recovering stamina (or any time while actually driving). The character is under the influence of pain killers, but that ought not to have such a severe effect.

I was just taking apart some humvees next to a free merchant caravan, the latter is probably what triggered the bug.

**Comment by anoobindisguise** [comment]
This is probably what's causing #55176 also.
