### ISSUE TITLE
Turret mount cannot be disassembled for parts

### ISSUE THREAD

**Issue by jeffplata** [CleverRaven/Cataclysm-DDA#57714]
### Describe the bug

Turret mount cannot be disassembled for parts using the '(' key for Disassemble menu, regardless if it's in the inventory or wielded or nearby.

### Steps to reproduce

Easy.

### Expected behavior

It should be possible to disassemble the turret mount. It's a source for parts.

### Versions and configuration

- OS: Windows
    - OS Version: 6.3 9600
- Game Version: 7a89bbe [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Hunting for tiny electric motors. There are numerous turret mounts around. What a waste.

**Comment by Night-Pryanik** [comment]
Turret mount is just a piece of stamped metal to put the gun onto. It doesn't have any motors in its structure.

**Comment by jeffplata** [comment]
The turret mount is craftable with various materials including 2 tiny electric motors, and like other craftable items I thought the player may be able to recover some or all of the materials used. The description does not mention disassembly details though. If it is intentional that disassembly is not allowed, then I rest my case. I just hope this lingering question will be answered someday: Why?

**Comment by Night-Pryanik** [comment]
Oh, sorry. Was looking at older version that didn't have any motor.

The answer is simple: it's just an oversight.
