### ISSUE TITLE
Military explosive homemade grenades do not explode

### ISSUE THREAD

**Issue by toweroglass** [CleverRaven/Cataclysm-DDA#57735]
### Describe the bug

I noticed military explosive homemade grenades, including the small ones, do not explode.
I opened my test character even held the grenade while it was active and got this:
![grenade bug](https://user-images.githubusercontent.com/81603517/168501139-0e75a555-ebb9-4b2e-8ac5-e285bc48da95.png)
and the grenade was gone

### Steps to reproduce

1. spawn a military explosive homemade grenade or military explosive small homemade grenade and a lighter.
2. activate the grenade
3. throw it or not, it just disappears.

### Expected behavior

i would expect it to explode.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1706 (21H2)
- Game Version: d5502cf [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    No Fungal Growth [no_fungal_growth]
]

**Comment by catdach** [comment]
Looks like the explosive data for those grenades aren't included in the active transformation of the item. Should be an easy fix.

**Comment by toweroglass** [comment]
> Looks like the explosive data for those grenades aren't included in the active transformation of the item. Should be an easy fix.

awesome! i was throwing grenade after grenade into a dark room before testing this lol.
