### ISSUE TITLE
Crashed while walking [Experimental]

### ISSUE THREAD

**Issue by lbnesquik** [CleverRaven/Cataclysm-DDA#57733]
### Describe the bug

I was walking, and i received a crash.
I did not update to latest before booting up, but it wasn't an set of files.

### Steps to reproduce

There was nothing special going on besides walking.

### Expected behavior

No crash.

### Screenshots

![image](https://user-images.githubusercontent.com/24830358/168495754-8d2f524e-9ff8-4296-a090-23fe24bf8526.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1706 (21H1)
- Game Version: ea157f5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Here is the crash & debug log zipped together.

[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8696117/config.zip)

**Comment by RoyBerube** [comment]
Looks like it happens during an auto save. It tries to serialize a player activity and can't find the _item_location_.  Possible cause PR #57625
