### ISSUE TITLE
Turning Logs in to planks does not give skill experience

### ISSUE THREAD

**Issue by aMegaSloth** [CleverRaven/Cataclysm-DDA#57746]
### Describe the bug

I was testing out power tools vs normal tools. Specifically The chainsaw vs bow saw to see what would yield more planks.

Surprise surprise they yield the same but it is dependent on the Fabrication skill.

So 0 fab tend to make a lot of 'wasted wood' message in red. 10 fab skill gets the 'perfect' yield of 10 planks.

Where am I headed with this? At 0 fab skill sawing 40 logs, I got 0 fab 0% skill gain. It seems like one should be gaining fab skills cutting wood over time? Logically one would start to get better a turning logs into planks if they do it enough times.

### Steps to reproduce

1. Start new world.
2. Roll basic 8/8/8/8 character, doesnt matter really
3. Observe fab skill at 0.
4. Debug spawn any amount of logs, and a wood sawing tool
5. Saw logs
6. Check character sheet, still shows 0/0% fab.

### Expected behavior

I expect to slowly gain Fab skill from turn logs into planks. The error message about "you waste a lot of wood" seems to indicate something can be done about it as well. I figured I'd be getting better over time sawing logs, but it doesn't seem to be the case.

### Versions and configuration

Using latest experimental;

cdda-experimental-2022-05-16-0602 

[cdda-windows-tiles-x64-msvc-2022-05-16-0602.zip](https://github.com/CleverRaven/Cataclysm-DDA/releases/download/cdda-experimental-2022-05-16-0602/cdda-windows-tiles-x64-msvc-2022-05-16-0602.zip)

**Comment by Golfavel** [comment]
I can confirm; cut over 10 logs, got no experience.
