### ISSUE TITLE
XL holster / XS holster oversight

### ISSUE THREAD

**Issue by toweroglass** [CleverRaven/Cataclysm-DDA#57755]
### Describe the bug

There is an XS holster item which is a smaller version of the XL holster. the problem being that the XL holster isn't specifically for large anatomy. It is for large **guns**. So now we have an extra small version of a large gun holster, but no normal size version.

I think someone went a little overboard implementing XS clothing, but I also think the name for XL holster might need to be tweaked a little since XL _usually_ indicates large anatomy.

### Steps to reproduce

1. look at the available holsters
2. are you looking at the holsters?

### Expected behavior

If the XL holster is intended to only be for large anatomy then i would expect there would not be an XS version. That sounds reasonable. Otherwise there would need to be an in the middle version.

### Versions and configuration

I'm up to date as of yesterday. I'm at work and just remembered to post this bug report. If this is really necessary I can fill it out later.

**Comment by catdach** [comment]
Looks like it happened back in #54322. Similarly the `rifle_case_xs_soft_leather` seems wrong, as it is proportional to the normal leather rifle case but is just called "long leather rifle case", they probably didn't realize that XL in `rifle_case_xl_soft_leather` meant extra long.

**Comment by toweroglass** [comment]
that's funny. i looked both of those up and they both have the OVERSIZE _and_ UNDERSIZE tags.

**Comment by catdach** [comment]
Yea, I think they need the OVERSIZE tag to prevent them from conflicting with tail mutations maybe? It's really strange.
