### ISSUE TITLE
Game segfaults when removing engine from mostly dismantled car.

### ISSUE THREAD

**Issue by Tearlach** [CleverRaven/Cataclysm-DDA#57759]
### Describe the bug

I've been having a issue with the game randomly segfaulting for a while now, has persisted between moving the save between versions. Finally found what was doing it, when npcs or my character attempts to remove a engine from a car the game segfaults

### Steps to reproduce

1)Unzip and load the save.
2)Interact South
3)Remove the engin
[Bennetts Mills.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8702548/Bennetts.Mills.zip)
e

### Expected behavior

Not segfaulting I guess?

### Versions and configuration

Windows 10
7a89bbe
Tiles
English language or system default.
Disable NPC needs, No fungal growth, Bionic Professions, Dinomod, Bionic Slots, Stats Through Skills, Stats through kills.

### Additional context

[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8702573/config.zip)

**Comment by andrei8l** [comment]
I'm only seeing the assertion failure in the tidy activity and cannot reproduce the other scenarios if I (for ex) kill the busy NPCs. The crash log from OP also shows only a SIGABRT rather than a SIGSEGV. Can you please try with the patch above and see if you can still reproduce?

**Comment by Tearlach** [comment]
Yeah, I can try. How would I go ahead to use the patch you linked? will I have to compile my own version or can I sneak in the code somehow?

**Comment by andrei8l** [comment]
Use one of the builds [here](https://github.com/andrei8l/Cataclysm-DDA/releases/tag/cdda-experimental-2022-05-17-0556). If your platform isn't in the list, just wait a couple more minutes.
